### ISSUE TITLE
[ICE] with lines()

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#100198]
This reduced code:

```rust
fn main() {
    let _ =
    "0"
    .lines()
    .map(|r| r
             .split_whitespace()
             .map(|s| s.parse::<u32>().unwrap())
             .collect::<Vec<_>>())
    .reduce(|x, y| y.iter().zip(x)
                   .map(|(a, b)| a + b)
                   .collect());
}
```

Gives:

```
thread 'rustc' panicked at 'invalid enum variant tag while decoding `ExpnKind`, expected 0..5', /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154\compiler\rustc_span\src\hygiene.rs:1045:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library\std\src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library\core\src/panicking.rs:142:14
   2: <rustc_span::hygiene::ExpnData as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <rustc_span::hygiene::ExpnId as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_span::hygiene::SyntaxContextData as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   5: <rustc_span::hygiene::SyntaxContext as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   6: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   7: <alloc::vec::Vec<rustc_middle::mir::Statement> as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   8: <rustc_middle::mir::BasicBlockData as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   9: <alloc::vec::Vec<rustc_middle::mir::BasicBlockData> as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
  10: <rustc_middle::mir::Body as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
  11: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir
  12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, &rustc_middle::mir::Body>>
  13: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt>
  14: <rustc_middle::ty::context::TyCtxt>::instance_mir
  15: rustc_monomorphize::collector::collect_neighbours
  16: rustc_monomorphize::collector::collect_items_rec
  17: rustc_monomorphize::collector::collect_items_rec
  18: rustc_monomorphize::collector::collect_items_rec
  19: rustc_monomorphize::collector::collect_items_rec
  20: rustc_monomorphize::collector::collect_items_rec
  21: rustc_monomorphize::collector::collect_items_rec
  22: rustc_monomorphize::collector::collect_items_rec
  23: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
  24: rustc_data_structures::sync::par_for_each_in::<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  25: <rustc_session::session::Session>::time::<(), rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}>
  26: rustc_monomorphize::collector::collect_crate_mono_items
  27: rustc_monomorphize::partitioning::collect_and_partition_mono_items
  28: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>>
  29: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::collect_and_partition_mono_items, rustc_query_impl::plumbing::QueryCtxt>
  30: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items
  31: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  32: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  33: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  34: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  35: <rustc_interface::queries::Queries>::ongoing_codegen
  36: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  37: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (affe0d3a0 2022-08-05) running on x86_64-pc-windows-gnu

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

Using:

```
rustc 1.64.0-nightly (affe0d3a0 2022-08-05)
binary: rustc
commit-hash: affe0d3a00e92fa7885e3f5d2c5073fde432d154
commit-date: 2022-08-05
host: x86_64-pc-windows-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

**Comment by SNCPlay42** [comment]
I haven't been able to reproduce this, even on the exact toolchain being used (`x86_64-pc-windows-gnu`). The code builds without ICE, and - modified to produce output and given different input - appears to produce correct results.

Judging by the message and stack trace, this is due to a broken .rmeta/.rlib file. Is this being built as a cargo project with any dependencies? Otherwise I think maybe your toolchain's installation has been corrupted somehow.

**Comment by leonardo-m** [comment]
It was built with just rustc (so with zero dependencies).

**Comment by ChrisDenton** [comment]
Hm, I'm also unable to reproduce with nightly `rustc`:

```
Z:\test> rustc +nightly-gnu --version --verbose
rustc 1.64.0-nightly (affe0d3a0 2022-08-05)
binary: rustc
commit-hash: affe0d3a00e92fa7885e3f5d2c5073fde432d154
commit-date: 2022-08-05
host: x86_64-pc-windows-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
Z:\test> cat main.rs
fn main() {
    let _ =
    "0"
    .lines()
    .map(|r| r
             .split_whitespace()
             .map(|s| s.parse::<u32>().unwrap())
             .collect::<Vec<_>>())
    .reduce(|x, y| y.iter().zip(x)
                   .map(|(a, b)| a + b)
                   .collect());
}

Z:\test> rustc +nightly-gnu main.rs
Z:\test>
```

Are there some command line arguments I should be trying?

**Comment by leonardo-m** [comment]
> Are there some command line arguments I should be trying?

I'm just using:

    rustc test.rs

**Comment by ChrisDenton** [comment]
Huh, weird that we're getting different results. I'm currently unable to figure out why.

**Comment by leonardo-m** [comment]
It isn't your fault ChrisDenton, thank you for helping :-)
 SNCPlay42 wrote "maybe your toolchain's installation has been corrupted somehow". So let's wait for the successive Nightly. I several years I've seen many weird things with rustc :-)

**Comment by leonardo-m** [comment]
The last Nightly doesn't have this problem...
