### ISSUE TITLE
ICE with multiple attributes on a test function

### ISSUE THREAD

**Issue by HaimYosefHaim** [rust-lang/rust#100263]
Error happened when I added the `test_case` attribute from the `test-case` crate without adding the required `use`.

### Code

main.rs -
```Rust
#[cfg(test)]
mod tests {
    #[test_case]
    #[tokio::test]
    async fn foo() {}
}
```

Cargo.toml -
```toml
[dev-dependencies]
tokio = { version = "*", features = ["macros"] }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-unknown-linux-gnu
release: 1.62.1
LLVM version: 14.0.5
```
Same error occurs on the latest nightly.

### Error output

```
error[E0658]: use of unstable library feature 'custom_test_frameworks': custom test frameworks are an unstable feature
 --> src/main.rs:4:7
  |
4 |     #[test_case]
  |       ^^^^^^^^^
  |
  = note: see issue #50297 <https://github.com/rust-lang/rust/issues/50297> for more information
  = help: add `#![feature(custom_test_frameworks)]` to the crate attributes to enable

thread 'rustc' panicked at 'attribute is missing tokens: Attribute { kind: Normal(AttrItem { path: Path { span: src/main.rs:4:5: 4:17 (#4), segments: [PathSegment { ident: rustc_test_marker#4, id: NodeId(4294967040), args: None }], tokens: None }, args: Empty, tokens: None }, None), id: AttrId(38), style: Outer, span: src/main.rs:4:5: 4:17 (#4) }', compiler/rustc_ast/src/attr/mod.rs:305:36
stack backtrace:
   0:     0x7faa3c05fc60 - std::backtrace_rs::backtrace::libunwind::trace::h60bf900414c5dcf2
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7faa3c05fc60 - std::backtrace_rs::backtrace::trace_unsynchronized::habfc3ef92583c158
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7faa3c05fc60 - std::sys_common::backtrace::_print_fmt::hae196fe4153d0b63
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7faa3c05fc60 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h08f9c50f850514f5
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7faa3c0bb62c - core::fmt::write::hcd15d2c673b5a9c1
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/fmt/mod.rs:1198:17
   5:     0x7faa3c050ca5 - std::io::Write::write_fmt::h417be4d25b915a22
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/io/mod.rs:1672:15
   6:     0x7faa3c062941 - std::sys_common::backtrace::_print::h95ab226f37d571aa
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7faa3c062941 - std::sys_common::backtrace::print::hc77fb9ed6b2eeb3d
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7faa3c062941 - std::panicking::default_hook::{{closure}}::hca418bd67097eb22
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:295:22
   9:     0x7faa3c06260e - std::panicking::default_hook::h1df4f10c6ed28c53
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:314:9
  10:     0x7faa3e8e37a4 - rustc_driver[6a784e82872844b3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7faa3c063176 - std::panicking::rust_panic_with_hook::hf1e7a1cb721a9823
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:702:17
  12:     0x7faa3c062fc7 - std::panicking::begin_panic_handler::{{closure}}::h573a00e95ce9340d
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:588:13
  13:     0x7faa3c060184 - std::sys_common::backtrace::__rust_end_short_backtrace::h597b7803117e52fd
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7faa3c062cf2 - rust_begin_unwind
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:584:5
  15:     0x7faa3c0b8103 - core::panicking::panic_fmt::h62ccf03c8a8a51b5
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:142:14
  16:     0x7faa3fa8266c - <rustc_ast[b2d367319fec95a3]::ast::Attribute>::tokens::{closure#0}
  17:     0x7faa3e23b109 - <&mut <rustc_ast[b2d367319fec95a3]::tokenstream::AttrAnnotatedTokenStream>::to_tokenstream::{closure#0} as core[480a4b334008baa8]::ops::function::FnOnce<(&(rustc_ast[b2d367319fec95a3]::tokenstream::AttrAnnotatedTokenTree, rustc_ast[b2d367319fec95a3]::tokenstream::Spacing),)>>::call_once
  18:     0x7faa3e239e51 - <alloc[37570755f066325e]::vec::Vec<rustc_ast[b2d367319fec95a3]::tokenstream::TokenTree> as alloc[37570755f066325e]::vec::spec_from_iter::SpecFromIter<rustc_ast[b2d367319fec95a3]::tokenstream::TokenTree, core[480a4b334008baa8]::iter::adapters::flatten::FlatMap<core[480a4b334008baa8]::slice::iter::Iter<(rustc_ast[b2d367319fec95a3]::tokenstream::AttrAnnotatedTokenTree, rustc_ast[b2d367319fec95a3]::tokenstream::Spacing)>, smallvec[d5266849f68e525]::IntoIter<[rustc_ast[b2d367319fec95a3]::tokenstream::TokenTree; 1usize]>, <rustc_ast[b2d367319fec95a3]::tokenstream::AttrAnnotatedTokenStream>::to_tokenstream::{closure#0}>>>::from_iter
  19:     0x7faa3e386993 - <rustc_ast[b2d367319fec95a3]::tokenstream::AttrAnnotatedTokenStream>::to_tokenstream
  20:     0x7faa3e386505 - <rustc_ast[b2d367319fec95a3]::tokenstream::TokenStream>::from_ast::<rustc_ast[b2d367319fec95a3]::ptr::P<rustc_ast[b2d367319fec95a3]::ast::Item>>
  21:     0x7faa3e278ee0 - <rustc_expand[7f20985625ea9680]::expand::MacroExpander>::fully_expand_fragment
  22:     0x7faa3e0dc8bb - <rustc_expand[7f20985625ea9680]::expand::MacroExpander>::expand_crate
  23:     0x7faa3e0dba45 - <rustc_session[3a7027c0efaeda76]::session::Session>::time::<core[480a4b334008baa8]::result::Result<rustc_ast[b2d367319fec95a3]::ast::Crate, rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_interface[b6374d447bec2332]::passes::configure_and_expand::{closure#1}>
  24:     0x7faa3e0d61f4 - <rustc_interface[b6374d447bec2332]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[b6374d447bec2332]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[480a4b334008baa8]::result::Result<rustc_ast[b2d367319fec95a3]::ast::Crate, rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>
  25:     0x7faa3e0c80fd - <rustc_interface[b6374d447bec2332]::queries::Queries>::expansion
  26:     0x7faa3e0c58ed - <rustc_interface[b6374d447bec2332]::interface::Compiler>::enter::<rustc_driver[6a784e82872844b3]::run_compiler::{closure#1}::{closure#2}, core[480a4b334008baa8]::result::Result<core[480a4b334008baa8]::option::Option<rustc_interface[b6374d447bec2332]::queries::Linker>, rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>
  27:     0x7faa3e0b946a - rustc_span[50cf38d84baf6853]::with_source_map::<core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_interface[b6374d447bec2332]::interface::create_compiler_and_run<core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_driver[6a784e82872844b3]::run_compiler::{closure#1}>::{closure#1}>
  28:     0x7faa3e0b8e40 - rustc_interface[b6374d447bec2332]::interface::create_compiler_and_run::<core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_driver[6a784e82872844b3]::run_compiler::{closure#1}>
  29:     0x7faa3e0b71b1 - <scoped_tls[3d37162c759ef368]::ScopedKey<rustc_span[50cf38d84baf6853]::SessionGlobals>>::set::<rustc_interface[b6374d447bec2332]::interface::run_compiler<core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_driver[6a784e82872844b3]::run_compiler::{closure#1}>::{closure#0}, core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>
  30:     0x7faa3e0b6e9f - std[c5ae6ddbbc7a9ee8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b6374d447bec2332]::util::run_in_thread_pool_with_globals<rustc_interface[b6374d447bec2332]::interface::run_compiler<core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_driver[6a784e82872844b3]::run_compiler::{closure#1}>::{closure#0}, core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>::{closure#0}, core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>
  31:     0x7faa3e70bc29 - <<std[c5ae6ddbbc7a9ee8]::thread::Builder>::spawn_unchecked_<rustc_interface[b6374d447bec2332]::util::run_in_thread_pool_with_globals<rustc_interface[b6374d447bec2332]::interface::run_compiler<core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>, rustc_driver[6a784e82872844b3]::run_compiler::{closure#1}>::{closure#0}, core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>::{closure#0}, core[480a4b334008baa8]::result::Result<(), rustc_errors[a2987978d4b02d94]::ErrorGuaranteed>>::{closure#1} as core[480a4b334008baa8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7faa3c06d143 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hede4885ee64a1fac
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/alloc/src/boxed.rs:1935:9
  33:     0x7faa3c06d143 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h06c745de9f474954
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/alloc/src/boxed.rs:1935:9
  34:     0x7faa3c06d143 - std::sys::unix::thread::Thread::new::thread_start::h529a493f2fb191b6
                               at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7faa3bf2e609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  36:     0x7faa3be51133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (d394408fb 2022-08-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
For more information about this error, try `rustc --explain E0658`.
error: could not compile `ice` due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'attribute is missing tokens: Attribute { kind: Normal(AttrItem { path: Path { span: src/main.rs:3:5: 3:17 (#4), segments: [PathSegment { ident: rustc_test_marker#4, id: NodeId(4294967040), args: None }], tokens: None }, args: Empty, tokens: None }, None), id: AttrId(38), style: Outer, span: src/main.rs:3:5: 3:17 (#4) }', compiler/rustc_ast/src/attr/mod.rs:305:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: <&mut <rustc_ast::tokenstream::AttrAnnotatedTokenStream>::to_tokenstream::{closure#0} as core::ops::function::FnOnce<(&(rustc_ast::tokenstream::AttrAnnotatedTokenTree, rustc_ast::tokenstream::Spacing),)>>::call_once
   3: <alloc::vec::Vec<(rustc_ast::tokenstream::TokenTree, rustc_ast::tokenstream::Spacing)> as alloc::vec::spec_from_iter::SpecFromIter<(rustc_ast::tokenstream::TokenTree, rustc_ast::tokenstream::Spacing), core::iter::adapters::flatten::FlatMap<core::slice::iter::Iter<(rustc_ast::tokenstream::AttrAnnotatedTokenTree, rustc_ast::tokenstream::Spacing)>, smallvec::IntoIter<[(rustc_ast::tokenstream::TokenTree, rustc_ast::tokenstream::Spacing); 1]>, <rustc_ast::tokenstream::AttrAnnotatedTokenStream>::to_tokenstream::{closure#0}>>>::from_iter
   4: <rustc_ast::tokenstream::AttrAnnotatedTokenStream>::to_tokenstream
   5: rustc_parse::prepend_attrs
   6: rustc_parse::to_token_stream::<rustc_ast::ptr::P<rustc_ast::ast::Item>>
   7: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
   8: <rustc_expand::expand::MacroExpander>::expand_crate
   9: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>, rustc_interface::passes::configure_and_expand::{closure#1}>
  10: rustc_interface::passes::configure_and_expand
  11: <rustc_interface::queries::Queries>::expansion
  12: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  13: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  14: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  15: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.1 (e092d0b6b 2022-07-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
For more information about this error, try `rustc --explain E0658`.
error: could not compile `ice` due to previous error
```

</p>
</details>

**Comment by clubby789** [comment]
Doesn't require nightly, will ICE on stable (just with a feature error beforehand)
