### ISSUE TITLE
'assertion failed: !span.inner().is_dummy()',

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#100454]
Found in [Rollup CI](https://github.com/rust-lang-ci/rust/runs/7806183078?check_suite_focus=true)
of [Rollup](https://github.com/rust-lang/rust/pull/100449#issuecomment-1213091420)

### Error output

```
 thread 'rustc' panicked at 'assertion failed: !span.inner().is_dummy()', src/librustdoc/html/render/context.rs:308:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>
```
thread 'rustc' panicked at 'assertion failed: !span.inner().is_dummy()', src/librustdoc/html/render/context.rs:308:9

stack backtrace:

   0:     0x7f21fb0dab1e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h45188f431115ce78

   1:     0x7f21fb13f539 - core::fmt::write::h116c5eafcc7364ca

   2:     0x7f21fb0cc151 - std::io::Write::write_fmt::hbbb87d55185d6ee7

   3:     0x7f21fb0dd948 - std::panicking::default_hook::{{closure}}::h033da0a33e6313e3

   4:     0x7f21fb0dd6aa - std::panicking::default_hook::hcc545e2135551ce9

   5:     0x7f21fc378364 - rustc_driver[c7963b40d229c8e3]::DEFAULT_HOOK::{closure#0}::{closure#0}

   6:     0x7f21fb0de0ea - std::panicking::rust_panic_with_hook::hd03a5bf0149f909a
   
7:     0x7f21fb0dded1 - std::panicking::begin_panic_handler::{{closure}}::hdc278d8f44697e69

   8:     0x7f21fb0db0bc - std::sys_common::backtrace::__rust_end_short_backtrace::hc791c42069729ead

   9:     0x7f21fb0ddbe2 - rust_begin_unwind

  10:     0x7f21fb094123 - core::panicking::panic_fmt::h17e348f497692bdf

  11:     0x7f21fb093fed - core::panicking::panic::hd45a1628a1e55d64

  12:     0x563c36d13401 - <rustdoc[680b4809a76ead34]::html::render::context::Context>::href_from_span

  13:     0x563c36cab860 - rustdoc[680b4809a76ead34]::html::render::print_item::print_item

  14:     0x563c36d1195d - <rustdoc[680b4809a76ead34]::html::render::context::Context>::render_item

  15:     0x563c36d18174 - <rustdoc[680b4809a76ead34]::html::render::context::Context as 
rustdoc[680b4809a76ead34]::formats::renderer::FormatRenderer>::mod_item_in

  16:     0x563c36d0f552 - rustdoc[680b4809a76ead34]::formats::renderer::run_format::
<rustdoc[680b4809a76ead34]::html::render::context::Context>

  17:     0x563c36b247d2 - rustdoc[680b4809a76ead34]::run_renderer::
<rustdoc[680b4809a76ead34]::html::render::context::Context>

  18:     0x563c36d57708 - <rustc_session[e9c8f298f1b7236a]::session::Session>::time::<core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>, rustdoc[680b4809a76ead34]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#1}>

  19:     0x563c36c31929 - <rustc_interface[61b2afca71575b98]::passes::QueryContext>::enter::<rustdoc[680b4809a76ead34]::main_options::{closure#0}::{closure#0}::{closure#1}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>

  20:     0x563c36b27820 - <rustc_interface[61b2afca71575b98]::interface::Compiler>::enter::<rustdoc[680b4809a76ead34]::main_options::{closure#0}::{closure#0}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>

  21:     0x563c36e2ce00 - rustc_span[45192a7c83250c40]::with_source_map::<core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>, rustc_interface[61b2afca71575b98]::interface::create_compiler_and_run<core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>, rustdoc[680b4809a76ead34]::main_options::{closure#0}>::{closure#1}>

  22:     0x563c36b29ec7 - rustc_interface[61b2afca71575b98]::interface::create_compiler_and_run::<core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>, rustdoc[680b4809a76ead34]::main_options::{closure#0}>

  23:     0x563c36b25ad4 - rustdoc[680b4809a76ead34]::main_options

  24:     0x563c36bcd2cc - <scoped_tls[a42e1a363a0b09d3]::ScopedKey<rustc_span[45192a7c83250c40]::SessionGlobals>>::set::<rustdoc[680b4809a76ead34]::main_args::{closure#0}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>

  25:     0x563c36d3ef50 - std[bb1f12c364247fc7]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[61b2afca71575b98]::util::run_in_thread_pool_with_globals<rustdoc[680b4809a76ead34]::main_args::{closure#0}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>::{closure#0}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>

  26:     0x563c36c55df8 - <<std[bb1f12c364247fc7]::thread::Builder>::spawn_unchecked_<rustc_interface[61b2afca71575b98]::util::run_in_thread_pool_with_globals<rustdoc[680b4809a76ead34]::main_args::{closure#0}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>::{closure#0}, core[82c21f9469e02c02]::result::Result<(), rustc_errors[398c4e0d74a5685a]::ErrorGuaranteed>>::{closure#1} as core[82c21f9469e02c02]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}

  27:     0x7f21fb0e9c85 - std::sys::unix::thread::Thread::new::thread_start::he40f12d1049c6b05

  28:     0x7f21fae106ba - start_thread

  29:     0x7f21fa62751d - clone

  30:                0x0 - <unknown>

error: internal compiler error: unexpected panic


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md


note: rustc 1.65.0-nightly (6d60e5b24 2022-08-12) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `foo`
```
</p>
</details>

**Comment by matthiaskrgr** [comment]
Hm i would guess this is caused by #100409 ?

**Comment by Dylan-DPC** [comment]
yes 

though there is also https://github.com/rust-lang/rust/pull/100299 in the same rollup

**Comment by GuillaumeGomez** [comment]
I think it's #100299, #100409 doesn't change the span in this "region".

**Comment by jyn514** [comment]
this is an ICE from an unmerged PR
