### ISSUE TITLE
ICE: called `Option::unwrap()` on a `None` value, compiler/rustc_metadata/src/rmeta/decoder.rs

### ISSUE THREAD

**Issue by Ajkcki** [rust-lang/rust#100715]
This happened when `cargo build` substrate (https://github.com/paritytech/substrate)

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08) running on x86_64-unknown-linux-gnu
```

`OS Info`:
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:1382:75
stack backtrace:
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x4fa9f3)[0x7ff376aa49f3]
/lib64/libpthread.so.0(+0x10140)[0x7ff375c13140]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x4fa9f3)[0x7fa08a5689f3]
/lib64/libpthread.so.0(+0x10140)[0x7fa0896d7140]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x1ff986e)[0x7ff3785a386e]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x1ff986e)[0x7fa08c06786e]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0xe7964b)[0x7ff37742364b]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0xe7964b)[0x7fa08aee764b]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x205b6fb)[0x7ff3786056fb]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x205b6fb)[0x7fa08c0c96fb]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b54910)[0x7ff3790fe910]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b54910)[0x7fa08cbc2910]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b61d6b)[0x7fa08cbcfd6b]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b61d6b)[0x7ff37910bd6b]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b4e4f6)[0x7ff3790f84f6]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b4e4f6)[0x7fa08cbbc4f6]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2bc9e41)[0x7fa08cc37e41]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2bc9e41)[0x7ff379173e41]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b1a8a5)[0x7fa08cb888a5]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2b1a8a5)[0x7ff3790c48a5]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x1ff279f)[0x7fa08c06079f]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x1ff279f)[0x7ff37859c79f]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(_RNvXs0_NtCslrRcAmyW1aA_16rustc_query_impl13on_disk_cacheNtB5_11OnDiskCacheNtNtNtCs9eX4qU5f535_12rustc_middle2ty7context11OnDiskCache9serialize+0x5f)[0x7fa08cbb3dff]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(_RNvXs0_NtCslrRcAmyW1aA_16rustc_query_impl13on_disk_cacheNtB5_11OnDiskCacheNtNtNtCs9eX4qU5f535_12rustc_middle2ty7context11OnDiskCache9serialize+0x5f)[0x7ff3790efdff]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(_RNvMs9_NtNtCs9eX4qU5f535_12rustc_middle2ty7contextNtB5_6TyCtxt28serialize_query_result_cache+0x80)[0x7fa08cf8de20]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(_RNvMs9_NtNtCs9eX4qU5f535_12rustc_middle2ty7contextNtB5_6TyCtxt28serialize_query_result_cache+0x80)[0x7ff3794c9e20]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cce0cc)[0x7fa08cd3c0cc]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cce0cc)[0x7ff3792780cc]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cd35bf)[0x7fa08cd415bf]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cd35bf)[0x7ff37927d5bf]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cce2ba)[0x7fa08cd3c2ba]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cce2ba)[0x7ff3792782ba]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cd045d)[0x7fa08cd3e45d]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cd045d)[0x7ff37927a45d]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cd7bc2)[0x7ff379281bc2]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x2cd7bc2)[0x7fa08cd45bc2]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(_RNvNtNtCs2TwaD1okL0n_17rustc_incremental7persist4save14save_dep_graph+0x11)[0x7ff37927a7f1]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(_RNvNtNtCs2TwaD1okL0n_17rustc_incremental7persist4save14save_dep_graph+0x11)[0x7fa08cd3e7f1]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26aca52)[0x7ff378c56a52]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26aca52)[0x7fa08c71aa52]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26af60a)[0x7ff378c5960a]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26af60a)[0x7fa08c71d60a]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26a8a7f)[0x7ff378c52a7f]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26a8a7f)[0x7fa08c716a7f]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26b0302)[0x7ff378c5a302]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26b0302)[0x7fa08c71e302]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26d399f)[0x7ff378c7d99f]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26d399f)[0x7fa08c74199f]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26c5529)[0x7ff378c6f529]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/libstd-8f1929c73c3f8167.so(rust_metadata_std_f9ee9c7d4fd68eda+0xab463)[0x7ff3762d8463]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-d680884a73809b24.so(+0x26c5529)[0x7fa08c733529]
/lib64/libpthread.so.0(+0x81a3)[0x7ff375c0b1a3]
/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/libstd-8f1929c73c3f8167.so(rust_metadata_std_f9ee9c7d4fd68eda+0xab463)[0x7fa089d9c463]
/lib64/libc.so.6(clone+0x6d)[0x7ff37593dfad]
/lib64/libpthread.so.0(+0x81a3)[0x7fa0896cf1a3]
/lib64/libc.so.6(clone+0x6d)[0x7fa089401fad]
error: could not compile `frame-system-rpc-runtime-api`

Caused by:
  process didn't exit successfully: `rustc --crate-name frame_system_rpc_runtime_api --edition=2021 frame/system/rpc/runtime-api/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=979075f452cb5906 -C extra-filename=-979075f452cb5906 --out-dir /Projects/substrate/target/debug/deps -C incremental=/Projects/substrate/target/debug/incremental -L dependency=/Projects/substrate/target/debug/deps --extern codec=/Projects/substrate/target/debug/deps/libparity_scale_codec-bfb854ea19c8e7bd.rmeta --extern sp_api=/Projects/substrate/target/debug/deps/libsp_api-d0ef273dfdcfc5ba.rmeta -L native=/Projects/substrate/target/debug/build/secp256k1-sys-2c7c48dfccd0c22b/out -L native=/Projects/substrate/target/debug/build/psm-6fdb5a0533e99f20/out -L native=/Projects/substrate/target/debug/build/zstd-sys-4d84a2f1f227b0ef/out -L native=/Projects/substrate/target/debug/build/wasmtime-runtime-93ab5baf8f1588a4/out` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: could not compile `pallet-nomination-pools-runtime-api`

Caused by:
  process didn't exit successfully: `rustc --crate-name pallet_nomination_pools_runtime_api --edition=2021 frame/nomination-pools/runtime-api/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=ba7457ac58659e09 -C extra-filename=-ba7457ac58659e09 --out-dir /Projects/substrate/target/debug/deps -C incremental=/Projects/substrate/target/debug/incremental -L dependency=/Projects/substrate/target/debug/deps --extern codec=/Projects/substrate/target/debug/deps/libparity_scale_codec-bfb854ea19c8e7bd.rmeta --extern sp_api=/Projects/substrate/target/debug/deps/libsp_api-d0ef273dfdcfc5ba.rmeta --extern sp_std=/Projects/substrate/target/debug/deps/libsp_std-dedbfbb50d345310.rmeta -L native=/Projects/substrate/target/debug/build/secp256k1-sys-2c7c48dfccd0c22b/out -L native=/Projects/substrate/target/debug/build/psm-6fdb5a0533e99f20/out -L native=/Projects/substrate/target/debug/build/zstd-sys-4d84a2f1f227b0ef/out -L native=/Projects/substrate/target/debug/build/wasmtime-runtime-93ab5baf8f1588a4/out` (signal: 11, SIGSEGV: invalid memory reference)
   0:     0x7f6f7083918d - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f6f7083918d - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6f7083918d - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f6f7083918d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f6f70894f7c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x7f6f7082a8a1 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x7f6f7083be55 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f6f7083be55 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f6f7083be55 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x7f6f7083bb76 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x7f6f71016b54 - rustc_driver[e01eec72899701d3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f6f4f1f47e3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9d4f6bc8e4409391
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1965:9
  12:     0x7f6f4f1f23ed - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h7fb9c8e38b87a365
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/proc_macro/src/bridge/client.rs:328:21
  13:     0x7f6f7083c52a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  14:     0x7f6f7083c329 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  15:     0x7f6f70839644 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7f6f7083c099 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  17:     0x7f6f70801253 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  18:     0x7f6f7080111d - core::panicking::panic::h467ee1bf554babeb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  19:     0x7f6f72cbed9d - <rustc_metadata[182445ef63e063fe]::creader::CStore as rustc_session[72c90254a58d88d1]::cstore::CrateStore>::def_key
  20:     0x7f6f731310bd - <rustc_middle[6ba33e07887d312d]::ty::context::TyCtxt>::def_key
  21:     0x7f6f72374372 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::namespace::item_namespace
  22:     0x7f6f723ada51 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_di_node
  23:     0x7f6f723b759f - <&mut rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_variant_struct_type_di_node::{closure#0}::{closure#0} as core[3edb0f9afb6adb32]::ops::function::FnOnce<(usize,)>>::call_once
  24:     0x7f6f7239810a - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_map::build_type_with_children::<rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_variant_struct_type_di_node::{closure#0}, rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_variant_struct_type_di_node::{closure#1}>
  25:     0x7f6f7237b79f - <&mut rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node::{closure#0}::{closure#0} as core[3edb0f9afb6adb32]::ops::function::FnOnce<(rustc_target[a08db204f19200fc]::abi::VariantIdx,)>>::call_once
  26:     0x7f6f723f948d - <smallvec[c83712d02d935975]::SmallVec<[rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::VariantMemberInfo; 16usize]> as core[3edb0f9afb6adb32]::iter::traits::collect::Extend<rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::VariantMemberInfo>>::extend::<core[3edb0f9afb6adb32]::iter::adapters::map::Map<core[3edb0f9afb6adb32]::ops::range::Range<rustc_target[a08db204f19200fc]::abi::VariantIdx>, rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node::{closure#0}::{closure#0}>>
  27:     0x7f6f72399252 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_map::build_type_with_children::<rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node::{closure#0}, for<'a, 'b, 'c> fn(&'a rustc_codegen_llvm[2f479a9f59493764]::context::CodegenCx<'b, 'c>) -> smallvec[c83712d02d935975]::SmallVec<[&'b rustc_codegen_llvm[2f479a9f59493764]::llvm_::ffi::Metadata; 16usize]>>
  28:     0x7f6f7237fceb - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node
  29:     0x7f6f723be523 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_type_di_node
  30:     0x7f6f723ae5e2 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_di_node
  31:     0x7f6f723b759f - <&mut rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_variant_struct_type_di_node::{closure#0}::{closure#0} as core[3edb0f9afb6adb32]::ops::function::FnOnce<(usize,)>>::call_once
  32:     0x7f6f7239810a - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_map::build_type_with_children::<rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_variant_struct_type_di_node::{closure#0}, rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_variant_struct_type_di_node::{closure#1}>
  33:     0x7f6f7237b79f - <&mut rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node::{closure#0}::{closure#0} as core[3edb0f9afb6adb32]::ops::function::FnOnce<(rustc_target[a08db204f19200fc]::abi::VariantIdx,)>>::call_once
  34:     0x7f6f723f948d - <smallvec[c83712d02d935975]::SmallVec<[rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::VariantMemberInfo; 16usize]> as core[3edb0f9afb6adb32]::iter::traits::collect::Extend<rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::VariantMemberInfo>>::extend::<core[3edb0f9afb6adb32]::iter::adapters::map::Map<core[3edb0f9afb6adb32]::ops::range::Range<rustc_target[a08db204f19200fc]::abi::VariantIdx>, rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node::{closure#0}::{closure#0}>>
  35:     0x7f6f72399252 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_map::build_type_with_children::<rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node::{closure#0}, for<'a, 'b, 'c> fn(&'a rustc_codegen_llvm[2f479a9f59493764]::context::CodegenCx<'b, 'c>) -> smallvec[c83712d02d935975]::SmallVec<[&'b rustc_codegen_llvm[2f479a9f59493764]::llvm_::ffi::Metadata; 16usize]>>
  36:     0x7f6f7237fceb - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::native::build_enum_type_di_node
  37:     0x7f6f723be523 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::enums::build_enum_type_di_node
  38:     0x7f6f723ae5e2 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_di_node
  39:     0x7f6f723adf95 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_di_node
  40:     0x7f6f723adf95 - rustc_codegen_llvm[2f479a9f59493764]::debuginfo::metadata::type_di_node
  41:     0x7f6f7238bb65 - <rustc_codegen_llvm[2f479a9f59493764]::context::CodegenCx as rustc_codegen_ssa[4198c3a8f20e319b]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn
  42:     0x7f6f723c81a6 - rustc_codegen_ssa[4198c3a8f20e319b]::mir::codegen_mir::<rustc_codegen_llvm[2f479a9f59493764]::builder::Builder>
  43:     0x7f6f7237edf3 - rustc_codegen_llvm[2f479a9f59493764]::base::compile_codegen_unit::module_codegen
  44:     0x7f6f7324ad83 - <rustc_query_system[141d649b4129d34f]::dep_graph::graph::DepGraph<rustc_middle[6ba33e07887d312d]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6ba33e07887d312d]::ty::context::TyCtxt, rustc_span[fb9cf5df1e5e5539]::symbol::Symbol, rustc_codegen_ssa[4198c3a8f20e319b]::ModuleCodegen<rustc_codegen_llvm[2f479a9f59493764]::ModuleLlvm>>
  45:     0x7f6f7324a5b9 - rustc_codegen_llvm[2f479a9f59493764]::base::compile_codegen_unit
  46:     0x7f6f73268030 - <rustc_codegen_llvm[2f479a9f59493764]::LlvmCodegenBackend as rustc_codegen_ssa[4198c3a8f20e319b]::traits::backend::CodegenBackend>::codegen_crate
  47:     0x7f6f731fce67 - <rustc_session[72c90254a58d88d1]::session::Session>::time::<alloc[59e4fb8ddcfb913c]::boxed::Box<dyn core[3edb0f9afb6adb32]::any::Any>, rustc_interface[be6c6c80f2cd8cf2]::passes::start_codegen::{closure#0}>
  48:     0x7f6f731f81da - <rustc_interface[be6c6c80f2cd8cf2]::passes::QueryContext>::enter::<<rustc_interface[be6c6c80f2cd8cf2]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[3edb0f9afb6adb32]::result::Result<alloc[59e4fb8ddcfb913c]::boxed::Box<dyn core[3edb0f9afb6adb32]::any::Any>, rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  49:     0x7f6f7322085f - <rustc_interface[be6c6c80f2cd8cf2]::queries::Queries>::ongoing_codegen
  50:     0x7f6f731c74a2 - <rustc_interface[be6c6c80f2cd8cf2]::interface::Compiler>::enter::<rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}::{closure#2}, core[3edb0f9afb6adb32]::result::Result<core[3edb0f9afb6adb32]::option::Option<rustc_interface[be6c6c80f2cd8cf2]::queries::Linker>, rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  51:     0x7f6f731c0a7f - rustc_span[fb9cf5df1e5e5539]::with_source_map::<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_interface[be6c6c80f2cd8cf2]::interface::create_compiler_and_run<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#1}>
  52:     0x7f6f731c8302 - <scoped_tls[134a193f706323ee]::ScopedKey<rustc_span[fb9cf5df1e5e5539]::SessionGlobals>>::set::<rustc_interface[be6c6c80f2cd8cf2]::interface::run_compiler<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  53:     0x7f6f731eb99f - std[f9ee9c7d4fd68eda]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[be6c6c80f2cd8cf2]::util::run_in_thread_pool_with_globals<rustc_interface[be6c6c80f2cd8cf2]::interface::run_compiler<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  54:     0x7f6f731dd529 - <<std[f9ee9c7d4fd68eda]::thread::Builder>::spawn_unchecked_<rustc_interface[be6c6c80f2cd8cf2]::util::run_in_thread_pool_with_globals<rustc_interface[be6c6c80f2cd8cf2]::interface::run_compiler<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>::{closure#1} as core[3edb0f9afb6adb32]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7f6f70846463 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1680342795a2dc08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  56:     0x7f6f70846463 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45204a69827b0e83
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  57:     0x7f6f70846463 - std::sys::unix::thread::Thread::new::thread_start::h5d4e11bbda4161c8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  58:     0x7f6f701791a3 - start_thread
                               at /data/deploy/glibc-2.18/nptl/pthread_create.c:309
  59:     0x7f6f6feabfad - __clone
                               at /data/deploy/glibc-2.18/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111
  60:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0 (4b91a6ea7 2022-08-08) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `sc-network`

```

**Comment by Noratrieb** [comment]
This issue does not have a reproduction and is therefore not really actionable, closing. If you find the problem again, please open a new issue, ideally with a reproduction.
