### ISSUE TITLE
thread 'rustc' panicked at 'no entry found for key'

### ISSUE THREAD

**Issue by AndyJado** [rust-lang/rust#100877]
I tried this code:

I pulled the latest, played some rebase

```rust
./x.py check
```

I expected to see this happen: *please show no error*

Instead, this happened: 
👀
```
thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:644:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::stable_crate_id_to_crate_num
   6: <rustc_query_impl::on_disk_cache::CacheDecoder>::file_index_to_file
   7: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   8: <alloc::vec::Vec<(rustc_middle::ty::Predicate, rustc_span::span_encoding::Span)> as alloc::vec::spec_from_iter::SpecFromIter<(rustc_middle::ty::Predicate, rustc_span::span_encoding::Span), core::iter::adapters::map::Map<core::ops::range::Range<usize>, <[(rustc_middle::ty::Predicate, rustc_span::span_encoding::Span)] as rustc_middle::ty::codec::RefDecodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode::{closure#0}>>>::from_iter
   9: <[(rustc_middle::ty::Predicate, rustc_span::span_encoding::Span)] as rustc_middle::ty::codec::RefDecodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
  10: <rustc_query_impl::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle::ty::generics::GenericPredicates>
  11: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::mir::ConstantKind>, core::option::Option<rustc_middle::mir::query::DestructuredMirConstant>>::{closure#0}, core::option::Option<core::option::Option<rustc_middle::mir::query::DestructuredMirConstant>>>
  12: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::DefId, rustc_middle::ty::generics::GenericPredicates>
  13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::ty::generics::GenericPredicates>>
  14: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::predicates_of, rustc_query_impl::plumbing::QueryCtxt>
  15: rustc_ty_utils::ty::param_env
  16: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::ty::ParamEnv>
  17: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::ty::ParamEnv>>
  18: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::param_env, rustc_query_impl::plumbing::QueryCtxt>
  19: rustc_typeck::check::wfcheck::check_item
  20: rustc_typeck::check::wfcheck::check_well_formed
  21: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, ()>
  22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  23: rustc_query_system::query::plumbing::force_query::<rustc_query_impl::queries::check_well_formed, rustc_query_impl::plumbing::QueryCtxt>
  24: rustc_query_impl::query_callbacks::check_well_formed::force_from_dep_node
  25: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
  26: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  27: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl::plumbing::QueryCtxt>
  28: rustc_query_system::query::plumbing::ensure_must_run::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, rustc_span::def_id::LocalDefId>
  29: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::check_mod_type_wf, rustc_query_impl::plumbing::QueryCtxt>
  30: <rustc_middle::hir::map::Map>::for_each_module::<rustc_typeck::check_crate::{closure#5}::{closure#0}::{closure#0}>
  31: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#5}, ()>
  32: rustc_typeck::check_crate
  33: rustc_interface::passes::analysis
  34: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  35: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  36: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  37: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  38: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  39: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  40: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  41: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-beta.1 (56714e533 2022-08-09) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Z unstable-options -C incremental -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -Z osx-rpath-install-name -C link-args=-Wl,-rpath,@loader_path/../lib -C split-debuginfo=unpacked -C llvm-args=-import-instr-limit=10 -Z unstable-options -Z binary-dep-depinfo -Z tls-model=initial-exec

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 206071', /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/compiler/rustc_query_system/src/dep_graph/graph.rs:450:25
stack backtrace:
   0:        0x105562f24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9e253e8bfd0bd445
   1:        0x1055b01ec - core::fmt::write::h170b384e36e58da9
   2:        0x105555df0 - std::io::Write::write_fmt::he5685bc095ff9c33
   3:        0x105565a34 - std::panicking::default_hook::{{closure}}::h36bb536bc8ecb089
   4:        0x105565754 - std::panicking::default_hook::h9fa506012ac971b8
   5:        0x10cde2a9c - rustc_driver[18596eb462993f47]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x1055660f8 - std::panicking::rust_panic_with_hook::h7ef5e8552af363cf
   7:        0x105565fa0 - std::panicking::begin_panic_handler::{{closure}}::hb908b7cd00d1e4a0
   8:        0x105563430 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c5dca1442adc757
   9:        0x105565cf8 - _rust_begin_unwind
  10:        0x1055db5e8 - core::panicking::panic_fmt::h2e977c44e9b05d81
  11:        0x10fe3f4c0 - <rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind as rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::DepKind>::read_deps::<<rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::graph::DepGraph<rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind>>::read_index::{closure#0}>
  12:        0x10fdafb98 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::get_query::<rustc_query_impl[4bd6f15526759191]::queries::def_span, rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  13:        0x10fe9a620 - <rustc_span[ac37a41155aa3224]::def_id::DefId as rustc_query_impl[4bd6f15526759191]::keys::Key>::default_span
  14:        0x10ff7e9bc - rustc_query_impl[4bd6f15526759191]::make_query::predicates_of
  15:        0x10fc7b20c - <rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::QueryState<(rustc_span[ac37a41155aa3224]::def_id::LocalDefId, rustc_span[ac37a41155aa3224]::def_id::LocalDefId)>>::try_collect_active_jobs::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  16:        0x1100295d4 - <rustc_query_impl[4bd6f15526759191]::Queries>::try_collect_active_jobs
  17:        0x10fffb9f8 - <rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>::try_print_query_stack
  18:        0x10ceebcfc - rustc_interface[af5f3681247a90d7]::interface::try_print_query_stack
  19:        0x10cde3590 - rustc_driver[18596eb462993f47]::report_ice
  20:        0x1055660f8 - std::panicking::rust_panic_with_hook::h7ef5e8552af363cf
  21:        0x105565fa0 - std::panicking::begin_panic_handler::{{closure}}::hb908b7cd00d1e4a0
  22:        0x105563430 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c5dca1442adc757
  23:        0x105565cf8 - _rust_begin_unwind
  24:        0x1055db5e8 - core::panicking::panic_fmt::h2e977c44e9b05d81
  25:        0x1055acfa4 - core::panicking::panic_display::hb149bcf9b0325d47
  26:        0x1055acf68 - core::panicking::panic_str::h2f181d16299832ab
  27:        0x1055db4d0 - core::option::expect_failed::h89ad4d3873e8634f
  28:        0x11036c50c - <rustc_metadata[13596a41ab21bd72]::creader::CStore as rustc_session[8f52ed710a0a8230]::cstore::CrateStore>::stable_crate_id_to_crate_num
  29:        0x10fee8488 - <rustc_query_impl[4bd6f15526759191]::on_disk_cache::CacheDecoder>::file_index_to_file
  30:        0x10fe2cdb0 - <rustc_span[ac37a41155aa3224]::span_encoding::Span as rustc_serialize[c65290704d5ce574]::serialize::Decodable<rustc_query_impl[4bd6f15526759191]::on_disk_cache::CacheDecoder>>::decode
  31:        0x110014a38 - <alloc[23bd3d266e9910b9]::vec::Vec<(rustc_middle[ae8652d5e274b38e]::ty::Predicate, rustc_span[ac37a41155aa3224]::span_encoding::Span)> as alloc[23bd3d266e9910b9]::vec::spec_from_iter::SpecFromIter<(rustc_middle[ae8652d5e274b38e]::ty::Predicate, rustc_span[ac37a41155aa3224]::span_encoding::Span), core[55bf22af6429b8f1]::iter::adapters::map::Map<core[55bf22af6429b8f1]::ops::range::Range<usize>, <[(rustc_middle[ae8652d5e274b38e]::ty::Predicate, rustc_span[ac37a41155aa3224]::span_encoding::Span)] as rustc_middle[ae8652d5e274b38e]::ty::codec::RefDecodable<rustc_query_impl[4bd6f15526759191]::on_disk_cache::CacheDecoder>>::decode::{closure#0}>>>::from_iter
  32:        0x10fffadf8 - <[(rustc_middle[ae8652d5e274b38e]::ty::Predicate, rustc_span[ac37a41155aa3224]::span_encoding::Span)] as rustc_middle[ae8652d5e274b38e]::ty::codec::RefDecodable<rustc_query_impl[4bd6f15526759191]::on_disk_cache::CacheDecoder>>::decode
  33:        0x10fee3e98 - <rustc_query_impl[4bd6f15526759191]::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle[ae8652d5e274b38e]::ty::generics::GenericPredicates>
  34:        0x10fe429b4 - <rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind as rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::DepKind>::with_deps::<rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_middle[ae8652d5e274b38e]::ty::ParamEnvAnd<rustc_middle[ae8652d5e274b38e]::mir::ConstantKind>, core[55bf22af6429b8f1]::option::Option<rustc_middle[ae8652d5e274b38e]::mir::query::DestructuredMirConstant>>::{closure#0}, core[55bf22af6429b8f1]::option::Option<core[55bf22af6429b8f1]::option::Option<rustc_middle[ae8652d5e274b38e]::mir::query::DestructuredMirConstant>>>
  35:        0x10fd4db38 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_span[ac37a41155aa3224]::def_id::DefId, rustc_middle[ae8652d5e274b38e]::ty::generics::GenericPredicates>
  36:        0x10fcfd840 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::try_execute_query::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_query_system[fb9d59d1cbbc6b4]::query::caches::DefaultCache<rustc_span[ac37a41155aa3224]::def_id::DefId, rustc_middle[ae8652d5e274b38e]::ty::generics::GenericPredicates>>
  37:        0x10fd6e438 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::get_query::<rustc_query_impl[4bd6f15526759191]::queries::predicates_of, rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  38:        0x10f52c564 - rustc_ty_utils[52560b1c30550d04]::ty::param_env
  39:        0x10ff44e7c - <rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::graph::DepGraph<rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[ae8652d5e274b38e]::ty::context::TyCtxt, rustc_span[ac37a41155aa3224]::def_id::DefId, rustc_middle[ae8652d5e274b38e]::ty::ParamEnv>
  40:        0x10fcf98d0 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::try_execute_query::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_query_system[fb9d59d1cbbc6b4]::query::caches::DefaultCache<rustc_span[ac37a41155aa3224]::def_id::DefId, rustc_middle[ae8652d5e274b38e]::ty::ParamEnv>>
  41:        0x10fdb2c40 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::get_query::<rustc_query_impl[4bd6f15526759191]::queries::param_env, rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  42:        0x10f459350 - rustc_typeck[76df9d047b9e63d0]::check::wfcheck::check_item
  43:        0x10f44db50 - rustc_typeck[76df9d047b9e63d0]::check::wfcheck::check_well_formed
  44:        0x10ff3d630 - <rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::graph::DepGraph<rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[ae8652d5e274b38e]::ty::context::TyCtxt, rustc_span[ac37a41155aa3224]::def_id::LocalDefId, ()>
  45:        0x10fce39bc - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::try_execute_query::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_query_system[fb9d59d1cbbc6b4]::query::caches::DefaultCache<rustc_span[ac37a41155aa3224]::def_id::LocalDefId, ()>>
  46:        0x10fc8ebbc - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::force_query::<rustc_query_impl[4bd6f15526759191]::queries::check_well_formed, rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  47:        0x11003e668 - rustc_query_impl[4bd6f15526759191]::query_callbacks::check_well_formed::force_from_dep_node
  48:        0x110acabbc - <rustc_middle[ae8652d5e274b38e]::ty::context::TyCtxt as rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::DepContext>::try_force_from_dep_node
  49:        0x10ff28c44 - <rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::graph::DepGraph<rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  50:        0x10fef68a8 - <rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::graph::DepGraph<rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  51:        0x10fca5ad0 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::ensure_must_run::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_span[ac37a41155aa3224]::def_id::LocalDefId, rustc_span[ac37a41155aa3224]::def_id::LocalDefId>
  52:        0x10fd7a884 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::get_query::<rustc_query_impl[4bd6f15526759191]::queries::check_mod_type_wf, rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  53:        0x10f3f0fc8 - <rustc_middle[ae8652d5e274b38e]::hir::map::Map>::for_each_module::<rustc_typeck[76df9d047b9e63d0]::check_crate::{closure#5}::{closure#0}::{closure#0}>
  54:        0x10f369b20 - <rustc_session[8f52ed710a0a8230]::session::Session>::track_errors::<rustc_typeck[76df9d047b9e63d0]::check_crate::{closure#5}, ()>
  55:        0x10f47ecbc - rustc_typeck[76df9d047b9e63d0]::check_crate
  56:        0x10ce8b508 - rustc_interface[af5f3681247a90d7]::passes::analysis
  57:        0x10ff5fb58 - <rustc_query_system[fb9d59d1cbbc6b4]::dep_graph::graph::DepGraph<rustc_middle[ae8652d5e274b38e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[ae8652d5e274b38e]::ty::context::TyCtxt, (), core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>
  58:        0x10fd18b88 - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::try_execute_query::<rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt, rustc_query_system[fb9d59d1cbbc6b4]::query::caches::DefaultCache<(), core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>>
  59:        0x10fdaf9cc - rustc_query_system[fb9d59d1cbbc6b4]::query::plumbing::get_query::<rustc_query_impl[4bd6f15526759191]::queries::analysis, rustc_query_impl[4bd6f15526759191]::plumbing::QueryCtxt>
  60:        0x10cd951ec - <rustc_interface[af5f3681247a90d7]::passes::QueryContext>::enter::<rustc_driver[18596eb462993f47]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>
  61:        0x10cd67388 - <rustc_interface[af5f3681247a90d7]::interface::Compiler>::enter::<rustc_driver[18596eb462993f47]::run_compiler::{closure#1}::{closure#2}, core[55bf22af6429b8f1]::result::Result<core[55bf22af6429b8f1]::option::Option<rustc_interface[af5f3681247a90d7]::queries::Linker>, rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>
  62:        0x10cd5db5c - rustc_span[ac37a41155aa3224]::with_source_map::<core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>, rustc_interface[af5f3681247a90d7]::interface::create_compiler_and_run<core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>, rustc_driver[18596eb462993f47]::run_compiler::{closure#1}>::{closure#1}>
  63:        0x10cd84948 - rustc_interface[af5f3681247a90d7]::interface::create_compiler_and_run::<core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>, rustc_driver[18596eb462993f47]::run_compiler::{closure#1}>
  64:        0x10cdcf7d4 - <scoped_tls[fb85e7293028960e]::ScopedKey<rustc_span[ac37a41155aa3224]::SessionGlobals>>::set::<rustc_interface[af5f3681247a90d7]::interface::run_compiler<core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>, rustc_driver[18596eb462993f47]::run_compiler::{closure#1}>::{closure#0}, core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>
  65:        0x10cd6390c - std[f978d67385de1fbe]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[af5f3681247a90d7]::util::run_in_thread_pool_with_globals<rustc_interface[af5f3681247a90d7]::interface::run_compiler<core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>, rustc_driver[18596eb462993f47]::run_compiler::{closure#1}>::{closure#0}, core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>::{closure#0}, core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>
  66:        0x10cd85218 - <<std[f978d67385de1fbe]::thread::Builder>::spawn_unchecked_<rustc_interface[af5f3681247a90d7]::util::run_in_thread_pool_with_globals<rustc_interface[af5f3681247a90d7]::interface::run_compiler<core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>, rustc_driver[18596eb462993f47]::run_compiler::{closure#1}>::{closure#0}, core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>::{closure#0}, core[55bf22af6429b8f1]::result::Result<(), rustc_errors[bcf41bbe0b2c89d4]::ErrorGuaranteed>>::{closure#1} as core[55bf22af6429b8f1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  67:        0x10556e7a8 - std::sys::unix::thread::Thread::new::thread_start::h7b984fe6b5676017
  68:        0x19e87906c - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-beta.1 (56714e533 2022-08-09) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Z unstable-options -C incremental -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -Z osx-rpath-install-name -C link-args=-Wl,-rpath,@loader_path/../lib -C split-debuginfo=unpacked -C llvm-args=-import-instr-limit=10 -Z unstable-options -Z binary-dep-depinfo -Z tls-model=initial-exec

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
rustc exited with signal: 6 (SIGABRT)
error: could not compile `rustdoc`

Caused by:
  process didn't exit successfully: `/Users/andyjado/Zf/rust/build/bootstrap/debug/rustc --crate-name rustdoc --edition=2021 src/librustdoc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Zunstable-options --check-cfg 'values(feature, "jemalloc")' --check-cfg 'names()' --check-cfg 'values()' -C metadata=6ed84bb01582938d -C extra-filename=-6ed84bb01582938d --out-dir /Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps --target aarch64-apple-darwin -C incremental=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/incremental -L dependency=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps -L dependency=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/release/deps --extern arrayvec=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libarrayvec-fa143faccdbb25ff.rmeta --extern askama=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libaskama-6eb7712ff6173225.rmeta --extern atty=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libatty-a1e0010096ae61e3.rmeta --extern itertools=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libitertools-f93c0c096ac0dad9.rmeta --extern minifier=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libminifier-63e86ae0f5ec1008.rmeta --extern once_cell=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libonce_cell-79882cf6077b310a.rmeta --extern pulldown_cmark=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libpulldown_cmark-cdbadca4d585e002.rmeta --extern regex=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libregex-311ed44b55304e0a.rmeta --extern rustdoc_json_types=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/librustdoc_json_types-2fc1b48a10ce44cb.rmeta --extern serde=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libserde-a5ab8f38148f2684.rmeta --extern serde_json=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libserde_json-c4474c04fc6af342.rmeta --extern smallvec=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libsmallvec-a96d7b969bca00ae.rmeta --extern tempfile=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libtempfile-28ea878ef7c6afbe.rmeta --extern tracing=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libtracing-f918f162a968d73b.rmeta --extern tracing_subscriber=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libtracing_subscriber-fc0abf83320cad86.rmeta --extern tracing_tree=/Users/andyjado/Zf/rust/build/aarch64-apple-darwin/stage0-tools/aarch64-apple-darwin/release/deps/libtracing_tree-c93c24d942bba593.rmeta --cfg=bootstrap -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(release)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)' -Zmacro-backtrace -Zosx-rpath-install-name '-Clink-args=-Wl,-rpath,@loader_path/../lib' -Csplit-debuginfo=unpacked -Cllvm-args=-import-instr-limit=10 -Zunstable-options -Z binary-dep-depinfo` (exit status: 254)
Build completed unsuccessfully in 0:00:10
```
### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by AndyJado** [comment]
I suppose it was becuase I accidently deleted some file in `src/tool/miri` and I committed my change, so git won't restore or sth.

anyway, I fixed it by some serious rebase and  run `x clean`, then `x check` passed like usual
