### ISSUE TITLE
Compiler panicked once, next compilation succeeded

### ISSUE THREAD

**Issue by Dango-rs** [rust-lang/rust#100950]
Happened once only, on second try the compilation succeeded.

### Code

```Rust
// Impossible to provide full example.. apologies!
pub fn hash64_fare_id_key(v1: u64, v2: &str, v3: &str, v4: &str) -> u64 {
    let mut hasher = XxHash64::with_seed(0);
    hasher.write(&v1.to_be_bytes());
    hasher.write(&v2.as_bytes());
    hasher.write(&v3.as_bytes());
    hasher.write(&v4.as_bytes());
    hasher.finish()
}
```

### Meta

```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-unknown-linux-gnu
release: 1.62.1
LLVM version: 14.0.5

```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 21647 but the index is 8388726', compiler/rustc_span/src/symbol.rs:1881:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 21647 but the index is 8388726', compiler/rustc_span/src/symbol.rs:1881:9
stack backtrace:
   0:     0x7fce3edeefbd - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fce3edeefbd - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fce3edeefbd - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fce3edeefbd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fce3ee4ac4c - core::fmt::write::h909e69a2c24f44cc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fce3ede0731 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:     0x7fce3edf1cd5 - std::sys_common::backtrace::_print::hff4838ebf14a2171
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fce3edf1cd5 - std::sys_common::backtrace::print::h2499280374189ad9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fce3edf1cd5 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:     0x7fce3edf1949 - std::panicking::default_hook::h3217e229d6e9d13c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:     0x7fce3f5b6571 - rustc_driver[b4654d3c4d4292dd]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fce13b9b6c3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfd4d7931c65e2c7e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1886:9
  12:     0x7fce13bc920d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hed90014dfca17563
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/proc_macro/src/bridge/client.rs:335:21
  13:     0x7fce3edf24a6 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
  14:     0x7fce3edf22a7 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
  15:     0x7fce3edef474 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7fce3edf1fd9 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  17:     0x7fce3edb7253 - core::panicking::panic_fmt::h9f8393e7fd56d655
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  18:     0x7fce3edb7192 - core::panicking::panic_bounds_check::h2bacc83b90ece467
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:84:5
  19:     0x7fce4161806b - <rustc_span[1d0b4d44d1f53955]::symbol::Symbol>::as_str
  20:     0x7fce415d9d59 - <rustc_hir[597a1a56ef61745a]::hir::QPath as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  21:     0x7fce415da768 - <rustc_hir[597a1a56ef61745a]::hir::PatKind as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  22:     0x7fce415dccb3 - <[rustc_hir[597a1a56ef61745a]::hir::Arm] as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  23:     0x7fce415d2ab2 - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  24:     0x7fce415d236e - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  25:     0x7fce415d3041 - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  26:     0x7fce415dcfa5 - <[rustc_hir[597a1a56ef61745a]::hir::Stmt] as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  27:     0x7fce415d2520 - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  28:     0x7fce415dcd0e - <[rustc_hir[597a1a56ef61745a]::hir::Arm] as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  29:     0x7fce415d2ab2 - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  30:     0x7fce415d255a - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  31:     0x7fce415d2dde - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  32:     0x7fce415d352c - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  33:     0x7fce415dcfa5 - <[rustc_hir[597a1a56ef61745a]::hir::Stmt] as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  34:     0x7fce415d2520 - <rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext as rustc_hir[597a1a56ef61745a]::stable_hash_impls::HashStableContext>::hash_hir_expr
  35:     0x7fce40c88f64 - <rustc_hir[597a1a56ef61745a]::hir::BodyId as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  36:     0x7fce40c54266 - <rustc_hir[597a1a56ef61745a]::hir::OwnerNode as rustc_data_structures[74206c8a5e07d11e]::stable_hasher::HashStable<rustc_query_system[b4bd2ce220f7e42d]::ich::hcx::StableHashingContext>>::hash_stable
  37:     0x7fce40c78345 - <rustc_ast_lowering[bc0e2759e326fbf7]::LoweringContext>::make_owner_info
  38:     0x7fce40c76e63 - <rustc_ast_lowering[bc0e2759e326fbf7]::LoweringContext>::with_hir_id_owner::<<rustc_ast_lowering[bc0e2759e326fbf7]::item::ItemLowerer>::with_lctx<<rustc_ast_lowering[bc0e2759e326fbf7]::item::ItemLowerer>::lower_assoc_item::{closure#0}>::{closure#0}>
  39:     0x7fce40c9b19e - <rustc_ast_lowering[bc0e2759e326fbf7]::item::ItemLowerer>::lower_node
  40:     0x7fce40c732bc - rustc_ast_lowering[bc0e2759e326fbf7]::lower_crate
  41:     0x7fce4165d957 - <rustc_interface[9f664daa3237129]::passes::boxed_resolver::BoxedResolver>::access::<rustc_interface[9f664daa3237129]::passes::create_global_ctxt::{closure#0}, &rustc_hir[597a1a56ef61745a]::hir::Crate>
  42:     0x7fce41653b67 - rustc_interface[9f664daa3237129]::passes::create_global_ctxt
  43:     0x7fce4167793d - <rustc_interface[9f664daa3237129]::queries::Queries>::global_ctxt
  44:     0x7fce4161f6a2 - <rustc_interface[9f664daa3237129]::interface::Compiler>::enter::<rustc_driver[b4654d3c4d4292dd]::run_compiler::{closure#1}::{closure#2}, core[dbea6f494faa966e]::result::Result<core[dbea6f494faa966e]::option::Option<rustc_interface[9f664daa3237129]::queries::Linker>, rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>>
  45:     0x7fce4164809f - rustc_span[1d0b4d44d1f53955]::with_source_map::<core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>, rustc_interface[9f664daa3237129]::interface::create_compiler_and_run<core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>, rustc_driver[b4654d3c4d4292dd]::run_compiler::{closure#1}>::{closure#1}>
  46:     0x7fce41620374 - rustc_interface[9f664daa3237129]::interface::create_compiler_and_run::<core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>, rustc_driver[b4654d3c4d4292dd]::run_compiler::{closure#1}>
  47:     0x7fce4161dc12 - <scoped_tls[ab1554bfb6e7ab15]::ScopedKey<rustc_span[1d0b4d44d1f53955]::SessionGlobals>>::set::<rustc_interface[9f664daa3237129]::interface::run_compiler<core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>, rustc_driver[b4654d3c4d4292dd]::run_compiler::{closure#1}>::{closure#0}, core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>>
  48:     0x7fce41634dff - std[8996aeeb2a45fe64]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9f664daa3237129]::util::run_in_thread_pool_with_globals<rustc_interface[9f664daa3237129]::interface::run_compiler<core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>, rustc_driver[b4654d3c4d4292dd]::run_compiler::{closure#1}>::{closure#0}, core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>>::{closure#0}, core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>>
  49:     0x7fce41634f39 - <<std[8996aeeb2a45fe64]::thread::Builder>::spawn_unchecked_<rustc_interface[9f664daa3237129]::util::run_in_thread_pool_with_globals<rustc_interface[9f664daa3237129]::interface::run_compiler<core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>, rustc_driver[b4654d3c4d4292dd]::run_compiler::{closure#1}>::{closure#0}, core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>>::{closure#0}, core[dbea6f494faa966e]::result::Result<(), rustc_errors[4633ef6e4608f9c1]::ErrorGuaranteed>>::{closure#1} as core[dbea6f494faa966e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  50:     0x7fce3edfc3c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h191d5c5ea3edb31d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
  51:     0x7fce3edfc3c3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h42ef7cb2ae640a31
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
  52:     0x7fce3edfc3c3 - std::sys::unix::thread::Thread::new::thread_start::he47f7169665dab60
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys/unix/thread.rs:108:17
  53:     0x7fce3ed18609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  54:     0x7fce3ec31133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  55:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.1 (e092d0b6b 2022-07-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

```

</p>
</details>

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Without a way to reproduce, there is not much that can be done right now though. Closing, but feel free to re-open if a way to reproduce is found.
