### ISSUE TITLE
ICE

### ISSUE THREAD

**Issue by sjud** [rust-lang/rust#101126]
```rust
 Checking sea-orm v0.8.0
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:554:13: Region parameter out of range when substituting in region 'b (index=5)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/34a6cae28e7013ff0e640026a8e46f315426829d/compiler/rustc_errors/src/lib.rs:1392:9
stack backtrace:
   0:        0x11643b6a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2b47c4cdbed401c
   1:        0x11649356b - core::fmt::write::h32ca8bf5b653b983
   2:        0x11642dc5c - std::io::Write::write_fmt::h18e76a3ea7a513b3
   3:        0x11643e787 - std::panicking::default_hook::{{closure}}::h905587026b7b9211
   4:        0x11643e48a - std::panicking::default_hook::hd6d8754368a0f24f
   5:        0x10d465ffa - rustc_driver[af7c8ea24ae9b802]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x11643eebd - std::panicking::rust_panic_with_hook::h30fd4bbf050c7dcc
   7:        0x111ae5117 - std[6fcc61ffe2130780]::panicking::begin_panic::<rustc_errors[36f8fd53ca2c25a0]::ExplicitBug>::{closure#0}
   8:        0x111ae45f9 - std[6fcc61ffe2130780]::sys_common::backtrace::__rust_end_short_backtrace::<std[6fcc61ffe2130780]::panicking::begin_panic<rustc_errors[36f8fd53ca2c25a0]::ExplicitBug>::{closure#0}, !>
   9:        0x112095269 - std[6fcc61ffe2130780]::panicking::begin_panic::<rustc_errors[36f8fd53ca2c25a0]::ExplicitBug>
  10:        0x111b49169 - std[6fcc61ffe2130780]::panic::panic_any::<rustc_errors[36f8fd53ca2c25a0]::ExplicitBug>
  11:        0x111b46b56 - <rustc_errors[36f8fd53ca2c25a0]::HandlerInner>::bug::<&alloc[e27ad7c008dcee4c]::string::String>
  12:        0x111b46777 - <rustc_errors[36f8fd53ca2c25a0]::Handler>::bug::<&alloc[e27ad7c008dcee4c]::string::String>
  13:        0x111b84de5 - rustc_middle[e92f947c8785ec97]::ty::context::tls::with_context_opt::<rustc_middle[e92f947c8785ec97]::ty::context::tls::with_opt<rustc_middle[e92f947c8785ec97]::util::bug::opt_span_bug_fmt<rustc_span[576036afad7afd91]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  14:        0x111b85e31 - rustc_middle[e92f947c8785ec97]::util::bug::opt_span_bug_fmt::<rustc_span[576036afad7afd91]::span_encoding::Span>
  15:        0x112099e9e - rustc_middle[e92f947c8785ec97]::util::bug::bug_fmt
  16:        0x112099b89 - <rustc_middle[e92f947c8785ec97]::ty::subst::SubstFolder as rustc_middle[e92f947c8785ec97]::ty::fold::TypeFolder>::fold_region::region_param_out_of_range
  17:        0x111b83758 - <rustc_middle[e92f947c8785ec97]::ty::subst::SubstFolder as rustc_middle[e92f947c8785ec97]::ty::fold::TypeFolder>::fold_region
  18:        0x1119333ea - <rustc_middle[e92f947c8785ec97]::ty::PredicateKind as rustc_middle[e92f947c8785ec97]::ty::fold::TypeFoldable>::try_fold_with::<rustc_middle[e92f947c8785ec97]::ty::subst::SubstFolder>
  19:        0x1119ab3a1 - <rustc_middle[e92f947c8785ec97]::ty::subst::SubstFolder as rustc_middle[e92f947c8785ec97]::ty::fold::FallibleTypeFolder>::try_fold_binder::<rustc_middle[e92f947c8785ec97]::ty::PredicateKind>
  20:        0x111906a19 - <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::register_hidden_type
  21:        0x1118fa07b - <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::handle_opaque_type::{closure#0}
  22:        0x1118f9a28 - <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::handle_opaque_type
  23:        0x11197f467 - <rustc_middle[e92f947c8785ec97]::ty::fold::BottomUpFolder<<rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#3}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#1}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#2}> as rustc_middle[e92f947c8785ec97]::ty::fold::FallibleTypeFolder>::try_fold_ty
  24:        0x11191f5f5 - <&rustc_middle[e92f947c8785ec97]::ty::list::List<rustc_middle[e92f947c8785ec97]::ty::subst::GenericArg> as rustc_middle[e92f947c8785ec97]::ty::fold::TypeFoldable>::try_fold_with::<rustc_middle[e92f947c8785ec97]::ty::fold::BottomUpFolder<<rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#3}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#1}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#2}>>
  25:        0x111938f7d - <rustc_middle[e92f947c8785ec97]::ty::Ty as rustc_middle[e92f947c8785ec97]::ty::fold::TypeSuperFoldable>::super_fold_with::<rustc_middle[e92f947c8785ec97]::ty::fold::BottomUpFolder<<rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#3}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#1}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#2}>>
  26:        0x11197f102 - <rustc_middle[e92f947c8785ec97]::ty::fold::BottomUpFolder<<rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#3}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#1}, <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars::{closure#2}> as rustc_middle[e92f947c8785ec97]::ty::fold::FallibleTypeFolder>::try_fold_ty
  27:        0x1118f9989 - <rustc_infer[58313dce5fb103d1]::infer::InferCtxt>::replace_opaque_types_with_inference_vars
  28:        0x10ff2e81d - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::supplied_sig_of_closure
  29:        0x10ff2c4ad - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_expr_closure
  30:        0x10ff2f73c - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_expr_kind
  31:        0x10fee404a - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:        0x10fef06e5 - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_argument_types
  33:        0x10fed3f7f - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  34:        0x10fed13cf - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_call
  35:        0x10ff30117 - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_expr_kind
  36:        0x10fee404a - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:        0x10fee4fa7 - <rustc_typeck[be571e35ac9eac5a]::check::fn_ctxt::FnCtxt>::check_return_expr
  38:        0x11009b8df - rustc_typeck[be571e35ac9eac5a]::check::check::check_fn
  39:        0x1100ebf31 - <rustc_infer[58313dce5fb103d1]::infer::InferCtxtBuilder>::enter::<&rustc_middle[e92f947c8785ec97]::ty::context::TypeckResults, <rustc_typeck[be571e35ac9eac5a]::check::inherited::InheritedBuilder>::enter<rustc_typeck[be571e35ac9eac5a]::check::typeck_with_fallback<rustc_typeck[be571e35ac9eac5a]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[e92f947c8785ec97]::ty::context::TypeckResults>::{closure#0}>
  40:        0x10ffb27a1 - rustc_typeck[be571e35ac9eac5a]::check::typeck
  41:        0x110b1a244 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_span[576036afad7afd91]::def_id::LocalDefId, &rustc_middle[e92f947c8785ec97]::ty::context::TypeckResults>>
  42:        0x110c23ace - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::typeck, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  43:        0x111b25d56 - <rustc_middle[e92f947c8785ec97]::ty::context::TyCtxt>::typeck_opt_const_arg
  44:        0x110472a98 - rustc_mir_build[99cbc2f634496d8d]::build::mir_built
  45:        0x110b066c8 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_middle[e92f947c8785ec97]::ty::WithOptConstParam<rustc_span[576036afad7afd91]::def_id::LocalDefId>, &rustc_data_structures[c4b76d422445032d]::steal::Steal<rustc_middle[e92f947c8785ec97]::mir::Body>>>
  46:        0x110c264ce - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::mir_built, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  47:        0x110eebb57 - <rustc_query_impl[bb093e0ab22ca1b1]::Queries as rustc_middle[e92f947c8785ec97]::ty::query::QueryEngine>::mir_built
  48:        0x10fcb893a - rustc_mir_transform[26a833a7cbed2875]::check_unsafety::unsafety_check_result
  49:        0x10fcb5182 - <rustc_mir_transform[26a833a7cbed2875]::check_unsafety::provide::{closure#0} as core[58d0edd94d2de736]::ops::function::FnOnce<(rustc_middle[e92f947c8785ec97]::ty::context::TyCtxt, rustc_span[576036afad7afd91]::def_id::LocalDefId)>>::call_once
  50:        0x110b1c264 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_span[576036afad7afd91]::def_id::LocalDefId, &rustc_middle[e92f947c8785ec97]::mir::query::UnsafetyCheckResult>>
  51:        0x110bf288e - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::unsafety_check_result, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  52:        0x10fc5bf2f - rustc_mir_transform[26a833a7cbed2875]::mir_const
  53:        0x110b066c8 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_middle[e92f947c8785ec97]::ty::WithOptConstParam<rustc_span[576036afad7afd91]::def_id::LocalDefId>, &rustc_data_structures[c4b76d422445032d]::steal::Steal<rustc_middle[e92f947c8785ec97]::mir::Body>>>
  54:        0x110c2660b - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::mir_const, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  55:        0x110eebb87 - <rustc_query_impl[bb093e0ab22ca1b1]::Queries as rustc_middle[e92f947c8785ec97]::ty::query::QueryEngine>::mir_const
  56:        0x10fc5cb63 - rustc_mir_transform[26a833a7cbed2875]::mir_promoted
  57:        0x110bcc5b4 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::mir_promoted, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  58:        0x110eebd07 - <rustc_query_impl[bb093e0ab22ca1b1]::Queries as rustc_middle[e92f947c8785ec97]::ty::query::QueryEngine>::mir_promoted
  59:        0x1106e4aac - rustc_borrowck[f75d14d6475f2ffe]::mir_borrowck
  60:        0x1106be1a2 - <rustc_borrowck[f75d14d6475f2ffe]::provide::{closure#0} as core[58d0edd94d2de736]::ops::function::FnOnce<(rustc_middle[e92f947c8785ec97]::ty::context::TyCtxt, rustc_span[576036afad7afd91]::def_id::LocalDefId)>>::call_once
  61:        0x110b1b254 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_span[576036afad7afd91]::def_id::LocalDefId, &rustc_middle[e92f947c8785ec97]::mir::query::BorrowCheckResult>>
  62:        0x110bcbf43 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::mir_borrowck, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  63:        0x1100110e3 - rustc_typeck[be571e35ac9eac5a]::collect::type_of::find_opaque_ty_constraints_for_rpit
  64:        0x11000fecf - rustc_typeck[be571e35ac9eac5a]::collect::type_of::type_of
  65:        0x110b37db7 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_span[576036afad7afd91]::def_id::DefId, rustc_middle[e92f947c8785ec97]::ty::Ty>>
  66:        0x110c23d90 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::type_of, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  67:        0x110079617 - rustc_typeck[be571e35ac9eac5a]::check::check::check_opaque
  68:        0x11007a98e - rustc_typeck[be571e35ac9eac5a]::check::check::check_item_type
  69:        0x110082c8e - rustc_typeck[be571e35ac9eac5a]::check::check::check_mod_item_types
  70:        0x110b1e27d - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<rustc_span[576036afad7afd91]::def_id::LocalDefId, ()>>
  71:        0x110beae9b - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::check_mod_item_types, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  72:        0x11009f5b9 - <rustc_middle[e92f947c8785ec97]::hir::map::Map>::for_each_module::<rustc_typeck[be571e35ac9eac5a]::check_crate::{closure#6}::{closure#0}>
  73:        0x10fff7bd0 - <rustc_session[8909a7d15ece2eeb]::session::Session>::time::<(), rustc_typeck[be571e35ac9eac5a]::check_crate::{closure#6}>
  74:        0x1101658bd - rustc_typeck[be571e35ac9eac5a]::check_crate
  75:        0x10d52551a - rustc_interface[c4c1293ab69a869a]::passes::analysis
  76:        0x110b65709 - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::try_execute_query::<rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt, rustc_query_system[4a8f35804a9c3fb3]::query::caches::DefaultCache<(), core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>>
  77:        0x110c23eaf - rustc_query_system[4a8f35804a9c3fb3]::query::plumbing::get_query::<rustc_query_impl[bb093e0ab22ca1b1]::queries::analysis, rustc_query_impl[bb093e0ab22ca1b1]::plumbing::QueryCtxt>
  78:        0x10d410783 - <rustc_interface[c4c1293ab69a869a]::passes::QueryContext>::enter::<rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>
  79:        0x10d3de607 - <rustc_interface[c4c1293ab69a869a]::interface::Compiler>::enter::<rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}::{closure#2}, core[58d0edd94d2de736]::result::Result<core[58d0edd94d2de736]::option::Option<rustc_interface[c4c1293ab69a869a]::queries::Linker>, rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>
  80:        0x10d3d3bd8 - rustc_span[576036afad7afd91]::with_source_map::<core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>, rustc_interface[c4c1293ab69a869a]::interface::create_compiler_and_run<core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>, rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}>::{closure#1}>
  81:        0x10d3feb18 - rustc_interface[c4c1293ab69a869a]::interface::create_compiler_and_run::<core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>, rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}>
  82:        0x10d4500c5 - <scoped_tls[6a99bf746b85ec55]::ScopedKey<rustc_span[576036afad7afd91]::SessionGlobals>>::set::<rustc_interface[c4c1293ab69a869a]::interface::run_compiler<core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>, rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}>::{closure#0}, core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>
  83:        0x10d3da709 - std[6fcc61ffe2130780]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c4c1293ab69a869a]::util::run_in_thread_pool_with_globals<rustc_interface[c4c1293ab69a869a]::interface::run_compiler<core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>, rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}>::{closure#0}, core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>::{closure#0}, core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>
  84:        0x10d3ff5e1 - <<std[6fcc61ffe2130780]::thread::Builder>::spawn_unchecked_<rustc_interface[c4c1293ab69a869a]::util::run_in_thread_pool_with_globals<rustc_interface[c4c1293ab69a869a]::interface::run_compiler<core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>, rustc_driver[af7c8ea24ae9b802]::run_compiler::{closure#1}>::{closure#0}, core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>::{closure#0}, core[58d0edd94d2de736]::result::Result<(), rustc_errors[36f8fd53ca2c25a0]::ErrorGuaranteed>>::{closure#1} as core[58d0edd94d2de736]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  85:        0x1164480d7 - std::sys::unix::thread::Thread::new::thread_start::h5e196962805cfa55
  86:     0x7fff2055d8fc - __pthread_start

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (34a6cae28 2022-08-09) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream`
#1 [mir_built] building MIR for `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream`
#2 [unsafety_check_result] unsafety-checking `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream`
#3 [mir_const] processing MIR for `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream`
#4 [mir_promoted] processing `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream`
#5 [mir_borrowck] borrow-checking `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream`
#6 [type_of] computing type of `executor::select::<impl at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-orm-0.8.0/src/executor/select.rs:113:1: 113:18>::stream::{opaque#0}`
#7 [check_mod_item_types] checking item types in module `executor::select`
#8 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `sea-orm`
```

**Comment by steffahn** [comment]
Looks like a duplicate of #100469 (same crate `SeaQL/sea-orm` as far as I can tell). Also that issue’s discussion mentions the issue is already fixed on nightly; @sjud, feel free to confirm or deny this by testing with something newer than nightly `2022-08-09`.

**Comment by compiler-errors** [comment]
This was fixed.
