### ISSUE TITLE
Unexpected panic when compiling rustdoc

### ISSUE THREAD

**Issue by chenyukang** [rust-lang/rust#101108]
`./x.py build` crash after rebase https://github.com/rust-lang/rust/commit/eaadb8947b850a025404082f6297766c4680a42a.

### Code

Generally, what I do is:

```bash
git pull upstream master
git checkout my-branch
git rebase master
./x.py build
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (9c20b2a8c 2022-08-17)
binary: rustc
commit-hash: 9c20b2a8cc7588decb6de25ac6a7912dcef24d65
commit-date: 2022-08-17
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

### Error output

```
<output>
```
<details><summary><strong>Backtrace</strong></summary>
<p>

```
cat@LAPTOP-V6U0QKD4:~/code/rust$ ./x.py build
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.12s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.18s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.56s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.10s
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building rustdoc for stage1 (x86_64-unknown-linux-gnu)
   Compiling rustdoc v0.0.0 (/home/cat/code/rust/src/librustdoc)
thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:644:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/option.rs:1874:5
   5: <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::stable_crate_id_to_crate_num
   6: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   7: <[(rustc_middle::ty::Predicate, rustc_span::span_encoding::Span)] as rustc_middle::ty::codec::RefDecodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   8: <rustc_query_impl::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle::ty::generics::GenericPredicates>
   9: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::predicates_of, rustc_query_impl::plumbing::QueryCtxt>
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
  11: rustc_ty_utils::ty::param_env
  12: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::ty::ParamEnv>
  13: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::param_env, rustc_query_impl::plumbing::QueryCtxt>
  14: rustc_typeck::check::wfcheck::check_well_formed
  15: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, ()>
  16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  17: rustc_query_system::query::plumbing::force_query::<rustc_query_impl::queries::check_well_formed, rustc_query_impl::plumbing::QueryCtxt>
  18: rustc_query_impl::query_callbacks::check_well_formed::force_from_dep_node
  19: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
  20: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  21: rustc_query_system::query::plumbing::ensure_must_run::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>
  22: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::check_mod_type_wf, rustc_query_impl::plumbing::QueryCtxt>
  23: <rustc_middle::hir::map::Map>::for_each_module::<rustc_typeck::check_crate::{closure#5}::{closure#0}::{closure#0}>
  24: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#5}, ()>
  25: rustc_typeck::check_crate
  26: rustc_interface::passes::analysis
  27: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  28: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  29: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  30: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  31: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  32: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  33: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-beta.1 (56714e533 2022-08-09) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -Z unstable-options -C incremental -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z binary-dep-depinfo -Z tls-model=initial-exec

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 207349', /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/compiler/rustc_query_system/src/dep_graph/graph.rs:450:25
stack backtrace:
   0:     0x7f9e16bb29f0 - std::backtrace_rs::backtrace::libunwind::trace::hc2aafb361b930ef6
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f9e16bb29f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h804481ad4855a013
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9e16bb29f0 - std::sys_common::backtrace::_print_fmt::hde719312690c42c7
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f9e16bb29f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3ac798ae3916ddb8
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f9e16c0e3bc - core::fmt::write::h56d0a26c056ebf7d
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f9e16ba3c35 - std::io::Write::write_fmt::hfc329b729ef3a4a4
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/io/mod.rs:1672:15
   6:     0x7f9e16bb56d1 - std::sys_common::backtrace::_print::h157d3034d56c5f2b
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f9e16bb56d1 - std::sys_common::backtrace::print::h8711cdaccf25c72b
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f9e16bb56d1 - std::panicking::default_hook::{{closure}}::h5a65e9070c5bad88
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:295:22
   9:     0x7f9e16bb539e - std::panicking::default_hook::h02eec242e22c1c0a
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:314:9
  10:     0x7f9e19429ab4 - rustc_driver[acf69d503f2fbc0f]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f9e16bb5f06 - std::panicking::rust_panic_with_hook::hd120b75e7be84603
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:702:17
  12:     0x7f9e16bb5d57 - std::panicking::begin_panic_handler::{{closure}}::he7b199a96ab3ad47
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:588:13
  13:     0x7f9e16bb2f14 - std::sys_common::backtrace::__rust_end_short_backtrace::h128233115a8d97ab
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f9e16bb5a82 - rust_begin_unwind
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:584:5
  15:     0x7f9e16c0ae93 - core::panicking::panic_fmt::h9ba2fa2bf5a290c7
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:142:14
  16:     0x7f9e1890f922 - rustc_query_system[2e598caf428403ff]::query::plumbing::get_query::<rustc_query_impl[a1817575795e40f3]::queries::def_span, rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  17:     0x7f9e1890d64e - <rustc_query_impl[a1817575795e40f3]::Queries as rustc_middle[b2160a7f10598e4]::ty::query::QueryEngine>::def_span
  18:     0x7f9e19d59f56 - <rustc_span[4ee036bbec706f06]::def_id::DefId as rustc_query_impl[a1817575795e40f3]::keys::Key>::default_span
  19:     0x7f9e19e28e64 - rustc_query_impl[a1817575795e40f3]::make_query::predicates_of
  20:     0x7f9e19ce3fc9 - <rustc_query_system[2e598caf428403ff]::query::plumbing::QueryState<rustc_span[4ee036bbec706f06]::def_id::DefId>>::try_collect_active_jobs::<rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  21:     0x7f9e19e23640 - <rustc_query_impl[a1817575795e40f3]::Queries>::try_collect_active_jobs
  22:     0x7f9e19e15c38 - <rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>::try_print_query_stack
  23:     0x7f9e194ccfcf - rustc_interface[50a00022d591bc14]::interface::try_print_query_stack
  24:     0x7f9e1942c0d6 - rustc_driver[acf69d503f2fbc0f]::report_ice
  25:     0x7f9e16bb5f06 - std::panicking::rust_panic_with_hook::hd120b75e7be84603
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:702:17
  26:     0x7f9e16bb5d57 - std::panicking::begin_panic_handler::{{closure}}::he7b199a96ab3ad47
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:588:13
  27:     0x7f9e16bb2f14 - std::sys_common::backtrace::__rust_end_short_backtrace::h128233115a8d97ab
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys_common/backtrace.rs:138:18
  28:     0x7f9e16bb5a82 - rust_begin_unwind
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/panicking.rs:584:5
  29:     0x7f9e16c0ae93 - core::panicking::panic_fmt::h9ba2fa2bf5a290c7
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:142:14
  30:     0x7f9e16c0ad51 - core::panicking::panic_display::hbfcb123bc44a2c20
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:72:5
  31:     0x7f9e16c0acfb - core::panicking::panic_str::h962e456a7a65e3f7
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/panicking.rs:56:5
  32:     0x7f9e16c0aa36 - core::option::expect_failed::h5739a3a57303cad0
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/core/src/option.rs:1874:5
  33:     0x7f9e1a031ffa - <rustc_metadata[d551b3bcc6264725]::creader::CStore as rustc_session[290e834ad62eeaf7]::cstore::CrateStore>::stable_crate_id_to_crate_num
  34:     0x7f9e18125395 - <rustc_span[4ee036bbec706f06]::span_encoding::Span as rustc_serialize[81a1dd3221d2b83]::serialize::Decodable<rustc_query_impl[a1817575795e40f3]::on_disk_cache::CacheDecoder>>::decode
  35:     0x7f9e18207ca2 - <[(rustc_middle[b2160a7f10598e4]::ty::Predicate, rustc_span[4ee036bbec706f06]::span_encoding::Span)] as rustc_middle[b2160a7f10598e4]::ty::codec::RefDecodable<rustc_query_impl[a1817575795e40f3]::on_disk_cache::CacheDecoder>>::decode
  36:     0x7f9e182076b3 - <rustc_query_impl[a1817575795e40f3]::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle[b2160a7f10598e4]::ty::generics::GenericPredicates>
  37:     0x7f9e186854ad - rustc_query_system[2e598caf428403ff]::query::plumbing::get_query::<rustc_query_impl[a1817575795e40f3]::queries::predicates_of, rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  38:     0x7f9e186846fe - <rustc_query_impl[a1817575795e40f3]::Queries as rustc_middle[b2160a7f10598e4]::ty::query::QueryEngine>::predicates_of
  39:     0x7f9e18068872 - rustc_ty_utils[f8c6b4a2d9639d59]::ty::param_env
  40:     0x7f9e189b7f7c - <rustc_query_system[2e598caf428403ff]::dep_graph::graph::DepGraph<rustc_middle[b2160a7f10598e4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b2160a7f10598e4]::ty::context::TyCtxt, rustc_span[4ee036bbec706f06]::def_id::DefId, rustc_middle[b2160a7f10598e4]::ty::ParamEnv>
  41:     0x7f9e189b69f0 - rustc_query_system[2e598caf428403ff]::query::plumbing::get_query::<rustc_query_impl[a1817575795e40f3]::queries::param_env, rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  42:     0x7f9e18689ec4 - rustc_typeck[b2fd0ce1781ed2]::check::wfcheck::check_well_formed
  43:     0x7f9e18665a32 - <rustc_query_system[2e598caf428403ff]::dep_graph::graph::DepGraph<rustc_middle[b2160a7f10598e4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b2160a7f10598e4]::ty::context::TyCtxt, rustc_span[4ee036bbec706f06]::def_id::LocalDefId, ()>
  44:     0x7f9e18664bbe - rustc_query_system[2e598caf428403ff]::query::plumbing::try_execute_query::<rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt, rustc_query_system[2e598caf428403ff]::query::caches::DefaultCache<rustc_span[4ee036bbec706f06]::def_id::LocalDefId, ()>>
  45:     0x7f9e19129c89 - rustc_query_system[2e598caf428403ff]::query::plumbing::force_query::<rustc_query_impl[a1817575795e40f3]::queries::check_well_formed, rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  46:     0x7f9e19129afe - rustc_query_impl[a1817575795e40f3]::query_callbacks::check_well_formed::force_from_dep_node
  47:     0x7f9e17dc53a1 - <rustc_middle[b2160a7f10598e4]::ty::context::TyCtxt as rustc_query_system[2e598caf428403ff]::dep_graph::DepContext>::try_force_from_dep_node
  48:     0x7f9e17dc47c6 - <rustc_query_system[2e598caf428403ff]::dep_graph::graph::DepGraph<rustc_middle[b2160a7f10598e4]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  49:     0x7f9e17e068c1 - rustc_query_system[2e598caf428403ff]::query::plumbing::ensure_must_run::<rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt, rustc_span[4ee036bbec706f06]::def_id::LocalDefId, &rustc_middle[b2160a7f10598e4]::mir::query::BorrowCheckResult>
  50:     0x7f9e18e7110f - rustc_query_system[2e598caf428403ff]::query::plumbing::get_query::<rustc_query_impl[a1817575795e40f3]::queries::check_mod_type_wf, rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  51:     0x7f9e18e0896f - <rustc_middle[b2160a7f10598e4]::hir::map::Map>::for_each_module::<rustc_typeck[b2fd0ce1781ed2]::check_crate::{closure#5}::{closure#0}::{closure#0}>
  52:     0x7f9e18e07322 - <rustc_session[290e834ad62eeaf7]::session::Session>::track_errors::<rustc_typeck[b2fd0ce1781ed2]::check_crate::{closure#5}, ()>
  53:     0x7f9e18e06e80 - rustc_typeck[b2fd0ce1781ed2]::check_crate
  54:     0x7f9e18e06517 - rustc_interface[50a00022d591bc14]::passes::analysis
  55:     0x7f9e191bbdac - <rustc_query_system[2e598caf428403ff]::dep_graph::graph::DepGraph<rustc_middle[b2160a7f10598e4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b2160a7f10598e4]::ty::context::TyCtxt, (), core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>
  56:     0x7f9e191bb56b - rustc_query_system[2e598caf428403ff]::query::plumbing::try_execute_query::<rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt, rustc_query_system[2e598caf428403ff]::query::caches::DefaultCache<(), core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>>
  57:     0x7f9e191bb0be - rustc_query_system[2e598caf428403ff]::query::plumbing::get_query::<rustc_query_impl[a1817575795e40f3]::queries::analysis, rustc_query_impl[a1817575795e40f3]::plumbing::QueryCtxt>
  58:     0x7f9e18bf353a - <rustc_interface[50a00022d591bc14]::interface::Compiler>::enter::<rustc_driver[acf69d503f2fbc0f]::run_compiler::{closure#1}::{closure#2}, core[4b7224d7e913b755]::result::Result<core[4b7224d7e913b755]::option::Option<rustc_interface[50a00022d591bc14]::queries::Linker>, rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>
  59:     0x7f9e18be6f5a - rustc_span[4ee036bbec706f06]::with_source_map::<core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>, rustc_interface[50a00022d591bc14]::interface::create_compiler_and_run<core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>, rustc_driver[acf69d503f2fbc0f]::run_compiler::{closure#1}>::{closure#1}>
  60:     0x7f9e18be6930 - rustc_interface[50a00022d591bc14]::interface::create_compiler_and_run::<core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>, rustc_driver[acf69d503f2fbc0f]::run_compiler::{closure#1}>
  61:     0x7f9e18be4ca1 - <scoped_tls[b32c5badeee3a461]::ScopedKey<rustc_span[4ee036bbec706f06]::SessionGlobals>>::set::<rustc_interface[50a00022d591bc14]::interface::run_compiler<core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>, rustc_driver[acf69d503f2fbc0f]::run_compiler::{closure#1}>::{closure#0}, core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>
  62:     0x7f9e18be498f - std[e93aab33ab818310]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[50a00022d591bc14]::util::run_in_thread_pool_with_globals<rustc_interface[50a00022d591bc14]::interface::run_compiler<core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>, rustc_driver[acf69d503f2fbc0f]::run_compiler::{closure#1}>::{closure#0}, core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>::{closure#0}, core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>
  63:     0x7f9e1924cfb9 - <<std[e93aab33ab818310]::thread::Builder>::spawn_unchecked_<rustc_interface[50a00022d591bc14]::util::run_in_thread_pool_with_globals<rustc_interface[50a00022d591bc14]::interface::run_compiler<core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>, rustc_driver[acf69d503f2fbc0f]::run_compiler::{closure#1}>::{closure#0}, core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>::{closure#0}, core[4b7224d7e913b755]::result::Result<(), rustc_errors[418a143e0b6d828f]::ErrorGuaranteed>>::{closure#1} as core[4b7224d7e913b755]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  64:     0x7f9e16bbfed3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hafebb5a654285d1f
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/alloc/src/boxed.rs:1935:9
  65:     0x7f9e16bbfed3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd7f46a8cec019e0f
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/alloc/src/boxed.rs:1935:9
  66:     0x7f9e16bbfed3 - std::sys::unix::thread::Thread::new::thread_start::hcd40f54db19fb2e5
                               at /rustc/56714e5332f5f21c39d710cc4a6dd279132dedd6/library/std/src/sys/unix/thread.rs:108:17
  67:     0x7f9e16a88609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  68:     0x7f9e169ab133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  69:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-beta.1 (56714e533 2022-08-09) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -Z unstable-options -C incremental -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z binary-dep-depinfo -Z tls-model=initial-exec

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
rustc exited with signal: 6 (SIGABRT)
error: could not compile `rustdoc`

Caused by:
  process didn't exit successfully: `/home/cat/code/rust/build/bootstrap/debug/rustc --crate-name rustdoc --edition=2021 src/librustdoc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -Zunstable-options --check-cfg 'values(feature, "jemalloc")' --check-cfg 'names()' --check-cfg 'values()' -C metadata=d70c8166fcf34778 -C extra-filename=-d70c8166fcf34778 --out-dir /home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C incremental=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/incremental -L dependency=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/release/deps --extern arrayvec=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libarrayvec-83fa309bbb3533dc.rmeta --extern askama=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libaskama-cc91a242c4ae7370.rmeta --extern atty=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libatty-2fceb4a89aeb0ec7.rmeta --extern itertools=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-72fd1158fdec39c6.rmeta --extern minifier=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libminifier-21399499f7d5db69.rmeta --extern once_cell=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libonce_cell-d885ef460db83f71.rmeta --extern pulldown_cmark=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libpulldown_cmark-32540f3bfb00bfbb.rmeta --extern regex=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libregex-02dea0b57b8293a3.rmeta --extern rustdoc_json_types=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/librustdoc_json_types-dad497f4cec17f1d.rmeta --extern serde=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libserde-120e7f3a31d6bbbf.rmeta --extern serde_json=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libserde_json-c0d6d0ccc4a7ff84.rmeta --extern smallvec=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libsmallvec-e5f0acb4b86067e2.rmeta --extern tempfile=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtempfile-c0d231d97f3f0822.rmeta --extern tracing=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtracing-4336127098d1e826.rmeta --extern tracing_subscriber=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtracing_subscriber-e444f60a6fcaa5cf.rmeta --extern tracing_tree=/home/cat/code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtracing_tree-9a138ed877bef3e5.rmeta --cfg=bootstrap -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(release)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)' -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Cllvm-args=-import-instr-limit=10 -Z binary-dep-depinfo` (exit status: 254)
Build completed unsuccessfully in 0:00:03
```

</p>
</details>

**Comment by chenyukang** [comment]
`./x.py clean` and the build will resolve the crash, I guess the are some deps issues when updated the source code of compiler without cleanup the old deps.
