### ISSUE TITLE
error: internal compiler error: src/value_and_place.rs:160:38: Please use load_scalar for ByVal

### ISSUE THREAD

**Issue by not-rusty** [rust-lang/rust#101226]
### Code

(No code)
I'm trying to compile latest helix version to try rustc_codegen_cranelift. Apparently the ropey 1.5.0 dependency breaks. I don't know if I should post here this, I'm just following orders from the stacktrace.

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/value_and_place.rs:160:38: Please use load_scalar for ByVal

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/compiler/rustc_errors/src/lib.rs:1453:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   Compiling futures-util v0.3.23
   7: rustc_codegen_cranelift::value_and_place::CValue::load_scalar_pair
   8: rustc_codegen_cranelift::value_and_place::CPlace::write_cvalue_maybe_transmute
   9: rustc_codegen_cranelift::intrinsics::codegen_regular_intrinsic_call
  10: rustc_codegen_cranelift::intrinsics::codegen_intrinsic_call
  11: rustc_codegen_cranelift::abi::codegen_terminator_call
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_codegen_cranelift::base::codegen_fn_body
  14: rustc_session::utils::<impl rustc_session::session::Session>::time
  15: rustc_codegen_cranelift::base::codegen_fn
  16: rustc_session::utils::<impl rustc_session::session::Session>::time
  17: rustc_codegen_cranelift::driver::aot::module_codegen
  18: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  21: rustc_session::utils::<impl rustc_session::session::Session>::time
  22: rustc_codegen_cranelift::driver::time
  23: rustc_codegen_cranelift::driver::aot::run_aot
  24: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  25: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  26: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  27: <rustc_interface::queries::Queries>::ongoing_codegen
  28: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  29: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  30: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  31: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (060e47f74 2022-08-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C panic=abort -Z panic-abort-tests -Z codegen-backend=/home/guillem/projects/rust/rustc_codegen_cranelift/build/lib/librustc_codegen_cranelift.so

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
   Compiling grep-searcher v0.1.10
fn <std::arch::x86_64::__m128i as str_indices::byte_chunk::ByteChunk>::sum_bytes(_1: &std::arch::x86_64::__m128i) -> usize {
    debug self => _1;                    // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:249:18: 249:23
    let mut _0: usize;                   // return place in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:249:28: 249:33
    let _2: std::arch::x86_64::__m128i;  // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:13: 250:21
    let mut _3: std::arch::x86_64::__m128i; // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:54: 250:59
    let mut _4: std::arch::x86_64::__m128i; // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:61: 250:88
    let mut _7: (u64, u64);              // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:27: 251:88
    let mut _8: std::arch::x86_64::__m128i; // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:77: 251:85
    let mut _9: u64;                     // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:9: 252:21
    let mut _10: u64;                    // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:10: 252:13
    let mut _11: u64;                    // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:16: 252:20
    let mut _12: (u64, bool);            // in scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:9: 252:21
    scope 1 {
        debug half_sum => _2;            // in scope 1 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:13: 250:21
        let _5: u64;                     // in scope 1 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:14: 251:17
        let _6: u64;                     // in scope 1 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:19: 251:23
        scope 3 {
            debug low => _5;             // in scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:14: 251:17
            debug high => _6;            // in scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:19: 251:23
        }
        scope 4 {
        }
    }
    scope 2 {
    }

    bb0: {
        _3 = (*_1);                      // scope 2 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:54: 250:59
        _4 = std::arch::x86_64::_mm_setzero_si128() -> bb1; // scope 2 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:61: 250:88
                                         // mir::Constant
                                         // + span: /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:61: 250:86
                                         // + literal: Const { ty: unsafe fn() -> std::arch::x86_64::__m128i {std::arch::x86_64::_mm_setzero_si128}, val: Value(<ZST>) }
    }

    bb1: {
        _2 = std::arch::x86_64::_mm_sad_epu8(move _3, move _4) -> bb2; // scope 2 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:33: 250:89
                                         // mir::Constant
                                         // + span: /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:250:33: 250:53
                                         // + literal: Const { ty: unsafe fn(std::arch::x86_64::__m128i, std::arch::x86_64::__m128i) -> std::arch::x86_64::__m128i {std::arch::x86_64::_mm_sad_epu8}, val: Value(<ZST>) }
    }

    bb2: {
        _8 = _2;                         // scope 4 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:77: 251:85
        _7 = std::intrinsics::transmute::<std::arch::x86_64::__m128i, (u64, u64)>(move _8) -> bb3; // scope 4 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:36: 251:86
                                         // mir::Constant
                                         // + span: /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:36: 251:76
                                         // + literal: Const { ty: unsafe extern "rust-intrinsic" fn(std::arch::x86_64::__m128i) -> (u64, u64) {std::intrinsics::transmute::<std::arch::x86_64::__m128i, (u64, u64)>}, val: Value(<ZST>) }
    }

    bb3: {
        _5 = (_7.0: u64);                // scope 1 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:14: 251:17
        _6 = (_7.1: u64);                // scope 1 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:251:19: 251:23
        _10 = _5;                        // scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:10: 252:13
        _11 = _6;                        // scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:16: 252:20
        _12 = CheckedAdd(_10, _11);      // scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:9: 252:21
        assert(!move (_12.1: bool), "attempt to compute `{} + {}`, which would overflow", move _10, move _11) -> bb4; // scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:9: 252:21
    }

    bb4: {
        _9 = move (_12.0: u64);          // scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:9: 252:21
        _0 = move _9 as usize (Misc);    // scope 3 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:252:9: 252:30
        return;                          // scope 0 at /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/str_indices-0.4.0/src/byte_chunk.rs:253:6: 253:6
    }
}

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `9`,
 right: `0`', src/concurrency_limiter.rs:112:13
stack backtrace:
   0:     0x7f0860982750 - std::backtrace_rs::backtrace::libunwind::trace::h18bb8883b170e61e
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f0860982750 - std::backtrace_rs::backtrace::trace_unsynchronized::hfbfd04778228f53a
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f0860982750 - std::sys_common::backtrace::_print_fmt::hf014d9c7ceb4c50b
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f0860982750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0cff30d852e41e28
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f08609dda5e - core::fmt::write::hf3278c297bc3e8c3
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f08609734d5 - std::io::Write::write_fmt::hb3fb7e9de918605f
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/io/mod.rs:1672:15
   6:     0x7f0860985413 - std::sys_common::backtrace::_print::hb735a2b0aa8c9126
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f0860985413 - std::sys_common::backtrace::print::h1d481f5d3b90ee64
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f0860985413 - std::panicking::default_hook::{{closure}}::h3cda275262afb117
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:295:22
   9:     0x7f08609850ff - std::panicking::default_hook::h2eba6d64b7e32862
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:314:9
  10:     0x7f08631d34e4 - <rustc_driver[b627559a5a77e284]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[e3f13d716672aa]::ops::function::FnOnce<(&core[e3f13d716672aa]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f0860985c4d - std::panicking::rust_panic_with_hook::hfaad0ec4972467c1
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:702:17
  12:     0x7f0860985aa7 - std::panicking::begin_panic_handler::{{closure}}::h401c5684148433ac
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:588:13
  13:     0x7f0860982c5c - std::sys_common::backtrace::__rust_end_short_backtrace::h356ecf2a7ec67271
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f08609857c2 - rust_begin_unwind
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/panicking.rs:584:5
  15:     0x7f08609da573 - core::panicking::panic_fmt::h9555dfef52eae25e
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/core/src/panicking.rs:142:14
  16:     0x7f08609da75b - core::panicking::assert_failed_inner::h7833264dc5441caa
  17:     0x7f085945199b - core::panicking::assert_failed::h49e4008385c22532
  18:     0x7f0859506595 - <rustc_codegen_cranelift::concurrency_limiter::ConcurrencyLimiter as core::ops::drop::Drop>::drop::h47936e304c402f36
  19:     0x7f085950473e - core::ptr::drop_in_place<rustc_codegen_cranelift::concurrency_limiter::ConcurrencyLimiter>::hbfa5a20a7dea4c0e
  20:     0x7f0859497cac - rustc_codegen_cranelift::driver::aot::run_aot::h45ea525f9bfee586
  21:     0x7f0859553cf9 - <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::ha97be491f7d63663
  22:     0x7f0862acac3c - <rustc_session[909454c3b87246db]::session::Session>::time::<alloc[762648e69aa85342]::boxed::Box<dyn core[e3f13d716672aa]::any::Any>, rustc_interface[bf5d5e33b83f0123]::passes::start_codegen::{closure#0}>
  23:     0x7f0862aca573 - <rustc_interface[bf5d5e33b83f0123]::passes::QueryContext>::enter::<<rustc_interface[bf5d5e33b83f0123]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[e3f13d716672aa]::result::Result<alloc[762648e69aa85342]::boxed::Box<dyn core[e3f13d716672aa]::any::Any>, rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>
  24:     0x7f0862a8c1a3 - <rustc_interface[bf5d5e33b83f0123]::queries::Queries>::ongoing_codegen
  25:     0x7f0862a8b281 - <rustc_interface[bf5d5e33b83f0123]::interface::Compiler>::enter::<rustc_driver[b627559a5a77e284]::run_compiler::{closure#1}::{closure#2}, core[e3f13d716672aa]::result::Result<core[e3f13d716672aa]::option::Option<rustc_interface[bf5d5e33b83f0123]::queries::Linker>, rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>
  26:     0x7f0862a86d5c - rustc_span[bead5e57778f0b1b]::with_source_map::<core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>, rustc_interface[bf5d5e33b83f0123]::interface::create_compiler_and_run<core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>, rustc_driver[b627559a5a77e284]::run_compiler::{closure#1}>::{closure#1}>
  27:     0x7f0862a867d2 - rustc_interface[bf5d5e33b83f0123]::interface::create_compiler_and_run::<core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>, rustc_driver[b627559a5a77e284]::run_compiler::{closure#1}>
  28:     0x7f0862a852c1 - <scoped_tls[c2b62212662a5735]::ScopedKey<rustc_span[bead5e57778f0b1b]::SessionGlobals>>::set::<rustc_interface[bf5d5e33b83f0123]::interface::run_compiler<core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>, rustc_driver[b627559a5a77e284]::run_compiler::{closure#1}>::{closure#0}, core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>
  29:     0x7f0862a84faf - std[bb5449232b08fe6e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bf5d5e33b83f0123]::util::run_in_thread_pool_with_globals<rustc_interface[bf5d5e33b83f0123]::interface::run_compiler<core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>, rustc_driver[b627559a5a77e284]::run_compiler::{closure#1}>::{closure#0}, core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>::{closure#0}, core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>
  30:     0x7f0862ff2059 - <<std[bb5449232b08fe6e]::thread::Builder>::spawn_unchecked_<rustc_interface[bf5d5e33b83f0123]::util::run_in_thread_pool_with_globals<rustc_interface[bf5d5e33b83f0123]::interface::run_compiler<core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>, rustc_driver[b627559a5a77e284]::run_compiler::{closure#1}>::{closure#0}, core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>::{closure#0}, core[e3f13d716672aa]::result::Result<(), rustc_errors[96dfb46f0b8980b]::ErrorGuaranteed>>::{closure#1} as core[e3f13d716672aa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x7f086098f7a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd8b4f77c73b6de54
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/alloc/src/boxed.rs:1940:9
  32:     0x7f086098f7a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h396dcf115ad932d5
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/alloc/src/boxed.rs:1940:9
  33:     0x7f086098f7a3 - std::sys::unix::thread::Thread::new::thread_start::h004395cd09d806b0
                               at /rustc/060e47f74a91b28c3db28d80a6a9d6841ca51026/library/std/src/sys/unix/thread.rs:108:17
  34:     0x7f086084c609 - start_thread
                               at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  35:     0x7f086076f163 - clone
  36:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (060e47f74 2022-08-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C panic=abort -Z panic-abort-tests -Z codegen-backend=/home/guillem/projects/rust/rustc_codegen_cranelift/build/lib/librustc_codegen_cranelift.so

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
   Compiling pulldown-cmark v0.9.2
   Compiling signal-hook-mio v0.2.3
   Compiling chrono v0.4.22
error: could not compile `ropey`

Caused by:
  process didn't exit successfully: `rustc --crate-name ropey /home/guillem/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="simd"' -C metadata=9515ed5bbb54e2b2 -C extra-filename=-9515ed5bbb54e2b2 --out-dir /home/guillem/projects/rust/helix/target/debug/deps -L dependency=/home/guillem/projects/rust/helix/target/debug/deps --extern smallvec=/home/guillem/projects/rust/helix/target/debug/deps/libsmallvec-5dbbcca6932bec01.rmeta --extern str_indices=/home/guillem/projects/rust/helix/target/debug/deps/libstr_indices-c757a6f6cc5b5323.rmeta --cap-lints allow -Cpanic=abort -Zpanic-abort-tests -Zcodegen-backend=/home/guillem/projects/rust/rustc_codegen_cranelift/build/lib/librustc_codegen_cranelift.so --sysroot /home/guillem/projects/rust/rustc_codegen_cranelift/build` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...


```

</p>
</details>

**Comment by compiler-errors** [comment]
@not-rusty can you please provide more detailed instructions on how to reproduce this?

**Comment by BGR360** [comment]
I presume by "helix" you're referring to https://github.com/helix-editor/helix

**Comment by not-rusty** [comment]
@BGR360  yes

I guess that to try to reproduce this, one should compile the helix editor with the cranelift_codegen backend

**Comment by bjorn3** [comment]
Thanks for reporting this issue! I don't actively look at cg_clif related issues in the rust issue tracker, so I didn't see this issue until just now. I have opened https://github.com/bjorn3/rustc_codegen_cranelift/issues/1292 over at cg_clif's repo to keep track of it.

**Comment by bjorn3** [comment]
Fixed in https://github.com/bjorn3/rustc_codegen_cranelift/commit/777d4732dc2389752ebaa4fc7256245c4873bc25.
