### ISSUE TITLE
Rustc panic "no label after fn" on invalid struct with Serde

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#101321]
I tried this [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c16a39e1cd58a77243e62f9faad8702c):

```rust
﻿use serde::Deserialize;

#[derive(Deserialize)]
struct Test<'a, str> {}
```

I expected to see this happen: Compilation error

Instead, this happened:
```
  Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'no label after fn', compiler/rustc_span/src/source_map.rs:972:18
stack backtrace:
   0:     0x7f446a9f918d - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f446a9f918d - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f446a9f918d - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f446a9f918d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f446aa54f7c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x7f446a9ea8a1 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x7f446a9fbe55 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f446a9fbe55 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f446a9fbe55 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x7f446a9fbb76 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x7f446b1d6b54 - rustc_driver[e01eec72899701d3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f445c1ea343 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h05e4048952ebd0e1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1965:9
  12:     0x7f445c16589d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::ha490d0e93b9d7a7b
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/proc_macro/src/bridge/client.rs:328:21
  13:     0x7f446a9fc52a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  14:     0x7f446a9fc367 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  15:     0x7f446a9f9644 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7f446a9fc099 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  17:     0x7f446a9c1253 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  18:     0x7f446aa51be1 - core::panicking::panic_display::h20fe9d7f27d4d64a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
  19:     0x7f446aa51b8b - core::panicking::panic_str::h00c94914e747c9f5
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
  20:     0x7f446a9c10c6 - core::option::expect_failed::h0322fe3c07a466dd
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
  21:     0x7f446c4bdce9 - <rustc_span[fb9cf5df1e5e5539]::source_map::SourceMap>::generate_fn_name_span
  22:     0x7f446b68a418 - <rustc_resolve[49a12e10a2b9467f]::Resolver>::into_struct_error
  23:     0x7f446b68734f - <rustc_resolve[49a12e10a2b9467f]::Resolver>::report_error
  24:     0x7f446c932b5e - <rustc_resolve[49a12e10a2b9467f]::Resolver>::resolve_path_with_ribs
  25:     0x7f446c8fceaa - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor>::smart_resolve_path_fragment
  26:     0x7f446c8e3589 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_ty
  27:     0x7f446c8e3b07 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_ty
  28:     0x7f446c8e7f32 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_fn
  29:     0x7f446c8efc9e - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor>::resolve_item
  30:     0x7f446c8e24d0 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_item
  31:     0x7f446c8e2cba - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_block
  32:     0x7f446c8e81cc - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_fn
  33:     0x7f446c8efc9e - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor>::resolve_item
  34:     0x7f446c8e24d0 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_item
  35:     0x7f446c8e2cba - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_block
  36:     0x7f446c90111b - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor>::resolve_expr
  37:     0x7f446c8f17c9 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor>::resolve_item
  38:     0x7f446c8e24d0 - <rustc_resolve[49a12e10a2b9467f]::late::LateResolutionVisitor as rustc_ast[f0424a11a3737d19]::visit::Visitor>::visit_item
  39:     0x7f446d6c788c - <rustc_resolve[49a12e10a2b9467f]::Resolver>::late_resolve_crate
  40:     0x7f446d6b734a - <rustc_session[72c90254a58d88d1]::session::Session>::time::<(), <rustc_resolve[49a12e10a2b9467f]::Resolver>::resolve_crate::{closure#0}>
  41:     0x7f446d3b4d7a - rustc_interface[be6c6c80f2cd8cf2]::passes::configure_and_expand
  42:     0x7f446d3df473 - <rustc_interface[be6c6c80f2cd8cf2]::queries::Queries>::expansion
  43:     0x7f446d38737a - <rustc_interface[be6c6c80f2cd8cf2]::interface::Compiler>::enter::<rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}::{closure#2}, core[3edb0f9afb6adb32]::result::Result<core[3edb0f9afb6adb32]::option::Option<rustc_interface[be6c6c80f2cd8cf2]::queries::Linker>, rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  44:     0x7f446d380a7f - rustc_span[fb9cf5df1e5e5539]::with_source_map::<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_interface[be6c6c80f2cd8cf2]::interface::create_compiler_and_run<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#1}>
  45:     0x7f446d388302 - <scoped_tls[134a193f706323ee]::ScopedKey<rustc_span[fb9cf5df1e5e5539]::SessionGlobals>>::set::<rustc_interface[be6c6c80f2cd8cf2]::interface::run_compiler<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  46:     0x7f446d3ab99f - std[f9ee9c7d4fd68eda]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[be6c6c80f2cd8cf2]::util::run_in_thread_pool_with_globals<rustc_interface[be6c6c80f2cd8cf2]::interface::run_compiler<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>
  47:     0x7f446d39d529 - <<std[f9ee9c7d4fd68eda]::thread::Builder>::spawn_unchecked_<rustc_interface[be6c6c80f2cd8cf2]::util::run_in_thread_pool_with_globals<rustc_interface[be6c6c80f2cd8cf2]::interface::run_compiler<core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>, rustc_driver[e01eec72899701d3]::run_compiler::{closure#1}>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>::{closure#0}, core[3edb0f9afb6adb32]::result::Result<(), rustc_errors[b2e8492a1747ee42]::ErrorGuaranteed>>::{closure#1} as core[3edb0f9afb6adb32]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7f446aa06463 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1680342795a2dc08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  49:     0x7f446aa06463 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45204a69827b0e83
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  50:     0x7f446aa06463 - std::sys::unix::thread::Thread::new::thread_start::h5d4e11bbda4161c8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f446a92c609 - start_thread
  52:     0x7f446a84f133 - clone
  53:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0 (4b91a6ea7 2022-08-08) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`
```

### Meta

```
rustc --version --verbose
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: aarch64-apple-darwin
release: 1.63.0
LLVM version: 14.0.5
```

</p>
</details>

**Comment by In-line** [comment]
Not reproducible on beta or nightly. Not sure, if I need to close this.

**Comment by compiler-errors** [comment]
Yeah, if it's not reproducible on beta or nightly then it's fixed. I'll close this, thanks for reporting!
