### ISSUE TITLE
thread 'rustc' panicked at 'no entry for node id: `NodeId(139092)`', compiler\rustc_ast_lowering\src\lib.rs:523:55

### ISSUE THREAD

**Issue by PFAhard** [rust-lang/rust#101415]
### Meta

I don't know if it compiles with the stable version because the code uses unstable features. Also doesn't seem relevant to the code, because reverting to the last successful commit doesn't work either.

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (c07a8b4e0 2022-08-26)
binary: rustc
commit-hash: c07a8b4e09f356c7468b69c50cac7fc5b5000b8a
commit-date: 2022-08-26
host: x86_64-pc-windows-msvc
release: 1.65.0-nightly
LLVM version: 15.0.0
```

command:

```
cargo clean && cargo build

compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental
```

### Error output

```
thread 'rustc' panicked at 'no entry for node id: `NodeId(139092)`', compiler\rustc_ast_lowering\src\lib.rs:523:55
stack backtrace:
   0:     0x7ff84e3a8cb6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf8210fa835a16a5
   1:     0x7ff84e3e428b - core::fmt::write::h1f5caf3dbd9420d0
   2:     0x7ff84e39b88a - <std::io::IoSlice as core::fmt::Debug>::fmt::h755e0aba9edd4504
   3:     0x7ff84e3ac434 - std::panicking::default_hook::ha4a4bcb5c9938ea7
   4:     0x7ff84e3ac06a - std::panicking::default_hook::ha4a4bcb5c9938ea7
   5:     0x7ff848a3ae8e - rustc_driver[4bc29db7fa6a984b]::describe_lints
   6:     0x7ff84e3ace32 - std::panicking::rust_panic_with_hook::h2b8e759989d1d193
   7:     0x7ff84e3acbbd - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h10d78d084596fee5
   8:     0x7ff84e3a99bf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf8210fa835a16a5
   9:     0x7ff84e3ac880 - rust_begin_unwind
  10:     0x7ff84e419625 - core::panicking::panic_fmt::heccde9d03cbc1a6d
  11:     0x7ff846a838e5 - <rustc_ast_lowering[6281666d600a521c]::index_crate::Indexer as rustc_ast[733dbb6f10d5fad0]::visit::Visitor>::visit_foreign_item
  12:     0x7ff846a890cd - <rustc_ast_lowering[6281666d600a521c]::index_crate::Indexer as rustc_ast[733dbb6f10d5fad0]::visit::Visitor>::visit_foreign_item
  13:     0x7ff847d86303 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  14:     0x7ff847d9d307 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  15:     0x7ff847d786ce - <rustc_mir_transform[ff2d91deca6a4573]::remove_noop_landing_pads::RemoveNoopLandingPads as rustc_middle[da574927bfa7926c]::mir::MirPass>::run_pass
  16:     0x7ff847d970e2 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  17:     0x7ff847ddbc08 - <rustc_ast_lowering[6281666d600a521c]::index::NodeCollector as rustc_hir[95355f4b5afb8c36]::intravisit::Visitor>::visit_trait_ref
  18:     0x7ff847d7eb21 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  19:     0x7ff846d81325 - <&rustc_index[be4fabed3c045652]::vec::IndexVec<rustc_middle[da574927bfa7926c]::mir::Promoted, rustc_middle[da574927bfa7926c]::mir::Body> as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  20:     0x7ff846eedf8f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  21:     0x7ff846de95be - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  22:     0x7ff846ebcd5f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  23:     0x7ff8488e6060 - <rustc_middle[da574927bfa7926c]::ty::context::TyCtxt>::instance_mir
  24:     0x7ff8484a657a - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7ff848492315 - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  26:     0x7ff84836aeda - <rustc_query_impl[b505e6b5e14c3243]::Queries as rustc_middle[da574927bfa7926c]::ty::query::QueryEngine>::as_any
  27:     0x7ff8471945fb - <rustc_middle[da574927bfa7926c]::hir::map::Map>::get_module
  28:     0x7ff84719679d - <rustc_middle[da574927bfa7926c]::hir::map::Map as rustc_hir[95355f4b5afb8c36]::intravisit::Map>::trait_item
  29:     0x7ff846d81325 - <&rustc_index[be4fabed3c045652]::vec::IndexVec<rustc_middle[da574927bfa7926c]::mir::Promoted, rustc_middle[da574927bfa7926c]::mir::Body> as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  30:     0x7ff846eec93c - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7ff846deedb8 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  32:     0x7ff846e7e36f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  33:     0x7ff84726309d - tracing_core[cdfe675b129e512e]::callsite::register_dispatch
  34:     0x7ff84a565069 - <rustc_query_impl[b505e6b5e14c3243]::queries::permits_zero_init as rustc_query_system[5c215ea2856b3a09]::query::config::QueryDescription<rustc_query_impl[b505e6b5e14c3243]::plumbing::QueryCtxt>>::describe
  35:     0x7ff84a6a9c9c - <&[rustc_middle[da574927bfa7926c]::ty::abstract_const::Node] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  36:     0x7ff846e30e02 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7ff846ea19f5 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  38:     0x7ff846350195 - <rustc_interface[d17d6a4a7f0ecc1c]::queries::Linker>::link
  39:     0x7ff846351c5f - <rustc_interface[d17d6a4a7f0ecc1c]::queries::Linker>::link
  40:     0x7ff84636194d - rustc_interface[d17d6a4a7f0ecc1c]::passes::analysis
  41:     0x7ff846d811de - <&rustc_index[be4fabed3c045652]::vec::IndexVec<rustc_middle[da574927bfa7926c]::mir::Promoted, rustc_middle[da574927bfa7926c]::mir::Body> as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  42:     0x7ff846eebad3 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7ff846e347b2 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7ff846ebc68f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7ff8463273c6 - <unknown>
  46:     0x7ff846306cf8 - <unknown>
  47:     0x7ff846302c1a - <unknown>
  48:     0x7ff846322303 - <unknown>
  49:     0x7ff846337ab7 - <rustc_middle[da574927bfa7926c]::ty::SymbolName as core[925e9186cc1e8cee]::fmt::Debug>::fmt
  50:     0x7ff846306679 - <unknown>
  51:     0x7ff846327ced - <unknown>
  52:     0x7ff84e3bd7ac - std::sys::windows::thread::Thread::new::he38aace67bdea9d1
  53:     0x7ff889cd7034 - BaseThreadInitThunk
  54:     0x7ff88bae2651 - RtlUserThreadStart

error: internal compiler error: unexpected panic
```

### Error output

```
query stack during panic:
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/c07a8b4e09f356c7468b69c50cac7fc5b5000b8a\compiler\rustc_query_system\src\query\plumbing.rs:341:11
stack backtrace:
   0:     0x7ff84e3a8cb6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf8210fa835a16a5
   1:     0x7ff84e3e428b - core::fmt::write::h1f5caf3dbd9420d0
   2:     0x7ff84e39b88a - <std::io::IoSlice as core::fmt::Debug>::fmt::h755e0aba9edd4504
   3:     0x7ff84e3ac434 - std::panicking::default_hook::ha4a4bcb5c9938ea7
   4:     0x7ff84e3ac06a - std::panicking::default_hook::ha4a4bcb5c9938ea7
   5:     0x7ff848a3ae8e - rustc_driver[4bc29db7fa6a984b]::describe_lints
   6:     0x7ff84e3ace32 - std::panicking::rust_panic_with_hook::h2b8e759989d1d193
   7:     0x7ff84e3acb7a - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h10d78d084596fee5
   8:     0x7ff84e3a99bf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf8210fa835a16a5
   9:     0x7ff84e3ac880 - rust_begin_unwind
  10:     0x7ff84e419625 - core::panicking::panic_fmt::heccde9d03cbc1a6d
  11:     0x7ff84e4194cc - core::panicking::panic::h0ca1aad646f02a19
  12:     0x7ff846dea017 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  13:     0x7ff846ebcd5f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  14:     0x7ff8488e3ec7 - <rustc_middle[da574927bfa7926c]::ty::context::TyCtxt>::instance_mir
  15:     0x7ff8484a72d2 - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  16:     0x7ff848470505 - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  17:     0x7ff8488e4f50 - <rustc_middle[da574927bfa7926c]::ty::context::TyCtxt>::instance_mir
  18:     0x7ff8484af7b0 - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  19:     0x7ff84848c58b - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  20:     0x7ff84836ffe7 - <rustc_query_impl[b505e6b5e14c3243]::Queries as rustc_middle[da574927bfa7926c]::ty::query::QueryEngine>::as_any
  21:     0x7ff84a52fbc7 - <rustc_span[e48dd0f66c859eaf]::def_id::DefId as rustc_query_impl[b505e6b5e14c3243]::keys::Key>::default_span
  22:     0x7ff84a512ff4 - <rustc_query_impl[b505e6b5e14c3243]::plumbing::QueryCtxt>::try_print_query_stack
  23:     0x7ff84a5ce495 - <&[rustc_middle[da574927bfa7926c]::ty::abstract_const::Node] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  24:     0x7ff84a604a56 - <&[rustc_middle[da574927bfa7926c]::ty::abstract_const::Node] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7ff84a4f8bd6 - <&[rustc_span[e48dd0f66c859eaf]::span_encoding::Span] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  26:     0x7ff84a58b72c - <rustc_span[e48dd0f66c859eaf]::hygiene::ExpnId as rustc_serialize[50d79c8c7897214b]::serialize::Encodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheEncoder>>::encode
  27:     0x7ff848ab10bd - rustc_interface[d17d6a4a7f0ecc1c]::interface::try_print_query_stack
  28:     0x7ff848a3bb63 - rustc_driver[4bc29db7fa6a984b]::report_ice
  29:     0x7ff84e3ace32 - std::panicking::rust_panic_with_hook::h2b8e759989d1d193
  30:     0x7ff84e3acbbd - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h10d78d084596fee5
  31:     0x7ff84e3a99bf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdf8210fa835a16a5
  32:     0x7ff84e3ac880 - rust_begin_unwind
  33:     0x7ff84e419625 - core::panicking::panic_fmt::heccde9d03cbc1a6d
  34:     0x7ff846a838e5 - <rustc_ast_lowering[6281666d600a521c]::index_crate::Indexer as rustc_ast[733dbb6f10d5fad0]::visit::Visitor>::visit_foreign_item
  35:     0x7ff846a890cd - <rustc_ast_lowering[6281666d600a521c]::index_crate::Indexer as rustc_ast[733dbb6f10d5fad0]::visit::Visitor>::visit_foreign_item
  36:     0x7ff847d86303 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  37:     0x7ff847d9d307 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  38:     0x7ff847d786ce - <rustc_mir_transform[ff2d91deca6a4573]::remove_noop_landing_pads::RemoveNoopLandingPads as rustc_middle[da574927bfa7926c]::mir::MirPass>::run_pass
  39:     0x7ff847d970e2 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  40:     0x7ff847ddbc08 - <rustc_ast_lowering[6281666d600a521c]::index::NodeCollector as rustc_hir[95355f4b5afb8c36]::intravisit::Visitor>::visit_trait_ref
  41:     0x7ff847d7eb21 - rustc_ast_lowering[6281666d600a521c]::lower_to_hir
  42:     0x7ff846d81325 - <&rustc_index[be4fabed3c045652]::vec::IndexVec<rustc_middle[da574927bfa7926c]::mir::Promoted, rustc_middle[da574927bfa7926c]::mir::Body> as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7ff846eedf8f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7ff846de95be - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7ff846ebcd5f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  46:     0x7ff8488e6060 - <rustc_middle[da574927bfa7926c]::ty::context::TyCtxt>::instance_mir
  47:     0x7ff8484a657a - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  48:     0x7ff848492315 - <rustc_span[e48dd0f66c859eaf]::hygiene::SyntaxContext as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  49:     0x7ff84836aeda - <rustc_query_impl[b505e6b5e14c3243]::Queries as rustc_middle[da574927bfa7926c]::ty::query::QueryEngine>::as_any
  50:     0x7ff8471945fb - <rustc_middle[da574927bfa7926c]::hir::map::Map>::get_module
  51:     0x7ff84719679d - <rustc_middle[da574927bfa7926c]::hir::map::Map as rustc_hir[95355f4b5afb8c36]::intravisit::Map>::trait_item
  52:     0x7ff846d81325 - <&rustc_index[be4fabed3c045652]::vec::IndexVec<rustc_middle[da574927bfa7926c]::mir::Promoted, rustc_middle[da574927bfa7926c]::mir::Body> as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  53:     0x7ff846eec93c - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  54:     0x7ff846deedb8 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  55:     0x7ff846e7e36f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  56:     0x7ff84726309d - tracing_core[cdfe675b129e512e]::callsite::register_dispatch
  57:     0x7ff84a565069 - <rustc_query_impl[b505e6b5e14c3243]::queries::permits_zero_init as rustc_query_system[5c215ea2856b3a09]::query::config::QueryDescription<rustc_query_impl[b505e6b5e14c3243]::plumbing::QueryCtxt>>::describe
  58:     0x7ff84a6a9c9c - <&[rustc_middle[da574927bfa7926c]::ty::abstract_const::Node] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  59:     0x7ff846e30e02 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  60:     0x7ff846ea19f5 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  61:     0x7ff846350195 - <rustc_interface[d17d6a4a7f0ecc1c]::queries::Linker>::link
  62:     0x7ff846351c5f - <rustc_interface[d17d6a4a7f0ecc1c]::queries::Linker>::link
  63:     0x7ff84636194d - rustc_interface[d17d6a4a7f0ecc1c]::passes::analysis
  64:     0x7ff846d811de - <&rustc_index[be4fabed3c045652]::vec::IndexVec<rustc_middle[da574927bfa7926c]::mir::Promoted, rustc_middle[da574927bfa7926c]::mir::Body> as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  65:     0x7ff846eebad3 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  66:     0x7ff846e347b2 - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  67:     0x7ff846ebc68f - <&[(rustc_middle[da574927bfa7926c]::middle::exported_symbols::ExportedSymbol, rustc_middle[da574927bfa7926c]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[50d79c8c7897214b]::serialize::Decodable<rustc_query_impl[b505e6b5e14c3243]::on_disk_cache::CacheDecoder>>::decode
  68:     0x7ff8463273c6 - <unknown>
  69:     0x7ff846306cf8 - <unknown>
  70:     0x7ff846302c1a - <unknown>
  71:     0x7ff846322303 - <unknown>
  72:     0x7ff846337ab7 - <rustc_middle[da574927bfa7926c]::ty::SymbolName as core[925e9186cc1e8cee]::fmt::Debug>::fmt
  73:     0x7ff846306679 - <unknown>
  74:     0x7ff846327ced - <unknown>
  75:     0x7ff84e3bd7ac - std::sys::windows::thread::Thread::new::he38aace67bdea9d1
  76:     0x7ff889cd7034 - BaseThreadInitThunk
  77:     0x7ff88bae2651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

```

### Error output

```
Caused by:
  process didn't exit successfully: `rustc --crate-name scas_peg --edition=2021 src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=45c9c1969c3ef8ac -C extra-filename=-45c9c1969c3ef8ac --out-dir C:\Users\pfapostol\code\Rust\scas\target\debug\deps -C incremental=C:\Users\pfapostol\code\Rust\scas\target\debug\incremental -L dependency=C:\Users\pfapostol\code\Rust\scas\target\debug\deps --extern clap=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\libclap-b2da49261a86480e.rmeta --extern lazy_static=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\liblazy_static-915917b7703ad76d.rmeta --extern num_bigint=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\libnum_bigint-e6656badaf4cfef2.rmeta --extern pest=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\libpest-a0b70d745e4fc1e9.rmeta --extern pest_derive=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\pest_derive-e3736e89df64d6d1.dll --extern snafu=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\libsnafu-4847b78c2cdab61a.rmeta --extern state=C:\Users\pfapostol\code\Rust\scas\target\debug\deps\libstate-6bde4d1ff79c03d9.rmeta` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by compiler-errors** [comment]
@PFAhard if you can provide code, that would be appreciated. Otherwise it's pretty difficult to investigate this.

**Comment by compiler-errors** [comment]
Anyways I am suspicious this is the same issue as #101297
