### ISSUE TITLE
Compiler Panic: Nightly: Trait Bounds?

### ISSUE THREAD

**Issue by jonaspleyer** [rust-lang/rust#101523]
### Description
Hi everyone!
I found a compiler error in the nightly rustc compiler. I was unsure about the title but could not come up with a better phrase. I also tried to follow the [bug-minimization-patterns](http://blog.pnkfx.org/blog/2019/11/18/rust-bug-minimization-patterns/) to the best of my ability.
Since this is my first contribution feel free to critique where I could do better.
Thank you (the community) for developing and maintaining Rust! I really enjoy the language.

### Code

```Rust
pub trait Stepper<I, F, E> {
    fn do_step
    (
        &mut self,
        y:  &mut I,
    )
    where
        for<'m>&'m I: IntoIterator<Item=&'m F>;
}

fn helper<I, F, E, S> (
    mut y: I,
    t: &F,
    mut stepper: S,
)
where
    S: Stepper<I, F, E>,
{
    stepper.do_step(&mut y, t);
}
```
### Cargo.toml
```Toml
[package]
name = "bug_report"
description="compiler bug_report"
authors = ["Jonas Pleyer"]
version = "0.0.1"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (748038961 2022-08-25)
binary: rustc
commit-hash: 7480389611f9d04bd34adf41a2b3029be4eb815e
commit-date: 2022-08-25
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

### Error output

```
error: could not compile `bug_report`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling bug_report v0.0.1 (/home/jpleyer/Documents/Studium/2022-WS/bug_test)
error: internal compiler error: compiler/rustc_infer/src/infer/region_constraints/mod.rs:568:17: cannot relate bound region: ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:8 ~ bug_report[998e]::Stepper::do_step::'m), 'm) }) <= '_#2r

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/compiler/rustc_errors/src/lib.rs:1393:9
stack backtrace:
   0:     0x7f52d92c4400 - std::backtrace_rs::backtrace::libunwind::trace::h2aab03b73f72c7df
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f52d92c4400 - std::backtrace_rs::backtrace::trace_unsynchronized::h3eca5d21f7d69aac
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f52d92c4400 - std::sys_common::backtrace::_print_fmt::hea9c617086d0512c
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f52d92c4400 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcd4c2c2cfdd5d0d6
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f52d931f12e - core::fmt::write::h10f610544bba85e2
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f52d92b5295 - std::io::Write::write_fmt::had4054a873710e65
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/io/mod.rs:1672:15
   6:     0x7f52d92c70c3 - std::sys_common::backtrace::_print::h4dd267ef32d500e5
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f52d92c70c3 - std::sys_common::backtrace::print::hd055a8f91e18a346
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f52d92c70c3 - std::panicking::default_hook::{{closure}}::hd0c792ae4e63357e
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:295:22
   9:     0x7f52d92c6daf - std::panicking::default_hook::h22fbb26b98df9cc4
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:314:9
  10:     0x7f52dbaef331 - <rustc_driver[82175be88d0838b5]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[200d113468b3e67d]::ops::function::FnOnce<(&core[200d113468b3e67d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f52d92c78fd - std::panicking::rust_panic_with_hook::ha5fcab7510d2c291
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/panicking.rs:702:17
  12:     0x7f52dc9e6861 - std[76b05c926e7310dd]::panicking::begin_panic::<rustc_errors[3aa815ae69db3b1c]::ExplicitBug>::{closure#0}
  13:     0x7f52dc9e1e56 - std[76b05c926e7310dd]::sys_common::backtrace::__rust_end_short_backtrace::<std[76b05c926e7310dd]::panicking::begin_panic<rustc_errors[3aa815ae69db3b1c]::ExplicitBug>::{closure#0}, !>
  14:     0x7f52dc9c5e26 - std[76b05c926e7310dd]::panicking::begin_panic::<rustc_errors[3aa815ae69db3b1c]::ExplicitBug>
  15:     0x7f52dc9b7416 - std[76b05c926e7310dd]::panic::panic_any::<rustc_errors[3aa815ae69db3b1c]::ExplicitBug>
  16:     0x7f52dc9b6a11 - <rustc_errors[3aa815ae69db3b1c]::HandlerInner>::span_bug::<rustc_span[58882ad2522b3487]::span_encoding::Span, &alloc[3b320fcdbc309927]::string::String>
  17:     0x7f52dc9b68d0 - <rustc_errors[3aa815ae69db3b1c]::Handler>::span_bug::<rustc_span[58882ad2522b3487]::span_encoding::Span, &alloc[3b320fcdbc309927]::string::String>
  18:     0x7f52dc972b48 - rustc_middle[3717ca78a5dec842]::ty::context::tls::with_context_opt::<rustc_middle[3717ca78a5dec842]::ty::context::tls::with_opt<rustc_middle[3717ca78a5dec842]::util::bug::opt_span_bug_fmt<rustc_span[58882ad2522b3487]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7f52dc9729e6 - rustc_middle[3717ca78a5dec842]::util::bug::opt_span_bug_fmt::<rustc_span[58882ad2522b3487]::span_encoding::Span>
  20:     0x7f52dc9729a4 - rustc_middle[3717ca78a5dec842]::util::bug::span_bug_fmt::<rustc_span[58882ad2522b3487]::span_encoding::Span>
  21:     0x7f52da4e7b06 - <rustc_infer[48ac37f9552e45ad]::infer::region_constraints::RegionConstraintCollector>::make_eqregion
  22:     0x7f52da4ed17f - <rustc_infer[48ac37f9552e45ad]::infer::equate::Equate as rustc_middle[3717ca78a5dec842]::ty::relate::TypeRelation>::relate_with_variance::<rustc_middle[3717ca78a5dec842]::ty::sty::Region>
  23:     0x7f52da4ebe94 - rustc_middle[3717ca78a5dec842]::ty::relate::super_relate_tys::<rustc_infer[48ac37f9552e45ad]::infer::equate::Equate>
  24:     0x7f52da3f7b83 - <rustc_infer[48ac37f9552e45ad]::infer::equate::Equate as rustc_middle[3717ca78a5dec842]::ty::relate::TypeRelation>::tys
  25:     0x7f52dadca000 - <rustc_infer[48ac37f9552e45ad]::infer::at::At>::eq::<rustc_middle[3717ca78a5dec842]::ty::Ty>
  26:     0x7f52dc85e271 - <rustc_infer[48ac37f9552e45ad]::infer::InferCtxt>::can_eq::<rustc_middle[3717ca78a5dec842]::ty::Ty>
  27:     0x7f52dc86412d - <rustc_infer[48ac37f9552e45ad]::infer::InferCtxt as rustc_trait_selection[31a146d52257b6bc]::traits::error_reporting::suggestions::InferCtxtExt>::suggest_dereferences
  28:     0x7f52dc87ca76 - <rustc_infer[48ac37f9552e45ad]::infer::InferCtxt as rustc_trait_selection[31a146d52257b6bc]::traits::error_reporting::InferCtxtExt>::report_selection_error
  29:     0x7f52dc88687d - <rustc_infer[48ac37f9552e45ad]::infer::InferCtxt as rustc_trait_selection[31a146d52257b6bc]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  30:     0x7f52dc87901d - <rustc_infer[48ac37f9552e45ad]::infer::InferCtxt as rustc_trait_selection[31a146d52257b6bc]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  31:     0x7f52da5e3bca - <rustc_typeck[190a4d868a0d33f8]::check::fn_ctxt::FnCtxt>::check_argument_types
  32:     0x7f52da50d7cd - <rustc_typeck[190a4d868a0d33f8]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  33:     0x7f52da578dac - <rustc_typeck[190a4d868a0d33f8]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  34:     0x7f52da50bde4 - <rustc_typeck[190a4d868a0d33f8]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  35:     0x7f52daf5e11d - <rustc_typeck[190a4d868a0d33f8]::check::fn_ctxt::FnCtxt>::check_return_expr
  36:     0x7f52daf5b1eb - rustc_typeck[190a4d868a0d33f8]::check::check::check_fn
  37:     0x7f52daf4dfa3 - <rustc_infer[48ac37f9552e45ad]::infer::InferCtxtBuilder>::enter::<&rustc_middle[3717ca78a5dec842]::ty::context::TypeckResults, <rustc_typeck[190a4d868a0d33f8]::check::inherited::InheritedBuilder>::enter<rustc_typeck[190a4d868a0d33f8]::check::typeck_with_fallback<rustc_typeck[190a4d868a0d33f8]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[3717ca78a5dec842]::ty::context::TypeckResults>::{closure#0}>
  38:     0x7f52daf4bbe4 - rustc_typeck[190a4d868a0d33f8]::check::typeck
  39:     0x7f52db20319d - <rustc_query_system[35f63f7c4b517368]::dep_graph::graph::DepGraph<rustc_middle[3717ca78a5dec842]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[3717ca78a5dec842]::ty::context::TyCtxt, rustc_span[58882ad2522b3487]::def_id::LocalDefId, &rustc_middle[3717ca78a5dec842]::ty::context::TypeckResults>
  40:     0x7f52db1fbbe0 - rustc_query_system[35f63f7c4b517368]::query::plumbing::try_execute_query::<rustc_query_impl[1e3c2d3b78f56143]::plumbing::QueryCtxt, rustc_query_system[35f63f7c4b517368]::query::caches::DefaultCache<rustc_span[58882ad2522b3487]::def_id::LocalDefId, &rustc_middle[3717ca78a5dec842]::ty::context::TypeckResults>>
  41:     0x7f52db9e4f58 - <rustc_query_impl[1e3c2d3b78f56143]::Queries as rustc_middle[3717ca78a5dec842]::ty::query::QueryEngine>::typeck
  42:     0x7f52db819eeb - rustc_data_structures[e320fec9a50473a]::sync::par_for_each_in::<&[rustc_span[58882ad2522b3487]::def_id::LocalDefId], <rustc_middle[3717ca78a5dec842]::hir::map::Map>::par_body_owners<rustc_typeck[190a4d868a0d33f8]::check::typeck_item_bodies::{closure#0}>::{closure#0}>
  43:     0x7f52db819ca3 - rustc_typeck[190a4d868a0d33f8]::check::typeck_item_bodies
  44:     0x7f52db724ec5 - <rustc_query_system[35f63f7c4b517368]::dep_graph::graph::DepGraph<rustc_middle[3717ca78a5dec842]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[3717ca78a5dec842]::ty::context::TyCtxt, (), ()>
  45:     0x7f52db723f7f - rustc_query_system[35f63f7c4b517368]::query::plumbing::try_execute_query::<rustc_query_impl[1e3c2d3b78f56143]::plumbing::QueryCtxt, rustc_query_system[35f63f7c4b517368]::query::caches::DefaultCache<(), ()>>
  46:     0x7f52db7239b1 - rustc_query_system[35f63f7c4b517368]::query::plumbing::get_query::<rustc_query_impl[1e3c2d3b78f56143]::queries::typeck_item_bodies, rustc_query_impl[1e3c2d3b78f56143]::plumbing::QueryCtxt>
  47:     0x7f52db4c912f - <rustc_session[720028cef8e445d5]::session::Session>::time::<(), rustc_typeck[190a4d868a0d33f8]::check_crate::{closure#7}>
  48:     0x7f52db4c8f25 - rustc_typeck[190a4d868a0d33f8]::check_crate
  49:     0x7f52db4c6d52 - rustc_interface[4cd9d1ba33da26b9]::passes::analysis
  50:     0x7f52db865e92 - <rustc_query_system[35f63f7c4b517368]::dep_graph::graph::DepGraph<rustc_middle[3717ca78a5dec842]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[3717ca78a5dec842]::ty::context::TyCtxt, (), core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>
  51:     0x7f52db865617 - rustc_query_system[35f63f7c4b517368]::query::plumbing::try_execute_query::<rustc_query_impl[1e3c2d3b78f56143]::plumbing::QueryCtxt, rustc_query_system[35f63f7c4b517368]::query::caches::DefaultCache<(), core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>>
  52:     0x7f52db86510e - rustc_query_system[35f63f7c4b517368]::query::plumbing::get_query::<rustc_query_impl[1e3c2d3b78f56143]::queries::analysis, rustc_query_impl[1e3c2d3b78f56143]::plumbing::QueryCtxt>
  53:     0x7f52db3cf5e7 - <rustc_interface[4cd9d1ba33da26b9]::passes::QueryContext>::enter::<rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>
  54:     0x7f52db3cb75e - <rustc_interface[4cd9d1ba33da26b9]::interface::Compiler>::enter::<rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}::{closure#2}, core[200d113468b3e67d]::result::Result<core[200d113468b3e67d]::option::Option<rustc_interface[4cd9d1ba33da26b9]::queries::Linker>, rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>
  55:     0x7f52db3c72fc - rustc_span[58882ad2522b3487]::with_source_map::<core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>, rustc_interface[4cd9d1ba33da26b9]::interface::create_compiler_and_run<core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>, rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}>::{closure#1}>
  56:     0x7f52db3c6d82 - rustc_interface[4cd9d1ba33da26b9]::interface::create_compiler_and_run::<core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>, rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}>
  57:     0x7f52db3c5921 - <scoped_tls[b2ec032a876a0ff7]::ScopedKey<rustc_span[58882ad2522b3487]::SessionGlobals>>::set::<rustc_interface[4cd9d1ba33da26b9]::interface::run_compiler<core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>, rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}>::{closure#0}, core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>
  58:     0x7f52db3c560f - std[76b05c926e7310dd]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4cd9d1ba33da26b9]::util::run_in_thread_pool_with_globals<rustc_interface[4cd9d1ba33da26b9]::interface::run_compiler<core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>, rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}>::{closure#0}, core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>::{closure#0}, core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>
  59:     0x7f52db90b549 - <<std[76b05c926e7310dd]::thread::Builder>::spawn_unchecked_<rustc_interface[4cd9d1ba33da26b9]::util::run_in_thread_pool_with_globals<rustc_interface[4cd9d1ba33da26b9]::interface::run_compiler<core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>, rustc_driver[82175be88d0838b5]::run_compiler::{closure#1}>::{closure#0}, core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>::{closure#0}, core[200d113468b3e67d]::result::Result<(), rustc_errors[3aa815ae69db3b1c]::ErrorGuaranteed>>::{closure#1} as core[200d113468b3e67d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  60:     0x7f52d92d1523 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h234c9f70a7e6c5bd
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/boxed.rs:1940:9
  61:     0x7f52d92d1523 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hae8fb94b47e06af2
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/alloc/src/boxed.rs:1940:9
  62:     0x7f52d92d1523 - std::sys::unix::thread::Thread::new::thread_start::hdbfed6a2cd9a6e41
                               at /rustc/7480389611f9d04bd34adf41a2b3029be4eb815e/library/std/src/sys/unix/thread.rs:108:17
  63:     0x7f52d903378d - <unknown>
  64:     0x7f52d90b48e4 - clone
  65:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (748038961 2022-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `helper`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `bug_report`

```

</p>
</details>

**Comment by jonaspleyer** [comment]
Sorry for the issue report. The bug was fixed by upgrading to a more recent nightly version.
```
rustc 1.65.0-nightly (78a891d36 2022-09-06)
binary: rustc
commit-hash: 78a891d364a7358ed9eb9c93099ba2f3e6817ca6
commit-date: 2022-09-06
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```
