### ISSUE TITLE
Aggressive optimizations lead to incorrect or unexpected results using `thread::scope()` with closed-over variables instead of local `static mut` variables.

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#101775]
With the recent stabilization of `std::thread::scope()`, I expect we'll see a number of users try to port some code using global/local `static` variables in conjunction with `std::thread::spawn()` to using regular local, mutable variables and `std::thread::scope()` instead. Unfortunately, while the revised approach may be sound in theory, in practice it may be untenable due to aggressive optimizations making assumptions about what local, mutable (non-`static`) variables can or can't change before being read by the scoped thread.

Please note that I am not saying this is necessarily a bug caused by over-eager optimizations - I am merely reporting my observations and suggesting that _something_ should be done about this, whether it is to expand the documentation for `std::thread::scope()` to make it clear that closing over mutable variables is not a panacea/general stand-in for using `static mut` or if it is to try to work reduce the aggressiveness of optimizations that take place regarding closed-over variables accessed or modified in `std::thread::scope()` closures.

In this specific case, I was attempting to revise the README example for a crate that I maintain [that implements thread signals/events à la WIN32 events](https://github.com/neosmart/rsevents). The original code used a local `static mut` variable w/ `std::thread::spawn()` and worked fine (though it was not re-entrant or thread-safe) and the revised code attempted to fix that by using local `let mut ...` vars closed over in the closure passed to `std::thread::scope()` instead, but the aggressive optimizations led the compiler to incorrectly infer that variables were never changed before being read, leading to incorrect results (something that it does not assume when `static mut` is used instead).

In the code sample below, `rsevents::AutoResetEvent` is a thread synchronization primitive that, when signalled, wakes one (and only one) waiting thread and also guarantees (via memory ordering semantics) that all writes prior to the signalling (via a `set()` call) will be visible to the awakened thread coming out of a `wait()` call. The code sample intentionally uses unsafe raw pointer reads/writes and does not use `Sync` or `Send` wrappers to illustrate the memory safety guarantees provided the `AutoResetEvent`.

**This issue would affect any code relying on thread synchronization primitives that don't wrap/own the shared data (so it would not replicate with `Mutex<T>`, `RwLock<T>`, etc.) such as the `rsevents` reset events, a semaphore, etc.** It's most likely to be encountered with low-level library code rather than high-level applications.

This is the original sample code, utilizing `static mut` and `std::thread::spawn()`, which works as expected:

```rust
use rsevents::{AutoResetEvent, Awaitable, EventState};
use std::time::Duration;

#[derive(Clone, Copy, Debug)]
enum ThreadMessage {
    /// Used in lieu of wrapping `ThreadMessage` in an `Option`
    None,
    /// Hands off a value to a worker thread for processing
    Input(u32),
}

// Events are cheap: each one is only a single byte!
static TASK_READY: AutoResetEvent = AutoResetEvent::new(EventState::Unset);
static DISPATCHED: AutoResetEvent = AutoResetEvent::new(EventState::Unset);

pub fn main() {
    // The events above synchronize access to this !Sync, !Send shared state
    static mut SHARED: ThreadMessage = ThreadMessage::None;

    const THREAD_COUNT: usize = 3;
    let mut threads = Vec::with_capacity(THREAD_COUNT);
    for thread_idx in 0..THREAD_COUNT {
        let join_handle = std::thread::spawn(move || {
            loop {
                // Wait efficiently for the main thread to signal _one_ (and
                // only one) worker thread at a time.
                if !TASK_READY.wait_for(Duration::from_millis(500)) {
                    // When there's not enough work, let the thread pool drain
                    break;
                }

                // This is safe because our events guarantee that
                // * one thread will be accessing this variable at a time
                // * shared memory will be consistent betwixt a call to
                //   event.set() from one thread and a call to event.wait()
                //   from another.
                let work_msg = unsafe { *(&SHARED as *const ThreadMessage) };

                // Signal to the main thread that we've taken the value and that
                // it can overwrite `shared` at its leisure. Afterwards,
                // processing can take as long as it needs.
                DISPATCHED.set();

                match work_msg {
                    ThreadMessage::None => {
                        unreachable!("The AutoResetEvent guarantees against this")
                    }
                    ThreadMessage::Input(value) => {
                        eprintln!("Thread {thread_idx} handling value {value}")
                    }
                }
            }
        });
        threads.push(join_handle);
    }

    // Generate some "random" values at an interval, dispatching each exactly
    // once to exactly one worker thread.
    for value in [4, 8, 15, 16, 23, 42] {
        unsafe {
            // It's perfectly safe to access - and even write - to SHARED here
            // because our two events guarantee exclusive access (as
            // AutoResetEvents wake one thread at a time) and take care of
            // synchronizing the memory plus any cache coherence issues between
            // the writing thread (this one) and the reading worker thread.
            *(&mut SHARED as *mut _) = ThreadMessage::Input(value);
        }

        // Signal a currently idle or the next idle worker thread to handle this
        // value.
        TASK_READY.set();

        // Remember that work is usually dispatched faster than it can be
        // handled!
        // Wait for a worker thread to signal it has received the payload and we
        // can stomp the `SHARED` value and dispatch work to the next worker.
        DISPATCHED.wait();
    }

    // Wait for the thread pool to drain and exit
    for jh in threads {
        jh.join().expect("Worker thread panicked!");
    }
    eprintln!("All work completed - exiting!")
}
```

It prints the following output then exits:

```
Thread 0 handling value 4
Thread 0 handling value 15
Thread 0 handling value 16
Thread 0 handling value 23
Thread 1 handling value 8
Thread 2 handling value 42
All work completed - exiting!
```

When modified to use `std::thread::scope()` and take advantage of its semantics to use a local mutable variable instead of a `static mut` variable (only one variable (`SHARED`) is changed from `static mut` to `let mut` to minimize the changes for this demonstration, but all the `static` variables could also be moved into the closure as well), the code no longer works correctly:

```rust
use rsevents::{AutoResetEvent, Awaitable, EventState};
use std::time::Duration;

#[derive(Clone, Copy, Debug)]
enum ThreadMessage {
    /// Used in lieu of wrapping `ThreadMessage` in an `Option`
    None,
    /// Hands off a value to a worker thread for processing
    Input(u32),
}

// Events are cheap: each one is only a single byte!
static TASK_READY: AutoResetEvent = AutoResetEvent::new(EventState::Unset);
static DISPATCHED: AutoResetEvent = AutoResetEvent::new(EventState::Unset);

pub fn main() {
    const THREAD_COUNT: usize = 3;
    std::thread::scope(|scope| {
        // The events above synchronize access to this !Sync, !Send shared state
        let mut SHARED: ThreadMessage = ThreadMessage::None;

        for thread_idx in 0..THREAD_COUNT {
            scope.spawn(move || {
                // This is here to cause panic messages to not collide w/ one another
                std::thread::sleep_ms(thread_idx as u32 * 100);

                loop {
                    // Wait efficiently for the main thread to signal _one_ (and
                    // only one) worker thread at a time.
                    if !TASK_READY.wait_for(Duration::from_millis(500)) {
                        // When there's not enough work, let the thread pool drain
                        break;
                    }

                    // This is safe because our events guarantee that
                    // * one thread will be accessing this variable at a time
                    // * shared memory will be consistent betwixt a call to
                    //   event.set() from one thread and a call to event.wait()
                    //   from another.
                    let work_msg = unsafe { *(&SHARED as *const ThreadMessage) };

                    // Signal to the main thread that we've taken the value and that
                    // it can overwrite `shared` at its leisure. Afterwards,
                    // processing can take as long as it needs.
                    DISPATCHED.set();

                    match work_msg {
                        ThreadMessage::None => {
                            unreachable!("The AutoResetEvent guarantees against this")
                        }
                        ThreadMessage::Input(value) => {
                            eprintln!("Thread {thread_idx} handling value {value}")
                        }
                    }
                }
            });
        }

        // Generate some "random" values at an interval, dispatching each exactly
        // once to exactly one worker thread.
        for value in [4, 8, 15, 16, 23, 42] {
            unsafe {
                // It's perfectly safe to access - and even write - to SHARED here
                // because our two events guarantee exclusive access (as
                // AutoResetEvents wake one thread at a time) and take care of
                // synchronizing the memory plus any cache coherence issues between
                // the writing thread (this one) and the reading worker thread.
                *(&mut SHARED as *mut _) = ThreadMessage::Input(value);
            }

            // Signal a currently idle or the next idle worker thread to handle this
            // value.
            TASK_READY.set();

            // Remember that work is usually dispatched faster than it can be
            // handled!
            // Wait for a worker thread to signal it has received the payload and we
            // can stomp the `SHARED` value and dispatch work to the next worker.
            DISPATCHED.wait();
        }

        // All spawned threads are automatically joined when the scope is dropped.
    });

    eprintln!("All work completed - exiting!")
}
```

The code fails its sanity checks because the optimizer replaces the read value of `SHARED` with the initial value it was initialized with (`ThreadMessage::None`), thinking that it couldn't possibly be modified before being read:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: The AutoResetEvent guarantees against this', examples/readme.rs:54:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'internal error: entered unreachable code: The AutoResetEvent guarantees against this', examples/readme.rs:54:29
thread '<unnamed>' panicked at 'internal error: entered unreachable code: The AutoResetEvent guarantees against this', examples/readme.rs:54:29
```

The code samples above have a dependency on `rsevents` version `0.3.1` (which itself has no dependencies other than `parking_lot_core`).

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (015a824f2 2022-08-22)
binary: rustc
commit-hash: 015a824f2dffe32707fceb59c47effaf7b73486c
commit-date: 2022-08-22
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

@rustbot label +A-concurrency +T-compiler

**Comment by kpreid** [comment]
> the optimizer replaces the read value of `SHARED` with the initial value it was initialized with (`ThreadMessage::None`), thinking that it couldn't possibly be modified before being read:

I think this is not “the optimizer” but the language semantics. By making `SHARED` into a `let` variable, you've made it one of the captured variables of the thread closure, which is `move`, so it moves/copies all its captures, and `ThreadMessage` implements `Copy`, so each thread gets its own copy of the current value of `SHARED` moved into the thread closure.

The typical solution to this problem is making the variable the closure refers to itself a raw pointer, but since you are working with shared mutability, you will be best off with a raw pointer:

```rust
        let mut shared: ThreadMessage = ThreadMessage::None;
        let shared_ptr = std::ptr::addr_of_mut!(shared);
        ....
                             let work_msg = unsafe { std::ptr::read(shared_ptr) };
```

**Comment by mqudsi** [comment]
I think you’re right. I should have studied this more before posting.
