### ISSUE TITLE
Compiler panics while compiling `cc`. 

### ISSUE THREAD

**Issue by DonielMoins** [rust-lang/rust#101916]
Sadly I could not reproduce this error. But a compiler bug is still a bug. If I manage to reproduce it, I'll make sure to update this thread.

### Code

Errors occured during compilation of cc and backtrace.

### Meta

(I couldn't because I tried to compile again, and the compiler did not panic...)

`rustc --version --verbose`:
```
rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.6
```

### Error output

```
thread 'rustc' panicked at 'range end index 2305843009213699158 out of range for slice of length 6306', library/core/src/slice/index.rs:73:5

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```<backtrace>
thread 'rustc' panicked at 'range end index 2305843009213699158 out of range for slice of length 6306', library/core/src/slice/index.rs:73:5
stack backtrace:
   0:     0x7fddbd0278ed - std::backtrace_rs::backtrace::libunwind::trace::hf17a016fe288d842
                               at /rustc/1.63.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fddbd0278ed - std::backtrace_rs::backtrace::trace_unsynchronized::hceb3b545c0fd1e3d
                               at /rustc/1.63.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fddbd0278ed - std::sys_common::backtrace::_print_fmt::hf8051f323ee84201
                               at /rustc/1.63.0/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fddbd0278ed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h402e40e4a8e7ede3
                               at /rustc/1.63.0/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fddbd083a5c - core::fmt::write::h3654b4b4eb96ea69
                               at /rustc/1.63.0/library/core/src/fmt/mod.rs:1197:17
   5:     0x7fddbd018bc1 - std::io::Write::write_fmt::hc74f10310bd62c8e
                               at /rustc/1.63.0/library/std/src/io/mod.rs:1672:15
   6:     0x7fddbd02a5c5 - std::sys_common::backtrace::_print::hac3a8154024e887c
                               at /rustc/1.63.0/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fddbd02a5c5 - std::sys_common::backtrace::print::h389a47f9d03ab376
                               at /rustc/1.63.0/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fddbd02a5c5 - std::panicking::default_hook::{{closure}}::h6725d3e98576dbfd
                               at /rustc/1.63.0/library/std/src/panicking.rs:295:22
   9:     0x7fddbd02a2e6 - std::panicking::default_hook::he332f9297e8e7ad2
                               at /rustc/1.63.0/library/std/src/panicking.rs:314:9
  10:     0x7fddbd7bbc16 - rustc_driver[a87249c75145e1d3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fddbd02ac9a - std::panicking::rust_panic_with_hook::h8b9beabb1a08cf53
                               at /rustc/1.63.0/library/std/src/panicking.rs:702:17
  12:     0x7fddbd02aad7 - std::panicking::begin_panic_handler::{{closure}}::h3d519d8b2ec35514
                               at /rustc/1.63.0/library/std/src/panicking.rs:588:13
  13:     0x7fddbd027da4 - std::sys_common::backtrace::__rust_end_short_backtrace::hf8442b6e345bb40a
                               at /rustc/1.63.0/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fddbd02a809 - rust_begin_unwind
                               at /rustc/1.63.0/library/std/src/panicking.rs:584:5
  15:     0x7fddbcfef3d3 - core::panicking::panic_fmt::h32a8402d06c53a14
                               at /rustc/1.63.0/library/core/src/panicking.rs:142:14
  16:     0x7fddbd086286 - core::slice::index::slice_end_index_len_fail_rt::h9f53d3029ea189a1
                               at /rustc/1.63.0/library/core/src/slice/index.rs:73:5
  17:     0x7fddbd077ee7 - core::ops::function::FnOnce::call_once::h6487a901e709db59
                               at /rustc/1.63.0/library/core/src/ops/function.rs:248:5
  18:     0x7fddbd07edb6 - core::intrinsics::const_eval_select::h508cdec3accfa0b2
                               at /rustc/1.63.0/library/core/src/intrinsics.rs:2376:5
  19:     0x7fddbcfef4e6 - core::slice::index::slice_end_index_len_fail::hfc7521fc95685b05
                               at /rustc/1.63.0/library/core/src/slice/index.rs:67:9
  20:     0x7fddbdba5b47 - <rustc_monomorphize[b975dcea49d43410]::collector::InliningMap>::with_inlining_candidates::<<rustc_monomorphize[b975dcea49d43410]::partitioning::default::DefaultPartitioning as rustc_monomorphize[b975dcea49d43410]::partitioning::Partitioner>::place_inlined_mono_items::follow_inlining::{closure#0}>
  21:     0x7fddbdba5ad6 - <rustc_monomorphize[b975dcea49d43410]::collector::InliningMap>::with_inlining_candidates::<<rustc_monomorphize[b975dcea49d43410]::partitioning::default::DefaultPartitioning as rustc_monomorphize[b975dcea49d43410]::partitioning::Partitioner>::place_inlined_mono_items::follow_inlining::{closure#0}>
  22:     0x7fddbdbbc215 - <rustc_monomorphize[b975dcea49d43410]::partitioning::default::DefaultPartitioning as rustc_monomorphize[b975dcea49d43410]::partitioning::Partitioner>::place_inlined_mono_items
  23:     0x7fddbdbb6bcc - rustc_monomorphize[b975dcea49d43410]::partitioning::partition
   Compiling backtrace v0.3.15
  24:     0x7fddbdbda174 - rustc_data_structures[5cf96a2aebef5225]::sync::join::<rustc_monomorphize[b975dcea49d43410]::partitioning::collect_and_partition_mono_items::{closure#0}::{closure#0}, rustc_monomorphize[b975dcea49d43410]::partitioning::collect_and_partition_mono_items::{closure#0}::{closure#1}, &[rustc_middle[44e2f01268f73f0a]::mir::mono::CodegenUnit], ()>
  25:     0x7fddbdbc226e - <rustc_session[8db53f120e28dbc3]::session::Session>::time::<(&[rustc_middle[44e2f01268f73f0a]::mir::mono::CodegenUnit], ()), rustc_monomorphize[b975dcea49d43410]::partitioning::collect_and_partition_mono_items::{closure#0}>
  26:     0x7fddbdbb7b0a - rustc_monomorphize[b975dcea49d43410]::partitioning::collect_and_partition_mono_items
  27:     0x7fddbef86dd3 - rustc_query_system[f22b808c35add234]::query::plumbing::try_execute_query::<rustc_query_impl[d4680241c12526ef]::plumbing::QueryCtxt, rustc_query_system[f22b808c35add234]::query::caches::DefaultCache<(), (&std[f333974dc079c91d]::collections::hash::set::HashSet<rustc_span[ae349b71173294b0]::def_id::DefId, core[47caee92d8c8de80]::hash::BuildHasherDefault<rustc_hash[6e53e9464fca9efb]::FxHasher>>, &[rustc_middle[44e2f01268f73f0a]::mir::mono::CodegenUnit])>>
  28:     0x7fddbf0110b8 - rustc_query_system[f22b808c35add234]::query::plumbing::get_query::<rustc_query_impl[d4680241c12526ef]::queries::collect_and_partition_mono_items, rustc_query_impl[d4680241c12526ef]::plumbing::QueryCtxt>
  29:     0x7fddbee79b02 - <rustc_query_impl[d4680241c12526ef]::Queries as rustc_middle[44e2f01268f73f0a]::ty::query::QueryEngine>::collect_and_partition_mono_items
  30:     0x7fddbf13f15b - rustc_codegen_ssa[80d666b2364d871c]::back::symbol_export::exported_symbols_provider_local
  31:     0x7fddbef67588 - rustc_query_system[f22b808c35add234]::query::plumbing::try_execute_query::<rustc_query_impl[d4680241c12526ef]::plumbing::QueryCtxt, rustc_query_system[f22b808c35add234]::query::caches::DefaultCache<rustc_span[ae349b71173294b0]::def_id::CrateNum, &[(rustc_middle[44e2f01268f73f0a]::middle::exported_symbols::ExportedSymbol, rustc_middle[44e2f01268f73f0a]::middle::exported_symbols::SymbolExportInfo)]>>
  32:     0x7fddbefe8faf - rustc_query_system[f22b808c35add234]::query::plumbing::get_query::<rustc_query_impl[d4680241c12526ef]::queries::exported_symbols, rustc_query_impl[d4680241c12526ef]::plumbing::QueryCtxt>
  33:     0x7fddbf3c7730 - <rustc_metadata[67d8be3fdd5b4b5f]::rmeta::encoder::EncodeContext>::encode_crate_root
  34:     0x7fddbf3de3e2 - rustc_metadata[67d8be3fdd5b4b5f]::rmeta::encoder::encode_metadata_impl
  35:     0x7fddbf4b9111 - rustc_data_structures[5cf96a2aebef5225]::sync::join::<rustc_metadata[67d8be3fdd5b4b5f]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[67d8be3fdd5b4b5f]::rmeta::encoder::encode_metadata::{closure#1}, rustc_metadata[67d8be3fdd5b4b5f]::rmeta::encoder::EncodedMetadata, ()>
  36:     0x7fddbf3dda31 - rustc_metadata[67d8be3fdd5b4b5f]::rmeta::encoder::encode_metadata
  37:     0x7fddbd86b201 - <rustc_interface[55b6698559b40cac]::passes::QueryContext>::enter::<<rustc_interface[55b6698559b40cac]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[47caee92d8c8de80]::result::Result<alloc[92d2065b36b7f772]::boxed::Box<dyn core[47caee92d8c8de80]::any::Any>, rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>
  38:     0x7fddbd915d68 - <rustc_interface[55b6698559b40cac]::queries::Queries>::ongoing_codegen
  39:     0x7fddbd74b6f5 - <rustc_interface[55b6698559b40cac]::interface::Compiler>::enter::<rustc_driver[a87249c75145e1d3]::run_compiler::{closure#1}::{closure#2}, core[47caee92d8c8de80]::result::Result<core[47caee92d8c8de80]::option::Option<rustc_interface[55b6698559b40cac]::queries::Linker>, rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>
  40:     0x7fddbd734a93 - rustc_span[ae349b71173294b0]::with_source_map::<core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>, rustc_interface[55b6698559b40cac]::interface::create_compiler_and_run<core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>, rustc_driver[a87249c75145e1d3]::run_compiler::{closure#1}>::{closure#1}>
  41:     0x7fddbd74c46a - <scoped_tls[10a988ae3fd37cfe]::ScopedKey<rustc_span[ae349b71173294b0]::SessionGlobals>>::set::<rustc_interface[55b6698559b40cac]::interface::run_compiler<core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>, rustc_driver[a87249c75145e1d3]::run_compiler::{closure#1}>::{closure#0}, core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>
  42:     0x7fddbd7a840f - std[f333974dc079c91d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[55b6698559b40cac]::util::run_in_thread_pool_with_globals<rustc_interface[55b6698559b40cac]::interface::run_compiler<core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>, rustc_driver[a87249c75145e1d3]::run_compiler::{closure#1}>::{closure#0}, core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>::{closure#0}, core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>
  43:     0x7fddbd7707f9 - <<std[f333974dc079c91d]::thread::Builder>::spawn_unchecked_<rustc_interface[55b6698559b40cac]::util::run_in_thread_pool_with_globals<rustc_interface[55b6698559b40cac]::interface::run_compiler<core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>, rustc_driver[a87249c75145e1d3]::run_compiler::{closure#1}>::{closure#0}, core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>::{closure#0}, core[47caee92d8c8de80]::result::Result<(), rustc_errors[23fb27470ece102c]::ErrorGuaranteed>>::{closure#1} as core[47caee92d8c8de80]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7fddbd034c33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0fea6006b2b04d61
                               at /rustc/1.63.0/library/alloc/src/boxed.rs:1951:9
  45:     0x7fddbd034c33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h04acd88e2c8d51b7
                               at /rustc/1.63.0/library/alloc/src/boxed.rs:1951:9
  46:     0x7fddbd034c33 - std::sys::unix::thread::Thread::new::thread_start::hef7a3467c486ba74
                               at /rustc/1.63.0/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7fddbce2b74d - <unknown>
  48:     0x7fddbcead700 - <unknown>
  49:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0 (Arch Linux rust 1:1.63.0-1) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debug-assertions=off

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
#1 [exported_symbols] exported_symbols
end of query stack
error: could not compile `cc`
```

</p>
</details>

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Unfortunately there is not much that can be done without a way to reproduce. Closing this issue for now. Please re-open if you find a way to reproduce this problem. Thank you.
