### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by afitzek** [rust-lang/rust#101917]
I don't really have any idea what is going on here, just reporting the bug as the output suggested.

### Code

```Rust
use std::{future::Future, sync::Arc, pin::Pin};

use tokio::sync::mpsc;
use tokio::sync::broadcast;

pub fn channel<Req, Resp>(limit: usize) -> (Requester<Req, Resp>, RequestHandler<Req, Resp>) {
    let (req_sender, req_receiver) = mpsc::channel::<(Req, Responder<Resp>)>(limit);
    let sender = Requester::new(req_sender);
    let receiver = RequestHandler::new(req_receiver);
    (sender, receiver)
}

pub struct Responder<Resp> {
    sender: mpsc::Sender<Resp>
}

impl<Resp> Responder<Resp> {
    fn new(sender: mpsc::Sender<Resp>) -> Self {
        Responder { sender }
    }

    pub async fn respond(&self, resp: Resp) -> anyhow::Result<()> {
        match self.sender.send(resp).await {
            Ok(_) => Ok(()),
            Err(e) => {
                Err(anyhow::Error::msg("Failed to send response"))
            }
        }
    }
}

pub struct RequestHandler<Req, Resp> {
    receiver: mpsc::Receiver<(Req, Responder<Resp>)>
}

impl<Req, Resp> RequestHandler<Req, Resp> {
    fn new(receiver: mpsc::Receiver<(Req, Responder<Resp>)>) -> Self {
        RequestHandler { receiver }
    }

    pub async fn recv(&mut self) -> Option<(Req, Responder<Resp>)> {
        self.receiver.recv().await
    }
}

pub struct Response<Resp> {
    receiver: mpsc::Receiver<Resp>
}

impl<Resp> Response<Resp> {
    fn new(receiver: mpsc::Receiver<Resp>) -> Self {
        Response { receiver }
    }

    pub async fn get(&mut self) -> Option<Resp> {
        self.receiver.recv().await
    }
}

pub struct Requester<Req, Resp> {
    sender: mpsc::Sender<(Req, Responder<Resp>)>
}

impl<Req, Resp> Requester<Req, Resp> {
    fn new(sender: mpsc::Sender<(Req, Responder<Resp>)>) -> Self {
        Requester { sender }
    }

    pub async fn send(&self, request: Req, await_response: bool) -> anyhow::Result<Option<Resp>> {
        let (resp_sender, resp_receiver) = mpsc::channel(1);
        let responder = Responder::new(resp_sender);
        match self.sender.send((request, responder)).await {
            Ok(v) => {
                if await_response {
                    let mut resp_receiver = Response::new(resp_receiver);
                    Ok(resp_receiver.get().await)
                } else {
                    Ok(None)
                }
            },
            Err(e) => {
                Err(anyhow::Error::msg("Failed to send request to service"))
            }
        }
    }
}


pub struct LookupService {
    tx: Requester<LookupRegisterRequest, LookupRegisterResponse>,
}

impl LookupService {
    pub async fn register_hosts(&self, hosts: Vec<String>) -> anyhow::Result<()> {
        let receiver = self
            .tx
            .send(LookupRegisterRequest::RegisterHosts, true)
            .await?;
        match receiver {
            Some(v) => {
                // TODO: something with the response
                println!("Received response for host registration ...");
            }
            None => {
                print!("No response")
            }
        };
        Ok(())
    }
}

enum LookupRegisterRequest {
    RegisterHosts,
}

enum LookupRegisterResponse {
    RegisteredHosts,
}

pub fn start_service<Req, Resp, F>(
    limit: usize,
    mut termination_rx: broadcast::Receiver<()>,
    mut f: F,
) -> anyhow::Result<(
    Requester<Req, Resp>,
    impl Future<Output = anyhow::Result<()>>,
)>
where
    F: FnMut(Req) -> Pin<Box<dyn Future<Output = Option<Resp>>>>,
    Req: Send + Sync,
    Resp: Send + Sync,
{
    let (register_tx, mut req_handler) = channel::<Req, Resp>(limit);

    let join = async move {
        loop {
            tokio::select! {
                handle_response = req_handler.recv() => {
                    match handle_response {
                        Some((req, responder)) => {
                            let result = f(req).await;
                            if let Some(v) = result {
                                responder.respond(v).await;
                            }
                        },
                        _ => {
                            println!("Some error")
                        }
                    };
                }
                _ = termination_rx.recv() => {
                    return Ok(());
                }
            }
        }
    };

    Ok((register_tx, join))
}

async fn lookup_handler(req: LookupRegisterRequest) -> Option<LookupRegisterResponse> {
    match req {
        LookupRegisterRequest::RegisterHosts => {
            println!("Got host register call");
        }
        _ => {
            println!("Invalid lookup request");
        }
    };
    Some(LookupRegisterResponse::RegisteredHosts)
}

pub fn start_lookup_service(
    termination_rx: broadcast::Receiver<()>,
) -> anyhow::Result<(Arc<LookupService>, impl Future<Output = anyhow::Result<()>>)> {
    let (request, join) = start_service::<LookupRegisterRequest, LookupRegisterResponse, _>(
        100,
        termination_rx,
        lookup_handler,
    )?;
    Ok((Arc::new(LookupService { tx: request }), join))
}
async fn signal_handler_ctrl_c(tx: broadcast::Sender<()>) -> std::io::Result<()> {
    tokio::signal::ctrl_c().await?;
    let _ = tx.send(());
    Ok(())
}

fn signal_handler() -> broadcast::Sender<()> {
    let (terminate_tx, _) = broadcast::channel(1);
    tokio::spawn(signal_handler_ctrl_c(terminate_tx.clone()));
    terminate_tx
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let terminate_rx = signal_handler();

    let (lookup_service, lookup_handle) =
        start_lookup_service(terminate_rx.subscribe())?;

    tokio::try_join!(
        lookup_handle,
        lookup_service.register_hosts(vec!["test".to_string()])
    );
    Ok(())
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

### Error output

```
warning: unreachable pattern
   --> src/main.rs:166:9
    |
166 |         _ => {
    |         ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

warning: unused variable: `e`
  --> src/main.rs:25:17
   |
25 |             Err(e) => {
   |                 ^ help: if this is intentional, prefix it with an underscore: `_e`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `v`
  --> src/main.rs:73:16
   |
73 |             Ok(v) => {
   |                ^ help: if this is intentional, prefix it with an underscore: `_v`

warning: unused variable: `e`
  --> src/main.rs:81:17
   |
81 |             Err(e) => {
   |                 ^ help: if this is intentional, prefix it with an underscore: `_e`

warning: unused variable: `hosts`
  --> src/main.rs:94:40
   |
94 |     pub async fn register_hosts(&self, hosts: Vec<String>) -> anyhow::Result<()> {
   |                                        ^^^^^ help: if this is intentional, prefix it with an underscore: `_hosts`

warning: unused variable: `v`
   --> src/main.rs:100:18
    |
100 |             Some(v) => {
    |                  ^ help: if this is intentional, prefix it with an underscore: `_v`

warning: unused `Result` that must be used
   --> src/main.rs:143:33
    |
143 | ...                   responder.respond(v).await;
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `Result` that must be used
   --> src/main.rs:202:5
    |
202 | /     tokio::try_join!(
203 | |         lookup_handle,
204 | |         lookup_service.register_hosts(vec!["test".to_string()])
205 | |     );
    | |_____^
    |
    = note: this `Result` may be an `Err` variant, which should be handled
    = note: this warning originates in the macro `$crate::try_join` (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/compiler/rustc_codegen_ssa/src/mir/block.rs:1167:22: codegen_argument: OperandRef(Ref((%"type 0x7f3777ae3c80"*:  %4 = alloca %41, align 1), None, Align { pow2: 0 }) @ TyAndLayout { ty: std::future::from_generator::GenFuture<[static generator@src/main.rs:161:87: 171:2]>, layout: Layout { fields: Arbitrary { offsets: [Size { raw: 0 }], memory_index: [0] }, variants: Single { index: 0 }, abi: Aggregate { sized: true }, largest_niche: Some(Niche { offset: Size { raw: 0 }, scalar: Scalar { value: Int(I8, false), valid_range: 0..=2 } }), align: AbiAndPrefAlign { abi: Align { pow2: 0 }, pref: Align { pow2: 3 } }, size: Size { raw: 1 } } }) invalid for pair argument

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1279:9
stack backtrace:
   0:     0x7f378e09e1cd - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f378e09e1cd - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f378e09e1cd - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f378e09e1cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f378e0f801c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f378e08f7c1 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x7f378e0a12b5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f378e0a12b5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f378e0a12b5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x7f378e0a0f69 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x7f378e8ad1d1 - rustc_driver[413d55b6344850e3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f377c3d64a3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f7e2ef87b1794c3
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1875:9
  12:     0x7f377c3decac - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hda9fd97957b4a278
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/proc_macro/src/bridge/client.rs:319:21
  13:     0x7f377c3e3fb0 - std::panicking::update_hook::{{closure}}::hb276c126826df1d8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:258:41
  14:     0x7f378e0a1a00 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
  15:     0x7f378f97d141 - std[3b302b3c9093c22]::panicking::begin_panic::<rustc_errors[a7dbbf867eaca825]::ExplicitBug>::{closure#0}
  16:     0x7f378f97ce96 - std[3b302b3c9093c22]::sys_common::backtrace::__rust_end_short_backtrace::<std[3b302b3c9093c22]::panicking::begin_panic<rustc_errors[a7dbbf867eaca825]::ExplicitBug>::{closure#0}, !>
  17:     0x7f378f984406 - std[3b302b3c9093c22]::panicking::begin_panic::<rustc_errors[a7dbbf867eaca825]::ExplicitBug>
  18:     0x7f378f990ec6 - std[3b302b3c9093c22]::panic::panic_any::<rustc_errors[a7dbbf867eaca825]::ExplicitBug>
  19:     0x7f378f992673 - <rustc_errors[a7dbbf867eaca825]::HandlerInner>::bug
  20:     0x7f378f9920d0 - <rustc_errors[a7dbbf867eaca825]::Handler>::bug
  21:     0x7f378f8d1636 - rustc_middle[9ca07169fec39ed9]::ty::context::tls::with_opt::<rustc_middle[9ca07169fec39ed9]::util::bug::opt_span_bug_fmt<rustc_span[7238ca7210ca999e]::span_encoding::Span>::{closure#0}, ()>
  22:     0x7f378f8d4746 - rustc_middle[9ca07169fec39ed9]::util::bug::opt_span_bug_fmt::<rustc_span[7238ca7210ca999e]::span_encoding::Span>
  23:     0x7f378f8d46c3 - rustc_middle[9ca07169fec39ed9]::util::bug::bug_fmt
  24:     0x7f378fb43e6f - rustc_codegen_ssa[1019aa072f95d074]::mir::codegen_mir::<rustc_codegen_llvm[8781444834f164ae]::builder::Builder>
  25:     0x7f378fb0a6d4 - rustc_codegen_llvm[8781444834f164ae]::base::compile_codegen_unit::module_codegen
  26:     0x7f37908110f6 - <rustc_query_system[ac245aac4c1950a0]::dep_graph::graph::DepGraph<rustc_middle[9ca07169fec39ed9]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9ca07169fec39ed9]::ty::context::TyCtxt, rustc_span[7238ca7210ca999e]::symbol::Symbol, rustc_codegen_ssa[1019aa072f95d074]::ModuleCodegen<rustc_codegen_llvm[8781444834f164ae]::ModuleLlvm>>
  27:     0x7f37908075b9 - rustc_codegen_llvm[8781444834f164ae]::base::compile_codegen_unit
  28:     0x7f37907e1096 - rustc_codegen_ssa[1019aa072f95d074]::base::codegen_crate::<rustc_codegen_llvm[8781444834f164ae]::LlvmCodegenBackend>
  29:     0x7f3790825db3 - <rustc_codegen_llvm[8781444834f164ae]::LlvmCodegenBackend as rustc_codegen_ssa[1019aa072f95d074]::traits::backend::CodegenBackend>::codegen_crate
  30:     0x7f37907b68e7 - <rustc_session[8df92abe178df33c]::session::Session>::time::<alloc[59b4cdf2bf51ef42]::boxed::Box<dyn core[a3420257622cd381]::any::Any>, rustc_interface[550884b2b179878f]::passes::start_codegen::{closure#0}>
  31:     0x7f37907ae9cb - <rustc_interface[550884b2b179878f]::passes::QueryContext>::enter::<<rustc_interface[550884b2b179878f]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[a3420257622cd381]::result::Result<alloc[59b4cdf2bf51ef42]::boxed::Box<dyn core[a3420257622cd381]::any::Any>, rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  32:     0x7f37907db48f - <rustc_interface[550884b2b179878f]::queries::Queries>::ongoing_codegen
  33:     0x7f379078fa8b - <rustc_interface[550884b2b179878f]::interface::Compiler>::enter::<rustc_driver[413d55b6344850e3]::run_compiler::{closure#1}::{closure#2}, core[a3420257622cd381]::result::Result<core[a3420257622cd381]::option::Option<rustc_interface[550884b2b179878f]::queries::Linker>, rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  34:     0x7f379077503f - rustc_span[7238ca7210ca999e]::with_source_map::<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustc_interface[550884b2b179878f]::interface::create_compiler_and_run<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustc_driver[413d55b6344850e3]::run_compiler::{closure#1}>::{closure#1}>
  35:     0x7f37907910a4 - rustc_interface[550884b2b179878f]::interface::create_compiler_and_run::<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustc_driver[413d55b6344850e3]::run_compiler::{closure#1}>
  36:     0x7f37907737c2 - <scoped_tls[7ed3ce20ede545d8]::ScopedKey<rustc_span[7238ca7210ca999e]::SessionGlobals>>::set::<rustc_interface[550884b2b179878f]::interface::run_compiler<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustc_driver[413d55b6344850e3]::run_compiler::{closure#1}>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  37:     0x7f379078938f - std[3b302b3c9093c22]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[550884b2b179878f]::util::run_in_thread_pool_with_globals<rustc_interface[550884b2b179878f]::interface::run_compiler<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustc_driver[413d55b6344850e3]::run_compiler::{closure#1}>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  38:     0x7f3790774af9 - <<std[3b302b3c9093c22]::thread::Builder>::spawn_unchecked_<rustc_interface[550884b2b179878f]::util::run_in_thread_pool_with_globals<rustc_interface[550884b2b179878f]::interface::run_compiler<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustc_driver[413d55b6344850e3]::run_compiler::{closure#1}>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>::{closure#1} as core[a3420257622cd381]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7f378e0abbf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha99802c2c52ada61
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
  40:     0x7f378e0abbf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha39aea1c57e28a15
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
  41:     0x7f378e0abbf3 - std::sys::unix::thread::Thread::new::thread_start::h9f8e3d72b1f7662f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7f378de9f78d - <unknown>
  43:     0x7f378df208e4 - clone
  44:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0 (fe5b13d68 2022-05-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `rust-compile-bug-1` (bin "rust-compile-bug-1") generated 8 warnings
error: could not compile `rust-compile-bug-1`; 8 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling rust-compile-bug-1 v0.1.0 (/home/andy/devel/github.com/afitzek/rust-compile-bug-1)
warning: unreachable pattern
   --> src/main.rs:166:9
    |
166 |         _ => {
    |         ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

warning: unused variable: `e`
  --> src/main.rs:25:17
   |
25 |             Err(e) => {
   |                 ^ help: if this is intentional, prefix it with an underscore: `_e`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `v`
  --> src/main.rs:73:16
   |
73 |             Ok(v) => {
   |                ^ help: if this is intentional, prefix it with an underscore: `_v`

warning: unused variable: `e`
  --> src/main.rs:81:17
   |
81 |             Err(e) => {
   |                 ^ help: if this is intentional, prefix it with an underscore: `_e`

warning: unused variable: `hosts`
  --> src/main.rs:94:40
   |
94 |     pub async fn register_hosts(&self, hosts: Vec<String>) -> anyhow::Result<()> {
   |                                        ^^^^^ help: if this is intentional, prefix it with an underscore: `_hosts`

warning: unused variable: `v`
   --> src/main.rs:100:18
    |
100 |             Some(v) => {
    |                  ^ help: if this is intentional, prefix it with an underscore: `_v`

warning: unused `Result` that must be used
   --> src/main.rs:143:33
    |
143 | ...                   responder.respond(v).await;
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled

warning: unused `Result` that must be used
   --> src/main.rs:202:5
    |
202 | /     tokio::try_join!(
203 | |         lookup_handle,
204 | |         lookup_service.register_hosts(vec!["test".to_string()])
205 | |     );
    | |_____^
    |
    = note: this `Result` may be an `Err` variant, which should be handled
    = note: this warning originates in the macro `$crate::try_join` (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/compiler/rustc_codegen_ssa/src/mir/block.rs:1167:22: codegen_argument: OperandRef(Ref((%"type 0x7f59d4c5ac80"*:  %4 = alloca %41, align 1), None, Align { pow2: 0 }) @ TyAndLayout { ty: std::future::from_generator::GenFuture<[static generator@src/main.rs:161:87: 171:2]>, layout: Layout { fields: Arbitrary { offsets: [Size { raw: 0 }], memory_index: [0] }, variants: Single { index: 0 }, abi: Aggregate { sized: true }, largest_niche: Some(Niche { offset: Size { raw: 0 }, scalar: Scalar { value: Int(I8, false), valid_range: 0..=2 } }), align: AbiAndPrefAlign { abi: Align { pow2: 0 }, pref: Align { pow2: 3 } }, size: Size { raw: 1 } } }) invalid for pair argument

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1279:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug
   3: <rustc_errors::Handler>::bug
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_codegen_ssa::mir::codegen_mir::<rustc_codegen_llvm::builder::Builder>
   8: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
   9: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::symbol::Symbol, rustc_codegen_ssa::ModuleCodegen<rustc_codegen_llvm::ModuleLlvm>>
  10: rustc_codegen_llvm::base::compile_codegen_unit
  11: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  12: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  13: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  14: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  15: <rustc_interface::queries::Queries>::ongoing_codegen
  16: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  17: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  18: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  19: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0 (fe5b13d68 2022-05-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `rust-compile-bug-1` (bin "rust-compile-bug-1") generated 8 warnings
error: could not compile `rust-compile-bug-1`; 8 warnings emitted
```

</p>
</details>

**Comment by mejrs** [comment]
This compiles for me (both on current and 1.61, on Windows).

Can you try
- `cargo clean` and try again
- upgrade to the latest stable rust and try again (perhaps it has already been fixed)

**Comment by iloveabm3** [comment]
cargo clean

**Comment by afitzek** [comment]
`cargo clean` worked! Thank you very much! :)
