### ISSUE TITLE
Panic while compiling

### ISSUE THREAD

**Issue by sadmac7000** [rust-lang/rust#102160]
### Code

```Rust

// ---- Snip ---

#[tracing::instrument(level = "info")]
async fn handle_controller_request(
    node: Arc<Router>,
    r: MeshControllerRequest,
) -> Result<(), Error> {

    // This line seems to be the issue. The enum in question is no longer a single-variant enum, so the code is incorrect, but
    // of course should not crash the compiler.
    let MeshControllerRequest::AttachSocketLink { socket, control_handle: _ } = r;


    let (mut rx, mut tx) = fidl::AsyncSocket::from_socket(socket)?.split();
    let config = Box::new(|| {
        Some(fidl_fuchsia_overnet_protocol::LinkConfig::Socket(
            fidl_fuchsia_overnet_protocol::Empty {},
        ))
    });
    if let Err(e) = run_stream_link(node, None, &mut rx, &mut tx, Default::default(), config).await
    {
        tracing::warn!("Socket link failed: {:#?}", e);
    }
    Ok(())
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

### Error output

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (350cca3b6 2022-08-30) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -Z dep-info-omit-d-target -C link-args=-Wl,--Map=host_x64/exe.unstripped/hoist_lib_test.map -C linker=../../prebuilt/third_party/clang/linux-x64/bin/clang++ -C default-linker-libraries -C link-arg=--sysroot=../../prebuilt/third_party/sysroot/linux -C link-arg=--target=x86_64-unknown-linux-gnu -C link-arg=-stdlib=libc++ -C link-arg=-unwindlib=libunwind -C link-arg=-rtlib=compiler-rt -C link-arg=-fuse-ld=lld -C link-arg=-Wl,--build-id -Z remap-cwd-prefix=. -C opt-level=s -C debuginfo=2 -Z allow-features= -C linker=../../prebuilt/third_party/clang/linux-x64/bin/clang++ -C default-linker-libraries -C link-arg=--sysroot=../../prebuilt/third_party/sysroot/linux -C link-arg=--target=x86_64-unknown-linux-gnu -C link-arg=-stdlib=libc++ -C link-arg=-unwindlib=libunwind -C link-arg=-rtlib=compiler-rt -C link-arg=-fuse-ld=lld -C link-arg=-Wl,--build-id -C link-arg=-fPIE -C link-arg=-pie -C link-arg=-static-libstdc++ -C link-arg=-Wl,-rpath=$ORIGIN/ -C link-arg=-Bdynamic -C link-arg=host_x64/obj/sdk/lib/syslog/cpp/backend_host.logging_backend_host.cc.o -C link-arg=host_x64/obj/sdk/lib/syslog/cpp/backend_host.logging_backend_shared.cc.o -C link-arg=host_x64/obj/sdk/lib/syslog/cpp/cpp.log_settings.cc.o -C link-arg=host_x64/obj/sdk/lib/syslog/cpp/cpp.macros.cc.o -C link-arg=host_x64/obj/zircon/system/ulib/zx-panic-libc/libzx-panic-libc.a -C link-arg=host_x64/obj/third_party/rust_crates/compat/ring/libring-core.a -C link-arg=host_x64/obj/third_party/boringssl/libcrypto.a -C link-arg=host_x64/obj/third_party/boringssl/libssl.a -C link-arg=host_x64/obj/sdk/lib/fit-promise/libfit-promise.a -C link-arg=host_x64/obj/sdk/lib/fit/libfit.a -C link-arg=host_x64/obj/sdk/lib/stdcompat/libstdcompat.a

query stack during panic:
#0 [mir_built] building MIR for `not_fuchsia::handle_controller_request::{closure#0}::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `not_fuchsia::handle_controller_request::{closure#0}::{closure#0}`
#2 [unsafety_check_result] unsafety-checking `not_fuchsia::handle_controller_request::{closure#0}`
#3 [unsafety_check_result] unsafety-checking `not_fuchsia::handle_controller_request`
#4 [mir_const] processing MIR for `not_fuchsia::handle_controller_request`
#5 [mir_promoted] processing `not_fuchsia::handle_controller_request`
#6 [mir_borrowck] borrow-checking `not_fuchsia::handle_controller_request`
#7 [type_of] computing type of `not_fuchsia::handle_controller_request::{opaque#0}`
#8 [check_mod_item_types] checking item types in module `not_fuchsia`
#9 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_mir_build/src/build/matches/mod.rs:1853:25
stack backtrace:
   0: rust_begin_unwind
             at rustlib/src/rust/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at rustlib/src/rust/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at rustlib/src/rust/library/core/src/panicking.rs:48:5
   3: <rustc_mir_build::build::Builder>::bind_and_guard_matched_candidate
   4: <rustc_mir_build::build::Builder>::bind_pattern
   5: <rustc_mir_build::build::Builder>::place_into_pattern
   6: <rustc_mir_build::build::Builder>::ast_block_stmts
   7: <rustc_mir_build::build::Builder>::expr_into_dest
   8: <rustc_mir_build::build::Builder>::in_scope::<<rustc_mir_build::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
   9: <rustc_mir_build::build::Builder>::expr_into_dest::{closure#0}
  10: <rustc_mir_build::build::Builder>::expr_into_dest
  11: <rustc_mir_build::build::Builder>::in_scope::<<rustc_mir_build::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  12: <rustc_mir_build::build::Builder>::expr_into_dest::{closure#0}
  13: <rustc_mir_build::build::Builder>::expr_into_dest
  14: rustc_mir_build::build::construct_fn::<core::iter::adapters::chain::Chain<alloc::vec::into_iter::IntoIter<rustc_mir_build::build::ArgInfo>, core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_hir::hir::Param>>, rustc_mir_build::build::mir_build::{closure#1}::{closure#1}>>>
  15: <rustc_infer::infer::InferCtxtBuilder>::enter::<rustc_middle::mir::Body, rustc_mir_build::build::mir_build::{closure#1}>
  16: rustc_mir_build::build::mir_built
  17: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>>
  18: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_built, rustc_query_impl::plumbing::QueryCtxt>
  19: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
  20: rustc_mir_transform::check_unsafety::unsafety_check_result
  21: <rustc_mir_transform::check_unsafety::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
  22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::UnsafetyCheckResult>>
  23: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::unsafety_check_result, rustc_query_impl::plumbing::QueryCtxt>
  24: <rustc_mir_transform::check_unsafety::UnsafetyChecker as rustc_middle::mir::visit::Visitor>::visit_rvalue
  25: rustc_mir_transform::check_unsafety::unsafety_check_result
  26: <rustc_mir_transform::check_unsafety::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
  27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::UnsafetyCheckResult>>
  28: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::unsafety_check_result, rustc_query_impl::plumbing::QueryCtxt>
  29: <rustc_mir_transform::check_unsafety::UnsafetyChecker as rustc_middle::mir::visit::Visitor>::visit_rvalue
  30: rustc_mir_transform::check_unsafety::unsafety_check_result
  31: <rustc_mir_transform::check_unsafety::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
  32: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::UnsafetyCheckResult>>
  33: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::unsafety_check_result, rustc_query_impl::plumbing::QueryCtxt>
  34: rustc_mir_transform::mir_const
  35: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>>
  36: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_const, rustc_query_impl::plumbing::QueryCtxt>
  37: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_const
  38: rustc_mir_transform::mir_promoted
  39: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_promoted, rustc_query_impl::plumbing::QueryCtxt>
  41: rustc_borrowck::mir_borrowck
  42: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
  43: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>>
  44: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
  45: rustc_typeck::collect::type_of::find_opaque_ty_constraints_for_rpit
  46: rustc_typeck::collect::type_of::type_of
  47: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::ty::Ty>>
  48: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::type_of, rustc_query_impl::plumbing::QueryCtxt>
  49: rustc_typeck::check::check::check_opaque
  50: rustc_typeck::check::check::check_item_type
  51: rustc_typeck::check::check::check_mod_item_types
  52: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  53: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::check_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
  54: <rustc_middle::hir::map::Map>::for_each_module::<rustc_typeck::check_crate::{closure#6}::{closure#0}>
  55: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#6}>
  56: rustc_typeck::check_crate
  57: rustc_interface::passes::analysis
  58: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  59: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  60: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  61: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  62: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  63: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  64: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by compiler-errors** [comment]
@sadmac7000 can you verify if this is fixed on the latest stable version of Rust?

**Comment by sadmac7000** [comment]
Not easily in this environment sadly.

**Comment by compiler-errors** [comment]
Can you at least provide a more complete sample of code to reproduce this issue? Otherwise there's little to work with here...
