### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [rust-lang/rust#102357]
### Code

compile https://github.com/pingcap/tidb-engine-ext

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
binary: rustc
commit-hash: 0f4bcadb46006bc484dad85616b484f93879ca4e
commit-date: 2022-07-30
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 38039 but the index is 4294967295', /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/compiler/rustc_middle/src/ty/context.rs:1403:13
stack backtrace:
   0:     0x7fc848a9f300 - std::backtrace_rs::backtrace::libunwind::trace::h31edb439d75c23ea
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fc848a9f300 - std::backtrace_rs::backtrace::trace_unsynchronized::hfd0c10bfc67bc40b
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc848a9f300 - std::sys_common::backtrace::_print_fmt::hd5ece79ecc21e662
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fc848a9f300 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h384e15382df8418e
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fc848afa71c - core::fmt::write::h09b8d6cece5f7080
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/core/src/fmt/mod.rs:1198:17
   5:     0x7fc848a90425 - std::io::Write::write_fmt::heb069dea4698d1ac
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/io/mod.rs:1672:15
   6:     0x7fc848aa1fd1 - std::sys_common::backtrace::_print::h03e4174505f14fd8
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fc848aa1fd1 - std::sys_common::backtrace::print::h4b64c72edc588aee
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fc848aa1fd1 - std::panicking::default_hook::{{closure}}::h5f215ae338479336
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/panicking.rs:295:22
   9:     0x7fc848aa1ca3 - std::panicking::default_hook::h7bd72f91dacb10dc
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/panicking.rs:314:9
  10:     0x7fc8474fad54 - <rustc_driver[d864055df839f662]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[35995d61b05a2a59]::ops::function::FnOnce<(&core[35995d61b05a2a59]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7fc848aa2806 - std::panicking::rust_panic_with_hook::h224a2633d189d821
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/panicking.rs:702:17
  12:     0x7fc848aa2657 - std::panicking::begin_panic_handler::{{closure}}::h5696293c9775baf5
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/panicking.rs:588:13
  13:     0x7fc848a9f824 - std::sys_common::backtrace::__rust_end_short_backtrace::h16692dd903c6d283
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fc848aa2382 - rust_begin_unwind
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/panicking.rs:584:5
  15:     0x7fc848af71f3 - core::panicking::panic_fmt::he2acabb419088210
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/core/src/panicking.rs:142:14
  16:     0x7fc848af7132 - core::panicking::panic_bounds_check::h939fb2c767c1b770
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/core/src/panicking.rs:84:5
  17:     0x7fc8470b76eb - <[rustc_hir[a3df154174837b06]::hir::ItemId] as rustc_serialize[24bac53ae34510b7]::serialize::Encodable<rustc_query_impl[d883736f3269451]::on_disk_cache::CacheEncoder>>::encode
  18:     0x7fc8470b7278 - <rustc_middle[b92577c6c7760ab]::hir::ModuleItems as rustc_serialize[24bac53ae34510b7]::serialize::Encodable<rustc_query_impl[d883736f3269451]::on_disk_cache::CacheEncoder>>::encode
  19:     0x7fc8470b70ea - rustc_query_impl[d883736f3269451]::on_disk_cache::encode_query_results::<rustc_query_impl[d883736f3269451]::plumbing::QueryCtxt, rustc_query_impl[d883736f3269451]::queries::hir_module_items>::{closure#0}
  20:     0x7fc846b33f02 - <rustc_query_system[e1d1848862cd4fa9]::query::caches::ArenaCache<rustc_span[9ff075de139204cb]::def_id::LocalDefId, rustc_middle[b92577c6c7760ab]::hir::ModuleItems> as rustc_query_system[e1d1848862cd4fa9]::query::caches::QueryCache>::iter
  21:     0x7fc846b33dc8 - rustc_query_impl[d883736f3269451]::on_disk_cache::encode_query_results::<rustc_query_impl[d883736f3269451]::plumbing::QueryCtxt, rustc_query_impl[d883736f3269451]::queries::hir_module_items>
  22:     0x7fc846b30a29 - <rustc_query_impl[d883736f3269451]::plumbing::QueryCtxt>::encode_query_results
  23:     0x7fc846b2ebf4 - <rustc_session[e01f1e918c25c286]::session::Session>::time::<(), <rustc_query_impl[d883736f3269451]::on_disk_cache::OnDiskCache as rustc_middle[b92577c6c7760ab]::ty::context::OnDiskCache>::serialize::{closure#0}::{closure#0}>
  24:     0x7fc846b2d873 - rustc_middle[b92577c6c7760ab]::ty::context::tls::with_context::<<rustc_middle[b92577c6c7760ab]::dep_graph::dep_node::DepKind as rustc_query_system[e1d1848862cd4fa9]::dep_graph::DepKind>::with_deps<<rustc_query_impl[d883736f3269451]::on_disk_cache::OnDiskCache as rustc_middle[b92577c6c7760ab]::ty::context::OnDiskCache>::serialize::{closure#0}, core[35995d61b05a2a59]::result::Result<usize, std[b4536ab15c6bbb10]::io::error::Error>>::{closure#0}, core[35995d61b05a2a59]::result::Result<usize, std[b4536ab15c6bbb10]::io::error::Error>>::{closure#0}
  25:     0x7fc8473df14f - <rustc_query_impl[d883736f3269451]::on_disk_cache::OnDiskCache as rustc_middle[b92577c6c7760ab]::ty::context::OnDiskCache>::serialize
  26:     0x7fc846d3ce23 - <rustc_middle[b92577c6c7760ab]::ty::context::TyCtxt>::serialize_query_result_cache
  27:     0x7fc846d3cd0e - rustc_incremental[17bef8061b9767f6]::persist::save::encode_query_cache
  28:     0x7fc846d3c1a5 - rustc_incremental[17bef8061b9767f6]::persist::file_format::save_in::<rustc_incremental[17bef8061b9767f6]::persist::save::save_dep_graph::{closure#0}::{closure#2}::{closure#0}::{closure#0}>
  29:     0x7fc846cdf945 - <rustc_session[e01f1e918c25c286]::session::Session>::time::<(), rustc_incremental[17bef8061b9767f6]::persist::save::save_dep_graph::{closure#0}::{closure#2}::{closure#0}>
  30:     0x7fc846cd51c9 - <rustc_middle[b92577c6c7760ab]::dep_graph::dep_node::DepKind as rustc_query_system[e1d1848862cd4fa9]::dep_graph::DepKind>::with_deps::<rustc_incremental[17bef8061b9767f6]::persist::save::save_dep_graph::{closure#0}, ()>
  31:     0x7fc846cd3ba1 - rustc_incremental[17bef8061b9767f6]::persist::save::save_dep_graph
  32:     0x7fc846cd331c - <rustc_interface[900ca293153297ea]::interface::Compiler>::enter::<rustc_driver[d864055df839f662]::run_compiler::{closure#1}::{closure#2}, core[35995d61b05a2a59]::result::Result<core[35995d61b05a2a59]::option::Option<rustc_interface[900ca293153297ea]::queries::Linker>, rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>>
  33:     0x7fc846cc6a1a - rustc_span[9ff075de139204cb]::with_source_map::<core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>, rustc_interface[900ca293153297ea]::interface::create_compiler_and_run<core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>, rustc_driver[d864055df839f662]::run_compiler::{closure#1}>::{closure#1}>
  34:     0x7fc846cc63f0 - rustc_interface[900ca293153297ea]::interface::create_compiler_and_run::<core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>, rustc_driver[d864055df839f662]::run_compiler::{closure#1}>
  35:     0x7fc846cc4761 - <scoped_tls[ebe096adc7bd02c1]::ScopedKey<rustc_span[9ff075de139204cb]::SessionGlobals>>::set::<rustc_interface[900ca293153297ea]::interface::run_compiler<core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>, rustc_driver[d864055df839f662]::run_compiler::{closure#1}>::{closure#0}, core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>>
  36:     0x7fc846cc444f - std[b4536ab15c6bbb10]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[900ca293153297ea]::util::run_in_thread_pool_with_globals<rustc_interface[900ca293153297ea]::interface::run_compiler<core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>, rustc_driver[d864055df839f662]::run_compiler::{closure#1}>::{closure#0}, core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>>::{closure#0}, core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>>
  37:     0x7fc847326549 - <<std[b4536ab15c6bbb10]::thread::Builder>::spawn_unchecked_<rustc_interface[900ca293153297ea]::util::run_in_thread_pool_with_globals<rustc_interface[900ca293153297ea]::interface::run_compiler<core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>, rustc_driver[d864055df839f662]::run_compiler::{closure#1}>::{closure#0}, core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>>::{closure#0}, core[35995d61b05a2a59]::result::Result<(), rustc_errors[fd35ba0f3e6e2e25]::ErrorGuaranteed>>::{closure#1} as core[35995d61b05a2a59]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7fc848aac2a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he325941c9178e1bb
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/alloc/src/boxed.rs:1935:9
  39:     0x7fc848aac2a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd9369e1e4ce32e48
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/alloc/src/boxed.rs:1935:9
  40:     0x7fc848aac2a3 - std::sys::unix::thread::Thread::new::thread_start::h501a801cbc05471d
                               at /rustc/0f4bcadb46006bc484dad85616b484f93879ca4e/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7fc8446e8e63 - start_thread
                               at /root/yuzhao/glibc-2.17/nptl/pthread_create.c:308
  42:     0x7fc84441955d - __clone
                               at /root/yuzhao/glibc-2.17/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113
  43:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (0f4bcadb4 2022-07-30) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=4 -C debuginfo=2 -C overflow-checks=off -C incremental -Z unstable-options -C link-arg=-fuse-ld=lld -C rpath=yes -C linker=/data1/qiuyang/projects/tiflash/build/contrib/tiflash-proxy-cmake/tiflash-linker -C force-frame-pointers=yes -C force-frame-pointers=yes

note: some of the compiler flags provided by cargo are hidden
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Rageking8** [comment]
@rustbot label +T-compiler +I-ICE +E-needs-mcve

> note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

@Lloyd-Pottiger Thanks for submitting an issue, however please use the link provided in the backtrace to open an ICE issue with the right template.

**Comment by Lloyd-Pottiger** [comment]
updated

**Comment by Lloyd-Pottiger** [comment]
> Can you update to the latest nightly and see if the issue is still present? Thanks!

yes, still

**Comment by istankovic** [comment]
@Lloyd-Pottiger could you please test with latest nightly and see if the issue is still there?

**Comment by Lloyd-Pottiger** [comment]
> @Lloyd-Pottiger could you please test with latest nightly and see if the issue is still there?

No, I will close this issue.
