### ISSUE TITLE
Internal compiler error from traderust

### ISSUE THREAD

**Issue by dripton** [rust-lang/rust#102687]
### Code

I made a commit with the exact broken code that causes this panic.  I have not minimized it yet.

https://github.com/dripton/traderust/commit/301d27f80e0d53e2173780ed9156948af64fcd3c

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (5435ed691 2022-06-07)
binary: rustc
commit-hash: 5435ed6916a59e8d5acba2149316a841c3905cbd
commit-date: 2022-06-07
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

### Error output

```
$ cargo b
   Compiling traderust v0.1.0 (/home/dripton/git/traderust)
error: this file contains an unclosed delimiter
    --> src/main.rs:1758:3
     |
349  | fn distance_modifier_table(distance: u16, iw_rules: bool) -> f64 {
     |                                                                  - unclosed delimiter
...
1758 | }
     |   ^

error[E0432]: unresolved imports `crate::Coords`, `crate::Sector`, `crate::World`
  --> src/pdf.rs:17:13
   |
17 | use crate::{Coords, Sector, World, DBTN_TO_CREDITS};
   |             ^^^^^^  ^^^^^^  ^^^^^ no `World` in the root
   |             |       |
   |             |       no `Sector` in the root
   |             no `Coords` in the root

error[E0412]: cannot find type `Coords` in this scope
   --> src/main.rs:309:25
    |
308 | fn populate_navigable_distances(
    |                                - help: you might be missing a type parameter: `<Coords>`
309 |     sorted_coords: &Vec<Coords>,
    |                         ^^^^^^ not found in this scope

error[E0412]: cannot find type `Coords` in this scope
   --> src/main.rs:310:31
    |
308 | fn populate_navigable_distances(
    |                                - help: you might be missing a type parameter: `<Coords>`
309 |     sorted_coords: &Vec<Coords>,
310 |     coords_to_world: &HashMap<Coords, World>,
    |                               ^^^^^^ not found in this scope

error[E0412]: cannot find type `World` in this scope
   --> src/main.rs:310:39
    |
308 | fn populate_navigable_distances(
    |                                - help: you might be missing a type parameter: `<World>`
309 |     sorted_coords: &Vec<Coords>,
310 |     coords_to_world: &HashMap<Coords, World>,
    |                                       ^^^^^ not found in this scope

error: internal compiler error: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:856:33: unexpected path: def=ndarray::ArrayBase substs=[_, _] path=Path { span: src/main.rs:320:18: 320:31 (#0), res: Def(TyAlias, DefId(21:195 ~ ndarray[f54d]::aliases::Array2)), segments: [PathSegment { ident: Array2#0, hir_id: Some(HirId { owner: DefId(0:268 ~ traderust[1321]::populate_navigable_distances), local_id: 125 }), res: Some(Err), args: Some(GenericArgs { args: [Type(Ty { hir_id: HirId { owner: DefId(0:268 ~ traderust[1321]::populate_navigable_distances), local_id: 123 }, kind: Path(Resolved(None, Path { span: src/main.rs:320:27: 320:30 (#0), res: PrimTy(Uint(U16)), segments: [PathSegment { ident: u16#0, hir_id: Some(HirId { owner: DefId(0:268 ~ traderust[1321]::populate_navigable_distances), local_id: 124 }), res: Some(Err), args: None, infer_args: false }] })), span: src/main.rs:320:27: 320:30 (#0) })], bindings: [], parenthesized: false, span_ext: src/main.rs:320:26: 320:31 (#0) }), infer_args: false }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/compiler/rustc_errors/src/lib.rs:1334:9
stack backtrace:
   0:     0x7f5aacc9e09d - std::backtrace_rs::backtrace::libunwind::trace::hee7943ada6bad29e
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5aacc9e09d - std::backtrace_rs::backtrace::trace_unsynchronized::h7ccd83155a46c065
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5aacc9e09d - std::sys_common::backtrace::_print_fmt::hfe24db8e4118fad6
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f5aacc9e09d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7d03ef0a4b68cd6d
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f5aaccf9e2c - core::fmt::write::hb36860eff00e9ada
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f5aacc8f831 - std::io::Write::write_fmt::ha4850a1b39c307b1
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/io/mod.rs:1654:15
   6:     0x7f5aacca0d75 - std::sys_common::backtrace::_print::hf3ecf36d224b16f3
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f5aacca0d75 - std::sys_common::backtrace::print::ha31789107cdf7920
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f5aacca0d75 - std::panicking::default_hook::{{closure}}::h1ca420da35ab94ba
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/panicking.rs:295:22
   9:     0x7f5aacca0a96 - std::panicking::default_hook::hf7cfd911ca8444f2
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/panicking.rs:314:9
  10:     0x7f5aad4f9911 - rustc_driver[9b2cc5dd0ee5154e]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f5a907d8d63 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5feb9c9efff7df64
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/alloc/src/boxed.rs:1965:9
  12:     0x7f5a907ca62d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h802884e90caa8638
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/proc_macro/src/bridge/client.rs:339:21
  13:     0x7f5aacca144a - std::panicking::rust_panic_with_hook::h8b0eedba7af397b5
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/panicking.rs:702:17
  14:     0x7f5aae595191 - std[a0eb98a96cd1d67b]::panicking::begin_panic::<rustc_errors[f2e3be3759aa4428]::ExplicitBug>::{closure#0}
  15:     0x7f5aae594ba6 - std[a0eb98a96cd1d67b]::sys_common::backtrace::__rust_end_short_backtrace::<std[a0eb98a96cd1d67b]::panicking::begin_panic<rustc_errors[f2e3be3759aa4428]::ExplicitBug>::{closure#0}, !>
  16:     0x7f5aae511476 - std[a0eb98a96cd1d67b]::panicking::begin_panic::<rustc_errors[f2e3be3759aa4428]::ExplicitBug>
  17:     0x7f5aae537836 - std[a0eb98a96cd1d67b]::panic::panic_any::<rustc_errors[f2e3be3759aa4428]::ExplicitBug>
  18:     0x7f5aae5372d5 - <rustc_errors[f2e3be3759aa4428]::HandlerInner>::bug::<&alloc[c44c0bf1429d9201]::string::String>
  19:     0x7f5aae535630 - <rustc_errors[f2e3be3759aa4428]::Handler>::bug::<&alloc[c44c0bf1429d9201]::string::String>
  20:     0x7f5aae59212d - rustc_middle[8ca1ffa4f0d07531]::ty::context::tls::with_opt::<rustc_middle[8ca1ffa4f0d07531]::util::bug::opt_span_bug_fmt<rustc_span[e19345dc80a27759]::span_encoding::Span>::{closure#0}, ()>
  21:     0x7f5aae592226 - rustc_middle[8ca1ffa4f0d07531]::util::bug::opt_span_bug_fmt::<rustc_span[e19345dc80a27759]::span_encoding::Span>
  22:     0x7f5aae5921a3 - rustc_middle[8ca1ffa4f0d07531]::util::bug::bug_fmt
  23:     0x7f5aae4677cb - <rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor>::path_inferred_subst_iter
  24:     0x7f5aae467d53 - <rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[3e81ab229655f335]::intravisit::Visitor>::visit_expr
  25:     0x7f5aae467bdc - <rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[3e81ab229655f335]::intravisit::Visitor>::visit_expr
  26:     0x7f5aae47e2bc - rustc_hir[3e81ab229655f335]::intravisit::walk_local::<rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  27:     0x7f5aae467858 - <rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[3e81ab229655f335]::intravisit::Visitor>::visit_local
  28:     0x7f5aae47e107 - rustc_hir[3e81ab229655f335]::intravisit::walk_block::<rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  29:     0x7f5aae467bee - <rustc_infer[1b92be4cd5a18007]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[3e81ab229655f335]::intravisit::Visitor>::visit_expr
  30:     0x7f5aae426a74 - <rustc_infer[1b92be4cd5a18007]::infer::InferCtxt>::emit_inference_failure_err
  31:     0x7f5aae378b52 - <rustc_infer[1b92be4cd5a18007]::infer::InferCtxt as rustc_trait_selection[324f59158696700b]::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  32:     0x7f5aae36c6f7 - <rustc_infer[1b92be4cd5a18007]::infer::InferCtxt as rustc_trait_selection[324f59158696700b]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  33:     0x7f5aaeabed42 - <rustc_infer[1b92be4cd5a18007]::infer::InferCtxtBuilder>::enter::<&rustc_middle[8ca1ffa4f0d07531]::ty::context::TypeckResults, <rustc_typeck[65f6cc0eda670a77]::check::inherited::InheritedBuilder>::enter<rustc_typeck[65f6cc0eda670a77]::check::typeck_with_fallback<rustc_typeck[65f6cc0eda670a77]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[8ca1ffa4f0d07531]::ty::context::TypeckResults>::{closure#0}>
  34:     0x7f5aaea5100a - rustc_typeck[65f6cc0eda670a77]::check::typeck
  35:     0x7f5aafb4f830 - <rustc_query_system[e792b288446fca87]::dep_graph::graph::DepGraph<rustc_middle[8ca1ffa4f0d07531]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8ca1ffa4f0d07531]::ty::context::TyCtxt, rustc_span[e19345dc80a27759]::def_id::LocalDefId, &rustc_middle[8ca1ffa4f0d07531]::ty::context::TypeckResults>
  36:     0x7f5aaf0790b0 - rustc_query_system[e792b288446fca87]::query::plumbing::try_execute_query::<rustc_query_impl[f4d741971085f907]::plumbing::QueryCtxt, rustc_query_system[e792b288446fca87]::query::caches::DefaultCache<rustc_span[e19345dc80a27759]::def_id::LocalDefId, &rustc_middle[8ca1ffa4f0d07531]::ty::context::TypeckResults>>
  37:     0x7f5aaefa484e - <rustc_query_impl[f4d741971085f907]::Queries as rustc_middle[8ca1ffa4f0d07531]::ty::query::QueryEngine>::typeck
  38:     0x7f5aaeb0fdc8 - <rustc_middle[8ca1ffa4f0d07531]::hir::map::Map>::par_body_owners::<rustc_typeck[65f6cc0eda670a77]::check::typeck_item_bodies::{closure#0}>
  39:     0x7f5aaf90d70c - rustc_typeck[65f6cc0eda670a77]::check::typeck_item_bodies
  40:     0x7f5aafb6f034 - <rustc_query_system[e792b288446fca87]::dep_graph::graph::DepGraph<rustc_middle[8ca1ffa4f0d07531]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8ca1ffa4f0d07531]::ty::context::TyCtxt, (), ()>
  41:     0x7f5aafc1a0e5 - rustc_query_system[e792b288446fca87]::query::plumbing::try_execute_query::<rustc_query_impl[f4d741971085f907]::plumbing::QueryCtxt, rustc_query_system[e792b288446fca87]::query::caches::DefaultCache<(), ()>>
  42:     0x7f5aafc44371 - rustc_query_system[e792b288446fca87]::query::plumbing::get_query::<rustc_query_impl[f4d741971085f907]::queries::typeck_item_bodies, rustc_query_impl[f4d741971085f907]::plumbing::QueryCtxt>
  43:     0x7f5aaf9440b3 - <rustc_session[e99e5395caf9b62]::session::Session>::time::<(), rustc_typeck[65f6cc0eda670a77]::check_crate::{closure#7}>
  44:     0x7f5aaf930cdb - rustc_typeck[65f6cc0eda670a77]::check_crate
  45:     0x7f5aaf6ed587 - rustc_interface[2808bdc579fb1dcb]::passes::analysis
  46:     0x7f5aafb6a315 - <rustc_query_system[e792b288446fca87]::dep_graph::graph::DepGraph<rustc_middle[8ca1ffa4f0d07531]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[8ca1ffa4f0d07531]::ty::context::TyCtxt, (), core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>
  47:     0x7f5aafc0f54d - rustc_query_system[e792b288446fca87]::query::plumbing::try_execute_query::<rustc_query_impl[f4d741971085f907]::plumbing::QueryCtxt, rustc_query_system[e792b288446fca87]::query::caches::DefaultCache<(), core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>>
  48:     0x7f5aafc5692e - rustc_query_system[e792b288446fca87]::query::plumbing::get_query::<rustc_query_impl[f4d741971085f907]::queries::analysis, rustc_query_impl[f4d741971085f907]::plumbing::QueryCtxt>
  49:     0x7f5aaf6aaa47 - <rustc_interface[2808bdc579fb1dcb]::passes::QueryContext>::enter::<rustc_driver[9b2cc5dd0ee5154e]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>
  50:     0x7f5aaf694bbf - <rustc_interface[2808bdc579fb1dcb]::interface::Compiler>::enter::<rustc_driver[9b2cc5dd0ee5154e]::run_compiler::{closure#1}::{closure#2}, core[9a5575405027e362]::result::Result<core[9a5575405027e362]::option::Option<rustc_interface[2808bdc579fb1dcb]::queries::Linker>, rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>
  51:     0x7f5aaf6be1cf - rustc_span[e19345dc80a27759]::with_source_map::<core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>, rustc_interface[2808bdc579fb1dcb]::interface::create_compiler_and_run<core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>, rustc_driver[9b2cc5dd0ee5154e]::run_compiler::{closure#1}>::{closure#1}>
  52:     0x7f5aaf695a52 - <scoped_tls[846b7f23ce5bfed4]::ScopedKey<rustc_span[e19345dc80a27759]::SessionGlobals>>::set::<rustc_interface[2808bdc579fb1dcb]::interface::run_compiler<core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>, rustc_driver[9b2cc5dd0ee5154e]::run_compiler::{closure#1}>::{closure#0}, core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>
  53:     0x7f5aaf6ab0cf - std[a0eb98a96cd1d67b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2808bdc579fb1dcb]::util::run_in_thread_pool_with_globals<rustc_interface[2808bdc579fb1dcb]::interface::run_compiler<core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>, rustc_driver[9b2cc5dd0ee5154e]::run_compiler::{closure#1}>::{closure#0}, core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>::{closure#0}, core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>
  54:     0x7f5aaf6ab239 - <<std[a0eb98a96cd1d67b]::thread::Builder>::spawn_unchecked_<rustc_interface[2808bdc579fb1dcb]::util::run_in_thread_pool_with_globals<rustc_interface[2808bdc579fb1dcb]::interface::run_compiler<core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>, rustc_driver[9b2cc5dd0ee5154e]::run_compiler::{closure#1}>::{closure#0}, core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>::{closure#0}, core[9a5575405027e362]::result::Result<(), rustc_errors[f2e3be3759aa4428]::ErrorGuaranteed>>::{closure#1} as core[9a5575405027e362]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7f5aaccab373 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hed7040088a8f20af
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/alloc/src/boxed.rs:1951:9
  56:     0x7f5aaccab373 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h74b0534bb454589b
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/alloc/src/boxed.rs:1951:9
  57:     0x7f5aaccab373 - std::sys::unix::thread::Thread::new::thread_start::hf83752a2adec8b03
                               at /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/library/std/src/sys/unix/thread.rs:108:17
  58:     0x7f5aaca6cb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  59:     0x7f5aacafea00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  60:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (5435ed691 2022-06-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `populate_navigable_distances`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
Some errors have detailed explanations: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `traderust` due to 5 previous errors

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 RUST_BACKTRACE=1 cargo b
   Compiling traderust v0.1.0 (/home/dripton/git/traderust)
error: this file contains an unclosed delimiter
    --> src/main.rs:1758:3
     |
349  | fn distance_modifier_table(distance: u16, iw_rules: bool) -> f64 {
     |                                                                  - unclosed delimiter
...
1758 | }
     |   ^

error[E0432]: unresolved imports `crate::Coords`, `crate::Sector`, `crate::World`
  --> src/pdf.rs:17:13
   |
17 | use crate::{Coords, Sector, World, DBTN_TO_CREDITS};
   |             ^^^^^^  ^^^^^^  ^^^^^ no `World` in the root
   |             |       |
   |             |       no `Sector` in the root
   |             no `Coords` in the root

error[E0412]: cannot find type `Coords` in this scope
   --> src/main.rs:309:25
    |
308 | fn populate_navigable_distances(
    |                                - help: you might be missing a type parameter: `<Coords>`
309 |     sorted_coords: &Vec<Coords>,
    |                         ^^^^^^ not found in this scope

error[E0412]: cannot find type `Coords` in this scope
   --> src/main.rs:310:31
    |
308 | fn populate_navigable_distances(
    |                                - help: you might be missing a type parameter: `<Coords>`
309 |     sorted_coords: &Vec<Coords>,
310 |     coords_to_world: &HashMap<Coords, World>,
    |                               ^^^^^^ not found in this scope

error[E0412]: cannot find type `World` in this scope
   --> src/main.rs:310:39
    |
308 | fn populate_navigable_distances(
    |                                - help: you might be missing a type parameter: `<World>`
309 |     sorted_coords: &Vec<Coords>,
310 |     coords_to_world: &HashMap<Coords, World>,
    |                                       ^^^^^ not found in this scope

error: internal compiler error: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:856:33: unexpected path: def=ndarray::ArrayBase substs=[_, _] path=Path { span: src/main.rs:320:18: 320:31 (#0), res: Def(TyAlias, DefId(21:195 ~ ndarray[f54d]::aliases::Array2)), segments: [PathSegment { ident: Array2#0, hir_id: Some(HirId { owner: DefId(0:268 ~ traderust[1321]::populate_navigable_distances), local_id: 125 }), res: Some(Err), args: Some(GenericArgs { args: [Type(Ty { hir_id: HirId { owner: DefId(0:268 ~ traderust[1321]::populate_navigable_distances), local_id: 123 }, kind: Path(Resolved(None, Path { span: src/main.rs:320:27: 320:30 (#0), res: PrimTy(Uint(U16)), segments: [PathSegment { ident: u16#0, hir_id: Some(HirId { owner: DefId(0:268 ~ traderust[1321]::populate_navigable_distances), local_id: 124 }), res: Some(Err), args: None, infer_args: false }] })), span: src/main.rs:320:27: 320:30 (#0) })], bindings: [], parenthesized: false, span_ext: src/main.rs:320:26: 320:31 (#0) }), infer_args: false }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/5435ed6916a59e8d5acba2149316a841c3905cbd/compiler/rustc_errors/src/lib.rs:1334:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor>::path_inferred_subst_iter
   8: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
   9: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  10: rustc_hir::intravisit::walk_local::<rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  11: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_local
  12: rustc_hir::intravisit::walk_block::<rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  13: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  14: <rustc_infer::infer::InferCtxt>::emit_inference_failure_err
  15: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  16: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  17: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
  18: rustc_typeck::check::typeck
  19: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  22: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_typeck::check::typeck_item_bodies::{closure#0}>
  23: rustc_typeck::check::typeck_item_bodies
  24: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  26: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
  27: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
  28: rustc_typeck::check_crate
  29: rustc_interface::passes::analysis
  30: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  32: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  33: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  34: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  35: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  36: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (5435ed691 2022-06-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `populate_navigable_distances`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
Some errors have detailed explanations: E0412, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `traderust` due to 5 previous errors

```

</p>
</details>

**Comment by dripton** [comment]
@jieyouxu Good news, it doesn't crash anymore with rustc 1.78.0-nightly (ef324565d 2024-02-27).

Closing the bug.
