### ISSUE TITLE
Failed to extract DefId: local_def_id_to_hir_id

### ISSUE THREAD

**Issue by dnut** [rust-lang/rust#102668]
### Code
https://github.com/jet-lab/jet-v2/pull/360/commits/8e384b87b066661f1f491f4a1238afe82cda9d9f

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

### Error output

```
 *  Executing task: cargo test --package hosted-tests --test bonds -- margin --exact --nocapture 

warning: skipping duplicate package `shared` found at `/home/drew/.cargo/git/checkouts/anchor-98410c127f24a008/5860941/tests/typescript/programs/shared`
warning: skipping duplicate package `shared` found at `/home/drew/.cargo/git/checkouts/anchor-98410c127f24a008/5860941/tests/zero-copy/programs/shared`
warning: skipping duplicate package `swap` found at `/home/drew/.cargo/git/checkouts/anchor-98410c127f24a008/5860941/tests/cfo/deps/swap/programs/swap`
   Compiling jet-margin-sdk v0.1.0 (/data/projects/jet-v2/libraries/rust/margin)
   Compiling hosted-tests v0.1.0 (/data/projects/jet-v2/tests/hosted)
thread 'rustc' panicked at 'Failed to extract DefId: local_def_id_to_hir_id 2bc7d07f9aa30790-98f33cd9989a54e1', compiler/rustc_middle/src/dep_graph/dep_node.rs:276:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: <rustc_query_system::dep_graph::dep_node::DepNode<rustc_middle::dep_graph::dep_node::DepKind> as rustc_middle::dep_graph::dep_node::DepNodeExt>::extract_def_id::{closure#0}
   3: <rustc_query_system::dep_graph::dep_node::DepNode<rustc_middle::dep_graph::dep_node::DepKind> as rustc_middle::dep_graph::dep_node::DepNodeExt>::extract_def_id
   4: rustc_query_impl::query_callbacks::local_def_id_to_hir_id::force_from_dep_node
   5: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
   6: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   7: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   8: rustc_query_system::query::plumbing::ensure_must_run::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
   9: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::check_mod_item_types, rustc_query_impl::plumbing::QueryCtxt>
  10: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#6}>
  11: rustc_typeck::check_crate
  12: rustc_interface::passes::analysis
  13: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  15: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  16: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  17: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  18: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  19: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `hosted-tests`

 *  The terminal process "cargo 'test', '--package', 'hosted-tests', '--test', 'bonds', '--', 'margin', '--exact', '--nocapture'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by cjgillot** [comment]
This is a bug with incremental compilation. Do you remember which changes you were making when this happened?

**Comment by dnut** [comment]
The linked commit is the change that led to this issue. It was a work in progress that I committed immediately as soon as I saw this error in hope that it would be reproducible from that commit.

I think maybe the last thing I did within that commit was something in the file `tests/hosted/tests/bonds.rs` around this line:
```rust
let wallet = user.user.signer;
```
Previously I had this
```rust
let wallet = user.user.tx.signer.unwrap();
```
and the struct for the tx field probably looked something like this:
```rust
pub struct MarginTxBuilder {
    rpc: Arc<dyn SolanaRpcClient>,
    ///
    pub ix: MarginIxBuilder,
    config_ix: MarginConfigIxBuilder,
    ///
    pub signer: Option<Keypair>,
    is_liquidator: bool,
}
```

I also have a copy of the target folder. It's 64 GB. I can still reproduce the error.

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve +A-incr-comp

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
