### ISSUE TITLE
nightly 1.66 x86_64-unknown-linux-gnu compiler error

### ISSUE THREAD

**Issue by Visic** [rust-lang/rust#102705]
Note: Switching back to 1.65 compiles fine

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (01af5040f 2022-10-04)
binary: rustc
commit-hash: 01af5040fdada6ef8f1b749cda798d80a8590b2c
commit-date: 2022-10-04
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Error output

```
error: internal compiler error: no warnings or errors encountered even though `delayed_good_path_bugs` issued

error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: <rustc_errors::Handler>::delay_good_path_bug::<&str>
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::ArenaCache<(), std::collections::hash::map::HashMap<rustc_span::def_id::DefId, rustc_span::symbol::Symbol, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>>>
             3: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
             4: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             5: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             6: <rustc_middle::ty::print::pretty::TraitPredPrintModifiersAndPath as rustc_middle::ty::print::Print<rustc_middle::ty::print::pretty::FmtPrinter>>::print
             7: <rustc_middle::ty::print::pretty::TraitPredPrintModifiersAndPath as core::fmt::Display>::fmt
             8: core::fmt::write
                       at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/core/src/fmt/mod.rs:1209:17
             9: core::fmt::Write::write_fmt
                       at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/core/src/fmt/mod.rs:192:9
            10: alloc::fmt::format::format_inner
                       at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/fmt.rs:612:9
            11: <rustc_infer::infer::InferCtxtBuilder>::enter::<(), <rustc_lint::opaque_hidden_inferred_bound::OpaqueHiddenInferredBound as rustc_lint::passes::LateLintPass>::check_item::{closure#0}>
            12: <rustc_lint::BuiltinCombinedModuleLateLintPass as rustc_lint::passes::LateLintPass>::check_item
            13: <rustc_lint::late::LateContextAndPass<rustc_lint::BuiltinCombinedModuleLateLintPass> as rustc_hir::intravisit::Visitor>::visit_nested_item
            14: <rustc_lint::late::LateContextAndPass<rustc_lint::BuiltinCombinedModuleLateLintPass> as rustc_hir::intravisit::Visitor>::visit_ty
            15: rustc_hir::intravisit::walk_fn::<rustc_lint::late::LateContextAndPass<rustc_lint::BuiltinCombinedModuleLateLintPass>>
            16: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::BuiltinCombinedModuleLateLintPass>>
            17: rustc_hir::intravisit::walk_mod::<rustc_lint::late::LateContextAndPass<rustc_lint::BuiltinCombinedModuleLateLintPass>>
            18: rustc_lint::late::late_lint_mod::<rustc_lint::BuiltinCombinedModuleLateLintPass>
            19: rustc_lint::lint_mod
            20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
            21: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::lint_mod, rustc_query_impl::plumbing::QueryCtxt>
            22: rustc_data_structures::sync::join::<rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}, rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}, (), ()>
            23: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
            24: <core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#5}::{closure#1}> as core::ops::function::FnOnce<()>>::call_once
            25: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}>
            26: rustc_interface::passes::analysis
            27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
            28: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            29: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            30: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
            31: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            32: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
            33: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1938:9
            35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1938:9
            36: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys/unix/thread.rs:108:17
            37: start_thread
                       at ./nptl/./nptl/pthread_create.c:442:8
            38: clone3
                       at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
          

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1536:13
stack backtrace:
   0:     0x7f6365050450 - std::backtrace_rs::backtrace::libunwind::trace::h0940e595a024cae9
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f6365050450 - std::backtrace_rs::backtrace::trace_unsynchronized::h105f21b55a45a169
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6365050450 - std::sys_common::backtrace::_print_fmt::h3a2ed111c2bd9337
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f6365050450 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9029dd42bc5e75b6
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f63650ab21e - core::fmt::write::he3e1f91c10d6c224
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f6365040fd5 - std::io::Write::write_fmt::he1f986100980651d
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/io/mod.rs:1679:15
   6:     0x7f63650531f3 - std::sys_common::backtrace::_print::h26c5f0fe9d048f5c
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f63650531f3 - std::sys_common::backtrace::print::h9d099d945c0c1b8a
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f63650531f3 - std::panicking::default_hook::{{closure}}::h56372a8ac9698e26
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:267:22
   9:     0x7f6365052eca - std::panicking::default_hook::h73cceb7588e9295f
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:286:9
  10:     0x7f6363a8d801 - <rustc_driver[d216f18393925def]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[f28c5c09f5a57553]::ops::function::FnOnce<(&core[f28c5c09f5a57553]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f6365053a2b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0f73c471a795acd8
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1952:9
  12:     0x7f6365053a2b - std::panicking::rust_panic_with_hook::hf37833f4792b3823
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/panicking.rs:673:13
  13:     0x7f6364bad7f1 - std[69fb72ec8d4ef55]::panicking::begin_panic::<rustc_errors[b49a65fbc2f1496c]::ExplicitBug>::{closure#0}
  14:     0x7f6364babe06 - std[69fb72ec8d4ef55]::sys_common::backtrace::__rust_end_short_backtrace::<std[69fb72ec8d4ef55]::panicking::begin_panic<rustc_errors[b49a65fbc2f1496c]::ExplicitBug>::{closure#0}, !>
  15:     0x7f6364ba5e26 - std[69fb72ec8d4ef55]::panicking::begin_panic::<rustc_errors[b49a65fbc2f1496c]::ExplicitBug>
  16:     0x7f6364ba8636 - std[69fb72ec8d4ef55]::panic::panic_any::<rustc_errors[b49a65fbc2f1496c]::ExplicitBug>
  17:     0x7f6363576453 - <rustc_errors[b49a65fbc2f1496c]::HandlerInner as core[f28c5c09f5a57553]::ops::drop::Drop>::drop
  18:     0x7f636276f428 - core[f28c5c09f5a57553]::ptr::drop_in_place::<rustc_session[cacedf3acd9600ce]::parse::ParseSess>
  19:     0x7f6362765208 - <alloc[5d0ace609dc05d4e]::rc::Rc<rustc_session[cacedf3acd9600ce]::session::Session> as core[f28c5c09f5a57553]::ops::drop::Drop>::drop
  20:     0x7f636276217d - core[f28c5c09f5a57553]::ptr::drop_in_place::<rustc_interface[d1ba96d6460e1c37]::interface::Compiler>
  21:     0x7f636275f88a - rustc_interface[d1ba96d6460e1c37]::interface::create_compiler_and_run::<core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>, rustc_driver[d216f18393925def]::run_compiler::{closure#1}>
  22:     0x7f636275dd52 - <scoped_tls[b12dded96dfafbb1]::ScopedKey<rustc_span[b945e457c1c57e62]::SessionGlobals>>::set::<rustc_interface[d1ba96d6460e1c37]::interface::run_compiler<core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>, rustc_driver[d216f18393925def]::run_compiler::{closure#1}>::{closure#0}, core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>>
  23:     0x7f636275da3f - std[69fb72ec8d4ef55]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d1ba96d6460e1c37]::util::run_in_thread_pool_with_globals<rustc_interface[d1ba96d6460e1c37]::interface::run_compiler<core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>, rustc_driver[d216f18393925def]::run_compiler::{closure#1}>::{closure#0}, core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>>::{closure#0}, core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>>
  24:     0x7f63638a4890 - <<std[69fb72ec8d4ef55]::thread::Builder>::spawn_unchecked_<rustc_interface[d1ba96d6460e1c37]::util::run_in_thread_pool_with_globals<rustc_interface[d1ba96d6460e1c37]::interface::run_compiler<core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>, rustc_driver[d216f18393925def]::run_compiler::{closure#1}>::{closure#0}, core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>>::{closure#0}, core[f28c5c09f5a57553]::result::Result<(), rustc_errors[b49a65fbc2f1496c]::ErrorGuaranteed>>::{closure#1} as core[f28c5c09f5a57553]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7f636505d503 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc84bda482f2a673d
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1938:9
  26:     0x7f636505d503 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc8d281b5c9b3d170
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/alloc/src/boxed.rs:1938:9
  27:     0x7f636505d503 - std::sys::unix::thread::Thread::new::thread_start::he8c81c74d5c82445
                               at /rustc/01af5040fdada6ef8f1b749cda798d80a8590b2c/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f6360e94b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  29:     0x7f6360f26a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (01af5040f 2022-10-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```
</p>
</details>

**Comment by Visic** [comment]
Oddly enough, I can no longer reproduce this issue.
In the hopes that any of this helps, the steps I went through this morning were..

1. Clean the project and update dependencies (Although I might have stopped the update prematurely)
2. Realize I should update to the latest nightly, so go ahead and update to 1.66
3. clean, update, and build (run into this issue)
5. set the rust_backtrace and build (reproduced this issue)
7. Switch to 1.65 nightly
8. clean, update, build (build succeeds)
9. do some minor work/testing (no significant code changes)
10. switch back to 1.66 to try and help make a mcve
11. clean, update, build (build succeeds)

Likely unrelated, but at some point this morning I did do some linux updates (pop-os), I doubt that has any bearing on this, but I can't think of anything else unusual to include.

If I run into this problem again I'll try to add more information.

**Comment by compiler-errors** [comment]
I caused this. Let me put up a fix.
