### ISSUE TITLE
compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no

### ISSUE THREAD

**Issue by expeluo** [rust-lang/rust#102959]
### Code

```Rust
Compiling massa_signature v0.1.0 (/home/massa/massa/massa-signature)
thread 'rustc' panicked at 'unexpected unresolved segments', /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/compiler/rustc_hir/src/def.rs:475:9
stack backtrace:
   0:     0x7f53ddc7d5b0 - std::backtrace_rs::backtrace::libunwind::trace::h0bf6f02637fe6971
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f53ddc7d5b0 - std::backtrace_rs::backtrace::trace_unsynchronized::hca573de4ebdee142
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f53ddc7d5b0 - std::sys_common::backtrace::_print_fmt::h78a3b0f3fa5431ce
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f53ddc7d5b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h388012888db78658
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f53ddcd959e - core::fmt::write::h8541eee12bfb22e1
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f53ddc6d835 - std::io::Write::write_fmt::haf5892ef07750179
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/io/mod.rs:1680:15
   6:     0x7f53ddc80353 - std::sys_common::backtrace::_print::hd2a58ab324867b58
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f53ddc80353 - std::sys_common::backtrace::print::h62650e0a0854a421
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f53ddc80353 - std::panicking::default_hook::{{closure}}::h0c0249b3670af819
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:267:22
   9:     0x7f53ddc8002a - std::panicking::default_hook::hdd3bdd204a1e5f34
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:286:9
  10:     0x7f53e05bc641 - rustc_driver[1f63e0707e3aafaf]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f53ddc80b8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f493fd9c4eb244a
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1952:9
  12:     0x7f53ddc80b8b - std::panicking::rust_panic_with_hook::hcdeb5a66936a633b
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:673:13
  13:     0x7f53ddc809e7 - std::panicking::begin_panic_handler::{{closure}}::h76d64f438650eafd
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:560:13
  14:     0x7f53ddc7da5c - std::sys_common::backtrace::__rust_end_short_backtrace::h6159ba2d4e07f4de
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x7f53ddc80702 - rust_begin_unwind
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:556:5
  16:     0x7f53ddcd6173 - core::panicking::panic_fmt::h811742b56cf0125a
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:142:14
  17:     0x7f53ddcd6031 - core::panicking::panic_display::h6303aa0d1e0b1fa9
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:72:5
  18:     0x7f53ddcd5fdb - core::panicking::panic_str::hbb50b0306ce7b150
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:56:5
  19:     0x7f53ddcd5d16 - core::option::expect_failed::h4c43dc39e1c41a00
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/option.rs:1876:5
  20:     0x7f53df2a3199 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor as rustc_ast[10d65a8be6722286]::visit::Visitor>::visit_fn
  21:     0x7f53df293736 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
  22:     0x7f53df29f0a6 - rustc_ast[10d65a8be6722286]::visit::walk_item::<rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>
  23:     0x7f53df28e6a1 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
  24:     0x7f53df29f0a6 - rustc_ast[10d65a8be6722286]::visit::walk_item::<rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>
  25:     0x7f53df28e6a1 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
  26:     0x7f53df28b1ea - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor as rustc_ast[10d65a8be6722286]::visit::Visitor>::visit_item
  27:     0x7f53df28b016 - <rustc_resolve[290e47d8627a4365]::Resolver>::late_resolve_crate
  28:     0x7f53df28a92a - <rustc_session[8b98ba4aacc9d309]::session::Session>::time::<(), <rustc_resolve[290e47d8627a4365]::Resolver>::resolve_crate::{closure#0}>
  29:     0x7f53df2888c3 - <rustc_interface[cf2fa28a67e8bef]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[cf2fa28a67e8bef]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[fae631be8e3c81b5]::result::Result<rustc_ast[10d65a8be6722286]::ast::Crate, rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  30:     0x7f53df273688 - <rustc_interface[cf2fa28a67e8bef]::queries::Queries>::expansion
  31:     0x7f53df27139c - <rustc_interface[cf2fa28a67e8bef]::interface::Compiler>::enter::<rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}::{closure#2}, core[fae631be8e3c81b5]::result::Result<core[fae631be8e3c81b5]::option::Option<rustc_interface[cf2fa28a67e8bef]::queries::Linker>, rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  32:     0x7f53df26c43c - rustc_span[ddec628aeed15f05]::with_source_map::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#1}>
  33:     0x7f53df26be3f - rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>
  34:     0x7f53df26b032 - <scoped_tls[4da31d6f3f5146b7]::ScopedKey<rustc_span[ddec628aeed15f05]::SessionGlobals>>::set::<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  35:     0x7f53df26a50f - std[7bd0f41fe60b70b6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  36:     0x7f53df26a37f - <<std[7bd0f41fe60b70b6]::thread::Builder>::spawn_unchecked_<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#1} as core[fae631be8e3c81b5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f53ddc8a793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc67cb2c032770d7f
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
  38:     0x7f53ddc8a793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he79e59a805a8533c
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
  39:     0x7f53ddc8a793 - std::sys::unix::thread::Thread::new::thread_start::hae509166483801f9
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f53ddb59609 - start_thread
  41:     0x7f53dda7c133 - clone
  42:                0x0 - <unknown>

```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by TaKO8Ki** [comment]
I think this is related to https://github.com/rust-lang/rust/issues/102946.
