### ISSUE TITLE
Nightly rustdoc ICE: `panicked at 'assertion failed: eps.array_windows().all(|[a, b]|\n        a.skip_binder().stable_cmp(self, &b.skip_binder()) !=\n `

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#102973]
### Error output

Whole output available at https://github.com/fedimint/fedimint/actions/runs/3233716428/jobs/5295926737

Just started happening in our CI on the one flow that doesn't have Rust locked via Nix, so I guess it must have just got introduced.

Please excuse very little information. I just want to report it timely, and I have move on to some other stuff for now.

```
thread 'rustc' panicked at 'assertion failed: eps.array_windows().all(|[a, b]|\n        a.skip_binder().stable_cmp(self, &b.skip_binder()) !=\n            Ordering::Greater)', compiler/rustc_middle/src/ty/context.rs:2684:9
stack backtrace:
   0:     0x7feec6b1d5b0 - std::backtrace_rs::backtrace::libunwind::trace::h0bf6f02637fe6971
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7feec6b1d5b0 - std::backtrace_rs::backtrace::trace_unsynchronized::hca573de4ebdee142
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7feec6b1d5b0 - std::sys_common::backtrace::_print_fmt::h78a3b0f3fa5431ce
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7feec6b1d5b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h388012888db78658
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7feec6b7959e - core::fmt::write::h8541eee12bfb22e1
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/fmt/mod.rs:1209:17
   5:     0x7feec6b0d835 - std::io::Write::write_fmt::haf5892ef07750179
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/io/mod.rs:1680:15
   6:     0x7feec6b20353 - std::sys_common::backtrace::_print::hd2a58ab324867b58
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7feec6b20353 - std::sys_common::backtrace::print::h62650e0a0854a421
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7feec6b20353 - std::panicking::default_hook::{{closure}}::h0c0249b3670af819
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:267:22
   9:     0x7feec6b2002a - std::panicking::default_hook::hdd3bdd204a1e5f34
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:286:9
  10:     0x7feec945c641 - rustc_driver[1f63e0707e3aafaf]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7feec6b20b8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f493fd9c4eb244a
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1952:9
  12:     0x7feec6b20b8b - std::panicking::rust_panic_with_hook::hcdeb5a66936a633b
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:673:13
  13:     0x7feec6b209a1 - std::panicking::begin_panic_handler::{{closure}}::h76d64f438650eafd
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:558:13
  14:     0x7feec6b1da5c - std::sys_common::backtrace::__rust_end_short_backtrace::h6159ba2d4e07f4de
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x7feec6b20702 - rust_begin_unwind
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:556:5
  16:     0x7feec6b76173 - core::panicking::panic_fmt::h811742b56cf0125a
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:142:14
  17:     0x7feec6b75fbd - core::panicking::panic::h272e8f4d1768c9aa
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:48:5
  18:     0x7feec85ae421 - <rustc_middle[a8ed4a0dc47aac3]::ty::context::TyCtxt>::intern_poly_existential_predicates
  19:     0x7feec8ed9585 - <rustc_middle[a8ed4a0dc47aac3]::ty::sty::Binder<rustc_middle[a8ed4a0dc47aac3]::ty::sty::ExistentialPredicate> as rustc_type_ir[967bf0ae5825f37d]::InternIteratorElement<rustc_middle[a8ed4a0dc47aac3]::ty::sty::Binder<rustc_middle[a8ed4a0dc47aac3]::ty::sty::ExistentialPredicate>, &rustc_middle[a8ed4a0dc47aac3]::ty::list::List<rustc_middle[a8ed4a0dc47aac3]::ty::sty::Binder<rustc_middle[a8ed4a0dc47aac3]::ty::sty::ExistentialPredicate>>>>::intern_with::<core[fae631be8e3c81b5]::iter::adapters::chain::Chain<core[fae631be8e3c81b5]::iter::sources::once::Once<rustc_middle[a8ed4a0dc47aac3]::ty::sty::Binder<rustc_middle[a8ed4a0dc47aac3]::ty::sty::ExistentialPredicate>>, core[fae631be8e3c81b5]::iter::adapters::filter_map::FilterMap<rustc_infer[47b922782ea47410]::traits::util::Elaborator, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_ty_for_trait::{closure#0}::{closure#1}>>, <rustc_middle[a8ed4a0dc47aac3]::ty::context::TyCtxt>::mk_poly_existential_predicates<core[fae631be8e3c81b5]::iter::adapters::chain::Chain<core[fae631be8e3c81b5]::iter::sources::once::Once<rustc_middle[a8ed4a0dc47aac3]::ty::sty::Binder<rustc_middle[a8ed4a0dc47aac3]::ty::sty::ExistentialPredicate>>, core[fae631be8e3c81b5]::iter::adapters::filter_map::FilterMap<rustc_infer[47b922782ea47410]::traits::util::Elaborator, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_ty_for_trait::{closure#0}::{closure#1}>>>::{closure#0}>
  20:     0x7feec8f6ed65 - rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::virtual_call_violation_for_method
  21:     0x7feec90e9ac8 - rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violation_for_method
  22:     0x7feec90e9973 - <core[fae631be8e3c81b5]::iter::adapters::map::Map<core[fae631be8e3c81b5]::iter::adapters::map::Map<core[fae631be8e3c81b5]::slice::iter::Iter<(rustc_span[ddec628aeed15f05]::symbol::Symbol, &rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItem)>, <rustc_data_structures[fec937313883fa6d]::sorted_map::index_map::SortedIndexMultiMap<u32, rustc_span[ddec628aeed15f05]::symbol::Symbol, &rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItem>>::iter::{closure#0}>, <rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItems>::in_definition_order::{closure#0}> as core[fae631be8e3c81b5]::iter::traits::iterator::Iterator>::try_fold::<(), core[fae631be8e3c81b5]::iter::adapters::filter::filter_try_fold<&rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItem, (), core[fae631be8e3c81b5]::ops::control_flow::ControlFlow<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations_for_trait::{closure#0}, core[fae631be8e3c81b5]::iter::adapters::filter_map::filter_map_try_fold<&rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItem, rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation, (), core[fae631be8e3c81b5]::ops::control_flow::ControlFlow<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations_for_trait::{closure#1}, core[fae631be8e3c81b5]::iter::traits::iterator::Iterator::find::check<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation, &mut rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations_for_trait::{closure#2}>::{closure#0}>::{closure#0}>::{closure#0}, core[fae631be8e3c81b5]::ops::control_flow::ControlFlow<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation>>
  23:     0x7feec90e9735 - <alloc[9f2f41052ee9385c]::vec::Vec<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation> as alloc[9f2f41052ee9385c]::vec::spec_from_iter::SpecFromIter<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation, core[fae631be8e3c81b5]::iter::adapters::filter::Filter<core[fae631be8e3c81b5]::iter::adapters::filter_map::FilterMap<core[fae631be8e3c81b5]::iter::adapters::filter::Filter<core[fae631be8e3c81b5]::iter::adapters::map::Map<core[fae631be8e3c81b5]::iter::adapters::map::Map<core[fae631be8e3c81b5]::slice::iter::Iter<(rustc_span[ddec628aeed15f05]::symbol::Symbol, &rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItem)>, <rustc_data_structures[fec937313883fa6d]::sorted_map::index_map::SortedIndexMultiMap<u32, rustc_span[ddec628aeed15f05]::symbol::Symbol, &rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItem>>::iter::{closure#0}>, <rustc_middle[a8ed4a0dc47aac3]::ty::assoc::AssocItems>::in_definition_order::{closure#0}>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations_for_trait::{closure#0}>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations_for_trait::{closure#1}>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations_for_trait::{closure#2}>>>::from_iter
  24:     0x7feec90e8961 - <&mut rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations::{closure#0} as core[fae631be8e3c81b5]::ops::function::FnOnce<(rustc_span[ddec628aeed15f05]::def_id::DefId,)>>::call_once
  25:     0x7feec90e858e - <core[fae631be8e3c81b5]::iter::adapters::flatten::FlatMap<rustc_trait_selection[a031dbb00953ed73]::traits::util::SupertraitDefIds, alloc[9f2f41052ee9385c]::vec::Vec<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations::{closure#0}> as core[fae631be8e3c81b5]::iter::traits::iterator::Iterator>::next
  26:     0x7feec90e7fcc - <smallvec[3f8234bbec1b645]::SmallVec<[rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation; 8usize]> as core[fae631be8e3c81b5]::iter::traits::collect::Extend<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation>>::extend::<core[fae631be8e3c81b5]::iter::adapters::flatten::FlatMap<rustc_trait_selection[a031dbb00953ed73]::traits::util::SupertraitDefIds, alloc[9f2f41052ee9385c]::vec::Vec<rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation>, rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations::{closure#0}>>
  27:     0x7feec90e7d51 - rustc_trait_selection[a031dbb00953ed73]::traits::object_safety::object_safety_violations
  28:     0x7feec91dbba0 - rustc_query_system[a76597d842537d9]::query::plumbing::try_execute_query::<rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt, rustc_query_system[a76597d842537d9]::query::caches::DefaultCache<rustc_span[ddec628aeed15f05]::def_id::DefId, &[rustc_middle[a8ed4a0dc47aac3]::traits::ObjectSafetyViolation]>>
  29:     0x7feec91db806 - rustc_query_system[a76597d842537d9]::query::plumbing::get_query::<rustc_query_impl[1e7ed5a7eb258aab]::queries::object_safety_violations, rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt>
  30:     0x7feec8097f62 - <rustc_middle[a8ed4a0dc47aac3]::ty::context::TyCtxt>::is_object_safe
  31:     0x7feec8086cb5 - <rustc_trait_selection[a031dbb00953ed73]::traits::fulfill::FulfillProcessor as rustc_data_structures[fec937313883fa6d]::obligation_forest::ObligationProcessor>::process_obligation
  32:     0x7feec807fdf9 - <rustc_data_structures[fec937313883fa6d]::obligation_forest::ObligationForest<rustc_trait_selection[a031dbb00953ed73]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[a031dbb00953ed73]::traits::fulfill::FulfillProcessor>
  33:     0x7feec87ba59f - <rustc_trait_selection[a031dbb00953ed73]::traits::engine::ObligationCtxt>::select_all_or_error
  34:     0x7feec8bc9b9e - rustc_hir_analysis[a6a5d63f9823a7da]::check::wfcheck::check_associated_item
  35:     0x7feec8bc1070 - rustc_hir_analysis[a6a5d63f9823a7da]::check::wfcheck::check_well_formed
  36:     0x7feec8412ce5 - rustc_query_system[a76597d842537d9]::query::plumbing::get_query::<rustc_query_impl[1e7ed5a7eb258aab]::queries::check_well_formed, rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt>
  37:     0x7feec8edf6af - rustc_data_structures[fec937313883fa6d]::sync::par_for_each_in::<&[rustc_hir[b10a2ea55ce97d34]::hir::ImplItemId], <rustc_middle[a8ed4a0dc47aac3]::hir::ModuleItems>::par_impl_items<rustc_hir_analysis[a6a5d63f9823a7da]::check::wfcheck::check_mod_type_wf::{closure#1}>::{closure#0}>
  38:     0x7feec92a3569 - rustc_hir_analysis[a6a5d63f9823a7da]::check::wfcheck::check_mod_type_wf
  39:     0x7feec8b32b95 - rustc_query_system[a76597d842537d9]::query::plumbing::try_execute_query::<rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt, rustc_query_system[a76597d842537d9]::query::caches::DefaultCache<rustc_span[ddec628aeed15f05]::def_id::LocalDefId, ()>>
  40:     0x7feec8e8a139 - rustc_query_system[a76597d842537d9]::query::plumbing::get_query::<rustc_query_impl[1e7ed5a7eb258aab]::queries::check_mod_type_wf, rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt>
  41:     0x7feec8e553e8 - rustc_data_structures[fec937313883fa6d]::sync::par_for_each_in::<&[rustc_hir[b10a2ea55ce97d34]::hir_id::OwnerId], <rustc_middle[a8ed4a0dc47aac3]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[a6a5d63f9823a7da]::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>
  42:     0x7feec8e551f3 - <rustc_session[8b98ba4aacc9d309]::session::Session>::track_errors::<rustc_hir_analysis[a6a5d63f9823a7da]::check_crate::{closure#5}, ()>
  43:     0x7feec8e54320 - rustc_hir_analysis[a6a5d63f9823a7da]::check_crate
  44:     0x7feec8e53ea7 - rustc_interface[cf2fa28a67e8bef]::passes::analysis
  45:     0x7feec91e69e4 - rustc_query_system[a76597d842537d9]::query::plumbing::try_execute_query::<rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt, rustc_query_system[a76597d842537d9]::query::caches::DefaultCache<(), core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>>
  46:     0x7feec91e6717 - rustc_query_system[a76597d842537d9]::query::plumbing::get_query::<rustc_query_impl[1e7ed5a7eb258aab]::queries::analysis, rustc_query_impl[1e7ed5a7eb258aab]::plumbing::QueryCtxt>
  47:     0x7feec8115044 - <rustc_interface[cf2fa28a67e8bef]::passes::QueryContext>::enter::<rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  48:     0x7feec8111496 - <rustc_interface[cf2fa28a67e8bef]::interface::Compiler>::enter::<rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}::{closure#2}, core[fae631be8e3c81b5]::result::Result<core[fae631be8e3c81b5]::option::Option<rustc_interface[cf2fa28a67e8bef]::queries::Linker>, rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  49:     0x7feec810c43c - rustc_span[ddec628aeed15f05]::with_source_map::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#1}>
  50:     0x7feec810be3f - rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>
  51:     0x7feec810b032 - <scoped_tls[4da31d6f3f5146b7]::ScopedKey<rustc_span[ddec628aeed15f05]::SessionGlobals>>::set::<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  52:     0x7feec810a50f - std[7bd0f41fe60b70b6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  53:     0x7feec810a37f - <<std[7bd0f41fe60b70b6]::thread::Builder>::spawn_unchecked_<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#1} as core[fae631be8e3c81b5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:     0x7feec6b2a793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc67cb2c032770d7f
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
  55:     0x7feec6b2a793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he79e59a805a8533c
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
  56:     0x7feec6b2a793 - std::sys::unix::thread::Thread::new::thread_start::hae509166483801f9
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys/unix/thread.rs:108:17
  57:     0x7feec687ab43 - <unknown>
  58:     0x7feec690ca00 - <unknown>
  59:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (db0597f56 2022-10-11) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C linker=clang -C link-arg=-fuse-ld=mold

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [object_safety_violations] determine object safety of trait `net::framed::FramedTransport`
#1 [check_well_formed] checking that `net::connect::<impl at fedimint-server/src/net/connect.rs:154:1: 154:41>::connect_framed` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in module `net::connect`
#3 [analysis] running analysis passes on this crate
end of query stack
warning: unclosed HTML tag `address-type`
   --> client/client-lib/src/lib.rs:292:67
    |
292 |     /// The name is derived from Bitcoin's terminology of "pay to <address-type>".
    |                                                                   ^^^^^^^^^^^^^^
    |
    = note: `#[warn(rustdoc::invalid_html_tags)]` on by default

error: could not compile `fedimint-server`
warning: build failed, waiting for other jobs to finish...
warning: `mint-client` (lib doc) generated 1 warning
```

**Comment by matthiaskrgr** [comment]
probably duplicate of https://github.com/rust-lang/rust/issues/102933

**Comment by compiler-errors** [comment]
Yup it's a duplicate.

**Comment by dpc** [comment]
Closing then.
