### ISSUE TITLE
Nightly ICE during build of `rkyv`

### ISSUE THREAD

**Issue by fu5ha** [rust-lang/rust#102978]
### Code

Unfortunately I don't have a minimal repro. ~~See the changes listed in this commit: https://github.com/rkyv/rkyv/pull/319/commits/8e558b3e3f4550c54b5eabd49a891c46c85be740~~

Not caused by the above changes, it seems just compiling `rkyv` with latest nightly ICEs identically. I'll try to bisect which nightly it first fails on...

Full failing job output here https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (db0597f56 2022-10-11)
binary: rustc
commit-hash: db0597f5619d5ed93feca28e61226d3581cc7867
commit-date: 2022-10-11
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

It compiles fine on my computer which is not on nightly:
```
➜  rkyv git:(relptr-from-raw-parts) rustc --version --verbose
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: aarch64-apple-darwin
release: 1.63.0
LLVM version: 14.0.5
```

### Error output

```
thread 'rustc' panicked at 'unexpected unresolved segments', /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/compiler/rustc_hir/src/def.rs:475:9
...
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (db0597f56 2022-10-11) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rkyv`

Caused by:
  process didn't exit successfully: `rustc --crate-name rkyv --edition=2018 rkyv/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="bytecheck"' --cfg 'feature="default"' --cfg 'feature="hashbrown"' --cfg 'feature="rend"' --cfg 'feature="size_32"' --cfg 'feature="std"' --cfg 'feature="validation"' -C metadata=6083e43e48ddcc38 -C extra-filename=-6083e43e48ddcc38 --out-dir /home/runner/work/rkyv/rkyv/target/debug/deps -L dependency=/home/runner/work/rkyv/rkyv/target/debug/deps --extern bytecheck=/home/runner/work/rkyv/rkyv/target/debug/deps/libbytecheck-d7c830c75cd9ce4e.rmeta --extern hashbrown=/home/runner/work/rkyv/rkyv/target/debug/deps/libhashbrown-ba069aef4711cd2b.rmeta --extern ptr_meta=/home/runner/work/rkyv/rkyv/target/debug/deps/libptr_meta-035d3af8c9bd90ec.rmeta --extern rend=/home/runner/work/rkyv/rkyv/target/debug/deps/librend-81254a0eac94b69a.rmeta --extern rkyv_derive=/home/runner/work/rkyv/rkyv/target/debug/deps/librkyv_derive-abdc556d2c2df1e9.so --extern seahash=/home/runner/work/rkyv/rkyv/target/debug/deps/libseahash-c28b18ad[170](https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316#step:4:171)5ad1d.rmeta --cfg has_atomics_64 --cfg has_atomics` (exit status: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f51b52f35b0 - std::backtrace_rs::backtrace::libunwind::trace::h0bf6f02637fe6971
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f51b52f35b0 - std::backtrace_rs::backtrace::trace_unsynchronized::hca573de4ebdee142
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f51b52f35b0 - std::sys_common::backtrace::_print_fmt::h78a3b0f3fa5431ce
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f51b52f35b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h388012888db78658
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f51b534f59e - core::fmt::write::h8541eee12bfb22e1
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/fmt/mod.rs:1209:17
   5:     0x7f51b52e3835 - std::io::Write::write_fmt::haf5892ef07750179
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/io/mod.rs:1680:15
   6:     0x7f51b52f6353 - std::sys_common::backtrace::_print::hd2a58ab324867b58
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f51b52f6353 - std::sys_common::backtrace::print::h62650e0a0854a421
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f51b52f6353 - std::panicking::default_hook::{{closure}}::h0c0249b3670af819
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:267:22
   9:     0x7f51b52f602a - std::panicking::default_hook::hdd3bdd204a1e5f34
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:286:9
  10:     0x7f51b7c32641 - rustc_driver[1f63e0707e3aafaf]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f51b52f6b8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f493fd9c4eb244a
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1952:9
  12:     0x7f51b52f6b8b - std::panicking::rust_panic_with_hook::hcdeb5a66936a633b
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:673:13
  13:     0x7f51b52f69e7 - std::panicking::begin_panic_handler::{{closure}}::h76d64f438650eafd
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:560:13
  14:     0x7f51b52f3a5c - std::sys_common::backtrace::__rust_end_short_backtrace::h6159ba2d4e07f4de
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:138:18
  15:     0x7f51b52f6702 - rust_begin_unwind
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:556:5
  16:     0x7f51b534c173 - core::panicking::panic_fmt::h811742b56cf0125a
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:142:14
  17:     0x7f51b534c031 - core::panicking::panic_display::h6303aa0d1e0b1fa9
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:72:5
  18:     0x7f51b534bfdb - core::panicking::panic_str::hbb50b0306ce7b150
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:56:5
  19:     0x7f51b534bd16 - core::option::expect_failed::h4c43dc39e1c41a00
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/option.rs:1876:5
  20:     0x7f51b6919199 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor as rustc_ast[10d65a8be6722286]::visit::Visitor>::visit_fn
  21:     0x7f51b6909736 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
  22:     0x7f51b69150a6 - rustc_ast[10d65a8be6722286]::visit::walk_item::<rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>
  23:     0x7f51b69046a1 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
  24:     0x7f51b69150a6 - rustc_ast[10d65a8be6722286]::visit::walk_item::<rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>
  25:     0x7f51b69046a1 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
  26:     0x7f51b69011ea - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor as rustc_ast[10d65a8be6722286]::visit::Visitor>::visit_item
  27:     0x7f51b6901016 - <rustc_resolve[290e47d8627a4365]::Resolver>::late_resolve_crate
  28:     0x7f51b690092a - <rustc_session[8b98ba4aacc9d309]::session::Session>::time::<(), <rustc_resolve[290e47d8627a4365]::Resolver>::resolve_crate::{closure#0}>
  29:     0x7f51b68fe8c3 - <rustc_interface[cf2fa28a67e8bef]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[cf2fa28a67e8bef]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[fae631be8e3c81b5]::result::Result<rustc_ast[10d65a8be6722286]::ast::Crate, rustc_errors[d5334a4a25fbb3[94](https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316#step:4:95)]::ErrorGuaranteed>>
  30:     0x7f51b68e[96](https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316#step:4:97)88 - <rustc_interface[cf2fa28a67e8bef]::queries::Queries>::expansion
  31:     0x7f51b68e739c - <rustc_interface[cf2fa28a67e8bef]::interface::Compiler>::enter::<rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}::{closure#2}, core[fae631be8e3c81b5]::result::Result<core[fae631be8e3c81b5]::option::Option<rustc_interface[cf2fa28a67e8bef]::queries::Linker>, rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  32:     0x7f51b68e243c - rustc_span[ddec628aeed15f05]::with_source_map::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#1}>
  33:     0x7f51b68e1e3f - rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>
  34:     0x7f51b68e1032 - <scoped_tls[4da31d6f3f5146b7]::ScopedKey<rustc_span[ddec628aeed15f05]::SessionGlobals>>::set::<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  35:     0x7f51b68e050f - std[7bd0f41fe60b70b6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
  36:     0x7f51b68e037f - <<std[7bd0f41fe60b70b6]::thread::Builder>::spawn_unchecked_<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#1} as core[fae631be8e3c81b5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f51b5300793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc67cb2c032770d7f
                               at /rustc/db05[97](https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316#step:4:98)f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
  38:     0x7f51b5300793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he79e59a805a8533c
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
  39:     0x7f51b5300793 - std::sys::unix::thread::Thread::new::thread_start::hae509166483801f9
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys/unix/thread.rs:[108](https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316#step:4:109):17
  40:     0x7f51b51c7609 - start_thread
  41:     0x7f51b50ea[133](https://github.com/rkyv/rkyv/actions/runs/3235626058/jobs/5300317316#step:4:134) - clone
  42:                0x0 - <unknown>
```

</p>
</details>

**Comment by fu5ha** [comment]
Okay I'm failing at bisecting which nightly it fails on, but it's at least known good on nightly-2022-10-05 since that was the last time `rkyv` had a CI build on nightly, which succeeded.

**Comment by fu5ha** [comment]
Yep, looks like it!
