### ISSUE TITLE
Noisy conflicting implementations error for a trait which has a const generic parameter that panics in multiple implementations

### ISSUE THREAD

**Issue by Imberflur** [rust-lang/rust#103369]
I tried this code:

```rust
pub trait ConstGenericTrait<const N: u32> {}

impl ConstGenericTrait<{my_fn(1)}> for () {}

impl ConstGenericTrait<{my_fn(2)}> for () {}

const fn my_fn(v: u32) -> u32 {
    panic!("Some error occurred");
}
```

I expected to see this happen: 
<details>
<summary> Only errors due to the const panic being displayed</summary>

```
error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): evaluation of constant value failed
 --> src/lib.rs:8:5
  |
3 | impl ConstGenericTrait<{my_fn(1)}> for () {}
  |                         -------- inside `<() as ConstGenericTrait<{my_fn(1)}>>::{constant#0}` at src/lib.rs:3:25
...
8 |     panic!("Some error occurred");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     |
  |     the evaluated program panicked at 'Some error occurred', src/lib.rs:8:5
  |     inside `my_fn` at /rustc/dcb376115066d111dbf5f13d5ac2a2dbe8c12add/library/core/src/panic.rs:57:9
  |
  = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): evaluation of constant value failed
 --> src/lib.rs:8:5
  |
5 | impl ConstGenericTrait<{my_fn(2)}> for () {}
  |                         -------- inside `<() as ConstGenericTrait<{my_fn(2)}>>::{constant#0}` at src/lib.rs:5:25
...
8 |     panic!("Some error occurred");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     |
  |     the evaluated program panicked at 'Some error occurred', src/lib.rs:8:5
  |     inside `my_fn` at /rustc/dcb376115066d111dbf5f13d5ac2a2dbe8c12add/library/core/src/panic.rs:57:9
  |
  = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)
```

</details>

Instead, this happened: 
<details>
<summary>In addition to the expected errors there is a conflicting implementation error showing the const generic as `[const error]`</summary>

```
error[[E0119]](https://doc.rust-lang.org/nightly/error-index.html#E0119): conflicting implementations of trait `ConstGenericTrait<[const error]>` for type `()`
 --> src/lib.rs:5:1
  |
3 | impl ConstGenericTrait<{my_fn(1)}> for () {}
  | ----------------------------------------- first implementation here
4 |
5 | impl ConstGenericTrait<{my_fn(2)}> for () {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `()`
```

</details>

This introduces excessive noise in the error output when there are many implementations like this. 

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5d63f992f258ee299a5d13cfa4b0d4a1

### Meta

Present on all toolchains on the playground (at the time of posting):
![image](https://user-images.githubusercontent.com/2002109/197288016-2170fbb0-c0e6-4f4c-9620-489ce31fa01f.png)

Locally I'm using an older nightly toolchain:
`rustc --version --verbose`:
```
rustc 1.63.0-nightly (dc80ca78b 2022-06-21)
binary: rustc
commit-hash: dc80ca78b6ec2b6bba02560470347433bcd0bb3c
commit-date: 2022-06-21
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5

```

**Comment by Imberflur** [comment]
I meant to use the Diagnostic issue template but I guess I clicked on the wrong one...

**Comment by Rageking8** [comment]
> I meant to use the Diagnostic issue template but I guess I clicked on the wrong one...

No worries.
@rustbot label +T-compiler +A-diagnostics -C-bug

**Comment by Imberflur** [comment]
Update, if the first const evaluation is successful it still reports a conflicting implementation error but reports in the first successful value in the error ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d1f1cb96bb96cf75940c38dd8ee88c26)):
```rs
pub trait ConstGenericTrait<const N: u32> {}

impl ConstGenericTrait<{my_fn(3)}> for () {}

impl ConstGenericTrait<{my_fn(1)}> for () {}

impl ConstGenericTrait<{my_fn(2)}> for () {}

const fn my_fn(v: u32) -> u32 {
    if v == 2 { 
        panic!("Some error occurred")
    } else {
        v
    }
}
```
```
error[[E0080]](https://doc.rust-lang.org/stable/error_codes/E0080.html): evaluation of constant value failed
  --> src/lib.rs:11:9
   |
11 |         panic!("Some error occurred")
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Some error occurred', src/lib.rs:11:9
   |
note: inside `my_fn`
  --> src/lib.rs:11:9
   |
11 |         panic!("Some error occurred")
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `<() as ConstGenericTrait<{my_fn(2)}>>::{constant#0}`
  --> src/lib.rs:7:25
   |
7  | impl ConstGenericTrait<{my_fn(2)}> for () {}
   |                         ^^^^^^^^
   = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

error[[E0119]](https://doc.rust-lang.org/stable/error_codes/E0119.html): conflicting implementations of trait `ConstGenericTrait<3>` for type `()`
 --> src/lib.rs:7:1
  |
3 | impl ConstGenericTrait<{my_fn(3)}> for () {}
  | ----------------------------------------- first implementation here
...
7 | impl ConstGenericTrait<{my_fn(2)}> for () {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `()`
```
And if the first evaluation fails (but the others would be successful) it sees all implemenations as conflicting and shows the original `ConstGenericTrait<[const error]>` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f057b5880d90f6ab32deffe268dca05f)):
```rs
pub trait ConstGenericTrait<const N: u32> {}

impl ConstGenericTrait<{my_fn(2)}> for () {}

impl ConstGenericTrait<{my_fn(3)}> for () {}

impl ConstGenericTrait<{my_fn(1)}> for () {}

const fn my_fn(v: u32) -> u32 {
    if v == 2 { 
        panic!("Some error occurred")
    } else {
        v
    }
}
```
```
error[[E0080]](https://doc.rust-lang.org/stable/error_codes/E0080.html): evaluation of constant value failed
  --> src/lib.rs:11:9
   |
11 |         panic!("Some error occurred")
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Some error occurred', src/lib.rs:11:9
   |
note: inside `my_fn`
  --> src/lib.rs:11:9
   |
11 |         panic!("Some error occurred")
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `<() as ConstGenericTrait<{my_fn(2)}>>::{constant#0}`
  --> src/lib.rs:3:25
   |
3  | impl ConstGenericTrait<{my_fn(2)}> for () {}
   |                         ^^^^^^^^
   = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

error[[E0119]](https://doc.rust-lang.org/stable/error_codes/E0119.html): conflicting implementations of trait `ConstGenericTrait<[const error]>` for type `()`
 --> src/lib.rs:5:1
  |
3 | impl ConstGenericTrait<{my_fn(2)}> for () {}
  | ----------------------------------------- first implementation here
4 |
5 | impl ConstGenericTrait<{my_fn(3)}> for () {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `()`

error[[E0119]](https://doc.rust-lang.org/stable/error_codes/E0119.html): conflicting implementations of trait `ConstGenericTrait<[const error]>` for type `()`
 --> src/lib.rs:7:1
  |
3 | impl ConstGenericTrait<{my_fn(2)}> for () {}
  | ----------------------------------------- first implementation here
...
7 | impl ConstGenericTrait<{my_fn(1)}> for () {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `()`
```

Compiler version `1.67.1`
