### ISSUE TITLE
Failed to normalize error (need repro)

### ISSUE THREAD

**Issue by zyansheep** [rust-lang/rust#103769]
Don't have time to do a reproduction atm. I'm using a proc macro and the error seems to go away when I use it correctly. The real error is probably a result from different interactions between libraries and nightly features... Posted this here anyway to see if anyone was interested in reproducing this error.

### Code

https://github.com/libdither/disp/tree/f902691c98898b1e7b3bdccc69ad9772a5e516e9

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (9565dfeb4 2022-10-28)
binary: rustc
commit-hash: 9565dfeb4e6225177bbe78f18cd48a7982f34401
commit-date: 2022-10-28
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```
Using the following nightly features:
```rust
// Main application:
#![feature(iter_intersperse)]
#![feature(option_result_contains)]
#![feature(type_alias_impl_trait)]
#![feature(try_blocks)]
#![feature(return_position_impl_trait_in_trait)]
#![feature(generic_const_exprs)]
// hashdb library:
#![allow(incomplete_features)]
#![allow(const_evaluatable_unchecked)]
#![feature(generic_const_exprs)]
#![feature(adt_const_params)]
#![feature(const_mut_refs)]
#![feature(associated_type_bounds)]
#![feature(associated_type_defaults)]
#![feature(downcast_unchecked)]
#![feature(type_alias_impl_trait)]
#![feature(return_position_impl_trait_in_trait)]
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:198:90: Failed to normalize <&expr::Expr<'_> as rkyv::Archive>::Archived, maybe try to call `try_normalize_erasing_regions` instead
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9565dfeb4e6225177bbe78f18cd48a7982f34401/compiler/rustc_errors/src/lib.rs:1519:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>::normalize_generic_arg_after_erasing_regions
   8: <rustc_middle::ty::Ty as rustc_middle::ty::fold::TypeFoldable>::fold_with::<rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>
   9: <rustc_middle::ty::context::TyCtxt>::struct_tail_erasing_lifetimes
  10: rustc_ty_utils::layout::layout_of_uncached
  11: rustc_ty_utils::layout::layout_of
  12: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, core::result::Result<rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>, rustc_middle::ty::layout::LayoutError>>
  13: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::layout_of, rustc_query_impl::plumbing::QueryCtxt>
  14: <core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::FieldDef>, rustc_ty_utils::layout::layout_of_uncached::{closure#5}::{closure#0}>, core::result::Result<core::convert::Infallible, rustc_middle::ty::layout::LayoutError>> as core::iter::traits::iterator::Iterator>::next
  15: <alloc::vec::Vec<alloc::vec::Vec<rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>>> as alloc::vec::spec_from_iter::SpecFromIter<alloc::vec::Vec<rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>>, core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::slice::iter::Iter<rustc_middle::ty::VariantDef>, rustc_ty_utils::layout::layout_of_uncached::{closure#5}>, core::result::Result<core::convert::Infallible, rustc_middle::ty::layout::LayoutError>>>>::from_iter
  16: rustc_ty_utils::layout::layout_of_uncached
  17: rustc_ty_utils::layout::layout_of
  18: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, core::result::Result<rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>, rustc_middle::ty::layout::LayoutError>>
  19: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::layout_of, rustc_query_impl::plumbing::QueryCtxt>
  20: <rustc_mir_transform::const_prop::CanConstProp>::check
  21: <rustc_mir_transform::const_prop_lint::ConstProp as rustc_mir_transform::pass_manager::MirLint>::run_lint
  22: rustc_mir_transform::run_analysis_to_runtime_passes
  23: rustc_mir_transform::mir_drops_elaborated_and_const_checked
  24: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>>
  26: rustc_mir_transform::optimized_mir
  27: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, &rustc_middle::mir::Body>
  28: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, &rustc_middle::mir::Body>>
  29: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  30: rustc_metadata::rmeta::encoder::encode_metadata_impl
  31: rustc_data_structures::sync::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  32: rustc_metadata::rmeta::encoder::encode_metadata
  33: rustc_metadata::fs::encode_and_write_metadata
  34: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  35: <rustc_interface::queries::Queries>::ongoing_codegen
  36: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  37: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  38: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (9565dfeb4 2022-10-28) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [layout_of] computing layout of `&expr::reduce::ArchivedReduceLink<'_>`
#1 [layout_of] computing layout of `core::result::Result<&expr::reduce::ArchivedReduceLink<'_>, bytecheck::StructCheckError>`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `expr::reduce::_::<impl at src/expr/reduce.rs:126:1: 126:12>::check_bytes`
#3 [optimized_mir] optimizing MIR for `expr::reduce::_::<impl at src/expr/reduce.rs:126:1: 126:12>::check_bytes`
end of query stack
```

</p>
</details>

**Comment by SNCPlay42** [comment]
I've reduced this down as far as:

```rust
pub struct ArchivedReduceLink<'e>
where
	&'e Expr<'e>: ::rkyv::Archive,
{
	reduced: ::rkyv::Archived<&'e Expr<'e>>,
}
impl<'e> ArchivedReduceLink<'e>
where
	&'e Expr<'e>: ::rkyv::Archive,
{
	unsafe fn check_bytes<'__bytecheck, __C>(value: (), context: ()) -> Result<&'__bytecheck Self, ()> {
		unimplemented!()
	}
}
pub enum Expr<'e> {
	Lambda { bind: &'e () },
}
```

I think this is a duplicate of #94651.

@rustbot label -requires-nightly

**Comment by zyansheep** [comment]
Just tested your repro and it looks like exactly the same bug, thanks! Closing this in favor of #94651
