### ISSUE TITLE
ICE with if let chain and optimization

### ISSUE THREAD

**Issue by rgreenblatt** [rust-lang/rust#103871]
This occurs with latest nightly and `--release`

### Code

```Rust
#![feature(let_chains)]

pub fn main() {
  if let Some(_) = Some(0) && let Some(_must_have_name) = Some(vec![0]) {}
}
```

### Error output

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ temp[7c1c]::main), const_param_did: None }) (after pass PhaseChange-Runtime(Optimized)) at bb8[0]:
                                use of local _10, which has no storage here
 --> src/main.rs:4:74
  |
4 |   if let Some(_) = Some(0) && let Some(_must_have_name) = Some(vec![0]) {}
  |                                                                          ^
  |
  = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:129:36

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1496:13
stack backtrace:
   0:     0x7f52c9f6dd50 - std::backtrace_rs::backtrace::libunwind::trace::h3857ef565af39398
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f52c9f6dd50 - std::backtrace_rs::backtrace::trace_unsynchronized::hbdcd051de7f77d0f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f52c9f6dd50 - std::sys_common::backtrace::_print_fmt::h23be2adc86b0a876
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f52c9f6dd50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b060ccd6bd6b034
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f52c9fc8aae - core::fmt::write::h8c66ea5bcce6741d
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f52c9f5e865 - std::io::Write::write_fmt::h4eb4d78dd880f1b9
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/io/mod.rs:1679:15
   6:     0x7f52c9f70a03 - std::sys_common::backtrace::_print::h95ae1478fe0e51b5
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f52c9f70a03 - std::sys_common::backtrace::print::h14585209d1e15fd7
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f52c9f70a03 - std::panicking::default_hook::{{closure}}::h8113d7aba344b100
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:295:22
   9:     0x7f52c9f706ef - std::panicking::default_hook::hc8f6609e883c8b5a
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:314:9
  10:     0x7f52cc7637d1 - <rustc_driver[5d611abbc2f17d9d]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[db135c73114314af]::ops::function::FnOnce<(&core[db135c73114314af]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f52c9f7123d - std::panicking::rust_panic_with_hook::h3db30b700f89d22f
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:702:17
  12:     0x7f52cd87fc11 - std[57446eb6c28e7555]::panicking::begin_panic::<rustc_errors[8c4755de5347ab4f]::ExplicitBug>::{closure#0}
  13:     0x7f52cd87f976 - std[57446eb6c28e7555]::sys_common::backtrace::__rust_end_short_backtrace::<std[57446eb6c28e7555]::panicking::begin_panic<rustc_errors[8c4755de5347ab4f]::ExplicitBug>::{closure#0}, !>
  14:     0x7f52cd87f616 - std[57446eb6c28e7555]::panicking::begin_panic::<rustc_errors[8c4755de5347ab4f]::ExplicitBug>
  15:     0x7f52cd87cdf6 - std[57446eb6c28e7555]::panic::panic_any::<rustc_errors[8c4755de5347ab4f]::ExplicitBug>
  16:     0x7f52cc250b4b - <rustc_errors[8c4755de5347ab4f]::HandlerInner as core[db135c73114314af]::ops::drop::Drop>::drop
  17:     0x7f52cb554168 - core[db135c73114314af]::ptr::drop_in_place::<rustc_session[3445cbfd28f83aee]::parse::ParseSess>
  18:     0x7f52cb511b18 - <alloc[12cf8e0601d39fe3]::rc::Rc<rustc_session[3445cbfd28f83aee]::session::Session> as core[db135c73114314af]::ops::drop::Drop>::drop
  19:     0x7f52cb50eadd - core[db135c73114314af]::ptr::drop_in_place::<rustc_interface[2ab31e4d01a50aaf]::interface::Compiler>
  20:     0x7f52cb50c34c - rustc_interface[2ab31e4d01a50aaf]::interface::create_compiler_and_run::<core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>, rustc_driver[5d611abbc2f17d9d]::run_compiler::{closure#1}>
  21:     0x7f52cb50a842 - <scoped_tls[f9dca722f455ede3]::ScopedKey<rustc_span[a0f10a6f74d9595c]::SessionGlobals>>::set::<rustc_interface[2ab31e4d01a50aaf]::interface::run_compiler<core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>, rustc_driver[5d611abbc2f17d9d]::run_compiler::{closure#1}>::{closure#0}, core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>>
  22:     0x7f52cb50a52f - std[57446eb6c28e7555]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2ab31e4d01a50aaf]::util::run_in_thread_pool_with_globals<rustc_interface[2ab31e4d01a50aaf]::interface::run_compiler<core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>, rustc_driver[5d611abbc2f17d9d]::run_compiler::{closure#1}>::{closure#0}, core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>>::{closure#0}, core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>>
  23:     0x7f52cc5d51c0 - <<std[57446eb6c28e7555]::thread::Builder>::spawn_unchecked_<rustc_interface[2ab31e4d01a50aaf]::util::run_in_thread_pool_with_globals<rustc_interface[2ab31e4d01a50aaf]::interface::run_compiler<core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>, rustc_driver[5d611abbc2f17d9d]::run_compiler::{closure#1}>::{closure#0}, core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>>::{closure#0}, core[db135c73114314af]::result::Result<(), rustc_errors[8c4755de5347ab4f]::ErrorGuaranteed>>::{closure#1} as core[db135c73114314af]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f52c9f7b013 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h444ca4f495d8afb9
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/boxed.rs:1940:9
  25:     0x7f52c9f7b013 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h73ae8bee2b70403b
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/boxed.rs:1940:9
  26:     0x7f52c9f7b013 - std::sys::unix::thread::Thread::new::thread_start::h2dd9b6f640aa1270
                               at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f52c9d1c8fd - <unknown>
  28:     0x7f52c9d9ea60 - <unknown>
  29:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (a37499ae6 2022-09-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

```

https://rust.godbolt.org/z/Kzc98jKnM

**Comment by Lee-Janggun** [comment]
This does not ice on the most recent nightly.

https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=01ad2e671e2982b74249b40e23f8db1b 

The note suggests the nightly is at 2022-09-18. Does godbolt not update to the most recent nightly?
