### ISSUE TITLE
pip rust libc.so.6 error Centos

### ISSUE THREAD

**Issue by putout** [rust-lang/rust#104222]
``
hey
``
OS: Centos 6

installed pip success

Installed Rust manually - success
~~~
curl https://sh.rustup.rs | sh
~~~

~~~
pip install cryptography 

     /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc)
      /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc)
      /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so)
      /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libstd-05737cf45bd30456.so)
      /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libstd-05737cf45bd30456.so)
      /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so)
      /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so)
~~~

which led me to 

Followed: this for the lib.so error
https://stackoverflow.com/a/50697155

also used it as a template for lib 2.17 and 2.15, reloaded the library paths as well

~~~
export LD_LIBRARY_PATH=/opt/glibc-2.17/lib  #did the same 2.14 and 2.15

LD_LIBRARY_PATH=/opt/glibc-2.17/lib   #did the same 2.14 and 2.15
source /etc/environment   #did the same each time for 2.14 and 2.15 after i entered the above commands 

rustc
rustc: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
~~~~
If I run yum I get the same command as above, but not if I open a new SSH session.

Once I open a new SSH session yum works without that error
but **rustc** command goes back to my initial error. Even though I reloaded the Env and library.

~~~~
# rustc
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc)
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc)
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so)
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libstd-05737cf45bd30456.so)
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libstd-05737cf45bd30456.so)
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so)
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so)
~~~~

**env** output
~~~~
TERM=xterm
SHELL=/bin/bash
HISTSIZE=10000
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
SSH_TTY=/dev/pts/0
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/root
PATH=/root/.cargo/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
PWD=/root
LANG=en_US.UTF-8
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
LOGNAME=root
QTLIB=/usr/lib64/qt-3.3/lib
CVS_RSH=ssh
LESSOPEN=||/usr/bin/lesspipe.sh %s
G_BROKEN_FILENAMES=1
_=/bin/env
~~~~

installing rust via **pip install rust**
````
 pip install rust
Collecting rust
  Using cached RUST-0.1.1.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib
  Using cached matplotlib-3.6.2.tar.gz (35.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [305 lines of output]
      /usr/local/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
        error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [252 lines of output]
            Running from numpy source directory.
            setup.py:86: DeprecationWarning:

              `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
              of the deprecation of `distutils` itself. It will be removed for
              Python >= 3.12. For older Python versions it will remain present.
              It is recommended to use `setuptools < 60.0` for those Python versions.
              For more details, see:
                https://numpy.org/devdocs/reference/distutils_status_migration.html


              import numpy.distutils.command.sdist
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_generator.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/_common.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Cythonizing sources
            INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO:   libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: accelerate_info:
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_3_10_blas_threads_info:
            INFO: Setting PTATLAS=ATLAS
            INFO:   libraries tatlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/atlas', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_3_10_blas_info:
            INFO:   libraries satlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/atlas', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_blas_threads_info:
            INFO: Setting PTATLAS=ATLAS
            INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/atlas', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_blas_info:
            INFO:   libraries f77blas,cblas,atlas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64/atlas', '/usr/lib64/sse2', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            /tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/system_info.py:2077: UserWarning:
                Optimized (vendor) Blas libraries are not found.
                Falls back to netlib Blas library which has worse performance.
                A better performance should be easily gained by switching
                Blas library.
              if self._calc_info(blas):
            INFO: blas_info:
            INFO:   libraries blas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            /tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/system_info.py:2077: UserWarning:
                Blas (http://www.netlib.org/blas/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [blas]) or by setting
                the BLAS environment variable.
              if self._calc_info(blas):
            INFO: blas_src_info:
            INFO:   NOT AVAILABLE
            INFO:
            /tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/system_info.py:2077: UserWarning:
                Blas (http://www.netlib.org/blas/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [blas_src]) or by setting
                the BLAS_SRC environment variable.
              if self._calc_info(blas):
            INFO:   NOT AVAILABLE
            INFO:
            non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:
            INFO: lapack_armpl_info:
            INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_mkl_info:
            INFO:   libraries mkl_rt not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_lapack_info:
            INFO:   libraries openblas not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_clapack_info:
            INFO:   libraries openblas,lapack not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: flame_info:
            INFO:   libraries flame not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_3_10_threads_info:
            INFO: Setting PTATLAS=ATLAS
            INFO:   libraries tatlas,tatlas not found in /usr/local/lib64
            INFO:   libraries tatlas,tatlas not found in /usr/local/lib
            INFO:   libraries tatlas,tatlas not found in /usr/lib64/atlas
            INFO:   libraries tatlas,tatlas not found in /usr/lib64/sse2
            INFO:   libraries tatlas,tatlas not found in /usr/lib64
            INFO:   libraries tatlas,tatlas not found in /usr/lib
            INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_3_10_info:
            INFO:   libraries satlas,satlas not found in /usr/local/lib64
            INFO:   libraries satlas,satlas not found in /usr/local/lib
            INFO:   libraries satlas,satlas not found in /usr/lib64/atlas
            INFO:   libraries satlas,satlas not found in /usr/lib64/sse2
            INFO:   libraries satlas,satlas not found in /usr/lib64
            INFO:   libraries satlas,satlas not found in /usr/lib
            INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_threads_info:
            INFO: Setting PTATLAS=ATLAS
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/atlas
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
            INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_info:
            INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib64
            INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
            INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64/atlas
            INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
            INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64
            INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
            INFO: <class 'numpy.distutils.system_info.atlas_info'>
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_info:
            INFO:   libraries lapack not found in ['/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            /tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/system_info.py:1902: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
            INFO: lapack_src_info:
            INFO:   NOT AVAILABLE
            INFO:
            /tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/system_info.py:1902: UserWarning:
                Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                the LAPACK_SRC environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
            INFO:   NOT AVAILABLE
            INFO:
            INFO: numpy_linalg_lapack_lite:
            INFO:   FOUND:
            INFO:     language = c
            INFO:     define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
            INFO:
            Warning: attempted relative import with no known parent package
            /tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            INFO: build_src
            INFO: building py_modules sources
            creating build
            creating build/src.linux-x86_64-3.9
            creating build/src.linux-x86_64-3.9/numpy
            creating build/src.linux-x86_64-3.9/numpy/distutils
            INFO: building library "npymath" sources
            WARN: Could not locate executable armflang
            cc1plus: error: unrecognized command line option "-std=c++11"
            Traceback (most recent call last):
              File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
                main()
              File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
                super(_BuildMetaLegacyBackend,
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 494, in <module>
                setup_package()
              File "setup.py", line 486, in setup_package
                setup(**metadata)
              File "/tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/command/build.py", line 62, in run
                old_build.run(self)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/tmp/pip-build-env-38751wlx/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/command/build_src.py", line 155, in build_sources
                self.build_library_sources(*libname_info)
              File "/tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/command/build_src.py", line 288, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/tmp/pip-wheel-01aypt6f/numpy_08a06db0fbe249348e0b9967115c6334/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 758, in get_mathlib_info
                raise RuntimeError(
            RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for C++11 language features is required.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpaez0pl2r', '--quiet', 'numpy>=1.19']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6p91igh6/matplotlib_b364f2b39009494d9fd88d7e379ca6ef/setup.py", line 260, in <module>
          setup(  # Finally, pass this all along to setuptools to do the heavy lifting.
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/usr/local/lib/python3.9/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/usr/local/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpaez0pl2r', '--quiet', 'numpy>=1.19']' returned non-zero exit status 1.

      Edit mplsetup.cfg to change the build options; suppress output with --quiet.

      BUILDING MATPLOTLIB
            python: yes [3.9.6 (default, Nov  4 2022, 01:56:04)  [GCC 4.4.7 20120313
                        (Red Hat 4.4.7-23)]]
          platform: yes [linux]
             tests: no  [skipping due to configuration]
            macosx: no  [Mac OS-X only]

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

any tips? 

My Stack post 
https://unix.stackexchange.com/questions/724191/pip-rust-libc-so-6-error-centos

**Comment by cuviper** [comment]
CentOS 6 is no longer a supported platform since Rust 1.64, as announced here:
https://blog.rust-lang.org/2022/08/01/Increasing-glibc-kernel-requirements.html

You _might_ be able to get a newer glibc working, but I wouldn't advise that, and the kernel will be harder to deal with. The safer route would be to limit yourself to 1.63.0, and you'll have to manually install that since `rustup` also updated to follow the new minimum requirements. You can find the offline installer here:

https://static.rust-lang.org/dist/rust-1.63.0-x86_64-unknown-linux-gnu.tar.gz

I can't tell you if that version will be sufficient for python cryptography though, and the Rust project only provides support for the current stable version. For that reason, I am closing this issue.
