### ISSUE TITLE
compiler panic

### ISSUE THREAD

**Issue by kontsaki** [rust-lang/rust#104423]
Hello, only happened once and I couldn't reproduce it.

### Code

```Rust
use clap::Parser;
use miette::{IntoDiagnostic, Result};
use thirtyfour::prelude::*;
use tokio::process;
use walkdir::WalkDir;
use watchexec::{
    action::Action,
    config::{InitConfig, RuntimeConfig},
    error,
    handler::PrintDebug,
    Watchexec,
};

#[derive(Parser)]
#[command(version)]
struct Cli {
    url: String,
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    let mut backend = process::Command::new("./geckodriver")
        .spawn()
        .into_diagnostic()?;

    let caps = DesiredCapabilities::firefox();
    let driver = WebDriver::new("http://localhost:4444", caps)
        .await
        .into_diagnostic()?;

    driver.goto(cli.url).await.into_diagnostic()?;

    let watcher = watch(driver.clone()).await;
    backend.kill().await.into_diagnostic()?;
    driver.quit().await.into_diagnostic()?;
    watcher?;
    Ok(())
}

async fn watch(driver: WebDriver) -> Result<()> {
    let files = WalkDir::new(".")
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file() && e.file_name().to_string_lossy().starts_with("."))
        .map(|e| e.into_path());

    let mut init = InitConfig::default();
    init.on_error(PrintDebug(std::io::stderr()));

    let mut runtime = RuntimeConfig::default();
    runtime.pathset(files);

    let refresher = driver.clone();
    runtime.on_action(move |a: Action| {
        println!("Action {a:?}");

        let refresher = refresher.clone();
        async move {
            refresher.refresh().await.unwrap();
            Ok::<(), error::RuntimeError>(())
        }
    });

    let we = Watchexec::new(init, runtime)?;
    we.main().await.into_diagnostic()?.unwrap();
    Ok(())
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

### Error output

```
thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/ffi_unwind_calls.rs:50:78
stack backtrace:
   0:     0x7fec4996dd40 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fec4996dd40 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fec4996dd40 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fec4996dd40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fec499c8bfe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x7fec4995e935 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x7fec499709f3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fec499709f3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fec499709f3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x7fec499706df - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x7fec4c19e2e1 - rustc_driver[cfb34b1539811fe8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fec4997122d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  12:     0x7fec49971087 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
  13:     0x7fec4996e1ec - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fec49970da2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  15:     0x7fec499c57d3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  16:     0x7fec4c020efc - rustc_mir_transform[de1f68ec5b9668bc]::ffi_unwind_calls::has_ffi_unwind_calls
  17:     0x7fec4b83088c - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_span[8f00505efff112e2]::def_id::LocalDefId, bool>
  18:     0x7fec4b82fb8e - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<rustc_span[8f00505efff112e2]::def_id::LocalDefId, bool>>
  19:     0x7fec4c0dd4fe - <rustc_query_impl[d6191eea714bd250]::Queries as rustc_middle[a9ca1c3f9fd197cd]::ty::query::QueryEngine>::has_ffi_unwind_calls
  20:     0x7fec4ba3b6fb - <rustc_query_impl[d6191eea714bd250]::queries::has_ffi_unwind_calls as rustc_query_system[860ed7b39cdfb46b]::query::config::QueryDescription<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>>::execute_query
  21:     0x7fec4aac92f0 - <rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt as rustc_query_system[860ed7b39cdfb46b]::dep_graph::DepContext>::try_load_from_on_disk_cache
  22:     0x7fec4aac91d6 - <rustc_query_system[860ed7b39cdfb46b]::dep_graph::graph::DepGraph<rustc_middle[a9ca1c3f9fd197cd]::dep_graph::dep_node::DepKind>>::exec_cache_promotions::<rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt>
  23:     0x7fec4aac9008 - <rustc_query_impl[d6191eea714bd250]::on_disk_cache::OnDiskCache as rustc_middle[a9ca1c3f9fd197cd]::ty::context::OnDiskCache>::drop_serialized_data
  24:     0x7fec4bf2c813 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_incremental[d8dc775a25cf5db2]::persist::save::save_dep_graph::{closure#0}::{closure#2}::{closure#0}>
  25:     0x7fec4bf2c3f9 - <rustc_middle[a9ca1c3f9fd197cd]::dep_graph::dep_node::DepKind as rustc_query_system[860ed7b39cdfb46b]::dep_graph::DepKind>::with_deps::<rustc_incremental[d8dc775a25cf5db2]::persist::save::save_dep_graph::{closure#0}, ()>
  26:     0x7fec4b04fc81 - rustc_incremental[d8dc775a25cf5db2]::persist::save::save_dep_graph
  27:     0x7fec4b04fbcd - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), <rustc_interface[3182dd864eff9d7d]::interface::Compiler>::enter<rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}::{closure#2}, core[8c92e53db3fc2eaa]::result::Result<core[8c92e53db3fc2eaa]::option::Option<rustc_interface[3182dd864eff9d7d]::queries::Linker>, rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}>
  28:     0x7fec4b04e43c - rustc_interface[3182dd864eff9d7d]::interface::create_compiler_and_run::<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>
  29:     0x7fec4b04cac1 - <scoped_tls[e395fa6e23b19669]::ScopedKey<rustc_span[8f00505efff112e2]::SessionGlobals>>::set::<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  30:     0x7fec4b04c7af - std[71cb4861428b0c25]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  31:     0x7fec4c001d70 - <<std[71cb4861428b0c25]::thread::Builder>::spawn_unchecked_<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7fec4997b003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  33:     0x7fec4997b003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  34:     0x7fec4997b003 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7fec49694b43 - <unknown>
  36:     0x7fec49726a00 - <unknown>
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic
```

**Comment by DzenanJupic** [comment]
Similar issue here
<details>
<summary> meta </summary>

```
rustc 1.67.0-nightly (a00f8ba7f 2022-11-15)
binary: rustc
commit-hash: a00f8ba7fcac1b27341679c51bf5a3271fa82df3
commit-date: 2022-11-15
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```
</details>

<details>
<summary> backtrace </summary>

```
thread '<unnamed>' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/check_unsafety.rs:472:36
stack backtrace:
   0:     0x7f89db332e60 - std::backtrace_rs::backtrace::libunwind::trace::h623ca7c2545da367
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f89db332e60 - std::backtrace_rs::backtrace::trace_unsynchronized::h339e54194b7bf843
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f89db332e60 - std::sys_common::backtrace::_print_fmt::h39130984054109fd
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f89db332e60 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfa5e4aa18ece27ff
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f89db39531e - core::fmt::write::h89f6ec0de92eb2ba
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f89db3232e5 - std::io::Write::write_fmt::hf0e465d1b13cde08
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/io/mod.rs:1682:15
   6:     0x7f89db332c25 - std::sys_common::backtrace::_print::h5c3a6b9e92733123
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f89db332c25 - std::sys_common::backtrace::print::h617c6080818fd336
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f89db3359cf - std::panicking::default_hook::{{closure}}::ha4c000959a58a266
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/panicking.rs:267:22
   9:     0x7f89db33570a - std::panicking::default_hook::h80287e6b1a8ab5a3
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/panicking.rs:286:9
  10:     0x7f89db3361dc - std::panicking::rust_panic_with_hook::hd38f216792535192
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/panicking.rs:688:13
  11:     0x7f89db335f77 - std::panicking::begin_panic_handler::{{closure}}::h04dbfee15e75c657
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/panicking.rs:579:13
  12:     0x7f89db33330c - std::sys_common::backtrace::__rust_end_short_backtrace::hefea495a2b02629d
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7f89db335c92 - rust_begin_unwind
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/panicking.rs:575:5
  14:     0x7f89db391cf3 - core::panicking::panic_fmt::h97a0144c9d72a8f8
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/core/src/panicking.rs:65:14
  15:     0x7f89dcd1db25 - rustc_mir_transform[90ab4d560697ca18]::check_unsafety::unsafety_check_result
  16:     0x7f89dcd1b3f8 - <rustc_mir_transform[90ab4d560697ca18]::check_unsafety::provide::{closure#0} as core[3fabb2b3983330a3]::ops::function::FnOnce<(rustc_middle[abcfb14e24642545]::ty::context::TyCtxt, rustc_span[9a6606dc9b427585]::def_id::LocalDefId)>>::call_once
  17:     0x7f89ded22480 - <rustc_middle[abcfb14e24642545]::dep_graph::dep_node::DepKind as rustc_query_system[a61e76100b0caf6f]::dep_graph::DepKind>::with_deps::<rustc_query_system[a61e76100b0caf6f]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[804366da8be58efc]::plumbing::QueryCtxt, rustc_span[9a6606dc9b427585]::def_id::LocalDefId, &rustc_middle[abcfb14e24642545]::mir::query::UnsafetyCheckResult>::{closure#1}, &rustc_middle[abcfb14e24642545]::mir::query::UnsafetyCheckResult>
  18:     0x7f89dcd1b907 - rustc_query_system[a61e76100b0caf6f]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[804366da8be58efc]::plumbing::QueryCtxt, rustc_span[9a6606dc9b427585]::def_id::LocalDefId, &rustc_middle[abcfb14e24642545]::mir::query::UnsafetyCheckResult>
  19:     0x7f89dcd1a763 - rustc_query_system[a61e76100b0caf6f]::query::plumbing::try_execute_query::<rustc_query_impl[804366da8be58efc]::plumbing::QueryCtxt, rustc_query_system[a61e76100b0caf6f]::query::caches::DefaultCache<rustc_span[9a6606dc9b427585]::def_id::LocalDefId, &rustc_middle[abcfb14e24642545]::mir::query::UnsafetyCheckResult>>
  20:     0x7f89ddf03c64 - <rustc_query_impl[804366da8be58efc]::Queries as rustc_middle[abcfb14e24642545]::ty::query::QueryEngine>::unsafety_check_result
  21:     0x7f89dc92aae7 - rustc_mir_transform[90ab4d560697ca18]::check_unsafety::check_unsafety
  22:     0x7f89dc929b21 - <rustc_session[3b411079dabf57a]::session::Session>::time::<(), rustc_interface[1c4c4049c89b9f16]::passes::analysis::{closure#3}>
  23:     0x7f89dc92553e - rustc_interface[1c4c4049c89b9f16]::passes::analysis
  24:     0x7f89ddd27d2e - <rustc_query_system[a61e76100b0caf6f]::dep_graph::graph::DepGraph<rustc_middle[abcfb14e24642545]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[abcfb14e24642545]::ty::context::TyCtxt, (), core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>
  25:     0x7f89ddd270a4 - rustc_query_system[a61e76100b0caf6f]::query::plumbing::try_execute_query::<rustc_query_impl[804366da8be58efc]::plumbing::QueryCtxt, rustc_query_system[a61e76100b0caf6f]::query::caches::DefaultCache<(), core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>>
  26:     0x7f89ddd26b27 - rustc_query_system[a61e76100b0caf6f]::query::plumbing::get_query::<rustc_query_impl[804366da8be58efc]::queries::analysis, rustc_query_impl[804366da8be58efc]::plumbing::QueryCtxt>
  27:     0x7f89dd80dd7e - <rustc_interface[1c4c4049c89b9f16]::passes::QueryContext>::enter::<rustc_driver[264bd666a4ec3967]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>
  28:     0x7f89dd80af5f - <rustc_interface[1c4c4049c89b9f16]::interface::Compiler>::enter::<rustc_driver[264bd666a4ec3967]::run_compiler::{closure#1}::{closure#2}, core[3fabb2b3983330a3]::result::Result<core[3fabb2b3983330a3]::option::Option<rustc_interface[1c4c4049c89b9f16]::queries::Linker>, rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>
  29:     0x7f89dd805fb2 - rustc_span[9a6606dc9b427585]::with_source_map::<core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>, rustc_interface[1c4c4049c89b9f16]::interface::run_compiler<core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>, rustc_driver[264bd666a4ec3967]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  30:     0x7f89dd805a8c - <scoped_tls[1c7f0121e168e3b1]::ScopedKey<rustc_span[9a6606dc9b427585]::SessionGlobals>>::set::<rustc_interface[1c4c4049c89b9f16]::interface::run_compiler<core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>, rustc_driver[264bd666a4ec3967]::run_compiler::{closure#1}>::{closure#0}, core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>
  31:     0x7f89dd805078 - std[a12c3934657dc52f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1c4c4049c89b9f16]::util::run_in_thread_pool_with_globals<rustc_interface[1c4c4049c89b9f16]::interface::run_compiler<core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>, rustc_driver[264bd666a4ec3967]::run_compiler::{closure#1}>::{closure#0}, core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>
  32:     0x7f89dd804d9c - <<std[a12c3934657dc52f]::thread::Builder>::spawn_unchecked_<rustc_interface[1c4c4049c89b9f16]::util::run_in_thread_pool_with_globals<rustc_interface[1c4c4049c89b9f16]::interface::run_compiler<core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>, rustc_driver[264bd666a4ec3967]::run_compiler::{closure#1}>::{closure#0}, core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3fabb2b3983330a3]::result::Result<(), rustc_errors[5b60f759d3f57066]::ErrorGuaranteed>>::{closure#1} as core[3fabb2b3983330a3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7f89df274c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he19adc936b97b661
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/alloc/src/boxed.rs:2000:9
  34:     0x7f89df274c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b08bc0be1f88378
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/alloc/src/boxed.rs:2000:9
  35:     0x7f89df274c63 - std::sys::unix::thread::Thread::new::thread_start::hb8a4d02754a9d514
                               at /rustc/a00f8ba7fcac1b27341679c51bf5a3271fa82df3/library/std/src/sys/unix/thread.rs:108:17
  36:     0x7f89db1eb609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  37:     0x7f89db10e133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  38:                0x0 - <unknown>
```
</details>

code is closed source unfortunatly

**Comment by cjgillot** [comment]
Marking as fixed by https://github.com/rust-lang/rust/pull/108820. Please open a new instance of this bug if it appears again.
