### ISSUE TITLE
How do I find out where the std error actually occurred?

### ISSUE THREAD

**Issue by Frozen1084** [rust-lang/rust#104502]
This is the vec error I get after using "RUST_BACKTRACE=full".
It has a very low chance of being wrong, it occurs about once a week. I can't reproduce this error in debug state.
The project has tens of thousands of lines and is in a working state. I can't find it by modifying the code. Although I have rewritten a lot of suspicious code.
Is there any way to find out exactly where it is in main.rs?

Or can we add a parameter like "RUST_BACKTRACE=all" to make the std-error contain information about main.rs?

```
thread '<unnamed>' panicked at 'insertion index (is 12) should be <= len (is 1)', library\alloc\src\vec\mod.rs:1379:13
stack backtrace:
   0:     0x7ff78b365a4f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff78b365a4f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff78b365a4f - std::sys_common::backtrace::_print_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff78b365a4f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff78b2f882b - core::fmt::write
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\fmt\mod.rs:1202
   5:     0x7ff78b35842a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\io\mod.rs:1679
   6:     0x7ff78b36772c - std::sys_common::backtrace::_print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff78b36772c - std::sys_common::backtrace::print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff78b36772c - std::panicking::default_hook::closure$1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:295
   9:     0x7ff78b368032 - std::panicking::default_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:314
  10:     0x7ff78b368032 - std::panicking::rust_panic_with_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:698
  11:     0x7ff78b367c05 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:588
  12:     0x7ff78b367b4f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff78b367b24 - std::panicking::begin_panic_handler
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
  14:     0x7ff78b36e2b5 - core::panicking::panic_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
  15:     0x7ff78b36e1fb - alloc::vec::impl$1::insert::assert_failed
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\alloc\src\vec\mod.rs:1379
  16:     0x7ff78b248b8a - __ImageBase
  17:     0x7ff78b285ff8 - __ImageBase
  18:     0x7ff78b28f248 - __ImageBase
  19:     0x7ff78b237df6 - __ImageBase
  20:     0x7ff78b240817 - __ImageBase
  21:     0x7ff78b364c4c - alloc::boxed::impl$44::call_once
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\alloc\src\boxed.rs:1940
  22:     0x7ff78b364c4c - alloc::boxed::impl$44::call_once
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\alloc\src\boxed.rs:1940
  23:     0x7ff78b364c4c - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys\windows\thread.rs:56
  24:     0x7ffb403e7034 - BaseThreadInitThunk
  25:     0x7ffb417026a1 - RtlUserThreadStart
```

**Comment by jyn514** [comment]
The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
