### ISSUE TITLE
Internal compiler error due to misnamed fields

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#104606]
### Code

Unfortunally I cannot provide any code to reproduce this, as this happens in a rather complicated private code base. The ICE goes away as soon as I fix the problems mentioned in the original error messages. Nevertheless I would expect that the compiler does not emit an ICE in that case.

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

(Note: I cannot try to reproduce that on newer compilers due to https://github.com/rust-lang/rust/issues/104322)

### Error output

```
error[E0412]: cannot find type `equality_check_plugin` in module `file_kind_plugins`
  --> geohub_database/src/graphql/filemanagement/mod.rs:84:9
   |
84 |       pub equality_check_plugin: bool,
   |           ^^^^^^^^^^^^^^^^^^^^^
   |
  ::: geohub_database/src/schema.rs:29:1
   |
29 | / table! {
30 | |     file_kind_plugins (file_kind_plugin_id) {
31 | |         file_kind_plugin_id -> Uuid,
32 | |         name -> Text,
...  |
39 | |     }
40 | | }
   | |_- similarly named struct `equality_check_api` defined here
   |
help: a struct with a similar name exists
   |
84 |     pub equality_check_api: bool,
   |         ~~~~~~~~~~~~~~~~~~
help: consider importing this struct
   |
1  | use crate::schema::file_kinds::equality_check_plugin;
   |
help: if you import `equality_check_plugin`, refer to it directly
   |
77 - #[table_name = "file_kind_plugins"]
77 + #[table_name = equality_check_plugin: bool,
   |

error[E0412]: cannot find type `metadata_extraction_plugin` in module `file_kind_plugins`
  --> geohub_database/src/graphql/filemanagement/mod.rs:85:9
   |
85 |       pub metadata_extraction_plugin: bool,
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: geohub_database/src/schema.rs:29:1
   |
29 | / table! {
30 | |     file_kind_plugins (file_kind_plugin_id) {
31 | |         file_kind_plugin_id -> Uuid,
32 | |         name -> Text,
...  |
39 | |     }
40 | | }
   | |_- similarly named struct `metadata_extraction_api` defined here
   |
help: a struct with a similar name exists
   |
85 |     pub metadata_extraction_api: bool,
   |         ~~~~~~~~~~~~~~~~~~~~~~~
help: consider importing this struct
   |
1  | use crate::schema::file_kinds::metadata_extraction_plugin;
   |
help: if you import `metadata_extraction_plugin`, refer to it directly
   |
77 - #[table_name = "file_kind_plugins"]
77 + #[table_name = metadata_extraction_plugin: bool,
   |

error: internal compiler error: compiler/rustc_trait_selection/src/traits/query/normalize.rs:257:21: unexpected ambiguity: Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder(TraitPredicate(<__Ctx as std::marker::Sized>, polarity:Positive), []), Binder(TraitPredicate(<<__Ctx as wundergraph::WundergraphContext>::Connection as diesel::Connection>, polarity:Positive), []), Binder(TraitPredicate(<<__Ctx as wundergraph::WundergraphContext>::Connection as std::marker::Send>, polarity:Positive), []), Binder(TraitPredicate(<<__Ctx as wundergraph::WundergraphContext>::Connection as std::marker::Sized>, polarity:Positive), []), Binder(TraitPredicate(<<__Ctx as wundergraph::WundergraphContext>::Connection as diesel::connection::SimpleConnection>, polarity:Positive), []), Binder(TraitPredicate(<__Ctx as wundergraph::WundergraphContext>, polarity:Positive), []), Binder(ProjectionPredicate(ProjectionTy { substs: [<__Ctx as wundergraph::WundergraphContext>::Connection], item_def_id: DefId(20:344 ~ diesel[eab3]::connection::Connection::Backend) }, Ty(diesel::pg::Pg)), []), Binder(OutlivesPredicate(__Ctx, ReStatic), [])], reveal: UserFacing, constness: NotConst }, value: ProjectionTy { substs: [wundergraph::query_builder::selection::filter::FilterConverter<graphql::filemanagement::FileKindPlugin, diesel::pg::Pg, __Ctx>], item_def_id: DefId(65:2325 ~ wundergraph[1cef]::query_builder::selection::filter::filter_helper::CreateFilter::Filter) } } } Canonical { max_universe: U2, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U1) }, CanonicalVarInfo { kind: PlaceholderRegion(Placeholder { universe: U1, name: BrNamed(DefId(65:4429 ~ wundergraph[1cef]::query_builder::types::wundergraph_value::{impl#10}::'a), 'a) }) }, CanonicalVarInfo { kind: Region(U2) }, CanonicalVarInfo { kind: PlaceholderRegion(Placeholder { universe: U2, name: BrNamed(DefId(65:4429 ~ wundergraph[1cef]::query_builder::types::wundergraph_value::{impl#10}::'a), 'a) }) }], value: QueryResponse { var_values: CanonicalVarValues { var_values: [] }, region_constraints: QueryRegionConstraints { outlives: [Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon(0) }), ReStatic), []), Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 2, kind: BrAnon(2) })), []), Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 3, kind: BrAnon(3) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 4, kind: BrAnon(4) })), []), Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 2, kind: BrAnon(2) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1) })), []), Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 4, kind: BrAnon(4) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 3, kind: BrAnon(3) })), []), Binder(OutlivesPredicate(diesel::pg::Pg, ReStatic), []), Binder(OutlivesPredicate(schema::file_kind_plugins::table, ReStatic), []), Binder(OutlivesPredicate(__Ctx, ReStatic), [])], member_constraints: [] }, certainty: Ambiguous, opaque_types: [], value: NormalizationResult { normalized_ty: [type error] } } }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/compiler/rustc_errors/src/lib.rs:1392:9
stack backtrace:
   0:     0x7ff93ef7419d - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff93ef7419d - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff93ef7419d - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7ff93ef7419d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7ff93efcf6ac - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x7ff93ef654e1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x7ff93ef76eb5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7ff93ef76eb5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7ff93ef76eb5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x7ff93ef76bd1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x7ff94184c484 - rustc_driver[4568cc0a685fd94d]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7ff93ef775ea - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
  12:     0x7ff9427f4641 - std[306a94a967d8f5ee]::panicking::begin_panic::<rustc_errors[5fcb1a1f56a762e6]::ExplicitBug>::{closure#0}
  13:     0x7ff9427f4516 - std[306a94a967d8f5ee]::sys_common::backtrace::__rust_end_short_backtrace::<std[306a94a967d8f5ee]::panicking::begin_panic<rustc_errors[5fcb1a1f56a762e6]::ExplicitBug>::{closure#0}, !>
  14:     0x7ff942846ee6 - std[306a94a967d8f5ee]::panicking::begin_panic::<rustc_errors[5fcb1a1f56a762e6]::ExplicitBug>
  15:     0x7ff9427dae66 - std[306a94a967d8f5ee]::panic::panic_any::<rustc_errors[5fcb1a1f56a762e6]::ExplicitBug>
  16:     0x7ff9427d9c95 - <rustc_errors[5fcb1a1f56a762e6]::HandlerInner>::bug::<&alloc[6d6f83537459af52]::string::String>
  17:     0x7ff9427d99f0 - <rustc_errors[5fcb1a1f56a762e6]::Handler>::bug::<&alloc[6d6f83537459af52]::string::String>
  18:     0x7ff9428d6c6d - rustc_middle[b6cf56a787d1e2a1]::ty::context::tls::with_opt::<rustc_middle[b6cf56a787d1e2a1]::util::bug::opt_span_bug_fmt<rustc_span[721a57c036170ce]::span_encoding::Span>::{closure#0}, ()>
  19:     0x7ff9428d6ce6 - rustc_middle[b6cf56a787d1e2a1]::util::bug::opt_span_bug_fmt::<rustc_span[721a57c036170ce]::span_encoding::Span>
  20:     0x7ff9402a1ea3 - rustc_middle[b6cf56a787d1e2a1]::util::bug::bug_fmt
  21:     0x7ff940940842 - <rustc_trait_selection[a68aa601d6a3b6cd]::traits::query::normalize::QueryNormalizer as rustc_middle[b6cf56a787d1e2a1]::ty::fold::FallibleTypeFolder>::try_fold_ty
  22:     0x7ff940ae3ead - <rustc_middle[b6cf56a787d1e2a1]::ty::subst::GenericArg as rustc_middle[b6cf56a787d1e2a1]::ty::fold::TypeFoldable>::try_fold_with::<rustc_trait_selection[a68aa601d6a3b6cd]::traits::query::normalize::QueryNormalizer>
  23:     0x7ff940ae3c5b - rustc_middle[b6cf56a787d1e2a1]::ty::util::fold_list::<rustc_trait_selection[a68aa601d6a3b6cd]::traits::query::normalize::QueryNormalizer, rustc_middle[b6cf56a787d1e2a1]::ty::subst::GenericArg, <&rustc_middle[b6cf56a787d1e2a1]::ty::list::List<rustc_middle[b6cf56a787d1e2a1]::ty::subst::GenericArg> as rustc_middle[b6cf56a787d1e2a1]::ty::fold::TypeFoldable>::try_fold_with<rustc_trait_selection[a68aa601d6a3b6cd]::traits::query::normalize::QueryNormalizer>::{closure#0}>
  24:     0x7ff940abc064 - <rustc_infer[b9251f21a0aa6bc7]::infer::at::At as rustc_trait_selection[a68aa601d6a3b6cd]::traits::query::normalize::AtExt>::normalize::<rustc_middle[b6cf56a787d1e2a1]::ty::sty::TraitRef>
  25:     0x7ff940aba31f - <rustc_infer[b9251f21a0aa6bc7]::infer::InferCtxtBuilder>::enter::<std[306a94a967d8f5ee]::collections::hash::set::HashSet<rustc_middle[b6cf56a787d1e2a1]::ty::Ty, core[6fcc70bcc91a5bf5]::hash::BuildHasherDefault<rustc_hash[8f2d741785335e67]::FxHasher>>, rustc_typeck[8db86e16038c4234]::check::wfcheck::impl_implied_bounds::{closure#0}>
  26:     0x7ff940ab9357 - rustc_typeck[8db86e16038c4234]::check::wfcheck::impl_implied_bounds
  27:     0x7ff940ab8764 - <rustc_infer[b9251f21a0aa6bc7]::infer::InferCtxtBuilder>::enter::<(), rustc_typeck[8db86e16038c4234]::check::wfcheck::enter_wf_checking_ctxt<rustc_typeck[8db86e16038c4234]::check::wfcheck::check_impl::{closure#0}>::{closure#0}>
  28:     0x7ff940ab3b21 - rustc_typeck[8db86e16038c4234]::check::wfcheck::check_well_formed
  29:     0x7ff9409eb901 - <rustc_query_system[8caf4755e287670e]::dep_graph::graph::DepGraph<rustc_middle[b6cf56a787d1e2a1]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b6cf56a787d1e2a1]::ty::context::TyCtxt, rustc_span[721a57c036170ce]::def_id::LocalDefId, ()>
  30:     0x7ff9409eaab6 - rustc_query_system[8caf4755e287670e]::query::plumbing::try_execute_query::<rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt, rustc_query_system[8caf4755e287670e]::query::caches::DefaultCache<rustc_span[721a57c036170ce]::def_id::LocalDefId, ()>>
  31:     0x7ff9415549a9 - rustc_query_system[8caf4755e287670e]::query::plumbing::force_query::<rustc_query_impl[232efbc2900411f9]::queries::check_well_formed, rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt>
  32:     0x7ff94155481e - rustc_query_impl[232efbc2900411f9]::query_callbacks::check_well_formed::force_from_dep_node
  33:     0x7ff9401e8531 - <rustc_middle[b6cf56a787d1e2a1]::ty::context::TyCtxt as rustc_query_system[8caf4755e287670e]::dep_graph::DepContext>::try_force_from_dep_node
  34:     0x7ff9401e7969 - <rustc_query_system[8caf4755e287670e]::dep_graph::graph::DepGraph<rustc_middle[b6cf56a787d1e2a1]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt>
  35:     0x7ff9401be7c1 - rustc_query_system[8caf4755e287670e]::query::plumbing::ensure_must_run::<rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt, rustc_span[721a57c036170ce]::def_id::LocalDefId, &rustc_middle[b6cf56a787d1e2a1]::ty::context::TypeckResults>
  36:     0x7ff9412b06bf - rustc_query_system[8caf4755e287670e]::query::plumbing::get_query::<rustc_query_impl[232efbc2900411f9]::queries::check_mod_type_wf, rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt>
  37:     0x7ff94123e5b0 - <rustc_session[98f7faf1d37bb5fb]::session::Session>::track_errors::<rustc_typeck[8db86e16038c4234]::check_crate::{closure#5}, ()>
  38:     0x7ff94123acfb - rustc_typeck[8db86e16038c4234]::check_crate
  39:     0x7ff941236917 - rustc_interface[f934826ba4c12dd9]::passes::analysis
  40:     0x7ff9415f12bc - <rustc_query_system[8caf4755e287670e]::dep_graph::graph::DepGraph<rustc_middle[b6cf56a787d1e2a1]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b6cf56a787d1e2a1]::ty::context::TyCtxt, (), core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>
  41:     0x7ff9415f0aab - rustc_query_system[8caf4755e287670e]::query::plumbing::try_execute_query::<rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt, rustc_query_system[8caf4755e287670e]::query::caches::DefaultCache<(), core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>>
  42:     0x7ff9415f05fe - rustc_query_system[8caf4755e287670e]::query::plumbing::get_query::<rustc_query_impl[232efbc2900411f9]::queries::analysis, rustc_query_impl[232efbc2900411f9]::plumbing::QueryCtxt>
  43:     0x7ff940fcad87 - <rustc_interface[f934826ba4c12dd9]::passes::QueryContext>::enter::<rustc_driver[4568cc0a685fd94d]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>
  44:     0x7ff940fc397f - <rustc_interface[f934826ba4c12dd9]::interface::Compiler>::enter::<rustc_driver[4568cc0a685fd94d]::run_compiler::{closure#1}::{closure#2}, core[6fcc70bcc91a5bf5]::result::Result<core[6fcc70bcc91a5bf5]::option::Option<rustc_interface[f934826ba4c12dd9]::queries::Linker>, rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>
  45:     0x7ff940fb886a - rustc_span[721a57c036170ce]::with_source_map::<core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>, rustc_interface[f934826ba4c12dd9]::interface::create_compiler_and_run<core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>, rustc_driver[4568cc0a685fd94d]::run_compiler::{closure#1}>::{closure#1}>
  46:     0x7ff940fb81a2 - <scoped_tls[80743de900a7f844]::ScopedKey<rustc_span[721a57c036170ce]::SessionGlobals>>::set::<rustc_interface[f934826ba4c12dd9]::interface::run_compiler<core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>, rustc_driver[4568cc0a685fd94d]::run_compiler::{closure#1}>::{closure#0}, core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>
  47:     0x7ff940fb65cf - std[306a94a967d8f5ee]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f934826ba4c12dd9]::util::run_in_thread_pool_with_globals<rustc_interface[f934826ba4c12dd9]::interface::run_compiler<core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>, rustc_driver[4568cc0a685fd94d]::run_compiler::{closure#1}>::{closure#0}, core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>::{closure#0}, core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>
  48:     0x7ff9416700b9 - <<std[306a94a967d8f5ee]::thread::Builder>::spawn_unchecked_<rustc_interface[f934826ba4c12dd9]::util::run_in_thread_pool_with_globals<rustc_interface[f934826ba4c12dd9]::interface::run_compiler<core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>, rustc_driver[4568cc0a685fd94d]::run_compiler::{closure#1}>::{closure#0}, core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>::{closure#0}, core[6fcc70bcc91a5bf5]::result::Result<(), rustc_errors[5fcb1a1f56a762e6]::ErrorGuaranteed>>::{closure#1} as core[6fcc70bcc91a5bf5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:     0x7ff93ef81723 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h56d5fc072706762b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  50:     0x7ff93ef81723 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h41deef8e33b824bb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  51:     0x7ff93ef81723 - std::sys::unix::thread::Thread::new::thread_start::ha6436304a1170bba
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys/unix/thread.rs:108:17
  52:     0x7ff93ecb1b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  53:     0x7ff93ed43a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  54:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-args=-fuse-ld=lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_well_formed] checking that `graphql::filemanagement::_IMPL_WUNDERGRAPH_ENTITY_FOR_FILEKINDPLUGIN::<impl at geohub_database/src/graphql/filemanagement/mod.rs:75:38: 75:55>` is well-formed
```

**Comment by jdahlstrom** [comment]
I added a possible MCVE to the potentially related #105299: https://github.com/rust-lang/rust/issues/105299#issuecomment-1364752793

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
