### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_borrowck\src\diagnostics\region_errors.rs:697:32

### ISSUE THREAD

**Issue by semiviral** [rust-lang/rust#105115]
### Code

```rust
// Minimum reproduction I could manage

struct A<'a> {
    data: &'a str,
    index: usize
}

impl A<'_> {
    fn a(&mut self, p: impl Pattern) -> Option<&str> {
        let remaining_data = self.data.get(self.index..)?;
        let pattern_suffix_data = p.strip_prefix_of(remaining_data)?;
        let pattern_len = remaining_data.len() - pattern_suffix_data.len();
        Some(self.data.get(self.index..(self.index + pattern_len))?)
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (c97d02cdb 2022-10-05)
binary: rustc
commit-hash: c97d02cdb5ca5f5e9eff1fa9e4560d220d1fd2a0
commit-date: 2022-10-05
host: x86_64-pc-windows-msvc
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_borrowck\src\diagnostics\region_errors.rs:697:32
stack backtrace:
   0:     0x7fff29ff91c2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04aa1af8887a8cbb
   1:     0x7fff2a0343fb - core::fmt::write::h0fb5165a869bd74a
   2:     0x7fff29feb84a - <std::io::IoSlice as core::fmt::Debug>::fmt::ha04759feb8548b78
   3:     0x7fff29ffc8b4 - std::panicking::default_hook::h24633d1d0bef6afd
   4:     0x7fff29ffc4ea - std::panicking::default_hook::h24633d1d0bef6afd
   5:     0x7fff1a9f832e - rustc_driver[83b8198720eea51b]::describe_lints
   6:     0x7fff29ffd2ca - std::panicking::rust_panic_with_hook::ha42499a1d2e05843
   7:     0x7fff29ffcffa - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h9ffe1488d336d55b
   8:     0x7fff29ff9ecf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04aa1af8887a8cbb
   9:     0x7fff29ffcd00 - rust_begin_unwind
  10:     0x7fff2a06a355 - core::panicking::panic_fmt::h3a8f1715105956fe
  11:     0x7fff2a06a1fc - core::panicking::panic::hf20b83f614f445e1
  12:     0x7fff1c1f0691 - <rustc_mir_build[64a5d3c14fb23fa4]::thir::pattern::PatternError as core[448be74a1a4414a3]::fmt::Debug>::fmt
  13:     0x7fff1a07460f - <rustc_mir_build[64a5d3c14fb23fa4]::thir::pattern::check_match::MatchVisitor as rustc_hir[bc1b08696a260a2e]::intravisit::Visitor>::visit_expr
  14:     0x7fff1a188daa - <polonius_engine[69e1e00dd921e3d]::facts::AllFacts<rustc_borrowck[1a77a1e216a25dd9]::facts::RustcFacts> as rustc_borrowck[1a77a1e216a25dd9]::facts::AllFactsExt>::enabled
  15:     0x7fff1a06531d - <rustc_mir_build[64a5d3c14fb23fa4]::thir::pattern::check_match::MatchVisitor as rustc_hir[bc1b08696a260a2e]::intravisit::Visitor>::visit_expr
  16:     0x7fff18c956d8 - <&[rustc_span[3d5e8dc43b4f8b60]::def_id::DefId] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  17:     0x7fff18cc5ac5 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  18:     0x7fff1a3bd5fc - <rustc_span[3d5e8dc43b4f8b60]::symbol::Symbol as rustc_serialize[b10207d2c4eb4655]::serialize::Encodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheEncoder>>::encode
  19:     0x7fff1a2d6875 - <rustc_query_impl[7e46f50f3831622d]::Queries as rustc_middle[65dde1654b97c283]::ty::query::QueryEngine>::as_any
  20:     0x7fff19161f51 - once_cell[3c1a1ac4a645dd8c]::imp::initialize_or_wait
  21:     0x7fff18282bbc - rustc_interface[8211937e4cb839a9]::passes::analysis
  22:     0x7fff1827be52 - rustc_interface[8211937e4cb839a9]::passes::analysis
  23:     0x7fff18c96e3e - <&[rustc_span[3d5e8dc43b4f8b60]::def_id::DefId] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  24:     0x7fff18ce4c39 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7fff18db2e31 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  26:     0x7fff18e02226 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  27:     0x7fff18255eb4 - rustc_driver[83b8198720eea51b]::args::arg_expand_all
  28:     0x7fff18223478 - <unknown>
  29:     0x7fff18256e4a - <rustc_middle[65dde1654b97c283]::ty::SymbolName as core[448be74a1a4414a3]::fmt::Display>::fmt  30:     0x7fff1823f170 - <unknown>
  31:     0x7fff18255cf7 - rustc_driver[83b8198720eea51b]::args::arg_expand_all
  32:     0x7fff18247449 - <unknown>
  33:     0x7fff182478ad - <unknown>
  34:     0x7fff2a00dabc - std::sys::windows::thread::Thread::new::ha597790fc6aa6b03
  35:     0x7fffbacf244d - BaseThreadInitThunk
  36:     0x7fffbbd0dfb8 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (c97d02cdb 2022-10-05) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `lexer::<impl at src\lexer\mod.rs:13:1: 13:19>::next_eq`
#1 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_borrowck\src\diagnostics\region_errors.rs:697:32
stack backtrace:
   0:     0x7fff29ff91c2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04aa1af8887a8cbb
   1:     0x7fff2a0343fb - core::fmt::write::h0fb5165a869bd74a
   2:     0x7fff29feb84a - <std::io::IoSlice as core::fmt::Debug>::fmt::ha04759feb8548b78
   3:     0x7fff29ffc8b4 - std::panicking::default_hook::h24633d1d0bef6afd
   4:     0x7fff29ffc4ea - std::panicking::default_hook::h24633d1d0bef6afd
   5:     0x7fff1a9f832e - rustc_driver[83b8198720eea51b]::describe_lints
   6:     0x7fff29ffd2ca - std::panicking::rust_panic_with_hook::ha42499a1d2e05843
   7:     0x7fff29ffcffa - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h9ffe1488d336d55b
   8:     0x7fff29ff9ecf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04aa1af8887a8cbb
   9:     0x7fff29ffcd00 - rust_begin_unwind
  10:     0x7fff2a06a355 - core::panicking::panic_fmt::h3a8f1715105956fe
  11:     0x7fff2a06a1fc - core::panicking::panic::hf20b83f614f445e1
  12:     0x7fff1c1f0691 - <rustc_mir_build[64a5d3c14fb23fa4]::thir::pattern::PatternError as core[448be74a1a4414a3]::fmt::Debug>::fmt
  13:     0x7fff1a07460f - <rustc_mir_build[64a5d3c14fb23fa4]::thir::pattern::check_match::MatchVisitor as rustc_hir[bc1b08696a260a2e]::intravisit::Visitor>::visit_expr
  14:     0x7fff1a188daa - <polonius_engine[69e1e00dd921e3d]::facts::AllFacts<rustc_borrowck[1a77a1e216a25dd9]::facts::RustcFacts> as rustc_borrowck[1a77a1e216a25dd9]::facts::AllFactsExt>::enabled
  15:     0x7fff1a06531d - <rustc_mir_build[64a5d3c14fb23fa4]::thir::pattern::check_match::MatchVisitor as rustc_hir[bc1b08696a260a2e]::intravisit::Visitor>::visit_expr
  16:     0x7fff18c956d8 - <&[rustc_span[3d5e8dc43b4f8b60]::def_id::DefId] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  17:     0x7fff18cc5ac5 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  18:     0x7fff1a3bd5fc - <rustc_span[3d5e8dc43b4f8b60]::symbol::Symbol as rustc_serialize[b10207d2c4eb4655]::serialize::Encodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheEncoder>>::encode
  19:     0x7fff1a2d6875 - <rustc_query_impl[7e46f50f3831622d]::Queries as rustc_middle[65dde1654b97c283]::ty::query::QueryEngine>::as_any
  20:     0x7fff19161f51 - once_cell[3c1a1ac4a645dd8c]::imp::initialize_or_wait
  21:     0x7fff18282bbc - rustc_interface[8211937e4cb839a9]::passes::analysis
  22:     0x7fff1827be52 - rustc_interface[8211937e4cb839a9]::passes::analysis
  23:     0x7fff18c96e3e - <&[rustc_span[3d5e8dc43b4f8b60]::def_id::DefId] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  24:     0x7fff18ce4c39 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7fff18db2e31 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  26:     0x7fff18e02226 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  27:     0x7fff18255eb4 - rustc_driver[83b8198720eea51b]::args::arg_expand_all
  28:     0x7fff18223478 - <unknown>
  29:     0x7fff18256e4a - <rustc_middle[65dde1654b97c283]::ty::SymbolName as core[448be74a1a4414a3]::fmt::Display>::fmt  30:     0x7fff1823f170 - <unknown>
  31:     0x7fff18255cf7 - rustc_driver[83b8198720eea51b]::args::arg_expand_all
  32:     0x7fff18247449 - <unknown>
  33:     0x7fff182478ad - <unknown>
  34:     0x7fff2a00dabc - std::sys::windows::thread::Thread::new::ha597790fc6aa6b03
  35:     0x7fffbacf244d - BaseThreadInitThunk
  36:     0x7fffbbd0dfb8 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (c97d02cdb 2022-10-05) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `lexer::<impl at src\lexer\mod.rs:13:1: 13:19>::next_until`
#1 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: `InferCtxt` incorrectly tainted by errors
  |
  = note: delayed at compiler\rustc_infer\src\infer\mod.rs:1282:27

thread 'rustc' panicked at 'Box<dyn Any>', compiler\rustc_errors\src\lib.rs:1536:13
stack backtrace:
   0:     0x7fff29ff91c2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04aa1af8887a8cbb
   1:     0x7fff2a0343fb - core::fmt::write::h0fb5165a869bd74a
   2:     0x7fff29feb84a - <std::io::IoSlice as core::fmt::Debug>::fmt::ha04759feb8548b78
   3:     0x7fff29ffc8b4 - std::panicking::default_hook::h24633d1d0bef6afd
   4:     0x7fff29ffc4ea - std::panicking::default_hook::h24633d1d0bef6afd
   5:     0x7fff1a9f832e - rustc_driver[83b8198720eea51b]::describe_lints
   6:     0x7fff29ffd2ca - std::panicking::rust_panic_with_hook::ha42499a1d2e05843
   7:     0x7fff1cd703a3 - <rustc_errors[d0d7f0e62c2e17db]::emitter::DisplaySuggestion as core[448be74a1a4414a3]::fmt::Debug>::fmt
   8:     0x7fff1cd701f9 - <rustc_errors[d0d7f0e62c2e17db]::emitter::DisplaySuggestion as core[448be74a1a4414a3]::fmt::Debug>::fmt
   9:     0x7fff1cd701c9 - <rustc_errors[d0d7f0e62c2e17db]::emitter::DisplaySuggestion as core[448be74a1a4414a3]::fmt::Debug>::fmt
  10:     0x7fff1cd66e19 - <getopts[94ee9c1606589425]::Fail as core[448be74a1a4414a3]::fmt::Debug>::fmt
  11:     0x7fff190f5a46 - <rustc_errors[d0d7f0e62c2e17db]::HandlerInner>::emit_diagnostic
  12:     0x7fff190f2bc2 - <rustc_errors[d0d7f0e62c2e17db]::HandlerInner as core[448be74a1a4414a3]::ops::drop::Drop>::drop
  13:     0x7fff18242d49 - <unknown>
  14:     0x7fff182461a1 - <unknown>
  15:     0x7fff18257a5d - <rustc_middle[65dde1654b97c283]::ty::SymbolName as core[448be74a1a4414a3]::fmt::Display>::fmt  16:     0x7fff182576f7 - <rustc_middle[65dde1654b97c283]::ty::SymbolName as core[448be74a1a4414a3]::fmt::Display>::fmt  17:     0x7fff1a97e140 - _rust_realloc
  18:     0x7fff1a97d596 - _rust_realloc
  19:     0x7fff1a979328 - _rust_realloc
  20:     0x7fff1a97c8fd - _rust_realloc
  21:     0x7fff1a979c41 - _rust_realloc
  22:     0x7fffbbd53f2f - _chkstk
  23:     0x7fffbbcd03d4 - RtlUnwindEx
  24:     0x7fff1a9797f2 - _rust_realloc
  25:     0x7fff1a97b5a9 - _rust_realloc
  26:     0x7fff1a97b9bf - _rust_realloc
  27:     0x7fff1a97c9f9 - _rust_realloc
  28:     0x7fff1a979c41 - _rust_realloc
  29:     0x7fffbbd53eaf - _chkstk
  30:     0x7fffbbcceae6 - RtlFindCharInUnicodeString
  31:     0x7fffbbd04b35 - RtlRaiseException
  32:     0x7fffb94a039c - RaiseException
  33:     0x7fff2a05d238 - _umodti3
  34:     0x7fff2a012eae - _rust_start_panic
  35:     0x7fff29ffd4eb - rust_panic
  36:     0x7fff29ffd47d - std::panicking::rust_panic_with_hook::ha42499a1d2e05843
  37:     0x7fff29ff12c9 - std::panic::resume_unwind::h6d984026f89dffef
  38:     0x7fff1916205d - once_cell[3c1a1ac4a645dd8c]::imp::initialize_or_wait
  39:     0x7fff18282bbc - rustc_interface[8211937e4cb839a9]::passes::analysis
  40:     0x7fff1827be52 - rustc_interface[8211937e4cb839a9]::passes::analysis
  41:     0x7fff18c96e3e - <&[rustc_span[3d5e8dc43b4f8b60]::def_id::DefId] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  42:     0x7fff18ce4c39 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7fff18db2e31 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7fff18e02226 - <&[(rustc_middle[65dde1654b97c283]::middle::exported_symbols::ExportedSymbol, rustc_middle[65dde1654b97c283]::middle::exported_symbols::SymbolExportInfo)] as rustc_serialize[b10207d2c4eb4655]::serialize::Decodable<rustc_query_impl[7e46f50f3831622d]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7fff18255eb4 - rustc_driver[83b8198720eea51b]::args::arg_expand_all
  46:     0x7fff18223478 - <unknown>
  47:     0x7fff18256e4a - <rustc_middle[65dde1654b97c283]::ty::SymbolName as core[448be74a1a4414a3]::fmt::Display>::fmt  48:     0x7fff1823f170 - <unknown>
  49:     0x7fff18255cf7 - rustc_driver[83b8198720eea51b]::args::arg_expand_all
  50:     0x7fff18247449 - <unknown>
  51:     0x7fff182478ad - <unknown>
  52:     0x7fff2a00dabc - std::sys::windows::thread::Thread::new::ha597790fc6aa6b03
  53:     0x7fffbacf244d - BaseThreadInitThunk
  54:     0x7fffbbd0dfb8 - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.0-nightly (c97d02cdb 2022-10-05) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `crash`

Caused by:
  process didn't exit successfully: `rustc --crate-name crash --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=8251a35eb6160c1a -C extra-filename=-8251a35eb6160c1a --out-dir C:\Users\semiv\GitHub\crash\target\debug\deps -C incremental=C:\Users\semiv\GitHub\crash\target\debug\incremental -L dependency=C:\Users\semiv\GitHub\crash\target\debug\deps --extern logos=C:\Users\semiv\GitHub\crash\target\debug\deps\liblogos-33c4624f5fc2a3cb.rmeta` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

</p>
</details>

**Comment by Rageking8** [comment]
That's a somewhat old nightly version, can you check if the ICE still repros on latest nightly.

**Comment by chenyukang** [comment]
Can not reproduce in curent nightly.
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4ac74c427618b4f3129efbdca9f749df

**Comment by semiviral** [comment]
`rustup update` was not updating the nightly version until I used `rustup default nightly`. This has fixed the issue, thank you.
