### ISSUE TITLE
ICE:  broken MIR in DropGlue(DefId(2:2801 ~ core[7784]::ptr::drop_in_place)

### ISSUE THREAD

**Issue by niklasad1** [rust-lang/rust#105129]
### Code

```
$ git clone https://github.com/paritytech/jsonrpsee && git checkout 237be727ade4dc833aedfe0fea62b786cc2451c5
$ cargo +nightly test
```

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (c97b539e4 2022-11-30)
binary: rustc
commit-hash: c97b539e408ea353f4fde2f9251d598291fec421
commit-date: 2022-11-30
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output

```
error: internal compiler error: broken MIR in DropGlue(DefId(2:2801 ~ core[7784]::ptr::drop_in_place), Some(hyper::proto::h1::dispatch::Server<hyper::service::util::ServiceFn<fn(hyper::Request<hyper::Body>) -> impl futures::Future<Output = std::result::Result<hyper::Response<hyper::Body>, std::convert::Infallible>> {jsonrpsee::jsonrpsee_server::transport::http::reject_connection::{closure#0}::reject}, hyper::Body>, hyper::Body>)) (after phase change to runtime-optimized) at bb0[0]:
                                Field projection `(*_1).field[0]` specified type `std::pin::Pin<std::boxed::Box<std::option::Option<[async fn body@jsonrpsee::jsonrpsee_server::transport::http::reject_connection::{closure#0}::reject::{closure#0}]>>>`, but actual type is `std::pin::Pin<std::boxed::Box<std::option::Option<<hyper::service::util::ServiceFn<fn(hyper::Request<hyper::Body>) -> impl futures::Future<Output = std::result::Result<hyper::Response<hyper::Body>, std::convert::Infallible>> {jsonrpsee::jsonrpsee_server::transport::http::reject_connection::{closure#0}::reject}, hyper::Body> as hyper::service::http::HttpService<hyper::Body>>::Future>>>`
   --> <PATH>/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1
    |
490 | pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:229:30

warning: Error finalizing incremental compilation session directory `<PATH>/jsonrpsee/target/debug/incremental/proc_macros-1yopek7gf1ry2/s-gfxew4es2p-es4z7d-working`: No such file or directory (os error 2)

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1609:13
stack backtrace:
   0:     0x7f257a8823fa - std::backtrace_rs::backtrace::libunwind::trace::hd0524392467f58f0
   0:     0x7f9fb8a823fa - std::backtrace_rs::backtrace::libunwind::trace::hd0524392467f58f0
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f9fb8a823fa - std::backtrace_rs::backtrace::trace_unsynchronized::h2c36934e8f6e9be3
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9fb8a823fa - std::sys_common::backtrace::_print_fmt::he6e9d614e924de03
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:65:5
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   0:     0x7f6df4a823fa - std::backtrace_rs::backtrace::libunwind::trace::hd0524392467f58f0
   3:     0x7f9fb8a823fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd3e316690863bea3
   1:     0x7f257a8823fa - std::backtrace_rs::backtrace::trace_unsynchronized::h2c36934e8f6e9be3
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:44:22
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f257a8823fa - std::sys_common::backtrace::_print_fmt::he6e9d614e924de03
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:65:5
   1:     0x7f6df4a823fa - std::backtrace_rs::backtrace::trace_unsynchronized::h2c36934e8f6e9be3
   3:     0x7f257a8823fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd3e316690863bea3
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:44:22
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6df4a823fa - std::sys_common::backtrace::_print_fmt::he6e9d614e924de03
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f6df4a823fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd3e316690863bea3
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f9fb49c912e - core::fmt::write::h61f017e5ff79d11e
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f9fb8a766c5 - std::io::Write::write_fmt::hdb1cd50f6bc7b937
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/io/mod.rs:1682:15
   4:     0x7f6df09c912e - core::fmt::write::h61f017e5ff79d11e
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f6df4a766c5 - std::io::Write::write_fmt::hdb1cd50f6bc7b937
   6:     0x7f9fb8a821c5 - std::sys_common::backtrace::_print::h61ced5a58150f7a3
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/io/mod.rs:1682:15
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:47:5
   6:     0x7f6df4a821c5 - std::sys_common::backtrace::_print::h61ced5a58150f7a3
   4:     0x7f25767c912e - core::fmt::write::h61f017e5ff79d11e
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/core/src/fmt/mod.rs:1208:17
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f6df4a821c5 - std::sys_common::backtrace::print::h60ec39223e784f04
   7:     0x7f9fb8a821c5 - std::sys_common::backtrace::print::h60ec39223e784f04
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f6df4a8452f - std::panicking::default_hook::{{closure}}::he373ef3cb63d5455
   5:     0x7f257a8766c5 - std::io::Write::write_fmt::hdb1cd50f6bc7b937
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:267:22
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:34:9
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/io/mod.rs:1682:15
   9:     0x7f6df4a8426b - std::panicking::default_hook::h97c2b49db1cfdaed
   8:     0x7f9fb8a8452f - std::panicking::default_hook::{{closure}}::he373ef3cb63d5455
   6:     0x7f257a8821c5 - std::sys_common::backtrace::_print::h61ced5a58150f7a3
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:286:9
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:267:22
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f257a8821c5 - std::sys_common::backtrace::print::h60ec39223e784f04
   9:     0x7f9fb8a8426b - std::panicking::default_hook::h97c2b49db1cfdaed
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys_common/backtrace.rs:34:9
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:286:9
   8:     0x7f257a88452f - std::panicking::default_hook::{{closure}}::he373ef3cb63d5455
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:267:22
   9:     0x7f257a88426b - std::panicking::default_hook::h97c2b49db1cfdaed
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:286:9
  10:     0x7f9fb7cc7904 - <rustc_driver[cc2f53293c3db517]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[7784b4547a4f67b7]::ops::function::FnOnce<(&core[7784b4547a4f67b7]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f9fb8a84d2d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h11f431d9b74177b9
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2032:9
  12:     0x7f9fb8a84d2d - std::panicking::rust_panic_with_hook::hd8e47e215c6e1b89
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:692:13
  10:     0x7f6df3cc7904 - <rustc_driver[cc2f53293c3db517]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[7784b4547a4f67b7]::ops::function::FnOnce<(&core[7784b4547a4f67b7]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f6df4a84d2d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h11f431d9b74177b9
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2032:9
  12:     0x7f6df4a84d2d - std::panicking::rust_panic_with_hook::hd8e47e215c6e1b89
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:692:13
  13:     0x7f6df3d00271 - std[5baa01868b04d1a3]::panicking::begin_panic::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>::{closure#0}
  13:     0x7f9fb7d00271 - std[5baa01868b04d1a3]::panicking::begin_panic::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>::{closure#0}
  14:     0x7f6df3cfeb36 - std[5baa01868b04d1a3]::sys_common::backtrace::__rust_end_short_backtrace::<std[5baa01868b04d1a3]::panicking::begin_panic<rustc_errors[18c341fe1ea9d738]::ExplicitBug>::{closure#0}, !>
  15:     0x7f6df3cf7276 - std[5baa01868b04d1a3]::panicking::begin_panic::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>
  16:     0x7f6df3cfa9c6 - std[5baa01868b04d1a3]::panic::panic_any::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>
  14:     0x7f9fb7cfeb36 - std[5baa01868b04d1a3]::sys_common::backtrace::__rust_end_short_backtrace::<std[5baa01868b04d1a3]::panicking::begin_panic<rustc_errors[18c341fe1ea9d738]::ExplicitBug>::{closure#0}, !>
  15:     0x7f9fb7cf7276 - std[5baa01868b04d1a3]::panicking::begin_panic::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>
  16:     0x7f9fb7cfa9c6 - std[5baa01868b04d1a3]::panic::panic_any::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>
  10:     0x7f2579ac7904 - <rustc_driver[cc2f53293c3db517]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[7784b4547a4f67b7]::ops::function::FnOnce<(&core[7784b4547a4f67b7]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  17:     0x7f9fb71a10c6 - <rustc_errors[18c341fe1ea9d738]::HandlerInner>::flush_delayed::<alloc[d3f7d9336efecc1b]::vec::Vec<rustc_errors[18c341fe1ea9d738]::diagnostic::Diagnostic>, &str>
  11:     0x7f257a884d2d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h11f431d9b74177b9
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2032:9
  12:     0x7f257a884d2d - std::panicking::rust_panic_with_hook::hd8e47e215c6e1b89
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/panicking.rs:692:13
  13:     0x7f2579b00271 - std[5baa01868b04d1a3]::panicking::begin_panic::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>::{closure#0}
  14:     0x7f2579afeb36 - std[5baa01868b04d1a3]::sys_common::backtrace::__rust_end_short_backtrace::<std[5baa01868b04d1a3]::panicking::begin_panic<rustc_errors[18c341fe1ea9d738]::ExplicitBug>::{closure#0}, !>
  15:     0x7f2579af7276 - std[5baa01868b04d1a3]::panicking::begin_panic::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>
  16:     0x7f2579afa9c6 - std[5baa01868b04d1a3]::panic::panic_any::<rustc_errors[18c341fe1ea9d738]::ExplicitBug>
  17:     0x7f6df31a10c6 - <rustc_errors[18c341fe1ea9d738]::HandlerInner>::flush_delayed::<alloc[d3f7d9336efecc1b]::vec::Vec<rustc_errors[18c341fe1ea9d738]::diagnostic::Diagnostic>, &str>
  18:     0x7f9fb71a03cb - <rustc_errors[18c341fe1ea9d738]::HandlerInner as core[7784b4547a4f67b7]::ops::drop::Drop>::drop
  18:     0x7f6df31a03cb - <rustc_errors[18c341fe1ea9d738]::HandlerInner as core[7784b4547a4f67b7]::ops::drop::Drop>::drop
  19:     0x7f6df2ef518e - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_session[b406fd2ad368bf1c]::parse::ParseSess>
  19:     0x7f9fb6ef518e - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_session[b406fd2ad368bf1c]::parse::ParseSess>
  20:     0x7f6df2ee5e4f - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_session[b406fd2ad368bf1c]::session::Session>
  20:     0x7f9fb6ee5e4f - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_session[b406fd2ad368bf1c]::session::Session>
  21:     0x7f6df2ee5b80 - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_interface[8ce952d76720d7f3]::interface::Compiler>
  22:     0x7f6df2ee4c8e - rustc_span[b86697cb2061a584]::with_source_map::<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  21:     0x7f9fb6ee5b80 - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_interface[8ce952d76720d7f3]::interface::Compiler>
  22:     0x7f9fb6ee4c8e - rustc_span[b86697cb2061a584]::with_source_map::<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  23:     0x7f6df2ee45c5 - <scoped_tls[8582b173e1e3b793]::ScopedKey<rustc_span[b86697cb2061a584]::SessionGlobals>>::set::<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>
  23:     0x7f9fb6ee45c5 - <scoped_tls[8582b173e1e3b793]::ScopedKey<rustc_span[b86697cb2061a584]::SessionGlobals>>::set::<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>
  24:     0x7f6df2ee3bb2 - std[5baa01868b04d1a3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8ce952d76720d7f3]::util::run_in_thread_pool_with_globals<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>
  24:     0x7f9fb6ee3bb2 - std[5baa01868b04d1a3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8ce952d76720d7f3]::util::run_in_thread_pool_with_globals<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>
  25:     0x7f6df2ee38c8 - <<std[5baa01868b04d1a3]::thread::Builder>::spawn_unchecked_<rustc_interface[8ce952d76720d7f3]::util::run_in_thread_pool_with_globals<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#1} as core[7784b4547a4f67b7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f6df4a8bf63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2b20690876748913
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2000:9
  27:     0x7f6df4a8bf63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h41a68158edcb5cdd
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2000:9
  28:     0x7f6df4a8bf63 - std::sys::unix::thread::Thread::new::thread_start::ha0be813dd2c37563
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7f9fb6ee38c8 - <<std[5baa01868b04d1a3]::thread::Builder>::spawn_unchecked_<rustc_interface[8ce952d76720d7f3]::util::run_in_thread_pool_with_globals<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#1} as core[7784b4547a4f67b7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f9fb8a8bf63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2b20690876748913
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2000:9
  27:     0x7f9fb8a8bf63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h41a68158edcb5cdd
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2000:9
  28:     0x7f9fb8a8bf63 - std::sys::unix::thread::Thread::new::thread_start::ha0be813dd2c37563
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f6df07068fd - <unknown>
  29:     0x7f9fb47068fd - <unknown>
  30:     0x7f6df0788a60 - <unknown>
  31:                0x0 - <unknown>

  30:     0x7f9fb4788a60 - <unknown>
  31:                0x0 - <unknown>

  17:     0x7f2578fa10c6 - <rustc_errors[18c341fe1ea9d738]::HandlerInner>::flush_delayed::<alloc[d3f7d9336efecc1b]::vec::Vec<rustc_errors[18c341fe1ea9d738]::diagnostic::Diagnostic>, &str>
  18:     0x7f2578fa03cb - <rustc_errors[18c341fe1ea9d738]::HandlerInner as core[7784b4547a4f67b7]::ops::drop::Drop>::drop
  19:     0x7f2578cf518e - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_session[b406fd2ad368bf1c]::parse::ParseSess>
  20:     0x7f2578ce5e4f - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_session[b406fd2ad368bf1c]::session::Session>
  21:     0x7f2578ce5b80 - core[7784b4547a4f67b7]::ptr::drop_in_place::<rustc_interface[8ce952d76720d7f3]::interface::Compiler>
  22:     0x7f2578ce4c8e - rustc_span[b86697cb2061a584]::with_source_map::<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  23:     0x7f2578ce45c5 - <scoped_tls[8582b173e1e3b793]::ScopedKey<rustc_span[b86697cb2061a584]::SessionGlobals>>::set::<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>
  24:     0x7f2578ce3bb2 - std[5baa01868b04d1a3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8ce952d76720d7f3]::util::run_in_thread_pool_with_globals<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>
  25:     0x7f2578ce38c8 - <<std[5baa01868b04d1a3]::thread::Builder>::spawn_unchecked_<rustc_interface[8ce952d76720d7f3]::util::run_in_thread_pool_with_globals<rustc_interface[8ce952d76720d7f3]::interface::run_compiler<core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>, rustc_driver[cc2f53293c3db517]::run_compiler::{closure#1}>::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7784b4547a4f67b7]::result::Result<(), rustc_errors[18c341fe1ea9d738]::ErrorGuaranteed>>::{closure#1} as core[7784b4547a4f67b7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f257a88bf63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2b20690876748913
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2000:9
  27:     0x7f257a88bf63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h41a68158edcb5cdd
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/alloc/src/boxed.rs:2000:9
  28:     0x7f257a88bf63 - std::sys::unix::thread::Thread::new::thread_start::ha0be813dd2c37563
                               at /rustc/c97b539e408ea353f4fde2f9251d598291fec421/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f25765068fd - <unknown>
  30:     0x7f2576588a60 - <unknown>
  31:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (c97b539e4 2022-11-30) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

```

</p>
</details>

**Comment by niklasad1** [comment]
closing duplicate of https://github.com/rust-lang/rust/issues/105009
