### ISSUE TITLE
ICE: -Zunpretty=ast-tree

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#105209]
### Code

```Rust
#![crate_name = { #![crate(_name = { #![crateate_name = )({ #![crate_name = 0}?)
```

### Meta

`rustc --version --verbose`:
```
binary: rustc
commit-hash: 32e613bbaafee1bcabba48a2257b838f8d1c03d3
commit-date: 2022-12-02
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output
`rustc 756a57bf91439a29db72a09edf57b5db532f610e.rs  -Zunpretty=ast-tree`
```
error: this file contains an unclosed delimiter
 --> 756a57bf91439a29db72a09edf57b5db532f610e.rs:1:82
  |
1 | #![crate_name = { #![crate(_name = { #![crateate_name = )({ #![crate_name = 0}?)
  |   -             -   - unclosed delimiter                                         ^
  |   |             |
  |   |             unclosed delimiter
  |   unclosed delimiter

error: expected `]`, found `(`
 --> 756a57bf91439a29db72a09edf57b5db532f610e.rs:1:40
  |
1 | #![crate_name = { #![crate(_name = { #![crateate_name = )({ #![crate_name = 0}?)
  |                                        ^                 ^ help: `]` may belong here
  |                                        |
  |                                        unclosed delimiter

error: expected one of `.`, `;`, `?`, `}`, or an operator, found `]`
 --> 756a57bf91439a29db72a09edf57b5db532f610e.rs:1:3
  |
1 | #![crate_name = { #![crate(_name = { #![crateate_name = )({ #![crate_name = 0}?)
  |   ^                                                                             -^ expected one of `.`, `;`, `?`, `}`, or an operator
  |   |                                                                             |
  |   unclosed delimiter                                                            help: `}` may belong here

error: mismatched closing delimiter: `}`
 --> 756a57bf91439a29db72a09edf57b5db532f610e.rs:1:63
  |
1 | #![crate_name = { #![crate(_name = { #![crateate_name = )({ #![crate_name = 0}?)
  |                                                           -   ^              ^ mismatched closing delimiter
  |                                                           |   |
  |                                                           |   unclosed delimiter
  |                                                           closing delimiter possibly meant for this
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Brace`,
 right: `Bracket`: Mismatched open/close delims: open=Brace close=756a57bf91439a29db72a09edf57b5db532f610e.rs:1:82: 1:82 (#0)', compiler/rustc_parse/src/parser/attr_wrapper.rs:416:17
stack backtrace:
   0:     0x7f408f4d025a - std::backtrace_rs::backtrace::libunwind::trace::h445f1a380ebe24fa
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f408f4d025a - std::backtrace_rs::backtrace::trace_unsynchronized::h8c542444dc84bbad
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f408f4d025a - std::sys_common::backtrace::_print_fmt::hd1e3793b0f95c644
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f408f4d025a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h515025d5c2825d78
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f408f532e4e - core::fmt::write::hfd15a46634ae3152
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f408f4c0675 - std::io::Write::write_fmt::h74b2e38eb2a622bf
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/io/mod.rs:1682:15
   6:     0x7f408f4d0025 - std::sys_common::backtrace::_print::hd2af8aafbe5d4e4d
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f408f4d0025 - std::sys_common::backtrace::print::hc83e0ce2c452dd90
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f408f4d2d6f - std::panicking::default_hook::{{closure}}::h6fa5498814662258
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/panicking.rs:267:22
   9:     0x7f408f4d2aab - std::panicking::default_hook::h27c5cc64dbc8482d
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/panicking.rs:286:9
  10:     0x7f408f4d358c - std::panicking::rust_panic_with_hook::hf0b4a17e8b00f779
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/panicking.rs:688:13
  11:     0x7f408f4d3329 - std::panicking::begin_panic_handler::{{closure}}::hdf74f3a50bd80b74
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/panicking.rs:579:13
  12:     0x7f408f4d070c - std::sys_common::backtrace::__rust_end_short_backtrace::h88bd6095b3fb0016
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7f408f4d3032 - rust_begin_unwind
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/panicking.rs:575:5
  14:     0x7f408f52f863 - core::panicking::panic_fmt::hff0dff09014a656f
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/panicking.rs:64:14
  15:     0x7f408f52fd49 - core::panicking::assert_failed_inner::hd3e1693765fb1921
  16:     0x7f408e9d638c - core[7075224b64f80aa]::panicking::assert_failed::<rustc_ast[a22e29301b1e637b]::token::Delimiter, rustc_ast[a22e29301b1e637b]::token::Delimiter>
  17:     0x7f408d78cba5 - <rustc_parse[d295d82b0ca875e3]::parser::attr_wrapper::LazyAttrTokenStreamImpl as rustc_ast[a22e29301b1e637b]::tokenstream::ToAttrTokenStream>::to_attr_token_stream
  18:     0x7f408decd646 - <rustc_ast[a22e29301b1e637b]::tokenstream::LazyAttrTokenStream as core[7075224b64f80aa]::fmt::Debug>::fmt
  19:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::{{closure}}::hf8fe0d0053d27264
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:317:17
  20:     0x7f408f5303b5 - core::result::Result<T,E>::and_then::h32f081f05c8f6cd1
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  21:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::hc8335cfd7fdc484a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:309:23
  22:     0x7f408f534439 - core::fmt::Formatter::debug_tuple_field1_finish::h22237b5fe171f113
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2139:9
  23:     0x7f408debe8cf - <&core[7075224b64f80aa]::option::Option<rustc_ast[a22e29301b1e637b]::tokenstream::LazyAttrTokenStream> as core[7075224b64f80aa]::fmt::Debug>::fmt
  24:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::{{closure}}::h8b9b321e6eeeb78f
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:134:17
  25:     0x7f408f53015f - core::result::Result<T,E>::and_then::h3fb57e30a746930b
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  26:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::h6a3a6a50f6b4d16a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:124:23
  27:     0x7f408f534249 - core::fmt::Formatter::debug_struct_field5_finish::h5ddfea307202e8b5
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2080:9
  28:     0x7f408deb4c4c - <rustc_ast[a22e29301b1e637b]::ast::Expr as core[7075224b64f80aa]::fmt::Debug>::fmt
  29:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::{{closure}}::hf8fe0d0053d27264
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:317:17
  30:     0x7f408f5303b5 - core::result::Result<T,E>::and_then::h32f081f05c8f6cd1
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  31:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::hc8335cfd7fdc484a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:309:23
  32:     0x7f408f534439 - core::fmt::Formatter::debug_tuple_field1_finish::h22237b5fe171f113
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2139:9
  33:     0x7f408deb5b65 - <rustc_ast[a22e29301b1e637b]::ast::AttrArgsEq as core[7075224b64f80aa]::fmt::Debug>::fmt
  34:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::{{closure}}::hf8fe0d0053d27264
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:317:17
  35:     0x7f408f5303b5 - core::result::Result<T,E>::and_then::h32f081f05c8f6cd1
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  36:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::hc8335cfd7fdc484a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:309:23
  37:     0x7f408f534512 - core::fmt::Formatter::debug_tuple_field2_finish::hf352b8245ad233e4
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2155:9
  38:     0x7f408deb5b0e - <rustc_ast[a22e29301b1e637b]::ast::AttrArgs as core[7075224b64f80aa]::fmt::Debug>::fmt
  39:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::{{closure}}::h8b9b321e6eeeb78f
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:134:17
  40:     0x7f408f53015f - core::result::Result<T,E>::and_then::h3fb57e30a746930b
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  41:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::h6a3a6a50f6b4d16a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:124:23
  42:     0x7f408f533fda - core::fmt::Formatter::debug_struct_field3_finish::h8f71e365666cdf24
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2028:9
  43:     0x7f408deb022d - <&rustc_ast[a22e29301b1e637b]::ast::AttrItem as core[7075224b64f80aa]::fmt::Debug>::fmt
  44:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::{{closure}}::h8b9b321e6eeeb78f
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:134:17
  45:     0x7f408f53015f - core::result::Result<T,E>::and_then::h3fb57e30a746930b
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  46:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::h6a3a6a50f6b4d16a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:124:23
  47:     0x7f408f533ef4 - core::fmt::Formatter::debug_struct_field2_finish::h704003fcfc3c3b8e
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2007:9
  48:     0x7f408deb7c32 - <rustc_ast[a22e29301b1e637b]::ast::NormalAttr as core[7075224b64f80aa]::fmt::Debug>::fmt
  49:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::{{closure}}::hf8fe0d0053d27264
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:317:17
  50:     0x7f408f5303b5 - core::result::Result<T,E>::and_then::h32f081f05c8f6cd1
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  51:     0x7f408f5303b5 - core::fmt::builders::DebugTuple::field::hc8335cfd7fdc484a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:309:23
  52:     0x7f408f534439 - core::fmt::Formatter::debug_tuple_field1_finish::h22237b5fe171f113
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2139:9
  53:     0x7f408deb7bc8 - <rustc_ast[a22e29301b1e637b]::ast::AttrKind as core[7075224b64f80aa]::fmt::Debug>::fmt
  54:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::{{closure}}::h8b9b321e6eeeb78f
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:134:17
  55:     0x7f408f53015f - core::result::Result<T,E>::and_then::h3fb57e30a746930b
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  56:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::h6a3a6a50f6b4d16a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:124:23
  57:     0x7f408f5340b1 - core::fmt::Formatter::debug_struct_field4_finish::hf07d2607b08c97f0
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2050:9
  58:     0x7f408deb7b3a - <rustc_ast[a22e29301b1e637b]::ast::Attribute as core[7075224b64f80aa]::fmt::Debug>::fmt
  59:     0x7f408f530550 - core::fmt::builders::DebugInner::entry::{{closure}}::hfb47500ab706cf89
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:388:17
  60:     0x7f408f530550 - core::result::Result<T,E>::and_then::he9883d2f6d42b83e
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  61:     0x7f408f530550 - core::fmt::builders::DebugInner::entry::hebb76a5dc40e1237
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:380:23
  62:     0x7f408f530589 - core::fmt::builders::DebugSet::entry::h4b06a59f18ca69c8
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:469:9
  63:     0x7f408ded022d - <core[7075224b64f80aa]::fmt::builders::DebugList>::entries::<&rustc_ast[a22e29301b1e637b]::ast::Attribute, core[7075224b64f80aa]::slice::iter::Iter<rustc_ast[a22e29301b1e637b]::ast::Attribute>>
  64:     0x7f408deb1013 - <[rustc_ast[a22e29301b1e637b]::ast::Attribute] as core[7075224b64f80aa]::fmt::Debug>::fmt
  65:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::{{closure}}::h8b9b321e6eeeb78f
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:134:17
  66:     0x7f408f53015f - core::result::Result<T,E>::and_then::h3fb57e30a746930b
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/result.rs:1372:22
  67:     0x7f408f53015f - core::fmt::builders::DebugStruct::field::h6a3a6a50f6b4d16a
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/builders.rs:124:23
  68:     0x7f408f5341c4 - core::fmt::Formatter::debug_struct_field5_finish::h5ddfea307202e8b5
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:2076:9
  69:     0x7f408deb3a5c - <rustc_ast[a22e29301b1e637b]::ast::Crate as core[7075224b64f80aa]::fmt::Debug>::fmt
  70:     0x7f408f532de2 - core::fmt::run::h605f89524cd20615
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:1256:5
  71:     0x7f408f532de2 - core::fmt::write::hfd15a46634ae3152
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:1224:26
  72:     0x7f408f524e6f - core::fmt::Write::write_fmt::hdc96e4833281beff
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/core/src/fmt/mod.rs:192:9
  73:     0x7f408f524e6f - alloc::fmt::format::format_inner::h89ef6cf67ba21d81
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/alloc/src/fmt.rs:612:9
  74:     0x7f408e2b08ed - rustc_driver[1a6385c1c72d16e7]::pretty::print_after_parsing
  75:     0x7f408d3eca10 - <rustc_interface[ee8495dca531fc0c]::interface::Compiler>::enter::<rustc_driver[1a6385c1c72d16e7]::run_compiler::{closure#1}::{closure#2}, core[7075224b64f80aa]::result::Result<core[7075224b64f80aa]::option::Option<rustc_interface[ee8495dca531fc0c]::queries::Linker>, rustc_errors[643e9caaba05b420]::ErrorGuaranteed>>
  76:     0x7f408d3e74e8 - rustc_span[c03eaf4ea18165a3]::with_source_map::<core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>, rustc_interface[ee8495dca531fc0c]::interface::run_compiler<core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>, rustc_driver[1a6385c1c72d16e7]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  77:     0x7f408d3e6fd5 - <scoped_tls[6605aed902b0fb11]::ScopedKey<rustc_span[c03eaf4ea18165a3]::SessionGlobals>>::set::<rustc_interface[ee8495dca531fc0c]::interface::run_compiler<core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>, rustc_driver[1a6385c1c72d16e7]::run_compiler::{closure#1}>::{closure#0}, core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>>
  78:     0x7f408d3e65c2 - std[79527836cf90b5dd]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ee8495dca531fc0c]::util::run_in_thread_pool_with_globals<rustc_interface[ee8495dca531fc0c]::interface::run_compiler<core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>, rustc_driver[1a6385c1c72d16e7]::run_compiler::{closure#1}>::{closure#0}, core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>>
  79:     0x7f408db6b8e8 - <<std[79527836cf90b5dd]::thread::Builder>::spawn_unchecked_<rustc_interface[ee8495dca531fc0c]::util::run_in_thread_pool_with_globals<rustc_interface[ee8495dca531fc0c]::interface::run_compiler<core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>, rustc_driver[1a6385c1c72d16e7]::run_compiler::{closure#1}>::{closure#0}, core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7075224b64f80aa]::result::Result<(), rustc_errors[643e9caaba05b420]::ErrorGuaranteed>>::{closure#1} as core[7075224b64f80aa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  80:     0x7f408f06e5e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb948150b9fd67a86
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/alloc/src/boxed.rs:2000:9
  81:     0x7f408f06e5e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2f842213b427eb19
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/alloc/src/boxed.rs:2000:9
  82:     0x7f408f06e5e3 - std::sys::unix::thread::Thread::new::thread_start::h2adb6f1223042fb8
                               at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library/std/src/sys/unix/thread.rs:108:17
  83:     0x7f408ae9f8fd - <unknown>
  84:     0x7f408af21a60 - <unknown>
  85:                0x0 - <unknown>
error: aborting due to 4 previous errors
```

</p>
</details>

**Comment by jruderman** [comment]
Reduced to:

```
#![c={#![c[)x
```
