### ISSUE TITLE
ICE when passing incorrect parameter to `Path::from`

### ISSUE THREAD

**Issue by fprasx** [rust-lang/rust#105333]
### Code

```Rust
use std::path::Path;

fn main() {
    let p = Path::from(format!("hello"));
}
```
I haven't found this ICE to occur when doing either of: 
```
let p = Path::from("hello");
let p = Path::from(String::from("hello"));
```

### Meta
The bug does not exist on `rustc 1.64.0-nightly (fe3342816 2022-08-01)`. 

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: aarch64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/context.rs:703:13: node_type: no type for node `expr {
                                        let res = $crate::fmt::format($crate::__export::format_args!($($arg)*));
                                        res
                                    } (hir_id=HirId { owner: DefId(0:6 ~ splash_todo[9f65]::main), local_id: 30 })`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
stack backtrace:
   0:        0x10562f670 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2990a6f24ccff6db
   1:        0x105679c34 - core::fmt::write::h91497fd291c8b104
   2:        0x105622604 - std::io::Write::write_fmt::h23fa41342cffacf4
   3:        0x105631eec - std::panicking::default_hook::{{closure}}::hb41cdb784f4c17ac
   4:        0x105631c10 - std::panicking::default_hook::hdfe992d5fb29a991
   5:        0x10d396718 - rustc_driver[250dcea03822790c]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x1056325b0 - std::panicking::rust_panic_with_hook::h2eb0e4b718773521
   7:        0x1110001f4 - std[a5ccfe66677bd8c7]::panicking::begin_panic::<rustc_errors[c8454b970e154417]::ExplicitBug>::{closure#0}
   8:        0x110ffe77c - std[a5ccfe66677bd8c7]::sys_common::backtrace::__rust_end_short_backtrace::<std[a5ccfe66677bd8c7]::panicking::begin_panic<rustc_errors[c8454b970e154417]::ExplicitBug>::{closure#0}, !>
   9:        0x11150af48 - std[a5ccfe66677bd8c7]::panicking::begin_panic::<rustc_errors[c8454b970e154417]::ExplicitBug>
  10:        0x110f63904 - std[a5ccfe66677bd8c7]::panic::panic_any::<rustc_errors[c8454b970e154417]::ExplicitBug>
  11:        0x110f6034c - <rustc_errors[c8454b970e154417]::HandlerInner>::bug::<&alloc[3ba61535766dd904]::string::String>
  12:        0x110f5fc50 - <rustc_errors[c8454b970e154417]::Handler>::bug::<&alloc[3ba61535766dd904]::string::String>
  13:        0x11108c640 - rustc_middle[a5107c7538e61c53]::ty::context::tls::with_context_opt::<rustc_middle[a5107c7538e61c53]::ty::context::tls::with_opt<rustc_middle[a5107c7538e61c53]::util::bug::opt_span_bug_fmt<rustc_span[b9fdb1d50c47c7fe]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  14:        0x111090994 - rustc_middle[a5107c7538e61c53]::util::bug::opt_span_bug_fmt::<rustc_span[b9fdb1d50c47c7fe]::span_encoding::Span>
  15:        0x11150be40 - rustc_middle[a5107c7538e61c53]::util::bug::bug_fmt
  16:        0x11103d0fc - <rustc_middle[a5107c7538e61c53]::ty::context::TypeckResults>::node_type
  17:        0x110d3a1b8 - <rustc_infer[95a93ab5ef712278]::infer::InferCtxt as rustc_trait_selection[20aa6160a2d29e77]::traits::error_reporting::suggestions::InferCtxtExt>::note_obligation_cause_code::<rustc_middle[a5107c7538e61c53]::ty::Predicate>
  18:        0x110d3f964 - <rustc_infer[95a93ab5ef712278]::infer::InferCtxt as rustc_trait_selection[20aa6160a2d29e77]::traits::error_reporting::InferCtxtExt>::report_selection_error
  19:        0x110d4d29c - <rustc_infer[95a93ab5ef712278]::infer::InferCtxt as rustc_trait_selection[20aa6160a2d29e77]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  20:        0x110d3c8e8 - <rustc_infer[95a93ab5ef712278]::infer::InferCtxt as rustc_trait_selection[20aa6160a2d29e77]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  21:        0x10f980640 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
  22:        0x10f983914 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::structurally_resolved_type
  23:        0x10f96bb74 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_call
  24:        0x10f9b8360 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_expr_kind
  25:        0x10f97a07c - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:        0x10f98a298 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_decl
  27:        0x10f98a658 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_stmt
  28:        0x10f98adf8 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  29:        0x10f9b8590 - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_expr_kind
  30:        0x10f97a07c - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:        0x10f97acfc - <rustc_typeck[4423ce6fa4a8f5dd]::check::fn_ctxt::FnCtxt>::check_return_expr
  32:        0x10fa02778 - rustc_typeck[4423ce6fa4a8f5dd]::check::check::check_fn
  33:        0x10fad8b94 - <rustc_infer[95a93ab5ef712278]::infer::InferCtxtBuilder>::enter::<&rustc_middle[a5107c7538e61c53]::ty::context::TypeckResults, <rustc_typeck[4423ce6fa4a8f5dd]::check::inherited::InheritedBuilder>::enter<rustc_typeck[4423ce6fa4a8f5dd]::check::typeck_with_fallback<rustc_typeck[4423ce6fa4a8f5dd]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[a5107c7538e61c53]::ty::context::TypeckResults>::{closure#0}>
  34:        0x10fa5aab0 - rustc_typeck[4423ce6fa4a8f5dd]::check::typeck
  35:        0x11053e64c - <rustc_query_system[376554ccb6bbe62f]::dep_graph::graph::DepGraph<rustc_middle[a5107c7538e61c53]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a5107c7538e61c53]::ty::context::TyCtxt, rustc_span[b9fdb1d50c47c7fe]::def_id::LocalDefId, &rustc_middle[a5107c7538e61c53]::ty::context::TypeckResults>
  36:        0x110316ee4 - rustc_query_system[376554ccb6bbe62f]::query::plumbing::try_execute_query::<rustc_query_impl[ebd438b5e01d582b]::plumbing::QueryCtxt, rustc_query_system[376554ccb6bbe62f]::query::caches::DefaultCache<rustc_span[b9fdb1d50c47c7fe]::def_id::LocalDefId, &rustc_middle[a5107c7538e61c53]::ty::context::TypeckResults>>
  37:        0x1103d6c20 - rustc_query_system[376554ccb6bbe62f]::query::plumbing::get_query::<rustc_query_impl[ebd438b5e01d582b]::queries::typeck, rustc_query_impl[ebd438b5e01d582b]::plumbing::QueryCtxt>
  38:        0x10f9ce0c0 - rustc_data_structures[25d5b65341446d42]::sync::par_for_each_in::<&[rustc_span[b9fdb1d50c47c7fe]::def_id::LocalDefId], <rustc_middle[a5107c7538e61c53]::hir::map::Map>::par_body_owners<rustc_typeck[4423ce6fa4a8f5dd]::check::typeck_item_bodies::{closure#0}>::{closure#0}>
  39:        0x10fa5e780 - rustc_typeck[4423ce6fa4a8f5dd]::check::typeck_item_bodies
  40:        0x11056aa4c - <rustc_query_system[376554ccb6bbe62f]::dep_graph::graph::DepGraph<rustc_middle[a5107c7538e61c53]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a5107c7538e61c53]::ty::context::TyCtxt, (), ()>
  41:        0x11037b0c4 - rustc_query_system[376554ccb6bbe62f]::query::plumbing::try_execute_query::<rustc_query_impl[ebd438b5e01d582b]::plumbing::QueryCtxt, rustc_query_system[376554ccb6bbe62f]::query::caches::DefaultCache<(), ()>>
  42:        0x1103c6130 - rustc_query_system[376554ccb6bbe62f]::query::plumbing::get_query::<rustc_query_impl[ebd438b5e01d582b]::queries::typeck_item_bodies, rustc_query_impl[ebd438b5e01d582b]::plumbing::QueryCtxt>
  43:        0x10fa6dd20 - <rustc_session[d9f8ead3a6f8da8f]::session::Session>::time::<(), rustc_typeck[4423ce6fa4a8f5dd]::check_crate::{closure#7}>
  44:        0x10fb60574 - rustc_typeck[4423ce6fa4a8f5dd]::check_crate
  45:        0x10d4a50f0 - rustc_interface[64ac8d545596c047]::passes::analysis
  46:        0x1105620ec - <rustc_query_system[376554ccb6bbe62f]::dep_graph::graph::DepGraph<rustc_middle[a5107c7538e61c53]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a5107c7538e61c53]::ty::context::TyCtxt, (), core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>
  47:        0x110370000 - rustc_query_system[376554ccb6bbe62f]::query::plumbing::try_execute_query::<rustc_query_impl[ebd438b5e01d582b]::plumbing::QueryCtxt, rustc_query_system[376554ccb6bbe62f]::query::caches::DefaultCache<(), core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>>
  48:        0x1103d702c - rustc_query_system[376554ccb6bbe62f]::query::plumbing::get_query::<rustc_query_impl[ebd438b5e01d582b]::queries::analysis, rustc_query_impl[ebd438b5e01d582b]::plumbing::QueryCtxt>
  49:        0x10d3c7054 - <rustc_interface[64ac8d545596c047]::passes::QueryContext>::enter::<rustc_driver[250dcea03822790c]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>
  50:        0x10d39c1b4 - rustc_interface[64ac8d545596c047]::interface::create_compiler_and_run::<core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>, rustc_driver[250dcea03822790c]::run_compiler::{closure#1}>
  51:        0x10d3ff5e0 - <scoped_tls[1c31aea71029b747]::ScopedKey<rustc_span[b9fdb1d50c47c7fe]::SessionGlobals>>::set::<rustc_interface[64ac8d545596c047]::interface::run_compiler<core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>, rustc_driver[250dcea03822790c]::run_compiler::{closure#1}>::{closure#0}, core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>
  52:        0x10d3cadc8 - std[a5ccfe66677bd8c7]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[64ac8d545596c047]::util::run_in_thread_pool_with_globals<rustc_interface[64ac8d545596c047]::interface::run_compiler<core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>, rustc_driver[250dcea03822790c]::run_compiler::{closure#1}>::{closure#0}, core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>::{closure#0}, core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>
  53:        0x10d3cdc4c - <<std[a5ccfe66677bd8c7]::thread::Builder>::spawn_unchecked_<rustc_interface[64ac8d545596c047]::util::run_in_thread_pool_with_globals<rustc_interface[64ac8d545596c047]::interface::run_compiler<core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>, rustc_driver[250dcea03822790c]::run_compiler::{closure#1}>::{closure#0}, core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>::{closure#0}, core[75a5a00debbb3d3d]::result::Result<(), rustc_errors[c8454b970e154417]::ErrorGuaranteed>>::{closure#1} as core[75a5a00debbb3d3d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:        0x10563a428 - std::sys::unix::thread::Thread::new::thread_start::hf682c03d0f237892
  55:        0x1bb4b026c - __pthread_deallocate

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/context.rs:703:13: node_type: no type for node `expr {
                                        let res = $crate::fmt::format($crate::__export::format_args!($($arg)*));
                                        res
                                    } (hir_id=HirId { owner: DefId(0:6 ~ splash_todo[9f65]::main), local_id: 30 })`

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_middle::ty::context::TypeckResults>::node_type
   8: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::suggestions::InferCtxtExt>::note_obligation_cause_code::<rustc_middle::ty::Predicate>
   9: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_selection_error
  10: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  11: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  12: <rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
  13: <rustc_typeck::check::fn_ctxt::FnCtxt>::structurally_resolved_type
  14: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  15: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  16: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  17: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_decl
  18: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  19: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  20: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  21: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  23: rustc_typeck::check::check::check_fn
  24: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
  25: rustc_typeck::check::typeck
  26: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  28: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck, rustc_query_impl::plumbing::QueryCtxt>
  29: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_typeck::check::typeck_item_bodies::{closure#0}>::{closure#0}>
  30: rustc_typeck::check::typeck_item_bodies
  31: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  32: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  33: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
  34: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
  35: rustc_typeck::check_crate
  36: rustc_interface::passes::analysis
  37: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  38: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  39: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  40: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  41: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  42: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by JohnTitor** [comment]
Closing as duplicate, thank you for reporting!
