### ISSUE TITLE
`for` syntax loops wrong times

### ISSUE THREAD

**Issue by sugiura-hiromichi** [rust-lang/rust#105407]
I tried this code:

```rust
#[derive(PartialEq, Eq, Clone, Debug,)]
pub struct ListNode {
	pub val:  i32,
	pub next: Option<Box<ListNode,>,>,
}

impl ListNode {
	#[inline]
	fn new(val: i32,) -> Self { ListNode { next: None, val, } }
}

impl Solution {
	pub fn reverse_k_group(head: Option<Box<ListNode,>,>, k: i32,) -> Option<Box<ListNode,>,> {
		if k == 1 {
			return head;
		} else if k == 2 {
			return swap_pairs(head,);
		}
		// NOTE: make sure that k > 2 from here

		let mut l_kth = &head;
		// detect (k-1)th node from head
		for _ in 2..k {
			println!("l_kth: {l_kth:?}");
			l_kth =  &l_kth.as_ref().unwrap().next;// ERROR OCCURS HERE
			if l_kth.is_none() {
				return head;
			}
		}
//....
```

I expected to see this happen: I set three test cases like this

```rust
#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_1() {
		let mut ans = ary_to_list(&[2, 1, 4, 3, 5,],);
		let mut sol = Solution::reverse_k_group(ary_to_list(&[1, 2, 3, 4, 5,],), 2,);
		assert_eq!(ans, sol);
	}

	#[test]
	fn test_2() {
		let mut ans = ary_to_list(&[3, 2, 1, 4, 5,],);
		let mut sol = Solution::reverse_k_group(ary_to_list(&[1, 2, 3, 4, 5,],), 3,);
		assert_eq!(ans, sol);
	}

	#[test]
	fn test_3() {
		let mut ans = ary_to_list(&[3, 2, 1,],);
		let mut sol = Solution::reverse_k_group(ary_to_list(&[1, 2, 3,],), 3,);
		assert_eq!(ans, sol);
	}

	fn ary_to_list(ary: &[i32],) -> Option<Box<ListNode,>,> {
		if ary.is_empty() {
			None
		} else {
			Some(Box::new(ListNode { val: ary[0], next: ary_to_list(&ary[1..],), },),)
		}
	}

	fn arys_to_lists(arys: Vec<&[i32],>,) -> Vec<Option<Box<ListNode,>,>,> {
		arys.iter().map(|&a| ary_to_list(a,),).collect()
	}
}
```

I expected to pass all tests.

Instead, this happened: Only test_3 fails.  
Here is `cargo t` output:
```
cargo t
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running unittests src/main.rs (target/debug/deps/leet_code-7f4542e82408fff9)

running 3 tests
test tests::test_2 ... ok
test tests::test_1 ... ok
test tests::test_3 ... FAILED

failures:

---- tests::test_3 stdout ----
l_kth: Some(ListNode { val: 1, next: Some(ListNode { val: 2, next: Some(ListNode { val: 3, next: None }) }) })
l_kth: None
thread 'tests::test_3' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:28:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_3

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--bin leet_code`
```

It seems for loop trying to loops more than two times where should be one.

### Meta

`rustc --version --verbose`:
```
rustc -V -v
rustc 1.67.0-nightly (b28d30e1e 2022-12-06)
binary: rustc
commit-hash: b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339
commit-date: 2022-12-06
host: aarch64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

<details><summary>Backtrace</summary>
<p>

```
RUST_BACKTRACE=1 cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/main.rs (target/debug/deps/leet_code-7f4542e82408fff9)

running 3 tests
test tests::test_1 ... ok
test tests::test_2 ... ok
test tests::test_3 ... FAILED

failures:

---- tests::test_3 stdout ----
l_kth: Some(ListNode { val: 1, next: Some(ListNode { val: 2, next: Some(ListNode { val: 3, next: None }) }) })
l_kth: None
thread 'tests::test_3' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:28:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/option.rs:778:21
   4: leet_code::Solution::reverse_k_group
             at ./src/main.rs:28:13
   5: leet_code::Solution::reverse_k_group
             at ./src/main.rs:45:4
   6: leet_code::tests::test_3
             at ./src/main.rs:91:17
   7: leet_code::tests::test_3::{{closure}}
             at ./src/main.rs:89:14
   8: core::ops::function::FnOnce::call_once
             at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/ops/function.rs:507:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/b28d30e1e3c2b90fd08b7dd79d8e63884d1e0339/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::test_3

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--bin leet_code`
```

</p>
</details>

**Comment by sugiura-hiromichi** [comment]
I'm currently use `match` like this and works fine

```rust
for _ in 2..k {
//before————————————————————————-
                        &l_kth.as_ref().unwrap().next;
			if l_kth.is_none() {
				return head;
			}
//-—————————————————————————————-
//after——————————————————————————
			l_kth = match l_kth.as_ref() {
				None => return head,
				Some(n,) => &n.next,
			}
		}
//-—————————————————————————————-
```

**Comment by Nilstrieb** [comment]
Thank you for your report. Could you post a fully runnable example or try to minimize your code?
