### ISSUE TITLE
thread 'rustc' panicked at 'Box<dyn Any> src\lib.rs:1560:9

### ISSUE THREAD

**Issue by cannero** [rust-lang/rust#105574]
The problem happened after I forgot to add a comma in a `println` statement on the nightly toolchain. With `rustc 1.63.0` the correct compiler error message is shown.
Could it be related to the msvc toolchain? On play.rust-lang.org the error message is not shown.

### Code

```Rust
fn main() {
    let months:i64 = 3;
    let (year, month) = (23 as i32, 3 as u32);
    let total = (year * 12) + (month as i32) - (months as i32 - 1);
    let (year, month) = ((total / 12), (total % 12) as u32);
    //missing comma
    println!("{}/{}"year,month); 
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (70f8737b2 2022-11-23)
binary: rustc
commit-hash: 70f8737b2f5d3bf7d6b784fad00b663b7ff9feda
commit-date: 2022-11-23
host: x86_64-pc-windows-msvc
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output

```
error: internal compiler error: /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda\compiler\rustc_middle\src\ty\visit.rs:103:17: expect tcx.sess.has_errors return true

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/70f8737b2f5d3bf7d6b784fad00b663b7ff9feda\compiler\rustc_errors\src\lib.rs:1560:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ffccfc69c92 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hba918c05c494276d
   1:     0x7ffccfca5ecb - core::fmt::write::h326ba0b5cc9122c1
   2:     0x7ffccfc5c7ca - <std::io::IoSlice as core::fmt::Debug>::fmt::h6a4545c6311d842e
   3:     0x7ffccfc699db - std::sys::common::alloc::realloc_fallback::h441738d96ae97ae9
   4:     0x7ffccfc6d119 - std::panicking::default_hook::h059832ce6832360a
   5:     0x7ffccfc6cd74 - std::panicking::default_hook::h059832ce6832360a
   6:     0x7ffcbf40273d - rustc_driver[8a5b5a72b896b5e6]::describe_lints
   7:     0x7ffccfc6da64 - std::panicking::rust_panic_with_hook::hde7217c92e4e1ec9
   8:     0x7ffcc170e073 - <rustc_middle[8ccecfea3e20d9bb]::ty::rvalue_scopes::RvalueScopes as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
   9:     0x7ffcc170a8a9 - <rustc_middle[8ccecfea3e20d9bb]::ty::rvalue_scopes::RvalueScopes as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
  10:     0x7ffcc174a919 - <rustc_middle[8ccecfea3e20d9bb]::ty::consts::int::CharTryFromScalarInt as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
  11:     0x7ffcc170a899 - <rustc_middle[8ccecfea3e20d9bb]::ty::rvalue_scopes::RvalueScopes as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
  12:     0x7ffcc1708870 - <rustc_middle[8ccecfea3e20d9bb]::ty::rvalue_scopes::RvalueScopes as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
  13:     0x7ffcc1708382 - <rustc_middle[8ccecfea3e20d9bb]::ty::rvalue_scopes::RvalueScopes as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
  14:     0x7ffcc1737fe8 - <&rustc_middle[8ccecfea3e20d9bb]::ty::list::List<rustc_middle[8ccecfea3e20d9bb]::ty::Ty> as rustc_middle[8ccecfea3e20d9bb]::ty::context::Lift>::lift_to_tcx
  15:     0x7ffcc17381d8 - rustc_middle[8ccecfea3e20d9bb]::util::bug::bug_fmt
  16:     0x7ffcc1738155 - rustc_middle[8ccecfea3e20d9bb]::util::bug::bug_fmt
  17:     0x7ffcbe57b19f - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::demand_coerce
  18:     0x7ffcbe5aeda7 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::probe_instantiate_query_response
  19:     0x7ffcbe547f68 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::check_call
  20:     0x7ffcbe573190 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::demand_coerce
  21:     0x7ffcbe5c0a66 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::check_struct_path
  22:     0x7ffcbe573356 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::demand_coerce
  23:     0x7ffcbe5c0a66 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::check_struct_path
  24:     0x7ffcbe573356 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::demand_coerce
  25:     0x7ffcbe587ed0 - <rustc_hir_typeck[e817f4f3c763c366]::fn_ctxt::FnCtxt>::demand_coerce
  26:     0x7ffcbe606d02 - <rustc_hir_typeck[e817f4f3c763c366]::inherited::Inherited>::build
  27:     0x7ffcbe5fd591 - <rustc_hir_typeck[e817f4f3c763c366]::inherited::Inherited>::build
  28:     0x7ffcbe53d917 - <rustc_hir_typeck[e817f4f3c763c366]::UnsafetyState>::recurse
  29:     0x7ffcbd60ca19 - <rustc_const_eval[86aaf24324239c20]::transform::validate::TypeChecker as rustc_middle[8ccecfea3e20d9bb]::mir::visit::Visitor>::visit_local
  30:     0x7ffcbd690885 - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7ffcbedc6b6b - <rustc_span[88404fc4168a9801]::def_id::DefId as rustc_serialize[803e00b07b971f36]::serialize::Encodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheEncoder>>::encode
  32:     0x7ffcbece23e6 - <rustc_query_impl[61c4e929323091bc]::Queries as rustc_middle[8ccecfea3e20d9bb]::ty::query::QueryEngine>::as_any
  33:     0x7ffcbe541375 - <rustc_hir_typeck[e817f4f3c763c366]::UnsafetyState>::recurse
  34:     0x7ffcbd303a71 - <rustc_hir_typeck[e817f4f3c763c366]::diverges::Diverges as core[25e9f914b1fbf8b]::ops::bit::BitAnd>::bitand
  35:     0x7ffcbd60e6af - <rustc_const_eval[86aaf24324239c20]::transform::validate::TypeChecker as rustc_middle[8ccecfea3e20d9bb]::mir::visit::Visitor>::visit_local
  36:     0x7ffcbd6b5ce6 - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7ffcbd797143 - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  38:     0x7ffcbd7ce216 - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  39:     0x7ffcbd3b89ea - <rustc_hir_analysis[c5c63f73555c096f]::collect::lifetimes::LifetimeContext as rustc_hir[e0f2077dd4561613]::intravisit::Visitor>::visit_trait_item
  40:     0x7ffcbd357133 - rustc_hir_analysis[c5c63f73555c096f]::check_crate
  41:     0x7ffcbcc37b45 - rustc_interface[74763efee9dee92]::passes::analysis
  42:     0x7ffcbd60e18f - <rustc_const_eval[86aaf24324239c20]::transform::validate::TypeChecker as rustc_middle[8ccecfea3e20d9bb]::mir::visit::Visitor>::visit_local
  43:     0x7ffcbd6b05c9 - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7ffcbd785fb0 - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7ffcbd7d5f2a - <alloc[b257067f30cc9b6e]::vec::Vec<u8> as rustc_serialize[803e00b07b971f36]::serialize::Decodable<rustc_query_impl[61c4e929323091bc]::on_disk_cache::CacheDecoder>>::decode
  46:     0x7ffcbcbfa804 - rustc_driver[8a5b5a72b896b5e6]::args::arg_expand_all
  47:     0x7ffcbcbfc5d6 - <rustc_middle[8ccecfea3e20d9bb]::ty::SymbolName as core[25e9f914b1fbf8b]::fmt::Debug>::fmt
  48:     0x7ffcbcbfb8d0 - rustc_driver[8a5b5a72b896b5e6]::args::arg_expand_all
  49:     0x7ffcbcbec2e9 - <unknown>
  50:     0x7ffcbcbe398d - <unknown>
  51:     0x7ffccfc7fd2c - std::sys::windows::thread::Thread::new::h8aefa68e81a1514b
  52:     0x7ffd3aa074b4 - BaseThreadInitThunk
  53:     0x7ffd3c8c26a1 - RtlUserThreadStart
```

</p>
</details>

**Comment by compiler-errors** [comment]
Please update your nightly toolchain with `rustup update` or however you acquire your rust versions.
