### ISSUE TITLE
Region parameter out of range when substituting in region 'a (index=1, substs = ['_#22r])

### ISSUE THREAD

**Issue by kothanzaw** [rust-lang/rust#105519]
```
Compiling shadowsocks v1.15.0 (/home/ktz/Desktop/ShadowSocks/shadowsocks-android/core/src/main/rust/shadowsocks-rust/crates/shadowsocks)
   Compiling shadowsocks-service v1.15.0 (/home/ktz/Desktop/ShadowSocks/shadowsocks-android/core/src/main/rust/shadowsocks-rust/crates/shadowsocks-service)
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:741:13: Region parameter out of range when substituting in region 'a (index=1, substs = ['_#22r])

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/compiler/rustc_errors/src/lib.rs:1576:9
stack backtrace:
internal compiler error: compiler/rustc_middle/src/ty/subst.rs:741:13: Region parameter out of range when substituting in region 'a (index=1, substs = ['_#22r])

   0:     0x7fcdfb47de9a - std::backtrace_rs::backtrace::libunwind::trace::hd10eda5ab6cb4cdc
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fcdfb47de9a - std::backtrace_rs::backtrace::trace_unsynchronized::hc2d933a1d87136b7
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fcdfb47de9a - std::sys_common::backtrace::_print_fmt::hbc6e39d05cece0e1
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fcdfb47de9a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4e096cc08b8f7ff2
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fcdf740a25e - core::fmt::write::hc749f618e420865d
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/core/src/fmt/mod.rs:1208:17
   5:     0x7fcdfb471db5 - std::io::Write::write_fmt::hcc30ae83ad852555
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/io/mod.rs:1682:15
   6:     0x7fcdfb47dc65 - std::sys_common::backtrace::_print::h959485d45136857a
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fcdfb47dc65 - std::sys_common::backtrace::print::h0230b8f1225098e1
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fcdfb47ffef - std::panicking::default_hook::{{closure}}::h8a33a3e829ffa1d9
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/panicking.rs:267:22
   9:     0x7fcdfb47fd2b - std::panicking::default_hook::hf47ea80dd34c42c2
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/panicking.rs:286:9
  10:     0x7fcdfa6d38f1 - <rustc_driver[a56d989e388971fc]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[295bdcd7e201aec9]::ops::function::FnOnce<(&core[295bdcd7e201aec9]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7fcdfb4807ed - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha49d1e0959d16196
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/alloc/src/boxed.rs:2032:9
  12:     0x7fcdfb4807ed - std::panicking::rust_panic_with_hook::h35768f1f6cd02ad1
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/panicking.rs:692:13
  13:     0x7fcdfab5cd31 - std[9caeed11b21f461c]::panicking::begin_panic::<rustc_errors[a151aa0c6b700682]::ExplicitBug>::{closure#0}
  14:     0x7fcdfab5c7b6 - std[9caeed11b21f461c]::sys_common::backtrace::__rust_end_short_backtrace::<std[9caeed11b21f461c]::panicking::begin_panic<rustc_errors[a151aa0c6b700682]::ExplicitBug>::{closure#0}, !>
  15:     0x7fcdfab96156 - std[9caeed11b21f461c]::panicking::begin_panic::<rustc_errors[a151aa0c6b700682]::ExplicitBug>
  16:     0x7fcdfab5aa26 - std[9caeed11b21f461c]::panic::panic_any::<rustc_errors[a151aa0c6b700682]::ExplicitBug>
  17:     0x7fcdfab58d76 - <rustc_errors[a151aa0c6b700682]::HandlerInner>::bug::<&alloc[101a34d45fdb044a]::string::String>
  18:     0x7fcdfab589e0 - <rustc_errors[a151aa0c6b700682]::Handler>::bug::<&alloc[101a34d45fdb044a]::string::String>
  19:     0x7fcdfab3a7ce - rustc_middle[a177af8518e4397e]::ty::context::tls::with_context_opt::<rustc_middle[a177af8518e4397e]::ty::context::tls::with_opt<rustc_middle[a177af8518e4397e]::util::bug::opt_span_bug_fmt<rustc_span[408aba7b93829b91]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7fcdfab3bc36 - rustc_middle[a177af8518e4397e]::util::bug::opt_span_bug_fmt::<rustc_span[408aba7b93829b91]::span_encoding::Span>
  21:     0x7fcdf8a3f413 - rustc_middle[a177af8518e4397e]::util::bug::bug_fmt
  22:     0x7fcdfab8db21 - <rustc_middle[a177af8518e4397e]::ty::subst::SubstFolder as rustc_middle[a177af8518e4397e]::ty::fold::TypeFolder>::fold_region::region_param_out_of_range
  23:     0x7fcdf86bef9d - <rustc_middle[a177af8518e4397e]::ty::generics::GenericPredicates>::instantiate_into
  24:     0x7fcdf8cc7f5a - <rustc_trait_selection[5c6c94d56278c00f]::traits::wf::WfPredicates>::nominal_obligations_inner
  25:     0x7fcdf8cc5e0a - <rustc_trait_selection[5c6c94d56278c00f]::traits::wf::WfPredicates>::compute
  26:     0x7fcdf8a09a79 - <rustc_trait_selection[5c6c94d56278c00f]::traits::fulfill::FulfillProcessor as rustc_data_structures[998337cd75c5adc6]::obligation_forest::ObligationProcessor>::process_obligation
  27:     0x7fcdf8a0717e - <rustc_data_structures[998337cd75c5adc6]::obligation_forest::ObligationForest<rustc_trait_selection[5c6c94d56278c00f]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[5c6c94d56278c00f]::traits::fulfill::FulfillProcessor>
  28:     0x7fcdf8a06c38 - <rustc_trait_selection[5c6c94d56278c00f]::traits::fulfill::FulfillmentContext as rustc_infer[60fda011af17f16c]::traits::engine::TraitEngine>::select_where_possible
  29:     0x7fcdf992b045 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::try_find_coercion_lub::<rustc_hir[ae6e3cba56b624a8]::hir::Arm>
  30:     0x7fcdf893aee3 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  31:     0x7fcdf88bce7f - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7fcdf890d6e4 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_block_with_expected
  33:     0x7fcdf88bf567 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7fcdf893aa62 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  35:     0x7fcdf88bce7f - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  36:     0x7fcdf891059a - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_decl
  37:     0x7fcdf88bf849 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  38:     0x7fcdf88bcfc9 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  39:     0x7fcdf890d6e4 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_block_with_expected
  40:     0x7fcdf88bad69 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  41:     0x7fcdf893aa62 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  42:     0x7fcdf88bce7f - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  43:     0x7fcdf890d7e0 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_block_with_expected
  44:     0x7fcdf88bad69 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  45:     0x7fcdf88bd35b - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  46:     0x7fcdf890d7e0 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_block_with_expected
  47:     0x7fcdf88bad69 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  48:     0x7fcdf88a5fd3 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_return_expr
  49:     0x7fcdf889d730 - rustc_hir_typeck[b7384ac53cef7d21]::check::check_fn
  50:     0x7fcdf895a608 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_closure
  51:     0x7fcdf88bed9d - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  52:     0x7fcdf89e9917 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_argument_types
  53:     0x7fcdf9a26807 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_call
  54:     0x7fcdf88ba965 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  55:     0x7fcdf88a5fd3 - <rustc_hir_typeck[b7384ac53cef7d21]::fn_ctxt::FnCtxt>::check_return_expr
  56:     0x7fcdf889d730 - rustc_hir_typeck[b7384ac53cef7d21]::check::check_fn
  57:     0x7fcdf8888842 - <rustc_hir_typeck[b7384ac53cef7d21]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[b7384ac53cef7d21]::typeck_with_fallback<rustc_hir_typeck[b7384ac53cef7d21]::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[a177af8518e4397e]::ty::context::TypeckResults>
  58:     0x7fcdf887b181 - rustc_hir_typeck[b7384ac53cef7d21]::typeck
  59:     0x7fcdf88855fc - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::LocalDefId, &rustc_middle[a177af8518e4397e]::ty::context::TypeckResults>
  60:     0x7fcdf88798f1 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::VecCache<rustc_span[408aba7b93829b91]::def_id::LocalDefId, &rustc_middle[a177af8518e4397e]::ty::context::TypeckResults>>
  61:     0x7fcdfa07b2cc - <rustc_query_impl[441135ee144544b6]::Queries as rustc_middle[a177af8518e4397e]::ty::query::QueryEngine>::typeck
  62:     0x7fcdf910ca59 - rustc_mir_build[19677bafc8c14c15]::thir::cx::thir_body
  63:     0x7fcdf97169df - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, core[295bdcd7e201aec9]::result::Result<(&rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::thir::Thir>, rustc_middle[a177af8518e4397e]::thir::ExprId), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>
  64:     0x7fcdf970e1c6 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::DefaultCache<rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, core[295bdcd7e201aec9]::result::Result<(&rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::thir::Thir>, rustc_middle[a177af8518e4397e]::thir::ExprId), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>>
  65:     0x7fcdf970645e - rustc_mir_build[19677bafc8c14c15]::build::mir_built
  66:     0x7fcdf93fcf1e - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, &rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::mir::Body>>
  67:     0x7fcdf93fb781 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::DefaultCache<rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, &rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::mir::Body>>>
  68:     0x7fcdf8fa087d - rustc_mir_transform[78ed1c0e4930349]::check_unsafety::unsafety_check_result
  69:     0x7fcdfa048e15 - <rustc_mir_transform[78ed1c0e4930349]::check_unsafety::provide::{closure#0} as core[295bdcd7e201aec9]::ops::function::FnOnce<(rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::LocalDefId)>>::call_once
  70:     0x7fcdf8f9faac - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::LocalDefId, &rustc_middle[a177af8518e4397e]::mir::query::UnsafetyCheckResult>
  71:     0x7fcdf8f9d220 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::VecCache<rustc_span[408aba7b93829b91]::def_id::LocalDefId, &rustc_middle[a177af8518e4397e]::mir::query::UnsafetyCheckResult>>
  72:     0x7fcdf9837064 - rustc_mir_transform[78ed1c0e4930349]::mir_const
  73:     0x7fcdf93fcf1e - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, &rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::mir::Body>>
  74:     0x7fcdf93fb781 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::DefaultCache<rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, &rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::mir::Body>>>
  75:     0x7fcdf8bf78a4 - rustc_mir_transform[78ed1c0e4930349]::mir_promoted
  76:     0x7fcdf9438d9f - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, (&rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::mir::Body>, &rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_index[38468d88891b7cf7]::vec::IndexVec<rustc_middle[a177af8518e4397e]::mir::Promoted, rustc_middle[a177af8518e4397e]::mir::Body>>)>
  77:     0x7fcdf943771c - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::DefaultCache<rustc_middle[a177af8518e4397e]::ty::WithOptConstParam<rustc_span[408aba7b93829b91]::def_id::LocalDefId>, (&rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_middle[a177af8518e4397e]::mir::Body>, &rustc_data_structures[998337cd75c5adc6]::steal::Steal<rustc_index[38468d88891b7cf7]::vec::IndexVec<rustc_middle[a177af8518e4397e]::mir::Promoted, rustc_middle[a177af8518e4397e]::mir::Body>>)>>
  78:     0x7fcdf94358cf - rustc_borrowck[1e34f6bae5b3962b]::mir_borrowck
  79:     0x7fcdf94352a5 - <rustc_borrowck[1e34f6bae5b3962b]::provide::{closure#0} as core[295bdcd7e201aec9]::ops::function::FnOnce<(rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::LocalDefId)>>::call_once
  80:     0x7fcdf973098c - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::LocalDefId, &rustc_middle[a177af8518e4397e]::mir::query::BorrowCheckResult>
  81:     0x7fcdf972f69c - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::VecCache<rustc_span[408aba7b93829b91]::def_id::LocalDefId, &rustc_middle[a177af8518e4397e]::mir::query::BorrowCheckResult>>
  82:     0x7fcdfa07b69a - <rustc_query_impl[441135ee144544b6]::Queries as rustc_middle[a177af8518e4397e]::ty::query::QueryEngine>::mir_borrowck
  83:     0x7fcdf9ecd175 - rustc_hir_analysis[946444d136c80aed]::collect::type_of::type_of
  84:     0x7fcdf8fe80c3 - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::DefId, rustc_middle[a177af8518e4397e]::ty::Ty>
  85:     0x7fcdf8fe5e90 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::get_query::<rustc_query_impl[441135ee144544b6]::queries::type_of, rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt>
  86:     0x7fcdf97f0a18 - rustc_hir_analysis[946444d136c80aed]::check::check::check_mod_item_types
  87:     0x7fcdf9209b2c - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, rustc_span[408aba7b93829b91]::def_id::LocalDefId, ()>
  88:     0x7fcdf9207a3e - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::VecCache<rustc_span[408aba7b93829b91]::def_id::LocalDefId, ()>>
  89:     0x7fcdf9a8dbc3 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::get_query::<rustc_query_impl[441135ee144544b6]::queries::check_mod_item_types, rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt>
  90:     0x7fcdf9d42c45 - <rustc_middle[a177af8518e4397e]::hir::map::Map>::for_each_module::<rustc_hir_analysis[946444d136c80aed]::check_crate::{closure#6}::{closure#0}>
  91:     0x7fcdf8ba2a32 - rustc_hir_analysis[946444d136c80aed]::check_crate
  92:     0x7fcdf8ba267b - rustc_interface[c8c7d65f4d7c863b]::passes::analysis
  93:     0x7fcdf9e81daf - <rustc_query_system[ddabab1eafb597f0]::dep_graph::graph::DepGraph<rustc_middle[a177af8518e4397e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[a177af8518e4397e]::ty::context::TyCtxt, (), core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>
  94:     0x7fcdf9e80ea7 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::try_execute_query::<rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt, rustc_query_system[ddabab1eafb597f0]::query::caches::DefaultCache<(), core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>>
  95:     0x7fcdf9e80900 - rustc_query_system[ddabab1eafb597f0]::query::plumbing::get_query::<rustc_query_impl[441135ee144544b6]::queries::analysis, rustc_query_impl[441135ee144544b6]::plumbing::QueryCtxt>
  96:     0x7fcdf9855cad - <rustc_interface[c8c7d65f4d7c863b]::passes::QueryContext>::enter::<rustc_driver[a56d989e388971fc]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>
  97:     0x7fcdf985237e - <rustc_interface[c8c7d65f4d7c863b]::interface::Compiler>::enter::<rustc_driver[a56d989e388971fc]::run_compiler::{closure#1}::{closure#2}, core[295bdcd7e201aec9]::result::Result<core[295bdcd7e201aec9]::option::Option<rustc_interface[c8c7d65f4d7c863b]::queries::Linker>, rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>
  98:     0x7fcdf984d358 - rustc_span[408aba7b93829b91]::with_source_map::<core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>, rustc_interface[c8c7d65f4d7c863b]::interface::run_compiler<core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>, rustc_driver[a56d989e388971fc]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  99:     0x7fcdf984ce45 - <scoped_tls[c17d4fcbe085de89]::ScopedKey<rustc_span[408aba7b93829b91]::SessionGlobals>>::set::<rustc_interface[c8c7d65f4d7c863b]::interface::run_compiler<core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>, rustc_driver[a56d989e388971fc]::run_compiler::{closure#1}>::{closure#0}, core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>
 100:     0x7fcdf984c432 - std[9caeed11b21f461c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c8c7d65f4d7c863b]::util::run_in_thread_pool_with_globals<rustc_interface[c8c7d65f4d7c863b]::interface::run_compiler<core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>, rustc_driver[a56d989e388971fc]::run_compiler::{closure#1}>::{closure#0}, core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>
 101:     0x7fcdf9f84518 - <<std[9caeed11b21f461c]::thread::Builder>::spawn_unchecked_<rustc_interface[c8c7d65f4d7c863b]::util::run_in_thread_pool_with_globals<rustc_interface[c8c7d65f4d7c863b]::interface::run_compiler<core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>, rustc_driver[a56d989e388971fc]::run_compiler::{closure#1}>::{closure#0}, core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[295bdcd7e201aec9]::result::Result<(), rustc_errors[a151aa0c6b700682]::ErrorGuaranteed>>::{closure#1} as core[295bdcd7e201aec9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 102:     0x7fcdfb487b33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0e5495d7a0467227
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/alloc/src/boxed.rs:2000:9
 103:     0x7fcdfb487b33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf2dc136765fe433b
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/alloc/src/boxed.rs:2000:9
 104:     0x7fcdfb487b33 - std::sys::unix::thread::Thread::new::thread_start::h249747de8b82cef9
                               at /rustc/7632db0e87d8adccc9a83a47795c9411b1455855/library/std/src/sys/unix/thread.rs:108:17
 105:     0x7fcdf726b609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
 106:     0x7fcdf718e133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 107:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (7632db0e8 2022-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C linker=/home/ktz/Desktop/ShadowSocks/shadowsocks-android/build/linker-wrapper/linker-wrapper.sh -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed`
#1 [thir_body] building THIR for `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed`
#2 [mir_built] building MIR for `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed`
#3 [unsafety_check_result] unsafety-checking `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed`
#4 [mir_const] preparing `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed` for borrow checking
#5 [mir_promoted] processing MIR for `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed`
#6 [mir_borrowck] borrow-checking `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed`
#7 [type_of] computing type of `acl::<impl at crates/shadowsocks-service/src/acl/mod.rs:327:1: 327:19>::check_target_bypassed::{opaque#0}`
#8 [check_mod_item_types] checking item types in module `acl`
#9 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `shadowsocks-service`
could not compile `shadowsocks-service`
```

**Comment by compiler-errors** [comment]
I think this was fixed
