### ISSUE TITLE
Internal compiler error on rustc 1.68.0 nightly using rocket framework

### ISSUE THREAD

**Issue by ras-drive** [rust-lang/rust#105818]
This only occurred while running a CI test with Docker

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (9c07efe84 2022-12-16) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:969:13: failed to get layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>`: unable to determine layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` cannot be normalized

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0:     0x7fb253e0ed5a - std::backtrace_rs::backtrace::libunwind::trace::hf3e23dba944728e7
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fb253e0ed5a - std::backtrace_rs::backtrace::trace_unsynchronized::ha7a661dbe14f9bec
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb253e0ed5a - std::sys_common::backtrace::_print_fmt::h8bb3e793399a1d31
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fb253e0ed5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f001b4156af7ff0
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fb24fd9b36e - core::fmt::write::h98c67bacb0ad9cb8
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/core/src/fmt/mod.rs:1208:17
   5:     0x7fb253e02e35 - std::io::Write::write_fmt::h21d43ee83b8bf3da
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/io/mod.rs:1682:15
   6:     0x7fb253e0eb25 - std::sys_common::backtrace::_print::hed3e659c4722fff2
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fb253e0eb25 - std::sys_common::backtrace::print::hf3af686623d05885
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fb253e10eaf - std::panicking::default_hook::{{closure}}::hfbc532e2813a4fd8
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/panicking.rs:267:22
   9:     0x7fb253e10beb - std::panicking::default_hook::hf22d9a6bedeb8cbb
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/panicking.rs:286:9
  10:     0x7fb25303a351 - rustc_driver[8203396c4671b89c]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fb253e116ad - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h839d8563a5defb2f
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/alloc/src/boxed.rs:2032:9
  12:     0x7fb253e116ad - std::panicking::rust_panic_with_hook::h2e7c62506c5adf89
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/panicking.rs:692:13
  13:     0x7fb252ed2e41 - std[fecc2c98d64c5e20]::panicking::begin_panic::<rustc_errors[6c86e693eff69e36]::ExplicitBug>::{closure#0}
  14:     0x7fb252ed2616 - std[fecc2c98d64c5e20]::sys_common::backtrace::__rust_end_short_backtrace::<std[fecc2c98d64c5e20]::panicking::begin_panic<rustc_errors[6c86e693eff69e36]::ExplicitBug>::{closure#0}, !>
  15:     0x7fb252e6c846 - std[fecc2c98d64c5e20]::panicking::begin_panic::<rustc_errors[6c86e693eff69e36]::ExplicitBug>
  16:     0x7fb252ed2436 - std[fecc2c98d64c5e20]::panic::panic_any::<rustc_errors[6c86e693eff69e36]::ExplicitBug>
  17:     0x7fb252ecf689 - <rustc_errors[6c86e693eff69e36]::HandlerInner>::span_bug::<rustc_span[b683b297262634fe]::span_encoding::Span, &alloc[4e38580f0181725e]::string::String>
  18:     0x7fb252ecf2f0 - <rustc_errors[6c86e693eff69e36]::Handler>::span_bug::<rustc_span[b683b297262634fe]::span_encoding::Span, &alloc[4e38580f0181725e]::string::String>
  19:     0x7fb252ed27b9 - rustc_middle[46166420d424f8d9]::ty::context::tls::with_context_opt::<rustc_middle[46166420d424f8d9]::ty::context::tls::with_opt<rustc_middle[46166420d424f8d9]::util::bug::opt_span_bug_fmt<rustc_span[b683b297262634fe]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7fb252ed2546 - rustc_middle[46166420d424f8d9]::util::bug::opt_span_bug_fmt::<rustc_span[b683b297262634fe]::span_encoding::Span>
  21:     0x7fb2517376c4 - rustc_middle[46166420d424f8d9]::util::bug::span_bug_fmt::<rustc_span[b683b297262634fe]::span_encoding::Span>
  22:     0x7fb252e762f2 - <rustc_codegen_llvm[30227101449b2fe9]::context::CodegenCx as rustc_middle[46166420d424f8d9]::ty::layout::LayoutOfHelpers>::handle_layout_err
  23:     0x7fb252e72e51 - <rustc_codegen_llvm[30227101449b2fe9]::context::CodegenCx as rustc_middle[46166420d424f8d9]::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
  24:     0x7fb252e75d4a - <rustc_codegen_llvm[30227101449b2fe9]::context::CodegenCx as rustc_middle[46166420d424f8d9]::ty::layout::LayoutOf>::layout_of
  25:     0x7fb252e6b356 - <rustc_codegen_ssa[b132c7f3e732167f]::mir::place::PlaceRef<&rustc_codegen_llvm[30227101449b2fe9]::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>
  26:     0x7fb25173b2f9 - <rustc_codegen_ssa[b132c7f3e732167f]::mir::FunctionCx<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>>::codegen_place
  27:     0x7fb251717130 - <rustc_codegen_ssa[b132c7f3e732167f]::mir::FunctionCx<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>>::codegen_block
  28:     0x7fb2517040d7 - rustc_codegen_ssa[b132c7f3e732167f]::mir::codegen_mir::<rustc_codegen_llvm[30227101449b2fe9]::builder::Builder>
  29:     0x7fb2524f6af6 - rustc_codegen_llvm[30227101449b2fe9]::base::compile_codegen_unit::module_codegen
  30:     0x7fb2526ca66c - <rustc_query_system[b2d3787a6eb3f954]::dep_graph::graph::DepGraph<rustc_middle[46166420d424f8d9]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[46166420d424f8d9]::ty::context::TyCtxt, rustc_span[b683b297262634fe]::symbol::Symbol, rustc_codegen_ssa[b132c7f3e732167f]::ModuleCodegen<rustc_codegen_llvm[30227101449b2fe9]::ModuleLlvm>>
  31:     0x7fb2526ca13e - <rustc_codegen_llvm[30227101449b2fe9]::LlvmCodegenBackend as rustc_codegen_ssa[b132c7f3e732167f]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  32:     0x7fb2526c7a22 - rustc_codegen_ssa[b132c7f3e732167f]::base::codegen_crate::<rustc_codegen_llvm[30227101449b2fe9]::LlvmCodegenBackend>
  33:     0x7fb2526c71c9 - <rustc_codegen_llvm[30227101449b2fe9]::LlvmCodegenBackend as rustc_codegen_ssa[b132c7f3e732167f]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7fb2522c38b1 - <rustc_session[23982924e285e106]::session::Session>::time::<alloc[4e38580f0181725e]::boxed::Box<dyn core[4c48bf2e04a135c7]::any::Any>, rustc_interface[3feed755d27e3616]::passes::start_codegen::{closure#0}>
  35:     0x7fb2522c33d9 - rustc_interface[3feed755d27e3616]::passes::start_codegen
  36:     0x7fb2522c10d6 - <rustc_interface[3feed755d27e3616]::passes::QueryContext>::enter::<<rustc_interface[3feed755d27e3616]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[4c48bf2e04a135c7]::result::Result<alloc[4e38580f0181725e]::boxed::Box<dyn core[4c48bf2e04a135c7]::any::Any>, rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  37:     0x7fb2522be586 - <rustc_interface[3feed755d27e3616]::queries::Queries>::ongoing_codegen
  38:     0x7fb2522bdaa7 - <rustc_interface[3feed755d27e3616]::interface::Compiler>::enter::<rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}::{closure#2}, core[4c48bf2e04a135c7]::result::Result<core[4c48bf2e04a135c7]::option::Option<rustc_interface[3feed755d27e3616]::queries::Linker>, rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  39:     0x7fb2522b8a88 - rustc_span[b683b297262634fe]::with_source_map::<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  40:     0x7fb2522b8575 - <scoped_tls[b4ee55afb72dd1f]::ScopedKey<rustc_span[b683b297262634fe]::SessionGlobals>>::set::<rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  41:     0x7fb2522b7b62 - std[fecc2c98d64c5e20]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3feed755d27e3616]::util::run_in_thread_pool_with_globals<rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>
  42:     0x7fb2528f81fe - <<std[fecc2c98d64c5e20]::thread::Builder>::spawn_unchecked_<rustc_interface[3feed755d27e3616]::util::run_in_thread_pool_with_globals<rustc_interface[3feed755d27e3616]::interface::run_compiler<core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>, rustc_driver[8203396c4671b89c]::run_compiler::{closure#1}>::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c48bf2e04a135c7]::result::Result<(), rustc_errors[6c86e693eff69e36]::ErrorGuaranteed>>::{closure#1} as core[4c48bf2e04a135c7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7fb253e18923 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha40757527af5f65d
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/alloc/src/boxed.rs:2000:9
  44:     0x7fb253e18923 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf5bd55cd4ab92745
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/alloc/src/boxed.rs:2000:9
  45:     0x7fb253e18923 - std::sys::unix::thread::Thread::new::thread_start::h087de3b4a94ba02b
                               at /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7fb24fa8fb43 - <unknown>
  47:     0x7fb24fb20bb4 - __clone
  48:                0x0 - <unknown>
```

</p>
</details>

**Comment by trevyn** [comment]
Probably a dupe of #105809

**Comment by jackh726** [comment]
Closing as duplicate.
