### ISSUE TITLE
Panic compiling simple rocket application with rustc 1.68.0-nightly

### ISSUE THREAD

**Issue by d-ufrik** [rust-lang/rust#105934]
### Code main..rs

``#[macro_use] extern crate rocket;

#[get("/")]
fn say_hello() -> &'static str {
    "hello"
}

#[launch]

fn rocket() -> _ {
    rocket::build().mount("/api",routes![say_hello])
}
```


### Meta
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (935dc0721 2022-12-19)
binary: rustc
commit-hash: 935dc07218b4bf6e20231e44eb9263b612fd649b
commit-date: 2022-12-19
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6

```

### Error output

```
 cargo build                                                                                                                                                                                                  ─╯
   Compiling version_check v0.9.4
   Compiling libc v0.2.138
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.49
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling typenum v1.16.0
   Compiling pin-project-lite v0.2.9
   Compiling memchr v2.5.0
   Compiling futures-channel v0.3.25
   Compiling futures-core v0.3.25
   Compiling subtle v2.4.1
   Compiling bytes v1.3.0
   Compiling itoa v1.0.5
   Compiling serde_derive v1.0.151
   Compiling log v0.4.17
   Compiling pin-utils v0.1.0
   Compiling serde v1.0.151
   Compiling once_cell v1.16.0
   Compiling yansi v0.5.1
   Compiling cpufeatures v0.2.5
   Compiling fnv v1.0.7
   Compiling httparse v1.8.0
   Compiling futures-task v0.3.25
   Compiling tracing-core v0.1.30
   Compiling futures-sink v0.3.25
   Compiling hashbrown v0.12.3
   Compiling futures-util v0.3.25
   Compiling try-lock v0.2.3
   Compiling opaque-debug v0.3.0
   Compiling futures-io v0.3.25
   Compiling generic-array v0.14.6
   Compiling proc-macro2-diagnostics v0.9.1
   Compiling http v0.2.8
   Compiling slab v0.4.7
   Compiling tokio v1.23.0
   Compiling ppv-lite86 v0.2.17
   Compiling tracing v0.1.37
   Compiling time-core v0.1.0
   Compiling time-macros v0.2.6
   Compiling indexmap v1.9.2
   Compiling cookie v0.16.2
   Compiling ref-cast v1.0.14
   Compiling tower-service v0.3.2
   Compiling smallvec v1.10.0
   Compiling httpdate v1.0.2
   Compiling inlinable_string v0.1.15
   Compiling getrandom v0.2.8
   Compiling socket2 v0.4.7
   Compiling num_cpus v1.14.0
   Compiling mio v0.8.5
   Compiling signal-hook-registry v1.4.0
   Compiling rand_core v0.6.4
   Compiling uncased v0.9.7
   Compiling base64 v0.20.0
   Compiling percent-encoding v2.2.0
   Compiling bitflags v1.3.2
   Compiling want v0.3.0
   Compiling stable-pattern v0.1.0
   Compiling rand_chacha v0.3.1
   Compiling http-body v0.4.5
   Compiling num-traits v0.2.15
   Compiling lock_api v0.4.9
   Compiling state v0.5.3
   Compiling rand v0.8.5
   Compiling either v1.8.0
   Compiling parking_lot_core v0.9.5
   Compiling encoding_rs v0.8.31
   Compiling num-integer v0.1.45
   Compiling atomic v0.5.1
   Compiling figment v0.10.8
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.3
   Compiling inout v0.1.3
   Compiling multer v2.0.4
   Compiling scopeguard v1.1.0
   Compiling serde_json v1.0.91
   Compiling digest v0.10.6
   Compiling universal-hash v0.5.0
   Compiling aead v0.5.1
   Compiling async-trait v0.1.60
   Compiling cipher v0.4.3
   Compiling polyval v0.6.0
   Compiling rocket v0.5.0-rc.2
   Compiling spin v0.9.4
   Compiling ctr v0.9.2
   Compiling ghash v0.5.0
   Compiling hmac v0.12.1
   Compiling aes v0.8.2
   Compiling time v0.3.17
   Compiling sha2 v0.10.6
   Compiling remove_dir_all v0.5.3
   Compiling glob v0.3.0
   Compiling mime v0.3.16
   Compiling hkdf v0.12.3
   Compiling unicode-xid v0.2.4
   Compiling fastrand v1.8.0
   Compiling ryu v1.0.12
   Compiling parking_lot v0.12.1
   Compiling time v0.1.45
   Compiling atty v0.2.14
   Compiling iana-time-zone v0.1.53
   Compiling binascii v0.1.4
   Compiling tempfile v3.3.0
   Compiling aes-gcm v0.10.1
   Compiling futures v0.3.25
   Compiling chrono v0.4.23
   Compiling hyper v0.14.23
   Compiling devise_core v0.3.1
   Compiling tokio-macros v1.8.2
   Compiling pear_codegen v0.2.3
   Compiling ref-cast-impl v1.0.14
   Compiling devise_codegen v0.3.1
   Compiling async-stream-impl v0.3.3
   Compiling async-stream v0.3.3
   Compiling devise v0.3.1
   Compiling pear v0.2.3
   Compiling rocket_http v0.5.0-rc.2
   Compiling rocket_codegen v0.5.0-rc.2
   Compiling tokio-util v0.7.4
   Compiling tokio-stream v0.1.11
   Compiling toml v0.5.10
   Compiling ubyte v0.10.3
   Compiling h2 v0.3.15
   Compiling rocket-get-post-webserver v0.1.0 (/home/dvd/dev/ufrik-rust/rocket-get-post-webserver)
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:971:13: failed to get layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>`: unable to determine layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` cannot be normalized

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0:     0x7f9c0a49aa7a - std::backtrace_rs::backtrace::libunwind::trace::h06c3ddb908575635
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f9c0a49aa7a - std::backtrace_rs::backtrace::trace_unsynchronized::h8bfc3753e1cc3345
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9c0a49aa7a - std::sys_common::backtrace::_print_fmt::h3c304feda98d6679
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f9c0a49aa7a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98af9289a7a29dc2
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f9c0a4fd7ae - core::fmt::write::h02538848739b7e2a
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f9c0a48af45 - std::io::Write::write_fmt::h4aac2f2c3f0128af
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/io/mod.rs:1682:15
   6:     0x7f9c0a49a845 - std::sys_common::backtrace::_print::h2e2acfe71f2fdb67
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f9c0a49a845 - std::sys_common::backtrace::print::h5bf077c253fab052
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f9c0a49d58f - std::panicking::default_hook::{{closure}}::h0ceeeedebdf177d0
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:267:22
   9:     0x7f9c0a49d2cb - std::panicking::default_hook::h7d6f04e84940bd1d
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:286:9
  10:     0x7f9c0d775511 - rustc_driver[3622bb61b1ebe64a]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f9c0a49ddcd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc60f5ae29562b326
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2032:9
  12:     0x7f9c0a49ddcd - std::panicking::rust_panic_with_hook::hce0f8648dbfb386b
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:692:13
  13:     0x7f9c0d608a81 - std[688abfdbcfe52504]::panicking::begin_panic::<rustc_errors[19d12f94925af316]::ExplicitBug>::{closure#0}
  14:     0x7f9c0d608156 - std[688abfdbcfe52504]::sys_common::backtrace::__rust_end_short_backtrace::<std[688abfdbcfe52504]::panicking::begin_panic<rustc_errors[19d12f94925af316]::ExplicitBug>::{closure#0}, !>
  15:     0x7f9c0d5a1b46 - std[688abfdbcfe52504]::panicking::begin_panic::<rustc_errors[19d12f94925af316]::ExplicitBug>
  16:     0x7f9c0d605376 - std[688abfdbcfe52504]::panic::panic_any::<rustc_errors[19d12f94925af316]::ExplicitBug>
  17:     0x7f9c0d605299 - <rustc_errors[19d12f94925af316]::HandlerInner>::span_bug::<rustc_span[ea560f4838c45ec0]::span_encoding::Span, &alloc[b02cc7237b8b6455]::string::String>
  18:     0x7f9c0d604f00 - <rustc_errors[19d12f94925af316]::Handler>::span_bug::<rustc_span[ea560f4838c45ec0]::span_encoding::Span, &alloc[b02cc7237b8b6455]::string::String>
  19:     0x7f9c0d6083d9 - rustc_middle[f828bfe4cd5e1a59]::ty::context::tls::with_context_opt::<rustc_middle[f828bfe4cd5e1a59]::ty::context::tls::with_opt<rustc_middle[f828bfe4cd5e1a59]::util::bug::opt_span_bug_fmt<rustc_span[ea560f4838c45ec0]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7f9c0d608276 - rustc_middle[f828bfe4cd5e1a59]::util::bug::opt_span_bug_fmt::<rustc_span[ea560f4838c45ec0]::span_encoding::Span>
  21:     0x7f9c0bec4694 - rustc_middle[f828bfe4cd5e1a59]::util::bug::span_bug_fmt::<rustc_span[ea560f4838c45ec0]::span_encoding::Span>
  22:     0x7f9c0d5abcc2 - <rustc_codegen_llvm[74aa7289b70d0100]::context::CodegenCx as rustc_middle[f828bfe4cd5e1a59]::ty::layout::LayoutOfHelpers>::handle_layout_err
  23:     0x7f9c0d5a8801 - <rustc_codegen_llvm[74aa7289b70d0100]::context::CodegenCx as rustc_middle[f828bfe4cd5e1a59]::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
  24:     0x7f9c0d5ab6fa - <rustc_codegen_llvm[74aa7289b70d0100]::context::CodegenCx as rustc_middle[f828bfe4cd5e1a59]::ty::layout::LayoutOf>::layout_of
  25:     0x7f9c0d5a0b06 - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::place::PlaceRef<&rustc_codegen_llvm[74aa7289b70d0100]::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>
  26:     0x7f9c0bec8c39 - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::FunctionCx<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>>::codegen_place
  27:     0x7f9c0bea44f8 - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::FunctionCx<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>>::codegen_block
  28:     0x7f9c0be92207 - rustc_codegen_ssa[cc351e334a9b8a56]::mir::codegen_mir::<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>
  29:     0x7f9c0cc44d16 - rustc_codegen_llvm[74aa7289b70d0100]::base::compile_codegen_unit::module_codegen
  30:     0x7f9c0ce1b25c - <rustc_query_system[ffa0917f108ec877]::dep_graph::graph::DepGraph<rustc_middle[f828bfe4cd5e1a59]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f828bfe4cd5e1a59]::ty::context::TyCtxt, rustc_span[ea560f4838c45ec0]::symbol::Symbol, rustc_codegen_ssa[cc351e334a9b8a56]::ModuleCodegen<rustc_codegen_llvm[74aa7289b70d0100]::ModuleLlvm>>
  31:     0x7f9c0ce1ae37 - <rustc_codegen_llvm[74aa7289b70d0100]::LlvmCodegenBackend as rustc_codegen_ssa[cc351e334a9b8a56]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  32:     0x7f9c0ce18883 - rustc_codegen_ssa[cc351e334a9b8a56]::base::codegen_crate::<rustc_codegen_llvm[74aa7289b70d0100]::LlvmCodegenBackend>
  33:     0x7f9c0ce18029 - <rustc_codegen_llvm[74aa7289b70d0100]::LlvmCodegenBackend as rustc_codegen_ssa[cc351e334a9b8a56]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7f9c0ca0c481 - <rustc_session[951b5ce950426db2]::session::Session>::time::<alloc[b02cc7237b8b6455]::boxed::Box<dyn core[62c015fcd585be4a]::any::Any>, rustc_interface[299971c75fff0058]::passes::start_codegen::{closure#0}>
  35:     0x7f9c0ca0bfa9 - rustc_interface[299971c75fff0058]::passes::start_codegen
  36:     0x7f9c0ca09ca6 - <rustc_interface[299971c75fff0058]::passes::QueryContext>::enter::<<rustc_interface[299971c75fff0058]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[62c015fcd585be4a]::result::Result<alloc[b02cc7237b8b6455]::boxed::Box<dyn core[62c015fcd585be4a]::any::Any>, rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  37:     0x7f9c0ca07156 - <rustc_interface[299971c75fff0058]::queries::Queries>::ongoing_codegen
  38:     0x7f9c0ca06677 - <rustc_interface[299971c75fff0058]::interface::Compiler>::enter::<rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}::{closure#2}, core[62c015fcd585be4a]::result::Result<core[62c015fcd585be4a]::option::Option<rustc_interface[299971c75fff0058]::queries::Linker>, rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  39:     0x7f9c0ca01658 - rustc_span[ea560f4838c45ec0]::with_source_map::<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  40:     0x7f9c0ca01145 - <scoped_tls[6f6de2f0677d8068]::ScopedKey<rustc_span[ea560f4838c45ec0]::SessionGlobals>>::set::<rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  41:     0x7f9c0ca00732 - std[688abfdbcfe52504]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[299971c75fff0058]::util::run_in_thread_pool_with_globals<rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  42:     0x7f9c0d038aba - <<std[688abfdbcfe52504]::thread::Builder>::spawn_unchecked_<rustc_interface[299971c75fff0058]::util::run_in_thread_pool_with_globals<rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>::{closure#1} as core[62c015fcd585be4a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7f9c0a4a7dc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h16c8b1a5112fc07f
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
  44:     0x7f9c0a4a7dc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0cc5ff4fc4b4dcff
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
  45:     0x7f9c0a4a7dc3 - std::sys::unix::thread::Thread::new::thread_start::ha7c6dff74603472f
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7f9c0a1d1b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  47:     0x7f9c0a263a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  48:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (935dc0721 2022-12-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rocket-get-post-webserver`

```

<!--
Include a backtrace in the code block by setting `RUST_BACKTRACE=1` in your
environment. E.g. `RUST_BACKTRACE=1 cargo build`.
-->
<details><summary><strong>Backtrace</strong></summary>
<p>

```
RUST_BACKTRACE=1 cargo build                                                                                                                                                                                 ─╯
   Compiling rocket-get-post-webserver v0.1.0 (/home/dvd/dev/ufrik-rust/rocket-get-post-webserver)
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:971:13: failed to get layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>`: unable to determine layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` cannot be normalized

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
   3: <rustc_errors::Handler>::span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::LayoutOfHelpers>::handle_layout_err
   8: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
   9: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::LayoutOf>::layout_of
  10: <rustc_codegen_ssa::mir::place::PlaceRef<&rustc_codegen_llvm::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm::builder::Builder>
  11: <rustc_codegen_ssa::mir::FunctionCx<rustc_codegen_llvm::builder::Builder>>::codegen_place
  12: <rustc_codegen_ssa::mir::FunctionCx<rustc_codegen_llvm::builder::Builder>>::codegen_block
  13: rustc_codegen_ssa::mir::codegen_mir::<rustc_codegen_llvm::builder::Builder>
  14: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  15: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::symbol::Symbol, rustc_codegen_ssa::ModuleCodegen<rustc_codegen_llvm::ModuleLlvm>>
  16: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  17: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  18: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  19: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  20: rustc_interface::passes::start_codegen
  21: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  22: <rustc_interface::queries::Queries>::ongoing_codegen
  23: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  24: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  25: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (935dc0721 2022-12-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rocket-get-post-webserver`

```

</p>
</details>

**Comment by d-ufrik** [comment]
Excellent, Thank you.

Sorry about the duplicate
