### ISSUE TITLE
google.github.io/comprehensive-rust thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3'

### ISSUE THREAD

**Issue by LLyaudet** [rust-lang/rust#106222]
Hello,

I tried this code:

```rust
fn main() {
    let array = [10, 20, 30];
    print!("Iterating over array:");
    for n in array {
        print!(" {n}");
    }
    println!();

    print!("Iterating over range:");
    for i in 0..4 {
        print!(" {}", array[i]);
    }
    println!();
}
```

which is a one digit modification of the exercise there : https://google.github.io/comprehensive-rust/exercises/day-1/for-loops.html

I expected to see this happen:
a nice compiler error at time of build

Instead, this happened:
a nice crash report at execution
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.17s
     Running `target/debug/playground`
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', src/main.rs:11:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Iterating over array: 10 20 30
Iterating over range: 10 20 30

Since there is no conditional at all between creation of array and loop definition,
I thought Rust would catch it.
(Well, technically there may be conditionals in print macros.)
I did it first on the website but I reproduced directly on my machine,
and here are the outputs from my machine.

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.6

```

<details><summary>Backtrace</summary>
<p>

```
RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/exercise`
Iterating over array: 10 20 30
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', src/main.rs:11:23
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-zmPChZ/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-zmPChZ/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /build/rustc-zmPChZ/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:84:5
   3: exercise::main
             at ./src/main.rs:11:23
   4: core::ops::function::FnOnce::call_once
             at /build/rustc-zmPChZ/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Iterating over range: 10 20 30
```

</p>
</details>

**Comment by chenyukang** [comment]
Seems LLVM will optimize it:
![image](https://user-images.githubusercontent.com/230646/209964611-13fb8285-6867-4abf-8935-57145b0228a4.png)

Theoretically, we can find it in static analysis phase, since there is no conditionals in loop.
I guess there are some other reasons...

**Comment by clubby789** [comment]
There is an `unconditional_panic` lint which tries to catch guaranteed panics, but it relies on constant propagation in MIR so it's somewhat limited and seems to not be able to look through iteration. LLVM is much better at this sort of thing

@rustbot label +C-enhancement
