### ISSUE TITLE
error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:1012:9: no MIR available for DefId(54:55 ~ tracing_core[c7b0]::callsite::{impl#1}::set_interest)

### ISSUE THREAD

**Issue by ropoctl** [rust-lang/rust#106344]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (574b64a97 2022-12-31)
binary: rustc
commit-hash: 574b64a97f52162f965bc201e47f0af8279ca65d
commit-date: 2022-12-31
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Error output

```
note: the compiler unexpectedly panicked. this is a bug.



note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md



note: rustc 1.68.0-nightly (574b64a97 2022-12-31) running on x86_64-unknown-linux-gnu



note: compiler flags: --crate-type rlib -C relocation-model=pic



note: some of the compiler flags provided by cargo are hidden



query stack during panic:

#0 [collect_and_partition_mono_items] collect_and_partition_mono_items

#1 [exported_symbols] collecting exported symbols for crate `0`

end of query stack

error: aborting due to 12 previous errors
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/compiler/rustc_errors/src/lib.rs:1581:9

stack backtrace:

   0:     0x7f8de8b2c2ba - std::backtrace_rs::backtrace::libunwind::trace::h58220cc92d95af9d

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5

   1:     0x7f8de8b2c2ba - std::backtrace_rs::backtrace::trace_unsynchronized::h5baad1b6045f1862

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5

   2:     0x7f8de8b2c2ba - std::sys_common::backtrace::_print_fmt::h00cd15ad313be7cd

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:65:5

   3:     0x7f8de8b2c2ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha3c10c2df3801f2e

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:44:22

   4:     0x7f8de8b8f3be - core::fmt::write::h15687caa14f55ffa

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/fmt/mod.rs:1208:17

   5:     0x7f8de8b1c865 - std::io::Write::write_fmt::h9b3ae37b79923fd4

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/io/mod.rs:1682:15

   6:     0x7f8de8b2c085 - std::sys_common::backtrace::_print::hec732d08a877f27f

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:47:5

   7:     0x7f8de8b2c085 - std::sys_common::backtrace::print::h21a7b69d4e96b04e

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:34:9

   8:     0x7f8de8b2ee4f - std::panicking::default_hook::{{closure}}::h4dd038b046e67fff

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:267:22

   9:     0x7f8de8b2eb8b - std::panicking::default_hook::h09d820041cd6bd93

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:286:9

  10:     0x7f8debe0b114 - rustc_driver[7a1e5a3798cd51b2]::DEFAULT_HOOK::{closure#0}::{closure#0}

  11:     0x7f8de8b2f68d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he092a4fd9b28e6e1

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:2002:9

  12:     0x7f8de8b2f68d - std::panicking::rust_panic_with_hook::he7925d19e6d87b9f

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:692:13

  13:     0x7f8dec2bb021 - std[eb796f4691fa113e]::panicking::begin_panic::<rustc_errors[d698377914337e8]::ExplicitBug>::{closure#0}

  14:     0x7f8dec2ba896 - std[eb796f4691fa113e]::sys_common::backtrace::__rust_end_short_backtrace::<std[eb796f4691fa113e]::panicking::begin_panic<rustc_errors[d698377914337e8]::ExplicitBug>::{closure#0}, !>

  15:     0x7f8dec292c76 - std[eb796f4691fa113e]::panicking::begin_panic::<rustc_errors[d698377914337e8]::ExplicitBug>

  16:     0x7f8dec2ba6d6 - std[eb796f4691fa113e]::panic::panic_any::<rustc_errors[d698377914337e8]::ExplicitBug>

  17:     0x7f8dec2b79b6 - <rustc_errors[d698377914337e8]::HandlerInner>::bug::<&alloc[f127cc518e7b321d]::string::String>

  18:     0x7f8dec2b75d0 - <rustc_errors[d698377914337e8]::Handler>::bug::<&alloc[f127cc518e7b321d]::string::String>

  19:     0x7f8dec2a2e5e - rustc_middle[6135c93de258c3da]::ty::context::tls::with_context_opt::<rustc_middle[6135c93de258c3da]::ty::context::tls::with_opt<rustc_middle[6135c93de258c3da]::util::bug::opt_span_bug_fmt<rustc_span[9ec51286058a4e72]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>

  20:     0x7f8dec2a4726 - rustc_middle[6135c93de258c3da]::util::bug::opt_span_bug_fmt::<rustc_span[9ec51286058a4e72]::span_encoding::Span>

  21:     0x7f8dea050833 - rustc_middle[6135c93de258c3da]::util::bug::bug_fmt

  22:     0x7f8deb02d5c8 - rustc_monomorphize[55ab131fc76041a0]::collector::should_codegen_locally

  23:     0x7f8dead82b4c - rustc_monomorphize[55ab131fc76041a0]::collector::collect_miri

  24:     0x7f8dead82af9 - rustc_monomorphize[55ab131fc76041a0]::collector::collect_miri

  25:     0x7f8dead82dd5 - rustc_monomorphize[55ab131fc76041a0]::collector::collect_miri

  26:     0x7f8dead6df3f - rustc_monomorphize[55ab131fc76041a0]::collector::collect_items_rec

  27:     0x7f8dead6d039 - rustc_monomorphize[55ab131fc76041a0]::collector::collect_items_rec

  28:     0x7f8deb21a0c2 - <rustc_session[20c634f2fa5fd3a]::session::Session>::time::<(), rustc_monomorphize[55ab131fc76041a0]::collector::collect_crate_mono_items::{closure#1}>

  29:     0x7f8deb219c04 - rustc_monomorphize[55ab131fc76041a0]::collector::collect_crate_mono_items

  30:     0x7f8deb2186f2 - rustc_monomorphize[55ab131fc76041a0]::partitioning::collect_and_partition_mono_items

  31:     0x7f8deb5ac022 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::try_execute_query::<rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_query_system[f2a92cc454341fcf]::query::caches::DefaultCache<(), (&std[eb796f4691fa113e]::collections::hash::set::HashSet<rustc_span[9ec51286058a4e72]::def_id::DefId, core[4db15884ec6b3fd6]::hash::BuildHasherDefault<rustc_hash[13694375fcc62fe6]::FxHasher>>, &[rustc_middle[6135c93de258c3da]::mir::mono::CodegenUnit])>>

  32:     0x7f8deb5abce4 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::get_query::<rustc_query_impl[892151da123d024f]::queries::collect_and_partition_mono_items, rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>

  33:     0x7f8deb5abc1e - <rustc_query_impl[892151da123d024f]::Queries as rustc_middle[6135c93de258c3da]::ty::query::QueryEngine>::collect_and_partition_mono_items

  34:     0x7f8deb5f14d3 - rustc_codegen_ssa[8b7f9559fa6d4cf7]::back::symbol_export::exported_symbols_provider_local

  35:     0x7f8deaedcd28 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::try_execute_query::<rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_query_system[f2a92cc454341fcf]::query::caches::VecCache<rustc_span[9ec51286058a4e72]::def_id::CrateNum, &[(rustc_middle[6135c93de258c3da]::middle::exported_symbols::ExportedSymbol, rustc_middle[6135c93de258c3da]::middle::exported_symbols::SymbolExportInfo)]>>

  36:     0x7f8deaedc980 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::get_query::<rustc_query_impl[892151da123d024f]::queries::exported_symbols, rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>

  37:     0x7f8deb0d4555 - <rustc_metadata[a81e1566ec24aed6]::rmeta::encoder::EncodeContext>::encode_crate_root

  38:     0x7f8deb06735d - rustc_metadata[a81e1566ec24aed6]::rmeta::encoder::encode_metadata_impl

  39:     0x7f8deb0634ae - rustc_data_structures[41d81d1908663610]::sync::join::<rustc_metadata[a81e1566ec24aed6]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[a81e1566ec24aed6]::rmeta::encoder::encode_metadata::{closure#1}, (), ()>

  40:     0x7f8deb0631b1 - rustc_metadata[a81e1566ec24aed6]::rmeta::encoder::encode_metadata

  41:     0x7f8deb062492 - rustc_metadata[a81e1566ec24aed6]::fs::encode_and_write_metadata

  42:     0x7f8deb0572ce - rustc_interface[921e14e9b1939ae4]::passes::start_codegen

  43:     0x7f8deb055036 - <rustc_interface[921e14e9b1939ae4]::passes::QueryContext>::enter::<<rustc_interface[921e14e9b1939ae4]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<alloc[f127cc518e7b321d]::boxed::Box<dyn core[4db15884ec6b3fd6]::any::Any>, rustc_errors[d698377914337e8]::ErrorGuaranteed>>

  44:     0x7f8deb051956 - <rustc_interface[921e14e9b1939ae4]::queries::Queries>::ongoing_codegen

  45:     0x7f8deb050748 - rustc_span[9ec51286058a4e72]::with_source_map::<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>

  46:     0x7f8deb048a45 - <scoped_tls[c0301d1e58d7cd39]::ScopedKey<rustc_span[9ec51286058a4e72]::SessionGlobals>>::set::<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>

  47:     0x7f8deb048032 - std[eb796f4691fa113e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[921e14e9b1939ae4]::util::run_in_thread_pool_with_globals<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>

  48:     0x7f8deb047dda - <<std[eb796f4691fa113e]::thread::Builder>::spawn_unchecked_<rustc_interface[921e14e9b1939ae4]::util::run_in_thread_pool_with_globals<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#1} as core[4db15884ec6b3fd6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}

  49:     0x7f8de8b39b43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h547009b1980571ef

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:1988:9

  50:     0x7f8de8b39b43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h47c8551d74ce8d22

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:1988:9

  51:     0x7f8de8b39b43 - std::sys::unix::thread::Thread::new::thread_start::he79de38213da15ab

                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys/unix/thread.rs:108:17

  52:     0x7f8de89f1ea7 - start_thread

                               at ./nptl/./nptl/pthread_create.c:477:8

  53:     0x7f8de8911a2f - __clone

                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

  54:                0x0 - <unknown>```

</p>
</details>

**Comment by Nilstrieb** [comment]
Thank you for your report. Can you share the original code that triggered the issue? If not, could you try to minimize it into a sharable reproducible example?

**Comment by pnkfelix** [comment]
If we cannot get more detail (as in sample code) from @ropoctl  , I'm not sure we can do anything to address this. I'm inclined to close this as non-actionable unless we get more information we can act on.

**Comment by tmiasko** [comment]
> It looks like the issue was passing some dependencies as rmeta instead of rlib.

Using metadata only crates for code generation is indeed unsupported:

```console
$ cat a.rs
#[inline]
pub fn f() {}
$ cat b.rs
fn main() {
    a::f();
}
$ rustc --edition=2021 a.rs --crate-type=lib --emit=metadata
$ rustc --edition=2021 b.rs --crate-type=bin --extern a=liba.rmeta -L.
error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:1012:9: no MIR available for DefId(20:3 ~ a[429a]::f)
...
```

We could potentially detect and diagnose the issue.

**Comment by JakobDegen** [comment]
I've updated the main issue with a MCVE. The version of things in tmiasko's comment should clearly not compile, and I'd expect that to just throw an error. However, it's not clear to me if the example that is now at the top of the post is supposed to compile - sort of feels like it should?
