### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:1309:75

### ISSUE THREAD

**Issue by bbigras** [rust-lang/rust#106422]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (574b64a97 2022-12-31)
binary: rustc
commit-hash: 574b64a97f52162f965bc201e47f0af8279ca65d
commit-date: 2022-12-31
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:1309:75
stack backtrace:
   0:     0x7f9821d652ba - std::backtrace_rs::backtrace::libunwind::trace::h58220cc92d95af9d
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f9821d652ba - std::backtrace_rs::backtrace::trace_unsynchronized::h5baad1b6045f1862
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9821d652ba - std::sys_common::backtrace::_print_fmt::h00cd15ad313be7cd
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f9821d652ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha3c10c2df3801f2e
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f9821dc83be - core::fmt::write::h15687caa14f55ffa
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f9821d55865 - std::io::Write::write_fmt::h9b3ae37b79923fd4
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/io/mod.rs:1682:15
   6:     0x7f9821d65085 - std::sys_common::backtrace::_print::hec732d08a877f27f
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f9821d65085 - std::sys_common::backtrace::print::h21a7b69d4e96b04e
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f9821d67e4f - std::panicking::default_hook::{{closure}}::h4dd038b046e67fff
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:267:22
   9:     0x7f9821d67b8b - std::panicking::default_hook::h09d820041cd6bd93
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:286:9
  10:     0x7f9825044114 - rustc_driver[7a1e5a3798cd51b2]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f9821d6868d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he092a4fd9b28e6e1
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:2002:9
  12:     0x7f9821d6868d - std::panicking::rust_panic_with_hook::he7925d19e6d87b9f
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:692:13
  13:     0x7f9821d683c2 - std::panicking::begin_panic_handler::{{closure}}::ha315fde4ace77e6d
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:577:13
  14:     0x7f9821d6576c - std::sys_common::backtrace::__rust_end_short_backtrace::h625a549b64bf26ca
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f9821d68112 - rust_begin_unwind
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:575:5
  16:     0x7f9821dc4da3 - core::panicking::panic_fmt::h3f6261900e8f8238
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/panicking.rs:64:14
  17:     0x7f9821dc4e7d - core::panicking::panic::h0872b33adc4829a3
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/panicking.rs:112:5
  18:     0x7f98235c14c1 - <core[4db15884ec6b3fd6]::iter::sources::from_generator::FromGenerator<<rustc_metadata[a81e1566ec24aed6]::creader::CrateMetadataRef>::get_module_children::{closure#0}> as core[4db15884ec6b3fd6]::iter::traits::iterator::Iterator>::next
  19:     0x7f98235bfe28 - <alloc[f127cc518e7b321d]::vec::Vec<rustc_middle[6135c93de258c3da]::metadata::ModChild> as alloc[f127cc518e7b321d]::vec::spec_from_iter::SpecFromIter<rustc_middle[6135c93de258c3da]::metadata::ModChild, core[4db15884ec6b3fd6]::iter::sources::from_generator::FromGenerator<<rustc_metadata[a81e1566ec24aed6]::creader::CrateMetadataRef>::get_module_children::{closure#0}>>>::from_iter
  20:     0x7f98235b07cf - <rustc_resolve[72daaa09f2dfa6e1]::Resolver>::resolve_ident_in_module_unadjusted_ext
  21:     0x7f98235a6b10 - <rustc_resolve[72daaa09f2dfa6e1]::Resolver>::resolve_path_with_ribs
  22:     0x7f9823bddd42 - <rustc_resolve[72daaa09f2dfa6e1]::imports::ImportResolver>::resolve_imports
  23:     0x7f9823bdda5f - <rustc_resolve[72daaa09f2dfa6e1]::Resolver as rustc_expand[535cdd40801f7ec]::base::ResolverExpand>::resolve_imports
  24:     0x7f9823fdd273 - <rustc_expand[535cdd40801f7ec]::expand::MacroExpander>::fully_expand_fragment
  25:     0x7f9824094b9d - <rustc_expand[535cdd40801f7ec]::expand::MacroExpander>::expand_crate
  26:     0x7f98240938a5 - <rustc_session[20c634f2fa5fd3a]::session::Session>::time::<core[4db15884ec6b3fd6]::result::Result<rustc_ast[a08e803ab2b279ef]::ast::Crate, rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_interface[921e14e9b1939ae4]::passes::configure_and_expand::{closure#1}>
  27:     0x7f9824058f4b - rustc_interface[921e14e9b1939ae4]::passes::configure_and_expand
  28:     0x7f982428c8a3 - <rustc_interface[921e14e9b1939ae4]::queries::Queries>::expansion
  29:     0x7f9824289600 - rustc_span[9ec51286058a4e72]::with_source_map::<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  30:     0x7f9824281a45 - <scoped_tls[c0301d1e58d7cd39]::ScopedKey<rustc_span[9ec51286058a4e72]::SessionGlobals>>::set::<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>
  31:     0x7f9824281032 - std[eb796f4691fa113e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[921e14e9b1939ae4]::util::run_in_thread_pool_with_globals<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>
  32:     0x7f9824280dda - <<std[eb796f4691fa113e]::thread::Builder>::spawn_unchecked_<rustc_interface[921e14e9b1939ae4]::util::run_in_thread_pool_with_globals<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#1} as core[4db15884ec6b3fd6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7f9821d72b43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h547009b1980571ef
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:1988:9
  34:     0x7f9821d72b43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h47c8551d74ce8d22
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:1988:9
  35:     0x7f9821d72b43 - std::sys::unix::thread::Thread::new::thread_start::he79de38213da15ab
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys/unix/thread.rs:108:17
  36:     0x7f9821a88e86 - start_thread
  37:     0x7f9821b0fce0 - clone3
  38:                0x0 - <unknown>

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (574b64a97 2022-12-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo build
   Compiling derpbot4 v0.1.0 (/home/bbigras/dev/tpg/derpbot4)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:1309:75
stack backtrace:
   0: rust_begin_unwind
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/panicking.rs:112:5
   3: <core::iter::sources::from_generator::FromGenerator<<rustc_metadata::creader::CrateMetadataRef>::get_module_children::{closure#0}> as core::iter::traits::iterator::Iterator>::next
   4: <alloc::vec::Vec<rustc_middle::metadata::ModChild> as alloc::vec::spec_from_iter::SpecFromIter<rustc_middle::metadata::ModChild, core::iter::sources::from_generator::FromGenerator<<rustc_metadata::creader::CrateMetadataRef>::get_module_children::{closure#0}>>>::from_iter
   5: <rustc_resolve::Resolver>::resolve_ident_in_module_unadjusted_ext
   6: <rustc_resolve::Resolver>::resolve_path_with_ribs
   7: <rustc_resolve::imports::ImportResolver>::resolve_imports
   8: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
   9: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  10: <rustc_expand::expand::MacroExpander>::expand_crate
  11: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>, rustc_interface::passes::configure_and_expand::{closure#1}>
  12: rustc_interface::passes::configure_and_expand
  13: <rustc_interface::queries::Queries>::expansion
  14: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  15: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (574b64a97 2022-12-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by compiler-errors** [comment]
@bbigras do you have any code that can reproduce this issue?

**Comment by bbigras** [comment]
Sadly no. The only thing I know so far is that the problem happened when I tried to switch from async-std to tokio. and I'm using `#![feature(async_closure, result_flattening, never_type)]`.

**Comment by pnkfelix** [comment]
If we cannot get more detail (as in sample code) from @bbigras , I'm not sure we can do anything to address this. I'm inclined to close this as non-actionable unless we get more information we can act on.
