### ISSUE TITLE
cargo doc crash on `narwhal-dag`

### ISSUE THREAD

**Issue by shiqicao** [rust-lang/rust#106623]
### Code

```bash 
git clone https://github.com/MystenLabs/sui.git
cd sui
git checkout devnet
cd crates/sui-sdk
cargo doc
```

### Meta

crash on 1.65, 1.66 and nightly

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (cc47b0699 2023-01-08)
binary: rustc
commit-hash: cc47b069983292e4ee8982d5dabe6301452c5f25
commit-date: 2023-01-08
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Error output

```
thread 'rustc' panicked at 'Unexpected result when selecting node_dag::NodeDag<T> Obligation(predicate=Binder(ProjectionPredicate(AliasTy { substs: [T, Const { ty: usize, kind: Value(Leaf(0x0000000000000020)) }], def_id: DefId(45:903 ~ fastcrypto[3b71]::hash::Hash::TypedDigest), _use_mk_alias_ty_instead: () }, Term::Ty(_)), []), depth=2)', compiler/rustc_trait_selection/src/traits/auto_trait.rs:757:33
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0:     0x7f5d51a6731a - std::backtrace_rs::backtrace::libunwind::trace::h226871b03ab0ff9d
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5d51a6731a - std::backtrace_rs::backtrace::trace_unsynchronized::hfec460a379dfa930
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5d51a6731a - std::sys_common::backtrace::_print_fmt::h47e3347a7a00a0b8
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f5d51a6731a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h29295205afe55042
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5d51aca55e - core::fmt::write::hff0191b598fb3b0b
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f5d51a578f5 - std::io::Write::write_fmt::hbb504f8b613362a3
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/io/mod.rs:1682:15
   6:     0x7f5d51a670e5 - std::sys_common::backtrace::_print::h4823cbf15bd070e6
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f5d51a670e5 - std::sys_common::backtrace::print::hf66f5a9cb072cea8
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f5d51a69eaf - std::panicking::default_hook::{{closure}}::h7bc0efdcc3bf56a7
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/panicking.rs:267:22
   9:     0x7f5d51a69beb - std::panicking::default_hook::h3f54f5b4fb31e406
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/panicking.rs:286:9
  10:     0x7f5d508a4604 - <rustc_driver[18602304c3814321]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[86ba13369de38d4f]::ops::function::FnOnce<(&core[86ba13369de38d4f]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f5d51a6a6ed - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h110d68855a8f4925
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/alloc/src/boxed.rs:2002:9
  12:     0x7f5d51a6a6ed - std::panicking::rust_panic_with_hook::haada24ea54b92d70
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/panicking.rs:692:13
  13:     0x7f5d51a6a469 - std::panicking::begin_panic_handler::{{closure}}::haa689299072e0542
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/panicking.rs:579:13
  14:     0x7f5d51a677cc - std::sys_common::backtrace::__rust_end_short_backtrace::h7f416720ed4cce52
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f5d51a6a172 - rust_begin_unwind
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/panicking.rs:575:5
  16:     0x7f5d51ac6f23 - core::panicking::panic_fmt::hab801c2bbfe27ddb
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/core/src/panicking.rs:64:14
  17:     0x7f5d514c7f05 - <rustc_trait_selection[836634366ff8830]::traits::auto_trait::AutoTraitFinder>::evaluate_predicates
  18:     0x564a0ee6b25c - <rustc_trait_selection[836634366ff8830]::traits::auto_trait::AutoTraitFinder>::find_auto_trait_generics::<rustdoc[943cad6dff1af7cf]::clean::types::Generics, <rustdoc[943cad6dff1af7cf]::clean::auto_trait::AutoTraitFinder>::generate_for_trait::{closure#0}>
  19:     0x564a0ebd1284 - <rustdoc[943cad6dff1af7cf]::clean::auto_trait::AutoTraitFinder>::generate_for_trait
  20:     0x564a0ec664e7 - <alloc[593078ccfaa74f72]::vec::Vec<rustdoc[943cad6dff1af7cf]::clean::types::Item> as alloc[593078ccfaa74f72]::vec::spec_from_iter::SpecFromIter<rustdoc[943cad6dff1af7cf]::clean::types::Item, core[86ba13369de38d4f]::iter::adapters::filter_map::FilterMap<alloc[593078ccfaa74f72]::vec::into_iter::IntoIter<rustc_span[4276d354efecb51]::def_id::DefId>, <rustdoc[943cad6dff1af7cf]::clean::auto_trait::AutoTraitFinder>::get_auto_trait_impls::{closure#0}>>>::from_iter
  21:     0x564a0ebdc311 - rustdoc[943cad6dff1af7cf]::clean::utils::get_auto_trait_and_blanket_impls
  22:     0x564a0ee02112 - <rustdoc[943cad6dff1af7cf]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[943cad6dff1af7cf]::visit::DocVisitor>::visit_item
  23:     0x564a0ee0225a - <rustdoc[943cad6dff1af7cf]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[943cad6dff1af7cf]::visit::DocVisitor>::visit_item
  24:     0x564a0ee0225a - <rustdoc[943cad6dff1af7cf]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[943cad6dff1af7cf]::visit::DocVisitor>::visit_item
  25:     0x564a0ee03381 - <rustdoc[943cad6dff1af7cf]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[943cad6dff1af7cf]::visit::DocVisitor>::visit_crate
  26:     0x564a0ee2e6ec - <rustc_session[428dcc9dad4836a4]::session::Session>::time::<alloc[593078ccfaa74f72]::vec::Vec<rustdoc[943cad6dff1af7cf]::clean::types::Item>, rustdoc[943cad6dff1af7cf]::passes::collect_trait_impls::collect_trait_impls::{closure#0}>
  27:     0x564a0edffe7a - rustdoc[943cad6dff1af7cf]::passes::collect_trait_impls::collect_trait_impls
  28:     0x564a0ee2ecae - <rustc_session[428dcc9dad4836a4]::session::Session>::time::<rustdoc[943cad6dff1af7cf]::clean::types::Crate, rustdoc[943cad6dff1af7cf]::core::run_global_ctxt::{closure#7}>
  29:     0x564a0edfa8e9 - rustdoc[943cad6dff1af7cf]::core::run_global_ctxt
  30:     0x564a0ee2ef7c - <rustc_session[428dcc9dad4836a4]::session::Session>::time::<(rustdoc[943cad6dff1af7cf]::clean::types::Crate, rustdoc[943cad6dff1af7cf]::config::RenderOptions, rustdoc[943cad6dff1af7cf]::formats::cache::Cache), rustdoc[943cad6dff1af7cf]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  31:     0x564a0ee697af - <rustc_interface[50bdaa1023eb7121]::passes::QueryContext>::enter::<rustdoc[943cad6dff1af7cf]::main_args::{closure#1}::{closure#0}::{closure#1}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>
  32:     0x564a0eba427a - <rustc_interface[50bdaa1023eb7121]::interface::Compiler>::enter::<rustdoc[943cad6dff1af7cf]::main_args::{closure#1}::{closure#0}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>
  33:     0x564a0ed82f2a - rustc_span[4276d354efecb51]::with_source_map::<core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>, rustc_interface[50bdaa1023eb7121]::interface::run_compiler<core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>, rustdoc[943cad6dff1af7cf]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  34:     0x564a0ed27965 - <scoped_tls[d847452d4e157dba]::ScopedKey<rustc_span[4276d354efecb51]::SessionGlobals>>::set::<rustc_interface[50bdaa1023eb7121]::interface::run_compiler<core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>, rustdoc[943cad6dff1af7cf]::main_args::{closure#1}>::{closure#0}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>
  35:     0x564a0ede79f0 - std[b80f5c9d0036a11a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[50bdaa1023eb7121]::util::run_in_thread_pool_with_globals<rustc_interface[50bdaa1023eb7121]::interface::run_compiler<core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>, rustdoc[943cad6dff1af7cf]::main_args::{closure#1}>::{closure#0}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>
  36:     0x564a0eecafcf - <<std[b80f5c9d0036a11a]::thread::Builder>::spawn_unchecked_<rustc_interface[50bdaa1023eb7121]::util::run_in_thread_pool_with_globals<rustc_interface[50bdaa1023eb7121]::interface::run_compiler<core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>, rustdoc[943cad6dff1af7cf]::main_args::{closure#1}>::{closure#0}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[86ba13369de38d4f]::result::Result<(), rustc_errors[109729f310d9e279]::ErrorGuaranteed>>::{closure#1} as core[86ba13369de38d4f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f5d51a74b23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h379e1b9bda46509f
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/alloc/src/boxed.rs:1988:9
  38:     0x7f5d51a74b23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf86d10042d2e6078
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/alloc/src/boxed.rs:1988:9
  39:     0x7f5d51a74b23 - std::sys::unix::thread::Thread::new::thread_start::h3f27ea3a68953b7e
                               at /rustc/cc47b069983292e4ee8982d5dabe6301452c5f25/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f5d4d290402 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  41:     0x7f5d4d31f590 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  42:                0x0 - <unknown>

```

</p>
</details>

**Comment by shiqicao** [comment]
it doesn't repro any more, likely narwhal-dag changed it.
