### ISSUE TITLE
Bootstrap fails to wipe the sysroot directory on Windows if proc-macro-server is being used

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#107018]
I tried this:

```rust
x build
```

I expected to see this happen: Bootstrap rebuilds the compiler.

Instead, this happened:
```
PS C:\Users\Joshua Nelson\src\rust> x b clippy --stage 1
Traceback (most recent call last):
  File "C:\Users\Joshua Nelson\src\rust\x.py", line 28, in <module>
    bootstrap.main()
  File "C:\Users\Joshua Nelson\src\rust\src\bootstrap\bootstrap.py", line 937, in main
    bootstrap(help_triggered)
  File "C:\Users\Joshua Nelson\src\rust\src\bootstrap\bootstrap.py", line 912, in bootstrap
    build.download_toolchain()
  File "C:\Users\Joshua Nelson\src\rust\src\bootstrap\bootstrap.py", line 428, in download_toolchain
    shutil.rmtree(bin_root)
  File "C:\Users\Joshua Nelson\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Joshua Nelson\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Joshua Nelson\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Joshua Nelson\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Joshua Nelson\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\libexec\\rust-analyzer-proc-macro-srv.exe'
```

### Meta

`git merge-base origin/master HEAD` is 9709a438721d679572f0f7c389cd1fa60922fbef

**Comment by jyn514** [comment]
> Bootstrap fails to wipe the sysroot directory on Windows if proc-macro-server is being used

In particular, this happens when rust-analyzer is running in the background *and* you have this config set:
```
    "rust-analyzer.procMacro.server": "./build/x86_64-pc-windows-msvc/stage0/libexec/rust-analyzer-proc-macro-srv",
```
We currently recommend that config in https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc.

**Comment by jyn514** [comment]
This would be fixed by having a "public" and "private" sysroot: https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Performing.20.60.2E.2Fx.2Epy.20dist.60.20results.20in.20a.20broken.20compiler.20at.20.2E.2E.2E/near/315810949

**Comment by albertlarsan68** [comment]
This happens because Windows doesn't allow deleting a running executable/DLL.

The way forward would be to special-case it as it is already the case with the `bootstrap.exe` file and ignore failures, or to make a double sysroot as you proposed.

**Comment by jyn514** [comment]
👍 I'm happy with both solutions. I think special casing proc-macro-server in the short term seems fine, but if we do that, we should open another issue for the public and private sysroot.
