### ISSUE TITLE
Master build from source fails at stage 1

### ISSUE THREAD

**Issue by JakubSilar3D** [rust-lang/rust#107126]
Absolutely does not hurt me, happy to provide more info.
source o on master, all submodules up to date,
master on 04a41f889f563b2384c63c990b5423d201d62ebd.. 
Priority for me is: you asked me to report :)

```
Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
.
.
.


   Compiling fluent-syntax v0.11.0
thread 'rustc' panicked at 'index out of bounds: the len is 36915 but the index is 36915', compiler/rustc_metadata/src/rmeta/decoder.rs:668:1
thread 'rustc' panicked at 'index out of bounds: the len is 36915 but the index is 36915', compiler/rustc_metadata/src/rmeta/decoder.rs:668:1
stack backtrace:
stack backtrace:
   0:     0x7f656d1e3fb9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6f4a713c17bbc504
   0:     0x7fd1589d8fb9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6f4a713c17bbc504
   1:     0x7f656d2548ee - core::fmt::write::hb0604da2144e5448
   1:     0x7fd158a498ee - core::fmt::write::hb0604da2144e5448
   2:     0x7f656d1a8d05 - std::io::Write::write_fmt::hfeb77003950f234a
   2:     0x7fd15899dd05 - std::io::Write::write_fmt::hfeb77003950f234a
   3:     0x7f656d1e3d75 - std::sys_common::backtrace::print::h28c5bb42f7d0a086
   3:     0x7fd1589d8d75 - std::sys_common::backtrace::print::h28c5bb42f7d0a086
   4:     0x7f656d1b878f - std::panicking::default_hook::{{closure}}::h2c272d69c2dc2d74
   4:     0x7fd1589ad78f - std::panicking::default_hook::{{closure}}::h2c272d69c2dc2d74
   5:     0x7f656d1b844a - std::panicking::default_hook::h7853f9ddcc3ff849
   5:     0x7fd1589ad44a - std::panicking::default_hook::h7853f9ddcc3ff849
   6:     0x7f656dedbc25 - rustc_driver[a8ab4d63811fa71]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7fd1596d0c25 - rustc_driver[a8ab4d63811fa71]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:     0x7f656d1b8f80 - std::panicking::rust_panic_with_hook::h1aeaa4f0cfa367bf
   7:     0x7fd1589adf80 - std::panicking::rust_panic_with_hook::h1aeaa4f0cfa367bf
   8:     0x7fd1589da269 - std::panicking::begin_panic_handler::{{closure}}::h0d0677a4a648fcf1
   8:     0x7f656d1e5269 - std::panicking::begin_panic_handler::{{closure}}::h0d0677a4a648fcf1
   9:     0x7fd1589d910c - std::sys_common::backtrace::__rust_end_short_backtrace::hba400e2fb7990386
   9:     0x7f656d1e410c - std::sys_common::backtrace::__rust_end_short_backtrace::hba400e2fb7990386
  10:     0x7f656d1b8ae2 - rust_begin_unwind
  11:     0x7f656d186cc3 - core::panicking::panic_fmt::hafdeea24cc142aec
  10:     0x7fd1589adae2 - rust_begin_unwind
  12:     0x7f656d186e32 - core::panicking::panic_bounds_check::h56ad238c1acd9b82
  11:     0x7fd15897bcc3 - core::panicking::panic_fmt::hafdeea24cc142aec
  13:     0x7f6572eb5a4c - <rustc_metadata[a03e1ae00c37b23f]::rmeta::CrateRoot as rustc_serialize[9be324ea5edbf312]::serialize::Decodable<rustc_metadata[a03e1ae00c37b23f]::rmeta::decoder::DecodeContext>>::decode
  12:     0x7fd15897be32 - core::panicking::panic_bounds_check::h56ad238c1acd9b82
  13:     0x7fd15e6aaa4c - <rustc_metadata[a03e1ae00c37b23f]::rmeta::CrateRoot as rustc_serialize[9be324ea5edbf312]::serialize::Decodable<rustc_metadata[a03e1ae00c37b23f]::rmeta::decoder::DecodeContext>>::decode
  14:     0x7f6572e13613 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::extract_one
  15:     0x7f6572e12522 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::extract_lib
  14:     0x7fd15e608613 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::extract_one
  16:     0x7f6572e11077 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::find_library_crate
  15:     0x7fd15e607522 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::extract_lib
  16:     0x7fd15e606077 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::find_library_crate
  17:     0x7f6572e0f440 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::maybe_load_library_crate
  18:     0x7f6572ede6ad - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::load
  17:     0x7fd15e604440 - <rustc_metadata[a03e1ae00c37b23f]::locator::CrateLocator>::maybe_load_library_crate
  19:     0x7f6572edb42e - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::maybe_resolve_crate
  20:     0x7f6572edd3c7 - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::maybe_resolve_crate
  18:     0x7fd15e6d36ad - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::load
  19:     0x7fd15e6d042e - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::maybe_resolve_crate
  21:     0x7f6572ee128d - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::maybe_process_path_extern
  20:     0x7fd15e6d23c7 - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::maybe_resolve_crate
  22:     0x7f6571d0b181 - <rustc_resolve[79d3dd1a5cc2e18]::Resolver>::extern_prelude_get
  23:     0x7f6571d0e98b - <rustc_resolve[79d3dd1a5cc2e18]::Resolver>::early_resolve_ident_in_lexical_scope
  21:     0x7fd15e6d628d - <rustc_metadata[a03e1ae00c37b23f]::creader::CrateLoader>::maybe_process_path_extern
  24:     0x7f6571cf1acd - <rustc_resolve[79d3dd1a5cc2e18]::Resolver>::resolve_path_with_ribs
  22:     0x7fd15d500181 - <rustc_resolve[79d3dd1a5cc2e18]::Resolver>::extern_prelude_get
  25:     0x7f6571d4081e - <rustc_resolve[79d3dd1a5cc2e18]::imports::ImportResolver>::resolve_imports
  23:     0x7fd15d50398b - <rustc_resolve[79d3dd1a5cc2e18]::Resolver>::early_resolve_ident_in_lexical_scope
  26:     0x7f6571cf6e2d - <rustc_resolve[79d3dd1a5cc2e18]::Resolver as rustc_expand[64c190404128a399]::base::ResolverExpand>::resolve_imports
  24:     0x7fd15d4e6acd - <rustc_resolve[79d3dd1a5cc2e18]::Resolver>::resolve_path_with_ribs
  27:     0x7f6573076db7 - <rustc_expand[64c190404128a399]::expand::MacroExpander>::fully_expand_fragment
  28:     0x7f6573076a06 - <rustc_expand[64c190404128a399]::expand::MacroExpander>::expand_crate
  25:     0x7fd15d53581e - <rustc_resolve[79d3dd1a5cc2e18]::imports::ImportResolver>::resolve_imports
  26:     0x7fd15d4ebe2d - <rustc_resolve[79d3dd1a5cc2e18]::Resolver as rustc_expand[64c190404128a399]::base::ResolverExpand>::resolve_imports
  27:     0x7fd15e86bdb7 - <rustc_expand[64c190404128a399]::expand::MacroExpander>::fully_expand_fragment
  29:     0x7f656e043df4 - <rustc_session[41bd6fdbe096cb13]::session::Session>::time::<core[3d15cbc1632fd665]::result::Result<rustc_ast[7ee88c495c439f9e]::ast::Crate, rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_interface[eaeda0d86261ec45]::passes::configure_and_expand::{closure#1}>
  28:     0x7fd15e86ba06 - <rustc_expand[64c190404128a399]::expand::MacroExpander>::expand_crate
  30:     0x7f656e019aa0 - rustc_interface[eaeda0d86261ec45]::passes::configure_and_expand
  31:     0x7f656e040911 - <rustc_interface[eaeda0d86261ec45]::queries::Queries>::expansion
  32:     0x7f656e040e81 - <rustc_interface[eaeda0d86261ec45]::queries::Queries>::global_ctxt
  29:     0x7fd159838df4 - <rustc_session[41bd6fdbe096cb13]::session::Session>::time::<core[3d15cbc1632fd665]::result::Result<rustc_ast[7ee88c495c439f9e]::ast::Crate, rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_interface[eaeda0d86261ec45]::passes::configure_and_expand::{closure#1}>
  30:     0x7fd15980eaa0 - rustc_interface[eaeda0d86261ec45]::passes::configure_and_expand
  31:     0x7fd159835911 - <rustc_interface[eaeda0d86261ec45]::queries::Queries>::expansion
  33:     0x7f656df462cc - <rustc_interface[eaeda0d86261ec45]::interface::Compiler>::enter::<rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}::{closure#2}, core[3d15cbc1632fd665]::result::Result<core[3d15cbc1632fd665]::option::Option<rustc_interface[eaeda0d86261ec45]::queries::Linker>, rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>
  32:     0x7fd159835e81 - <rustc_interface[eaeda0d86261ec45]::queries::Queries>::global_ctxt
  34:     0x7f656df6a0ea - rustc_span[a4ece7ac6c4fc5a8]::with_source_map::<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  33:     0x7fd15973b2cc - <rustc_interface[eaeda0d86261ec45]::interface::Compiler>::enter::<rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}::{closure#2}, core[3d15cbc1632fd665]::result::Result<core[3d15cbc1632fd665]::option::Option<rustc_interface[eaeda0d86261ec45]::queries::Linker>, rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>
  35:     0x7f656df3ce05 - <scoped_tls[535ca24a62cbd8c4]::ScopedKey<rustc_span[a4ece7ac6c4fc5a8]::SessionGlobals>>::set::<rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>
  34:     0x7fd15975f0ea - rustc_span[a4ece7ac6c4fc5a8]::with_source_map::<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  36:     0x7f656df04680 - std[55a387802d09a1ee]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[eaeda0d86261ec45]::util::run_in_thread_pool_with_globals<rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>
  35:     0x7fd159731e05 - <scoped_tls[535ca24a62cbd8c4]::ScopedKey<rustc_span[a4ece7ac6c4fc5a8]::SessionGlobals>>::set::<rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>
  37:     0x7f656dee578d - <<std[55a387802d09a1ee]::thread::Builder>::spawn_unchecked_<rustc_interface[eaeda0d86261ec45]::util::run_in_thread_pool_with_globals<rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>::{closure#1} as core[3d15cbc1632fd665]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f656d194343 - std::sys::unix::thread::Thread::new::thread_start::h4430dc500a776c4a
  36:     0x7fd1596f9680 - std[55a387802d09a1ee]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[eaeda0d86261ec45]::util::run_in_thread_pool_with_globals<rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>
  37:     0x7fd1596da78d - <<std[55a387802d09a1ee]::thread::Builder>::spawn_unchecked_<rustc_interface[eaeda0d86261ec45]::util::run_in_thread_pool_with_globals<rustc_interface[eaeda0d86261ec45]::interface::run_compiler<core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>, rustc_driver[a8ab4d63811fa71]::run_compiler::{closure#1}>::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3d15cbc1632fd665]::result::Result<(), rustc_errors[b9b5f32d7981f87a]::ErrorGuaranteed>>::{closure#1} as core[3d15cbc1632fd665]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7fd158989343 - std::sys::unix::thread::Thread::new::thread_start::h4430dc500a776c4a
  39:     0x7f656cf68b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  40:     0x7f656cffaa00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  41:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Z unstable-options -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C split-debuginfo=off -Z unstable-options -C prefer-dynamic -Z binary-dep-depinfo -Z tls-model=initial-exec -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
  39:     0x7fd15875db43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  40:     0x7fd1587efa00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  41:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=0 -C debug-assertions=off -Z unstable-options -Z binary-dep-depinfo -Z unstable-options -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden
``

**Comment by Nilstrieb** [comment]
Does it work after `./x.py clean`?

**Comment by JakubSilar3D** [comment]
Seems to fail in exactly the same manner. 
Just trying if stable builds ok. 
Will try a clean clone.
Note that it is lts lts ubuntu on an old yet powerfull dell workstation.

**Comment by JakubSilar3D** [comment]
My bad. "./x.py clean" isnt "./x.py c ". Maybe it is a proposal to improve the docs for people like me (idiots is the word, i suppose) :) . Thanks anyway.

**Comment by jyn514** [comment]
The original issue was a duplicate of https://github.com/rust-lang/rust/issues/76720.
