### ISSUE TITLE
TranslateError could have better formatting

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#107211]
I'm not sure if this is intentional
````
error: expected expression, found `,`
 --> /home/matthias/vcs/github/glacier2/fixed/94629.rs:2:40
  |
2 |     fn a(){{{{({{{ExprKind::Use {});(]),}}
  |                                        ^ expected expression

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: failed while formatting fluent string `parse_mismatched_closing_delimiter`:
message was missing
', compiler/rustc_errors/src/emitter.rs:1391:84
stack backtrace:
   0:     0x7f9840cf51e1 - std::backtrace_rs::backtrace::libunwind::trace::hd0b11c0adaab3249
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f9840cf51e1 - std::backtrace_rs::backtrace::trace_unsynchronized::h700e400a91d91fde
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9840cf51e1 - std::sys_common::backtrace::_print_fmt::hc78435809ad4efce
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f9840cf51e1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha735a792fef532f5
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f9840d6bae8 - core::fmt::write::h4891dd9bd07e2ad5
`````
Looks like we print `` `{stringname}`:\n{message}\n', ...``.
Might be better to just put everything in one line..?

You might need debug assertion to repro these ICEs in the first place.

**Comment by mejrs** [comment]
The relevant code is [here](https://github.com/rust-lang/rust/blob/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/compiler/rustc_errors/src/error.rs#L66-L135)

> Might be better to just put everything in one line..?

I'm not sure. Some variants of the error have much longer messages and I wouldn't like to squash everything to one line.

**Comment by matthiaskrgr** [comment]
Yeah, I saw it would writeLN everyhing which might be part of the problem :sweat_smile: 
Maybe we could oneline the error if it has less than 20 chars or something? :shrug:

**Comment by ts0yu** [comment]
can i take this as my first contribution? i might need some guidance but i think i have a good idea of where to start.

**Comment by mejrs** [comment]
> can i take this as my first contribution? i might need some guidance but i think i have a good idea of where to start.

If you think this is worth changing (personally I am neither for or against), then sure!

You probably want to change some of the `writeln!`s to `write!`. Then you can update/add to the tests at https://github.com/rust-lang/rust/blob/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/compiler/rustc_errors/src/tests.rs

Something to keep in mind is that `Report` is used 

https://github.com/rust-lang/rust/blob/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/compiler/rustc_errors/src/translation.rs#L49-L51

to forward from its  `Debug` impl (that's what `unwrap` uses) to `Display`. You might want to keep that in mind *if* you decide to customize the `Debug` impl rather than changing `Display`
