### ISSUE TITLE
Bootstrap in 1.67.0 fails: error: impl method assumes more implied bounds than the corresponding trait methodm

### ISSUE THREAD

**Issue by heitbaum** [rust-lang/rust#107349]
- #105572 stopping build of rust

Building rust:
```

$ rust-1.67.0/src/bootstrap/bootstrap.py

    error: impl method assumes more implied bounds than the corresponding trait method

```

### Meta

`rustc --version --verbose`:
```
1.67.0
```

Build error log
```

/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/bootstrap.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.version
Building rustbuild
running: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/rust-snapshot/bin/cargo build --manifest-path /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/Cargo.toml --verbose --frozen
       Fresh libc v0.2.137
       Fresh cfg-if v1.0.0
       Fresh memchr v2.5.0
       Fresh version_check v0.9.4
       Fresh unicode-ident v1.0.0
       Fresh cc v1.0.73
       Fresh pkg-config v0.3.25
       Fresh regex-automata v0.1.10
       Fresh lazy_static v1.4.0
       Fresh aho-corasick v0.7.18
       Fresh regex-syntax v0.6.26
       Fresh proc-macro2 v1.0.46
       Fresh bstr v0.2.17
       Fresh regex v1.5.6
       Fresh linux-raw-sys v0.1.3
       Fresh fnv v1.0.7
       Fresh quote v1.0.18
       Fresh typenum v1.15.0
       Fresh io-lifetimes v1.0.1
       Fresh log v0.4.17
       Fresh once_cell v1.12.0
       Fresh same-file v1.0.6
       Fresh bitflags v1.3.2
       Fresh crossbeam-utils v0.8.14
       Fresh filetime v0.2.16
       Fresh xattr v0.2.3
       Fresh unicode-width v0.1.9
       Fresh itoa v1.0.2
       Fresh cpufeatures v0.2.5
       Fresh generic-array v0.14.5
       Fresh syn v1.0.102
       Fresh walkdir v2.3.2
       Fresh thread_local v1.1.4
       Fresh globset v0.4.8
       Fresh rustix v0.36.3
       Fresh lzma-sys v0.1.17
       Fresh ryu v1.0.10
       Fresh tar v0.4.38
       Fresh getopts v0.2.21
       Fresh opener v0.5.0
       Fresh cmake v0.1.48
       Fresh object v0.29.0
       Fresh hex v0.4.3
       Fresh serde_derive v1.0.137
       Fresh block-buffer v0.10.2
       Fresh crypto-common v0.1.3
       Fresh ignore v0.4.18
       Fresh xz2 v0.1.6
       Fresh fd-lock v3.0.8
       Fresh serde v1.0.137
       Fresh digest v0.10.3
       Fresh toml v0.5.9
       Fresh sha2 v0.10.2
       Fresh serde_json v1.0.81
   Compiling bootstrap v0.0.0 (/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap)
     Running `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/rust-snapshot/bin/rustc --crate-name bootstrap --edition=2021 lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=1 -C metadata=2e732b35d72e40bd -C extra-filename=-2e732b35d72e40bd --out-dir /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps -C linker=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/host-gcc -C incremental=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/incremental -L dependency=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps --extern cc=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libcc-4fdaa6615e170798.rmeta --extern cmake=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libcmake-e34917385ef1ab50.rmeta --extern fd_lock=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libfd_lock-50958f11761ade76.rmeta --extern filetime=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libfiletime-ec84c225c9c077f4.rmeta --extern getopts=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libgetopts-f3cc463d60614f9c.rmeta --extern hex=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libhex-4995d4ec5a6a8bb8.rmeta --extern ignore=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libignore-30eaa53e59946c55.rmeta --extern libc=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/liblibc-00425cf962ef209a.rmeta --extern object=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libobject-00426b6b0b1b3613.rmeta --extern once_cell=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libonce_cell-36ff5aed838d903b.rmeta --extern opener=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libopener-5775f0ad04717918.rmeta --extern serde=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libserde-dede965d5e4dd2f7.rmeta --extern serde_json=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libserde_json-4463bc412753e0b8.rmeta --extern sha2=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libsha2-1375b5ae53405c81.rmeta --extern tar=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libtar-7dab063133f4edba.rmeta --extern toml=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libtoml-7622507e81f2654b.rmeta --extern walkdir=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libwalkdir-648ff28ff808654a.rmeta --extern xz2=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libxz2-915f220d064086e6.rmeta -Wrust_2018_idioms -Wunused_lifetimes -Wsemicolon_in_expressions_from_macros -Dwarnings -L native=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/lib`
error: impl method assumes more implied bounds than the corresponding trait method
  --> cache.rs:99:5
   |
99 |     fn as_ref(&self) -> &'static U {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #105572 <https://github.com/rust-lang/rust/issues/105572>
   = note: `-D implied-bounds-entailment` implied by `-D warnings`

error: could not compile `bootstrap` due to previous error

Caused by:
  process didn't exit successfully: `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/rust-snapshot/bin/rustc --crate-name bootstrap --edition=2021 lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=1 -C metadata=2e732b35d72e40bd -C extra-filename=-2e732b35d72e40bd --out-dir /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps -C linker=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/host-gcc -C incremental=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/incremental -L dependency=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps --extern cc=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libcc-4fdaa6615e170798.rmeta --extern cmake=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libcmake-e34917385ef1ab50.rmeta --extern fd_lock=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libfd_lock-50958f11761ade76.rmeta --extern filetime=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libfiletime-ec84c225c9c077f4.rmeta --extern getopts=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libgetopts-f3cc463d60614f9c.rmeta --extern hex=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libhex-4995d4ec5a6a8bb8.rmeta --extern ignore=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libignore-30eaa53e59946c55.rmeta --extern libc=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/liblibc-00425cf962ef209a.rmeta --extern object=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libobject-00426b6b0b1b3613.rmeta --extern once_cell=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libonce_cell-36ff5aed838d903b.rmeta --extern opener=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libopener-5775f0ad04717918.rmeta --extern serde=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libserde-dede965d5e4dd2f7.rmeta --extern serde_json=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libserde_json-4463bc412753e0b8.rmeta --extern sha2=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libsha2-1375b5ae53405c81.rmeta --extern tar=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libtar-7dab063133f4edba.rmeta --extern toml=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libtoml-7622507e81f2654b.rmeta --extern walkdir=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libwalkdir-648ff28ff808654a.rmeta --extern xz2=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/build/bootstrap/debug/deps/libxz2-915f220d064086e6.rmeta -Wrust_2018_idioms -Wunused_lifetimes -Wsemicolon_in_expressions_from_macros -Dwarnings -L native=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/lib` (exit status: 1)
Traceback (most recent call last):
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/bootstrap.py", line 954, in <module>
    main()
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/bootstrap.py", line 937, in main
    bootstrap(help_triggered)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/bootstrap.py", line 914, in bootstrap
    build.build_bootstrap(args.color)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/bootstrap.py", line 783, in build_bootstrap
    run(args, env=env, verbose=self.verbose, cwd=self.rust_root)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/bootstrap.py", line 166, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/rust-snapshot/bin/cargo build --manifest-path /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.67.0/src/bootstrap/Cargo.toml --verbose --frozen
FAILURE: scripts/build rust:host during make_host (package.mk)
*********** FAILED COMMAND ***********
python3 src/bootstrap/bootstrap.py -j ${CONCURRENCY_MAKE_LEVEL} build --stage 2 --verbose
```

**Comment by Nilstrieb** [comment]
You need to apply the diff from #105624 to fix it.

**Comment by heitbaum** [comment]
> You need to apply the diff from #105624 to fix it.

Thanks. Adding the patch fixed the compile.
