### ISSUE TITLE
bug: panic in rust 1.65

### ISSUE THREAD

**Issue by OliverNChalk** [rust-lang/rust#107485]
Just following the prompt to post this issue here, apologies if misplaced:

```bash
thread 'rustc' panicked at 'index out of bounds: the len is 6376 but the index is 6376', compiler/rustc_metadata/src/rmeta/decoder.rs:680:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:84:5
   3: <rustc_metadata::rmeta::CrateRoot as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_metadata::rmeta::decoder::MetadataBlob>::get_root
   5: <rustc_metadata::locator::CrateLocator>::extract_one
   6: <rustc_metadata::locator::CrateLocator>::extract_lib
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  11: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  12: <rustc_resolve::Resolver>::resolve_path_with_ribs
  13: <rustc_resolve::imports::ImportResolver>::resolve_imports
  14: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  15: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  16: <rustc_expand::expand::MacroExpander>::expand_crate
  17: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorGuaranteed>, rustc_interface::passes::configure_and_expand::{closure#1}>
  18: rustc_interface::passes::configure_and_expand
  19: <rustc_interface::queries::Queries>::expansion
  20: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  21: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

**Comment by Nilstrieb** [comment]
Did this bug reproduce after a `cargo clean`? If yes (which is probably not the case), can you share the code that caused it?

**Comment by OliverNChalk** [comment]
By the time I re-ran the compiler it rebuilt from zero (no incremental) and had no issue. Assuming it self cleaned or I unkowingly triggered a clean up. Can close if you're happy

**Comment by OliverNChalk** [comment]
As a point of further context, I belive this was caused by the fact I was using `sshfs` to replicate my server dir to my local machine for quicker debug iteration. I belive rust-analyzer was producing various metadata against my local machine that would end up getting torn when it wrote to the remote machine.

I didn't actually run `cargo build` against my local replica, so it seems rust-analyzer was enough to result in these weird errors.
