### ISSUE TITLE
Internal Compiler Error: Broken MIR

### ISSUE THREAD

**Issue by HarryET** [rust-lang/rust#107512]
I tried this code: https://github.com/WalletConnect/echo-server/blob/harry/fix/cors/src/lib.rs, which modified the original working project to add CORS

I expected to see this happen: this should have compiled successfully

Instead, this happened: compilation failed and the compiler asked me to file a bug report

### Meta
`rustc --version --verbose`:
```
rustc 1.69.0-nightly (1e225413a 2023-01-28)
binary: rustc
commit-hash: 1e225413a21fa69570bd3fefea9eb05e33f8b917
commit-date: 2023-01-28
host: aarch64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling echo-server v0.14.2 (/Users/harryet/Development/WalletConnect/echo-server)
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:895:9: Broken MIR: generator contains type [&std::option::Option<&str>, &std::option::Option<&str>] in MIR, but typeck only knows about {ResumeTy, hyper::Request<B>, &S, bool, &S, Pin<Box<dyn std::future::Future<Output = std::result::Result<T, <T as FromRequest<S, B>>::Rejection>> + Send>>, Pin<Box<dyn std::future::Future<Output = std::result::Result<T, <T as FromRequest<S, B>>::Rejection>> + Send>>, (), tracing::Span, &mut RelayClient, RelayClient, impl std::future::Future<Output = std::result::Result<PublicKey, error::Error>>, PublicKey, axum::http::request::Parts, B, impl std::future::Future<Output = std::result::Result<axum::body::Bytes, <B as HttpBody>::Error>>, axum::body::Bytes, Cow<'_, str>, std::option::Option<&str>, (std::option::Option<&str>, std::option::Option<&str>), &str, &&str, &Cow<'_, str>, &PublicKey, impl std::future::Future<Output = std::result::Result<bool, error::Error>>, &S, Pin<Box<dyn std::future::Future<Output = std::result::Result<T, <T as FromRequest<S, B>>::Rejection>> + Send>>} and [hyper::Request<B>, &S]
  --> src/middleware/validate_signature.rs:35:88
   |
35 |       async fn from_request(req: Request<B>, state: &S) -> Result<Self, Self::Rejection> {
   |  ________________________________________________________________________________________^
36 | |         if !state.validate_signatures() {
37 | |             // Skip signature validation
38 | |             return T::from_request(req, state)
...  |
79 | |         }
80 | |     }
   | |_____^

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/1e225413a21fa69570bd3fefea9eb05e33f8b917/compiler/rustc_errors/src/lib.rs:988:33
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
   3: <rustc_errors::Handler>::span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
   4: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   5: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   6: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   7: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   8: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   9: rustc_mir_transform::generator::mir_generator_witnesses
  10: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::mir::query::GeneratorLayout>
  11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_generator_witnesses, rustc_query_impl::plumbing::QueryCtxt>
  12: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::mir_generator_witnesses, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  13: rustc_mir_transform::mir_drops_elaborated_and_const_checked
  14: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>::{closure#0}, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  15: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_drops_elaborated_and_const_checked, rustc_query_impl::plumbing::QueryCtxt>
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_drops_elaborated_and_const_checked
  18: rustc_mir_transform::optimized_mir
  19: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, &rustc_middle::mir::Body>
  20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt>
  21: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  22: <rustc_middle::ty::context::TyCtxt>::generator_layout
  23: rustc_ty_utils::layout::layout_of_uncached
  24: rustc_ty_utils::layout::layout_of
  25: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, core::result::Result<rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>, rustc_middle::ty::layout::LayoutError>>
  26: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::layout_of, rustc_query_impl::plumbing::QueryCtxt>
  27: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::layout_of, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  28: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_of
  29: rustc_ty_utils::layout::layout_of
  30: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, core::result::Result<rustc_target::abi::TyAndLayout<rustc_middle::ty::Ty>, rustc_middle::ty::layout::LayoutError>>
  31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::layout_of, rustc_query_impl::plumbing::QueryCtxt>
  32: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::layout_of, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  33: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_of
  34: <rustc_mir_transform::const_prop::CanConstProp>::check
  35: <rustc_mir_transform::const_prop_lint::ConstProp as rustc_mir_transform::pass_manager::MirLint>::run_lint
  36: rustc_mir_transform::pass_manager::run_passes_inner
  37: rustc_mir_transform::run_analysis_to_runtime_passes
  38: rustc_mir_transform::mir_drops_elaborated_and_const_checked
  39: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>::{closure#0}, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  40: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  41: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_drops_elaborated_and_const_checked, rustc_query_impl::plumbing::QueryCtxt>
  42: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_drops_elaborated_and_const_checked
  43: rustc_mir_transform::optimized_mir
  44: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, &rustc_middle::mir::Body>
  45: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt>
  46: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  47: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  48: rustc_metadata::rmeta::encoder::encode_metadata_impl
  49: rustc_data_structures::sync::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  50: rustc_metadata::rmeta::encoder::encode_metadata
  51: rustc_metadata::fs::encode_and_write_metadata
  52: rustc_interface::passes::start_codegen
  53: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  54: <rustc_interface::queries::Queries>::ongoing_codegen
  55: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  56: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  57: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (1e225413a 2023-01-28) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_generator_witnesses] generator witness types for `middleware::validate_signature::<impl at src/middleware/validate_signature.rs:24:1: 24:61>::from_request::{closure#0}`
#1 [mir_drops_elaborated_and_const_checked] elaborating drops for `middleware::validate_signature::<impl at src/middleware/validate_signature.rs:24:1: 24:61>::from_request::{closure#0}`
#2 [optimized_mir] optimizing MIR for `middleware::validate_signature::<impl at src/middleware/validate_signature.rs:24:1: 24:61>::from_request::{closure#0}`
#3 [layout_of] computing layout of `[async block@src/middleware/validate_signature.rs:35:88: 80:6]`
#4 [layout_of] computing layout of `[async block@src/middleware/validate_signature.rs:35:88: 80:6]`
#5 [mir_drops_elaborated_and_const_checked] elaborating drops for `middleware::validate_signature::<impl at src/middleware/validate_signature.rs:24:1: 24:61>::from_request`
#6 [optimized_mir] optimizing MIR for `middleware::validate_signature::<impl at src/middleware/validate_signature.rs:24:1: 24:61>::from_request`
end of query stack
error: could not compile `echo-server`
```

</p>
</details>

**Comment by Nilstrieb** [comment]
cc @cjgillot , might be related to your recent changes

**Comment by HarryET** [comment]
For extra context, just tried building on stable and it works

**Comment by cjgillot** [comment]
@HarryET does it still fail on today's nightly?

**Comment by HarryET** [comment]
@cjgillot working with today's nightly!
