### ISSUE TITLE
[ICE]: index out of bounds: the len is 4 but the index is 2147483649 (compiler/rustc_middle/src/mir/mod.rs:471:22)

### ISSUE THREAD

**Issue by tarcieri** [rust-lang/rust#107613]
This error occurred in CI so unfortunately I don't have a minimal repro as I can't reproduce it locally. I also wasn't able to reproduce it in CI either: rerunning the job "fixed" the problem.

Possibly related to #107582?

There's a second panic:

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/compiler/rustc_query_system/src/query/plumbing.rs:269:23

### Code

Here's the PR where I experienced it: https://github.com/RustCrypto/elliptic-curves/pull/737

Here's the first commit where it manifested: https://github.com/RustCrypto/elliptic-curves/pull/737/commits/061548d3b0268b7e3eb1772a8cfe6f372d97ca33

### Meta

From CI:

note: rustc 1.67.0 (fc594f156 2023-01-24) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=2 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on

### Error output

From: https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528

```
thread 'rustc' panicked at 'index out of bounds: the len is 4 but the index is 2147483649', compiler/rustc_middle/src/mir/mod.rs:471:22
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 4 but the index is 2147483649', compiler/rustc_middle/src/mir/mod.rs:471:22
stack backtrace:
   0:     0x7faf8de976fa - std::backtrace_rs::backtrace::libunwind::trace::h34aec3ef6cd8ad7e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7faf8de976fa - std::backtrace_rs::backtrace::trace_unsynchronized::h8035d38698d0f7a8
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7faf8de976fa - std::sys_common::backtrace::_print_fmt::hff968f6695a1ba22
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7faf8de976fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7eea0efe77acf1ec
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7faf8defa25e - core::fmt::write::hc553f17407eb0b48
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:     0x7faf8de87a85 - std::io::Write::write_fmt::h62e5f01a089f48c0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:     0x7faf8de974c5 - std::sys_common::backtrace::_print::h52d116aff3db4cd1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7faf8de974c5 - std::sys_common::backtrace::print::h9e7d2f98fb7af075
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7faf8de9a20f - std::panicking::default_hook::{{closure}}::hf74999dab2d0a95c
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:     0x7faf8de99f4b - std::panicking::default_hook::hc11ca7d10c44c42f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:     0x7faf9119ac31 - rustc_driver[faf1f11f94aaf6ff]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7faf8de9aa4d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha7dbb2d260f78172
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/boxed.rs:2032:9
  12:     0x7faf8de9aa4d - std::panicking::rust_panic_with_hook::hdb4da1ae79c845a5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:692:13
  13:     0x7faf8de9a7c9 - std::panicking::begin_panic_handler::{{closure}}::h02b5b35b126d5cf2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:579:13
  14:     0x7faf8de97bac - std::sys_common::backtrace::__rust_end_short_backtrace::h6c6853376cf416d1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7faf8de9a4d2 - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  16:     0x7faf8def6c43 - core::panicking::panic_fmt::hfd9e949092070b66
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  17:     0x7faf8def6e12 - core::panicking::panic_bounds_check::h369b89af3d2735a6
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:147:5
  18:     0x7faf8fffc0b4 - <rustc_borrowck[dcfa3144f53dc2a2]::type_check::TypeChecker>::normalize_and_prove_instantiated_predicates
  19:     0x7faf900065db - <rustc_borrowck[dcfa3144f53dc2a2]::type_check::TypeVerifier as rustc_middle[bcb6873cde329d56]::mir::visit::Visitor>::visit_constant
  20:     0x7faf8ffe1056 - <rustc_borrowck[dcfa3144f53dc2a2]::type_check::TypeVerifier as rustc_middle[bcb6873cde329d56]::mir::visit::Visitor>::visit_body
  21:     0x7faf8ffad617 - rustc_borrowck[dcfa3144f53dc2a2]::type_check::type_check
  22:     0x7faf8ff841e5 - rustc_borrowck[dcfa3144f53dc2a2]::nll::compute_regions
  23:     0x7faf8ff61e4b - rustc_borrowck[dcfa3144f53dc2a2]::do_mir_borrowck
  24:     0x7faf8ff5dc79 - rustc_borrowck[dcfa3144f53dc2a2]::mir_borrowck
  25:     0x7faf90255c9e - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::VecCache<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId, &rustc_middle[bcb6873cde329d56]::mir::query::BorrowCheckResult>>
  26:     0x7faf90b446ca - <rustc_query_impl[7ca4c504d4b53a14]::Queries as rustc_middle[bcb6873cde329d56]::ty::query::QueryEngine>::mir_borrowck
  27:     0x7faf9004dd41 - <rustc_borrowck[dcfa3144f53dc2a2]::type_check::TypeChecker>::prove_closure_bounds
  28:     0x7faf90028f3b - <rustc_borrowck[dcfa3144f53dc2a2]::type_check::TypeChecker>::typeck_mir
  29:     0x7faf8ffad633 - rustc_borrowck[dcfa3144f53dc2a2]::type_check::type_check
  30:     0x7faf8ff841e5 - rustc_borrowck[dcfa3144f53dc2a2]::nll::compute_regions
  31:     0x7faf8ff61e4b - rustc_borrowck[dcfa3144f53dc2a2]::do_mir_borrowck
  32:     0x7faf8ff5dc79 - rustc_borrowck[dcfa3144f53dc2a2]::mir_borrowck
  33:     0x7faf90255c9e - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::VecCache<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId, &rustc_middle[bcb6873cde329d56]::mir::query::BorrowCheckResult>>
  34:     0x7faf8f694958 - rustc_data_structures[7e2dc299a6484f3b]::sync::par_for_each_in::<&[rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId], <rustc_middle[bcb6873cde329d56]::hir::map::Map>::par_body_owners<rustc_interface[1d25fa3620f328b6]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
  35:     0x7faf8f6943a3 - <rustc_session[d01ee0491e5e5048]::session::Session>::time::<(), rustc_interface[1d25fa3620f328b6]::passes::analysis::{closure#2}>
  36:     0x7faf8f692227 - rustc_interface[1d25fa3620f328b6]::passes::analysis
  37:     0x7faf9094fb2a - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<(), core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>>
  38:     0x7faf9094f820 - rustc_query_system[daa376e8a1534a67]::query::plumbing::get_query::<rustc_query_impl[7ca4c504d4b53a14]::queries::analysis, rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt>
  39:     0x7faf903559a3 - <rustc_interface[1d25fa3620f328b6]::passes::QueryContext>::enter::<rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  40:     0x7faf90351f23 - <rustc_interface[1d25fa3620f328b6]::interface::Compiler>::enter::<rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}::{closure#2}, core[e12cfea94acfcb96]::result::Result<core[e12cfea94acfcb96]::option::Option<rustc_interface[1d25fa3620f328b6]::queries::Linker>, rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  41:     0x7faf9034cf78 - rustc_span[5737ed96bfbdbd37]::with_source_map::<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  42:     0x7faf9034ca65 - <scoped_tls[85a67c9db469d989]::ScopedKey<rustc_span[5737ed96bfbdbd37]::SessionGlobals>>::set::<rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  43:     0x7faf9034c052 - std[3da7f01c8c2aa3e3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1d25fa3620f328b6]::util::run_in_thread_pool_with_globals<rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  44:     0x7faf90a50bea - <<std[3da7f01c8c2aa3e3]::thread::Builder>::spawn_unchecked_<rustc_interface[1d25fa3620f328b6]::util::run_in_thread_pool_with_globals<rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>::{closure#1} as core[e12cfea94acfcb96]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x7faf8dea4803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha93239d92e7b610d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/boxed.rs:[200](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:201)0:9
  46:     0x7faf8dea4803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hebda57b0[236](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:237)de612
                               at /rustc/fc594f15669680fa70d[255](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:256)faec3ca3fb507c3405/library/alloc/src/boxed.rs:2000:9
  47:     0x7faf8dea4803 - std::sys::unix::thread::Thread::new::thread_start::h1541b4390bbc26ca
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys/unix/thread.rs:108:17
  48:     0x7faf8dbe7b43 - <unknown>
  49:     0x7faf8dc79a00 - <unknown>
  50:                0x0 - <unknown>

error: internal compiler error: unexpected panic<backtrace>
```

Here is another backtrace that occurred during the same build:

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/compiler/rustc_query_system/src/query/plumbing.rs:269:23
stack backtrace:
    Checking base16ct v0.1.1
   Compiling serde_json v1.0.91
   0:     0x7faf8de976fa - std::backtrace_rs::backtrace::libunwind::trace::h34aec3ef6cd8ad7e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7faf8de976fa - std::backtrace_rs::backtrace::trace_unsynchronized::h8035d38698d0f7a8
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7faf8de976fa - std::sys_common::backtrace::_print_fmt::hff968f6695a1ba22
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7faf8de976fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7eea0efe77acf1ec
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7faf8defa25e - core::fmt::write::hc553f17407eb0b48
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:     0x7faf8de87a85 - std::io::Write::write_fmt::h62e5f01a089f48c0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:     0x7faf8de974c5 - std::sys_common::backtrace::_print::h52d116aff3db4cd1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7faf8de974c5 - std::sys_common::backtrace::print::h9e7d2f98fb7af075
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7faf8de9a20f - std::panicking::default_hook::{{closure}}::hf74999dab2d0a95c
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:     0x7faf8de99f4b - std::panicking::default_hook::hc11ca7d10c44c42f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
    Checking serdect v0.1.0
    Checking pkcs8 v0.9.0
  10:     0x7faf9119ac31 - rustc_driver[faf1f11f94aaf6ff]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7faf8de9aa4d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha7dbb2d260f7[81](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:82)72
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/boxed.rs:2032:9
  12:     0x7faf8de9aa4d - std::panicking::rust_panic_with_hook::hdb4da1ae79c845a5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:692:13
  13:     0x7faf8de9a7[82](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:83) - std::panicking::begin_panic_handler::{{closure}}::h02b5b35b126d5cf2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:577:13
  14:     0x7faf8de97bac - std::sys_common::backtrace::__rust_end_short_backtrace::h6c6853376cf416d1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7faf8de9a4d2 - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  16:     0x7faf8def6c43 - core::panicking::panic_fmt::hfd9e949092070b66
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  17:     0x7faf8def6d1d - core::panicking::panic::h341545107301821d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
  18:     0x7faf8f98478c - rustc_query_system[daa376e8a1534a67]::query::plumbing::get_query::<rustc_query_impl[7ca4c504d4b53a14]::queries::evaluate_obligation, rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt>
  19:     0x7faf8f[83](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:84)b7e4 - <rustc_infer[47503a1af3d697eb]::infer::InferCtxt as rustc_trait_selection[f2c8a436da4b1c5d]::traits::query::evaluate_obligation::InferCtxtExt>::predicate_must_hold_modulo_regions
  20:     0x7faf8f839f7d - rustc_trait_selection[f2c8a436da4b1c5d]::traits::type_known_to_meet_bound_modulo_regions
  21:     0x7faf8f8381a5 - rustc_ty_utils[e5f46be7994b0588]::common_traits::is_copy_raw
  22:     0x7faf8f833cd2 - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<rustc_middle[bcb6873cde329d56]::ty::ParamEnvAnd<rustc_middle[bcb6873cde329d56]::ty::Ty>, bool>>
  23:     0x7faf8f835b0a - rustc_ty_utils[e5f46be7994b0588]::needs_drop::needs_drop_raw
  24:     0x7faf8f8334e2 - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<rustc_middle[bcb6873cde329d56]::ty::ParamEnvAnd<rustc_middle[bcb6873cde329d56]::ty::Ty>, bool>>
    Checking ryu v1.0.12
  25:     0x7faf8f60123e - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::as_operand
  26:     0x7faf8f612b3d - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::as_call_operand
  27:     0x7faf8f612d65 - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::as_call_operand
  28:     0x7faf8f60aaab - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::expr_into_dest
  29:     0x7faf8f60a17e - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::expr_into_dest
  30:     0x7faf8f62bb0f - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::ast_block_stmts
  31:     0x7faf8f623948 - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::ast_block
  32:     0x7faf8f60b059 - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::expr_into_dest
  33:     0x7faf8f60a17e - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::expr_into_dest
  34:     0x7faf8f60a17e - <rustc_mir_build[352e76d761bc5cdf]::build::Builder>::expr_into_dest
  35:     0x7faf90234ef7 - rustc_mir_build[352e76d761bc5cdf]::build::mir_built
  36:     0x7faf8ff1651a - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<rustc_middle[bcb6873cde329d56]::ty::WithOptConstParam<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId>, &rustc_data_structures[7e2dc299a64[84](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:85)f3b]::steal::Steal<rustc_middle[bcb6873cde329d56]::mir::Body>>>
  37:     0x7faf8faaec8d - rustc_mir_transform[be636f278bbe35f]::check_unsafety::unsafety_check_result
  38:     0x7faf8faab06e - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::VecCache<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId, &rustc_middle[bcb6873cde329d56]::mir::query::UnsafetyCheckResult>>
  39:     0x7faf903274e4 - rustc_mir_transform[be636f278bbe35f]::mir_const
  40:     0x7faf8ff16[85](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:86)0 - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<rustc_middle[bcb6[87](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:88)3cde329d56]::ty::WithOptConstParam<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId>, &rustc_data_structures[7e2dc299a6484f3b]::steal::Steal<rustc_middle[bcb6873cde329d56]::mir::Body>>>
  41:     0x7faf8f6d6d54 - rustc_mir_transform[be636f278bbe35f]::mir_promoted
  42:     0x7faf8ff5ef2a - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<rustc_middle[bcb6873cde329d56]::ty::WithOptConstParam<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId>, (&rustc_data_structures[7e2dc299a6484f3b]::steal::Steal<rustc_middle[bcb6873cde329d56]::mir::Body>, &rustc_data_structures[7e2dc299a6484f3b]::steal::Steal<rustc_index[ef68f47d911a2ab6]::vec::IndexVec<rustc_middle[bcb6873cde329d56]::mir::Promoted, rustc_middle[bcb6873cde329d56]::mir::Body>>)>>
  43:     0x7faf8ff5d77f - rustc_borrowck[dcfa3144f53dc2a2]::mir_borrowck
  44:     0x7faf90255c9e - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::VecCache<rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId, &rustc_middle[bcb6873cde329d56]::mir::query::BorrowCheckResult>>
  45:     0x7faf8f694958 - rustc_data_structures[7e2dc299a6484f3b]::sync::par_for_each_in::<&[rustc_span[5737ed96bfbdbd37]::def_id::LocalDefId], <rustc_middle[bcb6873cde329d56]::hir::map::Map>::par_body_owners<rustc_interface[1d25fa3620f328b6]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
  46:     0x7faf8f6943a3 - <rustc_session[d01ee0491e5e5048]::session::Session>::time::<(), rustc_interface[1d25fa3620f328b6]::passes::analysis::{closure#2}>
  47:     0x7faf8f692227 - rustc_interface[1d25fa3620f328b6]::passes::analysis
  48:     0x7faf9094fb2a - rustc_query_system[daa376e8a1534a67]::query::plumbing::try_execute_query::<rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt, rustc_query_system[daa376e8a1534a67]::query::caches::DefaultCache<(), core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>>
  49:     0x7faf9094f820 - rustc_query_system[daa376e8a1534a67]::query::plumbing::get_query::<rustc_query_impl[7ca4c504d4b53a14]::queries::analysis, rustc_query_impl[7ca4c504d4b53a14]::plumbing::QueryCtxt>
  50:     0x7faf903559a3 - <rustc_interface[1d25fa3620f328b6]::passes::QueryContext>::enter::<rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  51:     0x7faf90351f23 - <rustc_interface[1d25fa3620f328b6]::interface::Compiler>::enter::<rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}::{closure#2}, core[e12cfea94acfcb96]::result::Result<core[e12cfea94acfcb96]::option::Option<rustc_interface[1d25fa3620f328b6]::queries::Linker>, rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  52:     0x7faf9034cf78 - rustc_span[5737ed96bfbdbd37]::with_source_map::<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  53:     0x7faf9034ca65 - <scoped_tls[85a67c9db469d9[89](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:90)]::ScopedKey<rustc_span[5737ed96bfbdbd37]::SessionGlobals>>::set::<rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  54:     0x7faf[90](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:91)34c052 - std[3da7f01c8c2aa3e3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1d25fa3620f328b6]::util::run_in_thread_pool_with_globals<rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>
  55:     0x7faf90a50bea - <<std[3da7f01c8c2aa3e3]::thread::Builder>::spawn_unchecked_<rustc_interface[1d25fa3620f328b6]::util::run_in_thread_pool_with_globals<rustc_interface[1d25fa3620f328b6]::interface::run_compiler<core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>, rustc_driver[faf1f11f94aaf6ff]::run_compiler::{closure#1}>::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e12cfea94acfcb96]::result::Result<(), rustc_errors[1b8cd632e3edc426]::ErrorGuaranteed>>::{closure#1} as core[e12cfea94acfcb96]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:     0x7faf8dea4803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha93239d[92](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:93)e7b610d
                               at /rustc/fc5[94](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:95)f1566[96](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:97)80fa70d255faec3ca3fb507c3405/library/alloc/src/boxed.rs:2000:9
  57:     0x7faf8dea4803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hebda57b0236de612
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/alloc/src/boxed.rs:2000:9
  58:     0x7faf8dea4803 - std::sys::unix::thread::Thread::new::thread_start::h1541b4390bbc26ca
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys/unix/thread.rs:[108](https://github.com/RustCrypto/elliptic-curves/actions/runs/4078778175/jobs/7029397528#step:5:109):17
  59:     0x7faf8dbe7b43 - <unknown>
  60:     0x7faf8dc79a00 - <unknown>
  61:                0x0 - <unknown>

error: internal compiler error: unexpected panic
```

</p>
</details>

**Comment by kpreid** [comment]
Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
