### ISSUE TITLE
Nightly ICE: thread 'rustc' panicked at 'no resolution for <type>

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#107990]
[Repository/branch](https://github.com/Kixunil/rust-bitcoin/tree/weight-prediction)

Unfortunately, I don't have the time to try to minimize right now, it seems this was caused by latest nightly. I'm posting [CI output](https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/4162401644/jobs/7201533098) for now, will try to look at minimization later.

If someone has the resources for it perhaps try bisecting rustc between latest nightlies.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (5b8f28453 2023-02-12) running on x86_64-unknown-linux-gnu
```

(Unfortunately not verbose in the CI.)

### Error output

```
thread 'rustc' panicked at 'no resolution for "TapLeafHash" MacroNS DefId(0:4471 ~ bitcoin[231d]::taproot)', src/librustdoc/passes/collect_intra_doc_links.rs:393:32
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f18e216403a - std::backtrace_rs::backtrace::libunwind::trace::h68819555df8b2d9c
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f18e216403a - std::backtrace_rs::backtrace::trace_unsynchronized::hd69f04a0acc016b0
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f18e216403a - std::sys_common::backtrace::_print_fmt::hd05f5f45b3abc36d
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f18e216403a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h97505bc956055c86
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f18e21c421e - core::fmt::write::hee40881876785ec8
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f18e2154755 - std::io::Write::write_fmt::h9ac4fb15bcdd983e
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/io/mod.rs:1684:15
   6:     0x7f18e2163e05 - std::sys_common::backtrace::_print::h7b79888859e1041b
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f18e2163e05 - std::sys_common::backtrace::print::h5f377a03e09d721c
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f18e2166b9f - std::panicking::default_hook::{{closure}}::h081dc35da89fae25
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/panicking.rs:267:22
   9:     0x7f18e21668db - std::panicking::default_hook::h5ac9a56440f0f320
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/panicking.rs:286:9
  10:     0x7f18e54c0144 - rustc_driver_impl[45704de6fc1a7e42]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f18e21673da - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h597f484af91b69d8
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/alloc/src/boxed.rs:2002:9
  12:     0x7f18e21673da - std::panicking::rust_panic_with_hook::h32591b11d4f9c8c2
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/panicking.rs:692:13
  13:     0x7f18e2167159 - std::panicking::begin_panic_handler::{{closure}}::hb2b75e52ec6963d4
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/panicking.rs:579:13
  14:     0x7f18e21644dc - std::sys_common::backtrace::__rust_end_short_backtrace::ha859a147e693367c
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f18e2166e62 - rust_begin_unwind
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/panicking.rs:575:5
  16:     0x7f18e21c0bc3 - core::panicking::panic_fmt::hb9e85c5c10f5beb5
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/core/src/panicking.rs:64:14
  17:     0x5630820a552f - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  18:     0x5630820a5662 - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector>::resolve
  19:     0x5630820aa1a9 - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e05275ab24b811c1]::visit::DocVisitor>::visit_item
  20:     0x5630820b742a - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e05275ab24b811c1]::visit::DocVisitor>::visit_inner_recur
  21:     0x5630820acf05 - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e05275ab24b811c1]::visit::DocVisitor>::visit_item
  22:     0x5630820b742a - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e05275ab24b811c1]::visit::DocVisitor>::visit_inner_recur
  23:     0x5630820acf05 - <rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[e05275ab24b811c1]::visit::DocVisitor>::visit_item
  24:     0x5630820a3fbf - rustdoc[e05275ab24b811c1]::passes::collect_intra_doc_links::collect_intra_doc_links
  25:     0x56308206403e - <rustc_session[15418ad64be04b7e]::session::Session>::time::<rustdoc[e05275ab24b811c1]::clean::types::Crate, rustdoc[e05275ab24b811c1]::core::run_global_ctxt::{closure#7}>
  26:     0x5630820e1c5b - rustdoc[e05275ab24b811c1]::core::run_global_ctxt
  27:     0x56308206432b - <rustc_session[15418ad64be04b7e]::session::Session>::time::<(rustdoc[e05275ab24b811c1]::clean::types::Crate, rustdoc[e05275ab24b811c1]::config::RenderOptions, rustdoc[e05275ab24b811c1]::formats::cache::Cache), rustdoc[e05275ab24b811c1]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  28:     0x563081ea671d - <rustc_interface[1dae503a51862634]::queries::QueryResult<&rustc_middle[950e6c013232a13e]::ty::context::GlobalCtxt>>::enter::<core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>, rustdoc[e05275ab24b811c1]::main_args::{closure#1}::{closure#0}::{closure#1}>
  29:     0x563081e1cc8a - <rustc_interface[1dae503a51862634]::interface::Compiler>::enter::<rustdoc[e05275ab24b811c1]::main_args::{closure#1}::{closure#0}, core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>>
  30:     0x56308206372b - rustc_span[9e92ed5877933bb8]::with_source_map::<core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>, rustc_interface[1dae503a51862634]::interface::run_compiler<core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>, rustdoc[e05275ab24b811c1]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  31:     0x563081fb1462 - <scoped_tls[d2579b36b1a9f18d]::ScopedKey<rustc_span[9e92ed5877933bb8]::SessionGlobals>>::set::<rustc_interface[1dae503a51862634]::interface::run_compiler<core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>, rustdoc[e05275ab24b811c1]::main_args::{closure#1}>::{closure#0}, core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>>
  32:     0x563082077ba0 - std[6e58747c831eadda]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1dae503a51862634]::util::run_in_thread_pool_with_globals<rustc_interface[1dae503a51862634]::interface::run_compiler<core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>, rustdoc[e05275ab24b811c1]::main_args::{closure#1}>::{closure#0}, core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>>
  33:     0x563081e7fb77 - <<std[6e58747c831eadda]::thread::Builder>::spawn_unchecked_<rustc_interface[1dae503a51862634]::util::run_in_thread_pool_with_globals<rustc_interface[1dae503a51862634]::interface::run_compiler<core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>, rustdoc[e05275ab24b811c1]::main_args::{closure#1}>::{closure#0}, core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8fc858d2dd58175c]::result::Result<(), rustc_errors[9a7f2c558b529898]::ErrorGuaranteed>>::{closure#1} as core[8fc858d2dd58175c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7f18e2171373 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfe75deb0c10a09d3
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/alloc/src/boxed.rs:1988:9
  35:     0x7f18e2171373 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcd4bdd69a317ae2f
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/alloc/src/boxed.rs:1988:9
  36:     0x7f18e2171373 - std::sys::unix::thread::Thread::new::thread_start::h1aad22be20900f56
                               at /rustc/5b8f284536d00ba649ca968584bedab4820d8527/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7f18e1e92b43 - <unknown>
  38:     0x7f18e1f24a00 - <unknown>
  39:                0x0 - <unknown>
```

</p>
</details>

Cc @apoelstra @tcharding

**Comment by weiznich** [comment]
Maybe a duplicate of https://github.com/rust-lang/rust/issues/107995? (That one has at least a bisection)

**Comment by olivereanderson** [comment]
I encountered a similar problem which I commented in #107995 in [this comment](https://github.com/rust-lang/rust/issues/107995#issuecomment-1428168265)

**Comment by Kixunil** [comment]
Not sure about flags on closed issues but E-needs-* could be removed.
