### ISSUE TITLE
support `x fmt` for sub and outside of rust directories

### ISSUE THREAD

**Issue by ozkanonur** [rust-lang/rust#108004]
When we run `../x fmt compiler` in `library` directory, the following error will occur:

```sh
thread 'main' panicked at 'entry failed with compiler: No such file or directory (os error 2)', format.rs:257:25
```

Same problem will occur also when we are outside of the `rust` directory like:

```sh
~/devspace/personal/rust-dist/tools  $ ../../rust/x fmt library/std --check

thread 'main' panicked at 'entry failed with library/std: No such file or directory (os error 2)', format.rs:257:25
```

The problem here is, `x fmt` expects the complete path for target directory in order to work. For example, instead of running `../../rust/x fmt library/std --check`, if we run `../../rust/x fmt ../../rust/library/std --check`, it will work without any problem.

Related zulip topic: https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/uncomfortable.20use.20of.20.60x.20fmt.60.20from.20outside.20of.20rust.20dir

**Comment by ozkanonur** [comment]
since https://github.com/rust-lang/rust/pull/107948#event-8510829293 is merged, shortcut functionality should be supported as well for sub and parent rust directories.
