### ISSUE TITLE
ICE documenting `clap@3.2.23` on `nightly-2023-02-14`.

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#108065]
ICE when documenting `clap@3.2.23` on nightly (as of 2023-02-14).

```
[[package]]
name = "clap"
version = "3.2.23"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "71655c45cb9845d3270c9d6df84ebe72b4dad3c2ba3f7023ad47c144e4e473a
```

Panic message:
```
thread 'rustc' panicked at 'no resolution for "ValueEnum" MacroNS DefId(0:56 ~ clap[12d4]::derive)', src/librustdoc
/passes/collect_intra_doc_links.rs:393:32
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (065852def 2023-02-13) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (065852def 2023-02-13) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 thread 'rustc' panicked at 'no resolution for "ValueEnum" MacroNS DefId(0:56 ~ clap[12d4]::derive)', src/librustdoc/passes/collect_intra_doc_links.rs:393:32
stack backtrace:
   0:     0x7f36699b39ea - std::backtrace_rs::backtrace::libunwind::trace::ha39be26a07fb8052
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f36699b39ea - std::backtrace_rs::backtrace::trace_unsynchronized::hd6e5588684dfc770
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f36699b39ea - std::sys_common::backtrace::_print_fmt::h0aa1f720c61d57cb
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f36699b39ea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc190949f222eb440
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3669a13afe - core::fmt::write::haec7e4ab73364fe1
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f36699a4005 - std::io::Write::write_fmt::hb6e3f525620bf821
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/io/mod.rs:1684:15
   6:     0x7f36699b37b5 - std::sys_common::backtrace::_print::h2247195b4ea8ad8f
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f36699b37b5 - std::sys_common::backtrace::print::h3d9da3a3c1b6d7ec
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f36699b654f - std::panicking::default_hook::{{closure}}::ha4d8e3c4db028445
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:267:22
   9:     0x7f36699b628b - std::panicking::default_hook::h20fc8e669161563d
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:286:9
  10:     0x7f366cd12eb4 - <rustc_driver_impl[dde0176af8c5ab09]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[745cf9$11:     0x7f36699b6d8a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9f47dbc14e762fb4[9/357]
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/boxed.rs:2002:9
  12:     0x7f36699b6d8a - std::panicking::rust_panic_with_hook::h6018fd309f9d5b5b
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:692:13
  13:     0x7f36699b6b09 - std::panicking::begin_panic_handler::{{closure}}::hbdb22e51e1673fd8
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:579:13
  14:     0x7f36699b3e8c - std::sys_common::backtrace::__rust_end_short_backtrace::h17e6abf2d9b11694
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f36699b6812 - rust_begin_unwind
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:575:5
  16:     0x7f3669a104a3 - core::panicking::panic_fmt::h400e7cee17c5d91a
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:64:14
  17:     0x559efd7a11df - <rustdoc[ab72e5851687a7f1]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  18:     0x559efd7a1312 - <rustdoc[ab72e5851687a7f1]::passes::collect_intra_doc_links::LinkCollector>::resolve
  19:     0x559efd7a5e99 - <rustdoc[ab72e5851687a7f1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[ab72e5851687a7f1]::visit::DocVisitor>::visit_item
  20:     0x559efd7b317a - <rustdoc[ab72e5851687a7f1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[ab72e5851687a7f1]::visit::DocVisitor>::visit_inner_recur
  21:     0x559efd7a8bf5 - <rustdoc[ab72e5851687a7f1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[ab72e5851687a7f1]::visit::DocVisitor>::visit_item
  22:     0x559efd79fc6f - rustdoc[ab72e5851687a7f1]::passes::collect_intra_doc_links::collect_intra_doc_links
  23:     0x559efd75fbee - <rustc_session[93261570977692f7]::session::Session>::time::<rustdoc[ab72e5851687a7f1]::clean::types::Crate, rustdoc[ab72e5851687a7f1]::core::run_global_ctxt::{closure#7}>
  24:     0x559efd7dd95b - rustdoc[ab72e5851687a7f1]::core::run_global_ctxt
  25:     0x559efd75fedb - <rustc_session[93261570977692f7]::session::Session>::time::<(rustdoc[ab72e5851687a7f1]::clean::types::Crate, rustdoc[ab72e5851687a7f1]::config::RenderOptions, rustdoc[ab72e5851687a7f1]::formats::cache::Cac
he), rustdoc[ab72e5851687a7f1]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  26:     0x559efd5a086d - <rustc_interface[ca9b18c665a84cba]::queries::QueryResult<&rustc_middle[f96e42c1fea88f4c]::ty::context::GlobalCtxt>>::enter::<core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>, rustdoc[ab72e5851687a7f1]::main_args::{closure#1}::{closure#0}::{closure#1}>
  27:     0x559efd516e5a - <rustc_interface[ca9b18c665a84cba]::interface::Compiler>::enter::<rustdoc[ab72e5851687a7f1]::main_args::{closure#1}::{closure#0}, core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>>
  28:     0x559efd75f2db - rustc_span[5815ad9c631c3526]::with_source_map::<core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>, rustc_interface[ca9b18c665a84cba]::interface::run_compiler<core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>, rustdoc[ab72e5851687a7f1]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  29:     0x559efd6aba02 - <scoped_tls[bc57a32744e3362]::ScopedKey<rustc_span[5815ad9c631c3526]::SessionGlobals>>::set::<rustc_interface[ca9b18c665a84cba]::interface::run_compiler<core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>, rustdoc[ab72e5851687a7f1]::main_args::{closure#1}>::{closure#0}, core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>>
  30:     0x559efd7732f0 - std[1c96249000aa551b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ca9b18c665a84cba]::util::run_in_thread_pool_with_globals<rustc_interface[ca9b18c665a84cba]::interface::run_compiler<core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>, rustdoc[ab72e5851687a7f1]::main_args::{closure#1}>::{closure#0}, core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>>
  31:     0x559efd579e67 - <<std[1c96249000aa551b]::thread::Builder>::spawn_unchecked_<rustc_interface[ca9b18c665a84cba]::util::run_in_thread_pool_with_globals<rustc_interface[ca9b18c665a84cba]::interface::run_compiler<core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>, rustdoc[ab72e5851687a7f1]::main_args::{closure#1}>::{closure#0}, core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[745cf9d9cd8fbdae]::result::Result<(), rustc_errors[22208327c08e6a91]::ErrorGuaranteed>>::{closure#1} as core[745cf9d9cd8fbdae]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7f36699c0d23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd8b371047d72378a
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/boxed.rs:1988:9
  33:     0x7f36699c0d23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h43857df79cf6223f
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/boxed.rs:1988:9
  34:     0x7f36699c0d23 - std::sys::unix::thread::Thread::new::thread_start::h405fa19d08d79454
                               at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7f366907bea5 - start_thread
  36:     0x7f3668da498d - __clone
  37:                0x0 - <unknown>

```

</p>
</details>

**Comment by derekdreery** [comment]
Probably a duplicate of #107990

**Comment by derekdreery** [comment]
I'm gonna close as the issue is clearly in hand.
