### ISSUE TITLE
ICE: non_lifetime_binders : ` could not resolve DefId`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#108179]
### Code

```Rust
#![feature(non_lifetime_binders)]
fn test_argument_position(x: impl for<'a> Trait<'_, Assoc = impl Trait<'_, Assoc =  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (f4f5fc3e5 2023-02-17)
binary: rustc
commit-hash: f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3
commit-date: 2023-02-17
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
error[E0405]: cannot find trait `Trait` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:43
  |
1 | fn test_argument_position(x: impl for<'a> Trait<'_, Assoc = impl Trait<'_, Assoc =  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test...
  |                                           ^^^^^ not found in this scope

error[E0405]: cannot find trait `Trait` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:66
  |
1 | fn test_argument_position(x: impl for<'a> Trait<'_, Assoc = impl Trait<'_, Assoc =  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test...
  |                                                                  ^^^^^ not found in this scope

error[E0405]: cannot find trait `Trait` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:118
  |
1 | fn test_argument_position(x: impl for<'a> Trait<'_, Assoc = impl Trait<'_, Assoc =  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test...
  |                                                                                                                      ^^^^^ not found in this scope

error[E0405]: cannot find trait `Trait` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:141
  |
1 | ...=  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug >...
  |                                                               ^^^^^ not found in this scope

error[E0412]: cannot find type `Trait` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:180
  |
1 | ...it<'_, Assoc = impl Trait<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}
  |                                                               ^^^^^ not found in this scope

error[E0405]: cannot find trait `Trait` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:203
  |
1 | ...it<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}
  |                                                               ^^^^^ not found in this scope

error[E0573]: expected type, found derive macro `Debug`
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:222
  |
1 | ...ent_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}
  |                                                                     ^^^^^ not a type
  |
help: consider importing this trait instead
  |
1 | use std::fmt::Debug;
  |

error[E0405]: cannot find trait `Assoc` in this scope
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:232
  |
1 | ...soc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}
  |                                                               ^^^^^ not found in this scope

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(non_lifetime_binders)
  |         ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #1 <https://github.com/rust-lang/rust/issues/1> for more information
  = note: `#[warn(incomplete_features)]` on by default

warning: type parameter `test_argument_position` should have an upper camel case name
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:94
  |
1 | ...ait<'_, Assoc =  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, As...
  |                              ^^^^^^^^^^^^^^^^^^^^^^ help: convert the identifier to upper camel case: `TestArgumentPosition`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

error[E0601]: `main` function not found in crate `733aa7416df0ee2943481d202059f8582eb2be38`
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:258
  |
1 | ... > + Assoc> > + '_> > + '_>) {}
  |                                   ^ consider adding a `main` function to `733aa7416df0ee2943481d202059f8582eb2be38.rs`

error[E0658]: anonymous lifetimes in `impl Trait` are unstable
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:209
  |
1 | ...gument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}
  |                                                           ^^ expected named lifetime parameter
  |
  = help: add `#![feature(anonymous_lifetime_in_impl_trait)]` to the crate attributes to enable
help: consider introducing a named lifetime parameter
  |
1 | fn test_argument_position<'a>(x: impl for<'a> Trait<'_, Assoc = impl Trait<'_, Assoc =  impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'a, Assoc =  Debug > + Assoc> > + '_> > + '_>) {}
  |                          ++++                                                                                                                                                                                       ~~

error: internal compiler error: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1367:9: could not resolve DefId(0:5 ~ 733aa7416df0ee2943481d202059f8582eb2be38[7c0b]::test_argument_position::test_argument_position)
 --> 733aa7416df0ee2943481d202059f8582eb2be38.rs:1:147
  |
1 | ...impl for<test_argument_position> Trait<'_, Assoc = impl Trait<test_argument_position, Assoc =  Trait<'_, Assoc = impl Trait<'_, Assoc =  Debug > + ...
  |                                                                  ^^^^^^^^^^^^^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/compiler/rustc_errors/src/lib.rs:991:33
stack backtrace:
   0:     0x7ffa5111ca5a - std::backtrace_rs::backtrace::libunwind::trace::hebe09041f884c65d
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ffa5111ca5a - std::backtrace_rs::backtrace::trace_unsynchronized::h546f6c63cbbce5a9
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ffa5111ca5a - std::sys_common::backtrace::_print_fmt::h2559cb0cfed7a617
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ffa5111ca5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1fb4eaaaafa2d72a
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ffa5117c9ae - core::fmt::write::hbaef4432b3c9d07b
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/core/src/fmt/mod.rs:1232:17
   5:     0x7ffa5110ce05 - std::io::Write::write_fmt::h1f8dce362441faaa
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/io/mod.rs:1684:15
   6:     0x7ffa5111c825 - std::sys_common::backtrace::_print::hc0e92ab849a4f4e1
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7ffa5111c825 - std::sys_common::backtrace::print::h878cd11684ebdec3
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7ffa5111f59f - std::panicking::default_hook::{{closure}}::h2ea8a6875aa6312d
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/panicking.rs:267:22
   9:     0x7ffa5111f2db - std::panicking::default_hook::h9e42277a84072188
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/panicking.rs:286:9
  10:     0x7ffa4fe6e7b4 - <rustc_driver_impl[afa3c304d692170b]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[ebab21900c9c0a2]::ops::function::FnOnce<(&core[ebab21900c9c0a2]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7ffa5111fddd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2c34f129ed413128
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:2002:9
  12:     0x7ffa5111fddd - std::panicking::rust_panic_with_hook::h4c799b8c4fc0a70b
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/panicking.rs:692:13
  13:     0x7ffa4ffb9e81 - std[dc63ca99f82ce43d]::panicking::begin_panic::<rustc_errors[faa449d960b5ce55]::ExplicitBug>::{closure#0}
  14:     0x7ffa4ffb9156 - std[dc63ca99f82ce43d]::sys_common::backtrace::__rust_end_short_backtrace::<std[dc63ca99f82ce43d]::panicking::begin_panic<rustc_errors[faa449d960b5ce55]::ExplicitBug>::{closure#0}, !>
  15:     0x7ffa4ffb6d56 - std[dc63ca99f82ce43d]::panicking::begin_panic::<rustc_errors[faa449d960b5ce55]::ExplicitBug>
  16:     0x7ffa4ff9c776 - std[dc63ca99f82ce43d]::panic::panic_any::<rustc_errors[faa449d960b5ce55]::ExplicitBug>
  17:     0x7ffa4ff9b6a2 - <rustc_errors[faa449d960b5ce55]::HandlerInner>::span_bug::<rustc_span[1010a352e5466fad]::span_encoding::Span, &alloc[d840872249f3dc84]::string::String>
  18:     0x7ffa4ff9b397 - <rustc_errors[faa449d960b5ce55]::Handler>::span_bug::<rustc_span[1010a352e5466fad]::span_encoding::Span, &alloc[d840872249f3dc84]::string::String>
  19:     0x7ffa50000feb - rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt::<rustc_span[1010a352e5466fad]::span_encoding::Span>::{closure#0}
  20:     0x7ffa5000103a - rustc_middle[6caff671bb338453]::ty::context::tls::with_opt::<rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt<rustc_span[1010a352e5466fad]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7ffa4ffff9b6 - rustc_middle[6caff671bb338453]::ty::context::tls::with_context_opt::<rustc_middle[6caff671bb338453]::ty::context::tls::with_opt<rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt<rustc_span[1010a352e5466fad]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7ffa4ffff946 - rustc_middle[6caff671bb338453]::util::bug::opt_span_bug_fmt::<rustc_span[1010a352e5466fad]::span_encoding::Span>
  23:     0x7ffa4ffff904 - rustc_middle[6caff671bb338453]::util::bug::span_bug_fmt::<rustc_span[1010a352e5466fad]::span_encoding::Span>
  24:     0x7ffa4e0b0bcd - <rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_path
  25:     0x7ffa4e0af73f - <rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_path
  26:     0x7ffa4e99f654 - <rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_poly_trait_ref
  27:     0x7ffa4e99d3fc - <rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_generics
  28:     0x7ffa4e9a55ca - <rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_fn
  29:     0x7ffa4e9a4c5c - rustc_hir[f4a2ff38696703b5]::intravisit::walk_item::<rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext>
  30:     0x7ffa4e9a373a - <rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_item
  31:     0x7ffa4e9976b3 - rustc_hir_analysis[257f64c795d1d076]::collect::resolve_bound_vars::resolve_bound_vars
  32:     0x7ffa4e99678c - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::resolve_bound_vars, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  33:     0x7ffa4f8746e5 - <rustc_query_impl[ef929ccf3c28623b]::Queries as rustc_middle[6caff671bb338453]::ty::query::QueryEngine>::resolve_bound_vars
  34:     0x7ffa4ef34633 - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::named_variable_map, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  35:     0x7ffa4e9f645f - <dyn rustc_hir_analysis[257f64c795d1d076]::astconv::AstConv>::res_to_ty
  36:     0x7ffa4e9f230b - <dyn rustc_hir_analysis[257f64c795d1d076]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}
  37:     0x7ffa4e1b9818 - rustc_hir_analysis[257f64c795d1d076]::collect::predicates_of::gather_explicit_predicates_of
  38:     0x7ffa4eaea8bd - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::get_query::<rustc_query_impl[ef929ccf3c28623b]::queries::explicit_predicates_of, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt, rustc_middle[6caff671bb338453]::dep_graph::dep_node::DepKind>
  39:     0x7ffa4e9b2bf0 - rustc_hir_analysis[257f64c795d1d076]::collect::predicates_of::predicates_of
  40:     0x7ffa4e9afc9c - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::get_query::<rustc_query_impl[ef929ccf3c28623b]::queries::predicates_of, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt, rustc_middle[6caff671bb338453]::dep_graph::dep_node::DepKind>
  41:     0x7ffa4e9af913 - <rustc_query_impl[ef929ccf3c28623b]::Queries as rustc_middle[6caff671bb338453]::ty::query::QueryEngine>::predicates_of
  42:     0x7ffa4e4d6135 - <rustc_hir_analysis[257f64c795d1d076]::collect::CollectItemTypesVisitor as rustc_hir[f4a2ff38696703b5]::intravisit::Visitor>::visit_item
  43:     0x7ffa4e4d4e75 - <rustc_middle[6caff671bb338453]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis[257f64c795d1d076]::collect::CollectItemTypesVisitor>
  44:     0x7ffa4e4d4d8c - rustc_hir_analysis[257f64c795d1d076]::collect::collect_mod_item_types
  45:     0x7ffa4f42f67f - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::collect_mod_item_types, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  46:     0x7ffa4f86e50d - <rustc_query_impl[ef929ccf3c28623b]::Queries as rustc_middle[6caff671bb338453]::ty::query::QueryEngine>::collect_mod_item_types
  47:     0x7ffa4e3129dd - <rustc_middle[6caff671bb338453]::hir::map::Map>::for_each_module::<rustc_hir_analysis[257f64c795d1d076]::check_crate::{closure#0}::{closure#0}::{closure#0}>
  48:     0x7ffa4e31056c - rustc_hir_analysis[257f64c795d1d076]::check_crate
  49:     0x7ffa4e306062 - rustc_interface[686dab9608bc6033]::passes::analysis
  50:     0x7ffa4f663d92 - rustc_query_system[5ff89444bbfc32f5]::query::plumbing::try_execute_query::<rustc_query_impl[ef929ccf3c28623b]::queries::analysis, rustc_query_impl[ef929ccf3c28623b]::plumbing::QueryCtxt>
  51:     0x7ffa4f867e2a - <rustc_query_impl[ef929ccf3c28623b]::Queries as rustc_middle[6caff671bb338453]::ty::query::QueryEngine>::analysis
  52:     0x7ffa4f080303 - <rustc_interface[686dab9608bc6033]::queries::QueryResult<&rustc_middle[6caff671bb338453]::ty::context::GlobalCtxt>>::enter::<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}::{closure#2}::{closure#3}>
  53:     0x7ffa4f07f4d4 - <rustc_interface[686dab9608bc6033]::interface::Compiler>::enter::<rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}::{closure#2}, core[ebab21900c9c0a2]::result::Result<core[ebab21900c9c0a2]::option::Option<rustc_interface[686dab9608bc6033]::queries::Linker>, rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>
  54:     0x7ffa4f07a6f4 - rustc_span[1010a352e5466fad]::with_source_map::<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  55:     0x7ffa4f07a204 - <scoped_tls[d487b98c36b0d138]::ScopedKey<rustc_span[1010a352e5466fad]::SessionGlobals>>::set::<rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>
  56:     0x7ffa4f079902 - std[dc63ca99f82ce43d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[686dab9608bc6033]::util::run_in_thread_pool_with_globals<rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>
  57:     0x7ffa4f0796ac - <<std[dc63ca99f82ce43d]::thread::Builder>::spawn_unchecked_<rustc_interface[686dab9608bc6033]::util::run_in_thread_pool_with_globals<rustc_interface[686dab9608bc6033]::interface::run_compiler<core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>, rustc_driver_impl[afa3c304d692170b]::run_compiler::{closure#1}>::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ebab21900c9c0a2]::result::Result<(), rustc_errors[faa449d960b5ce55]::ErrorGuaranteed>>::{closure#1} as core[ebab21900c9c0a2]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7ffa51129c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9fd36c4a0ba5b15d
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:1988:9
  59:     0x7ffa51129c63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd37d267854c7434f
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/alloc/src/boxed.rs:1988:9
  60:     0x7ffa51129c63 - std::sys::unix::thread::Thread::new::thread_start::h1ff24d5a09f2a8be
                               at /rustc/f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3/library/std/src/sys/unix/thread.rs:108:17
  61:     0x7ffa4ca8fbb5 - <unknown>
  62:     0x7ffa4cb11d90 - <unknown>
  63:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (f4f5fc3e5 2023-02-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(non_lifetime_binders)

query stack during panic:
#0 [resolve_bound_vars] resolving lifetimes
#1 [named_variable_map] looking up a named region
#2 [explicit_predicates_of] computing explicit predicates of `test_argument_position`
#3 [predicates_defined_on] computing predicates of `test_argument_position`
#4 [predicates_of] computing predicates of `test_argument_position`
#5 [collect_mod_item_types] collecting item types in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 11 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0405, E0412, E0573, E0601, E0658.
For more information about an error, try `rustc --explain E0405`.
```

</p>
</details>

**Comment by compiler-errors** [comment]
This could use minimization too.

**Comment by compiler-errors** [comment]
Can't repro this either, @matthiaskrgr. Maybe it stopped ICEing, or maybe it wasn't minimized correctly?

**Comment by matthiaskrgr** [comment]
Looks like its fixed :slightly_smiling_face:

**Comment by compiler-errors** [comment]
👍
