### ISSUE TITLE
debug ice: E0433 spans trying to point into proc macro? 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#108266]
### Code

```Rust
#![allow(deprecated)]
pub struct Encoder<'a> {}

mod tests {
    #[derive(RustcEncodable)]
    struct Struct { }
}
```

Without debug assertions it looks like this
```
error[E0433]: failed to resolve: could not find `rustc_serialize` in the crate root
 --> src/main.rs:5:14
  |
5 |     #[derive(RustcEncodable)]
  |              ^^^^^^^^^^^^^^ could not find `rustc_serialize` in the crate root
  |
  = note: this error originates in the derive macro `RustcEncodable` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `rustc_serialize` in the crate root
 --> src/main.rs:5:14
  |
5 |     #[derive(RustcEncodable)]
  |              ^^^^^^^^^^^^^^ could not find `rustc_serialize` in the crate root
  |
  = note: this error originates in the derive macro `RustcEncodable` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
  |
5 |     use crate::Encoder;
  |
help: if you import `Encoder`, refer to it directly
  |
5 |     #[derive(RustcEncodable)]
  |
```
We might be generating a span that refers to code inside the `#[derive(RustcEncodable)]` here.

### Meta

`rustc --version --verbose`:
```
7e253a7fb2e2e050021fed32da6fa2ec7bcea0fb
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0433]: failed to resolve: could not find `rustc_serialize` in the crate root
 --> src/main.rs:5:14
  |
5 |     #[derive(RustcEncodable)]
  |              ^^^^^^^^^^^^^^ could not find `rustc_serialize` in the crate root
  |
  = note: this error originates in the derive macro `RustcEncodable` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'Span must not be empty and have no suggestion', /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:710:9
stack backtrace:
   0:     0x7ff0b376fb34 - std::backtrace_rs::backtrace::libunwind::trace::h1544161bb283d831
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff0b376fb34 - std::backtrace_rs::backtrace::trace_unsynchronized::h88182f9ae043ea1d
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff0b376fb34 - std::sys_common::backtrace::_print_fmt::hbc46e181236b160e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ff0b376fb34 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h40f9d84c979d1c60
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ff0b37ddd38 - core::fmt::write::h3693e9c93ce31d95
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/fmt/mod.rs:1232:17
   5:     0x7ff0b375285f - std::io::Write::write_fmt::hf505aa7ad9258ee9
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/io/mod.rs:1684:15
   6:     0x7ff0b376f935 - std::sys_common::backtrace::_print::h7f7e9448ce377511
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7ff0b376f935 - std::sys_common::backtrace::print::h10d8939f3c4a7090
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7ff0b3737837 - std::panicking::default_hook::{{closure}}::hd96f1491f179fb0a
   9:     0x7ff0b37374f1 - std::panicking::default_hook::hea690dedd054fe31
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:286:9
  10:     0x7ff0b627b075 - <alloc[a96d60a9bf8c9b93]::boxed::Box<dyn for<'a, 'b> core[3a7799eb5b53fe42]::ops::function::Fn<(&'a core[3a7799eb5b53fe42]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[3a7799eb5b53fe42]::marker::Sync + core[3a7799eb5b53fe42]::marker::Send> as core[3a7799eb5b53fe42]::ops::function::Fn<(&core[3a7799eb5b53fe42]::panic::panic_info::PanicInfo,)>>::call
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  11:     0x7ff0b627b075 - rustc_driver_impl[c7adae1617edfc64]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:1145:17
  12:     0x7ff0b3738234 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hac989f8c5fbcacd1
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:2002:9
  13:     0x7ff0b3738234 - std::panicking::rust_panic_with_hook::hc778308fe861818c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:692:13
  14:     0x7ff0b3770122 - std::panicking::begin_panic_handler::{{closure}}::h18e0a9e49a0d5c86
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:577:13
  15:     0x7ff0b376fc16 - std::sys_common::backtrace::__rust_end_short_backtrace::h3cd1987cc33c3094
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7ff0b3737d32 - rust_begin_unwind
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:575:5
  17:     0x7ff0b37e7f53 - core::panicking::panic_fmt::ha9472d71642ed08e
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panicking.rs:64:14
  18:     0x7ff0b85a12ee - <rustc_errors[e2c6533d414d421d]::diagnostic::Diagnostic>::span_suggestion_with_style::<&alloc[a96d60a9bf8c9b93]::string::String, &str>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:710:9
  19:     0x7ff0b85a12ee - <rustc_errors[e2c6533d414d421d]::diagnostic::Diagnostic>::span_suggestion_verbose::<&alloc[a96d60a9bf8c9b93]::string::String, &str>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_errors/src/diagnostic.rs:733:9
  20:     0x7ff0b8498f49 - rustc_resolve[6f864bfd50f0fb33]::diagnostics::show_candidates
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/diagnostics.rs:2466:21
  21:     0x7ff0b853550f - <rustc_resolve[6f864bfd50f0fb33]::Resolver>::report_with_use_injections
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/diagnostics.rs:156:17
  22:     0x7ff0b853550f - <rustc_resolve[6f864bfd50f0fb33]::Resolver>::report_errors
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/diagnostics.rs:119:9
  23:     0x7ff0b85bcb41 - <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate::{closure#0}::{closure#6}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/lib.rs:1533:59
  24:     0x7ff0b85bcb41 - <rustc_data_structures[de9c3b5be789562e]::profiling::VerboseTimingGuard>::run::<(), <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate::{closure#0}::{closure#6}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:723:9
  25:     0x7ff0b85bcb41 - <rustc_session[ec4229a09ed780b3]::session::Session>::time::<(), <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate::{closure#0}::{closure#6}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:50
  26:     0x7ff0b85bcb41 - <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/lib.rs:1533:13
  27:     0x7ff0b85bcb41 - <rustc_data_structures[de9c3b5be789562e]::profiling::VerboseTimingGuard>::run::<(), <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_data_structures/src/profiling.rs:723:9
  28:     0x7ff0b85bcb41 - <rustc_session[ec4229a09ed780b3]::session::Session>::time::<(), <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_session/src/utils.rs:10:50
  29:     0x7ff0b6e65f2f - <rustc_resolve[6f864bfd50f0fb33]::Resolver>::resolve_crate
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_resolve/src/lib.rs:1524:9
  30:     0x7ff0b6e65f2f - rustc_interface[22044caa1f29908d]::passes::configure_and_expand
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/passes.rs:325:5
  31:     0x7ff0b6f22705 - <rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:202:29
  32:     0x7ff0b6f22705 - <rustc_interface[22044caa1f29908d]::queries::Query<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>>::compute::<<rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:43:41
  33:     0x7ff0b6f22705 - <core[3a7799eb5b53fe42]::option::Option<core[3a7799eb5b53fe42]::result::Result<rustc_data_structures[de9c3b5be789562e]::steal::Steal<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>, rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>>::get_or_insert_with::<<rustc_interface[22044caa1f29908d]::queries::Query<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>>::compute<<rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/option.rs:1593:49
  34:     0x7ff0b6f22705 - <rustc_interface[22044caa1f29908d]::queries::Query<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>>::compute::<<rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:43:17
  35:     0x7ff0b6f22705 - <core[3a7799eb5b53fe42]::cell::RefMut<core[3a7799eb5b53fe42]::option::Option<core[3a7799eb5b53fe42]::result::Result<rustc_data_structures[de9c3b5be789562e]::steal::Steal<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>, rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>>>::filter_map::<rustc_data_structures[de9c3b5be789562e]::steal::Steal<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>, <rustc_interface[22044caa1f29908d]::queries::Query<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>>::compute<<rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt::{closure#0}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/cell.rs:1588:15
  36:     0x7ff0b6f22705 - <rustc_interface[22044caa1f29908d]::queries::Query<&rustc_middle[d07bed17621820c2]::ty::context::GlobalCtxt>>::compute::<<rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:40:9
  37:     0x7ff0b6f22705 - <rustc_interface[22044caa1f29908d]::queries::Queries>::global_ctxt
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:187:9
  38:     0x7ff0b6300c08 - rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}::{closure#2}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:323:13
  39:     0x7ff0b6300c08 - <rustc_interface[22044caa1f29908d]::interface::Compiler>::enter::<rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}::{closure#2}, core[3a7799eb5b53fe42]::result::Result<core[3a7799eb5b53fe42]::option::Option<rustc_interface[22044caa1f29908d]::queries::Linker>, rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/queries.rs:383:19
  40:     0x7ff0b627c2e5 - rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_driver_impl/src/lib.rs:285:22
  41:     0x7ff0b627c2e5 - rustc_interface[22044caa1f29908d]::interface::run_compiler::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:299:21
  42:     0x7ff0b627c2e5 - rustc_span[82580b446b48c745]::with_source_map::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:1026:5
  43:     0x7ff0b6299299 - rustc_interface[22044caa1f29908d]::interface::run_compiler::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/interface.rs:293:13
  44:     0x7ff0b6299299 - <scoped_tls[3e8267cb6b5069b8]::ScopedKey<rustc_span[82580b446b48c745]::SessionGlobals>>::set::<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>
                               at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  45:     0x7ff0b629708f - rustc_span[82580b446b48c745]::create_session_globals_then::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}>
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_span/src/lib.rs:111:5
  46:     0x7ff0b629708f - rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals::<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/compiler/rustc_interface/src/util.rs:147:38
  47:     0x7ff0b629708f - std[6ee66c0b76df7c3f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys_common/backtrace.rs:121:18
  48:     0x7ff0b628d903 - <std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_::<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1}::{closure#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:560:17
  49:     0x7ff0b628d903 - <core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1}::{closure#0}> as core[3a7799eb5b53fe42]::ops::function::FnOnce<()>>::call_once
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/panic/unwind_safe.rs:271:9
  50:     0x7ff0b628d903 - std[6ee66c0b76df7c3f]::panicking::try::do_call::<core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:483:40
  51:     0x7ff0b628d903 - std[6ee66c0b76df7c3f]::panicking::try::<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panicking.rs:447:19
  52:     0x7ff0b628d903 - std[6ee66c0b76df7c3f]::panic::catch_unwind::<core[3a7799eb5b53fe42]::panic::unwind_safe::AssertUnwindSafe<<std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1}::{closure#0}>, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/panic.rs:140:14
  53:     0x7ff0b628d903 - <std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_::<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/thread/mod.rs:559:30
  54:     0x7ff0b628d903 - <<std[6ee66c0b76df7c3f]::thread::Builder>::spawn_unchecked_<rustc_interface[22044caa1f29908d]::util::run_in_thread_pool_with_globals<rustc_interface[22044caa1f29908d]::interface::run_compiler<core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>, rustc_driver_impl[c7adae1617edfc64]::run_compiler::{closure#1}>::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a7799eb5b53fe42]::result::Result<(), rustc_errors[e2c6533d414d421d]::ErrorGuaranteed>>::{closure#1} as core[3a7799eb5b53fe42]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /home/matthias/vcs/github/rust_debug_assertions/library/core/src/ops/function.rs:250:5
  55:     0x7ff0b3735098 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he94f0d2c6fa2933f
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1988:9
  56:     0x7ff0b3735098 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h81138e0c6d830c03
                               at /home/matthias/vcs/github/rust_debug_assertions/library/alloc/src/boxed.rs:1988:9
  57:     0x7ff0b3714785 - std::sys::unix::thread::Thread::new::thread_start::h439d4072ac7c5e1c
                               at /home/matthias/vcs/github/rust_debug_assertions/library/std/src/sys/unix/thread.rs:108:17
  58:     0x7ff0b389ebb5 - <unknown>
  59:     0x7ff0b3920d90 - <unknown>
  60:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error
```

</p>
</details>

**Comment by cyrgani** [comment]
`RustcEncodable` no longer exists since https://github.com/rust-lang/rust/pull/134272.
