### ISSUE TITLE
`./configure` doesn't allow setting hashmap toml values

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#108621]
I tried this code:

```sh
./configure --set llvm.build-config.LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES
```

I expected to see this happen: configure.py generates a toml file with the contents
```toml
build-config = {"LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN"="YES"}
```

Instead, this happened:
```
; ./configure --set llvm.build-config.LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES
configure: processing command line
configure: 
configure: llvm.build-config.LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN := YES
configure: build.configure-args := ['--set', 'llvm.build-config.LLVM_TEMPORARILY_ ...
Traceback (most recent call last):
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 486, in <module>
    configure_section(sections[section_key], section_config)
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 456, in configure_section
    lines[i] = "{} = {}".format(key, to_toml(value))
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 445, in to_toml
    raise RuntimeError('no toml')
RuntimeError: no toml
```

### Meta

HEAD is branched from 5423745db8b434fcde54888b35f518f00cce00e4.

**Comment by jyn514** [comment]
Relevant code: https://github.com/rust-lang/rust/blob/901241f3ecf5ae16eef89a129f3fb83973b26534/src/bootstrap/configure.py#L426-L445

**Comment by KittyBorgX** [comment]
I have a PR ready but I need to wait for #108618 to get merged since that PR was `master -> master` and creating a new branch now doesn't help 😔

**Comment by albertlarsan68** [comment]
You can run `git checkout upstream/master` (replace `upstream` with the name of the rust-lang remote), then run `git switch -c <new branch name>`.
In the future, take the habit of always having your `master` branch fast-forward able, it will avoid you hassles with the GitHub UI.

**Comment by KittyBorgX** [comment]
That worked for me, Thank you so much!
