### ISSUE TITLE
Panic in compilation of project using openssl (vendored)

### ISSUE THREAD

**Issue by franklinblanco** [rust-lang/rust#108785]
### Description
I'm getting this error when cross compiling a project that has `openssl` with the `vendored` feature from `aarch64-apple-darwin` to `x86_64-unknown-linux-gnu`. 
In the past this was not a problem, I could do this just fine for the last 8 months. And after removing the `openssl` dependency I can do it perfectly.
If you're wondering how I setup the linkers, pretty much just followed [this guide](https://github.com/messense/homebrew-macos-cross-toolchains)
Tried to switch to rustc version 1.63. Same issue, nightly rust as well.
Openssl dep: [rust-openssl](https://github.com/sfackler/rust-openssl)
### Code

```Rust
NONE
```
(No code, tested on a literal empty project.)

### Meta

`rustc --version --verbose`:
```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: aarch64-apple-darwin
release: 1.67.1
LLVM version: 15.0.6
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_codegen_llvm/src/back/archive.rs:367:33
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Compiling openssl-sys v0.9.80
   Compiling openssl v0.10.45
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_codegen_llvm/src/back/archive.rs:367:33
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_codegen_llvm::back::archive::LlvmArchiveBuilder as rustc_codegen_ssa::back::archive::ArchiveBuilder>::build
   4: rustc_codegen_ssa::back::link::link_binary
   5: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::link
   6: <rustc_interface::queries::Linker>::link
   7: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
   8: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.1 (d5a82bbd2 2023-02-07) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C linker=x86_64-unknown-linux-gnu-gcc

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `openssl-sys`
```

</p>
</details>

**Comment by clubby789** [comment]
Looks like a duplicate of #108648

**Comment by franklinblanco** [comment]
Duplicate indeed! Thanks
