### ISSUE TITLE
UdpSocket::bind(bind_addr).unwrap() panics under VS2022 debugger

### ISSUE THREAD

**Issue by parthopdas** [rust-lang/rust#108753]
(original: https://github.com/kitamstudios/rust-analyzer.vs/issues/14)

I tried this code (nothing in Cargo.toml):

```rust
// Steps
// - In VS2022, install https://marketplace.visualstudio.com/items?itemName=kitamstudios.RustAnalyzer&ssr=false#overview
// - cargo new soc --bin
// - Open folder soc in VS2022
//
use std::net::{SocketAddr, UdpSocket};

fn main() {
    let bind_addr = SocketAddr::from(([127, 0, 0, 1], 54321));
    let x = UdpSocket::bind(bind_addr).unwrap();
    eprintln!("{:?}", x);
}
```

I expected to see this happen: 
Running under the visual studio debugger should give the same results as cargo run.

Instead, this happened: *explanation*

1. Debug in VS2022 (i.e. using this rust-analyzer.vs extension) panics with ```Exception thrown at 0x00007FFB7B34CD29 in server.exe: Microsoft C++ exception:  ?? ::st_panic at memory location 0x000000A01290EF20.```.
1. cargo build --profile dev succeeds, run exe gives ```UdpSocket { addr: 127.0.0.1:54321, socket: 236 }```
1. cargo build --profile dev suceeds, open exe in vs and run under debugger gives the same as above ``````UdpSocket { addr: 127.0.0.1:54321, socket: 236 }``````

### Meta

`rustc --version --verbose`:
```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
cargo 1.67.1 (8ecd4f20a 2023-01-10)
Building on stable-x86_64-pc-windows-msvc
(Visual Studio Community 2022 (64-bit) Version 17.5.1)
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 10106, kind: Uncategorized, message: "The requested service provider could not be loaded or initialized." }', src\main.rs:5:40
stack backtrace:
   0:     0x7ff64207b1a2 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff64207b1a2 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff64207b1a2 - std::sys_common::backtrace::_print_fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:65
   3:     0x7ff64207b1a2 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff64208ac6b - core::fmt::write
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\fmt\mod.rs:1208
   5:     0x7ff64207846a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\io\mod.rs:1682
   6:     0x7ff64207aeeb - std::sys_common::backtrace::_print
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:47
   7:     0x7ff64207aeeb - std::sys_common::backtrace::print
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff64207d0e9 - std::panicking::default_hook::closure$1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:267
   9:     0x7ff64207cd6b - std::panicking::default_hook
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:286
  10:     0x7ff64207d981 - std::panicking::rust_panic_with_hook
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:688
  11:     0x7ff64207d70e - std::panicking::begin_panic_handler::closure$0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:579
  12:     0x7ff64207bbbf - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\sys_common\backtrace.rs:137
  13:     0x7ff64207d3c0 - std::panicking::begin_panic_handler
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
  14:     0x7ff642090c95 - core::panicking::panic_fmt
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
  15:     0x7ff6420910b6 - core::result::unwrap_failed
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\result.rs:1791
  16:     0x7ff642072545 - enum2$<core::result::Result<std::net::udp::UdpSocket,std::io::error::Error> >::unwrap<std::net::udp::UdpSocket,std::io::error::Error>
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\result.rs:1113
  17:     0x7ff6420727fd - soc::main
                               at D:\src\delme\soc\src\main.rs:5
  18:     0x7ff642071a3b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\core\src\ops\function.rs:507
  19:     0x7ff64207112e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\sys_common\backtrace.rs:121
  20:     0x7ff64207112e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\sys_common\backtrace.rs:121
  21:     0x7ff642071f81 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\rt.rs:166
  22:     0x7ff64207575e - core::ops::function::impls::impl$2::call_once
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\ops\function.rs:606
  23:     0x7ff64207575e - std::panicking::try::do_call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:483
  24:     0x7ff64207575e - std::panicking::try
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:447
  25:     0x7ff64207575e - std::panic::catch_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panic.rs:137
  26:     0x7ff64207575e - std::rt::lang_start_internal::closure$2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\rt.rs:148
  27:     0x7ff64207575e - std::panicking::try::do_call
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:483
  28:     0x7ff64207575e - std::panicking::try
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:447
  29:     0x7ff64207575e - std::panic::catch_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panic.rs:137
  30:     0x7ff64207575e - std::rt::lang_start_internal
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\rt.rs:148
  31:     0x7ff642071f5a - std::rt::lang_start<tuple$<> >
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483\library\std\src\rt.rs:165
  32:     0x7ff6420728b9 - main
  33:     0x7ff64208f54c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  34:     0x7ff64208f54c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  35:     0x7fff3db126bd - BaseThreadInitThunk
  36:     0x7fff3e4aa9f8 - RtlUserThreadStart

```

</p>
</details>

**Comment by parthopdas** [comment]
some more context

unwrap implementation clearly says it will panic if Result is Err - that is also my understanding of Rust.

https://github.com/rust-lang/rust/blob/f15f0ea73972786e426732c5b92ba9a904b866c4/library/core/src/result.rs#L1081-L1092

and

https://github.com/rust-lang/rust/blob/f15f0ea73972786e426732c5b92ba9a904b866c4/library/core/src/result.rs#L1744-L1752

so i think the debugger is right and cargo run has a bug where the panic is not getting triggered.

or the UdpBind is not happening for reason under the debugger.

**Comment by parthopdas** [comment]
not a bug.
