### ISSUE TITLE
ICE: return_position_impl_trait_in_trait + -Zlower-impl-trait-in-trait-to-assoc-ty

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#108756]
### Code

```Rust
#![feature(return_position_impl_trait_in_trait)]

trait Foo {
    fn bar(x: bool) -> impl Sized {
        if x {
            let _: u32 = Self::bar(!x);
        }
        Default::default()
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (44cfafe2f 2023-03-03)
binary: rustc
commit-hash: 44cfafe2fafe816395d3acc434663a45d5178c41
commit-date: 2023-03-03
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output
rustc -Zlower-impl-trait-in-trait-to-assoc-ty  --edition=2018 --crate-type lib file.rs
```
feature is unstable bla
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/context.rs:2438:55
stack backtrace:
   0:     0x7f005cd66afa - std::backtrace_rs::backtrace::libunwind::trace::h03465bf7db0a5bcb
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f005cd66afa - std::backtrace_rs::backtrace::trace_unsynchronized::hbbaffc0ea2e34ac1
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f005cd66afa - std::sys_common::backtrace::_print_fmt::h1d5b1e20ba71cca1
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f005cd66afa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h165ce139917464b9
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f005cdca27e - core::fmt::write::h2792ed374dfffc16
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f005cd59a65 - std::io::Write::write_fmt::h2cc74f32d7d965fd
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/io/mod.rs:1684:15
   6:     0x7f005cd668c5 - std::sys_common::backtrace::_print::h0f11964b8176847a
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f005cd668c5 - std::sys_common::backtrace::print::h470b2efe95139481
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f005cd6963f - std::panicking::default_hook::{{closure}}::h5390a93f85440547
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/panicking.rs:271:22
   9:     0x7f005cd6937b - std::panicking::default_hook::h55ab5fc49931b8c6
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/panicking.rs:290:9
  10:     0x7f005ffcea65 - rustc_driver_impl[d015eba24dbec9f4]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f005cd69e7d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf5a4865832d21b27
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/alloc/src/boxed.rs:2001:9
  12:     0x7f005cd69e7d - std::panicking::rust_panic_with_hook::h2cb5caacebd97de6
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/panicking.rs:696:13
  13:     0x7f005cd69bb2 - std::panicking::begin_panic_handler::{{closure}}::h9fd7c58afac75693
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/panicking.rs:581:13
  14:     0x7f005cd66f66 - std::sys_common::backtrace::__rust_end_short_backtrace::hd4720a754ddf6dfd
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f005cd69902 - rust_begin_unwind
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/panicking.rs:579:5
  16:     0x7f005cdc65e3 - core::panicking::panic_fmt::heb69d5c12120d37b
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/panicking.rs:64:14
  17:     0x7f005cdc667d - core::panicking::panic::h7951c76eac1ab789
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/panicking.rs:114:5
  18:     0x7f005e135c92 - <rustc_middle[5d26472a27b225ef]::ty::context::TyCtxt>::local_def_id_to_hir_id
  19:     0x7f005e62cae7 - rustc_ty_utils[b504107688b3e259]::ty::param_env
  20:     0x7f005e62a969 - rustc_query_system[b004d522c7f04025]::query::plumbing::try_execute_query::<rustc_query_impl[90210f7f475d36bc]::queries::param_env, rustc_query_impl[90210f7f475d36bc]::plumbing::QueryCtxt>
  21:     0x7f005e62a1b0 - <rustc_query_impl[90210f7f475d36bc]::Queries as rustc_middle[5d26472a27b225ef]::ty::query::QueryEngine>::param_env
  22:     0x7f005ec8b794 - rustc_hir_analysis[3ca3b9af3da40c63]::check::compare_impl_item::check_type_bounds
  23:     0x7f005ec6dd41 - rustc_hir_analysis[3ca3b9af3da40c63]::check::check::check_mod_item_types
  24:     0x7f005f6534e1 - rustc_query_system[b004d522c7f04025]::query::plumbing::try_execute_query::<rustc_query_impl[90210f7f475d36bc]::queries::check_mod_item_types, rustc_query_impl[90210f7f475d36bc]::plumbing::QueryCtxt>
  25:     0x7f005f65308a - <rustc_query_impl[90210f7f475d36bc]::Queries as rustc_middle[5d26472a27b225ef]::ty::query::QueryEngine>::check_mod_item_types
  26:     0x7f005f6c7a2f - <rustc_middle[5d26472a27b225ef]::hir::map::Map>::for_each_module::<rustc_hir_analysis[3ca3b9af3da40c63]::check_crate::{closure#6}::{closure#0}>
  27:     0x7f005e2c7bd8 - rustc_hir_analysis[3ca3b9af3da40c63]::check_crate
  28:     0x7f005e2bbe62 - rustc_interface[26c5cf3d4e6d8495]::passes::analysis
  29:     0x7f005f82d65d - rustc_query_system[b004d522c7f04025]::query::plumbing::try_execute_query::<rustc_query_impl[90210f7f475d36bc]::queries::analysis, rustc_query_impl[90210f7f475d36bc]::plumbing::QueryCtxt>
  30:     0x7f005f82d35f - <rustc_query_impl[90210f7f475d36bc]::Queries as rustc_middle[5d26472a27b225ef]::ty::query::QueryEngine>::analysis
  31:     0x7f005f656876 - <rustc_middle[5d26472a27b225ef]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[d015eba24dbec9f4]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>>
  32:     0x7f005f23fc18 - rustc_span[9d0cfc316ec6e1cb]::with_source_map::<core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>, rustc_interface[26c5cf3d4e6d8495]::interface::run_compiler<core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>, rustc_driver_impl[d015eba24dbec9f4]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  33:     0x7f005f23729c - std[ca26bff2e1d562d1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[26c5cf3d4e6d8495]::util::run_in_thread_pool_with_globals<rustc_interface[26c5cf3d4e6d8495]::interface::run_compiler<core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>, rustc_driver_impl[d015eba24dbec9f4]::run_compiler::{closure#1}>::{closure#0}, core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>>
  34:     0x7f005f236cca - <<std[ca26bff2e1d562d1]::thread::Builder>::spawn_unchecked_<rustc_interface[26c5cf3d4e6d8495]::util::run_in_thread_pool_with_globals<rustc_interface[26c5cf3d4e6d8495]::interface::run_compiler<core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>, rustc_driver_impl[d015eba24dbec9f4]::run_compiler::{closure#1}>::{closure#0}, core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c472ba66930c5d6]::result::Result<(), rustc_span[9d0cfc316ec6e1cb]::ErrorGuaranteed>>::{closure#1} as core[7c472ba66930c5d6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7f005cd73cb3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h53b8e926121c1b9a
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/alloc/src/boxed.rs:1987:9
  36:     0x7f005cd73cb3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he5a7c9fb3937128b
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/alloc/src/boxed.rs:1987:9
  37:     0x7f005cd73cb3 - std::sys::unix::thread::Thread::new::thread_start::hadeb8936ad30fb42
                               at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7f005cb06bb5 - <unknown>
  39:     0x7f005cb88d90 - <unknown>
  40:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (44cfafe2f 2023-03-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z lower-impl-trait-in-trait-to-assoc-ty --crate-type lib

query stack during panic:
#0 [param_env] computing normalized predicates of `Foo::{opaque#0}`
#1 [check_mod_item_types] checking item types in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
warning: 1 warning emitted
```

</p>
</details>

**Comment by compiler-errors** [comment]
Don't start testing this flag yet. It's incredibly unstable and **will** ICE, and we don't need to clog the issues page with it.
