### ISSUE TITLE
build: bootstrap panics when using the --llvm-root option

### ISSUE THREAD

**Issue by filnet** [rust-lang/rust#109194]
### Issue

Building rust with the `--llvm-root` option fails with a "missing llvm-tools" error.

Reverting https://github.com/rust-lang/rust/commit/23a34c18f7b2ce8b20fed717ef48e2be1776246b fixes the issue.

The install llvm-tools step should be skipped if no tarball is provided.
This happens when --llvm-root is used (i.e. externally provided llvm).

### Version it worked on

It most recently worked on: Rust 1.67.1

### Version with regression

Rust 1.68.0

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'missing llvm-tools', install.rs:215:14
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: core::option::Option<T>::expect
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\library\core\src\option.rs:786:21
   6: <bootstrap::install::LlvmTools as bootstrap::builder::Step>::run
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\install.rs:213:23
   7: bootstrap::builder::Builder::ensure
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\builder.rs:1966:23
   8: <bootstrap::install::LlvmTools as bootstrap::builder::Step>::make_run
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\install.rs:150:17
   9: bootstrap::builder::StepDescription::maybe_run
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\builder.rs:297:13
  10: bootstrap::builder::StepDescription::run
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\builder.rs:334:21
  11: bootstrap::builder::Builder::run_step_descriptions
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\builder.rs:893:9
  12: bootstrap::builder::Builder::execute_cli
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\builder.rs:873:9
  13: bootstrap::Build::build
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\lib.rs:748:17
  14: bootstrap::main
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\bin\main.rs:50:5
  15: core::ops::function::FnOnce::call_once
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\library\core\src\ops\function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:32
```

</p>
</details>

**Comment by filnet** [comment]
I filed a somewhat similar regression yesterday : https://github.com/rust-lang/rust/issues/109103

Related: https://github.com/rust-lang/rust/commit/e5c92bc2b6f0bd69856ad3c4d3056c7f0c0ad72d

**Comment by filnet** [comment]
fixed by https://github.com/rust-lang/rust/pull/109256
