### ISSUE TITLE
thread 'rustc' panicked at 'no entry found for key'

### ISSUE THREAD

**Issue by Jasha10** [rust-lang/rust#109329]
I got a compiler panic and am posting the stack trace here.
After running `cargo clean`, I'm no longer able to reproduce the crash.
I'm not sure if the below info will be helpful; feel free to close this issue if it's not.

<details>

```
$ cargo test
   Compiling sierrachart_dtc v0.1.0 (/home/homestar/dev/mrepo_wip/src_rs/trading/sierrachart_dtc)
thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:655:9
stack backtrace:
   0:     0x7f4b4dbee59a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4b4dbee59a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4b4dbee59a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4b4dbee59a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4b4dc5039e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f4b4dbdebe5 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x7f4b4dbee365 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f4b4dbee365 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f4b4dbf112f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x7f4b4dbf0e6b - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x7f4b50f3d6e4 - <rustc_driver[f4ad927b3c57833d]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[d16e85342ea223d9]::ops::function::FnOnce<(&core[d16e85342ea223d9]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f4b4dbf196a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4e6ced11e07d8b24
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  12:     0x7f4b4dbf196a - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
  13:     0x7f4b4dbf16e9 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  14:     0x7f4b4dbeea4c - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f4b4dbf13f2 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  16:     0x7f4b4dc4cd43 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  17:     0x7f4b4dc4ceb1 - core::panicking::panic_display::h20dbb78c57df5693
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
  18:     0x7f4b4dc4ce5b - core::panicking::panic_str::hb46d5710e4ab412a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
  19:     0x7f4b4dc4cac6 - core::option::expect_failed::h0b5d04c30548770b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
  20:     0x7f4b518b82ef - rustc_query_impl[3a6baddf07124ab7]::plumbing::try_load_from_on_disk_cache::<rustc_query_impl[3a6baddf07124ab7]::queries::local_def_id_to_hir_id>
  21:     0x7f4b5071c52e - <rustc_query_system[e5b40bf290de15d8]::dep_graph::graph::DepGraph<rustc_middle[eb7209f5870e9fb7]::dep_graph::dep_node::DepKind>>::exec_cache_promotions::<rustc_middle[eb7209f5870e9fb7]::ty::context::TyCtxt>
  22:     0x7f4b5071c338 - <rustc_query_impl[3a6baddf07124ab7]::on_disk_cache::OnDiskCache as rustc_middle[eb7209f5870e9fb7]::ty::context::OnDiskCache>::drop_serialized_data
  23:     0x7f4b501f3ddb - rustc_data_structures[f387d52c0b9780fc]::sync::join::<rustc_incremental[16ae4fc8a33f2de9]::persist::save::save_dep_graph::{closure#0}::{closure#2}, rustc_incremental[16ae4fc8a33f2de9]::persist::save::save_dep_graph::{closure#0}::{closure#3}, (), ()>
  24:     0x7f4b5011cb80 - <rustc_middle[eb7209f5870e9fb7]::dep_graph::dep_node::DepKind as rustc_query_system[e5b40bf290de15d8]::dep_graph::DepKind>::with_deps::<rustc_incremental[16ae4fc8a33f2de9]::persist::save::save_dep_graph::{closure#0}, ()>
  25:     0x7f4b5011c92a - <rustc_session[b580c712976fc965]::session::Session>::time::<(), <rustc_interface[3781616314f5d936]::interface::Compiler>::enter<rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}::{closure#2}, core[d16e85342ea223d9]::result::Result<core[d16e85342ea223d9]::option::Option<rustc_interface[3781616314f5d936]::queries::Linker>, rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}>
  26:     0x7f4b5011b45d - rustc_span[4bb3e3ecb57f95d5]::with_source_map::<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  27:     0x7f4b50113ce4 - <scoped_tls[1a6b834cb64348ef]::ScopedKey<rustc_span[4bb3e3ecb57f95d5]::SessionGlobals>>::set::<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  28:     0x7f4b501133e2 - std[3da461b304582a2c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3781616314f5d936]::util::run_in_thread_pool_with_globals<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  29:     0x7f4b5011318a - <<std[3da461b304582a2c]::thread::Builder>::spawn_unchecked_<rustc_interface[3781616314f5d936]::util::run_in_thread_pool_with_globals<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#1} as core[d16e85342ea223d9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f4b4dbfb823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  31:     0x7f4b4dbfb823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  32:     0x7f4b4dbfb823 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7f4b4daa9609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  34:     0x7f4b4d9cc133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  35:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0 (2c8cc3432 2023-03-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `sierrachart_dtc`
```

</details>

```
$ rustc --version --verbose
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-unknown-linux-gnu
release: 1.68.0
LLVM version: 15.0.6
```

**Comment by kpreid** [comment]
Relabeling issues which don't have a runnable reproduction (as opposed to not having a minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by RodBurman** [comment]
Without a way to reproduce this is going to be very difficult to fix (or test that it is fixed). I suggest closing it and redirecting to 
[mozilla/rust#101058](https://u307627.ct.sendgrid.net/ls/click?upn=u001.xF3SHJBu3q9pccTCoOA3ftIVa9u-2Fug1f20adLrStT16KRjf-2FxWsRri2lVLjD8vTRJcQwEuLdP-2BeOVQW91iJYv0hV-2BKsvsoEiMQ4l7TNIth8-3DXG_m_nFoAzWzcsCTF0BaeVhlvThAmTplURPCkO0XdK0RrWNahz-2FjjFPLmmvVYXXSD-2BPcCMSm5-2BTm0cgSR-2BGjX-2B-2BDWH7BNfSBzOYiGYzauFDa-2BSLaG7P-2B2tN7KJTNT-2B39ypE5WdPEEpRFQERPfdLSBRFcvgtUxFfiytdW1CrdPFejOynSTsLN9KkFj1BAevtxJmVsH6U4ETdWZHfghclytY-2FSJIQ-3D-3D) **Compilation suddenly stopped working; Cargo clean fixed the problem**
Which has the same cure and so may be the same problem which I am guessing is something to do with caching in incremental compiles and the "cargo clean" causes compilation to start again from zero cache.
I am pretty sure I saw a third instance of  a similar problem, but can't find it. :(

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
