### ISSUE TITLE
The compiler suggested i send this message to you

### ISSUE THREAD

**Issue by jmsunseri** [rust-lang/rust#109339]
### Code
https://gitlab.com/jmsunseri/dev-remenants/-/commits/git-search

### Meta

`rustc --version --verbose`:
```
<version>
➜  dev-remenants git:(git-search) rustc --version --verbose
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-unknown-linux-gnu
release: 1.68.0
LLVM version: 15.0.6
```

### Error output
error: internal compiler error: compiler/rustc_infer/src/infer/region_constraints/mod.rs:568:17: cannot relate bound region: ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed(DefId(0:199 ~ dev_remenants[a0e3]::is_ignored::'_), '_) }) <= '_#3r

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/compiler/rustc_errors/src/lib.rs:987:33
stack backtrace:
   0:     0x7f03e816659a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f03e816659a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f03e816659a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f03e816659a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f03e81c839e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f03e8156be5 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x7f03e8166365 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f03e8166365 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f03e816912f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x7f03e8168e6b - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x7f03eb4b56e4 - <rustc_driver[f4ad927b3c57833d]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[d16e85342ea223d9]::ops::function::FnOnce<(&core[d16e85342ea223d9]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f03e816996a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4e6ced11e07d8b24
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  12:     0x7f03e816996a - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
  13:     0x7f03eb771501 - std[3da461b304582a2c]::panicking::begin_panic::<rustc_errors[41d09747e2f98dea]::ExplicitBug>::{closure#0}
  14:     0x7f03eb769e56 - std[3da461b304582a2c]::sys_common::backtrace::__rust_end_short_backtrace::<std[3da461b304582a2c]::panicking::begin_panic<rustc_errors[41d09747e2f98dea]::ExplicitBug>::{closure#0}, !>
  15:     0x7f03eb7f9df6 - std[3da461b304582a2c]::panicking::begin_panic::<rustc_errors[41d09747e2f98dea]::ExplicitBug>
  16:     0x7f03eb7f9de6 - std[3da461b304582a2c]::panic::panic_any::<rustc_errors[41d09747e2f98dea]::ExplicitBug>
  17:     0x7f03eb7f8b92 - <rustc_errors[41d09747e2f98dea]::HandlerInner>::span_bug::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span, &alloc[5b05b59796bdfb5c]::string::String>
  18:     0x7f03eb7f8a37 - <rustc_errors[41d09747e2f98dea]::Handler>::span_bug::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span, &alloc[5b05b59796bdfb5c]::string::String>
  19:     0x7f03eb7adf9b - rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>::{closure#0}
  20:     0x7f03eb7adfea - rustc_middle[eb7209f5870e9fb7]::ty::context::tls::with_opt::<rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f03eb7ad0aa - rustc_middle[eb7209f5870e9fb7]::ty::context::tls::with_context_opt::<rustc_middle[eb7209f5870e9fb7]::ty::context::tls::with_opt<rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f03eb7acfd6 - rustc_middle[eb7209f5870e9fb7]::util::bug::opt_span_bug_fmt::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>
  23:     0x7f03eb7acf94 - rustc_middle[eb7209f5870e9fb7]::util::bug::span_bug_fmt::<rustc_span[4bb3e3ecb57f95d5]::span_encoding::Span>
  24:     0x7f03e9443fa4 - <rustc_middle[eb7209f5870e9fb7]::ty::sty::Region as rustc_middle[eb7209f5870e9fb7]::ty::relate::Relate>::relate::<rustc_infer[41785f830319e09c]::infer::equate::Equate>
  25:     0x7f03e943f25f - rustc_middle[eb7209f5870e9fb7]::ty::relate::super_relate_tys::<rustc_infer[41785f830319e09c]::infer::equate::Equate>
  26:     0x7f03e943c25e - <rustc_infer[41785f830319e09c]::infer::equate::Equate as rustc_middle[eb7209f5870e9fb7]::ty::relate::TypeRelation>::tys
  27:     0x7f03e9d75d23 - <rustc_infer[41785f830319e09c]::infer::InferCtxt>::commit_if_ok::<rustc_infer[41785f830319e09c]::infer::InferOk<()>, rustc_middle[eb7209f5870e9fb7]::ty::error::TypeError, <rustc_infer[41785f830319e09c]::infer::at::Trace>::eq<rustc_middle[eb7209f5870e9fb7]::ty::Ty>::{closure#0}>
  28:     0x7f03e9d75c16 - <rustc_infer[41785f830319e09c]::infer::at::At>::eq::<rustc_middle[eb7209f5870e9fb7]::ty::Ty>
  29:     0x7f03ec093bfe - <rustc_infer[41785f830319e09c]::infer::InferCtxt>::can_eq::<rustc_middle[eb7209f5870e9fb7]::ty::Ty>
  30:     0x7f03ec076b42 - rustc_trait_selection[94d7ef6b5a6b8462]::traits::error_reporting::suggestions::hint_missing_borrow
  31:     0x7f03ec119fe4 - <rustc_infer[41785f830319e09c]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[94d7ef6b5a6b8462]::traits::error_reporting::suggestions::TypeErrCtxtExt>::report_closure_arg_mismatch
  32:     0x7f03ec129e38 - <rustc_infer[41785f830319e09c]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[94d7ef6b5a6b8462]::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  33:     0x7f03ec133817 - <rustc_infer[41785f830319e09c]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[94d7ef6b5a6b8462]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  34:     0x7f03ec126e7f - <rustc_infer[41785f830319e09c]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[94d7ef6b5a6b8462]::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors
  35:     0x7f03e95d07dd - <rustc_hir_typeck[7533f7cabd9af3c4]::fn_ctxt::FnCtxt>::type_inference_fallback
  36:     0x7f03e95bb86b - rustc_hir_typeck[7533f7cabd9af3c4]::typeck
  37:     0x7f03e9529bf7 - <rustc_query_system[e5b40bf290de15d8]::dep_graph::graph::DepGraph<rustc_middle[eb7209f5870e9fb7]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[eb7209f5870e9fb7]::ty::context::TyCtxt, rustc_span[4bb3e3ecb57f95d5]::def_id::LocalDefId, &rustc_middle[eb7209f5870e9fb7]::ty::typeck_results::TypeckResults>
  38:     0x7f03e952174b - rustc_query_system[e5b40bf290de15d8]::query::plumbing::try_execute_query::<rustc_query_impl[3a6baddf07124ab7]::queries::typeck, rustc_query_impl[3a6baddf07124ab7]::plumbing::QueryCtxt>
  39:     0x7f03eac08aad - rustc_data_structures[f387d52c0b9780fc]::sync::par_for_each_in::<&[rustc_span[4bb3e3ecb57f95d5]::def_id::LocalDefId], <rustc_middle[eb7209f5870e9fb7]::hir::map::Map>::par_body_owners<rustc_hir_typeck[7533f7cabd9af3c4]::typeck_item_bodies::{closure#0}>::{closure#0}>
  40:     0x7f03eac08853 - rustc_hir_typeck[7533f7cabd9af3c4]::typeck_item_bodies
  41:     0x7f03eac1fa07 - <rustc_query_system[e5b40bf290de15d8]::dep_graph::graph::DepGraph<rustc_middle[eb7209f5870e9fb7]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[eb7209f5870e9fb7]::ty::context::TyCtxt, (), ()>
  42:     0x7f03eaa328e6 - rustc_query_system[e5b40bf290de15d8]::query::plumbing::try_execute_query::<rustc_query_impl[3a6baddf07124ab7]::queries::typeck_item_bodies, rustc_query_impl[3a6baddf07124ab7]::plumbing::QueryCtxt>
  43:     0x7f03eae6eefb - <rustc_query_impl[3a6baddf07124ab7]::Queries as rustc_middle[eb7209f5870e9fb7]::ty::query::QueryEngine>::typeck_item_bodies
  44:     0x7f03e9960892 - <rustc_session[b580c712976fc965]::session::Session>::time::<(), rustc_hir_analysis[9174c993ab369dfd]::check_crate::{closure#7}>
  45:     0x7f03e995fd12 - rustc_hir_analysis[9174c993ab369dfd]::check_crate
  46:     0x7f03e995f96b - rustc_interface[3781616314f5d936]::passes::analysis
  47:     0x7f03eabd7b16 - <rustc_query_system[e5b40bf290de15d8]::dep_graph::graph::DepGraph<rustc_middle[eb7209f5870e9fb7]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[eb7209f5870e9fb7]::ty::context::TyCtxt, (), core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  48:     0x7f03eabd6cd1 - rustc_query_system[e5b40bf290de15d8]::query::plumbing::try_execute_query::<rustc_query_impl[3a6baddf07124ab7]::queries::analysis, rustc_query_impl[3a6baddf07124ab7]::plumbing::QueryCtxt>
  49:     0x7f03eae6b7aa - <rustc_query_impl[3a6baddf07124ab7]::Queries as rustc_middle[eb7209f5870e9fb7]::ty::query::QueryEngine>::analysis
  50:     0x7f03ea695850 - <rustc_interface[3781616314f5d936]::passes::QueryContext>::enter::<rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  51:     0x7f03ea6932c4 - rustc_span[4bb3e3ecb57f95d5]::with_source_map::<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  52:     0x7f03ea68bce4 - <scoped_tls[1a6b834cb64348ef]::ScopedKey<rustc_span[4bb3e3ecb57f95d5]::SessionGlobals>>::set::<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  53:     0x7f03ea68b3e2 - std[3da461b304582a2c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3781616314f5d936]::util::run_in_thread_pool_with_globals<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>
  54:     0x7f03ea68b18a - <<std[3da461b304582a2c]::thread::Builder>::spawn_unchecked_<rustc_interface[3781616314f5d936]::util::run_in_thread_pool_with_globals<rustc_interface[3781616314f5d936]::interface::run_compiler<core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>, rustc_driver[f4ad927b3c57833d]::run_compiler::{closure#1}>::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d16e85342ea223d9]::result::Result<(), rustc_errors[41d09747e2f98dea]::ErrorGuaranteed>>::{closure#1} as core[d16e85342ea223d9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  55:     0x7f03e8173823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  56:     0x7f03e8173823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  57:     0x7f03e8173823 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  58:     0x7f03e7f1312d - start_thread
  59:     0x7f03e7f94bc0 - clone3
  60:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0 (2c8cc3432 2023-03-06) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `is_ignored`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `dev-remenants`
```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by workingjubilee** [comment]
Thank you for reporting an ICE!

Which commit of your repo did this break on?

**Comment by jmsunseri** [comment]
the last one.  i don't think this is still an issue.  i tried to compile using the nightly and it doesn't compile but at least it doesn't crash

**Comment by jmsunseri** [comment]
```
error[E0631]: type mismatch in closure arguments
   --> src/main.rs:202:29
    |
202 |     git_ignore_files.iter().any(|f: File| f.is_excluded(&dir_entry.path()) )
    |                             ^^^ --------- found signature defined here
    |                             |
    |                             expected due to this
    |
    = note: expected closure signature `fn(&gitignore::File<'_>) -> _`
               found closure signature `for<'a> fn(gitignore::File<'a>) -> _`
note: required by a bound in `any`
   --> /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/core/src/iter/traits/iterator.rs:2692:5
help: consider borrowing the argument
    |
202 |     git_ignore_files.iter().any(|f: &File| f.is_excluded(&dir_entry.path()) )
    |                                     +

For more information about this error, try `rustc --explain E0631`.
error: could not compile `dev-remenants` (bin "dev-remenants") due to previous error
```

**Comment by workingjubilee** [comment]
Cool!
For later reference, that commit SHA is 019fdacf906f1bb4c662bd2e9001349c84cf79ee
We'll probably close this if it is indeed fixed already, yeah, but maybe it's related to incremental compilation or something else!

**Comment by aliemjay** [comment]
This is fixed in latest nightly with sufficient tests. Closing in favor of https://github.com/rust-lang/rust/issues/109361 which has an MCVE and to track a possible stable backport.
