### ISSUE TITLE
"internal compiler error: var types encountered in super_relate_consts" from const generic type with default

### ISSUE THREAD

**Issue by NightEule5** [rust-lang/rust#109584]
I'm using const generics on a trait and a struct, with a default value on the struct's parameter. When the const parameter on the struct is omitted erroneously (the trait bound requires `N` to be specified), the compiler panics instead of catching the error. I would expect it to complain about mismatched generic parameters, correcting `wrong_const: Struct` to `wrong_const: Struct<N>`.

### Code

```Rust
const DEFAULT: usize = 0;

trait Trait<const N: usize> { }

struct Struct<const N: usize = DEFAULT>;

impl<const N: usize> Struct<N> {
    fn foo<T: Trait<N>>(&self, _: T) { }
}

fn bar<const N: usize, T: Trait<N>>(wrong_const: Struct, trait_usage: T) {
    wrong_const.foo(trait_usage)
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (574b64a97 2022-12-31)
binary: rustc
commit-hash: 574b64a97f52162f965bc201e47f0af8279ca65d
commit-date: 2022-12-31
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Error output

```
error: internal compiler error: /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/compiler/rustc_middle/src/ty/relate.rs:638:13: var types encountered in super_relate_consts: Const { ty: usize, kind: Infer(Var(_#0c)) } Const { ty: usize, kind: Value(Leaf(0x0000000000000000)) }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/compiler/rustc_errors/src/lib.rs:1581:9
stack backtrace:
   0:     0x7f86259652ba - std::backtrace_rs::backtrace::libunwind::trace::h58220cc92d95af9d
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f86259652ba - std::backtrace_rs::backtrace::trace_unsynchronized::h5baad1b6045f1862
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f86259652ba - std::sys_common::backtrace::_print_fmt::h00cd15ad313be7cd
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f86259652ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha3c10c2df3801f2e
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f86259c83be - core::fmt::write::h15687caa14f55ffa
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f8625955865 - std::io::Write::write_fmt::h9b3ae37b79923fd4
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/io/mod.rs:1682:15
   6:     0x7f8625965085 - std::sys_common::backtrace::_print::hec732d08a877f27f
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f8625965085 - std::sys_common::backtrace::print::h21a7b69d4e96b04e
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f8625967e4f - std::panicking::default_hook::{{closure}}::h4dd038b046e67fff
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:267:22
   9:     0x7f8625967b8b - std::panicking::default_hook::h09d820041cd6bd93
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:286:9
  10:     0x7f8628c44114 - rustc_driver[7a1e5a3798cd51b2]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f862596868d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he092a4fd9b28e6e1
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:2002:9
  12:     0x7f862596868d - std::panicking::rust_panic_with_hook::he7925d19e6d87b9f
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/panicking.rs:692:13
  13:     0x7f86290f4021 - std[eb796f4691fa113e]::panicking::begin_panic::<rustc_errors[d698377914337e8]::ExplicitBug>::{closure#0}
  14:     0x7f86290f3896 - std[eb796f4691fa113e]::sys_common::backtrace::__rust_end_short_backtrace::<std[eb796f4691fa113e]::panicking::begin_panic<rustc_errors[d698377914337e8]::ExplicitBug>::{closure#0}, !>
  15:     0x7f86290cbc76 - std[eb796f4691fa113e]::panicking::begin_panic::<rustc_errors[d698377914337e8]::ExplicitBug>
  16:     0x7f86290f36d6 - std[eb796f4691fa113e]::panic::panic_any::<rustc_errors[d698377914337e8]::ExplicitBug>
  17:     0x7f86290f09b6 - <rustc_errors[d698377914337e8]::HandlerInner>::bug::<&alloc[f127cc518e7b321d]::string::String>
  18:     0x7f86290f05d0 - <rustc_errors[d698377914337e8]::Handler>::bug::<&alloc[f127cc518e7b321d]::string::String>
  19:     0x7f86290dbe5e - rustc_middle[6135c93de258c3da]::ty::context::tls::with_context_opt::<rustc_middle[6135c93de258c3da]::ty::context::tls::with_opt<rustc_middle[6135c93de258c3da]::util::bug::opt_span_bug_fmt<rustc_span[9ec51286058a4e72]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7f86290dd726 - rustc_middle[6135c93de258c3da]::util::bug::opt_span_bug_fmt::<rustc_span[9ec51286058a4e72]::span_encoding::Span>
  21:     0x7f8626e89833 - rustc_middle[6135c93de258c3da]::util::bug::bug_fmt
  22:     0x7f86297d757e - rustc_middle[6135c93de258c3da]::ty::relate::super_relate_consts::<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>
  23:     0x7f8629809681 - <rustc_middle[6135c93de258c3da]::ty::consts::Const as rustc_middle[6135c93de258c3da]::ty::relate::Relate>::relate::<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>
  24:     0x7f8629834821 - <rustc_middle[6135c93de258c3da]::ty::subst::GenericArg as rustc_middle[6135c93de258c3da]::ty::relate::Relate>::relate::<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>
  25:     0x7f8629807ced - <core[4db15884ec6b3fd6]::result::Result<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg, rustc_middle[6135c93de258c3da]::ty::error::TypeError> as rustc_type_ir[1f83dc55238a9f9b]::InternIteratorElement<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg, &rustc_middle[6135c93de258c3da]::ty::list::List<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg>>>::intern_with::<core[4db15884ec6b3fd6]::iter::adapters::map::Map<core[4db15884ec6b3fd6]::iter::adapters::zip::Zip<core[4db15884ec6b3fd6]::iter::adapters::copied::Copied<core[4db15884ec6b3fd6]::slice::iter::Iter<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg>>, core[4db15884ec6b3fd6]::iter::adapters::copied::Copied<core[4db15884ec6b3fd6]::slice::iter::Iter<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg>>>, rustc_middle[6135c93de258c3da]::ty::relate::relate_substs<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>::{closure#0}>, <rustc_middle[6135c93de258c3da]::ty::context::TyCtxt>::mk_substs<core[4db15884ec6b3fd6]::iter::adapters::map::Map<core[4db15884ec6b3fd6]::iter::adapters::zip::Zip<core[4db15884ec6b3fd6]::iter::adapters::copied::Copied<core[4db15884ec6b3fd6]::slice::iter::Iter<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg>>, core[4db15884ec6b3fd6]::iter::adapters::copied::Copied<core[4db15884ec6b3fd6]::slice::iter::Iter<rustc_middle[6135c93de258c3da]::ty::subst::GenericArg>>>, rustc_middle[6135c93de258c3da]::ty::relate::relate_substs<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>::{closure#0}>>::{closure#0}>
  26:     0x7f86297e01cb - <rustc_middle[6135c93de258c3da]::ty::sty::TraitRef as rustc_middle[6135c93de258c3da]::ty::relate::Relate>::relate::<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>
  27:     0x7f86298b8ba7 - <rustc_middle[6135c93de258c3da]::ty::TraitPredicate as rustc_middle[6135c93de258c3da]::ty::relate::Relate>::relate::<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>
  28:     0x7f862981467a - <rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches as rustc_middle[6135c93de258c3da]::ty::relate::TypeRelation>::binders::<rustc_middle[6135c93de258c3da]::ty::TraitPredicate>
  29:     0x7f86297e6041 - <rustc_middle[6135c93de258c3da]::ty::sty::Binder<rustc_middle[6135c93de258c3da]::ty::TraitPredicate> as rustc_middle[6135c93de258c3da]::ty::relate::Relate>::relate::<rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::method_chain::CollectAllMismatches>
  30:     0x7f86298d444e - <rustc_infer[b21ec942315238b2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::suggestions::TypeErrCtxtExt>::note_function_argument_obligation
  31:     0x7f86298d06ca - <rustc_infer[b21ec942315238b2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::suggestions::TypeErrCtxtExt>::note_obligation_cause_code::<rustc_middle[6135c93de258c3da]::ty::Predicate>
  32:     0x7f86298df1f3 - <rustc_infer[b21ec942315238b2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::InferCtxtPrivExt>::note_obligation_cause
  33:     0x7f86298d7c1b - <rustc_infer[b21ec942315238b2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  34:     0x7f86298e2187 - <rustc_infer[b21ec942315238b2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  35:     0x7f86298d6354 - <rustc_infer[b21ec942315238b2]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[ddb8229eca56205a]::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors
  36:     0x7f8626e3541d - <rustc_hir_typeck[22bbd4c1d8fe66b7]::fn_ctxt::FnCtxt>::check_argument_types
  37:     0x7f8626f37e6b - <rustc_hir_typeck[22bbd4c1d8fe66b7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  38:     0x7f8626f87e49 - <rustc_hir_typeck[22bbd4c1d8fe66b7]::fn_ctxt::FnCtxt>::check_block_with_expected
  39:     0x7f8626f36229 - <rustc_hir_typeck[22bbd4c1d8fe66b7]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  40:     0x7f8626dfb6c3 - <rustc_hir_typeck[22bbd4c1d8fe66b7]::fn_ctxt::FnCtxt>::check_return_expr
  41:     0x7f8626df389c - rustc_hir_typeck[22bbd4c1d8fe66b7]::check::check_fn
  42:     0x7f8626ddc7f9 - <rustc_hir_typeck[22bbd4c1d8fe66b7]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[22bbd4c1d8fe66b7]::typeck_with_fallback<rustc_hir_typeck[22bbd4c1d8fe66b7]::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[6135c93de258c3da]::ty::typeck_results::TypeckResults>
  43:     0x7f8626dbd988 - rustc_hir_typeck[22bbd4c1d8fe66b7]::typeck
  44:     0x7f8626dd78a4 - <rustc_query_system[f2a92cc454341fcf]::dep_graph::graph::DepGraph<rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6135c93de258c3da]::ty::context::TyCtxt, rustc_span[9ec51286058a4e72]::def_id::LocalDefId, &rustc_middle[6135c93de258c3da]::ty::typeck_results::TypeckResults>
  45:     0x7f8626dbc232 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::try_execute_query::<rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_query_system[f2a92cc454341fcf]::query::caches::VecCache<rustc_span[9ec51286058a4e72]::def_id::LocalDefId, &rustc_middle[6135c93de258c3da]::ty::typeck_results::TypeckResults>>
  46:     0x7f86283cf775 - rustc_data_structures[41d81d1908663610]::sync::par_for_each_in::<&[rustc_span[9ec51286058a4e72]::def_id::LocalDefId], <rustc_middle[6135c93de258c3da]::hir::map::Map>::par_body_owners<rustc_hir_typeck[22bbd4c1d8fe66b7]::typeck_item_bodies::{closure#0}>::{closure#0}>
  47:     0x7f86283cf4b3 - rustc_hir_typeck[22bbd4c1d8fe66b7]::typeck_item_bodies
  48:     0x7f86282c9a67 - <rustc_query_system[f2a92cc454341fcf]::dep_graph::graph::DepGraph<rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6135c93de258c3da]::ty::context::TyCtxt, (), ()>
  49:     0x7f86282c88b0 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::try_execute_query::<rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_query_system[f2a92cc454341fcf]::query::caches::DefaultCache<(), ()>>
  50:     0x7f86282c8230 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::get_query::<rustc_query_impl[892151da123d024f]::queries::typeck_item_bodies, rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>
  51:     0x7f86270d9ae2 - <rustc_session[20c634f2fa5fd3a]::session::Session>::time::<(), rustc_hir_analysis[22e122b190ed8a83]::check_crate::{closure#7}>
  52:     0x7f86270d89dc - rustc_hir_analysis[22e122b190ed8a83]::check_crate
  53:     0x7f86270d85fb - rustc_interface[921e14e9b1939ae4]::passes::analysis
  54:     0x7f8628420f45 - <rustc_query_system[f2a92cc454341fcf]::dep_graph::graph::DepGraph<rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6135c93de258c3da]::ty::context::TyCtxt, (), core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>
  55:     0x7f8628420128 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::try_execute_query::<rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_query_system[f2a92cc454341fcf]::query::caches::DefaultCache<(), core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>>
  56:     0x7f862841fb90 - rustc_query_system[f2a92cc454341fcf]::query::plumbing::get_query::<rustc_query_impl[892151da123d024f]::queries::analysis, rustc_query_impl[892151da123d024f]::plumbing::QueryCtxt, rustc_middle[6135c93de258c3da]::dep_graph::dep_node::DepKind>
  57:     0x7f8627e8e623 - <rustc_interface[921e14e9b1939ae4]::passes::QueryContext>::enter::<rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>
  58:     0x7f8627e89714 - rustc_span[9ec51286058a4e72]::with_source_map::<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  59:     0x7f8627e81a45 - <scoped_tls[c0301d1e58d7cd39]::ScopedKey<rustc_span[9ec51286058a4e72]::SessionGlobals>>::set::<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>
  60:     0x7f8627e81032 - std[eb796f4691fa113e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[921e14e9b1939ae4]::util::run_in_thread_pool_with_globals<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>
  61:     0x7f8627e80dda - <<std[eb796f4691fa113e]::thread::Builder>::spawn_unchecked_<rustc_interface[921e14e9b1939ae4]::util::run_in_thread_pool_with_globals<rustc_interface[921e14e9b1939ae4]::interface::run_compiler<core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>, rustc_driver[7a1e5a3798cd51b2]::run_compiler::{closure#1}>::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4db15884ec6b3fd6]::result::Result<(), rustc_errors[d698377914337e8]::ErrorGuaranteed>>::{closure#1} as core[4db15884ec6b3fd6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  62:     0x7f8625972b43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h547009b1980571ef
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:1988:9
  63:     0x7f8625972b43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h47c8551d74ce8d22
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/alloc/src/boxed.rs:1988:9
  64:     0x7f8625972b43 - std::sys::unix::thread::Thread::new::thread_start::he79de38213da15ab
                               at /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/library/std/src/sys/unix/thread.rs:108:17
  65:     0x7f8625703bb5 - <unknown>
  66:     0x7f8625785d90 - <unknown>
  67:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (574b64a97 2022-12-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `bar`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/compiler/rustc_middle/src/ty/relate.rs:638:13: var types encountered in super_relate_consts: Const { ty: usize, kind: Infer(Var(_#0c)) } Const { ty: usize, kind: Value(Leaf(0x0000000000000000)) }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/574b64a97f52162f965bc201e47f0af8279ca65d/compiler/rustc_errors/src/lib.rs:1581:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_middle::ty::relate::super_relate_consts::<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>
   8: <rustc_middle::ty::consts::Const as rustc_middle::ty::relate::Relate>::relate::<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>
   9: <rustc_middle::ty::subst::GenericArg as rustc_middle::ty::relate::Relate>::relate::<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>
  10: <core::result::Result<rustc_middle::ty::subst::GenericArg, rustc_middle::ty::error::TypeError> as rustc_type_ir::InternIteratorElement<rustc_middle::ty::subst::GenericArg, &rustc_middle::ty::list::List<rustc_middle::ty::subst::GenericArg>>>::intern_with::<core::iter::adapters::map::Map<core::iter::adapters::zip::Zip<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::subst::GenericArg>>, core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::subst::GenericArg>>>, rustc_middle::ty::relate::relate_substs<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>::{closure#0}>, <rustc_middle::ty::context::TyCtxt>::mk_substs<core::iter::adapters::map::Map<core::iter::adapters::zip::Zip<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::subst::GenericArg>>, core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::subst::GenericArg>>>, rustc_middle::ty::relate::relate_substs<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>::{closure#0}>>::{closure#0}>
  11: <rustc_middle::ty::sty::TraitRef as rustc_middle::ty::relate::Relate>::relate::<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>
  12: <rustc_middle::ty::TraitPredicate as rustc_middle::ty::relate::Relate>::relate::<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>
  13: <rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches as rustc_middle::ty::relate::TypeRelation>::binders::<rustc_middle::ty::TraitPredicate>
  14: <rustc_middle::ty::sty::Binder<rustc_middle::ty::TraitPredicate> as rustc_middle::ty::relate::Relate>::relate::<rustc_trait_selection::traits::error_reporting::method_chain::CollectAllMismatches>
  15: <rustc_infer::infer::error_reporting::TypeErrCtxt as rustc_trait_selection::traits::error_reporting::suggestions::TypeErrCtxtExt>::note_function_argument_obligation
  16: <rustc_infer::infer::error_reporting::TypeErrCtxt as rustc_trait_selection::traits::error_reporting::suggestions::TypeErrCtxtExt>::note_obligation_cause_code::<rustc_middle::ty::Predicate>
  17: <rustc_infer::infer::error_reporting::TypeErrCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::note_obligation_cause
  18: <rustc_infer::infer::error_reporting::TypeErrCtxt as rustc_trait_selection::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  19: <rustc_infer::infer::error_reporting::TypeErrCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  20: <rustc_infer::infer::error_reporting::TypeErrCtxt as rustc_trait_selection::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors
  21: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_argument_types
  22: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_block_with_expected
  24: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  25: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_expr
  26: rustc_hir_typeck::check::check_fn
  27: <rustc_hir_typeck::inherited::InheritedBuilder>::enter::<rustc_hir_typeck::typeck_with_fallback<rustc_hir_typeck::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle::ty::typeck_results::TypeckResults>
  28: rustc_hir_typeck::typeck
  29: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::typeck_results::TypeckResults>
  30: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::typeck_results::TypeckResults>>
  31: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_typeck::typeck_item_bodies::{closure#0}>::{closure#0}>
  32: rustc_hir_typeck::typeck_item_bodies
  33: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  34: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  35: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  36: <rustc_session::session::Session>::time::<(), rustc_hir_analysis::check_crate::{closure#7}>
  37: rustc_hir_analysis::check_crate
  38: rustc_interface::passes::analysis
  39: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  40: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  41: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
  42: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#2}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  43: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  44: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (574b64a97 2022-12-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `bar`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by compiler-errors** [comment]
This is fixed on master. Please update your nightly compiler with `rustup update nightly`.
