### ISSUE TITLE
`cargo doc` panic (No resolutions for a doc link)

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust#109614]
### Code

**N/A**

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (1459b3128 2023-03-23)
binary: rustc
commit-hash: 1459b3128e288a85fcc4dd1fee7ada2cdcf28794
commit-date: 2023-03-23
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Error output

```
[...]
 Documenting clap_lex v0.3.3
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2251:18
stack backtrace:
   0:     0x7f1e0116580a - std::backtrace_rs::backtrace::libunwind::trace::h3973f51617998fc6
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1e0116580a - std::backtrace_rs::backtrace::trace_unsynchronized::hc880f45678a36b06
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1e0116580a - std::sys_common::backtrace::_print_fmt::h0c5a990bb8ef31fa
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1e0116580a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h55a8e98b4c6161da
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1e011c947e - core::fmt::write::h4c40d77c4903afa0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f1e01158485 - std::io::Write::write_fmt::ha3b362d3dcfb999f
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/io/mod.rs:1698:15
   6:     0x7f1e011655d5 - std::sys_common::backtrace::_print::h8269abb9d4b9ac2e
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f1e011655d5 - std::sys_common::backtrace::print::h475ddad52d027480
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f1e0116834f - std::panicking::default_hook::{{closure}}::hdb1a9b91764be170
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:271:22
   9:     0x7f1e0116808b - std::panicking::default_hook::hb3624b5fb0dd82aa
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:290:9
  10:     0x7f1e0448f225 - rustc_driver_impl[159109056ec6dbcd]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f1e01168b8d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hce90bfe2d8d3bfad
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:2002:9
  12:     0x7f1e01168b8d - std::panicking::rust_panic_with_hook::h34c77a71befec972
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:696:13
  13:     0x7f1e01168909 - std::panicking::begin_panic_handler::{{closure}}::hb5ae8193b4163d8b
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:583:13
  14:     0x7f1e01165c76 - std::sys_common::backtrace::__rust_end_short_backtrace::h53bbfcb82ab0fc3b
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f1e01168612 - rust_begin_unwind
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:579:5
  16:     0x7f1e011c57f3 - core::panicking::panic_fmt::h712e519910af2aa1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:64:14
  17:     0x7f1e011c5573 - core::panicking::panic_display::h73327eaae8c72270
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:147:5
  18:     0x7f1e011c5573 - core::panicking::panic_str::h5efcc14bd7078c99
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:131:5
  19:     0x7f1e011c5573 - core::option::expect_failed::h378c2f45805bd9f3
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/option.rs:2055:5
  20:     0x7f1e0491bc3c - <rustc_metadata[3a094ff839502453]::rmeta::encoder::provide::{closure#0} as core[9d00a47b0220fcc3]::ops::function::FnOnce<(rustc_middle[8aa151a798159f2c]::ty::context::TyCtxt, rustc_span[13ea7f588b3c13d6]::def_id::LocalDefId)>>::call_once
  21:     0x7f1e04d15298 - rustc_query_system[fd8aa6351e8df40e]::query::plumbing::try_execute_query::<rustc_query_impl[eee500123a0977cb]::queries::doc_link_resolutions, rustc_query_impl[eee500123a0977cb]::plumbing::QueryCtxt>
  22:     0x7f1e04da56a7 - <rustc_query_impl[eee500123a0977cb]::Queries as rustc_middle[8aa151a798159f2c]::ty::query::QueryEngine>::doc_link_resolutions
  23:     0x558c6fa9af3f - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  24:     0x558c6fa9b108 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector>::resolve
  25:     0x558c6fa9ec64 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector>::resolve_links
  26:     0x558c6faaa150 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector as rustdoc[853469566b21e95f]::visit::DocVisitor>::visit_inner_recur
  27:     0x558c6faaa138 - <rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::LinkCollector as rustdoc[853469566b21e95f]::visit::DocVisitor>::visit_inner_recur
  28:     0x558c6fa99ab9 - rustdoc[853469566b21e95f]::passes::collect_intra_doc_links::collect_intra_doc_links
  29:     0x558c6faac2a1 - <rustc_session[e3b3f8e1183b0336]::session::Session>::time::<rustdoc[853469566b21e95f]::clean::types::Crate, rustdoc[853469566b21e95f]::core::run_global_ctxt::{closure#7}>
  30:     0x558c6fb5bfeb - rustdoc[853469566b21e95f]::core::run_global_ctxt
  31:     0x558c6faac529 - <rustc_session[e3b3f8e1183b0336]::session::Session>::time::<(rustdoc[853469566b21e95f]::clean::types::Crate, rustdoc[853469566b21e95f]::config::RenderOptions, rustdoc[853469566b21e95f]::formats::cache::Cache), rustdoc[853469566b21e95f]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  32:     0x558c6f94c5b7 - <rustc_middle[8aa151a798159f2c]::ty::context::GlobalCtxt>::enter::<rustdoc[853469566b21e95f]::main_args::{closure#1}::{closure#0}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  33:     0x558c6f94b580 - <rustc_interface[3eea5f8e37acaac7]::interface::Compiler>::enter::<rustdoc[853469566b21e95f]::main_args::{closure#1}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  34:     0x558c6fad79cb - rustc_span[13ea7f588b3c13d6]::with_source_map::<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  35:     0x558c6f94e9d4 - <scoped_tls[fb9b4801708e8a70]::ScopedKey<rustc_span[13ea7f588b3c13d6]::SessionGlobals>>::set::<rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  36:     0x558c6fae6a60 - std[2b8d1b569764f7c5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3eea5f8e37acaac7]::util::run_in_thread_pool_with_globals<rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>
  37:     0x558c6fb889cd - <<std[2b8d1b569764f7c5]::thread::Builder>::spawn_unchecked_<rustc_interface[3eea5f8e37acaac7]::util::run_in_thread_pool_with_globals<rustc_interface[3eea5f8e37acaac7]::interface::run_compiler<core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>, rustdoc[853469566b21e95f]::main_args::{closure#1}>::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9d00a47b0220fcc3]::result::Result<(), rustc_span[13ea7f588b3c13d6]::ErrorGuaranteed>>::{closure#1} as core[9d00a47b0220fcc3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f1e01172c03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5465857e83d6d8ca
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:1988:9
  39:     0x7f1e01172c03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha9ee3b71411efa49
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:1988:9
  40:     0x7f1e01172c03 - std::sys::unix::thread::Thread::new::thread_start::hade30c6a6cbcfe88
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f1e00e94b43 - <unknown>
  42:     0x7f1e00f26a00 - <unknown>
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (1459b3128 2023-03-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /home/alejandra/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.36.11/src/lib.rs --cap-lints allow -o /home/alejandra/git/wawat/cuteness/target/doc --cfg 'feature="default"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=213 -C metadata=c8bad158e10ac0de -L dependency=/home/alejandra/git/wawat/cuteness/target/debug/deps --extern bitflags=/home/alejandra/git/wawat/cuteness/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern io_lifetimes=/home/alejandra/git/wawat/cuteness/target/debug/deps/libio_lifetimes-0e896a4daa128e32.rmeta --extern libc=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblibc-8aab922602f2fc15.rmeta --extern linux_raw_sys=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblinux_raw_sys-a31463b73c270e13.rmeta --crate-version 0.36.11 --cfg rustc_attrs --cfg linux_raw --cfg core_intrinsics --cfg asm` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

---

Weirdly, the output is longer than the backtrace.

---

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 ~/git/wawat/cuteness  main !1 ▓▒░ RUST_BACKTRACE=1 cargo doc --open                                                                                                                                          ░▒▓ ✔
   Compiling serde_derive v1.0.158
   Compiling thiserror-impl v1.0.40
   Compiling clap_derive v4.1.12
 Documenting rustix v0.36.11
 Documenting log v0.4.17
 Documenting unicase v2.6.0
 Documenting constant_time_eq v0.2.5
 Documenting strsim v0.10.0
    Checking litrs v0.2.3
 Documenting arrayref v0.3.7
 Documenting termcolor v1.2.0
 Documenting litrs v0.2.3
 Documenting arrayvec v0.7.2
 Documenting regex-syntax v0.6.29
 Documenting emojis v0.5.2
 Documenting pulldown-cmark v0.9.2
    Checking regex v1.7.3
    Checking blake3 v1.3.3
   Compiling document-features v0.2.7
 Documenting blake3 v1.3.3
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2251:18
stack backtrace:
    Checking pulldown-cmark v0.9.2
   0: rust_begin_unwind
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/option.rs:2055:5
   5: <rustc_metadata::rmeta::encoder::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
   6: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::doc_link_resolutions, rustc_query_impl::plumbing::QueryCtxt>
   7: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::doc_link_resolutions
   8: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_path
   9: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
  10: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_links
  11: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  13: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  14: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#7}>
  15: rustdoc::core::run_global_ctxt
  16: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  17: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  18: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_args::{closure#1}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  19: rustc_span::with_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}::{closure#0}>
  20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (1459b3128 2023-03-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
 Documenting document-features v0.2.7
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /home/alejandra/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.36.11/src/lib.rs --cap-lints allow -o /home/alejandra/git/wawat/cuteness/target/doc --cfg 'feature="default"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=213 -C metadata=c8bad158e10ac0de -L dependency=/home/alejandra/git/wawat/cuteness/target/debug/deps --extern bitflags=/home/alejandra/git/wawat/cuteness/target/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern io_lifetimes=/home/alejandra/git/wawat/cuteness/target/debug/deps/libio_lifetimes-0e896a4daa128e32.rmeta --extern libc=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblibc-8aab922602f2fc15.rmeta --extern linux_raw_sys=/home/alejandra/git/wawat/cuteness/target/debug/deps/liblinux_raw_sys-a31463b73c270e13.rmeta --crate-version 0.36.11 --cfg rustc_attrs --cfg linux_raw --cfg core_intrinsics --cfg asm` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

</p>
</details>

**Comment by lukas-code** [comment]
## Repro
Put this in Cargo.toml and run `cargo doc`. Latest version of rustix doesn't reproduce.
```toml
[package]
name = "issue-109614"
version = "0.1.0"
edition = "2021"

[dependencies]
rustix = "0.36.11"
```

## Bisect

searched nightlies: from nightly-2023-03-19 to nightly-2023-03-25
regressed nightly: nightly-2023-03-21
searched commit range: https://github.com/rust-lang/rust/compare/da7c50c089d5db2d3ebaf227fe075bb1346bfaec...44f5180584404d18058cbbf224c55255db4fdcbb
regressed commit: https://github.com/rust-lang/rust/commit/febd59e122f67d26d410a62f661a941a706b28ec

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc -- doc 
```
</details>

Regression in https://github.com/rust-lang/rust/pull/109266 cc @petrochenkov

**Comment by blyxyas** [comment]
`rustix` is imported as a dependency by `is-terminal` (v0.4.5), imported by `clap` (v4.1.13)
Weirdly enough, that rustix is v0.36.11 but the latest version (v0.37.3) also causes the issue.

Should I open an issue about this in rustix?

**Comment by lukas-code** [comment]
> Should I open an issue about this in rustix?

No, this is a bug in rustc/rustdoc, not in rustix.

**Comment by lukas-code** [comment]
## MCVE
```rust
mod read_write {
    pub fn preadv2() {}

    /// [`preadv2`]
    pub use crate::backend::ReadWriteFlags;
}
mod backend {
    pub struct ReadWriteFlags;
}
pub use read_write::{preadv2, ReadWriteFlags};
```

@rustbot label +C-bug-has-mcve +A-intra-doc-links +T-rustdoc -T-compiler

**Comment by petrochenkov** [comment]
Not fixed by https://github.com/rust-lang/rust/pull/109330, but fixed by https://github.com/rust-lang/rust/pull/109500.
