### ISSUE TITLE
Compiler crashes on implementing custom filter on iterator

### ISSUE THREAD

**Issue by martinsk** [rust-lang/rust#110246]
### Code

```Rust

impl Table { 

    fn select<P>(
        &self,
        vars: Vec<&'static str>,
        predicate: P,
    ) -> core::iter::Filter<TableIterator, P>
    where
        P: Fn(&TableIterator::Item) -> bool,
    {
        self.iter().filter(predicate)
    }

}

```

### Meta
`rustc --version --verbose`:
```
❯ rustc --version --verbose
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: aarch64-apple-darwin
release: 1.68.2
LLVM version: 15.0.6
```

### Error output

```
cargo build 
   Compiling test_app v0.1.0 (~/test_app)
error: internal compiler error: compiler/rustc_infer/src/infer/region_constraints/mod.rs:568:17: cannot relate bound region: ReErased <= ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrNamed(DefId(0:65 ~ test_app[73e0]::{impl#3}::select::'_#1), '_) })

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/compiler/rustc_errors/src/lib.rs:987:33
stack backtrace:
   0:        0x104d3a978 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
   1:        0x104d8acf0 - core::fmt::write::hc60df9bae744c40c
   2:        0x104d2e374 - std::io::Write::write_fmt::h1c4129dfc94f7c33
   3:        0x104d3a78c - std::sys_common::backtrace::print::h34db077f1fa49c76
   4:        0x104d3d2e0 - std::panicking::default_hook::{{closure}}::hff4fe3239c020cef
   5:        0x104d3d038 - std::panicking::default_hook::hd2988fbcc86fdc46
   6:        0x10d021400 - rustc_driver[b67fef72c303079b]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x104d3d9d8 - std::panicking::rust_panic_with_hook::h01730ad11d62092c
   8:        0x110ca16dc - std[8dc9805012fd1cea]::panicking::begin_panic::<rustc_errors[fe326c1ebc0a7364]::ExplicitBug>::{closure#0}
   9:        0x110c9b788 - std[8dc9805012fd1cea]::sys_common::backtrace::__rust_end_short_backtrace::<std[8dc9805012fd1cea]::panicking::begin_panic<rustc_errors[fe326c1ebc0a7364]::ExplicitBug>::{closure#0}, !>
  10:        0x111349d98 - std[8dc9805012fd1cea]::panicking::begin_panic::<rustc_errors[fe326c1ebc0a7364]::ExplicitBug>
  11:        0x110d47ea8 - std[8dc9805012fd1cea]::panic::panic_any::<rustc_errors[fe326c1ebc0a7364]::ExplicitBug>
  12:        0x110d453e4 - <rustc_errors[fe326c1ebc0a7364]::HandlerInner>::span_bug::<rustc_span[cd726bea196c4eb]::span_encoding::Span, &alloc[97d6479c9973beab]::string::String>
  13:        0x110d4522c - <rustc_errors[fe326c1ebc0a7364]::Handler>::span_bug::<rustc_span[cd726bea196c4eb]::span_encoding::Span, &alloc[97d6479c9973beab]::string::String>
  14:        0x110ce16e0 - rustc_middle[9a7f1a42d06ddbac]::util::bug::opt_span_bug_fmt::<rustc_span[cd726bea196c4eb]::span_encoding::Span>::{closure#0}
  15:        0x110ce19d8 - rustc_middle[9a7f1a42d06ddbac]::ty::context::tls::with_opt::<rustc_middle[9a7f1a42d06ddbac]::util::bug::opt_span_bug_fmt<rustc_span[cd726bea196c4eb]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  16:        0x110ce0f40 - rustc_middle[9a7f1a42d06ddbac]::ty::context::tls::with_context_opt::<rustc_middle[9a7f1a42d06ddbac]::ty::context::tls::with_opt<rustc_middle[9a7f1a42d06ddbac]::util::bug::opt_span_bug_fmt<rustc_span[cd726bea196c4eb]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  17:        0x110ce0efc - rustc_middle[9a7f1a42d06ddbac]::util::bug::opt_span_bug_fmt::<rustc_span[cd726bea196c4eb]::span_encoding::Span>
  18:        0x111345b20 - rustc_middle[9a7f1a42d06ddbac]::util::bug::span_bug_fmt::<rustc_span[cd726bea196c4eb]::span_encoding::Span>
  19:        0x110cdc24c - <rustc_infer[fd41469e2d6b21d1]::infer::region_constraints::RegionConstraintCollector>::make_subregion
  20:        0x110cd6730 - <rustc_infer[fd41469e2d6b21d1]::infer::region_constraints::RegionConstraintCollector>::make_eqregion
  21:        0x110ce6688 - <rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate as rustc_middle[9a7f1a42d06ddbac]::ty::relate::TypeRelation>::regions
  22:        0x110cfb9f4 - <rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg as rustc_middle[9a7f1a42d06ddbac]::ty::relate::Relate>::relate::<rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate>
  23:        0x110ccae08 - <core[cead920de05078ba]::result::Result<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg, rustc_middle[9a7f1a42d06ddbac]::ty::error::TypeError> as rustc_type_ir[72af779b5d6fb6af]::InternIteratorElement<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg, &rustc_middle[9a7f1a42d06ddbac]::ty::list::List<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg>>>::intern_with::<core[cead920de05078ba]::iter::adapters::map::Map<core[cead920de05078ba]::iter::adapters::zip::Zip<core[cead920de05078ba]::iter::adapters::copied::Copied<core[cead920de05078ba]::slice::iter::Iter<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg>>, core[cead920de05078ba]::iter::adapters::copied::Copied<core[cead920de05078ba]::slice::iter::Iter<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg>>>, rustc_middle[9a7f1a42d06ddbac]::ty::relate::relate_substs<rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate>::{closure#0}>, <rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt>::mk_substs<core[cead920de05078ba]::iter::adapters::map::Map<core[cead920de05078ba]::iter::adapters::zip::Zip<core[cead920de05078ba]::iter::adapters::copied::Copied<core[cead920de05078ba]::slice::iter::Iter<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg>>, core[cead920de05078ba]::iter::adapters::copied::Copied<core[cead920de05078ba]::slice::iter::Iter<rustc_middle[9a7f1a42d06ddbac]::ty::subst::GenericArg>>>, rustc_middle[9a7f1a42d06ddbac]::ty::relate::relate_substs<rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate>::{closure#0}>>::{closure#0}>
  24:        0x110ce654c - <rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate as rustc_middle[9a7f1a42d06ddbac]::ty::relate::TypeRelation>::relate_item_substs
  25:        0x110cecfc4 - rustc_middle[9a7f1a42d06ddbac]::ty::relate::super_relate_tys::<rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate>
  26:        0x110ce98b0 - <rustc_infer[fd41469e2d6b21d1]::infer::equate::Equate as rustc_middle[9a7f1a42d06ddbac]::ty::relate::TypeRelation>::tys
  27:        0x10f4e6f20 - <rustc_infer[fd41469e2d6b21d1]::infer::InferCtxt>::commit_if_ok::<rustc_infer[fd41469e2d6b21d1]::infer::InferOk<()>, rustc_middle[9a7f1a42d06ddbac]::ty::error::TypeError, <rustc_infer[fd41469e2d6b21d1]::infer::at::Trace>::eq<rustc_middle[9a7f1a42d06ddbac]::ty::Ty>::{closure#0}>
  28:        0x10f4e7d4c - <rustc_infer[fd41469e2d6b21d1]::infer::InferCtxt>::can_eq::<rustc_middle[9a7f1a42d06ddbac]::ty::Ty>
  29:        0x10f5bd488 - <&mut core[cead920de05078ba]::iter::adapters::cloned::clone_try_fold<rustc_span[cd726bea196c4eb]::def_id::DefId, (), core[cead920de05078ba]::ops::control_flow::ControlFlow<()>, core[cead920de05078ba]::iter::traits::iterator::Iterator::any::check<rustc_span[cd726bea196c4eb]::def_id::DefId, <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::associated_path_to_ty::{closure#0}::{closure#6}::{closure#1}>::{closure#0}>::{closure#0} as core[cead920de05078ba]::ops::function::FnMut<((), &rustc_span[cd726bea196c4eb]::def_id::DefId)>>::call_mut
  30:        0x10f580c10 - <core[cead920de05078ba]::iter::adapters::chain::Chain<core[cead920de05078ba]::slice::iter::Iter<rustc_span[cd726bea196c4eb]::def_id::DefId>, core[cead920de05078ba]::iter::adapters::flatten::FlatMap<indexmap[b4d4821567144853]::map::Iter<rustc_middle[9a7f1a42d06ddbac]::ty::fast_reject::SimplifiedType, alloc[97d6479c9973beab]::vec::Vec<rustc_span[cd726bea196c4eb]::def_id::DefId>>, &alloc[97d6479c9973beab]::vec::Vec<rustc_span[cd726bea196c4eb]::def_id::DefId>, <rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt>::all_impls::{closure#0}>> as core[cead920de05078ba]::iter::traits::iterator::Iterator>::try_fold::<(), core[cead920de05078ba]::iter::adapters::cloned::clone_try_fold<rustc_span[cd726bea196c4eb]::def_id::DefId, (), core[cead920de05078ba]::ops::control_flow::ControlFlow<()>, core[cead920de05078ba]::iter::traits::iterator::Iterator::any::check<rustc_span[cd726bea196c4eb]::def_id::DefId, <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::associated_path_to_ty::{closure#0}::{closure#6}::{closure#1}>::{closure#0}>::{closure#0}, core[cead920de05078ba]::ops::control_flow::ControlFlow<()>>
  31:        0x10f4b031c - <&mut <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::associated_path_to_ty::{closure#0}::{closure#6} as core[cead920de05078ba]::ops::function::FnMut<(&rustc_span[cd726bea196c4eb]::def_id::DefId,)>>::call_mut
  32:        0x10f554cfc - <alloc[97d6479c9973beab]::vec::Vec<alloc[97d6479c9973beab]::string::String> as alloc[97d6479c9973beab]::vec::spec_from_iter::SpecFromIter<alloc[97d6479c9973beab]::string::String, core[cead920de05078ba]::iter::adapters::map::Map<core[cead920de05078ba]::iter::adapters::filter::Filter<core[cead920de05078ba]::iter::adapters::flatten::FlatMap<core[cead920de05078ba]::iter::adapters::chain::Chain<core[cead920de05078ba]::iter::sources::once::Once<rustc_span[cd726bea196c4eb]::def_id::CrateNum>, core[cead920de05078ba]::iter::adapters::copied::Copied<core[cead920de05078ba]::slice::iter::Iter<rustc_span[cd726bea196c4eb]::def_id::CrateNum>>>, core[cead920de05078ba]::iter::adapters::copied::Copied<core[cead920de05078ba]::slice::iter::Iter<rustc_span[cd726bea196c4eb]::def_id::DefId>>, <rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt>::all_traits::{closure#0}>, <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::associated_path_to_ty::{closure#0}::{closure#6}>, <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::associated_path_to_ty::{closure#0}::{closure#7}>>>::from_iter
  33:        0x10f4c7adc - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::associated_path_to_ty::{closure#0}
  34:        0x10f4cc1ac - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}
  35:        0x10f4cc074 - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}
  36:        0x10f476e2c - <rustc_middle[9a7f1a42d06ddbac]::ty::Ty as rustc_type_ir[72af779b5d6fb6af]::InternIteratorElement<rustc_middle[9a7f1a42d06ddbac]::ty::Ty, rustc_middle[9a7f1a42d06ddbac]::ty::Ty>>::intern_with::<core[cead920de05078ba]::iter::adapters::map::Map<core[cead920de05078ba]::slice::iter::Iter<rustc_hir[7616077c04b065fb]::hir::Ty>, <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}::{closure#0}>, <rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt>::mk_tup<core[cead920de05078ba]::iter::adapters::map::Map<core[cead920de05078ba]::slice::iter::Iter<rustc_hir[7616077c04b065fb]::hir::Ty>, <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}::{closure#0}>>::{closure#0}>
  37:        0x10f4cc150 - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}
  38:        0x10f4c48d8 - <<dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::create_substs_for_ast_path::{closure#0}::SubstsForAstPathCtxt as rustc_hir_analysis[8c6c434a41694f32]::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind::{closure#0}
  39:        0x10f4c4624 - <<dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::create_substs_for_ast_path::{closure#0}::SubstsForAstPathCtxt as rustc_hir_analysis[8c6c434a41694f32]::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind
  40:        0x10f505ed4 - rustc_hir_analysis[8c6c434a41694f32]::astconv::generics::create_substs_for_generic_args::<<dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::create_substs_for_ast_path::{closure#0}::SubstsForAstPathCtxt>
  41:        0x10f4c429c - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::create_substs_for_ast_path
  42:        0x10f4b29b8 - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::instantiate_poly_trait_ref_inner
  43:        0x10f4c57b8 - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::instantiate_poly_trait_ref
  44:        0x10f4c5e40 - <dyn rustc_hir_analysis[8c6c434a41694f32]::astconv::AstConv>::add_bounds::<core[cead920de05078ba]::slice::iter::Iter<rustc_hir[7616077c04b065fb]::hir::GenericBound>>
  45:        0x10f54399c - rustc_hir_analysis[8c6c434a41694f32]::collect::predicates_of::gather_explicit_predicates_of
  46:        0x1102a4108 - <rustc_query_system[a99348637a748513]::dep_graph::graph::DepGraph<rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt, rustc_span[cd726bea196c4eb]::def_id::DefId, rustc_middle[9a7f1a42d06ddbac]::ty::generics::GenericPredicates>
  47:        0x11009d830 - rustc_query_system[a99348637a748513]::query::plumbing::try_execute_query::<rustc_query_impl[e6483fe3d2d29454]::queries::explicit_predicates_of, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt>
  48:        0x11012aec4 - rustc_query_system[a99348637a748513]::query::plumbing::get_query::<rustc_query_impl[e6483fe3d2d29454]::queries::explicit_predicates_of, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt, rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>
  49:        0x1101dc7ac - <rustc_query_impl[e6483fe3d2d29454]::Queries as rustc_middle[9a7f1a42d06ddbac]::ty::query::QueryEngine>::explicit_predicates_of
  50:        0x10f499678 - rustc_hir_analysis[8c6c434a41694f32]::collect::predicates_defined_on
  51:        0x1102a4108 - <rustc_query_system[a99348637a748513]::dep_graph::graph::DepGraph<rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt, rustc_span[cd726bea196c4eb]::def_id::DefId, rustc_middle[9a7f1a42d06ddbac]::ty::generics::GenericPredicates>
  52:        0x1100950a8 - rustc_query_system[a99348637a748513]::query::plumbing::try_execute_query::<rustc_query_impl[e6483fe3d2d29454]::queries::predicates_defined_on, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt>
  53:        0x11012a9cc - rustc_query_system[a99348637a748513]::query::plumbing::get_query::<rustc_query_impl[e6483fe3d2d29454]::queries::predicates_defined_on, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt, rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>
  54:        0x1101dc71c - <rustc_query_impl[e6483fe3d2d29454]::Queries as rustc_middle[9a7f1a42d06ddbac]::ty::query::QueryEngine>::predicates_defined_on
  55:        0x10f540dbc - rustc_hir_analysis[8c6c434a41694f32]::collect::predicates_of::predicates_of
  56:        0x1102a4108 - <rustc_query_system[a99348637a748513]::dep_graph::graph::DepGraph<rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt, rustc_span[cd726bea196c4eb]::def_id::DefId, rustc_middle[9a7f1a42d06ddbac]::ty::generics::GenericPredicates>
  57:        0x11002d410 - rustc_query_system[a99348637a748513]::query::plumbing::try_execute_query::<rustc_query_impl[e6483fe3d2d29454]::queries::predicates_of, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt>
  58:        0x1101258c8 - rustc_query_system[a99348637a748513]::query::plumbing::get_query::<rustc_query_impl[e6483fe3d2d29454]::queries::predicates_of, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt, rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>
  59:        0x1101db49c - <rustc_query_impl[e6483fe3d2d29454]::Queries as rustc_middle[9a7f1a42d06ddbac]::ty::query::QueryEngine>::predicates_of
  60:        0x10f48ff80 - <rustc_hir_analysis[8c6c434a41694f32]::collect::CollectItemTypesVisitor as rustc_hir[7616077c04b065fb]::intravisit::Visitor>::visit_impl_item
  61:        0x10f4f5b40 - <rustc_middle[9a7f1a42d06ddbac]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis[8c6c434a41694f32]::collect::CollectItemTypesVisitor>
  62:        0x10f48dd08 - rustc_hir_analysis[8c6c434a41694f32]::collect::collect_mod_item_types
  63:        0x110299dec - <rustc_query_system[a99348637a748513]::dep_graph::graph::DepGraph<rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt, rustc_span[cd726bea196c4eb]::def_id::LocalDefId, ()>
  64:        0x110099b98 - rustc_query_system[a99348637a748513]::query::plumbing::try_execute_query::<rustc_query_impl[e6483fe3d2d29454]::queries::collect_mod_item_types, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt>
  65:        0x1101ddf74 - <rustc_query_impl[e6483fe3d2d29454]::Queries as rustc_middle[9a7f1a42d06ddbac]::ty::query::QueryEngine>::collect_mod_item_types
  66:        0x10f4f6404 - <rustc_session[35ac6c007884beb3]::session::Session>::track_errors::<rustc_hir_analysis[8c6c434a41694f32]::check_crate::{closure#0}, ()>
  67:        0x10f4ac7f8 - rustc_hir_analysis[8c6c434a41694f32]::check_crate
  68:        0x10d0bf638 - rustc_interface[68ba7ba60dcf80eb]::passes::analysis
  69:        0x1102bf914 - <rustc_query_system[a99348637a748513]::dep_graph::graph::DepGraph<rustc_middle[9a7f1a42d06ddbac]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9a7f1a42d06ddbac]::ty::context::TyCtxt, (), core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>
  70:        0x1100e850c - rustc_query_system[a99348637a748513]::query::plumbing::try_execute_query::<rustc_query_impl[e6483fe3d2d29454]::queries::analysis, rustc_query_impl[e6483fe3d2d29454]::plumbing::QueryCtxt>
  71:        0x1101db324 - <rustc_query_impl[e6483fe3d2d29454]::Queries as rustc_middle[9a7f1a42d06ddbac]::ty::query::QueryEngine>::analysis
  72:        0x10cfc1608 - <rustc_interface[68ba7ba60dcf80eb]::passes::QueryContext>::enter::<rustc_driver[b67fef72c303079b]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>
  73:        0x10d012724 - <rustc_interface[68ba7ba60dcf80eb]::queries::QueryResult<rustc_interface[68ba7ba60dcf80eb]::passes::QueryContext>>::enter::<core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>, rustc_driver[b67fef72c303079b]::run_compiler::{closure#1}::{closure#2}::{closure#2}>
  74:        0x10cff9090 - <rustc_interface[68ba7ba60dcf80eb]::interface::Compiler>::enter::<rustc_driver[b67fef72c303079b]::run_compiler::{closure#1}::{closure#2}, core[cead920de05078ba]::result::Result<core[cead920de05078ba]::option::Option<rustc_interface[68ba7ba60dcf80eb]::queries::Linker>, rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>
  75:        0x10d011edc - rustc_span[cd726bea196c4eb]::with_source_map::<core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>, rustc_interface[68ba7ba60dcf80eb]::interface::run_compiler<core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>, rustc_driver[b67fef72c303079b]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  76:        0x10cfc732c - std[8dc9805012fd1cea]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[68ba7ba60dcf80eb]::util::run_in_thread_pool_with_globals<rustc_interface[68ba7ba60dcf80eb]::interface::run_compiler<core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>, rustc_driver[b67fef72c303079b]::run_compiler::{closure#1}>::{closure#0}, core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>
  77:        0x10cfa9f68 - <<std[8dc9805012fd1cea]::thread::Builder>::spawn_unchecked_<rustc_interface[68ba7ba60dcf80eb]::util::run_in_thread_pool_with_globals<rustc_interface[68ba7ba60dcf80eb]::interface::run_compiler<core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>, rustc_driver[b67fef72c303079b]::run_compiler::{closure#1}>::{closure#0}, core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[cead920de05078ba]::result::Result<(), rustc_errors[fe326c1ebc0a7364]::ErrorGuaranteed>>::{closure#1} as core[cead920de05078ba]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  78:        0x104d45e18 - std::sys::unix::thread::Thread::new::thread_start::h7c145656763309f3
  79:        0x18d7b3fa8 - __pthread_joiner_wake

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.2 (9eb3afe9e 2023-03-27) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [explicit_predicates_of] computing explicit predicates of `<impl at src/main.rs:62:1: 62:11>::select`
#1 [predicates_defined_on] computing predicates of `<impl at src/main.rs:62:1: 62:11>::select`
#2 [predicates_of] computing predicates of `<impl at src/main.rs:62:1: 62:11>::select`
#3 [collect_mod_item_types] collecting item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `test_app`


```

```
<backtrace>
```

</p>
</details>

**Comment by martinsk** [comment]
Nightly seems to have better error messages. And identified a type error.
