### ISSUE TITLE
rustc compiler panic when natively compiling on RPi8GB

### ISSUE THREAD

**Issue by hmuint32** [rust-lang/rust#110326]
```
binary: rustc
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: aarch64-unknown-linux-gnu
release: 1.68.2
LLVM version: 15.0.6
```

### Error output

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.66.1 (90743e729 2023-01-10) running on aarch64-unknown-linux-gnu

note: compiler flags: --crate-type lib --crate-type cdylib --crate-type staticlib -C embed-bitcode=no -C debuginfo=2 -C rpath -C incremental=[REDACTED] -C link-arg=-Wl,-undefined,dynamic_lookup

note: some of the compiler flags provided by cargo are hidden

```
stack backtrace:
   0:       0x7fa5d83288 - std::backtrace_rs::backtrace::libunwind::trace::hc361c690c6cc0a2e
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:       0x7fa5d83288 - std::backtrace_rs::backtrace::trace_unsynchronized::h4f1674dccde43951
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:       0x7fa5d83288 - std::sys_common::backtrace::_print_fmt::h2d01fbdb84f1e379
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:       0x7fa5d83288 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc7b3260ea43aec6
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:       0x7fa5dd52f4 - core::fmt::write::h4f5007ce80c73d48
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:       0x7fa5d75bb0 - std::io::Write::write_fmt::hb098837b295db6cc
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:       0x7fa5d83094 - std::sys_common::backtrace::_print::h7cecf3307e13698b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:       0x7fa5d83094 - std::sys_common::backtrace::print::hdbc0c12b5021624f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:       0x7fa5d85af4 - std::panicking::default_hook::{{closure}}::h619ebd920082027b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:       0x7fa5d85838 - std::panicking::default_hook::h813df240b3c7c49f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:       0x7fa6a4ca14 - rustc_driver[655e371651c097fd]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:       0x7fa5d86258 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3ccdcad3ae931b01
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:2001:9
  12:       0x7fa5d86258 - std::panicking::rust_panic_with_hook::hb3a0fceb72840e7d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:692:13
  13:       0x7fa5d85fd4 - std::panicking::begin_panic_handler::{{closure}}::h6932dca675575db1
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:577:13
  14:       0x7fa5d83718 - std::sys_common::backtrace::__rust_end_short_backtrace::hfde39e017ad84c30
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  15:       0x7fa5d85d58 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  16:       0x7fa5d512e4 - core::panicking::panic_fmt::h6aa2a797076a42e8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  17:       0x7faabed3dc - <rustc_type_ir[5e577e442a42a2b2]::IntTy as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode
  18:       0x7faac27e40 - <rustc_type_ir[5e577e442a42a2b2]::sty::TyKind<rustc_middle[4753f46d555a141e]::ty::context::TyCtxt> as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode
  19:       0x7faac7b188 - <rustc_middle[4753f46d555a141e]::ty::Ty as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode
  20:       0x7faacb4a44 - <rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext as rustc_type_ir[5e577e442a42a2b2]::codec::TyDecoder>::cached_ty_for_shorthand::<<rustc_middle[4753f46d555a141e]::ty::Ty as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode::{closure#0}>
  21:       0x7faac7b268 - <rustc_middle[4753f46d555a141e]::ty::Ty as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode
  22:       0x7faac29394 - <rustc_middle[4753f46d555a141e]::ty::subst::GenericArg as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode
  23:       0x7faac1a00c - <rustc_middle[4753f46d555a141e]::ty::subst::GenericArg as rustc_type_ir[5e577e442a42a2b2]::InternIteratorElement<rustc_middle[4753f46d555a141e]::ty::subst::GenericArg, &rustc_middle[4753f46d555a141e]::ty::list::List<rustc_middle[4753f46d555a141e]::ty::subst::GenericArg>>>::intern_with::<core[c0f9e66d1bb20e54]::iter::adapters::map::Map<core[c0f9e66d1bb20e54]::ops::range::Range<usize>, <&rustc_middle[4753f46d555a141e]::ty::list::List<rustc_middle[4753f46d555a141e]::ty::subst::GenericArg> as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode::{closure#0}>, <rustc_middle[4753f46d555a141e]::ty::context::TyCtxt>::mk_substs<core[c0f9e66d1bb20e54]::iter::adapters::map::Map<core[c0f9e66d1bb20e54]::ops::range::Range<usize>, <&rustc_middle[4753f46d555a141e]::ty::list::List<rustc_middle[4753f46d555a141e]::ty::subst::GenericArg> as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode::{closure#0}>>::{closure#0}>
  24:       0x7faabd5a20 - <&rustc_middle[4753f46d555a141e]::ty::list::List<rustc_middle[4753f46d555a141e]::ty::subst::GenericArg> as rustc_serialize[31d802baa5b3cab9]::serialize::Decodable<rustc_metadata[624cdbc944854026]::rmeta::decoder::DecodeContext>>::decode
  25:       0x7faac61214 - <rustc_metadata[624cdbc944854026]::rmeta::LazyValue<rustc_middle[4753f46d555a141e]::ty::sty::TraitRef>>::decode::<(rustc_metadata[624cdbc944854026]::creader::CrateMetadataRef, rustc_middle[4753f46d555a141e]::ty::context::TyCtxt)>
  26:       0x7faac91a40 - rustc_metadata[624cdbc944854026]::rmeta::decoder::cstore_impl::provide_extern::impl_trait_ref
  27:       0x7faa5d9b78 - <rustc_query_system[4f607f6d4ce1a73]::dep_graph::graph::DepGraph<rustc_middle[4753f46d555a141e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[4753f46d555a141e]::ty::context::TyCtxt, rustc_span[acb5271dfc350b62]::def_id::DefId, core[c0f9e66d1bb20e54]::option::Option<rustc_middle[4753f46d555a141e]::ty::sty::TraitRef>>
  28:       0x7faa78d104 - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::try_execute_query::<rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt, rustc_query_system[4f607f6d4ce1a73]::query::caches::DefaultCache<rustc_span[acb5271dfc350b62]::def_id::DefId, core[c0f9e66d1bb20e54]::option::Option<rustc_middle[4753f46d555a141e]::ty::sty::TraitRef>>>
  29:       0x7faa82d618 - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::get_query::<rustc_query_impl[d8c5c3257f8a5375]::queries::impl_trait_ref, rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt>
  30:       0x7faa4d9208 - <rustc_query_impl[d8c5c3257f8a5375]::Queries as rustc_middle[4753f46d555a141e]::ty::query::QueryEngine>::impl_trait_ref
  31:       0x7fab12b280 - <rustc_middle[4753f46d555a141e]::traits::specialization_graph::Children as rustc_trait_selection[595987372141a48a]::traits::specialize::specialization_graph::ChildrenExt>::insert_blindly
  32:       0x7fab1db0e8 - rustc_trait_selection[595987372141a48a]::traits::specialize::specialization_graph_provider
  33:       0x7faa5e4d58 - <rustc_query_system[4f607f6d4ce1a73]::dep_graph::graph::DepGraph<rustc_middle[4753f46d555a141e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[4753f46d555a141e]::ty::context::TyCtxt, rustc_span[acb5271dfc350b62]::def_id::DefId, rustc_middle[4753f46d555a141e]::traits::specialization_graph::Graph>
  34:       0x7faa72eca8 - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::try_execute_query::<rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt, rustc_query_system[4f607f6d4ce1a73]::query::caches::ArenaCache<rustc_span[acb5271dfc350b62]::def_id::DefId, rustc_middle[4753f46d555a141e]::traits::specialization_graph::Graph>>
  35:       0x7faa83c424 - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::get_query::<rustc_query_impl[d8c5c3257f8a5375]::queries::specialization_graph_of, rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt>
  36:       0x7fa98548b4 - rustc_hir_analysis[9ab94e5d084e2c18]::coherence::coherent_trait
  37:       0x7faa5ea328 - <rustc_query_system[4f607f6d4ce1a73]::dep_graph::graph::DepGraph<rustc_middle[4753f46d555a141e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[4753f46d555a141e]::ty::context::TyCtxt, rustc_span[acb5271dfc350b62]::def_id::DefId, ()>
  38:       0x7faa7b4068 - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::try_execute_query::<rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt, rustc_query_system[4f607f6d4ce1a73]::query::caches::DefaultCache<rustc_span[acb5271dfc350b62]::def_id::DefId, ()>>
  39:       0x7faa82cd9c - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::get_query::<rustc_query_impl[d8c5c3257f8a5375]::queries::coherent_trait, rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt>
  40:       0x7fa97fdef0 - <rustc_session[e91959d9c900515]::session::Session>::track_errors::<rustc_hir_analysis[9ab94e5d084e2c18]::check_crate::{closure#3}, ()>
  41:       0x7fa97ae2dc - rustc_hir_analysis[9ab94e5d084e2c18]::check_crate
  42:       0x7fa6b02740 - rustc_interface[f1c81e0b1d9667fe]::passes::analysis
  43:       0x7faa5fbe1c - <rustc_query_system[4f607f6d4ce1a73]::dep_graph::graph::DepGraph<rustc_middle[4753f46d555a141e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[4753f46d555a141e]::ty::context::TyCtxt, (), core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>
  44:       0x7faa7daddc - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::try_execute_query::<rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt, rustc_query_system[4f607f6d4ce1a73]::query::caches::DefaultCache<(), core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>>
  45:       0x7faa844674 - rustc_query_system[4f607f6d4ce1a73]::query::plumbing::get_query::<rustc_query_impl[d8c5c3257f8a5375]::queries::analysis, rustc_query_impl[d8c5c3257f8a5375]::plumbing::QueryCtxt>
  46:       0x7fa69e05d4 - <rustc_interface[f1c81e0b1d9667fe]::passes::QueryContext>::enter::<rustc_driver[655e371651c097fd]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>
  47:       0x7fa6a25d04 - <rustc_interface[f1c81e0b1d9667fe]::interface::Compiler>::enter::<rustc_driver[655e371651c097fd]::run_compiler::{closure#1}::{closure#2}, core[c0f9e66d1bb20e54]::result::Result<core[c0f9e66d1bb20e54]::option::Option<rustc_interface[f1c81e0b1d9667fe]::queries::Linker>, rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>
  48:       0x7fa69c4bfc - rustc_span[acb5271dfc350b62]::with_source_map::<core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>, rustc_interface[f1c81e0b1d9667fe]::interface::run_compiler<core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>, rustc_driver[655e371651c097fd]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  49:       0x7fa6a16994 - <scoped_tls[ab4fa6aa7d0ff839]::ScopedKey<rustc_span[acb5271dfc350b62]::SessionGlobals>>::set::<rustc_interface[f1c81e0b1d9667fe]::interface::run_compiler<core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>, rustc_driver[655e371651c097fd]::run_compiler::{closure#1}>::{closure#0}, core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>
  50:       0x7fa69e3298 - std[6ff08207d27ca969]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f1c81e0b1d9667fe]::util::run_in_thread_pool_with_globals<rustc_interface[f1c81e0b1d9667fe]::interface::run_compiler<core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>, rustc_driver[655e371651c097fd]::run_compiler::{closure#1}>::{closure#0}, core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>
  51:       0x7fa69cab2c - <<std[6ff08207d27ca969]::thread::Builder>::spawn_unchecked_<rustc_interface[f1c81e0b1d9667fe]::util::run_in_thread_pool_with_globals<rustc_interface[f1c81e0b1d9667fe]::interface::run_compiler<core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>, rustc_driver[655e371651c097fd]::run_compiler::{closure#1}>::{closure#0}, core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[c0f9e66d1bb20e54]::result::Result<(), rustc_errors[ff496d742c263fe1]::ErrorGuaranteed>>::{closure#1} as core[c0f9e66d1bb20e54]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:       0x7fa5d8f0a8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4227ee841b6f7a16
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  53:       0x7fa5d8f0a8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h89af2e72e0ffa477
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
  54:       0x7fa5d8f0a8 - std::sys::unix::thread::Thread::new::thread_start::hcf486b40587c45dc
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys/unix/thread.rs:108:17
  55:       0x7fa5af9648 - start_thread
                               at ./nptl/./nptl/pthread_create.c:477:8
  56:       0x7fa5c2dc1c - thread_start
                               at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:78
  57:                0x0 - <unknown>
```

**Comment by jyn514** [comment]
This is missing the actual panic message. There should be some output above that says something like "thread rustc panicked at ...", could you paste it here please?

**Comment by hmuint32** [comment]
After following instructions [here](https://github.com/tonarino/innernet/issues/225#issuecomment-1264846126), my compilation is able to complete. 

@jyn514 i will be closing this issue. Thanks for your help.
