### ISSUE TITLE
std::process:Command::spawn panics when pre_exec hook fails if SIGCHLD is ignored

### ISSUE THREAD

**Issue by kennylevinsen** [rust-lang/rust#110317]
On Linux when a `CommandExt::pre_exec` hook is in use, `std::process::Command::spawn` forks, calls `do_exec` and then runs each of the hooks in order. If any of these hooks fail, the `Err` bubbles up and the child process writes the errno to the pipe of the parent before exiting.

After the parent reads the error, it calls `Command::wait` which internally calls `waitpid(2)`. When a `SIGCHLD` handler is installed - in this case, `SIG_IGN` - there is no child to wait for, so `waitpid(2)` returns `ECHILD`. This leads to `spawn` panicking:

```
thread 'main' panicked at 'wait() should either return Ok or panic', library/std/src/sys/unix/process/process_unix.rs:129:21
```

I expected to be able to return an error from `pre_exec` hooks without causing a panic, even if `SIGCHLD` is handled.

### Reproduction

The issue can be reproduced as follows:

```rust
// Built with libc 0.2.141
fn main() {
    use std::os::unix::process::CommandExt;
    let mut cmd = std::process::Command::new("/bin/sh");

    unsafe {
        libc::signal(libc::SIGCHLD, libc::SIG_IGN);
        // Bogus error - this was originally a failed call to `setsid`
        cmd.pre_exec(|| Err(std::io::Error::last_os_error()) );
    }

    cmd.spawn().unwrap();
}
```

Which results in
```
thread 'main' panicked at 'wait() should either return Ok or panic', library/std/src/sys/unix/process/process_unix.rs:129:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5e1d3299a290026b85787bc9c7e72bcc53ac283f/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/5e1d3299a290026b85787bc9c7e72bcc53ac283f/library/core/src/panicking.rs:67:14
   2: std::sys::unix::process::process_inner::<impl std::sys::unix::process::process_common::Command>::spawn
   3: std::process::Command::spawn
             at /rustc/5e1d3299a290026b85787bc9c7e72bcc53ac283f/library/std/src/process.rs:893:9
   4: rust_test::main
             at ./src/main.rs:10:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/5e1d3299a290026b85787bc9c7e72bcc53ac283f/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The waitpid behavior can also be observed in plain C with:

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <errno.h>
#include <string.h>
#include <sys/wait.h>

int main() {
	signal(SIGCHLD, SIG_IGN);
	pid_t pid = fork();
	if (pid == -1) {
		fprintf(stderr, "fork failed: %d, %s\n", errno, strerror(errno));
		return 1;
	}

	if (pid == 0) {
		fprintf(stderr, "child!\n");
		return 0;
	}

	int status = 0;
	int res = waitpid(pid, &status, 0);
	fprintf(stderr, "res: %d, status: %d, errno: %d, %s\n", res, status, errno, strerror(errno));
	return 0;
}
```

Which outputs:
```
child!
res: -1, errno: 10, No child processes⏎
```

If the signal handler is commented out, `waitpid` works as the `Command::spawn` expects.

### Meta

- `rustc --version --verbose`:
```
rustc 1.70.0-nightly (5e1d3299a 2023-03-31)
binary: rustc
commit-hash: 5e1d3299a290026b85787bc9c7e72bcc53ac283f
commit-date: 2023-03-31
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```
- Kernel: Linux 6.2.10-arch1-1
- glibc: 2.37-2

**Comment by Urgau** [comment]
This is probably relevant, the standard library is using the `clone3` syscall with `SIGCHLD` as the exit child signal.
https://github.com/rust-lang/rust/blob/71ef9ecbdedb67c32f074884f503f8e582855c2f/library/std/src/sys/unix/process/process_unix.rs#L225

**Comment by kennylevinsen** [comment]
> This is probably relevant, the standard library is using the clone3 syscall with SIGCHLD as the exit child signal.

Yeah, this means that we will have the normal POSIX process behavior. See `man 3 _Exit`, "Consequences of Process Termination", and `man 3 sigaction`, and the flags "SA_NOCLDSTOP" and "SA_NOCLDWAIT". The issue here being that by setting SIG_IGN as the SIGCHLD handler, or by using one of the dedicated flags to `sigaction`, the parent process indicates that it is not interested in waiting on its children and all, and so the kernel just discards the process and its status immediately when it exits. With that, it is no longer possible to wait on the process.

**Comment by jyn514** [comment]
@kennylevinsen is this specific to Linux or will it happen on other Unix systems too?

In general I'm not sure what guarantees we have around signal handling.

**Comment by LunarLambda** [comment]
Would blocking the signal via `sigprocmask` work? As far as I know, that's the correct way to work with APIs like `signalfd` but I'm not sure how it intersects with something like `wait` calls. From the Linux code snippet it *looks* like blocking (rather than ignoring) SIGCHLD would still allow having the regular reaping behaviour

(specifically, blocking a signal causes it to be queued and once unblocked, the handler would be executed. But again, unsure about the intersection with `wait`.)

**Comment by LunarLambda** [comment]
> @kennylevinsen is this specific to Linux or will it happen on other Unix systems too?
> 
> In general I'm not sure what guarantees we have around signal handling.

The behaviour of "children will be reaped without needing to be waited on when SIGCHLD is set to SIG_IGN" is part of POSIX, so all conforming unix platforms will behave this way.

**Comment by kennylevinsen** [comment]
> Would blocking the signal via sigprocmask work?

It does not have effect on whether the process needs to call `wait`. In the Linux implementation, only `SIG_IGN` or `SA_NOCLDWAIT` affect whether autoreaping is enabled.

The point of the exercise is automatic reaping, where further wait calls are not required.
