### ISSUE TITLE
error: the compiler unexpectedly panicked. this is a bug.

### ISSUE THREAD

**Issue by WhyNotHugo** [rust-lang/rust#110875]
### Code

This git repository: https://git.sr.ht/~whynothugo/vdirsyncer-rs
And this commit: 8144e7235833d5b6ab6011559c2f920d163a2877

Run `cargo doc`.

Sorry I don't have a minimal example; I've no idea what the exact cause is.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16) (Alpine Linux)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-alpine-linux-musl
release: 1.69.0
LLVM version: 15.0.7
```

I can't test nightlies due to https://github.com/rust-lang/rust/issues/107566 and https://github.com/rust-lang/rust/issues/108878

### Error output

```console
cargo doc
 Documenting futures-executor v0.3.26
 Documenting tokio-rustls v0.23.4
 Documenting hyper v0.14.24
 Documenting toml_datetime v0.6.1
 Documenting serde_spanned v0.6.1
 Documenting rustix v0.36.11
 Documenting toml_edit v0.19.8
 Documenting futures v0.3.26
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2228:18
stack backtrace:
   0:     0x7fc1d1f1460a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85de4b219aa98fc9
   1:     0x7fc1d1f74d6e - core::fmt::write::hbc4b86e694d3f624
   2:     0x7fc1d1f08c65 - <unknown>
   3:     0x7fc1d1f143d5 - <unknown>
   4:     0x7fc1d1f1714f - <unknown>
   5:     0x7fc1d1f16e8b - std::panicking::default_hook::hb32ec55bcfb6be75
   6:     0x7fc1d2e6aad5 - <unknown>
   7:     0x7fc1d1f1792d - std::panicking::rust_panic_with_hook::hfa12b892f41beb71
   8:     0x7fc1d1f176a9 - <unknown>
   9:     0x7fc1d1f14a76 - <unknown>
  10:     0x7fc1d1f173b2 - rust_begin_unwind
  11:     0x7fc1d1edc913 - core::panicking::panic_fmt::hd4a5600d925a6ae4
  12:     0x7fc1d1f715f1 - <unknown>
  13:     0x7fc1d1f7159b - <unknown>
  14:     0x7fc1d1edc8d6 - core::option::expect_failed::h9748ab3a7e2da6a1
  15:     0x7fc1d36a80ef - <unknown>
  16:     0x7fc1d3f2be0d - <unknown>
  17:     0x7fc1d41e14c9 - <unknown>
  18:     0x55ca91c5d520 - <unknown>
  19:     0x55ca91c5d7de - <unknown>
  20:     0x55ca91c6247e - <unknown>
  21:     0x55ca91c8adda - <unknown>
  22:     0x55ca91c667fb - <unknown>
  23:     0x55ca91c8adda - <unknown>
  24:     0x55ca91c667fb - <unknown>
  25:     0x55ca91c5c8a2 - <unknown>
  26:     0x55ca91ba9b2c - <unknown>
  27:     0x55ca91c99556 - <unknown>
  28:     0x55ca91ac25bb - <unknown>
  29:     0x55ca91ae9954 - <unknown>
  30:     0x7fc1d1f212f3 - <unknown>
  31:     0x7fc1d5351c0b - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) (Alpine Linux) running on x86_64-alpine-linux-musl

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.11/src/lib.rs --cap-lints allow -o '/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/doc' --cfg 'feature="default"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=133 -C metadata=baa4de618b859767 -L 'dependency=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps' --extern 'bitflags=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/libbitflags-e6e034bd14f08a6d.rmeta' --extern 'io_lifetimes=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/libio_lifetimes-c2708d86792ecead.rmeta' --extern 'libc=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/liblibc-20bc37a273d08ba2.rmeta' --extern 'linux_raw_sys=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/liblinux_raw_sys-85df8ff196080b74.rmeta' --deny=warnings --allow=incomplete-features --crate-version 0.36.11 --cfg linux_raw --cfg asm` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```console
> RUST_BACKTRACE=1 cargo doc  
 Documenting domain v0.7.2
 Documenting hyper-rustls v0.23.2
 Documenting rustix v0.36.11
 Documenting toml v0.7.3
thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2228:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) (Alpine Linux) running on x86_64-alpine-linux-musl

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [doc_link_resolutions] resolutions for documentation links for a module
end of query stack
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.11/src/lib.rs --cap-lints allow -o '/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/doc' --cfg 'feature="default"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=133 -C metadata=baa4de618b859767 -L 'dependency=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps' --extern 'bitflags=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/libbitflags-e6e034bd14f08a6d.rmeta' --extern 'io_lifetimes=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/libio_lifetimes-c2708d86792ecead.rmeta' --extern 'libc=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/liblibc-20bc37a273d08ba2.rmeta' --extern 'linux_raw_sys=/home/hugo/src/git.sr.ht/~whynothugo/vdirsyncer-rs/target/debug/deps/liblinux_raw_sys-85df8ff196080b74.rmeta' --deny=warnings --allow=incomplete-features --crate-version 0.36.11 --cfg linux_raw --cfg asm` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

</p>
</details>

**Comment by WhyNotHugo** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/110626
