### ISSUE TITLE
ICE failed to resolve instance for fn

### ISSUE THREAD

**Issue by Florian-Dufly** [rust-lang/rust#110841]
### Code

```Rust
// Private code that sadly can't be leaked
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (7aa413d59 2023-02-19)
binary: rustc
commit-hash: 7aa413d59206fd511137728df3d9e0fd377429bd
commit-date: 2023-02-19
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```

error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:397:18: failed to resolve instance for <fn(ReadableSession, Cookies, Query<HistoryQuery>) -> impl Future<Output = impl IntoResponse> {history} as Handler<(axum_core::extract::private::ViaParts, ReadableSession, Cookies, Query<HistoryQuery>), ()>>::with_state

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0:     0x7fdcac16aa7a - std::backtrace_rs::backtrace::libunwind::trace::h9489b6bb69d0b539
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fdcac16aa7a - std::backtrace_rs::backtrace::trace_unsynchronized::h074cc8d03fa8d3dc
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdcac16aa7a - std::sys_common::backtrace::_print_fmt::h855b454124c5eb62
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fdcac16aa7a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb1cc20dbe9783028
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fdcac1ca9fe - core::fmt::write::h2ce679bf0de92319
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/fmt/mod.rs:1232:17
   5:     0x7fdcac15af25 - std::io::Write::write_fmt::hf0d271cfceb9d3c2
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/io/mod.rs:1684:15
   6:     0x7fdcac16a845 - std::sys_common::backtrace::_print::ha1c1c6cae6faf548
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fdcac16a845 - std::sys_common::backtrace::print::h4c052fa11a0cef4b
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fdcac16d5bf - std::panicking::default_hook::{{closure}}::h844c6ede57d48540
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:267:22
   9:     0x7fdcac16d2fb - std::panicking::default_hook::h854c8cb7dd25b7a5
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:286:9
  10:     0x7fdcaf4392b5 - <rustc_driver_impl[6e32b0e3e4ecc577]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[7c7d3fa1b0e0eb0]::ops::function::FnOnce<(&core[7c7d3fa1b0e0eb0]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7fdcac16ddfd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h99a819f48eb65709
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:2002:9
  12:     0x7fdcac16ddfd - std::panicking::rust_panic_with_hook::hfdf377d5e3bd50c0
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:692:13
  13:     0x7fdcaf9d45e1 - std[52c1871eff67b331]::panicking::begin_panic::<rustc_errors[6988015e967c596d]::ExplicitBug>::{closure#0}
  14:     0x7fdcaf9d2916 - std[52c1871eff67b331]::sys_common::backtrace::__rust_end_short_backtrace::<std[52c1871eff67b331]::panicking::begin_panic<rustc_errors[6988015e967c596d]::ExplicitBug>::{closure#0}, !>
  15:     0x7fdcaf9478d6 - std[52c1871eff67b331]::panicking::begin_panic::<rustc_errors[6988015e967c596d]::ExplicitBug>
  16:     0x7fdcafa2b466 - std[52c1871eff67b331]::panic::panic_any::<rustc_errors[6988015e967c596d]::ExplicitBug>
  17:     0x7fdcafa29096 - <rustc_errors[6988015e967c596d]::HandlerInner>::bug::<&alloc[f648dfb059bacbe8]::string::String>
  18:     0x7fdcafa28d60 - <rustc_errors[6988015e967c596d]::Handler>::bug::<&alloc[f648dfb059bacbe8]::string::String>
  19:     0x7fdcafa17acb - rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt::<rustc_span[cd9543e8608582e7]::span_encoding::Span>::{closure#0}
  20:     0x7fdcafa14d3a - rustc_middle[f89b3bfcac62aa00]::ty::context::tls::with_opt::<rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt<rustc_span[cd9543e8608582e7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7fdcafa14d06 - rustc_middle[f89b3bfcac62aa00]::ty::context::tls::with_context_opt::<rustc_middle[f89b3bfcac62aa00]::ty::context::tls::with_opt<rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt<rustc_span[cd9543e8608582e7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7fdcafa17a16 - rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt::<rustc_span[cd9543e8608582e7]::span_encoding::Span>
  23:     0x7fdcadaa9103 - rustc_middle[f89b3bfcac62aa00]::util::bug::bug_fmt
  24:     0x7fdcae1ea48e - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_neighbours
  25:     0x7fdcae1dfaba - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  26:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  27:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  28:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  29:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  30:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  31:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  32:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  33:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  34:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  35:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  36:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  37:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  38:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  39:     0x7fdcae1dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  40:     0x7fdcae82284a - rustc_data_structures[3f3ad1e59c028cf1]::sync::par_for_each_in::<alloc[f648dfb059bacbe8]::vec::Vec<rustc_middle[f89b3bfcac62aa00]::mir::mono::MonoItem>, rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  41:     0x7fdcae8224e1 - <rustc_session[94944b2b2b6abb1d]::session::Session>::time::<(), rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_crate_mono_items::{closure#1}>
  42:     0x7fdcae8220d4 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_crate_mono_items
  43:     0x7fdcae8201b2 - rustc_monomorphize[fa790fcb46b7b10c]::partitioning::collect_and_partition_mono_items
  44:     0x7fdcafd360a1 - <rustc_query_impl[ae5df09473318626]::queries::collect_and_partition_mono_items as rustc_query_system[61b579b99652e722]::query::config::QueryConfig<rustc_query_impl[ae5df09473318626]::plumbing::QueryCtxt>>::compute
  45:     0x7fdcaec61ef1 - <rustc_query_system[61b579b99652e722]::dep_graph::graph::DepGraph<rustc_middle[f89b3bfcac62aa00]::dep_graph::dep_node::DepKind>>::with_task::<rustc_query_impl[ae5df09473318626]::plumbing::QueryCtxt, (), (&rustc_data_structures[3f3ad1e59c028cf1]::unord::UnordSet<rustc_span[cd9543e8608582e7]::def_id::DefId>, &[rustc_middle[f89b3bfcac62aa00]::mir::mono::CodegenUnit])>
  46:     0x7fdcaec61823 - rustc_query_system[61b579b99652e722]::query::plumbing::try_execute_query::<rustc_query_impl[ae5df09473318626]::queries::collect_and_partition_mono_items, rustc_query_impl[ae5df09473318626]::plumbing::QueryCtxt>
  47:     0x7fdcaee39432 - <rustc_query_impl[ae5df09473318626]::Queries as rustc_middle[f89b3bfcac62aa00]::ty::query::QueryEngine>::collect_and_partition_mono_items
  48:     0x7fdcaeb5bf5d - rustc_codegen_ssa[c0b5016b42673f6a]::base::codegen_crate::<rustc_codegen_llvm[60f2ae8d96694fa4]::LlvmCodegenBackend>
  49:     0x7fdcaeb5bd41 - <rustc_codegen_llvm[60f2ae8d96694fa4]::LlvmCodegenBackend as rustc_codegen_ssa[c0b5016b42673f6a]::traits::backend::CodegenBackend>::codegen_crate
  50:     0x7fdcae6c6781 - <rustc_session[94944b2b2b6abb1d]::session::Session>::time::<alloc[f648dfb059bacbe8]::boxed::Box<dyn core[7c7d3fa1b0e0eb0]::any::Any>, rustc_interface[c6f24677e94f9079]::passes::start_codegen::{closure#0}>
  51:     0x7fdcae6c62a9 - rustc_interface[c6f24677e94f9079]::passes::start_codegen
  52:     0x7fdcae6c0e68 - <rustc_middle[f89b3bfcac62aa00]::ty::context::GlobalCtxt>::enter::<<rustc_interface[c6f24677e94f9079]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<alloc[f648dfb059bacbe8]::boxed::Box<dyn core[7c7d3fa1b0e0eb0]::any::Any>, rustc_errors[6988015e967c596d]::ErrorGuaranteed>>
  53:     0x7fdcae6c0554 - <rustc_interface[c6f24677e94f9079]::queries::Queries>::ongoing_codegen
  54:     0x7fdcae6bf6fa - <rustc_interface[c6f24677e94f9079]::interface::Compiler>::enter::<rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}::{closure#2}, core[7c7d3fa1b0e0eb0]::result::Result<core[7c7d3fa1b0e0eb0]::option::Option<rustc_interface[c6f24677e94f9079]::queries::Linker>, rustc_errors[6988015e967c596d]::ErrorGuaranteed>>
  55:     0x7fdcae6bd7a4 - rustc_span[cd9543e8608582e7]::with_source_map::<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_interface[c6f24677e94f9079]::interface::run_compiler<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  56:     0x7fdcae6bcd0d - std[52c1871eff67b331]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c6f24677e94f9079]::util::run_in_thread_pool_with_globals<rustc_interface[c6f24677e94f9079]::interface::run_compiler<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}>::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>
  57:     0x7fdcae6bc75c - <<std[52c1871eff67b331]::thread::Builder>::spawn_unchecked_<rustc_interface[c6f24677e94f9079]::util::run_in_thread_pool_with_globals<rustc_interface[c6f24677e94f9079]::interface::run_compiler<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}>::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>::{closure#1} as core[7c7d3fa1b0e0eb0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7fdcac177c83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd495064039f63337
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
  59:     0x7fdcac177c83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5810b8a5e2a1ff63
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
  60:     0x7fdcac177c83 - std::sys::unix::thread::Thread::new::thread_start::hda99a0382c8f8399
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys/unix/thread.rs:108:17
  61:     0x7fdcabe94b43 - <unknown>
  62:     0x7fdcabf26a00 - <unknown>
  63:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (7aa413d59 2023-02-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
warning: `server_ui` (bin "server_ui") generated 8 warnings (run `cargo fix --bin "server_ui"` to apply 6 suggestions)
error: could not compile `server_ui`; 8 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0:     0x7feef596aa7a - std::backtrace_rs::backtrace::libunwind::trace::h9489b6bb69d0b539
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7feef596aa7a - std::backtrace_rs::backtrace::trace_unsynchronized::h074cc8d03fa8d3dc
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7feef596aa7a - std::sys_common::backtrace::_print_fmt::h855b454124c5eb62
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7feef596aa7a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb1cc20dbe9783028
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7feef59ca9fe - core::fmt::write::h2ce679bf0de92319
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/fmt/mod.rs:1232:17
   5:     0x7feef595af25 - std::io::Write::write_fmt::hf0d271cfceb9d3c2
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/io/mod.rs:1684:15
   6:     0x7feef596a845 - std::sys_common::backtrace::_print::ha1c1c6cae6faf548
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7feef596a845 - std::sys_common::backtrace::print::h4c052fa11a0cef4b
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7feef596d5bf - std::panicking::default_hook::{{closure}}::h844c6ede57d48540
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:267:22
   9:     0x7feef596d2fb - std::panicking::default_hook::h854c8cb7dd25b7a5
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:286:9
  10:     0x7feef8c392b5 - <rustc_driver_impl[6e32b0e3e4ecc577]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[7c7d3fa1b0e0eb0]::ops::function::FnOnce<(&core[7c7d3fa1b0e0eb0]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7feef596ddfd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h99a819f48eb65709
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:2002:9
  12:     0x7feef596ddfd - std::panicking::rust_panic_with_hook::hfdf377d5e3bd50c0
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:692:13
  13:     0x7feef91d45e1 - std[52c1871eff67b331]::panicking::begin_panic::<rustc_errors[6988015e967c596d]::ExplicitBug>::{closure#0}
  14:     0x7feef91d2916 - std[52c1871eff67b331]::sys_common::backtrace::__rust_end_short_backtrace::<std[52c1871eff67b331]::panicking::begin_panic<rustc_errors[6988015e967c596d]::ExplicitBug>::{closure#0}, !>
  15:     0x7feef91478d6 - std[52c1871eff67b331]::panicking::begin_panic::<rustc_errors[6988015e967c596d]::ExplicitBug>
  16:     0x7feef922b466 - std[52c1871eff67b331]::panic::panic_any::<rustc_errors[6988015e967c596d]::ExplicitBug>
  17:     0x7feef9229096 - <rustc_errors[6988015e967c596d]::HandlerInner>::bug::<&alloc[f648dfb059bacbe8]::string::String>
  18:     0x7feef9228d60 - <rustc_errors[6988015e967c596d]::Handler>::bug::<&alloc[f648dfb059bacbe8]::string::String>
  19:     0x7feef9217acb - rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt::<rustc_span[cd9543e8608582e7]::span_encoding::Span>::{closure#0}
  20:     0x7feef9214d3a - rustc_middle[f89b3bfcac62aa00]::ty::context::tls::with_opt::<rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt<rustc_span[cd9543e8608582e7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7feef9214d06 - rustc_middle[f89b3bfcac62aa00]::ty::context::tls::with_context_opt::<rustc_middle[f89b3bfcac62aa00]::ty::context::tls::with_opt<rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt<rustc_span[cd9543e8608582e7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7feef9217a16 - rustc_middle[f89b3bfcac62aa00]::util::bug::opt_span_bug_fmt::<rustc_span[cd9543e8608582e7]::span_encoding::Span>
  23:     0x7feef72a9103 - rustc_middle[f89b3bfcac62aa00]::util::bug::bug_fmt
  24:     0x7feef79ea48e - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_neighbours
  25:     0x7feef79dfaba - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  26:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  27:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  28:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  29:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  30:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  31:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  32:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  33:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  34:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  35:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  36:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  37:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  38:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  39:     0x7feef79dff68 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_items_rec
  40:     0x7feef802284a - rustc_data_structures[3f3ad1e59c028cf1]::sync::par_for_each_in::<alloc[f648dfb059bacbe8]::vec::Vec<rustc_middle[f89b3bfcac62aa00]::mir::mono::MonoItem>, rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  41:     0x7feef80224e1 - <rustc_session[94944b2b2b6abb1d]::session::Session>::time::<(), rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_crate_mono_items::{closure#1}>
  42:     0x7feef80220d4 - rustc_monomorphize[fa790fcb46b7b10c]::collector::collect_crate_mono_items
  43:     0x7feef80201b2 - rustc_monomorphize[fa790fcb46b7b10c]::partitioning::collect_and_partition_mono_items
  44:     0x7feef95360a1 - <rustc_query_impl[ae5df09473318626]::queries::collect_and_partition_mono_items as rustc_query_system[61b579b99652e722]::query::config::QueryConfig<rustc_query_impl[ae5df09473318626]::plumbing::QueryCtxt>>::compute
  45:     0x7feef8461ef1 - <rustc_query_system[61b579b99652e722]::dep_graph::graph::DepGraph<rustc_middle[f89b3bfcac62aa00]::dep_graph::dep_node::DepKind>>::with_task::<rustc_query_impl[ae5df09473318626]::plumbing::QueryCtxt, (), (&rustc_data_structures[3f3ad1e59c028cf1]::unord::UnordSet<rustc_span[cd9543e8608582e7]::def_id::DefId>, &[rustc_middle[f89b3bfcac62aa00]::mir::mono::CodegenUnit])>
  46:     0x7feef8461823 - rustc_query_system[61b579b99652e722]::query::plumbing::try_execute_query::<rustc_query_impl[ae5df09473318626]::queries::collect_and_partition_mono_items, rustc_query_impl[ae5df09473318626]::plumbing::QueryCtxt>
  47:     0x7feef8639432 - <rustc_query_impl[ae5df09473318626]::Queries as rustc_middle[f89b3bfcac62aa00]::ty::query::QueryEngine>::collect_and_partition_mono_items
  48:     0x7feef835bf5d - rustc_codegen_ssa[c0b5016b42673f6a]::base::codegen_crate::<rustc_codegen_llvm[60f2ae8d96694fa4]::LlvmCodegenBackend>
  49:     0x7feef835bd41 - <rustc_codegen_llvm[60f2ae8d96694fa4]::LlvmCodegenBackend as rustc_codegen_ssa[c0b5016b42673f6a]::traits::backend::CodegenBackend>::codegen_crate
  50:     0x7feef7ec6781 - <rustc_session[94944b2b2b6abb1d]::session::Session>::time::<alloc[f648dfb059bacbe8]::boxed::Box<dyn core[7c7d3fa1b0e0eb0]::any::Any>, rustc_interface[c6f24677e94f9079]::passes::start_codegen::{closure#0}>
  51:     0x7feef7ec62a9 - rustc_interface[c6f24677e94f9079]::passes::start_codegen
  52:     0x7feef7ec0e68 - <rustc_middle[f89b3bfcac62aa00]::ty::context::GlobalCtxt>::enter::<<rustc_interface[c6f24677e94f9079]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<alloc[f648dfb059bacbe8]::boxed::Box<dyn core[7c7d3fa1b0e0eb0]::any::Any>, rustc_errors[6988015e967c596d]::ErrorGuaranteed>>
  53:     0x7feef7ec0554 - <rustc_interface[c6f24677e94f9079]::queries::Queries>::ongoing_codegen
  54:     0x7feef7ebf6fa - <rustc_interface[c6f24677e94f9079]::interface::Compiler>::enter::<rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}::{closure#2}, core[7c7d3fa1b0e0eb0]::result::Result<core[7c7d3fa1b0e0eb0]::option::Option<rustc_interface[c6f24677e94f9079]::queries::Linker>, rustc_errors[6988015e967c596d]::ErrorGuaranteed>>
  55:     0x7feef7ebd7a4 - rustc_span[cd9543e8608582e7]::with_source_map::<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_interface[c6f24677e94f9079]::interface::run_compiler<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  56:     0x7feef7ebcd0d - std[52c1871eff67b331]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c6f24677e94f9079]::util::run_in_thread_pool_with_globals<rustc_interface[c6f24677e94f9079]::interface::run_compiler<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}>::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>
  57:     0x7feef7ebc75c - <<std[52c1871eff67b331]::thread::Builder>::spawn_unchecked_<rustc_interface[c6f24677e94f9079]::util::run_in_thread_pool_with_globals<rustc_interface[c6f24677e94f9079]::interface::run_compiler<core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>, rustc_driver_impl[6e32b0e3e4ecc577]::run_compiler::{closure#1}>::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7c7d3fa1b0e0eb0]::result::Result<(), rustc_errors[6988015e967c596d]::ErrorGuaranteed>>::{closure#1} as core[7c7d3fa1b0e0eb0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7feef5977c83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd495064039f63337
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
  59:     0x7feef5977c83 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5810b8a5e2a1ff63
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
  60:     0x7feef5977c83 - std::sys::unix::thread::Thread::new::thread_start::hda99a0382c8f8399
                               at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys/unix/thread.rs:108:17
  61:     0x7feef5694b43 - <unknown>
  62:     0x7feef5726a00 - <unknown>
  63:                0x0 - <unknown>
```

</p>
</details>

**Comment by kehrazy** [comment]
See https://docs.rs/axum/0.6.0-rc.5/axum/attr.debug_handler.html

Not a rustc issue.

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
