### ISSUE TITLE
ICE: no MIR available for DefId(30:3023 ~ wgpu_core[f06f]::track::texture::{impl#0}::any_exclusive)

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#111407]
STR:
```
$ git clone https://github.com/gfx-rs/wgpu/
$ cd wgpu
$ cargo +nightly build --all
```

This is a recent regression. It doesn't happen with nightly-2023-05-06 and starts happening with nightly-2023-05-07 onwards.

The ICE looks like:
```
error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:1038:9: no MIR available for DefId(30:3023 ~ wgpu_core[f06f]::track::texture::{impl#0}::any_exclusive)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7f359096a361 - std::backtrace_rs::backtrace::libunwind::trace::he9e9030cf5bcddaa
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f359096a361 - std::backtrace_rs::backtrace::trace_unsynchronized::hb5e44a77ff0586eb
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f359096a361 - std::sys_common::backtrace::_print_fmt::h38e8723c5d83f22f
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f359096a361 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5e394c4b1f1cb045
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f35909ca6ff - core::fmt::rt::Argument::fmt::ha5dde4cb71578cc2
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/rt.rs:138:9
   5:     0x7f35909ca6ff - core::fmt::write::hb1413899fd777907
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f359095d5c1 - std::io::Write::write_fmt::h08b4eac68313bb0d
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/io/mod.rs:1712:15
   7:     0x7f359096a175 - std::sys_common::backtrace::_print::h2bb25f41b1777226
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f359096a175 - std::sys_common::backtrace::print::ha21981aa5a1c5802
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f359096ce07 - std::panicking::default_hook::{{closure}}::h603ce04329232051
  10:     0x7f359096cbf4 - std::panicking::default_hook::hd4285764fbdb24e1
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/panicking.rs:288:9
  11:     0x7f3593bbf94b - <rustc_driver_impl[27c68de0ac55b06a]::install_ice_hook::{closure#0} as core[3afeaedfb140cde7]::ops::function::FnOnce<(&core[3afeaedfb140cde7]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f359096d527 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h401f21a7538313bc
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1999:9
  13:     0x7f359096d527 - std::panicking::rust_panic_with_hook::h2322eda2481f33bc
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/panicking.rs:695:13
  14:     0x7f35940ae031 - std[53b54636b4f52653]::panicking::begin_panic::<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>::{closure#0}
  15:     0x7f35940aa7e6 - std[53b54636b4f52653]::sys_common::backtrace::__rust_end_short_backtrace::<std[53b54636b4f52653]::panicking::begin_panic<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>::{closure#0}, !>
  16:     0x7f35940aa6d6 - std[53b54636b4f52653]::panicking::begin_panic::<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>
  17:     0x7f35940a5264 - <rustc_errors[2afb0e2cc7c4c42d]::HandlerInner>::bug::<alloc[a4f318becb59a05]::string::String>
  18:     0x7f35940a4d76 - <rustc_errors[2afb0e2cc7c4c42d]::Handler>::bug::<alloc[a4f318becb59a05]::string::String>
  19:     0x7f3594131bac - rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt::<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}
  20:     0x7f359413137a - rustc_middle[232bd29a687eeda3]::ty::context::tls::with_opt::<rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f359413134a - rustc_middle[232bd29a687eeda3]::ty::context::tls::with_context_opt::<rustc_middle[232bd29a687eeda3]::ty::context::tls::with_opt<rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f3591dc8f8d - rustc_middle[232bd29a687eeda3]::util::bug::bug_fmt
  23:     0x7f3592a41845 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_neighbours
  24:     0x7f3592a31676 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
  25:     0x7f3592a31ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
  26:     0x7f3592a31ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
  27:     0x7f3592a31ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
  28:     0x7f3592a31ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
  29:     0x7f359301b250 - rustc_data_structures[fba7df231146955e]::sync::par_for_each_in::<alloc[a4f318becb59a05]::vec::Vec<rustc_middle[232bd29a687eeda3]::mir::mono::MonoItem>, rustc_monomorphize[6a4925edab24b3f4]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  30:     0x7f359301af74 - <rustc_session[f2a4139b8ec92988]::session::Session>::time::<(), rustc_monomorphize[6a4925edab24b3f4]::collector::collect_crate_mono_items::{closure#1}>
  31:     0x7f359301a050 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_crate_mono_items
  32:     0x7f35930188f7 - rustc_monomorphize[6a4925edab24b3f4]::partitioning::collect_and_partition_mono_items
  33:     0x7f35933dc894 - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::collect_and_partition_mono_items, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
  34:     0x7f35933dc2bd - rustc_query_impl[94005537e54250be]::get_query::collect_and_partition_mono_items
  35:     0x7f35933b0050 - rustc_codegen_ssa[4e498a107e2a3c27]::back::symbol_export::exported_symbols_provider_local
  36:     0x7f3594466df8 - <rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::execute_job_incr<rustc_query_impl[94005537e54250be]::queries::exported_symbols, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[3afeaedfb140cde7]::ops::function::FnOnce<((rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt, rustc_query_impl[94005537e54250be]::queries::exported_symbols), rustc_span[811089187935bcb6]::def_id::CrateNum)>>::call_once
  37:     0x7f35932cafe1 - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::exported_symbols, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
  38:     0x7f35932ca6c5 - rustc_query_impl[94005537e54250be]::get_query::exported_symbols
  39:     0x7f3592e546fe - <rustc_metadata[445d68004e50344]::rmeta::encoder::EncodeContext>::encode_crate_root
  40:     0x7f3592de97e4 - rustc_metadata[445d68004e50344]::rmeta::encoder::encode_metadata_impl
  41:     0x7f3592de48b6 - rustc_metadata[445d68004e50344]::rmeta::encoder::encode_metadata
  42:     0x7f3592de324e - rustc_metadata[445d68004e50344]::fs::encode_and_write_metadata
  43:     0x7f3592dd13df - rustc_interface[1005215f39c21569]::passes::start_codegen
  44:     0x7f3592dcd0d7 - <rustc_middle[232bd29a687eeda3]::ty::context::GlobalCtxt>::enter::<<rustc_interface[1005215f39c21569]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<alloc[a4f318becb59a05]::boxed::Box<dyn core[3afeaedfb140cde7]::any::Any>, rustc_span[811089187935bcb6]::ErrorGuaranteed>>
  45:     0x7f3592dcc84d - <rustc_interface[1005215f39c21569]::queries::Queries>::ongoing_codegen
  46:     0x7f3592dcbce3 - <rustc_interface[1005215f39c21569]::interface::Compiler>::enter::<rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}::{closure#2}, core[3afeaedfb140cde7]::result::Result<core[3afeaedfb140cde7]::option::Option<rustc_interface[1005215f39c21569]::queries::Linker>, rustc_span[811089187935bcb6]::ErrorGuaranteed>>
  47:     0x7f3592dc933b - std[53b54636b4f52653]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1005215f39c21569]::util::run_in_thread_pool_with_globals<rustc_interface[1005215f39c21569]::interface::run_compiler<core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>, rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}>::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>
  48:     0x7f3593498f55 - <<std[53b54636b4f52653]::thread::Builder>::spawn_unchecked_<rustc_interface[1005215f39c21569]::util::run_in_thread_pool_with_globals<rustc_interface[1005215f39c21569]::interface::run_compiler<core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>, rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}>::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#1} as core[3afeaedfb140cde7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  49:     0x7f35909779d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h20fe0a24dda744f1
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1985:9
  50:     0x7f35909779d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb11b4529d66356f4
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1985:9
  51:     0x7f35909779d5 - std::sys::unix::thread::Thread::new::thread_start::h896be1b4ceadbc98
                               at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys/unix/thread.rs:108:17
  52:     0x7f3594c5eea7 - start_thread
                               at ./nptl/pthread_create.c:477:8
  53:     0x7f359079ca2f - clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  54:                0x0 - <unknown>
```

**Comment by glandium** [comment]
cargo-bisect-rustc points to https://github.com/rust-lang/rust/commit/31a4f2da575f5e335bdbbe7f12a694f9e74ad0a1

**Comment by glandium** [comment]
Which made me find #111320, which this is a dupe of.
