### ISSUE TITLE
Compiler panicked when installing `mdbook-mermaid=0.12.6`

### ISSUE THREAD

**Issue by hayesall** [rust-lang/rust#111545]
(Need some time to reproduce on nightly)

This looks kinda similar to https://github.com/rust-lang/rust/issues/111542 from a couple hours ago.

### Reproducing

On WSL, I ran:

```bash
cargo install mdbook             # Installed mdbook v0.4.29
cargo install mdbook-mermaid     # Panicked
```

### Meta

`rustc --version --verbose`:

```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

### Error output

```
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mdbook-mermaid v0.12.6`, intermediate artifacts can be found at `/tmp/cargo-install57aL4h`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'could not lift for printing', compiler/rustc_middle/src/ty/print/pretty.rs:2664:1
stack backtrace:
   0:     0x7f5de1c0131a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5de1c0131a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5de1c0131a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f5de1c0131a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5de1c64b6e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f5de1bf42c5 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x7f5de1c010e5 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f5de1c010e5 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f5de1c03e5f - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x7f5de1c03b9b - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x7f5de4e658b5 - <rustc_driver_impl[fb92b3e21ac03dce]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[911a585bea10363d]::ops::function::FnOnce<(&core[911a585bea10363d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f5de1c0469d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6507bddc3eebb4a5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
  12:     0x7f5de1c0469d - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
  13:     0x7f5de1c04419 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  14:     0x7f5de1c01786 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f5de1c04122 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  16:     0x7f5de1c60ec3 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  17:     0x7f5de1c61031 - core::panicking::panic_display::ha103dd28e5023b08
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:147:5
  18:     0x7f5de1c60fdb - core::panicking::panic_str::h940bf021f492dc8c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:131:5
  19:     0x7f5de1c60c46 - core::option::expect_failed::h09b982639336e7ea
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/option.rs:2045:5
  20:     0x7f5de2feb5dd - <rustc_middle[1a4ce3311a146f18]::ty::Ty as core[911a585bea10363d]::fmt::Display>::fmt
  21:     0x7f5de54335bd - <rustc_middle[1a4ce3311a146f18]::ty::Ty as core[911a585bea10363d]::fmt::Debug>::fmt
  22:     0x7f5de1c64b6e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
  23:     0x7f5de1c649b0 - <core::fmt::Arguments as core::fmt::Display>::fmt::h4175b056ed0fab26
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:559:9
  24:     0x7f5de1c64b6e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
  25:     0x7f5de1c5398f - core::fmt::Write::write_fmt::h07ca8bb6411dff76
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:197:9
  26:     0x7f5de1c5398f - alloc::fmt::format::format_inner::hb8a7cc9ead64df92
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/fmt.rs:612:9
  27:     0x7f5de3e3c54a - <rustc_borrowck[34f28a8e93f81a6b]::type_check::TypeChecker>::typeck_mir
  28:     0x7f5de3d971ed - rustc_borrowck[34f28a8e93f81a6b]::nll::compute_regions
  29:     0x7f5de3d69a0c - rustc_borrowck[34f28a8e93f81a6b]::do_mir_borrowck
  30:     0x7f5de3d62e1e - rustc_borrowck[34f28a8e93f81a6b]::mir_borrowck
  31:     0x7f5de3f7828d - rustc_query_system[caf472e4bac2b2b6]::query::plumbing::try_execute_query::<rustc_query_impl[a4bd04fc7a0236b8]::queries::mir_borrowck, rustc_query_impl[a4bd04fc7a0236b8]::plumbing::QueryCtxt>
  32:     0x7f5de32ecdbf - rustc_data_structures[a232da6b1231993b]::sync::par_for_each_in::<&[rustc_span[fab0eb11f1fed58d]::def_id::LocalDefId], <rustc_middle[1a4ce3311a146f18]::hir::map::Map>::par_body_owners<rustc_interface[bd8390756bd7a52a]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
  33:     0x7f5de32ec9de - <rustc_session[b87ece769e9b9511]::session::Session>::time::<(), rustc_interface[bd8390756bd7a52a]::passes::analysis::{closure#2}>
  34:     0x7f5de32ec160 - rustc_interface[bd8390756bd7a52a]::passes::analysis
  35:     0x7f5de46bf97d - rustc_query_system[caf472e4bac2b2b6]::query::plumbing::try_execute_query::<rustc_query_impl[a4bd04fc7a0236b8]::queries::analysis, rustc_query_impl[a4bd04fc7a0236b8]::plumbing::QueryCtxt>
  36:     0x7f5de46bf67f - <rustc_query_impl[a4bd04fc7a0236b8]::Queries as rustc_middle[1a4ce3311a146f18]::ty::query::QueryEngine>::analysis
  37:     0x7f5de4505c16 - <rustc_middle[1a4ce3311a146f18]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>
  38:     0x7f5de40b6d38 - rustc_span[fab0eb11f1fed58d]::with_source_map::<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  39:     0x7f5de40ae3cc - std[685882fd5f6d52e5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bd8390756bd7a52a]::util::run_in_thread_pool_with_globals<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>
  40:     0x7f5de40addfa - <<std[685882fd5f6d52e5]::thread::Builder>::spawn_unchecked_<rustc_interface[bd8390756bd7a52a]::util::run_in_thread_pool_with_globals<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#1} as core[911a585bea10363d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f5de1c0e593 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39990b24eedef2ab
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  42:     0x7f5de1c0e593 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h01a027258444143b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  43:     0x7f5de1c0e593 - std::sys::unix::thread::Thread::new::thread_start::ha4f1cdd9c25884ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7f5de1955b43 - <unknown>
  45:     0x7f5de19e7a00 - <unknown>
  46:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `utils::render_markdown_with_path`
#1 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no warnings or errors encountered even though `delayed_good_path_bugs` issued

error: internal compiler error: trimmed_def_paths constructed but no error emitted; use `DelayDm` for lints or `with_no_trimmed_paths` for debugging
  |
  = note: delayed at    0: <rustc_errors::Handler>::delay_good_path_bug::<&str>
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::trimmed_def_paths, rustc_query_impl::plumbing::QueryCtxt>
             3: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::trimmed_def_paths
             4: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             5: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::Printer>::print_def_path
             6: <rustc_middle::ty::print::pretty::FmtPrinter as rustc_middle::ty::print::pretty::PrettyPrinter>::print_value_path
             7: <rustc_middle::mir::ConstantKind as core::fmt::Display>::fmt
             8: core::fmt::write
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
             9: core::fmt::Formatter::write_fmt
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1686:9
            10: <rustc_middle::mir::Constant as core::fmt::Debug>::fmt
            11: core::fmt::write
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
            12: core::fmt::Formatter::write_fmt
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1686:9
            13: <rustc_middle::mir::syntax::Operand as core::fmt::Debug>::fmt
            14: core::fmt::write
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
            15: core::fmt::Formatter::write_fmt
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1686:9
            16: <rustc_middle::mir::syntax::TerminatorKind as core::fmt::Debug>::fmt
            17: core::fmt::builders::DebugStruct::field::{{closure}}
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/builders.rs:141:17
            18: core::result::Result<T,E>::and_then
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1341:22
            19: core::fmt::builders::DebugStruct::field
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/builders.rs:124:23
            20: core::fmt::Formatter::debug_struct_field2_finish
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:2032:9
            21: <rustc_middle::mir::terminator::Terminator as core::fmt::Debug>::fmt
            22: core::fmt::write
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
            23: core::fmt::Write::write_fmt
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:197:9
            24: alloc::fmt::format::format_inner
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/fmt.rs:612:9
            25: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
            26: rustc_borrowck::nll::compute_regions
            27: rustc_borrowck::do_mir_borrowck
            28: rustc_borrowck::mir_borrowck
            29: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
            30: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
            31: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#2}>
            32: rustc_interface::passes::analysis
            33: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
            34: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            35: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            36: rustc_span::with_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
            37: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            38: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
            40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
            41: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
            42: <unknown>
            43: <unknown>


note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `mdbook`

Caused by:
  process didn't exit successfully: `rustc --crate-name mdbook --edition=2021 /home/hayesall/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-0.4.29/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=8f5092be63d1dbe6 -C extra-filename=-8f5092be63d1dbe6 --out-dir /tmp/cargo-install57aL4h/release/deps -L dependency=/tmp/cargo-install57aL4h/release/deps --extern anyhow=/tmp/cargo-install57aL4h/release/deps/libanyhow-8a64e709a9ea7090.rmeta --extern chrono=/tmp/cargo-install57aL4h/release/deps/libchrono-588ad35c78737617.rmeta --extern clap=/tmp/cargo-install57aL4h/release/deps/libclap-6df202431e9c25c2.rmeta --extern clap_complete=/tmp/cargo-install57aL4h/release/deps/libclap_complete-960a789b5642fc21.rmeta --extern env_logger=/tmp/cargo-install57aL4h/release/deps/libenv_logger-5574e727727fc3b9.rmeta --extern handlebars=/tmp/cargo-install57aL4h/release/deps/libhandlebars-a19349dd7ba5c803.rmeta --extern log=/tmp/cargo-install57aL4h/release/deps/liblog-1a300aa748007f13.rmeta --extern memchr=/tmp/cargo-install57aL4h/release/deps/libmemchr-f2862963475e2517.rmeta --extern once_cell=/tmp/cargo-install57aL4h/release/deps/libonce_cell-575c942fc25452c0.rmeta --extern opener=/tmp/cargo-install57aL4h/release/deps/libopener-f359d6dc2754235e.rmeta --extern pulldown_cmark=/tmp/cargo-install57aL4h/release/deps/libpulldown_cmark-8bcfadfd09d4bb03.rmeta --extern regex=/tmp/cargo-install57aL4h/release/deps/libregex-228633c49c71a421.rmeta --extern serde=/tmp/cargo-install57aL4h/release/deps/libserde-cbd258b7161bd8b7.rmeta --extern serde_json=/tmp/cargo-install57aL4h/release/deps/libserde_json-c187522d77f9924a.rmeta --extern shlex=/tmp/cargo-install57aL4h/release/deps/libshlex-80d763592c7de247.rmeta --extern tempfile=/tmp/cargo-install57aL4h/release/deps/libtempfile-db12b1083135c914.rmeta --extern toml=/tmp/cargo-install57aL4h/release/deps/libtoml-3f6c06ab359ed8da.rmeta --extern topological_sort=/tmp/cargo-install57aL4h/release/deps/libtopological_sort-f7a7581e9d3da237.rmeta --cap-lints allow` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mdbook-mermaid v0.12.6`, intermediate artifacts can be found at `/tmp/cargo-install57aL4h`
```

</p>
</details>

**Comment by saethlin** [comment]
My `rustc -vV` is the same as yours except outside WSL. I can't reproduce this on stable, beta, or nightly. _Maybe_ this depends on WSL? Or some other particular of your system?

I don't think https://github.com/rust-lang/rust/issues/111542 is related. That issue looks like flaky incremental compilation, and this does not.
