### ISSUE TITLE
ICE when compiling latest vello

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#111681]
### Code

Compile the [`vello` crate](https://github.com/linebender/vello).

### Meta

rustc 1.71.0-nightly (2f2c438dc 2023-05-08) running on x86_64-pc-windows-msvc
 - compiler flags: `--crate-type lib -C opt-level=3 -C linker-plugin-lto -C debuginfo=2`
 
The ICE does not occur on stable.

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (2f2c438dc 2023-05-08)
binary: rustc
commit-hash: 2f2c438dce75d8cc532c3baa849eeddc0901802c
commit-date: 2023-05-08
host: x86_64-pc-windows-msvc
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

<details><summary><strong>Output</strong></summary>

```
   Compiling wgpu v0.16.0
error: internal compiler error: compiler\rustc_monomorphize\src\collector.rs:1038:9: no MIR available for DefId(26:2800 ~ wgpu_core[3622]::track::buffer::{impl#0}::all_ordered)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\compiler\rustc_errors\src\lib.rs:1650:9
stack backtrace:
   0:     0x7ffb965361bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8451076aaccfa188
   1:     0x7ffb9656ee4b - core::fmt::write::hdd6f24e53a789517
   2:     0x7ffb9652b929 - <std::io::IoSlice as core::fmt::Debug>::fmt::h63656905d91555b2
   3:     0x7ffb96535f6b - std::sys::common::alloc::realloc_fallback::had3713156b5e8580
   4:     0x7ffb96539789 - std::panicking::default_hook::h1c43ff8622825dc1
   5:     0x7ffb9653943f - std::panicking::default_hook::h1c43ff8622825dc1
   6:     0x7ffb3cb6ced6 - rustc_driver_impl[7f3c104627fa441e]::install_ice_hook
   7:     0x7ffb96539e8b - std::panicking::rust_panic_with_hook::h9b07ff91ec3c29ef
   8:     0x7ffb3f015863 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
   9:     0x7ffb3f013f39 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
  10:     0x7ffb3effa6f9 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  11:     0x7ffb3eff7c00 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  12:     0x7ffb3eff77bc - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  13:     0x7ffb3f048c0d - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  14:     0x7ffb3f0481cd - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  15:     0x7ffb3f04818f - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  16:     0x7ffb3f048aff - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  17:     0x7ffb3be7717e - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_constant
  18:     0x7ffb3be6e0be - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  19:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  20:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  21:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  22:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  23:     0x7ffb3ab23ca9 - <rustc_hir_analysis[7f73c40221c0f21]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[647a106ea611c02d]::intravisit::Visitor>::visit_trait_item
  24:     0x7ffb3ab2a0bf - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  25:     0x7ffb3ab26971 - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  26:     0x7ffb3ae95a4e - <rustc_query_impl[786100d8525dfa7a]::queries::exported_symbols as rustc_query_system[ad82e17e51696613]::query::config::QueryConfig<rustc_query_impl[786100d8525dfa7a]::plumbing::QueryCtxt>>::execute_query
  27:     0x7ffb3ad62b86 - rustc_query_impl[786100d8525dfa7a]::query_system_fns
  28:     0x7ffb3a3ba370 - <rustc_codegen_llvm[372e2bf8ffdd465d]::builder::Builder as rustc_codegen_ssa[68920ad53f7650c2]::traits::builder::BuilderMethods>::unchecked_umul
  29:     0x7ffb3a3b02c0 - <rustc_codegen_llvm[372e2bf8ffdd465d]::LlvmCodegenBackend as rustc_codegen_ssa[68920ad53f7650c2]::traits::backend::CodegenBackend>::codegen_crate
  30:     0x7ffb3a38ad67 - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  31:     0x7ffb3a389f9a - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  32:     0x7ffb3a36e639 - rustc_log[62b31320fd9c4bf3]::init_env_logger
  33:     0x7ffb3a37ea45 - <rustc_interface[2dabe0186cf74270]::queries::Queries>::ongoing_codegen
  34:     0x7ffb3a33a0ba - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  35:     0x7ffb3a358e73 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  36:     0x7ffb3a35a2c6 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  37:     0x7ffb9654cfdc - std::sys::windows::thread::Thread::new::h92dca72e27387ad0
  38:     0x7ffbd79a26ad - BaseThreadInitThunk
  39:     0x7ffbd812a9f8 - RtlUserThreadStart

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f2c438dc 2023-05-08) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: compiler\rustc_monomorphize\src\collector.rs:1038:9: no MIR available for DefId(26:3016 ~ wgpu_core[3622]::track::texture::{impl#0}::all_ordered)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\compiler\rustc_errors\src\lib.rs:1650:9
stack backtrace:
   0:     0x7ffb965361bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8451076aaccfa188
   1:     0x7ffb9656ee4b - core::fmt::write::hdd6f24e53a789517
   2:     0x7ffb9652b929 - <std::io::IoSlice as core::fmt::Debug>::fmt::h63656905d91555b2
   3:     0x7ffb96535f6b - std::sys::common::alloc::realloc_fallback::had3713156b5e8580
   4:     0x7ffb96539789 - std::panicking::default_hook::h1c43ff8622825dc1
   5:     0x7ffb9653943f - std::panicking::default_hook::h1c43ff8622825dc1
   6:     0x7ffb3cb6ced6 - rustc_driver_impl[7f3c104627fa441e]::install_ice_hook
   7:     0x7ffb96539e8b - std::panicking::rust_panic_with_hook::h9b07ff91ec3c29ef
   8:     0x7ffb3f015863 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
   9:     0x7ffb3f013f39 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
  10:     0x7ffb3effa6f9 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  11:     0x7ffb3eff7c00 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  12:     0x7ffb3eff77bc - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  13:     0x7ffb3f048c0d - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  14:     0x7ffb3f0481cd - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  15:     0x7ffb3f04818f - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  16:     0x7ffb3f048aff - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  17:     0x7ffb3be7717e - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_constant
  18:     0x7ffb3be6e0be - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  19:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  20:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  21:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  22:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  23:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  24:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  25:     0x7ffb3ab23ca9 - <rustc_hir_analysis[7f73c40221c0f21]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[647a106ea611c02d]::intravisit::Visitor>::visit_trait_item
  26:     0x7ffb3ab2a0bf - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  27:     0x7ffb3ab26971 - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  28:     0x7ffb3ae95a4e - <rustc_query_impl[786100d8525dfa7a]::queries::exported_symbols as rustc_query_system[ad82e17e51696613]::query::config::QueryConfig<rustc_query_impl[786100d8525dfa7a]::plumbing::QueryCtxt>>::execute_query
  29:     0x7ffb3ad62b86 - rustc_query_impl[786100d8525dfa7a]::query_system_fns
  30:     0x7ffb3a3ba370 - <rustc_codegen_llvm[372e2bf8ffdd465d]::builder::Builder as rustc_codegen_ssa[68920ad53f7650c2]::traits::builder::BuilderMethods>::unchecked_umul
  31:     0x7ffb3a3b02c0 - <rustc_codegen_llvm[372e2bf8ffdd465d]::LlvmCodegenBackend as rustc_codegen_ssa[68920ad53f7650c2]::traits::backend::CodegenBackend>::codegen_crate
  32:     0x7ffb3a38ad67 - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  33:     0x7ffb3a389f9a - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  34:     0x7ffb3a36e639 - rustc_log[62b31320fd9c4bf3]::init_env_logger
  35:     0x7ffb3a37ea45 - <rustc_interface[2dabe0186cf74270]::queries::Queries>::ongoing_codegen
  36:     0x7ffb3a33a0ba - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  37:     0x7ffb3a358e73 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  38:     0x7ffb3a35a2c6 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  39:     0x7ffb9654cfdc - std::sys::windows::thread::Thread::new::h92dca72e27387ad0
  40:     0x7ffbd79a26ad - BaseThreadInitThunk
  41:     0x7ffbd812a9f8 - RtlUserThreadStart

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f2c438dc 2023-05-08) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: compiler\rustc_monomorphize\src\collector.rs:1038:9: no MIR available for DefId(26:2801 ~ wgpu_core[3622]::track::buffer::{impl#0}::any_exclusive)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\compiler\rustc_errors\src\lib.rs:1650:9
stack backtrace:
   0:     0x7ffb965361bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8451076aaccfa188
   1:     0x7ffb9656ee4b - core::fmt::write::hdd6f24e53a789517
   2:     0x7ffb9652b929 - <std::io::IoSlice as core::fmt::Debug>::fmt::h63656905d91555b2
   3:     0x7ffb96535f6b - std::sys::common::alloc::realloc_fallback::had3713156b5e8580
   4:     0x7ffb96539789 - std::panicking::default_hook::h1c43ff8622825dc1
   5:     0x7ffb9653943f - std::panicking::default_hook::h1c43ff8622825dc1
   6:     0x7ffb3cb6ced6 - rustc_driver_impl[7f3c104627fa441e]::install_ice_hook
   7:     0x7ffb96539e8b - std::panicking::rust_panic_with_hook::h9b07ff91ec3c29ef
   8:     0x7ffb3f015863 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
   9:     0x7ffb3f013f39 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
  10:     0x7ffb3effa6f9 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  11:     0x7ffb3eff7c00 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  12:     0x7ffb3eff77bc - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  13:     0x7ffb3f048c0d - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  14:     0x7ffb3f0481cd - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  15:     0x7ffb3f04818f - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  16:     0x7ffb3f048aff - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  17:     0x7ffb3be7717e - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_constant
  18:     0x7ffb3be6e0be - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  19:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  20:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  21:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  22:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  23:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  24:     0x7ffb3ab23ca9 - <rustc_hir_analysis[7f73c40221c0f21]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[647a106ea611c02d]::intravisit::Visitor>::visit_trait_item
  25:     0x7ffb3ab2a0bf - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  26:     0x7ffb3ab26971 - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  27:     0x7ffb3ae95a4e - <rustc_query_impl[786100d8525dfa7a]::queries::exported_symbols as rustc_query_system[ad82e17e51696613]::query::config::QueryConfig<rustc_query_impl[786100d8525dfa7a]::plumbing::QueryCtxt>>::execute_query
  28:     0x7ffb3ad62b86 - rustc_query_impl[786100d8525dfa7a]::query_system_fns
  29:     0x7ffb3a3ba370 - <rustc_codegen_llvm[372e2bf8ffdd465d]::builder::Builder as rustc_codegen_ssa[68920ad53f7650c2]::traits::builder::BuilderMethods>::unchecked_umul
  30:     0x7ffb3a3b02c0 - <rustc_codegen_llvm[372e2bf8ffdd465d]::LlvmCodegenBackend as rustc_codegen_ssa[68920ad53f7650c2]::traits::backend::CodegenBackend>::codegen_crate
  31:     0x7ffb3a38ad67 - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  32:     0x7ffb3a389f9a - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  33:     0x7ffb3a36e639 - rustc_log[62b31320fd9c4bf3]::init_env_logger
  34:     0x7ffb3a37ea45 - <rustc_interface[2dabe0186cf74270]::queries::Queries>::ongoing_codegen
  35:     0x7ffb3a33a0ba - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  36:     0x7ffb3a358e73 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  37:     0x7ffb3a35a2c6 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  38:     0x7ffb9654cfdc - std::sys::windows::thread::Thread::new::h92dca72e27387ad0
  39:     0x7ffbd79a26ad - BaseThreadInitThunk
  40:     0x7ffbd812a9f8 - RtlUserThreadStart

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f2c438dc 2023-05-08) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: compiler\rustc_monomorphize\src\collector.rs:1038:9: no MIR available for DefId(26:3017 ~ wgpu_core[3622]::track::texture::{impl#0}::any_exclusive)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\compiler\rustc_errors\src\lib.rs:1650:9
stack backtrace:
   0:     0x7ffb965361bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8451076aaccfa188
   1:     0x7ffb9656ee4b - core::fmt::write::hdd6f24e53a789517
   2:     0x7ffb9652b929 - <std::io::IoSlice as core::fmt::Debug>::fmt::h63656905d91555b2
   3:     0x7ffb96535f6b - std::sys::common::alloc::realloc_fallback::had3713156b5e8580
   4:     0x7ffb96539789 - std::panicking::default_hook::h1c43ff8622825dc1
   5:     0x7ffb9653943f - std::panicking::default_hook::h1c43ff8622825dc1
   6:     0x7ffb3cb6ced6 - rustc_driver_impl[7f3c104627fa441e]::install_ice_hook
   7:     0x7ffb96539e8b - std::panicking::rust_panic_with_hook::h9b07ff91ec3c29ef
   8:     0x7ffb3f015863 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
   9:     0x7ffb3f013f39 - <rustc_middle[573f4af23501b094]::ty::subst::UserSubsts as rustc_middle[573f4af23501b094]::ty::context::Lift>::lift_to_tcx
  10:     0x7ffb3effa6f9 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  11:     0x7ffb3eff7c00 - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  12:     0x7ffb3eff77bc - <rustc_middle[573f4af23501b094]::ty::subst::GenericArg as rustc_infer[36b08ec0da630c04]::infer::at::ToTrace>::to_trace
  13:     0x7ffb3f048c0d - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  14:     0x7ffb3f0481cd - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  15:     0x7ffb3f04818f - <rustc_middle[573f4af23501b094]::ty::consts::valtree::ValTree>::try_to_raw_bytes
  16:     0x7ffb3f048aff - rustc_middle[573f4af23501b094]::util::bug::bug_fmt
  17:     0x7ffb3be7717e - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_constant
  18:     0x7ffb3be6e0be - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  19:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  20:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  21:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  22:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  23:     0x7ffb3be6e49d - <rustc_monomorphize[fa77b408cb234aba]::collector::MirNeighborCollector as rustc_middle[573f4af23501b094]::mir::visit::Visitor>::visit_operand
  24:     0x7ffb3ab23ca9 - <rustc_hir_analysis[7f73c40221c0f21]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[647a106ea611c02d]::intravisit::Visitor>::visit_trait_item
  25:     0x7ffb3ab2a0bf - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  26:     0x7ffb3ab26971 - <rustc_monomorphize[fa77b408cb234aba]::partitioning::default::DefaultPartitioning as rustc_monomorphize[fa77b408cb234aba]::partitioning::Partition>::merge_codegen_units
  27:     0x7ffb3ae95a4e - <rustc_query_impl[786100d8525dfa7a]::queries::exported_symbols as rustc_query_system[ad82e17e51696613]::query::config::QueryConfig<rustc_query_impl[786100d8525dfa7a]::plumbing::QueryCtxt>>::execute_query
  28:     0x7ffb3ad62b86 - rustc_query_impl[786100d8525dfa7a]::query_system_fns
  29:     0x7ffb3a3ba370 - <rustc_codegen_llvm[372e2bf8ffdd465d]::builder::Builder as rustc_codegen_ssa[68920ad53f7650c2]::traits::builder::BuilderMethods>::unchecked_umul
  30:     0x7ffb3a3b02c0 - <rustc_codegen_llvm[372e2bf8ffdd465d]::LlvmCodegenBackend as rustc_codegen_ssa[68920ad53f7650c2]::traits::backend::CodegenBackend>::codegen_crate
  31:     0x7ffb3a38ad67 - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  32:     0x7ffb3a389f9a - rustc_interface[2dabe0186cf74270]::passes::start_codegen
  33:     0x7ffb3a36e639 - rustc_log[62b31320fd9c4bf3]::init_env_logger
  34:     0x7ffb3a37ea45 - <rustc_interface[2dabe0186cf74270]::queries::Queries>::ongoing_codegen
  35:     0x7ffb3a33a0ba - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  36:     0x7ffb3a358e73 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  37:     0x7ffb3a35a2c6 - rustc_driver_impl[7f3c104627fa441e]::args::arg_expand_all
  38:     0x7ffb9654cfdc - std::sys::windows::thread::Thread::new::h92dca72e27387ad0
  39:     0x7ffbd79a26ad - BaseThreadInitThunk
  40:     0x7ffbd812a9f8 - RtlUserThreadStart

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f2c438dc 2023-05-08) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `wgpu` (lib)
```

</details>

**Comment by derekdreery** [comment]
Seems to be fixed with latest nightly. Apologies I thought I was using a later one. 😸
