### ISSUE TITLE
Compile error with 1.70.0 - … InstrProfilingRuntime.cpp: C++ compiler not installed on this system

### ISSUE THREAD

**Issue by heitbaum** [rust-lang/rust#112262]
When compiling rust the following compile failure occurs. Compile of 1.69.0 was fine.

```

     Running `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/release/build/std-a0649b744850bb4d/build-script-build`
The following warnings were emitted during compilation:

warning: x86_64-libreelec-linux-gnu-gcc-12.2.0: error: ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingRuntime.cpp: C++ compiler not installed on this system

error: failed to run custom build command for `profiler_builtins v0.0.0 (/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/library/profiler_builtins)`

Caused by:
  process didn't exit successfully: `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/release/build/profiler_builtins-de071c1b82b3d16d/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-libreelec-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-libreelec-linux-gnu
  CC_x86_64-libreelec-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_libreelec_linux_gnu
  CC_x86_64_libreelec_linux_gnu = Some("/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-libreelec-linux-gnu
  CFLAGS_x86_64-libreelec-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_libreelec_linux_gnu
  CFLAGS_x86_64_libreelec_linux_gnu = Some("-ffunction-sections -fdata-sections -fPIC -m64")
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/GCDAProfiling.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/GCDAProfiling.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfiling.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfiling.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingBuffer.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingBuffer.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingMerge.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingMerge.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingMergeFile.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingMergeFile.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingNameVar.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingNameVar.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformDarwin.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformDarwin.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformFuchsia.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformFuchsia.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformLinux.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformLinux.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformOther.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformOther.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformWindows.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingPlatformWindows.c"
  exit status: 0
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingRuntime.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingRuntime.cpp"
  cargo:warning=x86_64-libreelec-linux-gnu-gcc-12.2.0: error: ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingRuntime.cpp: C++ compiler not installed on this system
  exit status: 1

  --- stderr


  error occurred: Command "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "../../src/llvm-project/compiler-rt/include" "-fno-builtin" "-fomit-frame-pointer" "-fvisibility=hidden" "-DVISIBILITY_HIDDEN" "-DCOMPILER_RT_HAS_UNAME=1" "-DCOMPILER_RT_HAS_FCNTL_LCK=1" "-DCOMPILER_RT_HAS_ATOMICS=1" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-libreelec-linux-gnu/release/build/profiler_builtins-c5eabb970eb2a4ca/out/../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingRuntime.o" "-c" "../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingRuntime.cpp" with args "x86_64-libreelec-linux-gnu-gcc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
command did not execute successfully: cd "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0" && AR_x86_64_libreelec_linux_gnu="ar" CARGO_INCREMENTAL="0" CARGO_PROFILE_RELEASE_DEBUG="0" CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS="false" CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS="false" CARGO_TARGET_DIR="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2-std" CARGO_TARGET_X86_64_LIBREELEC_LINUX_GNU_LINKER="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" CC_x86_64_libreelec_linux_gnu="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-gcc" CFG_COMPILER_HOST_TRIPLE="x86_64-libreelec-linux-gnu" CFG_DISABLE_UNSTABLE_FEATURES="1" CFG_RELEASE_CHANNEL="stable" CFLAGS_x86_64_libreelec_linux_gnu="-ffunction-sections -fdata-sections -fPIC -m64" CXXFLAGS_x86_64_libreelec_linux_gnu="-ffunction-sections -fdata-sections -fPIC -m64" CXX_x86_64_libreelec_linux_gnu="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++" LIBC_CHECK_CFG="1" RANLIB_x86_64_libreelec_linux_gnu="ar s" REAL_LIBRARY_PATH_VAR="LD_LIBRARY_PATH" RUSTBUILD_NATIVE_DIR="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-libreelec-linux-gnu/native" RUSTC="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc" RUSTC_BOOTSTRAP="1" RUSTC_BREAK_ON_ICE="1" RUSTC_ERROR_METADATA_DST="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/tmp/extended-error-metadata" RUSTC_FORCE_UNSTABLE="1" RUSTC_INSTALL_BINDIR="bin" RUSTC_LIBDIR="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2/lib" RUSTC_LINT_FLAGS="-Wrust_2018_idioms -Wunused_lifetimes -Wsemicolon_in_expressions_from_macros -Dwarnings" RUSTC_REAL="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUSTC_SNAPSHOT="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/rust-snapshot/bin/rustc" RUSTC_SNAPSHOT_LIBDIR="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/rust-snapshot/lib" RUSTC_STAGE="2" RUSTC_SYSROOT="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/x86_64-unknown-linux-gnu/stage2" RUSTC_VERBOSE="1" RUSTDOC="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustdoc" RUSTDOCFLAGS="-Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options --check-cfg=values(bootstrap) --check-cfg=values(stdarch_intel_sde) --check-cfg=values(no_fp_fmt_parse) --check-cfg=values(no_global_oom_handling) --check-cfg=values(no_rc) --check-cfg=values(no_sync) --check-cfg=values(freebsd12) --check-cfg=values(freebsd13) --check-cfg=values(backtrace_in_libstd) --check-cfg=values(target_env,\"libnx\") --check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\") --check-cfg=values(target_env,\"ohos\") -Dwarnings -Wrustdoc::invalid_codeblock_attributes --crate-version 1.70.0\n(90c541806\n2023-05-31)\n(built\nfrom\na\nsource\ntarball) -Zcrate-attr=doc(html_root_url=\"https://doc.rust-lang.org/1.70.0/\")" RUSTDOC_REAL="/path/to/nowhere/rustdoc/not/required" RUSTFLAGS="-Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options --check-cfg=values(bootstrap) --check-cfg=values(stdarch_intel_sde) --check-cfg=values(no_fp_fmt_parse) --check-cfg=values(no_global_oom_handling) --check-cfg=values(no_rc) --check-cfg=values(no_sync) --check-cfg=values(freebsd12) --check-cfg=values(freebsd13) --check-cfg=values(backtrace_in_libstd) --check-cfg=values(target_env,\"libnx\") --check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\") --check-cfg=values(target_env,\"ohos\") -Zmacro-backtrace -Clink-args=-Wl,-z,origin -Clink-args=-Wl,-rpath,$ORIGIN/../lib -Csplit-debuginfo=off -Cprefer-dynamic -Zinline-mir -Cembed-bitcode=yes -Zcrate-attr=doc(html_root_url=\"https://doc.rust-lang.org/1.70.0/\")" RUST_COMPILER_RT_ROOT="/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/src/llvm-project/compiler-rt" RUST_TEST_THREADS="16" WINAPI_NO_BUNDLED_LIBRARIES="1" __CARGO_DEFAULT_LIB_METADATA="stablestd" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/rust-snapshot/bin/cargo" "build" "--target" "x86_64-libreelec-linux-gnu" "--release" "-Zcheck-cfg=names,values,output" "-Zbinary-dep-depinfo" "-j" "16" "-v" "--frozen" "--features" " panic-unwind backtrace profiler compiler-builtins-c" "--manifest-path" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit status: 101
Traceback (most recent call last):
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 965, in <module>
    main()
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 950, in main
    bootstrap(args)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 925, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 167, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/bootstrap -j 16 build --stage 2 --verbose
```

**Comment by heitbaum** [comment]
On full clean build environment, unable to reproduce. Closing for the time being.
