### ISSUE TITLE
A thread_local! with a const initializer and a panicking drop impl unwinds through an extern "C" frame

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#112285]
Miri detects UB when running the following program:
```rust
pub struct NoisyDrop {}

impl Drop for NoisyDrop {
    fn drop(&mut self) {
        panic!("ow");
    }
}

thread_local! {
    pub static NOISY: NoisyDrop = const { NoisyDrop {} };
}

fn main() {
    NOISY.with(|_| ());
}
```

With `--target=x86_64-unknown-linux-gnu` and `--target=aarch64-apple-darwin`
```
thread '<unnamed>' panicked at 'ow', src/main.rs:5:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Undefined Behavior: unwinding past a stack frame that does not allow unwinding
  --> /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/thread_local_dtor.rs:43:17
   |
43 |                 dtor(ptr);
   |                 ^^^^^^^^^ unwinding past a stack frame that does not allow unwinding
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `std::sys_common::thread_local_dtor::register_dtor_fallback::run_dtors` at /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/thread_local_dtor.rs:43:17: 43:26
```
With `--target=x86_64-pc-windows-msvc`
```
thread 'main' panicked at 'ow', src/main.rs:5:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Undefined Behavior: unwinding past a stack frame that does not allow unwinding
  --> /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/windows/thread_local_dtor.rs:28:9
   |
28 |         (dtor)(ptr);
   |         ^^^^^^^^^^^ unwinding past a stack frame that does not allow unwinding
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `std::sys::windows::thread_local_dtor::run_keyless_dtors` at /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/windows/thread_local_dtor.rs:28:9: 28:20
   = note: inside `std::sys::windows::thread_local_key::on_tls_callback` at /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/windows/thread_local_key.rs:246:9: 246:54
```

**Comment by thomcc** [comment]
I see the bug. We have `#![feature(c_unwind)]` (which means `extern "C"` fns in std automatically trap aborts) but that doesn't apply to `extern "C"` functions which are present in the macro expansion (some of which can't really be moved outside the macro).

Ill fix in like an hour or two. We just need to guard panics in a couple places.

In practice I *think* this should not call problems and we'd just hit an abort guard in an `extern "C"` defined in `libstd` a few frames up, although perhaps that's not true in 100% of cases (I can update on this once I implement the fix).

**Comment by workingjubilee** [comment]
The [apparent consensus](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23112285.20A.20thread_local!.20with.20a.20const.20initializer.20and.20a.20pani.E2.80.A6) is that the fix to this may need to be backported thus I am tagging this with P-high.
