### ISSUE TITLE
ICE while running cargo check

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/rust#112408]
### Code

I don't have a minimized example, but hopefully the error output is useful anyways.

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: aarch64-apple-darwin
release: 1.70.0
LLVM version: 16.0.2
```

### Error output

```
warning: unused import: `BorshSerialize`
 --> crates/storage/src/snapshot.rs:5:31
  |
5 | use borsh::{BorshDeserialize, BorshSerialize};
  |                               ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `penumbra-storage` (lib) generated 1 warning (run `cargo fix --lib -p penumbra-storage` to apply 1 suggestion)
   Compiling penumbra-proto v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/proto)
   Compiling libgit2-sys v0.15.2+1.6.4
   Compiling doc-comment v0.3.3
   Compiling sysinfo v0.19.2
   Compiling git2 v0.17.2
   Compiling vergen v5.1.17
   Compiling penumbra-view v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/view)
   Compiling penumbra-custody v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/custody)
   Compiling narsil v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/narsil/narsil)
   Compiling pclientd v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/bin/pclientd)
   Compiling pd v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/bin/pd)
   Compiling penumbra-measure v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/misc/measure)
   Compiling pcli v0.53.1 (/Users/hdevalence/code/penumbra/penumbra/crates/bin/pcli)
error: internal compiler error: encountered incremental compilation error with mir_built(f7163643bf0de50a-a0dadd6ab59e21c6)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p penumbra_proto` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for mir_built(f7163643bf0de50a-a0dadd6ab59e21c6): Steal { value: RwLock(RefCell { value: Some(Body { basic_blocks: BasicBlocks { basic_blocks: [BasicBlockData { statements: [StorageLive(_3), StorageLive(_4), StorageLive(_5), _5 = move (_1.1: penumbra::core::dex::v1alpha1::Swap), _4 = action::Action::Swap(move _5)], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_5) -> [return: bb1, unwind: bb8] }), is_cleanup: false }, BasicBlockData { statements: [StorageDead(_5), _3 = std::option::Option::<action::Action>::Some(move _4)], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_4) -> [return: bb2, unwind: bb7] }), is_cleanup: false }, BasicBlockData { statements: [StorageDead(_4)], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#17167), scope: scope[0] }, kind: drop((*(_1.0: &mut std::option::Option<penumbra::core::transaction::v1alpha1::action::Action>))) -> [return: bb3, unwind: bb4] }), is_cleanup: false }, BasicBlockData { statements: [(*(_1.0: &mut std::option::Option<penumbra::core::transaction::v1alpha1::action::Action>)) = move _3, _0 = const ()], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_3) -> [return: bb5, unwind: bb9] }), is_cleanup: false }, BasicBlockData { statements: [(*(_1.0: &mut std::option::Option<penumbra::core::transaction::v1alpha1::action::Action>)) = move _3], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#17167), scope: scope[0] }, kind: goto -> bb7 }), is_cleanup: true }, BasicBlockData { statements: [StorageDead(_3)], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_1) -> [return: bb6, unwind: bb10] }), is_cleanup: false }, BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:46: 68:46 (#2235), scope: scope[0] }, kind: return }), is_cleanup: false }, BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_3) -> [return: bb9, unwind terminate] }), is_cleanup: true }, BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_4) -> [return: bb9, unwind terminate] }), is_cleanup: true }, BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:45: 68:46 (#2235), scope: scope[0] }, kind: drop(_1) -> [return: bb10, unwind terminate] }), is_cleanup: true }, BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), scope: scope[0] }, kind: resume }), is_cleanup: true }], cache: Cache { predecessors: OnceCell(Uninit), switch_sources: OnceCell(Uninit), is_cyclic: OnceCell(Uninit), postorder: OnceCell(Uninit) } }, phase: Built, pass_count: 0, source: MirSource { instance: Item(WithOptConstParam { did: DefId(0:8603 ~ penumbra_proto[e35f]::penumbra::core::transaction::v1alpha1::action::{impl#3}::merge::{closure#2}), const_param_did: None }), promoted: None }, source_scopes: [SourceScopeData { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), parent_scope: None, inlined: None, inlined_parent_scope: None, local_data: Set(SourceScopeLocalData { lint_root: HirId(DefId(0:8599 ~ penumbra_proto[e35f]::penumbra::core::transaction::v1alpha1::action::{impl#3}::merge).273), safety: Safe }) }], generator: None, local_decls: [LocalDecl { mutability: Mut, local_info: Set(Boring), internal: false, ty: (), user_ty: None, source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:32 (#2235), scope: scope[0] } }, LocalDecl { mutability: Mut, local_info: Set(Boring), internal: false, ty: [closure@crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46], user_ty: None, source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), scope: scope[0] } }, LocalDecl { mutability: Mut, local_info: Set(Boring), internal: false, ty: (), user_ty: None, source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), scope: scope[0] } }, LocalDecl { mutability: Mut, local_info: Set(Boring), internal: false, ty: std::option::Option<penumbra::core::transaction::v1alpha1::action::Action>, user_ty: None, source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), scope: scope[0] } }, LocalDecl { mutability: Mut, local_info: Set(AggregateTemp), internal: false, ty: penumbra::core::transaction::v1alpha1::action::Action, user_ty: None, source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), scope: scope[0] } }, LocalDecl { mutability: Mut, local_info: Set(AggregateTemp), internal: false, ty: penumbra::core::dex::v1alpha1::Swap, user_ty: None, source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), scope: scope[0] } }], user_type_annotations: [], arg_count: 2, spread_arg: None, var_debug_info: [VarDebugInfo { name: "field", source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#15841), scope: scope[0] }, value: (*(_1.0: &mut std::option::Option<penumbra::core::transaction::v1alpha1::action::Action>)), argument_index: None }, VarDebugInfo { name: "owned_value", source_info: SourceInfo { span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#15841), scope: scope[0] }, value: (_1.1: penumbra::core::dex::v1alpha1::Swap), argument_index: None }], span: crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46 (#2235), required_consts: [], is_polymorphic: true, injection_phase: None, tainted_by_errors: None }) }) }', /rustc/90c541806f23a127002de5b4038be731ba1458ca/compiler/rustc_query_system/src/query/plumbing.rs:715:9
stack backtrace:
   0:        0x103241864 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h819e9cbdf1a9e730
   1:        0x103294958 - core::fmt::write::ha5e9bf3131ecb7c0
   2:        0x103237214 - std::io::Write::write_fmt::h414ce9994bf17404
   3:        0x103241678 - std::sys_common::backtrace::print::h8072db0bbd5bcc3d
   4:        0x10324408c - std::panicking::default_hook::{{closure}}::h2c85c5b0c2ede151
   5:        0x103243e4c - std::panicking::default_hook::hcf2f70992d02f6fe
   6:        0x10b73c058 - rustc_driver_impl[783dc85a9905d0e5]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x10324474c - std::panicking::rust_panic_with_hook::h023af7f90b47eb8b
   8:        0x103244544 - std::panicking::begin_panic_handler::{{closure}}::h14283519edc1d634
   9:        0x103241c84 - std::sys_common::backtrace::__rust_end_short_backtrace::hc366c0b0cef5b747
  10:        0x1032442d8 - _rust_begin_unwind
  11:        0x1032c0400 - core::panicking::panic_fmt::h324f50b29db90195
  12:        0x10faa6d68 - rustc_query_system[a624e6a9fe4584df]::query::plumbing::incremental_verify_ich_failed::<rustc_middle[51dfd5d9279e1028]::ty::context::TyCtxt>
  13:        0x10ea13a48 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<rustc_query_system[a624e6a9fe4584df]::query::plumbing::execute_job_incr<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_built, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>::{closure#1}, core[b2c7346eda96f041]::option::Option<(rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core[b2c7346eda96f041]::option::Option<(rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>>
  14:        0x10e91870c - rustc_query_system[a624e6a9fe4584df]::query::plumbing::try_execute_query::<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_built, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>
  15:        0x10eb0acec - <rustc_query_impl[7b60fd99fe06ff81]::Queries as rustc_middle[51dfd5d9279e1028]::ty::query::QueryEngine>::mir_built
  16:        0x10df20b9c - rustc_mir_transform[9e4a16c1f6c5c5f7]::mir_const
  17:        0x10ea140e8 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<rustc_query_system[a624e6a9fe4584df]::query::plumbing::execute_job_incr<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_const, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>::{closure#1}, core[b2c7346eda96f041]::option::Option<(rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core[b2c7346eda96f041]::option::Option<(rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>>
  18:        0x10e918de8 - rustc_query_system[a624e6a9fe4584df]::query::plumbing::try_execute_query::<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_const, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>
  19:        0x10eb0aeac - <rustc_query_impl[7b60fd99fe06ff81]::Queries as rustc_middle[51dfd5d9279e1028]::ty::query::QueryEngine>::mir_const
  20:        0x10df21250 - rustc_mir_transform[9e4a16c1f6c5c5f7]::mir_promoted
  21:        0x10e980ab8 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<rustc_query_system[a624e6a9fe4584df]::query::plumbing::execute_job_incr<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_promoted, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>::{closure#1}, core[b2c7346eda96f041]::option::Option<(rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core[b2c7346eda96f041]::option::Option<(rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 16usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>>
  22:        0x10e8a1320 - rustc_query_system[a624e6a9fe4584df]::query::plumbing::try_execute_query::<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_promoted, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>
  23:        0x10eb0b940 - <rustc_query_impl[7b60fd99fe06ff81]::Queries as rustc_middle[51dfd5d9279e1028]::ty::query::QueryEngine>::mir_promoted
  24:        0x10e444e78 - rustc_borrowck[3cbad71922bf7c4a]::mir_borrowck
  25:        0x10e429388 - <rustc_borrowck[3cbad71922bf7c4a]::provide::{closure#0} as core[b2c7346eda96f041]::ops::function::FnOnce<(rustc_middle[51dfd5d9279e1028]::ty::context::TyCtxt, rustc_span[350718d478b9eefa]::def_id::LocalDefId)>>::call_once
  26:        0x10e97ee68 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<rustc_query_system[a624e6a9fe4584df]::query::plumbing::execute_job_incr<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_borrowck, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>
  27:        0x10e8a0698 - rustc_query_system[a624e6a9fe4584df]::query::plumbing::try_execute_query::<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_borrowck, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>
  28:        0x10eb13018 - <rustc_query_impl[7b60fd99fe06ff81]::Queries as rustc_middle[51dfd5d9279e1028]::ty::query::QueryEngine>::mir_borrowck
  29:        0x10e509934 - <rustc_borrowck[3cbad71922bf7c4a]::type_check::TypeChecker>::prove_closure_bounds
  30:        0x10e50d810 - <rustc_borrowck[3cbad71922bf7c4a]::type_check::TypeChecker>::check_rvalue
  31:        0x10e510e34 - <rustc_borrowck[3cbad71922bf7c4a]::type_check::TypeChecker>::typeck_mir
  32:        0x10e5016c8 - rustc_borrowck[3cbad71922bf7c4a]::nll::compute_regions
  33:        0x10e44db10 - rustc_borrowck[3cbad71922bf7c4a]::do_mir_borrowck
  34:        0x10e444f90 - rustc_borrowck[3cbad71922bf7c4a]::mir_borrowck
  35:        0x10e429388 - <rustc_borrowck[3cbad71922bf7c4a]::provide::{closure#0} as core[b2c7346eda96f041]::ops::function::FnOnce<(rustc_middle[51dfd5d9279e1028]::ty::context::TyCtxt, rustc_span[350718d478b9eefa]::def_id::LocalDefId)>>::call_once
  36:        0x10e97ee68 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<rustc_query_system[a624e6a9fe4584df]::query::plumbing::execute_job_incr<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_borrowck, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>
  37:        0x10e8a0698 - rustc_query_system[a624e6a9fe4584df]::query::plumbing::try_execute_query::<rustc_query_impl[7b60fd99fe06ff81]::queries::mir_borrowck, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>
  38:        0x10eb13018 - <rustc_query_impl[7b60fd99fe06ff81]::Queries as rustc_middle[51dfd5d9279e1028]::ty::query::QueryEngine>::mir_borrowck
  39:        0x10b7fbaa4 - <core[b2c7346eda96f041]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[b0ef732b28d74439]::sync::par_for_each_in<&[rustc_span[350718d478b9eefa]::def_id::LocalDefId], <rustc_middle[51dfd5d9279e1028]::hir::map::Map>::par_body_owners<rustc_interface[86097f894d44157]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core[b2c7346eda96f041]::ops::function::FnOnce<()>>::call_once
  40:        0x10b7db160 - rustc_data_structures[b0ef732b28d74439]::sync::par_for_each_in::<&[rustc_span[350718d478b9eefa]::def_id::LocalDefId], <rustc_middle[51dfd5d9279e1028]::hir::map::Map>::par_body_owners<rustc_interface[86097f894d44157]::passes::analysis::{closure#2}::{closure#0}>::{closure#0}>
  41:        0x10b7e2e04 - <rustc_session[fcd7c20a0454c43b]::session::Session>::time::<(), rustc_interface[86097f894d44157]::passes::analysis::{closure#2}>
  42:        0x10b85650c - rustc_interface[86097f894d44157]::passes::analysis
  43:        0x10ea0d1c8 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<rustc_query_system[a624e6a9fe4584df]::query::plumbing::execute_job_incr<rustc_query_impl[7b60fd99fe06ff81]::queries::analysis, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>::{closure#2}, (rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle[51dfd5d9279e1028]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[a624e6a9fe4584df]::dep_graph::graph::DepNodeIndex)>
  44:        0x10e913298 - rustc_query_system[a624e6a9fe4584df]::query::plumbing::try_execute_query::<rustc_query_impl[7b60fd99fe06ff81]::queries::analysis, rustc_query_impl[7b60fd99fe06ff81]::plumbing::QueryCtxt>
  45:        0x10eb08998 - <rustc_query_impl[7b60fd99fe06ff81]::Queries as rustc_middle[51dfd5d9279e1028]::ty::query::QueryEngine>::analysis
  46:        0x10b784c28 - <std[bf9110f564f42f12]::thread::local::LocalKey<core[b2c7346eda96f041]::cell::Cell<*const ()>>>::with::<rustc_middle[51dfd5d9279e1028]::ty::context::tls::enter_context<<rustc_middle[51dfd5d9279e1028]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[783dc85a9905d0e5]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>::{closure#0}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>::{closure#0}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>
  47:        0x10b7505d4 - <rustc_interface[86097f894d44157]::queries::QueryResult<&rustc_middle[51dfd5d9279e1028]::ty::context::GlobalCtxt>>::enter::<core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>, rustc_driver_impl[783dc85a9905d0e5]::run_compiler::{closure#1}::{closure#2}::{closure#4}>
  48:        0x10b78ca24 - <rustc_interface[86097f894d44157]::interface::Compiler>::enter::<rustc_driver_impl[783dc85a9905d0e5]::run_compiler::{closure#1}::{closure#2}, core[b2c7346eda96f041]::result::Result<core[b2c7346eda96f041]::option::Option<rustc_interface[86097f894d44157]::queries::Linker>, rustc_span[350718d478b9eefa]::ErrorGuaranteed>>
  49:        0x10b7432cc - rustc_span[350718d478b9eefa]::set_source_map::<core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>, rustc_interface[86097f894d44157]::interface::run_compiler<core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>, rustc_driver_impl[783dc85a9905d0e5]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  50:        0x10b7568a8 - std[bf9110f564f42f12]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[86097f894d44157]::util::run_in_thread_pool_with_globals<rustc_interface[86097f894d44157]::interface::run_compiler<core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>, rustc_driver_impl[783dc85a9905d0e5]::run_compiler::{closure#1}>::{closure#0}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>
  51:        0x10b747a78 - <<std[bf9110f564f42f12]::thread::Builder>::spawn_unchecked_<rustc_interface[86097f894d44157]::util::run_in_thread_pool_with_globals<rustc_interface[86097f894d44157]::interface::run_compiler<core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>, rustc_driver_impl[783dc85a9905d0e5]::run_compiler::{closure#1}>::{closure#0}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b2c7346eda96f041]::result::Result<(), rustc_span[350718d478b9eefa]::ErrorGuaranteed>>::{closure#1} as core[b2c7346eda96f041]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:        0x10324cdf4 - std::sys::unix::thread::Thread::new::thread_start::h7f56b35fafcfec87
  53:        0x19403826c - __pthread_deallocate

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `penumbra::core::transaction::v1alpha1::action::<impl at crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46>::merge::{closure#2}`
#1 [mir_const] preparing `penumbra::core::transaction::v1alpha1::action::<impl at crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46>::merge::{closure#2}` for borrow checking
#2 [mir_promoted] processing MIR for `penumbra::core::transaction::v1alpha1::action::<impl at crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46>::merge::{closure#2}`
#3 [mir_borrowck] borrow-checking `penumbra::core::transaction::v1alpha1::action::<impl at crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46>::merge::{closure#2}`
#4 [mir_borrowck] borrow-checking `penumbra::core::transaction::v1alpha1::action::<impl at crates/proto/src/gen/penumbra.core.transaction.v1alpha1.rs:68:32: 68:46>::merge`
#5 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: re-entrant incremental verify failure, suppressing message

error: could not compile `penumbra-proto` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by Nilstrieb** [comment]
This was probably fixed in #111952. Are you able to reproduce this on beta, which contains the fix?

**Comment by tgross35** [comment]
@hdevalence does this still happen?

Probably safe to close if we don't hear back soon

@rustbor label +E-needs-mcve

**Comment by hdevalence** [comment]
I lost the state I'd need to reproduce, so probably safe to close. Thanks!
