### ISSUE TITLE
`Unexpected parameter Type(Repr) when substituting in region`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#112823]
### Code

```Rust
use std::future::Future;

trait Stream {}

trait X {
    type LineStream<'a, Repr>
    where
        Self: 'a;
    type LineStreamFut<'a, Repr>
    where
        Self: 'a;
}

struct Y;

impl X for Y {
    type LineStream<'c, 'd> = impl Stream;
    type LineStreamFut<'a, Repr> = impl Future<Output = Self::LineStream<'a, Repr>>;
    fn line_stream<'a, Repr>(&'a self) -> Self::LineStreamFut<'a, Repr> {}
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (2d0aa5768 2023-06-18)
binary: rustc
commit-hash: 2d0aa57684e10f7b3d3fe740ee18d431181583ad
commit-date: 2023-06-18
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:817:13: Unexpected parameter Type(Repr) when substituting in region 'd (index=1)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7f549eb67e11 - std::backtrace_rs::backtrace::libunwind::trace::h184786643c1f8146
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f549eb67e11 - std::backtrace_rs::backtrace::trace_unsynchronized::h10cef21dd42edd42
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f549eb67e11 - std::sys_common::backtrace::_print_fmt::hca8722c6f82eccd9
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f549eb67e11 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b170c65cdf95c48
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f549ebc94bf - core::fmt::rt::Argument::fmt::h7e50834cab28e102
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/core/src/fmt/rt.rs:138:9
   5:     0x7f549ebc94bf - core::fmt::write::h8bd64fe81f89dd81
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f549eb5a977 - std::io::Write::write_fmt::hc75a842b3ecac8bc
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/io/mod.rs:1714:15
   7:     0x7f549eb67c25 - std::sys_common::backtrace::_print::hdb7a31bd8c54eb49
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f549eb67c25 - std::sys_common::backtrace::print::hbcf968a4222dc0b5
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f549eb6a9d3 - std::panicking::default_hook::{{closure}}::h02987b13cfa1387d
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/panicking.rs:269:22
  10:     0x7f549eb6a764 - std::panicking::default_hook::hcb3fd44404995c49
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/panicking.rs:288:9
  11:     0x7f54a1dabd6b - <rustc_driver_impl[7175fdba515aac6e]::install_ice_hook::{closure#0} as core[baaa20f768102eef]::ops::function::FnOnce<(&core[baaa20f768102eef]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f549eb6b1fe - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hec1e31de726d1657
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/alloc/src/boxed.rs:2007:9
  13:     0x7f549eb6b1fe - std::panicking::rust_panic_with_hook::h223f39091438ac61
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/panicking.rs:709:13
  14:     0x7f54a22ae8d1 - std[755122e38bdf80bb]::panicking::begin_panic::<rustc_errors[22c53a0383ffa2c9]::ExplicitBug>::{closure#0}
  15:     0x7f54a22ad526 - std[755122e38bdf80bb]::sys_common::backtrace::__rust_end_short_backtrace::<std[755122e38bdf80bb]::panicking::begin_panic<rustc_errors[22c53a0383ffa2c9]::ExplicitBug>::{closure#0}, !>
  16:     0x7f54a2342666 - std[755122e38bdf80bb]::panicking::begin_panic::<rustc_errors[22c53a0383ffa2c9]::ExplicitBug>
  17:     0x7f54a22aa2e4 - <rustc_errors[22c53a0383ffa2c9]::HandlerInner>::bug::<alloc[d1ea88cdd25af2a4]::string::String>
  18:     0x7f54a22aa166 - <rustc_errors[22c53a0383ffa2c9]::Handler>::bug::<alloc[d1ea88cdd25af2a4]::string::String>
  19:     0x7f54a22fd5fc - rustc_middle[56c503886228b671]::util::bug::opt_span_bug_fmt::<rustc_span[1e0547ff349d1bca]::span_encoding::Span>::{closure#0}
  20:     0x7f54a22fa49a - rustc_middle[56c503886228b671]::ty::context::tls::with_opt::<rustc_middle[56c503886228b671]::util::bug::opt_span_bug_fmt<rustc_span[1e0547ff349d1bca]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f54a22fa46a - rustc_middle[56c503886228b671]::ty::context::tls::with_context_opt::<rustc_middle[56c503886228b671]::ty::context::tls::with_opt<rustc_middle[56c503886228b671]::util::bug::opt_span_bug_fmt<rustc_span[1e0547ff349d1bca]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f54a00ef2bd - rustc_middle[56c503886228b671]::util::bug::bug_fmt
  23:     0x7f54a22df921 - <rustc_middle[56c503886228b671]::ty::subst::SubstFolder as rustc_type_ir[816d146e67c43ce4]::fold::TypeFolder<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::fold_region::region_param_invalid
  24:     0x7f549fdf0d4b - <rustc_middle[56c503886228b671]::ty::Ty as rustc_type_ir[816d146e67c43ce4]::fold::TypeSuperFoldable<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[56c503886228b671]::ty::subst::SubstFolder>
  25:     0x7f54a2adf6aa - <rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector as rustc_type_ir[816d146e67c43ce4]::visit::TypeVisitor<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::visit_ty
  26:     0x7f54a2ab1353 - <rustc_middle[56c503886228b671]::ty::Term as rustc_type_ir[816d146e67c43ce4]::visit::TypeVisitable<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::visit_with::<rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector>
  27:     0x7f54a2ab0cc7 - <rustc_middle[56c503886228b671]::ty::PredicateKind as rustc_type_ir[816d146e67c43ce4]::visit::TypeVisitable<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::visit_with::<rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector>
  28:     0x7f54a2adf60b - <rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector as rustc_type_ir[816d146e67c43ce4]::visit::TypeVisitor<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::visit_ty
  29:     0x7f54a2adf6b6 - <rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector as rustc_type_ir[816d146e67c43ce4]::visit::TypeVisitor<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::visit_ty
  30:     0x7f54a2ad44f3 - <rustc_middle[56c503886228b671]::ty::sty::FnSig as rustc_type_ir[816d146e67c43ce4]::visit::TypeVisitable<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::visit_with::<rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector>
  31:     0x7f54a2adec5b - <rustc_ty_utils[271e305c766ff689]::opaque_types::OpaqueTypeCollector>::collect::<rustc_middle[56c503886228b671]::ty::sty::FnSig>
  32:     0x7f54a2adefb6 - rustc_ty_utils[271e305c766ff689]::opaque_types::opaque_types_defined_by
  33:     0x7f54a26e9b8f - rustc_query_impl[e44c98b80a645267]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e44c98b80a645267]::query_impl::opaque_types_defined_by::dynamic_query::{closure#2}::{closure#0}, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 16usize]>>
  34:     0x7f54a26774e2 - <rustc_query_impl[e44c98b80a645267]::query_impl::opaque_types_defined_by::dynamic_query::{closure#2} as core[baaa20f768102eef]::ops::function::FnOnce<(rustc_middle[56c503886228b671]::ty::context::TyCtxt, rustc_span[1e0547ff349d1bca]::def_id::LocalDefId)>>::call_once
  35:     0x7f54a0672435 - rustc_query_system[ba457099f14053e9]::query::plumbing::try_execute_query::<rustc_query_impl[e44c98b80a645267]::DynamicConfig<rustc_query_system[ba457099f14053e9]::query::caches::VecCache<rustc_span[1e0547ff349d1bca]::def_id::LocalDefId, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[e44c98b80a645267]::plumbing::QueryCtxt, false>
  36:     0x7f54a266aa6c - rustc_query_impl[e44c98b80a645267]::query_impl::opaque_types_defined_by::get_query_non_incr::__rust_end_short_backtrace
  37:     0x7f54a0cf05e7 - <rustc_infer[8e145c87a4219640]::infer::InferCtxt>::opaque_type_origin
  38:     0x7f54a146c741 - <rustc_middle[56c503886228b671]::ty::fold::BottomUpFolder<<rustc_infer[8e145c87a4219640]::infer::InferCtxt>::replace_opaque_types_with_inference_vars<rustc_middle[56c503886228b671]::ty::Ty>::{closure#3}, <rustc_infer[8e145c87a4219640]::infer::InferCtxt>::replace_opaque_types_with_inference_vars<rustc_middle[56c503886228b671]::ty::Ty>::{closure#1}, <rustc_infer[8e145c87a4219640]::infer::InferCtxt>::replace_opaque_types_with_inference_vars<rustc_middle[56c503886228b671]::ty::Ty>::{closure#2}> as rustc_type_ir[816d146e67c43ce4]::fold::FallibleTypeFolder<rustc_middle[56c503886228b671]::ty::context::TyCtxt>>::try_fold_ty
  39:     0x7f54a062cad7 - rustc_hir_typeck[71f17ea952b4220]::check::check_fn
  40:     0x7f54a061a811 - rustc_hir_typeck[71f17ea952b4220]::typeck
  41:     0x7f549fe0495c - rustc_query_impl[e44c98b80a645267]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e44c98b80a645267]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 8usize]>>
  42:     0x7f549fe0493e - <rustc_query_impl[e44c98b80a645267]::query_impl::typeck::dynamic_query::{closure#2} as core[baaa20f768102eef]::ops::function::FnOnce<(rustc_middle[56c503886228b671]::ty::context::TyCtxt, rustc_span[1e0547ff349d1bca]::def_id::LocalDefId)>>::call_once
  43:     0x7f549fed14cd - rustc_query_system[ba457099f14053e9]::query::plumbing::try_execute_query::<rustc_query_impl[e44c98b80a645267]::DynamicConfig<rustc_query_system[ba457099f14053e9]::query::caches::VecCache<rustc_span[1e0547ff349d1bca]::def_id::LocalDefId, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e44c98b80a645267]::plumbing::QueryCtxt, false>
  44:     0x7f54a171961f - rustc_query_impl[e44c98b80a645267]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  45:     0x7f54a1f05e9b - rustc_middle[56c503886228b671]::query::plumbing::query_get_at::<rustc_query_system[ba457099f14053e9]::query::caches::VecCache<rustc_span[1e0547ff349d1bca]::def_id::LocalDefId, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 8usize]>>>
  46:     0x7f54a1f0a0f0 - <rustc_hir_analysis[eb0d24a920376e7]::collect::type_of::opaque::TaitConstraintLocator>::check
  47:     0x7f54a1f09841 - <rustc_hir_analysis[eb0d24a920376e7]::collect::type_of::opaque::TaitConstraintLocator as rustc_hir[51d35b3e8e0cb049]::intravisit::Visitor>::visit_nested_impl_item
  48:     0x7f54a1e99de5 - rustc_hir[51d35b3e8e0cb049]::intravisit::walk_item::<rustc_hir_analysis[eb0d24a920376e7]::collect::type_of::opaque::TaitConstraintLocator>
  49:     0x7f54a1f09f00 - rustc_hir_analysis[eb0d24a920376e7]::collect::type_of::opaque::find_opaque_ty_constraints_for_tait
  50:     0x7f54a0f52468 - rustc_hir_analysis[eb0d24a920376e7]::collect::type_of::type_of
  51:     0x7f549ff2635e - rustc_query_impl[e44c98b80a645267]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e44c98b80a645267]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 8usize]>>
  52:     0x7f549ff26090 - <rustc_query_impl[e44c98b80a645267]::query_impl::type_of::dynamic_query::{closure#2} as core[baaa20f768102eef]::ops::function::FnOnce<(rustc_middle[56c503886228b671]::ty::context::TyCtxt, rustc_span[1e0547ff349d1bca]::def_id::DefId)>>::call_once
  53:     0x7f549fe0cb35 - rustc_query_system[ba457099f14053e9]::query::plumbing::try_execute_query::<rustc_query_impl[e44c98b80a645267]::DynamicConfig<rustc_query_system[ba457099f14053e9]::query::caches::DefaultCache<rustc_span[1e0547ff349d1bca]::def_id::DefId, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e44c98b80a645267]::plumbing::QueryCtxt, false>
  54:     0x7f54a1716421 - rustc_query_impl[e44c98b80a645267]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  55:     0x7f54a0e94e66 - rustc_middle[56c503886228b671]::query::plumbing::query_get_at::<rustc_query_system[ba457099f14053e9]::query::caches::DefaultCache<rustc_span[1e0547ff349d1bca]::def_id::DefId, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 8usize]>>>
  56:     0x7f54a0e8cdcf - rustc_hir_analysis[eb0d24a920376e7]::check::check::check_mod_item_types
  57:     0x7f54a0a1438c - rustc_query_impl[e44c98b80a645267]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e44c98b80a645267]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 0usize]>>
  58:     0x7f54a0a1436e - <rustc_query_impl[e44c98b80a645267]::query_impl::check_mod_item_types::dynamic_query::{closure#2} as core[baaa20f768102eef]::ops::function::FnOnce<(rustc_middle[56c503886228b671]::ty::context::TyCtxt, rustc_span[1e0547ff349d1bca]::def_id::LocalDefId)>>::call_once
  59:     0x7f54a044397f - rustc_query_system[ba457099f14053e9]::query::plumbing::try_execute_query::<rustc_query_impl[e44c98b80a645267]::DynamicConfig<rustc_query_system[ba457099f14053e9]::query::caches::VecCache<rustc_span[1e0547ff349d1bca]::def_id::LocalDefId, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[e44c98b80a645267]::plumbing::QueryCtxt, false>
  60:     0x7f54a1721b92 - rustc_query_impl[e44c98b80a645267]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  61:     0x7f54a11c1187 - <rustc_middle[56c503886228b671]::hir::map::Map>::for_each_module::<rustc_hir_analysis[eb0d24a920376e7]::check_crate::{closure#6}::{closure#0}>
  62:     0x7f54a11c099d - <rustc_session[ebb9057f9195e4cc]::session::Session>::time::<(), rustc_hir_analysis[eb0d24a920376e7]::check_crate::{closure#6}>
  63:     0x7f54a11bee67 - rustc_hir_analysis[eb0d24a920376e7]::check_crate
  64:     0x7f54a11b280a - rustc_interface[e3841d12b9b221e7]::passes::analysis
  65:     0x7f54a122350a - rustc_query_impl[e44c98b80a645267]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e44c98b80a645267]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 1usize]>>
  66:     0x7f54a12234f9 - <rustc_query_impl[e44c98b80a645267]::query_impl::analysis::dynamic_query::{closure#2} as core[baaa20f768102eef]::ops::function::FnOnce<(rustc_middle[56c503886228b671]::ty::context::TyCtxt, ())>>::call_once
  67:     0x7f54a143f0f8 - rustc_query_system[ba457099f14053e9]::query::plumbing::try_execute_query::<rustc_query_impl[e44c98b80a645267]::DynamicConfig<rustc_query_system[ba457099f14053e9]::query::caches::SingleCache<rustc_middle[56c503886228b671]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e44c98b80a645267]::plumbing::QueryCtxt, false>
  68:     0x7f54a143eed7 - rustc_query_impl[e44c98b80a645267]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  69:     0x7f54a12d6115 - <rustc_middle[56c503886228b671]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[7175fdba515aac6e]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>>
  70:     0x7f54a12d57bc - <rustc_interface[e3841d12b9b221e7]::interface::Compiler>::enter::<rustc_driver_impl[7175fdba515aac6e]::run_compiler::{closure#1}::{closure#2}, core[baaa20f768102eef]::result::Result<core[baaa20f768102eef]::option::Option<rustc_interface[e3841d12b9b221e7]::queries::Linker>, rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>>
  71:     0x7f54a12d2e21 - std[755122e38bdf80bb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e3841d12b9b221e7]::util::run_in_thread_pool_with_globals<rustc_interface[e3841d12b9b221e7]::interface::run_compiler<core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>, rustc_driver_impl[7175fdba515aac6e]::run_compiler::{closure#1}>::{closure#0}, core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>>
  72:     0x7f54a12d25a5 - <<std[755122e38bdf80bb]::thread::Builder>::spawn_unchecked_<rustc_interface[e3841d12b9b221e7]::util::run_in_thread_pool_with_globals<rustc_interface[e3841d12b9b221e7]::interface::run_compiler<core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>, rustc_driver_impl[7175fdba515aac6e]::run_compiler::{closure#1}>::{closure#0}, core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[baaa20f768102eef]::result::Result<(), rustc_span[1e0547ff349d1bca]::ErrorGuaranteed>>::{closure#1} as core[baaa20f768102eef]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  73:     0x7f549eb75685 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59d6baf462325ed4
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/alloc/src/boxed.rs:1993:9
  74:     0x7f549eb75685 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4eca0dd82537346f
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/alloc/src/boxed.rs:1993:9
  75:     0x7f549eb75685 - std::sys::unix::thread::Thread::new::thread_start::h38e13b8ca4256fdb
                               at /rustc/2d0aa57684e10f7b3d3fe740ee18d431181583ad/library/std/src/sys/unix/thread.rs:108:17
  76:     0x7f549e90d44b - <unknown>
  77:     0x7f549e990e40 - <unknown>
  78:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (2d0aa5768 2023-06-18) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [opaque_types_defined_by] computing the opaque types defined by `<impl at treereduce.out:16:1: 16:13>::line_stream`
#1 [typeck] type-checking `<impl at treereduce.out:16:1: 16:13>::line_stream`
#2 [type_of] computing type of `<impl at treereduce.out:16:1: 16:13>::LineStream::{opaque#0}`
#3 [check_mod_item_types] checking item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 6 previous errors

Some errors have detailed explanations: E0049, E0407, E0601, E0658.
For more information about an error, try `rustc --explain E0049`.
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Crashing since at least `1.41.0`

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23112823.20.60Unexpected.20parameter.20Type.28Repr.29.20when.20substituting.20.E2.80.A6)).

@rustbot label -I-prioritize +P-low

**Comment by albertlarsan68** [comment]
Seems to be fixed in latest nightly (2023-07-12)
