### ISSUE TITLE
internal compiler error: encountered incremental compilation error with mir_built(70cff4bb142b8a2c-2b2efb937f56e202)

### ISSUE THREAD

**Issue by drriguz** [rust-lang/rust#113401]
### Code
prompt.rs:
```Rust
use serde::{Deserialize, Serialize};
use serde_yaml::Value;
use std::collections::HashMap;

#[derive(Debug, Deserialize)]
pub enum Example {
    CompletionExample {
        name: String,
        values: Vec<String>,
        test: Option<String>,
    },
    ChatExample {
        input: String,
        output: Vec<String>,
    },
}

#[derive(Debug, Deserialize)]
pub struct Message {
    pub input: String,
    pub output: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct Prompt {
    #[serde(rename = "type")]
    pub prompt_type: String,
    pub vendor: String,
    pub model: String,
    pub prompt: String,
    pub parameters: HashMap<String, Value>,
    pub examples: Option<Vec<Example>>,
    pub context: Option<String>,
    pub messages: Option<Vec<Message>>,
}
```

handler.rs:
```rust
use crate::config::HandlerConfig;
use crate::prompt::Prompt;
use actix_web::{http::Method, web, HttpRequest, HttpResponse};
use log::info;

pub async fn index(req: HttpRequest, config: web::Data<HandlerConfig>) -> HttpResponse {
    info!("{:#?}", req);
    if req.method() == Method::GET {
        HttpResponse::Ok().body(format!("Hello {}!\n", config.name))
    } else {
        HttpResponse::Ok().body(format!("Thanks {}!\n", config.name))
    }
}

pub async fn execute_prompt(yaml: String) -> HttpResponse {
    let prompt: Result<Prompt, _> = serde_yaml::from_str(&yaml);
    println!("{:?}", prompt);
    HttpResponse::Ok().body("OK")
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

### Error output

```
 Compiling function v0.1.0 (/home/tek/fn/prompt-runtime)
warning: unused import: `Serialize`
 --> src/prompt.rs:1:26
  |
1 | use serde::{Deserialize, Serialize};
  |                          ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: internal compiler error: encountered incremental compilation error with mir_built(70cff4bb142b8a2c-2b2efb937f56e202)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p function` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for mir_built(70cff4bb142b8a2c-2b2efb937f56e202): Steal { value: RwLock(RefCell { value: Some(Body { basic_blocks: BasicBlocks { basic_blocks: [BasicBlockData { statements: [StorageLive(_3), _3 = std::option::Option::<std::string::String>::None, FakeRead(ForLet(None), _3), AscribeUserType(_3, o, UserTypeProjection { base: UserType(1), projs: [] }), StorageLive(_4), _4 = std::option::Option::<Vec<std::string::String>>::None, FakeRead(ForLet(None), _4), AscribeUserType(_4, o, UserTypeProjection { base: UserType(3), projs: [] }), StorageLive(_5)], terminator: Some(Terminator { source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#64), scope: scope[2] }, kind: goto -> bb1 }), is_cleanup: false }, BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#64), scope: scope[2] }, kind: falseUnwind -> [real: bb2, unwind: bb181] }), is_cleanup: false }, BasicBlockData { statements: [StorageLive(_7), StorageLive(_8), StorageLive(_9), StorageLive(_10), _10 = &mut _2, _9 = &mut (*_10)], terminator: Some(Terminator { source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#64), scope: scope[3] }, ... SourceInfo { span: src/prompt.rs:5:17: 5:28 (#103), scope: scope[16] }, value: _69, argument_index: None }, VarDebugInfo { name: "__field1", source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#64), scope: scope[17] }, value: _72, argument_index: None }, VarDebugInfo { name: "__field1", source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#64), scope: scope[18] }, value: _74, argument_index: None }, VarDebugInfo { name: "__val", source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#105), scope: scope[19] }, value: _77, argument_index: None }, VarDebugInfo { name: "__err", source_info: SourceInfo { span: src/prompt.rs:5:17: 5:28 (#105), scope: scope[20] }, value: _78, argument_index: None }], span: src/prompt.rs:5:17: 5:28 (#64), required_consts: [], is_polymorphic: true, injection_phase: None, tainted_by_errors: None }) }) }', /rustc/90c541806f23a127002de5b4038be731ba1458ca/compiler/rustc_query_system/src/query/plumbing.rs:715:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: rustc_query_system::query::plumbing::incremental_verify_ich_failed::<rustc_middle::ty::context::TyCtxt>
   3: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_incr<rustc_query_impl::queries::mir_built, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
   4: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_built, rustc_query_impl::plumbing::QueryCtxt>
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
   6: rustc_mir_transform::mir_const
   7: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::mir_const, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
   8: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::mir_const, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, rustc_middle::query::erase::Erased<[u8; 8]>>
   9: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_incr<rustc_query_impl::queries::mir_const, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
  10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_const, rustc_query_impl::plumbing::QueryCtxt>
  11: rustc_mir_transform::mir_promoted
  12: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::mir_promoted, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, rustc_middle::query::erase::Erased<[u8; 16]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 16]>>
  13: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::mir_promoted, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, rustc_middle::query::erase::Erased<[u8; 16]>>
  14: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_incr<rustc_query_impl::queries::mir_promoted, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 16]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
  15: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_promoted, rustc_query_impl::plumbing::QueryCtxt>
  16: rustc_borrowck::mir_borrowck
  17: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
  18: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
  19: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, rustc_middle::query::erase::Erased<[u8; 8]>>
  20: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_incr<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>::{closure#0}, core::option::Option<(rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>>
  21: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_borrowck, rustc_query_impl::plumbing::QueryCtxt>
  22: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  23: rustc_mir_transform::mir_drops_elaborated_and_const_checked
  24: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_incr<rustc_query_impl::queries::mir_drops_elaborated_and_const_checked, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
  25: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_drops_elaborated_and_const_checked, rustc_query_impl::plumbing::QueryCtxt>
  26: rustc_mir_transform::optimized_mir
  27: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_incr<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt>::{closure#2}, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>::{closure#0}, (rustc_middle::query::erase::Erased<[u8; 8]>, rustc_query_system::dep_graph::graph::DepNodeIndex)>
  28: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt>
  29: rustc_monomorphize::collector::collect_neighbours
  ...
  90: rustc_monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `prompt::_::<impl at src/prompt.rs:5:17: 5:28>::deserialize::<impl at src/prompt.rs:5:17: 5:28>::visit_enum::<impl at src/prompt.rs:5:17: 5:28>::visit_map`
#1 [mir_const] preparing `prompt::_::<impl at src/prompt.rs:5:17: 5:28>::deserialize::<impl at src/prompt.rs:5:17: 5:28>::visit_enum::<impl at src/prompt.rs:5:17: 5:28>::visit_map` for borrow checking
#2 [mir_promoted] processing MIR for `prompt::_::<impl at src/prompt.rs:5:17: 5:28>::deserialize::<impl at src/prompt.rs:5:17: 5:28>::visit_enum::<impl at src/prompt.rs:5:17: 5:28>::visit_map`
#3 [mir_borrowck] borrow-checking `prompt::_::<impl at src/prompt.rs:5:17: 5:28>::deserialize::<impl at src/prompt.rs:5:17: 5:28>::visit_enum::<impl at src/prompt.rs:5:17: 5:28>::visit_map`
#4 [mir_drops_elaborated_and_const_checked] elaborating drops for `prompt::_::<impl at src/prompt.rs:5:17: 5:28>::deserialize::<impl at src/prompt.rs:5:17: 5:28>::visit_enum::<impl at src/prompt.rs:5:17: 5:28>::visit_map`
#5 [optimized_mir] optimizing MIR for `prompt::_::<impl at src/prompt.rs:5:17: 5:28>::deserialize::<impl at src/prompt.rs:5:17: 5:28>::visit_enum::<impl at src/prompt.rs:5:17: 5:28>::visit_map`
#6 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
warning: `function` (bin "function") generated 1 warning
error: could not compile `function` (bin "function") due to previous error; 1 warning emitted

 *  The terminal process "cargo 'run', '--package', 'function', '--bin', 'function'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by lqd** [comment]
Can you check if it happens on beta ? This issue should be fixed already, and the fix should land on stable next week.

**Comment by drriguz** [comment]
> Can you check if it happens on beta ? This issue should be fixed already, and the fix should land on stable next week.

Yes, I updated to `rustc 1.71.0-beta.4 (dbf31f17d 2023-06-24)` and it works! Thanks!
