### ISSUE TITLE
Error while building samply which depends on bitvec

### ISSUE THREAD

**Issue by jasikpark** [rust-lang/rust#113806]
### Code

`cargo install samply`
https://github.com/mstange/samply/commit/d4b3fa2a30f755340d1bd9df3f6b3417b165569b

### Meta

`rustc --version --verbose`:
```

rustc 1.71.0-nightly (2f6bc5d25 2023-05-09)
binary: rustc
commit-hash: 2f6bc5d259e7ab25ddfdd33de53b892770218918
commit-date: 2023-05-09
host: aarch64-apple-darwin
release: 1.71.0-nightly
LLVM version: 16.0.2

```

### Error output

```
 Compiling async-compression v0.4.1
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:195:90: Failed to normalize alloc::raw_vec::RawVec<<T as store::BitStore>::Mem>, maybe try to call `try_normalize_erasing_regions` instead

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f6bc5d259e7ab25ddfdd33de53b892770218918/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:        0x104bedb18 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc7511db9accc9da6
   1:        0x104c3d550 - core::fmt::write::hd57146df51ac22d3
   2:        0x104be3d24 - std::io::Write::write_fmt::hff4dc78dc1f20264
   3:        0x104bed96c - std::sys_common::backtrace::print::h5221e5047610643b
   4:        0x104bf0370 - std::panicking::default_hook::{{closure}}::h9a736db53539f589
   5:        0x104bf0178 - std::panicking::default_hook::hd659925107a6e71f
   6:        0x10d03cad4 - rustc_driver_impl[c1a57d0e5e3d90de]::install_ice_hook::{closure#0}
   7:        0x104bf0984 - std::panicking::rust_panic_with_hook::hd96777ae95bb62ed
   8:        0x110e29f6c - std[65552bf0469df9ea]::panicking::begin_panic::<rustc_errors[4695d0b1577230d1]::ExplicitBug>::{closure#0}
   9:        0x110e27124 - std[65552bf0469df9ea]::sys_common::backtrace::__rust_end_short_backtrace::<std[65552bf0469df9ea]::panicking::begin_panic<rustc_errors[4695d0b1577230d1]::ExplicitBug>::{closure#0}, !>
  10:        0x111420c88 - std[65552bf0469df9ea]::panicking::begin_panic::<rustc_errors[4695d0b1577230d1]::ExplicitBug>
  11:        0x110e1e508 - <rustc_errors[4695d0b1577230d1]::HandlerInner>::bug::<alloc[990e4dfb31e0f5f]::string::String>
  12:        0x110e1dec4 - <rustc_errors[4695d0b1577230d1]::Handler>::bug::<alloc[990e4dfb31e0f5f]::string::String>
  13:        0x110eff2f0 - rustc_middle[fcd121f4c157b0f5]::util::bug::opt_span_bug_fmt::<rustc_span[8eaa967f211a7d38]::span_encoding::Span>::{closure#0}
  14:        0x110efe9b4 - rustc_middle[fcd121f4c157b0f5]::ty::context::tls::with_opt::<rustc_middle[fcd121f4c157b0f5]::util::bug::opt_span_bug_fmt<rustc_span[8eaa967f211a7d38]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:        0x110efe980 - rustc_middle[fcd121f4c157b0f5]::ty::context::tls::with_context_opt::<rustc_middle[fcd121f4c157b0f5]::ty::context::tls::with_opt<rustc_middle[fcd121f4c157b0f5]::util::bug::opt_span_bug_fmt<rustc_span[8eaa967f211a7d38]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:        0x111425b14 - rustc_middle[fcd121f4c157b0f5]::util::bug::bug_fmt
  17:        0x110e91308 - <rustc_middle[fcd121f4c157b0f5]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_type_ir[49431c2b1ff976c6]::fold::TypeFolder<rustc_middle[fcd121f4c157b0f5]::ty::context::TyCtxt>>::fold_ty
  18:        0x10f74beb8 - <core[89aff604de9e9977]::iter::adapters::map::Map<core[89aff604de9e9977]::iter::adapters::enumerate::Enumerate<core[89aff604de9e9977]::slice::iter::Iter<rustc_middle[fcd121f4c157b0f5]::ty::FieldDef>>, <rustc_mir_dataflow[e3da9f9a952dbc88]::elaborate_drops::DropCtxt<rustc_mir_transform[72200e7fb31f2ff]::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}> as core[89aff604de9e9977]::iter::traits::iterator::Iterator>::fold::<(), core[89aff604de9e9977]::iter::traits::iterator::Iterator::for_each::call<(rustc_middle[fcd121f4c157b0f5]::mir::syntax::Place, core[89aff604de9e9977]::option::Option<()>), <alloc[990e4dfb31e0f5f]::vec::Vec<(rustc_middle[fcd121f4c157b0f5]::mir::syntax::Place, core[89aff604de9e9977]::option::Option<()>)>>::extend_trusted<core[89aff604de9e9977]::iter::adapters::map::Map<core[89aff604de9e9977]::iter::adapters::enumerate::Enumerate<core[89aff604de9e9977]::slice::iter::Iter<rustc_middle[fcd121f4c157b0f5]::ty::FieldDef>>, <rustc_mir_dataflow[e3da9f9a952dbc88]::elaborate_drops::DropCtxt<rustc_mir_transform[72200e7fb31f2ff]::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}>>::{closure#0}>::{closure#0}>
  19:        0x10f86da44 - <alloc[990e4dfb31e0f5f]::vec::Vec<(rustc_middle[fcd121f4c157b0f5]::mir::syntax::Place, core[89aff604de9e9977]::option::Option<()>)> as alloc[990e4dfb31e0f5f]::vec::spec_from_iter::SpecFromIter<(rustc_middle[fcd121f4c157b0f5]::mir::syntax::Place, core[89aff604de9e9977]::option::Option<()>), core[89aff604de9e9977]::iter::adapters::map::Map<core[89aff604de9e9977]::iter::adapters::enumerate::Enumerate<core[89aff604de9e9977]::slice::iter::Iter<rustc_middle[fcd121f4c157b0f5]::ty::FieldDef>>, <rustc_mir_dataflow[e3da9f9a952dbc88]::elaborate_drops::DropCtxt<rustc_mir_transform[72200e7fb31f2ff]::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}>>>::from_iter
  20:        0x10f757744 - <rustc_mir_dataflow[e3da9f9a952dbc88]::elaborate_drops::DropCtxt<rustc_mir_transform[72200e7fb31f2ff]::shim::DropShimElaborator>>::open_drop_for_adt
  21:        0x10f757110 - <rustc_mir_dataflow[e3da9f9a952dbc88]::elaborate_drops::DropCtxt<rustc_mir_transform[72200e7fb31f2ff]::shim::DropShimElaborator>>::elaborate_drop
  22:        0x10f889484 - rustc_mir_transform[72200e7fb31f2ff]::shim::make_shim
  23:        0x11025f498 - rustc_query_system[43c77ae2b9577fdf]::query::plumbing::try_execute_query::<rustc_query_impl[27a0964dc7102f4f]::queries::mir_shims, rustc_query_impl[27a0964dc7102f4f]::plumbing::QueryCtxt>
  24:        0x1102e5290 - rustc_query_impl[27a0964dc7102f4f]::get_query::mir_shims
  25:        0x110dd8eec - <rustc_middle[fcd121f4c157b0f5]::ty::context::TyCtxt>::instance_mir
  26:        0x10f832174 - <rustc_mir_transform[72200e7fb31f2ff]::inline::Inliner>::try_inlining
  27:        0x10f831a50 - <rustc_mir_transform[72200e7fb31f2ff]::inline::Inliner>::process_blocks
  28:        0x10f831b6c - <rustc_mir_transform[72200e7fb31f2ff]::inline::Inliner>::process_blocks
  29:        0x10f83137c - <rustc_mir_transform[72200e7fb31f2ff]::inline::Inline as rustc_middle[fcd121f4c157b0f5]::mir::MirPass>::run_pass
  30:        0x10f856084 - rustc_mir_transform[72200e7fb31f2ff]::pass_manager::run_passes_inner
  31:        0x10f765c00 - rustc_mir_transform[72200e7fb31f2ff]::optimized_mir
  32:        0x110174d44 - rustc_query_system[43c77ae2b9577fdf]::query::plumbing::try_execute_query::<rustc_query_impl[27a0964dc7102f4f]::queries::optimized_mir, rustc_query_impl[27a0964dc7102f4f]::plumbing::QueryCtxt>
  33:        0x1102dcb1c - rustc_query_impl[27a0964dc7102f4f]::get_query::optimized_mir
  34:        0x110752c64 - rustc_middle[fcd121f4c157b0f5]::ty::query::query_get_at::<rustc_query_system[43c77ae2b9577fdf]::query::caches::DefaultCache<rustc_span[8eaa967f211a7d38]::def_id::DefId, rustc_middle[fcd121f4c157b0f5]::query::erase::Erased<[u8; 8usize]>>>
  35:        0x1107589ac - <rustc_metadata[92e4fc00d230a709]::rmeta::encoder::EncodeContext>::encode_crate_root
  36:        0x110764a90 - rustc_metadata[92e4fc00d230a709]::rmeta::encoder::encode_metadata_impl
  37:        0x11072a890 - rustc_data_structures[b8c1add5d0670fd2]::sync::join::<rustc_metadata[92e4fc00d230a709]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[92e4fc00d230a709]::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  38:        0x11076429c - rustc_metadata[92e4fc00d230a709]::rmeta::encoder::encode_metadata
  39:        0x11073c6c4 - rustc_metadata[92e4fc00d230a709]::fs::encode_and_write_metadata
  40:        0x10d0ec840 - rustc_interface[c450773bf3cb492f]::passes::start_codegen
  41:        0x10d064ef4 - <rustc_middle[fcd121f4c157b0f5]::ty::context::GlobalCtxt>::enter::<<rustc_interface[c450773bf3cb492f]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[89aff604de9e9977]::result::Result<alloc[990e4dfb31e0f5f]::boxed::Box<dyn core[89aff604de9e9977]::any::Any>, rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>>
  42:        0x10d0eff00 - <rustc_interface[c450773bf3cb492f]::queries::Queries>::ongoing_codegen
  43:        0x10d018cd4 - <rustc_interface[c450773bf3cb492f]::interface::Compiler>::enter::<rustc_driver_impl[c1a57d0e5e3d90de]::run_compiler::{closure#1}::{closure#2}, core[89aff604de9e9977]::result::Result<core[89aff604de9e9977]::option::Option<rustc_interface[c450773bf3cb492f]::queries::Linker>, rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>>
  44:        0x10cfe1074 - std[65552bf0469df9ea]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c450773bf3cb492f]::util::run_in_thread_pool_with_globals<rustc_interface[c450773bf3cb492f]::interface::run_compiler<core[89aff604de9e9977]::result::Result<(), rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>, rustc_driver_impl[c1a57d0e5e3d90de]::run_compiler::{closure#1}>::{closure#0}, core[89aff604de9e9977]::result::Result<(), rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[89aff604de9e9977]::result::Result<(), rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>>
  45:        0x10cfe2eac - <<std[65552bf0469df9ea]::thread::Builder>::spawn_unchecked_<rustc_interface[c450773bf3cb492f]::util::run_in_thread_pool_with_globals<rustc_interface[c450773bf3cb492f]::interface::run_compiler<core[89aff604de9e9977]::result::Result<(), rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>, rustc_driver_impl[c1a57d0e5e3d90de]::run_compiler::{closure#1}>::{closure#0}, core[89aff604de9e9977]::result::Result<(), rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[89aff604de9e9977]::result::Result<(), rustc_span[8eaa967f211a7d38]::ErrorGuaranteed>>::{closure#1} as core[89aff604de9e9977]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:        0x104bf92ec - std::sys::unix::thread::Thread::new::thread_start::hcef86bdbdc3976e3
  47:        0x19e1a7fa8 - __pthread_joiner_wake

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f6bc5d25 2023-05-09) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=3 -C panic=abort -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_shims] generating MIR shim for `core::ptr::drop_in_place`
#1 [optimized_mir] optimizing MIR for `vec::ops::<impl at /Users/calebjasik-defined/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitvec-0.19.6/src/vec/ops.rs:141:1: 141:33>::drop::{closure#0}`
end of query stack
error: could not compile `bitvec` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `samply v0.11.0`, intermediate artifacts can be found at `/var/folders/6m/bb4xw4d52dv97pcs4269jdfc0000gn/T/cargo-installFoiwvl`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo install samply
    Updating crates.io index
  Installing samply v0.11.0
    Updating crates.io index
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling memchr v2.5.0
   Compiling syn v1.0.109
   Compiling cc v1.0.79
   Compiling byteorder v1.4.3
   Compiling pin-project-lite v0.2.10
   Compiling futures-core v0.3.28
   Compiling hashbrown v0.12.3
   Compiling thiserror v1.0.43
   Compiling bytes v1.4.0
   Compiling itoa v1.0.9
   Compiling indexmap v1.9.3
   Compiling serde v1.0.171
   Compiling tokio v1.29.1
   Compiling untrusted v0.7.1
   Compiling crc32fast v1.3.2
   Compiling quote v1.0.31
   Compiling syn v2.0.26
   Compiling ring v0.16.20
   Compiling once_cell v1.18.0
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.7.1
   Compiling mio v0.8.8
   Compiling socket2 v0.4.9
   Compiling num_cpus v1.16.0
   Compiling slab v0.4.8
   Compiling futures-task v0.3.28
   Compiling stable_deref_trait v1.2.0
   Compiling bitflags v1.3.2
   Compiling flate2 v1.0.26
   Compiling tracing-core v0.1.31
   Compiling futures-sink v0.3.28
   Compiling fallible-iterator v0.2.0
   Compiling fnv v1.0.7
   Compiling unicode-xid v0.2.4
   Compiling futures-util v0.3.28
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling http v0.2.9
   Compiling tracing v0.1.37
   Compiling errno v0.3.1
   Compiling num-traits v0.2.15
   Compiling rustls v0.21.5
   Compiling percent-encoding v2.3.0
   Compiling uuid v1.4.1
   Compiling httparse v1.8.0
   Compiling build_const v0.2.2
   Compiling alloc-no-stdlib v2.0.4
   Compiling ryu v1.0.15
   Compiling log v0.4.19
   Compiling futures-io v0.3.28
   Compiling futures-channel v0.3.28
   Compiling pin-utils v0.1.0
   Compiling alloc-stdlib v0.2.2
   Compiling crc v1.8.1
   Compiling form_urlencoded v1.2.0
   Compiling unicode-normalization v0.1.22
   Compiling radium v0.5.3
   Compiling try-lock v0.2.4
   Compiling rustix v0.38.4
   Compiling synstructure v0.12.6
   Compiling smallvec v1.11.0
   Compiling unicode-bidi v0.3.13
   Compiling inplace-vec-builder v0.1.1
   Compiling idna v0.4.0
   Compiling want v0.3.1
   Compiling brotli-decompressor v2.3.4
   Compiling thiserror-impl v1.0.43
   Compiling serde_derive v1.0.171
   Compiling tokio-macros v2.1.0
   Compiling futures-macro v0.3.28
   Compiling http-body v0.4.5
   Compiling gimli v0.27.3
   Compiling aho-corasick v1.0.2
   Compiling zerocopy-derive v0.3.2
   Compiling rustls-webpki v0.101.1
   Compiling sct v0.7.0
   Compiling zerocopy v0.6.1
   Compiling zerofrom-derive v0.1.2
   Compiling tokio-util v0.7.8
   Compiling serde_json v1.0.103
   Compiling h2 v0.3.20
   Compiling binary-merge v0.1.2
   Compiling httpdate v1.0.2
   Compiling scroll v0.11.0
   Compiling tower-service v0.3.2
   Compiling regex-syntax v0.7.4
   Compiling bitflags v2.3.3
   Compiling cpp_demangle v0.4.2
   Compiling pdb v0.8.0
   Compiling range-collections v0.2.4
   Compiling zerofrom v0.1.2
   Compiling tokio-rustls v0.24.1
   Compiling macho-unwind-info v0.3.0
   Compiling webpki v0.22.0
   Compiling hyper v0.14.27
   Compiling regex-automata v0.3.3
   Compiling yoke-derive v0.6.1
   Compiling brotli v3.3.4
   Compiling url v2.4.0
   Compiling yaxpeax-arch v0.2.7
   Compiling debugid v0.8.0
   Compiling elsa v1.8.1
   Compiling getrandom v0.2.10
   Compiling minimal-lexical v0.2.1
   Compiling time-core v0.1.1
   Compiling utf8parse v0.2.1
   Compiling funty v1.1.0
   Compiling io-lifetimes v1.0.11
   Compiling tap v1.0.1
   Compiling base64 v0.21.2
   Compiling wyz v0.2.0
   Compiling yaxpeax-x86 v1.1.5
   Compiling maybe-owned v0.3.4
   Compiling pdb-addr2line v0.10.4
   Compiling rustls-pemfile v1.0.3
   Compiling bitvec v0.19.6
   Compiling anstyle-parse v0.2.1
   Compiling time v0.3.23
   Compiling nom v7.1.3
   Compiling rand_core v0.6.4
   Compiling async-compression v0.4.1
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:195:90: Failed to normalize alloc::raw_vec::RawVec<<T as store::BitStore>::Mem>, maybe try to call `try_normalize_erasing_regions` instead

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f6bc5d259e7ab25ddfdd33de53b892770218918/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::HandlerInner>::bug::<alloc::string::String>
   2: <rustc_errors::Handler>::bug::<alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_ty
   8: <core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::FieldDef>>, <rustc_mir_dataflow::elaborate_drops::DropCtxt<rustc_mir_transform::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<(rustc_middle::mir::syntax::Place, core::option::Option<()>), <alloc::vec::Vec<(rustc_middle::mir::syntax::Place, core::option::Option<()>)>>::extend_trusted<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::FieldDef>>, <rustc_mir_dataflow::elaborate_drops::DropCtxt<rustc_mir_transform::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}>>::{closure#0}>::{closure#0}>
   9: <alloc::vec::Vec<(rustc_middle::mir::syntax::Place, core::option::Option<()>)> as alloc::vec::spec_from_iter::SpecFromIter<(rustc_middle::mir::syntax::Place, core::option::Option<()>), core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<rustc_middle::ty::FieldDef>>, <rustc_mir_dataflow::elaborate_drops::DropCtxt<rustc_mir_transform::shim::DropShimElaborator>>::move_paths_for_fields::{closure#0}>>>::from_iter
  10: <rustc_mir_dataflow::elaborate_drops::DropCtxt<rustc_mir_transform::shim::DropShimElaborator>>::open_drop_for_adt
  11: <rustc_mir_dataflow::elaborate_drops::DropCtxt<rustc_mir_transform::shim::DropShimElaborator>>::elaborate_drop
  12: rustc_mir_transform::shim::make_shim
  13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::mir_shims, rustc_query_impl::plumbing::QueryCtxt>
  14: rustc_query_impl::get_query::mir_shims
  15: <rustc_middle::ty::context::TyCtxt>::instance_mir
  16: <rustc_mir_transform::inline::Inliner>::try_inlining
  17: <rustc_mir_transform::inline::Inliner>::process_blocks
  18: <rustc_mir_transform::inline::Inliner>::process_blocks
  19: <rustc_mir_transform::inline::Inline as rustc_middle::mir::MirPass>::run_pass
  20: rustc_mir_transform::pass_manager::run_passes_inner
  21: rustc_mir_transform::optimized_mir
  22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::optimized_mir, rustc_query_impl::plumbing::QueryCtxt>
  23: rustc_query_impl::get_query::optimized_mir
  24: rustc_middle::ty::query::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
  25: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  26: rustc_metadata::rmeta::encoder::encode_metadata_impl
  27: rustc_data_structures::sync::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  28: rustc_metadata::rmeta::encoder::encode_metadata
  29: rustc_metadata::fs::encode_and_write_metadata
  30: rustc_interface::passes::start_codegen
  31: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
  32: <rustc_interface::queries::Queries>::ongoing_codegen
  33: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (2f6bc5d25 2023-05-09) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C opt-level=3 -C panic=abort -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_shims] generating MIR shim for `core::ptr::drop_in_place`
#1 [optimized_mir] optimizing MIR for `vec::ops::<impl at /Users/calebjasik-defined/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitvec-0.19.6/src/vec/ops.rs:141:1: 141:33>::drop::{closure#0}`
end of query stack
error: could not compile `bitvec` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `samply v0.11.0`, intermediate artifacts can be found at `/var/folders/6m/bb4xw4d52dv97pcs4269jdfc0000gn/T/cargo-installf0ojIt````

</p>
</details>

**Comment by jasikpark** [comment]
strangely I can build the project locally, the issue only occurs when I try to "install" the crate. `cargo build` works fine with a local clone.

**Comment by asquared31415** [comment]
This is a two month old nightly, and the error does not reproduce on my machine.  Does this occur for you on a more updated version?

**Comment by jasikpark** [comment]
eh, on 

```
❯ rustc --version -v
rustc 1.73.0-nightly (0e8e857b1 2023-07-16)
binary: rustc
commit-hash: 0e8e857b11f60a785aea24a84f280f6dad7a4d42
commit-date: 2023-07-16
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

it doesn't repro, so fair. I'll close :p
