### ISSUE TITLE
Panic inside a function that is called by CreateThread cause STATUS_STACK_BUFFER_OVERRUN on Windows

### ISSUE THREAD

**Issue by ultimaweapon** [rust-lang/rust#114680]
I tried this code:

```rust
use std::ffi::c_void;
use std::ptr::{null, null_mut};
use windows_sys::Win32::Foundation::WAIT_OBJECT_0;
use windows_sys::Win32::System::Threading::{CreateThread, WaitForSingleObject, INFINITE};

fn main() {
    let thr = unsafe { CreateThread(null(), 0, Some(thread_routine), null(), 0, null_mut()) };

    assert_ne!(thr, 0);
    assert_eq!(unsafe { WaitForSingleObject(thr, INFINITE) }, WAIT_OBJECT_0);
}

unsafe extern "system" fn thread_routine(_: *mut c_void) -> u32 {
    panic!("this will cause stack overrun");
}
```

I expected to see this happen: it should not cause `STATUS_STACK_BUFFER_OVERRUN` on Windows.

Instead, this happened:

```
thread '<unnamed>' panicked at 'this will cause stack overrun', src\main.rs:14:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\panic-overrun.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

### Meta

`rustc --version --verbose`:

```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-pc-windows-msvc
release: 1.71.1
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: panic_overrun::thread_routine
             at .\src\main.rs:14
   3: BaseThreadInitThunk
   4: RtlUserThreadStart
```

</p>
</details>

**Comment by saethlin** [comment]
Unless you compiled with `panic = "abort"`, this is an example of unwinding across FFI, which is UB. Technically I think the current wording is that you are unwinding across the wrong ABI, but the point is that you need to either compile without unwinding or do what the standard library does and catch the unwind before you unwind out of the thread: https://github.com/rust-lang/rust/blob/08d00b40aef2017fe6dba3ff7d6476efa0c10888/library/std/src/thread/mod.rs#L528-L530

**Comment by erikdesjardins** [comment]
Note that the same thing happens when unwinding out of a thread start function in C++, e.g.

```cpp
#include <windows.h>

DWORD WINAPI ThreadRoutine(LPVOID lpParam) {
    throw 0;
}

int main() {
    CreateThread(0, 0, ThreadRoutine, 0, 0, 0);
    Sleep(INFINITE);
}
```

results in

```
> test.exe || echo %errorlevel%
-1073740791
```
(`-1073740791 == 0xc0000409`)

I assume this is just the error code Windows uses when aborting a process in this situation.

**Comment by ultimaweapon** [comment]
The problem is even `panic = "abort"` it is still having this issue. Here is the repository for example code: https://github.com/ultimaweapon/panic-overrun

**Comment by ultimaweapon** [comment]
Tried with the release built also causing the same issue:

```
    Finished release [optimized] target(s) in 0.05s
     Running `target\release\panic-overrun.exe`
thread '<unnamed>' panicked at 'this will cause stack overrun', src\main.rs:14:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: std::rt::lang_start::{{closure}}
   3: BaseThreadInitThunk
   4: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\panic-overrun.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by ultimaweapon** [comment]
I think I found the problem now. Actually `0xc0000409` here is not `STATUS_STACK_BUFFER_OVERRUN` but [STATUS_FAIL_FAST_EXCEPTION](https://learn.microsoft.com/en-us/shows/inside/c0000409), which is caused by https://github.com/rust-lang/rust/blob/1.71.1/library/panic_abort/src/lib.rs#L70. That mean `panic = "abort"` working as expected.
