### ISSUE TITLE
ICE: Panic on absence of crate dependency

### ISSUE THREAD

**Issue by zenakl** [rust-lang/rust#114603]
### Code

`fn main() {}`

### Meta

`Cargo.toml`:
```
[package]
name = "sea-orm-bakery-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
sea-orm = { version = "^0.9.0", features = ["sqlx-sqlite", "runtime-async-std-native-tls", "macros"] }
```

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (f3623871c 2023-08-06)
binary: rustc
commit-hash: f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f
commit-date: 2023-08-06
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

```
Compiling sqlx v0.6.3
error: libssl.so.3: cannot open shared object file: No such file or directory
  --> /home/elijahdl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-0.6.3/src/lib.rs:67:1
   |
67 | pub extern crate sqlx_macros;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved imports `self::encode::Encode`, `self::decode::Decode`, `super::Decode`, `super::Encode`, `super::FromRow`, `super::Type`
   --> /home/elijahdl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-0.6.3/src/lib.rs:126:9
    |
126 | pub use self::encode::Encode;
    |         ^^^^^^^^^^^^^^^^^^^^
...
137 | pub use self::decode::Decode;
    |         ^^^^^^^^^^^^^^^^^^^^
...
151 |     pub use super::Decode;
    |             ^^^^^^^^^^^^^
152 |     pub use super::Encode;
    |             ^^^^^^^^^^^^^
153 |     pub use super::Executor;
154 |     pub use super::FromRow;
    |             ^^^^^^^^^^^^^^
...
158 |     pub use super::Type;
    |             ^^^^^^^^^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_resolve/src/lib.rs:1936:67:
internal error: entered unreachable code
stack backtrace:
   0:     0x7fe92351313c - std::backtrace_rs::backtrace::libunwind::trace::h22168c2758bad779
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe92351313c - std::backtrace_rs::backtrace::trace_unsynchronized::h8476c2ea3d84df47
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe92351313c - std::sys_common::backtrace::_print_fmt::hc9d29f1e517659f2
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fe92351313c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfaecf1789d8251aa
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fe92357983c - core::fmt::rt::Argument::fmt::h3b1f75374549a851
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/core/src/fmt/rt.rs:138:9
   5:     0x7fe92357983c - core::fmt::write::ha58f724e2b02bd3c
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fe9235058be - std::io::Write::write_fmt::hfaf8c46440fd7330
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/io/mod.rs:1714:15
   7:     0x7fe923512f25 - std::sys_common::backtrace::_print::ha65ab5537514f9a9
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fe923512f25 - std::sys_common::backtrace::print::h13679488dfb9eeec
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fe92351607a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h9cc69701f7e62906
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/panicking.rs:278:22
  10:     0x7fe923515d13 - std::panicking::panic_hook_with_disk_dump::h1978dc23604bc33d
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/panicking.rs:312:9
  11:     0x7fe92682c139 - rustc_driver_impl[c4790404c9758816]::install_ice_hook::{closure#0}
  12:     0x7fe923516920 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h46bb285d00152433
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/alloc/src/boxed.rs:2021:9
  13:     0x7fe923516920 - std::panicking::rust_panic_with_hook::h8b5176c817ebcabe
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/panicking.rs:733:13
  14:     0x7fe923516661 - std::panicking::begin_panic_handler::{{closure}}::hb49b3fe12db5ce29
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/panicking.rs:619:13
  15:     0x7fe923513676 - std::sys_common::backtrace::__rust_end_short_backtrace::he672dbe87f4a1cec
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7fe9235163f2 - rust_begin_unwind
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/panicking.rs:617:5
  17:     0x7fe923575bf3 - core::panicking::panic_fmt::hee8b5b930a85defe
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/core/src/panicking.rs:67:14
  18:     0x7fe923575c83 - core::panicking::panic::h9766d79ff6b7d450
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/core/src/panicking.rs:117:5
  19:     0x7fe92586f70d - <rustc_resolve[528a8bd54b7a5b24]::Resolver>::resolve_rustdoc_path
  20:     0x7fe92586eeea - <rustc_resolve[528a8bd54b7a5b24]::late::LateResolutionVisitor>::resolve_and_cache_rustdoc_path
  21:     0x7fe92586b245 - <rustc_resolve[528a8bd54b7a5b24]::late::LateResolutionVisitor>::resolve_doc_links
  22:     0x7fe925854840 - <rustc_resolve[528a8bd54b7a5b24]::late::LateResolutionVisitor>::resolve_item
  23:     0x7fe92585469e - <rustc_resolve[528a8bd54b7a5b24]::late::LateResolutionVisitor as rustc_ast[e85a96ff05be66fe]::visit::Visitor>::visit_item
  24:     0x7fe9258ea47c - <rustc_resolve[528a8bd54b7a5b24]::Resolver>::late_resolve_crate
  25:     0x7fe9258e5c15 - <rustc_session[691ca45f8e594827]::session::Session>::time::<(), <rustc_resolve[528a8bd54b7a5b24]::Resolver>::resolve_crate::{closure#0}>
  26:     0x7fe9258deb6a - rustc_interface[4410acd2651976fa]::passes::resolver_for_lowering
  27:     0x7fe925d18faa - rustc_query_impl[8cbc122abe1fe035]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8cbc122abe1fe035]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[9a2a8fa8673391f8]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7fe925d18f99 - <rustc_query_impl[8cbc122abe1fe035]::query_impl::resolver_for_lowering::dynamic_query::{closure#2} as core[4482a52a083d446a]::ops::function::FnOnce<(rustc_middle[9a2a8fa8673391f8]::ty::context::TyCtxt, ())>>::call_once
  29:     0x7fe925c6e6bc - rustc_query_system[e2c1d99569e6ed22]::query::plumbing::try_execute_query::<rustc_query_impl[8cbc122abe1fe035]::DynamicConfig<rustc_query_system[e2c1d99569e6ed22]::query::caches::SingleCache<rustc_middle[9a2a8fa8673391f8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[8cbc122abe1fe035]::plumbing::QueryCtxt, false>
  30:     0x7fe9261843c5 - rustc_query_impl[8cbc122abe1fe035]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7fe925a907f3 - <rustc_middle[9a2a8fa8673391f8]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[c4790404c9758816]::run_compiler::{closure#1}::{closure#2}::{closure#3}, &rustc_data_structures[53507b9ced03dbf9]::steal::Steal<(rustc_middle[9a2a8fa8673391f8]::ty::ResolverAstLowering, alloc[c531b2b407e8df49]::rc::Rc<rustc_ast[e85a96ff05be66fe]::ast::Crate>)>>
  32:     0x7fe925a8f396 - rustc_span[96fca95c4a579b36]::set_source_map::<core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>, rustc_interface[4410acd2651976fa]::interface::run_compiler<core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>, rustc_driver_impl[c4790404c9758816]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  33:     0x7fe925a89650 - std[88224629d68ee256]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4410acd2651976fa]::util::run_in_thread_pool_with_globals<rustc_interface[4410acd2651976fa]::interface::run_compiler<core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>, rustc_driver_impl[c4790404c9758816]::run_compiler::{closure#1}>::{closure#0}, core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>>
  34:     0x7fe925a88fae - <<std[88224629d68ee256]::thread::Builder>::spawn_unchecked_<rustc_interface[4410acd2651976fa]::util::run_in_thread_pool_with_globals<rustc_interface[4410acd2651976fa]::interface::run_compiler<core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>, rustc_driver_impl[c4790404c9758816]::run_compiler::{closure#1}>::{closure#0}, core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4482a52a083d446a]::result::Result<(), rustc_span[96fca95c4a579b36]::ErrorGuaranteed>>::{closure#1} as core[4482a52a083d446a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7fe9235210c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0a7d0f33a919d12d
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/alloc/src/boxed.rs:2007:9
  36:     0x7fe9235210c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfe447ac19e329dd1
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/alloc/src/boxed.rs:2007:9
  37:     0x7fe9235210c5 - std::sys::unix::thread::Thread::new::thread_start::hba6b7b003de99fc6
                               at /rustc/f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7fe9232b4dd4 - start_thread
  39:     0x7fe9233369b0 - __clone3
  40:                0x0 - <unknown>
```

</p>
</details>

**Comment by bvanjoi** [comment]
Does everything work fine after running ﻿`cargo clean`? I'm unable to reproduce the issue on my end.

**Comment by elijahdl** [comment]
I don't see any changes in behavior after running `cargo clean`. I spun up a fresh Ubuntu 23.04 VM to test and was also not able to reproduce the issue there.

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
