### ISSUE TITLE
hread 'rustc' panicked at 'index out of bounds: the len is 1389811 but the index is 1826700', /rustc

### ISSUE THREAD

**Issue by John-Nagle** [rust-lang/rust#115036]
### Code

```
cargo test
```
of a large program that just passed "cargo test" before a comment change. Failure repeatable three times.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0 (8ede3aae2 2023-07-12)
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'index out of bounds: the len is 1389811 but the index is 1826700', /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/compiler/rustc_query_system/src/dep_graph/graph.rs:1399:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5
   3: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   4: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl::plumbing::QueryCtxt>
   5: rustc_query_impl::plumbing::try_mark_green
   6: rustc_codegen_ssa::base::determine_cgu_reuse
   7: <alloc::vec::Vec<rustc_session::cgu_reuse_tracker::CguReuse> as alloc::vec::spec_from_iter::SpecFromIter<rustc_session::cgu_reuse_tracker::CguReuse, core::iter::adapters::map::Map<core::slice::iter::Iter<&rustc_middle::mir::mono::CodegenUnit>, rustc_codegen_ssa::base::codegen_crate<rustc_codegen_llvm::LlvmCodegenBackend>::{closure#3}::{closure#0}>>>::from_iter
   8: <rustc_session::session::Session>::time::<alloc::vec::Vec<rustc_session::cgu_reuse_tracker::CguReuse>, rustc_codegen_ssa::base::codegen_crate<rustc_codegen_llvm::LlvmCodegenBackend>::{closure#3}>
   9: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  10: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  12: rustc_interface::passes::start_codegen
  13: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
  14: <rustc_interface::queries::Queries>::ongoing_codegen
  15: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0 (8ede3aae2 2023-07-12) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

```

</p>
</details>

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by John-Nagle** [comment]
Tried **cargo clean**, then **cargo test**. No problems.

I've been encountering other problems lately, which seem to be related to which configuration of the program was built most recently.  I have a test profile

```
#   Use to enable extra checking. Too slow for production.
[profile.checkedrelease]
inherits = "release"
debug-assertions = true
```
and I've had intermittent linker errors [(see here) ](https://users.rust-lang.org/t/dilocations-scope-must-be-a-dilocalscope/98611)
A **cargo clean** fixed that. I suspect some problem involving the mechanism that decides what can reused in the next compile.

**Comment by darklyspaced** [comment]
Could you create a MRE for this panic. Failing that, atleast provide a link to _some_ code that exhibits this behaviour. Without code, there's not really much we can do in the way of solving this issue.

**Comment by John-Nagle** [comment]
> Could you create a MRE for this panic?

No. It happens with a large non-public project, and isn't repeatable after a **cargo clean**.
The compiler's error message said to file a bug report, so I did.
However, click on "Backtrace" in the bug report for the full backtrace from the panic.

This seems to be related to **determine_cgu_reuse**, which is in the backtrace. The error is in the dependency graph machinery. So the hypothesis that this has something to do with the machinery to decide what can be reused from previous compilations becomes more likely.

That's something for which a a minimal, reproducible example is not a small block of code, it's a complex project.

**Comment by Nilstrieb** [comment]
Closing this issue as unactionable. If you can provide a reproduction, we can re-open the issue, but without one, there is nothing we can do.
