### ISSUE TITLE
ICE when using `rustc_layout_scalar_valid_range_start` on newtype wrapper for `f64`

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust#115383]
### Code

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5b4996044f6a479d545f82dc64513a72))

```Rust
#![allow(internal_features)]
#![feature(rustc_attrs)]

#[repr(transparent)]
#[rustc_layout_scalar_valid_range_start(0b01)]
pub struct NonZeroF64(f64);

impl NonZeroF64 {
    pub fn new(_: f64) -> Option<Self> {
        None
    }
}
```

### Meta

`rustc -Vv`:
```
rustc 1.74.0-nightly (84a9f4c6e 2023-08-29)
binary: rustc
commit-hash: 84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc
commit-date: 2023-08-29
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

### Error output

```
error: internal compiler error: /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/compiler/rustc_middle/src/ty/layout.rs:153:26: floats do not have an int type

thread 'rustc' panicked at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/compiler/rustc_errors/src/lib.rs:1649:9:
Box<dyn Any>
...

note: please attach the file at `/home/patchmixolydic/tmp/ice/rustc-ice-2023-08-30T14:10:27.151163782Z-131103.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_drops_elaborated_and_const_checked] elaborating drops for `<impl at src/lib.rs:8:1: 8:16>::new`
#1 [analysis] running analysis passes on this crate
end of query stack

```

[rustc-ice-2023-08-30T14:10:27.151163782Z-131103.txt](https://github.com/rust-lang/rust/files/12476552/rustc-ice-2023-08-30T14.10.27.151163782Z-131103.txt)

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f284376316c - std::backtrace_rs::backtrace::libunwind::trace::h61d1a4bd3109c00e
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f284376316c - std::backtrace_rs::backtrace::trace_unsynchronized::he518998f6a608159
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f284376316c - std::sys_common::backtrace::_print_fmt::hfead36a99a75e763
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f284376316c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha2708bb72e7f985d
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f28437c941c - core::fmt::rt::Argument::fmt::h2a27ae88ff3f4924
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/core/src/fmt/rt.rs:138:9
   5:     0x7f28437c941c - core::fmt::write::h2a16d40804e2a731
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f2843755c8e - std::io::Write::write_fmt::h2bf46c81d834f7f3
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/io/mod.rs:1714:15
   7:     0x7f2843762f54 - std::sys_common::backtrace::_print::h96307086da4a78fa
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2843762f54 - std::sys_common::backtrace::print::h8ad121c6fc896da9
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f284376604a - std::panicking::panic_hook_with_disk_dump::{{closure}}::hc5cfa8f93853cb88
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/panicking.rs:280:22
  10:     0x7f2843765d45 - std::panicking::panic_hook_with_disk_dump::h1b945c35c11dc8e8
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/panicking.rs:314:9
  11:     0x7f2846933f29 - <rustc_driver_impl[71850d8a3633fbf4]::install_ice_hook::{closure#0} as core[286ef9e24d139666]::ops::function::FnOnce<(&core[286ef9e24d139666]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f2843766913 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7aca6fdfb88c36b5
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/alloc/src/boxed.rs:2021:9
  13:     0x7f2843766913 - std::panicking::rust_panic_with_hook::h2a2cdfd872929be4
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/panicking.rs:757:13
  14:     0x7f2846e8b964 - std[37c8f93d4d1a65f0]::panicking::begin_panic::<rustc_errors[31b91d9874feddd3]::ExplicitBug>::{closure#0}
  15:     0x7f2846e89946 - std[37c8f93d4d1a65f0]::sys_common::backtrace::__rust_end_short_backtrace::<std[37c8f93d4d1a65f0]::panicking::begin_panic<rustc_errors[31b91d9874feddd3]::ExplicitBug>::{closure#0}, !>
  16:     0x7f2846e625e6 - std[37c8f93d4d1a65f0]::panicking::begin_panic::<rustc_errors[31b91d9874feddd3]::ExplicitBug>
  17:     0x7f2846e65c34 - <rustc_errors[31b91d9874feddd3]::HandlerInner>::bug::<alloc[2645bf60e9ad0a21]::string::String>
  18:     0x7f2846e65ac6 - <rustc_errors[31b91d9874feddd3]::Handler>::bug::<alloc[2645bf60e9ad0a21]::string::String>
  19:     0x7f2846e4e09c - rustc_middle[1a63a2327586df1a]::util::bug::opt_span_bug_fmt::<rustc_span[9c9e3a6892bfa89d]::span_encoding::Span>::{closure#0}
  20:     0x7f2846e4bafa - rustc_middle[1a63a2327586df1a]::ty::context::tls::with_opt::<rustc_middle[1a63a2327586df1a]::util::bug::opt_span_bug_fmt<rustc_span[9c9e3a6892bfa89d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f2846e4bac8 - rustc_middle[1a63a2327586df1a]::ty::context::tls::with_context_opt::<rustc_middle[1a63a2327586df1a]::ty::context::tls::with_opt<rustc_middle[1a63a2327586df1a]::util::bug::opt_span_bug_fmt<rustc_span[9c9e3a6892bfa89d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f28450a2ab0 - rustc_middle[1a63a2327586df1a]::util::bug::bug_fmt
  23:     0x7f28459aef22 - <rustc_const_eval[d250f3f314c91ee6]::interpret::eval_context::InterpCx<rustc_mir_transform[8888f36f91abdfa2]::const_prop::ConstPropMachine>>::write_discriminant::<rustc_const_eval[d250f3f314c91ee6]::interpret::place::PlaceTy>
  24:     0x7f2845998a2b - <rustc_const_eval[d250f3f314c91ee6]::interpret::eval_context::InterpCx<rustc_mir_transform[8888f36f91abdfa2]::const_prop::ConstPropMachine>>::eval_rvalue_into_place
  25:     0x7f284598d1a1 - <rustc_mir_transform[8888f36f91abdfa2]::const_prop_lint::ConstPropagator as rustc_middle[1a63a2327586df1a]::mir::visit::Visitor>::visit_body
  26:     0x7f2845982aba - <rustc_mir_transform[8888f36f91abdfa2]::const_prop_lint::ConstProp as rustc_mir_transform[8888f36f91abdfa2]::pass_manager::MirLint>::run_lint
  27:     0x7f28451bafe2 - rustc_mir_transform[8888f36f91abdfa2]::mir_drops_elaborated_and_const_checked
  28:     0x7f2844a6e97e - rustc_query_impl[1e991c6cf370c708]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1e991c6cf370c708]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a63a2327586df1a]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f2844a6e94e - <rustc_query_impl[1e991c6cf370c708]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2} as core[286ef9e24d139666]::ops::function::FnOnce<(rustc_middle[1a63a2327586df1a]::ty::context::TyCtxt, rustc_span[9c9e3a6892bfa89d]::def_id::LocalDefId)>>::call_once
  30:     0x7f28450d7e4d - rustc_query_system[96ad6fdd1cc0785a]::query::plumbing::try_execute_query::<rustc_query_impl[1e991c6cf370c708]::DynamicConfig<rustc_query_system[96ad6fdd1cc0785a]::query::caches::VecCache<rustc_span[9c9e3a6892bfa89d]::def_id::LocalDefId, rustc_middle[1a63a2327586df1a]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1e991c6cf370c708]::plumbing::QueryCtxt, true>
  31:     0x7f28462b617e - rustc_query_impl[1e991c6cf370c708]::query_impl::mir_drops_elaborated_and_const_checked::get_query_incr::__rust_end_short_backtrace
  32:     0x7f28458fa153 - <rustc_session[c0512886684aa266]::session::Session>::time::<(), rustc_interface[772c657f70775e43]::passes::analysis::{closure#2}>
  33:     0x7f28458f7bf5 - rustc_interface[772c657f70775e43]::passes::analysis
  34:     0x7f2845e4d34a - rustc_query_impl[1e991c6cf370c708]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1e991c6cf370c708]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1a63a2327586df1a]::query::erase::Erased<[u8; 1usize]>>
  35:     0x7f2845e4d339 - <rustc_query_impl[1e991c6cf370c708]::query_impl::analysis::dynamic_query::{closure#2} as core[286ef9e24d139666]::ops::function::FnOnce<(rustc_middle[1a63a2327586df1a]::ty::context::TyCtxt, ())>>::call_once
  36:     0x7f284612b8db - rustc_query_system[96ad6fdd1cc0785a]::query::plumbing::try_execute_query::<rustc_query_impl[1e991c6cf370c708]::DynamicConfig<rustc_query_system[96ad6fdd1cc0785a]::query::caches::SingleCache<rustc_middle[1a63a2327586df1a]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1e991c6cf370c708]::plumbing::QueryCtxt, true>
  37:     0x7f284612b434 - rustc_query_impl[1e991c6cf370c708]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  38:     0x7f2845c1f096 - <rustc_middle[1a63a2327586df1a]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[71850d8a3633fbf4]::run_compiler::{closure#1}::{closure#2}::{closure#6}, core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>>
  39:     0x7f2845c1e4dd - <rustc_interface[772c657f70775e43]::interface::Compiler>::enter::<rustc_driver_impl[71850d8a3633fbf4]::run_compiler::{closure#1}::{closure#2}, core[286ef9e24d139666]::result::Result<core[286ef9e24d139666]::option::Option<rustc_interface[772c657f70775e43]::queries::Linker>, rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>>
  40:     0x7f2845c1b7f8 - std[37c8f93d4d1a65f0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[772c657f70775e43]::util::run_in_thread_pool_with_globals<rustc_interface[772c657f70775e43]::interface::run_compiler<core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>, rustc_driver_impl[71850d8a3633fbf4]::run_compiler::{closure#1}>::{closure#0}, core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>>
  41:     0x7f2845c1af6e - <<std[37c8f93d4d1a65f0]::thread::Builder>::spawn_unchecked_<rustc_interface[772c657f70775e43]::util::run_in_thread_pool_with_globals<rustc_interface[772c657f70775e43]::interface::run_compiler<core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>, rustc_driver_impl[71850d8a3633fbf4]::run_compiler::{closure#1}>::{closure#0}, core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[286ef9e24d139666]::result::Result<(), rustc_span[9c9e3a6892bfa89d]::ErrorGuaranteed>>::{closure#1} as core[286ef9e24d139666]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7f2843771375 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hed13213514545239
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/alloc/src/boxed.rs:2007:9
  43:     0x7f2843771375 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h62608fdaa8326b29
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/alloc/src/boxed.rs:2007:9
  44:     0x7f2843771375 - std::sys::unix::thread::Thread::new::thread_start::h4177969e7d75fa4e
                               at /rustc/84a9f4c6e6f0f02bff9acc9a5e0305a1554a87fc/library/std/src/sys/unix/thread.rs:108:17
  45:     0x7f284350cfd4 - start_thread
                               at ./nptl/pthread_create.c:442:8
  46:     0x7f284358d5bc - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  47:                0x0 - <unknown>
```

</p>
</details>

### More information
From the error message, it seems like this ICE may be an intentional reaction to using `rustc_layout_scalar_valid_range_start` on an `f64`. If this is the case, it would be nicer to emit a regular diagnostic here instead:
```
error: `rustc_layout_scalar_valid_range_start` can only be used on integer wrappers
 --> src/lib.rs:6:22
  |
5 | #[rustc_layout_scalar_valid_range_start(0b01)]
  |   -------------------------------------
6 | pub struct NonZeroF64(f64);
  |                       ^^^ not an integer
  |
```

Also, this ICE was only emitted when returning an `Option<NonZeroF64>` from a function. The following did not cause the ICE:
* Deriving `Clone`, `Copy`, and `Debug`
* Implementing `Hash` in terms of `f64::to_bits` (this was originally a non-NaN type with a niche that covered all positive NaNs; it was changed to non-zero to rule out a bug in wrapping valid ranges)
* Implementing `Default` (and, more generally, defining a function that just returns `NonZeroF64`)
* Replacing the body of `NonZeroF64::new` with `todo!()`

@rustbot modify labels +requires-nightly +requires-internal-features +F-rustc_attrs

**Comment by Nilstrieb** [comment]
rustc_attrs are not supported. Mistakes may lead to ICEs, this is intended.
