### ISSUE TITLE
Executing `./src/ci/docker/run.sh x86_64-gnu` raises errors

### ISSUE THREAD

**Issue by gemesa** [rust-lang/rust#115316]
I tried this code:

```
git clone git@github.com:rust-lang/rust.git
cd rust/src/ci/docker
./run.sh x86_64-gnu
```

I expected to see this happen: image is built and executed

Instead, this happened:

```
...
   Compiling build_helper v0.1.0 (/checkout/src/tools/build_helper)
    Finished dev [unoptimized] target(s) in 32.03s
error: manifest path `/checkout/src/tools/cargo/Cargo.toml` does not exist
thread 'main' panicked at metadata.rs:86:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml"
expected success, got: exit status: 101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:50
make: *** [Makefile:58: prepare] Error 1
Command failed. Attempt 2/5:
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.06s
error: manifest path `/checkout/src/tools/cargo/Cargo.toml` does not exist
thread 'main' panicked at metadata.rs:86:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml"
expected success, got: exit status: 101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:58: prepare] Error 1
Command failed. Attempt 3/5:
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.05s
error: manifest path `/checkout/src/tools/cargo/Cargo.toml` does not exist
thread 'main' panicked at metadata.rs:86:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml"
expected success, got: exit status: 101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:58: prepare] Error 1
Command failed. Attempt 4/5:
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.05s
error: manifest path `/checkout/src/tools/cargo/Cargo.toml` does not exist
thread 'main' panicked at metadata.rs:86:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml"
expected success, got: exit status: 101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:58: prepare] Error 1
Command failed. Attempt 5/5:
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.05s
error: manifest path `/checkout/src/tools/cargo/Cargo.toml` does not exist
thread 'main' panicked at metadata.rs:86:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/src/tools/cargo/Cargo.toml"
expected success, got: exit status: 101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:58: prepare] Error 1
The command has failed after 5 attempts.
  local time: Mon Aug 28 14:36:11 UTC 2023
  network time: Mon, 28 Aug 2023 14:36:11 GMT
```

### Meta

the HEAD in my clone is https://github.com/rust-lang/rust/commit/9847c6406dc8182abb417b69000fcd0bc5f4a1b7

might be related to #115041 (similar error message)

**Comment by gemesa** [comment]
this was a dumb mistake on my part, i forgot to check out the submodules

```
git submodule init
git submodule update
```
