### ISSUE TITLE
Error: the compiler unexpectedly panicked (features: const_trait_impl, effects)

### ISSUE THREAD

**Issue by A1-Triard** [rust-lang/rust#115533]
I cannot provide a minimal example, but I found my project [`components-arena`]() [fails to build](https://github.com/A1-Triard/components-arena/actions/runs/6075290946/job/16481173209) with the following command: `cargo test --verbose --workspace --tests --no-default-features --features=nightly`.

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (9f5fc1bd4 2023-09-02)
binary: rustc
commit-hash: 9f5fc1bd443f59583e7af0d94d289f95fe1e20c4
commit-date: 2023-09-02
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:1182:17:
assertion `left == right` failed
  left: TypeNs("host")
 right: Ctor

error: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
assertion `left == right` failed
  left: TypeNs("host")
 right: Ctor
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/9f5fc1bd443f59583e7af0d94d289f95fe1e20c4/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<rustc_hir::definitions::DefPathData, rustc_hir::definitions::DefPathData>
   4: <rustc_metadata::creader::CrateMetadataRef>::get_item_attrs
   5: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::item_attrs
      [... omitted 2 frames ...]
   6: <rustc_middle::ty::context::TyCtxt>::has_attr::<rustc_span::def_id::DefId>
   7: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_path
   8: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_call
   9: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  10: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_call
  11: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  12: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_block_with_expected
  13: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  14: <rustc_hir_typeck::fn_ctxt::FnCtxt>::check_return_expr
  15: rustc_hir_typeck::check::check_fn
  16: rustc_hir_typeck::typeck
      [... omitted 2 frames ...]
  17: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_hir_analysis::check_crate::{closure#7}>::{closure#0}>
  18: rustc_hir_analysis::check_crate
  19: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  20: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#6}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  21: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
```

</p>
</details>

**Comment by Luk-ESC** [comment]
I worked on minimizing this for a bit but couldn't get it down to one crate for some reason. It's only 10 lines of code in total so I'm sure someone can figure it out. Here it is if anyone wants to continue: https://github.com/Luk-ESC/ice-115533

**Comment by fmease** [comment]
Thanks for the minimization! You can't possibly get it down to one crate since this bug is either located in the encoder or in the decoder of the metadata (of an external crate) leading to an ICE when decoding.

MCVE extracted from the repo:

```rs
// a.rs — rustc a.rs --crate-type=lib
#![feature(const_trait_impl, effects)]

#[const_trait]
pub trait ComponentId { fn f(); }

// b.rs — rustc b.rs --editition=2021 --extern=a=liba.rlib
fn main() {
    <() as a::ComponentId>::f();
}
```

**Comment by oli-obk** [comment]
cc @fee1-dead
