### ISSUE TITLE
`fatal runtime error: failed to initiate panic, error 3` when `catch_unwind` a `panic`

### ISSUE THREAD

**Issue by fzyzcjy** [rust-lang/rust#115906]
Hi, thanks for the great language!

The context is that, in https://github.com/fzyzcjy/flutter_rust_bridge, Dart calls Rust functions via Dart FFI and Rust FFI (indeed using C-like ABI). It worked perfectly, until one day it fails to panic, and shows "fatal runtime error: failed to initiate panic, error 3".

I briefly looked at the source code, and my first guess is that, the panic mechanism has some problem interfering with the Dart stack traces (though I do catch_unwind it, so the panic will not cross FFI boundary).

I tried this code:

`/dart/main.dart`

```dart
import 'dart:ffi' as ffi;
import 'dart:ffi';

typedef NativeRustHelloFunction = ffi.Void Function();
typedef NativeHelloFunction = void Function();

void main() {
  final dl = ffi.DynamicLibrary.open("../rust/target/debug/libhello_rust.so");
  final f = dl.lookupFunction<NativeRustHelloFunction, NativeHelloFunction>("hello_rust_function");
  f();
}
```

`/rust/lib.rs`

```rs
#[no_mangle]
pub extern "C" fn hello_rust_function() {
    // or, test backtrace capture
    // println!("hi backtrace {:?}", std::backtrace::Backtrace::force_capture());

    // either test panic
    println!("hello_rust_function start");
    let result = std::panic::catch_unwind(move || {
        println!("call panic");
        panic!("hi this is panic");
    });
    println!("hello_rust_function end {:?}", result);
}
```

`/rust/Cargo.toml`

```
[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "hello_rust"
crate-type = ["cdylib"]
```

`/run.sh`

```
#!/bin/bash
set -eux

(cd rust && cargo build)

(cd dart && dart main.dart)
```

Then just `./run.sh` and see what happens.

The bug is confirmed on multiple Linux machines.

I expected to see this happen: No errors

Instead, this happened: 

```
hello_rust_function start
call panic
thread '<unnamed>' panicked at 'hi this is panic', src/lib.rs:6:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 3
./run.sh: line 6: 17361 Aborted                 (core dumped) dart main.dart
```

Or, if uncomment the backtrace capture line of code:

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
version=3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "linux_x64"
pid=18054, thread=18062, isolate_group=main(0x5573964a15f0), isolate=main(0x5573964a3e50)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=5573943f0360, vm_instructions=5573943f0360
fp=ffffffff, sp=7f31dc3fdf10, pc=557394ac12f2
Stack dump aborted because GetAndValidateThreadStackBounds failed.
  pc 0x0000557394ac12f2 fp 0x00000000ffffffff unw_get_reg+0x72
./run.sh: line 6: 18054 Aborted                 (core dumped) dart main.dart
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

<details><summary>Backtrace</summary>
<p>

```
➜  bug git:(feat/ci-valgrind) ✗ RUST_BACKTRACE=1 ./run.sh                    
+ cd rust
+ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
+ cd dart
+ dart main.dart
hello_rust_function start
call panic
thread '<unnamed>' panicked at 'hi this is panic', src/lib.rs:6:9
stack backtrace:

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
version=3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "linux_x64"
pid=17410, thread=17418, isolate_group=main(0x55efafc5f5f0), isolate=main(0x55efafc61e50)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=55efadaa9360, vm_instructions=55efadaa9360
fp=ffffffff, sp=7fa83117d8f0, pc=55efae17a2f2
Stack dump aborted because GetAndValidateThreadStackBounds failed.
  pc 0x000055efae17a2f2 fp 0x00000000ffffffff unw_get_reg+0x72
./run.sh: line 6: 17410 Aborted                 (core dumped) dart main.dart
➜  bug git:(feat/ci-valgrind) ✗ 
```

</p>
</details>

**Comment by workingjubilee** [comment]
...you know that `println!` can panic, right? So your `catch_unwind` is incorrectly scoped. I am not expecting that to change the results, but there's a very narrow likelihood that it does.

**Comment by fzyzcjy** [comment]
Thanks! But moving that println does not change things

**Comment by bjorn3** [comment]
Is lldb able to print a backtrace? Maybe dart produces an invalid unwinding table? The crash you have is inside the system unwinder. (Please try lldb, not gdb. Gdb has some heuristics when unwinding info is missing. Lldb only parses the unwinding tables just like the system unwinder.)

**Comment by fzyzcjy** [comment]
Thank you! As is linked above, more specially https://github.com/dart-lang/sdk/issues/53545#issuecomment-1722421459, it seems that Dart does produce something buggy, so I may wait until the cherrypick and report updates.

**Comment by Enselic** [comment]
Triage: The Dart bug seems fixed? Can this still be  reproduced? Is there anything to fix on the Rust side?

**Comment by fzyzcjy** [comment]
It seems everything works well now. Thanks for asking!
