### ISSUE TITLE
ICE: unstable -Z drop-tracking + labeled loop

### ISSUE THREAD

**Issue by yhx-12243** [rust-lang/rust#116425]
### Code

```Rust
async fn f() {
	'a: {
		break 'a;
	}
}

fn main() {
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (35e416303 2023-09-01)
binary: rustc
commit-hash: 35e416303e6591a71ef6a91e006c602d2def3968
commit-date: 2023-09-01
host: aarch64-apple-darwin
release: 1.74.0-nightly
LLVM version: 17.0.0
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_hir_typeck/src/generator_interior/drop_ranges/cfg_build.rs:596:52:
Expression ID not found
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x105ca6ffc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3b47a8212d267534
   1:        0x105cfad24 - core::fmt::write::h3568b9fa05e06f22
   2:        0x105c9c9d8 - std::io::Write::write_fmt::hc2f249daeddf7a36
   3:        0x105ca6e3c - std::sys_common::backtrace::print::h972bdc54a21efc27
   4:        0x105ca9be8 - std::panicking::panic_hook_with_disk_dump::{{closure}}::h7395dd04c3a9d625
   5:        0x105ca98e8 - std::panicking::panic_hook_with_disk_dump::h356927c4d06a25b8
   6:        0x10e11687c - rustc_driver_impl[e4aee68b9a041b8f]::install_ice_hook::{closure#0}
   7:        0x105caa3f8 - std::panicking::rust_panic_with_hook::h385b971d3f076234
   8:        0x105caa1c0 - std::panicking::begin_panic_handler::{{closure}}::h0f2722d630437615
   9:        0x105ca7488 - std::sys_common::backtrace::__rust_end_short_backtrace::h940c4472fdf975e6
  10:        0x105ca9f1c - _rust_begin_unwind
  11:        0x105d25e7c - core::panicking::panic_fmt::h5456c218fd292b42
  12:        0x105d25e48 - core::option::expect_failed::h54b4542480f4c3e0
  13:        0x1108cec00 - <rustc_hir_typeck[fea4e04095231fef]::generator_interior::drop_ranges::DropRangesBuilder>::process_deferred_edges
  14:        0x11086cf0c - rustc_hir_typeck[fea4e04095231fef]::generator_interior::drop_ranges::cfg_build::build_control_flow_graph
  15:        0x1108ced4c - rustc_hir_typeck[fea4e04095231fef]::generator_interior::drop_ranges::compute_drop_ranges
  16:        0x1108502d4 - rustc_hir_typeck[fea4e04095231fef]::generator_interior::resolve_interior
  17:        0x11079d584 - <rustc_hir_typeck[fea4e04095231fef]::fn_ctxt::FnCtxt>::resolve_generator_interiors
  18:        0x1108594dc - rustc_hir_typeck[fea4e04095231fef]::typeck
  19:        0x11144e210 - rustc_query_impl[61ad5ab37aec3919]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[61ad5ab37aec3919]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>
  20:        0x11152ffa8 - <rustc_query_impl[61ad5ab37aec3919]::query_impl::typeck::dynamic_query::{closure#2} as core[2681f0f28a31b5ec]::ops::function::FnOnce<(rustc_middle[df1e6ddc13461d29]::ty::context::TyCtxt, rustc_span[7f597af770a95843]::def_id::LocalDefId)>>::call_once
  21:        0x111413fb4 - rustc_query_system[4874da2f2daebb37]::query::plumbing::try_execute_query::<rustc_query_impl[61ad5ab37aec3919]::DynamicConfig<rustc_query_system[4874da2f2daebb37]::query::caches::VecCache<rustc_span[7f597af770a95843]::def_id::LocalDefId, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[61ad5ab37aec3919]::plumbing::QueryCtxt, false>
  22:        0x1114bfb2c - rustc_query_impl[61ad5ab37aec3919]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  23:        0x110a181ac - rustc_hir_analysis[ebedbbf8cb7bd6bd]::collect::type_of::type_of_opaque
  24:        0x11144a560 - rustc_query_impl[61ad5ab37aec3919]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[61ad5ab37aec3919]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>
  25:        0x1114a8f78 - <rustc_query_impl[61ad5ab37aec3919]::query_impl::type_of_opaque::dynamic_query::{closure#2} as core[2681f0f28a31b5ec]::ops::function::FnOnce<(rustc_middle[df1e6ddc13461d29]::ty::context::TyCtxt, rustc_span[7f597af770a95843]::def_id::DefId)>>::call_once
  26:        0x1113eaa78 - rustc_query_system[4874da2f2daebb37]::query::plumbing::try_execute_query::<rustc_query_impl[61ad5ab37aec3919]::DynamicConfig<rustc_query_system[4874da2f2daebb37]::query::caches::DefaultCache<rustc_span[7f597af770a95843]::def_id::DefId, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[61ad5ab37aec3919]::plumbing::QueryCtxt, false>
  27:        0x1114af600 - rustc_query_impl[61ad5ab37aec3919]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  28:        0x110a0d024 - rustc_middle[df1e6ddc13461d29]::query::plumbing::query_get_at::<rustc_query_system[4874da2f2daebb37]::query::caches::DefaultCache<rustc_span[7f597af770a95843]::def_id::DefId, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>>
  29:        0x110a17080 - rustc_hir_analysis[ebedbbf8cb7bd6bd]::collect::type_of::type_of
  30:        0x11144e284 - rustc_query_impl[61ad5ab37aec3919]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[61ad5ab37aec3919]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>
  31:        0x1114ac0a4 - <rustc_query_impl[61ad5ab37aec3919]::query_impl::type_of::dynamic_query::{closure#2} as core[2681f0f28a31b5ec]::ops::function::FnOnce<(rustc_middle[df1e6ddc13461d29]::ty::context::TyCtxt, rustc_span[7f597af770a95843]::def_id::DefId)>>::call_once
  32:        0x1113eaa78 - rustc_query_system[4874da2f2daebb37]::query::plumbing::try_execute_query::<rustc_query_impl[61ad5ab37aec3919]::DynamicConfig<rustc_query_system[4874da2f2daebb37]::query::caches::DefaultCache<rustc_span[7f597af770a95843]::def_id::DefId, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[61ad5ab37aec3919]::plumbing::QueryCtxt, false>
  33:        0x1114af2ac - rustc_query_impl[61ad5ab37aec3919]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  34:        0x1109e7544 - rustc_middle[df1e6ddc13461d29]::query::plumbing::query_get_at::<rustc_query_system[4874da2f2daebb37]::query::caches::DefaultCache<rustc_span[7f597af770a95843]::def_id::DefId, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 8usize]>>>
  35:        0x1109ed630 - rustc_hir_analysis[ebedbbf8cb7bd6bd]::check::check::check_item_type
  36:        0x1109f1800 - rustc_hir_analysis[ebedbbf8cb7bd6bd]::check::check::check_mod_item_types
  37:        0x11144be90 - rustc_query_impl[61ad5ab37aec3919]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[61ad5ab37aec3919]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 0usize]>>
  38:        0x11148d844 - <rustc_query_impl[61ad5ab37aec3919]::query_impl::check_mod_item_types::dynamic_query::{closure#2} as core[2681f0f28a31b5ec]::ops::function::FnOnce<(rustc_middle[df1e6ddc13461d29]::ty::context::TyCtxt, rustc_span[7f597af770a95843]::def_id::LocalModDefId)>>::call_once
  39:        0x1113de550 - rustc_query_system[4874da2f2daebb37]::query::plumbing::try_execute_query::<rustc_query_impl[61ad5ab37aec3919]::DynamicConfig<rustc_query_system[4874da2f2daebb37]::query::caches::DefaultCache<rustc_span[7f597af770a95843]::def_id::LocalModDefId, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[61ad5ab37aec3919]::plumbing::QueryCtxt, false>
  40:        0x1114be414 - rustc_query_impl[61ad5ab37aec3919]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  41:        0x110998954 - rustc_hir_analysis[ebedbbf8cb7bd6bd]::check_crate
  42:        0x10e2b2464 - rustc_interface[6e024422c4550366]::passes::analysis
  43:        0x11144e2ac - rustc_query_impl[61ad5ab37aec3919]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[61ad5ab37aec3919]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 1usize]>>
  44:        0x111496b20 - <rustc_query_impl[61ad5ab37aec3919]::query_impl::analysis::dynamic_query::{closure#2} as core[2681f0f28a31b5ec]::ops::function::FnOnce<(rustc_middle[df1e6ddc13461d29]::ty::context::TyCtxt, ())>>::call_once
  45:        0x1113bfe6c - rustc_query_system[4874da2f2daebb37]::query::plumbing::try_execute_query::<rustc_query_impl[61ad5ab37aec3919]::DynamicConfig<rustc_query_system[4874da2f2daebb37]::query::caches::SingleCache<rustc_middle[df1e6ddc13461d29]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[61ad5ab37aec3919]::plumbing::QueryCtxt, false>
  46:        0x1114b0270 - rustc_query_impl[61ad5ab37aec3919]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  47:        0x10e1246f8 - <rustc_middle[df1e6ddc13461d29]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[e4aee68b9a041b8f]::run_compiler::{closure#1}::{closure#2}::{closure#6}, core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>>
  48:        0x10e133528 - <rustc_interface[6e024422c4550366]::interface::Compiler>::enter::<rustc_driver_impl[e4aee68b9a041b8f]::run_compiler::{closure#1}::{closure#2}, core[2681f0f28a31b5ec]::result::Result<core[2681f0f28a31b5ec]::option::Option<rustc_interface[6e024422c4550366]::queries::Linker>, rustc_span[7f597af770a95843]::ErrorGuaranteed>>
  49:        0x10e1578e8 - std[14e5c38a806d900b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6e024422c4550366]::util::run_in_thread_with_globals<rustc_interface[6e024422c4550366]::interface::run_compiler<core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>, rustc_driver_impl[e4aee68b9a041b8f]::run_compiler::{closure#1}>::{closure#0}, core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>>
  50:        0x10e159aa8 - <<std[14e5c38a806d900b]::thread::Builder>::spawn_unchecked_<rustc_interface[6e024422c4550366]::util::run_in_thread_with_globals<rustc_interface[6e024422c4550366]::interface::run_compiler<core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>, rustc_driver_impl[e4aee68b9a041b8f]::run_compiler::{closure#1}>::{closure#0}, core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2681f0f28a31b5ec]::result::Result<(), rustc_span[7f597af770a95843]::ErrorGuaranteed>>::{closure#1} as core[2681f0f28a31b5ec]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:        0x105cb31f4 - std::sys::unix::thread::Thread::new::thread_start::h6c0761a1ed593a7b
  52:        0x18ca1f034 - __pthread_joiner_wake

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/private/tmp/rustc-ice-2023-10-04T16:05:55.819241Z-92550.txt` to your bug report

note: compiler flags: -Z drop-tracking

query stack during panic:
#0 [typeck] type-checking `f`
#1 [type_of_opaque] computing type of opaque `f::{opaque#0}`
#2 [type_of] computing type of `f::{opaque#0}`
#3 [check_mod_item_types] checking item types in top-level module
#4 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: {OpaqueTypeKey { def_id: DefId(0:9 ~ 1[30d7]::f::{opaque#0}), args: [] }: OpaqueTypeDecl { hidden_type: OpaqueHiddenType { span: 1.rs:5:37: 5:41 (#8), ty: _ } }}
  |
  = note: delayed at compiler/rustc_infer/src/infer/opaque_types/table.rs:44:26
             0: std::backtrace::Backtrace::create
             1: <rustc_errors::HandlerInner>::emit_diagnostic
             2: <rustc_session::session::Session>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
             3: <rustc_infer::infer::opaque_types::table::OpaqueTypeStorage as core::ops::drop::Drop>::drop
             4: core::ptr::drop_in_place::<rustc_infer::infer::InferCtxt>
             5: core::ptr::drop_in_place::<rustc_hir_typeck::inherited::Inherited>
             6: rustc_hir_typeck::typeck
             7: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
             8: <rustc_query_impl::query_impl::typeck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
             9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            10: rustc_query_impl::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
            11: rustc_hir_analysis::collect::type_of::type_of_opaque
            12: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            13: <rustc_query_impl::query_impl::type_of_opaque::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            14: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            15: rustc_query_impl::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
            16: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
            17: rustc_hir_analysis::collect::type_of::type_of
            18: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
            19: <rustc_query_impl::query_impl::type_of::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId)>>::call_once
            20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            21: rustc_query_impl::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
            22: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
            23: rustc_hir_analysis::check::check::check_item_type
            24: rustc_hir_analysis::check::check::check_mod_item_types
            25: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 0]>>
            26: <rustc_query_impl::query_impl::check_mod_item_types::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalModDefId)>>::call_once
            27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalM
odDefId, rustc_middle::query::erase::Erased<[u8; 0]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            28: rustc_query_impl::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
            29: rustc_hir_analysis::check_crate
            30: rustc_interface::passes::analysis
            31: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
            32: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
            33: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
            34: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
            35: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#6}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            36: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
            37: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
            38: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
            39: std::sys::unix::thread::Thread::new::thread_start
            40: __pthread_joiner_wake
```

</p>
</details>

**Comment by compiler-errors** [comment]
`-Zdrop-tracking` doesn't exist anymore on nightly rustc. Gonna close this because it's a nightly feature.
