### ISSUE TITLE
I seem to have noticed a problem with the clarity of error messages for syntax like `pub(in simplepath::method) struct`.

### ISSUE THREAD

**Issue by aliaaaasa** [rust-lang/rust#116524]
### Code
I encountered an error, looked at the error message, and resolved the error.
Since I am still a beginner in the rust language, I thought that the error was gone when the error message disappeared.
The code below is before correcting the error.
```Rust
pub struct First {
    pub a: String,
    pub b: String,
}
impl First {
    pub fn first_fn(&self, aas: Somethingthing) -> () {
        println!("b");
    }
    pub fn second_fn() -> () {
        pub struct Somethingthing {
            pub aa: String,
            pub bb: String,
        }
        println!("a");
    }
}
fn main() {
}
```
The error message is `cannot find type `Somethingthing` in this scope not found in this scope`. It was a fairly familiar error message, so I was able to resolve it by looking on the Internet.
Below is the modified code.
```rust
pub struct First {
    pub a: String,
    pub b: String,
}
impl First {
    pub fn first_fn(&self, aas: Somethingthing) -> () {
        println!("b");
    }
    pub fn second_fn() -> () {
        pub(in crate::First::first_fn) struct Somethingthing {
            pub aa: String,
            pub bb: String,
        }
        println!("a");
    }
}
fn main() {
}
```
If you modify the code like this, the error message itself will disappear, but the code will not compile.

https://doc.rust-lang.org/reference/visibility-and-privacy.html
https://doc.rust-lang.org/reference/paths.html#simple-paths
I studied from these two websites and I feel like I used grammar incorrectly.
Still, I wrote a report to see if it might help with a clearer error message.

I am a beginner so all my thoughts may be wrong. Please understand

### Meta

`rustc --version --verbose`:
```
rustc 1.72.1 (d5c2e9c34 2023-09-13)
binary: rustc
commit-hash: d5c2e9c342b358556da91d61ed4133f6f50fc0c3
commit-date: 2023-09-13
host: x86_64-unknown-linux-gnu
release: 1.72.1
LLVM version: 16.0.5
```

### Error output

```
thread 'rustc' panicked at 'unexpected unresolved segments', /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/compiler/rustc_hir/src/def.rs:479:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/option.rs:1952:5
   5: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>::resolve_visibility
   6: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
   7: rustc_ast::visit::walk_block::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
   8: rustc_ast::visit::walk_fn::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
   9: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_fn
  10: rustc_ast::visit::walk_assoc_item::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  11: rustc_ast::visit::walk_item::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  12: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
  13: <rustc_expand::expand::AstFragment>::visit_with::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  14: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::visit_ast_fragment_with_placeholders
  15: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  16: <rustc_expand::expand::MacroExpander>::expand_crate
  17: <rustc_session::session::Session>::time::<rustc_ast::ast::Crate, rustc_interface::passes::configure_and_expand::{closure#1}>
  18: rustc_interface::passes::resolver_for_lowering
  19: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#2}>
  20: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  21: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  22: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.1 (d5c2e9c34 2023-09-13) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
error: could not compile `las` (bin "las")

 *  The terminal process "cargo 'run', '--package', 'las', '--bin', 'las'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'unexpected unresolved segments', /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/compiler/rustc_hir/src/def.rs:479:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/option.rs:1952:5
   5: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>::resolve_visibility
   6: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
   7: rustc_ast::visit::walk_block::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
   8: rustc_ast::visit::walk_fn::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
   9: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_fn
  10: rustc_ast::visit::walk_assoc_item::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  11: rustc_ast::visit::walk_item::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  12: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
  13: <rustc_expand::expand::AstFragment>::visit_with::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  14: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::visit_ast_fragment_with_placeholders
  15: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  16: <rustc_expand::expand::MacroExpander>::expand_crate
  17: <rustc_session::session::Session>::time::<rustc_ast::ast::Crate, rustc_interface::passes::configure_and_expand::{closure#1}>
  18: rustc_interface::passes::resolver_for_lowering
  19: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<&rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>, rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#2}>
  20: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  21: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  22: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.1 (d5c2e9c34 2023-09-13) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
error: could not compile `las` (bin "las")

 *  The terminal process "cargo 'run', '--package', 'las', '--bin', 'las'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
reduced second example:
````rust
pub struct First {}

pub(in crate::First::first_fn) struct Somethingthing {}
````

seems to be fixed on stable 1.73.0 though :)
