### ISSUE TITLE
rustc ice

### ISSUE THREAD

**Issue by sarah-quinones** [rust-lang/rust#116638]
### Code
i don't have a minimal repro unfortunately, since this happened during a refactor of a company code base

### Meta

`rustc --version --verbose`:
```
rustc 1.72.1 (d5c2e9c34 2023-09-13)
binary: rustc
commit-hash: d5c2e9c342b358556da91d61ed4133f6f50fc0c3
commit-date: 2023-09-13
host: x86_64-unknown-linux-gnu
release: 1.72.1
LLVM version: 16.0.5


rustc 1.74.0-nightly (e7c502d93 2023-09-27)
binary: rustc
commit-hash: e7c502d9309ae6bc6a9750514ba7fe397844e84c
commit-date: 2023-09-27
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0

```

### Error output

```
thread 'rustc' panicked at compiler/rustc_resolve/src/lib.rs:2007:67:
internal error: entered unreachable code
stack backtrace:
   0:     0x7f4f4f34a894 - std::backtrace_rs::backtrace::libunwind::trace::h9181ffa9c3d4a750
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4f4f34a894 - std::backtrace_rs::backtrace::trace_unsynchronized::h6a317402f81c33c0
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4f4f34a894 - std::backtrace::Backtrace::create::hd22763ee98624e9c
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/backtrace.rs:331:13
   3:     0x7f4f4f34a7d0 - std::backtrace::Backtrace::force_capture::he555ea47920a8f17
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/backtrace.rs:313:9
   4:     0x7f4f525016cb - std[1ca7f2df6b6ff2b1]::panicking::update_hook::<alloc[b3660cac06f40a66]::boxed::Box<rustc_driver_impl[51ab906ef6457130]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f4f4f367771 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h13ad871b7a2770ec
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/alloc/src/boxed.rs:2021:9
   6:     0x7f4f4f367771 - std::panicking::rust_panic_with_hook::h3e798fc3ade5e233
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:735:13
   7:     0x7f4f4f3674a6 - std::panicking::begin_panic_handler::{{closure}}::hc91a6a16511779fa
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:601:13
   8:     0x7f4f4f3647a6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbdfb1f15edc4e2e0
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys_common/backtrace.rs:170:18
   9:     0x7f4f4f367242 - rust_begin_unwind
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:597:5
  10:     0x7f4f4f3c6565 - core::panicking::panic_fmt::h319347a3509c4d57
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/core/src/panicking.rs:72:14
  11:     0x7f4f4f3c6603 - core::panicking::panic::h064dcf53a83497d7
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/core/src/panicking.rs:127:5
  12:     0x7f4f515c4a3c - <rustc_resolve[9c6c6559343d5508]::Resolver>::resolve_rustdoc_path
  13:     0x7f4f515c424b - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_and_cache_rustdoc_path
  14:     0x7f4f515c1865 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_doc_links
  15:     0x7f4f515ab2af - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  16:     0x7f4f515c56aa - rustc_ast[ef80e278282167a3]::visit::walk_item::<rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>
  17:     0x7f4f515ad6e9 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  18:     0x7f4f515c56aa - rustc_ast[ef80e278282167a3]::visit::walk_item::<rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>
  19:     0x7f4f515ad6e9 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  20:     0x7f4f515c56aa - rustc_ast[ef80e278282167a3]::visit::walk_item::<rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>
  21:     0x7f4f515ad6e9 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  22:     0x7f4f515ab10e - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor as rustc_ast[ef80e278282167a3]::visit::Visitor>::visit_item
  23:     0x7f4f517ce65b - <rustc_resolve[9c6c6559343d5508]::Resolver>::late_resolve_crate
  24:     0x7f4f517cda90 - <rustc_session[f5e7ce946b8d9f8]::session::Session>::time::<(), <rustc_resolve[9c6c6559343d5508]::Resolver>::resolve_crate::{closure#0}>
  25:     0x7f4f517ca5e9 - rustc_interface[442ada56983741ed]::passes::resolver_for_lowering
  26:     0x7f4f5196a60a - rustc_query_impl[13a0a52e862e93eb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[13a0a52e862e93eb]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8318e585d4f56aca]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7f4f5196a5f9 - <rustc_query_impl[13a0a52e862e93eb]::query_impl::resolver_for_lowering::dynamic_query::{closure#2} as core[23641ef65c6f6c3a]::ops::function::FnOnce<(rustc_middle[8318e585d4f56aca]::ty::context::TyCtxt, ())>>::call_once
  28:     0x7f4f51c86617 - rustc_query_system[bec01fb9f9ecbd97]::query::plumbing::try_execute_query::<rustc_query_impl[13a0a52e862e93eb]::DynamicConfig<rustc_query_system[bec01fb9f9ecbd97]::query::caches::SingleCache<rustc_middle[8318e585d4f56aca]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[13a0a52e862e93eb]::plumbing::QueryCtxt, true>
  29:     0x7f4f51e69352 - rustc_query_impl[13a0a52e862e93eb]::query_impl::resolver_for_lowering::get_query_incr::__rust_end_short_backtrace
  30:     0x7f4f51a4b446 - <rustc_middle[8318e585d4f56aca]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}::{closure#2}::{closure#4}, &rustc_data_structures[22ffc45ba6767646]::steal::Steal<(rustc_middle[8318e585d4f56aca]::ty::ResolverAstLowering, alloc[b3660cac06f40a66]::rc::Rc<rustc_ast[ef80e278282167a3]::ast::Crate>)>>
  31:     0x7f4f51a493c3 - rustc_span[ebfafd642cc98e77]::set_source_map::<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_interface[442ada56983741ed]::interface::run_compiler<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  32:     0x7f4f51a44070 - std[1ca7f2df6b6ff2b1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[442ada56983741ed]::util::run_in_thread_with_globals<rustc_interface[442ada56983741ed]::interface::run_compiler<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}>::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>
  33:     0x7f4f51d5d67e - <<std[1ca7f2df6b6ff2b1]::thread::Builder>::spawn_unchecked_<rustc_interface[442ada56983741ed]::util::run_in_thread_with_globals<rustc_interface[442ada56983741ed]::interface::run_compiler<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}>::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>::{closure#1} as core[23641ef65c6f6c3a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  34:     0x7f4f4f3722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::habd582f39dd9789c
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/alloc/src/boxed.rs:2007:9
  35:     0x7f4f4f3722d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6aa0cee9365e9c12
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/alloc/src/boxed.rs:2007:9
  36:     0x7f4f4f3722d5 - std::sys::unix::thread::Thread::new::thread_start::ha6c33fae81256bd2
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7f4f4f094ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  38:     0x7f4f4f126a40 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  39:                0x0 - <unknown>


rustc version: 1.74.0-nightly (e7c502d93 2023-09-27)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_resolve/src/lib.rs:2007:67:
internal error: entered unreachable code
stack backtrace:
   0:     0x7f41eaead27c - std::backtrace_rs::backtrace::libunwind::trace::h9181ffa9c3d4a750
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f41eaead27c - std::backtrace_rs::backtrace::trace_unsynchronized::hbdccfdb9f54804b7
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f41eaead27c - std::sys_common::backtrace::_print_fmt::h30ee71b03bdebb9c
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f41eaead27c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0280fcf2819eb75f
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f41eaf12edc - core::fmt::rt::Argument::fmt::h38e0d2b510ca52ee
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/core/src/fmt/rt.rs:138:9
   5:     0x7f41eaf12edc - core::fmt::write::h1e7ff4b258ae9fa6
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/core/src/fmt/mod.rs:1114:21
   6:     0x7f41eae9ff0e - std::io::Write::write_fmt::h39163702b180fff1
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/io/mod.rs:1763:15
   7:     0x7f41eaead064 - std::sys_common::backtrace::_print::h64c13a11b52a9754
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f41eaead064 - std::sys_common::backtrace::print::h8d0e9a5a6da703be
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f41eaeaff43 - std::panicking::default_hook::{{closure}}::hc24f34219b71e6f9
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:272:22
  10:     0x7f41eaeafc64 - std::panicking::default_hook::h16c43f2915765f3b
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:292:9
  11:     0x7f41e9d0156f - std[1ca7f2df6b6ff2b1]::panicking::update_hook::<alloc[b3660cac06f40a66]::boxed::Box<rustc_driver_impl[51ab906ef6457130]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f41eaeb0771 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h13ad871b7a2770ec
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/alloc/src/boxed.rs:2021:9
  13:     0x7f41eaeb0771 - std::panicking::rust_panic_with_hook::h3e798fc3ade5e233
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:735:13
  14:     0x7f41eaeb04a6 - std::panicking::begin_panic_handler::{{closure}}::hc91a6a16511779fa
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:601:13
  15:     0x7f41eaead7a6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbdfb1f15edc4e2e0
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f41eaeb0242 - rust_begin_unwind
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/panicking.rs:597:5
  17:     0x7f41eaf0f565 - core::panicking::panic_fmt::h319347a3509c4d57
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/core/src/panicking.rs:72:14
  18:     0x7f41eaf0f603 - core::panicking::panic::h064dcf53a83497d7
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/core/src/panicking.rs:127:5
  19:     0x7f41e8dc4a3c - <rustc_resolve[9c6c6559343d5508]::Resolver>::resolve_rustdoc_path
  20:     0x7f41e8dc424b - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_and_cache_rustdoc_path
  21:     0x7f41e8dc1865 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_doc_links
  22:     0x7f41e8dab2af - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  23:     0x7f41e8dc56aa - rustc_ast[ef80e278282167a3]::visit::walk_item::<rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>
  24:     0x7f41e8dad6e9 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  25:     0x7f41e8dc56aa - rustc_ast[ef80e278282167a3]::visit::walk_item::<rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>
  26:     0x7f41e8dad6e9 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  27:     0x7f41e8dc56aa - rustc_ast[ef80e278282167a3]::visit::walk_item::<rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>
  28:     0x7f41e8dad6e9 - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor>::resolve_item
  29:     0x7f41e8dab10e - <rustc_resolve[9c6c6559343d5508]::late::LateResolutionVisitor as rustc_ast[ef80e278282167a3]::visit::Visitor>::visit_item
  30:     0x7f41e8fce65b - <rustc_resolve[9c6c6559343d5508]::Resolver>::late_resolve_crate
  31:     0x7f41e8fcda90 - <rustc_session[f5e7ce946b8d9f8]::session::Session>::time::<(), <rustc_resolve[9c6c6559343d5508]::Resolver>::resolve_crate::{closure#0}>
  32:     0x7f41e8fca5e9 - rustc_interface[442ada56983741ed]::passes::resolver_for_lowering
  33:     0x7f41e916a60a - rustc_query_impl[13a0a52e862e93eb]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[13a0a52e862e93eb]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8318e585d4f56aca]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7f41e916a5f9 - <rustc_query_impl[13a0a52e862e93eb]::query_impl::resolver_for_lowering::dynamic_query::{closure#2} as core[23641ef65c6f6c3a]::ops::function::FnOnce<(rustc_middle[8318e585d4f56aca]::ty::context::TyCtxt, ())>>::call_once
  35:     0x7f41e9486617 - rustc_query_system[bec01fb9f9ecbd97]::query::plumbing::try_execute_query::<rustc_query_impl[13a0a52e862e93eb]::DynamicConfig<rustc_query_system[bec01fb9f9ecbd97]::query::caches::SingleCache<rustc_middle[8318e585d4f56aca]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[13a0a52e862e93eb]::plumbing::QueryCtxt, true>
  36:     0x7f41e9669352 - rustc_query_impl[13a0a52e862e93eb]::query_impl::resolver_for_lowering::get_query_incr::__rust_end_short_backtrace
  37:     0x7f41e924b446 - <rustc_middle[8318e585d4f56aca]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}::{closure#2}::{closure#4}, &rustc_data_structures[22ffc45ba6767646]::steal::Steal<(rustc_middle[8318e585d4f56aca]::ty::ResolverAstLowering, alloc[b3660cac06f40a66]::rc::Rc<rustc_ast[ef80e278282167a3]::ast::Crate>)>>
  38:     0x7f41e92493c3 - rustc_span[ebfafd642cc98e77]::set_source_map::<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_interface[442ada56983741ed]::interface::run_compiler<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  39:     0x7f41e9244070 - std[1ca7f2df6b6ff2b1]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[442ada56983741ed]::util::run_in_thread_with_globals<rustc_interface[442ada56983741ed]::interface::run_compiler<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}>::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>
  40:     0x7f41e955d67e - <<std[1ca7f2df6b6ff2b1]::thread::Builder>::spawn_unchecked_<rustc_interface[442ada56983741ed]::util::run_in_thread_with_globals<rustc_interface[442ada56983741ed]::interface::run_compiler<core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>, rustc_driver_impl[51ab906ef6457130]::run_compiler::{closure#1}>::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[23641ef65c6f6c3a]::result::Result<(), rustc_span[ebfafd642cc98e77]::ErrorGuaranteed>>::{closure#1} as core[23641ef65c6f6c3a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f41eaebb2d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::habd582f39dd9789c
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/alloc/src/boxed.rs:2007:9
  42:     0x7f41eaebb2d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6aa0cee9365e9c12
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/alloc/src/boxed.rs:2007:9
  43:     0x7f41eaebb2d5 - std::sys::unix::thread::Thread::new::thread_start::ha6c33fae81256bd2
                               at /rustc/e7c502d9309ae6bc6a9750514ba7fe397844e84c/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7f41e6894ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  45:     0x7f41e6926a40 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  46:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md


note: compiler flags: --crate-type lib --crate-type staticlib --crate-type cdylib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -C symbol_mangling_version=v0

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.

```

</p>
</details>

**Comment by Noratrieb** [comment]
This issue does not have a reproduction and is therefore not really actionable, closing. If you find the problem again, please open a new issue, ideally with a reproduction.
