### ISSUE TITLE
ICE: rustc panicked at `compiler/rustc_mir_build/src/build/custom/mod.rs:110:40`

### ISSUE THREAD

**Issue by iamanonymouscs** [rust-lang/rust#116784]
### Code
`cat ice.rs`
```Rust
#![crate_type = "lib"]
#![feature(core_intrinsics)]
#![feature(custom_mir)]
use std::intrinsics::mir::*;
use std::mem::{transmute, ManuallyDrop, MaybeUninit};
pub unsafe fn identity_transmutes() {
    // These are nops and should be removed
    let _a = transmute::<i32, i32>(1);
    let _a = transmute::<Vec<i32>, Vec<i32>>(Vec::new());
}
#[custom_mir(transmute)]
pub unsafe fn integer_transmutes() {
    mir! {
        {
            let A = CastTransmute::<i32, u32>(1); 
            let B = CastTransmute::<i32, i64>(1); 
            let C = CastTransmute::<u64, i64>(1);
            let D = CastTransmute::<u64, u32>(1);
            let E = CastTransmute::<isize, usize>(1); 
            Return()
        }
    }
}
pub unsafe fn adt_transmutes() {
    let _a: u8 = transmute(Some(std::num::NonZeroU8::MAX));
    let _a: i16 = transmute(std::num::Wrapping(0_i16));
    let _a: u16 = transmute(std::num::Wrapping(0_i16));
    let _a: u32 = transmute(Union32 { i32: 0 });
    let _a: i32 = transmute(Union32 { u32: 0 });
    let _a: ManuallyDrop<String> = transmute(MaybeUninit::<String>::uninit());
}
pub union Union32 {
    u32: u32,
    i32: i32,
}
```
### Command
` rustc  -C opt-level=0 ice.rs`

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (42b1224e9 2023-10-15)
binary: rustc
commit-hash: 42b1224e9eb37177f608d3f6a6f2be2ee13902e4
commit-date: 2023-10-15
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.2
```

### Error output

```
warning: the feature `custom_mir` is internal to the compiler or standard library
 --> ice.rs:3:12
  |
3 | #![feature(custom_mir)]
  |            ^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default

warning: variable `A` is assigned to, but never used
  --> ice.rs:15:17
   |
15 |             let A = CastTransmute::<i32, u32>(1); 
   |                 ^
   |
   = note: consider using `_A` instead
   = note: `#[warn(unused_variables)]` on by default

warning: variable `B` is assigned to, but never used
  --> ice.rs:16:17
   |
16 |             let B = CastTransmute::<i32, i64>(1); 
   |                 ^
   |
   = note: consider using `_B` instead

warning: variable `C` is assigned to, but never used
  --> ice.rs:17:17
   |
17 |             let C = CastTransmute::<u64, i64>(1);
   |                 ^
   |
   = note: consider using `_C` instead

warning: variable `D` is assigned to, but never used
  --> ice.rs:18:17
   |
18 |             let D = CastTransmute::<u64, u32>(1);
   |                 ^
   |
   = note: consider using `_D` instead

warning: variable `E` is assigned to, but never used
  --> ice.rs:19:17
   |
19 |             let E = CastTransmute::<isize, usize>(1); 
   |                 ^
   |
   = note: consider using `_E` instead
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/build/custom/mod.rs:110:40:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fec4ac838ec - std::backtrace_rs::backtrace::libunwind::trace::hb36a1a71d07352e9
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fec4ac838ec - std::backtrace_rs::backtrace::trace_unsynchronized::hab5ecbe61dd45168
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fec4ac838ec - std::sys_common::backtrace::_print_fmt::hf8f8fcaa1a8a37df
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fec4ac838ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e949e3d2f600dc6
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fec4aceb370 - core::fmt::rt::Argument::fmt::h0bed2bd6f3173100
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/fmt/rt.rs:142:9
   5:     0x7fec4aceb370 - core::fmt::write::hcf2dc9ce923ddc63
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/fmt/mod.rs:1117:17
   6:     0x7fec4ac76baf - std::io::Write::write_fmt::h07a32290dc729d40
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/io/mod.rs:1762:15
   7:     0x7fec4ac836d4 - std::sys_common::backtrace::_print::h80c15d8ee2444dcc
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fec4ac836d4 - std::sys_common::backtrace::print::h1ac2ff1391eb0f3d
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fec4ac86507 - std::panicking::default_hook::{{closure}}::hd8919f68d7d73a2c
  10:     0x7fec4ac8624a - std::panicking::default_hook::h807e4d5d4c7a68a0
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:292:9
  11:     0x7fec4d839bda - std[d7b1197d38436841]::panicking::update_hook::<alloc[e96338735e4e82d]::boxed::Box<rustc_driver_impl[5a32d02242522b87]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fec4ac86ca8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd3d9b0571d38460f
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/alloc/src/boxed.rs:2021:9
  13:     0x7fec4ac86ca8 - std::panicking::rust_panic_with_hook::hac974fb018631aa6
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:735:13
  14:     0x7fec4ac869b6 - std::panicking::begin_panic_handler::{{closure}}::h4a8176702702a62b
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:601:13
  15:     0x7fec4ac83e06 - std::sys_common::backtrace::__rust_end_short_backtrace::h6179cf53427f95c0
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7fec4ac86732 - rust_begin_unwind
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:597:5
  17:     0x7fec4ace7995 - core::panicking::panic_fmt::h2ca7d2f7d2c65755
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/panicking.rs:72:14
  18:     0x7fec4ace7a33 - core::panicking::panic::h70b016af14e7c9a4
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/panicking.rs:127:5
  19:     0x7fec4f2d4012 - rustc_mir_build[663d5d6570e17f4a]::build::mir_built
  20:     0x7fec4f2cd621 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7fec4ea47b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  22:     0x7fec4ea47510 - rustc_query_impl[134db83d58928475]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7fec4cd195fe - rustc_mir_transform[60dc20ba90af5c94]::check_unsafety::unsafety_check_result
  24:     0x7fec4ea47907 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7fec4ea47b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  26:     0x7fec4ea475d0 - rustc_query_impl[134db83d58928475]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7fec4ea48616 - rustc_mir_transform[60dc20ba90af5c94]::mir_const
  28:     0x7fec4ea48569 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7fec4ea47b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  30:     0x7fec4ea47690 - rustc_query_impl[134db83d58928475]::query_impl::mir_const::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7fec4ce8cf43 - rustc_mir_transform[60dc20ba90af5c94]::mir_promoted
  32:     0x7fec4ed25298 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 16usize]>>
  33:     0x7fec4ed2550e - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  34:     0x7fec4ed2519d - rustc_query_impl[134db83d58928475]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7fec4f658043 - rustc_borrowck[a7ade61e6afc50c4]::mir_borrowck
  36:     0x7fec4f657fb1 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  37:     0x7fec4ea47b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  38:     0x7fec4ea47750 - rustc_query_impl[134db83d58928475]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7fec4eeb1c69 - rustc_interface[7cfec6a7cd1a04f4]::passes::analysis
  40:     0x7fec4eeb15af - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 1usize]>>
  41:     0x7fec4f4c8ba6 - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::SingleCache<rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  42:     0x7fec4f4c89d5 - rustc_query_impl[134db83d58928475]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7fec4f5d60b4 - std[d7b1197d38436841]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7cfec6a7cd1a04f4]::util::run_in_thread_with_globals<rustc_interface[7cfec6a7cd1a04f4]::interface::run_compiler<core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>, rustc_driver_impl[5a32d02242522b87]::run_compiler::{closure#1}>::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>
  44:     0x7fec4f5d53b3 - <<std[d7b1197d38436841]::thread::Builder>::spawn_unchecked_<rustc_interface[7cfec6a7cd1a04f4]::util::run_in_thread_with_globals<rustc_interface[7cfec6a7cd1a04f4]::interface::run_compiler<core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>, rustc_driver_impl[5a32d02242522b87]::run_compiler::{closure#1}>::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>::{closure#1} as core[9ee5d2235d3a5bf6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x7fec4ac91c25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha0c5a651faab0494
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/alloc/src/boxed.rs:2007:9
  46:     0x7fec4ac91c25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0f4ce6187e148d85
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/alloc/src/boxed.rs:2007:9
  47:     0x7fec4ac91c25 - std::sys::unix::thread::Thread::new::thread_start::hcb407001741deea6
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys/unix/thread.rs:108:17
  48:     0x7fec4ab59609 - start_thread
  49:     0x7fec4aa7c133 - clone
  50:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/interesting/rustc-ice-2023-10-16T06:57:49.336773836Z-23700.txt` to your bug report

note: compiler flags: -C opt-level=0

query stack during panic:
#0 [mir_built] building MIR for `integer_transmutes`
#1 [unsafety_check_result] unsafety-checking `integer_transmutes`
#2 [mir_const] preparing `integer_transmutes` for borrow checking
#3 [mir_promoted] promoting constants in MIR for `integer_transmutes`
#4 [mir_borrowck] borrow-checking `integer_transmutes`
#5 [analysis] running analysis passes on this crate
end of query stack
warning: 6 warnings emitted
```

</p>
</details>

**Comment by Nilstrieb** [comment]
this is expected, using any internal feature incorrectly is expected to cause ICEs. 
The ICE message does sadly not say this yet, thank you for the report anyways.
