### ISSUE TITLE
rust-installer may soon be too VM resource hungry for some 32-bit native builds

### ISSUE THREAD

**Issue by he32** [rust-lang/rust#116758]
Hi,

while watching the build of rust 1.73.0 on the various NetBSD targets we support via our packaging system `pkgsrc`, some of those targets slower than others, it appears to me that somewhat surprisingly, the `rust-installer` program is perhaps the most resource hungry in terms of virtual memory of all the processes used to complete a build and installation.  On amd64, I've seen it balloon to 1.8GB, and on 32-bit armv7, I've observed it ballooning to 1.5GB.  I predict that unless something is done to reign in and/or optimize the virtual memory consumption of `rust-installer`, it is going to be the first process which causes `rust` no longer to be possible to build (and install) natively on various 32-bit platforms.  If I'm not terribly mistaken, e.g. NetBSD's armv7 port(s) have an upper bound on user-mode virtual memory when executed on actual (or emulated) 32-bit hardware of somewhere in the area around 1.8GB.

I'll admit that I have not (yet) looked closely at what it is that `rust-installer` does which causes it to behave in this manner, or the particular way it goes about doing this, and therefore have no concrete suggestion for what needs to be improved / optimized or done differently.

Input solicited on whether this is easy, difficult or near-impossible to do anything about this issue.

**Comment by Nilstrieb** [comment]
Using so much memory does sound like a bug. I have tried to reproduce this in an Ubuntu (`x86_64-unknown-linux-gnu`) docker container with a memory limit of 100M and was not able to reproduce any issues, Rust installed just fine (using the [1.73.0 tarball](https://static.rust-lang.org/dist/rust-1.73.0-x86_64-unknown-linux-gnu.tar.gz) from [the forge](https://forge.rust-lang.org/infra/other-installation-methods.html).
Do you have a reproduction?

**Comment by Nilstrieb** [comment]
Out of curiousity, I also created a netbsd VM (9.3) and tried installing rust there using the [tarball](https://static.rust-lang.org/dist/rust-1.73.0-x86_64-unknown-netbsd.tar.gz). I limited my VM to just 500M, but it installed perfectly fine.

**Comment by saethlin** [comment]
I'm guessing that this phrasing:

> longer to be possible to build (and install) 

implies that installation on a target requires compilation on that target.

So I ran
```
/usr/bin/time -v x build src/tools/rust-installer/ -j1
```
And peak memory looks like 300 MB on x86_64-unknown-linux-gnu.

**Comment by he32** [comment]
> Out of curiousity, I also created a netbsd VM (9.3) and tried installing rust there using the [tarball](https://static.rust-lang.org/dist/rust-1.73.0-x86_64-unknown-netbsd.tar.gz). I limited my VM to just 500M, but it installed perfectly fine.

Just to clarify: my observation was done not while installing an already-built binary version of rust, but instead during the "install" phase (where rust-installer is apparently also used) of a full re-build of rust from source.

**Comment by he32** [comment]
> I'm guessing that this phrasing:
> 
> > longer to be possible to build (and install)
> 
> implies that installation on a target requires compilation on that target.

In essence: yes.  See my previous reply -- my observation was done while watching the progress of a full build of rust from source and subsequent installation of that result.

> So I ran
> 
> ```
> /usr/bin/time -v x build src/tools/rust-installer/ -j1
> ```
> 
> And peak memory looks like 300 MB on x86_64-unknown-linux-gnu.

I am not talking about building rust-installer itself, rather its use during the "install" phase of a full re-build and install of rust from source.

**Comment by Nilstrieb** [comment]
Can you share the exact actions to reproduce this, including the commands run?

**Comment by he32** [comment]
> Out of curiousity, I also created a netbsd VM (9.3) and tried installing rust there using the [tarball](https://static.rust-lang.org/dist/rust-1.73.0-x86_64-unknown-netbsd.tar.gz). I limited my VM to just 500M, but it installed perfectly fine.

How, exactly, did you limit your VM to 500M?

Perhaps this was done by `limit datasize 500M` (csh) or `ulimit -d 500000000` (sh)?  This tweaks the `RLMIT_DATA` resource limit, and it's documented as follows:

```
     RLIMIT_DATA     The maximum size (in bytes) of the data segment for a
                     process; this defines how far a program may extend its
                     break with the sbrk(2) system call.
```

However, if I'm not terribly mistaken, `rust` uses the `jemalloc` memory allocator (possibly indirectly via use of `malloc()` / `free()`), and that one does not do memory allocation using `sbrk()`, but instead uses `mmap()`, and the virtual memory used in that manner is not counted towards `RLMIT_DATA`.

Instead, you might want to do `limit vmemoryuse 500m` (csh) or `ulimit -v 500000000` (sh).  This tweaks the `RLIMIT_AS` resource limit, which is:

```
     RLIMIT_AS       The maximum amount (in bytes) of virtual memory the
                     process is allowed to map.
```

With `limit vmemoryuse 1g` (csh), and commenting out the pkgsrc Makefile's `ULIMIT_RESOURCES+=vmemoryuse` (its presence would invalidate the restriction), the build pretty quickly crashes with

```
...
     Running `/usr/pkgsrc/wip/rust/work/rust-bootstrap/bin/rustc --crate-name bootstrap --edition=2021 lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=1 -C metadata=6a339df84277c219 -C extra-filename=-6a339df84277c219 --out-dir /usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps -C incremental=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/incremental -L dependency=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps --extern build_helper=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libbuild_helper-148844f0d825da95.rmeta --extern cc=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libcc-cfafd781fde785da.rmeta --extern clap=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libclap-1420bb80674ee6cc.rmeta --extern clap_complete=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libclap_complete-78619a692105593a.rmeta --extern cmake=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libcmake-2d3d696122a4482b.rmeta --extern fd_lock=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libfd_lock-9327bce6210b1585.rmeta --extern filetime=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libfiletime-a27ee57a1af21421.rmeta --extern hex=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libhex-20bc7d08e541eb3e.rmeta --extern ignore=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libignore-2de0f2abcaa31b67.rmeta --extern libc=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/liblibc-28b82c8004bb0902.rmeta --extern object=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libobject-158ec9c52dc68688.rmeta --extern once_cell=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libonce_cell-f4e513737da2a51b.rmeta --extern opener=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libopener-1920d8429ee7a759.rmeta --extern semver=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libsemver-252e780ea80b2329.rmeta --extern serde=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libserde-0a16ffb75acb0aa0.rmeta --extern serde_derive=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libserde_derive-16deeefaf5676d7e.so --extern serde_json=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libserde_json-7c4ec635a8355868.rmeta --extern sha2=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libsha2-e568dc5110e464af.rmeta --extern tar=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libtar-6b4f64896f6662bb.rmeta --extern termcolor=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libtermcolor-13f633eead144ba4.rmeta --extern toml=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libtoml-e4dbac73cf72e1cd.rmeta --extern walkdir=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libwalkdir-6db987d1eec7b101.rmeta --extern xz2=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/deps/libxz2-235341897e44981d.rmeta -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings -L native=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/build/lzma-sys-d3dd0cf035ebd0d0/out`
thread '<unnamed>' panicked at 'failed to allocate an alternative stack: Cannot allocate memory (os error 12)', library/std/src/sys/unix/stack_overflow.rs:143:13
stack backtrace:
thread '<unnamed>' panicked at 'failed to spawn thread: Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }', /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/compiler/rustc_codegen_ssa/src/back/write.rs:1731:6
   0:     0x753b254a0ea1 - std::backtrace_rs::backtrace::libunwind::trace::h0199954ba03d2f6d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x753b254a0ea1 - std::backtrace_rs::backtrace::trace_unsynchronized::h58924b7fd9552277
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x753b254a0ea1 - std::sys_common::backtrace::_print_fmt::he38d624f4df25f0a
...
```

Setting the virtualsize resource limit to 1.7GB results in

```
[ 79%] Linking CXX static library ../libLLVMDWARFLinkerParallel.a
[ 79%] Built target LLVMDWARFLinkerParallel
virtual memory exhausted: Cannot allocate memory
gmake[2]: *** [lib/Passes/CMakeFiles/LLVMPasses.dir/build.make:90: lib/Passes/CMakeFiles/LLVMPasses.dir/PassBuilder.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:23319: lib/Passes/CMakeFiles/LLVMPasses.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
...
```

(ok, this uses the embedded LLVM).  And without the embedded LLVM:

```
   Compiling rustc_trait_selection v0.0.0 (/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/compiler/rustc_trait_selection)
     Running `/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/bootstrap/debug/rustc --crate-name rustc_trait_selection --edition=2021 compiler/rustc_trait_selection/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -Zunstable-options --check-cfg 'values(feature)' --check-cfg 'names()' --check-cfg 'values()' -C metadata=213947e234756eaf -C extra-filename=-213947e234756eaf --out-dir /usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps --target x86_64-unknown-netbsd -L dependency=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps -L dependency=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/release/deps --extern rustc_ast=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_ast-4589e29655c8ede7.rmeta --extern rustc_attr=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_attr-4ce68718baf2fa52.rmeta --extern rustc_data_structures=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_data_structures-e7f2548040007d3d.rmeta --extern rustc_errors=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_errors-a5f666787b8eaa09.rmeta --extern rustc_fluent_macro=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/release/deps/librustc_fluent_macro-3092679164a3eed5.so --extern rustc_hir=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_hir-a03c78227cc87bf2.rmeta --extern rustc_index=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_index-4f0957d9e1e6d5e6.rmeta --extern rustc_infer=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_infer-ef5ebd7449df8584.rmeta --extern rustc_macros=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/release/deps/librustc_macros-a919fdc9d5b260e7.so --extern rustc_middle=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_middle-5f53bec614c9c03e.rmeta --extern rustc_parse_format=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_parse_format-3101d7234be84a34.rmeta --extern rustc_query_system=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_query_system-6c2aedeb43c1764c.rmeta --extern rustc_serialize=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_serialize-44e3e3ebade4d0c7.rmeta --extern rustc_session=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_session-0d75d0e29b9022c1.rmeta --extern rustc_span=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_span-a7709ce0686aa2c2.rmeta --extern rustc_target=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_target-f9084243998c38b8.rmeta --extern rustc_transmute=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/librustc_transmute-8870a8427c2270f9.rmeta --extern smallvec=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/libsmallvec-38894e3004a6091d.rmeta --extern tracing=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/deps/libtracing-cb1efb95566b0c30.rmeta --cfg=bootstrap --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)' '--check-cfg=values(rustix_use_libc)' '--check-cfg=values(emulate_second_only_system)' '--check-cfg=values(windows_raw_dylib)' -Zmacro-backtrace -Clink-args=-Wl,-z,origin -Clink-args=-Wl,-rpath,/usr/pkg/lib -Zunstable-options -Csplit-debuginfo=off -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Z binary-dep-depinfo -L native=/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/x86_64-unknown-netbsd/stage0-rustc/x86_64-unknown-netbsd/release/build/psm-1f8a23e5d5ae19dd/out`
thread 'rustc' panicked at '/rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/compiler/rustc_codegen_ssa/src/back/write.rs:1930:17: panic during codegen/LLVM phase', compiler/rustc_middle/src/util/bug.rs:36:26
stack backtrace:
   0:     0x7d29e00a0ea1 - std::backtrace_rs::backtrace::libunwind::trace::h0199954ba03d2f6d
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7d29e00a0ea1 - std::backtrace_rs::backtrace::trace_unsynchronized::h58924b7fd9552277
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7d29e00a0ea1 - std::sys_common::backtrace::_print_fmt::he38d624f4df25f0a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7d29e00a0ea1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b6c3f3334d0b13f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7d29e01024af - core::fmt::rt::Argument::fmt::h7913c315e4242757
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x7d29e01024af - core::fmt::write::hbfcb318fe3db4234
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
...
```

So...  There may actually be other parts of the build which uses more than 1.7GB on amd64...

The thing I do is to build rust from source, usually using the pkgsrc-wip "rust" package.

For pkgsrc-wip, see

http://pkgsrc.org/wip/

This requires you already have pkgsrc extracted in /usr/pkgsrc.

Then it's a "simple" matter of

```
% cd /usr/pkgsrc/wip/rust
% make install
```

If you have many cores and enough memory, add

```
MAKE_JOBS+=  <number-of-cores>
```

and the build won't take eons.

Observe process virtual sizes of processes with e.g. `top`.

**Comment by the8472** [comment]
note that bumping max_jobs also increases memory footprint. if you're on a memory-constrained system you'll want to leave it on 1.

**Comment by he32** [comment]
OK, so the build results for rust 1.73.0 is now in for my emulated armv6 system (2-core CPU, 3GB memory, in qemu, with armv6hf user-land).  The first round failed using `rust-installer` at this point:

```
skipping Install miri stage2 (armv6-unknown-netbsd-eabihf)
Dist llvm-tools-1.73.0-armv6-unknown-netbsd-eabihf
running: LD_LIBRARY_PATH="/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/armv6-unknown-netbsd-eabihf/stage0-bootstrap-tools/armv6-unknown-netbsd-eabihf/release/deps:/usr/pkgsrc/wip/rust/work/rust-bootstrap/lib:/usr/pkgsrc/wip/rust/work/rust-bootstrap/lib" RUSTC="/usr/pkgsrc/wip/rust/work/rust-bootstrap/bin/rustc" "/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/armv6-unknown-netbsd-eabihf/stage0-tools-bin/rust-installer" "generate" "--image-dir" "/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/tmp/tarball/llvm-tools/armv6-unknown-netbsd-eabihf/image" "--component-name=llvm-tools-preview" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust" "--success-message=llvm-tools installed." "--package-name=llvm-tools-1.73.0-armv6-unknown-netbsd-eabihf" "--non-installed-overlay" "/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/tmp/tarball/llvm-tools/armv6-unknown-netbsd-eabihf/overlay" "--output-dir" "/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/dist" "--work-dir" "/usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/build/tmp/tarball/llvm-tools/armv6-unknown-netbsd-eabihf" "--compression-formats" "xz" "--compression-profile" "balanced"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Mem', /usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/vendor/xz2/src/write.rs:129:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Program', /usr/pkgsrc/wip/rust/work/rustc-1.73.0-src/vendor/xz2/src/write.rs:129:18
stack backtrace:
   0:  0xecd2b10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2455e1894ef022e0
   1:  0xed12498 - core::fmt::write::h855976d1553d9071
   2:  0xecda7fc - std::io::Write::write_fmt::hfb627c58caabce4e
   3:  0xecd28d4 - std::sys_common::backtrace::print::h50663170ec1ec8a3
   4:  0xecd3c60 - std::panicking::default_hook::{{closure}}::hfb79714ff038db5d
   5:  0xecd37a8 - std::panicking::default_hook::h62ec0bbea1c28158
   6:  0xecd53e8 - std::panicking::rust_panic_with_hook::hb41ec1d29ab2d1ba
   7:  0xecd5094 - std::panicking::begin_panic_handler::{{closure}}::h934ab9e5016e1a73
   8:  0xecd2fd8 - std::sys_common::backtrace::__rust_end_short_backtrace::h29f767293e3c2c0b
   9:  0xecd4e28 - rust_begin_unwind
  10:  0xebeede8 - core::panicking::panic_fmt::h83b04e006c5f1b7a
  11:  0xebef174 - core::result::unwrap_failed::haae0dc241f848b5d
  12:  0xec00cd8 - <xz2[56aa80380a44e612]::write::XzEncoder<std[7705438ee383069c]::io::buffered::bufwriter::BufWriter<std[7705438ee383069c]::fs::File>> as std[7705438ee383069c]::io::Write>::write
  13:  0xec01108 - <xz2[56aa80380a44e612]::write::XzEncoder<std[7705438ee383069c]::io::buffered::bufwriter::BufWriter<std[7705438ee383069c]::fs::File>> as std[7705438ee383069c]::io::Write>::write_all
  14:  0xec0d134 - <alloc[5ed73a658e58a13e]::vec::Vec<()> as alloc[5ed73a658e58a13e]::vec::spec_extend::SpecExtend<(), core[1540e49514bf7584]::iter::adapters::map::Map<core[1540e49514bf7584]::iter::adapters::take_while::TakeWhile<core[1540e49514bf7584]::iter::adapters::map::Map<core[1540e49514bf7584]::iter::adapters::map::Map<core[1540e49514bf7584]::slice::iter::IterMut<alloc[5ed73a658e58a13e]::boxed::Box<dyn installer[3ec92dd2391c9b4f]::compression::Encoder>>, &<installer[3ec92dd2391c9b4f]::compression::CombinedEncoder as std[7705438ee383069c]::io::Write>::write_all::{closure#0}>, &<core[1540e49514bf7584]::result::Result<_, _> as rayon[578a72d1c8a32669]::iter::FromParallelIterator<core[1540e49514bf7584]::result::Result<_, _>>>::from_par_iter::ok<(), std[7705438ee383069c]::io::error::Error>::{closure#0}>, <rayon[578a72d1c8a32669]::iter::while_some::WhileSomeFolder<_> as rayon[578a72d1c8a32669]::iter::plumbing::Folder<core[1540e49514bf7584]::option::Option<_>>>::consume_iter::some<()>::{closure#0}>, <core[1540e49514bf7584]::option::Option<()>>::unwrap>>>::spec_extend
  15:  0xebf84e8 - rayon[578a72d1c8a32669]::iter::plumbing::bridge_producer_consumer::helper::<rayon[578a72d1c8a32669]::slice::IterMutProducer<alloc[5ed73a658e58a13e]::boxed::Box<dyn installer[3ec92dd2391c9b4f]::compression::Encoder>>, rayon[578a72d1c8a32669]::iter::map::MapConsumer<rayon[578a72d1c8a32669]::iter::map::MapConsumer<rayon[578a72d1c8a32669]::iter::while_some::WhileSomeConsumer<rayon[578a72d1c8a32669]::iter::extend::ListVecConsumer>, <core[1540e49514bf7584]::result::Result<_, _> as rayon[578a72d1c8a32669]::iter::FromParallelIterator<core[1540e49514bf7584]::result::Result<_, _>>>::from_par_iter::ok<(), std[7705438ee383069c]::io::error::Error>::{closure#0}>, <installer[3ec92dd2391c9b4f]::compression::CombinedEncoder as std[7705438ee383069c]::io::Write>::write_all::{closure#0}>>

...

etc. etc. etc.
```

I *think* this is a roundabout way of telling me "out of virtual memory", though that is not exactly stellar clear.  One could have wished for a clearer error message.

Somewhat strangely, restarting the build made it complete, and the resulting compiler is at least able to build the `librsvg` package.

**Comment by the8472** [comment]
Note that the `install` step is a bit overkill, it first builds the distributable artifacts (the compressed tarballs) and then unpacks them again to install them locally.
Instead you can do `./x build` and extract the built rustc + tools from the build directory.

Or you can try setting `compression-profile="fast"` and `compression-formats=["gz"]` which should have less memory overhead.

**Comment by saethlin** [comment]
Reading over this error message, it looks like this is a propagated allocation error from liblzma, which is probably why it is so obscure. If the allocation failure happened in Rust, you'd get a clearer error message.

I wonder if just compressing the tarballs with `xz` would OOM your system?

**Comment by he32** [comment]
I took the largest result file:

```
-rw-r--r--  2 he  users  45182836 Oct 20 11:37 rustc-1.73.0-armv6-unknown-netbsd-eabihf.tar.xz
```

Doing `xz -f` on that file produced expected result and the process max size was 14MB.

Re-compressing with `xz --compress` (with otherwise default params) produced a 120MB process, which did not grow above that level.

This still doesn't explain why `rust-installer` grows to 1.7-1.8GB virtual size.  Is its memory consumption dependent on the size of the artifacts it wants to compress?

**Comment by the8472** [comment]
like I said, try modifying the compression settings. memory consumption depends on them.

**Comment by he32** [comment]
Illustration from `top` while installing rust 1.74.0 on NetBSD/powerpc:

```
load averages:  3.95,  3.77,  3.14;               up 61+20:46:42       11:08:03
54 processes: 52 sleeping, 2 on CPU
CPU states:  0.0% user, 92.8% nice,  7.2% system,  0.0% interrupt,  0.0% idle
Memory: 1188M Act, 583M Inact, 14M Wired, 24M Exec, 1150M File, 7736K Free
Swap: 2000M Total, 49M Used, 1951M Free / Pools: 140M Used

  PID USERNAME PRI NICE   SIZE   RES STATE       TIME   WCPU    CPU COMMAND
24935 he        23    4  1375M  594M CPU/1       1:44   199%   160% rust-instal
```
