### ISSUE TITLE
ICE in rustc during MIR construction

### ISSUE THREAD

**Issue by iamanonymouscs** [rust-lang/rust#116783]
### Code
`cat   mir_ice.rs`
```Rust
#![feature(custom_mir, core_intrinsics)]
extern crate core;
use core::intrinsics::mir::*;
fn ident<T>(t: T) -> T {
    t
}
#[custom_mir(dialect = "built")]
fn direct_call(x: i32) -> i32 {
    mir!(
        {
            Call(RET = ident(x), retblock)
        }
        retblock = {
            Return()
        }
    )
}
#[custom_mir(dialect = "built")]
fn indirect_call(x: i32, f: fn(i32) -> i32) -> i32 {
    mir!(
        {
            Call(RET = f(x), retblock)
        }
        retblock = {
            Return()
        }
    )
}
struct WriteOnDrop<'a>(&'a mut i32, i32);
impl<'a> Drop for WriteOnDrop<'a> {
    fn drop(&mut self) {
        *self.0 = self.1;
    }
}
#[custom_mir(dialect = "built")]
fn drop_first<'a>(a: WriteOnDrop<'a>, b: WriteOnDrop<'a>) {
    mir!(
        {
            Drop(a, retblock)
        }
        retblock = {
            a = Move(b);
            Return()
        }
    )
}
#[custom_mir(dialect = "built")]
fn drop_second<'a>(a: WriteOnDrop<'a>, b: WriteOnDrop<'a>) {
    mir!(
        {
            Drop(b, retblock)
        }
        retblock = {
            Return()
        }
    )
}
#[custom_mir(dialect = "built")]
fn assert_nonzero(a: i32) {
    assert_eq!(a, 0);
}
fn main() {
    assert_eq!(direct_call(5), 5);
    assert_eq!(indirect_call(5, ident), 5);
    let mut a = 0;
    let mut b = 0;
    drop_first(WriteOnDrop(&mut a, 1), WriteOnDrop(&mut b, 1));
    assert_eq!((a, b), (1, 0));
    let mut a = 0;
    let mut b = 0;
    drop_second(WriteOnDrop(&mut a, 1), WriteOnDrop(&mut b, 1));
    assert_eq!((a, b), (0, 1));
}
```
### Command
```sh
 rustc  -C opt-level=0 mir_ice.rs
```

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (42b1224e9 2023-10-15)
binary: rustc
commit-hash: 42b1224e9eb37177f608d3f6a6f2be2ee13902e4
commit-date: 2023-10-15
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.2
```

### Error output

```
warning: the feature `custom_mir` is internal to the compiler or standard library
 --> mir_ice.rs:1:12
  |
1 | #![feature(custom_mir, core_intrinsics)]
  |            ^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default

warning: value assigned to `a` is never read
  --> mir_ice.rs:42:13
   |
42 |             a = Move(b);
   |             ^
   |
   = help: maybe it is overwritten before being read?
   = note: `#[warn(unused_assignments)]` on by default

warning: unused variable: `a`
  --> mir_ice.rs:48:20
   |
48 | fn drop_second<'a>(a: WriteOnDrop<'a>, b: WriteOnDrop<'a>) {
   |                    ^ help: if this is intentional, prefix it with an underscore: `_a`
   |
   = note: `#[warn(unused_variables)]` on by default
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/build/custom/parse.rs:145:65:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f3ab46448ec - std::backtrace_rs::backtrace::libunwind::trace::hb36a1a71d07352e9
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f3ab46448ec - std::backtrace_rs::backtrace::trace_unsynchronized::hab5ecbe61dd45168
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3ab46448ec - std::sys_common::backtrace::_print_fmt::hf8f8fcaa1a8a37df
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f3ab46448ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e949e3d2f600dc6
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3ab46ac370 - core::fmt::rt::Argument::fmt::h0bed2bd6f3173100
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/fmt/rt.rs:142:9
   5:     0x7f3ab46ac370 - core::fmt::write::hcf2dc9ce923ddc63
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f3ab4637baf - std::io::Write::write_fmt::h07a32290dc729d40
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/io/mod.rs:1762:15
   7:     0x7f3ab46446d4 - std::sys_common::backtrace::_print::h80c15d8ee2444dcc
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f3ab46446d4 - std::sys_common::backtrace::print::h1ac2ff1391eb0f3d
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f3ab4647507 - std::panicking::default_hook::{{closure}}::hd8919f68d7d73a2c
  10:     0x7f3ab464724a - std::panicking::default_hook::h807e4d5d4c7a68a0
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:292:9
  11:     0x7f3ab71fabda - std[d7b1197d38436841]::panicking::update_hook::<alloc[e96338735e4e82d]::boxed::Box<rustc_driver_impl[5a32d02242522b87]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f3ab4647ca8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd3d9b0571d38460f
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/alloc/src/boxed.rs:2021:9
  13:     0x7f3ab4647ca8 - std::panicking::rust_panic_with_hook::hac974fb018631aa6
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:735:13
  14:     0x7f3ab46479b6 - std::panicking::begin_panic_handler::{{closure}}::h4a8176702702a62b
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:601:13
  15:     0x7f3ab4644e06 - std::sys_common::backtrace::__rust_end_short_backtrace::h6179cf53427f95c0
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f3ab4647732 - rust_begin_unwind
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/panicking.rs:597:5
  17:     0x7f3ab46a8995 - core::panicking::panic_fmt::h2ca7d2f7d2c65755
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/panicking.rs:72:14
  18:     0x7f3ab46a8a33 - core::panicking::panic::h70b016af14e7c9a4
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/core/src/panicking.rs:127:5
  19:     0x7f3ab8c9529c - rustc_mir_build[663d5d6570e17f4a]::build::mir_built
  20:     0x7f3ab8c8e621 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7f3ab8408b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  22:     0x7f3ab8408510 - rustc_query_impl[134db83d58928475]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7f3ab66da5fe - rustc_mir_transform[60dc20ba90af5c94]::check_unsafety::unsafety_check_result
  24:     0x7f3ab8408907 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7f3ab8408b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  26:     0x7f3ab84085d0 - rustc_query_impl[134db83d58928475]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7f3ab8409616 - rustc_mir_transform[60dc20ba90af5c94]::mir_const
  28:     0x7f3ab8409569 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f3ab8408b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  30:     0x7f3ab8408690 - rustc_query_impl[134db83d58928475]::query_impl::mir_const::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f3ab684df43 - rustc_mir_transform[60dc20ba90af5c94]::mir_promoted
  32:     0x7f3ab86e6298 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 16usize]>>
  33:     0x7f3ab86e650e - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  34:     0x7f3ab86e619d - rustc_query_impl[134db83d58928475]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f3ab9019043 - rustc_borrowck[a7ade61e6afc50c4]::mir_borrowck
  36:     0x7f3ab9018fb1 - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>
  37:     0x7f3ab8408b2c - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::VecCache<rustc_span[a7b117e47f94493d]::def_id::LocalDefId, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  38:     0x7f3ab8408750 - rustc_query_impl[134db83d58928475]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f3ab8872c69 - rustc_interface[7cfec6a7cd1a04f4]::passes::analysis
  40:     0x7f3ab88725af - rustc_query_impl[134db83d58928475]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[134db83d58928475]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 1usize]>>
  41:     0x7f3ab8e89ba6 - rustc_query_system[4f82f1838b22ca7e]::query::plumbing::try_execute_query::<rustc_query_impl[134db83d58928475]::DynamicConfig<rustc_query_system[4f82f1838b22ca7e]::query::caches::SingleCache<rustc_middle[3dc680b68da59c00]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[134db83d58928475]::plumbing::QueryCtxt, false>
  42:     0x7f3ab8e899d5 - rustc_query_impl[134db83d58928475]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7f3ab8f970b4 - std[d7b1197d38436841]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7cfec6a7cd1a04f4]::util::run_in_thread_with_globals<rustc_interface[7cfec6a7cd1a04f4]::interface::run_compiler<core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>, rustc_driver_impl[5a32d02242522b87]::run_compiler::{closure#1}>::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>
  44:     0x7f3ab8f963b3 - <<std[d7b1197d38436841]::thread::Builder>::spawn_unchecked_<rustc_interface[7cfec6a7cd1a04f4]::util::run_in_thread_with_globals<rustc_interface[7cfec6a7cd1a04f4]::interface::run_compiler<core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>, rustc_driver_impl[5a32d02242522b87]::run_compiler::{closure#1}>::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[9ee5d2235d3a5bf6]::result::Result<(), rustc_span[a7b117e47f94493d]::ErrorGuaranteed>>::{closure#1} as core[9ee5d2235d3a5bf6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x7f3ab4652c25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha0c5a651faab0494
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/alloc/src/boxed.rs:2007:9
  46:     0x7f3ab4652c25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0f4ce6187e148d85
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/alloc/src/boxed.rs:2007:9
  47:     0x7f3ab4652c25 - std::sys::unix::thread::Thread::new::thread_start::hcb407001741deea6
                               at /rustc/42b1224e9eb37177f608d3f6a6f2be2ee13902e4/library/std/src/sys/unix/thread.rs:108:17
  48:     0x7f3ab451a609 - start_thread
  49:     0x7f3ab443d133 - clone
  50:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/interesting/rustc-ice-2023-10-16T06:44:29.530580268Z-15682.txt` to your bug report

note: compiler flags: -C opt-level=0

query stack during panic:
#0 [mir_built] building MIR for `assert_nonzero`
#1 [unsafety_check_result] unsafety-checking `assert_nonzero`
#2 [mir_const] preparing `assert_nonzero` for borrow checking
#3 [mir_promoted] promoting constants in MIR for `assert_nonzero`
#4 [mir_borrowck] borrow-checking `assert_nonzero`
#5 [analysis] running analysis passes on this crate
end of query stack
warning: 3 warnings emitted
```

</p>
</details>

**Comment by Nilstrieb** [comment]
this is expected, using any internal feature incorrectly is expected to cause ICEs.
The ICE message does sadly not say this yet, thank you for the report anyways.
