### ISSUE TITLE
test `ui/backtrace-debuginfo.rs` is flaky

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#117097]
The test `ui/backtrace-debuginfo.rs` has been failing randomly in CI. The errors look like:

```
---- [ui] tests\ui\runtime\backtrace-debuginfo.rs stdout ----

error: test run failed!
status: exit code: 101
command: PATH="C:\a\rust\rust\build\i686-pc-windows-gnu\stage2\lib\rustlib\i686-pc-windows-gnu\lib;C:\a\rust\rust\build\i686-pc-windows-gnu\stage0-bootstrap-tools\i686-pc-windows-gnu\release\deps;C:\a\rust\rust\build\i686-pc-windows-gnu\stage0\bin;C:\a\rust\rust\ninja;C:\a\rust\rust\mingw32\bin;C:\hostedtoolcache\windows\Python\3.12.0\x64\Scripts;C:\hostedtoolcache\windows\Python\3.12.0\x64;C:\msys64\usr\bin;C:\a\rust\rust\sccache;C:\PROGRA~1\MongoDB\bin;C:\aliyun-cli;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS;C:\tools\zstd;C:\Program Files\Mercurial;C:\hostedtoolcache\windows\stack\2.13.1\x64;C:\cabal\bin;C:\ghcup\bin;C:\mingw64\bin;C:\Program Files\dotnet;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Program Files\R\R-4.3.1\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\npm\prefix;C:\hostedtoolcache\windows\go\1.20.10\x64\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\hostedtoolcache\windows\Ruby\2.5.9\x64\bin;C:\Program Files\OpenSSL\bin;C:\tools\kotlinc\bin;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.382-5\x64\bin;C:\Program Files\ImageMagick-7.1.1-Q16-HDRI;C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\ProgramData\Chocolatey\bin;C:\Program Files\PowerShell\7;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.7\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI;C:\tools\php;C:\Program Files (x86)\sbt\bin;C:\SeleniumWebDrivers\ChromeDriver;C:\SeleniumWebDrivers\EdgeDriver;C:\Program Files\Amazon\AWSCLIV2;C:\Program Files\Amazon\SessionManagerPlugin\bin;C:\Program Files\Amazon\AWSSAMCLI\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files (x86)\Microsoft BizTalk Server;C:\Program Files\LLVM\bin;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\.cargo\bin;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps" "C:\\a\\rust\\rust\\build\\i686-pc-windows-gnu\\test\\ui\\runtime\\backtrace-debuginfo\\a.exe"
--- stdout -------------------------------
---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:184"]

--- stdout
backtrace-debuginfo.rs:120
backtrace-debuginfo.rs:184

--- stderr
test case 0
thread 'main' panicked at C:\a\rust\rust\tests\ui\runtime\backtrace-debuginfo.rs:81:5:
explicit panic
stack backtrace:
   0: 0x66480390 - core::fmt::write::hf6ad17a1ea4b4b6c
   1: 0x66415d34 - std::io::Write::write_fmt::hd55ac99aa09403b9
   2:   0xa88718 - <unknown>
   3: 0x66422b27 - std::panicking::rust_panic_with_hook::hf6a9597b6c3b62db
   4:  0x13d3554 - std::panicking::begin_panic::{{closure}}::hc15786f9a6c83cf4
                       at /rustc/FAKE_PREFIX\library\std\src/panicking.rs:639:9
   5:  0x13d3132 - std::sys_common::backtrace::__rust_end_short_backtrace::h0586f07889c52192
                       at /rustc/FAKE_PREFIX\library\std\src\sys_common/backtrace.rs:170:18
   6:  0x13d34d0 - std::panicking::begin_panic::h77fecc14404bbcd9
                       at /rustc/FAKE_PREFIX\library\std\src/panicking.rs:638:12
   7:  0x13e5c7d - backtrace_debuginfo::inner::h5b01f04da66e8433
                       at C:\a\rust\rust\tests\ui\runtime\backtrace-debuginfo.rs:81:5
   8:  0x13e636e - backtrace_debuginfo::outer::hb144f59b805e2ef5
                       at C:\a\rust\rust\tests\ui\runtime\backtrace-debuginfo.rs:120:5
   9:   0xa88718 - <unknown>
  10:   0xa88718 - <unknown>
  11: 0x75297671 - <unknown>
  12:  0x13e778e - _main
  13:  0x13d1386 - ___tmainCRTStartup
  14: 0x75ea05c9 - <unknown>
  15: 0x779278bd - <unknown>
  16: 0x7792788d - <unknown>
------------------------------------------
--- stderr -------------------------------
thread 'main' panicked at C:\a\rust\rust\tests\ui\runtime\backtrace-debuginfo.rs:174:9:
found some errors
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------------------------------------
```

Seen failing on:
* https://github.com/rust-lang/rust/pull/107159#issuecomment-1754320939 i686-mingw
* https://github.com/rust-lang/rust/pull/115537#issuecomment-1705705610 i686-mingw
* https://github.com/rust-lang/rust/pull/110666#issuecomment-1518492177 i686-mingw-2
* https://github.com/rust-lang/rust/pull/97435#issuecomment-1140435960 i686-mingw-2
* https://github.com/rust-lang/rust/pull/82585#issuecomment-818279046 i686-mingw-2

**Comment by jieyouxu** [comment]
On Windows gnu (not msvc), I think the backtrace is not stable, cc #128911

**Comment by jieyouxu** [comment]
triage: @ehuss do you know if this is still a problem? I know this issue is ancient...

**Comment by clubby789** [comment]
Seems to be; https://github.com/rust-lang/rust/pull/131244#issuecomment-2564086577

**Comment by jieyouxu** [comment]
More specifically, in #131244 it failed on `i686-mingw`.

**Comment by jieyouxu** [comment]
Re-disabling this test for windows-gnu in #134842.
