### ISSUE TITLE
ICE when compiling `icu_locid_transform`

### ISSUE THREAD

**Issue by Berrysoft** [rust-lang/rust#117483]
### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)
binary: rustc
commit-hash: 31bc7e2c47e82798a392c770611975a6883132c8
commit-date: 2023-10-30
host: x86_64-pc-windows-msvc
release: 1.75.0-nightly
LLVM version: 17.0.3
```

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler\rustc_infer\src\infer\outlives\test_type_match.rs:46:5:
assertion failed: !verify_if_eq_b.has_escaping_bound_vars()
stack backtrace:
   0:     0x7ffb1333e64f - std::backtrace::Backtrace::force_capture::ha52447841341ca10
   1:     0x7ffb1333e5b4 - std::backtrace::Backtrace::force_capture::ha52447841341ca10
   2:     0x7ffb0c9134f7 - <tracing_subscriber[b4a61de95cdd9304]::fmt::format::Writer>::write_fmt
   3:     0x7ffb13357213 - std::panicking::rust_panic_with_hook::h7547b0ba56188f95
   4:     0x7ffb1335707b - <std::panicking::begin_panic_handler::StaticStrPayload as core::panic::PanicPayload>::take_box::h90cd8d7c238242ee
   5:     0x7ffb13354259 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h22ff4412db4a8ef2
   6:     0x7ffb13356dc4 - rust_begin_unwind
   7:     0x7ffb133bb807 - core::panicking::panic_fmt::h9993b7fa6b5d3979
   8:     0x7ffb133bb8c2 - core::panicking::panic::hb3fede680cbc7e00
   9:     0x7ffb0d9f95b2 - rustc_infer[b3b2bb3bc22e5909]::infer::outlives::test_type_match::extract_verify_if_eq
  10:     0x7ffb0b4bc8ab - <rustc_borrowck[5c9641c0b0b2135]::prefixes::Prefixes as core[91a61c20e88f426e]::iter::traits::iterator::Iterator>::next
  11:     0x7ffb0b4cda4c - <&mut rustc_borrowck[5c9641c0b0b2135]::type_check::constraint_conversion::ConstraintConversion as rustc_infer[b3b2bb3bc22e5909]::infer::outlives::obligations::TypeOutlivesDelegate>::push_sub_region_constraint
  12:     0x7ffb0c19c10b - <rustc_middle[43c180ffbcd70a42]::mir::syntax::Place as rustc_borrowck[5c9641c0b0b2135]::place_ext::PlaceExt>::ignore_borrow
  13:     0x7ffb0c19bb19 - <rustc_middle[43c180ffbcd70a42]::mir::syntax::Place as rustc_borrowck[5c9641c0b0b2135]::place_ext::PlaceExt>::ignore_borrow
  14:     0x7ffb0c19bacd - <rustc_middle[43c180ffbcd70a42]::mir::syntax::Place as rustc_borrowck[5c9641c0b0b2135]::place_ext::PlaceExt>::ignore_borrow
  15:     0x7ffb0c1b6d2a - <&mut rustc_borrowck[5c9641c0b0b2135]::type_check::constraint_conversion::ConstraintConversion as rustc_infer[b3b2bb3bc22e5909]::infer::outlives::obligations::TypeOutlivesDelegate>::push_verify
  16:     0x7ffb0c1a0c02 - <rustc_middle[43c180ffbcd70a42]::mir::syntax::Place as rustc_borrowck[5c9641c0b0b2135]::place_ext::PlaceExt>::ignore_borrow
  17:     0x7ffb0c10aef6 - <rustc_borrowck[5c9641c0b0b2135]::borrow_set::BorrowSet>::get_index_of
  18:     0x7ffb0c0e1f21 - <rustc_borrowck[5c9641c0b0b2135]::region_infer::values::PointIndex as core[91a61c20e88f426e]::ops::arith::Add<usize>>::add
  19:     0x7ffb0c095f0a - <rustc_borrowck[5c9641c0b0b2135]::MirBorrowckCtxt>::consume_operand
  20:     0x7ffb0c088717 - rustc_borrowck[5c9641c0b0b2135]::mir_borrowck
  21:     0x7ffb0c23f50f - <rustc_query_impl[c92f0bae84e526cf]::plumbing::QueryCtxt as rustc_query_system[c4ec1a0da6f21fa6]::query::QueryContext>::load_side_effects
  22:     0x7ffb0c22d22f - rustc_query_impl[c92f0bae84e526cf]::query_callbacks
  23:     0x7ffb0c30f951 - <rustc_query_impl[c92f0bae84e526cf]::plumbing::QueryCtxt as rustc_query_system[c4ec1a0da6f21fa6]::query::QueryContext>::load_side_effects
  24:     0x7ffb0c2aad02 - <rustc_query_impl[c92f0bae84e526cf]::plumbing::QueryCtxt as rustc_query_system[c4ec1a0da6f21fa6]::query::QueryContext>::load_side_effects
  25:     0x7ffb0b93bc69 - once_cell[d32db205b7b44be]::imp::initialize_or_wait
  26:     0x7ffb08af43aa - rustc_interface[6a519953d05b960]::passes::analysis
  27:     0x7ffb0b5270bd - rustc_query_impl[c92f0bae84e526cf]::profiling_support::alloc_self_profile_query_strings
  28:     0x7ffb0b543199 - rustc_query_impl[c92f0bae84e526cf]::profiling_support::alloc_self_profile_query_strings
  29:     0x7ffb0b58da58 - rustc_query_impl[c92f0bae84e526cf]::profiling_support::alloc_self_profile_query_strings
  30:     0x7ffb0b561682 - rustc_query_impl[c92f0bae84e526cf]::profiling_support::alloc_self_profile_query_strings
  31:     0x7ffb08aad4bb - <rustc_middle[43c180ffbcd70a42]::ty::SymbolName as core[91a61c20e88f426e]::fmt::Display>::fmt
  32:     0x7ffb08aab974 - <rustc_middle[43c180ffbcd70a42]::ty::SymbolName as core[91a61c20e88f426e]::fmt::Display>::fmt
  33:     0x7ffb08aa080a - rustc_driver_impl[11bb6f50d1f94169]::args::arg_expand_all
  34:     0x7ffb08aa1be1 - rustc_driver_impl[11bb6f50d1f94169]::args::arg_expand_all
  35:     0x7ffb1336a45c - std::sys::windows::thread::Thread::new::hd4756c1f6797d79f
  36:     0x7ffb897b257d - BaseThreadInitThunk
  37:     0x7ffb8b88aa58 - RtlUserThreadStart


rustc version: 1.75.0-nightly (31bc7e2c4 2023-10-30)
platform: x86_64-pc-windows-msvc

query stack during panic:
#0 [mir_borrowck] borrow-checking `expander::<impl at C:\Users\Straw\.cargo\registry\src\index.crates.io-6f17d22bba15001f\icu_locid_transform-1.3.2\src\expander.rs:184:1: 184:20>::try_new_compat`
#1 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

**Comment by lqd** [comment]
Thanks for opening an issue, this is a duplicate of #117455, and should be fixed by #117466. I'll close it as such to track the problem in a single place.

**Comment by lqd** [comment]
Thanks for opening an issue, this is a duplicate of #117455, and should be fixed by #117466. I'll close it as such to track the problem in a single place.
