### ISSUE TITLE
ICE: assertion failed: !verify_if_eq_b.has_escaping_bound_vars()

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#117455]
### Code

Check out ICU4X (tested on commit https://github.com/unicode-org/icu4x/commit/582e46cd5bac851d25eea6188e5641ad99ce8a78), and build `components/locid_transform`

### Meta

`rustc --version --verbose`:
```
$ rustc +nightly --version --verbose
rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)
binary: rustc
commit-hash: 31bc7e2c47e82798a392c770611975a6883132c8
commit-date: 2023-10-30
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3

```

However this started happening in our nightly CI since `rustc 1.75.0-nightly (608e9682f 2023-10-29)` (one nightly before this one). The PR must have landed in the recent past.

### Error output

```
[09:51:33] मanishearth@manishearth-glaptop2 ~/dev/icu4x/components/locid_transform O_o 
$ cargo +nightly c
   Compiling syn v2.0.37
   Compiling synstructure v0.13.0
   Compiling zerofrom-derive v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom/derive)
   Compiling yoke-derive v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke/derive)
   Compiling zerovec-derive v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec/derive)
   Compiling displaydoc v0.2.4
   Compiling icu_provider_macros v1.3.2 (/home/manishearth/dev/icu4x/provider/macros)
    Checking zerofrom v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom)
    Checking yoke v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke)
    Checking zerovec v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec)
    Checking tinystr v0.7.4 (/home/manishearth/dev/icu4x/utils/tinystr)
    Checking icu_locid v1.3.2 (/home/manishearth/dev/icu4x/components/locid)
    Checking icu_provider v1.3.2 (/home/manishearth/dev/icu4x/provider/core)
    Checking icu_locid_transform v1.3.2 (/home/manishearth/dev/icu4x/components/locid_transform)
thread 'rustc' panicked at compiler/rustc_infer/src/infer/outlives/test_type_match.rs:46:5:
assertion failed: !verify_if_eq_b.has_escaping_bound_vars()
stack backtrace:
   0:     0x7f8c3c812cfc - std::backtrace_rs::backtrace::libunwind::trace::h974857262e179b17
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f8c3c812cfc - std::backtrace_rs::backtrace::trace_unsynchronized::h6adce2053c056ac9
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8c3c812cfc - std::sys_common::backtrace::_print_fmt::hcf2018a5ad956761
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8c3c812cfc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3d39e48ce4d7e36f
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8c3c874f50 - core::fmt::rt::Argument::fmt::hef0ae15422a7f61d
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/fmt/rt.rs:142:9
   5:     0x7f8c3c874f50 - core::fmt::write::hf465a4ba34489409
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/fmt/mod.rs:1117:17
   6:     0x7f8c3c806c1f - std::io::Write::write_fmt::hf34ad5986fa99e89
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/io/mod.rs:1763:15
   7:     0x7f8c3c812ae4 - std::sys_common::backtrace::_print::h5aa7f1d99916c125
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f8c3c812ae4 - std::sys_common::backtrace::print::h036d85b5c81889eb
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f8c3c815777 - std::panicking::default_hook::{{closure}}::h9b311bcc8d2b2a40
  10:     0x7f8c3c8154df - std::panicking::default_hook::hd7a03fd029ce4ee2
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:292:9
  11:     0x7f8c398e06a0 - std[d7fc13cc5242579e]::panicking::update_hook::<alloc[46fb3a2f92666e24]::boxed::Box<rustc_driver_impl[88c66c37425cba72]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f8c3c815eb8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h079168172b9ee18d
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2021:9
  13:     0x7f8c3c815eb8 - std::panicking::rust_panic_with_hook::h9ec5267af19ebd61
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:783:13
  14:     0x7f8c3c815bd9 - std::panicking::begin_panic_handler::{{closure}}::hded4ae2a191a7bae
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:649:13
  15:     0x7f8c3c8131c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h3b03f6ccd27da73f
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f8c3c815972 - rust_begin_unwind
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/panicking.rs:645:5
  17:     0x7f8c3c871675 - core::panicking::panic_fmt::h290f6f1be63b094c
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/panicking.rs:72:14
  18:     0x7f8c3c871713 - core::panicking::panic::hac1e457063a02956
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/core/src/panicking.rs:127:5
  19:     0x7f8c3b9e68c5 - rustc_infer[fa218757abe60590]::infer::outlives::test_type_match::extract_verify_if_eq
  20:     0x7f8c3bbf112e - <core[53bdee0566a68c19]::iter::adapters::filter_map::FilterMap<core[53bdee0566a68c19]::iter::adapters::chain::Chain<rustc_middle[604fc891fd74f2d8]::ty::generic_args::IterInstantiated<&rustc_middle[604fc891fd74f2d8]::ty::list::List<rustc_middle[604fc891fd74f2d8]::ty::Clause>>, core[53bdee0566a68c19]::iter::adapters::copied::Copied<core[53bdee0566a68c19]::slice::iter::Iter<rustc_middle[604fc891fd74f2d8]::ty::Clause>>>, <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::generic_args::GenericArg>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty::{closure#0}> as core[53bdee0566a68c19]::iter::traits::iterator::Iterator>::next.cold.0
  21:     0x7f8c3ad5ba75 - <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::Ty>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty
  22:     0x7f8c3ad5ad00 - <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::Ty>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty
  23:     0x7f8c3ad5b438 - <rustc_infer[fa218757abe60590]::infer::outlives::for_liveness::FreeRegionsVisitor<<rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::LivenessContext>::make_all_regions_live<rustc_middle[604fc891fd74f2d8]::ty::Ty>::{closure#0}> as rustc_type_ir[d22dfb366bb74f41]::visit::TypeVisitor<rustc_middle[604fc891fd74f2d8]::ty::context::TyCtxt>>::visit_ty
  24:     0x7f8c3b6fcb44 - rustc_borrowck[1b2fc09ff996dd54]::type_check::liveness::trace::trace
  25:     0x7f8c3b37afbf - rustc_borrowck[1b2fc09ff996dd54]::type_check::type_check
  26:     0x7f8c3820b833 - rustc_borrowck[1b2fc09ff996dd54]::nll::compute_regions
  27:     0x7f8c3b7c384d - rustc_borrowck[1b2fc09ff996dd54]::do_mir_borrowck
  28:     0x7f8c3b7b3997 - rustc_borrowck[1b2fc09ff996dd54]::mir_borrowck
  29:     0x7f8c3b7b3557 - rustc_query_impl[688c8a72794c2a04]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[688c8a72794c2a04]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f8c3b212bd8 - rustc_query_system[92afb14951a5a4cf]::query::plumbing::try_execute_query::<rustc_query_impl[688c8a72794c2a04]::DynamicConfig<rustc_query_system[92afb14951a5a4cf]::query::caches::VecCache<rustc_span[88faddf4715d2d43]::def_id::LocalDefId, rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[688c8a72794c2a04]::plumbing::QueryCtxt, true>
  31:     0x7f8c3b209ef3 - rustc_query_impl[688c8a72794c2a04]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  32:     0x7f8c3b20a648 - rustc_interface[90d65b0f51490bf6]::passes::analysis
  33:     0x7f8c3b209f35 - rustc_query_impl[688c8a72794c2a04]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[688c8a72794c2a04]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 1usize]>>
  34:     0x7f8c3b4f2844 - rustc_query_system[92afb14951a5a4cf]::query::plumbing::try_execute_query::<rustc_query_impl[688c8a72794c2a04]::DynamicConfig<rustc_query_system[92afb14951a5a4cf]::query::caches::SingleCache<rustc_middle[604fc891fd74f2d8]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[688c8a72794c2a04]::plumbing::QueryCtxt, true>
  35:     0x7f8c3b4f2520 - rustc_query_impl[688c8a72794c2a04]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  36:     0x7f8c3b743643 - std[d7fc13cc5242579e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[90d65b0f51490bf6]::util::run_in_thread_with_globals<rustc_interface[90d65b0f51490bf6]::interface::run_compiler<core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>, rustc_driver_impl[88c66c37425cba72]::run_compiler::{closure#1}>::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>
  37:     0x7f8c3b742909 - <<std[d7fc13cc5242579e]::thread::Builder>::spawn_unchecked_<rustc_interface[90d65b0f51490bf6]::util::run_in_thread_with_globals<rustc_interface[90d65b0f51490bf6]::interface::run_compiler<core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>, rustc_driver_impl[88c66c37425cba72]::run_compiler::{closure#1}>::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[53bdee0566a68c19]::result::Result<(), rustc_span[88faddf4715d2d43]::ErrorGuaranteed>>::{closure#1} as core[53bdee0566a68c19]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f8c3c820c85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he310d06a8f297797
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2007:9
  39:     0x7f8c3c820c85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h69350f715ad37c20
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2007:9
  40:     0x7f8c3c820c85 - std::sys::unix::thread::Thread::new::thread_start::h7310dea1d780d6a0
                               at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f8c36ca63ec - start_thread
                               at ./nptl/pthread_create.c:444:8
  42:     0x7f8c36d26a4c - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  43:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/manishearth/dev/icu4x/rustc-ice-2023-10-31T16_51_40-491262.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `expander::<impl at components/locid_transform/src/expander.rs:184:1: 184:20>::try_new_compat`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `icu_locid_transform` (lib)

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
[09:51:33] मanishearth@manishearth-glaptop2 ~/dev/icu4x/components/locid_transform O_o 
$ cargo +nightly c
   Compiling syn v2.0.37
   Compiling synstructure v0.13.0
   Compiling zerofrom-derive v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom/derive)
   Compiling yoke-derive v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke/derive)
   Compiling zerovec-derive v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec/derive)
   Compiling displaydoc v0.2.4
   Compiling icu_provider_macros v1.3.2 (/home/manishearth/dev/icu4x/provider/macros)
    Checking zerofrom v0.1.3 (/home/manishearth/dev/icu4x/utils/zerofrom)
    Checking yoke v0.7.2 (/home/manishearth/dev/icu4x/utils/yoke)
    Checking zerovec v0.10.0 (/home/manishearth/dev/icu4x/utils/zerovec)
    Checking tinystr v0.7.4 (/home/manishearth/dev/icu4x/utils/tinystr)
    Checking icu_locid v1.3.2 (/home/manishearth/dev/icu4x/components/locid)
    Checking icu_provider v1.3.2 (/home/manishearth/dev/icu4x/provider/core)
    Checking icu_locid_transform v1.3.2 (/home/manishearth/dev/icu4x/components/locid_transform)
thread 'rustc' panicked at compiler/rustc_infer/src/infer/outlives/test_type_match.rs:46:5:
assertion failed: !verify_if_eq_b.has_escaping_bound_vars()
stack backtrace:

<snip>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/manishearth/dev/icu4x/rustc-ice-2023-10-31T16_51_40-491262.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `expander::<impl at components/locid_transform/src/expander.rs:184:1: 184:20>::try_new_compat`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `icu_locid_transform` (lib)

```

</p>
</details>

**Comment by Manishearth** [comment]
Working on bisection, so far I have this

```
1 versions remaining to test after this (roughly 1 steps)
installing nightly-2023-10-29
rust-std-nightly-x86_64-unknown-linux-gnu: 23.74 MB / 23.74 MB [=================================================] 100.00 % 7.13 MB/s testing...
RESULT: nightly-2023-10-29, ===> No
uninstalling nightly-2023-10-29

searched toolchains nightly-2023-10-28 through nightly-2023-10-30
checking last toolchain to determine final result
installing nightly-2023-10-30
rust-std-nightly-x86_64-unknown-linux-gnu: 23.72 MB / 23.72 MB [=================================================] 100.00 % 8.01 MB/s testing...
uninstalling nightly-2023-10-30


********************************************************************************
Regression in nightly-2023-10-30
********************************************************************************
```

**Comment by Manishearth** [comment]
regressed commit: https://github.com/rust-lang/rust/commit/ec2b311914a4880235862f3cd65fe24e92e6d3a5

<details>

```
fetching https://static.rust-lang.org/dist/2023-10-29/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2023-10-29: 40 B / 40 B [=====================================================================] 100.00 % 495.73 KB/s converted 2023-10-29 to e5cfc55477eceed1317a02189fdf77a4a98f2124
fetching https://static.rust-lang.org/dist/2023-10-30/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2023-10-30: 40 B / 40 B [=====================================================================] 100.00 % 572.40 KB/s converted 2023-10-30 to 608e9682f0a6482903de8d3332770104a0ad943c
looking for regression commit between 2023-10-29 and 2023-10-30
cloning rust repository
fetching (via local git) commits from e5cfc55477eceed1317a02189fdf77a4a98f2124 to 608e9682f0a6482903de8d3332770104a0ad943c
opening existing repository at "rust.git"
Found origin remote under name `origin`
refreshing repository at "rust.git"
looking up first commit
looking up second commit
checking that commits are by bors and thus have ci artifacts...
finding bors merge commits
found 9 bors merge commits in the specified range
  commit[0] 2023-10-28: Auto merge of #117149 - nnethercote:tidy-alphabetical-unit-tests, r=Nilstrieb
  commit[1] 2023-10-29: Auto merge of #116447 - oli-obk:gen_fn, r=compiler-errors
  commit[2] 2023-10-29: Auto merge of #117335 - workingjubilee:rollup-jsomm41, r=workingjubilee
  commit[3] 2023-10-29: Auto merge of #117336 - workingjubilee:rollup-6negquv, r=workingjubilee
  commit[4] 2023-10-29: Auto merge of #117354 - GuillaumeGomez:rollup-k9xtq0g, r=GuillaumeGomez
  commit[5] 2023-10-29: Auto merge of #116270 - cjgillot:gvn-aggregate, r=oli-obk,RalfJung
  commit[6] 2023-10-29: Auto merge of #116889 - MU001999:master, r=petrochenkov
  commit[7] 2023-10-29: Auto merge of #116733 - compiler-errors:alias-liveness-but-this-time-sound, r=aliemjay
  commit[8] 2023-10-29: Auto merge of #117089 - wesleywiser:update_backtrace, r=Mark-Simulacrum
validated commits found, specifying toolchains

checking the start range to verify it passes
installing e5cfc55477eceed1317a02189fdf77a4a98f2124
rust-std-nightly-x86_64-unknown-linux-gnu: 27.50 MB / 27.50 MB [=================================================] 100.00 % 4.70 MB/s testing...
RESULT: e5cfc55477eceed1317a02189fdf77a4a98f2124, ===> No
uninstalling e5cfc55477eceed1317a02189fdf77a4a98f2124

checking the end range to verify it does not pass
installing 608e9682f0a6482903de8d3332770104a0ad943c
rust-std-nightly-x86_64-unknown-linux-gnu: 27.54 MB / 27.54 MB [=================================================] 100.00 % 5.82 MB/s testing...
RESULT: 608e9682f0a6482903de8d3332770104a0ad943c, ===> Yes
uninstalling 608e9682f0a6482903de8d3332770104a0ad943c

4 versions remaining to test after this (roughly 2 steps)
installing 160fd3ceb5143100d4e06f324b02af1f9e786372
rustc-nightly-x86_64-unknown-linux-gnu: 19.18 MB / 71.71 MB [=============>------------------------------------] 26.75 % 7.03 MB/s 7s rust-std-nightly-x86_64-unknown-linux-gnu: 27.52 MB / 27.52 MB [=================================================] 100.00 % 9.80 MB/s testing...
RESULT: 160fd3ceb5143100d4e06f324b02af1f9e786372, ===> No
uninstalling 160fd3ceb5143100d4e06f324b02af1f9e786372

2 versions remaining to test after this (roughly 1 steps)
installing 88ae8c93854a1a67c6c0a45971c7198477456c33
rust-std-nightly-x86_64-unknown-linux-gnu: 27.50 MB / 27.50 MB [=================================================] 100.00 % 6.58 MB/s testing...
RESULT: 88ae8c93854a1a67c6c0a45971c7198477456c33, ===> No
uninstalling 88ae8c93854a1a67c6c0a45971c7198477456c33

1 versions remaining to test after this (roughly 1 steps)
installing ec2b311914a4880235862f3cd65fe24e92e6d3a5
rust-std-nightly-x86_64-unknown-linux-gnu: 27.52 MB / 27.52 MB [=================================================] 100.00 % 8.42 MB/s testing...
RESULT: ec2b311914a4880235862f3cd65fe24e92e6d3a5, ===> Yes
uninstalling ec2b311914a4880235862f3cd65fe24e92e6d3a5

searched toolchains e5cfc55477eceed1317a02189fdf77a4a98f2124 through 608e9682f0a6482903de8d3332770104a0ad943c


********************************************************************************
Regression in ec2b311914a4880235862f3cd65fe24e92e6d3a5
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment
==================================================================================
= Please file this regression report on the rust-lang/rust GitHub repository     =
=        New issue: https://github.com/rust-lang/rust/issues/new                 =
=     Known issues: https://github.com/rust-lang/rust/issues                     =
= Copy and paste the text below into the issue report thread.  Thanks!           =
==================================================================================

searched nightlies: from nightly-2023-10-28 to nightly-2023-10-30
regressed nightly: nightly-2023-10-30
searched commit range: https://github.com/rust-lang/rust/compare/e5cfc55477eceed1317a02189fdf77a4a98f2124...608e9682f0a6482903de8d3332770104a0ad943c
regressed commit: https://github.com/rust-lang/rust/commit/ec2b311914a4880235862f3cd65fe24e92e6d3a5

``


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-10-28 --end 2023-10-30 
```
</details>

**Comment by Manishearth** [comment]
Regression is https://github.com/rust-lang/rust/pull/116733 , cc @compiler-errors @aliemjay
