### ISSUE TITLE
Fatal Error: Unexpected type Alias(...) in Leptos project

### ISSUE THREAD

**Issue by J-Cake** [rust-lang/rust#117707]
### Code

To be honest, I'm not sure exactly what I was doing to cause this, but I'm working with Leptos, attempting to synchronise the scrolling between to elements. The gist of it is below: 

```Rust
view!(<section id="calendar" node_ref=calendar_ref on:scroll=move |_| (timeslice_scroll.set_x)(calendar_ref.get().map(|i| i.scroll_left() as f64).unwrap_or(0.0))>
  ...
</section>)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (e3abbd499 2023-09-06)
```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/closure.rs:185:25: Unexpected type Alias(Opaque, AliasTy { args: [leptos::NodeRef<leptos::html::Div>, leptos::web_sys::Element], def_id: DefId(93:3474 ~ leptos_use[339d]::use_scroll::use_scroll::{opaque#0}) }) for `Field` projection

thread 'rustc' panicked at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/compiler/rustc_errors/src/lib.rs:1651:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f2793163bec - std::backtrace_rs::backtrace::libunwind::trace::ha8fdac935a02131a
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f2793163bec - std::backtrace_rs::backtrace::trace_unsynchronized::hb68048cda790ac5f
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2793163bec - std::sys_common::backtrace::_print_fmt::h21603b010dfaab9c
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f2793163bec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8abe8125ce8cc357
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:44:22
...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f2793163bec - std::backtrace_rs::backtrace::libunwind::trace::ha8fdac935a02131a
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f2793163bec - std::backtrace_rs::backtrace::trace_unsynchronized::hb68048cda790ac5f
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2793163bec - std::sys_common::backtrace::_print_fmt::h21603b010dfaab9c
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f2793163bec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8abe8125ce8cc357
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f27931c9dfc - core::fmt::rt::Argument::fmt::h0b89466e95366624
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/core/src/fmt/rt.rs:138:9
   5:     0x7f27931c9dfc - core::fmt::write::hba3e72dd27cd44fb
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f279315662e - std::io::Write::write_fmt::h0b9ff5100202751b
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/io/mod.rs:1714:15
   7:     0x7f27931639d4 - std::sys_common::backtrace::_print::h5419658ee8e26b3e
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f27931639d4 - std::sys_common::backtrace::print::hc6e2605b7d6392d0
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2793166aca - std::panicking::panic_hook_with_disk_dump::{{closure}}::he2605802df562a55
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:280:22
  10:     0x7f27931667c5 - std::panicking::panic_hook_with_disk_dump::hca89a150bc2dd6d8
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:314:9
  11:     0x7f279634b489 - rustc_driver_impl[380ab9a1d5066bf7]::install_ice_hook::{closure#0}
  12:     0x7f2793167383 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hf824e2401af31114
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/alloc/src/boxed.rs:2021:9
  13:     0x7f2793167383 - std::panicking::rust_panic_with_hook::h64704a1b465c8f17
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/panicking.rs:757:13
  14:     0x7f279691d104 - std[672e43f96b30b94c]::panicking::begin_panic::<rustc_errors[d9a5f1ea3d50cef4]::ExplicitBug>::{closure#0}
  15:     0x7f279691aec6 - std[672e43f96b30b94c]::sys_common::backtrace::__rust_end_short_backtrace::<std[672e43f96b30b94c]::panicking::begin_panic<rustc_errors[d9a5f1ea3d50cef4]::ExplicitBug>::{closure#0}, !>
  16:     0x7f2796831696 - std[672e43f96b30b94c]::panicking::begin_panic::<rustc_errors[d9a5f1ea3d50cef4]::ExplicitBug>
  17:     0x7f2796880624 - <rustc_errors[d9a5f1ea3d50cef4]::HandlerInner>::bug::<alloc[4b180507ec4a63bb]::string::String>
  18:     0x7f27968804e6 - <rustc_errors[d9a5f1ea3d50cef4]::Handler>::bug::<alloc[4b180507ec4a63bb]::string::String>
  19:     0x7f2796897f4c - rustc_middle[84135860a2a2105]::util::bug::opt_span_bug_fmt::<rustc_span[6c623af79ae46af2]::span_encoding::Span>::{closure#0}
  20:     0x7f2796894b1a - rustc_middle[84135860a2a2105]::ty::context::tls::with_opt::<rustc_middle[84135860a2a2105]::util::bug::opt_span_bug_fmt<rustc_span[6c623af79ae46af2]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f2796894ae8 - rustc_middle[84135860a2a2105]::ty::context::tls::with_context_opt::<rustc_middle[84135860a2a2105]::ty::context::tls::with_opt<rustc_middle[84135860a2a2105]::util::bug::opt_span_bug_fmt<rustc_span[6c623af79ae46af2]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f2794807880 - rustc_middle[84135860a2a2105]::util::bug::bug_fmt
  23:     0x7f2794de98a2 - <rustc_middle[84135860a2a2105]::ty::closure::CapturedPlace>::to_symbol
  24:     0x7f27952d4534 - <core[21e80076a104f89f]::iter::adapters::map::Map<core[21e80076a104f89f]::iter::adapters::enumerate::Enumerate<core[21e80076a104f89f]::iter::adapters::zip::Zip<core[21e80076a104f89f]::slice::iter::Iter<&rustc_middle[84135860a2a2105]::ty::closure::CapturedPlace>, core[21e80076a104f89f]::iter::adapters::copied::Copied<core[21e80076a104f89f]::slice::iter::Iter<rustc_middle[84135860a2a2105]::ty::Ty>>>>, <rustc_mir_build[a1260734e06e85f6]::build::Builder>::insert_upvar_arg::{closure#0}> as core[21e80076a104f89f]::iter::traits::iterator::Iterator>::fold::<(), core[21e80076a104f89f]::iter::traits::iterator::Iterator::for_each::call<(rustc_hir[fc2af5a638eb1a90]::hir_id::HirId, rustc_mir_build[a1260734e06e85f6]::build::Capture), <alloc[4b180507ec4a63bb]::vec::Vec<(rustc_hir[fc2af5a638eb1a90]::hir_id::HirId, rustc_mir_build[a1260734e06e85f6]::build::Capture)>>::extend_trusted<core[21e80076a104f89f]::iter::adapters::map::Map<core[21e80076a104f89f]::iter::adapters::enumerate::Enumerate<core[21e80076a104f89f]::iter::adapters::zip::Zip<core[21e80076a104f89f]::slice::iter::Iter<&rustc_middle[84135860a2a2105]::ty::closure::CapturedPlace>, core[21e80076a104f89f]::iter::adapters::copied::Copied<core[21e80076a104f89f]::slice::iter::Iter<rustc_middle[84135860a2a2105]::ty::Ty>>>>, <rustc_mir_build[a1260734e06e85f6]::build::Builder>::insert_upvar_arg::{closure#0}>>::{closure#0}>::{closure#0}>
  25:     0x7f27952d147e - <alloc[4b180507ec4a63bb]::vec::Vec<(rustc_hir[fc2af5a638eb1a90]::hir_id::HirId, rustc_mir_build[a1260734e06e85f6]::build::Capture)> as alloc[4b180507ec4a63bb]::vec::spec_from_iter::SpecFromIter<(rustc_hir[fc2af5a638eb1a90]::hir_id::HirId, rustc_mir_build[a1260734e06e85f6]::build::Capture), core[21e80076a104f89f]::iter::adapters::map::Map<core[21e80076a104f89f]::iter::adapters::enumerate::Enumerate<core[21e80076a104f89f]::iter::adapters::zip::Zip<core[21e80076a104f89f]::slice::iter::Iter<&rustc_middle[84135860a2a2105]::ty::closure::CapturedPlace>, core[21e80076a104f89f]::iter::adapters::copied::Copied<core[21e80076a104f89f]::slice::iter::Iter<rustc_middle[84135860a2a2105]::ty::Ty>>>>, <rustc_mir_build[a1260734e06e85f6]::build::Builder>::insert_upvar_arg::{closure#0}>>>::from_iter
  26:     0x7f27952d122b - <rustc_data_structures[979685e57da97855]::sorted_map::index_map::SortedIndexMultiMap<usize, rustc_hir[fc2af5a638eb1a90]::hir_id::HirId, rustc_mir_build[a1260734e06e85f6]::build::Capture> as core[21e80076a104f89f]::iter::traits::collect::FromIterator<(rustc_hir[fc2af5a638eb1a90]::hir_id::HirId, rustc_mir_build[a1260734e06e85f6]::build::Capture)>>::from_iter::<core[21e80076a104f89f]::iter::adapters::map::Map<core[21e80076a104f89f]::iter::adapters::enumerate::Enumerate<core[21e80076a104f89f]::iter::adapters::zip::Zip<core[21e80076a104f89f]::slice::iter::Iter<&rustc_middle[84135860a2a2105]::ty::closure::CapturedPlace>, core[21e80076a104f89f]::iter::adapters::copied::Copied<core[21e80076a104f89f]::slice::iter::Iter<rustc_middle[84135860a2a2105]::ty::Ty>>>>, <rustc_mir_build[a1260734e06e85f6]::build::Builder>::insert_upvar_arg::{closure#0}>>
  27:     0x7f27952ca3db - rustc_mir_build[a1260734e06e85f6]::build::mir_built
  28:     0x7f27944257ec - rustc_query_impl[684e4000eafa2889]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[684e4000eafa2889]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f27944257ce - <rustc_query_impl[684e4000eafa2889]::query_impl::mir_built::dynamic_query::{closure#2} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_span[6c623af79ae46af2]::def_id::LocalDefId)>>::call_once
  30:     0x7f2794ba74b0 - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::VecCache<rustc_span[6c623af79ae46af2]::def_id::LocalDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  31:     0x7f2794e34348 - rustc_query_system[6d51a8198099840f]::query::plumbing::force_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::VecCache<rustc_span[6c623af79ae46af2]::def_id::LocalDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt>
  32:     0x7f2795cb22fb - <rustc_query_impl[684e4000eafa2889]::plumbing::query_callback<rustc_query_impl[684e4000eafa2889]::query_impl::mir_built::QueryType>::{closure#0} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_query_system[6d51a8198099840f]::dep_graph::dep_node::DepNode<rustc_middle[84135860a2a2105]::dep_graph::dep_node::DepKind>)>>::call_once
  33:     0x7f2794523768 - <rustc_query_system[6d51a8198099840f]::dep_graph::graph::DepGraphData<rustc_middle[84135860a2a2105]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt>
  34:     0x7f2794ba727b - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::VecCache<rustc_span[6c623af79ae46af2]::def_id::LocalDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  35:     0x7f2795cd193e - rustc_query_impl[684e4000eafa2889]::query_impl::unsafety_check_result::get_query_incr::__rust_end_short_backtrace
  36:     0x7f279550a2b2 - rustc_mir_transform[4994d551b28f4dfe]::check_unsafety::unsafety_check_result
  37:     0x7f279442582c - rustc_query_impl[684e4000eafa2889]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[684e4000eafa2889]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7f279442580e - <rustc_query_impl[684e4000eafa2889]::query_impl::unsafety_check_result::dynamic_query::{closure#2} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_span[6c623af79ae46af2]::def_id::LocalDefId)>>::call_once
  39:     0x7f2794ba74b0 - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::VecCache<rustc_span[6c623af79ae46af2]::def_id::LocalDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  40:     0x7f2794e34348 - rustc_query_system[6d51a8198099840f]::query::plumbing::force_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::VecCache<rustc_span[6c623af79ae46af2]::def_id::LocalDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt>
  41:     0x7f2795cae00b - <rustc_query_impl[684e4000eafa2889]::plumbing::query_callback<rustc_query_impl[684e4000eafa2889]::query_impl::unsafety_check_result::QueryType>::{closure#0} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_query_system[6d51a8198099840f]::dep_graph::dep_node::DepNode<rustc_middle[84135860a2a2105]::dep_graph::dep_node::DepKind>)>>::call_once
  42:     0x7f2794523768 - <rustc_query_system[6d51a8198099840f]::dep_graph::graph::DepGraphData<rustc_middle[84135860a2a2105]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt>
  43:     0x7f27945236fc - <rustc_query_system[6d51a8198099840f]::dep_graph::graph::DepGraphData<rustc_middle[84135860a2a2105]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt>
  44:     0x7f27945236fc - <rustc_query_system[6d51a8198099840f]::dep_graph::graph::DepGraphData<rustc_middle[84135860a2a2105]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt>
  45:     0x7f2794ba727b - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::VecCache<rustc_span[6c623af79ae46af2]::def_id::LocalDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  46:     0x7f2795cd566e - rustc_query_impl[684e4000eafa2889]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  47:     0x7f2795b6255a - rustc_hir_analysis[3c96a9a2889db8a6]::collect::type_of::type_of_opaque
  48:     0x7f27959a5621 - rustc_query_impl[684e4000eafa2889]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[684e4000eafa2889]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>
  49:     0x7f27959a5601 - <rustc_query_impl[684e4000eafa2889]::query_impl::type_of_opaque::dynamic_query::{closure#2} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_span[6c623af79ae46af2]::def_id::DefId)>>::call_once
  50:     0x7f2794f5d706 - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::DefaultCache<rustc_span[6c623af79ae46af2]::def_id::DefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  51:     0x7f2795cc85dd - rustc_query_impl[684e4000eafa2889]::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
  52:     0x7f2794d6870a - rustc_hir_analysis[3c96a9a2889db8a6]::collect::type_of::type_of
  53:     0x7f27945f4a4d - rustc_query_impl[684e4000eafa2889]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[684e4000eafa2889]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>
  54:     0x7f27945f4a10 - <rustc_query_impl[684e4000eafa2889]::query_impl::type_of::dynamic_query::{closure#2} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_span[6c623af79ae46af2]::def_id::DefId)>>::call_once
  55:     0x7f2794f5d706 - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::DefaultCache<rustc_span[6c623af79ae46af2]::def_id::DefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  56:     0x7f2795cc7cf8 - rustc_query_impl[684e4000eafa2889]::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
  57:     0x7f2794feb2c0 - rustc_middle[84135860a2a2105]::query::plumbing::query_get_at::<rustc_query_system[6d51a8198099840f]::query::caches::DefaultCache<rustc_span[6c623af79ae46af2]::def_id::DefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 8usize]>>>
  58:     0x7f2794feb02f - <rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>::expand_opaque_ty
  59:     0x7f27949d749a - <rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander as rustc_type_ir[38488b5989e33488]::fold::TypeFolder<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::fold_ty
  60:     0x7f27949d7a4b - <&rustc_middle[84135860a2a2105]::ty::list::List<rustc_middle[84135860a2a2105]::ty::Ty> as rustc_type_ir[38488b5989e33488]::fold::TypeFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>
  61:     0x7f27949d79ea - <rustc_middle[84135860a2a2105]::ty::sty::Binder<rustc_middle[84135860a2a2105]::ty::sty::FnSig> as rustc_type_ir[38488b5989e33488]::fold::TypeSuperFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::super_fold_with::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>
  62:     0x7f27949d77fc - <rustc_middle[84135860a2a2105]::ty::Ty as rustc_type_ir[38488b5989e33488]::fold::TypeSuperFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>
  63:     0x7f27949d7483 - <rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander as rustc_type_ir[38488b5989e33488]::fold::TypeFolder<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::fold_ty
  64:     0x7f27949d70ce - rustc_middle[84135860a2a2105]::ty::util::fold_list::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander, rustc_middle[84135860a2a2105]::ty::generic_args::GenericArg, <&rustc_middle[84135860a2a2105]::ty::list::List<rustc_middle[84135860a2a2105]::ty::generic_args::GenericArg> as rustc_type_ir[38488b5989e33488]::fold::TypeFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::try_fold_with<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>::{closure#0}>
  65:     0x7f27949d7816 - <rustc_middle[84135860a2a2105]::ty::Ty as rustc_type_ir[38488b5989e33488]::fold::TypeSuperFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>
  66:     0x7f27949d7483 - <rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander as rustc_type_ir[38488b5989e33488]::fold::TypeFolder<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::fold_ty
  67:     0x7f27949d6f15 - <&rustc_middle[84135860a2a2105]::ty::list::List<rustc_middle[84135860a2a2105]::ty::generic_args::GenericArg> as rustc_type_ir[38488b5989e33488]::fold::TypeFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>
  68:     0x7f27949d776b - <rustc_middle[84135860a2a2105]::ty::Ty as rustc_type_ir[38488b5989e33488]::fold::TypeSuperFoldable<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>
  69:     0x7f27949d7483 - <rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander as rustc_type_ir[38488b5989e33488]::fold::TypeFolder<rustc_middle[84135860a2a2105]::ty::context::TyCtxt>>::fold_ty
  70:     0x7f2794feb06e - <rustc_middle[84135860a2a2105]::ty::util::OpaqueTypeExpander>::expand_opaque_ty
  71:     0x7f2794fea0fe - <rustc_middle[84135860a2a2105]::ty::context::TyCtxt>::try_expand_impl_trait_type
  72:     0x7f2794fc9312 - rustc_hir_analysis[3c96a9a2889db8a6]::check::check::check_mod_item_types
  73:     0x7f279501558c - rustc_query_impl[684e4000eafa2889]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[684e4000eafa2889]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 0usize]>>
  74:     0x7f279501556e - <rustc_query_impl[684e4000eafa2889]::query_impl::check_mod_item_types::dynamic_query::{closure#2} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, rustc_span[6c623af79ae46af2]::def_id::LocalModDefId)>>::call_once
  75:     0x7f27959a5ba1 - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::DefaultCache<rustc_span[6c623af79ae46af2]::def_id::LocalModDefId, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  76:     0x7f2795cd3688 - rustc_query_impl[684e4000eafa2889]::query_impl::check_mod_item_types::get_query_incr::__rust_end_short_backtrace
  77:     0x7f27955a9967 - <rustc_middle[84135860a2a2105]::hir::map::Map>::for_each_module::<rustc_hir_analysis[3c96a9a2889db8a6]::check_crate::{closure#6}::{closure#0}>
  78:     0x7f27955a8450 - rustc_hir_analysis[3c96a9a2889db8a6]::check_crate
  79:     0x7f279559ea52 - rustc_interface[2c9f56ee7e1563bf]::passes::analysis
  80:     0x7f279584d77a - rustc_query_impl[684e4000eafa2889]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[684e4000eafa2889]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 1usize]>>
  81:     0x7f279584d769 - <rustc_query_impl[684e4000eafa2889]::query_impl::analysis::dynamic_query::{closure#2} as core[21e80076a104f89f]::ops::function::FnOnce<(rustc_middle[84135860a2a2105]::ty::context::TyCtxt, ())>>::call_once
  82:     0x7f2795b40c28 - rustc_query_system[6d51a8198099840f]::query::plumbing::try_execute_query::<rustc_query_impl[684e4000eafa2889]::DynamicConfig<rustc_query_system[6d51a8198099840f]::query::caches::SingleCache<rustc_middle[84135860a2a2105]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[684e4000eafa2889]::plumbing::QueryCtxt, true>
  83:     0x7f2795b40784 - rustc_query_impl[684e4000eafa2889]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  84:     0x7f27955cba13 - <rustc_middle[84135860a2a2105]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[380ab9a1d5066bf7]::run_compiler::{closure#1}::{closure#2}::{closure#6}, core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>>
  85:     0x7f27955caadd - <rustc_interface[2c9f56ee7e1563bf]::interface::Compiler>::enter::<rustc_driver_impl[380ab9a1d5066bf7]::run_compiler::{closure#1}::{closure#2}, core[21e80076a104f89f]::result::Result<core[21e80076a104f89f]::option::Option<rustc_interface[2c9f56ee7e1563bf]::queries::Linker>, rustc_span[6c623af79ae46af2]::ErrorGuaranteed>>
  86:     0x7f27955c1978 - std[672e43f96b30b94c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2c9f56ee7e1563bf]::util::run_in_thread_with_globals<rustc_interface[2c9f56ee7e1563bf]::interface::run_compiler<core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>, rustc_driver_impl[380ab9a1d5066bf7]::run_compiler::{closure#1}>::{closure#0}, core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>>
  87:     0x7f27955c10ee - <<std[672e43f96b30b94c]::thread::Builder>::spawn_unchecked_<rustc_interface[2c9f56ee7e1563bf]::util::run_in_thread_with_globals<rustc_interface[2c9f56ee7e1563bf]::interface::run_compiler<core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>, rustc_driver_impl[380ab9a1d5066bf7]::run_compiler::{closure#1}>::{closure#0}, core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[21e80076a104f89f]::result::Result<(), rustc_span[6c623af79ae46af2]::ErrorGuaranteed>>::{closure#1} as core[21e80076a104f89f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  88:     0x7f2793171d35 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h628520497d4b2f6e
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/alloc/src/boxed.rs:2007:9
  89:     0x7f2793171d35 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hef99eb1045ee26fe
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/alloc/src/boxed.rs:2007:9
  90:     0x7f2793171d35 - std::sys::unix::thread::Thread::new::thread_start::ha4fddad121748e56
                               at /rustc/e3abbd4994f72888f9e5e44dc89a4102e48c2a54/library/std/src/sys/unix/thread.rs:108:17
  91:     0x7f2792e8f6ba - start_thread
                               at ./nptl/pthread_create.c:444:8
  92:     0x7f2792f1e0d0 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  93:                0x0 - <unknown>
```

</p>
</details>
[rustc-ice-2023-11-08T10:25:16.444252243Z-25644.txt](https://github.com/rust-lang/rust/files/13295492/rustc-ice-2023-11-08T10.25.16.444252243Z-25644.txt)

**Comment by J-Cake** [comment]
Bit of extra digging, the [docs](https://docs.rs/leptos-use/latest/leptos_use/fn.use_scroll.html#smooth-scrolling) use a destructuring pattern, which I generally don't like, so I'm using the qualified syntax in the code example above. 

However, the compiler only crashes when not destructuring. 

```rust
let timeslice_ref = create_node_ref::<html::Div>();
let UseScrollReturn { set_x, .. } = use_scroll_with_options(timeslice_ref, UseScrollOptions::default().behavior(ScrollBehavior::Smooth));

// --- snip ---

view!(<section id="calendar" node_ref=calendar_ref 
                on:scroll=move |_| set_x(calendar_ref.get().map(|i| i.scroll_left() as f64).unwrap_or(0.0))>
 
 // --- snip ---

</section>)
```

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
