### ISSUE TITLE
thread panic handling broken on x32

### ISSUE THREAD

**Issue by plugwash** [rust-lang/rust#117859]
I tried this code:

```rust
use std::thread;
fn main() {
    let thread = thread::spawn(move || -> () {
        panic!();
    });
    println!("{:?}",thread.join());
}
```

When building the above program for x86_64-unknown-linux-gnu and running it I get

```
thread '<unnamed>' panicked at src/main.rs:4:9:
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Err(Any { .. })
```

However when building for x86_64-unknown-linux-gnux32 and running it I get.

```
thread '<unnamed>' panicked at src/main.rs:4:9:
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust cannot catch foreign exceptions
Aborted
```

### Meta
I have tested building natively with the compiler from Debian and cross building with a nightly compiler from rustup (since rust upstream don't provide a native compiler on x32).

`rustc --version --verbose`: (debian compiler)
```
rustc 1.70.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnux32
release: 1.70.0
LLVM version: 16.0.6
```

`rustc --version --verbose`: (rustup compiler)
```
rustc 1.76.0-nightly (2c1b65ee1 2023-11-11)
binary: rustc
commit-hash: 2c1b65ee1431f8d3fe2142e821eb13c623bbf8a0
commit-date: 2023-11-11
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.4
```

Note that when building with the rustup compiler I had to manually specify the linker. using the following in .cargo/config.toml

    [target.x86_64-unknown-linux-gnux32]
    linker = "x86_64-linux-gnux32-gcc

**Comment by saethlin** [comment]
I'm lazy, so instead of trying to add the target and whatnot, I tried to use `cargo-zigbuild` and was greeted with this:
```
cargo +nightly zigbuild --target=x86_64-unknown-linux-gnux32 -Zbuild-std
error: linking with `/home/ben/.cache/cargo-zigbuild/0.16.2/zigcc-x86_64-unknown-linux-gnux32.sh` failed: exit status: 1
  |
<huge linker invocation>
  = note: In file included from /usr/lib/zig/libunwind/src/libunwind.cpp:31:
          /usr/lib/zig/libunwind/src/UnwindCursor.hpp:1307:3: error: static assertion failed due to requirement 'check_fit<libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>, unw_cursor_t>::does_fit': UnwindCursor<> does not fit in unw_cursor_t
            static_assert((check_fit<UnwindCursor<A, R>, unw_cursor_t>::does_fit),
            ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          /usr/lib/zig/libunwind/src/libunwind.cpp:87:7: note: in instantiation of member function 'libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::UnwindCursor' requested here
                UnwindCursor<LocalAddressSpace, REGISTER_KIND>(
                ^
          1 error generated.
          

error: could not compile `scratch` (bin "scratch") due to previous error
```

That doesn't look good, is this an libunwind bug? cc @rust-lang/wg-llvm

**Comment by nikic** [comment]
@saethlin From a cursory look, it does not look like the x32 ABI is supported (or intended to be supported) by libunwind.
