### ISSUE TITLE
cargo xtask install --server for rust-analyzer failed with rustc 1.75.0-beta.1 (782883f60 2023-11-12)

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust#117935]
### Code

I am trying to build https://github.com/rust-lang/rust-analyzer/commit/57ef70cc08aff007d438ad6c0a85a4174319438c

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-beta.1 (782883f60 2023-11-12)
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:22:85:
called `Option::unwrap()` on a `None` value
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
    Finished dev [unoptimized] target(s) in 0.04s
     Running `target/debug/xtask install --server`
$ cargo install --path crates/rust-analyzer --locked --force --features force-always-assert
  Installing rust-analyzer v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/rust-analyzer)
    Updating crates.io index
   Compiling ide-db v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/ide-db)
   Compiling ide-assists v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/ide-assists)
   Compiling ide-completion v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/ide-completion)
   Compiling ide-ssr v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/ide-ssr)
   Compiling ide-diagnostics v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/ide-diagnostics)
   Compiling ide v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/ide)
   Compiling load-cargo v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/load-cargo)
   Compiling rust-analyzer v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/rust-analyzer)
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:22:85:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/782883f609713fe9617ba64d90086742ec62d374/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/782883f609713fe9617ba64d90086742ec62d374/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/782883f609713fe9617ba64d90086742ec62d374/library/core/src/panicking.rs:127:5
   3: <rustc_query_system::dep_graph::dep_node::DepNode as rustc_middle::dep_graph::dep_node::DepNodeExt>::extract_def_id
   4: rustc_query_impl::plumbing::force_from_dep_node::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>>
   5: <rustc_query_impl::plumbing::query_callback<rustc_query_impl::query_impl::type_of::QueryType>::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_query_system::dep_graph::dep_node::DepNode)>>::call_once
   6: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   7: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   8: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   9: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  10: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  11: <rustc_query_system::dep_graph::graph::DepGraphData<rustc_middle::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
  13: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Ty>, rustc_middle::query::erase::Erased<[u8; 1]>>>
  14: <core::iter::adapters::enumerate::Enumerate<_> as core::iter::traits::iterator::Iterator>::try_fold::enumerate::<rustc_middle::ty::Ty, (), core::ops::control_flow::ControlFlow<core::ops::control_flow::ControlFlow<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>>>, core::iter::adapters::map::map_try_fold<(usize, rustc_middle::ty::Ty), core::result::Result<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>, &rustc_middle::ty::layout::FnAbiError>, (), core::ops::control_flow::ControlFlow<core::ops::control_flow::ControlFlow<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>>>, rustc_ty_utils::abi::fn_abi_new_uncached::{closure#1}, <core::iter::adapters::GenericShunt<core::iter::adapters::map::Map<core::iter::adapters::enumerate::Enumerate<core::iter::adapters::chain::Chain<core::iter::adapters::chain::Chain<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::Ty>>, core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::ty::Ty>>>, core::option::IntoIter<rustc_middle::ty::Ty>>>, rustc_ty_utils::abi::fn_abi_new_uncached::{closure#1}>, core::result::Result<core::convert::Infallible, &rustc_middle::ty::layout::FnAbiError>> as core::iter::traits::iterator::Iterator>::try_fold<(), core::iter::traits::iterator::Iterator::try_for_each::call<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>, core::ops::control_flow::ControlFlow<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>>, core::ops::control_flow::ControlFlow<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>>::Break>::{closure#0}, core::ops::control_flow::ControlFlow<rustc_target::abi::call::ArgAbi<rustc_middle::ty::Ty>>>::{closure#0}>::{closure#0}>::{closure#0}
  15: rustc_ty_utils::abi::fn_abi_new_uncached
  16: rustc_ty_utils::abi::fn_abi_of_instance
      [... omitted 1 frame ...]
  17: <rustc_codegen_llvm::context::CodegenCx as rustc_codegen_ssa::traits::declare::PreDefineMethods>::predefine_fn
  18: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  19: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  20: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  21: rustc_interface::passes::start_codegen
  22: <rustc_interface::queries::Queries>::ongoing_codegen
  23: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.75.0-beta.1 (782883f60 2023-11-12) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C linker=/usr/bin/clang -C incremental=[REDACTED] -C link-arg=--ld-path=/usr/bin/mold

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [is_unpin_raw] computing whether `salsa::derived::slot::Memo<hir_ty::db::LayoutOfTyQuery>` is `Unpin`
#1 [fn_abi_of_instance] computing call ABI of `core::ptr::drop_in_place::<salsa::derived::slot::Memo<hir_ty::db::LayoutOfTyQuery>> - shim(Some(salsa::derived::slot::Memo<hir_ty::db::LayoutOfTyQuery>))`
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 TraitSelect(1f80f724dcbc1b14-e35a6bdf60d53538)
#1 TraitSelect(ea9eafc07fef2151-ab2d15c3b105f449)
#2 TraitSelect(33690aa3efb2d1e-2c6e67b8f973cdbd)
#3 TraitSelect(d4d2687e3ba883fa-126d58315c3396f)
#4 evaluate_obligation(4d1755f1141cbd8d-d381f834a71b511c)
#5 is_unpin_raw(795408232131d72d-b8b622c0e13e4b00)
end of try_mark_green dep node stack
error: could not compile `ide-db` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rust-analyzer v0.0.0 (/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/crates/rust-analyzer)`, intermediate artifacts can be found at `/home/evgeniy/bigdisk1/projects/rust-infra/rust-analyzer/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Error: install server

Caused by:
    command exited with non-zero code `cargo install --path crates/rust-analyzer --locked --force --features force-always-assert`: 101

```

</p>
</details>

**Comment by Dushistov** [comment]
rustc 1.73.0 (cc66ad468 2023-10-03) compiles the same commit of rust-analyzer just fine.

**Comment by Dushistov** [comment]
1.75.0-beta.2 (1bd723f02 2023-11-18) fixed the issue.
