### ISSUE TITLE
ICE: region_errors: `None` 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#118156]
auto-reduced (treereduce-rust):
````rust
#![feature(generic_const_exprs)]

struct DataWrapper<'static> {
    data: &'static [u8; Self::SIZE],
}

impl DataWrapper<'a> {
    const SIZE: usize = 14;
}


````

original:
````rust
#![feature(generic_const_exprs)]
//~^ WARN the feature `generic_const_exprs` is incomplete

struct DataWrapper<'static> {
    //~^ ERROR invalid lifetime parameter name: `'static`
    data: &'static [u8; Self::SIZE],
    //~^ ERROR use of undeclared lifetime name `'a`
    //~^ WARN the feature `generic_const_exprs` is incomplete
}

impl DataWrapper<'a> {
    //~^ ERROR undeclared lifetime
    const SIZE: usize = 14;
}

fn main(){}

````

Version information
````
rustc 1.76.0-nightly (e24e5af78 2023-11-21)
binary: rustc
commit-hash: e24e5af787f7015914cbf316063ed5821f370b71
commit-date: 2023-11-21
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0262]: invalid lifetime parameter name: `'static`
 --> /tmp/icemaker_global_tempdir.lIAQfmbdgOP6/rustc_testrunner_tmpdir_reporting.cVbqxV4zJghS/mvce.rs:3:20
  |
3 | struct DataWrapper<'static> {
  |                    ^^^^^^^ 'static is a reserved lifetime name

error[E0261]: use of undeclared lifetime name `'a`
 --> /tmp/icemaker_global_tempdir.lIAQfmbdgOP6/rustc_testrunner_tmpdir_reporting.cVbqxV4zJghS/mvce.rs:7:18
  |
7 | impl DataWrapper<'a> {
  |     -            ^^ undeclared lifetime
  |     |
  |     help: consider introducing lifetime `'a` here: `<'a>`

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.lIAQfmbdgOP6/rustc_testrunner_tmpdir_reporting.cVbqxV4zJghS/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.lIAQfmbdgOP6/rustc_testrunner_tmpdir_reporting.cVbqxV4zJghS/mvce.rs:9:2
  |
9 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.lIAQfmbdgOP6/rustc_testrunner_tmpdir_reporting.cVbqxV4zJghS/mvce.rs`

thread 'rustc' panicked at compiler/rustc_borrowck/src/diagnostics/region_errors.rs:766:52:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7fa66d1ceafc - std::backtrace_rs::backtrace::libunwind::trace::h0b040baf97a1a814
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fa66d1ceafc - std::backtrace_rs::backtrace::trace_unsynchronized::h3bb4f35c883ef0b7
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa66d1ceafc - std::sys_common::backtrace::_print_fmt::h7bc4c6c40e2dea38
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fa66d1ceafc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha29c192b6f9a05c7
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fa66d221c80 - core::fmt::rt::Argument::fmt::hd5d7e2c681722c4a
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/core/src/fmt/rt.rs:142:9
   5:     0x7fa66d221c80 - core::fmt::write::h44f28bd6729c28a7
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/core/src/fmt/mod.rs:1120:17
   6:     0x7fa66d1c291f - std::io::Write::write_fmt::h34e80b21f77f27fe
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/io/mod.rs:1762:15
   7:     0x7fa66d1ce8e4 - std::sys_common::backtrace::_print::hf6fce87ec4803f0c
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fa66d1ce8e4 - std::sys_common::backtrace::print::h2c7cd590dc94a621
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fa66d1d1577 - std::panicking::default_hook::{{closure}}::ha2265235df34f52e
  10:     0x7fa66d1d12df - std::panicking::default_hook::ha134722f286c6b3a
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/panicking.rs:292:9
  11:     0x7fa669ef42b0 - std[9e66bc0d43e7428]::panicking::update_hook::<alloc[6053f7fa92048905]::boxed::Box<rustc_driver_impl[6d46853ed3c470a0]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fa66d1d1cb8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3506115e7630eb0e
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/alloc/src/boxed.rs:2021:9
  13:     0x7fa66d1d1cb8 - std::panicking::rust_panic_with_hook::h7694bf37e5dc3efe
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/panicking.rs:783:13
  14:     0x7fa66d1d19d9 - std::panicking::begin_panic_handler::{{closure}}::h2dd4c764b0c8af53
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/panicking.rs:649:13
  15:     0x7fa66d1cefc6 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c23b4f1d73ba22d
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fa66d1d1772 - rust_begin_unwind
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/panicking.rs:645:5
  17:     0x7fa66d21e365 - core::panicking::panic_fmt::hc4f69c74680b17c4
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/core/src/panicking.rs:72:14
  18:     0x7fa66d21e403 - core::panicking::panic::hafadf320ec949d41
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/core/src/panicking.rs:127:5
  19:     0x7fa669d0af7b - <rustc_borrowck[39b32cd387d3cc8e]::MirBorrowckCtxt>::report_general_error
  20:     0x7fa669d07bce - <rustc_borrowck[39b32cd387d3cc8e]::MirBorrowckCtxt>::report_region_error
  21:     0x7fa66c0d065d - rustc_borrowck[39b32cd387d3cc8e]::do_mir_borrowck
  22:     0x7fa66c094cca - rustc_borrowck[39b32cd387d3cc8e]::mir_borrowck
  23:     0x7fa66c09476f - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>
  24:     0x7fa66b394cc3 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::VecCache<rustc_span[433598ff900853dd]::def_id::LocalDefId, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  25:     0x7fa66b394890 - rustc_query_impl[e3648600a664160f]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  26:     0x7fa668b4150b - rustc_mir_transform[de245b6feb8c03b6]::mir_drops_elaborated_and_const_checked
  27:     0x7fa66b394a35 - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>
  28:     0x7fa66b394cc3 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::VecCache<rustc_span[433598ff900853dd]::def_id::LocalDefId, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  29:     0x7fa66b394596 - rustc_query_impl[e3648600a664160f]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7fa66b3944e9 - rustc_middle[999cff9f20269db6]::query::plumbing::query_get_at::<rustc_query_system[68ab24f02628e1a4]::query::caches::VecCache<rustc_span[433598ff900853dd]::def_id::LocalDefId, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>>
  31:     0x7fa66bb92ccd - rustc_mir_transform[de245b6feb8c03b6]::mir_for_ctfe
  32:     0x7fa66b245c37 - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::mir_for_ctfe::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7fa66b244c54 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::DefaultCache<rustc_span[433598ff900853dd]::def_id::DefId, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  34:     0x7fa66bfc495e - rustc_query_impl[e3648600a664160f]::query_impl::mir_for_ctfe::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7fa66bfc4c67 - rustc_const_eval[21c4f2a446a0d210]::const_eval::eval_queries::eval_in_interpreter
  36:     0x7fa66bfc47db - rustc_const_eval[21c4f2a446a0d210]::const_eval::eval_queries::eval_to_allocation_raw_provider
  37:     0x7fa66bfc467a - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 24usize]>>
  38:     0x7fa66b8e1e8b - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::DefaultCache<rustc_middle[999cff9f20269db6]::ty::ParamEnvAnd<rustc_middle[999cff9f20269db6]::mir::interpret::GlobalId>, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  39:     0x7fa66b8e1870 - rustc_query_impl[e3648600a664160f]::query_impl::eval_to_allocation_raw::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7fa66b8e1526 - rustc_middle[999cff9f20269db6]::query::plumbing::query_get_at::<rustc_query_system[68ab24f02628e1a4]::query::caches::DefaultCache<rustc_middle[999cff9f20269db6]::ty::ParamEnvAnd<rustc_middle[999cff9f20269db6]::mir::interpret::GlobalId>, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 24usize]>>>
  41:     0x7fa66b8e0c67 - rustc_const_eval[21c4f2a446a0d210]::const_eval::eval_to_valtree
  42:     0x7fa66b8e0be2 - <rustc_const_eval[21c4f2a446a0d210]::provide::{closure#0} as core[4409ec5cd92597ed]::ops::function::FnOnce<(rustc_middle[999cff9f20269db6]::ty::context::TyCtxt, rustc_middle[999cff9f20269db6]::ty::ParamEnvAnd<rustc_middle[999cff9f20269db6]::mir::interpret::GlobalId>)>>::call_once
  43:     0x7fa66b8e0bb6 - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 24usize]>>
  44:     0x7fa66b8e0b6f - <rustc_query_impl[e3648600a664160f]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[4409ec5cd92597ed]::ops::function::FnOnce<(rustc_middle[999cff9f20269db6]::ty::context::TyCtxt, rustc_middle[999cff9f20269db6]::ty::ParamEnvAnd<rustc_middle[999cff9f20269db6]::mir::interpret::GlobalId>)>>::call_once
  45:     0x7fa66b8e1ea7 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::DefaultCache<rustc_middle[999cff9f20269db6]::ty::ParamEnvAnd<rustc_middle[999cff9f20269db6]::mir::interpret::GlobalId>, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  46:     0x7fa66b8e1770 - rustc_query_impl[e3648600a664160f]::query_impl::eval_to_valtree::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7fa66bb611a8 - rustc_middle[999cff9f20269db6]::query::plumbing::query_get_at::<rustc_query_system[68ab24f02628e1a4]::query::caches::DefaultCache<rustc_middle[999cff9f20269db6]::ty::ParamEnvAnd<rustc_middle[999cff9f20269db6]::mir::interpret::GlobalId>, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 24usize]>>>
  48:     0x7fa66b95e4ff - <rustc_middle[999cff9f20269db6]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  49:     0x7fa669874e4f - <rustc_infer[50de8a8fa00ca641]::infer::InferCtxt>::const_eval_resolve
  50:     0x7fa66bf5163e - rustc_trait_selection[f073768dbc72d10f]::traits::const_evaluatable::is_const_evaluatable
  51:     0x7fa66830b69d - <rustc_trait_selection[f073768dbc72d10f]::traits::fulfill::FulfillProcessor as rustc_data_structures[1f4db1f3361429ac]::obligation_forest::ObligationProcessor>::process_obligation
  52:     0x7fa66b210e92 - <rustc_data_structures[1f4db1f3361429ac]::obligation_forest::ObligationForest<rustc_trait_selection[f073768dbc72d10f]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[f073768dbc72d10f]::traits::fulfill::FulfillProcessor>
  53:     0x7fa66b5a1e79 - <rustc_trait_selection[f073768dbc72d10f]::traits::engine::ObligationCtxt>::select_all_or_error
  54:     0x7fa66b8b3e18 - rustc_hir_analysis[ac2ddafd5ff93a2f]::check::wfcheck::check_type_defn
  55:     0x7fa66b9efff0 - rustc_hir_analysis[ac2ddafd5ff93a2f]::check::wfcheck::check_well_formed
  56:     0x7fa66b9ef047 - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 1usize]>>
  57:     0x7fa66b9ee777 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::VecCache<rustc_hir[b19a94a0ae9cf398]::hir_id::OwnerId, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  58:     0x7fa66b9ee503 - rustc_query_impl[e3648600a664160f]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  59:     0x7fa66b9ed8c6 - rustc_hir_analysis[ac2ddafd5ff93a2f]::check::wfcheck::check_mod_type_wf
  60:     0x7fa66b9ed7fb - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 1usize]>>
  61:     0x7fa66b9ec9d5 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::DefaultCache<rustc_span[433598ff900853dd]::def_id::LocalModDefId, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  62:     0x7fa66b9ec783 - rustc_query_impl[e3648600a664160f]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  63:     0x7fa66b5b96da - <rustc_middle[999cff9f20269db6]::hir::map::Map>::try_par_for_each_module::<rustc_hir_analysis[ac2ddafd5ff93a2f]::check_crate::{closure#4}::{closure#0}>::{closure#0}
  64:     0x7fa66b5b9ed5 - rustc_hir_analysis[ac2ddafd5ff93a2f]::check_crate
  65:     0x7fa66b54e4d7 - rustc_interface[79d196cce7f623b3]::passes::analysis
  66:     0x7fa66b54e11d - rustc_query_impl[e3648600a664160f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e3648600a664160f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 1usize]>>
  67:     0x7fa66c18aac0 - rustc_query_system[68ab24f02628e1a4]::query::plumbing::try_execute_query::<rustc_query_impl[e3648600a664160f]::DynamicConfig<rustc_query_system[68ab24f02628e1a4]::query::caches::SingleCache<rustc_middle[999cff9f20269db6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e3648600a664160f]::plumbing::QueryCtxt, false>
  68:     0x7fa66c18a8c7 - rustc_query_impl[e3648600a664160f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  69:     0x7fa66c213678 - rustc_interface[79d196cce7f623b3]::interface::run_compiler::<core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>, rustc_driver_impl[6d46853ed3c470a0]::run_compiler::{closure#0}>::{closure#0}
  70:     0x7fa66c1a3054 - std[9e66bc0d43e7428]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[79d196cce7f623b3]::util::run_in_thread_with_globals<rustc_interface[79d196cce7f623b3]::util::run_in_thread_pool_with_globals<rustc_interface[79d196cce7f623b3]::interface::run_compiler<core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>, rustc_driver_impl[6d46853ed3c470a0]::run_compiler::{closure#0}>::{closure#0}, core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>>::{closure#0}, core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>>
  71:     0x7fa66c1a2e7d - <<std[9e66bc0d43e7428]::thread::Builder>::spawn_unchecked_<rustc_interface[79d196cce7f623b3]::util::run_in_thread_with_globals<rustc_interface[79d196cce7f623b3]::util::run_in_thread_pool_with_globals<rustc_interface[79d196cce7f623b3]::interface::run_compiler<core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>, rustc_driver_impl[6d46853ed3c470a0]::run_compiler::{closure#0}>::{closure#0}, core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>>::{closure#0}, core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4409ec5cd92597ed]::result::Result<(), rustc_span[433598ff900853dd]::ErrorGuaranteed>>::{closure#1} as core[4409ec5cd92597ed]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  72:     0x7fa66d1dbb75 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he2fe898dabd7bf63
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/alloc/src/boxed.rs:2007:9
  73:     0x7fa66d1dbb75 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2e31e36ca472739b
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/alloc/src/boxed.rs:2007:9
  74:     0x7fa66d1dbb75 - std::sys::unix::thread::Thread::new::thread_start::h72b7daa856b881db
                               at /rustc/e24e5af787f7015914cbf316063ed5821f370b71/library/std/src/sys/unix/thread.rs:108:17
  75:     0x7fa6670aa9eb - <unknown>
  76:     0x7fa66712e7cc - <unknown>
  77:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0-nightly (e24e5af78 2023-11-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_borrowck] borrow-checking `DataWrapper::data::{constant#0}`
#1 [mir_drops_elaborated_and_const_checked] elaborating drops for `DataWrapper::data::{constant#0}`
#2 [mir_for_ctfe] caching mir of `DataWrapper::data::{constant#0}` for CTFE
#3 [eval_to_allocation_raw] const-evaluating + checking `DataWrapper::data::{constant#0}`
#4 [eval_to_valtree] evaluating type-level constant
#5 [check_well_formed] checking that `DataWrapper` is well-formed
#6 [check_mod_type_wf] checking that types are well-formed in top-level module
#7 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0261, E0262, E0601.
For more information about an error, try `rustc --explain E0261`.

```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Not sure how this suddenly popped up and wasnt found ages ago already :| 

Regression in nightly-2022-06-08


found 7 bors merge commits in the specified range
  commit[0] 2022-06-06: Auto merge of #97730 - flip1995:clippyup, r=Manishearth
  commit[1] 2022-06-06: Auto merge of #97809 - matthiaskrgr:rollup-ajyvjd3, r=matthiaskrgr
  commit[2] 2022-06-07: Auto merge of #97801 - RalfJung:miri, r=RalfJung
  commit[3] 2022-06-07: Auto merge of #95565 - jackh726:remove-borrowck-mode, r=nikomatsakis
  commit[4] 2022-06-07: Auto merge of #97512 - scottmcm:add-coldcc, r=nagisa,lcnr
  commit[5] 2022-06-07: Auto merge of #97825 - Dylan-DPC:rollup-ya51k1k, r=Dylan-DPC
  commit[6] 2022-06-07: Auto merge of #97835 - Dylan-DPC:rollup-0ae3pwp, r=Dylan-DPC
ERROR: no CI builds available between 50b00252aeb77b10db04d65dc9e12ce758def4b5 and 5435ed6916a59e8d5acba2149316a841c3905cbd within last 167 days

**Comment by matthiaskrgr** [comment]
Ah this was fixed already in master, I just hadnt updated yet!

**Comment by matthiaskrgr** [comment]
Fixed in https://github.com/rust-lang/rust/pull/118035 :)

Seemed vaguely familiar but I didn't see my previous ticket because it was already closed as "fixed" :sweat_smile:
