### ISSUE TITLE
Failed to run custom build command for `libc v0.2.150` on macOS Apple silicon (aarch64-apple-darwin)

### ISSUE THREAD

**Issue by haba713** [rust-lang/rust#118309]
Building a project with [libc](https://crates.io/crates/libc) dependency fails on macOS Apple silicon (aarch64-apple-darwin):
```
% RUST_BACKTRACE=1 cargo build
   Compiling libc v0.2.150
error: failed to run custom build command for `libc v0.2.150`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/u2/build_test/target/debug/build/libc-4f9e2b02a856699f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at /Users/u2/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.150/build.rs:204:9:
  failed to run rustc: 
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
     1: core::panicking::panic_fmt
               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
     2: build_script_build::rustc_minor_nightly
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Steps for reproducing the issue:
```
rm -rf ~/.cargo ~/.rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
cargo init --lib build_test
cd build_test
cargo add libc 
cargo build
```

Versions:
```
% cargo tree | fgrep libc
└── libc v0.2.150

% rustc --version
rustc 1.74.0 (79e9716c9 2023-11-13)

% rustup target list --installed 
aarch64-apple-darwin

% cargo --version
cargo 1.74.0 (ecb9851af 2023-10-18)

% rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)

% uname -a
Darwin ... 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:26:43 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T8112 arm64
```

PATH:
```
% echo $PATH | tr : \\n
/Users/u2/.cargo/bin
/usr/local/bin
/System/Cryptexes/App/usr/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/Apple/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
```

**Comment by bjorn3** [comment]
For reference: https://users.rust-lang.org/t/error-failed-to-run-custom-build-command-for-libc-v0-2-150/103006/10
