### ISSUE TITLE
ICE: gce: `fn_abi_of_instance(..) failed: Layout(Unknown([FlatTree; UnevaluatedConst { .. }: usize]))`

### ISSUE THREAD

**Issue by jxors** [rust-lang/rust#118603]
### Code

```Rust
#![feature(generic_const_exprs)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
struct FlatTree;

#[derive(Copy, Clone)]
struct TreeLeaf;

#[derive(Copy, Clone)]
struct TreeNode<V, W>(V, W);

const fn const_concat<const A: usize, const B: usize>(_: [FlatTree; A], _: [FlatTree; B]) -> [FlatTree; A + B] {
    [FlatTree; A + B]
}

struct Builder<const N: usize, I> {
    ops: [FlatTree; N],
    builder: I,
}

fn create_node<const N: usize, const M: usize, A, B>(a: Builder<N, A>, b: Builder<M, B>) -> Builder<{ N + M + 1 }, TreeNode<A, B>> {
    Builder {
        ops: const_concat(const_concat::<N, M>(a.ops, b.ops), [FlatTree]),
        builder: TreeNode(a.builder, b.builder),
    }
}

const LEAF: Builder<1, TreeLeaf> = Builder {
    ops: [FlatTree],
    builder: TreeLeaf,
};

static INTERNAL_SIMPLE_BOOLEAN_TEMPLATES: &[fn()] = &[{
    fn eval() {
        create_node(LEAF, create_node(LEAF, LEAF));
    }

    eval
}];
```

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (9fad68599 2023-12-03)
binary: rustc
commit-hash: 9fad6859925b34f9a0b1af592a7839ccb1e71f60
commit-date: 2023-12-03
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Error output

```
   Compiling minimal-rust v0.1.0 (/home/../workspace/repro/minimal-rust)
[..] (warnings removed)
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:1043:21: `fn_abi_of_instance(const_concat::<{const expr}, 1>, [])` failed: Layout(Unknown([FlatTree; UnevaluatedConst { def: DefId(0:8 ~ minimal_rust[599e]::const_concat::{constant#2}), args: [(Add: 1_usize, 3_usize): usize, 1_usize] }: usize]))
  --> minimal-rust/src/lib.rs:11:1
   |
11 | const fn const_concat<const A: usize, const B: usize>(_: [FlatTree; A], _: [FlatTree; B]) -> [FlatTree; A + B] {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at /rustc/9fad6859925b34f9a0b1af592a7839ccb1e71f60/compiler/rustc_errors/src/lib.rs:995:33:
Box<dyn Any>


note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/home/../workspace/repro/rustc-ice-2023-12-04T12_27_11-290639.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=2 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `minimal-rust` (lib) generated 6 warnings
error: could not compile `minimal-rust` (lib); 6 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at /rustc/9fad6859925b34f9a0b1af592a7839ccb1e71f60/compiler/rustc_errors/src/lib.rs:995:33:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::HandlerInner>::span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
   2: <rustc_errors::Handler>::span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::FnAbiOfHelpers>::handle_fn_abi_err
   8: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::FnAbiOf>::fn_abi_of_instance::{closure#0}
   9: <rustc_codegen_llvm::context::CodegenCx as rustc_codegen_ssa::traits::declare::PreDefineMethods>::predefine_fn
  10: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  12: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  13: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  14: rustc_interface::passes::start_codegen
  15: <rustc_interface::queries::Queries>::codegen_and_build_linker
  16: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
```

</p>
</details>

**Comment by Luk-ESC** [comment]
Minimized:
```rust
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

struct Yo<const N: usize>;

const fn add<const A: usize, const B: usize>(_: Yo<A>, _: Yo<B>) -> Yo<{ A + B }> {
    Yo::<{ A + B }>
}

fn create_node<const N: usize>() -> Yo<{ N + N + 1 }> {
    add(add(Yo::<N>, Yo::<N>), Yo::<1>)
}


fn main(){
    create_node::<42>();
}
```

**Comment by compiler-errors** [comment]
No longer ICEs because we added the necessary normalization I think recently?

@rustbot label: E-needs-test

**Comment by jxors** [comment]
On `1.86.0-nightly (a580b5c37 2025-01-08` it now crashes with:

```
/rustc/a580b5c379b4fca50dfe5afc0fc0ce00921e4e00/compiler/rustc_middle/src/mir/consts.rs:333:25: Normalization of `ty::ConstKind::Expr` is unimplemented
```

**Comment by jakubadamw** [comment]
Still ICE-ing on the latest nightly (2026-08-19):

```
thread 'rustc' panicked at /rustc-dev/f7d782a3be46d6bb4b9792fe69a61db389ba1769/compiler/rustc_middle/src/mir/consts.rs:332:25:
Box<dyn Any>
stack backtrace:
   0:        0x10d201f18 - <std[6435e32e5249d112]::backtrace::Backtrace>::create
   1:        0x10b0871f8 - std[6435e32e5249d112]::panicking::update_hook::<alloc[91507a9d0c1147cb]::boxed::Box<rustc_driver_impl[56acef5a7b9db62a]::install_ice_hook::{closure#1}>>::{closure#0}
   2:        0x10d21623c - std[6435e32e5249d112]::panicking::panic_with_hook
   3:        0x10b0f33d0 - std[6435e32e5249d112]::panicking::begin_panic::<rustc_errors[577f254411a24d84]::ExplicitBug>::{closure#0}
   4:        0x10b0e605c - std[6435e32e5249d112]::sys::backtrace::__rust_end_short_backtrace::<std[6435e32e5249d112]::panicking::begin_panic<rustc_errors[577f254411a24d84]::ExplicitBug>::{closure#0}, !>
   5:        0x10d369ec8 - std[6435e32e5249d112]::panicking::begin_panic::<rustc_errors[577f254411a24d84]::ExplicitBug>
   6:        0x10d36ac90 - <rustc_errors[577f254411a24d84]::diagnostic::BugAbort as rustc_errors[577f254411a24d84]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   7:        0x10d3d03b4 - rustc_middle[73f285eb483e5141]::util::bug::opt_span_bug_fmt::<rustc_span[ef0e8f5162cea934]::span_encoding::Span>::{closure#0}
   8:        0x10bc9e0f0 - rustc_middle[73f285eb483e5141]::ty::context::tls::with_opt::<rustc_middle[73f285eb483e5141]::util::bug::opt_span_bug_fmt<rustc_span[ef0e8f5162cea934]::span_encoding::Span>::{closure#0}, !>::{closure#0}
   9:        0x10bc5fc48 - rustc_middle[73f285eb483e5141]::ty::context::tls::with_context_opt::<rustc_middle[73f285eb483e5141]::ty::context::tls::with_opt<rustc_middle[73f285eb483e5141]::util::bug::opt_span_bug_fmt<rustc_span[ef0e8f5162cea934]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  10:        0x10d3d4bac - rustc_middle[73f285eb483e5141]::util::bug::bug_fmt
  11:        0x10af4764c - <rustc_middle[73f285eb483e5141]::mir::consts::Const>::eval
  12:        0x10af3e838 - <rustc_const_eval[b38ba5363a167abe]::interpret::eval_context::InterpCx<rustc_const_eval[b38ba5363a167abe]::const_eval::machine::CompileTimeMachine>>::push_stack_frame_raw
  13:        0x10af57bf8 - rustc_const_eval[b38ba5363a167abe]::const_eval::eval_queries::eval_to_allocation_raw_provider
  14:        0x10c7c530c - rustc_query_impl[e19976bbb521a77b]::query_vtables::eval_to_allocation_raw::invoke_provider_fn::__rust_begin_short_backtrace
  15:        0x10c634cdc - rustc_query_impl[e19976bbb521a77b]::execution::try_execute_query::<rustc_middle[73f285eb483e5141]::query::caches::DefaultCache<rustc_middle[73f285eb483e5141]::ty::PseudoCanonicalInput<rustc_middle[73f285eb483e5141]::mir::interpret::GlobalId>, rustc_middle[73f285eb483e5141]::query::erase::ErasedData<[u8; 24usize]>>, false>
  16:        0x10c7c535c - rustc_query_impl[e19976bbb521a77b]::query_vtables::eval_to_allocation_raw::execute_query_non_incr::__rust_end_short_backtrace
  17:        0x10af57a40 - rustc_const_eval[b38ba5363a167abe]::const_eval::eval_queries::eval_to_allocation_raw_provider
  18:        0x10c7c530c - rustc_query_impl[e19976bbb521a77b]::query_vtables::eval_to_allocation_raw::invoke_provider_fn::__rust_begin_short_backtrace
  19:        0x10c634cdc - rustc_query_impl[e19976bbb521a77b]::execution::try_execute_query::<rustc_middle[73f285eb483e5141]::query::caches::DefaultCache<rustc_middle[73f285eb483e5141]::ty::PseudoCanonicalInput<rustc_middle[73f285eb483e5141]::mir::interpret::GlobalId>, rustc_middle[73f285eb483e5141]::query::erase::ErasedData<[u8; 24usize]>>, false>
  20:        0x10c7c535c - rustc_query_impl[e19976bbb521a77b]::query_vtables::eval_to_allocation_raw::execute_query_non_incr::__rust_end_short_backtrace
  21:        0x10af5a41c - rustc_const_eval[b38ba5363a167abe]::const_eval::valtrees::eval_to_valtree
  22:        0x10b997e20 - <rustc_const_eval[b38ba5363a167abe]::provide::{closure#0} as core[e07e215301fbc6f2]::ops::function::FnOnce<(rustc_middle[73f285eb483e5141]::ty::context::TyCtxt, rustc_middle[73f285eb483e5141]::ty::PseudoCanonicalInput<rustc_middle[73f285eb483e5141]::mir::interpret::GlobalId>)>>::call_once
  23:        0x10c7b92fc - rustc_query_impl[e19976bbb521a77b]::query_vtables::eval_to_valtree::invoke_provider_fn::__rust_begin_short_backtrace
  24:        0x10c632d90 - rustc_query_impl[e19976bbb521a77b]::execution::try_execute_query::<rustc_middle[73f285eb483e5141]::query::caches::DefaultCache<rustc_middle[73f285eb483e5141]::ty::PseudoCanonicalInput<rustc_middle[73f285eb483e5141]::mir::interpret::GlobalId>, rustc_middle[73f285eb483e5141]::query::erase::ErasedData<[u8; 16usize]>>, false>
  25:        0x10c7b9344 - rustc_query_impl[e19976bbb521a77b]::query_vtables::eval_to_valtree::execute_query_non_incr::__rust_end_short_backtrace
  26:        0x10bcc7578 - <rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  27:        0x10bcc6bb8 - <rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  28:        0x10cf2fb34 - rustc_trait_selection[590ef916f4978504]::traits::evaluate_const
  29:        0x10d018598 - <rustc_trait_selection[590ef916f4978504]::traits::query::normalize::QueryNormalizer as rustc_type_ir[ddd62fc6bcf5cedb]::fold::FallibleTypeFolder<rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>>::try_fold_const
  30:        0x10ce0d5b8 - <rustc_middle[73f285eb483e5141]::ty::Ty as rustc_type_ir[ddd62fc6bcf5cedb]::fold::TypeSuperFoldable<rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>>::try_super_fold_with::<rustc_trait_selection[590ef916f4978504]::traits::query::normalize::QueryNormalizer>
  31:        0x10d0181f8 - <rustc_trait_selection[590ef916f4978504]::traits::query::normalize::QueryNormalizer as rustc_type_ir[ddd62fc6bcf5cedb]::fold::FallibleTypeFolder<rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>>::try_fold_ty
  32:        0x10b8f38cc - rustc_traits[be2222dffce727b5]::normalize_erasing_regions::try_normalize_after_erasing_regions::<rustc_middle[73f285eb483e5141]::ty::generic_args::GenericArg>
  33:        0x10b99a35c - <rustc_traits[be2222dffce727b5]::normalize_erasing_regions::provide::{closure#0} as core[e07e215301fbc6f2]::ops::function::FnOnce<(rustc_middle[73f285eb483e5141]::ty::context::TyCtxt, rustc_middle[73f285eb483e5141]::ty::PseudoCanonicalInput<rustc_middle[73f285eb483e5141]::ty::generic_args::GenericArg>)>>::call_once
  34:        0x10c630a30 - rustc_query_impl[e19976bbb521a77b]::execution::try_execute_query::<rustc_middle[73f285eb483e5141]::query::caches::DefaultCache<rustc_middle[73f285eb483e5141]::ty::PseudoCanonicalInput<rustc_middle[73f285eb483e5141]::ty::generic_args::GenericArg>, rustc_middle[73f285eb483e5141]::query::erase::ErasedData<[u8; 8usize]>>, false>
  35:        0x10c7d0c68 - rustc_query_impl[e19976bbb521a77b]::query_vtables::try_normalize_generic_arg_after_erasing_regions::execute_query_non_incr::__rust_end_short_backtrace
  36:        0x10bce60fc - <rustc_middle[73f285eb483e5141]::ty::normalize_erasing_regions::TryNormalizeAfterErasingRegionsFolder>::try_normalize_generic_arg_after_erasing_regions
  37:        0x10c1d8fb4 - <rustc_monomorphize[53ab2e4d53199134]::collector::check_normalization_error::NormalizationChecker as rustc_type_ir[ddd62fc6bcf5cedb]::visit::TypeVisitor<rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>>::visit_ty
  38:        0x10c1a9dac - <rustc_middle[73f285eb483e5141]::mir::Body as rustc_type_ir[ddd62fc6bcf5cedb]::visit::TypeVisitable<rustc_middle[73f285eb483e5141]::ty::context::TyCtxt>>::visit_with::<rustc_monomorphize[53ab2e4d53199134]::collector::check_normalization_error::NormalizationChecker>
  39:        0x10c1d03d0 - rustc_monomorphize[53ab2e4d53199134]::collector::items_of_instance
  40:        0x10c7bde30 - rustc_query_impl[e19976bbb521a77b]::query_vtables::items_of_instance::invoke_provider_fn::__rust_begin_short_backtrace
  41:        0x10c6a5d90 - rustc_query_impl[e19976bbb521a77b]::execution::try_execute_query::<rustc_middle[73f285eb483e5141]::query::caches::DefaultCache<(rustc_middle[73f285eb483e5141]::ty::instance::Instance, rustc_middle[73f285eb483e5141]::mono::CollectionMode), rustc_middle[73f285eb483e5141]::query::erase::ErasedData<[u8; 32usize]>>, false>
  42:        0x10c7bde78 - rustc_query_impl[e19976bbb521a77b]::query_vtables::items_of_instance::execute_query_non_incr::__rust_end_short_backtrace
  43:        0x10c1ce79c - rustc_monomorphize[53ab2e4d53199134]::collector::collect_items_rec
  44:        0x10c1cf9e4 - rustc_monomorphize[53ab2e4d53199134]::collector::collect_items_rec
  45:        0x10c1cf9e4 - rustc_monomorphize[53ab2e4d53199134]::collector::collect_items_rec
  46:        0x10c1b7a58 - rustc_monomorphize[53ab2e4d53199134]::collector::collect_crate_mono_items::{closure#1}::{closure#0}
  47:        0x10c1c1a08 - rustc_monomorphize[53ab2e4d53199134]::partitioning::collect_and_partition_mono_items
  48:        0x10c7ce5dc - rustc_query_impl[e19976bbb521a77b]::query_vtables::collect_and_partition_mono_items::invoke_provider_fn::__rust_begin_short_backtrace
  49:        0x10c61bc00 - rustc_query_impl[e19976bbb521a77b]::execution::try_execute_query::<rustc_middle[73f285eb483e5141]::query::caches::SingleCache<rustc_middle[73f285eb483e5141]::query::erase::ErasedData<[u8; 24usize]>>, false>
  50:        0x10c7ce628 - rustc_query_impl[e19976bbb521a77b]::query_vtables::collect_and_partition_mono_items::execute_query_non_incr::__rust_end_short_backtrace
  51:        0x10ac32140 - rustc_codegen_ssa[d79af9a165a9459c]::base::codegen_crate::<rustc_codegen_llvm[8a84dbf1cf373f8f]::LlvmCodegenBackend, rustc_codegen_llvm[8a84dbf1cf373f8f]::ModuleLlvm>
  52:        0x10ad41f38 - <rustc_codegen_llvm[8a84dbf1cf373f8f]::LlvmCodegenBackend as rustc_codegen_ssa[d79af9a165a9459c]::traits::backend::CodegenBackend>::codegen_crate
  53:        0x10b9296f4 - <rustc_interface[d2ca564089294641]::queries::Linker>::codegen_and_build_linker
  54:        0x10b020788 - rustc_interface[d2ca564089294641]::passes::create_and_enter_global_ctxt::<core[e07e215301fbc6f2]::option::Option<rustc_interface[d2ca564089294641]::queries::Linker>, rustc_driver_impl[56acef5a7b9db62a]::run_compiler::{closure#0}::{closure#1}>
  55:        0x10b08a62c - rustc_interface[d2ca564089294641]::interface::run_compiler::<(), rustc_driver_impl[56acef5a7b9db62a]::run_compiler::{closure#0}>::{closure#2}
  56:        0x10b07d030 - std[6435e32e5249d112]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d2ca564089294641]::util::run_in_thread_with_globals<rustc_interface[d2ca564089294641]::util::run_in_thread_pool_with_globals<rustc_interface[d2ca564089294641]::interface::run_compiler<(), rustc_driver_impl[56acef5a7b9db62a]::run_compiler::{closure#0}>::{closure#2}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  57:        0x10b08da00 - <std[6435e32e5249d112]::thread::lifecycle::spawn_unchecked<rustc_interface[d2ca564089294641]::util::run_in_thread_with_globals<rustc_interface[d2ca564089294641]::util::run_in_thread_pool_with_globals<rustc_interface[d2ca564089294641]::interface::run_compiler<(), rustc_driver_impl[56acef5a7b9db62a]::run_compiler::{closure#0}>::{closure#2}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[e07e215301fbc6f2]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:        0x10d221074 - <std[6435e32e5249d112]::sys::thread::unix::Thread>::new::thread_start
  59:        0x18aadbc58 - __pthread_cond_wait


rustc version: 1.100.0-nightly (f7d782a3b 2026-08-19)
platform: aarch64-apple-darwin

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `const_concat::{constant#2}`
#1 [eval_to_allocation_raw] const-evaluating + checking `const_concat::{constant#2}`
#2 [eval_to_valtree] evaluating type-level constant
#3 [try_normalize_generic_arg_after_erasing_regions] normalizing `[FlatTree; A + B]`
#4 [items_of_instance] collecting items used by `create_node::<ValTree(Leaf(0x0000000000000001): usize), ValTree(Leaf(0x0000000000000001): usize), TreeLeaf, TreeLeaf>`
#5 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

@rustbot label -E-needs-test
