### ISSUE TITLE
Parallel front-end: [ICE] when trying to `RUSTFLAGS="-Z threads=8" cargo install --path=alacritty`

### ISSUE THREAD

**Issue by a6delwaha6z** [rust-lang/rust#118776]
### Repo

https://github.com/alacritty/alacritty

### Meta

`rustc --version --verbose`:
```
rustcrustc 1.76.0-nightly (1fdfe1234 2023-12-06)
binary: rustc
commit-hash: 1fdfe1234795a289af1088aefa92ef80191cb611
commit-date: 2023-12-06
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_data_structures/src/jobserver.rs:73:33:
  jobserver check should have been called earlier
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
0:     0x7f279efa945c - std::backtrace_rs::backtrace::libunwind::trace::h01adf09c1aaf2eab
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
     1:     0x7f279efa945c - std::backtrace_rs::backtrace::trace_unsynchronized::hb3620698cc0798b4
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x7f279efa945c - std::sys_common::backtrace::_print_fmt::h56e5d560c8c09485
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/sys_common/backtrace.rs:68:5
     3:     0x7f279efa945c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hca9d80fb6e5ad5fe
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x7f279effc4a0 - core::fmt::rt::Argument::fmt::he80c0e0f0c31e8da
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/core/src/fmt/rt.rs:142:9
     5:     0x7f279effc4a0 - core::fmt::write::h7acb2cb5522bc491
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/core/src/fmt/mod.rs:1120:17
     6:     0x7f279ef9d2bf - std::io::Write::write_fmt::h19435141596ff66c
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/io/mod.rs:1810:15
     7:     0x7f279efa9244 - std::sys_common::backtrace::_print::h062a00a21ffc3dcb
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x7f279efa9244 - std::sys_common::backtrace::print::h120ea2df27b2be8f
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x7f279efabed7 - std::panicking::default_hook::{{closure}}::hd7e3d5fa26e2ca93
    10:     0x7f279efabc3f - std::panicking::default_hook::h541732093fb638b5
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/panicking.rs:292:9
    11:     0x7f279bcf4190 - std[f18d9e43faf8528d]::panicking::update_hook::<alloc[c27557bba15c8b11]::boxed::Box<rustc_driver_impl[c56fb6e317b9b549]::install_ice_hook::{closure#0}>>::{closure#0}
    12:     0x7f279efac618 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h04510f5933ee8fe9
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/alloc/src/boxed.rs:2029:9
    13:     0x7f279efac618 - std::panicking::rust_panic_with_hook::h10b8d62d65c23db7
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/panicking.rs:783:13
    14:     0x7f279efac36e - std::panicking::begin_panic_handler::{{closure}}::h2bc5b33298108b9d
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/panicking.rs:657:13
    15:     0x7f279efa9926 - std::sys_common::backtrace::__rust_end_short_backtrace::h4d52701c18fca37f
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/sys_common/backtrace.rs:171:18
    16:     0x7f279efac0d2 - rust_begin_unwind
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/panicking.rs:645:5
    17:     0x7f279eff8b65 - core::panicking::panic_fmt::hc7d083b823bc25c6
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/core/src/panicking.rs:72:14
    18:     0x7f279eff8913 - core::panicking::panic_display::he67f8f212ca6850c
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/core/src/panicking.rs:196:5
    19:     0x7f279eff8913 - core::panicking::panic_str::h80d96e2361b552dc
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/core/src/panicking.rs:171:5
    20:     0x7f279eff8913 - core::option::expect_failed::hc53d5bf30a61945b
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/core/src/option.rs:1980:5
    21:     0x7f279bccf5cb - rustc_data_structures[e65f6cb355c9ed62]::jobserver::acquire_thread
    22:     0x7f279b8f62d2 - <rayon_core[d8d19e7dd9b22867]::registry::ThreadBuilder>::run
    23:     0x7f279bcf6077 - <<crossbeam_utils[3cd6860fb57732e3]::thread::ScopedThreadBuilder>::spawn<<rayon_core[d8d19e7dd9b22867]::ThreadPoolBuilder>::build_scoped<rustc_interface[921a47194d6ebb65]::util::run_in_thread_pool_with_globals<rustc_interface[921a47194d6ebb65]::interface::run_compiler<core[c8ad60286a7f2b9c]::result::Result<(), rustc_span[b99ab2601ab4e12]::ErrorGuaranteed>, rustc_driver_impl[c56fb6e317b9b549]::run_compiler::{closure#0}>::{closure#0}, core[c8ad60286a7f2b9c]::result::Result<(), rustc_span[b99ab2601ab4e12]::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}, rustc_interface[921a47194d6ebb65]::util::run_in_thread_pool_with_globals<rustc_interface[921a47194d6ebb65]::interface::run_compiler<core[c8ad60286a7f2b9c]::result::Result<(), rustc_span[b99ab2601ab4e12]::ErrorGuaranteed>, rustc_driver_impl[c56fb6e317b9b549]::run_compiler::{closure#0}>::{closure#0}, core[c8ad60286a7f2b9c]::result::Result<(), rustc_span[b99ab2601ab4e12]::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#1}, core[c8ad60286a7f2b9c]::result::Result<(), rustc_span[b99ab2601ab4e12]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0} as core[c8ad60286a7f2b9c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
    24:     0x7f279bcef4fe - std[f18d9e43faf8528d]::sys_common::backtrace::__rust_begin_short_backtrace::<alloc[c27557bba15c8b11]::boxed::Box<dyn core[c8ad60286a7f2b9c]::ops::function::FnOnce<(), Output = ()> + core[c8ad60286a7f2b9c]::marker::Send>, ()>
    25:     0x7f279bcf5d03 - <<std[f18d9e43faf8528d]::thread::Builder>::spawn_unchecked_<alloc[c27557bba15c8b11]::boxed::Box<dyn core[c8ad60286a7f2b9c]::ops::function::FnOnce<(), Output = ()> + core[c8ad60286a7f2b9c]::marker::Send>, ()>::{closure#1} as core[c8ad60286a7f2b9c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
    26:     0x7f279efb64a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcbb69bf7124e2abe
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/alloc/src/boxed.rs:2015:9
    27:     0x7f279efb64a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7be566a46ffc8b21
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/alloc/src/boxed.rs:2015:9
    28:     0x7f279efb64a5 - std::sys::unix::thread::Thread::new::thread_start::hd7af3ffb69b86edf
                                 at /rustc/1fdfe1234795a289af1088aefa92ef80191cb611/library/std/src/sys/unix/thread.rs:108:17
    29:     0x7f2798eaa9eb - <unknown>
    30:     0x7f2798f2e7cc - <unknown>
    31:                0x0 - <unknown>
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Could you please try with an updated nightly, I believe this might have been fixed recently.

**Comment by a6delwaha6z** [comment]
it's working thanks.
