### ISSUE TITLE
Transient Internal Compiler Error: operand Len((*_2)) already assigned

### ISSUE THREAD

**Issue by austinmoore-** [rust-lang/rust#118755]
### Code

N/A

### Meta

*Note:* I don't have shell access to the build system that did the build, so I can't run the verbose command, but the build does log a version that's hopefully descriptive enough:
```
stable-aarch64-unknown-linux-gnu unchanged - rustc 1.74.0 (79e9716c9 2023-11-13)
```

I also have hardware info:
```
 hardware_system_info:
    cpuarch = aarch64
    cpucount = 0
    cpuspeed = 0
    cputype = Xen
    kernel = 5.4.257
    manufacturer = Xen
    meminstalled = 126524MB
system_resources:
    cpu_mhz = 0
    disk_gb = 0
    memory_mb = 126524 
```

This error occured during a build only once. The build retried automatically and the second attempt was successful. The retry build ran on a different host, but the above information is the same between the two hosts. The `rustc` version is the same between the two hosts as well.

### Error output

```
error: internal compiler error: /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/compiler/rustc_codegen_ssa/src/mir/statement.rs:28:33: operand Len((*_2)) already assigned
--> /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/impls.rs:236:28
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/compiler/rustc_errors/src/lib.rs:995:33:
Box<dyn Any>
stack backtrace:
   0:     0xffff84dfea38 - std::backtrace_rs::backtrace::libunwind::trace::h6d78809c63e05a4f
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xffff84dfea38 - std::backtrace_rs::backtrace::trace_unsynchronized::hc74607bef8c2be48
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xffff84dfea38 - std::sys_common::backtrace::_print_fmt::h8a65788a1e62eccd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xffff84dfea38 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73a7ca41f87c483e
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xffff84e5cb4c - core::fmt::rt::Argument::fmt::hd82398f3343a4ba7
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0xffff84e5cb4c - core::fmt::write::hac8419432dce6b91
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0xffff84df1efc - std::io::Write::write_fmt::h587e5999cbd3372c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0xffff84dfe86c - std::sys_common::backtrace::_print::h6f3e1b90ee7060bb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xffff84dfe86c - std::sys_common::backtrace::print::h81d8d1318bbda281
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xffff84e0137c - std::panicking::default_hook::{{closure}}::h1357db1f906d50dc
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0xffff84e01090 - std::panicking::default_hook::h416c3597c8a2a9dd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0xffff86153aac - std[428620bee9cc31a5]::panicking::update_hook::<alloc[717fdc1343418ad5]::boxed::Box<rustc_driver_impl[8f022859ec6033f]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0xffff84e01c38 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha389d89fd865e8c6
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  13:     0xffff84e01c38 - std::panicking::rust_panic_with_hook::h428adbdedead02c4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
  14:     0xffff863fadf8 - std[428620bee9cc31a5]::panicking::begin_panic::<rustc_errors[e14d5fb2eedad70d]::ExplicitBug>::{closure#0}
  15:     0xffff863f6b70 - std[428620bee9cc31a5]::sys_common::backtrace::__rust_end_short_backtrace::<std[428620bee9cc31a5]::panicking::begin_panic<rustc_errors[e14d5fb2eedad70d]::ExplicitBug>::{closure#0}, !>
  16:     0xffff86363520 - std[428620bee9cc31a5]::panicking::begin_panic::<rustc_errors[e14d5fb2eedad70d]::ExplicitBug>
  17:     0xffff863633cc - <rustc_errors[e14d5fb2eedad70d]::HandlerInner>::span_bug::<rustc_span[8548a0259bbb10c5]::span_encoding::Span, alloc[717fdc1343418ad5]::string::String>
  18:     0xffff86363198 - <rustc_errors[e14d5fb2eedad70d]::Handler>::span_bug::<rustc_span[8548a0259bbb10c5]::span_encoding::Span, alloc[717fdc1343418ad5]::string::String>
  19:     0xffff863dfe94 - rustc_middle[97fe60a8638052d0]::util::bug::opt_span_bug_fmt::<rustc_span[8548a0259bbb10c5]::span_encoding::Span>::{closure#0}
  20:     0xffff863dfec8 - rustc_middle[97fe60a8638052d0]::ty::context::tls::with_opt::<rustc_middle[97fe60a8638052d0]::util::bug::opt_span_bug_fmt<rustc_span[8548a0259bbb10c5]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0xffff863de57c - rustc_middle[97fe60a8638052d0]::ty::context::tls::with_context_opt::<rustc_middle[97fe60a8638052d0]::ty::context::tls::with_opt<rustc_middle[97fe60a8638052d0]::util::bug::opt_span_bug_fmt<rustc_span[8548a0259bbb10c5]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0xffff863ddc88 - rustc_middle[97fe60a8638052d0]::util::bug::span_bug_fmt::<rustc_span[8548a0259bbb10c5]::span_encoding::Span>
  23:     0xffff8641887c - rustc_codegen_ssa[c888f21873c0e9e1]::mir::codegen_mir::<rustc_codegen_llvm[ded3916feab40b9]::builder::Builder>
  24:     0xffff8632c56c - rustc_codegen_ssa[c888f21873c0e9e1]::base::codegen_instance::<rustc_codegen_llvm[ded3916feab40b9]::builder::Builder>
  25:     0xffff863afc90 - rustc_codegen_llvm[ded3916feab40b9]::base::compile_codegen_unit::module_codegen
  26:     0xffff863af04c - rustc_codegen_llvm[ded3916feab40b9]::base::compile_codegen_unit
  27:     0xffff8632bfd0 - rustc_codegen_ssa[c888f21873c0e9e1]::base::codegen_crate::<rustc_codegen_llvm[ded3916feab40b9]::LlvmCodegenBackend>
  28:     0xffff86411bf8 - <rustc_codegen_llvm[ded3916feab40b9]::LlvmCodegenBackend as rustc_codegen_ssa[c888f21873c0e9e1]::traits::backend::CodegenBackend>::codegen_crate
  29:     0xffff8630bb68 - <rustc_session[74285ec5dc937c1a]::session::Session>::time::<alloc[717fdc1343418ad5]::boxed::Box<dyn core[4c63b776d8322acf]::any::Any>, rustc_interface[4267ecb2f28156d3]::passes::start_codegen::{closure#0}>
  30:     0xffff862fad5c - rustc_interface[4267ecb2f28156d3]::passes::start_codegen
  31:     0xffff8630fd34 - <rustc_middle[97fe60a8638052d0]::ty::context::GlobalCtxt>::enter::<<rustc_interface[4267ecb2f28156d3]::queries::Queries>::ongoing_codegen::{closure#0}, core[4c63b776d8322acf]::result::Result<alloc[717fdc1343418ad5]::boxed::Box<dyn core[4c63b776d8322acf]::any::Any>, rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>>
  32:     0xffff862d1fe8 - <rustc_interface[4267ecb2f28156d3]::queries::Queries>::ongoing_codegen
  33:     0xffff86162d50 - rustc_span[8548a0259bbb10c5]::set_source_map::<core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>, rustc_interface[4267ecb2f28156d3]::interface::run_compiler<core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>, rustc_driver_impl[8f022859ec6033f]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  34:     0xffff86152d38 - std[428620bee9cc31a5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4267ecb2f28156d3]::util::run_in_thread_with_globals<rustc_interface[4267ecb2f28156d3]::interface::run_compiler<core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>, rustc_driver_impl[8f022859ec6033f]::run_compiler::{closure#1}>::{closure#0}, core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>>
  35:     0xffff86153f14 - <<std[428620bee9cc31a5]::thread::Builder>::spawn_unchecked_<rustc_interface[4267ecb2f28156d3]::util::run_in_thread_with_globals<rustc_interface[4267ecb2f28156d3]::interface::run_compiler<core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>, rustc_driver_impl[8f022859ec6033f]::run_compiler::{closure#1}>::{closure#0}, core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[4c63b776d8322acf]::result::Result<(), rustc_span[8548a0259bbb10c5]::ErrorGuaranteed>>::{closure#1} as core[4c63b776d8322acf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0xffff84e0bae4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39408ba95e9dc68d
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  37:     0xffff84e0bae4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h340f92479af1d47d
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  38:     0xffff84e0bae4 - std::sys::unix::thread::Thread::new::thread_start::hed80bff1db5471de
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
  39:     0xffff84cab22c - start_thread
  40:     0xffff84bf279c - thread_start
  41:                0x0 - <unknown>
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball) running on aarch64-unknown-linux-gnu
note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C target-cpu=cortex-a57 -C link-args=-Wl,--as-needed -pthread -g -C linker=/usr/bin/gcc -C rpath=y -C link-arg=-Wl,--disable-new-dtags -C link-arg=-Wl,-rpath,<snipped-path> -C instrument-coverage -C link-arg=-Wl,--unresolved-symbols=ignore-in-object-files
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
```

</p>
</details>

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
