### ISSUE TITLE
Crash on documenting futures-rs with nightly compiler.

### ISSUE THREAD

**Issue by Frostie314159** [rust-lang/rust#118829]
### Code
See futures-rs github repo.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (503e12932 2023-12-07)
binary: rustc
commit-hash: 503e129328080e924c0ddfca6abf4c2812580102
commit-date: 2023-12-07
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_infer/src/infer/generalize.rs:28:40:
called `Result::unwrap_err()` on an `Ok` value: ?14t
stack backtrace:
   0:     0x7fbf74772da1 - std::backtrace_rs::backtrace::libunwind::trace::h815354fef816bc86
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fbf74772da1 - std::backtrace_rs::backtrace::trace_unsynchronized::hc83922bfc5a9ca50
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbf74772da1 - std::backtrace::Backtrace::create::hc02515a069387304
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/backtrace.rs:332:13
   3:     0x7fbf74772cf0 - std::backtrace::Backtrace::force_capture::h02194f1a0abef8b0
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/backtrace.rs:313:9
   4:     0x7fbf774f83dc - std[ce0584ef05f9a8b4]::panicking::update_hook::<alloc[9ee1258aa4f01231]::boxed::Box<rustc_driver_impl[42a0b4a1f0a933f6]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7fbf7478e618 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4054d74742b8ea41
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2029:9
   6:     0x7fbf7478e618 - std::panicking::rust_panic_with_hook::hbafd4f0baa9fdb9e
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:783:13
   7:     0x7fbf7478e36e - std::panicking::begin_panic_handler::{{closure}}::h4c976a34ccffa9e2
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:657:13
   8:     0x7fbf7478b926 - std::sys_common::backtrace::__rust_end_short_backtrace::h675039fe30aa0955
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x7fbf7478e0d2 - rust_begin_unwind
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/panicking.rs:645:5
  10:     0x7fbf747dab65 - core::panicking::panic_fmt::h32ca55ac70be178d
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/panicking.rs:72:14
  11:     0x7fbf747db273 - core::result::unwrap_failed::h179c95b92f11ec78
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/core/src/result.rs:1649:5
  12:     0x7fbf7885b2c8 - <rustc_infer[8d75f53857709946]::infer::equate::Equate as rustc_middle[3b7dc7f1ac8ce2bc]::ty::relate::TypeRelation>::tys
  13:     0x7fbf78efc9f4 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  14:     0x7fbf7592f0d8 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::poly_select
  15:     0x7fbf78ab7645 - rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::opt_normalize_projection_type
  16:     0x7fbf78a4b42a - rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::poly_project_and_unify_type
  17:     0x7fbf795482c6 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_predicate_recursively
  18:     0x7fbf79547f8b - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_predicates_recursively::<alloc[9ee1258aa4f01231]::vec::Vec<rustc_infer[8d75f53857709946]::traits::Obligation<rustc_middle[3b7dc7f1ac8ce2bc]::ty::Predicate>>>
  19:     0x7fbf795484b3 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_predicate_recursively
  20:     0x7fbf78f07a46 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  21:     0x7fbf7592f0d8 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::poly_select
  22:     0x7fbf78ab7645 - rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::opt_normalize_projection_type
  23:     0x7fbf78ab55f8 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::AssocTypeNormalizer as rustc_type_ir[ee20701d43e568e4]::fold::TypeFolder<rustc_middle[3b7dc7f1ac8ce2bc]::ty::context::TyCtxt>>::fold_ty
  24:     0x7fbf78ab4608 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::AssocTypeNormalizer as rustc_type_ir[ee20701d43e568e4]::fold::TypeFolder<rustc_middle[3b7dc7f1ac8ce2bc]::ty::context::TyCtxt>>::fold_predicate
  25:     0x7fbf7924b34a - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::confirm_candidate
  26:     0x7fbf7923e611 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_candidate
  27:     0x7fbf78f01584 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  28:     0x7fbf7592f0d8 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::poly_select
  29:     0x7fbf78ab7645 - rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::opt_normalize_projection_type
  30:     0x7fbf78ab55f8 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::AssocTypeNormalizer as rustc_type_ir[ee20701d43e568e4]::fold::TypeFolder<rustc_middle[3b7dc7f1ac8ce2bc]::ty::context::TyCtxt>>::fold_ty
  31:     0x7fbf78abccf4 - rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::opt_normalize_projection_type
  32:     0x7fbf78a4b42a - rustc_trait_selection[cc4a1b9dcbaa9312]::traits::project::poly_project_and_unify_type
  33:     0x7fbf7923ed00 - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_candidate
  34:     0x7fbf791e745c - <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_trait_predicate_recursively
  35:     0x7fbf7954258d - <rustc_infer[8d75f53857709946]::infer::InferCtxt>::probe::<core[a6856156d288c90]::result::Result<rustc_middle[3b7dc7f1ac8ce2bc]::traits::select::EvaluationResult, rustc_middle[3b7dc7f1ac8ce2bc]::traits::select::OverflowError>, <rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluation_probe<<rustc_trait_selection[cc4a1b9dcbaa9312]::traits::select::SelectionContext>::evaluate_root_obligation::{closure#0}>::{closure#0}>
  36:     0x7fbf78a0e890 - rustc_traits[6896ab33d75d3fc9]::evaluate_obligation::evaluate_obligation
  37:     0x7fbf78a0e260 - rustc_query_impl[d233ef11b2077f1a]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d233ef11b2077f1a]::query_impl::evaluate_obligation::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3b7dc7f1ac8ce2bc]::query::erase::Erased<[u8; 2usize]>>
  38:     0x7fbf78a0d810 - rustc_query_system[50084ec5a8fda77a]::query::plumbing::try_execute_query::<rustc_query_impl[d233ef11b2077f1a]::DynamicConfig<rustc_query_system[50084ec5a8fda77a]::query::caches::DefaultCache<rustc_type_ir[ee20701d43e568e4]::canonical::Canonical<rustc_middle[3b7dc7f1ac8ce2bc]::ty::context::TyCtxt, rustc_middle[3b7dc7f1ac8ce2bc]::ty::ParamEnvAnd<rustc_middle[3b7dc7f1ac8ce2bc]::ty::Predicate>>, rustc_middle[3b7dc7f1ac8ce2bc]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[d233ef11b2077f1a]::plumbing::QueryCtxt, false>
  39:     0x7fbf78a0d495 - rustc_query_impl[d233ef11b2077f1a]::query_impl::evaluate_obligation::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7fbf75992c5d - <rustc_infer[8d75f53857709946]::infer::InferCtxt as rustc_trait_selection[cc4a1b9dcbaa9312]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  41:     0x559a4804050a - rustdoc[608054bee3869830]::clean::utils::get_auto_trait_and_blanket_impls
  42:     0x559a4814d453 - <rustdoc[608054bee3869830]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[608054bee3869830]::visit::DocVisitor>::visit_item
  43:     0x559a4814d7ca - <rustdoc[608054bee3869830]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[608054bee3869830]::visit::DocVisitor>::visit_item
  44:     0x559a4814d7ca - <rustdoc[608054bee3869830]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[608054bee3869830]::visit::DocVisitor>::visit_item
  45:     0x559a4814d7ca - <rustdoc[608054bee3869830]::passes::collect_trait_impls::SyntheticImplCollector as rustdoc[608054bee3869830]::visit::DocVisitor>::visit_item
  46:     0x559a4814a0cc - rustdoc[608054bee3869830]::passes::collect_trait_impls::collect_trait_impls
  47:     0x559a480743e8 - rustdoc[608054bee3869830]::core::run_global_ctxt
  48:     0x559a4817adda - rustdoc[608054bee3869830]::main_args::{closure#1}::{closure#0}::{closure#0}
  49:     0x559a47f7a18e - rustc_interface[8941d970301189ef]::interface::run_compiler::<core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>, rustdoc[608054bee3869830]::main_args::{closure#1}>::{closure#0}
  50:     0x559a47f4acb2 - std[ce0584ef05f9a8b4]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8941d970301189ef]::util::run_in_thread_with_globals<rustc_interface[8941d970301189ef]::util::run_in_thread_pool_with_globals<rustc_interface[8941d970301189ef]::interface::run_compiler<core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>, rustdoc[608054bee3869830]::main_args::{closure#1}>::{closure#0}, core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>>::{closure#0}, core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>>
  51:     0x559a47f84f6e - <<std[ce0584ef05f9a8b4]::thread::Builder>::spawn_unchecked_<rustc_interface[8941d970301189ef]::util::run_in_thread_with_globals<rustc_interface[8941d970301189ef]::util::run_in_thread_pool_with_globals<rustc_interface[8941d970301189ef]::interface::run_compiler<core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>, rustdoc[608054bee3869830]::main_args::{closure#1}>::{closure#0}, core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>>::{closure#0}, core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a6856156d288c90]::result::Result<(), rustc_span[79cd123206d5c77b]::ErrorGuaranteed>>::{closure#1} as core[a6856156d288c90]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  52:     0x7fbf747984a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2d19f142671865ec
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  53:     0x7fbf747984a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h710d713fa9cb7127
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/alloc/src/boxed.rs:2015:9
  54:     0x7fbf747984a5 - std::sys::unix::thread::Thread::new::thread_start::haaff457ad882d05b
                               at /rustc/503e129328080e924c0ddfca6abf4c2812580102/library/std/src/sys/unix/thread.rs:108:17
  55:     0x7fbf7449b9eb - <unknown>
  56:     0x7fbf7451f7cc - <unknown>
  57:                0x0 - <unknown>


rustc version: 1.76.0-nightly (503e12932 2023-12-07)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `stream::stream::FlatMapUnordered<^1_1, ^1_2, ^1_0>: futures_core::stream::TryStream`
end of query stack
```

</p>
</details>
This only happens with the nightly compiler. The stable compiler is not affected.

**Comment by matthiaskrgr** [comment]
I believe this has been fixed on latest nightly.

**Comment by Frostie314159** [comment]
I just tested it and it is fixed thanks a lot!
