### ISSUE TITLE
I wrote code for class project and the compiler said to me create issue 

### ISSUE THREAD

**Issue by ari1008** [rust-lang/rust#119075]
### Code

```Rust
(https://github.com/esgi-project-4al1/rust_frakt) 

this is a  test  newton.rs test_first_fractale() 
```

### Meta

rustc --version --verbose
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6

### Error output

```
(error: internal compiler error: unexpected panic) 
```

<details><summary><strong>[Backtrace](error: internal compiler error: unexpected panic)</strong></summary>
<p>

```
/Users/aristidefumo/.cargo/bin/cargo test --color=always --message-format=json-diagnostic-rendered-ansi --no-run --lib newton::tests::test_first_fractale --manifest-path /Users/aristidefumo/Documents/rust/frakt/message/Cargo.toml
warning: /Users/aristidefumo/Documents/rust/frakt/Cargo.toml: unused manifest key: workspace.workspace
   Compiling message v0.1.0 (/Users/aristidefumo/Documents/rust/frakt/message)
warning: unused variable: `range`
  --> message/src/newton.rs:40:13
   |
40 |         let range = 2.0;
   |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_range`
   |
   = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/check_unsafety.rs:507:36
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>::borrow
   3: rustc_mir_transform::check_unsafety::unsafety_check_result
   4: <rustc_mir_transform::check_unsafety::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
   5: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::UnsafetyCheckResult>
   6: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::UnsafetyCheckResult>>
   7: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::unsafety_check_result, rustc_query_impl::plumbing::QueryCtxt>
   8: rustc_mir_transform::check_unsafety::check_unsafety
   9: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#3}>
  10: rustc_interface::passes::analysis
  11: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  12: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  13: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  14: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  15: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  16: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  17: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.64.0 (a55dd71d5 2022-09-19) running on aarch64-apple-darwin
note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [unsafety_check_result] unsafety-checking `message::<impl at message/src/message.rs:4:10: 4:15>::fmt`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 1 warning emitted

error: could not compile `message`; 2 warnings emitted
Process finished with exit code 101

```

</p>
</details>

If you have other questions or the problems is just my code, tell me.

**Comment by matthiaskrgr** [comment]
>rustc 1.64.0 (https://github.com/rust-lang/rust/commit/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52 2022-09-19)

your rust version is more than a year behind.. :sweat_smile:

**Comment by ari1008** [comment]
It's work, thanks to you. I'm just upgrading rust compiler
