### ISSUE TITLE
Error caused by compiler flag -Zself-profile-events=default,args

### ISSUE THREAD

**Issue by kapilsinha** [rust-lang/rust#119103]
### Code

```Rust
<code>
note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C linker=clang -Z self-profile -Z self-profile-events=default,args
```

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (de686cbc6 2023-12-14)
binary: rustc
commit-hash: de686cbc65478db53e3d51c52497685e852cc092
commit-date: 2023-12-14
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Error output

```
error: could not compile `polars-core` (lib)
error: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rust/deps/measureme-10.1.1/src/stringtable.rs:105:62:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f9158e36da1 - std::backtrace_rs::backtrace::libunwind::trace::heeb1a1d1e2dbc154
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f9158e36da1 - std::backtrace_rs::backtrace::trace_unsynchronized::h2b73b0b51d0f4bd0
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f9158e36da1 - std::backtrace::Backtrace::create::h48832537e52b215e
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/backtrace.rs:331:13
   3:     0x7f9158e36cf0 - std::backtrace::Backtrace::force_capture::hac4308e5700a51c6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/backtrace.rs:312:9
   4:     0x7f9155b4a05c - std[7e57236d4cf722ab]::panicking::update_hook::<alloc[b67f4363825276b5]::boxed::Box<rustc_driver_impl[2cd48a31253fd2b4]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f9158e52688 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1388f84c45c66892
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/alloc/src/boxed.rs:2029:9
   6:     0x7f9158e52688 - std::panicking::rust_panic_with_hook::h7c4f66d28b1ecc76
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:783:13
   7:     0x7f9158e523a9 - std::panicking::begin_panic_handler::{{closure}}::h4c6f212c8a3345a6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:649:13
   8:     0x7f9158e4f926 - std::sys_common::backtrace::__rust_end_short_backtrace::hca2125b9289465b6
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x7f9158e52142 - rust_begin_unwind
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/std/src/panicking.rs:645:5
  10:     0x7f9158e9ebd5 - core::panicking::panic_fmt::h1f0a3a584d873149
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/panicking.rs:72:14
  11:     0x7f9158e9ec93 - core::panicking::panic::hd4ce2f9e2b84581a
                               at /rustc/de686cbc65478db53e3d51c52497685e852cc092/library/core/src/panicking.rs:144:5
  12:     0x7f91556d152a - <measureme[4e4f9367e56b7d22]::event_id::EventIdBuilder>::from_label_and_arg
  13:     0x7f91562c0510 - <rustc_data_structures[c6c1454da6aa591e]::profiling::SelfProfilerRef>::with_profiler::<rustc_query_impl[265233e494cd0a10]::profiling_support::alloc_self_profile_query_strings_for_query_cache<rustc_query_system[20160a5715e66ec3]::query::caches::DefaultCache<rustc_middle[196e7cb20982c59e]::ty::ParamEnvAnd<rustc_middle[196e7cb20982c59e]::ty::Ty>, rustc_middle[196e7cb20982c59e]::query::erase::Erased<[u8; 1usize]>>>::{closure#0}>
  14:     0x7f91563b7a2b - rustc_query_impl[265233e494cd0a10]::query_impl::needs_drop_raw::alloc_self_profile_query_strings
  15:     0x7f9157d98c35 - rustc_interface[7e6b194adc137d27]::interface::run_compiler::<core[10bca3e69d00381c]::result::Result<(), rustc_span[17898b08fe0f9fc9]::ErrorGuaranteed>, rustc_driver_impl[2cd48a31253fd2b4]::run_compiler::{closure#0}>::{closure#0}
  16:     0x7f9157d0be9a - std[7e57236d4cf722ab]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7e6b194adc137d27]::util::run_in_thread_with_globals<rustc_interface[7e6b194adc137d27]::util::run_in_thread_pool_with_globals<rustc_interface[7e6b194adc137d27]::interface::run_compiler<core[10bca3e69d00381c]::result::Result<(), rustc_span[17898b08fe0f9fc9]::ErrorGuaranteed>, rustc_driver_impl[2cd48a31253fd2b4]::run_compiler::{closure#0}>::{closure#0}, core[10bca3e69d00381c]::result::Result<(), rustc_span[17898b08fe0f9fc9]::ErrorGuaranteed>>::{closure#0}, core[10bca3e69d00381c]::result::Result<(), rustc_span[17898b08fe0f9fc9]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[10bca3e69d00381c]::result::Result<(), rustc_span[17898b08fe0f9fc9]::ErrorGuaranteed>>
```

</p>
</details>

**Comment by kapilsinha** [comment]
Looks like it's taking a while to update that measureme crate...is there a temporary fix I can do on my end? Happy to compile a version of the compiler if that's what it takes
