### ISSUE TITLE
error: the compiler unexpectedly panicked. this is a bug.

### ISSUE THREAD

**Issue by isheff** [rust-lang/rust#119357]
### Code
I'm not sure what triggers it, but it happens when I try to compile this commit: https://github.com/isheff/het_paxos_ref/tree/34b215584709d9c4d528f7a3b9e8889579be4d03

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-apple-darwin
release: 1.69.0
LLVM version: 15.0.7
```

### Error output

```
⇒  cargo test
   Compiling het_paxos_ref v0.1.0 (/Users/isheff/Library/CloudStorage/Dropbox/Documents/Heliax/het_paxos_ref)
thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/check_unsafety.rs:503:36
stack backtrace:
   0:        0x10108f736 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84dde8223670de4
   1:        0x1010ef1ca - core::fmt::write::h0721d4325d1d86bb
   2:        0x1010846cc - std::io::Write::write_fmt::hf4d04b4d333539fa
   3:        0x10108f51a - std::sys_common::backtrace::print::hed06273df3ccacbe
   4:        0x1010927d3 - std::panicking::default_hook::{{closure}}::he8c58e8d0abf03c5
   5:        0x101092528 - std::panicking::default_hook::h8320561bf55c0290
   6:        0x10aa3e14a - rustc_driver_impl[7893df22573bd66e]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x101092fcc - std::panicking::rust_panic_with_hook::h38dc40cfa47552ba
   8:        0x101092d64 - std::\panicking::begin_panic_handler::{{closure}}::h727c67dc750b5cee
   9:        0x10108fb79 - std::sys_common::backtrace::__rust_end_short_backtrace::h6848121e0bfe63be
  10:        0x101092a2d - _rust_begin_unwind
  11:        0x10111a083 - core::panicking::panic_fmt::h690b01655a033c26
  12:        0x10b8b98a4 - rustc_mir_transform[341bd1993106d380]::check_unsafety::unsafety_check_result
  13:        0x10b8b54d1 - <rustc_mir_transform[341bd1993106d380]::check_unsafety::provide::{closure#0} as core[2e368d3e45d5bc15]::ops::function::FnOnce<(rustc_middle[f8fd6f79b0def500]::ty::context::TyCtxt, rustc_span[acf50603cc8e260b]::def_id::LocalDefId)>>::call_once
  14:        0x10bf391c0 - <rustc_middle[f8fd6f79b0def500]::dep_graph::dep_node::DepKind as rustc_query_system[3e412bc1907aaa01]::dep_graph::DepKind>::with_deps::<rustc_query_system[3e412bc1907aaa01]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[418c06df92e04716]::queries::unsafety_check_result, rustc_query_impl[418c06df92e04716]::plumbing::QueryCtxt>::{closure#1}, &rustc_middle[f8fd6f79b0def500]::mir::query::UnsafetyCheckResult>
  15:        0x10bdf51ef - rustc_query_system[3e412bc1907aaa01]::query::plumbing::try_execute_query::<rustc_query_impl[418c06df92e04716]::queries::unsafety_check_result, rustc_query_impl[418c06df92e04716]::plumbing::QueryCtxt>
  16:        0x10bf61602 - <rustc_query_impl[418c06df92e04716]::Queries as rustc_middle[f8fd6f79b0def500]::ty::query::QueryEngine>::unsafety_check_result
  17:        0x10b8b9ac0 - rustc_mir_transform[341bd1993106d380]::check_unsafety::check_unsafety
  18:        0x10b2292f8 - <rustc_session[e457045bc04ab619]::session::Session>::time::<(), rustc_interface[cfb9c87a3e9792c6]::passes::analysis::{closure#3}>
  19:        0x10b21e517 - rustc_interface[cfb9c87a3e9792c6]::passes::analysis
  20:        0x10bf2f157 - <rustc_middle[f8fd6f79b0def500]::dep_graph::dep_node::DepKind as rustc_query_system[3e412bc1907aaa01]::dep_graph::DepKind>::with_deps::<<rustc_query_system[3e412bc1907aaa01]::dep_graph::graph::DepGraph<rustc_middle[f8fd6f79b0def500]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_query_impl[418c06df92e04716]::plumbing::QueryCtxt, (), core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>::{closure#0}, core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>
  21:        0x10be83dd3 - rustc_query_system[3e412bc1907aaa01]::query::plumbing::try_execute_query::<rustc_query_impl[418c06df92e04716]::queries::analysis, rustc_query_impl[418c06df92e04716]::plumbing::QueryCtxt>
  22:        0x10bf5825e - <rustc_query_impl[418c06df92e04716]::Queries as rustc_middle[f8fd6f79b0def500]::ty::query::QueryEngine>::analysis
  23:        0x10aa94ed5 - <rustc_middle[f8fd6f79b0def500]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[7893df22573bd66e]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>
  24:        0x10aa93cb6 - rustc_span[acf50603cc8e260b]::with_source_map::<core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>, rustc_interface[cfb9c87a3e9792c6]::interface::run_compiler<core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>, rustc_driver_impl[7893df22573bd66e]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  25:        0x10aa4e745 - std[8b2f5776005dbe65]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cfb9c87a3e9792c6]::util::run_in_thread_pool_with_globals<rustc_interface[cfb9c87a3e9792c6]::interface::run_compiler<core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>, rustc_driver_impl[7893df22573bd66e]::run_compiler::{closure#1}>::{closure#0}, core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>
  26:        0x10aa50915 - <<std[8b2f5776005dbe65]::thread::Builder>::spawn_unchecked_<rustc_interface[cfb9c87a3e9792c6]::util::run_in_thread_pool_with_globals<rustc_interface[cfb9c87a3e9792c6]::interface::run_compiler<core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>, rustc_driver_impl[7893df22573bd66e]::run_compiler::{closure#1}>::{closure#0}, core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2e368d3e45d5bc15]::result::Result<(), rustc_span[acf50603cc8e260b]::ErrorGuaranteed>>::{closure#1} as core[2e368d3e45d5bc15]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:        0x10109c717 - std::sys::unix::thread::Thread::new::thread_start::hd752b82ee9981a13
  28:     0x7ff814f32202 - __pthread_start

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `grpc::acceptor_client::<impl at /Users/isheff/Library/CloudStorage/Dropbox/Documents/Heliax/het_paxos_ref/target/debug/build/het_paxos_ref-40b035be7541e615/out/hetpaxosref.rs:78:5: 78:51>::connect`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `het_paxos_ref`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
⇒  RUST_BACKTRACE=1 cargo build
   Compiling het_paxos_ref v0.1.0 (/Users/isheff/Library/CloudStorage/Dropbox/Documents/Heliax/het_paxos_ref)
thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/check_unsafety.rs:503:36
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rustc_mir_transform::check_unsafety::unsafety_check_result
   3: <rustc_mir_transform::check_unsafety::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
   4: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::queries::unsafety_check_result, rustc_query_impl::plumbing::QueryCtxt>::{closure#1}, &rustc_middle::mir::query::UnsafetyCheckResult>
   5: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::unsafety_check_result, rustc_query_impl::plumbing::QueryCtxt>
   6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result
   7: rustc_mir_transform::check_unsafety::check_unsafety
   8: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#3}>
   9: rustc_interface::passes::analysis
  10: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_query_impl::plumbing::QueryCtxt, (), core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  11: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  13: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  14: rustc_span::with_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `grpc::acceptor_client::<impl at /Users/isheff/Library/CloudStorage/Dropbox/Documents/Heliax/het_paxos_ref/target/debug/build/het_paxos_ref-40b035be7541e615/out/hetpaxosref.rs:78:5: 78:51>::connect`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `het_paxos_ref`
```

</p>
</details>

**Comment by lqd** [comment]
You're using an old rustc version, and some of these issues have since been fixed. Could you try the latest stable for example?

**Comment by isheff** [comment]
I can't even seem to re-create it with the old version after a `cargo clean`. I'm not sure what happened, but it asked me to file a bug report, so I did.
