### ISSUE TITLE
ICE: `expected type of coroutine-like closure to be a coroutine`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#119491]
auto-reduced (treereduce-rust):
````rust
fn f<T>(
    data: &[(); {
         let f: F = async { 1 };

         1
     }],
) -> impl Iterator<Item = SubAssign> {
}

#![feature(generic_const_exprs)]

````

original:
````rust
// edition:2021

use std::iter;

fn f<T>(data: &[(); {
        fn concrete_use() -> F {
            //~^ ERROR future that resolves to `u8`, but it resolves to `()`
            async {}
        }
        let f: F = async { 1 };
        //~^ ERROR item constrains opaque type that is not in its signature
        //~| ERROR `async` blocks are not allowed in constants
        1
    }]) -> impl Iterator<Item = SubAssign> {
    //~^ ERROR: missing generics for struct `Vec` [E0107]
    Some(())
        .into_iter()
}

fn g<T>(data: &[T], target: T) -> impl Iterator<Item = SubAssign> {
    match 13 {
        0 => {
            1u32 //~ ERROR mismatched types
        }
        _ => {
            1u32 //~ ERROR mismatched types
        }
    }
}

fn main() {}

````

Version information
````
rustc 1.77.0-nightly (e51e98dde 2023-12-31)
binary: rustc
commit-hash: e51e98dde6a60637b6a71b8105245b629ac3fe77
commit-date: 2023-12-31
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc --edition=2021 -Zcrate-attr=feature(generic_const_exprs)`

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `F` in this scope
  --> /tmp/icemaker_global_tempdir.39hz6WRyRT6X/rustc_testrunner_tmpdir_reporting.SBERK7UE9s1p/mvce.rs:3:17
   |
3  |          let f: F = async { 1 };
   |                 ^
   |
  ::: /home/matthias/.rustup/toolchains/master/lib/rustlib/src/rust/library/core/src/ops/function.rs:76:1
   |
76 | pub trait Fn<Args: Tuple>: FnMut<Args> {
   | -------------------------------------- similarly named trait `Fn` defined here
   |
help: a trait with a similar name exists
   |
3  |          let f: Fn = async { 1 };
   |                 ~~
help: you might be missing a type parameter
   |
1  | fn f<T, F>(
   |       +++

error[E0412]: cannot find type `SubAssign` in this scope
 --> /tmp/icemaker_global_tempdir.39hz6WRyRT6X/rustc_testrunner_tmpdir_reporting.SBERK7UE9s1p/mvce.rs:7:27
  |
7 | ) -> impl Iterator<Item = SubAssign> {
  |                           ^^^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 + use core::ops::SubAssign;
  |
1 + use std::ops::SubAssign;
  |

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> <crate attribute>:1:9
  |
1 | feature(generic_const_exprs)
  |         ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.39hz6WRyRT6X/rustc_testrunner_tmpdir_reporting.SBERK7UE9s1p/mvce.rs:8:2
  |
8 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.39hz6WRyRT6X/rustc_testrunner_tmpdir_reporting.SBERK7UE9s1p/mvce.rs`

warning: unused variable: `data`
 --> /tmp/icemaker_global_tempdir.39hz6WRyRT6X/rustc_testrunner_tmpdir_reporting.SBERK7UE9s1p/mvce.rs:2:5
  |
2 |     data: &[(); {
  |     ^^^^ help: if this is intentional, prefix it with an underscore: `_data`
  |
  = note: `#[warn(unused_variables)]` on by default

error: internal compiler error: compiler/rustc_mir_build/src/build/mod.rs:650:17: expected type of coroutine-like closure to be a coroutine

thread 'rustc' panicked at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/compiler/rustc_errors/src/lib.rs:1068:30:
Box<dyn Any>
stack backtrace:
   0:     0x7f6a47fdb946 - std::backtrace_rs::backtrace::libunwind::trace::h44f4ca7c442c0986
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f6a47fdb946 - std::backtrace_rs::backtrace::trace_unsynchronized::h8e72beef8f98799e
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6a47fdb946 - std::sys_common::backtrace::_print_fmt::had1f7322c7191a83
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f6a47fdb946 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc02075f68ac68e83
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f6a4802e060 - core::fmt::rt::Argument::fmt::h4fb797bf569c9381
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/fmt/rt.rs:142:9
   5:     0x7f6a4802e060 - core::fmt::write::h6f1ea15fe9368d17
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f6a47fcf36f - std::io::Write::write_fmt::haaa4143b58137630
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/io/mod.rs:1810:15
   7:     0x7f6a47fdb724 - std::sys_common::backtrace::_print::h16f1f390d8dff6aa
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f6a47fdb724 - std::sys_common::backtrace::print::h7a4cfc718891723c
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f6a47fde4b7 - std::panicking::default_hook::{{closure}}::h66f09592313f4ce8
  10:     0x7f6a47fde219 - std::panicking::default_hook::he45e0a376ce42f7d
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:292:9
  11:     0x7f6a44d6605c - std[59bbd359e4a0812d]::panicking::update_hook::<alloc[9e8bbef5278c9f16]::boxed::Box<rustc_driver_impl[f5f02e8ab7f89dcf]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f6a47fdec06 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h0ebdda5c503ff158
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/alloc/src/boxed.rs:2029:9
  13:     0x7f6a47fdec06 - std::panicking::rust_panic_with_hook::h4f38919015b1c60f
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:783:13
  14:     0x7f6a44d9f1b4 - std[59bbd359e4a0812d]::panicking::begin_panic::<rustc_errors[b2b45e62fb4172dd]::ExplicitBug>::{closure#0}
  15:     0x7f6a44d9b5b6 - std[59bbd359e4a0812d]::sys_common::backtrace::__rust_end_short_backtrace::<std[59bbd359e4a0812d]::panicking::begin_panic<rustc_errors[b2b45e62fb4172dd]::ExplicitBug>::{closure#0}, !>
  16:     0x7f6a44d96856 - std[59bbd359e4a0812d]::panicking::begin_panic::<rustc_errors[b2b45e62fb4172dd]::ExplicitBug>
  17:     0x7f6a44daa101 - <rustc_errors[b2b45e62fb4172dd]::diagnostic_builder::BugAbort as rustc_errors[b2b45e62fb4172dd]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f6a45171ece - <rustc_errors[b2b45e62fb4172dd]::DiagCtxt>::bug::<alloc[9e8bbef5278c9f16]::string::String>
  19:     0x7f6a4520e02b - rustc_middle[7d80ff9c88f366f3]::util::bug::opt_span_bug_fmt::<rustc_span[44814e3eac9e4a35]::span_encoding::Span>::{closure#0}
  20:     0x7f6a451f690a - rustc_middle[7d80ff9c88f366f3]::ty::context::tls::with_opt::<rustc_middle[7d80ff9c88f366f3]::util::bug::opt_span_bug_fmt<rustc_span[44814e3eac9e4a35]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f6a451f67a8 - rustc_middle[7d80ff9c88f366f3]::ty::context::tls::with_context_opt::<rustc_middle[7d80ff9c88f366f3]::ty::context::tls::with_opt<rustc_middle[7d80ff9c88f366f3]::util::bug::opt_span_bug_fmt<rustc_span[44814e3eac9e4a35]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f6a43188960 - rustc_middle[7d80ff9c88f366f3]::util::bug::bug_fmt
  23:     0x7f6a45264a07 - rustc_mir_build[92ecac31500debc4]::build::construct_error
  24:     0x7f6a4630cd38 - rustc_mir_build[92ecac31500debc4]::build::mir_built
  25:     0x7f6a4630b5ed - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7f6a46165c43 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::VecCache<rustc_span[44814e3eac9e4a35]::def_id::LocalDefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  27:     0x7f6a461655d0 - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f6a435a928e - rustc_mir_transform[8186e48857664e14]::check_unsafety::unsafety_check_result
  29:     0x7f6a461659c7 - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::unsafety_check_result::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7f6a46165c43 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::VecCache<rustc_span[44814e3eac9e4a35]::def_id::LocalDefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  31:     0x7f6a46165750 - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::unsafety_check_result::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7f6a46166c39 - rustc_mir_transform[8186e48857664e14]::mir_const
  33:     0x7f6a46166b67 - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7f6a46165c43 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::VecCache<rustc_span[44814e3eac9e4a35]::def_id::LocalDefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  35:     0x7f6a46165690 - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_const::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f6a442e324c - rustc_mir_transform[8186e48857664e14]::mir_promoted
  37:     0x7f6a4662915e - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 16usize]>>
  38:     0x7f6a4662942a - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::VecCache<rustc_span[44814e3eac9e4a35]::def_id::LocalDefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  39:     0x7f6a46629063 - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f6a46ed3a30 - rustc_borrowck[873e5fa24eb195b7]::mir_borrowck
  41:     0x7f6a46ed3979 - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>
  42:     0x7f6a46165c43 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::VecCache<rustc_span[44814e3eac9e4a35]::def_id::LocalDefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  43:     0x7f6a46165810 - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  44:     0x7f6a46ff1bb6 - <rustc_hir_analysis[239f966c4ce807be]::collect::type_of::opaque::RpitConstraintChecker>::check
  45:     0x7f6a44608705 - <rustc_hir_analysis[239f966c4ce807be]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[556501f2b35f222e]::intravisit::Visitor>::visit_expr
  46:     0x7f6a46fe68bb - <rustc_hir_analysis[239f966c4ce807be]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[556501f2b35f222e]::intravisit::Visitor>::visit_block
  47:     0x7f6a46fe5445 - <rustc_hir_analysis[239f966c4ce807be]::collect::type_of::opaque::RpitConstraintChecker as rustc_hir[556501f2b35f222e]::intravisit::Visitor>::visit_fn
  48:     0x7f6a46fe5a66 - rustc_hir_analysis[239f966c4ce807be]::collect::type_of::type_of_opaque
  49:     0x7f6a46fe54db - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>
  50:     0x7f6a46062514 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::DefaultCache<rustc_span[44814e3eac9e4a35]::def_id::DefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  51:     0x7f6a4702891e - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  52:     0x7f6a46177bb8 - rustc_middle[7d80ff9c88f366f3]::query::plumbing::query_get_at::<rustc_query_system[cdab7429fb42dda2]::query::caches::DefaultCache<rustc_span[44814e3eac9e4a35]::def_id::DefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>>
  53:     0x7f6a44427533 - rustc_hir_analysis[239f966c4ce807be]::collect::type_of::type_of
  54:     0x7f6a4606367e - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>
  55:     0x7f6a46062514 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::DefaultCache<rustc_span[44814e3eac9e4a35]::def_id::DefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  56:     0x7f6a460620dd - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  57:     0x7f6a46177bb8 - rustc_middle[7d80ff9c88f366f3]::query::plumbing::query_get_at::<rustc_query_system[cdab7429fb42dda2]::query::caches::DefaultCache<rustc_span[44814e3eac9e4a35]::def_id::DefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 8usize]>>>
  58:     0x7f6a46c75b42 - rustc_hir_analysis[239f966c4ce807be]::check::check::check_item_type
  59:     0x7f6a46c6f965 - rustc_hir_analysis[239f966c4ce807be]::check::check::check_mod_item_types
  60:     0x7f6a46c6f917 - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::check_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 0usize]>>
  61:     0x7f6a46c18dbb - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::DefaultCache<rustc_span[44814e3eac9e4a35]::def_id::LocalModDefId, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  62:     0x7f6a46c1879f - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::check_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  63:     0x7f6a468dfc25 - rustc_hir_analysis[239f966c4ce807be]::check_crate
  64:     0x7f6a4695a319 - rustc_interface[8dea96efab884454]::passes::analysis
  65:     0x7f6a46959f5f - rustc_query_impl[6eb9e4a88fa21aca]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6eb9e4a88fa21aca]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 1usize]>>
  66:     0x7f6a46f97a64 - rustc_query_system[cdab7429fb42dda2]::query::plumbing::try_execute_query::<rustc_query_impl[6eb9e4a88fa21aca]::DynamicConfig<rustc_query_system[cdab7429fb42dda2]::query::caches::SingleCache<rustc_middle[7d80ff9c88f366f3]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[6eb9e4a88fa21aca]::plumbing::QueryCtxt, false>
  67:     0x7f6a46f97855 - rustc_query_impl[6eb9e4a88fa21aca]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  68:     0x7f6a4702d094 - rustc_interface[8dea96efab884454]::interface::run_compiler::<core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>, rustc_driver_impl[f5f02e8ab7f89dcf]::run_compiler::{closure#0}>::{closure#0}
  69:     0x7f6a46fb7306 - std[59bbd359e4a0812d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8dea96efab884454]::util::run_in_thread_with_globals<rustc_interface[8dea96efab884454]::util::run_in_thread_pool_with_globals<rustc_interface[8dea96efab884454]::interface::run_compiler<core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>, rustc_driver_impl[f5f02e8ab7f89dcf]::run_compiler::{closure#0}>::{closure#0}, core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>>::{closure#0}, core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>>
  70:     0x7f6a46fb7133 - <<std[59bbd359e4a0812d]::thread::Builder>::spawn_unchecked_<rustc_interface[8dea96efab884454]::util::run_in_thread_with_globals<rustc_interface[8dea96efab884454]::util::run_in_thread_pool_with_globals<rustc_interface[8dea96efab884454]::interface::run_compiler<core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>, rustc_driver_impl[f5f02e8ab7f89dcf]::run_compiler::{closure#0}>::{closure#0}, core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>>::{closure#0}, core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f50a4b4ddb6878bb]::result::Result<(), rustc_span[44814e3eac9e4a35]::ErrorGuaranteed>>::{closure#1} as core[f50a4b4ddb6878bb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  71:     0x7f6a47fe8b35 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfced58be344e2c05
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/alloc/src/boxed.rs:2015:9
  72:     0x7f6a47fe8b35 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7842a7154462ae57
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/alloc/src/boxed.rs:2015:9
  73:     0x7f6a47fe8b35 - std::sys::unix::thread::Thread::new::thread_start::ha365c5d9b9d0ac99
                               at /rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/sys/unix/thread.rs:108:17
  74:     0x7f6a41eaa9eb - <unknown>
  75:     0x7f6a41f2e7cc - <unknown>
  76:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.77.0-nightly (e51e98dde 2023-12-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z crate-attr=feature(generic_const_exprs) -Z dump-mir-dir=dir

query stack during panic:
#0 [mir_built] building MIR for `f::{constant#0}::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `f::{constant#0}::{closure#0}`
#2 [mir_const] preparing `f::{constant#0}::{closure#0}` for borrow checking
#3 [mir_promoted] promoting constants in MIR for `f::{constant#0}::{closure#0}`
#4 [mir_borrowck] borrow-checking `f::{constant#0}::{closure#0}`
#5 [type_of_opaque] computing type of opaque `f::{opaque#0}`
#6 [type_of] computing type of `f::{opaque#0}`
#7 [check_mod_item_types] checking item types in top-level module
#8 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors; 2 warnings emitted

Some errors have detailed explanations: E0412, E0601.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/issues/113776
