### ISSUE TITLE
Buf on running `cargo test` with a crate-specific feature

### ISSUE THREAD

**Issue by Jazzpirate** [rust-lang/rust#119860]
Not sure I can provide a minimal example. It's a huge project and the bug only showed up recently after a major refactoring effort across the whole code base, which makes it difficult to pin down any potential cause. I apologize for having to be unhelpfully vague.

It seems to be related to infering the validity of a `Clone` derive on a deep/mutually recursive struct with various generics in between. I've had similar problems in the past, but this is the first time I get a compile error

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6

```

### Error output

```
error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto -C debuginfo=2 -C debug-assertions=on -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [fn_abi_of_instance] computing call ABI of `commands::<impl at src/commands.rs:257:10: 257:15>::clone`
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 opt_def_kind(thread 'rustc' panicked at compiler/rustc_middle/src/dep_graph/dep_node.rs:198:17:
Failed to extract DefId: opt_def_kind 64204579bbe8e9bc-176f3ec7aef700c
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f1e1c25362c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f1e1c25362c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1e1c25362c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f1e1c25362c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1e1c2a6630 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x7f1e1c2a6630 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f1e1c24754f - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x7f1e1c253414 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1e1c253414 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1e1c2560a7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x7f1e1c255e0f - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x7f1e19137190 - std[409886f6357001f0]::panicking::update_hook::<alloc[c1b021ad36e35877]::boxed::Box<rustc_driver_impl[7d23c5715ff089db]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f1e1c2567e8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1f8f335eaa9cfaee
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
  13:     0x7f1e1c2567e8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13
  14:     0x7f1e1c25653e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  15:     0x7f1e1c253af6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f1e1c2562a2 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  17:     0x7f1e1c2a2d15 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  18:     0x7f1e195c66f2 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::dep_node::DepNode as rustc_middle[aca4860da4e5a967]::dep_graph::dep_node::DepNodeExt>::extract_def_id::{closure#0}
  19:     0x7f1e1a574a47 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::dep_node::DepNode as rustc_middle[aca4860da4e5a967]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  20:     0x7f1e19470ee5 - rustc_interface[fbb0cb4be6c0ba34]::callbacks::dep_node_debug
  21:     0x7f1e19982277 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::dep_node::DepNode as core[21cdcf8e8af4c2d9]::fmt::Debug>::fmt
  22:     0x7f1e1c2a6630 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
  23:     0x7f1e1c2a6630 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
  24:     0x7f1e1c245b5b - std::io::Write::write_fmt::haebcad6df9d10a2f
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
  25:     0x7f1e1c245b5b - <&std::io::stdio::Stderr as std::io::Write>::write_fmt::h229f71fcbf3335e8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/stdio.rs:947:9
  26:     0x7f1e1c24646a - <std::io::stdio::Stderr as std::io::Write>::write_fmt::hb9932f1d0e57eb08
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/stdio.rs:921:9
  27:     0x7f1e1c24646a - std::io::stdio::print_to::h369048152caca230
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/stdio.rs:1020:21
  28:     0x7f1e1c24646a - std::io::stdio::_eprint::h74b8b736e69aef51
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/stdio.rs:1108:5
  29:     0x7f1e198ad1a3 - rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::print_markframe_trace::<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>
  30:     0x7f1e1a43a6f1 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  31:     0x7f1e1a439207 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  32:     0x7f1e1a439207 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  33:     0x7f1e1a439207 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  34:     0x7f1e1a439207 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  35:     0x7f1e1a439207 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  36:     0x7f1e1a439207 - <rustc_query_system[b5dcdc06a735d5f1]::dep_graph::graph::DepGraphData<rustc_middle[aca4860da4e5a967]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt>
  37:     0x7f1e1ae7b689 - rustc_query_system[b5dcdc06a735d5f1]::query::plumbing::try_execute_query::<rustc_query_impl[664ae873a521fa7c]::DynamicConfig<rustc_query_system[b5dcdc06a735d5f1]::query::caches::DefaultCache<rustc_middle[aca4860da4e5a967]::ty::ParamEnvAnd<(rustc_middle[aca4860da4e5a967]::ty::instance::Instance, &rustc_middle[aca4860da4e5a967]::ty::list::List<rustc_middle[aca4860da4e5a967]::ty::Ty>)>, rustc_middle[aca4860da4e5a967]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[664ae873a521fa7c]::plumbing::QueryCtxt, true>
  38:     0x7f1e1ae7ac16 - rustc_query_impl[664ae873a521fa7c]::query_impl::fn_abi_of_instance::get_query_incr::__rust_end_short_backtrace
  39:     0x7f1e17c2c16c - <rustc_codegen_llvm[aca462edc423cf78]::context::CodegenCx as rustc_codegen_ssa[d1233806591d2b47]::traits::declare::PreDefineMethods>::predefine_fn
  40:     0x7f1e1b0ac4f8 - rustc_codegen_llvm[aca462edc423cf78]::base::compile_codegen_unit::module_codegen
  41:     0x7f1e1b0aa949 - <rustc_codegen_llvm[aca462edc423cf78]::LlvmCodegenBackend as rustc_codegen_ssa[d1233806591d2b47]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  42:     0x7f1e1b1fbb51 - <rustc_codegen_llvm[aca462edc423cf78]::LlvmCodegenBackend as rustc_codegen_ssa[d1233806591d2b47]::traits::backend::CodegenBackend>::codegen_crate
  43:     0x7f1e1b1f9b45 - rustc_interface[fbb0cb4be6c0ba34]::passes::start_codegen
  44:     0x7f1e1b1f95e6 - <rustc_interface[fbb0cb4be6c0ba34]::queries::Queries>::ongoing_codegen
  45:     0x7f1e1b207071 - rustc_interface[fbb0cb4be6c0ba34]::interface::run_compiler::<core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>, rustc_driver_impl[7d23c5715ff089db]::run_compiler::{closure#1}>::{closure#0}
  46:     0x7f1e1b20215b - std[409886f6357001f0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[fbb0cb4be6c0ba34]::util::run_in_thread_with_globals<rustc_interface[fbb0cb4be6c0ba34]::interface::run_compiler<core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>, rustc_driver_impl[7d23c5715ff089db]::run_compiler::{closure#1}>::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>
  47:     0x7f1e1b201fb3 - <<std[409886f6357001f0]::thread::Builder>::spawn_unchecked_<rustc_interface[fbb0cb4be6c0ba34]::util::run_in_thread_with_globals<rustc_interface[fbb0cb4be6c0ba34]::interface::run_compiler<core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>, rustc_driver_impl[7d23c5715ff089db]::run_compiler::{closure#1}>::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[21cdcf8e8af4c2d9]::result::Result<(), rustc_span[3d5dc97049ad8d50]::ErrorGuaranteed>>::{closure#1} as core[21cdcf8e8af4c2d9]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7f1e1c2606a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  49:     0x7f1e1c2606a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  50:     0x7f1e1c2606a5 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7f1e16297ada - start_thread
                               at ./nptl/pthread_create.c:444:8
  52:     0x7f1e1632847c - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  53:                0x0 - <unknown>
```

</p>
</details>

**Comment by Jazzpirate** [comment]
It happens in here: https://github.com/Jazzpirate/RusTeX/tree/main/tex_engine on calling `cargo test --features pdflatex`, in case it's reproducible on other's machines

**Comment by Nilstrieb** [comment]
I cannot reproduce this on the latest nightly version, I just get some failing tests. On stable as well.
I ran `cargo test` in the `rustex` directory instead (like what your CI run did) and was able to reproduce the crash on stable, but not nightly. So the problem was fixed already, I'm closing the issue. Thank you for the report anyways!
