### ISSUE TITLE
`thread 'main' panicked. failed printing to stdout: Broken pipe (os error 32)`

### ISSUE THREAD

**Issue by afifurrohman-id** [rust-lang/rust#119980]
I tried this command:

```sh
cargo run | echo
```

I expected to see this happen: ignore.

Instead, this happened: `thread 'main' panicked. failed printing to stdout: Broken pipe (os error 32)`

### Meta

`rustc --version --verbose`:
```
1.74.1 (a28077b28 2023-12-04)
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at library/std/src/io/stdio.rs:1019:9:
failed printing to stdout: Broken pipe (os error 32)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: std::io::stdio::print_to
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/stdio.rs:1019:9
   3: std::io::stdio::_print
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/stdio.rs:1095:5
   4: data_type::compound_type
             at ./src/main.rs:3:5
   5: data_type::main
             at ./src/main.rs:100:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
```

</p>
</details>

**Comment by Nilstrieb** [comment]
This is a known feature/bug with sigpipe handing in the standard library. Std overwrites the sigpipe habdler to do nothing and return a broken pipe error, which println unwraps. There's an unstable feature for changing Unix sigpipe handling with an attribute. You can also just overwrite the sigpipe handler yourself to the default C one that exits the program.
