### ISSUE TITLE
Crash in `normalize_erasing_region`

### ISSUE THREAD

**Issue by virtualritz** [rust-lang/rust#120267]
### Code

I can't provide an MVE as this is proprietary code and I do not have the time to investigate further.

`rustc --version --verbose`:
```
rustc 1.77.0-nightly (d5fd09972 2024-01-22)
binary: rustc
commit-hash: d5fd0997291ca0135401a39dff25c8a9c13b8961
commit-date: 2024-01-22
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6

```

### Error output

```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:187:90: Failed to normalize Alias(Projection, AliasTy { args: [libp2p::libp2p_request_response::Behaviour<api::z_rr_zbin::codec::Codec<api::z_internalcomm::ZInternalReq, api::z_internalcomm::ZInternalRes>>], def_id: DefId(111:728 ~ libp2p_swarm[7505]::behaviour::NetworkBehaviour::ToSwarm) }), maybe try to call `try_normalize_erasing_regions` instead
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/compiler/rustc_errors/src/lib.rs:927:30:
Box<dyn Any>
stack backtrace:
   0:     0x7fe7da2491ce - std::backtrace_rs::backtrace::libunwind::trace::h822cf0d3f16ce96e
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7fe7da2491ce - std::backtrace_rs::backtrace::trace_unsynchronized::hb9053a9a31c80f63
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe7da2491ce - std::backtrace::Backtrace::create::h169e91a5f718310b
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/backtrace.rs:331:13
   3:     0x7fe7da249110 - std::backtrace::Backtrace::force_capture::h04a8ba1c02e0b2e7
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/backtrace.rs:312:9
   4:     0x7fe7d6f70853 - std[f27892e05d49fc7b]::panicking::update_hook::<alloc[820e4ba2a842b676]::boxed::Box<rustc_driver_impl[e28e9318a6752dc4]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7fe7da2650e6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4f1a7cbbf23939a2
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2030:9
   6:     0x7fe7da2650e6 - std::panicking::rust_panic_with_hook::h1836ba36a249344b
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:785:13
   7:     0x7fe7d6fa20b4 - std[f27892e05d49fc7b]::panicking::begin_panic::<rustc_errors[8272471c56a4b1bd]::ExplicitBug>::{closure#0}
   8:     0x7fe7d6f9eaf6 - std[f27892e05d49fc7b]::sys_common::backtrace::__rust_end_short_backtrace::<std[f27892e05d49fc7b]::panicking::begin_panic<rustc_errors[8272471c56a4b1bd]::ExplicitBug>::{closure#0}, !>
   9:     0x7fe7d6f9e766 - std[f27892e05d49fc7b]::panicking::begin_panic::<rustc_errors[8272471c56a4b1bd]::ExplicitBug>
  10:     0x7fe7d6facfe1 - <rustc_errors[8272471c56a4b1bd]::diagnostic_builder::BugAbort as rustc_errors[8272471c56a4b1bd]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7fe7d7368bbb - <rustc_errors[8272471c56a4b1bd]::DiagCtxt>::bug::<alloc[820e4ba2a842b676]::string::String>
  12:     0x7fe7d73ff99b - rustc_middle[a22e9aa1cd203080]::util::bug::opt_span_bug_fmt::<rustc_span[4f259522d7751bf2]::span_encoding::Span>::{closure#0}
  13:     0x7fe7d73e805a - rustc_middle[a22e9aa1cd203080]::ty::context::tls::with_opt::<rustc_middle[a22e9aa1cd203080]::util::bug::opt_span_bug_fmt<rustc_span[4f259522d7751bf2]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7fe7d73e7ed8 - rustc_middle[a22e9aa1cd203080]::ty::context::tls::with_context_opt::<rustc_middle[a22e9aa1cd203080]::ty::context::tls::with_opt<rustc_middle[a22e9aa1cd203080]::util::bug::opt_span_bug_fmt<rustc_span[4f259522d7751bf2]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7fe7d536eb00 - rustc_middle[a22e9aa1cd203080]::util::bug::bug_fmt
  16:     0x7fe7d855957f - <rustc_middle[a22e9aa1cd203080]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_type_ir[4b1a1c0a3819c03c]::fold::TypeFolder<rustc_middle[a22e9aa1cd203080]::ty::context::TyCtxt>>::fold_ty
  17:     0x7fe7d51c96ff - <rustc_pattern_analysis[be0ad85536945e28]::rustc::RustcMatchCheckCtxt>::lower_pat
  18:     0x7fe7d51c55f4 - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  19:     0x7fe7d51c4b9d - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  20:     0x7fe7d51c5f5d - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  21:     0x7fe7d51c4b9d - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  22:     0x7fe7d51c5ad3 - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  23:     0x7fe7d51c4b9d - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  24:     0x7fe7d51c5ad3 - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  25:     0x7fe7d51c4b9d - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  26:     0x7fe7d51c5ad3 - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  27:     0x7fe7d51c4b9d - <rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::MatchVisitor as rustc_middle[a22e9aa1cd203080]::thir::visit::Visitor>::visit_expr
  28:     0x7fe7d85dde15 - rustc_mir_build[26d57f2bd37a26a8]::thir::pattern::check_match::check_match
  29:     0x7fe7d85ddaad - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::check_match::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>
  30:     0x7fe7d85d8a49 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  31:     0x7fe7d85d7c32 - rustc_query_impl[37e0de7e1f66006]::query_impl::check_match::get_query_incr::__rust_end_short_backtrace
  32:     0x7fe7d846b40a - rustc_mir_build[26d57f2bd37a26a8]::build::mir_built
  33:     0x7fe7d846b2d5 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>
  34:     0x7fe7d86e4a95 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  35:     0x7fe7d86e2405 - rustc_query_impl[37e0de7e1f66006]::query_impl::mir_built::get_query_incr::__rust_end_short_backtrace
  36:     0x7fe7d82f9ff9 - rustc_mir_transform[c05555400551e386]::ffi_unwind_calls::has_ffi_unwind_calls
  37:     0x7fe7d82f9beb - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::has_ffi_unwind_calls::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>
  38:     0x7fe7d85d89ed - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  39:     0x7fe7d85d7b3f - rustc_query_impl[37e0de7e1f66006]::query_impl::has_ffi_unwind_calls::get_query_incr::__rust_end_short_backtrace
  40:     0x7fe7d847498d - rustc_mir_transform[c05555400551e386]::mir_const
  41:     0x7fe7d84748c7 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::mir_const::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>
  42:     0x7fe7d86e4a95 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  43:     0x7fe7d86e2517 - rustc_query_impl[37e0de7e1f66006]::query_impl::mir_const::get_query_incr::__rust_end_short_backtrace
  44:     0x7fe7d64990f2 - rustc_mir_transform[c05555400551e386]::mir_promoted
  45:     0x7fe7d87a5252 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 16usize]>>
  46:     0x7fe7d8c72f63 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  47:     0x7fe7d8c72591 - rustc_query_impl[37e0de7e1f66006]::query_impl::mir_promoted::get_query_incr::__rust_end_short_backtrace
  48:     0x7fe7d902f4ae - rustc_borrowck[4eb6c94253d64476]::mir_borrowck
  49:     0x7fe7d902f3d9 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>
  50:     0x7fe7d86e4a95 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  51:     0x7fe7d8b6f2de - rustc_query_impl[37e0de7e1f66006]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  52:     0x7fe7d86b0b09 - <rustc_borrowck[4eb6c94253d64476]::type_check::TypeChecker>::prove_closure_bounds
  53:     0x7fe7d8fe6abe - <rustc_borrowck[4eb6c94253d64476]::type_check::TypeChecker>::typeck_mir
  54:     0x7fe7d598eb74 - rustc_borrowck[4eb6c94253d64476]::type_check::type_check
  55:     0x7fe7d59727de - rustc_borrowck[4eb6c94253d64476]::nll::compute_regions
  56:     0x7fe7d903f60b - rustc_borrowck[4eb6c94253d64476]::do_mir_borrowck
  57:     0x7fe7d902f999 - rustc_borrowck[4eb6c94253d64476]::mir_borrowck
  58:     0x7fe7d902f3d9 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>
  59:     0x7fe7d86e4a95 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_span[4f259522d7751bf2]::def_id::LocalDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  60:     0x7fe7d8b6f2de - rustc_query_impl[37e0de7e1f66006]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  61:     0x7fe7d91faa8b - rustc_hir_analysis[2c86a586459b84d2]::collect::type_of::type_of_opaque
  62:     0x7fe7d91fa71b - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>
  63:     0x7fe7d85e6b8f - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::DefIdCache<rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  64:     0x7fe7d92825e0 - rustc_query_impl[37e0de7e1f66006]::query_impl::type_of_opaque::get_query_incr::__rust_end_short_backtrace
  65:     0x7fe7d866e4d1 - rustc_middle[a22e9aa1cd203080]::query::plumbing::query_get_at::<rustc_query_system[ab396eb147ea698a]::query::caches::DefIdCache<rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>>
  66:     0x7fe7d64ce45c - rustc_hir_analysis[2c86a586459b84d2]::collect::type_of::type_of
  67:     0x7fe7d825df2a - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>
  68:     0x7fe7d85e6b8f - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::DefIdCache<rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  69:     0x7fe7d8548039 - rustc_query_impl[37e0de7e1f66006]::query_impl::type_of::get_query_incr::__rust_end_short_backtrace
  70:     0x7fe7d8443827 - rustc_middle[a22e9aa1cd203080]::query::plumbing::query_get_at::<rustc_query_system[ab396eb147ea698a]::query::caches::DefIdCache<rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 8usize]>>>
  71:     0x7fe7d8be0316 - <rustc_middle[a22e9aa1cd203080]::ty::util::OpaqueTypeExpander>::expand_opaque_ty
  72:     0x7fe7d8bdfadf - <rustc_middle[a22e9aa1cd203080]::ty::util::OpaqueTypeExpander as rustc_type_ir[4b1a1c0a3819c03c]::fold::TypeFolder<rustc_middle[a22e9aa1cd203080]::ty::context::TyCtxt>>::fold_ty
  73:     0x7fe7d97580ca - <rustc_middle[a22e9aa1cd203080]::ty::util::OpaqueTypeExpander as rustc_type_ir[4b1a1c0a3819c03c]::fold::TypeFolder<rustc_middle[a22e9aa1cd203080]::ty::context::TyCtxt>>::fold_ty.cold.0
  74:     0x7fe7d8bdf6de - <&rustc_middle[a22e9aa1cd203080]::ty::list::List<rustc_middle[a22e9aa1cd203080]::ty::generic_args::GenericArg> as rustc_type_ir[4b1a1c0a3819c03c]::fold::TypeFoldable<rustc_middle[a22e9aa1cd203080]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[a22e9aa1cd203080]::ty::util::OpaqueTypeExpander>
  75:     0x7fe7d9758243 - <rustc_middle[a22e9aa1cd203080]::ty::util::OpaqueTypeExpander as rustc_type_ir[4b1a1c0a3819c03c]::fold::TypeFolder<rustc_middle[a22e9aa1cd203080]::ty::context::TyCtxt>>::fold_ty.cold.0
  76:     0x7fe7d8be0359 - <rustc_middle[a22e9aa1cd203080]::ty::util::OpaqueTypeExpander>::expand_opaque_ty
  77:     0x7fe7d8be00a2 - <rustc_middle[a22e9aa1cd203080]::ty::context::TyCtxt>::try_expand_impl_trait_type
  78:     0x7fe7d8e9ef14 - rustc_hir_analysis[2c86a586459b84d2]::check::check::check_item_type
  79:     0x7fe7d87a003b - rustc_hir_analysis[2c86a586459b84d2]::check::wfcheck::check_well_formed
  80:     0x7fe7d879eff3 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>
  81:     0x7fe7d879aac2 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::VecCache<rustc_hir[ae9358ce95817dc8]::hir_id::OwnerId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  82:     0x7fe7d879a5bf - rustc_query_impl[37e0de7e1f66006]::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
  83:     0x7fe7d879bee2 - rustc_hir_analysis[2c86a586459b84d2]::check::wfcheck::check_mod_type_wf
  84:     0x7fe7d879be13 - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>
  85:     0x7fe7d8facfb1 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::DefaultCache<rustc_span[4f259522d7751bf2]::def_id::LocalModDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  86:     0x7fe7d8e32a42 - rustc_query_impl[37e0de7e1f66006]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  87:     0x7fe7d8470411 - rustc_middle[a22e9aa1cd203080]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[ab396eb147ea698a]::query::caches::DefaultCache<rustc_span[4f259522d7751bf2]::def_id::LocalModDefId, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>, ()>
  88:     0x7fe7d8470d4d - rustc_hir_analysis[2c86a586459b84d2]::check_crate
  89:     0x7fe7d8b6f6d2 - rustc_interface[f4b5ac45d2bd61f0]::passes::analysis
  90:     0x7fe7d8b6f31f - rustc_query_impl[37e0de7e1f66006]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[37e0de7e1f66006]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>
  91:     0x7fe7d8c34fe7 - rustc_query_system[ab396eb147ea698a]::query::plumbing::try_execute_query::<rustc_query_impl[37e0de7e1f66006]::DynamicConfig<rustc_query_system[ab396eb147ea698a]::query::caches::SingleCache<rustc_middle[a22e9aa1cd203080]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[37e0de7e1f66006]::plumbing::QueryCtxt, true>
  92:     0x7fe7d8c34be4 - rustc_query_impl[37e0de7e1f66006]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  93:     0x7fe7d8f6e0b3 - rustc_interface[f4b5ac45d2bd61f0]::interface::run_compiler::<core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>, rustc_driver_impl[e28e9318a6752dc4]::run_compiler::{closure#0}>::{closure#0}
  94:     0x7fe7d91ee586 - std[f27892e05d49fc7b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f4b5ac45d2bd61f0]::util::run_in_thread_with_globals<rustc_interface[f4b5ac45d2bd61f0]::util::run_in_thread_pool_with_globals<rustc_interface[f4b5ac45d2bd61f0]::interface::run_compiler<core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>, rustc_driver_impl[e28e9318a6752dc4]::run_compiler::{closure#0}>::{closure#0}, core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>>::{closure#0}, core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>>
  95:     0x7fe7d91ee3b3 - <<std[f27892e05d49fc7b]::thread::Builder>::spawn_unchecked_<rustc_interface[f4b5ac45d2bd61f0]::util::run_in_thread_with_globals<rustc_interface[f4b5ac45d2bd61f0]::util::run_in_thread_pool_with_globals<rustc_interface[f4b5ac45d2bd61f0]::interface::run_compiler<core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>, rustc_driver_impl[e28e9318a6752dc4]::run_compiler::{closure#0}>::{closure#0}, core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>>::{closure#0}, core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ae9770195e47f994]::result::Result<(), rustc_span[4f259522d7751bf2]::ErrorGuaranteed>>::{closure#1} as core[ae9770195e47f994]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  96:     0x7fe7da26e6d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha12de79bc5f3375d
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2016:9
  97:     0x7fe7da26e6d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd0caa04c86a11da9
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2016:9
  98:     0x7fe7da26e6d5 - std::sys::pal::unix::thread::Thread::new::thread_start::hbc42e638d9ed0ea4
                               at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/sys/pal/unix/thread.rs:108:17
  99:     0x7fe7d3e97ada - start_thread
                               at ./nptl/pthread_create.c:444:8
 100:     0x7fe7d3f2847c - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
 101:                0x0 - <unknown>


rustc version: 1.77.0-nightly (d5fd09972 2024-01-22)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_match] match-checking `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{closure#0}`
#1 [mir_built] building MIR for `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{closure#0}`
#2 [has_ffi_unwind_calls] checking if `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{closure#0}` contains FFI-unwind calls
#3 [mir_const] preparing `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{closure#0}` for borrow checking
#4 [mir_promoted] promoting constants in MIR for `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{closure#0}`
#5 [mir_borrowck] borrow-checking `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{closure#0}`
#6 [mir_borrowck] borrow-checking `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event`
#7 [type_of_opaque] computing type of opaque `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{opaque#0}`
#8 [type_of] computing type of `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::handle_event::{opaque#0}`
#9 [check_well_formed] checking that `internal::swarms::internal::mod_impl::<impl at src/internal/swarms/internal/mod_impl.rs:30:1: 30:20>::run::{opaque#0}` is well-formed
#10 [check_mod_type_wf] checking that types are well-formed in module `internal::swarms::internal::mod_impl`
#11 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by Nilstrieb** [comment]
@Nadrieril this is code you've touched recently, did you may regress anything=

**Comment by Nadrieril** [comment]
Thats not unlikely but I have no idea where to start without some code :grimacing:

**Comment by Nilstrieb** [comment]
I'd just look at the diff and see whether I notice anything obvious. But yes, without code there is not much we can do^^

**Comment by Nadrieril** [comment]
The only call to `normalize_erasing_regions` is in a place I haven't touched in a long while. @virtualritz do you happen to know if that code used to compile with a previous rust version?

**Comment by virtualritz** [comment]
> @virtualritz do you happen to know if that code used to compile with a previous rust version?

Not sure.
The crash started appearing after some changes. I updated 1rust` after I saw ir for the 1st time today as I thought it may be something already fixed.
Earlier I was using `nightly` from Sunday/Monday, I think. But the since I changed the code I can't conclude it wouldn't have crashed with any previous `nightly` version.

I also didn't snapshot, unfortunately as I was in a rush to get some fixes out for the code I'm working on. I can't reproduce atm.

If I run into it again, I will make a snapshot at least and then see if I can try to reproduce with an MVE.

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
