### ISSUE TITLE
ICE when compiling aho-corasick-1.1.2 with next-resolver=globally

### ISSUE THREAD

**Issue by thynson** [rust-lang/rust#121178]
### Code

When trying the unstable option `next-resolver=globally`, an ICE was encountered.
And from the log, it's clear that ICE happens when trying to compile aho-corasick-1.1.2.

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (a4472498d 2024-02-15)
binary: rustc
commit-hash: a4472498d7e88041f6206faf4503eb1f246fd427
commit-date: 2024-02-15
host: x86_64-apple-darwin
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Error output

```
error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/Users/lanxingcan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aho-corasick-1.1.2/rustc-ice-2024-02-16T07_22_03-25603.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -Z next-solver=globally

note: some of the compiler flags provided by cargo are hidden

```
The file mentioned in the log is attached here: [rustc-ice-2024-02-16T07_22_03-25603.txt](https://github.com/rust-lang/rust/files/14307747/rustc-ice-2024-02-16T07_22_03-25603.txt)

<details><summary><strong>Backtrace</strong></summary>
<p>

```
query stack during panic:
#0 [mir_built] building MIR for `dfa::<impl at /Users/lanxingcan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aho-corasick-1.1.2/src/dfa.rs:405:1: 405:13>::finish_build_one_start::{closure#1}`
#1 [check_unsafety] unsafety-checking `dfa::<impl at /Users/lanxingcan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aho-corasick-1.1.2/src/dfa.rs:405:1: 405:13>::finish_build_one_start`
#2 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at compiler/rustc_mir_build/src/build/expr/as_place.rs:253:31:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x10e57aa25 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h979943bf502d7d4f
   1:        0x10e5c778b - core::fmt::write::hfa5e946638ba09b1
   2:        0x10e57095e - std::io::Write::write_fmt::h2f93bdcc2c4814f2
   3:        0x10e57a7e1 - std::sys_common::backtrace::print::ha205db31e79ae7db
   4:        0x10e57d839 - std::panicking::default_hook::{{closure}}::hdc0706eac9b3b16f
   5:        0x10e57d5a6 - std::panicking::default_hook::heb163f3854404db4
   6:        0x11820addf - std[afc9c01a3f1ae6db]::panicking::update_hook::<alloc[e0b6c6bf68f50a7f]::boxed::Box<rustc_driver_impl[d97970b31c4866e7]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x10e57e35b - std::panicking::rust_panic_with_hook::h6d9f9e8cadeb5bcc
   8:        0x10e57dc5c - std::panicking::begin_panic_handler::{{closure}}::hbb88d2355d64a0ce
   9:        0x10e57af19 - std::sys_common::backtrace::__rust_end_short_backtrace::h805afcec460e6e6f
  10:        0x10e57d9c6 - _rust_begin_unwind
  11:        0x10e5e3b85 - core::panicking::panic_fmt::h64574c8e7fa9fc25
  12:        0x10e5e3c57 - core::panicking::panic::hbb2532f70fe96f1b
  13:        0x10e5e3b28 - core::option::unwrap_failed::h2cfc6cd5205f773c
  14:        0x118f3b03c - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_read_only_place
  15:        0x118f56754 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  16:        0x118f549c2 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_temp_inner
  17:        0x118f53fde - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_operand
  18:        0x118f3aa4e - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_call_operand
  19:        0x118f3ac76 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_call_operand
  20:        0x118f63779 - <core[b2919c948e44261c]::iter::adapters::copied::Copied<core[b2919c948e44261c]::slice::iter::Iter<rustc_middle[d916dff39ba3e6f7]::thir::ExprId>> as core[b2919c948e44261c]::iter::traits::iterator::Iterator>::fold::<(), core[b2919c948e44261c]::iter::adapters::map::map_fold<rustc_middle[d916dff39ba3e6f7]::thir::ExprId, rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>, (), <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#4}, core[b2919c948e44261c]::iter::traits::iterator::Iterator::for_each::call<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>, <alloc[e0b6c6bf68f50a7f]::vec::Vec<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>>>::extend_trusted<core[b2919c948e44261c]::iter::adapters::map::Map<core[b2919c948e44261c]::iter::adapters::copied::Copied<core[b2919c948e44261c]::slice::iter::Iter<rustc_middle[d916dff39ba3e6f7]::thir::ExprId>>, <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#4}>>::{closure#0}>::{closure#0}>::{closure#0}>
  21:        0x118f9a8b7 - <alloc[e0b6c6bf68f50a7f]::vec::Vec<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>> as alloc[e0b6c6bf68f50a7f]::vec::spec_from_iter::SpecFromIter<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>, core[b2919c948e44261c]::iter::adapters::map::Map<core[b2919c948e44261c]::iter::adapters::copied::Copied<core[b2919c948e44261c]::slice::iter::Iter<rustc_middle[d916dff39ba3e6f7]::thir::ExprId>>, <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#4}>>>::from_iter
  22:        0x118f5597a - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  23:        0x118f549c2 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_temp_inner
  24:        0x118f3b14e - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_as_place
  25:        0x118f3afb2 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_read_only_place
  26:        0x118f56754 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  27:        0x118f549c2 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_temp_inner
  28:        0x118f53fde - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_operand
  29:        0x118f3aa4e - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_call_operand
  30:        0x118f3ac76 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_call_operand
  31:        0x118f63779 - <core[b2919c948e44261c]::iter::adapters::copied::Copied<core[b2919c948e44261c]::slice::iter::Iter<rustc_middle[d916dff39ba3e6f7]::thir::ExprId>> as core[b2919c948e44261c]::iter::traits::iterator::Iterator>::fold::<(), core[b2919c948e44261c]::iter::adapters::map::map_fold<rustc_middle[d916dff39ba3e6f7]::thir::ExprId, rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>, (), <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#4}, core[b2919c948e44261c]::iter::traits::iterator::Iterator::for_each::call<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>, <alloc[e0b6c6bf68f50a7f]::vec::Vec<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>>>::extend_trusted<core[b2919c948e44261c]::iter::adapters::map::Map<core[b2919c948e44261c]::iter::adapters::copied::Copied<core[b2919c948e44261c]::slice::iter::Iter<rustc_middle[d916dff39ba3e6f7]::thir::ExprId>>, <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#4}>>::{closure#0}>::{closure#0}>::{closure#0}>
  32:        0x118f9a8b7 - <alloc[e0b6c6bf68f50a7f]::vec::Vec<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>> as alloc[e0b6c6bf68f50a7f]::vec::spec_from_iter::SpecFromIter<rustc_span[4f8fd407630359e1]::source_map::Spanned<rustc_middle[d916dff39ba3e6f7]::mir::syntax::Operand>, core[b2919c948e44261c]::iter::adapters::map::Map<core[b2919c948e44261c]::iter::adapters::copied::Copied<core[b2919c948e44261c]::slice::iter::Iter<rustc_middle[d916dff39ba3e6f7]::thir::ExprId>>, <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#4}>>>::from_iter
  33:        0x118f5597a - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  34:        0x118f549c2 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::as_temp_inner
  35:        0x118f45a04 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::then_else_break
  36:        0x118f45fba - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::then_else_break
  37:        0x118f45fba - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::then_else_break
  38:        0x118f57647 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  39:        0x118f5b4ca - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::in_scope::<<rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  40:        0x118f58cdd - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}
  41:        0x118f55b14 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  42:        0x118f38688 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::ast_block_stmts
  43:        0x118f5ba66 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::in_scope::<<rustc_mir_build[4c9e0c252421902f]::build::Builder>::ast_block::{closure#0}, ()>
  44:        0x118f55be3 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  45:        0x118f5b4ca - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::in_scope::<<rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  46:        0x118f58cdd - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}
  47:        0x118f55b14 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  48:        0x118f5765b - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  49:        0x118f5b4ca - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::in_scope::<<rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  50:        0x118f58cdd - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}
  51:        0x118f55b14 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  52:        0x118f39a97 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::ast_block_stmts
  53:        0x118f5ba66 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::in_scope::<<rustc_mir_build[4c9e0c252421902f]::build::Builder>::ast_block::{closure#0}, ()>
  54:        0x118f55be3 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  55:        0x118f5b4ca - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::in_scope::<<rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  56:        0x118f58cdd - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest::{closure#0}
  57:        0x118f55b14 - <rustc_mir_build[4c9e0c252421902f]::build::Builder>::expr_into_dest
  58:        0x118f343a1 - rustc_mir_build[4c9e0c252421902f]::build::mir_build::{closure#0}
  59:        0x118f32898 - rustc_mir_build[4c9e0c252421902f]::build::mir_built
  60:        0x11979225f - rustc_query_impl[c6e1f6f96af28a0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6e1f6f96af28a0e]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d916dff39ba3e6f7]::query::erase::Erased<[u8; 8usize]>>
  61:        0x11985ab0c - <rustc_query_impl[c6e1f6f96af28a0e]::query_impl::mir_built::dynamic_query::{closure#2} as core[b2919c948e44261c]::ops::function::FnOnce<(rustc_middle[d916dff39ba3e6f7]::ty::context::TyCtxt, rustc_span[4f8fd407630359e1]::def_id::LocalDefId)>>::call_once
  62:        0x119741897 - rustc_query_system[220fe0e828ed40f9]::query::plumbing::try_execute_query::<rustc_query_impl[c6e1f6f96af28a0e]::DynamicConfig<rustc_query_system[220fe0e828ed40f9]::query::caches::VecCache<rustc_span[4f8fd407630359e1]::def_id::LocalDefId, rustc_middle[d916dff39ba3e6f7]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c6e1f6f96af28a0e]::plumbing::QueryCtxt, false>
  63:        0x1198205ab - rustc_query_impl[c6e1f6f96af28a0e]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  64:        0x118fdc581 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor>::visit_inner_body
  65:        0x118fdd8f6 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  66:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  67:        0x118f5f315 - rustc_middle[d916dff39ba3e6f7]::thir::visit::walk_expr::<rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor>
  68:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  69:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  70:        0x118fdcbc9 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_block
  71:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  72:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  73:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  74:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  75:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  76:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  77:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  78:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  79:        0x118f5f449 - rustc_middle[d916dff39ba3e6f7]::thir::visit::walk_expr::<rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor>
  80:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  81:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  82:        0x118fdcbc9 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_block
  83:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  84:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  85:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  86:        0x118f5f449 - rustc_middle[d916dff39ba3e6f7]::thir::visit::walk_expr::<rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor>
  87:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  88:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  89:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  90:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  91:        0x118fdcbc9 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_block
  92:        0x118fdd99b - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  93:        0x118fdda82 - <rustc_mir_build[4c9e0c252421902f]::check_unsafety::UnsafetyVisitor as rustc_middle[d916dff39ba3e6f7]::thir::visit::Visitor>::visit_expr
  94:        0x118fde29f - rustc_mir_build[4c9e0c252421902f]::check_unsafety::check_unsafety
  95:        0x11978d65f - rustc_query_impl[c6e1f6f96af28a0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6e1f6f96af28a0e]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d916dff39ba3e6f7]::query::erase::Erased<[u8; 0usize]>>
  96:        0x11981b83c - <rustc_query_impl[c6e1f6f96af28a0e]::query_impl::check_unsafety::dynamic_query::{closure#2} as core[b2919c948e44261c]::ops::function::FnOnce<(rustc_middle[d916dff39ba3e6f7]::ty::context::TyCtxt, rustc_span[4f8fd407630359e1]::def_id::LocalDefId)>>::call_once
  97:        0x119731559 - rustc_query_system[220fe0e828ed40f9]::query::plumbing::try_execute_query::<rustc_query_impl[c6e1f6f96af28a0e]::DynamicConfig<rustc_query_system[220fe0e828ed40f9]::query::caches::VecCache<rustc_span[4f8fd407630359e1]::def_id::LocalDefId, rustc_middle[d916dff39ba3e6f7]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[c6e1f6f96af28a0e]::plumbing::QueryCtxt, false>
  98:        0x11999faba - rustc_query_impl[c6e1f6f96af28a0e]::query_impl::check_unsafety::get_query_non_incr::__rust_end_short_backtrace
  99:        0x118a9810d - <rustc_middle[d916dff39ba3e6f7]::hir::map::Map>::par_body_owners::<rustc_interface[9dbd0d3bf6d5e45e]::passes::analysis::{closure#1}::{closure#0}>::{closure#0}
 100:        0x118a568dd - <rustc_data_structures[6eb0080a98524774]::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures[6eb0080a98524774]::sync::parallel::enabled::par_for_each_in<&rustc_span[4f8fd407630359e1]::def_id::LocalDefId, &[rustc_span[4f8fd407630359e1]::def_id::LocalDefId], <rustc_middle[d916dff39ba3e6f7]::hir::map::Map>::par_body_owners<rustc_interface[9dbd0d3bf6d5e45e]::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
 101:        0x118ac27be - <rustc_session[5761a788d009e717]::session::Session>::time::<(), rustc_interface[9dbd0d3bf6d5e45e]::passes::analysis::{closure#1}>
 102:        0x118ab3191 - rustc_interface[9dbd0d3bf6d5e45e]::passes::analysis
 103:        0x119791edd - rustc_query_impl[c6e1f6f96af28a0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6e1f6f96af28a0e]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d916dff39ba3e6f7]::query::erase::Erased<[u8; 1usize]>>
 104:        0x1198a7789 - <rustc_query_impl[c6e1f6f96af28a0e]::query_impl::analysis::dynamic_query::{closure#2} as core[b2919c948e44261c]::ops::function::FnOnce<(rustc_middle[d916dff39ba3e6f7]::ty::context::TyCtxt, ())>>::call_once
 105:        0x1196924a5 - rustc_query_system[220fe0e828ed40f9]::query::plumbing::try_execute_query::<rustc_query_impl[c6e1f6f96af28a0e]::DynamicConfig<rustc_query_system[220fe0e828ed40f9]::query::caches::SingleCache<rustc_middle[d916dff39ba3e6f7]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c6e1f6f96af28a0e]::plumbing::QueryCtxt, false>
 106:        0x119977271 - rustc_query_impl[c6e1f6f96af28a0e]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
 107:        0x1181f0019 - <rustc_middle[d916dff39ba3e6f7]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[d97970b31c4866e7]::run_compiler::{closure#0}::{closure#0}::{closure#3}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>
 108:        0x1181bf0dd - <rustc_interface[9dbd0d3bf6d5e45e]::interface::Compiler>::enter::<rustc_driver_impl[d97970b31c4866e7]::run_compiler::{closure#0}::{closure#0}, core[b2919c948e44261c]::result::Result<core[b2919c948e44261c]::option::Option<rustc_interface[9dbd0d3bf6d5e45e]::queries::Linker>, rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>
 109:        0x1181ef5c6 - rustc_span[4f8fd407630359e1]::set_source_map::<core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>, rustc_interface[9dbd0d3bf6d5e45e]::interface::run_compiler<core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>, rustc_driver_impl[d97970b31c4866e7]::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
 110:        0x1181f92c9 - std[afc9c01a3f1ae6db]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9dbd0d3bf6d5e45e]::util::run_in_thread_with_globals<rustc_interface[9dbd0d3bf6d5e45e]::util::run_in_thread_pool_with_globals<rustc_interface[9dbd0d3bf6d5e45e]::interface::run_compiler<core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>, rustc_driver_impl[d97970b31c4866e7]::run_compiler::{closure#0}>::{closure#0}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>::{closure#0}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>
 111:        0x1181b5a83 - <<std[afc9c01a3f1ae6db]::thread::Builder>::spawn_unchecked_<rustc_interface[9dbd0d3bf6d5e45e]::util::run_in_thread_with_globals<rustc_interface[9dbd0d3bf6d5e45e]::util::run_in_thread_pool_with_globals<rustc_interface[9dbd0d3bf6d5e45e]::interface::run_compiler<core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>, rustc_driver_impl[d97970b31c4866e7]::run_compiler::{closure#0}>::{closure#0}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>::{closure#0}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b2919c948e44261c]::result::Result<(), rustc_span[4f8fd407630359e1]::ErrorGuaranteed>>::{closure#1} as core[b2919c948e44261c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 112:        0x10e5870e9 - std::sys::pal::unix::thread::Thread::new::thread_start::h4b368d65f4b6afb7
 113:     0x7ff81aee0202 - __pthread_start
```

</p>
</details>

**Comment by 5225225** [comment]
I can't reproduce this on the latest nightly, so this seems fixed. Bisected it for fun anyways and got https://github.com/rust-lang/rust/pull/119106

searched nightlies: from nightly-2024-02-15 to nightly-2024-03-04
regressed nightly: nightly-2024-02-27
searched commit range: https://github.com/rust-lang/rust/compare/0ecbd0605770f45c9151715e66ba2b3cae367fcb...fc3800f65777a365b5125706d60f97e4d0675efe
regressed commit: https://github.com/rust-lang/rust/commit/b8de591b6556836633e0c1bce1f42b90801f4227

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve --start 2024-02-15 --regress non-ice --access github 
```
</details>

Can you still reproduce this?

**Comment by thynson** [comment]
It seems already fixed
