### ISSUE TITLE
ICE: `encountered errors when checking RPITIT refinement (regions)`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#121457]
auto-reduced (treereduce-rust):
````rust
pub trait Iterable {
    type Item<'a>
    where
        Self: 'a;

    fn iter(&self) -> impl '_;
}

impl<'a, I: 'a + Iterable> Iterable for &'a I {
    type Item<'a>: 'a;

    fn iter(&self) -> impl Iterator<Item = Self::Item<'missing>>;
}


````

original:
````rust
// issue: 114145


pub trait Iterable {
    type Item<'a>
    where
        Self: 'a;

    fn iter(&self) -> impl '_ + Iterator<Trait2 = Self::Item<'_>>;
}

impl<'a, I: 'a + Iterable> Iterable for &'a I {
    type Item<'a>
    where
        Self: 'a;

    fn iter(&self) -> impl Iterator<Item = Self::Item<'missing>>;
    //~^ ERROR use of undeclared lifetime name `'missing`
}

fn main() {}

````

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error: at least one trait must be specified
 --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:6:23
  |
6 |     fn iter(&self) -> impl '_;
  |                       ^^^^^^^

error: associated type in `impl` without body
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:10:5
   |
10 |     type Item<'a>: 'a;
   |     ^^^^^^^^^^^^^^^^^-
   |                      |
   |                      help: provide a definition for the type: `= <type>;`

error: bounds on `type`s in `impl`s have no effect
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:10:20
   |
10 |     type Item<'a>: 'a;
   |                    ^^

error: associated function in `impl` without body
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:12:5
   |
12 |     fn iter(&self) -> impl Iterator<Item = Self::Item<'missing>>;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
   |                                                                 |
   |                                                                 help: provide a definition for the function: `{ <body> }`

error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:10:15
   |
9  | impl<'a, I: 'a + Iterable> Iterable for &'a I {
   |      -- first declared here
10 |     type Item<'a>: 'a;
   |               ^^ lifetime `'a` already in scope

error[E0261]: use of undeclared lifetime name `'missing`
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:12:55
   |
12 |     fn iter(&self) -> impl Iterator<Item = Self::Item<'missing>>;
   |                                                       ^^^^^^^^ undeclared lifetime
   |
   = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'missing` lifetime
   |
12 |     fn iter(&self) -> impl for<'missing> Iterator<Item = Self::Item<'missing>>;
   |                            +++++++++++++
help: consider introducing lifetime `'missing` here
   |
12 |     fn iter<'missing>(&self) -> impl Iterator<Item = Self::Item<'missing>>;
   |            ++++++++++
help: consider introducing lifetime `'missing` here
   |
9  | impl<'missing, 'a, I: 'a + Iterable> Iterable for &'a I {
   |      +++++++++

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:13:2
   |
13 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs`

error[E0477]: the type `&'a I` does not fulfill the required lifetime
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:10:5
   |
2  |     type Item<'a>
   |     ------------- definition of `Item` from trait
...
10 |     type Item<'a>: 'a;
   |     ^^^^^^^^^^^^^^^^^^
   |
note: type must outlive the anonymous lifetime as defined here
  --> /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:10:15
   |
10 |     type Item<'a>: 'a;
   |               ^^
help: copy the `where` clause predicates from the trait
   |
10 |     type Item<'a>: 'a where Self: '_;
   |                       ++++++++++++++

error: internal compiler error: encountered errors when checking RPITIT refinement (regions)

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/check/compare_impl_item/refine.rs:171:19:
Box<dyn Any>
stack backtrace:
   0:     0x7f1264d8caf6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f1264d8caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1264d8caf6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f1264d8caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1264ddda7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f1264ddda7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f1264d814bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7f1264d8c8a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f1264d8c8a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f1264d8f5eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7f1264d8f339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7f1267c7a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f1264d8fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7f1264d8fd50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7f1267ca7524 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}
  15:     0x7f1267ca4176 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_end_short_backtrace::<std[5a8e7f94216a9138]::panicking::begin_panic<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}, !>
  16:     0x7f1267c9f936 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>
  17:     0x7f1266617631 - <rustc_errors[34364e5c712fab73]::diagnostic::BugAbort as rustc_errors[34364e5c712fab73]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f1267d2136b - <rustc_errors[34364e5c712fab73]::DiagCtxt>::bug::<&str>
  19:     0x7f12698494bd - rustc_hir_analysis[71d4294717f7f2b7]::check::compare_impl_item::refine::check_refining_return_position_impl_trait_in_trait
  20:     0x7f1269b53587 - rustc_hir_analysis[71d4294717f7f2b7]::check::check::check_item_type
  21:     0x7f12696fccb1 - rustc_hir_analysis[71d4294717f7f2b7]::check::wfcheck::check_well_formed
  22:     0x7f12696fbd1d - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  23:     0x7f12696fb3ff - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::VecCache<rustc_hir[170b9793d794ea06]::hir_id::OwnerId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  24:     0x7f12696fb17f - rustc_query_impl[9d4c51777e2bb749]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7f12696f9041 - rustc_hir_analysis[71d4294717f7f2b7]::check::wfcheck::check_mod_type_wf
  26:     0x7f12696f8f89 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  27:     0x7f12699ac270 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_span[adb133ac03280fc1]::def_id::LocalModDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  28:     0x7f12699abf7f - rustc_query_impl[9d4c51777e2bb749]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f12699ad2bc - rustc_middle[446dd094ad85939e]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_span[adb133ac03280fc1]::def_id::LocalModDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, ()>
  30:     0x7f12699adaf1 - rustc_hir_analysis[71d4294717f7f2b7]::check_crate
  31:     0x7f1269aa2dd3 - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  32:     0x7f1269aa2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  33:     0x7f1269d3d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  34:     0x7f1269d3d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f1269d4c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  36:     0x7f1269fbe705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  37:     0x7f1269fbe532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f1264d99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  39:     0x7f1264d99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  40:     0x7f1264d99725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  41:     0x7f1264b779eb - <unknown>
  42:     0x7f1264bfb7cc - <unknown>
  43:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [check_well_formed] checking that `<impl at /tmp/icemaker_global_tempdir.5zeGBwlYGxpV/rustc_testrunner_tmpdir_reporting.0dQILLcbkEFM/mvce.rs:9:1: 9:46>` is well-formed
#1 [check_mod_type_wf] checking that types are well-formed in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 9 previous errors

Some errors have detailed explanations: E0261, E0477, E0496, E0601.
For more information about an error, try `rustc --explain E0261`.

```

</p>
</details>

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/121208 cc @nnethercote
