### ISSUE TITLE
ICE: `expected const for .. but found Type(usize) when instantiating args=[usize] `

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#121429]
snippet:
````rust
#![feature(generic_const_exprs)]

pub trait True {}

impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
    If<{}>: True
{
}


````

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0412]: cannot find type `FixedI8` in this scope
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:50
  |
5 | impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                                                  ^^^^^^^ not found in this scope

error[E0412]: cannot find type `FRAC_RHS` in this scope
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:58
  |
5 | impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                                                          ^^^^^^^^ not found in this scope
  |
help: you might be missing a type parameter
  |
5 | impl<const N: usize = { const { 3 } }, FRAC_RHS> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                                      ++++++++++

error[E0412]: cannot find type `FixedI8` in this scope
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:73
  |
5 | impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                                                                         ^^^^^^^ not found in this scope

error[E0412]: cannot find type `FRAC_LHS` in this scope
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:81
  |
5 | impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                                                                                 ^^^^^^^^ not found in this scope
  |
help: you might be missing a type parameter
  |
5 | impl<const N: usize = { const { 3 } }, FRAC_LHS> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                                      ++++++++++

error[E0412]: cannot find type `If` in this scope
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:6:5
  |
6 |     If<{}>: True
  |     ^^ not found in this scope

error[E0658]: inline-const is experimental
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:25
  |
5 | impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |                         ^^^^^
  |
  = note: see issue #76001 <https://github.com/rust-lang/rust/issues/76001> for more information
  = help: add `#![feature(inline_const)]` to the crate attributes to enable
  = note: this compiler was built on 2024-02-21; consider upgrading it if it is out of date

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:8:2
  |
8 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs`

error: defaults for const parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions
 --> /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:6
  |
5 | impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: compiler/rustc_middle/src/ty/generic_args.rs:956:9: expected const for `N/#0` (N/#0: usize/0) but found Type(usize) when instantiating args=[usize]

thread 'rustc' panicked at compiler/rustc_middle/src/util/bug.rs:35:44:
Box<dyn Any>
stack backtrace:
   0:     0x7ffa6ad8caf6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7ffa6ad8caf6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ffa6ad8caf6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7ffa6ad8caf6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ffa6addda7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7ffa6addda7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7ffa6ad814bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7ffa6ad8c8a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7ffa6ad8c8a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7ffa6ad8f5eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7ffa6ad8f339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7ffa6dc7a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7ffa6ad8fd50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7ffa6ad8fd50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7ffa6dca7524 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}
  15:     0x7ffa6dca4176 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_end_short_backtrace::<std[5a8e7f94216a9138]::panicking::begin_panic<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}, !>
  16:     0x7ffa6dc9f936 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>
  17:     0x7ffa6c617631 - <rustc_errors[34364e5c712fab73]::diagnostic::BugAbort as rustc_errors[34364e5c712fab73]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7ffa6e08300c - <rustc_errors[34364e5c712fab73]::DiagCtxt>::bug::<alloc[e14ab1f516d287ab]::string::String>
  19:     0x7ffa6e127c7b - rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt::<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}
  20:     0x7ffa6e10bc3a - rustc_middle[446dd094ad85939e]::ty::context::tls::with_opt::<rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7ffa6e10bab8 - rustc_middle[446dd094ad85939e]::ty::context::tls::with_context_opt::<rustc_middle[446dd094ad85939e]::ty::context::tls::with_opt<rustc_middle[446dd094ad85939e]::util::bug::opt_span_bug_fmt<rustc_span[adb133ac03280fc1]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7ffa6c599af0 - rustc_middle[446dd094ad85939e]::util::bug::bug_fmt
  23:     0x7ffa6e11bba2 - <rustc_middle[446dd094ad85939e]::ty::generic_args::ArgFolder>::const_param_expected
  24:     0x7ffa6f038649 - <rustc_middle[446dd094ad85939e]::ty::generic_args::ArgFolder as rustc_type_ir[2405427f08dfadb1]::fold::TypeFolder<rustc_middle[446dd094ad85939e]::ty::context::TyCtxt>>::fold_const
  25:     0x7ffa6f37139d - <&rustc_middle[446dd094ad85939e]::ty::list::List<rustc_middle[446dd094ad85939e]::ty::generic_args::GenericArg> as rustc_type_ir[2405427f08dfadb1]::fold::TypeFoldable<rustc_middle[446dd094ad85939e]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[446dd094ad85939e]::ty::generic_args::ArgFolder>
  26:     0x7ffa6f038541 - <rustc_middle[446dd094ad85939e]::ty::generic_args::ArgFolder as rustc_type_ir[2405427f08dfadb1]::fold::TypeFolder<rustc_middle[446dd094ad85939e]::ty::context::TyCtxt>>::fold_const
  27:     0x7ffa6f037fc8 - <rustc_middle[446dd094ad85939e]::ty::predicate::Clause as rustc_type_ir[2405427f08dfadb1]::fold::TypeFoldable<rustc_middle[446dd094ad85939e]::ty::context::TyCtxt>>::try_fold_with::<rustc_middle[446dd094ad85939e]::ty::generic_args::ArgFolder>
  28:     0x7ffa6f035d60 - <rustc_middle[446dd094ad85939e]::ty::generics::GenericPredicates>::instantiate_into
  29:     0x7ffa6f035ff5 - <rustc_middle[446dd094ad85939e]::ty::generics::GenericPredicates>::instantiate_into
  30:     0x7ffa6f6aa74f - rustc_trait_selection[f311605eeacf2c8d]::traits::query::type_op::ascribe_user_type::type_op_ascribe_user_type_with_span
  31:     0x7ffa6f14fa91 - rustc_traits[e4f791f45ab3a736]::type_op::type_op_ascribe_user_type
  32:     0x7ffa6f14f42e - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::type_op_ascribe_user_type::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7ffa6f14f3f7 - <rustc_query_impl[9d4c51777e2bb749]::query_impl::type_op_ascribe_user_type::dynamic_query::{closure#2} as core[85b4fd477ce5bb21]::ops::function::FnOnce<(rustc_middle[446dd094ad85939e]::ty::context::TyCtxt, rustc_type_ir[2405427f08dfadb1]::canonical::Canonical<rustc_middle[446dd094ad85939e]::ty::context::TyCtxt, rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::traits::query::type_op::AscribeUserType>>)>>::call_once
  34:     0x7ffa6f9d0499 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_type_ir[2405427f08dfadb1]::canonical::Canonical<rustc_middle[446dd094ad85939e]::ty::context::TyCtxt, rustc_middle[446dd094ad85939e]::ty::ParamEnvAnd<rustc_middle[446dd094ad85939e]::traits::query::type_op::AscribeUserType>>, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  35:     0x7ffa6f9d01ae - rustc_query_impl[9d4c51777e2bb749]::query_impl::type_op_ascribe_user_type::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7ffa6f9cff2d - <rustc_middle[446dd094ad85939e]::traits::query::type_op::AscribeUserType as rustc_trait_selection[f311605eeacf2c8d]::traits::query::type_op::QueryTypeOp>::perform_query
  37:     0x7ffa6fe65ce4 - <rustc_borrowck[bb9d4175d74ce943]::type_check::TypeChecker>::ascribe_user_type
  38:     0x7ffa6f5571b7 - <rustc_borrowck[bb9d4175d74ce943]::type_check::TypeVerifier as rustc_middle[446dd094ad85939e]::mir::visit::Visitor>::visit_operand
  39:     0x7ffa6cd3809f - <rustc_borrowck[bb9d4175d74ce943]::type_check::TypeVerifier as rustc_middle[446dd094ad85939e]::mir::visit::Visitor>::visit_body
  40:     0x7ffa6ccf2ae0 - rustc_borrowck[bb9d4175d74ce943]::type_check::type_check
  41:     0x7ffa6ccd96bc - rustc_borrowck[bb9d4175d74ce943]::nll::compute_regions
  42:     0x7ffa6fded246 - rustc_borrowck[bb9d4175d74ce943]::do_mir_borrowck
  43:     0x7ffa6fddfb40 - rustc_borrowck[bb9d4175d74ce943]::mir_borrowck
  44:     0x7ffa6fddf5d7 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>
  45:     0x7ffa6f1098b0 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::VecCache<rustc_span[adb133ac03280fc1]::def_id::LocalDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  46:     0x7ffa6f10948c - rustc_query_impl[9d4c51777e2bb749]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  47:     0x7ffa6faa2f30 - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  48:     0x7ffa6faa2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  49:     0x7ffa6fd3d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  50:     0x7ffa6fd3d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  51:     0x7ffa6fd4c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  52:     0x7ffa6ffbe705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  53:     0x7ffa6ffbe532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  54:     0x7ffa6ad99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  55:     0x7ffa6ad99725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  56:     0x7ffa6ad99725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  57:     0x7ffa6ab819eb - <unknown>
  58:     0x7ffa6ac057cc - <unknown>
  59:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [type_op_ascribe_user_type] evaluating `type_op_ascribe_user_type` `AscribeUserType { mir_ty: usize, user_ty: TypeOf(DefId(0:7 ~ mvce[8c01]::{impl#0}::{constant#0}::{constant#0}), UserArgs { args: [usize], user_self_ty: None }) }`
#1 [mir_borrowck] borrow-checking `<impl at /tmp/icemaker_global_tempdir.YLWanMEPxk5w/rustc_testrunner_tmpdir_reporting.GqWIEqxOTkdO/mvce.rs:5:1: 6:17>::{constant#0}`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 9 previous errors; 1 warning emitted

Some errors have detailed explanations: E0412, E0601, E0658.
For more information about an error, try `rustc --explain E0412`.

```

</p>
</details>

**Comment by matthiaskrgr** [comment]
#120847 cc @oli-obk

**Comment by camelid** [comment]
After #133610, this particular code no longer crashes, but adding definitions causes it to start crashing again:

```rust
//@ known-bug: #121429

#![feature(generic_const_exprs)]

struct FixedI8<const X: usize>;
const FRAC_LHS: usize = 0;
const FRAC_RHS: usize = 1;

pub trait True {}

impl<const N: usize = { const { 3 } }> PartialEq<FixedI8<FRAC_RHS>> for FixedI8<FRAC_LHS> where
    If<{}>: True
{
}
```

**Comment by oli-obk** [comment]
The test in the test suite wasn't minimal.

```rust
#![feature(generic_const_exprs)]

struct FixedI8<const X: usize>;
const FRAC_LHS: usize = 0;

trait Foo<const N: usize> {}

impl<const N: usize = { const { 3 } }> Foo<FRAC_LHS> for () {}
```

is a bit reduced in what things it uses. Please only add minimal (human reduced, removing unrelated errors by adding definitions and simplifying types that are not relevant to the repro) tests to the test suite.

I removed it without replacement when it stopped ICEing again, it seemed like a not useful test to me either way
