### ISSUE TITLE
ICE: `failed region resolution while normalizing ParamEnv `

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#121414]
auto-reduced (treereduce-rust):
````rust
trait Bar {
    type Type;
}
struct Foo<'a>(&'a ());
impl<'a> Bar for Foo<'f> {}

fn test()
where
    for<'a> <Foo<'a> as Bar>::Type: Sized,
{
}


````

original:
````rust
//@ check-pass

trait Bar {
    type Type;
}
struct Foo<'a>(&'a ());
impl<'a> Bar for Foo<'f> {
    type Type = ();
}

fn func<'a>(_: <Foo<'a> as Bar>::Type) {}
fn assert_is_func<A>(_: fn(A)) {}

fn test()
where
    for<'a> <Foo<'a> as Bar>::Type: Sized,
{
    wrapper(func);
}

fn main() {}

````

Version information
````
rustc 1.78.0-nightly (f8131a48a 2024-02-21)
binary: rustc
commit-hash: f8131a48a46ac3bc8a3d0fe0477055b132cffdc3
commit-date: 2024-02-21
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0261]: use of undeclared lifetime name `'f`
 --> /tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs:5:22
  |
5 | impl<'a> Bar for Foo<'f> {}
  |      -               ^^ undeclared lifetime
  |      |
  |      help: consider introducing lifetime `'f` here: `'f,`

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs:11:2
   |
11 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs`

error[E0046]: not all trait items implemented, missing: `Type`
 --> /tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs:5:1
  |
2 |     type Type;
  |     --------- `Type` from trait
...
5 | impl<'a> Bar for Foo<'f> {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^ missing `Type` in implementation

error: internal compiler error: failed region resolution while normalizing ParamEnv { caller_bounds: [Binder { value: TraitPredicate(<<Foo<'a> as Bar>::Type as std::marker::Sized>, polarity:Positive), bound_vars: [Region(BrNamed(DefId(0:12 ~ mvce[8c01]::test::'a), 'a))] }], reveal: UserFacing }: [ConcreteFailure(Subtype(TypeTrace { cause: ObligationCause { span: /tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs:7:1: 9:43 (#0), body_id: DefId(0:11 ~ mvce[8c01]::test), code: MatchImpl(ObligationCause { span: /tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs:7:1: 9:43 (#0), body_id: DefId(0:11 ~ mvce[8c01]::test), code: MiscObligation }, DefId(0:9 ~ mvce[8c01]::{impl#0})) }, values: PolyTraitRefs(ExpectedFound { expected: Binder { value: <Foo<'a> as Bar>, bound_vars: [] }, found: Binder { value: <Foo<'_> as Bar>, bound_vars: [] } }) }), ReError, RePlaceholder(!1_BoundRegion { var: 0, kind: BrNamed(DefId(0:12 ~ mvce[8c01]::test::'a), 'a) }))]
 --> /tmp/icemaker_global_tempdir.Qz3b41LbdD6V/rustc_testrunner_tmpdir_reporting.lrX8blRIpTCX/mvce.rs:7:1
  |
7 | / fn test()
8 | | where
9 | |     for<'a> <Foo<'a> as Bar>::Type: Sized,
  | |__________________________________________^

thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/mod.rs:177:19:
Box<dyn Any>
stack backtrace:
   0:     0x7f6d36226af6 - std::backtrace_rs::backtrace::libunwind::trace::hbec2edc838b433e2
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f6d36226af6 - std::backtrace_rs::backtrace::trace_unsynchronized::h88c30257ee0dd166
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6d36226af6 - std::sys_common::backtrace::_print_fmt::h9176654d509e3088
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f6d36226af6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h671feaee1776bf19
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f6d36277a7c - core::fmt::rt::Argument::fmt::h59605c83ae32d935
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/rt.rs:142:9
   5:     0x7f6d36277a7c - core::fmt::write::hf7af8dfcfd20db5b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f6d3621b4bf - std::io::Write::write_fmt::h92a5dbf489025e71
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/io/mod.rs:1846:15
   7:     0x7f6d362268a4 - std::sys_common::backtrace::_print::h00080302d23998ae
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f6d362268a4 - std::sys_common::backtrace::print::h6b23124445400245
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f6d362295eb - std::panicking::default_hook::{{closure}}::hd67b2f9d36675a28
  10:     0x7f6d36229339 - std::panicking::default_hook::h10a39ef11c714e42
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:292:9
  11:     0x7f6d32e7a94c - std[5a8e7f94216a9138]::panicking::update_hook::<alloc[e14ab1f516d287ab]::boxed::Box<rustc_driver_impl[e279e4f1fedd9109]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f6d36229d50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h37ba37dc48823c1d
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2030:9
  13:     0x7f6d36229d50 - std::panicking::rust_panic_with_hook::he3e3bc7c345bf54b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/panicking.rs:786:13
  14:     0x7f6d32ea7524 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}
  15:     0x7f6d32ea4176 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_end_short_backtrace::<std[5a8e7f94216a9138]::panicking::begin_panic<rustc_errors[34364e5c712fab73]::ExplicitBug>::{closure#0}, !>
  16:     0x7f6d32e9f936 - std[5a8e7f94216a9138]::panicking::begin_panic::<rustc_errors[34364e5c712fab73]::ExplicitBug>
  17:     0x7f6d31817631 - <rustc_errors[34364e5c712fab73]::diagnostic::BugAbort as rustc_errors[34364e5c712fab73]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f6d31e00316 - rustc_trait_selection[f311605eeacf2c8d]::traits::do_normalize_predicates
  19:     0x7f6d31ded59e - rustc_trait_selection[f311605eeacf2c8d]::traits::normalize_param_env_or_error
  20:     0x7f6d34550a80 - rustc_ty_utils[d35b0e036186ec50]::ty::param_env
  21:     0x7f6d345506f9 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::param_env::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>
  22:     0x7f6d34274da1 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefIdCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  23:     0x7f6d342747e1 - rustc_query_impl[9d4c51777e2bb749]::query_impl::param_env::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7f6d344262dc - rustc_middle[446dd094ad85939e]::query::plumbing::query_get_at::<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefIdCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 8usize]>>>
  25:     0x7f6d34350d3c - rustc_hir_analysis[71d4294717f7f2b7]::check::wfcheck::check_item_fn
  26:     0x7f6d348fce30 - rustc_hir_analysis[71d4294717f7f2b7]::check::wfcheck::check_well_formed
  27:     0x7f6d348fbd1d - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  28:     0x7f6d348fb3ff - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::VecCache<rustc_hir[170b9793d794ea06]::hir_id::OwnerId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  29:     0x7f6d348fb17f - rustc_query_impl[9d4c51777e2bb749]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  30:     0x7f6d348f9041 - rustc_hir_analysis[71d4294717f7f2b7]::check::wfcheck::check_mod_type_wf
  31:     0x7f6d348f8f89 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  32:     0x7f6d34bac270 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_span[adb133ac03280fc1]::def_id::LocalModDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  33:     0x7f6d34babf7f - rustc_query_impl[9d4c51777e2bb749]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f6d34bad2bc - rustc_middle[446dd094ad85939e]::query::plumbing::query_ensure_error_guaranteed::<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::DefaultCache<rustc_span[adb133ac03280fc1]::def_id::LocalModDefId, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, ()>
  35:     0x7f6d34badaf1 - rustc_hir_analysis[71d4294717f7f2b7]::check_crate
  36:     0x7f6d34ca2dd3 - rustc_interface[7ca501d7f8f3a34f]::passes::analysis
  37:     0x7f6d34ca2a29 - rustc_query_impl[9d4c51777e2bb749]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>
  38:     0x7f6d34f3d4a5 - rustc_query_system[9b2ccfe41ae3bb1b]::query::plumbing::try_execute_query::<rustc_query_impl[9d4c51777e2bb749]::DynamicConfig<rustc_query_system[9b2ccfe41ae3bb1b]::query::caches::SingleCache<rustc_middle[446dd094ad85939e]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[9d4c51777e2bb749]::plumbing::QueryCtxt, false>
  39:     0x7f6d34f3d209 - rustc_query_impl[9d4c51777e2bb749]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7f6d34f4c719 - rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler::<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}
  41:     0x7f6d351be705 - std[5a8e7f94216a9138]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>
  42:     0x7f6d351be532 - <<std[5a8e7f94216a9138]::thread::Builder>::spawn_unchecked_<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_with_globals<rustc_interface[7ca501d7f8f3a34f]::util::run_in_thread_pool_with_globals<rustc_interface[7ca501d7f8f3a34f]::interface::run_compiler<core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>, rustc_driver_impl[e279e4f1fedd9109]::run_compiler::{closure#0}>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[85b4fd477ce5bb21]::result::Result<(), rustc_span[adb133ac03280fc1]::ErrorGuaranteed>>::{closure#1} as core[85b4fd477ce5bb21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7f6d36233725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1bff3efb61c3fa6b
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  44:     0x7f6d36233725 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h83141cf549dced8a
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/alloc/src/boxed.rs:2016:9
  45:     0x7f6d36233725 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe9287fdd7c325bc
                               at /rustc/f8131a48a46ac3bc8a3d0fe0477055b132cffdc3/library/std/src/sys/pal/unix/thread.rs:108:17
  46:     0x7f6d2feaa9eb - <unknown>
  47:     0x7f6d2ff2e7cc - <unknown>
  48:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0-nightly (f8131a48a 2024-02-21) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [param_env] computing normalized predicates of `test`
#1 [check_well_formed] checking that `test` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 4 previous errors

Some errors have detailed explanations: E0046, E0261, E0601.
For more information about an error, try `rustc --explain E0046`.

```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Another one of #121208 cc @nnethercote
