### ISSUE TITLE
ICE in macros: the following error was constructed but not emitted

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#121535]
```rust
macro_rules! the_macro {
    ( $foo:stmt ; $bar:stmt ; ) => {
        #[cfg(foo)]
        $foo
        
        #[cfg(bar)]
        $bar
    };
}

fn the_function() {
    the_macro!( (); (); );
}
```
[(playground link)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f131a51d46805b77655067f74154e28c)

Error message on stable:
```
error: internal compiler error: the following error was constructed but not emitted

error: expected expression, found statement `();`
  --> src/lib.rs:7:9
   |
7  |         $bar
   |         ^^^^ expected expression
...
12 |     the_macro!( (); (); );
   |     --------------------- in this macro invocation
   |
   = note: this error originates in the macro `the_macro` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at compiler/rustc_errors/src/diagnostic_builder.rs:652:21:
error was constructed but not emitted
stack backtrace:
   0:     0x7f5f07d6e6f6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f5f07d6e6f6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5f07d6e6f6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f5f07d6e6f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5f07dc0f40 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x7f5f07dc0f40 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f5f07d6253f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x7f5f07d6e4d4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5f07d6e4d4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f5f07d71267 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x7f5f07d70fc9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x7f5f0a9f761c - std[79729d9c385e1623]::panicking::update_hook::<alloc[6df67106ebca92c0]::boxed::Box<rustc_driver_impl[66ed8fdbde15dc6c]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f5f07d719b6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbc5ccf4eb663e1e5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:     0x7f5f07d719b6 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:     0x7f5f07d716c9 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  15:     0x7f5f07d6ebf6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f5f07d71460 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:     0x7f5f07dbd645 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:     0x7f5f0d00908f - <rustc_errors[6510d8b7a29ddd9f]::diagnostic_builder::DiagnosticBuilderInner as core[f975038e3cc9791c]::ops::drop::Drop>::drop.cold.0
  19:     0x7f5f0c4edfe6 - core[f975038e3cc9791c]::ptr::drop_in_place::<rustc_errors[6510d8b7a29ddd9f]::diagnostic_builder::DiagnosticBuilderInner>
  20:     0x7f5f09774260 - <rustc_parse[406b87b8ca9a37a2]::parser::Parser>::attr_on_non_tail_expr
  21:     0x7f5f0c17ec58 - <rustc_parse[406b87b8ca9a37a2]::parser::Parser>::parse_full_stmt
  22:     0x7f5f0bf27885 - <rustc_expand[b004a55061f4def]::mbe::macro_rules::ParserAnyMacro>::make
  23:     0x7f5f0c663c99 - <rustc_expand[b004a55061f4def]::expand::MacroExpander>::fully_expand_fragment
  24:     0x7f5f0c6609fe - <rustc_expand[b004a55061f4def]::expand::MacroExpander>::expand_crate
  25:     0x7f5f0cacab71 - rustc_interface[bf5cafa581ab7832]::passes::resolver_for_lowering
  26:     0x7f5f0caca033 - rustc_query_impl[aa9389cf74aaab3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[aa9389cf74aaab3]::query_impl::resolver_for_lowering::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e0f609162babcb92]::query::erase::Erased<[u8; 8usize]>>
  27:     0x7f5f0c8d7c65 - rustc_query_system[84cc5057ded7d916]::query::plumbing::try_execute_query::<rustc_query_impl[aa9389cf74aaab3]::DynamicConfig<rustc_query_system[84cc5057ded7d916]::query::caches::SingleCache<rustc_middle[e0f609162babcb92]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[aa9389cf74aaab3]::plumbing::QueryCtxt, false>
  28:     0x7f5f0c8d7309 - rustc_query_impl[aa9389cf74aaab3]::query_impl::resolver_for_lowering::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f5f0c8e15f3 - rustc_interface[bf5cafa581ab7832]::interface::run_compiler::<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}
  30:     0x7f5f0ca0f7db - std[79729d9c385e1623]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bf5cafa581ab7832]::util::run_in_thread_with_globals<rustc_interface[bf5cafa581ab7832]::interface::run_compiler<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>
  31:     0x7f5f0ca0f639 - <<std[79729d9c385e1623]::thread::Builder>::spawn_unchecked_<rustc_interface[bf5cafa581ab7832]::util::run_in_thread_with_globals<rustc_interface[bf5cafa581ab7832]::interface::run_compiler<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#1} as core[f975038e3cc9791c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7f5f07d7b8e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  33:     0x7f5f07d7b8e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  34:     0x7f5f07d7b8e5 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7f5f07c8e609 - start_thread
  36:     0x7f5f07bb1353 - clone
  37:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.76.0 (07dca489a 2024-02-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
error: could not compile `playground` (lib) due to 1 previous error
```

Error message on nightly:
```
warning: function `the_function` is never used
  --> src/lib.rs:11:4
   |
11 | fn the_function() {
   |    ^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: lowered ExprKind::Err
  --> src/lib.rs:4:9
   |
4  |         $foo
   |         ^^^^
...
12 |     the_macro!( (); (); );
   |     --------------------- in this macro invocation
   |
note: delayed at compiler/rustc_ast_lowering/src/expr.rs:332:51
         0: <rustc_errors::DiagCtxtInner>::emit_diagnostic
         1: <rustc_errors::DiagCtxt>::emit_diagnostic
         2: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
         3: <rustc_ast_lowering::LoweringContext>::lower_expr_mut
         4: <rustc_ast_lowering::LoweringContext>::lower_block_noalloc
         5: <rustc_ast_lowering::LoweringContext>::lower_maybe_coroutine_body
         6: <rustc_ast_lowering::LoweringContext>::lower_item_kind
         7: <rustc_ast_lowering::item::ItemLowerer>::lower_node
         8: rustc_ast_lowering::lower_to_hir
         9: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::hir_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        11: rustc_query_impl::query_impl::hir_crate::get_query_non_incr::__rust_end_short_backtrace
        12: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::opt_hir_owner_nodes::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        14: rustc_query_impl::query_impl::opt_hir_owner_nodes::get_query_non_incr::__rust_end_short_backtrace
        15: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
        16: <rustc_middle::hir::map::Map>::get_module
        17: rustc_middle::hir::map::hir_crate_items
        18: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::hir_crate_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
        19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        20: rustc_query_impl::query_impl::hir_crate_items::get_query_non_incr::__rust_end_short_backtrace
        21: rustc_interface::proc_macro_decls::proc_macro_decls_static
        22: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::proc_macro_decls_static::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 4]>>
        23: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 4]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        24: rustc_query_impl::query_impl::proc_macro_decls_static::get_query_non_incr::__rust_end_short_backtrace
        25: rustc_interface::passes::analysis
        26: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        28: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
        29: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
        30: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
        31: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
        32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/alloc/src/boxed.rs:2016:9
        33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                   at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/alloc/src/boxed.rs:2016:9
        34: std::sys::pal::unix::thread::Thread::new::thread_start
                   at /rustc/397937d812852f9bbeb671005cb399dbcb357cde/library/std/src/sys/pal/unix/thread.rs:108:17
        35: start_thread
        36: clone
  --> src/lib.rs:4:9
   |
4  |         $foo
   |         ^^^^
...
12 |     the_macro!( (); (); );
   |     --------------------- in this macro invocation
   = note: this error: internal compiler error originates in the macro `the_macro` (in Nightly builds, run with -Z macro-backtrace for more info)

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please attach the file at `/playground/rustc-ice-2024-02-24T05_35_13-20.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `playground` (lib) generated 1 warning
error: could not compile `playground` (lib); 1 warning emitted
```

**Comment by chenyukang** [comment]
it's fixed on nightly.
