### ISSUE TITLE
Build failure thread 'main' panicked at src/core/metadata.rs:86:31 when trying to build rustc 1.76.0

### ISSUE THREAD

**Issue by ms178** [rust-lang/rust#121734]
Trying to build https://gitlab.archlinux.org/archlinux/packaging/packages/rust with having stable-x86_64-unknown-linux-gnu unchanged - rustc 1.76.0 (07dca489a 2024-02-04) installed, results in the following build failure.

```
Finished dev [unoptimized] target(s) in 38.21s
thread 'main' panicked at src/core/metadata.rs:86:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/usr/bin/rustup" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/tmp/makepkg/rust/src/rustc-1.76.0-src/Cargo.toml"
expected success, got: exit status: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: bootstrap::utils::helpers::output
             at ./src/bootstrap/src/utils/helpers.rs:266:9
   3: bootstrap::core::metadata::workspace_members::{{closure}}
             at ./src/bootstrap/src/core/metadata.rs:86:31
   4: bootstrap::core::metadata::workspace_members
             at ./src/bootstrap/src/core/metadata.rs:92:20
   5: bootstrap::core::metadata::build
             at ./src/bootstrap/src/core/metadata.rs:44:20
   6: bootstrap::Build::new
             at ./src/bootstrap/src/lib.rs:465:13
   7: bootstrap::main
             at ./src/bootstrap/src/bin/main.rs:85:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:38
```

System: Intel Haswell
OS: CachyOS
Flags in /etc/makepkg.conf:

```
#-- Compiler and Linker Flags
CPPFLAGS="-D_FORTIFY_SOURCE=0"
CFLAGS="-O3 -march=native -mtune=native"
CXXFLAGS="$CFLAGS -Wp,-U_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O3,--as-needed"
CCLDFLAGS="$LDFLAGS"
CXXLDFLAGS="$LDFLAGS"
FFLAGS="$CFLAGS"
FCFLAGS="$CFLAGS"
GOAMD64="v3"
ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -msse2avx -D__FMA__=1"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-Copt-level=2 -Ctarget-cpu=native"
#-- Make Flags: change this for DistCC/SMP systems
MAKEFLAGS="-j$(nproc)"
NINJAFLAGS="-j$(nproc)"
#-- Debugging flags
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="$DEBUG_CFLAGS"
#DEBUG_RUSTFLAGS="-C debuginfo=2"
```
`gcc-Version 13.2.1 20230801 (GCC) `

**Comment by jieyouxu** [comment]
Does it happen again if you clear the build cache? This might be an incremental comp issue.

**Comment by ms178** [comment]
I don't have a build cache enabled.

**Comment by ms178** [comment]
That's the content of that file, the hunk you were posting cannot be found there.

```
[workspace]
resolver = "1"
members = [
  "compiler/rustc",
  "library/std",
  "library/sysroot",
  "src/rustdoc-json-types",
  "src/tools/build_helper",
  "src/tools/cargotest",
  "src/tools/clippy",
  "src/tools/clippy/clippy_dev",
  "src/tools/compiletest",
  "src/tools/error_index_generator",
  "src/tools/linkchecker",
  "src/tools/lint-docs",
  "src/tools/miropt-test-tools",
  "src/tools/rustbook",
  "src/tools/unstable-book-gen",
  "src/tools/tidy",
  "src/tools/tier-check",
  "src/tools/build-manifest",
  "src/tools/remote-test-client",
  "src/tools/remote-test-server",
  "src/tools/rust-installer",
  "src/tools/rust-demangler",
  "src/tools/rustdoc",
  "src/tools/rls",
  "src/tools/rustfmt",
  "src/tools/miri",
  "src/tools/miri/cargo-miri",
  "src/tools/rustdoc-themes",
  "src/tools/unicode-table-generator",
  "src/tools/expand-yaml-anchors",
  "src/tools/jsondocck",
  "src/tools/jsondoclint",
  "src/tools/html-checker",
  "src/tools/bump-stage0",
  "src/tools/replace-version-placeholder",
  "src/tools/lld-wrapper",
  "src/tools/collect-license-metadata",
  "src/tools/generate-copyright",
  "src/tools/suggest-tests",
  "src/tools/generate-windows-sys",
  "src/tools/rustdoc-gui-test",
  "src/tools/opt-dist",
  "src/tools/coverage-dump",
]

exclude = [
  "build",
  "compiler/rustc_codegen_cranelift",
  "compiler/rustc_codegen_gcc",
  "src/bootstrap",
  "tests/rustdoc-gui",
  # HACK(eddyb) This hardcodes the fact that our CI uses `/checkout/obj`.
  "obj",
  # The `x` binary is a thin wrapper that calls `x.py`, which initializes
  # submodules, before which workspace members cannot be invoked because
  # not all `Cargo.toml` files are available, so we exclude the `x` binary,
  # so it can be invoked before the current checkout is set up.
  "src/tools/x",
  # stdarch has its own Cargo workspace
  "library/stdarch",
]

[profile.release.package.compiler_builtins]
# The compiler-builtins crate cannot reference libcore, and it's own CI will
# verify that this is the case. This requires, however, that the crate is built
# without overflow checks and debug assertions. Forcefully disable debug
# assertions and overflow checks here which should ensure that even if these
# assertions are enabled for libstd we won't enable them for compiler_builtins
# which should ensure we still link everything correctly.
debug-assertions = false
overflow-checks = false

# For compiler-builtins we always use a high number of codegen units.
# The goal here is to place every single intrinsic into its own object
# file to avoid symbol clashes with the system libgcc if possible. Note
# that this number doesn't actually produce this many object files, we
# just don't create more than this number of object files.
#
# It's a bit of a bummer that we have to pass this here, unfortunately.
# Ideally this would be specified through an env var to Cargo so Cargo
# knows how many CGUs are for this specific crate, but for now
# per-crate configuration isn't specifiable in the environment.
codegen-units = 10000

[profile.release.package.rustc-rayon-core]
# The rustc fork of Rayon has deadlock detection code which intermittently
# causes overflows in the CI (see https://github.com/rust-lang/rust/issues/90227)
# so we turn overflow checks off for now.
# FIXME: This workaround should be removed once #90227 is fixed.
overflow-checks = false

# These dependencies of the standard library implement symbolication for
# backtraces on most platforms. Their debuginfo causes both linking to be slower
# (more data to chew through) and binaries to be larger without really all that
# much benefit. This section turns them all to down to have no debuginfo which
# helps to improve link times a little bit.
[profile.release.package]
addr2line.debug = 0
adler.debug = 0
gimli.debug = 0
miniz_oxide.debug = 0
object.debug = 0

[patch.crates-io]
# See comments in `library/rustc-std-workspace-core/README.md` for what's going on
# here
rustc-std-workspace-core = { path = 'library/rustc-std-workspace-core' }
rustc-std-workspace-alloc = { path = 'library/rustc-std-workspace-alloc' }
rustc-std-workspace-std = { path = 'library/rustc-std-workspace-std' }

[patch."https://github.com/rust-lang/rust-clippy"]
clippy_lints = { path = "src/tools/clippy/clippy_lints" }
```

**Comment by ms178** [comment]
Is there anything wrong with the PKGBUILD? This is where some toml-settings are modified in the PKGBUILD:

https://gitlab.archlinux.org/archlinux/packaging/packages/rust/-/blob/main/PKGBUILD?ref_type=heads#L83

**Comment by jieyouxu** [comment]
I don't see anything *immediately* wrong. It's really hard to debug a custom build config unfortunately. I can only identify the cause of the issue as libstd's Config.toml can'be be read through a `cargo metadata` invocation but I can't pinpoint *what* would cause that in this build config.

I will tag this as https://github.com/rust-lang/rust/labels/T-bootstrap, maybe someone more familiar with Arch/makepkg can help out.

**Comment by the8472** [comment]
The PKGBUILD sets

```toml
[build]
cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
```

Which means it doesn't download the previous binaries and instead requires that previous version must be available locally at those locations.

**Comment by ms178** [comment]
> The PKGBUILD sets
> 
> ```toml
> [build]
> cargo = "/usr/bin/cargo"
> rustc = "/usr/bin/rustc"
> ```
> 
> Which means it doesn't download the previous binaries and instead requires that the previous version is available locally at those locations.

Thanks for that hint, it now works when I modify that part in the PKGBUILD with the following entries, pointing it to the binaries provided by rustup:

```
cargo = "/home/xxx/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo"
rustc = "/home/xxx/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc"
rustfmt = "/home/xxx/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustfmt"
```
