### ISSUE TITLE
Nigtly panic on optional unwrap

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-lang/rust#121707]
### Code

It is not clear whether specifically compiler fails, but it happens during compilation of the following crate:

```bash
cargo +nightly install commit_verify --version 0.11.0-beta.4 --all-features
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (fc3800f65 2024-02-26)
binary: rustc
commit-hash: fc3800f65777a365b5125706d60f97e4d0675efe
commit-date: 2024-02-26
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Error output

In the attached file
[rustc-ice-2024-02-27T21_35_46-630453.txt](https://github.com/rust-lang/rust/files/14426036/rustc-ice-2024-02-27T21_35_46-630453.txt)

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_ast_lowering/src/lib.rs:962:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc3800f65777a365b5125706d60f97e4d0675efe/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/fc3800f65777a365b5125706d60f97e4d0675efe/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/fc3800f65777a365b5125706d60f97e4d0675efe/library/core/src/panicking.rs:144:5
   3: core::option::unwrap_failed
             at /rustc/fc3800f65777a365b5125706d60f97e4d0675efe/library/core/src/option.rs:1985:5
   4: <rustc_ast_lowering::LoweringContext>::lower_attrs
   5: <rustc_ast_lowering::LoweringContext>::lower_assoc_item
   6: <rustc_ast_lowering::item::ItemLowerer>::lower_node
   7: rustc_ast_lowering::lower_to_hir
      [... omitted 2 frames ...]
   8: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
   9: <rustc_middle::hir::map::Map>::get_module
  10: rustc_middle::hir::map::hir_crate_items
      [... omitted 1 frame ...]
  11: rustc_interface::proc_macro_decls::proc_macro_decls_static
      [... omitted 1 frame ...]
  12: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  13: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C strip=debuginfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [hir_crate] getting the crate HIR
#1 [opt_hir_owner_nodes] getting HIR owner items in ``
#2 [hir_crate_items] getting HIR crate items
#3 [proc_macro_decls_static] looking up the proc macro declarations for a crate
#4 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by jieyouxu** [comment]
Reduced `rustc 1.78.0-nightly (0ecbd0605 2024-02-25)`:

```rs
trait Foo {
    #[doc=hidden]
    fn foo();
}
```

**Comment by jieyouxu** [comment]
searched nightlies: from nightly-2024-02-10 to nightly-2024-02-16
regressed nightly: nightly-2024-02-16
searched commit range: https://github.com/rust-lang/rust/compare/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46...a4472498d7e88041f6206faf4503eb1f246fd427
regressed commit: https://github.com/rust-lang/rust/commit/cbddf31863495050e840571d2730c95b29dcc27f

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start=2024-02-10 --end=2024-02-16
```
</details>

**Comment by jieyouxu** [comment]
Duplicate of #121537.
