### ISSUE TITLE
Panic at std/thread/mod.rs:1517, called Option::unwrap() on a `None` value

### ISSUE THREAD

**Issue by markussilvan** [rust-lang/rust#121822]
```
   Compiling tokio-util v0.7.10
   Compiling sqlx-postgres v0.7.3
   Compiling h2 v0.4.2
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/mod.rs:1517:40:
called `Option::unwrap()` on a `None` value
stack backtrace:
   Compiling sqlx-macros-core v0.7.3
   Compiling hyper v1.2.0
   Compiling sqlx-macros v0.7.3
   Compiling hyper-util v0.1.3
   Compiling tower v0.4.13
   Compiling serde_urlencoded v0.7.1
   Compiling serde_path_to_error v0.1.15
   Compiling axum v0.7.4
    Building [=======================> ] 230/235: sqlx-core                     
```                    

Compilation then hanged in this state as the main thread had panic'ed.
Running cargo build again later, it completed successfully and didn't reproduce the bug.
I'll try again in the weekend to see if can reproduce it again and get a backtrace.

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

**Comment by markussilvan** [comment]
It's unreproducible. I don't know what happened there.
