### ISSUE TITLE
Compiler crashed (ICE) when using `-Zcombine-cgu` under `dev/test profile`.

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/rust#121990]
`thread 'coordinator' panicked at /rustc/516b6162a2ea8e66678c09e8243ebd83e4b8eeea/compiler/rustc_codegen_ssa/src/back/write.rs:1581:37:
assertion failed: needs_link.is_empty()`

`thread 'rustc' panicked at compiler/rustc_middle/src/util/bug.rs:36:26:
/rustc/516b6162a2ea8e66678c09e8243ebd83e4b8eeea/compiler/rustc_codegen_ssa/src/back/write.rs:1992:17: panic during codegen/LLVM phase`

But under `release profile` everything works fine.

Rust latest nightly on x86-64-apple-darwin.

**Comment by workingjubilee** [comment]
This lacks a CLI command to reproduce it with so I am going to close it.
