### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by Micas427** [rust-lang/rust#121947]
Bug report as requested in the error message.  

The compiler unexpectedly panicked while building timescaledb-toolkit on a Raspberry Pi, when running .rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/cargo" "build" "--release" "--features" "pg16" "--no-default-features" "--message-format=json-render-diagnostics"   

Full error report follows.

```
thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:73:26:
index out of bounds: the len is 64227 but the index is 71500867
stack backtrace:
   0:       0x7fb3032164 - std::backtrace_rs::backtrace::libunwind::trace::hee9690ac22774636
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src                                                                                                                        /backtrace/libunwind.rs:104:5
   1:       0x7fb3032164 - std::backtrace_rs::backtrace::trace_unsynchronized::ha30111b5438e6e61
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src                                                                                                                        /backtrace/mod.rs:66:5
   2:       0x7fb3032164 - std::sys_common::backtrace::_print_fmt::hc2516686a74b2a42
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrac                                                                                                                        e.rs:68:5
   3:       0x7fb3032164 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8984c8                                                                                                                        8846573cbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrac                                                                                                                        e.rs:44:22
   4:       0x7fb307be4c - core::fmt::rt::Argument::fmt::h071bdaa21123c9ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:       0x7fb307be4c - core::fmt::write::h3f4921a7ddfa57a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:       0x7fb30280a8 - std::io::Write::write_fmt::h0923e211983fe028
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:       0x7fb3031f90 - std::sys_common::backtrace::_print::h39d471a7e51d9dbd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrac                                                                                                                        e.rs:47:5
   8:       0x7fb3031f90 - std::sys_common::backtrace::print::h6306cb106d0c42e1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrac                                                                                                                        e.rs:34:9
   9:       0x7fb30349fc - std::panicking::default_hook::{{closure}}::h2a94c4f92161a016
  10:       0x7fb3034730 - std::panicking::default_hook::hd3c29c68b55e9f50
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:       0x7fb3b93580 - <alloc[62da33d4e78b0495]::boxed::Box<rustc_driver_impl[a38c2ed279593b55]::install_ice_hook                                                                                                                        ::{closure#0}> as core[7817230e571a6e0a]::ops::function::Fn<(&dyn for<'a, 'b> core[7817230e571a6e0a]::ops::function::                                                                                                                        Fn<(&'a core[7817230e571a6e0a]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[7817230e571a6e0a]::marker::Sy                                                                                                                        nc + core[7817230e571a6e0a]::marker::Send, &core[7817230e571a6e0a]::panic::panic_info::PanicInfo)>>::call
  12:       0x7fb30350ec - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h44043f3b7ad3e11e
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
  13:       0x7fb30350ec - std::panicking::rust_panic_with_hook::ha00bbb72a4f1b899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
  14:       0x7fb3034e6c - std::panicking::begin_panic_handler::{{closure}}::had2c64361be4b07b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  15:       0x7fb3032634 - std::sys_common::backtrace::__rust_end_short_backtrace::hf92a1e94dde0ed69
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrac                                                                                                                        e.rs:171:18
  16:       0x7fb3034c0c - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  17:       0x7fb30004d4 - core::panicking::panic_fmt::h815b849997a1324d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  18:       0x7fb300065c - core::panicking::panic_bounds_check::ha2c3f34711e33370
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:208:5
  19:       0x7fb8b78a70 - <rustc_hir[30b3405e224cbf8e]::definitions::Definitions>::def_path
  20:       0x7fb88707cc - <rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt>::def_path
  21:       0x7fb8870dcc - <rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt>::def_path_debug_str
  22:       0x7fb3d2f938 - rustc_interface[e73d2341e1cff0ed]::callbacks::def_id_debug
  23:       0x7fb307be4c - core::fmt::rt::Argument::fmt::h071bdaa21123c9ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
  24:       0x7fb307be4c - core::fmt::write::h3f4921a7ddfa57a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
  25:       0x7fb307be4c - core::fmt::rt::Argument::fmt::h071bdaa21123c9ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
  26:       0x7fb307be4c - core::fmt::write::h3f4921a7ddfa57a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
  27:       0x7fb306d028 - <&mut W as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt::h06024a976dccd0fb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:211:17
  28:       0x7fb306d028 - core::fmt::Write::write_fmt::hd0ff53ecbba2d81a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:215:14
  29:       0x7fb306d028 - alloc::fmt::format::format_inner::h07e6a5e06a0ce2ab
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/fmt.rs:612:16
  30:       0x7fb8994f14 - rustc_middle[eb966daf5a04f996]::util::bug::opt_span_bug_fmt::<rustc_span[6994779df6725c3d]                                                                                                                        ::span_encoding::Span>::{closure#0}
  31:       0x7fb898b210 - rustc_middle[eb966daf5a04f996]::ty::context::tls::with_opt::<rustc_middle[eb966daf5a04f996                                                                                                                        ]::util::bug::opt_span_bug_fmt<rustc_span[6994779df6725c3d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  32:       0x7fb898b1e0 - rustc_middle[eb966daf5a04f996]::ty::context::tls::with_context_opt::<rustc_middle[eb966daf                                                                                                                        5a04f996]::ty::context::tls::with_opt<rustc_middle[eb966daf5a04f996]::util::bug::opt_span_bug_fmt<rustc_span[6994779d                                                                                                                        f6725c3d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  33:       0x7fb3aa19c4 - rustc_middle[eb966daf5a04f996]::util::bug::bug_fmt
  34:       0x7fb88293bc - <<rustc_middle[eb966daf5a04f996]::query::Providers as core[7817230e571a6e0a]::default::Def                                                                                                                        ault>::default::{closure#132} as core[7817230e571a6e0a]::ops::function::FnOnce<(rustc_middle[eb966daf5a04f996]::ty::c                                                                                                                        ontext::TyCtxt, rustc_span[6994779df6725c3d]::def_id::LocalDefId)>>::call_once
  35:       0x7fb7a77cd0 - rustc_query_impl[d9f355b74a2388ce]::plumbing::__rust_begin_short_backtrace::<rustc_query_i                                                                                                                        mpl[d9f355b74a2388ce]::query_impl::def_kind::dynamic_query::{closure#2}::{closure#0}, rustc_middle[eb966daf5a04f996]:                                                                                                                        :query::erase::Erased<[u8; 2usize]>>
  36:       0x7fb7bfdd0c - <rustc_query_impl[d9f355b74a2388ce]::query_impl::def_kind::dynamic_query::{closure#2} as c                                                                                                                        ore[7817230e571a6e0a]::ops::function::FnOnce<(rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt, rustc_span[6994779                                                                                                                        df6725c3d]::def_id::DefId)>>::call_once
  37:       0x7fb7c89000 - rustc_query_system[25eac70257f58599]::query::plumbing::try_execute_query::<rustc_query_imp                                                                                                                        l[d9f355b74a2388ce]::DynamicConfig<rustc_query_system[25eac70257f58599]::query::caches::DefaultCache<rustc_span[69947                                                                                                                        79df6725c3d]::def_id::DefId, rustc_middle[eb966daf5a04f996]::query::erase::Erased<[u8; 2usize]>>, false, false, false                                                                                                                        >, rustc_query_impl[d9f355b74a2388ce]::plumbing::QueryCtxt, false>
  38:       0x7fb7ad82fc - rustc_query_impl[d9f355b74a2388ce]::query_impl::def_kind::get_query_non_incr::__rust_end_s                                                                                                                        hort_backtrace
  39:       0x7fb887ac18 - rustc_middle[eb966daf5a04f996]::query::plumbing::query_get_at::<rustc_query_system[25eac70                                                                                                                        257f58599]::query::caches::DefaultCache<rustc_span[6994779df6725c3d]::def_id::DefId, rustc_middle[eb966daf5a04f996]::                                                                                                                        query::erase::Erased<[u8; 2usize]>>>
  40:       0x7fb88789d0 - <rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt>::opt_rpitit_info
  41:       0x7fb88774e4 - <rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt>::is_impl_trait_in_trait
  42:       0x7fb75f5c84 - rustc_passes[2bd0e3f331e3381f]::dead::live_symbols_and_ignored_derived_traits
  43:       0x7fb7a7786c - rustc_query_impl[d9f355b74a2388ce]::plumbing::__rust_begin_short_backtrace::<rustc_query_i                                                                                                                        mpl[d9f355b74a2388ce]::query_impl::live_symbols_and_ignored_derived_traits::dynamic_query::{closure#2}::{closure#0},                                                                                                                         rustc_middle[eb966daf5a04f996]::query::erase::Erased<[u8; 8usize]>>
  44:       0x7fb7c3f5f4 - <rustc_query_impl[d9f355b74a2388ce]::query_impl::live_symbols_and_ignored_derived_traits::                                                                                                                        dynamic_query::{closure#2} as core[7817230e571a6e0a]::ops::function::FnOnce<(rustc_middle[eb966daf5a04f996]::ty::cont                                                                                                                        ext::TyCtxt, ())>>::call_once
  45:       0x7fb7c6217c - rustc_query_system[25eac70257f58599]::query::plumbing::try_execute_query::<rustc_query_imp                                                                                                                        l[d9f355b74a2388ce]::DynamicConfig<rustc_query_system[25eac70257f58599]::query::caches::SingleCache<rustc_middle[eb96                                                                                                                        6daf5a04f996]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d9f355b74a2388ce]::plumbin                                                                                                                        g::QueryCtxt, false>
  46:       0x7fb7ad27a4 - rustc_query_impl[d9f355b74a2388ce]::query_impl::live_symbols_and_ignored_derived_traits::g                                                                                                                        et_query_non_incr::__rust_end_short_backtrace
  47:       0x7fb75f76b4 - rustc_passes[2bd0e3f331e3381f]::dead::check_mod_deathness
  48:       0x7fb7a7568c - rustc_query_impl[d9f355b74a2388ce]::plumbing::__rust_begin_short_backtrace::<rustc_query_i                                                                                                                        mpl[d9f355b74a2388ce]::query_impl::check_mod_deathness::dynamic_query::{closure#2}::{closure#0}, rustc_middle[eb966da                                                                                                                        f5a04f996]::query::erase::Erased<[u8; 0usize]>>
  49:       0x7fb7bfbc04 - <rustc_query_impl[d9f355b74a2388ce]::query_impl::check_mod_deathness::dynamic_query::{clos                                                                                                                        ure#2} as core[7817230e571a6e0a]::ops::function::FnOnce<(rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt, rustc_s                                                                                                                        pan[6994779df6725c3d]::def_id::LocalModDefId)>>::call_once
  50:       0x7fb7c7e3c4 - rustc_query_system[25eac70257f58599]::query::plumbing::try_execute_query::<rustc_query_imp                                                                                                                        l[d9f355b74a2388ce]::DynamicConfig<rustc_query_system[25eac70257f58599]::query::caches::DefaultCache<rustc_span[69947                                                                                                                        79df6725c3d]::def_id::LocalModDefId, rustc_middle[eb966daf5a04f996]::query::erase::Erased<[u8; 0usize]>>, false, fals                                                                                                                        e, false>, rustc_query_impl[d9f355b74a2388ce]::plumbing::QueryCtxt, false>
  51:       0x7fb7ad2a08 - rustc_query_impl[d9f355b74a2388ce]::query_impl::check_mod_deathness::get_query_non_incr::_                                                                                                                        _rust_end_short_backtrace
  52:       0x7fb3d2ad68 - std[b7bdf322e3c58453]::panicking::try::<(), core[7817230e571a6e0a]::panic::unwind_safe::As                                                                                                                        sertUnwindSafe<rustc_data_structures[a56d6f77dfab58ce]::sync::parallel::disabled::par_for_each_in<&[rustc_hir[30b3405                                                                                                                        e224cbf8e]::hir_id::OwnerId], <rustc_middle[eb966daf5a04f996]::hir::map::Map>::par_for_each_module<rustc_interface[e7                                                                                                                        3d2341e1cff0ed]::passes::analysis::{closure#6}::{closure#1}::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{cl                                                                                                                        osure#0}>::{closure#0}::{closure#0}::{closure#0}>>
  53:       0x7fb3d8015c - rustc_data_structures[a56d6f77dfab58ce]::sync::parallel::disabled::par_for_each_in::<&[rus                                                                                                                        tc_hir[30b3405e224cbf8e]::hir_id::OwnerId], <rustc_middle[eb966daf5a04f996]::hir::map::Map>::par_for_each_module<rust                                                                                                                        c_interface[e73d2341e1cff0ed]::passes::analysis::{closure#6}::{closure#1}::{closure#0}::{closure#0}::{closure#1}::{cl                                                                                                                        osure#0}>::{closure#0}>
  54:       0x7fb3d2b9fc - std[b7bdf322e3c58453]::panicking::try::<(), core[7817230e571a6e0a]::panic::unwind_safe::As                                                                                                                        sertUnwindSafe<rustc_interface[e73d2341e1cff0ed]::passes::analysis::{closure#6}::{closure#1}::{closure#0}::{closure#0                                                                                                                        }::{closure#1}>>
  55:       0x7fb3d7ade0 - <rustc_data_structures[a56d6f77dfab58ce]::sync::parallel::ParallelGuard>::run::<(), rustc_                                                                                                                        interface[e73d2341e1cff0ed]::passes::analysis::{closure#6}::{closure#1}::{closure#0}::{closure#0}::{closure#1}>
  56:       0x7fb3d2bd9c - std[b7bdf322e3c58453]::panicking::try::<(), core[7817230e571a6e0a]::panic::unwind_safe::As                                                                                                                        sertUnwindSafe<rustc_interface[e73d2341e1cff0ed]::passes::analysis::{closure#6}::{closure#1}::{closure#0}>>
  57:       0x7fb3d7b83c - <rustc_data_structures[a56d6f77dfab58ce]::sync::parallel::ParallelGuard>::run::<(), rustc_                                                                                                                        interface[e73d2341e1cff0ed]::passes::analysis::{closure#6}::{closure#1}::{closure#0}>
  58:       0x7fb3d432a8 - <rustc_session[bc960a95d572e3a4]::session::Session>::time::<(), rustc_interface[e73d2341e1                                                                                                                        cff0ed]::passes::analysis::{closure#6}>
  59:       0x7fb3d297f4 - rustc_interface[e73d2341e1cff0ed]::passes::analysis
  60:       0x7fb7a77ca0 - rustc_query_impl[d9f355b74a2388ce]::plumbing::__rust_begin_short_backtrace::<rustc_query_i                                                                                                                        mpl[d9f355b74a2388ce]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[eb966daf5a04f996]:                                                                                                                        :query::erase::Erased<[u8; 1usize]>>
  61:       0x7fb7c17f24 - <rustc_query_impl[d9f355b74a2388ce]::query_impl::analysis::dynamic_query::{closure#2} as c                                                                                                                        ore[7817230e571a6e0a]::ops::function::FnOnce<(rustc_middle[eb966daf5a04f996]::ty::context::TyCtxt, ())>>::call_once
  62:       0x7fb7c5fb0c - rustc_query_system[25eac70257f58599]::query::plumbing::try_execute_query::<rustc_query_imp                                                                                                                        l[d9f355b74a2388ce]::DynamicConfig<rustc_query_system[25eac70257f58599]::query::caches::SingleCache<rustc_middle[eb96                                                                                                                        6daf5a04f996]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[d9f355b74a2388ce]::plumbin                                                                                                                        g::QueryCtxt, false>
  63:       0x7fb7ac45d8 - rustc_query_impl[d9f355b74a2388ce]::query_impl::analysis::get_query_non_incr::__rust_end_s                                                                                                                        hort_backtrace
  64:       0x7fb3ba8470 - <rustc_middle[eb966daf5a04f996]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[a38c2                                                                                                                        ed279593b55]::run_compiler::{closure#0}::{closure#0}::{closure#3}, core[7817230e571a6e0a]::result::Result<(), rustc_s                                                                                                                        pan[6994779df6725c3d]::ErrorGuaranteed>>
  65:       0x7fb3bbf1d4 - <rustc_interface[e73d2341e1cff0ed]::interface::Compiler>::enter::<rustc_driver_impl[a38c2e                                                                                                                        d279593b55]::run_compiler::{closure#0}::{closure#0}, core[7817230e571a6e0a]::result::Result<core[7817230e571a6e0a]::o                                                                                                                        ption::Option<rustc_interface[e73d2341e1cff0ed]::queries::Linker>, rustc_span[6994779df6725c3d]::ErrorGuaranteed>>
  66:       0x7fb3baee20 - rustc_span[6994779df6725c3d]::create_session_globals_then::<core[7817230e571a6e0a]::result                                                                                                                        ::Result<(), rustc_span[6994779df6725c3d]::ErrorGuaranteed>, rustc_interface[e73d2341e1cff0ed]::interface::run_compil                                                                                                                        er<core[7817230e571a6e0a]::result::Result<(), rustc_span[6994779df6725c3d]::ErrorGuaranteed>, rustc_driver_impl[a38c2                                                                                                                        ed279593b55]::run_compiler::{closure#0}>::{closure#0}>
  67:       0x7fb3bdb1d0 - std[b7bdf322e3c58453]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interfa                                                                                                                        ce[e73d2341e1cff0ed]::util::run_in_thread_with_globals<rustc_interface[e73d2341e1cff0ed]::interface::run_compiler<cor                                                                                                                        e[7817230e571a6e0a]::result::Result<(), rustc_span[6994779df6725c3d]::ErrorGuaranteed>, rustc_driver_impl[a38c2ed2795                                                                                                                        93b55]::run_compiler::{closure#0}>::{closure#0}, core[7817230e571a6e0a]::result::Result<(), rustc_span[6994779df6725c                                                                                                                        3d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7817230e571a6e0a]::result::Result<(), rustc_span[6994779df6725                                                                                                                        c3d]::ErrorGuaranteed>>
  68:       0x7fb3bb8c70 - <<std[b7bdf322e3c58453]::thread::Builder>::spawn_unchecked_<rustc_interface[e73d2341e1cff0                                                                                                                        ed]::util::run_in_thread_with_globals<rustc_interface[e73d2341e1cff0ed]::interface::run_compiler<core[7817230e571a6e0                                                                                                                        a]::result::Result<(), rustc_span[6994779df6725c3d]::ErrorGuaranteed>, rustc_driver_impl[a38c2ed279593b55]::run_compi                                                                                                                        ler::{closure#0}>::{closure#0}, core[7817230e571a6e0a]::result::Result<(), rustc_span[6994779df6725c3d]::ErrorGuarant                                                                                                                        eed>>::{closure#0}::{closure#0}, core[7817230e571a6e0a]::result::Result<(), rustc_span[6994779df6725c3d]::ErrorGuaran                                                                                                                        teed>>::{closure#1} as core[7817230e571a6e0a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  69:       0x7fb303e2c0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he98dd9388c7047c                                                                                                                        2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  70:       0x7fb303e2c0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h103af4b9c154ce5                                                                                                                        9
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  71:       0x7fb303e2c0 - std::sys::unix::thread::Thread::new::thread_start::hc59882c1f8885c71
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:                                                                                                                        108:17
  72:       0x7fb2e8ee58 - start_thread
                               at ./nptl/pthread_create.c:442:8
  73:       0x7fb2ef7f9c - thread_start
                               at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:79
  74:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compi                                                                                                                        ler&template=ice.md

note: rustc 1.76.0 (07dca489a 2024-02-04) running on aarch64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 -C link-                                                                                                                        args=-Wl,-undefined,dynamic_lookup

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
error: could not compile `pgrx-pg-sys` (lib)

Caused by:
  process didn't exit successfully: `/home/mike/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate                                                                                                                        -name pgrx_pg_sys --edition=2021 /home/mike/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.10.2/s                                                                                                                        rc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=117 --crat                                                                                                                        e-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 --cfg                                                                                                                         'feature="cshim"' --cfg 'feature="default"' --cfg 'feature="pg16"' -C metadata=2801ca3447f91d47 -C extra-filename=-28                                                                                                                        01ca3447f91d47 --out-dir /home/mike/src/timescaledb-toolkit/target/release/deps -L dependency=/home/mike/src/timescal                                                                                                                        edb-toolkit/target/release/deps --extern libc=/home/mike/src/timescaledb-toolkit/target/release/deps/liblibc-7e7e63e4                                                                                                                        c974b3ac.rmeta --extern memoffset=/home/mike/src/timescaledb-toolkit/target/release/deps/libmemoffset-5a8120188fc65ae                                                                                                                        c.rmeta --extern pgrx_macros=/home/mike/src/timescaledb-toolkit/target/release/deps/libpgrx_macros-d45679cc02b9da4d.s                                                                                                                        o --extern pgrx_sql_entity_graph=/home/mike/src/timescaledb-toolkit/target/release/deps/libpgrx_sql_entity_graph-ded0                                                                                                                        1aae5a762b0c.rmeta --extern serde=/home/mike/src/timescaledb-toolkit/target/release/deps/libserde-37458a0df4415895.rm                                                                                                                        eta --extern sptr=/home/mike/src/timescaledb-toolkit/target/release/deps/libsptr-61e7a3ffe2f22f63.rmeta --cap-lints a                                                                                                                        llow -C link-args=-Wl,-undefined,dynamic_lookup -L /home/mike/src/timescaledb-toolkit/target/release/build/pgrx-pg-sy                                                                                                                        s-c5b948b50cbb1a2d/out/cshim -l static=pgrx-cshim-16` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
```

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
