### ISSUE TITLE
Internal Error: Unreachable code, panick

### ISSUE THREAD

**Issue by ready-research** [rust-lang/rust#122436]
### Code

```Rust
pub type _Unwind_Exception_Cleanup_Fn =
    Option<extern "C" fn(unwind_code: _Unwind_Reason_Code, exception: *mut _Unwind_Exception)>;

https://github.com/rust-lang/rust/blob/9ce37dc7290e60bd0dfc7a5d4fcdbbd836f989f0/library/unwind/src/libunwind.rs#L93C1-L94C96
```

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### Error output

```
internal error: entered unreachable code
```
**Note: Added stack backtrace below**

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at checker/src/utils.rs:452:13:
internal error: entered unreachable code
stack backtrace:
   0:     0x7f5f248b0efc - std::backtrace_rs::backtrace::libunwind::trace::h094c2eb17225f35e
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5f248b0efc - std::backtrace_rs::backtrace::trace_unsynchronized::h615449becf5ed526
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5f248b0efc - std::sys_common::backtrace::_print_fmt::h4f6404afc9c28fa2
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f5f248b0efc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec8e2f82a9267356
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5f2491715c - core::fmt::rt::Argument::fmt::hc22bff1f3c8d5515
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/core/src/fmt/rt.rs:138:9
   5:     0x7f5f2491715c - core::fmt::write::h695f0d13ee2b63c0
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f5f248a393e - std::io::Write::write_fmt::h4c9769eac3690b0b
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/io/mod.rs:1714:15
   7:     0x7f5f248b0ce4 - std::sys_common::backtrace::_print::h1ecde903242aebf4
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5f248b0ce4 - std::sys_common::backtrace::print::h5bed2e94889011f9
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f5f248b3dda - std::panicking::panic_hook_with_disk_dump::{{closure}}::h9dff830c2c2c9e7d
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/panicking.rs:280:22
  10:     0x7f5f248b3a98 - std::panicking::panic_hook_with_disk_dump::hcd574b7c614f8fd7
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/panicking.rs:307:9
  11:     0x7f5f27a78899 - <rustc_driver_impl[4a48db23f7fef241]::install_ice_hook::{closure#0} as core[6b93bd2b6a9e1e0b]::ops::function::FnOnce<(&core[6b93bd2b6a9e1e0b]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7f5f248b4693 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h61a031d2161fa98e
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/alloc/src/boxed.rs:2021:9
  13:     0x7f5f248b4693 - std::panicking::rust_panic_with_hook::h3dc2c3e3f18f2734
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/panicking.rs:757:13
  14:     0x7f5f248b43c6 - std::panicking::begin_panic_handler::{{closure}}::hfec52c7accc59e93
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/panicking.rs:623:13
  15:     0x7f5f248b1426 - std::sys_common::backtrace::__rust_end_short_backtrace::h91bb17702521ee3a
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7f5f248b4152 - rust_begin_unwind
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/panicking.rs:619:5
  17:     0x7f5f24913505 - core::panicking::panic_fmt::hff1a5640486791f2
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/core/src/panicking.rs:72:14
  18:     0x7f5f249135a3 - core::panicking::panic::h1c6e717c03045a5e
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/core/src/panicking.rs:127:5
  19:     0x7f5f28e2db17 - mirai::utils::def_id_as_qualified_name_str::hd564c70089e98927
                               at /checker/src/utils.rs:452:13
  20:     0x7f5f28d68afb - mirai::callbacks::MiraiCallbacks::analyze_with_mirai::{{closure}}::h21a684309594e94c
                               at /checker/src/callbacks.rs:138:28
  21:     0x7f5f28d68afb - mirai::callbacks::MiraiCallbacks::analyze_with_mirai::h239fdfaf3650890e
                               at /checker/src/callbacks.rs:131:5
  22:     0x7f5f28d68651 - <mirai::callbacks::MiraiCallbacks as rustc_driver_impl::Callbacks>::after_analysis::{{closure}}::{{closure}}::h5cb33de0109802a8
                               at /checker/src/callbacks.rs:118:26
  23:     0x7f5f28d68651 - rustc_middle::ty::context::GlobalCtxt::enter::{{closure}}::h33f357414c169b8a
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/compiler/rustc_middle/src/ty/context.rs:595:37
  24:     0x7f5f28d68651 - rustc_middle::ty::context::tls::enter_context::{{closure}}::h30321079247bfda6
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/compiler/rustc_middle/src/ty/context/tls.rs:82:9
  25:     0x7f5f28d68651 - std::thread::local::LocalKey<T>::try_with::h4de1cea27c0b9f30
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/thread/local.rs:270:16
  26:     0x7f5f28d68651 - std::thread::local::LocalKey<T>::with::h22fe88bc3ebb25b4
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/thread/local.rs:246:9
  27:     0x7f5f28d68651 - rustc_middle::ty::context::tls::enter_context::h06ed8e3de39d231b
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/compiler/rustc_middle/src/ty/context/tls.rs:79:9
  28:     0x7f5f28d68651 - rustc_middle::ty::context::GlobalCtxt::enter::hb19829662c60c5c3
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/compiler/rustc_middle/src/ty/context.rs:595:9
  29:     0x7f5f28d68651 - rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>::enter::h18a971047614ece6
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/compiler/rustc_interface/src/queries.rs:71:9
  30:     0x7f5f28d68651 - <mirai::callbacks::MiraiCallbacks as rustc_driver_impl::Callbacks>::after_analysis::{{closure}}::h3f0a8c551db226d8
                               at /checker/src/callbacks.rs:115:9
  31:     0x7f5f28d68651 - <mirai::callbacks::MiraiCallbacks as rustc_driver_impl::Callbacks>::after_analysis::h6b7fe3fcc64b3a58
                               at /checker/src/callbacks.rs:98:5
  32:     0x7f5f26fbf84d - <rustc_interface[ff58ab769e259856]::interface::Compiler>::enter::<rustc_driver_impl[4a48db23f7fef241]::run_compiler::{closure#1}::{closure#2}, core[6b93bd2b6a9e1e0b]::result::Result<core[6b93bd2b6a9e1e0b]::option::Option<rustc_interface[ff58ab769e259856]::queries::Linker>, rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>>
  33:     0x7f5f26fb8ae8 - std[3c984aa0e273a99e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ff58ab769e259856]::util::run_in_thread_with_globals<rustc_interface[ff58ab769e259856]::interface::run_compiler<core[6b93bd2b6a9e1e0b]::result::Result<(), rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>, rustc_driver_impl[4a48db23f7fef241]::run_compiler::{closure#1}>::{closure#0}, core[6b93bd2b6a9e1e0b]::result::Result<(), rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b93bd2b6a9e1e0b]::result::Result<(), rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>>
  34:     0x7f5f26fb823e - <<std[3c984aa0e273a99e]::thread::Builder>::spawn_unchecked_<rustc_interface[ff58ab769e259856]::util::run_in_thread_with_globals<rustc_interface[ff58ab769e259856]::interface::run_compiler<core[6b93bd2b6a9e1e0b]::result::Result<(), rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>, rustc_driver_impl[4a48db23f7fef241]::run_compiler::{closure#1}>::{closure#0}, core[6b93bd2b6a9e1e0b]::result::Result<(), rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[6b93bd2b6a9e1e0b]::result::Result<(), rustc_span[4bc5c3472ac21a7b]::ErrorGuaranteed>>::{closure#1} as core[6b93bd2b6a9e1e0b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7f5f248bf075 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he40f230475481d5a
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/alloc/src/boxed.rs:2007:9
  36:     0x7f5f248bf075 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd8d1d2a8c2bb2577
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/alloc/src/boxed.rs:2007:9
  37:     0x7f5f248bf075 - std::sys::unix::thread::Thread::new::thread_start::h2fc0621e8c4d6f11
                               at /rustc/8ed4537d7c238eb77509d82445cf1cb861a3b5ff/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7f5f242d4ac3 - <unknown>
  39:     0x7f5f24365a04 - __clone
  40:                0x0 - <unknown>


query stack during panic:
end of query stack

```

</p>
</details>

**Comment by compiler-errors** [comment]
This is not a rust bug, but a mirai bug.

https://github.com/facebookexperimental/MIRAI/blob/a94a8c77a453e1d2365b39aa638a4f5e6b1d4dc3/checker/src/utils.rs#L452
