### ISSUE TITLE
ICE: `nonscalar layout for layout_scalar_valid_range type: Layout`

### ISSUE THREAD

**Issue by cushionbadak** [rust-lang/rust#122681]
### Code

(reduced)

```Rust
#[rustc_layout_scalar_valid_range_start(1)]
struct UnitStruct;

#[derive(Default)]
enum SomeEnum {
    #[default]
    Unit,
    Tuple(UnitStruct),
}
```

(original) - files at `rust-clippy's tests/ui` are used as fuzzer's seed files.

<details><summary><strong>Original Code</strong></summary>
<p>

```
#![allow(unused)]
#![warn(clippy::default_constructed_unit_structs)]
use std::marker::PhantomData;

#[rustc_layout_scalar_valid_range_start(1)]
struct UnitStruct;

impl E {
    fn new() -> Self {
        //should lint
        Self::default()
    }
}

#[derive(Default)]
struct TupleStruct(usize);

impl TupleStruct {
    fn new() -> Self {
        // should not lint
        Self(Default::default())
    }
}

// no lint for derived impl
#[derive(Default)]
struct NormalStruct {
    inner: PhantomData<usize>,
}

struct NonDefaultStruct;

impl NonDefaultStruct {
    fn default() -> Self {
        Self
    }
}

#[derive(Default)]
enum SomeEnum {
    #[default]
    Unit,
    Tuple(UnitStruct),
    Struct {
        inner: usize,
    },
}

impl NormalStruct {
    fn new() -> Self {
        // should lint
        Self {
            inner: PhantomData::default(),
        }
    }

    fn new2() -> Self {
        // ok, don't lint on `cfg` invocation
        Self {
            inner: Default::default(Ord::cmp(self, other)),
        }
    }
}

#[derive(Default)]
struct GenericStruct<'q> {
    t: T,
}

impl<T: Default> GenericStruct<T> {
    fn new() -> Self {
        // should not lint
        Self { t: T::default() }
    }

    fn new2() -> Self {
        // should not lint
        Self {
            t: Default::default(),
        }
    }
}

struct FakeDefault;
impl FakeDefault {
    fn default() -> Self {
        Self
    }
}

impl Default for FakeDefault {
    fn default() -> Self {
        Self
    }
}

#[derive(Default)]
struct EmptyStruct {}

#[derive(Default)]
#[non_exhaustive]
struct NonExhaustiveStruct;

mod issue_10755 {
    struct Sqlite {}

    trait HasArguments<'q> {
        type Arguments;
    }

    impl<'q> HasArguments<'q> for Sqlite {
        type Arguments = std::marker::PhantomData<&'q ()>;
    }

    type SqliteArguments<'q> = <Sqlite as HasArguments<'q>>::Arguments;

    fn foo() {
        // should not lint
        // type alias cannot be used as a constructor
        let _ = <Sqlite as HasArguments>::Arguments::default();

        let _ = NonExhaustiveStruct::default();
    }
}

fn main() {
    // should lint
    let _ = PhantomData::<usize>::default();
    let _: PhantomData<i32> = PhantomData::default();
    let _: PhantomData<i32> = std::marker::PhantomData::default();
    let _ = UnitStruct::default();

    // should not lint
    let _ = TupleStruct::default();
    let _ = NormalStruct::default();
    let _ = NonExhaustiveStruct::default();
    let _ = SomeEnum::default();
    let _ = NonDefaultStruct::default();
    let _ = EmptyStruct::default();
    let _ = FakeDefault::default();
    let _ = <FakeDefault as Default>::default();

    macro_rules! in_macro {
        ($i:ident) => {{
            let _ = UnitStruct::default();
            let _ = $i::default();
        }};
    }

    in_macro!(UnitStruct);

    macro_rules! struct_from_macro {
        () => {
            UnitStruct
        };
    }

    let _ = <struct_from_macro!()>::default();
}
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (eb45c8444 2024-03-17)
binary: rustc
commit-hash: eb45c844407968ea54df0d9870ebce9e3235b706
commit-date: 2024-03-17
host: x86_64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### Command
`rustc`

### Error output

```
error[E0658]: the `#[rustc_layout_scalar_valid_range_start]` attribute is just used to enable niche optimizations in libcore and libstd and will never be stable
 --> reduced_ed26c2ad02bf2ae9.rs:1:1
  |
1 | #[rustc_layout_scalar_valid_range_start(1)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(rustc_attrs)]` to the crate attributes to enable
  = note: this compiler was built on 2024-03-17; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `reduced_ed26c2ad02bf2ae9`
 --> reduced_ed26c2ad02bf2ae9.rs:9:2
  |
9 | }
  |  ^ consider adding a `main` function to `reduced_ed26c2ad02bf2ae9.rs`

thread 'rustc' panicked at /rustc/eb45c844407968ea54df0d9870ebce9e3235b706/compiler/rustc_abi/src/layout.rs:432:14:
nonscalar layout for layout_scalar_valid_range type: Layout {
    size: Size(0 bytes),
    align: AbiAndPrefAlign {
        abi: Align(1 bytes),
        pref: Align(8 bytes),
    },
    abi: Aggregate {
        sized: true,
    },
    fields: Arbitrary {
        offsets: [],
        memory_index: [],
    },
    largest_niche: None,
    variants: Single {
        index: 0,
    },
    max_repr_align: None,
    unadjusted_abi_align: Align(1 bytes),
}
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x10996bb27 - std::backtrace::Backtrace::create::hb0879181205ccb51
   1:        0x10996ba75 - std::backtrace::Backtrace::force_capture::h0d9ef6af34e67d10
   2:        0x1124a6e35 - std[d2f59205c3cc5fff]::panicking::update_hook::<alloc[2e597f350743db35]::boxed::Box<rustc_driver_impl[2c62cc41b08aa508]::install_ice_hook::{closure#0}>>::{closure#0}
   3:        0x109985a4b - std::panicking::rust_panic_with_hook::h5bbcc28711362199
   4:        0x109985374 - std::panicking::begin_panic_handler::{{closure}}::h3ebd450d3478f40f
   5:        0x1099825d9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1e24eecac8f71445
   6:        0x1099850a6 - _rust_begin_unwind
   7:        0x1099ea8c5 - core::panicking::panic_fmt::hb6314c522854994f
   8:        0x113f0d155 - <rustc_middle[a1758cd39e1aaae6]::ty::layout::LayoutCx<rustc_middle[a1758cd39e1aaae6]::ty::context::TyCtxt> as rustc_abi[d0306d2028f0405f]::layout::LayoutCalculator>::layout_of_struct_or_enum::<rustc_target[1f27652200010ea4]::abi::FieldIdx, rustc_target[1f27652200010ea4]::abi::VariantIdx, rustc_target[1f27652200010ea4]::abi::Layout, rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached::{closure#11}, core[f9fdfc6ae2c20ff7]::iter::adapters::flatten::Flatten<core[f9fdfc6ae2c20ff7]::option::IntoIter<core[f9fdfc6ae2c20ff7]::iter::adapters::map::Map<core[f9fdfc6ae2c20ff7]::iter::adapters::map::Map<core[f9fdfc6ae2c20ff7]::iter::adapters::map::Map<core[f9fdfc6ae2c20ff7]::iter::adapters::enumerate::Enumerate<core[f9fdfc6ae2c20ff7]::slice::iter::Iter<rustc_middle[a1758cd39e1aaae6]::ty::VariantDef>>, <rustc_index[3bab5bde94c9a092]::slice::IndexSlice<rustc_target[1f27652200010ea4]::abi::VariantIdx, rustc_middle[a1758cd39e1aaae6]::ty::VariantDef>>::iter_enumerated::{closure#0}>, <rustc_middle[a1758cd39e1aaae6]::ty::adt::AdtDef>::discriminants::{closure#0}>, rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached::{closure#12}::{closure#0}::{closure#0}>>>>
   9:        0x113f568d1 - rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached
  10:        0x113f690b7 - rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of
  11:        0x1138b8076 - rustc_query_impl[c49845d791f7123d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c49845d791f7123d]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 16usize]>>
  12:        0x11388b03e - <rustc_query_impl[c49845d791f7123d]::query_impl::layout_of::dynamic_query::{closure#2} as core[f9fdfc6ae2c20ff7]::ops::function::FnOnce<(rustc_middle[a1758cd39e1aaae6]::ty::context::TyCtxt, rustc_middle[a1758cd39e1aaae6]::ty::ParamEnvAnd<rustc_middle[a1758cd39e1aaae6]::ty::Ty>)>>::call_once
  13:        0x1136a7444 - rustc_query_system[560604c93bb76bb8]::query::plumbing::try_execute_query::<rustc_query_impl[c49845d791f7123d]::DynamicConfig<rustc_query_system[560604c93bb76bb8]::query::caches::DefaultCache<rustc_middle[a1758cd39e1aaae6]::ty::ParamEnvAnd<rustc_middle[a1758cd39e1aaae6]::ty::Ty>, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[c49845d791f7123d]::plumbing::QueryCtxt, false>
  14:        0x1138f3664 - rustc_query_impl[c49845d791f7123d]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  15:        0x113eede09 - rustc_middle[a1758cd39e1aaae6]::query::plumbing::query_get_at::<rustc_query_system[560604c93bb76bb8]::query::caches::DefaultCache<rustc_middle[a1758cd39e1aaae6]::ty::ParamEnvAnd<rustc_middle[a1758cd39e1aaae6]::ty::Ty>, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 16usize]>>>
  16:        0x113f19ee9 - <core[f9fdfc6ae2c20ff7]::iter::adapters::GenericShunt<core[f9fdfc6ae2c20ff7]::iter::adapters::by_ref_sized::ByRefSized<core[f9fdfc6ae2c20ff7]::iter::adapters::map::Map<core[f9fdfc6ae2c20ff7]::slice::iter::Iter<rustc_middle[a1758cd39e1aaae6]::ty::VariantDef>, rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached::{closure#9}>>, core[f9fdfc6ae2c20ff7]::result::Result<core[f9fdfc6ae2c20ff7]::convert::Infallible, &rustc_middle[a1758cd39e1aaae6]::ty::layout::LayoutError>> as core[f9fdfc6ae2c20ff7]::iter::traits::iterator::Iterator>::next
  17:        0x113eee88e - core[f9fdfc6ae2c20ff7]::iter::adapters::try_process::<core[f9fdfc6ae2c20ff7]::iter::adapters::by_ref_sized::ByRefSized<core[f9fdfc6ae2c20ff7]::iter::adapters::map::Map<core[f9fdfc6ae2c20ff7]::slice::iter::Iter<rustc_middle[a1758cd39e1aaae6]::ty::VariantDef>, rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached::{closure#9}>>, rustc_index[3bab5bde94c9a092]::vec::IndexVec<rustc_target[1f27652200010ea4]::abi::FieldIdx, rustc_target[1f27652200010ea4]::abi::Layout>, core[f9fdfc6ae2c20ff7]::result::Result<core[f9fdfc6ae2c20ff7]::convert::Infallible, &rustc_middle[a1758cd39e1aaae6]::ty::layout::LayoutError>, <core[f9fdfc6ae2c20ff7]::iter::adapters::map::Map<core[f9fdfc6ae2c20ff7]::slice::iter::Iter<rustc_middle[a1758cd39e1aaae6]::ty::VariantDef>, rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached::{closure#9}> as core[f9fdfc6ae2c20ff7]::iter::traits::iterator::Iterator>::try_collect<rustc_index[3bab5bde94c9a092]::vec::IndexVec<rustc_target[1f27652200010ea4]::abi::VariantIdx, rustc_index[3bab5bde94c9a092]::vec::IndexVec<rustc_target[1f27652200010ea4]::abi::FieldIdx, rustc_target[1f27652200010ea4]::abi::Layout>>>::{closure#0}, rustc_index[3bab5bde94c9a092]::vec::IndexVec<rustc_target[1f27652200010ea4]::abi::VariantIdx, rustc_index[3bab5bde94c9a092]::vec::IndexVec<rustc_target[1f27652200010ea4]::abi::FieldIdx, rustc_target[1f27652200010ea4]::abi::Layout>>>
  18:        0x113f54352 - rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of_uncached
  19:        0x113f690b7 - rustc_ty_utils[c0b689b1f3515b16]::layout::layout_of
  20:        0x1138b8076 - rustc_query_impl[c49845d791f7123d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c49845d791f7123d]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 16usize]>>
  21:        0x11388b03e - <rustc_query_impl[c49845d791f7123d]::query_impl::layout_of::dynamic_query::{closure#2} as core[f9fdfc6ae2c20ff7]::ops::function::FnOnce<(rustc_middle[a1758cd39e1aaae6]::ty::context::TyCtxt, rustc_middle[a1758cd39e1aaae6]::ty::ParamEnvAnd<rustc_middle[a1758cd39e1aaae6]::ty::Ty>)>>::call_once
  22:        0x1136a7444 - rustc_query_system[560604c93bb76bb8]::query::plumbing::try_execute_query::<rustc_query_impl[c49845d791f7123d]::DynamicConfig<rustc_query_system[560604c93bb76bb8]::query::caches::DefaultCache<rustc_middle[a1758cd39e1aaae6]::ty::ParamEnvAnd<rustc_middle[a1758cd39e1aaae6]::ty::Ty>, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[c49845d791f7123d]::plumbing::QueryCtxt, false>
  23:        0x1138f3664 - rustc_query_impl[c49845d791f7123d]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  24:        0x1131e63c9 - rustc_middle[a1758cd39e1aaae6]::query::plumbing::query_get_at::<rustc_query_system[560604c93bb76bb8]::query::caches::DefaultCache<rustc_middle[a1758cd39e1aaae6]::ty::ParamEnvAnd<rustc_middle[a1758cd39e1aaae6]::ty::Ty>, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 16usize]>>>
  25:        0x1132d47e4 - <rustc_mir_transform[23a41c5644e1310c]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[23a41c5644e1310c]::pass_manager::MirLint>::run_lint
  26:        0x11327ab62 - rustc_mir_transform[23a41c5644e1310c]::pass_manager::run_passes_inner
  27:        0x113318174 - rustc_mir_transform[23a41c5644e1310c]::run_analysis_to_runtime_passes
  28:        0x113317d14 - rustc_mir_transform[23a41c5644e1310c]::mir_drops_elaborated_and_const_checked
  29:        0x1138b78fa - rustc_query_impl[c49845d791f7123d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c49845d791f7123d]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 8usize]>>
  30:        0x11374229c - rustc_query_system[560604c93bb76bb8]::query::plumbing::try_execute_query::<rustc_query_impl[c49845d791f7123d]::DynamicConfig<rustc_query_system[560604c93bb76bb8]::query::caches::VecCache<rustc_span[2387f3d797c339cf]::def_id::LocalDefId, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c49845d791f7123d]::plumbing::QueryCtxt, false>
  31:        0x1138c855b - rustc_query_impl[c49845d791f7123d]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  32:        0x112c45015 - rustc_interface[170cbfe6d1742c00]::passes::analysis
  33:        0x1138b7d8a - rustc_query_impl[c49845d791f7123d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c49845d791f7123d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 1usize]>>
  34:        0x11369f1ce - rustc_query_system[560604c93bb76bb8]::query::plumbing::try_execute_query::<rustc_query_impl[c49845d791f7123d]::DynamicConfig<rustc_query_system[560604c93bb76bb8]::query::caches::SingleCache<rustc_middle[a1758cd39e1aaae6]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c49845d791f7123d]::plumbing::QueryCtxt, false>
  35:        0x1138c2087 - rustc_query_impl[c49845d791f7123d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  36:        0x112451072 - <rustc_interface[170cbfe6d1742c00]::queries::QueryResult<&rustc_middle[a1758cd39e1aaae6]::ty::context::GlobalCtxt>>::enter::<core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>, rustc_driver_impl[2c62cc41b08aa508]::run_compiler::{closure#0}::{closure#1}::{closure#3}>
  37:        0x1124a5462 - rustc_interface[170cbfe6d1742c00]::interface::run_compiler::<core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>, rustc_driver_impl[2c62cc41b08aa508]::run_compiler::{closure#0}>::{closure#0}
  38:        0x112498e76 - std[d2f59205c3cc5fff]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[170cbfe6d1742c00]::util::run_in_thread_with_globals<rustc_interface[170cbfe6d1742c00]::util::run_in_thread_pool_with_globals<rustc_interface[170cbfe6d1742c00]::interface::run_compiler<core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>, rustc_driver_impl[2c62cc41b08aa508]::run_compiler::{closure#0}>::{closure#0}, core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>>::{closure#0}, core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>>
  39:        0x1124ab808 - <<std[d2f59205c3cc5fff]::thread::Builder>::spawn_unchecked_<rustc_interface[170cbfe6d1742c00]::util::run_in_thread_with_globals<rustc_interface[170cbfe6d1742c00]::util::run_in_thread_pool_with_globals<rustc_interface[170cbfe6d1742c00]::interface::run_compiler<core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>, rustc_driver_impl[2c62cc41b08aa508]::run_compiler::{closure#0}>::{closure#0}, core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>>::{closure#0}, core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f9fdfc6ae2c20ff7]::result::Result<(), rustc_span[2387f3d797c339cf]::ErrorGuaranteed>>::{closure#1} as core[f9fdfc6ae2c20ff7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:        0x10998ebf9 - std::sys::pal::unix::thread::Thread::new::thread_start::hfe823ba696805494
  41:     0x7ff81b2e9202 - __pthread_start


rustc version: 1.79.0-nightly (eb45c8444 2024-03-17)
platform: x86_64-apple-darwin

query stack during panic:
#0 [layout_of] computing layout of `UnitStruct`
#1 [layout_of] computing layout of `SomeEnum`
#2 [mir_drops_elaborated_and_const_checked] elaborating drops for `<impl at reduced_ed26c2ad02bf2ae9.rs:4:10: 4:17>::default`
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
this is probably a duplicate of https://github.com/rust-lang/rust/issues/83394
