### ISSUE TITLE
ICE when type checking

### ISSUE THREAD

**Issue by cicilzx** [rust-lang/rust#123977]
### Code

The seed program is from the testsuite: `tests/codegen-units/item-collection/implicit-panic-call.rs`, here is the link: https://github.com/rust-lang/rust/blob/023084804e5e8ea42877451c2b3030e7050281cc/tests/codegen-units/item-collection/implicit-panic-call.rs
I made some token level fuzzing and triggers the following ICE.

```Rust

#![feature(lang_items)]
#![feature(no_core)]
#![crate_type = "lib"]
#![no_core]
#![no_std]
#[lang = "panic_location"]
struct Location<'a> {
    _file: &'a str,
    _line: u32,
    _col: u32,
}
#[lang = "panic"]
#[inline]
#[track_caller]
fn panic(_: &'static str) -> ! {
    loop {}
}
#[lang = "sized"]
trait Sized {}
#[lang = "copy"]
trait Copy {}
#[lang = "freeze"]
trait Freeze {}
impl Copy for i32 {}
#[lang = "div"]
trait Div<Rhs = Self> {
    type Output;
    fn    (self, rhs: Rhs) -> Self::Output;
}
impl Div for i32 {
    type Output = i32;
    fn div(self, rhs: i32) -> i32 {
        self / rhs
    }
}
#[allow(unconditional_panic)]
pub fn foo() {
    let _ = 1 / 0;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.77.2 (25ef9e3d8 2024-04-09) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: expected identifier, found `(`
  --> src/main.rs:29:11
   |
27 | trait Div<Rhs = Self> {
   |                       - while parsing this item list starting here
28 |     type Output;
29 |     fn    (self, rhs: Rhs) -> Self::Output;
   |           ^ expected identifier
30 | }
   | - the item list ends here

error[E0407]: method `div` is not a member of trait `Div`
  --> src/main.rs:33:5
   |
33 | /     fn div(self, rhs: i32) -> i32 {
34 | |         self / rhs
35 | |     }
   | |_____^ not a member of trait `Div`

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:2:1
  |
2 | #![feature(lang_items)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:3:1
  |
3 | #![feature(no_core)]
  | ^^^^^^^^^^^^^^^^^^^^

warning: the feature `lang_items` is internal to the compiler or standard library
 --> src/main.rs:2:12
  |
2 | #![feature(lang_items)]
  |            ^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default

error[E0601]: `main` function not found in crate `playground`
  --> src/main.rs:40:2
   |
40 | }
   |  ^ consider adding a `main` function to `src/main.rs`

error: internal compiler error: compiler/rustc_hir_typeck/src/method/mod.rs:387:13: expected associated item for operator trait

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/compiler/rustc_errors/src/lib.rs:932:30:
Box<dyn Any>
stack backtrace:
   0:     0x7f5708389d16 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f5708389d16 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5708389d16 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f5708389d16 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f57083dc770 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x7f57083dc770 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f570837d61f - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x7f5708389af4 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5708389af4 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f570838c887 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x7f570838c5e9 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x7f570af9edac - std[85008a29cc0b7dba]::panicking::update_hook::<alloc[a3006b27d8562c00]::boxed::Box<rustc_driver_impl[7bf504f3f6583165]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f570838cfd6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4dd5cc3b5605ae1a
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
  13:     0x7f570838cfd6 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
  14:     0x7f570afce624 - std[85008a29cc0b7dba]::panicking::begin_panic::<rustc_errors[827dd93ffb72cf29]::ExplicitBug>::{closure#0}
  15:     0x7f570afcb056 - std[85008a29cc0b7dba]::sys_common::backtrace::__rust_end_short_backtrace::<std[85008a29cc0b7dba]::panicking::begin_panic<rustc_errors[827dd93ffb72cf29]::ExplicitBug>::{closure#0}, !>
  16:     0x7f570afcacc6 - std[85008a29cc0b7dba]::panicking::begin_panic::<rustc_errors[827dd93ffb72cf29]::ExplicitBug>
  17:     0x7f570afd9b61 - <rustc_errors[827dd93ffb72cf29]::diagnostic_builder::BugAbort as rustc_errors[827dd93ffb72cf29]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f570b3684db - <rustc_errors[827dd93ffb72cf29]::DiagCtxt>::bug::<alloc[a3006b27d8562c00]::string::String>
  19:     0x7f570b400fdb - rustc_middle[a985f8abd286e753]::util::bug::opt_span_bug_fmt::<rustc_span[865b327b21456c24]::span_encoding::Span>::{closure#0}
  20:     0x7f570b3ea24a - rustc_middle[a985f8abd286e753]::ty::context::tls::with_opt::<rustc_middle[a985f8abd286e753]::util::bug::opt_span_bug_fmt<rustc_span[865b327b21456c24]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f570b3ea0c8 - rustc_middle[a985f8abd286e753]::ty::context::tls::with_context_opt::<rustc_middle[a985f8abd286e753]::ty::context::tls::with_opt<rustc_middle[a985f8abd286e753]::util::bug::opt_span_bug_fmt<rustc_span[865b327b21456c24]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f570950c8a0 - rustc_middle[a985f8abd286e753]::util::bug::bug_fmt
  23:     0x7f570c7ea7ae - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::lookup_method_in_trait
  24:     0x7f570c683148 - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_overloaded_binop
  25:     0x7f570cc5dfeb - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f570c68c6ea - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_block_with_expected
  27:     0x7f570cc5cfa2 - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f570c978d4e - rustc_hir_typeck[914be875d9b743f0]::check::check_fn
  29:     0x7f570cc4fba0 - rustc_hir_typeck[914be875d9b743f0]::typeck
  30:     0x7f570cc4ee9f - rustc_query_impl[616430243197e8f4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[616430243197e8f4]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 8usize]>>
  31:     0x7f570c4e9822 - rustc_query_system[d592f7b82322148b]::query::plumbing::try_execute_query::<rustc_query_impl[616430243197e8f4]::DynamicConfig<rustc_query_system[d592f7b82322148b]::query::caches::VecCache<rustc_span[865b327b21456c24]::def_id::LocalDefId, rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[616430243197e8f4]::plumbing::QueryCtxt, false>
  32:     0x7f570c4e9450 - rustc_query_impl[616430243197e8f4]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7f570c4e73f7 - rustc_hir_analysis[13775d5f02570a3]::check_crate
  34:     0x7f570cba1266 - rustc_interface[80a0b631737fb765]::passes::analysis
  35:     0x7f570cba0c5f - rustc_query_impl[616430243197e8f4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[616430243197e8f4]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7f570cbfbf82 - rustc_query_system[d592f7b82322148b]::query::plumbing::try_execute_query::<rustc_query_impl[616430243197e8f4]::DynamicConfig<rustc_query_system[d592f7b82322148b]::query::caches::SingleCache<rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[616430243197e8f4]::plumbing::QueryCtxt, false>
  37:     0x7f570cbfbdc7 - rustc_query_impl[616430243197e8f4]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x7f570cee420b - rustc_interface[80a0b631737fb765]::interface::run_compiler::<core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>, rustc_driver_impl[7bf504f3f6583165]::run_compiler::{closure#0}>::{closure#0}
  39:     0x7f570d131df1 - std[85008a29cc0b7dba]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[80a0b631737fb765]::util::run_in_thread_with_globals<rustc_interface[80a0b631737fb765]::interface::run_compiler<core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>, rustc_driver_impl[7bf504f3f6583165]::run_compiler::{closure#0}>::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>
  40:     0x7f570d131c4f - <<std[85008a29cc0b7dba]::thread::Builder>::spawn_unchecked_<rustc_interface[80a0b631737fb765]::util::run_in_thread_with_globals<rustc_interface[80a0b631737fb765]::interface::run_compiler<core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>, rustc_driver_impl[7bf504f3f6583165]::run_compiler::{closure#0}>::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>::{closure#1} as core[7fef78d3beba6ff5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f5708396675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  42:     0x7f5708396675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  43:     0x7f5708396675 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  44:     0x7f57082a8609 - start_thread
  45:     0x7f57081cb353 - clone
  46:                0x0 - <unknown>

note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

note: rustc 1.77.2 (25ef9e3d8 2024-04-09) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `<impl at src/main.rs:31:1: 31:17>::div`
#1 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/compiler/rustc_errors/src/lib.rs:932:30:
Box<dyn Any>
stack backtrace:
   0:     0x7f5708389d16 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f5708389d16 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5708389d16 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f5708389d16 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f57083dc770 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x7f57083dc770 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f570837d61f - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x7f5708389af4 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5708389af4 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f570838c887 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x7f570838c5e9 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x7f570af9edac - std[85008a29cc0b7dba]::panicking::update_hook::<alloc[a3006b27d8562c00]::boxed::Box<rustc_driver_impl[7bf504f3f6583165]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f570838cfd6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4dd5cc3b5605ae1a
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
  13:     0x7f570838cfd6 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
  14:     0x7f570afce624 - std[85008a29cc0b7dba]::panicking::begin_panic::<rustc_errors[827dd93ffb72cf29]::ExplicitBug>::{closure#0}
  15:     0x7f570afcb056 - std[85008a29cc0b7dba]::sys_common::backtrace::__rust_end_short_backtrace::<std[85008a29cc0b7dba]::panicking::begin_panic<rustc_errors[827dd93ffb72cf29]::ExplicitBug>::{closure#0}, !>
  16:     0x7f570afcacc6 - std[85008a29cc0b7dba]::panicking::begin_panic::<rustc_errors[827dd93ffb72cf29]::ExplicitBug>
  17:     0x7f570afd9b61 - <rustc_errors[827dd93ffb72cf29]::diagnostic_builder::BugAbort as rustc_errors[827dd93ffb72cf29]::diagnostic_builder::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f570b3684db - <rustc_errors[827dd93ffb72cf29]::DiagCtxt>::bug::<alloc[a3006b27d8562c00]::string::String>
  19:     0x7f570b400fdb - rustc_middle[a985f8abd286e753]::util::bug::opt_span_bug_fmt::<rustc_span[865b327b21456c24]::span_encoding::Span>::{closure#0}
  20:     0x7f570b3ea24a - rustc_middle[a985f8abd286e753]::ty::context::tls::with_opt::<rustc_middle[a985f8abd286e753]::util::bug::opt_span_bug_fmt<rustc_span[865b327b21456c24]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f570b3ea0c8 - rustc_middle[a985f8abd286e753]::ty::context::tls::with_context_opt::<rustc_middle[a985f8abd286e753]::ty::context::tls::with_opt<rustc_middle[a985f8abd286e753]::util::bug::opt_span_bug_fmt<rustc_span[865b327b21456c24]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f570950c8a0 - rustc_middle[a985f8abd286e753]::util::bug::bug_fmt
  23:     0x7f570c7ea7ae - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::lookup_method_in_trait
  24:     0x7f570c683148 - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_overloaded_binop
  25:     0x7f570cc5dfeb - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f570c68f6da - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_decl
  27:     0x7f570c68d608 - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_block_with_expected
  28:     0x7f570cc5cfa2 - <rustc_hir_typeck[914be875d9b743f0]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7f570c978d4e - rustc_hir_typeck[914be875d9b743f0]::check::check_fn
  30:     0x7f570cc4fba0 - rustc_hir_typeck[914be875d9b743f0]::typeck
  31:     0x7f570cc4ee9f - rustc_query_impl[616430243197e8f4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[616430243197e8f4]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7f570c4e9822 - rustc_query_system[d592f7b82322148b]::query::plumbing::try_execute_query::<rustc_query_impl[616430243197e8f4]::DynamicConfig<rustc_query_system[d592f7b82322148b]::query::caches::VecCache<rustc_span[865b327b21456c24]::def_id::LocalDefId, rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[616430243197e8f4]::plumbing::QueryCtxt, false>
  33:     0x7f570c4e9450 - rustc_query_impl[616430243197e8f4]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f570c4e73f7 - rustc_hir_analysis[13775d5f02570a3]::check_crate
  35:     0x7f570cba1266 - rustc_interface[80a0b631737fb765]::passes::analysis
  36:     0x7f570cba0c5f - rustc_query_impl[616430243197e8f4]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[616430243197e8f4]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7f570cbfbf82 - rustc_query_system[d592f7b82322148b]::query::plumbing::try_execute_query::<rustc_query_impl[616430243197e8f4]::DynamicConfig<rustc_query_system[d592f7b82322148b]::query::caches::SingleCache<rustc_middle[a985f8abd286e753]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[616430243197e8f4]::plumbing::QueryCtxt, false>
  38:     0x7f570cbfbdc7 - rustc_query_impl[616430243197e8f4]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f570cee420b - rustc_interface[80a0b631737fb765]::interface::run_compiler::<core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>, rustc_driver_impl[7bf504f3f6583165]::run_compiler::{closure#0}>::{closure#0}
  40:     0x7f570d131df1 - std[85008a29cc0b7dba]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[80a0b631737fb765]::util::run_in_thread_with_globals<rustc_interface[80a0b631737fb765]::interface::run_compiler<core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>, rustc_driver_impl[7bf504f3f6583165]::run_compiler::{closure#0}>::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>
  41:     0x7f570d131c4f - <<std[85008a29cc0b7dba]::thread::Builder>::spawn_unchecked_<rustc_interface[80a0b631737fb765]::util::run_in_thread_with_globals<rustc_interface[80a0b631737fb765]::interface::run_compiler<core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>, rustc_driver_impl[7bf504f3f6583165]::run_compiler::{closure#0}>::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7fef78d3beba6ff5]::result::Result<(), rustc_span[865b327b21456c24]::ErrorGuaranteed>>::{closure#1} as core[7fef78d3beba6ff5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7f5708396675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  43:     0x7f5708396675 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  44:     0x7f5708396675 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  45:     0x7f57082a8609 - start_thread
  46:     0x7f57081cb353 - clone
  47:                0x0 - <unknown>

note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

note: rustc 1.77.2 (25ef9e3d8 2024-04-09) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `foo`
#1 [analysis] running analysis passes on this crate
end of query stack
Some errors have detailed explanations: E0407, E0554, E0601.
For more information about an error, try `rustc --explain E0407`.
```

</p>
</details>

**Comment by fmease** [comment]
Thanks for fuzzing rustc! However, using **internal** features to trigger an ICE is not considered to be a bug. Unless you can minimize this and get rid of any internal features, I will have to close this issue.

Quoting the backtrace you posted:

> note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

**Comment by compiler-errors** [comment]
I don't believe this is reproducible without lang items.
