### ISSUE TITLE
opaque types got hidden types registered from within subtype predicate

### ISSUE THREAD

**Issue by waynexia** [rust-lang/rust#124121]
### Code

In branch https://github.com/GreptimeTeam/greptimedb/pull/3740

```shell
git clone https://github.com/waynexia/greptimedb.git
cd greptimedb
git checkout update-toolchain-3
make clippy
```

Minimal reproducer WIP

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (1cec373f6 2024-04-16)
binary: rustc
commit-hash: 1cec373f65eb76e8e4b4d1847213cf3ec6c292b6
commit-date: 2024-04-16
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3
```

### Error output

```
error: internal compiler error: compiler/rustc_infer/src/infer/mod.rs:956:17: opaque types got hidden types registered from within subtype predicate: tracing_subscriber::layer::Layered<Alias(Opaque, AliasTy { args: [tracing_subscriber::Registry], def_id: DefId(0:1668 ~ console_subscriber[3c62]::builder::{impl#1}::spawn::{opaque#0}) }), tracing_subscriber::Registry, tracing_subscriber::Registry> vs tracing_subscriber::layer::Layered<Alias(Opaque, AliasTy { args: [tracing_subscriber::Registry], def_id: DefId(0:1668 ~ console_subscriber[3c62]::builder::{impl#1}::spawn::{opaque#0}) }), tracing_subscriber::Registry, tracing_subscriber::Registry>
   --> /home/wayne/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/console-subscriber-0.1.10/src/builder.rs:407:19
    |
407 |             .with(tracing_subscriber::fmt::layer().with_filter(fmt_filter))
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at compiler/rustc_infer/src/infer/mod.rs:956:17:
Box<dyn Any>
stack backtrace:
   0:     0x7f50f0b31cd5 - std::backtrace_rs::backtrace::libunwind::trace::h39aa7bbcf61112e7
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f50f0b31cd5 - std::backtrace_rs::backtrace::trace_unsynchronized::h8cbdf27e1140b5c7
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f50f0b31cd5 - std::sys_common::backtrace::_print_fmt::hf30f89c5893a63c3
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f50f0b31cd5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ae58e1a025dc15e
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f50f0b80f9b - core::fmt::rt::Argument::fmt::h79663960ec3ead41
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/core/src/fmt/rt.rs:165:63
   5:     0x7f50f0b80f9b - core::fmt::write::hea0bc3323f37fb37
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/core/src/fmt/mod.rs:1157:21
   6:     0x7f50f0b2685f - std::io::Write::write_fmt::h0aebada01ce9c9e1
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/io/mod.rs:1832:15
   7:     0x7f50f0b31aae - std::sys_common::backtrace::_print::hb8b452cedd5245b9
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f50f0b31aae - std::sys_common::backtrace::print::h45e09369dba6d79a
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f50f0b34429 - std::panicking::default_hook::{{closure}}::h17bec0ff62b1df32
  10:     0x7f50f0b3416d - std::panicking::default_hook::hc8938c3997234b0d
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/panicking.rs:291:9
  11:     0x7f50ed46d3dc - std[531770c5e2e8d301]::panicking::update_hook::<alloc[d882034972180c03]::boxed::Box<rustc_driver_impl[427e5c398467f86b]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f50f0b34b2c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6d2f4133a0440d99
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/alloc/src/boxed.rs:2032:9
  13:     0x7f50f0b34b2c - std::panicking::rust_panic_with_hook::h7c86743fcac7c36d
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/panicking.rs:792:13
  14:     0x7f50ed49cf54 - std[531770c5e2e8d301]::panicking::begin_panic::<rustc_errors[1b3eec32e47ffd2f]::ExplicitBug>::{closure#0}
  15:     0x7f50ed499bd6 - std[531770c5e2e8d301]::sys_common::backtrace::__rust_end_short_backtrace::<std[531770c5e2e8d301]::panicking::begin_panic<rustc_errors[1b3eec32e47ffd2f]::ExplicitBug>::{closure#0}, !>
  16:     0x7f50ed4998b6 - std[531770c5e2e8d301]::panicking::begin_panic::<rustc_errors[1b3eec32e47ffd2f]::ExplicitBug>
  17:     0x7f50ed4a5f81 - <rustc_errors[1b3eec32e47ffd2f]::diagnostic::BugAbort as rustc_errors[1b3eec32e47ffd2f]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f50ed6e55b8 - <rustc_errors[1b3eec32e47ffd2f]::DiagCtxt>::span_bug::<rustc_span[53b55791d064607f]::span_encoding::Span, alloc[d882034972180c03]::string::String>
  19:     0x7f50ed71c5fd - rustc_middle[d8712503438341b1]::util::bug::opt_span_bug_fmt::<rustc_span[53b55791d064607f]::span_encoding::Span>::{closure#0}
  20:     0x7f50ed71c92a - rustc_middle[d8712503438341b1]::ty::context::tls::with_opt::<rustc_middle[d8712503438341b1]::util::bug::opt_span_bug_fmt<rustc_span[53b55791d064607f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f50ed70199b - rustc_middle[d8712503438341b1]::ty::context::tls::with_context_opt::<rustc_middle[d8712503438341b1]::ty::context::tls::with_opt<rustc_middle[d8712503438341b1]::util::bug::opt_span_bug_fmt<rustc_span[53b55791d064607f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f50ed7006b7 - rustc_middle[d8712503438341b1]::util::bug::span_bug_fmt::<rustc_span[53b55791d064607f]::span_encoding::Span>
  23:     0x7f50eb407ce1 - <rustc_trait_selection[27d743aeac5b0616]::traits::fulfill::FulfillProcessor as rustc_data_structures[f4bfcbb9d91a10eb]::obligation_forest::ObligationProcessor>::process_obligation
  24:     0x7f50ee80d823 - <rustc_data_structures[f4bfcbb9d91a10eb]::obligation_forest::ObligationForest<rustc_trait_selection[27d743aeac5b0616]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[27d743aeac5b0616]::traits::fulfill::FulfillProcessor>
  25:     0x7f50ef8e0b00 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_method_argument_types
  26:     0x7f50ef17384a - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x7f50ef173732 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f50ef16d6e1 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7f50ef173701 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7f50eea54821 - rustc_hir_typeck[77e1cc157524533d]::check::check_fn
  31:     0x7f50eea4ad49 - rustc_hir_typeck[77e1cc157524533d]::typeck
  32:     0x7f50eea4a709 - rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7f50eea36d31 - rustc_query_system[219200ddf699f4fc]::query::plumbing::try_execute_query::<rustc_query_impl[ffef2ea0cc82d0dd]::DynamicConfig<rustc_query_system[219200ddf699f4fc]::query::caches::VecCache<rustc_span[53b55791d064607f]::def_id::LocalDefId, rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::QueryCtxt, false>
  34:     0x7f50eea3564c - rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f50eea35218 - <rustc_middle[d8712503438341b1]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[6a1b22ded269dcc8]::check_crate::{closure#4}>::{closure#0}
  36:     0x7f50eea33f01 - rustc_hir_analysis[6a1b22ded269dcc8]::check_crate
  37:     0x7f50ef0c5b7a - rustc_interface[336e9a5fb47021d9]::passes::analysis
  38:     0x7f50ef0c56d5 - rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7f50ef64c9a5 - rustc_query_system[219200ddf699f4fc]::query::plumbing::try_execute_query::<rustc_query_impl[ffef2ea0cc82d0dd]::DynamicConfig<rustc_query_system[219200ddf699f4fc]::query::caches::SingleCache<rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::QueryCtxt, false>
  40:     0x7f50ef64c709 - rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7f50ef4bdfd9 - rustc_interface[336e9a5fb47021d9]::interface::run_compiler::<core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>, rustc_driver_impl[427e5c398467f86b]::run_compiler::{closure#0}>::{closure#1}
  42:     0x7f50ef3ab327 - std[531770c5e2e8d301]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_with_globals<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_pool_with_globals<rustc_interface[336e9a5fb47021d9]::interface::run_compiler<core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>, rustc_driver_impl[427e5c398467f86b]::run_compiler::{closure#0}>::{closure#1}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>
  43:     0x7f50ef3ab0ea - <<std[531770c5e2e8d301]::thread::Builder>::spawn_unchecked_<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_with_globals<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_pool_with_globals<rustc_interface[336e9a5fb47021d9]::interface::run_compiler<core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>, rustc_driver_impl[427e5c398467f86b]::run_compiler::{closure#0}>::{closure#1}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#2} as core[2a3c68b720306447]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f50f0b3ea1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc8d25b9018534ef3
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/alloc/src/boxed.rs:2018:9
  45:     0x7f50f0b3ea1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9f7c65c9881af958
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/alloc/src/boxed.rs:2018:9
  46:     0x7f50f0b3ea1b - std::sys::pal::unix::thread::Thread::new::thread_start::ha61a9957d3d99efc
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/sys/pal/unix/thread.rs:108:17
  47:     0x7f50ea2a955a - <unknown>
  48:     0x7f50ea326a3c - <unknown>
  49:                0x0 - <unknown>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_infer/src/infer/mod.rs:956:17:
Box<dyn Any>
stack backtrace:
   0:     0x7f50f0b19b55 - std::backtrace_rs::backtrace::libunwind::trace::h39aa7bbcf61112e7
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f50f0b19b55 - std::backtrace_rs::backtrace::trace_unsynchronized::hc85da789d7f1d5d2
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f50f0b19b55 - std::backtrace::Backtrace::create::hcb33de73690a8229
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/backtrace.rs:331:13
   3:     0x7f50f0b19aa5 - std::backtrace::Backtrace::force_capture::hfc740aded7593d99
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/backtrace.rs:312:9
   4:     0x7f50ed46db73 - std[531770c5e2e8d301]::panicking::update_hook::<alloc[d882034972180c03]::boxed::Box<rustc_driver_impl[427e5c398467f86b]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f50f0b34b2c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6d2f4133a0440d99
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/alloc/src/boxed.rs:2032:9
   6:     0x7f50f0b34b2c - std::panicking::rust_panic_with_hook::h7c86743fcac7c36d
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/panicking.rs:792:13
   7:     0x7f50ed49cf54 - std[531770c5e2e8d301]::panicking::begin_panic::<rustc_errors[1b3eec32e47ffd2f]::ExplicitBug>::{closure#0}
   8:     0x7f50ed499bd6 - std[531770c5e2e8d301]::sys_common::backtrace::__rust_end_short_backtrace::<std[531770c5e2e8d301]::panicking::begin_panic<rustc_errors[1b3eec32e47ffd2f]::ExplicitBug>::{closure#0}, !>
   9:     0x7f50ed4998b6 - std[531770c5e2e8d301]::panicking::begin_panic::<rustc_errors[1b3eec32e47ffd2f]::ExplicitBug>
  10:     0x7f50ed4a5f81 - <rustc_errors[1b3eec32e47ffd2f]::diagnostic::BugAbort as rustc_errors[1b3eec32e47ffd2f]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7f50ed6e55b8 - <rustc_errors[1b3eec32e47ffd2f]::DiagCtxt>::span_bug::<rustc_span[53b55791d064607f]::span_encoding::Span, alloc[d882034972180c03]::string::String>
  12:     0x7f50ed71c5fd - rustc_middle[d8712503438341b1]::util::bug::opt_span_bug_fmt::<rustc_span[53b55791d064607f]::span_encoding::Span>::{closure#0}
  13:     0x7f50ed71c92a - rustc_middle[d8712503438341b1]::ty::context::tls::with_opt::<rustc_middle[d8712503438341b1]::util::bug::opt_span_bug_fmt<rustc_span[53b55791d064607f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7f50ed70199b - rustc_middle[d8712503438341b1]::ty::context::tls::with_context_opt::<rustc_middle[d8712503438341b1]::ty::context::tls::with_opt<rustc_middle[d8712503438341b1]::util::bug::opt_span_bug_fmt<rustc_span[53b55791d064607f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7f50ed7006b7 - rustc_middle[d8712503438341b1]::util::bug::span_bug_fmt::<rustc_span[53b55791d064607f]::span_encoding::Span>
  16:     0x7f50eb407ce1 - <rustc_trait_selection[27d743aeac5b0616]::traits::fulfill::FulfillProcessor as rustc_data_structures[f4bfcbb9d91a10eb]::obligation_forest::ObligationProcessor>::process_obligation
  17:     0x7f50ee80d823 - <rustc_data_structures[f4bfcbb9d91a10eb]::obligation_forest::ObligationForest<rustc_trait_selection[27d743aeac5b0616]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[27d743aeac5b0616]::traits::fulfill::FulfillProcessor>
  18:     0x7f50ef8e0b00 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_method_argument_types
  19:     0x7f50ef17384a - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  20:     0x7f50ef173732 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  21:     0x7f50ef16d6e1 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_block_with_expected
  22:     0x7f50ef173701 - <rustc_hir_typeck[77e1cc157524533d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23:     0x7f50eea54821 - rustc_hir_typeck[77e1cc157524533d]::check::check_fn
  24:     0x7f50eea4ad49 - rustc_hir_typeck[77e1cc157524533d]::typeck
  25:     0x7f50eea4a709 - rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7f50eea36d31 - rustc_query_system[219200ddf699f4fc]::query::plumbing::try_execute_query::<rustc_query_impl[ffef2ea0cc82d0dd]::DynamicConfig<rustc_query_system[219200ddf699f4fc]::query::caches::VecCache<rustc_span[53b55791d064607f]::def_id::LocalDefId, rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::QueryCtxt, false>
  27:     0x7f50eea3564c - rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f50eea35218 - <rustc_middle[d8712503438341b1]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[6a1b22ded269dcc8]::check_crate::{closure#4}>::{closure#0}
  29:     0x7f50eea33f01 - rustc_hir_analysis[6a1b22ded269dcc8]::check_crate
  30:     0x7f50ef0c5b7a - rustc_interface[336e9a5fb47021d9]::passes::analysis
  31:     0x7f50ef0c56d5 - rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 1usize]>>
  32:     0x7f50ef64c9a5 - rustc_query_system[219200ddf699f4fc]::query::plumbing::try_execute_query::<rustc_query_impl[ffef2ea0cc82d0dd]::DynamicConfig<rustc_query_system[219200ddf699f4fc]::query::caches::SingleCache<rustc_middle[d8712503438341b1]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ffef2ea0cc82d0dd]::plumbing::QueryCtxt, false>
  33:     0x7f50ef64c709 - rustc_query_impl[ffef2ea0cc82d0dd]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f50ef4bdfd9 - rustc_interface[336e9a5fb47021d9]::interface::run_compiler::<core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>, rustc_driver_impl[427e5c398467f86b]::run_compiler::{closure#0}>::{closure#1}
  35:     0x7f50ef3ab327 - std[531770c5e2e8d301]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_with_globals<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_pool_with_globals<rustc_interface[336e9a5fb47021d9]::interface::run_compiler<core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>, rustc_driver_impl[427e5c398467f86b]::run_compiler::{closure#0}>::{closure#1}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>
  36:     0x7f50ef3ab0ea - <<std[531770c5e2e8d301]::thread::Builder>::spawn_unchecked_<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_with_globals<rustc_interface[336e9a5fb47021d9]::util::run_in_thread_pool_with_globals<rustc_interface[336e9a5fb47021d9]::interface::run_compiler<core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>, rustc_driver_impl[427e5c398467f86b]::run_compiler::{closure#0}>::{closure#1}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2a3c68b720306447]::result::Result<(), rustc_span[53b55791d064607f]::ErrorGuaranteed>>::{closure#2} as core[2a3c68b720306447]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f50f0b3ea1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc8d25b9018534ef3
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/alloc/src/boxed.rs:2018:9
  38:     0x7f50f0b3ea1b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9f7c65c9881af958
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/alloc/src/boxed.rs:2018:9
  39:     0x7f50f0b3ea1b - std::sys::pal::unix::thread::Thread::new::thread_start::ha61a9957d3d99efc
                               at /rustc/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6/library/std/src/sys/pal/unix/thread.rs:108:17
  40:     0x7f50ea2a955a - <unknown>
  41:     0x7f50ea326a3c - <unknown>
  42:                0x0 - <unknown>


rustc version: 1.79.0-nightly (1cec373f6 2024-04-16)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `builder::<impl at /home/wayne/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/console-subscriber-0.1.10/src/builder.rs:78:1: 78:13>::init`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by waynexia** [comment]
Appreciate it! It doesn't show up in
```
rustc 1.79.0-nightly (becebb315 2024-04-17)
binary: rustc
commit-hash: becebb3158149a115cad8a402612e25436a7e37b
commit-date: 2024-04-17
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3
```
