### ISSUE TITLE
ICW when Unknown MIR dialect: '       '

### ISSUE THREAD

**Issue by cicilzx** [rust-lang/rust#124160]
### Code

```Rust

#![feature(custom_mir, core_intrinsics)]
#![allow(unused_assignments)]
extern crate core;
use core::intrinsics::mir::*;
struct NotCopy(bool);
#[custom_mir(dialect = "       ")]
fn f(_1: NotCopy) {
    mir!({
        let _2 = _1;
        Call(RET = opaque(Move(_1)), ReturnTo(bb1), UnwindUnreachable())
    }
    bb1 = {
        let _3 = Move(_2);
        Call(RET = opaque(_3), ReturnTo(bb2), UnwindUnreachable())
    }
    bb2 = {
        Return()
    })
}
#[inline(never)]
fn opaque<T>(_t: T) {}
fn main() {
    f(NotCopy(true));
    println!("hi");
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (e3181b091 2024-04-18)
```

### Error output

```
Compiling playground v0.0.1 (/playground)
warning: the feature `custom_mir` is internal to the compiler or standard library
 --> src/main.rs:2:12
  |
2 | #![feature(custom_mir, core_intrinsics)]
  |            ^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default

warning: the feature `core_intrinsics` is internal to the compiler or standard library
 --> src/main.rs:2:24
  |
2 | #![feature(custom_mir, core_intrinsics)]
  |                        ^^^^^^^^^^^^^^^
  |
  = note: using it is strongly discouraged

error: internal compiler error: compiler/rustc_middle/src/mir/mod.rs:196:18: Unknown MIR dialect: '       '

thread 'rustc' panicked at compiler/rustc_middle/src/mir/mod.rs:196:18:
Box<dyn Any>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7fa1af9d8a75 - std::backtrace_rs::backtrace::libunwind::trace::h3178471d9f78e3cb
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7fa1af9d8a75 - std::backtrace_rs::backtrace::trace_unsynchronized::hbdc1834532c09e2a
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa1af9d8a75 - std::sys_common::backtrace::_print_fmt::he0effe2168984738
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fa1af9d8a75 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2a6106103c1910ba
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fa1afa27ceb - core::fmt::rt::Argument::fmt::h2639f1ab76ff1f58
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/core/src/fmt/rt.rs:165:63
   5:     0x7fa1afa27ceb - core::fmt::write::h6eeb5f66a1bca2fc
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/core/src/fmt/mod.rs:1157:21
   6:     0x7fa1af9cd5ff - std::io::Write::write_fmt::h2d109f420f32f292
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/io/mod.rs:1832:15
   7:     0x7fa1af9d884e - std::sys_common::backtrace::_print::h5eae48fb2e24a524
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fa1af9d884e - std::sys_common::backtrace::print::h82c60fdc4d53f603
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fa1af9db1b9 - std::panicking::default_hook::{{closure}}::hb1af461c15feab08
  10:     0x7fa1af9daefd - std::panicking::default_hook::h7844e690451631db
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/panicking.rs:291:9
  11:     0x7fa1b2a6a62c - std[470e2cc56b39f005]::panicking::update_hook::<alloc[d6b86ee176900255]::boxed::Box<rustc_driver_impl[49d04bc720e6c988]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fa1af9db8b6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1970eb6751de199d
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/alloc/src/boxed.rs:2036:9
  13:     0x7fa1af9db8b6 - std::panicking::rust_panic_with_hook::hbe7168eb035bc8b8
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/panicking.rs:792:13
  14:     0x7fa1b2a9a774 - std[470e2cc56b39f005]::panicking::begin_panic::<rustc_errors[8cb7adb7aedc754]::ExplicitBug>::{closure#0}
  15:     0x7fa1b2a972d6 - std[470e2cc56b39f005]::sys_common::backtrace::__rust_end_short_backtrace::<std[470e2cc56b39f005]::panicking::begin_panic<rustc_errors[8cb7adb7aedc754]::ExplicitBug>::{closure#0}, !>
  16:     0x7fa1b2a928d6 - std[470e2cc56b39f005]::panicking::begin_panic::<rustc_errors[8cb7adb7aedc754]::ExplicitBug>
  17:     0x7fa1b2aa3851 - <rustc_errors[8cb7adb7aedc754]::diagnostic::BugAbort as rustc_errors[8cb7adb7aedc754]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7fa1b2f4d13c - rustc_middle[30aac62dc32be234]::util::bug::opt_span_bug_fmt::<rustc_span[e4641a2caa7e40e]::span_encoding::Span>::{closure#0}
  19:     0x7fa1b2f3499a - rustc_middle[30aac62dc32be234]::ty::context::tls::with_opt::<rustc_middle[30aac62dc32be234]::util::bug::opt_span_bug_fmt<rustc_span[e4641a2caa7e40e]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7fa1b2f3481b - rustc_middle[30aac62dc32be234]::ty::context::tls::with_context_opt::<rustc_middle[30aac62dc32be234]::ty::context::tls::with_opt<rustc_middle[30aac62dc32be234]::util::bug::opt_span_bug_fmt<rustc_span[e4641a2caa7e40e]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7fa1b12ab0f0 - rustc_middle[30aac62dc32be234]::util::bug::bug_fmt
  22:     0x7fa1b2f11b46 - <rustc_middle[30aac62dc32be234]::mir::syntax::MirPhase>::parse
  23:     0x7fa1b41c11cd - rustc_mir_build[4bed8e987e2d1d92]::build::mir_build
  24:     0x7fa1b41bb30e - rustc_query_impl[c4c415242faa3e03]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c4c415242faa3e03]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7fa1b403ce31 - rustc_query_system[63c18adbd871b367]::query::plumbing::try_execute_query::<rustc_query_impl[c4c415242faa3e03]::DynamicConfig<rustc_query_system[63c18adbd871b367]::query::caches::VecCache<rustc_span[e4641a2caa7e40e]::def_id::LocalDefId, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c4c415242faa3e03]::plumbing::QueryCtxt, false>
  26:     0x7fa1b403c94c - rustc_query_impl[c4c415242faa3e03]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7fa1b465aeba - rustc_mir_transform[28852d9cd44326fd]::ffi_unwind_calls::has_ffi_unwind_calls
  28:     0x7fa1b465a95b - rustc_query_impl[c4c415242faa3e03]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c4c415242faa3e03]::query_impl::has_ffi_unwind_calls::dynamic_query::{closure#2}::{closure#0}, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 1usize]>>
  29:     0x7fa1b465a0c7 - rustc_query_system[63c18adbd871b367]::query::plumbing::try_execute_query::<rustc_query_impl[c4c415242faa3e03]::DynamicConfig<rustc_query_system[63c18adbd871b367]::query::caches::VecCache<rustc_span[e4641a2caa7e40e]::def_id::LocalDefId, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c4c415242faa3e03]::plumbing::QueryCtxt, false>
  30:     0x7fa1b4659cbf - rustc_query_impl[c4c415242faa3e03]::query_impl::has_ffi_unwind_calls::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7fa1b176e442 - rustc_mir_transform[28852d9cd44326fd]::mir_promoted
  32:     0x7fa1b43eb856 - rustc_query_impl[c4c415242faa3e03]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c4c415242faa3e03]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 16usize]>>
  33:     0x7fa1b43ebb1e - rustc_query_system[63c18adbd871b367]::query::plumbing::try_execute_query::<rustc_query_impl[c4c415242faa3e03]::DynamicConfig<rustc_query_system[63c18adbd871b367]::query::caches::VecCache<rustc_span[e4641a2caa7e40e]::def_id::LocalDefId, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[c4c415242faa3e03]::plumbing::QueryCtxt, false>
  34:     0x7fa1b43eb75f - rustc_query_impl[c4c415242faa3e03]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7fa1b4c64db5 - rustc_borrowck[73e75e45849ef543]::mir_borrowck
  36:     0x7fa1b4c64ce9 - rustc_query_impl[c4c415242faa3e03]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c4c415242faa3e03]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 8usize]>>
  37:     0x7fa1b403ce31 - rustc_query_system[63c18adbd871b367]::query::plumbing::try_execute_query::<rustc_query_impl[c4c415242faa3e03]::DynamicConfig<rustc_query_system[63c18adbd871b367]::query::caches::VecCache<rustc_span[e4641a2caa7e40e]::def_id::LocalDefId, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c4c415242faa3e03]::plumbing::QueryCtxt, false>
  38:     0x7fa1b403c88c - rustc_query_impl[c4c415242faa3e03]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7fa1b43d6eeb - rustc_interface[53da3a61844c65b8]::passes::analysis
  40:     0x7fa1b43d6095 - rustc_query_impl[c4c415242faa3e03]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c4c415242faa3e03]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 1usize]>>
  41:     0x7fa1b4be82a5 - rustc_query_system[63c18adbd871b367]::query::plumbing::try_execute_query::<rustc_query_impl[c4c415242faa3e03]::DynamicConfig<rustc_query_system[63c18adbd871b367]::query::caches::SingleCache<rustc_middle[30aac62dc32be234]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c4c415242faa3e03]::plumbing::QueryCtxt, false>
  42:     0x7fa1b4be8009 - rustc_query_impl[c4c415242faa3e03]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  43:     0x7fa1b4a7a399 - rustc_interface[53da3a61844c65b8]::interface::run_compiler::<core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>, rustc_driver_impl[49d04bc720e6c988]::run_compiler::{closure#0}>::{closure#1}
  44:     0x7fa1b4a638e7 - std[470e2cc56b39f005]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[53da3a61844c65b8]::util::run_in_thread_with_globals<rustc_interface[53da3a61844c65b8]::util::run_in_thread_pool_with_globals<rustc_interface[53da3a61844c65b8]::interface::run_compiler<core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>, rustc_driver_impl[49d04bc720e6c988]::run_compiler::{closure#0}>::{closure#1}, core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>>::{closure#0}, core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>>
  45:     0x7fa1b4a636aa - <<std[470e2cc56b39f005]::thread::Builder>::spawn_unchecked_<rustc_interface[53da3a61844c65b8]::util::run_in_thread_with_globals<rustc_interface[53da3a61844c65b8]::util::run_in_thread_pool_with_globals<rustc_interface[53da3a61844c65b8]::interface::run_compiler<core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>, rustc_driver_impl[49d04bc720e6c988]::run_compiler::{closure#0}>::{closure#1}, core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>>::{closure#0}, core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[face5b6acd610675]::result::Result<(), rustc_span[e4641a2caa7e40e]::ErrorGuaranteed>>::{closure#2} as core[face5b6acd610675]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x7fa1af9e578b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf6035c437e16c4de
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/alloc/src/boxed.rs:2022:9
  47:     0x7fa1af9e578b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2661e9a43deb34c7
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/alloc/src/boxed.rs:2022:9
  48:     0x7fa1af9e578b - std::sys::pal::unix::thread::Thread::new::thread_start::h748d17afc5d2b125
                               at /rustc/e3181b091e88321f5ea149afed6db0edf0a4f37b/library/std/src/sys/pal/unix/thread.rs:108:17
  49:     0x7fa1af8f2609 - start_thread
  50:     0x7fa1af815353 - clone
  51:                0x0 - <unknown>

note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

note: please attach the file at `/playground/rustc-ice-2024-04-19T13_32_55-25.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `f`
#1 [has_ffi_unwind_calls] checking if `f` contains FFI-unwind calls
#2 [mir_promoted] promoting constants in MIR for `f`
#3 [mir_borrowck] borrow-checking `f`
#4 [analysis] running analysis passes on this crate
end of query stack
warning: `playground` (bin "playground") generated 2 warnings
error: could not compile `playground` (bin "playground"); 2 warnings emitted
```

</p>
</details>

**Comment by compiler-errors** [comment]
> note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

Hey -- sorry, but you're misusing a feature not intended for end users. Gonna close this since I don't think it necessarily needs fixing.
