### ISSUE TITLE
Compiler Crash with "Hello world" on latest nightly (aarch64)

### ISSUE THREAD

**Issue by mrhh69** [rust-lang/rust#124719]
### Code

Any code (even just a `fn main() {}`)

### Meta

Latest nightly fails, going back a week or so (`nightly-2024-04-23-aarch64-unknown-linux-gnu`) works fine

### Error output

```
thread 'rustc' panicked at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/compiler/rustc_serialize/src/serialize.rs:122:9:
assertion failed: bytes[len] == STR_SENTINEL
stack backtrace:
   0:     0xfffef6ac75f0 - std::backtrace_rs::backtrace::libunwind::trace::h7468ef772fab1944
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0xfffef6ac75f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h900ea99b9b584ceb
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xfffef6ac75f0 - std::sys_common::backtrace::_print_fmt::h4f2b1b5f2242c591
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/sys_common/backtrace.rs:68:5
   3:     0xfffef6ac75f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h250450a89bfcfa72
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xfffef6b11934 - core::fmt::rt::Argument::fmt::h6af6fa5aee7c5ff0
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/core/src/fmt/rt.rs:165:63
   5:     0xfffef6b11934 - core::fmt::write::hdeed67595fb43eb7
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/core/src/fmt/mod.rs:1157:21
   6:     0xfffef6abc928 - std::io::Write::write_fmt::h72dd39cfeea5fbdf
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/io/mod.rs:1832:15
   7:     0xfffef6ac7438 - std::sys_common::backtrace::_print::heff530ec289745ee
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xfffef6ac7438 - std::sys_common::backtrace::print::h1d8af89a4ea71658
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xfffef6ac9bd8 - std::panicking::default_hook::{{closure}}::h50ca4cc325ab9fa1
  10:     0xfffef6ac9880 - std::panicking::default_hook::h73b9947aa4475ada
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/panicking.rs:298:9
  11:     0xfffef7704dcc - <alloc[dfc5dab200d34227]::boxed::Box<rustc_driver_impl[5695a40b5d0389e1]::install_ice_hook::{closure#0}> as core[1b6b982d7ada3f37]::ops::function::Fn<(&dyn for<'a, 'b> core[1b6b982d7ada3f37]::ops::function::Fn<(&'a core[1b6b982d7ada3f37]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[1b6b982d7ada3f37]::marker::Sync + core[1b6b982d7ada3f37]::marker::Send, &core[1b6b982d7ada3f37]::panic::panic_info::PanicInfo)>>::call
  12:     0xfffef6aca228 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hcddf09cfbab33b4d
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/alloc/src/boxed.rs:2036:9
  13:     0xfffef6aca228 - std::panicking::rust_panic_with_hook::hcbb63d208cd650b3
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/panicking.rs:799:13
  14:     0xfffef6ac9fd8 - std::panicking::begin_panic_handler::{{closure}}::h4a461efecd0b7b5e
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/panicking.rs:656:13
  15:     0xfffef6ac7ad0 - std::sys_common::backtrace::__rust_end_short_backtrace::h12f24d52d2002ba0
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/sys_common/backtrace.rs:171:18
  16:     0xfffef6ac9d78 - rust_begin_unwind
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/panicking.rs:652:5
  17:     0xfffef6a93778 - core::panicking::panic_fmt::ha11ce5ecdba6dd0c
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/core/src/panicking.rs:72:14
  18:     0xfffef6a937f8 - core::panicking::panic::h3397544d5b717631
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/core/src/panicking.rs:146:5
  19:     0xfffefc3876dc - <rustc_metadata[7162c47c71e4ba8d]::rmeta::decoder::DecodeContext as rustc_serialize[2a8b155d467a75af]::serialize::Decoder>::read_str
  20:     0xfffefc3867b8 - <rustc_target[66b02cdfa40375e]::spec::TargetTriple as rustc_serialize[2a8b155d467a75af]::serialize::Decodable<rustc_metadata[7162c47c71e4ba8d]::rmeta::decoder::DecodeContext>>::decode
  21:     0xfffefc36d610 - <rustc_metadata[7162c47c71e4ba8d]::rmeta::CrateHeader as rustc_serialize[2a8b155d467a75af]::serialize::Decodable<rustc_metadata[7162c47c71e4ba8d]::rmeta::decoder::DecodeContext>>::decode
  22:     0xfffefc2d9ca4 - <rustc_metadata[7162c47c71e4ba8d]::rmeta::decoder::MetadataBlob>::get_header
  23:     0xfffefc3a5928 - <rustc_metadata[7162c47c71e4ba8d]::locator::CrateLocator>::extract_one
  24:     0xfffefc3a4f58 - <rustc_metadata[7162c47c71e4ba8d]::locator::CrateLocator>::extract_lib
  25:     0xfffefc3a4388 - <rustc_metadata[7162c47c71e4ba8d]::locator::CrateLocator>::find_library_crate
  26:     0xfffefc3a3000 - <rustc_metadata[7162c47c71e4ba8d]::locator::CrateLocator>::maybe_load_library_crate
  27:     0xfffefc2b2bcc - <rustc_metadata[7162c47c71e4ba8d]::creader::CrateLoader>::load
  28:     0xfffefc2b0258 - <rustc_metadata[7162c47c71e4ba8d]::creader::CrateLoader>::maybe_resolve_crate
  29:     0xfffefc2afc84 - <rustc_metadata[7162c47c71e4ba8d]::creader::CrateLoader>::resolve_crate
  30:     0xfffefc2b5120 - <rustc_metadata[7162c47c71e4ba8d]::creader::CrateLoader>::process_extern_crate
  31:     0xfffefb03b24c - <rustc_resolve[e3a01cdf7257919b]::Resolver>::crate_loader::<core[1b6b982d7ada3f37]::option::Option<rustc_span[1d49b60665cf04bc]::def_id::CrateNum>, <rustc_resolve[e3a01cdf7257919b]::build_reduced_graph::BuildReducedGraphVisitor>::build_reduced_graph_for_extern_crate::{closure#0}>
  32:     0xfffefb0f31d8 - <rustc_resolve[e3a01cdf7257919b]::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast[53987b6f060c4fe4]::visit::Visitor>::visit_item
  33:     0xfffefb0b0614 - <rustc_expand[8a88420e6c275050]::expand::AstFragment>::visit_with::<rustc_resolve[e3a01cdf7257919b]::build_reduced_graph::BuildReducedGraphVisitor>
  34:     0xfffefb02e280 - <rustc_resolve[e3a01cdf7257919b]::Resolver as rustc_expand[8a88420e6c275050]::base::ResolverExpand>::visit_ast_fragment_with_placeholders
  35:     0xfffefc453f74 - <rustc_expand[8a88420e6c275050]::expand::MacroExpander>::collect_invocations
  36:     0xfffefc450a28 - <rustc_expand[8a88420e6c275050]::expand::MacroExpander>::fully_expand_fragment
  37:     0xfffefc4506f8 - <rustc_expand[8a88420e6c275050]::expand::MacroExpander>::expand_crate
  38:     0xfffef79380e4 - <rustc_session[84b1c42dc2c974d9]::session::Session>::time::<rustc_ast[53987b6f060c4fe4]::ast::Crate, rustc_interface[f578fb5164e7a136]::passes::configure_and_expand::{closure#1}>
  39:     0xfffef78fb228 - rustc_interface[f578fb5164e7a136]::passes::resolver_for_lowering_raw
  40:     0xfffefb6c1800 - rustc_query_impl[3b5bb93936467e5e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[3b5bb93936467e5e]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a3590e6fea2b3fb8]::query::erase::Erased<[u8; 16usize]>>
  41:     0xfffefb76de8c - <rustc_query_impl[3b5bb93936467e5e]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[1b6b982d7ada3f37]::ops::function::FnOnce<(rustc_middle[a3590e6fea2b3fb8]::ty::context::TyCtxt, ())>>::call_once
  42:     0xfffefb91be60 - rustc_query_system[207a0c77f1d940c6]::query::plumbing::try_execute_query::<rustc_query_impl[3b5bb93936467e5e]::DynamicConfig<rustc_query_system[207a0c77f1d940c6]::query::caches::SingleCache<rustc_middle[a3590e6fea2b3fb8]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[3b5bb93936467e5e]::plumbing::QueryCtxt, true>
  43:     0xfffefb829644 - rustc_query_impl[3b5bb93936467e5e]::query_impl::resolver_for_lowering_raw::get_query_incr::__rust_end_short_backtrace
  44:     0xfffefc70a90c - <rustc_middle[a3590e6fea2b3fb8]::ty::context::TyCtxt>::resolver_for_lowering
  45:     0xfffef77070a8 - <rustc_middle[a3590e6fea2b3fb8]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[5695a40b5d0389e1]::run_compiler::{closure#0}::{closure#1}::{closure#2}, &rustc_data_structures[2bc7bc38e9d68cc7]::steal::Steal<(rustc_middle[a3590e6fea2b3fb8]::ty::ResolverAstLowering, alloc[dfc5dab200d34227]::sync::Arc<rustc_ast[53987b6f060c4fe4]::ast::Crate>)>>
  46:     0xfffef773ef04 - <rustc_interface[f578fb5164e7a136]::interface::Compiler>::enter::<rustc_driver_impl[5695a40b5d0389e1]::run_compiler::{closure#0}::{closure#1}, core[1b6b982d7ada3f37]::result::Result<core[1b6b982d7ada3f37]::option::Option<rustc_interface[f578fb5164e7a136]::queries::Linker>, rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>
  47:     0xfffef772296c - <scoped_tls[8afa965b579d2ead]::ScopedKey<rustc_span[1d49b60665cf04bc]::SessionGlobals>>::set::<rustc_interface[f578fb5164e7a136]::util::run_in_thread_with_globals<rustc_interface[f578fb5164e7a136]::util::run_in_thread_pool_with_globals<rustc_interface[f578fb5164e7a136]::interface::run_compiler<core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>, rustc_driver_impl[5695a40b5d0389e1]::run_compiler::{closure#0}>::{closure#1}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>
  48:     0xfffef7710f30 - rustc_span[1d49b60665cf04bc]::create_session_globals_then::<core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>, rustc_interface[f578fb5164e7a136]::util::run_in_thread_with_globals<rustc_interface[f578fb5164e7a136]::util::run_in_thread_pool_with_globals<rustc_interface[f578fb5164e7a136]::interface::run_compiler<core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>, rustc_driver_impl[5695a40b5d0389e1]::run_compiler::{closure#0}>::{closure#1}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
  49:     0xfffef772a080 - std[34db25d220dbc32c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f578fb5164e7a136]::util::run_in_thread_with_globals<rustc_interface[f578fb5164e7a136]::util::run_in_thread_pool_with_globals<rustc_interface[f578fb5164e7a136]::interface::run_compiler<core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>, rustc_driver_impl[5695a40b5d0389e1]::run_compiler::{closure#0}>::{closure#1}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>
  50:     0xfffef772b0e0 - <<std[34db25d220dbc32c]::thread::Builder>::spawn_unchecked_<rustc_interface[f578fb5164e7a136]::util::run_in_thread_with_globals<rustc_interface[f578fb5164e7a136]::util::run_in_thread_pool_with_globals<rustc_interface[f578fb5164e7a136]::interface::run_compiler<core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>, rustc_driver_impl[5695a40b5d0389e1]::run_compiler::{closure#0}>::{closure#1}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1b6b982d7ada3f37]::result::Result<(), rustc_span[1d49b60665cf04bc]::ErrorGuaranteed>>::{closure#2} as core[1b6b982d7ada3f37]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  51:     0xfffef6ad3924 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h277e36f51d4f9e13
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/alloc/src/boxed.rs:2022:9
  52:     0xfffef6ad3924 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6a7d913526d04fc8
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/alloc/src/boxed.rs:2022:9
  53:     0xfffef6ad3924 - std::sys::pal::unix::thread::Thread::new::thread_start::hb554918c2e0d6e40
                               at /rustc/d2d24e395a1e4fcee62ca17bf4cbddb1f903af97/library/std/src/sys/pal/unix/thread.rs:108:17
  54:     0xfffef68f0584 - start_thread
  55:     0xfffef695fecc - thread_start
  56:                0x0 - <unknown>
```

**Comment by saethlin** [comment]
This looks like a corrupt rmeta section on disk, not a bug in the compiler. Sometimes the compiler produces corrupt files, but more often something else (another program or a buggy filesystem) has damaged the file, and the compiler has no handling for that scenario.

I'm working on improving this whole general situation, but basically right now you need to manually unstick your setup. You should purge any sort of global caching you're using like `sccache` or a shared `CARGO_TARGET_DIR` and uninstall then reinstall the errant nightly toolchain.

**Comment by mrhh69** [comment]
Thanks, wiping the toolchain and reinstalling worked! I'll close this issue because it is fixed for me.
