### ISSUE TITLE
hang in parser::diagnostics::expected_one_of_not_found()

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#124897]
### Code

I tried this code:

```rust
trait TraitA<'a, 'b, 'c> { type AsA; }
trait TraitB<'a, 'b> { type AsB; }
trait TraitC<'a, 'b, 'c> {}
struct X;
struct Y;
struct Z;

fn foo<T>() where for<const N: u8 = { T::<0>::A as u8 + TraitB<'a, 'b, AsB: for<'c> TraitC<'a, 'b, 'c>>::B as u8 }> T: TraitA<'a, AsA: for<'b> TraitB<'a, 'b, AsB: for<'c> TraitC<'a, 'b, 'c>>> {}

fn main() {}
```
on stable 1.78.0, this checks in 0.02 seconds.
on beta 1.79.0-beta.3, this hangs somewhere in `parser::diagnostics::expected_one_of_not_found()`, I killed it after 5 minutes of no progress.

**Comment by lqd** [comment]
#124169 cc @compiler-errors

**Comment by matthiaskrgr** [comment]
:thinking:  that doesn't really seem to be it
```
#0  0x00007ffff16a5ebe in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff16ab0e3 in ?? () from /usr/lib/libc.so.6
#2  0x00007ffff7f59911 in std::sys::pal::unix::thread::Thread::join () at library/std/src/sys/pal/unix/thread.rs:272
#3  0x00007ffff69363eb in rustc_driver_impl::run_compiler () from /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-baba34ae40c356f7.so
#4  0x00007ffff693512a in rustc_driver_impl::main () from /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-baba34ae40c356f7.so
#5  0x000055555556dc17 in rustc_main::main ()
#6  0x000055555556dc03 in std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()> ()
#7  0x000055555556dbf9 in <std::rt::lang_start<()>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} ()
#8  0x00007ffff7f31a7d in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at library/core/src/ops/function.rs:284
#9  std::panicking::try::do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at library/std/src/panicking.rs:559
#10 std::panicking::try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at library/std/src/panicking.rs:523
#11 std::panic::catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at library/std/src/panic.rs:149
#12 std::rt::lang_start_internal::{closure#2} () at library/std/src/rt.rs:141
#13 std::panicking::try::do_call<std::rt::lang_start_internal::{closure_env#2}, isize> () at library/std/src/panicking.rs:559
#14 std::panicking::try<isize, std::rt::lang_start_internal::{closure_env#2}> () at library/std/src/panicking.rs:523
#15 std::panic::catch_unwind<std::rt::lang_start_internal::{closure_env#2}, isize> () at library/std/src/panic.rs:149
#16 std::rt::lang_start_internal () at library/std/src/rt.rs:141
#17 0x000055555556dd47 in main ()
```

**Comment by compiler-errors** [comment]
You need to switch to like thread 2 or 3 if you're doing this in gdb

**Comment by lqd** [comment]
```
(gdb) where
#0  0x00007ffff5e3bd36 in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#1  0x00007ffff5e3c22e in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#2  0x00007ffff5e3c200 in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#3  0x00007ffff5e3c200 in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#4  0x00007ffff5e3c22e in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#5  0x00007ffff5e3c200 in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#6  0x00007ffff5e3c200 in _RINvNtNtCs3F8Jha18Tk_4core5slice4sort7recurseTNtNtCstuQ0eX0Bta_5alloc6string6StringjENvYBH_NtNtB6_3cmp10PartialOrd2ltECsas5oqsEyxam_11rustc_parse.llvm.17088249821402055010 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#7  0x00007ffff5d6facd in _RNvMs7_NtNtCsas5oqsEyxam_11rustc_parse6parser11diagnosticsNtB7_6Parser25expected_one_of_not_found.llvm.1155081324615980392 ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#8  0x00007ffff5e1234a in <rustc_parse::parser::Parser>::expect_one_of () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#9  0x00007ffff5d78a4c in <rustc_parse::parser::Parser>::check_mistyped_turbofish_with_multiple_type_params () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#10 0x00007ffff5e04a0d in <rustc_parse::parser::Parser>::parse_full_stmt () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#11 0x00007ffff5e03a5b in <rustc_parse::parser::Parser>::parse_block_tail () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#12 0x00007ffff5e03884 in <rustc_parse::parser::Parser>::parse_block_common () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#13 0x00007ffff5da93b1 in <rustc_parse::parser::Parser>::parse_expr_block () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#14 0x00007ffff5dfd1bc in <rustc_parse::parser::Parser>::parse_const_arg () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#15 0x00007ffff5dbd2b1 in <rustc_parse::parser::Parser>::parse_const_param () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#16 0x00007ffff5dbebb3 in <rustc_parse::parser::Parser>::parse_generic_params::{closure#0} () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#17 0x00007ffff5dbda5a in <rustc_parse::parser::Parser>::parse_generic_params () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#18 0x00007ffff5e11232 in <rustc_parse::parser::Parser>::parse_late_bound_lifetime_defs () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#19 0x00007ffff5dc1bd5 in <rustc_parse::parser::Parser>::parse_ty_where_predicate () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#20 0x00007ffff5dc0d2d in <rustc_parse::parser::Parser>::parse_where_clause_common () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#21 0x00007ffff5ddd17b in <rustc_parse::parser::Parser>::parse_fn () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#22 0x00007ffff5dc54c1 in <rustc_parse::parser::Parser>::parse_item_kind () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#23 0x00007ffff5dc3e2e in <rustc_parse::parser::Parser>::parse_item_common () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#24 0x00007ffff5dc36b6 in <rustc_parse::parser::Parser>::parse_item_ () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#25 0x00007ffff5dc2ed2 in <rustc_parse::parser::Parser>::parse_mod () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#26 0x00007ffff5e57724 in rustc_parse::parse_crate_from_file () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#27 0x00007ffff2fb7c56 in <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::diagnostic::Diag>, rustc_interface::passes::parse::{closure#0}> ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#28 0x00007ffff2f73900 in rustc_interface::passes::parse () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#29 0x00007ffff30058ba in <rustc_interface::queries::Queries>::parse () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#30 0x00007ffff2cd90d2 in <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>> () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#31 0x00007ffff2d71f48 in <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>> ()
   from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#32 0x00007ffff2d3f4ac in rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}> () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#33 0x00007ffff2d5e742 in _RINvNtNtCs69hc0yIuJnT_3std10sys_common9backtrace28___rust_begin_short_backtraceNCNCINvNtCs16xyWfNkGXi_15rustc_interface4util26run_in_thread_with_globalsNCINvB1m_31run_in_thread_pool_with_globalsNCINvNtB1o_9interface12run_compilerINtNtCs3F8Jha18Tk_4core6result6ResultuNtCs2Po303rOvog_10rustc_span15ErrorGuaranteedENCNvCsibkQhQqy7rQ_17rustc_driver_impl12run_compiler0Es_0B3F_E0B3F_E00B3F_EB55_.llvm.10632995656702153844 () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
--Type <RET> for more, q to quit, c to continue without paging--c
#34 0x00007ffff2d7b70a in <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#2} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} () from /checkout/obj/install/bin/../lib/librustc_driver-a38047290982a239.so
#35 0x00007ffff1f494d4 in std::sys::pal::unix::thread::Thread::new::thread_start () from /checkout/obj/install/bin/../lib/libstd-0062bd36a972ae2a.so
#36 0x00007ffff1d16ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#37 0x00007ffff1da8850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by compiler-errors** [comment]
Minimal:

```
fn foo() {
    let x = Tr<A, A:>;
}

fn main() {}
```
