### ISSUE TITLE
`cargo test`: `thread 'coordinator' panicked at compiler\rustc_middle\src\util\bug.rs:36:26:` when building on a drive with low storage

### ISSUE THREAD

**Issue by rscarson** [rust-lang/rust#125496]
Version: `cargo 1.78.0 (54d8815d0 2024-03-26)`

If my drive reaches 0 bytes available during the build I get a pair of errors; 

the below, from `rustc`:
```
thread 'coordinator' panicked at compiler\rustc_middle\src\util\bug.rs:36:26:
/rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\compiler\rustc_codegen_ssa\src\back\write.rs:1617:29: worker thread panicked
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.78.0 (9b00956e5 2024-04-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: cached cgu 581luizzqw65xw1h should have an object file, but doesn't

```

As well as
```
          LINK : warning LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
          LINK : fatal error LNK1318: Unexpected PDB error; OK (0) ''
```
          
 From the linker

**Comment by rscarson** [comment]
Too add to this; Sometimes I get only the `link.exe` error without the rustic crash

Seems rustc sometimes corrupts the PDB without being able to detect it

**Comment by saethlin** [comment]
There should have been another panic message printed as well; unfortunately this part of the compiler has a cascading multi-panic exit if one of the threads involved panics. The important panic is at the top, if there is an important one.

**Comment by saethlin** [comment]
Ah!

I think there's some code in the compiler that can't tell the difference between a fatal error and a panic. I specifically tried to make this _just_ a fatal error instead of an ICE, because the target directory state produced by a previous compiler run is invalid because a previous compilation ran out of disk space.

It looks like `emit_fatal` is perhaps not firm enough to terminate the compiler immediately. Hm.
