### ISSUE TITLE
rustc 1.80.0-nightly crash

### ISSUE THREAD

**Issue by rainliu** [rust-lang/rust#125934]
### Code

https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
  nightly-x86_64-unknown-linux-gnu installed - rustc 1.80.0-nightly (032af18af 2024-06-02)
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/dependency_format.rs:352:24:
index out of bounds: the len is 202 but the index is 212
stack backtrace:
   0:     0x7fc4c40d1cc5 - std::backtrace_rs::backtrace::libunwind::trace::haf0e753fffc1b5a5
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7fc4c40d1cc5 - std::backtrace_rs::backtrace::trace_unsynchronized::h70f82ab6a4db8cdf
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc4c40d1cc5 - std::sys_common::backtrace::_print_fmt::h5a6fce4ae01b1105
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7fc4c40d1cc5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1fa2920817bbbd09
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fc4c412246b - core::fmt::rt::Argument::fmt::h5f219a6468ec2c71
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/fmt/rt.rs:165:63
   5:     0x7fc4c412246b - core::fmt::write::h6731ff0b9c7b8ce8
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/fmt/mod.rs:1168:21
   6:     0x7fc4c40c6a4f - std::io::Write::write_fmt::hc4268973d8ae94c7
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/io/mod.rs:1835:15
   7:     0x7fc4c40d1a9e - std::sys_common::backtrace::_print::h419656dfbbb87639
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fc4c40d1a9e - std::sys_common::backtrace::print::h09b2[559](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:560)5eb301343
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fc4c40d44d9 - std::panicking::default_hook::{{closure}}::hf9ba49d7e1e5f023
  10:     0x7fc4c40d427a - std::panicking::default_hook::heea03dc93b69d475
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:298:9
  11:     0x7fc4c094403f - std[69052015ce1b7124]::panicking::update_hook::<alloc[f5014be2e767fdd]::boxed::Box<rustc_driver_impl[1b537cd12afd42a4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fc4c40d4c0b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6a19a53d0d9b021a
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2077:9
  13:     0x7fc4c40d4c0b - std::panicking::rust_panic_with_hook::h642286663fe7c96b
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:799:13
  14:     0x7fc4c40d4984 - std::panicking::begin_panic_handler::{{closure}}::h7ce4f616ce330fa6
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:664:13
  15:     0x7fc4c40d2189 - std::sys_common::backtrace::__rust_end_short_backtrace::h7035c7c2ee90efed
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fc4c40d46b7 - rust_begin_unwind
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:652:5
  17:     0x7fc4c411ea03 - core::panicking::panic_fmt::h3ec5d1efb44b5034
                               at /rustc/032af18af[578](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:579)f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:72:14
  18:     0x7fc4c411ec17 - core::panicking::panic_bounds_check::hde89ae76313212b4
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:274:5
  19:     0x7fc4c291a746 - <rustc_metadata[5adcf685f19e3a97]::rmeta::decoder::cstore_impl::provide::{closure#5} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, ())>>::call_once
  20:     0x7fc4c2c1940d - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7fc4c2c154d2 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::SingleCache<rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  22:     0x7fc4c2c14d5e - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7fc4c2c162a5 - rustc_codegen_ssa[d59740cb733497b7]::base::allocator_kind_for_codegen
  24:     0x7fc4c2911e05 - rustc_codegen_ssa[d59740cb733497b7]::back::symbol_export::exported_symbols_provider_local
  25:     0x7fc4c1f48e33 - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7fc4c1f48e09 - <rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, rustc_span[edacdd56afd4fe4e]::def_id::CrateNum)>>::call_once
  27:     0x7fc4c2a91371 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  28:     0x7fc4c2a90f6b - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7fc4c2a91023 - rustc_middle[8bb46b904fcf8bdf]::query::plumbing::query_get_at::<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>>
  30:     0x7fc4c291486d - <rustc_codegen_ssa[d59740cb733497b7]::CrateInfo>::new
  31:     0x7fc4c2b23ba0 - rustc_codegen_ssa[d59740cb733497b7]::back::write::start_async_codegen::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  32:     0x7fc4c2cffb83 - rustc_codegen_ssa[d59740cb733497b7]::base::codegen_crate::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  33:     0x7fc4c2cf344c - <rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend as rustc_codegen_ssa[d59740cb733497b7]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7fc4c2cf2ddf - rustc_interface[c4543bcf07cd468e]::passes::start_codegen
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fabad78aa9e - std::sys_common::backtrace::print::h09b25[595](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:596)eb301343
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fabad78d4d9 - std::panicking::default_hook::{{closure}}::hf9ba49d7e1e5f023
  10:     0x7fabad78d27a - std::panicking::default_hook::heea03dc93b69d475
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:298:9
  11:     0x7fabb094403f - std[69052015ce1b7124]::panicking::update_hook::<alloc[f5014be2e767fdd]::boxed::Box<rustc_driver_impl[1b537cd12afd42a4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fabad78dc0b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6a19a53d0d9b021a
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2077:9
  13:     0x7fabad78dc0b - std::panicking::rust_panic_with_hook::h642286663fe7c96b
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:799:13
  14:     0x7fabad78d984 - std::panicking::begin_panic_handler::{{closure}}::h7ce4f616ce330fa6
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:664:13
  15:     0x7fabad78b189 - std::sys_common::backtrace::__rust_end_short_backtrace::h7035c7c2ee90efed
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7fabad78d6b7 - rust_begin_unwind
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/panicking.rs:652:5
  17:     0x7fabad7d7a03 - core::panicking::panic_fmt::h3ec5d1efb44b5034
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:72:14
  18:     0x7fabad7d7c17 - core::panicking::panic_bounds_check::hde89ae76313212b4
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/core/src/panicking.rs:274:5
  19:     0x7fabb291a746 - <rustc_metadata[5adcf685f19e3a97]::rmeta::decoder::cstore_impl::provide::{closure#5} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, ())>>::call_once
  20:     0x7fabb2c1940d - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7fabb2c154d2 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::SingleCache<rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  22:     0x7fabb2c14d5e - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::dependency_formats::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7fabb2c162a5 - rustc_codegen_ssa[d[597](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:598)40cb733497b7]::base::allocator_kind_for_codegen
  24:     0x7fabb2911e05 - rustc_codegen_ssa[d59740cb733497b7]::back::symbol_export::exported_symbols_provider_local
  25:     0x7fabb1f48e33 - rustc_query_impl[75ba70ce79c8d8ef]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7fabb1f48e09 - <rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::dynamic_query::{closure#2} as core[57dce0d7678ad3a0]::ops::function::FnOnce<(rustc_middle[8bb46b904fcf8bdf]::ty::context::TyCtxt, rustc_span[edacdd56afd4fe4e]::def_id::CrateNum)>>::call_once
  27:     0x7fabb2a91371 - rustc_query_system[5ea179786410f179]::query::plumbing::try_execute_query::<rustc_query_impl[75ba70ce79c8d8ef]::DynamicConfig<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[75ba70ce79c8d8ef]::plumbing::QueryCtxt, false>
  28:     0x7fabb2a90f6b - rustc_query_impl[75ba70ce79c8d8ef]::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7fabb2a91023 - rustc_middle[8bb46b904fcf8bdf]::query::plumbing::query_get_at::<rustc_query_system[5ea179786410f179]::query::caches::VecCache<rustc_span[edacdd56afd4fe4e]::def_id::CrateNum, rustc_middle[8bb46b904fcf8bdf]::query::erase::Erased<[u8; 16usize]>>>
  30:     0x7fabb291486d - <rustc_codegen_ssa[d59740cb733497b7]::CrateInfo>::new
  31:     0x7fabb2b23ba0 - rustc_codegen_ssa[d59740cb733497b7]::back::write::start_async_codegen::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  32:     0x7fabb2cffb83 - rustc_codegen_ssa[d59740cb733497b7]::base::codegen_crate::<rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend>
  33:     0x7fabb2cf344c - <rustc_codegen_llvm[c02d8eeada8a187]::LlvmCodegenBackend as rustc_codegen_ssa[d59740cb733497b7]::traits::backend::CodegenBackend>::codegen_crate
  34:     0x7fabb2cf2ddf - rustc_interface[c4543bcf07cd468e]::passes::start_codegen
  35:     0x7fabb2cf245a - <rustc_interface[c4543bcf07cd468e]::queries::Queries>::codegen_and_build_linker
  36:     0x7fabb2a7f140 - rustc_interface[c4543bcf07cd468e]::interface::run_compiler::<core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>, rustc_driver_impl[1b537cd12afd42a4]::run_compiler::{closure#0}>::{closure#1}
  37:     0x7fabb2a400c9 - std[69052015ce1b7124]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_with_globals<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_pool_with_globals<rustc_interface[c4543bcf07cd468e]::interface::run_compiler<core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>, rustc_driver_impl[1b537cd12afd42a4]::run_compiler::{closure#0}>::{closure#1}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>
  38:     0x7fabb2a3fe86 - <<std[69052015ce1b7124]::thread::Builder>::spawn_unchecked_<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_with_globals<rustc_interface[c4543bcf07cd468e]::util::run_in_thread_pool_with_globals<rustc_interface[c4543bcf07cd468e]::interface::run_compiler<core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>, rustc_driver_impl[1b537cd12afd42a4]::run_compiler::{closure#0}>::{closure#1}, core[57dce0d7[678](https://github.com/webrtc-rs/webrtc/actions/runs/9354666974/job/25748024701#step:5:679)ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[57dce0d7678ad3a0]::result::Result<(), rustc_span[edacdd56afd4fe4e]::ErrorGuaranteed>>::{closure#2} as core[57dce0d7678ad3a0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7fabad797bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0eb2bde6064def81
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2063:9
  40:     0x7fabad797bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcdb0204268e0604a
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/alloc/src/boxed.rs:2063:9
  41:     0x7fabad797bfb - std::sys::pal::unix::thread::Thread::new::thread_start::hd7ebf2795d4ccec5
                               at /rustc/032af18af578f4283a2927fb43b90df2bbb72b67/library/std/src/sys/pal/unix/thread.rs:108:17
  42:     0x7fabad494ac3 - <unknown>
  43:     0x7fabad526850 - <unknown>
  44:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.
Error: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/runner/work/webrtc/webrtc/rustc-ice-2024-06-03T17_34_57-18114.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -Z profile -C codegen-units=1 -C opt-level=0 -C link-dead-code -C overflow-checks=off -Z panic_abort_tests -C panic=abort -C debug-assertions=off

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [dependency_formats] getting the linkage format of all dependencies
#1 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
error: could not compile `examples` (example "play-from-disk-renegotiation")
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by lqd** [comment]
While the stacktrace is different, I believe this to have the same cause as #125474 (and bisects to #124976 indeed cc @petrochenkov) and its other duplicates. It should also be fixed by #125493. I can reproduce the error on nightly, but not on my #125493 branch.
