### ISSUE TITLE
Compiler crash with extensive use of const generics

### ISSUE THREAD

**Issue by shosti** [rust-lang/rust#126078]
### Code

I'm not sure where to start in terms of a minimal example, but the relevant code is https://github.com/shosti/tensrus/tree/compiler-bug (reproducible with `cargo test`). The code makes extensive use of `adt_const_params` and `generic_const_exprs`.

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (72fdf913c 2024-06-05)
binary: rustc
commit-hash: 72fdf913c53dd0e75313ba83e4aa80df3f6e2871
commit-date: 2024-06-05
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

```
   Compiling tensrus v0.1.0 (/Users/shosti/src/tensrus)
error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:510:25: failed to resolve instance for <generic_tensor::GenericTensor<f64, 2, [2, 3, 0, 0, 0, 0]> as Add<view::View<'_, generic_tensor::GenericTensor<f64, 2, [2, 3, 0, 0, 0, 0]>>>>::add: Ok(
                                    None,
                                )

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling tensrus v0.1.0 (/Users/shosti/src/tensrus)
error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:510:25: failed to resolve instance for <generic_tensor::GenericTensor<f64, 2, [2, 3, 0, 0, 0, 0]> as Add<view::View<'_, generic_tensor::GenericTensor<f64, 2, [2, 3, 0, 0, 0, 0]>>>>::add: Ok(
                                    None,
                                )

thread 'rustc' panicked at compiler/rustc_middle/src/ty/instance.rs:510:25:
Box<dyn Any>
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::diagnostic::BugAbort as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   2: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   3: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   5: rustc_middle::util::bug::bug_fmt
   6: <rustc_middle::ty::instance::Instance>::expect_resolve
   7: <rustc_monomorphize::collector::MirUsedCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
   8: rustc_monomorphize::collector::collect_items_of_instance
   9: rustc_monomorphize::collector::collect_items_rec
  10: rustc_monomorphize::collector::collect_items_rec
  11: rustc_monomorphize::collector::collect_items_rec
  12: rustc_monomorphize::collector::collect_items_rec
  13: rustc_monomorphize::collector::collect_items_rec
  14: rustc_monomorphize::collector::collect_items_rec
  15: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
  16: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in<rustc_middle::mir::mono::MonoItem, alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
  17: <rustc_session::session::Session>::time::<(), rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}>
  18: rustc_monomorphize::collector::collect_crate_mono_items
  19: rustc_monomorphize::partitioning::collect_and_partition_mono_items
      [... omitted 2 frames ...]
  20: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  21: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  22: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  23: rustc_interface::passes::start_codegen
  24: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::codegen_and_build_linker::{closure#0}, core::result::Result<rustc_interface::queries::Linker, rustc_span::ErrorGuaranteed>>
  25: <rustc_interface::queries::Queries>::codegen_and_build_linker
  26: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/Users/shosti/src/tensrus/rustc-ice-2024-06-06T15_38_19-35349.txt` to your bug report

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `tensrus` (lib test)

```

</p>
</details>

[rustc-ice-2024-06-06T15_38_19-35349.txt](https://github.com/user-attachments/files/15648221/rustc-ice-2024-06-06T15_38_19-35349.txt)

**Comment by workingjubilee** [comment]
Sorry but this is an incomplete feature, so this is a known problem!

If you can extract a minimized version, that would be great!

**Comment by pacak** [comment]
A smaller example with no dependencies other than stdlib

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=97c639b3e948103bea86d71f16bfc9c9

**Comment by pacak** [comment]
```rust
#![feature(generic_const_exprs)]
trait Tensor {
    const S: usize;
}

struct GenericTensor<const S: usize>;

impl<const S: usize> Tensor for GenericTensor<S> {
    const S: usize = S;
}

impl<const S: usize, Rhs> std::ops::Add<Rhs> for GenericTensor<S>
where
    View<Self>: From<Rhs>,
{
    type Output = ();
    fn add(self, _: Rhs) -> Self::Output {}
}

fn x<const S: usize, A, B>(a: A, b: B) where
View<A>: From<B> {
}

struct ElemAddOp<const S: usize>;

impl<const S: usize> ElemAddOp<S> {
    fn forward(&self) {
        GenericTensor::<S> + View(GenericTensor);
    }
}

pub fn test_bcast_elem_add() {
    (ElemAddOp::<0>).forward()
}

struct View<T>(T);

impl<Tn> From<View<GenericTensor<{ Tn::S }>>> for View<Tn>
where
    Tn: Tensor,
{
    fn from(_: View<GenericTensor<{ Tn::S }>>) -> Self {
        loop {}
    }
}
```

**Comment by workingjubilee** [comment]
neat!

**Comment by theemathas** [comment]
Minimized further:

```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

trait Array {
    const SIZE: usize;
}
impl<const N: usize> Array for [i32; N] {
    const SIZE: usize = N;
}

// Note: Overlapping impls not detected by compiler
trait Reflexive<T> {
    fn reflexive() {}
}
impl<T> Reflexive<T> for T {}
impl<A: Array> Reflexive<[i32; A::SIZE]> for A {}

fn do_reflexive<const N: usize>() {
    <[i32; N]>::reflexive();
}
// Note: Load-bearing `pub`. Removing the pub stops the ICE.
pub fn what() {
    do_reflexive::<0>()
}
```

<details>
<summary>Compiler error</summary>

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: compiler/rustc_middle/src/ty/instance.rs:510:25: failed to resolve instance for <[i32; 0] as Reflexive<[i32; 0]>>::reflexive: Ok(
                                    None,
                                )

thread 'rustc' panicked at compiler/rustc_middle/src/ty/instance.rs:510:25:
Box<dyn Any>
stack backtrace:
   0:     0x7f5499f58f15 - std::backtrace_rs::backtrace::libunwind::trace::h7d3c800091db3e91
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f5499f58f15 - std::backtrace_rs::backtrace::trace_unsynchronized::h4cc0a280c32586b8
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5499f58f15 - std::sys_common::backtrace::_print_fmt::h9005d7a683a6d7a4
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f5499f58f15 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h519c17d5956798a6
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5499fa9c5b - core::fmt::rt::Argument::fmt::haa193bfc28a485eb
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/core/src/fmt/rt.rs:165:63
   5:     0x7f5499fa9c5b - core::fmt::write::h355a93f02c4b3ea1
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/core/src/fmt/mod.rs:1168:21
   6:     0x7f5499f4dc9f - std::io::Write::write_fmt::hbe0fd00858f9c1ec
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/io/mod.rs:1835:15
   7:     0x7f5499f58cee - std::sys_common::backtrace::_print::h7fe7f477e21fa361
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5499f58cee - std::sys_common::backtrace::print::h6c8dafcb53369ea1
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f5499f5b729 - std::panicking::default_hook::{{closure}}::hbcbc771124e8a531
  10:     0x7f5499f5b4ca - std::panicking::default_hook::ha99c0605f25db782
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/panicking.rs:298:9
  11:     0x7f549d1a4a00 - std[59958118404e088f]::panicking::update_hook::<alloc[25fe46b0aaca8953]::boxed::Box<rustc_driver_impl[2627b6be84d2f0c]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f5499f5be5b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4e37e0de343f25a5
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/alloc/src/boxed.rs:2077:9
  13:     0x7f5499f5be5b - std::panicking::rust_panic_with_hook::h6b51162bdfe57bbe
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/panicking.rs:799:13
  14:     0x7f549d1d5224 - std[59958118404e088f]::panicking::begin_panic::<rustc_errors[2ff0989c1584c7c0]::ExplicitBug>::{closure#0}
  15:     0x7f549d1d1d06 - std[59958118404e088f]::sys_common::backtrace::__rust_end_short_backtrace::<std[59958118404e088f]::panicking::begin_panic<rustc_errors[2ff0989c1584c7c0]::ExplicitBug>::{closure#0}, !>
  16:     0x7f549d1cd116 - std[59958118404e088f]::panicking::begin_panic::<rustc_errors[2ff0989c1584c7c0]::ExplicitBug>
  17:     0x7f549d1de841 - <rustc_errors[2ff0989c1584c7c0]::diagnostic::BugAbort as rustc_errors[2ff0989c1584c7c0]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f549d6bb04c - rustc_middle[ce3fbd8192a3c5ff]::util::bug::opt_span_bug_fmt::<rustc_span[6bc65aeac19990f8]::span_encoding::Span>::{closure#0}
  19:     0x7f549d6a487a - rustc_middle[ce3fbd8192a3c5ff]::ty::context::tls::with_opt::<rustc_middle[ce3fbd8192a3c5ff]::util::bug::opt_span_bug_fmt<rustc_span[6bc65aeac19990f8]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f549d6a46fb - rustc_middle[ce3fbd8192a3c5ff]::ty::context::tls::with_context_opt::<rustc_middle[ce3fbd8192a3c5ff]::ty::context::tls::with_opt<rustc_middle[ce3fbd8192a3c5ff]::util::bug::opt_span_bug_fmt<rustc_span[6bc65aeac19990f8]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f549bb5dd70 - rustc_middle[ce3fbd8192a3c5ff]::util::bug::bug_fmt
  22:     0x7f549eb00f42 - <rustc_middle[ce3fbd8192a3c5ff]::ty::instance::Instance>::expect_resolve
  23:     0x7f549f3f7d5f - rustc_monomorphize[b056ba09cdf9a699]::collector::collect_items_rec::{closure#0}
  24:     0x7f549e66637f - rustc_monomorphize[b056ba09cdf9a699]::collector::collect_items_rec
  25:     0x7f549e666af6 - rustc_monomorphize[b056ba09cdf9a699]::collector::collect_items_rec
  26:     0x7f549effee27 - rustc_monomorphize[b056ba09cdf9a699]::partitioning::collect_and_partition_mono_items
  27:     0x7f549f3d3364 - rustc_query_impl[9fa61a5fc93b94b6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9fa61a5fc93b94b6]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ce3fbd8192a3c5ff]::query::erase::Erased<[u8; 24usize]>>
  28:     0x7f549f3d3349 - <rustc_query_impl[9fa61a5fc93b94b6]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2} as core[666eafb1203b88c6]::ops::function::FnOnce<(rustc_middle[ce3fbd8192a3c5ff]::ty::context::TyCtxt, ())>>::call_once
  29:     0x7f549f3d2f08 - rustc_query_system[8cc4c292d92d3869]::query::plumbing::try_execute_query::<rustc_query_impl[9fa61a5fc93b94b6]::DynamicConfig<rustc_query_system[8cc4c292d92d3869]::query::caches::SingleCache<rustc_middle[ce3fbd8192a3c5ff]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[9fa61a5fc93b94b6]::plumbing::QueryCtxt, false>
  30:     0x7f549f3d2c21 - rustc_query_impl[9fa61a5fc93b94b6]::query_impl::collect_and_partition_mono_items::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f549f0af509 - rustc_codegen_ssa[7de31db090aae023]::back::symbol_export::exported_symbols_provider_local
  32:     0x7f549e7533a5 - rustc_query_impl[9fa61a5fc93b94b6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[9fa61a5fc93b94b6]::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ce3fbd8192a3c5ff]::query::erase::Erased<[u8; 16usize]>>
  33:     0x7f549e753373 - <rustc_query_impl[9fa61a5fc93b94b6]::query_impl::exported_symbols::dynamic_query::{closure#2} as core[666eafb1203b88c6]::ops::function::FnOnce<(rustc_middle[ce3fbd8192a3c5ff]::ty::context::TyCtxt, rustc_span[6bc65aeac19990f8]::def_id::CrateNum)>>::call_once
  34:     0x7f549f23b4b1 - rustc_query_system[8cc4c292d92d3869]::query::plumbing::try_execute_query::<rustc_query_impl[9fa61a5fc93b94b6]::DynamicConfig<rustc_query_system[8cc4c292d92d3869]::query::caches::VecCache<rustc_span[6bc65aeac19990f8]::def_id::CrateNum, rustc_middle[ce3fbd8192a3c5ff]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[9fa61a5fc93b94b6]::plumbing::QueryCtxt, false>
  35:     0x7f549f23b0ab - rustc_query_impl[9fa61a5fc93b94b6]::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f549f23adec - rustc_middle[ce3fbd8192a3c5ff]::query::plumbing::query_get_at::<rustc_query_system[8cc4c292d92d3869]::query::caches::VecCache<rustc_span[6bc65aeac19990f8]::def_id::CrateNum, rustc_middle[ce3fbd8192a3c5ff]::query::erase::Erased<[u8; 16usize]>>>
  37:     0x7f549ed6e9c0 - <rustc_metadata[d6f8184ef093beb3]::rmeta::encoder::EncodeContext>::encode_crate_root
  38:     0x7f549f5ef046 - rustc_metadata[d6f8184ef093beb3]::rmeta::encoder::encode_metadata
  39:     0x7f549f4255b2 - rustc_metadata[d6f8184ef093beb3]::fs::encode_and_write_metadata
  40:     0x7f549f42405e - rustc_interface[ed174d428a840afd]::passes::start_codegen
  41:     0x7f549f4237a8 - <rustc_interface[ed174d428a840afd]::queries::Queries>::codegen_and_build_linker
  42:     0x7f549f242332 - rustc_interface[ed174d428a840afd]::interface::run_compiler::<core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>, rustc_driver_impl[2627b6be84d2f0c]::run_compiler::{closure#0}>::{closure#1}
  43:     0x7f549f1f6009 - std[59958118404e088f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ed174d428a840afd]::util::run_in_thread_with_globals<rustc_interface[ed174d428a840afd]::util::run_in_thread_pool_with_globals<rustc_interface[ed174d428a840afd]::interface::run_compiler<core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>, rustc_driver_impl[2627b6be84d2f0c]::run_compiler::{closure#0}>::{closure#1}, core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>>::{closure#0}, core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>>
  44:     0x7f549f1f5dc0 - <<std[59958118404e088f]::thread::Builder>::spawn_unchecked_<rustc_interface[ed174d428a840afd]::util::run_in_thread_with_globals<rustc_interface[ed174d428a840afd]::util::run_in_thread_pool_with_globals<rustc_interface[ed174d428a840afd]::interface::run_compiler<core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>, rustc_driver_impl[2627b6be84d2f0c]::run_compiler::{closure#0}>::{closure#1}, core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>>::{closure#0}, core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[666eafb1203b88c6]::result::Result<(), rustc_span[6bc65aeac19990f8]::ErrorGuaranteed>>::{closure#2} as core[666eafb1203b88c6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x7f5499f65e4b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1f264a7d3d0a179d
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/alloc/src/boxed.rs:2063:9
  46:     0x7f5499f65e4b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h137c7bc9bcca4c45
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/alloc/src/boxed.rs:2063:9
  47:     0x7f5499f65e4b - std::sys::pal::unix::thread::Thread::new::thread_start::hf2fbd4f8eae045d7
                               at /rustc/804421dff5542c9c7da5c60257b5dbc849719505/library/std/src/sys/pal/unix/thread.rs:108:17
  48:     0x7f5499e73609 - start_thread
  49:     0x7f5499d96353 - clone
  50:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/playground/rustc-ice-2024-06-08T09_09_04-50.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
#1 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
error: could not compile `playground` (lib)
```
</details>

**Comment by matthiaskrgr** [comment]
Looks like a duplicate of https://github.com/rust-lang/rust/issues/119692

**Comment by workingjubilee** [comment]
Closing as duplicate then.
