### ISSUE TITLE
`thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27: index out of bounds: the len is 41 but the index is 41`

### ISSUE THREAD

**Issue by eval-exec** [rust-lang/rust#127080]
### Code
(Sorry, I can't reproduce this Error, this error occured when I'm using rust-analyzer as lsp backend to explorer a rust project codebase)

### Meta

`rustc --version --verbose`:
```
❯ rustc --version --verbose
rustc 1.80.0-nightly (bdbbb6c6a 2024-05-26)
binary: rustc
commit-hash: bdbbb6c6a718d4d196131aa16bafb60e850311d9
commit-date: 2024-05-26
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6

```

### Error output

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 41 but the index is 41
stack backtrace:
   0:     0x7f8a07a5f285 - std::backtrace_rs::backtrace::libunwind::trace::h987df5e44773aafe
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f8a07a5f285 - std::backtrace_rs::backtrace::trace_unsynchronized::h8dec5e1ffb2c6462
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8a07a5f285 - std::backtrace::Backtrace::create::h360db1a3c13f8166
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/backtrace.rs:331:13
   3:     0x7f8a07a5f1d5 - std::backtrace::Backtrace::force_capture::h2409ffa139fe82cc
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/backtrace.rs:312:9
   4:     0x7f8a044fc179 - std[6232ea12d2bfcd9b]::panicking::update_hook::<alloc[1b4638791ca5823]::boxed::Box<rustc_driver_impl[29241b62cc382467]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f8a07a7a08b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8256b2e4c3ef5395
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/alloc/src/boxed.rs:2077:9
   6:     0x7f8a07a7a08b - std::panicking::rust_panic_with_hook::h3b4bdb94a4a81709
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:799:13
   7:     0x7f8a07a79e04 - std::panicking::begin_panic_handler::{{closure}}::hc8a8fd8190f11ec9
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:664:13
   8:     0x7f8a07a77619 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c64b38918e03588
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x7f8a07a79b37 - rust_begin_unwind
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:652:5
  10:     0x7f8a07ac28f3 - core::panicking::panic_fmt::h68570b6442af3bae
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/core/src/panicking.rs:72:14
  11:     0x7f8a07ac2b07 - core::panicking::panic_bounds_check::hd3029b8e087bcb54
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/core/src/panicking.rs:274:5
  12:     0x7f8a064f8a0e - rustc_codegen_ssa[c3bff6ff8e28f812]::back::link::linker_with_args
  13:     0x7f8a0672205e - rustc_codegen_ssa[c3bff6ff8e28f812]::back::link::link_natively
  14:     0x7f8a0664e98f - rustc_codegen_ssa[c3bff6ff8e28f812]::back::link::link_binary
  15:     0x7f8a0664dea2 - <rustc_codegen_llvm[e6b15c943773d533]::LlvmCodegenBackend as rustc_codegen_ssa[c3bff6ff8e28f812]::traits::backend::CodegenBackend>::link
  16:     0x7f8a066516e4 - <rustc_interface[69523ac5def81162]::queries::Linker>::link
  17:     0x7f8a063e3769 - rustc_interface[69523ac5def81162]::interface::run_compiler::<core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>, rustc_driver_impl[29241b62cc382467]::run_compiler::{closure#0}>::{closure#1}
  18:     0x7f8a063cca89 - std[6232ea12d2bfcd9b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[69523ac5def81162]::util::run_in_thread_with_globals<rustc_interface[69523ac5def81162]::util::run_in_thread_pool_with_globals<rustc_interface[69523ac5def81162]::interface::run_compiler<core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>, rustc_driver_impl[29241b62cc382467]::run_compiler::{closure#0}>::{closure#1}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>
  19:     0x7f8a063cc848 - <<std[6232ea12d2bfcd9b]::thread::Builder>::spawn_unchecked_<rustc_interface[69523ac5def81162]::util::run_in_thread_with_globals<rustc_interface[69523ac5def81162]::util::run_in_thread_pool_with_globals<rustc_interface[69523ac5def81162]::interface::run_compiler<core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>, rustc_driver_impl[29241b62cc382467]::run_compiler::{closure#0}>::{closure#1}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#2} as core[e1dc4ef76536528]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  20:     0x7f8a07a83eeb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f3413245cb330c
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/alloc/src/boxed.rs:2063:9
  21:     0x7f8a07a83eeb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h584b65f9f9107480
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/alloc/src/boxed.rs:2063:9
  22:     0x7f8a07a83eeb - std::sys::pal::unix::thread::Thread::new::thread_start::he327f3d51af1cb92
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys/pal/unix/thread.rs:108:17
  23:     0x7f8a012a0272 - start_thread
  24:     0x7f8a0131bdec - __GI___clone3
  25:                0x0 - <unknown>


rustc version: 1.80.0-nightly (bdbbb6c6a 2024-05-26)
platform: x86_64-unknown-linux-gnu

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling tokio-util v0.7.10 (/home/exec/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-util-0.7.10)
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 41 but the index is 41
stack backtrace:
   0:     0x7f8a07a77155 - std::backtrace_rs::backtrace::libunwind::trace::h987df5e44773aafe
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f8a07a77155 - std::backtrace_rs::backtrace::trace_unsynchronized::hdbb6918bc8791ba4
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8a07a77155 - std::sys_common::backtrace::_print_fmt::h191b62db26c7e1af
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f8a07a77155 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h611323aa92eb8834
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8a07ac635b - core::fmt::rt::Argument::fmt::h9762efe50cb92faa
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/core/src/fmt/rt.rs:165:63
   5:     0x7f8a07ac635b - core::fmt::write::hf098dbbd19b38adf
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/core/src/fmt/mod.rs:1168:21
   6:     0x7f8a07a6be2f - std::io::Write::write_fmt::h2d289afe2b99fbba
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/io/mod.rs:1835:15
   7:     0x7f8a07a76f2e - std::sys_common::backtrace::_print::ha33e648b19811abf
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f8a07a76f2e - std::sys_common::backtrace::print::ha3313a7a50713f59
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f8a07a79959 - std::panicking::default_hook::{{closure}}::h5d889162db8f228d
  10:     0x7f8a07a796fa - std::panicking::default_hook::h19ecb0b1c82e9136
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:298:9
  11:     0x7f8a044fb9e0 - std[6232ea12d2bfcd9b]::panicking::update_hook::<alloc[1b4638791ca5823]::boxed::Box<rustc_driver_impl[29241b62cc382467]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f8a07a7a08b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8256b2e4c3ef5395
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/alloc/src/boxed.rs:2077:9
  13:     0x7f8a07a7a08b - std::panicking::rust_panic_with_hook::h3b4bdb94a4a81709
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:799:13
  14:     0x7f8a07a79e04 - std::panicking::begin_panic_handler::{{closure}}::hc8a8fd8190f11ec9
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:664:13
  15:     0x7f8a07a77619 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c64b38918e03588
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f8a07a79b37 - rust_begin_unwind
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/panicking.rs:652:5
  17:     0x7f8a07ac28f3 - core::panicking::panic_fmt::h68570b6442af3bae
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/core/src/panicking.rs:72:14
  18:     0x7f8a07ac2b07 - core::panicking::panic_bounds_check::hd3029b8e087bcb54
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/core/src/panicking.rs:274:5
  19:     0x7f8a064f8a0e - rustc_codegen_ssa[c3bff6ff8e28f812]::back::link::linker_with_args
  20:     0x7f8a0672205e - rustc_codegen_ssa[c3bff6ff8e28f812]::back::link::link_natively
  21:     0x7f8a0664e98f - rustc_codegen_ssa[c3bff6ff8e28f812]::back::link::link_binary
  22:     0x7f8a0664dea2 - <rustc_codegen_llvm[e6b15c943773d533]::LlvmCodegenBackend as rustc_codegen_ssa[c3bff6ff8e28f812]::traits::backend::CodegenBackend>::link
  23:     0x7f8a066516e4 - <rustc_interface[69523ac5def81162]::queries::Linker>::link
  24:     0x7f8a063e3769 - rustc_interface[69523ac5def81162]::interface::run_compiler::<core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>, rustc_driver_impl[29241b62cc382467]::run_compiler::{closure#0}>::{closure#1}
  25:     0x7f8a063cca89 - std[6232ea12d2bfcd9b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[69523ac5def81162]::util::run_in_thread_with_globals<rustc_interface[69523ac5def81162]::util::run_in_thread_pool_with_globals<rustc_interface[69523ac5def81162]::interface::run_compiler<core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>, rustc_driver_impl[29241b62cc382467]::run_compiler::{closure#0}>::{closure#1}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>
  26:     0x7f8a063cc848 - <<std[6232ea12d2bfcd9b]::thread::Builder>::spawn_unchecked_<rustc_interface[69523ac5def81162]::util::run_in_thread_with_globals<rustc_interface[69523ac5def81162]::util::run_in_thread_pool_with_globals<rustc_interface[69523ac5def81162]::interface::run_compiler<core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>, rustc_driver_impl[29241b62cc382467]::run_compiler::{closure#0}>::{closure#1}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[e1dc4ef76536528]::result::Result<(), rustc_span[1178d78475e05ce8]::ErrorGuaranteed>>::{closure#2} as core[e1dc4ef76536528]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7f8a07a83eeb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f3413245cb330c
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/alloc/src/boxed.rs:2063:9
  28:     0x7f8a07a83eeb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h584b65f9f9107480
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/alloc/src/boxed.rs:2063:9
  29:     0x7f8a07a83eeb - std::sys::pal::unix::thread::Thread::new::thread_start::he327f3d51af1cb92
                               at /rustc/bdbbb6c6a718d4d196131aa16bafb60e850311d9/library/std/src/sys/pal/unix/thread.rs:108:17
  30:     0x7f8a012a0272 - start_thread
  31:     0x7f8a0131bdec - __GI___clone3
  32:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/exec/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-util-0.7.10/rustc-ice-2024-06-28T09_42_45-1220519.txt` to your bug report

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=clang -C incremental=[REDACTED] -C link-arg=-fuse-ld=/etc/profiles/per-user/exec/bin/mold

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `tokio-util` (lib test)
{"reason":"build-finished","success":false}

Try installing a more recent version of rust-cargo, and please open a bug report if the issue persists in the latest release.  Thanks!


```

</p>
</details>

**Comment by lqd** [comment]
This should be fixed already, could you try on the latest nightly?

**Comment by eval-exec** [comment]
> This should be fixed already, could you try on the latest nightly?

I think this has be fixed already, thank you.
