### ISSUE TITLE
Crash on using any operations between two f128 in 1.80.0-nightly

### ISSUE THREAD

**Issue by celesteornato** [rust-lang/rust#127469]
### Code

```
#![feature(f128)]
fn function() -> f128 {
    1.0 as f128 - 1.0 as f128
}
fn main() {
    function();
}
```
(also crashes with addition, multiplication or division between two f128)

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (f705de596 2024-04-30)
binary: rustc
commit-hash: f705de59625bb76067a5d102edc1575ff23b8845
commit-date: 2024-04-30
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4
```

### Error output

```
thread 'rustc' panicked at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/compiler/rustc_const_eval/src/interpret/operator.rs:424:38:
not implemented: f16_f128
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/panicking.rs:72:14
   2: <rustc_const_eval::interpret::eval_context::InterpCx<rustc_const_eval::const_eval::dummy_machine::DummyMachine>>::overflowing_binary_op
   3: <rustc_mir_transform::known_panics_lint::ConstPropagator>::check_binary_op
   4: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_assign
   5: <rustc_mir_transform::known_panics_lint::ConstPropagator as rustc_middle::mir::visit::Visitor>::visit_body
   6: <rustc_mir_transform::known_panics_lint::KnownPanicsLint as rustc_mir_transform::pass_manager::MirLint>::run_lint
   7: rustc_mir_transform::pass_manager::run_passes_inner
   8: rustc_mir_transform::mir_drops_elaborated_and_const_checked
      [... omitted 1 frame ...]
   9: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  10: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

On NixOS-unstable (Linux kernel version 6.6.36)

[rustc-ice-2024-07-07T20_36_29-103491.txt](https://github.com/user-attachments/files/16120701/rustc-ice-2024-07-07T20_36_29-103491.txt)

**Comment by compiler-errors** [comment]
> rustc version: 1.80.0-nightly (f705de596 2024-04-30)

You're using a nightly from April. @celesteornato please update your rustc version then try again.

**Comment by celesteornato** [comment]
Ah sorry, bug seems to have been fixed since then.  Closing the issue now.
