### ISSUE TITLE
ICE: ` entered unreachable code: tail calls can't be present in generators`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#127551]
auto-reduced (treereduce-rust):
````rust

pub async const fn test(s: String) -> String {
    const fn takes_string(s: String) -> String {
        s
    }

    become takes_string(s);
}

````

original:
````rust
//@ check-pass
#![allow(incomplete_features)]
#![doc(test(a))]

pub async const fn test(s: String) -> String {
    const fn takes_string(s: String) -> String {
        s
    }

    become takes_string(s);
}

struct Type;

fn main() {}

````

Version information
````
rustc 1.81.0-nightly (956deab78 2024-07-10)
binary: rustc
commit-hash: 956deab78816b87764f1dbbe19fcd2bdc66ce950
commit-date: 2024-07-10
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0670]: `async fn` is not permitted in Rust 2015
 --> /tmp/icemaker_global_tempdir.iBV1n1oQo4xn/rustc_testrunner_tmpdir_reporting.KiPqkTOTw5ar/mvce.rs:5:5
  |
5 | pub async const fn test(s: String) -> String {
  |     ^^^^^ to use `async fn`, switch to Rust 2018 or later
  |
  = help: pass `--edition 2021` to `rustc`
  = note: for more on editions, read https://doc.rust-lang.org/edition-guide

error: expected one of `extern`, `fn`, `safe`, or `unsafe`, found keyword `const`
 --> /tmp/icemaker_global_tempdir.iBV1n1oQo4xn/rustc_testrunner_tmpdir_reporting.KiPqkTOTw5ar/mvce.rs:5:11
  |
5 | pub async const fn test(s: String) -> String {
  |     ------^^^^^
  |     |     |
  |     |     expected one of `extern`, `fn`, `safe`, or `unsafe`
  |     help: `const` must come before `async`: `const async`
  |
  = note: keyword order for functions declaration is `pub`, `default`, `const`, `async`, `unsafe`, `extern`

error: functions cannot be both `const` and `async`
  --> /tmp/icemaker_global_tempdir.iBV1n1oQo4xn/rustc_testrunner_tmpdir_reporting.KiPqkTOTw5ar/mvce.rs:5:5
   |
5  |   pub async const fn test(s: String) -> String {
   |   -   ^^^^^ ^^^^^ `const` because of this
   |   |   |
   |  _|   `async` because of this
   | |
6  | |     const fn takes_string(s: String) -> String {
7  | |         s
8  | |     }
9  | |
10 | |     become takes_string(s);
11 | | }
   | |_-

error[E0658]: `become` expression is experimental
  --> /tmp/icemaker_global_tempdir.iBV1n1oQo4xn/rustc_testrunner_tmpdir_reporting.KiPqkTOTw5ar/mvce.rs:10:5
   |
10 |     become takes_string(s);
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #112788 <https://github.com/rust-lang/rust/issues/112788> for more information
   = help: add `#![feature(explicit_tail_calls)]` to the crate attributes to enable
   = note: this compiler was built on 2024-07-10; consider upgrading it if it is out of date

error[E0601]: `main` function not found in crate `mvce`
  --> /tmp/icemaker_global_tempdir.iBV1n1oQo4xn/rustc_testrunner_tmpdir_reporting.KiPqkTOTw5ar/mvce.rs:11:2
   |
11 | }
   |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.iBV1n1oQo4xn/rustc_testrunner_tmpdir_reporting.KiPqkTOTw5ar/mvce.rs`

thread 'rustc' panicked at compiler/rustc_mir_transform/src/coroutine.rs:1372:17:
internal error: entered unreachable code: tail calls can't be present in generators
stack backtrace:
   0:     0x75e3356e6655 - std::backtrace_rs::backtrace::libunwind::trace::h23c5b5185d85ee4e
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x75e3356e6655 - std::backtrace_rs::backtrace::trace_unsynchronized::h37ba73b6af9ab482
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x75e3356e6655 - std::sys::backtrace::_print_fmt::haab9225cc6091b20
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/sys/backtrace.rs:68:5
   3:     0x75e3356e6655 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbbe967f0e048b98e
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/sys/backtrace.rs:44:22
   4:     0x75e335735d3b - core::fmt::rt::Argument::fmt::hd2ac4dea02787091
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/core/src/fmt/rt.rs:173:76
   5:     0x75e335735d3b - core::fmt::write::hb27082dbd28d03c3
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/core/src/fmt/mod.rs:1182:21
   6:     0x75e3356daf8f - std::io::Write::write_fmt::h98ced567c54415d8
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/io/mod.rs:1835:15
   7:     0x75e3356e642e - std::sys::backtrace::_print::hbbbe3c7dafb7d640
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/sys/backtrace.rs:47:5
   8:     0x75e3356e642e - std::sys::backtrace::print::hc8e8cb690f90de4a
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/sys/backtrace.rs:34:9
   9:     0x75e3356e8d79 - std::panicking::default_hook::{{closure}}::h85f571f888a7bf48
  10:     0x75e3356e8b1c - std::panicking::default_hook::h61506a6769f9b84c
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/panicking.rs:292:9
  11:     0x75e331c26679 - std[94a9b6aeea34a3af]::panicking::update_hook::<alloc[e6e32d418bb48065]::boxed::Box<rustc_driver_impl[b62f22f5ca09a37]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x75e3356e969f - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4441e7e17cba25c2
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/alloc/src/boxed.rs:2078:9
  13:     0x75e3356e969f - std::panicking::rust_panic_with_hook::hf8ad1dc167b64909
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/panicking.rs:804:13
  14:     0x75e3356e9293 - std::panicking::begin_panic_handler::{{closure}}::h1ed651657e762c32
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/panicking.rs:663:13
  15:     0x75e3356e6b19 - std::sys::backtrace::__rust_end_short_backtrace::h5e670380cd913ede
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/sys/backtrace.rs:171:18
  16:     0x75e3356e8f54 - rust_begin_unwind
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/panicking.rs:661:5
  17:     0x75e3357322f3 - core::panicking::panic_fmt::h4b4eb74434f6c869
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/core/src/panicking.rs:74:14
  18:     0x75e3323f4a82 - <rustc_mir_transform[fb78117a67728267]::coroutine::StateTransform as rustc_middle[8f0d78536b7a8669]::mir::MirPass>::run_pass
  19:     0x75e333201c3b - rustc_mir_transform[fb78117a67728267]::pass_manager::run_passes_inner
  20:     0x75e33346c724 - rustc_mir_transform[fb78117a67728267]::mir_drops_elaborated_and_const_checked
  21:     0x75e33346bf7d - rustc_query_impl[5a5208feae238999]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5a5208feae238999]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>
  22:     0x75e3335443b3 - rustc_query_system[9328994ec12ce07c]::query::plumbing::try_execute_query::<rustc_query_impl[5a5208feae238999]::DynamicConfig<rustc_query_system[9328994ec12ce07c]::query::caches::VecCache<rustc_span[a3183dfb17591e39]::def_id::LocalDefId, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[5a5208feae238999]::plumbing::QueryCtxt, false>
  23:     0x75e333543d59 - rustc_query_impl[5a5208feae238999]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  24:     0x75e3338abbc9 - rustc_mir_transform[fb78117a67728267]::optimized_mir
  25:     0x75e3340effdb - rustc_query_impl[5a5208feae238999]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5a5208feae238999]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>
  26:     0x75e3334d09a3 - rustc_query_system[9328994ec12ce07c]::query::plumbing::try_execute_query::<rustc_query_impl[5a5208feae238999]::DynamicConfig<rustc_query_system[9328994ec12ce07c]::query::caches::DefIdCache<rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[5a5208feae238999]::plumbing::QueryCtxt, false>
  27:     0x75e3334d01a0 - rustc_query_impl[5a5208feae238999]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  28:     0x75e333ba5429 - rustc_middle[8f0d78536b7a8669]::query::plumbing::query_get_at::<rustc_query_system[9328994ec12ce07c]::query::caches::DefIdCache<rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>>
  29:     0x75e33226ea40 - <rustc_middle[8f0d78536b7a8669]::ty::context::TyCtxt>::coroutine_layout
  30:     0x75e3338539c1 - rustc_ty_utils[cb8da5f8949738ab]::layout::layout_of_uncached
  31:     0x75e333843c35 - rustc_ty_utils[cb8da5f8949738ab]::layout::layout_of
  32:     0x75e333843b97 - rustc_query_impl[5a5208feae238999]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5a5208feae238999]::query_impl::layout_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 16usize]>>
  33:     0x75e333842ec8 - rustc_query_system[9328994ec12ce07c]::query::plumbing::try_execute_query::<rustc_query_impl[5a5208feae238999]::DynamicConfig<rustc_query_system[9328994ec12ce07c]::query::caches::DefaultCache<rustc_middle[8f0d78536b7a8669]::ty::ParamEnvAnd<rustc_middle[8f0d78536b7a8669]::ty::Ty>, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 16usize]>>, false, true, false>, rustc_query_impl[5a5208feae238999]::plumbing::QueryCtxt, false>
  34:     0x75e333842b67 - rustc_query_impl[5a5208feae238999]::query_impl::layout_of::get_query_non_incr::__rust_end_short_backtrace
  35:     0x75e32fb3f297 - <rustc_mir_transform[fb78117a67728267]::known_panics_lint::KnownPanicsLint as rustc_mir_transform[fb78117a67728267]::pass_manager::MirLint>::run_lint
  36:     0x75e333201c3b - rustc_mir_transform[fb78117a67728267]::pass_manager::run_passes_inner
  37:     0x75e33346c724 - rustc_mir_transform[fb78117a67728267]::mir_drops_elaborated_and_const_checked
  38:     0x75e33346bf7d - rustc_query_impl[5a5208feae238999]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5a5208feae238999]::query_impl::mir_drops_elaborated_and_const_checked::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>
  39:     0x75e3335443b3 - rustc_query_system[9328994ec12ce07c]::query::plumbing::try_execute_query::<rustc_query_impl[5a5208feae238999]::DynamicConfig<rustc_query_system[9328994ec12ce07c]::query::caches::VecCache<rustc_span[a3183dfb17591e39]::def_id::LocalDefId, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[5a5208feae238999]::plumbing::QueryCtxt, false>
  40:     0x75e333543d59 - rustc_query_impl[5a5208feae238999]::query_impl::mir_drops_elaborated_and_const_checked::get_query_non_incr::__rust_end_short_backtrace
  41:     0x75e33353790f - rustc_interface[d2bda87d81aa9d32]::passes::analysis
  42:     0x75e333536807 - rustc_query_impl[5a5208feae238999]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[5a5208feae238999]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 1usize]>>
  43:     0x75e334113225 - rustc_query_system[9328994ec12ce07c]::query::plumbing::try_execute_query::<rustc_query_impl[5a5208feae238999]::DynamicConfig<rustc_query_system[9328994ec12ce07c]::query::caches::SingleCache<rustc_middle[8f0d78536b7a8669]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[5a5208feae238999]::plumbing::QueryCtxt, false>
  44:     0x75e334112f8f - rustc_query_impl[5a5208feae238999]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  45:     0x75e333fd4445 - rustc_interface[d2bda87d81aa9d32]::interface::run_compiler::<core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>, rustc_driver_impl[b62f22f5ca09a37]::run_compiler::{closure#0}>::{closure#1}
  46:     0x75e333fb5c89 - std[94a9b6aeea34a3af]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[d2bda87d81aa9d32]::util::run_in_thread_with_globals<rustc_interface[d2bda87d81aa9d32]::util::run_in_thread_pool_with_globals<rustc_interface[d2bda87d81aa9d32]::interface::run_compiler<core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>, rustc_driver_impl[b62f22f5ca09a37]::run_compiler::{closure#0}>::{closure#1}, core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>>::{closure#0}, core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>>
  47:     0x75e333fb5a3a - <<std[94a9b6aeea34a3af]::thread::Builder>::spawn_unchecked_<rustc_interface[d2bda87d81aa9d32]::util::run_in_thread_with_globals<rustc_interface[d2bda87d81aa9d32]::util::run_in_thread_pool_with_globals<rustc_interface[d2bda87d81aa9d32]::interface::run_compiler<core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>, rustc_driver_impl[b62f22f5ca09a37]::run_compiler::{closure#0}>::{closure#1}, core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>>::{closure#0}, core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b0e39e91e5d0ade1]::result::Result<(), rustc_span[a3183dfb17591e39]::ErrorGuaranteed>>::{closure#2} as core[b0e39e91e5d0ade1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x75e3356f34fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2dd60573fdbf7ac9
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/alloc/src/boxed.rs:2064:9
  49:     0x75e3356f34fb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h439bb98f4e4ff285
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/alloc/src/boxed.rs:2064:9
  50:     0x75e3356f34fb - std::sys::pal::unix::thread::Thread::new::thread_start::hfe229f8257a82f15
                               at /rustc/956deab78816b87764f1dbbe19fcd2bdc66ce950/library/std/src/sys/pal/unix/thread.rs:108:17
  51:     0x75e32e6a6ded - <unknown>
  52:     0x75e32e72a0dc - <unknown>
  53:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.81.0-nightly (956deab78 2024-07-10) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_drops_elaborated_and_const_checked] elaborating drops for `test::{closure#0}`
#1 [optimized_mir] optimizing MIR for `test::{closure#0}`
end of query stack
error: aborting due to 5 previous errors

Some errors have detailed explanations: E0601, E0658, E0670.
For more information about an error, try `rustc --explain E0601`.

```

</p>
</details>

**Comment by Nilstrieb** [comment]
Thanks for already wanting to jump ahead and fuzz this new feature, but it really isn't ready yet for being fuzzed, there are enough known issues that finding new ones from fuzzing doesn't really help (since it's likely that fixing the known issue may fix some of the fuzzed one's too, and keeping track of that is busywork).
So it would be nice if you could avoid fuzzing become until it moves out of incomplete_features (and then hammer it until it falls over >:)).

(i think it's a bad idea to fuzz incomplete features in most cases, may be worth discussing in T-compiler as a general policy)
