### ISSUE TITLE
`Found unstable fingerprints for evaluate_obligation(c06a881ba4fc8a41-cdd7b5daf5a2edb3): Ok(EvaluatedToOkModuloRegions)`

### ISSUE THREAD

**Issue by yyny** [rust-lang/rust#128779]
### Code

Nope:

```
$ cloc --exclude-dir target .
     417 text files.
     392 unique files.                                          
      26 files ignored.

github.com/AlDanial/cloc v 2.02  T=0.09 s (4166.4 files/s, 466397.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rust                           322           3545           1885          31910
YAML                            17             86            150           1527
JSON                             4              0              0           1325
CSV                              2              0              0           1006
TOML                            22             54             12            583
SQL                              2             10              0            401
Bourne Shell                     5             56             49            400
XML                              4              0              0            297
PHP                              1              7              2            281
JavaScript                       1             18              3             90
Text                             1              7              0             89
Dockerfile                       6             24              0             34
Markdown                         2              6              0             13
C/C++ Header                     3              0              0             12
-------------------------------------------------------------------------------
SUM:                           392           3813           2101          37968
-------------------------------------------------------------------------------
```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

### Error output

```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(c06a881ba4fc8a41-cdd7b5daf5a2edb3)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p public_api` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/compiler/rustc_query_system/src/query/plumbing.rs:725:9:
Found unstable fingerprints for evaluate_obligation(c06a881ba4fc8a41-cdd7b5daf5a2edb3): Ok(EvaluatedToOkModuloRegions)
stack backtrace:
   0:     0x7f7eaa38c035 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f7eaa38c035 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7eaa38c035 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f7eaa38c035 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f7eaa3db29b - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:     0x7f7eaa3db29b - core::fmt::write::hc090a2ffd6b28c4a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:     0x7f7eaa380bdf - std::io::Write::write_fmt::h8898bac6ff039a23
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:     0x7f7eaa38be0e - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f7eaa38be0e - std::sys_common::backtrace::print::ha96650907276675e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f7eaa38e779 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
  10:     0x7f7eaa38e4bd - std::panicking::default_hook::h207342be97478370
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
  11:     0x7f7ead2891b7 - std[3c8ba8ebcf555201]::panicking::update_hook::<alloc[bfbae7e348dce413]::boxed::Box<rustc_driver_impl[c88438ade88661f4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f7eaa38ee76 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha9c3bc81d312fd83
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  13:     0x7f7eaa38ee76 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
  14:     0x7f7eaa38ec24 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
  15:     0x7f7eaa38c4f9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f7eaa38e957 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  17:     0x7f7eaa3d7763 - core::panicking::panic_fmt::hdc63834ffaaefae5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  18:     0x7f7eada067a6 - rustc_query_system[4e189ce2c77124d]::query::plumbing::incremental_verify_ich_failed::<rustc_middle[3ff731b746e7b038]::ty::context::TyCtxt>
  19:     0x7f7eaeb53e58 - rustc_query_system[4e189ce2c77124d]::query::plumbing::try_execute_query::<rustc_query_impl[a12402620de91e8]::DynamicConfig<rustc_query_system[4e189ce2c77124d]::query::caches::DefaultCache<rustc_type_ir[a145be3c51398263]::canonical::Canonical<rustc_middle[3ff731b746e7b038]::ty::context::TyCtxt, rustc_middle[3ff731b746e7b038]::ty::ParamEnvAnd<rustc_middle[3ff731b746e7b038]::ty::predicate::Predicate>>, rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[a12402620de91e8]::plumbing::QueryCtxt, true>
  20:     0x7f7eaeb525e0 - rustc_query_impl[a12402620de91e8]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  21:     0x7f7eab37b644 - <rustc_trait_selection[173dcaf5d960508e]::traits::fulfill::FulfillProcessor as rustc_data_structures[52ff41d7b92c45f3]::obligation_forest::ObligationProcessor>::process_obligation
  22:     0x7f7eae60ea00 - <rustc_data_structures[52ff41d7b92c45f3]::obligation_forest::ObligationForest<rustc_trait_selection[173dcaf5d960508e]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[173dcaf5d960508e]::traits::fulfill::FulfillProcessor>
  23:     0x7f7eabba0913 - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::confirm_builtin_call
  24:     0x7f7eaf0ba130 - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  25:     0x7f7eab4a40e2 - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::check_method_argument_types
  26:     0x7f7eaf0bc1d5 - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x7f7eaf0ba6a4 - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f7eaf0b4bc6 - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7f7eaf0ba64d - <rustc_hir_typeck[e95414a4bbf7473d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7f7eaeaddc8c - rustc_hir_typeck[e95414a4bbf7473d]::check::check_fn
  31:     0x7f7eaead2baf - rustc_hir_typeck[e95414a4bbf7473d]::typeck
  32:     0x7f7eaead188d - rustc_query_impl[a12402620de91e8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a12402620de91e8]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 8usize]>>
  33:     0x7f7eae7182b8 - rustc_query_system[4e189ce2c77124d]::query::plumbing::try_execute_query::<rustc_query_impl[a12402620de91e8]::DynamicConfig<rustc_query_system[4e189ce2c77124d]::query::caches::VecCache<rustc_span[8c7415e9d33ddd75]::def_id::LocalDefId, rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[a12402620de91e8]::plumbing::QueryCtxt, true>
  34:     0x7f7eae99308c - rustc_query_impl[a12402620de91e8]::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
  35:     0x7f7eaedca9b5 - rustc_hir_analysis[46a17d8846b4335f]::check_crate
  36:     0x7f7eaef890e0 - rustc_interface[640972162e3c086f]::passes::analysis
  37:     0x7f7eaef88aef - rustc_query_impl[a12402620de91e8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a12402620de91e8]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 1usize]>>
  38:     0x7f7eaf471e53 - rustc_query_system[4e189ce2c77124d]::query::plumbing::try_execute_query::<rustc_query_impl[a12402620de91e8]::DynamicConfig<rustc_query_system[4e189ce2c77124d]::query::caches::SingleCache<rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a12402620de91e8]::plumbing::QueryCtxt, true>
  39:     0x7f7eaf471a9c - rustc_query_impl[a12402620de91e8]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  40:     0x7f7eaf183149 - rustc_interface[640972162e3c086f]::interface::run_compiler::<core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>, rustc_driver_impl[c88438ade88661f4]::run_compiler::{closure#0}>::{closure#1}
  41:     0x7f7eaf140f8b - std[3c8ba8ebcf555201]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[640972162e3c086f]::util::run_in_thread_with_globals<rustc_interface[640972162e3c086f]::interface::run_compiler<core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>, rustc_driver_impl[c88438ade88661f4]::run_compiler::{closure#0}>::{closure#1}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>
  42:     0x7f7eaf140d80 - <<std[3c8ba8ebcf555201]::thread::Builder>::spawn_unchecked_<rustc_interface[640972162e3c086f]::util::run_in_thread_with_globals<rustc_interface[640972162e3c086f]::interface::run_compiler<core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>, rustc_driver_impl[c88438ade88661f4]::run_compiler::{closure#0}>::{closure#1}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>::{closure#2} as core[868bc93c3f2beb33]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  43:     0x7f7eaa398cab - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h09e5a4c541afa800
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  44:     0x7f7eaa398cab - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9c8b03c22f4e7026
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  45:     0x7f7eaa398cab - std::sys::pal::unix::thread::Thread::new::thread_start::h522bc89a54da820a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread.rs:108:17
  46:     0x7f7eaa177962 - start_thread
                               at ./nptl/pthread_create.c:447:8
  47:     0x7f7eaa1f2b08 - __GI___clone3
                               at /builddir/glibc-2.39/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  48:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0 (129f3b996 2024-06-10) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C linker=/usr/bin/clang -C incremental=[REDACTED] -C link-arg=-fuse-ld=lld -C link-arg=-Wl,-z,nostart-stop-gc

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `core::result::Result<core::convert::Infallible, rpcy::error::RpcError<rpcy_proto_jsonrpc::JSON_RPC_2_0, rpcy::transport::tokio::pooled::PooledTransport<rpcy_proto_jsonrpc::JSON_RPC_2_0, connect_core::rpc::Transport>, rpcy_proto_jsonrpc::ErrorResponseObject>>: core::marker::Send`
#1 [typeck] type-checking `route::activity::routes`
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `public-api` (bin "public-api") due to 1 previous error
```

</p>
</details>

**Comment by yyny** [comment]
`rust-analyzer` crashed earlier with a

```
called `?::unwrap()` on a `?` value
```

on an `Option` or `Error`, but I could not catch the log.
