### ISSUE TITLE
Cannot break on `rust_fail` using lldb on OSX 

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#12872]
Using the following program (compiled with `-g` flag):
```
fn main() {
    fail!("booga");
}
```

Rust version:
```
68a4f7d9babb0c638f3425ced08e13f9fbfdcf56 ../src/compiler/rust (0.9-1385-g68a4f7d)
```

LLDB output failing to stop on `rust_fail`:
```
[larsberg@lbergstrom tmp]$ lldb -- ./tf
Current executable set to './tf' (x86_64).
(lldb) b rust_fail
Breakpoint 1: where = tf`std::rt::unwind::Unwinder::begin_unwind::rust_fail + 63 at local_data.rs:285, address = 0x00000001000ca1cf
(lldb) run
Process 61512 launched: './tf' (x86_64)
task '<main>' failed at 'booga', /Users/larsberg/tmp/test-failure.rs:2
Process 61512 exited with status = 101 (0x00000065) 
(lldb) 
```

Compare with GDB output, stopping on `rust_fail`:
```
[larsberg@lbergstrom tmp]$ gdb --args ./tf
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin13.0.0".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /Users/larsberg/tmp/tf...Reading symbols from /Users/larsberg/tmp/tf.dSYM/Contents/Resources/DWARF/tf...done.
done.
(gdb) b rust_fail
Breakpoint 1 at 0x1000ca190: file /Users/larsberg/servo2/src/compiler/rust/src/libstd/rt/global_heap.rs, line 71.
(gdb) run
Starting program: /Users/larsberg/tmp/./tf 
task '<main>' failed at 'booga', /Users/larsberg/tmp/test-failure.rs:2
[New Thread 0x170b of process 61532]
[New Thread 0x1803 of process 61532]
[New Thread 0x1903 of process 61532]
[New Thread 0x1a03 of process 61532]
[New Thread 0x1b03 of process 61532]
[New Thread 0x1c03 of process 61532]
[New Thread 0x1d03 of process 61532]
[New Thread 0x1e03 of process 61532]
[Switching to Thread 0x170b of process 61532]

Breakpoint 1, std::rt::unwind::Unwinder::begin_unwind::rust_fail () at /Users/larsberg/servo2/src/compiler/rust/src/libstd/rt/global_heap.rs:71
71      pub unsafe fn exchange_malloc(size: uint) -> *u8 {
(gdb) 
```

CC @michaelwoerister

**Comment by steveklabnik** [comment]
Triage:

today's code:

```
fn main() {
    panic!("booga");
}
```

using lldb:

```
steve@warmachine:~/tmp$ rustc -g hello.rs
steve@warmachine:~/tmp$ lldb -- ./hello
Current executable set to './hello' (x86_64).
(lldb) b rust_panic
Breakpoint 1: where = hello`rust_panic, address = 0x000000000000ce20
(lldb) run
Process 32608 launching
Process 32608 launched: './hello' (x86_64)
Process 32608 stopped
* thread #1: tid = 32608, 0x00007f703ca0d190, name = 'hello'
    frame #0: 
thread '<main>' panicked at 'booga', hello.rs:2
Process 32608 stopped
* thread #1: tid = 32608, 0x00007f703cc3be20 hello`rust_panic, name = 'hello', stop reason = breakpoint 1.1
    frame #0: 0x00007f703cc3be20 hello`rust_panic
hello`rust_panic:
-> 0x7f703cc3be20:  cmpq   %fs:0x70, %rsp
   0x7f703cc3be29:  ja     0x7f703cc3be45            ; rust_panic + 37
   0x7f703cc3be2b:  movabsq $0xa8, %r10
   0x7f703cc3be35:  movabsq $0x0, %r11
(lldb) version
lldb version 3.5.0 ( revision )
```

Works for me too, on Debian. Given this bug is a year old, I'm going to give it a close, I think. @larsbergstrom , if this isn't working for you still, let me know and we'll re-open, but I bet the weirdness got fixed in the meantime.
