### ISSUE TITLE
regression: assertion `left == right` failed for floats

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128898]
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/TheLastBytebender.rust-workshop/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/YogirajT.rustnet/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/lightbird-0.1.10/log.txt

```
[INFO] [stdout] thread 'tests::test_get_ordebook_skew_by_range_orderbook' panicked at tests/test_orderbook.rs:645:9:
[INFO] [stdout] assertion `left == right` failed
[INFO] [stdout]   left: 0.8855105548523078
[INFO] [stdout]  right: 0.885510554852308
```

**Comment by tgross35** [comment]
The first crate is doing exact comparison on `ln` from floating point numbers, so the results are pretty order of operations sensitive. I haven't dug into what exactly could have caused the difference, I don't think the `cmath` implementation should have changed in this rev.

```rust
        let anw = sum_bid.ln() - sum_ask.ln();
        let result = orderbook.get_ordebook_skew_by_range(&range_diff);

        assert_eq!(anw, result);
```

and https://github.com/TheLastBytebender/rust-workshop/blob/66bb073d11487d3ad4ffa9716676e4f03666afad/src/trading/orderbook.rs#L126

**Comment by tgross35** [comment]
The second one is more surprising, those numbers are pretty different

```rust
[INFO] [stdout] thread 'tests::test_back_prop' panicked at tests/matrix.rs:280:9:
[INFO] [stdout] assertion `left == right` failed
[INFO] [stdout]   left: 2.9802323e-9
[INFO] [stdout]  right: 5.9604646e-9
```

Third one

```
[INFO] [stdout] thread 'processor::processor_test' panicked at src/processor.rs:173:9:
[INFO] [stdout] assertion `left != right` failed
[INFO] [stdout]   left: 0.0
[INFO] [stdout]  right: 0.0
```

**Comment by zachs18** [comment]
The `lightbird` test failure (third one) is not a regression AFAICT; I can reproduce it locally with 1.73.0, 1.76.0, and 1.80.1, after running it a few times.

I'm not entirely sure I understand the test in question, but it appears to be asserting that no processor had 0% usage over the past second, which is not necessarily the case, especially on multi-core systems and especially when running only `cargo test` and not much else.

**Comment by workingjubilee** [comment]
Hmm. Can we exclude a crate from running its tests only but still check if it builds?

**Comment by workingjubilee** [comment]
This was a float issue that got classed as a sorting issue (but all the sorting issues seem to actually be hashmap issues): https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/tommarek.MPCHomeControl/log.txt

**Comment by apiraino** [comment]
This is now a stable regression, but I'm not sure what we can do (or want to do)

**Comment by jieyouxu** [comment]
P Triage: status unclear, are these regressions still problematic?

**Comment by apiraino** [comment]
I guess we'll keep this issue around in case we can reference it from other report ([Zulip thread](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23128898.20regression.3A.20assertion.20.60left.20.3D.3D.20right.60.20failed.20for.20fl.E2.80.A6))

@rustbot label -I-prioritize
