### ISSUE TITLE
Compiler error when running cargo test.

### ISSUE THREAD

**Issue by yczhangsjtu** [rust-lang/rust#128995]
The error happens when `cargo test`, either with `--release` or not. But does not happen with `cargo build`.

### Code

Unfortunately, this error happens when compiling a large private project that I don't have the right to disclose.

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (da159eb33 2024-05-28)
binary: rustc
commit-hash: da159eb331b27df528185c616b394bb0e1d2a4bd
commit-date: 2024-05-28
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/link.rs:2700:27:
index out of bounds: the len is 73 but the index is 73
stack backtrace:
   0:     0x7574d2f70c65 - std::backtrace_rs::backtrace::libunwind::trace::h929c6931792afc00
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7574d2f70c65 - std::backtrace_rs::backtrace::trace_unsynchronized::h7b94610f2cd6af45
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7574d2f70c65 - std::sys_common::backtrace::_print_fmt::h69417add4f7d4125
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7574d2f70c65 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h37ecbc3541e2f776
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7574d2fc16ab - core::fmt::rt::Argument::fmt::h72f7455b2dedda8c
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/core/src/fmt/rt.rs:165:63
   5:     0x7574d2fc16ab - core::fmt::write::hd4702675b19bc4d7
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/core/src/fmt/mod.rs:1168:21
   6:     0x7574d2f659ef - std::io::Write::write_fmt::hdadc8b422b63d6bb
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/io/mod.rs:1835:15
   7:     0x7574d2f70a3e - std::sys_common::backtrace::_print::h7384e572a3d42335
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7574d2f70a3e - std::sys_common::backtrace::print::h5828213402223b55
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7574d2f73479 - std::panicking::default_hook::{{closure}}::hee234b2bd1c37953
  10:     0x7574d2f7321a - std::panicking::default_hook::h3adac050c249bf11
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/panicking.rs:298:9
  11:     0x7574cf931530 - std[b6126bf2e31db8f5]::panicking::update_hook::<alloc[6d24c75990bf29f0]::boxed::Box<rustc_driver_impl[2fcd50e4f8b27d1b]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7574d2f73bab - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h83a80c7b0ee741cc
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/alloc/src/boxed.rs:2077:9
  13:     0x7574d2f73bab - std::panicking::rust_panic_with_hook::h590c546ff7213364
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/panicking.rs:799:13
  14:     0x7574d2f73924 - std::panicking::begin_panic_handler::{{closure}}::hb6d18059142b9e4e
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/panicking.rs:664:13
  15:     0x7574d2f71129 - std::sys_common::backtrace::__rust_end_short_backtrace::h38cd1b9dc3c9a8e5
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7574d2f73657 - rust_begin_unwind
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/panicking.rs:652:5
  17:     0x7574d2fbdc43 - core::panicking::panic_fmt::h8f748e01104d2cd5
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/core/src/panicking.rs:72:14
  18:     0x7574d2fbde57 - core::panicking::panic_bounds_check::hd8cc6379ff00dde1
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/core/src/panicking.rs:274:5
  19:     0x7574d1ce9c8d - rustc_codegen_ssa[e86ae12667086e33]::back::link::linker_with_args
  20:     0x7574d1cefb9e - rustc_codegen_ssa[e86ae12667086e33]::back::link::link_natively
  21:     0x7574d1b6edcf - rustc_codegen_ssa[e86ae12667086e33]::back::link::link_binary
  22:     0x7574d1b6e2e2 - <rustc_codegen_llvm[b92eeab7daae03f2]::LlvmCodegenBackend as rustc_codegen_ssa[e86ae12667086e33]::traits::backend::CodegenBackend>::link
  23:     0x7574d175ffe4 - <rustc_interface[e5ab8d3757df5895]::queries::Linker>::link
  24:     0x7574d19b2b37 - rustc_interface[e5ab8d3757df5895]::interface::run_compiler::<core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>, rustc_driver_impl[2fcd50e4f8b27d1b]::run_compiler::{closure#0}>::{closure#1}
  25:     0x7574d1953789 - std[b6126bf2e31db8f5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e5ab8d3757df5895]::util::run_in_thread_with_globals<rustc_interface[e5ab8d3757df5895]::util::run_in_thread_pool_with_globals<rustc_interface[e5ab8d3757df5895]::interface::run_compiler<core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>, rustc_driver_impl[2fcd50e4f8b27d1b]::run_compiler::{closure#0}>::{closure#1}, core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>>::{closure#0}, core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>>
  26:     0x7574d1953530 - <<std[b6126bf2e31db8f5]::thread::Builder>::spawn_unchecked_<rustc_interface[e5ab8d3757df5895]::util::run_in_thread_with_globals<rustc_interface[e5ab8d3757df5895]::util::run_in_thread_pool_with_globals<rustc_interface[e5ab8d3757df5895]::interface::run_compiler<core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>, rustc_driver_impl[2fcd50e4f8b27d1b]::run_compiler::{closure#0}>::{closure#1}, core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>>::{closure#0}, core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3be9488f036ff4ce]::result::Result<(), rustc_span[5bba9e8fd8ea486f]::ErrorGuaranteed>>::{closure#2} as core[3be9488f036ff4ce]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7574d2f7db9b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdd2c9e7cd8e4aee1
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/alloc/src/boxed.rs:2063:9
  28:     0x7574d2f7db9b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9873e224d7902e40
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/alloc/src/boxed.rs:2063:9
  29:     0x7574d2f7db9b - std::sys::pal::unix::thread::Thread::new::thread_start::h66abe029d5d97728
                               at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/sys/pal/unix/thread.rs:108:17
  30:     0x7574cc494ac3 - <unknown>
  31:     0x7574cc526850 - <unknown>
  32:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/ubuntu/cyte/ceno/rustc-ice-2024-08-12T03_03_27-662521.txt` to your bug report

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C strip=debuginfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/da159eb331b27df528185c616b394bb0e1d2a4bd/library/core/src/panicking.rs:274:5
   3: rustc_codegen_ssa::back::link::linker_with_args
   4: rustc_codegen_ssa::back::link::link_natively
   5: rustc_codegen_ssa::back::link::link_binary
   6: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::link
   7: <rustc_interface::queries::Linker>::link
   8: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by yczhangsjtu** [comment]
Disappeared after upgraded to 1.82.0-nightly.
