### ISSUE TITLE
[ICE]: `None` in compiler/rustc_middle/src/ty/sty.rs 

### ISSUE THREAD

**Issue by jean-airoldie** [rust-lang/rust#129882]
### Code

```Rust
Here is a [reproduction repository](https://github.com/jean-airoldie/generic_const_exprs_bug)
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [X] Current Nightly

### Rust Version

```Shell
rustc 1.82.0-nightly (100fde524 2024-08-28)
binary: rustc
commit-hash: 100fde5246bf56f22fb5cc85374dd841296fce0e
commit-date: 2024-08-28
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

### Current error output

```Shell
<idk>
```

### Backtrace

```Shell
thread 'rustc' panicked at compiler/rustc_middle/src/ty/sty.rs:362:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f0bd51f2bad - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hfd30b84ebe11988c
   1:     0x7f0bd5a02c97 - core::fmt::write::hb626a39072c0eb4c
   2:     0x7f0bd698c7d1 - std::io::Write::write_fmt::h0614c4dd6b12fec7
   3:     0x7f0bd51f528b - std::panicking::default_hook::{{closure}}::h4464369cfb2c3523
   4:     0x7f0bd51f4efe - std::panicking::default_hook::hbe88f1457419259e
   5:     0x7f0bd4353d29 - std[4821b876adeec04f]::panicking::update_hook::<alloc[579338a18283919f]::boxed::Box<rustc_driver_impl[699cd2d3c3a41798]::install_ice_hook::{closure#0}>>::{closure#0}
   6:     0x7f0bd51f5ba7 - std::panicking::rust_panic_with_hook::hdf548254c8466072
   7:     0x7f0bd51f5833 - std::panicking::begin_panic_handler::{{closure}}::h3816939d6279b662
   8:     0x7f0bd51f3069 - std::sys::backtrace::__rust_end_short_backtrace::he8fc83e4c72749c8
   9:     0x7f0bd51f5534 - rust_begin_unwind
  10:     0x7f0bd2097b43 - core::panicking::panic_fmt::h7a006cece2943dea
  11:     0x7f0bd22725cc - core::panicking::panic::hb3c7ea25df633151
  12:     0x7f0bd2654db9 - core::option::unwrap_failed::hf05a1feec3e91ee0
  13:     0x7f0bd7474efc - <rustc_middle[177a089697687a0f]::ty::sty::ParamConst>::find_ty_from_env.cold
  14:     0x7f0bd2062493 - <rustc_trait_selection[c56acf29e3754aea]::traits::fulfill::FulfillProcessor as rustc_data_structures[9085261b91cf7e02]::obligation_forest::ObligationProcessor>::process_obligation
  15:     0x7f0bd5c71f01 - <rustc_data_structures[9085261b91cf7e02]::obligation_forest::ObligationForest<rustc_trait_selection[c56acf29e3754aea]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[c56acf29e3754aea]::traits::fulfill::FulfillProcessor>
  16:     0x7f0bd2402a19 - rustc_traits[64a9346c198cf531]::codegen::codegen_select_candidate
  17:     0x7f0bd5f2eef7 - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::codegen_select_candidate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 16usize]>>
  18:     0x7f0bd5f2ede7 - <rustc_query_impl[b7cf2626c3b456b5]::query_impl::codegen_select_candidate::dynamic_query::{closure#2} as core[3a188adb88b8af3f]::ops::function::FnOnce<(rustc_middle[177a089697687a0f]::ty::context::TyCtxt, (rustc_middle[177a089697687a0f]::ty::ParamEnv, rustc_type_ir[6093fd833338db7f]::predicate::TraitRef<rustc_middle[177a089697687a0f]::ty::context::TyCtxt>))>>::call_once
  19:     0x7f0bd5f2eda9 - <rustc_query_system[8ccef4992b07fb90]::query::plumbing::execute_job_incr<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::instance::InstanceKind, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[3a188adb88b8af3f]::ops::function::FnOnce<((rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::instance::InstanceKind, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 16usize]>>, false, false, false>), rustc_middle[177a089697687a0f]::ty::instance::InstanceKind)>>::call_once
  20:     0x7f0bd5f2d900 - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<(rustc_middle[177a089697687a0f]::ty::ParamEnv, rustc_type_ir[6093fd833338db7f]::predicate::TraitRef<rustc_middle[177a089697687a0f]::ty::context::TyCtxt>), rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  21:     0x7f0bd5f2ca26 - rustc_query_impl[b7cf2626c3b456b5]::query_impl::codegen_select_candidate::get_query_incr::__rust_end_short_backtrace
  22:     0x7f0bd2f93f83 - rustc_ty_utils[fdb58234601740b2]::instance::resolve_instance_raw
  23:     0x7f0bd6087869 - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::resolve_instance_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 32usize]>>
  24:     0x7f0bd608aa5f - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<(rustc_span[617b2c4e116b8252]::def_id::DefId, &rustc_middle[177a089697687a0f]::ty::list::RawList<(), rustc_middle[177a089697687a0f]::ty::generic_args::GenericArg>)>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 32usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  25:     0x7f0bd608973b - rustc_query_impl[b7cf2626c3b456b5]::query_impl::resolve_instance_raw::get_query_incr::__rust_end_short_backtrace
  26:     0x7f0bd2a02b35 - <rustc_middle[177a089697687a0f]::ty::context::TyCtxt>::const_eval_resolve
  27:     0x7f0bd672bc91 - rustc_const_eval[527f4e775693b9e9]::const_eval::eval_queries::eval_to_allocation_raw_provider
  28:     0x7f0bd67296b6 - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>
  29:     0x7f0bd672966f - <rustc_query_impl[b7cf2626c3b456b5]::query_impl::eval_to_allocation_raw::dynamic_query::{closure#2} as core[3a188adb88b8af3f]::ops::function::FnOnce<(rustc_middle[177a089697687a0f]::ty::context::TyCtxt, rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>)>>::call_once
  30:     0x7f0bd6725731 - <rustc_query_system[8ccef4992b07fb90]::query::plumbing::execute_job_incr<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[3a188adb88b8af3f]::ops::function::FnOnce<((rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>, false, false, false>), rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>)>>::call_once
  31:     0x7f0bd670df2e - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  32:     0x7f0bd670d436 - rustc_query_impl[b7cf2626c3b456b5]::query_impl::eval_to_allocation_raw::get_query_incr::__rust_end_short_backtrace
  33:     0x7f0bd67094b3 - rustc_const_eval[527f4e775693b9e9]::const_eval::valtrees::eval_to_valtree
  34:     0x7f0bd67092c3 - <rustc_const_eval[527f4e775693b9e9]::provide::{closure#0} as core[3a188adb88b8af3f]::ops::function::FnOnce<(rustc_middle[177a089697687a0f]::ty::context::TyCtxt, rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>)>>::call_once
  35:     0x7f0bd670927a - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::eval_to_valtree::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>
  36:     0x7f0bd670923b - <rustc_query_impl[b7cf2626c3b456b5]::query_impl::eval_to_valtree::dynamic_query::{closure#2} as core[3a188adb88b8af3f]::ops::function::FnOnce<(rustc_middle[177a089697687a0f]::ty::context::TyCtxt, rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>)>>::call_once
  37:     0x7f0bd6725731 - <rustc_query_system[8ccef4992b07fb90]::query::plumbing::execute_job_incr<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt>::{closure#2}::{closure#2} as core[3a188adb88b8af3f]::ops::function::FnOnce<((rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>, false, false, false>), rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>)>>::call_once
  38:     0x7f0bd670df2e - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  39:     0x7f0bd6b91252 - rustc_query_impl[b7cf2626c3b456b5]::query_impl::eval_to_valtree::get_query_incr::__rust_end_short_backtrace
  40:     0x7f0bd6395471 - rustc_middle[177a089697687a0f]::query::plumbing::query_get_at::<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_middle[177a089697687a0f]::ty::ParamEnvAnd<rustc_middle[177a089697687a0f]::mir::interpret::GlobalId>, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 24usize]>>>
  41:     0x7f0bd6394ee4 - <rustc_middle[177a089697687a0f]::ty::context::TyCtxt>::const_eval_global_id_for_typeck
  42:     0x7f0bd6393e8a - <rustc_middle[177a089697687a0f]::ty::context::TyCtxt>::const_eval_resolve_for_typeck
  43:     0x7f0bd6393b4a - <rustc_middle[177a089697687a0f]::ty::consts::Const>::eval
  44:     0x7f0bd6393a31 - <rustc_trait_selection[c56acf29e3754aea]::traits::normalize_param_env_or_error::{closure#0}::ConstNormalizer as rustc_type_ir[6093fd833338db7f]::fold::TypeFolder<rustc_middle[177a089697687a0f]::ty::context::TyCtxt>>::fold_const
  45:     0x7f0bd61900fd - rustc_trait_selection[c56acf29e3754aea]::traits::normalize_param_env_or_error
  46:     0x7f0bd1e4a481 - rustc_hir_analysis[fc33db6da9fe190b]::check::check::check_impl_items_against_trait
  47:     0x7f0bd2db52d2 - rustc_hir_analysis[fc33db6da9fe190b]::check::wfcheck::check_well_formed
  48:     0x7f0bd5e3bcc7 - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 1usize]>>
  49:     0x7f0bd5e3f476 - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::VecCache<rustc_hir[5e0bdc4562a2094d]::hir_id::OwnerId, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  50:     0x7f0bd5e3ee80 - rustc_query_impl[b7cf2626c3b456b5]::query_impl::check_well_formed::get_query_incr::__rust_end_short_backtrace
  51:     0x7f0bd5e3ca53 - rustc_hir_analysis[fc33db6da9fe190b]::check::wfcheck::check_mod_type_wf
  52:     0x7f0bd5e3c891 - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 1usize]>>
  53:     0x7f0bd695cf88 - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::DefaultCache<rustc_span[617b2c4e116b8252]::def_id::LocalModDefId, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  54:     0x7f0bd695dc5b - rustc_query_impl[b7cf2626c3b456b5]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  55:     0x7f0bd5bd28bb - rustc_hir_analysis[fc33db6da9fe190b]::check_crate
  56:     0x7f0bd607b53f - rustc_interface[4e8b14457d10516f]::passes::run_required_analyses
  57:     0x7f0bd67f00de - rustc_interface[4e8b14457d10516f]::passes::analysis
  58:     0x7f0bd67f00b1 - rustc_query_impl[b7cf2626c3b456b5]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[b7cf2626c3b456b5]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 1usize]>>
  59:     0x7f0bd6986acd - rustc_query_system[8ccef4992b07fb90]::query::plumbing::try_execute_query::<rustc_query_impl[b7cf2626c3b456b5]::DynamicConfig<rustc_query_system[8ccef4992b07fb90]::query::caches::SingleCache<rustc_middle[177a089697687a0f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[b7cf2626c3b456b5]::plumbing::QueryCtxt, true>
  60:     0x7f0bd698677a - rustc_query_impl[b7cf2626c3b456b5]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  61:     0x7f0bd67dc02c - rustc_interface[4e8b14457d10516f]::interface::run_compiler::<core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>, rustc_driver_impl[699cd2d3c3a41798]::run_compiler::{closure#0}>::{closure#1}
  62:     0x7f0bd68a9604 - std[4821b876adeec04f]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4e8b14457d10516f]::util::run_in_thread_with_globals<rustc_interface[4e8b14457d10516f]::util::run_in_thread_pool_with_globals<rustc_interface[4e8b14457d10516f]::interface::run_compiler<core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>, rustc_driver_impl[699cd2d3c3a41798]::run_compiler::{closure#0}>::{closure#1}, core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>>::{closure#0}, core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>>
  63:     0x7f0bd68a9c70 - <<std[4821b876adeec04f]::thread::Builder>::spawn_unchecked_<rustc_interface[4e8b14457d10516f]::util::run_in_thread_with_globals<rustc_interface[4e8b14457d10516f]::util::run_in_thread_pool_with_globals<rustc_interface[4e8b14457d10516f]::interface::run_compiler<core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>, rustc_driver_impl[699cd2d3c3a41798]::run_compiler::{closure#0}>::{closure#1}, core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>>::{closure#0}, core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3a188adb88b8af3f]::result::Result<(), rustc_span[617b2c4e116b8252]::ErrorGuaranteed>>::{closure#1} as core[3a188adb88b8af3f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  64:     0x7f0bd68a9feb - std::sys::pal::unix::thread::Thread::new::thread_start::h7ef170129820a8c9
  65:     0x7f0bd0ca8144 - start_thread
                               at ./nptl/pthread_create.c:442:8
  66:     0x7f0bd0d287dc - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  67:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/maxence/bug/generic_const_exprs_bug/rustc-ice-2024-09-02T08_57_34-282355.txt` to your bug report

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_select_candidate] computing candidate for `<Wrapper<F> as import::FromSlice>`
#1 [resolve_instance_raw] resolving instance `<Wrapper<F> as import::FromSlice>::SIZE`
#2 [eval_to_allocation_raw] const-evaluating + checking `import::FromSlice::validate_slice::{constant#0}`
#3 [eval_to_valtree] evaluating type-level constant
#4 [check_well_formed] checking that `<impl at compile/src/lib.rs:3:1: 3:54>` is well-formed
#5 [check_mod_type_wf] checking that types are well-formed in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `compile` (lib)
```

### Anything else?

Issue is solved when `generic_const_exprs` is enabled in the `compile` crate. In other words, when a dependency requires `generic_const_exprs` but it is not set in the current library, this ICE occurs.

I'm guessing this is related to #125958 based on the other issues i've seen.

**Comment by estebank** [comment]
This was fixed in nightly-2024-12-08.
