### ISSUE TITLE
ICE

### ISSUE THREAD

**Issue by jembishop** [rust-lang/rust#129937]
### Code

Too large to paste

### Meta

`rustc --version --verbose`:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.7
```

### Error output
Truncated due to github limit.
```

   Compiling hermes v3.1.10 (/home/jem/lotech/hermes)
   Compiling hermes v3.1.10 (/home/jem/lotech/hermes)
thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:389:13:
("Failed to extract DefId", def_kind, PackedFingerprint(Fingerprint(972924547419942312, 9808399571317748437)))
stack backtrace:
thread 'rustc' panicked at compiler/rustc_hir/src/definitions.rs:389:13:
("Failed to extract DefId", def_kind, PackedFingerprint(Fingerprint(972924547419942312, 9808399571317748437)))
stack backtrace:
   0:     0x7f2aa7d5cf05 - std::backtrace_rs::backtrace::libunwind::trace::h23054e327d0d4b55
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f2aa7d5cf05 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cc587407d7f7f64
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2aa7d5cf05 - std::sys_common::backtrace::_print_fmt::h4feeb59774730d6b
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f2aa7d5cf05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:44:22
   0:     0x7f2aa7d5cf05 - std::backtrace_rs::backtrace::libunwind::trace::h23054e327d0d4b55
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f2aa7d5cf05 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cc587407d7f7f64
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2aa7d5cf05 - std::sys_common::backtrace::_print_fmt::h4feeb59774730d6b
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f2aa7d5cf05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2aa7dadc4b - core::fmt::rt::Argument::fmt::h105051d8ea1ade1e
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
   5:     0x7f2aa7dadc4b - core::fmt::write::hc6043626647b98ea
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
   6:     0x7f2aa7d51bdf - std::io::Write::write_fmt::h0d24b3e0473045db
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
   4:     0x7f2aa7dadc4b - core::fmt::rt::Argument::fmt::h105051d8ea1ade1e
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
   5:     0x7f2aa7dadc4b - core::fmt::write::hc6043626647b98ea
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
   6:     0x7f2aa7d51bdf - std::io::Write::write_fmt::h0d24b3e0473045db
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
   7:     0x7f2aa7d5ccde - std::sys_common::backtrace::_print::h62df6fc36dcebfc8
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2aa7d5ccde - std::sys_common::backtrace::print::h45eb8174d25a1e76
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2aa7d5f719 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   7:     0x7f2aa7d5ccde - std::sys_common::backtrace::_print::h62df6fc36dcebfc8
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2aa7d5ccde - std::sys_common::backtrace::print::h45eb8174d25a1e76
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2aa7d5f719 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
  10:     0x7f2aa7d5f4ba - std::panicking::default_hook::hb5d3b27aa9f6dcda
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:298:9
  10:     0x7f2aa7d5f4ba - std::panicking::default_hook::hb5d3b27aa9f6dcda
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:298:9
  11:     0x7f2aaae150c1 - std[fba9fafec3bdacf8]::panicking::update_hook::<alloc[a325a9cea6fa5e89]::boxed::Box<rustc_driver_impl[ce01f96e2e949677]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f2aa7d5fe4b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2026a29033a1b9f6
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
  13:     0x7f2aa7d5fe4b - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
  14:     0x7f2aa7d5fbc4 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
  15:     0x7f2aa7d5d3c9 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
  11:     0x7f2aaae150c1 - std[fba9fafec3bdacf8]::panicking::update_hook::<alloc[a325a9cea6fa5e89]::boxed::Box<rustc_driver_impl[ce01f96e2e949677]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f2aa7d5fe4b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2026a29033a1b9f6
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
  13:     0x7f2aa7d5fe4b - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
  14:     0x7f2aa7d5fbc4 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
  15:     0x7f2aa7d5d3c9 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f2aa7d5f8f7 - rust_begin_unwind
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
  17:     0x7f2aa7daa1e3 - core::panicking::panic_fmt::ha02418e5cd774672
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
  18:     0x7f2aaaeb8e98 - <rustc_hir[b82cb5fa732ae2da]::definitions::Definitions>::local_def_path_hash_to_def_id::err
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f2aa7d5f8f7 - rust_begin_unwind
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
  17:     0x7f2aa7daa1e3 - core::panicking::panic_fmt::ha02418e5cd774672
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
  18:     0x7f2aaaeb8e98 - <rustc_hir[b82cb5fa732ae2da]::definitions::Definitions>::local_def_path_hash_to_def_id::err
  19:     0x7f2aac2c8e8e - <rustc_query_system[b257ee99c2874caa]::dep_graph::dep_node::DepNode as rustc_middle[ecc07153edf3c281]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  19:     0x7f2aac2c8e8e - <rustc_query_system[b257ee99c2874caa]::dep_graph::dep_node::DepNode as rustc_middle[ecc07153edf3c281]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  20:     0x7f2aab665f7a - <rustc_query_impl[c1633093ec927e0e]::plumbing::query_callback<rustc_query_impl[c1633093ec927e0e]::query_impl::def_kind::QueryType>::{closure#0} as core[1a380081440346cb]::ops::function::FnOnce<(rustc_middle[ecc07153edf3c281]::ty::context::TyCtxt, rustc_query_system[b257ee99c2874caa]::dep_graph::dep_node::DepNode)>>::call_once
  20:     0x7f2aab665f7a - <rustc_query_impl[c1633093ec927e0e]::plumbing::query_callback<rustc_query_impl[c1633093ec927e0e]::query_impl::def_kind::QueryType>::{closure#0} as core[1a380081440346cb]::ops::function::FnOnce<(rustc_middle[ecc07153edf3c281]::ty::context::TyCtxt, rustc_query_system[b257ee99c2874caa]::dep_graph::dep_node::DepNode)>>::call_once
  21:     0x7f2aac22efa9 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  21:     0x7f2aac22efa9 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  22:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  23:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  22:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  23:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  24:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  25:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  24:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  25:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  26:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  26:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  27:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  27:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  28:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  28:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  29:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  29:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  30:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  30:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  31:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  31:     0x7f2aac22ef22 - <rustc_query_system[b257ee99c2874caa]::dep_graph::graph::DepGraphData<rustc_middle[ecc07153edf3c281]::dep_graph::DepsType>>::try_mark_previous_green::<rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt>
  32:     0x7f2aac769dc4 - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::DefaultCache<rustc_type_ir[8d868667529acadd]::canonical::Canonical<rustc_middle[ecc07153edf3c281]::ty::context::TyCtxt, rustc_middle[ecc07153edf3c281]::ty::ParamEnvAnd<rustc_middle[ecc07153edf3c281]::ty::predicate::Predicate>>, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, true>
  32:     0x7f2aac769dc4 - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::DefaultCache<rustc_type_ir[8d868667529acadd]::canonical::Canonical<rustc_middle[ecc07153edf3c281]::ty::context::TyCtxt, rustc_middle[ecc07153edf3c281]::ty::ParamEnvAnd<rustc_middle[ecc07153edf3c281]::ty::predicate::Predicate>>, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, true>
  33:     0x7f2aac768631 - rustc_query_impl[c1633093ec927e0e]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  33:     0x7f2aac768631 - rustc_query_impl[c1633093ec927e0e]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  34:     0x7f2aa9161bab - <rustc_trait_selection[bf98a35716bfd7e5]::traits::fulfill::FulfillProcessor as rustc_data_structures[25e6784d61918b0d]::obligation_forest::ObligationProcessor>::process_obligation
  34:     0x7f2aa9161bab - <rustc_trait_selection[bf98a35716bfd7e5]::traits::fulfill::FulfillProcessor as rustc_data_structures[25e6784d61918b0d]::obligation_forest::ObligationProcessor>::process_obligation
  35:     0x7f2aac206a3d - <rustc_data_structures[25e6784d61918b0d]::obligation_forest::ObligationForest<rustc_trait_selection[bf98a35716bfd7e5]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[bf98a35716bfd7e5]::traits::fulfill::FulfillProcessor>
  35:     0x7f2aac206a3d - <rustc_data_structures[25e6784d61918b0d]::obligation_forest::ObligationForest<rustc_trait_selection[bf98a35716bfd7e5]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[bf98a35716bfd7e5]::traits::fulfill::FulfillProcessor>
  36:     0x7f2aacb76170 - rustc_hir_typeck[624c394323d1dd51]::typeck
  36:     0x7f2aacb76170 - rustc_hir_typeck[624c394323d1dd51]::typeck
  37:     0x7f2aacb748cf - rustc_query_impl[c1633093ec927e0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1633093ec927e0e]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 8usize]>>
  37:     0x7f2aacb748cf - rustc_query_impl[c1633093ec927e0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1633093ec927e0e]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 8usize]>>
  38:     0x7f2aac35d24d - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::VecCache<rustc_span[4d50fd03223eefaa]::def_id::LocalDefId, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, true>
  38:     0x7f2aac35d24d - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::VecCache<rustc_span[4d50fd03223eefaa]::def_id::LocalDefId, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, true>
  39:     0x7f2aacbe0c14 - rustc_query_impl[c1633093ec927e0e]::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
  39:     0x7f2aacbe0c14 - rustc_query_impl[c1633093ec927e0e]::query_impl::typeck::get_query_incr::__rust_end_short_backtrace
  40:     0x7f2aacbdf677 - rustc_hir_analysis[be96d916f40dad1b]::check_crate
  40:     0x7f2aacbdf677 - rustc_hir_analysis[be96d916f40dad1b]::check_crate
  41:     0x7f2aacc9362b - rustc_interface[c31201428b712578]::passes::analysis
  41:     0x7f2aacc9362b - rustc_interface[c31201428b712578]::passes::analysis
  42:     0x7f2aacc93025 - rustc_query_impl[c1633093ec927e0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1633093ec927e0e]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0},

**Comment by jembishop** [comment]
Updating fixed this
