### ISSUE TITLE
Regression of build infrastructure [src/bootstrap/bootstrap.py]

### ISSUE THREAD

**Issue by arttet** [rust-lang/rust#130231]
### Rust Targets

```
arm64e-apple-darwin
```

I didn't expect to see this happen:

```
error occurred: Unknown architecture for macOS target.

Traceback (most recent call last):
  File "/Users/runner/work/rust-compiler-builder/rust-compiler-builder/rust/src/bootstrap/bootstrap.py", line 1230, in <module>
    main()
  File "/Users/runner/work/rust-compiler-builder/rust-compiler-builder/rust/src/bootstrap/bootstrap.py", line 1215, in main
    bootstrap(args)
  File "/Users/runner/work/rust-compiler-builder/rust-compiler-builder/rust/src/bootstrap/bootstrap.py", line 1191, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/Users/runner/work/rust-compiler-builder/rust-compiler-builder/rust/src/bootstrap/bootstrap.py", line 202, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /Users/runner/work/rust-compiler-builder/rust-compiler-
builder/rust/build/bootstrap/debug/bootstrap build --stage 2
```

### How to reproduce

```
./configure \
		--enable-option-checking \
		--enable-verbose-tests \
		--codegen-backends=llvm \
		--enable-codegen-tests \
		--enable-dist-src \
		--tools=cargo,clippy,rustdoc,rustfmt,rust-analyzer,analysis,src \
		--target=arm64e-apple-darwin,aarch64-apple-darwin \
		--set llvm.download-ci-llvm=true \
		--set build.verbose=0 \
		--set rust.channel=dev \
		--set rust.description="" \
		--set rust.use-lld=true \
		--dist-compression-formats=xz \
		--prefix=install
```

**Comment by arttet** [comment]
This issue is related to [this](https://github.com/rust-lang/cc-rs/issues/1205)

**Comment by arttet** [comment]
Hey @onur-ozkan,

I can confirm that this issue was fixed. Thank you.
