### ISSUE TITLE
chrono dependency unexpected 🧊 es

### ISSUE THREAD

**Issue by drahnr** [rust-lang/rust#130606]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7

```

### Error output

```
error: internal compiler error: compiler/rustc_metadata/src/rmeta/decoder.rs:946:9: missing `def_ident_span` for DefId(49:559 ~ chrono[e135]::format)

thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:946:9:
Box<dyn Any>
stack backtrace:
<snip - see below>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.79.0 (129f3b996 2024-06-10) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C linker=clang -C link-arg=-fuse-ld=/usr/bin/mold

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [module_children] collecting child items of module `chrono`
#1 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:946:9:
Box<dyn Any>
stack backtrace:
   0:     0x7f48b77c2035 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x7f48b77c2035 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f48b77c2035 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f48b77c2035 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f48b781129b - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:     0x7f48b781129b - core::fmt::write::hc090a2ffd6b28c4a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:     0x7f48b77b6bdf - std::io::Write::write_fmt::h8898bac6ff039a23
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:     0x7f48b77c1e0e - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f48b77c1e0e - std::sys_common::backtrace::print::ha96650907276675e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f48b77c4779 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
  10:     0x7f48b77c44bd - std::panicking::default_hook::h207342be97478370
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
  11:     0x7f48b44891b7 - std[3c8ba8ebcf555201]::panicking::update_hook::<alloc[bfbae7e348dce413]::boxed::Box<rustc_driver_impl[c88438ade88661f4]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f48b77c4e76 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha9c3bc81d312fd83
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  13:     0x7f48b77c4e76 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
  14:     0x7f48b44b6b44 - std[3c8ba8ebcf555201]::panicking::begin_panic::<rustc_errors[80cf825e20fac581]::ExplicitBug>::{closure#0}
  15:     0x7f48b44b34f6 - std[3c8ba8ebcf555201]::sys_common::backtrace::__rust_end_short_backtrace::<std[3c8ba8ebcf555201]::panicking::begin_panic<rustc_errors[80cf825e20fac581]::ExplicitBug>::{closure#0}, !>
  16:     0x7f48b44aeb66 - std[3c8ba8ebcf555201]::panicking::begin_panic::<rustc_errors[80cf825e20fac581]::ExplicitBug>
  17:     0x7f48b44bff01 - <rustc_errors[80cf825e20fac581]::diagnostic::BugAbort as rustc_errors[80cf825e20fac581]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  18:     0x7f48b4939b1c - rustc_middle[3ff731b746e7b038]::util::bug::opt_span_bug_fmt::<rustc_span[8c7415e9d33ddd75]::span_encoding::Span>::{closure#0}
  19:     0x7f48b4920c2a - rustc_middle[3ff731b746e7b038]::ty::context::tls::with_opt::<rustc_middle[3ff731b746e7b038]::util::bug::opt_span_bug_fmt<rustc_span[8c7415e9d33ddd75]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  20:     0x7f48b4920acb - rustc_middle[3ff731b746e7b038]::ty::context::tls::with_context_opt::<rustc_middle[3ff731b746e7b038]::ty::context::tls::with_opt<rustc_middle[3ff731b746e7b038]::util::bug::opt_span_bug_fmt<rustc_span[8c7415e9d33ddd75]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  21:     0x7f48b2691740 - rustc_middle[3ff731b746e7b038]::util::bug::bug_fmt
  22:     0x7f48b4883bcf - <rustc_metadata[2110655d3a559aa6]::creader::CrateMetadataRef>::missing
  23:     0x7f48b59b2af1 - <core[868bc93c3f2beb33]::iter::sources::from_coroutine::FromCoroutine<<rustc_metadata[2110655d3a559aa6]::creader::CrateMetadataRef>::get_module_children::{closure#0}> as core[868bc93c3f2beb33]::iter::traits::iterator::Iterator>::next
  24:     0x7f48b59b0789 - rustc_metadata[2110655d3a559aa6]::rmeta::decoder::cstore_impl::provide_extern::module_children
  25:     0x7f48b59b039c - rustc_query_impl[a12402620de91e8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a12402620de91e8]::query_impl::module_children::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7f48b59b0375 - <rustc_query_impl[a12402620de91e8]::query_impl::module_children::dynamic_query::{closure#2} as core[868bc93c3f2beb33]::ops::function::FnOnce<(rustc_middle[3ff731b746e7b038]::ty::context::TyCtxt, rustc_span[8c7415e9d33ddd75]::def_id::DefId)>>::call_once
  27:     0x7f48b5987c94 - rustc_query_system[4e189ce2c77124d]::query::plumbing::try_execute_query::<rustc_query_impl[a12402620de91e8]::DynamicConfig<rustc_query_system[4e189ce2c77124d]::query::caches::DefIdCache<rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[a12402620de91e8]::plumbing::QueryCtxt, false>
  28:     0x7f48b5986121 - rustc_query_impl[a12402620de91e8]::query_impl::module_children::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f48b5985ffd - rustc_middle[3ff731b746e7b038]::query::plumbing::query_get_at::<rustc_query_system[4e189ce2c77124d]::query::caches::DefIdCache<rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 16usize]>>>
  30:     0x7f48b5c7238e - <rustc_resolve[7e610bf430b13343]::Resolver>::build_reduced_graph_external
  31:     0x7f48b5c6ba07 - <rustc_resolve[7e610bf430b13343]::Resolver>::resolve_ident_in_module_unadjusted_ext
  32:     0x7f48b64a8e48 - <rustc_resolve[7e610bf430b13343]::Resolver>::resolve_path_with_ribs
  33:     0x7f48b6030f6b - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::smart_resolve_path_fragment
  34:     0x7f48b6024056 - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::resolve_expr
  35:     0x7f48b60217dd - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::resolve_expr
  36:     0x7f48b6021a97 - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::resolve_expr
  37:     0x7f48b60232be - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::resolve_expr
  38:     0x7f48b6021ab9 - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::resolve_expr
  39:     0x7f48b602125e - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor>::resolve_block
  40:     0x7f48b602c59a - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor as rustc_ast[da7dcc15d95328b0]::visit::Visitor>::visit_fn
  41:     0x7f48b604687f - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor as rustc_ast[da7dcc15d95328b0]::visit::Visitor>::visit_item
  42:     0x7f48b6043f09 - rustc_ast[da7dcc15d95328b0]::visit::walk_assoc_item::<rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor, rustc_ast[da7dcc15d95328b0]::ast::ItemKind>
  43:     0x7f48b604bb11 - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor as rustc_ast[da7dcc15d95328b0]::visit::Visitor>::visit_item
  44:     0x7f48b6043f09 - rustc_ast[da7dcc15d95328b0]::visit::walk_assoc_item::<rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor, rustc_ast[da7dcc15d95328b0]::ast::ItemKind>
  45:     0x7f48b604bb11 - <rustc_resolve[7e610bf430b13343]::late::LateResolutionVisitor as rustc_ast[da7dcc15d95328b0]::visit::Visitor>::visit_item
  46:     0x7f48b5c5f2b9 - <rustc_resolve[7e610bf430b13343]::Resolver>::resolve_crate::{closure#0}
  47:     0x7f48b6181bc6 - <rustc_resolve[7e610bf430b13343]::Resolver>::resolve_crate
  48:     0x7f48b5df434d - rustc_interface[640972162e3c086f]::passes::resolver_for_lowering_raw
  49:     0x7f48b5df34db - rustc_query_impl[a12402620de91e8]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a12402620de91e8]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 16usize]>>
  50:     0x7f48b5df34c9 - <rustc_query_impl[a12402620de91e8]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[868bc93c3f2beb33]::ops::function::FnOnce<(rustc_middle[3ff731b746e7b038]::ty::context::TyCtxt, ())>>::call_once
  51:     0x7f48b64e463b - rustc_query_system[4e189ce2c77124d]::query::plumbing::try_execute_query::<rustc_query_impl[a12402620de91e8]::DynamicConfig<rustc_query_system[4e189ce2c77124d]::query::caches::SingleCache<rustc_middle[3ff731b746e7b038]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[a12402620de91e8]::plumbing::QueryCtxt, false>
  52:     0x7f48b64e4201 - rustc_query_impl[a12402620de91e8]::query_impl::resolver_for_lowering_raw::get_query_non_incr::__rust_end_short_backtrace
  53:     0x7f48b6382fba - rustc_interface[640972162e3c086f]::interface::run_compiler::<core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>, rustc_driver_impl[c88438ade88661f4]::run_compiler::{closure#0}>::{closure#1}
  54:     0x7f48b6340f8b - std[3c8ba8ebcf555201]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[640972162e3c086f]::util::run_in_thread_with_globals<rustc_interface[640972162e3c086f]::interface::run_compiler<core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>, rustc_driver_impl[c88438ade88661f4]::run_compiler::{closure#0}>::{closure#1}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>
  55:     0x7f48b6340d80 - <<std[3c8ba8ebcf555201]::thread::Builder>::spawn_unchecked_<rustc_interface[640972162e3c086f]::util::run_in_thread_with_globals<rustc_interface[640972162e3c086f]::interface::run_compiler<core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>, rustc_driver_impl[c88438ade88661f4]::run_compiler::{closure#0}>::{closure#1}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[868bc93c3f2beb33]::result::Result<(), rustc_span[8c7415e9d33ddd75]::ErrorGuaranteed>>::{closure#2} as core[868bc93c3f2beb33]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  56:     0x7f48b77cecab - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h09e5a4c541afa800
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  57:     0x7f48b77cecab - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9c8b03c22f4e7026
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  58:     0x7f48b77cecab - std::sys::pal::unix::thread::Thread::new::thread_start::h522bc89a54da820a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread.rs:108:17
  59:     0x7f48b14ac897 - start_thread
  60:     0x7f48b1533a5c - __clone3
  61:                0x0 - <unknown>
```

</p>
</details>

**Comment by SpriteOvO** [comment]
@drahnr Hi! Can you provide a minimal reproducible code? Also, I noticed that the ICE happens on an older version of rustc, can you update Rust to the latest to check if the ICE is still happening?
