### ISSUE TITLE
empty binary with dependency on serde; rustc panics when building proc_macro2

### ISSUE THREAD

**Issue by jobafr** [rust-lang/rust#132298]
### Code

Empty binary (straight from `cargo new`), with a dependency to this serde version.

```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: aarch64-unknown-linux-gnu
release: 1.74.1
LLVM version: 17.0.4
```

Operating System is Ubuntu 22.04. Computer is a Radxa Rock 5b (Single-Board computer based on Rockchip rk3588). The bug does not happen in nightly and stable (1.82.0), but for some reason, I can build the same code on Ubuntu 20.04 with Rust 1.74.1 without problems. It does not make a difference whether or not I use `--release`.

### Error output

```
$ cargo build --release
   Compiling proc-macro2 v1.0.89
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:999:66:
index out of bounds: the len is 1 but the index is 114
stack backtrace:
   0:     0xffffb3358d98 - std::backtrace_rs::backtrace::libunwind::trace::heef1386c69141c0e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xffffb3358d98 - std::backtrace_rs::backtrace::trace_unsynchronized::hf52898491dc115b3
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xffffb3358d98 - std::sys_common::backtrace::_print_fmt::h54a977219eb084db
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xffffb3358d98 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14034993f2dfde80
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xffffb33b4dc4 - core::fmt::rt::Argument::fmt::hc7ab06fc179a0538
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0xffffb33b4dc4 - core::fmt::write::h5c1b4d7dd1fe1297
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0xffffb334dc3c - std::io::Write::write_fmt::h5288162c5e42a3a2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0xffffb3358bcc - std::sys_common::backtrace::_print::he08b7cac662e6bf2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xffffb3358bcc - std::sys_common::backtrace::print::hfc02f4f778cfba10
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xffffb335b6dc - std::panicking::default_hook::{{closure}}::ha5e3ccf8ff24afce
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0xffffb335b3f0 - std::panicking::default_hook::h8515e68938392e65
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0xffffb3f5e564 - std[6b8b961216ba2a7f]::panicking::update_hook::<alloc[4f8e73ea9b6a9722]::boxed::Box<rustc_driver_impl[cea993793326056d]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0xffffb335befc - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h765c9f0a4b156b2b
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
  13:     0xffffb335befc - std::panicking::rust_panic_with_hook::hc79d39f29b02a8f2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
  14:     0xffffb335bc88 - std::panicking::begin_panic_handler::{{closure}}::hc334b8544d985752
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
  15:     0xffffb335927c - std::sys_common::backtrace::__rust_end_short_backtrace::h1479ad9e3d67013a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  16:     0xffffb335b9e0 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  17:     0xffffb3323fc4 - core::panicking::panic_fmt::h35c6be226eceb7e0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  18:     0xffffb3324108 - core::panicking::panic_bounds_check::h342f42cff8edc89b
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:180:5
  19:     0xffffb8291bd0 - <rustc_span[81ab1e5a2bd706f8]::def_id::CrateNum as rustc_serialize[cca6886dce726f40]::serialize::Decodable<rustc_metadata[3ffe5d51d5709cb]::rmeta::decoder::DecodeContext>>::decode
  20:     0xffffb8292da4 - <rustc_span[81ab1e5a2bd706f8]::SpanData as rustc_serialize[cca6886dce726f40]::serialize::Decodable<rustc_metadata[3ffe5d51d5709cb]::rmeta::decoder::DecodeContext>>::decode
  21:     0xffffb8292a94 - <rustc_span[81ab1e5a2bd706f8]::span_encoding::Span as rustc_serialize[cca6886dce726f40]::serialize::Decodable<rustc_metadata[3ffe5d51d5709cb]::rmeta::decoder::DecodeContext>>::decode
  22:     0xffffb82dc5e8 - <alloc[4f8e73ea9b6a9722]::vec::Vec<rustc_middle[5cd7730d9c586083]::mir::SourceScopeData> as rustc_serialize[cca6886dce726f40]::serialize::Decodable<rustc_metadata[3ffe5d51d5709cb]::rmeta::decoder::DecodeContext>>::decode
  23:     0xffffb81d0278 - <rustc_middle[5cd7730d9c586083]::mir::Body as rustc_serialize[cca6886dce726f40]::serialize::Decodable<rustc_metadata[3ffe5d51d5709cb]::rmeta::decoder::DecodeContext>>::decode
  24:     0xffffb826172c - rustc_metadata[3ffe5d51d5709cb]::rmeta::decoder::cstore_impl::provide_extern::optimized_mir
  25:     0xffffb7ca6274 - rustc_query_impl[d6bd33a5c51be834]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d6bd33a5c51be834]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 8usize]>>
  26:     0xffffb7e3acb8 - <rustc_query_impl[d6bd33a5c51be834]::query_impl::optimized_mir::dynamic_query::{closure#2} as core[f5820ae382bd3d]::ops::function::FnOnce<(rustc_middle[5cd7730d9c586083]::ty::context::TyCtxt, rustc_span[81ab1e5a2bd706f8]::def_id::DefId)>>::call_once
  27:     0xffffb7e9519c - rustc_query_system[4cf429313b71befe]::query::plumbing::try_execute_query::<rustc_query_impl[d6bd33a5c51be834]::DynamicConfig<rustc_query_system[4cf429313b71befe]::query::caches::DefaultCache<rustc_span[81ab1e5a2bd706f8]::def_id::DefId, rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[d6bd33a5c51be834]::plumbing::QueryCtxt, false>
  28:     0xffffb7cdbad8 - rustc_query_impl[d6bd33a5c51be834]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  29:     0xffffb8a6de20 - rustc_middle[5cd7730d9c586083]::query::plumbing::query_get_at::<rustc_query_system[4cf429313b71befe]::query::caches::DefaultCache<rustc_span[81ab1e5a2bd706f8]::def_id::DefId, rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 8usize]>>>
  30:     0xffffb8a72720 - <rustc_middle[5cd7730d9c586083]::ty::context::TyCtxt>::instance_mir
  31:     0xffffb7217cd8 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_used_items
  32:     0xffffb7216a04 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  33:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  34:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  35:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  36:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  37:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  38:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  39:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  40:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  41:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  42:     0xffffb7216e38 - rustc_monomorphize[bd31c5be202dd716]::collector::collect_items_rec
  43:     0xffffb722f234 - <core[f5820ae382bd3d]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[cd012cadb77dd83c]::sync::parallel::disabled::par_for_each_in<alloc[4f8e73ea9b6a9722]::vec::Vec<rustc_middle[5cd7730d9c586083]::mir::mono::MonoItem>, rustc_monomorphize[bd31c5be202dd716]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}> as core[f5820ae382bd3d]::ops::function::FnOnce<()>>::call_once
  44:     0xffffb7243078 - rustc_data_structures[cd012cadb77dd83c]::sync::parallel::disabled::par_for_each_in::<alloc[4f8e73ea9b6a9722]::vec::Vec<rustc_middle[5cd7730d9c586083]::mir::mono::MonoItem>, rustc_monomorphize[bd31c5be202dd716]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  45:     0xffffb722c0e4 - <rustc_session[1c993671b078983]::session::Session>::time::<(), rustc_monomorphize[bd31c5be202dd716]::collector::collect_crate_mono_items::{closure#1}>
  46:     0xffffb721556c - rustc_monomorphize[bd31c5be202dd716]::collector::collect_crate_mono_items
  47:     0xffffb721dc18 - rustc_monomorphize[bd31c5be202dd716]::partitioning::collect_and_partition_mono_items
  48:     0xffffb7ca9be0 - rustc_query_impl[d6bd33a5c51be834]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d6bd33a5c51be834]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 24usize]>>
  49:     0xffffb7d464b4 - <rustc_query_impl[d6bd33a5c51be834]::query_impl::collect_and_partition_mono_items::dynamic_query::{closure#2} as core[f5820ae382bd3d]::ops::function::FnOnce<(rustc_middle[5cd7730d9c586083]::ty::context::TyCtxt, ())>>::call_once
  50:     0xffffb7e69514 - rustc_query_system[4cf429313b71befe]::query::plumbing::try_execute_query::<rustc_query_impl[d6bd33a5c51be834]::DynamicConfig<rustc_query_system[4cf429313b71befe]::query::caches::SingleCache<rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[d6bd33a5c51be834]::plumbing::QueryCtxt, false>
  51:     0xffffb7cfe270 - rustc_query_impl[d6bd33a5c51be834]::query_impl::collect_and_partition_mono_items::get_query_non_incr::__rust_end_short_backtrace
  52:     0xffffb7f0ad6c - rustc_codegen_ssa[aebf214b54425532]::back::symbol_export::exported_symbols_provider_local
  53:     0xffffb7ca7118 - rustc_query_impl[d6bd33a5c51be834]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d6bd33a5c51be834]::query_impl::exported_symbols::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 16usize]>>
  54:     0xffffb7d85008 - <rustc_query_impl[d6bd33a5c51be834]::query_impl::exported_symbols::dynamic_query::{closure#2} as core[f5820ae382bd3d]::ops::function::FnOnce<(rustc_middle[5cd7730d9c586083]::ty::context::TyCtxt, rustc_span[81ab1e5a2bd706f8]::def_id::CrateNum)>>::call_once
  55:     0xffffb7ebd8ec - rustc_query_system[4cf429313b71befe]::query::plumbing::try_execute_query::<rustc_query_impl[d6bd33a5c51be834]::DynamicConfig<rustc_query_system[4cf429313b71befe]::query::caches::VecCache<rustc_span[81ab1e5a2bd706f8]::def_id::CrateNum, rustc_middle[5cd7730d9c586083]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[d6bd33a5c51be834]::plumbing::QueryCtxt, false>
  56:     0xffffb7cfdf98 - rustc_query_impl[d6bd33a5c51be834]::query_impl::exported_symbols::get_query_non_incr::__rust_end_short_backtrace
  57:     0xffffb81a5c98 - <rustc_metadata[3ffe5d51d5709cb]::rmeta::encoder::EncodeContext>::encode_crate_root
  58:     0xffffb81ad290 - rustc_metadata[3ffe5d51d5709cb]::rmeta::encoder::encode_metadata_impl
  59:     0xffffb824e9f4 - rustc_data_structures[cd012cadb77dd83c]::sync::parallel::disabled::join::<rustc_metadata[3ffe5d51d5709cb]::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata[3ffe5d51d5709cb]::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  60:     0xffffb81ac6b8 - rustc_metadata[3ffe5d51d5709cb]::rmeta::encoder::encode_metadata
  61:     0xffffb81c8918 - rustc_metadata[3ffe5d51d5709cb]::fs::encode_and_write_metadata
  62:     0xffffb40d28d0 - rustc_interface[42246dc7ebab8ec4]::passes::start_codegen
  63:     0xffffb40b96b4 - <rustc_middle[5cd7730d9c586083]::ty::context::GlobalCtxt>::enter::<<rustc_interface[42246dc7ebab8ec4]::queries::Queries>::ongoing_codegen::{closure#0}, core[f5820ae382bd3d]::result::Result<alloc[4f8e73ea9b6a9722]::boxed::Box<dyn core[f5820ae382bd3d]::any::Any>, rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>>
  64:     0xffffb409eedc - <rustc_interface[42246dc7ebab8ec4]::queries::Queries>::ongoing_codegen
  65:     0xffffb3f6d328 - rustc_span[81ab1e5a2bd706f8]::set_source_map::<core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>, rustc_interface[42246dc7ebab8ec4]::interface::run_compiler<core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>, rustc_driver_impl[cea993793326056d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  66:     0xffffb3f5d860 - std[6b8b961216ba2a7f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[42246dc7ebab8ec4]::util::run_in_thread_with_globals<rustc_interface[42246dc7ebab8ec4]::interface::run_compiler<core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>, rustc_driver_impl[cea993793326056d]::run_compiler::{closure#1}>::{closure#0}, core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>>
  67:     0xffffb3f5e9cc - <<std[6b8b961216ba2a7f]::thread::Builder>::spawn_unchecked_<rustc_interface[42246dc7ebab8ec4]::util::run_in_thread_with_globals<rustc_interface[42246dc7ebab8ec4]::interface::run_compiler<core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>, rustc_driver_impl[cea993793326056d]::run_compiler::{closure#1}>::{closure#0}, core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f5820ae382bd3d]::result::Result<(), rustc_span[81ab1e5a2bd706f8]::ErrorGuaranteed>>::{closure#1} as core[f5820ae382bd3d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  68:     0xffffb3365d44 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hecfad312c6eb2bd9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
  69:     0xffffb3365d44 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h16e8d93f3daf4d79
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
  70:     0xffffb3365d44 - std::sys::unix::thread::Thread::new::thread_start::he57adeb5083c7c94
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  71:     0xffffb315d5c8 - start_thread
                               at ./nptl/pthread_create.c:442:8
  72:     0xffffb31c5d9c - thread_start
                               at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:79
  73:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.74.1 (a28077b28 2023-12-04) running on aarch64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debug-assertions=off

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `core::str::pattern::TwoWaySearcher::next`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
#2 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
error: could not compile `proc-macro2` (lib)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build --release
   Compiling proc-macro2 v1.0.89
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:999:66:
index out of bounds: the len is 1 but the index is 114
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:180:5
   3: <rustc_span::def_id::CrateNum as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_span::SpanData as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   5: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   6: <alloc::vec::Vec<rustc_middle::mir::SourceScopeData> as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   7: <rustc_middle::mir::Body as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   8: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir
      [... omitted 2 frames ...]
   9: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
  10: <rustc_middle::ty::context::TyCtxt>::instance_mir
  11: rustc_monomorphize::collector::collect_used_items
  12: rustc_monomorphize::collector::collect_items_rec
  13: rustc_monomorphize::collector::collect_items_rec
  14: rustc_monomorphize::collector::collect_items_rec
  15: rustc_monomorphize::collector::collect_items_rec
  16: rustc_monomorphize::collector::collect_items_rec
  17: rustc_monomorphize::collector::collect_items_rec
  18: rustc_monomorphize::collector::collect_items_rec
  19: rustc_monomorphize::collector::collect_items_rec
  20: rustc_monomorphize::collector::collect_items_rec
  21: rustc_monomorphize::collector::collect_items_rec
  22: rustc_monomorphize::collector::collect_items_rec
  23: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::parallel::disabled::par_for_each_in<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
  24: rustc_data_structures::sync::parallel::disabled::par_for_each_in::<alloc::vec::Vec<rustc_middle::mir::mono::MonoItem>, rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
  25: <rustc_session::session::Session>::time::<(), rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}>
  26: rustc_monomorphize::collector::collect_crate_mono_items
  27: rustc_monomorphize::partitioning::collect_and_partition_mono_items
      [... omitted 2 frames ...]
  28: rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local
      [... omitted 2 frames ...]
  29: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  30: rustc_metadata::rmeta::encoder::encode_metadata_impl
  31: rustc_data_structures::sync::parallel::disabled::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
  32: rustc_metadata::rmeta::encoder::encode_metadata
  33: rustc_metadata::fs::encode_and_write_metadata
  34: rustc_interface::passes::start_codegen
  35: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
  36: <rustc_interface::queries::Queries>::ongoing_codegen
  37: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.74.1 (a28077b28 2023-12-04) running on aarch64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debug-assertions=off

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `core::str::pattern::TwoWaySearcher::next`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
#2 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
error: could not compile `proc-macro2` (lib)
```

</p>
</details>

**Comment by jieyouxu** [comment]
Isn't rustc 1.74.1 quite old? Does this reproduce on the latest stable?

**Comment by jieyouxu** [comment]
Given that this does not appear to affect latest stable and that it's 1.74.1 and multiple changes to how metadata is encoded has occurred over subsequent releases, I'm inclined to close this as not actionable -- it lacks a reproduction on latest stable.
