### ISSUE TITLE
the compiler unexpectedly panicked. this is a bug.

### ISSUE THREAD

**Issue by gavinma86** [rust-lang/rust#132589]
### Code

```Rust
    error!("Processing decode: {:?}", name.to_ascii().as_str());

    let info_part = name.iter().nth(0).ok_or("Missing info part")?;
    let info = decode_info(info_part)?;
    error!("{} {} {}", name, info, client_address);
    let v_m = name.iter().nth(1).ok_or("Missing v_m")?;
    let v_j = name.iter().nth(2).ok_or("Missing v_j")?;
```

### Meta

`rustc --version --verbose`:
```
note: rustc 1.80.1 (3f5fd8dd4 2024-08-06) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]
```

### Error output

```
thread 'rustc' panicked at compiler\rustc_span\src\lib.rs:2119:17:
assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
stack backtrace:
   0:     0x7ffb18983b3d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffb18983b3d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffb18983b3d - std::sys_common::backtrace::_print_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ffb18983b3d - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ffb189b4779 - core::fmt::rt::Argument::fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\rt.rs:165
   5:     0x7ffb189b4779 - core::fmt::write
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\fmt\mod.rs:1168
   6:     0x7ffb1897a2d1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\io\mod.rs:1835
   7:     0x7ffb18983916 - std::sys_common::backtrace::print
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ffb18986af8 - std::panicking::default_hook::closure$1
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:271
   9:     0x7ffb189867a6 - std::panicking::default_hook
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:298
  10:     0x7ffb0d4cf8cc - memchr
  11:     0x7ffb18987127 - alloc::boxed::impl$50::call
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\alloc\src\boxed.rs:2077
  12:     0x7ffb18987127 - std::panicking::rust_panic_with_hook
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:799
  13:     0x7ffb18986f79 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:656
  14:     0x7ffb189844af - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys_common\backtrace.rs:171
  15:     0x7ffb18986c68 - std::panicking::begin_panic_handler
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\panicking.rs:652
  16:     0x7ffb189dd124 - core::panicking::panic_fmt
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:72
  17:     0x7ffb189dd1ed - core::panicking::panic
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\core\src\panicking.rs:146
  18:     0x7ffb0d459f9d - <rustc_span[a229f81d2e77fa80]::source_map::SourceMap>::lookup_char_pos
  19:     0x7ffb0c0f7d6c - <<rustc_errors[3b3b7ad1e174fa8f]::json::Diagnostic>::from_errors_diagnostic::BufWriter as std[f01c98544d5f9dc9]::io::Write>::flush
  20:     0x7ffb0c0f7965 - <<rustc_errors[3b3b7ad1e174fa8f]::json::Diagnostic>::from_errors_diagnostic::BufWriter as std[f01c98544d5f9dc9]::io::Write>::flush
  21:     0x7ffb0c0f9970 - <<rustc_errors[3b3b7ad1e174fa8f]::json::Diagnostic>::from_errors_diagnostic::BufWriter as std[f01c98544d5f9dc9]::io::Write>::flush
  22:     0x7ffb0c0f5f6a - <rustc_errors[3b3b7ad1e174fa8f]::json::JsonEmitter as rustc_errors[3b3b7ad1e174fa8f]::emitter::Emitter>::emit_artifact_notification
  23:     0x7ffb0c0f5c5c - <rustc_errors[3b3b7ad1e174fa8f]::json::JsonEmitter as rustc_errors[3b3b7ad1e174fa8f]::emitter::Emitter>::emit_diagnostic
  24:     0x7ffb0c1027b5 - <rustc_errors[3b3b7ad1e174fa8f]::DiagCtxt>::emit_future_breakage_report
  25:     0x7ffb0941985f - <time[423df0c64135d13e]::format_description::component::Component as core[911ab0b3a5f9874b]::convert::From<time[423df0c64135d13e]::format_description::parse::format_item::Component>>::from
  26:     0x7ffb0c10010c - <rustc_errors[3b3b7ad1e174fa8f]::DiagCtxt>::emit_future_breakage_report
  27:     0x7ffb0c0ffac6 - <rustc_errors[3b3b7ad1e174fa8f]::DiagCtxt>::emit_diagnostic
  28:     0x7ffb0de6c785 - <rustc_ty_utils[12bfbdf018900c0f]::opaque_types::OpaqueTypeCollector as rustc_type_ir[e902431ed2c03425]::visit::TypeVisitor<rustc_middle[a05eb60f870ca86]::ty::context::TyCtxt>>::visit_ty
  29:     0x7ffb0ca8d42c - rustc_ty_utils[12bfbdf018900c0f]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  30:     0x7ffb0ca8c910 - rustc_ty_utils[12bfbdf018900c0f]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  31:     0x7ffb0bcdaafd - rustc_ty_utils[12bfbdf018900c0f]::ty::adt_sized_constraint
  32:     0x7ffb0bd7d66b - rustc_query_impl[ab3364ab44480fa]::query_system
  33:     0x7ffb0c41c485 - rustc_hir_analysis[d5fc9606ad539481]::check_crate
  34:     0x7ffb0c188356 - rustc_interface[6352c0d0dad531d8]::passes::analysis
  35:     0x7ffb0bd6aa2a - <dyn std[f01c98544d5f9dc9]::io::Write as nu_ansi_term[b580bdfef923f163]::write::AnyWrite>::write_str
  36:     0x7ffb0bce17b2 - rustc_ty_utils[12bfbdf018900c0f]::ty::adt_sized_constraint
  37:     0x7ffb0bd73373 - rustc_query_impl[ab3364ab44480fa]::query_system
  38:     0x7ffb093e658d - _wpgmptr
  39:     0x7ffb093e39b6 - _wpgmptr
  40:     0x7ffb093eb3f9 - _wpgmptr
  41:     0x7ffb1899832d - alloc::boxed::impl$48::call_once
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\alloc\src\boxed.rs:2063
  42:     0x7ffb1899832d - alloc::boxed::impl$48::call_once
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\alloc\src\boxed.rs:2063
  43:     0x7ffb1899832d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library\std\src\sys\pal\windows\thread.rs:52
  44:     0x7ffbc9187374 - BaseThreadInitThunk
  45:     0x7ffbca23cc91 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by gavinma86** [comment]
name is DNS query name()

**Comment by jieyouxu** [comment]
> bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32

Huh, did the `time` diagnostics have a `+ BytePos(1)` somewhere

**Comment by gavinma86** [comment]
The same code can be regenerated with cargo clean...

**Comment by jieyouxu** [comment]
Marking this as incr-comp because I feel like the span assertion shouldn't be firing...
