### ISSUE TITLE
ICE building Leptos 0.7.0 release candidate

### ISSUE THREAD

**Issue by paul-hansen** [rust-lang/rust#132743]
```
git clone https://github.com/leptos-rs/leptos.git
git checkout v0.7.0-rc1
cargo +nightly build --features=nightly
```

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (854980293 2024-11-06)
```

### Error output

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:1501:75:
called `Option::unwrap()` on a `None` value
stack backtrace:
 <ATTACHED_IN_FOLD_BELOW>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/paul/Projects/Rust/leptos/rustc-ice-2024-11-07T19_36_32-519661.txt` to your bug report

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
panicked at compiler/rustc_metadata/src/rmeta/decoder.rs:1499:14:
lock was already held
thread panicked while processing panic. aborting.
warning: `leptos` (lib doc) generated 9 warnings
error: could not document `leptos`

Caused by:
  process didn't exit successfully: `/home/paul/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustdoc --edition=2021 --crate-type lib --crate-name leptos leptos/src/lib.rs -o /home/paul/Projects/Rust/leptos/target/doc --cfg 'feature="base64"' --cfg 'feature="hydration"' --cfg 'feature="nightly"' --cfg 'feature="nonce"' --cfg 'feature="rand"' --cfg 'feature="ssr"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("base64", "csr", "default-tls", "delegation", "experimental-islands", "hydrate", "hydration", "leptos-spin-macro", "nightly", "nonce", "rand", "rkyv", "rustls", "spin", "ssr", "trace-component-props", "tracing"))' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=125 -C metadata=4986dd1d7729d272 -L dependency=/home/paul/Projects/Rust/leptos/target/debug/deps --extern any_spawner=/home/paul/Projects/Rust/leptos/target/debug/deps/libany_spawner-8ec32e91f73eeb66.rmeta --extern base64=/home/paul/Projects/Rust/leptos/target/debug/deps/libbase64-5b4bb36afce686df.rmeta --extern cfg_if=/home/paul/Projects/Rust/leptos/target/debug/deps/libcfg_if-28569b4d9cc7a1cd.rmeta --extern either_of=/home/paul/Projects/Rust/leptos/target/debug/deps/libeither_of-85f8f1e4e7923eb2.rmeta --extern futures=/home/paul/Projects/Rust/leptos/target/debug/deps/libfutures-8f0694dd02f62e51.rmeta --extern hydration_context=/home/paul/Projects/Rust/leptos/target/debug/deps/libhydration_context-c507925549c44cdb.rmeta --extern leptos_config=/home/paul/Projects/Rust/leptos/target/debug/deps/libleptos_config-94e368c4e81eca15.rmeta --extern leptos_dom=/home/paul/Projects/Rust/leptos/target/debug/deps/libleptos_dom-09a2dbb6bf5ccfe2.rmeta --extern leptos_hot_reload=/home/paul/Projects/Rust/leptos/target/debug/deps/libleptos_hot_reload-c0b783ffb5007bd9.rmeta --extern leptos_macro=/home/paul/Projects/Rust/leptos/target/debug/deps/libleptos_macro-bcd4e6e7a9a9b68f.so --extern leptos_server=/home/paul/Projects/Rust/leptos/target/debug/deps/libleptos_server-bb2c3b05cd3485e6.rmeta --extern oco_ref=/home/paul/Projects/Rust/leptos/target/debug/deps/liboco_ref-fd587708a776fb03.rmeta --extern or_poisoned=/home/paul/Projects/Rust/leptos/target/debug/deps/libor_poisoned-d176fd0438fd8b33.rmeta --extern paste=/home/paul/Projects/Rust/leptos/target/debug/deps/libpaste-328a92098632ae7d.so --extern rand=/home/paul/Projects/Rust/leptos/target/debug/deps/librand-30c835847f6d22e5.rmeta --extern reactive_graph=/home/paul/Projects/Rust/leptos/target/debug/deps/libreactive_graph-9ab10128d90d0103.rmeta --extern rustc_hash=/home/paul/Projects/Rust/leptos/target/debug/deps/librustc_hash-acd8c8c1044f0b17.rmeta --extern send_wrapper=/home/paul/Projects/Rust/leptos/target/debug/deps/libsend_wrapper-cb16a25fa604440b.rmeta --extern serde=/home/paul/Projects/Rust/leptos/target/debug/deps/libserde-d8ae5066e8539a02.rmeta --extern serde_qs=/home/paul/Projects/Rust/leptos/target/debug/deps/libserde_qs-250ccb8d36e3a1ea.rmeta --extern server_fn=/home/paul/Projects/Rust/leptos/target/debug/deps/libserver_fn-677563e5ad6194b7.rmeta --extern slotmap=/home/paul/Projects/Rust/leptos/target/debug/deps/libslotmap-2b424e949df38b08.rmeta --extern tachys=/home/paul/Projects/Rust/leptos/target/debug/deps/libtachys-5a1a478a2d76a836.rmeta --extern thiserror=/home/paul/Projects/Rust/leptos/target/debug/deps/libthiserror-24ee2d2630c62cce.rmeta --extern throw_error=/home/paul/Projects/Rust/leptos/target/debug/deps/libthrow_error-dad2886552bcdefd.rmeta --extern typed_builder=/home/paul/Projects/Rust/leptos/target/debug/deps/libtyped_builder-20a770402c60d512.rmeta --extern typed_builder_macro=/home/paul/Projects/Rust/leptos/target/debug/deps/libtyped_builder_macro-31161200d7aa688b.so --extern wasm_bindgen=/home/paul/Projects/Rust/leptos/target/debug/deps/libwasm_bindgen-8c9f20e7065ab9e4.rmeta --extern web_sys=/home/paul/Projects/Rust/leptos/target/debug/deps/libweb_sys-a9a3ab950e478b18.rmeta --crate-version 0.7.0-rc1` (signal: 6, SIGABRT: process abort signal)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x79c340a53f8a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8d76a2ebad741c31
   1:     0x79c3412043e6 - core::fmt::write::h7083017e822ed433
   2:     0x79c3425bf951 - std::io::Write::write_fmt::h46aae0d6ba1f44cd
   3:     0x79c340a53de2 - std::sys::backtrace::BacktraceLock::print::h868a0238128efcee
   4:     0x79c340a562e6 - std::panicking::default_hook::{{closure}}::h2066e468256aa3a1
   5:     0x79c340a56130 - std::panicking::default_hook::haec2bd80a2bacd69
   6:     0x79c33fad3659 - std[b0a00dbc0638d81d]::panicking::update_hook::<alloc[868bb6d6511729b6]::boxed::Box<rustc_driver_impl[f7b3d2aef74f50bd]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x79c340a569f8 - std::panicking::rust_panic_with_hook::hb61a22e0c1888abf
   8:     0x79c340a56796 - std::panicking::begin_panic_handler::{{closure}}::hdb44db17f4634f1a
   9:     0x79c340a54439 - std::sys::backtrace::__rust_end_short_backtrace::hec6e4cf6b39c69c1
  10:     0x79c340a5648c - rust_begin_unwind
  11:     0x79c33d4ca3b0 - core::panicking::panic_fmt::hd254657e38ffdc47
  12:     0x79c33d83768c - core::panicking::panic::hdcfc2c473348b4d9
  13:     0x79c33ebd4ca9 - core::option::unwrap_failed::hde07bbd2f122ffab
  14:     0x79c3419daed0 - <rustc_metadata[f4ff89d8dd20b927]::creader::CrateMetadataRef>::def_key
  15:     0x79c3419da80a - <rustc_metadata[f4ff89d8dd20b927]::creader::CStore as rustc_session[6e90dc4772e723fb]::cstore::CrateStore>::def_path
  16:     0x79c3419da6d6 - <rustc_middle[e19c0b1bdada1326]::ty::context::TyCtxt>::def_path
  17:     0x79c3401769ad - <rustc_middle[e19c0b1bdada1326]::ty::context::TyCtxt>::def_path_debug_str
  18:     0x79c33ffb5fad - rustc_interface[af777d83b93a0e77]::callbacks::def_id_debug
  19:     0x79c3412043e6 - core::fmt::write::h7083017e822ed433
  20:     0x79c3412043e6 - core::fmt::write::h7083017e822ed433
  21:     0x79c3412040e0 - alloc::fmt::format::format_inner::h23524232c1e8ef0d
  22:     0x79c34018f90b - rustc_middle[e19c0b1bdada1326]::util::bug::opt_span_bug_fmt::<rustc_span[db5cf53fd2dba3bf]::span_encoding::Span>::{closure#0}
  23:     0x79c340175f4a - rustc_middle[e19c0b1bdada1326]::ty::context::tls::with_opt::<rustc_middle[e19c0b1bdada1326]::util::bug::opt_span_bug_fmt<rustc_span[db5cf53fd2dba3bf]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  24:     0x79c340175ddb - rustc_middle[e19c0b1bdada1326]::ty::context::tls::with_context_opt::<rustc_middle[e19c0b1bdada1326]::ty::context::tls::with_opt<rustc_middle[e19c0b1bdada1326]::util::bug::opt_span_bug_fmt<rustc_span[db5cf53fd2dba3bf]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  25:     0x79c33e4abbf0 - rustc_middle[e19c0b1bdada1326]::util::bug::bug_fmt
  26:     0x79c3400e10ef - <rustc_metadata[f4ff89d8dd20b927]::creader::CrateMetadataRef>::missing
  27:     0x79c34135057b - rustc_query_impl[a7328f323106bed6]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a7328f323106bed6]::query_impl::def_kind::dynamic_query::{closure#2}::{closure#0}, rustc_middle[e19c0b1bdada1326]::query::erase::Erased<[u8; 3usize]>>
  28:     0x79c34134f5f6 - rustc_query_system[67d4df152bf9c514]::query::plumbing::try_execute_query::<rustc_query_impl[a7328f323106bed6]::DynamicConfig<rustc_query_system[67d4df152bf9c514]::query::caches::DefIdCache<rustc_middle[e19c0b1bdada1326]::query::erase::Erased<[u8; 3usize]>>, false, false, false>, rustc_query_impl[a7328f323106bed6]::plumbing::QueryCtxt, false>
  29:     0x79c34134f32d - rustc_query_impl[a7328f323106bed6]::query_impl::def_kind::get_query_non_incr::__rust_end_short_backtrace
  30:     0x5f79d94ce8a2 - rustc_middle[e19c0b1bdada1326]::query::plumbing::query_get_at::<rustc_query_system[67d4df152bf9c514]::query::caches::DefIdCache<rustc_middle[e19c0b1bdada1326]::query::erase::Erased<[u8; 3usize]>>>
  31:     0x5f79d9547992 - <alloc[868bb6d6511729b6]::vec::Vec<(rustdoc[7deb84addae318b4]::passes::collect_intra_doc_links::Res, core[15540c5044921d21]::option::Option<rustdoc[7deb84addae318b4]::passes::collect_intra_doc_links::UrlFragment>)>>::retain::<<rustdoc[7deb84addae318b4]::passes::collect_intra_doc_links::LinkCollector>::resolve_ambiguities::{closure#0}>::{closure#0}
  32:     0x5f79d96a8490 - rustdoc[7deb84addae318b4]::core::run_global_ctxt
  33:     0x5f79d97d4a2d - rustdoc[7deb84addae318b4]::main_args::{closure#2}::{closure#0}::{closure#0}
  34:     0x5f79d954e8c6 - rustc_interface[af777d83b93a0e77]::interface::run_compiler::<core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>, rustdoc[7deb84addae318b4]::main_args::{closure#2}>::{closure#1}
  35:     0x5f79d94cc0e5 - std[b0a00dbc0638d81d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[af777d83b93a0e77]::util::run_in_thread_with_globals<rustc_interface[af777d83b93a0e77]::util::run_in_thread_pool_with_globals<rustc_interface[af777d83b93a0e77]::interface::run_compiler<core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>, rustdoc[7deb84addae318b4]::main_args::{closure#2}>::{closure#1}, core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>>::{closure#0}, core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>>
  36:     0x5f79d955c858 - <<std[b0a00dbc0638d81d]::thread::Builder>::spawn_unchecked_<rustc_interface[af777d83b93a0e77]::util::run_in_thread_with_globals<rustc_interface[af777d83b93a0e77]::util::run_in_thread_pool_with_globals<rustc_interface[af777d83b93a0e77]::interface::run_compiler<core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>, rustdoc[7deb84addae318b4]::main_args::{closure#2}>::{closure#1}, core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>>::{closure#0}, core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[15540c5044921d21]::result::Result<(), rustc_span[db5cf53fd2dba3bf]::ErrorGuaranteed>>::{closure#1} as core[15540c5044921d21]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x79c34212ef39 - std::sys::pal::unix::thread::Thread::new::thread_start::h9245d1ee3a9d0779
  38:     0x79c33c2a339d - <unknown>
  39:     0x79c33c32849c - <unknown>
  40:                0x0 - <unknown>
```

</p>
</details>

[rustc-ice-2024-11-07T19_36_32-519661.txt](https://github.com/user-attachments/files/17668475/rustc-ice-2024-11-07T19_36_32-519661.txt)

**Comment by cyrgani** [comment]
Reduced version of the error: https://github.com/cyrgani/leptos_small

Run: 
```
cd leptos
cargo +nightly doc
```

**Comment by theemathas** [comment]
With cyrgani's reproducer, `cargo +1.68 doc` compiles fine with a correct warning. But `cargo +1.69 doc` produces an ICE.

@rustbot labels +regression-from-stable-to-stable

**Comment by apiraino** [comment]
Bisection is now harder because artifacts are gone, but if I am correct I get nightly nightly-2023-02-12 (2773383a314a4b8f481ce2bed12c32de794ffbe9) which leads to these PRs:
```
commit[0] 2023-02-10: Auto merge of #107886 - flip1995:clippyup, r=Manishearth
commit[1] 2023-02-10: Auto merge of #85158 - JulianKnodt:array_const_val, r=cjgillot
commit[2] 2023-02-11: Auto merge of #107507 - BoxyUwU:deferred_projection_equality, r=lcnr
commit[3] 2023-02-11: Auto merge of #107919 - Dylan-DPC:rollup-fkl9swa, r=Dylan-DPC
commit[4] 2023-02-11: Auto merge of #94857 - petrochenkov:doclink2, r=oli-obk
commit[5] 2023-02-11: Auto merge of #107167 - the8472:rawvec-simpler-layout, r=thomcc
commit[6] 2023-02-11: Auto merge of #107928 - matthiaskrgr:rollup-qnn380r, r=matthiaskrgr
commit[7] 2023-02-11: Auto merge of #107851 - cjgillot:sroa-const, r=oli-obk
```

The rustdoc changes I see in #107919 or #107928 are not ringing a bell

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23132743.20ICE.20building.20Leptos.200.2E7.2E0.20release.20candidate)).

@rustbot label -I-prioritize +P-medium

**Comment by lqd** [comment]
If there are links in doc comments in the repro, then https://github.com/rust-lang/rust/pull/94857 is likely involved.
