### ISSUE TITLE
[ICE]:

### ISSUE THREAD

**Issue by panjibae** [rust-lang/rust#133373]
### Code

```Rust
fn main() {
    let mut y = 10;
    let _x = &y; // Immutable borrow
    y = 20;       // Error: cannot assign to `y` because it's been borrowed
}
```

### Affected release channels

- [ ] Previous Stable
- [x] Current Stable
- [ ] Current Beta
- [ ] Current Nightly

### Rust Version

```Shell
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1
```

### Current error output

```Shell
20

the program can be executed and not cause error
```

### Backtrace

```Shell
RUST_BACKTRACE=full cargo run
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 10', src/main.rs:4:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/abcd1234/library/std/src/panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/abcd1234/library/core/src/panicking.rs:92
   2: core::panicking::panic_bounds_check
             at /rustc/abcd1234/library/core/src/panicking.rs:59
   3: <your_program_name>::main
             at src/main.rs:4
   4: std::rt::start::{{closure}}
             at /rustc/abcd1234/library/std/src/rt.rs:66
```

### Anything else?

This bug makes me a little ambiguous sir

**Comment by jieyouxu** [comment]
Your code snippet does not correspond to the panic (it's not an ICE either)?
