### ISSUE TITLE
Invalid instruction `trap invalid opcode ip`

### ISSUE THREAD

**Issue by nikita12100** [rust-lang/rust#133617]
hi everyone, I catch error when program try to execute code. `Cargo build`, `cargo run` works well, program starts and work, but when program try to excute [draw_pie](https://github.com/nikita12100/finHealth/blob/main/src/charts/pie_chart.rs) logic it fails with `Invalid instruction (memory image flushed to disk)`.

### Code

https://github.com/nikita12100/finHealth/blob/main/src/charts/pie_chart.rs

### Meta
`rustc --version --verbose`:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1
```

`cargo --version`
```
cargo 1.82.0 (8f40fc59f 2024-08-21)
```

### Error output of `sudo dmesg`

```
[    6.772223] systemd-journald[286]: Received client request to flush runtime journal.
[    6.820885] systemd-journald[286]: /var/log/journal/04a7948cba9b45e7a90ef36b47615a74/system.journal: Realtime clock jumped backwards relative to last journal entry, rotating.
[    6.820925] systemd-journald[286]: Rotating system journal.
[    7.250527] audit: type=1400 audit(1723128672.797:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name=4D6F6E676F444220436F6D70617373 pid=405 comm="apparmor_parser"
[    7.252255] audit: type=1400 audit(1723128672.798:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="1password" pid=403 comm="apparmor_parser"
[    7.252503] audit: type=1400 audit(1723128672.800:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="QtWebEngineProcess" pid=406 comm="apparmor_parser"
[    7.254387] audit: type=1400 audit(1723128672.802:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="Discord" pid=404 comm="apparmor_parser"
[    7.267510] audit: type=1400 audit(1723128672.815:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="brave" pid=412 comm="apparmor_parser"
[    7.267798] audit: type=1400 audit(1723128672.815:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="cam" pid=415 comm="apparmor_parser"
[    7.269296] audit: type=1400 audit(1723128672.816:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="buildah" pid=413 comm="apparmor_parser"
[    7.271345] audit: type=1400 audit(1723128672.819:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="busybox" pid=414 comm="apparmor_parser"
[    7.282426] audit: type=1400 audit(1723128672.830:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="vscode" pid=420 comm="apparmor_parser"
[    7.285902] audit: type=1400 audit(1723128672.833:11): apparmor="STATUS" operation="profile_load" profile="unconfined" name="ch-run" pid=418 comm="apparmor_parser"
[   11.269003] ACPI Warning: SystemIO range 0x0000000000000428-0x000000000000042F conflicts with OpRegion 0x0000000000000400-0x000000000000042F (\SWC1) (20230628/utaddress-204)
[   11.269047] ACPI Warning: SystemIO range 0x0000000000000428-0x000000000000042F conflicts with OpRegion 0x0000000000000400-0x000000000000047F (\PMIO) (20230628/utaddress-204)
[   11.269070] ACPI: OSL: Resource conflict; ACPI support missing from driver?
[   11.269081] ACPI Warning: SystemIO range 0x0000000000000530-0x000000000000053F conflicts with OpRegion 0x0000000000000500-0x000000000000053B (\GPIO) (20230628/utaddress-204)
[   11.269103] ACPI: OSL: Resource conflict; ACPI support missing from driver?
[   11.269111] ACPI Warning: SystemIO range 0x0000000000000500-0x000000000000052F conflicts with OpRegion 0x0000000000000500-0x000000000000053B (\GPIO) (20230628/utaddress-204)
[   11.269132] ACPI: OSL: Resource conflict; ACPI support missing from driver?
[   11.269138] lpc_ich: Resource conflict(s) found affecting gpio_ich
[   11.548670] gma500 0000:00:02.0: vgaarb: deactivate vga console
[   11.549311] gma500 0000:00:02.0: GPU: power management timed out.
[   11.560904] ACPI: video: Video Device [GFX0] (multi-head: yes  rom: no  post: no)
[   11.563461] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input6
[   11.568144] i801_smbus 0000:00:1f.3: SMBus using PCI interrupt
[   11.608944] i2c i2c-0: 1/2 memory slots populated (from DMI)
[   11.617918] i2c i2c-0: Successfully instantiated SPD at 0x51
[   11.860804] [drm] Initialized gma500 1.0.0 20140314 for 0000:00:02.0 on minor 0
[   12.122278] gma500 0000:00:02.0: [drm] Cannot find any crtc or sizes
[   12.240116] fbcon: Taking over console
[   12.246928] gma500 0000:00:02.0: [drm] Cannot find any crtc or sizes
[   12.287602] gma500 0000:00:02.0: [drm] Cannot find any crtc or sizes
[   12.447576] at24 0-0051: supply vcc not found, using dummy regulator
[   12.485568] at24 0-0051: 256 byte spd EEPROM, read-only
[   13.236296] snd_hda_codec_realtek hdaudioC0D2: autoconfig for ALC662 rev1: line_outs=1 (0x1b/0x0/0x0/0x0/0x0) type:hp
[   13.236330] snd_hda_codec_realtek hdaudioC0D2:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   13.236344] snd_hda_codec_realtek hdaudioC0D2:    hp_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   13.236356] snd_hda_codec_realtek hdaudioC0D2:    mono: mono_out=0x0
[   13.236364] snd_hda_codec_realtek hdaudioC0D2:    inputs:
[   13.236373] snd_hda_codec_realtek hdaudioC0D2:      Mic=0x18
[   13.264599] input: HDA Intel HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1b.0/sound/card0/input7
[   13.267576] input: HDA Intel Mic as /devices/pci0000:00/0000:00:1b.0/sound/card0/input8
[   13.270528] input: HDA Intel Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card0/input9
[   13.793346] kauditd_printk_skb: 144 callbacks suppressed
[   13.793360] audit: type=1400 audit(1732738203.415:156): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="rsyslogd" pid=770 comm="apparmor_parser"
[   14.951507] NET: Registered PF_QIPCRTR protocol family
[   18.333639] loop16: detected capacity change from 0 to 8
[   18.624601] RTL8211DN Gigabit Ethernet r8169-0-100:00: attached PHY driver (mii_bus:phy_addr=r8169-0-100:00, irq=MAC)
[   18.897010] r8169 0000:01:00.0 enp1s0: Link is Down
[   18.911335] RTL8211DN Gigabit Ethernet r8169-0-200:00: attached PHY driver (mii_bus:phy_addr=r8169-0-200:00, irq=MAC)
[   19.199336] r8169 0000:02:00.0 enp2s0: Link is Down
[   19.506563] audit: type=1400 audit(1732738209.128:157): apparmor="DENIED" operation="capable" class="cap" profile="/usr/sbin/cupsd" pid=1120 comm="cupsd" capability=12  capname="net_admin"
[   20.786832] r8169 0000:01:00.0 enp1s0: Link is Up - 1Gbps/Full - flow control off
[   39.590275] audit: type=1400 audit(1732866988.413:158): apparmor="DENIED" operation="capable" class="cap" profile="/usr/sbin/cupsd" pid=1226 comm="cupsd" capability=12  capname="net_admin"
[  112.186971] audit: type=1400 audit(1732867061.010:159): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/23258/usr/lib/snapd/snap-confine" pid=1284 comm="snap-confine" capability=12  capname="net_admin"
[  112.187164] audit: type=1400 audit(1732867061.010:160): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/23258/usr/lib/snapd/snap-confine" pid=1284 comm="snap-confine" capability=38  capname="perfmon"
[  280.189163] traps: tokio-runtime-w[1850] trap invalid opcode ip:560c8e046c39 sp:7a2cc6199080 error:0 in fin_health[560c8d1d7000+1ca8000]
[  493.890680] perf: interrupt took too long (2524 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
[  519.673500] perf: interrupt took too long (3164 > 3155), lowering kernel.perf_event_max_sample_rate to 63000
[  528.556262] traps: tokio-runtime-w[2168] trap invalid opcode ip:623e0faa6c39 sp:74f11b999080 error:0 in fin_health[623e0ec37000+1ca8000]
```

`cat /proc/cpuinfo`
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 54
model name	: Intel(R) Atom(TM) CPU D2550   @ 1.86GHz
stepping	: 1
microcode	: 0x10d
cpu MHz		: 1866.810
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm arat
bugs		:
bogomips	: 3733.62
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
...

</p>
</details>

**Comment by ds84182** [comment]
Your CPU is missing SSE4 instructions. It does not meet the requirements for `x86-64-v2`

**Comment by alexstanovoy** [comment]
> Your CPU is missing SSE4 instructions. It does not meet the requirements for `x86-64-v2`

But `rustc` should understand that this Atom CPU does not support these instructions and generate code without them. It should either be a problem in how `rustc` passes flags to LLVM or in LLVM itself.

**Comment by saethlin** [comment]
The `x86_64-unknown-linux-gnu` target's baseline is `x86-64`, not `x86-64-v2`.

If you are trying to compile for `-Ctarget-cpu=x86-64-v2`, `cargo run` will not do anything to prevent you from compiling and then trying to execute code that he host CPU does not support. But I don't see any evidence that you've changed the target-cpu? Have you set a target-cpu somehow? `cargo build --verbose` will print all the flags you've set.

**Comment by nikita12100** [comment]
No I didn't set any flags on `build` or `run`. `cargo build` and `cargo run` were executed on the same computer.

**Comment by lqd** [comment]
Do you have a `~/.cargo/config.toml` or similar?

**Comment by nikita12100** [comment]
```
ls -a ~/.cargo/
.  ..  bin  env  .global-cache  .package-cache  .package-cache-mutate  registry
```
```
cargo build --verbose
       Fresh unicode-ident v1.0.13
       Fresh cfg-if v1.0.0
       Fresh proc-macro2 v1.0.89
       Fresh autocfg v1.4.0
       Fresh shlex v1.3.0
       Fresh quote v1.0.37
       Fresh libc v0.2.161
       Fresh cc v1.1.36
       Fresh version_check v0.9.5
       Fresh syn v2.0.87
       Fresh once_cell v1.20.2
       Fresh memchr v2.7.4
       Fresh pkg-config v0.3.31
       Fresh getrandom v0.2.15
       Fresh pin-project-lite v0.2.15
       Fresh futures-core v0.3.31
       Fresh synstructure v0.13.1
       Fresh serde_derive v1.0.214
       Fresh scopeguard v1.2.0
       Fresh serde v1.0.214
       Fresh zerofrom-derive v0.1.4
       Fresh yoke-derive v0.7.4
       Fresh zerofrom v0.1.4
       Fresh stable_deref_trait v1.2.0
       Fresh yoke v0.7.4
       Fresh zerocopy-derive v0.7.35
       Fresh zerovec-derive v0.10.3
       Fresh bytes v1.8.0
       Fresh typenum v1.17.0
       Fresh zerovec v0.10.4
       Fresh lock_api v0.4.12
       Fresh displaydoc v0.2.5
       Fresh vcpkg v0.2.15
       Fresh smallvec v1.13.2
       Fresh generic-array v0.14.7
       Fresh mio v1.0.2
       Fresh socket2 v0.5.7
       Fresh tinystr v0.7.6
       Fresh slab v0.4.9
       Fresh pin-utils v0.1.0
       Fresh futures-io v0.3.31
       Fresh litemap v0.7.3
       Fresh writeable v0.5.5
       Fresh futures-task v0.3.31
       Fresh icu_locid v1.5.0
       Fresh spin v0.9.8
       Fresh icu_provider_macros v1.5.0
       Fresh icu_provider v1.5.0
       Fresh block-buffer v0.10.4
       Fresh either v1.13.0
       Fresh subtle v2.6.1
       Fresh itoa v1.0.11
       Fresh icu_locid_transform_data v1.5.0
       Fresh icu_locid_transform v1.5.0
       Fresh icu_collections v1.5.0
       Fresh untrusted v0.9.0
       Fresh icu_properties_data v1.5.0
       Fresh ring v0.17.8
       Fresh icu_properties v1.5.1
       Fresh tracing-core v0.1.32
       Fresh tracing-attributes v0.1.27
       Fresh write16 v1.0.0
       Fresh icu_normalizer_data v1.5.0
       Fresh utf16_iter v1.0.5
       Fresh utf8_iter v1.0.4
       Fresh icu_normalizer v1.5.0
       Fresh hashbrown v0.15.1
       Fresh percent-encoding v2.3.1
       Fresh equivalent v1.0.1
       Fresh idna_adapter v1.2.0
       Fresh rustls-webpki v0.101.7
       Fresh indexmap v2.6.0
       Fresh sct v0.7.1
       Fresh tokio-macros v2.4.0
       Fresh signal-hook-registry v1.4.2
       Fresh minimal-lexical v0.2.1
       Fresh nom v7.1.3
       Fresh thiserror-impl v1.0.68
       Fresh futures-macro v0.3.31
       Fresh allocator-api2 v0.2.18
       Fresh thiserror v1.0.68
       Fresh fnv v1.0.7
       Fresh byteorder v1.5.0
       Fresh ryu v1.0.18
       Fresh syn v1.0.109
       Fresh paste v1.0.15
       Fresh base64 v0.21.7
       Fresh parking_lot_core v0.9.10
       Fresh rustls-pemfile v1.0.4
       Fresh serde_json v1.0.132
       Fresh zerocopy v0.7.35
       Fresh openssl-src v300.4.1+3.4.0
       Fresh webpki-roots v0.25.4
       Fresh cpufeatures v0.2.14
       Fresh parking_lot v0.12.3
       Fresh crc-catalog v2.4.0
       Fresh simd-adler32 v0.3.7
       Fresh futures-sink v0.3.31
       Fresh unicode_categories v0.1.1
       Fresh crc v3.2.1
       Fresh sqlformat v0.2.6
       Fresh futures-intrusive v0.5.0
       Fresh crypto-common v0.1.6
       Fresh rand_core v0.6.4
       Fresh event-listener v2.5.3
       Fresh hex v0.4.3
       Fresh digest v0.10.7
       Fresh tinyvec_macros v0.1.1
       Fresh adler2 v2.0.0
       Fresh tinyvec v1.8.0
       Fresh miniz_oxide v0.8.0
       Fresh num-traits v0.2.19
       Fresh crossbeam-utils v0.8.20
       Fresh futures-util v0.3.31
       Fresh ahash v0.8.11
       Fresh http v0.2.12
       Fresh crossbeam-epoch v0.9.18
       Fresh idna v1.0.3
       Fresh form_urlencoded v1.2.1
       Fresh tokio v1.41.0
       Fresh log v0.4.22
       Fresh foreign-types-shared v0.1.1
       Fresh tracing v0.1.40
       Fresh foreign-types v0.3.2
       Fresh crossbeam-deque v0.8.5
       Fresh url v2.5.3
       Fresh hashbrown v0.14.5
       Fresh rustls v0.21.12
       Fresh semver v1.0.23
       Fresh unicode-normalization v0.1.24
       Fresh openssl-sys v0.9.104
       Fresh futures-channel v0.3.31
       Fresh tokio-util v0.7.12
       Fresh openssl-macros v0.1.1
       Fresh crc32fast v1.4.2
       Fresh bitflags v2.6.0
       Fresh bitflags v1.3.2
       Fresh ident_case v1.0.1
       Fresh unicode-properties v0.1.3
       Fresh strsim v0.10.0
       Fresh try-lock v0.2.5
       Fresh unicode-bidi v0.3.17
       Fresh want v0.3.1
       Fresh stringprep v0.1.5
       Fresh darling_core v0.13.4
       Fresh flate2 v1.0.34
       Fresh openssl v0.10.68
       Fresh h2 v0.3.26
       Fresh hashlink v0.8.4
       Fresh rustc_version v0.4.1
       Fresh rayon-core v1.12.1
       Fresh httparse v1.9.5
       Fresh http-body v0.4.6
       Fresh num-integer v0.1.46
       Fresh weezl v0.1.8
       Fresh unicode-segmentation v1.12.0
       Fresh urlencoding v2.1.3
       Fresh unicase v2.8.0
       Fresh color_quant v1.1.0
       Fresh whoami v1.5.2
       Fresh dotenvy v0.15.7
       Fresh home v0.5.9
       Fresh tower-service v0.3.3
       Fresh openssl-probe v0.1.5
       Fresh linux-raw-sys v0.4.14
       Fresh httpdate v1.0.3
       Fresh native-tls v0.2.12
       Fresh rustix v0.38.39
       Fresh hyper v0.14.31
       Fresh heck v0.4.1
       Fresh num-bigint v0.4.6
       Fresh darling_macro v0.13.4
       Fresh futures-executor v0.3.31
       Fresh sha2 v0.10.8
       Fresh fdeflate v0.3.6
       Fresh ppv-lite86 v0.2.20
       Fresh tokio-stream v0.1.16
       Fresh crossbeam-queue v0.3.11
       Fresh atoi v2.0.0
       Fresh fastrand v2.1.1
       Fresh jpeg-decoder v0.3.1
       Fresh bytemuck v1.19.0
       Fresh aligned-vec v0.5.0
       Fresh arrayvec v0.7.6
       Fresh built v0.7.5
       Fresh v_frame v0.3.8
       Fresh tempfile v3.13.0
       Fresh sqlx-core v0.7.4
       Fresh rand_chacha v0.3.1
       Fresh darling v0.13.4
       Fresh png v0.17.14
       Fresh libsqlite3-sys v0.27.0
       Fresh num-rational v0.4.2
       Fresh anyhow v1.0.93
       Fresh tokio-native-tls v0.3.1
       Fresh rayon v1.10.0
       Fresh tokio-rustls v0.24.1
       Fresh hmac v0.12.1
       Fresh aho-corasick v1.1.3
       Fresh profiling-procmacros v1.0.16
       Fresh libloading v0.8.5
       Fresh iana-time-zone v0.1.61
       Fresh regex-syntax v0.8.5
       Fresh mime v0.3.17
       Fresh option-ext v0.2.0
       Fresh regex-automata v0.4.8
       Fresh chrono v0.4.38
       Fresh dirs-sys v0.4.1
       Fresh mime_guess v2.0.5
       Fresh dlib v0.5.2
       Fresh profiling v1.0.16
       Fresh hyper-rustls v0.24.2
       Fresh hkdf v0.12.4
       Fresh maybe-rayon v0.1.1
       Fresh av1-grain v0.2.3
       Fresh hyper-tls v0.5.0
       Fresh pathfinder_simd v0.5.4
       Fresh rand v0.8.5
       Fresh serde_with_macros v1.5.2
       Fresh sqlx-macros-core v0.7.4
       Fresh proc-macro-error-attr v1.0.4
       Fresh erasable v1.2.1
       Fresh futures v0.3.31
       Fresh serde_urlencoded v0.7.1
       Fresh md-5 v0.10.6
       Fresh flume v0.11.1
       Fresh itertools v0.12.1
       Fresh pin-project-internal v1.1.7
       Fresh num-derive v0.4.2
       Fresh arg_enum_proc_macro v0.3.4
       Fresh simd_helpers v0.1.0
       Fresh include_dir_macros v0.7.4
       Fresh encoding_rs v0.8.35
       Fresh noop_proc_macro v0.3.0
       Fresh ipnet v2.10.1
       Fresh plotters-backend v0.3.7
       Fresh new_debug_unreachable v1.0.6
       Fresh quick-error v2.0.1
       Fresh same-file v1.0.6
       Fresh imgref v1.11.0
       Fresh sync_wrapper v0.1.2
       Fresh bitstream-io v2.6.0
       Fresh convert_case v0.4.0
       Fresh reqwest v0.11.27
       Fresh derive_more v0.99.18
       Fresh loop9 v0.1.5
       Fresh rav1e v0.7.1
       Fresh walkdir v2.5.0
       Fresh include_dir v0.7.4
       Fresh sqlx-sqlite v0.7.4
       Fresh pin-project v1.1.7
       Fresh sqlx-postgres v0.7.4
       Fresh rc-box v1.2.0
       Fresh sqlx-macros v0.7.4
       Fresh proc-macro-error v1.0.4
       Fresh serde_with v1.14.0
       Fresh pathfinder_geometry v0.5.1
       Fresh dirs v5.0.1
       Fresh yeslogic-fontconfig-sys v6.0.0
       Fresh regex v1.11.1
       Fresh image v0.24.9
       Fresh freetype-sys v0.20.1
       Fresh avif-serialize v0.8.2
       Fresh gif v0.12.0
       Fresh zune-inflate v0.2.54
       Fresh itertools v0.10.5
       Fresh uuid v1.11.0
       Fresh is-terminal v0.4.13
       Fresh half v2.4.1
       Fresh rgb v0.8.50
       Fresh lazy_static v1.5.0
       Fresh zune-core v0.4.12
       Fresh humantime v2.1.0
       Fresh float-ord v0.3.2
       Fresh takecell v0.1.1
       Fresh lebe v0.5.2
       Fresh bit_field v0.10.2
       Fresh termcolor v1.4.1
       Fresh byteorder-lite v0.1.0
       Fresh take_mut v0.2.2
       Fresh font-kit v0.14.2
       Fresh image-webp v0.2.0
       Fresh teloxide-core v0.10.1
       Fresh env_logger v0.10.2
       Fresh exr v1.73.0
       Fresh ravif v0.11.11
       Fresh zune-jpeg v0.4.13
       Fresh aquamarine v0.5.0
       Fresh plotters-bitmap v0.3.7
       Fresh sqlx v0.7.4
       Fresh rustversion v1.0.18
       Fresh plotters-svg v0.3.7
       Fresh dptree v0.3.0
       Fresh qoi v0.4.1
       Fresh tiff v0.9.1
       Fresh teloxide-macros v0.8.0
       Fresh gif v0.13.1
       Fresh fallible-iterator v0.3.0
       Fresh ttf-parser v0.20.0
       Fresh heck v0.5.0
       Fresh fallible-streaming-iterator v0.1.9
       Fresh rusqlite v0.30.0
       Fresh strum_macros v0.26.4
       Fresh plotters v0.3.7
       Fresh image v0.25.5
       Fresh teloxide v0.13.0
       Fresh pretty_env_logger v0.5.0
       Fresh itertools v0.13.0
       Fresh strum v0.26.3
       Fresh fin_health v0.1.0 (/usr/tg_bot/test_build/finHealth)
warning: associated items `new_date`, `set_balance_amount_date`, `add_balance_income_date`, and `add_balance_outcome_date` are never used
  --> src/db/account.rs:24:12
   |
23 | impl Account {
   | ------------ associated items in this implementation
24 |     pub fn new_date(name: String, start_balance: u32, currency: Currency, asset_location: A...
   |            ^^^^^^^^
...
62 |     fn set_balance_amount_date(&mut self, new_amount: u32, category: Option<Category>, date...
   |        ^^^^^^^^^^^^^^^^^^^^^^^
...
69 |     pub fn add_balance_income_date(&mut self, income: u32, date: DateTime<Utc>) {
   |            ^^^^^^^^^^^^^^^^^^^^^^^
...
77 |     pub fn add_balance_outcome_date(&mut self, outcome: u32, category: Category, date: Date...
   |            ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated functions `new_date` and `new_date_category` are never used
  --> src/db/balance_timed.rs:35:12
   |
17 | impl BalanceTimed {
   | ----------------- associated functions in this implementation
...
35 |     pub fn new_date(start_balance: u32, date: DateTime<Utc>) -> Self { BalanceTimed { id: U...
   |            ^^^^^^^^
36 |     pub fn new_category(start_balance: u32, category: Option<Category>) -> Self { BalanceTi...
37 |     pub fn new_date_category(start_balance: u32, date: DateTime<Utc>, category: Option<Cate...
   |            ^^^^^^^^^^^^^^^^^

warning: struct `MockData` is never constructed
 --> src/utils/mock_data.rs:9:12
  |
9 | pub struct MockData {}
  |            ^^^^^^^^

warning: associated function `create` is never used
  --> src/utils/mock_data.rs:12:12
   |
11 | impl MockData {
   | ------------- associated function in this implementation
12 |     pub fn create() -> Portfolio {
   |            ^^^^^^

warning: `fin_health` (bin "fin_health") generated 4 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.46s


```

**Comment by saethlin** [comment]
This project contains at least 2 dependencies that rely on runtime CPU feature detection. I learned this by skimming the disassembly.

So I think the next thing to do here is to come up with a portable way to reproduce this problem. I'll try poking at this in qemu later. Their docs suggest that they have CPU options for CPUs that only support x86-64 baseline: https://qemu-project.gitlab.io/qemu/system/qemu-cpu-models.html#id1

**Comment by saethlin** [comment]
Progress!

I can get this backtrace now to the sse4.1 instruction:
```
#0  0x00005555559f2839 in core::core_arch::x86::sse41::_mm_max_epi32 (a=..., b=...)
    at /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/../../stdarch/crates/core_arch/src/x86/sse41.rs:332
#1  0x00005555559eaf95 in pathfinder_simd::x86::I32x4::max (self=..., other=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.4/src/x86/mod.rs:705
#2  0x00005555559eab0b in pathfinder_simd::x86::I32x2::max (self=..., other=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.4/src/x86/mod.rs:525
#3  0x00005555559f0133 in pathfinder_geometry::vector::Vector2I::max (self=..., other=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_geometry-0.5.1/src/vector.rs:343
#4  0x00005555559f4ffe in pathfinder_geometry::rect::RectI::intersection (self=..., other=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_geometry-0.5.1/src/rect.rs:345
#5  0x00005555559ec82f in font_kit::canvas::Canvas::blit_from (self=0x7c93a9fb6278, dst_point=..., src_bytes=..., 
    src_size=..., src_stride=21, src_format=font_kit::canvas::Format::A8) at src/canvas.rs:98
#6  0x00005555559f3eb6 in font_kit::loaders::freetype::Font::rasterize_glyph (self=0x7c93a9fb8318, canvas=0x7c93a9fb6278, 
    glyph_id=441, point_size=40.3225822, transform=..., hinting_options=..., 
    rasterization_options=font_kit::canvas::RasterizationOptions::GrayscaleAa) at src/loaders/freetype.rs:861
#7  0x000055555594c956 in plotters::style::font::ttf::{impl#5}::draw<plotters_backend::DrawingErrorKind<plotters_bitmap::error::BitMapBackendError>, plotters::style::text::{impl#15}::draw::{closure_env#0}<plotters_backend::DrawingErrorKind<plotters_bitmap::error::BitMapBackendError>, plotters_backend::DrawingBackend::draw_text::{closure_env#1}<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle>>> (self=0x7c93a9fb7980, size=50, text=..., 
    draw=...) at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.7/src/style/font/ttf.rs:266
#8  0x0000555555954272 in plotters::style::font::font_desc::FontDesc::draw<plotters_backend::DrawingErrorKind<plotters_bitmap::error::BitMapBackendError>, plotters::style::text::{impl#15}::draw::{closure_env#0}<plotters_backend::DrawingErrorKind<plotters_bitmap::error::BitMapBackendError>, plotters_backend::DrawingBackend::draw_text::{closure_env#1}<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle>>> (self=0x7c93a9fb7968, text=..., 
    draw=...) at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.7/src/style/font/font_desc.rs:168
#9  0x00005555558ce739 in plotters::style::text::{impl#15}::draw<plotters_backend::DrawingErrorKind<plotters_bitmap::error::BitMapBackendError>, plotters_backend::DrawingBackend::draw_text::{closure_env#1}<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle>> (self=0x7c93a9fb7968, text=..., pos=..., draw=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.7/src/style/text.rs:322
#10 0x00005555558e7738 in plotters_backend::DrawingBackend::draw_text<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle> (self=0x7c9384002378, text=..., style=0x7c93a9fb7968, pos=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-backend-0.3.7/src/lib.rs:250
#11 0x000055555590d290 in plotters::drawing::area::{impl#9}::titled::{closure#0}<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle> (b=0x7c9384002378)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.7/src/drawing/area.rs:496
#12 0x000055555590b9a9 in plotters::drawing::area::DrawingArea<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::coord::Shift>::backend_ops<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::coord::Shift, (), plotters::drawing::area::{impl#9}::titled::{closure_env#0}<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle>> (self=0x7c93a9fb8658, ops=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.7/src/drawing/area.rs:282
#13 0x000055555590cec1 in plotters::drawing::area::DrawingArea<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::coord::Shift>::titled<plotters_bitmap::bitmap::BitMapBackend<plotters_bitmap::bitmap_pixel::rgb::RGBPixel>, plotters::style::text::TextStyle> (self=0x7c93a9fb8658, text=..., style=...)
    at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/plotters-0.3.7/src/drawing/area.rs:495
#14 0x000055555590a6c1 in fin_health_2024_11_30::charts::pie_chart::PieChart::create_bytes (sizes=..., labels=..., 
```

**Comment by Noratrieb** [comment]
I think you have hit https://github.com/servo/pathfinder/issues/502, a library bug. it does not look like the library supports your CPU today

**Comment by saethlin** [comment]
Given that we've root-caused this to a defect in a third-party crate, I'm closing this. There's nothing for us to do here. Is
