### ISSUE TITLE
ICE file dumps could be richer

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#133869]
I have seen it a couple of times already that people attach ICE files but these backtrace or files look like they are missing the actual ICE message from the report.

for example, my ICE may look like this (or, this is what I would consider part of it)

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_trait_selection/src/traits/normalize.rs:69:17: deeply_normalize should not be called with pending obligations: [
                                    Obligation(predicate=Binder { value: TraitPredicate(<_ as TraitA>, polarity:Positive), bound_vars: [] }, depth=1),
                                ]
  --> a.rs:52:24
   |
52 |     fn method(self) -> impl for<'a> FnMut(&'a ()) -> Self::Assoc<'a>;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:69:17:
Box<dyn Any>
stack backtrace:
   0:     0x75750014124a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hbaae7ee6452314ac
   1:     0x757500813c26 - core::fmt::write::h2f9a8d2f2637a85f
   2:     0x757501be0551 - std::io::Write::write_fmt::he34daf083f9a3021
   3:     0x7575001410a2 - std::sys::backtrace::BacktraceLock::print::h0058685886628669
   4:     0x7575001435aa - std::panicking::default_hook::{{closure}}::h57409c565dc0e9b1
   5:     0x7575001433f3 - std::panicking::default_hook::ha667d029378d179a
   6:     0x7574ff2bfa48 - std[c2c54d6827da810b]::panicking::update_hook::<alloc[34a40601127b84fc]::boxed::Box<rustc_driver_impl[c0d80c2a9490dd80]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x757500143d68 - std::panicking::rust_panic_with_hook::h12054419da422896
   8:     0x7574ff2f5271 - std[c2c54d6827da810b]::panicking::begin_panic::<rustc_errors[2e40efcb590bb17b]::ExplicitBug>::{closure#0}
   9:     0x7574ff2ea136 - std[c2c54d6827da810b]::sys::backtrace::__rust_end_short_backtrace::<std[c2c54d6827da810b]::panicking::begin_panic<rustc_errors[2e40efcb590bb17b]::ExplicitBug>::{closure#0}, !>
  10:     0x7574ff2ea123 - std[c2c54d6827da810b]::panicking::begin_panic::<rustc_errors[2e40efcb590bb17b]::ExplicitBug>
  11:     0x7574ff2ff2b1 - <rustc_errors[2e40efcb590bb17b]::diagnostic::BugAbort as rustc_errors[2e40efcb590bb17b]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7574ff854a9c - <rustc_errors[2e40efcb590bb17b]::DiagCtxtHandle>::span_bug::<rustc_span[2659c11acd16cd7]::span_encoding::Span, alloc[34a40601127b84fc]::string::String>
  13:     0x7574ff8e75d7 - rustc_middle[27a877ea52447dab]::util::bug::opt_span_bug_fmt::<rustc_span[2659c11acd16cd7]::span_encoding::Span>::{closure#0}
  14:     0x7574ff8cfa6a - rustc_middle[27a877ea52447dab]::ty::context::tls::with_opt::<rustc_middle[27a877ea52447dab]::util::bug::opt_span_bug_fmt<rustc_span[2659c11acd16cd7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7574ff8cf8fb - rustc_middle[27a877ea52447dab]::ty::context::tls::with_context_opt::<rustc_middle[27a877ea52447dab]::ty::context::tls::with_opt<rustc_middle[27a877ea52447dab]::util::bug::opt_span_bug_fmt<rustc_span[2659c11acd16cd7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7574fe3d2d77 - rustc_middle[27a877ea52447dab]::util::bug::span_bug_fmt::<rustc_span[2659c11acd16cd7]::span_encoding::Span>
  17:     0x757500bc00d4 - <rustc_trait_selection[bf65a12e96ea037e]::traits::engine::ObligationCtxt<rustc_trait_selection[bf65a12e96ea037e]::traits::FulfillmentError>>::assumed_wf_types_and_report_errors
  18:     0x75750105c126 - rustc_hir_analysis[6d68d5be0ecf7979]::check::compare_impl_item::check_type_bounds
  19:     0x757500e5921d - rustc_hir_analysis[6d68d5be0ecf7979]::check::compare_impl_item::compare_impl_item
  20:     0x757500e56b51 - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::compare_impl_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  21:     0x75750121e930 - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_data_structures[848008ad1566c8b0]::vec_cache::VecCache<rustc_span[2659c11acd16cd7]::def_id::LocalDefId, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[9a3c01f0ed066ff8]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  22:     0x75750121e401 - rustc_query_impl[a2008a1cc616166f]::query_impl::compare_impl_item::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7574fcdb057d - rustc_hir_analysis[6d68d5be0ecf7979]::check::check::check_item_type
  24:     0x7574fe4419e5 - rustc_hir_analysis[6d68d5be0ecf7979]::check::wfcheck::check_well_formed
  25:     0x75750121e687 - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  26:     0x75750121e948 - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_data_structures[848008ad1566c8b0]::vec_cache::VecCache<rustc_span[2659c11acd16cd7]::def_id::LocalDefId, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[9a3c01f0ed066ff8]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  27:     0x75750121e662 - rustc_query_impl[a2008a1cc616166f]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  28:     0x75750121f3ec - rustc_hir_analysis[6d68d5be0ecf7979]::check::wfcheck::check_mod_type_wf
  29:     0x75750121f20b - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  30:     0x75750181a208 - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_query_system[9a3c01f0ed066ff8]::query::caches::DefaultCache<rustc_span[2659c11acd16cd7]::def_id::LocalModDefId, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  31:     0x757501819fb0 - rustc_query_impl[a2008a1cc616166f]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  32:     0x757500a9eb9c - rustc_hir_analysis[6d68d5be0ecf7979]::check_crate
  33:     0x757501128cbc - rustc_interface[4b3ef207fa86e12e]::passes::run_required_analyses
  34:     0x757501123d1e - rustc_interface[4b3ef207fa86e12e]::passes::analysis
  35:     0x757501123cef - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  36:     0x7575017d5dba - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_query_system[9a3c01f0ed066ff8]::query::caches::SingleCache<rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  37:     0x7575017d5a8e - rustc_query_impl[a2008a1cc616166f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  38:     0x757501864e39 - rustc_interface[4b3ef207fa86e12e]::interface::run_compiler::<core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>, rustc_driver_impl[c0d80c2a9490dd80]::run_compiler::{closure#0}>::{closure#1}
  39:     0x7575017c08a1 - std[c2c54d6827da810b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_with_globals<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_pool_with_globals<rustc_interface[4b3ef207fa86e12e]::interface::run_compiler<core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>, rustc_driver_impl[c0d80c2a9490dd80]::run_compiler::{closure#0}>::{closure#1}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>
  40:     0x7575017c0548 - <<std[c2c54d6827da810b]::thread::Builder>::spawn_unchecked_<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_with_globals<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_pool_with_globals<rustc_interface[4b3ef207fa86e12e]::interface::run_compiler<core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>, rustc_driver_impl[c0d80c2a9490dd80]::run_compiler::{closure#0}>::{closure#1}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#1} as core[437bb64b3ca51b65]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7575017bfc7b - std::sys::pal::unix::thread::Thread::new::thread_start::h2b35487752b07311
  42:     0x7574fbaa339d - <unknown>
  43:     0x7574fbb2849c - <unknown>
  44:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/tmp/im/1/rustc-ice-2024-12-04T19_53_55-344983.txt` to your bug report

query stack during panic:
#0 [compare_impl_item] checking assoc item `<impl at a.rs:55:1: 57:43>::{synthetic#0}` is compatible with trait definition
#1 [check_well_formed] checking that `<impl at a.rs:55:1: 57:43>` is well-formed
end of query stack
error[E0433]: failed to resolve: use of undeclared type `WrapperT`
  --> a.rs:46:12
   |
46 |     helper(WrapperT::AssocB as TraitA);
   |            ^^^^^^^^
   |            |
   |            use of undeclared type `WrapperT`
   |            help: a struct with a similar name exists: `Wrapper`

error: aborting due to 13 previous errors

Some errors have detailed explanations: E0261, E0277, E0412, E0433, E0437, E0576, E0658.
For more information about an error, try `rustc --explain E0261`.
```

</p>
</details>

however, the ice-dump file does not contain the actual ICE message
```
error: internal compiler error: compiler/rustc_trait_selection/src/traits/normalize.rs:69:17: deeply_normalize should not be called with pending obligations: [
                                    Obligation(predicate=Binder { value: TraitPredicate(<_ as TraitA>, polarity:Positive), bound_vars: [] }, depth=1),
                                ]
```
 which makes it harder to compare it to other ICEs, check if it has been reported already or search for in the tracker...

what ends up in the file is only this:

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:69:17:
Box<dyn Any>
stack backtrace:
   0:     0x757501be59a5 - std::backtrace::Backtrace::create::h78d0e7511919e78f
   1:     0x75750012c445 - std::backtrace::Backtrace::force_capture::h954b965bf7c9452b
   2:     0x7574ff2c0046 - std[c2c54d6827da810b]::panicking::update_hook::<alloc[34a40601127b84fc]::boxed::Box<rustc_driver_impl[c0d80c2a9490dd80]::install_ice_hook::{closure#0}>>::{closure#0}
   3:     0x757500143d68 - std::panicking::rust_panic_with_hook::h12054419da422896
   4:     0x7574ff2f5271 - std[c2c54d6827da810b]::panicking::begin_panic::<rustc_errors[2e40efcb590bb17b]::ExplicitBug>::{closure#0}
   5:     0x7574ff2ea136 - std[c2c54d6827da810b]::sys::backtrace::__rust_end_short_backtrace::<std[c2c54d6827da810b]::panicking::begin_panic<rustc_errors[2e40efcb590bb17b]::ExplicitBug>::{closure#0}, !>
   6:     0x7574ff2ea123 - std[c2c54d6827da810b]::panicking::begin_panic::<rustc_errors[2e40efcb590bb17b]::ExplicitBug>
   7:     0x7574ff2ff2b1 - <rustc_errors[2e40efcb590bb17b]::diagnostic::BugAbort as rustc_errors[2e40efcb590bb17b]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   8:     0x7574ff854a9c - <rustc_errors[2e40efcb590bb17b]::DiagCtxtHandle>::span_bug::<rustc_span[2659c11acd16cd7]::span_encoding::Span, alloc[34a40601127b84fc]::string::String>
   9:     0x7574ff8e75d7 - rustc_middle[27a877ea52447dab]::util::bug::opt_span_bug_fmt::<rustc_span[2659c11acd16cd7]::span_encoding::Span>::{closure#0}
  10:     0x7574ff8cfa6a - rustc_middle[27a877ea52447dab]::ty::context::tls::with_opt::<rustc_middle[27a877ea52447dab]::util::bug::opt_span_bug_fmt<rustc_span[2659c11acd16cd7]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  11:     0x7574ff8cf8fb - rustc_middle[27a877ea52447dab]::ty::context::tls::with_context_opt::<rustc_middle[27a877ea52447dab]::ty::context::tls::with_opt<rustc_middle[27a877ea52447dab]::util::bug::opt_span_bug_fmt<rustc_span[2659c11acd16cd7]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  12:     0x7574fe3d2d77 - rustc_middle[27a877ea52447dab]::util::bug::span_bug_fmt::<rustc_span[2659c11acd16cd7]::span_encoding::Span>
  13:     0x757500bc00d4 - <rustc_trait_selection[bf65a12e96ea037e]::traits::engine::ObligationCtxt<rustc_trait_selection[bf65a12e96ea037e]::traits::FulfillmentError>>::assumed_wf_types_and_report_errors
  14:     0x75750105c126 - rustc_hir_analysis[6d68d5be0ecf7979]::check::compare_impl_item::check_type_bounds
  15:     0x757500e5921d - rustc_hir_analysis[6d68d5be0ecf7979]::check::compare_impl_item::compare_impl_item
  16:     0x757500e56b51 - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::compare_impl_item::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  17:     0x75750121e930 - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_data_structures[848008ad1566c8b0]::vec_cache::VecCache<rustc_span[2659c11acd16cd7]::def_id::LocalDefId, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[9a3c01f0ed066ff8]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  18:     0x75750121e401 - rustc_query_impl[a2008a1cc616166f]::query_impl::compare_impl_item::get_query_non_incr::__rust_end_short_backtrace
  19:     0x7574fcdb057d - rustc_hir_analysis[6d68d5be0ecf7979]::check::check::check_item_type
  20:     0x7574fe4419e5 - rustc_hir_analysis[6d68d5be0ecf7979]::check::wfcheck::check_well_formed
  21:     0x75750121e687 - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  22:     0x75750121e948 - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_data_structures[848008ad1566c8b0]::vec_cache::VecCache<rustc_span[2659c11acd16cd7]::def_id::LocalDefId, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>, rustc_query_system[9a3c01f0ed066ff8]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  23:     0x75750121e662 - rustc_query_impl[a2008a1cc616166f]::query_impl::check_well_formed::get_query_non_incr::__rust_end_short_backtrace
  24:     0x75750121f3ec - rustc_hir_analysis[6d68d5be0ecf7979]::check::wfcheck::check_mod_type_wf
  25:     0x75750121f20b - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::check_mod_type_wf::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  26:     0x75750181a208 - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_query_system[9a3c01f0ed066ff8]::query::caches::DefaultCache<rustc_span[2659c11acd16cd7]::def_id::LocalModDefId, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  27:     0x757501819fb0 - rustc_query_impl[a2008a1cc616166f]::query_impl::check_mod_type_wf::get_query_non_incr::__rust_end_short_backtrace
  28:     0x757500a9eb9c - rustc_hir_analysis[6d68d5be0ecf7979]::check_crate
  29:     0x757501128cbc - rustc_interface[4b3ef207fa86e12e]::passes::run_required_analyses
  30:     0x757501123d1e - rustc_interface[4b3ef207fa86e12e]::passes::analysis
  31:     0x757501123cef - rustc_query_impl[a2008a1cc616166f]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[a2008a1cc616166f]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>
  32:     0x7575017d5dba - rustc_query_system[9a3c01f0ed066ff8]::query::plumbing::try_execute_query::<rustc_query_impl[a2008a1cc616166f]::DynamicConfig<rustc_query_system[9a3c01f0ed066ff8]::query::caches::SingleCache<rustc_middle[27a877ea52447dab]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[a2008a1cc616166f]::plumbing::QueryCtxt, false>
  33:     0x7575017d5a8e - rustc_query_impl[a2008a1cc616166f]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  34:     0x757501864e39 - rustc_interface[4b3ef207fa86e12e]::interface::run_compiler::<core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>, rustc_driver_impl[c0d80c2a9490dd80]::run_compiler::{closure#0}>::{closure#1}
  35:     0x7575017c08a1 - std[c2c54d6827da810b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_with_globals<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_pool_with_globals<rustc_interface[4b3ef207fa86e12e]::interface::run_compiler<core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>, rustc_driver_impl[c0d80c2a9490dd80]::run_compiler::{closure#0}>::{closure#1}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>
  36:     0x7575017c0548 - <<std[c2c54d6827da810b]::thread::Builder>::spawn_unchecked_<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_with_globals<rustc_interface[4b3ef207fa86e12e]::util::run_in_thread_pool_with_globals<rustc_interface[4b3ef207fa86e12e]::interface::run_compiler<core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>, rustc_driver_impl[c0d80c2a9490dd80]::run_compiler::{closure#0}>::{closure#1}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[437bb64b3ca51b65]::result::Result<(), rustc_span[2659c11acd16cd7]::ErrorGuaranteed>>::{closure#1} as core[437bb64b3ca51b65]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7575017bfc7b - std::sys::pal::unix::thread::Thread::new::thread_start::h2b35487752b07311
  38:     0x7574fbaa339d - <unknown>
  39:     0x7574fbb2849c - <unknown>
  40:                0x0 - <unknown>


rustc version: 1.85.0-nightly (c44b3d50f 2024-12-03)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [compare_impl_item] checking assoc item `<impl at a.rs:55:1: 57:43>::{synthetic#0}` is compatible with trait definition
#1 [check_well_formed] checking that `<impl at a.rs:55:1: 57:43>` is well-formed
#2 [check_mod_type_wf] checking that types are well-formed in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

can we extend what is printed into the file, or are there privacy concerns etc?

**Comment by matthiaskrgr** [comment]
```
rustc version: 1.85.0-nightly (c44b3d50f 2024-12-03)
platform: x86_64-unknown-linux-gnu
```
is there a reason why we only print this into the backtrace file and not the stderr backtrace? Might be useful there as well.

**Comment by jieyouxu** [comment]
> is there a reason why we only print this into the backtrace file and not the stderr backtrace? Might be useful there as well.

Probably only the backtrace itself was included when the dumping mechanism was implemented.

**Comment by saethlin** [comment]
cc @estebank because of this behavior we have bug reports like https://github.com/rust-lang/rust/issues/134541 which are missing useful context. Was omitting the ICE message a deliberate decision?

**Comment by estebank** [comment]
There was some concern about including all the information that ICEs have if they *could* include user information, be it code snippets, paths or even identifiers, particularly for anyone that might be uploading the text file without looking at it first and accidentally leaking data they would have rather they didn't. I landed the minimal "safe" subset of the feature. It would be interesting to maybe have an *opt-in flag* to include that additional useful-to-us data, like the spans/paths/panic message.
