### ISSUE TITLE
Rustc 1.84 beta3 can't build from tarball: bootstrap try to find git commit on non git directory

### ISSUE THREAD

**Issue by 12101111** [rust-lang/rust#133860]
### Code

I tried to compile rustc 1.84 beta 3 from tarball (https://static.rust-lang.org/dist/2024-12-03/)

I expected to see this happen: It should compile

Instead, this happened: bootstrap try to use git and failed

### Version it worked on

It most recently worked on: 1.83.0

### Version with regression

`rustc --version --verbose`:
```rustc 1.84.0-beta.3 (ea5e5ca05 2024-12-02)
binary: rustc
commit-hash: ea5e5ca0553095786f968671ab1c222e5b1df5c3
commit-date: 2024-12-02
host: x86_64-unknown-linux-musl
release: 1.84.0-beta.3
LLVM version: 19.1.4
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
running: /tmp/portage/dev-lang/rust-1.84_beta20241203/work/rustc-beta-src/build/bootstrap/debug/bootstrap build -vvv --config=/tmp/portage/dev-lang/rust-1.84_beta20241203/work/rustc-beta-src/config.toml -j30
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
thread 'main' panicked at src/core/config/config.rs:2908:89:
called `Result::unwrap()` on an `Err` value: "command did not execute successfully: cd \"/tmp/portage/dev-lang/rust-1.84_beta20241203/work/rustc-beta-src\" && \"git\" \"rev-list\" \"--author=bors@rust-lang.org\" \"-n1\" \"--first-parent\" \"HEAD\"\nexpected success, got: exit status: 128\n"
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /usr/lib/rust/1.83.0/lib/rustlib/src/rust/library/core/src/result.rs:1104:23
   4: bootstrap::core::config::config::Config::last_modified_commit
             at ./src/bootstrap/src/core/config/config.rs:2908:22
   5: bootstrap::core::config::config::Config::download_ci_rustc_commit
             at ./src/bootstrap/src/core/config/config.rs:2820:28
   6: bootstrap::core::config::config::Config::parse_inner
             at ./src/bootstrap/src/core/config/config.rs:1775:17
   7: bootstrap::core::config::config::Config::parse
             at ./src/bootstrap/src/core/config/config.rs:1305:9
   8: bootstrap::main
             at ./src/bootstrap/src/bin/main.rs:27:18
   9: core::ops::function::FnOnce::call_once
             at /usr/lib/rust/1.83.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

The regression commit is https://github.com/rust-lang/rust/commit/1837f6f5b10865f0405e4ca3039c016f9cf6c0da

The fix commit is https://github.com/rust-lang/rust/commit/aafd56b87ac45454dd387f632af2eec48b004819

**Comment by jieyouxu** [comment]
I believe this is because the `download-rustc` logic changed back to `false` which skipps running git logic as opposed to when it was defaulted to `if-unchanged` previously. AFAICT this can be closed after #133068 was merged.
