### ISSUE TITLE
better explanation when evaluation of constant value failed with overflowing literal

### ISSUE THREAD

**Issue by b4D8** [rust-lang/rust#133983]
### Code

```Rust
fn main() {
    const _:() = assert!(0 <= 2_147_483_648);
}
```

### Current output

```Shell
error[E0080]: evaluation of constant value failed
 --> src/main.rs:4:18
  |
4 |     const _:() = assert!(0 <= 2_147_483_648);
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: 0 <= 2_147_483_648', src/main.rs:4:18
  |
  = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
```

### Desired output

```Shell
error[E0080]: evaluation of constant value failed
 --> src/main.rs:4:18
  |
4 |     const _:() = assert!(0 <= 2_147_483_648);
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: 0 <= 2_147_483_648', src/main.rs:4:18
  |
  = note: the literal `2_147_483_648` does not fit into the type `i32` whose range is `-2147483648..=2147483647`
  = help: consider using the type `u32` instead

For more information about this error, try `rustc --explain E0080`.
```

### Rationale and extra context

See: https://users.rust-lang.org/t/const-assertion-fails-to-infer-correct-type/122166/3

Desired output based on the [message returned in normal (not const) context](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7136d82a7b4a351769c38695ab75a871).

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1
```

**Comment by FedericoBruzzone** [comment]
IMHO, the your desired output should have as last `note` the following:

```
= note: `#[deny(overflowing_literals)]` on by default
```
