### ISSUE TITLE
regression: ICE: `tcx.extern_crate(LocalCrate)` is not supported for this key

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#134705]
### Meta

Using `rustc 1.84.0-beta.4` from crater #134138. 

### Error output

1. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/dpl0a.type-aliasing-bug/log.txt

```
[INFO] [stdout] error: internal compiler error: compiler/rustc_middle/src/query/plumbing.rs:654:5: `tcx.extern_crate(LocalCrate)` is not supported for this key;
[INFO] [stdout]                                 hint: Queries can be either made to the local crate, or the external crate. This error means you tried to use it for one that's not supported.
[INFO] [stdout]                                 If that's not the case, extern_crate was likely never assigned to a provider function.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
[INFO] [stderr] thread 'rustc' panicked at compiler/rustc_middle/src/query/plumbing.rs:654:5:
[INFO] [stderr] Box<dyn Any>
[INFO] [stderr] stack backtrace:
[INFO] [stderr]    0:     0x7ccf1c09152a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h98c26ac25ffe89bb
[INFO] [stderr]    1:     0x7ccf1c8248fc - core::fmt::write::h0dd5f6e2238c7982
[INFO] [stderr]    2:     0x7ccf1d74ffd1 - std::io::Write::write_fmt::hc00bff0a88e08857
[INFO] [stderr]    3:     0x7ccf1c091382 - std::sys::backtrace::BacktraceLock::print::h5c19c1c038ee186d
[INFO] [stderr]    4:     0x7ccf1c09385a - std::panicking::default_hook::{{closure}}::h77172f079a1fcb13
[INFO] [stderr]    5:     0x7ccf1c0936c0 - std::panicking::default_hook::he5f8e3b203ccddba
[INFO] [stderr]    6:     0x7ccf1b1108b5 - std[b9e7ca495922dc28]::panicking::update_hook::<alloc[a74230b4a4ddab6d]::boxed::Box<rustc_driver_impl[a84ad889800babb7]::install_ice_hook::{closure#0}>>::{closure#0}
[INFO] [stderr]    7:     0x7ccf1c093f38 - std::panicking::rust_panic_with_hook::h53863d4e9018df39
[INFO] [stderr]    8:     0x7ccf1b14ab81 - std[b9e7ca495922dc28]::panicking::begin_panic::<rustc_errors[b985534e12de5b37]::ExplicitBug>::{closure#0}
[INFO] [stderr]    9:     0x7ccf1b13db46 - std[b9e7ca495922dc28]::sys::backtrace::__rust_end_short_backtrace::<std[b9e7ca495922dc28]::panicking::begin_panic<rustc_errors[b985534e12de5b37]::ExplicitBug>::{closure#0}, !>
[INFO] [stderr]   10:     0x7ccf1b13934d - std[b9e7ca495922dc28]::panicking::begin_panic::<rustc_errors[b985534e12de5b37]::ExplicitBug>
[INFO] [stderr]   11:     0x7ccf1b154ab1 - <rustc_errors[b985534e12de5b37]::diagnostic::BugAbort as rustc_errors[b985534e12de5b37]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
[INFO] [stderr]   12:     0x7ccf1b7ce383 - rustc_middle[bd74a45dc8a6aeec]::util::bug::opt_span_bug_fmt::<rustc_span[84c8ca3d0b382817]::span_encoding::Span>::{closure#0}
[INFO] [stderr]   13:     0x7ccf1b7b58fa - rustc_middle[bd74a45dc8a6aeec]::ty::context::tls::with_opt::<rustc_middle[bd74a45dc8a6aeec]::util::bug::opt_span_bug_fmt<rustc_span[84c8ca3d0b382817]::span_encoding::Span>::{closure#0}, !>::{closure#0}
[INFO] [stderr]   14:     0x7ccf1b7b578b - rustc_middle[bd74a45dc8a6aeec]::ty::context::tls::with_context_opt::<rustc_middle[bd74a45dc8a6aeec]::ty::context::tls::with_opt<rustc_middle[bd74a45dc8a6aeec]::util::bug::opt_span_bug_fmt<rustc_span[84c8ca3d0b382817]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
[INFO] [stderr]   15:     0x7ccf198e9f60 - rustc_middle[bd74a45dc8a6aeec]::util::bug::bug_fmt
[INFO] [stderr]   16:     0x7ccf1b7d2645 - rustc_middle[bd74a45dc8a6aeec]::query::plumbing::default_query
[INFO] [stderr]   17:     0x7ccf1b77b9de - <<rustc_middle[bd74a45dc8a6aeec]::query::Providers as core[d10bf40c8679dc2f]::default::Default>::default::{closure#193} as core[d10bf40c8679dc2f]::ops::function::FnOnce<(rustc_middle[bd74a45dc8a6aeec]::ty::context::TyCtxt, rustc_middle[bd74a45dc8a6aeec]::query::keys::LocalCrate)>>::call_once
[INFO] [stderr]   18:     0x7ccf1e467b26 - rustc_query_impl[8969a7b8ce30dc91]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8969a7b8ce30dc91]::query_impl::extern_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>>.cold
[INFO] [stderr]   19:     0x7ccf1d6ca15c - rustc_query_system[bc50a602aa0ddde9]::query::plumbing::try_execute_query::<rustc_query_impl[8969a7b8ce30dc91]::DynamicConfig<rustc_data_structures[181125383e64cf8f]::vec_cache::VecCache<rustc_span[84c8ca3d0b382817]::def_id::CrateNum, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[bc50a602aa0ddde9]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[8969a7b8ce30dc91]::plumbing::QueryCtxt, false>
[INFO] [stderr]   20:     0x7ccf1d6c66c3 - rustc_query_impl[8969a7b8ce30dc91]::query_impl::extern_crate::get_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   21:     0x7ccf1bed0e93 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_similar_impl_candidates
[INFO] [stderr]   22:     0x7ccf1bedca77 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::try_to_add_help_message
[INFO] [stderr]   23:     0x7ccf1becb879 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_selection_error
[INFO] [stderr]   24:     0x7ccf1bf45fb4 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_fulfillment_error
[INFO] [stderr]   25:     0x7ccf1bf14747 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_fulfillment_errors
[INFO] [stderr]   26:     0x7ccf18ffab58 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::confirm_builtin_call
[INFO] [stderr]   27:     0x7ccf1d4ec34f - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   28:     0x7ccf1d4ed3da - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   29:     0x7ccf1d4f1b8e - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   30:     0x7ccf1c9305fc - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_match::{closure#0}
[INFO] [stderr]   31:     0x7ccf1d4edefe - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   32:     0x7ccf1d4e6966 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   33:     0x7ccf1d4ecc3b - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   34:     0x7ccf1ca31274 - rustc_hir_typeck[4b7e460e4213188]::check::check_fn
[INFO] [stderr]   35:     0x7ccf1ca3bedb - rustc_hir_typeck[4b7e460e4213188]::typeck
[INFO] [stderr]   36:     0x7ccf1ca3ab63 - rustc_query_impl[8969a7b8ce30dc91]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8969a7b8ce30dc91]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>>
[INFO] [stderr]   37:     0x7ccf1ca5274e - rustc_query_system[bc50a602aa0ddde9]::query::plumbing::try_execute_query::<rustc_query_impl[8969a7b8ce30dc91]::DynamicConfig<rustc_data_structures[181125383e64cf8f]::vec_cache::VecCache<rustc_span[84c8ca3d0b382817]::def_id::LocalDefId, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[bc50a602aa0ddde9]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[8969a7b8ce30dc91]::plumbing::QueryCtxt, false>
[INFO] [stderr]   38:     0x7ccf1ca51315 - rustc_query_impl[8969a7b8ce30dc91]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   39:     0x7ccf1ca50fe7 - <rustc_middle[bd74a45dc8a6aeec]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[926270c899b0aa20]::check_crate::{closure#4}>::{closure#0}
[INFO] [stderr]   40:     0x7ccf1ca4f026 - rustc_hir_analysis[926270c899b0aa20]::check_crate
[INFO] [stderr]   41:     0x7ccf1d07df0a - rustc_interface[164bca52f843a547]::passes::run_required_analyses
[INFO] [stderr]   42:     0x7ccf1d0721de - rustc_interface[164bca52f843a547]::passes::analysis
[INFO] [stderr]   43:     0x7ccf1d0721af - rustc_query_impl[8969a7b8ce30dc91]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8969a7b8ce30dc91]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 1usize]>>
[INFO] [stderr]   44:     0x7ccf1d7c66ae - rustc_query_system[bc50a602aa0ddde9]::query::plumbing::try_execute_query::<rustc_query_impl[8969a7b8ce30dc91]::DynamicConfig<rustc_query_system[bc50a602aa0ddde9]::query::caches::SingleCache<rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[8969a7b8ce30dc91]::plumbing::QueryCtxt, false>
[INFO] [stderr]   45:     0x7ccf1d7c638e - rustc_query_impl[8969a7b8ce30dc91]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   46:     0x7ccf1d708898 - rustc_interface[164bca52f843a547]::interface::run_compiler::<core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>, rustc_driver_impl[a84ad889800babb7]::run_compiler::{closure#0}>::{closure#1}
[INFO] [stderr]   47:     0x7ccf1d733420 - std[b9e7ca495922dc28]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[164bca52f843a547]::util::run_in_thread_with_globals<rustc_interface[164bca52f843a547]::util::run_in_thread_pool_with_globals<rustc_interface[164bca52f843a547]::interface::run_compiler<core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>, rustc_driver_impl[a84ad889800babb7]::run_compiler::{closure#0}>::{closure#1}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>
[INFO] [stderr]   48:     0x7ccf1d73313d - <<std[b9e7ca495922dc28]::thread::Builder>::spawn_unchecked_<rustc_interface[164bca52f843a547]::util::run_in_thread_with_globals<rustc_interface[164bca52f843a547]::util::run_in_thread_pool_with_globals<rustc_interface[164bca52f843a547]::interface::run_compiler<core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>, rustc_driver_impl[a84ad889800babb7]::run_compiler::{closure#0}>::{closure#1}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#1} as core[d10bf40c8679dc2f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
[INFO] [stderr]   49:     0x7ccf1d7328f9 - std::sys::pal::unix::thread::Thread::new::thread_start::h48cf765408f6f5f2
[INFO] [stderr]   50:     0x7ccf1ef89ac3 - <unknown>
[INFO] [stderr]   51:     0x7ccf1f01aa04 - clone
[INFO] [stderr]   52:                0x0 - <unknown>
[INFO] [stderr] 
[INFO] [stderr] note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
[INFO] [stderr] 
[INFO] [stderr] note: rustc 1.84.0-beta.4 (202008a1b 2024-12-07) running on x86_64-unknown-linux-gnu
[INFO] [stderr] 
[INFO] [stderr] note: compiler flags: -C embed-bitcode=no -C debuginfo=2
[INFO] [stderr] 
[INFO] [stderr] note: some of the compiler flags provided by cargo are hidden
[INFO] [stderr] 
[INFO] [stderr] query stack during panic:
[INFO] [stderr] #0 [extern_crate] getting crate's ExternCrateData
[INFO] [stderr] #1 [typeck] type-checking `tests::footest`
[INFO] [stderr] #2 [analysis] running analysis passes on this crate
[INFO] [stderr] end of query stack
[INFO] [stderr] error: could not compile `type-aliasing-bug` (lib test)
```

</p>
</details>

---

2. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/Luminoth.mazes-for-programmers/log.txt

```
[INFO] [stdout] error: internal compiler error: compiler/rustc_middle/src/query/plumbing.rs:654:5: `tcx.extern_crate(LocalCrate)` is not supported for this key;
[INFO] [stdout]                                 hint: Queries can be either made to the local crate, or the external crate. This error means you tried to use it for one that's not supported.
[INFO] [stdout]                                 If that's not the case, extern_crate was likely never assigned to a provider function.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
[INFO] [stderr] thread 'rustc' panicked at compiler/rustc_middle/src/query/plumbing.rs:654:5:
[INFO] [stderr] Box<dyn Any>
[INFO] [stderr] stack backtrace:
[INFO] [stderr]    0:     0x7ae151c9152a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h98c26ac25ffe89bb
[INFO] [stderr]    1:     0x7ae1524248fc - core::fmt::write::h0dd5f6e2238c7982
[INFO] [stderr]    2:     0x7ae15334ffd1 - std::io::Write::write_fmt::hc00bff0a88e08857
[INFO] [stderr]    3:     0x7ae151c91382 - std::sys::backtrace::BacktraceLock::print::h5c19c1c038ee186d
[INFO] [stderr]    4:     0x7ae151c9385a - std::panicking::default_hook::{{closure}}::h77172f079a1fcb13
[INFO] [stderr]    5:     0x7ae151c936c0 - std::panicking::default_hook::he5f8e3b203ccddba
[INFO] [stderr]    6:     0x7ae150d108b5 - std[b9e7ca495922dc28]::panicking::update_hook::<alloc[a74230b4a4ddab6d]::boxed::Box<rustc_driver_impl[a84ad889800babb7]::install_ice_hook::{closure#0}>>::{closure#0}
[INFO] [stderr]    7:     0x7ae151c93f38 - std::panicking::rust_panic_with_hook::h53863d4e9018df39
[INFO] [stderr]    8:     0x7ae150d4ab81 - std[b9e7ca495922dc28]::panicking::begin_panic::<rustc_errors[b985534e12de5b37]::ExplicitBug>::{closure#0}
[INFO] [stderr]    9:     0x7ae150d3db46 - std[b9e7ca495922dc28]::sys::backtrace::__rust_end_short_backtrace::<std[b9e7ca495922dc28]::panicking::begin_panic<rustc_errors[b985534e12de5b37]::ExplicitBug>::{closure#0}, !>
[INFO] [stderr]   10:     0x7ae150d3934d - std[b9e7ca495922dc28]::panicking::begin_panic::<rustc_errors[b985534e12de5b37]::ExplicitBug>
[INFO] [stderr]   11:     0x7ae150d54ab1 - <rustc_errors[b985534e12de5b37]::diagnostic::BugAbort as rustc_errors[b985534e12de5b37]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
[INFO] [stderr]   12:     0x7ae1513ce383 - rustc_middle[bd74a45dc8a6aeec]::util::bug::opt_span_bug_fmt::<rustc_span[84c8ca3d0b382817]::span_encoding::Span>::{closure#0}
[INFO] [stderr]   13:     0x7ae1513b58fa - rustc_middle[bd74a45dc8a6aeec]::ty::context::tls::with_opt::<rustc_middle[bd74a45dc8a6aeec]::util::bug::opt_span_bug_fmt<rustc_span[84c8ca3d0b382817]::span_encoding::Span>::{closure#0}, !>::{closure#0}
[INFO] [stderr]   14:     0x7ae1513b578b - rustc_middle[bd74a45dc8a6aeec]::ty::context::tls::with_context_opt::<rustc_middle[bd74a45dc8a6aeec]::ty::context::tls::with_opt<rustc_middle[bd74a45dc8a6aeec]::util::bug::opt_span_bug_fmt<rustc_span[84c8ca3d0b382817]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
[INFO] [stderr]   15:     0x7ae14f4e9f60 - rustc_middle[bd74a45dc8a6aeec]::util::bug::bug_fmt
[INFO] [stderr]   16:     0x7ae1513d2645 - rustc_middle[bd74a45dc8a6aeec]::query::plumbing::default_query
[INFO] [stderr]   17:     0x7ae15137b9de - <<rustc_middle[bd74a45dc8a6aeec]::query::Providers as core[d10bf40c8679dc2f]::default::Default>::default::{closure#193} as core[d10bf40c8679dc2f]::ops::function::FnOnce<(rustc_middle[bd74a45dc8a6aeec]::ty::context::TyCtxt, rustc_middle[bd74a45dc8a6aeec]::query::keys::LocalCrate)>>::call_once
[INFO] [stderr]   18:     0x7ae154067b26 - rustc_query_impl[8969a7b8ce30dc91]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8969a7b8ce30dc91]::query_impl::extern_crate::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>>.cold
[INFO] [stderr]   19:     0x7ae1532ca15c - rustc_query_system[bc50a602aa0ddde9]::query::plumbing::try_execute_query::<rustc_query_impl[8969a7b8ce30dc91]::DynamicConfig<rustc_data_structures[181125383e64cf8f]::vec_cache::VecCache<rustc_span[84c8ca3d0b382817]::def_id::CrateNum, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[bc50a602aa0ddde9]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[8969a7b8ce30dc91]::plumbing::QueryCtxt, false>
[INFO] [stderr]   20:     0x7ae1532c66c3 - rustc_query_impl[8969a7b8ce30dc91]::query_impl::extern_crate::get_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   21:     0x7ae151ad0e93 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_similar_impl_candidates
[INFO] [stderr]   22:     0x7ae151adca77 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::try_to_add_help_message
[INFO] [stderr]   23:     0x7ae151acb879 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_selection_error
[INFO] [stderr]   24:     0x7ae151b45fb4 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_fulfillment_error
[INFO] [stderr]   25:     0x7ae151b14747 - <rustc_trait_selection[b0ba933a80d089ed]::error_reporting::TypeErrCtxt>::report_fulfillment_errors
[INFO] [stderr]   26:     0x7ae14ec3a7b0 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_argument_types
[INFO] [stderr]   27:     0x7ae1530f9a2e - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   28:     0x7ae1530e6885 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   29:     0x7ae1530ecc3b - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   30:     0x7ae152530e10 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_match::{closure#0}
[INFO] [stderr]   31:     0x7ae1530edefe - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   32:     0x7ae1530e78f1 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   33:     0x7ae1530f15e1 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   34:     0x7ae152530e10 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_match::{closure#0}
[INFO] [stderr]   35:     0x7ae1530edefe - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   36:     0x7ae1530eec6e - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   37:     0x7ae1530e78f1 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   38:     0x7ae1530ecc3b - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   39:     0x7ae152530e10 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_match::{closure#0}
[INFO] [stderr]   40:     0x7ae1530edefe - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   41:     0x7ae1530e78f1 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   42:     0x7ae1530f15e1 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   43:     0x7ae152530e10 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_match::{closure#0}
[INFO] [stderr]   44:     0x7ae1530edefe - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   45:     0x7ae1530eec6e - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   46:     0x7ae1530e78f1 - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   47:     0x7ae1530ecc3b - <rustc_hir_typeck[4b7e460e4213188]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   48:     0x7ae152631274 - rustc_hir_typeck[4b7e460e4213188]::check::check_fn
[INFO] [stderr]   49:     0x7ae15263bedb - rustc_hir_typeck[4b7e460e4213188]::typeck
[INFO] [stderr]   50:     0x7ae15263ab63 - rustc_query_impl[8969a7b8ce30dc91]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8969a7b8ce30dc91]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>>
[INFO] [stderr]   51:     0x7ae15265274e - rustc_query_system[bc50a602aa0ddde9]::query::plumbing::try_execute_query::<rustc_query_impl[8969a7b8ce30dc91]::DynamicConfig<rustc_data_structures[181125383e64cf8f]::vec_cache::VecCache<rustc_span[84c8ca3d0b382817]::def_id::LocalDefId, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[bc50a602aa0ddde9]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[8969a7b8ce30dc91]::plumbing::QueryCtxt, false>
[INFO] [stderr]   52:     0x7ae152651315 - rustc_query_impl[8969a7b8ce30dc91]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   53:     0x7ae152650fe7 - <rustc_middle[bd74a45dc8a6aeec]::hir::map::Map>::par_body_owners::<rustc_hir_analysis[926270c899b0aa20]::check_crate::{closure#4}>::{closure#0}
[INFO] [stderr]   54:     0x7ae15264f026 - rustc_hir_analysis[926270c899b0aa20]::check_crate
[INFO] [stderr]   55:     0x7ae152c7df0a - rustc_interface[164bca52f843a547]::passes::run_required_analyses
[INFO] [stderr]   56:     0x7ae152c721de - rustc_interface[164bca52f843a547]::passes::analysis
[INFO] [stderr]   57:     0x7ae152c721af - rustc_query_impl[8969a7b8ce30dc91]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[8969a7b8ce30dc91]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 1usize]>>
[INFO] [stderr]   58:     0x7ae1533c66ae - rustc_query_system[bc50a602aa0ddde9]::query::plumbing::try_execute_query::<rustc_query_impl[8969a7b8ce30dc91]::DynamicConfig<rustc_query_system[bc50a602aa0ddde9]::query::caches::SingleCache<rustc_middle[bd74a45dc8a6aeec]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[8969a7b8ce30dc91]::plumbing::QueryCtxt, false>
[INFO] [stderr]   59:     0x7ae1533c638e - rustc_query_impl[8969a7b8ce30dc91]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   60:     0x7ae153308898 - rustc_interface[164bca52f843a547]::interface::run_compiler::<core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>, rustc_driver_impl[a84ad889800babb7]::run_compiler::{closure#0}>::{closure#1}
[INFO] [stderr]   61:     0x7ae153333420 - std[b9e7ca495922dc28]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[164bca52f843a547]::util::run_in_thread_with_globals<rustc_interface[164bca52f843a547]::util::run_in_thread_pool_with_globals<rustc_interface[164bca52f843a547]::interface::run_compiler<core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>, rustc_driver_impl[a84ad889800babb7]::run_compiler::{closure#0}>::{closure#1}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>
[INFO] [stderr]   62:     0x7ae15333313d - <<std[b9e7ca495922dc28]::thread::Builder>::spawn_unchecked_<rustc_interface[164bca52f843a547]::util::run_in_thread_with_globals<rustc_interface[164bca52f843a547]::util::run_in_thread_pool_with_globals<rustc_interface[164bca52f843a547]::interface::run_compiler<core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>, rustc_driver_impl[a84ad889800babb7]::run_compiler::{closure#0}>::{closure#1}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d10bf40c8679dc2f]::result::Result<(), rustc_span[84c8ca3d0b382817]::ErrorGuaranteed>>::{closure#1} as core[d10bf40c8679dc2f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
[INFO] [stderr]   63:     0x7ae1533328f9 - std::sys::pal::unix::thread::Thread::new::thread_start::h48cf765408f6f5f2
[INFO] [stderr]   64:     0x7ae154bb4ac3 - <unknown>
[INFO] [stderr]   65:     0x7ae154c45a04 - clone
[INFO] [stderr]   66:                0x0 - <unknown>
[INFO] [stderr] 
[INFO] [stderr]    Compiling tracing-subscriber v0.3.9
[INFO] [stderr] note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
[INFO] [stderr] 
[INFO] [stderr] note: rustc 1.84.0-beta.4 (202008a1b 2024-12-07) running on x86_64-unknown-linux-gnu
[INFO] [stderr] 
[INFO] [stderr] note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2
[INFO] [stderr] 
[INFO] [stderr] note: some of the compiler flags provided by cargo are hidden
[INFO] [stderr] 
[INFO] [stderr] query stack during panic:
[INFO] [stderr] #0 [extern_crate] getting crate's ExternCrateData
[INFO] [stderr] #1 [typeck] type-checking `grid::<impl at core/src/grid.rs:380:1: 380:20>::render_ascii`
[INFO] [stderr] #2 [analysis] running analysis passes on this crate
[INFO] [stderr] end of query stack
[INFO] [stdout] Some errors have detailed explanations: E0599, E0609.
[INFO] [stdout] 
[INFO] [stdout] For more information about an error, try `rustc --explain E0599`.
[INFO] [stdout] 
[INFO] [stderr] error: could not compile `core` (lib) due to 13 previous errors
```

</p>
</details>

**Comment by compiler-errors** [comment]
This should be fixed by #133585, which just needs a backport.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23134705.20regression.3A.20.60tcx.2Eextern_crate.28LocalCrate.29.60.20is.20not.20s.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by Mark-Simulacrum** [comment]
Backported/fixed in https://github.com/rust-lang/rust/pull/135048.
