### ISSUE TITLE
make check should suspend TIME_PASSES env var for pretty tests?

### ISSUE THREAD

**Issue by jbclements** [rust-lang/rust#15337]
It appears to me that running `make check` while there's an env var `TIME_PASSES` set to 1 causes all pretty-print tests to fail, because (it appears to me) the makefile passes `-Z time-passes` to the invocation of `rustc --pretty normal`, causing (e.g.) this failure:

``` rust

    task '[pretty] run-pass/writealias.rs' failed at 'explicit failure', /Users/clements/rust/src/compiletest/runtest.rs:1311


---- [pretty] run-pass/x86stdcall.rs stdout ----

    error: pretty-printing failed in round 1
    status: exit code: 101
    command: x86_64-apple-darwin/stage2/bin/rustc - --pretty normal --target=x86_64-apple-darwin -L x86_64-apple-darwin/test/run-pass/x86stdcall.stage2-x86_64-apple-darwin.libaux --cfg rtopt --cfg debug -Z time-passes -O -L x86_64-apple-darwin/rt
    stdout:
    ------------------------------------------

    ------------------------------------------
    stderr:
    ------------------------------------------
    <anon>:1:1: 1:5 error: expected item but found `time`
    <anon>:1 time: 0.001 s  parsing
             ^~~~

    ------------------------------------------
```

... note that the parser is failing in trying to parse the line `time: 0.001 s  parsing`.. 

looks like an easy fix in a makefile, if it's even worth fixing. Depends on how other folks feel about it.

**Comment by emanueLczirai** [comment]
Confirmed this still happens with `make check NO_REBUILD=1 TIME_PASSES=1 TIME_LLVM_PASSES=1`
tested with latest commit aedcbb9d82ccd7ead4b075ff55a99e363be94174

`test result: FAILED. 0 passed; 1816 failed; 75 ignored; 0 measured`

sample:

```
---- [pretty] run-pass/zero_sized_subslice_match.rs stdout ----
	
error: pretty-printing failed in round 1
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc - -Zunstable-options --pretty normal --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/run-pass/zero_sized_subslice_match.stage2-x86_64-unknown-linux-gnulibaux --cfg rtopt -Z time-passes -Z time-llvm-passes -O -L x86_64-unknown-linux-gnu/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
<anon>:1:1: 1:5 error: expected item, found `time`
<anon>:1 time: 0.000 	parsing
         ^~~~

------------------------------------------

thread '[pretty] run-pass/zero_sized_subslice_match.rs' panicked at 'explicit panic', /home/emacs/build/rust/src/compiletest/runtest.rs:1458
```

**Comment by steveklabnik** [comment]
After an extremely long build time, I can confirm that this is still an issue.

**Comment by Mark-Simulacrum** [comment]
#14607 is a more specific and likely easier/faster to reproduce.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of #14607.
