### ISSUE TITLE
rustdoc panics if target crate has compilation errors

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#19181]
# Updated issue
### STR

``` rust
// err.rs
fn main() { 0 }
```
### Output

```
$ rustc err.rs 2>/dev/null || echo compilation error as expected
compilation error as expected
$ rustdoc err.rs
err.rs:2:5: 2:6 error: mismatched types: expected `()`, found `_` (expected (), found integral variable)
err.rs:2     0
             ^
error: aborting due to previous error
task '<unnamed>' panicked at 'Box<Any>', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libsyntax/diagnostic.rs:142
task '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: rustc failed', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libcore/result.rs:743
```

---
# Original issue: rustdoc panics with `#![deny(missing_docs]` and associated items
### STR

``` rust
#![deny(missing_docs)]
#![feature(associated_types)]

//! Crate

/// Trait
pub trait AsSlice {
    /// Item
    type Item;

    // Forgot to document the method
    fn as_slice(&self) -> &[<Self as AsSlice>::Item];
}
```
### Output

``` rust
ai.rs:12:5: 12:53 error: missing documentation for a type method
ai.rs:12     fn as_slice(&self) -> &[<Self as AsSlice>::Item];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ai.rs:1:9: 1:21 note: lint level defined here
ai.rs:1 #![deny(missing_docs)]
                ^~~~~~~~~~~~
error: aborting due to previous error
task '<unnamed>' panicked at 'Box<Any>', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libsyntax/diagnostic.rs:142
task '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: rustc failed', /var/tmp/paludis/build/dev-lang-rust-scm/work/rust-scm/src/libcore/result.rs:743
```
### Version
#19174 on top of c9f6d69

cc @tomjakubowski

**Comment by tamird** [comment]
@steveklabnik I think this should not be tagged I-ICE since it is strictly a `rustdoc` issue.

**Comment by bltavares** [comment]
Triaging this issue.

It still happens on `rustc 1.7.0-nightly (b4707ebca 2015-12-27)`

**Comment by mitaa** [comment]
The two testcases don't panic for me (fixed/needstest ?)

`rustdoc 1.8.0-nightly (57c357d89 2016-02-16)`

**Comment by Mark-Simulacrum** [comment]
Yeah, this has been fixed. E-needstest.

```
error[E0308]: mismatched types
 --> test.rs:2:13
  |
2 | fn main() { 0 }
  |             ^ expected (), found integral variable
  |
  = note: expected type `()`
             found type `{integer}`

error: Compilation failed, aborting rustdoc
```
