### ISSUE TITLE
Panic => hang with -C codegen-units=2

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#20184]
Building `src/test/compile-fail/asm-src-loc-codegen-units.rs`, I get

```
$ RUST_BACKTRACE=1 x86_64-unknown-linux-gnu/stage1/bin/rustc /home/keegan/rust/src/test/compile-fail/asm-src-loc-codegen-units.rs -L x86_64-unknown-linux-gnu/test/compile-fail --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage1-x86_64-unknown-linux-gnulibaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage1-x86_64-unknown-linux-gnu --cfg rtopt --cfg debug -C rpath -O -L x86_64-unknown-linux-gnu/rt -C codegen-units=2  
thread 'codegen-1' panicked at 'Box<Any>', /home/keegan/rust/src/libsyntax/diagnostic.rs:144  
stack backtrace:  
   1:     0x7fa4c3cc6160 - sys::backtrace::write::h65ec9c5123795f5a7Et  
   2:     0x7fa4c3ce1560 - failure::on_fail::h57fab0e8dcfaeb44q5z  
   3:     0x7fa4c3c64d30 - rt::unwind::begin_unwind_inner::hfb3e098e3005b453qJz  
   4:     0x7fa4bf1b71d0 - rt::unwind::begin_unwind::h10618648795271420137  
   5:     0x7fa4bf1b7c70 - diagnostic::Handler::fatal::h4880a8481789b123GZF  
   6:     0x7fa4bf1b7e70 - diagnostic::Handler::abort_if_errors::h67ec7bdbe130dc33m1F  
   7:     0x7fa4c2b9b470 - thunk::F.Invoke<A,$u{20}R$GT$::invoke::h6510616859115949120  
   8:     0x7fa4c2b9a250 - rt::unwind::try::try_fn::h2108817931159087488  
   9:     0x7fa4c3d50080 - rust_try_inner  
  10:     0x7fa4c3d50070 - rust_try  
  11:     0x7fa4c2b9a4f0 - thunk::F.Invoke<A,$u{20}R$GT$::invoke::h6356295493119065651  
  12:     0x7fa4c3cd3870 - sys::thread::thread_start::h343c9a18cc8a2c6fxDw  
  13:     0x7fa4be9d0fe0 - start_thread  
  14:     0x7fa4c3911c99 - __clone  
  15:                0x0 - <unknown>  
```

at which point rustc hangs. Version: 96a3c7c6a051ab2f5fc01fe9e686f7fffcc87c61 (current master)

**Comment by tamird** [comment]
triage: still reproduces.

```shell
$ DYLD_LIBRARY_PATH=../rust-build/x86_64-apple-darwin/stage1/lib \
  ../rust-build/x86_64-apple-darwin/stage1/bin/rustc -C codegen-units=2 \
  src/test/compile-fail/asm-src-loc-codegen-units.rs
thread 'codegen-1' panicked at 'Box<Any>', /Users/tamird/src/rust/src/libsyntax/diagnostic.rs:192
<rustc is hung here>
```

**Comment by tamird** [comment]
bah this should be reopened

**Comment by dotdash** [comment]
@nrc You wondered on irc why there's a hang on stage 1 but not on stage 2, and I'm not sure it's related, but stage 0 (which builds the compiler used during stage 1) compiles without landing pads, maybe that breaks something?

**Comment by nrc** [comment]
I'm 99% sure this is because we build stage1 without landing pads.

**Comment by nrc** [comment]
See #16373, this led to a 19% improvement in build time, so we should not re-enable this test.
