### ISSUE TITLE
ICE: generic_bounds.has_escaping_regions()

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#21139]
```
Compiling hyper v0.1.1 (file:///home/manishearth/Mozilla/Git/hyper)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: !generic_bounds.has_escaping_regions()', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:2281
```

I was trying to use unboxed closures in Hyper, and I came across this.

[Here](https://github.com/Manishearth/hyper/commit/69d3aeba1f1793aed3a1b42b3180f6fe293e9135)'s the commit where it got introduced.

The following MWE also causes the ICE:

```
#![feature(unboxed_closures)]

pub struct HttpConnector<T = NoSslVerify>(Option<T>);
pub struct NoSslVerify;

impl Fn(&mut u8) -> () for NoSslVerify {
    #[inline(always)]
    fn call(&self, _: (&mut u8)) {}
}
```

**Comment by tamird** [comment]
@Manishearth this no longer compiles. Can you update the MWE?

**Comment by Manishearth** [comment]
Not sure if I can, things seem to have changed a lot.

```
#![feature(unboxed_closures, core)]

pub struct HttpConnector<T = NoSslVerify>(Option<T>);
pub struct NoSslVerify;

impl<'a> FnOnce<&'a mut u8> for NoSslVerify {
    type Output = ();
    #[inline(always)]
    extern "rust-call" fn call_once(self, _: (&mut u8)) {}
}
```

produces a _different_ ICE


```
error: internal compiler error: argument to function with "rust-call" ABI is neither a tuple nor unit
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:230
```

**Comment by arielb1** [comment]
dupe of #22565

**Comment by steveklabnik** [comment]
Triage: tracked by glacier. That said, pretty sure I agree with @arielb1 that this is a duplicate. Not 100% sure, so I'll keep it open; if anyone knows for sure, please feel free to close.
