### ISSUE TITLE
error: internal compiler error: this path should not cause illegal move

### ISSUE THREAD

**Issue by andrewrk** [rust-lang/rust#21273]
Here is the code that generates the issue:
https://github.com/andrewrk/rust-groove/tree/rust-bug-1

Here is the output:
```
andy@andy-bx:~/dev/rust-groove$ uname -a
Linux andy-bx 3.16.0-25-generic #33-Ubuntu SMP Tue Nov 4 12:06:54 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
andy@andy-bx:~/dev/rust-groove$ rustc --version --verbose
rustc 1.0.0-nightly (8903c21d6 2015-01-15 22:42:58 +0000)
binary: rustc
commit-hash: 8903c21d618fd25dca61d9bb668c5299d21feac9
commit-date: 2015-01-15 22:42:58 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
andy@andy-bx:~/dev/rust-groove$ RUST_BACKTRACE=1 cargo test --verbose
   Compiling groove v0.0.1 (file:///home/andy/dev/rust-groove)
     Running `rustc src/lib.rs --crate-name groove --crate-type lib -g -C metadata=26cd79f71fc2edaa -C extra-filename=-26cd79f71fc2edaa --out-dir /home/andy/dev/rust-groove/target --emit=dep-info,link -L dependency=/home/andy/dev/rust-groove/target -L dependency=/home/andy/dev/rust-groove/target/deps`
     Running `rustc src/lib.rs --crate-name groove --crate-type lib -g --test -C metadata=3f428b811436bb9b -C extra-filename=-3f428b811436bb9b --out-dir /home/andy/dev/rust-groove/target --emit=dep-info,link -L dependency=/home/andy/dev/rust-groove/target -L dependency=/home/andy/dev/rust-groove/target/deps`
src/lib.rs:26:31: 26:48 error: internal compiler error: this path should not cause illegal move
src/lib.rs:26             let groove_file = *self.groove_file;
                                            ^~~~~~~~~~~~~~~~~
src/lib.rs:26:31: 26:48 error: internal compiler error: this path should not cause illegal move
src/lib.rs:26             let groove_file = *self.groove_file;
                                            ^~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123

stack backtrace:
   1:     0x7f41d1366000 - sys::backtrace::write::h7e8ba1fc274cc36epRt
   2:     0x7f41d13879e0 - failure::on_fail::h823798930ebe140a64z
   3:     0x7f41d12f67b0 - rt::unwind::begin_unwind_inner::ha4a8df6010104da6ZJz
   4:     0x7f41cbf61330 - rt::unwind::begin_unwind::h2017061421562134061
   5:     0x7f41cbf612c0 - diagnostic::SpanHandler::span_bug::h26a451e055cae458CYF
   6:     0x7f41cf44c810 - session::Session::span_bug::h64d8052083ced862Ebr
   7:     0x7f41d00216c0 - borrowck::build_borrowck_dataflow_data::h8c638256049ffbefKRe
   8:     0x7f41d001e400 - borrowck::borrowck_fn::hdc6b07f7f72f47a26Oe
   9:     0x7f41d0021570 - visit::walk_method_helper::h16178071186034281973
  10:     0x7f41d001f310 - borrowck::borrowck_item::h22dfd39207f6713d3Ne
  11:     0x7f41d001f880 - borrowck::check_crate::hd2a6930915fc4577UIe
  12:     0x7f41d18b82e0 - driver::phase_3_run_analysis_passes::h77110bff138a8fd0EEa
  13:     0x7f41d18a5d70 - driver::compile_input::h8ec974b2bd4afe59Aba
  14:     0x7f41d19674d0 - run_compiler::h0e495a7c10e57aaae5b
  15:     0x7f41d1965c40 - thunk::F.Invoke<A, R>::invoke::h12226774702741163622
  16:     0x7f41d1964ba0 - rt::unwind::try::try_fn::h67848939709837360
  17:     0x7f41d13eeb90 - rust_try_inner
  18:     0x7f41d13eeb80 - rust_try
  19:     0x7f41d1964e50 - thunk::F.Invoke<A, R>::invoke::h15720675569063176780
  20:     0x7f41d1375680 - sys::thread::thread_start::h2ac456e96ea03cedcJw
  21:     0x7f41cb77afe0 - start_thread
  22:     0x7f41d0f97859 - __clone
  23:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123

stack backtrace:
   1:     0x7f34d7a2f000 - sys::backtrace::write::h7e8ba1fc274cc36epRt
   2:     0x7f34d7a509e0 - failure::on_fail::h823798930ebe140a64z
   3:     0x7f34d79bf7b0 - rt::unwind::begin_unwind_inner::ha4a8df6010104da6ZJz
   4:     0x7f34d262a330 - rt::unwind::begin_unwind::h2017061421562134061
   5:     0x7f34d262a2c0 - diagnostic::SpanHandler::span_bug::h26a451e055cae458CYF
   6:     0x7f34d5b15810 - session::Session::span_bug::h64d8052083ced862Ebr
   7:     0x7f34d66ea6c0 - borrowck::build_borrowck_dataflow_data::h8c638256049ffbefKRe
   8:     0x7f34d66e7400 - borrowck::borrowck_fn::hdc6b07f7f72f47a26Oe
   9:     0x7f34d66ea570 - visit::walk_method_helper::h16178071186034281973
  10:     0x7f34d66e8310 - borrowck::borrowck_item::h22dfd39207f6713d3Ne
  11:     0x7f34d66e8880 - borrowck::check_crate::hd2a6930915fc4577UIe
  12:     0x7f34d7f812e0 - driver::phase_3_run_analysis_passes::h77110bff138a8fd0EEa
  13:     0x7f34d7f6ed70 - driver::compile_input::h8ec974b2bd4afe59Aba
  14:     0x7f34d80304d0 - run_compiler::h0e495a7c10e57aaae5b
  15:     0x7f34d802ec40 - thunk::F.Invoke<A, R>::invoke::h12226774702741163622
  16:     0x7f34d802dba0 - rt::unwind::try::try_fn::h67848939709837360
  17:     0x7f34d7ab7b90 - rust_try_inner
  18:     0x7f34d7ab7b80 - rust_try
  19:     0x7f34d802de50 - thunk::F.Invoke<A, R>::invoke::h15720675569063176780
  20:     0x7f34d7a3e680 - sys::thread::thread_start::h2ac456e96ea03cedcJw
  21:     0x7f34d1e43fe0 - start_thread
  22:     0x7f34d7660859 - __clone
  23:                0x0 - <unknown>

Could not compile `groove`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name groove --crate-type lib -g -C metadata=26cd79f71fc2edaa -C extra-filename=-26cd79f71fc2edaa --out-dir /home/andy/dev/rust-groove/target --emit=dep-info,link -L dependency=/home/andy/dev/rust-groove/target -L dependency=/home/andy/dev/rust-groove/target/deps` (status=101)
```

**Comment by Aatch** [comment]
While obviously stil a bug, it looks like the workaround would be to use `&*self.groove_file` instead. Note that this code should be producing an error anyway, just not an ICE, obviously.

**Comment by jdm** [comment]
Looks like a dup of #20801.
