### ISSUE TITLE
`fn main` in a comment in rustdoc breaks tests

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#21299]
$ cat confuse.md
    ```rust
    // pub fn mai
    ```
    $ rustdoc --test confuse.md
    
    running 1 test
    test _0 ... ok
    
    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
    
    $ sed -i 's/mai/main/' confuse.md
    $ rustdoc --test confuse.md
    
    running 1 test
    test _0 ... FAILED
    
    failures:
    
    ---- _0 stdout ----
            error: main function not found
    error: aborting due to previous error
    thread '_0' panicked at 'Box<Any>', /home/aidanhs/Desktop/rust/rust/src/libsyntax/diagnostic.rs:144
    
    
    
    failures:
        _0
    
    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
    
    thread '<unnamed>' panicked at 'Some tests failed', /home/aidanhs/Desktop/rust/rust/src/libtest/lib.rs:265
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/aidanhs/Desktop/rust/rust/src/libcore/result.rs:746

Per http://doc.rust-lang.org/rustdoc.html, "Given a code block, if it does not contain fn main, it is wrapped in fn main() { your_code }"

Can it not be "does not contain 'fn main (' outside of a comment"?

**Comment by aidanhs** [comment]
A more painful example is

    ```
    fn main_test () {}
    ```

Which of course gives the same error.

**Comment by estsauver** [comment]
Looks like it's just doing a .contains on the string looking for fn main. I'll add some tests and start on this.

**Comment by steveklabnik** [comment]
Traige: still an error

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by QuietMisdreavus** [comment]
For anyone that wants to tackle this, the offending line is [right here](https://github.com/rust-lang/rust/blob/e2b5d7e6b37208b241d5aacd77cb245b362c7ff5/src/librustdoc/test.rs#L340). Changing that `s.contains("fn main")` to some more-robust kind of scan would fix this.

**Comment by QuietMisdreavus** [comment]
Current status: Thanks to #44713 the exact example in the OP now doesn't break! But we'd like to make a "more complete" fix, likely by using libsyntax to properly parse tests and looking for a parsed function called "main" that way. It's probably not that cumbersome to set up if you can get a Parser rolling, but... i haven't worked with it myself, so i can't mentor that without tinkering on it myself. `>_>`

**Comment by rep-nop** [comment]
I'd like to take a stab at a proper fix for this, if that's okay!

**Comment by QuietMisdreavus** [comment]
@rep-nop Feel free! If you have any questions, don't be afraid to post them here or find us on IRC or Discord (there are `#rustdoc` channels on both).
