### ISSUE TITLE
ICE on casting closure from &mut _ to *mut _

### ISSUE THREAD

**Issue by suhr** [rust-lang/rust#21638]
Example:
```rust
type FnMoo = FnMut(i32) + 'static;

fn foo(mut c: Box<FnMoo>) -> (*mut FnMoo, Box<FnMoo>) {
    (&mut *c as *mut _, c)
}
```

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /var/tmp/portage/dev-lang/rust-9999-r3/work/rust-9999/src/libcore/option.rs:361
```

EDIT: changing `*mut _` to `*mut FnMoo` causes another ICE:
```
<anon>:4:6: 4:13 error: internal compiler error: expected object type
<anon>:4     (&mut *c as *mut FnMoo, c)
              ^~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /build/rust-git/src/rust/src/libsyntax/diagnostic.rs:130
```

**Comment by tamird** [comment]
No longer ICEs:
```rust
type FnMoo = FnMut(i32) + 'static;

fn foo(mut c: Box<FnMoo>) -> (*mut FnMoo, Box<FnMoo>) {
    (&mut *c as *mut _, c)
}

fn main() {
    // Add code here
}
```
compiles without error.
