### ISSUE TITLE
Failed to download rustc.exe

### ISSUE THREAD

**Issue by trippleflux** [rust-lang/rust#21743]
When doing make, curl failed to download with the following error : 
```
$ make
cfg: build triple x86_64-pc-windows-gnu
cfg: host triples x86_64-pc-windows-gnu
cfg: target triples x86_64-pc-windows-gnu
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for x86_64-pc-windows-gnu is x86_64
cfg: os for x86_64-pc-windows-gnu is pc-windows-gnu
cfg: good valgrind for x86_64-pc-windows-gnu is
cfg: using CC=gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: no lualatex found, deferring to xelatex
cfg: no xelatex found, deferring to pdflatex
cfg: no pdflatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
fetch: x86_64-pc-windows-gnu/stage0/bin/rustc.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
determined most recent snapshot: rust-stage0-2015-01-20-9006c3c-winnt-x86_64-36b6f239fe1264bceb4b8202e692b7d49947eebe.tar.bz2
Traceback (most recent call last):
  File "C:/msys64/home/Prodigy/rust/src/etc/get-snapshot.py", line 78, in <module>
    main(sys.argv)
  File "C:/msys64/home/Prodigy/rust/src/etc/get-snapshot.py", line 66, in main
    get_url_to_file(url, dl)
  File "C:/msys64/home/Prodigy/rust/src/etc/snapshot.py", line 155, in get_url_to_file
    raise Exception("failed to fetch url")
Exception: failed to fetch url
/home/Prodigy/rust/mk/stage0.mk:17: recipe for target 'x86_64-pc-windows-gnu/stage0/bin/rustc.exe' failed
make: *** [x86_64-pc-windows-gnu/stage0/bin/rustc.exe] Error 1
```

Adding -k option to disable cert verification on src/etc/snapshot.py still failed.

**Comment by nhowell** [comment]
Running into this issue today, as well, when trying to build on Windows 7 64-bit for my first time.

**Comment by nhowell** [comment]
I think I found a workaround to this, finally. The CA certificate files at /usr/ssl/certs/ were blank. Reinstalling the ca-certificates package seems to write the cert files and then I was able to run make successfully.

```
$ pacman -S ca-certificates
warning: ca-certificates-20141019-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) ca-certificates-20141019-1

Total Installed Size:  1.02 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
(1/1) reinstalling ca-certificates                 [######################] 100%
```
```
$ make
cfg: version 1.0.0-dev (b75b21cb9 2015-02-06 19:49:31 +0000)
cfg: build triple x86_64-pc-windows-gnu
cfg: host triples x86_64-pc-windows-gnu
cfg: target triples x86_64-pc-windows-gnu
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for x86_64-pc-windows-gnu is x86_64
cfg: os for x86_64-pc-windows-gnu is pc-windows-gnu
cfg: good valgrind for x86_64-pc-windows-gnu is
cfg: using CC=gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to
cfg: no lualatex found, deferring to xelatex
cfg: no xelatex found, deferring to pdflatex
cfg: no pdflatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
fetch: x86_64-pc-windows-gnu/stage0/bin/rustc.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.4M  100 17.4M    0     0  1378k      0  0:00:12  0:00:12 --:--:-- 2763k
determined most recent snapshot: rust-stage0-2015-02-04-ac134f7-winnt-x86_64-f1736f47de2a6fad1ff881e51c176f71db5dc2a5.tar.bz2
got download with ok hash
opening snapshot dl/rust-stage0-2015-02-04-ac134f7-winnt-x86_64-f1736f47de2a6fad1ff881e51c176f71db5dc2a5.tar.bz2
extracting rust-stage0/bin/rustc.exe
...
```

After researching all of this, I realized that the download links on the [msys2 website](http://msys2.github.io/) are out of date (I filed a [ticket](https://sourceforge.net/p/msys2/tickets/127/)). Instead, I recommend downloading the latest msys2 directly from the project [on SourceForge](https://sourceforge.net/projects/msys2/). They seem to have fixed this issue in the latest version.

**Comment by alexcrichton** [comment]
Yeah having run into this myself I've found that reinstalling `ca-certificates` fixes the problem, so closing as this seems taken care of.
