### ISSUE TITLE
llvm::CallGraphNode::~CallGraphNode(): Assertion `NumReferences == 0 && "Node deleted while references remain"' failed.

### ISSUE THREAD

**Issue by pczarn** [rust-lang/rust#22053]
```
rustc src/libstd/lib.rs --test -C opt-level=3 -C lto
```
```
rustc: /src/rust/src/llvm/include/llvm/Analysis/CallGraph.h:178: llvm::CallGraphNode::~CallGraphNode(): Assertion `NumReferences == 0 && "Node deleted while references remain"' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffef7ff700 (LWP 12933)]
0x00007ffff7049a97 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7049a97 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff704ae6a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff70428bd in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff7042972 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007ffff32b68f9 in llvm::CallGraph::removeFunctionFromModule(llvm::CallGraphNode*) ()
   from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_llvm-4e7c5e5c.so
#5  0x00007ffff26fa223 in llvm::Inliner::removeDeadFunctions(llvm::CallGraph&, bool) ()
   from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_llvm-4e7c5e5c.so
#6  0x00007ffff32bcf6d in (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) ()
   from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_llvm-4e7c5e5c.so
#7  0x00007ffff35ec278 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_llvm-4e7c5e5c.so
#8  0x00007ffff352a72e in LLVMRunPassManager () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_llvm-4e7c5e5c.so
#9  0x00007ffff63767d3 in back::write::execute_work_item::h6223141d1c9bb9d4b3c () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_trans-4e7c5e5c.so
#10 0x00007ffff636e862 in back::write::run_passes::h2452a1cfd887acdbiKc () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_trans-4e7c5e5c.so
#11 0x00007ffff7aefda4 in driver::phase_5_run_llvm_passes::ha0d656b3686872cfSPa ()
   from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-4e7c5e5c.so
#12 0x00007ffff7acb4f9 in driver::compile_input::h558636263da5590eCba () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-4e7c5e5c.so
#13 0x00007ffff7b9a244 in run_compiler::h0146e31ecbcd3b6d7ac () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-4e7c5e5c.so
#14 0x00007ffff7b976dd in thunk::F.Invoke$LT$A$C$$u20$R$GT$::invoke::h6194183685552048735 ()
   from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-4e7c5e5c.so
#15 0x00007ffff7b9649f in rt::unwind::try::try_fn::h1172606590764728260 () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-4e7c5e5c.so
#16 0x00007ffff7585ce9 in rust_try_inner () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/libstd-4e7c5e5c.so
#17 0x00007ffff7585cd6 in rust_try () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/libstd-4e7c5e5c.so
#18 0x00007ffff7b96aec in thunk::F.Invoke$LT$A$C$$u20$R$GT$::invoke::h11142474840251891045 ()
   from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/librustc_driver-4e7c5e5c.so
#19 0x00007ffff74fd746 in sys::thread::thread_start::hb8c2f89482757a06JvB () from /src/rust/x86_64-unknown-linux-gnu/stage2/lib/libstd-4e7c5e5c.so
#20 0x00007ffff18dc314 in start_thread () from /usr/lib/libpthread.so.0
#21 0x00007ffff70fe24d in clone () from /usr/lib/libc.so.6
```

**Comment by tamird** [comment]
Triage: lots of warnings, but no ICE. I think this is good to close. @steveklabnik?

```
$ rustc src/libstd/lib.rs --test -C opt-level=3 -C lto
<many warnings>
$ echo $?
0
```
