### ISSUE TITLE
building rgtk results in compiler panic

### ISSUE THREAD

**Issue by briankropf** [rust-lang/rust#22209]
I tried to set rgtk as a cargo dependency and build, but it fails with a compiler panic.
```
$ rustc --version --verbose
binary: rustc
commit-hash: a954663db66fc8efb1889beaf7bd1771ecbb9b21
commit-date: 2015-02-10 22:08:30 +0000
host: x86_64-pc-windows-gnu
release: 1.0.0-nightly
bash: $: command not found


$ RUST_BACKTRACE=1 cargo build
   Compiling rgtk v0.0.1 (https://github.com/jeremyletang/rgtk.git#cbb9c869)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: JoinPathsError { inner: JoinPathsError }', C:\bot\slave\nightly-dist-rustc-win-64\build\src\libcore\result.rs:743

stack backtrace:
   1:         0x69bf683b - sys::backtrace::write::h7d61c79ba3792dc3mBz
   2:         0x69c0d964 - rt::unwind::register::hd85e194c4c171711sjH
   3:         0x69b836ef - rt::unwind::begin_unwind_inner::h0e39b1f93ac3a89cKgH
   4:         0x69b83eb1 - rt::unwind::begin_unwind_fmt::h27757afb901c7a7fgfH
   5:         0x69c0d57a - rust_begin_unwind
   6:         0x69c23669 - panicking::panic_fmt::ha05377679e9c022fWqw
   7:         0x70b5ca2d - driver::collect_crate_metadata::h42ae6e6df5a04a12A3a
   8:         0x70b12036 - driver::phase_2_configure_and_expand::h184f6ffa4fc7a5eb1ta
   9:         0x70b01755 - driver::compile_input::h11fd438edb1bdc22Eba
  10:         0x70bcfd1c - run_compiler::hbd95a2d5a56f8d595bc
  11:         0x70bcd92b - run::h472f020b4c0a3240Ibc
  12:         0x70bcc63a - run::h472f020b4c0a3240Ibc
  13:         0x69c3b64c - rust_try
  14:         0x69c3b629 - rust_try
  15:         0x70bcccac - run::h472f020b4c0a3240Ibc
  16:         0x69bfe002 - sys::tcp::TcpListener::bind::h073fedc1fd3c0a2cO6C
  17:         0x779459ed - BaseThreadInitThunk

Could not compile `rgtk`.

To learn more, run the command again with --verbose.
```

**Comment by GuillaumeGomez** [comment]
I don't get what you tried to do... Set rgtk as cargo dependency ?

**Comment by briankropf** [comment]
yes, I set rgtk as a cargo dependency and got a compiler failure.  I also
checked out the package and tried to build it directly and received the
same failure message.

-brian

**Comment by mattico** [comment]
I got a similar error trying to compile librlibc with nightly-2015-02-14:
```
rustc  --target i686-unknown-linux-gnu -L rustlib-i686-unknown-linux-gnu -g --out-dir=bin --crate-type=rlib --crate-name=rlibc  rlibc/src/lib.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Expected("Expected label \"ty\" but found \"predicates\"")', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743

stack backtrace:
   1:     0x7f148295aa60 - sys::backtrace::write::h17046f691c944fd6wlB
   2:     0x7f1482983650 - failure::on_fail::hc6163ed550dbd15faOK
   3:     0x7f14828c9e10 - rt::unwind::begin_unwind_inner::hf466231ca0fbfbbdvsK
   4:     0x7f14828ca920 - rt::unwind::begin_unwind_fmt::h27d5ddac69c783ff1qK
   5:     0x7f14829834b0 - rust_begin_unwind
   6:     0x7f14829cdc50 - panicking::panic_fmt::h21faf6f60b06c77cSvw
   7:     0x7f14808e9710 - middle::astencode::reader..Decoder<'a>.rbml_decoder_decoder_helpers<'tcx>::read_type_scheme::hfbdcf75b538c3875okc
   8:     0x7f14809097a0 - middle::astencode::decode_side_tables::closure.75216
   9:     0x7f14807664f0 - middle::astencode::decode_inlined_item::h1be258f0a7eb2ea8Xqa
  10:     0x7f148158fb10 - trans::inline::instantiate_inline::closure.40387
  11:     0x7f1480b86680 - metadata::decoder::maybe_get_item_ast::h727a4975347bffd4JMk

  12:     0x7f14809a9880 - metadata::csearch::maybe_get_item_ast::h1ce89de91301f293Egn

  13:     0x7f148158e0a0 - trans::inline::instantiate_inline::h63b7ba8263f83a0c6nd
  14:     0x7f14815da020 - trans::callee::trans_fn_ref_with_substs::hf1f1aa6751244623DDg
  15:     0x7f14815ef280 - trans::meth::trans_method_callee::h117e2758751228d39bz
  16:     0x7f14815edbf0 - trans::callee::trans_call_inner::h15628364085236728556
  17:     0x7f14815f4dd0 - trans::expr::trans_rvalue_dps_unadjusted::h2a5828c13afa2678YZi
  18:     0x7f14815f41f0 - trans::expr::trans_unadjusted::h593717f67744b8f0tri
  19:     0x7f14815abe90 - trans::expr::trans::h5693990fd79e5cb8sJh
  20:     0x7f148160bcf0 - trans::expr::trans_unary::h848754451d9cd6fboIj
  21:     0x7f14815f41f0 - trans::expr::trans_unadjusted::h593717f67744b8f0tri
  22:     0x7f14815abe90 - trans::expr::trans::h5693990fd79e5cb8sJh
  23:     0x7f14815fa690 - trans::expr::trans_rvalue_stmt_unadjusted::hf05c8801823516406Ti
  24:     0x7f14815aad00 - trans::expr::trans_into::h8fd4f8a9bb5dccd8YFh
  25:     0x7f14815aa1a0 - trans::controlflow::trans_stmt_semi::hccf4a17010754a60Zde
  26:     0x7f14815ab310 - trans::controlflow::trans_block::hc124f866353eafbdQee
  27:     0x7f14815fa690 - trans::expr::trans_rvalue_stmt_unadjusted::hf05c8801823516406Ti
  28:     0x7f14815aad00 - trans::expr::trans_into::h8fd4f8a9bb5dccd8YFh
  29:     0x7f14815aa1a0 - trans::controlflow::trans_stmt_semi::hccf4a17010754a60Zde
  30:     0x7f14815ab310 - trans::controlflow::trans_block::hc124f866353eafbdQee
  31:     0x7f1481678a20 - trans::base::trans_closure::h6c5fc36e7a33e12eofu
  32:     0x7f1481596270 - trans::base::trans_fn::h76390f46f62f07cdEqu
  33:     0x7f14815a6eb0 - trans::foreign::trans_rust_fn_with_foreign_abi::h2fb69aa838c4cd32oCC
  34:     0x7f1481591410 - trans::base::trans_item::ha4ea07b91896bde9tPu
  35:     0x7f14816800f0 - trans::base::trans_crate::hc435c9fdb6f30ff4NMv
  36:     0x7f1482fa5250 - driver::phase_4_translate_to_llvm::hb02bd998f41b29a0wPa
  37:     0x7f1482f7e170 - driver::compile_input::h91ff1ed16e22d05cEba
  38:     0x7f1483051ea0 - run_compiler::h9c581f85e29a6b265bc
  39:     0x7f1483050500 - thunk::F.Invoke<A, R>::invoke::h5155567596601403298
  40:     0x7f148304f3f0 - rt::unwind::try::try_fn::h5629523784837248188
  41:     0x7f14829eff20 - rust_try_inner
  42:     0x7f14829eff10 - rust_try
  43:     0x7f148304f6a0 - thunk::F.Invoke<A, R>::invoke::h7807062886684583533
  44:     0x7f148296f190 - sys::thread::thread_start::h57c9c75c73c301cbfVF
  45:     0x7f147c8eefe0 - start_thread
  46:     0x7f1482540859 - __clone
  47:                0x0 - <unknown>

Makefile:82: recipe for target 'bin/librlibc.rlib' failed
```

I don't think that this error occured with the previous nightly (2015-2-12 ?)

**Comment by tamird** [comment]
https://github.com/jeremyletang/rgtk @ cbb9c869 no longer compiles. Perhaps @jeremyletang can help specify the issue?

**Comment by GuillaumeGomez** [comment]
As said on the rgtk repo, it is now deprecated. Go to rust-gnome/gtk repo and then try again.

**Comment by tamird** [comment]
@steveklabnik I believe this won't be actionable since it's too stale.
