### ISSUE TITLE
Internal compiler error: panicked at 'parse_object_lifetime_default: bad input'

### ISSUE THREAD

**Issue by ChCronstrom** [rust-lang/rust#22508]
I can reproduce an internal compiler error in Nightly.

Command line: `rustc --target i686-unknown-linux-gnu --crate-type lib --emit obj -L .`

#### Stack trace:
```
thread 'rustc' panicked at 'parse_object_lifetime_default: bad input', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/metadata/tydecode.rs:852

stack backtrace:
   1:     0x7f3cb3871b70 - sys::backtrace::write::h00fa41ac57b8527bfmB
   2:     0x7f3cb389a4f0 - panicking::on_panic::he60a0e1a593653a5TOK
   3:     0x7f3cb37e1960 - rt::unwind::begin_unwind_inner::h3bcb1406fb794dc7etK
   4:     0x7f3cb1862260 - rt::unwind::begin_unwind::h10130892067423310058
   5:     0x7f3cb1c664c0 - metadata::decoder::doc_generics::h5235658332e7e7c3Zum
   6:     0x7f3cb1c6a6a0 - metadata::decoder::get_type::h1e8e26a28856ed88c8k
   7:     0x7f3cb1ac0710 - middle::ty::lookup_item_type::ha21c5db5c4b15aabB09
   8:     0x7f3cb306b2e0 - coherence::CoherenceChecker<'a, 'tcx>::check::hedd95f38d546b908Crz
   9:     0x7f3cb307f650 - check_crate::closure.35490
  10:     0x7f3cb307b660 - check_crate::h39be2e1dade157debNB
  11:     0x7f3cb3ed0010 - driver::phase_3_run_analysis_passes::hd653590d3e2d14feSGa
  12:     0x7f3cb3eb6070 - driver::compile_input::h5ed7326e88136f7fEba
  13:     0x7f3cb3f86290 - run_compiler::h12bed89c4496bc43Bbc
  14:     0x7f3cb3f847f0 - thunk::F.Invoke<A, R>::invoke::h13875370646425574429
  15:     0x7f3cb3f836d0 - rt::unwind::try::try_fn::h5086316350382225766
  16:     0x7f3cb3907050 - rust_try_inner
  17:     0x7f3cb3907040 - rust_try
  18:     0x7f3cb3f83980 - thunk::F.Invoke<A, R>::invoke::h12662570625570879817
  19:     0x7f3cb3885e80 - sys::thread::thread_start::h197b42630d52606aYVF
  20:     0x7f3cad9930c0 - start_thread
  21:     0x7f3cb345afd9 - __clone
  22:                0x0 - <unknown>
```

#### Features used:
```
#![feature(no_std)]
#![feature(core)]
#![feature(lang_items)]
```
I have cross-compiled a `libcore.rlib ` for target, and by now that library will be significantly out of sync ot the Rust compiler itself.

#### Version information:
```
rustc 1.0.0-nightly (81bce5290 2015-02-16) (built 2015-02-17)
binary: rustc
commit-hash: 81bce5290ff55b9a2eddd83d31b0778180904d7f
commit-date: 2015-02-16
build-date: 2015-02-17
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

I have the Rust git repo, so I will try to run a bisection with older versions if I have time.

**Comment by ChCronstrom** [comment]
I have run a bisection search through the nightlies, and this ICE first appears on 13 February:

```
rustc 1.0.0-nightly (ba2efe96a 2015-02-13 02:09:15 +0000)
binary: rustc
commit-hash: ba2efe96aeada34c1e2dc267a1a35948bdda91f8
commit-date: 2015-02-13 02:09:15 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

In this version, the error is a bit different though, and looks like it might be related to #14748
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Expected("Expected label \"ty\" but found \"predicates\"")', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743

stack backtrace:
   1:     0x7fa2e9c85750 - sys::backtrace::write::h49b06c4e5fa1765dZTA
   2:     0x7fa2e9caa3e0 - failure::on_fail::h128a61ca90111ec2JFJ
   3:     0x7fa2e9c02350 - rt::unwind::begin_unwind_inner::h142cc6242e7988934jJ
   4:     0x7fa2e9c02e60 - rt::unwind::begin_unwind_fmt::h9f6d3c7c640c0421AiJ
   5:     0x7fa2e9caa240 - rust_begin_unwind
   6:     0x7fa2e9cf47a0 - panicking::panic_fmt::h21faf6f60b06c77cSvw
   7:     0x7fa2e7c40160 - middle::astencode::reader..Decoder<'a>.rbml_decoder_decoder_helpers<'tcx>::read_type_scheme::h8e3dba270454c7e2okc
   8:     0x7fa2e7c601f0 - middle::astencode::decode_side_tables::closure.75145
   9:     0x7fa2e7ac04e0 - middle::astencode::decode_inlined_item::h068d532261c60680Xqa
  10:     0x7fa2e88d8df0 - trans::inline::instantiate_inline::closure.40362
  11:     0x7fa2e7ed28c0 - metadata::decoder::maybe_get_item_ast::hbd54e15ceac79354JMk
  12:     0x7fa2e7cfc770 - metadata::csearch::maybe_get_item_ast::h22d6fe7c2dd8b6ffEgn
  13:     0x7fa2e88d7380 - trans::inline::instantiate_inline::h08b37fe16127fdf76nd
  14:     0x7fa2e8922120 - trans::callee::trans_fn_ref_with_substs::h4a9e9231881dd945DDg
  15:     0x7fa2e8936ec0 - trans::meth::trans_method_callee::h96316b4b826569cf9bz
  16:     0x7fa2e8935a10 - trans::callee::trans_call_inner::h10290956782341029294
  17:     0x7fa2e893c920 - trans::expr::trans_rvalue_dps_unadjusted::he612c9f9091d08b2YZi
  18:     0x7fa2e893bd40 - trans::expr::trans_unadjusted::h0a35d1e10b03cd27tri
  19:     0x7fa2e88f4a20 - trans::expr::trans::h353ab30c52c622dbsJh
  20:     0x7fa2e8953470 - trans::expr::trans_unary::haee3f4e6a826b679oIj
  21:     0x7fa2e893bd40 - trans::expr::trans_unadjusted::h0a35d1e10b03cd27tri
  22:     0x7fa2e88f4a20 - trans::expr::trans::h353ab30c52c622dbsJh
  23:     0x7fa2e8942130 - trans::expr::trans_rvalue_stmt_unadjusted::hdc1fcb88faa3f8006Ti
  24:     0x7fa2e88f3890 - trans::expr::trans_into::h9f3ed4622867868fYFh
  25:     0x7fa2e88f2d30 - trans::controlflow::trans_stmt_semi::h18d9e1f6ee095b69Zde
  26:     0x7fa2e88f3ea0 - trans::controlflow::trans_block::h7a9017bd6dd61f5cQee
  27:     0x7fa2e8942130 - trans::expr::trans_rvalue_stmt_unadjusted::hdc1fcb88faa3f8006Ti
  28:     0x7fa2e88f3890 - trans::expr::trans_into::h9f3ed4622867868fYFh
  29:     0x7fa2e88f2d30 - trans::controlflow::trans_stmt_semi::h18d9e1f6ee095b69Zde
  30:     0x7fa2e88f3ea0 - trans::controlflow::trans_block::h7a9017bd6dd61f5cQee
  31:     0x7fa2e89bf180 - trans::base::trans_closure::hbc1e838a851464b4ofu
  32:     0x7fa2e88df550 - trans::base::trans_fn::h89cdd4576220c5b2Equ
  33:     0x7fa2e88da6f0 - trans::base::trans_item::h821a1d8c2f3bd0d2tPu
  34:     0x7fa2e89c3320 - trans::base::trans_mod::h004afd65bfc8913foVu
  35:     0x7fa2e88da6f0 - trans::base::trans_item::h821a1d8c2f3bd0d2tPu
  36:     0x7fa2e89c6730 - trans::base::trans_crate::hbc3532ac87923bc6NMv
  37:     0x7fa2ea2b8280 - driver::phase_4_translate_to_llvm::he2aa9fc36a75551bwPa
  38:     0x7fa2ea291190 - driver::compile_input::h2199f07dd067a038Eba
  39:     0x7fa2ea362360 - run_compiler::h7807f450e003c3f65bc
  40:     0x7fa2ea3609c0 - thunk::F.Invoke<A, R>::invoke::h10965480741658827823
  41:     0x7fa2ea35f8b0 - rt::unwind::try::try_fn::h9927690981525442750
  42:     0x7fa2e9d16a70 - rust_try_inner
  43:     0x7fa2e9d16a60 - rust_try
  44:     0x7fa2ea35fb60 - thunk::F.Invoke<A, R>::invoke::h17448596242061042531
  45:     0x7fa2e9c96050 - sys::thread::thread_start::h76415ad3898ce7eaaOE
  46:     0x7fa2e3c610c0 - start_thread
  47:     0x7fa2e9879fd9 - __clone
  48:                0x0 - <unknown>
```

Any suggestions on other diagnostics?

**Comment by tamird** [comment]
This is probably another stale metadata issue. There's not much that can be done unfortunately.

Is this resolved by recompiling your libcore? If so, this is probably good to close :(

**Comment by alexcrichton** [comment]
agreed that it's probably a stale metadata issue, but feel free to reopen if it reproduces!
