### ISSUE TITLE
rust-lldb pretty-printing: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#22656]
This file:

```rust
fn main() {
    let v = vec![1,2,3];
}
```

compiled with `rustc -g debug.rs`, then debugged with `rust-lldb debug`. Trying to print a value as `p v` yields:

```python
Traceback (most recent call last):
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 19, in print_val
    return print_struct_val(val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 44, in print_struct_val
    return print_struct_val_starting_from(0, val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 105, in print_struct_val_starting_from
    body = separator.join([render_child(idx) for idx in range(field_start_index, num_children)])
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 103, in render_child
    return this + print_val(field_val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 19, in print_val
    return print_struct_val(val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 44, in print_struct_val
    return print_struct_val_starting_from(0, val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 105, in print_struct_val_starting_from
    body = separator.join([render_child(idx) for idx in range(field_start_index, num_children)])
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 103, in render_child
    return this + print_val(field_val, internal_dict)
TypeError: cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 19, in print_val
    return print_struct_val(val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 44, in print_struct_val
    return print_struct_val_starting_from(0, val, internal_dict)
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 105, in print_struct_val_starting_from
    body = separator.join([render_child(idx) for idx in range(field_start_index, num_children)])
  File "/rust/x86_64-apple-darwin/stage2/lib/rustlib/etc/lldb_rust_formatters.py", line 103, in render_child
    return this + print_val(field_val, internal_dict)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

```
$ lldb --version
lldb-320.4.152
$ rustc --version
rustc 1.0.0-dev (2b01a37ec 2015-02-21) (built 2015-02-21)
```

**Comment by alexcrichton** [comment]
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
Interesting. I thought we had a test case for simple vectors. Anyway, I'm on it.
