### ISSUE TITLE
Compiler crashes on malformed macro

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#23389]
A simple malformed macro makes the compiler crash. 

Code:
```rust
macro_rules! code_block {
    $c:block => $c
}
```
Playpen error:
```
<anon>:1:1: 3:2 error: internal compiler error: wrong-structured lhs for follow check (didn't find a TtDelimited or TtSequence)
<anon>:1 macro_rules! code_block {
<anon>:2     $c:block => $c
<anon>:3 }
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130
```
Playpen: http://is.gd/COoZe7

**Comment by vi** [comment]
Another case:
`macro_rules! q { ($($w:ident,$t:$ident)*) => {}}  q!();`

Playpen: http://is.gd/CYZPiW

**Comment by ehiggs** [comment]
I had a crash in a bad macro which hits the same bug as vl. Note that his/her error has the following which is a different stack trace:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Cannot fill in a NT', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ext/tt/macro_parser.rs:236


playpen: application terminated with error code 101
```

I'm on the latest beta; not nightly.

**Comment by Nashenas88** [comment]
@ehiggs I think you and I are getting a different panic. I'm going to open a new bug now since the panic is in a different location in the code.
