### ISSUE TITLE
ICE on doc command

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#23754]
Here's the ICE:

```Shell
> cargo doc
```

```Rust
<stdin>:1:1: 1:2 [31merror: (B[m[1munknown start of token: \\(B[m
<stdin>:1 \Gamma^*(x) = \Gamma(x)/(\sqrt{2\pi} x^{(x-1/2)} \exp(-x))
          [31m^(B[m
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:93
stack backtrace:
   1:     0x7fe5b31caae9 - sys::backtrace::write::h76aa9c42f0d96a63zgD
   2:     0x7fe5b31f29b2 - panicking::on_panic::h96f6ae333e8ace3fRwJ
   3:     0x7fe5b3127223 - rt::unwind::begin_unwind_inner::hf943645b7eef6d43ycJ
   4:     0x7fe5b0a0389d - rt::unwind::begin_unwind::h18129537798709887526
   5:     0x7fe5b09c0696 - diagnostic::SpanHandler::span_fatal::h637298a145d3ed72P4A
   6:     0x7fe5b0a5ddaf - parse::lexer::StringReader<'a>::fatal_span::h0618e30d15af0051aKK
   7:     0x7fe5b0a5fe2c - parse::lexer::StringReader<'a>::fatal_span_char::h42be953baf774c43uLK
   8:     0x7fe5b0a60c4d - parse::lexer::StringReader<'a>::next_token_inner::h4a4cc4ee99d8b928KFL
   9:     0x7fe5b0a5ce38 - parse::lexer::StringReader<'a>::advance_token::h6148dd65df9cf860sOK
  10:     0x7fe5b0a5fb97 - parse::lexer::StringReader<'a>::new::h340fbdb72ec4d693uJK
  11:     0x7fe5b389a792 - html::highlight::highlight::h0bfc5b6896276e44oxj
  12:     0x7fe5b38b00b5 - html::markdown::render::block::h236ac973f8f2e1332mm
  13:     0x7fe5b39c0a4e - parse_block
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:1704
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:2388
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:2354
  14:     0x7fe5b39c2b76 - hoedown_document_render
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:2802
  15:     0x7fe5b38aee3f - html::markdown::render::h1cf9ca03469e4f0eMmm
  16:     0x7fe5b38b6da0 - html::markdown::Markdown<'a>.fmt..Display::fmt::h75756a28c762145aVOm
  17:     0x7fe5b32597a0 - fmt::write::hccc16603bacaa90dmbL
  18:     0x7fe5b3253771 - fmt::Formatter<'a>::write_fmt::he8f76fd270be4445OrL
  19:     0x7fe5b38eff6d - html::render::document::hf9202815e14c0324Gfp
  20:     0x7fe5b38eb3f1 - html::render::Item<'a>.fmt..Display::fmt::h43cf3a3ea8339594rVo
  21:     0x7fe5b3259701 - fmt::write::hccc16603bacaa90dmbL
  22:     0x7fe5b38d9d68 - io::Write::write_fmt::h10171908331439198518
  23:     0x7fe5b38e81c3 - html::render::Context::item::render::h8f32d60032f8674bmzo
  24:     0x7fe5b38d5428 - html::render::Context::krate::h2b4f6e71f3def8e9Xto
  25:     0x7fe5b38bfd03 - html::render::run::h2152d5221abd3f60i8m
  26:     0x7fe5b392ee7f - main_args::h53e8087100407efbQ3t
  27:     0x7fe5b392a479 - thunk::F.Invoke<A, R>::invoke::h3507444692421000353
  28:     0x7fe5b3929169 - rt::unwind::try::try_fn::h5156331870926964537
  29:     0x7fe5b326c5d8 - rust_try_inner
  30:     0x7fe5b326c5c5 - rust_try
  31:     0x7fe5b392949b - thunk::F.Invoke<A, R>::invoke::h17550050276384416299
  32:     0x7fe5b31df238 - sys::thread::create::thread_start::h2a0ece1f2186c095k6H
  33:     0x7fe5ad4afe99 - start_thread
  34:     0x7fe5b2d8a4bc - <unknown>
thread '<main>' panicked at 'child thread None panicked', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:726
stack backtrace:
   1:     0x7fe5b31caae9 - sys::backtrace::write::h76aa9c42f0d96a63zgD
   2:     0x7fe5b31f29b2 - panicking::on_panic::h96f6ae333e8ace3fRwJ
   3:     0x7fe5b3127223 - rt::unwind::begin_unwind_inner::hf943645b7eef6d43ycJ
   4:     0x7fe5b31275e1 - rt::unwind::begin_unwind_fmt::h1bdcdc9d116514b79aJ
   5:     0x7fe5b3928bf5 - main::he9ec8d0f8c3ce1afEZt
   6:     0x7fe5b326c5d8 - rust_try_inner
   7:     0x7fe5b326c5c5 - rust_try
   8:     0x7fe5b31f44ea - rt::lang_start::h01933925518bf540krJ
   9:     0x7fe5b2cb976c - __libc_start_main
  10:     0x7fe5b3fa8738 - <unknown>
```

You can have all this from [here](https://github.com/GuillaumeGomez/rust-GSL/pull/8).

**Comment by apasel422** [comment]
@GuillaumeGomez Do you have more information on the code that causes this?

**Comment by GuillaumeGomez** [comment]
Code is kinda old but it *seems* to build just fine.

**Comment by apasel422** [comment]
So can this be closed?

**Comment by GuillaumeGomez** [comment]
Absolutely.
