### ISSUE TITLE
ICE on 'let x = [];'

### ISSUE THREAD

**Issue by rhencke** [rust-lang/rust#23840]
When compiling:
```rust
fn main() {
    let x = [];
}
```

rustc dies with:
```
thread 'rustc' panicked at 'Box<Any>', /Users/roberthencke/src/rust/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:        0x107814644 - sys::backtrace::write::hc9fdfba4d7b15a9dYAD
   2:        0x10783f798 - panicking::on_panic::h8bb366db13a7bf028qJ
   3:        0x10775c71e - rt::unwind::begin_unwind_inner::h1d0bef9a44801ec8i9I
   4:        0x106f56ade - rt::unwind::begin_unwind::h12157501815572839086
   5:        0x106f56a8b - diagnostic::SpanHandler::span_bug::hfafb793ceb7823c8taB
   6:        0x10472bc9c - session::Session::span_bug::he70fb12f8935aafaPPn
   7:        0x103eb31eb - check::regionck::visit_expr::h4c8800f0a1106c751Hd
   8:        0x103eb3b51 - check::regionck::visit_local::h8f9bb4823989e3586Ed
   9:        0x103eadff9 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::hc1a37803b1d3181eekd
  10:        0x103f3ff96 - check::check_bare_fn::hb32b581dc74a9b093nn
  11:        0x103f37fcb - check::check_item::hd9f7940ef6a90ee9OGn
  12:        0x1040115b6 - check_crate::closure.35998
  13:        0x10400c47a - check_crate::hcda5f3cefbfd5d5fOmC
  14:        0x103d49787 - driver::phase_3_run_analysis_passes::h026e769b2b844eb5rGa
  15:        0x103d2f7c7 - driver::compile_input::hb475e8fd7969563dRba
  16:        0x103de9513 - run_compiler::h6333b890b54b4387s2b
  17:        0x103de70a5 - thunk::F.Invoke<A, R>::invoke::h5287984335417981805
  18:        0x103de6467 - rt::unwind::try::try_fn::h14175969919979542003
  19:        0x1078c8648 - rust_try_inner
  20:        0x1078c8635 - rust_try
  21:        0x103de6805 - thunk::F.Invoke<A, R>::invoke::h18234926616775157777
  22:        0x10782a72d - sys::thread::create::thread_start::h3ba002124437c3be86H
  23:     0x7fff8ef22267 - _pthread_body
  24:     0x7fff8ef221e4 - _pthread_start
```

rustc --version --verbose gives:
```
rustc 1.0.0-dev (1501f33e7 2015-03-26) (built 2015-03-26)
binary: rustc
commit-hash: 1501f33e76f6f9621aa08fb0cbbc5f85a5ac7f0f
commit-date: 2015-03-26
build-date: 2015-03-26
host: x86_64-apple-darwin
release: 1.0.0-dev
```

**Comment by ebfull** [comment]
Same ICE as #23827

**Comment by rprichard** [comment]
There's an ICE error before the stack trace:
```
test.rs:2:13: 2:15 error: internal compiler error: cat_expr Errd
test.rs:2     let x = [];
                      ^~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130
```
I think this issue is a duplicate of #22897.

**Comment by rhencke** [comment]
@rprichard, I think you're correct, it is a duplicate.  The stack traces are the same.  I will close this one.  Thank you.
