### ISSUE TITLE
ICE: Failed to unify `Obligation(...)` and `ProjectionPredicate(...)` in projection

### ISSUE THREAD

**Issue by stevenblenkinsop** [rust-lang/rust#24204]
Came across this error (ab)using the type system in the following way:

    #![allow(dead_code)]
    
    trait MultiDispatch<T> {
        type O;
    }
    
    trait Trait {
        type A: MultiDispatch<Self::B, O = Self>;
        type B;
        
        fn new<U>(u: U) -> <Self::A as MultiDispatch<U>>::O where Self::A : MultiDispatch<U>;
    }
    
    fn test<T: Trait<B=i32>>(b: i32) -> T where T::A : MultiDispatch<i32> { T::new(b) } 
    
    fn main() {}

This created the following ICE:
```
<anon>:14:73: 14:79 error: internal compiler error: Failed to unify `Obligation(predicate=<<T as Trait>::A as MultiDispatch<_>>::O,depth=0)` and `ProjectionPredicate(<<T as Trait>::A as MultiDispatch<<T as Trait>::B>>::O, T)` in projection: expected associated type, found i32
<anon>:14 fn test<T: Trait<B=i32>>(b: i32) -> T where T::A : MultiDispatch<i32> { T::new(b) } 
                                                                                  ^~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130
```

Note that changing `test` to:

    fn test<T: Trait<B=i32>>(b: i32) -> T where T::A : MultiDispatch<i32, O = T> { T::new(b) } 

so that it matches the bound on `Trait::A` [fixes the issue](http://is.gd/4nWMZs). This makes the whole `where` clause appear redundant, but removing it [causes an error](http://is.gd/SpPGRr), apparently ignoring the bound expressed on `Trait::A` (though clearly not completely, since the bound on `Trait::A` is still able to cause the original ICE). This is probably an instance of issue #24159.

**Comment by stevenblenkinsop** [comment]
With backtrace:

```
test.rs:14:73: 14:79 error: internal compiler error: Failed to unify `Obligation(predicate=<<T as Trait>::A as MultiDispatch<_>>::O,depth=0)` and `ProjectionPredicate(<<T as Trait>::A as MultiDispatch<<T as Trait>::B>>::O, T)` in projection: expected associated type, found i32
test.rs:14 fn test<T: Trait<B=i32>>(b: i32) -> T where T::A : MultiDispatch<i32> { T::new(b) } 
                                                                                   ^~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:        0x104a09f77 - sys::backtrace::write::h799ab135045ca9ca1LC
   2:        0x104a37e4d - panicking::on_panic::h9502e488a92fc8bcHAI
   3:        0x10495c2de - rt::unwind::begin_unwind_inner::hf0537788ee16eadbiiI
   4:        0x1041335ae - rt::unwind::begin_unwind::h447731439410619827
   5:        0x10413355b - diagnostic::SpanHandler::span_bug::h3f51c1d819f22bcfjnB
   6:        0x101c2ba43 - middle::traits::project::confirm_param_env_candidate::hf852dc0f5b320b18N1P
   7:        0x101c23962 - middle::traits::project::project_type::h7ca468ea33bc79f1AwP
   8:        0x101c1f367 - middle::traits::project::opt_normalize_projection_type::h766518f8b1310230cpP
   9:        0x101c083bf - middle::traits::project::normalize_projection_type::h734766f7a9915c990nP
  10:        0x101bf59f0 - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::h3729e5ef2601270eElP
  11:        0x101bf509f - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::h3729e5ef2601270eElP
  12:        0x100f953a8 - check::FnCtxt<'a, 'tcx>::normalize_associated_types_in::h16934591160211678581
  13:        0x100f94d2e - check::FnCtxt<'a, 'tcx>::instantiate_type_scheme::h5994741691476743977
  14:        0x100fa3b96 - check::instantiate_path::h72ec382ec88529f7HQs
  15:        0x1010cb36a - check::check_expr_with_unifier::h6698900367440735538
  16:        0x101053279 - check::callee::check_call::hf15968ef2ca0f38apcm
  17:        0x1010ab233 - check::check_expr_with_unifier::h7970691808293538245
  18:        0x1010759db - check::check_block_with_expected::h60bff5b1f9d55793fps
  19:        0x101051e05 - check::check_fn::h410d0ffafb47f675l1n
  20:        0x10107032e - check::check_bare_fn::h05c77be534ada2cfUQn
  21:        0x101069ee2 - check::check_item::h9d89bedf29e4fe82F9n
  22:        0x101146676 - check_crate::closure.36302
  23:        0x101140ae7 - check_crate::h09aa7856a322fd44bwC
  24:        0x100e61355 - driver::phase_3_run_analysis_passes::h1af60e7c926ca39dgGa
  25:        0x100e45a85 - driver::compile_input::h27cf4320fd56e5cbQba
  26:        0x100f03a15 - run_compiler::h93c68a2a3c26052bV4b
  27:        0x100f011e2 - boxed::F.FnBox<A>::call_box::h4498816167135712709
  28:        0x100f006d7 - rt::unwind::try::try_fn::h2387014819904265058
  29:        0x104ac1ea8 - rust_try_inner
  30:        0x104ac1e95 - rust_try
  31:        0x100f009ca - boxed::F.FnBox<A>::call_box::h4850138824497903476
  32:        0x104a2137d - sys::thread::create::thread_start::h42d6d904fce5365aihH
  33:     0x7fff91f75898 - _pthread_body
  34:     0x7fff91f75729 - _pthread_start
```

**Comment by m4rw3r** [comment]
I ran into this bug on both current stable `rustc 1.4.0 (8ab8581f6 2015-10-27)` and a nightly `rustc 1.6.0-nightly (2f95de3b3 2015-12-01)`.

Here is a backtrace for current stable (`rustc 1.4.0 (8ab8581f6 2015-10-27)`) using the above example code:
```
test2.rs:14:73: 14:79 error: internal compiler error: Failed to unify `Obligation(predicate=ProjectionTy { trait_ref: <<T as Trait>::A as MultiDispatch<_>>, item_name: O(64) },depth=0)` and `ProjectionPredicate(ProjectionTy { trait_ref: <<T as Trait>::A as MultiDispatch<<T as Trait>::B>>, item_name: O(64) }, T)` in projection: expected associated type, found i32
test2.rs:14 fn test<T: Trait<B=i32>>(b: i32) -> T where T::A : MultiDispatch<i32> { T::new(b) }
                                                                                    ^~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/diagnostic.rs:176

stack backtrace:
   1:        0x108accda0 - sys::backtrace::tracing::imp::write::he715e18a60aa49cbY7s
   2:        0x108aca149 - panicking::on_panic::hf85837ce31d02cf7wWw
   3:        0x108a936d2 - sys_common::unwind::begin_unwind_inner::h263a8f3a93eff05evas
   4:        0x1067a4d3a - sys_common::unwind::begin_unwind::h2734773420310895812
   5:        0x1067a4d02 - diagnostic::SpanHandler::span_bug::h2744963912bf7f266NA
   6:        0x105d33c98 - middle::traits::project::confirm_param_env_candidate::hf7d5c75e925102c3TzT
   7:        0x105d2ea6b - middle::traits::project::opt_normalize_projection_type::h4b8003c9d28f5606wNS
   8:        0x105d20870 - middle::traits::project::normalize_projection_type::h6ba4741429d69d6ckMS
   9:        0x105cc358a - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::hc3ec51c79dbc98331JS
  10:        0x105cc2f54 - middle::ty::fold::TypeFolder::fold_binder::h15745587145886015118
  11:        0x105cc37f4 - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::hc3ec51c79dbc98331JS
  12:        0x1055eea24 - middle::traits::project::normalize::h8576955180410799035
  13:        0x1055ee26d - check::assoc::normalize_associated_types_in::h2297513543514642305
  14:        0x1055fcd9c - check::instantiate_path::h52b78dac89e9bd79Vzu
  15:        0x1056ee184 - check::check_expr_with_unifier::h16728426817096888307
  16:        0x105685f53 - check::callee::check_call::h579204e755e32a83qVm
  17:        0x1056d7f52 - check::check_expr_with_unifier::h838939668687904838
  18:        0x1056af604 - check::check_block_with_expected::h7c883143007fc089kau
  19:        0x105685720 - check::check_fn::h9cecf86a589f5df33Jp
  20:        0x1056a62fc - check::check_bare_fn::h0cc5198eac888ed5Czp
  21:        0x1056a3c86 - check::check_item_body::hbe1715c86b39f19aW0p
  22:        0x10575c761 - check_crate::h7049eea75dfbb8929CE
  23:        0x104f0bd27 - driver::phase_3_run_analysis_passes::closure.21575
  24:        0x104eef3fa - middle::ty::context::ctxt<'tcx>::create_and_enter::h13460673800781906500
  25:        0x104eeade3 - driver::phase_3_run_analysis_passes::h1322645905457543974
  26:        0x104ecb3b6 - driver::compile_input::hb59f474fec28f4580ba
  27:        0x105028170 - run_compiler::hdc2ad537dbabfa44qqc
  28:        0x1050259cb - boxed::F.FnBox<A>::call_box::h6015891024191261117
  29:        0x1050252d2 - sys_common::unwind::try::try_fn::h8012090198820404000
  30:        0x108ac9a28 - __rust_try
  31:        0x108abe460 - sys_common::unwind::try::inner_try::h93da745d827b7cb5T6r
  32:        0x105025482 - boxed::F.FnBox<A>::call_box::h6138197769578501793
  33:        0x108ad22cd - sys::thread::Thread::new::thread_start::h770a3938c0de9490puw
  34:     0x7fff93838059 - _pthread_body
  35:     0x7fff93837fd6 - _pthread_start
```

**Comment by eddyb** [comment]
Current stable (`rustc 1.10.0 (cfcb716cf 2016-07-03)`) requires `trait Trait: Sized {...}` but even then a proper error is produced instead of an ICE:
```
error: type mismatch resolving `<<T as Trait>::A as MultiDispatch<i32>>::O == T`:
 expected associated type,
    found type parameter [--explain E0271]
  --> <anon>:14:1
   |>
14 |> fn test<T: Trait<B=i32>>(b: i32) -> T where T::A : MultiDispatch<i32> { T::new(b) }
   |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by `Trait`
```
