### ISSUE TITLE
ICE when run-pass test match-arm-statics is compiled with debuginfo

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#24956]
Compiling the test match-arm-statics with debug information (`rustc -g src/test/run-pass/match-arm-statics.rs`) causes an ICE:

```
../src/test/run-pass/match-arm-statics.rs:135:9: 135:19 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 48, node: ExprLit(Spanned { node: LitBool(false), span: Span { lo: BytePos(868), hi: BytePos(873), expn_id: ExpnId(4294967295) } }), span: Span { lo: BytePos(868), hi: BytePos(873), expn_id: ExpnId(4294967295) } })
../src/test/run-pass/match-arm-statics.rs:135         STATIC_FOO => 3,
                                                      ^~~~~~~~~~
<std macros>:1:1: 9:39 note: in expansion of assert_eq!
../src/test/run-pass/match-arm-statics.rs:132:5: 141:11 note: expansion site
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/ariel/Rust/source.arielb1/src/libsyntax/diagnostic.rs:170

stack backtrace:
   1:     0x7f4bfdd55ecf - sys::backtrace::write::h559186d920312a32qYr
                        at /home/ariel/Rust/source.arielb1/src/libstd/sys/unix/backtrace.rs:158
   2:     0x7f4bfdd7ed72 - panicking::on_panic::h8564e17e4133b3e8low
                        at /home/ariel/Rust/source.arielb1/src/libstd/panicking.rs:47
   3:     0x7f4bfdcc141e - rt::unwind::begin_unwind_inner::hfbbfddab1bfb087av3v
                        at /home/ariel/Rust/source.arielb1/src/libstd/rt/unwind.rs:569
   4:     0x7f4bf9b41367 - rt::unwind::begin_unwind::h7619580709946955206
                        at /home/ariel/Rust/source.arielb1/src/libstd/rt/unwind.rs:522
   5:     0x7f4bf9b412fe - diagnostic::SpanHandler::span_bug::hb39c3fcb069eb3d0cFB
                        at /home/ariel/Rust/source.arielb1/build/<std macros>:3
   6:     0x7f4bfa7fee68 - session::Session::span_bug::hddd01ab440b6016b3yq
                        at /home/ariel/Rust/source.arielb1/src/librustc/session/mod.rs:190
   7:     0x7f4bfc445bd8 - trans::debuginfo::scope_metadata::hf9fd39861fe17736Qwx
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/debuginfo.rs:1783
   8:     0x7f4bfc449003 - trans::debuginfo::set_source_location::h85432d1b64ef8ed5yZw
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/debuginfo.rs:1192
   9:     0x7f4bfc31a06e - trans::debuginfo::DebugLoc::apply::hbde8b0970990a654WXw
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/debuginfo.rs:1131
  10:     0x7f4bfc2067fb - trans::build::ICmp::hb71e7910d1b8469dObk
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/build.rs:869
  11:     0x7f4bfc2419e1 - trans::base::compare_scalar_types::h706f31ea0109b3d0Leg
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/base.rs:330
  12:     0x7f4bfc52c1df - trans::_match::compare_values::h710e2cbfb6f1c2edYnH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:846
  13:     0x7f4bfc536598 - trans::_match::compile_submatch_continue::h16329fc951fe728aMJH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1194
  14:     0x7f4bfc533cd8 - trans::_match::compile_submatch::h6a4ca73fe05b4716SDH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1013
  15:     0x7f4bfc537222 - trans::_match::compile_submatch_continue::h16329fc951fe728aMJH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1257
  16:     0x7f4bfc533cd8 - trans::_match::compile_submatch::h6a4ca73fe05b4716SDH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1013
  17:     0x7f4bfc5357a8 - trans::_match::compile_submatch_continue::h16329fc951fe728aMJH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1103
  18:     0x7f4bfc533cd8 - trans::_match::compile_submatch::h6a4ca73fe05b4716SDH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1013
  19:     0x7f4bfc5357a8 - trans::_match::compile_submatch_continue::h16329fc951fe728aMJH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1103
  20:     0x7f4bfc533cd8 - trans::_match::compile_submatch::h6a4ca73fe05b4716SDH
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1013
  21:     0x7f4bfc53c287 - trans::_match::trans_match_inner::h5f0836ef38b9f073DbI
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1492
  22:     0x7f4bfc4a6ba9 - trans::_match::trans_match::h239fad96f5ef96e0n2H
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1294
  23:     0x7f4bfc495ee4 - trans::expr::trans_rvalue_dps_unadjusted::h80f896fb3faf1245F7A
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:961
  24:     0x7f4bfc421019 - trans::expr::trans_into::h3ccaf3b6ea8f775508z
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:191
  25:     0x7f4bfc495c6f - trans::expr::trans_rvalue_dps_unadjusted::h80f896fb3faf1245F7A
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:952
  26:     0x7f4bfc49591f - trans::expr::trans_unadjusted::h268cb494e1c93df6cCA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:514
  27:     0x7f4bfc2174b3 - trans::expr::trans::h981e3932d3447597jfA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/macros.rs:268
  28:     0x7f4bfc4203c3 - trans::expr::trans_to_lvalue::h7887d39729fe05aelBA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/macros.rs:477
  29:     0x7f4bfc4a05a4 - trans::expr::trans_addr_of::h8d9a53b67ba55fb7FXB
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/macros.rs:1618
  30:     0x7f4bfc49ca84 - trans::expr::trans_datum_unadjusted::h7cc55f88be98701dIGA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:601
  31:     0x7f4bfc4956bf - trans::expr::trans_unadjusted::h268cb494e1c93df6cCA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:496
  32:     0x7f4bfc420f98 - trans::expr::trans_into::h3ccaf3b6ea8f775508z
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:188
  33:     0x7f4bfc27f4e8 - trans::expr::trans_adt::h0f77a7165e0d6f39oDB
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:1468
  34:     0x7f4bfc4962b7 - trans::expr::trans_rvalue_dps_unadjusted::h80f896fb3faf1245F7A
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:1030
  35:     0x7f4bfc49591f - trans::expr::trans_unadjusted::h268cb494e1c93df6cCA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:514
  36:     0x7f4bfc2174b3 - trans::expr::trans::h981e3932d3447597jfA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/macros.rs:268
  37:     0x7f4bfc4203c3 - trans::expr::trans_to_lvalue::h7887d39729fe05aelBA
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/macros.rs:477
  38:     0x7f4bfc53bd3d - trans::_match::trans_match_inner::h5f0836ef38b9f073DbI
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/macros.rs:1438
  39:     0x7f4bfc4a6ba9 - trans::_match::trans_match::h239fad96f5ef96e0n2H
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/_match.rs:1294
  40:     0x7f4bfc495ee4 - trans::expr::trans_rvalue_dps_unadjusted::h80f896fb3faf1245F7A
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:961
  41:     0x7f4bfc421019 - trans::expr::trans_into::h3ccaf3b6ea8f775508z
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:191
  42:     0x7f4bfc2797ad - trans::controlflow::trans_block::hb579432ea112bfeen6u
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/controlflow.rs:135
  43:     0x7f4bfc495f66 - trans::expr::trans_rvalue_dps_unadjusted::h80f896fb3faf1245F7A
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:964
  44:     0x7f4bfc421019 - trans::expr::trans_into::h3ccaf3b6ea8f775508z
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/expr.rs:191
  45:     0x7f4bfc420186 - trans::controlflow::trans_stmt_semi::hbc63e50e355c2024r5u
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/controlflow.rs:91
  46:     0x7f4bfc41fe4f - trans::controlflow::trans_stmt::h05ea3db289f03891I1u
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/controlflow.rs:59
  47:     0x7f4bfc27948d - trans::controlflow::trans_block::hb579432ea112bfeen6u
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/controlflow.rs:113
  48:     0x7f4bfc2766c2 - trans::base::trans_closure::h6d1530c49561d4cdIFh
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/base.rs:1575
  49:     0x7f4bfc279fbd - trans::base::trans_fn::hc581d87839a8bc70qQh
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/base.rs:1626
  50:     0x7f4bfc286c54 - trans::base::trans_item::h90343d4245c9b7d4Cei
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/base.rs:1974
  51:     0x7f4bfc29221c - trans::base::trans_mod::h47fae6c30e7d7488dli
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/base.rs:2072
  52:     0x7f4bfc2ae192 - trans::base::trans_crate::h411bbccf6051a049p3i
                        at /home/ariel/Rust/source.arielb1/src/librustc_trans/trans/base.rs:2678
  53:     0x7f4bfe5a545c - driver::phase_4_translate_to_llvm::closure.23322
                        at /home/ariel/Rust/source.arielb1/src/librustc_driver/driver.rs:726
  54:     0x7f4bfe5a4e56 - util::common::time::h107191199815012417
                        at /home/ariel/Rust/source.arielb1/src/librustc/util/common.rs:39
  55:     0x7f4bfe419f32 - driver::phase_4_translate_to_llvm::hd66343dc557f2851nOa
                        at /home/ariel/Rust/source.arielb1/src/librustc_driver/driver.rs:725
  56:     0x7f4bfe39dce5 - driver::compile_input::he2415a83948b6cffQba
                        at /home/ariel/Rust/source.arielb1/src/librustc_driver/driver.rs:141
  57:     0x7f4bfe61650f - run_compiler::h4bb177005d929e8465b
                        at /home/ariel/Rust/source.arielb1/src/librustc_driver/lib.rs:156
  58:     0x7f4bfe612feb - run::closure.26036
                        at /home/ariel/Rust/source.arielb1/src/librustc_driver/lib.rs:99
  59:     0x7f4bfe6121d8 - monitor::closure.26008
                        at /home/ariel/Rust/source.arielb1/src/librustc_driver/lib.rs:813
  60:     0x7f4bfe6120b5 - boxed::F.FnBox<A>::call_box::h5443103248061583594
                        at /home/ariel/Rust/source.arielb1/src/liballoc/boxed.rs:369
  61:     0x7f4bfe61183e - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h13737207089984465542
                        at /home/ariel/Rust/source.arielb1/src/liballoc/boxed.rs:385
  62:     0x7f4bfe610e0b - thread::Builder::spawn_inner::closure.25963
                        at /home/ariel/Rust/source.arielb1/src/libstd/thread/mod.rs:346
  63:     0x7f4bfe610d8e - rt::unwind::try::try_fn::__rust_abi::h14508903566358963269
                        at /home/ariel/Rust/source.arielb1/src/libstd/rt/unwind.rs:139
  64:     0x7f4bfe610d29 - rt::unwind::try::try_fn::h14508903566358963269
  65:     0x7f4bfdeadf28 - rust_try_inner
  66:     0x7f4bfdeadf15 - rust_try
  67:     0x7f4bfe6102d9 - rt::unwind::try::h16873351650945250128
                        at /home/ariel/Rust/source.arielb1/src/libstd/rt/unwind.rs:125
  68:     0x7f4bfe6100bc - thread::Builder::spawn_inner::closure.25885
                        at /home/ariel/Rust/source.arielb1/src/libstd/thread/mod.rs:346
  69:     0x7f4bfe611a70 - boxed::F.FnBox<A>::call_box::h6821850039505705260
                        at /home/ariel/Rust/source.arielb1/src/liballoc/boxed.rs:369
  70:     0x7f4bfdd4db0e - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h8025055706015138956
                        at /home/ariel/Rust/source.arielb1/src/liballoc/boxed.rs:377
  71:     0x7f4bfdd4da46 - sys_common::thread::start_thread::h849d0760ffa46914o0q
                        at /home/ariel/Rust/source.arielb1/src/libstd/sys/common/thread.rs:30
  72:     0x7f4bfdd7acf4 - sys::thread::Thread::new::thread_start::__rust_abi
                        at /home/ariel/Rust/source.arielb1/src/libstd/sys/unix/thread.rs:77
  73:     0x7f4bfdd7acd4 - sys::thread::Thread::new::thread_start::h246b8d39c875ef72R9u
  74:     0x7f4bf70b70a3 - start_thread
  75:     0x7f4bfd92c04c - clone
  76:                0x0 - <unknown>
```

This affects various versions of rustc including `6b95d8bed 2015-04-09` and `551a74ddd 2015-04-29`, and causes `make test` to fail when rustc is configured with `--enable-debuginfo`.

**Comment by arielb1** [comment]
Minified:
```Rust
struct Foo(bool);
const NEW_FALSE: bool = false;
const STATIC_FOO: Foo = Foo(NEW_FALSE);

pub fn main() {
    match (Foo(false)) {
        STATIC_FOO => 3,
        _ => 11
    };
}
```

**Comment by tamird** [comment]
This issue was incorrectly closed - it only manifests when building with debuginfo, but the test case added in #29284 is not a debuginfo test. cc @apasel422

**Comment by tamird** [comment]
@apasel422 see #29696
