### ISSUE TITLE
Compiler crash: thread 'rustc' panicked at 'expected item, found variant Add in timers::Add (id=649981)'

### ISSUE THREAD

**Issue by pgonda** [rust-lang/rust#25435]
I was trying to add new feature in to servo, got this compiler crash.

I tried this code:

https://github.com/pgonda/servo/blob/timeout-event-loop-thread/components/script/timers.rs

Instead, this happened: 
```~~~~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'expected item, found variant Add in timers::Add (id=649981)', /Users/larsberg/rust/src/libsyntax/ast_map/mod.rs:332```
 

## Meta

```rustc 1.0.0-nightly (cfea8ec41 2015-03-10) (built 2015-03-10)
binary: rustc
commit-hash: cfea8ec41699e25c8fb524d625190f0cb860dc71
commit-date: 2015-03-10
build-date: 2015-03-10
host: x86_64-apple-darwin
release: 1.0.0-nightly```

Backtrace:
```thread 'rustc' panicked at 'expected item, found variant Add in timers::Add (id=649981)', /Users/larsberg/rust/src/libsyntax/ast_map/mod.rs:332

stack backtrace:
   1:        0x106c334ef - sys::backtrace::write::h6990067d88907b48zVr
   2:        0x106c3bb60 - panicking::on_panic::he976cdbadffd9e1bEVv
   3:        0x106bf7ed5 - rt::unwind::begin_unwind_inner::ha519446d83876aa8nDv
   4:        0x106bf8d0c - rt::unwind::begin_unwind_fmt::h15c2d4adf8e8ecdatCv
   5:        0x106374382 - ast_map::Map<'ast>::expect_item::h4e16fb1d667f8361hhw
   6:        0x118830118 - lints::unrooted_must_root::UnrootedPass.LintPass::check_struct_def::habd1bd66de6adfa3qUa
   7:        0x10442ca73 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_struct_def::h0bcd744d676ee3caais
   8:        0x104434127 - visit::walk_variant::h2224026504919007410
   9:        0x104433751 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h11574635434562495924
  10:        0x104427839 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h3545367658681599959
  11:        0x10442c418 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_mod::hbcd53c11c2326899Mps
  12:        0x104427725 - lint::context::Context<'a, 'tcx>::with_lint_attrs::h3545367658681599959
  13:        0x10442c418 - lint::context::Context<'a, 'tcx>.Visitor<'v>::visit_mod::hbcd53c11c2326899Mps
  14:        0x10443ae42 - lint::context::check_crate::h13f19518a42a4859LJs
  15:        0x10372121f - driver::phase_3_run_analysis_passes::h318fe58bfd9a5097tGa
  16:        0x1037007dc - driver::compile_input::hd0d89b8b8141ab40Qba
  17:        0x1037bfbb3 - run_compiler::h2abbc25866a06d5065b
  18:        0x1037bd31a - boxed::F.FnBox<A>::call_box::h14521997622206872592
  19:        0x1037bc857 - rt::unwind::try::try_fn::h10757206887470260719
  20:        0x106cc1278 - rust_try_inner
  21:        0x106cc1265 - rust_try
  22:        0x1037bcb3e - boxed::F.FnBox<A>::call_box::h2889731625864154681
  23:        0x106c3a55d - sys::thread::Thread::new::thread_start::h5fcf8fe12ec3c274mYu
  24:     0x7fff8af8c267 - _pthread_body
  25:     0x7fff8af8c1e4 - _pthread_start```

**Comment by jdm** [comment]
The panic originates from one of our compiler plugins (lints/unrooted_must_root.rs), so that might be Servo's fault instead.

**Comment by jdm** [comment]
Oh yeah, that's definitely ours. I don't think we use struct variants anywhere else in the code.
