### ISSUE TITLE
ICE 'rustc' panicked at 'decoder error', libsyntax/diagnostics/plugin.rs:171

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#25680]
Panic  in libsyntax.
Rustc version: d7185dc

Configure: `./configure --enable-debug --enable-optimize --enable-ccache --disable-llvm-assertions`

```
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_borrowck
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'decoder error', src/rust/src/libsyntax/diagnostics/plugin.rs:171

stack backtrace:
   1:     0x7fb76141cfc9 - sys::backtrace::write::h1d8fb6d4dfce3c34r5r
                        at src/libstd/sys/unix/backtrace.rs:158
   2:     0x7fb7614264bd - panicking::on_panic::h43b958ce05dd6e67zLw
                        at src/libstd/panicking.rs:47
   3:     0x7fb7613e46db - rt::unwind::begin_unwind_inner::h6663476599878224Jqw
                        at src/libstd/rt/unwind/mod.rs:273
   4:     0x7fb7613e579d - rt::unwind::begin_unwind_fmt::hf828e1c3951fed88Ppw
                        at src/libstd/rt/unwind/mod.rs:212
   5:     0x7fb75e770efa - diagnostics::plugin::expand_build_diagnostic_array::h912e1e5803857908QNa
                        at src/rust/<std macros>:8
                        at src/libsyntax/diagnostics/plugin.rs:46
                        at src/libstd/thread/local.rs:245
                        at src/libsyntax/diagnostics/plugin.rs:45
                        at src/libsyntax/diagnostics/plugin.rs:162
   6:     0x7fb75f65e902 - ext::base::F.TTMacroExpander::expand::h7959181040335002158
                        at src/libsyntax/ext/base.rs:223
   7:     0x7fb75e997710 - ext::expand::expand_item_mac::h2c28ab6808a9488d1dc
                        at src/libsyntax/ext/expand.rs:597
   8:     0x7fb75e98cb85 - ext::expand::expand_annotatable::h82062816748e6a20tIc
                        at src/libsyntax/ext/expand.rs:1079
   9:     0x7fb75e989930 - ext::expand::expand_item::h7339efb8ef58b2be1ac
                        at src/libsyntax/ext/expand.rs:509
  10:     0x7fb75e991e5c - iter::FlatMap<I, U, F>.Iterator::next::h7384383747816317969
                        at src/libsyntax/ext/expand.rs:1423
                        at src/libsyntax/fold.rs:1028
                        at src/libcore/iter.rs:2288
                        at src/libcore/option.rs:420
                        at src/libcore/iter.rs:2288
  11:     0x7fb75e991b72 - vec::Vec<T>.FromIterator<T>::from_iter::h4598689836616378685
                        at src/libcollections/vec.rs:1501
  12:     0x7fb75e991813 - fold::noop_fold_mod::h16117845701021966637
                        at src/libcore/iter.rs:567
                        at src/libsyntax/fold.rs:1028
  13:     0x7fb75e98e646 - ext::expand::expand_item_underscore::h3ac0d12325ed32e3Cbc
                        at src/libsyntax/fold.rs:146
                        at src/libsyntax/fold.rs:929
                        at src/libsyntax/ext/expand.rs:522
  14:     0x7fb75e9d0ba1 - fold::noop_fold_item_simple::h14667964772249308596
                        at src/libsyntax/ext/expand.rs:1427
                        at src/libsyntax/fold.rs:1084
  15:     0x7fb75e9d0976 - ptr::P<T>::map::h3475871321125062719
                        at src/libsyntax/fold.rs:90
                        at src/libsyntax/fold.rs:1077
                        at src/libsyntax/ptr.rs:75
  16:     0x7fb75e98d5e2 - ext::expand::expand_annotatable::h82062816748e6a20tIc
                        at src/libsyntax/fold.rs:1077
                        at src/libsyntax/ext/expand.rs:1091
  17:     0x7fb75e989930 - ext::expand::expand_item::h7339efb8ef58b2be1ac
                        at src/libsyntax/ext/expand.rs:509
  18:     0x7fb75e9d62ef - ext::expand::expand_crate::h02456766be88b621Z9c
                        at src/libsyntax/ext/expand.rs:1423
                        at src/libsyntax/fold.rs:1036
                        at src/libsyntax/fold.rs:66
                        at src/libsyntax/ext/expand.rs:1526
  19:     0x7fb7619dc1f6 - driver::phase_2_configure_and_expand::closure.21634
                        at src/librustc_driver/driver.rs:494
  20:     0x7fb7619996f8 - driver::phase_2_configure_and_expand::h91dc2c00c68d4c90Ysa
                        at src/librustc/util/common.rs:39
                        at src/librustc_driver/driver.rs:472
  21:     0x7fb76198a63b - driver::compile_input::hddda0a8df1ee446bQba
                        at src/librustc_driver/driver.rs:88
  22:     0x7fb761a2ae65 - run_compiler::hdd012c90d6058dac75b
                        at src/librustc_driver/lib.rs:156
  23:     0x7fb761a28a2c - boxed::F.FnBox<A>::call_box::h3755598311287292093
                        at src/librustc_driver/lib.rs:99
                        at src/librustc_driver/lib.rs:813
                        at src/liballoc/boxed.rs:379
  24:     0x7fb761a2826e - rt::unwind::try::try_fn::h14663892004265928413
  25:     0x7fb7614c7cb8 - rust_try_inner
  26:     0x7fb7614c7ca5 - rust_try
  27:     0x7fb761410eac - rt::unwind::try::inner_try::h16d60c967f40c158Cmw
                        at src/libstd/rt/unwind/mod.rs:147
  28:     0x7fb761a284b0 - boxed::F.FnBox<A>::call_box::h8869887110923735820
                        at src/libstd/rt/unwind/mod.rs:130
                        at src/libstd/thread/mod.rs:346
                        at src/liballoc/boxed.rs:379
  29:     0x7fb76142523e - sys::thread::Thread::new::thread_start::hf710d4f2c57505bdSwv
  30:     0x7fb75b68e0a3 - start_thread
  31:     0x7fb76106104c - clone
  32:                0x0 - <unknown>
```

cc @nikomatsakis

**Comment by bluss** [comment]
Thanks steve.

This might have been due to some artifact being stale? Make clean && make built fine again.
