### ISSUE TITLE
Compiler panic at src/libsyntax/diagnostics/plugin.rs:171

### ISSUE THREAD

**Issue by cllns** [rust-lang/rust#25690]
Tried to compile from master, but the 'compiler unexpectedly panicked'

```
% make RUST_BACKTRACE=1
cfg: version 1.2.0-dev (7044f4a39 2015-05-21) (built 2015-05-21)
cfg: build triple x86_64-apple-darwin
cfg: host triples x86_64-apple-darwin
cfg: target triples x86_64-apple-darwin
cfg: host for x86_64-apple-darwin is x86_64
cfg: os for x86_64-apple-darwin is apple-darwin
cfg: good valgrind for x86_64-apple-darwin is
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: disabling valgrind run-pass tests
rustc: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_borrowck
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'decoder error', /Users/sean/dev/rust/src/libsyntax/diagnostics/plugin.rs:171

stack backtrace:
   1:        0x103f608bc - sys::backtrace::write::h5ff6ad25661cc291u2r
   2:        0x103f68665 - panicking::on_panic::h7c9ea8abc1bb177a2iw
   3:        0x103f2c613 - rt::unwind::begin_unwind_inner::ha6d16e5ff816806cL0v
   4:        0x103f2d3e5 - rt::unwind::begin_unwind_fmt::h4572fb92b577087aRZv
   5:        0x103755693 - diagnostics::plugin::expand_build_diagnostic_array::h4b7732f343a19110QNa
   6:        0x10189d443 - ext::base::F.TTMacroExpander::expand::h4136136389273748923
   7:        0x103959178 - ext::expand::expand_item_mac::hdd146f2c4019efdd1dc
   8:        0x10394efe8 - ext::expand::expand_annotatable::h033c6ecb5ac82abftIc
   9:        0x10394bdc0 - ext::expand::expand_item::hd0748d7fdb5619211ac
  10:        0x103953fff - iter::FlatMap<I, U, F>.Iterator::next::h8590409607985201328
  11:        0x103953d7b - vec::Vec<T>.FromIterator<T>::from_iter::h1639266260791834947
  12:        0x103950ee0 - ext::expand::expand_item_underscore::h04447d45156a5e66Cbc
  13:        0x10398e7f8 - fold::noop_fold_item_simple::h3416248848557026180
  14:        0x10394fbee - ext::expand::expand_annotatable::h033c6ecb5ac82abftIc
  15:        0x10394bdc0 - ext::expand::expand_item::hd0748d7fdb5619211ac
  16:        0x103994717 - ext::expand::expand_crate::hdfe08c43d5c734b9Z9c
  17:        0x100d90f8a - driver::phase_2_configure_and_expand::closure.20251
  18:        0x100d4a2ba - driver::phase_2_configure_and_expand::h5b2bd1e8bf0eb003Ysa
  19:        0x100d3c02c - driver::compile_input::h1c7d3f253c07f27aQba
  20:        0x100de3e12 - run_compiler::h18718cf0e294a90b75b
  21:        0x100de196e - boxed::F.FnBox<A>::call_box::h16766091035826955613
  22:        0x100de11a7 - rt::unwind::try::try_fn::h12655135335441453264
  23:        0x103ff21e8 - rust_try_inner
  24:        0x103ff21d5 - rust_try
  25:        0x103f55ed5 - rt::unwind::try::inner_try::hcd23c8ca0774326bEWv
  26:        0x100de1406 - boxed::F.FnBox<A>::call_box::h1657350025221526688
  27:        0x103f67368 - sys::thread::Thread::new::thread_start::h2e5b9b7bcb6859fchlv
  28:     0x7fff9a5342fb - _pthread_body
  29:     0x7fff9a534278 - _pthread_start

make: *** [x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/stamp.rustc_borrowck] Error 101
```

Not sure why this happened, could be something on my end.

https://github.com/rust-lang/rust/blob/master/src/libsyntax/diagnostics/plugin.rs#L171 is the file and line in question.

Running OS X Yosemite.

**Comment by pnkfelix** [comment]
When I encountered this today, I did `rm tmp/extended-errors/librustc*` and it seemed to go away on the next build attempt.  (Obviously that's not a proper fix; it just might be useful to people searching the repo and finding this ticket...)

**Comment by cllns** [comment]
Thanks @pnkfelix, that worked for me! I think i Ctrl-C'd the first time I ran make, so maybe it left the system in a bad state. 

Since you ran into this today as well, I'll leave this Issue open. Maybe there is an underlying bug here.

(Rust team: feel free to close this if there are no other responses within a week or so)

**Comment by Passw** [comment]
see this under 
```
# lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.4 (Santiago)
Release:	6.4
Codename:	Santiago
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid
```

**Comment by r-arias** [comment]
I have the same bug on OS X when building 1.1.0.
```
[~/Documents/rust-build-ios]$ make -j3 RUST_BACKTRACE=1                                               [ruby-2.1.2] 
cfg: version 1.1.0-dev (35ceea399 2015-06-19)
cfg: build triple x86_64-apple-darwin
cfg: host triples x86_64-apple-darwin
cfg: target triples x86_64-apple-darwin armv7-apple-ios armv7s-apple-ios i386-apple-ios aarch64-apple-ios x86_64-apple-ios
cfg: non-build target triples armv7-apple-ios armv7s-apple-ios i386-apple-ios aarch64-apple-ios x86_64-apple-ios
cfg: host for x86_64-apple-darwin is x86_64
cfg: host for armv7-apple-ios is armv7
cfg: host for armv7s-apple-ios is armv7s
cfg: host for i386-apple-ios is i386
cfg: host for aarch64-apple-ios is aarch64
cfg: host for x86_64-apple-ios is x86_64
cfg: os for x86_64-apple-darwin is apple-darwin
cfg: os for armv7-apple-ios is apple-ios
cfg: os for armv7s-apple-ios is apple-ios
cfg: os for i386-apple-ios is apple-ios
cfg: os for aarch64-apple-ios is apple-ios
cfg: os for x86_64-apple-ios is apple-ios
cfg: good valgrind for x86_64-apple-darwin is 
cfg: good valgrind for armv7-apple-ios is 
cfg: good valgrind for armv7s-apple-ios is 
cfg: good valgrind for i386-apple-ios is 
cfg: good valgrind for aarch64-apple-ios is 
cfg: good valgrind for x86_64-apple-ios is 
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: disabling valgrind run-pass tests
rustc: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'os error', /Users/arias/Documents/rust/src/libsyntax/diagnostics/plugin.rs:171

stack backtrace:
   1:        0x103544ffc - sys::backtrace::write::he9710ed45a1f2fddc2r
   2:        0x10354cce5 - panicking::on_panic::h651f57d66847d188Lgw
   3:        0x103510cc3 - rt::unwind::begin_unwind_inner::h8ce36f48c4f8d07cuYv
   4:        0x103511a95 - rt::unwind::begin_unwind_fmt::h6e0a2760e6dce819AXv
   5:        0x102d3b8de - diagnostics::plugin::expand_build_diagnostic_array::h13d81b0feb89cd21QNa
   6:        0x100e16ac3 - ext::base::F.TTMacroExpander::expand::h1439180917286580280
   7:        0x102f3f794 - ext::expand::expand_item_mac::h5fe1b3afec5fdc89Bgc
   8:        0x102f35868 - ext::expand::expand_annotatable::h53cf52c7843d40b73Kc
   9:        0x102f32640 - ext::expand::expand_item::hfe47e3cc20ce4f92Bdc
  10:        0x102f3a60f - iter::FlatMap<I, U, F>.Iterator::next::h3360546454327385898
  11:        0x102f3a38b - vec::Vec<T>.FromIterator<T>::from_iter::h10984259839597934138
  12:        0x102f37698 - ext::expand::expand_item_underscore::h459df196ec0e0203cec
  13:        0x102f74858 - fold::noop_fold_item_simple::h1980239792232803492
  14:        0x102f3646e - ext::expand::expand_annotatable::h53cf52c7843d40b73Kc
  15:        0x102f32640 - ext::expand::expand_item::hfe47e3cc20ce4f92Bdc
  16:        0x102f7a777 - ext::expand::expand_crate::hd57edfc3f3c25e28zcd
  17:        0x100315a5a - driver::phase_2_configure_and_expand::closure.20198
  18:        0x1002cee5a - driver::phase_2_configure_and_expand::hfd45f222dc91151aYsa
  19:        0x1002c0c4c - driver::compile_input::h5e52b152a6e61d0dQba
  20:        0x100368e62 - run_compiler::h2bae6ad099a5e6be75b
  21:        0x1003669be - boxed::F.FnBox<A>::call_box::h14492299571019174799
  22:        0x100366187 - rt::unwind::try::try_fn::h1980993045082273195
  23:        0x1035d7368 - rust_try_inner
  24:        0x1035d7355 - rust_try
  25:        0x100366425 - boxed::F.FnBox<A>::call_box::h3280019795504741580
  26:        0x10354bab8 - sys::thread::Thread::new::thread_start::h220539c055074a3aYjv
  27:     0x7fff8b069267 - _pthread_body
  28:     0x7fff8b0691e4 - _pthread_start

make: *** [x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/stamp.rustc] Error 101
```

**Comment by steveklabnik** [comment]
Triage: it's been a while. Is anyone still seeing this?

**Comment by Mark-Simulacrum** [comment]
I'm going to close since presumably this has gone away, let us know if you still see this and we can reopen.
