### ISSUE TITLE
ICE when importing a type that's already been imported

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#25930]
Test case:
```rust
use std::io::{Error};
use std::error::Error;
 
fn main() {}
```
Output:
```
ed.rs:2:5: 2:22 error: a type named `Error` has already been imported in this module [E0252]
ed.rs:2 use std::error::Error;
            ^~~~~~~~~~~~~~~~~
ed.rs:2:5: 2:22 help: run `rustc --explain E0252` to see a detailed explanation
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'expected item, found unknown node (id=5)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ast_map/mod.rs:332
```
Backtrace:
```
ed.rs:2:5: 2:22 error: a type named `Error` has already been imported in this module [E0252]
ed.rs:2 use std::error::Error;
            ^~~~~~~~~~~~~~~~~
ed.rs:2:5: 2:22 help: run `rustc --explain E0252` to see a detailed explanation
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'expected item, found unknown node (id=5)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ast_map/mod.rs:332

stack backtrace:
   1:     0x7f3b4d9ba169 - sys::backtrace::write::h4052d6a51ba10f8105r
   2:     0x7f3b4d9c20b9 - panicking::on_panic::h90cadee2464dd3b41Kw
   3:     0x7f3b4d983192 - rt::unwind::begin_unwind_inner::ha0307b6be50a7723bqw
   4:     0x7f3b4d983f27 - rt::unwind::begin_unwind_fmt::hb83f1cf97f4362d4hpw
   5:     0x7f3b4ad08d34 - ast_map::Map<'ast>::expect_item::h1d12c09f65923ec7Pyw
   6:     0x7f3b4ce71bbe - resolve_imports::ImportResolver<'a, 'b, 'tcx>::check_for_conflicting_import::h608d7a4439aa8b45p4c
   7:     0x7f3b4ce712db - resolve_imports::ImportResolver<'a, 'b, 'tcx>::resolve_single_import::closure.15499
   8:     0x7f3b4ce6ce3e - resolve_imports::ImportResolver<'a, 'b, 'tcx>::resolve_imports_for_module::h4f5175c3877ad2f468b
   9:     0x7f3b4ce6a46f - resolve_imports::ImportResolver<'a, 'b, 'tcx>::resolve_imports_for_module_subtree::h94228ba4073393c8V5b
  10:     0x7f3b4ceabcfc - resolve_crate::h9b28f68538793170iai
  11:     0x7f3b4df089c2 - driver::phase_3_run_analysis_passes::h83b5112ae07f494ftGa
  12:     0x7f3b4deee0cc - driver::compile_input::h0a7842b43c159d70Qba
  13:     0x7f3b4dfa4011 - run_compiler::hb2dfa1770188c5e175b
  14:     0x7f3b4dfa1862 - boxed::F.FnBox<A>::call_box::h10739628233630710986
  15:     0x7f3b4dfa0e29 - rt::unwind::try::try_fn::h12004866116241301408
  16:     0x7f3b4da3a7c8 - rust_try_inner
  17:     0x7f3b4da3a7b5 - rust_try
  18:     0x7f3b4dfa10c4 - boxed::F.FnBox<A>::call_box::h9242018289459349633
  19:     0x7f3b4d9c0e51 - sys::thread::Thread::new::thread_start::he4baa243e39f5dd6ixv
  20:     0x7f3b47a77b4f - start_thread
  21:     0x7f3b4d61e95c - <unknown>
```

**Comment by arielb1** [comment]
Does not affect nightly.

**Comment by steveklabnik** [comment]
That's true, it does not.
