### ISSUE TITLE
arithmetic operation overflowed at /src/libcore/cell.rs:510

### ISSUE THREAD

**Issue by skeleten** [rust-lang/rust#27225]
Hello, 
I seem to be experiencing a very volatile bug and after seeking help in the rust irc channel, I decided to file a bug report.
Unfortunately I didn't found a small piece of code that is able to replicate the bug, and even my full source code doesn't do so at all times (I have to try a couple of times for it to happen again)
The source code can be found under https://github.com/skeleten/fiesta-test/tree/cell-overflow-bug (the main code base can be found under https://github.com/skeleten/fiesta-net/tree/cell-overflow-bug )
What I do is, run the application and then for testing purposes `cat /dev/random | nc localhost 1080`. 
At times I receive the following panic:
```
thread 'WRKR 0' panicked at 'arithmetic operation overflowed', ../src/libcore/cell.rs:510
stack backtrace:
   1:     0x7fadd389c8ee - sys::backtrace::write::habd9c372567b62faQws
   2:     0x7fadd389fe96 - panicking::on_panic::hb5f16fc65f3b2d8ealx
   3:     0x7fadd389563e - rt::unwind::begin_unwind_inner::heaf29d445e8aff7fO0w
   4:     0x7fadd3896056 - rt::unwind::begin_unwind_fmt::hf01ad8aba22500ecUZw
   5:     0x7fadd389f866 - rust_begin_unwind
   6:     0x7fadd38cb534 - panicking::panic_fmt::hd5edd7147db51424AgC
   7:     0x7fadd38caf2d - panicking::panic::h573d06ec4f712e417eC
   8:     0x7fadd38333f6 - cell::BorrowRef<'b>.Drop::drop::h5ce7c189c93f9b73dNB
                        at ../src/libcore/cell.rs:510
   9:     0x7fadd3833341 - core..cell..BorrowRef::drop.2380::hbcf9aa2eaaa39869
  10:     0x7fadd3834e7e - core..cell..Ref<Box<fiesta_net..client..FiestaNetworkClient>>::drop.2698::h9b54f9f516719dc4
  11:     0x7fadd3832f11 - SampleHandler.PacketProcessor::process_packet::h3371842d6338820dsca
                        at src/main.rs:23
  12:     0x7fadd3878234 - packetproc::PacketProcessingThreadPool::start_new_thread::closure.5938
                        at /home/skeleten/.cargo/git/checkouts/fiesta-net-22a029fbb16557a6/master/src/packetproc.rs:53
  13:     0x7fadd3878001 - boxed::F.FnBox<A>::call_box::h8305063294465291424
                        at ../src/liballoc/boxed.rs:396
  14:     0x7fadd3877ac0 - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$Send$u20$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h17107311661406854154
                        at ../src/liballoc/boxed.rs:412
  15:     0x7fadd3877572 - thread::Builder::spawn_inner::closure.5910
                        at ../src/libstd/thread/mod.rs:349
  16:     0x7fadd38774ee - rt::unwind::try::try_fn::__rust_abi::h10505714486088128700
                        at ../src/libstd/rt/unwind/mod.rs:158
  17:     0x7fadd3877489 - rt::unwind::try::try_fn::h10505714486088128700
  18:     0x7fadd38a4ce8 - rust_try_inner
  19:     0x7fadd38a4cd5 - rust_try
  20:     0x7fadd389b2c7 - rt::unwind::try::inner_try::h7f07e312bac7c641HWw
  21:     0x7fadd38773e8 - rt::unwind::try::h386761419037415322
                        at ../src/libstd/rt/unwind/mod.rs:130
  22:     0x7fadd3877243 - thread::Builder::spawn_inner::closure.5861
                        at ../src/libstd/thread/mod.rs:349
  23:     0x7fadd3877e3d - boxed::F.FnBox<A>::call_box::h14137052913148472222
                        at ../src/liballoc/boxed.rs:396
  24:     0x7fadd389e9c1 - sys::thread::Thread::new::thread_start::hd09de2d7dbf22d32u6v
  25:     0x7fadd29280a3 - start_thread
  26:     0x7fadd313508c - __clone
  27:                0x0 - <unknown>
```

cargo version: `cargo 0.4.0-nightly (0faebf2 2015-07-20) (built 2015-07-20)`
rustc version: `rustc 1.3.0-nightly (118a5c4c3 2015-07-21)`

I am running this in an openSUSE 64bit VM, under VMWare Workstation 10

**Comment by eefriedman** [comment]
I think your issue is `unsafe impl Send for PacketProcessingInfo { }`.  The compiler can't protect you if you're intentionally dodging the thread safety rules.

**Comment by alexcrichton** [comment]
Yeah that looks to be quite suspect, especially the `Arc<RefCell<T>>` I'm going to close this because that'd definitely cause this bug to crop up. I'd recommend avoiding `unsafe` code like the plague as much as possible, for example using `RwLock` instead of `RefCell` in this case.
