### ISSUE TITLE
Explicitly using `extern crate` in documentation examples gives unhelpful error

### ISSUE THREAD

**Issue by Syntaf** [rust-lang/rust#27301]
This would be more an enhancement than anything, but say if you have a library `bignum` and wanted to write an example in your docs

``````
//lib.rs
//...

impl BigNum {

    //...


    /// Constructs a ...
    ///
    /// # Examples
    ///
    /// ```
    /// extern crate bignum;
    /// use bignum::inits::Zero;
    ///
    /// let a = bignum::BigNum::new(Zero::zero());
    /// ```
    ///
    pub fn new(base: BigNum) -> BigNum {
        // ...
    }
``````

The error I made initially was I didn't know `extern crate bignum` is implicit, but the compiler errors I generated were what led me on a goose hunt. If I tried to compile this with `cargo test` I would get

```
---- new_0 stdout ----
    <anon>:3:9: 3:15 error: unresolved import `bignum::inits::Zero`. Did you mean `self::bignum::inits`?
<anon>:3     use bignum::inits::Zero;
                 ^~~~~~
error: aborting due to previous error
thread 'new_0' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:192
```

So I followed the errors advice, changing that statement but instead got?

```
---- new_0 stdout ----
    <anon>:3:9: 3:15 error: unresolved import `self::bignum::inits::Zero`. Did you mean `self::self::bignum::inits`?
<anon>:3     use self::bignum::inits::Zero;
                 ^~~~~~
error: aborting due to previous error
thread 'new_0' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:192
```

which leads you to the final error

```
---- new_0 stdout ----
    <anon>:3:9: 3:13 error: unresolved import `self::self::bignum::inits::Zero`. Maybe a missing `extern crate self`?
<anon>:3     use self::self::bignum::inits::Zero;
                 ^~~~
error: aborting due to previous error
thread 'new_0' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:192
```

Maybe in the future it would be useful to instead tell the user `extern crate bignum` is implicit? I spent a good while digging around before I realized my silly mistake, but the errors didn't seem lead me in any helpful direction.

**Comment by steveklabnik** [comment]
Triage: with no other comments since the initial report, and with rust 2017 making `extern crate` no longer necessary, I'm going to give this a close. Thanks for the suggestion @Syntaf !
