### ISSUE TITLE
Failing debuginfo test

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#27514]
The test that was restored in #27500 fails for me:

```
failures:

---- [debuginfo-gdb] debuginfo/gdb-pretty-struct-and-enums.rs stdout ----
        NOTE: compiletest thinks it is using GDB version 7.7

error: line not found in debugger output: $13 = Some = {"abc"}
status: exit code: 0
command: gdb -quiet -batch -nx -command=x86_64-unknown-linux-gnu/test/debuginfo-gdb/gdb-pretty-struct-and-enums.debugger.script
stdout:
------------------------------------------
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Breakpoint 1 at 0xca8: file /home/doener/src/rust-submit/src/test/debuginfo/gdb-pretty-struct-and-enums.rs, line 185.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, gdb_pretty_struct_and_enums::main () at /home/doener/src/rust-submit/src/test/debuginfo/gdb-pretty-struct-and-enums.rs:185
185         zzz(); // #break
$1 = RegularStruct = {the_first_field = 101, the_second_field = 102.5, the_third_field = false, the_fourth_field = "I'm so pretty, oh so pretty..."}
$2 = {true, 103, "blub"}
$3 = TupleStruct = {-104.5, 105}
$4 = EmptyStruct
$5 = CStyleEnumVar1
$6 = CStyleEnumVar2
$7 = CStyleEnumVar3
$8 = MixedEnumCStyleVar
$9 = MixedEnumTupleVar = {106, 107, false}
$10 = MixedEnumStructVar = {field1 = 108.5, field2 = 109}
$11 = Some = {110}
$12 = None
$13 = {RUST$ENCODED$ENUM$0$0$None = Some = {"abc"}}
$14 = {RUST$ENCODED$ENUM$0$0$None = Some = {""}}
$15 = NestedVariant1 = {NestedStruct = {regular_struct = RegularStruct = {the_first_field = 111, the_second_field = 112.5, the_third_field = true, the_fourth_field = "NestedStructString1"}, tuple_struct = TupleStruct = {113.5, 114}, empty_struct = EmptyStruct, c_style_enum = CStyleEnumVar2, mixed_enum = MixedEnumTupleVar = {115, 116, false}}}
$16 = NestedVariant2 = {abc = NestedStruct = {regular_struct = RegularStruct = {the_first_field = 117, the_second_field = 118.5, the_third_field = false, the_fourth_field = "NestedStructString10"}, tuple_struct = TupleStruct = {119.5, 120}, empty_struct = EmptyStruct, c_style_enum = CStyleEnumVar3, mixed_enum = MixedEnumStructVar = {field1 = 121.5, field2 = -122}}}
$17 = {RUST$ENCODED$ENUM$0$1$0$0$0$0$None = Some = {{0, Vec<usize>(len: 0, cap: 0)}}}
$18 = {RUST$ENCODED$ENUM$0$0$0$0$0$0$None = Some = {""}}
A debugging session is active.

        Inferior 1 [process 2200] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

------------------------------------------
stderr:
------------------------------------------
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
Python Exception <class 'gdb.error'> Cannot convert value to int.: 

------------------------------------------

thread '[debuginfo-gdb] debuginfo/gdb-pretty-struct-and-enums.rs' panicked at 'explicit panic', /home/doener/src/rust-submit/src/compiletest/runtest.rs:1490



failures:
    [debuginfo-gdb] debuginfo/gdb-pretty-struct-and-enums.rs
```

Seems that there is some extra, unexpected output that makes the test fail.

cc @michaelwoerister

**Comment by michaelwoerister** [comment]
That's interesting. I'm also using GDB 7.7.1 and for me it works just fine.

**Comment by michaelwoerister** [comment]
@dotdash Thank you for the report! Is there anything special about the system you are getting this error on? A custom GDB version? Rust built with non-standard flags or LLVM?

**Comment by dotdash** [comment]
@michaelwoerister Nothing special AFAICT. GDB is just the one that currently comes with Debian Sid and Rust is built with the bundled LLVM and no special options, just disabled assertions.

**Comment by brson** [comment]
@mw Is this worth tracking? Seems like with debuggers we can't maintain perfect backcompat.

**Comment by leodasvacas** [comment]
I assume you meant to ping @michaelwoerister

**Comment by Mark-Simulacrum** [comment]
@michaelwoerister Should we be tracking this?

**Comment by michaelwoerister** [comment]
The test case doesn't exist anymore. We should look into writing a new one, now that we support Rust-enabled and legacy GDB versions in the test framework.

**Comment by tromey** [comment]
I don't think we really need any new tests here.  Printing is covered reasonably well by other existing tests.  Therefore, I'm closing this.  Feel free to reopen if you disagree with this assessment, but if so be sure to indicate what is missing.  Thanks.
