### ISSUE TITLE
configure should make sure that LLVM FileCheck exists

### ISSUE THREAD

**Issue by sylvestre** [rust-lang/rust#27621]
Trying to package rust 1.2 into Debian & Ubuntu, I get the following test failures:
```
running 4 tests
test [codegen] codegen/coercions.rs ... FAILED
test [codegen] codegen/stores.rs ... FAILED
test [codegen] codegen/loads.rs ... FAILED
test [codegen] codegen/function-arguments.rs ... FAILED

failures:

---- [codegen] codegen/coercions.rs stdout ----
	thread '[codegen] codegen/coercions.rs' panicked at 'failed to exec `/usr/lib/llvm-3.6/bin/FileCheck`', src/libcore/option.rs:330


---- [codegen] codegen/stores.rs stdout ----
	thread '[codegen] codegen/stores.rs' panicked at 'failed to exec `/usr/lib/llvm-3.6/bin/FileCheck`', src/libcore/option.rs:330


---- [codegen] codegen/loads.rs stdout ----
	thread '[codegen] codegen/loads.rs' panicked at 'failed to exec `/usr/lib/llvm-3.6/bin/FileCheck`', src/libcore/option.rs:330


---- [codegen] codegen/function-arguments.rs stdout ----
	thread '[codegen] codegen/function-arguments.rs' panicked at 'failed to exec `/usr/lib/llvm-3.6/bin/FileCheck`', src/libcore/option.rs:330



failures:
    [codegen] codegen/coercions.rs
    [codegen] codegen/function-arguments.rs
    [codegen] codegen/loads.rs
    [codegen] codegen/stores.rs

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /home/sylvestre/dev/debian/rustc.git/src/compiletest/compiletest.rs:252

```

I am using Debian LLVM 3.6.1 packages  (version 3.6.1-1)

**Comment by dotdash** [comment]
`FileCheck` is in the `llvm-3.6.-tools` package.

I wonder whether we want a check in `configure` that makes `FileCheck` a requirement or one that disables the respective tests if it is not available.

**Comment by sylvestre** [comment]
That was indeed the issue. I installed it and I have issue 27628 now.

**Comment by alexcrichton** [comment]
Addressed in https://github.com/rust-lang/rust/pull/27630

**Comment by Zoxc** [comment]
These test should be optional until LLVM has a way to install FileCheck
