### ISSUE TITLE
rustc_platform_intrinsics takes LLVM lots of time to compile

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#28273]
CPU: 
```
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
stepping	: 3
microcode	: 0x12
cpu MHz		: 3392.293
cache size	: 8192 KB
```

with debuginfo:
```
time: 0.580; rss: 228MB translation
  time: 0.228; rss: 172MB       llvm function passes
  time: 48.802; rss: 287MB      llvm module passes
  time: 17.807; rss: 454MB      codegen passes
  time: 0.001; rss: 454MB       codegen passes
time: 67.451; rss: 454MB        LLVM passes
```

without debuginfo:
```
time: 0.467; rss: 221MB translation
  time: 0.179; rss: 167MB       llvm function passes
  time: 30.995; rss: 222MB      llvm module passes
  time: 10.347; rss: 342MB      codegen passes
  time: 0.000; rss: 342MB       codegen passes
time: 41.762; rss: 342MB        LLVM passes
```

We should either make this fast or write it to not trigger this worst-case.

cc @huonw 
cc @dotdash 

there was also a case of 600s compile-time on the same CPU, but I can't reproduce it.

**Comment by dotdash** [comment]
We have  a winner here:

```
  161.8920 ( 66.8%)   0.0340 (  4.9%)  161.9260 ( 66.6%)  161.6847 ( 66.6%)  Function Integration/Inlining
   8.2570 (  3.4%)   0.0270 (  3.9%)   8.2840 (  3.4%)   8.2553 (  3.4%)  Induction Variable Simplification
   6.8030 (  2.8%)   0.0100 (  1.4%)   6.8130 (  2.8%)   6.7934 (  2.8%)  Induction Variable Users
```

That's pretty impressive...

**Comment by arielb1** [comment]
what command did you use?

**Comment by dotdash** [comment]
That's with `-Ztime-llvm-passes`

**Comment by dotdash** [comment]
Findings so far: This is caused by LLVM doing cost analysis on the _caller_ if the caller has local linkage.

**Comment by dotdash** [comment]
Marking the three `find()` functions as `#[inline(never)]` stops us from triggering a pathological case in the inliner and reduces compile times by almost 70%.

**Comment by arielb1** [comment]
This seems to have grown out of control in debuginfo builds, with this sample:
```
#0  0x00002b853d8e37f5 in (anonymous namespace)::LiveDebugValues::VarLoc::operator==((anonymous namespace)::LiveDebugValues::VarLoc const&) const ()
   from /tmp/tmp.Vfq0tEURq9/rust/build-debug-assertions/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_llvm-db5a760f.so
#1  0x00002b853d8e644c in (anonymous namespace)::LiveDebugValues::ExtendRanges(llvm::MachineFunction&) ()
   from /tmp/tmp.Vfq0tEURq9/rust/build-debug-assertions/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_llvm-db5a760f.so
#2  0x00002b853e0bcd7a in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
   from /tmp/tmp.Vfq0tEURq9/rust/build-debug-assertions/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_llvm-db5a760f.so
#3  0x00002b853e0bd0db in llvm::FPPassManager::runOnModule(llvm::Module&) ()
   from /tmp/tmp.Vfq0tEURq9/rust/build-debug-assertions/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_llvm-db5a760f.so
#4  0x00002b853e0bd3d0 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /tmp/tmp.Vfq0tEURq9/rust/build-debug-assertions/x86_64-unknown-linux-gnu/stage1/bin/../lib/librustc_llvm-db5a760f.so
#5  0x00002b853cfe8861 in LLVMRustWriteOutputFile (Target=0x2b85441d3550, 
    PMR=0x2b855d18f280, M=0x2b85472daab0, path=<optimised out>, 
    FileType=llvm::TargetMachine::CGFT_ObjectFile)
```

**Comment by aturon** [comment]
cc @michaelwoerister
