### ISSUE TITLE
internal compiler error: unexpected panic (ERROR:rbml::reader: failed to find block with tag 56)

### ISSUE THREAD

**Issue by dermetfan** [rust-lang/rust#28409]
I'm trying to run a clone of https://github.com/pistondevelopers/piston-examples (at revision 88ee3ff1f1dde20ef9c6d71c098d3abbaba38039).

The following commands work (which means that the program crashes on my system, but that already happened before so it shouldn't be related to this issue):
- `cargo run --bin hello_world`
- `cargo run --bin sprite`

The following fail with the exact same error messages:
- `cargo run --bin draw_state`
- `cargo run --bin image`
- `cargo run --bin paint`
- `cargo run --bin deform`
- `cargo run --bin cube`
- `cargo run --bin texure_swap`

Which are (using `--bin texture_swap` but like I said the error is always the same):

```
[nix-shell:~/documents/development/rust/piston-examples]$ cargo run --bin texture_swap
   Compiling piston-examples v0.0.0 (file:///home/dermetfan/documents/development/rust/piston-examples)
ERROR:rbml::reader: failed to find block with tag 56
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', src/librbml/lib.rs:395


Could not compile `piston-examples`.

To learn more, run the command again with --verbose.
```

So I ran it with `RUST_BACKTRACE=1`:

```
[nix-shell:~/documents/development/rust/piston-examples]$ RUST_BACKTRACE=1 cargo run --bin texture_swap
   Compiling piston-examples v0.0.0 (file:///home/dermetfan/documents/development/rust/piston-examples)
ERROR:rbml::reader: failed to find block with tag 56
Could not compile `piston-examples`.

To learn more, run the command again with --verbose.
```

Nothing new here... So I ran it again with `--verbose`:

```
[nix-shell:~/documents/development/rust/piston-examples]$ cargo run --bin texture_swap --verbose
       Fresh rustc-serialize v0.3.16
       Fresh interpolation v0.1.0
       Fresh lzw v0.8.0
       Fresh pkg-config v0.3.5
       Fresh shader_version v0.2.1
       Fresh winapi-build v0.1.1
       Fresh piston-shaders_graphics2d v0.1.0
       Fresh color_quant v1.0.0
       Fresh piston-texture v0.2.3
       Fresh bitflags v0.3.2
       Fresh glob v0.2.10
       Fresh khronos_api v0.0.8
       Fresh find_folder v0.2.0
       Fresh libc v0.1.10
       Fresh gcc v0.3.13
       Fresh winapi v0.2.2
       Fresh lazy_static v0.1.14
       Fresh read_color v0.1.0
       Fresh byteorder v0.3.13
       Fresh bitflags v0.1.1
       Fresh piston-float v0.1.0
       Fresh khronos_api v0.0.5
       Fresh khronos_api v0.0.7
       Fresh gif v0.5.0
       Fresh draw_state v0.2.0
       Fresh xml-rs v0.1.26
       Fresh gl_common v0.0.4
       Fresh dylib v0.0.1
       Fresh dlib v0.1.1
       Fresh log v0.3.2
       Fresh clock_ticks v0.0.6
       Fresh shared_library v0.1.0
       Fresh piston-viewport v0.1.0
       Fresh vecmath v0.1.1
       Fresh x11-dl v2.0.1
       Fresh wayland-client v0.2.1
       Fresh gl_generator v0.0.26
       Fresh gl_generator v0.0.27
       Fresh osmesa-sys v0.0.5
       Fresh pistoncore-input v0.5.1
       Fresh quaternion v0.1.0
       Fresh piston2d-graphics v0.9.0
       Fresh kernel32-sys v0.1.4
       Fresh advapi32-sys v0.1.2
       Fresh miniz-sys v0.1.5
       Fresh libz-sys v0.1.8
       Fresh pistoncore-window v0.9.1
       Fresh piston-ai_behavior v0.8.0
       Fresh piston2d-drag_controller v0.7.0
       Fresh piston3d-cam v0.1.0
       Fresh rand v0.3.11
       Fresh flate2 v0.2.8
       Fresh freetype-sys v0.1.2
       Fresh pistoncore-event_loop v0.10.1
       Fresh camera_controllers v0.7.0
       Fresh tempfile v1.1.1
       Fresh num v0.1.27
       Fresh uuid v0.1.17
       Fresh tempdir v0.3.4
       Fresh gfx_gl v0.1.4
       Fresh gl v0.0.12
       Fresh freetype-rs v0.3.1
       Fresh piston v0.10.1
       Fresh wayland-window v0.1.0
       Fresh gfx v0.7.0
       Fresh sdl2-sys v0.6.2
       Fresh enum_primitive v0.0.1
       Fresh png v0.3.1
       Fresh piston2d-sprite v0.14.0
       Fresh mmap v0.1.1
       Fresh gfx_device_gl v0.5.0
       Fresh sdl2 v0.9.1
       Fresh image v0.3.12
       Fresh wayland-kbd v0.2.0
       Fresh pistoncore-sdl2_window v0.13.0
       Fresh piston-gfx_texture v0.3.0
       Fresh glutin v0.3.5
       Fresh piston2d-gfx_graphics v0.9.0
       Fresh pistoncore-glutin_window v0.12.0
       Fresh piston_window v0.20.0
   Compiling piston-examples v0.0.0 (file:///home/dermetfan/documents/development/rust/piston-examples)
     Running `rustc src/texture_swap.rs --crate-name texture_swap --crate-type bin -g --out-dir /home/dermetfan/documents/development/rust/piston-examples/target/debug --emit=dep-info,link -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps --extern ai_behavior=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libai_behavior-c187fd481eefb02c.rlib --extern image=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libimage-be786b22ce00fa31.rlib --extern camera_controllers=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libcamera_controllers-0769ad16934a93c5.rlib --extern sdl2_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsdl2_window-ce150be33225003a.rlib --extern piston_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libpiston_window-20bf2651ff3b42bc.rlib --extern sprite=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsprite-a7a1cfcf2134d3b5.rlib --extern gfx_device_gl=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx_device_gl-6636b2e928090e69.rlib --extern vecmath=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libvecmath-7b01827101f36537.rlib --extern rand=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/librand-bdfcc55d3466feb3.rlib --extern find_folder=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libfind_folder-ea46062a64606452.rlib --extern gfx=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx-d474876570dc49a0.rlib --extern drag_controller=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libdrag_controller-5f136524f1122807.rlib -L native=/home/dermetfan/documents/development/rust/piston-examples/target/debug/build/miniz-sys-9343607e1ddc701d/out`
ERROR:rbml::reader: failed to find block with tag 56
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', src/librbml/lib.rs:395


Could not compile `piston-examples`.

Caused by:
  Process didn't exit successfully: `rustc src/texture_swap.rs --crate-name texture_swap --crate-type bin -g --out-dir /home/dermetfan/documents/development/rust/piston-examples/target/debug --emit=dep-info,link -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps --extern ai_behavior=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libai_behavior-c187fd481eefb02c.rlib --extern image=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libimage-be786b22ce00fa31.rlib --extern camera_controllers=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libcamera_controllers-0769ad16934a93c5.rlib --extern sdl2_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsdl2_window-ce150be33225003a.rlib --extern piston_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libpiston_window-20bf2651ff3b42bc.rlib --extern sprite=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsprite-a7a1cfcf2134d3b5.rlib --extern gfx_device_gl=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx_device_gl-6636b2e928090e69.rlib --extern vecmath=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libvecmath-7b01827101f36537.rlib --extern rand=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/librand-bdfcc55d3466feb3.rlib --extern find_folder=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libfind_folder-ea46062a64606452.rlib --extern gfx=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx-d474876570dc49a0.rlib --extern drag_controller=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libdrag_controller-5f136524f1122807.rlib -L native=/home/dermetfan/documents/development/rust/piston-examples/target/debug/build/miniz-sys-9343607e1ddc701d/out` (exit code: 101)
```

And finally with `RUST_BACKTRACE=1` and `--verbose`:

```
[nix-shell:~/documents/development/rust/piston-examples]$ RUST_BACKTRACE=1 cargo run --bin texture_swap --verbose
       Fresh pkg-config v0.3.5
       Fresh piston-texture v0.2.3
       Fresh khronos_api v0.0.5
       Fresh rustc-serialize v0.3.16
       Fresh khronos_api v0.0.8
       Fresh piston-shaders_graphics2d v0.1.0
       Fresh khronos_api v0.0.7
       Fresh lzw v0.8.0
       Fresh interpolation v0.1.0
       Fresh winapi v0.2.2
       Fresh libc v0.1.10
       Fresh color_quant v1.0.0
       Fresh winapi-build v0.1.1
       Fresh shader_version v0.2.1
       Fresh piston-float v0.1.0
       Fresh gcc v0.3.13
       Fresh find_folder v0.2.0
       Fresh lazy_static v0.1.14
       Fresh byteorder v0.3.13
       Fresh glob v0.2.10
       Fresh read_color v0.1.0
       Fresh bitflags v0.3.2
       Fresh bitflags v0.1.1
       Fresh dylib v0.0.1
       Fresh gl_common v0.0.4
       Fresh log v0.3.2
       Fresh clock_ticks v0.0.6
       Fresh dlib v0.1.1
       Fresh gif v0.5.0
       Fresh vecmath v0.1.1
       Fresh piston-viewport v0.1.0
       Fresh shared_library v0.1.0
       Fresh draw_state v0.2.0
       Fresh xml-rs v0.1.26
       Fresh x11-dl v2.0.1
       Fresh wayland-client v0.2.1
       Fresh quaternion v0.1.0
       Fresh pistoncore-input v0.5.1
       Fresh osmesa-sys v0.0.5
       Fresh piston2d-graphics v0.9.0
       Fresh gl_generator v0.0.26
       Fresh gl_generator v0.0.27
       Fresh advapi32-sys v0.1.2
       Fresh kernel32-sys v0.1.4
       Fresh piston3d-cam v0.1.0
       Fresh piston-ai_behavior v0.8.0
       Fresh pistoncore-window v0.9.1
       Fresh piston2d-drag_controller v0.7.0
       Fresh libz-sys v0.1.8
       Fresh miniz-sys v0.1.5
       Fresh rand v0.3.11
       Fresh camera_controllers v0.7.0
       Fresh pistoncore-event_loop v0.10.1
       Fresh freetype-sys v0.1.2
       Fresh flate2 v0.2.8
       Fresh tempdir v0.3.4
       Fresh uuid v0.1.17
       Fresh num v0.1.27
       Fresh tempfile v1.1.1
       Fresh piston v0.10.1
       Fresh freetype-rs v0.3.1
       Fresh gfx_gl v0.1.4
       Fresh gl v0.0.12
       Fresh mmap v0.1.1
       Fresh piston2d-sprite v0.14.0
       Fresh enum_primitive v0.0.1
       Fresh png v0.3.1
       Fresh gfx v0.7.0
       Fresh sdl2-sys v0.6.2
       Fresh wayland-window v0.1.0
       Fresh wayland-kbd v0.2.0
       Fresh image v0.3.12
       Fresh gfx_device_gl v0.5.0
       Fresh sdl2 v0.9.1
       Fresh glutin v0.3.5
       Fresh piston-gfx_texture v0.3.0
       Fresh pistoncore-sdl2_window v0.13.0
       Fresh pistoncore-glutin_window v0.12.0
       Fresh piston2d-gfx_graphics v0.9.0
   Compiling piston-examples v0.0.0 (file:///home/dermetfan/documents/development/rust/piston-examples)
     Running `rustc src/texture_swap.rs --crate-name texture_swap --crate-type bin -g --out-dir /home/dermetfan/documents/development/rust/piston-examples/target/debug --emit=dep-info,link -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps --extern gfx_device_gl=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx_device_gl-6636b2e928090e69.rlib --extern sprite=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsprite-a7a1cfcf2134d3b5.rlib --extern vecmath=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libvecmath-7b01827101f36537.rlib --extern find_folder=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libfind_folder-ea46062a64606452.rlib --extern ai_behavior=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libai_behavior-c187fd481eefb02c.rlib --extern image=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libimage-be786b22ce00fa31.rlib --extern gfx=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx-d474876570dc49a0.rlib --extern sdl2_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsdl2_window-ce150be33225003a.rlib --extern drag_controller=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libdrag_controller-5f136524f1122807.rlib --extern camera_controllers=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libcamera_controllers-0769ad16934a93c5.rlib --extern rand=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/librand-bdfcc55d3466feb3.rlib --extern piston_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libpiston_window-20bf2651ff3b42bc.rlib -L native=/home/dermetfan/documents/development/rust/piston-examples/target/debug/build/miniz-sys-9343607e1ddc701d/out`
       Fresh piston_window v0.20.0
ERROR:rbml::reader: failed to find block with tag 56
Could not compile `piston-examples`.

Caused by:
  Process didn't exit successfully: `rustc src/texture_swap.rs --crate-name texture_swap --crate-type bin -g --out-dir /home/dermetfan/documents/development/rust/piston-examples/target/debug --emit=dep-info,link -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug -L dependency=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps --extern gfx_device_gl=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx_device_gl-6636b2e928090e69.rlib --extern sprite=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsprite-a7a1cfcf2134d3b5.rlib --extern vecmath=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libvecmath-7b01827101f36537.rlib --extern find_folder=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libfind_folder-ea46062a64606452.rlib --extern ai_behavior=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libai_behavior-c187fd481eefb02c.rlib --extern image=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libimage-be786b22ce00fa31.rlib --extern gfx=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libgfx-d474876570dc49a0.rlib --extern sdl2_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libsdl2_window-ce150be33225003a.rlib --extern drag_controller=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libdrag_controller-5f136524f1122807.rlib --extern camera_controllers=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libcamera_controllers-0769ad16934a93c5.rlib --extern rand=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/librand-bdfcc55d3466feb3.rlib --extern piston_window=/home/dermetfan/documents/development/rust/piston-examples/target/debug/deps/libpiston_window-20bf2651ff3b42bc.rlib -L native=/home/dermetfan/documents/development/rust/piston-examples/target/debug/build/miniz-sys-9343607e1ddc701d/out` (signal: 11)
```

I figured I'd report a bug since that is what the error messages asked me to do.

## Meta

I'm running NixOS and here's the relevant part of my `~/nixpkgs/pkgs/top-level/rust-packages.nix` (which I used with `nix-shell -I nixpkgs=~/nixpkgs/` to enter the [nix-shell environment](http://nixos.org/nix/manual/#sec-nix-shell)):

```
# This file defines the source of Rust / cargo's crates registry
#
# buildRustPackage will automatically download dependencies from the registry
# version that we define here. If you're having problems downloading / finding
# a Rust library, try updating this to a newer commit.

{ runCommand, fetchFromGitHub, git }:

let
  version = "2015-09-15";
  rev = "120690580a8aa9b165520a4b290718b7b131d11e";

  src = fetchFromGitHub {
      inherit rev;

      owner = "rust-lang";
      repo = "crates.io-index";
      sha256 = "0j4wzlfi9cg73jqgx8lga1zchrgvynfi8xc46ls5286hca5i96gl";
  };

in
```

Here's my `default.nix` (used by `nix-shell`):

```
[nix-shell:~/documents/development/rust/piston-examples]$ cat default.nix 
with import <nixpkgs> { };
with rustUnstable;

buildRustPackage {
  name = "piston-examples";
  src = ./.;
  buildInputs = [ SDL2 SDL2_gfx SDL2_image SDL2_mixer SDL2_net SDL2_ttf freetype x11 ];
  depsSha256 = "";
}
```

Rust version:

```
[nix-shell:~/documents/development/rust/piston-examples]$ rustc --version --verbose
rustc 1.4.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.4.0-dev
```

Cargo version:

```
[nix-shell:~/documents/development/rust/piston-examples]$ cargo --version --verbose
cargo 0.3.0 ( ) (built 2015-09-14)
```

**Comment by Ticki** [comment]
I have the same problem.

**Comment by Ticki** [comment]
It appears to be solved by deleting the `target` folder, although I'm not sure what causes this problem.

**Comment by arielb1** [comment]
@Ticki 

the metadata format recently changed.

**Comment by Ticki** [comment]
I see.

**Comment by dermetfan** [comment]
Thanks!
