### ISSUE TITLE
rustdoc - panicked at 'Unexpected empty destination: ["dsp"]' - occurs on beta and nightly

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#28927]
Travis [is failing](https://travis-ci.org/RustAudio/dsp-chain/jobs/84483946) when running rustdoc on my dsp crate due to a panic occurring in rustdoc:

```
Compiling dsp-chain v0.7.1 (file:///home/travis/build/RustAudio/dsp-chain)
     Running `rustdoc src/lib.rs --crate-name dsp -o /home/travis/build/RustAudio/dsp-chain/target/doc -L dependency=/home/travis/build/RustAudio/dsp-chain/target/debug -L dependency=/home/travis/build/RustAudio/dsp-chain/target/debug/deps --extern num=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libnum-397f282c1d72fe58.rlib --extern num=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libnum-397f282c1d72fe58.rlib --extern sound_stream=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libsound_stream-96ca28702c32f71d.rlib --extern sound_stream=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libsound_stream-96ca28702c32f71d.rlib --extern daggy=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libdaggy-6c8daed9a0d833d9.rlib --extern daggy=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libdaggy-6c8daed9a0d833d9.rlib`
thread '<unnamed>' panicked at 'Unexpected empty destination: ["dsp"]', ../src/librustdoc/html/render.rs:1127
Could not document `dsp-chain`.
Caused by:
  Process didn't exit successfully: `rustdoc src/lib.rs --crate-name dsp -o /home/travis/build/RustAudio/dsp-chain/target/doc -L dependency=/home/travis/build/RustAudio/dsp-chain/target/debug -L dependency=/home/travis/build/RustAudio/dsp-chain/target/debug/deps --extern num=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libnum-397f282c1d72fe58.rlib --extern num=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libnum-397f282c1d72fe58.rlib --extern sound_stream=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libsound_stream-96ca28702c32f71d.rlib --extern sound_stream=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libsound_stream-96ca28702c32f71d.rlib --extern daggy=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libdaggy-6c8daed9a0d833d9.rlib --extern daggy=/home/travis/build/RustAudio/dsp-chain/target/debug/deps/libdaggy-6c8daed9a0d833d9.rlib` (exit code: 101)
The command "cargo doc --verbose" exited with 101.
```

He builds fine on the stable channel, but fails with the same error on both beta and nightly channels.

The line where the panic occurs seems to be [here](https://github.com/rust-lang/rust/blob/11a612795a8c93852fc1ed66118549e4dc6be99d/src/librustdoc/html/render.rs#L1142).

Unfortunately I only have stable available to me on my personal computer atm, and I don't have time to investigate much further.

**Comment by Eljay** [comment]
This seems to be caused by re-exporting crates, e.g:
```rust
extern crate foo;
pub use foo as bar;
```

Small repro project: https://github.com/Eljay/issue-28927
The regression from stable seems to be caused by #27643.

**Comment by mitchmindtree** [comment]
I'm still getting this same error on the current stable build of rust.

Here's the backtrace:

```
mindTree:dsp-chain Mitch$ RUST_BACKTRACE=1 cargo doc
 Documenting dsp-chain v0.10.0 (file:///Users/Mitch/Programming/Rust/dsp-chain)
thread '<unnamed>' panicked at 'Unexpected empty destination: ["dsp", "daggy"]', ../src/librustdoc/html/render.rs:1184
stack backtrace:
   1:        0x111601058 - sys::backtrace::tracing::imp::write::h06df28c2a8d245f9t9s
   2:        0x11160725f - panicking::log_panic::_<closure>::closure.39451
   3:        0x111606d02 - panicking::log_panic::h9348b1b0af36ae6aCYw
   4:        0x1115c8c86 - sys_common::unwind::begin_unwind_inner::h005d402245ebd8560cs
   5:        0x1115c962e - sys_common::unwind::begin_unwind_fmt::h440d2eb18c439fa86bs
   6:        0x10d85c166 - html::render::run::h42919733a08147f6xsn
   7:        0x10d8df047 - main_args::h9f2afc62a54ae9fbE2t
   8:        0x10d8da9f8 - sys_common::unwind::try::try_fn::try_fn::h7212718370687295260
   9:        0x1115fec08 - __rust_try
  10:        0x1115f2f8e - sys_common::unwind::try::inner_try::hcc3a84c80e36120fy9r
  11:        0x10d8daebe - boxed::_<impl>::call_box::call_box::h14966036215268722962
  12:        0x1116065ed - sys::thread::_<impl>::new::thread_start::h5776bf5f72f331a7Rvw
  13:     0x7fff889bf059 - _pthread_body
  14:     0x7fff889befd6 - _pthread_start
Could not document `dsp-chain`.

```

`rustc 1.5.0 (3d7cd77e4 2015-12-04)`

**Comment by mitchmindtree** [comment]
Ahh apologies, I see that this has been fixed in the latest nightly.
