### ISSUE TITLE
ICE when installing Rust 1.3.0 on El Capitano via homebrew

### ISSUE THREAD

**Issue by little-arhat** [rust-lang/rust#29052]
Error is:

```
Compiling crates-io v0.1.0 (file:///private/tmp/rust--cargo20151014-72976-7pfg6i)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to open archive") }) }', src/libcore/result.rs:732
Could not compile `libgit2-sys`.
```

Logs: 

```
==> Downloading https://static.rust-lang.org/dist/rustc-1.3.0-src.tar.gz
Already downloaded: /Library/Caches/Homebrew/rust-1.3.0.tar.gz
==> ./configure --prefix=/Users/user/.brew/Cellar/rust/1.3.0 --enable-clang --release-channel=stable
==> make
==> make install
==> Cloning https://github.com/rust-lang/cargo.git
Cloning into '/Library/Caches/Homebrew/rust--cargo--git'...
remote: Counting objects: 195, done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 195 (delta 15), reused 43 (delta 1), pack-reused 0
Receiving objects: 100% (195/195), 735.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (15/15), done.
Checking connectivity... done.
Note: checking out '8d21fd21a6b20056e9b5745e4e3f3b4279dc7fe4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag 0.5.0
==> Downloading https://static-rust-lang-org.s3.amazonaws.com/cargo-dist/2015-09-17/cargo-nightly-x86_64-apple-darwin.tar.gz
######################################################################## 100.0%
==> ./install.sh --prefix=/private/tmp/rust--cargo20151014-72976-7pfg6i/target/snapshot/cargo
==> ./configure --prefix=/Users/user/.brew/Cellar/rust/1.3.0 --local-rust-root=/Users/user/.brew/Cellar/rust/1.3.0 --enable-optimize
==> make
Last 15 lines from /Users/user/Library/Logs/Homebrew/rust/06.make:
   Compiling url v0.2.37
   Compiling toml v0.1.22
   Compiling curl v0.2.11
   Compiling crates-io v0.1.0 (file:///private/tmp/rust--cargo20151014-72976-7pfg6i)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to open archive") }) }', src/libcore/result.rs:732
```

sw_vers:

```
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284
```

**Comment by steveklabnik** [comment]
@little-arhat have you tried with 1.4? does it still ICE?

**Comment by little-arhat** [comment]
I have installed `multirust` and then nightly via it.

1.4 has been just successfully installed!

**Comment by steveklabnik** [comment]
Okay. I'm going to give this a close then, as it must have been some sort of transient thing. Thanks for reporting!
