### ISSUE TITLE
Compiling rust from git sources  with `RUSTFLAGS=-Ccodegen-units=4` will coredump.

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#29270]
Compiling rust from git sources  with `RUSTFLAGS=-Ccodegen-units=4` will coredump.

```
$ ./configure --prefix=/home/zazdxscf/build/1nonpkgs/rust/usr/local --enable-rpath --enable-manage-submodules --disable-clang --enable-ccache --enable-dist-host-only --disable-valgrind --disable-helgrind --disable-valgrind-rpass --python=/usr/bin/python2 --enable-optimize --enable-optimize-cxx --enable-optimize-llvm --enable-debug --enable-debuginfo --enable-debug-assertions --enable-debuginfo-tests --enable-llvm-assertions --enable-debug-jemalloc --disable-local-rust --release-channel=dev --host=x86_64-unknown-linux-gnu --target=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu
...
$ time RUST_LOG=rustc::metadata::loader make -j4 -- VERBOSE=1 TIME_PASSES=1 TIME_LLVM_PASSES=1 'RUSTFLAGS=--verbose -Z print-link-args -Z print-llvm-passes -C debug-assertions=y -Ccodegen-units=4' RUST_BACKTRACE=1
...
//coredump-ed here but rerunning command to see it better:

$ time RUST_LOG=rustc::metadata::loader make -j4 -- VERBOSE=1 TIME_PASSES=1 TIME_LLVM_PASSES=1 'RUSTFLAGS=--verbose -Z print-link-args -Z print-llvm-passes -C debug-assertions=y -Ccodegen-units=4' RUST_BACKTRACE=1
cfg: version 1.5.0-dev (d689182e5 2015-10-24)
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: enabling debug assertions (CFG_ENABLE_DEBUG_ASSERTIONS)
cfg: enabling debuginfo (CFG_ENABLE_DEBUGINFO)
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: good valgrind for x86_64-unknown-linux-gnu is 1
cfg: using CC=ccache gcc (CFG_CC)
cfg: disabling valgrind run-pass tests
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'libcore-*.so\' "libraries:" $MATCHES; rm $MATCHES ; fi
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'libcore-*.rlib\' "libraries:" $MATCHES; rm $MATCHES ; fi
CFG_LLVM_LINKAGE_FILE=/home/zazdxscf/build/1nonpkgs/rust/rust/x86_64-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/home/zazdxscf/build/1nonpkgs/rust/rust/x86_64-unknown-linux-gnu/stage0/lib:$LD_LIBRARY_PATH   x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0 --verbose -Z print-link-args -Z print-llvm-passes -C debug-assertions=y -Ccodegen-units=4 -O --cfg rtopt -C debug-assertions=on -Z time-passes -Z time-llvm-passes -C prefer-dynamic -C no-stack-check --target=x86_64-unknown-linux-gnu  -W warnings -L "x86_64-unknown-linux-gnu/rt" -L native="/home/zazdxscf/build/1nonpkgs/rust/rust/x86_64-unknown-linux-gnu/llvm/Release+Asserts/lib"     --out-dir x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib -C extra-filename=-bb943c5a src/libcore/lib.rs
time: 0.239; rss: 44MB  parsing
time: 0.079; rss: 45MB  configuration 1
time: 0.000; rss: 45MB  recursion limit
time: 0.007; rss: 45MB  gated macro checking
time: 0.000; rss: 45MB  crate injection
time: 0.003; rss: 45MB  macro loading
time: 0.000; rss: 45MB  plugin loading
time: 0.000; rss: 45MB  plugin registration
time: 1.432; rss: 73MB  expansion
time: 0.027; rss: 73MB  complete gated feature checking 1
time: 0.301; rss: 73MB  configuration 2
time: 0.152; rss: 73MB  maybe building test harness
time: 0.000; rss: 73MB  prelude injection
time: 0.014; rss: 73MB  checking that all macro invocations are gone
time: 0.028; rss: 73MB  complete gated feature checking 2
time: 0.170; rss: 79MB  assigning node ids and indexing ast
time: 0.015; rss: 79MB  external crate/lib resolution
time: 0.031; rss: 79MB  language item collection
time: 0.271; rss: 97MB  resolution
time: 0.028; rss: 94MB  lifetime resolution
time: 0.000; rss: 94MB  looking for entry point
time: 0.016; rss: 94MB  looking for plugin registrar
time: 0.109; rss: 105MB region resolution
time: 0.015; rss: 105MB loop checking
time: 0.014; rss: 105MB static item recursion checking
time: 0.219; rss: 111MB type collecting
time: 0.029; rss: 112MB variance inference
time: 2.161; rss: 123MB coherence checking
time: 16.785; rss: 169MB    type checking
time: 1.231; rss: 170MB const checking
time: 0.145; rss: 170MB privacy checking
time: 0.015; rss: 170MB stability index
time: 0.098; rss: 170MB intrinsic checking
time: 0.025; rss: 170MB effect checking
time: 0.353; rss: 170MB match checking
time: 0.059; rss: 170MB liveness checking
time: 2.403; rss: 170MB borrow checking
time: 1.208; rss: 170MB rvalue checking
time: 0.083; rss: 171MB reachability checking
time: 0.096; rss: 172MB death checking
time: 0.079; rss: 172MB stability checking
time: 0.000; rss: 172MB unused lib feature checking
src/libcore/lib.rs:82:12: 82:29 warning: unused or unknown feature, #[warn(unused_features)] on by default
src/libcore/lib.rs:82 #![feature(unwind_attributes)]
                                 ^~~~~~~~~~~~~~~~~
src/libcore/ptr.rs:21:11: 21:24 warning: unused import, #[warn(unused_imports)] on by default
src/libcore/ptr.rs:21 use ops::{CoerceUnsized, Deref};
                                ^~~~~~~~~~~~~
src/libcore/ptr.rs:25:52: 25:58 warning: unused import, #[warn(unused_imports)] on by default
src/libcore/ptr.rs:25 use marker::{Copy, PhantomData, Send, Sized, Sync, Unsize};
                                                                         ^~~~~~
src/libcore/panicking.rs:65:9: 65:18 warning: unused attribute, #[warn(unused_attributes)] on by default
src/libcore/panicking.rs:65         #[unwind]
                                    ^~~~~~~~~
time: 1.503; rss: 172MB lint checking
time: 0.000; rss: 172MB resolving dependency formats
time: 6.517; rss: 302MB translation
Pass Arguments: Pass Arguments:  -tti -targetlibinfo -no-aa -tbaa -scoped-noalias -assumption-cache-tracker -basicaa -verify -simplifycfg -domtree -sroa -early-cse -lower-expect
Target Transform Information
Target Library Information
No Alias Analysis (always returns 'may' alias)
Type-Based Alias Analysis
Scoped NoAlias Alias Analysis
Assumption Cache Tracker
Basic Alias Analysis (stateless AA impl)
  FunctionPass Manager
    Module Verifier
    Simplify the CFG
    Dominator Tree Construction
    SROA
    Early CSE
    Lower 'expect' Intrinsics
Pass Arguments:  -tti -targetlibinfo -no-aa -tbaa -scoped-noalias -assumption-cache-tracker -basicaa -verify -simplifycfg -domtree -sroa -early-cse -lower-expect
Target Transform Information
Target Library Information
No Alias Analysis (always returns 'may' alias)
Type-Based Alias Analysis
Scoped NoAlias Alias Analysis
Assumption Cache Tracker
Basic Alias Analysis (stateless AA impl)
  FunctionPass Manager
    Module Verifier
    Simplify the CFG
    Dominator Tree Construction
    SROA
    Early CSE
    Lower 'expect' Intrinsics
 -tti -targetlibinfo -no-aa -tbaa -scoped-noalias -assumption-cache-tracker -basicaa -verify -simplifycfg -domtree -sroa -early-cse -lower-expect
Target Transform Information
Target Library Information
No Alias Analysis (always returns 'may' alias)
Type-Based Alias Analysis
Scoped NoAlias Alias Analysis
Assumption Cache Tracker
Basic Alias Analysis (stateless AA impl)
  FunctionPass Manager
    Module Verifier
    Simplify the CFG
    Dominator Tree Construction
    SROA
    Early CSE
    Lower 'expect' Intrinsics
/home/zazdxscf/build/1nonpkgs/rust/rust/mk/target.mk:164: recipe for target 'x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.core' failed
make: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.core] Killed (core dumped)

real    0m41.107s
user    0m36.047s
sys 0m3.873s
```

Using gdb on core and the exe x86_64-unknown-linux-gnu/stage0/bin/rustc

``` bash
$ LD_LIBRARY_PATH=/home/zazdxscf/build/1nonpkgs/rust/rust/x86_64-unknown-linux-gnu/stage0/lib coredump_to_backtrace   x86_64-unknown-linux-gnu/stage0/bin/rustc ./core all >~/logs/rust_crash_backtrace_full.log 2>&1 

$ cat ~/logs/rust_crash_backtrace_full.log
2 -ex thread apply all bt full
3 -ex quit --batch
[New LWP 19483]
[New LWP 19485]
[New LWP 19486]
[New LWP 19122]
[New LWP 19123]
[New LWP 19484]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0 --verbose -Z print-link-'.
Program terminated with signal SIGKILL, Killed.
#0  0x0000005f12932774 in (anonymous namespace)::EarlyCSELegacyPass::ID ()
[Current thread is 1 (Thread 0x315242cf700 (LWP 19483))]

Thread 6 (Thread 0x3151bb14700 (LWP 19484)):
#0  0x0000005f1160e495 in (anonymous namespace)::Verifier::visitFunction(llvm::Function const&) ()
No symbol table info available.
#1  0x0000005f1161b40b in (anonymous namespace)::Verifier::verify(llvm::Function const&) ()
No symbol table info available.
#2  0x0000005f1161b4fd in (anonymous namespace)::VerifierLegacyPass::runOnFunction(llvm::Function&) ()
No symbol table info available.
#3  0x0000005f115df4e3 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
No symbol table info available.
#4  0x0000005f115df65c in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) ()
No symbol table info available.
#5  0x0000005f115df82f in llvm::legacy::FunctionPassManager::run(llvm::Function&) ()
No symbol table info available.
#6  0x0000005f10cdde10 in LLVMRustRunFunctionPassManager (PM=0x3150c0008f0, M=0x3152c01a090) at /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/rustllvm/PassWrapper.cpp:207
        I = {<std::iterator<std::bidirectional_iterator_tag, llvm::Function, long, llvm::Function*, llvm::Function&>> = {<No data fields>}, NodePtr = 0x3152c023908}
        E = {<std::iterator<std::bidirectional_iterator_tag, llvm::Function, long, llvm::Function*, llvm::Function&>> = {<No data fields>}, NodePtr = 0x3152c01a070}
#7  0x0000005f10317784 in back::write::execute_work_item::hccf81336d64618b9NZd ()
No symbol table info available.
#8  0x0000005f1031bbef in boxed::F.FnBox$LT$A$GT$::call_box::h15988861949149214809 ()
No symbol table info available.
#9  0x0000005f1031b3b5 in rt::unwind::try::try_fn::h12548014035612796083 ()
No symbol table info available.
#10 0x0000005f11d55309 in __rust_try ()
No symbol table info available.
#11 0x0000005f11d47bc3 in rt::unwind::try::inner_try::ha3b130acdaf96544aWw ()
No symbol table info available.
#12 0x0000005f1031b559 in boxed::F.FnBox$LT$A$GT$::call_box::h4221393651147923897 ()
No symbol table info available.
#13 0x0000005f11d546f4 in sys::thread::Thread::new::thread_start::h3819a1565b813297A5v ()
No symbol table info available.
#14 0x0000031534aa864c in start_thread (arg=0x3151bb14700) at pthread_create.c:334
        __res = <optimized out>
        pd = 0x3151bb14700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {3389193799424, 3924466253662624026, 3389588385376, 3389588384831, 0, 3389588385376, 3924466253683595546, 3924569817357719834}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#15 0x0000031533eca9bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 5 (Thread 0x3153336b700 (LWP 19123)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x0000005f11d32a2e in thread::park::hfd71a0d44abbc824jCb ()
No symbol table info available.
#2  0x0000005f11d4e313 in sync::mpsc::blocking::WaitToken::wait::h6616f6c632d0e9b1Czm ()
No symbol table info available.
#3  0x0000005f103141e0 in back::write::run_work_multithreaded::hec567ce15e5c7e0e40d ()
No symbol table info available.
#4  0x0000005f10311a88 in back::write::run_passes::he948175407aa67481Kd ()
No symbol table info available.
#5  0x0000005f102278c8 in driver::phase_5_run_llvm_passes::hc8c4832ac88b1937QPa ()
No symbol table info available.
#6  0x0000005f101fb726 in driver::compile_input::h37859d56374280caTba ()
No symbol table info available.
#7  0x0000005f102db947 in run_compiler::h86a39f47860f70c7C7b ()
No symbol table info available.
#8  0x0000005f102d96ca in boxed::F.FnBox$LT$A$GT$::call_box::h15702049526784006720 ()
No symbol table info available.
#9  0x0000005f102d90a5 in rt::unwind::try::try_fn::h2747471524830943407 ()
No symbol table info available.
#10 0x0000005f11d55309 in __rust_try ()
No symbol table info available.
#11 0x0000005f11d47bc3 in rt::unwind::try::inner_try::ha3b130acdaf96544aWw ()
No symbol table info available.
#12 0x0000005f102d9249 in boxed::F.FnBox$LT$A$GT$::call_box::h2060115051421633638 ()
No symbol table info available.
#13 0x0000005f11d546f4 in sys::thread::Thread::new::thread_start::h3819a1565b813297A5v ()
No symbol table info available.
#14 0x0000031534aa864c in start_thread (arg=0x3153336b700) at pthread_create.c:334
        __res = <optimized out>
        pd = 0x3153336b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {3389588420352, 3924553154272794906, 3896555126480, 3896555125935, 0, 3896555126480, 3924553154293766426, 3924569817357719834}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#15 0x0000031533eca9bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 4 (Thread 0x31534ebca40 (LWP 19122)):
#0  0x0000031534aa99ad in pthread_join (threadid=3389588420352, thread_return=0x0) at pthread_join.c:90
        __tid = 19123
        _buffer = {__routine = 0x31534aa98d0 <cleanup>, __arg = 0x3153336bd28, __canceltype = 0, __prev = 0x0}
        oldtype = 0
        pd = 0x3153336b700
        self = 0x31534ebca40
        result = 0
#1  0x0000005f102d7b6d in run::hc1a284b3d5df13aei7b ()
No symbol table info available.
#2  0x0000005f102e9bc6 in main::h183edcfa8c3946b0gfd ()
No symbol table info available.
#3  0x0000005f11d57765 in rt::unwind::try::try_fn::h4880324144649223239 ()
No symbol table info available.
#4  0x0000005f11d55309 in __rust_try ()
No symbol table info available.
#5  0x0000005f11d5741c in rt::lang_start::h74469c6250afc3c4Ttx ()
No symbol table info available.
#6  0x0000031533df56a4 in __libc_start_main (main=0x5f101f9ff0 <main>, argc=36, argv=0x38b3cc8ccb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x38b3cc8cca8) at libc-start.c:289
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 3984225176103524634, 408321314656, 3896555130032, 0, 0, 3984225176128690458, 3924554606186436890}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x31534ee3148, 0x1c}, data = {prev = 0x0, cleanup = 0x0, canceltype = 888025416}}}
        not_first_call = <optimized out>
#7  0x0000005f101f9e99 in _start ()
No symbol table info available.

Thread 3 (Thread 0x3151b611700 (LWP 19486)):
#0  _wordcopy_fwd_aligned (dstp=<optimized out>, srcp=<optimized out>, len=2305843009213670472) at wordcopy.c:110
        a0 = 0
        a1 = 0
#1  0x0000031533e60eb4 in __memmove_sse2 (dest=0x31514004620, src=<optimized out>, len=18446744073709551608) at ../string/memmove.c:78
        dstp = <optimized out>
        srcp = <optimized out>
#2  0x0000005f11652734 in llvm::Timer::stopTimer() ()
No symbol table info available.
#3  0x0000005f115dc11c in llvm::PMDataManager::freePass(llvm::Pass*, llvm::StringRef, llvm::PassDebuggingString) ()
No symbol table info available.
#4  0x0000005f115dc4ab in llvm::PMDataManager::removeDeadPasses(llvm::Pass*, llvm::StringRef, llvm::PassDebuggingString) ()
No symbol table info available.
#5  0x0000005f115df423 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
No symbol table info available.
#6  0x0000005f115df65c in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) ()
No symbol table info available.
#7  0x0000005f115df82f in llvm::legacy::FunctionPassManager::run(llvm::Function&) ()
No symbol table info available.
#8  0x0000005f10cdde10 in LLVMRustRunFunctionPassManager (PM=0x315040008f0, M=0x3152c013a10) at /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/rustllvm/PassWrapper.cpp:207
        I = {<std::iterator<std::bidirectional_iterator_tag, llvm::Function, long, llvm::Function*, llvm::Function&>> = {<No data fields>}, NodePtr = 0x3152c03f2d8}
        E = {<std::iterator<std::bidirectional_iterator_tag, llvm::Function, long, llvm::Function*, llvm::Function&>> = {<No data fields>}, NodePtr = 0x3152c0139f0}
#9  0x0000005f10317784 in back::write::execute_work_item::hccf81336d64618b9NZd ()
No symbol table info available.
#10 0x0000005f1031bbef in boxed::F.FnBox$LT$A$GT$::call_box::h15988861949149214809 ()
No symbol table info available.
#11 0x0000005f1031b3b5 in rt::unwind::try::try_fn::h12548014035612796083 ()
No symbol table info available.
#12 0x0000005f11d55309 in __rust_try ()
No symbol table info available.
#13 0x0000005f11d47bc3 in rt::unwind::try::inner_try::ha3b130acdaf96544aWw ()
No symbol table info available.
#14 0x0000005f1031b559 in boxed::F.FnBox$LT$A$GT$::call_box::h4221393651147923897 ()
No symbol table info available.
#15 0x0000005f11d546f4 in sys::thread::Thread::new::thread_start::h3819a1565b813297A5v ()
No symbol table info available.
#16 0x0000031534aa864c in start_thread (arg=0x3151b611700) at pthread_create.c:334
        __res = <optimized out>
        pd = 0x3151b611700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {3389188544256, 3924465840808892698, 3389588385376, 3389588384831, 0, 3389588385376, 3924465840829864218, 3924569817357719834}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#17 0x0000031533eca9bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 2 (Thread 0x3151b905700 (LWP 19485)):
#0  0x0000005f115d5d47 in non-virtual thunk to llvm::legacy::PassManagerImpl::getTopLevelPassManagerType() ()
No symbol table info available.
#1  0x0000005f115dfa46 in llvm::PMTopLevelManager::schedulePass(llvm::Pass*) ()
No symbol table info available.
#2  0x0000005f115dfd6d in llvm::PMTopLevelManager::schedulePass(llvm::Pass*) ()
No symbol table info available.
#3  0x0000005f10d5a8c7 in llvm::PassManagerBuilder::populateModulePassManager(llvm::legacy::PassManagerBase&) ()
No symbol table info available.
#4  0x0000005f1030e61a in back::write::with_llvm_pmb::h5cf3eca4ffe4df7bQce ()
No symbol table info available.
#5  0x0000005f10317467 in back::write::execute_work_item::hccf81336d64618b9NZd ()
No symbol table info available.
#6  0x0000005f1031bbef in boxed::F.FnBox$LT$A$GT$::call_box::h15988861949149214809 ()
No symbol table info available.
#7  0x0000005f1031b3b5 in rt::unwind::try::try_fn::h12548014035612796083 ()
No symbol table info available.
#8  0x0000005f11d55309 in __rust_try ()
No symbol table info available.
#9  0x0000005f11d47bc3 in rt::unwind::try::inner_try::ha3b130acdaf96544aWw ()
No symbol table info available.
#10 0x0000005f1031b559 in boxed::F.FnBox$LT$A$GT$::call_box::h4221393651147923897 ()
No symbol table info available.
#11 0x0000005f11d546f4 in sys::thread::Thread::new::thread_start::h3819a1565b813297A5v ()
No symbol table info available.
#12 0x0000031534aa864c in start_thread (arg=0x3151b905700) at pthread_create.c:334
        __res = <optimized out>
        pd = 0x3151b905700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {3389191640832, 3924465967510427930, 3389588385376, 3389588384831, 0, 3389588385376, 3924465967531399450, 3924569817357719834}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#13 0x0000031533eca9bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 1 (Thread 0x315242cf700 (LWP 19483)):
#0  0x0000005f12932774 in (anonymous namespace)::EarlyCSELegacyPass::ID ()
No symbol table info available.
#1  0x0000005f115dac36 in llvm::PMDataManager::removeNotPreservedAnalysis(llvm::Pass*) ()
No symbol table info available.
#2  0x0000005f115df3e5 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
No symbol table info available.
#3  0x0000005f115df65c in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) ()
No symbol table info available.
#4  0x0000005f115df82f in llvm::legacy::FunctionPassManager::run(llvm::Function&) ()
No symbol table info available.
#5  0x0000005f10cdde10 in LLVMRustRunFunctionPassManager (PM=0x315140008f0, M=0x3152c01d3a0) at /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/rustllvm/PassWrapper.cpp:207
        I = {<std::iterator<std::bidirectional_iterator_tag, llvm::Function, long, llvm::Function*, llvm::Function&>> = {<No data fields>}, NodePtr = 0x3152c0abf08}
        E = {<std::iterator<std::bidirectional_iterator_tag, llvm::Function, long, llvm::Function*, llvm::Function&>> = {<No data fields>}, NodePtr = 0x3152c01d380}
#6  0x0000005f10317784 in back::write::execute_work_item::hccf81336d64618b9NZd ()
No symbol table info available.
#7  0x0000005f1031bbef in boxed::F.FnBox$LT$A$GT$::call_box::h15988861949149214809 ()
No symbol table info available.
#8  0x0000005f1031b3b5 in rt::unwind::try::try_fn::h12548014035612796083 ()
No symbol table info available.
#9  0x0000005f11d55309 in __rust_try ()
No symbol table info available.
#10 0x0000005f11d47bc3 in rt::unwind::try::inner_try::ha3b130acdaf96544aWw ()
No symbol table info available.
#11 0x0000005f1031b559 in boxed::F.FnBox$LT$A$GT$::call_box::h4221393651147923897 ()
No symbol table info available.
#12 0x0000005f11d546f4 in sys::thread::Thread::new::thread_start::h3819a1565b813297A5v ()
No symbol table info available.
#13 0x0000031534aa864c in start_thread (arg=0x315242cf700) at pthread_create.c:334
        __res = <optimized out>
        pd = 0x315242cf700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {3389336123136, 3924603918638749978, 3389588385376, 3389588384831, 0, 3389588385376, 3924603918659721498, 3924569817357719834}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#14 0x0000031533eca9bd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

**Comment by alexcrichton** [comment]
Make's gone now, so closing.
