### ISSUE TITLE
OSX make check failure

### ISSUE THREAD

**Issue by dagit** [rust-lang/rust#29389]
At commit:
```
commit 0b9edc77c57c86c49cf8413b1022f1279e7f3f38
Merge: 7de9c4e 315f762
Author: bors <bors@rust-lang.org>
Date:   Mon Oct 26 13:58:50 2015 +0000

    Auto merge of #29280 - Ryman:bad_docattr, r=Manishearth

    As is, this attr would lead to the "///" prefix being in the output text.
```

Running `make all check` on my mac (OSX 10.11), I get the following:
```
failures:

---- [run-pass] run-pass/sepcomp-lib-lto.rs stdout ----

error: compilation failed!
status: signal: 6
command: x86_64-apple-darwin/stage2/bin/rustc /Users/dagit/local-data/rust-lang-compiler/src/test/run-pass/sepcomp-lib-lto.rs -L x86_64-apple-darwin/test/run-pass/ --target=x86_64-apple-darwin -L x86_64-apple-darwin/test/run-pass/sepcomp-
lib-lto.stage2-x86_64-apple-darwin.run-pass.libaux -o x86_64-apple-darwin/test/run-pass/sepcomp-lib-lto.stage2-x86_64-apple-darwin -O -L x86_64-apple-darwin/rt -C lto
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
Assertion failed: (Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."), function getOrCreateTypeDIE, file /Users/dagit/local-data/rust-lang-compiler/src/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp, line 713.

------------------------------------------

thread '[run-pass] run-pass/sepcomp-lib-lto.rs' panicked at 'explicit panic', /Users/dagit/local-data/rust-lang-compiler/src/compiletest/runtest.rs:1501
stack backtrace:
   1:        0x100d3a450 - sys::backtrace::tracing::imp::write::hf107b98e309f98bft9s
   2:        0x100d5c8e4 - panicking::log_panic::_<closure>::closure.40016
   3:        0x100d5c0ac - panicking::log_panic::he9f044d8ca42048bCYw
   4:        0x100d34932 - panicking::on_panic::hc93f040068d0d07d61w
   5:        0x100ca595c - sys_common::unwind::begin_unwind_inner::h774e2b0f9a1d64090cs
   6:        0x1007c34e7 - sys_common::unwind::begin_unwind::begin_unwind::h6224335352308574802
   7:        0x1007e679f - runtest::fatal_proc_rec::heffa25f44077935cSFc
   8:        0x1007db7ce - runtest::run_rpass_test::h3812af752db29e14hWa
   9:        0x1007daa71 - runtest::run::h1a9ed2eedc86af97tLa
  10:        0x100828c90 - make_test_closure::_<closure>::closure.13217
  11:        0x100828d67 - boxed::_<impl>::call_box::call_box::h15507799779027141966
  12:        0x100921a4b - boxed::_<impl>::call_once::call_once::h17133247396099640213
  13:        0x100920b58 - run_test::run_test_inner::_<closure>::_<closure>::closure.12002
  14:        0x100920472 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.11991
  15:        0x100920409 - sys_common::unwind::try::try_fn::try_fn::h12033109523930689998
  16:        0x100d341c2 - __rust_try
  17:        0x100d34001 - sys_common::unwind::try::inner_try::_<closure>::closure.39120
  18:        0x100d33ca2 - thread::local::_<impl>::with::h10217896450654346749
  19:        0x100d10934 - sys_common::unwind::try::inner_try::h3234ba98b10d90bdy9r
  20:        0x10092037b - sys_common::unwind::try::try::h326227057172652928
  21:        0x1009201cb - std::thread::_<impl>::spawn::_<closure>::closure.11988
  22:        0x100920d44 - boxed::_<impl>::call_box::call_box::h11575122192980029640
  23:        0x100d2578b - boxed::_<impl>::call_once::call_once::h4961840585078401157
  24:        0x100d31088 - sys_common::thread::start_thread::h368cfc97332a192fgWr
  25:        0x100d5a8d8 - sys::thread::_<impl>::new::thread_start::__rust_abi
  26:        0x100d5a874 - sys::thread::_<impl>::new::thread_start::hfe91e9edabc12009Rvw
  27:     0x7fff91ccf9b0 - _pthread_body
  28:     0x7fff91ccf92d - _pthread_start

failures:
    [run-pass] run-pass/sepcomp-lib-lto.rs

test result: FAILED. 2268 passed; 1 failed; 3 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/dagit/local-data/rust-lang-compiler/src/compiletest/compiletest.rs:246
stack backtrace:
   1:        0x100d3a450 - sys::backtrace::tracing::imp::write::hf107b98e309f98bft9s
   2:        0x100d5c8e4 - panicking::log_panic::_<closure>::closure.40016
   3:        0x100d5c0e0 - panicking::log_panic::he9f044d8ca42048bCYw
   4:        0x100d34932 - panicking::on_panic::hc93f040068d0d07d61w
   5:        0x100ca595c - sys_common::unwind::begin_unwind_inner::h774e2b0f9a1d64090cs
   6:        0x1007c34e7 - sys_common::unwind::begin_unwind::begin_unwind::h6224335352308574802
   7:        0x10081eea5 - run_tests::hb18f11d1306a4e04bZd
   8:        0x100816f55 - main::hf9201a0ffb9d2d5bayd
   9:        0x100d5bb22 - fn()::fn_pointer_shim.40005::ha2b1253da0575b48
  10:        0x100d5b91d - thread::catch_panic::_<closure>::closure.40000
  11:        0x100d5b8f1 - sys_common::unwind::try::try_fn::h9850555208666536251
  12:        0x100d341c2 - __rust_try
  13:        0x100d34001 - sys_common::unwind::try::inner_try::_<closure>::closure.39120
  14:        0x100d33ca2 - thread::local::_<impl>::with::h10217896450654346749
  15:        0x100d10934 - sys_common::unwind::try::inner_try::h3234ba98b10d90bdy9r
  16:        0x100d5b898 - sys_common::unwind::try::h14811681286345342057
  17:        0x100d5b6e4 - thread::catch_panic::h3729940494774802947
  18:        0x100d5b5c8 - rt::lang_start::h485de80a76209824KVw
  19:        0x10081f0e9 - main
make: *** [tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rpass.ok] Error 101
make all check  15936.39s user 382.28s system 145% cpu 3:06:49.88 total
```

**Comment by Manishearth** [comment]
cc @dotdash

**Comment by dagit** [comment]
Looks like the failure happens in DwarfUnit.cpp:

```
$ x86_64-apple-darwin/stage2/bin/rustc /Users/dagit/local-data/rust-lang-compiler/src/test/run-pass/sepcomp-lib-lto.rs -L x86_64-apple-darwin/test/run-pass/ --target=x86_64-apple-darwin -L x86_64-apple-darwin/test/run-pass/sepcomp-lib-lto.stage2-x86_64-apple-darwin.run-pass.libaux -o x86_64-apple-darwin/test/run-pass/sepcomp-lib-lto.stage2-x86_64-apple-darwin -O -L x86_64-apple-darwin/rt -C lto
Assertion failed: (Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."), function getOrCreateTypeDIE, file /Users/dagit/local-data/rust-lang-compiler/src/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp, line 713.
zsh: abort      x86_64-apple-darwin/stage2/bin/rustc  -L x86_64-apple-darwin/test/run-pass/
```

**Comment by sanxiyn** [comment]
This seems to be #25270. What did you pass to ./configure?

**Comment by dagit** [comment]
I think you're right. I enabled debug too.
