### ISSUE TITLE
println! sometimes panics in drop methods

### ISSUE THREAD

**Issue by sorear** [rust-lang/rust#29488]
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/issues/29488)*

If you try to println!-debug a drop method in a type which is being used in TLS, you can have problems because the TLS variable which holds the local stdout might already have been destroyed, turning your innocent print into a panic with "cannot access a TLS value during or after it is destroyed".  This seems unnecessarily user-hostile.

(I solved the bug in my code, but I'm kinda curious what the recommended way to trace a drop method is.  rt::util::dumb_print?)

**Comment by nagisa** [comment]
The issue here is that we initialise TLS variables lazily (AFAIR), but they still get dropped in order. If you happen to initialise your droppable type before whatever `println!` stores in the TLS, you will encounter this error.

A simple solution would be to somehow ensure that types which depend on TLS in their `Drop` get initialised latest… Sadly we do not have any means to figure out such dependencies.

**Comment by alexcrichton** [comment]
Sounds bad! I think we just need to add a check to see if TLS is already destroyed: https://github.com/rust-lang/rust/pull/29491

**Comment by ranma42** [comment]
@nagisa I am afraid that we do not have any kind of guarantee about the order in which TLS variables are destroyed.

@alexcrichton We might also want to sanitise std to ensure that this issue does not affect other code. This has already been done for stderr and thread_info and it is now being done to stdout.
AFAICT `thread_local!" is also used in `src/libstd/rand/mod.rs`; I guess it is not very likely to call it directly from a `Drop` implementation, but it could still happen if some (complex) data structures were using while dropping.

**Comment by alexcrichton** [comment]
That's a good point about an audit! We probably don't need to worry much about rand as it's not an exported interface of the standard library, however, but probably good to fixup nonetheless!

**Comment by da-x** [comment]
If I improve the test case by adding: `FOO.with(|_| {});` as the first line in `main()`, I get:

```
thread 'main' panicked at 'cannot access stdout during shutdown', src/libcore/option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

(rustc 1.23.0)

It's the same if I add another FOO2 : Foo TLS and access it from main in the same way.

My question is, shouldn't `stdout` handling in TLS be symmetrical with regard to the main thread compared to threads created during runtime? @alexcrichton

**Comment by DustinByfuglien** [comment]
Applications continue panic while using TLS/println:
```
struct Foo {}

impl Drop for Foo {
    fn drop(&mut self) {
        println!("drop begin");
    }
}


thread_local! {
    static FOO: Foo = Foo{};
}


fn main() {
    println!("main begin");
    FOO.with(|_| {});
}

```
This code output is:
```
main begin
thread '<unnamed>' panicked at 'cannot access stdout during shutdown', libcore\option.rs:916:5
```

May be it also must be fixed in Rust language?

**Comment by pietroalbini** [comment]
Seems like this is happening again?

**Comment by sfackler** [comment]
> My question is, shouldn't stdout handling in TLS be symmetrical with regard to the main thread compared to threads created during runtime?

We don't control the TLS implementation unfortunately.

**Comment by DustinByfuglien** [comment]
Bug is critical as rust is panic. I think the `I-ICE` label must be added.
But I have no privilegies for this.
Can someone add `I-ICE` please?

**Comment by DustinByfuglien** [comment]
Thanks.
It seems this issue is related to [another old one](https://github.com/rust-lang/rust/issues/28129#issue-104099188).

**Comment by alexcrichton** [comment]
Assigning P-medium, would be great to fix but not super-high-priority

**Comment by DustinByfuglien** [comment]
I think is quite high priority.
I want to use private TLS-variables in a library.
How can I gracefuly drop this variables? I don't know a method.

Without this I can't develop my applications based on this library.
Tell me please if you know a method.

**Comment by sfackler** [comment]
Why do you need to print in the destructor of your type?

**Comment by DustinByfuglien** [comment]
Due to debugging and logging needs.

**Comment by DustinByfuglien** [comment]
I think a fact that drop trait is not working is not a println! issue. Without println! TLS-drop don't work as expected too.

Windows7x64

**Comment by DustinByfuglien** [comment]
Let's see an example without println!
TLS-drop function try to use c++ external function lib_fun() that writes to stdout.
Expected that this app must write `from C++: 23`
But it don't write anything:

main.rs:
```
use std::os::raw::c_int;

#[link(name = "Project1", kind="static")]
extern {
    pub fn lib_fun(i: c_int) -> c_int;
}

struct Foo {}

impl Drop for Foo {
    fn drop(&mut self) {
        unsafe {
            lib_fun(23);
        }
    }
}

thread_local! {
    static FOO: Foo = Foo {};
}

fn main() {}
```

Project1.cpp:
```
#include <stdio.h>

extern "C" {
	int lib_fun(int t) {
		printf("from C++: %d\r\n", t);
		fflush(stdout);
		return t;
	}
}

```

**Comment by sfackler** [comment]
Some platforms do not run TLS destructors on the main thread. We have no control over that behavior.

**Comment by DustinByfuglien** [comment]
In my C++ project on this platform I freely used TLS variables destructors in main thread without errors.
I assume Rust must doing this well too.

**Comment by sfackler** [comment]
@DustinByfuglien that is #28129, not this issue.

**Comment by DustinByfuglien** [comment]
Both issues are platform-depending. I will not wonder if this issues may have a one internal cause.
But if this issues have dufferent causes than there is prefferable for my to see that both are solved in near future. Without they are fixed  I don'tknow how to write apps with TLS in Rust on my platform.

**Comment by ArtemGr** [comment]
> Why do you need to print in the destructor of your type?

I have a peculiar use case there in that the test framework (cargo test) will only capture the output from the main test thread, so we're gathering the logs from the other threads and then emit them (via the `println!`s) in a `Drop` of a RAII variable living inside the test, in order to ensure that the logs are printed even if the test panics.

**Comment by Ciantic** [comment]
> BTW, adding catch_unwind around the println! statement seems to work as a workaround.

I tried this:

```rust
std::panic::catch_unwind(|| {
    println!("Something");
});
```

That doesn't work for me. I need to remove all `println!` in `drop` implementations if I want to remove these errors.

**Comment by joboet** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/77154, which also added a test for the `println!`-during-shutdown scenario. The trick was to merely disable buffering instead of preventing all access to stdout.
