### ISSUE TITLE
Content of enum docblock not ignored in tests

### ISSUE THREAD

**Issue by daschl** [rust-lang/rust#29771]
Hi folks, I'm on rustc 1.4 (rustc 1.4.0 (8ab8581f6 2015-10-27).

**edit:** see [below](https://github.com/rust-lang/rust/issues/29771#issuecomment-156429608) for a much simpler and reduced test case.
I have the following FFI file which I'm developing, that works without issues (other than described below):

```rust
use libc::{c_int, c_uint, c_ulonglong};

pub enum HwlocTopology {}

#[repr(u32)]
#[derive(Debug,PartialEq)]
pub enum ObjectType {
	/// The whole system that is accessible to hwloc. That may comprise several 
	/// machines in SSI systems like Kerrighed.
	System,
	/// The typical root object type. A set of processors and memory with cache 
	/// coherency.
	Machine,
	/// A set of processors around memory which the processors can directly 
	/// access.
	NUMANode,
	/// Physical package, what goes into a socket. In the physical meaning, 
	/// i.e. that you can add or remove physically.
	Package,
	/// The Cache. Can be L1i, L1d, L2, L3,...
	Cache,
	/// A computation unit (may be shared by several logical processors).
	Core,
	/// Processing Unit, or (Logical) Processor.
	///
	/// An execution unit (may share a core with some other logical 
	/// processors, e.g. in the case of an SMT core). Objects of this kind 
	/// are always reported and can thus be used as fallback when others are 
	/// not.
	PU,
	/// Group objects.
	///
	///	Objects which do not fit in the above but are detected by hwloc and 
	/// are useful to take into account for affinity. For instance, some 
	/// operating systems expose their arbitrary processors aggregation this
	/// way. And hwloc may insert such objects to group NUMA nodes according 
	/// to their distances.
	///
	/// These objects are ignored when they do not bring any structure.
	Group,
	/// Miscellaneous objects.
	///
	/// Objects without particular meaning, that can e.g. be
	/// added by the application for its own use, or by hwloc
	/// for miscellaneous objects such as MemoryModule (DIMMs).
	Misc,
	/// Any bridge that connects the host or an I/O bus, to another I/O bus.
	///
	/// Bridge objects have neither CPU sets nor node sets.
	/// They are not added to the topology unless I/O discovery
	/// is enabled through the custom flags.
	Bridge,
	/// PCI device.
	///
	/// These objects have neither CPU sets nor node sets.
	/// They are not added to the topology unless I/O discovery
	/// is enabled through the custom flags.
	PCIDevice,
	/// Operating system device.
	///	
	/// These objects have neither CPU sets nor node sets. They are not 
	/// added to the topology unless I/O discovery is enabled 
	/// through the custom flags.
	OSDevice,
	/// An internal sentinel value.
	TypeMax,
}

#[derive(Debug,PartialEq)]
pub enum TypeDepthError {
	/// HWLOC returned a depth error which is not known to the rust binding.
	UnkownTypeDepthError,
	/// No object of given type exists in the topology.
	TypeDepthUnknown,
	/// Objects of given type exist at different depth in the topology.
	TypeDepthMultiple,
	/// Virtual depth for bridge object level.
	TypeDepthBridge,
	/// Virtual depth for PCI device object level.
	TypeDepthPCIDevice,
	/// Virtual depth for software device object level.
	TypeDepthOSDevice,
}

#[link(name = "hwloc")]
extern "C" {

	// === Topology Creation and Destruction ===

	pub fn hwloc_topology_init(topology: *mut *mut HwlocTopology) -> c_int;
	pub fn hwloc_topology_load(topology: *mut HwlocTopology) -> c_int;
	pub fn hwloc_topology_destroy(topology: *mut HwlocTopology);

	// === Topology Detection Configuration and Query ===

	pub fn hwloc_topology_set_flags(topology: *mut HwlocTopology, flags: c_ulonglong) -> c_int;
	pub fn hwloc_topology_get_flags(topology: *mut HwlocTopology) -> c_ulonglong;

	// === Object levels, depths and types ===

	pub fn hwloc_topology_get_depth(topology: *mut HwlocTopology) -> c_uint;
	pub fn hwloc_get_type_depth(topology: *mut HwlocTopology, object_type: ObjectType) -> c_int;
	pub fn hwloc_get_depth_type(topology: *mut HwlocTopology, depth: c_uint) -> ObjectType;
	pub fn hwloc_get_nbobjs_by_depth(topology: *mut HwlocTopology, depth: c_uint) -> c_uint;
	pub fn hwloc_get_obj_by_depth(topology: *mut HwlocTopology, depth: c_uint, idx: c_uint) -> ObjectType;
}
```

Now when I try to run this through cargo test, I get:

```
   Compiling hwloc v0.1.0 (file:///Users/michael/rust/hwloc-rs)
src/ffi.rs:96:6: 96:93 warning: foreign function is never used: `hwloc_topology_set_flags`, #[warn(dead_code)] on by default
src/ffi.rs:96 	pub fn hwloc_topology_set_flags(topology: *mut HwlocTopology, flags: c_ulonglong) -> c_int;
              	    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ffi.rs:97:6: 97:79 warning: foreign function is never used: `hwloc_topology_get_flags`, #[warn(dead_code)] on by default
src/ffi.rs:97 	pub fn hwloc_topology_get_flags(topology: *mut HwlocTopology) -> c_ulonglong;
              	    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     Running target/debug/hwloc-eb4c737c5f23fc40

running 4 tests
test tests::should_get_nbobjs_by_depth ... ok
test tests::should_match_types_and_their_depth ... ok
test tests::should_get_topology_depth ... ok
test tests::should_get_object_at_depth_and_index ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests hwloc

running 1 test
test ffi::ObjectType::Group_0 ... FAILED

failures:

---- ffi::ObjectType::Group_0 stdout ----
	<anon>:3:13: 3:18 error: expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `which`
<anon>:3     Objects which do not fit in the above but are detected by hwloc and 
                     ^~~~~
thread 'ffi::ObjectType::Group_0' panicked at 'Box<Any>', ../src/libsyntax/parse/mod.rs:98



failures:
    ffi::ObjectType::Group_0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

check out the doc failure in the middle there. When I remove the following empty line:

```
	/// Group objects.
--> this to be removed	/// 
	///	Objects which do not fit in the above but are detected by hwloc and 
	/// are useful to take into account for affinity. For instance, some 
	/// operating systems expose their arbitrary processors aggregation this
	/// way. And hwloc may insert such objects to group NUMA nodes according 
	/// to their distances.
	///
	/// These objects are ignored when they do not bring any structure.
```

It compiles fine. Am I doing anything wrong or is this a bug in the docblock parser?

it works properly. It seems that somehow rust thinks my docblock contains a test while it doesn't?

**Comment by steveklabnik** [comment]
Something is strange here. Look at how even on GitHub, `PU` is highlighted differently than the others.

**Comment by daschl** [comment]
@steveklabnik I just tried renaming PU to Pu and while it changes the syntax highlighting to be what one would expect, the same error happens. So it's not related to that apparently.

**Comment by Eljay** [comment]
Can't reproduce this issue locally, although I see there are other tests in the output that are in another file that could be relevant. Could you upload the rest of the code somewhere or make a smaller test case?


@steveklabnik Github highlights enum variants in all caps as constants for some reason.
```rust
const FOO: i32 = 1;
enum X { Foo, BAR, Baz }
```

**Comment by daschl** [comment]
@Eljay I see if I can extract it into something smaller

**Comment by daschl** [comment]
heh, I could indeed get it down to something very simple, so I hope for someone who knows the stuff its easily to debug.

Step1: create a `lib.rs`:

```rust
pub enum MySimpleEnum {
	/// some other text
	///
	///	here is some text
	SomeValue,
}
```

Now run `rustdoc --test lib.rs`:

```
michael@daschlbook ~/rust/repro/src $ rustc --version
rustc 1.4.0 (8ab8581f6 2015-10-27)
michael@daschlbook ~/rust/repro/src $ rustdoc --test lib.rs 

running 1 test
test MySimpleEnum::SomeValue_0 ... FAILED

failures:

---- MySimpleEnum::SomeValue_0 stdout ----
	<anon>:2:10: 2:12 error: expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `is`
<anon>:2     here is some text
                  ^~
thread 'MySimpleEnum::SomeValue_0' panicked at 'Box<Any>', ../src/libsyntax/parse/mod.rs:98



failures:
    MySimpleEnum::SomeValue_0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Note that even this fails:

```rust
pub enum MySimpleEnum {
	///
	///	here is some text
	SomeValue,
}
```

**Comment by daschl** [comment]
Okay folks, please disregard. It looks like there was an invisible character somewhere which messed up the parser :/ .. when I cleaned out all the comments and wrote them in manually again it now works.
