### ISSUE TITLE
ICE in print::pprust with `-Z unstable-options --pretty normal`

### ISSUE THREAD

**Issue by whipsch** [rust-lang/rust#30731]
Input: https://gist.github.com/whipsch/9053cc076083248b2c13

RUST_BACKTRACE:

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:366
stack backtrace:
   1:     0x7f2723300d70 - sys::backtrace::tracing::imp::write::h1fe79f3711caca0eUnt
   2:     0x7f2723307685 - panicking::log_panic::_<closure>::closure.39701
   3:     0x7f27233070f5 - panicking::log_panic::hffc6d029fed602571nx
   4:     0x7f27232ca663 - sys_common::unwind::begin_unwind_inner::h7045c1c64d9ab8edYgs
   5:     0x7f27232cafc8 - sys_common::unwind::begin_unwind_fmt::h40ee994bfe85f7a54fs
   6:     0x7f27232fec31 - rust_begin_unwind
   7:     0x7f272335226f - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:     0x7f272334c818 - panicking::panic::hb8a57f0c8013c90awDK
   9:     0x7f271dced38a - print::pprust::_<impl>::bclose_maybe_open::h37355ecf49953be2XtY
  10:     0x7f271dcecf44 - print::pprust::_<impl>::print_mac::hc75ea26b8c9d79336F0
  11:     0x7f271dcdf524 - print::pprust::_<impl>::print_stmt::h5f88115daf2f26f5Gk0
  12:     0x7f271dcf2f23 - print::pprust::_<impl>::print_block_maybe_unclosed::hf7ad1da05081d4e4uq0
  13:     0x7f271dce209e - print::pprust::_<impl>::print_item::h7e0f2b203ddfcd92P3Y
  14:     0x7f271dccd47e - print::pprust::print_crate::ha70da7fc58cc53ecBoX
  15:     0x7f2723867ea7 - pretty::pretty_print_input::_<closure>::closure.30268
  16:     0x7f2723864d75 - pretty::pretty_print_input::he4ab854e00707a30IYb
  17:     0x7f27238ed5fc - run_compiler::h9d54ca8784090b78sqc
  18:     0x7f27238eab36 - sys_common::unwind::try::try_fn::try_fn::h11041572279465146525
  19:     0x7f27232fea98 - __rust_try
  20:     0x7f27232f2aeb - sys_common::unwind::try::inner_try::h0c3b0e63f018cc29wds
  21:     0x7f27238eae84 - boxed::_<impl>::call_box::call_box::h7023908653336004374
  22:     0x7f2723306153 - sys::thread::_<impl>::new::thread_start::h85eb4d682b5d5d4ffGw
  23:     0x7f271d41a554 - start_thread
  24:     0x7f2722f8eb9c - __clone
  25:                0x0 - <unknown>
```

`rustc --version --verbose`:

```
rustc 1.5.0 (3d7cd77e4 2015-12-04)
binary: rustc
commit-hash: 3d7cd77e442ce34eaac8a176ae8be17669498ebc
commit-date: 2015-12-04
host: x86_64-unknown-linux-gnu
release: 1.5.0
```

**Comment by nodakai** [comment]
Boils down to this small test case:
```rust
fn f() {
  b! { }
  c
}
```

```
$ RUST_BACKTRACE=1 rustc -Z unstable-options --pretty normal main.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:330
stack backtrace:
   1:     0x7fa6afcc9780 - sys::backtrace::tracing::imp::write::h95a06036b37126f3Inu
   2:     0x7fa6afcd0425 - panicking::default_handler::_<closure>::closure.42754
   3:     0x7fa6afccffb3 - panicking::default_handler::h52ff76369879c06eaFy
   4:     0x7fa6afc997c6 - sys_common::unwind::begin_unwind_inner::ha2d7340df818fe5efgt
   5:     0x7fa6afc9a188 - sys_common::unwind::begin_unwind_fmt::hbf84897d960dd3falft
   6:     0x7fa6afcc7391 - rust_begin_unwind
   7:     0x7fa6afd2295f - panicking::panic_fmt::h429a8e624209fa72nYL
   8:     0x7fa6afd23458 - panicking::panic::h405d26906251684dUWL
   9:     0x7fa6abd8029a - print::pprust::State<'a>::bclose_maybe_open::h691140728605ea9dfM1
  10:     0x7fa6abd8b476 - print::pprust::State<'a>::print_block_maybe_unclosed::h0abaae9e5f2e58d5RI3
  11:     0x7fa6abd76b4f - print::pprust::State<'a>::print_item::ha28389c25b5ba8d8wl2
  12:     0x7fa6abd686de - print::pprust::print_crate::h7ba34fcca613a873dF0
  13:     0x7fa6b028dee7 - pretty::pretty_print_input::_<closure>::closure.35080
  14:     0x7fa6b01ab160 - pretty::pretty_print_input::hfe9a6ab02ec6f263i5b
  15:     0x7fa6b01a0edc - run_compiler::he8ecf6cfff34818aexc
  16:     0x7fa6b019e271 - sys_common::unwind::try::try_fn::h6472701518541106374
  17:     0x7fa6afcc7328 - __rust_try
  18:     0x7fa6afcbed8b - sys_common::unwind::try::inner_try::hef60513bede8266eNct
  19:     0x7fa6b019e5d0 - boxed::F.FnBox<A>::call_box::h12686579556207503277
  20:     0x7fa6afcce9a3 - sys::thread::Thread::new::thread_start::h046316123445d4346Bx
  21:     0x7fa6a9468283 - start_thread
  22:     0x7fa6af94d74c - clone
  23:                0x0 - <unknown>

$ rustc --version                                                   
rustc 1.8.0-dev (8ff48fea1 2016-01-23)
```

These variants don't ICE:
```rust
fn f() {
  b! { };
  c
}
```
```rust
fn f() {
  b! { }
}
```

**Comment by Mark-Simulacrum** [comment]
#31254 added a test when it fixed this, closing.
