### ISSUE TITLE
rustc panics when adding #[derive(Deserialize)] to pub type declaration

### ISSUE THREAD

**Issue by dikaiosune** [rust-lang/rust#30861]
## Summary

I accidentally added a `#[derive(Deserialize)]` (from serde_macros) to a `pub type _ = _;` declaration instead a struct, which then caused the compiler to panic. I reproduced it with this toy example on the 2016-01-04 nightly (the 01-11 nightly isn't compiling a dependency of `serde_macros` right now):

## Repro

```bash
adam@ARD155-01 ~/rust-projects $ cargo new demo --bin
adam@ARD155-01 ~/rust-projects/demo $ multirust override nightly-2016-01-04
multirust: using existing install for 'nightly-2016-01-04'
multirust: override toolchain for '/home/adam/rust-projects/demo' set to 'nightly-2016-01-04'
```

Cargo.toml:
```toml
[package]
name = "demo"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
serde_macros = "0.6"
```

main.rs:
```rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

#[derive(Deserialize)]
pub type NewType = Vec<u8>;

fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen:

`Don't do that stupid, here's a compiler (plugin) error.`

Instead, this happened:

```bash
error: internal compiler error: expected ItemStruct or ItemEnum in #[derive(Deserialize)]
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:469
```

## Meta

```bash
adam@ARD155-01 ~/rust-projects/demo $ rustc --version --verbose
rustc 1.7.0-nightly (8f11a9ef4 2016-01-03)
binary: rustc
commit-hash: 8f11a9ef4e23db189676c57c91c2675e97a74fea
commit-date: 2016-01-03
host: x86_64-unknown-linux-gnu
release: 1.7.0-nightly
```

```bash
adam@ARD155-01 ~/rust-projects/demo $ RUST_BACKTRACE=1 cargo build --verbose
       Fresh quasi v0.3.12
       Fresh aster v0.9.3
       Fresh quasi_codegen v0.3.12
       Fresh quasi_macros v0.3.12
       Fresh serde_codegen v0.6.8
       Fresh serde_macros v0.6.5
   Compiling demo v0.1.0 (file:///home/adam/rust-projects/demo)
     Running `rustc src/main.rs --crate-name demo --crate-type bin -g --out-dir /home/adam/rust-projects/demo/target/debug --emit=dep-info,link -L dependency=/home/adam/rust-projects/demo/target/debug -L dependency=/home/adam/rust-projects/demo/target/debug/deps --extern serde_macros=/home/adam/rust-projects/demo/target/debug/deps/libserde_macros-cc8fd08d94a4bbe6.so`
error: internal compiler error: expected ItemStruct or ItemEnum in #[derive(Deserialize)]
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:469
stack backtrace:
   1:     0x7f8ded2b9ae0 - sys::backtrace::tracing::imp::write::h83c931a57293be64Afu
   2:     0x7f8ded2c0925 - panicking::default_handler::_<closure>::closure.42389
   3:     0x7f8ded2c038e - panicking::default_handler::hf06b6e142d791340Eqy
   4:     0x7f8ded2896a6 - sys_common::unwind::begin_unwind_inner::h1f0575245cf3d0d097s
   5:     0x7f8de94a3c57 - sys_common::unwind::begin_unwind::h12034783770677981522
   6:     0x7f8de94a4094 - errors::Handler::bug::hdf0210fa875065449ed
   7:     0x7f8de9700a98 - ext::base::ExtCtxt<'a>::bug::h7e5b95135edda145nY7
   8:     0x7f8de1cd578e - de::expand_derive_deserialize::hd8e126252fab8683hra
                        at /home/adam/.multirust/toolchains/nightly-2016-01-04/cargo/registry/src/github.com-88ac128001ac3a9a/serde_codegen-0.6.8/src/de.rs:42
   9:     0x7f8de1cd7a71 - fn(&mut syntax..ext..base..ExtCtxt, syntax..codemap..Span, &syntax..codemap..Spanned<syntax..ast..MetaItem_>, &syntax..ext..base..Annotatable, &mut core..ops..FnMut(syntax..ext..base..Annotatable)) $u7b$de..expand_derive_deserialize$u7d$::fn_pointer_shim.11656::h4bad183350a0218a
  10:     0x7f8de1cd7a3d - ext::base::F.MultiItemDecorator::expand::h17106332544396698413
                        at ../src/libsyntax/ext/base.rs:119
  11:     0x7f8de97414cb - ext::expand::expand_annotatable::h8c7d426b1e137197Zua
  12:     0x7f8de973f4a8 - ext::expand::expand_item::h39bd2724f5135651IX9
  13:     0x7f8de974b325 - fold::noop_fold_mod::h5906434227193000799
  14:     0x7f8de9744ec9 - ext::expand::expand_item_underscore::h21fd83f940aaf048jY9
  15:     0x7f8de977a2be - fold::noop_fold_item_simple::h14303000504543087339
  16:     0x7f8de9779e20 - fold::noop_fold_item::h6885099739504352802
  17:     0x7f8de9743559 - ext::expand::expand_annotatable::h8c7d426b1e137197Zua
  18:     0x7f8de973f4a8 - ext::expand::expand_item::h39bd2724f5135651IX9
  19:     0x7f8de9783abb - ext::expand::expand_crate::h11ede8e6c601d3973Sa
  20:     0x7f8ded8138d2 - driver::phase_2_configure_and_expand::_<closure>::closure.31650
  21:     0x7f8ded7a5b55 - driver::phase_2_configure_and_expand::hb11cfa87638fbd7ekya
  22:     0x7f8ded7852f5 - driver::compile_input::h7886c8c232de8c7bjca
  23:     0x7f8ded778a1b - run_compiler::hfed1b58f3d8ec3b4Lwc
  24:     0x7f8ded7757e1 - sys_common::unwind::try::try_fn::h2798711789016417359
  25:     0x7f8ded2b7778 - __rust_try
  26:     0x7f8ded2aef6b - sys_common::unwind::try::inner_try::hfe5be09170a408dfH4s
  27:     0x7f8ded775b40 - boxed::F.FnBox<A>::call_box::h4070559527455171401
  28:     0x7f8ded2beb33 - sys::thread::Thread::new::thread_start::he835c8386c59daa96nx
  29:     0x7f8de616e4a3 - start_thread
  30:     0x7f8decf4513c - clone
  31:                0x0 - <unknown>

Could not compile `demo`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name demo --crate-type bin -g --out-dir /home/adam/rust-projects/demo/target/debug --emit=dep-info,link -L dependency=/home/adam/rust-projects/demo/target/debug -L dependency=/home/adam/rust-projects/demo/target/debug/deps --extern serde_macros=/home/adam/rust-projects/demo/target/debug/deps/libserde_macros-cc8fd08d94a4bbe6.so` (exit code: 101)
```

**Comment by est31** [comment]
This looks more like a bug in the compiler plugin you used https://github.com/serde-rs/serde , the stack trace mentions this line: https://github.com/serde-rs/serde/blob/v0.6.9/serde_codegen/src/de.rs#L42

**Comment by dikaiosune** [comment]
It may very well be a problem in the plugin, but the error message indicates that the panic was in libsyntax:

https://github.com/rust-lang/rust/blob/master/src/libsyntax/errors/mod.rs#L469

And rustc specifically asked me to submit a bug report here. I also opened an issue in the serde repo (serde-rs/serde#206) in case that's the more appropriate place to report this.

**Comment by est31** [comment]
Yes, the fact that the compiler asks you to open an issue at this place and not at the place of the compiler plugin is unfortunate.

The plugin used an internal rustc API function that causes the panic and prints the "internal error" message you see above, it seems to be more intended for internal compiler usage than a compiler plugin. The way the plugin used the function is clearly wrong, it only complains about wrong by code writers.

The compiler exposes this API to plugins, this is wrong IMO, but I don't know whether there is a way to hide single functions from compiler plugins. Perhaps it could also check whether a plugin's code is in the stacktrace when printing the backtrace near the "the compiler unexpectedly panicked" code.

So agreed, rustc could do better here, but the major cause for this panic is the plugin.

**Comment by erickt** [comment]
This was just a serde bug, which I'm fixing in https://github.com/serde-rs/serde/pull/210. I was using `syntax::ext::base::ExtCtxt::span_bug`, which produces this error message, when I should have been using `span_err`. We should probably have some other mechanism for plugins to change this error message to point at our projects for error reporting instead of the rust-lang/rust repo.
