### ISSUE TITLE
Rustdoc crashed on time crate under FreeBSD

### ISSUE THREAD

**Issue by andoriyu** [rust-lang/rust#30885]
Every time I try to make documentation for my crate it failed because of time crate. Reproducible 100% of a time. Let me know if more info required.

```
$ gdb -ex r --args rustdoc /home/andoriyu/.cargo/registry/src/github.com-88ac128001ac3a9a/time-0.1.34/src/lib.rs --crate-name time -o /usr/home/andoriyu/Dev/Heaven/angel-whisper/target/doc -L dependency=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps -L dependency=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps --extern winapi=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libwinapi-96db160368c72f00.rlib --extern winapi=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libwinapi-96db160368c72f00.rlib --extern kernel32=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libkernel32-a6ecb7771eb9fd8d.rlib --extern kernel32=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libkernel32-a6ecb7771eb9fd8d.rlib --extern libc=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/liblibc-adb8b8e7aaa2f93f.rlib --extern libc=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/liblibc-adb8b8e7aaa2f93f.rlib
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...(no debugging symbols found)...
(gdb) run
Starting program: /usr/local/bin/rustdoc /home/andoriyu/.cargo/registry/src/github.com-88ac128001ac3a9a/time-0.1.34/src/lib.rs --crate-name time -o /usr/home/andoriyu/Dev/Heaven/angel-whisper/target/doc -L dependency=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps -L dependency=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps --extern winapi=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libwinapi-96db160368c72f00.rlib --extern winapi=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libwinapi-96db160368c72f00.rlib --extern kernel32=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libkernel32-a6ecb7771eb9fd8d.rlib --extern kernel32=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/libkernel32-a6ecb7771eb9fd8d.rlib --extern libc=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/liblibc-adb8b8e7aaa2f93f.rlib --extern libc=/usr/home/andoriyu/Dev/Heaven/angel-whisper/target/debug/deps/liblibc-adb8b8e7aaa2f93f.rlib
(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...[New LWP 100797]
(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...[New Thread 80b410400 (LWP 101627/rustc)]
[New Thread 80a806800 (LWP 101601/rustdoc)]

Program received signal SIGBUS, Bus error.
[Switching to Thread 80a806800 (LWP 101601/rustdoc)]
0x0000000800ba8e4d in html::toc::TocBuilder::new::h7090f1964647bba2BXs () from /usr/local/lib/librustdoc-17a8ccbd.so
(gdb) bt
#0  0x0000000800ba8e4d in html::toc::TocBuilder::new::h7090f1964647bba2BXs () from /usr/local/lib/librustdoc-17a8ccbd.so
#1  0x0000000800643800 in ?? ()
#2  0x0000000800643c00 in ?? ()
#3  0x0000000800632000 in ?? ()
#4  0x0000000000000000 in ?? ()
```
### Meta

```
$ rustc --version --verbose
rustc 1.7.0-nightly
binary: rustc
commit-hash: unknown (EDIT: 5e8cb38)
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.7.0-nightly
$ uname -a
FreeBSD beast.local 10.2-STABLE FreeBSD 10.2-STABLE #1: Tue Dec  8 15:17:10 PST 2015     root@beast.local:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by GuillaumeGomez** [comment]
Interesting. I'm gonna take a look at it.

**Comment by GuillaumeGomez** [comment]
Sorry, I wasn't able to reproduce your bug. I have two possibilities in mind:
* this is specific to FreeBSD
* you had not enough RAM (who knows?)

Also, have you retry since last time?

**Comment by andoriyu** [comment]
@GuillaumeGomez Plenty of RAM. 

Just tried time crate by itself — the same.

**Comment by GuillaumeGomez** [comment]
So this is specific to FreeBSD. Now I have to install one. :-/

**Comment by andoriyu** [comment]
@GuillaumeGomez You can use virtual box: https://atlas.hashicorp.com/infinitycode/boxes/heaven-server (that one already set to use repository with fresh rust-nightly and cargo builds)

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Comment by steveklabnik** [comment]
Is this still happening? it's been quite a while

**Comment by andoriyu** [comment]
I'll check today.

**Comment by jyn514** [comment]
I was not able to install 1.7.0 on FreeBSD, 1.8.0 gives a rustup error (https://github.com/rust-lang/rustup/issues/2547), and 1.9.0 doesn't give a SIGBUS, it panics instead. 1.47 builds the docs fine. I think it's unlikely this is still an issue - @andoriyu feel free to re-open if you're still having trouble.
