### ISSUE TITLE
error: internal compiler error: Error constructed but not emitted

### ISSUE THREAD

**Issue by ferjm** [rust-lang/rust#31676]
I am seeing the following panic:
```

Compiling foxbox_users v0.1.0 (file:///Volumes/mozilladev/foxbox/users-ferjm)
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/libsyntax/errors/mod.rs:360
stack backtrace:
   1:        0x10a9bd488 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x10a9c3555 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x10a9c3035 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10a98bf16 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x107ef8084 - sys_common::unwind::begin_unwind::h13146085605143757291
   6:        0x107eff9f4 - errors::DiagnosticBuilder<'a>.Drop::drop::h74630777c3a3e7973Bd
   7:        0x10e11fcfc - syntax..errors..DiagnosticBuilder::drop.13872::he841adc067eec1b4
   8:        0x10e122a16 - core..result..Result<syntax..ptr..P<syntax..ast..Block>, syntax..errors..DiagnosticBuilder>::drop.14045::ha78fca7fe0fa1afa
   9:        0x10e1229a8 - result::Result<T, E>::ok::h8598607649825527066
  10:        0x10e11f977 - parse::Test.Parse<bool>::parse::h5bc3db50069b1db6cea
  11:        0x10e11c26d - parse::DescribeState.Parse<(codemap..Span, &'a mut base..ExtCtxt<'b>, Option<ast..Ident>)>::parse::h157da640af2ff6cfaia
  12:        0x10e0e8d90 - describe::describe::h47eeebe418369c49Sca
  13:        0x10e0e905d - fn(&mut syntax..ext..base..ExtCtxt, syntax..codemap..Span, syntax..ast..Ident, collections..vec..Vec<syntax..ast..TokenTree>) .> Box<syntax..ext..base..MacResult> $u7b$describe..describe$u7d$::fn_pointer_shim.12515::h11bf6433a9f5c463
  14:        0x10e0e8fa5 - ext::base::F.IdentMacroExpander::expand::h2255893400289716387
  15:        0x108184e48 - ext::expand::expand_item_mac::hc9348d4e1cc575a7O29
  16:        0x108177c6d - ext::expand::expand_annotatable::h588765912514d47ejxa
  17:        0x1081748b8 - ext::expand::expand_item::h7a48d46a3d280a782Z9
  18:        0x108180de9 - fold::noop_fold_mod::h5514942419128523883
  19:        0x10817abba - ext::expand::expand_item_underscore::hc3669d26e238942aD09
  20:        0x1081b1c4b - fold::noop_fold_item_simple::h11240569791642338683
  21:        0x1081b179f - fold::noop_fold_item::h6562330027966964896
  22:        0x108178f4a - ext::expand::expand_annotatable::h588765912514d47ejxa
  23:        0x1081748b8 - ext::expand::expand_item::h7a48d46a3d280a782Z9
  24:        0x108180de9 - fold::noop_fold_mod::h5514942419128523883
  25:        0x10817abba - ext::expand::expand_item_underscore::hc3669d26e238942aD09
  26:        0x1081b1c4b - fold::noop_fold_item_simple::h11240569791642338683
  27:        0x1081b179f - fold::noop_fold_item::h6562330027966964896
  28:        0x108178f4a - ext::expand::expand_annotatable::h588765912514d47ejxa
  29:        0x1081748b8 - ext::expand::expand_item::h7a48d46a3d280a782Z9
  30:        0x1081badd3 - ext::expand::expand_crate::h30ce0ee1f7e97002nVa
  31:        0x10653ad22 - driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::closure.32913
  32:        0x1064d1404 - driver::phase_2_configure_and_expand::h68ab6c933fccd499hza
  33:        0x1064b1b40 - driver::compile_input::h43265b54b30381a1xca
  34:        0x1064a5438 - run_compiler::hd56abf18e73f9531dEc
  35:        0x1064a1f45 - sys_common::unwind::try::try_fn::h3725603775136238299
  36:        0x10a9baf4b - __rust_try
  37:        0x10a9b2fb3 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  38:        0x1064a2809 - boxed::F.FnBox<A>::call_box::h11662039638244946638
  39:        0x10a9c254d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  40:     0x7fff8baea267 - _pthread_body
  41:     0x7fff8baea1e4 - _pthread_start

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/libsyntax/errors/mod.rs:360
stack backtrace:
   1:        0x10f493488 - sys::backtrace::tracing::imp::write::h268482af15af0a80Y8t
   2:        0x10f499555 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42271
   3:        0x10f499035 - panicking::default_handler::h97bc664f7e2bfeb5Ocy
   4:        0x10f461f16 - sys_common::unwind::begin_unwind_inner::h98c0975c9b6b2fa0Zbt
   5:        0x10c9c3084 - sys_common::unwind::begin_unwind::h13146085605143757291
   6:        0x10c9ca9f4 - errors::DiagnosticBuilder<'a>.Drop::drop::h74630777c3a3e7973Bd
   7:        0x112c75cfc - syntax..errors..DiagnosticBuilder::drop.13872::he841adc067eec1b4
   8:        0x112c78a16 - core..result..Result<syntax..ptr..P<syntax..ast..Block>, syntax..errors..DiagnosticBuilder>::drop.14045::ha78fca7fe0fa1afa
   9:        0x112c789a8 - result::Result<T, E>::ok::h8598607649825527066
  10:        0x112c75977 - parse::Test.Parse<bool>::parse::h5bc3db50069b1db6cea
  11:        0x112c7226d - parse::DescribeState.Parse<(codemap..Span, &'a mut base..ExtCtxt<'b>, Option<ast..Ident>)>::parse::h157da640af2ff6cfaia
  12:        0x112c3ed90 - describe::describe::h47eeebe418369c49Sca
  13:        0x112c3f05d - fn(&mut syntax..ext..base..ExtCtxt, syntax..codemap..Span, syntax..ast..Ident, collections..vec..Vec<syntax..ast..TokenTree>) .> Box<syntax..ext..base..MacResult> $u7b$describe..describe$u7d$::fn_pointer_shim.12515::h11bf6433a9f5c463
  14:        0x112c3efa5 - ext::base::F.IdentMacroExpander::expand::h2255893400289716387
  15:        0x10cc4fe48 - ext::expand::expand_item_mac::hc9348d4e1cc575a7O29
  16:        0x10cc42c6d - ext::expand::expand_annotatable::h588765912514d47ejxa
  17:        0x10cc3f8b8 - ext::expand::expand_item::h7a48d46a3d280a782Z9
  18:        0x10cc4bde9 - fold::noop_fold_mod::h5514942419128523883
  19:        0x10cc45bba - ext::expand::expand_item_underscore::hc3669d26e238942aD09
  20:        0x10cc7cc4b - fold::noop_fold_item_simple::h11240569791642338683
  21:        0x10cc7c79f - fold::noop_fold_item::h6562330027966964896
  22:        0x10cc43f4a - ext::expand::expand_annotatable::h588765912514d47ejxa
  23:        0x10cc3f8b8 - ext::expand::expand_item::h7a48d46a3d280a782Z9
  24:        0x10cc4bde9 - fold::noop_fold_mod::h5514942419128523883
  25:        0x10cc45bba - ext::expand::expand_item_underscore::hc3669d26e238942aD09
  26:        0x10cc7cc4b - fold::noop_fold_item_simple::h11240569791642338683
  27:        0x10cc7c79f - fold::noop_fold_item::h6562330027966964896
  28:        0x10cc43f4a - ext::expand::expand_annotatable::h588765912514d47ejxa
  29:        0x10cc3f8b8 - ext::expand::expand_item::h7a48d46a3d280a782Z9
  30:        0x10cc85dd3 - ext::expand::expand_crate::h30ce0ee1f7e97002nVa
  31:        0x10afefd22 - driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::closure.32913
  32:        0x10af86404 - driver::phase_2_configure_and_expand::h68ab6c933fccd499hza
  33:        0x10af66b40 - driver::compile_input::h43265b54b30381a1xca
  34:        0x10af5a438 - run_compiler::hd56abf18e73f9531dEc
  35:        0x10af56f45 - sys_common::unwind::try::try_fn::h3725603775136238299
  36:        0x10f490f4b - __rust_try
  37:        0x10f488fb3 - sys_common::unwind::inner_try::h3c719a7bb47af1af18s
  38:        0x10af57809 - boxed::F.FnBox<A>::call_box::h11662039638244946638
  39:        0x10f49854d - sys::thread::Thread::new::thread_start::hbf136943ebd5e19atrx
  40:     0x7fff8baea267 - _pthread_body
  41:     0x7fff8baea1e4 - _pthread_start

Build failed, waiting for other jobs to finish...
Could not compile `foxbox_users`.

To learn more, run the command again with --verbose.
```

Caused by the following code:

```
describe! routes_tests {
    before_each {
        use iron::{headers, Headers};
        use iron_test::request;

        let router = UsersRouter::new();

        use iron::method::Method;
        use iron::middleware::Handler;
        use iron::status::Status;

        use super::Endpoint;
    }

    it "should respond with 501 not implemented" {
        const ENDPOINTS: &'static[Endpoint] = &[
            (Method::Post,      &["invitations"]),
            (Method::Get,       &["invitations"]),
            (Method::Delete,    &["invitations"]),
            (Method::Post,      &["users"]),
            (Method::Get,       &["users"]),
            (Method::Put,       &["users", "*"]),
            (Method::Post,      &["users", "*"]),
            (Method::Post,      &["recoveries", "*"]),
            (Method::Get,       &["recoveries", "*", "*"]),
            (Method::Get,       &["permissions"]),
            (Method::Get,       &["permissions", "*"]),
            (Method::Get,       &["permissions", "*", "*"]),
            (Method::Get,       &["permissions", "_", "*"]),
            (Method::Put,       &["permissions", "*", "*"]),
        ];

        for endpoint in ENDPOINTS {
            let (ref method, path) = *endpoint;
            let path = "http://localhost:3000/".to_string() +
                       &(path.join("/").replace("*", "foo"));
           
            let req = match *method {
                Method::Get => {
                    request::get(&path, Headers::new(), &router)
                },
                Method::Post => {
                    request::post(&path, Headers::new(), "", &router)
                },
                Method::Delete => {
                    request::delete(&path, Headers::new(), &router)
                },
                Method::Put => {
                    request::put(&path, Headers::new(), "", &router)
                },
                _ => {
                    assert!(false);
                    request::get(&path, Headers::new(), "", &router)
                }
            }
            assert!(true);
        }
    }
}
```

I can workaround the panic if I do:
```

            match *method {
                Method::Get => {
                    let req = request::get(&path, Headers::new(), &router);
                },
                Method::Post => {
                    let req = request::post(&path, Headers::new(), "", &router);
                },
                Method::Delete => {
                    let req = request::delete(&path, Headers::new(), &router);
                },
                Method::Put => {
                    let req = request::put(&path, Headers::new(), "", &router);
                },
                _ => {}
            }
```

**Comment by ferjm** [comment]
The issue seems to be the missing `;` after the closing match `}`

**Comment by jonas-schievink** [comment]
Looks like this is a bug in the "describe" syntax extension.

**Comment by jonas-schievink** [comment]
Yep. Bug in stainless. This file is using `.ok()` quite a lot: https://github.com/reem/stainless/blob/master/src/parse.rs

**Comment by sanxiyn** [comment]
Closing this, as the bug is clearly in stainless syntax extension.
