### ISSUE TITLE
compiler panic (on stable) when trying to implement trait for enum member

### ISSUE THREAD

**Issue by flying-sheep** [rust-lang/rust#31699]
offending code:

``` rust
impl From<function::ArgumentType> for function::Error::WrongType {
    fn from(arg_type: function::ArgumentType) -> function::Error::WrongType {

    }
}
```

where “function” is [`sxd_xpath::function`](http://jakegoulding.com/sxd-xpath/sxd_xpath/function/index.html)

backtrace:

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:367
stack backtrace:
   1:     0x7fca9a518ad0 - sys::backtrace::tracing::imp::write::hab863fe071b2ab40G0t
   2:     0x7fca9a51f6b5 - panicking::log_panic::_<closure>::closure.41218
   3:     0x7fca9a51f14f - panicking::log_panic::hf48e729df98b0b98W7x
   4:     0x7fca9a4e87a3 - sys_common::unwind::begin_unwind_inner::he149221c893514bafTs
   5:     0x7fca9a4e9108 - sys_common::unwind::begin_unwind_fmt::h76025582fb6dc4f7lSs

   6:     0x7fca9a516921 - rust_begin_unwind
   7:     0x7fca9a55cb8f - panicking::panic_fmt::h61cf019703dfce9dLFK
   8:     0x7fca9a55d1c8 - panicking::panic::ha1e522b9c3aef120iEK
   9:     0x7fca986a6688 - astconv::finish_resolving_def_to_ty::h5d33d451a073c83dYIw
  10:     0x7fca986574bb - astconv::ast_ty_to_ty::h0600161d6a5b07ecsKw
  11:     0x7fca987343ea - collect::convert_item::h51b4e04b669f38897vy
  12:     0x7fca9873101b - collect::_<impl>::visit_item::h7609c1b427098effRRx
  13:     0x7fca98613ce2 - collect::collect_item_types::hf0b5d2fe225176d7fJx
  14:     0x7fca986105e3 - check_crate::h59e62ba807f72882jxD
  15:     0x7fca9aa13a08 - driver::phase_3_run_analysis_passes::_<closure>::closure.25590
  16:     0x7fca9a9f7573 - middle::ty::context::_<impl>::create_and_enter::create_and_enter::h13769573967675817450
  17:     0x7fca9a9f2fb1 - driver::phase_3_run_analysis_passes::h11828585256869968594
  18:     0x7fca9a9c82b9 - driver::compile_input::h11272f634c6ad992hca
  19:     0x7fca9a9ba4db - run_compiler::h98a9a809e704e6c5Owc
  20:     0x7fca9a9b7196 - sys_common::unwind::try::try_fn::try_fn::h17568269690421307877
  21:     0x7fca9a516768 - __rust_try
  22:     0x7fca9a50e06b - sys_common::unwind::try::inner_try::h9e6b3ceacaea5d44NPs
  23:     0x7fca9a9b74f0 - boxed::_<impl>::call_box::call_box::h14495816298810048001
  24:     0x7fca9a51dbb3 - sys::thread::_<impl>::new::thread_start::ha8bf94240aaddd0089w
  25:     0x7fca944084a3 - start_thread
  26:     0x7fca9a1ac13c - clone
  27:                0x0 - <unknown>
```

**Comment by mitaa** [comment]
I think this may have been fixed recently (#31126)

**Comment by mrZalli** [comment]
I am not sure if this is the same bug, but it kind of seems like it.

The backtrace I got was:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x7f2c90370e09 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7f2c903814fc - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7f2c9037f807 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7f2c90380018 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7f2c9037feb2 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7f2c9037fde0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7f2c9037fd61 - rust_begin_unwind
   8:     0x7f2c903eb42f - core::panicking::panic_fmt::hc5789f4e80194729
   9:     0x7f2c903eb35b - core::panicking::panic::h1953378f4b37b561
  10:     0x7f2c8ea7f0dc - rustc_typeck::check::compare_method::compare_impl_method::_{{closure}}::h08bef90d287aed42
  11:     0x7f2c8e9db0f9 - rustc_typeck::check::compare_method::compare_impl_method::he3538453c2efe177
  12:     0x7f2c8e9f0082 - rustc_typeck::check::check_impl_items_against_trait::hb105ca8bb42a0b3d
  13:     0x7f2c8e9ed602 - rustc_typeck::check::check_item_type::hba3733559d49be1e
  14:     0x7f2c8e9e5e4b - _<rustc_typeck..check..CheckItemTypesVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'tcx>>::visit_item::h369cacffbaa18923
  15:     0x7f2c8e9e7d4b - rustc_typeck::check::check_item_types::h81e44a5d40f450fd
  16:     0x7f2c8ea5f4c3 - rustc_typeck::check_crate::h8ec8b2f490f5dc28
  17:     0x7f2c90760d13 - rustc_driver::driver::phase_3_run_analysis_passes::_{{closure}}::h45e03cee16dcf298
  18:     0x7f2c9072d756 - rustc_driver::driver::phase_3_run_analysis_passes::hc0de40cea97d81a1
  19:     0x7f2c90719f42 - rustc_driver::driver::compile_input::hd9ecc57abd3cba85
  20:     0x7f2c9074c966 - rustc_driver::run_compiler::h184264500271cc39
  21:     0x7f2c906928c2 - std::panicking::try::do_call::h17a7a17ad7240c5c
  22:     0x7f2c9038f866 - __rust_maybe_catch_panic
  23:     0x7f2c906ac2aa - _<F as alloc..boxed..FnBox<A>>::call_box::h93f9128277b2964a
  24:     0x7f2c9037dbd2 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  25:     0x7f2c886b10a3 - start_thread
  26:     0x7f2c8ffc087c - clone
  27:                0x0 - <unknown>
```

**Comment by Mark-Simulacrum** [comment]
I get the following today, so closing. A test seems impractical due to needing a crate dep.

```rust
extern crate sxd_xpath;

use sxd_xpath::function;

impl From<function::ArgumentType> for function::Error::WrongType {
    fn from(arg_type: function::ArgumentType) -> function::Error::WrongType {

    }
}
```

```
error[E0573]: expected type, found variant `function::Error::WrongType`
 --> test.rs:5:39
  |
5 | impl From<function::ArgumentType> for function::Error::WrongType {
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ not a type
  |
  = help: there is an enum variant `sxd_xpath::function::Error::WrongType`, did you mean to use `sxd_xpath::function::Error`?

error[E0573]: expected type, found variant `function::Error::WrongType`
 --> test.rs:6:50
  |
6 |     fn from(arg_type: function::ArgumentType) -> function::Error::WrongType {
  |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ not a type
  |
  = help: there is an enum variant `sxd_xpath::function::Error::WrongType`, did you mean to use `sxd_xpath::function::Error`?

error: aborting due to 2 previous errors
```
