### ISSUE TITLE
Arithmetic overflow in function but not in main

### ISSUE THREAD

**Issue by andrewrynhard** [rust-lang/rust#31829]
I get the error
````
thread '<main>' panicked at 'arithmetic operation overflowed', test.rs:4
````

with `rustc 1.6.0 (c30b771ad 2016-01-19)`

at runtime with the following code:
```` rust
fn this_fails(L: usize, N: usize) {
    for k in 1..L {
        println!("k = {:?}", k);
        for i in k + 2..N - k + 1 {
            println!("i = {:?}", i);
        }
    }
}

fn main() {
    let N: usize = 10 as usize;
    let L: usize = ((N as f64/2.0).ceil() - 1.0) as usize;

    println!("This works ...");
    for k in 1..L {
        println!("k = {:?}", k);
        for i in k + 2..N - k + 1 {
            println!("i = {:?}", i);
        }
    }

    println!("This fails ...");
    this_fails(N, L);
}
````

The complete output is
````
k = 1
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
k = 2
i = 4
i = 5
i = 6
i = 7
k = 3
i = 5
i = 6

k = 1
i = 3
k = 2
k = 3
k = 4
k = 5
thread '<main>' panicked at 'arithmetic operation overflowed', src/main.rs:90
stack backtrace:
   1:        0x10f48abf8 - sys::backtrace::tracing::imp::write::h71b7c99a21cff148fMt
   2:        0x10f48bfdf - panicking::log_panic::_<closure>::closure.40876
   3:        0x10f48ba82 - panicking::log_panic::h2d79dd1ccae87ed8BFx
   4:        0x10f485816 - sys_common::unwind::begin_unwind_inner::hb8ac08b8a72b9d1bhPs
   5:        0x10f48594e - sys_common::unwind::begin_unwind_fmt::h076ba7ed08690e9dnOs
   6:        0x10f48a217 - rust_begin_unwind
   7:        0x10f4ab8b0 - panicking::panic_fmt::h3967afc085fe8067LFK
   8:        0x10f4abbac - panicking::panic::h77d028a733b1a80eiEK
   9:        0x10f48344a - lms::hc70a7134f2a56c9beaa
  10:        0x10f484793 - main::h372c68c82150c71eLba
  11:        0x10f48b802 - sys_common::unwind::try::try_fn::h4103587514840227558
  12:        0x10f48a038 - __rust_try
  13:        0x10f48b6a9 - rt::lang_start::h216753457f385fdaJCx
  14:        0x10f484ce9 - main
````
As you can see, the loop works fine in `main` but acts strange in a `fn`.

**Comment by alexcrichton** [comment]
Perhaps it's because the arguments to `this_fails` are switched?

**Comment by andrewrynhard** [comment]
Wow. I should get some sleep. Thank you.
