### ISSUE TITLE
ICE when building

### ISSUE THREAD

**Issue by hfiguiere** [rust-lang/rust#32195]
I tried to compile project:

I have ````rustc 1.9.0-dev (998a6720b 2016-03-07)````

````
$ git clone https://github.com/hfiguiere/foxbox.git
$ cd foxbox ; git checkout rustc-ice-1
$ cargo test
````
I get an internal compiler error.
````
    $cargo test
       Compiling foxbox v0.1.0 (file:///home/hub/source/mozilla/foxbox)
    error: internal compiler error: Error constructed but not emitted
    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'explicit panic', src/libsyntax/errors/mod.rs:360
    stack backtrace:
       1:     0x7f1d1c51dfd0 - sys::backtrace::tracing::imp::write::h0521077ef22e0136cHv
       2:     0x7f1d1c52732b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44995
       3:     0x7f1d1c526e83 - panicking::default_handler::hdc60e3ec418dc2431nA
       4:     0x7f1d1c4ea46c - sys_common::unwind::begin_unwind_inner::h955eeda71252d25avvu
       5:     0x7f1d182bcd8f - sys_common::unwind::begin_unwind::h9420075238342015703
       6:     0x7f1d182c443f - errors::DiagnosticBuilder<'a>.Drop::drop::hb20e0eda7415a5b6uCd
       7:     0x7f1d0c17993c - syntax..errors..DiagnosticBuilder::drop.13989::h712844b71210ba11
       8:     0x7f1d0c17c246 - core..result..Result<syntax..ptr..P<syntax..ast..Block>, syntax..errors..DiagnosticBuilder>::drop.14223::h5f3c03798d26b4e5
       9:     0x7f1d0c17c1d8 - result::Result<T, E>::ok::h6738451972438490412
                            at src/libcore/result.rs:326
      10:     0x7f1d0c176df7 - parse::DescribeState.Parse<(codemap..Span, &'a mut base..ExtCtxt<'b>, Option<ast..Ident>)>::parse::h47755fa011aed36aaia
                            at /home/hub/.cargo/registry/src/github.com-88ac128001ac3a9a/stainless-0.1.4/src/parse.rs:109
      11:     0x7f1d0c149121 - describe::describe::h04b9b7cb19a0bc3cSca
                            at /home/hub/.cargo/registry/src/github.com-88ac128001ac3a9a/stainless-0.1.4/src/describe.rs:62
      12:     0x7f1d0c14940d - fn(&mut syntax..ext..base..ExtCtxt, syntax..codemap..Span, syntax..ast..Ident, collections..vec..Vec<syntax..ast..TokenTree>) .> Box<syntax..ext..base..MacResult> $u7b$describe..describe$u7d$::fn_pointer_shim.12608::hf27ab56c3393d725
      13:     0x7f1d0c149356 - ext::base::F.IdentMacroExpander::expand::h6791951820521778383
                            at src/libsyntax/ext/base.rs:199
      14:     0x7f1d1857346f - ext::expand::expand_item_mac::h0c9ef81058cb15a1mO9
      15:     0x7f1d18561db1 - ext::expand::expand_annotatable::h1244c9bf9cdbe2f0nia
      16:     0x7f1d1855ef78 - ext::expand::expand_item::hdbb8077c6a5424bbAL9
      17:     0x7f1d1856d02e - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h306e8a01d1d75b11ZAa
      18:     0x7f1d1856cc63 - fold::noop_fold_mod::h748798114235938965
      19:     0x7f1d185665d2 - ext::expand::expand_item_kind::h66a4ab28aa406d9abM9
      20:     0x7f1d185a292e - fold::noop_fold_item_simple::h9534234569163732720
      21:     0x7f1d185a24a0 - fold::noop_fold_item::h3246028842972066210
      22:     0x7f1d18563542 - ext::expand::expand_annotatable::h1244c9bf9cdbe2f0nia
      23:     0x7f1d1855ef78 - ext::expand::expand_item::hdbb8077c6a5424bbAL9
      24:     0x7f1d1856d23c - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h306e8a01d1d75b11ZAa
      25:     0x7f1d1856cc63 - fold::noop_fold_mod::h748798114235938965
      26:     0x7f1d185665d2 - ext::expand::expand_item_kind::h66a4ab28aa406d9abM9
      27:     0x7f1d185a292e - fold::noop_fold_item_simple::h9534234569163732720
      28:     0x7f1d185a24a0 - fold::noop_fold_item::h3246028842972066210
      29:     0x7f1d18563542 - ext::expand::expand_annotatable::h1244c9bf9cdbe2f0nia
      30:     0x7f1d1855ef78 - ext::expand::expand_item::hdbb8077c6a5424bbAL9
      31:     0x7f1d1856d23c - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h306e8a01d1d75b11ZAa
      32:     0x7f1d185ae779 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_crate::he12b454038938e421za
      33:     0x7f1d185afc5a - ext::expand::expand_crate::h363746c44503a0f8PJa
      34:     0x7f1d1caa5ce1 - driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::closure.35538
      35:     0x7f1d1ca53417 - driver::phase_2_configure_and_expand::h9487c2f69ae1947d8Aa
      36:     0x7f1d1ca36c11 - driver::compile_input::h9329a4ca1d4846bfKca
      37:     0x7f1d1ca266ef - run_compiler::hc76a855ecf2c5ad88Oc
      38:     0x7f1d1ca23e11 - sys_common::unwind::try::try_fn::h12872287387039651173
      39:     0x7f1d1c51b9bb - __rust_try
      40:     0x7f1d1c513c6d - sys_common::unwind::inner_try::ha3396506e5f7c46dxsu
      41:     0x7f1d1ca2465a - boxed::F.FnBox<A>::call_box::h15690486906178592244
      42:     0x7f1d1c5258f9 - sys::thread::Thread::new::thread_start::h98b61de3bdb99dbbllz
      43:     0x7f1d15977609 - start_thread
      44:     0x7f1d1c193a4c - clone
      45:                0x0 - <unknown>
    
    Could not compile `foxbox`.
````

The commit to trigger the bug is:
https://github.com/hfiguiere/foxbox/commit/5d53cd524d18c62a43912b64405a06ff64e05630

**Comment by sanxiyn** [comment]
Closing this, as the bug is clearly in stainless syntax extension.
