### ISSUE TITLE
Backtraces in windows are not useful

### ISSUE THREAD

**Issue by taralx** [rust-lang/rust#32969]
When debugging a stage1 panic on a rustbuild on windows, I get this backtrace:

```
stack backtrace:
   0:         0x6781025f - mingw_set_invalid_parameter_handler
   1:         0x6783d5dc - mingw_set_invalid_parameter_handler
...
```

Not useful. :(

**Comment by retep998** [comment]
Did you remember to enable debuginfo?

**Comment by taralx** [comment]
Does --enable-debug not do that? Maybe it should by default?

**Comment by taralx** [comment]
Or maybe we could always include debuginfo. How expensive is it?

**Comment by taralx** [comment]
In the worst case, we should not advise people to enable backtrace when they won't produce useful results.

**Comment by retep998** [comment]
I'm personally in favor of always having debug info by default and having to opt out if you really don't want it. That's the approach VC++ takes, with release builds having full debug info by default.

I'm not sure what the exact state of backtraces is on Windows. For -msvc PDB files are always emitted and when debuginfo is enabled backtraces work perfectly, when debuginfo is disabled the PDB won't have symbols defined in the top level binary crate leaving holes in backtraces. For -gnu we depend on libbacktrace to parse the dwarf debuginfo to give us backtraces, and that has had reliability issues in the past sometimes not working at all even though there was dwarf debuginfo and sometimes working fine.

**Comment by taralx** [comment]
Well, I'm using ./configure --enable-rustbuild --enable-debug for what that's worth.

**Comment by retep998** [comment]
Are you building `i686-pc-windows-gnu` or `x86_64-pc-windows-gnu`?

cc @vadimcn  @Diggsey

**Comment by taralx** [comment]
mingw-w64, so x86_64-pc-windows-gnu.

**Comment by retep998** [comment]
The w64 bit in mingw-w64 is actually unrelated to the architecture. There are both 32 and 64 bit versions of mingw-w64.

**Comment by taralx** [comment]
Was 64-bit.

**Comment by Zoxc** [comment]
It would be nice if this tier 1 platform supported backtraces

**Comment by steveklabnik** [comment]
Triage: Changing `hello world` to a panic.

Compiling with `msvc`:

```text
~\back [master +4 ~0 -0 !]> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target\debug\back.exe`
thread 'main' panicked at 'Hello, world!', src\main.rs:2:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:474
   7: std::panicking::begin_panic<str*>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\panicking.rs:408
   8: back::main
             at .\src\main.rs:2
   9: std::rt::lang_start::{{closure}}<()>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\rt.rs:64
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\rt.rs:49
  11: std::panicking::try::do_call<closure,i32>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:293
  12: panic_unwind::__rust_maybe_catch_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libpanic_unwind\lib.rs:85
  13: std::panicking::try
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panicking.rs:272
  14: std::panic::catch_unwind
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\panic.rs:394
  15: std::rt::lang_start_internal
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\/src\libstd\rt.rs:48
  16: std::rt::lang_start<()>
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c\src\libstd\rt.rs:64
  17: main
  18: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  19: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\back.exe` (exit code: 101)
```

With `gnu`:

```text
~\back [master +4 ~0 -0 !]> cargo +stable-x86_64-pc-windows-gnu run
   Compiling back v0.1.0 (C:\Users\steve\back)
    Finished dev [unoptimized + debuginfo] target(s) in 1.05s
     Running `target\debug\back.exe`
thread 'main' panicked at 'Hello, world!', src\main.rs:2:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace/dbghelp.rs:90
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src\libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd/panicking.rs:411
   8: back::main
             at src/main.rs:2
   9: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd/rt.rs:64
  10: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:49
  11: std::panicking::try::do_call
             at src\libstd/panicking.rs:296
  12: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:82
  13: std::panicking::try
             at src\libstd/panicking.rs:275
  14: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  15: std::rt::lang_start_internal
             at src\libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd/rt.rs:64
  17: main
  18: _tmainCRTStartup
  19: mainCRTStartup
  20: unit_addrs_search
  21: unit_addrs_search
error: process didn't exit successfully: `target\debug\back.exe` (exit code: 101)
```

These are pretty close to each other; has this been fixed?

**Comment by mati865** [comment]
@steveklabnik yes, it's resolved.

**Comment by steveklabnik** [comment]
Thanks!
