### ISSUE TITLE
test harness does not give file name for panics in macros

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#32981]
**Description**:
If a test case fails with a panic inside of a macro invocation, the test file name is not included in the stack trace. Originally reported as rust-lang/cargo#2581, but moved here at the request of the maintainers there.

**Steps to reproduce**:

``` rust
// test.rs
#[test]
fn it_works() {
    use std::collections::HashMap;
    let x: HashMap<&str, &str> = HashMap::new();
    assert_eq!(x["y"], "z");
}
```

**Actual output**:

``` console
$ rustc --test -g test.rs
$ ./test
running 1 test
test it_works ... FAILED

failures:

---- it_works stdout ----
    thread 'it_works' panicked at 'no entry found for key', ../src/libcore/option.rs:704
stack backtrace:
   1:     0x5600cbbf14a0 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x5600cbbf3e5b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x5600cbbf3a13 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x5600cbbe7bec - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x5600cbbe8038 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x5600cbbf0911 - rust_begin_unwind
   7:     0x5600cbc233ef - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x5600cbc27dd4 - option::expect_failed::ha2bedd125befb493uGO
   9:     0x5600cbba8cdf - option::Option<T>::expect::h5884297980627299622
                        at ../src/libcore/option.rs:298
  10:     0x5600cbba8c7f - collections::hash::map::HashMap<K, V, S>.Index<&'a Q>::index::h15197474938586646891
                        at ../src/libstd/collections/hash/map.rs:1315
  11:     0x5600cbba6e4b - it_works::h86b830f3898815a4eaa
                        at /tmp/src/<std macros>:5
  12:     0x5600cbbcadb6 - boxed::F.FnBox<A>::call_box::h12974170719861018744
  13:     0x5600cbbcd4ab - sys_common::unwind::try::try_fn::h16547832986514587285
  14:     0x5600cbbf089b - __rust_try
  15:     0x5600cbbee06d - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  16:     0x5600cbbcd82a - boxed::F.FnBox<A>::call_box::h8956144540797489804
  17:     0x5600cbbf2909 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  18:     0x7f1c7eb70423 - start_thread
  19:     0x7f1c7e699cbc - clone
  20:                0x0 - <unknown>


failures:
    it_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Notice that backtrace segment number 11 says that the error occurred in `/tmp/<std macros>:7`.

**Expected output**:

```
…
  11:     0x5600cbba6e4b - it_works::h86b830f3898815a4eaa
                        at /tmp/test.rs:7
…
```

**Comment by Mark-Simulacrum** [comment]
This works today, closing.

```
  12: test::it_works
             at ./test.rs:6
```
