### ISSUE TITLE
ICE when Attempting to Use an Unimportable Method in the Serde `deserializes_with` Attribute

### ISSUE THREAD

**Issue by indiv0** [rust-lang/rust#33051]
When attempting to compile a project utilizing the `deserialize_with` field annotation macro of [`Serde`](https://github.com/serde-rs/serde) with the annotation trying to use a function which is `not directly importable`, rustc panics.

This is the code that causes the issue:

`src/lib.rs`:

``` rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

extern crate serde;
extern crate serde_json;

use serde::{Deserialize, Deserializer, Error as SerdeError};
use serde::de::Visitor;

use ShapeName::deserialize_shape_name;

#[derive(Debug, Deserialize)]
pub struct MyStruct {
    #[serde(deserialize_with="deserialize_shape_name")]
    pub shape: String,
}

pub trait ShapeName: Sized {
    fn deserialize_shape_name<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer;
}

impl ShapeName for String {
    fn deserialize_shape_name<D>(deserializer: &mut D) -> Result<String, D::Error>
        where D: Deserializer,
    {
        String::deserialize(deserializer)
    }
}
```

`Cargo.toml`:

``` rust
[package]
name = "ice_example"
version = "0.1.0"

[dependencies]
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = "0.7.2"
```

Note that the correct code for this scenario would be:

``` rust
#![feature(custom_derive, plugin)]
#![plugin(serde_macros)]

extern crate serde;
extern crate serde_json;

use serde::{Deserialize, Deserializer, Error as SerdeError};
use serde::de::Visitor;

// use ShapeName::deserialize_shape_name; // This line is unnecessary

#[derive(Debug, Deserialize)]
pub struct MyStruct {
    #[serde(deserialize_with="ShapeName::deserialize_shape_name")] // The struct must be specified as well
    pub shape: String,
}

pub trait ShapeName: Sized {
    fn deserialize_shape_name<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer;
}

impl ShapeName for String {
    fn deserialize_shape_name<D>(deserializer: &mut D) -> Result<String, D::Error>
        where D: Deserializer,
    {
        String::deserialize(deserializer)
    }
}
```

I expected to see this happen:

The "`deserialize_shapes_map` is not directly importable" is expected since I'm trying to import a method, but the ICE should not be occuring.

So the above code should just fail to compile with a "`deserialize_shapes_map` is not directly importable" error.

This happened instead:

When compiling the code, it threw the expected "`deserialize_shapes_map` is not directly importable" error but also gave the following ICE:

``` sh
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'UFCS sugared method missing Self', ../src/libcore/option.rs:700
```
## Meta

`rustc --version --verbose`:

rustc 1.10.0-nightly (2174bd97c 2016-04-14)
binary: rustc
commit-hash: 2174bd97c1458d89a87eb2b614135d7ad68d6f18
commit-date: 2016-04-14
host: x86_64-unknown-linux-gnu
release: 1.10.0-nightly

Backtrace:

``` sh
─── cargo build --verbose                                                                                                                                                                     
       Fresh aster v0.15.0
       Fresh quasi v0.9.0
       Fresh quasi_codegen v0.9.0
       Fresh num-traits v0.1.32
       Fresh quasi_macros v0.9.0
       Fresh num-integer v0.1.32
       Fresh serde v0.7.0
       Fresh num-iter v0.1.32
       Fresh serde_codegen v0.7.2
       Fresh num v0.1.32
       Fresh serde_macros v0.7.2
       Fresh serde_json v0.7.0
   Compiling ice_example v0.1.0 (file:///home/indiv0/src/rust/ice_example)
     Running `rustc src/lib.rs --crate-name ice_example --crate-type lib -g --out-dir /home/indiv0/src/rust/ice_example/target/debug --emit=dep-info,link -L dependency=/home/indiv0/src/rust/ice_example/target/debug -L dependency=/home/indiv0/src/rust/ice_example/target/debug/deps --extern serde=/home/indiv0/src/rust/ice_example/target/debug/deps/libserde-3a777b14c091f0d1.rlib --extern serde_json=/home/indiv0/src/rust/ice_example/target/debug/deps/libserde_json-6edc82d6f60f8983.rlib --extern serde_macros=/home/indiv0/src/rust/ice_example/target/debug/deps/libserde_macros-eba2c386ff2377e8.so`
src/lib.rs:10:5: 10:38 error: `deserialize_shape_name` is not directly importable [E0253]
src/lib.rs:10 use ShapeName::deserialize_shape_name;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:10:5: 10:38 help: run `rustc --explain E0253` to see a detailed explanation
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'UFCS sugared method missing Self', ../src/libcore/option.rs:700
stack backtrace:
   1:     0x7ff7464f6600 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x7ff746503d4b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x7ff7465038ec - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x7ff7464c88bf - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x7ff7464ca9a8 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
   6:     0x7ff7464f3e11 - rust_begin_unwind
   7:     0x7ff74654d7cf - core::panicking::panic_fmt::h257ceb0aa351d801
   8:     0x7ff74656d6f4 - core::option::expect_failed::h2d57a5644f345e0b
   9:     0x7ff740c814d0 - rustc_typeck::check::instantiate_path::h0028f01e0d6c28a1
  10:     0x7ff740c7ade6 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::hdaa9a3d5d214eeb7
  11:     0x7ff740c8d67a - rustc_typeck::check::callee::check_call::h581c68eea83787eb
  12:     0x7ff740c7671e - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::hdaa9a3d5d214eeb7
  13:     0x7ff740c87828 - rustc_typeck::check::_match::check_match::he7382d310f6a62c7
  14:     0x7ff740c75ba1 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::hdaa9a3d5d214eeb7
  15:     0x7ff740cad6aa - rustc_typeck::check::check_decl_initializer::h4a842ce5ee3d42ee
  16:     0x7ff740cad771 - rustc_typeck::check::check_decl_local::h85cb2e43d704995a
  17:     0x7ff740cada61 - rustc_typeck::check::check_stmt::h7b32d7406e628d2a
  18:     0x7ff740c547c8 - rustc_typeck::check::check_block_with_expected::hc05ff1e7fff64a1e
  19:     0x7ff740c4c459 - rustc_typeck::check::check_fn::hb43882d54094ac4a
  20:     0x7ff740c49d0c - rustc_typeck::check::check_bare_fn::h7e4c2ad58d1814dd
  21:     0x7ff740c5904f - rustc_typeck::check::check_method_body::h7863cacbf117e455
  22:     0x7ff740c44d3e - rustc_typeck::check::check_item_body::h7ffec660fc242796
  23:     0x7ff740c3cab1 - rustc_typeck::check::check_item_bodies::ha729008a2e67410e
  24:     0x7ff740c3401f - rustc_typeck::check_crate::hb08ba31a6a5f65b5
  25:     0x7ff746a52a60 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::h5a042a091cd7658c
  26:     0x7ff746a50c6b - rustc::ty::context::TyCtxt::create_and_enter::h3f9051bcccbd93e4
  27:     0x7ff746a4d71e - rustc_driver::driver::phase_3_run_analysis_passes::h9c723484c588a35b
  28:     0x7ff746a1ff7f - rustc_driver::driver::compile_input::h0629572e6f316b31
  29:     0x7ff746a064e4 - rustc_driver::run_compiler::h8902aebf8b1849a8
  30:     0x7ff746a03941 - std::sys_common::unwind::try::try_fn::h4c74456035d0fcc7
  31:     0x7ff7464f3d9b - __rust_try
  32:     0x7ff7464f3d2d - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  33:     0x7ff746a0418a - _<F as std..boxed..FnBox<A>>::call_box::h27f542a39f1d61ef
  34:     0x7ff746501ee4 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  35:     0x7ff73e384423 - start_thread
  36:     0x7ff746160cbc - clone
  37:                0x0 - <unknown>

error: Could not compile `ice_example`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name ice_example --crate-type lib -g --out-dir /home/indiv0/src/rust/ice_example/target/debug --emit=dep-info,link -L dependency=/home/indiv0/src/rust/ice_example/target/debug -L dependency=/home/indiv0/src/rust/ice_example/target/debug/deps --extern serde=/home/indiv0/src/rust/ice_example/target/debug/deps/libserde-3a777b14c091f0d1.rlib --extern serde_json=/home/indiv0/src/rust/ice_example/target/debug/deps/libserde_json-6edc82d6f60f8983.rlib --extern serde_macros=/home/indiv0/src/rust/ice_example/target/debug/deps/libserde_macros-eba2c386ff2377e8.so` (exit code: 101)
```

**Comment by dtolnay** [comment]
No more ICE as of rustc 1.17.0-nightly (62eb6056d 2017-02-15) so I think this issue can be closed.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
use serde::{Deserialize, Deserializer};

use ShapeName::deserialize_shape_name;

#[derive(Debug, Deserialize)]
pub struct MyStruct {
    #[serde(deserialize_with="deserialize_shape_name")]
    pub shape: String,
}

pub trait ShapeName: Sized {
    fn deserialize_shape_name<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer;
}

impl ShapeName for String {
    fn deserialize_shape_name<D>(deserializer: D) -> Result<String, D::Error>
        where D: Deserializer
    {
        String::deserialize(deserializer)
    }
}
```

```
error[E0253]: `deserialize_shape_name` is not directly importable
 --> src/main.rs:7:5
  |
7 | use ShapeName::deserialize_shape_name;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be imported directly

error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
Closing as per previous comment.
