### ISSUE TITLE
ICE when macro substitution doesn't have */+

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#33150]
Regression from stable (present in beta and nightly)

The following code hits an ICE after emitting the expected error

``` rust
macro_rules! def_response_type {
    ($($n: $ty,)*) => {
        struct Bar {
            $($n: $ty,)
        }
        impl Bar {
        }
    };
}
```

```
<anon>:6:9: 6:13 error: expected `*` or `+`
<anon>:6         impl Bar {

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'internal error: entered unreachable code', ../src/libsyntax/parse/parser.rs:2857
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by tiehuis** [comment]
Another test case for what appears to be the same error.

```
macro_rules! x {
    ($1) => true
}
```

```
<anon>:2:7: 2:8 error: expected identifier, found `1`
<anon>:2     ($1) => true
               ^
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'internal error: entered unreachable code', ../src/libsyntax/parse/parser.rs:2849
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

http://is.gd/yHjQVd

**Comment by Mark-Simulacrum** [comment]
Neither example ICEs today, closing.
