### ISSUE TITLE
Spurious LLDB debuginfo test failures, "couldn't get the client port"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33350]
https://gist.github.com/alexcrichton/e0e6b34dae91356011b07c4dfd571016
http://buildbot.rust-lang.org/builders/auto-mac-64-opt-rustbuild/builds/944

```
failures:

---- [debuginfo-lldb] debuginfo-lldb/struct-namespace.rs stdout ----
	NOTE: compiletest thinks it is using LLDB version 330

error: line not found in debugger output: (struct_namespace::Struct1) $0 = [...]
status: exit code: 0
command: "/usr/bin/python" "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/etc/lldb_batchmode.py" "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj/build/x86_64-apple-darwin/test/debuginfo/struct-namespace.stage2-x86_64-apple-darwin" "/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj/build/x86_64-apple-darwin/test/debuginfo/struct-namespace.debugger.script"
stdout:
------------------------------------------
LLDB batch-mode script
----------------------
Debugger commands script is '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj/build/x86_64-apple-darwin/test/debuginfo/struct-namespace.debugger.script'.
Target executable is '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj/build/x86_64-apple-darwin/test/debuginfo/struct-namespace.stage2-x86_64-apple-darwin'.
Current working directory is '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj'
Creating a target for '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj/build/x86_64-apple-darwin/test/debuginfo/struct-namespace.stage2-x86_64-apple-darwin'
settings set auto-confirm true

version
lldb-330.0.48 
command script import /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/./src/etc/lldb_rust_formatters.py
type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
type category enable Rust

breakpoint set --file 'struct-namespace.rs' --line 66
Breakpoint 1: where = struct-namespace.stage2-x86_64-apple-darwin`struct_namespace::main + 70 at struct-namespace.rs:66, address = 0x0000000100000e66 
run
Hit breakpoint 1.1: where = struct-namespace.stage2-x86_64-apple-darwin`struct_namespace::main + 70 at struct-namespace.rs:66, address = 0x0000000100000e66, resolved, hit count = 1 
Process 97392 stopped * thread #1: tid = 0x202d5a8, 0x0000000100000e66 struct-namespace.stage2-x86_64-apple-darwin`struct_namespace::main + 70 at struct-namespace.rs:66, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1 frame #0: 0x0000000100000e66 struct-namespace.stage2-x86_64-apple-darwin`struct_namespace::main + 70 at struct-namespace.rs:66 63 64 let mod1_struct2 = mod1::Struct2(5); 65 -> 66 zzz(); // #break 67 } 68 69 #[inline(never)] Process 97392 launched: '/Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/obj/build/x86_64-apple-darwin/test/debuginfo/struct-namespace.stage2-x86_64-apple-darwin' (x86_64) 
p struct1
(struct_namespace::Struct1) $0 = Struct1 { a: 0, b: 1 } 
p struct2
(struct_namespace::Struct2) $1 = Struct2(2) 
p mod1_struct1
(struct_namespace::mod1::Struct1) $2 = Struct1 { a: 3, b: 4 } 
p mod1_struct2
(struct_namespace::mod1::Struct2) $3 = Struct2(5) 
quit


------------------------------------------
stderr:
------------------------------------------
2016-05-02 02:41:44.097 Python[97391:33740198] Metadata.framework [Error]: couldn't get the client port

------------------------------------------

thread '[debuginfo-lldb] debuginfo-lldb/struct-namespace.rs' panicked at 'explicit panic', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [debuginfo-lldb] debuginfo-lldb/struct-namespace.rs

test result: FAILED. 91 passed; 1 failed; 10 ignored; 0 measured
```

**Comment by michaelwoerister** [comment]
I'm wondering if this is really an error or just some warning that we also get in passing tests.

**Comment by alexcrichton** [comment]
Hm ok so actually this looks less suspicious than I thought

The error:

```
error: line not found in debugger output: (struct_namespace::Struct1) $0 = [...]
```

seems odd, because it does show up!

```
(struct_namespace::Struct1) $0 = Struct1 { a: 0, b: 1 } 
```

This may actually be related to the PR at hand (https://github.com/rust-lang/rust/pull/33225), so I'm gonna close this for now, but if it ends up being more spurious we can reopen. Sorry for the noise!
