### ISSUE TITLE
Spurious rbml failure in incremental tests

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33435]
http://buildbot.rust-lang.org/builders/auto-linux-64-opt-rustbuild/builds/983/steps/test/logs/stdio
https://gist.github.com/alexcrichton/df863e77c5c5de902151c189b7319d71
https://github.com/rust-lang/rust/pull/33091#issuecomment-217191997

```
failures:

---- [codegen-units] codegen-units/partitioning/local-drop-glue.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/local-drop-glue.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-drop-glue.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-drop-glue.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/local-drop-glue
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/local-drop-glue/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 30")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/local-drop-glue.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- [codegen-units] codegen-units/partitioning/local-generic.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/local-generic.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-generic.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-generic.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=eager -Zincremental=tmp/partitioning-tests/local-generic
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/local-generic/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 13")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/local-generic.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/local-inlining.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/local-inlining.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-inlining.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-inlining.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/local-inlining
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/local-inlining/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 5")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/local-inlining.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/local-transitive-inlining.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/local-transitive-inlining.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-transitive-inlining.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/local-transitive-inlining.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/local-transitive-inlining
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/local-transitive-inlining/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 9")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/local-transitive-inlining.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/regular-modules.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/regular-modules.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/regular-modules.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/regular-modules.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=eager -Zincremental=tmp/partitioning-tests/regular-modules
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/regular-modules/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 32")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/regular-modules.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/methods-are-with-self-type.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/methods-are-with-self-type.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/methods-are-with-self-type.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/methods-are-with-self-type.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/methods-are-with-self-type
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/methods-are-with-self-type/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 5")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/methods-are-with-self-type.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/statics.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/statics.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/statics.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/statics.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/statics
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/statics/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 31")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/statics.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/extern-drop-glue.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/extern-drop-glue.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/extern-drop-glue.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuthread '<main>' panicked at 'Some tests failed', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/main.rs:275
ild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/extern-drop-glue.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/extern-drop-glue
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/extern-drop-glue/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 5")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/extern-drop-glue.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/extern-generic.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/extern-generic.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/extern-generic.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/extern-generic.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=eager -Zincremental=tmp/partitioning-tests/extern-generic
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/extern-generic/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 15")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/extern-generic.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595

---- [codegen-units] codegen-units/partitioning/inlining-from-extern-crate.rs stdout ----
	
error: compilation failed!
status: exit code: 101
command: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/test/codegen-units/partitioning/inlining-from-extern-crate.rs -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units --target=x86_64-unknown-linux-gnu -L /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/inlining-from-extern-crate.stage2-x86_64-unknown-linux-gnu.codegen-units.libaux -C prefer-dynamic -o /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/test/codegen-units/partitioning/inlining-from-extern-crate.stage2-x86_64-unknown-linux-gnu -Crpath -Lnative=/buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/obj/build/x86_64-unknown-linux-gnu/rust-test-helpers -Zprint-trans-items=lazy -Zincremental=tmp/partitioning-tests/inlining-from-extern-crate
stdout:
------------------------------------------
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/libsyntax/errors/mod.rs:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.


------------------------------------------
stderr:
------------------------------------------
error: internal compiler error: /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/librustc_incremental/persist/load.rs:72: decoding error in dep-graph from `tmp/partitioning-tests/inlining-from-extern-crate/dep_graph.rbml`: Expected("Invalid tuple length. Expected 2, found 0")
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

------------------------------------------

thread '[codegen-units] codegen-units/partitioning/inlining-from-extern-crate.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt-rustbuild/build/src/tools/compiletest/src/runtest.rs:1595


failures:
    [codegen-units] codegen-units/partitioning/extern-drop-glue.rs
    [codegen-units] codegen-units/partitioning/extern-generic.rs
    [codegen-units] codegen-units/partitioning/inlining-from-extern-crate.rs
    [codegen-units] codegen-units/partitioning/local-drop-glue.rs
    [codegen-units] codegen-units/partitioning/local-generic.rs
    [codegen-units] codegen-units/partitioning/local-inlining.rs
    [codegen-units] codegen-units/partitioning/local-transitive-inlining.rs
    [codegen-units] codegen-units/partitioning/methods-are-with-self-type.rs
    [codegen-units] codegen-units/partitioning/regular-modules.rs
    [codegen-units] codegen-units/partitioning/statics.rs

test result: FAILED. 22 passed; 10 failed; 0 ignored; 0 measured
```

Looks like either these files are being read/written concurrently or we've got stale artifacts from previous builds.

cc @michaelwoerister, thoughts?

**Comment by alexcrichton** [comment]
cc @nikomatsakis

**Comment by eddyb** [comment]
The incremental code should probably use [`OpenOptions::create_new`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.create_new) instead of just `File::create`, but I still see no reason it could actually cause problems the way it is right now.
Each builder runs in its own directory, right? They each have their own `tmp` and the incremental code removes a file before trying to write it.

**Comment by eddyb** [comment]
Hang on, the problem is that it's trying to load the dep graph at all, which was written by a previous build run? Shouldn't we just nuke `tmp` before each build?

**Comment by alexcrichton** [comment]
I believe this was fixed by https://github.com/rust-lang/rust/pull/33130 in https://github.com/rust-lang/rust/pull/33130/commits/300162659504fed4798e535791023bf0174fc81c, so the spurious failures have at least been fixed for now, so closing.

**Comment by Eh2406** [comment]
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/main.rs#L302
Now that the issue is closed can the FIXME be fix, or made more specific?
