### ISSUE TITLE
ICE: Error constructed but not emitted

### ISSUE THREAD

**Issue by octplane** [rust-lang/rust#33760]
Hello,

When using `rustfmt` 0.5.0, with latest nightly `rustc 1.10.0-nightly (764ef92ae 2016-05-19)`, I have a ICE when formatting a very simple piece of code:

```
echo "pub mod foo;" | rustfmt
error: internal compiler error: Error constructed but not emitted
thread '<main>' panicked at 'explicit panic', /Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/errors/mod.rs:361
stack backtrace:
   1:        0x109284c58 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:        0x109286b15 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:        0x10928674e - std::panicking::default_hook::hc2c969e7453d080c
   4:        0x1092792b0 - std::panicking::rust_panic_with_hook::hfe203e3083c2b544
   5:        0x1090e96d4 - std::panicking::begin_panic::h4ebf9fe884b2415f
   6:        0x1090eb6a4 - _<errors..DiagnosticBuilder<'a> as std..ops..Drop>::drop::hf9983317f4db5217
   7:        0x108ff7f8b - rustfmt::format_input::hb55408203a5b2f7d
   8:        0x108ffcd7e - rustfmt::run::hc3c3f45cca8c2090
   9:        0x108fe9b86 - rustfmt::execute::h7a803e49ef9bfa61
  10:        0x108fec524 - rustfmt::main::h72bee7f7a14fa8c0
  11:        0x10928633d - std::panicking::try::call::hc5e1f5b484ec7f0e
  12:        0x109289dab - __rust_try
  13:        0x109289d45 - __rust_maybe_catch_panic
  14:        0x109286161 - std::rt::lang_start::h61f4934e780b4dfc
```

Not sure where to report that but folks #rust-fr told me this was the place because this is an ICE.

`cargo install rustfmt` trace so that we have all deps version:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt v0.5.0
 Downloading diff v0.1.9
 Downloading rustc-serialize v0.3.19
 Downloading syntex_syntax v0.32.0
 Downloading toml v0.1.30
 Downloading regex v0.1.71
 Downloading unicode-segmentation v0.1.2
 Downloading term v0.4.4
 Downloading strings v0.0.1
 Downloading log v0.3.6
 Downloading env_logger v0.3.3
 Downloading getopts v0.2.14
 Downloading libc v0.2.11
 Downloading unicode-xid v0.0.3
 Downloading term v0.2.14
 Downloading bitflags v0.5.0
 Downloading kernel32-sys v0.2.2
 Downloading winapi v0.2.7
 Downloading winapi-build v0.1.1
 Downloading memchr v0.1.11
 Downloading aho-corasick v0.5.2
 Downloading utf8-ranges v0.1.3
 Downloading thread_local v0.2.5
 Downloading regex-syntax v0.3.2
 Downloading thread-id v2.0.0
   Compiling bitflags v0.5.0
   Compiling unicode-xid v0.0.3
   Compiling log v0.3.6
   Compiling libc v0.2.11
   Compiling utf8-ranges v0.1.3
   Compiling rustc-serialize v0.3.19
   Compiling unicode-segmentation v0.1.2
   Compiling getopts v0.2.14
   Compiling regex-syntax v0.3.2
   Compiling diff v0.1.9
   Compiling winapi-build v0.1.1
   Compiling strings v0.0.1
   Compiling kernel32-sys v0.2.2
   Compiling winapi v0.2.7
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.2
   Compiling thread-id v2.0.0
   Compiling term v0.2.14
   Compiling thread_local v0.2.5
   Compiling term v0.4.4
   Compiling regex v0.1.71
   Compiling syntex_syntax v0.32.0
   Compiling toml v0.1.30
   Compiling env_logger v0.3.3
   Compiling rustfmt v0.5.0
```

**Comment by nagisa** [comment]
A rule of thumb is: if some ICE does not happen when compiling with nightly rustc, reporting the issue against rust repository is probably not what you want to do. 

What you probably should have done is reporting this against rustfmt.

Also rustfmt does not interact with rustc in any way, it uses a crate called syntex where the error originates, as can be seen in this path: `thread '<main>' panicked at 'explicit panic', /Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/errors/mod.rs:361`

**Comment by nagisa** [comment]
cc @nrc @marcusklaas either way.

**Comment by nrc** [comment]
Yeah, this looks like a Rustfmt bug, in fact I think I fixed it last week. @octplane could you test with master and see if it fixes this please? If not, I'll take a look.

@nagisa syntex is just a mirror of libsyntax, so errors there should be reported and fixed here.

**Comment by octplane** [comment]
Yep. closed. THXBYE :)
