### ISSUE TITLE
Error compiling on stable, works in nightly

### ISSUE THREAD

**Issue by jordanbray** [rust-lang/rust#33799]
I have been having trouble compiling my project using the latest stable compiler.  It has been working with nightly this whole time :/

It fails when compiling existing modules within cargo, not when compiling my code.

If any more information is needed, please let me know.  I'm not sure what I can do to help.

Here's the output from "cargo build" in both cases.

[jordan@localhost src]$ rustup default stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.8.0 (db2939409 2016-04-11)

[jordan@localhost src]$ RUST_BACKTRACE=1 cargo build --verbose
   Compiling lazy_static v0.1.16
     Running `rustc /home/jordan/.cargo/registry/src/github.com-88ac128001ac3a9a/lazy_static-0.1.16/src/lib.rs --crate-name lazy_static --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=e69e55dcc7527931 -C extra-filename=-e69e55dcc7527931 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling winapi v0.2.6
     Running `rustc /home/jordan/.cargo/registry/src/github.com-88ac128001ac3a9a/winapi-0.2.6/src/lib.rs --crate-name winapi --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=153e1a405ad119e7 -C extra-filename=-153e1a405ad119e7 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling winapi-build v0.1.1
     Running `rustc /home/jordan/.cargo/registry/src/github.com-88ac128001ac3a9a/winapi-build-0.1.1/src/lib.rs --crate-name build --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=7bc4b8a4c9d61577 -C extra-filename=-7bc4b8a4c9d61577 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling libc v0.2.10
     Running `rustc /home/jordan/.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.2.10/src/lib.rs --crate-name libc --crate-type lib -C opt-level=3 -g -C debug-assertions=on --cfg feature=\"default\" --cfg feature=\"use_std\" -C metadata=12d5d911cf5411c3 -C extra-filename=-12d5d911cf5411c3 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7faecebb9330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7faecebc268b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7faecebc21e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7faeceb869ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7faeceb87448 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x7faecebb6d91 - rust_begin_unwind
   7:     0x7faecec097af - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x7faec693a31b - result::unwrap_failed::h14307315525592478485
   9:     0x7faec693a28e - Doc<'doc>::as_str_slice::ha91bf39a19faeabdHVa
  10:     0x7faecc81545f - loader::Context<'a>::extract_one::h945c702fbde346e3Eem
  11:     0x7faecc80cacf - loader::Context<'a>::find_library_crate::h30971509c344ad3bD3l
  12:     0x7faecc7f1f16 - loader::Context<'a>::load_library_crate::h0ade06e110892b81WSl
  13:     0x7faecc7f0d99 - creader::CrateReader<'a>::resolve_crate::he1542772b02d0896E3j
  14:     0x7faecc7f258d - creader::CrateReader<'a>::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::closure.38792
  15:     0x7faecc7f233c - collections::hash::map::HashMap<K, V, S>.FromIterator<(K, V)>::from_iter::h12379182329167058746
  16:     0x7faecc7ee4dd - creader::CrateReader<'a>::register_crate::h62645edecf14372cTZj
  17:     0x7faecc7f345c - creader::CrateReader<'a>::read_extension_crate::hb5e653870a478718Zak
  18:     0x7faecc7f56b5 - creader::CrateReader<'a>::read_exported_macros::h2322639de24bfa4cUek
  19:     0x7faecc81ad0d - macro_import::MacroLoader<'a>.Visitor<'v>::visit_item::hf3405d18ebfdd3eakYm
  20:     0x7faecc81988a - macro_import::read_macro_defs::h345dbb1da4180a9foXm
  21:     0x7faecf0cdd89 - driver::phase_2_configure_and_expand::h0bbd128ff132a80elBa
  22:     0x7faecf0b3b21 - driver::compile_input::h7ae6a86e23de0774Hca
  23:     0x7faecf0a4b47 - run_compiler::hb0408bcf47642fe6mPc
  24:     0x7faecf0a22c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  25:     0x7faecebb6d1b - __rust_try
  26:     0x7faecebaf1fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  27:     0x7faecf0a2b10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  28:     0x7faecebc0c59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  29:     0x7faec7e41473 - start_thread
  30:     0x7faece83169c - clone
  31:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7f5afcd29330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7f5afcd3268b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7f5afcd321e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7f5afccf69ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7f5afccf7448 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x7f5afcd26d91 - rust_begin_unwind
   7:     0x7f5afcd797af - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x7f5af4aaa31b - result::unwrap_failed::h14307315525592478485
   9:     0x7f5af4aaa28e - Doc<'doc>::as_str_slice::ha91bf39a19faeabdHVa
  10:     0x7f5afa98545f - loader::Context<'a>::extract_one::h945c702fbde346e3Eem
  11:     0x7f5afa97cacf - loader::Context<'a>::find_library_crate::h30971509c344ad3bD3l
  12:     0x7f5afa961f16 - loader::Context<'a>::load_library_crate::h0ade06e110892b81WSl
  13:     0x7f5afa960d99 - creader::CrateReader<'a>::resolve_crate::he1542772b02d0896E3j
  14:     0x7f5afa96258d - creader::CrateReader<'a>::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::closure.38792
  15:     0x7f5afa96233c - collections::hash::map::HashMap<K, V, S>.FromIterator<(K, V)>::from_iter::h12379182329167058746
  16:     0x7f5afa95e4dd - creader::CrateReader<'a>::register_crate::h62645edecf14372cTZj
  17:     0x7f5afa96345c - creader::CrateReader<'a>::read_extension_crate::hb5e653870a478718Zak
  18:     0x7f5afa9656b5 - creader::CrateReader<'a>::read_exported_macros::h2322639de24bfa4cUek
  19:     0x7f5afa98ad0d - macro_import::MacroLoader<'a>.Visitor<'v>::visit_item::hf3405d18ebfdd3eakYm
  20:     0x7f5afa98988a - macro_import::read_macro_defs::h345dbb1da4180a9foXm
  21:     0x7f5afd23dd89 - driver::phase_2_configure_and_expand::h0bbd128ff132a80elBa
  22:     0x7f5afd223b21 - driver::compile_input::h7ae6a86e23de0774Hca
  23:     0x7f5afd214b47 - run_compiler::hb0408bcf47642fe6mPc
  24:     0x7f5afd2122c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  25:     0x7f5afcd26d1b - __rust_try
  26:     0x7f5afcd1f1fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  27:     0x7f5afd212b10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  28:     0x7f5afcd30c59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  29:     0x7f5af5fb1473 - start_thread
  30:     0x7f5afc9a169c - clone
  31:                0x0 - <unknown>

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7f140fc19330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7f140fc2268b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7f140fc221e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7f140fbe69ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7f140fbe7448 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x7f140fc16d91 - rust_begin_unwind
   7:     0x7f140fc697af - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x7f140799a31b - result::unwrap_failed::h14307315525592478485
   9:     0x7f140799a28e - Doc<'doc>::as_str_slice::ha91bf39a19faeabdHVa
  10:     0x7f140d87545f - loader::Context<'a>::extract_one::h945c702fbde346e3Eem
  11:     0x7f140d86cacf - loader::Context<'a>::find_library_crate::h30971509c344ad3bD3l
  12:     0x7f140d851f16 - loader::Context<'a>::load_library_crate::h0ade06e110892b81WSl
  13:     0x7f140d850d99 - creader::CrateReader<'a>::resolve_crate::he1542772b02d0896E3j
  14:     0x7f140d85258d - creader::CrateReader<'a>::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::closure.38792
  15:     0x7f140d85233c - collections::hash::map::HashMap<K, V, S>.FromIterator<(K, V)>::from_iter::h12379182329167058746
  16:     0x7f140d84e4dd - creader::CrateReader<'a>::register_crate::h62645edecf14372cTZj
  17:     0x7f140d85345c - creader::CrateReader<'a>::read_extension_crate::hb5e653870a478718Zak
  18:     0x7f140d8556b5 - creader::CrateReader<'a>::read_exported_macros::h2322639de24bfa4cUek
  19:     0x7f140d87ad0d - macro_import::MacroLoader<'a>.Visitor<'v>::visit_item::hf3405d18ebfdd3eakYm
  20:     0x7f140d87988a - macro_import::read_macro_defs::h345dbb1da4180a9foXm
  21:     0x7f141012dd89 - driver::phase_2_configure_and_expand::h0bbd128ff132a80elBa
  22:     0x7f1410113b21 - driver::compile_input::h7ae6a86e23de0774Hca
  23:     0x7f1410104b47 - run_compiler::hb0408bcf47642fe6mPc
  24:     0x7f14101022c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  25:     0x7f140fc16d1b - __rust_try
  26:     0x7f140fc0f1fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  27:     0x7f1410102b10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  28:     0x7f140fc20c59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  29:     0x7f1408ea1473 - start_thread
  30:     0x7f140f89169c - clone
  31:                0x0 - <unknown>

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7efee2a61330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7efee2a6a68b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7efee2a6a1e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7efee2a2e9ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7efee2a2f448 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x7efee2a5ed91 - rust_begin_unwind
   7:     0x7efee2ab17af - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x7efeda7e231b - result::unwrap_failed::h14307315525592478485
   9:     0x7efeda7e228e - Doc<'doc>::as_str_slice::ha91bf39a19faeabdHVa
  10:     0x7efee06bd45f - loader::Context<'a>::extract_one::h945c702fbde346e3Eem
  11:     0x7efee06b4acf - loader::Context<'a>::find_library_crate::h30971509c344ad3bD3l
  12:     0x7efee0699f16 - loader::Context<'a>::load_library_crate::h0ade06e110892b81WSl
  13:     0x7efee0698d99 - creader::CrateReader<'a>::resolve_crate::he1542772b02d0896E3j
  14:     0x7efee069a58d - creader::CrateReader<'a>::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::closure.38792
  15:     0x7efee069a33c - collections::hash::map::HashMap<K, V, S>.FromIterator<(K, V)>::from_iter::h12379182329167058746
  16:     0x7efee06964dd - creader::CrateReader<'a>::register_crate::h62645edecf14372cTZj
  17:     0x7efee069b45c - creader::CrateReader<'a>::read_extension_crate::hb5e653870a478718Zak
  18:     0x7efee069d6b5 - creader::CrateReader<'a>::read_exported_macros::h2322639de24bfa4cUek
  19:     0x7efee06c2d0d - macro_import::MacroLoader<'a>.Visitor<'v>::visit_item::hf3405d18ebfdd3eakYm
  20:     0x7efee06c188a - macro_import::read_macro_defs::h345dbb1da4180a9foXm
  21:     0x7efee2f75d89 - driver::phase_2_configure_and_expand::h0bbd128ff132a80elBa
  22:     0x7efee2f5bb21 - driver::compile_input::h7ae6a86e23de0774Hca
  23:     0x7efee2f4cb47 - run_compiler::hb0408bcf47642fe6mPc
  24:     0x7efee2f4a2c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  25:     0x7efee2a5ed1b - __rust_try
  26:     0x7efee2a571fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  27:     0x7efee2f4ab10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  28:     0x7efee2a68c59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  29:     0x7efedbce9473 - start_thread
  30:     0x7efee26d969c - clone
  31:                0x0 - <unknown>

Could not compile `lazy_static`.

Caused by:
  Process didn't exit successfully: `rustc /home/jordan/.cargo/registry/src/github.com-88ac128001ac3a9a/lazy_static-0.1.16/src/lib.rs --crate-name lazy_static --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=e69e55dcc7527931 -C extra-filename=-e69e55dcc7527931 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow` (exit code: 101)
[jordan@localhost src]$ rustup default nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.10.0-nightly (476fe6eef 2016-05-21)

[jordan@localhost src]$ RUST_BACKTRACE=1 cargo build --verbose
   Compiling lazy_static v0.1.16
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.1.16/src/lib.rs --crate-name lazy_static --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=3a04918be71c80ee -C extra-filename=-3a04918be71c80ee --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling winapi-build v0.1.1
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-build-0.1.1/src/lib.rs --crate-name build --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=493a7b0628804707 -C extra-filename=-493a7b0628804707 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling winapi v0.2.6
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.2.6/src/lib.rs --crate-name winapi --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=0f5f77a5f89d9e92 -C extra-filename=-0f5f77a5f89d9e92 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling libc v0.2.10
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.10/src/lib.rs --crate-name libc --crate-type lib -C opt-level=3 -g -C debug-assertions=on --cfg feature=\"use_std\" --cfg feature=\"default\" -C metadata=52c343f029f850c4 -C extra-filename=-52c343f029f850c4 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --cap-lints allow`
   Compiling kernel32-sys v0.2.2
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/build.rs --crate-name build_script_build --crate-type bin -C opt-level=3 -g -C debug-assertions=on --out-dir /home/jordan/Projects/thekingsmen/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --extern build=/home/jordan/Projects/thekingsmen/target/debug/deps/libbuild-493a7b0628804707.rlib --cap-lints allow`
     Running `/home/jordan/Projects/thekingsmen/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef/build-script-build`
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/src/lib.rs --crate-name kernel32 --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=df86a08647459244 -C extra-filename=-df86a08647459244 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --extern winapi=/home/jordan/Projects/thekingsmen/target/debug/deps/libwinapi-0f5f77a5f89d9e92.rlib --cap-lints allow`
   Compiling rand v0.3.14
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.3.14/src/lib.rs --crate-name rand --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=49a08859d086fffe -C extra-filename=-49a08859d086fffe --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --extern libc=/home/jordan/Projects/thekingsmen/target/debug/deps/liblibc-52c343f029f850c4.rlib --cap-lints allow`
   Compiling time v0.1.35
     Running `rustc /home/jordan/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.35/src/lib.rs --crate-name time --crate-type lib -C opt-level=3 -g -C debug-assertions=on -C metadata=750bfdd52feafcb7 -C extra-filename=-750bfdd52feafcb7 --out-dir /home/jordan/Projects/thekingsmen/target/debug/deps --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --extern kernel32=/home/jordan/Projects/thekingsmen/target/debug/deps/libkernel32-df86a08647459244.rlib --extern winapi=/home/jordan/Projects/thekingsmen/target/debug/deps/libwinapi-0f5f77a5f89d9e92.rlib --extern libc=/home/jordan/Projects/thekingsmen/target/debug/deps/liblibc-52c343f029f850c4.rlib --cap-lints allow`
   Compiling thekingsmen v0.0.1 (file:///home/jordan/Projects/thekingsmen)
     Running `rustc lib.rs --crate-name thekingsmen --crate-type lib -C opt-level=3 -g -C debug-assertions=on --out-dir /home/jordan/Projects/thekingsmen/target/debug --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --extern rand=/home/jordan/Projects/thekingsmen/target/debug/deps/librand-49a08859d086fffe.rlib --extern lazy_static=/home/jordan/Projects/thekingsmen/target/debug/deps/liblazy_static-3a04918be71c80ee.rlib --extern time=/home/jordan/Projects/thekingsmen/target/debug/deps/libtime-750bfdd52feafcb7.rlib`
board.rs:5:22: 5:33 warning: unused import, #[warn(unused_imports)] on by default
board.rs:5 use square::{Square, NUM_SQUARES};
                                ^~~~~~~~~~~
board.rs:588:13: 588:14 warning: unused variable: `x`, #[warn(unused_variables)] on by default
board.rs:588         for x in 0..depth {
                         ^
board.rs:595:5: 597:6 warning: method is never used: `in_check`, #[warn(dead_code)] on by default
board.rs:595     fn in_check(&self) -> bool {
                 ^
     Running `rustc main.rs --crate-name thekingsmen --crate-type bin -C opt-level=3 -g -C debug-assertions=on --out-dir /home/jordan/Projects/thekingsmen/target/debug --emit=dep-info,link -L dependency=/home/jordan/Projects/thekingsmen/target/debug -L dependency=/home/jordan/Projects/thekingsmen/target/debug/deps --extern rand=/home/jordan/Projects/thekingsmen/target/debug/deps/librand-49a08859d086fffe.rlib --extern lazy_static=/home/jordan/Projects/thekingsmen/target/debug/deps/liblazy_static-3a04918be71c80ee.rlib --extern time=/home/jordan/Projects/thekingsmen/target/debug/deps/libtime-750bfdd52feafcb7.rlib --extern thekingsmen=/home/jordan/Projects/thekingsmen/target/debug/libthekingsmen.rlib`
piece.rs:13:1: 13:129 warning: constant item is never used: `ALL_PIECES`, #[warn(dead_code)] on by default
piece.rs:13 pub const ALL_PIECES: [Piece; NUM_PIECES] = [Piece::Pawn, Piece::Knight, Piece::Bishop, Piece::Rook, Piece::Queen, Piece::King];
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
square.rs:25:5: 30:6 warning: method is never used: `forward`, #[warn(dead_code)] on by default
square.rs:25     pub fn forward(&self, color: Color) -> Option<Square> {
                 ^
square.rs:32:5: 37:6 warning: method is never used: `backward`, #[warn(dead_code)] on by default
square.rs:32     pub fn backward(&self, color: Color) -> Option<Square> {
                 ^
square.rs:86:5: 91:6 warning: method is never used: `ubackward`, #[warn(dead_code)] on by default
square.rs:86     pub fn ubackward(&self, color: Color) -> Square {
                 ^
bitboard.rs:98:5: 100:6 warning: method is never used: `from_maybe_square`, #[warn(dead_code)] on by default
bitboard.rs:98     pub fn from_maybe_square(sq: Option<Square>) -> Option<BitBoard> {
                   ^
bitboard.rs:110:5: 112:6 warning: method is never used: `reverse_colors`, #[warn(dead_code)] on by default
bitboard.rs:110     pub fn reverse_colors(&self) -> BitBoard {
                    ^
bitboard.rs:124:5: 128:6 warning: method is never used: `get_file`, #[warn(dead_code)] on by default
bitboard.rs:124     pub fn get_file(f: u8) -> BitBoard {
                    ^
board.rs:5:22: 5:33 warning: unused import, #[warn(unused_imports)] on by default
board.rs:5 use square::{Square, NUM_SQUARES};
                                ^~~~~~~~~~~
board.rs:340:5: 358:6 warning: method is never used: `is_sane`, #[warn(dead_code)] on by default
board.rs:340     pub fn is_sane(&self) -> bool {
                 ^
board.rs:588:13: 588:14 warning: unused variable: `x`, #[warn(unused_variables)] on by default
board.rs:588         for x in 0..depth {
                         ^
board.rs:595:5: 597:6 warning: method is never used: `in_check`, #[warn(dead_code)] on by default
board.rs:595     fn in_check(&self) -> bool {
                 ^
[jordan@localhost src]$

**Comment by jordanbray** [comment]
"cargo clean" resolves the issue

**Comment by jordanbray** [comment]
Duplicate of  #33778.
