### ISSUE TITLE
Error unable to find scope infor for NodeExpr on Stable and Nightly when using std::path::MAIN_SEPARATOR

### ISSUE THREAD

**Issue by elliottneilclark** [rust-lang/rust#34331]
Unable to compile danielpclark/faster_path on either stable or nightly.

I tried this:
`git clone https://github.com/danielpclark/faster_path.git && cd faster_path && cargo update && cargo test`
I expected to see this happen: it either to compile or provide a compilation error.
Instead, this happened: The compiler panicked.
## Stable

`rustc --version --verbose`:
rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: x86_64-apple-darwin
release: 1.9.0

Backtrace:

```
RUST_BACKTRACE=1 cargo build --verbose                                                                                    101 ↵
       Fresh libc v0.2.11
   Compiling faster_path v0.0.1 (file:///Users/elliott/Code/Public/faster_path)
     Running `rustc src/lib.rs --crate-name faster_path --crate-type dylib -g --out-dir /Users/elliott/Code/Public/faster_path/target/debug --emit=dep-info,link -L dependency=/Users/elliott/Code/Public/faster_path/target/debug -L dependency=/Users/elliott/Code/Public/faster_path/target/debug/deps --extern libc=/Users/elliott/Code/Public/faster_path/target/debug/deps/liblibc-38919d24e617a235.rlib`
src/basename_for_chop.rs:20:12: 20:26 error: internal compiler error: ../src/librustc_trans/debuginfo/metadata.rs:910: debuginfo: Could not find scope info for node NodeExpr(expr(1173: '/'))
src/basename_for_chop.rs:20       Some(MAIN_SEPARATOR) => { offset = offset + 1 },
                                       ^~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:536
stack backtrace:
   1:        0x1081b23a8 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:        0x1081be7f5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:        0x1081be32f - std::panicking::default_hook::haac48fa641db8fa2
   4:        0x108182f86 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:        0x10460ce6b - std::sys_common::unwind::begin_unwind::hb6dfe67d47a39536
   6:        0x10460ce0b - syntax::errors::Handler::span_bug::h98fe6cb651d17ad3
   7:        0x104642e8f - rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::hda87a029f26efa73
   8:        0x104642d66 - rustc::session::span_bug_fmt::hbb98cefb6da7b8d2
   9:        0x1046f7ebb - rustc_trans::debuginfo::metadata::scope_metadata::h8bc8a8d2f7e800cb
  10:        0x1046eaeea - rustc_trans::debuginfo::source_loc::set_source_location::h8b3972858edfdcb2
  11:        0x104645db1 - rustc_trans::build::ICmp::hfb8885280dc80daf
  12:        0x104652206 - rustc_trans::base::compare_scalar_types::hcae3d4bada8a343b
  13:        0x10473564a - rustc_trans::_match::compile_submatch_continue::hcd7f8b7be900c70d
  14:        0x104731680 - rustc_trans::_match::compile_submatch::h1de5752782f6605b
  15:        0x104736f60 - rustc_trans::_match::compile_submatch_continue::hcd7f8b7be900c70d
  16:        0x104731680 - rustc_trans::_match::compile_submatch::h1de5752782f6605b
  17:        0x1047398c8 - rustc_trans::_match::trans_match_inner::hed0f6414d25cfb0d
  18:        0x104703b04 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hfc708f6d884d180a
  19:        0x10467bb35 - rustc_trans::expr::trans_into::h42fcfc33be1fd4c2
  20:        0x10467321e - rustc_trans::controlflow::trans_block::hbf71b2a467189fc4
  21:        0x104707a0f - rustc_trans::expr::trans_rvalue_stmt_unadjusted::h6a58e578dd012c09
  22:        0x10467bb05 - rustc_trans::expr::trans_into::h42fcfc33be1fd4c2
  23:        0x1046e0f62 - rustc_trans::controlflow::trans_stmt_semi::hcba83f2a6075f097
  24:        0x104672f16 - rustc_trans::controlflow::trans_block::hbf71b2a467189fc4
  25:        0x104671780 - rustc_trans::base::trans_closure::h3bda42021fe9c927
  26:        0x104673911 - rustc_trans::base::trans_fn::he1c838fa1dbfdc03
  27:        0x10467e165 - rustc_trans::base::trans_item::hf167e469e36b8935
  28:        0x104696416 - _<base..TransItemsWithinModVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::hfd0663a7c8d5f16c
  29:        0x104694356 - rustc::hir::intravisit::walk_item::h511d7aa5180d79ae
  30:        0x104684eae - rustc_trans::base::trans_crate::h62301dd3c79c73a7
  31:        0x103d1f73a - rustc_driver::driver::phase_4_translate_to_llvm::hd44e506f53bb81e3
  32:        0x103d1deec - rustc_driver::driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::h9811bece2a8f1da7
  33:        0x103d1a7dd - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hc699330eb6f2bc1e
  34:        0x103d14392 - rustc::ty::context::TyCtxt::create_and_enter::h656b2d3a4956519e
  35:        0x103d10cdc - rustc_driver::driver::phase_3_run_analysis_passes::h83da042ec4b8ea10
  36:        0x103ce4571 - rustc_driver::driver::compile_input::h6491aaddd9e61258
  37:        0x103ccad8f - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  38:        0x103cc8122 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  39:        0x1081afb3b - __rust_try
  40:        0x1081afac3 - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  41:        0x103cc89b9 - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  42:        0x1081bd6c8 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  43:     0x7fff9478c99c - _pthread_body
  44:     0x7fff9478c919 - _pthread_start

error: Could not compile `faster_path`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name faster_path --crate-type dylib -g --out-dir /Users/elliott/Code/Public/faster_path/target/debug --emit=dep-info,link -L dependency=/Users/elliott/Code/Public/faster_path/target/debug -L dependency=/Users/elliott/Code/Public/faster_path/target/debug/deps --extern libc=/Users/elliott/Code/Public/faster_path/target/debug/deps/liblibc-38919d24e617a235.rlib` (exit code: 101)
```
## Nightly

`rustc --version --verbose`:

```
rustc 1.11.0-nightly (bb4a79b08 2016-06-15)
binary: rustc
commit-hash: bb4a79b087158f396b984bdf552d2c90890b12a3
commit-date: 2016-06-15
host: x86_64-apple-darwin
release: 1.11.0-nightly
```

Backtrace:

```
RUST_BACKTRACE=1 cargo build --verbose
   Compiling libc v0.2.11
     Running `rustc /Users/elliott/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.11/src/lib.rs --crate-name libc --crate-type lib -g --cfg feature=\"default\" --cfg feature=\"use_std\" -C metadata=6b483f9a7097e9a4 -C extra-filename=-6b483f9a7097e9a4 --out-dir /Users/elliott/Code/Public/faster_path/target/debug/deps --emit=dep-info,link -L dependency=/Users/elliott/Code/Public/faster_path/target/debug/deps -L dependency=/Users/elliott/Code/Public/faster_path/target/debug/deps --cap-lints allow`
   Compiling faster_path v0.0.1 (file:///Users/elliott/Code/Public/faster_path)
     Running `rustc src/lib.rs --crate-name faster_path --crate-type dylib -g --out-dir /Users/elliott/Code/Public/faster_path/target/debug --emit=dep-info,link -L dependency=/Users/elliott/Code/Public/faster_path/target/debug -L dependency=/Users/elliott/Code/Public/faster_path/target/debug/deps --extern libc=/Users/elliott/Code/Public/faster_path/target/debug/deps/liblibc-6b483f9a7097e9a4.rlib`
src/basename_for_chop.rs:20:12: 20:26 error: internal compiler error: ../src/librustc_trans/debuginfo/metadata.rs:909: debuginfo: Could not find scope info for node NodeExpr(expr(1163: '/'))
src/basename_for_chop.rs:20       Some(MAIN_SEPARATOR) => { offset = offset + 1 },
                                       ^~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:545
stack backtrace:
   1:        0x1134500ab - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:        0x11345ca5a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:        0x11345c58b - std::panicking::default_hook::he0146e6a74621cb4
   4:        0x113422368 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:        0x10f11252b - std::panicking::begin_panic::hf9f206df23a555af
   6:        0x10f1123bd - rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::h083e19915ee66466
   7:        0x10f1121a2 - rustc::session::span_bug_fmt::h0ed5e1c04618deff
   8:        0x10f1f0bb1 - rustc_trans::debuginfo::metadata::scope_metadata::h88a7aa4543e957f8
   9:        0x10f1e3560 - rustc_trans::debuginfo::source_loc::set_source_location::h72462a7b259b1995
  10:        0x10f1156ef - rustc_trans::build::ICmp::hecf445429fe7bc68
  11:        0x10f1229c3 - rustc_trans::base::compare_scalar_types::h976479cb6082dcea
  12:        0x10f234b8a - rustc_trans::_match::compile_submatch_continue::hddafc0ec12927206
  13:        0x10f230400 - rustc_trans::_match::compile_submatch::hd9532ace09ec5f72
  14:        0x10f2366f1 - rustc_trans::_match::compile_submatch_continue::hddafc0ec12927206
  15:        0x10f230400 - rustc_trans::_match::compile_submatch::hd9532ace09ec5f72
  16:        0x10f239589 - rustc_trans::_match::trans_match_inner::h6c279313259c5422
  17:        0x10f1fcf63 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hadda29044ed9a2df
  18:        0x10f14c28a - rustc_trans::expr::trans_into::h39379abaf24a5d90
  19:        0x10f143581 - rustc_trans::controlflow::trans_block::h7ec6b213337f773e
  20:        0x10f200f99 - rustc_trans::expr::trans_rvalue_stmt_unadjusted::h3b7a708ec9feb123
  21:        0x10f14c25a - rustc_trans::expr::trans_into::h39379abaf24a5d90
  22:        0x10f1dcf1f - rustc_trans::controlflow::trans_stmt_semi::hd28c1af600c97612
  23:        0x10f1431d0 - rustc_trans::controlflow::trans_block::h7ec6b213337f773e
  24:        0x10f13d632 - rustc_trans::base::trans_closure::h9e96f7e9279dd729
  25:        0x10f143dfd - rustc_trans::base::trans_fn::ha453f4075c16fe7d
  26:        0x10f14e7b2 - rustc_trans::base::trans_item::hca2904a0eb6b2a6f
  27:        0x10f166e81 - _<rustc_trans..base..TransItemsWithinModVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::hc86f557d139a067e
  28:        0x10f165298 - rustc::hir::intravisit::walk_item::he9a143fadf3af5d7
  29:        0x10f157c71 - rustc_trans::base::trans_crate::h999c47a06d45abea
  30:        0x10e9bbc9a - rustc_driver::driver::phase_4_translate_to_llvm::had910d0e745bc40f
  31:        0x10e9b907f - rustc_driver::driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::hf187cb470aad2bf2
  32:        0x10e9b5754 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hd565ad56c5876a16
  33:        0x10e9af410 - rustc::ty::context::TyCtxt::create_and_enter::habef58c7230d34f9
  34:        0x10e979901 - rustc_driver::driver::compile_input::hfd60b020f6d0208d
  35:        0x10e9666d4 - rustc_driver::run_compiler::h884d01d12eb76bbb
  36:        0x10e9636df - std::panicking::try::call::hd72cf79141f67e60
  37:        0x113463b3b - __rust_try
  38:        0x113463ad5 - __rust_maybe_catch_panic
  39:        0x10e9641eb - _<F as alloc..boxed..FnBox<A>>::call_box::h589d2091babf223a
  40:        0x11345b4d8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  41:     0x7fff9478c99c - _pthread_body
  42:     0x7fff9478c919 - _pthread_start

error: Could not compile `faster_path`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name faster_path --crate-type dylib -g --out-dir /Users/elliott/Code/Public/faster_path/target/debug --emit=dep-info,link -L dependency=/Users/elliott/Code/Public/faster_path/target/debug -L dependency=/Users/elliott/Code/Public/faster_path/target/debug/deps --extern libc=/Users/elliott/Code/Public/faster_path/target/debug/deps/liblibc-6b483f9a7097e9a4.rlib` (exit code: 101)
```

**Comment by elliottneilclark** [comment]
This is in a rustup environment in fully updated.
I've tried completely removing ~/.cargo, reinstalling rustup, and re-doing this and I see the same errors.

**Comment by elliottneilclark** [comment]
```rust
use std::path::MAIN_SEPARATOR;
use std::str;

pub const S: char = '/';

#[no_mangle]
pub extern "C" fn repro() {
    let a: &[u8] = b"123456";
    let mut chars = str::from_utf8(a).unwrap().chars();
    match chars.next() {
        Some(MAIN_SEPARATOR) => println!("Test"),
        _ => println!("Nope"),
    }
}


fn main() {
    println!("Hello, world!");
}

```

That's about the smallest repro that I have been able to create. It seems like there's some interaction between the unsafe and pattern matching on an external constant.

If I use just a str not from utf8 this all seems to work well.
If I try and remove the pattern matching this works well.
If I try and pattern match on S rather than MAIN_SEPERATOR this all seems to work well.

**Comment by skade** [comment]
My minimal reproduction is this:

```
use std::path::MAIN_SEPARATOR;

fn main() {
  match Some('/') {
    Some(MAIN_SEPARATOR) => { },
    _                    => { },
  }
}
```

It doesn't compile in `debug` mode, but it does in `release` mode.

See the following playpen and switch between debug in release: https://is.gd/AMwx2o

**Comment by murarth** [comment]
I've encountered this same issue, using a constant defined in my own crate rather than `std::path::MAIN_SEPARATOR`.

The ICE is dependent upon the used constant being defined as the value of another constant.
It also appears to be dependent upon the constant in question being of type `char`. A `u32` constant does not trigger the ICE.

I was thus able to make a smaller minimal case (smaller because it does not touch `std`):

```rust
pub const ALPHA: char = 'a';
pub const BETA: char = ALPHA;

pub fn foo(c: char) {
    match c {
        BETA => (),
        _ => ()
    }
}
```

Compiled with `rustc lib.rs --crate-type=lib -g` produces:

```
lib.rs:6:9: 6:13 error: internal compiler error: ../src/librustc_trans/debuginfo/metadata.rs:909: debuginfo: Could not find scope info for node NodeExpr(expr(6: 'a'))
lib.rs:6         BETA => (),
                 ^~~~
```

The ICE occurs on both stable (`rustc 1.10.0 (cfcb716cf 2016-07-03)`) and a recent nightly (`rustc 1.12.0-nightly (936bfea94 2016-07-20)`).

**Comment by elliottneilclark** [comment]
This no longer seems to repro for me.

**Comment by arielb1** [comment]
Fix-by-MIR?
