### ISSUE TITLE
the compiler unexpectedly panicked

### ISSUE THREAD

**Issue by munyari** [rust-lang/rust#34361]
Added dependencies for [nom](https://github.com/Geal/nom) to Cargo.toml

```toml
[dependencies.nom]
version = "^1.2.3"
features = ["regexp"]
```

The entire file:

```toml
[package]
name = "rush"
version = "0.0.0"
authors = ["Panashe M. Fundira <fundirap@gmail.com>"]
description = "The Rust shell"
repository = "https://github.com/munyari/rush"
readme = "README.md"
keywords = ["shell"]
license = "GPLv3"

[[bin]]
name = "rush"

[dependencies]
readline = "0.0.12"

[dependencies.nom]
version = "^1.2.3"
features = ["regexp"]
```

output from `RUST_BACKTRACE=1 cargo build --verbose`:

```
   Compiling libc v0.2.12
     Running `rustc /home/nash/.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.2.12/src/lib.rs --crate-name libc --crate-type lib -g --cfg feature=\"default\" --cfg feature=\"use_std\" -C metadata=d9dba2869ce64308 -C extra-filename=-d9dba2869ce64308 --out-dir /home/nash/code/recurse/rust/rush/target/debug/deps --emit=dep-info,link -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps --cap-lints allow`
   Compiling regex-syntax v0.3.3
     Running `rustc /home/nash/.cargo/registry/src/github.com-88ac128001ac3a9a/regex-syntax-0.3.3/src/lib.rs --crate-name regex_syntax --crate-type lib -g -C metadata=4120f877c60021d8 -C extra-filename=-4120f877c60021d8 --out-dir /home/nash/code/recurse/rust/rush/target/debug/deps --emit=dep-info,link -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps --cap-lints allow`
   Compiling readline-sys v0.0.12
     Running `rustc /home/nash/.cargo/registry/src/github.com-88ac128001ac3a9a/readline-sys-0.0.12/build.rs --crate-name build_script_build --crate-type bin -g --out-dir /home/nash/code/recurse/rust/rush/target/debug/build/readline-sys-5a34b2d67f0a1999 --emit=dep-info,link -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps --cap-lints allow`
   Compiling utf8-ranges v0.1.3
     Running `rustc /home/nash/.cargo/registry/src/github.com-88ac128001ac3a9a/utf8-ranges-0.1.3/src/lib.rs --crate-name utf8_ranges --crate-type lib -g -C metadata=a6119bc781af556b -C extra-filename=-a6119bc781af556b --out-dir /home/nash/code/recurse/rust/rush/target/debug/deps --emit=dep-info,link -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps --cap-lints allow`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', src/libcore/result.rs:746
stack backtrace:
   1:     0x7f15f5a284e0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7f15f5a35bdb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7f15f5a3577c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7f15f59fa70f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7f15f59fc7f8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7f15f5a25cf1 - rust_begin_unwind
   7:     0x7f15f5a761af - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7f15ed41188b - core::result::unwrap_failed::h82c81d60621f70bd
   9:     0x7f15ed4117fe - rbml::Doc::as_str_slice::hd88d17b04c3f2cca
  10:     0x7f15f382ddf2 - rustc_metadata::decoder::maybe_get_crate_hash::h1c0939ce4d9ba236
  11:     0x7f15f38613ab - rustc_metadata::loader::Context::extract_one::h56453781fb65bffa
  12:     0x7f15f3859145 - rustc_metadata::loader::Context::find_library_crate::h30ea71d32623d713
  13:     0x7f15f383f326 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
  14:     0x7f15f383e1af - rustc_metadata::creader::CrateReader::resolve_crate::h98decfaedbcfe12a
  15:     0x7f15f383fa7b - rustc_metadata::creader::CrateReader::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::h4bd0eba4f8aa0bca
  16:     0x7f15f383f82c - _<std..collections..HashMap<K, V, S> as std..iter..FromIterator<(K, V)>>::from_iter::h7ccc89cd3e9da036
  17:     0x7f15f383b54a - rustc_metadata::creader::CrateReader::register_crate::hdfd966766b932c68
  18:     0x7f15f38408f2 - rustc_metadata::creader::CrateReader::read_extension_crate::hb0997de4fb0918fb
  19:     0x7f15f3842bee - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  20:     0x7f15f3866478 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  21:     0x7f15f386527a - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  22:     0x7f15f5f5535c - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  23:     0x7f15f5f3ba0a - rustc_driver::driver::compile_input::h6491aaddd9e61258
  24:     0x7f15f5f23e74 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  25:     0x7f15f5f212d1 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  26:     0x7f15f5a25c7b - __rust_try
  27:     0x7f15f5a25c0d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  28:     0x7f15f5f21b1a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  29:     0x7f15f5a33d74 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  30:     0x7f15ee64a483 - start_thread
  31:     0x7f15f568b6dc - clone
  32:                0x0 - <unknown>

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', src/libcore/result.rs:746
stack backtrace:
   1:     0x7fbc6265a4e0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7fbc62667bdb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7fbc6266777c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7fbc6262c70f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7fbc6262e7f8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7fbc62657cf1 - rust_begin_unwind
   7:     0x7fbc626a81af - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7fbc5a04388b - core::result::unwrap_failed::h82c81d60621f70bd
   9:     0x7fbc5a0437fe - rbml::Doc::as_str_slice::hd88d17b04c3f2cca
  10:     0x7fbc6045fdf2 - rustc_metadata::decoder::maybe_get_crate_hash::h1c0939ce4d9ba236
  11:     0x7fbc604933ab - rustc_metadata::loader::Context::extract_one::h56453781fb65bffa
  12:     0x7fbc6048b145 - rustc_metadata::loader::Context::find_library_crate::h30ea71d32623d713
  13:     0x7fbc60471326 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
  14:     0x7fbc604701af - rustc_metadata::creader::CrateReader::resolve_crate::h98decfaedbcfe12a
  15:     0x7fbc60471a7b - rustc_metadata::creader::CrateReader::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::h4bd0eba4f8aa0bca
  16:     0x7fbc6047182c - _<std..collections..HashMap<K, V, S> as std..iter..FromIterator<(K, V)>>::from_iter::h7ccc89cd3e9da036
  17:     0x7fbc6046d54a - rustc_metadata::creader::CrateReader::register_crate::hdfd966766b932c68
  18:     0x7fbc604728f2 - rustc_metadata::creader::CrateReader::read_extension_crate::hb0997de4fb0918fb
  19:     0x7fbc60474bee - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  20:     0x7fbc60498478 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  21:     0x7fbc6049727a - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  22:     0x7fbc62b8735c - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  23:     0x7fbc62b6da0a - rustc_driver::driver::compile_input::h6491aaddd9e61258
  24:     0x7fbc62b55e74 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  25:     0x7fbc62b532d1 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  26:     0x7fbc62657c7b - __rust_try
  27:     0x7fbc62657c0d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  28:     0x7fbc62b53b1a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  29:     0x7fbc62665d74 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  30:     0x7fbc5b27c483 - start_thread
  31:     0x7fbc622bd6dc - clone
  32:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', src/libcore/result.rs:746
stack backtrace:
   1:     0x7efd02bdd4e0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7efd02beabdb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7efd02bea77c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7efd02baf70f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7efd02bb17f8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7efd02bdacf1 - rust_begin_unwind
   7:     0x7efd02c2b1af - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7efcfa5c688b - core::result::unwrap_failed::h82c81d60621f70bd
   9:     0x7efcfa5c67fe - rbml::Doc::as_str_slice::hd88d17b04c3f2cca
  10:     0x7efd009e2df2 - rustc_metadata::decoder::maybe_get_crate_hash::h1c0939ce4d9ba236
  11:     0x7efd00a163ab - rustc_metadata::loader::Context::extract_one::h56453781fb65bffa
  12:     0x7efd00a0e145 - rustc_metadata::loader::Context::find_library_crate::h30ea71d32623d713
  13:     0x7efd009f4326 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
  14:     0x7efd009f31af - rustc_metadata::creader::CrateReader::resolve_crate::h98decfaedbcfe12a
  15:     0x7efd009f4a7b - rustc_metadata::creader::CrateReader::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::h4bd0eba4f8aa0bca
  16:     0x7efd009f482c - _<std..collections..HashMap<K, V, S> as std..iter..FromIterator<(K, V)>>::from_iter::h7ccc89cd3e9da036
  17:     0x7efd009f054a - rustc_metadata::creader::CrateReader::register_crate::hdfd966766b932c68
  18:     0x7efd009f58f2 - rustc_metadata::creader::CrateReader::read_extension_crate::hb0997de4fb0918fb
  19:     0x7efd009f7bee - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  20:     0x7efd00a1b478 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  21:     0x7efd00a1a27a - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  22:     0x7efd0310a35c - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  23:     0x7efd030f0a0a - rustc_driver::driver::compile_input::h6491aaddd9e61258
  24:     0x7efd030d8e74 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  25:     0x7efd030d62d1 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  26:     0x7efd02bdac7b - __rust_try
  27:     0x7efd02bdac0d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  28:     0x7efd030d6b1a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  29:     0x7efd02be8d74 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  30:     0x7efcfb7ff483 - start_thread
  31:     0x7efd028406dc - clone
  32:                0x0 - <unknown>
Build failed, waiting for other jobs to finish...

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', src/libcore/result.rs:746
stack backtrace:
   1:     0x7fea998444e0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7fea99851bdb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7fea9985177c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7fea9981670f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7fea998187f8 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7fea99841cf1 - rust_begin_unwind
   7:     0x7fea998921af - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7fea9122d88b - core::result::unwrap_failed::h82c81d60621f70bd
   9:     0x7fea9122d7fe - rbml::Doc::as_str_slice::hd88d17b04c3f2cca
  10:     0x7fea97649df2 - rustc_metadata::decoder::maybe_get_crate_hash::h1c0939ce4d9ba236
  11:     0x7fea9767d3ab - rustc_metadata::loader::Context::extract_one::h56453781fb65bffa
  12:     0x7fea97675145 - rustc_metadata::loader::Context::find_library_crate::h30ea71d32623d713
  13:     0x7fea9765b326 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
  14:     0x7fea9765a1af - rustc_metadata::creader::CrateReader::resolve_crate::h98decfaedbcfe12a
  15:     0x7fea9765ba7b - rustc_metadata::creader::CrateReader::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::h4bd0eba4f8aa0bca
  16:     0x7fea9765b82c - _<std..collections..HashMap<K, V, S> as std..iter..FromIterator<(K, V)>>::from_iter::h7ccc89cd3e9da036
  17:     0x7fea9765754a - rustc_metadata::creader::CrateReader::register_crate::hdfd966766b932c68
  18:     0x7fea9765c8f2 - rustc_metadata::creader::CrateReader::read_extension_crate::hb0997de4fb0918fb
  19:     0x7fea9765ebee - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  20:     0x7fea97682478 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  21:     0x7fea9768127a - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  22:     0x7fea99d7135c - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  23:     0x7fea99d57a0a - rustc_driver::driver::compile_input::h6491aaddd9e61258
  24:     0x7fea99d3fe74 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  25:     0x7fea99d3d2d1 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  26:     0x7fea99841c7b - __rust_try
  27:     0x7fea99841c0d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  28:     0x7fea99d3db1a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  29:     0x7fea9984fd74 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  30:     0x7fea92466483 - start_thread
  31:     0x7fea994a76dc - clone
  32:                0x0 - <unknown>

error: Could not compile `readline-sys`.

Caused by:
  Process didn't exit successfully: `rustc /home/nash/.cargo/registry/src/github.com-88ac128001ac3a9a/readline-sys-0.0.12/build.rs --crate-name build_script_build --crate-type bin -g --out-dir /home/nash/code/recurse/rust/rush/target/debug/build/readline-sys-5a34b2d67f0a1999 --emit=dep-info,link -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps -L dependency=/home/nash/code/recurse/rust/rush/target/debug/deps --cap-lints allow` (exit code: 101)
```

`rustc --version --verbose`:
```
rustc 1.9.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.9.0
```

**Comment by TimNN** [comment]
Duplicate of #33778, a `cargo clean` should fix the problem, I believe.

**Comment by munyari** [comment]
@TimNN This worked, thank you. I'll close the issue because it is a duplicate
