### ISSUE TITLE
Internal compiler error with string constant

### ISSUE THREAD

**Issue by koba-e964** [rust-lang/rust#34448]
When I tried to define a string constant in `src/main.rs`, the compiler was terminated by internal error. 
I tried `cargo run` in the repository [koba-e964/calc-rust:bug-report](https://github.com/koba-e964/calc-rust/tree/bug-report):

The compiler was terminated because of internal error, with the following output:

```
(some lines omitted)
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/libsyntax/errors/mod.rs:370
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `calc`.
```
## Meta

`rustc --version --verbose`:

```
rustc 1.11.0-nightly (5522e678b 2016-06-20)
binary: rustc
commit-hash: 5522e678bcefe14cc2ab3d0ab329b7059ce52b36
commit-date: 2016-06-20
host: x86_64-apple-darwin
release: 1.11.0-nightly
```

Backtrace (`RUST_BACKTRACE=1 cargo run`):

```
   Compiling libc v0.2.12
   Compiling peg v0.3.13
   Compiling winapi-build v0.1.1
   Compiling strsim v0.3.0
   Compiling kernel32-sys v0.2.2
   Compiling regex-syntax v0.3.3
   Compiling winapi v0.2.7
   Compiling memchr v0.1.11
   Compiling utf8-ranges v0.1.3
   Compiling aho-corasick v0.5.2
   Compiling rustc-serialize v0.3.19
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.6
   Compiling regex v0.1.71
   Compiling docopt v0.6.81
   Compiling docopt_macros v0.6.84
   Compiling calc v0.1.0 (file:///Users/koba_mac/srcview/calc-rust)
src/interpret.rs:41:21: 41:26 warning: unused variable: `f`, #[warn(unused_variables)] on by default
src/interpret.rs:41         AST::FunApp(ref f, ref es) => panic!("eval_funapp"),
                                        ^~~~~
src/interpret.rs:41:28: 41:34 warning: unused variable: `es`, #[warn(unused_variables)] on by default
src/interpret.rs:41         AST::FunApp(ref f, ref es) => panic!("eval_funapp"),
                                               ^~~~~~
src/typing.rs:34:21: 34:26 warning: unused variable: `f`, #[warn(unused_variables)] on by default
src/typing.rs:34         AST::FunApp(ref f, ref es) => panic!("typing_funapp"),
                                     ^~~~~
src/typing.rs:34:28: 34:34 warning: unused variable: `es`, #[warn(unused_variables)] on by default
src/typing.rs:34         AST::FunApp(ref f, ref es) => panic!("typing_funapp"),
                                            ^~~~~~
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', ../src/libsyntax/errors/mod.rs:370
stack backtrace:
   1:        0x106e1bb4b - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:        0x106e2882a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:        0x106e2835b - std::panicking::default_hook::he0146e6a74621cb4
   4:        0x106dede08 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:        0x1041c5004 - std::panicking::begin_panic::h0bf39f6d43ab9349
   6:        0x1041cd638 - _<syntax..errors..DiagnosticBuilder<'a> as core..ops..Drop>::drop::h7bf6d745882a0d7c
   7:        0x107c11fa0 - syntax..errors..DiagnosticBuilder::drop.21685::h11584c18ad2b9e97
   8:        0x107c11f57 - std..result..Result<Parsed, syntax..errors..DiagnosticBuilder>::drop.21682::hdff0d2eaebc0cefd
   9:        0x107c01a8b - docopt_macros::expand::hf63339f6a0f063b6
  10:        0x102a6b089 - _<F as syntax..ext..base..TTMacroExpander>::expand::h9e11b515514e3f92
  11:        0x1043c0626 - syntax::ext::expand::expand_mac_invoc::mac_result::hae15856b289b7c95
  12:        0x10444e9fb - syntax::ext::expand::expand_annotatable::_$u7b$$u7b$closure$u7d$$u7d$::h8520d1055a82cb81
  13:        0x10440cb87 - syntax::ext::expand::expand_annotatable::h05daf8dbfd45385d
  14:        0x10440b1ec - syntax::ext::expand::expand_item::h0c304e718d09cf1e
  15:        0x104417101 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::h7e3a9cc89287eb31
  16:        0x104416db0 - syntax::fold::noop_fold_mod::h9b639661453b4e4a
  17:        0x104410c25 - syntax::ext::expand::expand_item_kind::h77370e172ebc6967
  18:        0x104451b2d - syntax::fold::Folder::fold_item_simple::h389274292ee655e4
  19:        0x104451716 - _<syntax..ptr..P<T>>::map::h0f976487c864d039
  20:        0x10440def0 - syntax::ext::expand::expand_annotatable::h05daf8dbfd45385d
  21:        0x10440b1ec - syntax::ext::expand::expand_item::h0c304e718d09cf1e
  22:        0x104417347 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::h7e3a9cc89287eb31
  23:        0x104466571 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_crate::hc04a1c2ade6e09bb
  24:        0x104467a31 - syntax::ext::expand::expand_crate::h751c1b1de09c42dd
  25:        0x1023aff98 - rustc_driver::driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::hfdc4ab61e58580ac
  26:        0x102364181 - rustc_driver::driver::phase_2_configure_and_expand::h7aa0bb3346817b72
  27:        0x10233751e - rustc_driver::driver::compile_input::hfd60b020f6d0208d
  28:        0x102328b54 - rustc_driver::run_compiler::h884d01d12eb76bbb
  29:        0x102325b5f - std::panicking::try::call::hd72cf79141f67e60
  30:        0x106e2f90b - __rust_try
  31:        0x106e2f8a5 - __rust_maybe_catch_panic
  32:        0x10232666b - _<F as alloc..boxed..FnBox<A>>::call_box::h589d2091babf223a
  33:        0x106e272a8 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  34:     0x7fff8ab9799c - _pthread_body
  35:     0x7fff8ab97919 - _pthread_start

error: Could not compile `calc`.

To learn more, run the command again with --verbose.
```

[Here](https://travis-ci.org/koba-e964/calc-rust/builds/139983383) is the output of Travis CI, which also has unexpected compiler termination.

**Comment by pocket7878** [comment]
This still happens on latest nightly:

```
rustc 1.14.0-nightly (9c31d76e9 2016-10-03)
binary: rustc
commit-hash: 9c31d76e97c6116ba2480aa23a48f3e7bd25a7cb
commit-date: 2016-10-03
host: x86_64-apple-darwin
release: 1.14.0-nightly
```

https://github.com/pocket7878/calc-rust/tree/bug-report

**Comment by pocket7878** [comment]
It looks like bug in decopt syntax plugin bug?

Cause below example (which passing unexist value to docpot! macro)

```
#![feature(plugin)]
#![plugin(docopt_macros)]

extern crate docopt;
use docopt::Docopt;

docopt!(Args, HOGE);

fn main() {
}
```

Produce same error

**Comment by koba-e964** [comment]
It looks so. Should I close this issue?

**Comment by arielb1** [comment]
`docopt_macros::expand::h6d29a5b0a5787255`

Yup.

Can you report the bug to docopt?
