### ISSUE TITLE
Panic compiling libc after switching around release channels

### ISSUE THREAD

**Issue by stensonowen** [rust-lang/rust#34514]
```
$ cargo build
   Compiling libc v0.2.12
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1 }', ../src/libcore/result.rs:746
```
Running with `--verbose` gives 
```
Caused by:
  Process didn't exit successfully: `rustc /home/owen/.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.2.12/src/lib.rs --crate-name libc --crate-type lib -g --cfg feature="use_std" --cfg feature="default" -C metadata=d9dba2869ce64308 -C extra-filename=-d9dba2869ce64308 --out-dir /home/owen/shared/code/rust/game_of_life/life/target/debug/deps --emit=dep-info,link -L dependency=/home/owen/shared/code/rust/game_of_life/life/target/debug/deps -L dependency=/home/owen/shared/code/rust/game_of_life/life/target/debug/deps --cap-lints allow` (exit code: 101)
```
and with RUST_BACKTRACE=1 gives 
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7fe2b560b570 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7fe2b5618c6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7fe2b561880c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7fe2b55dd79f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7fe2b55df888 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7fe2b5608d81 - rust_begin_unwind
   7:     0x7fe2b566285f - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7fe2acbb5a0b - core::result::unwrap_failed::h82c81d60621f70bd
   9:     0x7fe2acbb597e - rbml::Doc::as_str_slice::hd88d17b04c3f2cca
  10:     0x7fe2b3409a62 - rustc_metadata::decoder::maybe_get_crate_hash::h1c0939ce4d9ba236
  11:     0x7fe2b343d01b - rustc_metadata::loader::Context::extract_one::h56453781fb65bffa
  12:     0x7fe2b3434db5 - rustc_metadata::loader::Context::find_library_crate::h30ea71d32623d713
  13:     0x7fe2b341af96 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
  14:     0x7fe2b3419e1f - rustc_metadata::creader::CrateReader::resolve_crate::h98decfaedbcfe12a
  15:     0x7fe2b341b6eb - rustc_metadata::creader::CrateReader::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::h4bd0eba4f8aa0bca
  16:     0x7fe2b341b49c - _<std..collections..HashMap<K, V, S> as std..iter..FromIterator<(K, V)>>::from_iter::h7ccc89cd3e9da036
  17:     0x7fe2b34171ba - rustc_metadata::creader::CrateReader::register_crate::hdfd966766b932c68
  18:     0x7fe2b341c562 - rustc_metadata::creader::CrateReader::read_extension_crate::hb0997de4fb0918fb
  19:     0x7fe2b341e85e - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  20:     0x7fe2b34420e8 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  21:     0x7fe2b3440eea - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  22:     0x7fe2b5b419ec - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  23:     0x7fe2b5b2809a - rustc_driver::driver::compile_input::h6491aaddd9e61258
  24:     0x7fe2b5b104e4 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  25:     0x7fe2b5b0d941 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  26:     0x7fe2b5608d0b - __rust_try
  27:     0x7fe2b5608c9d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  28:     0x7fe2b5b0e18a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  29:     0x7fe2b5616e04 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  30:     0x7fe2adff40a3 - start_thread
  31:     0x7fe2b526c87c - clone
  32:                0x0 - <unknown>
```

Before this happened I was playing around with different channels using rustup, and had just run `rustup default stable`.

[Here](https://github.com/stensonowen/game_of_life/blob/0a3eb367ea3ee45ae47a52b5724aba5c521ec00c/src/lib.rs) is the file I was playing around with in the state it was in when the bug appeared. I can't imagine it's relevant, but may as well include it.

I was compiling fine (on every channel) a few minutes before. 

Version info: 
```
rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: x86_64-unknown-linux-gnu
release: 1.9.0
```
`cargo 0.10.0-nightly (10ddd7d 2016-04-08)`, 
`rustup 0.2.0 (57f335a 2016-06-21)`

**Comment by rkruppe** [comment]
From the backtrace it seems like yet another instance of #33778 

This issue is really hitting a lot of people :(

**Comment by stensonowen** [comment]
Yeah, thanks, `cargo clean` fixes the problem. If it's a duplicate I'll close it.
