### ISSUE TITLE
tcp-stress-test.rs fails in master

### ISSUE THREAD

**Issue by the-kenny** [rust-lang/rust#35107]
I'm packaging `unstable` (rev d9a911d236cbecb47775276ba51a5f9111bdbc9c) for NixOS. Right now I can't continue here as one test fails. I'm not sure if this is related to our chrooted build environment or if it's an upstream issue.

Noteworthy is also that `beta` and `stable` are working fine (with the same build process).

Error messages:

```

failures:

---- [run-pass] run-pass/tcp-stress.rs stdout ----

executing x86_64-unknown-linux-gnu/stage2/bin/rustc /tmp/nix-build-rustc-master-1.12.0-gd9a911d.drv-0/rust-d9a911d/src/test/run-pass/tcp-stress.rs -L x86_64-unknown-linux-gnu/test/run-pass/ --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/run-pass/tcp-stress.stage2-x86_64-unknown-linux-gnu.run-pass.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/run-pass/tcp-stress.stage2-x86_64-unknown-linux-gnu --cfg rtopt -C rpath -O -L x86_64-unknown-linux-gnu/rt
------stdout------------------------------

------stderr------------------------------

------------------------------------------
executing x86_64-unknown-linux-gnu/test/run-pass/tcp-stress.stage2-x86_64-unknown-linux-gnu
------stdout------------------------------

------stderr------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `484`, right: `1000`)', /tmp/nix-build-rustc-master-1.12.0-gd9a911d.drv-0/rust-d9a911d/src/test/run-pass/tcp-stress.rs:69
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

error: test run failed!
status: exit code: 101
command: x86_64-unknown-linux-gnu/test/run-pass/tcp-stress.stage2-x86_64-unknown-linux-gnu
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `484`, right: `1000`)', /tmp/nix-build-rustc-master-1.12.0-gd9a911d.drv-0/rust-d9a911d/src/test/run-pass/tcp-stress.rs:69
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

thread '[run-pass] run-pass/tcp-stress.rs' panicked at 'explicit panic', /tmp/nix-build-rustc-master-1.12.0-gd9a911d.drv-0/rust-d9a911d/src/tools/compiletest/src/runtest.rs:2353
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-pass] run-pass/tcp-stress.rs

test result: FAILED. 2470 passed; 1 failed; 3 ignored; 0 measured

thread 'main' panicked at 'Some tests failed', /tmp/nix-build-rustc-master-1.12.0-gd9a911d.drv-0/rust-d9a911d/src/tools/compiletest/src/main.rs:293
make: *** [/tmp/nix-build-rustc-master-1.12.0-gd9a911d.drv-0/rust-d9a911d/mk/tests.mk:771: tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rpass.ok] Error 101
builder for ‘/nix/store/13ij8ra9xgqqk8xpdgv9c0hrmk189jc2-rustc-master-1.12.0-gd9a911d.drv’ failed with exit code 2
error: build of ‘/nix/store/13ij8ra9xgqqk8xpdgv9c0hrmk189jc2-rustc-master-1.12.0-gd9a911d.drv’ failed
```

I forgot to pipe the build output to a file, but I'm running it again now and will include a link to the full output as soon as possible.

**Comment by TimNN** [comment]
It looks like that test is already ignored on lot's of platforms:

```
// ignore-android needs extra network permissions
// ignore-bitrig system ulimit (Too many open files)
// ignore-netbsd system ulimit (Too many open files)
// ignore-openbsd system ulimit (Too many open files)
// ignore-emscripten no threads or sockets support
```

And far as I can tell it fails because it can only spawn `484` out of `1000` threads.

**Comment by TimNN** [comment]
I believe this issue manifest itself since #33640, when the failing assert was introduced.

**Comment by the-kenny** [comment]
Is this something to be handled upstream? I don't think we can easily
change the ulimit for a specific build.

Should I just patch out the failing test on our side?

Am 29.07.2016 12:53 schrieb "Tim Neumann" <notifications@github.com>:

**Comment by TimNN** [comment]
Mh, I'm not that familiar with the topic, better wait for someone like @alexcrichton to chime in, who know better, whats going on.

(Just on a side note, the `// ignore-*` lines were present before #33640, the PR which introduced the failing assertion).

**Comment by alexcrichton** [comment]
It should be fine to just turn down the size of this tests, it was originally meant to stress libuv and turn up bugs, but that's long gone now!

**Comment by the-kenny** [comment]
@alexcrichton Thanks! Lowering the thread count to `256` fixed the build for us. Shall we close this issue?

**Comment by alexcrichton** [comment]
Sure, sounds good to me!
