### ISSUE TITLE
rustc segfaults on Beaglebone

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#36465]
```
# omitted: install https://static.rust-lang.org/dist/2016-09-13/rustc-nightly-arm-unknown-linux-gnueabihf.tar.gz

$ gdb rustc
(gdb) run -V
Starting program: rustc -V
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xb2ef57b4 in __pthread_initialize_minimal_internal () from /usr/lib/libpthread.so.0
#2  0xb2ef4d54 in _init () from /usr/lib/libpthread.so.0
#3  0xb6fdf2e8 in call_init.part () from /lib/ld-linux-armhf.so.3
#4  0xb6fdf4b8 in _dl_init () from /lib/ld-linux-armhf.so.3
#5  0xb6fcfbc4 in _dl_start_user () from /lib/ld-linux-armhf.so.3
```

The armv7-unknown-linux-gnueabihf variant also segfaults.

1.9.0, 1.10.0 and 1.11.0 also segfault in their both (arm and armv7) variants and there is no official rustc-1.8.0 release for ARM.

The unofficial 1.8.0 rustc release (for armv7) from the [RustBuild] project does work.

[RustBuild]: https://github.com/warricksothr/RustBuild#armv7-direct-repository-links

Hello world cross compiled for armv7 using rustc-1.8.0 works fine.

### Meta

Tested on a fresh [Arch Linux ARM] install.

Note that the Beaglebone only has 256 MB. But I created a 512MB swapfile and flushed all the caches before testing all this. Unsure if the low amount of RAM contributes to the problem.

[Arch Linux ARM]: https://archlinuxarm.org/platforms/armv7/ti/beaglebone

cc @petevine

**Comment by japaric** [comment]
Ah this is the same #35843.
