### ISSUE TITLE
'debuginfo-lldb/union-smoke.rs' failing for me on master

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#37479]
```
failures:

---- [debuginfo-lldb] debuginfo-lldb/union-smoke.rs stdout ----
    NOTE: compiletest thinks it is using LLDB version 360

error: line not found in debugger output: [...]$0 = { a = ('\x02', '\x02') b = 514 }
status: exit code: 0
command: "/usr/bin/python" "/Users/coreyf/Development/rust/rust/src/etc/lldb_batchmode.py" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo/union-smoke.stage2-x86_64-apple-darwin" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo/union-smoke.debugger.script"
stdout:
------------------------------------------
LLDB batch-mode script
----------------------
Debugger commands script is '/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo/union-smoke.debugger.script'.
Target executable is '/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo/union-smoke.stage2-x86_64-apple-darwin'.
Current working directory is '/Users/coreyf/Development/rust/rust'
Creating a target for '/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo/union-smoke.stage2-x86_64-apple-darwin'
settings set auto-confirm true

version
lldb-360.1.50
command script import /Users/coreyf/Development/rust/rust/./src/etc/lldb_rust_formatters.py
type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
type category enable Rust

breakpoint set --file 'union-smoke.rs' --line 47
Breakpoint 1: where = union-smoke.stage2-x86_64-apple-darwin`union_smoke::main + 44 at union-smoke.rs:47, address = 0x0000000100000eac
run
Hit breakpoint 1.1: where = union-smoke.stage2-x86_64-apple-darwin`union_smoke::main + 44 at union-smoke.rs:47, address = 0x0000000100000eac, resolved, hit count = 1
Process 11207 stopped * thread #1: tid = 0x1936db, 0x0000000100000eac union-smoke.stage2-x86_64-apple-darwin`union_smoke::main + 44 at union-smoke.rs:47, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1 frame #0: 0x0000000100000eac union-smoke.stage2-x86_64-apple-darwin`union_smoke::main + 44 at union-smoke.rs:47 44 let u = U { b: (2 << 8) + 2 }; 45 unsafe { SU = U { a: (1, 1) } } 46 -> 47 zzz(); // #break 48 } 49 50 fn zzz() {()} Process 11207 launched: '/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo/union-smoke.stage2-x86_64-apple-darwin' (x86_64)
print u
(union_smoke::U) $0 = None
print union_smoke::SU
(union_smoke::U) $1 = 257
quit


------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[debuginfo-lldb] debuginfo-lldb/union-smoke.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:2377
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [debuginfo-lldb] debuginfo-lldb/union-smoke.rs

test result: FAILED. 95 passed; 1 failed; 10 ignored; 0 measured

thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:298


command did not execute successfully: "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/stage2-tools/x86_64-apple-darwin/release/compiletest" "--compile-lib-path" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/stage2/lib" "--run-lib-path" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib" "--rustc-path" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/stage2/bin/rustc" "--rustdoc-path" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/stage2/bin/rustdoc" "--src-base" "/Users/coreyf/Development/rust/rust/src/test/debuginfo" "--build-base" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/test/debuginfo" "--stage-id" "stage2-x86_64-apple-darwin" "--mode" "debuginfo-lldb" "--target" "x86_64-apple-darwin" "--host" "x86_64-apple-darwin" "--llvm-filecheck" "/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/llvm/build/bin/FileCheck" "--nodejs" "/usr/local/bin/node" "--host-rustcflags" "-Crpath -O" "--target-rustcflags" "-Crpath -O -Lnative=/Users/coreyf/Development/rust/rust/build/x86_64-apple-darwin/rust-test-helpers" "--docck-python" "python" "--lldb-python" "/usr/bin/python" "--gdb-version" "GNU gdb (GDB) 7.12" "--lldb-version" "lldb-360.1.50" "--lldb-python-dir" "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python" "--llvm-version" "3.9.0\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp" "--android-cross-path" ""
expected success, got: exit code: 101
```

**Comment by morisbartyno** [comment]
git install

**Comment by frewsxcv** [comment]
@morisbartyno Did you mean anything by "git install"?

**Comment by frewsxcv** [comment]
This test case only seems to fail for me when using rustbuild on MacOS.

**Comment by alexcrichton** [comment]
Looks like this is related to using lldb 360 vs lldb 330. The 330 version was in use by our old buildbots, and 360 recently [failed on Travis](https://github.com/rust-lang/rust/pull/38507). I've confirmed locally 360 fails with both rustbuild and makefiles (e.g. it's not a rustbuild problem).

I'm going to ignore this test for now on OSX, to land that change, but let's leave this open to track the test not working on lldb 360
