### ISSUE TITLE
wasm linker failure (Windows 8.1)

### ISSUE THREAD

**Issue by Happy-Ferret** [rust-lang/rust#37558]
Attempting to follow this [tutorial](https://users.rust-lang.org/t/compiling-to-the-web-with-rust-and-emscripten/7627) yields the following backtrace upon running 

``rustc --target=wasm32-unknown-emscripten hello.rs``

Backtrace:

```
error: could not exec the linker `emcc`: The system cannot find the file specifi
ed. (os error 2)
  |
  = note: "emcc" "-L" "C:\\Users\\user\\.multirust\\toolchains\\nightly-x86_
64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib" "hello.0.o" "-
o" "hello.js" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\user\\.m
ultirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unkno
wn-emscripten\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\Users\\user\\.multir
ust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-em
scripten\\lib\\libstd-17342542cc541012.rlib" "C:\\Users\\user\\.multirust\\t
oolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscript
en\\lib\\libpanic_unwind-f78756b576499725.rlib" "C:\\Users\\user\\.multirust
\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscr
ipten\\lib\\libunwind-11f7709e0c71505b.rlib" "C:\\Users\\user\\.multirust\\t
oolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscript
en\\lib\\librand-46ed9b788a6928f6.rlib" "C:\\Users\\user\\.multirust\\toolch
ains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\l
ib\\libcollections-e32369d7fef31fbf.rlib" "C:\\Users\\user\\.multirust\\tool
chains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\
\lib\\librustc_unicode-844a33a197b559a5.rlib" "C:\\Users\\user\\.multirust\\
toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscrip
ten\\lib\\liballoc-24699c1ddb055eb0.rlib" "C:\\Users\\user\\.multirust\\tool
chains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\
\lib\\liballoc_system-3e467e865c8fa572.rlib" "C:\\Users\\user\\.multirust\\t
oolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscript
en\\lib\\liblibc-60365c932e50e382.rlib" "C:\\Users\\user\\.multirust\\toolch
ains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\l
ib\\libcore-d9873b515905cac5.rlib" "C:\\Users\\user\\.multirust\\toolchains\
\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\wasm32-unknown-emscripten\\lib\\l
ibcompiler_builtins-e428224f6caf212a.rlib" "-l" "c" "-s" "BINARYEN=1" "-s" "ERRO
R_ON_UNDEFINED_SYMBOLS=1"

error: aborting due to previous error
```

emcc is accessible and inside the path, so I can only assume that the error message refers to another file rather than the linker itself.

**Comment by Happy-Ferret** [comment]
Taking the above ``emcc`` command and sanitizing it (i. e. removing all the quotation marks and whitespaces) gets me a bit further but eventually fails because of another Windows pathing issue (note the lack of either forward or backward slashes).

```
C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2013_64/RelWithDebInfo/bin\llvm-link: c:usersuserappdatalocaltemptmpuuovrhstrlwr.c.o: error: Could not open input file: no such file or directory
C:/Program Files/Emscripten/clang/fastcomp/build_incoming_vs2013_64/RelWithDebInfo/bin\llvm-link: error loading file 'c:usersuserappdatalocaltemptmpuuovrhstrlwr.c.o'
Traceback (most recent call last):
  File "C:/Program Files/Emscripten/emscripten/1.35.0/emcc", line 1222, in <module>
    extra_files_to_link += system_libs.calculate([f for _, f in sorted(temp_files)] + extra_files_to_link, in_temp, stdout, stderr, forced=forced_stdlibs)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 339, in calculate
    libfile = shared.Cache.get(name, do_create, extension=suffix)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\cache.py", line 41, in get
    temp = creator()
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 337, in do_create
    ret = create(name)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 119, in create_libc
    return build_libc(libname, libc_files, args)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\system_libs.py", line 66, in build_libc
    shared.Building.link(o_s, in_temp(lib_filename))
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\shared.py", line 1432, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error:
```

**Comment by whoisj** [comment]
For those developing Windows tooling for Rust, Windows can handle '/' path separators. If you're having issues with escaping strings (and we all do occasionally) fallback to using '/' instead of '\'. That said, if you do use '/' there are certain API which will not accept them, specifically the "Nt*" and "Zw*" methods. Finally, the "\\?\" prefix to avoid Window's legacy MAX_PATH issues won't work unless the backslash is used as the path separator.

**Comment by alexcrichton** [comment]
I believe the original error from rustc is because emcc is a shell script (so I've heard) which can't be executed on Windows. AFAIK there's a emcc.bat that we can execute, which we should try to do so by default!

**Comment by Happy-Ferret** [comment]
The problem won't subside on MSys2 either (which should be able to take shell scripts as an input), so I'm not sure that's really the problem.

**Comment by Happy-Ferret** [comment]
Getting the exact same error on GNU/Linux (Ubuntu 16.04) now :(

**Comment by chris-morgan** [comment]
Same as #38489. I posted a workaround there.

**Comment by brson** [comment]
Thank you for the investigations. Closing in favor of https://github.com/rust-lang/rust/issues/38489. Patch enqueued.
