### ISSUE TITLE
Location info is incorrect when using mod in macro

### ISSUE THREAD

**Issue by ShikChen** [rust-lang/rust#37663]
This made debugging/logging much harder. Here is an example:

### main.rs

``` rust
macro_rules! m { () => { mod a; } }
m!();
fn main() {
    println!("{:?}", a::f());
    a::g();
}
```

### a.rs

``` rust
pub fn f() -> (&'static str, u32) { (file!(), line!()) }
pub fn g() { panic!(); }
```

### Output

```
$ rustc main.rs && RUST_BACKTRACE=1 ./main
("main.rs", 2)
thread 'main' panicked at 'explicit panic', main.rs:2
stack backtrace:
   1:        0x10a870099 - std::sys::backtrace::tracing::imp::write::hd4b54a4a2078cb15
   2:        0x10a871e30 - std::panicking::default_hook::_{{closure}}::h51a5ee7ba6a9fcef
   3:        0x10a8712d0 - std::panicking::default_hook::hf823fce261e27590
   4:        0x10a871896 - std::panicking::rust_panic_with_hook::h8d486474663979b9
   5:        0x10a869a9c - std::panicking::begin_panic::h94e6fb50d7864116
   6:        0x10a869df2 - main::a::g::hd3cb4865f31817a2
   7:        0x10a869ea2 - main::main::he714a2e23ed7db23
   8:        0x10a87241a - __rust_maybe_catch_panic
   9:        0x10a870d9e - std::rt::lang_start::hca48e539ce72a288
  10:        0x10a869ed9 - main
```

### Expected Output

```
("a.rs", 1)
thread 'main' panicked at 'explicit panic', a.rs:2
...
```

### Version

```
$ rustc --version
rustc 1.12.1 (d4f39402a 2016-10-19)
```

**Comment by mitsuhiko** [comment]
I cam across the same thing. I used to do this for building command line apps but it turns out that this breaks debug info:

https://github.com/getsentry/sentry-cli/blob/4b8d4e89153ba409e42bb2cdbf24f39bdef5ec54/src/commands/mod.rs#L17-L33

**Comment by Mark-Simulacrum** [comment]
@jseyfried Have you looked at this yet? You assigned this to yourself.

**Comment by jseyfried** [comment]
I haven't prioritized it, but it's on my radar (also specifics of this issue probably changed since my recent span refactoring).

If anyone would like to work on this, I'd be happy to help/mentor.

**Comment by jyn514** [comment]
Triage: this is now fixed.
```
("a.rs", 1)
thread 'main' panicked at 'explicit panic', a.rs:2:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
