### ISSUE TITLE
rustc crash: thread 'rustc' panicked at 'Box<Any>', rust/1.13/src/rust/src/librustc_errors/lib.rs:602

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#37809]
rustc 1.13 crashed with:
```
thread 'rustc' panicked at 'Box<Any>', rust/1.13/src/rust/src/librustc_errors/lib.rs:602
stack backtrace:
   1:     0x7f3e4917aa8f - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x7f3e49189fed - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x7f3e4918745e - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x7f3e49187b48 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x7f3e489d4628 - std::panicking::begin_panic::hf3c77cb5fd5814c4
   6:     0x7f3e48b01575 - rustc::session::opt_span_bug_fmt::{{closure}}::hf0e25c590c479ec5
   7:     0x7f3e48a197ca - rustc::session::span_bug_fmt::h42d4c0a219d5e4ec
   8:     0x7f3e48ac8457 - rustc_typeck::check::FnCtxt::check_path_parameter_count::hc2ad181f3f777040
   9:     0x7f3e48ac6825 - rustc_typeck::check::FnCtxt::instantiate_value_path::hfa5d7d83b8353970
  10:     0x7f3e48ab94d0 - rustc_typeck::check::FnCtxt::check_expr_kind::h2bc479cd1fbdeadf
  11:     0x7f3e48ab6a6a - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h681fafa88c40b2ba
  12:     0x7f3e48ab1213 - rustc_typeck::check::FnCtxt::check_argument_types::hed35c9823eddf317
  13:     0x7f3e48a82ca6 - rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::confirm_builtin_call::h2a6f0d42e9460044
  14:     0x7f3e48a81dbf - rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::check_call::h2eb88b075d26016a
  15:     0x7f3e48ab79ed - rustc_typeck::check::FnCtxt::check_expr_kind::h2bc479cd1fbdeadf
  16:     0x7f3e48ab6a6a - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h681fafa88c40b2ba
  17:     0x7f3e48a41aab - rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::check_match::h883631eee69589e9
  18:     0x7f3e48ab6edf - rustc_typeck::check::FnCtxt::check_expr_kind::h2bc479cd1fbdeadf
  19:     0x7f3e48ab6a6a - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h681fafa88c40b2ba
  20:     0x7f3e48ac620c - rustc_typeck::check::FnCtxt::check_block_with_expected::hbd45bbda86915d07
  21:     0x7f3e48a953cb - rustc_typeck::check::check_fn::h12c0d05f83ad8556
  22:     0x7f3e48a93cb7 - rustc_typeck::check::check_bare_fn::hb4550dd2ea96340d
  23:     0x7f3e48a96e95 - rustc_typeck::check::check_item_body::h3f1f413025e17499
  24:     0x7f3e48a9138e - rustc_typeck::check::check_item_bodies::h3fa451d8a8774470
  25:     0x7f3e48afd56e - rustc_typeck::check_crate::h54ff5b2dd08c0691
  26:     0x7f3e49536365 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h4091eeab6f271a29
  27:     0x7f3e4951149d - rustc_driver::driver::phase_3_run_analysis_passes::hff1c31d493acfd09
  28:     0x7f3e494fdb29 - rustc_driver::driver::compile_input::hef221f9f618e92f5
  29:     0x7f3e495282f6 - rustc_driver::run_compiler::h7dddd4089f8330b4
  30:     0x7f3e494643b3 - std::panicking::try::do_call::h1e3ece12e3f812df
  31:     0x7f3e491931b6 - __rust_maybe_catch_panic
  32:     0x7f3e494825e9 - <F as alloc::boxed::FnBox<A>>::call_box::h05b222e46803eb30
  33:     0x7f3e49185eb0 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  34:     0x7f3e41fd1dc4 - start_thread
  35:     0x7f3e48e40cec - clone
  36:                0x0 - <unknown>


error[E0533]: `Flag::Unknown(_)` does not name a unit variant, unit struct or a constant
   --> src/mercurial/manifest/manifest.rs:141:1
    |
141 | graphql_enum!(Flag {
    | ^
    |
    = note: this error originates in a macro outside of the current crate

error: internal compiler error: rust/1.13/src/rust/src/librustc_typeck/check/mod.rs:4366: parenthesized parameters cannot appear in ExprPath
   --> src/mercurial/manifest/manifest.rs:141:1
    |
141 | graphql_enum!(Flag {
    | ^
    |
    = note: this error originates in a macro outside of the current crate

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

```

The code in question is using the `graphql_enum` macro from the [juniper crate](https://github.com/mhallin/juniper). I'm trying to get a smaller repro case.

The enum in question is basically:
```
enum Flag {
  Unknown(u8),
  Foo,
  Bar,
  Blatt,
};
```

which I tried to (incorrectly) use with `graphql_enum` as:
```
graphql_enum!(Flag {
  Flag::Unknown(_) => "UNKNOWN",
  Flag::Foo => "FOO",
  Flag::Bar => "BAR",
  Flag::Blatt => "BLATT",
});
```

which expands to expressions of the form `&Foo::Unknown::(_)`, which seems to be what's making the compiler upset. But when I do a much simpler example with these same elements, the compiler doesn't crash (just fails with lots of reasonable-looking errors).

**Comment by Mark-Simulacrum** [comment]
Without a smaller reproduction (or at least a branch somewhere) I don't think this is going to be purposefully fixed; as such, I'm going to close. Please let us know if you could get a branch that fails with this problem and we'll reopen!
