### ISSUE TITLE
rust-lldb throws Python errors macOS 10.12.2

### ISSUE THREAD

**Issue by dchammond** [rust-lang/rust#38380]
When starting `rust-lldb` on stable or nightly it throws numerous python errors from the init script for the LLDB framework.

```
~  rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.13.0 (2c6933acc 2016-11-07)
```

```
~  rust-lldb
(lldb) command source -s 0 '/tmp/rust-lldb-commands.fn4R9i'
Executing commands in '/tmp/rust-lldb-commands.fn4R9i'.
(lldb) command script import "/Users/dillon/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc/lldb_rust_formatters.py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
error: module importing failed: No module named six
  File "temp.py", line 1, in <module>
  File "/Users/dillon/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc/lldb_rust_formatters.py", line 11, in <module>
    import lldb
  File "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six

(lldb) quit
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
```

For the record:

```
~  pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
joblib (0.10.3)
pip (9.0.1)
powerline-status (2.5)
setuptools (31.0.0)
six (1.10.0)
wheel (0.29.0)
```

**Comment by frewsxcv** [comment]
If you're looking for a fix, you'll need to `pip install six`. This *might* be an issue with LLDB upstream. Here are similar issues:

* https://github.com/Homebrew/homebrew-core/issues/2712
* http://community.rubymotion.com/t/nameerror-name-run-one-line-is-not-defined/1538/21

**Comment by dchammond** [comment]
Unfortunately `six` is already installed

```
~  pip install six
Requirement already satisfied: six in /usr/local/lib/python3.5/site-packages
```

**Comment by frewsxcv** [comment]
Presumably, your `pip` is mapped to your own Python 3 environment (not the system Python). I wouldn't be surprised if LLDB uses Python 2.

**Comment by frewsxcv** [comment]
@dchammond Did you get this working?

**Comment by dchammond** [comment]
Sorry, sort of, I used the hack suggested in your second link which was to `brew unlink python && brew unlink python3`, then it runs fine. This is an unfortunate convince, though not rust's fault it seems.

**Comment by michaelwoerister** [comment]
Yeah, unfortunately LLDB only runs with the pre-installed version of Python. Even using the same version installed via homebrew often fails.
