### ISSUE TITLE
rustc 1.14 miscompiles bloom-0.3.2

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38423]
Against https://github.com/nicklan/bloom-rs, commit 7fa2d6747a39f8b723656f173933a77908ad087c

Using

```
rustc 1.15.0-nightly (8f02c429a 2016-12-15)
binary: rustc
commit-hash: 8f02c429ad3e2ad687a222d1daae2e04bb9bb876
commit-date: 2016-12-15
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9
```

I get:

```
~/dev/bloom-rs⟫ cargo +beta test
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.18
   Compiling bit-vec v0.4.3
   Compiling bloom v0.3.1 (file:///mnt2/dev/bloom-rs)
   Compiling rand v0.3.15
    Finished debug [unoptimized + debuginfo] target(s) in 4.68 secs
     Running target/debug/deps/bloom-3c428171117ad4c0

running 12 tests
test bloom::tests::simple ... ok
test bloom::tests::intersect ... FAILED
test bloom::tests::union ... FAILED
test counting::tests::estimate_count ... ok
test counting::tests::remove ... ok
test counting::tests::simple ... ok
test valuevec::tests::over_with_max ... ok
test valuevec::tests::set_get_no_overlap ... ok
test valuevec::tests::set_get_overlap ... ok
test valuevec::tests::set_over_max ... ok
test valuevec::tests::with_max ... ok
test bloom::tests::fpr_test ... ok

failures:

---- bloom::tests::intersect stdout ----
        thread 'bloom::tests::intersect' panicked at 'assertion failed: b1.contains(&1)', src/bloom.rs:308
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- bloom::tests::union stdout ----
        thread 'bloom::tests::union' panicked at 'assertion failed: b1.contains(&2)', src/bloom.rs:322


failures:
    bloom::tests::intersect
    bloom::tests::union

test result: FAILED. 10 passed; 2 failed; 0 ignored; 0 measured

error: test failed
```

This does not happen on Rust 1.13.

cc @nicklan

**Comment by arielb1** [comment]
The problem is that `BloomFilter` relies on multiple instantiations of `std::collections::hash_map::RandomState` within a single execution being consistent.

Given that this was never guaranteed and quite intentionally broken, I'll say its NOTABUG.

**Comment by brson** [comment]
Thanks for investigating @arielb1 !

cc @rust-lang/libs fallout from the hashmap randomstate change.
