### ISSUE TITLE
Failed to connect to the Mir Server (Running compiled binary fails on Windows Linux Subsystem, Ubuntu 14.04 with Rust 1.14.0 and latest nightly)

### ISSUE THREAD

**Issue by stianeklund** [rust-lang/rust#38599]
Compiling works, but running the binary fails on WSL with Rust 1.14.0 and nightly.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to connect to the Mir Server"', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:837
stack backtrace:
   1:     0x7f9ec1a4179a - std::sys::imp::backtrace::tracing::imp::write::h0d1aacfb8fc693ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f9ec1a43aef - std::panicking::default_hook::{{closure}}::hff87359baf5754d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7f9ec1a436ee - std::panicking::default_hook::h936f17ca3b2b98dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x7f9ec1a43ed7 - std::panicking::rust_panic_with_hook::he9c830ab830c7944
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7f9ec1a43d64 - std::panicking::begin_panic::hbd10b7f500042f98
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7f9ec1a43c89 - std::panicking::begin_panic_fmt::h49583ddd44614a0d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x7f9ec1a43c17 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x7f9ec1a69d7d - core::panicking::panic_fmt::h3b787d0ceafd7204
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7f9ec1a0cd24 - core::result::unwrap_failed::hb53ada5fe8b46ab4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x7f9ec1a0a719 - <core::result::Result<T, E>>::unwrap::h750fdc79084f4529
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:737
  11:     0x7f9ec1a15b2b - chip8::display::Display::new::h0748ade1323c511e
                        at /home/stian/dev/projects/chip8/src/display.rs:18
  12:     0x7f9ec1a16c08 - chip8::main::h56583d0405cd70cc
                        at /home/stian/dev/projects/chip8/src/main.rs:41
  13:     0x7f9ec1a4a94a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x7f9ec1a443d6 - std::rt::lang_start::ha749a62502c90792
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  15:     0x7f9ec1a16e92 - main
  16:     0x7f9ec06e1f44 - __libc_start_main
  17:     0x7f9ec1a08408 - <unknown>
  18:                0x0 - <unknown>

```

**Comment by est31** [comment]
Hello!

I think WSL wasn't made for GUI applications. They can't run in WSL without some manual work (and its not officially supported by Microsoft). Rust runs just as well with an msvc linker, or with mingw/msys. Maybe try those instead.

The error you seem to have is less related with rust and more related with your actual program (aka a bug in the program). This issue tracker is for bugs in the Rust compiler or the language.

**Comment by stianeklund** [comment]
@est31 It must be a change in WSL perhaps, it worked earlier. :-) Anyhow, I thought as much and have it running fine in Virtualbox. It's likely the change has happened on Microsoft's end. Consider this solved.

**Comment by alexcrichton** [comment]
@stianeklund does this panic come from the Rust compiler itself? From the backtrace it looks like a local program perhaps?

**Comment by stianeklund** [comment]
@alexcrichton It comes from the compiled program, indeed.

**Comment by alexcrichton** [comment]
Ah ok, in that case I think this may be a bug locally rather in the compiler itself, so closing.
