### ISSUE TITLE
Compiler error: No def'n found for DefId

### ISSUE THREAD

**Issue by thirtythreeforty** [rust-lang/rust#38651]
The following code ([Playground link](https://is.gd/VeDxzS)) produces an ICE on Rust 1.14.0 on Arch Linux x86_64.

```rust
pub trait AnyFilter {
    type Item;
    fn any_filter<F>(self, filters: &[F]) -> AnyFilterImpl<F, Self>
        where F: FnMut(&Self::Item) -> bool,
        Self: Iterator;
}

impl<I: Iterator> AnyFilter for I {
    type Item = I::Item;

    fn any_filter<F>(self, filters: &[F]) -> AnyFilterImpl<F, Self>
        where F: FnMut(&Self::Item) -> bool
    {
        AnyFilterImpl { filters: filters, source: self }
    }
}

#[derive(Clone)]
pub struct AnyFilterImpl<F, I>
    where F: FnMut(&I::Item) -> bool,
    I: Iterator
{
    filters: Vec<F>,
    source: I
}

impl<F, I> Iterator for AnyFilterImpl<F, I>
    where F: FnMut(&I::Item) -> bool,
    I: Iterator
{
    type Item = I::Item;

    fn next(&mut self) -> Option<Self::Item> where Self: Sized {
        self.source.by_ref().next().and_then(|val| {
            for filter in self.filters {
                if filter(val) {
                    return Some(val);
                }
            }
            None
        })
    }
}

fn main() {
}
```

The error is:

```
error: internal compiler error: src/librustc/ty/mod.rs:2083: No def'n found for DefId { krate: CrateNum(0), node: DefIndex(52) => typo/f4c2e3f433cba122302729faf5a796d0-exe::any_filter[0]::AnyFilter[0] } in tcx.impl_or_trait_items
```

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:424
stack backtrace:
   1:     0x7f7b9331efba - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /build/rust/src/rustc-1.14.0/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f7b9333124f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:247
   3:     0x7f7b9332da95 - std::panicking::default_hook::h5897799da33ece67
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:257
   4:     0x7f7b9332e1b7 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:451
   5:     0x7f7b8f78af9a - std::panicking::begin_panic::h7ee1a5d23402297a
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:413
   6:     0x7f7b8f79c27d - rustc_errors::Handler::bug::hcb152875f06770ca
                        at /build/rust/src/rustc-1.14.0/src/librustc_errors/lib.rs:424
   7:     0x7f7b907e6851 - rustc::session::opt_span_bug_fmt::{{closure}}::hac6e8f2df662620f
                        at /build/rust/src/rustc-1.14.0/src/librustc/session/mod.rs:770
   8:     0x7f7b9071f21e - rustc::session::opt_span_bug_fmt::he7e61f6adc55e29d
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1057
                        at /build/rust/src/rustc-1.14.0/src/librustc/session/mod.rs:766
   9:     0x7f7b9071ee82 - rustc::session::bug_fmt::h995c6792d8929834
                        at /build/rust/src/rustc-1.14.0/src/librustc/session/mod.rs:750
  10:     0x7f7b907a13e5 - rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::impl_or_trait_items::hccd3536ffe440893
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/mod.rs:2083
                        at /build/rust/src/rustc-1.14.0/src/librustc/dep_graph/dep_tracking_map.rs:145
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/mod.rs:2081
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/mod.rs:2254
  11:     0x7f7b92c05727 - <core::iter::Map<I, F> as core::iter_private::TrustedRandomAccess>::get_unchecked::h29aea1fc2836b633
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1263
                        at /build/rust/src/rustc-1.14.0/src/libcore/iter/mod.rs:1027
  12:     0x7f7b92c9a8d0 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::one_bound_for_assoc_type::hc8dd689db5184164
                        at /build/rust/src/rustc-1.14.0/src/libcore/iter/mod.rs:828
                        at /build/rust/src/rustc-1.14.0/src/libcore/iter/mod.rs:712
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1281
  13:     0x7f7b92c9a30f - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::find_bound_for_assoc_item::he8bb900cda55902b
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1235
  14:     0x7f7b92c9bc51 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::finish_resolving_def_to_ty::hb33ba6ff972bf66a
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1352
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1641
  15:     0x7f7b92c9d82d - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_ty_to_ty::h4c84cc5def66e1b0
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1782
  16:     0x7f7b92c9d477 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_ty_to_ty::h4c84cc5def66e1b0
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1685
  17:     0x7f7b92ba1af0 - <rustc_data_structures::accumulate_vec::AccumulateVec<A> as core::iter::traits::FromIterator<<A as rustc_data_structures::array_vec::Array>::Element>>::from_iter::hfdecda85b6ee2dc0
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:1471
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:637
                        at /build/rust/src/rustc-1.14.0/src/libcore/ops.rs:2645
                        at /build/rust/src/rustc-1.14.0/src/libcore/option.rs:383
                        at /build/rust/src/rustc-1.14.0/src/libcore/iter/mod.rs:982
                        at /build/rust/src/rustc-1.14.0/src/librustc_data_structures/array_vec.rs:83
                        at /build/rust/src/rustc-1.14.0/src/librustc_data_structures/accumulate_vec.rs:45
  18:     0x7f7b92bfd5cd - <T as rustc::ty::context::InternIteratorElement<T, R>>::intern_with::hbed1effdf5d4565d
                        at /build/rust/src/rustc-1.14.0/src/libcore/iter/iterator.rs:1196
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1585
  19:     0x7f7b92c94769 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::convert_parenthesized_parameters::h1b374d401abe269f
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1573
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1526
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:636
  20:     0x7f7b92cc502b - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::create_substs_for_ast_path::{{closure}}::h3b953e74f9262ad4
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:494
  21:     0x7f7b92bd8a11 - rustc::ty::subst::<impl rustc::ty::Slice<rustc::ty::subst::Kind<'tcx>>>::fill_item::hc2473b62b2e76567
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/subst.rs:215
  22:     0x7f7b92c93f77 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::create_substs_for_ast_path::hcb4d8d3715bef93a
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/subst.rs:182
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:473
  23:     0x7f7b92c96b8c - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::create_substs_for_ast_trait_ref::he7e542db1af8aef7
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:826
  24:     0x7f7b92c95771 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_path_to_poly_trait_ref::h614bbc13174ca471
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:738
  25:     0x7f7b92caeced - rustc_typeck::collect::ty_generic_predicates::h881ada9eb3a9f029
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/astconv.rs:673
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/collect.rs:1840
  26:     0x7f7b92ca4fe5 - rustc_typeck::collect::convert_method::h8688aa375c36d11a
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/collect.rs:574
  27:     0x7f7b92ca84bd - rustc_typeck::collect::convert_item::h7034bc47a5dd94fa
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/collect.rs:927
  28:     0x7f7b92ca1442 - rustc_typeck::collect::collect_item_types::h129f81a692b66ae1
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/collect.rs:135
                        at /build/rust/src/rustc-1.14.0/src/librustc/dep_graph/visit.rs:46
                        at /build/rust/src/rustc-1.14.0/src/librustc/hir/mod.rs:445
                        at /build/rust/src/rustc-1.14.0/src/librustc/dep_graph/visit.rs:57
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/mod.rs:2844
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/collect.rs:97
  29:     0x7f7b92cc0585 - rustc_typeck::check_crate::h49660caa41b9699c
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/lib.rs:350
                        at /build/rust/src/rustc-1.14.0/src/librustc/util/common.rs:38
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/lib.rs:349
                        at /build/rust/src/rustc-1.14.0/src/librustc/session/mod.rs:222
                        at /build/rust/src/rustc-1.14.0/src/librustc_typeck/lib.rs:348
  30:     0x7f7b936e15ae - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h5a9a7c8e1b6dbe3a
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/driver.rs:891
  31:     0x7f7b936ba86a - rustc_driver::driver::phase_3_run_analysis_passes::h823704ee01fd0a1e
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1028
                        at /build/rust/src/rustc-1.14.0/src/libstd/thread/local.rs:245
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1025
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1012
                        at /build/rust/src/rustc-1.14.0/src/libstd/thread/local.rs:245
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:1009
                        at /build/rust/src/rustc-1.14.0/src/librustc/ty/context.rs:797
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/driver.rs:869
  32:     0x7f7b936acd47 - rustc_driver::driver::compile_input::h66a0adaf05fab85d
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/driver.rs:173
  33:     0x7f7b936d2490 - rustc_driver::run_compiler::hafe7bbfedf95a825
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/lib.rs:222
  34:     0x7f7b936073d8 - std::panicking::try::do_call::h5ff5e568cb9cce51
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/lib.rs:1138
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/lib.rs:138
                        at /build/rust/src/rustc-1.14.0/src/librustc_driver/lib.rs:1072
                        at /build/rust/src/rustc-1.14.0/src/libstd/panic.rs:295
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:356
  35:     0x7f7b93338ffa - __rust_maybe_catch_panic
                        at /build/rust/src/rustc-1.14.0/src/libpanic_unwind/lib.rs:97
  36:     0x7f7b93627038 - <F as alloc::boxed::FnBox<A>>::call_box::h92e2f4ed0df1d5b6
                        at /build/rust/src/rustc-1.14.0/src/libstd/panicking.rs:332
                        at /build/rust/src/rustc-1.14.0/src/libstd/panic.rs:351
                        at /build/rust/src/rustc-1.14.0/src/libstd/thread/mod.rs:287
                        at /build/rust/src/rustc-1.14.0/src/liballoc/boxed.rs:595
  37:     0x7f7b9332cd64 - std::sys::imp::thread::Thread::new::thread_start::ha102a6120fc52763
                        at /build/rust/src/rustc-1.14.0/src/liballoc/boxed.rs:605
                        at /build/rust/src/rustc-1.14.0/src/libstd/sys_common/thread.rs:21
                        at /build/rust/src/rustc-1.14.0/src/libstd/sys/unix/thread.rs:84
  38:     0x7f7b8e6fe453 - start_thread
  39:     0x7f7b92ff47de - __GI___clone
  40:                0x0 - <unknown>
```
Version info:
```
rustc 1.14.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.14.0
LLVM version: 3.9
```

**Comment by apasel422** [comment]
Yields the following on beta and nightly:

```
error[E0221]: ambiguous associated type `Item` in bounds of `Self`
 --> <anon>:4:25
  |
2 |     type Item;
  |     ---------- ambiguous `Item` from `AnyFilter`
3 |     fn any_filter<F>(self, filters: &[F]) -> AnyFilterImpl<F, Self>
4 |         where F: FnMut(&Self::Item) -> bool,
  |                         ^^^^^^^^^^ ambiguous associated type `Item`
  |
note: associated type `Self` could derive from `std::iter::Iterator`
 --> <anon>:4:25
  |
4 |         where F: FnMut(&Self::Item) -> bool,
  |                         ^^^^^^^^^^
```

**Comment by thirtythreeforty** [comment]
Ah.  If it works in beta, sounds like the problem has already been identified.  Does a unit test exist for this?

**Comment by thirtythreeforty** [comment]
This is no longer an iCE in 1.15.x, so I'll close!
