### ISSUE TITLE
itm fails its tests in Rust 1.15

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38684]
Regression from 1.14.

https://github.com/japaric/itm commit 2a27aa2e2bd66598d39e5c1f8ec4f1a7987074b7

```
brian@ip-10-145-43-250:~/dev/itm⟫ rustc +beta -Vv
rustc 1.15.0-beta.1 (d9a0f0df7 2016-12-19)
binary: rustc
commit-hash: d9a0f0df7051c603011d6b60fbdd155318fc47f3
commit-date: 2016-12-19
host: x86_64-unknown-linux-gnu
release: 1.15.0-beta.1
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/itm⟫ cargo +beta test
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/itm-a7dae96d00473452

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/deps/itmdump-803690837f746b89

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/deps/smoke-865b2435c4af1044

running 3 tests
test multiple ... FAILED
test chunks ... FAILED
test single ... FAILED

failures:

---- multiple stdout ----
        thread 'multiple' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- chunks stdout ----
        thread 'chunks' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837

---- single stdout ----
        thread 'single' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837


failures:
    chunks
    multiple
    single

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured

error: test failed
```

cc @japaric

**Comment by alexcrichton** [comment]
Fixed in https://github.com/japaric/itm/pull/9, caused by https://github.com/rust-lang/cargo/pull/3102

I'd prefer to close this as the "bug" here is that Cargo's output directory structure changed slightly, but we haven't really provided any strong guarantee about the structure so it's just a bug fix really.

**Comment by brson** [comment]
Thanks @alexcrichton. I concur there's nothing else we can do here.
