### ISSUE TITLE
Regression in cargo-check 0.2.2 test suite in Rust 1.15

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38722]
https://github.com/rsolomo/cargo-check at d446f7865b2ac925c8e05c7129998084718c00d4

```
brian@ip-10-145-43-250:~/dev/cargo-check⟫ rustc +beta -Vv
rustc 1.15.0-beta.1 (d9a0f0df7 2016-12-19)
binary: rustc
commit-hash: d9a0f0df7051c603011d6b60fbdd155318fc47f3
commit-date: 2016-12-19
host: x86_64-unknown-linux-gnu
release: 1.15.0-beta.1
LLVM version: 3.9

```

```
brian@ip-10-145-43-250:~/dev/cargo-check⟫ cargo +beta test
   Compiling itoa v0.1.1
   Compiling num-traits v0.1.35
   Compiling serde v0.8.17
   Compiling dtoa v0.2.2
   Compiling serde_json v0.8.3
   Compiling cargo-check v0.2.2 (file:///mnt2/dev/cargo-check)
    Finished debug [unoptimized + debuginfo] target(s) in 12.60 secs
     Running target/debug/deps/cargo_check-7f0aeef4249df34a

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/deps/multitarget-fd24899997c91294

running 5 tests
test multiple_targets ... FAILED
test multiple_targets_2 ... FAILED
test multiple_targets_3 ... FAILED
test multiple_targets_4 ... FAILED
test self_test ... FAILED

failures:

---- multiple_targets stdout ----
        thread 'multiple_targets' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- multiple_targets_2 stdout ----
        thread 'multiple_targets_2' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837

---- multiple_targets_3 stdout ----
        thread 'multiple_targets_3' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837

---- multiple_targets_4 stdout ----
        thread 'multiple_targets_4' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837

---- self_test stdout ----
        thread 'self_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:837


failures:
    multiple_targets
    multiple_targets_2
    multiple_targets_3
    multiple_targets_4
    self_test

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured

error: test failed
```

Seems likely to be https://github.com/rust-lang/cargo/issues/3368

 cc @rsolomo

**Comment by alexcrichton** [comment]
I believe this was actually https://github.com/rust-lang/cargo/pull/3102, and I've submitted a fix: https://github.com/rsolomo/cargo-check/pull/21

**Comment by brson** [comment]
Thanks @alexcrichton. I suppose we should wait and see if that PR is accepted, but seems like that's all for us to do.

**Comment by rsolomo** [comment]
Thanks for the PR. It has been merged.
