### ISSUE TITLE
[i128] ICE when calling function with #[repr(C)]'d tuple struct

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38763]
The following code causes an ICE on current master (ac5cd3bd43b9dbe681417e482065b24c08c544e8):

```rust
#![feature(i128_type)]

#[repr(C)]
struct Foo(i128);

#[link(name = "test", kind = "static")]
extern "C" {
    fn foo(f: Foo) -> Foo;
}

fn main() {
    unsafe {
        foo(Foo(1));
    }
}
```

ICE message:

```
error: internal compiler error: src/librustc_trans/cabi_x86_64.rs:321: llregtype: unhandled class

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:423
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

cc #35118 (tracking issue)
cc @nagisa , me

**Comment by kennytm** [comment]
Still ICE-ing but with a different stack trace.

```
rustc 1.19.0-nightly (6a5fc9eec 2017-05-02)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329
stack backtrace:
<snip>
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:49
  10: rustc_trans::cabi_x86_64::compute_abi_info::{{closure}}
  11: rustc_trans::abi::FnType::adjust_for_abi
  12: rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_block
  13: rustc_trans::mir::trans_mir
  14: rustc_trans::trans_item::TransItem::define
  15: rustc_trans::base::trans_crate
  16: rustc_driver::driver::phase_4_translate_to_llvm
<snip>
```

Relevant line I guess (there is only one unwrap right?): https://github.com/rust-lang/rust/blob/b16c7a235fa0f57fed6b7ec13ffd3cff1bcdd9ad/src/librustc_trans/cabi_x86_64.rs#L246

**Comment by eddyb** [comment]
This is very suspicious - that `unwrap` *can't possibly* fail - because it only runs when `in_mem` is `false` but when `cls` is `Err`, `in_mem` is `true`:
https://github.com/rust-lang/rust/blob/b16c7a235fa0f57fed6b7ec13ffd3cff1bcdd9ad/src/librustc_trans/cabi_x86_64.rs#L215-L216
