### ISSUE TITLE
ICE: Encountered error `Unimplemented` selecting `Binder(<[i32; 1000] as std::clone::Clone>)` during trans

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#38808]
```rust
fn test<T: Copy>(x: T) { x.clone(); }
fn main() { test([0; 1000]); }
```

```text
rustc 1.16.0-nightly (4ecc85beb 2016-12-28)
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/common.rs:660: Encountered error `Unimplemented` selecting `Binder(<[i32; 1000] as std::clone::Clone>)` during trans

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:382
stack backtrace:
   1:     0x7f8721bd638a - std::sys::imp::backtrace::tracing::imp::write::h0d1aacfb8fc693ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f8721be46ff - std::panicking::default_hook::{{closure}}::hff87359baf5754d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7f8721be429d - std::panicking::default_hook::h936f17ca3b2b98dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:359
   4:     0x7f8721be4ba7 - std::panicking::rust_panic_with_hook::he9c830ab830c7944
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7f8720d53b4b - std::panicking::begin_panic::h91982347d535fafe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7f8720d72c13 - rustc::session::opt_span_bug_fmt::{{closure}}::h91ff9525fefce1f6
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/<panic macros>:3
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:782
   7:     0x7f8720d72a3c - rustc::session::span_bug_fmt::haf6a9c040a3bb825
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1060
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1049
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1045
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1060
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:779
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:772
   8:     0x7f8720deade2 - rustc_trans::common::fulfill_obligation::{{closure}}::{{closure}}::hf4a4fb99978256fd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/common.rs:974
   9:     0x7f8720de7411 - rustc_trans::common::fulfill_obligation::h854442356e9db792
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/infer/mod.rs:442
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1033
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1030
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:846
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/infer/mod.rs:442
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/common.rs:949
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/dep_graph/dep_tracking_map.rs:145
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/common.rs:943
  10:     0x7f8720de2c68 - rustc_trans::collector::do_static_dispatch::hf0b80195a40066af
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:897
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:862
  11:     0x7f8720de22fa - <rustc_trans::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_operand::h1a63549ffd9691a3
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:610
  12:     0x7f8720de29d6 - <rustc_trans::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind::h3a4fd019aba3a232
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:424
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:693
  13:     0x7f8720d6e2e7 - rustc::mir::visit::Visitor::visit_mir::h2d438cdc687d2590
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:354
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:290
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:96
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:256
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/mir/visit.rs:90
  14:     0x7f8720de07b2 - rustc_trans::collector::collect_items_rec::h12d3f5e6e48a9c8d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:1258
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:377
  15:     0x7f8720de0a6f - rustc_trans::collector::collect_items_rec::h12d3f5e6e48a9c8d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:384
  16:     0x7f8720dcd1b0 - rustc_trans::base::collect_and_partition_translation_items::{{closure}}::h87ac2618d59e98bb
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:285
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/dep_graph/graph.rs:70
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/collector.rs:276
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/base.rs:2031
  17:     0x7f8720dc8abf - rustc_trans::base::collect_and_partition_translation_items::ha2fbfc4b378559ea
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/util/common.rs:34
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/base.rs:2030
  18:     0x7f8720dbc57d - rustc_trans::base::trans_crate::hb2a0cffce6a10d65
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/base.rs:1611
  19:     0x7f8721f7fb6d - rustc_driver::driver::phase_4_translate_to_llvm::hb8bd437a1d5aaeda
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:1045
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/util/common.rs:34
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:1043
  20:     0x7f8721f5029f - rustc_driver::driver::compile_input::{{closure}}::ha0e33150308cf6ef
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:204
  21:     0x7f8721f7e341 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::hd352d0090529a6be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:991
  22:     0x7f8721f67b88 - rustc_driver::driver::phase_3_run_analysis_passes::hf45ad5d717ac6301
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1033
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1030
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1017
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1014
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:782
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:865
  23:     0x7f8721f4e1d2 - rustc_driver::driver::compile_input::hc9da7de451d406ba
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:171
  24:     0x7f8721f93b47 - rustc_driver::run_compiler::h408af14fa24a33a5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:221
  25:     0x7f8721eb19e8 - std::panicking::try::do_call::h2c149962956958c1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:1117
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:137
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:1051
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  26:     0x7f8721bed3ca - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  27:     0x7f8721ed3328 - <F as alloc::boxed::FnBox<A>>::call_box::hf839c55097f480b2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  28:     0x7f8721be3564 - std::sys::imp::thread::Thread::new::thread_start::h1fa04983ba2271d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  29:     0x7f8719d78183 - start_thread
  30:     0x7f872188a37c - clone
  31:                0x0 - <unknown>
```

**Comment by jonas-schievink** [comment]
Duplicate of #25733

**Comment by steveklabnik** [comment]
whoops!
