### ISSUE TITLE
Regression in xsv-0.10.3 test suite, Rust 1.15

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38976]
https://github.com/BurntSushi/xsv b08250c31ae07bf6ef1b9b5f9c386ea5c7aeb8b8

Not on stable, but it is on beta.

```
brian@ip-10-145-43-250:~/dev/log4rs-rolling-file⟫ rustc +beta -Vv
rustc 1.15.0-beta.3 (a035041ba 2017-01-07)
binary: rustc
commit-hash: a035041ba450ce3061d78a2bdb9c446eb5321d0d
commit-date: 2017-01-07
host: x86_64-unknown-linux-gnu
release: 1.15.0-beta.3
LLVM version: 3.9
```

All tests fail:

```

---- test_stats::stats_sum_nulls1::no_headers_no_index stdout ----
        thread 'test_stats::stats_sum_nulls1::no_headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:84

---- test_stats::stats_sum_nulls2::headers_index stdout ----
        thread 'test_stats::stats_sum_nulls2::headers_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_sum_nulls2::headers_no_index stdout ----
        thread 'test_stats::stats_sum_nulls2::headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_sum_nulls2::no_headers_index stdout ----
        thread 'test_stats::stats_sum_nulls2::no_headers_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_sum_nulls2::no_headers_no_index stdout ----
        thread 'test_stats::stats_sum_nulls2::no_headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:84

---- test_stats::stats_zero_cardinality::headers_index stdout ----
        thread 'test_stats::stats_zero_cardinality::headers_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:84

---- test_stats::stats_zero_cardinality::headers_no_index stdout ----
        thread 'test_stats::stats_zero_cardinality::headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_zero_mean::headers_no_index stdout ----
        thread 'test_stats::stats_zero_mean::headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_zero_median::headers_index stdout ----
        thread 'test_stats::stats_zero_median::headers_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_zero_mean::headers_index stdout ----
        thread 'test_stats::stats_zero_mean::headers_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_zero_median::headers_no_index stdout ----
        thread 'test_stats::stats_zero_median::headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_zero_mode::headers_no_index stdout ----
        thread 'test_stats::stats_zero_mode::headers_no_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_stats::stats_zero_mode::headers_index stdout ----
        thread 'test_stats::stats_zero_mode::headers_index' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- test_table::table stdout ----
        thread 'test_table::table' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845


```

Probably expected cargo breakage, but I don't see a previous report, and xsv head is fixed. cc @BurntSushi

**Comment by BurntSushi** [comment]
This was the fix: https://github.com/BurntSushi/xsv/pull/53
