### ISSUE TITLE
Regression in vk_generator 0.2.1, Rust 1.15

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38974]
https://github.com/Osspial/vk-rs bda37be653e259cb50dfc68cfe1a2462fdec756d

Note to build this the https://github.com/KhronosGroup/Vulkan-Docs repo must be checked out to the right place.

Beta regression.

```
brian@ip-10-145-43-250:~/dev/log4rs-rolling-file⟫ rustc +beta -Vv
rustc 1.15.0-beta.3 (a035041ba 2017-01-07)
binary: rustc
commit-hash: a035041ba450ce3061d78a2bdb9c446eb5321d0d
commit-date: 2017-01-07
host: x86_64-unknown-linux-gnu
release: 1.15.0-beta.3
LLVM version: 3.9
```

```
101 brian@ip-10-145-43-250:~/dev/vk-rs/vk_generator⟫ cargo +nightly test
   Compiling vk_api v1.0.36 (file:///mnt2/dev/vk-rs/vk_api)
   Compiling boolinator v0.1.0
   Compiling bitflags v0.7.0
   Compiling xml-rs v0.3.5
   Compiling vk_generator v0.2.1 (file:///mnt2/dev/vk-rs/vk_generator)
    Finished debug [unoptimized + debuginfo] target(s) in 13.4 secs
     Running target/debug/deps/lib-e99e150af901ffb6

running 4 tests
test nondefault_global ... FAILED
test default_struct ... FAILED
test default_global ... FAILED
test nondefault_struct ... FAILED

failures:

---- nondefault_global stdout ----
        thread 'nondefault_global' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- default_struct stdout ----
        thread 'default_struct' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845

---- default_global stdout ----
        thread 'default_global' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- nondefault_struct stdout ----
        thread 'nondefault_struct' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:845


failures:
    default_global
    default_struct
    nondefault_global
    nondefault_struct

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured

error: test failed
```

This looks like expected breakage due to using unspecified details of cargo directory layout, but I can't tell exactly why.

cc @Osspial

**Comment by mbrubeck** [comment]
These tests are panicking at `env::var("OUT_DIR").unwrap()` so this is another case of #38391 (rust-lang/cargo#3368).

**Comment by mbrubeck** [comment]
Fixed in Osspial/vk-rs#6

This regression was slightly different than most of the others.  It appears that `$OUT_DIR` was no longer set when building *or* running the integration tests, but adding an empty build script causes it to be set again at both times.

**Comment by mbrubeck** [comment]
See also rust-lang/cargo#3379.

**Comment by brson** [comment]
Closing per linked issues.
