### ISSUE TITLE
1.14.0 mips test failures: net "timeouts" tests

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#39014]
Build machine: https://db.debian.org/machines.cgi?host=mips-aql-01
Build log: https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=mips&ver=1.14.0%2Bdfsg1-3&stamp=1484077706
Raw build log: https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=mips&ver=1.14.0%2Bdfsg1-3&stamp=1484077706&raw=1

This is after applying #38650 and #38675. The LLVM diff between Debian vs Rust is [here](https://gist.github.com/infinity0/873566481db105fea47630da88e1b632).

Note that, because of these failures, the whole-compiler tests (e.g. run-pass etc) have not been run, but they probably also have failures.

Relevant links:
https://github.com/rust-lang/rust/blob/1.14.0/src/librustc_back/target/mips_unknown_linux_gnu.rs
https://github.com/rust-lang/rust/blob/1.14.0/mk/cfg/mips-unknown-linux-gnu.mk

~~~~
test net::addr::tests::to_socket_addr_str_bad ... ok
test net::tcp::tests::test_read_timeout ... ok
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `Some(Duration { secs: 15410, nanos: 0 })`, right: `Some(Duration { secs: 0, nanos: 15410000 })`)', src/libstd/net/tcp.rs:1037
stack backtrace:
   1: 0x7760a8d3 - std::sys::imp::backtrace::tracing::imp::write::h6a9c57665d54ffb2
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2: 0x77657daf - std::panicking::default_hook::{{closure}}::hafb54aec2b339d2d
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:247
   3: 0x77637feb - std::panicking::rust_panic_with_hook::h95213085ace59c69
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:263
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:451
   4: 0x7763792b - std::panicking::begin_panic::hcbad7f9d34dc4a4f
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:413
   5: 0x776377d3 - std::panicking::begin_panic_fmt::h29140d07f42a68b3
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:397
   6: 0x77538b43 - std::net::tcp::tests::timeouts::h0ec9c2a738748ae5
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/net/tcp.rs:1037
   7: 0x7766aa77 - <F as test::FnBox<T>>::call_box::h1e8b0f3e8d4f40ca
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1265
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:141
   8: 0x7765b1fb - std::panicking::try::do_call::h1a9e31a8c5a5a291
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1211
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
   9: 0x776b419f - __rust_maybe_catch_panic
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
  10: 0x7765b3db - std::panicking::try::do_call::hc453b0f24ea28e2d
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1210
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
  11: 0x776b419f - __rust_maybe_catch_panic
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
  12: 0x7766417f - <F as alloc::boxed::FnBox<A>>::call_box::hc1ea8b30e2bd2527
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/thread/mod.rs:287
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:595
  13: 0x776a6abb - std::sys::imp::thread::Thread::new::thread_start::h177a2a20f0a67315
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:605
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys_common/thread.rs:21
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/thread.rs:84
  14: 0x773a98bf - <unknown>
test net::tcp::tests::timeouts ... FAILED
test net::tcp::tests::ttl ... ok
test net::tcp::tests::write_close ... ok
test net::udp::tests::bind_error ... ok
test net::udp::tests::connect_send_recv ... ok
test net::udp::tests::debug ... ok
test net::udp::tests::set_nonblocking ... ok
test net::udp::tests::socket_name_ip4 ... ok
test net::udp::tests::socket_smoke_test_ip4 ... ok
test net::tcp::tests::test_read_with_timeout ... ok
test net::udp::tests::test_read_timeout ... ok
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `Some(Duration { secs: 15410, nanos: 0 })`, right: `Some(Duration { secs: 0, nanos: 15410000 })`)', src/libstd/net/udp.rs:546
stack backtrace:
   1: 0x7760a8d3 - std::sys::imp::backtrace::tracing::imp::write::h6a9c57665d54ffb2
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2: 0x77657daf - std::panicking::default_hook::{{closure}}::hafb54aec2b339d2d
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:247
   3: 0x77637feb - std::panicking::rust_panic_with_hook::h95213085ace59c69
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:263
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:451
   4: 0x7763792b - std::panicking::begin_panic::hcbad7f9d34dc4a4f
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:413
   5: 0x776377d3 - std::panicking::begin_panic_fmt::h29140d07f42a68b3
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:397
   6: 0x7753e227 - std::net::udp::tests::timeouts::h3ada528d964e3a48
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/net/udp.rs:546
   7: 0x7766aa77 - <F as test::FnBox<T>>::call_box::h1e8b0f3e8d4f40ca
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1265
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:141
   8: 0x7765b1fb - std::panicking::try::do_call::h1a9e31a8c5a5a291
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1211
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
   9: 0x776b419f - __rust_maybe_catch_panic
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
  10: 0x7765b3db - std::panicking::try::do_call::hc453b0f24ea28e2d
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
test net::udp::tests::test_read_with_timeout ... ok
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1210
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
  11: 0x776b419f - __rust_maybe_catch_panic
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
  12: 0x7766417ftest net::udp::tests::ttl ... ok
 - <F as alloc::boxed::FnBox<A>>::call_box::hc1ea8b30e2bd2527
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/thread/mod.rs:287
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:595
  13: 0x776a6abb - std::sys::imp::thread::Thread::new::thread_start::h177a2a20f0a67315
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:605
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys_common/thread.rs:21
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/thread.rs:84
  14: 0x773a98bf - <unknown>
test net::udp::tests::timeouts ... FAILED
test net::udp::tests::udp_clone_two_read ... ok
test net::udp::tests::udp_clone_two_write ... ok
[..]
test sys::imp::ext::net::test::test_unix_datagram_recv ... ok
test sys::imp::ext::net::test::test_unnamed_unix_datagram ... ok
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `Some(Duration { secs: 15410, nanos: 0 })`, right: `Some(Duration { secs: 0, nanos: 15410000 })`)', src/libstd/sys/unix/ext/net.rs:956
stack backtrace:
   1: 0x7760a8d3 - std::sys::imp::backtrace::tracing::imp::write::h6a9c57665d54ffb2
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2: 0x77657daf - std::panicking::default_hook::{{closure}}::hafb54aec2b339d2d
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:247
   3: 0x77637feb - std::panicking::rust_panic_with_hook::h95213085ace59c69
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:263
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:451
   4: 0x7763792b - std::panicking::begin_panic::hcbad7f9d34dc4a4f
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:413
   5: 0x776377d3 - std::panicking::begin_panic_fmt::h29140d07f42a68b3
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:397
   6: 0x77610523 - std::sys::imp::ext::net::test::timeouts::ha74f838f1f72b4d0
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/ext/net.rs:956
   7: 0x7766aa77 - <F as test::FnBox<T>>::call_box::h1e8b0f3e8d4f40ca
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1265
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:141
   8: 0x7765b1fb - std::panicking::try::do_call::h1a9e31a8c5a5a291
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1211
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
   9: 0x776b419f - __rust_maybe_catch_panic
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
  10: 0x7765b3db - std::panicking::try::do_call::hc453b0f24ea28e2d
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libtest/lib.rs:1210
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:295
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:356
  11: 0x776b419f - __rust_maybe_catch_panic
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libpanic_unwind/lib.rs:97
  12: 0x7766417f - <F as alloc::boxed::FnBox<A>>::call_box::hc1ea8b30e2bd2527
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panicking.rs:332
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/panic.rs:351
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/thread/mod.rs:287
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:595
  13: 0x776a6abb - std::sys::imp::thread::Thread::new::thread_start::h177a2a20f0a67315
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/liballoc/boxed.rs:605
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys_common/thread.rs:21
                at /«BUILDDIR»/rustc-1.14.0+dfsg1/src/libstd/sys/unix/thread.rs:84
  14: 0x773a98bf - <unknown>
test sys::imp::ext::net::test::timeouts ... FAILED
test sys::imp::ext::net::test::try_clone ... ok
[..]
failures:
    net::tcp::tests::timeouts
    net::udp::tests::timeouts
    sys::imp::ext::net::test::timeouts

test result: FAILED. 772 passed; 3 failed; 0 ignored; 0 measured

/«BUILDDIR»/rustc-1.14.0+dfsg1/mk/tests.mk:423: recipe for target 'tmp/check-stage2-T-mips-unknown-linux-gnu-H-mips-unknown-linux-gnu-std.ok' failed
make[2]: *** [tmp/check-stage2-T-mips-unknown-linux-gnu-H-mips-unknown-linux-gnu-std.ok] Error 101
[..]
~~~~

**Comment by xen0n** [comment]
Seems an ABI mismatch. However I moved (pun semi-intended) recently and my MIPS64 box isn't currently with me so I can't investigate any further at this time.

**Comment by Enselic** [comment]
Triage: Let's close this as obsolete as this issue is now very old and nothing has happened in several years, and it is unlikely something will ever happen.
