### ISSUE TITLE
ICE: librustc_trans/mir/operand.rs:83: not immediate: […]

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#39098]
The following error occurs when compiling the [x86 crate](https://github.com/gz/rust-x86) on the latest nightly (ff591b6dc 2017-01-15):

```
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/mir/operand.rs:83: not immediate: OperandRef(Ref((%"shared::segmentation::SegmentSelector"*:  %_4 = alloca %"shared::segmentation::SegmentSelector")) @ shared::segmentation::SegmentSelector)
```

Backtrace:

```
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423
stack backtrace:
   1:     0x7fe16bb306bc - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fe16bb3eafe - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7fe16bb3e6a3 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7fe16bb3ef9b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7fe16412ca37 - std::panicking::begin_panic::he43dc5d9a599d346
   6:     0x7fe164142039 - rustc_errors::Handler::bug::h7088c6afc4a008fb
   7:     0x7fe168e5d92a - rustc::session::opt_span_bug_fmt::{{closure}}::hfd034971cdf18ea9
   8:     0x7fe168e5d3e5 - rustc::session::opt_span_bug_fmt::hc2cac313cb6d0020
   9:     0x7fe168e5d042 - rustc::session::bug_fmt::he01375c3004c5cfe
  10:     0x7fe16b25d01c - rustc_trans::mir::rvalue::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_rvalue::h7dc15384ecc85210
  11:     0x7fe16b248b8f - rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_block::h31596f784d651219
  12:     0x7fe16b246448 - rustc_trans::mir::trans_mir::h7e5fc59940d6977e
  13:     0x7fe16b26798b - rustc_trans::trans_item::TransItem::define::h929f421e720c71df
  14:     0x7fe16b1e8166 - rustc_trans::base::trans_crate::h496d157cb52a4b02
  15:     0x7fe16bef80b0 - rustc_driver::driver::phase_4_translate_to_llvm::h106eb073675c3bee
  16:     0x7fe16bec9e22 - rustc_driver::driver::compile_input::{{closure}}::heec508e3b0737586
  17:     0x7fe16beeb541 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::haa13372f770e9055
  18:     0x7fe16be49319 - rustc::ty::context::TyCtxt::create_and_enter::h6acd1d75709e85e8
  19:     0x7fe16bec7dd0 - rustc_driver::driver::compile_input::h44853ffed84a12cb
  20:     0x7fe16bf0d034 - rustc_driver::run_compiler::hdc4bb0fcf7d0917a
  21:     0x7fe16be11c5b - std::panicking::try::do_call::h84a15e0d2b943318
  22:     0x7fe16bb47dda - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  23:     0x7fe16be3b9a2 - <F as alloc::boxed::FnBox<A>>::call_box::h61c78220cad685ea
  24:     0x7fe16bb3d954 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  25:     0x7fe1638d76b9 - start_thread
  26:     0x7fe16b7f482c - clone
  27:                0x0 - <unknown>
```

**Comment by nagisa** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/39083

**Comment by phil-opp** [comment]
@nagisa thanks!

**Comment by ashleygwilliams** [comment]
@phil-opp just hit this, @steveklabnik just said "oh look @phil-opp filed a bug five hours ago", ha!
