### ISSUE TITLE
configure spews python error detecting LLDB

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39274]
```
brian@ip-10-145-43-250:~/dev/rust⟫ ./configure
configure: looking for configure programs
configure: found program 'cmp'
configure: found program 'mkdir'
configure: found program 'printf'
configure: found program 'cut'
configure: found program 'head'
configure: found program 'grep'
configure: found program 'xargs'
configure: found program 'cp'
configure: found program 'find'
configure: found program 'uname'
configure: found program 'date'
configure: found program 'tr'
configure: found program 'sed'
configure: found program 'file'
configure: found program 'make'
configure: inspecting environment
configure: recreating config.tmp
configure:
configure: processing ./configure args
configure:
configure: CFG_LOCALSTATEDIR    := /var/lib
configure: CFG_SYSCONFDIR       := /etc
configure: CFG_DATADIR          := /share
configure: CFG_INFODIR          := /share/info
configure: CFG_LLVM_ROOT        :=
configure: CFG_PYTHON           :=
configure: CFG_JEMALLOC_ROOT    :=
configure: CFG_BUILD            := x86_64-unknown-linux-gnu
configure: CFG_ANDROID_CROSS_PATH :=
configure: CFG_I686_LINUX_ANDROID_NDK :=
configure: CFG_ARM_LINUX_ANDROIDEABI_NDK :=
configure: CFG_ARMV7_LINUX_ANDROIDEABI_NDK :=
configure: CFG_AARCH64_LINUX_ANDROID_NDK :=
configure: CFG_NACL_CROSS_PATH  :=
configure: CFG_MUSL_ROOT        := /usr/local
configure: CFG_MUSL_ROOT_X86_64 :=
configure: CFG_MUSL_ROOT_I686   :=
configure: CFG_MUSL_ROOT_ARM    :=
configure: CFG_MUSL_ROOT_ARMHF  :=
configure: CFG_MUSL_ROOT_ARMV7  :=
configure: CFG_EXTRA_FILENAME   :=
configure: CFG_RELEASE_CHANNEL  := dev
configure: CFG_DEFAULT_LINKER   := cc
configure: CFG_DEFAULT_AR       := ar
configure: CFG_LIBDIR           := /usr/local/lib
configure:
configure: validating ./configure args
configure:
configure:
configure: looking for build programs
configure:
configure: CFG_CURL             := /usr/bin/curl (7.47.0)
configure: CFG_PYTHON           := /usr/bin/python2.7
configure: CFG_GIT              := /usr/bin/git (2.7.4)
configure: CFG_MD5              :=
configure: CFG_MD5SUM           := /usr/bin/md5sum (8.25)
configure: CFG_HASH_COMMAND     := /usr/bin/md5sum | cut -c 1-8
configure: CFG_CLANG            := /mnt2/dev/emsdk_portable/clang/fast ...
configure: CFG_CCACHE           :=
configure: CFG_GCC              := /usr/bin/gcc (5.4.0-6ubuntu1)
configure: CFG_LD               := /usr/bin/ld (2.26.1)
configure: CFG_VALGRIND         :=
configure: CFG_PERF             :=
configure: CFG_ISCC             :=
configure: CFG_ANTLR4           := /usr/bin/antlr4
configure: CFG_GRUN             := /usr/bin/grun
configure: CFG_FLEX             := /usr/bin/flex (2.6.0)
configure: CFG_BISON            := /usr/bin/bison (3.0.4)
configure: CFG_GDB              := /usr/bin/gdb (7.11.1-0ubuntu1)
configure: CFG_LLDB             := /usr/bin/lldb (3.8.0)
configure: CFG_CMAKE            := /usr/bin/cmake (3.5.1)
configure: CFG_ANTLR4_JAR       := "" ""
configure: CFG_JAVAC            := /usr/bin/javac
configure: CFG_DISABLE_VALGRIND_RPASS := 1
configure: CFG_LLDB_VERSION     := lldb version 3.8.0 ( revision )
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/lldb/__init__.py", line 123, in <module>
    import six
ImportError: No module named six
configure: CFG_LLDB_PYTHON_DIR  := LLDB_PYTHON_DIRECTORY_NOT_FOUND
configure: CFG_LLDB_PYTHON      := /usr/bin/python2.7
configure:
configure: looking for target specific programs
configure:
configure: CFG_ADB              :=
configure: CFG_CC               := gcc
configure: CFG_STDCPP_NAME      := stdc++
configure:
configure: configuring submodules
configure:
configure:
configure: looking at LLVM
configure:
configure: not configuring LLVM, rustbuild in use
configure: CFG_CMAKE_GENERATOR  := Unix Makefiles
configure: configuring LLVM for x86_64-unknown-linux-gnu
configure:
configure: writing configuration
configure:
configure: CFG_SRC_DIR          := /home/brian/dev/rust/
configure: CFG_SRC_DIR_RELATIVE := ./
configure: CFG_BUILD_DIR        := /home/brian/dev/rust/
configure: CFG_OSTYPE           := unknown-linux-gnu
configure: CFG_CPUTYPE          := x86_64
configure: CFG_CONFIGURE_ARGS   :=
configure: CFG_PREFIX           := /usr/local
configure: CFG_HOST             := x86_64-unknown-linux-gnu
configure: CFG_TARGET           := x86_64-unknown-linux-gnu
configure: CFG_LIBDIR_RELATIVE  := lib
configure: CFG_DISABLE_MANAGE_SUBMODULES :=
configure: CFG_AARCH64_LINUX_ANDROID_NDK :=
configure: CFG_ARM_LINUX_ANDROIDEABI_NDK :=
configure: CFG_ARMV7_LINUX_ANDROIDEABI_NDK :=
configure: CFG_I686_LINUX_ANDROID_NDK :=
configure: CFG_NACL_CROSS_PATH  :=
configure: CFG_MANDIR           := /usr/local/share/man
configure: CFG_DOCDIR           := /usr/local/share/doc/rust
configure: CFG_USING_LIBCPP     := 0
configure: CFG_LLVM_SRC_DIR     := /home/brian/dev/rust/src/llvm/
configure: CFG_LLVM_BUILD_DIR_x86_64_unknown_linux_gnu :=
configure: CFG_LLVM_INST_DIR_x86_64_unknown_linux_gnu :=
configure:
configure: leaving ./Makefile unchanged
configure: mv -f config.tmp config.mk
configure:
configure: configured in release mode. for development consider --enable-debug
configure:
configure: NOTE you have now configured rust to use a rewritten build system
configure:      called rustbuild, and as a result this may have bugs that
configure:      you did not see before. If you experience any issues you can
configure:      go back to the old build system with --disable-rustbuild and
configure:      please feel free to report any bugs!
configure:
configure: run `python ./x.py --help`
configure:
brian@ip-10-145-43-250:~/dev/rust⟫
```

Here's what's generating the error:

```
brian@ip-10-145-43-250:~/dev/rust⟫ lldb -P
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/lldb/__init__.py", line 123, in <module>
    import six
ImportError: No module named six
/usr/lib/x86_64-linux-gnu/python2.7/site-packages
```

```
brian@ip-10-145-43-250:~/dev/rust⟫ rustc -Vv
rustc 1.16.0-nightly (4ce7accaa 2017-01-17)
binary: rustc
commit-hash: 4ce7accaa7e64af918e5e8b3fee65096132350f6
commit-date: 2017-01-17
host: x86_64-unknown-linux-gnu
release: 1.16.0-nightly
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/rust⟫ git log -1
commit fe597dc9a9f325de9b2b11d69e190e1c22c4e7dc
```
```

**Comment by michaelwoerister** [comment]
LLDB can only cope with the pre-installed python on OSX. This looks like the same error but I'm don't think I've seen it on Linux before.

**Comment by brson** [comment]
This error went away after running `easy_install six`.

**Comment by Mark-Simulacrum** [comment]
I feel like this is sort of not our problem. Python dependencies either exist or don't, and this is from lldb-internal python, so I'm going to close.
