### ISSUE TITLE
unexpected panic when compiling imap

### ISSUE THREAD

**Issue by busarovalex** [rust-lang/rust#39451]
I was trying to compile an example from the imap crate:
[example](https://github.com/mattnenterprise/rust-imap/blob/master/examples/basic.rs)
when the error occured:  `error: internal compiler error: unexpected panic`

I tried this code:
```
extern crate imap;
extern crate openssl;

use openssl::ssl::{SslContext, SslMethod};
use imap::client::Client;

fn main() {
    let mut imap_socket = Client::secure_connect(
        ("imap.gmail.com", 993), 
        SslContext::new(SslMethod::Sslv23).unwrap()
        )
    .unwrap();

}
```

## Meta
`rustc --version --verbose`:
rustc 1.16.0-nightly (df8debf6d 2017-01-25)
binary: rustc
commit-hash: df8debf6d9afc431adbbd8311dcaf2b70eb9762e
commit-date: 2017-01-25
host: x86_64-unknown-linux-gnu
release: 1.16.0-nightly
LLVM version: 3.9

Backtrace:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x7fefee63b96c - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fefee649e6e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7fefee649a13 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7fefee64a30b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7fefee64a1a4 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7fefee64a0c9 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7fefee64a057 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7fefee68739d - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7fefee6872d4 - core::panicking::panic::h22ba9383231afe8b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x7fefec30a526 - rustc_metadata::creader::CrateLoader::resolve_crate::he89f9a9423254baa
  11:     0x7fefec31163f - <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_item::h3bcaeb0147f0373b
  12:     0x7fefebb32660 - rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::build_reduced_graph_for_item::hdde3d314cfc12862
  13:     0x7fefebb3942f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h220e5c529f36a7a1
  14:     0x7fefebb3992f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h220e5c529f36a7a1
  15:     0x7fefebb2d36f - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::hf2f69d86db69f9ff
  16:     0x7fefe72cd992 - syntax::ext::expand::MacroExpander::collect_invocations::hb7286b5215f6cabe
  17:     0x7fefe72cb5d7 - syntax::ext::expand::MacroExpander::expand::he64090ad698e4ac4
  18:     0x7fefe72cb095 - syntax::ext::expand::MacroExpander::expand_crate::h9effb4e2a488a85d
  19:     0x7fefee9db1ec - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h3ddcf02b571a1c51
  20:     0x7fefee9d2905 - rustc_driver::driver::phase_2_configure_and_expand::hd0c4535cf8df7dea
  21:     0x7fefee9c8dee - rustc_driver::driver::compile_input::h44853ffed84a12cb
  22:     0x7fefeea12554 - rustc_driver::run_compiler::hdc4bb0fcf7d0917a
  23:     0x7fefee91ec2b - std::panicking::try::do_call::h84a15e0d2b943318
  24:     0x7fefee65314a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  25:     0x7fefee946e62 - <F as alloc::boxed::FnBox<A>>::call_box::h61c78220cad685ea
  26:     0x7fefee648cc4 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  27:     0x7fefe6404183 - start_thread
  28:     0x7fefee2f637c - clone
  29:                0x0 - <unknown>

```

**Comment by est31** [comment]
Can't reproduce on linux with neither stable, beta, or the mentioned nightly.

**Comment by steveklabnik** [comment]
I cannot either. @busarovalex if this is still happening, please let us know!
