### ISSUE TITLE
15.0 test is failing on Debian x86_64

### ISSUE THREAD

**Issue by sylvestre** [rust-lang/rust#39681]
```
running: "/home/sylvestre/dev/debian/rustc.git/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/tidy" "/home/sylvestre/dev/debian/rustc.git/src"
/home/sylvestre/dev/debian/rustc.git/src/etc/mklldeps.py:63: TODO is deprecated; use FIXME
/home/sylvestre/dev/debian/rustc.git/src/librustc_llvm/build.rs:162: TODO is deprecated; use FIXME
/home/sylvestre/dev/debian/rustc.git/src/librustc_trans/back/link.rs:898: line longer than 100 chars
/home/sylvestre/dev/debian/rustc.git/src/test/run-pass/allocator-default.rs:13: line longer than 100 chars
/home/sylvestre/dev/debian/rustc.git/src/test/compile-fail/allocator-rust-dylib-is-jemalloc.rs:32: line longer than 100 chars
/home/sylvestre/dev/debian/rustc.git/src/test/compile-fail/allocator-rust-dylib-is-jemalloc.rs:34: line longer than 100 chars
thread 'main' panicked at 'some tidy checks failed', src/tools/tidy/src/main.rs:55
stack backtrace:
   1:     0x7f699d0bf84a - std::sys::imp::backtrace::tracing::imp::write::hc59a86242bcbdf1a
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f699d0d0c9f - std::panicking::default_hook::{{closure}}::hb5e7e626cf978ea2
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/panicking.rs:349
   3:     0x7f699d0cd85c - std::panicking::default_hook::h807f6f73fec53735
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/panicking.rs:365
   4:     0x7f699d0cdf17 - std::panicking::rust_panic_with_hook::h5daa03fb8d89fe83
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/panicking.rs:553
   5:     0x5600f389a074 - std::panicking::begin_panic::hae351bd062040dd8
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/panicking.rs:515
   6:     0x5600f38a1c90 - tidy::main::hf1d54b4860c1ca8d
                        at /home/sylvestre/dev/debian/rustc.git/src/tools/tidy/src/main.rs:55
   7:     0x7f699d0d6f9a - __rust_maybe_catch_panic
                        at /home/sylvestre/dev/debian/rustc.git/src/libpanic_unwind/lib.rs:98
   8:     0x7f699d0ceb26 - std::rt::lang_start::h53d4d12ac8f99791
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/panicking.rs:434
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/panic.rs:351
                        at /home/sylvestre/dev/debian/rustc.git/src/libstd/rt.rs:57
   9:     0x7f699caba2b0 - __libc_start_main
  10:     0x5600f3898da9 - _start
  11:                0x0 - <unknown>


command did not execute successfully: "/home/sylvestre/dev/debian/rustc.git/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/tidy" "/home/sylvestre/dev/debian/rustc.git/src"
expected success, got: exit code: 101


Makefile:53 : la recette pour la cible « check » a échouée
```

**Comment by est31** [comment]
cc @brson

**Comment by alexcrichton** [comment]
The file `src/etc/mklldeps.py` on the [stable branch](https://github.com/rust-lang/rust/blob/stable/src/etc/mklldeps.py#L63) doesn't have TODO on line 63, odd!

@sylvestre are these local patches applied by debian?

**Comment by sylvestre** [comment]
Really sorry about that :( It is indeed the case in this patch: https://anonscm.debian.org/cgit/pkg-rust/rust.git/tree/debian/patches/d-dynamic-link-llvm_1.15.patch
