### ISSUE TITLE
ICE building protobuf-json-0.1.0, Rust 1.16 beta

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39823]
https://github.com/mrjones/rust-protobuf-json 5dbb6be3e4fed92ede0c5ddc9e5a0560ef27e0f8

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.16.0-beta.1 (5276ba72e 2017-01-31)
binary: rustc
commit-hash: 5276ba72e8fe13597200254447fce9cb3783c583
commit-date: 2017-01-31
host: x86_64-unknown-linux-gnu
release: 1.16.0-beta.1
LLVM version: 3.9
```

```
101 brian@ip-10-145-43-250:~/dev/rust-protobuf-json⟫ cargo +beta test
   Compiling protobuf v1.2.1
   Compiling serde v0.9.7
   Compiling dtoa v0.4.1
   Compiling itoa v0.3.1
   Compiling num-traits v0.1.36
   Compiling serde_json v0.9.6
   Compiling protobuf-json v0.2.0 (file:///mnt2/dev/rust-protobuf-json)
error: internal compiler error: /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_trans/collector.rs:702: Cannot create local trans-item for DefId { krate: CrateNum(13), node: DefIndex(2720) => serde_json/d2f2c5cb81f8962426114e6f1be74067::value[0]::Value[0]::Bool[0] }

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_errors/lib.rs:416
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `protobuf-json`.
Build failed, waiting for other jobs to finish...
warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1597:29
     |
1597 |                 fields.push(::protobuf::reflect::accessor::make_repeated_f64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1601:29
     |
1601 |                 fields.push(::protobuf::reflect::accessor::make_repeated_f64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1605:29
     |
1605 |                 fields.push(::protobuf::reflect::accessor::make_repeated_i32_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1609:29
     |
1609 |                 fields.push(::protobuf::reflect::accessor::make_repeated_i64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1613:29
     |
1613 |                 fields.push(::protobuf::reflect::accessor::make_repeated_u32_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1617:29
     |
1617 |                 fields.push(::protobuf::reflect::accessor::make_repeated_u64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1621:29
     |
1621 |                 fields.push(::protobuf::reflect::accessor::make_repeated_i32_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1625:29
     |
1625 |                 fields.push(::protobuf::reflect::accessor::make_repeated_i64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1629:29
     |
1629 |                 fields.push(::protobuf::reflect::accessor::make_repeated_u32_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1633:29
     |
1633 |                 fields.push(::protobuf::reflect::accessor::make_repeated_u64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1637:29
     |
1637 |                 fields.push(::protobuf::reflect::accessor::make_repeated_i32_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1641:29
     |
1641 |                 fields.push(::protobuf::reflect::accessor::make_repeated_i64_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1645:29
     |
1645 |                 fields.push(::protobuf::reflect::accessor::make_repeated_bool_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1649:29
     |
1649 |                 fields.push(::protobuf::reflect::accessor::make_repeated_string_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1653:29
     |
1653 |                 fields.push(::protobuf::reflect::accessor::make_repeated_bytes_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1657:29
     |
1657 |                 fields.push(::protobuf::reflect::accessor::make_repeated_message_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item, #[warn(deprecated)] on by default
    --> src/tests/test_proto.rs:1661:29
     |
1661 |                 fields.push(::protobuf::reflect::accessor::make_repeated_enum_accessor(
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_trans/collector.rs:702: Cannot create local trans-item for DefId { krate: CrateNum(13), node: DefIndex(2720) => serde_json/d2f2c5cb81f8962426114e6f1be74067::value[0]::Value[0]::Bool[0] }

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_errors/lib.rs:416
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: build failed
```

Not on 1.15.

cc @mrjones

**Comment by arielb1** [comment]
Fun note: another bug fixed on my shimmir branch. Not that I really want to merge it to 1.16/1.17.

**Comment by arielb1** [comment]
Minified:
```Rust
fn main() {
    &Some as &Fn(u32) -> _;
}
```

**Comment by nikomatsakis** [comment]
triage: P-high
