### ISSUE TITLE
error: internal compiler error: unexpected panic, with `fold.rs` `fold_macro`

### ISSUE THREAD

**Issue by qorost** [rust-lang/rust#39982]
<short summary of the bug>
I tried to write a plugin to annotate my code. So I overrides `Folder` to write my plugin. The plugin succeeded in compiling, but when I imported the plugin to my project, it failed with  

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'fold_mac disabled by default', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:180
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

## Meta

`rustc --version --verbose`:
```
rustc 1.17.0-nightly (ea7a6486a 2017-02-04)
binary: rustc
commit-hash: ea7a6486a26af085862cd7a5596bb69e83d85e12
commit-date: 2017-02-04
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9
```
Backtrace:
```
thread 'rustc' panicked at 'fold_mac disabled by default', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:180
stack backtrace:
   1:     0x7f4b0054746c - std::sys::imp::backtrace::tracing::imp::write::hf7294f5e24536b4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f4b0055591e - std::panicking::default_hook::{{closure}}::h9a07d0b00c43fbee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f4b005554c3 - std::panicking::default_hook::hf25feff2d08bf39b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7f4b00555dbb - std::panicking::rust_panic_with_hook::h4cb8c6fbb8386ccf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f4af553a183 - std::panicking::begin_panic::h942f31d05ff9d837
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f4af559246d - syntax::fold::Folder::fold_mac::hefcb7e19f28b1461
                        at /home/huang/Desktop/Rust/sfi/fine-unsafe/fine-unsafe/<panic macros>:3
   7:     0x7f4af5589d27 - syntax::fold::noop_fold_stmt_kind::{{closure}}::h2bf26da7bd042844
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:1321
   8:     0x7f4af551c58a - <syntax::ptr::P<T>>::map::h2df2a20d3ed8cbfd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ptr.rs:86
   9:     0x7f4af558988f - syntax::fold::noop_fold_stmt_kind::h3611ee7245deccb6
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:1320
  10:     0x7f4af5583350 - syntax::fold::noop_fold_stmt::h370d66b83338fa0b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:1305
  11:     0x7f4af5592ad4 - syntax::fold::Folder::fold_stmt::h2ef5c614340db0c3
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:100
  12:     0x7f4af558384e - syntax::fold::noop_fold_block::{{closure}}::{{closure}}::ha98c25f04360420d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:854
  13:     0x7f4af55a96f1 - <collections::vec::Vec<T> as syntax::util::move_map::MoveMap<T>>::move_flat_map::h8ef2372e321353ce
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/util/move_map.rs:40
  14:     0x7f4af55836dc - syntax::fold::noop_fold_block::{{closure}}::hedb708829b40ffe5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:854
  15:     0x7f4af551c861 - <syntax::ptr::P<T>>::map::h33479a26b5464bee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ptr.rs:86
  16:     0x7f4af5583573 - syntax::fold::noop_fold_block::h26da07b7cfc9d89a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:852
  17:     0x7f4af559004c - syntax::fold::Folder::fold_block::hadb106a75830ef3a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:96
  18:     0x7f4af558741e - syntax::fold::noop_fold_item_kind::hc5ba0bc792ec825b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:875
  19:     0x7f4af5590bea - syntax::fold::Folder::fold_item_kind::h7fe0e8b663620147
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:80
  20:     0x7f4af558c1c8 - syntax::fold::noop_fold_item_simple::h5c21c96c18447284
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:1027
  21:     0x7f4af559134a - syntax::fold::Folder::fold_item_simple::he51a2fd5863a591d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:72
  22:     0x7f4af5582dc9 - syntax::fold::noop_fold_item::{{closure}}::h38fdefde631a2eca
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:1016
  23:     0x7f4af551e284 - <syntax::ptr::P<T>>::map::hd8485117d8c4a23a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ptr.rs:86
  24:     0x7f4af5582c91 - syntax::fold::noop_fold_item::heeb63a42787ce36a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:1016
  25:     0x7f4af559293b - syntax::fold::Folder::fold_item::h3a1fc04ebed254fe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/fold.rs:68
  26:     0x7f4af55c404e - myplugin::plugin_registrar::{{closure}}::hcc2818d567d33c99
                        at /home/huang/Desktop/Rust/sfi/fine-unsafe/fine-unsafe/myplugin/src/lib.rs:165
  27:     0x7f4af5564431 - <F as syntax::ext::base::MultiItemModifier>::expand::h073db6609c74d7e4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ext/base.rs:135
  28:     0x7f4af91d263a - syntax::ext::expand::MacroExpander::expand_invoc::h8c740b40c25e30d1
  29:     0x7f4af91cfd4d - syntax::ext::expand::MacroExpander::expand::h32c0cdf50a69c606
  30:     0x7f4af91cf285 - syntax::ext::expand::MacroExpander::expand_crate::h1c8ecd75edc55074
  31:     0x7f4b008e231c - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h03b336c71cb87528
  32:     0x7f4b008d97f5 - rustc_driver::driver::phase_2_configure_and_expand::h026284537f8f8432
  33:     0x7f4b008d240a - rustc_driver::driver::compile_input::hab977ae496b3a6f1
  34:     0x7f4b0091e594 - rustc_driver::run_compiler::h81290683db66a63c
  35:     0x7f4b0082ae7b - std::panicking::try::do_call::h00942d7a5d04424f
  36:     0x7f4b0055ebfa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  37:     0x7f4b008531c2 - <F as alloc::boxed::FnBox<A>>::call_box::hd87f7ab2fccbd670
  38:     0x7f4b00554774 - std::sys::imp::thread::Thread::new::thread_start::hc16926852e47c008
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:623
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  39:     0x7f4af830a6b9 - start_thread
  40:     0x7f4b0020a82c - clone
  41:                0x0 - <unknown>
```

**Comment by qorost** [comment]
to fix this,

In the plugin source code, when implement the `Folder` trait, add 
```
    fn fold_mac(&mut self, mac: Mac) -> Mac {
        mac
    }
```
