### ISSUE TITLE
nightly-arm-unknown-linux-gnueabihf: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by jedisct1** [rust-lang/rust#40639]
Recent nightly builds seem to be broken on arm.

For example when trying to compile edgedns, cargo always panics with:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
stack backtrace:
   0: 0x7fb226db - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hf9ed9ccfd9f14c2b
                       at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: 0x7fb1efa3 - std::sys_common::backtrace::_print::hd8a1b72dcf3955ef
                       at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: 0x7fb29bf7 - std::panicking::default_hook::{{closure}}::h5ff605bba7612658
                       at /checkout/src/libstd/sys_common/backtrace.rs:60
                       at /checkout/src/libstd/panicking.rs:355
   3: 0x7fb29663 - std::panicking::default_hook::h9bc4f6dfee57d6bd
                       at /checkout/src/libstd/panicking.rs:371
   4: 0x7fb2a0ff - std::panicking::rust_panic_with_hook::hdc01585dc2bf7122
                       at /checkout/src/libstd/panicking.rs:549
   5: 0x7fb29fb3 - std::panicking::begin_panic::hf84f4975d9f9b642
                       at /checkout/src/libstd/panicking.rs:511
   6: 0x7fb29ef3 - std::panicking::begin_panic_fmt::hcc3f360b2ba80419
                       at /checkout/src/libstd/panicking.rs:495
   7: 0x7fb29e8f - rust_begin_unwind
                       at /checkout/src/libstd/panicking.rs:471
   8: 0x7fb59d7f - core::panicking::panic_fmt::h795d9a9608ddc2bb
                       at /checkout/src/libcore/panicking.rs:69
   9: 0x7fb59ccb - core::panicking::panic::hcab3e0dfa81beee9
                       at /checkout/src/libcore/panicking.rs:49
  10: 0x7f83d0db - cargo::version::haea7e89a3b191e3c
                       at /checkout/src/libcore/macros.rs:21
                       at /checkout/cargo/src/cargo/lib.rs:263
  11: 0x7f7d9b0b - cargo::ops::registry::http_handle::h3e076e6b4e3144ec
                       at /checkout/cargo/src/cargo/ops/registry.rs:227
  12: 0x7f7ffa6f - <cargo::sources::registry::remote::RemoteRegistry<'cfg> as cargo::sources::registry::RegistryData>::update_index::h282902cfa6380402
                       at /checkout/cargo/src/cargo/sources/registry/remote.rs:63
  13: 0x7f80439b - cargo::sources::registry::RegistrySource::do_update::h07f4b56389efd3cc
                       at /checkout/cargo/src/cargo/sources/registry/mod.rs:309
  14: 0x7f80451f - <cargo::sources::registry::RegistrySource<'cfg> as cargo::core::registry::Registry>::query::h2abb0b233f8e6482
                       at /checkout/cargo/src/cargo/sources/registry/mod.rs:327
  15: 0x7f753117 - <cargo::core::registry::PackageRegistry<'cfg> as cargo::core::registry::Registry>::query::hadbdbf4d0ac9bf3b
                       at /checkout/cargo/src/cargo/core/registry.rs:346
  16: 0x7f70a1df - <&'a mut I as core::iter::iterator::Iterator>::next::h332f2d5f927afe91
                       at /checkout/cargo/src/cargo/core/resolver/mod.rs:859
                       at /checkout/cargo/src/cargo/core/resolver/mod.rs:832
                       at /checkout/src/libcore/ops.rs:2654
                       at /checkout/src/libcore/option.rs:383
                       at /checkout/src/libcore/iter/mod.rs:999
                       at /checkout/src/libcore/result.rs:1087
                       at /checkout/src/libcore/iter/iterator.rs:2197
  17: 0x7f741cdb - cargo::core::resolver::activate::h1c3cc7b12a94433a
                       at /checkout/src/libcollections/vec.rs:1745
                       at /checkout/src/libcollections/vec.rs:1670
                       at /checkout/src/libcollections/vec.rs:1665
                       at /checkout/src/libcollections/vec.rs:1566
                       at /checkout/src/libcore/result.rs:1104
                       at /checkout/src/libcore/iter/iterator.rs:1221
                       at /checkout/cargo/src/cargo/core/resolver/mod.rs:831
                       at /checkout/cargo/src/cargo/core/resolver/mod.rs:340
  18: 0x7f743343 - cargo::core::resolver::activate_deps_loop::h62b26829fcbf8fc0
                       at /checkout/cargo/src/cargo/core/resolver/mod.rs:457
  19: 0x7f73f423 - cargo::core::resolver::resolve::hf9d29d69f2ae3cba
                       at /checkout/cargo/src/cargo/core/resolver/mod.rs:280
  20: 0x7f7e1743 - cargo::ops::resolve::resolve_with_previous::h5764c025c137350f
                       at /checkout/cargo/src/cargo/ops/resolve.rs:225
  21: 0x7f7e06db - cargo::ops::resolve::resolve_with_registry::hc56cdcff8df388e3
                       at /checkout/cargo/src/cargo/ops/resolve.rs:88
  22: 0x7f7df143 - cargo::ops::resolve::resolve_ws_precisely::h263da6db31cfdb9c
                       at /checkout/cargo/src/cargo/ops/resolve.rs:43
  23: 0x7f761acf - cargo::ops::cargo_compile::compile_ws::h4c2bd5ad47cac06f
                       at /checkout/cargo/src/cargo/ops/cargo_compile.rs:177
  24: 0x7f7616ab - cargo::ops::cargo_compile::compile_with_exec::h991af086f5b71658
                       at /checkout/cargo/src/cargo/ops/cargo_compile.rs:153
  25: 0x7f761543 - cargo::ops::cargo_compile::compile::ha766b618a61ce249
                       at /checkout/cargo/src/cargo/ops/cargo_compile.rs:141
  26: 0x7f613ff7 - cargo::try_execute_builtin_command::h117b1963a08549be
                       at /checkout/cargo/src/bin/build.rs:112
                       at /checkout/cargo/src/cargo/lib.rs:128
                       at /checkout/cargo/src/bin/cargo.rs:259
  27: 0x7f60c9fb - cargo::execute::h38e6c27236d82ec3
                       at /checkout/cargo/src/bin/cargo.rs:223
  28: 0x7f603ecf - cargo::call_main_without_stdin::hde98a839d8ab6c0f
                       at /checkout/cargo/src/cargo/lib.rs:128
  29: 0x7f60b8fb - cargo::main::h2cff0d0817bf7ef6
                       at /checkout/cargo/src/bin/cargo.rs:91
                       at /checkout/cargo/src/bin/cargo.rs:84
  30: 0x7fb29dcb - std::panicking::try::do_call::h689a21caeeef92aa
                       at /checkout/src/libstd/panicking.rs:454
  31: 0x7fb30e8f - __rust_maybe_catch_panic
                       at /checkout/src/libpanic_unwind/lib.rs:98
  32: 0x7fb2a7a7 - std::rt::lang_start::hf63d494cb7dd034c
                       at /checkout/src/libstd/panicking.rs:433
                       at /checkout/src/libstd/panic.rs:361
                       at /checkout/src/libstd/rt.rs:57
  33: 0xb6de54a9 - __libc_start_main
```

Tested with `rustc 1.17.0-nightly (a559452b0 2017-03-17)`.

**Comment by Voultapher** [comment]
Same on Ubuntu `16:04 x86-64`, all I need to call to get that problem is `cargo --version`

**Comment by anatol** [comment]
I confirm the issue at Arch Linux. Here is the stacktrace I see

```
$ RUST_BACKTRACE=full cargo install xargo
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
stack backtrace:
   0:     0x556c4239fac3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hf9ed9ccfd9f14c2b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x556c4239bdf4 - std::sys_common::backtrace::_print::hd8a1b72dcf3955ef
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x556c423a76bc - std::panicking::default_hook::{{closure}}::h5ff605bba7612658
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x556c423a7284 - std::panicking::default_hook::h9bc4f6dfee57d6bd
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x556c423a7b0b - std::panicking::rust_panic_with_hook::hdc01585dc2bf7122
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x556c423a79e4 - std::panicking::begin_panic::hf84f4975d9f9b642
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x556c423a7919 - std::panicking::begin_panic_fmt::hcc3f360b2ba80419
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x556c423a78a7 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x556c423d401d - core::panicking::panic_fmt::h795d9a9608ddc2bb
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x556c423d3f54 - core::panicking::panic::hcab3e0dfa81beee9
                               at /checkout/src/libcore/panicking.rs:49
  10:     0x556c420566de - cargo::version::haea7e89a3b191e3c
                               at /checkout/src/libcore/macros.rs:21
                               at /checkout/cargo/src/cargo/lib.rs:263
  11:     0x556c41feb8cf - cargo::ops::registry::http_handle::h3e076e6b4e3144ec
                               at /checkout/cargo/src/cargo/ops/registry.rs:227
  12:     0x556c42014e19 - <cargo::sources::registry::remote::RemoteRegistry<'cfg> as cargo::sources::registry::RegistryData>::update_index::h282902cfa6380402
                               at /checkout/cargo/src/cargo/sources/registry/remote.rs:63
  13:     0x556c4201a6c7 - cargo::sources::registry::RegistrySource::do_update::h07f4b56389efd3cc
                               at /checkout/cargo/src/cargo/sources/registry/mod.rs:309
  14:     0x556c4201a986 - <cargo::sources::registry::RegistrySource<'cfg> as cargo::core::source::Source>::update::h790227a7871fecb4
                               at /checkout/cargo/src/cargo/sources/registry/mod.rs:353
  15:     0x556c41f74ff2 - cargo::ops::cargo_install::install::ha102628dcbc73b48
                               at /checkout/cargo/src/cargo/core/source.rs:64
                               at /checkout/cargo/src/cargo/ops/cargo_install.rs:273
                               at /checkout/cargo/src/cargo/ops/cargo_install.rs:80
  16:     0x556c41e1d96e - cargo::try_execute_builtin_command::h117b1963a08549be
                               at /checkout/cargo/src/bin/install.rs:148
                               at /checkout/cargo/src/cargo/lib.rs:128
                               at /checkout/cargo/src/bin/cargo.rs:259
  17:     0x556c41e09714 - cargo::execute::h38e6c27236d82ec3
                               at /checkout/cargo/src/bin/cargo.rs:223
  18:     0x556c41e00701 - cargo::call_main_without_stdin::hde98a839d8ab6c0f
                               at /checkout/cargo/src/cargo/lib.rs:128
  19:     0x556c41e082e1 - cargo::main::h2cff0d0817bf7ef6
                               at /checkout/cargo/src/bin/cargo.rs:91
                               at /checkout/cargo/src/bin/cargo.rs:84
  20:     0x556c423a7805 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libstd/panicking.rs:454
  21:     0x556c423aeaca - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  22:     0x556c423a82a6 - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  23:     0x7f87aa25f510 - __libc_start_main
  24:     0x556c41defb4c - <unknown>


$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.16.0 (30cf806ef 2017-03-10)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.17.0-nightly (a559452b0 2017-03-17)
```

**Comment by alexcrichton** [comment]
Yes this should be fixed on master, but thanks for the report!
