### ISSUE TITLE
thread 'main' panicked at 'path.metadata() failed with The system cannot find the file specified. (os error 2)', src\bootstrap\clean.rs:76

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#40674]
I'm on MSVC, and running `python x.py clean` this morning, get this error:

```
> python x.py clean
extracting C:\Users\steve\src\rust\build\cache\2017-02-01\rust-std-beta-x86_64-pc-windows-msvc.tar.gz
extracting C:\Users\steve\src\rust\build\cache\2017-02-01\rustc-beta-x86_64-pc-windows-msvc.tar.gz
extracting C:\Users\steve\src\rust\build\cache\407edef22e894266eb562618cba5ca9757051946\cargo-nightly-x86_64-pc-windows-msvc.tar.gz
    Finished dev [unoptimized] target(s) in 0.0 secs
thread 'main' panicked at 'path.metadata() failed with The system cannot find the file specified. (os error 2)', src\bootstrap\clean.rs:76
stack backtrace:
   0:     0x7ff68a8f1548 - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:356
   1:     0x7ff68a8f0a54 - std::panicking::default_hook
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:367
   2:     0x7ff68a8f439d - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:555
   3:     0x7ff68a8f4238 - std::panicking::begin_panic<collections::string::String>
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:517
   4:     0x7ff68a8f4154 - std::panicking::begin_panic_fmt
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:501
   5:     0x7ff68a7669ac - <bootstrap::check::TestKind as core::fmt::Display>::fmt::h14b609f8bfe6d82e
   6:     0x7ff68a766181 - <bootstrap::check::TestKind as core::fmt::Display>::fmt::h14b609f8bfe6d82e
   7:     0x7ff68a766161 - <bootstrap::check::TestKind as core::fmt::Display>::fmt::h14b609f8bfe6d82e
   8:     0x7ff68a765681 - <bootstrap::check::TestKind as core::fmt::Display>::fmt::h14b609f8bfe6d82e
   9:     0x7ff68a7cc128 - bootstrap::Build::build::h21831fd8d2e5b0a8
  10:     0x7ff68a6583fe - EMPTY
  11:     0x7ff68a8f5871 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
  12:     0x7ff68a8f498a - std::rt::lang_start
                        at C:\bot\slave\beta-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
  13:     0x7ff68a6585b9 - main
  14:     0x7ff68a904658 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  15:     0x7ffd39368363 - BaseThreadInitThunk
Build completed unsuccessfully in 0:00:06
```

not sure what's going on here. I vaguely remember someone on IRC mentioning this, but cannot remember who.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this. I suspect this is just Windows, but I think we now handle this case.
