### ISSUE TITLE
Panic over 'None'

### ISSUE THREAD

**Issue by moonheart08** [rust-lang/rust#41038]
```
       Fresh libc v0.2.21
       Fresh rustc-serialize v0.3.23
       Fresh num-traits v0.1.37
       Fresh byteorder v1.0.0
       Fresh lazy_static v0.2.5
       Fresh matches v0.1.4
       Fresh unicode-normalization v0.1.4
       Fresh gcc v0.3.45
       Fresh time v0.1.36
       Fresh num-integer v0.1.33
       Fresh rand v0.3.15
       Fresh num-complex v0.1.36
       Fresh sha1 v0.1.1
       Fresh unicode-bidi v0.2.5
       Fresh num-iter v0.1.33
       Fresh num-bigint v0.1.37
       Fresh idna v0.1.1
       Fresh num-rational v0.1.36
       Fresh url v1.4.0
       Fresh rust-crypto v0.2.36
       Fresh num v0.1.37
       Fresh redis v0.5.4
       Fresh bcrypt v0.1.3
       Fresh nalgebra v0.6.0
       Fresh ncollide_math v0.2.2
       Fresh ncollide_utils v0.2.6
       Fresh ncollide_procedural v0.2.5
       Fresh ncollide_entities v0.4.1
       Fresh ncollide_queries v0.3.2
       Fresh ncollide_pipeline v0.6.1
       Fresh ncollide_transformation v0.2.3
       Fresh ncollide v0.7.2
       Fresh nphysics3d v0.1.2
   Compiling rusemmo v0.1.0 (file:///home/ubuntu/workspace/rusemmo)
     Running `rustc --crate-name rusemmo src/main.rs --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=8b4407e547170639 -C extra-filename=-8b4407e547170639 --out-dir /home/ubuntu/workspace/rusemmo/target/debug/deps -L dependency=/home/ubuntu/workspace/rusemmo/target/debug/deps --extern nphysics3d=/home/ubuntu/workspace/rusemmo/target/debug/deps/libnphysics3d-4df89cbaaf8f2c4a.rmeta --extern bcrypt=/home/ubuntu/workspace/rusemmo/target/debug/deps/libbcrypt-1d6f7263b0ed40ab.rmeta --extern redis=/home/ubuntu/workspace/rusemmo/target/debug/deps/libredis-7bbcbde683b68122.rmeta -L native=/home/ubuntu/workspace/rusemmo/target/debug/build/rust-crypto-1726770e89591a2e/out`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `rusemmo`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rusemmo src/main.rs --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=8b4407e547170639 -C extra-filename=-8b4407e547170639 --out-dir /home/ubuntu/workspace/rusemmo/target/debug/deps -L dependency=/home/ubuntu/workspace/rusemmo/target/debug/deps --extern nphysics3d=/home/ubuntu/workspace/rusemmo/target/debug/deps/libnphysics3d-4df89cbaaf8f2c4a.rmeta --extern bcrypt=/home/ubuntu/workspace/rusemmo/target/debug/deps/libbcrypt-1d6f7263b0ed40ab.rmeta --extern redis=/home/ubuntu/workspace/rusemmo/target/debug/deps/libredis-7bbcbde683b68122.rmeta -L native=/home/ubuntu/workspace/rusemmo/target/debug/build/rust-crypto-1726770e89591a2e/out` (exit code: 101)
```
The code im running is closed source, and this is on the Nightly Build, and as i have no idea which part is causing it to panic like that, i wont reveal info unless asked. From what i can tell, someone forgot to check if a option would be 'None'

Here is a backtrace:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `rusemmo`.

To learn more, run the command again with --verbose.
moonheart08:~/workspace/rusemmo (master) $ export RUST_BACKTRACE=1
moonheart08:~/workspace/rusemmo (master) $ cargo check
   Compiling rusemmo v0.1.0 (file:///home/ubuntu/workspace/rusemmo)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rustc_metadata::creader::CrateLoader::resolve_crate
   1: <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_item
   2: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::build_reduced_graph_for_item
   3: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
   4: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
   5: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion
   6: syntax::ext::expand::MacroExpander::collect_invocations
   7: syntax::ext::expand::MacroExpander::expand
   8: syntax::ext::expand::MacroExpander::expand_crate
   9: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}
  10: rustc_driver::driver::phase_2_configure_and_expand
  11: rustc_driver::driver::compile_input
  12: rustc_driver::run_compiler
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  17: start_thread
  18: clone
```

**Comment by arielb1** [comment]
cc @jseyfried

**Comment by arielb1** [comment]
Which `rustc` version are you using?

**Comment by moonheart08** [comment]
Latest nightly, @arielb1

**Comment by arielb1** [comment]
This is odd. The only nearby Option::unwrap I see is https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/creader.rs#L604, which should never be hit.

@moonheart08 

Can you compile a rustc using `./configure --enable-debug --enable-optimize` and compile your program using it? That would give us a more useful backtrace.

**Comment by moonheart08** [comment]
@arielb1 Certainly, i'll do so as soon as possible and will post the backtrace.

**Comment by kpcyrd** [comment]
I think I ran into the same issue, somebody from irc pointed me here.

This has been caused by (poorly) removing a dependency from my project:
- I built my project with `rustc-serialize` until I didn't need it anymore
- I removed the dependency from Cargo.toml
- I still had `extern crate rustc_serialize` in my code (not sure I did or did not use it in my code)
- cargo removed rustc-serialize from Cargo.lock, but the build failed

I removed `target/` and `Cargo.lock` and built again, which fixed the build until it complained about `extern crate rustc_serialize` (which was my fault).

I hope this helps.

```
   Compiling something v0.1.0 (file:///something/something)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   1:      0x3be2ba97c9c - <unknown>
   2:      0x3be2baa636e - <unknown>
   3:      0x3be2baa5f03 - <unknown>
   4:      0x3be2baa680b - std::panicking::rust_panic_with_hook::h9f3930ca8cee8a65
   5:      0x3be2baa66a4 - <unknown>
   6:      0x3be2baa65c9 - std::panicking::begin_panic_fmt::h6073f869f9b775fa
   7:      0x3be2baa6557 - rust_begin_unwind
   8:      0x3be2bafcfbd - core::panicking::panic_fmt::hc8432e9fe5639d04
   9:      0x3be2bafcef4 - core::panicking::panic::hd491630d7a1ea17f
  10:      0x3be297902a6 - <unknown>
  11:      0x3be297973bf - <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_item::h3d7a10bdafa59007
  12:      0x3be28fb50c0 - <unknown>
  13:      0x3be28fbbe8f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h2eab4919824bc032
  14:      0x3be28fbc38f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h2eab4919824bc032
  15:      0x3be28fafdcf - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::h6a021c2cdf355ad5
  16:      0x3be254ffa32 - <unknown>
  17:      0x3be254fd677 - <unknown>
  18:      0x3be254fd135 - syntax::ext::expand::MacroExpander::expand_crate::h9b5d9e839a2028cc
  19:      0x3be2be4bc0c - <unknown>
  20:      0x3be2be43325 - <unknown>
  21:      0x3be2be3bf62 - rustc_driver::driver::compile_input::h9ff46639bcd36041
  22:      0x3be2be88394 - rustc_driver::run_compiler::hb5d68fffb8e95cee
  23:      0x3be2bd945cb - <unknown>
  24:      0x3be2baaf67a - __rust_maybe_catch_panic
  25:      0x3be2bdbc802 - <unknown>
  26:      0x3be2baa51b4 - <unknown>
  27:      0x3be246342e6 - start_thread
  28:      0x3be2b76554e - clone
  29:                0x0 - <unknown>

error: Could not compile `something`.

To learn more, run the command again with --verbose.
```

**Comment by steveklabnik** [comment]
Triage: I am not sure how to reproduce this.

**Comment by bjorn3** [comment]
This issue has last been hit 5 years ago with no known reproducer. Should this be closed?

**Comment by moonheart08** [comment]
There's almost no chance this issue can still be reproduced, so I'd say yes but will leave it to the team.
