### ISSUE TITLE
Unexpected panic while running cargo check

### ISSUE THREAD

**Issue by Tiwalun** [rust-lang/rust#41046]
I get an unexpected panic while running cargo check on the following code:

```rust
extern crate csv;
extern crate rustc_serialize;

fn main() {
}
```

My cargo.toml contains the following dependencies:

```
[dependencies]
csv = "0.14"
```

If I add the rustc_serialize crate to my cargo.toml, I can succesfully run the command.

If I run cargo run, I get an error message indicating that the crate rustc_serialize is not found.
I would expect the same to happen when I run cargo check.

The following backtrace is printed when running cargo check:

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x7f7e2355940c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f7e235679ae - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f7e23567553 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7f7e23567e4b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f7e23567ce4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f7e23567c09 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7f7e23567b97 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7f7e235a4edd - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7f7e235a4e14 - core::panicking::panic::h7abeb5b818ec354e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x7f7e2122a876 - rustc_metadata::creader::CrateLoader::resolve_crate::h6e72600e2dd6f65b
  11:     0x7f7e2123198f - <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_item::h3593d13570805f47
  12:     0x7f7e20a518b0 - rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::build_reduced_graph_for_item::h3cc2f08d7828c563
  13:     0x7f7e20a5867f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h775ca4c5a23a8667
  14:     0x7f7e20a58b7f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h775ca4c5a23a8667
  15:     0x7f7e20a4c5bf - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::hc836a3e7268abdbf
  16:     0x7f7e1ceea77a - syntax::ext::expand::MacroExpander::collect_invocations::h32417ac98c0c9be1
  17:     0x7f7e1cee9140 - syntax::ext::expand::MacroExpander::expand::h695353fd58aabfd3
  18:     0x7f7e1cee8ba5 - syntax::ext::expand::MacroExpander::expand_crate::h9811866201c8237a
  19:     0x7f7e238f40dc - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h231d639b5d33e30c
  20:     0x7f7e238eb7f5 - rustc_driver::driver::phase_2_configure_and_expand::hd9965365e42d7a90
  21:     0x7f7e238e443a - rustc_driver::driver::compile_input::hd9f060ee16a643fb
  22:     0x7f7e23930844 - rustc_driver::run_compiler::h762802568c0e140e
  23:     0x7f7e2383cedb - std::panicking::try::do_call::h935e2f773deaf841
  24:     0x7f7e23570c8a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  25:     0x7f7e23865112 - <F as alloc::boxed::FnBox<A>>::call_box::he43811d1f6894655
  26:     0x7f7e23566804 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  27:     0x7f7e1c0216c9 - start_thread
  28:     0x7f7e232200ae - __clone
  29:                0x0 - <unknown>
```

Output of rustc --version --verbose:

```
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-unknown-linux-gnu
release: 1.16.0
LLVM version: 3.9

```

**Comment by abonander** [comment]
This should be fixed on nightly and the next stable release. I'm not sure if a beta has been cut yet but the fix was backported, IIRC.

**Comment by Tiwalun** [comment]
I tried it with the current nightly (rustc 1.18.0-nightly (5e122f59b 2017-04-01)),
and now I get the following error:

```
error: use of unstable library feature 'rustc_private' (see issue #27812)
 --> src/main.rs:3:1
  |
3 | extern crate rustc_serialize;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
```

which seems confusing to me, as I would expect an error telling me that the crate is missing, but I'm not sure if that's related to the crate itself?

**Comment by steveklabnik** [comment]
> which seems confusing to me, as I would expect an error telling me that the crate is missing, but I'm not sure if that's related to the crate itself?

Rust has an internal copy of `rustc_serialize`, and so if you don't put it in your `Cargo.toml`, rust will try to use its own internal copy. That one is guarded by the `rustc_private` gate. So you get this warning. If it was any crate that rustc _didn't_ have a copy of, then you'd get that error.

Given this no longer ICEs, I'm going to give it a close!
