### ISSUE TITLE
Unexpected Compiler Panic

### ISSUE THREAD

**Issue by isaacg1** [rust-lang/rust#41107]
I was running my code, which I didn't expect to compile, and got a compiler panic, so I'm posting it here. Apologies that it's not a minimal test case.

I tried this code:

```
#![allow(dead_code)]
extern crate termios;
extern crate libc;

use std::io::{self, Read, Write};
use std::os::raw::c_int;

use termios::*;

/*** utility ***/

const STDIN: c_int = 1;
const STDOUT: c_int = 2;

fn ctrl_key(k: char) -> u8 {
    k as u8 & 0x1f
}

/*** data ***/


struct EditorConfig {
    orig_termios: Termios,
    screen_rows: usize,
    screen_cols: usize,
}

impl EditorConfig {
    fn new(orig_termios: Termios) -> EditorConfig {
        let mut ws = libc::winsize { 
            ws_row: 0,
            ws_col: 0,
            ws_xpixel: 0,
            ws_ypixel: 0,
        };
        let res = libc::ioctl(STDOUT, libc::TIOCGWINSZ, &mut ws);
        if res == 1 || ws.ws_col == 0 {
            panic!("Editor config failed.");
        } else {
            EditorConfig {
                orig_termios = orig_termios,
                screen_rows = ws.ws_row,
                screen_cols = wc.ws_col,
            }
        }
    }
}

/*** terminal ***/
fn enable_raw_mode() -> io::Result<Termios> {
    let orig_termios = Termios::from_fd(STDIN)?;

    let mut termios = orig_termios.clone();

    termios.c_cflag |= CS8;
    termios.c_iflag &= !(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
    termios.c_lflag &= !(ECHO | ICANON | IEXTEN | ISIG);
    termios.c_oflag &= !(OPOST);
    termios.c_cc[VMIN] = 0; // Return on any characters read;
    termios.c_cc[VTIME] = 1; //Wait for 0.1 seconds.

    tcsetattr(STDIN, TCSAFLUSH, &mut termios)?;

    Ok(orig_termios)
}

fn restore_orig_mode(editor_config: &mut EditorConfig) -> io::Result<()> {
    tcsetattr(STDIN, TCSAFLUSH, &mut editor_config.orig_termios)
}

fn editor_read_key() -> u8 {
    let mut buffer: [u8; 1] = [0];
    loop {
        match io::stdin().read(&mut buffer) {
            Ok(0) => (),
            Ok(_) => return buffer[0],
            Err(e) => panic!("Read failure: {}", e),
        };
    }
}

/*** output ***/

fn editor_draw_rows() {
    for _ in 0..24 {
        println!("~\r");
    }
}

fn editor_refresh_screen() {
    print!("\x1b[2J");
    print!("\x1b[H");

    editor_draw_rows();

    print!("\x1b[H");
    io::stdout().flush().unwrap();
}

/*** input ***/
fn editor_process_keypress() -> bool {
    let c: u8 = editor_read_key();

    if c == ctrl_key('q') {
        false
    } else {
        true
    }
}

/*** init ***/

fn main() {
    let orig_termios = match enable_raw_mode() {
        Ok(t) => t,
        Err(e) => panic!("Enabling raw mode failed with {}", e),
    };

    let mut editor_config: EditorConfig = EditorConfig { orig_termios: orig_termios };
    
    println!("Type text, CTRL-q to exit.\r");
    loop {
        editor_refresh_screen();
        let to_continue = editor_process_keypress();
        if !to_continue { break } 
    }
    
    match restore_orig_mode(&mut editor_config) {
        Ok(()) => (),
        Err(e) => panic!("Disabling raw mode failed with {}", e),
    };
}
```
I ran this using `cargo check`, with the Cargo.toml file:

```
[package]
name = "text"
version = "0.1.0"
authors = ["Isaac Grosof <isaacg@mit.edu>"]

[dependencies]
termios = "0.2"
ioctl-rs = "0.1.5"
```

I expected to see this happen: A compiler error

Instead, this happened: The compiler unexpectedly panicked, and told me that this was a bug.

## Meta

`rustc --version --verbose`

rustc 1.15.0-nightly (71c06a56a 2016-12-18)
binary: rustc
commit-hash: 71c06a56a120a0d5e3b224105ee3e6754f83e5fa
commit-date: 2016-12-18
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9

`cargo --version`
cargo 0.16.0-nightly (ddb5c32 2016-12-16)

Backtrace:

`RUST_BACKTRACE=1 cargo check 2> log.txt`

```
   Compiling text v0.1.0 (file:///home/isaac/prog/rust/text)
error: expected one of `,` or `}`, found `=`
  --> src/main.rs:40:30
   |
40 |                 orig_termios = orig_termios,
   |                              ^

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x7f034cdad38a - std::sys::imp::backtrace::tracing::imp::write::h0d1aacfb8fc693ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f034cdbb6ff - std::panicking::default_hook::{{closure}}::hff87359baf5754d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7f034cdbb29d - std::panicking::default_hook::h936f17ca3b2b98dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:359
   4:     0x7f034cdbbba7 - std::panicking::rust_panic_with_hook::he9c830ab830c7944
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7f034cdbba34 - std::panicking::begin_panic::hbd10b7f500042f98
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7f034cdbb959 - std::panicking::begin_panic_fmt::h49583ddd44614a0d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x7f034cdbb8e7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x7f034cdf71cd - core::panicking::panic_fmt::h3b787d0ceafd7204
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7f034cdf7104 - core::panicking::panic::h57808c0fa90ee3ee
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x7f034b2b51bb - rustc_metadata::creader::CrateLoader::resolve_crate::h42bbaa7ad477c08e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_metadata/creader.rs:229
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_metadata/cstore.rs:148
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_metadata/creader.rs:192
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_metadata/creader.rs:344
  11:     0x7f034b2bc564 - <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_item::h27e3d871efa8103e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_metadata/creader.rs:1021
  12:     0x7f034c52a1d0 - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h34d3157f6c27082e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_resolve/build_reduced_graph.rs:236
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_resolve/build_reduced_graph.rs:708
  13:     0x7f034c52ca4e - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item::h34d3157f6c27082e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/visit.rs:140
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/visit.rs:59
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/visit.rs:258
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_resolve/build_reduced_graph.rs:709
  14:     0x7f034c52236f - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::h256af8786c8e8cc7
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ext/expand.rs:94
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_resolve/macros.rs:136
  15:     0x7f0345e7259e - syntax::ext::expand::MacroExpander::collect_invocations::h3b6970f712e5246a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ext/expand.rs:323
  16:     0x7f0345e71002 - syntax::ext::expand::MacroExpander::expand::he915f7737e57b90c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ext/expand.rs:225
  17:     0x7f0345e708d7 - syntax::ext::expand::MacroExpander::expand_crate::h46f2fa9a3b1ebe5a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/ext/expand.rs:209
  18:     0x7f034d13193f - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::h0ad68d726f9b2568
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:681
  19:     0x7f034d12a4c4 - rustc_driver::driver::phase_2_configure_and_expand::h2cc6ba3ed8dbd9ea
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/util/common.rs:34
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:644
  20:     0x7f034d12395e - rustc_driver::driver::compile_input::hc9da7de451d406ba
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:120
  21:     0x7f034d16ab47 - rustc_driver::run_compiler::h408af14fa24a33a5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:221
  22:     0x7f034d0889e8 - std::panicking::try::do_call::h2c149962956958c1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:1117
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:137
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:1051
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  23:     0x7f034cdc43ca - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  24:     0x7f034d0aa328 - <F as alloc::boxed::FnBox<A>>::call_box::hf839c55097f480b2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  25:     0x7f034cdba564 - std::sys::imp::thread::Thread::new::thread_start::h1fa04983ba2271d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  26:     0x7f0344fc2183 - start_thread
  27:     0x7f034ca6f37c - clone
  28:                0x0 - <unknown>

error: Could not compile `text`.

To learn more, run the command again with --verbose.
```

**Comment by arielb1** [comment]
Does the problem still exist in the new stable (1.16)?

**Comment by isaacg1** [comment]
@arielb1 I hadn't realised I hadn't updated in a while. The problem's gone on the new stable and the new nightly.

**Comment by arielb1** [comment]
Well then we're not going to fix this on 1.15. Closing.

**Comment by arielb1** [comment]
If the problem shows up on 1.16/1.17, feel free to open a new bug.

**Comment by isaacg1** [comment]
@arielb1 Thanks for your help.
