### ISSUE TITLE
ICE when invoking attribute macro on crate root

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#41211]
An ICE occurs when invoking a procedural macro attribute on the root of a crate with `#![my_proc_macro]`.

Relevant backtrace frames:

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:329
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: syntax::ext::expand::MacroExpander::expand_crate
             at C:\Users\cyber\Rust\rust\src\libsyntax\ext\expand.rs:225
   1: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}<closure>
             at C:\Users\cyber\Rust\rust\src\librustc_driver\driver.rs:699
```

This happens on the latest nightly [`rustc 1.18.0-nightly (ad36c2f55 2017-04-09)`], however because I'm lazy I got this backtrace from the last debug build from my last PR so the lines have moved. I suspect it's one of the two `unwraps()` at [line 217](https://github.com/rust-lang/rust/blob/master/src/libsyntax/ext/expand.rs#L217).

cc @jseyfried

**Comment by abonander** [comment]
@jseyfried If you haven't started on this one I'll go ahead and take a crack at it since people are stumbling on it.

**Comment by abonander** [comment]
That second unwrap is `syntax::ptr::P::unwrap()` which is infallible. That's kind of misleading, but okay.
