### ISSUE TITLE
Intermittent ctrl_c_kills_everyone Windows test failure

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#41511]
https://github.com/rust-lang/rust/pull/41503#issuecomment-296758814

```
running 1 test
test ctrl_c_kills_everyone ... FAILED
failures:
---- ctrl_c_kills_everyone stdout ----
	attempt 0: The directory is not empty. (os error 145)
attempt 1: Access is denied. (os error 5)
attempt 2: Access is denied. (os error 5)
attempt 3: Access is denied. (os error 5)
attempt 4: Access is denied. (os error 5)
attempt 5: Access is denied. (os error 5)
attempt 6: Access is denied. (os error 5)
attempt 7: Access is denied. (os error 5)
attempt 8: Access is denied. (os error 5)
attempt 9: Access is denied. (os error 5)
thread 'ctrl_c_kills_everyone' panicked at 'couldn't remove build directory after a few tries, seems like we won't be able to!', tests\death.rs:120
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    ctrl_c_kills_everyone
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
error: test failed
thread 'main' panicked at 'tests failed for https://github.com/rust-lang/cargo', src\tools\cargotest\main.rs:98
note: Run with `RUST_BACKTRACE=1` for a backtrace.
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-tools\\x86_64-pc-windows-msvc\\release\\cargotest.exe" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "C:\\projects\\rust\\build\\ct"
expected success, got: exit code: 101
Build completed unsuccessfully in 0:18:23
make: *** [Makefile:56: check-aux] Error 1
Command exited with code 2
```

**Comment by alexcrichton** [comment]
The test in question is [in Cargo](https://github.com/rust-lang/cargo/blob/b987ce4f26a955595d168abdba951ab4bba63dd2/tests/death.rs#L53-L122) and tests whether ctrl-c actually kills Cargo's process tree. 

I ... don't know how this'd happen. This means that for a full second something was alive which kept open a file in that build tree ...

**Comment by Mark-Simulacrum** [comment]
This hasn't happened since then judging by GitHub not having any more than that one PR, so I'm going to close this.
