### ISSUE TITLE
Compiler says I found a bug, not sure what to do.

### ISSUE THREAD

**Issue by siscia** [rust-lang/rust#41541]
The code I am trying to compile looks like this:

``` rust
unsafe extern "C" fn rdb_save(rdb: *mut ffi::RedisModuleIO,
                              value: *mut std::os::raw::c_void) {


    let db: *mut DBKey =
        unsafe { Box::into_raw(Box::from_raw(value as *mut DBKey)) };

    // create a new db physical db and start the backup
    // then use the rdb api to copy the new db into redis
    // delete the old db

    let path = format!("rediSQL_rdb_{}.sqlite", Uuid::new_v4());

    match create_backup(&(*db).db, path.clone()) {
        Err(e) => println!("{}", e),
        Ok(not_done) if !sql::backup_complete_with_done(not_done) => {
            println!("Return NOT DONE: {}", not_done)
        }
        Ok(done) => {
            match File::open(path) {
                Err(e) => println!("{}", e),
                Ok(f) => {
                    let mut to_write: Vec<u8> = vec![0, 1024 * 4];
                    let buffer = BufReader::with_capacity(1024 * 4, f);
                    let mut keep_going = true;
                    while continue {
                        match buffer.read(to_write.as_mut_slice()) {
                            Ok(0) => {
                                keep_going = false;
                            }
                            Ok(n) => {
                                keep_going = true;
                                // line below I believe is where the problem appear
                                ffi::RedisModule_SaveStringBuffer.unwrap()(rdb, to_write.as_ptr() as *const i8, n)
                            }
                            Err(_) => keep_going = false,
                        }
                    }
                }
            }
        }
    }
}

```

Where RedisModule_SaveStringBuffer is a function exposed by redis 4.0 in the module API.

```rust 
extern "C" {
    #[link_name = "RedisModule_SaveStringBuffer"]
    pub static mut RedisModule_SaveStringBuffer:
               ::std::option::Option<unsafe extern "C" fn(io:
                                                              *mut RedisModuleIO,
                                                          str:
                                                              *const ::std::os::raw::c_char,
                                                          len: usize)>;
}
```

```
$ RUST_BACKTRACE=1 cargo build --verbose
       Fresh glob v0.2.11
       Fresh num-traits v0.1.37
       Fresh utf8-ranges v1.0.0
       Fresh bitflags v0.8.2
       Fresh itoa v0.3.1
       Fresh lazy_static v0.2.6
       Fresh ansi_term v0.9.0
       Fresh log v0.3.7
       Fresh rustc-serialize v0.3.23
       Fresh dtoa v0.4.1
       Fresh unicode-width v0.1.4
       Fresh vec_map v0.7.0
       Fresh serde v0.9.13
       Fresh unicode-xid v0.0.4
       Fresh libc v0.2.21
       Fresh syntex_pos v0.58.1
       Fresh gcc v0.3.45
       Fresh cfg-if v0.1.0
       Fresh term v0.4.5
       Fresh serde_json v0.9.9
       Fresh regex-syntax v0.4.0
       Fresh thread-id v3.0.0
       Fresh term_size v0.2.3
       Fresh rand v0.3.15
       Fresh atty v0.2.2
       Fresh memchr v1.0.1
       Fresh syntex_errors v0.58.1
       Fresh strsim v0.6.0
       Fresh void v1.0.2
       Fresh siphasher v0.2.2
       Fresh nom v1.2.4
       Fresh uuid v0.4.0
       Fresh unicode-segmentation v1.1.0
       Fresh aho-corasick v0.6.3
       Fresh syntex_syntax v0.58.1
       Fresh unreachable v0.1.1
       Fresh phf_shared v0.7.21
       Fresh cexpr v0.2.0
       Fresh clap v2.23.1
       Fresh quasi v0.32.0
       Fresh aster v0.41.0
       Fresh syntex v0.58.1
       Fresh thread_local v0.3.3
       Fresh phf_generator v0.7.21
       Fresh phf v0.7.21
       Fresh quasi_codegen v0.32.0
       Fresh regex v0.2.1
       Fresh phf_codegen v0.7.21
       Fresh env_logger v0.4.2
       Fresh target_build_utils v0.3.0
       Fresh libloading v0.3.4
       Fresh clang-sys v0.15.1
       Fresh bindgen v0.22.1 (https://github.com/servo/rust-bindgen#26eeb6db)
warning: src/CDeps/Redis/redismodule.c:3:25: warning: ‘DBType’ initialized and declared ‘extern’
warning:  extern RedisModuleType *DBType = NULL;
warning:                          ^
   Compiling rediSQL v0.1.0 (file:///home/simo/rediSQL)
     Running `rustc --crate-name redis_sql src/lib.rs --crate-type cdylib --emit=dep-info,link -C debuginfo=2 -C metadata=7db90ffd5f4bab73 -C extra-filename=-7db90ffd5f4bab73 --out-dir /home/simo/rediSQL/target/debug/deps -L dependency=/home/simo/rediSQL/target/debug/deps --extern uuid=/home/simo/rediSQL/target/debug/deps/libuuid-0b38668ad3f0fd0f.rlib --extern libc=/home/simo/rediSQL/target/debug/deps/liblibc-5dc7b85e748840b4.rlib -L native=/home/simo/rediSQL/target/debug/build/rediSQL-5b8806de7e0c6fc6/out -L native=/home/simo/rediSQL/target/debug/build/rediSQL-5b8806de7e0c6fc6/out -l static=redismodule -l static=sqlite3`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x7fed6ae1240c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fed6ae209ae - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7fed6ae20553 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7fed6ae20e4b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7fed6ae20ce4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7fed6ae20c09 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7fed6ae20b97 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7fed6ae5dedd - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7fed6ae5de14 - core::panicking::panic::h7abeb5b818ec354e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x7fed67e0ee69 - rustc::cfg::construct::CFGBuilder::find_scope::h19db9ca36372ea72
  11:     0x7fed67e0d1f5 - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  12:     0x7fed67e0c72e - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  13:     0x7fed67e0d040 - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  14:     0x7fed67e0cf76 - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  15:     0x7fed67e0d040 - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  16:     0x7fed67e0cf76 - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  17:     0x7fed67e0d040 - rustc::cfg::construct::CFGBuilder::expr::h5ac36b4c2d8be0fb
  18:     0x7fed67e10399 - rustc::cfg::CFG::new::h312b69631e686d0a
  19:     0x7fed694ea821 - rustc_borrowck::borrowck::borrowck_fn::h2640a8d61361adc2
  20:     0x7fed694e83f9 - <rustc_borrowck::borrowck::BorrowckCtxt<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::h1a1f9183d356add9
  21:     0x7fed694ea0df - rustc_borrowck::borrowck::borrowck_item::h39fc61bc1562191e
  22:     0x7fed694e8e80 - rustc_borrowck::borrowck::check_crate::h254861d0e7063156
  23:     0x7fed6b1c1014 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h040eea107b0d299b
  24:     0x7fed6b1bb6c6 - rustc_driver::driver::phase_3_run_analysis_passes::haec055f3322a38aa
  25:     0x7fed6b19f150 - rustc_driver::driver::compile_input::hd9f060ee16a643fb
  26:     0x7fed6b1e9844 - rustc_driver::run_compiler::h762802568c0e140e
  27:     0x7fed6b0f5edb - std::panicking::try::do_call::h935e2f773deaf841
  28:     0x7fed6ae29c8a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  29:     0x7fed6b11e112 - <F as alloc::boxed::FnBox<A>>::call_box::he43811d1f6894655
  30:     0x7fed6ae1f804 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  31:     0x7fed638d96b9 - start_thread
  32:     0x7fed6aad582c - clone
  33:                0x0 - <unknown>

error: Could not compile `rediSQL`.

Caused by:
  process didn't exit successfully: `rustc --crate-name redis_sql src/lib.rs --crate-type cdylib --emit=dep-info,link -C debuginfo=2 -C metadata=7db90ffd5f4bab73 -C extra-filename=-7db90ffd5f4bab73 --out-dir /home/simo/rediSQL/target/debug/deps -L dependency=/home/simo/rediSQL/target/debug/deps --extern uuid=/home/simo/rediSQL/target/debug/deps/libuuid-0b38668ad3f0fd0f.rlib --extern libc=/home/simo/rediSQL/target/debug/deps/liblibc-5dc7b85e748840b4.rlib -L native=/home/simo/rediSQL/target/debug/build/rediSQL-5b8806de7e0c6fc6/out -L native=/home/simo/rediSQL/target/debug/build/rediSQL-5b8806de7e0c6fc6/out -l static=redismodule -l static=sqlite3` (exit code: 101)
```

I push the whole code here:
https://github.com/siscia/rediSQL/tree/error_rustc

**Comment by jmesmon** [comment]
Appears to reduce to: https://is.gd/5Cwj9Q

```
fn main() {
    while continue {}
}
```

**Comment by jmesmon** [comment]
@siscia as for your code, `while continue` should likely be `while keep_going`. This is still a valid bug report though, we should likely complain about `while continue` instead of panicking.

**Comment by jmesmon** [comment]
Oh, and an error is reported on beta & nightly, so we appear to be good to go:

```
rustc 1.17.0-beta.3 (ca3d11832 2017-04-05)
error[E0590]: `break` or `continue` with no label in the condition of a `while` loop
 --> <anon>:3:11
  |
3 |     while continue {}
  |           ^^^^^^^^ unlabeled `continue` in the condition of a `while` loop

error: aborting due to previous error
```

**Comment by siscia** [comment]
Ahahaha, sorry about the noise.
