### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by sirideain** [rust-lang/rust#41689]
I am getting this error when trying to build from source. I am on Windows 10 with the creators update.

```
PS C:\Users\User\Documents\Source\GitHub\rust> python .\x.py build -vv
    Finished dev [unoptimized] target(s) in 0.0 secs
 Downloading strsim v0.6.0
 Downloading void v1.0.2
 Downloading diff v0.1.10
 Downloading atty v0.2.2
 Downloading unicode-segmentation v1.1.0
 Downloading quick-error v1.1.0
 Downloading ansi_term v0.9.0
 Downloading winapi v0.2.8
 Downloading env_logger v0.4.2
 Downloading thread-id v3.0.0
 Downloading kernel32-sys v0.2.2
 Downloading handlebars v0.25.2
 Downloading regex v0.2.1
 Downloading aho-corasick v0.6.3
 Downloading clap v2.22.1
 Downloading unreachable v0.1.1
 Downloading bitflags v0.8.2
 Downloading rls-span v0.1.0
 Downloading memchr v1.0.1
 Downloading pulldown-cmark v0.0.8
 Downloading pest v0.3.3
 Downloading utf8-ranges v1.0.0
 Downloading log v0.3.7
 Downloading vec_map v0.7.0
 Downloading rls-data v0.1.0
 Downloading term_size v0.2.3
 Downloading serde v0.9.11
 Downloading thread_local v0.3.3
 Downloading lazy_static v0.2.5
 Downloading unicode-width v0.1.4
 Downloading toml v0.3.1
 Downloading bitflags v0.5.0
 Downloading mdbook v0.0.21
 Downloading serde_json v0.9.9
 Downloading winapi-build v0.1.1
 Downloading pulldown-cmark v0.0.14
 Downloading open v1.2.0
finding compilers
CC_x86_64-pc-windows-msvc = "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe"
CXX_x86_64-pc-windows-msvc = "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe"
running sanity check
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:329
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:49
   9: main
  10: bootstrap::flags::Subcommand::test_args
  11: main
  12: bootstrap::flags::Subcommand::test_args
  13: bootstrap::flags::Subcommand::test_args
  14: bootstrap::Build::build
  15: EMPTY
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  17: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  18: main
  19: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  20: BaseThreadInitThunk
Build completed unsuccessfully in 0:00:31
```

**Comment by sirideain** [comment]
No idea what caused this, but I fixed it by reinstalling Windows.
