### ISSUE TITLE
Rust 1.18 regression, rust_utp 0.8.1

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41804]
https://github.com/meqif/rust-utp

```
130 brian@ip-10-145-43-250:~/dev/rust-utp⟫ git log -1
commit e9bf831c41714f545762f482a1d464f188faa1a9
Author: Ricardo Martins <ricardo@scarybox.net>
Date:   Wed Sep 7 21:35:13 2016 +0100

    Add compiler flag to improve coverage accuracy
```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.18.0-beta.1 (4dce67253 2017-04-25)
binary: rustc
commit-hash: 4dce67253d67785c74c8d270c38d774edd0deed8
commit-date: 2017-04-25
host: x86_64-unknown-linux-gnu
release: 1.18.0-beta.1
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/rust-utp⟫ cargo +beta test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/utp-c485d82845010176

running 49 tests
test packet::tests::test_decode_empty_packet ... ok
test packet::tests::extension_iterator ... ok
test bit_iterator::test_iterator ... ok
test packet::tests::test_decode_evil_sequence ... ok
test packet::tests::test_packet_decode ... FAILED
test packet::tests::test_decode_packet_with_extension ... FAILED
test packet::tests::test_packet_decode_with_malformed_extension ... ok
test packet::tests::test_packet_decode_with_missing_extension ... ok
test packet::tests::test_decode_packet_with_unknown_extensions ... FAILED
test packet::tests::test_packet_encode_with_payload ... FAILED
test packet::tests::test_packet_set_selective_acknowledgment ... ok
test packet::tests::test_packet_encode ... FAILED
test packet::tests::test_reversible ... ok
test socket::test::test_base_delay_calculation ... ok
test socket::test::test_connection_loss_data ... ignored
test socket::test::test_connection_loss_fin ... ignored
test socket::test::test_connection_loss_waiting ... ignored
test packet::tests::test_packet_set_type ... ok
test socket::test::test_drop_unused_socket ... ok
test socket::test::test_duplicate_packet_handling ... FAILED
test socket::test::test_handle_packet ... ok
test socket::test::test_invalid_packet_on_connect ... ok
test socket::test::test_listener_local_addr ... ok
test socket::test::test_local_addr ... ok
test socket::test::test_peer_addr ... FAILED
test packet::tests::quicktest ... ok
test socket::test::test_receive_unexpected_reply_type_on_connect ... FAILED
test socket::test::test_acks_on_socket ... FAILED
thread '<unnamed>' panicked at 'Error { repr: Custom(Custom { kind: Other, error: StringError("The packet is too small") }) }', thread 'src/socket.rs<unnamed>:' panicked at '1846Error { repr: Custom(Custom { kind: Other, error: StringError("The packet is too small") }) }',
src/socket.rs:1789
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'Error { repr: Custom(Custom { kind: Other, error: StringError("The packet is too small") }) }Error { repr: Custom(Custom { kind: Other, error: StringError("The packet is too small") }) }', ', src/socket.rssrc/socket.rs:2099
:2185
thread '<unnamed>' panicked at 'Error { repr: Custom(Custom { kind: Other, error: StringError("The packet is too small") }) }', src/socket.rs:2060
test socket::test::test_correct_packet_loss has been running for over 60 seconds
test socket::test::test_premature_fin has been running for over 60 seconds
test socket::test::test_receiving_reset_on_established_connection has been running for over 60 seconds
test socket::test::test_receiving_syn_on_established_connection ... FAILED
```

cc @meqif

**Comment by meqif** [comment]
I assume "0.8.1" is a typo, the latest version until a few minutes ago was 0.6.3.
That issue was caused by a missing `#repr(C)` in a `struct`, and it was fixed in the `master` branch. I publish a new version (0.7.0) of the library to crates.io with the fix. Thank you for poking me.

Is there anything else I can help with?

**Comment by brson** [comment]
Thank you for investigating @meqif. Sounds like there's nothing left to do here.
