### ISSUE TITLE
AddressSanitizer: odr-violation with zero size

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#41807]
```
   Compiling libz-sys v1.0.13 (file:///tmp/libz-sys)
error: failed to run custom build command for `libz-sys v1.0.13 (file:///tmp/libz-sys)`
process didn't exit successfully: `/tmp/libz-sys/target/debug/build/libz-sys-adcfdad3f52dba5a/build-script-build` (exit code: 1)
--- stderr
=================================================================
==3839==ERROR: AddressSanitizer: odr-violation (0x5604022c8b20):
  [1] size=0 'ref.x' pkg_config.rs
  [2] size=0 'ref.d' build_script_build.rs
These globals were registered at these points:
  [1]:
    #0 0x5604021f2130 in __asan_register_globals.part.11 /build/src/rust/src/compiler-rt/lib/asan/asan_globals.cc:338
    #1 0x5604020a3bad in asan.module_ctor (/tmp/libz-sys/target/debug/build/libz-sys-adcfdad3f52dba5a/build-script-build+0xc0bad)

  [2]:
    #0 0x5604021f2130 in __asan_register_globals.part.11 /build/src/rust/src/compiler-rt/lib/asan/asan_globals.cc:338
    #1 0x56040202420d in asan.module_ctor (/tmp/libz-sys/target/debug/build/libz-sys-adcfdad3f52dba5a/build-script-build+0x4120d)

==3839==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'ref.x' at pkg_config.rs
==3839==ABORTING
```

As you can see, they are both 0 sized, which means this is some kind of internally generated code.

```
rustc 1.19.0-dev (5d0865315 2017-05-03)
binary: rustc
commit-hash: 5d0865315b0f46546db298f7bcdaa713cf20e11a
commit-date: 2017-05-03
host: x86_64-unknown-linux-gnu
release: 1.19.0-dev
LLVM version: 4.0
```

**Comment by dwrensha** [comment]
Related cargo-fuzz pull request: https://github.com/rust-fuzz/cargo-fuzz/pull/32

**Comment by Shnatsel** [comment]
This can be worked around by disabling the ODR violation check, as seen here: https://github.com/image-rs/image-png/blob/edcf8b07a355159fe69248aeb757cc48f212cf41/png-afl/src/main.rs#L5-L11

**Comment by tmiasko** [comment]
Is this still an issue? Could you provide updated reproduction steps?
