### ISSUE TITLE
Cannot Relate Bound Region on const in Trait, compiler panic

### ISSUE THREAD

**Issue by InsidiousMind** [rust-lang/rust#41823]
I tried this code:

```
pub trait Emulator<'a> {
    const m:State<'a> = State::new();

    fn init(&self, ram_64K: &mut u8);

    fn load(&mut self, regs: [u8; Sizes::REGISTER_COUNT as usize]);

    // Runs DSP for specified number of clocks (~1024000 per second). Every 32 clocks
    // a pair of samples is to be generated
    fn run(clock_count: isize);
}
```
The repo with this exact code is here: https://github.com/InsidiousMind/smpd/tree/e4e5842ee6c80f3d7e8319c4ceecdb3b0ef36c8f

the file being: https://github.com/InsidiousMind/smpd/blob/e4e5842ee6c80f3d7e8319c4ceecdb3b0ef36c8f/SPC_DSP/src/SPC_DSP.rs

The code i added was the `const m:State<'a> = State::new()` (specifically panicked at the lifetime, 'a. Did not expect this code to work.) 

I expected to see this happen: Compile, albeit with many errors (scope errors mostly)

Instead, this happened: ICE, with an error citing "cannot relate bound region"

## Meta

```
rustc 1.19.0-nightly (777ee2079 2017-05-01)
binary: rustc
commit-hash: 777ee20796e80a31d4b7c985dd68eda2941460d6
commit-date: 2017-05-01
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```
backtrace:
```
   Compiling SPC_DSP v0.1.0 (file:///home/insi/Projects/smpd/SPC_DSP)
     Running `rustc --crate-name SPC_DSP src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=32ecbd31718c60b7 -C extra-filename=-32ecbd31718c60b7 --out-dir /home/insi/Projects/smpd/SPC_DSP/target/debug/deps -L dependency=/home/insi/Projects/smpd/SPC_DSP/target/debug/deps`
error[E0425]: cannot find value `m` in this scope
  --> src/SPC_DSP.rs:81:9
   |
81 |         m.set_ram(ram_64K); 
   |         ^ did you mean `Self::m`?

error[E0425]: cannot find value `m` in this scope
  --> src/SPC_DSP.rs:82:9
   |
82 |         m.mute_voices(0);
   |         ^ did you mean `Self::m`?

error[E0425]: cannot find value `m` in this scope
  --> src/SPC_DSP.rs:83:9
   |
83 |         m.disable_surround(false);
   |         ^ did you mean `Self::m`?

error[E0425]: cannot find value `m` in this scope
  --> src/SPC_DSP.rs:84:9
   |
84 |         m.set_output(0 as *mut sample_t, 0isize);
   |         ^ did you mean `Self::m`?

error[E0425]: cannot find value `m` in this scope
  --> src/SPC_DSP.rs:85:9
   |
85 |         m.reset();
   |         ^ did you mean `Self::m`?

error[E0425]: cannot find value `m` in this scope
  --> src/SPC_DSP.rs:99:9
   |
99 |         m.regs = regs;
   |         ^ did you mean `Self::m`?

error[E0425]: cannot find value `m` in this scope
   --> src/macros.rs:37:17
    |
37  |     (kon)   => (m.regs[GlobalRegisters::r_kon   as usize]);
    |                 ^ did you mean `Self::m`?
    | 
   ::: src/SPC_DSP.rs
    |
107 |         self.m.new_kon = reg!(kon) as isize;
    |                          --------- in this macro invocation

error[E0425]: cannot find value `m` in this scope
   --> src/SPC_DSP.rs:108:28
    |
108 |         self.m.mute_voices(m.mute_mask);
    |                            ^ did you mean `Self::m`?

error: internal compiler error: /checkout/src/librustc/infer/region_inference/mod.rs:710: cannot relate bound region: ReEarlyBound(1, 'a) <= ReStatic
  --> src/SPC_DSP.rs:66:25
   |
66 |     const m:State<'a> = State::new();
   |                         ^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:375
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::span_bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::span_bug_fmt
  10: rustc::infer::region_inference::RegionVarBindings::make_subregion
  11: <rustc::infer::sub::Sub<'combine, 'infcx, 'gcx, 'tcx> as rustc::ty::relate::TypeRelation<'infcx, 'gcx, 'tcx>>::regions
  12: rustc::ty::relate::relate_substs::{{closure}}
  13: <<core::result::Result<V, E> as core::iter::traits::FromIterator<core::result::Result<A, E>>>::from_iter::Adapter<Iter, E> as core::iter::iterator::Iterator>::next
  14: <core::result::Result<V, E> as core::iter::traits::FromIterator<core::result::Result<A, E>>>::from_iter
  15: <core::result::Result<T, E> as rustc::ty::context::InternIteratorElement<T, R>>::intern_with
  16: rustc::ty::relate::relate_substs
  17: rustc::ty::relate::relate_item_substs
  18: rustc::ty::relate::super_relate_tys
  19: <rustc::infer::sub::Sub<'combine, 'infcx, 'gcx, 'tcx> as rustc::ty::relate::TypeRelation<'infcx, 'gcx, 'tcx>>::tys
  20: rustc::infer::InferCtxt::sub
  21: rustc::infer::InferCtxt::sub_types
  22: rustc_typeck::check::FnCtxt::expected_inputs_for_expected_output
  23: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::confirm_builtin_call
  24: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::check_call
  25: rustc_typeck::check::FnCtxt::check_expr_kind
  26: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  27: rustc_typeck::check::typeck_tables_of
  28: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  29: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  30: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  31: rustc_typeck::check::typeck_item_bodies
  32: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get
  33: rustc::ty::maps::TyCtxtAt::typeck_item_bodies
  34: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies
  35: rustc_typeck::check_crate
  36: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  37: rustc_driver::driver::phase_3_run_analysis_passes
  38: rustc_driver::driver::compile_input
  39: rustc_driver::run_compiler
  40: std::panicking::try::do_call
  41: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  42: <F as alloc::boxed::FnBox<A>>::call_box
  43: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:658
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  44: start_thread
  45: clone

error: Could not compile `SPC_DSP`.

Caused by:
  process didn't exit successfully: `rustc --crate-name SPC_DSP src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=32ecbd31718c60b7 -C extra-filename=-32ecbd31718c60b7 --out-dir /home/insi/Projects/smpd/SPC_DSP/target/debug/deps -L dependency=/home/insi/Projects/smpd/SPC_DSP/target/debug/deps` (exit code: 101)
```

**Comment by Mark-Simulacrum** [comment]
This does not ICE today as best as I can tell, and since testing this specific case without a minimal example doesn't seem feasible I'm closing.
