### ISSUE TITLE
program segfaults when compiled with opt-level>0

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#41888]
The following program (reduced from https://github.com/shepmaster/fuzzy-pickles/issues/62) segfaults when compiled with optimizations in `panic=abort` mode using beta or nightly `rustc`.

<details>
<summary> code </summary>

```rust
// parse.rs

fn main() {
    let tokens = &[Token::Ident, Token::AmpersandEquals, Token::Ident];
    let _ = expression(Point::new(tokens));
}

struct Progress<'s, T> {
    point: Point<'s>,
    status: Result<T, ()>,
}

impl<'s, T> Progress<'s, T> {
    pub fn success(point: Point<'s>, val: T) -> Self {
        Progress { point: point, status: Ok(val) }
    }

    pub fn failure(point: Point<'s>) -> Self {
        Progress { point: point, status: Err(()) }
    }

    pub fn map<F, T2>(self, f: F) -> Progress<'s, T2>
        where F: FnOnce(T) -> T2
    {
        Progress { point: self.point, status: self.status.map(f) }
    }
}

#[derive(Copy, Clone)]
enum Token {
    AmpersandEquals,
    Ident,
}

impl Token {
    fn into_ident(self) -> Option<Extent> {
        match self {
            Token::Ident => Some((0,0)),
            _ => None,
        }
    }

    fn into_ampersand_equals(self) -> Option<Extent> {
        match self {
            Token::AmpersandEquals => Some((0,0)),
            _ => None,
        }
    }
}

#[derive(Copy, Clone)]
struct Point<'s> {
    pub offset: usize,
    pub s: &'s [Token],
}

impl<'s> Point<'s> {
    fn new(slice: &'s [Token]) -> Self {
        Point {
            offset: 0,
            s: slice,
        }
    }

    fn advance_by(&self, offset: usize) -> Self {
        Point {
            offset: self.offset + offset,
            s: &self.s[offset..],
        }
    }
}

pub type Extent = (usize, usize);

enum Expression {
    AsType(AsType),
    Binary(Binary),
    Call(Call),
    FieldAccess(FieldAccess),
    Slice(Slice),
    Value(Value),
}

struct FieldAccess {
    target: Box<Expression>,
}

pub struct Value;

pub struct Call {
    extent: Extent,
    target: Box<Expression>,
    args: Vec<Expression>,
}

pub struct Binary {
    lhs: Box<Expression>,
    rhs: Box<Expression>,
}

struct AsType {
    extent: Extent,
    target: Box<Expression>,
}

struct Slice {
    target: Box<Expression>,
    index: Box<Expression>,
}

fn token<'s, F, T>(token_convert: F, pt: Point<'s>) ->
    Progress<'s, T>
    where F: Fn(Token) -> Option<T>,
{
    let original_token = match pt.s.first() {
        Some(&token) => token,
        None => return Progress::failure(pt),
    };

    match token_convert(original_token) {
        Some(v) => {
            Progress::success(pt.advance_by(1), v)
        }
        None => {
            Progress::failure(pt)
        }
    }
}

enum OperatorInfix {
    BitwiseAndAssign(Extent),
}

enum OperatorPostfix {
    AsType { typ: () },
    Call { args: Vec<Expression> },
    FieldAccess { field: () },
    Slice { index: Expression },
}

enum OperatorKind {
    Infix(OperatorInfix),
    Postfix(OperatorPostfix),
}

impl OperatorKind {
    fn precedence(&self) -> u8 {
        match *self {
            OperatorKind::Infix(_) => 10,
            OperatorKind::Postfix(OperatorPostfix::Call { .. }) => 10,
            OperatorKind::Postfix(_) => 20,
        }
    }
}

enum InfixOrPostfix {
    Infix(OperatorInfix),
    Postfix(OperatorPostfix),
}

struct ShuntCar<'s, T> {
    value: T,
    spt: Point<'s>,
    ept: Point<'s>,
}

struct ShuntingYard<'s> {
    operators: Vec<ShuntCar<'s, OperatorKind>>,
    result: Vec<ShuntCar<'s, Expression>>,
}

type PointRange<'s> = std::ops::Range<Point<'s>>;
type ExprResult<'s, T> = std::result::Result<T, Point<'s>>;

impl<'s> ShuntingYard<'s> {
    fn add_infix(&mut self, op: OperatorInfix, spt: Point<'s>, ept: Point<'s>) -> ExprResult<'s, ()>
    {
        let op = OperatorKind::Infix(op);
        self.apply_precedence(&op)?;
        self.operators.push(ShuntCar { value: op, spt, ept });
        Ok(())
    }

    fn apply_precedence(&mut self, operator: &OperatorKind) -> ExprResult<'s, ()>  {
        let op_precedence = operator.precedence();
        while self.operators.last().map_or(false, |&ShuntCar { value: ref top, .. }| top.precedence() > op_precedence) {
            let ShuntCar { value: _, spt, ept } = self.operators.pop().unwrap();
            self.apply_binary(spt..ept)?;
        }
        Ok(())
    }

    fn apply_all(&mut self) -> ExprResult<'s, ()> {
        while let Some(ShuntCar { value: _, spt, ept }) = self.operators.pop() {
            self.apply_binary(spt..ept)?;
        }
        Ok(())
    }

    fn apply_infix<F>(&mut self, op_range: PointRange<'s>, f: F) ->
        ExprResult<'s, ()>
        where F: FnOnce(Expression, Expression) -> Expression
    {
        let ShuntCar { value: rhs, ept: rexpr_ept, .. } = self.pop_expression(op_range.end)?;
        let ShuntCar { value: lhs, spt: lexpr_spt, .. } = self.pop_expression(op_range.start)?;
        let new_expr = f(lhs, rhs);
        self.result.push(ShuntCar { value: new_expr, spt: lexpr_spt, ept: rexpr_ept });
        Ok(())
    }

    fn apply_binary(&mut self, op_range: PointRange<'s>) ->
        ExprResult<'s, ()>
    {
        self.apply_infix(op_range, |lhs, rhs| {
            Expression::Binary(Binary {
                lhs: Box::new(lhs),
                rhs: Box::new(rhs),
            })
        })
    }

    fn pop_expression(&mut self, location: Point<'s>) ->
        ExprResult<'s, ShuntCar<'s, Expression>>
    {
        self.result.pop().ok_or(location)
    }
}

enum ExpressionState {
    Prefix, // Also "beginning of expression"
    Infix,
    Atom,
}

fn expression<'s>(pt: Point<'s>) -> Progress<'s, Expression> {
    match expression_x(pt) {
        Ok(ShuntCar { value: expr, ept, .. }) => Progress::success(ept, expr),
        Err(failure_point) => Progress::failure(failure_point),
    }
}

fn expression_x<'s>(mut pt: Point<'s>) ->
    ExprResult<'s, ShuntCar<'s, Expression>>
{
    let mut shunting_yard = ShuntingYard { operators: Vec::new(), result: Vec::new() };
    let mut state = ExpressionState::Prefix;
    loop {
        println!("expression_x loop");
        match state {
            ExpressionState::Prefix |
            ExpressionState::Infix => {
                println!("branch 1");
                let Progress { point, .. } =
                    token(Token::into_ident, pt).map(|_| Value).map(Expression::Value);
                state = ExpressionState::Atom;
                pt = point;
            }
            ExpressionState::Atom => {
                println!("branch 2");
                match token(Token::into_ampersand_equals, pt)
                    .map(OperatorInfix::BitwiseAndAssign).map(InfixOrPostfix::Infix) {
                    Progress { status: Ok(infix_or_postfix), point } => {
                        match infix_or_postfix {
                            InfixOrPostfix::Infix(op) => {
                                shunting_yard.add_infix(op, pt, point)?;
                                state = ExpressionState::Infix;
                            }
                            InfixOrPostfix::Postfix(_) => unimplemented!(),
                        }
                        pt = point;
                    }
                    _ => shunting_yard.apply_all()?,
                }
            }
        }
    }
}
```

```
$ rustc --version
rustc 1.18.0-beta.1 (4dce67253 2017-04-25)
 $ rustc -C opt-level=1 -C panic=abort parse.rs 
[...]
$ ./parse
expression_x loop
branch 1
expression_x loop
branch 2
expression_x loop
branch 1
expression_x loop
branch 2
Segmentation fault

```

</details>

**Comment by dwrensha** [comment]
```
$ valgrind ./parse
==1034== Memcheck, a memory error detector
==1034== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==1034== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==1034== Command: ./parse
==1034== 
expression_x loop
branch 1
expression_x loop
branch 2
expression_x loop
branch 1
expression_x loop
branch 2
==1034== Invalid read of size 8
==1034==    at 0x10F2C0: core::ptr::drop_in_place::h4d1aff9439cb72f2 (in /home/dwrensha/Desktop/peresil-segfault/parse)
==1034==    by 0x1: ???
==1034==    by 0x1442C3: ??? (in /home/dwrensha/Desktop/peresil-segfault/parse)
==1034==  Address 0x1 is not stack'd, malloc'd or (recently) free'd
==1034== 
==1034== 
==1034== Process terminating with default action of signal 11 (SIGSEGV)
==1034==  Access not within mapped region at address 0x1
==1034==    at 0x10F2C0: core::ptr::drop_in_place::h4d1aff9439cb72f2 (in /home/dwrensha/Desktop/peresil-segfault/parse)
==1034==    by 0x1: ???
==1034==    by 0x1442C3: ??? (in /home/dwrensha/Desktop/peresil-segfault/parse)
==1034==  If you believe this happened as a result of a stack
==1034==  overflow in your program's main thread (unlikely but
==1034==  possible), you can try to increase the size of the
==1034==  main thread stack using the --main-stacksize= flag.
==1034==  The main thread stack size used in this run was 8388608.
==1034== 
==1034== HEAP SUMMARY:
==1034==     in use at exit: 64 bytes in 2 blocks
==1034==   total heap usage: 7 allocs, 5 frees, 2,032 bytes allocated
==1034== 
==1034== LEAK SUMMARY:
==1034==    definitely lost: 0 bytes in 0 blocks
==1034==    indirectly lost: 0 bytes in 0 blocks
==1034==      possibly lost: 0 bytes in 0 blocks
==1034==    still reachable: 64 bytes in 2 blocks
==1034==         suppressed: 0 bytes in 0 blocks
==1034== Rerun with --leak-check=full to see details of leaked memory
==1034== 
==1034== For counts of detected and suppressed errors, rerun with: -v
==1034== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault

```

**Comment by dwrensha** [comment]
Apparently `panic=abort` is not necessary. I still see the segfault when compiling with

```
rustc -C opt-level=1 src/parse.rs
```

**Comment by kennytm** [comment]
Without `-Cpanic=abort`, segfault only happens at opt-level=1. No repro at 0, 2 or 3.

With `-Cpanic=abort`, segfault happens at opt-level=1,2,3.

**Comment by shepmaster** [comment]
> No repro when -Zsanitizer=address is enabled

@dwrensha and I have been fuzzing my library. I assumed that was the source of this issue, so I'm surprised about that.

**Comment by dwrensha** [comment]
@shepmaster: I hit this bug while running cargo-fuzz with `--sanitizer leak`.

**Comment by kennytm** [comment]
Somewhat reduced, but only repro in `-Copt-level=1 -Cpanic=abort` in nightly (interesting, also in `-Copt-level=2,3 -Cpanic=abort` in stable):

```rust
fn main() {
    let _ = g((0, 0));
}

type P = (u32, u8); // one field must be ≥u32, the other field must be ≥u8
type R = Result<(), P>;

#[allow(dead_code)]
enum X {
    A(Box<X>),
    B(Box<X>),
    C, // B and C can be omitted, but they are added to ensure well-formed semantic
}

enum K {
    D
}

enum E {
    F(K), // must not be built-in type
    #[allow(dead_code)]
    G([X; 2]), // must present, can also be Vec<X> or (X, X), but not X or [X; 1] ...
}

fn g(mut pt: P) -> R {
    let mut y = None;
    loop {
        let status = if pt.0 == 0 {
            Some(E::F(K::D))
        } else {
            None
        };
        pt.0 = 1;

        match status {
            Some(infix_or_postfix) => {
                if let E::F(_op) = infix_or_postfix { // <- must be captured by value
                    y = Some(pt);
                    Ok(())?; // <- yes this line is needed
                }
            }
            _ => {
                Err(y.unwrap())? // <-- must use `?`, return Err won't trigger segfault
            }
        }
    }
}
```

<details>
<summary>Versions</summary>

```
$ rustc +nightly -vV
rustc 1.19.0-nightly (f1140a331 2017-05-08)
binary: rustc
commit-hash: f1140a33176a5fb2e91e26ea3ae42a834dd9bfdf
commit-date: 2017-05-08
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0

$ rustc +stable -vV
rustc 1.17.0 (56124baa9 2017-04-24)
binary: rustc
commit-hash: 56124baa9e73f28c0709e59e74783cf234a978cf
commit-date: 2017-04-24
host: x86_64-apple-darwin
release: 1.17.0
LLVM version: 3.9
```

</details>

**Comment by Mark-Simulacrum** [comment]
Bisection isn't quite working for me, for various reasons (unrelated to the segfault), but I think the failure might have been introduced in the rollup PR #39199. I haven't investigated beyond that, though, and this might be completely wrong.

**Comment by nagisa** [comment]
<details>
<summary>This slightly more minimised sample</summary>

```rust
#![feature(question_mark_carrier)]

fn main() { let _ = g((0, 0)); }

type P = (u32, u8);
// one field must be ≥u32, the other field must be ≥u8
type R = Result<(), P>;
struct K;

#[allow(dead_code)]
enum X {
    A(Box<X>, Box<X>),
    C,
}

enum E {
    F(K), // must not be built-in type
    #[allow(dead_code)]
    G(X), // must present, can also be Vec<X> or (X, X), but not X or [X; 1] ...
}

fn g(mut pt: P) -> R {
    let mut y = (0, 0);
    loop  {
        let status = if pt.0 == 0 {
            Some(E::F(K))
        } else {
            None
        };
        pt.0 = 1;
        match status {
            Some(infix_or_postfix) => match infix_or_postfix {
                E::F(_op) => { // <- must be captured by value
                    y = pt;
                    match Ok(()) {
                        Err(err) => return Err(From::from(err)),
                        Ok(_) => {},
                    };
                }
                _ => (),
            },
            _ => match ::std::ops::Carrier::translate(Err(y)) {
                Err(err) => return Err(From::from(err)),
                Ok(val) => val,
            }
        }
    }
}
```

</details>

results in read of uninitialized memory:

```llvm
define internal void @_ZN5test24main17hd4f6b2920169b984E() unnamed_addr #1 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality {
start:
  %infix_or_postfix.i = alloca %E, align 8         ; alloca a stack slot
  %0 = bitcast %E* %infix_or_postfix.i to i8*      ; for lifetime.end later on
  %1 = getelementptr inbounds %E, %E* %infix_or_postfix.i, i64 0, i32 0  ; discriminant
  %2 = load i64, i64* %1, align 8, !noalias !2     ; read the discriminant
  %cond11.i = icmp eq i64 %2, 0 ; …
  br i1 %cond11.i, label %_ZN5test21g17h3e85430d2d279929E.exit, label %bb3.i21.i ; russian roulette at this point
```

**Comment by dwrensha** [comment]
@nagisa's program reproduces the problem on rustc stable `1.12.1`, but not on `1.11.0`, suggesting that the problem was introduced when rustc switched to MIR.

**Comment by nikomatsakis** [comment]
triage: P-high

Looks bad. @nagisa did an [admirable job reducing](https://github.com/rust-lang/rust/issues/41888#issuecomment-300733182). Hopefully that's indeed the same problem. :)

**Comment by arielb1** [comment]
Turns out we have to clear the ADT master drop flag even if we have 0 variants. Fixed as a commit in #41917 because I am already refactoring this and I don't want to write things twice.

**Comment by lilianmoraru** [comment]
I am not sure if it is the same issue but it is related(opt-level > 0 = SIGSEGV or SIGILL).
This happens on both stable(`rustc 1.17.0 (56124baa9 2017-04-24)`) and nightly(`rustc 1.19.0-nightly (75b056812 2017-05-15)`)
In `Cargo.toml` I have only:
```toml
[package]
name = "load_cpu"
#...
[dependencies]
num_cpus = "1.4.0"
```

In `main.rs`:
```rust
#![allow(unused_variables)]
extern crate num_cpus;

fn main() {
    let cpus = num_cpus::get();
    let mut threads = Vec::with_capacity(cpus);

    for i in 0..cpus {
        threads.push(::std::thread::spawn(|| {
            loop {
                let number = 20000_f64;
                let using = number.sqrt();
            }
        }));
    }

    for thread in threads {
        thread.join().unwrap();
    }
}
```

If I set in `Cargo.toml`:
```
[profile.release]
opt-level = 0
```

And build through `cargo build --release` - running the binary is ok.

If I set `opt-level = 1`, I get `SIGILL` with the messages:
```
fatal runtime error: out of memory
fatal runtime error: out of memory
Illegal instruction
```
and this GDB stacktrace:
```
#0  std::sys::imp::init::oom_handler () at /checkout/src/libstd/sys/unix/mod.rs:89
#1  0x000055555556f4bd in alloc::oom::imp::oom () at /checkout/src/liballoc/oom.rs:41
#2  alloc::oom::oom () at /checkout/src/liballoc/oom.rs:27
#3  0x000055555555b973 in _$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::allocate::h98ae98b690b5a3d6 ()
#4  0x000055555555b859 in _$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::with_capacity::h646536492684a6cd
    ()
#5  0x000055555556f2eb in panic_unwind::__rust_maybe_catch_panic ()
    at /checkout/src/libpanic_unwind/lib.rs:98
#6  0x000055555555b815 in std::panicking::try::h9f2efeaaffe7c6c4 ()
#7  0x000055555555b469 in std::panic::catch_unwind::h3b627ac82596e62b ()
#8  0x000055555555b751 in std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h99fd97c22f4dc633 ()
#9  0x000055555555c519 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h53150036c5a896a3 ()
#10 0x0000555555566626 in alloc::boxed::{{impl}}::call_once<(),()> ()
    at /checkout/src/liballoc/boxed.rs:658
#11 std::sys_common::thread::start_thread () at /checkout/src/libstd/sys_common/thread.rs:21
#12 std::sys::imp::thread::{{impl}}::new::thread_start ()
    at /checkout/src/libstd/sys/unix/thread.rs:84
#13 0x00007ffff77b56ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#14 0x00007ffff72d582d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

With `opt-level > 1`, I get always `SIGSEGV`(`Segmentation fault`), always seeing `jemalloc` here - GDB stacktrace(`opt-level = 2` and `opt-level = 3`):
```
#0  je_rtree_get (dependent=true, key=key@entry=3, rtree=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/rtree.h:325
#1  je_chunk_lookup (dependent=true, ptr=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/chunk.h:89
#2  huge_node_get (ptr=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/src/huge.c:11
#3  je_huge_salloc (tsdn=<optimized out>, ptr=ptr@entry=0x0) at /checkout/src/liballoc_jemalloc/../jemalloc/src/huge.c:455
#4  0x0000555555573953 in je_arena_salloc (demote=false, ptr=0x0, tsdn=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h:1417
#5  je_isalloc (demote=false, ptr=0x0, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1054
#6  rallocx (ptr=0x0, size=9007189332333568, flags=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/src/jemalloc.c:2401
#7  0x000055555555b1ff in _$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::double::h51d74fc503deb7ce ()
#8  0x000055555556e44b in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#9  0x000055555555b612 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hc72d94f6aec109ae ()
#10 0x0000555555565786 in alloc::boxed::{{impl}}::call_once<(),()> () at /checkout/src/liballoc/boxed.rs:658
#11 std::sys_common::thread::start_thread () at /checkout/src/libstd/sys_common/thread.rs:21
#12 std::sys::imp::thread::{{impl}}::new::thread_start () at /checkout/src/libstd/sys/unix/thread.rs:84
#13 0x00007ffff77b56ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#14 0x00007ffff72d582d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by nagisa** [comment]
@lilianmoraru That’s https://github.com/rust-lang/rust/issues/28728.
