### ISSUE TITLE
Incremental ICE: could not find ICH for FileMap

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#42000]
The compiler is a little bit old, but I didn't see any open discussion about this.
```
rustc 1.19.0-dev (1d468400f 2017-05-11)
binary: rustc
commit-hash: 1d468400f5bf205a92eabdededc17e0a2789d651
commit-date: 2017-05-11
host: x86_64-unknown-linux-gnu
release: 1.19.0-dev
LLVM version: 4.0
```

I suspect this becomes broken when I use workspace? I was testing #41369.

```
error: internal compiler error: src/librustc_incremental/calculate_svh/mod.rs:89: Could not find ICH for FileMap(DefId { krate: CrateNum(0), node: DefIndex(0) => cargo/210d1058e686a5256f66a17dfa7d9257 }, "src/cargo/util/machine_message.rs")

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:428
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::bug_fmt
  10: <rustc_incremental::calculate_svh::IncrementalHashesMap as core::ops::Index<&'a rustc::dep_graph::dep_node::DepNode<rustc::hir::def_id::DefId>>>::index
  11: rustc_incremental::persist::hash::HashContext::hash
  12: rustc_incremental::persist::load::decode_dep_graph
  13: rustc_incremental::persist::load::load_dep_graph
  14: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  15: rustc_driver::driver::phase_3_run_analysis_passes
  16: rustc_driver::driver::compile_input
  17: rustc_driver::run_compiler
```
```
error: internal compiler error: src/librustc_incremental/calculate_svh/mod.rs:89: Could not find ICH for FileMap(DefId { krate: CrateNum(0), node: DefIndex(0) => build_script_build/37b2acc0ad68845f8b5fa3c2ff2d64a5-exe }, "/home/ishitatsuyuki/.cargo/git/checkouts/rustfmt-5390e0ead582d971/65e1512/build.rs")

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:428
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::bug_fmt
  10: <rustc_incremental::calculate_svh::IncrementalHashesMap as core::ops::Index<&'a rustc::dep_graph::dep_node::DepNode<rustc::hir::def_id::DefId>>>::index
  11: rustc_incremental::persist::hash::HashContext::hash
  12: rustc_incremental::persist::load::decode_dep_graph
  13: rustc_incremental::persist::load::load_dep_graph
  14: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  15: rustc_driver::driver::phase_3_run_analysis_passes
  16: rustc_driver::driver::compile_input
  17: rustc_driver::run_compiler
```

**Comment by michaelwoerister** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/41873. Would you mind giving it another try with the latest nightly?

**Comment by ishitatsuyuki** [comment]
I have cleaned the directory already, so feel free to close this issue as duplicate.

**Comment by michaelwoerister** [comment]
Thanks, @ishitatsuyuki!
