### ISSUE TITLE
compiler panic: thread 'rustc' panicked at 'already have hash for FileMap(DefId { krate: CrateNum(40), node: DefIndex(0) => yup_oauth2/eca2350967a7ffe9c145bef4f7d7f2ae }, "/src/<proc-macro source code>")', src/librustc_incremental/persist/hash.rs:254

### ISSUE THREAD

**Issue by donhcd** [rust-lang/rust#42107]
compiler panicks when building project.

Relevant logs:
```
   Compiling gcp-apis v0.1.0 (https://github.com/sigmacomputing/gcp-apis.git?rev=281c2ea#281c2eab)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'already have hash for FileMap(DefId { krate: CrateNum(40), node: DefIndex(0) => yup_oauth2/eca2350967a7ffe9c145bef4f7d7f2ae }, "/Users/don/src/qwill/<proc-macro source code>")', src/librustc_incremental/persist/hash.rs:254
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rustc_incremental::persist::hash::HashContext::load_data
   7: rustc_incremental::persist::hash::HashContext::hash
   8: rustc_incremental::persist::save::save_dep_graph
   9: rustc_driver::driver::phase_4_translate_to_llvm
  10: rustc_driver::driver::compile_input::{{closure}}
  11: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  12: rustc_driver::driver::phase_3_run_analysis_passes
  13: rustc_driver::driver::compile_input
  14: rustc_driver::run_compiler

error: Could not compile `gcp-apis`.
```

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0-nightly (0ed1ec9f9 2017-05-18)
binary: rustc
commit-hash: 0ed1ec9f9eb8174273867343d01177b5ac13ff4c
commit-date: 2017-05-18
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0
```

**Comment by donhcd** [comment]
my bad, this seems to be a dupe of https://github.com/rust-lang/rust/issues/42101
