### ISSUE TITLE
Compiler panics when compiling 'core'

### ISSUE THREAD

**Issue by shakram02** [rust-lang/rust#42273]
I was trying to compile redox-os when the compiler panicked
How to reproduce:
```
Run bootstrap setup
$ curl -sf https://raw.githubusercontent.com/redox-os/redox/master/bootstrap.sh -o bootstrap.sh && bash -e bootstrap.sh

#Change to project directory
$ cd redox

# Build Redox
$ make all
```

`rustc --version --verbose`:
```
rustc 1.19.0-nightly (557967766 2017-05-26)
binary: rustc
commit-hash: 557967766be6139bd747ab2c3dc56ff0c9b8852a
commit-date: 2017-05-26
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:473
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::bug_fmt
  10: rustc_typeck::check::FnCtxt::check_struct_path
  11: rustc_typeck::check::FnCtxt::check_expr_kind
  12: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  13: rustc_typeck::check::FnCtxt::check_method_call
  14: rustc_typeck::check::FnCtxt::check_expr_kind
  15: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  16: rustc_typeck::check::FnCtxt::check_block_with_expected::{{closure}}
  17: rustc_typeck::check::FnCtxt::check_block_with_expected
  18: rustc_typeck::check::FnCtxt::check_expr_kind
  19: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  20: rustc_typeck::check::FnCtxt::check_return_expr
  21: rustc_typeck::check::check_fn
  22: rustc_typeck::check::typeck_tables_of::{{closure}}
  23: rustc_typeck::check::typeck_tables_of
  24: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  25: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  26: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  27: rustc_typeck::check::typeck_item_bodies
  28: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get
  29: rustc::ty::maps::TyCtxtAt::typeck_item_bodies
  30: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies
  31: rustc_typeck::check_crate
  32: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  33: rustc_driver::driver::phase_3_run_analysis_passes
  34: rustc_driver::driver::compile_input
  35: rustc_driver::run_compiler

error: Could not compile `core`.
```

**Comment by kennytm** [comment]
Is there any error message *before* the `thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:473` line?

**Comment by shakram02** [comment]
yes
```
mkdir -p build/kernel
RUSTC="./krustc.sh" RUSTDOC="./krustdoc.sh" CARGO_INCREMENTAL=1 cargo rustc --manifest-path rust/src/libcollections/Cargo.toml --target x86_64-unknown-none --release -- -C soft-float -o build/kernel/libcollections.rlib
   Compiling core v0.0.0 (file:///home/ahmed/code/rust/redox/rust/src/libcore)
error: unused macro definition
  --> rust/src/libcore/num/float_macros.rs:13:1
   |
13 | / macro_rules! assert_approx_eq {
14 | |     ($a:expr, $b:expr) => ({
15 | |         use num::Float;
16 | |         let (a, b) = (&$a, &$b);
...  |
19 | |     })
20 | | }
   | |_^
   |
   = note: #[deny(unused_macros)] implied by #[deny(warnings)]
note: lint level defined here
  --> rust/src/libcore/lib.rs:68:9
   |
68 | #![deny(warnings)]
   |         ^^^^^^^^

error: unused macro definition
  --> rust/src/libcore/num/wrapping.rs:15:1
   |
15 | / macro_rules! sh_impl_signed {
16 | |     ($t:ident, $f:ident) => (
17 | |         #[stable(feature = "rust1", since = "1.0.0")]
18 | |         impl Shl<$f> for Wrapping<$t> {
...  |
60 | |     )
61 | | }
   | |_^
   |
   = note: #[deny(unused_macros)] implied by #[deny(warnings)]

error: unused macro definition
   --> rust/src/libcore/num/mod.rs:99:1
    |
99  | / macro_rules! checked_op {
100 | |     ($U:ty, $op:path, $x:expr, $y:expr) => {{
101 | |         let (result, overflowed) = unsafe { $op($x as $U, $y as $U) };
102 | |         if overflowed { None } else { Some(result as Self) }
103 | |     }}
104 | | }
    | |_^
    |
    = note: #[deny(unused_macros)] implied by #[deny(warnings)]

error: unused macro definition
   --> rust/src/libcore/ops.rs:766:1
    |
766 | / macro_rules! neg_impl_unsigned {
767 | |     ($($t:ty)*) => {
768 | |         neg_impl_core!{ x => {
769 | |             !x.wrapping_add(1)
770 | |         }, $($t)*} }
771 | | }
    | |_^
    |
    = note: #[deny(unused_macros)] implied by #[deny(warnings)]

error: internal compiler error: /checkout/src/librustc_typeck/check/mod.rs:3295: unexpected definition: Enum(DefId { krate: CrateNum(0), node: DefIndex(13457) => core/912dd31c2582a9b9a1af69a0b75b641c::ops[0]::RangeInclusive[0] })
```

**Comment by eddyb** [comment]
@shakram02 Only the very last line is interesting. But it really sounds like you're using the wrong version of `libcore` for that compiler.

**Comment by shakram02** [comment]
I haven't changed any settings, ( actually I'm still a newbie and don't know how ), how can I provide more info about it ? ( if that will help )

**Comment by eddyb** [comment]
I mean that redox isn't using the `libcore` from *the exact source* of the compiler you're using. Nothing else is supported.

**Comment by shakram02** [comment]
aha, thank you so much for the info, I'll close this issue then

**Comment by eddyb** [comment]
In more detail: `RangeInclusive` has changed from an `enum` to a `struct` recently, and while name resolution catches the difference earlier for *user code*, the compiler desugars to the exact definition.

**Comment by shakram02** [comment]
sounds interesting, hopefully I'll hack on rust compiler someday, that'll be awesome. I'll keep messing around until then, it's very kind of you to provide the explanation, thanks!
