### ISSUE TITLE
Rust 1.19 regression, milagro-crypto 0.1.13

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42461]
Unfortunately the source repo is not listed, but here's what cargobomb saw

```
Jun 03 16:49:30.103 INFO testing milagro-crypto-0.1.13 against nightly for nightly-2017-06-01
Jun 03 16:49:30.103 INFO running: cargo +nightly build --frozen
Jun 03 16:49:30.103 INFO creating container for: cargo +nightly build --frozen
Jun 03 16:49:30.103 INFO running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly-2017-06-01/nightly:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly-2017-06-01/nightly:/target:rw -e USER_ID=500 -e CMD=cargo +nightly build --frozen cargobomb`
Jun 03 16:49:30.180 INFO blam! 944fea8b0ad02c46169bc87a8f40983afc816e91803fb459590013db4d34d547
Jun 03 16:49:30.181 INFO running `docker start -a 944fea8b0ad02c46169bc87a8f40983afc816e91803fb459590013db4d34d547`
Jun 03 16:49:30.650 INFO kablam!    Compiling milagro-crypto v0.1.13 (file:///source)
Jun 03 16:49:37.399 INFO kablam!     Finished dev [unoptimized + debuginfo] target(s) in 6.74 secs
Jun 03 16:49:37.402 INFO kablam! su: No module specific data is present
Jun 03 16:49:37.735 INFO running `docker rm -f 944fea8b0ad02c46169bc87a8f40983afc816e91803fb459590013db4d34d547`
Jun 03 16:49:37.751 INFO blam! 944fea8b0ad02c46169bc87a8f40983afc816e91803fb459590013db4d34d547
Jun 03 16:49:37.751 INFO running: cargo +nightly test --frozen --no-run
Jun 03 16:49:37.751 INFO creating container for: cargo +nightly test --frozen --no-run
Jun 03 16:49:37.751 INFO running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly-2017-06-01/nightly:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly-2017-06-01/nightly:/target:rw -e USER_ID=500 -e CMD=cargo +nightly test --frozen --no-run cargobomb`
Jun 03 16:49:37.834 INFO blam! cdb6d92c8d8ce53faa0d81d0d7beec63bdec7d9c537cd45f4d9bcefaa16c891f
Jun 03 16:49:37.834 INFO running `docker start -a cdb6d92c8d8ce53faa0d81d0d7beec63bdec7d9c537cd45f4d9bcefaa16c891f`
Jun 03 16:49:38.163 INFO kablam!    Compiling milagro-crypto v0.1.13 (file:///source)
Jun 03 16:49:40.362 INFO kablam!     Finished dev [unoptimized + debuginfo] target(s) in 2.20 secs
Jun 03 16:49:40.366 INFO kablam! su: No module specific data is present
Jun 03 16:49:40.755 INFO running `docker rm -f cdb6d92c8d8ce53faa0d81d0d7beec63bdec7d9c537cd45f4d9bcefaa16c891f`
Jun 03 16:49:40.771 INFO blam! cdb6d92c8d8ce53faa0d81d0d7beec63bdec7d9c537cd45f4d9bcefaa16c891f
Jun 03 16:49:40.772 INFO running: cargo +nightly test --frozen
Jun 03 16:49:40.772 INFO creating container for: cargo +nightly test --frozen
Jun 03 16:49:40.772 INFO running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly-2017-06-01/nightly:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly-2017-06-01/nightly:/target:rw -e USER_ID=500 -e CMD=cargo +nightly test --frozen cargobomb`
Jun 03 16:49:40.837 INFO blam! 1eeee8d63fcc5958593c2f92ea1dd5612229b85a6f6081103814abebbf90885a
Jun 03 16:49:40.837 INFO running `docker start -a 1eeee8d63fcc5958593c2f92ea1dd5612229b85a6f6081103814abebbf90885a`
Jun 03 16:49:41.323 INFO kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Jun 03 16:49:41.324 INFO kablam!      Running /target/debug/deps/milagro_crypto-f2414ca2f8c916d9
Jun 03 16:49:41.325 INFO blam! 
Jun 03 16:49:41.325 INFO blam! running 46 tests
Jun 03 16:49:41.326 INFO blam! test big::tests::test_bytes ... ok
Jun 03 16:49:41.326 INFO blam! test big::tests::test_big_hex_io ... ok
Jun 03 16:49:41.326 INFO blam! test ecp::tests::test_eq ... ok
Jun 03 16:49:41.327 INFO blam! test big::tests::test_big_random ... ok
Jun 03 16:49:41.327 INFO blam! test ecp::tests::test_new_bigs ... ok
Jun 03 16:49:41.327 INFO blam! test ff::overloading::tests::mul_test ... ok
Jun 03 16:49:41.327 INFO blam! test big::wrappers::tests::test_hex ... ok
Jun 03 16:49:41.328 INFO blam! test ff::overloading::tests::sub_assign_test ... ok
Jun 03 16:49:41.328 INFO blam! test ff::overloading::tests::sub_test ... ok
Jun 03 16:49:41.328 INFO blam! test ff::overloading::tests::plus_assign_test ... ok
Jun 03 16:49:41.328 INFO blam! test ecp2::tests::test_ecp2_hex_io ... ok
Jun 03 16:49:41.328 INFO blam! test ff::overloading::tests::mul_assign_test ... ok
Jun 03 16:49:41.328 INFO blam! test ff::tests::inv_test ... ok
Jun 03 16:49:41.329 INFO blam! test ff::overloading::tests::plus_test ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::plus_test ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::mul_test ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::test_ff_inc ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::sub_test ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::test_ff_io ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::test_copy ... ok
Jun 03 16:49:41.329 INFO blam! test ff::tests::test_ff_modulus ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_bytes ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_add ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_compare ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_mul ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_set_size ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_io_sized_bytes ... ok
Jun 03 16:49:41.330 INFO blam! test ff::tests::test_ff_io_sized_hex ... ok
Jun 03 16:49:41.332 INFO blam! test ff::wrappers::tests::test_more_ops ... ok
Jun 03 16:49:41.335 INFO blam! test ff::tests::test_ff_randomN ... ok
Jun 03 16:49:41.336 INFO blam! test ff::tests::test_ff_randoms ... ok
Jun 03 16:49:41.337 INFO blam! test ff::tests::test_ff_sub ... ok
Jun 03 16:49:41.337 INFO blam! test fp12::tests::test_eq ... ok
Jun 03 16:49:41.338 INFO kablam! error: process didn't exit successfully: `/target/debug/deps/milagro_crypto-f2414ca2f8c916d9` (signal: 11, SIGSEGV: invalid memory reference)
Jun 03 16:49:41.338 INFO kablam! 
Jun 03 16:49:41.338 INFO kablam! To learn more, run the command again with --verbose.
Jun 03 16:49:41.341 INFO kablam! su: No module specific data is present
Jun 03 16:49:41.684 INFO running `docker rm -f 1eeee8d63fcc5958593c2f92ea1dd5612229b85a6f6081103814abebbf90885a`
Jun 03 16:49:41.700 INFO blam! 1eeee8d63fcc5958593c2f92ea1dd5612229b85a6f6081103814abebbf90885a
```

Another report of sigsigv [here](https://github.com/rust-lang/rust/issues/42459) but not obviously related.

**Comment by Mark-Simulacrum** [comment]
Segfault appears to be non-deterministic, and not in rust code -- backtrace is below. I don't think this is our fault, and I was able to reproduce with stable (also non-deterministically). I propose we close as won't fix -- doesn't appear to be a regression, and is in C code.

```
#0  0x000055ed856cc059 in BIG_fshl ()
#1  0x000055ed856ccb50 in BIG_mod ()
#2  0x000055ed856b36dd in milagro_crypto::big::{{impl}}::rmod (b=0x7ffacabfb308, c=0x55ed85757980 <CURVE_Order>) at src/big/mod.rs:220
#3  0x000055ed856b3b51 in milagro_crypto::big::{{impl}}::randomnum (q=0x55ed85757980 <CURVE_Order>, rng=0x7ffacabfb460) at src/big/mod.rs:322
#4  0x000055ed856b48b7 in milagro_crypto::big::tests::test_random_mod_order () at src/big/mod.rs:402
#5  0x000055ed856e5f02 in test::run_test::{{closure}} () at /checkout/src/libtest/lib.rs:1451
#6  core::ops::FnOnce::call_once<closure,(())> () at /checkout/src/libcore/ops.rs:2683
#7  test::{{impl}}::call_box<(),closure> () at /checkout/src/libtest/lib.rs:140
#8  0x000055ed857219fb in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#9  0x000055ed856da3d4 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> () at /checkout/src/libstd/panicking.rs:433
#10 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> () at /checkout/src/libstd/panic.rs:361
#11 test::run_test::run_test_inner::{{closure}} () at /checkout/src/libtest/lib.rs:1390
#12 std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> () at /checkout/src/libstd/sys_common/backtrace.rs:136
#13 0x000055ed856db173 in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> () at /checkout/src/libstd/thread/mod.rs:364
#14 std::panic::{{impl}}::call_once<(),closure> () at /checkout/src/libstd/panic.rs:296
#15 std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> () at /checkout/src/libstd/panicking.rs:454
#16 0x000055ed857219fb in panic_unwind::__rust_maybe_catch_panic () at /checkout/src/libpanic_unwind/lib.rs:98
#17 0x000055ed856e10fd in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> () at /checkout/src/libstd/panicking.rs:433
#18 std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> () at /checkout/src/libstd/panic.rs:361
#19 std::thread::{{impl}}::spawn::{{closure}}<closure,()> () at /checkout/src/libstd/thread/mod.rs:363
#20 alloc::boxed::{{impl}}::call_box<(),closure> () at /checkout/src/liballoc/boxed.rs:648
#21 0x000055ed85719826 in alloc::boxed::{{impl}}::call_once<(),()> () at /checkout/src/liballoc/boxed.rs:658
#22 std::sys_common::thread::start_thread () at /checkout/src/libstd/sys_common/thread.rs:21
#23 std::sys::imp::thread::{{impl}}::new::thread_start () at /checkout/src/libstd/sys/unix/thread.rs:84
#24 0x00007ffacc09e6ba in start_thread (arg=0x7ffacabfc700) at pthread_create.c:333
#25 0x00007ffacbbbe82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
