### ISSUE TITLE
Missing serialization in Rustc (TyS)?

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust#42672]
Hi,

(Let me first apologise for not knowing how to build a minimal runnable example. I'm working in an MIR pass...)

I've been playing around inside rustc. I needed the ability to save away the MIR of each BasicBlock, (I intend for another program to load them in later).

I was pleased to find the `RustcEncodable` and `RustcDecodable` traits, and furthermore that the MIR `Statement` type implement these traits:

```
#[derive(Clone, RustcEncodable, RustcDecodable)] 
pub struct Statement<'tcx> {
    pub source_info: SourceInfo,
    pub kind: StatementKind<'tcx>,
}
```

This suggests that statements are intended to be serialized/deserialized. It follows that I should be able to encode statements as JSON. I tried the following in my MIR pass:

``` 
 // bb_data is a BasicBlockData struct from the MIR
let js = json::encode(&bb_data.statements);                         
if js.is_ok() {                                                     
    println!("{}", js.unwrap());                                                                           
} else {
    println!("can't serialize");
}
```

This compiles, but if I use the resulting rustc to build my test program, rustc panics:
```
thread 'rustc' panicked at 'missing specializaiton: `<serialize::json::Encoder as SpecializedEncoder<&rustc::ty::TyS>>::specialized_encode` not overriden', src/libserialize/serialize.rs:740
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: <T as serialize::serialize::Encodable>::encode
   8: <rustc::mir::ProjectionElem<'tcx, V> as serialize::serialize::Encodable>::encode
   9: <serialize::json::Encoder<'a> as serialize::serialize::Encoder>::emit_struct_field
  10: <rustc::mir::Lvalue<'tcx> as serialize::serialize::Encodable>::encode
  11: <serialize::json::Encoder<'a> as serialize::serialize::Encoder>::emit_enum_variant
  12: <rustc::mir::Operand<'tcx> as serialize::serialize::Encodable>::encode
  13: <rustc::mir::StatementKind<'tcx> as serialize::serialize::Encodable>::encode
  14: <rustc_mir::transform::metarust_block_marker::BlockMarkerPass as rustc::mir::transform::MirPass>::run_pass
  15: rustc_mir::transform::run_suite
  16: rustc_mir::transform::mir_const
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_const<'tcx>>::try_get
  18: rustc::ty::maps::TyCtxtAt::mir_const
  19: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_const
  20: rustc_mir::transform::mir_validated
  21: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_validated<'tcx>>::try_get
  22: rustc::ty::maps::TyCtxtAt::mir_validated
  23: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_validated
  24: rustc_borrowck::borrowck::borrowck
  25: rustc::ty::maps::<impl rustc::ty::maps::queries::borrowck<'tcx>>::try_get
  26: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::borrowck
  27: rustc_borrowck::borrowck::check_crate
  28: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  29: rustc_driver::driver::phase_3_run_analysis_passes
  30: rustc_driver::driver::compile_input
  31: rustc_driver::run_compiler
```

Alright, so the compiler doesn't know how to serialize a `TyS`. If I derive the serialization implementations for this type:

```diff
+#[derive(RustcEncodable, RustcDecodable)]
 pub struct TyS<'tcx> {
     pub sty: TypeVariants<'tcx>,
     pub flags: TypeFlags,
```

This gives a compile-time error for the MIR pass:

```
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc v0.0.0 (file:///home/vext01/research/metarust/src/librustc)
error[E0277]: the trait bound `ty::TypeFlags: serialize::UseSpecializedEncodable` is not satisfied
   --> src/librustc/ty/mod.rs:446:10
    |
446 | #[derive(RustcEncodable, RustcDecodable)]
    |          ^^^^^^^^^^^^^^ the trait `serialize::UseSpecializedEncodable` is not implemented for `ty::TypeFlags`
    |
    = note: required because of the requirements on the impl of `serialize::Encodable` for `ty::TypeFlags`
    = note: required by `serialize::Encodable::encode`

error[E0277]: the trait bound `ty::TypeFlags: serialize::UseSpecializedDecodable` is not satisfied
   --> src/librustc/ty/mod.rs:446:26
    |
446 | #[derive(RustcEncodable, RustcDecodable)]
    |                          ^^^^^^^^^^^^^^ the trait `serialize::UseSpecializedDecodable` is not implemented for `ty::TypeFlags`
    |
    = note: required because of the requirements on the impl of `serialize::Decodable` for `ty::TypeFlags`
    = note: required by `serialize::Decodable::decode`

error: aborting due to 2 previous errors
```

Alright, let's do the same for `TypeFlags`:

```diff
 bitflags! {
+    #[derive(RustcEncodable, RustcDecodable)]
     flags TypeFlags: u32 {
         const HAS_PARAMS         = 1 << 0,
         const HAS_SELF           = 1 << 1,
```

This makes rustc fail to compile like this:
```
thread 'rustc' panicked at 'internal error: entered unreachable code', src/librustc/hir/mod.rs:681
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: serialize::serialize::Decoder::read_enum_variant_arg
   7: <rustc_metadata::decoder::DecodeContext<'a, 'tcx> as serialize::serialize::SpecializedDecoder<&'tcx
 rustc::ty::TyS<'tcx>>>::specialized_decode
   8: rustc_metadata::decoder::<impl rustc_metadata::cstore::CrateMetadata>::get_type
   9: rustc_metadata::cstore_impl::provide::type_of
  10: rustc::ty::maps::<impl rustc::ty::maps::queries::type_of<'tcx>>::try_get
  11: rustc::ty::trait_def::trait_impls_of_provider
  12: rustc::ty::maps::<impl rustc::ty::maps::queries::trait_impls_of<'tcx>>::try_get
  13: rustc::ty::maps::TyCtxtAt::trait_impls_of
  14: rustc::ty::trait_def::relevant_trait_impls_provider
  15: rustc::ty::maps::<impl rustc::ty::maps::queries::relevant_trait_impls_for<'tcx>>::try_get
  16: rustc::ty::maps::TyCtxtAt::relevant_trait_impls_for
  17: rustc::traits::select::SelectionContext::assemble_candidates_from_impls
  18: rustc::traits::select::SelectionContext::assemble_candidates
  19: rustc::traits::select::SelectionContext::candidate_from_obligation
  20: rustc::traits::select::SelectionContext::select
  21: rustc_typeck::check::coercion::Coerce::coerce
  22: rustc_typeck::check::coercion::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::try_coerce
  23: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::demand_coerce
  24: rustc_typeck::check::typeck_tables_of::{{closure}}
  25: rustc_typeck::check::typeck_tables_of
  26: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  27: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  28: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  29: rustc_const_eval::eval::const_eval
  30: rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::try_get
  31: rustc::ty::maps::TyCtxtAt::const_eval
  32: rustc::middle::const_val::eval_length
  33: <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_ty_to_ty
  34: rustc_typeck::collect::type_of
  35: rustc::ty::maps::<impl rustc::ty::maps::queries::type_of<'tcx>>::try_get
  36: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::type_of
  37: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>
::visit_item
  38: rustc_typeck::check_crate::{{closure}}::{{closure}}
  39: rustc_typeck::check_crate
  40: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  41: rustc_driver::driver::phase_3_run_analysis_passes
  42: rustc_driver::driver::compile_input
  43: rustc_driver::run_compiler
```

Before I go deeper down the rabbit hole. Is this a real bug? Should I be able to encode/decode MIR statements?

Thanks

**Comment by TimNN** [comment]
I personally wouldn't consider this a bug and don't think mir was meant to be accessed like this. You may have some luck by looking at https://github.com/rust-lang/rust/blob/master/src/librustc_mir/util/pretty.rs.

**Comment by Mark-Simulacrum** [comment]
I don't believe it's intended to save MIR in some form to disk for loading by rustc or other programs. While incremental compilation sort of does this, it's level isn't quite the same as here, I believe.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close, please ask on internals.rust-lang.org or on IRC (irc.mozilla.org, #rust-internals, #rustc).
