### ISSUE TITLE
rustc 1.16.0 test failure - run-make/linker-output-non-utf8

### ISSUE THREAD

**Issue by daym** [rust-lang/rust#42713]
We are trying to enable rustc tests in the Guix distribution and are now down to two test failures total.

One test failure is in run-make/linker-output-non-utf8.

This seems to test whether funny characters in directory names work.

Unfortunately I don't know what the cause is (i.e. which other package we should update). Therefore I ask here: What can I do about it? The person who wrote the test probably knows :)

I've found https://github.com/rust-lang/rust/issues/29122 https://github.com/wthrowe/rust/commit/19664fdf8d1b8fc5fd3b359c2440625b2b4d8cec  https://github.com/rust-lang/rust/pull/29134 about it.

Output follows:
```
test [run-make] run-make/linker-output-non-utf8 ... FAILED
---- [run-make] run-make/linker-output-non-utf8 stdout ----
        
error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
make[1]: Entering directory '/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/src/test/run-make/linker-output-non-utf8'
LD_LIBRARY_PATH="/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu:/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage2/lib:/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage2/lib:/gnu/store/ad2cqzpfvcs08iackla9npif4k1nsqad-llvm-3.9.1/lib:" '/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu -L /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu  library.rs
mkdir /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu/zzz$'\xff'
mv /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu/liblibrary.a /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu/zzz$'\xff'
LIBRARY_PATH=/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu/zzz$'\xff' LD_LIBRARY_PATH="/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu:/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage2/lib:/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage2/lib:/gnu/store/ad2cqzpfvcs08iackla9npif4k1nsqad-llvm-3.9.1/lib:" '/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu -L /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/x86_64-unknown-linux-gnu/test/run-make/linker-output-non-utf8.stage2-x86_64-unknown-linux-gnu  exec.rs 2>&1 | grep this_symbol_not_defined
make[1]: Leaving directory '/tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/src/test/run-make/linker-output-non-utf8'

------------------------------------------
stderr:
------------------------------------------
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
note: link against the following native artifacts when linking against this static library

note: the order and any duplication can be significant on some platforms, and so may need to be preserved

note: library: dl

note: library: pthread

note: library: gcc_s

note: library: c

note: library: m

note: library: rt

note: library: util

make[1]: *** [Makefile:22: all] Error 1

------------------------------------------

thread '[run-make] run-make/linker-output-non-utf8' panicked at 'explicit panic', /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/src/tools/compiletest/src/runtest.rs:2474
stack backtrace:
   1:     0x7ffff7499d4c - std::sys::imp::backtrace::tracing::imp::write::h59f11508bbbb14ed
                        at /tmp/guix-build-rustc-1.16.0.drv-0/rustc-1.16.0-src/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
```

**Comment by daym** [comment]
Our linker requires LIBRARY_PATH to find system libraries. Please don't clobber it (amending it is fine).

**Comment by daym** [comment]
Seems to be a problem in Guix's ld wrapper. Investigating...
