### ISSUE TITLE
Rust 1.19/1.20 regression, cargo-check

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42844]
https://github.com/rsolomo/cargo-check

```
brian@ip-10-145-43-250:/mnt2/dev/cargo-check⟫ git log -1
commit ce05b428822f18fe89f42c39436b7b53d9ddb15a
Merge: d446f78 8452a90
Author: Ray Solomon <raybsolomon@gmail.com>
Date:   Mon Jan 2 11:03:39 2017 -0800

    Merge pull request #21 from alexcrichton/fix-beta

    Fix tests on beta
```

Obviously this crate is doing deep integration with cargo, but it behaves differently on all three channels:

Beta:

```
running 5 tests
    Blocking waiting for file lock on build directory
   Compiling multitarget v0.1.0 (file:///mnt2/dev/cargo-check/tests/fixtures/multitarget)
   Compiling multitarget v0.1.0 (file:///mnt2/dev/cargo-check/tests/fixtures/multitarget)
error: the option `Z` is only accepted on the nightly compiler

error: the option `Z` is only accepted on the nightly compiler

error: Could not compile `multitarget`.

To learn more, run the command again with --verbose.
error: Could not compile `multitarget`.

To learn more, run the command again with --verbose.
test multiple_targets_4 ... FAILED
test multiple_targets ... FAILED
   Compiling multitarget v0.1.0 (file:///mnt2/dev/cargo-check/tests/fixtures/multitarget)
error: the option `Z` is only accepted on the nightly compiler

error: Could not compile `multitarget`.

To learn more, run the command again with --verbose.
test multiple_targets_2 ... ok
   Compiling cargo-check v0.2.2 (file:///mnt2/dev/cargo-check)
test multiple_targets_3 ... FAILED
error: the option `Z` is only accepted on the nightly compiler

error: Could not compile `cargo-check`.

To learn more, run the command again with --verbose.
test self_test ... FAILED

failures:

---- multiple_targets_4 stdout ----
        thread 'multiple_targets_4' panicked at 'assertion failed: status.success()', tests/multitarget.rs:88
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- multiple_targets stdout ----
        thread 'multiple_targets' panicked at 'assertion failed: status.success()', tests/multitarget.rs:37

---- multiple_targets_3 stdout ----
        thread 'multiple_targets_3' panicked at 'assertion failed: output.contains("no associated item")', tests/multitarget.rs:70

---- self_test stdout ----
        thread 'self_test' panicked at 'assertion failed: status.success()', tests/multitarget.rs:23


failures:
    multiple_targets
    multiple_targets_3
    multiple_targets_4
    self_test

test result: FAILED. 1 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test multitarget'
```

Nightly:

```
101 brian@ip-10-145-43-250:/mnt2/dev/cargo-check⟫ cargo +nightly test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/cargo_check-b85bd87650eafed9

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/multitarget-5188c670dfaf0624

running 5 tests
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
    Finished release [optimized] target(s) in 0.0 secs
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
    Blocking waiting for file lock on build directory
    Blocking waiting for file lock on build directory
   Compiling multitarget v0.1.0 (file:///mnt2/dev/cargo-check/tests/fixtures/multitarget)
test multiple_targets_3 ... FAILED
    Finished release [optimized] target(s) in 0.41 secs
test multiple_targets_4 ... ok
   Compiling multitarget v0.1.0 (file:///mnt2/dev/cargo-check/tests/fixtures/multitarget)
    Finished dev [unoptimized + debuginfo] target(s) in 0.46 secs
test multiple_targets ... ok
   Compiling cargo-check v0.2.2 (file:///mnt2/dev/cargo-check)
   Compiling multitarget v0.1.0 (file:///mnt2/dev/cargo-check/tests/fixtures/multitarget)
error[E0425]: cannot find function `helloworld` in module `multitarget`
 --> src/main.rs:5:34
  |
5 |     println!("{}", &multitarget::helloworld());
  |                                  ^^^^^^^^^^ did you mean `hello_world`?

error: aborting due to previous error(s)

error: Could not compile `multitarget`.

To learn more, run the command again with --verbose.
test multiple_targets_2 ... ok
    Finished dev [unoptimized + debuginfo] target(s) in 0.65 secs
   Compiling cargo-check v0.2.2 (file:///mnt2/dev/cargo-check)
    Finished dev [unoptimized + debuginfo] target(s) in 0.53 secs
test self_test ... ok

failures:

---- multiple_targets_3 stdout ----
        thread 'multiple_targets_3' panicked at 'assertion failed: output.contains("no associated item")', tests/multitarget.rs:70
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    multiple_targets_3

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test multitarget'
```

cc @rslomo

**Comment by mattico** [comment]
cc @rsolomo :)

**Comment by durka** [comment]
I think since `cargo check` became a native command and `-Z` was removed (unfortunately), this crate is supposed to be deprecated.

**Comment by rsolomo** [comment]
Yeah, I've been using the more native `cargo check` these days. I should probably deprecate that project.

**Comment by nikomatsakis** [comment]
Seems like this is expected breakage, no? I'm thinking we should close, and just recommend people use the native `cargo check`.
