### ISSUE TITLE
NulError when using rustc with external llvm

### ISSUE THREAD

**Issue by johanneskoester** [rust-lang/rust#43311]
We are trying to package rust for the conda package manager. For that, we use an external llvm build. We can successfully compile rustc and cargo for both osx and linux64 (CentOS 6), however, when trying to use the resulting binaries to build crates, we get the following error:
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0, 0, 0, 0, 0, 0, 0, 0, 0])', src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/sys_common/backtrace.rs:60
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rustc_trans::type_::Type::named_struct
  11: rustc_trans::context::LocalCrateContext::new
  12: rustc_trans::base::trans_crate
  13: rustc_driver::driver::phase_4_translate_to_llvm
  14: rustc_driver::driver::compile_input::{{closure}}
  15: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  16: rustc::ty::context::TyCtxt::create_and_enter
  17: rustc_driver::driver::phase_3_run_analysis_passes
  18: rustc_driver::driver::compile_input
  19: rustc_driver::run_compiler
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libpanic_unwind/lib.rs:98
  22: <F as alloc::boxed::FnBox<A>>::call_box
  23: std::sys::imp::thread::Thread::new::thread_start
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/liballoc/boxed.rs:650
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/sys_common/thread.rs:21
             at /feedstock_root/build_artefacts/rust_1500377496458/work/rustc-1.18.0-src/src/libstd/sys/unix/thread.rs:84
  24: start_thread
  25: __clone

error: Could not compile `void`.
```

This happens for any crate.

xref: conda-forge/rust-feedstock#1

Has it something to do with our external llvm build?  We are using llvm 3.9. Are we missing an important flag? Any help would be greatly appreciated!

**Comment by Mark-Simulacrum** [comment]
To clarify, are you building Rust locally or are you using an alternate method? It might be helpful if you could give us the steps to reproduce this on a clean ubuntu install, or something similar to it... This may be resolved with our update to LLVM 4.0 in the next stable release (this Thursday), not sure -- hard to tell based on the pull request.

**Comment by johanneskoester** [comment]
This is what we do for building:

```
#!/bin/bash -e

##### build rustc

./configure --disable-codegen-tests --prefix=$PREFIX --llvm-root=$PREFIX
make
make install


##### build cargo

cd cargo
# use stage0 from rustc build
STAGE0=$(echo ../build/*/stage0/bin)

PATH=$STAGE0:$PATH cargo install --root $PREFIX
```

Thereby, --llvm-root points to an external build of llvm 3.9.

**Comment by Enselic** [comment]
Is this still a problem that needs to be solved? [This comment ](https://github.com/conda-forge/rust-feedstock/issues/3#issuecomment-428949258) indicates that this is no problem any longer.

**Comment by Enselic** [comment]
Triage: Closing. Feel free to reopen if this is still a problem.
