### ISSUE TITLE
internal compiler error: anonymous bound region BrAnon(1) in return but not args

### ISSUE THREAD

**Issue by rillian** [rust-lang/rust#43599]
rustc 1.21.0-nightly (37c7d0ebb 2017-07-31) fails to compile today's Firefox.
```
 3:02.19 error: internal compiler error: /checkout/src/librustc_typeck/astconv.rs:1267: anonymous bound region BrAnon(1) in return but not args
 3:02.19    --> /home/giles/firefox/obj-x86_64-pc-linux-gnu/toolkit/library/x86_64-unknown-linux-gnu/debug/build/style-b88ec12e074624e1/out/gecko/bindings.rs:523:9
 3:02.19     |
 3:02.19 523 |      -> RawGeckoNodeBorrowedOrNull;
 3:02.19     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
 3:02.19 
 3:02.19 note: the compiler unexpectedly panicked. this is a bug.
 3:02.20 
 3:02.20 note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
 3:02.20 
 3:02.20 note: rustc 1.21.0-nightly (37c7d0ebb 2017-07-31) running on x86_64-unknown-linux-gnu
 3:02.20 
 3:02.20 note: run with `RUST_BACKTRACE=1` for a backtrace
 3:02.20 
 3:02.20 thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
 3:02.20 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 3:02.20 stack backtrace:
 3:02.20    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
 3:02.20              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
 3:02.20    1: std::sys_common::backtrace::_print
 3:02.20              at /checkout/src/libstd/sys_common/backtrace.rs:71
 3:02.20    2: std::panicking::default_hook::{{closure}}
 3:02.20              at /checkout/src/libstd/sys_common/backtrace.rs:60
 3:02.20              at /checkout/src/libstd/panicking.rs:380
 3:02.20    3: std::panicking::default_hook
 3:02.20              at /checkout/src/libstd/panicking.rs:390
 3:02.20    4: std::panicking::rust_panic_with_hook
 3:02.20              at /checkout/src/libstd/panicking.rs:610
 3:02.20    5: std::panicking::begin_panic
 3:02.20    6: rustc_errors::Handler::span_bug
 3:02.20    7: rustc::session::opt_span_bug_fmt::{{closure}}
 3:02.20    8: rustc::session::span_bug_fmt
 3:02.20    9: <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ty_of_fn
 3:02.20   10: rustc_typeck::collect::fn_sig
 3:02.20   11: rustc::dep_graph::graph::DepGraph::with_task
 3:02.20   12: rustc::ty::maps::<impl rustc::ty::maps::queries::fn_sig<'tcx>>::try_get
 3:02.20   13: rustc::ty::maps::TyCtxtAt::fn_sig
 3:02.20   14: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::fn_sig
 3:02.20   15: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
 3:02.20   16: rustc_typeck::check_crate::{{closure}}::{{closure}}
 3:02.20   17: rustc_typeck::check_crate
 3:02.20   18: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
 3:02.20   19: rustc_driver::driver::phase_3_run_analysis_passes
 3:02.20   20: rustc_driver::driver::compile_input
 3:02.20   21: rustc_driver::run_compiler
 3:02.20 
 3:02.20 error: Could not compile `style`.
```

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/43567. Thanks!
