### ISSUE TITLE
Nightly is panicking on mozilla-inbound 901c59d3ab9f (stylo)

### ISSUE THREAD

**Issue by gcp** [rust-lang/rust#43638]
``` 
 9:11.53    Compiling regex v0.2.1
 9:11.53    Compiling gleam v0.4.7
 9:11.53    Compiling encoding_glue v0.1.0 (file:///home/morbo/hg/firefox/intl/encoding_glue)
 9:11.53    Compiling syntex_syntax v0.58.1
 9:11.53    Compiling phf_codegen v0.7.21
 9:11.53    Compiling rayon v0.8.1
 9:11.54    Compiling rust_url_capi v0.0.1 (file:///home/morbo/hg/firefox/netwerk/base/rust-url-capi)
 9:11.54    Compiling selectors v0.19.0 (file:///home/morbo/hg/firefox/servo/components/selectors)
 9:11.54    Compiling cssparser-macros v0.3.0
 9:11.54    Compiling serde_derive_internals v0.15.1
 9:11.54    Compiling synstructure v0.5.2
 9:11.54    Compiling cssparser v0.18.2
 9:11.54    Compiling env_logger v0.4.1
 9:11.54    Compiling style_derive v0.0.1 (file:///home/morbo/hg/firefox/servo/components/style_derive)
 9:11.54    Compiling serde_derive v1.0.8
 9:11.54    Compiling serde v1.0.8
 9:11.54    Compiling aster v0.41.0
 9:11.54    Compiling quasi v0.32.0
 9:11.54    Compiling syntex v0.58.1
 9:11.54    Compiling quasi_codegen v0.32.0
 9:11.54    Compiling bincode v0.8.0
 9:11.54    Compiling app_units v0.5.2
 9:11.54    Compiling euclid v0.15.1
 9:11.54    Compiling plane-split v0.6.0
 9:11.54    Compiling style_traits v0.0.1 (file:///home/morbo/hg/firefox/servo/components/style_traits)
 9:11.54    Compiling webrender_api v0.48.0 (file:///home/morbo/hg/firefox/gfx/webrender_api)
 9:11.54    Compiling bindgen v0.29.0
 9:11.54 warning: doc comment not used by rustdoc
 9:11.54    --> /home/morbo/hg/firefox/gfx/webrender/src/render_task.rs:186:9
 9:11.54     |
 9:11.54 186 |         /// Filter out all the clip instances that don't contribute to the result
 9:11.54     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 9:11.54     |
 9:11.54     = note: #[warn(unused_doc_comment)] on by default
 9:11.54 
 9:11.54    Compiling style v0.0.1 (file:///home/morbo/hg/firefox/servo/components/style)
 9:11.55    Compiling webrender_bindings v0.1.0 (file:///home/morbo/hg/firefox/gfx/webrender_bindings)
 9:11.55 error: internal compiler error: /checkout/src/librustc_typeck/astconv.rs:1267: anonymous bound region BrAnon(1) in return but not args
 9:11.55    --> /home/morbo/ff-out/toolkit/library/x86_64-unknown-linux-gnu/debug/build/style-8c0d191974b0de51/out/gecko/bindings.rs:527:9
 9:11.55     |
 9:11.55 527 |      -> RawGeckoNodeBorrowedOrNull;
 9:11.55     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
 9:11.55 
 9:11.55 note: the compiler unexpectedly panicked. this is a bug.
 9:11.55 
 9:11.55 note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
 9:11.55 
 9:11.55 note: rustc 1.21.0-nightly (1d2a6df38 2017-08-03) running on x86_64-unknown-linux-gnu
 9:11.55 
 9:11.55 note: run with `RUST_BACKTRACE=1` for a backtrace
 9:11.55 
 9:11.55 thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:434:8
 9:11.55 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 9:11.55 stack backtrace:
 9:11.55    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
 9:11.55              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
 9:11.55    1: std::sys_common::backtrace::_print
 9:11.55              at /checkout/src/libstd/sys_common/backtrace.rs:71
 9:11.55    2: std::panicking::default_hook::{{closure}}
 9:11.55              at /checkout/src/libstd/sys_common/backtrace.rs:60
 9:11.55              at /checkout/src/libstd/panicking.rs:380
 9:11.55    3: std::panicking::default_hook
 9:11.55              at /checkout/src/libstd/panicking.rs:390
 9:11.55    4: std::panicking::rust_panic_with_hook
 9:11.55              at /checkout/src/libstd/panicking.rs:610
 9:11.55    5: std::panicking::begin_panic
 9:11.55    6: rustc_errors::Handler::span_bug
 9:11.55    7: rustc::session::opt_span_bug_fmt::{{closure}}
 9:11.56    8: rustc::session::span_bug_fmt
 9:11.56    9: <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ty_of_fn
 9:11.56   10: rustc_typeck::collect::fn_sig
 9:11.56   11: rustc::dep_graph::graph::DepGraph::with_task
 9:11.56   12: rustc::ty::maps::<impl rustc::ty::maps::queries::fn_sig<'tcx>>::try_get
 9:11.56   13: rustc::ty::maps::TyCtxtAt::fn_sig
 9:11.56   14: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::fn_sig
 9:11.56   15: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
 9:11.56   16: rustc_typeck::check_crate::{{closure}}::{{closure}}
 9:11.56   17: rustc_typeck::check_crate
 9:11.56   18: rustc::ty::context::TyCtxt::create_and_enter
 9:11.56   19: rustc_driver::driver::compile_input
 9:11.56   20: rustc_driver::run_compiler
 9:11.56 
 9:11.56 error: Could not compile `style`.

```

**Comment by gcp** [comment]
Duplicate of issue 43567.
