### ISSUE TITLE
1.19.0 and nightly ICE: unexpected panic at 'Expected Def::Macro(..)', /checkout/src/librustc_resolve/build_reduced_graph.rs:513 

### ISSUE THREAD

**Issue by zhendongsu** [rust-lang/rust#43921]
```bash
$ rustc-nightly --version
rustc 1.21.0-nightly (f25c2283b 2017-08-15)
$ 
$ rustc-nightly small.rs
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (f25c2283b 2017-08-15) running on i686-unknown-linux-gnu

thread 'rustc' panicked at 'Expected Def::Macro(..)', /checkout/src/librustc_resolve/build_reduced_graph.rs:555:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ 
$ cat small.rs
#![feature(use_extern_macros)]
extern crate serialize;
use serialize::{Encodable, Decodable};
#[derive(Encodable::Decodable)]  
struct A {}
$ 
```

**Comment by arielb1** [comment]
cc @jseyfried

**Comment by jseyfried** [comment]
This looks like a bug in error handling of name resolution errors in derive macro paths.

**Comment by dtolnay** [comment]
This looks like the same crash as #41719.
