### ISSUE TITLE
thread 'rustc' panicked at 'cannot use the `#[rustc_if_this_changed]` or `#[rustc_then_this_would_need]` annotations without supplying `-Z query-dep-graph`', /checkout/src/librustc_incremental/assert_dep_graph.rs:88:8

### ISSUE THREAD

**Issue by zhendongsu** [rust-lang/rust#43969]
```bash
$ rustc-nightly --version
rustc 1.21.0-nightly (f25c2283b 2017-08-15)
$ 
$ rustc-nightly -Z query-dep-graph tmp.rs                      
$ 
$ RUST_BACKTRACE=1 rustc-nightly tmp.rs
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (f25c2283b 2017-08-15) running on i686-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'cannot use the `#[rustc_if_this_changed]` or `#[rustc_then_this_would_need]` annotations without supplying `-Z query-dep-graph`', /checkout/src/librustc_incremental/assert_dep_graph.rs:88:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rustc_incremental::assert_dep_graph::assert_dep_graph
   8: rustc_trans::base::assert_and_save_dep_graph
   9: rustc_trans::base::trans_crate
  10: rustc_driver::driver::phase_4_translate_to_llvm
  11: rustc_driver::driver::compile_input::{{closure}}
  12: rustc::ty::context::TyCtxt::create_and_enter
  13: rustc_driver::driver::compile_input
  14: rustc_driver::run_compiler

$ 
$ cat tmp.rs
#![feature(rustc_attrs)]
#![allow(dead_code)]
#![allow(unused_variables)]
#[rustc_if_this_changed]

struct A < T > { x : T }

fn main () { } 
$ 
```

**Comment by arielb1** [comment]
Use internal options, get ICEs. This is far from the only way to achieve this.
