### ISSUE TITLE
Panic on thead::spawn

### ISSUE THREAD

**Issue by martindeegan** [rust-lang/rust#44040]
It panics [here](https://github.com/martindeegan/drone/blob/master/copter/src/sensor_manager/mod.rs#L179).

The odd thing is that the thread is still spawned and the closure runs, but I always get this long error message. I spawn multiple threads without problem throughout the program. I am also not moving or using any vectors.

Here is the backtrace:
```
thread '<unnamed>' panicked at 'capacity overflow', /checkout/src/liballoc/raw_vec.rs:584
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:49
  10: <alloc::raw_vec::RawVec<T>>::double
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: <F as alloc::boxed::FnBox<A>>::call_box
  13: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:658
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
```

**Comment by shepmaster** [comment]
How many total threads are you spawning? What kind of platform are you running on?

**Comment by martindeegan** [comment]
There are 4 threads always running (main + 3 spawned). 
2 optional threads if I am logging data.
Also I start the motors concurrently which spawns 4 threads for a short period of time.

This was running on a Raspberry Pi 3 Model B, quad-core ARM.

**Comment by martindeegan** [comment]
Just to clarify, the motor threads are joined before this error occurs, so there were 2-4 spawned threads at the time this thread starts. This error occurred every time.

**Comment by Mark-Simulacrum** [comment]
The source code is no longer available and as such I'm going to close this as not actionable.
