### ISSUE TITLE
Rustdoc unit tests not being run by Rustbuild

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#44237]
As far as we could tell.

Currently, running `cargo test` in src/librustdoc seems to work, but there are some failures:

```
   Doc-tests rustdoc

running 3 tests
test clean/simplify.rs - clean::simplify (line 24) ... FAILED
test clean/simplify.rs - clean::simplify (line 20) ... FAILED
test html/markdown.rs - html::markdown (line 18) ... FAILED

failures:

---- clean/simplify.rs - clean::simplify (line 24) stdout ----
	error: expected expression, found keyword `where`
 --> clean/simplify.rs:2:1
  |
2 | where T: Trait, <T as Trait>::Foo = Bar
  | ^^^^^

thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12

---- clean/simplify.rs - clean::simplify (line 20) stdout ----
	error: expected expression, found keyword `where`
 --> clean/simplify.rs:2:1
  |
2 | where T: Trait<Foo=Bar>
  | ^^^^^

thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- html/markdown.rs - html::markdown (line 18) stdout ----
	error[E0061]: this function takes 2 parameters but 1 parameter was supplied
 --> html/markdown.rs:6:35
  |
6 | let html = format!("{}", Markdown(s));
  |                                   ^ expected 2 parameters

thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:280:12


failures:
    clean/simplify.rs - clean::simplify (line 20)
    clean/simplify.rs - clean::simplify (line 24)
    html/markdown.rs - html::markdown (line 18)

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by Mark-Simulacrum** [comment]
Seems like more of an infrastructure team problem. Assigning myself, will hopefully have time before Monday.

**Comment by Mark-Simulacrum** [comment]
Not yet fixed, just a preliminary patch....

**Comment by frewsxcv** [comment]
This will be fixed by https://github.com/rust-lang/rust/pull/44274 ?

**Comment by Mark-Simulacrum** [comment]
It should be, yes.

**Comment by frewsxcv** [comment]
Presumably fixed by https://github.com/rust-lang/rust/pull/44274.

**Comment by QuietMisdreavus** [comment]
At some point, this regressed and `src/librustdoc` is no longer tested by bootstrap.

**Comment by QuietMisdreavus** [comment]
Turns out that a refactor in https://github.com/rust-lang/rust/pull/48105 caused the new `CrateRustdoc` test spec to get hidden. I've opened https://github.com/rust-lang/rust/pull/49090 to re-enable it.
