### ISSUE TITLE
'no entry found for key' rustc crash

### ISSUE THREAD

**Issue by jonathanstrong** [rust-lang/rust#44863]
cmd: `RUST_BACKTRACE=1 CARGO_INCREMENTAL=1 cargo build --release`

error: 

```
note: rustc 1.22.0-nightly (6c476ce46 2017-09-25) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'no entry found for key', /checkout/src/libcore/option.rs:839:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::option::expect_failed
             at /checkout/src/libcore/option.rs:839
  10: rustc::dep_graph::graph::DepGraph::fingerprint_of
  11: rustc_incremental::persist::load::decode_dep_graph
  12: rustc_incremental::persist::load::load_dep_graph
  13: rustc::ty::context::TyCtxt::create_and_enter
  14: rustc_driver::driver::compile_input
  15: rustc_driver::run_compiler
```

rustc:

```
binary: rustc
commit-hash: 6c476ce462333fccd89ce3ed8c290998db874653
commit-date: 2017-09-25
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0
```

`cargo build --release` (with no incremental) runs without issue.

**Comment by avl** [comment]
I've seen the exact same problem, going by the stack trace at least.

I don't know what I might have done to trigger it. Solved by cargo clean + cargo build.

**Comment by michaelwoerister** [comment]
Thanks for the bug report!

Is this still reproducible with a current nightly? If so, can you provide an example that causes the problem?

**Comment by michaelwoerister** [comment]
I haven't seen this in a long time, so I'm closing. Please re-open if the issue still persists for you.

**Comment by avl** [comment]
I haven't seen it for quite some time either. Seems like it might be fixed (hopefully it is! :-) )!
