### ISSUE TITLE
/checkout/src/librustc/ich/impls_ty.rs:78: TypeIdHasher: unexpected region ReLateBound(DebruijnIndex { depth: 1 }, "BrEnv")

### ISSUE THREAD

**Issue by mmstick** [rust-lang/rust#45242]
When compiling the [calculate crate](https://github.com/redox-os/calc), I'm getting this error with `nightly-2017-10-11` and `nightly-2017-10-10`. `nightly-2017-10-09` works though.

```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::bug_fmt
  10: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::RegionKind>::hash_stable
  11: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable
  12: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::Binder<T>>::hash_stable
  13: rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable
  14: <T as rustc::dep_graph::dep_node::DepNodeParams<'a, 'gcx, 'tcx>>::to_fingerprint
  15: rustc::dep_graph::dep_node::DepNode::new
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::is_sized_raw<'tcx>>::try_get
  17: rustc::ty::maps::TyCtxtAt::is_sized_raw
  18: rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::is_sized
  19: rustc_trans::callee::get_fn
  20: rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_terminator
  21: rustc_trans::mir::trans_mir
  22: rustc_trans::base::trans_instance
  23: rustc_trans::base::compile_codegen_unit
  24: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force
  25: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get
  26: rustc::ty::maps::TyCtxtAt::compile_codegen_unit
  27: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit
  28: rustc_trans::base::trans_crate
  29: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  30: rustc_driver::driver::compile_input::{{closure}}
  31: rustc::ty::context::TyCtxt::create_and_enter
  32: rustc_driver::driver::compile_input
  33: rustc_driver::run_compiler
```

**Comment by mmstick** [comment]
Closing as duplicate of #45241
