### ISSUE TITLE
Can't build with LLVM-5.0.0

### ISSUE THREAD

**Issue by tpgxyz** [rust-lang/rust#45309]
Hi,

i cant build rust-1.21.0 with system-wide LLVM/clang-5.0.0

Full logs can be found here http://file-store.openmandriva.org/api/v1/file_stores/c2556f0322987eef8b2b894e1180aceff35a2222.log?show=true

```
     Running `/builddir/build/BUILD/rustc-1.21.0-src/build/x86_64-unknown-linux-gnu/stage0-std/release/build/rustc_tsan-3ca86eb7b613857d/build-script-build`
     Running `/builddir/build/BUILD/rustc-1.21.0-src/build/x86_64-unknown-linux-gnu/stage0-std/release/build/rustc_lsan-c674ac66d4c31444/build-script-build`
error: failed to run custom build command for `compiler_builtins v0.0.0 (file:///builddir/build/BUILD/rustc-1.21.0-src/src/rustc/compiler_builtins_shim)`
process didn't exit successfully: `/builddir/build/BUILD/rustc-1.21.0-src/build/x86_64-unknown-linux-gnu/stage0-std/release/build/compiler_builtins-44447bd60866f757/build-script-build` (exit code: 101)


ARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("2")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = Some("/usr/bin/clang")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = Some("-ffunction-sections -fdata-sections -fPIC -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC --target=x86_64-unknown-linux-gnu")
PROFILE = Some("release")
running: "/usr/bin/clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-Wstrict-aliasing=2" "-pipe" "-Wformat" "-Werror=format-security" "-D_FORTIFY_SOURCE=2" "-fstack-protector" "--param=ssp-buffer-size=4" "-fPIC" "--target=x86_64-unknown-linux-gnu" "--target=x86_64-unknown-linux-gnu" "-fno-builtin" "-fvisibility=hidden" "-fomit-frame-pointer" "-ffreestanding" "-DVISIBILITY_HIDDEN" "-o" "/builddir/build/BUILD/rustc-1.21.0-src/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-3726c83d777fb924/out/../../libcompiler_builtins/compiler-rt/lib/builtins/int_util.o" "-c" "../../libcompiler_builtins/compiler-rt/lib/builtins/int_util.c"
cargo:warning=In file included from ../../libcompiler_builtins/compiler-rt/lib/builtins/int_util.c:51:
cargo:warning=In file included from /usr/include/stdlib.h:905:
cargo:warning=/usr/include/bits/stdlib.h:90:3: error: "Assumed value of MB_LEN_MAX wrong"
cargo:warning=# error "Assumed value of MB_LEN_MAX wrong"
cargo:warning=  ^
cargo:warning=1 error generated.
exit code: 1
command did not execute successfully, got: exit code: 1
--- stderr
thread 'main' panicked at 'explicit panic', src/vendor/gcc/src/lib.rs:1239:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
   6: gcc::fail
   7: gcc::run
   8: gcc::Config::compile
   9: build_script_build::main
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  11: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  12: __libc_start_main
  13: _start
             at ../sysdeps/x86_64/start.S:120
warning: build failed, waiting for other jobs to finish...
error: build failed
thread 'main' panicked at 'command did not execute successfully: "/builddir/build/BUILD/rustc-1.21.0-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "12" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--frozen" "--features" "panic-unwind backtrace" "--manifest-path" "/builddir/build/BUILD/rustc-1.21.0-src/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:883:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: bootstrap::compile::run_cargo
   8: <bootstrap::compile::Std as bootstrap::builder::Step>::run
   9: bootstrap::builder::Builder::ensure
  10: <bootstrap::compile::Test as bootstrap::builder::Step>::run
  11: bootstrap::builder::Builder::ensure
  12: <bootstrap::compile::Rustc as bootstrap::builder::Step>::run
  13: bootstrap::builder::Builder::ensure
  14: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
  15: bootstrap::builder::Builder::ensure
  16: bootstrap::builder::Builder::compiler
  17: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
  18: bootstrap::builder::Builder::ensure
  19: bootstrap::builder::Builder::compiler
  20: <bootstrap::compile::Std as bootstrap::builder::Step>::make_run
  21: bootstrap::builder::StepDescription::maybe_run
  22: bootstrap::builder::StepDescription::run
  23: bootstrap::builder::Builder::run
  24: bootstrap::Build::build
  25: bootstrap::main
  26: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  27: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  28: main
  29: __libc_start_main
  30: _start
             at ../sysdeps/x86_64/start.S:120
Traceback (most recent call last):
  File "./x.py", line 20, in <module>
    bootstrap.main()
  File "/builddir/build/BUILD/rustc-1.21.0-src/src/bootstrap/bootstrap.py", line 799, in main
    bootstrap()
  File "/builddir/build/BUILD/rustc-1.21.0-src/src/bootstrap/bootstrap.py", line 790, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/builddir/build/BUILD/rustc-1.21.0-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /builddir/build/BUILD/rustc-1.21.0-src/build/bootstrap/debug/bootstrap build --verbose
error: Bad exit status from /var/tmp/rpm-tmp.18704 (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.18704 (%build)
Child returncode was: 1
```

**Comment by est31** [comment]
see  #43370
