### ISSUE TITLE
BufWriter::write panics during flush_buf

### ISSUE THREAD

**Issue by azdlowry** [rust-lang/rust#45318]
I'm still investigating this but it seems if we have a `BufStream `around a ~~UnixStream~~ `openssl::ssl::SslStream<std::net::TcpStream>`, and we write to it too quickly it panics.

The `std::net::TcpStream` is non-blocking which might be relevant.

```
thread '<unnamed>' panicked at 'assertion failed: end <= len', /checkout/src/liballoc/vec.rs:1117:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: <alloc::vec::Vec<T>>::drain
             at /checkout/obj/<panic macros>:3
  11: <std::io::buffered::BufWriter<W>>::flush_buf
             at /checkout/src/libstd/io/buffered.rs:421
  12: <std::io::buffered::BufWriter<W> as std::io::Write>::write
             at /checkout/src/libstd/io/buffered.rs:488
  13: <bufstream::BufStream<S> as std::io::Write>::write
             at /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/bufstream-0.1.3/src/lib.rs:217
  14: <netopt::non_blocking_conn::NonBlockingConnection as std::io::Write>::write
             at src/netopt/src/non_blocking_conn.rs:82
  15: std::io::Write::write_all
             at /checkout/src/libstd/io/mod.rs:1072
```

```
active toolchain
----------------

nightly-2017-09-22-x86_64-unknown-linux-gnu (default)
rustc 1.22.0-nightly (17f56c549 2017-09-21)

openssl 0.9.20
```

I'll add more details as I investigate more.

**Comment by azdlowry** [comment]
Apologies, I originally said this was wrapping a UnixStream, but it's actually wrapping an SslStream<TcpStream>. This is easily reproducible in our application. Trying to reduce the code down to the bare minimum required to reproduce.

**Comment by azdlowry** [comment]
The wrapped SslStream::write had returned 'Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }' for the previous few writes.

**Comment by sfackler** [comment]
From looking at the code, I would only expect this to happen if the underlying writer said that it wrote more bytes than the input buffer contained.

**Comment by azdlowry** [comment]
Seconds ahead of me :D. Looks like SslStream is returning Ok(24999) for a write of buf.len() = 8192.

Doesn't sound like is something that should be handled in BufStream. I'll investigate what is happening in the OpenSsl crate.

**Comment by sfackler** [comment]
Cool - I'm going to close this issue since it doesn't seem to be an issue with BufWriter.
