### ISSUE TITLE
Can't build stylo in FF 56.x

### ISSUE THREAD

**Issue by tpgxyz** [rust-lang/rust#45342]
I'm trying to build FF 56.0.1 with rust-1.21.0.

Full logs can be found here http://file-store.openmandriva.org/api/v1/file_stores/1e85cf22a732ff76c55f52625dfab10fbfcaac23.log?show=true

error: failed to run custom build command for `style v0.0.1 (file:///builddir/build/BUILD/firefox-56.0.1/servo/components/style)`
```

/builddir/build/BUILD/firefox-56.0.1/obj/dist/include/nsCSSFontFaceRule.h:137:38: warning: offset of on non-standard-layout type 'nsCSSFontFaceRule' [-Winvalid-offsetof], err: false
/builddir/build/BUILD/firefox-56.0.1/obj/dist/include/nsCSSFontFaceRule.h:144:44: warning: offset of on non-standard-layout type 'nsCSSFontFaceRule' [-Winvalid-offsetof], err: false
/builddir/build/BUILD/firefox-56.0.1/obj/dist/include/nsStyleContext.h:76:15: warning: inline function 'nsStyleContext::Release' is not defined [-Wundefined-inline], err: false
--- stderr
thread '<unnamed>' panicked at 'Non floating-type complex?', /builddir/build/BUILD/firefox-56.0.1/third_party/rust/bindgen/src/ir/context.rs:1409:25
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:60
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
   6: bindgen::ir::context::BindgenContext::builtin_or_resolved_ty
   7: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_or_ref_with_id
   8: bindgen::ir::ty::Type::from_clang_ty
   9: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id
  10: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse
  11: bindgen::clang::visit_children
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: clang_visitChildren
  17: clang_sys::clang_visitChildren
  18: bindgen::Bindings::generate
  19: bindgen::Builder::generate
  20: build_script_build::build_gecko::bindings::write_binding_file
  21: build_script_build::build_gecko::bindings::generate_bindings
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  23: <F as alloc::boxed::FnBox<A>>::call_box
  24: std::sys::imp::thread::Thread::new::thread_start
             at /builddir/build/BUILD/rustc-1.21.0-src/src/liballoc/boxed.rs:692
             at src/libstd/sys_common/thread.rs:21
             at src/libstd/sys/unix/thread.rs:84
  25: start_thread
  26: __GI___clone
thread '<unnamed>' panicked at 'Non floating-type complex?', /builddir/build/BUILD/firefox-56.0.1/third_party/rust/bindgen/src/ir/context.rs:1409:25
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:60
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
   6: bindgen::ir::context::BindgenContext::builtin_or_resolved_ty
   7: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_or_ref_with_id
   8: bindgen::ir::ty::Type::from_clang_ty
   9: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id
  10: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse
  11: bindgen::clang::visit_children
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: clang_visitChildren
  17: clang_sys::clang_visitChildren
  18: bindgen::clang::visit_children
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: clang_visitChildren
  24: clang_sys::clang_visitChildren
  25: bindgen::Bindings::generate
  26: bindgen::Builder::generate
  27: build_script_build::build_gecko::bindings::write_binding_file
  28: build_script_build::build_gecko::bindings::generate_structs
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  30: <F as alloc::boxed::FnBox<A>>::call_box
  31: std::sys::imp::thread::Thread::new::thread_start
             at /builddir/build/BUILD/rustc-1.21.0-src/src/liballoc/boxed.rs:692
             at src/libstd/sys_common/thread.rs:21
             at src/libstd/sys/unix/thread.rs:84
  32: start_thread
  33: __GI___clone
thread '<unnamed>' panicked at 'Non floating-type complex?', /builddir/build/BUILD/firefox-56.0.1/third_party/rust/bindgen/src/ir/context.rs:1409:25
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:60
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
   6: bindgen::ir::context::BindgenContext::builtin_or_resolved_ty
   7: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_or_ref_with_id
   8: bindgen::ir::ty::Type::from_clang_ty
   9: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id
  10: <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse
  11: bindgen::clang::visit_children
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: clang_visitChildren
  17: clang_sys::clang_visitChildren
  18: bindgen::clang::visit_children
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: clang_visitChildren
  24: clang_sys::clang_visitChildren
  25: bindgen::Bindings::generate
  26: bindgen::Builder::generate
  27: build_script_build::build_gecko::bindings::write_binding_file
  28: build_script_build::build_gecko::bindings::generate_structs
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  30: <F as alloc::boxed::FnBox<A>>::call_box
  31: std::sys::imp::thread::Thread::new::thread_start
             at /builddir/build/BUILD/rustc-1.21.0-src/src/liballoc/boxed.rs:692
             at src/libstd/sys_common/thread.rs:21
             at src/libstd/sys/unix/thread.rs:84
  32: start_thread
  33: __GI___clone
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:60
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: build_script_build::main
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:361
             at src/libstd/rt.rs:61
  13: __libc_start_main
  14: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by kennytm** [comment]
This sounds like a bug in [bindgen](https://github.com/rust-lang-nursery/rust-bindgen/issues), not Rust itself.
