### ISSUE TITLE
target wasm no longer work with latest emscripten incoming branch

### ISSUE THREAD

**Issue by Guara92** [rust-lang/rust#45395]
If rustc or cargo is launched using target=wasm32-unknown-emscripten the build will fail:
error: linking with `emcc` failed: exit code: 1
  = note: Unknown option '--trap-mode'
          Traceback (most recent call last):
            File "/usr/bin/emcc", line 13, in <module>
              emcc.run()
            File "/usr/lib/emscripten/emcc.py", line 1818, in run
              wasm_text_target, misc_temp_files, optimizer)
            File "/usr/lib/emscripten/emcc.py", line 2288, in do_binaryen
              subprocess.check_call(cmd)
            File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
              raise CalledProcessError(retcode, cmd)
I'm using emscripten 1.37.22.16

**Comment by chicoxyzzy** [comment]
Probably this was fix on Emscripten side

**Comment by jryans** [comment]
I can’t reproduce this: Rust and Emscripten are working well.

**Comment by workingjubilee** [comment]
not clear what the issue was, but also seems to be fixed, so taking no news as good news.
