### ISSUE TITLE
MIR borrowck: ICE: End-user description not implemented for field access on TyClosure

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#45643]
Code:
```Rust
fn main() {
    let s = String::new();
    move || {
        drop(s);
        drop(s);
    };
}
```

Result:
```
$ RUST_BACKTRACE=1 ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc ds.rs -Z borrowck-mir
error[E0382]: use of moved value: `s` (Ast)
 --> ds.rs:5:14
  |
4 |         drop(s);
  |              - value moved here
5 |         drop(s);
  |              ^ value used here after move
  |
  = note: move occurs because `s` has type `std::string::String`, which does not implement the `
Copy` trait

error: internal compiler error: rust://src/librustc_mir/borrow_check.rs:1300: End-user descripti
on not implemented for field access on `TyClosure(DefId { krate: CrateNum(0), index: DefIndex(1:
9) => ds[317d]::main[0]::{{closure}}[0] }, ClosureSubsts { substs: Slice([std::string::String]) 
})`

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTI
NG.md#bug-reports

note: rustc 1.23.0-dev running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', rust://src/librustc_errors/lib.rs:503:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at rust://src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at rust://src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at rust://src/libstd/sys_common/backtrace.rs:58
             at rust://src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at rust://src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at rust://src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at rust://src/libstd/panicking.rs:538
   6: rustc_errors::Handler::bug
             at rust://src/librustc_errors/lib.rs:503
   7: rustc::session::opt_span_bug_fmt::{{closure}}
             at rust://src/librustc/session/mod.rs:981
   8: rustc::session::opt_span_bug_fmt
             at rust://src/librustc/ty/context.rs:0
   9: rustc::session::bug_fmt
             at rust://src/librustc/session/mod.rs:961
  10: rustc_mir::borrow_check::MirBorrowckCtxt::describe_field_from_ty
             at rust://src/librustc_mir/borrow_check.rs:1300
  11: rustc_mir::borrow_check::MirBorrowckCtxt::describe_field
             at rust://src/librustc_mir/borrow_check.rs:0
  12: rustc_mir::borrow_check::MirBorrowckCtxt::append_lvalue_to_string
             at rust://src/librustc_mir/borrow_check.rs:1208
  13: rustc_mir::borrow_check::MirBorrowckCtxt::report_use_of_moved
             at rust://src/librustc_mir/borrow_check.rs:1181
             at rust://src/librustc_mir/borrow_check.rs:1063
  14: rustc_mir::borrow_check::MirBorrowckCtxt::check_if_path_is_moved
             at rust://src/librustc_mir/borrow_check.rs:0
  15: rustc_mir::borrow_check::MirBorrowckCtxt::consume_lvalue
             at rust://src/librustc_mir/borrow_check.rs:578
  16: <rustc_mir::borrow_check::MirBorrowckCtxt<'c, 'b, 'a, 'gcx, 'tcx> as rustc_mir::dataflow::DataflowResultsConsumer<'b, 'gcx>>::visit_statement_entry
             at rust://src/librustc_mir/borrow_check.rs:547
             at rust://src/librustc_mir/borrow_check.rs:503
             at rust://src/librustc_mir/borrow_check.rs:211
  17: rustc_mir::borrow_check::mir_borrowck::{{closure}}
             at rust://src/librustc_mir/dataflow/mod.rs:309
             at rust://src/librustc_mir/dataflow/mod.rs:299
             at rust://src/librustc_mir/borrow_check.rs:115
  18: rustc_mir::borrow_check::mir_borrowck
             at rust://src/librustc/infer/mod.rs:375
             at rust://src/librustc/ty/context.rs:1511
             at rust://src/libstd/thread/local.rs:377
             at rust://src/libstd/thread/local.rs:288
             at rust://src/librustc/ty/context.rs:1508
             at rust://src/librustc/ty/context.rs:1319
             at rust://src/librustc/infer/mod.rs:375
             at rust://src/librustc_mir/borrow_check.rs:61
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
             at rust://src/librustc/ty/maps/plumbing.rs:390
             at rust://src/librustc/dep_graph/graph.rs:287
  20: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::force
             at rust://src/librustc/dep_graph/graph.rs:203
             at rust://src/librustc/ty/maps/plumbing.rs:442
             at rust://src/librustc_errors/lib.rs:566
             at rust://src/librustc/ty/maps/plumbing.rs:435
             at rust://src/librustc/ty/maps/plumbing.rs:130
             at rust://src/librustc/ty/maps/plumbing.rs:434
  21: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::try_get
             at rust://src/librustc/ty/maps/plumbing.rs:313
             at rust://src/librustc/ty/maps/plumbing.rs:471
  22: rustc::ty::maps::TyCtxtAt::mir_borrowck
             at rust://src/librustc/ty/maps/plumbing.rs:510
  23: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
             at rust://src/librustc/ty/maps/plumbing.rs:503
  24: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::{{closure}}
             at rust://src/librustc_driver/driver.rs:1095
  25: rustc::ty::context::TyCtxt::create_and_enter
             at rust://src/librustc/util/common.rs:120
             at rust://src/librustc_driver/driver.rs:1093
             at rust://src/librustc/ty/context.rs:1511
             at rust://src/libstd/thread/local.rs:377
             at rust://src/libstd/thread/local.rs:288
             at rust://src/librustc/ty/context.rs:1508
             at rust://src/librustc/ty/context.rs:1495
             at rust://src/libstd/thread/local.rs:377
             at rust://src/libstd/thread/local.rs:288
             at rust://src/librustc/ty/context.rs:1492
             at rust://src/librustc/ty/context.rs:1136
  26: rustc_driver::driver::compile_input
             at rust://src/librustc_driver/driver.rs:1041
             at rust://src/librustc_driver/driver.rs:210
  27: rustc_driver::run_compiler
             at rust://src/librustc_driver/lib.rs:252
```

**Comment by arielb1** [comment]
This has been fixed.
