### ISSUE TITLE
thread 'rustc' panicked at 'Expected Def::Macro(..)' with rocket_contrib and serde_json

### ISSUE THREAD

**Issue by pbzweihander** [rust-lang/rust#45976]
## The Code

```rust
#![feature(plugin, custom_derive, decl_macro)]
#![plugin(rocket_codegen)]
extern crate rocket;
extern crate rocket_contrib;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

use rocket_contrib::Value;

fn main() {
    Value::json!("boo");
    println!("Hello, world!");
}
```

When I mistakenly typed `Value::json!( ... )` instead of just `json!( ... )`, I found these errors:

## What I Get

```bash
$ RUST_BACKTRACE=1 cargo check --verbose        
       Fresh itoa v0.3.4
       ...
       Fresh rocket_codegen v0.3.3
   Compiling bugtest v0.1.0 (file:///home/thomas/project/rust/bugtest)
     Running `rustc --crate-name bugtest src/main.rs --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=1c6219ec60e80471 -C extra-filename=-1c6219ec60e80471 --out-dir /home/thomas/project/rust/bugtest/target/debug/deps -L dependency=/home/thomas/project/rust/bugtest/target/debug/deps --extern rocket=/home/thomas/project/rust/bugtest/target/debug/deps/librocket-20cf9c2231c2d91e.rmeta --extern rocket_codegen=/home/thomas/project/rust/bugtest/target/debug/deps/librocket_codegen-3e5b1b554f9914af.so --extern serde_json=/home/thomas/project/rust/bugtest/target/debug/deps/libserde_json-6714a52d2eda8944.rmeta --extern serde_derive=/home/thomas/project/rust/bugtest/target/debug/deps/libserde_derive-938a2640abce037f.so --extern rocket_contrib=/home/thomas/project/rust/bugtest/target/debug/deps/librocket_contrib-02837b02e6cafcc4.rmeta -L native=/home/thomas/project/rust/bugtest/target/debug/build/ring-82bb059f0ed9030c/out`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0-nightly (79cfce3d3 2017-11-12) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Expected Def::Macro(..)', /checkout/src/librustc_resolve/build_reduced_graph.rs:571:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::get_macro
   7: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::resolve_invoc
   8: _ZN6syntax3ext6expand13MacroExpander6expand17h048b8176d9094bd6E.llvm.9932C54D
   9: syntax::ext::expand::MacroExpander::expand_crate
  10: _ZN12rustc_driver6driver28phase_2_configure_and_expand28_$u7b$$u7b$closure$u7d$$u7d$17h947c02dab5db8ba4E.llvm.5DFC5664
  11: rustc::util::common::time
  12: rustc_driver::driver::compile_input
  13: rustc_driver::run_compiler

error: Could not compile `bugtest`.

Caused by:
  process didn't exit successfully: `rustc --crate-name bugtest src/main.rs --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=1c6219ec60e80471 -C extra-filename=-1c6219ec60e80471 --out-dir /home/thomas/project/rust/bugtest/target/debug/deps -L dependency=/home/thomas/project/rust/bugtest/target/debug/deps --extern rocket=/home/thomas/project/rust/bugtest/target/debug/deps/librocket-20cf9c2231c2d91e.rmeta --extern rocket_codegen=/home/thomas/project/rust/bugtest/target/debug/deps/librocket_codegen-3e5b1b554f9914af.so --extern serde_json=/home/thomas/project/rust/bugtest/target/debug/deps/libserde_json-6714a52d2eda8944.rmeta --extern serde_derive=/home/thomas/project/rust/bugtest/target/debug/deps/libserde_derive-938a2640abce037f.so --extern rocket_contrib=/home/thomas/project/rust/bugtest/target/debug/deps/librocket_contrib-02837b02e6cafcc4.rmeta -L native=/home/thomas/project/rust/bugtest/target/debug/build/ring-82bb059f0ed9030c/out` (exit code: 101)
```

## Rust Version

```bash
$ rustc --version --verbose
rustc 1.23.0-nightly (79cfce3d3 2017-11-12)
binary: rustc
commit-hash: 79cfce3d35cc8c2716c65650389d79551c2ea6ea
commit-date: 2017-11-12
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0
```

**Comment by tirr-c** [comment]
I think this is the minimal testcase.

https://play.rust-lang.org/?gist=371836b3fab5dbe95759d6dda2ead1d0&version=nightly

**Comment by dtolnay** [comment]
Thanks! This looks like the same crash as #41719.
