### ISSUE TITLE
rustc "unexpected panic"; no /proc/self/exe inside a debootstrap chroot

### ISSUE THREAD

**Issue by nigeltao** [rust-lang/rust#46090]
I installed rustc in a Debian chroot, as per https://wiki.debian.org/Debootstrap

```
sudo debootstrap testing /debian-testing-chroot https://deb.debian.org/debian/
```

Inside that chroot, rustc crashes.

```
# rustc hello.rs
Can't read /proc/cpuinfo: No such file or directory
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0 running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'failed to get current_exe: no /proc/self/exe available. Is /proc mounted?', src/librustc/session/filesearch.rs:169:22
note: Run with `RUST_BACKTRACE=1` for a backtrace.

# ls /proc
#
```

Sure, I can tinker with my chroot configuration to flesh out /proc, but as rustc's output said, "the compiler unexpectedly panicked. this is a bug".

**Comment by nigeltao** [comment]
RUST_BACKTRACE=1 doesn't give much information.

```
# RUST_BACKTRACE=1 rustc hello.rs
Can't read /proc/cpuinfo: No such file or directory
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0 running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'failed to get current_exe: no /proc/self/exe available. Is /proc mounted?', src/librustc/session/filesearch.rs:169:22
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
```

**Comment by guysoft** [comment]
Getting the same when building cryptography for python.
```
rustc' panicked at 'failed to get current_exe: no /proc/self/exe available. Is /proc mounted
```

Source at this project:
https://github.com/guysoft/MagicMirrorOS

**Comment by filippoSelvatici** [comment]
I'm having the same issue when compiling a simple rust program inside a sandbox. The error I get is:
```
error: Unable to proceed. Could not locate working directory.: no /proc/self/exe available. Is /proc mounted?
```
Is there any workaround to avoid mounting proc inside the sandbox? 

Source of the sandbox:
[https://github.com/alerighi/tabox](https://github.com/alerighi/tabox )

**Comment by bjorn3** [comment]
We need `/proc/self/exe` to implement `std::env::current_exe()` which rustc uses to locate the sysroot.

**Comment by DemiMarie** [comment]
@bjorn3 that is going to be a problem, because some sandboxes (such as Sandstorm) deliberately avoid mounting `/proc` to reduce attack surface.  I think `rustc` should have a compiled-in fallback if `/proc` is not mounted.
