### ISSUE TITLE
Compiler panic when creating macro_rules from a custom derive

### ISSUE THREAD

**Issue by Luthaf** [rust-lang/rust#46185]
I changed some code in soa-derive to emit a macro_rules inside a custom derive, and got the following ICE:

```
$ RUST_BACKTRACE=1 cargo test          
   Compiling soa_derive v0.4.1 (file:///home/guillaume/perso/lumol/soa-derive)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.21.0 (3b72af97e 2017-10-09) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assume all sequences have (unique) spans for now', /checkout/src/libsyntax/ext/tt/macro_rules.rs:493:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
   6: syntax::ext::tt::macro_rules::check_matcher_core::{{closure}}
   7: syntax::ext::tt::macro_rules::check_matcher_core
   8: syntax::ext::tt::macro_rules::compile
   9: rustc_resolve::macros::<impl rustc_resolve::Resolver<'a>>::define_macro
  10: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion
  11: syntax::ext::expand::MacroExpander::collect_invocations
  12: syntax::ext::expand::MacroExpander::expand
  13: syntax::ext::expand::MacroExpander::expand_crate
  14: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}
  15: rustc_driver::driver::phase_2_configure_and_expand
  16: rustc_driver::driver::compile_input
  17: rustc_driver::run_compiler

error: Could not compile `soa_derive`.
```

The code is in the [soa_zip](https://github.com/lumol-org/soa-derive/tree/soa_zip) branch, at commit https://github.com/lumol-org/soa-derive/commit/70376c15c05eeb9cc87249ca4db3b1ff15bf9543.

The macro_rules definition compiles fine if I write it directly, and I could not reproduce the issue with a simpler macro_rules definition.

```
$ rustc -vV
rustc 1.21.0 (3b72af97e 2017-10-09)
binary: rustc
commit-hash: 3b72af97e42989b2fe104d8edbaee123cdf7c58f
commit-date: 2017-10-09
host: x86_64-unknown-linux-gnu
release: 1.21.0
LLVM version: 4.0
```

EDIT: the ICE exist for all of stable, beta, nightly, see the travis build [here](https://travis-ci.org/lumol-org/soa-derive/builds/305897587)

**Comment by Aaron1011** [comment]
I can't reproduce this on the latest Nightly (`rustc 1.45.0-nightly (8970e8bcf 2020-05-23)`)

**Comment by CraftSpider** [comment]
No ICE on currently nightly (`rustc 1.70.0-nightly (ab654863c 2023-03-15)`) with syn set to `0.11` or `0.9` (since `0.10` has been yanked), confirmed by another person on discord. I imagine this can be closed now.
