### ISSUE TITLE
ICE when using associated constant as an array size

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#46394]
The following code ICEs on stable:

```Rust
trait Nat {
    const VALUE: usize;
}

struct Zero;

impl Nat for Zero {
    const VALUE: usize = 0;
}

struct Succ<N>(N);

impl<N: Nat> Nat for Succ<N> {
    const VALUE: usize = N::VALUE + 1;
}

fn main() {
    type A = [u8; Succ::<Succ<Zero>>::VALUE];
    eprintln!("::std::mem::size_of::<xs>() = {:?}", ::std::mem::size_of::<A>());
}
```

<details>

```
error: internal compiler error: /checkout/src/librustc_trans/context.rs:640: failed to get layout for `[u8; <unevaluated[]>]`: the type `[u8; <unevaluated[]>]` has an unknown layout

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.22.1 (05e2e1c41 2017-11-22) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
stack backtrace:
   0:     0x7f3e4c6f3e43 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h8ed7485deb8ab958
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f3e4c6ee590 - std::sys_common::backtrace::_print::h3d4f9ea58578e60f
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
   2:     0x7f3e4c701343 - std::panicking::default_hook::{{closure}}::h0088fe51b67c687c
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7f3e4c70104a - std::panicking::default_hook::hf425c768c5ffbbad
                               at /checkout/src/libstd/panicking.rs:391
   4:     0x7f3e4c701807 - std::panicking::rust_panic_with_hook::h25b934bb4484e9e0
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7f3e47e438a8 - std::panicking::begin_panic::hb516dde7009d236d
   6:     0x7f3e47e61405 - rustc_errors::Handler::bug::h54cc1d8184cfe898
   7:     0x7f3e49347f80 - rustc::session::opt_span_bug_fmt::{{closure}}::he1ac465da2b81207
   8:     0x7f3e49347c55 - rustc::session::opt_span_bug_fmt::h5974b48e1bbe9aa6
   9:     0x7f3e49347936 - rustc::session::bug_fmt::ha64c971210a59f62
  10:     0x7f3e4a8a9e0b - <&'a rustc_trans::context::SharedCrateContext<'a, 'tcx> as rustc::ty::layout::LayoutTyper<'tcx>>::layout_of::hd874b5e544391a8b
  11:     0x7f3e4a8da7c6 - rustc_trans::mir::constant::MirConstContext::trans::hcdac8daf54d455c0
  12:     0x7f3e4a8da5c8 - rustc_trans::mir::constant::MirConstContext::trans_def::hf76cd48dc83329da
  13:     0x7f3e4a8da893 - rustc_trans::mir::constant::MirConstContext::trans::hcdac8daf54d455c0
  14:     0x7f3e4a8e0187 - rustc_trans::mir::constant::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_constant::h300c9b809c076638
  15:     0x7f3e4a8e3731 - rustc_trans::mir::operand::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_operand::h7418e0c869f6f1ba
  16:     0x7f3e4a8e4f33 - rustc_trans::mir::rvalue::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_rvalue_operand::hf512e3355ec46093
  17:     0x7f3e4a8cf906 - rustc_trans::mir::trans_mir::h2a0b6e1a7a38e7bd
  18:     0x7f3e4a88d8be - rustc_trans::base::trans_instance::h1c470d3104ad2a98
  19:     0x7f3e4a899ea1 - rustc_trans::base::compile_codegen_unit::he7f773e2d7fbe06e
  20:     0x7f3e4958d9b7 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force::h19824cb5f217305d
  21:     0x7f3e4958e9df - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get::hf856a8538a3d36f6
  22:     0x7f3e495a1043 - rustc::ty::maps::TyCtxtAt::compile_codegen_unit::h4ab897227d123c6d
  23:     0x7f3e49598967 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit::habecaff1f58fc5b4
  24:     0x7f3e4a890243 - rustc_trans::base::trans_crate::h60046f7f3676a313
  25:     0x7f3e4a8f5fe3 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::hc216841f6d249410
  26:     0x7f3e4caa60f3 - rustc_driver::driver::compile_input::{{closure}}::h46c1758fee8f92a3
  27:     0x7f3e4ca269b7 - rustc::ty::context::TyCtxt::create_and_enter::h3dad1968772b9cec
  28:     0x7f3e4caa3d4b - rustc_driver::driver::compile_input::h4bf59ac61f928939
  29:     0x7f3e4cabf9fe - rustc_driver::run_compiler::h2a410e29e6088b6b
  30:     0x7f3e4c9de7c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb62d9d382e421fd7
  31:     0x7f3e4c73bbdc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  32:     0x7f3e4ca17870 - <F as alloc::boxed::FnBox<A>>::call_box::h56ea5c52b2f008af
  33:     0x7f3e4c70020b - std::sys::imp::thread::Thread::new::thread_start::hbaf1b5aa1ca8e3ea
                               at /checkout/src/liballoc/boxed.rs:736
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  34:     0x7f3e475d3233 - start_thread
  35:     0x7f3e4c3cd75e - clone
  36:                0x0 - <unknown>
```

</details>

Additionally, the following code fails to compile with a wrong error message:

```Rust
trait Nat {
    const VALUE: usize;
}

struct Zero;

impl Nat for Zero {
    const VALUE: usize = 0;
}

struct Succ<N>(N);

impl<N: Nat> Nat for Succ<N> {
    const VALUE: usize = N::VALUE + 1;
}

struct S<N: Nat> {
    data: [u8; N::VALUE]
            // ^^^^^^^^ no associated item named `VALUE` found for type `N` in the current scope
}

fn main() {
}
```

I understand that this is probably just the expected behavior at the moment, because real const generics are not yet implemented, and this is basically const generics :)

**Comment by michaelwoerister** [comment]
Discussed during triage. This seems to be fixed in beta and nightly. We should add a test.

**Comment by arielb1** [comment]
We already have a test: src/test/run-pass/ctfe/assoc-const.rs
