### ISSUE TITLE
`librustc_trans_utils/collector.rs:743: Cannot create local trans-item for DefId(11/0:54 ~ stpl[d907]::html[0]::h1[0])`

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#46456]
I'm abusing

```
#![feature(universal_impl_trait)]                                                                                               
#![feature(conservative_impl_trait)]
```

and I get:

```
   Compiling stpl-test v0.1.0 (file:///home/dpc/lab/rust/stpl/stpl-test)
error: internal compiler error: /checkout/src/librustc_trans_utils/collector.rs:743: Cannot create local trans-item for DefId(11/0:54 ~ stpl[d907]::html[0]::h1[0])

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (bb42071f6 2017-12-01) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:501:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17h6b0e028b9e47eeccE.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h5c0ea1fecbcb832fE.llvm.C2EB5BE0
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: <std::thread::local::LocalKey<T>>::with
   8: rustc::ty::context::tls::with_opt
   9: _ZN5rustc7session16opt_span_bug_fmt17h090455933aeccff4E.llvm.158FE8B7
  10: rustc::session::bug_fmt
  11: rustc_trans_utils::collector::should_trans_locally
  12: _ZN17rustc_trans_utils9collector18visit_instance_use17h3db3c0d8547c1c9fE.llvm.D884AA40
  13: _ZN17rustc_trans_utils9collector12visit_fn_use17h8abff5569d43207aE.llvm.D884AA40
  14: <rustc_trans_utils::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind
  15: _ZN5rustc3mir5visit7Visitor9visit_mir17h4fdd93ac5128789eE.llvm.D884AA40
  16: _ZN17rustc_trans_utils9collector17collect_items_rec17h3394c380f31e8055E.llvm.D884AA40
  17: _ZN17rustc_trans_utils9collector17collect_items_rec17h3394c380f31e8055E.llvm.D884AA40
  18: _ZN17rustc_trans_utils9collector17collect_items_rec17h3394c380f31e8055E.llvm.D884AA40
  19: rustc_trans_utils::collector::collect_crate_translation_items
  20: rustc::util::common::time
  21: _ZN11rustc_trans4base39collect_and_partition_translation_items17h450eea1f6d722960E.llvm.B55CB618
  22: _ZN5rustc9dep_graph5graph8DepGraph14with_task_impl17h5dafa9b8d878cb0aE.llvm.D6588A24
  23: rustc_errors::Handler::track_diagnostics
  24: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  25: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::force
  26: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get
  27: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
  28: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items
  29: rustc_trans::base::trans_crate
  30: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  31: rustc::util::common::time
  32: rustc_driver::driver::phase_4_translate_to_llvm
  33: _ZN12rustc_driver6driver13compile_input28_$u7b$$u7b$closure$u7d$$u7d$17hc6f1f1ca89cb2ce3E.llvm.2FBC5379
  34: <std::thread::local::LocalKey<T>>::with
  35: <std::thread::local::LocalKey<T>>::with
  36: rustc::ty::context::TyCtxt::create_and_enter
  37: rustc_driver::driver::compile_input
  38: rustc_driver::run_compiler

error: Could not compile `stpl-test`.

To learn more, run the command again with --verbose.
```

I'm unable to provide code just yet, so I'm reporting what I've got. Will provide more as needed/as I can.

**Comment by michaelwoerister** [comment]
Thanks, @dpc!
cc @eddyb @cramertj

**Comment by cramertj** [comment]
@dpc Can you try this on the latest nightly and see if it still breaks? I think this issue was fixed already.

**Comment by dpc** [comment]
I am sorry, but I don't have that state anymore, and I haven't seen it for a while now. I think, it being  addressed in nightly is good enough, and I'll always reopen if it resurfaces. Thanks!
