### ISSUE TITLE
Tests succeeded with panic inside

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#46536]
Unit tests with panic inside caused tests to pass successfully.

I tried this: `cargo test -j8`

I expected to see this happen: 2 of 250 tests failed with description:
```
failures:

---- toxcore_tests::network_tests::networking_core_new_test stdout ----
	thread 'toxcore_tests::network_tests::networking_core_new_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4

---- toxcore_tests::network_tests::networking_core_register_test stdout ----
	thread 'toxcore_tests::network_tests::networking_core_register_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4


failures:
    toxcore_tests::network_tests::networking_core_new_test
    toxcore_tests::network_tests::networking_core_register_test

test result: FAILED. 248 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

Instead, this happened: 250 tests passed:

```
~/zetox$ cargo test -j8
   Compiling winapi v0.2.8
   Compiling winapi-build v0.1.1
   Compiling rustc-serialize v0.3.24
   Compiling regex-syntax v0.3.9
   Compiling utf8-ranges v0.1.3
   Compiling memchr v0.1.11
   Compiling tokio-timer v0.1.2
   Compiling env_logger v0.4.3
   Compiling aho-corasick v0.5.3
   Compiling kernel32-sys v0.2.2
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.7
   Compiling regex v0.1.80
   Compiling env_logger v0.3.5
   Compiling quickcheck v0.4.1
   Compiling tox v0.0.1 (file:///home/humbug/zetox)
    Finished dev [unoptimized + debuginfo] target(s) in 20.8 secs
     Running target/debug/deps/tox-496c483329a13367

running 250 tests
test toxcore::dht::test::bucket_default_test ... ok
test toxcore::dht::test::bucket_position_test ... ok
ERROR:tox::toxcore::dht: Treating Some(0) as None
test toxcore::dht_node::test::dht_node_create_getn_test ... ok
test toxcore::dht_node::test::dht_node_create_ping_req_test ... ok
test toxcore::dht::test::kbucket_position_test ... ok
test toxcore::dht::test::dht_packet_new_test ... ok
test toxcore::dht::test::kbucket_iter_next_test ... ok
test toxcore::dht::test::bucket_iter_next_test ... ok
test toxcore::dht_node::test::dht_node_new ... ok
test toxcore::dht_node::test::dht_node_pk_test ... ok
test toxcore::dht_node::test::dht_node_create_ping_resp_test ... ok
test toxcore::dht_node::test::dht_node_request_nodes_test ... ok
test toxcore::dht_node::test::dht_node_request_ping_test ... ok
test toxcore::dht::test::kbucket_contains_test ... ok
ERROR:tox::toxcore::dht: Treating Some(0) as None
test toxcore::dht::test::bucket_contains_test ... ok
test toxcore::dht_node::test::dht_node_sk_test ... ok
test toxcore::dht::test::kbucket_can_add_test ... ok
test toxcore::dht_node::test::dht_node_handle_packet_sendn_test ... ok
test toxcore::dht_node::test::dht_node_handle_packet ... ok
test toxcore::dht_node::test::dht_node_respond_ping_test ... ok
test toxcore::dht_node::test::tox_codec_decode_test ... ok
test toxcore::state_format::old::dht_state_kind_test ... ok
test toxcore::state_format::old::eof_kind_test ... ok
test toxcore::dht_node::test::dht_node_create_sendn_test ... ok
test toxcore::state_format::old::friend_state_new_from_pk_test ... ok
test toxcore::dht_node::test::tox_codec_encode_test ... ok
test toxcore::state_format::old::friends_kind_test ... ok
test toxcore::state_format::old::name_kind_test ... ok
test toxcore::state_format::old::name_to_bytes_test ... ok
test toxcore::state_format::old::nospam_keys_kind_test ... ok
test toxcore::state_format::old::path_nodes_kind_test ... ok
test toxcore::dht_node::test::dht_node_send_nodes ... ok
test toxcore::state_format::old::path_nodes_test ... ok
test toxcore::dht_node::test::dht_node_request_nodes_close_test ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_name ... ok
test toxcore::dht_node::test::dht_node_try_add_to_empty ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_nospamkeys ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_dht ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_status ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_status_msg ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_path_nodes ... ok
test toxcore::state_format::old::friends_is_friend_test ... ok
test toxcore::dht_node::test::receive_packets_test ... ok
test toxcore::dht_node::test::send_packets_test ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_tcp_relays ... ok
test toxcore::state_format::old::friend_state_parse_bytes_test ... ok
test toxcore::state_format::old::section_data_into_sect_test_dht ... ok
test toxcore::state_format::old::section_data_into_sect_test_eof ... ok
test toxcore::state_format::old::section_data_into_sect_test_name ... ok
test toxcore::state_format::old::section_data_into_sect_test_friends ... ok
test toxcore::state_format::old::section_data_into_sect_test_nospamkeys ... ok
test toxcore::state_format::old::section_data_parse_bytes_test ... ok
test toxcore::state_format::old::section_data_into_section_test_random ... ok
test toxcore::state_format::old::section_data_into_sect_test_status ... ok
test toxcore::state_format::old::section_data_into_sect_test_path_nodes ... ok
test toxcore::state_format::old::section_data_into_sect_test_status_msg ... ok
test toxcore::state_format::old::status_msg_kind_test ... ok
test toxcore::state_format::old::status_msg_to_bytes_test ... ok
test toxcore::state_format::old::tcp_relays_kind_test ... ok
test toxcore::state_format::old::state_add_friend_norequest_test ... ok
test toxcore::state_format::old::user_status_kind_test ... ok
test toxcore::tcp::codec::tests::decode_encrypted_packet_incomplete ... ok
test toxcore::tcp::codec::tests::decode_encrypted_packet_wrong_key ... ok
test toxcore::tcp::codec::tests::decode_encrypted_packet_zero_length ... ok
test toxcore::tcp::codec::tests::decode_packet_error ... ok
test toxcore::tcp::codec::tests::decode_packet_imcomplete ... ok
test toxcore::tcp::codec::tests::encode_decode ... ok
test toxcore::tcp::codec::tests::encode_packet_too_big ... ok
test toxcore::tcp::handshake::tests::client_decode_incomplete ... ok
test toxcore::tcp::handshake::tests::client_encode_decode ... ok
test toxcore::tcp::handshake::tests::client_encode_too_big ... ok
test toxcore::tcp::handshake::tests::server_decode_incomplete ... ok
test toxcore::tcp::handshake::tests::server_encode_decode ... ok
test toxcore::tcp::handshake::tests::server_encode_too_big ... ok
test toxcore::tcp::secure::tests::test_secure_communication ... ok
test toxcore::tcp::tests::client_handshake_with_bad_payload ... ok
test toxcore::tcp::tests::client_handshake_with_different_keypair ... ok
test toxcore::tcp::tests::network_handshake ... ok
test toxcore::tcp::tests::secure_communication_with_handshake ... ok
test toxcore::tcp::tests::server_handshake_with_bad_payload ... ok
test toxcore::tcp::tests::server_handshake_with_different_keypair ... ok
test toxcore::timeout::test::node_timeout_id_test ... ok
test toxcore::state_format::old::section_data_into_sect_test_tcp_relays ... ok
test toxcore::timeout::test::node_timeout_new_test ... ok
test toxcore::timeout::test::node_timeout_pk_test ... ok
test toxcore::timeout::test::timeout_queue_add_test ... ok
test toxcore::timeout::test::timeout_queue_deref_test ... ok
test toxcore::state_format::old::tcp_relays_test ... ok
test toxcore::state_format::old::state_is_own_pk_test ... ok
test toxcore::timeout::test::timeout_queue_get_timed_out_test ... ok
test toxcore::timeout::test::timeout_queue_push_test ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u16_pass ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u32_fail ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u32_pass ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u64_fail ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u64_pass ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u8_fail ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u8_pass ... ok
test toxcore_tests::binary_io_tests::ne_u64_test ... ok
test toxcore_tests::binary_io_tests::xor_checksum_test ... ok
test toxcore::timeout::test::timeout_queue_remove_test ... ok
test toxcore_tests::binary_io_tests::append_zeros_test_u16_fail ... ok
test toxcore_tests::crypto_core_tests::decrypt_data_symmetric_test ... ok
test toxcore_tests::crypto_core_tests::encrypt_data_symmetric_test ... ok
test toxcore_tests::crypto_core_tests::encrypt_precompute_test ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_number_test_0xff0000_plus_0x011000 ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_test_0xf_plus_one ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_test_0xff_max ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_test_0xff_plus_one ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_number_test_zero_plus_0xff00 ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_test_zero_plus_one ... ok
test toxcore_tests::crypto_core_tests::increment_nonce_test_random ... ok
test toxcore_tests::crypto_core_tests::nonce_parse_bytes_test ... ok
test toxcore_tests::crypto_core_tests::public_key_cmp_test_empty ... ok
test toxcore_tests::crypto_core_tests::public_key_cmp_test_random ... ok
test toxcore_tests::crypto_core_tests::public_key_valid_test ... ok
test toxcore_tests::crypto_core_tests::public_key_parse_bytes_test ... ok
test toxcore_tests::crypto_core_tests::random_u32_test ... ok
test toxcore_tests::crypto_core_tests::random_u64_test ... ok
test toxcore_tests::crypto_core_tests::secret_key_parse_bytes_test ... ok
test toxcore_tests::dht_tests::bucket_1_capacity_try_add_test ... ok
ERROR:tox::toxcore::dht: Treating Some(0) as None
ERROR:tox::toxcore::dht: Treating Some(0) as None
test toxcore_tests::dht_tests::bucket_new_test ... ok
ERROR:tox::toxcore::dht: Treating Some(0) as None
ERROR:tox::toxcore::dht: Treating Some(0) as None
test toxcore_tests::dht_tests::bucket_remove_test ... ok
test toxcore_tests::crypto_core_tests::crypto_init_test ... ok
test toxcore_tests::dht_tests::bucket_try_add_test ... ok
test toxcore_tests::dht_tests::dht_packet_from_bytes_test ... ok
test toxcore_tests::dht_tests::dht_packet_parse_bytes_rest_test ... ok
test toxcore_tests::dht_tests::dht_packet_ping_resp_test ... ok
test toxcore_tests::dht_tests::dht_packet_ping_resp_test_invalid ... ok
test toxcore_tests::dht_tests::dht_packet_to_bytes_test ... ok
test toxcore_tests::dht_tests::dht_paket_get_payload_test ... ok
test toxcore_tests::dht_tests::dht_request_get_request_test ... ok
test toxcore_tests::dht_tests::get_nodes_from_bytes_test ... ok
test toxcore_tests::dht_tests::get_nodes_kind_test ... ok
test toxcore_tests::dht_tests::get_nodes_new_test ... ok
test toxcore_tests::dht_tests::get_nodes_parse_bytes_rest_test ... ok
test toxcore::state_format::old::state_parse_bytes_test_magic ... ok
test toxcore_tests::dht_tests::get_nodes_to_bytes_test ... ok
test toxcore_tests::dht_tests::ip_addr_parse_bytes_rest_test ... ok
test toxcore_tests::dht_tests::ip_addr_to_bytes_test ... ok
test toxcore_tests::dht_tests::ip_type_from_bytes_test ... ok
test toxcore_tests::dht_tests::ip_type_parse_bytes_rest_test ... ok
test toxcore_tests::dht_tests::ipv4_addr_from_bytes_test ... ok
test toxcore_tests::dht_tests::ipv6_addr_from_bytes_test ... ok
test toxcore_tests::dht_tests::dht_request_new_test ... ok
test toxcore_tests::dht_tests::kbucket_index_test ... ok
test toxcore_tests::dht_tests::kbucket_new_test ... ok
test toxcore_tests::dht_tests::bucket_is_empty_test ... ok
test toxcore_tests::dht_tests::kbucket_size_test ... ok
test toxcore_tests::dht_tests::kbucket_try_add_test ... ok
test toxcore_tests::dht_tests::nat_ping_req_deref_test ... ok
test toxcore_tests::dht_tests::nat_ping_req_from_bytes_test ... ok
test toxcore_tests::dht_tests::nat_ping_req_id_test ... ok
test toxcore_tests::dht_tests::nat_ping_req_new_test ... ok
test toxcore_tests::dht_tests::nat_ping_req_parse_bytes_test ... ok
test toxcore_tests::dht_tests::nat_ping_req_to_bytes_test ... ok
test toxcore_tests::dht_tests::nat_ping_resp_deref_test ... ok
test toxcore_tests::dht_tests::nat_ping_resp_from_bytes_test ... ok
test toxcore_tests::dht_tests::nat_ping_resp_id_test ... ok
test toxcore_tests::dht_tests::nat_ping_resp_parse_bytes_test ... ok
test toxcore_tests::dht_tests::nat_ping_resp_to_bytes_test ... ok
test toxcore_tests::dht_tests::nat_ping_resp_to_bytes_test_cmp_to_req ... ok
test toxcore_tests::dht_tests::packed_node_ip_test ... ok
test toxcore_tests::dht_tests::packed_node_new_test_ip_type_TCP_IPv4 ... ok
test toxcore_tests::dht_tests::packed_node_new_test_ip_type_TCP_IPv6 ... ok
test toxcore_tests::dht_tests::packed_node_new_test_ip_type_UDP_IPv4 ... ok
test toxcore_tests::dht_tests::packed_node_new_test_ip_type_UDP_IPv6 ... ok
test toxcore_tests::dht_tests::packed_node_parse_bytes_multiple_n_test ... ok
test toxcore::state_format::old::state_parse_bytes_test_section_detect ... ok
test toxcore_tests::dht_tests::packed_node_parse_bytes_multiple_test ... ok
test toxcore_tests::dht_tests::packed_node_parse_bytes_test_port ... ok
test toxcore_tests::dht_tests::packed_node_to_bytes_test_ipv4 ... ok
test toxcore_tests::dht_tests::packed_nodes_from_bytes_test ... ok
test toxcore_tests::dht_tests::packed_nodes_from_bytes_test_length_short ... ok
test toxcore::timeout::test::node_timeout_is_timed_out_test ... ok
test toxcore_tests::dht_tests::packed_node_to_bytes_test_ipv6 ... ok
test toxcore_tests::dht_tests::packed_nodes_from_bytes_test_length_too_long ... ok
test toxcore_tests::dht_tests::packed_nodes_from_bytes_test_wrong_iptype ... ok
test toxcore_tests::dht_tests::packed_nodes_from_bytes_test_no_iptype ... ok
test toxcore_tests::dht_tests::packed_nodes_to_bytes_test_pk ... ok
test toxcore_tests::dht_tests::ping_req_id_test ... ok
test toxcore_tests::dht_tests::ping_req_kind_test ... ok
test toxcore_tests::dht_tests::ping_req_new_test ... ok
test toxcore_tests::dht_tests::ping_req_from_bytes_test ... ok
test toxcore_tests::dht_tests::packed_nodes_parse_bytes_test_length_too_long ... ok
test toxcore_tests::dht_tests::ping_req_to_bytes_test ... ok
test toxcore_tests::dht_tests::ping_resp_from_test ... ok
test toxcore_tests::dht_tests::ping_resp_id_test ... ok
test toxcore_tests::dht_tests::ping_resp_kind_test ... ok
test toxcore_tests::dht_tests::ping_req_parse_test ... ok
test toxcore_tests::dht_tests::ping_resp_to_bytes_test ... ok
test toxcore_tests::dht_tests::ping_resp_to_bytes_test_cmp_ping_req ... ok
test toxcore_tests::dht_tests::public_key_distance_test ... ok
test toxcore_tests::dht_tests::ping_resp_parse_test ... ok
test toxcore_tests::dht_tests::ping_resp_from_bytes_test ... ok
test toxcore_tests::dht_tests::send_nodes_kind_test ... ok
test toxcore_tests::dht_tests::send_nodes_to_bytes_test ... ok
test toxcore_tests::dht_tests::kbucket_remove_test ... ok
test toxcore_tests::network_tests::bind_udp_test ... ok
test toxcore_tests::network_tests::networking_core_new_test ... ok
test toxcore_tests::network_tests::networking_core_register_test ... ok
test toxcore_tests::packet_kind_tests::packet_kind_from_bytes_test ... ok
thread 'thread '<unnamed><unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }' panicked at '', /checkout/src/libcore/result.rs:called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }906', /checkout/src/libcore/result.rs:4
:906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
ERROR:tox::toxcore::network: Failed to bind to any port in range!
thread '<unnamed>' panicked at 'This should have worked; bind_udp()', src/toxcore_tests/network_tests.rs:82:24
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
test toxcore_tests::packet_kind_tests::user_status_parse_bytes_rest_test ... okthread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', ERROR:tox::toxcore::network: Failed to bind to any port in range!/checkout/src/libcore/result.rs
:thread '906:4
<unnamed>' panicked at 'This should have worked; bind_udp()', src/toxcore_tests/network_tests.rs:82:24

thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }thread 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', <unnamed>', /checkout/src/libcore/result.rs' panicked at '/checkout/src/libcore/result.rs:called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }:906thread '', 906:<unnamed>:4' panicked at '4
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
', /checkout/src/libcore/result.rs:906:4
thread 'thread '<unnamed><unnamed>thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }/checkout/src/libcore/result.rs', :/checkout/src/libcore/result.rs906:906' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }<unnamed>thread '' panicked at '<unnamed>thread ':<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', ', thread ':thread '/checkout/src/libcore/result.rs<unnamed><unnamed>:' panicked at '' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', <unnamed>/checkout/src/libcore/result.rs:/checkout/src/libcore/result.rs' panicked at '906:called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }:', 44called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
4
ERROR:tox::toxcore::network: Failed to bind to any port in range!906:thread '4
thread 'thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4

called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906thread ':<unnamed>4' panicked at '
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906/checkout/src/libcore/result.rs::
4906
:4
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
', /checkout/src/libcore/result.rs<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }
:906thread '<unnamed>' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }<unnamed>', ' panicked at '/checkout/src/libcore/result.rscalled `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', :thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }thread '', <unnamed>/checkout/src/libcore/result.rs' panicked at ':called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }906', :/checkout/src/libcore/result.rs4:
906:4
thread '<unnamed>' panicked at 'This should have worked; bind_udp()', src/toxcore_tests/network_tests.rs:82:24
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
:906', :/checkout/src/libcore/result.rs:906:44

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
4
/checkout/src/libcore/result.rs:906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
thread '<unnamed>thread '' panicked at '<unnamed>called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }' panicked at '', called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }/checkout/src/libcore/result.rs', :/checkout/src/libcore/result.rs906::9064:
4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
thread 'thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
', thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
/checkout/src/libcore/result.rs:906:4
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', /checkout/src/libcore/result.rs:906:4
test toxcore_tests::dht_tests::send_nodes_with_nodes_test ... ok
test toxcore_tests::dht_tests::send_nodes_from_bytes_test ... ok
test toxcore_tests::dht_tests::send_nodes_parse_bytes_rest_test ... ok
test toxcore_tests::state_format_old_tests::friend_status_parse_bytes_rest_test ... ok
test toxcore_tests::state_format_old_tests::dht_state_from_bytes ... ok
test toxcore_tests::state_format_old_tests::dht_state_parse_bytes_rest_test ... ok
test toxcore_tests::state_format_old_tests::dht_state_to_bytes_test ... ok
test toxcore_tests::state_format_old_tests::name_parse_bytes_test ... ok
test toxcore_tests::state_format_old_tests::nospam_keys_default_test ... ok
test toxcore_tests::state_format_old_tests::nospam_keys_from_bytes_test ... ok
test toxcore_tests::state_format_old_tests::nospam_keys_parse_bytes_rest_test ... ok
test toxcore_tests::state_format_old_tests::section_kind_parse_bytes_rest_test ... ok
test toxcore_tests::state_format_old_tests::section_kind_parse_bytes_test ... ok
test toxcore_tests::state_format_old_tests::section_kind_to_bytes_test ... ok
test toxcore_tests::dht_tests::kbucket_get_closest_test ... ok
test toxcore_tests::dht_tests::get_nodes_response_test ... ok
test toxcore_tests::state_format_old_tests::user_status_default_test ... ok
test toxcore_tests::state_format_old_tests::user_status_parse_bytes_test ... ok
test toxcore_tests::state_format_old_tests::status_message_parse_bytes_test ... ok
test toxcore_tests::state_format_old_tests::user_status_to_bytes_test ... ok
test toxcore_tests::toxid_tests::no_spam_default_test ... ok
test toxcore_tests::toxid_tests::no_spam_fmt_test ... ok
test toxcore_tests::state_format_old_tests::user_status_parse_bytes_test_rest ... ok
test toxcore_tests::toxid_tests::no_spam_new_test ... ok
test toxcore_tests::toxid_tests::no_spam_parse_bytes_rest_test ... ok
test toxcore_tests::toxid_tests::no_spam_from_bytes_test ... ok
test toxcore_tests::toxid_tests::tox_id_fmt_test ... ok
test toxcore_tests::toxid_tests::tox_id_new_nospam_test ... ok
test toxcore_tests::toxid_tests::tox_id_from_bytes_test ... ok
test toxcore_tests::toxid_tests::tox_id_to_bytes_test ... ok
test toxcore_tests::toxid_tests::tox_id_parse_bytes_rest_test ... ok
test toxcore_tests::state_format_old_tests::friends_add_friend_test ... ok
test toxencryptsave_tests::encryptsave_tests::get_salt_test ... ok
test toxencryptsave_tests::encryptsave_tests::is_encrypted_test ... ok
test toxencryptsave_tests::encryptsave_tests::pass_decrypt_error_test ... ok
test toxencryptsave_tests::encryptsave_tests::pass_decrypt_test ... ok
test toxencryptsave_tests::encryptsave_tests::pass_encrypt_error_test ... ok
test toxcore_tests::state_format_old_tests::friends_to_bytes_test ... ok
test toxcore_tests::state_format_old_tests::friends_parse_bytes_test ... ok
test toxcore_tests::state_format_old_tests::state_to_bytes_test ... ok
test toxencryptsave::pass_key_new_test ... ok
test toxencryptsave::pass_key_with_salt_test ... ok
test toxencryptsave_tests::encryptsave_tests::pass_encrypt_test ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_random ... ok
test toxcore::state_format::old::section_data_into_sect_mult_test_friends ... ok
test toxencryptsave_tests::encryptsave_tests::pass_key_decrypt_test ... ok
test toxencryptsave_tests::encryptsave_tests::pass_key_encrypt_test ... ok

test result: ok. 250 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

```

## Meta

`rustc --version --verbose`:
```
rustc 1.24.0-nightly (cfba0d446 2017-12-05)
binary: rustc
commit-hash: cfba0d446e8ab90f0c81aa0942819d05621c8b8e
commit-date: 2017-12-05
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

No backtrace available. Here is a screenshot with green oks to prove the issue is not a joke.

![cargo_test](https://user-images.githubusercontent.com/467709/33660758-0847ca18-da96-11e7-9c05-5987451d2945.png)

The incident is reproducible with 30% chance on https://github.com/zetok/tox/commit/1ceb098a417807392b7eacafd8f2b68713ccf1da with:

```
git co Cargo.lock
cargo clean
cargo test -j8 # expected 2 of 250 failed
cargo update -p clippy
cargo test -j8 # succeeded somehow ?!
```

**Comment by durka** [comment]
"Too many open files" sounds like a fairly random, system-dependent error condition. Is there a reason you expect that to happen every time?

**Comment by sfackler** [comment]
As far as I can tell, none of the threads that panicked were the test threads themselves but rather other threads that were presumably spawned by them. The main test threads will all be named after the test.

**Comment by bjorn3** [comment]
Based on @sfackler's comment this seems to be an issue with your tests not panicking if a helper thread panics rather than an issue with libtest.
