### ISSUE TITLE
[ICE] with universal_impl_trait

### ISSUE THREAD

**Issue by rizakrko** [rust-lang/rust#46584]
Following code produces ICE:
`main.rs`

```
extern crate test_project;

struct Foo {}

impl test_project::T for Foo {}

fn main() {
    test_project::test_fn(Foo {});
}
```
`lib.rs`
```
#![feature(universal_impl_trait)]

pub trait T {}
pub fn test_fn(t: impl T) {}
```
I expected to see this happen: Code compiles
Instead, this happened: 
```
error: internal compiler error: /checkout/src/librustc_trans_utils/collector.rs:743: Cannot create local trans-item for DefId(11/0:4 ~ test_project[7b49]::test_fn[0])
```
## Meta
`rustc --version --verbose`:
```
rustc 1.24.0-nightly (c8ddf2852 2017-12-07)
binary: rustc
commit-hash: c8ddf28527119a06a9f5da9bd34c97ae97afe531
commit-date: 2017-12-07
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```
Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:501:8
stack backtrace:
   0:     0x7fa24b53c29b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he397ff399ab10f70
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fa24b54a50e - std::sys_common::backtrace::print::hb3c6b7045fdb6844
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x7fa24b543ef0 - std::panicking::default_hook::{{closure}}::ha933d0ad7dfae7df
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7fa24b543bf5 - std::panicking::default_hook::hb335bd8cf8a46857
                               at /checkout/src/libstd/panicking.rs:391
   4:     0x7fa24b5443cb - std::panicking::rust_panic_with_hook::h97bc3b62dd4043a0
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7fa245d7ff17 - std::panicking::begin_panic::haa21720f5950667e
   6:     0x7fa245d9d981 - rustc_errors::Handler::bug::h530dee93ced7726c
   7:     0x7fa2475c30bf - <std::thread::local::LocalKey<T>>::with::h661c270223aa7d49
   8:     0x7fa2477d3fee - rustc::ty::context::tls::with_opt::h04a8f43ade461d80
   9:     0x7fa2473de937 - rustc::session::opt_span_bug_fmt::h4a68404fdea86ebf
  10:     0x7fa2473de846 - rustc::session::bug_fmt::h0f3f82c9190314e7
  11:     0x7fa2486a2328 - rustc_trans_utils::collector::should_trans_locally::h7f6e93eff47ee0aa
  12:     0x7fa2486a20f4 - rustc_trans_utils::collector::visit_instance_use::hb4dfc2f5ac03ee18
  13:     0x7fa2486a20b4 - rustc_trans_utils::collector::visit_fn_use::h948027a218a5f140
  14:     0x7fa2486a18ea - <rustc_trans_utils::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind::h77fe79a7ec747854
  15:     0x7fa24869f0fa - rustc::mir::visit::Visitor::visit_mir::h6b0d43fd9b906726
  16:     0x7fa2486a028e - rustc_trans_utils::collector::collect_items_rec::heb5ce4fd21f8755b
  17:     0x7fa24869f5dd - rustc_trans_utils::collector::collect_crate_translation_items::h8d911e4ec1f7fab7
  18:     0x7fa2499d57af - rustc::util::common::time::h9594a33375515789
  19:     0x7fa249904ab0 - rustc_trans::base::collect_and_partition_translation_items::h04375b7d84f115ae
  20:     0x7fa2476f6e00 - rustc::dep_graph::graph::DepGraph::with_task_impl::h7e60845912e15129
  21:     0x7fa247359f98 - rustc_errors::Handler::track_diagnostics::hb811bb8b256bd17d
  22:     0x7fa24787b790 - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check::h162d730623a0a166
  23:     0x7fa2475264bf - rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::force::h4de6323b20aea870
  24:     0x7fa247526c1e - rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get::h90f7144b602ec2df
  25:     0x7fa247637ca7 - rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items::ha98b2ff74f983210
  26:     0x7fa2478d943e - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items::h259e7450f896c098
  27:     0x7fa2499029f8 - rustc_trans::base::trans_crate::h0f50ca66a934980d
  28:     0x7fa249994c46 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::h014a424647baa493
  29:     0x7fa24b8ff8a7 - rustc::util::common::time::h8f3dc720d560e0e5
  30:     0x7fa24b92f40d - rustc_driver::driver::phase_4_translate_to_llvm::h26bdd0eda70a9cfb
  31:     0x7fa24b9727b2 - rustc_driver::driver::compile_input::{{closure}}::h029d7e3a020dd2aa
  32:     0x7fa24b96ba11 - <std::thread::local::LocalKey<T>>::with::ha09fe06cbd6872eb
  33:     0x7fa24b9680e6 - <std::thread::local::LocalKey<T>>::with::h3bd11e5486ef383b
  34:     0x7fa24b9b49a7 - rustc::ty::context::TyCtxt::create_and_enter::ha7b863438f1f46a0
  35:     0x7fa24b92a5f4 - rustc_driver::driver::compile_input::h30cbeda331948b93
  36:     0x7fa24b9c4153 - rustc_driver::run_compiler::h8871ce8dbc735fff
  37:     0x7fa24b909241 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf1041df6796406b7
  38:     0x7fa24b5765ce - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:101
  39:     0x7fa24b985f72 - <F as alloc::boxed::FnBox<A>>::call_box::h7606daa916ddac39
  40:     0x7fa24b5326cb - std::sys::unix::thread::Thread::new::thread_start::hae1fcb3fb5b43dda
                               at /checkout/src/liballoc/boxed.rs:827
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  41:     0x7fa2454f57fb - start_thread
  42:     0x7fa24b218b0e - clone
  43:                0x0 - <unknown>

error: Could not compile `test_project`.

```

**Comment by cramertj** [comment]
This is fixed on the current nightly.
