### ISSUE TITLE
nightly rustdoc ICE - `rustdoc::html::render::Item::src_href` expect failed

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#46675]
I'm attempting to submit a PR for conrod but noticed that travis is failing to build documentation on the current nightly. Here's the relevant part of the output with `--verbose` and `RUST_BACKTRACE=1`

```
 Documenting conrod v0.56.0 (file:///home/mindtree/programming/rust/conrod)
     Running `rustdoc --crate-name conrod src/lib.rs -o /home/mindtree/programming/rust/conrod/target/doc -L dependency=/home/mindtree/programming/rust/conrod/target/debug/deps --extern rusttype=/home/mindtree/programming/rust/conrod/target/debug/deps/librusttype-7a24d47f60459cc0.rlib --extern input=/home/mindtree/programming/rust/conrod/target/debug/deps/libinput-693e50c807e002ee.rlib --extern num=/home/mindtree/programming/rust/conrod/target/debug/deps/libnum-134981b13104da42.rlib --extern conrod_derive=/home/mindtree/programming/rust/conrod/target/debug/deps/libconrod_derive-192bad1d6b6b2c19.so --extern daggy=/home/mindtree/programming/rust/conrod/target/debug/deps/libdaggy-d429e8d942046223.rlib --extern fnv=/home/mindtree/programming/rust/conrod/target/debug/deps/libfnv-e7f66d21584a9ea3.rlib`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (9fe7aa353 2017-12-11) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'source has no filename', /checkout/src/libcore/option.rs:891:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::option::expect_failed
             at /checkout/src/libcore/option.rs:891
  10: rustdoc::html::render::Item::src_href
             at /checkout/src/libcore/option.rs:302
             at /checkout/src/librustdoc/html/render.rs:1699
  11: <rustdoc::html::render::Item<'a> as core::fmt::Display>::fmt
             at /checkout/src/librustdoc/html/render.rs:1779
  12: core::fmt::write
             at /checkout/src/libcore/fmt/mod.rs:1055
             at /checkout/src/libcore/fmt/mod.rs:1023
  13: std::io::Write::write_fmt
             at /checkout/src/libstd/io/mod.rs:1162
  14: rustdoc::html::layout::render
             at /checkout/src/librustdoc/html/layout.rs:37
  15: rustdoc::html::render::Context::render_item
  16: rustdoc::html::render::Context::item
             at /checkout/src/librustdoc/html/render.rs:1598
  17: rustdoc::html::render::run
             at /checkout/src/librustdoc/html/render.rs:1469

error: Could not document `conrod`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name conrod src/lib.rs -o /home/mindtree/programming/rust/conrod/target/doc -L dependency=/home/mindtree/programming/rust/conrod/target/debug/deps --extern rusttype=/home/mindtree/programming/rust/conrod/target/debug/deps/librusttype-7a24d47f60459cc0.rlib --extern input=/home/mindtree/programming/rust/conrod/target/debug/deps/libinput-693e50c807e002ee.rlib --extern num=/home/mindtree/programming/rust/conrod/target/debug/deps/libnum-134981b13104da42.rlib --extern conrod_derive=/home/mindtree/programming/rust/conrod/target/debug/deps/libconrod_derive-192bad1d6b6b2c19.so --extern daggy=/home/mindtree/programming/rust/conrod/target/debug/deps/libdaggy-d429e8d942046223.rlib --extern fnv=/home/mindtree/programming/rust/conrod/target/debug/deps/libfnv-e7f66d21584a9ea3.rlib` (exit code: 101)
```
Here is the nightly version:
```
[mindtree@mindtree conrod]$ rustc --version
rustc 1.24.0-nightly (9fe7aa353 2017-12-11)
[mindtree@mindtree conrod]$ rustdoc --version
rustdoc 1.24.0-nightly (9fe7aa353 2017-12-11)
```

Both stable and beta build the documentation fine.

**Comment by mitchmindtree** [comment]
I'm no longer getting this on the latest nightly, so I'm guessing this has been fixed! Going to close. If anyone knows what fixed this, I'd appreciate a link to the PR but no worries if not.
