### ISSUE TITLE
Compiler panic related cause by NLLs

### ISSUE THREAD

**Issue by 6A** [rust-lang/rust#47153]
When compiling a project with `#[feature(nll)]` enabled, `rustc` panics because of a failed assertion.

My project has many errors so I can't determine exactly what code is causing a problem; I'll update when I'll know more.

## Backtrace
```
note: rustc 1.24.0-nightly (687d3d15b 2018-01-02) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: identity_substs.is_empty()', /checkout/src/librustc_mir/borrow_check/nll/universal_regions.rs:593:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_mir::borrow_check::nll::universal_regions::UniversalRegions::new
   7: rustc_mir::borrow_check::nll::replace_regions_in_mir
   8: rustc_mir::borrow_check::do_mir_borrowck
   9: rustc::ty::context::tls::enter
  10: rustc::infer::InferCtxtBuilder::enter
  11: rustc_mir::borrow_check::mir_borrowck
  12: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::compute_result
  13: rustc::dep_graph::graph::DepGraph::with_task_impl
  14: rustc_errors::Handler::track_diagnostics
  15: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::force
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::try_get
  18: rustc::ty::maps::TyCtxtAt::mir_borrowck
  19: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  20: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::{{closure}}
  21: <std::thread::local::LocalKey<T>>::with
  22: <std::thread::local::LocalKey<T>>::with
  23: rustc::ty::context::TyCtxt::create_and_enter
  24: rustc_driver::driver::compile_input
  25: rustc_driver::run_compiler
```

## Version
```
rustc 1.24.0-nightly (687d3d15b 2018-01-02)
binary: rustc
commit-hash: 687d3d15ba726dbb1ac6b85223ebe0e98c6820cc
commit-date: 2018-01-02
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

**Comment by nikomatsakis** [comment]
Can you give any sort of link to code that reproduces the problem?

**Comment by 6A** [comment]
I tried fixing the project to determine what exactly caused the issue, but couldn't find exactly what code was doing this. If no similar issue is encountered, I can try rolling back my old code and see if I can make it crash again.

**Comment by nikomatsakis** [comment]
I don't recall seeing any similar ICEs.

**Comment by mtanski** [comment]
Ran into this bug here: https://github.com/mtanski/dbkit/tree/nll-build-crash

Regular build (`cargo build`) doesn't crash it, but building test code (`cargo test`) does.

Could not slim down the test case. Attempts at it make the bug go away.

**Version**
```
mtanski@crunchy:~/src/dbkit$ rustup show
Default host: x86_64-unknown-linux-gnu

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.25.0-nightly (79a521bb9 2018-01-15)
```

**Crash**
```
mtanski@crunchy:~/src/dbkit$ RUST_BACKTRACE=1 cargo test
   Compiling dbkit-engine v0.0.9 (file:///home/mtanski/src/dbkit)

...

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (79a521bb9 2018-01-15) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: identity_substs.is_empty()', librustc_mir/borrow_check/nll/universal_regions.rs:593:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
   6: rustc_mir::borrow_check::nll::universal_regions::UniversalRegions::new
   7: rustc::ty::context::tls::enter
   8: rustc::infer::InferCtxtBuilder::enter
   9: rustc_mir::borrow_check::mir_borrowck
  10: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::compute_result
  11: rustc::dep_graph::graph::DepGraph::with_task_impl
  12: rustc_errors::Handler::track_diagnostics
  13: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::force
  15: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::try_get
  16: rustc::ty::maps::TyCtxtAt::mir_borrowck
  17: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  18: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::{{closure}}
  19: <std::thread::local::LocalKey<T>>::with
  20: <std::thread::local::LocalKey<T>>::with
  21: rustc::ty::context::TyCtxt::create_and_enter
  22: rustc_driver::driver::compile_input
  23: rustc_driver::run_compiler

error: Could not compile `dbkit-engine`.

To learn more, run the command again with --verbose.
```

**Comment by nikomatsakis** [comment]
[Minimized example](https://play.rust-lang.org/?gist=5b1641ce203dc471c5372f9eb19aa434&version=nightly):

```rust
#![feature(nll)]

trait Foo {
    const B: bool = true;
}

fn main() { }
```

**Comment by nikomatsakis** [comment]
Hmm, I tried running `cargo test` locally but did not encounter the bug. Honestly I think we can just remove the asseron.

**Comment by nikomatsakis** [comment]
The problem is this assertion is firing:

https://github.com/rust-lang/rust/blob/da569fa9ddf8369a9809184d43c600dc06bd4b4d/src/librustc_mir/borrow_check/nll/universal_regions.rs#L593

My assumption in writing that code was that constant values were never generic. But that was simply not true, as these examples show. I suspect we can just remove the assertion, actually, though I'm trying to see if this was important for some other reason.

**Comment by Pulkit07** [comment]
Thanks @nikomatsakis for helping in breaking down the bug, I will take care of this.

**Comment by nikomatsakis** [comment]
@Pulkit07 too late ;)

**Comment by Pulkit07** [comment]
@nikomatsakis hehe, no worries
