### ISSUE TITLE
Wasm build works in debug mode, fails with --release

### ISSUE THREAD

**Issue by ndarilek** [rust-lang/rust#47221]
I'm hacking on wasm-based game development in [this repository](https://gitlab.com/ndarilek/rust-wasm-gamedev). The master branch of the above repository successfully builds in debug mode on stable and nightly if I run:

```
export RUSTFLAGS="-C link-arg=-s -C link-arg=USE_SDL=2"
cargo build --target="wasm32-unknown-emscripten"
```

But if I run:

```
cargo build --target="wasm32-unknown-emscripten" --release
```

I get:

```
  = note: WARNING:root:emcc: cannot find library "SDL2"
          WARNING:root:object /tmp/emscripten_temp_75vQ5__archive_contents/recs-c24c169ddc07da30.recs0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_75vQ5__archive_contents/recs-c24c169ddc07da30.recs0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_1RHLlw_archive_contents/alto-32a6704552f5fb58.alto0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_1RHLlw_archive_contents/alto-32a6704552f5fb58.alto0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_cTzX_D_archive_contents/nphysics2d-2e16980c0c81cc7c.nphysics2d0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_cTzX_D_archive_contents/nphysics2d-2e16980c0c81cc7c.nphysics2d0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_ERvIDk_archive_contents/parking_lot-c261a91d82f23854.parking_lot0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_ERvIDk_archive_contents/parking_lot-c261a91d82f23854.parking_lot0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_HwU6cy_archive_contents/owning_ref-84acb8553a658820.owning_ref0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_FgJ_7r_archive_contents/parking_lot_core-905428f789805305.parking_lot_core0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_FgJ_7r_archive_contents/parking_lot_core-905428f789805305.parking_lot_core0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Vvbc1A_archive_contents/smallvec-37f32ce66f63d893.smallvec0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_zdJvJX_archive_contents/lewton-c506aceeb5edae50.lewton0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_zdJvJX_archive_contents/lewton-c506aceeb5edae50.lewton0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_UmwnFr_archive_contents/sdl2-774c6f83df1849a0.sdl20.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_UmwnFr_archive_contents/sdl2-774c6f83df1849a0.sdl20.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_obHxWs_archive_contents/bitflags-5abdbf62d355981e.bitflags0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_vLO9OM_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_vLO9OM_archive_contents/num-6cfc17ceaa54ff0e.num0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_lKPc3e_archive_contents/num_iter-81eea78158cd5d73.num_iter0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_V8z0Xu_archive_contents/failure-8be8cb0c478d307e.failure0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_V8z0Xu_archive_contents/failure-8be8cb0c478d307e.failure0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_X5J0Qj_archive_contents/backtrace-747d90696f19176f.backtrace0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_X5J0Qj_archive_contents/backtrace-747d90696f19176f.backtrace0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_bSOqR2_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_bSOqR2_archive_contents/rustc_demangle-b34068dccbe1202d.rustc_demangle0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_bSOqR2_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_bSOqR2_archive_contents/rustc_demangle-b34068dccbe1202d.rustc_demangle0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Mk0hDA_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Mk0hDA_archive_contents/cfg_if-a7fd0fe9ff9fd6cb.cfg_if0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Idk1ip_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Idk1ip_archive_contents/ncollide-ebe71d9bb775f163.ncollide0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_OX3RlD_archive_contents/ncollide_pipeline-e76a47562ea4db98.ncollide_pipeline0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_OX3RlD_archive_contents/ncollide_pipeline-e76a47562ea4db98.ncollide_pipeline0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_6sWI5u_archive_contents/ncollide_transformation-b4d8518a97fa9f99.ncollide_transformation0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_1fJidp_archive_contents/ncollide_procedural-a60a5c6112ce6f6a.ncollide_procedural0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_FddB5q_archive_contents/ncollide_geometry-462a72a897d83c59.ncollide_geometry0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_FddB5q_archive_contents/ncollide_geometry-462a72a897d83c59.ncollide_geometry0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_6ST1nC_archive_contents/ncollide_utils-abc94fe08523afdf.ncollide_utils0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_6ST1nC_archive_contents/ncollide_utils-abc94fe08523afdf.ncollide_utils0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Gp1Suq_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Gp1Suq_archive_contents/ncollide_math-8b52198f3449fffc.ncollide_math0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Gp1Suq_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_Gp1Suq_archive_contents/ncollide_math-8b52198f3449fffc.ncollide_math0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_gkSH0E_archive_contents/nalgebra-5d2c70f5540a5bc7.nalgebra0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_WshJ9q_archive_contents/matrixmultiply-b4aec5b2a99f9c2c.matrixmultiply0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_naHgoQ_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_naHgoQ_archive_contents/rawpointer-6362b3a0187cc424.rawpointer0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_GTvbTJ_archive_contents/generic_array-0df6567777d1adbd.generic_array0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_s4MY1R_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_s4MY1R_archive_contents/nodrop-e0ba5fbbf029a224.nodrop0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_8dNk_s_archive_contents/typenum-97e6ba0c00176e21.typenum0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_xJFYUb_archive_contents/rand-18dd4d115d1a7fe9.rand0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_xJFYUb_archive_contents/rand-18dd4d115d1a7fe9.rand0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_UtnKVf_archive_contents/libc-463e29423bc365b9.libc0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_6EgvMV_archive_contents/alga-a30302d0f7ebf310.alga0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp__PzRUh_archive_contents/num_complex-ffa5fd74cd58485e.num_complex0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_ZxKGRu_archive_contents/approx-3ff8b90b9c8e97df.approx0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_A5jx91_archive_contents/rustc_serialize-0163f6b4ae10d21a.rustc_serialize0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_YxFwBy_archive_contents/stdweb-90c5f6e93da5b9ce.stdweb0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_YxFwBy_archive_contents/stdweb-90c5f6e93da5b9ce.stdweb0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_mDqxDr_archive_contents/serde_json-4c0e8bce188320b1.serde_json0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_bIt0ce_archive_contents/dtoa-c6fe42da0e171c9d.dtoa0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_peIAZr_archive_contents/serde-5192932ad7d38ade.serde0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_peIAZr_archive_contents/serde-5192932ad7d38ade.serde0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_6pmoWB_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_6pmoWB_archive_contents/itoa-27dc9f6b2ff5bcf6.itoa0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_b4hP3b_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_b4hP3b_archive_contents/lazy_static-f20787c324f8972c.lazy_static0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_qS1Om9_archive_contents/stable_deref_trait-14823485b98f7337.stable_deref_trait0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_2EChTe_archive_contents/al_sys-fb34f5693085e370.al_sys0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_2EChTe_archive_contents/al_sys-fb34f5693085e370.al_sys0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_hXu0DU_archive_contents/ogg-52d188d37fddfa25.ogg0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_hXu0DU_archive_contents/ogg-52d188d37fddfa25.ogg0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_x_6B4P_archive_contents/byteorder-564bf00960afabb3.byteorder0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_MFQkdM_archive_contents/num_integer-804f3c47caf4d67c.num_integer0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_023egM_archive_contents/num_traits-49299b980a496015.num_traits0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_ci3nlH_archive_contents/sdl2_sys-74a498dd593ced55.sdl2_sys0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_ci3nlH_archive_contents/sdl2_sys-74a498dd593ced55.sdl2_sys0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_P6tkn2_archive_contents/std-827ddea93328ae2d.std0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_P6tkn2_archive_contents/std-827ddea93328ae2d.std0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_vkeEjT_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_vkeEjT_archive_contents/panic_unwind-8cb97051d8238386.panic_unwind0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_vkeEjT_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_vkeEjT_archive_contents/panic_unwind-8cb97051d8238386.panic_unwind0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_cEIXbe_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_cEIXbe_archive_contents/unwind-25cc9b024a02d330.unwind0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_cEIXbe_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_cEIXbe_archive_contents/unwind-25cc9b024a02d330.unwind0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_r8ohgK_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_r8ohgK_archive_contents/alloc_system-751808ba756769d5.alloc_system0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_r8ohgK_archive_contents/rust.metadata.bin is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_r8ohgK_archive_contents/alloc_system-751808ba756769d5.alloc_system0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_c4yBK8_archive_contents/libc-d42e80cee81b06ce.libc0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_nbpEv__archive_contents/alloc-78c21267a2dc15c1.alloc0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_nbpEv__archive_contents/alloc-78c21267a2dc15c1.alloc0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_DaXLET_archive_contents/std_unicode-0e1b544c94586415.std_unicode0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_DaXLET_archive_contents/std_unicode-0e1b544c94586415.std_unicode0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_7o8hCz_archive_contents/rand-3d7b10e850a67e89.rand0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_7o8hCz_archive_contents/rand-3d7b10e850a67e89.rand0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_aYbLv8_archive_contents/core-0c5e3d6c117f8c44.core0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_aYbLv8_archive_contents/core-0c5e3d6c117f8c44.core0.rust-cgu.bytecode.encoded is not valid, cannot link
          WARNING:root:object /tmp/emscripten_temp_J55lnQ_archive_contents/compiler_builtins-bd7cc5ada1e908e0.compiler_builtins0.rust-cgu.bytecode.encoded is not valid, cannot link
          
          /home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
                  throw new JS_Parse_Error(message, line, col, pos);
                  ^
          TypeError: (intermediate value) is not a function
              at new JS_Parse_Error (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
              at js_error (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
              at croak (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
              at token_error (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
              at unexpected (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
              at Object.semicolon (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
              at prog1 (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
              at simple_statement (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
              at /home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
              at block_ (/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:999:32)
          Traceback (most recent call last):
            File "/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/emcc", line 13, in <module>
              emcc.run()
            File "/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/emcc.py", line 1849, in run
              wasm_text_target, misc_temp_files, optimizer)
            File "/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/emcc.py", line 2391, in do_binaryen
              emit_symbol_map=emit_symbol_map)
            File "/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/shared.py", line 2295, in minify_wasm_js
              js_file = Building.js_optimizer_no_asmjs(js_file, passes)
            File "/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/shared.py", line 2168, in js_optimizer_no_asmjs
              subprocess.check_call(NODE_JS + [js_optimizer.JS_OPTIMIZER, filename] + passes, stdout=open(next, 'w'))
            File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['/home/nolan/opt/home/nolan/opt/emsdk-portable/node/4.1.1_64bit/bin/node', '/home/nolan/opt/home/nolan/opt/emsdk-portable/emscripten/incoming/tools/js-optimizer.js', '/tmp/tmp47hhYu/tts.bc.o.js.mem.js', 'noPrintMetadata', 'AJSDCE', 'minifyWhitespace']' returned non-zero exit status 1
          

error: aborting due to previous error

error: Could not compile `tts`.
To learn more, run the command again with --verbose.
```

There are no other changes in the codebase. Not sure why it finds SDL when compiled in debug mode but fails with `--release`. I'm currently running emsdk as of late December. Not sure at what point this started, as I only recently began attempting release builds. Some initial debugging work was done at koute/cargo-web#31 but this is clearly not a cargo-web error.

Sorry if this is a dupe, I'm in a bit over my head with this one and don't know what to look for. :)

**Comment by ndarilek** [comment]
We figured it out. Seems it's a problem with Emscripten's uglify step run in release mode not liking ES6 syntax, which I use in my code. https://github.com/koute/cargo-web/issues/31#issuecomment-355647212

Is this something that rustc can even fix? Could it provide a better error message, or is this an Emscripten issue? It's hard to know where the problem lies with projects built on projects built on projects. :)

Thanks.

**Comment by tlively** [comment]
It sounds like this is an Emscripten issue (and possibly already fixed, idk) and not a Rust issue. @alexcrichton This issue can probably be closed.
