### ISSUE TITLE
Embedded in Rust

### ISSUE THREAD

**Issue by uscmule** [rust-lang/rust#47303]
I was following this tutorial:
http://blog.japaric.io/quickstart/

when I run:
xargo build --example hello

I see:
```
$ RUST_BACKTRACE=1 xargo build --example hello --verbose
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
+ RUSTFLAGS="-C link-arg=-Tlink.x -C linker=arm-none-eabi-ld -Z linker-flavor=ld --sysroot /home/ubuntu/.xargo"
+ "cargo" "build" "--example" "hello" "--verbose"
       Fresh aligned v0.1.1
       Fresh vcell v0.1.0
       Fresh cortex-m-semihosting v0.1.3
       Fresh r0 v0.2.2
       Fresh volatile-register v0.2.0
       Fresh cortex-m v0.2.12
       Fresh cortex-m-rt v0.2.5
   Compiling cortex-m-quickstart v0.1.9 (file:///home/ubuntu/src/cortex-m-quickstart)
     Running `rustc --crate-name hello examples/hello.rs --crate-type bin --emit=dep-info,link -C codegen-units=1 -C debuginfo=2 -C metadata=160a26b47f773a97 -C extra-filename=-160a26b47f773a97 --out-dir /home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/examples --target thumbv7em-none-eabihf -C incremental=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/incremental -L dependency=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps -L dependency=/home/ubuntu/src/cortex-m-quickstart/target/debug/deps --extern cortex_m=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps/libcortex_m-a2de18ac99d3bfe1.rlib --extern cortex_m_rt=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps/libcortex_m_rt-01160b032927b9a6.rlib --extern cortex_m_quickstart=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps/libcortex_m_quickstart-bfac0bbe4ea2a1e9.rlib -C link-arg=-Tlink.x -C linker=arm-none-eabi-ld -Z linker-flavor=ld --sysroot /home/ubuntu/.xargo -L /home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/build/cortex-m-quickstart-60554625ac353680/out -L /home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/build/cortex-m-rt-26c7a180cdb43972/out`
error: internal compiler error: librustc_metadata/cstore_impl.rs:131: get_optimized_mir: missing MIR for `DefId(7/0:8 ~ cortex_m_rt[9c79]::lang_items[0]::start[0])`

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (b5392f545 2018-01-08) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:504:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: <std::thread::local::LocalKey<T>>::with
   8: rustc::ty::context::tls::with_opt
   9: rustc::session::opt_span_bug_fmt
  10: rustc::session::bug_fmt
  11: rustc_metadata::cstore_impl::provide_extern::optimized_mir
  12: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::compute_result
  13: rustc::dep_graph::graph::DepGraph::with_task_impl
  14: rustc_errors::Handler::track_diagnostics
  15: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::force
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::try_get
  18: rustc::ty::maps::TyCtxtAt::optimized_mir
  19: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  20: rustc_mir::monomorphize::collector::collect_items_rec
  21: rustc_mir::monomorphize::collector::collect_crate_mono_items
  22: rustc::util::common::time
  23: rustc_trans::base::collect_and_partition_translation_items
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: rustc_errors::Handler::track_diagnostics
  26: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  27: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::force
  28: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get
  29: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
  30: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items
  31: rustc_trans::base::trans_crate
  32: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  33: rustc_driver::driver::phase_4_translate_to_llvm
  34: rustc_driver::driver::compile_input::{{closure}}
  35: <std::thread::local::LocalKey<T>>::with
  36: <std::thread::local::LocalKey<T>>::with
  37: rustc::ty::context::TyCtxt::create_and_enter
  38: rustc_driver::driver::compile_input
  39: rustc_driver::run_compiler

error: Could not compile `cortex-m-quickstart`.

Caused by:
  process didn't exit successfully: `rustc --crate-name hello examples/hello.rs --crate-type bin --emit=dep-info,link -C codegen-units=1 -C debuginfo=2 -C metadata=160a26b47f773a97 -C extra-filename=-160a26b47f773a97 --out-dir /home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/examples --target thumbv7em-none-eabihf -C incremental=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/incremental -L dependency=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps -L dependency=/home/ubuntu/src/cortex-m-quickstart/target/debug/deps --extern cortex_m=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps/libcortex_m-a2de18ac99d3bfe1.rlib --extern cortex_m_rt=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps/libcortex_m_rt-01160b032927b9a6.rlib --extern cortex_m_quickstart=/home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/deps/libcortex_m_quickstart-bfac0bbe4ea2a1e9.rlib -C link-arg=-Tlink.x -C linker=arm-none-eabi-ld -Z linker-flavor=ld --sysroot /home/ubuntu/.xargo -L /home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/build/cortex-m-quickstart-60554625ac353680/out -L /home/ubuntu/src/cortex-m-quickstart/target/thumbv7em-none-eabihf/debug/build/cortex-m-rt-26c7a180cdb43972/out` (exit code: 101)
```

**Comment by sanpii** [comment]
The same as #47040

**Comment by nagisa** [comment]
Closing because duplicate as noted above.
