### ISSUE TITLE
`cargo test --doc` panics if an empty line is present in a doc comment

### ISSUE THREAD

**Issue by illicitonion** [rust-lang/rust#47323]
```
$ cat src/lib.rs
pub struct S {
    s: String,
}

impl S {
  ///
  /// * `arg` - Blah.
  ///
  ///           Foo.
  ///
  pub fn new(arg: String) -> S {
      S { s: arg }
  }

  pub fn s(&self) -> &str {
      &self.s
  }
}
```
```
$ rustup override set nightly
info: using existing install for 'nightly-x86_64-apple-darwin'
info: override toolchain for '/Users/dwagnerhall/tmp/rustplay' set to 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.25.0-nightly (61452e506 2018-01-09)
```
```
$ cargo test --doc
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
   Doc-tests rustplay

running 1 test
test src/lib.rs - S::new (line 9) ... FAILED

failures:

---- src/lib.rs - S::new (line 9) stdout ----
	error: unexpected token: `}`
 --> src/lib.rs:4:1
  |
4 | }
  | ^

error: aborting due to previous error

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:541:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: rustc_errors::Handler::abort_if_errors
   6: rustc_errors::Handler::emit
   7: rustc_errors::Handler::span_err
   8: syntax::parse::parser::Parser::parse_dot_or_call_expr_with
   9: syntax::parse::parser::Parser::parse_stmt_without_recovery
  10: syntax::parse::parser::Parser::parse_full_stmt
  11: syntax::parse::parser::Parser::parse_block_tail
  12: syntax::parse::parser::Parser::parse_inner_attrs_and_block
  13: syntax::parse::parser::Parser::parse_item_fn
  14: syntax::parse::parser::Parser::parse_item_
  15: syntax::parse::parser::Parser::parse_item
  16: syntax::parse::parser::Parser::parse_mod_items
  17: syntax::parse::parser::Parser::parse_crate_mod
  18: syntax::parse::parse_crate_from_source_str
  19: rustc_driver::driver::phase_1_parse_input::{{closure}}
  20: rustc::util::common::time
  21: rustc_driver::driver::phase_1_parse_input
  22: rustc_driver::driver::compile_input
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
  25: rustdoc::test::run_test
thread 'rustc' panicked at 'couldn't compile the test', librustdoc/test.rs:286:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: rustdoc::test::run_test


failures:
    src/lib.rs - S::new (line 9)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

**Comment by Mark-Simulacrum** [comment]
This is expected behavior; the line with `Foo.` gets interpreted as a code block and parsed as an incomplete dot access to a field of the ident `Foo`. As such, I'm closing.
