### ISSUE TITLE
'rustc' panicked at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by thbar** [rust-lang/rust#47517]
I'm on a Mac OS X High Sierra, using Docker (Docker 17.12.0-ce-mac47 (21805) and the [rust Docker image 1.23.0](https://hub.docker.com/_/rust/).

I'm using the Dockerfile:

```Dockerfile
FROM rust:1.23.0

WORKDIR /git
RUN cargo --version
```

Then:

```
mkdir share
ln -s ~/git/thbar-rbspy/ share
docker build . -t logeek:rbspy
docker run -it --rm -v $(pwd)/share/thbar-rbspy:/share/thbar-rbspy:rw -w /share/thbar-rbspy logeek:rbspy bash
```

Once bash is started, inside that container, I'm running `cargo build` for the [rbspy](https://github.com/rbspy/rbspy) project, as I'm trying to contribute to that project (which currently doesn't build on OS X).

I get the following error:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.23.0 (766bd11c8 2018-01-01) running on x86_64-unknown-linux-gnu
thread 'rustc' panicked at 'internal error: entered unreachable code', /checkout/src/librustc/ty/sty.rs:82:61
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `clap`.
```

If I run with `RUST_BACKTRACE=1` again, I get:

```
thread 'rustc' panicked at 'internal error: entered unreachable code', /checkout/src/librustc/ty/sty.rs:82:61
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: serialize::serialize::Decoder::read_enum
   7: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::SpecializedDecoder<&'tcx rustc::ty::TyS<'tcx>> for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::specialized_decode
   8: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::SpecializedDecoder<&'tcx rustc::ty::TyS<'tcx>> for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::specialized_decode
   9: serialize::serialize::Decoder::read_struct
  10: <alloc::boxed::Box<T> as serialize::serialize::Decodable>::decode
  11: serialize::serialize::Decoder::read_enum
  12: serialize::serialize::Decoder::read_enum
  13: serialize::serialize::Decoder::read_option
  14: serialize::serialize::Decoder::read_struct
  15: serialize::serialize::Decoder::read_seq
  16: <rustc_data_structures::indexed_vec::IndexVec<I, T> as serialize::serialize::Decodable>::decode
  17: serialize::serialize::Decoder::read_struct
  18: rustc_metadata::decoder::<impl rustc_metadata::cstore::CrateMetadata>::maybe_get_optimized_mir
  19: _ZN14rustc_metadata11cstore_impl14provide_extern13optimized_mir17he4071e3e521493baE.llvm.488EF64A
  20: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::compute_result
  21: _ZN5rustc9dep_graph5graph8DepGraph14with_task_impl17he87b54904788f06eE.llvm.F50A461C
  22: rustc_errors::Handler::track_diagnostics
  23: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  24: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::force
  25: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::try_get
  26: rustc::ty::maps::TyCtxtAt::optimized_mir
  27: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  28: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  29: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  30: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  31: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  32: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  33: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  34: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  35: _ZN17rustc_trans_utils9collector17collect_items_rec17h0ec041e24bd9cc59E.llvm.52FA7423
  36: rustc_trans_utils::collector::collect_crate_translation_items
  37: rustc::util::common::time
  38: _ZN11rustc_trans4base39collect_and_partition_translation_items17ha603c65adf8fd661E.llvm.F98EC436
  39: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::compute_result
  40: _ZN5rustc9dep_graph5graph8DepGraph14with_task_impl17h6b25a71960f39f3bE.llvm.F50A461C
  41: rustc_errors::Handler::track_diagnostics
  42: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  43: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::force
  44: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get
  45: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
  46: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items
  47: rustc_trans::base::trans_crate
  48: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  49: rustc::util::common::time
  50: rustc_driver::driver::phase_4_translate_to_llvm
  51: _ZN12rustc_driver6driver13compile_input28_$u7b$$u7b$closure$u7d$$u7d$17h6f1af84bbbc06559E.llvm.1ABF736A
  52: <std::thread::local::LocalKey<T>>::with
  53: <std::thread::local::LocalKey<T>>::with
  54: rustc::ty::context::TyCtxt::create_and_enter
  55: rustc_driver::driver::compile_input
  56: rustc_driver::run_compiler

error: Could not compile `clap`.
```

Interestingly, the build works on another machine.

**Comment by Centril** [comment]
@thbar Can you check if this reproduces today?

**Comment by Elinvynia** [comment]
I was unable to reproduce this using `Docker version 19.03.8, build afacb8b7f0` on ` 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
(otherwise the same rust image, repo, etc)

**Comment by Nilstrieb** [comment]
This cannot be reproduced and there's nothing easy to extract a test from, so I'm closing it as unactionable. Feel free to open a new issue if you encounter the problem again.
