### ISSUE TITLE
Panic on rustc proc macro compilation, nightly linux

### ISSUE THREAD

**Issue by sfleischman105** [rust-lang/rust#47527]
I've seemingly been having some issues compiling on linux machines, at least from version `1.25.0-nightly (da569fa9d 2018-01-16)` and onwards.

Specifically, one of my crate dependency is `failure`, and therefore `failure_derive` as well. The versions of those have previously been compiling successfully, but recently that compilation of `failure_derive` has been failing. It seems it might have something to do with it being a `proc-macro` crate?

I should note that this is an error I've only been encountering on linux machines so far, specifically with travis-ci. Everything works normally on windows. 

Here is a full build log from [Travis.CI](https://travis-ci.org/sfleischman105/Pleco/builds/329366995) that may be of use.

## Backtrace

```
Compiling failure_derive v0.1.1
     Running `rustc --crate-name failure_derive /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.1/src/lib.rs --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=d8a0852fc2bf7096 -C extra-filename=-d8a0852fc2bf7096 --out-dir /home/travis/build/sfleischman105/Pleco/target/debug/deps -L dependency=/home/travis/build/sfleischman105/Pleco/target/debug/deps --extern syn=/home/travis/build/sfleischman105/Pleco/target/debug/deps/libsyn-ad5fb783d9b863eb.rlib --extern synstructure=/home/travis/build/sfleischman105/Pleco/target/debug/deps/libsynstructure-36475990079c3250.rlib --extern quote=/home/travis/build/sfleischman105/Pleco/target/debug/deps/libquote-bb8c90d97ed7d4da.rlib --cap-lints allow -Ctarget-cpu=native -Zthinlto=on -Zmir-opt-level=3 -Zmutable-noalias`
...
thread 'rustc' panicked at 'assertion failed: bpos.to_usize() >= mbc.pos.to_usize() + mbc.bytes', libsyntax/codemap.rs:644:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
   6: syntax::codemap::CodeMap::bytepos_to_file_charpos
   7: syntax::codemap::CodeMap::lookup_char_pos
   8: rustc_trans::mir::FunctionCx::debug_loc
   9: rustc_trans::mir::trans_mir
  10: rustc_trans::base::trans_instance
  11: rustc_trans::trans_item::MonoItemExt::define
  12: rustc_trans::base::compile_codegen_unit
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::compute_result
  14: rustc::dep_graph::graph::DepGraph::with_task_impl
  15: rustc_errors::Handler::track_diagnostics
  16: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force
  18: rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get
  19: rustc::ty::maps::TyCtxtAt::compile_codegen_unit
  20: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit
  21: rustc_trans::base::trans_crate
  22: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  23: rustc::util::common::time
  24: rustc_driver::driver::phase_4_translate_to_llvm
  25: rustc_driver::driver::compile_input::{{closure}}
  26: <std::thread::local::LocalKey<T>>::with
  27: <std::thread::local::LocalKey<T>>::with
  28: rustc::ty::context::TyCtxt::create_and_enter
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler
error: Could not compile `failure_derive`.
Caused by:
  process didn't exit successfully: `rustc --crate-name failure_derive /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.1/src/lib.rs --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 --cfg feature="default" --cfg feature="std" -C metadata=d8a0852fc2bf7096 -C extra-filename=-d8a0852fc2bf7096 --out-dir /home/travis/build/sfleischman105/Pleco/target/debug/deps -L dependency=/home/travis/build/sfleischman105/Pleco/target/debug/deps --extern syn=/home/travis/build/sfleischman105/Pleco/target/debug/deps/libsyn-ad5fb783d9b863eb.rlib --extern synstructure=/home/travis/build/sfleischman105/Pleco/target/debug/deps/libsynstructure-36475990079c3250.rlib --extern quote=/home/travis/build/sfleischman105/Pleco/target/debug/deps/libquote-bb8c90d97ed7d4da.rlib --cap-lints allow -Ctarget-cpu=native -Zthinlto=on -Zmir-opt-level=3 -Zmutable-noalias` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by sfleischman105** [comment]
Alright, this issue has been solved by removing the following `RUSTFLAGS` from my build:

`-Ctarget-cpu=native -Zthinlto=on -Zmir-opt-level=3 -Zmutable-noalias`

While the -Z flags are experimental flags, I think this might be useful to look into this further to determine the conflict with procedural macros.

I'll post comment again when I determine which combination of flags causes the procedural macro to fail compilation.

**Comment by sfleischman105** [comment]
Determined that with a `RUSTFLAGS` of `-Zmir-opt-level=3` seems to be causing this.

**Comment by Centril** [comment]
@sfleischman105 Can you reproduce this today?

**Comment by Elinvynia** [comment]
I am unable to reproduce this:
`failure_derive` pinned to v0.1.1
RUSTFLAGS set to `-Ctarget-cpu=native -Zthinlto=on -Zmir-opt-level=3 -Zmutable-noalias`
rustc --version --verbose:
```
rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
binary: rustc
commit-hash: 7ebd87a7a1e0e21767422e115c9455ef6e6d4bee
commit-date: 2020-05-08
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

**Comment by bjorn3** [comment]
There have been changes in the relevant code and given that this only reproduce with `-Zmir-opt-level=3` it may have been a broken MIR opt (maybe inlining?). This has probably been fixed at some point. If you ever see it again please reopen or create a new issue.
