### ISSUE TITLE
[NLL] yield-in-box.rs test ICEs

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#47586]
```
$ RUST_BACKTRACE=full rustc +stage1 src/test/run-pass/generator/yield-in-box.rs -Znll -Zborrowck=mir -Ztwo-phase-borrows
error: internal compiler error: librustc_mir/borrow_check/nll/universal_regions.rs:805: cannot convert `ReScope(Node(ItemLocalId(37)))` to a region vid

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-dev running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:509:9
stack backtrace:
   0:     0x7f2cf0aff0fb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h89e4e024185eb251
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f2cf0b13861 - std::sys_common::backtrace::print::h2c98df9d22a6e204
                               at libstd/sys_common/backtrace.rs:68
                               at libstd/sys_common/backtrace.rs:57
   2:     0x7f2cf0af4651 - std::panicking::default_hook::{{closure}}::hc4353cdd7897b77b
                               at libstd/panicking.rs:380
   3:     0x7f2cf0af4271 - std::panicking::default_hook::h9bbd1477c233f26c
                               at libstd/panicking.rs:390
   4:     0x7f2cf0af4946 - std::panicking::rust_panic_with_hook::hdfded1d66d2e81cf
                               at libstd/panicking.rs:576
   5:     0x7f2ceac67b0a - std::panicking::begin_panic::hc1e06300d698b4bf
                               at /home/santiago/src/oss/rust1/src/libstd/panicking.rs:537
   6:     0x7f2ceac4e0fc - rustc_errors::Handler::bug::he87305f1ede57b19
                               at librustc_errors/lib.rs:509
   7:     0x7f2cec89e7ec - <std::thread::local::LocalKey<T>>::with::h5470058d3b926080
                               at librustc/session/mod.rs:1137
                               at librustc/ty/context.rs:1600
                               at librustc/ty/context.rs:1589
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:377
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:288
   8:     0x7f2cec403d79 - rustc::ty::context::tls::with_opt::h2796bc91cf351e3e
                               at librustc/ty/context.rs:1585
                               at librustc/ty/context.rs:1600
   9:     0x7f2cec397892 - rustc::session::opt_span_bug_fmt::hf3a2233d30c89c49
                               at librustc/session/mod.rs:1133
  10:     0x7f2cec37ff29 - rustc::session::bug_fmt::h607a5b7f07dd949a
                               at librustc/session/mod.rs:1117
  11:     0x7f2cee6386c6 - rustc_mir::borrow_check::nll::universal_regions::UniversalRegionIndices::to_region_vid::he03012a5077f472e
                               at librustc_mir/borrow_check/nll/universal_regions.rs:805
  12:     0x7f2cee621578 - rustc_mir::borrow_check::nll::subtype_constraint_generation::generate::h6bf13380917ccf40
                               at librustc_mir/borrow_check/nll/subtype_constraint_generation.rs:0
                               at librustc_mir/borrow_check/nll/subtype_constraint_generation.rs:33
  13:     0x7f2cee60fcdc - rustc_mir::borrow_check::nll::compute_regions::h8a28351ecd692877
                               at librustc_mir/borrow_check/nll/mod.rs:97
  14:     0x7f2cee607d5d - rustc_mir::borrow_check::do_mir_borrowck::h5527e035bdb6f90b
                               at librustc_mir/borrow_check/mod.rs:196
  15:     0x7f2cee7e4bcc - <std::thread::local::LocalKey<T>>::with::h09e3d281217138a6
                               at librustc_mir/borrow_check/mod.rs:81
                               at /home/santiago/src/oss/rust1/src/librustc/infer/mod.rs:439
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1573
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:377
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:288
  16:     0x7f2cee5d8f0a - rustc::ty::context::tls::enter::hf92705338ff04233
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1570
  17:     0x7f2cee5db66c - rustc::ty::context::GlobalCtxt::enter_local::h834852a1d0d3a09a
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1381
  18:     0x7f2cee5c43f2 - rustc::infer::InferCtxtBuilder::enter::h876297f802958ad2
                               at /home/santiago/src/oss/rust1/src/librustc/infer/mod.rs:439
  19:     0x7f2cee6074ad - rustc_mir::borrow_check::mir_borrowck::ha3ddcadee42ed870
                               at librustc_mir/borrow_check/mod.rs:79
  20:     0x7f2cec567b90 - rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::compute_result::hf45a226b5c044941
                               at librustc/ty/maps/plumbing.rs:383
  21:     0x7f2cec1b2108 - rustc::dep_graph::graph::DepGraph::with_task_impl::h977b285d649164fa
                               at librustc/dep_graph/graph.rs:289
  22:     0x7f2cec184a0f - rustc::dep_graph::graph::DepGraph::with_task::h606c300c86adccb4
                               at librustc/dep_graph/graph.rs:199
  23:     0x7f2cec6b1057 - rustc_errors::Handler::track_diagnostics::h5c4733a59e59914c
                               at librustc/ty/maps/plumbing.rs:492
                               at /home/santiago/src/oss/rust1/src/librustc_errors/lib.rs:572
  24:     0x7f2cec434ace - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check::h510dda0193aa77a2
                               at librustc/ty/maps/plumbing.rs:485
                               at librustc/ty/maps/plumbing.rs:121
  25:     0x7f2cec567c92 - rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::force::h5b5a43ddd69d4127
                               at librustc/ty/maps/plumbing.rs:484
  26:     0x7f2cec568921 - rustc::ty::maps::<impl rustc::ty::maps::queries::mir_borrowck<'tcx>>::try_get::hb7409412e9075295
                               at librustc/ty/maps/plumbing.rs:301
                               at librustc/ty/maps/plumbing.rs:526
  27:     0x7f2cec4bc015 - rustc::ty::maps::TyCtxtAt::mir_borrowck::hb6ba692bbeabd5e9
                               at librustc/ty/maps/plumbing.rs:565
  28:     0x7f2cec3ff718 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck::h44d6f533e09947b5
                               at librustc/ty/maps/plumbing.rs:558
  29:     0x7f2cf0e87155 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::{{closure}}::h5b4653d0f1e2de53
                               at librustc_driver/driver.rs:1073
  30:     0x7f2cf0f4e226 - <std::thread::local::LocalKey<T>>::with::h5c65293ff59250fe
                               at librustc_driver/driver.rs:1071
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1573
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:377
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:288
  31:     0x7f2cf0e6b71e - rustc::ty::context::tls::enter::h88b739b20317ffe4
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1570
  32:     0x7f2cf0f4ccec - <std::thread::local::LocalKey<T>>::with::h43c40e0d4e18765b
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1557
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:377
                               at /home/santiago/src/oss/rust1/src/libstd/thread/local.rs:288
  33:     0x7f2cf0e6b1d7 - rustc::ty::context::tls::enter_global::h0e8e2e22f658e325
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1554
  34:     0x7f2cf0e6fbf5 - rustc::ty::context::TyCtxt::create_and_enter::h1843d08844146f02
                               at /home/santiago/src/oss/rust1/src/librustc/ty/context.rs:1197
  35:     0x7f2cf0eb4e27 - rustc_driver::driver::phase_3_run_analysis_passes::hdca06791b92b8d71
                               at librustc_driver/driver.rs:1017
  36:     0x7f2cf0ea6c57 - rustc_driver::driver::compile_input::h80b1c15489d523ea
                               at librustc_driver/driver.rs:220
  37:     0x7f2cf0e98646 - rustc_driver::run_compiler::h6941f27d9cf14ec2
                               at librustc_driver/lib.rs:248
  38:     0x7f2cf0f4597a - std::sys_common::backtrace::__rust_begin_short_backtrace::h2f40e38beb20488f
                               at librustc_driver/lib.rs:1305
                               at librustc_driver/lib.rs:132
                               at librustc_driver/lib.rs:1212
                               at /home/santiago/src/oss/rust1/src/libstd/sys_common/backtrace.rs:133
  39:     0x7f2cf0b28e76 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  40:     0x7f2cf0f28437 - std::panicking::try::hf10cda8586478214
                               at /home/santiago/src/oss/rust1/src/libstd/panicking.rs:458
  41:     0x7f2cf0f2827d - std::panic::catch_unwind::h95b8c396b2db40d5
                               at /home/santiago/src/oss/rust1/src/libstd/panic.rs:358
  42:     0x7f2cf0f5a9f3 - <F as alloc::boxed::FnBox<A>>::call_box::h6aa43ee35a088e4c
                               at /home/santiago/src/oss/rust1/src/libstd/thread/mod.rs:405
                               at /home/santiago/src/oss/rust1/src/liballoc/boxed.rs:817
  43:     0x7f2cf0b1b792 - std::sys_common::thread::start_thread::he35a8e58b745ed7d
                               at libstd/sys_common/thread.rs:24
  44:     0x7f2cf0b10408 - std::sys::unix::thread::Thread::new::thread_start::h669389680624d627
                               at libstd/sys/unix/thread.rs:90
  45:     0x7f2cea36b08b - start_thread
  46:     0x7f2cf07bee1e - __GI___clone
  47:                0x0 - <unknown>
```

**Comment by spastorino** [comment]
This is fixed, I believe by https://github.com/rust-lang/rust/pull/47353
