### ISSUE TITLE
ICE with broken pipe

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang/rust#47985]
Repro:

```
$ rustc | derp
```

Output

```
$ RUST_BACKTRACE=full rustc | derp
bash: derp: command not found
thread 'rustc' panicked at 'failed printing to stdout: Broken pipe (os error 32)', libstd/io/stdio.rs:690:9
stack backtrace:
   0:     0x7ff53d4a858b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6777dc4c3f6de9b9
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7ff53d473ed0 - std::sys_common::backtrace::print::h2b9a4998e933da56
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7ff53d47a1a0 - std::panicking::default_hook::{{closure}}::h320975af855e84a7
                               at libstd/panicking.rs:380
   3:     0x7ff53d479ef7 - std::panicking::default_hook::h76239d7d4466a452
                               at libstd/panicking.rs:396
   4:     0x7ff53d47a5eb - std::panicking::rust_panic_with_hook::h20162ef1dca3f0d1
                               at libstd/panicking.rs:576
   5:     0x7ff53d47a4ae - std::panicking::begin_panic::hd430b2cb23357e97
                               at libstd/panicking.rs:537
   6:     0x7ff53d47a3aa - std::panicking::begin_panic_fmt::hd7ac0cdb7639cf6a
                               at libstd/panicking.rs:521
   7:     0x7ff53d4961b7 - std::io::stdio::_print::haa3141784e7182dd
                               at libstd/io/stdio.rs:690
                               at libstd/io/stdio.rs:699
   8:     0x7ff53d8e1e37 - rustc_driver::usage::hab83e3f4d905e813
   9:     0x7ff53d8e4053 - rustc_driver::handle_options::h9e6ef44ce2c426a6
  10:     0x7ff53d8dad9a - rustc_driver::run_compiler::heed8e02952dd2b80
  11:     0x7ff53d7df5c8 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc7097ed49752c97f
  12:     0x7ff53d4bd0be - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  13:     0x7ff53d843b97 - <F as alloc::boxed::FnBox<A>>::call_box::hdbe333bbf46b4062
  14:     0x7ff53d4ac487 - std::sys_common::thread::start_thread::h43bdcc5538fc8b7c
                               at /checkout/src/liballoc/boxed.rs:798
                               at libstd/sys_common/thread.rs:24
  15:     0x7ff53d47aef8 - std::sys::unix::thread::Thread::new::thread_start::hf61986fa14cc6f4f
                               at libstd/sys/unix/thread.rs:90
  16:     0x7ff53795808b - start_thread
  17:     0x7ff53d165e7e - __GI___clone
  18:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (616b66dca 2018-02-02) running on x86_64-unknown-linux-gnu
```

**Comment by zackmdavis** [comment]
(duplicate of #34376)

**Comment by AdamNiederer** [comment]
Thanks; closing.
