### ISSUE TITLE
LLVM assertion in run-make/issue-26092

### ISSUE THREAD

**Issue by pftbest** [rust-lang/rust#48128]
Just did a `make check` on the [latest master](https://github.com/rust-lang/rust/commit/39abcc04139a0fd24422f422271849dc91e39a88) with llvm assertions enabled:

```
failures:

---- [run-make] run-make/issue-26092 stdout ----
	
error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
DYLD_LIBRARY_PATH="/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/test/run-make/issue-26092.stage2-x86_64-apple-darwin:/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage2/lib:" '/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage2/bin/rustc' --out-dir /Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/test/run-make/issue-26092.stage2-x86_64-apple-darwin -L /Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/test/run-make/issue-26092.stage2-x86_64-apple-darwin  -o "" blank.rs 2>&1 | "/Users/vadzim/Documents/rust-lang/src/etc/cat-and-grep.sh" -i 'No such file or directory'
[[[ begin stdout ]]]
warning: ignoring --out-dir flag due to -o flag

Assertion failed: (FD >= 0 && "File not yet open!"), function preferred_buffer_size, file /Users/vadzim/Documents/rust-lang/src/llvm/lib/Support/raw_ostream.cpp, line 666.

[[[ end stdout ]]]
Error: cannot match: No such file or directory

------------------------------------------
stderr:
------------------------------------------
make[1]: *** [all] Error 1

------------------------------------------

thread '[run-make] run-make/issue-26092' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2883:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-make] run-make/issue-26092

test result: FAILED. 174 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:476:22


command did not execute successfully: "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage0-tools-bin/compiletest" "--compile-lib-path" "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage2/lib" "--run-lib-path" "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib" "--rustc-path" "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage2/bin/rustc" "--rustdoc-path" "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/stage2/bin/rustdoc" "--src-base" "/Users/vadzim/Documents/rust-lang/src/test/run-make" "--build-base" "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/test/run-make" "--stage-id" "stage2-x86_64-apple-darwin" "--mode" "run-make" "--target" "x86_64-apple-darwin" "--host" "x86_64-apple-darwin" "--llvm-filecheck" "/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/llvm/build/bin/FileCheck" "--nodejs" "/usr/local/bin/node" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/native/rust-test-helpers" "--docck-python" "/usr/local/opt/python/bin/python2.7" "--lldb-python" "/usr/bin/python" "--lldb-version" "lldb-900.0.64" "--lldb-python-dir" "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python" "--llvm-version" "6.0.0\n" "--cc" "cc" "--cxx" "c++" "--cflags" "-ffunction-sections -fdata-sections -fPIC -m64 -stdlib=libc++" "--llvm-components" "aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils all all-targets analysis arm armasmparser armasmprinter armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter binaryformat bitreader bitwriter codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfomsf debuginfopdb demangle dlltooldriver engine executionengine fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader libdriver lineeditor linker lto mc mcdisassembler mcjit mcparser mips mipsasmparser mipsasmprinter mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmprinter msp430codegen msp430desc msp430info native nativecodegen nvptx nvptxasmprinter nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit passes powerpc powerpcasmparser powerpcasmprinter powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata runtimedyld scalaropts selectiondag sparc sparcasmparser sparcasmprinter sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzasmprinter systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target transformutils vectorize webassembly webassemblyasmprinter webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86asmprinter x86codegen x86desc x86disassembler x86info x86utils" "--llvm-cxxflags" "-I/Users/vadzim/Documents/rust-lang/build/x86_64-apple-darwin/llvm/include -ffunction-sections -fdata-sections -fPIC -m64 -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -O3   -fno-exceptions -fno-rtti -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" "--ar" "ar" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" ""
expected success, got: exit code: 101


failed to run: /Users/vadzim/Documents/rust-lang/build/bootstrap/debug/bootstrap test
Build completed unsuccessfully in 0:22:46
```

**Comment by pietroalbini** [comment]
cc @alexcrichton

**Comment by kennytm** [comment]
cc #43402

**Comment by jyn514** [comment]
Looks like https://github.com/rust-lang/rust/pull/45170 was fixed in 2017. This test passes reliably for me locally even with LLVM assertions enabled, so I'm going to close this.
