### ISSUE TITLE
Build failure on FreeBSD-CURRENT/aarch64

### ISSUE THREAD

**Issue by gczuczy** [rust-lang/rust#48459]
Hello,

I'm trying to build Rust on FreeBSD -CURRENT / aarch64, but I'm getting a build failure (after manually fixing the -march=native stuff, that's not available with clang):

```
   Compiling syntax_ext v0.0.0 (file:///usr/ports/lang/rust/work/rustc-1.24.0-src/src/libsyntax_ext)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0 (766bd11c8 2018-01-01) running on aarch64-unknown-freebsd

thread 'rustc' panicked at 'other was less than the current instant', src/libstd/sys/unix/time.rs:284:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `rustc`.

Caused by:
  process didn't exit successfully: `/usr/ports/lang/rust/work/rustc-1.24.0-src/build/bootstrap/debug/rustc --crate-name rustc src/librustc/lib.rs --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=2 -C metadata=0e4023cd73b81f18 -C extra-filename=-0e4023cd73b81f18 --out-dir /usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps --target aarch64-unknown-freebsd -L dependency=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps -L dependency=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/release/deps --extern serialize=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libserialize-5c4a770b35d7301c.so --extern serialize=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libserialize-5c4a770b35d7301c.rlib --extern rustc_back=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/librustc_back-e57d34b62838ce95.so --extern rustc_const_math=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/librustc_const_math-31abc7bbf08cf770.so --extern jobserver=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libjobserver-80deaee93ecabf45.rlib --extern bitflags=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libbitflags-59566638c9ff1415.rlib --extern arena=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libarena-000b1a891acd24bf.so --extern log=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/liblog-e8c8481f3bf3f955.rlib --extern rustc_data_structures=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/librustc_data_structures-892d539ff539f47b.so --extern rustc_apfloat=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/librustc_apfloat-ea6c3828ef99f19b.rlib --extern syntax=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libsyntax-49a9760049fea63e.so --extern fmt_macros=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libfmt_macros-4a76d5230d38a606.so --extern graphviz=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libgraphviz-2c9a85200bc4b126.so --extern backtrace=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libbacktrace-55e17f198c3c34f9.rlib --extern rustc_errors=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/librustc_errors-3246924e41422b8b.so --extern byteorder=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libbyteorder-55efc62f6738f0b2.rlib --extern syntax_pos=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libsyntax_pos-9f18feb0a98f6609.so --extern flate2=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/deps/libflate2-5dbea30b4a6382a0.rlib -L native=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/build/backtrace-sys-7dc3515dc554b97d/out/.libs -L native=/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0-rustc/aarch64-unknown-freebsd/release/build/miniz-sys-566067a6ed2393e6/out` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/usr/ports/lang/rust/work/rustc-1.24.0-src/build/aarch64-unknown-freebsd/stage0/bin/cargo" "build" "--target" "aarch64-unknown-freebsd" "--release" "--frozen" "--features" " jemalloc llvm" "--manifest-path" "/usr/ports/lang/rust/work/rustc-1.24.0-src/src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:886:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Traceback (most recent call last):
  File "/usr/ports/lang/rust/work/rustc-1.24.0-src/x.py", line 20, in <module>
    bootstrap.main()
  File "/usr/ports/lang/rust/work/rustc-1.24.0-src/src/bootstrap/bootstrap.py", line 758, in main
    bootstrap()
  File "/usr/ports/lang/rust/work/rustc-1.24.0-src/src/bootstrap/bootstrap.py", line 749, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/usr/ports/lang/rust/work/rustc-1.24.0-src/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /usr/ports/lang/rust/work/rustc-1.24.0-src/build/bootstrap/debug/bootstrap build --verbose --config ./config.toml --jobs 4
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/lang/rust
*** Error code 1

Stop.
make: stopped in /usr/ports/lang/rust
```

make.conf:
```
DEFAULT_VERSIONS+= python=3.6
OPTIONS_UNSET= TEST NLS DOCS EXAMPLES
```
options set for the port:
```
# This file is auto-generated by 'make config'.
# Options for rust-1.24.0
_OPTIONS_READ=rust-1.24.0
_FILE_COMPLETE_OPTIONS_LIST=DOCS GDB LLNEXTGEN SOURCES
OPTIONS_FILE_UNSET+=DOCS
OPTIONS_FILE_UNSET+=GDB
OPTIONS_FILE_UNSET+=LLNEXTGEN
OPTIONS_FILE_UNSET+=SOURCES
```
And the exact OS version:
```
FreeBSD build-pine64.bealak.harmless.hu 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r328533M: Mon Jan 29 15:43:25 CET 2018     toor@marvin.harmless.hu:/tank/rpi3/crochet/work.pine64vanilla/obj/tank/rpi3/src/arm64.aarch64/sys/GENERIC-NODEBUG  arm64
```

FYI it's after the clang 6 import:
```
# cc -v
FreeBSD clang version 6.0.0 (branches/release_60 323338) (based on LLVM 6.0.0)
Target: aarch64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```

And the FreeBSD PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225643

Could you please take a look into it and try to fix it?

Thanks,
Gergely

**Comment by Aaronepower** [comment]
@gczuczy Hello sorry there's been no response, is current Rust still failing build?

**Comment by myfreeweb** [comment]
This issue seems obsolete, the current problem on aarch64 is: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228892

**Comment by Aaronepower** [comment]
@myfreeweb Is there a issue for that on the Rust GitHub? Does there need to be?

**Comment by myfreeweb** [comment]
I'm not sure. @dumbbell was testing a patch, so there might be a pull request eventually.

**Comment by sanxiyn** [comment]
The linked FreeBSD bug is closed as fixed. Can this be closed?

**Comment by myfreeweb** [comment]
@sanxiyn yes, everything works fine these days :)

Would be nice to have official builds in rustup btw

**Comment by sanxiyn** [comment]
Thanks for confirmation! Yes it would be nice to have in rustup.
