### ISSUE TITLE
Building the crate "alga" fails on nightly 2018-02-26

### ISSUE THREAD

**Issue by dominikwerder** [rust-lang/rust#48580]
The `rustc` output kindly asked me to provide this bug report:

Using `rustc 1.26.0-nightly (bedbad611 2018-02-26) running on x86_64-unknown-linux-gnu` I tried to use the crate `alga` which in turn is required by `nalgebra`.

As soon as I put `alga` (or `nalgebra`) into `Cargo.toml` and cargo attempts to compile `alga`, I get:

```
$ cargo run
   Compiling alga v0.5.2
thread 'rustc' panicked at 'assertion failed: `(left != right)`
  left: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([<Self as linear::vector::EuclideanSpace>::Coordinates, <Self as linear::vector::EuclideanSpace>::Real]), item_def_id: DefId(2/0:893 ~ core[4840]::ops[0]::arith[0]::Mul[0]::Output[0]) }, <Self as linear::vector::EuclideanSpace>::Coordinates)))`,
 right: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([<Self as linear::vector::EuclideanSpace>::Coordinates, <Self as linear::vector::EuclideanSpace>::Real]), item_def_id: DefId(2/0:893 ~ core[4840]::ops[0]::arith[0]::Mul[0]::Output[0]) }, <Self as linear::vector::EuclideanSpace>::Coordinates)))`', librustc/traits/project.rs:146:17
stack backtrace:
   0:     0x7f040a5a1ff3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h92c858273beca9db
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f040a599534 - std::sys_common::backtrace::_print::h6cb1e7663c70c510
                               at libstd/sys_common/backtrace.rs:71
   2:     0x7f040a59ec7d - std::panicking::default_hook::{{closure}}::h46fa0787be3918b6
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:206
   3:     0x7f040a59e979 - std::panicking::default_hook::h7dddf112a45a90f8
                               at libstd/panicking.rs:222
   4:     0x7f0407028a5d - core::ops::function::Fn::call::h3cb97c4162eec9f6
   5:     0x7f040a59f119 - std::panicking::rust_panic_with_hook::h42848144b6747469
                               at libstd/panicking.rs:401
   6:     0x7f040a59ef02 - std::panicking::begin_panic_fmt::h14c37c5e3685a2bb
                               at libstd/panicking.rs:347
   7:     0x7f040733aa22 - rustc::traits::project::ProjectionTyCandidateSet::push_candidate::h2672d39becc9aba3
   8:     0x7f040733f012 - rustc::traits::project::opt_normalize_projection_type::h1fb7b886d286337f
   9:     0x7f040733df83 - rustc::traits::project::normalize_projection_type::hfdd96356f7e979d2
  10:     0x7f040733d86c - <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty::h27356651973a3854
  11:     0x7f04073c4e7a - rustc::ty::subst::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::Slice<rustc::ty::subst::Kind<'tcx>>>::super_fold_with::hcb4c12f430c98df5
  12:     0x7f04073ebdee - rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for rustc::ty::Predicate<'tcx>>::super_fold_with::h81d9e56dd0820402
  13:     0x7f040736a4dc - rustc::traits::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for rustc::traits::Obligation<'tcx, O>>::super_fold_with::h4c9a7f60e6f745db
  14:     0x7f040733c432 - rustc::traits::project::normalize_with_depth::h3d391e0ed1f21835
  15:     0x7f04073c7e82 - rustc::ty::wf::WfPredicates::normalize::{{closure}}::hc5c71bc5bb70f84c
  16:     0x7f040718c979 - <core::iter::FlattenCompat<I, U> as core::iter::iterator::Iterator>::next::h7b6fc964cbd4c975
  17:     0x7f0407015bc7 - <alloc::vec::Vec<T>>::extend_desugared::h4a9cc89317e1b0b9
  18:     0x7f0407182782 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h09c60980fbd8ae5d
  19:     0x7f04073c7c74 - rustc::ty::wf::predicate_obligations::h74ece49687a4a4e1
  20:     0x7f040924d593 - rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_where_clauses::h343cb02e7c27c865
  21:     0x7f04092458b3 - rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_item_well_formed::hd49e4e9035d32eeb
  22:     0x7f040924e788 - <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h2fd643ee2fb8da76
  23:     0x7f04092b6a68 - rustc_typeck::check_crate::{{closure}}::h65bc6b2cde8fc8d8
  24:     0x7f04092b277c - rustc_typeck::check_crate::h6a4b56b529504aab
  25:     0x7f040a8e7e99 - rustc::ty::context::TyCtxt::create_and_enter::hc45b3a73dd46ae96
  26:     0x7f040a94c73e - rustc_driver::driver::compile_input::h60b5346f3903c44c
  27:     0x7f040a968e8a - rustc_driver::run_compiler::h606ede5b4fb41a6e
  28:     0x7f040a894840 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha956e4fd16418a0d
  29:     0x7f040a5b7bde - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  30:     0x7f040a8cdce6 - <F as alloc::boxed::FnBox<A>>::call_box::ha7d35e4049273418
  31:     0x7f040a5aef9b - std::sys::unix::thread::Thread::new::thread_start::h15b68dbc19e967f4
                               at /checkout/src/liballoc/boxed.rs:793
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  32:     0x7f04054aa08b - start_thread
  33:     0x7f040a271e7e - __GI___clone
  34:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (bedbad611 2018-02-26) running on x86_64-unknown-linux-gnu

error: Could not compile `alga`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It works fine on `stable 1.24`.

**Comment by dominikwerder** [comment]
This is maybe related to issue #48551.

**Comment by ishitatsuyuki** [comment]
Exact duplicate, closing.
