### ISSUE TITLE
ICE: index out of bounds with rls and span generated by proc-macro attribute

### ISSUE THREAD

**Issue by kdy1** [rust-lang/rust#48582]
`#[parser]` is a simple hack to make macro partially unhygienic.
It prepends self to macro arguments.
Given
```rust
#[parser]
impl Parser {
  pub fn parse_XX(&mut self) -> PResult<XX> {
    cur!();
    bump!();
    eat!('a');
  }
}

```
prints
```rust
impl Parser {
  pub fn parse_XX(&mut self) -> PResult<XX> {
    cur!(self);
    bump!(self);
    eat!(self, 'a');
  }
}
```

`cargo check` or `build` does not have any problem with it but rls is broken.

## `rls --cli`
Note: You have to run this twice to get stack trace. See https://github.com/rust-lang-nursery/rls/issues/738 

```
$ RUST_BACKTRACE=full RUST_LOG=debug CARGO_INCREMENTAL=1 rls --cli
# Omitted useless log messages

 DEBUG 2018-02-27T12:29:27Z: cargo::ops::cargo_rustc::fingerprint: write fingerprint: /mnt/c/Users/kdy/Documents/projects/swc/ecmascript/parser/target/rls/debug/.fingerprint/swc_macros-d557c2bb15f46f82/lib-swc_macros-d557c2bb15f46f82
 INFO 2018-02-27T12:29:27Z: cargo::ops::cargo_rustc::job_queue: end: swc_macros v0.1.0 (file:///mnt/c/Users/kdy/Documents/projects/swc/macros) => Target(lib)/Profile(check) => Host
 INFO 2018-02-27T12:29:27Z: cargo::ops::cargo_rustc::job_queue: start: swc_ecma_ast v0.1.0 (file:///mnt/c/Users/kdy/Documents/projects/swc/ecmascript/ast) => Target(lib)/Profile(check) => Host
thread 'rustc' panicked at 'index out of bounds: the len is 71658 but the index is 71776', /checkout/src/liballoc/vec.rs:1536:10
stack backtrace:
   0:     0x7f9dc374aff3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h92c858273beca9db
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f9dc3742534 - std::sys_common::backtrace::_print::h6cb1e7663c70c510
                               at libstd/sys_common/backtrace.rs:71
   2:     0x7f9dc3747c7d - std::panicking::default_hook::{{closure}}::h46fa0787be3918b6
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:206
   3:     0x7f9dc3747979 - std::panicking::default_hook::h7dddf112a45a90f8
                               at libstd/panicking.rs:222
   4:     0x7f9dc4685a5d - core::ops::function::Fn::call::h3cb97c4162eec9f6
   5:     0x7f9dc3748119 - std::panicking::rust_panic_with_hook::h42848144b6747469
                               at libstd/panicking.rs:401
   6:     0x7f9dc3747f02 - std::panicking::begin_panic_fmt::h14c37c5e3685a2bb
                               at libstd/panicking.rs:347
   7:     0x7f9dc3747e32 - rust_begin_unwind
                               at libstd/panicking.rs:323
   8:     0x7f9dc37acf60 - core::panicking::panic_fmt::h073d1a33c55ca52f
                               at libcore/panicking.rs:71
   9:     0x7f9dc37acf03 - core::panicking::panic_bounds_check::he6e885ab6d60a660
                               at libcore/panicking.rs:58
  10:     0x7f9dc482fb60 - rustc::dep_graph::graph::DepGraph::node_color::hd92c76e4d9e87791
  11:     0x7f9dc49f5fc3 - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_mark_green_and_read::h5ae1aac390c36966
  12:     0x7f9dc4bd59f8 - rustc::ty::maps::<impl rustc::ty::maps::queries::exported_symbols<'tcx>>::try_get::he412a88851c0b7de
  13:     0x7f9dc4c04ec3 - rustc::ty::maps::TyCtxtAt::exported_symbols::h7e7735f415e36778
  14:     0x7f9dc4bfdf8e - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::exported_symbols::h95796b0982d4ffc5
  15:     0x7f9db1aa0850 - rustc_trans::back::write::start_async_translation::h830084af12a98a14
  16:     0x7f9db1abdd85 - rustc_trans::base::trans_crate::h738847f13ac11d6b
  17:     0x7f9db1b1ac07 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::he1547238cf95100e
  18:     0x7f9dc534e782 - rustc_driver::driver::phase_4_translate_to_llvm::h4e2ec031fd084a01
  19:     0x7f9dc534770e - rustc_driver::driver::compile_input::{{closure}}::he9f831ecdaf7dbd7
  20:     0x7f9dc52e1c24 - rustc::ty::context::TyCtxt::create_and_enter::hc45b3a73dd46ae96
  21:     0x7f9dc534573e - rustc_driver::driver::compile_input::h60b5346f3903c44c
  22:     0x7f9dc5361e8a - rustc_driver::run_compiler::h606ede5b4fb41a6e
  23:     0x7f9dc5abca3e - std::sys_common::backtrace::__rust_begin_short_backtrace::hd309709ee10a0577
  24:     0x7f9dc5acc7a6 - std::panicking::try::do_call::hd26d704d41061070
  25:     0x7f9dc3760bde - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  26:     0x7f9dc5b37492 - <F as alloc::boxed::FnBox<A>>::call_box::h606d90f3d1f8ac56
  27:     0x7f9dc3757f9b - std::sys::unix::thread::Thread::new::thread_start::h15b68dbc19e967f4
                               at /checkout/src/liballoc/boxed.rs:793
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  28:     0x7f9dc30a76b9 - start_thread
  29:     0x7f9dc2bb741c - clone
  30:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (bedbad611 2018-02-26) running on x86_64-unknown-linux-gnu

```

**Comment by kdy1** [comment]
# Step to reproduce

1. `git clone git@github.com:swc-project/swc.git && cd swc && git checkout 67daa4c4e41a407c08026d9efbd27d927660f7f5`


2. run `RUST_BACKTRACE=full RUST_LOG=debug CARGO_INCREMENTAL=1 rls --cli` twice

**Comment by Centril** [comment]
@kdy1 Can you still reproduce this?

**Comment by kdy1** [comment]
@Centril  Sorry for delay. I can't..
