### ISSUE TITLE
bootstrap panicked

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#48667]
```
$ git rev-parse HEAD
9cb18a92ad87852c4c5d6726b8fbe8c38deda4ba

$ ./x.py build -j 8 -i
# while running and after compiling libstd edit a file of libstd
# while compiling stage 1 librustc press ctrl-C
```

<details>
<summary>$ ./x.py test -j 8 -i --keep-stage 1 --stage 1 src/test/run-make</summary>

```
$ ./x.py test -j 8 -i --keep-stage 1 --stage 1 src/test/run-make
    Finished dev [unoptimized] target(s) in 0.11 secs
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Assembling stage1 compiler (x86_64-apple-darwin)
Building stage1 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.1 secs
Copying stage1 std from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage1 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage1 test from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage1 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling rustc v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc)
   Compiling rustc_incremental v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_incremental)
   Compiling rustc_metadata v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_metadata)
   Compiling rustc_allocator v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_allocator)
   Compiling rustc_const_eval v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_const_eval)
   Compiling rustc_resolve v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_resolve)
   Compiling rustc_typeck v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_typeck)
   Compiling rustc_mir v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_mir)
   Compiling rustc_passes v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_passes)
   Compiling rustc_lint v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_lint)
   Compiling rustc_plugin v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_plugin)
   Compiling rustc_save_analysis v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_save_analysis)
   Compiling rustc_privacy v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_privacy)
   Compiling rustc_trans_utils v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_trans_utils)
   Compiling rustc_borrowck v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_borrowck)
   Compiling rustc_driver v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_driver)
   Compiling rustc-main v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/rustc)
    Finished release [optimized] target(s) in 449.56 secs
Copying stage1 rustc from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building test helpers
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-o" "/Users/bjorn/Documents/rust-fork/build/x86_64-apple-darwin/native/rust-test-helpers/rust_test_helpers.o" "-c" "/Users/bjorn/Documents/rust-fork/src/test/auxiliary/rust_test_helpers.c"
exit code: 0
running: "ar" "crs" "/Users/bjorn/Documents/rust-fork/build/x86_64-apple-darwin/native/rust-test-helpers/librust_test_helpers.a" "/Users/bjorn/Documents/rust-fork/build/x86_64-apple-darwin/native/rust-test-helpers/rust_test_helpers.o"
exit code: 0
Check compiletest suite=run-make mode=run-make (x86_64-apple-darwin -> x86_64-apple-darwin)
Building stage0 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling std v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libstd)
    Finished release [optimized] target(s) in 13.16 secs
Building stage0 test artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling getopts v0.2.15
   Compiling term v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libterm)
   Compiling test v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libtest)
    Finished release [optimized] target(s) in 9.1 secs
Building stage0 tool compiletest (x86_64-apple-darwin)
   Compiling utf8-ranges v1.0.0
   Compiling rustc-serialize v0.3.24
   Compiling diff v0.1.11
   Compiling getopts v0.2.15
   Compiling libc v0.2.36
   Compiling lazy_static v1.0.0
   Compiling cfg-if v0.1.2
   Compiling regex-syntax v0.4.2
   Compiling void v1.0.2
   Compiling log v0.4.1
   Compiling unreachable v1.0.0
   Compiling thread_local v0.3.5
   Compiling memchr v2.0.1
   Compiling filetime v0.1.15
   Compiling log v0.3.9
   Compiling aho-corasick v0.6.4
   Compiling env_logger v0.4.3
   Compiling regex v0.2.5
   Compiling compiletest v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/tools/compiletest)
    Finished release [optimized] target(s) in 24.55 secs
Building stage0 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
   Compiling cfg-if v0.1.2
   Compiling fmt_macros v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libfmt_macros)
   Compiling syntax v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libsyntax)
   Compiling lazy_static v0.2.11
   Compiling rustc_metadata v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_metadata)
   Compiling rustc v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc)
   Compiling rustc_driver v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_driver)
   Compiling libc v0.2.36
   Compiling rustc_incremental v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_incremental)
   Compiling rustc_back v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_back)
   Compiling stable_deref_trait v1.0.0
   Compiling cc v1.0.4
   Compiling arena v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libarena)
   Compiling lazy_static v1.0.0
   Compiling rustc-serialize v0.3.24
   Compiling unicode-width v0.1.4
   Compiling graphviz v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libgraphviz)
   Compiling bitflags v1.0.1
   Compiling serialize v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libserialize)
   Compiling rustc_platform_intrinsics v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_platform_intrinsics)
   Compiling rustc-demangle v0.1.5
   Compiling ar v0.3.1
   Compiling byteorder v1.2.1
   Compiling smallvec v0.6.0
   Compiling log v0.4.1
   Compiling log_settings v0.1.1
   Compiling owning_ref v0.3.3
   Compiling rand v0.3.20
   Compiling jobserver v0.1.9
   Compiling rustc_cratesio_shim v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_cratesio_shim)
   Compiling backtrace v0.3.5
   Compiling log v0.3.9
   Compiling rustc_apfloat v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_apfloat)
   Compiling miniz-sys v0.1.10
   Compiling env_logger v0.4.3
   Compiling ena v0.9.1
   Compiling parking_lot_core v0.2.9
   Compiling rls-span v0.4.0
   Compiling rls-data v0.15.0
   Compiling parking_lot v0.5.3
   Compiling flate2 v1.0.1
   Compiling rustc_data_structures v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_data_structures)
   Compiling syntax_pos v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/libsyntax_pos)
   Compiling rustc_errors v0.0.0 (file:///Users/bjorn/Documents/rust-fork/src/librustc_errors)
^C
Build completed unsuccessfully in 0:09:44
```

</details>
<br>

```
$ ./x.py test -j 8 -i --keep-stage 1 --stage 1 src/test/run-make
    Finished dev [unoptimized] target(s) in 0.8 secs
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Copying stage0 test from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
thread 'main' panicked at 'File::open(stamp) failed with No such file or directory (os error 2)', bootstrap/util.rs:71:8
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::begin_panic
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::try::do_call
             at libstd/panicking.rs:521
   7: <str as std_unicode::u_str::UnicodeStr>::split_whitespace
             at bootstrap/util.rs:71
   8: bootstrap::compile::add_to_sysroot
             at bootstrap/compile.rs:937
   9: bootstrap::compile::rustc_cargo_env
             at bootstrap/compile.rs:572
  10: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:829
  11: bootstrap::compile::compiler_file
             at bootstrap/compile.rs:882
  12: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:829
  13: bootstrap::builder::Builder::compiler
             at bootstrap/builder.rs:423
  14: <bootstrap::test::RunFailFullDepsPretty as core::clone::Clone>::clone
             at bootstrap/test.rs:591
  15: bootstrap::builder::StepDescription::maybe_run
             at bootstrap/builder.rs:185
  16: bootstrap::builder::StepDescription::run
             at bootstrap/builder.rs:215
  17: bootstrap::builder::Builder::run
             at bootstrap/builder.rs:410
  18: bootstrap::Crate::local_path
             at bootstrap/lib.rs:392
  19: bootstrap::main
             at bootstrap/bin/main.rs:29
  20: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  21: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  22: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  23: rust_panic
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  24: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  25: bootstrap::main
failed to run: /Users/bjorn/Documents/rust-fork/build/bootstrap/debug/bootstrap test -j 8 -i --keep-stage 1 --stage 1 src/test/run-make
Build completed unsuccessfully in 0:00:02
```

**Comment by Mark-Simulacrum** [comment]
Hm, I suspect this is possibly fixed now so I'm going to close but if you see this again we can probably modify rustbuild to just assume dirty on stamp files not existing (but we really shouldn't care too much anymore as we read them much less).
