### ISSUE TITLE
lexical-scope-with-macro.rs failed on Xcode 9.3

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#48807]
From https://travis-ci.org/rust-lang/rust/jobs/350058114

<details>

```
[02:04:32] failures:
[02:04:32] 
[02:04:32] ---- [debuginfo-lldb] debuginfo/lexical-scope-with-macro.rs stdout ----
[02:04:32] 	NOTE: compiletest thinks it is using LLDB version 902
[02:04:32] 
[02:04:32] error: line not found in debugger output: [...]$2 = 890242
[02:04:32] status: exit code: 0
[02:04:32] command: "/usr/bin/python" "/Users/travis/build/rust-lang/rust/src/etc/lldb_batchmode.py" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/lexical-scope-with-macro.stage2-x86_64-apple-darwin" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/lexical-scope-with-macro.debugger.script"
[02:04:32] stdout:
[02:04:32] ------------------------------------------
[02:04:32] LLDB batch-mode script
[02:04:32] ----------------------
[02:04:32] Debugger commands script is '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/lexical-scope-with-macro.debugger.script'.
[02:04:32] Target executable is '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/lexical-scope-with-macro.stage2-x86_64-apple-darwin'.
[02:04:32] Current working directory is '/Users/travis/build/rust-lang/rust'
[02:04:32] Creating a target for '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/lexical-scope-with-macro.stage2-x86_64-apple-darwin'
[02:04:32] settings set auto-confirm true
[02:04:32] 
[02:04:32] version
[02:04:32] lldb-902.0.73.1 Swift-4.1 
[02:04:32] command script import /Users/travis/build/rust-lang/rust/./src/etc/lldb_rust_formatters.py
[02:04:32] type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
[02:04:32] type category enable Rust
[02:04:32] 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 127
[02:04:32] Breakpoint 1: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 136
[02:04:32] Breakpoint 2: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 141
[02:04:32] Breakpoint 3: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 157
[02:04:32] Breakpoint 4: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 24 at lexical-scope-with-macro.rs:157, address = 0x0000000100000be8 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 162
[02:04:32] Breakpoint 5: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 51 at lexical-scope-with-macro.rs:162, address = 0x0000000100000c03 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 167
[02:04:32] Breakpoint 6: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 99 at lexical-scope-with-macro.rs:167, address = 0x0000000100000c33 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 172
[02:04:32] Breakpoint 7: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 122 at lexical-scope-with-macro.rs:172, address = 0x0000000100000c4a 
[02:04:32] run
[02:04:32] Hit breakpoint 4.1: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 24 at lexical-scope-with-macro.rs:157, address = 0x0000000100000be8, resolved, hit count = 1 
[02:04:32] Process 57845 stopped * thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 4.1 frame #0: 0x0000000100000be8 lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 at lexical-scope-with-macro.rs:157 154 let a = trivial!(10); 155 let b = no_new_scope!(33); 156 -> 157 zzz(); // #break 158 sentinel(); 159 160 new_scope!(); Target 0: (lexical-scope-with-macro.stage2-x86_64-apple-darwin) stopped. Process 57845 launched: '/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo/lexical-scope-with-macro.stage2-x86_64-apple-darwin' (x86_64) 
[02:04:32] print a
[02:04:32] (int) $0 = 10 
[02:04:32] print b
[02:04:32] (int) $1 = 34 
[02:04:32] continue
[02:04:32] Hit breakpoint 5.1: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 51 at lexical-scope-with-macro.rs:162, address = 0x0000000100000c03, resolved, hit count = 1 
[02:04:32] print a
[02:04:32] (int) $2 = 10 
[02:04:32] print b
[02:04:32] (int) $3 = 34 
[02:04:32] continue
[02:04:32] Hit breakpoint 6.1: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 99 at lexical-scope-with-macro.rs:167, address = 0x0000000100000c33, resolved, hit count = 1 
[02:04:32] print a
[02:04:32] (int) $4 = 10 
[02:04:32] print b
[02:04:32] (int) $5 = 34 
[02:04:32] continue
[02:04:32] Hit breakpoint 7.1: where = lexical-scope-with-macro.stage2-x86_64-apple-darwin`lexical_scope_with_macro::main::h22e96ead882753b7 + 122 at lexical-scope-with-macro.rs:172, address = 0x0000000100000c4a, resolved, hit count = 1 
[02:04:32] print a
[02:04:32] (int) $6 = 10 
[02:04:32] print b
[02:04:32] (int) $7 = 34 
[02:04:32] continue
[02:04:32] print a
[02:04:32] error: use of undeclared identifier 'a'
[02:04:32] 
[02:04:32] print b
[02:04:32] error: use of undeclared identifier 'b'
[02:04:32] 
[02:04:32] continue
[02:04:32] error: Process must be launched.
[02:04:32] 
[02:04:32] print a
[02:04:32] error: use of undeclared identifier 'a'
[02:04:32] 
[02:04:32] print b
[02:04:32] error: use of undeclared identifier 'b'
[02:04:32] 
[02:04:32] continue
[02:04:32] error: Process must be launched.
[02:04:32] 
[02:04:32] print a
[02:04:32] error: use of undeclared identifier 'a'
[02:04:32] 
[02:04:32] print b
[02:04:32] error: use of undeclared identifier 'b'
[02:04:32] 
[02:04:32] print c
[02:04:32] error: use of undeclared identifier 'c'
[02:04:32] 
[02:04:32] continue
[02:04:32] error: Process must be launched.
[02:04:32] 
[02:04:32] quit
[02:04:32] None
[02:04:32] 
[02:04:32] ------------------------------------------
[02:04:32] stderr:
[02:04:32] ------------------------------------------
[02:04:32] 
[02:04:32] ------------------------------------------
[02:04:32] 
[02:04:32] thread '[debuginfo-lldb] debuginfo/lexical-scope-with-macro.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2893:9
[02:04:32] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[02:04:32] 
[02:04:32] 
[02:04:32] failures:
[02:04:32]     [debuginfo-lldb] debuginfo/lexical-scope-with-macro.rs
[02:04:32] 
[02:04:32] test result: [31mFAILED(B[m. 90 passed; 1 failed; 18 ignored; 0 measured; 0 filtered out
[02:04:32] 
[02:04:32] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:476:22
[02:04:32] 
[02:04:32] 
[02:04:32] command did not execute successfully: "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage0-tools-bin/compiletest" "--compile-lib-path" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib" "--run-lib-path" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib" "--rustc-path" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/bin/rustc" "--src-base" "/Users/travis/build/rust-lang/rust/src/test/debuginfo" "--build-base" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/test/debuginfo" "--stage-id" "stage2-x86_64-apple-darwin" "--mode" "debuginfo-lldb" "--target" "x86_64-apple-darwin" "--host" "x86_64-apple-darwin" "--llvm-filecheck" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/llvm/build/bin/FileCheck" "--nodejs" "/Users/travis/.nvm/versions/node/v6.12.3/bin/node" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "--docck-python" "/usr/local/opt/python/bin/python2.7" "--lldb-python" "/usr/bin/python" "--lldb-version" "lldb-902.0.73.1" "--lldb-python-dir" "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python" "--quiet" "--llvm-version" "6.0.0\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[02:04:32] expected success, got: exit code: 101
[02:04:32] 
[02:04:32] 
[02:04:32] failed to run: /Users/travis/build/rust-lang/rust/build/bootstrap/debug/bootstrap test
[02:04:32] Build completed unsuccessfully in 0:22:54
[02:04:32] make: *** [check] Error 1
[02:04:32] make: INTERNAL: Exiting with 2 jobserver tokens available; should be 3!
```

</details>

cc @michaelwoerister, @tromey

**Comment by tromey** [comment]
```
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 127
[02:04:32] Breakpoint 1: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 136
[02:04:32] Breakpoint 2: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
[02:04:32] breakpoint set --file 'lexical-scope-with-macro.rs' --line 141
[02:04:32] Breakpoint 3: no locations (pending). WARNING: Unable to resolve breakpoint to any actual locations. 
```
This is probably what is causing the tests to fail.  I haven't looked any more deeply.

**Comment by wesleywiser** [comment]
Visited during wg-debugging triage. It looks like the `//ignore macos` annotation on this test has turned into a more generic `// ignore lldb` annotation. There is some work happening to re-evaluate these kinds of disabled tests in (https://github.com/rust-lang/rust/pull/95696) so this might get changed there. If not, the first step here is to retest on a recent macOS & XCode release.

**Comment by madsmtm** [comment]
This seems to have been fixed in https://github.com/rust-lang/rust/pull/129218, specifically e93e61032962b80747ed869a21e887090ac63c90.
