### ISSUE TITLE
Stage 1 test failure on master branch

### ISSUE THREAD

**Issue by Phlosioneer** [rust-lang/rust#49352]
I'm getting a test failure for `ui-fulldeps/proc-macro/load-panic.rs` on my local machine:

```
    Finished release [optimized] target(s) in 756.80 secs
Copying stage1 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Check compiletest suite=ui-fulldeps mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 12 tests
test [ui] ui-fulldeps/custom-derive/issue-36935.rs ... ignored
test [ui] ui-fulldeps/lint-group-plugin.rs ... ignored
test [ui] ui-fulldeps/lint-plugin-cmdline-allow.rs ... ignored
test [ui] ui-fulldeps/lint-plugin-cmdline-load.rs ... ignored
test [ui] ui-fulldeps/lint-plugin-forbid-attrs.rs ... ignored
test [ui] ui-fulldeps/lint-plugin.rs ... ignored
test [ui] ui-fulldeps/proc-macro/parent-source-spans.rs ... ignored
test [ui] ui-fulldeps/proc-macro/three-equals.rs ... ignored
test [ui] ui-fulldeps/proc-macro/signature.rs ... ok
test [ui] ui-fulldeps/deprecated-derive.rs ... ok
test [ui] ui-fulldeps/proc-macro/load-panic.rs ... FAILED
test [ui] ui-fulldeps/resolve-error.rs ... ok

failures:

---- [ui] ui-fulldeps/proc-macro/load-panic.rs stdout ----
        diff of stderr:

+       thread '<unnamed>' panicked at 'nope!', $DIR/auxiliary/derive-panic.rs:22:5
+       note: Run with `RUST_BACKTRACE=1` for a backtrace.
1       error: proc-macro derive panicked
2         --> $DIR/load-panic.rs:17:10
3          |


The actual stderr differed from the expected stderr.
Actual stderr saved to /home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/proc-macro/load-panic.stderr
To update references, run this command from build directory:
/home/unix_sub/rust/rust/src/test/ui-fulldeps/update-references.sh '/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps' 'proc-macro/load-panic.rs'

error: 1 errors occurred comparing output.
status: exit code: 101
command: "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/unix_sub/rust/rust/src/test/ui-fulldeps/proc-macro/load-panic.rs" "-L" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps" "--target=x86_64-unknown-linux-gnu" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/proc-macro/load-panic.stage1-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zmiri" "-Zunstable-options" "-Lnative=/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--error-format" "human" "-L" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/proc-macro/load-panic.stage1-x86_64-unknown-linux-gnu.aux" "-A" "unused"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread '<unnamed>' panicked at 'nope!', /home/unix_sub/rust/rust/src/test/ui-fulldeps/proc-macro/auxiliary/derive-panic.rs:22:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: proc-macro derive panicked
  --> /home/unix_sub/rust/rust/src/test/ui-fulldeps/proc-macro/load-panic.rs:17:10
   |
LL | #[derive(A)]
   |          ^
   |
   = help: message: nope!

error: aborting due to previous error


------------------------------------------

thread '[ui] ui-fulldeps/proc-macro/load-panic.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2901:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [ui] ui-fulldeps/proc-macro/load-panic.rs

test result: FAILED. 3 passed; 1 failed; 8 ignored; 0 measured; 0 filtered out

thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:478:22


command did not execute successfully: "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/stage1/lib" "--run-lib-path" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--src-base" "/home/unix_sub/rust/rust/src/test/ui-fulldeps" "--build-base" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/test/ui-fulldeps" "--stage-id" "stage1-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Zmiri -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zmiri -Zunstable-options  -Lnative=/home/unix_sub/rust/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python" "--lldb-python" "/usr/bin/python" "--gdb" "/usr/bin/gdb" "--llvm-version" "6.0.0\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" ""
expected success, got: exit code: 101


failed to run: /home/unix_sub/rust/rust/build/bootstrap/debug/bootstrap test --stage 1
Build completed unsuccessfully in 1:07:09
unix_sub@DevWindows ~/r/rust> git branch
  10234-wall-help-message
  32463-impl-integer-for-wrapping
  42453-debug-hygene
  43601-document-opaque-size
  49123-sort-where-conditions
  add-decode-utf-8-size-hint
  add-trivial-size-hints
* master
  more-size-hints
  rebase-test-32463
unix_sub@DevWindows ~/r/rust> git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
unix_sub@DevWindows ~/r/rust> git log | head
commit 77e2bcb613c58ed2aeb86fdb07f470440f94f205
Merge: f5631d9 4eff4d9
Author: bors <bors@rust-lang.org>
Date:   Sun Mar 25 00:02:48 2018 +0000

    Auto merge of #49141 - gnzlbg:simd_select, r=alexcrichton

    adds simd_select intrinsic

    The select SIMD intrinsic is used to select elements from two SIMD vectors using a mask:
unix_sub@DevWindows ~/r/rust>
```

I'm running on the linux subsystem for windows, which is:
```
unix_sub@DevWindows ~/r/rust> uname -a
Linux DevWindows 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```
I have never had any issues compiling before. (`DevWindows` is my computer's name)

I'm running the tests using the command:
```
unix_sub@DevWindows ~/r/rust> ./x.py test --stage 1
```

**Comment by rkruppe** [comment]
This is a proc macro test so it's expected that it doesn't work on stage1 right now. #49219 should fix that.

**Comment by oli-obk** [comment]
It should still be marked //ignore-stage1

**Comment by Phlosioneer** [comment]
I'm guessing `run-pass-fulldeps/compiler-calls.rs` and `run-pass-fulldeps/proc-macro/span-api-tests.rs` should be ignored too. I've added them to a PR.

I'm now getting an error for `double_bind()` in `src/libstd/net/tcp.rs:1199`. It's panicking because a double-bind is allowed?

There's no associated error message, it's just a raw `panic!()`.

Again, same test command; just a vanilla stage-1 test.

**Comment by Phlosioneer** [comment]
`double_bind()` is also failing with stage 2 (`./x.py test`). I'm going to make a new issue for it.

**Comment by jonas-schievink** [comment]
This is fixed.
