### ISSUE TITLE
ICE on ARM - missing MIR for `DefId(7/0:7 ~ cortex_m_rt[cc3c]::lang_items[0]::start[0])

### ISSUE THREAD

**Issue by sbourdeauducq** [rust-lang/rust#49375]
When compiling https://github.com/m-labs/ionpak at fe088d7bba189d4b0edf584b69c8b3974a1dce5a
new versions of the compiler crash:
```
error: internal compiler error: librustc_metadata/cstore_impl.rs:135: get_optimized_mir: missing MIR for `DefId(7/0:7 ~ cortex_m_rt[cc3c]::lang_items[0]::start[0])`

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:543:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:403
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: <std::thread::local::LocalKey<T>>::try_with
  11: <std::thread::local::LocalKey<T>>::with
  12: rustc::ty::context::tls::with
  13: rustc::ty::context::tls::with_opt
  14: rustc::session::opt_span_bug_fmt
  15: rustc::session::bug_fmt
  16: rustc_metadata::cstore_impl::provide_extern::optimized_mir
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::compute_result
  18: rustc::dep_graph::graph::DepGraph::with_task_impl
  19: rustc_errors::Handler::track_diagnostics
  20: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  21: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::force
  22: rustc::ty::maps::<impl rustc::ty::maps::queries::optimized_mir<'tcx>>::try_get
  23: rustc::ty::maps::TyCtxtAt::optimized_mir
  24: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_crate_mono_items
  27: rustc::util::common::time
  28: rustc_trans::base::collect_and_partition_translation_items
  29: rustc::dep_graph::graph::DepGraph::with_task_impl
  30: rustc_errors::Handler::track_diagnostics
  31: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  32: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::force
  33: rustc::ty::maps::<impl rustc::ty::maps::queries::collect_and_partition_translation_items<'tcx>>::try_get
  34: rustc::ty::maps::TyCtxtAt::collect_and_partition_translation_items
  35: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::collect_and_partition_translation_items
  36: rustc_trans::base::trans_crate
  37: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  38: rustc::util::common::time
  39: rustc_driver::driver::phase_4_translate_to_llvm
  40: rustc_driver::driver::compile_input::{{closure}}
  41: <std::thread::local::LocalKey<T>>::with
  42: <std::thread::local::LocalKey<T>>::with
  43: rustc::ty::context::TyCtxt::create_and_enter
  44: rustc_driver::driver::compile_input
  45: rustc_driver::run_compiler_impl
  46: syntax::with_globals
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (482a913fb 2018-03-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z linker-flavor=ld -C opt-level=3 -C lto -C debuginfo=2 -C link-arg=-Tlink.x -C linker=arm-none-eabi-ld --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `ionpak-firmware`.
```

**Comment by sbourdeauducq** [comment]
This was not a problem with rustc 1.22.0-nightly (ddd123ed9 2017-09-09).
