### ISSUE TITLE
rustc 1.25.0-nightly panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by anykey111** [rust-lang/rust#49449]
I have changed type alias MyHash from std::collections::HashSet to fnv::FnvHashSet.
After switching to stable channel 1.24.1 compiler give me error that method MyHash::new() not available, proper usage is MyHash::default().

fnv crate version "1.0.6"

## Meta

rustc 1.25.0-nightly (3ec5a99aa 2018-02-14) running on x86_64-unknown-linux-gnu

Backtrace:

```
thread 'rustc' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: rustc::ty::maps::on_disk_cache::OnDiskCache::load_diagnostics
  11: rustc::dep_graph::graph::DepGraph::try_mark_green
  12: rustc::dep_graph::graph::DepGraph::try_mark_green
  13: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_mark_green_and_read
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::adt_def<'tcx>>::try_get_with
  15: rustc::ty::maps::TyCtxtAt::adt_def
  16: rustc::ty::codec::decode_adt_def
  17: serialize::serialize::Decoder::read_enum_variant
  18: rustc::ty::codec::decode_ty
  19: rustc::ty::codec::decode_ty
  20: serialize::serialize::Decoder::read_enum_variant
  21: <<core::result::Result<V, E> as core::iter::traits::FromIterator<core::result::Result<A, E>>>::from_iter::Adapter<Iter, E> as core::iter::iterator::Iterator>::next
  22: <core::result::Result<V, E> as core::iter::traits::FromIterator<core::result::Result<A, E>>>::from_iter
  23: <core::result::Result<T, E> as rustc::ty::context::InternIteratorElement<T, R>>::intern_with
  24: rustc::ty::codec::decode_substs
  25: serialize::serialize::Decoder::read_enum_variant
  26: rustc::ty::codec::decode_ty
  27: rustc::ty::maps::on_disk_cache::OnDiskCache::load_indexed
  28: rustc::ty::maps::<impl rustc::ty::maps::queries::type_of<'tcx>>::try_get_with
  29: rustc::ty::maps::TyCtxtAt::type_of
  30: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::type_of
  31: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  32: rustc_typeck::check_crate::{{closure}}::{{closure}}
  33: rustc_typeck::check_crate
  34: rustc::ty::context::TyCtxt::create_and_enter
  35: rustc_driver::driver::compile_input
  36: rustc_driver::run_compiler

error: internal compiler error: unexpected panic
```

**Comment by anykey111** [comment]
Stable Rust 1.25.0 just arrived and i can't reproduce crash, so i think this issue is not relevant anymore.
