### ISSUE TITLE
Compiler panic due to assertion error

### ISSUE THREAD

**Issue by munyari** [rust-lang/rust#49562]
I'm attempting to build [alacritty-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alacritty-git) from the Arch Linux user repository. I keep seeing a compiler panic while compiling the crate dependencies.

Backtrace:
```
thread 'rustc' panicked at 'assertion failed: `(left != right)`
  left: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([S, S]), item_def_id: DefId(2/0:885 ~ core[4840]::ops[0]::arith[0]::Add[0]::Output[0]) }, S)))`,
 right: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([S, S]), item_def_id: DefId(2/0:885 ~ core[4840]::ops[0]::arith[0]::Add[0]::Output[0]) }, S)))`', librustc/traits/project.rs:146:17
stack backtrace:
   0:     0x7fe73f0e0ff3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h92c858273beca9db
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fe73f0d8534 - std::sys_common::backtrace::_print::h6cb1e7663c70c510
                               at libstd/sys_common/backtrace.rs:71
   2:     0x7fe73f0ddc7d - std::panicking::default_hook::{{closure}}::h46fa0787be3918b6
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:206
   3:     0x7fe73f0dd979 - std::panicking::default_hook::h7dddf112a45a90f8
                               at libstd/panicking.rs:222
   4:     0x7fe73b963a5d - core::ops::function::Fn::call::h3cb97c4162eec9f6
   5:     0x7fe73f0de119 - std::panicking::rust_panic_with_hook::h42848144b6747469
                               at libstd/panicking.rs:401
   6:     0x7fe73f0ddf02 - std::panicking::begin_panic_fmt::h14c37c5e3685a2bb
                               at libstd/panicking.rs:347
   7:     0x7fe73bc75a22 - rustc::traits::project::ProjectionTyCandidateSet::push_candidate::h2672d39becc9aba3
   8:     0x7fe73bc7a012 - rustc::traits::project::opt_normalize_projection_type::h1fb7b886d286337f
   9:     0x7fe73bc75f95 - rustc::traits::project::poly_project_and_unify_type::{{closure}}::h263dd4b025f36e3f
  10:     0x7fe73bc75b26 - rustc::traits::project::poly_project_and_unify_type::h320025eec3e59da3
  11:     0x7fe73bc734fd - <rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation::hac6790f001fc5a92
  12:     0x7fe73bc723ba - rustc::traits::fulfill::FulfillmentContext::select::hf3f1c6e20ecb57a4
  13:     0x7fe73bc71426 - rustc::traits::fulfill::FulfillmentContext::select_all_or_error::h15cec768664df1eb
  14:     0x7fe73db91f3b - rustc_typeck::check::compare_method::compare_predicate_entailment::hb5bcdf792a53358b
  15:     0x7fe73dbaf646 - rustc_typeck::check::check_impl_items_against_trait::ha54ec9f6ebc4daf0
  16:     0x7fe73dba9296 - rustc_typeck::check::check_item_type::ha723eb383ae7db9c
  17:     0x7fe73dbf209b - rustc_typeck::check_crate::{{closure}}::hfdb538aa117f82ae
  18:     0x7fe73dbed78e - rustc_typeck::check_crate::h6a4b56b529504aab
  19:     0x7fe73f426e99 - rustc::ty::context::TyCtxt::create_and_enter::hc45b3a73dd46ae96
  20:     0x7fe73f48b73e - rustc_driver::driver::compile_input::h60b5346f3903c44c
  21:     0x7fe73f4a7e8a - rustc_driver::run_compiler::h606ede5b4fb41a6e
  22:     0x7fe73f3d3840 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha956e4fd16418a0d
  23:     0x7fe73f0f6bde - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  24:     0x7fe73f40cce6 - <F as alloc::boxed::FnBox<A>>::call_box::ha7d35e4049273418
  25:     0x7fe73f0edf9b - std::sys::unix::thread::Thread::new::thread_start::h15b68dbc19e967f4
                               at /checkout/src/liballoc/boxed.rs:793
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  26:     0x7fe739fe908b - start_thread
  27:     0x7fe73edb0e7e - __GI___clone
  28:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (bedbad611 2018-02-26) running on x86_64-unknown-linux-gnu
```

`rustc --version --verbose`:
rustc 1.26.0-nightly (bedbad611 2018-02-26)
binary: rustc
commit-hash: bedbad61195d2eae69b43eca49c6d3e2aee8f208
commit-date: 2018-02-26
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0

System details:
GNU/Linux x86_64, kernel release 4.15.11-1-ARCH

**Comment by munyari** [comment]
Noticed while posting this that I was on a >1 month old nightly. Updating to the latest fixed the issue :smile:
