### ISSUE TITLE
error: internal compiler error: librustc/ty/context.rs:502: node_id_to_type: no type for node `expr 10 (id=678)`

### ISSUE THREAD

**Issue by oherrala** [rust-lang/rust#49644]
I get an internal compiler error when running Clippy:

```
$ cargo +nightly clippy
   Compiling hyper v0.10.13
error: internal compiler error: librustc/ty/context.rs:502: node_id_to_type: no type for node `expr 10 (id=678)`

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:543:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (637ac17c5 2018-04-03) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `hyper`.

To learn more, run the command again with --verbose.
```

This happens in both macOS and Linux.

Backtrace when running on macOS:

```
thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:543:9                                                                                                       [29/489]
stack backtrace:                                                                          
   0:        0x10d4ce4ab - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h8969571b2ed70056
   1:        0x10d4a439b - std::sys_common::backtrace::print::h8b41ea2ab91085de
   2:        0x10d4bee2d - std::panicking::default_hook::{{closure}}::h6b63ffa98c9c5531
   3:        0x10d4beb8a - std::panicking::default_hook::hcc5e535908221461
   4:        0x10bbacaa0 - core::ops::function::Fn::call::he8ed09e64eaa183e                           
   5:        0x10d4bf2e0 - std::panicking::rust_panic_with_hook::he092b47fc1086b55
   6:        0x10d24f04c - std::panicking::begin_panic::h5f0aedd5c961bd8d
   7:        0x10d26204c - rustc_errors::Handler::bug::h3a32f6c77e0e3538             
   8:        0x10bc80035 - rustc::session::opt_span_bug_fmt::{{closure}}::h92fec8f585ac20d7
   9:        0x10bc91b47 - rustc::ty::context::tls::with_opt::{{closure}}::h8f5a2b07cd66a127   
  10:        0x10bc353bb - <std::thread::local::LocalKey<T>>::try_with::heb418b4adc6476f8
  11:        0x10bc314d4 - <std::thread::local::LocalKey<T>>::with::hc93552b4dd314498
  12:        0x10ba7343b - rustc::ty::context::tls::with::h335637f04f377e73
  13:        0x10ba734a3 - rustc::ty::context::tls::with_opt::h04759ebc1bc14b21
  14:        0x10b7ff324 - rustc::session::opt_span_bug_fmt::h165c865fec15b83d
  15:        0x10b7ff271 - rustc::session::bug_fmt::hf24a43e343294c9b
  16:        0x10ba6e68b - rustc::ty::context::TypeckTables::expr_ty::h738e41f1f0ef8b5d
  17:        0x109a58f3f - clippy_lints::consts::ConstEvalLateContext::expr::h9d9bc37c2145935a                   
  18:        0x109a588b5 - clippy_lints::consts::constant_simple::h59069fef9230cfe6
  19:        0x109ada776 - clippy_lints::utils::hir_utils::SpanlessHash::hash_expr::h5d8e7d60810965f5
  20:        0x109adaa6e - clippy_lints::utils::hir_utils::SpanlessHash::hash_expr::h5d8e7d60810965f5
  21:        0x109adac5e - clippy_lints::utils::hir_utils::SpanlessHash::hash_expr::h5d8e7d60810965f5
  22:        0x109aa38f9 - <clippy_lints::copies::CopyAndPaste as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr::h49b79f111093d4c1
  23:        0x10bc53442 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h70424ae12ac1a56b
  24:        0x10bc559ba - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block::hbd6b59113fce854e
  25:        0x10bc5354c - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h70424ae12ac1a56b
  26:        0x10bc52320 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body::h85f574a4f2ab38fd
  27:        0x10bc52109 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::he469639e4df10555
  28:        0x10bc53da5 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn::hfa1a90b028a7ddd1
  29:        0x10bb99838 - rustc::hir::intravisit::walk_impl_item::h4cf866f37ac486c3
  30:        0x10bc573a6 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item::h89972f07a1591f90
  31:        0x10bb9a8f4 - rustc::hir::intravisit::walk_impl_item_ref::he0051d3e14230760
  32:        0x10bb7ccee - rustc::hir::intravisit::walk_item::h13ac93f5ae218f02
  33:        0x10bc528b6 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h77aacc8fd84a78bb
  34:        0x10bc552bc - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::h9224807ee57e100e
  35:        0x10bb7cb31 - rustc::hir::intravisit::walk_item::h13ac93f5ae218f02
  36:        0x10bc528b6 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h77aacc8fd84a78bb
  37:        0x10bc552bc - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::h9224807ee57e100e
  38:        0x10bb7cb31 - rustc::hir::intravisit::walk_item::h13ac93f5ae218f02
  39:        0x10bc528b6 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h77aacc8fd84a78bb
  40:        0x10bc552bc - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::h9224807ee57e100e
  41:        0x10bb7a181 - rustc::hir::intravisit::walk_crate::h717e6e07c5e1fda2
  42:        0x10bc5d060 - rustc::lint::context::check_crate::hac4093efbb7cecc3
  43:        0x109efc449 - <std::thread::local::LocalKey<T>>::with::hc5277bcd57ac8e0e
  44:        0x109efa97c - <std::thread::local::LocalKey<T>>::with::h50a9d3cea19cd3fa
  45:        0x109f5aa69 - rustc::ty::context::TyCtxt::create_and_enter::h0a6bf74357892c1f
  46:        0x109e7f7a9 - rustc_driver::driver::compile_input::hdfc363407ffb5e4b
  47:        0x109f179f5 - rustc_driver::run_compiler_impl::h8b12a548d7f86865
  48:        0x109e7d29b - syntax::with_globals::hbefd81f7a524ee77
  49:        0x109f16880 - rustc_driver::run_compiler::h0a0dcf51384e1aa0
  50:        0x1099473d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65d1a1066b5f9ae3
  51:        0x10994fdcf - std::panicking::try::do_call::h1c51c67aec5663a2
  52:        0x10d4e3b1e - __rust_maybe_catch_panic
  53:        0x10994bd86 - <F as alloc::boxed::FnBox<A>>::call_box::hb18341989fe4ae54
  54:        0x10d4d6d97 - std::sys_common::thread::start_thread::ha419e3549bb7ac8a
  55:        0x10d4a3128 - std::sys::unix::thread::Thread::new::thread_start::h7672b8325f3f7580
  56:     0x7fffa73a593a - _pthread_body
  57:     0x7fffa73a5886 - _pthread_start
error: aborting due to previous error
```

Clippy is latest published in crates.io and compiled with current nightly compiler.

```
$ cargo +nightly clippy --version
0.0.191
```

**Comment by oherrala** [comment]
Here is a minimal crate to reproduce the issue.

Cargo.toml:

```
[package]
name = "rustc-49644"
version = "0.1.0"
authors = ["Ossi Herrala <oherrala@iki.fi>"]

[dependencies]
iron = "0.6.0"
```

src/main.rs:
```
extern crate iron;
use iron::prelude::*;
use iron::status;fn main() {
   Iron::new(|_: &mut Request| {
       Ok(Response::with((status::Ok, "Hello world!")))
   }).http("localhost:3000").unwrap();
}
```

**Comment by oherrala** [comment]
This looks like same issue as #49643.

**Comment by pietroalbini** [comment]
Yeah, it's the same issue. Thanks for reporting this!
