### ISSUE TITLE
Shouldn't ICE when owned_box has wrong type

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#49960]
Starting from this code:

```rust
#![feature(lang_items, box_syntax, owned_box, start)]
#![no_std]

#[start]
pub fn start(_: isize, _: *const *const u8) -> isize { 
    let x = box 1i32;
    0
}

#[lang = "eh_personality"] extern fn eh_personality() {}
#[lang = "eh_unwind_resume"] extern fn eh_unwind_resume() {}
#[lang = "panic_fmt"] fn panic_fmt() -> ! { loop {} }

#[lang = "exchange_malloc"]
unsafe fn exchange_malloc(size: usize, align: usize) -> *mut u8 {
    core::ptr::null_mut()
}
```

Adding various `owned_box` patterns leads to different kinds of ICE:
```rust
#[lang = "owned_box"]
struct Box;
```
yields
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/libcore/slice/mod.rs:865:10
```

```rust
#[lang = "owned_box"]
struct Box<T>(Option<T>);
```

yields
```
error: internal compiler error: librustc_trans/mir/operand.rs:175: Deref of by-Ref operand OperandRef(Ref((%"Box<i32>"*:  %3 = alloca %"Box<i32>", align 4), Align { abi: 2, pref: 3 }) @ TyLayout { ty: Box<i32>, details: LayoutDetails { variants: Single { index: 0 }, fields: Arbitrary { offsets: [Size { raw: 0 }], memory_index: [0] }, abi: Aggregate { sized: true }, align: Align { abi: 2, pref: 3 }, size: Size { raw: 8 } } })

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:542:9
```

```rust
#[lang = "owned_box"]
struct Box<T>(u8, T);
```
yields
```
error: internal compiler error: librustc/ty/layout.rs:2245: TyLayout::field_type(TyLayout { ty: *mut i32, details: LayoutDetails { variants: Single { index: 0 }, fields: Union(0), abi: Scalar(Scalar { value: Pointer, valid_range: 0..=18446744073709551615 }), align: Align { abi: 3, pref: 3 }, size: Size { raw: 8 } } }): not applicable

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:542:9
```

```rust
#[lang = "owned_box"]
struct Box<T, U>(T, U);
```
yields
```
error: internal compiler error: librustc/ty/subst.rs:493: Type parameter `U/#1` (U/1) out of range when substituting (root type=Some(U)) substs=[i32]

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:487:9
```

**Comment by glandium** [comment]
I'll add that `Box<T>(T)` goes through without an error, but the program fails to link, and I didn't try to make it link, but somehow, I doubt the right thing happens with that type.

**Comment by oli-obk** [comment]
This is already tracked in https://github.com/rust-lang/rust/issues/9307

Lang items need to be typechecked
