### ISSUE TITLE
thread 'main' panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by cacamao** [rust-lang/rust#50428]
Hi,

This code works:

```rust
fn main() {
    // Separate characters into groups of 4
    let s = String::from("1234567890");
    let count = s.chars().count();
    let start = count % 4;
    let mut output = String::new();
    for (i, c) in s.chars().enumerate() {
        // Notice this line
        if i > 0 && i % 4 == start {
            output.push('-');
        }
        output.push(c);
    }
    println!("{}", output);
}
```

But if I changed the notice line to:

```rust
        if i > 0 && i % 4 - start == 0 {
            ...
        }
```

It will cause this error:

```shell
   0:     0x559e01f308c3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h5ac0de120f67d91c
   1:     0x559e01f2bbd4 - std::sys_common::backtrace::_print::h369ce9ed074962ab
   2:     0x559e01f2fc30 - std::panicking::default_hook::{{closure}}::hdfc577cf0b1e83a5
   3:     0x559e01f2f932 - std::panicking::default_hook::h666711b150f76408
   4:     0x559e01f2ffdb - std::panicking::rust_panic_with_hook::h2afa2c9e7284bf9a
   5:     0x559e01f2fe36 - std::panicking::begin_panic::h9403d2eb2fd79ee8
   6:     0x559e01f2fd99 - std::panicking::begin_panic_fmt::h70d2cac2ff1d17fb
   7:     0x559e01f2fd22 - rust_begin_unwind
   8:     0x559e01f3a590 - core::panicking::panic_fmt::h1f47c2a140d4c41c
   9:     0x559e01f3a4b6 - core::panicking::panic::h89445031f225423b
  10:     0x559e01f1fe1d - macros::main::hf019eab628633c10
                               at src/main.rs:9
  11:     0x559e01f21da1 - std::rt::lang_start::{{closure}}::h45a21b8fd1cf1210
                               at /builddir/build/BUILD/rustc-1.25.0-src/src/libstd/rt.rs:74
  12:     0x559e01f2fce7 - std::panicking::try::do_call::h0d807804dcdeee4f
  13:     0x559e01f398ae - __rust_maybe_catch_panic
  14:     0x559e01f30433 - std::rt::lang_start_internal::hdd77304604ed43d8
  15:     0x559e01f21d81 - std::rt::lang_start::hfac19a4bc2192fe0
                               at /builddir/build/BUILD/rustc-1.25.0-src/src/libstd/rt.rs:74
  16:     0x559e01f1fe5d - main
  17:     0x7f36649fff29 - __libc_start_main
  18:     0x559e01f1f829 - _start
  19:                0x0 - <unknown>
```

I'm using Rust version:

```shell
rustc 1.25.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.25.0
LLVM version: 5.0
```

**Comment by kennytm** [comment]
This is expected. In debug mode, integer overflow such as `2usize - 3usize` will panic. You may want to use one of `.checked_sub`, `.wrapping_sub` or `.saturating_sub` if you want to explicitly control the overflow behavior.
