### ISSUE TITLE
Miri crashes on fat ptr to thin ptr conversion

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#50495]
At https://github.com/rust-lang/rust/blob/428ea5f6b9e7c6e5ee3294fe9f105e77e89ab407/src/librustc_mir/interpret/eval_context.rs#L671

This is used by is_null() https://github.com/rust-lang/rust/blob/428ea5f6b9e7c6e5ee3294fe9f105e77e89ab407/src/libcore/ptr.rs#L527-L531

Backtrace:

```
error: internal compiler error: librustc_mir/interpret/eval_context.rs:671: expected fat ptr

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:554:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::bug_fmt
  14: <rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::eval_rvalue_into_place
             at /home/bjorn/Documenten/miri/<bug macros>:4
  15: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::statement
             at /checkout/src/librustc_mir/interpret/step.rs:59
  16: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::step
             at /checkout/src/librustc_mir/interpret/step.rs:35
  17: priroda::step::step
             at src/step.rs:82
  18: priroda::step::step_routes::single::{{closure}}
             at src/step.rs:214
  19: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:638
  20: priroda::act
             at src/main.rs:213
  21: <priroda::MiriCompilerCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
             at src/main.rs:101
  22: rustc::ty::context::tls::with_context
  23: rustc_driver::driver::compile_input::{{closure}}
  24: rustc::ty::context::tls::enter_context
  25: <std::thread::local::LocalKey<T>>::with
  26: rustc::ty::context::TyCtxt::create_and_enter
  27: rustc_driver::driver::compile_input
  28: rustc_driver::run_compiler_impl
  29: <scoped_tls::ScopedKey<T>>::set
  30: syntax::with_globals
  31: rustc_driver::run_compiler
  32: priroda::main
             at src/main.rs:249
  33: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  34: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  35: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  36: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  37: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  38: main
  39: __libc_start_main
  40: _start
query stack during panic:
end of query stack
```

cc solson/miri#368

**Comment by oli-obk** [comment]
Minimal repro:

```rust
#![feature(extern_types)]

extern {
    type Opaque;
}

const FOO: *const u8 = &42 as *const _ as *const Opaque as *const u8;

fn main() {
    let foo = FOO;
}
```
