### ISSUE TITLE
rustc, error 101

### ISSUE THREAD

**Issue by hedgar2017** [rust-lang/rust#50628]
The code I worked on when the compiler started to crash:
```
state.database.send(user)
        .from_err()
        .and_then(|res| {
            match res {
                Ok(user) => Ok(view::user::json(&user)),
                Err(_) => Ok(view::Error::InternalError.into()),
                //Err(_) => Ok(actix_web::HttpResponse::InternalServerError().into()),
            }
        })
        .responder()
```

Logs with full backtrace:

  ```
 Compiling l2_loki_server v0.1.1 (file:///home/hedgar/share/src/L2LokiServer)
     Running `rustc --crate-name l2_loki_server src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=893315bf4caeed9c -C extra-filename=-893315bf4caeed9c --out-dir /home/hedgar/share/src/L2LokiServer/target/debug/deps -C incremental=/home/hedgar/share/src/L2LokiServer/target/debug/incremental -L dependency=/home/hedgar/share/src/L2LokiServer/target/debug/deps --extern futures=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libfutures-91246f81fd045a75.rlib --extern serde_derive=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libserde_derive-d252ad1b95e490b0.so --extern actix=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libactix-be666c94d5155c10.rlib --extern failure=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libfailure-b81d669fb4be0425.rlib --extern diesel=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libdiesel-d4b184aa0bb9f13a.rlib --extern serde=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libserde-d7469299e49f1978.rlib --extern env_logger=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libenv_logger-d933f45970fb75ad.rlib --extern serde_json=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libserde_json-020d1231a90ed580.rlib --extern actix_web=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libactix_web-a8bed6e22a252cda.rlib -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/backtrace-sys-593be0f56d76b72e/out/.libs -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/brotli-sys-63eab5591cb8b2f0/out -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/ring-e012e05d037e6ca4/out -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/miniz-sys-3e2c2de0c9951ff4/out -L native=/usr/lib`
warning: Hard linking files in the incremental compilation cache failed. Copying files instead. Consider moving the cache directory to a file system which supports hard linking in session dir `/home/hedgar/share/src/L2LokiServer/target/debug/incremental/l2_loki_server-milgj98ihldx/s-f0wyl220dn-1gbunql-working`

thread 'rustc' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: rustc::ty::maps::on_disk_cache::OnDiskCache::load_diagnostics
  11: rustc::dep_graph::graph::DepGraph::try_mark_green
  12: rustc::dep_graph::graph::DepGraph::try_mark_green
  13: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_mark_green_and_read
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::adt_def<'tcx>>::try_get_with
  15: rustc::ty::maps::TyCtxtAt::adt_def
  16: rustc::ty::codec::decode_adt_def
  17: serialize::serialize::Decoder::read_enum_variant
  18: rustc::ty::codec::decode_ty
  19: serialize::serialize::Decoder::read_enum_variant
  20: <<core::result::Result<V, E> as core::iter::traits::FromIterator<core::result::Result<A, E>>>::from_iter::Adapter<Iter, E> as core::iter::iterator::Iterator>::next
  21: <core::result::Result<V, E> as core::iter::traits::FromIterator<core::result::Result<A, E>>>::from_iter
  22: <core::result::Result<T, E> as rustc::ty::context::InternIteratorElement<T, R>>::intern_with
  23: rustc::ty::codec::decode_substs
  24: serialize::serialize::Decoder::read_enum_variant
  25: rustc::ty::codec::decode_ty
  26: rustc::ty::maps::on_disk_cache::OnDiskCache::load_indexed
  27: rustc::ty::maps::<impl rustc::ty::maps::queries::type_of<'tcx>>::try_get_with
  28: rustc::ty::maps::TyCtxtAt::type_of
  29: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::type_of
  30: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  31: rustc_typeck::check_crate::{{closure}}::{{closure}}
  32: rustc_typeck::check_crate
  33: rustc::ty::context::TyCtxt::create_and_enter
  34: rustc_driver::driver::compile_input
  35: rustc_driver::run_compiler

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0 (84203cac6 2018-03-25) running on x86_64-unknown-linux-gnu

error: Could not compile `l2_loki_server`.

Caused by:
  process didn't exit successfully: `rustc --crate-name l2_loki_server src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=893315bf4caeed9c -C extra-filename=-893315bf4caeed9c --out-dir /home/hedgar/share/src/L2LokiServer/target/debug/deps -C incremental=/home/hedgar/share/src/L2LokiServer/target/debug/incremental -L dependency=/home/hedgar/share/src/L2LokiServer/target/debug/deps --extern futures=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libfutures-91246f81fd045a75.rlib --extern serde_derive=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libserde_derive-d252ad1b95e490b0.so --extern actix=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libactix-be666c94d5155c10.rlib --extern failure=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libfailure-b81d669fb4be0425.rlib --extern diesel=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libdiesel-d4b184aa0bb9f13a.rlib --extern serde=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libserde-d7469299e49f1978.rlib --extern env_logger=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libenv_logger-d933f45970fb75ad.rlib --extern serde_json=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libserde_json-020d1231a90ed580.rlib --extern actix_web=/home/hedgar/share/src/L2LokiServer/target/debug/deps/libactix_web-a8bed6e22a252cda.rlib -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/backtrace-sys-593be0f56d76b72e/out/.libs -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/brotli-sys-63eab5591cb8b2f0/out -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/ring-e012e05d037e6ca4/out -L native=/home/hedgar/share/src/L2LokiServer/target/debug/build/miniz-sys-3e2c2de0c9951ff4/out -L native=/usr/lib` (exit code: 101)
```

I had a problem with different futures crate versions conflicting with each other. When I fixed it and finished playing with it, I returned to one of my futures handles (at the beginning of the post), commented the third arm, uncommented the second one and ran 'cargo run', then the compiler crashed.
I removed the whole /target directory and recompiled everything. Does not crash now.

**Comment by Mark-Simulacrum** [comment]
Could you provide the codebase which caused this error? Otherwise I think we'll have to close this as it's not actionable without a test case.

**Comment by hedgar2017** [comment]
Sorry, I cannot provide the codebase. Therefore, please, close the issue.
