### ISSUE TITLE
Unexpected compiler panic in 2018-05-12 nightly

### ISSUE THREAD

**Issue by jgrillo** [rust-lang/rust#50707]
I'm getting a panic `thread 'main' panicked at 'miri allocation never successfully created', libcore/option.rs:914:5` while trying to compile an actix project using cargo with rustc version `1.27.0-nightly (ff2ac35db 2018-05-12)`.

This is the invocation with a backtrace and cargo's failure message:
```
[jgrillo@localhost wordcountrs]$ RUST_BACKTRACE=1 cargo build --release
   Compiling h2 v0.1.6
   Compiling trust-dns-proto v0.3.3
   Compiling tokio-signal v0.1.5
   Compiling actix v0.5.6
   Compiling cookie v0.10.1
thread 'main' panicked at 'miri allocation never successfully created', libcore/option.rs:914:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::option::expect_failed
             at libcore/option.rs:914
  10: rustc_mir::interpret::const_eval::value_to_const_value
  11: rustc_mir::interpret::const_eval::const_val_field
  12: rustc_mir::hair::pattern::PatternContext::const_to_pat::{{closure}}
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  14: rustc_mir::hair::pattern::PatternContext::const_to_pat
  15: rustc_mir::hair::pattern::PatternContext::lower_path
  16: rustc_mir::hair::pattern::PatternContext::lower_pattern
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  20: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  21: rustc::hir::intravisit::walk_expr
  22: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  23: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  24: <rustc_mir::hair::pattern::check_match::MatchVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  25: rustc::session::Session::track_errors
  26: rustc_mir::hair::pattern::check_match::check_match
  27: rustc::dep_graph::graph::DepGraph::with_task_impl
  28: rustc::ty::context::tls::with_related_context
  29: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  30: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  31: rustc::hir::intravisit::Visitor::visit_nested_body
  32: rustc::hir::Crate::visit_all_item_likes
  33: rustc_mir::hair::pattern::check_match::check_crate
  34: rustc::util::common::time
  35: rustc::ty::context::tls::enter_context
  36: <std::thread::local::LocalKey<T>>::with
  37: rustc::ty::context::TyCtxt::create_and_enter
  38: rustc_driver::driver::compile_input
  39: rustc_driver::run_compiler_impl
  40: <scoped_tls::ScopedKey<T>>::set
  41: syntax::with_globals
  42: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  43: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  44: rustc_driver::run
  45: rustc_driver::main
  46: std::rt::lang_start::{{closure}}
  47: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  48: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  49: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  50: main
  51: __libc_start_main
  52: <unknown>
query stack during panic:
#0 [check_match] processing `hpack::table::index_static`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (ff2ac35db 2018-05-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `h2`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Please let me know if I can provide any more information. Thanks!

**Comment by maccam912** [comment]
I just got an identical bug. I'm also using actix-web, had the "miri allocation" message and "could not compile h2". It looks like @jgrillo has this bug report covered, but let me know if I can help out at all too.

**Comment by pietroalbini** [comment]
Thanks for reporting this! This is indeed a regression from stable to nightly, and it happens when trying to compile the `h2` crate.

A bisect points at #50249 as the cause of the regression. cc @oli-obk @Zoxc

**Comment by nikomatsakis** [comment]
Possibly fixed. Marking as P-high until we verify.

**Comment by Pzixel** [comment]
Have this issue on `cargo 1.27.0-nightly (9e53ac6e6 2018-05-07)`

Sample code:

```rs
extern crate hyper;

fn main() {}
```

Output:

```
C:/Users/Alex/.cargo/bin/cargo.exe run --package boyan_detector_bot --bin boyan_detector_bot
   Compiling h2 v0.1.10
thread 'main' panicked at 'miri allocation never successfully created', libcore\option.rs:914:5
stack backtrace:
   0:         0x67ac882b - mingw_set_invalid_parameter_handler
   1:         0x67ad09e9 - mingw_set_invalid_parameter_handler
   2:         0x67ad8086 - mingw_set_invalid_parameter_handler
   3:         0x67ad7dad - mingw_set_invalid_parameter_handler
   4:          0x4deee80 - mingw_set_invalid_parameter_handler
   5:         0x67ad86e0 - mingw_set_invalid_parameter_handler
   6:         0x67ad82cc - mingw_set_invalid_parameter_handler
   7:         0x67ad828f - mingw_set_invalid_parameter_handler
   8:         0x67b2fd6c - mingw_set_invalid_parameter_handler
   9:         0x67b5d281 - mingw_set_invalid_parameter_handler
  10:          0x60ec9f9 - mingw_set_invalid_parameter_handler
  11:          0x60f01f0 - mingw_set_invalid_parameter_handler
  12:          0x612b3a1 - mingw_set_invalid_parameter_handler
  13:          0x5efc7d3 - mingw_set_invalid_parameter_handler
  14:          0x612ab21 - mingw_set_invalid_parameter_handler
  15:          0x612a3cf - mingw_set_invalid_parameter_handler
  16:          0x61280e9 - mingw_set_invalid_parameter_handler
  17:          0x5f5c8c6 - mingw_set_invalid_parameter_handler
  18:          0x5f0de93 - mingw_set_invalid_parameter_handler
  19:          0x5f08603 - mingw_set_invalid_parameter_handler
  20:          0x5f8e2e5 - mingw_set_invalid_parameter_handler
  21:          0x60d4385 - mingw_set_invalid_parameter_handler
  22:          0x5f8e145 - mingw_set_invalid_parameter_handler
  23:          0x5f8e145 - mingw_set_invalid_parameter_handler
  24:          0x5f903f0 - mingw_set_invalid_parameter_handler
  25:          0x6120294 - mingw_set_invalid_parameter_handler
  26:          0x5f8df42 - mingw_set_invalid_parameter_handler
  27:          0x48ceaf8 - mingw_set_invalid_parameter_handler
  28:          0x4b0afdb - mingw_set_invalid_parameter_handler
  29:          0x4b74f13 - mingw_set_invalid_parameter_handler
  30:          0x4bf3d97 - mingw_set_invalid_parameter_handler
  31:          0x4c409e6 - mingw_set_invalid_parameter_handler
  32:          0x5f78f39 - mingw_set_invalid_parameter_handler
  33:          0x60da717 - mingw_set_invalid_parameter_handler
  34:          0x5f8de69 - mingw_set_invalid_parameter_handler
  35:         0x7029f850 - mingw_set_invalid_parameter_handler
  36:         0x7033481c - mingw_set_invalid_parameter_handler
  37:         0x702e3169 - mingw_set_invalid_parameter_handler
  38:         0x7021cac2 - mingw_set_invalid_parameter_handler
  39:         0x7026915c - mingw_set_invalid_parameter_handler
  40:         0x7033efab - mingw_set_invalid_parameter_handler
  41:         0x70273c37 - mingw_set_invalid_parameter_handler
  42:         0x70228252 - mingw_set_invalid_parameter_handler
  43:         0x70271b44 - mingw_set_invalid_parameter_handler
  44:         0x67b11878 - mingw_set_invalid_parameter_handler
  45:         0x7033b68b - mingw_set_invalid_parameter_handler
  46:         0x7034a53d - mingw_set_invalid_parameter_handler
  47:           0x401565 - std::rt::lang_start::{{closure}}::h9b8d47d5009967cd
  48:         0x67ad8206 - mingw_set_invalid_parameter_handler
  49:         0x67b11878 - mingw_set_invalid_parameter_handler
  50:         0x67ad8159 - mingw_set_invalid_parameter_handler
  51:         0x67ac81af - mingw_set_invalid_parameter_handler
  52:           0x4015f7 - main
  53:           0x4013f7 - _tmainCRTStartup
  54:           0x40151a - mainCRTStartup
  55:     0x7fffa8273033 - mingw_set_invalid_parameter_handler
  56:     0x7fffa83c1430 - mingw_set_invalid_parameter_handler
query stack during panic:
#0 [check_match] processing `hpack::table::index_static`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (ac5c0848d 2018-05-14) running on x86_64-pc-windows-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `h2`.

To learn more, run the command again with --verbose.

Process finished with exit code 101
```

Branch with sample code: https://github.com/Pzixel/boyan_detector_bot/tree/feature/rust-compiler-bug

**Comment by Pzixel** [comment]
Sorry, I think i just have to update my nightly. DIdn't see my version is so outdated.
