### ISSUE TITLE
Compiler panics on nightly compiling `speculate` tests

### ISSUE THREAD

**Issue by Denaun** [rust-lang/rust#50915]
I tried compiling some tests written using `speculate` (https://github.com/utkarshkukreti/speculate.rs), and this causes the rust compiler to panic.

I checked a few versions, and it looks like this broke sometime between `rustc 1.26.0-nightly (a04b88d19 2018-03-19)` and `rustc 1.26.0-nightly (f5631d9ac 2018-03-24)`. Apparently it does not compile with `rustc 1.26.0-nightly (a04b88d19 2018-03-19)`, but that's another issue.

Minimal example
---
```rust
#![feature(plugin)]
#![cfg_attr(test, plugin(speculate))]

speculate! {
    describe hello {
        it "panics" {
            assert!(true);
        }
    }
}
```

Correctly fails compiling on
---
```
rustc 1.26.0-nightly (a04b88d19 2018-03-19)
binary: rustc
commit-hash: a04b88d1941644df01fa5e31dd43e0f57c13d938
commit-date: 2018-03-19
host: x86_64-apple-darwin
release: 1.26.0-nightly
LLVM version: 6.0
```

Compilation panics on
---
```
rustc 1.26.0-nightly (f5631d9ac 2018-03-24)
binary: rustc
commit-hash: f5631d9ac7745dd6eaea2bc6c236d5f8e54e9a18
commit-date: 2018-03-24
host: x86_64-apple-darwin
release: 1.26.0-nightly
LLVM version: 6.0
```

Backtrace of `cargo test`
---
```
   Compiling speculate v0.0.26
   Compiling panic v0.1.0 (file:///.../panic)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Diagnostic { level: Fatal, message: [("expected string literal", NoStyle)], code: None, span: MultiSpan { primary_spans: [Span { lo: BytePos(85), hi: BytePos(90), ctxt: #0 }], span_labels: [(Span { lo: BytePos(85), hi: BytePos(90), ctxt: #0 }, "expected string literal")] }, children: [], suggestions: [] }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: <syntax::ast::AngleBracketedParameterData as core::clone::Clone>::clone
             at libcore/macros.rs:26
  10: <syntax::ast::AngleBracketedParameterData as core::clone::Clone>::clone
             at libcore/result.rs:782
  11: speculate::parser::parse_describe
             at speculate-0.0.26/src/parser.rs:27
  12: speculate::parser::parse
             at speculate-0.0.26/src/parser.rs:8
  13: speculate::expand_speculate
             at speculate-0.0.26/src/lib.rs:26
  14: <F as syntax::ext::base::TTMacroExpander>::expand
  15: syntax::ext::expand::MacroExpander::expand_invoc
  16: syntax::ext::expand::MacroExpander::expand
  17: syntax::ext::expand::MacroExpander::expand_crate
  18: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  19: rustc::util::common::time
  20: rustc_driver::driver::phase_2_configure_and_expand
  21: rustc_driver::driver::compile_input
  22: rustc_driver::run_compiler_with_pool
  23: syntax::with_globals
  24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  25: __rust_maybe_catch_panic
  26: rustc_driver::run
  27: rustc_driver::main
  28: std::rt::lang_start::{{closure}}
  29: std::panicking::try::do_call
  30: __rust_maybe_catch_panic
  31: std::rt::lang_start_internal
  32: main
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (a3085756e 2018-05-19) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `panic`.

To learn more, run the command again with --verbose.
```

**Comment by kennytm** [comment]
It looks like a bug of speculate, not rustc.

Try again writing the spec as `describe "hello"` (a string, not an identifier).

**Comment by Denaun** [comment]
I don't know how I missed that… This explains both the panic message and the backtrace. Thanks!
Before closing the issue, should rustc catch plugin panics and show a different error message?

**Comment by ishitatsuyuki** [comment]
Please update your nightly and check if it ICEs.

**Comment by Denaun** [comment]
I checked with `rustc 1.28.0-nightly (cb20f68d0 2018-05-21)`, and it still ICEs if I try to compile the syntactically incorrect code (using `describe hello` instead of `describe "hello"`).

**Comment by Dylan-DPC** [comment]
@Denaun is this still an issue?

**Comment by Denaun** [comment]
Sorry for the delay.

I would say this is not an issue anymore, thanks! \
This is what I get now if I try to compile the syntactically incorrect code with `rustc 1.68.2 (9eb3afe9e 2023-03-27)`:
```
error: proc macro panicked
 --> src/main.rs:3:1
  |
3 | / speculate! {
4 | |     describe hello {
5 | |         it "panics" {
6 | |             assert!(true);
7 | |         }
8 | |     }
9 | | }
  | |_^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: ParseError(Some("failed to parse anything")
```

(FTR things changed and the first two lines of the example should now be replaced with something like `#[macro_use] extern crate speculate as other_speculate;`, which was nice 🙂)
