### ISSUE TITLE
/checkout/src in backtraces

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#51253]
```rust
fn main() {
    let big_val = std::i32::MAX;
    let x = big_val + 1;
    println!("{} + 1 = {}", std::i32::MAX, x);
}
```

getting in debug build ...

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: myapp::main
             at src/main.rs:3
  10: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  15: main
  16: __libc_start_main
  17: _start
```

Which is fine but getting `libstd/rt.rs` and `/checkout/src/libstd/rt.rs` which is misleading because I don't have a /checkout directory. Maybe better to point to stick to `libstd/rt.rs`?.

**Comment by Mark-Simulacrum** [comment]
Hm, it'd be interesting to find out why some of the paths are remapped to start with `libstd` and some aren't. I suspect this might be indicative of a bug somewhere in the compiler. cc @michaelwoerister

**Comment by michaelwoerister** [comment]
Do we even actively use path remapping for dist builds?

**Comment by Mark-Simulacrum** [comment]
No we don't... which is odd, because I'm confused why else those paths would sometimes be partial and sometimes complete.

**Comment by michaelwoerister** [comment]
If someone in @rust-lang/release wants to experiment: the `-Cremap-path-prefix` option should not be too hard to use.

**Comment by awoimbee** [comment]
Fixed, please close.

The (full) backtrace now looks like:
```
thread 'main' panicked at 'attempt to add with overflow', src/main.rs:5:13
stack backtrace:
   0: rust_begin_unwind
(...)
  19:     0x55f9928ac3c1 - std::rt::lang_start::{{closure}}::hcc222df3ba29fe0f
                               at /home/toto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  20:     0x55f9928c1dc7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  21:     0x55f9928c1dc7 - std::panicking::try::do_call::h81cbbe0c3b30a28e
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  22:     0x55f9928c1dc7 - std::panicking::try::hbeeb95b4e1f0a876
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  23:     0x55f9928c1dc7 - std::panic::catch_unwind::h59c48ccb40a0bf20
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  24:     0x55f9928c1dc7 - std::rt::lang_start_internal::ha53ab63f88fee728
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  25:     0x55f9928ac397 - std::rt::lang_start::h6ffeed854908e5f1
                               at /home/toto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  26:     0x55f9928ac34a - main
  27:     0x7f0e96185152 - __libc_start_main
  28:     0x55f9928ac08e - _start
  29:                0x0 - <unknown>
```

Also, the exemple code now needs `#[allow(arithmetic_overflow)]`.
And `rt.rs` only appears in backtraces with `RUST_BACKTRACE=full`.

**Comment by spastorino** [comment]
@awoimbee
