### ISSUE TITLE
ICE when using rls (vscode)

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#51488]
```
thread '<unnamed>' panicked at 'Box<Any>', librustc_errors\lib.rs:554:9
stack backtrace:
   0: <std::collections::hash::map::DefaultHasher as core::fmt::Debug>::fmt
   1: <std::sys::windows::dynamic_lib::DynamicLibrary as core::ops::drop::Drop>::drop
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: rustc::ty::walk::walk_shallow
   5: std::panicking::rust_panic_with_hook
   6: <rustc_errors::emitter::ColorConfig as core::fmt::Debug>::fmt
   7: rustc_errors::Handler::bug
   8: rustc::session::config::OutputTypes::values
   9: rustc::ty::context::tls::track_diagnostic
  10: rustc::ty::context::tls::track_diagnostic
  11: rustc::ty::context::tls::track_diagnostic
  12: rustc::session::bug_fmt
  13: rustc::session::bug_fmt
  14: rustc::hir::map::Map::get
  15: rustc_save_analysis::SaveContext::get_path_def
  16: <unknown>
  17: <rustc_save_analysis::json_dumper::Access as core::fmt::Debug>::fmt
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <rustc_save_analysis::CallbackHandler<'b> as rustc_save_analysis::SaveHandler>::save
  23: <unknown>
  24: <unknown>
  25: rustc_driver::profile::dump
  26: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  27: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_trait_item
  28: <unknown>
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler
  31: rustc_driver::target_features::add_configuration
  32: <unknown>
  33: rustc_driver::run_compiler
  34: <unknown>
  35: <unknown>
  36: _rust_maybe_catch_panic
  37: <unknown>
  38: <unknown>
  39: _rust_maybe_catch_panic
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: _rust_maybe_catch_panic
  45: <unknown>
  46: <std::sys::windows::handle::Handle as core::ops::drop::Drop>::drop
  47: std::sys::windows::thread::Thread::new
  48: BaseThreadInitThunk
  49: RtlUserThreadStart
query stack during panic:
end of query stack

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (4a9c58c6b 2018-06-05) running on x86_64-pc-windows-msvc
```

**Comment by pietroalbini** [comment]
Does this also happen on stable rust?

**Comment by nc-x** [comment]
I don't have the code which gave the above ICE so I won't be able to reproduce it.

But a similar ICE is given by this code - 
(Tested on nightly. I don't have stable installed right now.)

```
use std::collections::HashMap;

struct something {
    map: HashMap<String, u32>,
}

impl something {
    fn new() -> something {
        return something {
            map: {
                let mut m = HashMap::new();
                m.insert("abcde".to_string(), 3);
                m
            },
        };
    }
}

fn main() {
    let t = something::new();
    let string = "abcde".to_string();

    let x = match t.map.get<S>(&string) {    <--  this invalid <S> is giving the crash in vscode -> output -> rust language server
        Some(z) => (*z).clone(),
        None => 2,
    };
    println!("Hello, world!");
}
```

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
stack backtrace:
   0: <std::collections::hash::map::DefaultHasher as core::fmt::Debug>::fmt
   1: <std::sys::windows::dynamic_lib::DynamicLibrary as core::ops::drop::Drop>::drop
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: rustc::ty::walk::walk_shallow
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic
  10: rustc_save_analysis::SaveContext::get_expr_data
  11: <unknown>
  12: <rustc_save_analysis::json_dumper::Access as core::fmt::Debug>::fmt
  13: <rustc_save_analysis::json_dumper::Access as core::fmt::Debug>::fmt
  14: <rustc_save_analysis::json_dumper::Access as core::fmt::Debug>::fmt
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <rustc_save_analysis::CallbackHandler<'b> as rustc_save_analysis::SaveHandler>::save
  19: <unknown>
  20: <unknown>
  21: rustc_driver::profile::dump
  22: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  23: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_trait_item
  24: <unknown>
  25: rustc_driver::driver::compile_input
  26: rustc_driver::run_compiler
  27: rustc_driver::target_features::add_configuration
  28: <unknown>
  29: rustc_driver::run_compiler
  30: <unknown>
  31: <unknown>
  32: _rust_maybe_catch_panic
  33: <unknown>
  34: <unknown>
  35: _rust_maybe_catch_panic
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: _rust_maybe_catch_panic
  41: <unknown>
  42: <std::sys::windows::handle::Handle as core::ops::drop::Drop>::drop
  43: std::sys::windows::thread::Thread::new
  44: BaseThreadInitThunk
  45: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (4a9c58c6b 2018-06-05) running on x86_64-pc-windows-msvc
```

**Comment by neelesh-c** [comment]
@pietroalbini Yes, I can reproduce it on stable as well.

**Comment by camelid** [comment]
ping from triage: Status?

**Comment by mati865** [comment]
OP account was deleted, there is no point in keeping this issue open.
