### ISSUE TITLE
ICE panicked at `slice index starts at 4292870143 but ends at 782341` when compile serde_json

### ISSUE THREAD

**Issue by csmoe** [rust-lang/rust#51568]
Err:
```
thread 'main' panicked at 'slice index starts at 4292870143 but ends at 782341', libcore/slice/mod.rs:2262:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::slice::slice_index_order_fail
             at libcore/slice/mod.rs:2262
  10: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::read_usize
  11: serialize::serialize::Decoder::read_enum
  12: serialize::serialize::Decoder::read_struct
  13: rustc_metadata::decoder::<impl rustc_metadata::schema::Lazy<T>>::decode
  14: rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::item_children_untracked
  15: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::populate_module_if_necessary
  16: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::build_reduced_graph_for_item
  17: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  18: syntax::visit::walk_item
  19: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  20: syntax::ext::expand::Expansion::visit_with
  21: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion
  22: syntax::ext::expand::MacroExpander::collect_invocations
  23: syntax::ext::expand::MacroExpander::expand
  24: syntax::ext::expand::MacroExpander::expand_crate
  25: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  26: rustc::util::common::time
  27: rustc_driver::driver::phase_2_configure_and_expand
  28: rustc_driver::driver::compile_input
  29: rustc_driver::run_compiler_impl
  30: <scoped_tls::ScopedKey<T>>::set
  31: syntax::with_globals
  32: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  33: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  34: rustc_driver::run
  35: rustc_driver::main
  36: std::rt::lang_start::{{closure}}
  37: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  38: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  39: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  40: main
  41: __libc_start_main
  42: <unknown>
query stack during panic:
end of query stack
```
Meta:
`serde_json = "1.0.15"`

*rustc*
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-beta.1 (03fb2f447 2018-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debug-assertions=off -C overflow-checks=on -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by pietroalbini** [comment]
I can't seem to reproduce this ICE using the same compiler flags as you, 1.27.0-beta.1 on `x86_64-unknown-linux-gnu` and `serde_json = 1.0.15`. Are you sure the ICE happens there?

Also, does it affect the latest beta (you're using an old one), stable and nightly?

**Comment by csmoe** [comment]
@pietroalbini I occured this err repeatedly when compiling rustc `./x.py test src/test/ui`, but the testing worked with my local nightly rustc(`––enable-local-rust`). I’ll update more reproduction step soon if possible(may caused by my wrong local machine setting)

**Comment by csmoe** [comment]
close since not reproducible locally.
