### ISSUE TITLE
Custom add lang_item makes compiler unexpectedly panic

### ISSUE THREAD

**Issue by DominusCarnufex** [rust-lang/rust#51766]
Hello,

The following minimal code

```rust
#![crate_type="rlib"]
#![feature(lang_items)]
#![feature(no_core)]
#![no_core]

#[lang = "sized"]
pub trait Sized {}

#[lang = "copy"]
pub trait Copy {}

#[lang = "add"]
pub trait Add<T> {
  #[must_use]
  fn add(self, T) -> Self;
}

impl Add<usize> for usize {
  #[inline]
  fn add(self, other : usize) -> Self { self + other }
}

impl<T> Add<usize> for *const T {
  #[inline]
  fn add(self, off : usize) -> Self {
    ((self as usize) + off) as Self
  }
}

pub unsafe fn buggy(pos : *const u16) -> *const u16 {
  pos + 2
}
```

makes the compiler panic with the following error

```console
thread 'main' panicked at 'assertion failed: op.node == hir::BiEq || op.node == hir::BiNe || op.node == hir::BiLe ||
    op.node == hir::BiLt || op.node == hir::BiGe || op.node == hir::BiGt', librustc_passes/rvalue_promotion.rs:307:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::begin_panic
   7: <rustc_passes::rvalue_promotion::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
   8: <rustc_passes::rvalue_promotion::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
   9: <rustc_passes::rvalue_promotion::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  10: rustc_passes::rvalue_promotion::rvalue_promotable_map
  11: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::rvalue_promotable_map<'tcx>>::compute
  12: rustc::dep_graph::graph::DepGraph::with_task_impl
  13: rustc::ty::context::tls::with_related_context
  14: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  15: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  16: rustc_passes::rvalue_promotion::const_is_rvalue_promotable_to_static
  17: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_is_rvalue_promotable_to_static<'tcx>>::compute
  18: rustc::dep_graph::graph::DepGraph::with_task_impl
  19: rustc::ty::context::tls::with_related_context
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  22: rustc_passes::rvalue_promotion::check_crate
  23: rustc::util::common::time
  24: rustc::ty::context::tls::enter_context
  25: <std::thread::local::LocalKey<T>>::with
  26: rustc::ty::context::TyCtxt::create_and_enter
  27: rustc_driver::driver::compile_input
  28: rustc_driver::run_compiler_with_pool
  29: <scoped_tls::ScopedKey<T>>::set
  30: syntax::with_globals
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  33: rustc_driver::run
  34: rustc_driver::main
  35: std::rt::lang_start::{{closure}}
  36: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  37: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  38: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:397
             at libstd/rt.rs:58
  39: main
  40: __libc_start_main
  41: <unknown>
query stack during panic:
#0 [rvalue_promotable_map] checking which parts of `buggy` are promotable to static
#1 [const_is_rvalue_promotable_to_static] const checking if rvalue is promotable to static `buggy`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (60efbdead 2018-06-23) running on x86_64-unknown-linux-gnu
```

I’m using the latest nightly.

```console
rustc 1.28.0-nightly (60efbdead 2018-06-23)
binary: rustc
commit-hash: 60efbdead6b65d7fd8ebfd564c86de4594ef0076
commit-date: 2018-06-23
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```

**Comment by DominusCarnufex** [comment]
I’ve tried going around the problem, and this code compiles perfectly well.

```rust
#![crate_type="rlib"]
#![feature(lang_items)]
#![feature(no_core)]
#![no_core]

#[lang = "sized"]
pub trait Sized {}

#[lang = "copy"]
pub trait Copy {}

#[lang = "freeze"]
trait Freeze {}

#[lang = "add"]
pub trait Add<T> {
  #[must_use]
  fn add(self, T) -> Self;
}

impl Add<usize> for usize {
  #[inline]
  fn add(self, other : usize) -> Self { self + other }
}

impl<T> Add<usize> for *const T {
  #[inline]
  fn add(self, off : usize) -> Self {
    ((self as usize) + off) as Self
  }
}

pub unsafe fn buggy(pos : *const u16) -> *const u16 {
  ((pos as usize) + 2) as _
}
```

Notice how I converted the pointer to a `usize` so as not to use the `Add<usize> for *const T` implementation, but the `Add<usize> for <usize>` implementation.

On the other hand, if I use this as the two last items, the bug comes back.

```rust
impl<T> Add<*const T> for *const T {
  #[inline]
  fn add(self, off : *const T) -> Self {
    ((self as usize) + (off as usize)) as Self
  }
}

pub unsafe fn buggy(pos : *const u16) -> *const u16 {
  pos + (2 as _)
}
```

The problem comes from [this block of code](https://github.com/rust-lang/rust/blob/master/src/librustc_passes/rvalue_promotion.rs#L304-L315), as per the error message.

If I understand well what happens, the code explicitly forbids to implement numeric operators on raw pointers. I think it should not. Can we safely remove this assert, or just add some more operators?

**Comment by oli-obk** [comment]
This is working as intended. The ICE is only reachable if libcore (or your own rewrite of it) violates Rust language invariants. One such invariant is, that `*const T` and `*mut T` do not implement the `Add`, `Sub`, `Mul` and similar traits. Instead there are inherent methods on the types that can be used to expliclity opt into a specific behaviour. Changing this behaviour requires an RFC. Opening a thread on https://internals.rust-lang.org/ beforehand can help figuring out the details around such a change.
