### ISSUE TITLE
Internal Compiler error in nighly: thread 'main' panicked at 'region_obligations not empty

### ISSUE THREAD

**Issue by xMAC94x** [rust-lang/rust#51763]
<short summary of the bug>

I tried this code:
https://github.com/veloren/game
(sorry i have no made a minimal reproduction szenario yet)
run cargo run in the voxygen folder with the nightly version

I expected to see this happen: no internal compiler error

Instead, this happened: internal compiler error

##Link to Travis where error occured
https://travis-ci.org/veloren/game/jobs/396105627

## Meta

`rustc --version --verbose`:
```
$ rustc --version
rustc 1.28.0-nightly (60efbdead 2018-06-23)
$ rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
$ cargo --version
cargo 1.28.0-nightly (e2348c2db 2018-06-07)
```
Backtrace:
```
thread 'main' panicked at 'region_obligations not empty: [
    (
        NodeId(
            2439
        ),
        RegionObligation(sub_region='_#1r, sup_type=nalgebra::Matrix<f32, nalgebra::U4, nalgebra::U4, nalgebra::MatrixArray<f32, nalgebra::U4, nalgebra::U4>>)
    )
]', librustc/infer/mod.rs:1057:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   8: rustc::infer::InferCtxt::take_and_reset_region_constraints
   9: rustc_mir::borrow_check::nll::type_check::TypeChecker::prove_predicates
  10: <rustc_mir::borrow_check::nll::type_check::TypeVerifier<'a, 'b, 'gcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_constant
  11: <rustc_mir::borrow_check::nll::type_check::TypeVerifier<'a, 'b, 'gcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_mir
  12: rustc_mir::borrow_check::nll::type_check::type_check_internal
  13: rustc_mir::borrow_check::nll::compute_regions
  14: rustc_mir::borrow_check::do_mir_borrowck
  15: rustc::ty::context::tls::with_related_context
  16: rustc::infer::InferCtxtBuilder::enter
  17: rustc_mir::borrow_check::mir_borrowck
  18: rustc::ty::query::__query_compute::mir_borrowck
  19: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_borrowck<'tcx>>::compute
  20: rustc::ty::context::tls::with_context
  21: rustc::dep_graph::graph::DepGraph::with_task_impl
  22: rustc::ty::context::tls::with_related_context
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  24: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  25: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck
  26: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners
  27: rustc::util::common::time
  28: rustc::ty::context::tls::enter_context
  29: <std::thread::local::LocalKey<T>>::with
  30: rustc::ty::context::TyCtxt::create_and_enter
  31: rustc_driver::driver::compile_input
  32: rustc_driver::run_compiler_with_pool
  33: <scoped_tls::ScopedKey<T>>::set
  34: syntax::with_globals
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  36: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  37: rustc_driver::run
  38: rustc_driver::main
  39: std::rt::lang_start::{{closure}}
  40: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  41: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  42: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:397
             at libstd/rt.rs:58
  43: main
  44: __libc_start_main
  45: <unknown>
```
query stack during panic:
```
#0 [mir_borrowck] processing `model_object::mat4_to_array`
end of query stack
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.28.0-nightly (60efbdead 2018-06-23) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
```

**Comment by estebank** [comment]
Closing as per the fixed duplicate. Feel free to reopen if you see this problem again!
