### ISSUE TITLE
ICE when incremental compilation can't write to the target directory

### ISSUE THREAD

**Issue by Eijebong** [rust-lang/rust#52127]
```
error: incremental compilation: could not create session directory lock file: Permission denied (os error 13)

thread 'main' panicked at 'librustc/session/mod.rs:802: Trying to get session directory from IncrCompSession `NotInitialized`', librustc/session/mod.rs:1293:26
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::begin_panic
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::ty::context::tls::with_opt::{{closure}}
   9: rustc::ty::context::tls::with_context_opt
  10: rustc::ty::context::tls::with_opt
  11: rustc::session::opt_span_bug_fmt
  12: rustc::session::bug_fmt
  13: rustc::session::Session::incr_comp_session_dir
  14: rustc_incremental::persist::fs::garbage_collect_session_directories
  15: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  16: rustc::util::common::time
  17: rustc_driver::driver::phase_2_configure_and_expand
  18: rustc_driver::driver::compile_input
  19: rustc_driver::run_compiler_with_pool
  20: <scoped_tls::ScopedKey<T>>::set
  21: <scoped_tls::ScopedKey<T>>::set
  22: syntax::with_globals
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  25: rustc_driver::run
  26: rustc_driver::main
  27: std::rt::lang_start::{{closure}}
  28: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  29: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  30: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  31: main
  32: __libc_start_main
  33: <unknown>
query stack during panic:
end of query stack
error: aborting due to previous error


error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (e06c87544 2018-07-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `deploy`.   
```

Ran `sudo cargo run` and then `cargo build` after changing some code.

**Comment by asyncfn** [comment]
Hi,

I checked this issue. Right now you have the following error

```sh
cargo build
error: failed to open: /home/michal/projects/tests/test_playground/target/debug/.cargo-lock

Caused by:
  Permission denied (os error 13)
```

@oli-obk IMO this issue could be closed. 1 we don't have an ICE anymore. 2 we have a nice error message that says exactly what is wrong.

Best regards,
Michal
