### ISSUE TITLE
ICE: "leak-check would have us replace ... with ..." (HRTBs)

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#52259]
I tried this code ([Playground](https://play.rust-lang.org/?gist=6725437d4879ca49d74fb0c55f709ba1&version=stable&mode=debug&edition=2015), this is as minimal as I can get it):

```rust
// ======================================
// BaseTrait
// ======================================
trait BaseTrait<'s> {
    type Target;
}

// Impl for ()
impl<'s> BaseTrait<'s> for () {
    type Target = u32;
}

// Impl for references
impl<'s, M> BaseTrait<'s> for &'s M
where
    M: BaseTrait<'s>,
{
    type Target = M::Target;
}


// ======================================
// MidTrait
// ======================================
trait MidTrait<'s> {}

impl<'s, M> MidTrait<'s> for M
where
    M: BaseTrait<'s>,
    M::Target: Clone,
{
}


// ======================================
// TopTrait
// ======================================
trait TopTrait {
    fn write(&self);
}

impl<T> TopTrait for Vec<T>
where
    T: for<'t> MidTrait<'t>,
{
    fn write(&self) {}
}


// ======================================
// main
// ======================================
fn main() {
    vec![&()].write();
}
```
This results in:

```
thread 'main' panicked at 'leak-check would have us replace ReErased with BrNamed(crate0:DefIndex(1:17), 't)', librustc/infer/higher_ranked/mod.rs:743:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   8: rustc::infer::higher_ranked::<impl rustc::infer::InferCtxt<'a, 'gcx, 'tcx>>::plug_leaks::{{closure}}
   9: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::TyS<'tcx>>::super_fold_with
  10: <rustc_data_structures::array_vec::ArrayVec<A> as core::iter::traits::Extend<<A as rustc_data_structures::array_vec::Array>::Element>>::extend
  11: <rustc_data_structures::accumulate_vec::AccumulateVec<A> as core::iter::traits::FromIterator<<A as rustc_data_structures::array_vec::Array>::Element>>::from_iter
  12: rustc::ty::fold::TypeFoldable::fold_with
  13: rustc::ty::fold::TypeFoldable::fold_with
  14: rustc::ty::fold::TypeFoldable::fold_with
  15: rustc::infer::higher_ranked::<impl rustc::infer::InferCtxt<'a, 'gcx, 'tcx>>::plug_leaks
  16: rustc::traits::select::SelectionContext::impl_or_trait_obligations
  17: rustc::traits::select::SelectionContext::vtable_impl
  18: rustc::infer::InferCtxt::in_snapshot
  19: rustc::traits::select::SelectionContext::confirm_candidate
  20: rustc::traits::select::SelectionContext::select
  21: <rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
  22: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_where_possible
  23: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_all_or_error
  24: rustc::traits::codegen::<impl rustc::infer::InferCtxt<'a, 'gcx, 'tcx>>::drain_fulfillment_cx_or_panic
  25: rustc::ty::context::tls::with_related_context
  26: rustc::infer::InferCtxtBuilder::enter
  27: rustc::traits::codegen::codegen_fulfill_obligation
  28: rustc::ty::query::__query_compute::codegen_fulfill_obligation
  29: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::codegen_fulfill_obligation<'tcx>>::compute
  30: rustc::dep_graph::graph::DepGraph::with_task_impl
  31: rustc::ty::context::tls::with_related_context
  32: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  33: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  34: rustc::ty::instance::Instance::resolve
  35: rustc_mir::monomorphize::collector::visit_fn_use
  36: <rustc_mir::monomorphize::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  39: rustc::util::common::time
  40: rustc_mir::monomorphize::collector::collect_crate_mono_items
  41: rustc::util::common::time
  42: rustc_codegen_llvm::base::collect_and_partition_mono_items
  43: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute
  44: rustc::dep_graph::graph::DepGraph::with_task_impl
  45: rustc::ty::context::tls::with_related_context
  46: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  47: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  48: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  49: rustc::util::common::time
  50: rustc_driver::driver::phase_4_codegen
  51: rustc_driver::driver::compile_input::{{closure}}
  52: rustc::ty::context::tls::enter_context
  53: <std::thread::local::LocalKey<T>>::with
  54: rustc::ty::context::TyCtxt::create_and_enter
  55: rustc_driver::driver::compile_input
  56: rustc_driver::run_compiler_with_pool
  57: <scoped_tls::ScopedKey<T>>::set
  58: <scoped_tls::ScopedKey<T>>::set
  59: syntax::with_globals
  60: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  61: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  62: rustc_driver::run
  63: rustc_driver::main
  64: std::rt::lang_start::{{closure}}
  65: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  66: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  67: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  68: main
  69: __libc_start_main
  70: <unknown>
query stack during panic:
#0 [codegen_fulfill_obligation] checking if `TopTrait` fulfills its obligations
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (e5f6498d3 2018-07-10) running on x86_64-unknown-linux-gnu
```

Happens on stable and nightly.

**Comment by LukasKalbertodt** [comment]
Apparently, this has been fixed. Works on `1.31.0-nightly (2018-10-09 96cafc53cfc6667a03c8)`. Still breaks on `1.30.0-beta.14 (2018-10-09 1320d2145eb7d9f99983)`.
