### ISSUE TITLE
Rustc panic when trying to use a mod that does not exist in an extern crate

### ISSUE THREAD

**Issue by Yatekii** [rust-lang/rust#52583]
So I don't know how I could describe better than the log can. Have a look for yourself:
```
error[E0432]: unresolved import `pyo3::proc_macro`> ] 208/210  
   --> src/lib/parsing/schema_file/mod.rs:104:11
    |
104 | use pyo3::proc_macro::pyclass;
    |           ^^^^^^^^^^ Could not find `proc_macro` in `pyo3`

thread 'main' panicked at 'Expected Def::Macro(..)', librustc_resolve/build_reduced_graph.rs:596:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::begin_panic
   7: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::get_macro
   8: rustc_resolve::Resolver::check_proc_macro_attrs
   9: rustc_resolve::Resolver::resolve_item
  10: syntax::visit::walk_item
  11: rustc_resolve::Resolver::resolve_item
  12: syntax::visit::walk_item
  13: rustc_resolve::Resolver::resolve_item
  14: rustc_resolve::Resolver::resolve_crate
  15: rustc::util::common::time
  16: rustc_driver::driver::phase_2_configure_and_expand
  17: rustc_driver::driver::compile_input
  18: rustc_driver::run_compiler_with_pool
  19: <scoped_tls::ScopedKey<T>>::set
  20: <scoped_tls::ScopedKey<T>>::set
  21: syntax::with_globals
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  24: rustc_driver::run
  25: rustc_driver::main
  26: std::rt::lang_start::{{closure}}
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  28: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  29: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  30: main
  31: __libc_start_main
  32: <unknown>
query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (254f8796b 2018-07-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

If more info is needed, I'll gladly provide it!
Best,
Yatekii

**Comment by hellow554** [comment]
This has nothing to do with the unavailable extern crate I guess. Could not reprdocude this with the MCVE.

https://play.rust-lang.org/?gist=5f202ba8295a7c5f7e0b682577918fcb&version=nightly&mode=release&edition=2015

Maybe you can try to provide a MCVE (although I guess the BT should be enough for the team to figure this one out ;) )

**Comment by Yatekii** [comment]
Unfortunately the MCVE is really hard to do as I was tired and didn't store the broken state ... real dumb from my side, unfortunately :(

**Comment by Dylan-DPC** [comment]
Closing this as there is no mcve and there's no way to reproduce this
