### ISSUE TITLE
Compiler panic on nightly 12ed235ad 2018-07-18

### ISSUE THREAD

**Issue by njaremko** [rust-lang/rust#52595]
```
RUST_BACKTRACE=1 cargo check --verbose
    (Edit: removed verbose dependency output)                                                       
    Checking iota-lib-rs v0.0.32 (file:///home/njaremko/Development/rust/iota-lib-rs)                                                       
     Running `rustc --edition=2018 --crate-name iota_lib_rs src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=18f264f74a33ac24 -C extra-filename=-18f264f74a33ac24 --out-dir /home/njaremko/Development/rust/iota-lib-rs/target/debug/deps -C incremental=/home/njaremko/Development/rust/iota-lib-rs/target/debug/incremental -L dependency=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps --extern chrono=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libchrono-2c4a20a404860717.rmeta --extern crossbeam=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrossbeam-1dc394dd641fa01f.rmeta --extern crunchy=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrunchy-9d303dc8705e22ca.rmeta --extern failure=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfailure-be4122abde74ddb3.rmeta --extern futures=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfutures-868df803a2d0ee05.rmeta --extern lazy_static=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/liblazy_static-cdc8cdabb13175ed.rmeta --extern num_cpus=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libnum_cpus-5bc5b56fb72b7759.rmeta --extern rand=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/librand-b7d39cebaf27dab3.rmeta --extern regex=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libregex-9fec8678a6fff143.rmeta --extern reqwest=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libreqwest-018ef8bc6fb68a5f.rmeta --extern serde=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde-0ae2b6ea699e7ff3.rmeta --extern serde_derive=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_derive-e5f626992c8020e8.so --extern serde_json=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_json-f5f0863ea72d5780.rmeta -L native=/home/njaremko/Development/rust/iota-lib-rs/target/debug/build/backtrace-sys-913fb9c4b6a52caa/out`
warning: unused import: `futures::future::Future`==================> ] 159/160: iota-lib-rs
  --> src/iota_api.rs:13:5
   |
13 | use futures::future::Future;
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0/1:95 ~ iota_lib_rs[7f28]::iota_api[0]::{{impl}}[0]::prepare_transfers[0]::{{closure}}[0])`,
 right: `DefId(0/0:219 ~ iota_lib_rs[7f28]::iota_api[0]::{{impl}}[0]::prepare_transfers[0])`', librustc/middle/region.rs:761:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   8: rustc::middle::region::ScopeTree::free_scope
   9: rustc::infer::lexical_region_resolve::LexicalResolver::expand_node
  10: rustc::infer::lexical_region_resolve::resolve
  11: rustc::infer::InferCtxt::resolve_regions_and_report_errors_inner
  12: rustc_typeck::check::regionck::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::regionck_fn
  13: rustc::ty::context::tls::with_related_context
  14: rustc::infer::InferCtxtBuilder::enter
  15: rustc_typeck::check::typeck_tables_of
  16: rustc::ty::query::__query_compute::typeck_tables_of
  17: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_tables_of<'tcx>>::compute
  18: rustc::ty::context::tls::with_context
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc::ty::context::tls::with_related_context
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  23: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  24: rustc_typeck::check::typeck_tables_of
  25: rustc::ty::query::__query_compute::typeck_tables_of
  26: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_tables_of<'tcx>>::compute
  27: rustc::ty::context::tls::with_context
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::context::tls::with_related_context
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  31: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  32: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  33: rustc_typeck::collect::type_of
  34: rustc::ty::query::__query_compute::type_of
  35: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::type_of<'tcx>>::compute
  36: rustc::ty::context::tls::with_context
  37: rustc::dep_graph::graph::DepGraph::with_task_impl
  38: rustc::ty::context::tls::with_related_context
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  40: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  41: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::type_of
  42: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  43: rustc::hir::intravisit::walk_expr
  44: rustc::hir::intravisit::Visitor::visit_fn
  45: rustc::hir::intravisit::walk_impl_item
  46: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  47: rustc::hir::Crate::visit_all_item_likes
  48: rustc::session::Session::track_errors
  49: rustc_typeck::check_crate
  50: rustc::ty::context::tls::enter_context
  51: <std::thread::local::LocalKey<T>>::with
  52: rustc::ty::context::TyCtxt::create_and_enter
  53: rustc_driver::driver::compile_input
  54: rustc_driver::run_compiler_with_pool
  55: <scoped_tls::ScopedKey<T>>::set
  56: <scoped_tls::ScopedKey<T>>::set
  57: syntax::with_globals
  58: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  59: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  60: rustc_driver::run
  61: rustc_driver::main
  62: std::rt::lang_start::{{closure}}
  63: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  64: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  65: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  66: main
  67: __libc_start_main
  68: <unknown>
query stack during panic:
#0 [typeck_tables_of] processing `iota_api::API::prepare_transfers`
#1 [typeck_tables_of] processing `iota_api::API::prepare_transfers::{{closure}}`
#2 [type_of] processing `iota_api::API::prepare_transfers::{{closure}}`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (12ed235ad 2018-07-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `iota-lib-rs`.                                                                                                     

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name iota_lib_rs src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=18f264f74a33ac24 -C extra-filename=-18f264f74a33ac24 --out-dir /home/njaremko/Development/rust/iota-lib-rs/target/debug/deps -C incremental=/home/njaremko/Development/rust/iota-lib-rs/target/debug/incremental -L dependency=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps --extern chrono=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libchrono-2c4a20a404860717.rmeta --extern crossbeam=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrossbeam-1dc394dd641fa01f.rmeta --extern crunchy=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrunchy-9d303dc8705e22ca.rmeta --extern failure=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfailure-be4122abde74ddb3.rmeta --extern futures=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfutures-868df803a2d0ee05.rmeta --extern lazy_static=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/liblazy_static-cdc8cdabb13175ed.rmeta --extern num_cpus=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libnum_cpus-5bc5b56fb72b7759.rmeta --extern rand=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/librand-b7d39cebaf27dab3.rmeta --extern regex=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libregex-9fec8678a6fff143.rmeta --extern reqwest=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libreqwest-018ef8bc6fb68a5f.rmeta --extern serde=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde-0ae2b6ea699e7ff3.rmeta --extern serde_derive=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_derive-e5f626992c8020e8.so --extern serde_json=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_json-f5f0863ea72d5780.rmeta -L native=/home/njaremko/Development/rust/iota-lib-rs/target/debug/build/backtrace-sys-913fb9c4b6a52caa/out` (exit code: 101)
```

**Comment by njaremko** [comment]
To recreate this, just do something like this:
```
pub async fn search<'a>(
        &'a mut self,
        v1: &'a mut [i8],
        v2: usize,
        v3: Option<usize>,
    ) -> Result<()>
```
Basically, this happens whenever I make two parameters share the same lifetime in an async function definition.

**Comment by estebank** [comment]
@njaremko could you help me reproduce this issue? I haven't been able to with 1.29.0 and suspect that with newer versions this is fixed, but without a self contained repro case we can't add a regression test to avoid this cropping up in the future.

**Comment by rylev** [comment]
Triage: Going to close this since it's been quite a while without a repro. Feel free to reopen with a repro! 😊
