### ISSUE TITLE
NLL MIR compiler panic on 1.29.0-nightly (12ed235ad 2018-07-18)

### ISSUE THREAD

**Issue by njaremko** [rust-lang/rust#52601]
```
RUST_BACKTRACE=1 cargo check --verbose                      
       Fresh nodrop v0.1.12
       Fresh cfg-if v0.1.4                                                                                                                  
       Fresh byteorder v1.2.3                                                                                                               
       Fresh memoffset v0.2.1                                                                                                               
       Fresh scopeguard v0.3.3                                                                                                              
       Fresh version_check v0.1.4                                                                                                           
       Fresh lazy_static v1.0.1                                                                                                             
       Fresh futures v0.1.21                                                                                                                
       Fresh lazycell v0.6.0                                                                                                                
       Fresh slab v0.4.0                                                                                                                    
       Fresh cc v1.0.17                                                                                                                     
       Fresh pkg-config v0.3.11                                                                                                             
       Fresh libc v0.2.42                                                                                                                   
       Fresh either v1.5.0                                                                                                                  
       Fresh foreign-types-shared v0.1.1                                                                                                    
       Fresh scoped-tls v0.1.2                                                                                                              
       Fresh bitflags v0.9.1                                                                                                                
       Fresh build_const v0.2.1                                                                                                             
       Fresh matches v0.1.6                                                                                                                 
       Fresh unicode-xid v0.0.4                                                                                                             
       Fresh slab v0.3.0                                                                                                                    
       Fresh siphasher v0.2.2                                                                                                               
       Fresh quote v0.3.15                                                                                                                  
       Fresh safemem v0.2.0                                                                                                                 
       Fresh smallvec v0.2.1                                                                                                                
       Fresh try-lock v0.1.0                                                                                                                
       Fresh unicode-normalization v0.1.7                                                                                                   
       Fresh take v0.1.0                                                                                                                    
       Fresh unicode-xid v0.1.0                                                                                                             
       Fresh lazy_static v0.2.11                                                                                                            
       Fresh void v1.0.2                                                                                                                    
       Fresh percent-encoding v1.0.1                                                                                                        
       Fresh language-tags v0.2.2                                                                                                           
       Fresh rustc-demangle v0.1.8                                                                                                          
       Fresh itoa v0.4.2                                                                                                                    
       Fresh ucd-util v0.1.1                                                                                                                
       Fresh dtoa v0.4.3                                                                                                                    
       Fresh adler32 v1.0.3                                                                                                                 
       Fresh rand_core v0.2.1                                                                                                               
       Fresh utf8-ranges v1.0.0                                                                                                             
       Fresh crossbeam v0.3.2                                                                                                               
       Fresh arrayvec v0.4.7                                                                                                                
       Fresh iovec v0.1.2                                                                                                                   
       Fresh num_cpus v1.8.0                                                                                                                
       Fresh time v0.1.40                                                                                                                   
       Fresh memchr v2.0.1                                                                                                                  
       Fresh crossbeam-utils v0.3.2                                                                                                         
       Fresh net2 v0.2.33                                                                                                                   
       Fresh log v0.4.3                                                                                                                     
       Fresh encoding_rs v0.7.2                                                                                                             
       Fresh tokio-executor v0.1.2                                                                                                          
       Fresh tokio-service v0.1.0                                                                                                           
       Fresh relay v0.1.1                                                                                                                   
       Fresh rand v0.4.2                                                                                                                    
       Fresh futures-core-preview v0.3.0-alpha.1                                                                                            
       Fresh foreign-types v0.3.2                                                                                                           
       Fresh unicode-bidi v0.3.4                                                                                                            
       Fresh synom v0.11.3                                                                                                                  
       Fresh base64 v0.9.2                                                                                                                  
       Fresh proc-macro2 v0.4.6                                                                                                             
       Fresh unreachable v1.0.0                                                                                                             
       Fresh regex-syntax v0.6.1                                                                                                            
       Fresh rand v0.5.3                                                                                                                    
       Fresh bytes v0.4.8                                                                                                                   
       Fresh futures-cpupool v0.1.8                                                                                                         
       Fresh rand v0.3.22                                                                                                                   
       Fresh uuid v0.6.5                                                                                                                    
       Fresh aho-corasick v0.6.5                                                                                                            
       Fresh crossbeam-epoch v0.4.3                                                                                                         
       Fresh mio v0.6.15                                                                                                                    
       Fresh log v0.3.9                                                                                                                     
       Fresh want v0.0.4                                                                                                                    
       Fresh tokio-timer v0.2.4                                                                                                             
       Fresh futures-channel-preview v0.3.0-alpha.1                                                                                         
       Fresh futures-io-preview v0.3.0-alpha.1                                                                                              
       Fresh httparse v1.3.2                                                                                                                
       Fresh idna v0.1.5                                                                                                                    
       Fresh syn v0.11.11                                                                                                                   
       Fresh num-traits v0.2.5                                                                                                              
       Fresh serde v1.0.69                                                                                                                  
       Fresh quote v0.6.3                                                                                                                   
       Fresh thread_local v0.3.5                                                                                                            
       Fresh crunchy v0.2.1                                                                                                                 
       Fresh tokio-io v0.1.7                                                                                                                
       Fresh crossbeam-deque v0.3.1                                                                                                         
       Fresh unicase v1.4.2                                                                                                                 
       Fresh unicase v2.1.0                                                                                                                 
       Fresh backtrace-sys v0.1.23                                                                                                          
       Fresh openssl-sys v0.9.33                                                                                                            
       Fresh futures-sink-preview v0.3.0-alpha.1                                                                                            
       Fresh crc v1.8.1                                                                                                                     
       Fresh url v1.7.1                                                                                                                     
       Fresh synstructure v0.6.1                                                                                                            
       Fresh num-integer v0.1.39                                                                                                            
       Fresh serde_json v1.0.22                                                                                                             
       Fresh syn v0.14.4                                                                                                                    
       Fresh regex v1.0.1                                                                                                                   
       Fresh tokio-codec v0.1.0                                                                                                             
       Fresh tokio-reactor v0.1.2                                                                                                           
       Fresh tokio-threadpool v0.1.5                                                                                                        
       Fresh phf_shared v0.7.22                                                                                                             
       Fresh mime v0.3.8                                                                                                                    
       Fresh backtrace v0.3.9                                                                                                               
       Fresh openssl v0.9.24                                                                                                                
       Fresh futures-util-preview v0.3.0-alpha.1                                                                                            
       Fresh libflate v0.1.16                                                                                                               
       Fresh serde_urlencoded v0.5.2                                                                                                        
       Fresh failure_derive v0.1.1                                                                                                          
       Fresh chrono v0.4.4                                                                                                                  
       Fresh serde_derive v1.0.69                                                                                                           
       Fresh tokio-tcp v0.1.0                                                                                                               
       Fresh tokio-udp v0.1.1                                                                                                               
       Fresh tokio-fs v0.1.1                                                                                                                
       Fresh phf_generator v0.7.22                                                                                                          
       Fresh phf v0.7.22                                                                                                                    
       Fresh native-tls v0.1.5                                                                                                              
       Fresh futures-executor-preview v0.3.0-alpha.1                                                                                        
       Fresh failure v0.1.1                                                                                                                 
       Fresh tokio v0.1.7                                                                                                                   
       Fresh phf_codegen v0.7.22                                                                                                            
       Fresh futures-preview v0.3.0-alpha.1                                                                                                 
       Fresh tokio-core v0.1.17                                                                                                             
       Fresh tokio-proto v0.1.1                                                                                                             
       Fresh tokio-tls v0.1.4                                                                                                               
       Fresh hyper v0.11.27                                                                                                                 
       Fresh mime_guess v2.0.0-alpha.5                                                                                                      
       Fresh hyper-tls v0.1.3                                                                                                               
       Fresh reqwest v0.8.6                                                                                                                 
    Checking iota-lib-rs v0.0.32 (file:///home/njaremko/Development/rust/iota-lib-rs)                                                       
     Running `rustc --edition=2018 --crate-name iota_lib_rs src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=18f264f74a33ac24 -C extra-filename=-18f264f74a33ac24 --out-dir /home/njaremko/Development/rust/iota-lib-rs/target/debug/deps -C incremental=/home/njaremko/Development/rust/iota-lib-rs/target/debug/incremental -L dependency=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps --extern chrono=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libchrono-2c4a20a404860717.rmeta --extern crossbeam=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrossbeam-1dc394dd641fa01f.rmeta --extern crunchy=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrunchy-9d303dc8705e22ca.rmeta --extern failure=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfailure-be4122abde74ddb3.rmeta --extern futures=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfutures-868df803a2d0ee05.rmeta --extern lazy_static=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/liblazy_static-cdc8cdabb13175ed.rmeta --extern num_cpus=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libnum_cpus-5bc5b56fb72b7759.rmeta --extern rand=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/librand-b7d39cebaf27dab3.rmeta --extern regex=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libregex-9fec8678a6fff143.rmeta --extern reqwest=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libreqwest-018ef8bc6fb68a5f.rmeta --extern serde=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde-0ae2b6ea699e7ff3.rmeta --extern serde_derive=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_derive-e5f626992c8020e8.so --extern serde_json=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_json-f5f0863ea72d5780.rmeta -L native=/home/njaremko/Development/rust/iota-lib-rs/target/debug/build/backtrace-sys-913fb9c4b6a52caa/out`
warning: unused `#[macro_use]` import==============================> ] 159/160: iota-lib-rs
  --> src/lib.rs:64:1
   |
64 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `futures::prelude`
  --> src/iota_api.rs:13:5
   |
13 | use futures::prelude::*;
   |     ^^^^^^^^^^^^^^^^

error: internal compiler error: librustc_mir/transform/generator.rs:495: Broken MIR: generator contains type std::result::Result<std::string::String, failure::Error> in MIR, but typeck only knows about for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11> {usize, std::vec::Vec<std::string::String>, std::option::Option<usize>, fn(std::ops::Range<usize>) -> <std::ops::Range<usize> as std::iter::IntoIterator>::IntoIter {<std::ops::Range<usize> as std::iter::IntoIterator>::into_iter}, std::ops::Range<usize>, fn(std::result::Result<std::string::String, failure::Error>) -> std::result::Result<<std::result::Result<std::string::String, failure::Error> as std::ops::Try>::Ok, <std::result::Result<std::string::String, failure::Error> as std::ops::Try>::Error> {<std::result::Result<std::string::String, failure::Error> as std::ops::Try>::into_result}, impl futures::Future, std::mem::PinMut<'s, impl futures::Future>, for<'t12, 't13> fn(&'t12 mut std::mem::PinMut<'t13, impl futures::Future>) -> futures::Poll<<impl futures::Future as futures::Future>::Output> {std::future::poll_in_task_cx::<impl futures::Future>}, &'t2 mut std::mem::PinMut<'t3, impl futures::Future>, futures::Poll<std::result::Result<std::string::String, failure::Error>>, (), impl futures::Future, std::mem::PinMut<'t6, impl futures::Future>, for<'t12, 't13> fn(&'t12 mut std::mem::PinMut<'t13, impl futures::Future>) -> futures::Poll<<impl futures::Future as futures::Future>::Output> {std::future::poll_in_task_cx::<impl futures::Future>}, &'t9 mut std::mem::PinMut<'t10, impl futures::Future>}
   --> src/iota_api.rs:113:30
    |
113 |       ) -> Result<Vec<String>> {
    |  ______________________________^
114 | |         let mut index = index.unwrap_or_default();
115 | |         let security = security.unwrap_or(2);
116 | |         ensure!(input_validator::is_trytes(&seed), "Invalid seed.");
...   |
157 | |         }
158 | |     }
    | |_____^

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:502:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::span_bug_fmt
  14: <rustc_mir::transform::generator::StateTransform as rustc_mir::transform::MirPass>::run_pass
  15: rustc_mir::transform::optimized_mir::{{closure}}
  16: rustc_mir::transform::optimized_mir
  17: rustc::ty::query::__query_compute::optimized_mir
  18: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::optimized_mir<'tcx>>::compute
  19: rustc::ty::context::tls::with_context
  20: rustc::dep_graph::graph::DepGraph::with_task_impl
  21: rustc::ty::context::tls::with_related_context
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query
  24: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::generator_layout
  25: rustc_metadata::encoder::<impl rustc_metadata::isolated_encoder::IsolatedEncoder<'a, 'b, 'tcx>>::encode_info_for_closure
  26: rustc::dep_graph::graph::DepGraph::with_ignore
  27: rustc_metadata::encoder::<impl rustc_metadata::index_builder::IndexBuilder<'a, 'b, 'tcx>>::encode_info_for_expr
  28: rustc::hir::intravisit::walk_expr
  29: rustc::hir::intravisit::Visitor::visit_nested_body
  30: rustc::hir::Crate::visit_all_item_likes
  31: rustc_metadata::encoder::encode_metadata
  32: rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata
  33: rustc::ty::context::TyCtxt::encode_metadata
  34: rustc_codegen_llvm::base::write_metadata
  35: rustc::util::common::time
  36: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  37: rustc::util::common::time
  38: rustc_driver::driver::phase_4_codegen
  39: rustc_driver::driver::compile_input::{{closure}}
  40: rustc::ty::context::tls::enter_context
  41: <std::thread::local::LocalKey<T>>::with
  42: rustc::ty::context::TyCtxt::create_and_enter
  43: rustc_driver::driver::compile_input
  44: rustc_driver::run_compiler_with_pool
  45: <scoped_tls::ScopedKey<T>>::set
  46: <scoped_tls::ScopedKey<T>>::set
  47: syntax::with_globals
  48: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  49: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  50: rustc_driver::run
  51: rustc_driver::main
  52: std::rt::lang_start::{{closure}}
  53: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  54: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  55: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  56: main
  57: __libc_start_main
  58: <unknown>
query stack during panic:
#0 [optimized_mir] processing `iota_api::API::get_new_address::{{closure}}`
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (12ed235ad 2018-07-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `iota-lib-rs`.                                                                                                     

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name iota_lib_rs src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=18f264f74a33ac24 -C extra-filename=-18f264f74a33ac24 --out-dir /home/njaremko/Development/rust/iota-lib-rs/target/debug/deps -C incremental=/home/njaremko/Development/rust/iota-lib-rs/target/debug/incremental -L dependency=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps --extern chrono=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libchrono-2c4a20a404860717.rmeta --extern crossbeam=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrossbeam-1dc394dd641fa01f.rmeta --extern crunchy=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libcrunchy-9d303dc8705e22ca.rmeta --extern failure=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfailure-be4122abde74ddb3.rmeta --extern futures=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libfutures-868df803a2d0ee05.rmeta --extern lazy_static=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/liblazy_static-cdc8cdabb13175ed.rmeta --extern num_cpus=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libnum_cpus-5bc5b56fb72b7759.rmeta --extern rand=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/librand-b7d39cebaf27dab3.rmeta --extern regex=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libregex-9fec8678a6fff143.rmeta --extern reqwest=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libreqwest-018ef8bc6fb68a5f.rmeta --extern serde=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde-0ae2b6ea699e7ff3.rmeta --extern serde_derive=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_derive-e5f626992c8020e8.so --extern serde_json=/home/njaremko/Development/rust/iota-lib-rs/target/debug/deps/libserde_json-f5f0863ea72d5780.rmeta -L native=/home/njaremko/Development/rust/iota-lib-rs/target/debug/build/backtrace-sys-913fb9c4b6a52caa/out` (exit code: 101)
```

**Comment by steveklabnik** [comment]
I am *guessing* that this code is https://github.com/njaremko/iota-lib-rs ?

it needs some updating to compile:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index e2052d3..85719ae 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -1,5 +1,3 @@
-cargo-features = ["edition"]
-
 [package]
 name = "iota-lib-rs"
 edition = '2018'
diff --git a/src/lib.rs b/src/lib.rs
index 71334be..d2c39e8 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -39,8 +39,6 @@
 //! }
 //!```
 #![allow(dead_code)]
-#![feature(rust_2018_preview)]
-#![feature(rust_2018_idioms)]

 #[macro_use]
 extern crate crunchy;
```

but now compiles without error: Given no action on this since July, I'm going to guess that this was fixed; if something is still wrong here, please let me know and I'm happy to re-open!
