### ISSUE TITLE
`cargo doc` ICEs on links to unused extern crates

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#52957]
`cargo doc` ICEs on the following crate when compiling with `edition = "2018"`:

```rust
/// [link](::rand::random)
pub fn foo() {}
```

Adding `use rand;` any path in rand (like `use rand::random;`) causes `cargo doc` to succeed.

<details><summary>Backtrace:</summary>
<p>

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 10 but the index is 10', /checkout/src/libcore/slice/mod.rs:2085:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic_bounds_check
             at libcore/panicking.rs:59
   9: rustc::ty::query::__query_compute::crate_name
  10: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::crate_name<'tcx>>::compute
  11: rustc::dep_graph::graph::DepGraph::with_task_impl
  12: rustc::ty::context::tls::with_related_context
  13: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  14: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  15: rustdoc::clean::inline::record_extern_fqn
             at librustdoc/clean/inline.rs:160
  16: rustdoc::clean::register_def
             at librustdoc/clean/mod.rs:4265
  17: <[syntax::ast::Attribute] as rustdoc::clean::Clean<rustdoc::clean::Attributes>>::clean
             at librustdoc/clean/mod.rs:1495
  18: <rustdoc::doctree::Function as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
             at librustdoc/clean/mod.rs:2164
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
             at librustdoc/clean/mod.rs:613
             at /checkout/src/libcore/ops/function.rs:271
             at /checkout/src/libcore/option.rs:414
             at /checkout/src/libcore/iter/mod.rs:1394
             at /checkout/src/liballoc/vec.rs:1892
  20: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
             at /checkout/src/liballoc/vec.rs:1830
             at librustdoc/clean/mod.rs:613
  21: <rustdoc::visit_ast::RustdocVisitor<'a, 'tcx, 'rcx> as rustdoc::clean::Clean<rustdoc::clean::Crate>>::clean
             at librustdoc/clean/mod.rs:169
  22: rustdoc::core::run_core::{{closure}}::{{closure}}
             at librustdoc/core.rs:395
  23: rustc::ty::context::tls::enter_context
             at /checkout/src/librustc_driver/driver.rs:1337
             at /checkout/src/librustc/ty/context.rs:1908
             at /checkout/src/librustc/ty/context.rs:1876
             at /checkout/src/librustc/ty/context.rs:1815
             at /checkout/src/librustc/ty/context.rs:1875
  24: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/librustc/ty/context.rs:1907
             at /checkout/src/librustc/ty/context.rs:1865
             at /checkout/src/libstd/thread/local.rs:294
             at /checkout/src/libstd/thread/local.rs:248
             at /checkout/src/librustc/ty/context.rs:1857
             at /checkout/src/libstd/thread/local.rs:294
             at /checkout/src/libstd/thread/local.rs:248
  25: rustc_driver::driver::phase_3_run_analysis_passes
             at /checkout/src/librustc/ty/context.rs:1849
             at /checkout/src/librustc/ty/context.rs:1887
             at /checkout/src/librustc/ty/context.rs:1187
             at /checkout/src/librustc_driver/driver.rs:1245
  26: <scoped_tls::ScopedKey<T>>::set
             at librustdoc/core.rs:338
             at /checkout/src/librustc_driver/driver.rs:74
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  27: rustdoc::core::run_core
             at /checkout/src/librustc_driver/driver.rs:73
             at librustdoc/core.rs:249
  28: <scoped_tls::ScopedKey<T>>::set
             at librustdoc/lib.rs:675
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at /checkout/src/libsyntax/lib.rs:98
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  29: syntax::with_globals
             at /checkout/src/libsyntax/lib.rs:97
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at librustdoc/lib.rs:671
             at /checkout/src/librustc_driver/lib.rs:1657
             at /checkout/src/libstd/panic.rs:313
  31: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:310
  32: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  33: rustc_driver::monitor
             at /checkout/src/libstd/panicking.rs:289
             at /checkout/src/libstd/panic.rs:392
             at /checkout/src/librustc_driver/lib.rs:1571
             at /checkout/src/librustc_driver/lib.rs:1582
             at /checkout/src/librustc_driver/lib.rs:1656
  34: rustdoc::rust_input
             at librustdoc/lib.rs:671
  35: rustdoc::main_args
             at librustdoc/lib.rs:595
             at librustdoc/lib.rs:550
  36: <scoped_tls::ScopedKey<T>>::set
             at librustdoc/lib.rs:117
             at /checkout/src/libcore/option.rs:414
             at librustdoc/lib.rs:117
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at /checkout/src/libsyntax/lib.rs:98
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  37: syntax::with_globals
             at /checkout/src/libsyntax/lib.rs:97
  38: std::panicking::try::do_call
             at /checkout/src/libstd/thread/mod.rs:409
             at /checkout/src/libstd/panic.rs:313
             at /checkout/src/libstd/panicking.rs:310
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  40: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panicking.rs:289
             at /checkout/src/libstd/panic.rs:392
             at /checkout/src/libstd/thread/mod.rs:408
             at /checkout/src/liballoc/boxed.rs:642
  41: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:652
             at libstd/sys_common/thread.rs:24
  42: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  43: start_thread
  44: __clone
```

</p>
</details>

**Comment by GuillaumeGomez** [comment]
It's working fine on nightly...

**Comment by cramertj** [comment]
@GuillaumeGomez I just tested on the current nightly (`rustc 1.29.0-nightly (97085f9fb 2018-08-01)`) and I still get the same ICE. Just in case there's confusion, here's my Cargo.toml:

```toml
cargo-features = ["edition"]

[package]
name = "foo"
edition = "2018"
version = "0.1.0"

[dependencies]
rand = "0.5"
```

**Comment by GuillaumeGomez** [comment]
I had the same... Can you publish your code in a repository so I can just run my rustdoc on it please?

**Comment by cramertj** [comment]
[Gist](https://gist.github.com/cramertj/d7b3d84dcab6c6e9a45842781df35a23)

**Comment by GuillaumeGomez** [comment]
So the problem is a bit more complicated than expected. To sum it up: since the crate isn't used, rustc doesn't load it in phase 3, therefore, when we try to access an item inside it, since we don't have symbols loaded, it fails. @Mark-Simulacrum helped me in here trying to find multiple solutions:

 1. Going through all intra-links and load crates just in case -> works fine until you load a crate which has already be loaded, so not really viable
 2. Prevent the link to be resolved if the crate hasn't been loaded -> this seems like the best solution but some unexpected issues came up because rustc is trying to load something when it shouldn't (to put things simply).

More to come later!

**Comment by jashank** [comment]
I've run up against this one in nightly f8d34596f 2018-08-30 (while building documentation for `futures-util-preview` at 5cca7072f).

**Comment by GuillaumeGomez** [comment]
I assume it's still is... Unless some changes happened in rustc to fix this?

**Comment by Aaron1011** [comment]
@GuillaumeGomez: Using `rustdoc 1.31.0-nightly (f99911a4a 2018-10-23)`, @cramertj's gist is working fine for me.

**Comment by cramertj** [comment]
Yup, I cannot repro with a new nightly. Perhaps one of @QuietMisdreavus's changes caught this? Closing.
