### ISSUE TITLE
rustc SIGSEGV on AArch64 with nightly  in lib sysfs_gpio on Fedora 28

### ISSUE THREAD

**Issue by uwearzt** [rust-lang/rust#53071]
Howto reproduce:

1. Create a new project ```cargo init --bin```
2. Add sysfs_gpio as dependency
```
[dependencies]
sysfs_gpio = "0.5.3"
```
3. compile
```
     Running `rustc --crate-name sysfs_gpio /home/uwe/.cargo/registry/src/github.com-1ecc6299db9ec823/sysfs_gpio-0.5.3/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=11ce9553bd486458 -C extra-filename=-11ce9553bd486458 --out-dir /home/uwe/rust-test/target/debug/deps -L dependency=/home/uwe/rust-test/target/debug/deps --extern nix=/home/uwe/rust-test/target/debug/deps/libnix-1532c76627b70904.rlib --cap-lints allow`
error: Could not compile `sysfs_gpio`.

Caused by:
  process didn't exit successfully: `rustc --crate-name sysfs_gpio /home/uwe/.cargo/registry/src/github.com-1ecc6299db9ec823/sysfs_gpio-0.5.3/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=11ce9553bd486458 -C extra-filename=-11ce9553bd486458 --out-dir /home/uwe/rust-test/target/debug/deps -L dependency=/home/uwe/rust-test/target/debug/deps --extern nix=/home/uwe/rust-test/target/debug/deps/libnix-1532c76627b70904.rlib --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
```

Additional infos:
```
coredumpctl list                                                                                                                          21:57:42
TIME                            PID   UID   GID SIG COREFILE  EXE
Sat 2018-08-04 21:57:45 CEST   1548  1000  1000  11 present   /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/bin/rustc
```

```
coredumpctl gdb                                                                                                                           21:57:50
           PID: 1548 (rustc)
           UID: 1000 (uwe)
           GID: 1000 (uwe)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-08-04 21:57:41 CEST (25s ago)
  Command Line: /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/bin/rustc --crate-name sysfs_gpio /home/uwe/.cargo/registry/src/github.com-1ecc6299db9ec823/sysfs_gpio-0.5.3/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=11ce9553bd486458 -C extra-filename=-11ce9553bd486458 --out-dir /home/uwe/rust-test/target/debug/deps -L dependency=/home/uwe/rust-test/target/debug/deps --extern nix=/home/uwe/rust-test/target/debug/deps/libnix-1532c76627b70904.rlib --cap-lints allow
    Executable: /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/bin/rustc
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (uwe)
       Boot ID: 8fc8e93af1d84b5aa43ba10d1a51e6e5
    Machine ID: 8db0a625299b41ff83148b6a511913da
      Hostname: leda.localdomain
       Storage: /var/lib/systemd/coredump/core.rustc.1000.8fc8e93af1d84b5aa43ba10d1a51e6e5.1548.1533412661000000.lz4
       Message: Process 1548 (rustc) of user 1000 dumped core.
                
                Stack trace of thread 1552:
                #0  0x0000ffffac41a1e0 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #1  0x0000ffffac41a1e0 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #2  0x0000ffffac45def4 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #3  0x0000ffffac45e16c n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #4  0x0000ffffac77f260 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #5  0x0000ffffad048060 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #6  0x0000ffffad048138 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #7  0x0000ffffad047bc0 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)
                #8  0x0000ffffab8c6600 n/a (/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so)

GNU gdb (GDB) Fedora 8.1-25.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/bin/rustc...(no debugging symbols found)...done.
[New LWP 1552]
[New LWP 1554]
[New LWP 1555]
[New LWP 1550]
[New LWP 1549]
[New LWP 1548]
bt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/bin/rustc --crat'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000ffffac41a1e0 in llvm::AArch64RegisterBankInfo::getInstrMapping(llvm::MachineInstr const&) const ()
   from /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
[Current thread is 1 (Thread 0xffffa7ddfe90 (LWP 1552))]
(gdb) bt
#0  0x0000ffffac41a1e0 in llvm::AArch64RegisterBankInfo::getInstrMapping(llvm::MachineInstr const&) const ()
   from /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#1  0x0000ffffac45def4 in llvm::RegBankSelect::assignInstr(llvm::MachineInstr&) ()
   from /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#2  0x0000ffffac45e16c in llvm::RegBankSelect::runOnMachineFunction(llvm::MachineFunction&) ()
   from /home/uwe/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

```
rustc -V                                                                                                                                  22:13:18
rustc 1.30.0-nightly (3edb355b7 2018-08-03)
```

```
cat /etc/os-release                                                                                                                       22:13:44
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Comment by uwearzt** [comment]
Works with a new nightly 

```
 rustc -V                                                                                                                                                         17:53:40
rustc 1.30.0-nightly (d5a448b3f 2018-08-13)
