### ISSUE TITLE
ICE when using 2018 edition and "use super::" imports

### ISSUE THREAD

**Issue by little-arhat** [rust-lang/rust#53095]
main.rs:

```rust
use rand::random;

mod ttt;
use crate::ttt::S;

fn main() {
    let x: u8 = random();
    let mut b = ttt::it::N::new();
    println!("Hello, world!: {}/{}", x, b.s());
}
```

ttt.rs:

```rust
use rand;

pub trait S {
    fn s(&mut self) -> u8;
}

pub mod it {
    use super::rand;
    use rand::random;

    pub struct N;
    impl N {
        pub fn new() -> N {
            N
        }
    }

    impl super::S for N {
        fn s(&mut self) -> u8 {
            random() * rand::random()
        }
    }
}
```

Cargo.toml:
```toml
cargo-features = ["edition"]

[package]
name = "ice2018"
version = "0.1.0"
authors = ["R"]
edition = "2018"

[dependencies]
rand = "0.5.4"
```

(or check out [example project](https://github.com/little-arhat/rust-ice-edition2018-super))

```
$ cargo -v build
       Fresh rand_core v0.2.1
       Fresh libc v0.2.42
       Fresh rand v0.5.4
   Compiling ice2018 v0.1.0 (file:///Users/r/stuff/ice2018)
     Running `rustc --edition=2018 --crate-name ice2018 src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=b9709535ec05cf3d -C extra-filename=-b9709535ec05cf3d --out-dir /Users/r/stuff/ice2018/target/debug/deps -C incremental=/Users/r/stuff/ice2018/target/debug/incremental -L dependency=/Users/r/stuff/ice2018/target/debug/deps --extern rand=/Users/r/stuff/ice2018/target/debug/deps/librand-d128365fea08090a.rlib`
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/travis/build/rust-lang/rust/src/libcore/slice/mod.rs:2049:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: internal compiler error: cat_expr Errd
  --> src/ttt.rs:19:31
   |
19 |           fn s(&mut self) -> u8 {
   |  _______________________________^
20 | |             random() * rand::random()
21 | |         }
   | |_________^

error: internal compiler error: cat_expr Errd
  --> src/ttt.rs:20:13
   |
20 |             random() * rand::random()
   |             ^^^^^^^^

error: internal compiler error: cat_expr Errd
  --> src/ttt.rs:20:13
   |
20 |             random() * rand::random()
   |             ^^^^^^

error: internal compiler error: cat_expr Errd
  --> src/ttt.rs:20:24
   |
20 |             random() * rand::random()
   |                        ^^^^^^^^^^^^^^

error: internal compiler error: cat_expr Errd
  --> src/ttt.rs:20:24
   |
20 |             random() * rand::random()
   |                        ^^^^^^^^^^^^

error: internal compiler error: QualifyAndPromoteConstants: Mir had errors
  --> src/ttt.rs:19:9
   |
19 | /         fn s(&mut self) -> u8 {
20 | |             random() * rand::random()
21 | |         }
   | |_________^

error: internal compiler error: broken MIR in DefId(0/0:15 ~ ice2018[e3cf]::ttt[0]::it[0]::{{impl}}[1]::s[0]) ("return type"): bad type [type error]
  --> src/ttt.rs:19:9
   |
19 | /         fn s(&mut self) -> u8 {
20 | |             random() * rand::random()
21 | |         }
   | |_________^

error: internal compiler error: broken MIR in DefId(0/0:15 ~ ice2018[e3cf]::ttt[0]::it[0]::{{impl}}[1]::s[0]) (LocalDecl { mutability: Mut, is_user_variable: None, internal: false, ty: [type error], name: None, source_info: SourceInfo { span: src/ttt.rs:19:9: 21:10, scope: scope[0] }, visibility_scope: scope[0] }): bad type [type error]
  --> src/ttt.rs:19:9
   |
19 | /         fn s(&mut self) -> u8 {
20 | |             random() * rand::random()
21 | |         }
   | |_________^

thread 'main' panicked at 'no errors encountered even though `delay_span_bug` issued', librustc_errors/lib.rs:313:17
stack backtrace:
   0:        0x10bf7896f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h60992a2468d9b34b
   1:        0x10bf513cd - std::sys_common::backtrace::print::h3d595f8bfd7a6552
   2:        0x10bf81183 - std::panicking::default_hook::{{closure}}::h81129c613607866a
   3:        0x10bf80f0c - std::panicking::default_hook::h6f4c35b82282fcbb
   4:        0x10cd592f8 - rustc::util::common::panic_hook::h8c5d4add166a7821
   5:        0x10bf818c8 - std::panicking::rust_panic_with_hook::h4cd3b1a9170dbff2
   6:        0x10bc1ced7 - std::panicking::begin_panic::h36d08fbb286f451f
   7:        0x10bc17703 - <rustc_errors::Handler as core::ops::drop::Drop>::drop::hd231ad19080becf6
   8:        0x109dfdd45 - core::ptr::drop_in_place::hf8d5766926f6093a
   9:        0x109e0a80e - rustc_driver::run_compiler_with_pool::h27c8606590aa1541
  10:        0x109d67e6a - <scoped_tls::ScopedKey<T>>::set::he1de84e3a4811c35
  11:        0x109dd99d5 - syntax::with_globals::hbcdde4ce11e0b04f
  12:        0x109d671ea - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hfeac9fa871456af8
  13:        0x10bf8d7ce - __rust_maybe_catch_panic
  14:        0x109e06fbe - rustc_driver::run::ha2d70362b8d81965
  15:        0x109e14a6d - rustc_driver::main::hb3d6809f2feb6c31
  16:        0x109cfcdf5 - std::rt::lang_start::{{closure}}::hb69b1e67e5ea982e
  17:        0x10bf81287 - std::panicking::try::do_call::hc60531099b955535
  18:        0x10bf8d7ce - __rust_maybe_catch_panic
  19:        0x10bf61e0c - std::rt::lang_start_internal::h4e7f2b40bed38d65
  20:        0x109cfce5b - main
thread panicked while panicking. aborting.
error: Could not compile `ice2018`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name ice2018 src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=b9709535ec05cf3d -C extra-filename=-b9709535ec05cf3d --out-dir /Users/r/stuff/ice2018/target/debug/deps -C incremental=/Users/r/stuff/ice2018/target/debug/incremental -L dependency=/Users/r/stuff/ice2018/target/debug/deps --extern rand=/Users/r/stuff/ice2018/target/debug/deps/librand-d128365fea08090a.rlib` (signal: 4, SIGILL: illegal instruction)
```
```
rustc --version
rustc 1.30.0-nightly (3edb355b7 2018-08-03)
```
```
$ cargo --version
cargo 1.29.0-nightly (15433e8cc 2018-08-02)
```
Can be [fixed](https://github.com/little-arhat/rust-ice-edition2018-super/compare/master...how-to-fix) by removing "use" from ttt enclosing module and using rand directly. 

This is minimized example, ICE happened in a bigger project with different external crate.

**Comment by jackh726** [comment]
@little-arhat @Mark-Simulacrum This no longer ICEs on the latest stable/nightly.
