### ISSUE TITLE
Cargo does not pass CC environment variable

### ISSUE THREAD

**Issue by tomrittervg** [rust-lang/rust#53392]
I am working on a mingw-clang build for Firefox, and hit this error: https://treeherder.mozilla.org/#/jobs?repo=try&revision=d317916a52e7b9493926d599d1f57fe11be1c91a

```
     Running `/builds/worker/workspace/build/src/sccache2/sccache /builds/worker/workspace/build/src/rustc/bin/rustc --crate-name uuid third_party/rust/uuid/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=1 -C panic=abort -C debuginfo=2 -C debug-assertions=on --cfg 'feature="rand"' --cfg 'feature="v4"' -C metadata=680533a3129dedd4 -C extra-filename=-680533a3129dedd4 --out-dir /builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps --target x86_64-pc-windows-gnu -L dependency=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps -L dependency=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/debug/deps --extern rand=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps/librand-772ae5924c4e5406.rlib --cap-lints warn -C opt-level=2 -C debuginfo=2`
   0:     0x563f9b6b0b1e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h845003dfd4057b58
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x563f9b6a25e6 - std::sys_common::backtrace::print::he21204c91f031ba1
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x563f9b6a056d - std::panicking::default_hook::{{closure}}::h67eac88e3f053d87
                               at libstd/panicking.rs:211
   3:     0x563f9b6a02e0 - std::panicking::default_hook::hb9cbad724f559203
                               at libstd/panicking.rs:227
   4:     0x563f9b6a0c0c - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                               at libstd/panicking.rs:511
   5:     0x563f9b6a09b9 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                               at libstd/panicking.rs:426
   6:     0x563f9b6a091d - std::panicking::begin_panic_fmt::h6c68b0cc82493124
                               at libstd/panicking.rs:413
   7:     0x563f9b67552b - cc::fail::h40dec426326dc15c
                               at third_party/rust/cc/src/lib.rs:2181
   8:     0x563f9b66d09b - cc::Build::compile::ha10b6deb1fb0ed53
                               at third_party/rust/cc/src/lib.rs:914
   9:     0x563f9b665566 - build_script_build::main::h6e86facdc937e870
                               at third_party/rust/lmdb-sys/build.rs:14
  10:     0x563f9b665612 - std::rt::lang_start::{{closure}}::h1952862317e56406
                               at /checkout/src/libstd/rt.rs:74
  11:     0x563f9b6a0672 - std::panicking::try::do_call::hac56dcc01f36ef70
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  12:     0x563f9b6c12a9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  13:     0x563f9b69b1e5 - std::rt::lang_start_internal::h249c3823b1cd2120
     Running `/builds/worker/workspace/build/src/sccache2/sccache /builds/worker/workspace/build/src/rustc/bin/rustc --crate-name nsstring servo/support/gecko/nsstring/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=1 -C panic=abort -C debuginfo=2 -C debug-assertions=on --cfg 'feature="gecko_debug"' -C metadata=0de542a27f5f741d -C extra-filename=-0de542a27f5f741d --out-dir /builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps --target x86_64-pc-windows-gnu -L dependency=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps -L dependency=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/debug/deps --extern bitflags=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps/libbitflags-888d48167ec1bacf.rlib --extern encoding_rs=/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/deps/libencoding_rs-fe8e74f6d4864e7b.rlib -C opt-level=2 -C debuginfo=2`
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  14:     0x563f9b6655ff - std::rt::lang_start::h2841bd5def32fef5
                               at /checkout/src/libstd/rt.rs:74
  15:     0x7fa762fb42b0 - __libc_start_main
  16:     0x563f9b664bc9 - _start
  17:                0x0 - <unknown>
error: failed to run custom build command for `lmdb-sys v0.8.0`
process didn't exit successfully: `/builds/worker/workspace/build/src/obj-firefox/toolkit/library/debug/build/lmdb-sys-f9bd5eade835f887/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
CROSS_COMPILE = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "x86_64-w64-mingw32-gcc" "-O2" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-Wall" "-Wextra" "-o" "/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-pc-windows-gnu/debug/build/lmdb-sys-a1f59ada2bcc3535/out/mdb.o" "-c" "/builds/worker/workspace/build/src/third_party/rust/lmdb-sys/lmdb/libraries/liblmdb/mdb.c"
--- stderr
thread 'main' panicked at '
Internal error occurred: Failed to find tool. Is `x86_64-w64-mingw32-gcc` installed?
', third_party/rust/cc/src/lib.rs:2181:5
stack backtrace:
   0:     0x563f9b6b0b1e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h845003dfd4057b58
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x563f9b6a25e6 - std::sys_common::backtrace::print::he21204c91f031ba1
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x563f9b6a056d - std::panicking::default_hook::{{closure}}::h67eac88e3f053d87
                               at libstd/panicking.rs:211
   3:     0x563f9b6a02e0 - std::panicking::default_hook::hb9cbad724f559203
                               at libstd/panicking.rs:227
   4:     0x563f9b6a0c0c - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                               at libstd/panicking.rs:511
   5:     0x563f9b6a09b9 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                               at libstd/panicking.rs:426
   6:     0x563f9b6a091d - std::panicking::begin_panic_fmt::h6c68b0cc82493124
                               at libstd/panicking.rs:413
   7:     0x563f9b67552b - cc::fail::h40dec426326dc15c
                               at third_party/rust/cc/src/lib.rs:2181
   8:     0x563f9b66d09b - cc::Build::compile::ha10b6deb1fb0ed53
                               at third_party/rust/cc/src/lib.rs:914
   9:     0x563f9b665566 - build_script_build::main::h6e86facdc937e870
                               at third_party/rust/lmdb-sys/build.rs:14
  10:     0x563f9b665612 - std::rt::lang_start::{{closure}}::h1952862317e56406
                               at /checkout/src/libstd/rt.rs:74
  11:     0x563f9b6a0672 - std::panicking::try::do_call::hac56dcc01f36ef70
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  12:     0x563f9b6c12a9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  13:     0x563f9b69b1e5 - std::rt::lang_start_internal::h249c3823b1cd2120
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  14:     0x563f9b6655ff - std::rt::lang_start::h2841bd5def32fef5
                               at /checkout/src/libstd/rt.rs:74
  15:     0x7fa762fb42b0 - __libc_start_main
  16:     0x563f9b664bc9 - _start
  17:                0x0 - <unknown> 
```

In particular note that CC = None and x86_64-w64-mingw32-gcc - which should be "x86_64-w64-mingw32-clang".

I got pointed to this code: https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/custom_build.rs#L140-L173 which might be the relevant portion?

**Comment by tomrittervg** [comment]
Moving to cargo...

**Comment by tomrittervg** [comment]
https://github.com/rust-lang/cargo/issues/5897
