### ISSUE TITLE
ICE when existential type is exported from one crate and used in another

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/rust#53443]
```
rustc 1.30.0-dev
binary: rustc
commit-hash: b5590423e6ceb048dd7d792382e960d66b7615d2
commit-date: 2018-08-16
host: x86_64-pc-windows-msvc
release: 1.30.0-dev
LLVM version: 7.0
```

`a/Cargo.toml`

```toml
[package]
name = "a"
version = "0.1.0"
```

`a/src/lib.rs`

```rust
#![feature(existential_type)]

pub existential type Foo: std::fmt::Debug;

pub fn foo() -> Foo {
	5
}
```

`b/Cargo.toml`

```toml
[package]
name = "b"
version = "0.1.0"

[dependencies]
a = { path = "../a" }
```

`b/src/main.rs`

```rust
extern crate a;

fn main() {
	let _ = a::foo();
}
```

<details><summary>ICE</summary>

```
thread 'main' panicked at 'librustc_resolve\build_reduced_graph.rs:741: unexpected definition: Existential(DefId(9/0:3))', librustc\util\bug.rs:47:26
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\Stuff\Sources\rustsrc\src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys_common::backtrace::print
             at C:\Stuff\Sources\rustsrc\src\libstd\sys_common\backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:211
   3: std::panicking::default_hook
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:227
   4: rustc::util::common::panic_hook
             at C:\Stuff\Sources\rustsrc\src\librustc\util\common.rs:51
   5: std::panicking::rust_panic_with_hook
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:479
   6: std::panicking::begin_panic<alloc::string::String>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:409
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}<syntax_pos::span_encoding::Span>
             at C:\Stuff\Sources\rustsrc\src\librustc\util\bug.rs:47
   8: rustc::ty::context::tls::with_opt::{{closure}}<closure,!>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:2008
   9: rustc::ty::context::tls::with_context_opt<closure,!>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:1939
  10: rustc::ty::context::tls::with_opt<closure,!>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:2008
  11: rustc::util::bug::opt_span_bug_fmt<syntax_pos::span_encoding::Span>
             at C:\Stuff\Sources\rustsrc\src\librustc\util\bug.rs:42
  12: rustc::util::bug::bug_fmt
             at C:\Stuff\Sources\rustsrc\src\librustc\util\bug.rs:22
  13: rustc_resolve::Resolver::populate_module_if_necessary
             at C:\Stuff\Sources\rustsrc\src\librustc_resolve\build_reduced_graph.rs:813
  14: rustc_resolve::Resolver::build_reduced_graph_for_item
             at C:\Stuff\Sources\rustsrc\src\librustc_resolve\build_reduced_graph.rs:441
  15: rustc_resolve::build_reduced_graph::{{impl}}::visit_item
             at C:\Stuff\Sources\rustsrc\src\librustc_resolve\build_reduced_graph.rs:991
  16: syntax::visit::walk_item<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
             at C:\Stuff\Sources\rustsrc\src\libsyntax\visit.rs:245
  17: rustc_resolve::build_reduced_graph::{{impl}}::visit_item
             at C:\Stuff\Sources\rustsrc\src\librustc_resolve\build_reduced_graph.rs:992
  18: syntax::ext::expand::AstFragment::visit_with<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
             at C:\Stuff\Sources\rustsrc\src\libsyntax\ext\expand.rs:120
  19: rustc_resolve::macros::{{impl}}::visit_ast_fragment_with_placeholders
             at C:\Stuff\Sources\rustsrc\src\librustc_resolve\macros.rs:209
  20: syntax::ext::expand::MacroExpander::collect_invocations
             at C:\Stuff\Sources\rustsrc\src\libsyntax\ext\expand.rs:478
  21: syntax::ext::expand::MacroExpander::expand_fragment
             at C:\Stuff\Sources\rustsrc\src\libsyntax\ext\expand.rs:318
  22: syntax::ext::expand::MacroExpander::expand_crate
             at C:\Stuff\Sources\rustsrc\src\libsyntax\ext\expand.rs:292
  23: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}<closure>
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\driver.rs:1006
  24: rustc::util::common::time<syntax::ast::Crate,closure>
             at C:\Stuff\Sources\rustsrc\src\librustc\util\common.rs:157
  25: rustc_driver::driver::phase_2_configure_and_expand<closure>
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\driver.rs:764
  26: rustc_driver::driver::compile_input
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\driver.rs:184
  27: rustc_driver::run_compiler_with_pool
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\lib.rs:562
  28: scoped_tls::ScopedKey<syntax::Globals>::set<syntax::Globals,closure,(core::result::Result<(), rustc::session::CompileIncomplete>, core::option::Option<rustc::session::Session>)>
             at C:\Users\Arnavion\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-0.1.2\src\lib.rs:155
  29: std::panic::{{impl}}::call_once<(),closure>
             at C:\Stuff\Sources\rustsrc\src\libstd\panic.rs:313
  30: panic_unwind::__rust_maybe_catch_panic
             at C:\Stuff\Sources\rustsrc\src\libpanic_unwind\lib.rs:102
  31: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:289
  32: rustc_driver::run<closure>
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\lib.rs:187
  33: rustc_driver::main
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\lib.rs:1737
  34: std::rt::lang_start::{{closure}}<()>
             at C:\Stuff\Sources\rustsrc\src\libstd\rt.rs:74
  35: std::panicking::try::do_call<closure,i32>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:310
  36: panic_unwind::__rust_maybe_catch_panic
             at C:\Stuff\Sources\rustsrc\src\libpanic_unwind\lib.rs:102
  37: std::panicking::try<i32,closure>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:289
  38: std::rt::lang_start_internal
             at C:\Stuff\Sources\rustsrc\src\libstd\rt.rs:58
  39: main
  40: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  41: BaseThreadInitThunk
  42: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic
```

</details>

https://github.com/rust-lang/rust/blob/b5590423e6ceb048dd7d792382e960d66b7615d2/src/librustc_resolve/build_reduced_graph.rs#L741

`Resolver::build_reduced_graph_for_external_crate_def` needs an arm for `Def::Existential` ? @oli-obk 

---

Edit: [Easy playground repro](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=5b99a5302c398ecd7a2b47f27e512629)

**Comment by Arnavion** [comment]
Is the fix just to have `self.define(parent, ident, TypeNS, (def, vis, DUMMY_SP, expansion));` ? I added that and it passes the repro in the OP, but my real code triggers another ICE at:

https://github.com/rust-lang/rust/blob/b5590423e6ceb048dd7d792382e960d66b7615d2/src/librustc/middle/resolve_lifetime.rs#L630

where the `as_local_node_id` returns `None`

If you think the fix for this ICE is just that one `self.define()` call, I can start making a minimal repro for this second ICE too.

**Comment by oli-obk** [comment]
I think they are closely related. We should probably run

```rust
{
                            intravisit::walk_ty(self, ty);
                            return;
}
```

in case `as_local_node_id` returns `None`. A repro for that would be nice though. It should probably suffice to add some lifetimes to the existential type or its concrete type.

**Comment by Arnavion** [comment]
My real code's existential types do not have lifetimes, though they do have `'static` bounds.

```rust
pub existential type GetResponse: Future<Output = crate::Result<crate::Mod>> + 'static;
pub existential type DownloadResponse: Stream<Item = crate::Result<crate::reqwest_async::Chunk>> + 'static;
```

Adding `'static` bounds to the OP code did not repro the same crash.

The concrete type for the first one is compiler-created because it's the return type of an async block.

```rust
pub fn get(&self, mod_name: &factorio_mods_common::ModName) -> GetResponse {
    ...
    async {
        ....
    }
}
```

I believe this is sugar for `std::future::GenFuture`, so that should also not have any lifetimes.

The second one's concrete type is my own Stream impl that also does not have lifetimes.

It'll take me some time to get a repro because something is broken with the rustc I built locally (it started hitting #53469 even though it was fine before, not sure why). If you want you can find the real code at https://github.com/Arnavion/fac-rs/tree/3a6afed4. The existential types are in the `factorio-mods-web` crate and imported by the workspace root crate. It won't compile because I'm still in the process of migrating it to std::future, but atleast it shouldn't ICE.

**Comment by oli-obk** [comment]
> factorio-mods-web

Rust + factorio? <3

> It'll take me some time to get a repro because something is broken with the rustc I built locally

the issue you are hitting is that a `delay_span_bug` is hidden from you. I'm fixing that later today

**Comment by Arnavion** [comment]
@oli-obk The #53469 I started hitting was because of two different versions of libsyntax_pos in stage1 builds, as I described [here.](https://github.com/rust-lang/rust/issues/53469#issuecomment-415135116) So with stage2 builds I don't have that problem,


So I've got a repro for the issue where `as_local_node_id` returns `None`. It happens when using the imported existential type in a struct or enum definition, like:

`b/src/main.rs`

```rust
extern crate a;

struct Bar(a::GetResponse);

fn main() {
}
```

**Comment by Arnavion** [comment]
With the above patch, there is a new ICE when using the field inside an inherent method.

```rust
extern crate a;

struct Bar(a::Foo);

impl Bar {
	fn zero(&self) -> &a::Foo {
		&self.0
	}
}

fn main() {
}
```

<details>
<summary>ICE</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\Stuff\Sources\rustsrc\src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys_common::backtrace::print
             at C:\Stuff\Sources\rustsrc\src\libstd\sys_common\backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:211
   3: std::panicking::default_hook
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:227
   4: rustc::util::common::panic_hook
             at C:\Stuff\Sources\rustsrc\src\librustc\util\common.rs:51
   5: std::panicking::rust_panic_with_hook
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:479
   6: std::panicking::continue_panic_fmt
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:390
   7: std::panicking::rust_begin_panic
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:325
   8: core::panicking::panic_fmt
             at C:\Stuff\Sources\rustsrc\src\libcore\panicking.rs:77
   9: core::panicking::panic
             at C:\Stuff\Sources\rustsrc\src\libcore\panicking.rs:52
  10: rustc::ty::fold::{{impl}}::fold_ty<closure,closure>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\fold.rs:221
  11: rustc::ty::structural_impls::{{impl}}::super_fold_with<rustc::ty::fold::BottomUpFolder<closure, closure>>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\structural_impls.rs:851
  12: rustc::ty::fold::{{impl}}::fold_ty<closure,closure>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\fold.rs:219
  13: rustc_typeck::check::wfcheck::check_where_clauses
             at C:\Stuff\Sources\rustsrc\src\librustc_typeck\check\wfcheck.rs:503
  14: rustc_typeck::check::wfcheck::check_fn_or_method
             at C:\Stuff\Sources\rustsrc\src\librustc_typeck\check\wfcheck.rs:544
  15: rustc::ty::context::tls::with_related_context<closure,()>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:1964
  16: rustc::infer::InferCtxtBuilder::enter<closure,()>
             at C:\Stuff\Sources\rustsrc\src\librustc\infer\mod.rs:469
  17: rustc_typeck::check::wfcheck::check_associated_item
             at C:\Stuff\Sources\rustsrc\src\librustc_typeck\check\wfcheck.rs:182
  18: rustc_typeck::check::wfcheck::check_impl_item
             at C:\Stuff\Sources\rustsrc\src\librustc_typeck\check\wfcheck.rs:174
  19: rustc::ty::query::{{impl}}::compute
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\query\plumbing.rs:820
  20: rustc::ty::context::tls::with_context<closure,()>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:1953
  21: rustc::dep_graph::graph::DepGraph::with_task_impl<rustc::ty::context::TyCtxt,rustc::hir::def_id::DefId,()>
             at C:\Stuff\Sources\rustsrc\src\librustc\dep_graph\graph.rs:266
  22: rustc::ty::context::tls::with_related_context<closure,((), rustc::dep_graph::graph::DepNodeIndex)>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:1964
  23: rustc::ty::context::TyCtxt::force_query_with_job<rustc::ty::query::queries::check_impl_item_well_formed>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\query\plumbing.rs:543
  24: rustc::ty::context::TyCtxt::get_query<rustc::ty::query::queries::check_impl_item_well_formed>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\query\plumbing.rs:640
  25: rustc::ty::context::TyCtxt::ensure_query<rustc::ty::query::queries::check_impl_item_well_formed>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\query\plumbing.rs:602
  26: rustc_typeck::check::wfcheck::{{impl}}::visit_impl_item
             at C:\Stuff\Sources\rustsrc\src\librustc_typeck\check\wfcheck.rs:934
  27: rustc::hir::Crate::visit_all_item_likes<rustc::hir::itemlikevisit::DeepVisitor<rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor>>
             at C:\Stuff\Sources\rustsrc\src\librustc\hir\mod.rs:727
  28: rustc::session::Session::track_errors<closure,()>
             at C:\Stuff\Sources\rustsrc\src\librustc\session\mod.rs:320
  29: rustc::util::common::time<core::result::Result<(), rustc::util::common::ErrorReported>,closure>
             at C:\Stuff\Sources\rustsrc\src\librustc\util\common.rs:157
  30: rustc_typeck::check_crate
             at C:\Stuff\Sources\rustsrc\src\librustc_typeck\lib.rs:368
  31: rustc::ty::context::tls::enter_context<closure,core::result::Result<core::result::Result<(rustc::session::config::OutputFilenames, alloc::boxed::Box<Any>, rustc::dep_graph::graph::DepGraph), rustc::session::CompileIncomplete>, rustc::session::CompileIncomplete>>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:1868
  32: std::thread::local::LocalKey<core::cell::Cell<fn(syntax_pos::span_encoding::Span, mut core::fmt::Formatter*) -> core::result::Result<(), core::fmt::Error>>>::with<core::cell::Cell<fn(syntax_pos::span_encoding::Span, mut core::fmt::Formatter*) -> core::result::Result<(), core::fmt::Error>>,closure,core::result::Result<core::result::Result<(rustc::session::config::OutputFilenames, alloc::boxed::Box<Any>, rustc::dep_graph::graph::DepGraph), rustc::session::CompileIncomplete>, rustc::session::CompileIncomplete>>
             at C:\Stuff\Sources\rustsrc\src\libstd\thread\local.rs:248
  33: rustc::ty::context::TyCtxt::create_and_enter<closure,core::result::Result<core::result::Result<(rustc::session::config::OutputFilenames, alloc::boxed::Box<Any>, rustc::dep_graph::graph::DepGraph), rustc::session::CompileIncomplete>, rustc::session::CompileIncomplete>>
             at C:\Stuff\Sources\rustsrc\src\librustc\ty\context.rs:1186
  34: rustc_driver::driver::compile_input
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\driver.rs:285
  35: rustc_driver::run_compiler_with_pool
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\lib.rs:562
  36: scoped_tls::ScopedKey<syntax::Globals>::set<syntax::Globals,closure,(core::result::Result<(), rustc::session::CompileIncomplete>, core::option::Option<rustc::session::Session>)>
             at C:\Users\Arnavion\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-0.1.2\src\lib.rs:155
  37: std::panic::{{impl}}::call_once<(),closure>
             at C:\Stuff\Sources\rustsrc\src\libstd\panic.rs:313
  38: panic_unwind::__rust_maybe_catch_panic
             at C:\Stuff\Sources\rustsrc\src\libpanic_unwind\lib.rs:102
  39: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:289
  40: rustc_driver::run<closure>
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\lib.rs:187
  41: rustc_driver::main
             at C:\Stuff\Sources\rustsrc\src\librustc_driver\lib.rs:1737
  42: std::rt::lang_start::{{closure}}<()>
             at C:\Stuff\Sources\rustsrc\src\libstd\rt.rs:74
  43: std::panicking::try::do_call<closure,i32>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:310
  44: panic_unwind::__rust_maybe_catch_panic
             at C:\Stuff\Sources\rustsrc\src\libpanic_unwind\lib.rs:102
  45: std::panicking::try<i32,closure>
             at C:\Stuff\Sources\rustsrc\src\libstd\panicking.rs:289
  46: std::rt::lang_start_internal
             at C:\Stuff\Sources\rustsrc\src\libstd\rt.rs:58
  47: main
  48: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  49: BaseThreadInitThunk
  50: RtlUserThreadStart
query stack during panic:
#0 [check_impl_item_well_formed] processing `Bar::zero`
end of query stack
```

</details>

**Comment by andreytkachenko** [comment]
For me another variant of this issues is blocker:

`a/Cargo.toml` and `b/Cargo.toml` - is same
`a/src/lib.rs`:
```rust
#![feature(existential_type)]

pub trait View {
    type Tmp: Iterator<Item = u32>;

    fn test(&self) -> Self::Tmp;
}

pub struct X;

impl View for X {
    existential type Tmp: Iterator<Item = u32>;

    fn test(&self) -> Self::Tmp {
        vec![1,2,3].into_iter()
    }
}
```

and `b/src/main.rs`:
```rust
extern crate a;
use a::View;

fn main() {
    let v = a::X;
    v.test();
}
```

**Comment by tikue** [comment]
Is there any progress on this?

**Comment by tikue** [comment]
@Arnavion how do you feel about making a PR with your patch that has a partial fix? It looks like that would be enough to unblock me from using existential types in my project.

**Comment by Arnavion** [comment]
A bunch of stuff changed with [oli-obk's recent change](https://github.com/rust-lang/rust/commit/2a1ea44bdc5a8fd1723686020c1bbe7f4da86d1d#diff-9694c2dab1b4140752e569e4b1ba58c4) so the second patch won't apply directly. I'll retest and put up a fork.

**Comment by Arnavion** [comment]
@tikue

For the first ICE (function that returns existential type in crate A called from crate B), the patch (on top of 46880f41b7aeb897b8245474196bba9dc11f0e88) is

```patch
diff --git a/src/librustc_resolve/build_reduced_graph.rs b/src/librustc_resolve/build_reduced_graph.rs
index 25a7ff9cd3..02a28a1e2f 100644
--- a/src/librustc_resolve/build_reduced_graph.rs
+++ b/src/librustc_resolve/build_reduced_graph.rs
@@ -736,6 +736,9 @@ impl<'a, 'cl> Resolver<'a, 'cl> {
             Def::Macro(..) => {
                 self.define(parent, ident, MacroNS, (def, vis, DUMMY_SP, expansion));
             }
+            Def::Existential(..) => {
+                self.define(parent, ident, TypeNS, (def, vis, DUMMY_SP, expansion));
+            }
             _ => bug!("unexpected definition: {:?}", def)
         }
     }
```

The second ICE (existential type exported from crate A used as struct member in crate B) is already fixed.

The third ICE (existential type exported from crate A used in return type of a function in crate B) still exists.

**Comment by tikue** [comment]
@Arnavion thanks so much for following up on this! Do you want to open a PR, since you've done all the work? 😁

**Comment by Arnavion** [comment]
The patch is just guesswork on my part, and the whole thing is still broken anyway, so there's no point to me making a PR. If you want to try it you can apply that patch locally.

**Comment by jimmycuadra** [comment]
Just encountered an ICE and searching led me here. Is this just another instance of the same bug or should I report it separately?

Run `cargo test` on [rustin@a100f20](https://github.com/rustinio/rustin/tree/a100f20dc0f5621fe8174758b5ed4312f9ed4d1d) using nightly rustc and you get:

```
error: internal compiler error: src/librustc_metadata/decoder.rs:893: cannot get associated-item of `DefKey { parent: Some(DefIndex(0:47)), disambiguated_data: DisambiguatedDefPathData { data: AssocExistentialInImpl("Success"), disambiguator: 0 } }`

thread 'main' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error
```

**Comment by jonhoo** [comment]
I'm running into this with [`noria`](https://github.com/mit-pdos/noria/tree/rpc-rewrite) too. Curiously, I see this when I run tests, presumably because the crate-under-test essentially operates as an "external" crate?

**Comment by jonhoo** [comment]
@oli-obk any thoughts on the further ICEs that @Arnavion discovered when trying to fix this? This ICE sadly makes existential types pretty unusable in libraries.

**Comment by oli-obk** [comment]
Sorry about taking so long, it was just a few small fixes in the end. I think https://github.com/rust-lang/rust/pull/57836 fixes all the ICEs mentioned in this issue.

**Comment by Arnavion** [comment]
Thanks. I confirmed this fixed all the issues with my original project too.
