### ISSUE TITLE
Building basic program using datafusion results in linker panic

### ISSUE THREAD

**Issue by ehiggs** [rust-lang/rust#53554]
```
note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-apple-darwin
note: compiler flags: -C opt-level=3 -C lto --crate-type bin
```

```
$ cat Cargo.toml 
[package]
name = "ndarray-csv-reader"
version = "0.1.0"
authors = ["Ewan Higgs <ewan_higgs@some-email-provider>"]

[dependencies]
arrow = "*"
datafusion = "*"

[profile.release]
opt-level = 3
lto = true
```

```
extern crate arrow;
extern crate datafusion;

use arrow::datatypes::*;
use datafusion::exec::*;

use std::env;

fn main() {
    let ctx = ExecutionContext::local();
    let schema = Schema::new(vec![
                             Field::new("0", DataType::Utf8, false),
                             Field::new("1", DataType::Utf8, false),
                             Field::new("2", DataType::Utf8, false),
                             Field::new("3", DataType::Utf8, false),
                             Field::new("4", DataType::Utf8, false),
    ]);

    let fpath = env::args().nth(1).unwrap();
    let df1 = ctx
        .load_csv(&fpath, &schema, false, None)
        .unwrap();
    println!("df1: {}", df1.schema().to_string());
    df1.show(10);

}
```

```
   Compiling ndarray-csv-reader v0.1.0 (file:///Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader)
     Running `rustc --crate-name ndarray_csv_reader src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=079e0df49abc13ae -C extra-filename=-079e0df49abc13ae --out-dir /Users/ehiggs/src/home/csv-game/rust/  ndarray-csv-reader/target/release/deps -L dependency=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/deps --extern arrow=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/deps/libarrow-         b88108540943c586.rlib --extern datafusion=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/deps/libdatafusion-8ef2a8f5161810d2.rlib -L native=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/   build/miniz-sys-d0544425f1697f69/out -L native=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/build/lz4-sys-09a968ec9628aa73/out -L native=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/    build/zstd-sys-676b8bbb2312f44b/out`
thread 'main' panicked at 'assertion failed: !are_upstream_rust_objects_already_included(sess)', librustc_codegen_llvm/back/link.rs:1533:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 -C lto --crate-type bin

note: some of the compiler flags provided by cargo are hidden
                                                                                
error: Could not compile `ndarray-csv-reader`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ndarray_csv_reader src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=079e0df49abc13ae -C extra-filename=-079e0df49abc13ae --out-dir /Users/ehiggs/  src/home/csv-game/rust/ndarray-csv-reader/target/release/deps -L dependency=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/deps --extern arrow=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/deps/libarrow-b88108540943c586.rlib --extern datafusion=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/deps/libdatafusion-8ef2a8f5161810d2.rlib -L native=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/    target/release/build/miniz-sys-d0544425f1697f69/out -L native=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/target/release/build/lz4-sys-09a968ec9628aa73/out -L native=/Users/ehiggs/src/home/csv-game/rust/ndarray-csv-reader/    target/release/build/zstd-sys-676b8bbb2312f44b/out` (exit code: 101)
```

**Comment by ehiggs** [comment]
bt

```
thread 'main' panicked at 'assertion failed: !are_upstream_rust_objects_already_included(sess)', librustc_codegen_llvm/back/link.rs:1533:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_codegen_llvm::back::link::link_natively
   8: rustc_codegen_llvm::back::link::link_binary
   9: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link::{{closure}}
  10: rustc::util::common::time
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link
  12: rustc_driver::driver::compile_input
  13: rustc_driver::run_compiler_with_pool
  14: syntax::with_globals
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: __rust_maybe_catch_panic
  17: rustc_driver::run
  18: rustc_driver::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: main
query stack during panic:
end of query stack
```

**Comment by Dushistov** [comment]
The same problem, "lto = true" cause assert failure, rustc 1.31.1

```
thread 'main' panicked at 'assertion failed: !are_upstream_rust_objects_already_included(sess)', librustc_codegen_llvm/back/link.rs:1577:9
```


```
stack backtrace:                                                                                                                               
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                                
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                                                                  
   1: std::sys_common::backtrace::print                                                                                                        
             at libstd/sys_common/backtrace.rs:71                                                                                              
             at libstd/sys_common/backtrace.rs:59                                                                                              
   2: std::panicking::default_hook::{{closure}}                                                                                                
             at libstd/panicking.rs:211                                                                                                        
   3: std::panicking::default_hook                                                                                                             
             at libstd/panicking.rs:227                                                                                                        
   4: rustc::util::common::panic_hook                                                                                                          
   5: std::panicking::rust_panic_with_hook                                                                                                     
             at libstd/panicking.rs:480                                                                                                        
   6: std::panicking::begin_panic                                                                                                              
   7: rustc_codegen_llvm::back::link::link_natively                                                                                            
   8: rustc_codegen_llvm::back::link::link_binary                                                                                              
   9: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link::{{closure}}     
  10: rustc::util::common::time                                                                                                                
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link                  
  12: rustc_driver::driver::compile_input                                                                                                      
  13: rustc_driver::run_compiler_with_pool                                                                                                     
  14: rustc_driver::driver::spawn_thread_pool                                                                                                  
  15: rustc_driver::run_compiler                                                                                                               
  16: <scoped_tls::ScopedKey<T>>::set                                                                                                          
  17: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once                                                          
  18: __rust_maybe_catch_panic                                                                                                                 
             at libpanic_unwind/lib.rs:102                                                                                                     
  19: rustc_driver::run                                                                                                                        
  20: rustc_driver::main                       
```

**Comment by Dushistov** [comment]
Steps to reproduce is rather simple:

1. `git clone https://github.com/Dushistov/rust_swig`
2. `git checkout 35c1265b5b531789baee6ef7d76946d6415df91f`
3. patch via:
```patch
diff --git a/workspace.Cargo.toml b/workspace.Cargo.toml
index 7d53923..08313fd 100644
--- a/workspace.Cargo.toml
+++ b/workspace.Cargo.toml
@@ -1,2 +1,7 @@
 [workspace]
 members = ["macroslib", "jni_tests", "c++_tests", "android-example"]
+
+[profile.release]
+debug = true
+lto = true
```
4. `cp workspace.Cargo.toml Cargo.toml && cd macrolib && cargo build --release` 

The interesting thing that `rustup run beta cargo build --release` works (**rustc 1.32.0-beta.14 (31d631f84 2019-01-11)**), but takes 1 minute for build

**Comment by jonas-schievink** [comment]
Can reproduce on 1.31.1. This works fine on 1.32.0, closing as fixed.
