### ISSUE TITLE
Rustdoc panics on beta and nightly 

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#53875]
# Summary

After adding some functionality to [typenum](https://github.com/paholg/typenum), the compiler panicked while generating documentation on both the `nightly` and `beta` channels. The code compiles and runs successfully on all compiler versions, but docs can only be generated on `stable`.

I'm not sure how to go about generating a reduced test case, so here's a link to the [PR which caused the ICE](https://github.com/paholg/typenum/pull/101).

# Output

This is the output with `RUST_BACKTRACE=1` enabled:

```
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached

thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   8: rustc::ty::context::tls::with_opt::{{closure}}
   9: rustc::ty::context::tls::with_context_opt
  10: rustc::ty::context::tls::with_opt
  11: rustc::util::bug::opt_span_bug_fmt
  12: rustc::util::bug::bug_fmt
  13: rustc::traits::structural_impls::<impl rustc::ty::context::Lift<'tcx> for rustc::traits::SelectionError<'a>>::lift_to_tcx
  14: rustc::ty::context::TyCtxt::lift_to_global
  15: rustc::traits::select::SelectionContext::candidate_from_obligation
  16: rustc::traits::select::SelectionContext::evaluate_stack
  17: rustc::dep_graph::graph::DepGraph::with_anon_task
  18: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  19: rustc::infer::InferCtxt::probe
  20: <&'a mut I as core::iter::iterator::Iterator>::next
  21: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  22: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  23: rustc::dep_graph::graph::DepGraph::with_anon_task
  24: rustc::traits::select::SelectionContext::candidate_from_obligation
  25: rustc::traits::select::SelectionContext::evaluate_stack
  26: rustc::dep_graph::graph::DepGraph::with_anon_task
  27: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  28: rustc::infer::InferCtxt::probe
  29: <&'a mut I as core::iter::iterator::Iterator>::next
  30: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  31: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  32: rustc::dep_graph::graph::DepGraph::with_anon_task
  33: rustc::traits::select::SelectionContext::candidate_from_obligation
  34: rustc::traits::select::SelectionContext::evaluate_stack
  35: rustc::dep_graph::graph::DepGraph::with_anon_task
  36: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  37: rustc::infer::InferCtxt::probe
  38: <&'a mut I as core::iter::iterator::Iterator>::next
  39: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  40: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  41: rustc::dep_graph::graph::DepGraph::with_anon_task
  42: rustc::traits::select::SelectionContext::candidate_from_obligation
  43: rustc::traits::select::SelectionContext::evaluate_stack
  44: rustc::dep_graph::graph::DepGraph::with_anon_task
  45: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  46: rustc::infer::InferCtxt::probe
  47: <&'a mut I as core::iter::iterator::Iterator>::next
  48: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  49: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  50: rustc::dep_graph::graph::DepGraph::with_anon_task
  51: rustc::traits::select::SelectionContext::candidate_from_obligation
  52: rustc::traits::select::SelectionContext::evaluate_stack
  53: rustc::dep_graph::graph::DepGraph::with_anon_task
  54: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  55: rustc::infer::InferCtxt::probe
  56: <&'a mut I as core::iter::iterator::Iterator>::next
  57: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  58: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  59: rustc::dep_graph::graph::DepGraph::with_anon_task
  60: rustc::traits::select::SelectionContext::candidate_from_obligation
  61: rustc::traits::select::SelectionContext::evaluate_stack
  62: rustc::dep_graph::graph::DepGraph::with_anon_task
  63: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  64: rustc::infer::InferCtxt::probe
  65: <&'a mut I as core::iter::iterator::Iterator>::next
  66: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  67: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  68: rustc::dep_graph::graph::DepGraph::with_anon_task
  69: rustc::traits::select::SelectionContext::candidate_from_obligation
  70: rustc::traits::select::SelectionContext::evaluate_stack
  71: rustc::dep_graph::graph::DepGraph::with_anon_task
  72: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  73: rustc::infer::InferCtxt::probe
  74: <&'a mut I as core::iter::iterator::Iterator>::next
  75: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  76: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  77: rustc::dep_graph::graph::DepGraph::with_anon_task
  78: rustc::traits::select::SelectionContext::candidate_from_obligation
  79: rustc::traits::select::SelectionContext::evaluate_stack
  80: rustc::dep_graph::graph::DepGraph::with_anon_task
  81: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  82: rustc::infer::InferCtxt::probe
  83: <&'a mut I as core::iter::iterator::Iterator>::next
  84: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  85: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  86: rustc::dep_graph::graph::DepGraph::with_anon_task
  87: rustc::traits::select::SelectionContext::candidate_from_obligation
  88: rustc::traits::select::SelectionContext::evaluate_stack
  89: rustc::dep_graph::graph::DepGraph::with_anon_task
  90: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  91: rustc::infer::InferCtxt::probe
  92: <&'a mut I as core::iter::iterator::Iterator>::next
  93: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  94: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  95: rustc::dep_graph::graph::DepGraph::with_anon_task
  96: rustc::traits::select::SelectionContext::candidate_from_obligation
  97: rustc::traits::select::SelectionContext::evaluate_stack
  98: rustc::dep_graph::graph::DepGraph::with_anon_task
  99: rustc::traits::select::SelectionContext::evaluate_predicate_recursively

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (f8d34596f 2018-08-30) running on x86_64-unknown-linux-gnu

error: Could not document `typenum`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name typenum src/lib.rs -o /home/mackendy/src/rust/typenum/target/doc -L dependency=/home/mackendy/src/rust/typenum/target/debug/deps` (exit code: 1)
```

**Comment by ecstatic-morse** [comment]
This is a duplicate of #52873.
