### ISSUE TITLE
Compile rocket hello world project, compile error

### ISSUE THREAD

**Issue by oldtree2008** [rust-lang/rust#53985]
thread 'main' panicked at 'could not initialize thread_rng: All entropy sources failed (permanently unavailable); cause: OS RNG not yet seeded (not ready yet); cause: Resource temporarily unavailable (os error 11)', /cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.5.4/src/rngs/thread.rs:84:17
   Compiling cc v1.0.23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   8: rand::rngs::thread::THREAD_RNG_KEY::__init::{{closure}}
   9: rand::rngs::thread::THREAD_RNG_KEY::__init
  10: <std::thread::local::LocalKey<T>>::with
  11: tempfile::util::tmpname
  12: tempfile::util::create_helper
  13: tempfile::Builder::tempdir
  14: rustc_codegen_llvm::back::link::link_binary
  15: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link::{{closure}}
  16: rustc::util::common::time
  17: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link
  18: rustc_driver::driver::compile_input
  19: rustc_driver::run_compiler_with_pool
  20: <scoped_tls::ScopedKey<T>>::set
  21: rustc_driver::run_compiler
  22: syntax::with_globals
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  24: rustc_driver::run
  25: rustc_driver::main
  26: std::rt::lang_start::{{closure}}
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  28: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  29: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  30: main
  31: __libc_start_main
  32: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (6e0f1cc15 2018-09-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

**Comment by brson** [comment]
This is currently affecting TiKV's CI servers on nightly-2018-12-06, where it didn't on previous nightlies from July. We speculate it happens on linuxes without getrandom. It's not clear whether current nightlies are affected.

**Comment by brson** [comment]
The crash is in tempfile, and since this report, and the nightly TiKV is on, tempfile's rand has been upgraded from 0.5.4 to 0.6.1. It may be possible that it picked up fixes for ThreadRng, which, according to rand master, is never supposed to fail.

**Comment by Nilstrieb** [comment]
running out of entropy does not seem like a rustc issue but a system issue. there's also no reproduction, so I'm closing this as unactionable. If you think that this is a bug in the rust compiler, feel free to reopen the issue.
