### ISSUE TITLE
ICE:  trait impl with anonymous lifetime

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#54082]
cargo.toml
````toml
cargo-features = ["edition"]
[package]
name = "warn"
version = "0.1.0"
authors = ["me"]
edition = "2018"
[dependencies]
````

src/main.rs
````rust
mod a;
fn main() {}
````

src/a.rs
````rust
pub(crate) struct A<'a> {
    pub(crate) b: &'a String,
}

impl<'_> A<'_> {
    pub(crate) fn new(a: &'a String) -> Self {
        let b = &a;
        Self { b }
    }
}
````
````
    Checking warn v0.1.0 (file:///tmp/warn)
thread 'main' panicked at 'assertion failed: self.is_collecting_in_band_lifetimes', librustc/hir/lowering.rs:746:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   6: std::panicking::begin_panic
   7: rustc::hir::lowering::LoweringContext::lower_lifetime
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
   9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  10: rustc::hir::lowering::LoweringContext::lower_generics
  11: rustc::hir::lowering::LoweringContext::lower_item
  12: <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item
  13: syntax::visit::walk_item
  14: <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item
  15: rustc::hir::lowering::lower_crate
  16: rustc::util::common::time
  17: rustc_driver::driver::phase_2_configure_and_expand
  18: rustc_driver::driver::compile_input
  19: rustc_driver::run_compiler_with_pool
  20: <scoped_tls::ScopedKey<T>>::set
  21: rustc_driver::run_compiler
  22: syntax::with_globals
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  24: rustc_driver::run
  25: rustc_driver::main
  26: std::rt::lang_start::{{closure}}
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  28: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  29: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  30: main
  31: __libc_start_main
  32: <unknown>
query stack during panic:
end of query stack
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.30.0-nightly (0198a1ea4 2018-09-08) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental -C target-cpu=native --crate-type bin
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `warn`.
To learn more, run the command again with --verbose.
````

**Comment by matthiaskrgr** [comment]
turns out the the single_use_lifetimes lint is unrelated, I reduced the code a bit more and updated the heading-

**Comment by galich** [comment]
looks like the same as https://github.com/rust-lang/rust/issues/54022

**Comment by estebank** [comment]
Current output:

```
error[E0637]: `'_` cannot be used here
 --> src/a.rs:5:6
  |
5 | impl<'_> A<'_> {
  |      ^^ `'_` is a reserved lifetime name

error[E0261]: use of undeclared lifetime name `'a`
 --> src/a.rs:6:27
  |
6 |     pub(crate) fn new(a: &'a String) -> Self {
  |                           ^^ undeclared lifetime
```
