### ISSUE TITLE
[ICE] librustc_traits/normalize_erasing_regions.rs:53: could not fully normalize

### ISSUE THREAD

**Issue by WesleyAC** [rust-lang/rust#54114]
I have the following ICE:

```
error: internal compiler error: librustc_traits/normalize_erasing_regions.rs:53: could not fully normalize `fn() -> usize {std::mem::size_of::<wire::arp::Body<<AD as device::arp::ArpDevice<P>>::HardwareAddr, P>>}`
```

The full output of `cargo build` with `RUST_BACKTRACE=1` is [attached](https://github.com/rust-lang/rust/files/2368803/rustc_output.txt). This looks like it could be a regression of #49685

This is for the repo at https://fuchsia-review.googlesource.com/c/garnet/+/194882 - you should be able to cd into `bin/recovery_netstack/core/` and run `cargo build` to get this error.

cc: @cramertj and @cavedweller

**Comment by robsmith11** [comment]
Not sure if related, but I get the same error when compiling nalgebra with the latest nightly and `mir-opt-level=3` (using default `mir-opt-level` fixes it):

```
Compiling nalgebra v0.16.7
error: internal compiler error: librustc_traits/normalize_erasing_regions.rs:53: could not fully normalize `base::matrix_slice::SliceStorage<N, base::dimension::U3, base::dimension::U1, <base::matrix_array::MatrixArray<N, base::dimension::U4, base::dimension::U1> as base::storage::Storage<N, base::dimension::U4>>::RStride, <base::matrix_array::MatrixArray<N, base::dimension::U4, base::dimension::U1> as base::storage::Storage<N, base::dimension::U4>>::CStride>`                                                                                                                                                    thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:600:9
```

**Comment by oli-obk** [comment]
This is happening in const eval. I'll investigate.

**Comment by bkchr** [comment]
I'm not sure that this is the same problem, but I have found the following:
```
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:42: could not fully normalize `<[u8] as Test>::Type`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:650:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error
```

See [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6e07239ee57df16c42f6e85809f9353a) for the code.

If I change `fn test(data: <[u8] as Test>::Type);` to `fn test(data: <&[u8] as Test>::Type);` to make the resolution work, it compiles without any problem.

Without the `extern "C"`, it does not produce an ICE and prints the expected error message.

**Comment by Nilstrieb** [comment]
The link to the reproduction seems to be dead.

**Comment by bkchr** [comment]
If you mean my link above, it works for me. However, I don't see the ICE anymore.

**Comment by apiraino** [comment]
Closing as it seems the ICE can't be reproduced anymore, no MCVE was provided.
