### ISSUE TITLE
codegen/lto-removes-invokes.rs test fails

### ISSUE THREAD

**Issue by Munksgaard** [rust-lang/rust#54154]
On a fresh clone of the Github repository, the codegen/lto-removes-invokes.rs test fails with the following output:

```
$ RUST_BACKTRACE=1 ./x.py test --stage 1 src/test/codegen --test-args lto-remove  
Updating only changed submodules
Submodules updated in 0.03 seconds
    Finished dev [unoptimized] target(s) in 0.22s                                                                                                                                              
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.22s                                                                                                                                            
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.20s                                                                                                                                            
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.28s                                                                                                                                            
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 codegen artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu, llvm)
    Finished release [optimized] target(s) in 0.25s                                                                                                                                            
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.20s                                                                                                                                            
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.22s                                                                                                                                            
Copying stage1 test from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 tool compiletest (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.22s                                                                                                                                            
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 1 test
F
failures:

---- [codegen] codegen/lto-removes-invokes.rs stdout ----

error: compilation failed!
status: signal: 6
command: "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/munksgaard/src/rust/src/test/codegen/lto-removes-invokes.rs" "--target=x86_64-unknown-linux-gnu" "--out-dir" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/test/codegen/lto-removes-invokes" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-C" "lto" "-C" "panic=abort" "-O" "-L" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/test/codegen/lto-removes-invokes/auxiliary" "--emit=llvm-ir"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: function is marked #[no_mangle], but not exported
  --> /home/munksgaard/src/rust/src/test/codegen/lto-removes-invokes.rs:20:1
   |
20 |   fn foo() {
   |   ^
   |   |
   |  _help: try making it public: `pub`
   | |
21 | |     let _a = Box::new(3);
22 | |     bar();
23 | | // CHECK-LABEL: foo
24 | | // CHECK: call {{.*}} void @bar
25 | | }
   | |_^
   |
   = note: #[warn(private_no_mangle_fns)] on by default

warning: function is marked #[no_mangle], but not exported
  --> /home/munksgaard/src/rust/src/test/codegen/lto-removes-invokes.rs:29:1
   |
29 |   fn bar() {
   |   ^
   |   |
   |  _help: try making it public: `pub`
   | |
30 | |     println!("hello!");
31 | | }
   | |_^

rustc: /home/munksgaard/src/rust/src/llvm/lib/IR/Value.cpp:256: void llvm::Value::setNameImpl(const llvm::Twine&): Assertion `!getType()->isVoidTy() && "Cannot assign a name to void values!"' failed.

------------------------------------------

thread '[codegen] codegen/lto-removes-invokes.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3196:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
   6: compiletest::runtest::ProcRes::fatal
   7: compiletest::runtest::TestCx::fatal_proc_rec
   8: compiletest::runtest::TestCx::run_revision
   9: compiletest::runtest::run
  10: <F as alloc::boxed::FnBox<A>>::call_box
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1444
             at /checkout/src/liballoc/boxed.rs:642
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105


failures:
    [codegen] codegen/lto-removes-invokes.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 105 filtered out

thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:497:22
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
   6: compiletest::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: main
  12: __libc_start_main
  13: _start


command did not execute successfully: "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/stage1/lib" "--run-lib-path" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--src-base" "/home/munksgaard/src/rust/src/test/codegen" "--build-base" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/test/codegen" "--stage-id" "stage1-x86_64-unknown-linux-gnu" "--mode" "codegen" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--nodejs" "/home/munksgaard/.nvm/versions/node/v8.10.0/bin/node" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/home/munksgaard/src/rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python" "--lldb-python" "/usr/bin/python" "--gdb" "/usr/bin/gdb" "lto-remove" "--quiet" "--llvm-version" "8.0.0svn\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" ""
expected success, got: exit code: 101


failed to run: /home/munksgaard/src/rust/build/bootstrap/debug/bootstrap test --stage 1 src/test/codegen --test-args lto-remove
Build completed unsuccessfully in 0:00:04

```

Here is my config.toml file: http://termbin.com/ek7z

The config file is taken from https://rust-lang-nursery.github.io/rustc-guide/how-to-build-and-run.html#create-a-configtoml

**Comment by Munksgaard** [comment]
The test also fails with `--stage 2` but not with `--stage 0`.

**Comment by eddyb** [comment]
cc @alexcrichton @michaelwoerister @nagisa

**Comment by Munksgaard** [comment]
For your information:

```
$ uname -a
Linux turing 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

**Comment by Munksgaard** [comment]
Apparently this is caused by the `use-jemalloc = false` setting. Setting `use-jemalloc = true` fixes the error for me.

**Comment by workingjubilee** [comment]
No repro with `jemalloc = false` (specifically: the test is there but passes). Assuming fixed or erroneous.
