### ISSUE TITLE
ICE in existential type with lifetime in trait implementation

### ISSUE THREAD

**Issue by petertodd** [rust-lang/rust#54169]
Example:

```
#![feature(existential_type)]
use std::fmt::Debug;

pub trait Foo {
    type Assoc : Debug;
    fn func() -> Self::Assoc;
}

pub struct Bar;

impl Foo for Bar {
    existential type Assoc<'b> : Debug;

    fn func() -> Self::Assoc {
    }   
}

fn main() {
}
```

Backtrace:

```
$ rustc  existential-panic.rs 
error: internal compiler error: librustc/ty/subst.rs:445: Region parameter out of range when substituting in region 'b (root type=Some(Assoc::<'b>)) (index=0)

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:525:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (2f1547c0a 2018-09-11) running on x86_64-unknown-linux-gnu
```

**Comment by Matthias247** [comment]
I just run into the same problem when trying to define an async interface (with `Future`) and implement it with existential type:

```rust
#![feature(existential_type, async_await)]

use std::future::Future;

pub trait MyTrait<'a> {
    type ResultFut: Future<Output = ()> + 'a;

    fn do_sth(&'a mut self, a: &'a str) -> Self::ResultFut;
}

struct MyImpl {
}

impl<'a> MyTrait<'a> for MyImpl {
    existential type ResultFut<'a>: Future<Output = ()> + 'a;

    fn do_sth(&'a mut self, a: &'a str) -> Self::ResultFut {
        async {
            Ok(())
        }
    }
}
```

```
Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc/ty/subst.rs:489: Region parameter out of range when substituting in region 'a (root type=Some(ResultFut::<'a, 'a>)) (index=1)

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:572:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (a9ec99f42 2019-05-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Comment by petertodd** [comment]
Closing as `existential_type` no longer exists and the replacement `type_alias_impl_trait` doesn't seem to have a similar issue.
