### ISSUE TITLE
Compiler panic while parsing source code

### ISSUE THREAD

**Issue by humenda** [rust-lang/rust#54221]
I'm getting a Rust compiler panic while compiling for x86_64-unknown-l4re-uclibc
(from GNU/Linux), but the backtrace  looks as if there were a problem while parsing the Rust source itself. A crate without macros works fine. The crate that I'm getting the panic with makes heavy use of macros. It could even be that one of the macros is syntactically not correct.
Please let me know if you need more information.

```
     Running `rustc --crate-name l4 lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=4c8d090999c9849b -C extra-filename=-4c8d090999c9849b --out-dir $L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps --target x86_64-unknown-l4re-uclibc -L dependency=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps -L dependency=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/release/deps --extern libc=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps/liblibc-c67e31bbc170de3d.rlib --extern num_derive=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/release/deps/libnum_derive-752bc9a2f64320be.so --extern num_traits=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps/libnum_traits-45ee2a2c478d9ae8.rlib -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen/l4f -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen -L$L4RE_BASE/obj/l4/amd64/lib -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen/l4f -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen -L$L4RE_BASE/obj/l4/amd64/lib -g -C opt-level=3`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "read_option: expected 0 for None or 1 for Some"', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
             at librustc/util/common.rs:51
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   7: rust_begin_unwind
             at libstd/panicking.rs:326
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   9: core::result::unwrap_failed
             at $RUST_SRC/src/libcore/macros.rs:26
  10: rustc_metadata::decoder::<impl rustc_metadata::cstore::MetadataBlob>::get_root
             at $RUST_SRC/src/libcore/result.rs:808
             at librustc_metadata/decoder.rs:143
             at librustc_metadata/decoder.rs:393
  11: rustc_metadata::locator::Context::extract_one
             at librustc_metadata/locator.rs:707
             at librustc_metadata/locator.rs:612
  12: rustc_metadata::locator::Context::find_library_crate
             at librustc_metadata/locator.rs:529
  13: rustc_metadata::locator::Context::maybe_load_library_crate
             at librustc_metadata/locator.rs:315
  14: rustc_metadata::creader::CrateLoader::load
             at librustc_metadata/creader.rs:344
  15: rustc_metadata::creader::CrateLoader::resolve_crate
             at librustc_metadata/creader.rs:306
  16: rustc_metadata::creader::CrateLoader::process_extern_crate
             at librustc_metadata/creader.rs:1102
  17: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a, 'cl>>::build_reduced_graph_for_item
             at librustc_resolve/build_reduced_graph.rs:436
  18: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
             at librustc_resolve/build_reduced_graph.rs:984
  19: syntax::visit::walk_item
             at $RUST_SRC/src/libsyntax/visit.rs:166
             at $RUST_SRC/src/libsyntax/visit.rs:60
             at $RUST_SRC/src/libsyntax/visit.rs:245
  20: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
             at librustc_resolve/build_reduced_graph.rs:985
  21: syntax::ext::expand::AstFragment::visit_with
             at $RUST_SRC/src/libsyntax/ext/expand.rs:119
  22: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a, 'crateloader>>::visit_ast_fragment_with_placeholders
             at librustc_resolve/macros.rs:215
  23: syntax::ext::expand::MacroExpander::collect_invocations
             at libsyntax/ext/expand.rs:466
  24: syntax::ext::expand::MacroExpander::expand_fragment
             at libsyntax/ext/expand.rs:308
  25: syntax::ext::expand::MacroExpander::expand_crate
             at libsyntax/ext/expand.rs:282
  26: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
             at librustc_driver/driver.rs:1006
             at $RUST_SRC/src/librustc/util/common.rs:163
             at $RUST_SRC/src/librustc/util/common.rs:157
             at librustc_driver/driver.rs:1005
  27: rustc::util::common::time
             at $RUST_SRC/src/librustc/util/common.rs:163
             at $RUST_SRC/src/librustc/util/common.rs:157
  28: rustc_driver::driver::phase_2_configure_and_expand
             at librustc_driver/driver.rs:958
             at librustc_driver/driver.rs:764
  29: rustc_driver::driver::compile_input
             at librustc_driver/driver.rs:184
  30: rustc_driver::run_compiler_with_pool
             at librustc_driver/lib.rs:562
  31: <scoped_tls::ScopedKey<T>>::set
             at librustc_driver/lib.rs:484
             at librustc_driver/driver.rs:74
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  32: rustc_driver::run_compiler
             at librustc_driver/driver.rs:73
             at librustc_driver/lib.rs:483
  33: syntax::with_globals
             at librustc_driver/lib.rs:1744
             at librustc_driver/lib.rs:189
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at $RUST_SRC/src/libsyntax/lib.rs:107
             at $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at $RUST_SRC/src/libsyntax/lib.rs:106
  34: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  35: rustc_driver::run
             at $RUST_SRC/src/libstd/panicking.rs:289
             at $RUST_SRC/src/libstd/panic.rs:392
             at librustc_driver/lib.rs:1573
             at librustc_driver/lib.rs:1584
             at librustc_driver/lib.rs:1658
             at librustc_driver/lib.rs:187
  36: rustc_driver::main
             at librustc_driver/lib.rs:1737
  37: std::rt::lang_start::{{closure}}
             at $RUST_SRC/src/libstd/rt.rs:74
  38: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  40: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  41: main
  42: __libc_start_main
  43: _start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `l4`.

Caused by:
  process didn't exit successfully: `rustc --crate-name l4 lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=4c8d090999c9849b -C extra-filename=-4c8d090999c9849b --out-dir $L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps --target x86_64-unknown-l4re-uclibc -L dependency=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps -L dependency=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/release/deps --extern libc=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps/liblibc-c67e31bbc170de3d.rlib --extern num_derive=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/release/deps/libnum_derive-752bc9a2f64320be.so --extern num_traits=$L4RE_BASE/obj/l4/amd64/pkg/l4re-rust/l4/l4-rust/OBJ-amd64_gen-l4f/x86_64-unknown-l4re-uclibc/release/deps/libnum_traits-45ee2a2c478d9ae8.rlib -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen/l4f -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen -L$L4RE_BASE/obj/l4/amd64/lib -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen/l4f -L$L4RE_BASE/obj/l4/amd64/lib/amd64_gen -L$L4RE_BASE/obj/l4/amd64/lib -g -C opt-level=3` (exit code: 101)
```

**Comment by humenda** [comment]
This bug was caused by a compiler library popping up in a normal Cargo `target`
dir for reasons unknown to me. Hence closing this issue.
