### ISSUE TITLE
Vec::set_len on Vec<Option<Sender<T>>> leads to SIGSEGV on drop

### ISSUE THREAD

**Issue by Garophel** [rust-lang/rust#54245]
### Code to reproduce this:
```Rust
use std::sync::mpsc::Sender;

fn main() {
    let mut vec: Vec<Option<Sender<()>>> = Vec::with_capacity(1);
    unsafe { vec.set_len(1); }
}
```
### gdb backtrace:
```
#0  0x000055555555d20f in core::sync::atomic::atomic_swap ()
#1  0x000055555555cd6f in core::sync::atomic::AtomicUsize::swap ()
#2  0x000055555555db5a in <std::sync::mpsc::oneshot::Packet<T>>::drop_chan ()
#3  0x000055555555e7a2 in <std::sync::mpsc::Sender<T> as core::ops::drop::Drop>::drop ()
#4  0x000055555556236d in core::ptr::drop_in_place ()
#5  0x0000555555562509 in core::ptr::drop_in_place ()
#6  0x0000555555561fc3 in core::ptr::drop_in_place ()
#7  0x0000555555564aa0 in <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop ()
#8  0x0000555555561bad in core::ptr::drop_in_place ()
#9  0x0000555555564d9a in application::main ()
```
### Rustc version:
```
rustc 1.29.0 (aa3ca1994 2018-09-11)
binary: rustc
commit-hash: aa3ca1994904f2e056679fce1f185db8c7ed2703
commit-date: 2018-09-11
host: x86_64-unknown-linux-gnu
release: 1.29.0
LLVM version: 7.0
```
### Note:
* `Vec<Option<Box<Sender<()>>>>` does not segfault.
* `Vec<Rc<()>>` causes a segfault but it can be expected. `Vec<Option<Rc<()>>>` does not.

**Comment by Garophel** [comment]
Okay, didn't realize it was reading uninitialized data. Thanks for pointing that out, now I have some code to fix.
