### ISSUE TITLE
Compiler panic on on_disk_cache

### ISSUE THREAD

**Issue by drager** [rust-lang/rust#54272]
Hey,

I stumbled upon some an error while trying to run my code using `cargo run` (running `cargo check` works just fine). My code that errors can be found here: https://github.com/drager/handle/tree/with-handle3. The `master-bug` branch works fine however and can be run without errors: https://github.com/drager/handle/tree/master-bug

**Other information**
Installed Rust via rustup
OS: Arch Linux x86_64

**Error**
Here's the full output from the attempt:
```cargo run     
   Compiling handler v0.1.0 (file:///home/drager/development/handle)
warning: field is never used: `config`
  --> src/main.rs:93:9
   |
93 |         config: &'a Config<'b>,
   |         ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: field is never used: `config`
   --> src/main.rs:217:9
    |
217 |         config: &'a Config,
    |         ^^^^^^^^^^^^^^^^^^

warning: field is never used: `logger_handle`
   --> src/main.rs:219:9
    |
219 |         logger_handle: &'a logger::Handle<'b, 'b>,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `105`,
 right: `49641`', librustc/ty/query/on_disk_cache.rs:532:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0 (9634041f0 2018-07-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `handler`.
```

**Backtrace**:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `105`,
 right: `49641`', librustc/ty/query/on_disk_cache.rs:532:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   8: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
   9: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  10: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::symbol_name
  11: rustc_mir::monomorphize::item::MonoItemExt::symbol_name
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: rustc_mir::monomorphize::assert_symbols_are_distinct
  14: rustc_codegen_llvm::base::collect_and_partition_mono_items
  15: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute
  16: rustc::ty::context::tls::with_context
  17: rustc::dep_graph::graph::DepGraph::with_task_impl
  18: rustc::ty::context::tls::with_related_context
  19: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  21: rustc_codegen_llvm::base::codegen_crate
  22: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  23: rustc::util::common::time
  24: rustc_driver::driver::phase_4_codegen
  25: rustc_driver::driver::compile_input::{{closure}}
  26: rustc::ty::context::tls::enter_context
  27: <std::thread::local::LocalKey<T>>::with
  28: rustc::ty::context::TyCtxt::create_and_enter
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler_with_pool
  31: <scoped_tls::ScopedKey<T>>::set
  32: syntax::with_globals
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  34: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  35: rustc_driver::run
  36: rustc_driver::main
  37: std::rt::lang_start::{{closure}}
  38: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  40: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  41: main
  42: __libc_start_main
  43: <unknown>
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

`cargo run` with `--verbose`:

```RUST_BACKTRACE=1 cargo run --verbose
       Fresh unicode-xid v0.1.0
       Fresh version_check v0.1.4
       Fresh libc v0.2.43
       Fresh antidote v1.0.0
       Fresh cfg-if v0.1.5
       Fresh byteorder v1.2.6
       Fresh bitflags v1.0.4
       Fresh slog v2.3.3
       Fresh take_mut v0.2.2
       Fresh proc-macro2 v0.3.8
       Fresh time v0.1.40
       Fresh scheduled-thread-pool v0.2.0
       Fresh log v0.4.5
       Fresh isatty v0.1.9
       Fresh term v0.5.1
       Fresh quote v0.5.2
       Fresh num-traits v0.2.5
       Fresh proc-macro2 v0.4.19
       Fresh pq-sys v0.4.6
       Fresh r2d2 v0.8.2
       Fresh serde v1.0.78
       Fresh syn v0.13.11
       Fresh lazy_static v1.1.0
       Fresh num-integer v0.1.39
       Fresh quote v0.6.8
       Fresh diesel_derives v1.3.0
       Fresh thread_local v0.3.6
       Fresh chrono v0.4.6
       Fresh syn v0.15.4
       Fresh diesel v1.3.2
       Fresh slog-async v2.3.0
       Fresh slog-term v2.4.0
       Fresh serde_derive v1.0.78
       Fresh r2d2-diesel v1.0.0
   Compiling handler v0.1.0 (file:///home/drager/development/handle)
     Running `rustc --crate-name handler src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=d25e4ad03d5eb1e9 -C extra-filename=-d25e4ad03d5eb1e9 --out-dir /home/drager/development/handle/target/debug/deps -C incremental=/home/drager/development/handle/target/debug/incremental -L dependency=/home/drager/development/handle/target/debug/deps --extern diesel=/home/drager/development/handle/target/debug/deps/libdiesel-0976950f95418f39.rlib --extern r2d2=/home/drager/development/handle/target/debug/deps/libr2d2-be4830cf82818a3b.rlib --extern r2d2_diesel=/home/drager/development/handle/target/debug/deps/libr2d2_diesel-b4dc008b83f4c9b5.rlib --extern serde=/home/drager/development/handle/target/debug/deps/libserde-5768b7af984bb420.rlib --extern serde_derive=/home/drager/development/handle/target/debug/deps/libserde_derive-802a57c49f18d38a.so --extern slog_async=/home/drager/development/handle/target/debug/deps/libslog_async-4a297d4b8cdadbb4.rlib --extern slog=/home/drager/development/handle/target/debug/deps/libslog-b8378d34b0be1ee3.rlib --extern slog_term=/home/drager/development/handle/target/debug/deps/libslog_term-5a1f7eafc342ee34.rlib -L native=/usr/lib`
warning: field is never used: `config`
  --> src/main.rs:93:9
   |
93 |         config: &'a Config<'b>,
   |         ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: field is never used: `config`
   --> src/main.rs:217:9
    |
217 |         config: &'a Config,
    |         ^^^^^^^^^^^^^^^^^^

warning: field is never used: `logger_handle`
   --> src/main.rs:219:9
    |
219 |         logger_handle: &'a logger::Handle<'b, 'b>,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `105`,
 right: `49641`', librustc/ty/query/on_disk_cache.rs:532:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   8: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
   9: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  10: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::symbol_name
  11: rustc_mir::monomorphize::item::MonoItemExt::symbol_name
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: rustc_mir::monomorphize::assert_symbols_are_distinct
  14: rustc_codegen_llvm::base::collect_and_partition_mono_items
  15: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute
  16: rustc::ty::context::tls::with_context
  17: rustc::dep_graph::graph::DepGraph::with_task_impl
  18: rustc::ty::context::tls::with_related_context
  19: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  21: rustc_codegen_llvm::base::codegen_crate
  22: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  23: rustc::util::common::time
  24: rustc_driver::driver::phase_4_codegen
  25: rustc_driver::driver::compile_input::{{closure}}
  26: rustc::ty::context::tls::enter_context
  27: <std::thread::local::LocalKey<T>>::with
  28: rustc::ty::context::TyCtxt::create_and_enter
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler_with_pool
  31: <scoped_tls::ScopedKey<T>>::set
  32: syntax::with_globals
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  34: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  35: rustc_driver::run
  36: rustc_driver::main
  37: std::rt::lang_start::{{closure}}
  38: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  39: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  40: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  41: main
  42: __libc_start_main
  43: <unknown>
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0 (9634041f0 2018-07-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `handler`.

Caused by:
  process didn't exit successfully: `rustc --crate-name handler src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=d25e4ad03d5eb1e9 -C extra-filename=-d25e4ad03d5eb1e9 --out-dir /home/drager/development/handle/target/debug/deps -C incremental=/home/drager/development/handle/target/debug/incremental -L dependency=/home/drager/development/handle/target/debug/deps --extern diesel=/home/drager/development/handle/target/debug/deps/libdiesel-0976950f95418f39.rlib --extern r2d2=/home/drager/development/handle/target/debug/deps/libr2d2-be4830cf82818a3b.rlib --extern r2d2_diesel=/home/drager/development/handle/target/debug/deps/libr2d2_diesel-b4dc008b83f4c9b5.rlib --extern serde=/home/drager/development/handle/target/debug/deps/libserde-5768b7af984bb420.rlib --extern serde_derive=/home/drager/development/handle/target/debug/deps/libserde_derive-802a57c49f18d38a.so --extern slog_async=/home/drager/development/handle/target/debug/deps/libslog_async-4a297d4b8cdadbb4.rlib --extern slog=/home/drager/development/handle/target/debug/deps/libslog-b8378d34b0be1ee3.rlib --extern slog_term=/home/drager/development/handle/target/debug/deps/libslog_term-5a1f7eafc342ee34.rlib -L native=/usr/lib` (exit code: 101)```

**Comment by drager** [comment]
If I clone the [with_handle3 branch](https://github.com/drager/handle/tree/with-handle3) into a new folder and run `cargo run` I don't get the error.

**Comment by cjgillot** [comment]
Incremental compilation has evolved a lot since this bug was filed. Keeping it open does not bring any value.
