### ISSUE TITLE
[nightly] ICE in macros-2.0 heavy crate

### ISSUE THREAD

**Issue by jjpe** [rust-lang/rust#54515]
I have a crate that uses an unholy mix of `macros 2.0`, a couple of old-style macros I haven't been able to get rid of yet, and a derive macro.
Together these generate what should become a parser.

So far they combine marvellously well, but now I've hit an ICE.
It's got a nondeterministic feel to it, as sometimes when I build, I get this ICE, and sometimes (with identical code and config!) the build runs perfectly smoothly. However, when I do a `cargo clean` and then a `cargo build`, so far it builds correctly every time so *perhaps.

I'm using `rustc rustc 1.30.0-nightly (79fcc58b2 2018-09-18)`, and I'm working on a `Fedora 28` host.

The build log containing the ICE: 

````
-*- mode: cargo-process; default-directory: "~/dev/toy_parser/" -*-
Cargo-Process started at Sun Sep 23 23:41:55

/home/j/.cargo/bin/cargo build --manifest-path /home/j/dev/toy_parser/Cargo.toml 
   Compiling toy_parser v0.1.0 (/home/j/dev/toy_parser)
parser type: ToyParser
thread 'main' panicked at 'index out of bounds: the len is 24 but the index is 41', libcore/slice/mod.rs:2046:10
stack backtrace:
   0:     0x7fb036ccd69e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4d878bab27fd0f70
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fb036ca6966 - std::sys_common::backtrace::print::h35bb85d3b98f8626
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7fb036ca45cd - std::panicking::default_hook::{{closure}}::h200bf37fc8919558
                               at libstd/panicking.rs:211
   3:     0x7fb036ca4340 - std::panicking::default_hook::he298f773e406a972
                               at libstd/panicking.rs:227
   4:     0x7fb033321811 - rustc::util::common::panic_hook::h7a484c4bc0b7e466
   5:     0x7fb036ca4c93 - std::panicking::rust_panic_with_hook::hb8a41eeada5713c9
                               at libstd/panicking.rs:481
   6:     0x7fb036ca4839 - std::panicking::continue_panic_fmt::hb390f79f908da969
                               at libstd/panicking.rs:391
   7:     0x7fb036ca4735 - rust_begin_unwind
                               at libstd/panicking.rs:326
   8:     0x7fb036d37dab - core::panicking::panic_fmt::h9df27fbdce6cd890
                               at libcore/panicking.rs:77
   9:     0x7fb036d37d5f - core::panicking::panic_bounds_check::hd3ca1cf6860f370f
                               at libcore/panicking.rs:59
  10:     0x7fb032f4cb72 - <rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x> as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode::haf36a776572d0532
  11:     0x7fb032efc5a3 - <syntax_pos::hygiene::ExpnInfo as serialize::serialize::Decodable>::decode::hc90798acbce0dee6
  12:     0x7fb032f4c840 - <rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x> as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode::haf36a776572d0532
  13:     0x7fb032f0dc5c - serialize::serialize::Decoder::read_struct::hf1af29377a264348
  14:     0x7fb032f07344 - serialize::serialize::Decoder::read_struct::h44ed42a7b3bad803
  15:     0x7fb032f187ec - serialize::serialize::Decoder::read_seq::he8ff09d78ef83105
  16:     0x7fb03300e003 - <rustc::mir::Mir<'tcx> as serialize::serialize::Decodable>::decode::{{closure}}::h2848e41c2d23fc5c
  17:     0x7fb032f4654b - rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result::h7c3782a51ad12b8e
  18:     0x7fb032d02b00 - <rustc::ty::query::queries::optimized_mir<'tcx> as rustc::ty::query::config::QueryDescription<'tcx>>::try_load_from_disk::h03fcc147b0cfef99
  19:     0x7fb0330ad786 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query::h84aa791ae4321112
  20:     0x7fb0331aa416 - rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::optimized_mir::ha2f74ea799f06ac4
  21:     0x7fb034eea948 - rustc_metadata::encoder::<impl rustc_metadata::isolated_encoder::IsolatedEncoder<'a, 'b, 'tcx>>::encode_optimized_mir::h7592cc16217bb636
  22:     0x7fb034eebc60 - rustc_metadata::encoder::<impl rustc_metadata::isolated_encoder::IsolatedEncoder<'a, 'b, 'tcx>>::encode_info_for_item::h93226db7d2f33957
  23:     0x7fb034ec4757 - rustc::ty::context::tls::with_context::hbd124c5effdbb45f
  24:     0x7fb034dfc9f3 - <rustc_metadata::encoder::EncodeVisitor<'a, 'b, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h225d6897f30e15b7
  25:     0x7fb034e10f1a - rustc::hir::Crate::visit_all_item_likes::he0147d47e484bb95
  26:     0x7fb034dfdb9a - rustc_metadata::encoder::encode_metadata::h5a7037861d93f8ef
  27:     0x7fb034edfcae - rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata::hc5c3c6fabad0559f
  28:     0x7fb0331a0c80 - rustc::ty::context::TyCtxt::encode_metadata::h31815857e386509c
  29:     0x7fb02cabfb06 - rustc_codegen_llvm::base::write_metadata::h978ea2f11520b6aa
  30:     0x7fb02c9e9b94 - rustc::util::common::time::hf555149f3077fea3
  31:     0x7fb02cac04a4 - rustc_codegen_llvm::base::codegen_crate::h37dba7e1eb0177e1
  32:     0x7fb02caf4f9f - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::hb62d04d0bb4aee9d
  33:     0x7fb037038ce1 - rustc::util::common::time::hed0ba969379f3144
  34:     0x7fb037055a1d - rustc_driver::driver::phase_4_codegen::h7de0b037a738f5e8
  35:     0x7fb0370ef343 - rustc_driver::driver::compile_input::{{closure}}::h02fddf9351c26ef6
  36:     0x7fb0370e8129 - rustc::ty::context::tls::enter_context::h8f0d021915b2f34d
  37:     0x7fb0370aa26a - <std::thread::local::LocalKey<T>>::with::h68c56c88e15ae56a
  38:     0x7fb03710ccd6 - rustc::ty::context::TyCtxt::create_and_enter::h525f6f0ef4f469d3
  39:     0x7fb03704eb88 - rustc_driver::driver::compile_input::h4f47cdbacf41587e
  40:     0x7fb0370f3fdc - rustc_driver::run_compiler_with_pool::hf2761cb646965bbf
  41:     0x7fb03704c814 - rustc_driver::driver::spawn_thread_pool::he9b41f41389dfef1
  42:     0x7fb0370f2ff1 - rustc_driver::run_compiler::h2f161f58bd524a71
  43:     0x7fb03703b0ec - <scoped_tls::ScopedKey<T>>::set::hf16868c69d7a8d53
  44:     0x7fb037077171 - syntax::with_globals::h8dae2372140c50b5
  45:     0x7fb036ce41f9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  46:     0x7fb0370f124c - rustc_driver::run::h26fa391579b13041
  47:     0x7fb0370ff29a - rustc_driver::main::h943dabc10c09630e
  48:     0x55d57d868952 - std::rt::lang_start::{{closure}}::hadd84dae5f71d4e1
  49:     0x7fb036ca46d2 - std::panicking::try::do_call::h3c29175827f8c066
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  50:     0x7fb036ce41f9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  51:     0x7fb036cbaba5 - std::rt::lang_start_internal::h790baabe7ccaf0b4
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  52:     0x55d57d8689b3 - main
  53:     0x7fb0368b411a - __libc_start_main
  54:     0x55d57d868838 - <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (79fcc58b2 2018-09-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `toy_parser`.

To learn more, run the command again with --verbose.

Cargo-Process exited abnormally with code 101 at Sun Sep 23 23:41:56

````

**Comment by Centril** [comment]
@jjpe Could you provide a reproducer for this?

**Comment by jjpe** [comment]
The bug was from a long time ago, 2018. At this point I don't even remember which repo that was in, or which commit it would be.

**Comment by spastorino** [comment]
We were checking this with @pnkfelix and noticed that there's no way for us to reproduce it and also @jjpe doesn't have access to the repo anymore.

Closing as non actionable.
