### ISSUE TITLE
'specified instant was later than self' when compiling libc on aarch64 with rust-nightly

### ISSUE THREAD

**Issue by marce11us** [rust-lang/rust#54588]
compiling libc fails when compiling on aarch64 with rust-nightly. It works with stable, as well as with nightly on x86_64.

```
$ cargo build
   Compiling libc v0.2.43 (/home/marcellus/del/libc)
thread 'main' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (5c875d938 2018-09-24) running on aarch64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `libc`.

To learn more, run the command again with --verbose.

```

## Meta

```
$ rustc --version --verbose
rustc 1.30.0-nightly (5c875d938 2018-09-24)
binary: rustc
commit-hash: 5c875d93855c6d577962b0f74f17374f37b219c9
commit-date: 2018-09-24
host: aarch64-unknown-linux-gnu
release: 1.30.0-nightly
LLVM version: 8.0
```

Backtrace:

```
$ RUST_BACKTRACE=1 cargo build
   Compiling libc v0.2.43 (/home/marcellus/del/libc)
thread 'main' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   6: std::panicking::begin_panic
             at libstd/panicking.rs:411
   7: std::sys::unix::time::inner::Instant::sub_instant::{{closure}}
             at libstd/sys/unix/time.rs:292
   8: std::time::Instant::elapsed
             at libcore/result.rs:774
             at libstd/sys/unix/time.rs:291
             at libstd/time.rs:185
             at libstd/time.rs:250
             at libstd/time.rs:209
   9: rustc::util::profiling::SelfProfiler::end_activity
  10: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  11: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  12: <rustc::hir::check_attr::CheckAttrVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  13: rustc::hir::Crate::visit_all_item_likes
  14: rustc::hir::check_attr::check_crate
  15: rustc::util::common::time
  16: rustc::ty::context::tls::enter_context
  17: <std::thread::local::LocalKey<T>>::with
  18: rustc::ty::context::TyCtxt::create_and_enter
  19: rustc_driver::driver::compile_input
  20: rustc_driver::run_compiler_with_pool
  21: <scoped_tls::ScopedKey<T>>::set
  22: rustc_driver::run_compiler
  23: <scoped_tls::ScopedKey<T>>::set
  24: syntax::with_globals
  25: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  26: rustc_driver::run
  27: rustc_driver::main
  28: std::rt::lang_start::{{closure}}
  29: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  30: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  31: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  32: main
  33: __libc_start_main
             at ../csu/libc-start.c:308
  34: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (5c875d938 2018-09-24) running on aarch64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `libc`.

To learn more, run the command again with --verbose.
```

**Comment by marce11us** [comment]
I updated today to

`rustc 1.30.0-nightly (bb0896af1 2018-09-29)`

and it compiles fine.
