### ISSUE TITLE
1.30.0-beta.7 with LLVM 7 fails debuginfo-gdb tests on all architectures

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#54614]
Failures here: https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=amd64&ver=1.30.0%7Ebeta.7%2Bdfsg1-1%7Eexp3&stamp=1538038525&raw=0

The same tests worked with LLVM 6

**Comment by tromey** [comment]
Most of these will be fixed by #54004.

`debuginfo/c-style-enum-in-composite.rs` says this:
```
// ignore-gdb // Test temporarily ignored due to debuginfo tests being disabled, see PR 47155
```
...but that isn't actually a valid directive as far as I can tell.

**Comment by tromey** [comment]
Perhaps a more targeted fix for the `DW_AT_enum_class` thing is needed for the beta?  I don't know.

**Comment by tromey** [comment]
@infinity0 can you try this again with git master?  I think these were all fixed by #54004.

**Comment by infinity0** [comment]
I backported #54004 [like this](https://salsa.debian.org/rust-team/rust/blob/6f119a4340b15d0acdf52e58a08a613e361765f3/debian/patches/u-debuginfo-gdb-8.2.patch) to 1.31.0 and it seems to be resulting in [segfaults when compiling various LTO related tests](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=amd64&ver=1.31.0%2Bdfsg1-1%7Eexp2&stamp=1544921599&raw=0). I will revert that and try again with 1.32.0 later.

**Comment by infinity0** [comment]
@tromey same result with 1.32.0, e.g. on [i386](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=i386&ver=1.32.0%7Ebeta.2%2Bdfsg1-1%7Eexp1&stamp=1545089675&raw=0)

~~~~
---- [run-pass] run-pass/debuginfo-lto.rs stdout ----
[..]
error: test compilation failed although it shouldn't!
status: signal: 11
[..]
test [run-pass] run-pass/debuginfo-lto.rs ... FAILED
test [run-pass] run-pass/fat-lto.rs ... FAILED
test [run-pass] run-pass/lto-many-codegen-units.rs ... FAILED
test [run-pass] run-pass/lto-still-runs-thread-dtors.rs ... FAILED
test [run-pass] run-pass/panic-runtime/lto-abort.rs ... FAILED
test [run-pass] run-pass/panic-runtime/lto-unwind.rs ... FAILED
test [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs ... FAILED
test [run-pass] run-pass/sse2.rs ... FAILED
test [run-pass] run-pass/stack-probes-lto.rs ... FAILED
~~~~

Is your PR 54004 supposed to be used together with some LLVM patches? We are not using rust's LLVM in Debian but the upstream LLVM.

**Comment by tromey** [comment]
> Is your PR 54004 supposed to be used together with some LLVM patches? We are not using rust's LLVM in Debian but the upstream LLVM.

There were LLVM patches, but they all went in upstream first.  They involved additional APIs, so if your LLVM did not have these changes, then I would expect the build to fail.

Can you get a stack trace at the point of failure?  That might help.

There was also https://github.com/rust-lang/llvm/pull/128 (also upstream).  My recollection is that this bug didn't cause crashes, but you might check that your LLVM has the fix just in case.

**Comment by infinity0** [comment]
Looks like it's segfaulting inside LLVM:

<details>

~~~~
$ rust-gdb -q rustc
Reading symbols from rustc...Reading symbols from /usr/lib/debug/.build-id/cc/2e687974d5efcf7cd07c41b8da67b68dc39332.debug...done.
done.
(gdb) run "src/test/run-pass/fat-lto.rs" "-O" "-Clto=fat"
Starting program: /usr/bin/rustc "src/test/run-pass/fat-lto.rs" "-O" "-Clto=fat"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee1b8700 (LWP 21063)]
[New Thread 0x7fffedfb7700 (LWP 21064)]
[New Thread 0x7fffeddb6700 (LWP 21065)]
[Thread 0x7fffeddb6700 (LWP 21065) exited]
[New Thread 0x7fffedbb5700 (LWP 21066)]
[Thread 0x7fffedbb5700 (LWP 21066) exited]
[New Thread 0x7fffeddb6700 (LWP 21067)]
[New Thread 0x7fffedbb5700 (LWP 21068)]
[Thread 0x7fffeddb6700 (LWP 21067) exited]
[Thread 0x7fffedbb5700 (LWP 21068) exited]
[New Thread 0x7fffedbb5700 (LWP 21069)]

Thread 8 "rustc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffedbb5700 (LWP 21069)]
0x00007ffff2493f69 in llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
(gdb) thread apply all bt

Thread 8 (Thread 0x7fffedbb5700 (LWP 21069)):
#0  0x00007ffff2493f69 in llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#1  0x00007ffff24934ea in llvm::DwarfUnit::getOrCreateTypeDIE(llvm::MDNode const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#2  0x00007ffff249321f in llvm::DwarfUnit::addType(llvm::DIE&, llvm::DIType const*, llvm::dwarf::Attribute) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#3  0x00007ffff24958b7 in llvm::DwarfUnit::constructMemberDIE(llvm::DIE&, llvm::DIDerivedType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#4  0x00007ffff249418a in llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#5  0x00007ffff24934ea in llvm::DwarfUnit::getOrCreateTypeDIE(llvm::MDNode const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#6  0x00007ffff249321f in llvm::DwarfUnit::addType(llvm::DIE&, llvm::DIType const*, llvm::dwarf::Attribute) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#7  0x00007ffff2494c42 in llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DIDerivedType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#8  0x00007ffff24934d7 in llvm::DwarfUnit::getOrCreateTypeDIE(llvm::MDNode const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#9  0x00007ffff249321f in llvm::DwarfUnit::addType(llvm::DIE&, llvm::DIType const*, llvm::dwarf::Attribute) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#10 0x00007ffff2492d59 in llvm::DwarfUnit::constructTemplateTypeParameterDIE(llvm::DIE&, llvm::DITemplateTypeParameter const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#11 0x00007ffff24944aa in llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#12 0x00007ffff24934ea in llvm::DwarfUnit::getOrCreateTypeDIE(llvm::MDNode const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#13 0x00007ffff249321f in llvm::DwarfUnit::addType(llvm::DIE&, llvm::DIType const*, llvm::dwarf::Attribute) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#14 0x00007ffff24958b7 in llvm::DwarfUnit::constructMemberDIE(llvm::DIE&, llvm::DIDerivedType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#15 0x00007ffff249418a in llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#16 0x00007ffff24934ea in llvm::DwarfUnit::getOrCreateTypeDIE(llvm::MDNode const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#17 0x00007ffff249321f in llvm::DwarfUnit::addType(llvm::DIE&, llvm::DIType const*, llvm::dwarf::Attribute) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#18 0x00007ffff24714fd in llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(llvm::DIGlobalVariable const*, llvm::ArrayRef<llvm::DwarfCompileUnit::GlobalExpr>) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#19 0x00007ffff247ba9f in llvm::DwarfDebug::beginModule() () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#20 0x00007ffff2457407 in llvm::AsmPrinter::doInitialization(llvm::Module&) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#21 0x00007ffff1fae8d1 in llvm::FPPassManager::doInitialization(llvm::Module&) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#22 0x00007ffff1faeb31 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#23 0x00007ffff519435f in LLVMRustWriteOutputFile (Target=0x5555560b5aa0, PMR=0x7fffe44b4e20, M=0x555555c86220, Path=<optimized out>, RustFileType=<optimized out>) at /usr/lib/llvm-7/include/llvm/IR/Module.h:877
#24 0x00007ffff50c5e1c in rustc_codegen_llvm::back::write::write_output_file (handler=0x7fffedbb3ff0, target=0x7fffe4475808, pm=0x30, m=0x0, 
    output=<error reading variable: access outside bounds of object referenced via synthetic pointer>, file_type=rustc_codegen_llvm::llvm_::ffi::FileType::ObjectFile) at src/librustc_codegen_llvm/back/write.rs:84
#25 0x00007ffff50c979d in rustc_codegen_llvm::back::write::codegen::{{closure}}::{{closure}} (cpm=0x7fffe44b4e20) at src/librustc_codegen_llvm/back/write.rs:594
#26 rustc_codegen_llvm::back::write::codegen::with_codegen (tm=<optimized out>, llmod=<optimized out>, f=..., no_builtins=<optimized out>) at src/librustc_codegen_llvm/back/write.rs:481
#27 rustc_codegen_llvm::back::write::codegen::{{closure}} () at src/librustc_codegen_llvm/back/write.rs:593
#28 0x00007ffff50c8abf in rustc::util::common::time_ext (what=..., f=..., do_it=<optimized out>, sess=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/librustc/util/common.rs:160
#29 rustc_codegen_llvm::back::write::codegen (cgcx=<optimized out>, diag_handler=<optimized out>, module=..., config=<optimized out>, timeline=<optimized out>) at src/librustc_codegen_llvm/back/write.rs:530
#30 0x00007ffff5087d6a in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::write::WriteBackendMethods>::codegen (cgcx=<optimized out>, diag_handler=0x0, config=<optimized out>, timeline=<optimized out>, 
    module=...) at src/librustc_codegen_llvm/lib.rs:210
#31 rustc_codegen_ssa::back::write::execute_lto_work_item (cgcx=<optimized out>, module_config=0x555555acd7e0, timeline=<optimized out>, module=...) at /usr/src/rustc-1.32.0~beta.2/src/librustc_codegen_ssa/back/write.rs:834
#32 rustc_codegen_ssa::back::write::execute_work_item (cgcx=0x7fffedbb4400, work_item=<unknown type in /usr/lib/debug/.build-id/d9/817e80a0a0d69b28249d54f71b937f409d4865.debug, CU 0x2a0fdd, DIE 0x31c563>, timeline=0x7fffedbb42b0)
    at /usr/src/rustc-1.32.0~beta.2/src/librustc_codegen_ssa/back/write.rs:694
#33 0x00007ffff515f812 in rustc_codegen_ssa::back::write::spawn_work::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/librustc_codegen_ssa/back/write.rs:1526
#34 std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sys_common/backtrace.rs:136
#35 0x00007ffff506c529 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/thread/mod.rs:477
#36 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:319
#37 std::panicking::try::do_call (data=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:310
#38 0x00007ffff7cc937a in __rust_maybe_catch_panic (f=0x7fffe4063400, data=0x7fffe4475808 "\000", data_ptr=0x7fffedbb4790, vtable_ptr=0x7fffedbb4798) at src/libpanic_unwind/lib.rs:102
#39 0x00007ffff505e198 in std::panicking::try (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:289
#40 std::panic::catch_unwind (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:398
#41 std::thread::Builder::spawn_unchecked::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/thread/mod.rs:476
#42 <F as alloc::boxed::FnBox<A>>::call_box (self=0x7fffe3fa8b10, args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/liballoc/boxed.rs:673
#43 0x00007ffff7cb9dae in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hf85a69e57ba810f9 (
    self=..., args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/liballoc/boxed.rs:683
#44 std::sys_common::thread::start_thread (main=0x7fffe011a2e0 "\020\213\372\343\377\177\000") at src/libstd/sys_common/thread.rs:24
#45 0x00007ffff7c8d306 in std::sys::unix::thread::Thread::new::thread_start (main=0x7fffe4475808) at src/libstd/sys/unix/thread.rs:90
#46 0x00007ffff5487fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#47 0x00007ffff7b7288f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffedfb7700 (LWP 21064)):
#0  0x00007ffff548dfec in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff7c9b223 in std::sys::unix::condvar::Condvar::wait (self=0x89fffffbdde8df89, mutex=<optimized out>) at src/libstd/sys/unix/condvar.rs:80
#2  std::sys_common::condvar::Condvar::wait (self=0x89fffffbdde8df89, mutex=<optimized out>) at src/libstd/sys_common/condvar.rs:51
#3  std::sync::condvar::Condvar::wait (self=0x7ffff548e02c <pthread_cond_wait@@GLIBC_2.3.2+572>, guard=...) at src/libstd/sync/condvar.rs:214
#4  std::thread::park () at src/libstd/thread/mod.rs:885
#5  0x00007ffff7c88fd2 in std::sync::mpsc::blocking::WaitToken::wait (self=...) at src/libstd/sync/mpsc/blocking.rs:81
#6  0x00007ffff508fc1b in <std::sync::mpsc::shared::Packet<T>>::recv (self=0x555555ad0280, deadline=<unknown type in /usr/lib/debug/.build-id/d9/817e80a0a0d69b28249d54f71b937f409d4865.debug, CU 0x2a0fdd, DIE 0x329d05>)
    at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/shared.rs:239
#7  0x00007ffff50792ab in <std::sync::mpsc::Receiver<T>>::recv (self=0x7fffedfb6348) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/mod.rs:1219
#8  0x00007ffff515cfd6 in rustc_codegen_ssa::back::write::start_executing_work::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/librustc_codegen_ssa/back/write.rs:1287
#9  std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sys_common/backtrace.rs:136
#10 0x00007ffff506c4de in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/thread/mod.rs:477
#11 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:319
#12 std::panicking::try::do_call (data=0x7fffedfb66a0 "\000") at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:310
#13 0x00007ffff7cc937a in __rust_maybe_catch_panic (f=0xfffffffffffffe00, data=0x555555efe05c "\000", data_ptr=0x7fffedfb6690, vtable_ptr=0x7fffedfb6698) at src/libpanic_unwind/lib.rs:102
#14 0x00007ffff505df99 in std::panicking::try (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:289
#15 std::panic::catch_unwind (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:398
#16 std::thread::Builder::spawn_unchecked::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/thread/mod.rs:476
#17 <F as alloc::boxed::FnBox<A>>::call_box (self=0x555555be19d0, args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/liballoc/boxed.rs:673
#18 0x00007ffff7cb9dae in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hf85a69e57ba810f9 (
    self=..., args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/liballoc/boxed.rs:683
#19 std::sys_common::thread::start_thread (main=0x555555e91950 "\320\031\276UUU\000") at src/libstd/sys_common/thread.rs:24
#20 0x00007ffff7c8d306 in std::sys::unix::thread::Thread::new::thread_start (main=0x555555efe05c) at src/libstd/sys/unix/thread.rs:90
#21 0x00007ffff5487fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#22 0x00007ffff7b7288f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffee1b8700 (LWP 21063)):
#0  0x00007ffff548dfec in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff7c9b223 in std::sys::unix::condvar::Condvar::wait (self=0x89fffffbdde8df89, mutex=<optimized out>) at src/libstd/sys/unix/condvar.rs:80
#2  std::sys_common::condvar::Condvar::wait (self=0x89fffffbdde8df89, mutex=<optimized out>) at src/libstd/sys_common/condvar.rs:51
#3  std::sync::condvar::Condvar::wait (self=0x7ffff548e02c <pthread_cond_wait@@GLIBC_2.3.2+572>, guard=...) at src/libstd/sync/condvar.rs:214
#4  std::thread::park () at src/libstd/thread/mod.rs:885
#5  0x00007ffff7c88fd2 in std::sync::mpsc::blocking::WaitToken::wait (self=...) at src/libstd/sync/mpsc/blocking.rs:81
#6  0x00007ffff6553eec in <std::sync::mpsc::stream::Packet<T>>::recv (self=0x7fffe0001080, deadline=<unknown type in /usr/lib/debug/.build-id/5d/1efa2f574559af1b4477d1f4e507b1a5e7d551.debug, CU 0x2a9b824, DIE 0x2a9e0c2>)
    at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/stream.rs:210
#7  0x00007ffff655a7f9 in <std::sync::mpsc::Receiver<T>>::recv (self=0x7fffee1b78f0) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/mod.rs:1211
#8  <std::sync::mpsc::IntoIter<T> as core::iter::iterator::Iterator>::next (self=0x7fffee1b78f0) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/mod.rs:1618
#9  0x00007ffff655683d in jobserver::imp::spawn_helper::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/vendor/jobserver/src/lib.rs:606
#10 std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sys_common/backtrace.rs:136
#11 0x00007ffff6554a3e in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/thread/mod.rs:477
#12 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:319
#13 std::panicking::try::do_call (data=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:310
#14 0x00007ffff7cc937a in __rust_maybe_catch_panic (f=0xfffffffffffffe00, data=0x555555efe1fc "\000", data_ptr=0x7fffee1b7a20, vtable_ptr=0x7fffee1b7a28) at src/libpanic_unwind/lib.rs:102
#15 0x00007ffff655572f in std::panicking::try (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:289
#16 std::panic::catch_unwind (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:398
#17 std::thread::Builder::spawn_unchecked::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/thread/mod.rs:476
#18 <F as alloc::boxed::FnBox<A>>::call_box (self=0x555555e8f600, args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/liballoc/boxed.rs:673
#19 0x00007ffff7cb9dae in _$LT$alloc..boxed..Box$LT$$LP$dyn$u20$alloc..boxed..FnBox$LT$A$C$$u20$Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hf85a69e57ba810f9 (
    self=..., args=<optimized out>) at /usr/src/rustc-1.32.0~beta.2/src/liballoc/boxed.rs:683
#20 std::sys_common::thread::start_thread (main=0x555555e915c0 "\000") at src/libstd/sys_common/thread.rs:24
#21 0x00007ffff7c8d306 in std::sys::unix::thread::Thread::new::thread_start (main=0x555555efe1fc) at src/libstd/sys/unix/thread.rs:90
#22 0x00007ffff5487fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#23 0x00007ffff7b7288f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff52231c0 (LWP 20918)):
#0  0x00007ffff548dfec in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff7c9b223 in std::sys::unix::condvar::Condvar::wait (self=0x89fffffbdde8df89, mutex=<optimized out>) at src/libstd/sys/unix/condvar.rs:80
#2  std::sys_common::condvar::Condvar::wait (self=0x89fffffbdde8df89, mutex=<optimized out>) at src/libstd/sys_common/condvar.rs:51
#3  std::sync::condvar::Condvar::wait (self=0x7ffff548e02c <pthread_cond_wait@@GLIBC_2.3.2+572>, guard=...) at src/libstd/sync/condvar.rs:214
#4  std::thread::park () at src/libstd/thread/mod.rs:885
#5  0x00007ffff7c88fd2 in std::sync::mpsc::blocking::WaitToken::wait (self=...) at src/libstd/sync/mpsc/blocking.rs:81
#6  0x00007ffff4f598da in <std::sync::mpsc::shared::Packet<T>>::recv (self=0x555555e91440, deadline=<unknown type in /usr/lib/debug/.build-id/f5/927bde91e6a320aae8cf747aeb6c5f5295b6ef.debug, CU 0x37e216, DIE 0x37e7c4>)
    at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/shared.rs:239
#7  0x00007ffff4f52094 in <std::sync::mpsc::Receiver<T>>::recv (self=0x7fffffff5c18) at /usr/src/rustc-1.32.0~beta.2/src/libstd/sync/mpsc/mod.rs:1219
#8  0x00007ffff4f565c5 in rustc_codegen_ssa::back::write::SharedEmitterMain::check (self=0x7fffffff5c18, sess=0x7fffffff8850, blocking=true) at src/librustc_codegen_ssa/back/write.rs:1623
#9  0x00007ffff509d247 in <rustc_codegen_ssa::back::write::OngoingCodegen<B>>::join (self=..., sess=0x7fffffff8850) at /usr/src/rustc-1.32.0~beta.2/src/librustc_codegen_ssa/back/write.rs:1693
#10 0x00007ffff50f8e61 in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::join_codegen_and_link (self=<optimized out>, ongoing_codegen=..., sess=0x7fffffff8850, 
    dep_graph=0x7fffffff6508, outputs=<optimized out>) at src/librustc_codegen_llvm/lib.rs:313
#11 0x00007ffff7dd7303 in rustc_driver::driver::compile_input (codegen_backend=..., sess=0x7ffff548dfec <pthread_cond_wait@@GLIBC_2.3.2+508>, cstore=<optimized out>, input_path=<optimized out>, input=<optimized out>, 
    outdir=<optimized out>, output=<optimized out>, addl_plugins=<optimized out>, control=<optimized out>) at src/librustc_driver/driver.rs:351
#12 0x00007ffff7eafbf0 in rustc_driver::run_compiler_with_pool (matches=..., sopts=..., cfg=..., callbacks=..., 
    file_loader=<unknown type in /usr/lib/debug/.build-id/a5/4f3981a08d34d18d0e17635c6dd36038586c32.debug, CU 0x78f432, DIE 0x79be1e>, 
    emitter_dest=<unknown type in /usr/lib/debug/.build-id/a5/4f3981a08d34d18d0e17635c6dd36038586c32.debug, CU 0x78f432, DIE 0x79be2d>) at src/librustc_driver/lib.rs:552
#13 0x00007ffff7ddf9b6 in rustc_driver::run_compiler::{{closure}} (sopts=...) at src/librustc_driver/lib.rs:474
#14 rustc_driver::driver::spawn_thread_pool::{{closure}} () at src/librustc_driver/driver.rs:76
#15 <scoped_tls::ScopedKey<T>>::set (self=<optimized out>, t=<optimized out>, f=...) at /usr/src/rustc-1.32.0~beta.2/vendor/scoped-tls/src/lib.rs:155
#16 0x00007ffff7eaebfb in rustc_driver::driver::spawn_thread_pool (f=..., opts=...) at src/librustc_driver/driver.rs:75
#17 rustc_driver::run_compiler (args=..., callbacks=..., file_loader=<unknown type in /usr/lib/debug/.build-id/a5/4f3981a08d34d18d0e17635c6dd36038586c32.debug, CU 0x78f432, DIE 0x79ba4a>, 
    emitter_dest=<unknown type in /usr/lib/debug/.build-id/a5/4f3981a08d34d18d0e17635c6dd36038586c32.debug, CU 0x78f432, DIE 0x79ba59>) at src/librustc_driver/lib.rs:473
#18 0x00007ffff7dfceaf in rustc_driver::main::{{closure}} () at src/librustc_driver/lib.rs:1726
#19 rustc_driver::run::{{closure}}::{{closure}} () at src/librustc_driver/lib.rs:189
#20 <scoped_tls::ScopedKey<T>>::set (self=<optimized out>, t=<optimized out>, f=...) at /usr/src/rustc-1.32.0~beta.2/vendor/scoped-tls/src/lib.rs:155
#21 syntax::with_globals::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libsyntax/lib.rs:123
#22 <scoped_tls::ScopedKey<T>>::set (self=<optimized out>, t=0x0, f=...) at /usr/src/rustc-1.32.0~beta.2/vendor/scoped-tls/src/lib.rs:155
#23 syntax::with_globals (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libsyntax/lib.rs:122
#24 rustc_driver::run::{{closure}} () at src/librustc_driver/lib.rs:188
#25 rustc_driver::monitor::{{closure}} () at src/librustc_driver/lib.rs:1642
#26 0x00007ffff7cc937a in __rust_maybe_catch_panic (f=0xfffffffffffffe00, data=0x555555559a98 "\000", data_ptr=0x7fffffffda40, vtable_ptr=0x7fffffffdaf0) at src/libpanic_unwind/lib.rs:102
#27 0x00007ffff7eaccec in std::panicking::try (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panicking.rs:289
#28 std::panic::catch_unwind (f=...) at /usr/src/rustc-1.32.0~beta.2/src/libstd/panic.rs:398
#29 rustc_driver::in_named_rustc_thread (name=..., f=...) at src/librustc_driver/lib.rs:1556
#30 rustc_driver::in_rustc_thread (f=...) at src/librustc_driver/lib.rs:1567
#31 rustc_driver::monitor (f=...) at src/librustc_driver/lib.rs:1641
#32 rustc_driver::run (run_compiler=...) at src/librustc_driver/lib.rs:187
#33 0x00007ffff7eba80c in rustc_driver::main () at src/librustc_driver/lib.rs:1719
#34 0x0000555555555133 in std::rt::lang_start::{{closure}} () at /usr/src/rustc-1.32.0~beta.2/src/libstd/rt.rs:74
#35 0x00007ffff7c89bb3 in std::rt::lang_start_internal::{{closure}} () at src/libstd/rt.rs:59
#36 std::panicking::try::do_call (data=0x7fffffffdce0 "\000") at src/libstd/panicking.rs:310
#37 0x00007ffff7cc937a in __rust_maybe_catch_panic (f=0xfffffffffffffe00, data=0x555555559a98 "\000", data_ptr=0x7fffffffdcf8, vtable_ptr=0x7fffffffdcb8) at src/libpanic_unwind/lib.rs:102
#38 0x00007ffff7c9eb9b in std::panicking::try (f=...) at src/libstd/panicking.rs:289
#39 std::panic::catch_unwind (f=...) at src/libstd/panic.rs:398
#40 std::rt::lang_start_internal (main=..., argc=4, argv=<optimized out>) at src/libstd/rt.rs:58
#41 0x000055555555519b in main ()
#42 0x00007ffff7a9d09b in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#43 0x000055555555506a in _start ()
~~~~

</details>

We don't have debugging symbols for this particular build of LLVM unfortunately but I've asked the maintainer if he could supply them for the next b uild.

**Comment by infinity0** [comment]
FWIW the versions are:

~~~~
$ apt-cache policy rustc libllvm7
rustc:
  Installed: 1.32.0~beta.2+dfsg1-1~exp1
[..]
libllvm7:
  Installed: 1:7.0.1-1
[..]
~~~~

**Comment by tromey** [comment]
That crash seems familiar.  Maybe it was the patch I mentioned earlier.  I looked at upstream and apparently that patch did not make it to the 7.0 branch :-(

**Comment by infinity0** [comment]
Yes, looks like cherry-picking that patch into our LLVM fixed the specific segfault I pasted just above. I will re-run the whole testsuite again and close this if it's all OK.

**Comment by infinity0** [comment]
Everything looks good, so closing.
