### ISSUE TITLE
ICE on '_ in impl generics

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#54689]
edition: 2018
rustc 1.30.0-nightly (bb0896af1 2018-09-29)

```rust
struct S;
impl<'_> S {}
```

```console
thread 'main' panicked at 'assertion failed: self.is_collecting_in_band_lifetimes', librustc/hir/lowering.rs:778:9
stack backtrace:                                                               
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                  
   1: std::sys_common::backtrace::print                                        
             at libstd/sys_common/backtrace.rs:71                              
             at libstd/sys_common/backtrace.rs:59                              
   2: std::panicking::default_hook::{{closure}}                                
             at libstd/panicking.rs:211                                        
   3: std::panicking::default_hook                                             
             at libstd/panicking.rs:227                                        
   4: rustc::util::common::panic_hook                                          
   5: std::panicking::rust_panic_with_hook                                     
             at libstd/panicking.rs:481                                        
   6: std::panicking::begin_panic                                              
   7: rustc::hir::lowering::LoweringContext::lower_lifetime                    
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
   9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter          
  10: rustc::hir::lowering::LoweringContext::lower_generics                    
  11: rustc::hir::lowering::LoweringContext::lower_item                        
  12: <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item
  13: rustc::hir::lowering::lower_crate                                        
  14: rustc::util::common::time                                                
  15: rustc_driver::driver::phase_2_configure_and_expand                       
  16: rustc_driver::driver::compile_input                                      
  17: rustc_driver::run_compiler_with_pool                                     
  18: rustc_driver::driver::spawn_thread_pool                                  
  19: rustc_driver::run_compiler                                               
  20: syntax::with_globals                                                     
  21: __rust_maybe_catch_panic                                                 
             at libpanic_unwind/lib.rs:102                                     
  22: rustc_driver::run                                                        
  23: rustc_driver::main                                                       
  24: std::rt::lang_start::{{closure}}                                         
  25: std::panicking::try::do_call                                             
             at libstd/rt.rs:59                                                
             at libstd/panicking.rs:310                                        
  26: __rust_maybe_catch_panic                                                 
             at libpanic_unwind/lib.rs:102                                     
  27: std::rt::lang_start_internal                                             
             at libstd/panicking.rs:289                                        
             at libstd/panic.rs:392                                            
             at libstd/rt.rs:58                                                
  28: main                                                                     
  29: __libc_start_main                                                        
  30: <unknown>                                                                
query stack during panic:                                                      
end of query stack                                                             
                                                                               
error: internal compiler error: unexpected panic
```

**Comment by zackmdavis** [comment]
Duplicate of #52098.

**Comment by dtolnay** [comment]
Thanks! Didn't find it with ["is_collecting_in_band_lifetimes"](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+is_collecting_in_band_lifetimes).
