### ISSUE TITLE
'internal error: entered unreachable code', librustc_target/spec/mod.rs:1204:57

### ISSUE THREAD

**Issue by twirrim** [rust-lang/rust#54897]
This could be down to something with lolbench, but when compiling lolbench on Raspberry Pi3 running Ubuntu 18.04 armv7, I ran in to an issue compiling "proc-macro-hack-impl"

I tried this code:

Git clone'd lolbench.  This commit is at HEAD:
https://github.com/anp/lolbench/tree/e9c210057229bb41eb19b335ff314b54155693c4

ran cargo test-core

Eventually it panics:
```
thread 'main' panicked at 'internal error: entered unreachable code', librustc_target/spec/mod.rs:1204:57
```

I tried starting a new cargo space and pulling in just proc-macro-hack-impl v0.4.1 and building that, but it builds fine at both normal and release variants.  I'm not sure what lolbench is doing to result in the failure.

I expected to see this happen: lolbench do its thing.

Instead, this happened:

```
   Compiling proc-macro-hack-impl v0.4.1
thread 'main' panicked at 'internal error: entered unreachable code', librustc_target/spec/mod.rs:1204:57
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0 (aa3ca1994 2018-09-11) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C prefer-dynamic -C opt-level=1 -C debuginfo=1 -C debug-assertions=on --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `proc-macro-hack-impl`.
```

## Meta

`rustc --version --verbose`:

```
rustc 1.29.0 (aa3ca1994 2018-09-11)
binary: rustc
commit-hash: aa3ca1994904f2e056679fce1f185db8c7ed2703
commit-date: 2018-09-11
host: armv7-unknown-linux-gnueabihf
release: 1.29.0
LLVM version: 7.0
```

Backtrace:
```
ubuntu@ubuntu:~/lolbench$ RUST_BACKTRACE=1 cargo test-core -j 1
   Compiling proc-macro-hack-impl v0.4.1
thread 'main' panicked at 'internal error: entered unreachable code', librustc_target/spec/mod.rs:1204:57
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::begin_panic
   7: serialize::serialize::Decoder::read_enum
   8: <rustc_metadata::schema::CrateRoot as serialize::serialize::Decodable>::decode::{{closure}}
   9: rustc_metadata::decoder::<impl rustc_metadata::schema::Lazy<T>>::decode
  10: rustc_metadata::decoder::<impl rustc_metadata::cstore::MetadataBlob>::get_root
  11: rustc_metadata::locator::Context::extract_one
  12: rustc_metadata::locator::Context::find_library_crate
  13: rustc_metadata::locator::Context::maybe_load_library_crate
  14: rustc_metadata::creader::CrateLoader::load
  15: rustc_metadata::creader::CrateLoader::resolve_crate
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  18: rustc_metadata::creader::CrateLoader::resolve_crate
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  20: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  21: rustc_metadata::creader::CrateLoader::resolve_crate
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  24: rustc_metadata::creader::CrateLoader::resolve_crate
  25: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  26: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  27: rustc_metadata::creader::CrateLoader::resolve_crate
  28: <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::process_extern_crate
  29: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::build_reduced_graph_for_item
  30: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  31: syntax::visit::walk_item
  32: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  33: syntax::ext::expand::AstFragment::visit_with
  34: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_ast_fragment_with_placeholders
  35: syntax::ext::expand::MacroExpander::collect_invocations
  36: syntax::ext::expand::MacroExpander::expand_fragment
  37: syntax::ext::expand::MacroExpander::expand_crate
  38: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  39: rustc::util::common::time
  40: rustc_driver::driver::phase_2_configure_and_expand
  41: rustc_driver::driver::compile_input
  42: rustc_driver::run_compiler_with_pool
  43: <scoped_tls::ScopedKey<T>>::set
  44: <scoped_tls::ScopedKey<T>>::set
  45: syntax::with_globals
  46: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  47: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  48: rustc_driver::run
  49: rustc_driver::main
  50: std::rt::lang_start::{{closure}}
  51: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  52: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  53: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  54: main
  55: __libc_start_main
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0 (aa3ca1994 2018-09-11) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C prefer-dynamic -C opt-level=1 -C debuginfo=1 -C debug-assertions=on --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `proc-macro-hack-impl`.

To learn more, run the command again with --verbose.
```

**Comment by Centril** [comment]
@twirrim Could you check whether this reproduces with a current nightly? Also, could reduce this to a minimal example? cc @petrochenkov
