### ISSUE TITLE
rustc segfaults when compiling on release

### ISSUE THREAD

**Issue by fulmicoton** [rust-lang/rust#55068]
When compiling `tantivy-cli` (version 0.7) on a ARMv7 on linux and for the default target (stable-armv7-unknown-linux-gnueabihf) I get a segfault.

```rust
     Running `rustc --crate-name tantivy /home/fulmicoton/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.7.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="atomicwrites"' --cfg 'feature="default"' --cfg 'feature="fail"' --cfg 'feature="fst"' --cfg 'feature="mmap"' --cfg 'feature="no_fail"' -C metadata=d25a6e98440c62af -C extra-filename=-d25a6e98440c62af --out-dir /home/fulmicoton/tantivy-cli/target/release/deps -L dependency=/home/fulmicoton/tantivy-cli/target/release/deps --extern atomicwrites=/home/fulmicoton/tantivy-cli/target/release/deps/libatomicwrites-fce46e63738aa183.rlib --extern base64=/home/fulmicoton/tantivy-cli/target/release/deps/libbase64-f98a201d1596be7a.rlib --extern bit_set=/home/fulmicoton/tantivy-cli/target/release/deps/libbit_set-2a4f07d0f5d0ce60.rlib --extern bitpacking=/home/fulmicoton/tantivy-cli/target/release/deps/libbitpacking-0a442b5a4ed94920.rlib --extern byteorder=/home/fulmicoton/tantivy-cli/target/release/deps/libbyteorder-20a705f1c3cf9d5b.rlib --extern census=/home/fulmicoton/tantivy-cli/target/release/deps/libcensus-51540c7c8476b422.rlib --extern combine=/home/fulmicoton/tantivy-cli/target/release/deps/libcombine-7984627c4cb85f3c.rlib --extern crossbeam=/home/fulmicoton/tantivy-cli/target/release/deps/libcrossbeam-cc5c25c3ec786bd3.rlib --extern crossbeam_channel=/home/fulmicoton/tantivy-cli/target/release/deps/libcrossbeam_channel-985f8323105e65b7.rlib --extern downcast=/home/fulmicoton/tantivy-cli/target/release/deps/libdowncast-01f2a97a7c46e30a.rlib --extern fail=/home/fulmicoton/tantivy-cli/target/release/deps/libfail-fbe792fd0fe1b495.rlib --extern failure=/home/fulmicoton/tantivy-cli/target/release/deps/libfailure-d57102ea71ef774e.rlib --extern fnv=/home/fulmicoton/tantivy-cli/target/release/deps/libfnv-9de9b309c71d9aa9.rlib --extern fst=/home/fulmicoton/tantivy-cli/target/release/deps/libfst-a67597a5b879eb0f.rlib --extern fst_regex=/home/fulmicoton/tantivy-cli/target/release/deps/libfst_regex-252b7a802eb733bd.rlib --extern futures_cpupool=/home/fulmicoton/tantivy-cli/target/release/deps/libfutures_cpupool-fb1ef65cc9ade2ac.rlib --extern futures=/home/fulmicoton/tantivy-cli/target/release/deps/libfutures-51a3f490184862d6.rlib --extern htmlescape=/home/fulmicoton/tantivy-cli/target/release/deps/libhtmlescape-5427adf1a1b456a1.rlib --extern itertools=/home/fulmicoton/tantivy-cli/target/release/deps/libitertools-6719e83ee1ae24ee.rlib --extern lazy_static=/home/fulmicoton/tantivy-cli/target/release/deps/liblazy_static-ab1d4bba080234a1.rlib --extern levenshtein_automata=/home/fulmicoton/tantivy-cli/target/release/deps/liblevenshtein_automata-3860633b8cb7d47c.rlib --extern log=/home/fulmicoton/tantivy-cli/target/release/deps/liblog-9b12357f1aa25994.rlib --extern matches=/home/fulmicoton/tantivy-cli/target/release/deps/libmatches-35ccf9e113cc4d5f.rlib --extern num_cpus=/home/fulmicoton/tantivy-cli/target/release/deps/libnum_cpus-d37020bfff920810.rlib --extern owned_read=/home/fulmicoton/tantivy-cli/target/release/deps/libowned_read-766ff4dc896229a6.rlib --extern owning_ref=/home/fulmicoton/tantivy-cli/target/release/deps/libowning_ref-53bd3be7552b7105.rlib --extern regex=/home/fulmicoton/tantivy-cli/target/release/deps/libregex-12aacd86feeb8e41.rlib --extern rust_stemmers=/home/fulmicoton/tantivy-cli/target/release/deps/librust_stemmers-0b9931c65fedda11.rlib --extern serde=/home/fulmicoton/tantivy-cli/target/release/deps/libserde-77233942176769c6.rlib --extern serde_derive=/home/fulmicoton/tantivy-cli/target/release/deps/libserde_derive-7716c330b6339791.so --extern serde_json=/home/fulmicoton/tantivy-cli/target/release/deps/libserde_json-186a8fb7f63e9fe4.rlib --extern snap=/home/fulmicoton/tantivy-cli/target/release/deps/libsnap-7a9787219f00dfa3.rlib --extern stable_deref_trait=/home/fulmicoton/tantivy-cli/target/release/deps/libstable_deref_trait-a89d3eee24b53f9b.rlib --extern tempdir=/home/fulmicoton/tantivy-cli/target/release/deps/libtempdir-848ea86628036f3c.rlib --extern tempfile=/home/fulmicoton/tantivy-cli/target/release/deps/libtempfile-0abedeed6134d4f9.rlib --extern uuid=/home/fulmicoton/tantivy-cli/target/release/deps/libuuid-21e48c51d05b9c29.rlib --cap-lints allow -C target-cpu=native -L native=/home/fulmicoton/tantivy-cli/target/release/build/backtrace-sys-52bf4ffcaa7390b0/out`
error: Could not compile `tantivy`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tantivy /home/fulmicoton/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.7.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="atomicwrites"' --cfg 'feature="default"' --cfg 'feature="fail"' --cfg 'feature="fst"' --cfg 'feature="mmap"' --cfg 'feature="no_fail"' -C metadata=d25a6e98440c62af -C extra-filename=-d25a6e98440c62af --out-dir /home/fulmicoton/tantivy-cli/target/release/deps -L dependency=/home/fulmicoton/tantivy-cli/target/release/deps --extern atomicwrites=/home/fulmicoton/tantivy-cli/target/release/deps/libatomicwrites-fce46e63738aa183.rlib --extern base64=/home/fulmicoton/tantivy-cli/target/release/deps/libbase64-f98a201d1596be7a.rlib --extern bit_set=/home/fulmicoton/tantivy-cli/target/release/deps/libbit_set-2a4f07d0f5d0ce60.rlib --extern bitpacking=/home/fulmicoton/tantivy-cli/target/release/deps/libbitpacking-0a442b5a4ed94920.rlib --extern byteorder=/home/fulmicoton/tantivy-cli/target/release/deps/libbyteorder-20a705f1c3cf9d5b.rlib --extern census=/home/fulmicoton/tantivy-cli/target/release/deps/libcensus-51540c7c8476b422.rlib --extern combine=/home/fulmicoton/tantivy-cli/target/release/deps/libcombine-7984627c4cb85f3c.rlib --extern crossbeam=/home/fulmicoton/tantivy-cli/target/release/deps/libcrossbeam-cc5c25c3ec786bd3.rlib --extern crossbeam_channel=/home/fulmicoton/tantivy-cli/target/release/deps/libcrossbeam_channel-985f8323105e65b7.rlib --extern downcast=/home/fulmicoton/tantivy-cli/target/release/deps/libdowncast-01f2a97a7c46e30a.rlib --extern fail=/home/fulmicoton/tantivy-cli/target/release/deps/libfail-fbe792fd0fe1b495.rlib --extern failure=/home/fulmicoton/tantivy-cli/target/release/deps/libfailure-d57102ea71ef774e.rlib --extern fnv=/home/fulmicoton/tantivy-cli/target/release/deps/libfnv-9de9b309c71d9aa9.rlib --extern fst=/home/fulmicoton/tantivy-cli/target/release/deps/libfst-a67597a5b879eb0f.rlib --extern fst_regex=/home/fulmicoton/tantivy-cli/target/release/deps/libfst_regex-252b7a802eb733bd.rlib --extern futures_cpupool=/home/fulmicoton/tantivy-cli/target/release/deps/libfutures_cpupool-fb1ef65cc9ade2ac.rlib --extern futures=/home/fulmicoton/tantivy-cli/target/release/deps/libfutures-51a3f490184862d6.rlib --extern htmlescape=/home/fulmicoton/tantivy-cli/target/release/deps/libhtmlescape-5427adf1a1b456a1.rlib --extern itertools=/home/fulmicoton/tantivy-cli/target/release/deps/libitertools-6719e83ee1ae24ee.rlib --extern lazy_static=/home/fulmicoton/tantivy-cli/target/release/deps/liblazy_static-ab1d4bba080234a1.rlib --extern levenshtein_automata=/home/fulmicoton/tantivy-cli/target/release/deps/liblevenshtein_automata-3860633b8cb7d47c.rlib --extern log=/home/fulmicoton/tantivy-cli/target/release/deps/liblog-9b12357f1aa25994.rlib --extern matches=/home/fulmicoton/tantivy-cli/target/release/deps/libmatches-35ccf9e113cc4d5f.rlib --extern num_cpus=/home/fulmicoton/tantivy-cli/target/release/deps/libnum_cpus-d37020bfff920810.rlib --extern owned_read=/home/fulmicoton/tantivy-cli/target/release/deps/libowned_read-766ff4dc896229a6.rlib --extern owning_ref=/home/fulmicoton/tantivy-cli/target/release/deps/libowning_ref-53bd3be7552b7105.rlib --extern regex=/home/fulmicoton/tantivy-cli/target/release/deps/libregex-12aacd86feeb8e41.rlib --extern rust_stemmers=/home/fulmicoton/tantivy-cli/target/release/deps/librust_stemmers-0b9931c65fedda11.rlib --extern serde=/home/fulmicoton/tantivy-cli/target/release/deps/libserde-77233942176769c6.rlib --extern serde_derive=/home/fulmicoton/tantivy-cli/target/release/deps/libserde_derive-7716c330b6339791.so --extern serde_json=/home/fulmicoton/tantivy-cli/target/release/deps/libserde_json-186a8fb7f63e9fe4.rlib --extern snap=/home/fulmicoton/tantivy-cli/target/release/deps/libsnap-7a9787219f00dfa3.rlib --extern stable_deref_trait=/home/fulmicoton/tantivy-cli/target/release/deps/libstable_deref_trait-a89d3eee24b53f9b.rlib --extern tempdir=/home/fulmicoton/tantivy-cli/target/release/deps/libtempdir-848ea86628036f3c.rlib --extern tempfile=/home/fulmicoton/tantivy-cli/target/release/deps/libtempfile-0abedeed6134d4f9.rlib --extern uuid=/home/fulmicoton/tantivy-cli/target/release/deps/libuuid-21e48c51d05b9c29.rlib --cap-lints allow -C target-cpu=native -L native=/home/fulmicoton/tantivy-cli/target/release/build/backtrace-sys-52bf4ffcaa7390b0/out` (signal: 11, SIGSEGV: invalid memory reference)
```

Without `--release` compilation finishes  ok.

rustc 1.29.2 (17a9dc751 2018-10-05)

**Comment by Centril** [comment]
Labeled as a soundness hole in the interim due to the segfault but it might not be a soundness issue depending on details.

@fulmicoton could you try to minify the input given to rustc?

**Comment by fulmicoton** [comment]
Unfortunately `tantivy` is quite bit and compilling is very slow. I won't have time to do that any time soon.

**Comment by Centril** [comment]
@fulmicoton alright; thanks for filing the issue!

**Comment by oli-obk** [comment]
A backtrace with gdb would be enormously helpful in tracking this down.

Do our nightlies have llvm assertions enabled? If not, we'll probably hit one when compiling with a rustc built with llvm assertions

**Comment by nikic** [comment]
`cargo +431e0ab62f7730f11db693c23f48403e4c719f82-alt build --release` (recent master commit with LLVM assertions) on `x86_64-unknown-linux-gnu` ran through cleanly for me.

**Comment by nikic** [comment]
I was able to reproduce with `--release` after dropping the `debug = true` line from Cargo.toml. Here's a backtrace (segfault, not assertion failure):

```
#0  0x00007fffee33d626 in llvm::ValueHandleBase::AddToExistingUseList(llvm::ValueHandleBase**) ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#1  0x00007fffecf8bc99 in llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::DFSVisitChildren() ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#2  0x00007fffecf8b0e8 in llvm::scc_iterator<llvm::CallGraph*, llvm::GraphTraits<llvm::CallGraph*> >::GetNextSCC() ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#3  0x00007fffedf31046 in (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#4  0x00007fffee2f1df0 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#5  0x00007fffee24f17b in LLVMRunPassManager ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
#6  0x00007fffec5a7da6 in rustc_codegen_llvm::back::write::execute_work_item ()
   from /home/nikic/.rustup/toolchains/1ecf6929dc3b309cdfcb7239260777dab38242b9-alt/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so
```

This is with the 2018-07-16 nightly, I couldn't reproduce with a recent master commit. However the issue mentions that the segfault doesn't always happen.

**Comment by nikic** [comment]
So I was able to reproduce this problem with 1.29.2, but not with 1.30.1 and also ran the upcoming 1.31.0 multiple times in case it's intermittent. Looks to me like *something* fixed this between 1.29 and 1.30, but I don't think it's worthwhile to investigate further.
