### ISSUE TITLE
ICE: inconsistent resolution for a macro

### ISSUE THREAD

**Issue by mandeepbrar** [rust-lang/rust#55220]
compiler panics

```
thread 'main' panicked at 'librustc_resolve/macros.rs:880: inconsistent resolution for a macro', librustc/util/bug.rs:47:26
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::begin_panic
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   8: rustc::ty::context::tls::with_opt::{{closure}}
   9: rustc::ty::context::tls::with_context_opt
  10: rustc::ty::context::tls::with_opt
  11: rustc::util::bug::opt_span_bug_fmt
  12: rustc::util::bug::span_bug_fmt
  13: rustc_resolve::macros::<impl rustc_resolve::Resolver<'a, 'cl>>::finalize_current_module_macro_resolutions
  14: rustc_resolve::Resolver::resolve_crate
  15: rustc::util::common::time
  16: rustc_driver::driver::phase_2_configure_and_expand
  17: rustc_driver::driver::compile_input
  18: rustc_driver::run_compiler_with_pool
  19: rustc_driver::driver::spawn_thread_pool
  20: rustc_driver::run_compiler
  21: <scoped_tls::ScopedKey<T>>::set
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  24: rustc_driver::run
  25: rustc_driver::main
  26: std::rt::lang_start::{{closure}}
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  28: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  29: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  30: main
  31: __libc_start_main
  32: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (78ff609d7 2018-10-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by petrochenkov** [comment]
@mandeep 
Does this issue still reproduce? If yes, then could you provide code that can be used for reproducing it?

**Comment by petrochenkov** [comment]
The issue is from Oct 20, 2018, multiple cases of "inconsistent resolution for a macro" were addressed since then and one remaining case has its own issue assigned to me.
So, if reproduction doesn't appear in some time, this issue needs to be closed.

**Comment by petrochenkov** [comment]
Closing in accordance with the previous comment.
