### ISSUE TITLE
ICE when checking hyper: HirIdValidator

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#55376]
````
git clone https://github.com/hyperium/hyper 
cd hyper
git checkout 576addd531ec6a6b8d62fbf16411fad7dd475421
cargo +master check
````

````
    Checking hyper v0.12.12 (/tmp/hyper)
thread 'main' panicked at 'librustc/hir/map/hir_id_validator.rs:31:
HirIdValidator: The recorded owner of path segment super (id=36924) is ::server[0]::conn[0]::{{?}}[34] instead of ::server[0]::conn[0]::{{?}}[34]::{{?}}[0]
HirIdValidator: Same HirId ::server[0]::conn[0]::{{?}}[34]::{{?}}[0]/2 assigned for nodes path segment super (id=36924) and path segment spawn_all (id=89958)', librustc/util/bug.rs:47:26
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::begin_panic
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   8: rustc::ty::context::tls::with_opt::{{closure}}
   9: rustc::ty::context::tls::with_context_opt
  10: rustc::ty::context::tls::with_opt
  11: rustc::util::bug::opt_span_bug_fmt
  12: rustc::util::bug::bug_fmt
  13: rustc::hir::map::hir_id_validator::check_crate
  14: rustc::hir::map::map_crate
  15: rustc::util::common::time
  16: rustc_driver::driver::compile_input
  17: rustc_driver::run_compiler_with_pool
  18: rustc_driver::driver::spawn_thread_pool
  19: rustc_driver::run_compiler
  20: <scoped_tls::ScopedKey<T>>::set
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  22: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  23: rustc_driver::run
  24: rustc_driver::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  27: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  28: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  29: main
  30: __libc_start_main
  31: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (82239b04d 2018-10-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental -C target-cpu=native --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `hyper`.

To learn more, run the command again with --verbose.
````

This bug was introduced between 4bd4e4130 and 82239b04d

Found via https://github.com/rust-lang-nursery/rust-clippy/pull/3359

**Comment by oli-obk** [comment]
I'm assuming this is due to https://github.com/rust-lang/rust/pull/54145

cc @nrc

**Comment by phansch** [comment]
If I did nothing wrong, then this is a minimal repro:

```rust
pub(super) use self::my_mod::Foo;

mod my_mod {
    pub struct Foo;
}
```

**Comment by matthiaskrgr** [comment]
Can we revert the commit for now?

**Comment by Manishearth** [comment]
Bisection confirms it's #54145

**Comment by matthiaskrgr** [comment]
Why was this closed?

**Comment by Manishearth** [comment]
Hit close on the wrong issue

**Comment by nrc** [comment]
I'm investigating today

**Comment by nrc** [comment]
OK, I have a fix, but I need to write a test, run the whole test suite, etc. and it is late here. I'll have a PR tomorrow.
