### ISSUE TITLE
ICE building hyper: same HirId assigned to `super` and `spawn_all`

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#55488]
rustc revision: `d586d5d2f51489821b471f20959333558c24b129`

```
thread 'main' panicked at 'librustc/hir/map/hir_id_validator.rs:31:                                      
HirIdValidator: The recorded owner of path segment super (id=33113) is ::server[0]::conn[0]::{{?}}[31] in
stead of ::server[0]::conn[0]::{{?}}[31]::{{?}}[0]                                                       
HirIdValidator: Same HirId ::server[0]::conn[0]::{{?}}[31]::{{?}}[0]/2 assigned for nodes path segment su
per (id=33113) and path segment spawn_all (id=79903)', librustc/util/bug.rs:47:26                        
stack backtrace:                                                                                         
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                          
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                            
   1: std::sys_common::backtrace::print                                                                  
             at libstd/sys_common/backtrace.rs:71                                                        
             at libstd/sys_common/backtrace.rs:59                                                        
   2: std::panicking::default_hook::{{closure}}                                                          
             at libstd/panicking.rs:211                                                                  
   3: std::panicking::default_hook                                                                       
             at libstd/panicking.rs:227                                                                  
   4: rustc::util::common::panic_hook                                                                    
   5: std::panicking::rust_panic_with_hook                                                               
             at libstd/panicking.rs:480                                                                  
   6: std::panicking::begin_panic                                                                        
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}                                                    
   8: rustc::ty::context::tls::with_opt::{{closure}}                                                     
   9: rustc::ty::context::tls::with_context_opt                                                          
  10: rustc::ty::context::tls::with_opt                                                                  
  11: rustc::util::bug::opt_span_bug_fmt                                                                 
  12: rustc::util::bug::bug_fmt                                                                          
  13: rustc::hir::map::hir_id_validator::check_crate                                                     
  14: rustc::hir::map::map_crate                                                                         
  15: rustc::util::common::time                                                                          
  16: rustc_driver::driver::compile_input                                                                
  17: rustc_driver::run_compiler_with_pool                                                               
  18: rustc_driver::driver::spawn_thread_pool                                                            
  19: rustc_driver::run_compiler
  20: <scoped_tls::ScopedKey<T>>::set
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  22: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  23: rustc_driver::run
  24: rustc_driver::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  27: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  28: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  29: main
  30: __libc_start_main
  31: _start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug
-reports

note: rustc 1.31.0-nightly (d586d5d2f 2018-10-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C linker=/usr/local/google/home/cramertj/src/fuchsia/buildtools/lin
ux-x64/clang/bin/clang -C opt-level=0 -C debuginfo=2 -C link-arg=--target=x86_64-fuchsia -C link-arg=-Wl,
--pack-dyn-relocs=relr -C link-arg=-Wl,--threads -C link-arg=--sysroot=/usr/local/google/home/cramertj/sr
c/fuchsia/out/x64/sdk/exported/zircon_sysroot/arch/x64/sysroot --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `hyper`
```

**Comment by cramertj** [comment]
dup of https://github.com/rust-lang/rust/issues/55376
