### ISSUE TITLE
compiler panics on improper use of static value from lazy_static within array type declaration.

### ISSUE THREAD

**Issue by WarpspeedSCP** [rust-lang/rust#55512]
When I try this code:

```rust
#[macro_use]
extern crate lazy_static;

lazy_static!{

    pub static ref a: [u32; 1] = [
        1
    ];

    pub static ref b: [u32; 1] = [
        1
    ];

    pub static ref a_b: usize = a.len() * std::mem::size_of::<u32>() + b.len() * std::mem::size_of::<u32>();
    
    // Can be in any fn as well, say main.
    // I understand that I cant can't use a_b directly here...
     pub static ref c: [u8; a_b] = [ 1, 2];
}

fn main() {
    
}   
```

I understand that there's a move going on here that isn't permitted. However, it fails to compile with an internal compiler error:

```
       Fresh version_check v0.1.5
       Fresh lazy_static v1.1.0
   Compiling testbench v0.1.0 (/home/warpspeedscp/testbench)
     Running `rustc --edition=2018 --crate-name testbench src/main.rs --color never --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=1d442159062b5d65 -C extra-filename=-1d442159062b5d65 --out-dir /home/warpspeedscp/testbench/target/debug/deps -C incremental=/home/warpspeedscp/testbench/target/debug/incremental -L dependency=/home/warpspeedscp/testbench/target/debug/deps --extern lazy_static=/home/warpspeedscp/testbench/target/debug/deps/liblazy_static-0e474105497027c9.rlib`
error[E0308]: mismatched types
  --> src/main.rs:17:29
   |
17 |      pub static ref c: [u8; a_b] = [ 1, 2];
   |                             ^^^ expected usize, found struct `a_b`
   |
   = note: expected type `usize`
              found type `a_b`

error[E0013]: constants cannot refer to statics, use a constant instead
  --> src/main.rs:17:29
   |
17 |      pub static ref c: [u8; a_b] = [ 1, 2];
   |                             ^^^

error[E0507]: cannot move out of static item
  --> src/main.rs:17:29
   |
17 |      pub static ref c: [u8; a_b] = [ 1, 2];
   |                             ^^^ cannot move out of static item

error[E0507]: cannot move out of immutable static item `a_b`
  --> src/main.rs:17:29
   |
17 |      pub static ref c: [u8; a_b] = [ 1, 2];
   |                             ^^^
   |                             |
   |                             cannot move out of immutable static item `a_b`
   |                             cannot move

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `a_b`,
 right: `usize`', librustc/ty/wf.rs:271:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   8: rustc::ty::wf::WfPredicates::compute
   9: rustc::ty::wf::obligations
  10: <rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
  11: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_where_possible
  12: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_all_or_error
  13: rustc_typeck::check::FnCtxt::select_all_obligations_or_error
  14: rustc::ty::context::tls::with_related_context
  15: rustc::infer::InferCtxtBuilder::enter
  16: rustc_typeck::check::wfcheck::check_item_well_formed
  17: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::check_item_well_formed<'tcx>>::compute
  18: rustc::ty::context::tls::with_context
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc::ty::context::tls::with_related_context
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  24: rustc::session::Session::track_errors
  25: rustc::util::common::time
  26: rustc_typeck::check_crate
  27: rustc::ty::context::tls::enter_context
  28: <std::thread::local::LocalKey<T>>::with
  29: rustc::ty::context::TyCtxt::create_and_enter
  30: rustc_driver::driver::compile_input
  31: rustc_driver::run_compiler_with_pool
  32: rustc_driver::driver::spawn_thread_pool
  33: rustc_driver::run_compiler
  34: <scoped_tls::ScopedKey<T>>::set
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  36: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  37: rustc_driver::run
  38: rustc_driver::main
  39: std::rt::lang_start::{{closure}}
  40: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  41: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  42: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  43: main
  44: __libc_start_main
  45: <unknown>
query stack during panic:
#0 [check_item_well_formed] processing `<c as lazy_static::Deref>::deref::__stability`
end of query stack
error: aborting due to 4 previous errors

Some errors occurred: E0013, E0308, E0507.
For more information about an error, try `rustc --explain E0013`.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (155510e37 2018-10-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `testbench`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name testbench src/main.rs --color never --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=1d442159062b5d65 -C extra-filename=-1d442159062b5d65 --out-dir /home/warpspeedscp/testbench/target/debug/deps -C incremental=/home/warpspeedscp/testbench/target/debug/incremental -L dependency=/home/warpspeedscp/testbench/target/debug/deps --extern lazy_static=/home/warpspeedscp/testbench/target/debug/deps/liblazy_static-0e474105497027c9.rlib` (exit code: 101)

```

Rust version info-

```
$ rustc -v -V
rustc 1.31.0-nightly (155510e37 2018-10-20)
binary: rustc
commit-hash: 155510e377ae2a8d8ee0dad1a5f809c9062a5526
commit-date: 2018-10-20
host: x86_64-unknown-linux-gnu
release: 1.31.0-nightly
LLVM version: 8.0
```

**Comment by jakubadamw** [comment]
Doesn't ICE any more.

```
error[E0308]: mismatched types
  --> src\lib.rs:18:29
   |
18 |      pub static ref c: [u8; a_b] = [ 1, 2];
   |                             ^^^
   |                             |
   |                             expected usize, found struct `a_b`
   |                             help: consider dereferencing the type: `*a_b`
   |
   = note: expected type `usize`
              found type `a_b`
```

**Comment by oli-obk** [comment]
Without a reproduction, I don't think this issue is actionable.
