### ISSUE TITLE
ICE when compiling the `compact` crate

### ISSUE THREAD

**Issue by hirschenberger** [rust-lang/rust#55643]
ICE when compiling the `compact` crate v0.2.13

```
error: internal compiler error: librustc/traits/specialize/mod.rs:104: When translating substitutions for specialization, the expected specialization failed to hold

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:600:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc::traits::specialize::translate_substs::{{closure}}
  15: rustc::traits::specialize::translate_substs
  16: rustc::ty::context::tls::with_related_context
  17: rustc::infer::InferCtxtBuilder::enter
  18: rustc::traits::specialize::find_associated_item
  19: rustc::ty::instance::Instance::resolve
  20: rustc_mir::lints::check
  21: rustc::ty::context::tls::with_context::{{closure}}
  22: rustc::ty::context::GlobalCtxt::enter_local
  23: rustc_mir::build::mir_build
  24: rustc_mir::transform::mir_built
  25: rustc::ty::query::__query_compute::mir_built
  26: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_built<'tcx>>::compute
  27: rustc::dep_graph::graph::DepGraph::with_task_impl
  28: rustc::ty::context::tls::with_related_context
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  31: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_built
  32: rustc_mir::transform::check_unsafety::unsafety_check_result
  33: rustc::ty::query::__query_compute::unsafety_check_result
  34: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::unsafety_check_result<'tcx>>::compute
  35: rustc::dep_graph::graph::DepGraph::with_task_impl
  36: rustc::ty::context::tls::with_related_context
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  38: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  39: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::unsafety_check_result
  40: rustc_mir::transform::mir_const
  41: rustc::ty::query::__query_compute::mir_const
  42: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_const<'tcx>>::compute
  43: rustc::dep_graph::graph::DepGraph::with_task_impl
  44: rustc::ty::context::tls::with_related_context
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  46: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  47: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_const
  48: rustc_mir::transform::mir_validated
  49: rustc::ty::query::__query_compute::mir_validated
  50: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_validated<'tcx>>::compute
  51: rustc::dep_graph::graph::DepGraph::with_task_impl
  52: rustc::ty::context::tls::with_related_context
  53: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  54: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  55: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  56: rustc_borrowck::borrowck::borrowck
  57: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::borrowck<'tcx>>::compute
  58: rustc::dep_graph::graph::DepGraph::with_task_impl
  59: rustc::ty::context::tls::with_related_context
  60: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  61: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  62: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners
  63: rustc_borrowck::borrowck::check_crate
  64: rustc::util::common::time
  65: rustc::ty::context::tls::enter_context
  66: <std::thread::local::LocalKey<T>>::with
  67: rustc::ty::context::TyCtxt::create_and_enter
  68: rustc_driver::driver::compile_input
  69: rustc_driver::run_compiler_with_pool
  70: rustc_driver::driver::spawn_thread_pool
  71: rustc_driver::run_compiler
  72: <scoped_tls::ScopedKey<T>>::set
  73: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  74: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  75: rustc_driver::run
  76: rustc_driver::main
  77: std::rt::lang_start::{{closure}}
  78: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  79: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  80: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  81: main
  82: __libc_start_main
  83: <unknown>
query stack during panic:
#0 [mir_built] processing `<compact_dict::CompactDict<K, V, A> as compact::Compact>::decompact`
#1 [unsafety_check_result] processing `<compact_dict::CompactDict<K, V, A> as compact::Compact>::decompact`
#2 [mir_const] processing `<compact_dict::CompactDict<K, V, A> as compact::Compact>::decompact`
#3 [mir_validated] processing `<compact_dict::CompactDict<K, V, A> as compact::Compact>::decompact`
#4 [borrowck] processing `<compact_dict::CompactDict<K, V, A> as compact::Compact>::decompact`
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (8b096314a 2018-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C codegen-units=4 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by hirschenberger** [comment]
Does not ICE with current nightly `rustc 1.39.0-nightly (eb48d6bde 2019-09-12)`

I'll close this.
