### ISSUE TITLE
ICE - expected specialization failed to hold

### ISSUE THREAD

**Issue by J-Light** [rust-lang/rust#55818]
Hi 
Trying to compile the simple example [PyO3](https://github.com/PyO3/pyo3) and get the following error

**`./Cargo.toml`**
```toml
[package]
name = "rust-py"
version = "0.1.0"

[lib]
name = "rust_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.4.1"
features = ["extension-module"]
```

**`src/lib.rs`**
```rust
#![feature(specialization)]

#[macro_use]
extern crate pyo3;

use pyo3::prelude::*;

#[pyfunction]
/// Formats the sum of two numbers as string
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

/// This module is a python moudle implemented in Rust.
#[pymodinit]
fn rust_py(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_function!(sum_as_string))?;

    Ok(())
}
```

Error message
```log
§ cargo build --release
   Compiling pyo3 v0.4.1
error: internal compiler error: librustc\traits\specialize\mod.rs:104: When translating substitutions for specialization, the expected specialization failed to hold

thread 'main' panicked at 'Box<Any>', librustc_errors\lib.rs:600:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (04fdb44f5 2018-11-03) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `pyo3`.
To learn more, run the command again with --verbose.
```
Compiler Information (Nightly active in directory):
```powershell
§ rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (directory override for '\\?\C:\abc\rust-py')
rustc 1.32.0-nightly (04fdb44f5 2018-11-03)
```

**Comment by mstallmo** [comment]
I'm getting the same error on Linux:

`Cargo.toml`
```
[package]
name = "lenrs"
version = "0.1.0"
edition = "2018"

[dependencies.pyo3]
version = "0.4"
features = ["extension-module"]

[lib]
crate-type = ["cdylib"]
name = "lenrs"
```


`lib.rs`
```
#![feature(specialization)]

#[macro_use]
extern crate pyo3;

use pyo3::prelude::*;

#[pyfunction]
/// Formats the sum of two numbers as string
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

/// This module is a python module implemented in Rust.
#[pymodule]
fn string_sum(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_function!(sum_as_string))?;

    Ok(())
}
```

`Error Message`
```
cargo build
   Compiling pyo3 v0.4.1
error: internal compiler error: librustc/traits/specialize/mod.rs:104: When translating substitutions for specialization, the expected specialization failed to hold

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:600:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (6b9b97bd9 2018-11-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `pyo3`.

To learn more, run the command again with --verbose.
```

`Compiler information`
```
rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-2018-11-12-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/mason/Workspace/lenrs')
rustc 1.32.0-nightly (6b9b97bd9 2018-11-15)
```

**Comment by Elinvynia** [comment]
I am unable to reproduce this on:
```
rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
binary: rustc
commit-hash: 7ebd87a7a1e0e21767422e115c9455ef6e6d4bee
commit-date: 2020-05-08
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

Compiling `pyo3 v0.4.1` just results in the following warning:
```
warning: unused variable: `py`
  --> src/lib.rs:16:12
   |
16 | fn rust_py(py: Python, m: &PyModule) -> PyResult<()> {
   |            ^^ help: if this is intentional, prefix it with an underscore: `_py`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted
```

**Comment by Nilstrieb** [comment]
There's no simple reproduction, so this is not really actionable, I don't think this is worth minimizing.
