### ISSUE TITLE
build rust from source fail on macos 10.13.6

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang/rust#55875]
build rust from source code in macOS High Sierra 10.13.6:

```rust
$ python ./x.py build
```

I got the following errors : 

```rust
...
Compiling std v0.0.0 (/Users/xxx/work/projects/rust/rust/src/libstd)        
error: failed to run custom build command for `std v0.0.0 (/Users/xxx/work/projects/rust/rust/src/libstd)`
process didn't exit successfully: `/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/stage0-std/release/build/std-defaf1519120b693/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=static=backtrace
cargo:rustc-link-search=native=/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/native/libbacktrace/
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("2")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = Some("cc")
CFLAGS_x86_64-apple-darwin = Some("-ffunction-sections -fdata-sections -fPIC -m64 -stdlib=libc++")
running: "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-stdlib=libc++" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "../libbacktrace" "-I" "/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/native/libbacktrace" "-fvisibility=hidden" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-o" "/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/native/libbacktrace/../libbacktrace/alloc.o" "-c" "../libbacktrace/alloc.c"
cargo:warning=clang: error: no such file or directory: '../libbacktrace/alloc.c'
cargo:warning=clang: error: no input files
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-stdlib=libc++" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "../libbacktrace" "-I" "/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/native/libbacktrace" "-fvisibility=hidden" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-o" "/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/native/libbacktrace/../libbacktrace/alloc.o" "-c" "../libbacktrace/alloc.c" with args "cc" did not execute successfully (status code exit code: 1).

', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: cc::fail
   8: cc::Build::compile
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main

warning: build failed, waiting for other jobs to finish...
error: build failed                                                                   
command did not execute successfully: "/Users/xxx/work/projects/rust/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-j" "4" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "/Users/xxx/work/projects/rust/rust/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1101:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:476
   5: <core::str::CharIndices<'a> as core::iter::iterator::Iterator>::next
             at libstd/panicking.rs:410
   6: bootstrap::compile::run_cargo
             at bootstrap/compile.rs:1101
   7: std::thread::panicking
             at bootstrap/compile.rs:115
   8: bootstrap::builder::Builder::cargo::{{closure}}
             at bootstrap/builder.rs:1215
   9: bootstrap::compile::copy_apple_sanitizer_dylibs
             at bootstrap/compile.rs:342
  10: bootstrap::builder::Builder::cargo::{{closure}}
             at bootstrap/builder.rs:1215
  11: bootstrap::compile::test_cargo
             at bootstrap/compile.rs:464
  12: bootstrap::builder::Builder::cargo::{{closure}}
             at bootstrap/builder.rs:1215
  13: bootstrap::compile::compiler_file
             at bootstrap/compile.rs:959
  14: bootstrap::builder::Builder::cargo::{{closure}}
             at bootstrap/builder.rs:1215
  15: bootstrap::builder::Builder::run_step_descriptions
             at bootstrap/builder.rs:579
  16: bootstrap::compile::compiler_file
             at bootstrap/compile.rs:952
  17: bootstrap::builder::Builder::cargo::{{closure}}
             at bootstrap/builder.rs:1215
  18: bootstrap::builder::Builder::run_step_descriptions
             at bootstrap/builder.rs:579
  19: std::thread::panicking
             at bootstrap/compile.rs:55
  20: bootstrap::builder::StepDescription::maybe_run
             at bootstrap/builder.rs:191
  21: bootstrap::builder::StepDescription::run
             at bootstrap/builder.rs:215
  22: bootstrap::builder::Builder::run_step_descriptions
             at bootstrap/builder.rs:571
  23: bootstrap::builder::Builder::get_step_descriptions
             at bootstrap/builder.rs:561
  24: bootstrap::Crate::local_path
             at bootstrap/lib.rs:479
  25: bootstrap::main
             at bootstrap/bin/main.rs:29
  26: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  28: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  29: std::alloc::default_alloc_error_hook
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  30: std::rt::lang_start
             at libstd/rt.rs:74
  31: bootstrap::main
failed to run: /Users/xxx/work/projects/rust/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:01:05
```

**Comment by ZhangHanDong** [comment]
anyone help ？

**Comment by ZhangHanDong** [comment]
It's my fault!   It was eventually fixed by moving /Users/USER/python/bin to the end of $PATH.
