### ISSUE TITLE
ICE when macro produces multiple functions each with "wrong number of type arguments" turbofish errors

### ISSUE THREAD

**Issue by tormol** [rust-lang/rust#55873]
Minimal repro:

```rust
macro_rules! m {($asref:ty) => {
    fn bar(s: &str) -> &$asref {s.as_ref::<$asref>()}
    fn baz(s: &str) -> &$asref {s.as_ref::<$asref>()}
}}

m!{[u8]}

fn main() {}
```

Produces this error and backtrace:

```
$ RUST_BACKTRACE=1 rustc two_functions.rs 
error[E0107]: wrong number of type arguments: expected 0, found 1
 --> two_functions.rs:6:4
  |
6 | m!{[u8]}
  |    ^^^^ unexpected type argument

error: internal compiler error: librustc_typeck/check/mod.rs:2384: no type for node 47: type u8 (id=47) in fcx 0x7ffd82952eb0

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:600:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc_typeck::check::FnCtxt::node_ty
  15: <rustc_typeck::check::writeback::WritebackCx<'cx, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_ty
  16: <rustc_typeck::check::writeback::WritebackCx<'cx, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_ty
  17: rustc::hir::intravisit::walk_expr
  18: <rustc_typeck::check::writeback::WritebackCx<'cx, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  19: <rustc_typeck::check::writeback::WritebackCx<'cx, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  20: rustc_typeck::check::writeback::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::resolve_type_vars_in_body
  21: rustc::ty::context::tls::with_related_context
  22: rustc::infer::InferCtxtBuilder::enter
  23: rustc_typeck::check::typeck_tables_of
  24: rustc::ty::query::__query_compute::typeck_tables_of
  25: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_tables_of<'tcx>>::compute
  26: rustc::dep_graph::graph::DepGraph::with_task_impl
  27: rustc::ty::context::tls::with_related_context
  28: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  31: rustc::session::Session::track_errors
  32: rustc_typeck::check::typeck_item_bodies
  33: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_item_bodies<'tcx>>::compute
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::ty::context::tls::with_related_context
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  38: rustc_typeck::check_crate
  39: rustc::ty::context::tls::enter_context
  40: <std::thread::local::LocalKey<T>>::with
  41: rustc::ty::context::TyCtxt::create_and_enter
  42: rustc_driver::driver::compile_input
  43: rustc_driver::run_compiler_with_pool
  44: <scoped_tls::ScopedKey<T>>::set
  45: rustc_driver::run_compiler
  46: syntax::with_globals
  47: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  48: rustc_driver::run
  49: rustc_driver::main
  50: std::rt::lang_start::{{closure}}
  51: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  52: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  53: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
             at libstd/rt.rs:58
  54: main
  55: __libc_start_main
  56: <unknown>
query stack during panic:
#0 [typeck_tables_of] processing `baz`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0107`.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (6e9b84296 2018-11-10) running on x86_64-unknown-linux-gnu
```

The ICE does not occur if the type list does not contain a macro parameter, or both usages are in the same function:

```rust
macro_rules! foo {($asref:ty) => {
    fn bar(s: &str) -> &[u8] {s.as_ref::<[u8]>()}
    fn baz(s: &str) -> &[u8] {s.as_ref::<[u8]>()}
    fn quux(s: &str) -> (&asref, &$asref) {
        let a = {s.as_ref::<$asref>()};
        let b = {s.as_ref::<$asref>()};
        (a, b)
    }
}}

foo!{[u8]}
```

I discovered this ICE with a macro containing mirrored `PartialEq` impls using `.as_ref()` for turning the
local type into the type to compare against. Reduced version:

```rust
struct Foo(u8);
impl AsRef<u8> for Foo {
    fn as_ref(&self) -> &u8 {
        &self.0
    }
}

macro_rules! impl_partial_eq {($wider: ty) => {
    impl PartialEq<Foo> for $wider {
        fn eq(&self, other: &Foo) -> bool {
            self == other.as_ref::<$wider>()
        }
    }
    impl PartialEq<$wider> for Foo {
        fn eq(&self, other: &$wider) -> bool {
            self.as_ref::<$wider>() == other
        }
    }
}}

impl_partial_eq!{u8}
```
A single impl but with both `eq()` and `ne()` also ICEs.

## Meta
rustc 1.32.0-nightly (6e9b84296 2018-11-10)
binary: rustc
commit-hash: 6e9b84296223126a0a59bde63a0f97011bb7b0f5
commit-date: 2018-11-10
host: x86_64-unknown-linux-gnu
release: 1.32.0-nightly
LLVM version: 8.0

## Release bisect
The ICE first appeared in Rust 1.25.0, and is also present in Rust 1.30.1 and 1.31.0-beta-8.

Rust 1.20.0 and before had a much clearer error message:
```
error[E0035]: does not take type parameters
 --> two_functions.rs:2:35
  |
2 |     fn bar(s: &str) -> &$asref {s.as_ref::<$asref>()}
  |                                   ^^^^^^ called with unneeded type parameters
...
6 | m!{[u8]}
  | -------- in this macro invocation

error[E0035]: does not take type parameters
 --> two_functions.rs:3:35
  |
3 |     fn baz(s: &str) -> &$asref {s.as_ref::<$asref>()}
  |                                   ^^^^^^ called with unneeded type parameters
...
6 | m!{[u8]}
  | -------- in this macro invocation

error: aborting due to 2 previous errors
```

**Comment by jonas-schievink** [comment]
Still reproduces on 1.35.0 and the current nightly (`rustc 1.37.0-nightly (991c719a1 2019-06-08)`).

> The ICE first appeared in Rust 1.25.0

Indeed, marking as regression.

**Comment by pnkfelix** [comment]
triage: P-medium. Removing nomination label.

**Comment by estebank** [comment]
@pnkfelix will replacing the `bug!()` call with `delay_span_bug` be correct in this case? This case seems to be reached only if prior errors have occurred, but it seems like a lazy solution to the ICE that could mask other issues.

**Comment by Alexendoo** [comment]
No longer appears to ICE

**Comment by tormol** [comment]
I can confirm that the ICE is gone from Rust >= 1.37.
