### ISSUE TITLE
cargo build panic

### ISSUE THREAD

**Issue by nextzhou** [rust-lang/rust#56099]
cargo version:  cargo 1.31.0-beta (339d9f9c8 2018-11-16)
rustc version: rustc 1.31.0-beta.13 (d4de9b138 2018-11-16)
rust 2018 edition

code that causes panic:
```rust
pub (in ::xxx) struct Xxx {};
```

panic infomation: 

```
thread 'main' panicked at 'librustc_resolve/lib.rs:3458: indetermined path result in resolve_qpath', librustc/util/bug.rs:47:26
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::begin_panic
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   8: rustc::ty::context::tls::with_opt::{{closure}}
   9: rustc::ty::context::tls::with_context_opt
  10: rustc::ty::context::tls::with_opt
  11: rustc::util::bug::opt_span_bug_fmt
  12: rustc::util::bug::bug_fmt
  13: rustc_resolve::Resolver::smart_resolve_path_fragment
  14: rustc_resolve::Resolver::resolve_visibility
  15: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a, 'cl>>::build_reduced_graph_for_item
  16: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
  17: syntax::ext::expand::AstFragment::visit_with
  18: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a, 'crateloader>>::visit_ast_fragment_with_placeholders
  19: syntax::ext::expand::MacroExpander::collect_invocations
  20: syntax::ext::expand::MacroExpander::expand_fragment
  21: syntax::ext::expand::MacroExpander::expand_crate
  22: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  23: rustc::util::common::time
  24: rustc_driver::driver::phase_2_configure_and_expand
  25: rustc_driver::driver::compile_input
  26: rustc_driver::run_compiler_with_pool
  27: rustc_driver::driver::spawn_thread_pool
  28: rustc_driver::run_compiler
  29: <scoped_tls::ScopedKey<T>>::set
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  31: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  32: rustc_driver::run
  33: rustc_driver::main
  34: std::rt::lang_start::{{closure}}
  35: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  36: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  37: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  38: main
  39: __libc_start_main
  40: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-beta.13 (d4de9b138 2018-11-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

**Comment by gralpli** [comment]
I can't reproduce this. I tried the following steps:

```bash
rustup default beta-2018-11-17
cargo new issue56099
cd issue56099
echo "pub (in ::xxx) struct Xxx {};" > src/main.rs
cargo run
```

I get:

```
   Compiling issue56099 v0.1.0 (/issue56099)
error: expected item, found `;`
 --> src/main.rs:1:29
  |
1 | pub (in ::xxx) struct Xxx {};
  |                             ^ help: consider removing this semicolon
  |
  = help: braced struct declarations are not followed by a semicolon

error: aborting due to previous error

error: Could not compile `issue56099`.

To learn more, run the command again with --verbose.
```
