### ISSUE TITLE
Compiler panic when running rustdoc (unreproducible on latest nightly)

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#56103]
I got a compiler panic running `RUST_BACKTRACE=1 cargo doc --open` in the most up-to-date `wasm-bindgen` `js-sys`. It seems to have been fixed in latest nightly, but I thought I should report it anyway.

<details><summary>compiler output</summary>

```
thread 'main' panicked at 'no entry found for key', libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: rust_begin_unwind
             at libstd/panicking.rs:325
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   9: core::option::expect_failed
             at libcore/option.rs:1008
  10: <T as serialize::serialize::Decodable>::decode
  11: serialize::serialize::Decoder::read_enum
  12: rustc::ty::query::on_disk_cache::__ty_decoder_impl::<impl serialize::serialize::SpecializedDecoder<&'tcx rustc::ty::TyS<'tcx>> for rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x>>::specialized_decode
  13: rustc::ty::query::on_disk_cache::__ty_decoder_impl::<impl serialize::serialize::SpecializedDecoder<&'tcx rustc::ty::TyS<'tcx>> for rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x>>::specialized_decode
  14: serialize::serialize::Decoder::read_enum
  15: <smallvec::SmallVec<A> as core::iter::traits::FromIterator<<A as smallvec::Array>::Item>>::from_iter
  16: <core::result::Result<T, E> as rustc::ty::context::InternIteratorElement<T, R>>::intern_with
  17: serialize::serialize::Decoder::read_enum
  18: rustc::ty::query::on_disk_cache::__ty_decoder_impl::<impl serialize::serialize::SpecializedDecoder<&'tcx rustc::ty::TyS<'tcx>> for rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x>>::specialized_decode
  19: serialize::serialize::Decoder::read_struct
  20: <alloc::boxed::Box<T> as serialize::serialize::Decodable>::decode
  21: serialize::serialize::Decoder::read_enum
  22: <rustc::mir::TerminatorKind<'tcx> as serialize::serialize::Decodable>::decode::{{closure}}::{{closure}}
  23: serialize::serialize::Decoder::read_struct
  24: serialize::serialize::Decoder::read_option
  25: serialize::serialize::Decoder::read_struct
  26: serialize::serialize::Decoder::read_seq
  27: <rustc::mir::Mir<'tcx> as serialize::serialize::Decodable>::decode::{{closure}}
  28: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  29: <rustc::ty::query::queries::optimized_mir<'tcx> as rustc::ty::query::config::QueryDescription<'tcx>>::try_load_from_disk
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query
  31: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  32: rustc_mir::monomorphize::collector::collect_items_rec
  33: rustc_mir::monomorphize::collector::collect_items_rec
  34: rustc_mir::monomorphize::collector::collect_items_rec
  35: rustc_mir::monomorphize::collector::collect_items_rec
  36: rustc_mir::monomorphize::collector::collect_items_rec
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_items_rec
  41: rustc_mir::monomorphize::collector::collect_items_rec
  42: rustc_mir::monomorphize::collector::collect_items_rec
  43: rustc_mir::monomorphize::collector::collect_items_rec
  44: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  45: rustc::util::common::time
  46: rustc_mir::monomorphize::collector::collect_crate_mono_items
  47: rustc::util::common::time
  48: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  49: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute
  50: rustc::ty::context::tls::with_context
  51: rustc::dep_graph::graph::DepGraph::with_task_impl
  52: rustc::ty::context::tls::with_related_context
  53: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  54: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query
  55: rustc::ty::query::plumbing::force_from_dep_node
  56: rustc::dep_graph::graph::DepGraph::try_mark_green
  57: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_mark_green_and_read
  58: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  59: rustc_metadata::encoder::encode_metadata
  60: rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata
  61: rustc::ty::context::TyCtxt::encode_metadata
  62: rustc_codegen_llvm::base::write_metadata
  63: rustc::util::common::time
  64: rustc_codegen_llvm::base::codegen_crate
  65: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  66: rustc::util::common::time
  67: rustc_driver::driver::phase_4_codegen
  68: rustc_driver::driver::compile_input::{{closure}}
  69: rustc::ty::context::tls::enter_context
  70: <std::thread::local::LocalKey<T>>::with
  71: rustc::ty::context::TyCtxt::create_and_enter
  72: rustc_driver::driver::compile_input
  73: rustc_driver::run_compiler_with_pool
  74: <scoped_tls::ScopedKey<T>>::set
  75: rustc_driver::run_compiler
  76: syntax::with_globals
  77: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  78: rustc_driver::run
  79: rustc_driver::main
  80: std::rt::lang_start::{{closure}}
  81: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  82: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  83: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
             at libstd/rt.rs:58
  84: main
  85: __libc_start_main
  86: <unknown>
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (ca79ecd69 2018-11-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

```
</details>

**Comment by Mark-Simulacrum** [comment]
Closing since this has presumably been fixed. Thanks!
