### ISSUE TITLE
thread '<unnamed>' panicked at 'upgrading again', libstd/sync/mpsc/oneshot.rs:225:22

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/rust#56150]
```
thread '<unnamed>' panicked at 'upgrading again', libstd/sync/mpsc/oneshot.rs:225:22
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', libstd/sync/mpsc/shared.rs:504:9
stack backtrace:
   0:        0x10e580673 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hef12090eedc5fdba
   1:        0x10e57b00c - std::sys_common::backtrace::_print::hd179a38b6e7095fc
   2:        0x10e57f543 - std::panicking::default_hook::{{closure}}::h6a8c88b94e7f4a45
   3:        0x10e57f23d - std::panicking::default_hook::h120fec8932528539
   4:        0x10e57fcce - std::panicking::rust_panic_with_hook::h75d395e9de1e6680
   5:        0x10e57f7ec - std::panicking::continue_panic_fmt::h58c717bdfd177e27
   6:        0x10e57f740 - std::panicking::begin_panic_fmt::h43a3bb92c2545418
   7:        0x10e0983df - <std::sync::mpsc::shared::Packet<T> as core::ops::drop::Drop>::drop::hb1fddd8f7000a32e
   8:        0x10e09415c - <alloc::sync::Arc<T>>::drop_slow::h74f89d80a6fab371
   9:        0x10e097e2e - <std::sync::mpsc::Sender<T> as core::clone::Clone>::clone::h6b988534d070e160
  10:        0x10e09081c - cache_server::handle_command::h8ed40ed6c0aca9bc
  11:        0x10e08e2ec - cache_server::child_loop::h99fd4c574d04f8c3
  12:        0x10e09ec33 - <F as crossbeam::FnBox>::call_box::h64c13abd361901cf
  13:        0x10e58dbfe - __rust_maybe_catch_panic
  14:        0x10e09cf21 - <F as alloc::boxed::FnBox<A>>::call_box::h933cc180a1938386
  15:        0x10e581ffb - std::sys::unix::thread::Thread::new::thread_start::hadf530c67ee3886e
  16:     0x7fff68b84660 - _pthread_body
  17:     0x7fff68b8450c - _pthread_start
thread panicked while panicking. aborting.
Illegal instruction: 4
```

**Comment by estebank** [comment]
@rohitjoshi could you provide a repro case? How did you come across this error?

**Comment by jonas-schievink** [comment]
Assuming this is one of the issues in https://github.com/rust-lang/rust/issues/39364, so closing in favor of that issue. This would also be fixed with the new channels proposed in https://internals.rust-lang.org/t/proposal-new-channels-for-rusts-standard-library/9548
