### ISSUE TITLE
Issue in consuming pipe on arm7

### ISSUE THREAD

**Issue by RCasatta** [rust-lang/rust#57423]
I have a rust program which reads from stdin and sometimes it receives 0 from read_line even if I know there are many more lines before the outputs of the previous program ends. (read lines are different across launches in the following example 53542171 lines are read, sometimes it reads everything which are about 300M lines)

I am not sure I am not panicking somewhere else but the strange thins is the same program always works on x86_64 platform (this is armv7)

consuming the output for example with `| wc -l` always work 

sources are here https://github.com/RCasatta/rustat/tree/v2 

```
time ./bitcoin-iterate/bitcoin-iterate --blockdir /mnt/ssd/bitcoin/blocks -q --tx=$
%bN %bl %bc %bH %tX' | RUST_BACKTRACE=full ./rustat/target/release/rustat
starting op_return processer
starting blocks processer
starting Segwit processer
bitcoin-iterate: Skipped 13965764 at end of /mnt/ssd/bitcoin/blocks/blk01485.dat
Received 0 as read_line after 53542171 lines
sending None to line_senders[0]
sending None to line_senders[1]
thread '<unnamed>ending line parser 0
' panicked at 'failed to parse line: Io(Custom { kind: UnexpectedEof, error: StringError("failed to $
ill whole buffer") })', libcore/result.rs:ending line parser 1
1009:5sending None to line_senders[2]

sending None to line_senders[3]
ending line parser 3
stack backtrace:
   0:   0x5326eb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h2534e215b56d3dcf
                       at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:   0x529a27 - std::sys_common::backtrace::print::hdffa0e0e2a717179
                       at libstd/sys_common/backtrace.rs:71
                       at libstd/sys_common/backtrace.rs:59
   2:   0x525bef - std::panicking::default_hook::{{closure}}::h938b45f75e1e39a4
                       at libstd/panicking.rs:211
   3:   0x525867 - std::panicking::default_hook::hd9fdeabb669e43fc
                       at libstd/panicking.rs:227
   4:   0x5263eb - std::panicking::rust_panic_with_hook::h781594332e68f14e
                       at libstd/panicking.rs:476
   5:   0x525faf - std::panicking::continue_panic_fmt::h986a35a447ed28cf
                       at libstd/panicking.rs:390
   6:   0x525e97 - rust_begin_unwind
                       at libstd/panicking.rs:325
   7:   0x5694e3 - core::panicking::panic_fmt::hca5dc4e8b320bc56
                       at libcore/panicking.rs:77
   8:   0x5166a3 - core::result::unwrap_failed::ha22f88ccb2ce83ed
   9:   0x50391f - std::sys_common::backtrace::__rust_begin_short_backtrace::he443d31fa1795249
  10:   0x51a353 - std::panicking::try::do_call::hd6efff1203506246                           [27/610]
  11:   0x53adeb - __rust_maybe_catch_panic
                       at libpanic_unwind/lib.rs:102
  12:   0x5052a7 - <F as alloc::boxed::FnBox<A>>::call_box::h5aa894c61e9323d5
  13:   0x533557 - std::sys_common::thread::start_thread::h2eb9063e808b4355
                       at liballoc/boxed.rs:682
                       at libstd/sys_common/thread.rs:24
  14:   0x52698f - std::sys::unix::thread::Thread::new::thread_start::h1c12c88a139098f3
                       at libstd/sys/unix/thread.rs:90
thread 'main' panicked at 'line_parser failed to join: Any', libcore/result.rs:1009:5
stack backtrace:
   0:   0x5326eb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h2534e215b56d3dcf
                       at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:   0x529a27 - std::sys_common::backtrace::print::hdffa0e0e2a717179
                       at libstd/sys_common/backtrace.rs:71
                       at libstd/sys_common/backtrace.rs:59
   2:   0x525bef - std::panicking::default_hook::{{closure}}::h938b45f75e1e39a4
                       at libstd/panicking.rs:211
   3:   0x525867 - std::panicking::default_hook::hd9fdeabb669e43fc
                       at libstd/panicking.rs:227
   4:   0x5263eb - std::panicking::rust_panic_with_hook::h781594332e68f14e
   5:   0x525faf - std::panicking::continue_panic_fmt::h986a35a447ed28cf                      [5/610]
                       at libstd/panicking.rs:390
   6:   0x525e97 - rust_begin_unwind
                       at libstd/panicking.rs:325
   7:   0x5694e3 - core::panicking::panic_fmt::hca5dc4e8b320bc56
                       at libcore/panicking.rs:77
   8:   0x516353 - core::result::unwrap_failed::h20c0d0eb43913a43
   9:   0x502fe7 - rustat::main::hf8527cc1fc92370e
  10:   0x5039e3 - std::rt::lang_start::{{closure}}::ha435600535d49604
  11:   0x525e0f - std::panicking::try::do_call::hd6aaccba94060c88
                       at libstd/rt.rs:59
                       at libstd/panicking.rs:310
  12:   0x53adeb - __rust_maybe_catch_panic
                       at libpanic_unwind/lib.rs:102
  13:   0x525d5b - std::panicking::try::h3baffb5b8337159b
                       at libstd/panicking.rs:289
  14:   0x523d53 - std::rt::lang_start_internal::h6b7407d3925ded7f
                       at libstd/panic.rs:392
                       at libstd/rt.rs:58
  15:   0x5033bf - main
  16: 0xb6db8fe5 - __libc_start_main

real    37m7.149s
user    140m21.616s
sys     30m43.543s
```

```
$ rustc --version --verbose
rustc 1.31.1 (b6c32da9b 2018-12-18)
binary: rustc
commit-hash: b6c32da9b0481e3e9d737153286b3ff8aa39a22c
commit-date: 2018-12-18
host: armv7-unknown-linux-gnueabihf
release: 1.31.1
LLVM version: 8.0
```

I can try to emulate the bug with simpler code is that could help

**Comment by nagisa** [comment]
Please minimize and isolate the issue as much as possible.

**Comment by RCasatta** [comment]
The issue was getting out of memory on the arm platform, sorry for opening
