### ISSUE TITLE
`std::env` fails every 30 tests (or so)

### ISSUE THREAD

**Issue by SamuelMarks** [rust-lang/rust#58391]
Run this piece of code dozens of times, with `cargo test`:

```rust
pub fn env_or<T>(key: &str, default_env: T) -> std::ffi::OsString
where
    T: Into<std::ffi::OsString>,
{
    match std::env::var_os(key) {
        Some(val) => val,
        None => default_env.into(),
    }
}

#[cfg(test)]
mod tests {
    use super::env_or;
    use std::env;

    const KEY: &'static str = "FOO";
    const VALUE: &'static str = "BAR";

    #[test]
    fn env_or_some() {
        env::set_var(KEY, VALUE);
        assert_eq!(env_or(KEY, KEY), VALUE);
    }

    #[test]
    fn env_or_default() {
        if env::var(KEY).is_ok() {
            env::remove_var(KEY);
        }
        assert_eq!(env_or(KEY, KEY), KEY);
    }
}
```

After mostly successes, you'll get something like:
```
thread 'env::tests::env_or_default' panicked at 'assertion failed: `(left == right)`
  left: `"BAR"`,
 right: `"FOO"`', src/env.rs:36:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:209
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:340
   7: offregisters_lib::env::tests::env_or_default
             at src/env.rs:36
   8: offregisters_lib::env::tests::env_or_default::{{closure}}
             at src/env.rs:32
   9: core::ops::function::FnOnce::call_once
             at /rustc/d1731801163df1d3a8d4ddfa68adac2ec833ef7f/src/libcore/ops/function.rs:231
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1497
             at /rustc/d1731801163df1d3a8d4ddfa68adac2ec833ef7f/src/libcore/ops/function.rs:231
             at /rustc/d1731801163df1d3a8d4ddfa68adac2ec833ef7f/src/liballoc/boxed.rs:734
  11: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:90
  12: test::run_test::run_test_inner::{{closure}}
             at /rustc/d1731801163df1d3a8d4ddfa68adac2ec833ef7f/src/libstd/panicking.rs:276
             at /rustc/d1731801163df1d3a8d4ddfa68adac2ec833ef7f/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1452
```

**Comment by kennytm** [comment]
`cargo test` executes the test in parallel by default, which means `env_or_some` could run after the `env::remove_var` and before the `assert_eq!(env_or(KEY, KEY), KEY);`. The failure is expected.

Use `cargo test -- --test-threads=1` if your test can't be executed in parallel.

**Comment by SamuelMarks** [comment]
Hmm, is there some way to run the function body in a—to use database terminology—transaction?

**Comment by kennytm** [comment]
You could use a global `std::sync::Mutex`.

**Comment by SamuelMarks** [comment]
True that
