### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by michaelmelanson** [rust-lang/rust#58444]
This gist has two files: `neuron-broken.rs` and `neuron-working.rs`

https://gist.github.com/michaelmelanson/1f815ca9fea0b9500289c1db4ebf2760

As the name implies, the 'working' one is fine except for a warning about `num_neurons` being lowercase. When I corrected it to `NUM_NEURONS`, I got the 'broken' one which triggers this compiler panic:

```
error: internal compiler error: src/librustc/dep_graph/graph.rs:610: DepNode Hir(7feb039e5ce2b460-c7bd8dd1a29de264) should have been pre-allocated but wasn't.

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:588:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0-nightly (03acbd71c 2019-01-14) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `neuron-opencl`.

To learn more, run the command again with --verbose.
```

## Meta

`rustc --version --verbose`:
```
rustc 1.33.0-nightly (03acbd71c 2019-01-14)
binary: rustc
commit-hash: 03acbd71c977cd63ce5f39ba9b6fe9ffd578785a
commit-date: 2019-01-14
host: x86_64-apple-darwin
release: 1.33.0-nightly
LLVM version: 8.0
```

Backtrace:

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:588:9
stack backtrace:
   0:        0x113879fd3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1be753e13b79693c
   1:        0x113872d2c - std::sys_common::backtrace::_print::h21830a766329d3ff
   2:        0x113876581 - std::panicking::default_hook::{{closure}}::hfefd778b639ae694
   3:        0x113876287 - std::panicking::default_hook::h39aa21f7c87a1bd3
   4:        0x111ffaf71 - rustc::util::common::panic_hook::h116742de5863eaae
   5:        0x113876de1 - std::panicking::rust_panic_with_hook::hefe388a303cb8993
   6:        0x113452de0 - std::panicking::begin_panic::hadb888776fb9cace
   7:        0x11344e0fd - rustc_errors::Handler::bug::h6f53128992cdfa78
   8:        0x111d19b75 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::hb0275c8cace6f5d9
   9:        0x111d17b49 - rustc::ty::context::tls::with_opt::{{closure}}::h87ee9b533cf44cc0
  10:        0x111d17aa8 - rustc::ty::context::tls::with_context_opt::h2c4224c1de372b60
  11:        0x111d17b01 - rustc::ty::context::tls::with_opt::hce6e9dba2226af16
  12:        0x111d19a84 - rustc::util::bug::opt_span_bug_fmt::h0b581b00f9dc8276
  13:        0x111d199d1 - rustc::util::bug::bug_fmt::h02169a3e5fc3d2da
  14:        0x111c3b486 - rustc::dep_graph::graph::DepGraph::try_mark_green::hc13ba537e552a0db
  15:        0x111eab376 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query::h80c83855cca9131f
  16:        0x1104b7091 - rustc::session::Session::track_errors::h12f76ef9d99a3dec
  17:        0x11029d569 - rustc::util::common::time::h24e655a92529c503
  18:        0x1104db6ec - rustc_typeck::check_crate::h632c71f2e5fe5282
  19:        0x10f9803cb - <std::thread::local::LocalKey<T>>::with::hb5d387e4b6249b54
  20:        0x10f91ce8c - rustc::ty::context::TyCtxt::create_and_enter::hbe66d1bdf790f97c
  21:        0x10f95a70c - rustc_driver::driver::compile_input::h2ff41dfe06205d1a
  22:        0x10f8e3ef1 - <scoped_tls::ScopedKey<T>>::set::hc947be29b765e2e7
  23:        0x10f8eeee8 - rustc_driver::run_compiler::h6a4a6528b29e6e9f
  24:        0x10f8e2b1b - <scoped_tls::ScopedKey<T>>::set::h16f71e71c94d3efa
  25:        0x10f9ad61d - std::sys_common::backtrace::__rust_begin_short_backtrace::hca6bd88909f3a39e
  26:        0x11388681e - __rust_maybe_catch_panic
  27:        0x10f9b568d - <F as alloc::boxed::FnBox<A>>::call_box::hd8bad3d9b4b2371e
  28:        0x11388577b - std::sys::unix::thread::Thread::new::thread_start::hc1f19dfe8b570103
  29:     0x7fff7e6af304 - _pthread_body
  30:     0x7fff7e6b226e - _pthread_start
query stack during panic:
end of query stack
```

**Comment by Zoxc** [comment]
This is fixed on rustc 1.34.0-nightly (e54494727 2019-02-13)
