### ISSUE TITLE
Compiler panic when using generic associated types

### ISSUE THREAD

**Issue by burtonageo** [rust-lang/rust#58467]
The compiler panics when using a [generic associated type](https://github.com/rust-lang/rust/issues/44265) as a bound on a trait requirement's associated type, as shown below.

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ff11dd72cd5efa94c764e5564754c496)

```rust
#![feature(generic_associated_types)]

use std::ops::Deref;

trait SomeTrait {
    type Assoc<T>: Deref<Target = T>;
}

fn main() {
}
```

Backtrace:

```
error: internal compiler error: src/librustc/ty/subst.rs:480: Type parameter `T/#1` (T/1) out of range when substituting (root type=Some(T)) substs=[Self]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:534:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:482
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::span_bug_fmt
  14: <rustc::ty::subst::SubstFolder<'a, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
  15: rustc::ty::subst::Subst::subst
  16: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
  17: rustc::ty::GenericPredicates::instantiate_into
  18: rustc::ty::wf::WfPredicates::nominal_obligations
  19: rustc::ty::wf::WfPredicates::compute_trait_ref
  20: rustc::ty::wf::predicate_obligations
  21: <core::iter::adapters::flatten::FlatMap<I, U, F> as core::iter::traits::iterator::Iterator>::next
  22: rustc_typeck::check::wfcheck::check_where_clauses
  23: rustc::ty::context::GlobalCtxt::enter_local
  24: rustc_typeck::check::wfcheck::check_trait
  25: rustc_typeck::check::wfcheck::check_item_well_formed
  26: rustc::ty::query::__query_compute::check_item_well_formed
  27: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::check_item_well_formed<'tcx>>::compute
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  31: rustc::hir::Crate::visit_all_item_likes
  32: rustc::util::common::time
  33: rustc_typeck::check_crate
  34: <std::thread::local::LocalKey<T>>::with
  35: rustc::ty::context::TyCtxt::create_and_enter
  36: rustc_driver::driver::compile_input
  37: rustc_driver::run_compiler_with_pool
  38: <scoped_tls::ScopedKey<T>>::set
  39: rustc_driver::run_compiler
  40: syntax::with_globals
  41: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:90
  42: <F as alloc::boxed::FnBox<A>>::call_box
  43: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e54494727855cd14229f5d456591ed2a2f027c46/src/liballoc/boxed.rs:744
             at src/libstd/sys_common/thread.rs:14
             at src/libstd/sys/unix/thread.rs:81
  44: start_thread
  45: __clone
query stack during panic:
#0 [check_item_well_formed] processing `SomeTrait`
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.0-nightly (e54494727 2019-02-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.
```

**Comment by varkor** [comment]
The warning when using `generic_associated_types` feature is not misleading:
```
warning: the feature `generic_associated_types` is incomplete and may cause the compiler to crash
```
GATs are not actually implemented and as such, instances like this are expected. I think we've been closing issues regarding GATs until they're at a point when they need testing.
