### ISSUE TITLE
Compiler unepectedly paniced

### ISSUE THREAD

**Issue by FoseFx** [rust-lang/rust#58532]
## short summary of the bug

I tried to compile  this code:

## code sample that causes the bug
```

#[derive(Debug)]
enum NodeOrNull<T> {
    Node(Node<T>),
    Null
}

#[derive(Debug)]
struct Node<T> {
    value: T,
    lower_equal: NodeOrNull<T>,
    higher: NodeOrNull<T>
}

impl<T> Node<T> {
    fn new(val: T) -> Self {
        return Node {value: val, higher: NodeOrNull::Null, lower_equal: NodeOrNull::Null};
    }
}

#[derive(Debug)]
struct Sort<T> {
    root: NodeOrNull<T>
}
impl<T> Sort<T> {
    fn new() -> Self {
        return Sort { root: NodeOrNull::Null };
    }
    fn of(val: Node<T>) -> Self {
        return Sort { root: val };
    }
    
}


fn main() {
    let root = Node::new(5);
    let sort = Sort::of(root);
    println!("{:#?}", sort);
}
```

## I expected to see this happen:
It should compile.

Instead, this happened:
`error: internal compiler error: unexpected panic`

## Meta

`rustc --version --verbose`:
```
rustc 1.32.0 (9fda7c223 2019-01-16)
binary: rustc
commit-hash: 9fda7c2237db910e41d6a712e9a2139b352e558b
commit-date: 2019-01-16
host: x86_64-unknown-linux-gnu
release: 1.32.0
LLVM version: 8.0

```

Backtrace:
```
thread 'main' panicked at 'did not find a cycle', src/librustc/ty/query/job.rs:146:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:495
   6: std::panicking::begin_panic
   7: rustc::ty::query::job::QueryJob::await
   8: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query
   9: rustc::ty::AdtDef::sized_constraint
  10: rustc::ty::AdtDef::sized_constraint_for_ty
  11: <core::iter::FlatMap<I, U, F> as core::iter::iterator::Iterator>::next
  12: <smallvec::SmallVec<A> as core::iter::traits::FromIterator<<A as smallvec::Array>::Item>>::from_iter
  13: <T as rustc::ty::context::InternIteratorElement<T, R>>::intern_with
  14: rustc::ty::adt_sized_constraint
  15: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::adt_sized_constraint<'tcx>>::compute
  16: rustc::ty::context::tls::with_context
  17: rustc::dep_graph::graph::DepGraph::with_task_impl
  18: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  19: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query
  21: rustc::ty::query::plumbing::force_from_dep_node
  22: rustc::dep_graph::graph::DepGraph::try_mark_green
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_mark_green_and_read
  24: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query
  25: rustc::ty::AdtDef::sized_constraint
  26: rustc::traits::select::SelectionContext::sized_conditions
  27: rustc::traits::select::SelectionContext::assemble_candidates
  28: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  29: rustc::ty::context::tls::with_context
  30: rustc::traits::select::SelectionContext::candidate_from_obligation
  31: rustc::traits::select::SelectionContext::select
  32: <rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
  33: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_where_possible
  34: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_all_or_error
  35: rustc_typeck::check::FnCtxt::select_all_obligations_or_error
  36: rustc::ty::context::tls::with_related_context
  37: rustc::infer::InferCtxtBuilder::enter
  38: rustc_typeck::check::wfcheck::check_item_well_formed
  39: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::check_item_well_formed<'tcx>>::compute
  40: rustc::ty::context::tls::with_context
  41: rustc::dep_graph::graph::DepGraph::with_task_impl
  42: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  43: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  46: rustc::session::Session::track_errors
  47: rustc::util::common::time
  48: rustc_typeck::check_crate
  49: rustc::ty::context::tls::enter_context
  50: <std::thread::local::LocalKey<T>>::with
  51: rustc::ty::context::TyCtxt::create_and_enter
  52: rustc_driver::driver::compile_input
  53: rustc_driver::run_compiler_with_pool
  54: <scoped_tls::ScopedKey<T>>::set
  55: rustc_driver::run_compiler
  56: rustc_driver::monitor::{{closure}}
  57: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  58: rustc_driver::run
  59: rustc_driver::main
  60: std::rt::lang_start::{{closure}}
  61: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  62: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  63: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  64: main
  65: __libc_start_main
  66: <unknown>
query stack during panic:
#0 [adt_sized_constraint] processing `NodeOrNull`
#1 [check_item_well_formed] processing `NodeOrNull`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0 (9fda7c223 2019-01-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

**Comment by Centril** [comment]
Hmm; I cannot reproduce this on the playground on stable, beta, nightly, release, debug, ... so it's probably due to other factors such as the flags or such.

Could you try to remove bits and pieces from your code snippet that causes the ICE (Internal Compiler Error) incrementally until you have the smallest possible snippet that still produces the ICE?

**Comment by FoseFx** [comment]
Cannot reproduce anymore, changed nothing.

**Comment by Lonami** [comment]
Is there any reason to keep this open if nobody (including OP) can reproduce it?
