### ISSUE TITLE
IndexError: list index out of range when running `./x.py help`

### ISSUE THREAD

**Issue by Eijebong** [rust-lang/rust#58640]
```
$ ./x.py help
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/home/eijebong/code/rust/src/bootstrap/bootstrap.py", line 833, in main
    sys.argv = sys.argv[:1] + [sys.argv[2], '-h'] + sys.argv[3:]
IndexError: list index out of range
```

**Comment by Centril** [comment]
cc @rust-lang/infra
