### ISSUE TITLE
internal compiler error when evaluate trait associated constants  

### ISSUE THREAD

**Issue by flier** [rust-lang/rust#58944]
<short summary of the bug>

I tried this code:

```rust

pub trait MemoryModel {
    const ALIGNMENT: isize = mem::size_of::<Self::Item>() as isize;
    const ALIGN_MASK: isize = Self::ALIGNMENT - 1;

    type Item;

    unsafe fn fetch<P>(p: *const P) -> Self::Item;

    unsafe fn tail<P>(p: *const P, len: isize) -> Self::Item;
}

pub struct LittenEndianAligned<T>(PhantomData<T>);
pub struct BigEndianAligned<T>(PhantomData<T>);
pub struct LittenEndianUnaligned<T>(PhantomData<T>);
pub struct BigEndianUnaligned<T>(PhantomData<T>);

impl<T> MemoryModel for LittenEndianAligned<T>
where
    T: PrimInt + Zero + WrappingShr,
{
    type Item = T;

    #[inline(always)]
    unsafe fn fetch<P>(p: *const P) -> Self::Item {
        debug_assert!(aligned_to::<Self::Item, _>(p));

        ptr::read(p as *const Self::Item).to_le()
    }

    #[inline(always)]
    unsafe fn tail<P>(p: *const P, tail: isize) -> Self::Item {
        let p = p as *const u8;
        let shift = ((Self::ALIGNMENT - tail) & Self::ALIGN_MASK) << 3;

        Self::fetch(p) & ((!T::zero()).wrapping_shr(shift as u32))
    }
}
```

I expected to see this happen: `ALIGNMENT` can be used as a constant

Instead, this happened: `rustc` crashed at src/librustc_traits/normalize_erasing_regions.rs:43: could not fully normalize `fn() -> usize {std::mem::size_of::<<bits::LittenEndianUnaligned<T> as bits::MemoryModel>::Item>}`

## Meta

`rustc --version --verbose`:
```
rustc 1.33.0 (2aa4c46cf 2019-02-28)
binary: rustc
commit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858
commit-date: 2019-02-28
host: x86_64-apple-darwin
release: 1.33.0
LLVM version: 8.0
```
Backtrace:
```
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:43: could not fully normalize `fn() -> usize {std::mem::size_of::<<bits::LittenEndianUnaligned<T> as bits::MemoryModel>::Item>}`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:588:9
stack backtrace:
   0:        0x10d67f0c3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h9a87463918f2aff9
   1:        0x10d677c8c - std::sys_common::backtrace::_print::h54740e69908f9100
   2:        0x10d67b671 - std::panicking::default_hook::{{closure}}::h519f1fd4b67636f1
   3:        0x10d67b377 - std::panicking::default_hook::h5442e3ae9abda811
   4:        0x10bdf5e21 - rustc::util::common::panic_hook::he77624544de4249c
   5:        0x10d67bed1 - std::panicking::rust_panic_with_hook::h4a3495c63f64f755
   6:        0x10d25cdb0 - std::panicking::begin_panic::h39822d9e7784ad14
   7:        0x10d2580fd - rustc_errors::Handler::bug::h12485ae4ffb29a65
   8:        0x10b98e315 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::hab4de751350b061f
   9:        0x10b98da89 - rustc::ty::context::tls::with_opt::{{closure}}::hf9789a4ca7b4602d
  10:        0x10b98d9e8 - rustc::ty::context::tls::with_context_opt::h31a8f07b2eede9b0
  11:        0x10b98da41 - rustc::ty::context::tls::with_opt::he5de36b9ad0ca1ee
  12:        0x10b98e224 - rustc::util::bug::opt_span_bug_fmt::hc498b6667031b6cf
  13:        0x10b98e171 - rustc::util::bug::bug_fmt::hfd92ab0e6a89baed
  14:        0x109ae4d1a - rustc::ty::context::GlobalCtxt::enter_local::he69b2fd5601780c2
  15:        0x109b00f92 - rustc_traits::normalize_erasing_regions::normalize_ty_after_erasing_regions::heeb9b350e0788a77
  16:        0x10b8fc413 - rustc::ty::query::__query_compute::normalize_ty_after_erasing_regions::h25ba473c2cbb5f91
  17:        0x10bd563b7 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::normalize_ty_after_erasing_regions<'tcx>>::compute::h2797662c3f7cd8ca
  18:        0x10ba109d9 - rustc::dep_graph::graph::DepGraph::with_task_impl::hb4afe1ce8de4db34
  19:        0x10bc30643 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::hcbee305efcaa1bba
  20:        0x10b868ab0 - <rustc::traits::query::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder<'cx, 'tcx> as rustc::ty::fold::TypeFolder<'tcx, 'tcx>>::fold_ty::ha1312668f05af920
  21:        0x10b06474c - <rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::monomorphize::hc675c5aa3dad5bda
  22:        0x10b071f1a - rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::eval_operand::hd23a144388e1cb67
  23:        0x10b07d98f - rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::run::hd94964c3162bbd32
  24:        0x10b198ec0 - rustc_mir::const_eval::eval_body_using_ecx::h85d6c988eb978748
  25:        0x10b19bff9 - rustc_mir::const_eval::const_eval_raw_provider::h55417685e94b25f3
  26:        0x10af572cd - rustc::ty::query::__query_compute::const_eval_raw::h19be9be679663101
  27:        0x10afbe39b - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_eval_raw<'tcx>>::compute::h2a59c05a38c265e5
  28:        0x10b0bf6f8 - rustc::dep_graph::graph::DepGraph::with_task_impl::h78f118fdc8cc0fa2
  29:        0x10afcc1d7 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::h13d8933cc076f6ea
  30:        0x10b065daf - <rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::const_eval_raw::hb87faaa19e0565e4
  31:        0x10b072354 - rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::const_value_to_op::h9c75f03cb319c423
  32:        0x10b1984b3 - rustc_mir::const_eval::lazy_const_to_op::h484daea38f460369
  33:        0x10af1ffb7 - rustc_mir::transform::const_prop::ConstPropagator::eval_constant::hd57a29fdd4fce1a8
  34:        0x10af2124c - <rustc_mir::transform::const_prop::ConstPropagator<'b, 'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_statement::h986e790e34d86c26
  35:        0x10af1faa0 - <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass::h24494d23adcd300d
  36:        0x10aea7399 - rustc_mir::transform::run_passes::{{closure}}::h5a3111ff2f0524f9
  37:        0x10aea7064 - rustc_mir::transform::run_passes::h56d8559c020127f5
  38:        0x10aea865e - rustc_mir::transform::optimized_mir::hcf2ca92db26caa53
  39:        0x10bd54b9e - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::optimized_mir<'tcx>>::compute::ha89834205e788d17
  40:        0x10b9fde33 - rustc::dep_graph::graph::DepGraph::with_task_impl::h7db825d9d5640f5f
  41:        0x10bb9bae0 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::h4fe76f248f0c73dc
  42:        0x10bd51d09 - rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir::hfaed18623f5c04a0
  43:        0x10afaab73 - rustc_mir::monomorphize::collector::collect_items_rec::h09d63daa43236281
  44:        0x10afab738 - rustc_mir::monomorphize::collector::collect_items_rec::h09d63daa43236281
  45:        0x10afab738 - rustc_mir::monomorphize::collector::collect_items_rec::h09d63daa43236281
  46:        0x10b0fbc22 - rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}::h44e232944bf48893
  47:        0x10b0a4640 - rustc::util::common::time::hba68bb23d659cb61
  48:        0x10afa9ea1 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h95202579e2c09fea
  49:        0x10b0a435d - rustc::util::common::time::h5eac0ddf03178ca2
  50:        0x10ae24dd6 - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h574c60a5faaeddd4
  51:        0x1119490b6 - rustc::ty::query::__query_compute::collect_and_partition_mono_items::he71cbabce5543db2
  52:        0x1118f243b - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::collect_and_partition_mono_items<'tcx>>::compute::hd79b96136421cf90
  53:        0x11196564a - rustc::dep_graph::graph::DepGraph::with_task_impl::h510e2ee23e8bda33
  54:        0x111911918 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::h6692a4b37709a446
  55:        0x1118ddd63 - rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local::h3ee26838abeab855
  56:        0x10a7bd0a6 - rustc::ty::query::__query_compute::exported_symbols::he9d400a1100003a3
  57:        0x10a73d6bb - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::exported_symbols<'tcx>>::compute::h81f46efa531ca0bc
  58:        0x10a6b7171 - rustc::dep_graph::graph::DepGraph::with_task_impl::h38d57381fac233c2
  59:        0x10a75a50b - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::h733195fd10b8992c
  60:        0x10a64f7e6 - rustc_metadata::encoder::encode_metadata::h84ffe3d763cf6b0a
  61:        0x10a712f83 - rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata::h512f837a9bf31d98
  62:        0x10bd4066f - rustc::ty::context::TyCtxt::encode_metadata::hed61c5e9bcec2d1d
  63:        0x10e0b562e - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::write_metadata::hf071b6a90ea4f3e1
  64:        0x10e0822b4 - rustc::util::common::time::hee64a61363c606b0
  65:        0x10e12e732 - rustc_codegen_ssa::base::codegen_crate::h84ba208f99852984
  66:        0x10e0b6894 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::h37d480117b8e98f2
  67:        0x10981e916 - rustc::util::common::time::hc536d18472c053d4
  68:        0x10987653f - rustc_driver::driver::phase_4_codegen::h06de4945ae22674c
  69:        0x109848bed - rustc_driver::driver::compile_input::{{closure}}::ha346b7af023ab56d
  70:        0x1098423ee - <std::thread::local::LocalKey<T>>::with::h2d81d3d20e7fbeba
  71:        0x1097d085f - rustc::ty::context::TyCtxt::create_and_enter::hfd77cec70a307209
  72:        0x109870e4f - rustc_driver::driver::compile_input::h0a81d2a90aae52be
  73:        0x1097e151e - rustc_driver::run_compiler_with_pool::h762933062fd399ae
  74:        0x1097ed2ae - <scoped_tls::ScopedKey<T>>::set::hbad459430e7ff417
  75:        0x1097e0488 - rustc_driver::run_compiler::ha1900917d325f169
  76:        0x1097ed46b - <scoped_tls::ScopedKey<T>>::set::hf6e550156f6dc0f3
  77:        0x10984e78d - std::sys_common::backtrace::__rust_begin_short_backtrace::hb4db181f859dd41a
  78:        0x10d68b7ce - __rust_maybe_catch_panic
  79:        0x10986562d - <F as alloc::boxed::FnBox<A>>::call_box::h54bd2886afe0d20a
  80:        0x10d68a71b - std::sys::unix::thread::Thread::new::thread_start::h2ccd51efe09a6d88
  81:     0x7fff78514304 - _pthread_body
  82:     0x7fff7851726e - _pthread_start
query stack during panic:
#0 [normalize_ty_after_erasing_regions] normalizing `ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All, def_id: None }, value: fn() -> usize {std::mem::size_of::<<bits::LittenEndianUnaligned<T> as bits::MemoryModel>::Item>} }`
#1 [const_eval_raw] const-evaluating `bits::MemoryModel::ALIGNMENT`
   --> src/bits.rs:103:22
    |
103 |         let offset = (Self::ALIGNMENT - tail) & Self::ALIGN_MASK;
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^
#2 [optimized_mir] processing `<bits::LittenEndianUnaligned<T> as bits::MemoryModel>::tail`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
#4 [exported_symbols] exported_symbols
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by Centril** [comment]
cc @oli-obk @RalfJung

**Comment by oli-obk** [comment]
Minimal repro:

```rust
pub trait MemoryModel {
    const ALIGNMENT: usize = std::mem::size_of::<Self::Item>();

    type Item;

    unsafe fn tail() -> Self::Item;
}

pub struct LittenEndianAligned<T>(T);

impl<T> MemoryModel for LittenEndianAligned<T> {
    type Item = T;

    unsafe fn tail() -> Self::Item {
        let _ = Self::ALIGNMENT;
        unimplemented!()
    }
}
```

This is already fixed in beta according to the playground.

**Comment by Centril** [comment]
@oli-obk Do we want to add a test case for this or is the existing one enough?

**Comment by oli-obk** [comment]
I have no idea what fixed it. I assume it was an ICE that was fixed, and usually those get a regression test case, too. Not sure if the effort required to pinpoint the fix-PR is worth it

**Comment by Centril** [comment]
My interpretation of what you said is that adding a new test case is unnecessary so I'll go ahead and close the issue for now as resolved.
