### ISSUE TITLE
Unexpected panic in rustc at missing `=` in the `-Z unpretty=` variants

### ISSUE THREAD

**Issue by MacConsoli** [rust-lang/rust#58954]
rustc panics at missing `=` in the argument, as in `-Z unpretty=flowgraph` or `-Z unpretty=flowgraph,unlabelled`.

## Meta
```
$ rustc +nightly --version --verbose
rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)
binary: rustc
commit-hash: a9da8fc9c267c08cfdb8cf5b39da14f154d12939
commit-date: 2019-03-04
host: x86_64-unknown-linux-gnu
release: 1.35.0-nightly
LLVM version: 8.0
```

## Backtrace
```
$ RUST_BACKTRACE=1 rustc +nightly -Z unpretty=flowgraph example.rs
thread 'rustc' panicked at '`pretty flowgraph=..` needs NodeId (int) or unique path suffix (b::c::d)', src/libcore/option.rs:1038:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::option::expect_failed
             at src/libcore/option.rs:1038
  10: <std::thread::local::LocalKey<T>>::with
  11: rustc::ty::context::TyCtxt::create_and_enter
  12: rustc_driver::pretty::print_after_hir_lowering
  13: <rustc_driver::RustcDefaultCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
  14: rustc_driver::driver::compile_input
  15: rustc_driver::run_compiler_with_pool
  16: <scoped_tls::ScopedKey<T>>::set
  17: rustc_driver::run_compiler
  18: syntax::with_globals
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  20: <F as alloc::boxed::FnBox<A>>::call_box
  21: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a9da8fc9c267c08cfdb8cf5b39da14f154d12939/src/liballoc/boxed.rs:759
             at src/libstd/sys_common/thread.rs:14
             at src/libstd/sys/unix/thread.rs:80
  22: start_thread
  23: clone
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (a9da8fc9c 2019-03-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=flowgraph
```
`example.rs`:
```rust
fn main() {
    println!("Hello, World");
}
```
---
An appropriate error is given if there is no `main` function or when used as `rustc +nightly -Z unpretty=flowgraph= example.rs`.

Running `rustc +nightly -Z unpretty=flowgraph,unlabelled example.rs` results in the same panic.

*Expected*: error message and aborting.

**Comment by MacConsoli** [comment]
I'm closing this issue as it seems to be fixed at version `1.40.0-nightly`.
