### ISSUE TITLE
rustc panics documenting sr-api-macros

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [rust-lang/rust#59063]
From https://github.com/paritytech/substrate.git

> matthias@Matthias:~/substrate$ RUST_BACKTRACE=1 cargo doc --open
>    Compiling parity-codec-derive v3.1.0
>    Compiling sr-api-macros v0.1.0 (/home/matthias/substrate/core/sr-api-macros)
>  Documenting sr-api-macros v0.1.0 (/home/matthias/substrate/core/sr-api-macros)
>  Documenting url v1.7.2
>    Compiling vergen v3.0.4
>  Documenting slog-json v2.3.0
>    Compiling rayon v1.0.3
>  Documenting rayon v1.0.3
> error: internal compiler error: src/librustc/hir/def.rs:257: attempted .def_id() on invalid def: NonMacroAttr(Builtin)
> 
> thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:588:9
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> stack backtrace:
>    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
>              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
>    1: std::sys_common::backtrace::_print
>              at src/libstd/sys_common/backtrace.rs:70
>    2: std::panicking::default_hook::{{closure}}
>              at src/libstd/sys_common/backtrace.rs:58
>              at src/libstd/panicking.rs:200
>    3: std::panicking::default_hook
>              at src/libstd/panicking.rs:215
>    4: std::panicking::rust_panic_with_hook
>              at src/libstd/panicking.rs:478
>    5: std::panicking::begin_panic
>    6: rustc_errors::Handler::bug
>    7: rustc::util::bug::opt_span_bug_fmt::{{closure}}
>    8: rustc::ty::context::tls::with_opt::{{closure}}
>    9: rustc::ty::context::tls::with_context_opt
>   10: rustc::ty::context::tls::with_opt
>   11: rustc::util::bug::opt_span_bug_fmt
>   12: rustc::util::bug::bug_fmt
>   13: rustc::hir::def::Def::def_id::{{closure}}
>   14: rustc::hir::def::Def::def_id
>   15: rustdoc::clean::register_def
>              at src/librustdoc/clean/mod.rs:3809
>   16: <rustdoc::doctree::Import as rustdoc::clean::Clean<alloc::vec::Vec<rustdoc::clean::Item>>>::clean
>              at src/librustdoc/clean/mod.rs:3824
>              at src/librustdoc/clean/mod.rs:3586
>   17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
>              at src/librustdoc/clean/mod.rs:591
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/ops/function.rs:279
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/option.rs:414
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/iter/mod.rs:1428
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/iter/mod.rs:2715
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/iter/mod.rs:2552
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/vec.rs:1933
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/vec.rs:1830
>   18: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/vec.rs:1794
>              at src/librustdoc/clean/mod.rs:591
>   19: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
>              at src/librustdoc/clean/mod.rs:597
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/iter/mod.rs:1447
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/slice/mod.rs:2913
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/iter/mod.rs:1447
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/iter/iterator.rs:606
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/vec.rs:1856
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/vec.rs:1794
>              at src/librustdoc/clean/mod.rs:597
>   20: <rustdoc::visit_ast::RustdocVisitor<'a, 'tcx, 'rcx> as rustdoc::clean::Clean<rustdoc::clean::Crate>>::clean
>              at src/librustdoc/clean/mod.rs:162
>   21: rustdoc::core::run_core::{{closure}}::{{closure}}
>              at src/librustdoc/core.rs:547
>   22: <std::thread::local::LocalKey<T>>::with
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc_driver/driver.rs:1332
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1958
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1924
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1857
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1923
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1957
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1912
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/local.rs:299
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/local.rs:245
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1904
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/local.rs:299
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/thread/local.rs:245
>   23: rustc::ty::context::TyCtxt::create_and_enter
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1896
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1935
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc/ty/context.rs:1255
>   24: rustc_driver::driver::phase_3_run_analysis_passes
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc_driver/driver.rs:1229
>   25: <scoped_tls::ScopedKey<T>>::set
>              at src/librustdoc/core.rs:491
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc_driver/driver.rs:65
>              at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
>   26: rustdoc::core::run_core
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/librustc_driver/driver.rs:64
>              at src/librustdoc/core.rs:394
>   27: <scoped_tls::ScopedKey<T>>::set
>              at src/librustdoc/lib.rs:428
>              at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libsyntax/lib.rs:111
>              at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
>   28: syntax::with_globals
>              at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libsyntax/lib.rs:110
> 
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
> 
> note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-unknown-linux-gnu
> 
> error: Could not document `sr-api-macros`.
> 
> Caused by:
>   process didn't exit successfully: `rustdoc --edition=2018 --crate-name sr_api_macros core/sr-api-macros/src/lib.rs --color always -o /home/matthias/substrate/target/doc -L dependency=/home/matthias/substrate/target/debug/deps --extern blake2_rfc=/home/matthias/substrate/target/debug/deps/libblake2_rfc-66a781f937f8fb35.rmeta --extern proc_macro_crate=/home/matthias/substrate/target/debug/deps/libproc_macro_crate-a5315f1e33e73818.rmeta --extern proc_macro2=/home/matthias/substrate/target/debug/deps/libproc_macro2-b7ee48ecc1c6fa1c.rmeta --extern quote=/home/matthias/substrate/target/debug/deps/libquote-fc84fd9546e2fa9b.rmeta --extern syn=/home/matthias/substrate/target/debug/deps/libsyn-5772549f280c3407.rmeta` (exit code: 1)
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by Matthias-Fauconneau** [comment]
My bad. Seems to have been fixed very recently
