### ISSUE TITLE
Test cases fail with 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)'

### ISSUE THREAD

**Issue by lysannef** [rust-lang/rust#59088]
**python x.py test gives the following error:** 
arch: **ppc64le**
environment: **Ubuntu:16.04 docker container** 
```
Testing panic_unwind stage1 (powerpc64le-unknown-linux-gnu -> powerpc64le-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.38s
   Doc-tests panic_unwind
error: no global memory allocator found but one is required; link to std or add #[global_allocator] to a static item that implements the GlobalAlloc trait.


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

        finished in 0.501
Testing std stage1 (powerpc64le-unknown-linux-gnu -> powerpc64le-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.44s
     Running build/powerpc64le-unknown-linux-gnu/stage1-std/powerpc64le-unknown-linux-gnu/release/deps/std-37f26269282899fb

running 762 tests
.................................................................................................... 100/762
.................................................................................................... 200/762
...............................................thread '<unnamed>' panicked at 'explicit panic', src/libstd/io/buffered.rs:1277:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
..thread '<unnamed>' panicked at 'explicit panic', src/libstd/io/buffered.rs:1290:17
.......................................thread '<unnamed>' panicked at 'explicit panic', src/libstd/io/stdio.rs:748:13
............ 300/762
............................................................thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1457:21
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1439:21
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1399:26
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1372:21
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1333:21
F.thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:978:28
F...thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1190:29
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1206:28
F.thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1087:28
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1122:28
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1065:28
F.thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1170:23
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1650:23
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1019:28
F.thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1313:21
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:999:28
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1154:28
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1221:28
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1252:28
Fthread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1286:28
F.....thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/tcp.rs:1038:28
F.thread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:1093:26
F..thread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:1115:26
Fthread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:1147:26
Fthread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:870:26
F 400/762
thread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&server_ip)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:856:26
thread '<unnamed>' panicked at 'Freceived error for `UdpSocket::bind(&client_ip)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:850:30
.....thread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr1)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:878:25
Fthread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr1)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:907:25
Fthread '<unnamed>' panicked at 'received error for `UdpSocket::bind(&addr1)`: Cannot assign requested address (os error 99)', src/libstd/net/udp.rs:939:25
F........................................................................thread '<unnamed>' panicked at 'attempted to use a condition variable with two mutexes', src/libstd/sync/condvar.rs:584:18
................... 500/762
.......................thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:997:5
....thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:997:5
.......thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:997:5
..........................................thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:997:5
....thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:997:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:997:5
.......thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:997:5
............. 600/762
.........................thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/mutex.rs:627:13
..thread '<unnamed>' panicked at 'test panic in inner thread to poison mutex', src/libstd/sync/mutex.rs:582:13
...thread '<unnamed>' panicked at 'test panic in inner thread to poison mutex', src/libstd/sync/mutex.rs:559:13
.thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/mutex.rs:687:13
...thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/libstd/sync/mutex.rs:651:13
...thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/once.rs:572:28
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:362:21
...thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/once.rs:600:28
....thread '<unnamed>' panicked at 'test panic in inner thread to poison RwLock', src/libstd/sync/rwlock.rs:787:13
...thread '<unnamed>' panicked at 'test panic in inner thread to poison RwLock', src/libstd/sync/rwlock.rs:764:13
..thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:701:13
.thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:631:13
.thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:642:13
.thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:607:13
.thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:619:13
.........................thread '<unnamed>' panicked at 'What the answer to my lifetimes dilemma is?', src/libstd/sys_common/remutex.rs:231:13
.....................thread '<unnamed>' panicked at 'index 2 and/or 8 in `"aé 💩"` do not lie on character boundary', src/libstd/sys_common/wtf8.rs:774:5
. 700/762
thread '<unnamed>' panicked at 'index 2 and/or 4 in `"aé 💩"` do not lie on character boundary', src/libstd/sys_common/wtf8.rs:774:5
..thread '<unnamed>' panicked at 'index 5 and/or 8 in `"aé 💩"` do not lie on character boundary', src/libstd/sys_common/wtf8.rs:774:5
..................thread '<unnamed>' panicked at 'assertion failed: is_code_point_boundary(self, new_len)', src/libstd/sys_common/wtf8.rs:319:9
.thread '<unnamed>' panicked at 'assertion failed: is_code_point_boundary(self, new_len)', src/libstd/sys_common/wtf8.rs:319:9
................thread '<unnamed>' panicked at 'explicit panic', src/libstd/thread/mod.rs:1528:13
...........thread '<unnamed>' panicked at 'Box<Any>', src/libstd/thread/mod.rs:1660:13
.thread '<unnamed>' panicked at 'owned string', src/libstd/thread/mod.rs:1646:13
.thread '<unnamed>' panicked at 'static string', src/libstd/thread/mod.rs:1632:13
.thread '<unnamed>' panicked at 'Box<Any>', src/libstd/thread/mod.rs:1678:13
..thread '<unnamed>' panicked at 'specified instant was later than self', src/libstd/sys/unix/time.rs:292:17
..a: Instant { tv_sec: 10540564, tv_nsec: 363235918 }
b: Instant { tv_sec: 10540564, tv_nsec: 363236248 }
dur: 330ns
.......
failures:

failures:
    net::tcp::tests::clone_accept_concurrent
    net::tcp::tests::clone_accept_smoke
    net::tcp::tests::clone_while_reading
    net::tcp::tests::close_read_wakes_up
    net::tcp::tests::close_readwrite_smoke
    net::tcp::tests::connect_loopback
    net::tcp::tests::double_bind
    net::tcp::tests::fast_rebind
    net::tcp::tests::multiple_connect_interleaved_greedy_schedule
    net::tcp::tests::multiple_connect_interleaved_lazy_schedule
    net::tcp::tests::multiple_connect_serial
    net::tcp::tests::partial_read
    net::tcp::tests::peek
    net::tcp::tests::read_eof
    net::tcp::tests::shutdown_smoke
    net::tcp::tests::smoke_test
    net::tcp::tests::socket_and_peer_name
    net::tcp::tests::tcp_clone_smoke
    net::tcp::tests::tcp_clone_two_read
    net::tcp::tests::tcp_clone_two_write
    net::tcp::tests::write_close
    net::udp::tests::connect_send_peek_recv
    net::udp::tests::peek_from
    net::udp::tests::set_nonblocking
    net::udp::tests::socket_name_ip4
    net::udp::tests::socket_smoke_test_ip4
    net::udp::tests::udp_clone_smoke
    net::udp::tests::udp_clone_two_read
    net::udp::tests::udp_clone_two_write

test result: FAILED. 733 passed; 29 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'


command did not execute successfully: "/rust/build/powerpc64le-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "powerpc64le-unknown-linux-gnu" "-j" "3" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "/rust/src/libstd/Cargo.toml" "-p" "std" "--" "--quiet"
expected success, got: exit code: 101


failed to run: /rust/build/bootstrap/debug/bootstrap test
Build completed unsuccessfully in 0:28:17
```

Executing the command : 

"/rust/build/powerpc64le-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "powerpc64le-unknown-linux-gnu" "-j" "3" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "/rust/src/libstd/Cargo.toml" "-p" "std" "--" "--quiet"

Get the following output:
```
error: failed to parse manifest at `/rust/src/tools/miri/Cargo.toml`

Caused by:
  the cargo feature `default-run` requires a nightly version of Cargo, but this is the `stable` channel
```

**Comment by lysannef** [comment]
Thank you @parched , the work around helped , and it does not give the bind address error anymore. 
Thanks for the heads up on debug info tests too.
