### ISSUE TITLE
using 'cargo install xsv' on windows 10 triggers rustc internal error

### ISSUE THREAD

**Issue by GuoXu-GX** [rust-lang/rust#59392]
rustc panics when using 'cargo install xsv' on windows 10:

```
vc toolchain: 
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.3
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

error command line and output:
=========
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>cargo install xsv
    Updating crates.io index
  Installing xsv v0.13.0
   Compiling proc-macro2 v0.4.27
   Compiling libc v0.2.50
   Compiling winapi v0.3.6
   Compiling memchr v2.2.0
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.29
   Compiling serde v1.0.89
   Compiling num-traits v0.2.6
   Compiling lazy_static v1.3.0
   Compiling byteorder v1.3.1
   Compiling regex v1.1.2
   Compiling ucd-util v0.1.3
   Compiling utf8-ranges v1.0.2
   Compiling strsim v0.7.0
   Compiling cfg-if v0.1.7
   Compiling unicode-width v0.1.5
   Compiling thread_local v0.3.6
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: Other, message: "函数不正确。" }', src\libcore\result.rs:997:5
   Compiling regex-syntax v0.6.5
stack backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: rustc::ty::trait_def::TraitDef::ancestors
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: rustc_metadata::creader::CrateLoader::maybe_process_path_extern
   9: rustc_metadata::locator::Context::report_errs
  10: rustc_metadata::locator::Context::maybe_load_library_crate
  11: rustc_metadata::creader::CrateLoader::new
  12: rustc_metadata::creader::CrateLoader::new
  13: rustc_metadata::creader::CrateLoader::process_extern_crate
  14: rustc_resolve::build_reduced_graph::<impl rustc_resolve::ToNameBinding<'a> for (&'a rustc_resolve::ModuleData<'a>, rustc::ty::Visibility, syntax_pos::span_encoding::Span, syntax_pos::hygiene::Mark)>::to_name_binding
  15: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  16: <rustc_resolve::macros::<impl rustc_resolve::Resolver<'a>>::early_resolve_ident_in_lexical_scope::Flags as core::fmt::UpperHex>::fmt
  17: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  18: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_ty
  19: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_ast_fragment_with_placeholders
  20: syntax::ext::expand::MacroExpander::expand_crate
  21: syntax::ext::expand::MacroExpander::expand_crate
  22: syntax::ext::expand::MacroExpander::expand_crate
  23: rustc_driver::profile::trace::write_style
  24: rustc_driver::profile::dump
  25: rustc_driver::driver::count_nodes
  26: rustc_driver::driver::compile_input
  27: rustc_driver::run_compiler
  28: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  29: rustc_driver::run_compiler
  30: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  31: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  32: _rust_maybe_catch_panic
  33: <humantime::date::Error as std::error::Error>::cause
  34: std::sys::windows::thread::Thread::new
  35: BaseThreadInitThunk
  36: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `thread_local`.
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: Other, message: "函数不正确。" }', src\libcore\result.rs:997:5
stack backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: rustc::ty::trait_def::TraitDef::ancestors
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: rustc_metadata::creader::CrateLoader::maybe_process_path_extern
   9: rustc_metadata::locator::Context::report_errs
  10: rustc_metadata::locator::Context::maybe_load_library_crate
  11: rustc_metadata::creader::CrateLoader::new
  12: rustc_metadata::creader::CrateLoader::new
  13: rustc_metadata::creader::CrateLoader::process_extern_crate
  14: rustc_resolve::build_reduced_graph::<impl rustc_resolve::ToNameBinding<'a> for (&'a rustc_resolve::ModuleData<'a>, rustc::ty::Visibility, syntax_pos::span_encoding::Span, syntax_pos::hygiene::Mark)>::to_name_binding
  15: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  16: <rustc_resolve::macros::<impl rustc_resolve::Resolver<'a>>::early_resolve_ident_in_lexical_scope::Flags as core::fmt::UpperHex>::fmt
  17: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_item
  18: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit::Visitor<'a>>::visit_ty
  19: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_ast_fragment_with_placeholders
  20: syntax::ext::expand::MacroExpander::expand_crate
  21: syntax::ext::expand::MacroExpander::expand_crate
  22: syntax::ext::expand::MacroExpander::expand_crate
  23: rustc_driver::profile::trace::write_style
  24: rustc_driver::profile::dump
  25: rustc_driver::driver::count_nodes
  26: rustc_driver::driver::compile_input
  27: rustc_driver::run_compiler
  28: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  29: rustc_driver::run_compiler
  30: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  31: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  32: _rust_maybe_catch_panic
  33: <humantime::date::Error as std::error::Error>::cause
  34: std::sys::windows::thread::Thread::new
  35: BaseThreadInitThunk
  36: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `regex-syntax`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `xsv v0.13.0`, intermediate artifacts can be found at `R:\Temp\cargo-install3sJ2BW`

Caused by:
  build failed
=========

.rustc_info.json in intermediate artifacts directory:
=========
{"rustc_fingerprint":3745648978097277157,"outputs":{"1617349019360157463":["___.exe\nlib___.rlib\n___.dll\n___.dll\n___.lib\n___.dll\nC:\\Users\\Leonhard\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\ndebug_assertions\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"msvc\"\ntarget_family=\"windows\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_os=\"windows\"\ntarget_pointer_width=\"64\"\ntarget_vendor=\"pc\"\nwindows\n",""],"1464629490410732173":["___.exe\nlib___.rlib\n___.dll\n___.dll\n___.lib\n___.dll\nC:\\Users\\Leonhard\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\ndebug_assertions\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"msvc\"\ntarget_family=\"windows\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_os=\"windows\"\ntarget_pointer_width=\"64\"\ntarget_vendor=\"pc\"\nwindows\n",""],"1164083562126845933":["rustc 1.33.0 (2aa4c46cf 2019-02-28)\nbinary: rustc\ncommit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858\ncommit-date: 2019-02-28\nhost: x86_64-pc-windows-msvc\nrelease: 1.33.0\nLLVM version: 8.0\n",""]},"successes":{}}
=========
```

**Comment by estebank** [comment]
函数不正确。seems to translate to "The function is incorrect."

**Comment by retep998** [comment]
What sort of disk is `R:\`? Is it a network drive, a ram disk, or a normal HDD/SSD?

**Comment by GuoXu-GX** [comment]
> 
> 
> What sort of disk is `R:\`? Is it a network drive, a ram disk, or a normal HDD/SSD?

a ram disk, sized about 4GB

**Comment by retep998** [comment]
I suspect this is the ram disk not supporting the canonicalize operation that rustc insists on performing. https://github.com/rust-lang/rust/issues/59117

As a workaround, you can change your temporary directory to be on a normal HDD/SSD.

**Comment by GuoXu-GX** [comment]
> 
> 
> I suspect this is the ram disk not supporting the canonicalize operation that rustc insists on performing. #59117
> 
> As a workaround, you can change your temporary directory to be on a normal HDD/SSD.

it seems this could work around the issue, thanks

**Comment by Enselic** [comment]
Triage: This is about problems canonicalizing paths on RAM drives. So is #48249, so closing as duplicate.
