### ISSUE TITLE
Compiler panic for `error: lifetime parameters must be declared prior to type parameters`

### ISSUE THREAD

**Issue by mikrostew** [rust-lang/rust#59495]
I found a compiler panic, which has a similar error message to #39239, but it looks like a different issue.

I expect to get an error for this because my code is wrong, but I did not expect a panic in the middle of the error.

## Minimal Repro

This code panics:

```rust
struct A;

impl A {
    pub fn do_things<T, 'a, 'b: 'a>() {
        println!("panic");
    }
}
```

This is the error:

```
error: lifetime parameters must be declared prior to type parameters
 --> src/main.rs:4:25
  |
4 |     pub fn do_things<T, 'a, 'b: 'a>() {
  |                         ^^      ^^
thread 'rustc' panicked at 'begin <= end (28 <= 26) when slicing `    pub fn do_things<T, 'a, 'b: 'a>() {`', src/libcore/str/mod.rs:2089:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin
```

## Environment

I'm running 1.33 stable:

```
$ rustc --version --verbose
rustc 1.33.0 (2aa4c46cf 2019-02-28)
binary: rustc
commit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858
commit-date: 2019-02-28
host: x86_64-apple-darwin
release: 1.33.0
LLVM version: 8.0
```

## Backtrace:

```
$ RUST_BACKTRACE=1 cargo build
   Compiling panic v0.1.0 (/Users/mistewar/repro/panic)
error: lifetime parameters must be declared prior to type parameters
 --> src/main.rs:4:25
  |
4 |     pub fn do_things<T, 'a, 'b: 'a>() {
  |                         ^^      ^^
thread 'rustc' panicked at 'begin <= end (28 <= 26) when slicing `    pub fn do_things<T, 'a, 'b: 'a>() {`', src/libcore/str/mod.rs:2089:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::str::slice_error_fail
   9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
  10: rustc_errors::CodeSuggestion::splice_lines::push_trailing
  11: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::fold
  12: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  13: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit
  14: rustc_errors::Handler::emit_db
  15: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  16: syntax::parse::parser::Parser::parse_generic_params
  17: syntax::parse::parser::Parser::parse_generics
  18: syntax::parse::parser::Parser::parse_impl_item
  19: syntax::parse::parser::Parser::parse_item_implementation
  20: syntax::parse::parser::Parser::parse_item_
  21: syntax::parse::parser::Parser::parse_item
  22: syntax::parse::parser::Parser::parse_mod_items
  23: syntax::parse::parser::Parser::parse_crate_mod
  24: syntax::parse::parse_crate_from_file
  25: rustc_driver::driver::phase_1_parse_input::{{closure}}
  26: rustc::util::common::time
  27: rustc_driver::driver::phase_1_parse_input
  28: rustc_driver::driver::compile_input
  29: rustc_driver::run_compiler_with_pool
  30: <scoped_tls::ScopedKey<T>>::set
  31: rustc_driver::run_compiler
  32: <scoped_tls::ScopedKey<T>>::set

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0 (2aa4c46cf 2019-02-28) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `panic`.
```

**Comment by varkor** [comment]
This just affects stable: on beta and nightly, this doesn't ICE.

**Comment by jonas-schievink** [comment]
Indeed, fixed on beta and nightly, so closing.
