### ISSUE TITLE
x.py should indicate status code of failed commands

### ISSUE THREAD

**Issue by federicomenaquintero** [rust-lang/rust#59541]
x.py's `run()` function just prints `failed to run: $command_name` when something fails, but it doesn't say why it failed, which makes debugging builds harder.

At Suse we just ran into the following.  In trying to bootstrap Rust 1.33, it turned out that the prebuilt compiler and cargo for 1.32 are probably broken for ppc64le.  Running `cargo` from the prebuilt binaries immediately causes it to die with `Illegal instruction`.  I have to do some digging to see what's going on there, but in the meantime, x.py only printed this:

```
[  123s] + ./x.py build -v
[  124s] running: /home/abuild/rpmbuild/BUILD/rust-1.32.0-powerpc64le-unknown-linux-gnu/usr/bin/cargo build --manifest-path /home/abuild/rpmbuild/BUILD/rustc-1.33.0-src/src/bootstrap/Cargo.toml --frozen
[  124s] Traceback (most recent call last):
[  124s]   File "./x.py", line 11, in <module>
[  124s]     bootstrap.main()
[  124s]   File "/home/abuild/rpmbuild/BUILD/rustc-1.33.0-src/src/bootstrap/bootstrap.py", line 843, in main
[  124s]     bootstrap(help_triggered)
[  124s]   File "/home/abuild/rpmbuild/BUILD/rustc-1.33.0-src/src/bootstrap/bootstrap.py", line 814, in bootstrap
[  124s]     build.build_bootstrap()
[  124s]   File "/home/abuild/rpmbuild/BUILD/rustc-1.33.0-src/src/bootstrap/bootstrap.py", line 642, in build_bootstrap
[  124s]     run(args, env=env, verbose=self.verbose)
[  124s]   File "/home/abuild/rpmbuild/BUILD/rustc-1.33.0-src/src/bootstrap/bootstrap.py", line 141, in run
[  124s]     raise RuntimeError(err)
[  124s] RuntimeError: failed to run: /home/abuild/rpmbuild/BUILD/rust-1.32.0-powerpc64le-unknown-linux-gnu/usr/bin/cargo build --manifest-path /home/abuild/rpmbuild/BUILD/rustc-1.33.0-src/src/bootstrap/Cargo.toml --frozen
[  124s] error: Bad exit status from /var/tmp/rpm-tmp.jaylIJ (%build)
[  124s] 
[  124s] 
[  124s] RPM build errors:
[  124s]     Bad exit status from /var/tmp/rpm-tmp.jaylIJ (%build)
```

This is not rpmbuild eating output or anything; running x.py by hand does the same thing.  I had to actually paste the `cargo` command line into a chroot inside the buildroot to be able to know that it had died due to an Illegal Instruction.

**Comment by federicomenaquintero** [comment]
To be honest I haven't checked :)  After the builds got fixed, I've never run into errors inside x.py.
