### ISSUE TITLE
error: internal compiler error: unexpected region in query response: `ReScope(Destruction(219))`

### ISSUE THREAD

**Issue by RyanBluth** [rust-lang/rust#60127]
I went through the process of updating one of my projects from actix-web 0.7 to 1.0 and ran into a compiler bug. I'm not sure what is causing the issue because I had to change a lot of code to get to this point. Cargo check passes but cargo run produces the provided backtrace.

Here is a link to the project that produces the issue:
[Source Code](https://drive.google.com/file/d/1sBL-0vEzo6jlA_-gHuLXfbZ4orQSiVAz/view?usp=sharing)

## Meta

rustc 1.34.0 (91856ed52 2019-04-10)
binary: rustc
commit-hash: 91856ed52c58aa5ba66a015354d1cc69e9779bdf
commit-date: 2019-04-10
host: x86_64-unknown-linux-gnu
release: 1.34.0
LLVM version: 8.0

Backtrace: 
```
error: internal compiler error: unexpected region in query response: `ReScope(Destruction(219))`

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:354:17
stack backtrace:
   0:     0x7f23cd2fde53 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd71462e61ec5c76e
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x7f23cd2f655b - std::sys_common::backtrace::_print::hae2106692f421f30
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x7f23cd2fa0b6 - std::panicking::default_hook::{{closure}}::h4e372307f318ae92
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x7f23cd2f9e34 - std::panicking::default_hook::hb6f777c87029e950
                               at src/libstd/panicking.rs:215
   4:     0x7f23c948206f - rustc::util::common::panic_hook::h75e82952bcc200c3
   5:     0x7f23cd2fa8a8 - std::panicking::rust_panic_with_hook::h49d43efebcb63d45
                               at src/libstd/panicking.rs:482
   6:     0x7f23c8218184 - std::panicking::begin_panic::h6ebe56746cc56638
   7:     0x7f23c82345f4 - <rustc_errors::Handler as core::ops::drop::Drop>::drop::hef827629e4ce9ecc
   8:     0x7f23cd6c2651 - core::ptr::real_drop_in_place::hcc2b600d1fae643c
   9:     0x7f23cd6c4230 - core::ptr::real_drop_in_place::hf3f5d5902e82ca0d
  10:     0x7f23cd6c4b53 - core::ptr::real_drop_in_place::hfc487cb4d89cbd7e
  11:     0x7f23cd6c9c44 - syntax::with_globals::hb84a324ec1ebdbc3
  12:     0x7f23cd30bb19 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  13:     0x7f23cd708f70 - <F as alloc::boxed::FnBox<A>>::call_box::h91432f0e06b88aa0
  14:     0x7f23cd30a85d - std::sys::unix::thread::Thread::new::thread_start::hb4e0e015a1494c74
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:759
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:81
  15:     0x7f23cd257163 - start_thread
  16:     0x7f23cd16ddee - __clone
  17:                0x0 - <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.0 (91856ed52 2019-04-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `icebreaker_server`.

```

**Comment by hellow554** [comment]
One quick note: This is GitHub. It is meant for sharing code, but yet you share your code via google drive? :|

**Comment by RyanBluth** [comment]
Sorry, it's a private project on gitlab. There's not a lot there yet so I didn't mind posting the code here as a zip file. If anyone needs access via gitlab to look into this I'd be happy to provide it

**Comment by hellow554** [comment]
You could have created a new repo at GitHub/GitLab ;) As said, thanks again!

**Comment by nikomatsakis** [comment]
It seems like what we really need here is to reduce this to a smaller, standalone test case -- or at minimum to bisect the failure to a particular PR, perhaps using https://github.com/rust-lang-nursery/cargo-bisect-rustc.

**Comment by hellow554** [comment]
Sadly I haden't time yet to look into it :| If somebody comes up with a MCVE I will happily bisect it

**Comment by RyanBluth** [comment]
Would seeing the diff between the working code and failing code help at all?

**Comment by lqd** [comment]
Looks related to #57464 ? (which @pnkfelix is working on)
