### ISSUE TITLE
thread 'main' panicked at 'internal error: entered unreachable code', src/tools/tidy/src/pal.rs:224:9

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#60505]
Adding some `#[cfg()]` with unbalanced parens in some file in the rust directory makes `python x.py build` fail with the following error and backtrace:
```
thread 'main' panicked at 'internal error: entered unreachable code', src/tools/tidy/src/pal.rs:224:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
   8: tidy::pal::check::{{closure}}
   9: tidy::walk
  10: tidy::walk
  11: tidy::pal::check
  12: tidy::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: main
  18: __libc_start_main
  19: _start
```

Which is rather unhelpful.

**Comment by hellow554** [comment]
Looking at 

https://github.com/rust-lang/rust/blob/08bfe16129b0621bc90184f8704523d4929695ef/src/tools/tidy/src/pal.rs#L206-L225

means, that `unreachable` should be 
```
panic!("An uneven amount of `(` and `)` has been discovered")
```
(or similar)

**Comment by varkor** [comment]
Rather than panicking, it would be better to throw an error (e.g. using `tidy_error!`).

**Comment by glandium** [comment]
Note that there are other cases where there is an error message like:
```
    |
207 | #[cfg(not(stage0)]
    |  -   -           ^ incorrect close delimiter
    |  |   |
    |  |   un-closed delimiter
    |  close delimiter possibly meant for this
```

It seems like we should get the same here too.

**Comment by varkor** [comment]
We could just ignore `#[cfg]`s with unbalanced parentheses in tidy, as they'll be picked up during compilation. In that case, removing the `unreachable!()` and adding a comment to that effect should be enough.
