### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by woody77** [rust-lang/rust#60621]
Ran into a compiler panic while refactoring a function from returning an Option<T> to a Result<T, E>.

In a file full of unit tests with (expected) compilation failures on lines like:
`assert_eq!( [fn that returns Result::Err], None);`

I changed one line over to:
`assert_eq!( [fn that returns Result::Err), Err);`

And got the following panic.

I'll see if I can make a smaller reproduction case.

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::panicking::panic
             at src/libcore/panicking.rs:49
  10: rustc_typeck::check::has_typeck_tables
  11: rustc::ty::query::__query_compute::has_typeck_tables
  12: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::has_typeck_tables>::compute
  13: rustc::dep_graph::graph::DepGraph::with_task_impl
  14: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  15: rustc_typeck::check::op::<impl rustc_typeck::check::FnCtxt>::add_type_neq_err_label
  16: rustc_typeck::check::op::<impl rustc_typeck::check::FnCtxt>::check_overloaded_binop
  17: rustc_typeck::check::op::<impl rustc_typeck::check::FnCtxt>::check_binop
  18: rustc_typeck::check::FnCtxt::check_expr_kind
  19: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  20: rustc_typeck::check::FnCtxt::check_expr_kind
  21: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  22: rustc_typeck::check::FnCtxt::check_expr_meets_expectation_or_error
  23: rustc_typeck::check::FnCtxt::check_expr_kind
  24: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  25: rustc_typeck::check::FnCtxt::check_block_with_expected
  26: rustc_typeck::check::FnCtxt::check_expr_kind
  27: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  28: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  29: rustc_typeck::check::FnCtxt::check_expr_kind
  30: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  31: rustc_typeck::check::FnCtxt::check_block_with_expected
  32: rustc_typeck::check::FnCtxt::check_expr_kind
  33: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  34: rustc_typeck::check::FnCtxt::check_stmt
  35: rustc_typeck::check::FnCtxt::check_block_with_expected
  36: rustc_typeck::check::FnCtxt::check_expr_kind
  37: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  38: rustc_typeck::check::FnCtxt::check_return_expr
  39: rustc_typeck::check::check_fn
  40: rustc::ty::context::GlobalCtxt::enter_local
  41: rustc_typeck::check::typeck_tables_of
  42: rustc::ty::query::__query_compute::typeck_tables_of
  43: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  44: rustc::dep_graph::graph::DepGraph::with_task_impl
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  46: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  47: rustc_typeck::check::typeck_item_bodies
  48: rustc::ty::query::__query_compute::typeck_item_bodies
  49: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_item_bodies>::compute
  50: rustc::dep_graph::graph::DepGraph::with_task_impl
  51: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  52: rustc::util::common::time
  53: rustc_typeck::check_crate
  54: rustc_interface::passes::analysis
  55: rustc::ty::query::__query_compute::analysis
  56: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  57: rustc::dep_graph::graph::DepGraph::with_task_impl
  58: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  59: rustc::ty::context::tls::enter_global
  60: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  61: rustc_interface::passes::create_global_ctxt::{{closure}}
  62: rustc_interface::interface::run_compiler_in_existing_thread_pool
  63: std::thread::local::LocalKey<T>::with
  64: scoped_tls::ScopedKey<T>::set
  65: syntax::with_globals
query stack during panic:
#0 [has_typeck_tables] processing `std::prelude::v1::Err`
#1 [typeck_tables_of] processing `install_plan::tests::test_invalid_uri`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0369`.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (3991285f5 2019-04-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z allow-features=async_await,await_macro,futures_api -C opt-level=0 -C debuginfo=2 -C link-arg=--pack-dyn-relocs=relr -C link-arg=--sysroot=/usr/local/google/home/aaronwood/development/goma/fuchsia/out/default/sdk/exported/zircon_sysroot/arch/x64/sysroot -C link-arg=-L/usr/local/google/home/aaronwood/development/goma/fuchsia/out/default/sdk/exported/zircon_sysroot/arch/x64/sysroot/lib -C link-arg=-L/usr/local/google/home/aaronwood/development/goma/fuchsia/buildtools/linux-x64/clang/lib/clang/9.0.0/x86_64-fuchsia/lib -C link-arg=--threads -C link-arg=-dynamic-linker=ld.so.1 --crate-type bin
```

**Comment by woody77** [comment]
@cramertj

**Comment by hellow554** [comment]
Has maybe something to do with incremental compiling? Try chaning the signature back and forth and look if the error still occurs

**Comment by woody77** [comment]
Unfortunately, I now can't get it to reproduce (and I needed to make progress).  I _think_ I can get back to that state in the source code, and see if it reproduces on the same input again.

**Comment by nikomatsakis** [comment]
Hmm, this *sounds* like some kind of incremental bug. Unfortunately, there isn't really enough information here to be actionable, so I'm going to close the issue for now. @woody77, thanks for the bug report, and if you are able to reproduce or you see the problem again, please feel free to re-open the issue. Thanks. ❤️
