### ISSUE TITLE
bootstrap fails on powerpc64le-unknown-linux-musl (stage1 std rustc sigsegv for `alloc`)

### ISSUE THREAD

**Issue by q66** [rust-lang/rust#61182]
When trying to bootstrap natively on `powerpc64le-unknown-linux-musl`, rustc segfaults when compiling stage1 std artifacts:

```
Building stage1 std artifacts (powerpc64le-unknown-linux-musl -> powerpc64le-unknown-linux-musl)
running: "/builddir/rustc-1.35.0-src/prebuilt/bin/cargo" "build" "--target" "powerpc64le-unknown-linux-musl" "-j" "72" "--release" "--frozen" "--features" "panic-unwind backtrace" "--manifest-path" "/builddir/rustc-1.35.0-src/src/libstd/Cargo.toml" "--message-format" "json"
   Compiling cc v1.0.28
   Compiling core v0.0.0 (/builddir/rustc-1.35.0-src/src/libcore)
   Compiling libc v0.2.51
   Compiling unwind v0.0.0 (/builddir/rustc-1.35.0-src/src/libunwind)
   Compiling compiler_builtins v0.1.9
   Compiling backtrace-sys v0.1.27
   Compiling std v0.0.0 (/builddir/rustc-1.35.0-src/src/libstd)
   Compiling rustc-std-workspace-core v1.0.0 (/builddir/rustc-1.35.0-src/src/tools/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/builddir/rustc-1.35.0-src/src/liballoc)
   Compiling panic_abort v0.0.0 (/builddir/rustc-1.35.0-src/src/libpanic_abort)
   Compiling rustc-demangle v0.1.10
error: Could not compile `alloc`.

Caused by:
  process didn't exit successfully: `/builddir/rustc-1.35.0-src/build/bootstrap/debug/rustc --edition=2018 --crate-name alloc src/liballoc/lib.rs --color never --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=f6536ad6454e1a0f -C extra-filename=-f6536ad6454e1a0f --out-dir /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1-std/powerpc64le-unknown-linux-musl/release/deps --target powerpc64le-unknown-linux-musl -L dependency=/builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1-std/powerpc64le-unknown-linux-musl/release/deps -L dependency=/builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1-std/release/deps --extern compiler_builtins=/builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1-std/powerpc64le-unknown-linux-musl/release/deps/libcompiler_builtins-7fc2bd91898850dc.rlib --extern core=/builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1-std/powerpc64le-unknown-linux-musl/release/deps/libcore-821d71ff6e8bc869.rlib -C linker=cc -L native=/builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1-std/powerpc64le-unknown-linux-musl/release/build/compiler_builtins-4678d9d6beb9ca77/out` (signal: 11, SIGSEGV: invalid memory reference)
command did not execute successfully: "/builddir/rustc-1.35.0-src/prebuilt/bin/cargo" "build" "--target" "powerpc64le-unknown-linux-musl" "-j" "72" "--release" "--frozen" "--features" "panic-unwind backtrace" "--manifest-path" "/builddir/rustc-1.35.0-src/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
Traceback (most recent call last):
  File "/builddir/rustc-1.35.0-src/src/bootstrap/bootstrap.py", line 859, in <module>
    main()
  File "/builddir/rustc-1.35.0-src/src/bootstrap/bootstrap.py", line 842, in main
    bootstrap(help_triggered)
  File "/builddir/rustc-1.35.0-src/src/bootstrap/bootstrap.py", line 828, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/builddir/rustc-1.35.0-src/src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /builddir/rustc-1.35.0-src/build/bootstrap/debug/bootstrap dist -v
make: *** [Makefile:60: dist] Error 1
```

Enabling debuginfo and getting a coredump reveals this backtrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x000070d4b46793a0 in syntax_pos::<impl core::fmt::Debug for syntax_pos::span_encoding::Span>::fmt () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/libsyntax_pos-d7af1be421a84ca1.so
#2  0x000070d4b6ce30d4 in core::fmt::write (output=..., args=...) at src/libcore/fmt/mod.rs:1016
#3  0x000070d4b526d0b8 in rustc::ty::print::pretty::PrettyPrinter::pretty_print_type () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc-c34e8f271e128c49.so
#4  0x000070d4b54bdab4 in rustc::ty::print::pretty::<impl core::fmt::Display for &rustc::ty::TyS>::fmt () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc-c34e8f271e128c49.so
#5  0x000070d4b6ce30d4 in core::fmt::write (output=..., args=...) at src/libcore/fmt/mod.rs:1016
#6  0x000070d4b6cb99e0 in core::fmt::Write::write_fmt (self=0xe20320709e0, args=...) at /builddir/rustc-1.35.0-src/src/libcore/fmt/mod.rs:195
#7  alloc::fmt::format (args=...) at src/liballoc/fmt.rs:563
#8  0x000070d4b43c306c in rustc_lint::builtin::BoxPointers::check_heap_type () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#9  0x000070d4b43ecdb8 in <rustc_lint::BuiltinCombinedModuleLateLintPass as rustc::lint::LateLintPass>::check_expr () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#10 0x000070d4b43f952c in rustc::hir::intravisit::walk_expr () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#11 0x000070d4b43ef8b0 in rustc::hir::intravisit::walk_block () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#12 0x000070d4b43a1028 in <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_nested_body ()
   from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#13 0x000070d4b43a1c58 in <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_fn () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#14 0x000070d4b43f197c in rustc::hir::intravisit::walk_impl_item () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#15 0x000070d4b43a7974 in rustc::hir::intravisit::Visitor::visit_nested_impl_item () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#16 0x000070d4b43fc428 in rustc::hir::intravisit::walk_item () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#17 0x000070d4b43a6e84 in rustc::hir::intravisit::Visitor::visit_nested_item () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#18 0x000070d4b43a8cd0 in rustc::lint::context::late_lint_mod () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_lint-ec9b804da742764c.so
#19 0x000070d4b6b0c448 in rustc::ty::query::__query_compute::lint_mod () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#20 0x000070d4b6a2280c in rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::lint_mod>::compute ()
   from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#21 0x000070d4b6a1bb9c in rustc::dep_graph::graph::DepGraph::with_task_impl () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#22 0x000070d4b6a2a5d0 in rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#23 0x000070d4b6a0f594 in rustc::lint::context::check_crate::{{closure}}::{{closure}} () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#24 0x000070d4b6a0073c in rustc_data_structures::sync::serial_join () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#25 0x000070d4b6a13458 in rustc::util::common::time () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#26 0x000070d4b6ca7de4 in __rust_maybe_catch_panic (f=<optimized out>, data=<optimized out>, data_ptr=0x70d4b33c39f8, vtable_ptr=0x70d4b33c3a00) at src/libpanic_unwind/lib.rs:87
#27 0x000070d4b69d1314 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#28 0x000070d4b6ca7de4 in __rust_maybe_catch_panic (f=<optimized out>, data=<optimized out>, data_ptr=0x70d4b33c3ae0, vtable_ptr=0x70d4b33c3ae8) at src/libpanic_unwind/lib.rs:87
#29 0x000070d4b6a200d0 in rustc_interface::passes::analysis::{{closure}} () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#30 0x000070d4b6a13eb8 in rustc::util::common::time () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#31 0x000070d4b6a7ae10 in rustc_interface::passes::analysis () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#32 0x000070d4b6db7574 in rustc::ty::query::__query_compute::analysis () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#33 0x000070d4b6e1bd58 in rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute ()
   from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#34 0x000070d4b6de7394 in rustc::dep_graph::graph::DepGraph::with_task_impl () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#35 0x000070d4b6e1cb50 in rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#36 0x000070d4b6dc7954 in rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}} () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#37 0x000070d4b6adbc60 in rustc_interface::passes::create_global_ctxt::{{closure}} () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_interface-5183811d86ee957c.so
#38 0x000070d4b6dcad78 in rustc_interface::interface::run_compiler_in_existing_thread_pool () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#39 0x000070d4b6da7888 in std::thread::local::LocalKey<T>::with () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#40 0x000070d4b6e29858 in scoped_tls::ScopedKey<T>::set () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#41 0x000070d4b6e6a0d4 in syntax::with_globals () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#42 0x000070d4b6dcbb64 in std::sys_common::backtrace::__rust_begin_short_backtrace () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#43 0x000070d4b6ca7de4 in __rust_maybe_catch_panic (f=<optimized out>, data=<optimized out>, data_ptr=0x70d4b33ce500, vtable_ptr=0x70d4b33ce508) at src/libpanic_unwind/lib.rs:87
#44 0x000070d4b6dcd084 in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /builddir/rustc-1.35.0-src/build/powerpc64le-unknown-linux-musl/stage1/lib/librustc_driver-64f3f0b358d083de.so
#45 0x000070d4b6c8dab8 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (self=..., args=<optimized out>) at /builddir/rustc-1.35.0-src/src/liballoc/boxed.rs:702
#46 0x000070d4b6c9ee90 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (self=<optimized out>, args=<optimized out>) at /builddir/rustc-1.35.0-src/src/liballoc/boxed.rs:702
#47 std::sys_common::thread::start_thread (main=0x70d4b700e8c0 "\200", <incomplete sequence \350>) at src/libstd/sys_common/thread.rs:14
#48 0x000070d4b6ca6848 in std::sys::unix::thread::Thread::new::thread_start (main=<optimized out>) at src/libstd/sys/unix/thread.rs:80
#49 0x000070d4b6fa40f8 in start (p=0x70d4b33ce6b0) at src/thread/pthread_create.c:144
#50 0x000070d4b6fb697c in __clone () at src/thread/powerpc64/clone.s:44
```

Cross-compiling for the target works okay (from `powerpc64le-unknown-linux-gnu`).

**Comment by q66** [comment]
can no longer reproduce this on 1.36
