### ISSUE TITLE
ICE: index out of bounds

### ISSUE THREAD

**Issue by scampi** [rust-lang/rust#61466]
I got an ICE when running tests on https://github.com/scampi/rustfmt/tree/xiongmao86-issue3456

```
rustc 1.36.0-nightly (d35181ad8 2019-05-20)
binary: rustc
commit-hash: d35181ad8785fa958e43580a29a982afe02c728f
commit-date: 2019-05-20
host: x86_64-unknown-linux-gnu
release: 1.36.0-nightly
LLVM version: 8.0
```

```
thread 'rustc' panicked at 'index out of bounds: the len is 611 but the index is 611', /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libcore/slice/mod.rs:2695:10
stack backtrace:
   0:     0x7f29ff3fe5a3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4240c895ef074e6c
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x7f29ff3f63fb - std::sys_common::backtrace::_print::h85732469f5e91569
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x7f29ff3fa7d6 - std::panicking::default_hook::{{closure}}::h7453219da447228b
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x7f29ff3fa569 - std::panicking::default_hook::h5a5763a0f6f96470
                               at src/libstd/panicking.rs:211
   4:     0x7f29fd126eb0 - rustc::util::common::panic_hook::h40a6b0402ac96de0
   5:     0x7f29ff3fafc8 - std::panicking::rust_panic_with_hook::h4be2dd51a1409e2e
                               at src/libstd/panicking.rs:478
   6:     0x7f29ff3faa61 - std::panicking::continue_panic_fmt::h61d6f2fc96e05179
                               at src/libstd/panicking.rs:381
   7:     0x7f29ff3fa945 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   8:     0x7f29ff423c5c - core::panicking::panic_fmt::h315e732055dee1aa
                               at src/libcore/panicking.rs:85
   9:     0x7f29ff423c14 - core::panicking::panic_bounds_check::h683d2ab324274178
                               at src/libcore/panicking.rs:61
  10:     0x7f29fce6c424 - <rustc::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode::hef8e2452b1d86168
  11:     0x7f29fcde8329 - serialize::serialize::Decoder::read_struct::h33b0239277e2b407
  12:     0x7f29fcdf89ff - serialize::serialize::Decoder::read_seq::h6a0d55bd51d4703f
  13:     0x7f29fcde8b20 - serialize::serialize::Decoder::read_struct::h41905a59c3403897
  14:     0x7f29fcdf71ec - serialize::serialize::Decoder::read_seq::h4ddeb4158bd23a39
  15:     0x7f29fce81ec3 - <rustc::mir::Mir as serialize::serialize::Decodable>::decode::{{closure}}::h5b989d05a5c4a907
  16:     0x7f29fce67826 - rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result::hc2eaab7ae64506b4
  17:     0x7f29fcf15645 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h5f5c9fa8a7600879
  18:     0x7f29fdaba906 - rustc_mir::monomorphize::collector::collect_items_rec::h8a6d22a02bc3cf3a
  19:     0x7f29fdabb59d - rustc_mir::monomorphize::collector::collect_items_rec::h8a6d22a02bc3cf3a
  20:     0x7f29fd9730fd - rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}::hd872a46be74f19c8
  21:     0x7f29fd94c4b6 - rustc::util::common::time::hb3016e70e0c3ccaf
  22:     0x7f29fdab9cf9 - rustc_mir::monomorphize::collector::collect_crate_mono_items::hbe38bada5c50b21e
  23:     0x7f29fd94c34c - rustc::util::common::time::h4ba7591e66bc15cf
  24:     0x7f29fdba6408 - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::hdeec2021303965a2
  25:     0x7f29f514bc29 - rustc::ty::query::__query_compute::collect_and_partition_mono_items::h1033fc055ac782a7
  26:     0x7f29f5173348 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::collect_and_partition_mono_items>::compute::ha45925b0c18bf89a
  27:     0x7f29f51605c6 - rustc::dep_graph::graph::DepGraph::with_task_impl::hfd8138d423881373
  28:     0x7f29f51aa985 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::hb2b52db37293e8bc
  29:     0x7f29f51cb20c - rustc_codegen_ssa::base::codegen_crate::h19d81e2638f87714
  30:     0x7f29f52231f9 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::h70d7c3822e68cdef
  31:     0x7f29fedfb8a6 - rustc::util::common::time::h36791dc77bd8a658
  32:     0x7f29fedc0cea - rustc_interface::passes::start_codegen::h10be19aa5a7f0cba
  33:     0x7f29feda3986 - rustc::ty::context::tls::enter_global::hd5f076e61138ae06
  34:     0x7f29fedc14e0 - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::h96e9d914741bd5a2
  35:     0x7f29fee624a4 - rustc_interface::passes::create_global_ctxt::{{closure}}::h3a0248d19580fca6
  36:     0x7f29fedc0035 - rustc_interface::passes::BoxedGlobalCtxt::enter::h9ea5ae414b4f8994
  37:     0x7f29feda7eff - rustc_interface::queries::Query<T>::compute::h50fa16ab35370818
  38:     0x7f29feeb2293 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen::h4e75d8b561950cee
  39:     0x7f29ff6e5eee - rustc_interface::interface::run_compiler_in_existing_thread_pool::h341a36ff89978958
  40:     0x7f29ff764795 - std::thread::local::LocalKey<T>::with::h6d7fda5052d96fbc
  41:     0x7f29ff707094 - scoped_tls::ScopedKey<T>::set::hfaf08c0381228ba8
  42:     0x7f29ff753301 - syntax::with_globals::h31c144c3250114b0
  43:     0x7f29ff6b44d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h489c725d3170fb96
  44:     0x7f29ff40c069 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  45:     0x7f29ff6dff08 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he16f7f8014f4fba5
  46:     0x7f29ff3dd2be - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8ef6d1bf34fb7980
                               at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/liballoc/boxed.rs:704
  47:     0x7f29ff40acdf - std::sys::unix::thread::Thread::new::thread_start::h8ab744ad746ba41c
                               at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/liballoc/boxed.rs:704
                               at src/libstd/sys_common/thread.rs:13
                               at src/libstd/sys/unix/thread.rs:79
  48:     0x7f29ff340a91 - start_thread
  49:     0x7f29ff25fcd2 - __clone
  50:                0x0 - <unknown>
query stack during panic:
#0 [optimized_mir] processing `unit_tests::test_format_code_block::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

**Comment by oli-obk** [comment]
`on_disk_cache` looks like incremental. Can you try `cargo clean` and running `cargo test` again?

**Comment by scampi** [comment]
Cleaning fixes the problem. BTW, in-between I updated the version of rust:

```
rustc 1.37.0-nightly (03ee55bb1 2019-06-01)
binary: rustc
commit-hash: 03ee55bb1c8c2379fdabf68e306186b390444f61
commit-date: 2019-06-01
host: x86_64-unknown-linux-gnu
release: 1.37.0-nightly
LLVM version: 8.0
```

**Comment by pnkfelix** [comment]
triage: If it truly is an incremental compilation bug, I'm not sure if there's anything we can do without more information on how to reproduce. Marking P-medium.

**Comment by scampi** [comment]
@pnkfelix Can I try to provide you some info ?

**Comment by gilescope** [comment]
This is too old. Can't repro. rustc-ap-arena seems to need raw_vec_internals feature, but after that am getting:
```
error[E0308]: mismatched types
    --> /Users/gilescope/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-syntax-174.0.0/attr.rs:1314:64
     |
1314 |                 Token::Literal(token::Lit::Str_(Symbol::intern(&escaped)), None)
     |                                                                ^^^^^^^^ expected str, found struct `std::str::EscapeDefault`
     |
     = note: expected type `&str`
                found type `&std::str::EscapeDefault<'_>`
```
when doing a clean cargo build --frozen with a may/june compiler. :-(
