### ISSUE TITLE
ICE when experimenting with FromIterator and constant generics

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#61514]
Code:

```rust
#![feature(const_generics)]

use core::iter::FromIterator;

pub struct Struct<const N: usize>([usize; N]);

impl<const N: usize> FromIterator<usize> for Struct<{ N }>
{
  #[inline]
  fn from_iter<I>(iter: I) -> Self
  where
    I: IntoIterator<Item = usize>,
  {
    let mut array: [usize; N] = [0; N];
    iter.into_iter().take(N).enumerate().for_each(|(idx, elem)| array[idx] = elem);
    Self(array)
  }
}
```

Error:

```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/6ffb8f53ee1cb0903f9df7d2fdb37ad06d748566/src/libcore/slice/mod.rs:2695:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: internal compiler error: cat_expr Errd
  --> src/lib.rs:13:3
   |
13 | /   {
14 | |     let mut array: [usize; N] = [0; N];
15 | |     iter.into_iter().take(N).enumerate().for_each(|(idx, elem)| array[idx] = elem);
16 | |     Self(array)
17 | |   }
   | |___^
``

**Comment by c410-f3r** [comment]
NVM, it was just a bad implementation

**Comment by hellow554** [comment]
Complete error message:

```text
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/5d8f59f4b1473217c2de7e02330b5aaae70a1668/src/libcore/slice/mod.rs:2695:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: internal compiler error: cat_expr Errd
  --> src/lib.rs:13:5
   |
13 | /     {
14 | |         let mut array: [usize; N] = [0; N];
15 | |         iter.into_iter()
16 | |             .take(N)
...  |
19 | |         Self(array)
20 | |     }
   | |_____^

error: internal compiler error: cat_expr Errd
  --> src/lib.rs:14:37
   |
14 |         let mut array: [usize; N] = [0; N];
   |                                     ^^^^^^

error: internal compiler error: cat_expr Errd
  --> src/lib.rs:18:23
   |
18 |             .for_each(|(idx, elem)| array[idx] = elem);
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: cat_expr Errd
  --> src/lib.rs:18:37
   |
18 |             .for_each(|(idx, elem)| array[idx] = elem);
   |                                     ^^^^^

error: internal compiler error: QualifyAndPromoteConstants: MIR had errors
  --> src/lib.rs:10:5
   |
10 | /     fn from_iter<I>(iter: I) -> Self
11 | |     where
12 | |         I: IntoIterator<Item = usize>,
13 | |     {
...  |
19 | |         Self(array)
20 | |     }
   | |_____^

error: internal compiler error: broken MIR in DefId(0:21 ~ playground[8e33]::{{impl}}[0]::from_iter[0]) ("return type"): bad type [type error]
  --> src/lib.rs:10:5
   |
10 | /     fn from_iter<I>(iter: I) -> Self
11 | |     where
12 | |         I: IntoIterator<Item = usize>,
13 | |     {
...  |
19 | |         Self(array)
20 | |     }
   | |_____^

error: internal compiler error: broken MIR in DefId(0:21 ~ playground[8e33]::{{impl}}[0]::from_iter[0]) (LocalDecl { mutability: Mut, is_user_variable: None, internal: false, is_block_tail: None, ty: [type error], user_ty: UserTypeProjections { contents: [] }, name: None, source_info: SourceInfo { span: src/lib.rs:10:5: 20:6, scope: scope[0] }, visibility_scope: scope[0] }): bad type [type error]
  --> src/lib.rs:10:5
   |
10 | /     fn from_iter<I>(iter: I) -> Self
11 | |     where
12 | |         I: IntoIterator<Item = usize>,
13 | |     {
...  |
19 | |         Self(array)
20 | |     }
   | |_____^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:357:17
stack backtrace:
   0:     0x7fe33d09107a - backtrace::backtrace::libunwind::trace::h67d6e4bec97fc135
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.25/src/backtrace/libunwind.rs:97
   1:     0x7fe33d09107a - backtrace::backtrace::trace_unsynchronized::hf7d78522dc561709
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.25/src/backtrace/mod.rs:66
   2:     0x7fe33d09107a - std::sys_common::backtrace::_print::h42a74ea4b7d276a3
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x7fe33d09107a - std::sys_common::backtrace::print::h348ac7b7055622fa
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x7fe33d09107a - std::panicking::default_hook::{{closure}}::h8d7eb65d5f035331
                               at src/libstd/panicking.rs:197
   5:     0x7fe33d090d7b - std::panicking::default_hook::h88d1c552f88cbbc1
                               at src/libstd/panicking.rs:211
   6:     0x7fe33a6017e0 - rustc::util::common::panic_hook::hcd84a0bd3c350d77
   7:     0x7fe33d0918d8 - std::panicking::rust_panic_with_hook::hb9dbdd96753a2b32
                               at src/libstd/panicking.rs:478
   8:     0x7fe33924fd94 - std::panicking::begin_panic::h5e7430a15f858c47
   9:     0x7fe339270264 - <rustc_errors::Handler as core::ops::drop::Drop>::drop::hc110121a929ca848
  10:     0x7fe33d3b6221 - core::ptr::real_drop_in_place::h081af655f9056019
  11:     0x7fe33d3b82f0 - core::ptr::real_drop_in_place::h3db6e08239f052f3
  12:     0x7fe33d3c25c3 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h39fb9de3452e098f
  13:     0x7fe33d389dbb - core::ptr::real_drop_in_place::h59b311e6f48b1ef5
  14:     0x7fe33d386161 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h3649b34e89a7a882
  15:     0x7fe33d3f7e75 - std::thread::local::LocalKey<T>::with::h387f74f50ff2c76d
  16:     0x7fe33d39bba4 - scoped_tls::ScopedKey<T>::set::hc5b8741bd4d84453
  17:     0x7fe33d3c3973 - syntax::with_globals::h82e94067137cd3aa
  18:     0x7fe33d3e2afc - std::sys_common::backtrace::__rust_begin_short_backtrace::hdcd589f4f8a2f6a9
  19:     0x7fe33d0a27c9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  20:     0x7fe33d36e228 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8338aaad711a2c71
  21:     0x7fe33d074d9e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h895599b155fe1448
                               at /rustc/5d8f59f4b1473217c2de7e02330b5aaae70a1668/src/liballoc/boxed.rs:746
  22:     0x7fe33d0a149f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h725e97f5b2a75aa7
                               at /rustc/5d8f59f4b1473217c2de7e02330b5aaae70a1668/src/liballoc/boxed.rs:746
  23:     0x7fe33d0a149f - std::sys_common::thread::start_thread::h4b9fafc7837adacc
                               at src/libstd/sys_common/thread.rs:13
  24:     0x7fe33d0a149f - std::sys::unix::thread::Thread::new::thread_start::h12f7e3ef786ef196
                               at src/libstd/sys/unix/thread.rs:79
  25:     0x7fe33ce116da - start_thread
  26:     0x7fe33c72e88e - __clone
  27:                0x0 - <unknown>
thread panicked while panicking. aborting.
error: Could not compile `playground`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name playground src/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C codegen-units=1 -C debuginfo=2 -C metadata=4ce9ad46bb4bcd9d -C extra-filename=-4ce9ad46bb4bcd9d --out-dir /playground/target/debug/deps -L dependency=/playground/target/debug/deps --extern adler32=/playground/target/debug/deps/libadler32-5b8bfce4a8d923b6.rlib --extern aho_corasick=/playground/target/debug/deps/libaho_corasick-df8c8ee910a01715.rlib --extern ansi_term=/playground/target/debug/deps/libansi_term-c8b922b2940d1ece.rlib --extern argon2rs=/playground/target/debug/deps/libargon2rs-72378b554f46221e.rlib --extern arrayvec=/playground/target/debug/deps/libarrayvec-3de2e45f08a083df.rlib --extern atty=/playground/target/debug/deps/libatty-9b0d6949146f58c5.rlib --extern autocfg=/playground/target/debug/deps/libautocfg-6d65bceef577cc2e.rlib --extern backtrace=/playground/target/debug/deps/libbacktrace-7dbc743409528fb7.rlib --extern backtrace_sys=/playground/target/debug/deps/libbacktrace_sys-f0b630eae5a96fe1.rlib --extern base64=/playground/target/debug/deps/libbase64-9b4df73e4ff19802.rlib --extern bit_set=/playground/target/debug/deps/libbit_set-78bd73ecb4466128.rlib --extern bit_vec=/playground/target/debug/deps/libbit_vec-2d60fda1f19f1555.rlib --extern bitflags=/playground/target/debug/deps/libbitflags-af24a001ed6c6435.rlib --extern blake2_rfc=/playground/target/debug/deps/libblake2_rfc-99d7333095151bbb.rlib --extern build_const=/playground/target/debug/deps/libbuild_const-8b2394e620cf5460.rlib --extern byteorder=/playground/target/debug/deps/libbyteorder-547eaa830f973278.rlib --extern bytes=/playground/target/debug/deps/libbytes-2db262b61e7a1f06.rlib --extern cc=/playground/target/debug/deps/libcc-2cbc62c9cb7b65cf.rlib --extern cfg_if=/playground/target/debug/deps/libcfg_if-057b840b7dfaaa38.rlib --extern chrono=/playground/target/debug/deps/libchrono-78878e221c2d18ce.rlib --extern clap=/playground/target/debug/deps/libclap-d4e37ac0c8ad9151.rlib --extern cloudabi=/playground/target/debug/deps/libcloudabi-11afdb7c975002b5.rlib --extern color_quant=/playground/target/debug/deps/libcolor_quant-03fa0f73f40cdea1.rlib --extern constant_time_eq=/playground/target/debug/deps/libconstant_time_eq-2c84c5a207b72066.rlib --extern cookie=/playground/target/debug/deps/libcookie-a41774d282b2a073.rlib --extern cookie_store=/playground/target/debug/deps/libcookie_store-efdfce9e0eeebe08.rlib --extern crc=/playground/target/debug/deps/libcrc-6bf652b8e5287d61.rlib --extern crc32fast=/playground/target/debug/deps/libcrc32fast-75a961ee59fef69d.rlib --extern crossbeam=/playground/target/debug/deps/libcrossbeam-81820020d8f3cf48.rlib --extern crossbeam_channel=/playground/target/debug/deps/libcrossbeam_channel-2879002e0b3157e1.rlib --extern crossbeam_deque=/playground/target/debug/deps/libcrossbeam_deque-29515c0b1ef82931.rlib --extern crossbeam_epoch=/playground/target/debug/deps/libcrossbeam_epoch-b35f21236afb94de.rlib --extern crossbeam_queue=/playground/target/debug/deps/libcrossbeam_queue-e46770637aacf33a.rlib --extern crossbeam_utils=/playground/target/debug/deps/libcrossbeam_utils-3ee1614c5b6c8ad1.rlib --extern csv=/playground/target/debug/deps/libcsv-452eac13f49df03e.rlib --extern csv_core=/playground/target/debug/deps/libcsv_core-2f8e174b9a7c15db.rlib --extern data_encoding=/playground/target/debug/deps/libdata_encoding-ba8ac7ab2b64d830.rlib --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-84bdd789473ece0e.rlib --extern deflate=/playground/target/debug/deps/libdeflate-216068561aa03b4a.rlib --extern dirs=/playground/target/debug/deps/libdirs-496fe772f33a2e8a.rlib --extern dtoa=/playground/target/debug/deps/libdtoa-9ea866bdfefdb590.rlib --extern either=/playground/target/debug/deps/libeither-3a738a74bc537024.rlib --extern encoding_rs=/playground/target/debug/deps/libencoding_rs-46a756fe6727a600.rlib --extern env_logger=/playground/target/debug/deps/libenv_logger-00f0d7777353ad92.rlib --extern error_chain=/playground/target/debug/deps/liberror_chain-65f0ea80f8e26efa.rlib --extern failure=/playground/target/debug/deps/libfailure-df8fb297fe93322e.rlib --extern failure_derive=/playground/target/debug/deps/libfailure_derive-daa1f993e0126060.so --extern filetime=/playground/target/debug/deps/libfiletime-8a102de59a58bb72.rlib --extern fixedbitset=/playground/target/debug/deps/libfixedbitset-c53e7d8ee0bc6668.rlib --extern flate2=/playground/target/debug/deps/libflate2-71de60cdf60b517f.rlib --extern fnv=/playground/target/debug/deps/libfnv-d2cf8aba90603606.rlib --extern foreign_types=/playground/target/debug/deps/libforeign_types-51387807f81ec9f5.rlib --extern foreign_types_shared=/playground/target/debug/deps/libforeign_types_shared-59766993938408f0.rlib --extern fuchsia_cprng=/playground/target/debug/deps/libfuchsia_cprng-8eaa7578d674e36f.rlib --extern fuchsia_zircon=/playground/target/debug/deps/libfuchsia_zircon-8e8114de6251eadf.rlib --extern fuchsia_zircon_sys=/playground/target/debug/deps/libfuchsia_zircon_sys-b33dda9dd6c285e2.rlib --extern futf=/playground/target/debug/deps/libfutf-e24612e5d0074d63.rlib --extern futures=/playground/target/debug/deps/libfutures-273b18761a5bbd83.rlib --extern futures_cpupool=/playground/target/debug/deps/libfutures_cpupool-f5d0ddf70d8681b0.rlib --extern gcc=/playground/target/debug/deps/libgcc-1589e87f8adb1fe1.rlib --extern gif=/playground/target/debug/deps/libgif-79093d98d98a50d9.rlib --extern glob=/playground/target/debug/deps/libglob-c27fb541539efedb.rlib --extern h2=/playground/target/debug/deps/libh2-c7ce6677767bf2b2.rlib --extern html5ever=/playground/target/debug/deps/libhtml5ever-f4a13c769a9cb769.rlib --extern http=/playground/target/debug/deps/libhttp-2610dcd9617c3713.rlib --extern http_body=/playground/target/debug/deps/libhttp_body-88d959c09f365b75.rlib --extern httparse=/playground/target/debug/deps/libhttparse-d56e044bc71ec136.rlib --extern humantime=/playground/target/debug/deps/libhumantime-aa5c1887caea58a7.rlib --extern hyper=/playground/target/debug/deps/libhyper-1b1e1ca6ffc1f557.rlib --extern hyper_tls=/playground/target/debug/deps/libhyper_tls-954217e8826fe451.rlib --extern idna=/playground/target/debug/deps/libidna-b06a6542581f5c1b.rlib --extern image=/playground/target/debug/deps/libimage-de930669db1e2ce8.rlib --extern indexmap=/playground/target/debug/deps/libindexmap-a38e4eccc41929fe.rlib --extern inflate=/playground/target/debug/deps/libinflate-ca80a4a4047b451f.rlib --extern iovec=/playground/target/debug/deps/libiovec-c36aa17fb4a55bdc.rlib --extern itertools=/playground/target/debug/deps/libitertools-0ece32b335d8ad5e.rlib --extern itoa=/playground/target/debug/deps/libitoa-8451d85c257700bb.rlib --extern jpeg_decoder=/playground/target/debug/deps/libjpeg_decoder-4f7fe26b76e5a00e.rlib --extern kernel32=/playground/target/debug/deps/libkernel32-de0cb954741e81f9.rlib --extern lazy_static=/playground/target/debug/deps/liblazy_static-3e2402156c138e08.rlib --extern lazycell=/playground/target/debug/deps/liblazycell-7eb8c7940f9acf00.rlib --extern libc=/playground/target/debug/deps/liblibc-126db52017b696ea.rlib --extern lock_api=/playground/target/debug/deps/liblock_api-19136556e8b90988.rlib --extern log=/playground/target/debug/deps/liblog-b9565a325888d1fd.rlib --extern lzw=/playground/target/debug/deps/liblzw-cf02781997ffe28a.rlib --extern mac=/playground/target/debug/deps/libmac-5f584c4b710b2f26.rlib --extern markup5ever=/playground/target/debug/deps/libmarkup5ever-c37227a5e6b08ad8.rlib --extern matches=/playground/target/debug/deps/libmatches-d9933cb4f10c977d.rlib --extern memchr=/playground/target/debug/deps/libmemchr-24b25ed5b5073d71.rlib --extern memmap=/playground/target/debug/deps/libmemmap-0d089cd23d5ce2d0.rlib --extern memoffset=/playground/target/debug/deps/libmemoffset-e477d193aef5ec97.rlib --extern mime=/playground/target/debug/deps/libmime-dde8373fa6623403.rlib --extern mime_guess=/playground/target/debug/deps/libmime_guess-f71b390c544af0b1.rlib --extern miniz_sys=/playground/target/debug/deps/libminiz_sys-707da806d6d0d6ca.rlib --extern miniz_oxide=/playground/target/debug/deps/libminiz_oxide-95ef1f59b66f0d75.rlib --extern miniz_oxide_c_api=/playground/target/debug/deps/libminiz_oxide_c_api-1c272a6657450717.rlib --extern mio=/playground/target/debug/deps/libmio-3036330810ddd562.rlib --extern miow=/playground/target/debug/deps/libmiow-002c95aac1955ea4.rlib --extern native_tls=/playground/target/debug/deps/libnative_tls-eea4b4f1074178c7.rlib --extern net2=/playground/target/debug/deps/libnet2-8096d198f8a379f3.rlib --extern debug_unreachable=/playground/target/debug/deps/libdebug_unreachable-f71df3a7b40965df.rlib --extern nodrop=/playground/target/debug/deps/libnodrop-bfcfa17d775afe43.rlib --extern num=/playground/target/debug/deps/libnum-77f31466ad225756.rlib --extern num_bigint=/playground/target/debug/deps/libnum_bigint-36ef90b55f542516.rlib --extern num_complex=/playground/target/debug/deps/libnum_complex-4c2b16f2e7ff62ef.rlib --extern num_derive=/playground/target/debug/deps/libnum_derive-2efecec524356cea.so --extern num_integer=/playground/target/debug/deps/libnum_integer-8e74a8dfbd46081a.rlib --extern num_iter=/playground/target/debug/deps/libnum_iter-688da8778c413b2e.rlib --extern num_rational=/playground/target/debug/deps/libnum_rational-33ab51517903fb16.rlib --extern num_traits=/playground/target/debug/deps/libnum_traits-cefc9ad5e9c15653.rlib --extern num_cpus=/playground/target/debug/deps/libnum_cpus-ba7fe9aaffbd6dcb.rlib --extern numtoa=/playground/target/debug/deps/libnumtoa-dce2d5716773603e.rlib --extern openssl_probe=/playground/target/debug/deps/libopenssl_probe-9742d8d9dc8a6319.rlib --extern ordermap=/playground/target/debug/deps/libordermap-8ff35f4b3cc7878c.rlib --extern owning_ref=/playground/target/debug/deps/libowning_ref-a04b5d8c893c7adb.rlib --extern parking_lot=/playground/target/debug/deps/libparking_lot-9046688540e97817.rlib --extern parking_lot_core=/playground/target/debug/deps/libparking_lot_core-3dd35b7fc2604d5a.rlib --extern percent_encoding=/playground/target/debug/deps/libpercent_encoding-a6e5b7a041228229.rlib --extern petgraph=/playground/target/debug/deps/libpetgraph-3f985994dff157df.rlib --extern phf=/playground/target/debug/deps/libphf-38157029f811c9f0.rlib --extern phf_codegen=/playground/target/debug/deps/libphf_codegen-1c381106228b4783.rlib --extern phf_generator=/playground/target/debug/deps/libphf_generator-fe0d26cbfc430aaf.rlib --extern phf_shared=/playground/target/debug/deps/libphf_shared-e9b41563f174e38a.rlib --extern pkg_config=/playground/target/debug/deps/libpkg_config-4c6770a901e96104.rlib --extern png=/playground/target/debug/deps/libpng-a719a98adf261766.rlib --extern precomputed_hash=/playground/target/debug/deps/libprecomputed_hash-058f42d2817d6650.rlib --extern proc_macro2=/playground/target/debug/deps/libproc_macro2-b237f229956e0b8c.rlib --extern publicsuffix=/playground/target/debug/deps/libpublicsuffix-fdfc981398fd0bba.rlib --extern quick_error=/playground/target/debug/deps/libquick_error-9a9b9c21ab7a32ab.rlib --extern quote=/playground/target/debug/deps/libquote-8a56b592a675c8ef.rlib --extern rand=/playground/target/debug/deps/librand-dcb8958f729a4786.rlib --extern rand_chacha=/playground/target/debug/deps/librand_chacha-c8f7cd9d73098aae.rlib --extern rand_core=/playground/target/debug/deps/librand_core-d9b4c64b73409e1a.rlib --extern rand_hc=/playground/target/debug/deps/librand_hc-aae543dbcee4a4e6.rlib --extern rand_isaac=/playground/target/debug/deps/librand_isaac-dccb6010909b4e1e.rlib --extern rand_jitter=/playground/target/debug/deps/librand_jitter-31326c4f76a07ec0.rlib --extern rand_os=/playground/target/debug/deps/librand_os-b3d091c49642bb84.rlib --extern rand_pcg=/playground/target/debug/deps/librand_pcg-7bded6cbb8475291.rlib --extern rand_xorshift=/playground/target/debug/deps/librand_xorshift-3cc4bb21c0f06660.rlib --extern rayon=/playground/target/debug/deps/librayon-50172f7a8255f8a7.rlib --extern rayon_core=/playground/target/debug/deps/librayon_core-a69622204d3db582.rlib --extern rdrand=/playground/target/debug/deps/librdrand-068c4bb4fbdc7237.rlib --extern regex=/playground/target/debug/deps/libregex-531a4de629601f29.rlib --extern regex_syntax=/playground/target/debug/deps/libregex_syntax-03bda2297586e245.rlib --extern remove_dir_all=/playground/target/debug/deps/libremove_dir_all-eef8a6946d8eb36f.rlib --extern reqwest=/playground/target/debug/deps/libreqwest-97b285b5f428fc98.rlib --extern ring=/playground/target/debug/deps/libring-74bffe9a8e0f200c.rlib --extern rustc_demangle=/playground/target/debug/deps/librustc_demangle-f6172972cdb77315.rlib --extern rustc_serialize=/playground/target/debug/deps/librustc_serialize-59cb842cd38a7393.rlib --extern rustc_version=/playground/target/debug/deps/librustc_version-26e2190160493d28.rlib --extern ryu=/playground/target/debug/deps/libryu-6dbeb43e4c493f58.rlib --extern same_file=/playground/target/debug/deps/libsame_file-202c5a5547835a7f.rlib --extern schannel=/playground/target/debug/deps/libschannel-8c44ff4aa73c9af9.rlib --extern scoped_threadpool=/playground/target/debug/deps/libscoped_threadpool-af38a0b7fdd00db2.rlib --extern scopeguard=/playground/target/debug/deps/libscopeguard-543619a793da8a7e.rlib --extern select=/playground/target/debug/deps/libselect-b1b48ffba67dbe94.rlib --extern semver=/playground/target/debug/deps/libsemver-d19d4c2d81b10e44.rlib --extern semver_parser=/playground/target/debug/deps/libsemver_parser-4e104c19d258550b.rlib --extern serde=/playground/target/debug/deps/libserde-2aa503f86e9b6f5d.rlib --extern serde_derive=/playground/target/debug/deps/libserde_derive-28361935f965e193.so --extern serde_json=/playground/target/debug/deps/libserde_json-be2d30d1f4bd7b44.rlib --extern serde_urlencoded=/playground/target/debug/deps/libserde_urlencoded-049abb719beec164.rlib --extern siphasher=/playground/target/debug/deps/libsiphasher-c9ae8943cf8394d7.rlib --extern slab=/playground/target/debug/deps/libslab-ca5ea4ff1ff3aa65.rlib --extern smallvec=/playground/target/debug/deps/libsmallvec-09b3f09d11a1ddf6.rlib --extern spin=/playground/target/debug/deps/libspin-1547bc39d803889d.rlib --extern stable_deref_trait=/playground/target/debug/deps/libstable_deref_trait-a56bef8c0dd11f79.rlib --extern string=/playground/target/debug/deps/libstring-61356db66dd3575d.rlib --extern string_cache=/playground/target/debug/deps/libstring_cache-4142bf0cce63b1a2.rlib --extern string_cache_codegen=/playground/target/debug/deps/libstring_cache_codegen-aeaba8ca44742423.rlib --extern string_cache_shared=/playground/target/debug/deps/libstring_cache_shared-3f5d3bfc015cafe8.rlib --extern strsim=/playground/target/debug/deps/libstrsim-4cb6219a4074c255.rlib --extern syn=/playground/target/debug/deps/libsyn-640f08911c8ee733.rlib --extern synom=/playground/target/debug/deps/libsynom-78a1faaa108554ee.rlib --extern synstructure=/playground/target/debug/deps/libsynstructure-36bb64c95ab6e557.rlib --extern syslog=/playground/target/debug/deps/libsyslog-965616aabe062253.rlib --extern tar=/playground/target/debug/deps/libtar-26ceaa77e6984712.rlib --extern tempdir=/playground/target/debug/deps/libtempdir-3144dab449de6d84.rlib --extern tempfile=/playground/target/debug/deps/libtempfile-9f55f237d649771d.rlib --extern tendril=/playground/target/debug/deps/libtendril-0502bfa7bc32b754.rlib --extern term=/playground/target/debug/deps/libterm-0dcdf637e3410cfe.rlib --extern termcolor=/playground/target/debug/deps/libtermcolor-a5ec155e06605d1a.rlib --extern termion=/playground/target/debug/deps/libtermion-8998934b942406e6.rlib --extern textwrap=/playground/target/debug/deps/libtextwrap-5943a671c5cddd31.rlib --extern thread_id=/playground/target/debug/deps/libthread_id-847b7cdc0c3a5700.rlib --extern thread_local=/playground/target/debug/deps/libthread_local-92a5265038bc6b1c.rlib --extern threadpool=/playground/target/debug/deps/libthreadpool-ceabe56a1096d00d.rlib --extern tiff=/playground/target/debug/deps/libtiff-19b940ca5ec0a93c.rlib --extern time=/playground/target/debug/deps/libtime-4f6864c6df86a76d.rlib --extern tokio=/playground/target/debug/deps/libtokio-96b1b76587b30114.rlib --extern tokio_buf=/playground/target/debug/deps/libtokio_buf-d8fe264693180ee0.rlib --extern tokio_current_thread=/playground/target/debug/deps/libtokio_current_thread-da73dbda9b3572e5.rlib --extern tokio_executor=/playground/target/debug/deps/libtokio_executor-8de100ce4863da82.rlib --extern tokio_io=/playground/target/debug/deps/libtokio_io-2220c265f8d63665.rlib --extern tokio_reactor=/playground/target/debug/deps/libtokio_reactor-d017020d5aab08bd.rlib --extern tokio_sync=/playground/target/debug/deps/libtokio_sync-e36f8b186b8bf2a4.rlib --extern tokio_tcp=/playground/target/debug/deps/libtokio_tcp-fbe84f64efcede6a.rlib --extern tokio_threadpool=/playground/target/debug/deps/libtokio_threadpool-6071dcd928d1ca16.rlib --extern tokio_timer=/playground/target/debug/deps/libtokio_timer-9362464bd43b0c38.rlib --extern tokio_trace_core=/playground/target/debug/deps/libtokio_trace_core-e9a61c80eeb557ad.rlib --extern toml=/playground/target/debug/deps/libtoml-8f6544dead7eec6c.rlib --extern try_lock=/playground/target/debug/deps/libtry_lock-492fc0e0eadbe6af.rlib --extern try_from=/playground/target/debug/deps/libtry_from-c32e81280a79ebad.rlib --extern ucd_util=/playground/target/debug/deps/libucd_util-ebe8ec40d13a6155.rlib --extern unicase=/playground/target/debug/deps/libunicase-fab938ad94a1e989.rlib --extern unicode_bidi=/playground/target/debug/deps/libunicode_bidi-804a16b7065032fb.rlib --extern unicode_normalization=/playground/target/debug/deps/libunicode_normalization-8ed87bc39bdcce48.rlib --extern unicode_width=/playground/target/debug/deps/libunicode_width-e76f0fedc95b9357.rlib --extern unicode_xid=/playground/target/debug/deps/libunicode_xid-5cf37620a54f4a9d.rlib --extern unreachable=/playground/target/debug/deps/libunreachable-ef2401bd0ead3357.rlib --extern untrusted=/playground/target/debug/deps/libuntrusted-faf223450e002b9e.rlib --extern url=/playground/target/debug/deps/liburl-fd2523973520d653.rlib --extern utf8=/playground/target/debug/deps/libutf8-8e492ff082441a58.rlib --extern utf8_ranges=/playground/target/debug/deps/libutf8_ranges-888ab5da0a0eab75.rlib --extern uuid=/playground/target/debug/deps/libuuid-43ee0c65684811f8.rlib --extern vcpkg=/playground/target/debug/deps/libvcpkg-bec14018b04367c5.rlib --extern vec_map=/playground/target/debug/deps/libvec_map-0af5b361474d54eb.rlib --extern version_check=/playground/target/debug/deps/libversion_check-1203c7927bbb66f8.rlib --extern void=/playground/target/debug/deps/libvoid-386207741ced880b.rlib --extern walkdir=/playground/target/debug/deps/libwalkdir-8b17ca081aa1b9b8.rlib --extern want=/playground/target/debug/deps/libwant-f322fad76d6206ba.rlib --extern winapi=/playground/target/debug/deps/libwinapi-7d5483cddc53c3ef.rlib --extern build=/playground/target/debug/deps/libbuild-5b4c3c589dc1649e.rlib --extern winapi_i686_pc_windows_gnu=/playground/target/debug/deps/libwinapi_i686_pc_windows_gnu-1573049ed2d844df.rlib --extern winapi_util=/playground/target/debug/deps/libwinapi_util-8044d63c31993790.rlib --extern winapi_x86_64_pc_windows_gnu=/playground/target/debug/deps/libwinapi_x86_64_pc_windows_gnu-c7319092770fcc17.rlib --extern wincolor=/playground/target/debug/deps/libwincolor-83c9030f7dc4e32a.rlib --extern ws2_32=/playground/target/debug/deps/libws2_32-35a1ce480745a29e.rlib --extern xattr=/playground/target/debug/deps/libxattr-f9980684670af848.rlib -L native=/playground/target/debug/build/backtrace-sys-61c154d4a7669585/out -L native=/playground/target/debug/build/miniz-sys-7cb73f824e7870e8/out -L native=/playground/target/debug/build/ring-2da2bb081b608576/out` (signal: 4, SIGILL: illegal instruction)
```

I find ` (signal: 4, SIGILL: illegal instruction)` very interesting and weird.

**Comment by skinny121** [comment]
I think the cause of this ICE is the same as #61336, although it's unclear without #61336 fixed if there is any other problem with this snippet.

**Comment by c410-f3r** [comment]
Duplicated of #61336
