### ISSUE TITLE
rustc crash

### ISSUE THREAD

**Issue by jeff-davis** [rust-lang/rust#61589]
```
jdavis@jdavis:~/wd/postgres-extension.rs/examples/udf-spi (master)$ rustc --versi[50/1944]
ose                                                           
rustc 1.35.0 (3c235d560 2019-05-20)                                   
binary: rustc                              
commit-hash: 3c235d5600393dfe6c36eeed34042efad8d4f26e
commit-date: 2019-05-20          
host: x86_64-unknown-linux-gnu  
release: 1.35.0                                      
LLVM version: 8.0                                   
jdavis@jdavis:~/wd/postgres-extension.rs/examples/udf-spi (master)$ RUST_BACKTRACE=1 cargo
 build                                 
   Compiling udf-spi v0.1.0 (/home/jdavis/wd/postgres-extension.rs/examples/udf-spi)
error: internal compiler error: src/librustc/dep_graph/graph.rs:688: DepNode Hir(udf_spi[fd57]::udf_spi[0]::{{misc}}[1]::{{misc}}[0]) should have been pre-allocated but wasn't.

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:635:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:                                                             
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39      
   1: std::sys_common::backtrace::_print         
             at src/libstd/sys_common/backtrace.rs:71                                     
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59  
             at src/libstd/panicking.rs:197                                   
   3: std::panicking::default_hook                                 
             at src/libstd/panicking.rs:211                        
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc::dep_graph::graph::DepGraph::try_mark_previous_green
  15: rustc::dep_graph::graph::DepGraph::try_mark_green
  16: rustc::dep_graph::graph::DepGraph::try_mark_green_and_read
  17: rustc_typeck::impl_wf_check::impl_wf_check
  18: rustc::util::common::time
  19: rustc_typeck::check_crate
  20: rustc_interface::passes::analysis
  21: rustc::ty::query::__query_compute::analysis
  22: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  23: rustc::dep_graph::graph::DepGraph::with_task_impl
  24: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  25: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  26: rustc_interface::passes::create_global_ctxt::{{closure}}
  27: rustc_interface::interface::run_compiler_in_existing_thread_pool
  28: std::thread::local::LocalKey<T>::with
  29: scoped_tls::ScopedKey<T>::set
  30: syntax::with_globals
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0 (3c235d560 2019-05-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `udf-spi`.

To learn more, run the command again with --verbose.
```

Can be reproduced with https://github.com/jeff-davis/postgres-extension.rs/commit/8c12f124e42f1b1f88fb3fcc24daea6b6bb2a5eb by ``cargo build`` of the ``examples/udf-spi``.

**Comment by jonas-schievink** [comment]
I can't seem to reproduce this, so maybe this is an incremental compilation problem. Can you try running `cargo clean` and then `cargo build` again?

**Comment by jeff-davis** [comment]
Now it works, but I fear I've lost information that might have helped track it down.

**Comment by jonas-schievink** [comment]
@jeff-davis do you perhaps remember the changes you made to the code before the ICE first appeared?

**Comment by jeff-davis** [comment]
I repro'd it building ``HEAD^`` and then incrementally building ``HEAD``

**Comment by jonas-schievink** [comment]
Yep, can reproduce on 1.35.0. It appears to be already fixed on beta and nightly though.

**Comment by jeff-davis** [comment]
Thanks!

**Comment by jonas-schievink** [comment]
Yeah this should've been fixed by https://github.com/rust-lang/rust/pull/57698, to be specific. Closing as fixed.
