### ISSUE TITLE
Internal compiler error anonymous bound region BrAnon(0) in binding but not trait ref

### ISSUE THREAD

**Issue by SeeSpring** [rust-lang/rust#62200]
The following code causes an error

```rust
impl<'b, B: Ty<'b>, I: SIterator, F> SIterator for FilterMap<I, F> where
    F: FnMut(<I as Ty>::V) -> Option<<B as Ty>::V>
{}

pub trait SIterator: for<'a> Ty<'a> {}

pub trait Ty<'a> {
    type V;
}

```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e175d6557baecbf033a125d9276bd385))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0465]: multiple rlib candidates for `debug_unreachable` found
  |
  = note: candidate #1: /playground/target/debug/deps/libdebug_unreachable-53cbbc8451f8a571.rlib
  = note: candidate #2: /playground/target/debug/deps/libdebug_unreachable-9f86ee3a7179ede7.rlib

error[E0412]: cannot find type `FilterMap` in this scope
 --> src/lib.rs:1:52
  |
1 | impl<'b, B: Ty<'b>, I: SIterator, F> SIterator for FilterMap<I, F> where
  |                                                    ^^^^^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
  |
1 | use core::iter::FilterMap;
  |
1 | use futures::stream::FilterMap;
  |
1 | use itertools::__std_iter::FilterMap;
  |
1 | use rayon::iter::FilterMap;
  |
and 2 other candidates

error: internal compiler error: src/librustc_typeck/astconv.rs:1097: anonymous bound region BrAnon(0) in binding but not trait ref
 --> src/lib.rs:2:31
  |
2 |     F: FnMut(<I as Ty>::V) -> Option<<B as Ty>::V>
  |                               ^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:578:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0412`.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (b25ee6449 2019-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by Centril** [comment]
Reduced:
```rust
pub trait SIterator {}

pub trait Ty<'a> {
    type V;
}

struct FilterMap<F>(F);

impl<X, F> SIterator for FilterMap<F>
where
    F: FnOnce(<X as Ty<'_>>::V) -> Option<<X as Ty<'_>>::V>
{}
```

**Comment by pnkfelix** [comment]
seems like this bug dates at least to when `'_` was stabilized in 1.26.0

**Comment by pnkfelix** [comment]
bug dates back to at *least* nightly-2017-10-15 and perhaps earlier. It seems reasonable right now to assume its been present ever since `feature(underscore_lifetimes)` was introduced.

**Comment by pnkfelix** [comment]
I'm going to have to do some background reading to remember what we are *supposed* to do in a case like this.

If you remove the occurrences of `'_` you get the same ICE behavior, and *that* behavior dates all the way back to rust 1.10.0:

```
% rustc +1.10.0 issue-62200.rs
issue-62200.rs:11:32: 11:52 error: internal compiler error: ../src/librustc_typeck/astconv.rs:916: anonymous bound regi\
on BrAnon(0) in binding but not trait ref
issue-62200.rs:11     F: FnOnce(<X as Ty>::V) -> Option<<X as Ty>::V>
                                                 ^~~~~~~~~~~~~~~~~~~~
```

**Comment by pnkfelix** [comment]
triage: P-medium. Removing nomination. Assigning to self.

**Comment by smmalis37** [comment]
I just ran into this on 1.41.1. I can try to produce a minimized version if it would be helpful.

**Comment by smmalis37** [comment]
If it helps, this slightly modified snippet produces a very odd error:

```rust
struct S {}

trait T<'a>{
    type A;
}

impl T<'_> for S {
    type A = i32;
}

fn foo<'a>(x: impl Fn(<S as T>::A) -> <S as T<'a>>::A) {
    x(2i32);
}

fn main() {
    foo(|x| x);
}
```

```
error[E0308]: mismatched types
  --> src/main.rs:12:7
   |
12 |     x(2i32);
   |       ^^^^ expected associated type, found `i32`
   |
   = note: expected associated type `<S as T<'_>>::A`
                         found type `i32`
   = note: consider constraining the associated type `<S as T<'_>>::A` to `i32` or calling a method that returns `<S as T<'_>>::A`
   = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
```

In that code `<S as T<'_>>::A` is `i32`, so it seems like something isn't being fully expanded somewhere?

**Comment by SeeSpring** [comment]
Seems related to #62201

```rust
struct S {}

trait T<'a> {
    type A;
}

impl T<'_> for S {
    type A = i32;
}

fn foo<'a>(x: impl Fn(<S as T>::A) -> <S as T<'a>>::A) {
    help(x, 2i32);
}

fn help<'a, TT: T<'a>, F>(f: F, t: <TT as T<'a>>::A) -> <S as T<'a>>::A
where
    F: Fn(<TT as T>::A) -> <S as T<'a>>::A,
{
    f(t)
}

fn main() {
    foo(|x| x)
}
```

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc_infer/traits/codegen/mod.rs:61: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@src/main.rs:23:9: 23:14] as std::ops::Fn<(<S as T<'_>>::A,)>>), Binder(<[closure@src/main.rs:23:9: 23:14] as std::ops::Fn<(i32,)>>), Sorts(ExpectedFound { expected: i32, found: <S as T<'_>>::A }))` selecting `Binder(<[closure@src/main.rs:23:9: 23:14] as std::ops::Fn<(i32,)>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc::ty::context::GlobalCtxt::enter_local
  21: rustc_infer::traits::codegen::codegen_fulfill_obligation
  22: rustc::ty::query::__query_compute::codegen_fulfill_obligation
  23: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::codegen_fulfill_obligation>::compute
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  26: rustc_ty::instance::resolve_instance
  27: rustc::ty::instance::Instance::resolve
  28: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc::mir::visit::Visitor>::visit_terminator_kind
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_session::utils::<impl rustc_session::session::Session>::time
  33: rustc_mir::monomorphize::collector::collect_crate_mono_items
  34: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  35: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  36: rustc::dep_graph::graph::DepGraph::with_task_impl
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  38: rustc_codegen_ssa::base::codegen_crate
  39: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  40: rustc_interface::passes::start_codegen
  41: rustc::ty::context::tls::enter_global
  42: rustc_interface::queries::Queries::ongoing_codegen
  43: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (3dbade652 2020-03-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::ops::Fn` fulfills its obligations
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=630d1c7db98eea220255d85669681b6d)
note that `t` in `help` needs to be generic to compile, but the output type can be changed to `<S as T<'a>>::A`
