### ISSUE TITLE
./x.py build OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by superriva** [rust-lang/rust#62676]
Trying to build from source on Ubuntu 18.04 x64
```
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 866, in main
    bootstrap(help_triggered)
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 834, in bootstrap
    build.download_stage0()
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 355, in download_stage0
    self._download_stage0_helper(filename, pattern)
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 390, in _download_stage0_helper
    get("{}/{}".format(url, filename), tarball, verbose=self.verbose)
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 26, in get
    download(sha_path, sha_url, False, verbose)
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 59, in download
    _download(path, url, probably_big, verbose, True)
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 86, in _download
    exception=exception)
  File "/tmp/z/rust/src/bootstrap/bootstrap.py", line 136, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
`Python 2.7.15+ (default, Nov 27 2018, 23:36:35)`

**Comment by sfackler** [comment]
You're probably missing curl: https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L81

**Comment by superriva** [comment]
@sfackler You absolutely right! I apologize! I didn't check `curl` because I thought it's default on linux.

**Comment by Lonami** [comment]
Maybe `x.py` could warn on missing required tools?

**Comment by gounthar** [comment]
I have curl, but I have the same error.
Something else must be missing:
` sudo apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
linaro@captation-techforum-rk3399-2GB:~/ffmpeg_sources/rust$ ./x.py build && ./x.py install
Updating only changed submodules
Submodules updated in 0.18 seconds
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/home/linaro/ffmpeg_sources/rust/src/bootstrap/bootstrap.py", line 866, in main
    bootstrap(help_triggered)
  File "/home/linaro/ffmpeg_sources/rust/src/bootstrap/bootstrap.py", line 837, in bootstrap
    build.build_bootstrap()
  File "/home/linaro/ffmpeg_sources/rust/src/bootstrap/bootstrap.py", line 648, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/home/linaro/ffmpeg_sources/rust/src/bootstrap/bootstrap.py", line 136, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`
