### ISSUE TITLE
Test `run-pass\backtrace-debuginfo.rs` fails on i686-pc-windows-msvc

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#62844]
Due to a regression in `compiletest` some `run-pass` tests weren't run properly for some time and this is one of the regressions that slipped through during that time.

https://github.com/rust-lang/rust/pull/62797#issuecomment-513516054
```
---- [run-pass] run-pass\backtrace-debuginfo.rs stdout ----

error: test run failed!
status: exit code: 101
command: PATH="D:\a\1\s\build\i686-pc-windows-msvc\stage2\lib\rustlib\i686-pc-windows-msvc\lib;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;D:\a\1\s\build\i686-pc-windows-msvc\stage0-bootstrap-tools\i686-pc-windows-msvc\release\deps;D:\a\1\s\build\i686-pc-windows-msvc\stage0\bin;D:\a\1\s\ninja;C:\Python27amd64;D:\a\1\s\citools\msys64\mingw32\bin;D:\a\1\s\citools\msys64\usr\bin;C:\Program Files (x86)\Inno Setup 5;D:\a\1\s\sccache;C:\agents\2.154.3\externals\git\cmd;C:\hostedtoolcache\windows\Python\3.6.8\x64;C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts;C:\Program Files\Mercurial;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS;C:\Program Files\Mercurial;C:\Program Files\Boost\1.69.0;C:\Users\VssAdministrator\.dotnet\tools;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\zulu-8-azure-jdk_8.38.0.13-8.0.212-win_x64\bin;C:\npm\prefix;C:\Program Files\Rust\.cargo\bin;C:\hostedtoolcache\windows\Ruby\2.5.3\x64\bin;C:\Go1.12.4\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\hostedtoolcache\windows\Python\3.6.8\Scripts;C:\hostedtoolcache\windows\Python\3.6.8;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft MPI\Bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\6;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\tools\php;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs;C:\Program Files\CMake\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\OpenSSL\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps" "D:\\a\\1\\s\\build\\i686-pc-windows-msvc\\test\\run-pass\\backtrace-debuginfo\\a.exe"
stdout:
------------------------------------------
---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:173", "backtrace-debuginfo.rs:109", "backtrace-debuginfo.rs:72", "backtrace-debuginfo-aux.rs:5"]

--- stdout
backtrace-debuginfo-aux.rs:5
backtrace-debuginfo.rs:72
backtrace-debuginfo.rs:109
backtrace-debuginfo.rs:173

--- stderr
test case 2
thread 'main' panicked at 'explicit panic', D:\a\1\s\src/test\run-pass\backtrace-debuginfo.rs:73:9
stack backtrace:
   0: 0x71809730 - std::panicking::take_hook::hfbb9fe42674c6a04
   1: 0x71809330 - std::panicking::take_hook::hfbb9fe42674c6a04
   2: 0x71809f61 - std::panicking::rust_panic_with_hook::h49a19dfc0991b7ac

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:173", "backtrace-debuginfo.rs:110"]

--- stdout
backtrace-debuginfo.rs:110
backtrace-debuginfo.rs:173

--- stderr
test case 4
thread 'main' panicked at 'explicit panic', D:\a\1\s\src/test\run-pass\backtrace-debuginfo.rs:84:5
stack backtrace:
   0: 0x71809730 - std::panicking::take_hook::hfbb9fe42674c6a04
   1: 0x71809330 - std::panicking::take_hook::hfbb9fe42674c6a04
   2: 0x71809f61 - std::panicking::rust_panic_with_hook::h49a19dfc0991b7ac

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:173", "backtrace-debuginfo.rs:110", "backtrace-debuginfo.rs:98", "backtrace-debuginfo-aux.rs:12"]

--- stdout
backtrace-debuginfo-aux.rs:12
backtrace-debuginfo.rs:98
backtrace-debuginfo.rs:110
backtrace-debuginfo.rs:173

--- stderr
test case 8
thread 'main' panicked at 'explicit panic', D:\a\1\s\src/test\run-pass\backtrace-debuginfo.rs:99:9
stack backtrace:
   0: 0x71809730 - std::panicking::take_hook::hfbb9fe42674c6a04
   1: 0x71809330 - std::panicking::take_hook::hfbb9fe42674c6a04
   2: 0x71809f61 - std::panicking::rust_panic_with_hook::h49a19dfc0991b7ac


------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'found some errors', D:\a\1\s\src/test\run-pass\backtrace-debuginfo.rs:163:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

------------------------------------------
```

cc @alexcrichton

**Comment by petrochenkov** [comment]
`run-pass\backtrace.rs` is also failing on `i686-pc-windows-msvc`.
```
---- [run-pass] run-pass\backtrace.rs stdout ----

error: test run failed!
status: exit code: 101
command: PATH="D:\a\1\s\build\i686-pc-windows-msvc\stage2\lib\rustlib\i686-pc-windows-msvc\lib;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;D:\a\1\s\build\i686-pc-windows-msvc\stage0-bootstrap-tools\i686-pc-windows-msvc\release\deps;D:\a\1\s\build\i686-pc-windows-msvc\stage0\bin;D:\a\1\s\ninja;C:\Python27amd64;D:\a\1\s\citools\msys64\mingw32\bin;D:\a\1\s\citools\msys64\usr\bin;C:\Program Files (x86)\Inno Setup 5;D:\a\1\s\sccache;C:\agents\2.154.3\externals\git\cmd;C:\hostedtoolcache\windows\Python\3.6.8\x64;C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts;C:\Program Files\Mercurial;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS;C:\Program Files\Mercurial;C:\Program Files\Boost\1.69.0;C:\Users\VssAdministrator\.dotnet\tools;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\zulu-8-azure-jdk_8.38.0.13-8.0.212-win_x64\bin;C:\npm\prefix;C:\Program Files\Rust\.cargo\bin;C:\hostedtoolcache\windows\Ruby\2.5.3\x64\bin;C:\Go1.12.4\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\hostedtoolcache\windows\Python\3.6.8\Scripts;C:\hostedtoolcache\windows\Python\3.6.8;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft MPI\Bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\6;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\tools\php;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs;C:\Program Files\CMake\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\OpenSSL\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps" "D:\\a\\1\\s\\build\\i686-pc-windows-msvc\\test\\run-pass\\backtrace\\a.exe"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'bad output: thread 'main' panicked at 'explicit panic', D:\a\1\s\src/test\run-pass\backtrace.rs:16:9
stack backtrace:
   0: std::panicking::take_hook
   1: std::panicking::take_hook
   2: std::panicking::rust_panic_with_hook
', D:\a\1\s\src/test\run-pass\backtrace.rs:66:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

------------------------------------------
```

**Comment by alexcrichton** [comment]
Thanks for the heads up, definitely want to keep these tests running! I've opened https://github.com/rust-lang/rust/pull/62897 to work towards fixing it.
