### ISSUE TITLE
rust-gdb doesn't set up path substitutions?

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust#62945]
I'm trying to use `rust-gdb` on project generated by `cargo new` and looks like the `rust-src` source code path is not configured:

```
Reading symbols from target/debug/hello...
(gdb) show directories
Source directories searched: ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc:$cdir:$cwd
(gdb) r
Starting program: target/debug/hello 

Program received signal SIGSEGV, Segmentation fault.
core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/a7f28678bbf4e16893bb6a718e427504167a9494/src/libcore/ops/function.rs:231
231	/rustc/a7f28678bbf4e16893bb6a718e427504167a9494/src/libcore/ops/function.rs: No such file or directory.
(gdb) set substitute-path /rustc/a7f28678bbf4e16893bb6a718e427504167a9494/ ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/
(gdb) l
226	    #[stable(feature = "fn_once_output", since = "1.12.0")]
227	    type Output;
228	
229	    /// Performs the call operation.
230	    #[unstable(feature = "fn_traits", issue = "29625")]
231	    extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
232	}
233	
234	mod impls {
235	    #[stable(feature = "rust1", since = "1.0.0")] 
```

**Comment by wesleywiser** [comment]
Visited during wg-debugging's triage meeting. We think this is most likely still an issue but probably not a high priority one. If someone wants to work on this, the first thing they should do is retest and verify this is still broken (but we think it most likely is). 

There may be a fairly simple resolution to modify rust-gdb to detect which toolchain it's being invoked from and then run the set substitute-path path with the appropriate paths. 

I'm willing to help mentor someone in fixing this 🙂

**Comment by diogofriggo** [comment]
can't reproduce it, it works just fine nearly 4 yrs later, has this perhaps already been fixed?

**Comment by lnicola** [comment]
Past @lnicola should have included a sample test case.

**Comment by lnicola** [comment]
No, I can still reproduce it. @diogofriggo are you maybe using a distro-provided toolchain?

Crashing program:

```rust
use std::sync::Once;

static INIT: Once = Once::new();

fn main() {
    INIT.call_once(|| unsafe {
        *(0xaabbccdd as *mut usize) = 1234;
    });
}
```

`gdb` output:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555568e15 in hello::expensive_computation () at src/main.rs:23
23	       *(0xaabbccdd as *mut usize) = 1234;
(gdb) bt
#0  0x0000555555568e15 in hello::expensive_computation () at src/main.rs:23
#1  0x0000555555568dc6 in hello::get_cached_val::{closure#0} () at src/main.rs:15
#2  0x0000555555568db1 in std::sync::once::{impl#2}::call_once::{closure#0}<hello::get_cached_val::{closure_env#0}> ()
    at /rustc/b955c8271da80a1af8a1d54c4e1bbdaf51b032e9/library/std/src/sync/once.rs:149
#3  0x0000555555568b77 in std::sys_common::once::futex::Once::call<std::sync::once::{impl#2}::call_once::{closure_env#0}<hello::get_cached_val::{closure_env#0}>> (
    self=0x5555555a5340 <hello::INIT::h9c84dac174d4d2e5>, ignore_poisoning=false, f=0x7fffffffdb28)
    at /rustc/b955c8271da80a1af8a1d54c4e1bbdaf51b032e9/library/std/src/sys_common/once/futex.rs:124
#4  0x0000555555568d16 in std::sync::once::Once::call_once<hello::get_cached_val::{closure_env#0}> (self=0x5555555a5340 <hello::INIT::h9c84dac174d4d2e5>, f=...)
    at /rustc/b955c8271da80a1af8a1d54c4e1bbdaf51b032e9/library/std/src/sync/once.rs:149
#5  0x0000555555568e04 in hello::get_cached_val () at src/main.rs:14
#6  0x0000555555568e36 in hello::main () at src/main.rs:29
(gdb) f 2
#2  0x0000555555568db1 in std::sync::once::{impl#2}::call_once::{closure#0}<hello::get_cached_val::{closure_env#0}> ()
    at /rustc/b955c8271da80a1af8a1d54c4e1bbdaf51b032e9/library/std/src/sync/once.rs:149
149	/rustc/b955c8271da80a1af8a1d54c4e1bbdaf51b032e9/library/std/src/sync/once.rs: No such file or directory.
```

To make `set substitute-path` work, don't use `~` in the replacement.
