### ISSUE TITLE
incremental compilation DepNode Bug running cargo check

### ISSUE THREAD

**Issue by acourdavault** [rust-lang/rust#63150]
# cargo check panic

# code that produced the panic
```rust
type Data = Vec<u8>;

#[derive(Debug)]
enum EventImpl{
    NoteOn(u8),
    NoteOff(u8)
}
#[derive(Debug)]
struct Event{
    data:Data,
    i:EventImpl
}

impl Event{
    fn new(data:Data)->Self{
        Event{
            i: match data[0]{
                0 => EventImpl::NoteOn(data[1]),
                1 => EventImpl::NoteOff(data[1]),
                _ => panic!("unk")
            },
            data:data
        }
    }
    
    fn data(&self)->&Data{
        &self.data
    }
}
type Seq = Vec<Event>;

impl PartialEq for Seq{
    fn eq(&self,o:&Self)->bool{
    // i have to learn the iterator implementation    
        let r=o.len()==self.len();
        if ! r{
            return false;
        }
        for i in 0..o.len() {
            r = r && o[i]==self[i];
        }
        r
    }
}

fn main() {
    let mut s:Seq=vec![Event::new(vec![1,2,3])];
    s.push(Event::new(vec![0,1,2]));
    let mut s2:Seq=vec![Event::new(vec![1,2,3]),Event::new(vec![0,1,2])];

    println!("Hello, world! {:?} {:?}",s, s[1].data());
    println!("S1 == S2 ? {}",s==s2);
}
```
# expected
```shell
   Compiling playground v0.0.1 (/playground)
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/main.rs:32:1
   |
32 | impl PartialEq for Seq{
   | ^^^^^^^^^^^^^^^^^^^^^^ impl doesn't use types inside crate
   |
   = note: the impl does not reference only types defined in this crate
   = note: define and implement a trait or new type instead

error: aborting due to previous error

For more information about this error, try `rustc --explain E0117`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```
(as seen in rust playground)

# observed
```
PS D:\wc\test_so> cargo check --verbose
    Checking test_so v0.1.0 (D:\wc\test_so)
     Running `rustc --edition=2018 --crate-name test_so src\main.rs --color always --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=0bbeeee7b98c47d4 -C extra-filename=-0bbeeee7b98c47d4 --out-dir D:\wc\test_so\target\debug\deps -C incremental=D:\wc\test_so\target\debug\incremental -L dependency=D:\wc\test_so\target\debug\deps`
error: internal compiler error: src\librustc\dep_graph\graph.rs:688: DepNode Hir(test_so[2397]::Event[0]::data[0]) should have been pre-allocated but wasn't.

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:637:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0 (a53f9df32 2019-07-03) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `test_so`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name test_so src\main.rs --color always --crate-type bin --emit=dep-info,metadata -C debuginfo=2 -C metadata=0bbeeee7b98c47d4 -C extra-filename=-0bbeeee7b98c47d4 --out-dir D:\wc\test_so\target\debug\deps -C incremental=D:\wc\test_so\target\debug\incremental -L dependency=D:\wc\test_so\target\debug\deps` (exit code: 101)
```

# meta
on windows 10, rustc 1.36.0 (a53f9df32 2019-07-03)

**Comment by idubrov** [comment]
Seeing similar issue in our project (`error: internal compiler error: src/librustc/dep_graph/graph.rs:687: DepNode Hir(bend[3a80]::{{impl}}[5]::from_request_inner[0]::{{misc}}[0]::{{misc}}[0]) should have been pre-allocated but wasn't.`).

What can I do to debug it / provide more information? I have it failing consistently on `cargo check --verbose`. I'm pretty sure I've seen it before and it always goes away if I do `cargo clean`, so must be related to incremental compilation.

I would rather not provide arguments to `rustc` (it's our internal product), but I can, maybe, run `rustc` with different arguments or do some experiments?

The stack trace for some reason is empty:
```
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: src/librustc/dep_graph/graph.rs:687: DepNode Hir(bend[3a80]::{{impl}}[5]::from_request_inner[0]::{{misc}}[0]::{{misc}}[0]) should have been pre-allocated but wasn't.

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:650:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

**Comment by pnkfelix** [comment]
its hard to act on cases like this since its very difficult to reproduce incremental compilation bugs based solely on a snapshot of the source code. Normally we need a transcript of some delta (preferably small)  between versions of the code in order to have a hope of reproducing the bug locally

**Comment by pnkfelix** [comment]
closing as non-actionable since we do not have information about what the delta was that caused the ICE to arise.
