### ISSUE TITLE
debuginfo/empty-string.rs test failed on Linux

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#63436]
When I run `x.py test` on Linux, `debuginfo/empty-string.rs` test failed with
the following error:

```rust
Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 122 tests
.iiiii..ii.....i..i...i..i.iFi..i.ii..iii....ii.ii....i..........iiii..........i.i.ii..ii.......ii.i 100/122
.iii.....iiiiii.....ii
failures:

---- [debuginfo-gdb+lldb] debuginfo/empty-string.rs stdout ----
NOTE: compiletest thinks it is using GDB with native rust support
NOTE: compiletest thinks it is using GDB version 7012000

error: line not found in debugger output: $2 = ""
status: exit code: 0
command: "/usr/bin/gdb" "-quiet" "-batch" "-nx" "-command=/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/test/debuginfo/empty-string/empty-string.debugger.script"
stdout:
------------------------------------------
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Breakpoint 1 at 0x267f: file /home/lzutao/forked/rust/compiler-rust/src/test/debuginfo/empty-string.rs, line 32.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, empty_string::main::h4739d54fd70936a5 () at /home/lzutao/forked/rust/compiler-rust/src/test/debuginfo/empty-string.rs:32
32          zzz(); // #break
$1 = ""
$2 = &str {data_ptr: 0x555555554a4e "attempt to create unaligned or null slicesrc/libcore/slice/mod.rsattempt to create slice covering half the address space\000", length: 0}
A debugging session is active.

        Inferior 1 [process 6653] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

------------------------------------------
stderr:
------------------------------------------

------------------------------------------



failures:
    [debuginfo-gdb+lldb] debuginfo/empty-string.rs

test result: FAILED. 73 passed; 1 failed; 48 ignored; 0 measured; 0 filtered out

thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:536:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

command did not execute successfully: "/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/home/lzuta
o/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/home/lzutao/forked/rust/compiler-rust/src/tes
t/debuginfo" "--build-base" "/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/test/debuginfo" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "debuginfo-gdb+lldb" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llv
m-filecheck" "/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--nodejs" "/home/lzutao/.local/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/home/lzutao/forked/rust/compiler-rust/build/
x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-py
thon" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "9.0.0-rust-1.38.0-dev-48818e9f5\n" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" ""
expected success, got: exit code: 101
```

#### Git commits

> * ffb85f3925 - (HEAD -> hashmap-prelude) Remove more HashMap redundantly imports errors (43 minutes ago)<Lzu Tao>
> * 3b490cc02e - Remove more HashMap redundantly imports errors (43 minutes ago)<Lzu Tao>
> * 00a5eb58d0 - Fix `HashMap` is imported redundantly (43 minutes ago)<Lzu Tao>
> * 5918257d87 - Replace HashpMap by BTreeMap in test suggested by Jonas (43 minutes ago)<Lzu Tao>
> * 3c1f25a832 - Fix some test to build (43 minutes ago)<Lzu Tao>
> * a32a2bb7dd - Add HashMap to std prelude (43 minutes ago)<Lzu Tao>
> *   d19a359444 - (upstream/master, upstream/HEAD, master) Auto merge of #63428 - Centril:rollup-c2ru1z1, r=Centril (7 hours ago)<bors>

**Comment by lzutao** [comment]
It seems like gdb cannot load the pretty printer:
Run the script manually, I got:
```rust
% "/usr/bin/gdb" "-quiet" "-nx" "-command=/home/lzutao/forked/rust/compiler-rust/build/x86_64-unknown-linux-gnu/test/debuginfo/empty-string/empty-string.debugger.script"       
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/lzutao/forked/rust/compiler-rust/src/etc/gdb_load_rust_pretty_printers.py", line 2, in <module>
    import gdb_rust_pretty_printing
ImportError: No module named 'gdb_rust_pretty_printing'
Breakpoint 1 at 0x263f: file /home/lzutao/forked/rust/compiler-rust/src/test/debuginfo/empty-string.rs, line 32.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, empty_string::main::h4739d54fd70936a5 () at /home/lzutao/forked/rust/compiler-rust/src/test/debuginfo/empty-string.rs:32
32          zzz(); // #break
$1 = alloc::string::String {vec: alloc::vec::Vec<u8> {buf: alloc::raw_vec::RawVec<u8, alloc::alloc::Global> {ptr: core::ptr::unique::Unique<u8> {pointer: 0x1 <error: Cannot access memory at address 0x1>, _marker: core::marker::PhantomData<u8>}, cap: 0, a: alloc::alloc::Gl
obal}, len: 0}}
$2 = &str {data_ptr: 0x5555555549fe "attempt to create unaligned or null slicesrc/libcore/slice/mod.rsattempt to create slice covering half the address space\000", length: 0}
A debugging session is active.

        Inferior 1 [process 14010] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
```

**Comment by lzutao** [comment]
rust-gdb load and run the script fine.
