### ISSUE TITLE
ICE in import resolution with renamed crate import

### ISSUE THREAD

**Issue by shawntabrizi** [rust-lang/rust#64143]
I tried renaming a crate import and a bunch of dependent uses of the crate, and ended up seeing a unexpected panic in the compiler.

Log is here: https://gitlab.parity.io/parity/substrate/-/jobs/223357

```
Compiling srml-support v2.0.0 (/builds/parity/substrate/srml/support)
thread 'rustc' panicked at 'src/librustc_resolve/resolve_imports.rs:847: inconsistent resolution for an import', src/librustc/util/bug.rs:37:26
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: rustc::util::common::panic_hook
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::begin_panic
   9: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  10: rustc::ty::context::tls::with_opt::{{closure}}
  11: rustc::ty::context::tls::with_context_opt
  12: rustc::ty::context::tls::with_opt
  13: rustc::util::bug::opt_span_bug_fmt
  14: rustc::util::bug::span_bug_fmt
  15: rustc_resolve::resolve_imports::ImportResolver::finalize_import
  16: rustc_resolve::resolve_imports::ImportResolver::finalize_imports
  17: rustc_resolve::Resolver::resolve_crate
  18: rustc::util::common::time
  19: rustc_interface::passes::configure_and_expand_inner
  20: rustc_interface::passes::configure_and_expand::{{closure}}
  21: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  22: rustc_interface::passes::configure_and_expand
  23: rustc_interface::queries::Query<T>::compute
  24: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::expansion
  25: rustc_interface::interface::run_compiler_in_existing_thread_pool
  26: std::thread::local::LocalKey<T>::with
  27: scoped_tls::ScopedKey<T>::set
  28: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (9af17757b 2019-09-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C panic=abort -C link-arg=--export-table -C link-arg=--export=__heap_base --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `srml-support`.

To learn more, run the command again with --verbose.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `node-runtime v2.0.0 (/builds/parity/substrate/node/runtime)`

Caused by:
  process didn't exit successfully: `/builds/parity/substrate/target/release/build/node-runtime-8543150fed0dc4f2/build-script-build` (exit code: 1)
--- stdout
Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/builds/parity/substrate/target/release/wbuild/node-runtime/Cargo.toml" "--release"
```

This was the specific commit, but errors may have started one commit before:

https://github.com/paritytech/substrate/pull/3543/commits/ba2ec61da7acc36821a70e76a31a6a5bf13bbe95

**Comment by hellow554** [comment]
I can confirm the ICE with https://github.com/paritytech/substrate/pull/3543/commits/9a6070450107dec17784ba34af4b871023f6dc81 and `rustc 1.39.0-nightly (dfd43f0fd 2019-09-01)`

**Comment by estebank** [comment]
CC @petrochenkov

**Comment by nikomatsakis** [comment]
check-in from compiler triage:

I'm going with medium priority on this; it looks like @petrochenkov is working on it already in any case. In particular, this isn't marked as a regression, and I *think* the ICE is primarily affecting an "in-progress" change, so it's not blocking anything on crates.io from building or anything like that (right?).

**Comment by shawntabrizi** [comment]
This ICE is not blocking anything on my side.

**Comment by petrochenkov** [comment]
@shawntabrizi 
Could you clarify, does the issue happen only during cross-compilation to wasm?
That's what I see in the log:
```
Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/builds/parity/substrate/target/release/wbuild/node-template-runtime/Cargo.toml" "--release"
```
In that case this is a duplicate of https://github.com/rust-lang/rust/issues/56935 or https://github.com/rust-lang/rust/issues/64450.

I wasn't able to reproduce the cross-compilation testing locally, and without cross-compilation the build completes successfully at least `srml-support`.

**Comment by petrochenkov** [comment]
In general, help with a minimized reproduction would be appreciated.
It's hard to reproduce issues in a crate with 600 dependencies and a bunch of non-Rust pre-requisites some of which don't build on my platform.

**Comment by shawntabrizi** [comment]
@petrochenkov Sorry, I wont be able to help with a minimal reproduction step. It is just something I ran into and reported. I will close this issue, and allow you to reopen if you feel you can further investigate.
