### ISSUE TITLE
rustdoc crashes parsing yet another strange doc-comment on 1.37

### ISSUE THREAD

**Issue by bobbobbio** [rust-lang/rust#64397]
I had a similar issue on 1.36 that seemed to have been fixed: https://github.com/rust-lang/rust/issues/62571

That fix looks like it went into 1.37, but I'm getting a crash running on a similar doc comment once again.

Here is the offending doc-comment
```
#[doc = " |  _ \\ __ _ _ __ ___  ___  | |__   __ _ ___  ___  |  _ \\| \\ | | | (_)___| |_"]
#[doc = " | |_) / _` | \'__/ __|/ _ \\ | \'_ \\ / _` / __|/ _ \\ | | | |  \\| | | | / __| __|"]
#[doc = " |  __/ (_| | |  \\__ \\  __/ | |_) | (_| \\__ \\  __/ | |_| | |\\  | | | \\__ \\ |_"]
```

And here is the backtrace
```
thread 'rustc' panicked at 'slice index starts at 1 but ends at 0', src/libcore/slice/mod.rs:2561:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/backtrace/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2561
  11: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/slice/mod.rs:2730
  12: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/slice/mod.rs:2813
  13: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/slice/mod.rs:2538
  14: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1756
  15: pulldown_cmark::parse::InlineStack::find_match
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/pulldown-cmark/src/parse.rs:1523
  16: pulldown_cmark::parse::Parser::handle_emphasis
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/pulldown-cmark/src/parse.rs:2081
  17: pulldown_cmark::parse::Parser::handle_inline
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/pulldown-cmark/src/parse.rs:1825
  18: <pulldown_cmark::parse::Parser as core::iter::traits::iterator::Iterator>::next
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/pulldown-cmark/src/parse.rs:2482
  19: rustdoc::html::markdown::find_testable_code
             at src/librustdoc/html/markdown.rs:544
  20: rustdoc::passes::look_for_tests
             at src/librustdoc/passes/mod.rs:338
  21: <rustdoc::passes::private_items_doc_tests::PrivateItemDocTestLinter as rustdoc::fold::DocFolder>::fold_item
             at src/librustdoc/passes/private_items_doc_tests.rs:35
  22: rustdoc::fold::DocFolder::fold_inner_recur::{{closure}}
             at src/librustdoc/fold.rs:63
  23: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/adapters/mod.rs:826
  24: core::iter::traits::iterator::Iterator::try_fold
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/traits/iterator.rs:1573
  25: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/adapters/mod.rs:826
  26: core::iter::traits::iterator::Iterator::try_for_each
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/traits/iterator.rs:1610
  27: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/adapters/mod.rs:812
  28: alloc::vec::Vec<T>::extend_desugared
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:2003
  29: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1900
  30: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1895
  31: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1796
  32: core::iter::traits::iterator::Iterator::collect
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/traits/iterator.rs:1466
  33: rustdoc::fold::DocFolder::fold_mod
             at src/librustdoc/fold.rs:100
  34: rustdoc::fold::DocFolder::fold_inner_recur
             at src/librustdoc/fold.rs:27
  35: rustdoc::fold::DocFolder::fold_item_recur
             at src/librustdoc/fold.rs:90
  36: <rustdoc::passes::private_items_doc_tests::PrivateItemDocTestLinter as rustdoc::fold::DocFolder>::fold_item
             at src/librustdoc/passes/private_items_doc_tests.rs:37
  37: rustdoc::fold::DocFolder::fold_inner_recur::{{closure}}
             at src/librustdoc/fold.rs:63
  38: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/adapters/mod.rs:826
  39: core::iter::traits::iterator::Iterator::try_fold
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/traits/iterator.rs:1573
  40: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/adapters/mod.rs:826
  41: core::iter::traits::iterator::Iterator::try_for_each
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/traits/iterator.rs:1610
  42: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/adapters/mod.rs:812
  43: alloc::vec::Vec<T>::extend_desugared
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:2003
  44: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1900
  45: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1895
  46: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/vec.rs:1796
  47: core::iter::traits::iterator::Iterator::collect
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/iter/traits/iterator.rs:1466
  48: rustdoc::fold::DocFolder::fold_mod
             at src/librustdoc/fold.rs:100
  49: rustdoc::fold::DocFolder::fold_inner_recur
             at src/librustdoc/fold.rs:27
  50: rustdoc::fold::DocFolder::fold_item_recur
             at src/librustdoc/fold.rs:90
  51: <rustdoc::passes::private_items_doc_tests::PrivateItemDocTestLinter as rustdoc::fold::DocFolder>::fold_item
             at src/librustdoc/passes/private_items_doc_tests.rs:37
  52: rustdoc::fold::DocFolder::fold_crate::{{closure}}
             at src/librustdoc/fold.rs:105
  53: core::option::Option<T>::and_then
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libcore/option.rs:624
  54: rustdoc::fold::DocFolder::fold_crate
             at src/librustdoc/fold.rs:105
  55: rustdoc::passes::private_items_doc_tests::check_private_items_doc_tests
             at src/librustdoc/passes/private_items_doc_tests.rs:27
  56: rustdoc::core::run_core::{{closure}}::{{closure}}
             at src/librustdoc/core.rs:463
  57: rustc_interface::passes::BoxedGlobalCtxt::enter::{{closure}}::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/passes.rs:803
  58: rustc::ty::context::tls::enter_global::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1963
  59: rustc::ty::context::tls::enter_context::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1929
  60: rustc::ty::context::tls::set_tlv
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1862
  61: rustc::ty::context::tls::enter_context
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1928
  62: rustc::ty::context::tls::enter_global
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1962
  63: rustc_interface::passes::BoxedGlobalCtxt::enter::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/passes.rs:803
  64: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/<::rustc_data_structures::box_region::declare_box_region_type macros>:17
  65: rustc_interface::passes::create_global_ctxt::{{closure}}
             at src/librustc_interface/passes.rs:869
  66: alloc::boxed::<impl core::ops::generator::Generator for core::pin::Pin<alloc::boxed::Box<G>>>::resume
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/liballoc/boxed.rs:897
  67: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::access
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_data_structures/box_region.rs:52
  68: rustc_interface::passes::BoxedGlobalCtxt::access
             at /work/toolchain/packages/rust/rustc-1.37.0-src/<::rustc_data_structures::box_region::declare_box_region_type macros>:19
  69: rustc_interface::passes::BoxedGlobalCtxt::enter
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/passes.rs:803
  70: rustdoc::core::run_core::{{closure}}
             at src/librustdoc/core.rs:355
  71: rustc_interface::interface::run_compiler_in_existing_thread_pool
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/interface.rs:123
  72: rustdoc::core::run_core
             at src/librustdoc/core.rs:341
  73: rustdoc::rust_input::{{closure}}
             at src/librustdoc/lib.rs:458
  74: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/panic.rs:315
  75: std::panicking::try::do_call
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/panicking.rs:296
  76: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  77: std::panicking::try
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/panicking.rs:275
  78: std::panic::catch_unwind
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/panic.rs:394
  79: rustc_driver::report_ices_to_stderr_if_any
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_driver/lib.rs:1116
  80: rustdoc::rust_input
             at src/librustdoc/lib.rs:455
  81: rustdoc::main_options
             at src/librustdoc/lib.rs:411
  82: rustdoc::main_args::{{closure}}
             at src/librustdoc/lib.rs:384
  83: rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/util.rs:192
  84: rustc::ty::context::tls::with_thread_locals::{{closure}}::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1917
  85: std::thread::local::LocalKey<T>::try_with
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/thread/local.rs:257
  86: std::thread::local::LocalKey<T>::with
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/thread/local.rs:234
  87: rustc::ty::context::tls::with_thread_locals::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1909
  88: std::thread::local::LocalKey<T>::try_with
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/thread/local.rs:257
  89: std::thread::local::LocalKey<T>::with
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libstd/thread/local.rs:234
  90: rustc::ty::context::tls::with_thread_locals
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc/ty/context.rs:1901
  91: rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/util.rs:192
  92: scoped_tls::ScopedKey<T>::set
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/scoped-tls/src/lib.rs:137
  93: rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/util.rs:188
  94: scoped_tls::ScopedKey<T>::set
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/scoped-tls/src/lib.rs:137
  95: syntax::with_globals::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libsyntax/lib.rs:108
  96: scoped_tls::ScopedKey<T>::set
             at /work/toolchain/packages/rust/rustc-1.37.0-src/vendor/scoped-tls/src/lib.rs:137
  97: syntax::with_globals
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/libsyntax/lib.rs:107
  98: rustc_interface::util::spawn_thread_pool::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/util.rs:187
  99: rustc_interface::util::scoped_thread::{{closure}}
             at /work/toolchain/packages/rust/rustc-1.37.0-src/src/librustc_interface/util.rs:164
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bobbobbio** [comment]
I'm sorry. It seems that the original issue I linked must not be fixed in 1.37. If I try this or the original issue on nightly, it goes away. So I probably just was wrong about which release the fix went into.
