### ISSUE TITLE
rust-1.38: bootstrap linker=clang: error: failed to run custom build command for `ryu v1.0.0` // Caused by: process didn't exit successfully: `.../work/rustc-1.38.0-src/build/bootstrap/debug/build/ryu-deb3460cf2bb47d1/build-script-build` (signal: 11, SIGSEGV [...]

### ISSUE THREAD

**Issue by perfect7gentleman** [rust-lang/rust#64903]
```
running: /tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/cargo build --manifest-path /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/bootstrap/Cargo.toml --verbose --locked --frozen
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.35
   Compiling serde v1.0.92
   Compiling libc v0.2.60
   Compiling ryu v1.0.0
   Compiling fixedbitset v0.1.9
   Compiling cc v1.0.35
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name build_script_build /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/proc-macro2/build.rs --color always --crate-type bin --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=73b233e31e645dad -C extra-filename=-73b233e31e645dad --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/proc-macro2-73b233e31e645dad -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name unicode_xid /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/unicode-xid/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="default"' -C metadata=adf96169a1a7ea00 -C extra-filename=-adf96169a1a7ea00 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name build_script_build /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/syn/build.rs --color always --crate-type bin --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=edd26050ab2cbf16 -C extra-filename=-edd26050ab2cbf16 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/syn-edd26050ab2cbf16 -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name build_script_build /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/serde/build.rs --color always --crate-type bin --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="serde_derive"' --cfg 'feature="std"' -C metadata=3382a5780ebba442 -C extra-filename=-3382a5780ebba442 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/serde-3382a5780ebba442 -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name build_script_build /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/libc/build.rs --color always --crate-type bin --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=382d8539f85e2a38 -C extra-filename=-382d8539f85e2a38 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/libc-382d8539f85e2a38 -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name build_script_build /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/ryu/build.rs --color always --crate-type bin --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on -C metadata=deb3460cf2bb47d1 -C extra-filename=-deb3460cf2bb47d1 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/ryu-deb3460cf2bb47d1 -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name fixedbitset /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/fixedbitset/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=5dc644754f6e93a5 -C extra-filename=-5dc644754f6e93a5 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name cc /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/cc/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=029dea8777d25e5d -C extra-filename=-029dea8777d25e5d --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
   Compiling unicode-width v0.1.5
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name unicode_width /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/unicode-width/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="default"' -C metadata=8d9ae87263799cf8 -C extra-filename=-8d9ae87263799cf8 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
   Compiling cfg-if v0.1.8
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name cfg_if /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/cfg-if/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=ef75cc763ff14f71 -C extra-filename=-ef75cc763ff14f71 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
   Compiling ordermap v0.3.5
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name ordermap /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/ordermap/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=1f4b95adccf76dea -C extra-filename=-1f4b95adccf76dea --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
   Compiling itoa v0.4.4
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name itoa /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/itoa/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=561c85ccf52c7602 -C extra-filename=-561c85ccf52c7602 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
   Compiling lazy_static v1.3.0
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name lazy_static /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/lazy_static/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=3edae4655874533f -C extra-filename=-3edae4655874533f --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -C linker=clang`
   Compiling build_helper v0.1.0 (/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/build_helper)
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --edition=2018 --crate-name build_helper src/build_helper/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=428217be61cb03b8 -C extra-filename=-428217be61cb03b8 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -C incremental=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/incremental -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -Cdebuginfo=2 -C linker=clang`
   Compiling getopts v0.2.19
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/rustc --crate-name getopts /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/vendor/getopts/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debug-assertions=off -C overflow-checks=on -C metadata=818a0bd779e64845 -C extra-filename=-818a0bd779e64845 --out-dir /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps -L dependency=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps --extern unicode_width=/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/deps/libunicode_width-8d9ae87263799cf8.rlib --cap-lints allow -Cdebuginfo=2 -C linker=clang`
     Running `/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/ryu-deb3460cf2bb47d1/build-script-build`
error: failed to run custom build command for `ryu v1.0.0`

Caused by:
  process didn't exit successfully: `/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/build/bootstrap/debug/build/ryu-deb3460cf2bb47d1/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/bootstrap/bootstrap.py", line 866, in main
    bootstrap(help_triggered)
  File "/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/bootstrap/bootstrap.py", line 837, in bootstrap
    build.build_bootstrap()
  File "/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/bootstrap/bootstrap.py", line 648, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/portage/dev-lang/rust-1.38.0/work/rust-stage0/bin/cargo build --manifest-path /tmp/portage/dev-lang/rust-1.38.0/work/rustc-1.38.0-src/src/bootstrap/Cargo.toml --verbose --locked --frozen
```
LLVM/Clang-9.0
```
 ~ $ clang -v
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/9/bin
Selected GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
```
~ $ llvm-config --version
9.0.0libcxx
```
```
sys-devel/clang-9.0.0::gentoo was built with the following:
USE="default-compiler-rt default-libcxx -debug -doc -static-analyzer -test -xml" LLVM_TARGETS="(X86) -AArch64 -AMDGPU -ARM -BPF -Hexagon -Lanai -MSP430 -Mips -NVPTX -PowerPC -RISCV -Sparc -SystemZ -WebAssembly -XCore" PYTHON_SINGLE_TARGET="python3_7 -python2_7 -python3_5 -python3_6" PYTHON_TARGETS="python3_7 -python2_7 -python3_5 -python3_6"
CFLAGS="-march=native -mtune=native -O2 -pipe -fomit-frame-pointer -fno-plt -fno-stack-protector -flto=thin"
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fomit-frame-pointer -fno-plt -fno-stack-protector -flto=thin -stdlib=libc++"
FEATURES="strict distlocks parallel-install preserve-libs ipc-sandbox unmerge-logs binpkg-logs usersync assume-digests sfperms xattr unmerge-orphans protect-owned userfetch config-protect-if-modified unknown-features-warn usersandbox merge-sync binpkg-dostrip multilib-strict news network-sandbox binpkg-docompress pid-sandbox sandbox userpriv ebuild-locks parallel-fetch fixlafiles"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--strip-debug -Wl,--thinlto-jobs=9 -flto=thin -fuse-ld=lld"
```

**Comment by splitice** [comment]
I can confirm same results on armv7l

**Comment by jyn514** [comment]
@perfect7gentleman @splitice are you still running into this issue?

**Comment by splitice** [comment]
We moved that project away from rust due to this issue @jyn514 

It was my only exposure on arm to rust.

**Comment by perfect7gentleman** [comment]
@jyn514, nope.

**Comment by mati865** [comment]
FYI this looks like typical LLVM crash which were much more common with older versions.
