### ISSUE TITLE
rustc panic on pattern matching when no unit type instance is specified

### ISSUE THREAD

**Issue by johnlepikhin** [rust-lang/rust#64953]
I forgot to add () inside Some():

```
fn main() {
	match Some(()) {
		Some() => (),
		None => (),
	}
}
```

Got panic:

```
$ RUST_BACKTRACE=full cargo build
   Compiling crash v0.1.0 (/tmp/crash)
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', src/librustc_typeck/check/pat.rs:729:23
stack backtrace:
   0:     0x7f85ac9edad4 - backtrace::backtrace::libunwind::trace::h7ad6a8b922fcbc6b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x7f85ac9edad4 - backtrace::backtrace::trace_unsynchronized::hbac2e1529d61bd77
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x7f85ac9edad4 - std::sys_common::backtrace::_print_fmt::hbe7c998fd23d81c1
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x7f85ac9edad4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd16e96c1802eeddf
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x7f85aca2611c - core::fmt::write::h6eabb3ca7a98a71e
                               at src/libcore/fmt/mod.rs:1030
   5:     0x7f85ac9e1cf7 - std::io::Write::write_fmt::h9ff2cb44f8ed5906
                               at src/libstd/io/mod.rs:1412
   6:     0x7f85ac9f2305 - std::sys_common::backtrace::_print::h156faaaa311a1c35
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x7f85ac9f2305 - std::sys_common::backtrace::print::hd8f44adca3b9c7af
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f85ac9f2305 - std::panicking::default_hook::{{closure}}::h7d7cdcb2c7cdbed8
                               at src/libstd/panicking.rs:196
   9:     0x7f85ac9f1ff6 - std::panicking::default_hook::hb4a9065c39b6e99a
                               at src/libstd/panicking.rs:210
  10:     0x7f85acf28763 - rustc_driver::report_ice::h9cc52dc823233a99
  11:     0x7f85ac9f2aec - std::panicking::rust_panic_with_hook::haa206b44ed70b8bb
                               at src/libstd/panicking.rs:477
  12:     0x7f85ac9f25a2 - std::panicking::continue_panic_fmt::h4f54b156fa6d4e21
                               at src/libstd/panicking.rs:380
  13:     0x7f85ac9f2496 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  14:     0x7f85aca1faaa - core::panicking::panic_fmt::h6f2ecda11bddbc92
                               at src/libcore/panicking.rs:85
  15:     0x7f85aca1fa65 - core::panicking::panic_bounds_check::h7a713bdad7b06331
                               at src/libcore/panicking.rs:61
  16:     0x7f85ad476ea9 - rustc_typeck::check::pat::<impl rustc_typeck::check::FnCtxt>::check_pat_tuple_struct::h73ce997b2ae28249
  17:     0x7f85ad4741a6 - rustc_typeck::check::pat::<impl rustc_typeck::check::FnCtxt>::check_pat::h1154b576e5c15482
  18:     0x7f85ad6441d3 - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::hf9b0f18d120905db
  19:     0x7f85ad4726e6 - rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match::h516add054d139735
  20:     0x7f85ad485d09 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::h19abb1ae80745f34
  21:     0x7f85ad484b7b - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::h37043b23577c990f
  22:     0x7f85ad4ba988 - rustc_typeck::check::FnCtxt::check_block_with_expected::h12945972370b33ff
  23:     0x7f85ad48577e - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::h19abb1ae80745f34
  24:     0x7f85ad484b7b - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::h37043b23577c990f
  25:     0x7f85ad48ea7b - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr::h3c4f69ba1cce95ca
  26:     0x7f85ad4a837d - rustc_typeck::check::check_fn::hf50a0a355f4a9ef3
  27:     0x7f85ad612fc8 - rustc::ty::context::GlobalCtxt::enter_local::h9b115692e8d80545
  28:     0x7f85ad4a7368 - rustc_typeck::check::typeck_tables_of::hbebf8ec408c8c987
  29:     0x7f85ad4f58ea - rustc::ty::query::__query_compute::typeck_tables_of::h6d0d1f8c25893b23
  30:     0x7f85ad58c4ab - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute::h96aaedbb379690ed
  31:     0x7f85ad529132 - rustc::dep_graph::graph::DepGraph::with_task_impl::hfad24bebe9e54fb5
  32:     0x7f85ad5eff51 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::hc7562d06be9c9f5e
  33:     0x7f85ad58925f - rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners::h82ab751e7b924778
  34:     0x7f85ad4a6ddd - rustc_typeck::check::typeck_item_bodies::h1f4c0a67bd6d912c
  35:     0x7f85ad4f5d35 - rustc::ty::query::__query_compute::typeck_item_bodies::h8781c7d95039fad8
  36:     0x7f85ad51e4d4 - rustc::dep_graph::graph::DepGraph::with_task_impl::h7bbb1550aebf51f1
  37:     0x7f85ad5ff88d - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::hec0517a60c6f224a
  38:     0x7f85ad4fab9e - rustc::util::common::time::he5ec949cbd28152e
  39:     0x7f85ad6d1c6f - rustc_typeck::check_crate::h45efac8225124edd
  40:     0x7f85acfd760a - rustc_interface::passes::analysis::h1a2029d49a642db4
  41:     0x7f85aceebcc1 - rustc::ty::query::__query_compute::analysis::hb144bea793c7c81b
  42:     0x7f85acecfdc2 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::hb7f5e01e00f10efb
  43:     0x7f85acef37ea - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::hbcd26733fe2516fa
  44:     0x7f85ad054eca - rustc_interface::passes::create_global_ctxt::{{closure}}::hce4659f662f1362b
  45:     0x7f85acef570e - rustc_interface::interface::run_compiler_in_existing_thread_pool::h3eacfe71c460b918
  46:     0x7f85acf2a872 - std::thread::local::LocalKey<T>::with::haa3657031f9a9086
  47:     0x7f85acf2f97e - scoped_tls::ScopedKey<T>::set::h5424f26f60b0ba2e
  48:     0x7f85acf500c2 - syntax::with_globals::h8be135a59913b377
  49:     0x7f85acebd6b0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h73f273238896f8e9
  50:     0x7f85aca0323a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  51:     0x7f85acee6f19 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h24793ad2ddc98e02
  52:     0x7f85ac9d41df - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1e72a7e97d9b2974
                               at /rustc/9689670079a48b06b5c440cc41844dab663e9dca/src/liballoc/boxed.rs:922
  53:     0x7f85aca01ee0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5d9592ea096e0c24
                               at /rustc/9689670079a48b06b5c440cc41844dab663e9dca/src/liballoc/boxed.rs:922
  54:     0x7f85aca01ee0 - std::sys_common::thread::start_thread::h4ca8b5ada9cddd3c
                               at src/libstd/sys_common/thread.rs:13
  55:     0x7f85aca01ee0 - std::sys::unix::thread::Thread::new::thread_start::hd5b5a48a9ec7adde
                               at src/libstd/sys/unix/thread.rs:79
  56:     0x7f85ac91bfa3 - start_thread
  57:     0x7f85ac83b4cf - clone
  58:                0x0 - <unknown>
```

## Meta

rustc 1.39.0-beta.1 (968967007 2019-09-24)
binary: rustc
commit-hash: 9689670079a48b06b5c440cc41844dab663e9dca
commit-date: 2019-09-24
host: x86_64-unknown-linux-gnu
release: 1.39.0-beta.1
LLVM version: 9.0

**Comment by Mark-Simulacrum** [comment]
This is fixed on the most recent beta. Thanks for the report!
