### ISSUE TITLE
Error while building rustc on Windows MSVC (cl.exe returns 2)

### ISSUE THREAD

**Issue by mgostIH** [rust-lang/rust#65065]
Building with x.py on Windows, I already have Rust working thru rustup, but I wanted to build a patched rustc.
However this error comes before stage1 begins and is related to cl.exe not compiling something I haven't touched; I made sure to update all the submodules with git and solved some errors I had with earlier stages of bootstrapping, but I don't know how to fix this.

Run with RUST_BACKTRACE=1 on a Git Bash console, OS Windows 7.

If you need any more information, sure ask, the error cl gives is quite generic and online I've found the issue could be related to anything.

```
Compiling rustc_llvm v0.0.0 (C:\Users\user\Desktop\Coding\Github\rust\src\librustc_llvm)
error: failed to run custom build command for `rustc_llvm v0.0.0 (C:\Users\user\Desktop\Coding\Github\rust\src\librustc_llvm)`

Caused by:
  process didn't exit successfully: `C:\Users\user\Desktop\Coding\Github\rust\build\x86_64-pc-windows-msvc\stage0-codegen\release\build\rustc_llvm-53b15cdc99a3c443\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MT" "/O2" "-IC:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\llvm\\include" "/EHs-c-" "/GR-" "-D_CRT_SECURE_NO_DEPRECATE" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_NONSTDC_NO_DEPRECATE" "-D_CRT_NONSTDC_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-DUNICODE" "-D_UNICODE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "/DLLVM_COMPONENT_AARCH64" "/DLLVM_COMPONENT_ARM" "/DLLVM_COMPONENT_ASMPARSER" "/DLLVM_COMPONENT_BITREADER" "/DLLVM_COMPONENT_BITWRITER" "/DLLVM_COMPONENT_HEXAGON" "/DLLVM_COMPONENT_INSTRUMENTATION" "/DLLVM_COMPONENT_IPO" "/DLLVM_COMPONENT_LINKER" "/DLLVM_COMPONENT_LTO" "/DLLVM_COMPONENT_MIPS" "/DLLVM_COMPONENT_MSP430" "/DLLVM_COMPONENT_NVPTX" "/DLLVM_COMPONENT_POWERPC" "/DLLVM_COMPONENT_RISCV" "/DLLVM_COMPONENT_SPARC" "/DLLVM_COMPONENT_SYSTEMZ" "/DLLVM_COMPONENT_WEBASSEMBLY" "/DLLVM_COMPONENT_X86" "/DLLVM_RUSTLLVM" "/DNDEBUG" "/FoC:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\build\\rustc_llvm-967e43a15e8972c9\\out\\../rustllvm\\PassWrapper.o" "/c" "../rustllvm/PassWrapper.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.35\src\lib.rs:2398:5
stack backtrace:
   0: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\sys_common\backtrace.rs:60
   1: core::fmt::write
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libcore\fmt\mod.rs:1030
   2: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\io\mod.rs:1413
   3: std::panicking::default_hook::{{closure}}
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\panicking.rs:196
   4: std::panicking::default_hook
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\panicking.rs:212
   5: std::panicking::rust_panic_with_hook
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\panicking.rs:473
   6: std::panicking::continue_panic_fmt
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\panicking.rs:380
   7: std::panicking::begin_panic_fmt
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\panicking.rs:335
   8: cc::Tool::to_command
   9: cc::Build::compile
  10: alloc::alloc::box_free
  11: alloc::raw_vec::RawVec<T,A>::reserve
  12: std::panicking::try::do_call<closure-0,i32>
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\panicking.rs:292
  13: panic_unwind::__rust_maybe_catch_panic
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libpanic_unwind\lib.rs:80
  14: std::rt::lang_start_internal
             at /rustc/9689670079a48b06b5c440cc41844dab663e9dca\/src\libstd\rt.rs:48
  15: main
  16: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

command did not execute successfully: "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\bin\\cargo.exe" "build" "-Zconfig-profile" "--target" "x86_64-pc-windows-msvc" "-Zbinary-dep-depinfo" "-j" "4" "--release" "--manifest-path" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\src/librustc_codegen_llvm/Cargo.toml" "--features" "" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: C:\Users\user\Desktop\Coding\Github\rust\build\bootstrap\debug\bootstrap build
Build completed unsuccessfully in 0:11:18
```

**Comment by mgostIH** [comment]
Apparently I was able to overcome this one issue by downloading the latest VC++ build tools and running `python x.py build` from the dev console, however now the problem comes in the next pass, still related to LLVM, except here the linker is failing with a different error message, possibly related to some UTF8 encode error, as I tried switching to the x64 version of cl aswell by changing the PATH environment variable but no difference was seen.
I am gonna investigate more tomorrow, but here is the full thing:

```
   Compiling rustc_codegen_llvm v0.0.0 (C:\Users\user\Desktop\Coding\Github\rust
\src\librustc_codegen_llvm)
error: linking with `link.exe` failed: exit code: 1112
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\V
C\\Tools\\MSVC\\14.23.28105\\bin\\Hostx64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT"
"/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windo
ws-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\
user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codeg
en\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.r
ustc_codegen_llvm.adbupitk-cgu.0.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Gith
ub\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\
\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk-
cgu.1.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-
windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codeg
en_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk-cgu.10.rcgu.o" "C:\\Users\\
user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codeg
en\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.r
ustc_codegen_llvm.adbupitk-cgu.11.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Git
hub\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc
\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk
-cgu.12.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-p
c-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_cod
egen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk-cgu.13.rcgu.o" "C:\\Users
\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-cod
egen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd
.rustc_codegen_llvm.adbupitk-cgu.14.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\G
ithub\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-ms
vc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupi
tk-cgu.15.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64
-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_c
odegen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk-cgu.2.rcgu.o" "C:\\User
s\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-co
degen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527d
d.rustc_codegen_llvm.adbupitk-cgu.3.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\G
ithub\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-ms
vc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupi
tk-cgu.4.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-
pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_co
degen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk-cgu.5.rcgu.o" "C:\\Users
\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-cod
egen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd
.rustc_codegen_llvm.adbupitk-cgu.6.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Gi
thub\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msv
c\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupit
k-cgu.7.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-p
c-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_cod
egen_llvm-7ace2575052527dd.rustc_codegen_llvm.adbupitk-cgu.8.rcgu.o" "C:\\Users\
\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-code
gen\\x86_64-pc-windows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.
rustc_codegen_llvm.adbupitk-cgu.9.rcgu.o" "/OUT:C:\\Users\\user\\Desktop\\Coding
\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows
-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.dll" "/DEF:C:\\Users\\
user\\AppData\\Local\\Temp\\rustc4TuCVf\\lib.def" "C:\\Users\\user\\Desktop\\Cod
ing\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-wind
ows-msvc\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.1ld8b1bw3mqm337o.rc
gu.o" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github
\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\r
elease\\deps" "/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x
86_64-pc-windows-msvc\\stage0-codegen\\release\\deps" "/LIBPATH:C:\\Users\\user\
\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x
86_64-pc-windows-msvc\\release\\build\\rustc_llvm-967e43a15e8972c9\\out" "/LIBPA
TH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc
\\llvm\\lib" "/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x8
6_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib"
 "C:\\Users\\user\\AppData\\Local\\Temp\\rustc4TuCVf\\librustc_llvm-a8bdd0585c15
39c0.rlib" "/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_
64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "
rustc_driver-1435ff31eaaf41ce.dll.lib" "/LIBPATH:C:\\Users\\user\\Desktop\\Codin
g\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysroot\\lib\\rustlib\\x8
6_64-pc-windows-msvc\\lib" "test-e860c1ab2ca1821d.dll.lib" "/LIBPATH:C:\\Users\\
user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage0-sysro
ot\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "std-dd6e99fcfdc10abf.dll.lib" "C
:\\Users\\user\\AppData\\Local\\Temp\\rustc4TuCVf\\libcompiler_builtins-4a8172f7
ec29889b.rlib" "psapi.lib" "shell32.lib" "ole32.lib" "uuid.lib" "advapi32.lib" "
advapi32.lib" "ole32.lib" "oleaut32.lib" "psapi.lib" "kernel32.lib" "kernel32.li
b" "advapi32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "setup
api.lib" "user32.lib" "winspool.lib" "advapi32.lib" "advapi32.lib" "ws2_32.lib"
"userenv.lib" "libcmt.lib" "/DLL" "/IMPLIB:C:\\Users\\user\\Desktop\\Coding\\Git
hub\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc
\\release\\deps\\rustc_codegen_llvm-7ace2575052527dd.dll.lib"
  = note: Non-UTF-8 output: libcmt.lib(chkstk.obj) : fatal error LNK1112: il tip
o di computer del modulo \'x86\' \xe8 in conflitto con il tipo di computer di de
stinazione \'x64\'\r\n

error: aborting due to previous error

error: could not compile `rustc_codegen_llvm`.

To learn more, run the command again with --verbose.
command did not execute successfully: "C:\\Users\\user\\Desktop\\Coding\\Github\
\rust\\build\\x86_64-pc-windows-msvc\\stage0\\bin\\cargo.exe" "build" "-Zconfig-
profile" "--target" "x86_64-pc-windows-msvc" "-Zbinary-dep-depinfo" "-j" "4" "--
release" "--manifest-path" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\src/
librustc_codegen_llvm/Cargo.toml" "--features" "" "--message-format" "json-rende
r-diagnostics"
expected success, got: exit code: 101
failed to run: C:\Users\user\Desktop\Coding\Github\rust\build\bootstrap\debug\bo
otstrap build
Build completed unsuccessfully in 0:01:09
```

**Comment by retep998** [comment]
When you run in the dev console there are many environment variables that are set that are architecture specific, not just `PATH`. Since it looks like you used the 32-bit dev console but are building for 64-bit, there's a mismatch and stuff fails to link. If you're going to use the dev console make sure you use the 64-bit dev console.

**Comment by mgostIH** [comment]
Using the x64 dev console seemed to help, as now I started getting on stage 1.
However soon after there's linker errors regarding symbols not being resolved when building hashbrown:
```
   Compiling std v0.0.0 (C:\Users\user\Desktop\Coding\Github\rust\src\libstd)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\V
C\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT"
"/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windo
ws-msvc\\stage1\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\user\\De
sktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-p
c-windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2ddc-cgu.0.rcgu.o" "
C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\s
tage1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2
ddc-cgu.1.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64
-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f72
5555de45e.std.choc2ddc-cgu.10.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\
\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\releas
e\\deps\\std-7302f725555de45e.std.choc2ddc-cgu.11.rcgu.o" "C:\\Users\\user\\Desk
top\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-
windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2ddc-cgu.12.rcgu.o" "C
:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\st
age1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2d
dc-cgu.13.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64
-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f72
5555de45e.std.choc2ddc-cgu.14.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\
\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\releas
e\\deps\\std-7302f725555de45e.std.choc2ddc-cgu.15.rcgu.o" "C:\\Users\\user\\Desk
top\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-
windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2ddc-cgu.2.rcgu.o" "C:
\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\sta
ge1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2dd
c-cgu.3.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-p
c-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f7255
55de45e.std.choc2ddc-cgu.4.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\ru
st\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\
deps\\std-7302f725555de45e.std.choc2ddc-cgu.5.rcgu.o" "C:\\Users\\user\\Desktop\
\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-wind
ows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2ddc-cgu.6.rcgu.o" "C:\\Us
ers\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-
std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f725555de45e.std.choc2ddc-cg
u.7.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-wi
ndows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f725555de
45e.std.choc2ddc-cgu.8.rcgu.o" "C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\
build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps
\\std-7302f725555de45e.std.choc2ddc-cgu.9.rcgu.o" "/OUT:C:\\Users\\user\\Desktop
\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-win
dows-msvc\\release\\deps\\std-7302f725555de45e.dll" "/DEF:C:\\Users\\user\\AppDa
ta\\Local\\Temp\\rustc5oxodE\\lib.def" "C:\\Users\\user\\Desktop\\Coding\\Github
\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\relea
se\\deps\\std-7302f725555de45e.4xlyany15x3fck0l.rcgu.o" "C:\\Users\\user\\Deskto
p\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-wi
ndows-msvc\\release\\deps\\std-7302f725555de45e.1hxmsfn61ptjb7zf.rcgu.o" "/OPT:R
EF,ICF" "/DEBUG" "/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build
\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\release\\deps" "/L
IBPATH:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-
msvc\\stage1-std\\release\\deps" "/LIBPATH:C:\\Users\\user\\Desktop\\Coding\\Git
hub\\rust\\build\\x86_64-pc-windows-msvc\\stage1-std\\x86_64-pc-windows-msvc\\re
lease\\build\\compiler_builtins-4ce05667ac5973f5\\out" "/LIBPATH:C:\\Users\\user
\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rus
tlib\\x86_64-pc-windows-msvc\\lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "C:
\\Users\\user\\AppData\\Local\\Temp\\rustc5oxodE\\libpanic_unwind-ad29e72a49baf7
5a.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\rustc5oxodE\\libhashbrown-8b4cc
f07ed155f90.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\rustc5oxodE\\librustc_
std_workspace_alloc-4e26530d6e727273.rlib" "C:\\Users\\user\\AppData\\Local\\Tem
p\\rustc5oxodE\\libbacktrace-b2a83a0bb5cc2ef2.rlib" "C:\\Users\\user\\AppData\\L
ocal\\Temp\\rustc5oxodE\\librustc_demangle-0d686bd63c6067ce.rlib" "C:\\Users\\us
er\\AppData\\Local\\Temp\\rustc5oxodE\\libunwind-e865d4cedfb55758.rlib" "C:\\Use
rs\\user\\AppData\\Local\\Temp\\rustc5oxodE\\libcfg_if-f0704b615501d4f0.rlib" "C
:\\Users\\user\\AppData\\Local\\Temp\\rustc5oxodE\\liblibc-35390ed243bd0e13.rlib
" "C:\\Users\\user\\AppData\\Local\\Temp\\rustc5oxodE\\liballoc-d3086b0aae1cb1c7
.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\rustc5oxodE\\librustc_std_workspa
ce_core-86a77daa712061fe.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\rustc5oxo
dE\\libcore-29b2ed085f1f6e7c.rlib" "C:\\Users\\user\\AppData\\Local\\Temp\\rustc
5oxodE\\libcompiler_builtins-ab225fad5fb2f247.rlib" "libcmt.lib" "/DLL" "/IMPLIB
:C:\\Users\\user\\Desktop\\Coding\\Github\\rust\\build\\x86_64-pc-windows-msvc\\
stage1-std\\x86_64-pc-windows-msvc\\release\\deps\\std-7302f725555de45e.dll.lib"

  = note:    Creazione della libreria C:\Users\user\Desktop\Coding\Github\rust\b
uild\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\std-7
302f725555de45e.dll.lib e dell'oggetto C:\Users\user\Desktop\Coding\Github\rust\
build\x86_64-pc-windows-msvc\stage1-std\x86_64-pc-windows-msvc\release\deps\std-
7302f725555de45e.dll.exp
          std-7302f725555de45e.std.choc2ddc-cgu.0.rcgu.o : error LNK2019: riferi
mento al simbolo esterno rust_oom non risolto nella funzione _ZN4core3fmt5Write1
0write_char17h4b41e90904bba6daE
          std-7302f725555de45e.std.choc2ddc-cgu.11.rcgu.o : error LNK2001: simbo
lo esterno rust_oom non risolto
          std-7302f725555de45e.std.choc2ddc-cgu.2.rcgu.o : error LNK2001: simbol
o esterno rust_oom non risolto
          std-7302f725555de45e.std.choc2ddc-cgu.3.rcgu.o : error LNK2001: simbol
o esterno rust_oom non risolto
          std-7302f725555de45e.std.choc2ddc-cgu.0.rcgu.o : error LNK2019: riferi
mento al simbolo esterno __rust_start_panic non risolto nella funzione rust_pani
c
          std-7302f725555de45e.1hxmsfn61ptjb7zf.rcgu.o : error LNK2019: riferime
nto al simbolo esterno __rdl_alloc non risolto nella funzione __rust_alloc
          std-7302f725555de45e.1hxmsfn61ptjb7zf.rcgu.o : error LNK2019: riferime
nto al simbolo esterno __rdl_dealloc non risolto nella funzione __rust_dealloc
          std-7302f725555de45e.1hxmsfn61ptjb7zf.rcgu.o : error LNK2019: riferime
nto al simbolo esterno __rdl_realloc non risolto nella funzione __rust_realloc
          std-7302f725555de45e.1hxmsfn61ptjb7zf.rcgu.o : error LNK2019: riferime
nto al simbolo esterno __rdl_alloc_zeroed non risolto nella funzione __rust_allo
c_zeroed
          libcore-29b2ed085f1f6e7c.rlib(core-29b2ed085f1f6e7c.core.bmnb44nl-cgu.
5.rcgu.o) : error LNK2019: riferimento al simbolo esterno rust_begin_unwind non
risolto nella funzione _ZN4core9panicking9panic_fmt17h5543ff381218df4aE
          C:\Users\user\Desktop\Coding\Github\rust\build\x86_64-pc-windows-msvc\
stage1-std\x86_64-pc-windows-msvc\release\deps\std-7302f725555de45e.dll : fatal
error LNK1120: 7 esterni non risolti


error: aborting due to previous error

error: could not compile `std`.
```
