### ISSUE TITLE
compiler error building arrow on rustc 1.40.0-nightly on mac

### ISSUE THREAD

**Issue by jspeis** [rust-lang/rust#65291]
```$ ~/code/example  cargo build
   Compiling arrow v0.15.0
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:42: could not fully normalize `fn() -> usize {std::mem::size_of::<<T as datatypes::ArrowPrimitiveType>::Native>}`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:915:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (2daa404e9 2019-10-02) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `arrow`.
```

simple steps to reproduce:

```cargo new myproject```

add arrow to the dependencies in `Cargo.toml` for `myproject`
 
```toml
[dependencies]
arrow = "*"
```

and when I try to build the project. I get the above error.

**Comment by csmoe** [comment]
reproduced with
```
rustc 1.40.0-nightly (787005079 2019-10-04)
binary: rustc
commit-hash: 7870050796e5904a0fc85ecbe6fa6dde1cfe0c91
commit-date: 2019-10-04
host: x86_64-apple-darwin
release: 1.40.0-nightly
LLVM version: 9.0
```
error:
```
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿   Compiling arrow v0.15.0
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:42: could not fully normalize `fn() -> usize {std::mem::size_of::<<T as datatypes::ArrowPrimitiveType>::Native>}`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:915:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (787005079 2019-10-04) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_ty_after_erasing_regions] normalizing `ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All, def_id: None }, value: fn() -> usize {std::mem::size_of::<<T as datatypes::ArrowPrimitiveType>::Native>} }`
#1 [const_eval_raw] const-evaluating `tensor::Tensor::<'a, T>::new`
#2 [optimized_mir] processing `tensor::Tensor::<'a, T>::new`
end of query stack
error: aborting due to previous error

error: could not compile `arrow`.

```

**Comment by Centril** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/64908.
