### ISSUE TITLE
ICE: 

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust#65998]
Ran `cargo clippy` on https://github.com/paritytech/ink/tree/robin-ink-lang2/lang2.

```
error: internal compiler error: src/librustc/ty/context.rs:210: node expr COUNT (hir_id=HirId { owner: DefIndex(3695), local_id: 15 }) with HirId::owner DefId(0:3695 ~ ink_core[d1da]::storage[0]::collections[0]::binary_heap[0]::duplex_sync_chunk[0]::_[1]::{{impl}}[0]) cannot be placed in TypeckTables with local_id_root DefId(0:3693 ~ ink_core[d1da]::storage[0]::collections[0]::binary_heap[0]::duplex_sync_chunk[0]::_[1])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:925:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/aa69777ea2902208b24b3fd77767d577ceaf6386/src/liballoc/boxed.rs:956
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/aa69777ea2902208b24b3fd77767d577ceaf6386/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  14: std::panicking::begin_panic
  15: rustc_errors::HandlerInner::bug
  16: rustc_errors::Handler::bug
  17: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  18: rustc::ty::context::tls::with_opt::{{closure}}
  19: rustc::ty::context::tls::with_context_opt
  20: rustc::ty::context::tls::with_opt
  21: rustc::util::bug::opt_span_bug_fmt
  22: rustc::util::bug::bug_fmt
  23: rustc::ty::context::validate_hir_id_for_typeck_tables::{{closure}}
  24: rustc::ty::context::tls::with::{{closure}}
  25: rustc::ty::context::tls::with_context::{{closure}}
  26: rustc::ty::context::tls::with_context_opt
  27: rustc::ty::context::tls::with_context
  28: rustc::ty::context::tls::with
  29: rustc::ty::context::TypeckTables::node_substs
  30: clippy_lints::consts::ConstEvalLateContext::expr
  31: clippy_lints::consts::constant_simple
  32: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  33: clippy_lints::utils::hir_utils::SpanlessHash::hash_expr
  34: <clippy_lints::trait_bounds::TraitBounds as rustc::lint::LateLintPass>::check_generics
  35: <rustc::lint::context::LateLintPassObjects as rustc::lint::LateLintPass>::check_generics
  36: rustc::hir::intravisit::walk_item
  37: rustc::hir::intravisit::Visitor::visit_nested_item
  38: rustc::hir::intravisit::walk_block
  39: rustc::hir::intravisit::walk_expr
  40: <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr
  41: <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_nested_body
  42: rustc::hir::intravisit::walk_item
  43: rustc::hir::intravisit::Visitor::visit_nested_item
  44: rustc::hir::intravisit::walk_item
  45: rustc::hir::intravisit::Visitor::visit_nested_item
  46: rustc::hir::intravisit::walk_item
  47: rustc::hir::intravisit::Visitor::visit_nested_item
  48: rustc::hir::intravisit::walk_item
  49: rustc::hir::intravisit::Visitor::visit_nested_item
  50: rustc::hir::intravisit::walk_item
  51: rustc::hir::intravisit::Visitor::visit_nested_item
  52: rustc::hir::intravisit::walk_crate
  53: rustc::lint::context::late_lint_pass_crate
  54: rustc::lint::context::late_lint_crate
  55: rustc::util::common::time
  56: rustc::util::common::time
  57: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:83
  58: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  59: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:83
  60: rustc_interface::passes::analysis::{{closure}}
  61: rustc_interface::passes::analysis
  62: rustc::ty::query::__query_compute::analysis
  63: rustc::dep_graph::graph::DepGraph::with_task_impl
  64: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  65: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  66: rustc_interface::passes::create_global_ctxt::{{closure}}
  67: rustc_interface::passes::BoxedGlobalCtxt::enter
  68: rustc_interface::interface::run_compiler_in_existing_thread_pool
  69: std::thread::local::LocalKey<T>::with
  70: scoped_tls::ScopedKey<T>::set
  71: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (aa69777ea 2019-10-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by Centril** [comment]
cc @rust-lang/clippy -- this should probably be transferred to clippy.
