### ISSUE TITLE
ICE in qualify_consts.rs

### ISSUE THREAD

**Issue by GabrielMajeri** [rust-lang/rust#66016]
I was working on [fixing the build](https://github.com/rust-lang/packed_simd/pull/272) for the [packed_simd](https://github.com/rust-lang/packed_simd) crate. Sadly, I ran into an internal compiler error:
```
error: internal compiler error: src/librustc_mir/transform/qualify_consts.rs:1145: promotion candidate validation mismatches (see above)
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:925:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
...
```
The full backtrace and log is available [here](https://travis-ci.com/rust-lang/packed_simd/jobs/251582760#L387).

I'm afraid I do not have enough time right now to investigate the issue and get a minimal repro, but I've reported it here in the hopes someone can help.

**Comment by ecstatic-morse** [comment]
cc @eddyb

**Comment by ecstatic-morse** [comment]
This is almost certainly caused by #65946.

**Comment by ecstatic-morse** [comment]
Hmm, actually the author reported this ~3 days ago, and that PR should only be on the latest nightly. Maybe rust-lang/stdarch#825 somehow?
