### ISSUE TITLE
unexpected panic, including librocksdb

### ISSUE THREAD

**Issue by Arnaz87** [rust-lang/rust#66727]
This is from a crate I'm working in that includes librocksdb. The rest of the dependencies compile normally. That crate is failing too when I try to compile it directly, but from my crate I don't know what happened, only that the compiler panicked.

```
   Compiling librocksdb-sys v6.2.4
thread 'rustc' panicked at 'no entry found for key', src/libcore/option.rs:1187:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/liballoc/boxed.rs:956
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  14: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  15: rust_begin_unwind
             at src/libstd/panicking.rs:302
  16: core::panicking::panic_fmt
             at src/libcore/panicking.rs:82
  17: core::option::expect_failed
             at src/libcore/option.rs:1187
  18: rustc::hir::map::definitions::Definitions::placeholder_field_index
  19: rustc_resolve::def_collector::DefCollector::collect_field
  20: syntax_expand::expand::AstFragment::visit_with
  21: rustc_resolve::macros::<impl syntax_expand::base::Resolver for rustc_resolve::Resolver>::visit_ast_fragment_with_placeholders
  22: syntax_expand::expand::MacroExpander::collect_invocations
  23: syntax_expand::expand::MacroExpander::fully_expand_fragment
  24: syntax_expand::expand::MacroExpander::expand_crate
  25: rustc_interface::passes::configure_and_expand_inner::{{closure}}
  26: rustc_interface::passes::configure_and_expand_inner
  27: rustc_interface::passes::configure_and_expand::{{closure}}
  28: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  29: rustc_interface::passes::configure_and_expand
  30: rustc_interface::queries::Query<T>::compute
  31: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::expansion
  32: rustc_interface::interface::run_compiler_in_existing_thread_pool
  33: std::thread::local::LocalKey<T>::with
  34: scoped_tls::ScopedKey<T>::set
  35: syntax::with_globals

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: rustc 1.41.0-nightly (412f43ac5 2019-11-24) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

query stack during panic:
end of query stack
```

_Cargo.lock_

``` toml
[[package]]
name = "librocksdb-sys"
version = "6.2.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0a0785e816e1e11e7599388a492c61ef80ddc2afc91e313e61662cce537809be"
dependencies = [
 "bindgen",
 "cc",
 "glob",
 "libc",
]
```

At first, I was compiling in an older version of rust, but it halted, so I updated rustc and now it panics like that. I didn't try to compile the bad crate in the old version.

**Comment by Arnaz87** [comment]
Relevant issue in [rocksdb repo](https://github.com/rust-rocksdb/rust-rocksdb/issues/355)

**Comment by petrochenkov** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/66669.

**Comment by Arnaz87** [comment]
I was mistaken, it was not rocksdb, I don't know which one is the crate anymore, but there appears to be a fix pending
