### ISSUE TITLE
Compiler panic while building crate with tokio, rocket, and snafu

### ISSUE THREAD

**Issue by SamWilsn** [rust-lang/rust#66787]
# Summary

I'm trying to build my crate on nightly, and I'm getting a compiler panic.

I bisected several nightly builds to try and narrow down when the problem started.

The last known good nightly was `nightly-2019-11-10-x86_64-unknown-linux-gnu`, and the first failing was `nightly-2019-11-11-x86_64-unknown-linux-gnu`

The panic also occurs in `nightly-2019-11-26-x86_64-unknown-linux-gnu`.

The crates causing the panic are available here: https://github.com/quilt/simulation/tree/bug-report

# Build Output

```
sam@sam-XPS-15-9570:~/Code/notion/notion-server$ RUST_BACKTRACE=1 cargo build
   Compiling notion-server v0.1.0 (/home/sam/Code/notion/notion-server)
warning: unused variable: `handle`
  --> notion-server/src/api/mod.rs:12:12
   |
12 | pub fn run(handle: Handle) -> Result<()> {
   |            ^^^^^^ help: consider prefixing with an underscore: `_handle`
   |
   = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'overflow computing relative variant idx', src/libcore/option.rs:1187:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/3fc30d884ae0c988d98452a06737705cfe34806a/src/liballoc/boxed.rs:956
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/3fc30d884ae0c988d98452a06737705cfe34806a/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  14: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  15: rust_begin_unwind
             at src/libstd/panicking.rs:302
  16: core::panicking::panic_fmt
             at src/libcore/panicking.rs:141
  17: core::option::expect_failed
             at src/libcore/option.rs:1187
  18: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
  19: <rustc_mir::transform::const_prop::ConstPropagator as rustc::mir::visit::MutVisitor>::visit_statement
  20: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  21: rustc_mir::transform::run_passes
  22: rustc_mir::transform::run_optimization_passes
  23: rustc_mir::transform::optimized_mir
  24: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  25: rustc::dep_graph::graph::DepGraph::with_task_impl
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  33: rustc::util::common::time
  34: rustc_mir::monomorphize::collector::collect_crate_mono_items
  35: rustc::util::common::time
  36: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  37: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  40: rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local
  41: rustc::ty::query::__query_compute::exported_symbols
  42: rustc::dep_graph::graph::DepGraph::with_task_impl
  43: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  44: rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root
  45: rustc::ty::context::tls::with_context::{{closure}}
  46: rustc_metadata::rmeta::encoder::encode_metadata
  47: rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::encode_metadata
  48: rustc::ty::context::TyCtxt::encode_metadata
  49: rustc_interface::passes::start_codegen::{{closure}}
  50: rustc_interface::passes::start_codegen
  51: rustc::ty::context::tls::enter_global
  52: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  53: rustc_interface::passes::create_global_ctxt::{{closure}}
  54: rustc_interface::passes::BoxedGlobalCtxt::enter
  55: rustc_interface::queries::Query<T>::compute
  56: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  57: rustc_interface::interface::run_compiler_in_existing_thread_pool
  58: std::thread::local::LocalKey<T>::with
  59: scoped_tls::ScopedKey<T>::set
  60: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (3fc30d884 2019-11-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `<error::Api as snafu::IntoError<error::Error>>::into_error`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
#2 [exported_symbols] exported_symbols
end of query stack
error: could not compile `notion-server`.

To learn more, run the command again with --verbose
```

**Comment by jonas-schievink** [comment]
cc @wesleywiser

**Comment by pnkfelix** [comment]
triage: P-high, removing nomination label.

**Comment by wesleywiser** [comment]
Minimal repro:

Cargo.toml:

```toml
[package]
name = "notion-server"
version = "0.1.0"

[dependencies]
tokio = "0.2.0-alpha.6"
```

lib.rs:

```rust
pub enum ApiError {}
pub enum Error {
    Api {
        source: ApiError,
    },
    Ethereum,
    Tokio {
        source: tokio::io::Error,
    },
}
struct Api;
impl IntoError<Error> for Api
{
    type Source = ApiError;
    fn into_error(self, error: Self::Source) -> Error {
        Error::Api {
            source: (|v| v)(error),
        }
    }
}

pub trait IntoError<E>
{
    /// The underlying error
    type Source;

    /// Combine the information to produce the error
    fn into_error(self, source: Self::Source) -> E;
}
```

**Comment by nathanwhit** [comment]
As some added info, I've narrowed down the offending commit to 57a5f92bef4b459005920f1aeff05a52c7e356b0 –– most likely the changes in #66216.
