### ISSUE TITLE
incremental comp ICE from string escape sequences (maybe)

### ISSUE THREAD

**Issue by remipassmoilesel** [rust-lang/rust#67165]
Hi, 
I work on a learning project, and I've got this error when I try to compile tests:

```
$ 😔 cargo test -- --nocapture                                                                                                                                                                         [22:46:12] 
   Compiling notes v0.1.3 (/home/user/linux-utils/notes)
thread 'rustc' panicked at 'index out of bounds: the len is 168 but the index is 171', /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/slice/mod.rs:2797:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-nightly (412f43ac5 2019-11-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

error: could not compile `notes`.

To learn more, run the command again with --verbose.
```

**I tried this code:**

```
    pub fn search_should_skip_title() -> () {
        let note = Note::from(
            0,
            PathBuf::from("/tmp/note-1.txt"),
            SAMPLE_NOTE_CONTENT.to_string())
            .ok()
            .unwrap();
        assert_eq!(note.format_for_search(&"ssh".to_string(), 10), "\n\u{1b}[32m@0\u{1b}[0m \u{1b}[36m# SSH\u{1b}[0m \u{1b}[2m(Score: 10)\u{1b}[0m \n\n\u{1b}[2m3. \u{1b}[0m A note about \u{1b}[33mSSH\u{1b}[0m");
    }
```

**An example (MCVE) is available here**: https://github.com/remipassmoilesel/notes/tree/issue/compiler-2019-12-08-22-44

**I expected to see this happen:** Green tests :)

## Meta

`rustc --version --verbose`:

```
$ 😔 rustc --version --verbose                                                                                                                                                                         [22:46:14] 
rustc 1.41.0-nightly (412f43ac5 2019-11-24)
binary: rustc
commit-hash: 412f43ac5b4ae8c3599e71c6972112e9be4758fa
commit-date: 2019-11-24
host: x86_64-unknown-linux-gnu
release: 1.41.0-nightly
LLVM version: 9.0

```

Verbose:
```
$ 😔 cargo test --verbose 
       Fresh autocfg v0.1.7
       Fresh unicode-xid v0.2.0
       Fresh lazy_static v1.4.0
       Fresh approx v0.1.1
       Fresh rgb v0.8.14
       Fresh cfg-if v0.1.10
       Fresh regex-syntax v0.6.12
       Fresh strsim v0.9.2
       Fresh thread_local v0.3.6
       Fresh libc v0.2.65
       Fresh num-traits v0.2.8
       Fresh proc-macro2 v1.0.6
       Fresh memchr v2.2.1
       Fresh winapi v0.3.8
       Fresh quote v1.0.2
       Fresh rand v0.4.6
       Fresh num-traits v0.1.43
       Fresh aho-corasick v0.7.6
       Fresh num-integer v0.1.41
       Fresh dirs-sys v0.3.4
       Fresh time v0.1.42
       Fresh syn v1.0.7
       Fresh cgmath v0.16.1
       Fresh regex v1.3.1
       Fresh dirs v2.0.2
       Fresh chrono v0.4.9
       Fresh serde_derive v1.0.102
       Fresh winconsole v0.10.0
       Fresh serde v1.0.102
       Fresh colored v1.8.0
       Fresh docopt v1.1.0
   Compiling notes v0.1.3 (/home/remipassmoilesel/linux-utils/notes)
     Running `rustc --edition=2018 --crate-name notes src/main.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C debuginfo=2 --test -C metadata=940a3f2b6cc7f947 -C extra-filename=-940a3f2b6cc7f947 --out-dir /home/remipassmoilesel/linux-utils/notes/target/debug/deps -C incremental=/home/remipassmoilesel/linux-utils/notes/target/debug/incremental -L dependency=/home/remipassmoilesel/linux-utils/notes/target/debug/deps --extern chrono=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libchrono-0e43c85cee52b1ac.rlib --extern colored=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libcolored-b053139b8e3e47da.rlib --extern dirs=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libdirs-cb97c3f3abf05034.rlib --extern docopt=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libdocopt-900e6269d136947c.rlib --extern lazy_static=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/liblazy_static-b074b94abd77b008.rlib --extern regex=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libregex-130b75cdecfdb053.rlib --extern serde=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libserde-9008510253652cd4.rlib`
thread 'rustc' panicked at 'index out of bounds: the len is 168 but the index is 171', /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/slice/mod.rs:2797:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/liballoc/boxed.rs:956
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  14: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  15: rust_begin_unwind
             at src/libstd/panicking.rs:302
  16: core::panicking::panic_fmt
             at src/libcore/panicking.rs:82
  17: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  18: <rustc::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode
  19: serialize::serialize::Decoder::read_struct
  20: serialize::serialize::Decoder::read_seq
  21: serialize::serialize::Decoder::read_struct
  22: serialize::serialize::Decoder::read_seq
  23: <rustc::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
  24: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  29: rustc::util::common::time
  30: rustc_mir::monomorphize::collector::collect_crate_mono_items
  31: rustc::util::common::time
  32: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  33: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  36: rustc_codegen_ssa::base::codegen_crate
  37: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  38: rustc_interface::passes::start_codegen::{{closure}}
  39: rustc_interface::passes::start_codegen
  40: rustc::ty::context::tls::enter_global
  41: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  42: rustc_interface::passes::create_global_ctxt::{{closure}}
  43: rustc_interface::passes::BoxedGlobalCtxt::enter
  44: rustc_interface::queries::Query<T>::compute
  45: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  46: rustc_interface::interface::run_compiler_in_existing_thread_pool
  47: std::thread::local::LocalKey<T>::with
  48: scoped_tls::ScopedKey<T>::set
  49: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-nightly (412f43ac5 2019-11-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `note::tests::search_should_skip_title::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `notes`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name notes src/main.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C debuginfo=2 --test -C metadata=940a3f2b6cc7f947 -C extra-filename=-940a3f2b6cc7f947 --out-dir /home/remipassmoilesel/linux-utils/notes/target/debug/deps -C incremental=/home/remipassmoilesel/linux-utils/notes/target/debug/incremental -L dependency=/home/remipassmoilesel/linux-utils/notes/target/debug/deps --extern chrono=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libchrono-0e43c85cee52b1ac.rlib --extern colored=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libcolored-b053139b8e3e47da.rlib --extern dirs=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libdirs-cb97c3f3abf05034.rlib --extern docopt=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libdocopt-900e6269d136947c.rlib --extern lazy_static=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/liblazy_static-b074b94abd77b008.rlib --extern regex=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libregex-130b75cdecfdb053.rlib --extern serde=/home/remipassmoilesel/linux-utils/notes/target/debug/deps/libserde-9008510253652cd4.rlib` (exit code: 101)

```

Thanks !

**Comment by koivunej** [comment]
I also hit similar to this with a bit different error message on stable 1.39.0. Error message I got was:

> thread 'rustc' panicked at 'index out of bounds: the len is 178 but the index is 178', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717:1
0

Happened on: https://github.com/koivunej/aoc/commit/ffdaa2487775b711475f0e211e6f4a1dbd715b3f

```
$ rustc --version --verbose
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-unknown-linux-gnu
release: 1.39.0
LLVM version: 9.0
```

<details><summary>My full `cargo test` output on commit</summary>

```
$ RUST_BACKTRACE=1 cargo test
   Compiling day11 v0.1.0 (.../aoc/2019/day11)
thread 'rustc' panicked at 'index out of bounds: the len is 178 but the index is 178', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717:1
0
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  13: rust_begin_unwind
             at src/libstd/panicking.rs:307
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  16: <rustc::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode
  17: serialize::serialize::Decoder::read_struct
  18: serialize::serialize::Decoder::read_seq
  19: serialize::serialize::Decoder::read_struct
  20: serialize::serialize::Decoder::read_seq
  21: <rustc::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
  22: rustc::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  27: rustc_mir::monomorphize::collector::collect_crate_mono_items
  28: rustc::util::common::time
  29: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  30: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  31: rustc::dep_graph::graph::DepGraph::with_task_impl
  32: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  33: rustc_codegen_ssa::base::codegen_crate
  34: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  35: rustc::util::common::time
  36: rustc_interface::passes::start_codegen
  37: rustc::ty::context::tls::enter_global
  38: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  39: rustc_interface::passes::create_global_ctxt::{{closure}}
  40: rustc_interface::passes::BoxedGlobalCtxt::enter
  41: rustc_interface::queries::Query<T>::compute
  42: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen
  43: rustc_interface::interface::run_compiler_in_existing_thread_pool
  44: std::thread::local::LocalKey<T>::with
  45: scoped_tls::ScopedKey<T>::set
  46: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `full_stage2::{{closure}}#0`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `day11`.

To learn more, run the command again with --verbose.
```

</details>

I tried to provide MCVE but couldn't do it in play.rust-lang.org, and now going back to my commit which did trigger the ICE repeatedly it will not trigger any more.  On a clean clone the originally reported commit does not produce an ICE either.

@remipassmoilesel are you able to reproduce this bug still locally? If yes, I think we'd need to back up your `target/` directory immediatedly :)

**Comment by remipassmoilesel** [comment]
Hmm, it's very strange but unfortunately I cannot reproduce this bug now, even my rust version and my environment are the same.

**Comment by pnkfelix** [comment]
triage: P-medium (unfortunately); until we can get a more readily reproducible scenario, we cannot readily act on this

**Comment by remipassmoilesel** [comment]
Should I close this ?

**Comment by pnkfelix** [comment]
Closing as non actionable
