### ISSUE TITLE
ICE on ./mir-opt/inline/inline-into-box-place.rs with -Zmir-opt-level=3  :  Return place is None, not local

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#67550]
`src/test/mir-opt/inline/inline-into-box-place.rs` ICEs when compiled with `-Zmir-opt-level=3`:

`RUST_BACKTRACE=1 rustc ./mir-opt/inline/inline-into-box-place.rs  -Zmir-opt-level=3`

````
error: internal compiler error: src/librustc_mir/transform/inline.rs:668: Return place is None, not local

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:892:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc_mir::transform::inline::Integrator::make_integrate_local
  21: <rustc_mir::transform::inline::Integrator as rustc::mir::visit::MutVisitor>::visit_place
  22: <rustc_mir::transform::inline::Integrator as rustc::mir::visit::MutVisitor>::visit_basic_block_data
  23: rustc_mir::transform::inline::Inliner::run_pass
  24: <rustc_mir::transform::inline::Inline as rustc_mir::transform::MirPass>::run_pass
  25: rustc_mir::transform::run_passes
  26: rustc_mir::transform::run_optimization_passes
  27: rustc_mir::transform::optimized_mir
  28: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  29: rustc::dep_graph::graph::DepGraph::with_task_impl
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  31: rustc::ty::<impl rustc::ty::context::TyCtxt>::instance_mir
  32: rustc_mir::monomorphize::collector::collect_items_rec
  33: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  34: rustc::util::common::time
  35: rustc_mir::monomorphize::collector::collect_crate_mono_items
  36: rustc::util::common::time
  37: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  38: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  39: rustc::dep_graph::graph::DepGraph::with_task_impl
  40: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  41: rustc_codegen_ssa::base::codegen_crate
  42: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  43: rustc_interface::passes::start_codegen::{{closure}}
  44: rustc_interface::passes::start_codegen
  45: rustc::ty::context::tls::enter_global
  46: rustc_interface::queries::Queries::ongoing_codegen
  47: rustc_interface::interface::run_compiler_in_existing_thread_pool
  48: std::thread::local::LocalKey<T>::with
  49: scoped_tls::ScopedKey<T>::set
  50: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (0de96d37f 2019-12-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3

query stack during panic:
#0 [optimized_mir] processing `main`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error
````

`rustc 1.42.0-nightly (0de96d37f 2019-12-19)`

**Comment by Aaron1011** [comment]
I can no longer reproduce this on the latest nightly.

**Comment by matthiaskrgr** [comment]
Looks like this has been resolved indeed (testing with master toolchain).
So it's only missing a testcase now. :)
