### ISSUE TITLE
Missing backtraces in local compiler build

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/rust#67615]
I recently rebased an old branch (branched off at 4007d4ef26eab44bdabc2b7574d032152264d3ad) and afterwards found that the backtrace didn't contain any of the compiler (ignore the actual ICE, I'm sure I'll fix it once I stop trying to get backtraces back):

```
error: internal compiler error: src/librustc/traits/codegen/mod.rs:58: Encountered error `Unimplemented` selecting `Binder(<T as num::dec2flt::rawfp::RawFloat>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:895:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
error: could not compile `core`.
```

You can find my [`config.toml` here](https://github.com/davidtwco/veritas/blob/fbdde10284101a7e2b412495894828dd2fbe3067/shells/rust.nix#L13-L524). This is running on a NixOS host with an i7-8700. It isn't fixed by setting `RUST_BACKTRACE` to `1`, `full` or leaving it unset. I've also tried with and without the `backtrace` option in `config.toml`. I also tried invoking the compiler directly (original error was in compiling `libcore` through `x.py` after some of my changes).

I was able to bisect ([results](http://sprunge.us/ACXOa3)) the issue to a handful of commits:

- 150d328d2e70b4cbc63d0f7d2dc802e1d6d2ac39
- 9245182420879321962ec63c6d8cf2d9a862316e
- a7de090e35efdbe7c45a7840726c1b4facf26ae6
- 8b9c5396ca574fad9cc7b51d16c8c96e0ae74632
- 1aa34d4decde1d1e0089a4aef450d45efd9ea2d4
- fca192cca2dc1a9ea730f2b1ac5b5976ea62bb61
- f94b0e6af32c095d1627926d8922d6d3e218ca76
- 91b25a84df08d88c9bf7910da9d84ae30e410edb
- 7f23e6e8d7479d8a430e007fab9b195b7ea0d261

I wasn't able to test any of these and be more specific because `Cargo.lock` was in a broken state in these commits. On the last commit which failed, after printing the same limited backtrace as above (on a simple test case that compile errors and `-Z treat-err-as-bug`), it printed the following:

```
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193 
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210    
fish: “rustc +rust2-stage1 -Z treat-er…” terminated by signal SIGSEGV (Address boundary error)
```

cc @Aaron1011 @alexcrichton (authors of the above commits)

**Comment by davidtwco** [comment]
I've found that I can also reproduce this in a Ubuntu 18.04 LXC container on the same host. I also noticed that the command that failed mentions which signal caused the failure:

```
  process didn't exit successfully: `/working/build/bootstrap/debug/rustc --edition=2018 --crate-name core src/libcore/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C debuginfo=2 -C metadata=48803f0c286bf5f4 -C extra-filename=-48803f0c286bf5f4 --out-dir /working/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C incremental=/working/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental -L dependency=/working/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/working/build/x86_64-unknown-linux-gnu/stage1-std/release/deps -Zexternal-macro-backtrace '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings -Cprefer-dynamic -Zbinary-dep-depinfo` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by davidtwco** [comment]
Changing the kernel version from 4.19.88 to 5.4.2 doesn't appear to have an effect (not that I would particularly have expected it to).

**Comment by davidtwco** [comment]
With some more experimentation, I've found that this is a result of `debug = true` or `debuginfo-level > 1`.

**Comment by davidtwco** [comment]
I've rebased and this has started happening again, but now with any `debuginfo-level`. 

```
error: internal compiler error: src/librustc/ty/instance.rs:85: Instance.ty called for type fn() -> u32 {closures::unused::<T>} with params in substs: [T]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:885:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1053
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
fish: Process 25930, “rustc” “rustc +rust0-stage1 src/test/co…” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by tmiasko** [comment]
Potentially the same as #69151, which has more details regarding root cause.

**Comment by davidtwco** [comment]
@tmiasko thanks, closing this in favour of #69151.
