### ISSUE TITLE
Compiling with local llvm

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#67718]
When I set `llvm-config = "/usr/lib/llvm-8/bin/llvm-config"` in `config.toml`, I get the following error:

```console
$ RUST_BACKTRACE=1 ./x.py test --stage 1 -i --keep-stage 1 --compare-mode=nll
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized] target(s) in 0.11s
thread 'main' panicked at 'FileCheck executable "/usr/lib/llvm-8/bin/FileCheck" does not exist', src/bootstrap/sanity.rs:186:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  13: bootstrap::sanity::check
             at src/bootstrap/sanity.rs:186
  14: bootstrap::Build::new
             at src/bootstrap/lib.rs:384
  15: bootstrap::main
             at src/bootstrap/bin/main.rs:15
  16: std::rt::lang_start::{{closure}}
             at /rustc/eb3f7c2d3aec576f47eba854cfbd3c1187b8a2a0/src/libstd/rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:270
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
             at /rustc/eb3f7c2d3aec576f47eba854cfbd3c1187b8a2a0/src/libstd/rt.rs:67
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failed to run: /home/mark/nobackup/rust2/build/bootstrap/debug/bootstrap test --stage 1 -i --keep-stage 1 --compare-mode=nll
Build completed unsuccessfully in 0:00:00
```

Am I doing something stupid?

**Comment by petrochenkov** [comment]
Not sure why `FileCheck` is missing in your specific case, but `config.toml.example` has a couple of options to specify custom `FileCheck` (`llvm-filecheck`) or proceed without it (`codegen-tests`).

**Comment by mati865** [comment]
Alternatively assuming it's Debian based distro like Ubuntu you can install `llvm-8-tools` which will provide `/usr/lib/llvm-8/bin/FileCheck`.

**Comment by mark-i-m** [comment]
Thanks! I will add this info to the rustc-guide.
