### ISSUE TITLE
ICE in unsized locals

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#67981]
The following ICE's in nightly:
```Rust
#![feature(unsized_locals)]

fn main() {
    let f: fn([u8]) = |_| {};
    
    let slice: Box<[u8]> = Box::new([1; 8]);
    
    f(*slice);
}
```

<details>
<summary>Backtrace:</summary>

```
 Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'tried to statically allocate unsized place', src/librustc_codegen_ssa/mir/place.rs:55:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  12: std::panicking::begin_panic
  13: rustc_codegen_ssa::mir::place::PlaceRef<V>::alloca
  14: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  16: rustc_codegen_ssa::mir::codegen_mir
  17: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  18: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  19: rustc::dep_graph::graph::DepGraph::with_task
  20: rustc_codegen_llvm::base::compile_codegen_unit
  21: rustc_codegen_ssa::base::codegen_crate
  22: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  23: rustc_interface::passes::start_codegen::{{closure}}
  24: rustc::util::common::time
  25: rustc_interface::passes::start_codegen
  26: rustc::ty::context::tls::enter_global
  27: rustc_interface::queries::Queries::ongoing_codegen
  28: rustc_interface::interface::run_compiler_in_existing_thread_pool
  29: scoped_tls::ScopedKey<T>::set
  30: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (da3629b05 2019-12-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`.
```

</details>

**Comment by DutchGhost** [comment]
update,
```Rust
#![feature(unsized_locals, raw_ref_op)]

fn main() {
    let f: fn([u8]) = |_| {};
}
```
seems already enough to cause the ICE

**Comment by JohnTitor** [comment]
Triage: This now occurs on `unsized_fn_params`.

**Comment by Jules-Bertholet** [comment]
Reduced further:

```rust
#![feature(unsized_fn_params)]

fn main() {
    let _f: fn([u8]) = |_| ();
}
```

**Comment by Jules-Bertholet** [comment]
With #110872, this now has a slightly nicer ICE.

The issue is that `unsized_fn_params` is incompatible with the `"rust-call"` ABI that the `Fn` traits use. `"rust-call"` tries to collect all its arguments into a tuple, but when the arguments are unsized, that's not possible—the tuple might not even be a valid type! This problem can't be fixed without some new design, like explicit `&move` or variadics.

**Comment by Jules-Bertholet** [comment]
With #111864, this is now an error instead of an ICE.

@rustbot label -I-ICE

**Comment by JohnTitor** [comment]
https://github.com/rust-lang/rust/pull/111864 added a relevant test, dropping `E-needs-test` cc @matthiaskrgr
