### ISSUE TITLE
[spurious] thread 'rustc' panicked at 'slice index starts at 24722962 but ends at 13279232', src/libcore/slice/mod.rs:2680:5

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#68132]
```
thread 'rustc' panicked at 'slice index starts at 24722962 but ends at 13279232', src/libcore/slice/mod.rs:2680:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::slice::slice_index_order_fail
  10: rustc_metadata::rmeta::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::rmeta::decoder::DecodeContext>::read_str
  11: <rustc_span::symbol::Symbol as serialize::serialize::Decodable>::decode
  12: <rustc_metadata::rmeta::CrateRoot as serialize::serialize::Decodable>::decode::{{closure}}
  13: rustc_metadata::rmeta::decoder::<impl rustc_metadata::rmeta::Lazy<T>>::decode
  14: rustc_metadata::rmeta::decoder::MetadataBlob::get_root
  15: rustc_metadata::locator::CrateLocator::extract_one
  16: rustc_metadata::locator::CrateLocator::extract_lib
  17: rustc_metadata::locator::CrateLocator::find_library_crate
  18: rustc_metadata::locator::CrateLocator::maybe_load_library_crate
  19: rustc_metadata::creader::CrateLoader::load
  20: rustc_metadata::creader::CrateLoader::maybe_resolve_crate
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  23: rustc_metadata::creader::CrateLoader::maybe_resolve_crate
  24: rustc_metadata::creader::CrateLoader::process_extern_crate
  25: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as syntax::visit::Visitor>::visit_item
  26: syntax::visit::walk_item
  27: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as syntax::visit::Visitor>::visit_item
  28: rustc_expand::expand::AstFragment::visit_with
  29: rustc_resolve::macros::<impl rustc_expand::base::Resolver for rustc_resolve::Resolver>::visit_ast_fragment_with_placeholders
  30: rustc_expand::expand::MacroExpander::collect_invocations
  31: rustc_expand::expand::MacroExpander::fully_expand_fragment
  32: rustc_expand::expand::MacroExpander::expand_crate
  33: rustc_session::utils::<impl rustc_session::session::Session>::time
  34: rustc_interface::passes::configure_and_expand_inner
  35: rustc_interface::passes::configure_and_expand::{{closure}}
  36: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  37: rustc_interface::passes::configure_and_expand
  38: rustc_interface::queries::Queries::expansion
  39: rustc_interface::interface::run_compiler_in_existing_thread_pool
  40: scoped_tls::ScopedKey<T>::set
  41: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (175631311 2020-01-10) running on x86_64-apple-darwin

note: compiler flags: -Z panic-abort-tests -Z codegen-backend=/Users/bjorn/Documents/rustc_codegen_cranelift/target/release/librustc_codegen_cranelift.dylib -Z force-unstable-if-unmarked -C debuginfo=2 -C panic=abort -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `hashbrown`.
```

This is with a custom codegen backend, but that shouldn't matter as it doesn't modify metadata reading and writing.

**Comment by pnkfelix** [comment]
triage: leaving nominated and added to explicit nomination list for today's meeting

**Comment by pnkfelix** [comment]
discussed at T-compiler triage meeting. Prioritizing as P-low, with intent to close in near term as non-actionable

**Comment by bjorn3** [comment]
:+1: I haven't seen this since I reported this, so it is very spurious or fixed.

**Comment by Centril** [comment]
Closing per "very spurious or fixed".
