### ISSUE TITLE
error: internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by technicallyblue** [rust-lang/rust#68138]
<short summary of the bug>

I tried this code:

<rustc main.rs>

I expected to see this happen: <Hello, world!>

Instead, this happened: 
```
thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1488: worker thread panicked', src/librustc/util/bug.rs:37:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0 (73528e339 2019-12-16) running on x86_64-unknown-linux-gnu

error: could not write output to main.4s37gsrti678ik8u.rcgu.o: Permission denied

error: aborting due to previous error
```

## Meta

`rustc --version --verbose`:
rustc 1.40.0 (73528e339 2019-12-16)
binary: rustc
commit-hash: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
commit-date: 2019-12-16
host: x86_64-unknown-linux-gnu
release: 1.40.0
LLVM version: 9.0

Next I ran <```RUST_BACKTRACE=1 rustc main.rs```>

The result:
```
thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1488: worker thread panicked', src/librustc/util/bug.rs:37:26
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  12: std::panicking::begin_panic
  13: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  14: rustc::ty::context::tls::with_opt::{{closure}}
  15: rustc::ty::context::tls::with_context_opt
  16: rustc::ty::context::tls::with_opt
  17: rustc::util::bug::opt_span_bug_fmt
  18: rustc::util::bug::bug_fmt
  19: rustc_codegen_ssa::back::write::start_executing_work::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

Thank you

**Comment by Centril** [comment]
If you could provide the contents of `main.rs` that would be helpful. Thanks.

**Comment by technicallyblue** [comment]
`fn main() {
    println!("Hello, world!");
}`

This is the beginner's instruction from a book.

**Comment by Centril** [comment]
Oh wow; that's a short example. Does this reproduce for you with the latest nightly compiler?

**Comment by technicallyblue** [comment]
Just updated to nightly
`nightly-x86_64-unknown-linux-gnu installed - rustc 1.42.0-nightly (859764425 2020-01-07)`

No change

**Comment by Janrupf** [comment]
`error: could not write output to main.4s37gsrti678ik8u.rcgu.o: Permission denied`

Maybe there is no check for catching such error?

**Comment by technicallyblue** [comment]
I appreciate your help. Having stared at the error message one more time from Janrupf post the "permission part caught my eye" Went ahead and chmod 777 on the project folders being used. The program compiled! Sorry for wasting time on something so basic.
