### ISSUE TITLE
ICE: (exact cause yet to be determined)

### ISSUE THREAD

**Issue by leo-lb** [rust-lang/rust#68382]
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x7fff9891b424 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7fff9891b424 - backtrace::backtrace::trace_unsynchronized::h85fd8d34e214d876
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7fff9891b424 - std::sys_common::backtrace::_print_fmt::he35a37f9b8e4b952
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7fff9891b424 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he0e762d8ed66f8bc
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7fff9895d6a4 - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7fff9890b088 - std::io::Write::write_fmt::hfae316bf0dea24b4
                               at src/libstd/io/mod.rs:1412
   6:     0x7fff98920af0 - std::sys_common::backtrace::_print::ha081546d159043e6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7fff98920af0 - std::sys_common::backtrace::print::h5ae28d5a72f95be5
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7fff98920af0 - std::panicking::default_hook::{{closure}}::h00506bfaacab8ec5
                               at src/libstd/panicking.rs:188
   9:     0x7fff989206e0 - std::panicking::default_hook::h55fa199021de9a28
                               at src/libstd/panicking.rs:205
  10:     0x7fff98c57860 - rustc_driver::report_ice::h3fb8cf3cd94bf46e
  11:     0x7fff98cc2b98 - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}::h8ce44bb331c2513a
  12:     0x7fff82b155b4 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h66e8c99220bb439e
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:956
  13:     0x7fff82a8cb0c - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h7f2ee4ecfc22111c
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libproc_macro/bridge/client.rs:305
  14:     0x7fff989215c4 - std::panicking::rust_panic_with_hook::h61149c5bf815a5b0
                               at src/libstd/panicking.rs:468
  15:     0x7fff98920efc - std::panicking::continue_panic_fmt::h8c2cbca8aac85ef4
                               at src/libstd/panicking.rs:373
  16:     0x7fff98920d78 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  17:     0x7fff989555a8 - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  18:     0x7fff989554cc - core::panicking::panic::hb5daa85c7c72fc62
                               at src/libcore/panicking.rs:70
  19:     0x7fff9936a6dc - rustc_typeck::check::typeck_tables_of::h2dcde3e4c66e4003
  20:     0x7fff99390f18 - rustc::ty::query::__query_compute::typeck_tables_of::hd81e4e65a0ee71f4
  21:     0x7fff99483678 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute::h11b3a68e875fed6a
  22:     0x7fff993ea630 - rustc::dep_graph::graph::DepGraph::with_task_impl::h295dd8246a0cb8c7
  23:     0x7fff994a4978 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h3c4226264eb1e87a
  24:     0x7fff9a6b5fec - rustc::ty::query::__query_compute::typeck_tables_of::hb88e2d385d368051
  25:     0x7fff9ae26408 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute::h11b3a68e875fed6a
  26:     0x7fff9a7aca18 - rustc::dep_graph::graph::DepGraph::with_task_impl::hc077e21a9e731094
  27:     0x7fff9acd5af0 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h37b4c08331ec28ff
  28:     0x7fff9a808ebc - rustc::traits::error_reporting::<impl rustc::infer::InferCtxt>::note_obligation_cause::h2a84079b4e534b15
  29:     0x7fff9a7ff46c - rustc::traits::error_reporting::<impl rustc::infer::InferCtxt>::report_selection_error::h2d16377cb2bfd13b
  30:     0x7fff9a7f8f90 - rustc::traits::error_reporting::<impl rustc::infer::InferCtxt>::report_fulfillment_errors::hc8038178075c8e04
  31:     0x7fff9937a73c - rustc_typeck::check::FnCtxt::check_argument_types::h1df8ce32d8237cd9
  32:     0x7fff99363d48 - rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call::h803ff2abc395e6fe
  33:     0x7fff993625d4 - rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call::heb46a602756afb92
  34:     0x7fff9934aaa8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::had750cb81e6b8db5
  35:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  36:     0x7fff9937d3a4 - rustc_typeck::check::FnCtxt::check_stmt::h4089b63277c5efc3
  37:     0x7fff9937da4c - rustc_typeck::check::FnCtxt::check_block_with_expected::h5e08c35a8a5fde4b
  38:     0x7fff9934c464 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::had750cb81e6b8db5
  39:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  40:     0x7fff9937d1e4 - rustc_typeck::check::FnCtxt::check_stmt::h4089b63277c5efc3
  41:     0x7fff9937da4c - rustc_typeck::check::FnCtxt::check_block_with_expected::h5e08c35a8a5fde4b
  42:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  43:     0x7fff9937da7c - rustc_typeck::check::FnCtxt::check_block_with_expected::h5e08c35a8a5fde4b
  44:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  45:     0x7fff99352758 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr::h0925c1b87dc7b7fe
  46:     0x7fff9936b6e8 - rustc_typeck::check::check_fn::h22d4c0d66acc8ba4
  47:     0x7fff9935ff04 - rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure::he37d3045f91429b6
  48:     0x7fff9934a5ac - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::had750cb81e6b8db5
  49:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  50:     0x7fff9937a8dc - rustc_typeck::check::FnCtxt::check_argument_types::h1df8ce32d8237cd9
  51:     0x7fff99363d48 - rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call::h803ff2abc395e6fe
  52:     0x7fff993625d4 - rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call::heb46a602756afb92
  53:     0x7fff9934aaa8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::had750cb81e6b8db5
  54:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  55:     0x7fff9937a8dc - rustc_typeck::check::FnCtxt::check_argument_types::h1df8ce32d8237cd9
  56:     0x7fff993790b8 - rustc_typeck::check::FnCtxt::check_method_argument_types::h8336465e217f2104
  57:     0x7fff9934e638 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind::had750cb81e6b8db5
  58:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  59:     0x7fff9937da7c - rustc_typeck::check::FnCtxt::check_block_with_expected::h5e08c35a8a5fde4b
  60:     0x7fff99349de8 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs::hb8bdc8e466d7f1b8
  61:     0x7fff99352758 - rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr::h0925c1b87dc7b7fe
  62:     0x7fff9936b6e8 - rustc_typeck::check::check_fn::h22d4c0d66acc8ba4
  63:     0x7fff994fee98 - rustc::ty::context::tls::with_context::{{closure}}::h9f7702db4a8ae077
  64:     0x7fff9936a554 - rustc_typeck::check::typeck_tables_of::h2dcde3e4c66e4003
  65:     0x7fff9a6b5fec - rustc::ty::query::__query_compute::typeck_tables_of::hb88e2d385d368051
  66:     0x7fff9ae26408 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute::h11b3a68e875fed6a
  67:     0x7fff9a7aca18 - rustc::dep_graph::graph::DepGraph::with_task_impl::hc077e21a9e731094
  68:     0x7fff9adb5688 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::force_query::h6f302c5f2d796ef7
  69:     0x7fff9a736070 - rustc::ty::query::plumbing::force_from_dep_node::hd41ea0279482704a
  70:     0x7fff9a7bcbcc - rustc::dep_graph::graph::DepGraph::try_mark_previous_green::h51fd38ce52f0f7ab
  71:     0x7fff9a7bc944 - rustc::dep_graph::graph::DepGraph::try_mark_green::h3d0b66236ddcc5c5
  72:     0x7fff9a7bc6c8 - rustc::dep_graph::graph::DepGraph::try_mark_green_and_read::hdc80b580acb9c115
  73:     0x7fff994a3f20 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h3c4226264eb1e87a
  74:     0x7fff9946ea94 - rustc_typeck::collect::checked_type_of::he15ff3daea8a06c2
  75:     0x7fff9946dcd4 - rustc_typeck::collect::type_of::h954bf8339ce7a808
  76:     0x7fff99393188 - rustc::ty::query::__query_compute::type_of::h016069c31b1b3704
  77:     0x7fff99482fc8 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::type_of>::compute::hae494d0e4ee96c5e
  78:     0x7fff993f3710 - rustc::dep_graph::graph::DepGraph::with_task_impl::h97635124ff05d3e9
  79:     0x7fff994ea104 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::hf15399218e41b82d
  80:     0x7fff9951f32c - rustc::hir::intravisit::walk_expr::h85c659c8d282a415
  81:     0x7fff9951f380 - rustc::hir::intravisit::walk_expr::h85c659c8d282a415
  82:     0x7fff99451b18 - rustc::hir::intravisit::Visitor::visit_fn::h1c356e921460d931
  83:     0x7fff99523afc - rustc::hir::intravisit::walk_item::h182b74b419c8f582
  84:     0x7fff99468824 - <rustc_typeck::collect::CollectItemTypesVisitor as rustc::hir::intravisit::Visitor>::visit_item::h16a4b9ba88a8e28e
  85:     0x7fff993c5028 - rustc::hir::map::Map::visit_item_likes_in_module::h09d39c4ea562267a
  86:     0x7fff994683b4 - rustc_typeck::collect::collect_mod_item_types::h48d04387163cbb3f
  87:     0x7fff99392228 - rustc::ty::query::__query_compute::collect_mod_item_types::h1fa8e01b0c49cae5
  88:     0x7fff99483b28 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::collect_mod_item_types>::compute::h8d6b3185fd1de0a5
  89:     0x7fff993fc84c - rustc::dep_graph::graph::DepGraph::with_task_impl::hf4e5908be5f3e646
  90:     0x7fff994a27dc - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h37b251d58d830297
  91:     0x7fff99484534 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query::hb8a7f43f89ea46c4
  92:     0x7fff995c7640 - rustc_typeck::check_crate::{{closure}}::{{closure}}::h55daebbe893c2835
  93:     0x7fff995aab8c - rustc::util::common::time::hb8460002621a0239
  94:     0x7fff995fac14 - rustc_typeck::check_crate::ha8743f985b58ba4f
  95:     0x7fff98d7e37c - rustc_interface::passes::analysis::hbc0793af0c48a573
  96:     0x7fff98ce4760 - rustc::ty::query::__query_compute::analysis::h13637fdaa2efb1e6
  97:     0x7fff98ce7200 - rustc::dep_graph::graph::DepGraph::with_task_impl::h9350c917143f01a9
  98:     0x7fff98c3bf70 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h2b158e41a1c23a6b
  99:     0x7fff98cebd5c - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::hc9068e2c58b072ed
 100:     0x7fff98de64a0 - rustc_interface::passes::create_global_ctxt::{{closure}}::h31fa6dbbd350543e
 101:     0x7fff98ceb2f4 - rustc_interface::passes::BoxedGlobalCtxt::enter::hb9a9cd3a7f0b74ae
 102:     0x7fff98cac54c - rustc_interface::interface::run_compiler_in_existing_thread_pool::h43c0621320721185
 103:     0x7fff98c826a0 - std::thread::local::LocalKey<T>::with::h07620661cda799fb
 104:     0x7fff98c7f8ec - scoped_tls::ScopedKey<T>::set::h3e52bcdbf6ab99d2
 105:     0x7fff98cbced8 - syntax::with_globals::hf493a25b88f5e67f
 106:     0x7fff98cdc6a0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e4392a23b1355c4
 107:     0x7fff989357b4 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
 108:     0x7fff98cdded4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf0c205c7fe605dfa
 109:     0x7fff988f78b8 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h72164f22cf22b003
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
 110:     0x7fff98933c60 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd71ff6d17adcf1cd
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
 111:     0x7fff98933c60 - std::sys_common::thread::start_thread::h5aa0af9a6133da67
                               at src/libstd/sys_common/thread.rs:13
 112:     0x7fff98933c60 - std::sys::unix::thread::Thread::new::thread_start::h8fae6fef275a32d6
                               at src/libstd/sys/unix/thread.rs:79
 113:     0x7fff98539a88 - start_thread
 114:     0x7fff98783ad8 - clone

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0 (73528e339 2019-12-16) running on powerpc64le-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] processing `tokio::task::local::LocalSet::run_until`
#1 [typeck_tables_of] processing `tokio::task::local::LocalSet::run_until::{{closure}}#0`
#2 [typeck_tables_of] processing `main`
#3 [typeck_tables_of] processing `main::{{closure}}#0`
#4 [type_of] processing `main::{{closure}}#0`
#5 [collect_mod_item_types] collecting item types in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `ssb-server-rs`.

To learn more, run the command again with --verbose.
```

with https://github.com/leo-lb/ssb-server-rs/commit/a01a9fe84c894d4ca230380ba0d5093a23fefbb1

**Comment by Centril** [comment]
Does it reproduce with nightly?

**Comment by leo-lb** [comment]
duplicate? https://github.com/rust-lang/rust/issues/66868

**Comment by leo-lb** [comment]
@Centril Looks like not! That's great.

**Comment by Centril** [comment]
Cool; closing the issue then. Thanks :)

**Comment by leo-lb** [comment]
@Centril Are you going to make a point release?

**Comment by Centril** [comment]
It's unlikely since it's an ICE in already erroring code (at least from what I can surmise from the backtrace).

**Comment by leo-lb** [comment]
@Centril Indeed, and I see. Didnt know about such policy.
