### ISSUE TITLE
'index out of bounds: the len is 1 but the index is 1': libcore/slice/mod.rs

### ISSUE THREAD

**Issue by harrisonthorne** [rust-lang/rust#68801]
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/cd1ef390e73
1ed77b90b11b1f77e2c5ca641b261/src/libcore/slice/mod.rs:2791:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

Edit: Clippy version:

```
clippy 0.0.212 (c0f39cf 2020-01-29)
```

**Comment by estebank** [comment]
What `rustc` version are you running?

**Comment by Centril** [comment]
cc @matthewjasper

**Comment by threecgreen** [comment]
I got a similar panic with rustc 1.43.0-nightly (58b834344 2020-02-05)
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/58b834344fc7b9185e7a50db1ff24e5eb07dae5e/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt               at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/58b834344fc7b9185e7a50db1ff24e5eb07dae5e/src/liballoc/boxed.rs:1030
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/58b834344fc7b9185e7a50db1ff24e5eb07dae5e/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  14: rust_begin_unwind
             at src/libstd/panicking.rs:378
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  16: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  17: rustc_mir::borrow_check::type_check::type_check
  18: rustc_mir::borrow_check::nll::compute_regions
  19: rustc_mir::borrow_check::do_mir_borrowck
  20: rustc::ty::context::GlobalCtxt::enter_local
  21: rustc_mir::borrow_check::mir_borrowck
  22: rustc::ty::query::__query_compute::mir_borrowck
  23: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  24: rustc::dep_graph::graph::DepGraph::with_task_impl
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  26: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  27: rustc_session::utils::<impl rustc_session::session::Session>::time
  28: rustc_interface::passes::analysis
  29: rustc::ty::query::__query_compute::analysis
  30: rustc::dep_graph::graph::DepGraph::with_task_impl
  31: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  32: rustc::ty::context::tls::enter_global
  33: rustc_interface::interface::run_compiler_in_existing_thread_pool
  34: scoped_tls::ScopedKey<T>::set
  35: syntax::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.  
error: internal compiler error: unexpected panic
```

**Comment by pnkfelix** [comment]
@threecgreen that is great that you can reproduce this bug. Can you provide a code sample for the reproduction, or a link to the source code for your crate where you are seeing it?

**Comment by pnkfelix** [comment]
triage: I don't want to assign a priority to this without more information. leaving nominated to ensure I come back to it.

**Comment by threecgreen** [comment]
I was not able to easily create a small code sample, but [this was the state of my code](https://github.com/threecgreen/vinoteca/tree/crash-demo) when I saw the panic.

**Comment by jonas-schievink** [comment]
I just caused a lot of these to appear in the async/await tests when changing the HIR lowering of async/await. I've pushed that state as https://github.com/jonas-schievink/rust/commit/1197e62c8573e72c41231dc65d58c9a0efc13ecb. I probably did something wrong in the HIR building code, but a similar issue might be preexisting, which could cause this I guess.

**Comment by nikomatsakis** [comment]
@rustbot ping icebreakers-cleanup-crew

Dear cleanup crew, it would be great to try and narrow this down to a self-contained example. @threecgreen [has a crate here](https://github.com/rust-lang/rust/issues/68801#issuecomment-582920167) that reproduces the problem, but it's not a small, workable example.

**Comment by nikomatsakis** [comment]
Also would be good to know if this is a regression.

**Comment by nikomatsakis** [comment]
Tagging as P-high for now because the ICE gives so little actionable information to guide the user as to how to correct the problem.

**Comment by ethanboxx** [comment]
@harrisonthorne Can you run [cargo bisect](https://github.com/rust-lang/cargo-bisect-rustc/) on this so we can identify if this is a regression in rustc.

**Comment by chrissimpkins** [comment]
Source: crash-demo branch of https://github.com/threecgreen/vinoteca/tree/crash-demo

There are multiple ICE error types coming from this [block of source](https://github.com/threecgreen/vinoteca/blob/f28f1b1315211b4c37dfec776761e5d1281ec7a7/src/producers.rs#L43-L60):

```rust
pub fn top<Table: diesel::Table + diesel::query_dsl::InternalJoinDsl<_, diesel::query_source::joins::Inner, _>>(table: Table, limit: usize, connection: DbConn) -> RestResult<Vec<TopWineType>> {
    table
        .inner_join(wines::table.inner_join(purchases::table))
        .group_by((producers::id, producers::name))
        .select((
            wines::id,
            wines::name,
            sql::<Integer>("sum(purchases.quantity)"),
            // Should probably be distinct
            sql::<Integer>("count(wines.id)"),
            sql::<Float>("avg(purchases.price)"),
        ))
        .order_by(sql::<Integer>("sum(purchases.quantity) DESC"))
        .limit(limit as i64)
        .load::<TopWineType>(&*connection)
        .map(Json)
        .map_err(VinotecaError::from)
}
```

ICE's:

- `bad placeholder type`
- `cat_expr Errd`
- `PromoteTemps: MIR had errors`
- `broken MIR in DefId(0:84 ~ vinoteca[2dad]::producers[0]::top[0]) ("return type"): bad type [type error]`
- `broken MIR in DefId(0:84 ~ vinoteca[2dad]::producers[0]::top[0]) (LocalDecl { mutability: Mut, local_info: Other, internal: false, is_block_tail: None, ty: [type error], user_ty: UserTypeProjections { contents: [] }, source_info: SourceInfo { span: src/producers.rs:43:1: 60:2, scope: scope[0] } }): bad type [type error]`

then this panic:

- `thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued'`

**Comment by chrissimpkins** [comment]
Regression. 

Tested with builds of the full crate

searched nightlies: from nightly-2019-08-01 to nightly-2020-02-01
regressed nightly: nightly-2020-01-01
searched commits: from https://github.com/rust-lang/rust/commit/a9dd56ff9a08d74c53d5cc22d18f126a12749608 to https://github.com/rust-lang/rust/commit/119307a83e12291a3fc126735d6bd0292c443464
regressed commit: https://github.com/rust-lang/rust/commit/71bb0ff33e3759ee71ea19c230492c11e5e32b87
source code: https://github.com/threecgreen/vinoteca/tree/crash-demo

Errors before the regression:

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> src/producers.rs:43:70
   |
43 | pub fn top<Table: diesel::Table + diesel::query_dsl::InternalJoinDsl<_, diesel::query_source::joins::Inner, _>>(table: Table, limit: usize, connection: DbConn) -> RestResult<Vec<TopWineType>> {
   |                                                                      ^ not allowed in type signatures

error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> src/producers.rs:43:109
   |
43 | pub fn top<Table: diesel::Table + diesel::query_dsl::InternalJoinDsl<_, diesel::query_source::joins::Inner, _>>(table: Table, limit: usize, connection: DbConn) -> RestResult<Vec<TopWineType>> {
   |                                                                                                             ^ not allowed in type signatures

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0121`.
error: could not compile `vinoteca`.

```

Reproduce rustc bisect report:

```
cargo bisect-rustc --start 2019-12-31 --end 2020-01-01 --prompt
```

**Comment by estebank** [comment]
Mea culpa.

**Comment by chrissimpkins** [comment]
@estebank Esteban, I'm not sure if this is the same ICE that was reported in the OP.  The source that I used was from https://github.com/rust-lang/rust/issues/68801#issuecomment-582920167 based on the request in https://github.com/rust-lang/rust/issues/68801#issuecomment-585825312.  

I'm not seeing a `'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1'` ICE in the vinotecta source with the current nightly.

**Comment by estebank** [comment]
@chrissimpkins by fixing that underlying bad gating of `_` in type parameters the crate no longer panics:

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> src/producers.rs:43:70
   |
43 | pub fn top<Table: diesel::Table + diesel::query_dsl::InternalJoinDsl<_, diesel::query_source::joins::Inner, _>>(table: Table, limit: usize, connection: DbConn) -> RestResult<Vec<TopWineType>> {
   |                                                                      ^ not allowed in type signatures

error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> src/producers.rs:43:109
   |
43 | pub fn top<Table: diesel::Table + diesel::query_dsl::InternalJoinDsl<_, diesel::query_source::joins::Inner, _>>(table: Table, limit: usize, connection: DbConn) -> RestResult<Vec<TopWineType>> {
   |                                                                                                             ^ not allowed in type signatures

error: aborting due to 2 previous errors
```

**Comment by jyn514** [comment]
I have a repro for the first panic, not for the panic while panicking yet:

```rust
extern crate diesel;
pub fn top<Table: diesel::Table +
                  diesel::query_dsl::InternalJoinDsl<
                    _, diesel::query_source::joins::Inner, _
                  >>(
    table: Table
) {}
```
```
$ cargo +nightly check
error: internal compiler error: bad placeholder type
 --> src/lib.rs:4:21
  |
4 |                     _, diesel::query_source::joins::Inner, _
  |                     ^

error: internal compiler error: bad placeholder type
 --> src/lib.rs:4:60
  |
4 |                     _, diesel::query_source::joins::Inner, _
  |                                                            ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:347:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (859764425 2020-01-07) running on x86_64-unknown-linux-musl

note: compiler flags: -C debuginfo=2 -C incremental -C target-feature=-crt-static --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `vinoteca`.
```

**Comment by jyn514** [comment]
Ok, I think this is as small as I can make all 8 errors:

```rust
#[macro_use]
extern crate diesel;

mod schema {
    table! {
        producers (id) {
            id -> Integer,
        }
    }

    table! {
        purchases (id) {
            id -> Integer,
            wine_id -> Integer,
        }
    }

    table! {
        wines (id) {
            id -> Integer,
            producer_id -> Integer,
        }
    }

    joinable!(purchases -> wines (wine_id));

    allow_tables_to_appear_in_same_query!(
        producers,
        purchases,
        wines,
    );
}

mod model {
    use crate::schema::{purchases, wines};
    use diesel::prelude::*;

    pub fn top<Table: diesel::Table +
                      diesel::query_dsl::InternalJoinDsl<
                        _, diesel::query_source::joins::Inner, _
                      >>(
        table: Table
    ) {
        table.inner_join(wines::table.inner_join(purchases::table))
    }
}
```

**Comment by hellow554** [comment]
@estebank is this related to your PR #69148 and will this be fixed as well?

**Comment by estebank** [comment]
@hellow554 I'm 99% sure it will.
