### ISSUE TITLE
rustc panic when using format! incorrectly in fold

### ISSUE THREAD

**Issue by andresv** [rust-lang/rust#69246]
I tried to print out vec of tuples as hex string.
`let v = vec![(0, 1), (0, 2)];` would have printed out as `(00, 01), (00, 02)`.

### Code
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2770538ab32b24cf531f31419ea6bb02
```
fn main() {
    let v = vec![(0, 1), (0, 2)];
    let m = v.iter().fold("", |acc, (id, msg)| acc + format!("({:02X}, {:02X}), ", id, msg));
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-apple-darwin
release: 1.41.0
LLVM version: 9.0
```

### Error output

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src/main.rs"), BytePos(0)), end: (Macros("::alloc::macros::format"), BytePos(8496805)) })', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0 (5e1a79984 2020-01-27) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `crash`.

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src/main.rs"), BytePos(0)), end: (Macros("::alloc::macros::format"), BytePos(8496805)) })', src/libcore/result.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  12: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
  13: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
  14: rustc_errors::HandlerInner::emit_diagnostic
  15: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  16: rustc_typeck::check::op::<impl rustc_typeck::check::FnCtxt>::check_overloaded_binop
  17: rustc_typeck::check::op::<impl rustc_typeck::check::FnCtxt>::check_binop
  18: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  19: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  20: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  21: rustc_typeck::check::check_fn
  22: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  24: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  25: rustc_typeck::check::FnCtxt::check_argument_types
  26: rustc_typeck::check::FnCtxt::check_method_argument_types
  27: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  29: rustc_typeck::check::FnCtxt::check_decl_initializer
  30: rustc_typeck::check::FnCtxt::check_decl_local
  31: rustc_typeck::check::FnCtxt::check_stmt
  32: rustc_typeck::check::FnCtxt::check_block_with_expected
  33: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  34: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  35: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  36: rustc_typeck::check::check_fn
  37: rustc::ty::context::tls::with_context::{{closure}}
  38: rustc_typeck::check::typeck_tables_of
  39: rustc::ty::query::__query_compute::typeck_tables_of
  40: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  41: rustc::dep_graph::graph::DepGraph::with_task_impl
  42: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  43: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  44: rustc_typeck::check::typeck_item_bodies
  45: rustc::ty::query::__query_compute::typeck_item_bodies
  46: rustc::dep_graph::graph::DepGraph::with_task_impl
  47: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  48: rustc::util::common::time
  49: rustc_typeck::check_crate
  50: rustc_interface::passes::analysis
  51: rustc::ty::query::__query_compute::analysis
  52: rustc::dep_graph::graph::DepGraph::with_task_impl
  53: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  54: rustc::ty::context::tls::enter_global
  55: rustc_interface::interface::run_compiler_in_existing_thread_pool
  56: std::thread::local::LocalKey<T>::with
  57: scoped_tls::ScopedKey<T>::set
  58: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0 (5e1a79984 2020-01-27) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] processing `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `crash`.

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by jonas-schievink** [comment]
Looks like it's already fixed in nightly, so closing as fixed.
