### ISSUE TITLE
ICE in constprop due to out of bounds access in a zero sized array

### ISSUE THREAD

**Issue by gwafotapa** [rust-lang/rust#69312]
Here's the crashing code I came down to:

- An empty `main.rs`
- `lib.rs` contains a single line: "pub mod matrix.rs"
- a file `matrix.rs` with the following code:

```rust
pub struct Bug {
    field: usize,
}

impl Bug {
    pub fn test(&self) {
        let cols = [self.field; 0];
        cols[self.field];
    }
}
```

This happened as I permuted type and size in my array definition. My intention was not to declare a zero sized array but to declare an array filled with zeros. Anyway, the compiler crashed. I noticed that if I remove the `pub` from the line in lib.rs, it compiles fine.

## Meta

```
rustc --verbose --version:

rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-unknown-linux-gnu
release: 1.41.0
LLVM version: 9.0
```

Backtrace:

```
   Compiling bug v0.1.0 (/home/guillaume/projects/bug)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `0`', src/librustc/mir/interpret/value.rs:319:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
  12: rust_begin_unwind
             at src/libstd/panicking.rs:375
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  14: rustc_mir::interpret::visitor::ValueVisitor::walk_value
  15: rustc_mir::interpret::validity::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::validate_operand
  16: <rustc_mir::transform::const_prop::ConstPropagator as rustc::mir::visit::MutVisitor>::visit_statement
  17: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  18: rustc_mir::transform::run_passes
  19: rustc_mir::transform::run_optimization_passes
  20: rustc_mir::transform::optimized_mir
  21: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::optimized_mir>::compute
  22: rustc::dep_graph::graph::DepGraph::with_task_impl
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  24: rustc::ty::<impl rustc::ty::context::TyCtxt>::instance_mir
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_crate_mono_items::{{closure}}
  27: rustc::util::common::time
  28: rustc_mir::monomorphize::collector::collect_crate_mono_items
  29: rustc::util::common::time
  30: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  31: rustc::ty::query::__query_compute::collect_and_partition_mono_items
  32: rustc::dep_graph::graph::DepGraph::with_task_impl
  33: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  34: rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local
  35: rustc::ty::query::__query_compute::exported_symbols
  36: rustc::dep_graph::graph::DepGraph::with_task_impl
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  38: rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root
  39: rustc::ty::context::tls::with_context::{{closure}}
  40: rustc_metadata::rmeta::encoder::encode_metadata
  41: rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::creader::CStore>::encode_metadata
  42: rustc::ty::context::TyCtxt::encode_metadata
  43: rustc_interface::passes::start_codegen::{{closure}}
  44: rustc_interface::passes::start_codegen
  45: rustc::ty::context::tls::enter_global
  46: rustc_interface::queries::Queries::ongoing_codegen
  47: rustc_interface::interface::run_compiler_in_existing_thread_pool
  48: std::thread::local::LocalKey<T>::with
  49: scoped_tls::ScopedKey<T>::set
  50: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0 (5e1a79984 2020-01-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `matrix::Bug::test`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
#2 [exported_symbols] exported_symbols
end of query stack
error: could not compile `bug`.
```

**Comment by Centril** [comment]
cc @wesleywiser @oli-obk

**Comment by oli-obk** [comment]
cc @RalfJung did the value visitor changes get merged?

**Comment by RalfJung** [comment]
@oli-obk  https://github.com/rust-lang/rust/pull/69257 is still waiting for review if that's the one you mean.

**Comment by RalfJung** [comment]
The ICE seems to be [gone on nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=850991cefb8b838cc6a0374df5414ce3), though. So likely just needs a test?

**Comment by Centril** [comment]
@RalfJung Maybe we should also find the PR that fixed this and beta nominate?

**Comment by wesleywiser** [comment]
`cargo bisect-rustc` points to #67501 as being responsible for fixing this.

**Comment by oli-obk** [comment]
That PR is too big to backport. I suggest to just remove the assertion on beta as the ICE is properly fixed on master

**Comment by oli-obk** [comment]
Still need to backport

**Comment by JohnTitor** [comment]
The fix is already on beta so backport is unneeded?

**Comment by RalfJung** [comment]
Yeah, playground confirms that this ICEs on stable but works fine on beta and nightly.
