### ISSUE TITLE
PathBuf join sometimes adds ASCII 0x7F to the end of the path

### ISSUE THREAD

**Issue by rehwinkel** [rust-lang/rust#69483]
I tried this code:

```rust
let current_dir = env::current_dir().expect("no current dir");
let lib_path = current_dir.join(libname);
let str_path = lib_path.to_str().unwrap(); // for debugging
let bytes_path = lib_path.to_str().unwrap().as_bytes(); // for debugging
let lib = unsafe { LibRc::new(lib_path) }.expect("failed to load library");
```

I expected to see this happen: The `PathBuf` should be passed to `LibRc::new` and load a dynamic library. LibRc uses the byte representation of the String to load a dynamic library. The contents of the PathBuf should be the joined path name.

Instead, this happened: Sometimes, the byte representation of the PathBuf is correct and the library loads sucessfully. Sometimes there is a strange 0x7f at the end of the string, and `LibRc::new` fails to load the library because it can't find the file anymore. Here's the lldb output when the error arises:
```
(&str) libname = (data_ptr = "libmath.so", length = 10)
(std::path::PathBuf) lib_path = {
  inner = {
    inner = {
      inner = {
        buf = {
          ptr = (pointer = "/home/ian/Desktop/Rust/OliveScript/libmath.so\x7f", _marker = core::marker::PhantomData<unsigned char> @ 0x00007fffffffa550)
          cap = 68
          a = {}
        }
        len = 45
      }
    }
  }
}
(&str) str_path = (data_ptr = "/home/ian/Desktop/Rust/OliveScript/libmath.so\x7f", length = 45)
(&[u8]) bytes_path = (data_ptr = "/home/ian/Desktop/Rust/OliveScript/libmath.so\x7f", length = 45)
```

And here's the lldb output where the error doesn't happen:
```
(&str) libname = (data_ptr = "libmath.so", length = 10)
(std::path::PathBuf) lib_path = {
  inner = {
    inner = {
      inner = {
        buf = {
          ptr = (pointer = "/home/ian/Desktop/Rust/OliveScript/libmath.so", _marker = core::marker::PhantomData<unsigned char> @ 0x00007fffffffa550)
          cap = 68
          a = {}
        }
        len = 45
      }
    }
  }
}
(&str) str_path = (data_ptr = "/home/ian/Desktop/Rust/OliveScript/libmath.so", length = 45)
(&[u8]) bytes_path = (data_ptr = "/home/ian/Desktop/Rust/OliveScript/libmath.so", length = 45)
```

Im aware that this issue could also be with the [sharedlib](https://crates.io/crates/sharedlib) crate, but this is unexpected behavior from PathBuf so I'm filing the issue here too.

### Meta

`rustc --version --verbose`:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-unknown-linux-gnu
release: 1.41.0
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'failed to load library: Error(LibraryOpen("/home/ian/Desktop/Rust/OliveScript/libmath.so"), State { next_error: Some(Error(OsError("/home/ian/Desktop/Rust/OliveScript/libmath.so\u{7f}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: core::result::Result<T,E>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:983
  15: olv::interpreter::n_import
             at src/interpreter.rs:428
  16: olv::interpreter::run
             at src/interpreter.rs:722
  17: olv::main
             at src/main_interpreter.rs:14
  18: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  26: main
  27: __libc_start_main
  28: _start
```

</p>
</details>

**Comment by jonas-schievink** [comment]
It's a bug in sharedlib. It seems to assume the path is 0-terminated. The `length` is still correct in your examples, the debugger just seems to print more characters than that.
