### ISSUE TITLE
ICE when runnig clippy-driver on ./ui/raw-ref-op/unusual_locations.rs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#69873]
I'm reporting this in the rustc repo because this crash seems to happen in rustc code.
Feel free to move this to the clippy repo if its a clippy bug.
### Code
The code is a reduced form of `./ui/raw-ref-op/unusual_locations.rs`
```rust
fn main() {
    let x: [i32; {
        let u = 2;
        4
    }] = [2; { 4 }];
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (564758c4c 2020-03-08)
binary: rustc
commit-hash: 564758c4c329e89722454dd2fbb35f1ac0b8b47c
commit-date: 2020-03-08
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0

clippy 0.0.212 (329923e 2020-03-04)
```

### Error output

```
warning: unused variable: `x`
 --> ./ui/raw-ref-op/unusual_locations.rs:3:9
  |
3 |     let x: [i32; {
  |         ^ help: consider prefixing with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

error: internal compiler error: src/librustc/ty/context.rs:530: node_type: no type for node `local u (hir_id=HirId { owner: DefIndex(3), local_id: 2 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused variable: `x`
 --> ./ui/raw-ref-op/unusual_locations.rs:3:9
  |
3 |     let x: [i32; {
  |         ^ help: consider prefixing with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

error: internal compiler error: src/librustc/ty/context.rs:530: node_type: no type for node `local u (hir_id=HirId { owner: DefIndex(3), local_id: 2 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: clippy_driver::report_clippy_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc::ty::context::TypeckTables::node_type::{{closure}}
  21: rustc::ty::context::TypeckTables::node_type
  22: clippy_lints::shadow::check_pat
  23: clippy_lints::shadow::check_expr
  24: clippy_lints::shadow::check_expr
  25: <clippy_lints::shadow::Shadow as rustc_lint::passes::LateLintPass>::check_fn
  26: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn
  27: rustc_hir::intravisit::walk_item
  28: rustc_hir::intravisit::Visitor::visit_nested_item
  29: rustc_hir::intravisit::walk_crate
  30: rustc_lint::late::late_lint_pass_crate
  31: rustc_session::utils::<impl rustc_session::session::Session>::time
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  34: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  35: rustc_session::utils::<impl rustc_session::session::Session>::time
  36: rustc_interface::passes::analysis
  37: rustc::ty::query::__query_compute::analysis
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  40: rustc::ty::context::tls::enter_global
  41: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (329923e 2020-03-04)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

```

</p>
</details>

**Comment by Centril** [comment]
This doesn't seem to reproduce on nightly / the playground (nightly).

**Comment by JohnTitor** [comment]
It's a Clippy ICE, not rustc one.

**Comment by Centril** [comment]
Please transfer the issue to the Clippy repo. :)

**Comment by JohnTitor** [comment]
> Please transfer the issue to the Clippy repo. :)

I don't have access to do so, maybe @Manishearth or @oli-obk could.

**Comment by JohnTitor** [comment]
The fix has landed, I'm not sure we should still transfer, can we just close?

**Comment by matthiaskrgr** [comment]
Let's just close it, I doubt that someone finds this and opens a ticket in the clippy repo until the next clippy sync... :)
