### ISSUE TITLE
src/librustc_infer/traits/codegen/mod.rs:108: Encountered errors `[FulfillmentError(Obligation [...]

### ISSUE THREAD

**Issue by bbigras** [rust-lang/rust#69892]
It's probably the same as #68645 or the other FulfillmentError errors but just in case.

### Code

```toml
[dependencies]
http = "0.2"
tokio = "0.2"
warp = "0.2"

```

```rust
#![feature(async_closure)]

use std::io::Error;
use warp::reject::Reject;
use warp::Filter;

#[derive(Debug)]
struct WarpErr;

impl Reject for WarpErr {}

fn str_err<E: std::fmt::Debug>(e: E) -> warp::Rejection {
    println!("err: {:?}", e);
    warp::reject::custom(WarpErr)
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let routes = filters::get_data();

    warp::serve(routes).run(([0, 0, 0, 0], 8080)).await;

    Ok(())
}

async fn handle_get_data() -> Result<warp::reply::Json, Error> {}

mod filters {
    use super::*;

    pub fn get_data() -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
        warp::get()
            .and_then(async move || handle_get_data().await.map_err(str_err))
            .with(warp::reply::with::header(
                http::header::CACHE_CONTROL,
                "no-cache, no-store, must-revalidate",
            ))
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (564758c4c 2020-03-08)
binary: rustc
commit-hash: 564758c4c329e89722454dd2fbb35f1ac0b8b47c
commit-date: 2020-03-08
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

### Error output

```
    Checking something v0.1.0 (/home/bbigras2/dev/something)
error[E0433]: failed to resolve: could not find `main` in `tokio`
  --> src/main.rs:17:10
   |
17 | #[tokio::main]
   |          ^^^^ could not find `main` in `tokio`

error[E0308]: mismatched types
  --> src/main.rs:26:64
   |
26 | async fn handle_get_data() -> Result<warp::reply::Json, Error> {}
   |                                                                ^^ expected enum `std::result::Result`, found `()`
   |
   = note:   expected enum `std::result::Result<warp::reply::Json, std::io::Error>`
           found unit type `()`

error: internal compiler error: src/librustc_infer/traits/codegen/mod.rs:108: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<impl core::future::future::Future as std::marker::Send>)), depth=7),Ambiguity)]` resolving bounds after type-checking

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (564758c4c 2020-03-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0433.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `something`.

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
    Checking something v0.1.0 (/home/bbigras2/dev/something)
error[E0433]: failed to resolve: could not find `main` in `tokio`
  --> src/main.rs:17:10
   |
17 | #[tokio::main]
   |          ^^^^ could not find `main` in `tokio`

error[E0308]: mismatched types
  --> src/main.rs:26:64
   |
26 | async fn handle_get_data() -> Result<warp::reply::Json, Error> {}
   |                                                                ^^ expected enum `std::result::Result`, found `()`
   |
   = note:   expected enum `std::result::Result<warp::reply::Json, std::io::Error>`
           found unit type `()`

error: internal compiler error: src/librustc_infer/traits/codegen/mod.rs:108: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<impl core::future::future::Future as std::marker::Send>)), depth=7),Ambiguity)]` resolving bounds after type-checking

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc_infer::traits::codegen::<impl rustc_infer::infer::InferCtxt>::drain_fulfillment_cx_or_panic
  21: rustc::ty::context::GlobalCtxt::enter_local
  22: rustc_infer::traits::codegen::codegen_fulfill_obligation
  23: rustc::ty::query::__query_compute::codegen_fulfill_obligation
  24: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::codegen_fulfill_obligation>::compute
  25: rustc::dep_graph::graph::DepGraph::with_task_impl
  26: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  27: rustc_ty::instance::resolve_instance
  28: rustc::ty::instance::Instance::resolve
  29: rustc_mir_build::lints::check
  30: rustc::ty::context::GlobalCtxt::enter_local
  31: rustc_mir_build::build::mir_built
  32: rustc::ty::query::__query_compute::mir_built
  33: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_built>::compute
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  36: rustc_mir::transform::check_unsafety::unsafety_check_result
  37: rustc::ty::query::__query_compute::unsafety_check_result
  38: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::unsafety_check_result>::compute
  39: rustc::dep_graph::graph::DepGraph::with_task_impl
  40: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  41: rustc_mir::transform::mir_const
  42: rustc::ty::query::__query_compute::mir_const
  43: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_const>::compute
  44: rustc::dep_graph::graph::DepGraph::with_task_impl
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  46: rustc_mir::transform::mir_validated
  47: rustc::ty::query::__query_compute::mir_validated
  48: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_validated>::compute
  49: rustc::dep_graph::graph::DepGraph::with_task_impl
  50: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  51: rustc_mir::borrow_check::mir_borrowck
  52: rustc::ty::query::__query_compute::mir_borrowck
  53: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  54: rustc::dep_graph::graph::DepGraph::with_task_impl
  55: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  56: rustc_typeck::collect::type_of::type_of
  57: rustc::ty::query::__query_compute::type_of
  58: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::type_of>::compute
  59: rustc::dep_graph::graph::DepGraph::with_task_impl
  60: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  61: rustc_infer::traits::select::SelectionContext::constituent_types_for_ty
  62: rustc_infer::traits::select::SelectionContext::confirm_candidate
  63: rustc_infer::infer::InferCtxt::probe
  64: rustc_infer::traits::select::SelectionContext::evaluate_stack
  65: rustc::dep_graph::graph::DepGraph::with_anon_task
  66: rustc_infer::traits::select::SelectionContext::evaluate_predicate_recursively
  67: rustc_infer::infer::InferCtxt::probe
  68: rustc_infer::traits::select::SelectionContext::evaluate_root_obligation
  69: rustc::ty::context::GlobalCtxt::enter_local
  70: rustc_traits::evaluate_obligation::evaluate_obligation
  71: rustc::ty::query::__query_compute::evaluate_obligation
  72: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::evaluate_obligation>::compute
  73: rustc::dep_graph::graph::DepGraph::with_task_impl
  74: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  75: rustc_infer::traits::query::evaluate_obligation::<impl rustc_infer::infer::InferCtxt>::evaluate_obligation
  76: rustc_infer::traits::query::evaluate_obligation::<impl rustc_infer::infer::InferCtxt>::predicate_must_hold_considering_regions
  77: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  78: <rustc_infer::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  79: rustc_typeck::check::FnCtxt::check_argument_types
  80: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
  81: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  82: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  83: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  84: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  85: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  86: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  87: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  88: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  89: rustc_typeck::check::FnCtxt::check_stmt
  90: rustc_typeck::check::FnCtxt::check_block_with_expected
  91: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  92: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  93: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  94: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  95: rustc_typeck::check::FnCtxt::check_block_with_expected
  96: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  97: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  98: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_return_expr
  99: rustc_typeck::check::check_fn
 100: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
 101: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
 102: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
 103: rustc_typeck::check::FnCtxt::check_argument_types
 104: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::confirm_builtin_call
 105: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (564758c4c 2020-03-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `warp::filter::Filter` fulfills its obligations
#1 [mir_built] building MIR for
#2 [unsafety_check_result] unsafety-checking `filters::get_data`
#3 [mir_const] processing `filters::get_data`
#4 [mir_validated] processing `filters::get_data`
#5 [mir_borrowck] borrow-checking `filters::get_data`
#6 [type_of] processing `filters::get_data::{{opaque}}#0`
#7 [evaluate_obligation] evaluating trait selection obligation `impl std::clone::Clone+warp::filter::Filter: std::marker::Send`
#8 [typeck_tables_of] type-checking `main`
#9 [typeck_tables_of] type-checking `main::{{closure}}#0`
#10 [type_of] processing `main::{{closure}}#0`
#11 [collect_mod_item_types] collecting item types in top-level module
#12 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0433.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `something`.

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by connorskees** [comment]
I am not able to reproduce this on `rustc 1.46.0-nightly (50fc24d8a 2020-06-25)`

<details>

<summary>Output</summary>

```
error[E0433]: failed to resolve: could not find `main` in `tokio`
  --> src/main.rs:17:10
   |
17 | #[tokio::main]
   |          ^^^^ could not find `main` in `tokio`

error[E0308]: mismatched types
  --> src/main.rs:26:64
   |
26 | async fn handle_get_data() -> Result<warp::reply::Json, Error> {}
   |                                                                ^^ expected enum `std::result::Result`, found `()`
   |
   = note:   expected enum `std::result::Result<warp::reply::Json, std::io::Error>`
           found unit type `()`

error[E0277]: `main` has invalid return type `impl core::future::future::Future`
  --> src/main.rs:18:20
   |
18 | async fn main() -> Result<(), Error> {
   |                    ^^^^^^^^^^^^^^^^^ `main` can only return types that implement `std::process::Termination`
   |
   = help: consider using `()`, or a `Result`

error[E0752]: `main` function is not allowed to be `async`
  --> src/main.rs:18:1
   |
18 | async fn main() -> Result<(), Error> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `main` function is not allowed to be `async`

error: aborting due to 4 previous errors
```

</details>

**Comment by bbigras** [comment]
And I can't reproduce with `rustc 1.46.0-nightly (346aec9b0 2020-07-11)`. thanks!

**Comment by hellow554** [comment]
Regardless of if it doesn't occur in the latest nighzly anymore, thia should be added as a test.
What do you think @jonas-schievink ?

**Comment by Enselic** [comment]
Triage: I was about to add a test but unfortunately the reproducer does not build any more, so let's close this again. Feel free to reopen if the reproducer is updated.
