### ISSUE TITLE
ICE on calling a macro with structs with type params.

### ISSUE THREAD

**Issue by FireCubez** [rust-lang/rust#69948]
### Code

I don't know which part causes the error, but here's the [zipfile](https://cdn.discordapp.com/attachments/255409416772386817/687640266491953199/ffi-std.zip). It's very small, just 3 source files.

### Meta
`rustc --version --verbose`:
```
rustc 1.42.0-nightly (1ce08f9d6 2020-01-18)
binary: rustc
commit-hash: 1ce08f9d631ef767c915270bc63283c6af40dc3f
commit-date: 2020-01-18
host: x86_64-pc-windows-msvc
release: 1.42.0-nightly
LLVM version: 9.0
```

### Error output

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src\\lib.rs"), BytePos(0)), end: (Real("src\\slice.rs"), BytePos(900)) })', src\librustc_errors\lib.rs:197:29
```
<details><summary><strong>Backtrace</strong></summary>
<p>

```
λ set RUST_BACKTRACE=1 && cargo build
   Compiling ffi-std v0.1.0 (D:\projects\active\ffi-std)
warning: unused import: `DerefMut`
 --> src\slice.rs:3:23
  |
3 | use std::ops::{Deref, DerefMut};
  |                       ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src\\lib.rs"), BytePos(0)), end: (Real("src\\slice.rs"), BytePos(900)) })', src\librustc_errors\lib.rs:197:29
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: rustc_feature::active::ACTIVE_FEATURES::f
  11: rustc_errors::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter::ui_testing
  12: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
  13: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
  14: rustc_errors::HandlerInner::emit_diagnostic
  15: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  16: <rustc_typeck::collect::PlaceholderHirTyCollector as rustc_hir::intravisit::Visitor>::visit_ty
  17: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item
  18: <rustc_typeck::variance::terms::InferredIndex as core::fmt::Debug>::fmt
  19: rustc_typeck::expr_use_visitor::ExprUseVisitor::walk_expr
  20: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  21: <rustc_typeck::check::method::CandidateSource as core::fmt::Debug>::fmt
  22: <rustc_typeck::check::method::probe::ProbeScope as core::fmt::Debug>::fmt
  23: <rustc_typeck::check::method::CandidateSource as core::fmt::Debug>::fmt
  24: <rustc_typeck::check::method::CandidateSource as core::fmt::Debug>::fmt
  25: rustc_typeck::check_crate
  26: rustc_interface::passes::QueryContext::print_stats
  27: rustc_driver::pretty::print_after_hir_lowering
  28: rustc_driver::pretty::print_after_hir_lowering
  29: rustc_driver::pretty::print_after_hir_lowering
  30: rustc_driver::pretty::print_after_hir_lowering
  31: rustc_driver::pretty::print_after_hir_lowering
  32: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  33: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  34: rustc_driver::pretty::print_after_hir_lowering
  35: _rust_maybe_catch_panic
  36: rustc_driver::pretty::print_after_hir_lowering
  37: ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  38: std::sys::windows::thread::Thread::new
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (1ce08f9d6 2020-01-18) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_mod_item_types] collecting item types in module `slice`
#1 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: bad placeholder type
  --> src\slice.rs:13:73
   |
13 | constructor!(FFISlice<T>; ptr: *const T, len: usize); display!(FFISlice<_>); debug!(FFISlice<_>);
   |                                                                         ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src\librustc_errors\lib.rs:356:17
stack backtrace:
   0:     0x7ffa63257689 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6dc2c5916632db49
   1:     0x7ffa632822db - core::fmt::write::h52a946af4bd6ee1f
   2:     0x7ffa632492c4 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::hf5e8a05ca8e7e878
   3:     0x7ffa6325bd2c - std::panicking::take_hook::ha0832abcc0af4162
   4:     0x7ffa6325b97c - std::panicking::take_hook::ha0832abcc0af4162
   5:     0x7ffa635270e4 - rustc_driver::report_ice::ha323ff4045a1702c
   6:     0x7ffa6325c534 - std::panicking::rust_panic_with_hook::he93c4e55052d410d
   7:     0x7ffa66f35ced - <rustc_errors::emitter::FileWithAnnotatedLines as core::fmt::Debug>::fmt::h4bdf93aa60e2a43c
   8:     0x7ffa66f2038d - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h5328b60c8ac4780c
   9:     0x7ffa63580c17 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  10:     0x7ffa635954e6 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  11:     0x7ffa6357924c - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  12:     0x7ffa63570ec1 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  13:     0x7ffa67086b60 - _rust_realloc
  14:     0x7ffa670863bb - _rust_realloc
  15:     0x7ffa670840e4 - _rust_realloc
  16:     0x7ffa67085efe - _rust_realloc
  17:     0x7ffa67084595 - _rust_realloc
  18:     0x7ffa99c463bd - _chkstk
  19:     0x7ffa99bc458c - RtlUnwindEx
  20:     0x7ffa632a2255 - <libc::windows::timeval as core::clone::Clone>::clone::h4a298064cb9316a7
  21:     0x7ffa632a307c - <libc::windows::timeval as core::clone::Clone>::clone::h4a298064cb9316a7
  22:     0x7ffa632a3373 - <libc::windows::timeval as core::clone::Clone>::clone::h4a298064cb9316a7
  23:     0x7ffa632a3a90 - <libc::windows::timeval as core::clone::Clone>::clone::h4a298064cb9316a7
  24:     0x7ffa632a23c5 - <libc::windows::timeval as core::clone::Clone>::clone::h4a298064cb9316a7
  25:     0x7ffa99c4633d - _chkstk
  26:     0x7ffa99bc3c00 - RtlWalkFrameChain
  27:     0x7ffa99bc21c4 - RtlRaiseException
  28:     0x7ffa970ca1c8 - RaiseException
  29:     0x7ffa632a272d - <libc::windows::timeval as core::clone::Clone>::clone::h4a298064cb9316a7
  30:     0x7ffa6326de81 - _rust_start_panic
  31:     0x7ffa6326de09 - _rust_start_panic
  32:     0x7ffa6325c6d8 - rust_panic
  33:     0x7ffa6325c5bd - std::panicking::rust_panic_with_hook::he93c4e55052d410d
  34:     0x7ffa6325c095 - rust_begin_unwind
  35:     0x7ffa6327ecd0 - core::panicking::panic_fmt::h65b0fe35a1f41d02
  36:     0x7ffa6327e963 - core::result::unwrap_failed::hf29e45b6f7069c9d
  37:     0x7ffa66f1f0f1 - rustc_feature::active::ACTIVE_FEATURES::f::hcf227fe31d9cbd69
  38:     0x7ffa66f4eebf - rustc_errors::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter::ui_testing::hedf6d55315776364
  39:     0x7ffa66f29d23 - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic::h05308105d22319cf
  40:     0x7ffa66f3e800 - <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic::h407d98d7f1a5e258
  41:     0x7ffa66f23936 - rustc_errors::HandlerInner::emit_diagnostic::h2a744e9c4d7f783d
  42:     0x7ffa66f24d65 - rustc_errors::diagnostic_builder::DiagnosticBuilder::emit::h299227436f9a5eda
  43:     0x7ffa6577933c - <rustc_typeck::collect::PlaceholderHirTyCollector as rustc_hir::intravisit::Visitor>::visit_ty::h484dd1d5e6027811
  44:     0x7ffa65779aea - <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item::h8f7eb766d7b2c612
  45:     0x7ffa657003d9 - <rustc_typeck::variance::terms::InferredIndex as core::fmt::Debug>::fmt::h2d0be5118c71aab8
  46:     0x7ffa65778c04 - rustc_typeck::expr_use_visitor::ExprUseVisitor::walk_expr::hc453a8bdc53ae1da
  47:     0x7ffa658026ad - <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt::hae839609ab16b0ac
  48:     0x7ffa65898d9c - <rustc_typeck::check::method::CandidateSource as core::fmt::Debug>::fmt::h7a81059ba570a56d
  49:     0x7ffa65764190 - <rustc_typeck::check::method::probe::ProbeScope as core::fmt::Debug>::fmt::h176c8a617c18d3c5
  50:     0x7ffa658df7f7 - <rustc_typeck::check::method::CandidateSource as core::fmt::Debug>::fmt::h7a81059ba570a56d
  51:     0x7ffa658992c4 - <rustc_typeck::check::method::CandidateSource as core::fmt::Debug>::fmt::h7a81059ba570a56d
  52:     0x7ffa656ed6fb - rustc_typeck::check_crate::h4d24d689e19f64ea
  53:     0x7ffa636c5981 - rustc_interface::passes::QueryContext::print_stats::hfb3b5278a85cb9df
  54:     0x7ffa63569c03 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  55:     0x7ffa6356ba95 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  56:     0x7ffa6359755c - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  57:     0x7ffa6359ec1d - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  58:     0x7ffa6356f9a0 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  59:     0x7ffa635418ce - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h6dea0f0ce90733ef
  60:     0x7ffa6353f649 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h6dea0f0ce90733ef
  61:     0x7ffa63564c3c - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  62:     0x7ffa6326dd82 - _rust_maybe_catch_panic
  63:     0x7ffa63572b22 - rustc_driver::pretty::print_after_hir_lowering::he79a023e751fcba8
  64:     0x7ffa632379c7 - ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  65:     0x7ffa6326b637 - std::sys::windows::thread::Thread::new::h4c2df6fe9da6590b
  66:     0x7ffa99a62d92 - BaseThreadInitThunk
  67:     0x7ffa99bb9f64 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (1ce08f9d6 2020-01-18) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `ffi-std`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ffi_std --edition=2018 src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=00922e51e6a8b3d5 -C extra-filename=-00922e51e6a8b3d5 --out-dir D:\projects\active\ffi-std\target\debug\deps -C incremental=D:\projects\active\ffi-std\target\debug\incremental -L dependency=D:\projects\active\ffi-std\target\debug\deps` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

</p>
</details>

**Comment by Centril** [comment]
Let's try to reduce / bisect the bug and see if it reproduces on a current nightly.

@rustbot ping icebreakers-cleanup-crew

**Comment by ketsuban** [comment]
I'm [unable to reproduce this on the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3b46e803c9199b64ae859e1656f9ea47).

**Comment by FireCubez** [comment]
It seems this may have been patched on the latest nightly. I'm currently unable to test.

**Comment by Centril** [comment]
Great, I think we can close the issue then. Thanks for the report.
