### ISSUE TITLE
[const_generics]: encountered bad ConstKind in codegen

### ISSUE THREAD

**Issue by crawford** [rust-lang/rust#70125]
### Code

```rust
#![feature(const_generics)]

const L: usize = 3;

fn main() {
    let p = Printer {};
    p.print(&[1, 2, 3]);
}

trait Print<const LEN: usize> {
    fn print(&self, _data: &[u8; LEN]) {
        for _ in 0..LEN {}
    }
}

struct Printer {}
impl Print<L> for Printer {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

### Error output

```
error: internal compiler error: src/librustc_codegen_ssa/mir/constant.rs:65: encountered bad ConstKind in codegen: Const { ty: usize, val: Unevaluated(DefId(0:11 ~ ice[1944]::{{impl}}[0]::{{constant}}[0]), [], None) }
  --> src/main.rs:12:21
   |
12 |         for _ in 0..LEN {}
   |                     ^^^

thread 'rustc' panicked at 'Box<Any>', src/librustc_codegen_llvm/lib.rs:1:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `ice`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_codegen_ssa/mir/constant.rs:65: encountered bad ConstKind in codegen: Const { ty: usize, val: Unevaluated(DefId(0:11 ~ ice[1944]::{{impl}}[0
]::{{constant}}[0]), [], None) }
  --> src/main.rs:12:21
   |
12 |         for _ in 0..LEN {}
   |                     ^^^

thread 'rustc' panicked at 'Box<Any>', src/librustc_codegen_llvm/lib.rs:1:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::span_bug_fmt
  20: rustc_codegen_ssa::mir::constant::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::eval_mir_constant
  21: rustc_codegen_ssa::mir::operand::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_operand
  22: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue
  23: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
  24: rustc_codegen_ssa::base::codegen_instance
  25: <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  26: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  27: rustc::dep_graph::graph::DepGraph::with_task
  28: rustc_codegen_llvm::base::compile_codegen_unit
  29: rustc_codegen_ssa::base::codegen_crate
  30: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  31: rustc_session::utils::<impl rustc_session::session::Session>::time
  32: rustc_interface::passes::start_codegen
  33: rustc::ty::context::tls::enter_global
  34: rustc_interface::queries::Queries::ongoing_codegen
  35: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

error: could not compile `ice`.
```

</p>
</details>

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70125#issuecomment-602041732).

**Comment by Fi3** [comment]
Got same error with:
```rust
#![feature(const_generics)]

pub fn broke(const_g: u8) -> () {}

pub trait A<const CONST_GEN: u8> {
    fn call_broken() -> () {
        broke(CONST_GEN)
    }
}

const CONST: u8 = 2;

struct Test {}

impl A<CONST> for Test {}

impl Test {
    fn call_broken_<const CONST: u8>() -> () {
        broke(CONST)
    }
}
fn call_ok<const CONST: u8>() -> () {
    broke(CONST)
}
fn main() {
    call_ok::<CONST>();
    Test::call_broken();
    Test::call_broken_::<CONST>();
}
```
It seems unrelated to the type of the const

**Comment by eddyb** [comment]
Reduced:
```rust
#![feature(const_generics)]

fn main() {
    <()>::foo();
}

trait Foo<const X: usize> {
    fn foo() -> usize {
        X
    }
}

impl Foo<{3}> for () {}
```

Looks like a normalization failure to me, but that shouldn't happen for `{3}`.

**Comment by eddyb** [comment]
So I found the bug, this is just outright missing `fold_const`:

But also, it's worrying that this is missing for consts (even if it's not relevant here):
https://github.com/rust-lang/rust/blob/c6b172f7885cb83842fa15e4b0e2ff1647aebb40/src/librustc_trait_selection/traits/project.rs#L321
https://github.com/rust-lang/rust/blob/c6b172f7885cb83842fa15e4b0e2ff1647aebb40/src/librustc_trait_selection/traits/query/normalize.rs#L90

**Comment by eddyb** [comment]
@varkor @yodaldevoid @wesleywiser @oli-obk For the record, what I described above (https://github.com/rust-lang/rust/issues/70125#issuecomment-602133708) isn't fixed, just worked around.
