### ISSUE TITLE
ICE: Switch on discriminant of non-ADT (running cargo clippy)

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/rust#70461]
This did not happe the first time I ran `cargo clippy`, but every subsequent time.
### Code

https://github.com/openanalytics/s3-algo/tree/ice
This tag.

### Meta
```
$ rustc --version --verbose
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-unknown-linux-gnu
release: 1.41.1
LLVM version: 9.0
```

### Error output

```
$ cargo clippy
    Checking s3-algo v0.1.14 (/home/erlend/code/s3-algo)
warning: unused variable: `config`
  --> src/list_actions.rs:26:31
   |
26 |         let ListObjects { s3, config, bucket, stream } = self;
   |                               ^^^^^^ help: try ignoring the field: `config: _`
   |
   = note: `#[warn(unused_variables)]` on by default

error: internal compiler error: src/librustc_mir/dataflow/generic/engine.rs:315: Switch on discriminant of non-ADT

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:881:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1053
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: clippy_driver::report_clippy_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/0eb878d2aa6e3a1cb315f3f328681b26bb4bffdb/src/liballoc/boxed.rs:1031
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/0eb878d2aa6e3a1cb315f3f328681b26bb4bffdb/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  14: std::panicking::begin_panic
  15: rustc_errors::HandlerInner::bug
  16: rustc_errors::Handler::bug
  17: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  18: rustc::ty::context::tls::with_opt::{{closure}}
  19: rustc::ty::context::tls::with_opt
  20: rustc::util::bug::opt_span_bug_fmt
  21: rustc::util::bug::bug_fmt
  22: rustc_mir::dataflow::generic::engine::Engine<A>::iterate_to_fixpoint
  23: <clippy_lints::redundant_clone::RedundantClone as rustc_lint::passes::LateLintPass>::check_fn
  24: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn
  25: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  26: rustc_hir::intravisit::walk_expr
  27: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  28: rustc_hir::intravisit::walk_expr
  29: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  30: rustc_hir::intravisit::walk_expr
  31: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  32: rustc_hir::intravisit::walk_fn
  33: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  34: rustc_hir::intravisit::walk_expr
  35: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  36: rustc_hir::intravisit::walk_expr
  37: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  38: rustc_hir::intravisit::walk_expr
  39: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  40: rustc_hir::intravisit::walk_fn
  41: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  42: rustc_hir::intravisit::walk_impl_item
  43: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  44: rustc_hir::intravisit::walk_item
  45: rustc_hir::intravisit::Visitor::visit_nested_item
  46: rustc_hir::intravisit::walk_item
  47: rustc_hir::intravisit::Visitor::visit_nested_item
  48: rustc_hir::intravisit::walk_crate
  49: rustc_lint::late::late_lint_pass_crate
  50: rustc_session::utils::<impl rustc_session::session::Session>::time
  51: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  52: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  53: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  54: rustc_session::utils::<impl rustc_session::session::Session>::time
  55: rustc_interface::passes::analysis
  56: rustc::ty::query::__query_compute::analysis
  57: rustc::dep_graph::graph::DepGraph::with_task_impl
  58: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  59: rustc::ty::context::tls::enter_global
  60: rustc_interface::interface::run_compiler_in_existing_thread_pool
  61: syntax::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (fc5d0cc 2020-02-24)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `s3-algo`.

To learn more, run the command again with --verbose.
```

**Comment by jonas-schievink** [comment]
Please update to the newest nightly and check if this is still an issue

**Comment by Ploppz** [comment]
Seems fine, thanks.
