### ISSUE TITLE
GitHub Actions: no space left on device on arm-android

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#70738]
Some GitHub Actions arm-android builds are failing due to a lack of disk space:

```
Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

https://github.com/rust-lang-ci/rust/runs/557672408

**Comment by RaldyDaldy** [comment]
https://github.com/rust-lang/rust/issues/70738#issue-593414426

**Comment by RaldyDaldy** [comment]
> Some GitHub Actions arm-android builds are failing due to a lack of disk space:
> 
> ```
> Unhandled exception. System.IO.IOException: No space left on device
>    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
>    at System.IO.FileStream.FlushWriteBuffer()
>    at System.IO.FileStream.Flush(Boolean flushToDisk)
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.Diagnostics.TextWriterTraceListener.Flush()
>    at System.Diagnostics.TraceSource.Flush()
>    at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
>    at GitHub.Runner.Common.TraceManager.Dispose()
>    at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
>    at GitHub.Runner.Common.HostContext.Dispose()
>    at GitHub.Runner.Worker.Program.Main(String[] args)
> System.IO.IOException: No space left on device
>    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
>    at System.IO.FileStream.FlushWriteBuffer()
>    at System.IO.FileStream.Flush(Boolean flushToDisk)
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.Diagnostics.TextWriterTraceListener.Flush()
>    at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
>    at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
>    at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
>    at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
>    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
> System.IO.IOException: No space left on device
>    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
>    at System.IO.FileStream.FlushWriteBuffer()
>    at System.IO.FileStream.Flush(Boolean flushToDisk)
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.Diagnostics.TextWriterTraceListener.Flush()
>    at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
>    at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
>    at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
>    at GitHub.Runner.Common.Tracing.Error(Exception exception)
>    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
> ```
> 
> https://github.com/rust-lang-ci/rust/runs/557672408

Reply

**Comment by pietroalbini** [comment]
@RaldyDaldy hmm, what's up with those comments?

**Comment by pietroalbini** [comment]
This seems to be fixed.
