### ISSUE TITLE
ICE issue-70723.rs:  self.cur_frame() != old_stack || self.frame().block != old_bb' -Zmir-opt-level=3

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#70867]
### Code

```Rust
#![feature(const_loop)]

static _X: () = loop {}; //~ ERROR could not evaluate static initializer

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (b543afca9 2020-04-05)
binary: rustc
commit-hash: b543afca9b90ad6e4689b6d613ab51f9d3ba15e7
commit-date: 2020-04-05
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: self.cur_frame() != old_stack || self.frame().block != old_bb', src/librustc_mir/interpret/step.rs:288:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (b543afca9 2020-04-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: self.cur_frame() != old_stack || self.frame().block != old_bb', src/librustc_mir/interpret/step.rs:288:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1439
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
  14: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
  15: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_raw>::compute
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  17: rustc_query_system::query::plumbing::get_query
  18: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_query_system::query::plumbing::get_query
  22: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_query_system::query::plumbing::get_query
  26: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  27: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly
  28: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_item
  29: rustc_hir::intravisit::Visitor::visit_nested_item
  30: rustc_hir::intravisit::walk_crate
  31: rustc_lint::late::late_lint_crate
  32: rustc_data_structures::sync::join
  33: rustc_interface::passes::analysis::{{closure}}::{{closure}}
  34: rustc_session::utils::<impl rustc_session::session::Session>::time
  35: rustc_interface::passes::analysis
  36: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  37: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  38: rustc_query_system::query::plumbing::get_query
  39: rustc_middle::ty::context::tls::enter_global
  40: rustc_interface::interface::run_compiler_in_existing_thread_pool
  41: scoped_tls::ScopedKey<T>::set
  42: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (b543afca9 2020-04-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=3

query stack during panic:
#0 [const_eval_raw] const-evaluating `_X`
#1 [const_eval_validated] const-evaluating + checking `_X`
#2 [const_eval_validated] const-evaluating + checking `_X`
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Mh nevermind, this was probably merged in a pr today and nightly has not caught up yet...
