### ISSUE TITLE
ICE: No `move_errors` should be allowed in MIR borrowck

### ISSUE THREAD

**Issue by jurkstas** [rust-lang/rust#70934]
I get an ICE when I try to build [evolvim](https://github.com/syberant/evolvim):
```
error: internal compiler error: No `move_errors` should be allowed in MIR borrowck
   --> evolvim-lib\./src/lib\neat\genome\mod.rs:100:13
    |
100 |             InputType::Eye(EYE[2]).clone(),
    |             ^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: No `move_errors` should be allowed in MIR borrowck
  --> evolvim-lib\./src/lib\neat\genome\mod.rs:99:13
   |
99 |             InputType::Eye(EYE[1]).clone(),
   |             ^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: No `move_errors` should be allowed in MIR borrowck
  --> evolvim-lib\./src/lib\neat\genome\mod.rs:98:13
   |
98 |             InputType::Eye(EYE[0]).clone(),
   |             ^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src\librustc_errors\lib.rs:357:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: <rustc_errors::snippet::Style as core::fmt::Debug>::fmt
   8: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   9: rustc_driver::pretty::print_after_hir_lowering
  10: rustc_driver::pretty::print_after_hir_lowering
  11: rustc_driver::pretty::print_after_hir_lowering
  12: rustc_driver::pretty::print_after_hir_lowering
  13: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  14: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  15: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  16: _rust_maybe_catch_panic
  17: rustc_driver::pretty::print_after_hir_lowering
  18: ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  19: std::sys::windows::thread::Thread::new
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```
I tried stable, beta and nightly. All ended with an ICE.
```
>rustc --version --verbose
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-pc-windows-msvc
release: 1.42.0
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
Important detail: Only happens on the `develop` branch, not `master`

**Comment by jonas-schievink** [comment]
(bisecting)

**Comment by jurkstas** [comment]
> Important detail: Only happens on the `develop` branch, not `master`
It happens with master branch as well if I do `cargo update` before building. Without it, it fails due to nalgebra bug before it even gets to evolvim-lib.

**Comment by jonas-schievink** [comment]
Ah, I see

**Comment by jonas-schievink** [comment]
regression in nightly-2019-08-17

https://github.com/rust-lang/rust/compare/f7af19c27...bdfd698f3

**Comment by spastorino** [comment]
@jonas-schievink great :). Unsure if you're bisecting this further, anyway pinging cleanup crew in case you are not doing it further and also to see if someone is able to get an mcve.

@rustbot ping cleanup

**Comment by jonas-schievink** [comment]
There don't seem to be any prebuilt artifacts for that commit range, so I've stopped there.

**Comment by spastorino** [comment]
Assigning `P-high` meanwhile we don't have an mcve as [discussed as part of WG-prioritization procedure](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/.2370934.20ICE.3A.20No.20.60move_errors.60.20in.20borrowck).

**Comment by steffahn** [comment]
```rust

pub fn f() -> () {
    const l: [S2; 1] = [S2];
    S1(l[0]).clone();
}

#[derive(Clone)]
pub struct S1(S2);

#[derive(Clone)]
pub struct S2;

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=31724edefe3b09150653edafe3fa462a))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: constant `l` should have an upper case name
 --> src/lib.rs:3:11
  |
3 |     const l: [S2; 1] = [S2];
  |           ^ help: convert the identifier to upper case: `L`
  |
  = note: `#[warn(non_upper_case_globals)]` on by default

warning: unused return value of `std::clone::Clone::clone` that must be used
 --> src/lib.rs:4:5
  |
4 |     S1(l[0]).clone();
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
  = note: cloning is often expensive and is not expected to have side effects

error: internal compiler error: No `move_errors` should be allowed in MIR borrowck
 --> src/lib.rs:4:5
  |
4 |     S1(l[0]).clone();
  |     ^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:357:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0 (b8cedc004 2020-03-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```
@rustbot modify labels to -E-needs-mcve

**Comment by steffahn** [comment]
The reduced example regresses at nightly-2019-09-29.

**Comment by steffahn** [comment]
Even smaller (same regressing nightly):
```rust
struct S;

fn main() {
    &([S][0],);
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=08904ba3fd3b4d73653187b26bb18e13))

Errors:
<details>
```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: No `move_errors` should be allowed in MIR borrowck
 --> src/main.rs:4:5
  |
4 |     &([S][0],);
  |     ^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:357:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0 (b8cedc004 2020-03-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```
</details>

**Comment by steffahn** [comment]
regression in commit dfd365f3e4fed3df101bd2d3ea01c494f40bd345 (part of #64790)
cc @Centril 
@rustbot modify labels: -E-needs-bisection

**Comment by Mark-Simulacrum** [comment]
Now that we have an [MCVE](https://github.com/rust-lang/rust/issues/70934#issuecomment-611820782) -- thanks @steffahn! -- let's @rustbot prioritize again

**Comment by Centril** [comment]
Looks like this compiles but it shouldn't:
```rust
struct S;

fn foo() {
    &([S][0],);
}
```
Dumping the MIR for this you get:
```rust
fn  foo() -> () {
    let mut _0: ();                      // return place in scope 0 at src/lib.rs:3:10: 3:10
    let _1: &(S,);                       // in scope 0 at src/lib.rs:4:5: 4:15
    let mut _2: &(S,);                   // in scope 0 at src/lib.rs:4:5: 4:15

    bb0: {
        StorageLive(_1);                 // bb0[0]: scope 0 at src/lib.rs:4:5: 4:15
        _2 = const foo::promoted[0];     // bb0[1]: scope 0 at src/lib.rs:4:5: 4:15
                                         // ty::Const
                                         // + ty: &(S,)
                                         // + val: Unevaluated(DefId(0:5 ~ playground[4e22]::foo[0]), [], Some(promoted[0]))
                                         // mir::Constant
                                         // + span: src/lib.rs:4:5: 4:15
                                         // + literal: Const { ty: &(S,), val: Unevaluated(DefId(0:5 ~ playground[4e22]::foo[0]), [], Some(promoted[0])) }
        _1 = _2;                         // bb0[2]: scope 0 at src/lib.rs:4:5: 4:15
        StorageDead(_1);                 // bb0[3]: scope 0 at src/lib.rs:4:15: 4:16
        return;                          // bb0[4]: scope 0 at src/lib.rs:5:2: 5:2
    }
}

promoted[0] in  foo: &(S,) = {
    let mut _0: &(S,);                   // return place in scope 0 at src/lib.rs:4:5: 4:15
    let mut _1: (S,);                    // in scope 0 at src/lib.rs:4:6: 4:15
    let mut _2: S;                       // in scope 0 at src/lib.rs:4:7: 4:13
    let mut _3: [S; 1];                  // in scope 0 at src/lib.rs:4:7: 4:10
    let mut _4: S;                       // in scope 0 at src/lib.rs:4:8: 4:9
    let mut _5: usize;                   // in scope 0 at src/lib.rs:4:11: 4:12

    bb0: {
        _3 = [move _4];                  // bb0[0]: scope 0 at src/lib.rs:4:7: 4:10
        _5 = const 0usize;               // bb0[1]: scope 0 at src/lib.rs:4:11: 4:12
                                         // ty::Const
                                         // + ty: usize
                                         // + val: Value(Scalar(0x0000000000000000))
                                         // mir::Constant
                                         // + span: src/lib.rs:4:11: 4:12
                                         // + literal: Const { ty: usize, val: Value(Scalar(0x0000000000000000)) }
        _2 = move _3[_5];                // bb0[2]: scope 0 at src/lib.rs:4:7: 4:13
        (_1.0: S) = move _2;             // bb0[3]: scope 0 at src/lib.rs:4:6: 4:15
        _0 = &_1;                        // bb0[4]: scope 0 at src/lib.rs:4:5: 4:15
        return;                          // bb0[5]: scope 0 at src/lib.rs:4:5: 4:15
    }
}
```

Presumably, what should happen here is:
```
error[E0508]: cannot move out of type `[S; 1]`, a non-copy array
 --> src/lib.rs:4:6
  |
4 |    &([S][0],);
  |      ^^^^^^
  |      |
  |      cannot move out of here
  |      move occurs because value has type `S`, which does not implement the `Copy` trait
```

The `delay_span_bug` occurs here:
```rust
impl<'tcx> MirPass<'tcx> for ElaborateDrops {
    fn run_pass(&self, tcx: TyCtxt<'tcx>, src: MirSource<'tcx>, body: &mut BodyAndCache<'tcx>) {
        debug!("elaborate_drops({:?} @ {:?})", src, body.span);

        let def_id = src.def_id();
        let param_env = tcx.param_env(src.def_id()).with_reveal_all();
        let move_data = match MoveData::gather_moves(body, tcx, param_env) {
            Ok(move_data) => move_data,
            Err((move_data, _)) => {
                tcx.sess.delay_span_bug(
                    body.span,
                    "No `move_errors` should be allowed in MIR borrowck",
                );
                move_data
            }
        };
```

cc @oli-obk @matthewjasper

**Comment by spastorino** [comment]
This issue is already prioritized as `P-high` removing `I-prioritize` label.

**Comment by oli-obk** [comment]
I guess we need to track down where `error[E0508]: cannot move out of type `[S; 1]`, a non-copy array` is emitted and make that code also look at the MIR of promoteds.

We can't avoid that code from getting promoted without getting into an unfun game of whack-a-mole in the promotion code.

**Comment by Centril** [comment]
The error is constructed here:
https://github.com/rust-lang/rust/blob/ba72b15666b2491415aec703a02c2364fe5e2790/src/librustc_mir/util/borrowck_errors.rs#L281-L305
which is called here:
https://github.com/rust-lang/rust/blob/ba72b15666b2491415aec703a02c2364fe5e2790/src/librustc_mir/borrow_check/diagnostics/move_errors.rs#L258
and here:
https://github.com/rust-lang/rust/blob/ba72b15666b2491415aec703a02c2364fe5e2790/src/librustc_mir/borrow_check/diagnostics/move_errors.rs#L331

**Comment by oli-obk** [comment]
hmmm... not sure what borrowck does to promoteds. I mean we basically declared all lifetimes to be static, but the same is true for the body of constants which we do run borrowck on. So... let's try to just run borrowck on promoteds and see how it goes.

**Comment by oli-obk** [comment]
alternatively we just run the `gather_moves` logic on promoteds instead of full borrowck, as the latter may have a significant perf impact.
