### ISSUE TITLE
GAT ICEs: different parameter counts, cat_expr Errd, broken MIR, debuginfo

### ISSUE THREAD

**Issue by lily-commure** [rust-lang/rust#71176]
The following code produces four separate ICEs, including the known #68648.  The behavior is different between release and debug mode.

### Code

[Playground link](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=f65cb5297fbe6a74e65e40fcba511885)

```Rust
#![feature(generic_associated_types)]

trait Provider {
    type A<'a>;
}

impl Provider for () {
    type A<'a> = ();
}

struct Holder<B> {
  inner: Box<dyn Provider<A = B>>,
}

fn main() {
    Holder {
        inner: Box::new(()),
    };
}
```

### Meta

(Environment is the Rust Playground)

```
rustc 1.44.0-nightly (edc02580e 2020-04-14) running on x86_64-unknown-linux-gnu
```

### Error output

<details><summary><strong>Release mode error output</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
warning: the feature `generic_associated_types` is incomplete and may cause the compiler to crash
 --> src/main.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

warning: field is never read: `inner`
  --> src/main.rs:12:3
   |
12 |   inner: Box<dyn Provider<A = B>>,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: 2 warnings emitted

error: internal compiler error: impl item and trait item have different parameter counts

error: internal compiler error: cat_expr Errd
  --> src/main.rs:16:5
   |
16 | /     Holder {
17 | |         inner: Box::new(()),
18 | |     };
   | |_____^

error: internal compiler error: broken MIR in DefId(0:12 ~ playground[bef7]::main[0]) (LocalDecl { mutability: Not, local_info: Other, internal: false, is_block_tail: None, ty: Holder<[type error]>, user_ty: UserTypeProjections { contents: [] }, source_info: SourceInfo { span: src/main.rs:16:5: 18:6, scope: scope[0] } }): bad type Holder<[type error]>
  --> src/main.rs:15:1
   |
15 | / fn main() {
16 | |     Holder {
17 | |         inner: Box::new(()),
18 | |     };
19 | | }
   | |_^

error: internal compiler error: broken MIR in DefId(0:12 ~ playground[bef7]::main[0]) (LocalDecl { mutability: Mut, local_info: Other, internal: false, is_block_tail: None, ty: std::boxed::Box<dyn Provider<A = [type error]>>, user_ty: UserTypeProjections { contents: [] }, source_info: SourceInfo { span: src/main.rs:17:16: 17:28, scope: scope[0] } }): bad type std::boxed::Box<dyn Provider<A = [type error]>>
  --> src/main.rs:15:1
   |
15 | / fn main() {
16 | |     Holder {
17 | |         inner: Box::new(()),
18 | |     };
19 | | }
   | |_^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  14: core::ptr::drop_in_place
  15: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  16: core::ptr::drop_in_place
  17: rustc_interface::interface::run_compiler_in_existing_thread_pool
  18: scoped_tls::ScopedKey<T>::set
  19: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (edc02580e 2020-04-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C codegen-units=1 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
</p>
</details>

<details><summary><strong>Debug mode error output</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
warning: the feature `generic_associated_types` is incomplete and may cause the compiler to crash
 --> src/main.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

warning: field is never read: `inner`
  --> src/main.rs:12:3
   |
12 |   inner: Box<dyn Provider<A = B>>,
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

error: internal compiler error: src/librustc_codegen_ssa/debuginfo/type_names.rs:207: debuginfo: Trying to create type name for unexpected type: [type error]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:904:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::bug_fmt
  20: rustc_codegen_ssa::debuginfo::type_names::push_debuginfo_type_name
  21: rustc_codegen_ssa::debuginfo::type_names::push_debuginfo_type_name::push_type_params
  22: rustc_codegen_ssa::debuginfo::type_names::compute_debuginfo_type_name
  23: rustc_codegen_llvm::debuginfo::metadata::type_metadata
  24: rustc_codegen_llvm::debuginfo::metadata::type_metadata::{{closure}}
  25: rustc_codegen_llvm::debuginfo::metadata::type_metadata
  26: rustc_codegen_llvm::debuginfo::<impl rustc_codegen_ssa::traits::debuginfo::DebugInfoMethods for rustc_codegen_llvm::context::CodegenCx>::create_function_debug_context::get_function_signature
  27: rustc_codegen_llvm::debuginfo::<impl rustc_codegen_ssa::traits::debuginfo::DebugInfoMethods for rustc_codegen_llvm::context::CodegenCx>::create_function_debug_context
  28: rustc_codegen_ssa::mir::codegen_mir
  29: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  30: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  32: rustc_codegen_llvm::base::compile_codegen_unit
  33: rustc_codegen_ssa::base::codegen_crate
  34: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  35: rustc_interface::passes::start_codegen
  36: rustc_middle::ty::context::tls::enter_global
  37: rustc_interface::queries::Queries::ongoing_codegen
  38: rustc_interface::interface::run_compiler_in_existing_thread_pool
  39: scoped_tls::ScopedKey<T>::set
  40: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (edc02580e 2020-04-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error; 2 warnings emitted

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
</p>
</details>

**Comment by casey** [comment]
This now only produces the parameter count ICE.

I tried to cut it down a little bit, and the following is as minimal as I could get it:

```rust
trait A {
    type B<'a>;
}

struct C(&'static dyn A<B = ()>);

fn main() {}
```

The message is now `error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:475:25: Region parameter out of range when substituting in region 'a (index=1)`.

Additionally, there is a related ICE which produces a slightly different error message:

```rust
trait A {
    type B<T>;
}

trait C {
    type D: A<B = ()>;
}

fn main() {}
```

Which produces the message ``error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:528:17: type parameter `T/#1` (T/1) out of range when substituting, substs=[<Self as C>::D]``.

**Comment by matthiaskrgr** [comment]
The last example that `@casey` linked which does not use a feature gate crashes nightly and beta but not stable.
 
 @rustbot modify labels: +regression-from-stable-to-beta

**Comment by matthiaskrgr** [comment]
ICE in 
````rust
trait A {
    type B<T>;
}

trait C {
    type D: A<B = ()>;
}

fn main() {}
````
bisected to 08e2d4616613716362b4b49980ff303f2b9ae654 cc @matthewjasper

**Comment by matthewjasper** [comment]
#79554 is the proper fix for this. I guess I could put in a temporary fatal error when specifying a GAT in a trait path for now if people think that it is worth it.

**Comment by jackh726** [comment]
Should work after #79554
