### ISSUE TITLE
Issue when running cargo test in nested lib in a workspace.

### ISSUE THREAD

**Issue by abrassel** [rust-lang/rust#71778]
I tried this code:

```rust test```

I expected to see my tests run.

Instead, this happened: ```thread panicked while panicking. aborting.```

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

```
running 2 tests
thread 'linked_bst::tests::test_inorder' panicked at 'thread 'assertion failed: `(left == right)`
  left: `Some(10)`,
 right: `Some(1)`linked_bst::tests::test_preorder', ' panicked at 'pqueue/src/linked_bst.rsassertion failed: `(left == right)`
  left: `Some(7)`,
 right: `Some(4)`:', 250pqueue/src/linked_bst.rs::9223
:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: pqueue::linked_bst::tests::test_inorder
             at pqueue/src/linked_bst.rs:250
  14: pqueue::linked_bst::tests::test_inorder::{{closure}}
             at pqueue/src/linked_bst.rs:235
  15: core::ops::function::FnOnce::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  18: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  19: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  20: test::run_test_in_process
             at src/libtest/lib.rs:539
  21: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:452
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'linked_bst::tests::test_inorder' panicked at 'not yet implemented', pqueue/src/linked_bst.rs:stack backtrace:
69:9
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: pqueue::linked_bst::tests::test_preorder
             at pqueue/src/linked_bst.rs:223
  14: pqueue::linked_bst::tests::test_preorder::{{closure}}
             at pqueue/src/linked_bst.rs:207
  15: core::ops::function::FnOnce::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  18: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  19: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  20: test::run_test_in_process
             at src/libtest/lib.rs:539
  21: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:452
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'linked_bst::tests::test_preorder' panicked at 'not yet implemented', pqueue/src/linked_bst.rs:stack backtrace:
69:9
   0:     0x563e4d00a8c4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x563e4d00a8c4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x563e4d00a8c4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x563e4d00a8c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x563e4d02baac - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x563e4d007657 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x563e4d00cb75 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x563e4d00cb75 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x563e4d00cb75 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x563e4d00c861 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x563e4d00d1da - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x563e4cfb81a7 - std::panicking::begin_panic::hfde593c8adcd0526
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:399
  12:     0x563e4cfb537d - pqueue::linked_bst::LinkedBST<T>::clear::h2873c5d588334bfd
                               at pqueue/src/linked_bst.rs:69
  13:     0x563e4cfb53ee - <pqueue::linked_bst::LinkedBST<T> as core::ops::drop::Drop>::drop::h38b4d751f0d5f3f0
                               at pqueue/src/linked_bst.rs:119
  14:     0x563e4cfba361 - core::ptr::drop_in_place::h35cce6e99d4c3796
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
  15:     0x563e4cfbdf52 - pqueue::linked_bst::tests::test_inorder::hc7f228591a4e9506
                               at pqueue/src/linked_bst.rs:260
  16:     0x563e4cfb770a - pqueue::linked_bst::tests::test_inorder::{{closure}}::h8a090ecf7f7e0c38
                               at pqueue/src/linked_bst.rs:235
  17:     0x563e4cfba29e - core::ops::function::FnOnce::call_once::h88abc37c6a737e12
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  18:     0x563e4cfcb16f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h475aad1d2c31134b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  19:     0x563e4d013e77 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x563e4cfe5f81 - std::panicking::try::hd62f6e4f8420ceba
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  21:     0x563e4cfe5f81 - std::panic::catch_unwind::hc2e8046ccc21e1ce
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  22:     0x563e4cfe5f81 - test::run_test_in_process::h995368d8855d316e
                               at src/libtest/lib.rs:539
  23:     0x563e4cfe5f81 - test::run_test::run_test_inner::{{closure}}::h9d340cbc9c948d1d
                               at src/libtest/lib.rs:452
  24:     0x563e4cfbf8a6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h263f57609c58fd78
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/sys_common/backtrace.rs:129
  25:     0x563e4cfc3e76 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::he48f3c390b307d2a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:475
  26:     0x563e4cfc3e76 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h25632fa6cd6e735b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:318
  27:     0x563e4cfc3e76 - std::panicking::try::do_call::h46edd85e35bab050
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:305
  28:     0x563e4d013e77 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  29:     0x563e4cfc49d6 - std::panicking::try::h689d027f9de46764
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:281
  30:     0x563e4cfc49d6 - std::panic::catch_unwind::h007d6d1ca365ec57
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panic.rs:394
  31:     0x563e4cfc49d6 - std::thread::Builder::spawn_unchecked::{{closure}}::h7348caa4b4241ad9
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/thread/mod.rs:474
  32:     0x563e4cfc49d6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1c0e48707c1ce7ba
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:232
  33:     0x563e4d001baf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he3e3bc9932f56404
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  34:     0x563e4d0133e0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0d82364c11057a62
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  35:     0x563e4d0133e0 - std::sys_common::thread::start_thread::h6cf2238254b521b3
                               at src/libstd/sys_common/thread.rs:13
  36:     0x563e4d0133e0 - std::sys::unix::thread::Thread::new::thread_start::he70a06005b4d03f8
                               at src/libstd/sys/unix/thread.rs:80
  37:     0x7fef0ea50609 - start_thread
  38:     0x7fef0e95c103 - __clone
  39:                0x0 - <unknown>

```

</p>
</details>

**Comment by jonas-schievink** [comment]
The backtrace looks like your tests are simply failing. Is there any reason you believe this is a bug in Rust? If so, you'll need to provide the source code to reproduce this, or it's unlikely that we'll be able to do anything.

**Comment by abrassel** [comment]
Hi, so it was in fact my tests simply failing.  My drop method relied on a method that had todo!() as its contents.  Apologies.
