### ISSUE TITLE
Error: Install Rust Lang on the WLS

### ISSUE THREAD

**Issue by francis-du** [rust-lang/rust#71855]
I tried this code:

```rust
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-04-23, rust version 1.43.0 (4fb7144ed 2020-04-20)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
```

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

### Meta

`rustc --version --verbose`:
```
latest 
```

` cat /etc/issue`:
```
Ubuntu 20.04 LTS 
```

<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
   0:     0x7f60cfcdbc9c - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7f60cfcdbc9c - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7f60cfcdbc9c - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7f60cfcdbc9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7f60cf9ba81c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7f60cfcdb526 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7f60cfcdb19e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7f60cfcdb19e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7f60cfcdb19e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7f60cfcda943 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7f60cfcda943 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x7f60cfcda4be - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x7f60cfcda450 - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x7f60cfcaae86 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::hf33124263a81d2a4
  14:     0x7f60cfc9cd40 - rustup::dist::component::package::unpack_without_first_dir::h352b57d236248e9a
  15:     0x7f60cfc762f6 - rustup::dist::manifestation::Manifestation::update::h8c800deec8167b5b
  16:     0x7f60cfc64b8a - rustup::dist::dist::try_update_from_dist_::h113375517e7a85ca
  17:     0x7f60cfc4964c - rustup::toolchain::Toolchain::install::h048b51ffab245b48
  18:     0x7f60cfc46c8c - rustup::toolchain::Toolchain::install_from_dist::h00b9aafeb93470e5
  19:     0x7f60cf9143ee - rustup_init::self_update::install::h4cee0e396cee456b
  20:     0x7f60cf925ca2 - rustup_init::run_rustup_inner::ha545371fd2dc19a6
  21:     0x7f60cf922d64 - rustup_init::main::hba9a23e308c96901
  22:     0x7f60cf8b7a03 - std::rt::lang_start::{{closure}}::h1778d9ce6385bef5
  23:     0x7f60cf92c458 - main
  24:     0x7f60cf4070b3 - __libc_start_main
  25:     0x7f60cf8b4029 - <unknown>
info: rolling back changes
```

</p>
</details>

**Comment by Xanewok** [comment]
Same happened to me - the current workaround is to use the Ubuntu 18.04 LTS image from the Windows Store.

**Comment by francis-du** [comment]
Thanks for the reply, i try it.

**Comment by francis-du** [comment]
Change to ubuntu18, the installation is normal.

Thanks guys.

**Comment by francis-du** [comment]
Do i need to close this issue?

**Comment by JohnTitor** [comment]
I'd close this issue in favor of https://github.com/rust-lang/rustup/issues/2293#issuecomment-619248357. But feel free to re-open if we could do something here.
