### ISSUE TITLE
broken MIR when transmuting integer to &'static () in const generic

### ISSUE THREAD

**Issue by iwikal** [rust-lang/rust#72293]
### Code

```Rust
#![feature(const_generics)]

struct Const<const P: &'static ()>;

fn main() {
    const A: &'static () = unsafe {
        std::mem::transmute(10 as *const ())
    };

    let _ = Const::<{A}>;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
binary: rustc
commit-hash: a74d1862d4d87a56244958416fd05976c58ca1a8
commit-date: 2020-05-14
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

### Error output

```
warning: the feature `const_generics` is incomplete and may cause the compiler to crash
 --> src/main.rs:1:12
  |
1 | #![feature(const_generics, const_transmute)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

warning: 1 warning emitted

error: internal compiler error: broken MIR in DefId(0:6 ~ main[317d]::main[0]) (CanonicalUserTypeAnnotation { user_ty: Canonical { max_universe: U0, variables: [], value: TypeOf(DefId(0:4 ~ main[317d]::Const[0]::{{constructor}}[0]), UserSubsts { substs: [Const { ty: &'static (), val: Unevaluated(DefId(0:8 ~ main[317d]::main[0]::{{constant}}[0]), [], None) }], user_self_ty: None }) }, span: src/main.rs:10:13: 10:25, inferred_ty: Const<{transmute(0x000000000000000a): &()}> }): bad user type AscribeUserType(Const<{transmute(0x000000000000000a): &()}>, DefId(0:4 ~ main[317d]::Const[0]::{{constructor}}[0]) UserSubsts { substs: [Const { ty: &'static (), val: Unevaluated(DefId(0:8 ~ main[317d]::main[0]::{{constant}}[0]), [], None) }], user_self_ty: None }): NoSolution

error: internal compiler error: broken MIR in DefId(0:6 ~ main[317d]::main[0]) (_1 = Const::<{transmute(0x000000000000000a): &()}>): bad assignment (Const<{transmute(0x000000000000000a): &()}> = Const<{transmute(0x000000000000000a): &()}>): NoSolution
  --> src/main.rs:10:13
   |
10 |     let _ = Const::<{A}>;
   |             ^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(0:6 ~ main[317d]::main[0]) (_1 = Const::<{transmute(0x000000000000000a): &()}>): bad user type on rvalue (CanonicalUserTypeAnnotation { user_ty: Canonical { max_universe: U0, variables: [], value: TypeOf(DefId(0:4 ~ main[317d]::Const[0]::{{constructor}}[0]), UserSubsts { substs: [Const { ty: &'static (), val: Unevaluated(DefId(0:8 ~ main[317d]::main[0]::{{constant}}[0]), [], None) }], user_self_ty: None }) }, span: src/main.rs:10:13: 10:25, inferred_ty: Const<{transmute(0x000000000000000a): &()}> } = Const<{transmute(0x000000000000000a): &()}>): NoSolution
  --> src/main.rs:10:13
   |
10 |     let _ = Const::<{A}>;
   |             ^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (a74d1862d 2020-05-14) running on x86_64-unknown-linux-gnu

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: std::panicking::begin_panic
  13: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  14: core::ptr::drop_in_place
  15: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  16: core::ptr::drop_in_place
  17: rustc_interface::interface::run_compiler_in_existing_thread_pool
  18: scoped_tls::ScopedKey<T>::set
  19: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by Alexendoo** [comment]
Still ICEs but needs const_transmute removed from features after #72920

```rust
#![feature(const_generics)]

struct Const<const P: &'static ()>;

fn main() {
    const A: &'static () = unsafe {
        std::mem::transmute(10 as *const ())
    };

    let _ = Const::<{A}>;
}
```

**Comment by Alexendoo** [comment]
No longer ICEs, bisect shows since #82936

**Comment by RalfJung** [comment]
@oli-obk is that an expected side-effect of your PR?

**Comment by oli-obk** [comment]
Not expected before that PR, but the ICE in this issue "obviously" (in hindsight) occurred because before https://github.com/rust-lang/rust/pull/82936/commits/019dba0cebac1944c74644ba7365490ef3a8c753 the problem was that types were compared exactly (including lifetimes), so a constant of type `&'static ()` is not the same as a constant of type `&'empty ()`, even though all lifetimes in constants' final values are `'static` by definition.

**Comment by lcnr** [comment]
> even though all lifetimes in constants' final values are `'static` by definition.

not necessarily though? You can have constants with non-static lifetimes, even if their target actually does live forever.
```rust
use std::marker::PhantomData;

struct Foo<'a>(&'a (), PhantomData<fn(&'a ()) -> &'a ()>);

fn covariant<'a>(v: Foo<'static>) -> Foo<'a> {
    v // ERROR mismatched types
}

fn covariant_xd<'a>(_: Foo<'static>) -> Foo<'a> {
    Foo::<'a>::ASSOC
}

impl<'a> Foo<'a> {
    const ASSOC: Foo<'a> = Foo(&(), PhantomData);
}
```

**Comment by oli-obk** [comment]
Right. Even so, this doesn't affect `Relate`, as the constants are still equal to each other irrespective of actual lifetimes. The only way I can see this breaking is if we could specialize on lifetimes.
