### ISSUE TITLE
net::tcp::tests::double_bind panics in ./x.py test

### ISSUE THREAD

**Issue by Walther** [rust-lang/rust#72576]
On the `rust` master branch, `git show`
```
commit ee6c0dae394f67b5286909704f8f0a608696c96c (HEAD -> master, origin/master, origin/HEAD)
Merge: 997d953eeec 7c9fdb332bd
Author: bors <bors@rust-lang.org>
Date:   Mon May 25 09:43:59 2020 +0000

    Auto merge of #72562 - RalfJung:rollup-2ngjgwi, r=RalfJung

    Rollup of 5 pull requests

    Successful merges:

     - #71940 (Add `len` and `slice_from_raw_parts` to `NonNull<[T]>`)
     - #72525 (Miri casts: do not blindly rely on dest type)
     - #72537 (Fix InlineAsmOperand expresions being visited twice during liveness checking)
     - #72544 (librustc_middle: Rename upvars query to upvars_mentioned)
     - #72551 (First draft documenting Debug stability.)

    Failed merges:

    r? @ghost
```

Running on a Debian in WSL on Windows 10. `uname -a`
```
Linux matcha 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 GNU/Linux
```

Running `./x.py test` results in a panic & failure. Error snippet:

```
Testing std stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling std v0.0.0 (/home/walther/git/rust/src/libstd)
    Finished release [optimized] target(s) in 34.85s
     Running build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-20605fa9ae467443

running 764 tests
.................................................................................................... 100/764
.................................................................................................... 200/764
....................................thread '<unnamed>' panicked at 'explicit panic', src/libstd/io/buffered.rs:1533:17
...................................................thread '<unnamed>' panicked at 'explicit panic', src/libstd/io/stdio.rs:944.:13
............ 300/764
................................................................................F................... 400/764
.................................................................................................... 500/764
........thread '<unnamed>' panicked at '.called `Result::unwrap()` on an `Err` value: RecvError', src/libstd/sync/mpsc/mod.rs:2741:22
...........thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', .src/libstd/sync/mpsc/mod.rs:2645:13
................thread '<unnamed>.' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libstd/sync/mpsc/mod.rs:2766:17
.thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libstd/sync/mpsc/mod.rs:2778.:21
........................thread '<unnamed>' panicked at '.called `Result::unwrap()` on an `Err` value: RecvError', src/libstd/sync/mpsc/mod.rs:1997:22
....thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libstd/sync/mpsc/mod.rs:2034:21
.....thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libstd/sync/mpsc/mod.rs:1916:13.
......................... 600/764
............thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/mutex.rs:634.:13
.thread '<unnamed>' panicked at 'test panic in inner thread to poison mutex', src/libstd/sync/mutex.rs:588:13
...thread '<unnamed>' panicked at 'test panic in inner thread to poison mutex', src/libstd/sync/mutex.rsthread ':<unnamed>564' panicked at ':explicit panic13',
src/libstd/sync/mutex.rs:695:13
...thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/libstd/sync/mutex.rs:658:.13
..........thread '<unnamed>' panicked at 'test panic in inner thread to poison RwLock.', src/libstd/sync/rwlock.rs:789:13
..thread '<unnamed>' panicked at 'test panic in inner thread to poison RwLock', src/libstd/sync/rwlock.rs:765:13
thread '.<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:701:13
.thread '<unnamed>' panicked at '.explicit panic', src/libstd/sync/rwlock.rs:629:13
thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs:641:13.
thread '<unnamed>' panicked at '.explicit panic', src/libstd/sync/rwlock.rs:603:13
thread '<unnamed>' panicked at 'explicit panic', src/libstd/sync/rwlock.rs.:616:13
............................................................ 700/764
......................thread '<unnamed>' panicked at 'explicit panic', src/libstd/thread/mod.rs:1577:37
............thread '<unnamed>' panicked at 'Box<Any>', src/libstd/thread/mod.rs:1712:13
.thread '<unnamed>' panicked at 'owned string', src/libstd/thread/mod.rs:1696:13
.thread '<unnamed>' panicked at 'static string', src/libstd/thread/mod.rs:1680:13
.thread '<unnamed>' panicked at 'Box<Any>', src/libstd/thread/mod.rs:1731:37
...........................
failures:

---- net::tcp::tests::double_bind stdout ----
thread '<unnamed>' panicked at 'This system (perhaps due to options set by TcpListener::bind) permits double binding: TcpListener { addr: V4(127.0.0.1:19612), fd: 14 } and TcpListener { addr: V4(127.0.0.1:19612), fd: 47 }', src/libstd/net/tcp.rs:1315:34


failures:
    net::tcp::tests::double_bind

test result: FAILED. 763 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p std --lib'


command did not execute successfully: "/home/walther/git/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/home/walther/git/rust/src/libtest/Cargo.toml" "-p" "std" "--" "--quiet"
expected success, got: exit code: 101


failed to run: /home/walther/git/rust/build/bootstrap/debug/bootstrap test
Build completed unsuccessfully in 0:11:22
./x.py test  2651.84s user 2522.56s system 757% cpu 11:22.95 total
```

**Comment by Walther** [comment]
Duplicate of https://github.com/rust-lang/rust/pull/58551 and https://github.com/rust-lang/rust/issues/49367

Sorry, only found those after creating this issue 🙈
