### ISSUE TITLE
ICE: Broken MIR

### ISSUE THREAD

**Issue by Spanfile** [rust-lang/rust#72651]
**EDIT: Here's MCVE: https://github.com/rust-lang/rust/issues/72651#issuecomment-636485820**

Error:
```
error: internal compiler error: src/librustc_mir/transform/generator.rs:722: Broken MIR: generator contains type &util::human_version::HumanVersionReq in MIR, but typeck only knows about for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14> {std::future::ResumeTy, &'r factorio::mods::Mods<P>, &'s mod_common::Mod, std::vec::Vec<std::string::String>, impl std::future::Future, (), std::result::Result<std::vec::Vec<mod_common::dependency::Dependency>, anyhow::Error>, std::vec::Vec<mod_common::dependency::Dependency>, std::vec::IntoIter<mod_common::dependency::Dependency>, mod_common::dependency::Dependency, &'t1 mod_common::dependency::Dependency, mod_common::dependency::Requirement, &'t2 str, std::result::Result<&'t3 mod_common::Mod, anyhow::Error>, std::option::Option<util::human_version::HumanVersionReq>, util::human_version::HumanVersionReq, impl std::future::Future, log::Level, bool, [&'t5 str; 4], &'t6 [&'t7 str], &'t8 [&'t9 str; 4], impl std::future::Future, std::string::String, &'t11 std::string::String, [&'t12 str; 3], &'t13 [&'t14 str; 3]}
   --> crates/modtorio/src/factorio/mods.rs:266:38
    |
266 |       ) -> anyhow::Result<Vec<String>> {
    |  ______________________________________^
267 | |         let mut missing = Vec::new();
268 | |
269 | |         for dep in target_mod.dependencies().await? {
...   |
317 | |         Ok(missing)
318 | |     }
    | |_____^

thread 'rustc' panicked at 'Box<Any>', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/macros.rs:13:23
```

Reproduce:
```
git clone https://github.com/Spanfile/Modtorio.git
cd Modtorio
git checkout bf757a3f710dd7af60b82e322790dddd77680483
cargo clippy
```

```
$ cargo clippy -V
clippy 0.0.212 (a74d186 2020-05-14)
$ cargo -V
cargo 1.45.0-nightly (cb06cb269 2020-05-08)
$ rustc -V
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
```

**Comment by Spanfile** [comment]
I've created an MCVE. Seems it's related to borrowing the pattern variable in the match guard after an `await` in the same guard.

```rust
fn main() {}

struct StructA {}
struct StructB {}

impl StructA {
    fn fn_taking_struct_b(&self, struct_b: &StructB) -> bool {
        true
    }
}

async fn get_struct_a_async() -> StructA {
    StructA {}
}

async fn ice() {
    match Some(StructB {}) {
        Some(struct_b) if get_struct_a_async().await.fn_taking_struct_b(&struct_b) => {}
        _ => {}
    }
}
```

`RUST_BACKTRACE=1 RUSTFLAGS="--emit mir" cargo check`
```
error: internal compiler error: src/librustc_mir/transform/generator.rs:713: Broken MIR: generator contains type &StructB in MIR, but typeck only knows about {std::future::ResumeTy, StructB, std::option::Option<StructB>, impl std::future::Future, ()}
  --> src/main.rs:20:16
   |
20 |   async fn ice() {
   |  ________________^
21 | |     match Some(StructB {}) {
22 | |         Some(struct_b) if get_struct_a_async().await.fn_taking_struct_b(&struct_b) => {}
23 | |         _ => {}
24 | |     }
25 | | }
   | |_^

thread 'rustc' panicked at 'Box<Any>', /rustc/74e80468347471779be6060d8d7d6d04e98e467f/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::span_bug_fmt
  20: <rustc_mir::transform::generator::StateTransform as rustc_mir::transform::MirPass>::run_pass
  21: rustc_mir::transform::run_passes
  22: rustc_mir::transform::run_optimization_passes
  23: rustc_mir::transform::optimized_mir
  24: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
  25: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  27: rustc_query_system::query::plumbing::get_query_impl::{{closure}}
  28: rustc_query_system::query::plumbing::get_query_impl
  29: rustc_mir::util::pretty::write_mir_pretty
  30: rustc_mir::transform::dump_mir::emit_mir
  31: rustc_interface::passes::start_codegen
  32: rustc_middle::ty::context::tls::enter_global
  33: rustc_interface::queries::Queries::ongoing_codegen
  34: rustc_interface::interface::run_compiler_in_existing_thread_pool
  35: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (74e804683 2020-05-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `ice::{{closure}}#0`
end of query stack
```

**Comment by spastorino** [comment]
Assigning `P-medium` as [discussed as part of the Prioritization Working Group process](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2372651.20ICE.3A.20Broken.20MIR) and removing `I-prioritize`.

**Comment by tmandry** [comment]
A smaller MVCE is in https://github.com/rust-lang/rust/issues/74961#issuecomment-666893845

**Comment by nikomatsakis** [comment]
So in our call today we dug into this (will post video later). I'm pretty sure that the problem is this:

* When we build the MIR for a match arm, if there is a pattern guard expression, we wind up creating references to all the bindings that appear in the pattern for use within that expresssion. (So `y if is_even(y) => ...` is kind of desugared to `is_even(*r_y)` where `r_y` is a reference to where `y` lives.
* One fix might be to check if there is an await in the pattern guard for a given arm and, if so, add references to all the bound names that appear in that arm. 

This may or may not be what https://github.com/rust-lang/rust/pull/75213/files is doing, we didn't read it quite deeply enough to tell, but it seems like it might be a bit simpler.


cc @dingxiangfei2009
