### ISSUE TITLE
segfault with -C lto with rustc 1.43.0, 1.44.0 on s390x

### ISSUE THREAD

**Issue by mwhudson** [rust-lang/rust#72723]
I'm updating rustc and cargo on Ubuntu. The build of cargo 0.44.1 on s390x with rustc 1.43.0 fails: 

https://launchpad.net/~mwhudson/+archive/ubuntu/rust-stuff/+build/19366472

One of the failing tests runs this command:

```
rustc --crate-name test src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=7394e033338f9890 -C extra-filename=-7394e033338f9890 --out-dir /build/cargo-IGXegx/cargo-0.44.1/target/s390x-unknown-linux-gnu/cit/t263/foo/target/release/deps -L dependency=/build/cargo-IGXegx/cargo-0.44.1/target/s390x-unknown-linux-gnu/cit/t263/foo/target/release/deps
```

I expected to see this happen: not a segfault

Instead, this happened: "Segmentation fault (core dumped)"

The backtrace from gdb is this:

```
(gdb) bt
#0  memcpy () at ../sysdeps/s390/memcpy-z900.S:191
#1  0x000003fff599b0d4 in core::intrinsics::copy_nonoverlapping (src=0x1 <error: Cannot access memory at address 0x1>, dst=<optimized out>, count=16)
    at /usr/src/rustc-1.43.0/src/libcore/intrinsics.rs:1999
#2  core::slice::<impl [T]>::copy_from_slice (self=..., src=...) at /usr/src/rustc-1.43.0/src/libcore/slice/mod.rs:2280
#3  <alloc::vec::Vec<T> as alloc::vec::SpecExtend<&T,core::slice::Iter<T>>>::spec_extend (self=0x3fff06b31f8, iterator=...) at /usr/src/rustc-1.43.0/src/liballoc/vec.rs:2124
#4  <alloc::vec::Vec<T> as core::iter::traits::collect::Extend<&T>>::extend (self=0x3fff06b31f8, iter=...) at /usr/src/rustc-1.43.0/src/liballoc/vec.rs:2265
#5  <&str as std::ffi::c_str::CString::new::SpecIntoVec>::into_vec (self=...) at src/libstd/ffi/c_str.rs:346
#6  0x000003fff67be9de in std::ffi::c_str::CString::new (t=...) at /usr/src/rustc-1.43.0/src/libstd/ffi/c_str.rs:351
#7  rustc_codegen_llvm::back::lto::fat_lto (cgcx=0x3fff06b3910, diag_handler=0x3fff06b3310, symbol_white_list=..., modules=..., cached_modules=..., serialized_modules=...)
    at src/librustc_codegen_llvm/back/lto.rs:270
#8  rustc_codegen_llvm::back::lto::run_fat (cgcx=0x3fff06b3910, modules=..., cached_modules=...) at src/librustc_codegen_llvm/back/lto.rs:147
#9  0x000003fff6639dac in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::write::WriteBackendMethods>::run_fat_lto (cgcx=0x3fff06b3910, modules=..., cached_modules=...)
    at src/librustc_codegen_llvm/lib.rs:141
#10 rustc_codegen_ssa::back::write::generate_lto_work (cgcx=0x3fff06b3910, needs_fat_lto=..., needs_thin_lto=..., import_only_modules=...)
    at /usr/src/rustc-1.43.0/src/librustc_codegen_ssa/back/write.rs:284
#11 0x000003fff67a5f1c in rustc_codegen_ssa::back::write::start_executing_work::{{closure}} () at /usr/src/rustc-1.43.0/src/librustc_codegen_ssa/back/write.rs:1304
#12 std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /usr/src/rustc-1.43.0/src/libstd/sys_common/backtrace.rs:130
#13 0x000003fff67009f8 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /usr/src/rustc-1.43.0/src/libstd/thread/mod.rs:475
#14 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=<optimized out>) at /usr/src/rustc-1.43.0/src/libstd/panic.rs:318
#15 std::panicking::try::do_call (data=0x3fff06b4648 "") at /usr/src/rustc-1.43.0/src/libstd/panicking.rs:303
#16 0x000003fff59a1938 in __rust_try () from /lib/s390x-linux-gnu/libstd-388f52bec4c8e58e.so
#17 0x000003fff59a1822 in __rust_maybe_catch_panic (f=<optimized out>, data=<optimized out>, data_ptr=0x3fff06b4638, vtable_ptr=0x3fff06b4640) at src/libpanic_unwind/lib.rs:86
#18 0x000003fff6621e4a in std::panicking::try (f=...) at /usr/src/rustc-1.43.0/src/libstd/panicking.rs:281
#19 std::panic::catch_unwind (f=...) at /usr/src/rustc-1.43.0/src/libstd/panic.rs:394
#20 std::thread::Builder::spawn_unchecked::{{closure}} () at /usr/src/rustc-1.43.0/src/libstd/thread/mod.rs:474
#21 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /usr/src/rustc-1.43.0/src/libcore/ops/function.rs:232
#22 0x000003fff5956028 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (self=..., args=<optimized out>) at /usr/src/rustc-1.43.0/src/liballoc/boxed.rs:1017
#23 0x000003fff596d428 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once (self=0x3ffec6f6ec0, args=<optimized out>) at /usr/src/rustc-1.43.0/src/liballoc/boxed.rs:1017
#24 std::sys_common::thread::start_thread (main=<optimized out>) at src/libstd/sys_common/thread.rs:13
#25 std::sys::unix::thread::Thread::new::thread_start (main=0x3ffec6f6ec0) at src/libstd/sys/unix/thread.rs:80
#26 0x000003fff55099f6 in start_thread (arg=0x3fff06b5900) at pthread_create.c:477
#27 0x000003fff58067e6 in thread_start () at ../sysdeps/unix/sysv/linux/s390/s390-64/clone.S:65
```

src=0x1 in `#1  0x000003fff599b0d4 in core::intrinsics::copy_nonoverlapping (src=0x1 <error: Cannot access memory at address 0x1>, dst=<optimized out>, count=16)` sure looks bad.

I don't have a lot of time to dig into this now, will be able to get back to it and run more tests Tuesday NZ time if there's anything I can run that would be useful.

**Comment by mwhudson** [comment]
One (rather obvious from the traceback) thing: removing "-C lto" from the invocation makes it pass.

The same code passes tests on all other ubuntu architectures, amd64, i386, arm64, ppc64el (not riscv64 because our rustc 1.43.0 didn't build there)

**Comment by mwhudson** [comment]
This happens with any use of -C lto, and happens with stable (rustc 1.43.1 (8d69840ab 2020-05-04)) and beta (rustc 1.44.0-beta.4 (02c25b359 2020-05-23)) installed via rustup but not 1.42.0 (rustc 1.42.0 (b8cedc004 2020-03-09)) or nightly (rustc 1.45.0-nightly (5fd2f06e9 2020-05-31)).

```
ubuntu@juju-b11c42-ubuntu-23:~$ rustup default stable
info: using existing install for 'stable-s390x-unknown-linux-gnu'
info: default toolchain set to 'stable-s390x-unknown-linux-gnu'

  stable-s390x-unknown-linux-gnu unchanged - rustc 1.43.1 (8d69840ab 2020-05-04)

ubuntu@juju-b11c42-ubuntu-23:~$ cat hello.rs
fn main() {
    println!("Hello World!");
}
ubuntu@juju-b11c42-ubuntu-23:~$ rustc -C lto hello.rs 
Segmentation fault (core dumped)
```

**Comment by msirringhaus** [comment]
I can confirm this issue. Same happens on SUSE.

**Comment by tmiasko** [comment]
The same issue as #73324?

**Comment by msirringhaus** [comment]
Looks like it. Thanks for the pointer. I'm trying out the patch from there.

**Comment by msirringhaus** [comment]
I can verify that the patch (applied to the bundled LLVM) solves the issue for me.

**Comment by mwhudson** [comment]
Me too, thanks for the link!
