### ISSUE TITLE
ICE: Hir should have been pre-marked as red or green but wasn't

### ISSUE THREAD

**Issue by fschutt** [rust-lang/rust#72887]
# Code

code: https://github.com/maps4print/azul
branch `rust-ice`

```sh
git clone https://github.com/maps4print/azul
git checkout rust-ice
RUST_BACKTRACE=full cargo check --verbose --example public
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

### Error output

```
    Checking azul-core v0.0.2 (/home/felix/Development/azul/azul-core)
       Fresh serde_bytes v0.11.3
       Fresh bincode v1.2.1
       Fresh font-loader v0.8.0
     Running `rustc --crate-name azul_core --edition=2018 azul-core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type rlib --crate-type cdylib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="azul-css-parser"' --cfg 'feature="css_parser"' --cfg 'feature="default"' --cfg 'feature="gleam"' --cfg 'feature="opengl"' -C metadata=54992c066eb0e957 -C extra-filename=-54992c066eb0e957 --out-dir /home/felix/Development/azul/target/debug/deps -C incremental=/home/felix/Development/azul/target/debug/incremental -L dependency=/home/felix/Development/azul/target/debug/deps --extern azul_css=/home/felix/Development/azul/target/debug/deps/libazul_css-4ffeb28145c985cd.rmeta --extern azul_css_parser=/home/felix/Development/azul/target/debug/deps/libazul_css_parser-b54b1c41bd4e1d4b.rmeta --extern gleam=/home/felix/Development/azul/target/debug/deps/libgleam-b31425c365d33d8c.rmeta`
       Fresh clipboard2 v0.1.1
       Fresh wayland-client v0.23.6
       Fresh image v0.21.3
       Fresh peek-poke v0.2.0
       Fresh wr_malloc_size_of v0.1.0
       Fresh plane-split v0.15.0
       Fresh wayland-protocols v0.23.6
       Fresh azul-webrender-api v0.61.0
       Fresh smithay-client-toolkit v0.6.6
       Fresh azul-webrender v0.61.0
       Fresh winit v0.22.2
       Fresh glutin v0.24.0
error: internal compiler error: src/librustc/dep_graph/graph.rs:686: DepNode Hir(azul_core[9673]::display_list[0]::displaylist_handle_rect[0]::{{misc}}[2]::{{misc}}[0]) should have been pre-marked as red or green but wasn't.

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.1 (8d69840ab 2020-05-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type rlib --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `azul-core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name azul_core --edition=2018 azul-core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type rlib --crate-type cdylib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="azul-css-parser"' --cfg 'feature="css_parser"' --cfg 'feature="default"' --cfg 'feature="gleam"' --cfg 'feature="opengl"' -C metadata=54992c066eb0e957 -C extra-filename=-54992c066eb0e957 --out-dir /home/felix/Development/azul/target/debug/deps -C incremental=/home/felix/Development/azul/target/debug/incremental -L dependency=/home/felix/Development/azul/target/debug/deps --extern azul_css=/home/felix/Development/azul/target/debug/deps/libazul_css-4ffeb28145c985cd.rmeta --extern azul_css_parser=/home/felix/Development/azul/target/debug/deps/libazul_css_parser-b54b1c41bd4e1d4b.rmeta --extern gleam=/home/felix/Development/azul/target/debug/deps/libgleam-b31425c365d33d8c.rmeta` (exit code: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f0867f42e84 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x7f0867f42e84 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x7f0867f42e84 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f0867f42e84 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f0867f7b87c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x7f0867f34ba3 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x7f0867f47cb5 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f0867f47cb5 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f0867f47cb5 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x7f0867f47a02 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x7f08685a14b9 - rustc_driver::report_ice::h8d4b0ce2a38d7202
  11:     0x7f0867f483e5 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:474
  12:     0x7f086acd0903 - std::panicking::begin_panic::h182af0fc049c3d83
  13:     0x7f086ad06b40 - rustc_errors::HandlerInner::bug::h2bc200f0bdb837d8
  14:     0x7f086ad05990 - rustc_errors::Handler::bug::hf04b08124512ba91
  15:     0x7f086a8ccbb2 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h101531c4abdf7645
  16:     0x7f086a8c17eb - rustc::ty::context::tls::with_opt::{{closure}}::ha997b5572c526c4a
  17:     0x7f086a8c173a - rustc::ty::context::tls::with_opt::ha3e111e98ee4052c
  18:     0x7f086a8ccac8 - rustc::util::bug::opt_span_bug_fmt::h0fe4189c307b3479
  19:     0x7f086a8cca32 - rustc::util::bug::bug_fmt::h2f1715e27dd31fab
  20:     0x7f086aa665e6 - rustc::dep_graph::graph::DepGraph::try_mark_previous_green::h6295c1c4280dcc4e
  21:     0x7f086aa65fe8 - rustc::dep_graph::graph::DepGraph::try_mark_green::h845753c95d5f3009
  22:     0x7f086aa65e3d - rustc::dep_graph::graph::DepGraph::try_mark_green_and_read::h0e32f5abf1d3d304
  23:     0x7f0868facafe - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query::h1445dfb4acbd896f
  24:     0x7f0868e62857 - rustc_typeck::impl_wf_check::impl_wf_check::hceb4b0bb1560cca7
  25:     0x7f0868f7566f - rustc_typeck::check_crate::h867d0fc30a33d36f
  26:     0x7f08688216ff - rustc_interface::passes::analysis::h230237c9cbb3fdb6
  27:     0x7f08685ad707 - rustc::ty::query::__query_compute::analysis::hbc563388fd843223
  28:     0x7f0868615a61 - rustc::dep_graph::graph::DepGraph::with_task_impl::h1cb0f8ed5729c659
  29:     0x7f08685eddaa - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h7e1e949aa0374ae8
  30:     0x7f0868623eb7 - rustc::ty::context::tls::enter_global::hb9491bff2ad90cd2
  31:     0x7f08685f61f4 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hac1bef342f5ec9c4
  32:     0x7f08685a8d5c - std::sys_common::backtrace::__rust_begin_short_backtrace::h6381e44ac7775862
  33:     0x7f0867f596b7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  34:     0x7f08685f81e6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h99e2514ff0276c99
  35:     0x7f0867f2464f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h36e46972b1b7f7b7
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  36:     0x7f0867f57fbd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hdde89c32ce6999de
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  37:     0x7f0867f57fbd - std::sys_common::thread::start_thread::h5ae3fdd4dad03dd5
                               at src/libstd/sys_common/thread.rs:13
  38:     0x7f0867f57fbd - std::sys::unix::thread::Thread::new::thread_start::h76b2403b2434c4c0
                               at src/libstd/sys/unix/thread.rs:80
  39:     0x7f0867cbe6db - start_thread
  40:     0x7f08675db88f - __clone
  41:                0x0 - <unknown>
```

</p>
</details>

# Notes

I have no idea why this happens, but it's slightly urgent since I can't compile my code anymore. You can look at the last few commits, they didn't even touch the `DisplayList` code. rustc seems to panic somewhere around here (?):

https://github.com/maps4print/azul/blob/d6139f0624528c866374b2dc5a41560b35555792/azul-core/src/display_list.rs#L1107-L1110

I'll test again with another rustc version, but I hope I can keep using the stable branch.

**Comment by jonas-schievink** [comment]
Cannot reproduce, presumably an incremental-only bug. You can probably work around it by running `cargo clean -p azul-core` when it happens.

**Comment by fschutt** [comment]
Indeed, after a clean rebuild the issue doesn't happen anymore. I tried reverting to one commit before the HEAD to see if the caching between the builds would trigger the error, still doesn't happen. I'll let you know if it happens again, closing this issue until then. Thanks!
