### ISSUE TITLE
compiler ICE (only on stable 1.41.1)

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#72930]
I got an ice when compiling on stable (1.43.1) on linux 5.6.11-arch1-1. I've pushed the particular code that caused the ICE to https://github.com/derekdreery/druid-material-icons (rev 6b47be9, currently the only commit). Just do `cargo run` to get the error.

There was no ICE on nightly, so feel free to close if this is a known issue.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
error: internal compiler error: src/librustc/ty/sty.rs:1953: `sequence_element_type` called on non-sequence value: [type error]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc::ty::sty::<impl rustc::ty::TyS>::sequence_element_type
  21: rustc_mir_build::build::expr::as_rvalue::<impl rustc_mir_build::build::Builder>::expr_as_rvalue
  22: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  23: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  24: rustc_mir_build::build::expr::as_rvalue::<impl rustc_mir_build::build::Builder>::expr_as_rvalue
  25: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  26: rustc_mir_build::build::expr::as_temp::<impl rustc_mir_build::build::Builder>::expr_as_temp
  27: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::expr_as_operand
  28: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::expr_as_operand
  29: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::as_local_operand
  30: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  31: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  32: rustc_mir_build::build::expr::as_temp::<impl rustc_mir_build::build::Builder>::expr_as_temp
  33: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::expr_as_operand
  34: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::expr_as_operand
  35: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  36: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K, V)>>::from_iter
  37: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  38: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  39: rustc_mir_build::build::block::<impl rustc_mir_build::build::Builder>::ast_block_stmts
  40: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  41: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  42: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::into_expr
  43: rustc_mir_build::build::construct_fn
  44: rustc::ty::context::GlobalCtxt::enter_local
  45: rustc_mir_build::build::mir_built
  46: rustc::ty::query::__query_compute::mir_built
  47: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_built>::compute
  48: rustc::dep_graph::graph::DepGraph::with_task_impl
  49: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  50: rustc_mir::transform::check_unsafety::unsafety_check_result
  51: rustc::ty::query::__query_compute::unsafety_check_result
  52: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::unsafety_check_result>::compute
  53: rustc::dep_graph::graph::DepGraph::with_task_impl
  54: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  55: rustc_mir::transform::mir_const
  56: rustc::ty::query::__query_compute::mir_const
  57: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_const>::compute
  58: rustc::dep_graph::graph::DepGraph::with_task_impl
  59: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  60: rustc_mir::transform::mir_validated
  61: rustc::ty::query::__query_compute::mir_validated
  62: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_validated>::compute
  63: rustc::dep_graph::graph::DepGraph::with_task_impl
  64: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  65: rustc_mir::borrow_check::mir_borrowck
  66: rustc::ty::query::__query_compute::mir_borrowck
  67: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  68: rustc::dep_graph::graph::DepGraph::with_task_impl
  69: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  70: rustc_typeck::collect::type_of::type_of
  71: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::type_of>::compute
  72: rustc::dep_graph::graph::DepGraph::with_task_impl
  73: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  74: rustc::ty::util::<impl rustc::ty::context::TyCtxt>::try_expand_impl_trait_type::OpaqueTypeExpander::expand_opaque_ty
  75: rustc::ty::util::<impl rustc::ty::context::TyCtxt>::try_expand_impl_trait_type
  76: rustc_typeck::check::check_item_type
  77: rustc::hir::map::Map::visit_item_likes_in_module
  78: rustc_typeck::check::check_mod_item_types
  79: rustc::ty::query::__query_compute::check_mod_item_types
  80: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::check_mod_item_types>::compute
  81: rustc::dep_graph::graph::DepGraph::with_task_impl
  82: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  83: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query
  84: rustc_session::utils::<impl rustc_session::session::Session>::time
  85: rustc_typeck::check_crate
  86: rustc_interface::passes::analysis
  87: rustc::ty::query::__query_compute::analysis
  88: rustc::dep_graph::graph::DepGraph::with_task_impl
  89: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  90: rustc::ty::context::tls::enter_global
  91: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.1 (8d69840ab 2020-05-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for
#1 [unsafety_check_result] unsafety-checking `find::find_icons`
#2 [mir_const] processing `find::find_icons`
#3 [mir_validated] processing `find::find_icons`
#4 [mir_borrowck] borrow-checking `find::find_icons`
#5 [type_of] processing `find::find_icons::{{opaque}}#0`
#6 [check_mod_item_types] checking item types in module `find`
#7 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by derekdreery** [comment]
Since this is fixed on nightly I'm gonna close.
