### ISSUE TITLE
ICE: -Zvalidate-mir: broken mir in libcore

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#73109]
### Code

```Rust
fn main() {
	let x = "a".to_string();
  }
```

### Meta

`rustc --version --verbose`:
repo @ 0262de554b4c4c5af346137bbb1664a3f6cf4df2
```
<version>
```

### Error output
`build/x86_64-unknown-linux-gnu/stage2/bin/rustc bad.rs -Zvalidate-mir`
```
error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (input to phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after AddMovesForPackedDrops in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after NoLandingPads in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after RemoveNoopLandingPads in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after SimplifyCfg-make_shim in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after AddCallGuards in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused variable: `x`
 --> ./src/test/ui/issues/issue-29053.rs:4:5
  |
4 | let x = "a".to_string();
  |     ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (input to phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after AddMovesForPackedDrops in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after NoLandingPads in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after RemoveNoopLandingPads in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after SimplifyCfg-make_shim in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: broken MIR in DefId(2:2110 ~ core[13dc]::ops[0]::function[0]::FnOnce[0]::call_once[0]) (after AddCallGuards in phase Const) at bb0[0]:
encountered non-callable type Self in `Call` terminator
   --> /home/matthias/vcs/github/rust/src/libcore/ops/function.rs:232:5
    |
232 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
stack backtrace:
   0:     0x7ff80b84a927 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h76512f7a256472fb
   1:     0x7ff80b8973ed - core::fmt::write::hc64edb3869fa1953
   2:     0x7ff80b838ed5 - std::io::Write::write_fmt::h22c2e31bf0666336
   3:     0x7ff80b826720 - std::panicking::default_hook::{{closure}}::h8f574173d5f96f34
   4:     0x7ff80b826434 - std::panicking::default_hook::h6d7c5c0ca6d5609a
   5:     0x7ff80d1e3063 - rustc_driver::report_ice::h431648ac89c0c7bf
   6:     0x7ff80b826e0c - std::panicking::rust_panic_with_hook::hf2dca5902ecb2b51
   7:     0x7ff81131e02e - std::panicking::begin_panic::hf5fc738ac6374f42
   8:     0x7ff81135661e - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h3bc01279a971299c
   9:     0x7ff80d23ea56 - core::ptr::drop_in_place::h2641e7528eee45ff
  10:     0x7ff80d2475a6 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h324ce0426c1e8578
  11:     0x7ff80d26733d - core::ptr::drop_in_place::hec47fdddd89633e0
  12:     0x7ff80d2591b1 - rustc_span::with_source_map::ha1d5ff3f79f62133
  13:     0x7ff80d1e84b9 - rustc_interface::interface::run_compiler_in_existing_thread_pool::ha05b609632adf0fb
  14:     0x7ff80d1cda8e - scoped_tls::ScopedKey<T>::set::h3583f55ed4da470f
  15:     0x7ff80d1e99e6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8229f831f4f87563
  16:     0x7ff80d1c5dce - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc78b13e1eb35a770
  17:     0x7ff80b82f058 - std::sys::unix::thread::Thread::new::thread_start::heec70046c66b2eb2
  18:     0x7ff80b555422 - start_thread
  19:     0x7ff80b673bf3 - __GI___clone
  20:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z validate-mir

query stack during panic:
end of query stack
```

</p>
</details>

This issue has been assigned to @doctorn via [this comment](https://github.com/rust-lang/rust/issues/73109#issuecomment-641462206).

**Comment by matthiaskrgr** [comment]
This was introduced between 
118b50524b79e565f017e08bce9b90a16c63634f and 0262de554b4c4c5af346137bbb1664a3f6cf4df2

**Comment by matthiaskrgr** [comment]
Might be related to https://github.com/rust-lang/rust/pull/72810 
cc @RalfJung  ?

**Comment by RalfJung** [comment]
Hm... @jonas-schievink suggested to also accept `Self` as callable. I was initially opposed because Miri will ICE when anything but a FnPtr/FnDef is called. But is this even MIR that Miri ever sees? What does the `Self` here normalize to, and is there a method we have to do that normalization?

**Comment by doctorn** [comment]
I'm having a look at this - if it gets too rough I'll be sure to release

@rustbot claim

**Comment by jonas-schievink** [comment]
FYI: I think the solution outlined in https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/-Zvalidate-mir.20errors.20on.20master/near/200033437 is better than just accepting `Self`. The latter is very easy, but the "proper" solution involves changing the shim code, and I don't really know much about how that works.

**Comment by doctorn** [comment]
Checking `Self: FnOnce` seems to work

**Comment by doctorn** [comment]
Papered over by #73175 but @RalfJung explains that this really isn't a proper solution. I'll have a serious look at the shim code this week and see if we can get a more robust solution.

**Comment by RalfJung** [comment]
FWIW, here's the Miri code that would ICE for a `Self` callee:

https://github.com/rust-lang/rust/blob/bb8674837a9cc5225020e07fc3f164762bb4c11c/src/librustc_mir/interpret/terminator.rs#L63

I *think* Miri runs shims as well, so... not sure what happens here.

**Comment by RalfJung** [comment]
But, the thing is, `Self` isn't actually a type. `Self` is more like a type alias. So what is the actual underlying type here? My theory is that it's a `FnDef`/`FnPtr` and that's why Miri does not complain.

**Comment by jonas-schievink** [comment]
I've checked this locally and `Self` is in fact a `TyParam` there (is the type-alias-`Self` even pretty-printed as `Self` instead of the aliased type?). Maybe Miri is applying some substs that replace it with the real type?

**Comment by RalfJung** [comment]
Miri has a subst that monomorphizes everything, yes.
So the problem is that this is generic MIR, and `Self` is later substituted with a `FnDef`/`FnPtr` for codegen/Miri?

**Comment by jonas-schievink** [comment]
That's my current hypothesis, but I haven't verified it yet

**Comment by doctorn** [comment]
That was how I was thinking about it when I wrote the trait bounds check - although I'm really just getting to grips with MIR so it was just an idea

**Comment by doctorn** [comment]
In that case though - isn't a trait bounds check enough given a flag for the MIR validator to disable it when we expect non-generic MIR?

**Comment by RalfJung** [comment]
Maybe... I guess the question is, right now we don't see this happen outside the shims; should we make sure it stays that way?

**Comment by jonas-schievink** [comment]
I've managed to fix the shim creation to avoid `Self`: https://github.com/rust-lang/rust/pull/73359

Not sure that's the best approach, but it seems to work.
