### ISSUE TITLE
Opening files in WASM32-WASI does not work

### ISSUE THREAD

**Issue by AlexEne** [rust-lang/rust#73278]
Hello,

I may just miss-understand how this is supposed to be used, but I cannot find a way to get a simple rust program to open a file in wasm32-wasi (tried a few VMs and at this point I am almost certain the issue sits with the implementation here:
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasi/fs.rs

In the host VM (e.g. for WAMR):
```cpp
const char* dirs[] = {".", "./"};

// This method isn't super documented (what is env?), but I hope this is the correct way to set the dirs.
wasm_runtime_set_wasi_args(module_handle, dirs, 2, nullptr, 0, nullptr, 0, nullptr, 0);

instance = wasm_runtime_instantiate(module_handle, stack_size, heap_size, ...);

// Then i run the main() function with no args.
```

The rust program:
```rs
#[no_mangle]
extern "C" fn main() {
    println!("Hello world!");
    let f = File::open("myfile.txt").unwrap();
}
```

The error I get:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"myfile.txt\" could be opened" }', src/lib.rs:9:13
```

This is generated by [this file](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasi/fs.rs#L629) from rust's libstd.
```rs
        let fd = __wasilibc_find_relpath(p.as_ptr(), &mut ret);
        if fd == -1 {
            let msg = format!(
                "failed to find a preopened file descriptor \
                 through which {:?} could be opened",
                p
            );
            return Err(io::Error::new(io::ErrorKind::Other, msg));
        }
```
I did check that:
1) any other rust programs work just fine (e.g. "Hello world!" is printed).
2) the file is there.
3) I build the VM with wasi support: `set (WAMR_BUILD_LIBC_WASI 1)`

Could the team clarify a few things:
Where is `__wasilibc_find_relpath` function supposed to come from?  
A quick github search doesn't show anything about it. It also does not seem to be a standard WASI method.

WAMR devs suggested in this issue (https://github.com/bytecodealliance/wasm-micro-runtime/issues/278) that `path_open` is the correct method that needs to be called, but I can't seem to make rust stdlib use it even this basic program. 
Is this a bug in rust stdlib's implementation for WASI, am I missing some methods?

### Meta
`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-apple-darwin
release: 1.44.0
LLVM version: 9.0
```

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a preopened file descriptor through which \"myfile.txt\" could be opened" }', src/lib.rs:9:13
```

</p>
</details>

**Comment by AlexEne** [comment]
I did some more investigation, when compiling this program I get different results.

```rust
use std::fs::File;

fn main() {
   println!("Hello world!");
   let f = std::fs::File::open("./myfile.txt").unwrap();
}
```

On OSX with the compiler version mentioned above:
```s
(import "wasi_snapshot_preview1" "path_open" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview19path_open17h9b75b6a14e23237dE (type $t8)))
  (import "wasi_snapshot_preview1" "fd_close" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview18fd_close17hea4f1c40604fd822E (type $t7)))
  (import "wasi_snapshot_preview1" "fd_write" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview18fd_write17h2091a591d4934a86E (type $t9)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $__wasi_proc_exit (type $t0)))
  (import "wasi_snapshot_preview1" "environ_sizes_get" (func $__wasi_environ_sizes_get (type $t2)))
  (import "wasi_snapshot_preview1" "environ_get" (func $__wasi_environ_get (type $t2)))
```


On Windows the imports looks like :

```s
  (import "wasi_snapshot_preview1" "proc_exit" (func $__wasi_proc_exit (type $t1)))
  (import "wasi_snapshot_preview1" "fd_close" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview18fd_close17hdba3f070f61a23f1E (type $t7)))
  (import "wasi_snapshot_preview1" "fd_write" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview18fd_write17h678792b23a3c3a65E (type $t9)))
  (import "wasi_snapshot_preview1" "path_open" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview19path_open17h11daa5ef7c0a6036E (type $t10)))
  (import "wasi_snapshot_preview1" "fd_prestat_get" (func $__wasi_fd_prestat_get (type $t2)))
  (import "wasi_snapshot_preview1" "fd_prestat_dir_name" (func $__wasi_fd_prestat_dir_name (type $t8)))
  (import "wasi_snapshot_preview1" "environ_sizes_get" (func $__wasi_environ_sizes_get (type $t2)))
  (import "wasi_snapshot_preview1" "environ_get" (func $__wasi_environ_get (type $t2)))
```

Windows `rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-pc-windows-msvc
release: 1.44.0
LLVM version: 9.0
```

The missing `fd_prestat_get` and `fd_prestat_dir_name` are the culprits as they are missing on the OSX version (the one where I initially tried).

**Comment by AlexEne** [comment]
I am closing this as @alexcrichton was kind enough to test on his setup and couldn't reproduce the issue so it's likely something on my seide. Will reopen if I find some extra data.
