### ISSUE TITLE
caller_location ICEs in Miri

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#73272]
Some Miri tests, e.g. `./miri run tests/run-pass/panic/catch_panic.rs`, now ICE with
```
thread 'rustc' panicked at 'internal error: entered unreachable code', /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: std::panicking::begin_panic
             at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/panicking.rs:404
  13: rustc_mir::interpret::intrinsics::caller_location::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::find_closest_untracked_caller_location
             at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/macros.rs:13
  14: rustc_mir::interpret::intrinsics::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::emulate_intrinsic
             at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/librustc_mir/interpret/intrinsics.rs:102
  15: miri::shims::intrinsics::EvalContextExt::call_intrinsic
             at src/shims/intrinsics.rs:23
  16: <miri::machine::Evaluator as rustc_mir::interpret::machine::Machine>::call_intrinsic
             at src/machine.rs:365
```
This is a regression introduced by https://github.com/rust-lang/rust/pull/73246. The likely cause is https://github.com/rust-lang/rust/pull/73182.

Cc @Aaron1011 @matthewjasper

**Comment by RalfJung** [comment]
@LeSeulArtichaut I removed "regression from stable" as Miri does not exist on stable.

**Comment by LeSeulArtichaut** [comment]
Sorry, got it.
