### ISSUE TITLE
error: internal compiler error: error during interning should later cause validation failure

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#73327]
### Code

```rust
fn load<R>(_r: R) {}

#[inline(always)]
pub fn load_from_memory_with_format(buf: &[u8]) {
    let b = ::std::io::Cursor::new(buf);
    load(b)
}
```

Compile as library with `-Zmir-opt-level=2`. Reduced from the `image` crate.

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (a37c32e2d 2020-06-11)
binary: rustc
commit-hash: a37c32e2d5fb186627ffe99a391c7fd6fd159334
commit-date: 2020-06-11
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

### Error output

```
error: internal compiler error: error during interning should later cause validation failure
 --> src/lib.rs:6:10
  |
6 |     load(b)
  |          ^

error: internal compiler error: error during interning should later cause validation failure
 --> src/lib.rs:6:5
  |
6 |     load(b)
  |     ^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:366:17
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: std::panicking::begin_panic
  13: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  14: core::ptr::drop_in_place
  15: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  16: core::ptr::drop_in_place
  17: rustc_span::with_source_map
  18: rustc_interface::interface::run_compiler_in_existing_thread_pool
  19: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (a37c32e2d 2020-06-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2 -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `image`.

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by wesleywiser** [comment]
This got fixed by #73130.
