### ISSUE TITLE
Doctest panic line numbers are incorrect

### ISSUE THREAD

**Issue by enterprisey** [rust-lang/rust#73469]
I tried this code:

```rust
/// ```
/// panic!()
/// ```
fn f() {}
```

I expected to see this happen: either

 - `thread 'main' panicked at 'explicit panic', src/lib.rs:2:1`, the actual line of the panic
 - `thread 'main' panicked at 'explicit panic', src/lib.rs:1:1`, the line of the panic inside the doctest

Instead, this happened: `thread 'main' panicked at 'explicit panic', src/lib.rs:3:1`. Why line 3?

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-unknown-linux-gnu
release: 1.44.0
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'explicit panic', src/lib.rs:3:1
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: std::panicking::begin_panic
  12: rust_out::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  16: std::panicking::try
             at src/libstd/panicking.rs:274
  17: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  18: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  19: std::rt::lang_start
  20: main
  21: __libc_start_main
  22: _start
```

</p>
</details>

**Comment by lolbinarycat** [comment]
this would require adding a `#[line]` or similar attribute, which i believe has been rejected before.
