### ISSUE TITLE
cannot create local mono-item for DefId

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/rust#73537]
[Branch `ice` of the Amadeus repo](https://github.com/constellation-rs/amadeus/tree/ice) triggers an ICE. The ICE can be avoided by adding `#[inline(always)]` to the function identified in the error message.

```bash
git clone https://github.com/constellation-rs/amadeus.git
cd amadeus
git checkout ice
cargo +nightly-2020-06-10 test --features "aws"
```

### Meta

With `nightly-2019-10-15` two functions triggered this (see the most recent commit on the `ice` branch). With `nightly-2020-06-10` only one triggers it. My guess is inlining heuristics or similar have changed, making one of the functions inline thus avoiding triggering the ICE?

### Error output

```
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:766: cannot create local mono-item for DefId(112:77 ~ amadeus_aws[d447]::cloudfront[0]::{{impl}}[2]::from_line[0])
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo test --features "aws"
   Compiling amadeus v0.2.0 (/Users/alecmocatta/Documents/deploy/amadeus)
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:766: cannot create local mono-item for DefId(112:77 ~ amadeus_aws[d447]::cloudfront[0]::{{impl}}[2]::from_line[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_errors::HandlerInner::bug
   9: rustc_errors::Handler::bug
  10: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc_middle::ty::context::tls::with_opt::{{closure}}
  12: rustc_middle::ty::context::tls::with_opt
  13: rustc_middle::util::bug::opt_span_bug_fmt
  14: rustc_middle::util::bug::bug_fmt
  15: rustc_mir::monomorphize::collector::should_monomorphize_locally
  16: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator_kind
  17: rustc_mir::monomorphize::collector::collect_neighbours
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_mir::monomorphize::collector::collect_items_rec
  20: rustc_mir::monomorphize::collector::collect_items_rec
  21: rustc_mir::monomorphize::collector::collect_items_rec
  22: rustc_mir::monomorphize::collector::collect_items_rec
  23: rustc_mir::monomorphize::collector::collect_items_rec
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_mir::monomorphize::collector::collect_items_rec
  33: rustc_mir::monomorphize::collector::collect_items_rec
  34: rustc_mir::monomorphize::collector::collect_items_rec
  35: rustc_mir::monomorphize::collector::collect_items_rec
  36: rustc_mir::monomorphize::collector::collect_items_rec
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_items_rec
  41: rustc_mir::monomorphize::collector::collect_items_rec
  42: rustc_mir::monomorphize::collector::collect_items_rec
  43: rustc_mir::monomorphize::collector::collect_items_rec
  44: rustc_mir::monomorphize::collector::collect_items_rec
  45: rustc_mir::monomorphize::collector::collect_items_rec
  46: rustc_mir::monomorphize::collector::collect_items_rec
  47: rustc_mir::monomorphize::collector::collect_items_rec
  48: rustc_mir::monomorphize::collector::collect_items_rec
  49: rustc_mir::monomorphize::collector::collect_items_rec
  50: rustc_mir::monomorphize::collector::collect_items_rec
  51: rustc_mir::monomorphize::collector::collect_items_rec
  52: rustc_mir::monomorphize::collector::collect_items_rec
  53: rustc_mir::monomorphize::collector::collect_items_rec
  54: rustc_mir::monomorphize::collector::collect_items_rec
  55: rustc_mir::monomorphize::collector::collect_items_rec
  56: rustc_mir::monomorphize::collector::collect_items_rec
  57: rustc_mir::monomorphize::collector::collect_items_rec
  58: rustc_mir::monomorphize::collector::collect_items_rec
  59: rustc_mir::monomorphize::collector::collect_items_rec
  60: rustc_mir::monomorphize::collector::collect_items_rec
  61: rustc_mir::monomorphize::collector::collect_items_rec
  62: rustc_mir::monomorphize::collector::collect_items_rec
  63: rustc_mir::monomorphize::collector::collect_items_rec
  64: rustc_mir::monomorphize::collector::collect_items_rec
  65: rustc_mir::monomorphize::collector::collect_items_rec
  66: rustc_mir::monomorphize::collector::collect_items_rec
  67: rustc_mir::monomorphize::collector::collect_items_rec
  68: rustc_mir::monomorphize::collector::collect_items_rec
  69: rustc_mir::monomorphize::collector::collect_items_rec
  70: rustc_mir::monomorphize::collector::collect_items_rec
  71: rustc_mir::monomorphize::collector::collect_items_rec
  72: rustc_mir::monomorphize::collector::collect_items_rec
  73: rustc_mir::monomorphize::collector::collect_items_rec
  74: rustc_mir::monomorphize::collector::collect_items_rec
  75: rustc_mir::monomorphize::collector::collect_items_rec
  76: rustc_mir::monomorphize::collector::collect_items_rec
  77: rustc_mir::monomorphize::collector::collect_items_rec
  78: rustc_mir::monomorphize::collector::collect_items_rec
  79: rustc_mir::monomorphize::collector::collect_items_rec
  80: rustc_mir::monomorphize::collector::collect_items_rec
  81: rustc_mir::monomorphize::collector::collect_items_rec
  82: rustc_mir::monomorphize::collector::collect_items_rec
  83: rustc_mir::monomorphize::collector::collect_items_rec
  84: rustc_mir::monomorphize::collector::collect_items_rec
  85: rustc_mir::monomorphize::collector::collect_items_rec
  86: rustc_mir::monomorphize::collector::collect_items_rec
  87: rustc_mir::monomorphize::collector::collect_items_rec
  88: rustc_mir::monomorphize::collector::collect_items_rec
  89: rustc_mir::monomorphize::collector::collect_items_rec
  90: rustc_mir::monomorphize::collector::collect_items_rec
  91: rustc_mir::monomorphize::collector::collect_items_rec
  92: rustc_mir::monomorphize::collector::collect_items_rec
  93: rustc_mir::monomorphize::collector::collect_items_rec
  94: rustc_mir::monomorphize::collector::collect_items_rec
  95: rustc_mir::monomorphize::collector::collect_items_rec
  96: rustc_mir::monomorphize::collector::collect_items_rec
  97: rustc_mir::monomorphize::collector::collect_items_rec
  98: rustc_mir::monomorphize::collector::collect_items_rec
  99: rustc_mir::monomorphize::collector::collect_items_rec
 100: rustc_mir::monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (feb3536eb 2020-06-09) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error

error: could not compile `amadeus`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:766: cannot create local mono-item for DefId(112:77 ~ amadeus_aws[d447]::cloudfront[0]::{{impl}}[2]::from_line[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_errors::HandlerInner::bug
   9: rustc_errors::Handler::bug
  10: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc_middle::ty::context::tls::with_opt::{{closure}}
  12: rustc_middle::ty::context::tls::with_opt
  13: rustc_middle::util::bug::opt_span_bug_fmt
  14: rustc_middle::util::bug::bug_fmt
  15: rustc_mir::monomorphize::collector::should_monomorphize_locally
  16: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator_kind
  17: rustc_mir::monomorphize::collector::collect_neighbours
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_mir::monomorphize::collector::collect_items_rec
  20: rustc_mir::monomorphize::collector::collect_items_rec
  21: rustc_mir::monomorphize::collector::collect_items_rec
  22: rustc_mir::monomorphize::collector::collect_items_rec
  23: rustc_mir::monomorphize::collector::collect_items_rec
  24: rustc_mir::monomorphize::collector::collect_items_rec
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_mir::monomorphize::collector::collect_items_rec
  33: rustc_mir::monomorphize::collector::collect_items_rec
  34: rustc_mir::monomorphize::collector::collect_items_rec
  35: rustc_mir::monomorphize::collector::collect_items_rec
  36: rustc_mir::monomorphize::collector::collect_items_rec
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_items_rec
  41: rustc_mir::monomorphize::collector::collect_items_rec
  42: rustc_mir::monomorphize::collector::collect_items_rec
  43: rustc_mir::monomorphize::collector::collect_items_rec
  44: rustc_mir::monomorphize::collector::collect_items_rec
  45: rustc_mir::monomorphize::collector::collect_items_rec
  46: rustc_mir::monomorphize::collector::collect_items_rec
  47: rustc_mir::monomorphize::collector::collect_items_rec
  48: rustc_mir::monomorphize::collector::collect_items_rec
  49: rustc_mir::monomorphize::collector::collect_items_rec
  50: rustc_mir::monomorphize::collector::collect_items_rec
  51: rustc_mir::monomorphize::collector::collect_items_rec
  52: rustc_mir::monomorphize::collector::collect_items_rec
  53: rustc_mir::monomorphize::collector::collect_items_rec
  54: rustc_mir::monomorphize::collector::collect_items_rec
  55: rustc_mir::monomorphize::collector::collect_items_rec
  56: rustc_mir::monomorphize::collector::collect_items_rec
  57: rustc_mir::monomorphize::collector::collect_items_rec
  58: rustc_mir::monomorphize::collector::collect_items_rec
  59: rustc_mir::monomorphize::collector::collect_items_rec
  60: rustc_mir::monomorphize::collector::collect_items_rec
  61: rustc_mir::monomorphize::collector::collect_items_rec
  62: rustc_mir::monomorphize::collector::collect_items_rec
  63: rustc_mir::monomorphize::collector::collect_items_rec
  64: rustc_mir::monomorphize::collector::collect_items_rec
  65: rustc_mir::monomorphize::collector::collect_items_rec
  66: rustc_mir::monomorphize::collector::collect_items_rec
  67: rustc_mir::monomorphize::collector::collect_items_rec
  68: rustc_mir::monomorphize::collector::collect_items_rec
  69: rustc_mir::monomorphize::collector::collect_items_rec
  70: rustc_mir::monomorphize::collector::collect_items_rec
  71: rustc_mir::monomorphize::collector::collect_items_rec
  72: rustc_mir::monomorphize::collector::collect_items_rec
  73: rustc_mir::monomorphize::collector::collect_items_rec
  74: rustc_mir::monomorphize::collector::collect_items_rec
  75: rustc_mir::monomorphize::collector::collect_items_rec
  76: rustc_mir::monomorphize::collector::collect_items_rec
  77: rustc_mir::monomorphize::collector::collect_items_rec
  78: rustc_mir::monomorphize::collector::collect_items_rec
  79: rustc_mir::monomorphize::collector::collect_items_rec
  80: rustc_mir::monomorphize::collector::collect_items_rec
  81: rustc_mir::monomorphize::collector::collect_items_rec
  82: rustc_mir::monomorphize::collector::collect_items_rec
  83: rustc_mir::monomorphize::collector::collect_items_rec
  84: rustc_mir::monomorphize::collector::collect_items_rec
  85: rustc_mir::monomorphize::collector::collect_items_rec
  86: rustc_mir::monomorphize::collector::collect_items_rec
  87: rustc_mir::monomorphize::collector::collect_items_rec
  88: rustc_mir::monomorphize::collector::collect_items_rec
  89: rustc_mir::monomorphize::collector::collect_items_rec
  90: rustc_mir::monomorphize::collector::collect_items_rec
  91: rustc_mir::monomorphize::collector::collect_items_rec
  92: rustc_mir::monomorphize::collector::collect_items_rec
  93: rustc_mir::monomorphize::collector::collect_items_rec
  94: rustc_mir::monomorphize::collector::collect_items_rec
  95: rustc_mir::monomorphize::collector::collect_items_rec
  96: rustc_mir::monomorphize::collector::collect_items_rec
  97: rustc_mir::monomorphize::collector::collect_items_rec
  98: rustc_mir::monomorphize::collector::collect_items_rec
  99: rustc_mir::monomorphize::collector::collect_items_rec
 100: rustc_mir::monomorphize::collector::collect_items_rec
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (feb3536eb 2020-06-09) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: aborting due to previous error
```

</p>
</details>

**Comment by LeSeulArtichaut** [comment]
Let’s try to find an MCVE.
@rustbot ping cleanup

**Comment by spastorino** [comment]
Would be nice to find an MCVE and this also seems to be a regression, would be nice to find when this has regressed.

**Comment by spastorino** [comment]
Prioritizing it as `P-critical` for now to raise awareness until we have a better understanding of this. This was discussed briefly on [this Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2373537.20cannot.20create.20local.20mono-item.20for.20DefId).

**Comment by hellow554** [comment]
I was on it, but Amadeus is a *massive* code base and it's not easy to isolate dependencies (especially because `!` needs some improvements in this regards ;) ), but I'll try it again today, to see if there's something.

**Comment by alecmocatta** [comment]
@hellow554 The `could not fully normalize <A as sealed::SimdArray>::Tuple` ICE was fixed by https://github.com/rust-lang/rust/pull/73257. I didn't notice the `delegate` ICE myself.

You're right that as of `nightly-2020-06-20` the `cannot create local mono-item for DefId` ICE isn't reproducing.

As I mentioned I observed two functions triggering it on `2019-10-15`, and only one on `2020-06-10`. Now zero on `2020-06-20`. Either it was fixed or masked some time in those 10 days.

I'll remove the workaround from `master` so I'll notice if any future nightlies re-trigger this and update this issue.

Until then, shall I leave this issue open as the ICE might not have been fixed, just masked, or close it as it's no longer reproducable on current nightly?

**Comment by LeSeulArtichaut** [comment]
I think we will need a test for this anyway.

**Comment by spastorino** [comment]
Lowered to `P-medium`, priority of adding a test for it :).

**Comment by connorskees** [comment]
This one is hard! I've managed to get it down from 50,000 to around 1,200 lines and remove most dependencies (notably, `tokio` and `futures` remain), but it's still very difficult to remove the remaining lines. 

If anyone else wants to try to reduce it further, I've put the repository here:
https://github.com/connorskees/rust-issue-73537


```bash
git clone https://github.com/connorskees/rust-issue-73537
cd rust-issue-73537
cargo +nightly-2020-06-10 test --features "aws"
```

**Comment by hellow554** [comment]
Interesting enough I found a different ICE while trying to minify it further :D

<details>
<summary>Obviously different ICE</summary>

```
error[E0706]: functions in traits cannot be declared `async`
  --> amadeus-core/src/par_stream.rs:62:5
   |
62 |       async fn reduce<P, B, R1F, R1, R3>(
   |       ^----
   |       |
   |  _____`async` because of this
   | |
63 | |         self,
64 | |     ) {
65 | |         let handles = vec![]
66 | |             .into_iter()
67 | |             .map(|tasks| {});
68 | |     }
   | |_____^
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/3503f565e1fb7296983757d2716346f48a4a262b/src/librustc_hir/definitions.rs:316:35
stack backtrace:
   0:     0x7f32261edf05 - backtrace::backtrace::libunwind::trace::h34afbfad7fd770fc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f32261edf05 - backtrace::backtrace::trace_unsynchronized::h460d522b1619a600
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f32261edf05 - std::sys_common::backtrace::_print_fmt::ha45fac10086813b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f32261edf05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde84f63fcfd0e6de
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f322622b49c - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f32261dfd72 - std::io::Write::write_fmt::hc344eafd6e850b4d
                               at src/libstd/io/mod.rs:1537
   6:     0x7f32261f2e30 - std::sys_common::backtrace::_print::h4db88ff15cb5d61d
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f32261f2e30 - std::sys_common::backtrace::print::h5fc39e1b1f610bd3
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f32261f2e30 - std::panicking::default_hook::{{closure}}::h59e55edacb1d974a
                               at src/libstd/panicking.rs:198
   9:     0x7f32261f2b7c - std::panicking::default_hook::heee4c8016dfbf328
                               at src/libstd/panicking.rs:217
  10:     0x7f322695ea73 - rustc_driver::report_ice::h26eb523a40d729cf
  11:     0x7f321bbf7216 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h082305267bbe2157
                               at /rustc/3503f565e1fb7296983757d2716346f48a4a262b/src/liballoc/boxed.rs:1095
  12:     0x7f321bc05fb5 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h93042890da1620b3
                               at /rustc/3503f565e1fb7296983757d2716346f48a4a262b/src/libproc_macro/bridge/client.rs:318
  13:     0x7f32261f35a8 - std::panicking::rust_panic_with_hook::h8405b6301c79fb5a
                               at src/libstd/panicking.rs:524
  14:     0x7f32261f317b - rust_begin_unwind
                               at src/libstd/panicking.rs:431
  15:     0x7f3226228041 - core::panicking::panic_fmt::h78830ea6a34e7206
                               at src/libcore/panicking.rs:85
  16:     0x7f3226227f8d - core::panicking::panic::h68e56c2eeba99c8c
                               at src/libcore/panicking.rs:50
  17:     0x7f3228ee2e18 - rustc_middle::hir::map::Map::def_kind::hafb262fbf0d38c75
  18:     0x7f3228ed701a - core::ops::function::FnOnce::call_once::hf8c5a3a31d68c4c7
  19:     0x7f32293d0bb1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hddf6668a514f1551
  20:     0x7f3228e598dd - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hc013b7ff2582024e
  21:     0x7f3229154952 - rustc_data_structures::stack::ensure_sufficient_stack::h52380575085609a2
  22:     0x7f3228f872aa - rustc_query_system::query::plumbing::get_query_impl::hb3a05b7f5b583756
  23:     0x7f32291c0a80 - rustc_middle::ty::util::<impl rustc_middle::ty::context::TyCtxt>::closure_base_def_id::h17764ecfb292c8f3
  24:     0x7f3227596f30 - rustc_typeck::collect::generics_of::h2d71d824fa4bf7bc
  25:     0x7f3227569c2b - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::generics_of>::compute::h69cce6614aed3c59
  26:     0x7f32273fb043 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h5f4e1d0635b188f7
  27:     0x7f3227511126 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h606eb85f7cd1a802
  28:     0x7f3227544ec9 - rustc_data_structures::stack::ensure_sufficient_stack::h55c904426c20f7fc
  29:     0x7f322745f7d8 - rustc_query_system::query::plumbing::get_query_impl::h57da19642e9c745d
  30:     0x7f32274a4f64 - rustc_query_system::query::plumbing::ensure_query_impl::h94dcd0801933967a
  31:     0x7f32274e9d7f - rustc_hir::intravisit::walk_expr::hf083e7c97404000d
  32:     0x7f3227592bd9 - <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h4760b49ab9b8385b
  33:     0x7f32275845ce - rustc_hir::intravisit::Visitor::visit_stmt::hd7d75fd2d63dd139
  34:     0x7f32274ea23f - rustc_hir::intravisit::walk_expr::hf083e7c97404000d
  35:     0x7f32274e5f8e - rustc_hir::intravisit::walk_body::h56da48f921ac51fb
  36:     0x7f32274d89ae - rustc_hir::intravisit::walk_trait_item::h6dbdc62e387e3321
  37:     0x7f3227592f0d - <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_trait_item::h585101dc821ed179
  38:     0x7f32274fe2b8 - rustc_middle::hir::map::Map::visit_item_likes_in_module::h2fc5c339188d4a79
  39:     0x7f32275907c4 - rustc_typeck::collect::collect_mod_item_types::h14a5b9d007c58603
  40:     0x7f322760a835 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_mod_item_types>::compute::h55f7d1c38c919e5c
  41:     0x7f32273fbad1 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h71d6d4a6cdfbae36
  42:     0x7f3227513f94 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::haf98227a6d0ddc0c
  43:     0x7f32275467a3 - rustc_data_structures::stack::ensure_sufficient_stack::h84406c3b568f39a8
  44:     0x7f32274a16e3 - rustc_query_system::query::plumbing::get_query_impl::hfa21f15e8339624f
  45:     0x7f32274a4aee - rustc_query_system::query::plumbing::ensure_query_impl::h8af3ba1f8784298a
  46:     0x7f322760cd03 - rustc_session::session::Session::track_errors::h33a1cb2fba4e84c5
  47:     0x7f32275a408b - rustc_typeck::check_crate::hd09a544480ba7537
  48:     0x7f3226b001af - rustc_interface::passes::analysis::h3a6008da1c156296
  49:     0x7f322694666b - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute::hae71a7f9d73047a0
  50:     0x7f3226947df8 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h6c2ce8b92f30caac
  51:     0x7f32269bb644 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hfe3c0a8b0dcc9800
  52:     0x7f32269be959 - rustc_data_structures::stack::ensure_sufficient_stack::h80ac0f704de7cdf6
  53:     0x7f3226924644 - rustc_query_system::query::plumbing::get_query_impl::hebe8aa5a8aac99c3
  54:     0x7f3226946b0f - rustc_middle::ty::context::tls::enter_global::h614eb6f235bbc020
  55:     0x7f32269193fa - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hb3ecfe94ca03e6c6
  56:     0x7f32269b9343 - rustc_span::with_source_map::h21eed361cfe861de
  57:     0x7f322691ab16 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h902d0e3e1f552acf
  58:     0x7f32269441bd - scoped_tls::ScopedKey<T>::set::hbc88e7d76dd9a901
  59:     0x7f322696a81a - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f0c30d1296961bc
  60:     0x7f32269275be - core::ops::function::FnOnce::call_once{{vtable.shim}}::h36b2cf3218c61088
  61:     0x7f3226202daa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13d34828db364579
                               at /rustc/3503f565e1fb7296983757d2716346f48a4a262b/src/liballoc/boxed.rs:1081
  62:     0x7f3226202daa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd51b619e0f884abf
                               at /rustc/3503f565e1fb7296983757d2716346f48a4a262b/src/liballoc/boxed.rs:1081
  63:     0x7f3226202daa - std::sys::unix::thread::Thread::new::thread_start::h02c6e34c2c73f344
                               at src/libstd/sys/unix/thread.rs:87
  64:     0x7f322614b432 - start_thread
  65:     0x7f32260679d3 - __clone
  66:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (3503f565e 2020-07-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [def_kind] looking up definition kind of `par_stream::ParallelStream::reduce::{{closure}}#0`
#1 [generics_of] computing generics of `par_stream::ParallelStream::reduce::{{closure}}#0::{{closure}}#0`
#2 [collect_mod_item_types] collecting item types in module `par_stream`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0706`.
error: could not compile `amadeus-core`.

To learn more, run the command again with --verbose.
```

</details>

**Comment by tmiasko** [comment]
Looks like the same issue as #69785, which is already minimized. The use of an
existential type in an associated type position, which happens to reference a
function which isn't otherwise externally reachable. The MIR of the function is
incorrectly omitted, despite the fact it might be referenced externally.

**Comment by oli-obk** [comment]
closing as duplicate
