### ISSUE TITLE
Unexpected panic during compilation

### ISSUE THREAD

**Issue by alethes** [rust-lang/rust#73659]
I occasionally encounter the following error when compiling a large GraphQL server application with `cargo`:
```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `321`,
 right: `829925`', /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x7f1fcfb947e5 - backtrace::backtrace::libunwind::trace::h34afbfad7fd770fc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f1fcfb947e5 - backtrace::backtrace::trace_unsynchronized::h460d522b1619a600
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f1fcfb947e5 - std::sys_common::backtrace::_print_fmt::ha45fac10086813b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f1fcfb947e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde84f63fcfd0e6de
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f1fcfbd1d8c - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f1fcfb86c53 - std::io::Write::write_fmt::hc344eafd6e850b4d
                               at src/libstd/io/mod.rs:1537
   6:     0x7f1fcfb99800 - std::sys_common::backtrace::_print::h4db88ff15cb5d61d
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f1fcfb99800 - std::sys_common::backtrace::print::h5fc39e1b1f610bd3
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f1fcfb99800 - std::panicking::default_hook::{{closure}}::h59e55edacb1d974a
                               at src/libstd/panicking.rs:198
   9:     0x7f1fcfb9954c - std::panicking::default_hook::heee4c8016dfbf328
                               at src/libstd/panicking.rs:217
  10:     0x7f1fd02bc9f3 - rustc_driver::report_ice::h76049a6f226ee6c7
  11:     0x7f1f931e4bf6 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h8b66e73603fbb42f
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/liballoc/boxed.rs:1090
  12:     0x7f1f931da7c5 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h1b578f5f1be49c0f
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/libproc_macro/bridge/client.rs:318
  13:     0x7f1fcfb99eac - std::panicking::rust_panic_with_hook::h8405b6301c79fb5a
                               at src/libstd/panicking.rs:477
  14:     0x7f1fcfb99a8b - rust_begin_unwind
                               at src/libstd/panicking.rs:384
  15:     0x7f1fcfb999fb - std::panicking::begin_panic_fmt::h0ed87aa3b2c392e6
                               at src/libstd/panicking.rs:338
  16:     0x7f1fd0effd00 - rustc_middle::ty::query::on_disk_cache::OnDiskCache::try_load_query_result::hc0a7c4f591afe943
  17:     0x7f1fd0df335c - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::hd1f3d30fb4690ded
  18:     0x7f1fd0e4fe22 - rustc_data_structures::stack::ensure_sufficient_stack::hfc8feab680e4256e
  19:     0x7f1fd0de49b6 - rustc_query_system::query::plumbing::get_query_impl::hf667a765bff71c4e
  20:     0x7f1fd0f5add7 - rustc_typeck::check_unused::check_crate::ha4730e15dde5b776
  21:     0x7f1fd0eacad8 - rustc_typeck::check_crate::h591428c22796cbd0
  22:     0x7f1fd0480d7f - rustc_interface::passes::analysis::h727469a3678584e2
  23:     0x7f1fd02a9122 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute::habcfeb94cac45b7e
  24:     0x7f1fd0296268 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h4b61e28318e39819
  25:     0x7f1fd033a0e4 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h7806ae86a91cb757
  26:     0x7f1fd029d7c3 - rustc_data_structures::stack::ensure_sufficient_stack::h92505c43811de748
  27:     0x7f1fd033515b - rustc_query_system::query::plumbing::get_query_impl::h67eabce2583369d3
  28:     0x7f1fd02a924f - rustc_middle::ty::context::tls::enter_global::h06dbca5f4ea893ff
  29:     0x7f1fd02bfaf4 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hcf417da2db5c1b24
  30:     0x7f1fd0331ac3 - rustc_span::with_source_map::hd51cdb00f1ade542
  31:     0x7f1fd02c15f8 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h48e988b1c838f60a
  32:     0x7f1fd02a739d - scoped_tls::ScopedKey<T>::set::h87c0e807a204a5a9
  33:     0x7f1fd02c2dda - std::sys_common::backtrace::__rust_begin_short_backtrace::hfbb180f8198592d3
  34:     0x7f1fd029e8be - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3e4003c89c3d9855
  35:     0x7f1fcfba969a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13d34828db364579
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/liballoc/boxed.rs:1076
  36:     0x7f1fcfba969a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd51b619e0f884abf
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a/src/liballoc/boxed.rs:1076
  37:     0x7f1fcfba969a - std::sys::unix::thread::Thread::new::thread_start::h02c6e34c2c73f344
                               at src/libstd/sys/unix/thread.rs:87
  38:     0x7f1fcfaf8609 - start_thread
                               at /build/glibc-YYA7BZ/glibc-2.31/nptl/pthread_create.c:477
  39:     0x7f1fcfa0c103 - __clone
  40:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (a8cf39911 2020-06-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [used_trait_imports] used_trait_imports `gen::defaultbool`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `marketplace`.

To learn more, run the command again with --verbose.
```
The project usually compiles fine, but sometimes the compiler panics with that assertion error. The `left` and `right` numeric values vary between the occurrences of the error. Once the error happens, only `cargo clean` followed by a fresh build temporarily resolves the issue. I would appreciate any information on what the reasons behind this problem could be.

**Comment by alethes** [comment]
The issue occurs on both stable and nightly channels. We've noticed it on several Ubuntu computers with both Intel i7 and AMD Ryzen CPUs.

**Comment by TatriX** [comment]
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `^1`,
 right: `^0`', /build/rust/src/rustc-1.46.0-src/src/libstd/macros.rs:16:9
```
Happens very often on my wasm codebase. Can someone help with debugging please?

**Comment by Enselic** [comment]
Triage: Are you still observing this in recent versions of stable/nightly?

**Comment by Enselic** [comment]
Triage: Closing as obsolete.
