### ISSUE TITLE
bench Arc::clone()

### ISSUE THREAD

**Issue by neetdai** [rust-lang/rust#73686]
I tried this code:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
fn criterion_benchmark(c: &mut Criterion) {

    c.bench_function("arf clone", |b| {
        use std::sync::Arc;
        let s: Arc<(String, Option<String>, String)> = Arc::new((String::from("hello"), None, String::from("hello")));

        let test = |s| {};

        b.iter(|| {
            test(s.clone());
        });
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);

```

I expected to see this happen: bench result

Instead, this happened: thread 'main' panicked at 'index out of bounds: the len is 500 but the index is 18446744073709551615'

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-unknown-linux-gnu
release: 1.44.0
LLVM version: 9.0

```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'index out of bounds: the len is 500 but the index is 18446744073709551615', /home/phs/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/criterion-0.3.2/src/plot/plotters_backend/distributions.rs:164:15
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  14: criterion::plot::plotters_backend::distributions::rel_distributions
  15: <criterion::plot::plotters_backend::PlottersBackend as criterion::plot::Plotter>::rel_distributions
  16: <criterion::html::Html as criterion::report::Report>::measurement_complete
  17: <criterion::report::Reports as criterion::report::Report>::measurement_complete
  18: criterion::analysis::common
  19: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
  20: criterion::Criterion<M>::bench_function
  21: bench::main
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  25: std::panicking::try
             at src/libstd/panicking.rs:274
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by jonas-schievink** [comment]
This is not a Rust bug, the panic happens in criterion's libraries.
