### ISSUE TITLE
`rustc` keep crashing while `cargo expand`ing big file

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#73703]
### Code

The code is really big (3k lines & I have no idea how to minimize it.... (though, most of it is a comment)). Here is a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=60ea0401357c0afc121c9c5d6f5e37e6).

(p.s. the code is totally wrong, a was experimenting....)

### Meta

```
rustc 1.46.0-nightly (ff5b446d2 2020-06-23) // playground
rustc 1.46.0-nightly (6bb3dbfc6 2020-06-22) // local
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `2772`,
 right: `1`', src/librustc_ast_pretty/pprust.rs:441:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (ff5b446d2 2020-06-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin
```

<details><summary><strong>Backtrace</strong></summary>
<p>

(I couldn't turn on the backtrace in the playground, so the backtrace is local)
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: rust_begin_unwind
             at src/libstd/panicking.rs:384
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:338
  14: rustc_ast_pretty::pprust::PrintState::print_comment
  15: rustc_ast_pretty::pprust::State::print_stmt
  16: rustc_ast_pretty::pprust::State::print_block_maybe_unclosed
  17: rustc_ast_pretty::pprust::State::print_item
  18: rustc_ast_pretty::pprust::print_crate
  19: rustc_driver::pretty::print_after_hir_lowering::{{closure}}
  20: rustc_driver::pretty::print_after_hir_lowering
  21: rustc_middle::ty::context::tls::enter_global
  22: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  23: rustc_span::with_source_map
  24: rustc_interface::interface::run_compiler_in_existing_thread_pool
  25: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by WaffleLapkin** [comment]
`rustc` doesn't crash on latest nightly (2020-11-30) anymore ([updated code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1932c34ec198726d2becbefe28619101)).
