### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds: the len is xxx but the index is xxx'

### ISSUE THREAD

**Issue by gotoxu** [rust-lang/rust#73859]
When I use rustc to compile the [TiKV](https://github.com/tikv/tikv) project, the compiler reported the following error: 
```shell
thread 'rustc' panicked at 'index out of bounds: the len is 998 but the index is 18791998', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/librustc_hir/definitions.rs:58:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**A detailed description of this problem can be found in this [issue](https://github.com/tikv/tikv/issues/8153).**

The rust toolchain: **nightly-2020-04-23**

<details><summary>Backtrace</summary>

```
** ✘ ⚡ root@db-test-10-101-31-65  ~/tikv   master  RUST_BACKTRACE=1 make build
cargo build --no-default-features --features "jemalloc portable sse protobuf-codec"
   Compiling cdc v0.0.1 (/root/tikv/components/cdc)
   Compiling cmd v0.0.1 (/root/tikv/cmd)
thread 'rustc' panicked at 'index out of bounds: the len is 998 but the index is 18791998', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/librustc_hir/definitions.rs:58:20
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /root/.rustup/toolchains/nightly-2020-04-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1022
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /root/.rustup/toolchains/nightly-2020-04-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  14: rust_begin_unwind
             at src/libstd/panicking.rs:419
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  16: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  17: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::DefId>::to_fingerprint
  18: rustc_query_system::query::plumbing::get_query
  19: rustc_middle::ty::AdtDef::eval_explicit_discr
  20: rustc_middle::ty::sty::<impl rustc_middle::ty::TyS>::discriminant_for_variant
  21: rustc_codegen_ssa::mir::place::PlaceRef<V>::codegen_set_discr
  22: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
  23: rustc_codegen_ssa::mir::codegen_mir
  24: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  25: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  26: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  28: rustc_codegen_llvm::base::compile_codegen_unit
  29: rustc_codegen_ssa::base::codegen_crate
  30: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  31: rustc_session::utils::<impl rustc_session::session::Session>::time
  32: rustc_interface::passes::start_codegen
  33: rustc_middle::ty::context::tls::enter_global
  34: rustc_interface::queries::Queries::ongoing_codegen
  35: rustc_interface::interface::run_compiler_in_existing_thread_pool
  36: scoped_tls::ScopedKey<T>::set
  37: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (b2e36e6c2 2020-04-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -C bitcode-in-rlib=no -C codegen-units=4 -C debuginfo=1 -C overflow-checks=off -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `cdc`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:119: build] Error 101**
```

</details>

**Comment by lzutao** [comment]
Try update to newer rustc version.

**Comment by gotoxu** [comment]
From the current situation, it should be that we upgraded the glibc library of centos7 from 2.17 to 2.18, which caused the problem. Now that we have upgraded glibc to 2.28, the problem disappeared. It is unknown why the 2.18 version of glibc causes this problem.

**Comment by Enselic** [comment]
Triage: Since the OS this is reported on, namely CentOS Linux release 7.8.2003, is no longer maintained, let's close this issue. Feel free to re-open if this can still be reproduced in current operating systems.
