### ISSUE TITLE
Nightly compiler panic after error dump.

### ISSUE THREAD

**Issue by spwilson2** [rust-lang/rust#74049]
### Code

Sorry, I believe the issue stems from error reporting/lifetime checking so creating a MVE would be difficult. I'll sticky the repository + branch until this issue is resolved:

https://gitlab.com/ertos/fdt-rs/-/tree/compiler-bug

### Meta

Error occurs on nightly:

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.46.0-nightly (0cd7ff7dd 2020-07-04)
binary: rustc
commit-hash: 0cd7ff7ddfb75a38dca81ad3e76b1e984129e939
commit-date: 2020-07-04
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

Does **not** reproduce on stable:

```
$ rustc --version --verbose
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build
warning: file found to be present in multiple build targets: /localhome/sean.wilson/projects/fdt-rs/tests/parsing_test.rs
   Compiling fdt-rs v0.2.0 (/localhome/sean.wilson/projects/fdt-rs)
error: cannot find macro `def_common_iter_funcs` in this scope
  --> src/base/iters.rs:75:1
   |
75 | def_common_iter_funcs!($ DevTreeNode<'a, 'dt>, DevTreeProp<'a, 'dt>, DevTreeNodeIter, DevTreePropIter, DevTreeItem);
   | ^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_next_node` in this scope
   --> src/base/iters.rs:113:5
    |
113 |     fn_next_node!(
    |     ^^^^^^^^^^^^

error: cannot find macro `fn_next_node_prop` in this scope
   --> src/base/iters.rs:127:5
    |
127 |     fn_next_node_prop!(
    |     ^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_find_next_compatible_node` in this scope
   --> src/base/iters.rs:132:5
    |
132 |     fn_find_next_compatible_node!(
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `def_common_iter_funcs` in this scope
   --> src/index/iters.rs:111:1
    |
111 | def_common_iter_funcs!($ DevTreeIndexNode<'a, 'i, 'dt>, DevTreeIndexProp<'a, 'i, 'dt>, DevTreeIndexNodeIter, DevTreeIndexPropIter, DevTreeIndexItem);
    | ^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_next_node` in this scope
   --> src/index/iters.rs:121:5
    |
121 |     fn_next_node!(
    |     ^^^^^^^^^^^^

error: cannot find macro `fn_next_prop` in this scope
   --> src/index/iters.rs:125:5
    |
125 |     fn_next_prop!(
    |     ^^^^^^^^^^^^

error: cannot find macro `fn_next_node_prop` in this scope
   --> src/index/iters.rs:130:5
    |
130 |     fn_next_node_prop!(
    |     ^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_find_next_compatible_node` in this scope
   --> src/index/iters.rs:134:5
    |
134 |     fn_find_next_compatible_node!(
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `find_next_compatible_node` found for struct `base::iters::DevTreeIter<'a, 'dt>` in the current scope
  --> src/base/node.rs:53:25
   |
53 |         self.parse_iter.find_next_compatible_node(string)
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `base::iters::DevTreeIter<'a, 'dt>`
   | 
  ::: src/base/iters.rs:61:1
   |
61 | pub struct DevTreeIter<'a, 'dt:'a> {
   | ---------------------------------- method `find_next_compatible_node` not found for this

error[E0599]: no method named `next_node` found for struct `base::iters::DevTreeIter<'_, '_>` in the current scope
  --> src/base/prop.rs:36:34
   |
36 |         self.parent_iter.clone().next_node().unwrap()
   |                                  ^^^^^^^^^ method not found in `base::iters::DevTreeIter<'_, '_>`
   | 
  ::: src/base/iters.rs:61:1
   |
61 | pub struct DevTreeIter<'a, 'dt:'a> {
   | ---------------------------------- method `next_node` not found for this

error[E0599]: no method named `find_next_compatible_node` found for struct `base::iters::DevTreeIter<'_, '_>` in the current scope
   --> src/base/tree.rs:211:22
    |
211 |         self.items().find_next_compatible_node(string)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `base::iters::DevTreeIter<'_, '_>`
    | 
   ::: src/base/iters.rs:61:1
    |
61  | pub struct DevTreeIter<'a, 'dt:'a> {
    | ---------------------------------- method `find_next_compatible_node` not found for this

error: internal compiler error: src/librustc_typeck/collect/type_of.rs:51: associated type missing default
  --> src/base/iter_macro.rs:18:5
   |
18 |     type TreeProp;
   |     ^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/macros.rs:13:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /localhome/sean.wilson/.rustup/toolchains/nightly-2020-05-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1048
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /localhome/sean.wilson/.rustup/toolchains/nightly-2020-05-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:312
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  14: std::panicking::begin_panic
  15: rustc_errors::HandlerInner::span_bug
  16: rustc_errors::Handler::span_bug
  17: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  18: rustc_middle::ty::context::tls::with_opt::{{closure}}
  19: rustc_middle::ty::context::tls::with_opt
  20: rustc_middle::util::bug::opt_span_bug_fmt
  21: rustc_middle::util::bug::span_bug_fmt
  22: rustc_typeck::collect::type_of::type_of
  23: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_middle::ty::error::<impl rustc_middle::ty::context::TyCtxt>::note_and_explain_type_err
  28: rustc_infer::infer::error_reporting::<impl rustc_infer::infer::InferCtxt>::note_type_err
  29: rustc_infer::infer::error_reporting::<impl rustc_infer::infer::InferCtxt>::report_and_explain_type_error
  30: rustc_infer::infer::InferCtxt::report_mismatched_types
  31: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt>::demand_eqtype_with_origin
  32: rustc_typeck::check::pat::<impl rustc_typeck::check::FnCtxt>::check_pat
  33: rustc_typeck::check::check_fn
  34: rustc_middle::ty::context::GlobalCtxt::enter_local
  35: rustc_typeck::check::typeck_tables_of
  36: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_tables_of>::compute
  37: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_query_system::query::plumbing::get_query_impl
  40: rustc_query_system::query::plumbing::ensure_query_impl
  41: rustc_typeck::check::typeck_item_bodies
  42: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  43: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  44: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  45: rustc_query_system::query::plumbing::get_query_impl
  46: rustc_typeck::check_crate
  47: rustc_interface::passes::analysis
  48: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  49: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  50: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  51: rustc_data_structures::stack::ensure_sufficient_stack
  52: rustc_query_system::query::plumbing::get_query_impl
  53: rustc_middle::ty::context::tls::enter_global
  54: rustc_interface::interface::run_compiler_in_existing_thread_pool
  55: scoped_tls::ScopedKey<T>::set
  56: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (a74d1862d 2020-05-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_of] processing `base::iter_macro::ItemIterator::TreeProp`
#1 [typeck_tables_of] type-checking `base::iter_macro::ItemIterator::next_prop`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 13 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `fdt-rs`.

To learn more, run the command again with --verbose.
=
```

</p>
</details>

**Comment by LeSeulArtichaut** [comment]
Let’s bisect this and try to find an MCVE.
@rustbot ping cleanup

**Comment by hellow554** [comment]
Can't reproduce the ICE on the specified nightly with your repo. I'll get an error, but no ICE:

<details>
<summary>Error backtrace</summary>

```
warning: file found to be present in multiple build targets: /tmp/tmp.SnVAq2F49X/fdt-rs/tests/parsing_test.rs
   Compiling fdt-rs v0.2.0 (/tmp/tmp.SnVAq2F49X/fdt-rs)
error: cannot find macro `def_common_iter_funcs` in this scope
  --> src/base/iters.rs:75:1
   |
75 | def_common_iter_funcs!($ DevTreeNode<'a, 'dt>, DevTreeProp<'a, 'dt>, DevTreeNodeIter, DevTreePropIter, DevTreeItem);
   | ^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_next_node` in this scope
   --> src/base/iters.rs:113:5
    |
113 |     fn_next_node!(
    |     ^^^^^^^^^^^^

error: cannot find macro `fn_next_node_prop` in this scope
   --> src/base/iters.rs:127:5
    |
127 |     fn_next_node_prop!(
    |     ^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_find_next_compatible_node` in this scope
   --> src/base/iters.rs:132:5
    |
132 |     fn_find_next_compatible_node!(
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `def_common_iter_funcs` in this scope
   --> src/index/iters.rs:111:1
    |
111 | def_common_iter_funcs!($ DevTreeIndexNode<'a, 'i, 'dt>, DevTreeIndexProp<'a, 'i, 'dt>, DevTreeIndexNodeIter, DevTreeIndexPropIter, DevTre...
    | ^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_next_node` in this scope
   --> src/index/iters.rs:121:5
    |
121 |     fn_next_node!(
    |     ^^^^^^^^^^^^

error: cannot find macro `fn_next_prop` in this scope
   --> src/index/iters.rs:125:5
    |
125 |     fn_next_prop!(
    |     ^^^^^^^^^^^^

error: cannot find macro `fn_next_node_prop` in this scope
   --> src/index/iters.rs:130:5
    |
130 |     fn_next_node_prop!(
    |     ^^^^^^^^^^^^^^^^^

error: cannot find macro `fn_find_next_compatible_node` in this scope
   --> src/index/iters.rs:134:5
    |
134 |     fn_find_next_compatible_node!(
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `find_next_compatible_node` found for struct `base::iters::DevTreeIter<'a, 'dt>` in the current scope
  --> src/base/node.rs:53:25
   |
53 |         self.parse_iter.find_next_compatible_node(string)
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `base::iters::DevTreeIter<'a, 'dt>`
   |
  ::: src/base/iters.rs:61:1
   |
61 | pub struct DevTreeIter<'a, 'dt:'a> {
   | ---------------------------------- method `find_next_compatible_node` not found for this

error[E0599]: no method named `next_node` found for struct `base::iters::DevTreeIter<'_, '_>` in the current scope
  --> src/base/prop.rs:36:34
   |
36 |         self.parent_iter.clone().next_node().unwrap()
   |                                  ^^^^^^^^^ method not found in `base::iters::DevTreeIter<'_, '_>`
   |
  ::: src/base/iters.rs:61:1
   |
61 | pub struct DevTreeIter<'a, 'dt:'a> {
   | ---------------------------------- method `next_node` not found for this

error[E0599]: no method named `find_next_compatible_node` found for struct `base::iters::DevTreeIter<'_, '_>` in the current scope
   --> src/base/tree.rs:211:22
    |
211 |         self.items().find_next_compatible_node(string)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `base::iters::DevTreeIter<'_, '_>`
    |
   ::: src/base/iters.rs:61:1
    |
61  | pub struct DevTreeIter<'a, 'dt:'a> {
    | ---------------------------------- method `find_next_compatible_node` not found for this

error[E0308]: mismatched types
  --> src/base/iter_macro.rs:22:18
   |
22 |     fn next_prop(&mut iter: Self::TreeItem) -> Option<Self::TreeProp> {
   |                  ^^^^^^^^^-----------------
   |                  |          |
   |                  |          expected due to this
   |                  expected associated type, found `&mut _`
   |                  help: did you mean `iter`: `&<Self as base::iter_macro::ItemIterator>::TreeItem`
   |
   = note: expected associated type `<Self as base::iter_macro::ItemIterator>::TreeItem`
            found mutable reference `&mut _`
   = help: consider constraining the associated type `<Self as base::iter_macro::ItemIterator>::TreeItem` to `&mut _` or calling a method that returns `<Self as base::iter_macro::ItemIterator>::TreeItem`
   = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html

error[E0599]: no method named `next_node` found for struct `base::iters::DevTreeIter<'a, 'dt>` in the current scope
   --> src/base/iters.rs:191:16
    |
61  | pub struct DevTreeIter<'a, 'dt:'a> {
    | ---------------------------------- method `next_node` not found for this
...
191 |         self.0.next_node()
    |                ^^^^^^^^^ method not found in `base::iters::DevTreeIter<'a, 'dt>`

error[E0599]: no method named `next_node_prop` found for struct `base::iters::DevTreeIter<'a, 'dt>` in the current scope
   --> src/base/iters.rs:231:16
    |
61  | pub struct DevTreeIter<'a, 'dt:'a> {
    | ---------------------------------- method `next_node_prop` not found for this
...
231 |         self.0.next_node_prop()
    |                ^^^^^^^^^^^^^^ method not found in `base::iters::DevTreeIter<'a, 'dt>`

error[E0599]: no method named `find_next_compatible_node` found for struct `index::iters::DevTreeIndexIter<'_, '_, '_>` in the current scope
   --> src/index/tree.rs:347:22
    |
347 |         self.items().find_next_compatible_node(string)
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `index::iters::DevTreeIndexIter<'_, '_, '_>`
    |
   ::: src/index/iters.rs:104:1
    |
104 | pub struct DevTreeIndexIter<'a, 'i: 'a, 'dt: 'i> {
    | ------------------------------------------------ method `find_next_compatible_node` not found for this

error[E0599]: no method named `next_node` found for struct `index::iters::DevTreeIndexIter<'a, 'i, 'dt>` in the current scope
   --> src/index/iters.rs:26:16
    |
26  |         self.0.next_node()
    |                ^^^^^^^^^ method not found in `index::iters::DevTreeIndexIter<'a, 'i, 'dt>`
...
104 | pub struct DevTreeIndexIter<'a, 'i: 'a, 'dt: 'i> {
    | ------------------------------------------------ method `next_node` not found for this

error[E0599]: no method named `next_node_prop` found for struct `index::iters::DevTreeIndexIter<'a, 'i, 'dt>` in the current scope
   --> src/index/iters.rs:72:16
    |
72  |         self.0.next_node_prop()
    |                ^^^^^^^^^^^^^^ method not found in `index::iters::DevTreeIndexIter<'a, 'i, 'dt>`
...
104 | pub struct DevTreeIndexIter<'a, 'i: 'a, 'dt: 'i> {
    | ------------------------------------------------ method `next_node_prop` not found for this

error[E0599]: no method named `next_prop` found for struct `index::iters::DevTreeIndexIter<'a, 'i, 'dt>` in the current scope
   --> src/index/iters.rs:95:16
    |
95  |         self.0.next_prop()
    |                ^^^^^^^^^ method not found in `index::iters::DevTreeIndexIter<'a, 'i, 'dt>`
...
104 | pub struct DevTreeIndexIter<'a, 'i: 'a, 'dt: 'i> {
    | ------------------------------------------------ method `next_prop` not found for this
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `base::iter_macro::ItemIterator` defines an item `next_prop`, perhaps you need to implement it
   --> src/base/iter_macro.rs:17:1
    |
17  | pub trait ItemIterator {
    | ^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::prelude`
 --> src/index/iters.rs:1:5
  |
1 | use crate::prelude::*;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to 19 previous errors; 1 warning emitted

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `fdt-rs`.

To learn more, run the command again with --verbose.
```

</details>

**Comment by spwilson2** [comment]
It looks like for some reason my environment was printing a different rustc version than it used to compile this crate. See from my backtrace:
```
 12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /localhome/sean.wilson/.rustup/toolchains/nightly-2020-05-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:312
 ```

This looks like a reproduction of https://github.com/rust-lang/rust/issues/72076

I'm no longer able to reproduce this issue with the current nightly compiler. Sorry for the disruptive bug report.
