### ISSUE TITLE
rustc debug panic `Panic index out of bounds running` on linux

### ISSUE THREAD

**Issue by yorkart** [rust-lang/rust#74092]
CentOS7.3 : relase is OK, debug Panic.
MacOS:  debug and release is OK.

build command
```rust
RUST_BACKTRACE=1 cargo build --color=always --all --all-targets
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 13 but the index is 4294967295', src/librustc_span/hygiene.rs:203:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  15: rustc_span::hygiene::HygieneData::adjust
  16: scoped_tls::ScopedKey<T>::with
  17: rustc_span::hygiene::SyntaxContext::hygienic_eq
  18: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::hygienic_eq
  19: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  20: rustc_middle::ty::sty::ProjectionTy::from_ref_and_name
  21: rustc_trait_selection::traits::project::confirm_callable_candidate
  22: rustc_trait_selection::traits::project::opt_normalize_projection_type
  23: rustc_trait_selection::traits::project::normalize_projection_type
  24: rustc_middle::ty::context::GlobalCtxt::enter_local
  25: rustc_traits::normalize_projection_ty::normalize_projection_ty
  26: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::normalize_projection_ty>::compute
  27: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  28: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  29: rustc_query_system::query::plumbing::get_query
  30: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  31: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize
  32: rustc_middle::ty::context::GlobalCtxt::enter_local
  33: rustc_traits::normalize_erasing_regions::normalize_generic_arg_after_erasing_regions
  34: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::normalize_generic_arg_after_erasing_regions>::compute
  35: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  36: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  37: rustc_query_system::query::plumbing::get_query
  38: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  39: rustc_middle::ty::structural_impls::fold_list
  40: rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_late_bound_regions
  41: <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_middle::ty::layout::FnAbiExt<C>>::of_instance
  42: rustc_codegen_llvm::callee::get_fn
  43: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
  44: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  45: rustc_codegen_ssa::meth::get_vtable
  46: rustc_codegen_ssa::base::unsize_thin_ptr
  47: rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue_operand
  48: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block
  49: rustc_codegen_ssa::mir::codegen_mir
  50: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
  51: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  52: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  53: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  54: rustc_codegen_llvm::base::compile_codegen_unit
  55: rustc_codegen_ssa::base::codegen_crate
  56: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  57: rustc_session::utils::<impl rustc_session::session::Session>::time
  58: rustc_interface::passes::start_codegen
  59: rustc_middle::ty::context::tls::enter_global
  60: rustc_interface::queries::Queries::ongoing_codegen
  61: rustc_interface::interface::run_compiler_in_existing_thread_pool
  62: scoped_tls::ScopedKey<T>::set
  63: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.1 (c7087fe00 2020-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'already borrowed: BorrowMutError', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/cell.rs:878:9
stack backtrace:
   0:     0x7ff04dc1fab4 - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7ff04dc1fab4 - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7ff04dc1fab4 - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7ff04dc1fab4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7ff04dc5dbac - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x7ff04dc114d3 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x7ff04dc24ab5 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7ff04dc24ab5 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7ff04dc24ab5 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x7ff04dc247f2 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x7ff04e1c1923 - rustc_driver::report_ice::h303988fb5b9997d4
  11:     0x7ff04dc25235 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:515
  12:     0x7ff04dc24d4b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  13:     0x7ff04dc5a841 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  14:     0x7ff04dc5a4b3 - core::option::expect_none_failed::hb01994a49b20448c
                               at src/libcore/option.rs:1268
  15:     0x7ff0509d9988 - scoped_tls::ScopedKey<T>::with::he9061b34532376b2
  16:     0x7ff0509b718a - <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h1aa07cc2fd3a77cc
  17:     0x7ff0509b9a3c - rustc_errors::emitter::Emitter::fix_multispans_in_extern_macros_and_render_macro_backtrace::h401ee134e1ddc8fa
  18:     0x7ff0509bab5e - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic::h61639635a6f27438
  19:     0x7ff0509e7159 - rustc_errors::Handler::force_print_diagnostic::hc2d41d993b3ba92f
  20:     0x7ff05044c660 - rustc_middle::ty::query::plumbing::<impl rustc_middle::ty::context::TyCtxt>::try_print_query_stack::h50e7eccfbd010213
  21:     0x7ff04e1c26c4 - rustc_driver::report_ice::h303988fb5b9997d4
  22:     0x7ff04dc25235 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:515
  23:     0x7ff04dc24d4b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  24:     0x7ff04dc5a841 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  25:     0x7ff04dc5a802 - core::panicking::panic_bounds_check::h4b3d0dcda831e378
                               at src/libcore/panicking.rs:69
  26:     0x7ff050b7d58e - rustc_span::hygiene::HygieneData::adjust::h508b4f03e611c975
  27:     0x7ff050b8529c - scoped_tls::ScopedKey<T>::with::hbb7317439b770f45
  28:     0x7ff050b7e06f - rustc_span::hygiene::SyntaxContext::hygienic_eq::h6cba83a1b001d29f
  29:     0x7ff050473091 - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::hygienic_eq::hfb7673db15e06b0d
  30:     0x7ff050672460 - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h2564fe0e0bdf2ed8
  31:     0x7ff050294eca - rustc_middle::ty::sty::ProjectionTy::from_ref_and_name::h2798a8483e3ae977
  32:     0x7ff0500af699 - rustc_trait_selection::traits::project::confirm_callable_candidate::hf46dd2343d1481b2
  33:     0x7ff0500ada97 - rustc_trait_selection::traits::project::opt_normalize_projection_type::hc1464d6abc7657d2
  34:     0x7ff0500ab736 - rustc_trait_selection::traits::project::normalize_projection_type::h5836f408fa55147a
  35:     0x7ff04e8ce7d9 - rustc_middle::ty::context::GlobalCtxt::enter_local::h8d882757cc247279
  36:     0x7ff04e90ac46 - rustc_traits::normalize_projection_ty::normalize_projection_ty::h932d838242450a80
  37:     0x7ff0500482cf - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::normalize_projection_ty>::compute::h62de4dca30a43537
  38:     0x7ff0500241cd - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h659afff68d85061f
  39:     0x7ff04ff0fdee - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::ha2da78a0c27b3cbe
  40:     0x7ff050088418 - rustc_query_system::query::plumbing::get_query::hf91b10edce48dea6
  41:     0x7ff050044a6a - <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty::h2de7babe743f81b3
  42:     0x7ff04e93130b - <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize::h1e3dab83141d39b1
  43:     0x7ff04e8ca407 - rustc_middle::ty::context::GlobalCtxt::enter_local::h0393857d324ac8a5
  44:     0x7ff04e90ab95 - rustc_traits::normalize_erasing_regions::normalize_generic_arg_after_erasing_regions::h4065646363864fb5
  45:     0x7ff05084cd1d - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::normalize_generic_arg_after_erasing_regions>::compute::h2c6f697827f36556
  46:     0x7ff05043326f - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hc2afa9ec1fbc9a68
  47:     0x7ff0506197da - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h5ea32329a8673ba4
  48:     0x7ff0507ded77 - rustc_query_system::query::plumbing::get_query::h1f09847ad1321b57
  49:     0x7ff0505e1ec7 - <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty::h1e71f49caf456c9c
  50:     0x7ff04e65914c - rustc_middle::ty::structural_impls::fold_list::hcbdb99cf0f050f2e
  51:     0x7ff04e5c71bc - rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_late_bound_regions::h85516c4d9ca5345f
  52:     0x7ff04e737955 - <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_middle::ty::layout::FnAbiExt<C>>::of_instance::h60e8125d6a2e5e54
  53:     0x7ff04e75b88f - rustc_codegen_llvm::callee::get_fn::h6032c9f29e3bc43e
  54:     0x7ff04e6aa2f3 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold::ha34e3e6f73e4b40e
  55:     0x7ff04e710e25 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h2b1f7b4df52c0fac
  56:     0x7ff04e73eb99 - rustc_codegen_ssa::meth::get_vtable::hf9cdd34d25c98f48
  57:     0x7ff04e72359c - rustc_codegen_ssa::base::unsize_thin_ptr::h72a68a24e3332ff0
  58:     0x7ff04e6eb428 - rustc_codegen_ssa::mir::rvalue::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_rvalue_operand::ha8d445d45398b20b
  59:     0x7ff04e6df286 - rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block::hb184e88ef5b6ee88
  60:     0x7ff04e6ddcbe - rustc_codegen_ssa::mir::codegen_mir::h6478bade6b4d2be7
  61:     0x7ff04e66e35c - <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define::hb0edc2887e27afbc
  62:     0x7ff04e5e276a - rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::hb005e2a52aa0d677
  63:     0x7ff04e5cbcf9 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h720fb68b17b5bdde
  64:     0x7ff04e656e89 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::hfbaee293aded9443
  65:     0x7ff04e5e233c - rustc_codegen_llvm::base::compile_codegen_unit::h59b28a37172b4d15
  66:     0x7ff04e7221db - rustc_codegen_ssa::base::codegen_crate::hc413f056d4aa3962
  67:     0x7ff04e6a8185 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h3ba007dcc6abf3ad
  68:     0x7ff04e4b0cd0 - rustc_session::utils::<impl rustc_session::session::Session>::time::h0d8d5e007e529c37
  69:     0x7ff04e517337 - rustc_interface::passes::start_codegen::h0de1a7c5cab291e8
  70:     0x7ff04e462d69 - rustc_middle::ty::context::tls::enter_global::h002e7a569421dba6
  71:     0x7ff04e5696a6 - rustc_interface::queries::Queries::ongoing_codegen::h3524bcd51fd0ff5e
  72:     0x7ff04e317da6 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h1fe14dfeda5e7ff8
  73:     0x7ff04e1cb52d - scoped_tls::ScopedKey<T>::set::h7ef5c845735c44d5
  74:     0x7ff04e1c83d4 - rustc_ast::attr::with_globals::h80403999168944fb
  75:     0x7ff04e1d3a92 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65e906f83ddca1d2
  76:     0x7ff04e31b40e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4a7aeea8942a4e2c
  77:     0x7ff04dc352aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf207c3654ee300a0
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  78:     0x7ff04dc352aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h66e0c6190e34816b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  79:     0x7ff04dc352aa - std::sys::unix::thread::Thread::new::thread_start::h30687bc0b1c3cd55
                               at src/libstd/sys/unix/thread.rs:87
  80:     0x7ff04d99b1b3 - start_thread
                               at /root/glibc-2.18/nptl/pthread_create.c:309
  81:     0x7ff04d2c1fed - __clone
                               at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
  82:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.1 (c7087fe00 2020-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
```

</p>
</details>

**Comment by NieDzejkob** [comment]
Thanks for the report. Could you provide us with the code that causes this error?

**Comment by hellow554** [comment]
Hey @yorkart 
To help you with this problem (and fix the compiler crash) we need the code that leads to this error. Can you provide it to us?
