### ISSUE TITLE
Internal compiler error when running with `entr -r cargo run`

### ISSUE THREAD

**Issue by mortie** [rust-lang/rust#74164]
When I run a long-running process using `entr -r cargo run` (where `entr` is http://eradman.com/entrproject/), the compiler dies with an internal compiler error. I don't know what's special with how entr runs cargo compared to how it's normally run.

### Code

```Rust
fn main() {
    println!("Hello World");
    std::thread::sleep(std::time::Duration::from_secs(10));
}
```

### Meta

`rustc --version --verbose`:

```
rustc 1.40.0 (73528e339 2019-12-16)
binary: rustc
commit-hash: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
commit-date: 2019-12-16
host: x86_64-unknown-linux-gnu
release: 1.40.0
LLVM version: 9.0
```

### Error output

```
martin@ubun /tmp/martin.tmp.FAjPzdkv $ find src | entr -r cargo run
   Compiling tmp v0.1.0 (/tmp/martin.tmp.FAjPzdkv)
thread '<unnamed>' panicked at 'failed to acquire jobserver token: early EOF on jobserver pipe', src/librustc_codegen_ss
a/back/write.rs:1401:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.40.0 (73528e339 2019-12-16) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin
note: some of the compiler flags provided by cargo are hidden
error: failed to acquire jobserver token: early EOF on jobserver pipe
error: aborting due to previous error
error: could not compile `tmp`.
To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
martin@ubun /tmp/martin.tmp.FAjPzdkv $ find src | RUST_BACKTRACE=1 entr -r cargo run --verbose
   Compiling tmp v0.1.0 (/tmp/martin.tmp.FAjPzdkv)
     Running `rustc --edition=2018 --crate-name tmp src/main.rs --error-format=json --json=diagnostic-rendered-ansi --cr
ate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=c21f1704f6025fec -C extra-filename=-c21f1704f6025fec --out-
dir /tmp/martin.tmp.FAjPzdkv/target/debug/deps -C incremental=/tmp/martin.tmp.FAjPzdkv/target/debug/incremental -L depen
dency=/tmp/martin.tmp.FAjPzdkv/target/debug/deps`
thread '<unnamed>' panicked at 'failed to acquire jobserver token: early EOF on jobserver pipe', src/librustc_codegen_ss
a/back/write.rs:1401:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  14: rustc_codegen_ssa::back::write::start_executing_work::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.40.0 (73528e339 2019-12-16) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: failed to acquire jobserver token: early EOF on jobserver pipe
error: aborting due to previous error
error: could not compile `tmp`.
Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name tmp src/main.rs --error-format=json --json=diagno
stic-rendered-ansi --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=c21f1704f6025fec -C extra-filename=-
c21f1704f6025fec --out-dir /tmp/martin.tmp.FAjPzdkv/target/debug/deps -C incremental=/tmp/martin.tmp.FAjPzdkv/target/deb
ug/incremental -L dependency=/tmp/martin.tmp.FAjPzdkv/target/debug/deps` (exit code: 1)
```

</p>
</details>

**Comment by NieDzejkob** [comment]
The version you're using seems to be a nightly from half a year ago. I tried reproducing this bug on both stable 1.40 and 1.44 and couldn't, though the instructions are somewhat unclear and I might be doing something slightly different than you.

As such, could you try updating? If the bug persists, could you expand on how you're triggering it? Is it intermittent? Do you save while the 10-second sleep is in progress, or after it runs out? What editor are you using?

**Comment by mortie** [comment]
Aha, I installed it through rustup once and didn't think more about it. I removed the version from rustup now, instead using the version from my distro's repositories (rustc 1.41.0), and now it works.
