### ISSUE TITLE
internal compiler error: src/librustc_middle/ty/query/mod.rs:105:1: `tcx.dep_kind(crate0)` unsupported by its crate

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#74258]
### Reproduction steps

I have no idea. Originally this happened from rebasing https://github.com/rust-lang/rust/pull/73964/commits/bfed9303c8d508f6885c4e03e0bee43c9051c4fe over https://github.com/rust-lang/rust/commit/daecab3a784f28082df90cebb204998051f3557d, but I had lots of strange changes to x.py in the meantime, so I doubt that alone will replicate the build state. However the panic happens consistently, so I can upload a zip of the build directory if someone knows a place to host 10 GB of binary artifacts.

### Meta

This is using a stage1 build of rustc. I think the cache may possibly not have been invalidated?

### Error output

```
$ xpy test --doc src/tools/rustdoc --stage 1 -j1
Updating only changed submodules
Submodules updated in 0.01 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.11s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.12s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.11s
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc_graphviz v0.0.0 (/home/joshua/src/rustc2/src/librustc_graphviz)
error: internal compiler error: src/librustc_middle/ty/query/mod.rs:105:1: `tcx.dep_kind(crate0)` unsupported by its crate

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:916:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=8 -C debuginfo=1 -C debug-assertions=on -C overflow-checks=off -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `rustc_graphviz`.

To learn more, run the command again with --verbose.
command did not execute successfully: "/home/joshua/src/rustc2/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "1" "--release" "--features" " llvm" "--manifest-path" "/home/joshua/src/rustc2/src/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /home/joshua/src/rustc2/build/bootstrap/debug/bootstrap test --doc src/tools/rustdoc --stage 1 -j1
Build completed unsuccessfully in 0:00:00
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_middle/ty/query/mod.rs:105:1: `tcx.dep_kind(crate0)` unsupported by its crate

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:916:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at ./src/liballoc/boxed.rs:1095
  11: rustc_driver::report_ice
             at src/librustc_driver/lib.rs:1161
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  13: std::panicking::begin_panic
             at ./src/libstd/panicking.rs:456
  14: rustc_errors::HandlerInner::bug
             at src/librustc_errors/lib.rs:916
  15: rustc_errors::Handler::bug
             at src/librustc_errors/lib.rs:666
  16: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
             at src/librustc_middle/util/bug.rs:33
  17: rustc_middle::ty::context::tls::with_opt::{{closure}}
             at src/librustc_middle/ty/context.rs:1819
  18: rustc_middle::ty::context::tls::with_context_opt
             at src/librustc_middle/ty/context.rs:1771
  19: rustc_middle::ty::context::tls::with_opt
             at src/librustc_middle/ty/context.rs:1819
  20: rustc_middle::util::bug::opt_span_bug_fmt
             at src/librustc_middle/util/bug.rs:29
  21: rustc_middle::util::bug::bug_fmt
             at src/librustc_middle/util/bug.rs:14
  22: <rustc_middle::ty::query::Providers as core::default::Default>::default::dep_kind
             at src/librustc_middle/ty/query/plumbing.rs:571
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::{{closure}}
             at ./src/librustc_query_system/dep_graph/graph.rs:249
  24: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::{{closure}}
             at src/librustc_middle/dep_graph/mod.rs:71
  25: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at src/librustc_middle/ty/context.rs:1710
  26: rustc_middle::ty::context::tls::set_tlv
             at src/librustc_middle/ty/context.rs:1694
  27: rustc_middle::ty::context::tls::enter_context
             at src/librustc_middle/ty/context.rs:1710
  28: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}
             at src/librustc_middle/dep_graph/mod.rs:71
  29: rustc_middle::ty::context::tls::with_context::{{closure}}
             at src/librustc_middle/ty/context.rs:1782
  30: rustc_middle::ty::context::tls::with_context_opt
             at src/librustc_middle/ty/context.rs:1771
  31: rustc_middle::ty::context::tls::with_context
             at src/librustc_middle/ty/context.rs:1782
  32: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
             at src/librustc_middle/dep_graph/mod.rs:68
  33: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
             at ./src/librustc_query_system/dep_graph/graph.rs:249
  34: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::{{closure}}
             at ./src/librustc_query_system/dep_graph/graph.rs:0
  35: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
             at src/librustc_middle/ty/query/plumbing.rs:72
  36: stacker::maybe_grow
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.9/src/lib.rs:52
  37: rustc_data_structures::stack::ensure_sufficient_stack
             at ./src/librustc_data_structures/stack.rs:16
  38: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}
             at src/librustc_middle/ty/query/plumbing.rs:72
  39: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at src/librustc_middle/ty/context.rs:1710
  40: rustc_middle::ty::context::tls::set_tlv
             at src/librustc_middle/ty/context.rs:1694
  41: rustc_middle::ty::context::tls::enter_context
             at src/librustc_middle/ty/context.rs:1710
  42: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}
             at src/librustc_middle/ty/query/plumbing.rs:71
  43: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at src/librustc_middle/ty/context.rs:1798
  44: rustc_middle::ty::context::tls::with_context::{{closure}}
             at src/librustc_middle/ty/context.rs:1782
  45: rustc_middle::ty::context::tls::with_context_opt
             at src/librustc_middle/ty/context.rs:1771
  46: rustc_middle::ty::context::tls::with_context
             at src/librustc_middle/ty/context.rs:1782
  47: rustc_middle::ty::context::tls::with_related_context
             at src/librustc_middle/ty/context.rs:1795
  48: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query
             at src/librustc_middle/ty/query/plumbing.rs:60
  49: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:589
  50: rustc_query_system::query::plumbing::with_diagnostics
             at ./src/librustc_query_system/query/plumbing.rs:296
  51: rustc_query_system::query::plumbing::force_query_with_job
             at ./src/librustc_query_system/query/plumbing.rs:588
  52: rustc_query_system::query::plumbing::force_query_impl::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:717
  53: <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::lookup
             at ./src/librustc_query_system/query/caches.rs:111
  54: rustc_query_system::query::plumbing::try_get_cached
             at ./src/librustc_query_system/query/plumbing.rs:369
  55: rustc_query_system::query::plumbing::force_query_impl
             at ./src/librustc_query_system/query/plumbing.rs:703
  56: rustc_query_system::query::plumbing::force_query
             at ./src/librustc_query_system/query/plumbing.rs:751
  57: rustc_middle::ty::query::force_from_dep_node
             at src/librustc_middle/ty/query/mod.rs:172
  58: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepContext for rustc_middle::ty::context::TyCtxt>::try_force_from_dep_node
             at src/librustc_middle/dep_graph/mod.rs:150
  59: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
             at ./src/librustc_query_system/dep_graph/graph.rs:634
  60: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
             at ./src/librustc_query_system/dep_graph/graph.rs:611
  61: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
             at ./src/librustc_query_system/dep_graph/graph.rs:611
  62: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
             at ./src/librustc_query_system/dep_graph/graph.rs:611
  63: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
             at ./src/librustc_query_system/dep_graph/graph.rs:611
  64: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green
             at ./src/librustc_query_system/dep_graph/graph.rs:532
  65: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
             at ./src/librustc_query_system/dep_graph/graph.rs:504
  66: rustc_query_system::query::plumbing::ensure_query_impl
             at ./src/librustc_query_system/query/plumbing.rs:671
  67: rustc_query_system::query::plumbing::ensure_query
             at ./src/librustc_query_system/query/plumbing.rs:741
  68: rustc_middle::ty::query::TyCtxtEnsure::codegen_fn_attrs
             at ./src/librustc_middle/ty/query/plumbing.rs:408
  69: rustc_passes::check_attr::CheckAttrVisitor::check_attributes
             at src/librustc_passes/check_attr.rs:83
  70: <rustc_passes::check_attr::CheckAttrVisitor as rustc_hir::intravisit::Visitor>::visit_impl_item
             at src/librustc_passes/check_attr.rs:438
  71: <rustc_hir::intravisit::DeepVisitor<V> as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
             at ./src/librustc_hir/intravisit.rs:65
  72: rustc_middle::hir::map::Map::visit_item_likes_in_module
             at ./src/librustc_middle/hir/map/mod.rs:476
  73: rustc_passes::check_attr::check_mod_attrs
             at src/librustc_passes/check_attr.rs:468
  74: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_mod_attrs>::compute
             at ./src/librustc_middle/ty/query/plumbing.rs:381
  75: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::{{closure}}
             at ./src/librustc_query_system/dep_graph/graph.rs:249
  76: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::{{closure}}
             at ./src/librustc_middle/dep_graph/mod.rs:71
  77: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1710
  78: rustc_middle::ty::context::tls::set_tlv
             at ./src/librustc_middle/ty/context.rs:1694
  79: rustc_middle::ty::context::tls::enter_context
             at ./src/librustc_middle/ty/context.rs:1710
  80: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}
             at ./src/librustc_middle/dep_graph/mod.rs:71
  81: rustc_middle::ty::context::tls::with_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1782
  82: rustc_middle::ty::context::tls::with_context_opt
             at ./src/librustc_middle/ty/context.rs:1771
  83: rustc_middle::ty::context::tls::with_context
             at ./src/librustc_middle/ty/context.rs:1782
  84: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
             at ./src/librustc_middle/dep_graph/mod.rs:68
  85: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
             at ./src/librustc_query_system/dep_graph/graph.rs:249
  86: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
             at ./src/librustc_query_system/dep_graph/graph.rs:200
  87: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:599
  88: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
             at ./src/librustc_middle/ty/query/plumbing.rs:72
  89: stacker::maybe_grow
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.9/src/lib.rs:52
  90: rustc_data_structures::stack::ensure_sufficient_stack
             at ./src/librustc_data_structures/stack.rs:16
  91: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}
             at ./src/librustc_middle/ty/query/plumbing.rs:72
  92: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1710
  93: rustc_middle::ty::context::tls::set_tlv
             at ./src/librustc_middle/ty/context.rs:1694
  94: rustc_middle::ty::context::tls::enter_context
             at ./src/librustc_middle/ty/context.rs:1710
  95: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}
             at ./src/librustc_middle/ty/query/plumbing.rs:71
  96: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1798
  97: rustc_middle::ty::context::tls::with_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1782
  98: rustc_middle::ty::context::tls::with_context_opt
             at ./src/librustc_middle/ty/context.rs:1771
  99: rustc_middle::ty::context::tls::with_context
             at ./src/librustc_middle/ty/context.rs:1782
 100: rustc_middle::ty::context::tls::with_related_context
             at ./src/librustc_middle/ty/context.rs:1795
 101: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query
             at ./src/librustc_middle/ty/query/plumbing.rs:60
 102: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:589
 103: rustc_query_system::query::plumbing::with_diagnostics
             at ./src/librustc_query_system/query/plumbing.rs:296
 104: rustc_query_system::query::plumbing::force_query_with_job
             at ./src/librustc_query_system/query/plumbing.rs:588
 105: rustc_query_system::query::plumbing::try_execute_query
             at ./src/librustc_query_system/query/plumbing.rs:465
 106: rustc_query_system::query::plumbing::get_query_impl::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:639
 107: <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::lookup
             at ./src/librustc_query_system/query/caches.rs:111
 108: rustc_query_system::query::plumbing::try_get_cached
             at ./src/librustc_query_system/query/plumbing.rs:369
 109: rustc_query_system::query::plumbing::get_query_impl
             at ./src/librustc_query_system/query/plumbing.rs:631
 110: rustc_query_system::query::plumbing::ensure_query_impl
             at ./src/librustc_query_system/query/plumbing.rs:679
 111: rustc_query_system::query::plumbing::ensure_query
             at ./src/librustc_query_system/query/plumbing.rs:741
 112: rustc_middle::ty::query::TyCtxtEnsure::check_mod_attrs
             at ./src/librustc_middle/ty/query/plumbing.rs:408
 113: rustc_interface::passes::analysis::{{closure}}::{{closure}}::{{closure}}
             at src/librustc_interface/passes.rs:848
 114: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at ./src/libcore/iter/traits/iterator.rs:655
 115: core::iter::traits::iterator::Iterator::fold
             at ./src/libcore/iter/traits/iterator.rs:2022
 116: core::iter::traits::iterator::Iterator::for_each
             at ./src/libcore/iter/traits/iterator.rs:658
 117: rustc_interface::passes::analysis::{{closure}}::{{closure}}
             at src/librustc_interface/passes.rs:845
 118: core::ops::function::FnOnce::call_once
             at ./src/libcore/ops/function.rs:233
 119: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./src/libstd/panic.rs:318
 120: std::panicking::try::do_call
             at ./src/libstd/panicking.rs:348
 121: std::panicking::try
             at ./src/libstd/panicking.rs:325
 122: std::panic::catch_unwind
             at ./src/libstd/panic.rs:394
 123: rustc_interface::passes::analysis::{{closure}}
             at src/librustc_interface/passes.rs:833
 124: rustc_data_structures::profiling::VerboseTimingGuard::run
             at ./src/librustc_data_structures/profiling.rs:573
 125: rustc_session::utils::<impl rustc_session::session::Session>::time
             at ./src/librustc_session/utils.rs:9
 126: rustc_interface::passes::analysis
             at src/librustc_interface/passes.rs:832
 127: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
             at ./src/librustc_middle/ty/query/plumbing.rs:381
 128: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::{{closure}}
             at ./src/librustc_query_system/dep_graph/graph.rs:249
 129: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}::{{closure}}
             at ./src/librustc_middle/dep_graph/mod.rs:71
 130: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1710
 131: rustc_middle::ty::context::tls::set_tlv
             at ./src/librustc_middle/ty/context.rs:1694
 132: rustc_middle::ty::context::tls::enter_context
             at ./src/librustc_middle/ty/context.rs:1710
 133: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::{{closure}}
             at ./src/librustc_middle/dep_graph/mod.rs:71
 134: rustc_middle::ty::context::tls::with_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1782
 135: rustc_middle::ty::context::tls::with_context_opt
             at ./src/librustc_middle/ty/context.rs:1771
 136: rustc_middle::ty::context::tls::with_context
             at ./src/librustc_middle/ty/context.rs:1782
 137: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
             at ./src/librustc_middle/dep_graph/mod.rs:68
 138: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
             at ./src/librustc_query_system/dep_graph/graph.rs:249
 139: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}::{{closure}}
             at ./src/librustc_query_system/dep_graph/graph.rs:0
 140: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
             at ./src/librustc_middle/ty/query/plumbing.rs:72
 141: stacker::maybe_grow
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.9/src/lib.rs:52
 142: rustc_data_structures::stack::ensure_sufficient_stack
             at ./src/librustc_data_structures/stack.rs:16
 143: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}
             at ./src/librustc_middle/ty/query/plumbing.rs:72
 144: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1710
 145: rustc_middle::ty::context::tls::set_tlv
             at ./src/librustc_middle/ty/context.rs:1694
 146: rustc_middle::ty::context::tls::enter_context
             at ./src/librustc_middle/ty/context.rs:1710
 147: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}
             at ./src/librustc_middle/ty/query/plumbing.rs:71
 148: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1798
 149: rustc_middle::ty::context::tls::with_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1782
 150: rustc_middle::ty::context::tls::with_context_opt
             at ./src/librustc_middle/ty/context.rs:1771
 151: rustc_middle::ty::context::tls::with_context
             at ./src/librustc_middle/ty/context.rs:1782
 152: rustc_middle::ty::context::tls::with_related_context
             at ./src/librustc_middle/ty/context.rs:1795
 153: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query
             at ./src/librustc_middle/ty/query/plumbing.rs:60
 154: rustc_query_system::query::plumbing::force_query_with_job::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:589
 155: rustc_query_system::query::plumbing::with_diagnostics
             at ./src/librustc_query_system/query/plumbing.rs:296
 156: rustc_query_system::query::plumbing::force_query_with_job
             at ./src/librustc_query_system/query/plumbing.rs:588
 157: rustc_query_system::query::plumbing::try_execute_query
             at ./src/librustc_query_system/query/plumbing.rs:465
 158: rustc_query_system::query::plumbing::get_query_impl::{{closure}}
             at ./src/librustc_query_system/query/plumbing.rs:639
 159: <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::lookup
             at ./src/librustc_query_system/query/caches.rs:111
 160: rustc_query_system::query::plumbing::try_get_cached
             at ./src/librustc_query_system/query/plumbing.rs:369
 161: rustc_query_system::query::plumbing::get_query_impl
             at ./src/librustc_query_system/query/plumbing.rs:631
 162: rustc_query_system::query::plumbing::get_query
             at ./src/librustc_query_system/query/plumbing.rs:731
 163: rustc_middle::ty::query::TyCtxtAt::analysis
             at ./src/librustc_middle/ty/query/plumbing.rs:491
 164: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::analysis
             at ./src/librustc_middle/ty/query/plumbing.rs:452
 165: rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}
             at src/librustc_driver/lib.rs:381
 166: rustc_middle::ty::context::tls::enter_global::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1733
 167: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at ./src/librustc_middle/ty/context.rs:1710
 168: rustc_middle::ty::context::tls::set_tlv
             at ./src/librustc_middle/ty/context.rs:1694
 169: rustc_middle::ty::context::tls::enter_context
             at ./src/librustc_middle/ty/context.rs:1710
 170: rustc_middle::ty::context::tls::enter_global
             at ./src/librustc_middle/ty/context.rs:1733
 171: rustc_interface::passes::QueryContext::enter
             at ./src/librustc_interface/passes.rs:755
 172: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at src/librustc_driver/lib.rs:381
 173: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at ./src/librustc_interface/queries.rs:386
 174: rustc_driver::run_compiler::{{closure}}
             at src/librustc_driver/lib.rs:284
 175: rustc_interface::interface::run_compiler_in_existing_thread_pool::{{closure}}
             at ./src/librustc_interface/interface.rs:195
 176: rustc_span::with_source_map
             at ./src/librustc_span/lib.rs:733
 177: rustc_interface::interface::run_compiler_in_existing_thread_pool
             at ./src/librustc_interface/interface.rs:189
 178: rustc_interface::interface::run_compiler::{{closure}}
             at ./src/librustc_interface/interface.rs:211
 179: rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}::{{closure}}
             at ./src/librustc_interface/util.rs:149
 180: scoped_tls::ScopedKey<T>::set
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
 181: rustc_interface::util::spawn_thread_pool::{{closure}}::{{closure}}
             at ./src/librustc_interface/util.rs:145
 182: scoped_tls::ScopedKey<T>::set
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
 183: rustc_ast::attr::with_session_globals::{{closure}}
             at ./src/librustc_ast/attr/mod.rs:49
 184: scoped_tls::ScopedKey<T>::set
             at /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
 185: rustc_ast::attr::with_session_globals
             at ./src/librustc_ast/attr/mod.rs:48
 186: rustc_interface::util::spawn_thread_pool::{{closure}}
             at ./src/librustc_interface/util.rs:144
 187: rustc_interface::util::scoped_thread::{{closure}}
             at ./src/librustc_interface/util.rs:119
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

query stack during panic:
#0 [dep_kind] fetching what a dependency looks like
#1 [check_mod_attrs] checking attributes in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

@rustbot modify labels: A-rustbuild A-incr-comp

**Comment by jyn514** [comment]
Also this has the changes to x.py that I made in https://github.com/rust-lang/rust/pull/73964, so maybe I introduced a bug myself?

**Comment by jyn514** [comment]
>  However the panic happens consistently, so I can upload a zip of the build directory if someone knows a place to host 10 GB of binary artifacts.

This is no longer the case, I've since lost the state of the build directory.

**Comment by wesleywiser** [comment]
@jyn514 confirmed they haven't experienced this since reporting the issue 4 months ago. It seems likely the root cause was the changes to rustbuild they were working on. I've looked through the issue tracker and can't find any similar issues reported other than this so we're going to close for now. 

If this happens again, feel free to re-open.
