### ISSUE TITLE
Borrowck panics possibly while analyzing async fns after typeck fails earlier

### ISSUE THREAD

**Issue by dingxiangfei2009** [rust-lang/rust#74339]
Sorry that I cannot reduce the original code for reproduction. However, I will provide as many details as possible. Any guidance for how to reduce the test case is very welcome.

In an `async fn`, obvious things such as `await` on non-`Future`s fails typeck. However, borrowck panics after this. Here is the backtrace info.

### Error output
```
error: internal compiler error: src/librustc_mir/borrow_check/universal_regions.rs:750: cannot convert `ReEmpty(U0)` to a region vid

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:904:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc_middle::ty::context::tls::with_opt::{{closure}}
  17: rustc_middle::ty::context::tls::with_opt
  18: rustc_middle::util::bug::opt_span_bug_fmt
  19: rustc_middle::util::bug::bug_fmt
  20: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid::{{closure}}
  21: rustc_mir::borrow_check::universal_regions::UniversalRegionIndices::to_region_vid
  22: rustc_mir::borrow_check::type_check::constraint_conversion::ConstraintConversion::convert_all
  23: rustc_mir::borrow_check::type_check::TypeChecker::prove_predicate
  24: rustc_mir::borrow_check::type_check::TypeChecker::normalize_and_prove_instantiated_predicates
  25: <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_constant
  26: <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body
  27: rustc_mir::borrow_check::type_check::type_check
  28: rustc_mir::borrow_check::nll::compute_regions
  29: rustc_mir::borrow_check::do_mir_borrowck
  30: rustc_middle::ty::context::GlobalCtxt::enter_local
  31: rustc_mir::borrow_check::mir_borrowck
  32: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  33: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  34: rustc_query_system::query::plumbing::get_query
  35: rustc_mir::borrow_check::type_check::TypeChecker::check_rvalue
  36: rustc_mir::borrow_check::type_check::TypeChecker::typeck_mir
  37: rustc_mir::borrow_check::type_check::type_check
  38: rustc_mir::borrow_check::nll::compute_regions
  39: rustc_mir::borrow_check::do_mir_borrowck
  40: rustc_middle::ty::context::GlobalCtxt::enter_local
  41: rustc_mir::borrow_check::mir_borrowck
  42: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  43: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  44: rustc_query_system::query::plumbing::get_query
  45: rustc_typeck::collect::type_of::type_of
  46: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  47: rustc_query_system::query::plumbing::get_query
  48: rustc_middle::ty::util::<impl rustc_middle::ty::context::TyCtxt>::try_expand_impl_trait_type::OpaqueTypeExpander::expand_opaque_ty
  49: rustc_middle::ty::util::<impl rustc_middle::ty::context::TyCtxt>::try_expand_impl_trait_type
  50: rustc_typeck::check::check_item_type
  51: rustc_middle::hir::map::Map::visit_item_likes_in_module
  52: rustc_typeck::check::check_mod_item_types
  53: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_mod_item_types>::compute
  54: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  55: rustc_query_system::query::plumbing::get_query
  56: rustc_query_system::query::plumbing::ensure_query
  57: rustc_typeck::check_crate
  58: rustc_interface::passes::analysis
  59: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  60: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  61: rustc_query_system::query::plumbing::get_query
  62: rustc_middle::ty::context::tls::enter_global
  63: rustc_interface::interface::run_compiler_in_existing_thread_pool
  64: scoped_tls::ScopedKey<T>::set
  65: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0 (49cae5576 2020-06-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `state::session::<impl state::Session<G>>::process_session::{{closure}}#0`
#1 [mir_borrowck] borrow-checking `state::session::<impl state::Session<G>>::process_session`
#2 [type_of] processing `state::session::<impl state::Session<G>>::process_session::{{opaque}}#0`
#3 [check_mod_item_types] checking item types in module `state::session`
#4 [analysis] running analysis passes on this crate
end of query stack
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-unknown-linux-gnu
release: 1.44.0
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
Please check if this still occurs on the newest nightly

**Comment by dingxiangfei2009** [comment]
Standby, as reproduction on nightly is currently blocked by other borrow checker issue.

**Comment by dingxiangfei2009** [comment]
I think it is no longer reproducible on the most recent nightly. Though I will report the other borrow checker issue. Thank you for the help, @jonas-schievink :smile:
