### ISSUE TITLE
ICE - Panic while cross-compiling for i686/x86_64-unknown-uefi

### ISSUE THREAD

**Issue by Dark-Legion** [rust-lang/rust#74542]
Must be compiled with nightly as `build-std=core` is used for cargo.

### Code

`lib.rs`:
```
#![no_std]

pub fn pass_array(data: &[u8; 16]) {}

pub struct S {
	data: (),
}

fn work(s: &S) {
	pass_array(
		unsafe {
			&*(s.data as *const _ as *const [u8; 16])
			// Correct syntax (& compiler works properly):
			// &*(&s.data as *const _ as *const [u8; 16])
		}
	);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
binary: rustc
commit-hash: 346aec9b02f3c74f3fce97fd6bda24709d220e49
commit-date: 2020-07-11
host: x86_64-pc-windows-msvc
release: 1.46.0-nightly
LLVM version: 10.0
```

Commands:
```
cargo build -Z unstable-options -Z build-std=core --target=i686-unknown-uefi
cargo build -Z unstable-options -Z build-std=core --release --target=i686-unknown-uefi
cargo build -Z unstable-options -Z build-std=core --target=x86_64-unknown-uefi
cargo build -Z unstable-options -Z build-std=core --release --target=x86_64-unknown-uefi
```

### Error output

On debug:
```
error: internal compiler error: src\librustc_middle\ich\impls_ty.rs:167:9: ty::TyKind::hash_stable() - can't hash a TyVid _#1t.
```

On release:
```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 1', C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\ena-0.14.0\src\snapshot_vec.rs:199:10
```
**...**
```
note: rustc 1.46.0-nightly (346aec9b0 2020-07-11) running on x86_64-pc-windows-msvc

note: compiler flags: -Z unstable-options -C opt-level=3 -C linker-plugin-lto --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

<details><summary><strong>Backtrace</strong></summary>
<p>

On debug:
```
thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:916:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: <rustc_errors::styled_buffer::StyledBuffer as core::fmt::Debug>::fmt
   8: rustc_errors::HandlerInner::err_count
   9: rustc_errors::Handler::bug
  10: rustc_middle::util::bug::bug_fmt
  11: <rustc_middle::ty::consts::ConstInt as core::fmt::Debug>::fmt
  12: <rustc_middle::ty::consts::ConstInt as core::fmt::Debug>::fmt
  13: rustc_middle::util::bug::bug_fmt
  14: rustc_middle::util::bug::bug_fmt
  15: rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::TyVid>::hash_stable
  16: ZN12rustc_middle2ty3sty108_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_middle_ich_StableHashingContext_ctx_FOR_InferTy161_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc_middle..ich..hcx..StableHashingContext$GT$$u20
  17: ZN12rustc_middle2ty3sty107_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_middle_ich_StableHashingContext_ctx_FOR_TyKind160_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc_middle..ich..hcx..StableHashingContext$GT$$u20$
  18: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  19: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  20: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  21: rustc_typeck::check::FnCtxt::field_ty
  22: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  23: <rustc_typeck::check::fixup_opaque_types::FixupFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  24: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  25: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  26: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  27: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  28: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  29: <rustc_typeck::check::CheckItemTypesVisitor as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_item
  30: <rustc_typeck::astconv::Bounds as core::fmt::Debug>::fmt
  31: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  32: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  33: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  34: rustc_typeck::check_crate
  35: rustc_interface::passes::QueryContext::print_stats
  36: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  37: <rustc_codegen_ssa::back::linker::MsvcLinker as rustc_codegen_ssa::back::linker::Linker>::partial_relro
  38: rustc_driver::pretty::print_after_hir_lowering
  39: <(&rustc_middle::ty::sty::Const,rustc_middle::mir::Field) as rustc_middle::ty::query::keys::Key>::default_span
  40: rustc_driver::pretty::print_after_hir_lowering
  41: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  42: <rustc_codegen_ssa::back::linker::MsvcLinker as rustc_codegen_ssa::back::linker::Linker>::partial_relro
  43: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  44: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  45: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  46: <(&rustc_middle::ty::sty::Const,rustc_middle::mir::Field) as rustc_middle::ty::query::keys::Key>::default_span
  47: std::sys::windows::thread::Thread::new
  48: BaseThreadInitThunk
  49: RtlUserThreadStart

query stack during panic:
#0 [typeck_tables_of] type-checking `work`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
```

On release:
```
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: rustc_infer::infer::InferCtxt::probe_ty_var
  11: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  12: <rustc_infer::infer::region_constraints::leak_check::LeakCheckNode as core::ops::arith::Add<usize>>::add
  13: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  14: <<rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors::ErrorDescriptor as core::fmt::Debug>::fmt
  15: <rustc_trait_selection::traits::util::TraitAliasExpansionInfo as core::fmt::Debug>::fmt
  16: <<rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors::ErrorDescriptor as core::fmt::Debug>::fmt
  17: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  18: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  19: unicode_normalization::normalize::is_hangul_syllable
  20: rustc_trait_selection::traits::normalize_and_test_predicates
  21: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  22: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  23: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  24: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  25: rustc_typeck::check::FnCtxt::field_ty
  26: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  27: <rustc_typeck::check::fixup_opaque_types::FixupFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  28: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  29: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  30: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  31: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  32: <rustc_typeck::check::CheckItemTypesVisitor as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_item
  33: <rustc_typeck::astconv::Bounds as core::fmt::Debug>::fmt
  34: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  35: <rustc_typeck::variance::constraints::ConstraintContext as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  36: rustc_typeck::check_crate
  37: rustc_interface::passes::QueryContext::print_stats
  38: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  39: rustc_driver::pretty::print_after_hir_lowering
  40: <(&rustc_middle::ty::sty::Const,rustc_middle::mir::Field) as rustc_middle::ty::query::keys::Key>::default_span
  41: rustc_driver::pretty::print_after_hir_lowering
  42: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  43: <rustc_codegen_ssa::back::linker::MsvcLinker as rustc_codegen_ssa::back::linker::Linker>::partial_relro
  44: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  45: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  46: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  47: <(&rustc_middle::ty::sty::Const,rustc_middle::mir::Field) as rustc_middle::ty::query::keys::Key>::default_span
  48: std::sys::windows::thread::Thread::new
  49: BaseThreadInitThunk
  50: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (346aec9b0 2020-07-11) running on x86_64-pc-windows-msvc

note: compiler flags: -Z unstable-options -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_implements_trait] evaluating `type_implements_trait` `(DefId(1:1851 ~ core[aabf]::convert[0]::From[0]), *const _, [()], ParamEnv { caller_bounds: [], 
reveal: UserFacing, def_id: None })`
#1 [typeck_tables_of] type-checking `work`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by Dark-Legion** [comment]
@jonas-schievink I have added a link to the repository and, as noted, will try to isolate the problem.

**Comment by Dark-Legion** [comment]
@jonas-schievink I have isolated the problem and added minimal example.
