### ISSUE TITLE
NaN checking for result function failed

### ISSUE THREAD

**Issue by Zaryob** [rust-lang/rust#74725]
I trying to create a mathematical expression library. I wrote that function in  `lib.rs`:

```rust

pub fn limit(reachment: f64, function: &dyn Fn(f64) -> f64) -> f64 {
    function(reachment)
}

```

In theory whether there is not limit at `reachment` it needs to return NaN.

I write a test to check that issue:

```rust
#[cfg(test)]
mod tests {
    use limit::limit;
    use core::f64::NAN;

    pub fn simple_function_one(x: f64) -> f64 {
        x / x
    }

    #[test]
    fn test_sf1_zerotest() {
        assert_eq!(limit(0.0, &simple_function_one), NAN);
    }
```

When I started `cargo test` command it gives that failture:
```
test tests::test_sf1_zerotest ... FAILED

failures:

---- tests::test_sf1_zerotest stdout ----
thread 'tests::test_sf1_zerotest' panicked at 'assertion failed: `(left == right)`
  left: `NaN`,
 right: `NaN`', limit/tests/test.rs:29:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_sf1_zerotest

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

`rustc --version --verbose`:
```
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 10.0

```

`cargo --version --verbose`
```
cargo 1.45.0 (744bd1fbb 2020-06-15)
release: 1.45.0
commit-hash: 744bd1fbb666f33b20b09d5bacc5047957c8ed42
commit-date: 2020-06-15
```

<details><summary>Backtrace</summary>
<p>

```
warning: function is never used: `simple_function_two`
  --> limit/tests/test.rs:10:12
   |
10 |     pub fn simple_function_two(x: f64) -> f64 {
   |            ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

    Finished test [unoptimized + debuginfo] target(s) in 0.09s
     Running target/debug/deps/derivative-406fa269dbb62fe0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/mtd_test-ad4d1838a0370202

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/simple_otd_test-6d002bde59911887

running 6 tests
test simple_otd_tests::test_sf1_1 ... ok
test simple_otd_tests::test_sf1_2 ... ok
test simple_otd_tests::test_sf1_zerotest ... ok
test simple_otd_tests::test_sf2_2 ... ok
test simple_otd_tests::test_sf2_zerotest ... ok
test simple_otd_tests::test_sf2_1 ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integral-7af9a0aa4242f899

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/limit-a55dacd3e564f507

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test-72247c6600249bbd

running 3 tests
test tests::test_sf1_1 ... ok
test tests::test_sf1_2 ... ok
test tests::test_sf1_zerotest ... FAILED

failures:

---- tests::test_sf1_zerotest stdout ----
thread 'tests::test_sf1_zerotest' panicked at 'assertion failed: `(left == right)`
  left: `NaN`,
 right: `NaN`', limit/tests/test.rs:29:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  12: rust_begin_unwind
             at src/libstd/panicking.rs:388
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:342
  14: test::tests::test_sf1_zerotest
             at limit/tests/test.rs:29
  15: test::tests::test_sf1_zerotest::{{closure}}
             at limit/tests/test.rs:28
  16: core::ops::function::FnOnce::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libcore/ops/function.rs:232
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panic.rs:318
  19: std::panicking::try::do_call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:297
  20: std::panicking::try
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:541
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::test_sf1_zerotest

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p limit --test test'

```

</p>
</details>

**Comment by Zaryob** [comment]
I have been C and Python encoding for a long time. I started this project to understand the structure of the language. I have been running small business with rust for 1 month, but I could not find any reason for this error.

if you want to review, Full code on my github account [Calculusator](https://github.com/Zaryob/Calculusator)

**Comment by bugadani** [comment]
I think you need to use `is_nan` to check if a number is nan or not. I think the same is true as in C, where NAN is not equal to itself.

**Comment by jonas-schievink** [comment]
Yes, NaN != NaN
