### ISSUE TITLE
Cargo Build hangs forever with recent nighlies

### ISSUE THREAD

**Issue by jamesmunns** [rust-lang/rust#75074]
With the following steps, I see the build hang indefinitely. This caused a 6 hour CI timeout for the nrf-rs organization. This does not happen with the stable/beta CI jobs, and did not happen previously with nightly. The following is a minimal repro of the CI steps of https://github.com/nrf-rs/nrf-hal/pull/189.

```bash
git clone https://github.com/kalkyl/nrf-hal.git
cd nrf-hal
git checkout comp
rustup override set nightly-2020-08-02-x86_64-unknown-linux-gnu
rustup target add thumbv7em-none-eabihf
cargo build --manifest-path examples/rtic-demo/Cargo.toml
```

**Comment by jonas-schievink** [comment]
```
#0  0x00007ffff53b4ea6 in rustc_mir::transform::simplify::CfgSimplifier::simplify ()
   from /home/jonas/.rustup/toolchains/nightly-2020-08-02-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-edb22b7dff97b8bd.so
#1  0x00007ffff53b4728 in rustc_mir::transform::simplify::simplify_cfg ()
   from /home/jonas/.rustup/toolchains/nightly-2020-08-02-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-edb22b7dff97b8bd.so
```

yep, same issue as https://github.com/rust-lang/rust/issues/75051

**Comment by jonas-schievink** [comment]
Reduced to just:

```rust
fn main() {
    loop {
        continue;
    }
}
```
