### ISSUE TITLE
1.45.0 regression macro-related ICE on 32-bit arm/ppc in tests

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#75219]
Didn't try on 1.45.2 yet but the failures seem unrelated to the things mentioned in the release notes.

[armel log](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=armel&ver=1.45.0%2Bdfsg1-1&stamp=1596692850&raw=0), [armhf log](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=armhf&ver=1.45.0%2Bdfsg1-1&stamp=1596690844&raw=0)

~~~
test [ui] ui/fn/expr-fn-panic.rs ... FAILED
test [ui] ui/imports/glob-use-std.rs ... FAILED
test [ui] ui/macros/die-macro-2.rs ... FAILED
test [ui] ui/macros/die-macro-pure.rs ... FAILED
test [ui] ui/macros/unimplemented-macro-panic.rs ... FAILED
test [ui] ui/macros/unreachable-macro-panic.rs ... FAILED
test [ui] ui/macros/unreachable.rs ... FAILED
test [ui] ui/meta-revision-ok.rs#bar ... FAILED
test [ui] ui/meta-revision-ok.rs#foo ... FAILED
test [ui] ui/mir/mir_codegen_calls_diverging.rs ... FAILED
test [ui] ui/panics/doublepanic.rs ... FAILED
test [ui] ui/panics/explicit-panic.rs ... FAILED
test [ui] ui/panics/main-panic.rs ... FAILED
test [ui] ui/panics/panic-macro-explicit.rs ... FAILED
test [ui] ui/panics/panic-macro-owned.rs ... FAILED
test [ui] ui/panics/panic-macro-static.rs ... FAILED
test [ui] ui/panics/panic-main.rs ... FAILED
test [ui] ui/rfc-1937-termination-trait/termination-trait-for-never.rs ... FAILED
~~~~

**Comment by infinity0** [comment]
example:

~~~~
---- [ui] ui/fn/expr-fn-panic.rs stdout ----


executing "/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/stage2/bin/rustc" "/<<PKGBUILDDIR>>/src/test/ui/fn/expr-fn-panic.rs" "-Zthreads=1" "--target=armv7-unknown-linux-gnueabihf" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "-o" "/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/test/ui/fn/expr-fn-panic/a" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/native/rust-test-helpers" "-Clinker=arm-linux-gnueabihf-gcc" "-L" "/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/test/ui/fn/expr-fn-panic/auxiliary"
------stdout------------------------------

------stderr------------------------------
thread 'rustc' panicked at 'assertion failed: self.ptr <= self.end', /usr/src/rustc-1.45.0/src/libstd/macros.rs:13:23
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_middle::ty::context::TyCtxt::mk_const
   9: <rustc_middle::mir::Constant as serialize::serialize::Decodable>::decode
  10: <rustc_middle::mir::Operand as serialize::serialize::Decodable>::decode
  11: <(T10,T11) as serialize::serialize::Decodable>::decode
  12: <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode
  13: serialize::serialize::Decoder::read_seq
  14: <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode
  15: serialize::serialize::Decoder::read_seq
  16: <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
  17: rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_optimized_mir
  18: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::get_query_impl
  23: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir
  24: rustc_mir::monomorphize::collector::collect_neighbours
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_crate_mono_items
  29: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  30: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::get_query_impl
  34: rustc_codegen_ssa::base::codegen_crate
  35: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  36: rustc_interface::passes::start_codegen
  37: rustc_middle::ty::context::tls::enter_global
  38: rustc_interface::queries::Queries::ongoing_codegen
  39: rustc_interface::interface::run_compiler_in_existing_thread_pool
  40: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0 running on armv7-unknown-linux-gnueabihf

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C prefer-dynamic -C rpath -C debuginfo=0 -C linker=arm-linux-gnueabihf-gcc

query stack during panic:
thread 'rustc' panicked at 'assertion failed: self.ptr <= self.end', /usr/src/rustc-1.45.0/src/libstd/macros.rs:13:23
stack backtrace:
   0: 0xb3bea4e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he917653db8b9aaa2
   1: 0xb3c2ec48 - core::fmt::write::h86686004711a56bf
   2: 0xb3bbaf58 - std::io::Write::write_fmt::hff0069a3f62df2fe
   3: 0xb3bc68ec - std::panicking::default_hook::{{closure}}::h3eba463d12c99b0a
   4: 0xb3bc6594 - std::panicking::default_hook::h6117faad3ea2c585
   5: 0xb3faf4b0 - rustc_driver::report_ice::h1280f2762d7c80a3
   6: 0xb3bc7074 - std::panicking::rust_panic_with_hook::h58b73c3c20469f0b
   7: 0xb5855aa8 - std::panicking::begin_panic::h909bc1d80acfc4f3
   8: 0xb58287d4 - rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::item_children::hbd48240e313d545a
   9: 0xb5802034 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::item_children>::compute::hd327c31558ea60ea
  10: 0xb58ee7bc - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hab8927634d2a3be2
  11: 0xb59220fc - rustc_data_structures::stack::ensure_sufficient_stack::haeb1fa644999285f
  12: 0xb58be4e4 - rustc_query_system::query::plumbing::get_query_impl::haec55dddb166a3ae
  13: 0xb5804eb0 - core::ops::function::FnOnce::call_once::h1d3cfdf5ee1bb180
  14: 0xb621d0ec - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::visible_parent_map>::compute::h1a86670413180fc0
  15: 0xb62c0690 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hd21b1d5f9abc9bc1
  16: 0xb640cfe8 - rustc_data_structures::stack::ensure_sufficient_stack::h3e90162c9bcf2e6b
  17: 0xb631a028 - rustc_query_system::query::plumbing::get_query_impl::h6d7087982c264df3
  18: 0xb61de4e0 - rustc_middle::ty::print::pretty::PrettyPrinter::try_print_visible_def_path_recur::h73f4d5540f20fa4f
  19: 0xb61e96c4 - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::h21d56930e03f7862
  20: 0xb6477718 - rustc_middle::ty::print::pretty::<impl rustc_middle::ty::context::TyCtxt>::def_path_str_with_substs::h735850dce207a367
  21: 0xb6261960 - rustc_middle::ty::query::Query::describe::hf2e43136da6cb566
  22: 0xb647a900 - rustc_middle::ty::query::plumbing::<impl rustc_middle::ty::context::TyCtxt>::try_print_query_stack::he858c1f250faf89a
  23: 0xb3fafee4 - rustc_driver::report_ice::h1280f2762d7c80a3
  24: 0xb3bc7074 - std::panicking::rust_panic_with_hook::h58b73c3c20469f0b
  25: 0xb641be48 - std::panicking::begin_panic::ha97e79a759e28ac5
  26: 0xb64ad988 - rustc_middle::ty::context::TyCtxt::mk_const::h5c579b579a5d4e4e
  27: 0xb57ed2e4 - <rustc_middle::mir::Constant as serialize::serialize::Decodable>::decode::hcccd2e53e0fbdc9a
  28: 0xb57ece28 - <rustc_middle::mir::Operand as serialize::serialize::Decodable>::decode::hef40af16ce4eb25f
  29: 0xb57e6e90 - <(T10,T11) as serialize::serialize::Decodable>::decode::he0a546990f60f411
  30: 0xb57ef32c - <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode::ha59124684abb7737
  31: 0xb590f8e0 - serialize::serialize::Decoder::read_seq::h0bdeb39a663d95e4
  32: 0xb57f57f0 - <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode::h85192902e977ca51
  33: 0xb5911480 - serialize::serialize::Decoder::read_seq::h3d53abe3ecf9c8f7
  34: 0xb57e9910 - <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}::h4f958f0814a98d03
  35: 0xb578444c - rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_optimized_mir::h1461bddf9273a65a
  36: 0xb581e1f4 - rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir::h8a524a5a40407959
  37: 0xb64a18fc - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute::h1153aaf480992394
  38: 0xb62b28e8 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h93c28e2c4e0992a3
  39: 0xb6418ae8 - rustc_data_structures::stack::ensure_sufficient_stack::hf6b20815eb074795
  40: 0xb631c05c - rustc_query_system::query::plumbing::get_query_impl::h6ddbca02528d39d6
  41: 0xb64923f0 - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir::hd8182a721d5f616f
  42: 0xb51f3b6c - rustc_mir::monomorphize::collector::collect_neighbours::hc8d196b66c6c2876
  43: 0xb51efdb8 - rustc_mir::monomorphize::collector::collect_items_rec::hde5cdc56f19e4b54
  44: 0xb51efe90 - rustc_mir::monomorphize::collector::collect_items_rec::hde5cdc56f19e4b54
  45: 0xb51efe90 - rustc_mir::monomorphize::collector::collect_items_rec::hde5cdc56f19e4b54
  46: 0xb51eedd0 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h6ebc2adeb0958363
  47: 0xb5435ea0 - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h86734da86fabc034
  48: 0xb44646bc - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h46959837fa33a65e
  49: 0xb4387854 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h358985cc3bdeae71
  50: 0xb446ddd0 - rustc_data_structures::stack::ensure_sufficient_stack::h7c4338a0c6c3d3cc
  51: 0xb440576c - rustc_query_system::query::plumbing::get_query_impl::h273d88f120260805
  52: 0xb44671a0 - rustc_codegen_ssa::base::codegen_crate::h966cb957dfed02a2
  53: 0xb43ccba8 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h15eea20020a9b9cd
  54: 0xb415b1f4 - rustc_interface::passes::start_codegen::h54a790bd0636dfc7
  55: 0xb41675c8 - rustc_middle::ty::context::tls::enter_global::h97c12a123ac35350
  56: 0xb41624c0 - rustc_interface::queries::Queries::ongoing_codegen::h879bdaeae4b0ca6f
  57: 0xb3f76194 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hc35c209e94217a6b
  58: 0xb3fbcef4 - rustc_ast::attr::with_globals::h3fc4a959b4267c29
  59: 0xb3fc6c6c - std::sys_common::backtrace::__rust_begin_short_backtrace::h6b300124e5ce2ac5
  60: 0xb3f78e2c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a101086f2a6e1c9
  61: 0xb3bced80 - std::sys::unix::thread::Thread::new::thread_start::h71da00e0bb15a647

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0 running on armv7-unknown-linux-gnueabihf

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C prefer-dynamic -C rpath -C debuginfo=0 -C linker=arm-linux-gnueabihf-gcc

query stack during panic:
thread panicked while processing panic. aborting.

------------------------------------------

error: test compilation failed although it shouldn't!
status: signal: 4
command: "/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/stage2/bin/rustc" "/<<PKGBUILDDIR>>/src/test/ui/fn/expr-fn-panic.rs" "-Zthreads=1" "--target=armv7-unknown-linux-gnueabihf" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "-o" "/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/test/ui/fn/expr-fn-panic/a" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/native/rust-test-helpers" "-Clinker=arm-linux-gnueabihf-gcc" "-L" "/<<PKGBUILDDIR>>/build/armv7-unknown-linux-gnueabihf/test/ui/fn/expr-fn-panic/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'assertion failed: self.ptr <= self.end', /usr/src/rustc-1.45.0/src/libstd/macros.rs:13:23
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_middle::ty::context::TyCtxt::mk_const
   9: <rustc_middle::mir::Constant as serialize::serialize::Decodable>::decode
  10: <rustc_middle::mir::Operand as serialize::serialize::Decodable>::decode
  11: <(T10,T11) as serialize::serialize::Decodable>::decode
  12: <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode
  13: serialize::serialize::Decoder::read_seq
  14: <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode
  15: serialize::serialize::Decoder::read_seq
  16: <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}
  17: rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_optimized_mir
  18: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::get_query_impl
  23: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir
  24: rustc_mir::monomorphize::collector::collect_neighbours
  25: rustc_mir::monomorphize::collector::collect_items_rec
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_crate_mono_items
  29: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  30: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_data_structures::stack::ensure_sufficient_stack
  33: rustc_query_system::query::plumbing::get_query_impl
  34: rustc_codegen_ssa::base::codegen_crate
  35: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  36: rustc_interface::passes::start_codegen
  37: rustc_middle::ty::context::tls::enter_global
  38: rustc_interface::queries::Queries::ongoing_codegen
  39: rustc_interface::interface::run_compiler_in_existing_thread_pool
  40: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0 running on armv7-unknown-linux-gnueabihf

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C prefer-dynamic -C rpath -C debuginfo=0 -C linker=arm-linux-gnueabihf-gcc

query stack during panic:
thread 'rustc' panicked at 'assertion failed: self.ptr <= self.end', /usr/src/rustc-1.45.0/src/libstd/macros.rs:13:23
stack backtrace:
   0: 0xb3bea4e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he917653db8b9aaa2
   1: 0xb3c2ec48 - core::fmt::write::h86686004711a56bf
   2: 0xb3bbaf58 - std::io::Write::write_fmt::hff0069a3f62df2fe
   3: 0xb3bc68ec - std::panicking::default_hook::{{closure}}::h3eba463d12c99b0a
   4: 0xb3bc6594 - std::panicking::default_hook::h6117faad3ea2c585
   5: 0xb3faf4b0 - rustc_driver::report_ice::h1280f2762d7c80a3
   6: 0xb3bc7074 - std::panicking::rust_panic_with_hook::h58b73c3c20469f0b
   7: 0xb5855aa8 - std::panicking::begin_panic::h909bc1d80acfc4f3
   8: 0xb58287d4 - rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::item_children::hbd48240e313d545a
   9: 0xb5802034 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::item_children>::compute::hd327c31558ea60ea
  10: 0xb58ee7bc - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hab8927634d2a3be2
  11: 0xb59220fc - rustc_data_structures::stack::ensure_sufficient_stack::haeb1fa644999285f
  12: 0xb58be4e4 - rustc_query_system::query::plumbing::get_query_impl::haec55dddb166a3ae
  13: 0xb5804eb0 - core::ops::function::FnOnce::call_once::h1d3cfdf5ee1bb180
  14: 0xb621d0ec - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::visible_parent_map>::compute::h1a86670413180fc0
  15: 0xb62c0690 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hd21b1d5f9abc9bc1
  16: 0xb640cfe8 - rustc_data_structures::stack::ensure_sufficient_stack::h3e90162c9bcf2e6b
  17: 0xb631a028 - rustc_query_system::query::plumbing::get_query_impl::h6d7087982c264df3
  18: 0xb61de4e0 - rustc_middle::ty::print::pretty::PrettyPrinter::try_print_visible_def_path_recur::h73f4d5540f20fa4f
  19: 0xb61e96c4 - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::h21d56930e03f7862
  20: 0xb6477718 - rustc_middle::ty::print::pretty::<impl rustc_middle::ty::context::TyCtxt>::def_path_str_with_substs::h735850dce207a367
  21: 0xb6261960 - rustc_middle::ty::query::Query::describe::hf2e43136da6cb566
  22: 0xb647a900 - rustc_middle::ty::query::plumbing::<impl rustc_middle::ty::context::TyCtxt>::try_print_query_stack::he858c1f250faf89a
  23: 0xb3fafee4 - rustc_driver::report_ice::h1280f2762d7c80a3
  24: 0xb3bc7074 - std::panicking::rust_panic_with_hook::h58b73c3c20469f0b
  25: 0xb641be48 - std::panicking::begin_panic::ha97e79a759e28ac5
  26: 0xb64ad988 - rustc_middle::ty::context::TyCtxt::mk_const::h5c579b579a5d4e4e
  27: 0xb57ed2e4 - <rustc_middle::mir::Constant as serialize::serialize::Decodable>::decode::hcccd2e53e0fbdc9a
  28: 0xb57ece28 - <rustc_middle::mir::Operand as serialize::serialize::Decodable>::decode::hef40af16ce4eb25f
  29: 0xb57e6e90 - <(T10,T11) as serialize::serialize::Decodable>::decode::he0a546990f60f411
  30: 0xb57ef32c - <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode::ha59124684abb7737
  31: 0xb590f8e0 - serialize::serialize::Decoder::read_seq::h0bdeb39a663d95e4
  32: 0xb57f57f0 - <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode::h85192902e977ca51
  33: 0xb5911480 - serialize::serialize::Decoder::read_seq::h3d53abe3ecf9c8f7
  34: 0xb57e9910 - <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode::{{closure}}::h4f958f0814a98d03
  35: 0xb578444c - rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_optimized_mir::h1461bddf9273a65a
  36: 0xb581e1f4 - rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir::h8a524a5a40407959
  37: 0xb64a18fc - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute::h1153aaf480992394
  38: 0xb62b28e8 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h93c28e2c4e0992a3
  39: 0xb6418ae8 - rustc_data_structures::stack::ensure_sufficient_stack::hf6b20815eb074795
  40: 0xb631c05c - rustc_query_system::query::plumbing::get_query_impl::h6ddbca02528d39d6
  41: 0xb64923f0 - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir::hd8182a721d5f616f
  42: 0xb51f3b6c - rustc_mir::monomorphize::collector::collect_neighbours::hc8d196b66c6c2876
  43: 0xb51efdb8 - rustc_mir::monomorphize::collector::collect_items_rec::hde5cdc56f19e4b54
  44: 0xb51efe90 - rustc_mir::monomorphize::collector::collect_items_rec::hde5cdc56f19e4b54
  45: 0xb51efe90 - rustc_mir::monomorphize::collector::collect_items_rec::hde5cdc56f19e4b54
  46: 0xb51eedd0 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h6ebc2adeb0958363
  47: 0xb5435ea0 - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h86734da86fabc034
  48: 0xb44646bc - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute::h46959837fa33a65e
  49: 0xb4387854 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h358985cc3bdeae71
  50: 0xb446ddd0 - rustc_data_structures::stack::ensure_sufficient_stack::h7c4338a0c6c3d3cc
  51: 0xb440576c - rustc_query_system::query::plumbing::get_query_impl::h273d88f120260805
  52: 0xb44671a0 - rustc_codegen_ssa::base::codegen_crate::h966cb957dfed02a2
  53: 0xb43ccba8 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h15eea20020a9b9cd
  54: 0xb415b1f4 - rustc_interface::passes::start_codegen::h54a790bd0636dfc7
  55: 0xb41675c8 - rustc_middle::ty::context::tls::enter_global::h97c12a123ac35350
  56: 0xb41624c0 - rustc_interface::queries::Queries::ongoing_codegen::h879bdaeae4b0ca6f
  57: 0xb3f76194 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hc35c209e94217a6b
  58: 0xb3fbcef4 - rustc_ast::attr::with_globals::h3fc4a959b4267c29
  59: 0xb3fc6c6c - std::sys_common::backtrace::__rust_begin_short_backtrace::h6b300124e5ce2ac5
  60: 0xb3f78e2c - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a101086f2a6e1c9
  61: 0xb3bced80 - std::sys::unix::thread::Thread::new::thread_start::h71da00e0bb15a647

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0 running on armv7-unknown-linux-gnueabihf

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z unstable-options -C prefer-dynamic -C rpath -C debuginfo=0 -C linker=arm-linux-gnueabihf-gcc

query stack during panic:
thread panicked while processing panic. aborting.

------------------------------------------
~~~~

**Comment by infinity0** [comment]
Upon further investigation it seems that these failures also occur on [32-bit powerpc](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=powerpc&ver=1.45.0%2Bdfsg1-1&stamp=1596667509&raw=0) so not arm-specific.

**Comment by infinity0** [comment]
Most (possibly all) of the error messages contain `thread 'rustc' panicked at 'assertion failed: self.ptr <= self.end', /usr/src/rustc-1.45.0/src/libstd/macros.rs:13:23`, @jonas-schievink can you please add the relevant tags?

**Comment by jonas-schievink** [comment]
Isn't that just pointing to one of the `panic!`-family macros?

**Comment by tmiasko** [comment]
The failing assertion looks like an issue that was fixed by #73237.

**Comment by infinity0** [comment]
@jonas-schievink from the history of some of those tests, they were moved from run-fail so I think panicing is the desired behaviour, however it appears in this case the panic is causing an ICE rather than "failing successfully".

@tmiasko OK thanks, I'll backport that and see if it solves the problem.

**Comment by jonas-schievink** [comment]
This is a metadata panic, actually

**Comment by infinity0** [comment]
@tmiasko thanks, backporting #73237 directly on top of 1.45.0 seems to fix these failures. I also had to include 5ceff6b96af9a21e044545b9e064433feccaf659.
