### ISSUE TITLE
[ICE] in inner const generic function 

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#75299]
```rust
#![feature(const_generics, box_syntax)]
#![allow(incomplete_features)]
fn main() {
    fn foo<const N: usize>() {
        box [0; N];
    }
    foo::<1>();
}
```

Compiled with:
`rustc -Z mir-opt-level=3 bug.rs`

Using:
`rustc 1.47.0-nightly (09f4c9f50 2020-08-07) running on x86_64-pc-windows-gnu`

Gives:
```rust
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3 ~ bug[317d]::main[0]), const_param_did: None }) (
encountered `Assign` statement with incompatible types:
left-hand side has type: [i32; 1]
right-hand side has type: [i32; N]
 --> bug.rs:5:13
  |
5 |         box [0; N];
  |             ^^^^^^
  |
  = note: delayed at src\librustc_mir\transform\validate.rs:140:36

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src\librustc_errors\lib.rs:366:17
```

**Comment by leonardo-m** [comment]
The problem is not tied to box:

```rust
#![feature(const_generics)]
#![allow(incomplete_features)]
fn main() {
    fn foo<const N: usize>() -> [u8; N] {
        [0; N]
    }
    let _x = foo::<1>();
}
```

**Comment by Alexendoo** [comment]
No longer ICEs after #76376

**Comment by leonardo-m** [comment]
Ops, sorry, I reopen until a test is present.
