### ISSUE TITLE
`_lzma.LZMAError: Corrupt input data` occured when try to test the compiler

### ISSUE THREAD

**Issue by p0lunin** [rust-lang/rust#75456]
I try to test compiler usign command `python x.py --stage 1 test src/test/ui/issues` and see the output:
```
Updating only changed submodules
Submodules updated in 0.15 seconds
extracting C:\Users\polun\RiderProjects\rust\build\cache\2020-07-16\rust-std-beta-x86_64-pc-windows-msvc.tar.xz
extracting C:\Users\polun\RiderProjects\rust\build\cache\2020-07-16\rustc-beta-x86_64-pc-windows-msvc.tar.xz
Traceback (most recent call last):
  File "x.py", line 11, in <module>
    bootstrap.main()
  File "C:\Users\polun\RiderProjects\rust\src\bootstrap\bootstrap.py", line 1009, in main
    bootstrap(help_triggered)
  File "C:\Users\polun\RiderProjects\rust\src\bootstrap\bootstrap.py", line 973, in bootstrap
    build.download_stage0()
  File "C:\Users\polun\RiderProjects\rust\src\bootstrap\bootstrap.py", line 391, in download_stage0
    self._download_stage0_helper(filename, "rustc", tarball_suffix)
  File "C:\Users\polun\RiderProjects\rust\src\bootstrap\bootstrap.py", line 446, in _download_stage0_helper
    unpack(tarball, tarball_suffix, self.bin_root(), match=pattern, verbose=self.verbose)
  File "C:\Users\polun\RiderProjects\rust\src\bootstrap\bootstrap.py", line 112, in unpack
    for member in tar.getnames():
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\tarfile.py", line 1795, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\tarfile.py", line 1787, in getmembers
    self._load()        # all members, we first have to
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\tarfile.py", line 2372, in _load
    tarinfo = self.next()
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\tarfile.py", line 2303, in next
    self.fileobj.seek(self.offset - 1)
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\lzma.py", line 253, in seek
    return self._buffer.seek(offset, whence)
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "C:\Users\polun\AppData\Local\Programs\Python\Python38\lib\_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
_lzma.LZMAError: Corrupt input data
```
OS: Windows 10.0 2004
rustc: (last)[https://github.com/rust-lang/rust/tree/cee14d8c300feb2ac2a949848911bf4c3b143e70]

**Comment by jonas-schievink** [comment]
Try deleting those files, they might just be corrupted during download

**Comment by p0lunin** [comment]
It really is, thanks.
