### ISSUE TITLE
rust will not compile natively on RPi4 aarch64

### ISSUE THREAD

**Issue by juanitotc** [rust-lang/rust#75624]
I've compiled rust-1.42.0 natively on x86, x86_64 and RPi4 armv7 hardware, but cannot get it to compile on RPi4 aarch64.

Using clang/llvm-10.0.0, gcc-10.1.0, glibc-2.31, it fails as per below, what is the best way to trouble-shoot?

```
   Compiling rustc_parse v0.0.0 (/usr/src/rustc-1.42.0-src/src/librustc_parse)
error: could not compile `rustc`.

Caused by:
  process didn't exit successfully: `/usr/src/rustc-1.42.0-src/build/bootstrap/debug/rustc --edition=2018 --crate-name rustc src/librustc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C debuginfo=0 -C metadata=a16bfefcad7824a3 -C extra-filename=-a16bfefcad7824a3 --out-dir /usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps --target aarch64-unknown-linux-gnu -L dependency=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps -L dependency=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/release/deps --extern arena=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libarena-7b6ed11467491f3d.rmeta --extern backtrace=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libbacktrace-a9ff0f93d36165e5.rmeta --extern bitflags=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libbitflags-eae63fb24b6bd26a.rmeta --extern byteorder=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libbyteorder-4562f6783268a106.rmeta --extern chalk_engine=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libchalk_engine-3bb9470d6b2e87ff.rmeta --extern fmt_macros=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libfmt_macros-c0f44836778f0030.rmeta --extern graphviz=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libgraphviz-f23ebc288d688733.rmeta --extern jobserver=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libjobserver-7df4e10db22d2370.rmeta --extern log=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/liblog-cb21ee8d6c104ce8.rmeta --extern measureme=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libmeasureme-5da903ef2a57c11a.rmeta --extern parking_lot=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libparking_lot-35be582bc34dd39d.rmeta --extern polonius_engine=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libpolonius_engine-0b2097db24b64508.rmeta --extern rustc_rayon=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_rayon-72aa1e78bce9746d.rmeta --extern rustc_rayon_core=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_rayon_core-5bf14c00d46eb414.rmeta --extern rustc_apfloat=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_apfloat-dfef8aecde167ce0.rmeta --extern rustc_data_structures=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_data_structures-642b000c7910b70b.rmeta --extern rustc_errors=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_errors-f6e2934f4310599a.rmeta --extern rustc_feature=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_feature-f80f1fcb630442b8.rmeta --extern rustc_hir=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_hir-5d549d097fdacd9a.rmeta --extern rustc_index=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_index-32e3d918985ad9a0.rmeta --extern rustc_macros=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/release/deps/librustc_macros-269b579d26bca1dd.so --extern rustc_session=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_session-4c0a22405a3e574e.rmeta --extern rustc_span=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_span-e503f1ebb99ed23e.rmeta --extern rustc_target=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_target-6c22cf12287cf97f.rmeta --extern scoped_tls=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libscoped_tls-c1d289c4da076b0d.rmeta --extern rustc_serialize=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libserialize-6772459ab2f065d8.rmeta --extern smallvec=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libsmallvec-16a8b3a46d271f70.rmeta --extern syntax=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libsyntax-184845c3ccf56d16.rmeta -C link-args=-lffi -C link-args=-lffi -C link-args=-lffi --cfg=bootstrap -Zexternal-macro-backtrace -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Zbinary-dep-depinfo -L native=/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/build/backtrace-sys-8b250dfb11ed9d7c/out` (signal: 9, SIGKILL: kill)

command did not execute successfully: "/usr/src/rustc-1.42.0-src/build/aarch64-unknown-linux-gnu/stage0/bin/cargo" "build" "-Zconfig-profile" "--target" "aarch64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "1" "--release" "--features" " llvm" "--manifest-path" "/usr/src/rustc-1.42.0-src/src/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/usr/src/rustc-1.42.0-src/src/bootstrap/bootstrap.py", line 951, in main
    bootstrap(help_triggered)
  File "/usr/src/rustc-1.42.0-src/src/bootstrap/bootstrap.py", line 937, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/usr/src/rustc-1.42.0-src/src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /usr/src/rustc-1.42.0-src/build/bootstrap/debug/bootstrap -j 1 -v build --exclude src/tools/miri
```

**Comment by jonas-schievink** [comment]
You're probably running out of memory

**Comment by juanitotc** [comment]
Thanks - the build is still on-going, but since it got much further, I presume that a lack of ram was the problem.

Strange that I don't recall having to activate a swap file for the RPi4 armv7 build.

Surely the error message could indicate an out of memory event?

**Comment by jonas-schievink** [comment]
No, Linux just kills the compiler via the OOM killer, there's no way to catch that.

**Comment by juanitotc** [comment]
Anyway it compiled and works :)
