### ISSUE TITLE
Retrieving closure signature causes panic

### ISSUE THREAD

**Issue by FabianWolff** [rust-lang/rust#75662]
I have been trying to write a compiler plugin which, at some point, has to retrieve the signature of a closure. There seems to be a recommended way of doing it, described [here](https://github.com/rust-lang/rust/blob/4717cf2fcbde585d81c47417b1fb921572a3c537/src/librustc_typeck/collect.rs#L1576), but calling this function [as described](https://github.com/FabianWolff/rustc-cl-sig-mwe/blob/ce9b269bcc8701d9e4cd26bd69cd5ff77868f462/src/bin/cl-mwe.rs#L49) leads to a panic:
```
error: internal compiler error: src/librustc_middle/ty/sty.rs:419:18: closure_sig_as_fn_ptr_ty is not a fn-ptr: Param(<closure_signature>/#1)
```
From my understanding, the issue stems from [here](https://github.com/rust-lang/rust/blob/4717cf2fcbde585d81c47417b1fb921572a3c537/src/librustc_typeck/collect.rs#L1420), where "junk" is created instead of the actual signature, but of course I might be wrong.

### Code

A minimal working example for the plugin side is [here](https://github.com/FabianWolff/rustc-cl-sig-mwe); the input code might look like this:
```Rust
fn main() {
    |_a: i32, _b: i32| {};
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (7e6d6e5f5 2020-08-16)
binary: rustc
commit-hash: 7e6d6e5f535321c2223f044caba16f97b825009c
commit-date: 2020-08-16
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0
```

### Error output

```
error: internal compiler error: src/librustc_middle/ty/sty.rs:419:18: closure_sig_as_fn_ptr_ty is not a fn-ptr: Param(<closure_signature>/#1)

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (7e6d6e5f5 2020-08-16) running on x86_64-unknown-linux-gnu
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src/librustc_middle/ty/sty.rs:419:18: closure_sig_as_fn_ptr_ty is not a fn-ptr: Param(<closure_signature>/#1)

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:918:9
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_middle::ty::sty::ClosureSubsts::sig
   9: <cl_mwe::ClVisitor as rustc_hir::intravisit::Visitor>::visit_expr
             at ./src/bin/cl-mwe.rs:49
  10: rustc_hir::intravisit::walk_stmt
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:1051
  11: rustc_hir::intravisit::Visitor::visit_stmt
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:340
  12: rustc_hir::intravisit::walk_block
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:1041
  13: rustc_hir::intravisit::Visitor::visit_block
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:337
  14: rustc_hir::intravisit::walk_expr
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:1125
  15: <cl_mwe::ClVisitor as rustc_hir::intravisit::Visitor>::visit_expr
             at ./src/bin/cl-mwe.rs:56
  16: rustc_hir::intravisit::walk_body
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:486
  17: rustc_hir::intravisit::Visitor::visit_body
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:303
  18: rustc_hir::intravisit::Visitor::visit_nested_body
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:289
  19: rustc_hir::intravisit::walk_fn
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:927
  20: rustc_hir::intravisit::Visitor::visit_fn
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:370
  21: rustc_hir::intravisit::walk_item
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:561
  22: rustc_hir::intravisit::Visitor::visit_item
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:299
  23: <rustc_hir::intravisit::DeepVisitor<V> as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_item
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/intravisit.rs:57
  24: rustc_hir::hir::Crate::visit_all_item_likes
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_hir/hir.rs:678
  25: <cl_mwe::ClCallback as rustc_driver::Callbacks>::after_analysis::{{closure}}
             at ./src/bin/cl-mwe.rs:72
  26: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_interface/passes.rs:738
  27: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_middle/ty/context.rs:1731
  28: rustc_middle::ty::context::tls::set_tlv
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_middle/ty/context.rs:1715
  29: rustc_middle::ty::context::tls::enter_context
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_middle/ty/context.rs:1731
  30: rustc_interface::passes::QueryContext::enter
             at /rustc/7e6d6e5f535321c2223f044caba16f97b825009c/src/librustc_interface/passes.rs:738
  31: <cl_mwe::ClCallback as rustc_driver::Callbacks>::after_analysis
             at ./src/bin/cl-mwe.rs:67
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  33: rustc_span::with_source_map
  34: rustc_interface::interface::create_compiler_and_run
  35: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (7e6d6e5f5 2020-08-16) running on x86_64-unknown-linux-gnu
```

</p>
</details>

**Comment by Qwaz** [comment]
I had the same problem. I solved it by calling `.as_closure().sig()` on `ty = instance.ty(tcx, ParamEnv::reveal_all())` instead of `ty = tcx.type_of(instance.def_id())`. This was fine for my usage as I only needed the `Unsafety` part of the signature.

**Comment by Enselic** [comment]
Triage: I can reproduce the ICE with `nightly-2020-08-17`, but I get a bunch of compile errors when trying to compile the plugin against latest nightly. The first error is:

```
error[E0433]: failed to resolve: could not find `NestedVisitorMap` in `intravisit`
  --> src/bin/cl-mwe.rs:28:21
   |
28 |         intravisit::NestedVisitorMap::OnlyBodies(self.hir)
   |                     ^^^^^^^^^^^^^^^^ could not find `NestedVisitorMap` in `intravisit`
```

Can the ICE still be reproduced if the plugin is ported to the current compiler plugin API?

**Comment by jackh726** [comment]
I'm going to close this, as I think we have very minimal to no support for interacting with the compiler internals.
