### ISSUE TITLE
rustc panic: "Unable to fulfull trait ..." (cargo doc, stable)

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/rust#76660]
```
active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.46.0 (04488afe3 2020-08-24)
```
Steps to reproduce:
1) cd in https://github.com/hecrj/iced/tree/4f2962d73f3bdeeca8a11817e404c45e91e2c2cc/examples/game_of_life
2) `cargo doc --open`

```
thread 'rustc' panicked at 'Unable to fulfill trait DefId(2:1968 ~ core[e9de]::marker[0]::Unpin[0]) for 'lines::Lines<'a, 'b, L, F, S>': [FulfillmentError(Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { substs: [S], item_def_id: DefId(2:4990 ~ core[e9de]::iter[0]::traits[0]::iterator[0]::Iterator[0]::Item[0]) }, section::SectionText<'_>)), depth=3),Ambiguity)]', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  13: rustc_trait_selection::traits::auto_trait::AutoTraitFinder::find_auto_trait_generics::{{closure}}::{{closure}}
  14: rustc_infer::infer::InferCtxtBuilder::enter
  15: rustc_trait_selection::traits::auto_trait::AutoTraitFinder::find_auto_trait_generics
  16: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: rustdoc::clean::utils::get_auto_trait_and_blanket_impls
  19: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::fold::DocFolder>::fold_item
  20: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  21: rustdoc::fold::DocFolder::fold_inner_recur
  22: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::fold::DocFolder>::fold_item
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  24: rustdoc::fold::DocFolder::fold_inner_recur
  25: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::fold::DocFolder>::fold_item
  26: rustdoc::passes::collect_trait_impls::collect_trait_impls
  27: rustc_middle::ty::context::tls::enter_global
  28: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  29: rustc_span::with_source_map
  30: rustc_interface::interface::create_compiler_and_run
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: rustc_driver::catch_fatal_errors
  33: rustdoc::main_options
  34: scoped_tls::ScopedKey<T>::set
  35: rustc_ast::attr::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 Documenting guillotiere v0.5.1
error: Could not document `glyph_brush_layout`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name glyph_brush_layout /home/erlend/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush_layout-0.2.0/src/lib.rs --cap-lints allow -o /home/erlend/code/iced/target/doc --error-format=json --json=diagnostic-rendered-ansi -L dependency=/home/erlend/code/iced/target/debug/deps --extern ab_glyph=/home/erlend/code/iced/target/debug/deps/libab_glyph-11e87b3b5c93e967.rmeta --extern approx=/home/erlend/code/iced/target/debug/deps/libapprox-4ea0b68a72353845.rmeta --extern xi_unicode=/home/erlend/code/iced/target/debug/deps/libxi_unicode-5ef2abf21606e58b.rmeta` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
```

**Comment by jonas-schievink** [comment]
Fixed in nightly.
