### ISSUE TITLE
Compiler error in rustc_span::source_map::SourceMap::lookup_line::habdc26824ed25798

### ISSUE THREAD

**Issue by a1ph** [rust-lang/rust#76697]
Sorry, cannot provide source code, but here's the stack trace:

```
rustc --version --verbose
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0

(gdb) info registers
rax            0x7fcb0056d950	140509860780368
rbx            0x1	1
rcx            0x0	0
rdx            0x14e9	5353
rsi            0xe7a	3706
rdi            0x1	1
rbp            0x14e9	0x14e9
rsp            0x7fcb0056d920	0x7fcb0056d920
r8             0xffffffffffffffff	-1
r9             0x7fcae7db6380	140509450036096
r10            0x7fcaff87ca80	140509847210624
r11            0x1	1
r12            0xfff	4095
r13            0x7fcb0056dd88	140509860781448
r14            0x0	0
r15            0x7fcaff83c010	140509846945808
rip            0x7fcb09c868f2	0x7fcb09c868f2 <rustc_span::source_map::SourceMap::lookup_line::habdc26824ed25798+338>
eflags         0x10297	[ CF PF AF SF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) bt
#0  0x00007fcb09c868f2 in rustc_span::source_map::SourceMap::lookup_line::habdc26824ed25798 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#1  0x00007fcb073e1ef5 in rustc_codegen_llvm::debuginfo::metadata::VariantInfo::source_info::h9d98ed5be7f87c02 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#2  0x00007fcb074101b7 in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::h85e92cdad7f986ee ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#3  0x00007fcb073e0cdf in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#4  0x00007fcb073dbae9 in rustc_codegen_llvm::debuginfo::metadata::RecursiveTypeDescription::finalize::h6b402576358cf512 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#5  0x00007fcb073dd63c in rustc_codegen_llvm::debuginfo::metadata::type_metadata::h3875d4681e92778b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#6  0x00007fcb0741391f in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::hf67dbb98fe2a81a9 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#7  0x00007fcb073e0237 in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#8  0x00007fcb073dbae9 in rustc_codegen_llvm::debuginfo::metadata::RecursiveTypeDescription::finalize::h6b402576358cf512 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#9  0x00007fcb073de1d7 in rustc_codegen_llvm::debuginfo::metadata::type_metadata::h3875d4681e92778b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#10 0x00007fcb0740e49c in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::h5e914e2d218fb781 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#11 0x00007fcb073e02e5 in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#12 0x00007fcb074100d1 in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::h85e92cdad7f986ee ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#13 0x00007fcb073e0cdf in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#14 0x00007fcb073dbae9 in rustc_codegen_llvm::debuginfo::metadata::RecursiveTypeDescription::finalize::h6b402576358cf512 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#15 0x00007fcb073dd63c in rustc_codegen_llvm::debuginfo::metadata::type_metadata::h3875d4681e92778b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#16 0x00007fcb0741391f in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::hf67dbb98fe2a81a9 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#17 0x00007fcb073e0237 in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#18 0x00007fcb073dbae9 in rustc_codegen_llvm::debuginfo::metadata::RecursiveTypeDescription::finalize::h6b402576358cf512 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#19 0x00007fcb073de1d7 in rustc_codegen_llvm::debuginfo::metadata::type_metadata::h3875d4681e92778b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#20 0x00007fcb0740e49c in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::h5e914e2d218fb781 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#21 0x00007fcb073e02e5 in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#22 0x00007fcb074100d1 in _$LT$core..iter..adapters..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::h85e92cdad7f986ee ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#23 0x00007fcb073e0cdf in rustc_codegen_llvm::debuginfo::metadata::MemberDescriptionFactory::create_member_descriptions::hcb289e03244a8efb () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#24 0x00007fcb073dbae9 in rustc_codegen_llvm::debuginfo::metadata::RecursiveTypeDescription::finalize::h6b402576358cf512 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#25 0x00007fcb073dd63c in rustc_codegen_llvm::debuginfo::metadata::type_metadata::h3875d4681e92778b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#26 0x00007fcb073de84d in rustc_codegen_llvm::debuginfo::metadata::type_metadata::_$u7b$$u7b$closure$u7d$$u7d$::h1df9e98365860f90 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#27 0x00007fcb073dd7e6 in rustc_codegen_llvm::debuginfo::metadata::type_metadata::h3875d4681e92778b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#28 0x00007fcb072f0d10 in rustc_codegen_llvm::debuginfo::_$LT$impl$u20$rustc_codegen_ssa..traits..debuginfo..DebugInfoMethods$u20$for$u20$rustc_codegen_llvm..context..CodegenCx$GT$::create_function_debug_context::get_function_signature::h88eba3b656dd158b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#29 0x00007fcb0734531c in rustc_codegen_llvm::debuginfo::_$LT$impl$u20$rustc_codegen_ssa..traits..debuginfo..DebugInfoMethods$u20$for$u20$rustc_codegen_llvm..context..CodegenCx$GT$::create_function_debug_context::h149048cd9e3dfb3d ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#30 0x00007fcb07420c83 in rustc_codegen_ssa::mir::codegen_mir::h0a029c5f5cb65c7b () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#31 0x00007fcb073681bb in _$LT$rustc_middle..mir..mono..MonoItem$u20$as$u20$rustc_codegen_ssa..mono_item..MonoItemExt$GT$::define::h189831e6139b7fc4 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#32 0x00007fcb072ef71b in rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::hebf37019aa985243 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#33 0x00007fcb073094a9 in rustc_middle::dep_graph::_$LT$impl$u20$rustc_query_system..dep_graph..DepKind$u20$for$u20$rustc_middle..dep_graph..dep_node..DepKind$GT$::with_deps::hc7993c2db4009218 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#34 0x00007fcb07361260 in rustc_query_system::dep_graph::graph::DepGraph$LT$K$GT$::with_task::h4e02fbe6cd440f76 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#35 0x00007fcb072ef225 in rustc_codegen_llvm::base::compile_codegen_unit::hc44825254ad94c99 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#36 0x00007fcb0744c263 in rustc_codegen_ssa::base::codegen_crate::he85cd82bcdda5938 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#37 0x00007fcb0741bd45 in _$LT$rustc_codegen_llvm..LlvmCodegenBackend$u20$as$u20$rustc_codegen_ssa..traits..backend..CodegenBackend$GT$::codegen_crate::h5ffaae01a695dc25 ()
   from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#38 0x00007fcb071bc100 in rustc_session::utils::_$LT$impl$u20$rustc_session..session..Session$GT$::time::h5b48e80e1cf714c8 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
---Type <return> to continue, or q <return> to quit---
#39 0x00007fcb07113f38 in rustc_interface::passes::start_codegen::h7c8947b42ff1b1a6 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#40 0x00007fcb07134416 in rustc_middle::ty::context::tls::enter_global::h6daccd4a7f498cd0 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#41 0x00007fcb0712fbde in rustc_interface::queries::Queries::ongoing_codegen::h36555eafb64d9795 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#42 0x00007fcb06f30653 in rustc_interface::queries::_$LT$impl$u20$rustc_interface..interface..Compiler$GT$::enter::hd9d325143dad59c2 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#43 0x00007fcb06fcf8e7 in rustc_span::with_source_map::h8932c000c7b08879 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#44 0x00007fcb06f31826 in rustc_interface::interface::create_compiler_and_run::h442b6cbb52362b36 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#45 0x00007fcb06f5bf1d in scoped_tls::ScopedKey$LT$T$GT$::set::h8938bb49c90cd057 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#46 0x00007fcb06f82272 in std::sys_common::backtrace::__rust_begin_short_backtrace::hde285eb3c6f4aaa5 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#47 0x00007fcb06f3f70e in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hbbf6021168227a97 () from /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-1cd905f603d5b1d4.so
#48 0x00007fcb0681acfa in call_once<(),FnOnce<()>> () at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
#49 call_once<(),alloc::boxed::Box<FnOnce<()>>> () at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
#50 std::sys::unix::thread::Thread::new::thread_start::h276e6ca033938925 () at src/libstd/sys/unix/thread.rs:87
#51 0x00007fcb06580184 in start_thread (arg=0x7fcb0057f700) at pthread_create.c:312
#52 0x00007fcb05ea103d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by jonas-schievink** [comment]
What's the actual error? Does it also happen on nightly?

**Comment by a1ph** [comment]
The error is:
```
(signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It's not reproducible on todays nightly.
```
# rustc --version --verbose
rustc 1.48.0-nightly (7402a3944 2020-09-13)
binary: rustc
commit-hash: 7402a394471a6738a40fea7d4f1891666e5a80c5
commit-date: 2020-09-13
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

**Comment by jonas-schievink** [comment]
Okay, in that case, closing as fixed on nightly
