### ISSUE TITLE
Lint docs failed to build

### ISSUE THREAD

**Issue by o01eg** [rust-lang/rust#76702]
I tried to build rust right after https://github.com/rust-lang/rust/pull/76549 got merged and caught error:

```
    Finished release [optimized] target(s) in 6.81s
Copy "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/lint-docs" to "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/lint-docs"
        < ToolBuild { compiler: Compiler { stage: 0, host: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None } }, target: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None }, tool: "lint-docs", path: "src/tools/lint-docs", mode: ToolBootstrap, is_optional_tool: false, source_type: InTree, extra_features: [] }
      < LintDocs { compiler: Compiler { stage: 0, host: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None } }, target: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None } }
      c Assemble { target_compiler: Compiler { stage: 0, host: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None } } }
running: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/lint-docs" "--src" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/compiler" "--out" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/md-doc/rustc/src/lints" "--rustc" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--verbose"
compiling lint ill_formed_attribute_input
error: failed to test example in lint docs for `ill_formed_attribute_input` in /tmp/portage/dev-lang/rust-9999/work/rust-git-src/compiler/rustc_session/src/lint/builtin.rs:12: did not find lint `ill_formed_attribute_input` in output of example, got:



command did not execute successfully: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/lint-docs" "--src" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/compiler" "--out" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/md-doc/rustc/src/lints" "--rustc" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--verbose"
expected success, got: exit code: 1


Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 1061, in main
    bootstrap(help_triggered)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 1047, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/bootstrap install -vv --config=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/config.toml -j7
```

### Meta

config.toml:
```toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
ninja = true
targets = "X86;Mips;NVPTX;RISCV;BPF;AArch64;WebAssembly"
experimental-targets = ""
link-shared = false
[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["i686-unknown-linux-gnu","x86_64-unknown-linux-gnu","wasm32-unknown-unknown"]
docs = true
compiler-docs = true
submodules = false
python = "python3.7"
locked-deps = true
vendor = false
extended = true
tools = ["rust-analyzer","rustfmt","rls","miri","clippy","cargo",]
verbose = 2
sanitizers = true
profiler = false
cargo-native-static = false
[install]
prefix = "/usr"
libdir = "lib64/rust-9999"
docdir = "share/doc/rust-9999"
mandir = "share/rust-9999/man"
[rust]
optimize = true
debug = false
debug-assertions = false
debuginfo-level-rustc = 0
backtrace = true
incremental = false
default-linker = "x86_64-pc-linux-gnu-gcc"
parallel-compiler = false
rpath = false
verbose-tests = true
optimize-tests = true
codegen-tests = true
dist-src = false
ignore-git = false
lld = true
backtrace-on-ice = true
jemalloc = false
deny-warnings = false
[dist]
src-tarball = false
[target.i686-unknown-linux-gnu]
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ar = "x86_64-pc-linux-gnu-ar"
[target.x86_64-unknown-linux-gnu]
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ar = "x86_64-pc-linux-gnu-ar"
[target.wasm32-unknown-unknown]
linker = "rust-lld"
```

**Comment by jyn514** [comment]
cc @ehuss

**Comment by ehuss** [comment]
What command did you run?

**Comment by o01eg** [comment]
```shell
./x.py install -vv --config=config.toml -j7
```
