### ISSUE TITLE
Various ICEs when mis-implementing `drop_in_place` lang item

### ISSUE THREAD

**Issue by bossmc** [rust-lang/rust#77109]
I've found two ways to ICE when trying to provide a `drop_in_place` implementation (for some `no_core` code) - I've raised as one issue, because I think they're basically the same issue (rustc making assumptions about language item prototypes) but I'm happy to break up if preferred.

### Code

```Rust
#[lang = "drop_in_place"]
#[inline]
unsafe fn drop_in_place(_to_drop: *mut i32) {}
```

```Rust
#[lang = "drop_in_place"]
#[inline]
unsafe fn drop_in_place<T: ?Sized, U: ?Sized>(_to_drop: *mut T, _extra: U) {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (0da580074 2020-09-22) running on x86_64-unknown-linux-gnu
```

### Error output

First example (too few generics):

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/0da58007451a154da2480160429e1604a1f5f0ec/compiler/rustc_middle/src/ty/subst.rs:302:43
```
<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0da58007451a154da2480160429e1604a1f5f0ec/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/0da58007451a154da2480160429e1604a1f5f0ec/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/0da58007451a154da2480160429e1604a1f5f0ec/library/core/src/panicking.rs:62
   3: rustc_ty::instance::inner_resolve_instance
   4: rustc_ty::instance::resolve_instance
   5: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::resolve_instance>::compute
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   7: rustc_data_structures::stack::ensure_sufficient_stack
   8: rustc_query_system::query::plumbing::get_query_impl
   9: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  10: rustc_middle::ty::instance::Instance::resolve_drop_in_place
  11: rustc_mir::monomorphize::collector::collect_items_rec
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_mir::monomorphize::collector::collect_crate_mono_items
  14: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  15: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::get_query_impl
  19: rustc_codegen_ssa::base::codegen_crate
  20: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  21: rustc_interface::passes::QueryContext::enter
  22: rustc_interface::queries::Queries::ongoing_codegen
  23: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  24: rustc_span::with_source_map
  25: rustc_interface::interface::create_compiler_and_run
  26: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

</p>
</details>

Latter example (too many generics):

```
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:529:17: type parameter `U/#1` (U/1) out of range when substituting, substs=[u32]

thread 'rustc' panicked at 'Box<Any>', /rustc/0da58007451a154da2480160429e1604a1f5f0ec/compiler/rustc_errors/src/lib.rs:891:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::span_bug
   2: rustc_errors::Handler::span_bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::span_bug_fmt
   8: <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
   9: rustc_middle::ty::fold::TypeFoldable::fold_with
  10: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with
  11: <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  12: rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::subst_and_normalize_erasing_regions
  13: rustc_ty::instance::inner_resolve_instance
  14: rustc_ty::instance::resolve_instance
  15: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::resolve_instance>::compute
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::get_query_impl
  19: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  20: rustc_middle::ty::instance::Instance::resolve_drop_in_place
  21: rustc_mir::monomorphize::collector::collect_items_rec
  22: rustc_session::utils::<impl rustc_session::session::Session>::time
  23: rustc_mir::monomorphize::collector::collect_crate_mono_items
  24: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  25: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::get_query_impl
  29: rustc_codegen_ssa::base::codegen_crate
  30: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  31: rustc_interface::passes::QueryContext::enter
  32: rustc_interface::queries::Queries::ongoing_codegen
  33: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  34: rustc_span::with_source_map
  35: rustc_interface::interface::create_compiler_and_run
  36: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.
```

</p>
</details>

**Comment by jonas-schievink** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/9307, which is more general

**Comment by bossmc** [comment]
Ah, thanks @jonas-schievink that's a better issue (maybe this one just adds some motivation/justification to that one)
