### ISSUE TITLE
Two UI tests fail on master with macOS

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#77424]
For some reason, I've had two UI tests fail recently on master (or other branches):

```
failures:
    [ui] ui/backtrace-debuginfo.rs
    [ui] ui/issues/issue-45731.rs

test result: FAILED. 10760 passed; 2 failed; 79 ignored; 0 measured; 0 filtered out
```

The error output from `x.py` is over 400 lines and seems to have a lot of explicit panics.

<details>
<summary>Full x.py output</summary>

```
failures:

---- [ui] ui/backtrace-debuginfo.rs stdout ----

error: test run failed!
status: exit code: 101
command: "/Users/user/rust/build/x86_64-apple-darwin/test/ui/backtrace-debuginfo/a"
stdout:
------------------------------------------
---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:125"]

--- stdout
backtrace-debuginfo.rs:125
backtrace-debuginfo.rs:189

--- stderr
test case 0
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:86:5
stack backtrace:
   0:        0x10091673b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x1009a5585 - core::fmt::write::h9ed04393291ac92a
   2:        0x100957328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10091654a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x100932d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x100932b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x1009331b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x10089704d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x100896f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x1008a8bf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x10089e02b - backtrace_debuginfo::inner::h3e06eb48f40b8b80
  11:        0x10089e891 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  12:        0x10089f4c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  13:        0x1008971ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  14:        0x100896f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  15:        0x100896fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  16:        0x100931105 - std::panicking::try::hf2178c705006d454
  17:        0x10093d049 - std::rt::lang_start_internal::hfba044b21b8e1869
  18:        0x100896fae - std::rt::lang_start::h95a045a81aad1638
  19:        0x10089f556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:125"]

--- stdout
backtrace-debuginfo.rs:125
backtrace-debuginfo.rs:189

--- stderr
test case 1
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:87:5
stack backtrace:
   0:        0x10311973b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x1031a8585 - core::fmt::write::h9ed04393291ac92a
   2:        0x10315a328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10311954a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x103135d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x103135b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x1031361b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x10309904d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x103098f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x1030aabf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x1030a012b - backtrace_debuginfo::inner::h3e06eb48f40b8b80
  11:        0x1030a0891 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  12:        0x1030a14c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  13:        0x1030991ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  14:        0x103098f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  15:        0x103098fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  16:        0x103134105 - std::panicking::try::hf2178c705006d454
  17:        0x103140049 - std::rt::lang_start_internal::hfba044b21b8e1869
  18:        0x103098fae - std::rt::lang_start::h95a045a81aad1638
  19:        0x1030a1556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:125", "backtrace-debuginfo.rs:88", "backtrace-debuginfo-aux.rs:6"]

--- stdout
backtrace-debuginfo-aux.rs:6
backtrace-debuginfo.rs:88
backtrace-debuginfo.rs:125
backtrace-debuginfo.rs:189

--- stderr
test case 2
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:89:9
stack backtrace:
   0:        0x10237673b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x102405585 - core::fmt::write::h9ed04393291ac92a
   2:        0x1023b7328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10237654a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x102392d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x102392b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x1023931b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x1022f704d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x1022f6f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x102308bf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x1022f6dab - backtrace_debuginfo::inner::{{closure}}::h140b2376f0673b2d
  11:        0x1022f6c66 - backtrace_debuginfo::aux::callback::hc70f628e7cdfe17a
  12:        0x1022fe08d - backtrace_debuginfo::inner::h3e06eb48f40b8b80
  13:        0x1022fe891 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  14:        0x1022ff4c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  15:        0x1022f71ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  16:        0x1022f6f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  17:        0x1022f6fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  18:        0x102391105 - std::panicking::try::hf2178c705006d454
  19:        0x10239d049 - std::rt::lang_start_internal::hfba044b21b8e1869
  20:        0x1022f6fae - std::rt::lang_start::h95a045a81aad1638
  21:        0x1022ff556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:125", "backtrace-debuginfo.rs:91", "backtrace-debuginfo-aux.rs:13"]

--- stdout
backtrace-debuginfo-aux.rs:13
backtrace-debuginfo.rs:91
backtrace-debuginfo.rs:125
backtrace-debuginfo.rs:189

--- stderr
test case 3
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:92:9
stack backtrace:
   0:        0x10a7ec73b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x10a87b585 - core::fmt::write::h9ed04393291ac92a
   2:        0x10a82d328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10a7ec54a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x10a808d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x10a808b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x10a8091b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x10a76f04d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x10a76ef18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x10a780bf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x10a7762cb - backtrace_debuginfo::inner::{{closure}}::h24b79ef638e543e4
  11:        0x10a775d56 - backtrace_debuginfo::aux::callback_inlined::h7461d73be30de2a4
  12:        0x10a776181 - backtrace_debuginfo::inner::h3e06eb48f40b8b80
  13:        0x10a776891 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  14:        0x10a7774c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  15:        0x10a76f1ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  16:        0x10a76ef51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  17:        0x10a76efd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  18:        0x10a807105 - std::panicking::try::hf2178c705006d454
  19:        0x10a813049 - std::rt::lang_start_internal::hfba044b21b8e1869
  20:        0x10a76efae - std::rt::lang_start::h95a045a81aad1638
  21:        0x10a777556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:126"]

--- stdout
backtrace-debuginfo.rs:126
backtrace-debuginfo.rs:189

--- stderr
test case 4
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:100:5
stack backtrace:
   0:        0x10630973b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x106398585 - core::fmt::write::h9ed04393291ac92a
   2:        0x10634a328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10630954a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x106325d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x106325b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x1063261b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x10628a04d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x106289f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x10629bbf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x1062913ab - backtrace_debuginfo::inner_inlined::he2e3ee617d0991b0
  11:        0x1062918d3 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  12:        0x1062924c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  13:        0x10628a1ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  14:        0x106289f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  15:        0x106289fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  16:        0x106324105 - std::panicking::try::hf2178c705006d454
  17:        0x106330049 - std::rt::lang_start_internal::hfba044b21b8e1869
  18:        0x106289fae - std::rt::lang_start::h95a045a81aad1638
  19:        0x106292556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:126"]

--- stdout
backtrace-debuginfo.rs:126
backtrace-debuginfo.rs:189

--- stderr
test case 5
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:101:5
stack backtrace:
   0:        0x10585b73b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x1058ea585 - core::fmt::write::h9ed04393291ac92a
   2:        0x10589c328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10585b54a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x105877d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x105877b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x1058781b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x1057dd04d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x1057dcf18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x1057eebf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x1057e44d6 - backtrace_debuginfo::inner_inlined::he2e3ee617d0991b0
  11:        0x1057e48d3 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  12:        0x1057e54c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  13:        0x1057dd1ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  14:        0x1057dcf51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  15:        0x1057dcfd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  16:        0x105876105 - std::panicking::try::hf2178c705006d454
  17:        0x105882049 - std::rt::lang_start_internal::hfba044b21b8e1869
  18:        0x1057dcfae - std::rt::lang_start::h95a045a81aad1638
  19:        0x1057e5556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:126", "backtrace-debuginfo.rs:109"]

--- stdout
backtrace-debuginfo.rs:109
backtrace-debuginfo.rs:126
backtrace-debuginfo.rs:189

--- stderr
test case 6
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:107:9
stack backtrace:
   0:        0x107a3a73b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x107ac9585 - core::fmt::write::h9ed04393291ac92a
   2:        0x107a7b328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x107a3a54a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x107a56d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x107a56b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x107a571b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x1079be04d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x1079bdf18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x1079cfbf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x1079c5833 - backtrace_debuginfo::inner_inlined::inner_further_inlined::h0aabe380fd0ff24c
  11:        0x1079c5438 - backtrace_debuginfo::inner_inlined::he2e3ee617d0991b0
  12:        0x1079c58d3 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  13:        0x1079c64c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  14:        0x1079be1ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  15:        0x1079bdf51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  16:        0x1079bdfd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  17:        0x107a55105 - std::panicking::try::hf2178c705006d454
  18:        0x107a61049 - std::rt::lang_start_internal::hfba044b21b8e1869
  19:        0x1079bdfae - std::rt::lang_start::h95a045a81aad1638
  20:        0x1079c6556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:126", "backtrace-debuginfo.rs:111", "backtrace-debuginfo-aux.rs:6"]

--- stdout
backtrace-debuginfo-aux.rs:6
backtrace-debuginfo.rs:111
backtrace-debuginfo.rs:126
backtrace-debuginfo.rs:189

--- stderr
test case 7
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:112:9
stack backtrace:
   0:        0x106fc473b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x107053585 - core::fmt::write::h9ed04393291ac92a
   2:        0x107005328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x106fc454a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x106fe0d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x106fe0b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x106fe11b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x106f4404d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x106f43f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x106f55bf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x106f43eeb - backtrace_debuginfo::inner_inlined::{{closure}}::h747935a98c68625a
  11:        0x106f43bf6 - backtrace_debuginfo::aux::callback::h3164eff58d61bcda
  12:        0x106f4b52c - backtrace_debuginfo::inner_inlined::he2e3ee617d0991b0
  13:        0x106f4b8d3 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  14:        0x106f4c4c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  15:        0x106f441ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  16:        0x106f43f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  17:        0x106f43fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  18:        0x106fdf105 - std::panicking::try::hf2178c705006d454
  19:        0x106feb049 - std::rt::lang_start_internal::hfba044b21b8e1869
  20:        0x106f43fae - std::rt::lang_start::h95a045a81aad1638
  21:        0x106f4c556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:126", "backtrace-debuginfo.rs:114", "backtrace-debuginfo-aux.rs:13"]

--- stdout
backtrace-debuginfo-aux.rs:13
backtrace-debuginfo.rs:114
backtrace-debuginfo.rs:126
backtrace-debuginfo.rs:189

--- stderr
test case 8
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:115:9
stack backtrace:
   0:        0x1049a773b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x104a36585 - core::fmt::write::h9ed04393291ac92a
   2:        0x1049e8328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x1049a754a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x1049c3d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x1049c3b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x1049c41b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x10492604d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x104925f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x104937bf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x10492d74b - backtrace_debuginfo::inner_inlined::{{closure}}::h86d10ea2ed224605
  11:        0x10492cdc6 - backtrace_debuginfo::aux::callback_inlined::h7da60bf6dd3293d2
  12:        0x10492d582 - backtrace_debuginfo::inner_inlined::he2e3ee617d0991b0
  13:        0x10492d8d3 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  14:        0x10492e4c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  15:        0x1049261ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  16:        0x104925f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  17:        0x104925fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  18:        0x1049c2105 - std::panicking::try::hf2178c705006d454
  19:        0x1049ce049 - std::rt::lang_start_internal::hfba044b21b8e1869
  20:        0x104925fae - std::rt::lang_start::h95a045a81aad1638
  21:        0x10492e556 - _main

---------------------------------------
trace does not match position list
still need to find ["backtrace-debuginfo.rs:189", "backtrace-debuginfo.rs:126", "backtrace-debuginfo.rs:120"]

--- stdout
backtrace-debuginfo.rs:120
backtrace-debuginfo.rs:126
backtrace-debuginfo.rs:189

--- stderr
test case 9
thread 'main' panicked at 'explicit panic', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:107:9
stack backtrace:
   0:        0x10fc3573b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h817ba919041bc66e
   1:        0x10fcc4585 - core::fmt::write::h9ed04393291ac92a
   2:        0x10fc76328 - std::io::Write::write_fmt::h8d0808c7c6564952
   3:        0x10fc3554a - std::sys_common::backtrace::print::h1e0bb963048b1caa
   4:        0x10fc51d14 - std::panicking::default_hook::{{closure}}::h078e52d97ca6d6cb
   5:        0x10fc51b2f - std::panicking::default_hook::hae15b5a7536d8322
   6:        0x10fc521b6 - std::panicking::rust_panic_with_hook::hd17928b126e49584
   7:        0x10fbb404d - std::panicking::begin_panic::{{closure}}::h5eb40b345a2582ba
   8:        0x10fbb3f18 - std::sys_common::backtrace::__rust_end_short_backtrace::h94802c8b24526f36
   9:        0x10fbc5bf3 - std::panicking::begin_panic::hc4870475b84c9b0d
  10:        0x10fbbb833 - backtrace_debuginfo::inner_inlined::inner_further_inlined::h0aabe380fd0ff24c
  11:        0x10fbbb603 - backtrace_debuginfo::inner_inlined::he2e3ee617d0991b0
  12:        0x10fbbb8d3 - backtrace_debuginfo::outer::hb72dd12c6666bd5b
  13:        0x10fbbc4c6 - backtrace_debuginfo::main::had8ee1c1e858a3e3
  14:        0x10fbb41ce - core::ops::function::FnOnce::call_once::h757b15c12a397906
  15:        0x10fbb3f51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a1edf10bee2007a
  16:        0x10fbb3fd4 - std::rt::lang_start::{{closure}}::h34d63719520289ab
  17:        0x10fc50105 - std::panicking::try::hf2178c705006d454
  18:        0x10fc5c049 - std::rt::lang_start_internal::hfba044b21b8e1869
  19:        0x10fbb3fae - std::rt::lang_start::h95a045a81aad1638
  20:        0x10fbbc556 - _main


------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'found some errors', /Users/user/rust/src/test/ui/backtrace-debuginfo.rs:179:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------------------------------------


---- [ui] ui/issues/issue-45731.rs stdout ----

error: test run failed!
status: exit code: 101
command: "/Users/user/rust/build/x86_64-apple-darwin/test/ui/issues/issue-45731/a"
stdout:
------------------------------------------

running 1 test
test simple_test ... FAILED

failures:

---- simple_test stdout ----
thread 'simple_test' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/user/rust/src/test/ui/issues/issue-45731.rs:18:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    simple_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out


------------------------------------------
stderr:
------------------------------------------

------------------------------------------



failures:
    [ui] ui/backtrace-debuginfo.rs
    [ui] ui/issues/issue-45731.rs

test result: FAILED. 10760 passed; 2 failed; 79 ignored; 0 measured; 0 filtered out

thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:354:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


command did not execute successfully: "/Users/user/rust/build/x86_64-apple-darwin/stage0-tools-bin/compiletest" "--compile-lib-path" "/Users/user/rust/build/x86_64-apple-darwin/stage1/lib" "--run-lib-path" "/Users/user/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib" "--rustc-path" "/Users/user/rust/build/x86_64-apple-darwin/stage1/bin/rustc" "--src-base" "/Users/user/rust/src/test/ui" "--build-base" "/Users/user/rust/build/x86_64-apple-darwin/test/ui" "--stage-id" "stage1-x86_64-apple-darwin" "--mode" "ui" "--target" "x86_64-apple-darwin" "--host" "x86_64-apple-darwin" "--llvm-filecheck" "/Users/user/rust/build/x86_64-apple-darwin/llvm/build/bin/FileCheck" "--nodejs" "/usr/local/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/Users/user/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/Users/user/rust/build/x86_64-apple-darwin/native/rust-test-helpers" "--docck-python" "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python" "--lldb-python" "/usr/bin/python3" "--lldb-version" "lldb version 10.0.0\n" "--lldb-python-dir" "<COULD NOT FIND PATH>" "--quiet" "--llvm-version" "11.0.0-rust-dev" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions frontendopenmp fuzzmutate globalisel gtest gtest_main hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target testingsupport textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xray" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" ""
expected success, got: exit code: 101


failed to run: /Users/user/rust/build/bootstrap/debug/bootstrap test src/test/ui/
Build completed unsuccessfully in 0:36:22
```

</details>

**Comment by camelid** [comment]
@LeSeulArtichaut thought this would have been caught by bors, but I think I saw that we've been having issues with the macOS build runners and they were disabled. Is that correct?

**Comment by jyn514** [comment]
Possibly related to https://github.com/rust-lang/rust/pull/73441 ?

**Comment by jyn514** [comment]
@camelid are you still running into this failure?
