### ISSUE TITLE
ICE from public Macro 2.0 + use crate as

### ISSUE THREAD

**Issue by DrMeepster** [rust-lang/rust#77475]
This does not happen if the macro is private or `pub(crate)`.

### Code

```Rust
#![feature(decl_macro)]
use crate as _;
pub macro ice(){}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (154f1f544 2020-10-02)
binary: rustc
commit-hash: 154f1f544dd68f7b53ff8d9952811e855f4c2d7c
commit-date: 2020-10-02
host: x86_64-pc-windows-msvc
release: 1.48.0-nightly
LLVM version: 11.0
```

### Error output

```
error: internal compiler error: compiler\rustc_middle\src\hir\map\mod.rs:477:41: couldn't find hir id HirId { owner: DefId(0:0 ~ icetest[63b0]), local_id: 0 } in the HIR map

thread 'rustc' panicked at 'Box<Any>', compiler\rustc_errors\src\lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-nightly (154f1f544 2020-10-02) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `icetest`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler\rustc_middle\src\hir\map\mod.rs:477:41: couldn't find hir id HirId { owner: DefId(0:0 ~ icetest[63b0]), local_id: 0 } in the HIR map

thread 'rustc' panicked at 'Box<Any>', compiler\rustc_errors\src\lib.rs:945:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0-nightly (154f1f544 2020-10-02) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [privacy_access_levels] privacy access levels
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `icetest`
```

</p>
</details>

**Comment by DrMeepster** [comment]
The ice also occurs with `extern crate self as _`.

**Comment by JohnTitor** [comment]
This is now compiled fine with the latest nightly, I _think_ #78077 fixed it. Marking as `E-needs-test`.

**Comment by DrMeepster** [comment]
Still ICEs for me on playground

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=56cf48a33f2f54951e1897847119dcf5

**Comment by JohnTitor** [comment]
@DrMeepster Note that its nightly isn't the latest.

**Comment by DrMeepster** [comment]
Latest nightly compiles it fine

**Comment by JohnTitor** [comment]
This should be open until the test is added.
