### ISSUE TITLE
ICE "unexpected predicate" with trait_alias

### ISSUE THREAD

**Issue by carado** [rust-lang/rust#77632]
### Code

```Rust
#![feature(trait_alias)]

use std::ops::{Deref, DerefMut};

trait DoubleDerefMut<T> = DerefMut where
	<Self as Deref>::Target: DerefMut<Target = T>;

fn _f() -> impl DoubleDerefMut<u32> {
	Box::new(Box::new(0))
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (a1dfd2490 2020-10-05)
binary: rustc
commit-hash: a1dfd2490a6cb456b92e469fa550dc217e20ad6d
commit-date: 2020-10-05
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

### Error output

```
   Compiling rust25 v0.1.0 (/home/carado/tmp/rust25)
     Running `rustc --crate-name rust25 --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=dcd7e8409bf485cf -C extra-filename=-dcd7e8409bf485cf --out-dir /home/carado/tmp/rust25/target/debug/deps -C incremental=/home/carado/tmp/rust25/target/debug/incremental -L dependency=/home/carado/tmp/rust25/target/debug/deps`
warning: Error finalizing incremental compilation session directory `/home/carado/tmp/rust25/target/debug/incremental/rust25-3xbehoyywx89/s-frvbjon4zu-zltv7r-working`: No such file or directory (os error 2)

warning: 1 warning emitted

error: internal compiler error: unexpected predicate ProjectionPredicate(ProjectionTy { substs: [<impl DoubleDerefMut<u32> as std::ops::Deref>::Target], item_def_id: DefId(2:2234 ~ core[5bc6]::ops::deref::Deref::Target) }, u32) on opaque type
 --> src/lib.rs:6:36
  |
6 |     <Self as Deref>::Target: DerefMut<Target = T>;
  |                                       ^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_ty/src/ty.rs:602:18

error: internal compiler error: unexpected predicate TraitPredicate(<<impl DoubleDerefMut<u32> as std::ops::Deref>::Target as std::ops::DerefMut>) on opaque type
 --> src/lib.rs:6:27
  |
6 |     <Self as Deref>::Target: DerefMut<Target = T>;
  |                              ^^^^^^^^^^^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_ty/src/ty.rs:602:18

error: internal compiler error: unexpected predicate TraitPredicate(<<impl DoubleDerefMut<u32> as std::ops::Deref>::Target as std::ops::Deref>) on opaque type
   --> /home/carado/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:167:21
    |
167 | pub trait DerefMut: Deref {
    |                     ^^^^^
    |
    = note: delayed at compiler/rustc_ty/src/ty.rs:602:18

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:961:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:437
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
   9: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (a1dfd2490 2020-10-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rust25`

Caused by:
  process didn't exit successfully: `rustc --crate-name rust25 --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=dcd7e8409bf485cf -C extra-filename=-dcd7e8409bf485cf --out-dir /home/carado/tmp/rust25/target/debug/deps -C incremental=/home/carado/tmp/rust25/target/debug/incremental -L dependency=/home/carado/tmp/rust25/target/debug/deps` (exit code: 101)
```

</p>
</details>

**Comment by carado** [comment]
The code in question no longer causes ICE, closing. (`rustc 1.49.0-nightly (fd542592f 2020-10-26)`)
