### ISSUE TITLE
ICE: compiler/rustc_middle/src/ty/sty.rs:1919:18: `simd_size_and_type` called on invalid type

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#77735]
### Code

```Rust
# ! [ feature ( platform_intrinsics ) ]
# ! [ feature ( staged_api ) ]
                    struct f32x3 (                 ) ;
extern "platform-intrinsic" {
# [ rustc_const_stable ( feature = "foo" , since = "1.3.37" ) ]
fn simd_extract < T , U > ( x : T , idx : u32 ) -> U ;
}
const Y0 : i8 = unsafe { simd_extract ( f32x3 , 0 ) } ;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (91a79fb29 2020-10-07)

binary: rustc

commit-hash: 91a79fb29ac78d057d04dbe86be13d5dcc64309a

commit-date: 2020-10-07

host: x86_64-unknown-linux-gnu

release: 1.49.0-nightly

LLVM version: 11.0
```

### Error output

```
warning: struct is never constructed: `i8x1`

 --> mutant.rs:7:28

  |

7 | # [ repr ( simd ) ] struct i8x1 ( i8 ) ;

  |                            ^^^^

  |

  = note: `#[warn(dead_code)]` on by default



warning: struct is never constructed: `u16x2`

 --> mutant.rs:8:28

  |

8 | # [ repr ( simd ) ] struct u16x2 ( u16 , u16 ) ;

  |                            ^^^^^



warning: struct is never constructed: `f32x3`

 --> mutant.rs:9:28

  |

9 | # [ repr ( simd ) ] struct f32x3 ( f32 , f32 , f32 ) ;

  |                            ^^^^^



warning: function is never used: `simd_insert`

  --> mutant.rs:12:1

   |

12 | fn simd_insert < T , U > ( x : T , idx : u32 , val : U ) -> T ;

   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



warning: function is never used: `simd_extract`

  --> mutant.rs:14:1

   |

14 | fn simd_extract < T , U > ( x : T , idx : u32 ) -> U ;

   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



warning: function is never used: `main`

  --> mutant.rs:16:4

   |

16 | fn main ( ) {

   |    ^^^^



error: internal compiler error: compiler/rustc_middle/src/ty/sty.rs:1919:18: `simd_size_and_type` called on invalid type



thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



note: the compiler unexpectedly panicked. this is a bug.



note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md



note: rustc 1.49.0-nightly (91a79fb29 2020-10-07) running on x86_64-unknown-linux-gnu



note: compiler flags: -C debuginfo=2 -C opt-level=1 -C target-cpu=skylake --crate-type staticlib



error: aborting due to previous error; 6 warnings emitted


```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_middle/src/ty/sty.rs:1919:18: `simd_size_and_type` called on invalid type

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::bug_fmt
   8: rustc_middle::ty::sty::<impl rustc_middle::ty::TyS>::simd_size_and_type
   9: rustc_mir::interpret::intrinsics::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::emulate_intrinsic
  10: <rustc_mir::const_eval::machine::CompileTimeInterpreter as rustc_mir::interpret::machine::Machine>::call_intrinsic
  11: rustc_mir::interpret::terminator::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_fn_call
  12: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
  13: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
  14: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_allocation_raw>::compute
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_query_system::query::plumbing::get_query_impl
  18: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_const_value_raw>::compute
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::get_query_impl
  23: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  24: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::eval_to_const_value_raw>::compute
  25: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  26: rustc_data_structures::stack::ensure_sufficient_stack
  27: rustc_query_system::query::plumbing::get_query_impl
  28: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  29: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly
  30: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_item
  31: rustc_hir::intravisit::Visitor::visit_nested_item
  32: rustc_hir::intravisit::walk_expr
  33: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  34: rustc_hir::intravisit::walk_expr
  35: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  36: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  37: rustc_hir::intravisit::walk_item
  38: rustc_hir::intravisit::Visitor::visit_nested_item
  39: rustc_hir::intravisit::walk_crate
  40: rustc_lint::late::late_lint_crate
  41: rustc_data_structures::sync::join
  42: rustc_session::utils::<impl rustc_session::session::Session>::time
  43: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  44: rustc_session::utils::<impl rustc_session::session::Session>::time
  45: rustc_interface::passes::analysis
  46: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  47: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  48: rustc_data_structures::stack::ensure_sufficient_stack
  49: rustc_query_system::query::plumbing::get_query_impl
  50: rustc_interface::passes::QueryContext::enter
  51: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  52: rustc_span::with_source_map
  53: rustc_interface::interface::create_compiler_and_run
  54: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**NOTE: The bug is found by our work-in-progress compiler testing tool Kira, and the test program is reduced/minimized by [Perses](https://github.com/chengniansun/perses)**

**Comment by workingjubilee** [comment]
One rustfmt and addressing the "calls in functions cannot use stability attributes" error later, we get this:
```rust
#![feature(platform_intrinsics)]
#![feature(staged_api)]
struct f32x3();
extern "platform-intrinsic" {
    fn simd_extract<T, U>(x: T, idx: u32) -> U;
}
const Y0: i8 = unsafe { simd_extract(f32x3, 0) };
```

Which gives the following normal compiler error:
```bash
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
 --> src/lib.rs:7:25
  |
7 | const Y0: i8 = unsafe { simd_extract(f32x3, 0) };
  |                         ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0015`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

This ICE was generated by attempting to compile code using attributes that are not intended for public consumption, which apparently tricked rustc into skipping ahead of this normal compilation error. Note also it doesn't work with the other version, removing `#![feature(staged_api)]` just gives:

```bash


error[E0734]: stability attributes may not be used outside of the standard library
 --> src/lib.rs:4:5
  |
4 |     #[rustc_const_stable(feature = "foo", since = "1.3.37")]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0734`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

**Comment by jyn514** [comment]
@chengniansun Hi, I'm not sure how to contact you, so I'm reaching out here - you said that this input was autogenerated with a tool called Kira? Is that tool open-source/available? I would be very interested in using it to automatically find bugs in rustdoc :), which sees much fewer bug reports than rustc because people usually run it on working code.

**Comment by chengniansun** [comment]
@jyn514 

Thank you for your interest. The tool is currently under active development, and is not ready to be open sourced. We hope this can happen in the middle of next year. 

Meanwhile, if can share how to run rustdoc on a single rust file, i.e., the command lines you want to test, I would be happy to launch several testing runs on our server to stress test rustdoc.

**Comment by jyn514** [comment]
Sure, that would be great! Rustdoc is mostly the same as rustc (i.e. if you have `rustc --extern=... src/lib.rs`, then `rustdoc --extern=... src/lib.rs` should work fine as well). It does accept slightly different options - `--out-dir` is `--output`, `--emit` is unstable, and a few other things - but for simple things like fuzzing it should be the same :)

Rustdoc also has a couple different modes it can run in, so if you pass `--test` it goes through a completely different code path. That may or may not turn up more bugs.

**Comment by Alexendoo** [comment]
Original can still ice with the addition of a stability gate, but closing for the same reason as #94382
