### ISSUE TITLE
Compiler panic on `cargo +nightly test --all-features`

### ISSUE THREAD

**Issue by zeenix** [rust-lang/rust#78018]
```
$ RUST_BACKTRACE=full RUST_BACKTRACE=1 cargo +nightly test --verbose --all-features
       Fresh unicode-xid v0.2.1
       Fresh cfg-if v0.1.10
       Fresh once_cell v1.4.1
       Fresh unicode-segmentation v1.6.0
       Fresh xml-rs v0.8.3
       Fresh void v1.0.2
       Fresh fastrand v1.3.4
       Fresh scoped-tls v1.0.0
       Fresh version_check v0.9.2
       Fresh pkg-config v0.3.18
       Fresh strum v0.18.0
       Fresh version-compare v0.0.10
       Fresh futures-core v0.3.5
       Fresh proc-macro-hack v0.5.18
       Fresh either v1.6.0
       Fresh slab v0.4.2
       Fresh ntest_proc_macro_helper v0.7.1
       Fresh pin-utils v0.1.0
       Fresh ppv-lite86 v0.2.9
       Fresh itoa v0.4.6
       Fresh snakecase v0.1.0
       Fresh heck v0.3.1
       Fresh futures-task v0.3.5
       Fresh itertools v0.9.0
       Fresh futures-channel v0.3.5
       Fresh proc-macro2 v1.0.18
       Fresh libc v0.2.72
       Fresh byteorder v1.3.4
       Fresh log v0.4.11
       Fresh bitflags v1.2.1
       Fresh proc-macro-nested v0.1.6
       Fresh anyhow v1.0.32
       Fresh quote v1.0.7
       Fresh nix v0.17.0
       Fresh getrandom v0.1.14
       Fresh ryu v1.0.5
       Fresh doc-comment v0.3.3
       Fresh syn v1.0.38
       Fresh proc-macro-error-attr v1.0.4
       Fresh rand_core v0.5.1
       Fresh serde_derive v1.0.114
       Fresh thiserror-impl v1.0.20
       Fresh enumflags2_derive v0.6.4
       Fresh serde_repr v0.1.6
       Fresh derivative v2.1.1
       Fresh strum_macros v0.18.0
       Fresh pin-project-internal v0.4.23
       Fresh futures-macro v0.3.5
       Fresh ntest_test_cases v0.7.1
       Fresh serde v1.0.114
       Fresh thiserror v1.0.20
       Fresh pin-project v0.4.23
       Fresh toml v0.5.6
       Fresh enumflags2 v0.6.4
       Fresh arrayvec v0.5.1
       Fresh serde-xml-rs v0.4.0
       Fresh serde_json v1.0.56
       Fresh proc-macro-crate v0.1.5
       Fresh system-deps v1.3.2
       Fresh futures-util v0.3.5
       Fresh ntest_timeout v0.7.1
       Fresh futures-executor v0.3.5
       Fresh ntest v0.7.1
       Fresh zvariant_derive v2.2.0 (/home/zeenix/checkout/zbus/zvariant_derive)
       Fresh glib-sys v0.10.0 (https://github.com/gtk-rs/sys#56e03c02)
       Fresh proc-macro-error v1.0.4
       Fresh rand_chacha v0.2.2
       Fresh zbus-xmlgen v1.0.0 (/home/zeenix/checkout/zbus/zbus_xmlgen)
   Compiling zbus_macros v1.2.0 (/home/zeenix/checkout/zbus/zbus_macros)
       Fresh glib-macros v0.10.0 (https://github.com/gtk-rs/glib?rev=c9ee583cea0#c9ee583c)
       Fresh rand v0.7.3
       Fresh zbus v1.2.0 (/home/zeenix/checkout/zbus/zbus)
       Fresh zbus_polkit v1.0.1 (/home/zeenix/checkout/zbus/zbus_polkit)
     Running `rustc --crate-name zbus_macros --edition=2018 zbus_macros/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 --test -C metadata=cbc07e92ad333fef -C extra-filename=-cbc07e92ad333fef --out-dir /home/zeenix/checkout/zbus/target/debug/deps -C incremental=/home/zeenix/checkout/zbus/target/debug/incremental -L dependency=/home/zeenix/checkout/zbus/target/debug/deps --extern proc_macro_crate=/home/zeenix/checkout/zbus/target/debug/deps/libproc_macro_crate-a39458da35e20ba7.rlib --extern proc_macro2=/home/zeenix/checkout/zbus/target/debug/deps/libproc_macro2-6853290c5739ec5d.rlib --extern quote=/home/zeenix/checkout/zbus/target/debug/deps/libquote-ab332d09c2bc17ce.rlib --extern serde=/home/zeenix/checkout/zbus/target/debug/deps/libserde-08e957a3740c3b39.rlib --extern syn=/home/zeenix/checkout/zbus/target/debug/deps/libsyn-04adfc23a785c136.rlib --extern zbus=/home/zeenix/checkout/zbus/target/debug/deps/libzbus-a2365ac682edbe09.rlib --extern zvariant=/home/zeenix/checkout/zbus/target/debug/deps/libzvariant-acc55b742ea7b295.rlib --extern proc_macro`
       Fresh gobject-sys v0.10.0 (https://github.com/gtk-rs/sys#56e03c02)
       Fresh glib v0.10.0 (https://github.com/gtk-rs/glib?rev=c9ee583cea0#c9ee583c)
       Fresh zvariant v2.3.0 (/home/zeenix/checkout/zbus/zvariant)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `14`,
 right: `22934`', compiler/rustc_middle/src/ty/query/on_disk_cache.rs:558:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:437
   2: rustc_middle::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
   3: rustc_middle::query::<impl rustc_query_system::query::config::QueryDescription<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::codegen_fn_attrs>::try_load_from_disk
   4: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::get_query_impl
   7: rustc_middle::ty::query::try_load_from_on_disk_cache
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   9: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  10: rustc_session::utils::<impl rustc_session::session::Session>::time
  11: rustc_incremental::persist::save::save_in
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  14: rustc_incremental::persist::save::save_dep_graph
  15: rustc_session::utils::<impl rustc_session::session::Session>::time
  16: rustc_codegen_ssa::base::finalize_tcx
  17: rustc_codegen_ssa::base::codegen_crate
  18: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  19: rustc_session::utils::<impl rustc_session::session::Session>::time
  20: rustc_interface::passes::QueryContext::enter
  21: rustc_interface::queries::Queries::ongoing_codegen
  22: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  23: rustc_span::with_source_map
  24: rustc_interface::interface::create_compiler_and_run
  25: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (a1dfd2490 2020-10-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_fn_attrs] computing codegen attributes of `quote::__private::push_pound`
end of query stack
error: could not compile `zbus_macros`

Caused by:
  process didn't exit successfully: `rustc --crate-name zbus_macros --edition=2018 zbus_macros/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 --test -C metadata=cbc07e92ad333fef -C extra-filename=-cbc07e92ad333fef --out-dir /home/zeenix/checkout/zbus/target/debug/deps -C incremental=/home/zeenix/checkout/zbus/target/debug/incremental -L dependency=/home/zeenix/checkout/zbus/target/debug/deps --extern proc_macro_crate=/home/zeenix/checkout/zbus/target/debug/deps/libproc_macro_crate-a39458da35e20ba7.rlib --extern proc_macro2=/home/zeenix/checkout/zbus/target/debug/deps/libproc_macro2-6853290c5739ec5d.rlib --extern quote=/home/zeenix/checkout/zbus/target/debug/deps/libquote-ab332d09c2bc17ce.rlib --extern serde=/home/zeenix/checkout/zbus/target/debug/deps/libserde-08e957a3740c3b39.rlib --extern syn=/home/zeenix/checkout/zbus/target/debug/deps/libsyn-04adfc23a785c136.rlib --extern zbus=/home/zeenix/checkout/zbus/target/debug/deps/libzbus-a2365ac682edbe09.rlib --extern zvariant=/home/zeenix/checkout/zbus/target/debug/deps/libzvariant-acc55b742ea7b295.rlib --extern proc_macro` (exit code: 101)
```

**Comment by zeenix** [comment]
updating to latest nightly (rustc 1.49.0-nightly (dd7fc54eb 2020-10-15) helped.
