### ISSUE TITLE
ICE: panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:958:13

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#78652]
### Code

```Rust
#![unstable(feature = "humans", issue = "none")]
#![feature(staged_api)]
struct Foo;
impl Foo {
    #[stable(feature = "rust1", since = "1.0.0")]
    const fn gated() -> u32 {
        42
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (4f7612ac1 2020-10-31)
binary: rustc
commit-hash: 4f7612ac1499258025077f1fd05d2f429f9accfb
commit-date: 2020-10-31
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

### Error output

```
warning: struct is never constructed: `Foo`
 --> reduced_mutant.rs:3:8
  |
3 | struct Foo;
  |        ^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `gated`
 --> reduced_mutant.rs:6:14
  |
6 |     const fn gated() -> u32 {
  |              ^^^^^

warning: 2 warnings emitted

error: internal compiler error: stable const functions must have either `rustc_const_stable` or `rustc_const_unstable` attribute
 --> reduced_mutant.rs:6:5
  |
6 |     const fn gated() -> u32 {
  |     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/const_eval/fn_queries.rs:53:34

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:958:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (4f7612ac1 2020-10-31) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:958:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4f7612ac1499258025077f1fd05d2f429f9accfb/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/4f7612ac1499258025077f1fd05d2f429f9accfb/library/std/src/panicking.rs:437:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**NOTE: The bug is found by our work-in-progress compiler testing tool Kira, and the test program is reduced/minimized by [Perses](https://github.com/chengniansun/perses)**

**Comment by JohnTitor** [comment]
Panicking has been removed by #84547. I'm going to just close this as it's an internal attribute hence a regression test doesn't make much sense.
