### ISSUE TITLE
Nightly compiler bug – thread 'rustc' panicked at 'Box<Any>'

### ISSUE THREAD

**Issue by aendeavor** [rust-lang/rust#78839]
I tried this code:

``` RUST
println!("{:?}", pnet::datalink::interfaces().iter().filter(|interface| interface.name = "enp3s0"));
```

I expected to see this happen: The debug output of the vector containing `pnet::datalink::NetworkInterface`s.

Instead, this happened:

I saw the following, which I cannot interpret well:

``` BASH
error: internal compiler error: compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:308:25: while adjusting Expr { hir_id: HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 23 }, kind: Path(Resolved(None, Path { span: src/main.rs:12:65: 12:74 (#0), res: Local(HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 2 }), segments: [PathSegment { ident: interface#0, hir_id: Some(HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 22 }), res: Some(Local(HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 2 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/main.rs:12:65: 12:74 (#0) }, can't compose [Deref(None) -> &NetworkInterface, Deref(None) -> NetworkInterface] and [Deref(None) -> &NetworkInterface, Deref(None) -> NetworkInterface]

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to previous error

error: could not compile `rather`

To learn more, run the command again with --verbose.
error: Recipe `build` failed on line 6 with exit code 101
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

The verbose output of the compilation as suggested by `cargo` is:

``` BASH
Running `rustc --crate-name rather --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a5e0fa68fdb22d01 -C extra-filename=-a5e0fa68fdb22d01 --out-dir /home/maxwell/Dokumente/github/rather/target/debug/deps -C incremental=/home/maxwell/Dokumente/github/rather/target/debug/incremental -L dependency=/home/maxwell/Dokumente/github/rather/target/debug/deps --extern libc=/home/maxwell/Dokumente/github/rather/target/debug/deps/liblibc-e41c2d10207ee17e.rlib --extern pnet=/home/maxwell/Dokumente/github/rather/target/debug/deps/libpnet-3408e1b601512524.rlib`
error: internal compiler error: compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:308:25: while adjusting Expr { hir_id: HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 23 }, kind: Path(Resolved(None, Path { span: src/main.rs:12:65: 12:74 (#0), res: Local(HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 2 }), segments: [PathSegment { ident: interface#0, hir_id: Some(HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 22 }), res: Some(Local(HirId { owner: DefId(0:58 ~ rather[260f]::main), local_id: 2 })), args: None, infer_args: true }] })), attrs: ThinVec(None), span: src/main.rs:12:65: 12:74 (#0) }, can't compose [Deref(None) -> &NetworkInterface, Deref(None) -> NetworkInterface] and [Deref(None) -> &NetworkInterface, Deref(None) -> NetworkInterface]

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to previous error

error: could not compile `rather`

Caused by:
  process didn't exit successfully: `rustc --crate-name rather --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a5e0fa68fdb22d01 -C extra-filename=-a5e0fa68fdb22d01 --out-dir /home/maxwell/Dokumente/github/rather/target/debug/deps -C incremental=/home/maxwell/Dokumente/github/rather/target/debug/incremental -L dependency=/home/maxwell/Dokumente/github/rather/target/debug/deps --extern libc=/home/maxwell/Dokumente/github/rather/target/debug/deps/liblibc-e41c2d10207ee17e.rlib --extern pnet=/home/maxwell/Dokumente/github/rather/target/debug/deps/libpnet-3408e1b601512524.rlib` (exit code: 101)
``` 

The stable compiler will output:

``` BASH
error[E0308]: mismatched types
  --> src/main.rs:12:82
   |
12 |     let x = pnet::datalink::interfaces().iter().filter(|interface| interface.name = "enp3s0");
   |                                                                                     ^^^^^^^^
   |                                                                                     |
   |                                                                                     expected struct `std::string::String`, found `&str`
   |                                                                                     help: try using a conversion method: `"enp3s0".to_string()`

error[E0308]: mismatched types
  --> src/main.rs:12:65
   |
12 |     let x = pnet::datalink::interfaces().iter().filter(|interface| interface.name = "enp3s0");
   |                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                                                    |
   |                                                                    expected `bool`, found `()`
   |                                                                    help: try comparing for equality: `interface.name == "enp3s0"`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rather`.
```

which obviously is correct.

**Comment by jonas-schievink** [comment]
This is already fixed, you need to update your compiler
