### ISSUE TITLE
Fresh MSYS2 gdb cannot set a breakpoint in Rust executables

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#79112]
Reproduction:
```c
// main.c

#include <stdio.h>

int main() {
    printf("Hello world!\n");
}
```
```rust
// main.rs

fn main() {
    println!("Hello world!");
}
```
```sh
# script.gdb

break main
run
quit
```
```sh
# reproduce.sh

set -x

gcc --version
rustc --version
/mingw64/bin/gdb --version
/usr/bin/gdb --version

gcc -g main.c -o mainc
rustc -g main.rs -o mainrs

/mingw64/bin/gdb -q -x script.gdb ./mainc
/mingw64/bin/gdb -q -x script.gdb ./mainrs
/usr/bin/gdb -q -x script.gdb ./mainc
/usr/bin/gdb -q -x script.gdb ./mainrs
```
Output on my machine:
```
++ gcc --version
gcc.exe (Rev5, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

++ rustc --version
rustc 1.50.0-nightly (74f7e32f4 2020-11-13)
++ /mingw64/bin/gdb --version
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
++ /usr/bin/gdb --version
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
++ gcc -g main.c -o mainc
++ rustc -g main.rs -o mainrs
++ /mingw64/bin/gdb -q -x script.gdb ./mainc
Reading symbols from ./mainc...
Breakpoint 1 at 0x4015a1: file main.c, line 6.

Breakpoint 1, main () at main.c:6
6           printf("Hello world!\n");
++ /mingw64/bin/gdb -q -x script.gdb ./mainrs
Reading symbols from ./mainrs...
Breakpoint 1 at 0x4015a7: main. (2 locations)

Breakpoint 1, 0x00000000013515fa in main ()
++ /usr/bin/gdb -q -x script.gdb ./mainc
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'libstdcxx'
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from ./mainc...
Breakpoint 1 at 0x4015a1: file main.c, line 6.

Breakpoint 1, main () at main.c:6
6           printf("Hello world!\n");
++ /usr/bin/gdb -q -x script.gdb ./mainrs
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'libstdcxx'
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from ./mainrs...
Breakpoint 1 at 0x4015a7: main. (2 locations)
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x4015a7
Cannot insert breakpoint 1.
Cannot access memory at address 0x4015f0

script.gdb:4: Error in sourced command file:
Command aborted.
```

**Comment by petrochenkov** [comment]
As you can see with both `/mingw64/bin/gdb` and C executables breakpoints are set correctly, only the combination "`/usr/bin/gdb` + Rust" doesn't work.
This is a recent regression (a month or so).

(`ModuleNotFoundError: No module named 'libstdcxx'` is a red herring, this is an independent issue - a modern incarnation of https://github.com/msys2/MSYS2-packages/pull/598.)

cc @mati865

**Comment by petrochenkov** [comment]
The whole `debuginfo` test suite fails due to this issue.
The solution is to switch to `/mingw64/bin/gdb` (which has its own set of issues, but at least they don't affect the test suite).

**Comment by mati865** [comment]
I don't think I've tried using `/usr/bin/gdb` with Rust but if you say it worked before bisecting could be useful.

**Comment by petrochenkov** [comment]
@mati865 
This is a consequence of enabling ASLR (https://github.com/rust-lang/rust/pull/75406).
Apparently `/usr/bin/gdb` cannot handle it.
Perhaps it can be fixed on MSYS2 side?

The workaround is to build Rust code without ASLR using `-Clink-args=-Wl,--disable-dynamicbase`.

**Comment by mati865** [comment]
@petrochenkov right, MinGW GDB was updated with ASLR fix but msys/gdb was not since `msys/*` packages do not use ASLR. Definitely could be fixed by MSYS2.

**Comment by mati865** [comment]
This is now fixed upstream since version 10 was uploaded: https://packages.msys2.org/package/gdb?repo=msys&variant=x86_64

**Comment by petrochenkov** [comment]
Great news.
I've just confirmed that it works.

The issue with libstdcxx pretty-printers (https://github.com/rust-lang/rust/issues/79112#issuecomment-728346212) still remains though, but it's not critical.

**Comment by mati865** [comment]
Will be fixed soon: https://github.com/msys2/MSYS2-packages/pull/2477 but I don't know if it gives any benefit other than silencing the warning since this is Cygwin (UNIX) libstdc++ not Win32.
