### ISSUE TITLE
Incorrectly unified locals at -Zmir-opt-level=2

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#79191]
```rust
fn main() {
    if f(false) != 1 {
        panic!();
    }
}

#[inline(always)]
fn f(use_y: bool) -> u8 {
    let (x, y) = (1, 2);
    if use_y { y } else { x }
}
```

```console
$ rustc -Zmir-opt-level=1 a.rs && ./a
$ rustc -Zmir-opt-level=2 a.rs && ./a
thread 'main' panicked at 'explicit panic', a.rs:3:9
```

```diff
--- a.main.005-011.DestinationPropagation.before.mir
+++ a.main.005-011.DestinationPropagation.after.mir
@@ -1,70 +1,70 @@
-// MIR for `main` before DestinationPropagation
+// MIR for `main` after DestinationPropagation
 
 fn main() -> () {
     let mut _0: ();
     let mut _1: bool;
     let mut _2: u8;
     let mut _3: !;
     let _4: ();
     let mut _5: !;
     let mut _6: bool;
     scope 1 (inlined f) {
         debug use_y => _6;
         let _7: u8;
         let mut _8: bool;
         scope 2 {
             debug x => _2;
-            debug y => _7;
+            debug y => _2;
         }
     }
 
     bb0: {
         StorageLive(_1);
-        StorageLive(_2);
+        nop;
         StorageLive(_6);
         _6 = const false;
         _2 = const 1_u8;
-        StorageLive(_7);
-        _7 = const 2_u8;
+        nop;
+        _2 = const 2_u8;
         StorageLive(_8);
         _8 = const false;
         goto -> bb4;
     }
 
     bb1: {
-        StorageDead(_2);
+        nop;
         _0 = const ();
         StorageDead(_1);
         return;
     }
 
     bb2: {
-        StorageDead(_2);
+        nop;
         StorageLive(_4);
         StorageLive(_5);
         begin_panic::<&str>(const "explicit panic");
     }
 
     bb3: {
-        _2 = _7;
+        nop;
         goto -> bb4;
     }
 
     bb4: {
-        StorageDead(_7);
+        nop;
         StorageDead(_8);
         StorageDead(_6);
         _1 = Ne(_2, const 1_u8);
         nop;
         switchInt(move _2) -> [1_u8: bb1, otherwise: bb2];
     }
 }

**Comment by jonas-schievink** [comment]
Hmm, seems like it doesn't see the conflict because the assignment is unreachable:

```rust
    // init: <unreachable>
    // live: <unreachable>
    bb3: {
        // init: <unreachable>
        // live: <unreachable>
        _2 = _7;                         // scope 2 at borken.rs:2:8: 2:16
        // init: <unreachable>
        // live: <unreachable>
        goto -> bb4;                     // scope 2 at borken.rs:2:8: 2:16
        // init: <unreachable>
        // live: <unreachable>
    }
```

Seems like we should consider assignments in dead blocks as propagation candidates. But does that fix the whole bug?

**Comment by tmiasko** [comment]
I think that the main issue is that the notion of conflicts is based on liveness. A local could be never live but still conflict with others merely because there are dead stores to it.

For example, in code below `a` will be unified with `b` (after running destination propagation for the second time after inlining):

```rust
#![allow(unused)]

#[inline(never)]
pub fn id<T>(x: T) -> T { x }

pub fn main() {
    assert_eq!(1, g(1));
}

#[inline(never)]
pub fn g(x: usize) -> usize {
    f(x)
}

#[inline(always)]
pub fn f(a: usize) -> usize {
    let mut b = 3;
    b = a;
    b = 4;
    id(a)
}
```

**Comment by jonas-schievink** [comment]
Right. I think this briefly came up when implementing the pass, but I never wrote it down anywhere, nor could I produce an example.

Sounds like we need to run a dead store elimination pass before destination propagation, or change the analysis it uses to account for dead stores.

**Comment by SparrowLii** [comment]
@JakobDegen I'm interested in this, too. Have you done some work? If not, I should be able to submit a PR soon

**Comment by tmiasko** [comment]
Fixed in #96451.
