### ISSUE TITLE
Rustc panics on incremental build

### ISSUE THREAD

**Issue by ISSOtm** [rust-lang/rust#79368]
### Code

Happens when running `cargo run` and `cargo build` but *not* `cargo check` on [this archive](https://eldred.fr/rsgbasm.tar.bz2). Does not reproduce anymore after `cargo clean`, so it's likely to be an incremental problem. Here is [the original source code](https://github.com/ISSOtm/rsgbasm/tree/5a7cb4e44dc81ed250b50ad7c282e8e8aceb86e0).

(Note: I uploaded this file on my GitHub Pages, and it's just below the file size limit, so I'd like to be able to take it down as soon as possible.)

### Meta

```
issotm@sheik-kitty ~/rsgbasm% rustc --version --verbose                          [master|✔] 
rustc 1.48.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

Due to the nature of the bug, it's impossible to reproduce on nightly.

### Error output

```
issotm@sheik-kitty ~/rsgbasm% RUST_BACKTRACE=1 cargo build                       [master|✔] 
   Compiling rsgbasm v0.1.0 (/home/issotm/rsgbasm)
warning: unused import: `Mul`
 --> src/expression.rs:2:23
  |
2 | use std::ops::{BitOr, Mul, Neg, Shl};
  |                       ^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unreachable expression
  --> src/expression.rs:13:9
   |
12 |         unimplemented!();
   |         ----------------- any code following this expression is unreachable
13 |         self
   |         ^^^^ unreachable expression
   |
   = note: `#[warn(unreachable_code)]` on by default

thread 'rustc' panicked at 'index out of bounds: the len is 99312 but the index is 699444', /build/rust/src/rustc-1.48.0-src/compiler/rustc_query_system/src/dep_graph/graph.rs:1110:15
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.48.0-src/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /build/rust/src/rustc-1.48.0-src/library/core/src/panicking.rs:62
   3: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
   5: rustc_query_system::query::plumbing::ensure_query_impl
   6: rustc_session::utils::<impl rustc_session::session::Session>::time
   7: rustc_session::utils::<impl rustc_session::session::Session>::time
   8: rustc_interface::passes::analysis
   9: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  10: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::get_query_impl
  14: rustc_interface::passes::QueryContext::enter
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0 running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
warning: 2 warnings emitted

error: could not compile `rsgbasm`

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by Enselic** [comment]
Triage: The archive that reproduced the ICE is gone, and I can't reproduce the ICE with "the original source code". I'll close this issue for now. Feel free to reopen after updating how to reproduce this ICE.

**Comment by ISSOtm** [comment]
Whoops, I had forgotten what that archive was for, so I deleted it during some cleanup. I updated the OP with a functional link. Apologies!

**Comment by Enselic** [comment]
Thank you for the update! Can you still reproduce the ICE? If so, please share your command line commands to do so. Best is if you can give me the commands for a docker image for maximum reproducibility:

```sh
docker run -it ubuntu:23.04

apt-get update -y && apt-get install -y build-essential curl git libssl-dev pkg-config
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"   
# Step 1
# Step 2
# ...
```
