### ISSUE TITLE
ICE with source-based code coverage

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#79393]
### Repro

- Create an empty library with `cargo new --lib`
- Add `dashmap = "3.11.10"` to dependencies.
- Set `RUSTFLAGS="-Zinstrument-coverage"`
- Run `cargo test`

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (3525087ad 2020-10-08)
binary: rustc
commit-hash: 3525087ada7018ef227b10846648660b7f07b6d1
commit-date: 2020-10-08
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
LLVM version: 11.0
```

### Error output

```
error: internal compiler error: compiler\rustc_mir\src\transform\instrument_coverage.rs:554:18: source_file.name should be a RealFileName, but it was: Real(Devirtualized { local_path: "C:\\Users\\diggs\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib/rustlib/src/rust\\library\\core\\src\\macros\\mod.rs", virtual_name: "/rustc/3525087ada7018ef227b10846648660b7f07b6d1\\library\\core\\src\\macros\\mod.rs" })

thread 'rustc' panicked at 'Box<Any>', compiler\rustc_errors\src\lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', compiler\rustc_errors\src\lib.rs:945:9
stack backtrace:
   0:     0x7ffb569a9989 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc20a26e0f7659afd
   1:     0x7ffb569d70bb - core::fmt::write::h435be716304d26a1
   2:     0x7ffb5699b1d8 - <std::io::IoSlice as core::fmt::Debug>::fmt::h997d94c78f1ba97b
   3:     0x7ffb569aed74 - std::panicking::take_hook::hbf7e33d26fc3ca30
   4:     0x7ffb569ae958 - std::panicking::take_hook::hbf7e33d26fc3ca30
   5:     0x7ffb022ae305 - rustc_driver::report_ice::hf312ccffbe1edb81
   6:     0x7ffb569af7d0 - std::panicking::rust_panic_with_hook::h19068ccbe4b337a1
   7:     0x7ffb06a1fe10 - <rustc_errors::snippet::Style as core::fmt::Debug>::fmt::h0b62f4af8631af46
   8:     0x7ffb06a1fd69 - <rustc_errors::snippet::Style as core::fmt::Debug>::fmt::h0b62f4af8631af46
   9:     0x7ffb06a1fd81 - <rustc_errors::snippet::Style as core::fmt::Debug>::fmt::h0b62f4af8631af46
  10:     0x7ffb06a51f3f - rustc_errors::HandlerInner::err_count::hc50b2c4e38661a30
  11:     0x7ffb06a505f2 - rustc_errors::Handler::bug::had6fb00075fb8f2a
  12:     0x7ffb064b8ecf - rustc_middle::util::bug::bug_fmt::hb0b66de69b1afddc
  13:     0x7ffb064b7860 - rustc_middle::ty::walk::<impl rustc_middle::ty::subst::GenericArg>::walk_shallow::hea9f4f76c7e761e2
  14:     0x7ffb064b7113 - rustc_middle::ty::walk::<impl rustc_middle::ty::subst::GenericArg>::walk_shallow::hea9f4f76c7e761e2
  15:     0x7ffb064b8dfc - rustc_middle::util::bug::bug_fmt::hb0b66de69b1afddc
  16:     0x7ffb064b8d60 - rustc_middle::util::bug::bug_fmt::hb0b66de69b1afddc
  17:     0x7ffb0534655c - <rustc_mir::transform::instrument_coverage::BasicCoverageBlocks as core::ops::index::Index<rustc_middle::mir::BasicBlock>>::index::ha1a521222eb2378a
  18:     0x7ffb0534229b - <rustc_mir::transform::instrument_coverage::InstrumentCoverage as rustc_mir::transform::MirPass>::run_pass::h7c336ab096e42dbd
  19:     0x7ffb0555b0c6 - rustc_mir::transform::run_passes::h3074ddb52caf61e1
  20:     0x7ffb0555c167 - rustc_mir::transform::run_passes::h3074ddb52caf61e1
  21:     0x7ffb0556a58e - <rustc_mir::util::spanview::SpanViewable as core::fmt::Debug>::fmt::h00cc381235b87f25
  22:     0x7ffb053d0a1e - <rustc_mir::transform::early_otherwise_branch::OptimizationInfo as core::fmt::Debug>::fmt::h81ab8dab256817f7
  23:     0x7ffb053e8f54 - <rustc_mir::transform::early_otherwise_branch::OptimizationInfo as core::fmt::Debug>::fmt::h81ab8dab256817f7
  24:     0x7ffb05276aef - <rustc_mir::borrow_check::type_check::liveness::local_use_map::AppearanceIndex as core::fmt::Debug>::fmt::h78d999ab39932b2a
  25:     0x7ffb055a1046 - rustc_mir::borrow_check::provide::h9e786960534ab244
  26:     0x7ffb0556fe8f - <rustc_mir::util::spanview::SpanViewable as core::fmt::Debug>::fmt::h00cc381235b87f25
  27:     0x7ffb0517993e - <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt::h07071a2480c87500
  28:     0x7ffb053d48f8 - <rustc_mir::transform::early_otherwise_branch::OptimizationInfo as core::fmt::Debug>::fmt::h81ab8dab256817f7
  29:     0x7ffb053e9b9d - <rustc_mir::transform::early_otherwise_branch::OptimizationInfo as core::fmt::Debug>::fmt::h81ab8dab256817f7
  30:     0x7ffb0526377c - <rustc_mir::borrow_check::type_check::liveness::local_use_map::AppearanceIndex as core::fmt::Debug>::fmt::h78d999ab39932b2a
  31:     0x7ffb05185471 - <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body::hdd8eb50ba1c4105c
  32:     0x7ffb0518aed1 - <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body::hdd8eb50ba1c4105c
  33:     0x7ffb0517d4fe - <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt::h07071a2480c87500
  34:     0x7ffb053fe283 - <rustc_middle::ty::sty::RegionVid as rustc_mir::borrow_check::facts::FactRow>::write::h6d8c730b7c7d4efe
  35:     0x7ffb055a3f87 - rustc_mir::borrow_check::provide::h9e786960534ab244
  36:     0x7ffb050924fb - <rustc_mir_build::thir::pattern::_match::split_grouped_constructors::Border as core::fmt::Debug>::fmt::h57b308ed6f4e9a60
  37:     0x7ffb055a1080 - rustc_mir::borrow_check::provide::h9e786960534ab244
  38:     0x7ffb0556fe8f - <rustc_mir::util::spanview::SpanViewable as core::fmt::Debug>::fmt::h00cc381235b87f25
  39:     0x7ffb024a4f4e - rustc_interface::interface::parse_cfgspecs::hd18342bf8d640f8e
  40:     0x7ffb024526a8 - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  41:     0x7ffb024a865d - rustc_interface::interface::parse_cfgspecs::hd18342bf8d640f8e
  42:     0x7ffb024287d8 - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  43:     0x7ffb0244dfcf - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  44:     0x7ffb02493f24 - <rls_span::serde_expanded::_IMPL_DESERIALIZE_FOR_OneIndexed::<impl serde::de::Deserialize for rls_span::OneIndexed>::deserialize::__Visitor as serde::de::Visitor>::expecting::h9a9b74719e191e7e
  45:     0x7ffb024cf49d - rustc_interface::passes::QueryContext::print_stats::h19272f484043387d
  46:     0x7ffb0223318b - <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_local::hf9de07b4d4aa877d
  47:     0x7ffb022b6ae7 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5e5e8ea505c90384
  48:     0x7ffb022c3e46 - <rustc_codegen_llvm::builder::Builder as core::ops::deref::Deref>::deref::h818c0e561b07554d
  49:     0x7ffb0226058e - <rustc_span::symbol::SymbolStr as core::fmt::Display>::fmt::h2f1bcc3f2a45cfa1
  50:     0x7ffb022351ec - <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_local::hf9de07b4d4aa877d
  51:     0x7ffb022bee14 - <rustc_codegen_llvm::builder::Builder as core::ops::deref::Deref>::deref::h818c0e561b07554d
  52:     0x7ffb02291076 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::he3794826ebaa6de3
  53:     0x7ffb022c1798 - <rustc_codegen_llvm::builder::Builder as core::ops::deref::Deref>::deref::h818c0e561b07554d
  54:     0x7ffb022b30c0 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5e5e8ea505c90384
  55:     0x7ffb022c5303 - <rustc_codegen_llvm::builder::Builder as core::ops::deref::Deref>::deref::h818c0e561b07554d
  56:     0x7ffb02251573 - <rustc_span::symbol::SymbolStr as core::fmt::Display>::fmt::h2f1bcc3f2a45cfa1
  57:     0x7ffb569bf6a7 - std::sys::windows::thread::Thread::new::h04914a10b014a9d7
  58:     0x7ffb954e7034 - BaseThreadInitThunk
  59:     0x7ffb9721cec1 - RtlUserThreadStart
```

</p>
</details>

Query stack:
```
query stack during panic:
#0 [mir_promoted] processing `<lock::RwLock<T> as std::fmt::Debug>::fmt::{closure#1}`
#1 [mir_borrowck] borrow-checking `<lock::RwLock<T> as std::fmt::Debug>::fmt::{closure#1}`
#2 [mir_borrowck] borrow-checking `<lock::RwLock<T> as std::fmt::Debug>::fmt`
#3 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by vitaly-burovoy** [comment]
Confirm this bug. It is not Windows-only, also for Linux:

I compiled stable rust-1.48.0 with a `nightly` feature
# Meta
```
$ rustc --version --verbose
rustc 1.48.0-nightly
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

# Error output

```
error: internal compiler error: compiler/rustc_mir/src/transform/instrument_coverage.rs:411:14: start.file.name should be a RealFileName, but it was: Real(Devirtualized { local_path: "/usr/lib64/rust/1.48.0/lib/rustlib/src/rust/library/core/src/macros/mod.rs", virtual_name: "/rustc/1.48.0/library/core/src/macros/mod.rs" })
```

# Repro
The same as in the initial message and (in my case) two more crates lead to the bug (as dependency of the `tokio-postgres` crate):
`typenum = "1.12.0"`
`once_cell = "1.5.2"`

**Comment by richkadel** [comment]
@Diggsey - Thanks for the bug report! There have been some new releases with multiple bug fixes since you reported this. This error _should_ be resolved. Can you confirm?

Thanks!

**Comment by richkadel** [comment]
@wesleywiser, @tmandry  - I don't see a reply from @Diggsey to my request to re-try, but  I'm comfortable that the "Error output" mentioned in this issue was resolved.

Can we close this?

Thanks

**Comment by Diggsey** [comment]
I just tested this, and it does appear to be fixed, thanks!
