### ISSUE TITLE
ICE: rustdoc on refutable-pattern-errors.rs: tried to get argument name from PatKind::Range, which is not allowed in function arguments

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#79497]
### Code
code is from `./src/test/ui/pattern/usefulness/refutable-pattern-errors.rs`
```Rust
// ignore-tidy-linelength

fn func((1, (Some(1), 2..=3)): (isize, (Option<isize>, isize))) { }
//~^ ERROR refutable pattern in function argument: `(_, _)` not covered

fn main() {
    let (1, (Some(1), 2..=3)) = (1, (None, 2));
    //~^ ERROR refutable pattern in local binding: `(i32::MIN..=0_i32, _)` and `(2_i32..=i32::MAX, _)` not covered
}
```

### Meta

`rustc --version --verbose`:
```
rustdoc 1.50.0-nightly (1c389ffef 2020-11-24)
binary: rustdoc
commit-hash: 1c389ffeff814726dec325f0f2b0c99107df2673
commit-date: 2020-11-24
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
thread 'rustc' panicked at 'tried to get argument name from PatKind::Range, which is not allowed in function arguments', src/librustdoc/clean/utils.rs:430:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (1c389ffef 2020-11-24) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'tried to get argument name from PatKind::Range, which is not allowed in function arguments', src/librustdoc/clean/utils.rs:430:31
stack backtrace:
   0:     0x7f947a274e30 - std::backtrace_rs::backtrace::libunwind::trace::h746c3e9529d524bc
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f947a274e30 - std::backtrace_rs::backtrace::trace_unsynchronized::h86340908ff889faa
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f947a274e30 - std::sys_common::backtrace::_print_fmt::h43f85f9b18230404
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f947a274e30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc132ae1a5b5aa7cd
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f947a2e7c4c - core::fmt::write::hdf023a0036d2a25f
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/fmt/mod.rs:1078:17
   5:     0x7f947a2669a2 - std::io::Write::write_fmt::h8580846154bcb66a
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/io/mod.rs:1519:15
   6:     0x7f947a278a95 - std::sys_common::backtrace::_print::h7ee55fed88d107a3
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f947a278a95 - std::sys_common::backtrace::print::h54a7d3e52a524177
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f947a278a95 - std::panicking::default_hook::{{closure}}::h60921e857bf55a40
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:208:50
   9:     0x7f947a2785ea - std::panicking::default_hook::hf0f9afb1017317fc
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:225:9
  10:     0x7f947ab05bb8 - rustc_driver::report_ice::ha25ae86a5858acc3
  11:     0x7f947a279396 - std::panicking::rust_panic_with_hook::h8d66bf42b407aaea
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:595:17
  12:     0x563e7ea559d4 - std::panicking::begin_panic::{{closure}}::hfb2142642975470b
  13:     0x563e7ea5518c - std::sys_common::backtrace::__rust_end_short_backtrace::h20a6f95504e96913
  14:     0x563e7eb8467c - std::panicking::begin_panic::h1822bde8a223a8ff
  15:     0x563e7ec96150 - rustdoc::clean::utils::name_from_pat::h1b61c8e430f27b93
  16:     0x563e7ec95c0d - rustdoc::clean::utils::name_from_pat::h1b61c8e430f27b93
  17:     0x563e7ec95c0d - rustdoc::clean::utils::name_from_pat::h1b61c8e430f27b93
  18:     0x563e7ea2bdb6 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h64c59269cd1e2f54
  19:     0x563e7ec08666 - <(&rustc_hir::hir::FnDecl,A) as rustdoc::clean::Clean<rustdoc::clean::types::FnDecl>>::clean::h0d96c315d7646885
  20:     0x563e7ec9818e - rustdoc::clean::utils::enter_impl_trait::h89ecd5f85c6cf117
  21:     0x563e7ec10339 - <(&rustc_hir::hir::Item,core::option::Option<rustc_span::symbol::Ident>) as rustdoc::clean::Clean<alloc::vec::Vec<rustdoc::clean::types::Item>>>::clean::h6efe2622d62f0879
  22:     0x563e7ed1c01f - <alloc::vec::Vec<T,A> as alloc::vec::SpecExtend<T,I>>::spec_extend::hbf27f2437fec8031
  23:     0x563e7ec98de8 - <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::types::Item>>::clean::hee8955bac14e83bc
  24:     0x563e7ec92153 - rustdoc::clean::utils::krate::h68bb50ab032123ce
  25:     0x563e7ea0db3b - rustdoc::core::run_global_ctxt::h7cf39be6ea65128e
  26:     0x563e7ea87ece - rustc_interface::passes::QueryContext::enter::hedb615e17429b641
  27:     0x563e7eb7d917 - rustc_interface::interface::create_compiler_and_run::h25fa5935e40978f2
  28:     0x563e7ea240d3 - rustdoc::main_options::h8a5cda9c1c8c625b
  29:     0x563e7eb6ea68 - rustc_span::with_session_globals::h7a83fbbd64fb6823
  30:     0x563e7ea5530e - std::sys_common::backtrace::__rust_begin_short_backtrace::h50722f4a01515f7b
  31:     0x563e7eb8703a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h22276985fb540191
  32:     0x7f947a28865a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea1090dbdcecbf5a
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/alloc/src/boxed.rs:1318:9
  33:     0x7f947a28865a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5723d3912bd325
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/alloc/src/boxed.rs:1318:9
  34:     0x7f947a28865a - std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724
                               at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys/unix/thread.rs:71:17
  35:     0x7f947a1643e9 - start_thread
  36:     0x7f9479f4a293 - __GI___clone
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (1c389ffef 2020-11-24) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by fanninpm** [comment]
[Playground link of example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=da421418415b26e804b82f61564476be)

The playground's nightly compiler doesn't ICE on this example. Are you able to confirm this with the latest nightly?

**Comment by jyn514** [comment]
@fanninpm rustdoc is crashing, not the compiler itself. Playground doesn't have a button for running rustdoc.

**Comment by jyn514** [comment]
MCVE:
```rust
fn f(0..=255: u8) {}
```
Marking as P-medium since this happens on valid code.
