### ISSUE TITLE
RUSTFLAGS='-Z fuel=rand_core=0' leads to ICE: trimmed_def_paths constructed

### ISSUE THREAD

**Issue by andersk** [rust-lang/rust#79546]
### Code

**`Cargo.toml`**

```toml
[package]
name = "fuel-test"
version = "0.1.0"

[dependencies]
rand_core = "0.5.1"
```

**`src/main.rs`**

```rust
fn main() {}
```

Building with `env RUSTFLAGS='-Z fuel=rand_core=0' cargo build --release` leads to `error: internal compiler error: trimmed_def_paths constructed`.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (349b3b324 2020-11-29)
binary: rustc
commit-hash: 349b3b324dade7ca638091db93ba08bbc443c63d
commit-date: 2020-11-29
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

From bisecting previous nightlies, this is a regression between 2020-09-03 0d0f6b113047b2cf9afbde990cee30fd5b866469 and 2020-09-04 c59199efca5856cdf810919fbf9b5bce32dc4523. Within 0d0f6b113047b2cf9afbde990cee30fd5b866469...c59199efca5856cdf810919fbf9b5bce32dc4523, it looks like #73996 is related. Cc @da-x.

### Error output

```
   Compiling rand_core v0.5.1
     Running `rustc --crate-name rand_core --edition=2018 /home/anders/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=4da4ae534686a8b2 -C extra-filename=-4da4ae534686a8b2 --out-dir /tmp/fuel-test/target/release/deps -L dependency=/tmp/fuel-test/target/release/deps --cap-lints allow -Z fuel=rand_core=0`
error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: rustc_errors::Handler::delay_good_path_bug
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::trimmed_def_paths>::compute
             3: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
             4: rustc_data_structures::stack::ensure_sufficient_stack
             5: rustc_query_system::query::plumbing::get_query_impl
             6: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
             7: rustc_middle::ty::print::pretty::<impl rustc_middle::ty::context::TyCtxt>::def_path_str_with_substs
             8: rustc_session::session::Session::consider_optimizing
             9: rustc_middle::ty::ReprOptions::new
            10: rustc_typeck::collect::adt_def
            11: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::adt_def>::compute
            12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            13: rustc_data_structures::stack::ensure_sufficient_stack
            14: rustc_query_system::query::plumbing::get_query_impl
            15: rustc_typeck::collect::type_of::type_of
            16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::type_of>::compute
            17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            18: rustc_data_structures::stack::ensure_sufficient_stack
            19: rustc_query_system::query::plumbing::get_query_impl
            20: <dyn rustc_typeck::astconv::AstConv>::res_to_ty
            21: <dyn rustc_typeck::astconv::AstConv>::ast_ty_to_ty_inner
            22: rustc_typeck::collect::type_of::type_of
            23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::type_of>::compute
            24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            25: rustc_data_structures::stack::ensure_sufficient_stack
            26: rustc_query_system::query::plumbing::get_query_impl
            27: rustc_typeck::collect::impl_trait_ref
            28: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            29: rustc_data_structures::stack::ensure_sufficient_stack
            30: rustc_query_system::query::plumbing::get_query_impl
            31: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::trait_id_of_impl
            32: rustc_typeck::collect::codegen_fn_attrs
            33: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::codegen_fn_attrs>::compute
            34: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            35: rustc_data_structures::stack::ensure_sufficient_stack
            36: rustc_query_system::query::plumbing::get_query_impl
            37: rustc_query_system::query::plumbing::ensure_query_impl
            38: rustc_passes::check_attr::CheckAttrVisitor::check_attributes
            39: <rustc_passes::check_attr::CheckAttrVisitor as rustc_hir::intravisit::Visitor>::visit_impl_item
            40: rustc_middle::hir::map::Map::visit_item_likes_in_module
            41: rustc_passes::check_attr::check_mod_attrs
            42: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_mod_attrs>::compute
            43: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
            44: rustc_data_structures::stack::ensure_sufficient_stack
            45: rustc_query_system::query::plumbing::get_query_impl
            46: rustc_query_system::query::plumbing::ensure_query_impl
            47: std::panic::catch_unwind
            48: rustc_session::utils::<impl rustc_session::session::Session>::time
            49: rustc_interface::passes::analysis
            50: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
            51: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
            52: rustc_data_structures::stack::ensure_sufficient_stack
            53: rustc_query_system::query::plumbing::get_query_impl
            54: rustc_interface::passes::QueryContext::enter
            55: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
            56: rustc_span::with_source_map
            57: scoped_tls::ScopedKey<T>::set
            58: std::sys_common::backtrace::__rust_begin_short_backtrace
            59: core::ops::function::FnOnce::call_once{{vtable.shim}}
            60: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/alloc/src/boxed.rs:1327:9
                <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/alloc/src/boxed.rs:1327:9
                std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/std/src/sys/unix/thread.rs:71:17
            61: start_thread
            62: __GI___clone
          

thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (349b3b324 2020-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z fuel=rand_core=0 -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rand_core`

Caused by:
  process didn't exit successfully: `rustc --crate-name rand_core --edition=2018 /home/anders/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=4da4ae534686a8b2 -C extra-filename=-4da4ae534686a8b2 --out-dir /tmp/fuel-test/target/release/deps -L dependency=/tmp/fuel-test/target/release/deps --cap-lints allow -Z fuel=rand_core=0` (exit code: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by andersk** [comment]
`-Z trim-diagnostic-paths=no` is a workaround.

**Comment by andersk** [comment]
Minimal reproduction without Cargo:

```rs
struct S;
fn main() {}
```

```console
$ rustc test.rs --cap-lints allow -Z fuel=test=0
error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: rustc_errors::Handler::delay_good_path_bug
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_data_structures::stack::ensure_sufficient_stack
             3: rustc_query_system::query::plumbing::get_query_impl
             4: rustc_query_system::query::plumbing::get_query
             5: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
             6: rustc_middle::ty::print::pretty::<impl rustc_middle::ty::context::TyCtxt>::def_path_str_with_substs
             7: rustc_session::session::Session::consider_optimizing
             8: rustc_middle::ty::context::TyCtxt::consider_optimizing
             9: rustc_middle::ty::ReprOptions::new
            10: rustc_typeck::collect::adt_def
            11: rustc_query_system::query::plumbing::get_query_impl
            12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::adt_def
            13: rustc_typeck::collect::type_of::type_of
            14: rustc_query_system::query::plumbing::get_query_impl
            15: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
            16: rustc_typeck::collect::convert_item
            17: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item
            18: rustc_middle::hir::map::Map::visit_item_likes_in_module
            19: rustc_typeck::collect::collect_mod_item_types
            20: rustc_query_system::query::plumbing::get_query_impl
            21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_mod_item_types
            22: rustc_session::session::Session::track_errors
            23: rustc_typeck::check_crate
            24: rustc_interface::passes::analysis
            25: rustc_query_system::query::plumbing::get_query_impl
            26: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            27: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
            28: rustc_span::with_source_map
            29: rustc_interface::interface::create_compiler_and_run
            30: scoped_tls::ScopedKey<T>::set
            31: std::sys_common::backtrace::__rust_begin_short_backtrace
            32: core::ops::function::FnOnce::call_once{{vtable.shim}}
            33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/a6ece56152d8eb11e049e9fcce147b2859e12c92/library/alloc/src/boxed.rs:1572:9
            34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/a6ece56152d8eb11e049e9fcce147b2859e12c92/library/alloc/src/boxed.rs:1572:9
            35: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/a6ece56152d8eb11e049e9fcce147b2859e12c92/library/std/src/sys/unix/thread.rs:91:17
            36: start_thread
            37: __clone
          

thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:1050:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (a6ece5615 2021-08-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z fuel=test=0

query stack during panic:
end of query stack
```

**Comment by ryanolf** [comment]
I am also seeing this panic, though perhaps unrelated because I don't have those flags. I don't have a minimal example yet. Here's my trace. Let me know if I should make another bug.
```
error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: std::backtrace::Backtrace::create
             1: rustc_errors::Handler::delay_good_path_bug
             2: rustc_middle::ty::print::pretty::trimmed_def_paths
             3: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
             4: rustc_data_structures::stack::ensure_sufficient_stack
             5: rustc_query_system::query::plumbing::try_execute_query
             6: rustc_query_system::query::plumbing::get_query
             7: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
             8: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
             9: rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_type
            10: rustc_middle::ty::print::pretty::<impl core::fmt::Display for &rustc_middle::ty::TyS>::fmt
            11: core::fmt::write
            12: alloc::fmt::format
            13: rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::recur
            14: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::try_fold
            15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
            16: core::iter::adapters::process_results
            17: rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::recur
            18: rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::recur
            19: rustc_mir_build::thir::pattern::const_to_pat::ConstToPat::to_pat
            20: rustc_infer::infer::InferCtxtBuilder::enter
            21: rustc_mir_build::thir::pattern::const_to_pat::<impl rustc_mir_build::thir::pattern::PatCtxt>::const_to_pat
            22: rustc_mir_build::thir::pattern::PatCtxt::lower_path
            23: rustc_mir_build::thir::pattern::PatCtxt::lower_pattern
            24: rustc_mir_build::thir::pattern::check_match::MatchVisitor::lower_pattern
            25: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
            26: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
            27: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
            28: rustc_hir::intravisit::walk_expr
            29: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
            30: rustc_hir::intravisit::walk_expr
            31: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
            32: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
            33: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
            34: rustc_mir_build::thir::pattern::check_match::check_match
            35: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            36: rustc_data_structures::stack::ensure_sufficient_stack
            37: rustc_query_system::query::plumbing::try_execute_query
            38: rustc_query_system::query::plumbing::get_query
            39: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
            40: rustc_session::utils::<impl rustc_session::session::Session>::time
            41: rustc_interface::passes::analysis
            42: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            43: rustc_data_structures::stack::ensure_sufficient_stack
            44: rustc_query_system::query::plumbing::try_execute_query
            45: rustc_query_system::query::plumbing::get_query
            46: rustc_interface::passes::QueryContext::enter
            47: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
            48: rustc_span::with_source_map
            49: scoped_tls::ScopedKey<T>::set
            50: std::sys_common::backtrace::__rust_begin_short_backtrace
            51: core::ops::function::FnOnce::call_once{{vtable.shim}}
            52: std::sys::unix::thread::Thread::new::thread_start
            53: _pthread_jit_write_protect_np
          

thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:1165:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (9dd4ce80f 2021-09-17) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

**Comment by ryanolf** [comment]
I found a minimal example and opened a new issue, #89088. Same error message, very different example. Seems unrelated.
