### ISSUE TITLE
internal compiler error when inferring `_` type for Associated Type bound

### ISSUE THREAD

**Issue by woodsmur** [rust-lang/rust#79590]
Rust compiler error for simple code like this:

### Code

[playaround](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1059ed9242a9b0abf87e052667a17085)
```Rust
trait Database: Restriction<Inner = u32> {}

trait Restriction {
    type Inner;
}

struct Test {}

impl Database for Test {}
impl Restriction for Test {
    type Inner = u32;
}

fn main() {
    let t = Test {};
    let x: &dyn Database<Inner = _> = &t;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-apple-darwin
release: 1.48.0
LLVM version: 11.0
```

### Error output

```
   Compiling aaaa v0.1.0 (/Users/dudu/tmp/aaaa)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/main.rs:16:13
   |
16 |     let x: &Database<Inner = _> = &t;
   |             ^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Database<Inner = _>`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: unused variable: `x`
  --> src/main.rs:16:9
   |
16 |     let x: &Database<Inner = _> = &t;
   |         ^ help: if this is intentional, prefix it with an underscore: `_x`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: Error finalizing incremental compilation session directory `/Users/dudu/tmp/aaaa/target/debug/incremental/aaaa-3t9641te2lvvd/s-ftkew3bbem-6oinlz-working`: No such file or directory (os error 2)

warning: 3 warnings emitted

error: internal compiler error: broken MIR in DefId(0:10 ~ aaaa[fab6]::main) (CanonicalUserTypeAnnotation { user_ty: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Ty(General(U0)) }, CanonicalVarInfo { kind: Region(U0) }], value: Ty(&dyn Database<Inner = ^1_1, Inner = u32>) }, span: src/main.rs:16:12: 16:32 (#0), inferred_ty: &dyn Database<Inner = u32, Inner = u32> }): bad user type (&dyn Database<Inner = _, Inner = u32> = &dyn Database<Inner = u32, Inner = u32>): NoSolution
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:258:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:961:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0 (7eac88abb 2020-11-16) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `aaaa`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Reproduces on stable, beta and nightly.

**Comment by matthiaskrgr** [comment]
The ICE triggers since 1.45

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379590.20internal.20compiler.20error.3A.20unexpected.20pan.E2.80.A6) in the prioritization working group.

**Comment by osa1** [comment]
I'm trying to debug this and have a question on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Multiple.20associated.20types.20in.20TyS.20when.20the.20user-written.20type) (also copied to [internals]( https://internals.rust-lang.org/t/multiple-associated-types-in-tys-when-the-user-written-type-has-one/13939/2)). If anyone have any pointers that would be helpful.

**Comment by osa1** [comment]
I found the code where we add the duplicate `Inner = _` predicate mentioned in the Zulip and internals links above, and confirmed that if I don't add the duplicate the program compiles fine. I'm not 100% sure this is the root cause but I think having two predicates for the same associated type doesn't make sense so I'm hopeful.

If I remove the code block that adds the duplicate predicate I get 8 UI test failures. I'll try to figure out why that code exists by looking at failing tests now.

**Comment by pnkfelix** [comment]
Visiting for P-high review

@lcnr is there a roadmap for resolving this? Should we open it up for other people to claim?

(The error does seem like it remains P-high worthy, since I can imagine this to be pretty frustrating to someone since it doesn't print any diagnostic info guiding them towards even the obvious workaround of plugging in `u32` for the `_` type)

**Comment by lcnr** [comment]
The issue here is that the associated type bound is redundant, we're specifying `Inner` on `Database` even though that one is already fully constrained by the trait definition of `Database` itself.

I don't think it necessarily needs a roadmap, I expect it to be a fairly self-contained - if complex - fix.

**Comment by compiler-errors** [comment]
I've taken a look at this in the past but I can again 👀

**Comment by compiler-errors** [comment]
This was fixed by #136458.
