### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/query/mod.rs:235:5

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#79661]
### Code

This happened while working on cg_clif.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (f4db9ffb2 2020-12-02)
binary: rustc
commit-hash: f4db9ffb22dfcb702dbdb2e0607cb91791866b57
commit-date: 2020-12-02
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
   Compiling rustc_codegen_cranelift v0.1.0 (/home/bjorn/Documenten/cg_clif3)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/query/mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4db9ffb22dfcb702dbdb2e0607cb91791866b57/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/f4db9ffb22dfcb702dbdb2e0607cb91791866b57/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/f4db9ffb22dfcb702dbdb2e0607cb91791866b57/library/core/src/panicking.rs:50:5
   3: rustc_middle::ty::query::try_load_from_on_disk_cache
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: rustc_incremental::persist::save::save_in
   7: rustc_data_structures::sync::join
   8: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   9: rustc_incremental::persist::save::save_dep_graph
  10: rustc_codegen_ssa::base::finalize_tcx
  11: rustc_codegen_ssa::base::codegen_crate
  12: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  13: rustc_interface::queries::Queries::ongoing_codegen
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (f4db9ffb2 2020-12-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z run_dsymutil=no -C opt-level=3 -C embed-bitcode=no -C incremental -C link-arg=-Wl,-rpath=$ORIGIN/../lib --crate-type dylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', /rustc/f4db9ffb22dfcb702dbdb2e0607cb91791866b57/compiler/rustc_codegen_ssa/src/back/write.rs:1425:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4db9ffb22dfcb702dbdb2e0607cb91791866b57/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/f4db9ffb22dfcb702dbdb2e0607cb91791866b57/library/core/src/panicking.rs:92:14
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (f4db9ffb2 2020-12-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z run_dsymutil=no -C opt-level=3 -C embed-bitcode=no -C incremental -C link-arg=-Wl,-rpath=$ORIGIN/../lib --crate-type dylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rustc_codegen_cranelift`

To learn more, run the command again with --verbose.
```

**Comment by bjorn3** [comment]
Removing the incremental cache fixed the issue.

**Comment by bjorn3** [comment]
Just saw this again.

**Comment by bjorn3** [comment]
I have hit this like 10 times now.

**Comment by wesleywiser** [comment]
Would you be able to push your changes to a branch or tag so we can try to repro? Thanks!

**Comment by bjorn3** [comment]
This is bjorn3/rustc_codegen_cranelift@d95d03ae8ad10f253dce81a62a9ac372835b9bb4 with the following patch:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index ba9ee0d..82a88b1 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -204,11 +204,7 @@ fn codegen_crate<'tcx>(
         metadata: EncodedMetadata,
         need_metadata_module: bool,
     ) -> Box<dyn Any> {
-        let res = driver::codegen_crate(tcx, metadata, need_metadata_module, self.config);
-
-        rustc_symbol_mangling::test::report_symbol_names(tcx);
-
-        res
+        driver::codegen_crate(tcx, metadata, need_metadata_module, self.config)
     }
 
     fn join_codegen(
@@ -229,8 +225,6 @@ fn link(
     ) -> Result<(), ErrorReported> {
         use rustc_codegen_ssa::back::link::link_binary;
 
-        let _timer = sess.prof.generic_activity("link_crate");
-
         sess.time("linking", || {
             let target_cpu = crate::target_triple(sess).to_string();
             link_binary::<crate::archive::ArArchiveBuilder<'_>>(
```

The first time I hit this I think it was with just that patch. I have been working on https://github.com/bytecodealliance/wasmtime/pull/2403 though and patched cg_clif to use a local checkout. This is something like https://github.com/bytecodealliance/wasmtime/pull/2403/commits/2fea3003df4684ab3ffa1633b5f59c3f99a2b21e. I don't have any clear instructions to reproduce it, but I have seen it quite often today.

**Comment by poliorcetics** [comment]
The line in question is currently `rustc_cached_queries!(try_load_from_on_disk_cache!);`, removing cache seems like the recommandable workaround for now, as you said earlier.

**Comment by jyn514** [comment]
I ran into this running `x.py clippy` on 0ad3dce83a4506875e6b1381f5261e458b5c5d98 with clippy version `clippy 0.0.212 (f4db9ff 2020-12-02)`.

**Comment by matthiaskrgr** [comment]
I see this on [ci](https://github.com/matthiaskrgr/cargo-cache/runs/1490283450?check_suite_focus=true#step:12:6) for my `cargo-cache` crate as well but I didn't manage to reproduce locally yet.

**Comment by vext01** [comment]
I'm getting this on ykrustc too. We last synced with upstream rust on December 3rd.

It only seems to happen on an incremental build (i.e. not on a fresh build). I was able to trigger the error by adding more and more `dbg!("x")` lines and rebuilding until it crashed.

**Comment by wesleywiser** [comment]
cc @Aaron1011 It looks like we're seeing some regressions from #74967

**Comment by Aaron1011** [comment]
I'm not able to reproduce this locally.

@bjorn3 Could you try to write a script that reproduces this crash with `rustc_codegen_cranelift`?

**Comment by jyn514** [comment]
@Aaron1011 can you reproduce it using clippy? https://github.com/rust-lang/rust/issues/79661#issuecomment-738357285

**Comment by Aaron1011** [comment]
I managed to reproduce this using https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2032

**Comment by Aaron1011** [comment]
I've fixed the isusue locally, and I'm working on a PR.

**Comment by hameerabbasi** [comment]
Labelling `P-high` [as discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379661.20thread.20'rustc'.20panicked.20at.20'called.20.60Opt.E2.80.A6).
