### ISSUE TITLE
ICE: "unwrap called on None" during futures 0.1 -> 0.3 migration

### ISSUE THREAD

**Issue by drahnr** [rust-lang/rust#79702]
I tried this code:

```rust
<code>
```

```sh
git clone https://github.com/paritytech/sccache sccache-demo2
cd sccache-demo2
git checkout bernhard-rustc-none-unwrap
cargo b
```

I expected to see this happen: `rustc` completing with errors

Instead, this happened: `unwrap` on a `None` value

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0

```

<details><summary>Backtrace</summary>
<p>

```

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/librustc_hir/definitions.rs:316:35
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /home/bernhard/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1095
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /home/bernhard/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libproc_macro/bridge/client.rs:318
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  14: rust_begin_unwind
             at src/libstd/panicking.rs:437
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  16: core::panicking::panic
             at src/libcore/panicking.rs:50
  17: rustc_middle::hir::map::Map::def_kind
  18: core::ops::function::FnOnce::call_once
  19: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::get_query_impl
  23: rustc_middle::ty::util::<impl rustc_middle::ty::context::TyCtxt>::closure_base_def_id
  24: rustc_typeck::collect::generics_of
  25: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::generics_of>::compute
  26: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  28: rustc_data_structures::stack::ensure_sufficient_stack
  29: rustc_query_system::query::plumbing::get_query_impl
  30: rustc_query_system::query::plumbing::ensure_query_impl
  31: rustc_hir::intravisit::walk_expr
  32: rustc_hir::intravisit::walk_expr
  33: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  34: rustc_hir::intravisit::Visitor::visit_stmt
  35: rustc_hir::intravisit::walk_expr
  36: rustc_hir::intravisit::walk_body
  37: rustc_hir::intravisit::walk_trait_item
  38: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_trait_item
  39: rustc_middle::hir::map::Map::visit_item_likes_in_module
  40: rustc_typeck::collect::collect_mod_item_types
  41: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_mod_item_types>::compute
  42: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  43: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  44: rustc_data_structures::stack::ensure_sufficient_stack
  45: rustc_query_system::query::plumbing::get_query_impl
  46: rustc_query_system::query::plumbing::ensure_query_impl
  47: rustc_session::session::Session::track_errors
  48: rustc_typeck::check_crate
  49: rustc_interface::passes::analysis
  50: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  51: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  52: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  53: rustc_query_system::query::plumbing::get_query_impl
  54: rustc_middle::ty::context::tls::enter_global
  55: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  56: rustc_span::with_source_map
  57: rustc_interface::interface::create_compiler_and_run
  58: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0 (04488afe3 2020-08-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-arg=-fuse-ld=lld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [def_kind] looking up definition kind of `compiler::compiler::CompilerHasher::get_cached_or_compile::{{closure}}#0`
#1 [generics_of] computing generics of `compiler::compiler::CompilerHasher::get_cached_or_compile::{{closure}}#0::{{closure}}#0`
#2 [collect_mod_item_types] collecting item types in module `compiler::compiler`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 12 previous errors; 20 warnings emitted

Some errors have detailed explanations: E0423, E0425, E0706, E0728.
For more information about an error, try `rustc --explain E0423`.
error: could not compile `sccache`.

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by jyn514** [comment]
This is using 1.46.0. Does the same issue occur on nightly?

**Comment by camelid** [comment]
> This is using 1.46.0. Does the same issue occur on nightly?

@drahnr ^

**Comment by drahnr** [comment]
Just tested against 1.48 and that works. For some reason my toolchain was stuck at 1.46, but that's a different issue (no overrides present).

Nightly is also producing the expected error message.

I think this is ready to be closed, sorry for the noise.
