### ISSUE TITLE
Cast into constant-value generic parameter type causes rust compiler to crash

### ISSUE THREAD

**Issue by skejeton** [rust-lang/rust#79745]
### Code

Code that makes compiler crash
```Rust
tele.get_buf() as &buffer::Buffer<VgaChar, 2000>
```

passed into

```Rust
pub const T_WIDTH: usize = 80;
pub const T_HEIGHT: usize = 25;
pub const T_SIZE: usize = T_WIDTH*T_HEIGHT;

pub fn vga_text_swap(buf: &crate::buffer::Buffer<VgaChar, T_SIZE>)
```

declaration of Buffer
```Rust
pub struct Buffer<T: Default + Copy, const S: usize>
{
    contains: [T; S]
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
binary: rustc
commit-hash: 1c389ffeff814726dec325f0f2b0c99107df2673
commit-date: 2020-11-24
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 3', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: rustc 1.50.0-nightly (1c389ffef 2020-11-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options -C opt-level=2 -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_implements_trait] evaluating `type_implements_trait` `(DefId(1:1974 ~ core[a213]::convert::From), &buffer::Buffer<vga_text::VgaChar, 2000_usize>, [&buffer::Buffer<u8, {_: usize}>], ParamEnv { caller_bounds: [], reveal: UserFacing })`
#1 [typeck] type-checking `prelude`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 3', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:69:5
   3: ena::unify::UnificationTable<S>::probe_value
   4: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::TypeFolder>::fold_const
   5: rustc_middle::ty::fold::TypeFoldable::fold_with
   6: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
   7: <rustc_infer::infer::canonical::canonicalizer::Canonicalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
   8: rustc_middle::ty::fold::TypeFoldable::fold_with
   9: rustc_middle::ty::fold::TypeFoldable::fold_with
  10: rustc_middle::ty::fold::TypeFoldable::fold_with
  11: rustc_infer::infer::canonical::canonicalizer::Canonicalizer::canonicalize
  12: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  13: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  14: rustc_infer::infer::InferCtxtBuilder::enter
  15: rustc_trait_selection::traits::type_implements_trait
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::type_implements_trait>::compute
  17: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  18: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  19: rustc_data_structures::stack::ensure_sufficient_stack
  20: rustc_query_system::query::plumbing::get_query_impl
  21: rustc_typeck::check::cast::CastCheck::check
  22: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_casts
  23: rustc_infer::infer::InferCtxtBuilder::enter
  24: rustc_typeck::check::typeck
  25: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  26: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  28: rustc_data_structures::stack::ensure_sufficient_stack
  29: rustc_query_system::query::plumbing::get_query_impl
  30: rustc_query_system::query::plumbing::ensure_query_impl
  31: rustc_typeck::check::typeck_item_bodies
  32: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  33: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  34: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  35: rustc_data_structures::stack::ensure_sufficient_stack
  36: rustc_query_system::query::plumbing::get_query_impl
  37: rustc_typeck::check_crate
  38: rustc_interface::passes::analysis
  39: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  40: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  41: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  42: rustc_data_structures::stack::ensure_sufficient_stack
  43: rustc_query_system::query::plumbing::get_query_impl
  44: rustc_interface::passes::QueryContext::enter
  45: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  46: rustc_span::with_source_map
  47: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by camelid** [comment]
@ishidex2 I tried to reproduce with this:

```rust
#![feature(min_const_generics)]

pub struct Buffer<T: Default + Copy, const S: usize> {
    contains: [T; S],
}

pub const T_WIDTH: usize = 80;
pub const T_HEIGHT: usize = 25;
pub const T_SIZE: usize = T_WIDTH * T_HEIGHT;

#[derive(Clone, Copy, Default)]
pub struct VgaChar(char);

pub fn vga_text_swap(buf: &Buffer<VgaChar, T_SIZE>) {}

fn main() {
    let buf = &Buffer {
        contains: [VgaChar('a'); 2000],
    };
    vga_text_swap(buf as &Buffer<VgaChar, 2000>);
}
```

But it compiles fine on nightly-2020-12-03. Can you try with nightly-2020-12-03 and see if it works?

**Comment by camelid** [comment]
Also, it would be helpful if you could provide some information about what `tele.get_buf()` returns.

**Comment by Enselic** [comment]
Triage: Since there currently is no known way to reproduce this ICE, I will close this issue. Without a way for others to reproduce, not much can be done. Feel free to re-open if a way to reproduce is found.
