### ISSUE TITLE
Cargo/rustc issue

### ISSUE THREAD

**Issue by GreenBeard** [rust-lang/rust#79928]
### Code
Unknown which part (large library, and small test program). Apologizes for making your life more difficult, although as specified in **Meta** I suspect this is to do with `cargo`.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (3ff10e74a 2020-12-04)
binary: rustc
commit-hash: 3ff10e74a74ed093fcabac1de27fe1cd65bbbb4a
commit-date: 2020-12-04
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
<version>
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/query/mod.rs:235:5
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
    Updating git repository `https://github.com/GreenBeard/z3.rs`
    Updating git submodule `https://github.com/Z3Prover/z3.git`
    Updating crates.io index
   Compiling z3-sys v0.6.3 (https://github.com/GreenBeard/z3.rs#11859da6)
   Compiling z3 v0.9.0 (https://github.com/GreenBeard/z3.rs#11859da6)
   Compiling rust_z3 v0.1.0 (/home/alex/workspace/rust_z3)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/query/mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3ff10e74a74ed093fcabac1de27fe1cd65bbbb4a/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/3ff10e74a74ed093fcabac1de27fe1cd65bbbb4a/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/3ff10e74a74ed093fcabac1de27fe1cd65bbbb4a/library/core/src/panicking.rs:50:5
   3: rustc_middle::ty::query::try_load_from_on_disk_cache
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   5: rustc_incremental::persist::save::save_in
   6: rustc_data_structures::sync::join
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   8: rustc_incremental::persist::save::save_dep_graph
   9: rustc_codegen_ssa::base::finalize_tcx
  10: rustc_codegen_ssa::base::codegen_crate
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  12: rustc_interface::queries::Queries::ongoing_codegen
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (3ff10e74a 2020-12-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rust_z3`

To learn more, run the command again with --verbose.

```

</p>
</details>

Edit: Let me know if I can do anything specific to help pinpoint this bug.

**Comment by GreenBeard** [comment]
Hmm, this may be a duplicate of #79661. Feel free to close this.

**Comment by mati865** [comment]
Most likely it's the duplicate. You should try with latest nightly.
