### ISSUE TITLE
x.py build fails with `download-ci-llvm = true`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#80086]
I just started running into this recently - maybe `llvm-dwp` stopped being packaged recently? I think the fix is just to make it optional in bootstrap.

```
$ x.py build
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
thread 'main' panicked at 'src.symlink_metadata() failed with No such file or directory (os error 2)', src/bootstrap/lib.rs:1216:24
```

<details><summary>Backtrace</summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/21dea46d8347c8b4117c5567949703f0fbb51649/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/21dea46d8347c8b4117c5567949703f0fbb51649/library/std/src/panicking.rs:437:5
   2: bootstrap::Build::copy
             at ./src/bootstrap/lib.rs:1216:24
   3: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
             at ./src/bootstrap/compile.rs:990:13
   4: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:1474:23
   5: bootstrap::builder::Builder::compiler
             at ./src/bootstrap/builder.rs:578:9
   6: <bootstrap::compile::Std as bootstrap::builder::Step>::make_run
             at ./src/bootstrap/compile.rs:48:23
   7: bootstrap::builder::StepDescription::maybe_run
             at ./src/bootstrap/builder.rs:179:13
   8: bootstrap::builder::StepDescription::run
             at ./src/bootstrap/builder.rs:200:25
   9: bootstrap::builder::Builder::run_step_descriptions
             at ./src/bootstrap/builder.rs:570:9
  10: bootstrap::builder::Builder::execute_cli
             at ./src/bootstrap/builder.rs:561:9
  11: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:509:13
  12: bootstrap::main
             at ./src/bootstrap/bin/main.rs:30:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/21dea46d8347c8b4117c5567949703f0fbb51649/library/core/src/ops/function.rs:227:5
```

</details>

A workaround is `touch build/x86_64-unknown-linux-gnu/ci-llvm/bin/llvm-dwp`.

**Comment by jyn514** [comment]
`git merge-base HEAD master` reports 2ba7ca2bbbff6cd424aebc654308febc00b9497a.

**Comment by jyn514** [comment]
This is likely a regression from https://github.com/rust-lang/rust/pull/77117, cc @davidtwco

**Comment by tgnottingham** [comment]
Hitting this despite doing `rm -r build` and updating to latest. The workaround works though.

**Comment by jyn514** [comment]
Yup, this still fails for me after b32e6e6ac8921035177256ab6806e6ab0d4b9b94.

**Comment by Mark-Simulacrum** [comment]
Oh, we forgot to bump the stamp file so we're not downloading a fresh copy.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/blob/master/src/bootstrap/download-ci-llvm-stamp should be bumped in a PR to fix this.
