### ISSUE TITLE
thread 'rustc' panicked at 'Failed to recover key for type_of(67d9c01528728aa0-119cad37ba2666f0) with hash 67d9c01528728aa0-119cad37ba2666f0', compiler/rustc_middle/src/ty/query/mod.rs:235:5

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#80152]
### Code

I was working on [Yorick](https://github.com/softdevteam/yk).

### Meta

Commit https://github.com/softdevteam/ykrustc/commit/5ccb675d43f2dda2917b1afc5e48d1c9f10a7e8f

### Error output

<details>
<p>

```
thread 'rustc' panicked at 'Failed to recover key for type_of(67d9c01528728aa0-119cad37ba2666f0) with hash 67d9c01528728aa0-119cad37ba2666f0', compiler/rustc_middle/src/ty/query/mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_middle::ty::query::try_load_from_on_disk_cache::{{closure}}
   3: rustc_middle::ty::query::try_load_from_on_disk_cache
   4: rustc_middle::ty::query::on_disk_cache::OnDiskCache::serialize::{{closure}}
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   6: rustc_session::utils::<impl rustc_session::session::Session>::time
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   8: rustc_incremental::persist::save::save_dep_graph
   9: rustc_codegen_ssa::base::finalize_tcx
  10: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: rustc_session::utils::<impl rustc_session::session::Session>::time
  12: rustc_interface::queries::Queries::ongoing_codegen
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C tracer=hw --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `ykrt`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'Failed to recover key for type_of(67d9c01528728aa0-119cad37ba2666f0) with hash 67d9c01528728aa0-119cad37ba2666f0', compiler/rustc_middle/src/ty/query/mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_middle::ty::query::try_load_from_on_disk_cache::{{closure}}
   3: rustc_middle::ty::query::try_load_from_on_disk_cache
   4: rustc_middle::ty::query::on_disk_cache::OnDiskCache::serialize::{{closure}}
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   6: rustc_session::utils::<impl rustc_session::session::Session>::time
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   8: rustc_incremental::persist::save::save_dep_graph
   9: rustc_codegen_ssa::base::finalize_tcx
  10: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: rustc_session::utils::<impl rustc_session::session::Session>::time
  12: rustc_interface::queries::Queries::ongoing_codegen
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C tracer=hw

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', /home/bjorn3/ykrustc/compiler/rustc_codegen_ssa/src/back/write.rs:1425:21
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rustc_codegen_ssa::back::write::start_executing_work::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C tracer=hw

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: build failed
```

</p>
</details>

**Comment by Aaron1011** [comment]
@bjorn3: I assume that this occured when building using a stage1 ykrustc? If so, you're missing commit https://github.com/rust-lang/rust/commit/19eb1c4c526071c430c05fffc64da71ac057a3d5 which fixes this issue.

In the future, please include the upstream rustc commit that a particular build of ykrustc is based on.

**Comment by bjorn3** [comment]
> I assume that this occured when building using a stage1 ykrustc?

Yes

> If so, you're missing commit 19eb1c4 which fixes this issue.

Thanks for pointing me to that commit. I will suggest another sync.

> In the future, please include the upstream rustc commit that a particular build of ykrustc is based on.

Sure. I will do that in the future.
