### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds: the len is 76 but the index is 76',

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust#80151]
### Code

```Rust
/*
cargo run -p async-ssh2-lite-demo-smol --bin proxy_jump intranet.com:22 intranet_user bastion.com:22 bastion_user
*/

#![recursion_limit = "256"]

use std::env;
use std::io;
use std::net::{TcpStream, ToSocketAddrs};
use std::sync::Arc;

use async_executor::{Executor, LocalExecutor, Task};
use async_io::Async;
use easy_parallel::Parallel;
use futures::executor::block_on;
use futures::future::FutureExt;
use futures::select;
use futures::{AsyncReadExt, AsyncWriteExt};

#[cfg(not(unix))]
use std::net::TcpListener;
#[cfg(unix)]
use std::os::unix::net::{UnixListener, UnixStream};
#[cfg(unix)]
use tempfile::tempdir;

use async_ssh2_lite::AsyncSession;

fn main() -> io::Result<()> {
    let ex = Executor::new();
    let ex = Arc::new(ex);
    let local_ex = LocalExecutor::new();
    let (trigger, shutdown) = async_channel::unbounded::<()>();

    let ret_vec: (_, io::Result<()>) = Parallel::new()
        .each(0..4, |_| {
            block_on(ex.run(async {
                shutdown
                    .recv()
                    .await
                    .map_err(|err| io::Error::new(io::ErrorKind::Other, err))
            }))
        })
        .finish(|| {
            block_on(local_ex.run(async {
                run(ex.clone()).await?;

                drop(trigger);

                Ok(())
            }))
        });

    println!("ret_vec: {:?}", ret_vec);

    Ok(())
}

async fn run(ex: Arc<Executor<'_>>) -> io::Result<()> {
    let addr = env::args()
        .nth(1)
        .unwrap_or_else(|| env::var("ADDR").unwrap_or("127.0.0.1:22".to_owned()));
    let username = env::args()
        .nth(2)
        .unwrap_or_else(|| env::var("USERNAME").unwrap_or("root".to_owned()));
    let bastion_addr = env::args()
        .nth(3)
        .unwrap_or_else(|| env::var("BASTION_ADDR").unwrap_or("127.0.0.1:22".to_owned()));
    let bastion_username = env::args()
        .nth(4)
        .unwrap_or_else(|| env::var("BASTION_USERNAME").unwrap_or("root".to_owned()));

    let addr = addr.to_socket_addrs().unwrap().next().unwrap();
    let bastion_addr = bastion_addr.to_socket_addrs().unwrap().next().unwrap();

    //
    let mut receivers = vec![];
    let (sender_with_main, receiver) = async_channel::unbounded();
    receivers.push(receiver);
    let (sender_with_forward, receiver) = async_channel::unbounded();
    receivers.push(receiver);

    let task_with_main: Task<io::Result<()>> = ex.clone().spawn(async move {
        let bastion_stream = Async::<TcpStream>::connect(bastion_addr).await?;

        let mut bastion_session = AsyncSession::new(bastion_stream, None)?;

        bastion_session.handshake().await?;

        bastion_session
            .userauth_agent(bastion_username.as_ref())
            .await?;

        if !bastion_session.authenticated() {
            return Err(bastion_session
                .last_error()
                .and_then(|err| Some(io::Error::from(err)))
                .unwrap_or(io::Error::new(
                    io::ErrorKind::Other,
                    "bastion unknown userauth error",
                )));
        }

        let mut channel = bastion_session.channel_session().await?;
        channel.exec("hostname").await?;
        let mut s = String::new();
        channel.read_to_string(&mut s).await?;
        println!("bastion hostname: {}", s);
        channel.close().await?;
        println!("bastion channel exit_status: {}", channel.exit_status()?);

        let remote_port = 4444;
        let (mut  bastion_channel, _) = bastion_session
            .channel_forward_listen(remote_port, None, None)
            .await?;

        //
        loop {
            let mut channel =  bastion_channel.accept().await?;

            let task_with_forward: Task<io::Result<()>> = ex.clone().spawn(async move {
                let mut buf_bastion_channel = vec![0_u8; 2048];
                let mut buf_forward_stream_r = vec![0_u8; 2048];


            let (mut forward_stream_r, mut forward_stream_w) = {
                // cfg_if::cfg_if! {
                //     if #[cfg(unix)] {
                //         let dir = tempdir()?;
                //         let path = dir.path().join("ssh_channel_direct_tcpip");
                //         let listener = Async::<UnixListener>::bind(&path)?;
                //         let stream_s = Async::<UnixStream>::connect(&path).await?;
                //     } else {
                //         let listen_addr = TcpListener::bind("localhost:0")
                //             .unwrap()
                //             .local_addr()
                //             .unwrap();
                //         let listener = Async::<TcpListener>::bind(listen_addr)?;
                        let stream_s = Async::<TcpStream>::connect("127.0.0.1:22".to_socket_addrs().unwrap().next().unwrap()).await?;
                    // }
                // }

                // let (stream_r,_) = listener.accept().await.unwrap();

                stream_s.split()
            };

            loop {
                select! {
                    ret_forward_stream_r = forward_stream_r.read(&mut buf_forward_stream_r).fuse() => match ret_forward_stream_r {
                        Ok(n) if n == 0 => {
                            println!("forward_stream_r read 0");
                            break
                        },
                        Ok(n) => {
                            println!("forward_stream_r read {}", n);
                            channel.write(&buf_forward_stream_r[..n]).await.map(|_| ()).map_err(|err| {
                                eprintln!("bastion_channel write failed, err {:?}", err);
                                err
                            })?
                        },
                        Err(err) =>  {
                            eprintln!("forward_stream_r read failed, err {:?}", err);

                            return Err(err);
                        }
                    },
                    ret_bastion_channel = channel.read(&mut buf_bastion_channel).fuse() => match ret_bastion_channel {
                        Ok(n) if n == 0 => {
                            println!("bastion_channel read 0");
                            break
                        },
                        Ok(n) => {
                            println!("bastion_channel read {}", n);
                            forward_stream_w.write(&buf_bastion_channel[..n]).await.map(|_| ()).map_err(|err| {
                                eprintln!("forward_stream_r write failed, err {:?}", err);
                                err
                            })?
                        },
                        Err(err) => {
                            eprintln!("bastion_channel read failed, err {:?}", err);

                            return Err(err);
                        }
                    },
                }
            }


            Ok(())
        });
        task_with_forward.detach();
        }

            sender_with_forward.clone().send("done_with_forward").await.unwrap();
        //
        // let mut session = AsyncSession::new(forward_stream_r, None)?;
        // session.handshake().await?;
        //
        // session.userauth_agent(username.as_ref()).await?;
        //
        // if !session.authenticated() {
        //     return Err(session
        //         .last_error()
        //         .and_then(|err| Some(io::Error::from(err)))
        //         .unwrap_or(io::Error::new(
        //             io::ErrorKind::Other,
        //             "unknown userauth error",
        //         )));
        // }
        //
        // let mut channel = session.channel_session().await?;
        // channel.exec("hostname").await?;
        // let mut s = String::new();
        // channel.read_to_string(&mut s).await?;
        // println!("hostname: {}", s);
        // channel.close().await?;
        // println!("channel exit_status: {}", channel.exit_status()?);
        //
        // session.disconnect(None, "foo", None).await?;
        //
        // sender_with_main.send("done_with_main").await.unwrap();

        Ok(())
    });

    //
    task_with_main.await.map_err(|err| {
        eprintln!("task_with_main run failed, err {:?}", err);

        err
    })?;

    for receiver in receivers {
        let msg = receiver.recv().await.unwrap();
        println!("{}", msg);
    }

    Ok(())
}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

thread 'rustc' panicked at 'index out of bounds: the len is 76 but the index is 76', compiler/rustc_middle/src/ty/query/on_disk_cache.rs:458:9
thread 'rustc' panicked at 'index out of bounds: the len is 71 but the index is 71', compiler/rustc_middle/src/ty/query/on_disk_cache.rs:458:9
stack backtrace:
stack backtrace:
   0: rust_begin_unwind
   0: rust_begin_unwind
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/core/src/panicking.rs:69:5
   3: rustc_middle::ty::query::on_disk_cache::OnDiskCache::def_path_hash_to_def_id
   4: rustc_middle::ty::query::force_from_dep_node
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
   8: rustc_data_structures::stack::ensure_sufficient_stack
   9: rustc_query_system::query::plumbing::get_query_impl
  10: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::dropck_outlives::AtExt>::dropck_outlives
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/core/src/panicking.rs:69:5
   3: rustc_middle::ty::query::on_disk_cache::OnDiskCache::def_path_hash_to_def_id
   4: rustc_middle::ty::query::force_from_dep_node
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
   8: rustc_data_structures::stack::ensure_sufficient_stack
   9: rustc_query_system::query::plumbing::get_query_impl
  10: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::dropck_outlives::AtExt>::dropck_outlives
  11: rustc_typeck::check::dropck::check_drop_obligations
  12: rustc_hir::hir::Pat::walk_
  13: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_local
  14: rustc_hir::intravisit::walk_expr
  15: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  16: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  17: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  18: rustc_typeck::check::regionck::RegionCtxt::visit_fn_body
  19: rustc_hir::intravisit::walk_expr
  20: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  21: rustc_hir::intravisit::walk_expr
  22: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  23: rustc_typeck::check::regionck::RegionCtxt::visit_fn_body
  24: rustc_typeck::check::regionck::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::regionck_fn
  25: rustc_infer::infer::InferCtxtBuilder::enter
  26: rustc_typeck::check::typeck
  27: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  28: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  29: rustc_data_structures::stack::ensure_sufficient_stack
  30: rustc_query_system::query::plumbing::get_query_impl
  31: rustc_middle::ty::context::TyCtxt::typeck_opt_const_arg
  32: rustc_mir_build::thir::cx::Cx::new
  33: rustc_infer::infer::InferCtxtBuilder::enter
  34: rustc_mir_build::build::mir_built
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_built>::compute
  36: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  37: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
  38: rustc_query_system::query::plumbing::get_query_impl
  39: rustc_mir::transform::check_unsafety::unsafety_check_result
  40: core::ops::function::FnOnce::call_once
  41: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  42: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  43: rustc_data_structures::stack::ensure_sufficient_stack
  44: rustc_query_system::query::plumbing::force_query_impl
  45: rustc_middle::ty::query::force_from_dep_node
  46: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  47: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  48: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  49: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  50: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
  51: rustc_data_structures::stack::ensure_sufficient_stack
  52: rustc_query_system::query::plumbing::get_query_impl
  53: rustc_typeck::check::check::check_item_type
  54: rustc_typeck::check::check::check_mod_item_types
  55: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_mod_item_types>::compute
  56: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  57: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  58: rustc_data_structures::stack::ensure_sufficient_stack
  59: rustc_query_system::query::plumbing::get_query_impl
  60: rustc_query_system::query::plumbing::ensure_query_impl
  61: rustc_session::utils::<impl rustc_session::session::Session>::time
  62: rustc_typeck::check_crate
  63: rustc_interface::passes::analysis
  11: rustc_typeck::check::dropck::check_drop_obligations
  12: rustc_hir::hir::Pat::walk_
  13: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_local
  64: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  14: rustc_hir::intravisit::walk_expr
  15: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  16: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  65: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  17: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  18: rustc_typeck::check::regionck::RegionCtxt::visit_fn_body
  19: rustc_hir::intravisit::walk_expr
  20: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  21: rustc_hir::intravisit::walk_expr
  22: <rustc_typeck::check::regionck::RegionCtxt as rustc_hir::intravisit::Visitor>::visit_expr
  66: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  23: rustc_typeck::check::regionck::RegionCtxt::visit_fn_body
  24: rustc_typeck::check::regionck::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::regionck_fn
  25: rustc_infer::infer::InferCtxtBuilder::enter
  67: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_typeck::check::typeck
  27: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  28: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  29: rustc_data_structures::stack::ensure_sufficient_stack
  30: rustc_query_system::query::plumbing::get_query_impl
  31: rustc_middle::ty::context::TyCtxt::typeck_opt_const_arg
  32: rustc_mir_build::thir::cx::Cx::new
  33: rustc_infer::infer::InferCtxtBuilder::enter
  34: rustc_mir_build::build::mir_built
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_built>::compute
  36: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  37: rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}
  38: rustc_query_system::query::plumbing::get_query_impl
  39: rustc_mir::transform::check_unsafety::unsafety_check_result
  40: core::ops::function::FnOnce::call_once
  41: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  68: rustc_query_system::query::plumbing::get_query_impl
  42: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  43: rustc_data_structures::stack::ensure_sufficient_stack
  44: rustc_query_system::query::plumbing::force_query_impl
  69: rustc_interface::passes::QueryContext::enter
  45: rustc_middle::ty::query::force_from_dep_node
  70: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  46: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  71: rustc_span::with_source_map
  47: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  72: rustc_interface::interface::create_compiler_and_run
  48: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  49: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  73: scoped_tls::ScopedKey<T>::set
  50: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  51: rustc_data_structures::stack::ensure_sufficient_stack
  52: rustc_query_system::query::plumbing::get_query_impl

  53: rustc_typeck::check::check::check_item_type
  54: rustc_typeck::check::check::check_mod_item_types
error: internal compiler error: unexpected panic
  55: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_mod_item_types>::compute

  56: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  57: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  58: rustc_data_structures::stack::ensure_sufficient_stack
  59: rustc_query_system::query::plumbing::get_query_impl
  60: rustc_query_system::query::plumbing::ensure_query_impl
  61: rustc_session::utils::<impl rustc_session::session::Session>::time
  62: rustc_typeck::check_crate
  63: rustc_interface::passes::analysis
  64: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  65: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  66: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  67: rustc_data_structures::stack::ensure_sufficient_stack
  68: rustc_query_system::query::plumbing::get_query_impl
note: the compiler unexpectedly panicked. this is a bug.
  69: rustc_interface::passes::QueryContext::enter
  70: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  71: rustc_span::with_source_map
  72: rustc_interface::interface::create_compiler_and_run
  73: scoped_tls::ScopedKey<T>::set

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (d32c320d7 2020-12-10) running on x86_64-unknown-linux-gnu
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin


note: some of the compiler flags provided by cargo are hidden
note: rustc 1.50.0-nightly (d32c320d7 2020-12-10) running on x86_64-unknown-linux-gnu

query stack during panic:

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [dropck_outlives] computing dropck types for `Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: std::vec::Vec<async_channel::Receiver<&str>> } }`
#1 [typeck] type-checking `run`
#2 [mir_built] building MIR for `run`
#3 [unsafety_check_result] unsafety-checking `run`
#4 [type_of] computing type of `run::{opaque#0}`
#5 [check_mod_item_types] checking item types in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
#0 [dropck_outlives] computing dropck types for `Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: std::vec::Vec<async_channel::Receiver<&str>> } }`
#1 [typeck] type-checking `run`
#2 [mir_built] building MIR for `run`
#3 [unsafety_check_result] unsafety-checking `run`
#4 [type_of] computing type of `run::{opaque#0}`
#5 [check_mod_item_types] checking item types in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by GopherJ** [comment]
rustc: *rustc 1.50.0-nightly (d32c320d7 2020-12-10)*

**Comment by GopherJ** [comment]
I tried to run cargo clean, it fixed the issue, but it can come again and happens quite frequently

**Comment by Aaron1011** [comment]
This should be fixed by https://github.com/rust-lang/rust/commit/19eb1c4c526071c430c05fffc64da71ac057a3d5 . Can you re-test on the latest nightly?

**Comment by GopherJ** [comment]
@Aaron1011 it looks better, but I'm not sure if it's fixed or not because if I clean the cache then the old version can also compile. Can I test it for days and tell you the beginning of the next week?

**Comment by Aaron1011** [comment]
Sure!

**Comment by GopherJ** [comment]
Hi, I think this can be closed because it doesn't happen to me anymore, thanks
