### ISSUE TITLE
ICE after WSL crash

### ISSUE THREAD

**Issue by panstromek** [rust-lang/rust#80516]
Whole WSL crashed during `cargo test` and me doing something in the IDE at the same time. The build folder probably got corrupted somehow, which is understandable in this situation. 

I don't really know if this is actionable or even meaningful to fix, but I reported it anyway, just in case.

### Code

```Rust

```

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (2d8a3b918 2020-08-26)
binary: rustc
commit-hash: 2d8a3b9181f41d3af9b9f016c5d73b2553e344bf
commit-date: 2020-08-26
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 11.0
```

### Error output

```
 $ cargo build --release
   Compiling booktool v0.1.0 (/home/matyas/zebra-fresh/booktool)
   Compiling legacy-zebra v0.1.0 (/home/matyas/zebra-fresh/legacy-zebra)
   Compiling practice v0.1.0 (/home/matyas/zebra-fresh/practice)
   Compiling enddev v0.1.0 (/home/matyas/zebra-fresh/enddev)
   Compiling scrzebra v0.1.0 (/home/matyas/zebra-fresh/scrzebra)
   Compiling wasm-simple v0.1.0 (/home/matyas/zebra-fresh/wasm-simple)
error: cannot determine resolution for the import
 --> practice/src/practice.rs:6:28
  |
6 | use engine::src::globals::{board_state};
  |                            ^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:7:26
  |
7 | use engine::src::moves::{make_move, moves_state, generate_all, valid_move, unmake_move};
  |                          ^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:7:37
  |
7 | use engine::src::moves::{make_move, moves_state, generate_all, valid_move, unmake_move};
  |                                     ^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:7:50
  |
7 | use engine::src::moves::{make_move, moves_state, generate_all, valid_move, unmake_move};
  |                                                  ^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:7:64
  |
7 | use engine::src::moves::{make_move, moves_state, generate_all, valid_move, unmake_move};
  |                                                                ^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:7:76
  |
7 | use engine::src::moves::{make_move, moves_state, generate_all, valid_move, unmake_move};
  |                                                                            ^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:8:28
  |
8 | use engine::src::osfbook::{get_hash, find_opening_name, g_book};
  |                            ^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:8:38
  |
8 | use engine::src::osfbook::{get_hash, find_opening_name, g_book};
  |                                      ^^^^^^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> practice/src/practice.rs:8:57
  |
8 | use engine::src::osfbook::{get_hash, find_opening_name, g_book};
  |                                                         ^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error[E0463]: can't find crate for `engine`
  --> wasm-simple/src/lib.rs:27:1
   |
27 | extern crate engine;
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `wasm-simple`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: cannot determine resolution for the import
 --> scrzebra/src/scrzebra.rs:5:25
  |
5 | use engine::src::game::{global_terminate, game_state};
  |                         ^^^^^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> scrzebra/src/scrzebra.rs:5:43
  |
5 | use engine::src::game::{global_terminate, game_state};
  |                                           ^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: cannot determine resolution for the import
 --> scrzebra/src/scrzebra.rs:6:29
  |
6 | use engine::src::myrandom::{random_instance};
  |                             ^^^^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying other imports

error: aborting due to 9 previous errors

error: aborting due to 3 previous errors

thread '<unnamed>' panicked at 'wanted an rlib: "file too small to be an archive"', src/librustc_codegen_llvm/back/lto.rs:111:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto=thin -C overflow-checks=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

thread 'rustc' panicked at '/rustc/2d8a3b9181f41d3af9b9f016c5d73b2553e344bf/src/librustc_codegen_ssa/back/write.rs:1713:17: panic during codegen/LLVM phase', src/librustc_middle/util/bug.rs:34:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto=thin -C overflow-checks=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

thread '<unnamed>' panicked at 'wanted an rlib: "file too small to be an archive"', src/librustc_codegen_llvm/back/lto.rs:111:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto=thin -C overflow-checks=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

thread 'rustc' panicked at '/rustc/2d8a3b9181f41d3af9b9f016c5d73b2553e344bf/src/librustc_codegen_ssa/back/write.rs:1713:17: panic during codegen/LLVM phase', src/librustc_middle/util/bug.rs:34:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto=thin -C overflow-checks=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

thread '<unnamed>' panicked at 'wanted an rlib: "file too small to be an archive"', src/librustc_codegen_llvm/back/lto.rs:111:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto=thin -C overflow-checks=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

thread 'rustc' panicked at '/rustc/2d8a3b9181f41d3af9b9f016c5d73b2553e344bf/src/librustc_codegen_ssa/back/write.rs:1713:17: panic during codegen/LLVM phase', src/librustc_middle/util/bug.rs:34:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C lto=thin -C overflow-checks=on -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: build failed

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at '/rustc/2d8a3b9181f41d3af9b9f016c5d73b2553e344bf/src/librustc_codegen_ssa/back/write.rs:1713:17: panic during codegen/LLVM phase', src/librustc_middle/util/bug.rs:34:26
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   2: rustc_middle::ty::context::tls::with_opt::{{closure}}
   3: rustc_middle::ty::context::tls::with_opt
   4: rustc_middle::util::bug::opt_span_bug_fmt
   5: rustc_middle::util::bug::bug_fmt
   6: rustc_session::utils::<impl rustc_session::session::Session>::time
   7: rustc_codegen_ssa::back::write::OngoingCodegen<B>::join
   8: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::join_codegen
   9: rustc_interface::queries::Linker::link
  10: rustc_span::with_source_map
  11: rustc_interface::interface::create_compiler_and_run
  12: scoped_tls::ScopedKey<T>::set

```

</p>
</details>

**Comment by camelid** [comment]
@panstromek Did running `cargo clean` stop the issue from occurring? Also, updating to a recent nightly *may* fix the issue (yours is 4 months old).

**Comment by panstromek** [comment]
Yes. Cargo clean fixed the issue. I also forgot mention that this only happened during release build, debug worked fine. The WSL crash happened during release build, so it probably just broke some related files

**Comment by workingjubilee** [comment]
Was this WSL1 or WSL2?

**Comment by panstromek** [comment]
It was WSL2

**Comment by workingjubilee** [comment]
> 
> 
> Yes. Cargo clean fixed the issue. I also forgot to mention that this only happened during release build, debug worked fine. The WSL crash happened during release build, too so it probably just broke some related files

Yes, Cargo probably falsely believed some files were still good because the crash, uh, successfully raced cargo.
What were you doing in the IDE?
Was the IDE running atop WSL or was it atop the Windows kernel?

**Comment by panstromek** [comment]
I don't remember exactly but I think I was making a commit through UI. I usually run build + tests, open commit dialog and when I see the tests passed, I hit enter. 

It's CLion running in the WSL (so atop wsl kernel) and using X client on Windows side.

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Without a way for other to reproduce reasonably easily, not much can be done at this point. Closing.
