### ISSUE TITLE
Unaligned usize in Range on custom target

### ISSUE THREAD

**Issue by DomWilliams0** [rust-lang/rust#80616]
Trying to use a Range<usize> on my custom x86_64-based OS (spec below) is aborting on an unaligned usize.

I tried this code:

```rust
for _ in 0..7usize {}
```

What I expected: loops silently
What happened: abort() is called

My target spec:
```json
{
	"llvm-target": "x86_64-unknown-none",
	"data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
	"arch": "x86_64",
	"target-endian": "little",
	"target-pointer-width": "64",
	"target-c-int-width": "64",
	"os": "none",
	"executables": true,
	"linker-flavor": "ld.lld",
	"linker": "rust-lld",
	"panic-strategy": "abort",
	"disable-redzone": true,
	"features": "-mmx,-sse,+soft-float"
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (44e3daf5e 2020-12-31)
```

<details><summary>Backtrace</summary>
<p>

```
#0  core::ptr::write<usize> (dst=0x157c14, src=0) at /home/dom/.rustup/toolchains/nightly-2021-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:888
#1  0x00000000001316de in core::ptr::swap_nonoverlapping_one<usize> (x=0x157e7c, y=0x157c14) at /home/dom/.rustup/toolchains/nightly-2021-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:460
#2  0x00000000001246e3 in core::mem::swap<usize> (x=0x157e7c, y=0x157c14) at /home/dom/.rustup/toolchains/nightly-2021-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:695
#3  0x0000000000124758 in core::mem::replace<usize> (dest=0x157e7c, src=1) at /home/dom/.rustup/toolchains/nightly-2021-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:822
#4  0x000000000013992c in core::iter::range::{{impl}}::next<usize> (self=0x157e7c) at /home/dom/.rustup/toolchains/nightly-2021-01-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/range.rs:508
#5  0x00000000001077f7 in domeos_kernel::start::parse_multiboot (multiboot=0x10000) at /home/dom/backups/20-29_Dev/dev/os/project/kernel/src/start.rs:46
#6  0x0000000000107255 in domeos_kernel::start::start (multiboot=0x10000) at /home/dom/backups/20-29_Dev/dev/os/project/kernel/src/start.rs:21
#7  0x00000000001070bf in domeos_kernel::kernel_main (magic=732803074, multiboot=0x10000) at /home/dom/backups/20-29_Dev/dev/os/project/kernel/src/lib.rs:35
#8  0x00000000001060c4 in long_mode ()

```

My OS has jumped to long mode and other 64 bit Rust code is working fine. Checking size_of::<usize>() is definitely 8, yet the pointer `0x157c14` is not aligned. 

</p>
</details>

**Comment by sfackler** [comment]
Is your stack properly 16 byte aligned?

**Comment by DomWilliams0** [comment]
@sfackler Nope, that was it! It turns out something hairy was happening during stack setup and it was only 4 byte aligned by the time it got to the Rust code.

Thanks :100:
