### ISSUE TITLE
ICE'd (twice in a row!) when not enabling `const_generics` but a downstream crate that does enable and use it

### ISSUE THREAD

**Issue by mental32** [rust-lang/rust#80748]
So this time rustc ICE'd with a SIGILL, I'm not sure how bad that's supposed to be...

### Code

tree

```
├── Cargo.toml
├── src
│   ├── lib.rs
│   └── main.rs
```

main.rs

```Rust
// #![feature(const_generics)]  // If you enable this feature in main.rs it all works fine!

use icey::*;

fn main() {
    let obj = TypeErasedObject::from(0usize);
}
```

lib.rs:

```Rust
#![feature(const_evaluatable_checked)]
#![feature(const_generics)]

use core::mem::{forget, size_of, MaybeUninit};

#[repr(packed)]
pub struct TypeErasedObject<const N: usize> {
    buf: [u8; N],
}

impl<U> From<U> for TypeErasedObject<{ size_of::<U>() }> {
    fn from(val: U) -> Self {
        unsafe {
            let mut obj = MaybeUninit::zeroed().assume_init();

            core::intrinsics::copy_nonoverlapping(
                &val as *const U,
                &mut obj as *const _ as *mut U,
                size_of::<U>(),
            );

            forget(val);

            obj
        }
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (da305a2b0 2021-01-05)
binary: rustc
commit-hash: da305a2b00530aa34dea4e48389204c26fa35dbb
commit-date: 2021-01-05
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

### Error output

<details><summary><strong>Error output</strong></summary>
<p>

```
mental@felix /t/icey (master) [101]> cargo run
warning: the feature `const_evaluatable_checked` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:12
  |
1 | #![feature(const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information

warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:2:12
  |
2 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: field is never read: `buf`
 --> src/lib.rs:8:5
  |
8 |     buf: [u8; N],
  |     ^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 3 warnings emitted

   Compiling icey v0.1.0 (/tmp/icey)
warning: unused variable: `obj`
 --> src/main.rs:6:9
  |
6 |     let obj = TypeErasedObject::from(0usize);
  |         ^^^ help: if this is intentional, prefix it with an underscore: `_obj`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorReported', compiler/rustc_mir/src/monomorphize/collector.rs:746:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (da305a2b0 2021-01-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
warning: 1 warning emitted

error: internal compiler error: Encountered error `Unimplemented` selecting `Binder(<icey::TypeErasedObject<8_usize> as std::convert::From<usize>>)` during codegen
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:68:32

error: internal compiler error: broken MIR in DefId(0:4 ~ icey[a815]::main) (CanonicalUserTypeAnnotation { user_ty: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Const(U0) }, CanonicalVarInfo { kind: Ty(General(U0)) }], value: TypeOf(DefId(2:1991 ~ core[27a9]::convert::From::from), UserSubsts { substs: [icey::TypeErasedObject<^0>, ^1], user_self_ty: None }) }, span: src/main.rs:6:15: 6:37 (#0), inferred_ty: fn(usize) -> icey::TypeErasedObject<{_: usize}> {<icey::TypeErasedObject<{_: usize}> as std::convert::From<usize>>::from} }): bad user type AscribeUserType(fn(usize) -> icey::TypeErasedObject<{_: usize}> {<icey::TypeErasedObject<{_: usize}> as std::convert::From<usize>>::from}, DefId(2:1991 ~ core[27a9]::convert::From::from) UserSubsts { substs: [icey::TypeErasedObject<{_: _}>, _], user_self_ty: None }): NoSolution
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0:     0x7ff631e847f7 - std::backtrace_rs::backtrace::libunwind::trace::h746c3e9529d524bc
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7ff631e847f7 - std::backtrace_rs::backtrace::trace_unsynchronized::h84373278bfb39e0c
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff631e847f7 - std::sys_common::backtrace::_print_fmt::h517324efde750597
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7ff631e847f7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf594ab77fac89284
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7ff631ef507c - core::fmt::write::h3868db8542c90941
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/core/src/fmt/mod.rs:1078:17
   5:     0x7ff631e76732 - std::io::Write::write_fmt::h3f6656f045fa877f
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/io/mod.rs:1518:15
   6:     0x7ff631e884c5 - std::sys_common::backtrace::_print::hda7655c057c24dcc
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7ff631e884c5 - std::sys_common::backtrace::print::h546a6c8431d46287
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7ff631e884c5 - std::panicking::default_hook::{{closure}}::h006dd083853faf51
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/panicking.rs:208:50
   9:     0x7ff631e88023 - std::panicking::default_hook::hf0f9afb1017317fc
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/panicking.rs:225:9
  10:     0x7ff6326ef36b - rustc_driver::report_ice::h7f38a651c021f7c4
  11:     0x7ff631e88dc6 - std::panicking::rust_panic_with_hook::hb7a19826c029b1d6
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/panicking.rs:595:17
  12:     0x7ff631e888e7 - std::panicking::begin_panic_handler::{{closure}}::hde71edcd925d0c5e
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/panicking.rs:497:13
  13:     0x7ff631e84cbc - std::sys_common::backtrace::__rust_end_short_backtrace::h8a3c7d6cea578919
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7ff631e88849 - rust_begin_unwind
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/panicking.rs:493:5
  15:     0x7ff631e887fb - std::panicking::begin_panic_fmt::hee67ce14b77d0396
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/panicking.rs:435:5
  16:     0x7ff635808a23 - rustc_errors::HandlerInner::flush_delayed::h336555a5d5079cda
  17:     0x7ff6358072a4 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::he52694f8b8fafc7c
  18:     0x7ff634bba8e8 - core::ptr::drop_in_place::hb66213509a6069c4
  19:     0x7ff634bbc88d - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h162a1b2d5ffb70e8
  20:     0x7ff634bb8a5d - core::ptr::drop_in_place::h1b39670ebb19752a
  21:     0x7ff634bb8473 - rustc_span::with_source_map::h36095e686800efef
  22:     0x7ff634bc3b7a - rustc_interface::interface::create_compiler_and_run::hbd9692e1ed97f25b
  23:     0x7ff634bb8737 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc05e05dc1f4978f3
  24:     0x7ff634b9c55a - core::ops::function::FnOnce::call_once{{vtable.shim}}::h105413704138b627
  25:     0x7ff631e98fea - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hea1090dbdcecbf5a
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/alloc/src/boxed.rs:1480:9
  26:     0x7ff631e98fea - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5723d3912bd325
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/alloc/src/boxed.rs:1480:9
  27:     0x7ff631e98fea - std::sys::unix::thread::Thread::new::thread_start::hc17a425ca2995724
                               at /rustc/da305a2b00530aa34dea4e48389204c26fa35dbb/library/std/src/sys/unix/thread.rs:71:17
  28:     0x7ff631d9a3e9 - start_thread
  29:     0x7ff631cb7293 - __GI___clone
  30:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (da305a2b0 2021-01-05) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `icey`

Caused by:
  process didn't exit successfully: `rustc --crate-name icey --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=9186bff72f6e5e0b -C extra-filename=-9186bff72f6e5e0b --out-dir /tmp/icey/target/debug/deps -C incremental=/tmp/icey/target/debug/incremental -L dependency=/tmp/icey/target/debug/deps --extern icey=/tmp/icey/target/debug/deps/libicey-738371281f5478e6.rlib` (signal: 4, SIGILL: illegal instruction)
```

</p>
</details>

**Comment by mental32** [comment]
I could probably word the title better but I'm not exactly sure how... if anyone has ideas let me know :D

**Comment by fanninpm** [comment]
> `-C incremental`

Does it go away after you run `cargo clean`?

**Comment by mental32** [comment]
Actually I cant reproduce it anymore [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=869f80d57e326bee152dd8d714d39128)
