### ISSUE TITLE
rustc_mir::borrow_check::region_infer::RegionInferenceContext::find_outlives_blame_span called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust#80772]
### Code

```Rust
trait SomeTrait {}

struct Exhibit {
    constant: usize,
    factory: fn(&usize) -> Box<dyn SomeTrait>,
}

const A_CONSTANT: &[Exhibit] = &[
    Exhibit {
        constant: 1,
        factory: |_| unimplemented!(),
    },
    Exhibit {
        constant: "Hello world".len(),
        factory: |_| unimplemented!(),
    },
];
```

[On playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=93d6c56fb58b81120a70dd3e358dd3b1)

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-apple-darwin
release: 1.49.0
```

Also happens on 1.48.0 and nightly.

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_mir/src/borrow_check/region_infer/mod.rs:2120:35

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0 (e1884a8e3 2020-12-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `A_CONSTANT`
#1 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: rustc_mir::borrow_check::region_infer::RegionInferenceContext::find_outlives_blame_span
   4: rustc_mir::borrow_check::do_mir_borrowck
   5: rustc_infer::infer::InferCtxtBuilder::enter
   6: rustc_mir::borrow_check::mir_borrowck
   7: core::ops::function::FnOnce::call_once
   8: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  10: rustc_data_structures::stack::ensure_sufficient_stack
  11: rustc_query_system::query::plumbing::get_query_impl
  12: rustc_query_system::query::plumbing::ensure_query_impl
  13: rustc_session::utils::<impl rustc_session::session::Session>::time
  14: rustc_interface::passes::analysis
  15: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::get_query_impl
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: rustc_interface::interface::create_compiler_and_run
  23: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by kpreid** [comment]
On taking another look at the issues I found before filing this one, it looks like #74599 _might_ be the same thing, as it has a similar stack trace. That code sample requires nightly, however, and this one does not.

From a superficial examination (I know nothing about the compiler internals), both issues involve:
* multiple subexpressions (an array expression or a match) where the problem is sensitive to the number of branches even if they're irrelevant
* calling a method on a literal in a constant context
* a closure in one or more of the branches

**Comment by camelid** [comment]
This also reproduces the ICE:

```rust
trait SomeTrait {}

struct Exhibit {
    constant: bool,
    factory: fn(&usize) -> Box<dyn SomeTrait>,
}

const A_CONSTANT: &[Exhibit] = &[
    Exhibit {
        constant: "".is_empty(),
        factory: |_| unimplemented!(),
    },
    Exhibit {
        constant: "".is_empty(),
        factory: |_| unimplemented!(),
    },
];
```

**Comment by camelid** [comment]
```
searched toolchains nightly-2019-11-01 through nightly-2020-01-30


********************************************************************************
Regression in nightly-2019-11-29
********************************************************************************
```

Regression was too long ago to bisect to an individual commit, but the commit range is e87a205c2e117d9fb57f6cdeac0a7f6e95c88316..bbb664a99c0188fa756cbbb3a6c4e5d8825c372b.

**Comment by apiraino** [comment]
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2380772.20rustc_mir.3A.3Aborrow_check.3A.3Aregion_infer.3A.3ARegionInferen.E2.80.A6) and removing `I-prioritize`.

**Comment by joho-stop** [comment]
It looks like the ICE was introduced with #66642 / bbb664a99c0188fa756cbbb3a6c4e5d8825c372b.

The `unwrap` that triggers the ICE is at the end of `RegionInferenceContext::best_blame_constraint`.

Issue #74599, mentioned above by @kpreid, is triggered by a `None` on the same `unwrap` but the error was already happening earlier in history. I observed it with the immediate parent commit f453d11.

**Comment by joho-stop** [comment]
Actually it looks like f9ed2199ff is the first commit with this issue
