### ISSUE TITLE
Internal compiler error - tuple_fields called on non-tuple

### ISSUE THREAD

**Issue by DNNX** [rust-lang/rust#80786]
### Code

```Rust
use std::collections::HashMap;

fn main() {
    let mut res: HashMap<u16, Vec<u16>> = HashMap::new();

    let masks: Vec<u16> = (0..=0xffffu16).filter(|&x| false).to_owned().collect();

    for &x in masks.iter() {
        res.insert(x, masks.iter().filter(|&y| false).collect());
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-apple-darwin
release: 1.49.0-nightly
LLVM version: 11.0
```

### Error output

```
   Compiling pe237 v0.1.0 (/Users/dnnx/work/competitions/projecteuler/pe237)
error[E0277]: a value of type `Vec<u16>` cannot be built from an iterator over elements of type `&u16`
 --> src/main.rs:9:55
  |
9 |         res.insert(x, masks.iter().filter(|&y| false).collect());
  |                                                       ^^^^^^^ value of type `Vec<u16>` cannot be built from `std::iter::Iterator<Item=&u16>`
  |
  = help: the trait `FromIterator<&u16>` is not implemented for `Vec<u16>`

error: internal compiler error: compiler/rustc_middle/src/ty/sty.rs:2150:18: tuple_fields called on non-tuple

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `[closure@src/main.rs:6:50: 6:60]: std::clone::Clone`
#1 [typeck] type-checking `main`
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `pe237`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
stack backtrace:
   0:        0x10efba6a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h808cc0fc691f5922
   1:        0x10f022330 - core::fmt::write::h0ce880d33cd2a300
   2:        0x10efabea6 - std::io::Write::write_fmt::h057e6b5365b25cdb
   3:        0x10efbf229 - std::panicking::default_hook::{{closure}}::hcbe1ecfff77305a1
   4:        0x10efbeeed - std::panicking::default_hook::h8422621c02c35b35
   5:        0x10765d638 - rustc_driver::report_ice::hc552e667d6d38f36
   6:        0x10efbf95e - std::panicking::rust_panic_with_hook::h82b76d3adf4cbc3a
   7:        0x10bbca9e1 - std::panicking::begin_panic::{{closure}}::h085bca95250ed8bf
   8:        0x10bbca989 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a6e599d0c1b60d1
   9:        0x10c02f8d1 - std::panicking::begin_panic::h3a64de21fa178bdd
  10:        0x10bbf85e7 - rustc_errors::HandlerInner::bug::he1b4901d1c33f4e1
  11:        0x10bbf7057 - rustc_errors::Handler::bug::hfa317f4299131d0f
  12:        0x10b7205b4 - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h7f42b77a79094ea9
  13:        0x10b71b586 - rustc_middle::ty::context::tls::with_opt::{{closure}}::h02206696c3a105cf
  14:        0x10b71b543 - rustc_middle::ty::context::tls::with_opt::h26ddb50870ff0105
  15:        0x10b7204d1 - rustc_middle::util::bug::opt_span_bug_fmt::hbf114ecad48a4e81
  16:        0x10c016306 - rustc_middle::util::bug::bug_fmt::h18f192f6a062df6a
  17:        0x10b825b41 - rustc_middle::ty::sty::<impl rustc_middle::ty::TyS>::tuple_fields::he6788e44bd72e04d
  18:        0x10b167b4b - rustc_trait_selection::traits::select::SelectionContext::copy_clone_conditions::h382b59a9631a2383
  19:        0x10b163002 - rustc_trait_selection::traits::select::candidate_assembly::<impl rustc_trait_selection::traits::select::SelectionContext>::assemble_candidates::h44c0bfd580b3a02c
  20:        0x10b161366 - rustc_trait_selection::traits::select::candidate_assembly::<impl rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation_no_cache::he58fb21b2a8d7326
  21:        0x10b2ba0d4 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h4127592c0dc9d779
  22:        0x10b175bb4 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task::he94f2607e5f9e3a9
  23:        0x10b1693f8 - rustc_trait_selection::traits::select::candidate_assembly::<impl rustc_trait_selection::traits::select::SelectionContext>::candidate_from_obligation::h6423adc08bb9d6ba
  24:        0x10b166029 - rustc_trait_selection::traits::select::SelectionContext::evaluate_stack::h58fa960e770aea82
  25:        0x10b2bfdae - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hebcb6e33436b0642
  26:        0x10b170d86 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task::h2ee16ef6907409a7
  27:        0x10b165597 - rustc_trait_selection::traits::select::SelectionContext::evaluate_trait_predicate_recursively::h6a058e14091ee2c7
  28:        0x10b2ef71b - rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::{{closure}}::h4f175c150efe4f05
  29:        0x10b16fd30 - rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::h01edce3a2a6ab13e
  30:        0x10b133ab9 - rustc_infer::infer::InferCtxt::probe::h84c89a89d3e7c476
  31:        0x10b164b70 - rustc_trait_selection::traits::select::SelectionContext::evaluate_root_obligation::h90a805781d408434
  32:        0x1099cedcc - rustc_infer::infer::InferCtxtBuilder::enter_with_canonical::h0fc02de196b0cb8a
  33:        0x109a2fa50 - rustc_traits::evaluate_obligation::evaluate_obligation::h3e1b6a6cac252eff
  34:        0x10b139d91 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::evaluate_obligation>::compute::hd538796ae8dfb17d
  35:        0x10b2be287 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h871c34e0499252fb
  36:        0x10b182cde - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hccbfed99f9d8e0de
  37:        0x10b2b55e6 - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}::h4b40a9dbd067c5bf
  38:        0x10b2a1dba - rustc_query_system::query::plumbing::get_query_impl::hed84abc9405fbe6e
  39:        0x10b15cfe6 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation::hf47140af67924da9
  40:        0x10b15d091 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow::h7d5edce09f46f734
  41:        0x10b23b77c - rustc_trait_selection::traits::fulfill::FulfillProcessor::process_trait_obligation::hb00f87db7e5a3c37
  42:        0x10b23aa77 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::h0badff222a534e35
  43:        0x10b2c0e86 - rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations::h2e4630acba8c6317
  44:        0x10b239bb9 - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible::hee98043f412c5e2e
  45:        0x109c9dba8 - rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::select_obligations_where_possible::h5f9e802ffce899b0
  46:        0x109ec7444 - rustc_infer::infer::InferCtxtBuilder::enter::hdb862ab7e63ac988
  47:        0x109f55ad8 - rustc_typeck::check::typeck::h19bb90b326c33706
  48:        0x109e6943d - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute::h4a4f77ab3d73475d
  49:        0x109d83951 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hcf9218ce6d103ad8
  50:        0x109e44237 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h82a256da336ee7f1
  51:        0x109dcf64c - rustc_data_structures::stack::ensure_sufficient_stack::h14f735f22b2dcb72
  52:        0x109d1baf9 - rustc_query_system::query::plumbing::get_query_impl::hae16bbff19dcf8a1
  53:        0x109d4cce5 - rustc_query_system::query::plumbing::ensure_query_impl::h6c563b91ba5ff733
  54:        0x109f5a784 - rustc_typeck::check::typeck_item_bodies::h74e555288e597808
  55:        0x109e2c10d - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute::h382e400dbb214a00
  56:        0x109d80a8a - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h6b44cd0cd467b3f9
  57:        0x109e48b94 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hb4bf0adb3eb9029d
  58:        0x109dd8c8d - rustc_data_structures::stack::ensure_sufficient_stack::hbdf4cfe6d21ed26b
  59:        0x109d3cfbc - rustc_query_system::query::plumbing::get_query_impl::hef63af7ed2d7d2c6
  60:        0x109e7f744 - rustc_typeck::check_crate::heab083594ec68626
  61:        0x10783a9ad - rustc_interface::passes::analysis::hd2b5ad3cc5fe453e
  62:        0x1075f2aba - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute::h620490f1f313a641
  63:        0x1075f35b4 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h3d28d40dc412d809
  64:        0x107675cc4 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h4ad8376470714065
  65:        0x107671c1f - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}::hfa9e026f3553f1cf
  66:        0x107619681 - rustc_query_system::query::plumbing::get_query_impl::ha7bb177bffa54122
  67:        0x1075f4eaa - rustc_interface::passes::QueryContext::enter::h49dada493e6a503c
  68:        0x107672d95 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h41f348cdc8bbe333
  69:        0x10764212f - rustc_span::with_source_map::hc57a0c1060683b63
  70:        0x1076749a1 - rustc_interface::interface::create_compiler_and_run::h7b3634e1b272bb77
  71:        0x107661433 - scoped_tls::ScopedKey<T>::set::he87175a0cbe8a68d
  72:        0x107677d76 - std::sys_common::backtrace::__rust_begin_short_backtrace::h11e569b16e975fec
  73:        0x10760bf7c - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf3134e9dfffbe255
  74:        0x10efcdccd - std::sys::unix::thread::Thread::new::thread_start::h982ed3bd26e29e66
  75:     0x7fff5550c661 - __pthread_body
  76:     0x7fff5550c50d - __pthread_start

note: the compiler unexpectedly panicked. this is a bug.
```

</p>
</details>

Note: when I remove `.to_owned()` from the source code, the internal compiler error goes away, so it must be connected.

Don't look at the source code too closely. ~I don't know what I am doing.~

UPDATE: I removed irrelevant stuff from the original code and updated the compiler output accordingly in the issue description.

**Comment by jyn514** [comment]
@DNNX this works for me on both 1.49 stable and 1.51 nightly. Can you double check it works for you? If so I think this has already been fixed.

**Comment by DNNX** [comment]
Works for me as well on the latest 1.49 stable and 1.51 nightly. Sorry for the trouble. I'm closing the issue.
