### ISSUE TITLE
ICE when returning a Box with a reference as its Allocator

### ISSUE THREAD

**Issue by DrMeepster** [rust-lang/rust#81246]
### Code

```Rust
#![feature(allocator_api)]

fn ice() -> Box<(), &'static std::alloc::Global> {todo!()}

fn main(){
    ice();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (a4cbb44ae 2021-01-20)
binary: rustc
commit-hash: a4cbb44ae2c80545db957763b502dc7f6ea22085
commit-date: 2021-01-20
host: x86_64-pc-windows-msvc
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/a4cbb44ae2c80545db957763b502dc7f6ea22085\compiler\rustc_middle\src\ty\layout.rs:2149:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (a4cbb44ae 2021-01-20) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
query stack during panic:
error: could not compile `icetest`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/a4cbb44ae2c80545db957763b502dc7f6ea22085\compiler\rustc_middle\src\ty\layout.rs:2149:21
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (a4cbb44ae 2021-01-20) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `icetest`

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by jfrimmel** [comment]
Another code snippet, that hits this assertion is ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1e88d6aa15bd28f2121d074bb1d005c4)):
```rust
#![feature(allocator_api)]
use std::alloc::{Layout, Allocator, Global, AllocError};
use std::ptr::NonNull;
use std::marker::PhantomData;

struct S<A>{ a: PhantomData<A>, b: (u8,) }
unsafe impl<A> Allocator for S<A> {
    fn allocate(&self, _: Layout) -> Result<NonNull<[u8]>, AllocError> {
        todo!();
    }
    unsafe fn deallocate(&self, _: NonNull<u8>, _: Layout) {
        todo!();
    }
}

fn main() {
    let x: Box<u8, S<u8>> = Box::new_in(0, S {
        a: PhantomData,
        b: (0,),
    });
}
```
This is a slightly changed variant of #81270, but the array was changed to a 1-element-tuple.

**Comment by exrook** [comment]
I believe this is the same issue as #78459

**Comment by DrMeepster** [comment]
Yeah, looks like it
