### ISSUE TITLE
rustdoc ICE 'Deref section without derived id'

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#81395]
### Code

Original:

```
git clone https://gitlab.freedesktop.org/gstreamer/gstreamer-rs
cd gstreamer-rs
RUST_BACKTRACE=1 cargo +nightly doc -p gstreamer-video --no-deps
```

Minimized:

```rust
pub struct Generic<T>(T);

impl<'a> std::ops::Deref for Generic<&'a mut ()> {
    type Target = Generic<&'a ()>;
    fn deref(&self) -> &Self::Target {
        unimplemented!()
    }
}

impl<'a> Generic<&'a ()> {
    pub fn some_method(&self) {}
}
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
binary: rustc
commit-hash: 1d0d76f8dd4f5f6ecbeab575b87edaf1c9f56bb8
commit-date: 2021-01-24
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
 Documenting gstreamer-video v0.17.0 (/home/simon/projects/servo-deps/gstreamer-rs/gstreamer-video)
thread 'rustc' panicked at 'Deref section without derived id', src/librustdoc/html/render/mod.rs:4427:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `gstreamer-video`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Deref section without derived id', src/librustdoc/html/render/mod.rs:4427:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1d0d76f8dd4f5f6ecbeab575b87edaf1c9f56bb8/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1d0d76f8dd4f5f6ecbeab575b87edaf1c9f56bb8/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/1d0d76f8dd4f5f6ecbeab575b87edaf1c9f56bb8/library/core/src/option.rs:1258:5
   3: rustdoc::html::render::sidebar_deref_methods
   4: rustdoc::html::render::sidebar_assoc_items
   5: rustdoc::html::render::print_sidebar
   6: rustdoc::html::layout::render
   7: rustdoc::html::render::Context::render_item
   8: <rustdoc::html::render::Context as rustdoc::formats::renderer::FormatRenderer>::item
   9: rustdoc::formats::renderer::run_format
  10: rustdoc::run_renderer
  11: rustc_session::utils::<impl rustc_session::session::Session>::time
  12: rustc_interface::passes::QueryContext::enter
  13: rustc_interface::interface::create_compiler_and_run
  14: rustdoc::main_options
  15: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by SimonSapin** [comment]
When running with `RUSTDOC_LOG=trace`, the last few lines before the panic are:

```
INFO rustdoc::html::render Recursing into /home/simon/projects/servo-deps/gstreamer-rs/target/doc/gstreamer_video/video_frame
INFO rustdoc::html::render Documenting video_frame
INFO rustdoc::html::render Recursed; leaving /home/simon/projects/servo-deps/gstreamer-rs/target/doc/gstreamer_video/video_frame
INFO rustdoc::html::render Documenting VideoBufferExt
INFO rustdoc::html::render Documenting get_video_flags on Some("VideoBufferExt")
INFO rustdoc::html::render Documenting get_video_flags
INFO rustdoc::html::render Documenting set_video_flags on Some("VideoBufferExt")
INFO rustdoc::html::render Documenting set_video_flags
INFO rustdoc::html::render Documenting unset_video_flags on Some("VideoBufferExt")
INFO rustdoc::html::render Documenting unset_video_flags
INFO rustdoc::html::render Documenting associated items of Some("VideoBufferExt")
INFO rustdoc::html::render Documenting VideoFrameRef
INFO rustdoc::html::render Documenting associated items of Some("VideoFrameRef")
thread 'rustc' panicked at 'Deref section without derived id', src/librustdoc/html/render/mod.rs:4427:22
```

`VideoFrameRef` seems relevant since it has a `Deref` impl:

```rust
impl<'a> ops::Deref for VideoFrameRef<&'a mut gst::BufferRef> {
    type Target = VideoFrameRef<&'a gst::BufferRef>;

    fn deref(&self) -> &Self::Target {
        unsafe {
            &*(self as *const VideoFrameRef<&'a mut gst::BufferRef>
                as *const VideoFrameRef<&'a gst::BufferRef>)
        }
    }
}
```
```rust
#[derive(Debug)]
pub struct VideoFrameRef<T> {
    frame: ffi::GstVideoFrame,
    buffer: Option<T>,
    info: crate::VideoInfo,
    unmap: bool,
}
```

**Comment by SimonSapin** [comment]
Minimized:

```rust
pub struct Generic<T>(T);

impl<'a> std::ops::Deref for Generic<&'a mut ()> {
    type Target = Generic<&'a ()>;
    fn deref(&self) -> &Self::Target {
        unimplemented!()
    }
}

impl<'a> Generic<&'a ()> {
    pub fn some_method(&self) {}
}

**Comment by SNCPlay42** [comment]
searched nightlies: from nightly-2020-11-12 to nightly-2021-01-17
regressed nightly: nightly-2021-01-09
searched commits: from https://github.com/rust-lang/rust/commit/c8915eebeaaef9f7cc1cff6ffd97f578b03c2ac9 to https://github.com/rust-lang/rust/commit/26438b473883ea607b30288e461187f0fb2fe589
regressed commit: https://github.com/rust-lang/rust/commit/937f629535f38c655267f1ed21ce6830f592f5df

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2020-11-12 --end=2021-01-17 --preserve -- doc 
```
</details>

Regressed in #80653.

@rustbot label regression-from-stable-to-nightly

**Comment by jyn514** [comment]
cc @jryans - do you have time to figure out what's going wrong here?

**Comment by jryans** [comment]
Yes, I believe so, I'll see what I can do here.

@rustbot claim

**Comment by GuillaumeGomez** [comment]
@jryans Please ping me once you open the PR (@jyn514 is taking a break :) )

**Comment by jryans** [comment]
The core issue is the `Deref` recursion cycle handling... It focuses only on `DefId`s and wasn't anticipating targets that differ only in generic type args. I believe I see the tweak we'll need here, so I should have a PR in the next day or so.
