### ISSUE TITLE
Panic in libtest while running doc tests

### ISSUE THREAD

**Issue by KronicDeth** [rust-lang/rust#81602]
Encountered while updating https://github.com/lumen/lumen from `nightly-2020-05-13` to latest `nightly` (`nightly-2020-01-29`)

I haven't minimized yet this.  Posting now to minimize later.

### Code

1. `git checkout git@github.com:lumen/lumen.git`
2. `git checkout 614cd157dfa302e8235c0957b6fe0b5b8f59332e`
3. `cargo make test -- --package liblumen_alloc`

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (c0b64d97b 2021-01-28)
binary: rustc
commit-hash: c0b64d97beebb09325b5587abed39f4f1621026f
commit-date: 2021-01-28
host: x86_64-apple-darwin
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
running 9 tests
test src/erts/process/alloc/iter.rs - erts::process::alloc::iter::HeapIter::iter_mut (line 18) ... ignored
test src/erts/process/trace/utils.rs - erts::process::trace::utils::calculate_fragment_layout (line 159) ... ignored
test src/erts/term/binary/primitives.rs - erts::term::binary::primitives::is_bit_set (line 41) ... ignored
test src/erts/term/binary/primitives.rs - erts::term::binary::primitives::make_bitmask (line 10) ... ignored
test src/erts/term/binary/primitives.rs - erts::term::binary::primitives::mask_bits (line 25) ... ignored
test src/lib.rs - SysAlloc (line 58) ... ignored
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', library/test/src/lib.rs:356:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (c0b64d97b 2021-01-28) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no --crate-type lib

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', library/test/src/lib.rs:356:75
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: test::run_tests
   4: test::console::run_tests_console
   5: test::test_main
   6: rustdoc::doctest::run
   7: rustdoc::main_options
   8: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

The panicked line is trying to remove the completed test https://github.com/rust-lang/rust/blob/0e63af5da3400ace48a0345117980473fd21ad73/library/test/src/lib.rs#L356

```
est stats::histogram::tests::histogram_from_ranges_test ... ok

test result: ok. 77 passed; 0 failed; 4 ignored; 0 measured; 0 filtered out; finished in 0.01s

   Doc-tests liblumen_alloc

running 9 tests
test src/erts/process/alloc/iter.rs - erts::process::alloc::iter::HeapIter::iter_mut (line 18) ... ignored
test src/erts/process/trace/utils.rs - erts::process::trace::utils::calculate_fragment_layout (line 159) ... ignored
test src/erts/term/binary/primitives.rs - erts::term::binary::primitives::is_bit_set (line 41) ... ignored
test src/erts/term/binary/primitives.rs - erts::term::binary::primitives::make_bitmask (line 10) ... ignored
test src/erts/term/binary/primitives.rs - erts::term::binary::primitives::mask_bits (line 25) ... ignored
test src/lib.rs - SysAlloc (line 58) ... ignored
```

The normal unit tests are passing fine, so this is when the doctest section is being printed so it is either a problem during the doctest or immediately after

**Comment by KronicDeth** [comment]
Removing all doctests fixes the build as one would expect.  

<details>

```patchIndex: liblumen_alloc/src/erts/process/monitor.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/erts/process/monitor.rs b/liblumen_alloc/src/erts/process/monitor.rs
--- a/liblumen_alloc/src/erts/process/monitor.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/erts/process/monitor.rs	(date 1612120689957)
@@ -7,43 +7,9 @@
     /// When monitoring a name, it does not matter if the name change after the monitor, the name
     /// passed to monitor is always returned, but the node name reflects the current node name.
     ///
-    /// ```elixir
-    /// child = spawn_link(fn ->
-    ///   receive do
-    ///     {parent_pid, :change_name} ->
-    ///       Process.unregister(:first_name)
-    ///       Process.register(self(), :second_name)
-    ///       send(parent_pid, :name_changed)
-    ///   end
-    ///
-    ///   receive do
-    ///     :exit ->
-    ///       exit(:normal)
-    ///   end
-    /// end)
-    ///
-    /// Process.register(child, :first_name)
-    /// :net_kernel.start([:first_node_name, :shortnames])
-    /// :erlang.node()
-    /// :erlang.monitor(:process, {:first_name, :erlang.node()})
-    /// :net_kernel.stop()
-    /// :net_kernel.start([:second_node_name, :shortnames])
-    /// send(:first_name, {self(), :change_name})
-    /// receive do
-    ///   :name_changed ->
-    ///     IO.puts("first_name is #{inspect(Process.whereis(:first_name))} while second_name is #{inspect(Process.whereis(:second_name))}")
-    ///     send(child, :exit)
-    ///     flush()
-    /// end
-    /// ```
     ///
     /// Ouputs:
     ///
-    /// ```text
-    /// first_name is nil while second_name is #PID<0.122.0>
-    /// {:DOWN, #Reference<0.3637422028.3801874438.147163>, :process,
-    ///   {:first_name, :second_node_name@Medina}, :normal}
-    /// ```
     Name {
         monitoring_pid: Pid,
         monitored_name: Atom,
Index: liblumen_alloc/src/erts/term/binary/primitives.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/erts/term/binary/primitives.rs b/liblumen_alloc/src/erts/term/binary/primitives.rs
--- a/liblumen_alloc/src/erts/term/binary/primitives.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/erts/term/binary/primitives.rs	(date 1612121542625)
@@ -7,10 +7,6 @@
 ///
 /// # Example
 ///
-/// ```rust,ignore
-/// let mask = make_bitmask(3);
-/// assert_eq!(0b00000111, mask);
-/// ```
 #[inline(always)]
 pub(super) fn make_bitmask(n: u8) -> u8 {
     debug_assert!(n < 8);
@@ -22,13 +18,6 @@
 ///
 /// # Example
 ///
-/// ```rust,ignore
-/// let mask = make_bitmask(3);
-/// let src = 0b00000101;
-/// let dst = 0b01000010;
-/// let result = mask_bits(src, dst, mask);
-/// assert_eq!(0b01000101);
-/// ```
 #[inline(always)]
 pub(super) fn mask_bits(src: u8, dst: u8, mask: u8) -> u8 {
     (src & mask) | (dst & !mask)
@@ -38,10 +27,6 @@
 ///
 /// # Example
 ///
-/// ```rust,ignore
-/// let byte = 0b01000000;
-/// assert_eq!(is_bit_set(byte, 7), true);
-/// ```
 #[allow(unused)]
 #[inline(always)]
 pub(super) fn is_bit_set(byte: u8, bit: u8) -> bool {
Index: liblumen_alloc/src/erts/term/atom.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/erts/term/atom.rs b/liblumen_alloc/src/erts/term/atom.rs
--- a/liblumen_alloc/src/erts/term/atom.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/erts/term/atom.rs	(date 1612121050549)
@@ -173,7 +173,6 @@
     /// with an id that doesn't exist will result in undefined
     /// behavior. This should only be used by `Term` when converting
     /// to `TypedTerm`
-    /// ```
     #[inline]
     pub unsafe fn from_id(id: usize) -> Self {
         Self(id)
Index: liblumen_alloc/src/stats/histogram.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/stats/histogram.rs b/liblumen_alloc/src/stats/histogram.rs
--- a/liblumen_alloc/src/stats/histogram.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/stats/histogram.rs	(date 1612121645047)
@@ -6,59 +6,6 @@
 //! the histogram, and can be constructed at compile-time.
 //!
 //! # Examples
-//!
-//! ```
-//! use liblumen_alloc::stats::Histogram;
-//!
-//! mod stats {
-//!     use liblumen_alloc::define_histogram;
-//!     define_histogram!(10);
-//! }
-//! # fn main() {
-//! // Create a histogram that will spread the given range over
-//! // the 10 buckets the `Histogram` type was defined with.
-//! let mut histogram = stats::Histogram::with_const_width(0, 10_000);
-//!
-//! // Adds some samples to the histogram.
-//! for sample in 0..100 {
-//!     histogram.add(sample);
-//!     histogram.add(sample * sample);
-//! }
-//!
-//! // Iterate over buckets and do stuff with their range and count.
-//! for ((start, end), count) in histogram.into_iter() {
-//!     println!("{}..{} has {} samples", start, end, count);
-//! }
-//!
-//! // And you can also `Display` a histogram!
-//! println!("{}", histogram);
-//!
-//! // Prints:
-//! //
-//! // ```
-//! // # Number of samples = 200
-//! // # Min = 0
-//! // # Max = 9801
-//! // #
-//! // # Mean = 1666.5000000000005
-//! // # Standard deviation = 2641.2281518263426
-//! // # Variance = 6976086.1499999985
-//! // #
-//! // # Each ∎ is a count of 2
-//! // #
-//! //    0 ..  980 [ 132 ]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
-//! //  980 .. 1960 [  13 ]: ∎∎∎∎∎∎
-//! // 1960 .. 2940 [  10 ]: ∎∎∎∎∎
-//! // 2940 .. 3920 [   8 ]: ∎∎∎∎
-//! // 3920 .. 4900 [   7 ]: ∎∎∎
-//! // 4900 .. 5880 [   7 ]: ∎∎∎
-//! // 5880 .. 6860 [   6 ]: ∎∎∎
-//! // 6860 .. 7840 [   6 ]: ∎∎∎
-//! // 7840 .. 8820 [   5 ]: ∎∎
-//! // 8820 .. 9800 [   6 ]: ∎∎∎
-//! // ```
-//! # }
-//! ```
 #![deny(unsafe_code)]
 
 use core::fmt;
Index: liblumen_alloc/src/erts/process/trace/utils.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/erts/process/trace/utils.rs b/liblumen_alloc/src/erts/process/trace/utils.rs
--- a/liblumen_alloc/src/erts/process/trace/utils.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/erts/process/trace/utils.rs	(date 1612120932936)
@@ -154,12 +154,6 @@
 /// stacktrace as an Erlang term. This allows the trace to live separately
 /// from the process which raised it
 ///
-/// Each (full) frame looks like so:
-///
-/// ```ignore
-///     [{module, function, arity, [{file, "path/to/file"}, {line, 1}]}]
-/// ```
-///
 /// The amount allocated for a trace is calculated by taking the number of frames
 /// in the trace, multiplying that by `BASE_FRAME_SIZE`, and then adding on an extra
 /// 25% padding to that. If `extra` is specified, that is added as an additional amount
Index: liblumen_alloc/src/lib.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/lib.rs b/liblumen_alloc/src/lib.rs
--- a/liblumen_alloc/src/lib.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/lib.rs	(date 1612126503970)
@@ -55,10 +55,6 @@
 
 /// The system allocator. Can be used with `#[global_allocator]`, like so:
 ///
-/// ```ignore
-/// #[global_allocator]
-/// pub static ALLOC: SysAlloc = SysAlloc;
-/// ```
 pub use liblumen_core::alloc::SysAlloc;
 
 /// A tracing allocator for tracking statistics about the allocator it wraps
Index: liblumen_alloc/src/erts/process/alloc/iter.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/erts/process/alloc/iter.rs b/liblumen_alloc/src/erts/process/alloc/iter.rs
--- a/liblumen_alloc/src/erts/process/alloc/iter.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/erts/process/alloc/iter.rs	(date 1612120932927)
@@ -15,12 +15,6 @@
     ///
     /// # Example
     ///
-    /// ```rust,ignore
-    /// for term in self.iter_mut() {
-    ///   if term.is_boxed() {
-    ///       ...
-    ///   }
-    /// }
     fn iter_mut<'a>(&mut self) -> IterMut<'a, Self>;
 }
 

```

</details>

Adding each test back in, it turned out that it is just the test that shows setting the `#[global_allocator]`.  I'm not sure if this means the test is failing because `SysAlloc` is broken by the upgrade of Rust and the adjustments made by going from `AllocRef` to `Allocator` meaning the global allocator is broke and so it makes sense that the test is broken OR if this is really a test bug.  The weird part is that the test is marked `ignore`, so the `#[global_allocator]` should NOT trigger, so it could a change in behavior of how attributes like `#[global_allocator]` are handled in Rust in ignored doc tests.

<details>

```patch
Index: liblumen_alloc/src/lib.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/liblumen_alloc/src/lib.rs b/liblumen_alloc/src/lib.rs
--- a/liblumen_alloc/src/lib.rs	(revision 614cd157dfa302e8235c0957b6fe0b5b8f59332e)
+++ b/liblumen_alloc/src/lib.rs	(date 1612127949750)
@@ -55,10 +55,6 @@
 
 /// The system allocator. Can be used with `#[global_allocator]`, like so:
 ///
-/// ```ignore
-/// #[global_allocator]
-/// pub static ALLOC: SysAlloc = SysAlloc;
-/// ```
 pub use liblumen_core::alloc::SysAlloc;
 
 /// A tracing allocator for tracking statistics about the allocator it wraps
````

</details>

## Work-around

Since the test is already ignored, for now I can delete the doctest completely and see if the crates that depend on it can show that the allocator is messed up.

**Comment by Enselic** [comment]
Triage: I can't reproduce this ICE any longer. Can you still reproduce?

```sh
git clone https://github.com/GetFirefly/firefly.git
cd firefly
git fetch origin 614cd157dfa302e8235c0957b6fe0b5b8f59332e
git checkout FETCH_HEAD
cargo +nightly-2020-01-29 test -- --package liblumen_alloc
```

**Comment by KronicDeth** [comment]
@Enselic We've paused development of `firefly` at this time as we concentrate on other R&D projects. Feel free to close for now as I don't have the bandwidth to check if it reproduces.
