### ISSUE TITLE
ICE in nightly compiling Rocket master

### ISSUE THREAD

**Issue by ecton** [rust-lang/rust#81936]
This is minimized as much as I could from an ICE arising from compiling the [HEAD of master as of today](https://github.com/SergioBenitez/Rocket/tree/c24f15c18f02319be83af4f3c1951dc220b52c5e) of [Rocket](https://github.com/SergioBenitez/Rocket). The error messages stayed the same throughout minimization, but upon resolving the issue, it would be good to also test that issuing `cargo build` inside of `core/lib` in Rocket also compiles. Although this has been minimized on Windows, the original ICE occurred on an Ubuntu Github Actions CI Server.

### Code

```Rust
macro_rules! info {
    (target: $target:expr, $($arg:tt)+) => (
        ()
    );
    ($($arg:tt)+) => (
        ()
    )
}

macro_rules! log_ { ($name:ident: $($args:tt)*) => { $name!(target: "_", $($args)*) }; }
macro_rules! info_ { ($($args:expr),+) => { log_!(info: $($args),+); }; }

fn main() {
    async {
        // No error
        info_!("");
        match Result::<(),()>::Ok(()) {
            // Errors
            Ok(()) => info_!(""),
            Err(()) => info_!(""),
        }
    };
}

```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-pc-windows-msvc
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
   Compiling ice-attempt v0.1.0 (C:\Users\jon\repos\ice-attempt)
warning: unused implementer of `Future` that must be used
  --> src\main.rs:14:5
   |
14 | /     async {
15 | |         // No error
16 | |         info_!("");
17 | |         match Result::<(),()>::Ok(()) {
...  |
21 | |         }
22 | |     };
   | |______^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: futures do nothing unless you `.await` or poll them

warning: Error finalizing incremental compilation session directory `\\?\C:\Users\jon\repos\ice-attempt\target\debug\incremental\ice_attempt-1u7zclevihugp\s-fvq2o5hk8t-1d3ihh7-working`: The system cannot find the file specified. (os error 2)

warning: 2 warnings emitted

error: internal compiler error: failed to process buffered lint here
  --> src\main.rs:11:68
   |
11 | macro_rules! info_ { ($($args:expr),+) => { log_!(info: $($args),+); }; }
   |                                                                    ^
...
19 |             Ok(()) => info_!(""),
   |                       ---------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877\compiler\rustc_lint\src\early.rs:384:18        
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace 
for more info)

error: internal compiler error: failed to process buffered lint here
  --> src\main.rs:11:68
   |
11 | macro_rules! info_ { ($($args:expr),+) => { log_!(info: $($args),+); }; }
   |                                                                    ^
...
20 |             Err(()) => info_!(""),
   |                        ---------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877\compiler\rustc_lint\src\early.rs:384:18        
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace 
for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:974:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ff95e1f9755 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h07eb7c6246901ad5
   1:     0x7ff95e225fdb - core::fmt::write::ha3ea633b18d2da75
   2:     0x7ff95e1ec08d - <std::io::IoSlice as core::fmt::Debug>::fmt::h8573cdc9b491acbf
   3:     0x7ff95e1fd8fd - std::panicking::take_hook::h462942ea222a8ec2
   4:     0x7ff95e1fd3c9 - std::panicking::take_hook::h462942ea222a8ec2
   5:     0x7ff9564796f7 - rustc_driver::report_ice::hc33e4d260fbc44ec
   6:     0x7ff95e1fe362 - std::panicking::rust_panic_with_hook::h18985e2f09a20bf1
   7:     0x7ff95e1fde51 - rust_begin_unwind
   8:     0x7ff95e1fa12f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h07eb7c6246901ad5
   9:     0x7ff95e1fdda9 - rust_begin_unwind
  10:     0x7ff95e1fdd5c - std::panicking::begin_panic_fmt::h1e00459759aac2c8
  11:     0x7ff95ab12744 - rustc_errors::HandlerInner::delay_as_bug::ha06953acff9f7d8d
  12:     0x7ff95ab0deb4 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h32f0e30ae1a18e6e
  13:     0x7ff9564935a7 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h29458aa7f6b0c34e
  14:     0x7ff95649a00a - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h29458aa7f6b0c34e
  15:     0x7ff95649503c - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h29458aa7f6b0c34e
  16:     0x7ff95647c264 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h29458aa7f6b0c34e
  17:     0x7ff9563ec95c - <rustc_infer::infer::error_reporting::<impl rustc_infer::infer::InferCtxt>::check_and_note_conflicting_crates::AbsolutePathPrinter as rustc_middle::ty::print::Printer>::print_type::h3de678dd541c9b13
  18:     0x7ff95648ac8b - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h29458aa7f6b0c34e
  19:     0x7ff95641c77d - rustc_driver::pretty::print_after_hir_lowering::h9432b6a55607de6b
  20:     0x7ff95e20e0ca - std::sys::windows::thread::Thread::new::ha39cc759d7fbecd8
  21:     0x7ff9eceb7034 - BaseThreadInitThunk
  22:     0x7ff9edf7d0d1 - RtlUserThreadStart
```

</p>
</details>

### Other notes from attempts to minimize further

* If I change the log messages to point directly to the log_  macro, the ICE goes away. 
* The async block is required, even though the future isn't being awaited.

**Comment by ecton** [comment]
I didn't realize my rustup was not updating because of a dependency on rustfmt, which is currently broken on nightly. This affected my CI server too. Sorry for the noise.
