### ISSUE TITLE
'assertion failed' after error

### ISSUE THREAD

**Issue by m-hugo** [rust-lang/rust#82092]
### Code

```Rust
use std::result::Result;
fn main() -> Ok {Ok}
```

### Meta

`rustc --version --verbose`:
```
note: rustc 1.52.0-nightly (3f5aee2d5 2021-02-12) running on x86_64-unknown-linux-gnu
```

### Error output

```
error[E0573]: expected type, found variant `Ok`
 --> ./out.rs:2:14
  |
2 | fn main() -> Ok {Ok}
  |              ^^ not a type
  |

thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:189:9

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/3f5aee2d5241139d808f4fdece0026603489afd1/library/core/src/panicking.rs:50:5
   3: rustc_errors::CodeSuggestion::splice_lines
   4: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   5: rustc_errors::HandlerInner::emit_diagnostic
   6: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
   7: rustc_resolve::Resolver::report_errors
   8: rustc_session::utils::<impl rustc_session::session::Session>::time
   9: rustc_resolve::Resolver::resolve_crate
  10: rustc_interface::passes::configure_and_expand_inner
  11: rustc_interface::passes::configure_and_expand::{{closure}}
  12: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  13: rustc_interface::queries::Queries::expansion
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: scoped_tls::ScopedKey<T>::set

```

</p>
</details>

**Comment by osa1** [comment]
There could be multiple ways of fixing this, but I think it would be good to fix this by fixing this function: https://github.com/rust-lang/rust/blob/b86674e7cc8ac9c846ed5aca84aaefc2d0d12e4a/compiler/rustc_resolve/src/late/diagnostics.rs#L92-L106

Given something like `std::prelude::v1::Ok`, this function returns `std::prelude::v1` as the enum path. Instead it should return `std::prelude::v1::Result`. More generally, for variant path like `x::y::V` it will return `x::y` (a module path, instead of a variant path), which is not right.

I don't know if this is easy to fix though. Perhaps there's an easier fix at the call site of this function and we could avoid calling this function altogether.

**Comment by tmiasko** [comment]
cc #82087

**Comment by osa1** [comment]
#82087 should fix this issue, without generating a suggestion.

**Comment by m-hugo** [comment]
i didn't see #78651, closing as duplicate
