### ISSUE TITLE
panicked at 'Failed to recover key for type_of(232faba9fa9763cb-67a35d6dc40d7ed2) with hash 232faba9fa9763cb-67a35d6dc40d7ed2', compiler\rustc_middle\src\ty\query\mod.rs:235:5

### ISSUE THREAD

**Issue by scaphe** [rust-lang/rust#82115]
### Code

```Rust
lots
```

### Meta

`rustc --version --verbose`:
```

$ rustc --version --verbose
rustc 1.50.0-nightly (f0f68778f 2020-12-09)
binary: rustc
commit-hash: f0f68778f798d6d34649745b41770829b17ba5b8
commit-date: 2020-12-09
host: x86_64-pc-windows-gnu
release: 1.50.0-nightly

```

### Error output

```

thread 'rustc' panicked at 'Failed to recover key for type_of(232faba9fa9763cb-67a35d6dc40d7ed2) with hash 232faba9fa9763cb-67a35d6dc40d7ed2', compiler\rustc_middle\src\ty\query\mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0f68778f798d6d34649745b41770829b17ba5b8\/library\std\src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f0f68778f798d6d34649745b41770829b17ba5b8\/library\std\src/panicking.rs:435:5
   2: rustc_middle::ty::query::try_load_from_on_disk_cache::{{closure}}
   3: rustc_middle::ty::query::try_load_from_on_disk_cache
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: rustc_incremental::persist::save::save_in
   7: rustc_data_structures::sync::join
   8: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   9: rustc_incremental::persist::save::save_dep_graph
  10: rustc_codegen_ssa::base::finalize_tcx
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_interface::passes::QueryContext::enter
  14: rustc_interface::queries::Queries::ongoing_codegen
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: rustc_interface::interface::create_compiler_and_run
  18: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (f0f68778f 2020-12-09) running on x86_64-pc-windows-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
above```

</p>
</details>

**Comment by scaphe** [comment]
clean build fixed it

**Comment by Aaron1011** [comment]
This is fixed in the latest nightly

**Comment by wesleywiser** [comment]
@Aaron1011 do you remember what PR might have fixed this? I took a quick look at the merged PR list around this time and didn't find anything that looked immediately relevant.

**Comment by Enselic** [comment]
Triage: Closing since
* This issue was claimed to have been fixed and there were no objections.
* There is no MCVE that can be used with `cargo bisect-rustc`.

Feel free to reopen if the problem persists, but then please also include step-by-step instructions on how to reproduce.
