### ISSUE TITLE
Closure syntax error crashes compiler: my code where I confused a variable and a type crashes rustc

### ISSUE THREAD

**Issue by diekmann** [rust-lang/rust#82298]
### Code

```Rust
fn main() {
    |f: f(_)| { };
}
```

This code is syntactically wrong, so it it okay that it does not compile. Yet, the compiler nicely asked me to report this crash.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

### Error output

```
$ cargo run
   Compiling looping v0.1.0 (/home/corny/rust/looping)
error[E0573]: expected type, found local variable `f`
 --> src/main.rs:2:9
  |
2 |     |f: f(_)| { };
  |         ^^^^ not a type

thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(13),
)', compiler/rustc_ast_lowering/src/lib.rs:674:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.
error: could not compile `looping`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build
   Compiling looping v0.1.0 (/home/corny/rust/looping)
error[E0573]: expected type, found local variable `f`
 --> src/main.rs:2:9
  |
2 |     |f: f(_)| { };
  |         ^^^^ not a type

thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(13),
)', compiler/rustc_ast_lowering/src/lib.rs:674:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5
   2: rustc_ast_lowering::LoweringContext::lower_node_id_generic
   3: rustc_ast_lowering::path::<impl rustc_ast_lowering::LoweringContext>::lower_path_segment
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: rustc_ast_lowering::path::<impl rustc_ast_lowering::LoweringContext>::lower_qpath
   6: rustc_ast_lowering::LoweringContext::lower_ty_direct
   7: rustc_ast_lowering::LoweringContext::lower_fn_decl
   8: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_closure
   9: rustc_data_structures::stack::ensure_sufficient_stack
  10: rustc_ast_lowering::LoweringContext::lower_stmt
  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  12: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  13: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  14: rustc_arena::cold_path
  15: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_fn_body_block
  16: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_maybe_async_body
  17: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_item
  18: rustc_ast_lowering::LoweringContext::with_hir_id_owner
  19: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  20: rustc_ast_lowering::lower_crate
  21: rustc_interface::passes::BoxedResolver::access::{{closure}}
  22: rustc_interface::passes::configure_and_expand::{{closure}}
  23: rustc_interface::passes::BoxedResolver::access
  24: rustc_interface::queries::Queries::lower_to_hir
  25: rustc_interface::queries::Queries::global_ctxt
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  27: rustc_span::with_source_map
  28: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.
error: could not compile `looping`

To learn more, run the command again with --verbose.
```

</p>
</details>

### More

With rust nightly, everything works as expected, without crash:

```
$ rustup default nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-02-19, rust version 1.52.0-nightly (0148b971c 2021-02-18)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 15.0 MiB /  15.0 MiB (100 %)  10.1 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 24.9 MiB /  24.9 MiB (100 %)   6.6 MiB/s in  4s ETA:  0s
info: downloading component 'rustc'
 50.5 MiB /  50.5 MiB (100 %)   9.5 MiB/s in  6s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: using up to 500.0 MiB of RAM to unpack components
  6.0 MiB /   6.0 MiB (100 %)   5.1 MiB/s in  1s ETA:  0s
info: installing component 'clippy'
info: installing component 'rust-docs'
 15.0 MiB /  15.0 MiB (100 %)   1.2 MiB/s in 20s ETA:  0s    
info: installing component 'rust-std'
 24.9 MiB /  24.9 MiB (100 %)   4.1 MiB/s in 10s ETA:  0s
info: installing component 'rustc'
 50.5 MiB /  50.5 MiB (100 %)   4.0 MiB/s in 12s ETA:  0s
info: installing component 'rustfmt'
  3.6 MiB /   3.6 MiB (100 %)   1.1 MiB/s in  3s ETA:  0s
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu installed - rustc 1.52.0-nightly (0148b971c 2021-02-18)

$ RUST_BACKTRACE=1 cargo build
   Compiling looping v0.1.0 (/home/corny/rust/looping)
error[E0573]: expected type, found local variable `f`
 --> src/main.rs:2:9
  |
2 |     |f: f(_)| { };
  |         ^^^^ not a type

error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.
error: could not compile `looping`

To learn more, run the command again with --verbose.
```

**Comment by jyn514** [comment]
If this is fixed on nightly, there's no need to report it. Thanks though!
