### ISSUE TITLE
ICE: Return type `i8` must match vector element type `u16`, compiler/rustc_mir/src/interpret/intrinsics.rs:474:17

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#82880]
### Code

```Rust
#![feature(platform_intrinsics)]
#![feature(staged_api)]
struct u16x2(u16, u16);
extern "platform-intrinsic" {
    #[rustc_const_stable(feature = "foo", since = "1.3.37")]
    fn simd_extract<T, U>(x: T, idx: u32) -> U;
}
fn main() {
    const U: u16x2 = u16x2(13, 14);
    const V: u16x2 = U;
    const Y0: i8 = unsafe { simd_extract(V, 0) };
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (51748a8fc 2021-03-05)
binary: rustc
commit-hash: 51748a8fc77283914d4135f31b5966a407208187
commit-date: 2021-03-05
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0
```

### Error output

```
warning: type `u16x2` should have an upper camel case name
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:8
  |
3 | struct u16x2(u16, u16);
  |        ^^^^^ help: convert the identifier to upper camel case (notice the capitalization): `U16x2`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: struct is never constructed: `u16x2`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:8
  |
3 | struct u16x2(u16, u16);
  |        ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function is never used: `simd_extract`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:6:5
  |
6 |     fn simd_extract<T, U>(x: T, idx: u32) -> U;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant is never used: `U`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:9:5
  |
9 |     const U: u16x2 = u16x2(13, 14);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant is never used: `V`
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:10:5
   |
10 |     const V: u16x2 = U;
   |     ^^^^^^^^^^^^^^^^^^^

warning: constant is never used: `Y0`
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:11:5
   |
11 |     const Y0: i8 = unsafe { simd_extract(V, 0) };
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: module has missing stability attribute
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
   |
1  | / #![feature(platform_intrinsics)]
2  | | #![feature(staged_api)]
3  | | struct u16x2(u16, u16);
4  | | extern "platform-intrinsic" {
...  |
11 | |     const Y0: i8 = unsafe { simd_extract(V, 0) };
12 | | }
   | |_^

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `u16`,
 right: `i8: Return type `i8` must match vector element type `u16``', compiler/rustc_mir/src/interpret/intrinsics.rs:474:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (51748a8fc 2021-03-05) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `main::Y0`
#1 [eval_to_const_value_raw] simplifying constant for the type system `main::Y0`
end of query stack
error: aborting due to previous error; 6 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: type `u16x2` should have an upper camel case name
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:8
  |
3 | struct u16x2(u16, u16);
  |        ^^^^^ help: convert the identifier to upper camel case (notice the capitalization): `U16x2`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: struct is never constructed: `u16x2`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:8
  |
3 | struct u16x2(u16, u16);
  |        ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function is never used: `simd_extract`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:6:5
  |
6 |     fn simd_extract<T, U>(x: T, idx: u32) -> U;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant is never used: `U`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:9:5
  |
9 |     const U: u16x2 = u16x2(13, 14);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: constant is never used: `V`
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:10:5
   |
10 |     const V: u16x2 = U;
   |     ^^^^^^^^^^^^^^^^^^^

warning: constant is never used: `Y0`
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:11:5
   |
11 |     const Y0: i8 = unsafe { simd_extract(V, 0) };
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: module has missing stability attribute
  --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
   |
1  | / #![feature(platform_intrinsics)]
2  | | #![feature(staged_api)]
3  | | struct u16x2(u16, u16);
4  | | extern "platform-intrinsic" {
...  |
11 | |     const Y0: i8 = unsafe { simd_extract(V, 0) };
12 | | }
   | |_^

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `u16`,
 right: `i8: Return type `i8` must match vector element type `u16``', compiler/rustc_mir/src/interpret/intrinsics.rs:474:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/51748a8fc77283914d4135f31b5966a407208187/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/51748a8fc77283914d4135f31b5966a407208187/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: rustc_mir::interpret::intrinsics::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::emulate_intrinsic
   5: <rustc_mir::const_eval::machine::CompileTimeInterpreter as rustc_mir::interpret::machine::Machine>::call_intrinsic
   6: rustc_mir::interpret::terminator::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_fn_call
   7: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
   8: rustc_mir::const_eval::eval_queries::eval_to_allocation_raw_provider
   9: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_allocation_raw>::compute
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::force_query_with_job
  13: rustc_query_system::query::plumbing::get_query_impl
  14: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw
  15: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  16: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::force_query_with_job
  20: rustc_query_system::query::plumbing::get_query_impl
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
  22: rustc_mir::const_eval::eval_queries::eval_to_const_value_raw_provider
  23: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::eval_to_const_value_raw>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::force_query_with_job
  27: rustc_query_system::query::plumbing::get_query_impl
  28: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
  29: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  30: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly
  31: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_item
  32: rustc_hir::intravisit::Visitor::visit_nested_item
  33: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  34: rustc_hir::intravisit::walk_block
  35: rustc_hir::intravisit::walk_expr
  36: rustc_hir::intravisit::walk_body
  37: rustc_hir::intravisit::walk_fn
  38: rustc_hir::intravisit::walk_item
  39: rustc_hir::intravisit::Visitor::visit_nested_item
  40: rustc_hir::intravisit::walk_crate
  41: rustc_session::utils::<impl rustc_session::session::Session>::time
  42: std::panic::catch_unwind
  43: rustc_session::utils::<impl rustc_session::session::Session>::time
  44: rustc_interface::passes::analysis
  45: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  46: rustc_data_structures::stack::ensure_sufficient_stack
  47: rustc_query_system::query::plumbing::force_query_with_job
  48: rustc_query_system::query::plumbing::get_query_impl
  49: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  50: rustc_interface::passes::QueryContext::enter
  51: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  52: rustc_span::with_source_map
  53: rustc_interface::interface::create_compiler_and_run
  54: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (51748a8fc 2021-03-05) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [eval_to_allocation_raw] const-evaluating + checking `main::Y0`
#1 [eval_to_const_value_raw] simplifying constant for the type system `main::Y0`
#2 [eval_to_const_value_raw] simplifying constant for the type system `main::Y0`
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 6 warnings emitted
```

</p>
</details>

**Comment by Alexendoo** [comment]
Original can still ice with the addition of a stability gate, but closing for the same reason as #94382
