### ISSUE TITLE
ICE: print_if saw if with weird alternative', compiler/rustc_hir_pretty/src/lib.rs:1106:25

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83136]
### Code

https://github.com/integer32llc/rust-playground/commit/a19bffb94c30dfa2080d29c8f5e0381ef7ff68e0

### Meta

`rustc --version`: rustc 1.52.0-nightly (3a5d45f68 2021-03-09)

### Error output

```
thread 'rustc' panicked at 'print_if saw if with weird alternative', compiler/rustc_hir_pretty/src/lib.rs:1106:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (3a5d45f68 2021-03-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unpretty=hir -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-arg=-fuse-ld=lld --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `ui`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'print_if saw if with weird alternative', compiler/rustc_hir_pretty/src/lib.rs:1106:25
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_hir_pretty::State::print_else
   2: rustc_hir_pretty::State::print_expr
   3: rustc_hir_pretty::State::print_block_maybe_unclosed
   4: rustc_hir_pretty::State::print_expr
   5: rustc_hir_pretty::State::print_stmt
   6: rustc_hir_pretty::State::print_block_maybe_unclosed
   7: rustc_hir_pretty::State::print_expr
   8: rustc_hir_pretty::State::print_arm
   9: rustc_hir_pretty::State::print_expr
  10: rustc_hir_pretty::State::print_expr
  11: rustc_hir_pretty::State::print_stmt
  12: rustc_hir_pretty::State::print_block_maybe_unclosed
  13: rustc_hir_pretty::State::print_expr
  14: <rustc_driver::pretty::NoAnn as rustc_hir_pretty::PpAnn>::nested
  15: rustc_hir_pretty::State::print_item
  16: <rustc_driver::pretty::NoAnn as rustc_hir_pretty::PpAnn>::nested
  17: rustc_hir_pretty::State::print_mod
  18: rustc_hir_pretty::State::print_item
  19: <rustc_driver::pretty::NoAnn as rustc_hir_pretty::PpAnn>::nested
  20: rustc_hir_pretty::State::print_mod
  21: rustc_hir_pretty::print_crate
  22: rustc_driver::pretty::print_after_hir_lowering
  23: rustc_interface::passes::QueryContext::enter
  24: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  25: rustc_span::with_source_map
  26: rustc_interface::interface::create_compiler_and_run
  27: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/blob/d6eaea1c8860adb5302d2fbaad409e36585ab217/compiler/rustc_hir_pretty/src/lib.rs#L1118-L1121

**Comment by matthiaskrgr** [comment]
dupe of https://github.com/rust-lang/rust/issues/82329 ?
Most of the -Zunpretty flags are pretty ICEy

**Comment by jyn514** [comment]
> dupe of #82329 ?

yup, thanks!
