### ISSUE TITLE
'rustc' panicked at 'do not use `optimized_mir` for constants: Const', 

### ISSUE THREAD

**Issue by basavesh** [rust-lang/rust#83200]
### Code

```Rust
https://gist.github.com/rust-play/00c628037372767e81f239fd87f7ed55
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

`cargo --version --verbose`:
```
cargo 1.51.0-nightly (c3abcfe8a 2021-01-25)
release: 1.51.0
commit-hash: c3abcfe8a75901c7c701557a728941e8fb19399e
commit-date: 2021-01-25
```

### Error output

```
Compiling secret_integers_usage v0.1.0 (/home/basavesh/research/rustStuff/splitspectre/secret_integers_usage)
thread 'rustc' panicked at 'do not use `optimized_mir` for constants: Const', compiler/rustc_mir/src/transform/mod.rs:579:24

query stack during panic:
#0 [optimized_mir] optimizing MIR for `simple::get_secret_key::{constant#0}`
end of query stack
error: could not compile `secret_integers_usage`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
0:     0x7fdf4ef05de7 - std::backtrace_rs::backtrace::libunwind::trace::h8bc78f7bc1f75bdb
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fdf4ef05de7 - std::backtrace_rs::backtrace::trace_unsynchronized::ha4c961c9576f95ba
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdf4ef05de7 - std::sys_common::backtrace::_print_fmt::hc20cfdc233d6eb02
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fdf4ef05de7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04bea14549780a0f
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fdf4ef76ebc - core::fmt::write::h3868db8542c90941
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/core/src/fmt/mod.rs:1096:17
   5:     0x7fdf4eef8612 - std::io::Write::write_fmt::h55dd75636eef6a5c
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/io/mod.rs:1568:15
   6:     0x7fdf4ef09d45 - std::sys_common::backtrace::_print::h6439e8525077c7da
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fdf4ef09d45 - std::sys_common::backtrace::print::h02b685f728ce3931
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fdf4ef09d45 - std::panicking::default_hook::{{closure}}::h7c29625065fafae1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:208:50
   9:     0x7fdf4ef098a3 - std::panicking::default_hook::hba441710bb71f4d5
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:225:9
  10:     0x7fdf4f762f6b - rustc_driver::report_ice::h6029ac9bafd12823
  11:     0x7fdf4ef0a646 - std::panicking::rust_panic_with_hook::ha936eb00e51bc4d9
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:595:17
  12:     0x7fdf4ef0a167 - std::panicking::begin_panic_handler::{{closure}}::hcd15140e0238536e
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:497:13
  13:     0x7fdf4ef062ac - std::sys_common::backtrace::__rust_end_short_backtrace::hb13a021bb64823a1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fdf4ef0a0c9 - rust_begin_unwind
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:493:5
  15:     0x7fdf4ef0a07b - std::panicking::begin_panic_fmt::h3ef6798fa589483b
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:435:5
  16:     0x7fdf52137195 - rustc_mir::transform::optimized_mir::hd9c246171458d5c8
  17:     0x7fdf4f77cffa - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute::h3f0c2ab24dc10395
  18:     0x7fdf4f72bb75 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h024e06bccb8d4c44
  19:     0x7fdf4f781583 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h05cbe9ffb5c9a521
  20:     0x7fdf4f78289c - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::he9c93d7a7639cb7e
  21:     0x7fdf4f78bff3 - rustc_middle::ty::query::plumbing::<impl rustc_query_system::query::QueryContext for rustc_middle::ty::context::TyCtxt>::start_query::{{closure}}::{{closure}}::{{closure}}::h52f19a20ea4b6e60
  22:     0x7fdf4f79176f - rustc_data_structures::stack::ensure_sufficient_stack::h0dd45ab819c3bfac
  23:     0x7fdf4f74485f - rustc_query_system::query::plumbing::force_query_with_job::h5b3652d0d8f383f5
  24:     0x7fdf4f74228c - rustc_query_system::query::plumbing::get_query_impl::h4fc671faf7ed5767
  25:     0x7fdf4f787763 - rustc_mir::util::graphviz::write_mir_graphviz::h6d3864ca53c10a88
  26:     0x7fdf4f73b368 - rustc_driver::pretty::print_after_hir_lowering::h5bcaea8fe9fa88cf
  27:     0x7fdf4f790ec4 - rustc_interface::passes::QueryContext::enter::h5fbfa7fc999de143
  28:     0x7fdf51b057a4 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h734423f4595e60ef
  29:     0x7fdf51b3cdf4 - rustc_span::with_source_map::h0b3994d7a2f67198
  30:     0x7fdf51b06477 - rustc_interface::interface::create_compiler_and_run::h4d7ef2129059135c
  31:     0x7fdf51b3dabf - std::sys_common::backtrace::__rust_begin_short_backtrace::hcb0be55fe1a86377
  32:     0x7fdf51b233ca - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0363f9b03bb4d9ca
  33:     0x7fdf4ef1ab5a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8ffdf8dc1f37e360
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/alloc/src/boxed.rs:1488:9
  34:     0x7fdf4ef1ab5a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h74f6ec149ce6acc8
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/alloc/src/boxed.rs:1488:9
  35:     0x7fdf4ef1ab5a - std::sys::unix::thread::Thread::new::thread_start::h565bef3956c58d58
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys/unix/thread.rs:71:17
  36:     0x7fdf4ee3a609 - start_thread
  37:     0x7fdf4ed4e293 - clone
  38:                0x0 - <unknown>
```

</p>
</details>

**Comment by basavesh** [comment]
fixed in the latest nightly build. Closing it. Apologies.
