### ISSUE TITLE
ICE: `usize`: cannot relate constants of different types', compiler/rustc_middle/src/ty/relate.rs:502:5

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#83253]
### Code

```Rust
impl X {
    fn getn<const N: usize>() -> [u8; N] {
        getn::<N>()
    }
}
fn getn<const N: cfg_attr>() -> [u8; N] {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (36f1f04f1 2021-03-17)
binary: rustc
commit-hash: 36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d
commit-date: 2021-03-17
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0
```

### Error output

```
error[E0412]: cannot find type `X` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:6
  |
1 | impl X {
  |      ^ not found in this scope

error[E0573]: expected type, found built-in attribute `cfg_attr`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:6:18
  |
6 | fn getn<const N: cfg_attr>() -> [u8; N] {}
  |                  ^^^^^^^^ not a type

error[E0601]: `main` function not found in crate `perses_node_priority_with_dfs_delta_reduced_mutant`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | / impl X {
2 | |     fn getn<const N: usize>() -> [u8; N] {
3 | |         getn::<N>()
4 | |     }
5 | | }
6 | | fn getn<const N: cfg_attr>() -> [u8; N] {}
  | |__________________________________________^ consider adding a `main` function to `perses_node_priority_with_dfs_delta_reduced_mutant.rs`

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `[type error]`,
 right: `usize`: cannot relate constants of different types', /rustc/36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d/compiler/rustc_middle/src/ty/relate.rs:502:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (36f1f04f1 2021-03-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1: 5:2>::getn`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0412, E0573, E0601.
For more information about an error, try `rustc --explain E0412`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0412]: cannot find type `X` in this scope
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:6
  |
1 | impl X {
  |      ^ not found in this scope

error[E0573]: expected type, found built-in attribute `cfg_attr`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:6:18
  |
6 | fn getn<const N: cfg_attr>() -> [u8; N] {}
  |                  ^^^^^^^^ not a type

error[E0601]: `main` function not found in crate `perses_node_priority_with_dfs_delta_reduced_mutant`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1
  |
1 | / impl X {
2 | |     fn getn<const N: usize>() -> [u8; N] {
3 | |         getn::<N>()
4 | |     }
5 | | }
6 | | fn getn<const N: cfg_attr>() -> [u8; N] {}
  | |__________________________________________^ consider adding a `main` function to `perses_node_priority_with_dfs_delta_reduced_mutant.rs`

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `[type error]`,
 right: `usize`: cannot relate constants of different types', /rustc/36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d/compiler/rustc_middle/src/ty/relate.rs:502:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: rustc_middle::ty::relate::super_relate_consts
   5: rustc_infer::infer::combine::<impl rustc_infer::infer::InferCtxt>::super_combine_consts
   6: rustc_middle::ty::relate::super_relate_tys
   7: rustc_infer::infer::combine::<impl rustc_infer::infer::InferCtxt>::super_combine_tys
   8: <rustc_infer::infer::sub::Sub as rustc_middle::ty::relate::TypeRelation>::tys
   9: rustc_infer::infer::InferCtxt::commit_if_ok
  10: rustc_infer::infer::fudge::<impl rustc_infer::infer::InferCtxt>::fudge_inference_if_ok
  11: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  12: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  13: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  14: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  15: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  16: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  17: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  18: rustc_typeck::check::check::check_fn
  19: rustc_infer::infer::InferCtxtBuilder::enter
  20: rustc_typeck::check::typeck
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  22: rustc_query_system::query::plumbing::force_query_with_job
  23: rustc_query_system::query::plumbing::get_query_impl
  24: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  25: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  26: rustc_typeck::check::typeck_item_bodies
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  28: rustc_data_structures::stack::ensure_sufficient_stack
  29: rustc_query_system::query::plumbing::force_query_with_job
  30: rustc_query_system::query::plumbing::get_query_impl
  31: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  32: rustc_session::utils::<impl rustc_session::session::Session>::time
  33: rustc_typeck::check_crate
  34: rustc_interface::passes::analysis
  35: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  36: rustc_data_structures::stack::ensure_sufficient_stack
  37: rustc_query_system::query::plumbing::force_query_with_job
  38: rustc_query_system::query::plumbing::get_query_impl
  39: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  40: rustc_interface::passes::QueryContext::enter
  41: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  42: rustc_span::with_source_map
  43: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (36f1f04f1 2021-03-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at perses_node_priority_with_dfs_delta_reduced_mutant.rs:1:1: 5:2>::getn`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0412, E0573, E0601.
For more information about an error, try `rustc --explain E0412`.
```

</p>
</details>

**Comment by SNCPlay42** [comment]
`getn`'s `N` parameter doesn't have to have an error type; it appears it can be any type (that doesn't trip the full `const_generics` feature gate error.) This version ICEs without any prior diagnostics:

```rust
fn foo<const N: usize>() -> [u8; N] {
    bar::<N>()
}

fn bar<const N: u8>() -> [u8; N] {}
```

Neither version ICEs on beta or stable. (const generics aren't stable on 1.50, but after reporting an error for use of unstable features the compiler reports the same errors as beta and doesn't ICE.)

@rustbot label A-const-generics regression-from-stable-to-nightly

**Comment by hameerabbasi** [comment]
Bisected, this is a weird one:

```
********************************************************************************
Regression in nightly-2021-03-17
********************************************************************************

fetching https://static.rust-lang.org/dist/2021-03-16/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2021-03-16: 40 B / 40 B [===============] 100.00 % 697.91 KB/s converted 2021-03-16 to 107896c32d5dda4db508968ff34997a39d286966
fetching https://static.rust-lang.org/dist/2021-03-17/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2021-03-17: 40 B / 40 B [===============] 100.00 % 705.85 KB/s converted 2021-03-17 to f5d8117c338a788bd24abec733fd143dfceb25a0
looking for regression commit between 2021-03-16 and 2021-03-17
opening existing repository at "rust.git"
refreshing repository
fetching (via local git) commits from 107896c32d5dda4db508968ff34997a39d286966 to f5d8117c338a788bd24abec733fd143dfceb25a0
opening existing repository at "rust.git"
refreshing repository
looking up first commit
looking up second commit
checking that commits are by bors and thus have ci artifacts...
finding bors merge commits
found 6 bors merge commits in the specified range
  commit[0] 2021-03-15UTC: Auto merge of #83121 - the8472:env-rwlock-2, r=joshtriplett
  commit[1] 2021-03-16UTC: Auto merge of #83153 - Aaron1011:eval-always-extern_mod_stmt_cnum, r=michaelwoerister
  commit[2] 2021-03-16UTC: Auto merge of #82898 - oli-obk:tait_🧊, r=nikomatsakis
  commit[3] 2021-03-16UTC: Auto merge of #82838 - Amanieu:rustdoc_asm, r=nagisa
  commit[4] 2021-03-16UTC: Auto merge of #83199 - JohnTitor:rollup-zrfk94a, r=JohnTitor
  commit[5] 2021-03-16UTC: Auto merge of #82536 - sexxi-goose:handle-patterns-take-2, r=nikomatsakis
validated commits found, specifying toolchains

installing 107896c32d5dda4db508968ff34997a39d286966
rustc for x86_64-unknown-linux-gnu: 1003.49 KB / 49.11 MB  2.00 % 881.96 KB/s 56rustc for x86_64-unknown-linux-gnu: 1004.49 KB / 49.11 MB  2.00 % 882.53 KB/s 56rustc for x86_64-unknown-linux-gnu: 1012.49 KB / 49.11 MB  2.01 % 889.51 KB/s 55rustc for x86_64-unknown-linux-gnu: 1020.49 KB / 49.11 MB  2.03 % 896.23 KB/s 55rustc for x86_64-unknown-linux-gnu: 1021.49 KB / 49.11 MB  2.03 % 896.79 KB/s 55cargo for x86_64-unknown-linux-gnu: 5.96 MB / 5.96 MB [====] 100.00 % 7.31 MB/s testing...
RESULT: 107896c32d5dda4db508968ff34997a39d286966, ===> No
uninstalling 107896c32d5dda4db508968ff34997a39d286966

installing f5d8117c338a788bd24abec733fd143dfceb25a0
cargo for x86_64-unknown-linux-gnu: 5.96 MB / 5.96 MB [====] 100.00 % 8.68 MB/s testing...
RESULT: f5d8117c338a788bd24abec733fd143dfceb25a0, ===> No
uninstalling f5d8117c338a788bd24abec733fd143dfceb25a0

ERROR: the commit at the end of the range (f5d8117c338a788bd24abec733fd143dfceb25a0) does not reproduce the regression
```

**Comment by apiraino** [comment]
@hameerabbasi I've attempted a second bisection using the snippet from the [second comment](https://github.com/rust-lang/rust/issues/83253#issuecomment-801766548), I got a different result (not sure why, unsure if it helps)

searched nightlies: from nightly-2021-02-15 to nightly-2021-03-18
regressed nightly: nightly-2021-03-18
searched commits: from https://github.com/rust-lang/rust/commit/f5d8117c338a788bd24abec733fd143dfceb25a0 to https://github.com/rust-lang/rust/commit/36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d
regressed commit: https://github.com/rust-lang/rust/commit/e655fb62216b6ba64a094b30f116d7988d19322d

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve --start=2021-02-15 --regress=ice 
```
</details>

**Comment by oli-obk** [comment]
> This PR does not cause functional changes

I guess that was a lie 🙃 

I'm looking into this

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2383253.20ICE.3A.20.60usize.60.3A.20cannot.20relate.20constants.20of.20different.20t.E2.80.A6) in the prioritization working group.

@rustbot label: +P-high -I-prioritize
