### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:189:9

### ISSUE THREAD

**Issue by szunami** [rust-lang/rust#83309]
```
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:189:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/core/src/panicking.rs:50:5
   3: rustc_errors::CodeSuggestion::splice_lines
   4: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   5: rustc_errors::json::Diagnostic::from_errors_diagnostic
   6: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: rustc_errors::HandlerInner::emit_diagnostic
   8: rustc_errors::Handler::emit_diagnostic
   9: rustc_mir::borrow_check::do_mir_borrowck
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_mir::borrow_check::mir_borrowck
  12: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  13: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::force_query_with_job
  17: rustc_query_system::query::plumbing::get_query_impl
  18: rustc_query_system::query::plumbing::ensure_query_impl
  19: rustc_interface::passes::analysis
  20: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  21: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::force_query_with_job
  25: rustc_query_system::query::plumbing::get_query_impl
  26: rustc_interface::passes::QueryContext::enter
  27: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  28: rustc_span::with_source_map
  29: rustc_interface::interface::create_compiler_and_run
  30: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (e9920ef77 2021-02-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z share-generics=y -C embed-bitcode=no -C debuginfo=2 -C linker=/usr/bin/clang -C incremental -C link-arg=-fuse-ld=lld --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `falling`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 5 warnings emitted

For more information about this error, try `rustc --explain E0594`.
error: could not compile `staircases`
```

Code that generated this error is available here:

https://github.com/szunami/staircases/commit/cc74cecd6bdc1d0a8a5b266b977092ae944c3b8f

I am happy to spend some time trying to create a smaller repro but it will take me a few days. This error is reproducible on my machine.

**Comment by szunami** [comment]
FYI, with https://github.com/szunami/staircases/pull/3/commits/a0dfe8324c7671589bc2c01664b62480982ca404 this code compiled.

**Comment by tmiasko** [comment]
```rust
fn main() {}

pub struct Query;
pub struct Velocity(i32);
pub struct QueryIter<'a>(&'a ());

impl Query {
    pub fn iter_mut<'a>(&'a mut self) -> QueryIter<'a> {
        todo!();
    }
}

impl<'a> Iterator for QueryIter<'a> {
    type Item = &'a Velocity;

    fn next(&mut self) -> Option<Self::Item> {
        todo!();
    }
}

fn foo(mut q: Query) {
    for mut v in q.iter_mut() {
        v.0 -= 1;
    }
}
```

Similar error was reported in #83292.

**Comment by apiraino** [comment]
Assigning priority as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2383309.20thread.20'rustc'.20panicked.20at.20'assertion.20failed.3A.20!self.2E.E2.80.A6) and removing `I-prioritize`.

@rustbot label -I-prioritize +P-medium
