### ISSUE TITLE
A rustc crash

### ISSUE THREAD

**Issue by zeenix** [rust-lang/rust#83321]
```
     Running `rustc --crate-name zvariant --edition=2018 zvariant/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="enumflags2"' --cfg 'feature="gvariant"' -C metadata=28a35b025aa7596b -C extra-filename=-28a35b025aa7596b --out-dir /home/zeenix/checkout/dbus/zbus/target/debug/deps -C incremental=/home/zeenix/checkout/dbus/zbus/target/debug/incremental -L dependency=/home/zeenix/checkout/dbus/zbus/target/debug/deps --extern byteorder=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libbyteorder-a6db7e07f13316c2.rmeta --extern enumflags2=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libenumflags2-f9e9f7ecfba82bb2.rmeta --extern serde=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libserde-5b03fa9c708802b8.rmeta --extern zvariant_derive=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libzvariant_derive-1dd2fd47904d1814.so`
       Fresh gobject-sys v0.10.0 (https://github.com/gtk-rs/sys#5f35e26c)
       Fresh glib v0.10.0 (https://github.com/gtk-rs/glib?rev=c9ee583cea0#c9ee583c)
warning: unused variable: `s`
    --> zvariant/src/lib.rs:1613:13
     |
1613 |         let s = SomeStuct {
     |             ^ help: if this is intentional, prefix it with an underscore: `_s`
     |
     = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

thread 'rustc' panicked at 'index out of bounds: the len is 174568 but the index is 943372', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/compiler/rustc_query_system/src/dep_graph/graph.rs:1546:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:69:5
   3: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::get_query_impl
   7: rustc_plugin_impl::build::find_plugin_registrar
   8: rustc_session::utils::<impl rustc_session::session::Session>::time
   9: rustc_session::utils::<impl rustc_session::session::Session>::time
  10: rustc_interface::passes::analysis
  11: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  12: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  13: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  14: rustc_data_structures::stack::ensure_sufficient_stack
  15: rustc_query_system::query::plumbing::get_query_impl
  16: rustc_interface::passes::QueryContext::enter
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [plugin_registrar_fn] looking up the plugin registrar for a crate
#1 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at 'range end index 364357 out of range for slice of length 364356', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/compiler/rustc_query_system/src/dep_graph/serialized.rs:48:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:41:5
   3: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
   6: rustc_query_system::query::plumbing::ensure_query_impl
   7: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   8: rustc_session::utils::<impl rustc_session::session::Session>::time
   9: rustc_interface::passes::analysis
  10: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  11: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: rustc_query_system::query::plumbing::get_query_impl
  15: rustc_interface::passes::QueryContext::enter
  16: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  17: rustc_span::with_source_map
  18: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `zvariant`

Caused by:
  process didn't exit successfully: `rustc --crate-name zvariant --edition=2018 zvariant/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="enumflags2"' --cfg 'feature="gvariant"' -C metadata=28a35b025aa7596b -C extra-filename=-28a35b025aa7596b --out-dir /home/zeenix/checkout/dbus/zbus/target/debug/deps -C incremental=/home/zeenix/checkout/dbus/zbus/target/debug/incremental -L dependency=/home/zeenix/checkout/dbus/zbus/target/debug/deps --extern byteorder=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libbyteorder-a6db7e07f13316c2.rmeta --extern enumflags2=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libenumflags2-f9e9f7ecfba82bb2.rmeta --extern serde=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libserde-5b03fa9c708802b8.rmeta --extern zvariant_derive=/home/zeenix/checkout/dbus/zbus/target/debug/deps/libzvariant_derive-1dd2fd47904d1814.so` (exit code: 101)
```

**Comment by zeenix** [comment]
I did a `cargo clean` and now I can't reproduce the issue. I'll close this now and reopen if I can again. If I manage to reproduce it again, I will try to provide a minimal example. In the meantime, this is the [WIP branch](https://github.com/zeenix/zbus/tree/zeenix/wip/rustc-crash-issue-83321) with which the crash happened (I just ran `cargo test --no-run` in the toplevel dir).

**Comment by p0lunin** [comment]
I have a similar issue.
```
thread 'rustc' panicked at 'index out of bounds: the len is 221944 but the index is 221944', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\compiler\rustc_query_system\src\dep_graph\gr
aph.rs:477:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

```
erorr locates here: https://github.com/rust-lang/rust/blob/stable/compiler/rustc_query_system/src/dep_graph/graph.rs#L477
but i upgrade my rustc toolchain and i can't reproduce this bug now, and can't show the backtrace.
