### ISSUE TITLE
Cargo seg fault

### ISSUE THREAD

**Issue by maxlein** [rust-lang/rust#83685]
Immediate seg fault when calling `cargo build` on Ubuntu 20.04 x64.  

I tried this code:

```bash
$ cargo new demo
$ cargo build
```

I expected to see this happen:  

Build runs through.

Instead, this happened:  

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (signal: 11, SIGSEGV: invalid memory reference)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1
```

<details><summary>Backtrace</summary>
<p>

```
#0  0x000056105166febc in tcache_dalloc_large (tsd=<optimized out>, tcache=0x7f54f93fe0c0, ptr=0x7f54f8239260, binind=0, slow_path=false)
    at ../jemalloc/include/jemalloc/internal/tcache_inlines.h:203
203	../jemalloc/include/jemalloc/internal/tcache_inlines.h: No such file or directory.
[Current thread is 1 (Thread 0x7f54f93ff700 (LWP 28673))]
(gdb) 
(gdb) bt
#0  0x000056105166febc in tcache_dalloc_large (tsd=<optimized out>, tcache=0x7f54f93fe0c0, ptr=0x7f54f8239260, binind=0, slow_path=false)
    at ../jemalloc/include/jemalloc/internal/tcache_inlines.h:203
#1  arena_dalloc (tsdn=0x7f54f93fdf00, ptr=0x7f54f8239260, tcache=0x7f54f93fe0c0, alloc_ctx=<optimized out>, slow_path=false)
    at ../jemalloc/include/jemalloc/internal/arena_inlines_b.h:232
#2  idalloctm (tsdn=0x7f54f93fdf00, ptr=0x7f54f8239260, tcache=0x7f54f93fe0c0, alloc_ctx=<optimized out>, is_internal=false, slow_path=false)
    at ../jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:118
#3  ifree (tsd=<optimized out>, ptr=0x7f54f8239260, tcache=0x7f54f93fe0c0, slow_path=false) at ../jemalloc/src/jemalloc.c:2222
#4  free (ptr=0x7f54f8239260) at ../jemalloc/src/jemalloc.c:2393
#5  0x00007f5502328741 in LLVMRustCreateTargetMachine ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#6  0x00007f55022c00ce in rustc_codegen_llvm::back::write::target_machine_factory::{{closure}} ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#7  0x00007f55022bf4ff in rustc_codegen_llvm::back::write::create_informational_target_machine ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#8  0x00007f5502316bff in <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::target_features ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#9  0x00007f5502230ed8 in rustc_interface::util::create_session ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#10 0x00007f55021fede5 in rustc_interface::interface::create_compiler_and_run ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#11 0x00007f55021f7d05 in rustc_span::with_session_globals ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#12 0x00007f55021ff36a in std::sys_common::backtrace::__rust_begin_short_backtrace ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#13 0x00007f550221bc4a in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
   from /home/max/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-7ea116e55de24565.so
#14 0x00007f54ff668c8a in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once ()
    at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
#15 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once ()
    at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521
#16 std::sys::unix::thread::Thread::new::thread_start () at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0//library/std/src/sys/unix/thread.rs:71
#17 0x00007f54ff55b609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#18 0x00007f54ff46f293 in clone () from /lib/x86_64-linux-gnu/libc.so.6```

</p>
</details>

**Comment by jyn514** [comment]
>   rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (signal: 11, SIGSEGV: invalid memory reference)

That doesn't look like it came from the demo project, this is what cargo runs for me:

```
Running `CARGO=/home/joshua/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_BIN_NAME=demo CARGO_CRATE_NAME=demo CARGO_MANIFEST_DIR=/home/joshua/src/rust/test-rustdoc/demo CARGO_PKG_AUTHORS='Joshua Nelson <jyn514@gmail.com>' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=demo CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/home/joshua/src/rust/test-rustdoc/demo/target/debug/deps:/home/joshua/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/joshua/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' rustc --crate-name demo --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a310f5dafc91749b -C extra-filename=-a310f5dafc91749b --out-dir /home/joshua/src/rust/test-rustdoc/demo/target/debug/deps -C incremental=/home/joshua/src/rust/test-rustdoc/demo/target/debug/incremental -L dependency=/home/joshua/src/rust/test-rustdoc/demo/target/debug/deps -C link-arg=-fuse-ld=lld`
```

Can you make sure this happens in a fresh project? If not, can you link the project where it crashes?

**Comment by maxlein** [comment]
I do exactly this:  

```bash
cargo new demo
cd demo
cargo build
```  
Then crash ...

**Comment by ehuss** [comment]
> That doesn't look like it came from the demo project,

@jyn514 That's normal behavior for cargo. That command is usually hidden, and will be cached if it is successful.  It is only displayed if it fails.

**Comment by maxlein** [comment]
No I didn't overclock my system.  
This is just my work notebook with a common dev environment setup. ( clang, g++, vscode )

**Comment by Enselic** [comment]
Triage: Since it works in a docker container it seems likely that the error is within your dev environment somewhere. If you gradually make the docker environment identical to your dev environment you will eventually find the culprit. 

Closing as not reproducible.
