### ISSUE TITLE
ICE: compiler/rustc_symbol_mangling/src/legacy.rs, finding type for DefId(...), encountered def-id DefId(...) with no parent

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#83702]
### Code

```Rust
#![feature(rustc_attrs)]
#[rustc_symbol_name]
use std::ops;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (74874a690 2021-03-30)
binary: rustc
commit-hash: 74874a690bc95443292496ff5df5cc5c8cb56e0b
commit-date: 2021-03-30
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
warning: unused import: `std::ops`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:5
  |
3 | use std::ops;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: internal compiler error: compiler/rustc_symbol_mangling/src/legacy.rs:41:21: finding type for DefId(0:3 ~ perses_node_priority_with_dfs_delta_reduced_mutant[8787]::{misc#1}), encountered def-id DefId(0:0 ~ perses_node_priority_with_dfs_delta_reduced_mutant[8787]) with no parent

thread 'rustc' panicked at 'Box<Any>', /rustc/74874a690bc95443292496ff5df5cc5c8cb56e0b/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (74874a690 2021-03-30) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
#0 [symbol_name] computing the symbol for `{misc#1}`
end of query stack
error: aborting due to previous error; 1 warning emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: unused import: `std::ops`
 --> perses_node_priority_with_dfs_delta_reduced_mutant.rs:3:5
  |
3 | use std::ops;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: internal compiler error: compiler/rustc_symbol_mangling/src/legacy.rs:41:21: finding type for DefId(0:3 ~ perses_node_priority_with_dfs_delta_reduced_mutant[8787]::{misc#1}), encountered def-id DefId(0:0 ~ perses_node_priority_with_dfs_delta_reduced_mutant[8787]) with no parent

thread 'rustc' panicked at 'Box<Any>', /rustc/74874a690bc95443292496ff5df5cc5c8cb56e0b/library/std/src/panic.rs:59:5
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_symbol_mangling::legacy::mangle
   8: rustc_symbol_mangling::symbol_name_provider
   9: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::symbol_name>::compute
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::force_query_with_job
  13: rustc_query_system::query::plumbing::get_query_impl
  14: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::symbol_name
  15: rustc_symbol_mangling::test::SymbolNamesTest::process_attrs
  16: rustc_hir::hir::Crate::visit_all_item_likes
  17: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  18: rustc_symbol_mangling::test::report_symbol_names
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::Queries::ongoing_codegen
  21: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  22: rustc_span::with_source_map
  23: rustc_interface::interface::create_compiler_and_run
  24: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (74874a690 2021-03-30) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
#0 [symbol_name] computing the symbol for `{misc#1}`
end of query stack
error: aborting due to previous error; 1 warning emitted
```

</p>
</details>

**Comment by chengniansun** [comment]
A duplicate

```rust
#![feature(rustc_attrs)]
#[rustc_symbol_name]
use std::io;
```

**Comment by workingjubilee** [comment]
This requires blatant misuse of a rustc-internal attribute and thus will probably not be fixed.
