### ISSUE TITLE
Option::unwrap() on a None value' with wrong import path

### ISSUE THREAD

**Issue by Thoralf-M** [rust-lang/rust#83749]
### Code

In Cargo.toml
`bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }`

Then just add

```Rust
pub enum Error {
    BeeCryptoError(bee_crypto::ternary::sponge::<bee_crypto::ternary::sponge::Kerl as Sponge>::Error),
}
```

### Meta

```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-pc-windows-msvc
release: 1.51.0
LLVM version: 11.0.1
```

### Error output

```
error: expected one of `,` or `>`, found keyword `as`
 --> src\main.rs:6:84
  |
6 |     BeeCryptoError(bee_crypto::ternary::sponge::<bee_crypto::ternary::sponge::Kerl as Sponge>::Error),
  |                                                                                    ^^ expected one of `,` or `>`
  |
help: expressions must be enclosed in braces to be used as const generic arguments
  |
6 |     BeeCryptoError(bee_crypto::ternary::sponge::<{ bee_crypto::ternary::sponge::Kerl as Sponge }>::Error),
  |                                                  ^                                             ^

error[E0412]: cannot find type `Error` in module `bee_crypto::ternary::sponge`
 --> src\main.rs:6:96
  |
6 |     BeeCryptoError(bee_crypto::ternary::sponge::<bee_crypto::ternary::sponge::Kerl as Sponge>::Error),
  |                                                                                                ^^^^^ not found in `bee_crypto::ternary::sponge`
  |
help: consider importing one of these items
  |
1 | use bee_crypto::ternary::bigint::error::Error;
  |
1 | use core::fmt::Error;
  |
1 | use std::error::Error;
  |
1 | use std::fmt::Error;
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_metadata\src\rmeta\decoder.rs:900:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [generics_of] computing generics of `bee_crypto::ternary::sponge`
#1 [opt_const_param_of] computing the optional const parameter of `Error::BeeCryptoError::0::{constant#0}`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_metadata\src\rmeta\decoder.rs:900:54
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [generics_of] computing generics of `bee_crypto::ternary::sponge`
#1 [opt_const_param_of] computing the optional const parameter of `Error::BeeCryptoError::0::{constant#0}`
#2 [typeck] type-checking `Error::BeeCryptoError::0::{constant#0}`
#3 [typeck_item_bodies] type-checking all item bodies
#4 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by Nilstrieb** [comment]
I tried reproducing this with https://github.com/iotaledger/bee/commit/04f456b550a7c7113fa726b6c2e2b8fab6322059 and it passed. Closing as fixed.
