### ISSUE TITLE
Internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by jfsulliv** [rust-lang/rust#84208]
### Code

```Rust
type Example = futures::future::BoxFuture<Output = ()>;
```

e.g.: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cbb80560be88e3d7622942d6d383f79a

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (132b4e5d1 2021-04-13) running on x86_64-unknown-linux-gnu
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:880:62
<backtrace omitted>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (132b4e5d1 2021-04-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [super_predicates_of] computing the super predicates of `futures::future::BoxFuture`
#1 [super_predicates_that_define_assoc_type] computing the super traits of `futures::future::BoxFuture` with associated type name `Output`
#2 [resolve_lifetimes] resolving lifetimes
#3 [named_region_map] looking up a named region
#4 [type_of] computing type of `Example`
#5 [collect_mod_item_types] collecting item types in top-level module
#6 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:880:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/core/src/panicking.rs:50:5
   3: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::super_predicates_of
   4: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::super_predicates_of>::compute
   5: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   6: rustc_data_structures::stack::ensure_sufficient_stack
   7: rustc_query_system::query::plumbing::force_query_with_job
   8: rustc_query_system::query::plumbing::get_query_impl
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::super_predicates_of
  10: rustc_typeck::collect::super_predicates_that_define_assoc_type
  11: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::super_predicates_that_define_assoc_type>::compute
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: rustc_query_system::query::plumbing::force_query_with_job
  15: rustc_query_system::query::plumbing::get_query_impl
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::super_predicates_that_define_assoc_type
  17: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_path
  18: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_ty
  19: rustc_hir::intravisit::walk_item
  20: <rustc_resolve::late::lifetimes::LifetimeContext as rustc_hir::intravisit::Visitor>::visit_item
  21: rustc_resolve::late::lifetimes::do_resolve
  22: rustc_resolve::late::lifetimes::resolve_lifetimes
  23: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::resolve_lifetimes>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::force_query_with_job
  27: rustc_query_system::query::plumbing::get_query_impl
  28: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_lifetimes
  29: rustc_resolve::late::lifetimes::resolve_lifetimes_for
  30: core::ops::function::FnOnce::call_once
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  32: rustc_query_system::query::plumbing::force_query_with_job
  33: rustc_query_system::query::plumbing::get_query_impl
  34: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::named_region_map
  35: rustc_middle::ty::context::TyCtxt::named_region
  36: <dyn rustc_typeck::astconv::AstConv>::ast_region_to_region
  37: <<dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path::SubstsForAstPathCtxt as rustc_typeck::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind
  38: <dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path
  39: <dyn rustc_typeck::astconv::AstConv>::ast_path_substs_for_ty
  40: <dyn rustc_typeck::astconv::AstConv>::ast_path_to_ty
  41: <dyn rustc_typeck::astconv::AstConv>::ast_ty_to_ty_inner
  42: rustc_typeck::collect::type_of::type_of
  43: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  44: rustc_data_structures::stack::ensure_sufficient_stack
  45: rustc_query_system::query::plumbing::force_query_with_job
  46: rustc_query_system::query::plumbing::get_query_impl
  47: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
  48: rustc_typeck::collect::convert_item
  49: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item
  50: rustc_middle::hir::map::Map::visit_item_likes_in_module
  51: rustc_typeck::collect::collect_mod_item_types
  52: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  53: rustc_query_system::query::plumbing::force_query_with_job
  54: rustc_query_system::query::plumbing::get_query_impl
  55: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_mod_item_types
  56: rustc_session::session::Session::track_errors
  57: rustc_typeck::check_crate
  58: rustc_interface::passes::analysis
  59: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  60: rustc_data_structures::stack::ensure_sufficient_stack
  61: rustc_query_system::query::plumbing::force_query_with_job
  62: rustc_query_system::query::plumbing::get_query_impl
  63: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  64: rustc_interface::passes::QueryContext::enter
  65: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  66: rustc_span::with_source_map
  67: rustc_interface::interface::create_compiler_and_run
  68: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by jackh726** [comment]
A variant of #83753. Will check tomorrow if the fix in #83944 covers this case.

**Comment by jackh726** [comment]
This is fixed now. I didn't get a chance to check this before that PR landed. I'm tempted to just close this as a duplicate. Not sure if it's worth another test given that the PR has a test covering this issue.

**Comment by jackh726** [comment]
Closing as duplicate
