### ISSUE TITLE
ICE: called `Result::unwrap()` on an `Err` value: "read_option: expected 0 for None or 1 for Some"

### ISSUE THREAD

**Issue by ZNielsen** [rust-lang/rust#84231]
### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (16bf626a3 2021-04-14)
binary: rustc
commit-hash: 16bf626a31cb5b121d0bca2baa969b4f67eb0dab
commit-date: 2021-04-14
host: armv7-unknown-linux-gnueabihf
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "read_option: expected 0 for None or 1 for Some"', compiler/rustc_metadata/src/rmeta/decoder.rs:231:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (16bf626a3 2021-04-14) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `backtrace`

Caused by:
  process didn't exit successfully: `rustc --crate-name backtrace --edition=2018 /home/pi1/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.56/src/lib.rs --error-for
mat=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="addr2line"' --cfg 'feature="d
efault"' --cfg 'feature="gimli-symbolize"' --cfg 'feature="miniz_oxide"' --cfg 'feature="object"' --cfg 'feature="std"' -C metadata=d73275e8109ed1da -C extra-filename=-d73275e810
9ed1da --out-dir /home/pi1/code/PodRacer/target/debug/deps -L dependency=/home/pi1/code/PodRacer/target/debug/deps --extern addr2line=/home/pi1/code/PodRacer/target/debug/deps/li
baddr2line-27bfd05649fa5edc.rmeta --extern cfg_if=/home/pi1/code/PodRacer/target/debug/deps/libcfg_if-bac9815126dd26ab.rmeta --extern libc=/home/pi1/code/PodRacer/target/debug/de
ps/liblibc-865d787c40f6f9e1.rmeta --extern miniz_oxide=/home/pi1/code/PodRacer/target/debug/deps/libminiz_oxide-e2cb559dbd9224f3.rmeta --extern object=/home/pi1/code/PodRacer/tar
get/debug/deps/libobject-a8d5d5218f1e2317.rmeta --extern rustc_demangle=/home/pi1/code/PodRacer/target/debug/deps/librustc_demangle-3c4074d920228f05.rmeta --cap-lints allow` (exi
t status: 101)
warning: build failed, waiting for other jobs to finish...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Compiling backtrace v0.3.56
     Running `rustc --crate-name backtrace --edition=2018 /home/pi1/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.56/src/lib.rs --error-format=json --json=diagnos
tic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="addr2line"' --cfg 'feature="default"' --cfg 'feature
="gimli-symbolize"' --cfg 'feature="miniz_oxide"' --cfg 'feature="object"' --cfg 'feature="std"' -C metadata=d73275e8109ed1da -C extra-filename=-d73275e8109ed1da --out-dir /home/
pi1/code/PodRacer/target/debug/deps -L dependency=/home/pi1/code/PodRacer/target/debug/deps --extern addr2line=/home/pi1/code/PodRacer/target/debug/deps/libaddr2line-27bfd05649fa
5edc.rmeta --extern cfg_if=/home/pi1/code/PodRacer/target/debug/deps/libcfg_if-bac9815126dd26ab.rmeta --extern libc=/home/pi1/code/PodRacer/target/debug/deps/liblibc-865d787c40f6
f9e1.rmeta --extern miniz_oxide=/home/pi1/code/PodRacer/target/debug/deps/libminiz_oxide-e2cb559dbd9224f3.rmeta --extern object=/home/pi1/code/PodRacer/target/debug/deps/libobjec
t-a8d5d5218f1e2317.rmeta --extern rustc_demangle=/home/pi1/code/PodRacer/target/debug/deps/librustc_demangle-3c4074d920228f05.rmeta --cap-lints allow`
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "read_option: expected 0 for None or 1 for Some"', compiler/rustc_metadata/src/rmeta/decoder.rs:231:29
stack backtrace:
   0: 0x70c0b1f8 - std::backtrace_rs::backtrace::libunwind::trace::h20ca6d4fe5a6ff1e
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1: 0x70c0b1f8 - std::backtrace_rs::backtrace::trace_unsynchronized::h1565fe12d85c7f61
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0x70c0b1f8 - std::sys_common::backtrace::_print_fmt::h815e49a4212124f6
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/sys_common/backtrace.rs:67:5
   3: 0x70c0b1f8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdccba4431eb48e07
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/sys_common/backtrace.rs:46:22
   4: 0x70c86b48 - core::fmt::write::h65f45ea6dd932e37
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/fmt/mod.rs:1094:17
   5: 0x70bff0e4 - std::io::Write::write_fmt::h3f10ca4fef4d6cab
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/io/mod.rs:1580:15
   6: 0x70c0f050 - std::sys_common::backtrace::_print::hf20c82a2782c103d
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/sys_common/backtrace.rs:49:5
   7: 0x70c0f050 - std::sys_common::backtrace::print::h695ad96c50412e30
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/sys_common/backtrace.rs:36:9
   8: 0x70c0f050 - std::panicking::default_hook::{{closure}}::h049f1fd76127d8f7
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:208:50
   9: 0x70c0ea3c - std::panicking::default_hook::h20986d84e0e1e97d
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:225:9
  10: 0x71384428 - rustc_driver::report_ice::hb9532f74fa0e880d
  11: 0x70c0f824 - std::panicking::rust_panic_with_hook::hde3743e8a72e5b21
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:595:17
  12: 0x70c0f3c8 - std::panicking::begin_panic_handler::{{closure}}::h62a43f778df3e38e
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:497:13
  13: 0x70c0b788 - std::sys_common::backtrace::__rust_end_short_backtrace::had9ab5179cc1fa2c
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/sys_common/backtrace.rs:141:18
  14: 0x70c0f310 - rust_begin_unwind
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
  15: 0x70bdcfc0 - core::panicking::panic_fmt::h43ff2feb76285b83
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
  16: 0x70bdd094 - core::result::unwrap_failed::h0d932f19f0ef290e
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/result.rs:1355:5
17: 0x747311f4 - rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::def_key::h44c88a6f58c8f44a
  18: 0x74724694 - rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc_metadata::creader::CStore>::item_children_untracked::h117f9705ec3a4b86
  19: 0x7389b844 - rustc_resolve::Resolver::resolutions::he07bedd3cf28d32a
  20: 0x7389babc - rustc_resolve::Resolver::resolution::h4d8f1dbcdef76aa1
  21: 0x738869b4 - rustc_resolve::imports::<impl rustc_resolve::Resolver>::resolve_ident_in_module_unadjusted_ext::hf9ea9aacccba55f7
  22: 0x738a0a20 - rustc_resolve::Resolver::resolve_path_with_ribs::{{closure}}::hc90020a3b28b16d6
  23: 0x7389e464 - rustc_resolve::Resolver::resolve_path_with_ribs::he0f6e83da1fb9d83
  24: 0x739042d8 - rustc_resolve::imports::ImportResolver::resolve_imports::h7619f2c387326e7d
  25: 0x7388aed4 - rustc_resolve::macros::<impl rustc_expand::base::ResolverExpand for rustc_resolve::Resolver>::resolve_imports::h127fa06e92b1f0dc
  26: 0x748cce10 - rustc_expand::expand::MacroExpander::fully_expand_fragment::h89d1e55c30cd4111
  27: 0x748ca0f4 - rustc_expand::expand::MacroExpander::expand_crate::h47f77a08249bfc72
  28: 0x714c53f4 - rustc_session::utils::<impl rustc_session::session::Session>::time::h33e4644e53065cca
  29: 0x714b476c - rustc_interface::passes::configure_and_expand_inner::h53464a81837ea54b
  30: 0x714abe4c - rustc_interface::passes::configure_and_expand::{{closure}}::h9e5ae767d9f0b7fb
  31: 0x7149abb8 - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::h2e14c27f7832dd9d
  32: 0x714b3bc0 - rustc_interface::passes::configure_and_expand::h90f48d509f1bc790
  33: 0x714d0428 - rustc_interface::queries::Queries::expansion::h4601ba85500da8b7
  34: 0x7138e3a0 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h353bb3fb6d681681
  35: 0x713862a0 - rustc_span::with_source_map::ha7fcf856cadcf5e7
  36: 0x71390494 - rustc_interface::interface::create_compiler_and_run::hff8bb603a185aa90
  37: 0x713b05d0 - scoped_tls::ScopedKey<T>::set::h5043a9a1ce03501b
  38: 0x713b2a50 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0fca6c9917971b07
  39: 0x713be754 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbdadf28f3adaa7b2
  40: 0x70c1dd2c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hffa79756d345fc92
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
  41: 0x70c1dd2c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd662c5647d541486
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
  42: 0x70c1dd2c - std::sys::unix::thread::Thread::new::thread_start::he040c0b2b7fd672b
                       at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/sys/unix/thread.rs:71:17

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (16bf626a3 2021-04-14) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `backtrace`

Caused by:
  process didn't exit successfully: `rustc --crate-name backtrace --edition=2018 /home/pi1/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.56/src/lib.rs --error-for
mat=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="addr2line"' --cfg 'feature="d
efault"' --cfg 'feature="gimli-symbolize"' --cfg 'feature="miniz_oxide"' --cfg 'feature="object"' --cfg 'feature="std"' -C metadata=d73275e8109ed1da -C extra-filename=-d73275e810
9ed1da --out-dir /home/pi1/code/PodRacer/target/debug/deps -L dependency=/home/pi1/code/PodRacer/target/debug/deps --extern addr2line=/home/pi1/code/PodRacer/target/debug/deps/li
baddr2line-27bfd05649fa5edc.rmeta --extern cfg_if=/home/pi1/code/PodRacer/target/debug/deps/libcfg_if-bac9815126dd26ab.rmeta --extern libc=/home/pi1/code/PodRacer/target/debug/de
ps/liblibc-865d787c40f6f9e1.rmeta --extern miniz_oxide=/home/pi1/code/PodRacer/target/debug/deps/libminiz_oxide-e2cb559dbd9224f3.rmeta --extern object=/home/pi1/code/PodRacer/tar
get/debug/deps/libobject-a8d5d5218f1e2317.rmeta --extern rustc_demangle=/home/pi1/code/PodRacer/target/debug/deps/librustc_demangle-3c4074d920228f05.rmeta --cap-lints allow` (exi
t status: 101)
```

</p>
</details>

**Comment by jonas-schievink** [comment]
Is this reproducible? If not then this might just be data corruption

**Comment by Enselic** [comment]
Triage: Without a way for others to reproduce the ICE, not much can be done at this point. Closing.
