### ISSUE TITLE
pointer calculation error

### ISSUE THREAD

**Issue by dvmason** [rust-lang/rust#84247]
I am building an interpreter and I have objects in a heap that I'll be managing, separate from the Rust heap.

Each object has a header followed by 0 or more fields. I think the `raw_at_put` code is the correct calculation. But there is an off-by-one error, and in fact the `alt_at_put` code produces the correct result. This code is simplified from my actual code, but exhibits the same error. In my actual code I have allocated several objects, and if I use the `alt_at_put` code, it works perfectly.

There may be a better way to do what I'm looking for (and I'd be happy to hear about it), but regardless, I think this is a bug.

I tried this code:

```rust
#![allow(warnings)] 
type Header = usize;
type Object = i64;
pub struct HeapObject {
    header : Header,
    fields : [Object;0], // typically many more than 1, but will be accessed as unsafe
}
impl HeapObject {
    pub fn raw_at_put(&mut self,index:usize,value:Object) {
        let fields : * mut Object = &mut self.fields as * mut Object;
        unsafe{fields.offset(index as isize).write(value)}
    }
    pub fn alt_at_put(&mut self,index:usize,value:Object) {
        let fields : * mut Object = &mut self.fields as * mut Object;
        unsafe{fields.offset(index as isize+1).write(value)} // why is this off by 1?
    }
    pub fn initialize(&mut self,n_instVars:usize) -> * mut HeapObject {
        self.header=n_instVars as Header;
        let words = n_instVars as isize+1; // this +1 is for the header (assumes sizeof<Object> == sizeof<Header>)
        unsafe{(self as *mut HeapObject).offset(words)}
    }
}
#[cfg(test)]
mod testHeapObject {
    use super::*;
    #[test]
    fn correct() {
        let mut mem = [0_usize;100];
        let next : * mut HeapObject = &mut mem as * const usize as * mut HeapObject;
        let obj = unsafe { next.as_mut().unwrap() };
        let mut next = obj.initialize(3);
        obj.raw_at_put(0,42);
        obj.raw_at_put(1,1);
        obj.raw_at_put(2,2);
        let obj = unsafe { next.as_mut().unwrap() };
        let _ = obj.initialize(4);
        assert_eq!(mem[4],4);
        assert_eq!(mem[0],3);
        assert_eq!(mem[1],42);
        assert_eq!(mem[2],1);
        assert_eq!(mem[3],2);
    }
    #[test]
    fn wrong() {
        let mut mem = [0_usize;100];
        let next : * mut HeapObject = &mut mem as * const usize as * mut HeapObject;
        let obj = unsafe { next.as_mut().unwrap() };
        let mut next = obj.initialize(3);
        obj.alt_at_put(0,42);
        obj.alt_at_put(1,1);
        obj.alt_at_put(2,2);
        let obj = unsafe { next.as_mut().unwrap() };
        let _ = obj.initialize(4);
        assert_eq!(mem[4],4);
        assert_eq!(mem[0],3);
        assert_eq!(mem[1],42);
        assert_eq!(mem[2],1);
        assert_eq!(mem[3],2);
    }
}
```

I expected to see the correct test pass and the wrong test fail

Instead, this it was the reverse!!

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (8f349be27 2021-03-08)
binary: rustc
commit-hash: 8f349be27815d43d462a32faeb270a22a68486b6
commit-date: 2021-03-08
host: x86_64-apple-darwin
release: 1.52.0-nightly
LLVM version: 12.0.0
```

<details><summary>Backtrace</summary>
<p>

```
    Finished test [unoptimized + debuginfo] target(s) in 0.18s
     Running unittests (target/debug/deps/bug-48cbeea253982f41)

running 2 tests
test testHeapObject::wrong ... ok
test testHeapObject::correct ... FAILED

failures:

- testHeapObject::correct stdout ----
thread 'testHeapObject::correct' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `3`', src/main.rs:38:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/panicking.rs:160:17
   3: core::panicking::assert_failed
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/panicking.rs:117:5
   4: bug::testHeapObject::correct
             at ./src/main.rs:38:9
   5: bug::testHeapObject::correct::{{closure}}
             at ./src/main.rs:27:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8f349be27815d43d462a32faeb270a22a68486b6/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    testHeapObject::correct

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass '--bin bug'
```

</p>
</details>

**Comment by SNCPlay42** [comment]
Your `HeapObject` is not `#[repr(C)]`, so the compiler is allowed to place its fields in an arbitrary order. It appears `fields` is being placed *before* `header` in memory.

**Comment by dvmason** [comment]
Doh!

Yup, that fixed it. It's not surprising that it would put a 0-length field first!

Sorry.
