### ISSUE TITLE
unstable fingerprints on rust-analyzer on 1.52.beta3

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#84335]
Have seen these a couple of times today when running `cargo xtask install --mimalloc` (incremental realase build) in rust-analyzer repo

### Code

https://github.com/rust-analyzer/rust-analyzer/tree/e7a8977358c108164d3ba39aede67119baa5aaf9

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-beta.3 (215738137 2021-04-06)
binary: rustc
commit-hash: 215738137bcbef2c3637a5bd290ef612cffe6ba5
commit-date: 2021-04-06
host: x86_64-unknown-linux-gnu
release: 1.52.0-beta.3
LLVM version: 12.0.0
```

### Error output

<details>
<summary>Specimen 1</summary>

```
thread 'rustc' panicked at 'found unstable fingerprints for evaluate_obligation(9d8b05d87bf321ac-181c48f3b61fefcc): Ok(EvaluatedToOk)', /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-beta.3 (215738137 2021-04-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C linker=/run/current-system/sw/bin/clang -C incremental -C link-arg=-fuse-ld=lld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `chalk_ir::BindersIntoIterator<&std::vec::Vec<chalk_ir::Binders<chalk_ir::WhereClause<interner::Interner>>>>: std::marker::Sized`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [std::iter::Map<chalk_ir::BindersIntoIterator<&std::vec::Vec<chalk_ir::Binders<chalk_ir::WhereClause<interner::Interner>>>>, [closure@<chalk_solve::rust_ir::AssociatedTyValue<interner::Interner> as chalk_solve::clauses::program_clauses::ToProgramClauses<interner::Interner>>::to_program_clauses::{closure#0}::{closure#3}]>], item_def_id: DefId(2:6993 ~ core[8a07]::iter::traits::collect::IntoIterator::IntoIter) } } }`
end of query stack
error: could not compile `hir_ty`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'found unstable fingerprints for evaluate_obligation(5bda6a3b2a36606f-5ba2f326f85b10cb): Ok(EvaluatedToOk)', /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-beta.3 (215738137 2021-04-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C linker=/run/current-system/sw/bin/clang -C incremental -C link-arg=-fuse-ld=lld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `RootDatabase: base_db::Upcast<dyn hir::db::AstDatabase>`
#1 [typeck] type-checking `symbol_index::crate_symbols`
end of query stack
error: failed to compile `rust-analyzer v0.0.0 (/home/matklad/projects/rust-analyzer/crates/rust-analyzer)`, intermediate artifacts can be found at `/home/matklad/projects/rust-analyzer/target`

Caused by:
  build failed
Error: install server

Caused by:
    command `cargo install --path crates/rust-analyzer --locked --force --features force-always-assert --features mimalloc` failed, exit code: 101
```
</details>

<details>
<summary>Specimen 2</summary>

```
thread 'rustc' panicked at 'found unstable fingerprints for item_children(profile[5124]): [Export { ident: stop_watch#0, res: Def(Mod, DefId(23:3 ~ profile[5124]::stop_watch)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:3:1: 3:16 (#0), vis: Restricted(DefId(23:0 ~ profile[5124])) }, Export { ident: memory_usage#0, res: Def(Mod, DefId(23:36 ~ profile[5124]::memory_usage)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:4:1: 4:18 (#0), vis: Restricted(DefId(23:0 ~ profile[5124])) }, Export { ident: hprof#0, res: Def(Mod, DefId(23:59 ~ profile[5124]::hprof)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:7:1: 7:11 (#0), vis: Restricted(DefId(23:0 ~ profile[5124])) }, Export { ident: tree#0, res: Def(Mod, DefId(23:164 ~ profile[5124]::tree)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:8:1: 8:10 (#0), vis: Restricted(DefId(23:0 ~ profile[5124])) }, Export { ident: IN_SCOPE#0, res: Def(Const, DefId(23:315 ~ profile[5124]::IN_SCOPE)), span: /home/matklad/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:192:22: 193:59 (#7), vis: Restricted(DefId(23:0 ~ profile[5124])) }, Export { ident: Scope#0, res: Def(Struct, DefId(23:245 ~ profile[5124]::Scope)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:29:1: 31:2 (#0), vis: Public }, Export { ident: CpuSpan#0, res: Def(Struct, DefId(23:319 ~ profile[5124]::CpuSpan)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:80:1: 82:2 (#0), vis: Public }, Export { ident: cpu_span#0, res: Def(Fn, DefId(23:255 ~ profile[5124]::cpu_span)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:85:1: 85:29 (#0), vis: Public }, Export { ident: memory_usage#0, res: Def(Fn, DefId(23:258 ~ profile[5124]::memory_usage)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:126:1: 126:37 (#0), vis: Public }, Export { ident: RefCell#0, res: Def(Struct, DefId(2:3979 ~ core[8a07]::cell::RefCell)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:10:5: 10:23 (#0), vis: Restricted(DefId(23:0 ~ profile[5124])) }, Export { ident: heartbeat#0, res: Def(Fn, DefId(23:115 ~ profile[5124]::hprof::heartbeat)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:13:13: 13:22 (#0), vis: Public }, Export { ident: heartbeat_span#0, res: Def(Fn, DefId(23:114 ~ profile[5124]::hprof::heartbeat_span)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:13:24: 13:38 (#0), vis: Public }, Export { ident: init#0, res: Def(Fn, DefId(23:109 ~ profile[5124]::hprof::init)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:13:40: 13:44 (#0), vis: Public }, Export { ident: init_from#0, res: Def(Fn, DefId(23:110 ~ profile[5124]::hprof::init_from)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:13:46: 13:55 (#0), vis: Public }, Export { ident: span#0, res: Def(Fn, DefId(23:112 ~ profile[5124]::hprof::span)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:13:57: 13:61 (#0), vis: Public }, Export { ident: Bytes#0, res: Def(Struct, DefId(23:264 ~ profile[5124]::memory_usage::Bytes)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:14:20: 14:25 (#0), vis: Public }, Export { ident: MemoryUsage#0, res: Def(Struct, DefId(23:259 ~ profile[5124]::memory_usage::MemoryUsage)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:14:27: 14:38 (#0), vis: Public }, Export { ident: StopWatch#0, res: Def(Struct, DefId(23:18 ~ profile[5124]::stop_watch::StopWatch)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:15:18: 15:27 (#0), vis: Public }, Export { ident: StopWatchSpan#0, res: Def(Struct, DefId(23:22 ~ profile[5124]::stop_watch::StopWatchSpan)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:15:29: 15:42 (#0), vis: Public }, Export { ident: countme#0, res: Def(Mod, DefId(26:0 ~ countme[8e9d])), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:18:9: 18:16 (#0), vis: Public }, Export { ident: Count#0, res: Def(Struct, DefId(26:116 ~ countme[8e9d]::Count)), span: /home/matklad/tmp/repro/crates/profile/src/lib.rs:23:9: 23:23 (#0), vis: Public }]', /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/compiler/rustc_query_system/src/query/plumbing.rs:593:5
stack backtrace:
   0:     0x7f6ac6623b00 - std::backtrace_rs::backtrace::libunwind::trace::hc65bb72b4a549d12
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f6ac6623b00 - std::backtrace_rs::backtrace::trace_unsynchronized::h6e6089972b3c123e
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6ac6623b00 - std::sys_common::backtrace::_print_fmt::h6a259ed64281b14e
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f6ac6623b00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hada463cae5e69c09
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f6ac669222f - core::fmt::write::hd526fa92c7915d40
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1092:17
   5:     0x7f6ac6617c12 - std::io::Write::write_fmt::h6bc7fe34c0e5e633
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/io/mod.rs:1572:15
   6:     0x7f6ac6627835 - std::sys_common::backtrace::_print::h2485fe440d733b74
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f6ac6627835 - std::sys_common::backtrace::print::hfe9bf64cf6d5131b
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f6ac6627835 - std::panicking::default_hook::{{closure}}::h9da41c6d765e6d84
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:208:50
   9:     0x7f6ac66272e3 - std::panicking::default_hook::h12592fd0ecea94ff
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:225:9
  10:     0x7f6ac6e3615b - rustc_driver::report_ice::h14075d822d976f42
  11:     0x7f6ac6627fa0 - std::panicking::rust_panic_with_hook::h48e31a52a6a5e11f
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:595:17
  12:     0x7f6ac6627b17 - std::panicking::begin_panic_handler::{{closure}}::h74f000b3d866b063
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:497:13
  13:     0x7f6ac6623fbc - std::sys_common::backtrace::__rust_end_short_backtrace::h1dcb6d2a32dff0c7
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f6ac6627a79 - rust_begin_unwind
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:493:5
  15:     0x7f6ac65ec23b - std::panicking::begin_panic_fmt::h1063ff74a06df2ee
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:435:5
  16:     0x7f6ac739d5b1 - rustc_query_system::query::plumbing::incremental_verify_ich::h7b46b71e55b606e9
  17:     0x7f6ac73bf2f8 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h81cafe23465fef37
  18:     0x7f6ac8f74597 - rustc_data_structures::stack::ensure_sufficient_stack::h4f9e934914800f92
  19:     0x7f6ac83876e3 - rustc_query_system::query::plumbing::get_query_impl::h697e6775b8074851
  20:     0x7f6ac83f5e5a - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::item_children::h0394edf0db6752ac
  21:     0x7f6ac7ed2f14 - rustc_middle::ty::print::pretty::trimmed_def_paths::h0a26266d616c33d5
  22:     0x7f6ac73cf936 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::trimmed_def_paths>::compute::hf6b652ac28d0ff8e
  23:     0x7f6ac75ecd5c - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::ha85a97550b6b0bac
  24:     0x7f6ac7547685 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hb99f09c7b5a41f39
  25:     0x7f6ac754ee4b - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h91b8bf9dc8dd1db3
  26:     0x7f6ac760360a - rustc_data_structures::stack::ensure_sufficient_stack::h32ccfc7885dba4f4
  27:     0x7f6ac7388aae - rustc_query_system::query::plumbing::force_query_with_job::hbac0dec5da3af5d9
  28:     0x7f6ac7350da2 - rustc_query_system::query::plumbing::get_query_impl::ha3a25ad98dce2e70
  29:     0x7f6ac73c8bd1 - rustc_query_system::query::plumbing::get_query::h96df1ab11cedb508
  30:     0x7f6ac89e076e - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::h3bb922496dadfb41
  31:     0x7f6ac7ecac8b - rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_const::hdc5b4b9b125938a0
  32:     0x7f6ac7e1d8df - rustc_middle::mir::pretty_print_const::hf612b360f9fe865e
  33:     0x7f6ac669222f - core::fmt::write::hd526fa92c7915d40
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1092:17
  34:     0x7f6ac6693404 - core::fmt::Formatter::write_fmt::h065f17fef40bc6c2
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1535:9
  35:     0x7f6ac7e1d671 - <rustc_middle::mir::Constant as core::fmt::Debug>::fmt::hc666bd8336adbc99
  36:     0x7f6ac669222f - core::fmt::write::hd526fa92c7915d40
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1092:17
  37:     0x7f6ac6693404 - core::fmt::Formatter::write_fmt::h065f17fef40bc6c2
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1535:9
  38:     0x7f6ac7e1bc49 - <rustc_middle::mir::Operand as core::fmt::Debug>::fmt::h4455d289c6de8587
  39:     0x7f6ac669222f - core::fmt::write::hd526fa92c7915d40
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1092:17
  40:     0x7f6ac6693404 - core::fmt::Formatter::write_fmt::h065f17fef40bc6c2
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1535:9
  41:     0x7f6ac7e1c452 - <rustc_middle::mir::Rvalue as core::fmt::Debug>::fmt::h9a5d6d13bf8c97ff
  42:     0x7f6ac669222f - core::fmt::write::hd526fa92c7915d40
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1092:17
  43:     0x7f6ac6693404 - core::fmt::Formatter::write_fmt::h065f17fef40bc6c2
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1535:9
  44:     0x7f6ac7e1b465 - <rustc_middle::mir::Statement as core::fmt::Debug>::fmt::ha7853a05661ad777
  45:     0x7f6ac668f09a - core::fmt::builders::DebugInner::entry::{{closure}}::h48f301b78689925a
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:417:17
  46:     0x7f6ac668f09a - core::result::Result<T,E>::and_then::ha138ac621db2bd1e
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/result.rs:704:22
  47:     0x7f6ac668f09a - core::fmt::builders::DebugInner::entry::h7bfe5b8dcccf238e
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:403:23
  48:     0x7f6ac668f169 - core::fmt::builders::DebugSet::entry::ha731768ebd0e8466
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:492:9
  49:     0x7f6ac7e5cc2b - core::fmt::builders::DebugList::entries::hb82f62076260069d
  50:     0x7f6ac7e153c2 - <[T] as core::fmt::Debug>::fmt::h356df4a098be9b87
  51:     0x7f6ac668ec4e - core::fmt::builders::DebugStruct::field::{{closure}}::h593a8be22597e88b
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:154:17
  52:     0x7f6ac668ec4e - core::result::Result<T,E>::and_then::h7bb0007399fd060f
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/result.rs:704:22
  53:     0x7f6ac668ec4e - core::fmt::builders::DebugStruct::field::h569d908b4e5aeafe
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:137:23
  54:     0x7f6ac7e224a8 - <rustc_middle::mir::BasicBlockData as core::fmt::Debug>::fmt::h181aca1273770af1
  55:     0x7f6ac668f09a - core::fmt::builders::DebugInner::entry::{{closure}}::h48f301b78689925a
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:417:17
  56:     0x7f6ac668f09a - core::result::Result<T,E>::and_then::ha138ac621db2bd1e
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/result.rs:704:22
  57:     0x7f6ac668f09a - core::fmt::builders::DebugInner::entry::h7bfe5b8dcccf238e
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:403:23
  58:     0x7f6ac668f169 - core::fmt::builders::DebugSet::entry::ha731768ebd0e8466
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:492:9
  59:     0x7f6ac7e5cade - core::fmt::builders::DebugList::entries::hacba6a3f0572b851
  60:     0x7f6ac7e15415 - <[T] as core::fmt::Debug>::fmt::h3a8e40bdd014308f
  61:     0x7f6ac668ec4e - core::fmt::builders::DebugStruct::field::{{closure}}::h593a8be22597e88b
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:154:17
  62:     0x7f6ac668ec4e - core::result::Result<T,E>::and_then::h7bb0007399fd060f
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/result.rs:704:22
  63:     0x7f6ac668ec4e - core::fmt::builders::DebugStruct::field::h569d908b4e5aeafe
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/builders.rs:137:23
  64:     0x7f6ac7e238fd - <rustc_middle::mir::Body as core::fmt::Debug>::fmt::h98a07214599caf7b
  65:     0x7f6ac669222f - core::fmt::write::hd526fa92c7915d40
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:1092:17
  66:     0x7f6ac6627cc8 - core::fmt::Write::write_fmt::hc519dc9a3ff8b137
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/fmt/mod.rs:182:9
  67:     0x7f6ac6627cc8 - std::panicking::begin_panic_handler::PanicPayload::fill::{{closure}}::h386d169ce17edab4
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:459:22
  68:     0x7f6ac6627cc8 - core::option::Option<T>::get_or_insert_with::h3e368fff70624ade
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/core/src/option.rs:929:26
  69:     0x7f6ac6627cc8 - std::panicking::begin_panic_handler::PanicPayload::fill::h695b2a76c1ce7ecc
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:457:13
  70:     0x7f6ac6627cc8 - <std::panicking::begin_panic_handler::PanicPayload as core::panic::BoxMeUp>::get::h7db7688fd72424b7
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:475:13
  71:     0x7f6ac6627f8d - std::panicking::rust_panic_with_hook::h48e31a52a6a5e11f
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:594:34
  72:     0x7f6ac6627b17 - std::panicking::begin_panic_handler::{{closure}}::h74f000b3d866b063
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:497:13
  73:     0x7f6ac6623fbc - std::sys_common::backtrace::__rust_end_short_backtrace::h1dcb6d2a32dff0c7
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys_common/backtrace.rs:141:18
  74:     0x7f6ac6627a79 - rust_begin_unwind
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:493:5
  75:     0x7f6ac65ec23b - std::panicking::begin_panic_fmt::h1063ff74a06df2ee
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/panicking.rs:435:5
  76:     0x7f6ac73a6b51 - rustc_query_system::query::plumbing::incremental_verify_ich::hbf34849ebaa84bb6
  77:     0x7f6ac8e7876a - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h340a3c0ce053d18c
  78:     0x7f6ac8f8213f - rustc_data_structures::stack::ensure_sufficient_stack::he9adc7dd892d4a5c
  79:     0x7f6ac838dcc0 - rustc_query_system::query::plumbing::get_query_impl::h7e76b949d89870f5
  80:     0x7f6ac83f377a - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::optimized_mir::h401a3d53e7dcbee1
  81:     0x7f6ac899141c - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir::h5f0db09bbe075026
  82:     0x7f6ac8592bf5 - rustc_mir::monomorphize::collector::collect_neighbours::h45efddbd88316496
  83:     0x7f6ac858d1a2 - rustc_mir::monomorphize::collector::collect_items_rec::hcf385ce49b0dac54
  84:     0x7f6ac858d29a - rustc_mir::monomorphize::collector::collect_items_rec::hcf385ce49b0dac54
  85:     0x7f6ac858d29a - rustc_mir::monomorphize::collector::collect_items_rec::hcf385ce49b0dac54
  86:     0x7f6ac9052ab5 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h5e938d33c32d217f
  87:     0x7f6ac86bd48f - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h03845bf13a114fb9
  88:     0x7f6ac8e88536 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::collect_and_partition_mono_items>::compute::hed2913f26e88b55b
  89:     0x7f6ac75eb932 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h9b46ee972b1b8012
  90:     0x7f6ac8f1fba9 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h9c8ca348ba0add32
  91:     0x7f6ac8f71059 - rustc_data_structures::stack::ensure_sufficient_stack::h28783f2fa69f9d12
  92:     0x7f6ac8e48076 - rustc_query_system::query::plumbing::force_query_with_job::h52821edff849046d
  93:     0x7f6ac8df1cd5 - rustc_query_system::query::plumbing::get_query_impl::h089045c262cfe9d5
  94:     0x7f6ac8efff38 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items::h7771003db9eeff21
  95:     0x7f6ac8b18e40 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h1e56384b76669d7e
  96:     0x7f6ac8a9faf1 - rustc_interface::passes::QueryContext::enter::h79609ad161979a7f
  97:     0x7f6ac8aa8546 - rustc_interface::queries::Queries::ongoing_codegen::hb65b58f1b98d1b19
  98:     0x7f6ac8a65f36 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h60cfe93b7b0e1e5f
  99:     0x7f6ac8a60521 - rustc_span::with_source_map::hd8e0dcfd833db880
 100:     0x7f6ac8a66ede - rustc_interface::interface::create_compiler_and_run::h016141feddeec777
 101:     0x7f6ac8a613d8 - scoped_tls::ScopedKey<T>::set::h251cc53c4edaefe8
 102:     0x7f6ac8a67294 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8e422294f8c54ce3
 103:     0x7f6ac8a7e8f5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9d09c7ff9f326ef9
 104:     0x7f6ac66378e8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h36b08298aa835de6
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/alloc/src/boxed.rs:1546:9
 105:     0x7f6ac66378e8 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39c1de95e16a780f
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/alloc/src/boxed.rs:1546:9
 106:     0x7f6ac66378e8 - std::sys::unix::thread::Thread::new::thread_start::ha33b608c43829834
                               at /rustc/215738137bcbef2c3637a5bd290ef612cffe6ba5/library/std/src/sys/unix/thread.rs:71:17
 107:     0x7f6ac6570e9e - start_thread
 108:     0x7f6ac649049f - __GI___clone
 109:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-beta.3 (215738137 2021-04-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C linker=/run/current-system/sw/bin/clang -C incremental -C link-arg=-fuse-ld=lld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
error: could not compile `test_utils`

Caused by:
  process didn't exit successfully: `rustc --crate-name test_utils --edition=2018 crates/test_utils/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=841701a26642e6d0 -C extra-filename=-841701a26642e6d0 --out-dir /home/matklad/tmp/repro/target/release/deps -C linker=/run/current-system/sw/bin/clang -C incremental=/home/matklad/tmp/repro/target/release/incremental -L dependency=/home/matklad/tmp/repro/target/release/deps --extern dissimilar=/home/matklad/tmp/repro/target/release/deps/libdissimilar-eec14215b5274a1f.rmeta --extern profile=/home/matklad/tmp/repro/target/release/deps/libprofile-a7f190270a9f9869.rmeta --extern rustc_hash=/home/matklad/tmp/repro/target/release/deps/librustc_hash-91540ab907838161.rmeta --extern stdx=/home/matklad/tmp/repro/target/release/deps/libstdx-b6bdb47ec8150b80.rmeta --extern text_size=/home/matklad/tmp/repro/target/release/deps/libtext_size-958ac5d61f4e85e9.rmeta -Clink-arg=-fuse-ld=lld` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rust-analyzer v0.0.0 (/home/matklad/tmp/repro/crates/rust-analyzer)`, intermediate artifacts can be found at `/home/matklad/tmp/repro/target`

Caused by:
  build failed
Error: install server

Caused by:
    command `cargo install --path crates/rust-analyzer --locked --force --features force-always-assert --features mimalloc` failed, exit code: 101

```
</details>

**Comment by bjorn3** [comment]
The first crash is a duplicate of https://github.com/rust-lang/rust/issues/83538 I think. The second one doesn't seem to be a duplicate though.

**Comment by matklad** [comment]
The second one was me re-running command with the same target directory

**Comment by wesleywiser** [comment]
Thanks for filing the bug report! We just shipped a [patch release to work around this issue](https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html) and are currently triaging related issues related to ensure each underlying problem gets resolved. Since this appears to be a duplicate of #85019 and #83538, I'm going to close in favor of those issues.
