### ISSUE TITLE
Panic while compiling generic struct that wraps a closure, on borrow checking analysis.

### ISSUE THREAD

**Issue by jdfreder** [rust-lang/rust#84567]
Hi, 

I'm new to Rust and I've managed to blow something up - sorry! Otherwise I've been having a lot of fun learning the language :-) While I'm here reporting this panic, would someone mind clarifying to me what is the most idiomatic way to accept a closure of any type (FnOnce, Fn, and FnMut). I read somewhere that FnOnce was sort of the trait that all of the closures would implement regardless - does that mean I can use that alone to accept any closure (assuming the `mut` and `&` matches)?

My attempt caused a rustc panic, as seen below:

### Code

```Rust
struct Callback<'a, T> {
    callback: &'a mut dyn FnOnce() -> T,
}

impl<'a, T> Callback<'a, T> {
    pub fn new(callback: &'a mut dyn FnOnce() -> T) -> Callback<'a, T> {
        Callback { callback }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn can_wrap_fnonce() {
        let x = 0;
        let fn_once = || x;
        let callback = Callback::new(&mut fn_once);
    }
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-pc-windows-msvc
release: 1.51.0
LLVM version: 11.0.1
```

### Error output

```
thread 'rustc' panicked at 'LocalTableInContext: key not found', compiler\rustc_mir\src\borrow_check\diagnostics\mutability_errors.rs:512:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `graph::callback::tests::can_wrap_fnonce`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 4 warnings emitted

error: could not compile `game-renderer`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'LocalTableInContext: key not found', compiler\rustc_mir\src\borrow_check\diagnostics\mutability_errors.rs:512:30
stack backtrace:
   0:     0x7ff93b8b896e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0be32b274330c008
   1:     0x7ff93b8e47cb - core::fmt::write::h1aaaeb17cc45ab1e
   2:     0x7ff93b8abe68 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h4953295bcdf7c8c4
   3:     0x7ff93b8bcb3d - std::panicking::take_hook::h407a4a30481be788
   4:     0x7ff93b8bc609 - std::panicking::take_hook::h407a4a30481be788
   5:     0x7ff93be4e0b5 - rustc_driver::report_ice::h95f5b27be13b72ff
   6:     0x7ff93b8bd5a2 - std::panicking::rust_panic_with_hook::h0389acbd2be8eae9
   7:     0x7ff93b8bd091 - rust_begin_unwind
   8:     0x7ff93b8b92ff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0be32b274330c008
   9:     0x7ff93b8bcfe9 - rust_begin_unwind
  10:     0x7ff93b8e0a80 - core::panicking::panic_fmt::hcb326269aca941d7
  11:     0x7ff93b8e0672 - core::option::expect_failed::h16d9254b0eeda644
  12:     0x7ff93f0b3a58 - <rustc_mir::borrow_check::constraint_generation::ConstraintGeneration as rustc_middle::mir::visit::Visitor>::visit_terminator::h2307897895b70cb2
  13:     0x7ff93f0afbd8 - <rustc_mir::borrow_check::constraint_generation::ConstraintGeneration as rustc_middle::mir::visit::Visitor>::visit_terminator::h2307897895b70cb2
  14:     0x7ff93f0c2eec - <rustc_mir::borrow_check::MirBorrowckCtxt as rustc_mir::dataflow::framework::visitor::ResultsVisitor>::visit_terminator_after_primary_effect::he8600b98d875dee6  
  15:     0x7ff93f0c1598 - <rustc_mir::borrow_check::MirBorrowckCtxt as rustc_mir::dataflow::framework::visitor::ResultsVisitor>::visit_statement_before_primary_effect::h7bafd5c837be7a82  
  16:     0x7ff93eebaf62 - <rustc_mir::borrow_check::type_check::liveness::polonius::UseFactsExtractor as rustc_middle::mir::visit::Visitor>::visit_place::h0987aa4e9aa96d00
  17:     0x7ff93f15de3b - <rustc_mir::borrow_check::type_check::TypeVerifier as rustc_middle::mir::visit::Visitor>::visit_body::ha6c145c16ee8d1b5
  18:     0x7ff93f0bc0c0 - rustc_mir::borrow_check::provide::hef6a38431e907834
  19:     0x7ff93ebfc2cb - <rustc_middle::mir::traversal::ReversePostorder as core::iter::traits::iterator::Iterator>::size_hint::hda36076c24cd7432
  20:     0x7ff93f0b838b - rustc_mir::borrow_check::provide::hef6a38431e907834
  21:     0x7ff93f07d639 - <rustc_mir::util::spanview::SpanViewable as core::fmt::Debug>::fmt::h634057fcf70b84bf
  22:     0x7ff93c07205e - rustc_interface::passes::BoxedResolver::complete::hc73eeae317e78de9
  23:     0x7ff93c007fa6 - rustc_interface::util::commit_date_str::h3912c38032a724c5
  24:     0x7ff93bfd08f0 - rustc_interface::util::commit_date_str::h3912c38032a724c5
  25:     0x7ff93c034d98 - rustc_interface::interface::parse_cfgspecs::hccf1b6756214f4f0
  26:     0x7ff93c0974f0 - rustc_interface::queries::Linker::link::hb404463f08312af9
  27:     0x7ff93c07f46b - rustc_interface::queries::Linker::link::hb404463f08312af9
  28:     0x7ff93c0931b9 - rustc_interface::queries::Linker::link::hb404463f08312af9
  29:     0x7ff93c00eef7 - rustc_interface::util::commit_date_str::h3912c38032a724c5
  30:     0x7ff93c04a15c - rustc_interface::passes::QueryContext::print_stats::hbb0586fa10203714
  31:     0x7ff93be557c0 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::hc5ecdaebd526739d
  32:     0x7ff93be97fc6 - rustc_ast::util::parser::prec_let_scrutinee_needs_par::h214551e4e217a2e9
  33:     0x7ff93be055ad - chalk_engine::TimeStamp::increment::h8ab57932dde938a4
  34:     0x7ff93be74911 - rustc_ast::util::parser::prec_let_scrutinee_needs_par::h214551e4e217a2e9
  35:     0x7ff93bdeb9bf - <rustc_typeck::coherence::inherent_impls::InherentCollect as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_trait_item::h1647d16705366107
  36:     0x7ff93bde5f7f - <rustc_typeck::coherence::inherent_impls::InherentCollect as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_trait_item::h1647d16705366107
  37:     0x7ff93be55e9c - <rustc_driver::Compilation as core::fmt::Debug>::fmt::hc5ecdaebd526739d
  38:     0x7ff93be71e1e - rustc_ast::util::parser::prec_let_scrutinee_needs_par::h214551e4e217a2e9
  39:     0x7ff93be51215 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::hc5ecdaebd526739d
  40:     0x7ff93be736a9 - rustc_ast::util::parser::prec_let_scrutinee_needs_par::h214551e4e217a2e9
  41:     0x7ff93be52e05 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::hc5ecdaebd526739d
  42:     0x7ff93be75515 - rustc_ast::util::parser::prec_let_scrutinee_needs_par::h214551e4e217a2e9
  43:     0x7ff93be9da9d - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::hb3fcb74fea10bfb2
  44:     0x7ff93b8ccb8a - std::sys::windows::thread::Thread::new::h1849799f24702024
  45:     0x7ff9af5a7c24 - BaseThreadInitThunk
  46:     0x7ff9b154d721 - RtlUserThreadStart
```

</p>
</details>

**Comment by jyn514** [comment]
This is fixed on nightly: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=70ec08b9bdda8197d99f502241d7932f (switch it to 'stable' to see that you get the same ICE).

> While I'm here reporting this panic, would someone mind clarifying to me what is the most idiomatic way to accept a closure of any type (FnOnce, Fn, and FnMut). I read somewhere that FnOnce was sort of the trait that all of the closures would implement regardless - does that mean I can use that alone to accept any closure (assuming the mut and & matches)?

Yes, anything that implements `FnMut` will also implement FnOnce. There's some more info in the docs: https://doc.rust-lang.org/std/ops/trait.FnOnce.html

**Comment by jyn514** [comment]
Note that since FnOnce closures have to be taken by value, you can't use `dyn FnOnce` in all the places you can use `&mut dyn FnMut`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=58fc253710ab03dd85d60bdb856f308d
but if you use FnOnce and the code compiles, you will also accept FnMut and Fn closures.

**Comment by jdfreder** [comment]
Thank you for confirming that it's already fixed - and extra thank you for the explaination!
