### ISSUE TITLE
Internal Compiler Error

### ISSUE THREAD

**Issue by DrOptix** [rust-lang/rust#84760]
I tried to isolate the best I can the problem. I would say it is because of how I wrote the `Event::emit()` function.
Let me know if I can provide more context.

### Code

```Rust
#![deny(unsafe_code)]
#![feature(decl_macro)]

mod events {
    pub struct Event<'a, T> {
        subscribers: Vec<Box<dyn FnMut(&T) + 'a>>,
    }

    impl<'a, T> Event<'a, T> {
        pub fn new() -> Self {
            Self {
                subscribers: Vec::new(),
            }
        }

        pub fn emit(&self, data: &T) {
            for callback in self.subscribers.as_slice() {
                callback(&data);
            }
        }
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (42816d61e 2021-04-24)
binary: rustc
commit-hash: 42816d61ead7e46d462df997958ccfd514f8c21c
commit-date: 2021-04-24
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0

```

### Error output

```
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:192:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:192:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:50:5
   3: rustc_errors::CodeSuggestion::splice_lines
   4: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   5: rustc_errors::json::Diagnostic::from_errors_diagnostic
   6: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: rustc_errors::HandlerInner::emit_diagnostic
   8: rustc_errors::Handler::emit_diagnostic
   9: rustc_mir::borrow_check::do_mir_borrowck
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_mir::borrow_check::mir_borrowck
  12: core::ops::function::FnOnce::call_once
  13: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::force_query_with_job
  17: rustc_query_system::query::plumbing::get_query_impl
  18: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  19: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  20: rustc_interface::passes::analysis
  21: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::force_query_with_job
  25: rustc_query_system::query::plumbing::get_query_impl
  26: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  27: rustc_interface::passes::QueryContext::enter
  28: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  29: rustc_span::with_source_map
  30: rustc_interface::interface::create_compiler_and_run
  31: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (42816d61e 2021-04-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `events::<impl at project/src/events.rs:17:1: 38:2>::emit`
#1 [analysis] running analysis passes on this crate
end of query stack
   0: rust_begin_unwind
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/42816d61ead7e46d462df997958ccfd514f8c21c/library/core/src/panicking.rs:50:5
   3: rustc_errors::CodeSuggestion::splice_lines
   4: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   5: rustc_errors::json::Diagnostic::from_errors_diagnostic
   6: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: rustc_errors::HandlerInner::emit_diagnostic
   8: rustc_errors::Handler::emit_diagnostic
   9: rustc_mir::borrow_check::do_mir_borrowck
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_mir::borrow_check::mir_borrowck
  12: core::ops::function::FnOnce::call_once
  13: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::force_query_with_job
  17: rustc_query_system::query::plumbing::get_query_impl
  18: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  19: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  20: rustc_interface::passes::analysis
  21: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::force_query_with_job
  25: rustc_query_system::query::plumbing::get_query_impl
  26: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  27: rustc_interface::passes::QueryContext::enter
  28: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  29: rustc_span::with_source_map
  30: rustc_interface::interface::create_compiler_and_run
  31: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (42816d61e 2021-04-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `events::<impl at project/src/events.rs:17:1: 38:2>::emit`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `project`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by fanninpm** [comment]
> `rustc 1.53.0-nightly (42816d61e 2021-04-24)`

Have you tried this on the latest version of nightly?

**Comment by jackh726** [comment]
I don't reproduce this at all in the playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=98ac6b0031af7018ab69d8178dd663a9

**Comment by DrOptix** [comment]
> Have you tried this on the latest version of nightly?
Just now I've noticed that `rustup` is skipping some nightly versions when I do an update because some nightly builds are missing some modules.
```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-04-30, rust version 1.53.0-nightly (478a07df0 2021-04-29)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2021-04-29-x86_64-unknown-linux-gnu'
info: latest update on 2021-04-29, rust version 1.53.0-nightly (ca075d268 2021-04-28)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2021-04-28-x86_64-unknown-linux-gnu'
info: latest update on 2021-04-28, rust version 1.53.0-nightly (727d10156 2021-04-27)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2021-04-27-x86_64-unknown-linux-gnu'
info: latest update on 2021-04-27, rust version 1.53.0-nightly (968425893 2021-04-26)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2021-04-26-x86_64-unknown-linux-gnu'
info: latest update on 2021-04-26, rust version 1.53.0-nightly (3709ae324 2021-04-25)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
info: syncing channel updates for 'nightly-2021-04-25-x86_64-unknown-linux-gnu'
info: checking for self-updates
```

I will try to do some more tests

> I don't reproduce this at all in the playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=98ac6b0031af7018ab69d8178dd663a9
I've noticed this too, but I guessed it is worth reporting as the compiler panic itself invited me to report the issue.

**Comment by jackh726** [comment]
@DrOptix Did you try to minimize it before posting? Seems like maybe the minimization wasn't quite correct and didn't capture the error.

**Comment by DrOptix** [comment]
Just to be here for potential future reference.

I went back to the version of nightly and rechecked and it spit out this with `RUST_BACKTRACE=full`, but without a `cargo clean`: 
https://pastebin.com/b25UR2Mb

After I did a `cargo clean`, running with `RUST_BACKRACE=full`:
https://pastebin.com/JDZcwm6K

**Comment by DrOptix** [comment]
I'm closing this one. Anyway all the info I could give is posted.
