### ISSUE TITLE
'rustc' panicked at 'LocalTableInContext: key not found', compiler/rustc_mir/src/borrow_check/diagnostics/mutability_errors.rs:512:30

### ISSUE THREAD

**Issue by rmsk2** [rust-lang/rust#84817]
When compiling the following program with  `rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-apple-darwin` the compiler panics. The resulting error message is:

```
user@hostname data % RUST_BACKTRACE=1 rustc bug.rs 
thread 'rustc' panicked at 'LocalTableInContext: key not found', compiler/rustc_mir/src/borrow_check/diagnostics/mutability_errors.rs:512:30
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: rustc_mir::borrow_check::diagnostics::mutability_errors::<impl rustc_mir::borrow_check::MirBorrowckCtxt>::show_mutating_upvar
   4: rustc_mir::borrow_check::diagnostics::mutability_errors::<impl rustc_mir::borrow_check::MirBorrowckCtxt>::report_mutability_error
   5: rustc_mir::borrow_check::MirBorrowckCtxt::access_place
   6: <rustc_mir::borrow_check::MirBorrowckCtxt as rustc_mir::dataflow::framework::visitor::ResultsVisitor>::visit_statement_before_primary_effect
   7: <rustc_mir::dataflow::framework::direction::Forward as rustc_mir::dataflow::framework::direction::Direction>::visit_results_in_block
   8: rustc_mir::dataflow::framework::visitor::visit_results
   9: rustc_mir::borrow_check::do_mir_borrowck
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_mir::borrow_check::mir_borrowck
  12: core::ops::function::FnOnce::call_once
  13: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::force_query_with_job
  17: rustc_query_system::query::plumbing::get_query_impl
  18: rustc_query_system::query::plumbing::ensure_query_impl
  19: rustc_session::utils::<impl rustc_session::session::Session>::time
  20: rustc_interface::passes::analysis
  21: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::force_query_with_job
  25: rustc_query_system::query::plumbing::get_query_impl
  26: rustc_interface::passes::QueryContext::enter
  27: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  28: rustc_span::with_source_map
  29: rustc_interface::interface::create_compiler_and_run
  30: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-apple-darwin

query stack during panic:
#0 [mir_borrowck] borrow-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
```

Here the program that I tried to compile:

```
use std::env;


fn hash_files(file_names: &Vec<String>, line_formatter: &mut dyn FnMut(&String, &String) -> String) {
    for i in file_names {
        let hash = "abcdef".to_string();
        let line_out = line_formatter(i, &hash);

        println!("{}", line_out);
    }
}

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    
    if args.len() == 0 {
        println!("usage: rs256shum <file_name> [<file_name> ...]");
    }

    let simple_format = |f_name: &String, hash_val: &String| -> String {
        return format!("{}  {}", f_name, hash_val);
    };

    hash_files(&args, &mut simple_format);
}
```
As far as I can tell the program is in fact invalid as the variable `simple_format` should be mutable as it is borrowed as mutable in the function call following its definition. If this definition is replaced by 

```
    let mut simple_format = |f_name: &String, hash_val: &String| -> String {
        return format!("{}  {}", f_name, hash_val);
    };
```

the program compiles.

**Comment by klensy** [comment]
On current nightly 01-05-21 no ICE
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0ca1d358a97de3da571c072a8c40a67a

**Comment by rmsk2** [comment]
So it seems to be already fixed. Cool!

Do I close the issue or the rust team?
