### ISSUE TITLE
ICE when compiling code

### ISSUE THREAD

**Issue by bioglaze** [rust-lang/rust#84831]
Crashes when running `cargo build`.

### Code

```Rust
// Cargo.toml dependency: ash = "0.32"

pub use ash::version::{DeviceV1_0, EntryV1_0, InstanceV1_0};

pub struct GfxDevice
{
    pub physical_device : vk::PhysicalDevice,
    pub vulkan_device : ash::version::<Type as InstanceV1_0>::Device
}


fn main() {
    println!("Hello, world!");
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1

```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:900:54

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

query stack during panic:
#0 [generics_of] computing generics of `ash::version`
#1 [opt_const_param_of] computing the optional const parameter of `GfxDevice::vulkan_device::{constant#0}`
#2 [typeck] type-checking `GfxDevice::vulkan_device::{constant#0}`
#3 [typeck_item_bodies] type-checking all item bodies
#4 [analysis] running analysis passes on this crate
end of query stack

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   3: rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_generics
   4: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::generics_of
   5: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::generics_of>::compute
   6: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   8: rustc_data_structures::stack::ensure_sufficient_stack
   9: rustc_query_system::query::plumbing::force_query_with_job
  10: rustc_query_system::query::plumbing::get_query_impl
  11: rustc_typeck::collect::type_of::opt_const_param_of
  12: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::opt_const_param_of>::compute
  13: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::force_query_with_job
  17: rustc_query_system::query::plumbing::get_query_impl
  18: rustc_typeck::check::typeck
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
  20: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  22: rustc_data_structures::stack::ensure_sufficient_stack
  23: rustc_query_system::query::plumbing::force_query_with_job
  24: rustc_query_system::query::plumbing::get_query_impl
  25: rustc_query_system::query::plumbing::ensure_query_impl
  26: rustc_typeck::check::typeck_item_bodies
  27: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
  28: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  29: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  30: rustc_data_structures::stack::ensure_sufficient_stack
  31: rustc_query_system::query::plumbing::force_query_with_job
  32: rustc_query_system::query::plumbing::get_query_impl
  33: rustc_typeck::check_crate
  34: rustc_interface::passes::analysis
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  36: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  37: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  38: rustc_data_structures::stack::ensure_sufficient_stack
  39: rustc_query_system::query::plumbing::force_query_with_job
  40: rustc_query_system::query::plumbing::get_query_impl
  41: rustc_interface::passes::QueryContext::enter
  42: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  43: rustc_span::with_source_map
  44: rustc_interface::interface::create_compiler_and_run
  45: rustc_span::with_session_globals

```

</p>
</details>

**Comment by hellow554** [comment]
Regression in nightly-2020-10-28 between fd542592f08ca0d1f7255600115c2eafdf6b5da7...07e968b640e8ff76fa8be4b48b70ab80ea577800

**Comment by hameerabbasi** [comment]
This is an error->ICE case, with a nice error as well.

<details><summary>full build output</summary>

```bash
$ cargo build
   Compiling bisect v0.1.0 (/home/habbasi/bisect)
error: expected one of `,` or `>`, found keyword `as`
 --> src/lib.rs:6:45
  |
6 |     pub vulkan_device : ash::version::<Type as InstanceV1_0>::Device
  |                                             ^^ expected one of `,` or `>`
  |
help: expressions must be enclosed in braces to be used as const generic arguments
  |
6 |     pub vulkan_device : ash::version::<{ Type as InstanceV1_0 }>::Device
  |                                        ^                      ^

error[E0433]: failed to resolve: use of undeclared crate or module `vk`
 --> src/lib.rs:5:27
  |
5 |     pub physical_device : vk::PhysicalDevice,
  |                           ^^ use of undeclared crate or module `vk`

error[E0412]: cannot find type `Device` in module `ash::version`
 --> src/lib.rs:6:63
  |
6 |     pub vulkan_device : ash::version::<Type as InstanceV1_0>::Device
  |                                                               ^^^^^^ not found in `ash::version`
  |
help: consider importing one of these items
  |
1 | use ash::Device;
  |
1 | use ash::vk::Device;
  |

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/decoder.rs:900:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [generics_of] computing generics of `ash::version`
#1 [opt_const_param_of] computing the optional const parameter of `GfxDevice::vulkan_device::{constant#0}`
end of query stack
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `bisect`

To learn more, run the command again with --verbose.
```
</details>

**Comment by hameerabbasi** [comment]
@rustbot modify labels -I-prioritize +P-high

As discussed in the prioritization working group [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2384831.20ICE.20when.20compiling.20code)

**Comment by steffahn** [comment]
Minimized
```rust
fn f() {
    std::<_ as _>;   
}
```

**Comment by steffahn** [comment]
Interesting thing… my minimized example only regresses at `nightly-2020-11-16` (98d66340d6e63eda115afc8b0da1d87965881936 to 603ab5bd6e0ffefafa7411cd8bd23a6ca82bcff0), however I can confirm the regression at `nightly-2020-10-28` (fd542592f08ca0d1f7255600115c2eafdf6b5da7 to 07e968b640e8ff76fa8be4b48b70ab80ea577800) for the original example.
```
fetching (via remote github) commits from max(fd542592f08ca0d1f7255600115c2eafdf6b5da7, 2020-10-25) to 07e968b640e8ff76fa8be4b48b70ab80ea577800
ending github query because we found starting sha: fd542592f08ca0d1f7255600115c2eafdf6b5da7
get_commits_between returning commits, len: 9
  commit[0] 2020-10-26UTC: Auto merge of #77187 - TimDiekmann:box-alloc, r=Amanieu
  commit[1] 2020-10-26UTC: Auto merge of #77876 - tmiasko:simplify-locals, r=wesleywiser
  commit[2] 2020-10-27UTC: Auto merge of #78421 - JohnTitor:rollup-bq2d7fo, r=JohnTitor
  commit[3] 2020-10-27UTC: Auto merge of #78359 - ssomers:btree_cleanup_mem, r=Mark-Simulacrum
  commit[4] 2020-10-27UTC: Auto merge of #77317 - varkor:break-diverging-value, r=nikomatsakis
  commit[5] 2020-10-27UTC: Auto merge of #77502 - varkor:const-generics-suggest-enclosing-braces, r=petrochenkov
  commit[6] 2020-10-27UTC: Auto merge of #78227 - SergioBenitez:test-stdout-threading, r=m-ou-se
  commit[7] 2020-10-27UTC: Auto merge of #78434 - jonas-schievink:disable-miropt, r=wesleywiser
  commit[8] 2020-10-27UTC: Auto merge of #76269 - ayrtonm:function-reference-lint, r=oli-obk
ERROR: no commits between fd542592f08ca0d1f7255600115c2eafdf6b5da7 and 07e968b640e8ff76fa8be4b48b70ab80ea577800 within last 167 days
```
AFAICT likely #77502.

**Comment by steffahn** [comment]
Ah, that makes sense… the later regression is due to #79016. Using `std::<x as y>` takes it back to `nightly-2020-10-28`.

**Comment by steffahn** [comment]
Confirmed #77502 as the regression point.
cc @varkor @estebank

**Comment by steffahn** [comment]
Nevermind, further minimization to
```rust
fn f() {
    std::<0>;   
}
```
puts the regression point _earlier_ than #77502.
```
********************************************************************************
Regression in nightly-2020-03-25
********************************************************************************

fetching https://static.rust-lang.org/dist/2020-03-24/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-03-24: 40 B / 40 B [================================================================================] 100.00 % 363.73 KB/s converted 2020-03-24 to 1edd389cc4c7b5be7a3dd4fe4b986f6017018e54
fetching https://static.rust-lang.org/dist/2020-03-25/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-03-25: 40 B / 40 B [================================================================================] 100.00 % 410.38 KB/s converted 2020-03-25 to 02046a5d402c789c006d0da7662f800fe3c45faf
looking for regression commit between 2020-03-24 and 2020-03-25
fetching (via remote github) commits from max(1edd389cc4c7b5be7a3dd4fe4b986f6017018e54, 2020-03-22) to 02046a5d402c789c006d0da7662f800fe3c45faf
ending github query because we found starting sha: 1edd389cc4c7b5be7a3dd4fe4b986f6017018e54
get_commits_between returning commits, len: 8
  commit[0] 2020-03-23UTC: Auto merge of #70330 - Centril:rollup-ts0clvx, r=Centril
  commit[1] 2020-03-23UTC: Auto merge of #70322 - matthiaskrgr:submodule_upd, r=Dylan-DPC
  commit[2] 2020-03-24UTC: Auto merge of #70343 - Centril:rollup-94egfvs, r=Centril
  commit[3] 2020-03-24UTC: Auto merge of #70351 - Centril:rollup-tveoq3w, r=Centril
  commit[4] 2020-03-24UTC: Auto merge of #69894 - vtbassmatt:master, r=nellshamrell
  commit[5] 2020-03-24UTC: Auto merge of #70163 - nikic:llvm-10-preparation, r=cuviper
  commit[6] 2020-03-24UTC: Auto merge of #70190 - pietroalbini:gha, r=Mark-Simulacrum
  commit[7] 2020-03-24UTC: Auto merge of #70371 - Centril:rollup-ywi1vo3, r=Centril
ERROR: no commits between 1edd389cc4c7b5be7a3dd4fe4b986f6017018e54 and 02046a5d402c789c006d0da7662f800fe3c45faf within last 167 days
```

**Comment by steffahn** [comment]
The regression of the `std::<0>` example happens at #70284.

cc @lcnr

**Comment by hellow554** [comment]
As a reminder: Please add [both][0] code [snippets][1] as testcases. They seem to be triggered differently, therefore it shouldn't hurt to add them both.


[0]: https://github.com/rust-lang/rust/issues/84831#issuecomment-831123197
[1]: https://github.com/rust-lang/rust/issues/84831#issuecomment-831232546
