### ISSUE TITLE
Unable to install bat by cargo

### ISSUE THREAD

**Issue by diohabara** [rust-lang/rust#85248]
### Code

```Rust
cargo install bat
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.52.1
LLVM version: 12.0.0
```

### Error output

```
    Updating crates.io index
  Installing bat v0.18.1
   Compiling libc v0.2.94
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling pkg-config v0.3.19
   Compiling bitflags v1.2.1
   Compiling serde_derive v1.0.126
   Compiling memchr v2.4.0
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.126
   Compiling encoding_index_tests v0.1.4
   Compiling proc-macro-hack v0.5.19
   Compiling matches v0.1.8
   Compiling tinyvec_macros v0.1.0
   Compiling log v0.4.14
   Compiling ryu v1.0.5
   Compiling unicode-width v0.1.8
   Compiling crc32fast v1.2.1
   Compiling regex-syntax v0.6.25
   Compiling lazy_static v1.4.0
   Compiling percent-encoding v2.1.0
   Compiling vec_map v0.8.2
   Compiling linked-hash-map v0.5.4
   Compiling ansi_term v0.11.0
   Compiling safemem v0.3.3
   Compiling ucd-trie v0.1.3
   Compiling hashbrown v0.9.1
   Compiling serde_json v1.0.64
   Compiling strsim v0.8.0
   Compiling adler v1.0.2
   Compiling version_check v0.9.3
   Compiling base64 v0.13.0
   Compiling bugreport v0.4.0
   Compiling same-file v1.0.6
   Compiling itoa v0.4.7
   Compiling xml-rs v0.8.3
   Compiling fnv v1.0.7
   Compiling lazycell v1.3.0
   Compiling dtoa v0.4.8
   Compiling shell-escape v0.1.5
   Compiling std_prelude v0.2.12
   Compiling ansi_term v0.12.1
   Compiling shell-words v1.0.0
   Compiling wild v2.0.4
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling miniz_oxide v0.4.4
   Compiling indexmap v1.6.2
   Compiling unicode-bidi v0.3.5
   Compiling tinyvec v1.2.0
   Compiling form_urlencoded v1.0.1
   Compiling line-wrap v0.1.1
   Compiling yaml-rust v0.4.5
   Compiling pest v2.1.3
   Compiling walkdir v2.3.2
   Compiling error-chain v0.12.4
   Compiling path_abs v0.5.1
   Compiling encoding v0.2.33
   Compiling unicode-normalization v0.1.17
   Compiling semver-parser v0.10.2
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.16
   Compiling content_inspector v0.2.4
   Compiling quote v1.0.9
   Compiling jobserver v0.1.22
   Compiling term_size v0.3.2
   Compiling atty v0.2.14
   Compiling terminal_size v0.1.16
   Compiling dirs-sys-next v0.1.2
   Compiling semver v0.11.0
   Compiling regex v1.5.4
   Compiling idna v0.2.3
   Compiling textwrap v0.11.0
   Compiling cc v1.0.67
   Compiling dirs-next v2.0.0
   Compiling flate2 v1.0.20
   Compiling clap v2.33.3
   Compiling url v2.2.2
   Compiling globset v0.4.6
   Compiling console v0.14.1
   Compiling chrono v0.4.19
   Compiling libz-sys v1.1.3
   Compiling onig_sys v69.6.0
   Compiling sys-info v0.9.0
   Compiling libgit2-sys v0.12.20+1.1.0
   Compiling ansi_colours v1.0.2
   Compiling git-version-macro v0.3.4
thread 'rustc' panicked at 'Failed to get crate data for crate21', compiler/rustc_metadata/src/creader.rs:136:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.1 (9bc8c42bb 2021-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debug-assertions=off --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `git-version-macro`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bat v0.18.1`, intermediate artifacts can be found at `/tmp/cargo-installGIwmuj`

Caused by:
  build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo install bat
    Updating crates.io index
  Installing bat v0.18.1
   Compiling libc v0.2.94
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling pkg-config v0.3.19
   Compiling bitflags v1.2.1
   Compiling serde_derive v1.0.126
   Compiling serde v1.0.126
   Compiling cfg-if v1.0.0
   Compiling memchr v2.4.0
   Compiling encoding_index_tests v0.1.4
   Compiling tinyvec_macros v0.1.0
   Compiling matches v0.1.8
   Compiling proc-macro-hack v0.5.19
   Compiling log v0.4.14
   Compiling ryu v1.0.5
   Compiling unicode-width v0.1.8
   Compiling regex-syntax v0.6.25
   Compiling crc32fast v1.2.1
   Compiling safemem v0.3.3
   Compiling adler v1.0.2
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling serde_json v1.0.64
   Compiling vec_map v0.8.2
   Compiling lazy_static v1.4.0
   Compiling percent-encoding v2.1.0
   Compiling linked-hash-map v0.5.4
   Compiling version_check v0.9.3
   Compiling ucd-trie v0.1.3
   Compiling hashbrown v0.9.1
   Compiling same-file v1.0.6
   Compiling itoa v0.4.7
   Compiling bugreport v0.4.0
   Compiling fnv v1.0.7
   Compiling base64 v0.13.0
   Compiling xml-rs v0.8.3
   Compiling std_prelude v0.2.12
   Compiling shell-escape v0.1.5
   Compiling dtoa v0.4.8
   Compiling lazycell v1.3.0
   Compiling ansi_term v0.12.1
   Compiling wild v2.0.4
   Compiling shell-words v1.0.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling indexmap v1.6.2
   Compiling miniz_oxide v0.4.4
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling unicode-bidi v0.3.5
   Compiling tinyvec v1.2.0
   Compiling line-wrap v0.1.1
   Compiling form_urlencoded v1.0.1
   Compiling pest v2.1.3
   Compiling yaml-rust v0.4.5
   Compiling walkdir v2.3.2
   Compiling error-chain v0.12.4
   Compiling path_abs v0.5.1
   Compiling encoding v0.2.33
   Compiling unicode-normalization v0.1.17
   Compiling semver-parser v0.10.2
   Compiling quote v1.0.9
   Compiling jobserver v0.1.22
   Compiling term_size v0.3.2
   Compiling atty v0.2.14
   Compiling terminal_size v0.1.16
   Compiling dirs-sys-next v0.1.2
   Compiling aho-corasick v0.7.18
   Compiling bstr v0.2.16
   Compiling content_inspector v0.2.4
   Compiling semver v0.11.0
   Compiling idna v0.2.3
   Compiling cc v1.0.67
   Compiling textwrap v0.11.0
   Compiling dirs-next v2.0.0
   Compiling flate2 v1.0.20
   Compiling regex v1.5.4
   Compiling url v2.2.2
   Compiling clap v2.33.3
   Compiling chrono v0.4.19
   Compiling libz-sys v1.1.3
   Compiling sys-info v0.9.0
   Compiling onig_sys v69.6.0
   Compiling libgit2-sys v0.12.20+1.1.0
   Compiling ansi_colours v1.0.2
   Compiling console v0.14.1
   Compiling globset v0.4.6
   Compiling git-version-macro v0.3.4
thread 'rustc' panicked at 'Failed to get crate data for crate21', compiler/rustc_metadata/src/creader.rs:136:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: rustc_metadata::creader::CrateLoader::maybe_resolve_crate
   3: rustc_metadata::creader::CrateLoader::maybe_process_path_extern
   4: rustc_resolve::Resolver::extern_prelude_get
   5: rustc_resolve::macros::<impl rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
   6: rustc_resolve::Resolver::resolve_path_with_ribs::{{closure}}
   7: rustc_resolve::Resolver::resolve_path_with_ribs
   8: rustc_resolve::imports::ImportResolver::resolve_imports
   9: rustc_resolve::macros::<impl rustc_expand::base::ResolverExpand for rustc_resolve::Resolver>::resolve_imports
  10: rustc_expand::expand::MacroExpander::fully_expand_fragment
  11: rustc_expand::expand::MacroExpander::expand_crate
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_interface::passes::configure_and_expand_inner
  14: rustc_interface::passes::configure_and_expand::{{closure}}
  15: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  16: rustc_interface::passes::configure_and_expand
  17: rustc_interface::queries::Queries::expansion
  18: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  19: rustc_span::with_source_map
  20: rustc_interface::interface::create_compiler_and_run
  21: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.1 (9bc8c42bb 2021-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debug-assertions=off --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `git-version-macro`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bat v0.18.1`, intermediate artifacts can be found at `/tmp/cargo-installYLZxjp`

Caused by:
  build failed
```

</p>
</details>

**Comment by est31** [comment]
Sounds like a dupe of #85386, which itself was closed in favour of #56935.
