### ISSUE TITLE
Internal compiler error: Failed to get crate data for crate18

### ISSUE THREAD

**Issue by yanganto** [rust-lang/rust#85282]
### Code
repo: git@github.com:second-state/SewUp.git
hash: 9a19457f65a8195ecd40a8bc11540d364425acac

### Meta

[full log](https://github.com/second-state/SewUp/runs/2582317015)
`rustc --version --verbose`:
```
rustc 1.52.0 (88f19c6da 2021-05-03)
binary: rustc
commit-hash: 88f19c6dab716c6281af7602e30f413e809c5974
commit-date: 2021-05-03
host: x86_64-unknown-linux-gnu
release: 1.52.0
LLVM version: 12.0.0
```

### Error output

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.1 (9bc8c42bb 2021-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `thiserror`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Failed to get crate data for crate18', compiler/rustc_metadata/src/creader.rs:136:32
stack backtrace:
   0:     0x7fedb927f990 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fedb927f990 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fedb927f990 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fedb927f990 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fedb92edf1f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x7fedb9273ae2 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x7fedb92837d5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fedb92837d5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fedb92837d5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x7fedb9283283 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x7fedb9a545eb - rustc_driver::report_ice::hfd0c5c387cfb7249
  11:     0x7fedb9283f40 - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
  12:     0x7fedb9283ab7 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  13:     0x7fedb927fe4c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fedb9283a19 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  15:     0x7fedb924816b - std::panicking::begin_panic_fmt::h400b8e9dca200408
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  16:     0x7fedbb3edaaa - rustc_metadata::creader::CrateLoader::maybe_resolve_crate::hf4c5f66bf6258d21
  17:     0x7fedbbcef000 - rustc_metadata::creader::CrateLoader::process_path_extern::h5ee3a89ace640e17
  18:     0x7fedbb00dfc8 - rustc_resolve::Resolver::extern_prelude_get::h80fb23ec6b21721b
  19:     0x7fedbb001855 - rustc_resolve::macros::<impl rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope::h366127a48d13ca61
  20:     0x7fedbb00d9ea - rustc_resolve::Resolver::resolve_path_with_ribs::{{closure}}::h293029fd2e27143b
  21:     0x7fedbb00b87f - rustc_resolve::Resolver::resolve_path_with_ribs::h5846fb8b054342d4
  22:     0x7fedbba1c78c - rustc_resolve::imports::ImportResolver::finalize_import::h319227ca78bdc1b2
  23:     0x7fedbba1bd06 - rustc_resolve::imports::ImportResolver::finalize_imports::h224aac0a28652153
  24:     0x7fedbba17fc0 - rustc_session::utils::<impl rustc_session::session::Session>::time::h94694ba3f9a8942c
  25:     0x7fedbba2ead8 - rustc_resolve::Resolver::resolve_crate::h52e48da6ab9a355f
  26:     0x7fedbb731cf3 - rustc_interface::passes::configure_and_expand_inner::hb2bcbfa207a7b6c6
  27:     0x7fedbb72f6df - rustc_interface::passes::configure_and_expand::{{closure}}::ha5f9c50efa4e445b
  28:     0x7fedbb72b988 - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::hd6c6a8557c6de885
  29:     0x7fedbb730f53 - rustc_interface::passes::configure_and_expand::hf23936bd4783aada
  30:     0x7fedbb73c486 - rustc_interface::queries::Queries::expansion::hcdf9046404e6271d
  31:     0x7fedbb6fbea0 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h25e70888d22e3a4c
  32:     0x7fedbb6f6a51 - rustc_span::with_source_map::h2cd9a6094ef7af0e
  33:     0x7fedbb6fd04e - rustc_interface::interface::create_compiler_and_run::h5877f5f12804db55
  34:     0x7fedbb6f78f8 - scoped_tls::ScopedKey<T>::set::hd60de2a62f3fb82b
  35:     0x7fedbb6fd3fb - std::sys_common::backtrace::__rust_begin_short_backtrace::hf09e28c4d01a4892
  36:     0x7fedbb714a35 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hff3afb7d3b239db0
  37:     0x7fedb929372a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc444a77f8dd8d825
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  38:     0x7fedb929372a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8b68a0a9a2093dfc
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  39:     0x7fedb929372a - std::sys::unix::thread::Thread::new::thread_start::hb95464447f61f48d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  40:     0x7fedb91bc609 - start_thread
  41:     0x7fedb90d0293 - clone
  42:                0x0 - <unknown>
```

</p>
</details>

**Comment by Enselic** [comment]
Triage: The reproducer does not work any longer. Can you still reproduce this ICE?

**Comment by yanganto** [comment]
I'm sorry, it is too long ago, I tried to reproduce it, but unfortunately, I can not set up the environment to produce the same issue.
https://github.com/second-state/SewUp/commits/debug
