### ISSUE TITLE
ICE: broken MIR in DefId(0:3 ~ mutant[8787]::has_efiapi) (NoSolution): could not prove Binder(TraitPredicate(<i32 as Copy>), [])

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#85349]
### Code

```Rust
#![feature(no_core, lang_items)]
#![no_core]
#[lang = "sized"]
trait Sized {}
#[lang = "copy"]
trait Copy {}
fn has_efiapi() {
    if let 0 = 1 {}
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (1025db84a 2021-05-14)
binary: rustc
commit-hash: 1025db84a68b948139b5adcd55da31bce32da8f3
commit-date: 2021-05-14
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
warning: function is never used: `has_efiapi`
 --> mutant.rs:7:4
  |
7 | fn has_efiapi() {
  |    ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

error: internal compiler error: broken MIR in DefId(0:3 ~ mutant[8787]::has_efiapi) (NoSolution): could not prove Binder(TraitPredicate(<i32 as Copy>), [])
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1021:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (1025db84a 2021-05-14) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
warning: function is never used: `has_efiapi`
 --> mutant.rs:7:4
  |
7 | fn has_efiapi() {
  |    ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

error: internal compiler error: broken MIR in DefId(0:3 ~ mutant[8787]::has_efiapi) (NoSolution): could not prove Binder(TraitPredicate(<i32 as Copy>), [])
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:252:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1021:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1025db84a68b948139b5adcd55da31bce32da8f3/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/1025db84a68b948139b5adcd55da31bce32da8f3/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
   9: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (1025db84a 2021-05-14) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type staticlib

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by jackh726** [comment]
This is expected behavior. The `Copy` impl of `i32` is in core itself: https://github.com/rust-lang/rust/blob/fe72845f7bb6a77b9e671e6a4f32fe714962cec4/library/core/src/marker.rs#L815
