### ISSUE TITLE
Inconsistent results between split functions and chained functions as well as match expression

### ISSUE THREAD

**Issue by superwushu** [rust-lang/rust#85537]
Very accidentally, I hit an issue when playing with the [sample web server](https://doc.rust-lang.org/book/ch20-03-graceful-shutdown-and-cleanup.html) (full code in the end) from The Book.

The web server is supposed to handle multiple requests by `Worker`'s threads in the `ThreadPool`. The sample code has no problem. Making two requests simultaneously:
```
(console 1)
$ curl localhost:7878/sleep    # return the result after 5 seconds

(console 2)
$ curl localhost:7878/404      # return the result immediately

(console 0)
$ cargo run
...
Worker 2 got a job; executing.
Worker 0 got a job; executing.
```

That worked as expected.

However, when I split the chained message unwrapping:

```rust
impl Worker {
    fn new(id: usize, receiver: Arc<Mutex<mpsc::Receiver<Message>>>) -> Worker {
        let thread = thread::spawn(move || loop {
-           let message = receiver.lock().unwrap().recv().unwrap();
+           let recv = receiver.lock().unwrap();
+           let message = recv.recv().unwrap();
            match message {
                Message::NewJob(job) => {
                    println!("Worker {} got a job; executing.", id);
                    job();
                }
   ...
```
Or whatever other forms I tried:

```rust
let recv = receiver.lock();
let message = unwrap().recv().unwrap();
```

```rust
let recv = receiver.lock().unwrap().recv();
let message = recv.unwrap();
```

or even

```rust
impl Worker {
    fn new(id: usize, receiver: Arc<Mutex<mpsc::Receiver<Message>>>) -> Worker {
        let thread = thread::spawn(move || loop {
-           let message = receiver.lock().unwrap().recv().unwrap();
-           match message {
+           match receiver.lock().unwrap().recv().unwrap() {
                Message::NewJob(job) => {
                    println!("Worker {} got a job; executing.", id);
                    job();
                }

```

The result is completely different:

```
(console 1)
$ curl localhost:7878/sleep    # return the result after 5 seconds

(console 2)
$ curl localhost:7878/404      # return the result after the above curl completes

(console 0)
$ cargo run
...
Worker 0 got a job; executing.
(after ~5 seconds)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/lib.rs:80:35
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/lib.rs:80:35
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/lib.rs:80:35
```

Split functions probably differ in semantics from chained functions. But I'm quite confused by omitting the variable `message` and moving the chained functions to the `match` expression.

### Meta

Tried both stable and nightly.

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-apple-darwin
release: 1.50.0
```
```
rustc 1.54.0-nightly (40d230204 2021-05-20)
binary: rustc
commit-hash: 40d23020470db06903589e210c83a4936f22d52a
commit-date: 2021-05-20
host: x86_64-apple-darwin
release: 1.54.0-nightly
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:42:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/wushu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: bootme_rs::handle_connection
             at ./src/main.rs:42:20
   5: bootme_rs::main::{{closure}}
             at ./src/main.rs:19:13
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /Users/wushu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /Users/wushu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1328:9
   8: bootme_rs::lib::Worker::new::{{closure}}
             at ./src/lib.rs:84:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/lib.rs:80:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/wushu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: bootme_rs::lib::Worker::new::{{closure}}
             at ./src/lib.rs:80:19
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/lib.rs:80:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/wushu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: bootme_rs::lib::Worker::new::{{closure}}
             at ./src/lib.rs:80:19
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/lib.rs:80:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/wushu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: bootme_rs::lib::Worker::new::{{closure}}
             at ./src/lib.rs:80:19
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by csmoe** [comment]
It's known behavior, the reference might be helpful for you https://doc.rust-lang.org/reference/destructors.html#temporary-scopes

**Comment by superwushu** [comment]
@csmoe Appreciate it if you can elaborate on this. Moving the chained functions to `match` scrutinee should not change the place of destructor because there is only one `match` statement within the loop. As quoted below from [temporary scopes](https://doc.rust-lang.org/reference/destructors.html#temporary-scopes):

> The scrutinee of a match expression is not a temporary scope, so temporaries in the scrutinee can be dropped after the match expression.

**Comment by jonas-schievink** [comment]
The guard is dropped after the `let message = receiver.lock().unwrap().recv().unwrap();` is evaluated, which unlocks the mutex.

**Comment by superwushu** [comment]
> The guard is dropped after the `let message = receiver.lock().unwrap().recv().unwrap();` is evaluated, which unlocks the mutex.

Ah, I see. It's because of the implicit unlock for `Mutex` when dropped. Thanks a lot!
