### ISSUE TITLE
ICE on `#![feature(rustc_insignificant_dtor)]`

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust#85680]
### Code
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=60dcf2615cf526fe8c7676a4f92a5172))
```rust
#![feature(rustc_insignificant_dtor)]
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (5dc8789e3 2021-05-21)
binary: rustc
commit-hash: 5dc8789e300930751a78996da0fa906be5a344a2
commit-date: 2021-05-21
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

Also reproduced on the playground: `1.54.0-nightly (2021-05-24 126561cb31e8ebe1e2dd)`.

### Error output

```
thread 'rustc' panicked at 'feature `rustc_insignificant_dtor` is not declared anywhere', compiler/rustc_feature/src/lib.rs:122:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (5dc8789e3 2021-05-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'feature `rustc_insignificant_dtor` is not declared anywhere', compiler/rustc_feature/src/lib.rs:122:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/std/src/panicking.rs:457:5
   2: rustc_feature::find_feature_issue
   3: core::ops::function::FnOnce::call_once{{vtable.shim}}
   4: rustc_middle::lint::struct_lint_level::struct_lint_level_impl
   5: rustc_middle::lint::struct_lint_level
   6: rustc_lint::levels::LintLevelsBuilder::struct_lint
   7: rustc_lint::context::LintContext::struct_span_lint
   8: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
   9: <rustc_lint::builtin::IncompleteFeatures as rustc_lint::passes::EarlyLintPass>::check_crate
  10: rustc_lint::early::check_ast_crate
  11: rustc_session::utils::<impl rustc_session::session::Session>::time
  12: rustc_interface::passes::BoxedResolver::access::{{closure}}
  13: rustc_interface::passes::configure_and_expand::{{closure}}
  14: rustc_interface::passes::BoxedResolver::access
  15: rustc_interface::queries::Queries::lower_to_hir
  16: rustc_interface::queries::Queries::global_ctxt
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (5dc8789e3 2021-05-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

### Addendum

Note that similar internal feature gates don't ICE ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7a239cbf08e32ea2f1ed00784c615232)):
```rust
#![feature(rustc_variance)]
```

```
error[E0635]: unknown feature `rustc_variance`
 --> src/lib.rs:1:12
  |
1 | #![feature(rustc_variance)]
  |            ^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by PatchMixolydic** [comment]
This ICE does not happen if the `incomplete_features` lint is allowed ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5fb2796c8f09af7d607a8ee2c960e19b)). This may be because `rustc_insignificant_dtor` is listed in `rustc_feature::active::INCOMPLETE_FEATURES` but is not declared with `declare_features!`.

https://github.com/rust-lang/rust/blob/1969c2e312303faa458cf19dad9783165e3c72c8/compiler/rustc_feature/src/active.rs#L679-L699
