### ISSUE TITLE
One-off ICE - Failed to get crate data for crate23

### ISSUE THREAD

**Issue by ralfbiedert** [rust-lang/rust#85785]
### Code

Unfortunately I don't have an example, it ICE'ed only once when attempting `cargo fix` on a larger internal project. Running the command again just gave regular compile errors. 

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-pc-windows-msvc
release: 1.52.1
LLVM version: 12.0.0
```

### Error output

```
❯ cargo fix
    Checking strsim v0.8.0
    Checking clap v2.33.3
    [...]
thread 'rustc' panicked at 'Failed to get crate data for crate23', compiler\rustc_metadata\src\creader.rs:136:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.1 (9bc8c42bb 2021-05-09) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=rust-lld.exe -C incremental --crate-type lib --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `encoderlib-ffi`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'Failed to get crate data for crate23', compiler\rustc_metadata\src\creader.rs:136:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.1 (9bc8c42bb 2021-05-09) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=rust-lld.exe -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

**Comment by Smittyvb** [comment]
I sometimes get a similar ICE when compiling `rustc`. I think it might have something to do with rust-analyzer -- were you running rust-analyzer around when the ICE occurred?

**Comment by ralfbiedert** [comment]
I had CLion idling in the background, but it's not using rust-analyzer to my knowledge, and I haven't installed rust-analyser either.

**Comment by Enselic** [comment]
Triage: Without a way for others to reproduce the ICE, not much can be done at this point. Closing.
