### ISSUE TITLE
ICE: panicked at 'explicit panic', compiler/rustc_errors/src/diagnostic_builder.rs:424:13

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#85794]
### Code

```Rust
struct Baz {
  inner : dyn fn ()
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (1c6868aa2 2021-05-27)
binary: rustc
commit-hash: 1c6868aa21981b37cbd3fc95828ee3b0ac22d494
commit-date: 2021-05-27
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
error: expected `,`, or `}`, found keyword `fn`
 --> mutant.rs:2:14
  |
2 |   inner : dyn fn ()
  |              ^ help: try adding a comma: `,`

error: internal compiler error: the following error was constructed but not emitted

error: expected identifier, found `(`
 --> mutant.rs:2:18
  |
2 |   inner : dyn fn ()
  |                  ^ expected identifier

thread 'rustc' panicked at 'explicit panic', compiler/rustc_errors/src/diagnostic_builder.rs:424:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (1c6868aa2 2021-05-27) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 3 previous errors
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: expected `,`, or `}`, found keyword `fn`
 --> mutant.rs:2:14
  |
2 |   inner : dyn fn ()
  |              ^ help: try adding a comma: `,`

error: internal compiler error: the following error was constructed but not emitted

error: expected identifier, found `(`
 --> mutant.rs:2:18
  |
2 |   inner : dyn fn ()
  |                  ^ expected identifier

thread 'rustc' panicked at 'explicit panic', compiler/rustc_errors/src/diagnostic_builder.rs:424:13
stack backtrace:
   0: std::panicking::begin_panic
   1: <rustc_errors::diagnostic_builder::DiagnosticBuilder as core::ops::drop::Drop>::drop
   2: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_field_ident
   3: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_field_def::{{closure}}
   4: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_record_struct_body
   5: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_kind
   6: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_item_common
   7: rustc_parse::parser::item::<impl rustc_parse::parser::Parser>::parse_mod
   8: rustc_parse::parse_crate_from_file
   9: rustc_session::utils::<impl rustc_session::session::Session>::time
  10: rustc_interface::queries::Queries::parse
  11: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (1c6868aa2 2021-05-27) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to 3 previous errors
```

</p>
</details>

**Comment by LingMan** [comment]
This regressed in https://github.com/rust-lang/rust/pull/85057, which is a rollup. Luckily https://github.com/rust-lang/rust/pull/76808 is the only real candidate though.

The panic that gets called is this one: https://github.com/rust-lang/rust/blob/6166929741584d8b3ebcce6c758d5e8ba128d7f4/compiler/rustc_errors/src/diagnostic_builder.rs#L417-L424

From a quick scan of https://github.com/rust-lang/rust/pull/76808 it looks like a result gets dropped here : https://github.com/rust-lang/rust/blob/9964284fed181676300aad693449f5b751e35ff2/compiler/rustc_parse/src/parser/item.rs#L1477

cc @LeSeulArtichaut


searched nightlies: from nightly-2021-05-07 to nightly-2021-05-29
regressed nightly: nightly-2021-05-09
searched commits: from https://github.com/rust-lang/rust/commit/770792ff8d1ec542e78e77876ac936f43ffb8e05 to https://github.com/rust-lang/rust/commit/881c1ac408d93bb7adaa3a51dabab9266e82eee8
regressed commit: https://github.com/rust-lang/rust/commit/abf3ec5b3353be973b18269fcdda76a59743f235

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --prompt 
```
</details>

**Comment by LeSeulArtichaut** [comment]
Mhh, I don't even remember why I added this call to `parse_fn` in the first place, maybe to consume the fn body and get fewer/cleaner errors? Should have added a comment...
Anyway fixing this should be easy, we can `delay_as_bug` (or `cancel`) the error, or remove the call to `parse_fn`.
