### ISSUE TITLE
`lang_start` in std/src/rt.rs is unsound in presence of panic payload that panics on drop

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#86030]
See https://github.com/rust-lang/rust/issues/86027 for an example of the problem.

```
fn main() {
    std::panic::panic_any(Bomb);
}
```

```
thread 'main' panicked at 'Box<Any>', src/main.rs:12:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'explicit panic', src/main.rs:7:9
fatal runtime error: failed to initiate panic, error 5
abort (core dumped)
```

Here we panic without any landing pads available upstack, because we are already the top-most(-ish) frame in the first place. This is UB.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2386030.20.60lang_start.60.20in.20std.2Fsrc.2Frt.2Ers.20is.20unsound.20in.20presence.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical

**Comment by RalfJung** [comment]
Playground link with full code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8042bb4b47c3b1c57f1a0dfe11a3bf41

**Comment by RalfJung** [comment]
FWIW, Miri does detect this. :)
```rust
error: Undefined Behavior: unwinding past the topmost frame of the stack
  --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:43:1
   |
43 | / fn lang_start<T: crate::process::Termination + 'static>(
44 | |     main: fn() -> T,
45 | |     argc: isize,
46 | |     argv: *const *const u8,
...  |
52 | |     )
53 | | }
   | |_^ unwinding past the topmost frame of the stack
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
           
   = note: inside `std::rt::lang_start::<()>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:43:1

error: aborting due to previous error
```
