### ISSUE TITLE
`rustdoc` ICE: Unexpected result when selecting <trait>

### ISSUE THREAD

**Issue by jmaargh** [rust-lang/rust#86182]
### Code

Check out https://github.com/jmaargh/imgui-rs/tree/6b92da44cf43a4afeacb78934827c8b9ce218fa0 and run `cargo doc` (apologies for non-minimal example, but I don't have time to narrow it down right now - especially as it seems to be due to some verbose trait bounds I'm using - and I want to report before I forget).

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.52.1
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'Unexpected result when selecting OwningRenderer<G, T, S, C> Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { substs: [G], item_def_id: DefId(31:4660 ~ glow[7586]::HasContext::Buffer) }, _)), depth=2)', compiler/rustc_trait_selection/src/traits/auto_trait.rs:770:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `imgui-glow-renderer`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name imgui_glow_renderer imgui-glow-renderer/src/lib.rs -o /home/john-mark/repos/imgui-rs/target/doc --cfg 'feature="bind_sampler_support"' --cfg 'feature="bind_vertex_array_support"' --cfg 'feature="clip_origin_support"' --cfg 'feature="default"' --cfg 'feature="gl_extensions_support"' --cfg 'feature="polygon_mode_support"' --cfg 'feature="primitive_restart_support"' --cfg 'feature="vertex_offset_support"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/home/john-mark/repos/imgui-rs/target/debug/deps --extern glow=/home/john-mark/repos/imgui-rs/target/debug/deps/libglow-8894152216d955ec.rmeta --extern imgui=/home/john-mark/repos/imgui-rs/target/debug/deps/libimgui-ba73fe0f5ea74e6b.rmeta --extern memoffset=/home/john-mark/repos/imgui-rs/target/debug/deps/libmemoffset-a0f3543968cf1097.rmeta --crate-version 0.7.0` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: rustc_trait_selection::traits::auto_trait::AutoTraitFinder::evaluate_nested_obligations
   3: rustc_trait_selection::traits::auto_trait::AutoTraitFinder::evaluate_predicates
   4: rustc_infer::infer::InferCtxtBuilder::enter
   5: rustc_trait_selection::traits::auto_trait::AutoTraitFinder::find_auto_trait_generics
   6: rustdoc::clean::auto_trait::AutoTraitFinder::generate_for_trait
   7: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   8: rustdoc::clean::auto_trait::AutoTraitFinder::get_auto_trait_impls
   9: rustdoc::clean::utils::get_auto_trait_and_blanket_impls
  10: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::fold::DocFolder>::fold_item
  11: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  12: rustdoc::fold::DocFolder::fold_inner_recur
  13: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector as rustdoc::fold::DocFolder>::fold_item
  14: rustdoc::passes::collect_trait_impls::collect_trait_impls
  15: rustdoc::core::run_global_ctxt
  16: rustc_interface::passes::QueryContext::enter
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: rustc_interface::interface::create_compiler_and_run
  20: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by jmaargh** [comment]
This appears to have been fixed.
