### ISSUE TITLE
Error while using rust-fuzz on a project that depends on rustc_ap_rustc-span

### ISSUE THREAD

**Issue by david-pikas** [rust-lang/rust#86216]
### Code

I encontered this issue while trying to use `rust-fuzz` on a project that depends on the crate `rustc_ap_rustc-span`. A minimal repo with this bug can be found [here](https://github.com/david-pikas/rust_span_fuzz_failure)

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (eab201df7 2021-06-09)
binary: rustc
commit-hash: eab201df7028ebb6812c0b1a01702ac6ecfcceed
commit-date: 2021-06-09
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
   Compiling rustc-ap-rustc_span v723.0.0
   Compiling rust_span_fuzz_failure v0.1.0 (/home/dave/Documents/rust_span_fuzz_failure)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorReported', compiler/rustc_mir/src/monomorphize/collector.rs:1322:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (eab201df7 2021-06-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C opt-level=3 -C embed-bitcode=no -C passes=sancov -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -C link-dead-code -C llvm-args=-sanitizer-coverage-stack-depth -C debug-assertions -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: Encountered error `Unimplemented` selecting `Binder(<hygiene::ExpnData as std::cmp::PartialEq>, [])` during codegen
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:68:32

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1023:13
stack backtrace:
   0:     0x7f8fcd85af80 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f8fcd85af80 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8fcd85af80 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8fcd85af80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f8fcd8c89dc - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/core/src/fmt/mod.rs:1110:17
   5:     0x7f8fcd84c955 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/io/mod.rs:1588:15
   6:     0x7f8fcd85eddb - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f8fcd85eddb - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f8fcd85eddb - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:208:50
   9:     0x7f8fcd85e8b1 - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:225:9
  10:     0x7f8fce066ced - rustc_driver::report_ice::hfad451a47de91ee8
  11:     0x7f8fc0e81ba9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4b9c3ad663c43d82
  12:     0x7f8fc0e7710a - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::he7365af0e0b3d33d
  13:     0x7f8fcd85f5e6 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:626:17
  14:     0x7f8fcd85f0c7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:519:13
  15:     0x7f8fcd85b45c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7f8fcd85f029 - rust_begin_unwind
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:515:5
  17:     0x7f8fcd827eeb - std::panicking::begin_panic_fmt::h2db7e4060dc9c373
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:457:5
  18:     0x7f8fd0444aa9 - rustc_errors::HandlerInner::flush_delayed::hae29d8c7bf0ae2bd
  19:     0x7f8fd044355d - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h3414f28393187f8f
  20:     0x7f8fcfacaee6 - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::hcc69453e55348989
  21:     0x7f8fcfacd75e - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h86919fca460adbce
  22:     0x7f8fcfad234d - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::he551afb833930fee
  23:     0x7f8fcfad1ba4 - rustc_span::with_source_map::h9f9411a16a095f07
  24:     0x7f8fcfad3980 - rustc_interface::interface::create_compiler_and_run::h490b97e4c4015303
  25:     0x7f8fcfad1cb9 - rustc_span::with_session_globals::he4f45813d9f58793
  26:     0x7f8fcfaf76af - std::sys_common::backtrace::__rust_begin_short_backtrace::h6681b13d784a0ebb
  27:     0x7f8fcfaca305 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h912f30352946e4b4
  28:     0x7f8fcd86bad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd1f9b751a68dd2ac
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/alloc/src/boxed.rs:1575:9
  29:     0x7f8fcd86bad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h22d732940e85619f
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/alloc/src/boxed.rs:1575:9
  30:     0x7f8fcd86bad7 - std::sys::unix::thread::Thread::new::thread_start::h04c7a9e17ed1032c
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys/unix/thread.rs:71:17
  31:     0x7f8fcd7ac259 - start_thread
  32:     0x7f8fcd6c15e3 - __GI___clone
  33:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (eab201df7 2021-06-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C opt-level=3 -C embed-bitcode=no -C passes=sancov -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -C link-dead-code -C llvm-args=-sanitizer-coverage-stack-depth -C debug-assertions -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `rustc-ap-rustc_span`

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_ap_rustc_span --edition=2018 /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_span-723.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=f2596c496023db9a -C extra-filename=-f2596c496023db9a --out-dir /home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/release/deps --extern cfg_if=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libcfg_if-bfddd7c2f68008e4.rmeta --extern md5=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libmd5-b97813422ad8c177.rmeta --extern rustc_arena=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_arena-53ef577baead45b2.rmeta --extern rustc_data_structures=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_data_structures-bc41b0a72ad19009.rmeta --extern rustc_index=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_index-944346f1723b9f38.rmeta --extern rustc_macros=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/release/deps/librustc_ap_rustc_macros-b59c777896e26120.so --extern rustc_serialize=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_serialize-4eff6da6fa47a3d8.rmeta --extern scoped_tls=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libscoped_tls-0544dc31e93bd078.rmeta --extern sha1=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libsha1-a9fb90785d23d1f2.rmeta --extern sha2=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libsha2-537b9bc5ba272acb.rmeta --extern tracing=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libtracing-f273b01f3d83e7c1.rmeta --extern unicode_width=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libunicode_width-d0839f5e5cd9eccf.rmeta --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-trace-compares -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Clink-dead-code -Zsanitizer=address -Cllvm-args=-sanitizer-coverage-stack-depth -Cdebug-assertions -C codegen-units=1 -L native=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/build/psm-5d8c23ba5c20aeab/out` (signal: 4, SIGILL: illegal instruction)
Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "/home/dave/Documents/rust_span_fuzz_failure/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--bin" "fuzz_target_1"

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling rustc-ap-rustc_span v723.0.0
   Compiling rust_span_fuzz_failure v0.1.0 (/home/dave/Documents/rust_span_fuzz_failure)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorReported', compiler/rustc_mir/src/monomorphize/collector.rs:1322:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (eab201df7 2021-06-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C opt-level=3 -C embed-bitcode=no -C passes=sancov -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -C link-dead-code -C llvm-args=-sanitizer-coverage-stack-depth -C debug-assertions -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: Encountered error `Unimplemented` selecting `Binder(<hygiene::ExpnData as std::cmp::PartialEq>, [])` during codegen
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:68:32

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1023:13
stack backtrace:
   0:     0x7f6eede91f80 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f6eede91f80 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6eede91f80 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f6eede91f80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f6eedeff9dc - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/core/src/fmt/mod.rs:1110:17
   5:     0x7f6eede83955 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/io/mod.rs:1588:15
   6:     0x7f6eede95ddb - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f6eede95ddb - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f6eede95ddb - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:208:50
   9:     0x7f6eede958b1 - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:225:9
  10:     0x7f6eee69dced - rustc_driver::report_ice::hfad451a47de91ee8
  11:     0x7f6ee1497ba9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4b9c3ad663c43d82
  12:     0x7f6ee148d10a - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::he7365af0e0b3d33d
  13:     0x7f6eede965e6 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:626:17
  14:     0x7f6eede960c7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:519:13
  15:     0x7f6eede9245c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7f6eede96029 - rust_begin_unwind
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:515:5
  17:     0x7f6eede5eeeb - std::panicking::begin_panic_fmt::h2db7e4060dc9c373
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/panicking.rs:457:5
  18:     0x7f6ef0a7baa9 - rustc_errors::HandlerInner::flush_delayed::hae29d8c7bf0ae2bd
  19:     0x7f6ef0a7a55d - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h3414f28393187f8f
  20:     0x7f6ef0101ee6 - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::hcc69453e55348989
  21:     0x7f6ef010475e - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h86919fca460adbce
  22:     0x7f6ef010934d - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::he551afb833930fee
  23:     0x7f6ef0108ba4 - rustc_span::with_source_map::h9f9411a16a095f07
  24:     0x7f6ef010a980 - rustc_interface::interface::create_compiler_and_run::h490b97e4c4015303
  25:     0x7f6ef0108cb9 - rustc_span::with_session_globals::he4f45813d9f58793
  26:     0x7f6ef012e6af - std::sys_common::backtrace::__rust_begin_short_backtrace::h6681b13d784a0ebb
  27:     0x7f6ef0101305 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h912f30352946e4b4
  28:     0x7f6eedea2ad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd1f9b751a68dd2ac
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/alloc/src/boxed.rs:1575:9
  29:     0x7f6eedea2ad7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h22d732940e85619f
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/alloc/src/boxed.rs:1575:9
  30:     0x7f6eedea2ad7 - std::sys::unix::thread::Thread::new::thread_start::h04c7a9e17ed1032c
                               at /rustc/eab201df7028ebb6812c0b1a01702ac6ecfcceed/library/std/src/sys/unix/thread.rs:71:17
  31:     0x7f6eedde3259 - start_thread
  32:     0x7f6eedcf85e3 - __GI___clone
  33:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (eab201df7 2021-06-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C opt-level=3 -C embed-bitcode=no -C passes=sancov -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -C link-dead-code -C llvm-args=-sanitizer-coverage-stack-depth -C debug-assertions -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `rustc-ap-rustc_span`

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_ap_rustc_span --edition=2018 /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_span-723.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=f2596c496023db9a -C extra-filename=-f2596c496023db9a --out-dir /home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/release/deps --extern cfg_if=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libcfg_if-bfddd7c2f68008e4.rmeta --extern md5=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libmd5-b97813422ad8c177.rmeta --extern rustc_arena=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_arena-53ef577baead45b2.rmeta --extern rustc_data_structures=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_data_structures-bc41b0a72ad19009.rmeta --extern rustc_index=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_index-944346f1723b9f38.rmeta --extern rustc_macros=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/release/deps/librustc_ap_rustc_macros-b59c777896e26120.so --extern rustc_serialize=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/librustc_ap_rustc_serialize-4eff6da6fa47a3d8.rmeta --extern scoped_tls=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libscoped_tls-0544dc31e93bd078.rmeta --extern sha1=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libsha1-a9fb90785d23d1f2.rmeta --extern sha2=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libsha2-537b9bc5ba272acb.rmeta --extern tracing=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libtracing-f273b01f3d83e7c1.rmeta --extern unicode_width=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/deps/libunicode_width-d0839f5e5cd9eccf.rmeta --cap-lints allow --cfg fuzzing -Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-trace-compares -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table -Clink-dead-code -Zsanitizer=address -Cllvm-args=-sanitizer-coverage-stack-depth -Cdebug-assertions -C codegen-units=1 -L native=/home/dave/Documents/rust_span_fuzz_failure/fuzz/target/x86_64-unknown-linux-gnu/release/build/psm-5d8c23ba5c20aeab/out` (signal: 4, SIGILL: illegal instruction)
Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "/home/dave/Documents/rust_span_fuzz_failure/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--bin" "fuzz_target_1"
```

</p>
</details>

**Comment by hellow554** [comment]
Your repo link is broken. Can you fix that please?

**Comment by david-pikas** [comment]
Oops, I had the repo set to private by accident. It should work now!

**Comment by hellow554** [comment]
me neither so probably a dependency updated and now everything works? I'm not entirely sure.

But nethertheless, I think this can be closeed...
