### ISSUE TITLE
Possible user error but complier error occurs when setting ptr width in custom target to 32bit instead of 64bit

### ISSUE THREAD

**Issue by stillbeingnick** [rust-lang/rust#86496]
### Error info

Hello rust crew! 

This could be my own fault but I was not able to find documentation on any other way to do this.

What I am trying to do:
    I am writing a pretty simple kernel that is loaded from 32bit protected mode on a virtual qemu x86_64 system. The kernel will load and execute just fine until I add a loop. I have tried both
```Rust
for x in 0..10 {

}
```
and I have also tried resorting to a 
```Rust
let mut i  = 0;
while i < 10 {
   i += 1
}
```
Anytime I add a loop to any function the qemu system will get stuck in a boot loop.

However 
```rust
loop{}
```
works just fine

Before adjusting the target I was able to narrow the issue down to a 64bit return address being set on the stack and since the system is running in 32bit mode I think the stack is being corrupted and omiting the high bits of the register.

After stepping through each instruction with gdb I was able to confirm this by watching the stack morph.

This is what lead me to changing the custom target "data-specification" and adjusting the pointer size from 64bit to 32bit according to llvm docs.

When I set the pointer size abi size and idx size to 32 I get an llvm error.

I have not tried adding to the boot loader to change into long mode (which I suspect will fix everything).

as a side note it also seems I cant set the target type or arch to i686 (for 32 bit) rustc tells me that doesnt exist.

This could absolutely be my fault in messing with too many things to shoehorn the rs to 32bit mode but It would be nice to see if this is the case.

I am going to experiment to see if I can write my own loop functions that are 32bit compatible and revert the custom target back to 64bit ptr width

Thank you all!

### Code

```Rust
  #![feature(lang_items, core_intrinsics, core_panic)]
  #![feature(start)]
  #![no_std]
  use core::panic::PanicInfo;
  use core::intrinsics::abort;

  #[no_mangle]
  pub extern fn main() {
      //add char to piece of video mem
      let x_char = 'X';
      let col = 0x0f;
      //grab the first char cell and color cell of video mem
      let video_mem = 0xb8000usize;
      let color_mem = 0xb8001usize;
      //create mut ptr to it
      let vid_1 = video_mem as *mut char;
      let color_1 = color_mem as *mut i32;
      //fn for test loop
      test_loop();
      //set x in vid mem
      unsafe {
          *vid_1 = x_char;
          *color_1 = col;
      }
      //loop till the world ends
      loop{}
  }
  //rlibc copy
  #[no_mangle]
  pub unsafe extern fn memcpy(dest: *mut u8, src: *const u8, n: usize) -> *mut u8{
      let mut i = 0;
      while i < n {
          *dest.offset(i as isize) = *src.offset(i as isize);
          i += 1;
      }
      dest
  }
  #[no_mangle]
  pub unsafe extern fn memcmp(s1: *const u8, s2: *const u8, n: usize) -> i32{
      let mut i = 0;
      while i < n {
          let a = *s1.offset(i as isize);
          let b = *s2.offset(i as isize);
          if a != b {
              return a as i32 - b as i32;
          }
          i += 1;
      }
      0
  }
  #[no_mangle]
  pub unsafe extern fn memset(s: *mut u8, c: i32, n: usize) -> *mut u8{
      let mut i = 0;
      while i < n {
          *s.offset(i as isize) = c as u8;
          i += 1;
      }
      s
  }
  fn test_loop(){
     for x in 0..10{

      }
  }
  #[panic_handler]
  fn panic(_panic: &PanicInfo<'_>) -> ! {
      loop{ abort() }
  }
```

### Custom Target Spec
```json
{
  "llvm-target": "x86_64-unknown-none",
  "data-layout": "e-m:e-i64:64-f80:128-n8:16:32-S128-p0:32:64:32",
  "linker-flavor": "ld",
  "target-endian": "little",
  "target-pointer-width": "32",
  "target-c-int-width": "32",
  "arch": "x86_64",
  "os": "none",
  "disable-redzone": true,
  "features": "-mmx,-sse,+soft-float"
}
```
### Custom Target Spec (this one compiles)
```json
{
  "llvm-target": "x86_64-unknown-none",
  "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
  "linker-flavor": "ld",
  "target-endian": "little",
  "target-pointer-width": "64",
  "target-c-int-width": "32",
  "arch": "x86_64",
  "os": "none",
  "disable-redzone": true,
  "features": "-mmx,-sse,+soft-float"
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (149f4836d 2021-06-17)
binary: rustc
commit-hash: 149f4836dd6d9e789a26dca16dc034588866894e
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
~/personal/development/os/kernel/rust
```

### Error output

```
cargo build -Z build-std --target kernel-os.json --verbose
   Compiling core v0.0.0 (/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
       Fresh cc v1.0.68
     Running `rustc --crate-name core --edition=2018 /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=51b123216f6a4d0d -C extra-filename=-51b123216f6a4d0d --out-dir /home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps --target /home/user/personal/development/os/kernel/rust/kernel-os.json -Z force-unstable-if-unmarked -L dependency=/home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps -L dependency=/home/user/personal/development/os/kernel/rust/target/debug/deps --cap-lints allow`
   Compiling rustc-std-workspace-core v1.99.0 (/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
     Running `rustc --crate-name rustc_std_workspace_core --edition=2018 /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=59540977353716dd -C extra-filename=-59540977353716dd --out-dir /home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps --target /home/user/personal/development/os/kernel/rust/kernel-os.json -Z force-unstable-if-unmarked -L dependency=/home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps -L dependency=/home/user/personal/development/os/kernel/rust/target/debug/deps --extern core=/home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps/libcore-51b123216f6a4d0d.rmeta --cap-lints allow`
LLVM ERROR: Cannot select: 0x7fac71d99000: ch = brind 0x7fac71d99270:1, 0x7fac71d99068
  0x7fac71d99068: i32 = add 0x7fac71d99270, 0x7fac71d99680
    0x7fac71d99270: i32,ch = load<(load 4 from jump-table)> 0x7fac71d99750:1, 0x7fac71d990d0, undef:i32
      0x7fac71d990d0: i32 = add 0x7fac71d99478, 0x7fac71d99680
        0x7fac71d99478: i32 = shl 0x7fac71d99750, Constant:i8<2>
          0x7fac71d99750: i32,ch = CopyFromReg 0x7fac71cb63e8, Register:i32 %2
            0x7fac71d991a0: i32 = Register %2
          0x7fac71d99618: i8 = Constant<2>
        0x7fac71d99680: i32 = X86ISD::WrapperRIP TargetJumpTable:i32<0>
          0x7fac71d99340: i32 = TargetJumpTable<0>
      0x7fac71d99208: i32 = undef
    0x7fac71d99680: i32 = X86ISD::WrapperRIP TargetJumpTable:i32<0>
      0x7fac71d99340: i32 = TargetJumpTable<0>
In function: _ZN4core3num5error13ParseIntError13__description17he098af9a8c47c09fE
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2018 /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=51b123216f6a4d0d -C extra-filename=-51b123216f6a4d0d --out-dir /home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps --target /home/user/personal/development/os/kernel/rust/kernel-os.json -Z force-unstable-if-unmarked -L dependency=/home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps -L dependency=/home/user/personal/development/os/kernel/rust/target/debug/deps --cap-lints allow` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
~/personal/development/os/kernel/rust
❯ cargo build -Z build-std --target kernel-os.json --verbose
   Compiling core v0.0.0 (/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
       Fresh cc v1.0.68
     Running `rustc --crate-name core --edition=2018 /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=51b123216f6a4d0d -C extra-filename=-51b123216f6a4d0d --out-dir /home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps --target /home/uset/personal/development/os/kernel/rust/kernel-os.json -Z force-unstable-if-unmarked -L dependency=/home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps -L dependency=/home/user/personal/development/os/kernel/rust/target/debug/deps --cap-lints allow`
thread 'rustc' panicked at 'nonscalar layout for layout_scalar_valid_range type ptr::non_null::NonNull: Layout {
    fields: Arbitrary {
        offsets: [
            Size {
                raw: 0,
            },
        ],
        memory_index: [
            0,
        ],
    },
    variants: Single {
        index: 0,
    },
    abi: Aggregate {
        sized: true,
    },
    largest_niche: None,
    align: AbiAndPrefAlign {
        abi: Align {
            pow2: 3,
        },
        pref: Align {
            pow2: 3,
        },
    },
    size: Size {
        raw: 8,
    },
}', compiler/rustc_middle/src/ty/layout.rs:960:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (149f4836d 2021-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z force-unstable-if-unmarked -C panic=abort -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [layout_raw] computing layout of `ptr::non_null::NonNull<u8>`
#1 [layout_raw] computing layout of `slice::iter::Iter<u8>`
end of query stack
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2018 /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=51b123216f6a4d0d -C extra-filename=-51b123216f6a4d0d --out-dir /home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps --target /home/user/personal/development/os/kernel/rust/kernel-os.json -Z force-unstable-if-unmarked -L dependency=/home/user/personal/development/os/kernel/rust/target/kernel-os/debug/deps -L dependency=/home/user/personal/development/os/kernel/rust/target/debug/deps --cap-lints allow` (exit status: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/149f4836dd6d9e789a26dca16dc034588866894e/library/std/src/panicking.rs:457:5
   2: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
   3: rustc_middle::ty::layout::layout_raw
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_raw
   6: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: core::iter::adapters::process_results
  10: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
  11: rustc_middle::ty::layout::layout_raw
  12: rustc_query_system::query::plumbing::get_query_impl
  13: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_raw
  14: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  17: core::iter::adapters::process_results
  18: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
  19: rustc_middle::ty::layout::layout_raw
  20: rustc_query_system::query::plumbing::get_query_impl
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_raw
  22: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  25: core::iter::adapters::process_results
  26: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
  27: rustc_middle::ty::layout::layout_raw
  28: rustc_query_system::query::plumbing::get_query_impl
  29: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::layout_raw
  30: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  31: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  32: rustc_mir::transform::run_passes
  33: rustc_mir::transform::optimized_mir
  34: rustc_query_system::query::plumbing::get_query_impl
  35: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::optimized_mir
  36: rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root
  37: rustc_metadata::rmeta::encoder::encode_metadata_impl
  38: rustc_data_structures::sync::join
  39: rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc_middle::middle::cstore::CrateStore for rustc_metadata::creader::CStore>::encode_metadata
  40: rustc_middle::ty::context::TyCtxt::encode_metadata
  41: rustc_interface::passes::QueryContext::enter
  42: rustc_interface::queries::Queries::ongoing_codegen
  43: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  44: rustc_span::with_source_map
  45: rustc_interface::interface::create_compiler_and_run
  46: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (149f4836d 2021-06-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z force-unstable-if-unmarked -C panic=abort -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [layout_raw] computing layout of `ptr::non_null::NonNull<u8>`
#1 [layout_raw] computing layout of `slice::iter::Iter<u8>`
#2 [layout_raw] computing layout of `option::Option<slice::iter::Iter<u8>>`
#3 [layout_raw] computing layout of `iter::adapters::chain::Chain<slice::iter::Iter<u8>, slice::iter::Iter<u8>>`
#4 [optimized_mir] optimizing MIR for `num::dec2flt::algorithm::fast_path`
end of query stack
error: could not compile `core`
```

</p>
</details>

**Comment by jyn514** [comment]
I don't think this is a compiler bug. It can't know if target-specs are accurate or not, you as the target author are guaranteeing that it's right; if it's not then it's your responsibility to fix it.

**Comment by stillbeingnick** [comment]
> I don't think this is a compiler bug. It can't know if target-specs are accurate or not, you as the target author are guaranteeing that it's right; if it's not then it's your responsibility to fix it.

More playing around this is not a compiler error this is my own config being off 

```json
{
  "llvm-target": "i686-unknown-none",
  "data-layout": "e-m:e-i32:32-f80:128-n8:16:32-S128-p:32:32",
  "arch": "x86",
  "target-endian": "little",
  "target-pointer-width": "32",
  "target-c-int-width": "32",
  "os": "none",
  "executables": true,
  "linker-flavor": "ld",
  "panic-strategy": "abort",
  "disable-redzone": true,
  "features": "+soft-float,+sse"
}
```
The above config works with the compiler

thanks for the quick response @jyn514!

closing this one down
