### ISSUE TITLE
OutputTypeParameterMismatch error under -Clink-dead-code

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#86703]
### Code

I haven't been able to minimize this but the two tests in https://github.com/Manishearth/icu4x/blob/yoke-ice/utils/yoke/src/yoke.rs#L474-L551 fail when run under `-Clink-dead-code`

Steps:
 - check out the `yoke-ice` branch of https://github.com/Manishearth/icu4x
 - `cd utils/yoke`
 - `RUSTDOCFLAGS="-Clink-dead-code" cargo +nightly test`

Adding code that makes use of the functions defined in these tests does not change anything, e.g. the function in the first test is not being called, but if you add code that calls it like below, the ICE still happens. I'm not sure as to what role `-Clink-dead-code` has here.

```rust
let rc: Rc<[u8]> = Rc::from("hello".as_bytes());
let yoke: Yoke<&'static str, Rc<[u8]>> = Yoke::attach_to_cart_badly(rc, |rc| std::str::from_utf8(&rc).unwrap());
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (e8cb1a4a5 2021-06-27)
binary: rustc
commit-hash: e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5
commit-date: 2021-06-27
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1

```

### Error output

```
---- src/yoke.rs - yoke::Yoke<Y, C>::project (line 500) stdout ----
error: internal compiler error: compiler/rustc_trait_selection/src/traits/codegen.rs:78:17: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@src/yoke.rs:16:17: 16:38] as std::ops::FnMut<(&<main::_doctest_main_src_yoke_rs_500_0::Bar as yoke::Yokeable<'_>>::Output, &())>>, [Region(BrAnon(0))]), Binder(<[closure@src/yoke.rs:16:17: 16:38] as std::ops::FnMut<(&main::_doctest_main_src_yoke_rs_500_0::Bar, &())>>, []), Sorts(ExpectedFound { expected: main::_doctest_main_src_yoke_rs_500_0::Bar, found: <main::_doctest_main_src_yoke_rs_500_0::Bar as yoke::Yokeable<'_>>::Output }))` selecting `Binder(<[closure@src/yoke.rs:16:17: 16:38] as std::ops::FnMut<(&main::_doctest_main_src_yoke_rs_500_0::Bar, &())>>, [])` during codegen

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1007:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (e8cb1a4a5 2021-06-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C embed-bitcode=no -C link-dead-code --crate-type bin

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::ops::FnMut` fulfills its obligations
#1 [resolve_instance] resolving instance `<[closure@src/yoke.rs:16:17: 16:38] as std::ops::FnMut<(&main::_doctest_main_src_yoke_rs_500_0::Bar, &())>>::call_mut`
end of query stack
error: aborting due to previous error


```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_infer::infer::InferCtxtBuilder::enter
   8: rustc_trait_selection::traits::codegen::codegen_fulfill_obligation
   9: rustc_query_system::query::plumbing::get_query_impl
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::codegen_fulfill_obligation
  11: rustc_ty_utils::instance::inner_resolve_instance
  12: rustc_ty_utils::instance::resolve_instance
  13: rustc_query_system::query::plumbing::get_query_impl
  14: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  15: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  16: rustc_middle::ty::instance::Instance::resolve
  17: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  18: rustc_mir::monomorphize::collector::collect_neighbours
  19: rustc_mir::monomorphize::collector::collect_items_rec
  20: rustc_mir::monomorphize::collector::collect_items_rec
  21: rustc_session::utils::<impl rustc_session::session::Session>::time
  22: rustc_mir::monomorphize::collector::collect_crate_mono_items
  23: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  24: rustc_query_system::query::plumbing::get_query_impl
  25: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items
  26: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  27: rustc_interface::passes::QueryContext::enter
  28: rustc_interface::queries::Queries::ongoing_codegen
  29: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  30: rustc_span::with_source_map
  31: rustc_interface::interface::create_compiler_and_run
  32: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by Manishearth** [comment]
This _may_ be related to https://github.com/rust-lang/rust/issues/86702

**Comment by Manishearth** [comment]
The weird thing is that even if I make sure all of the functions are used, I still do not get the error without `-C link-dead-code`, and still get the error with `-C link-dead-code`

**Comment by Manishearth** [comment]
Jonas says this might be https://github.com/rust-lang/rust/issues/62529

**Comment by Manishearth** [comment]
The ICE here is fixed by https://github.com/rust-lang/rust/pull/85499, however it gets replaced with the following (incorrect) error:

```rust
error: implementation of `Yokeable` is not general enough
  --> foo.rs:31:7
   |
31 |     y.project(move |yk, _| yk.as_bytes())
   |       ^^^^^^^ implementation of `Yokeable` is not general enough
   |
   = note: `&[u8]` must implement `Yokeable<'0>`, for any lifetime `'0`...
   = note: ...but `Yokeable<'_>` is actually implemented for the type `&'static [u8]`
```

**Comment by hellow554** [comment]
Reduced to this:

```rust
trait Yokeable<'a> {
    type Output: 'a;
}

fn project<'this>(_: for<'a> fn(<() as Yokeable<'a>>::Output)) {}

impl<'a> Yokeable<'a> for () {
    type Output = ();
}

fn main() {
    project(|_| {});
}
```

looks related at least

**Comment by lqd** [comment]
The subtlety with reducing this is that it quickly falls into an actual duplicate of #62529, losing what made it slightly different under #85499. That PR will successfully compile this reduction, but not the OP.

**Comment by hellow554** [comment]
@lqd you're right. Here's what needs to be done, to be able to trigger the ICE with `-C link-dead-code` again:

```rust
fn crash() {
    project(|_| {});
}

fn main() {}
```

which seems plausible, because that's what `link-dead-code` is supposed to do, right?
Is that enough or am I missing something?

**Comment by lqd** [comment]
I guess it depends on your reduction goals :) 

If you want the minimal ICE regardless of the intent of the OP, that's valuable for tests and debugging. 

Similarly valuable, we could reduce to try to understand why the OP doesn't compile, [even without the ICE](https://github.com/rust-lang/rust/issues/86703#issuecomment-870183743): there could be 
- an existing rustc bug that manifests today as this ICE but is surfaced as an error with #85499
- or something unclear in documentation or diagnostics about why this shouldn't compile
- or an issue in #85499 itself. 

This would likely require reducing using the CI artifacts of that PR.

**Comment by jackh726** [comment]
Here is a smaller reproduction of this that passes on current master but fails in #85499. It's `no_core` and doesn't need `-C link-dead-code`

```rust
// build-pass

#![feature(no_core)]

pub trait Yokeable<'a> {
    type Output: 'a;
}

pub struct Yoke<Y: for<'a> Yokeable<'a>> {
    _yokeable: Y,
}

impl<Y: for<'a> Yokeable<'a>> Yoke<Y> {
    pub fn project<'this, P>(
        &'this self,
        _f: for<'a> fn(&'this <Y as Yokeable<'a>>::Output, &'a ()) -> <P as Yokeable<'a>>::Output,
    ) -> Yoke<P>
    where
        P: for<'a> Yokeable<'a>,
    {
        unimplemented!()
    }
}

pub fn slice(y: Yoke<&'static ()>) -> Yoke<&'static ()> {
    y.project(move |yk, _| *yk)
}

impl<'a, T> Yokeable<'a> for &'static T {
    type Output = &'a T;
}

fn main() {}
```

**Comment by Manishearth** [comment]
I find the -Clink-dead-code to be an interesting part of the bug as well fwiw since i don't think we have bugs like that anywhere.

**Comment by Manishearth** [comment]
With the latest https://github.com/rust-lang/rust/pull/85499 I get the following bug:

```
error: internal compiler error: broken MIR in DefId(0:13 ~ rust_out[6150]::main::_doctest_main_src_yoke_rs_488_0::slice::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&[closure@src/yoke.rs:8:14: 8:40]==&[closure@src/yoke.rs:8:14: 8:40]` failed with `NoSolution`
 --> src/yoke.rs:493:14
  |
8 |    y.project(move |yk, _| yk.as_bytes())
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jackh726** [comment]
@Manishearth can you run with `-Z verbose`?

**Comment by Manishearth** [comment]
```
error: internal compiler error: broken MIR in DefId(0:27 ~ rust_out[6150]::main::_doctest_main_src_yoke_rs_500_0::project_string_1::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&'_#3r [main::_doctest_main_src_yoke_rs_500_0::project_string_1::{closure#0} closure_kind_ty=i8 closure_sig_as_fn_ptr_ty=for<'r> extern "rust-call" fn((&'_#1r main::_doctest_main_src_yoke_rs_500_0::Bar<ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) })>, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) ())) -> &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) str upvar_tys=()]==&'_#11r [main::_doctest_main_src_yoke_rs_500_0::project_string_1::{closure#0} closure_kind_ty=i8 closure_sig_as_fn_ptr_ty=for<'r> extern "rust-call" fn((&'_#12r main::_doctest_main_src_yoke_rs_500_0::Bar<ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) })>, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) ())) -> <&'_#13r str as yoke::Yokeable<ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) })>>::Output upvar_tys=()]` failed with `NoSolution`
```

**Comment by jackh726** [comment]
Okay, so looks like my minimization in https://github.com/rust-lang/rust/issues/86703#issuecomment-872361485 doesn't fully capture the issue (though that *did* fail and now doesn't).

Looking at the `-Z verbose` error output, it looks really similar. But I'm wondering if maybe the region variables aren't resolving the `ReErased` as they were.

@Manishearth do you think you can on getting a more minimized repro using #85499? Just getting it done to one file is enough for me to work with.

That being said, I'm tempted to let this slip through the PR if I can't figure out a quick and easy solution, given that this didn't come up in the crater run *and* this exact issue is "gated" behind an ICE right now anyways.

**Comment by lqd** [comment]
IIUC the minimized test in the OP ICEs similarly

**Comment by Manishearth** [comment]
@jackh726 The minimized tescase in my post, if you add a `fn main()` to it, errors with this:

```
error: internal compiler error: broken MIR in DefId(0:38 ~ bar[290d]::slice::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&'_#3r [slice::{closure#0} closure_kind_ty=i8 closure_sig_as_fn_ptr_ty=for<'r> extern "rust-call" fn((&'_#1r &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) str, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) ())) -> &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) [u8] upvar_tys=()]==&'_#11r [slice::{closure#0} closure_kind_ty=i8 closure_sig_as_fn_ptr_ty=for<'r> extern "rust-call" fn((&'_#12r &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) str, &ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) }) ())) -> <&'_#13r [u8] as Yokeable<ReLateBound(DebruijnIndex(0), BoundRegion { var: 0, kind: BrNamed('r) })>>::Output upvar_tys=()]` failed with `NoSolution`
  --> bar.rs:31:15
   |
31 |     y.project(move |yk, _| yk.as_bytes())
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27
```

`-Clink-dead-code` does not affect the error.


> That being said, I'm tempted to let this slip through the PR if I can't figure out a quick and easy solution, given that this didn't come up in the crater run _and_ this exact issue is "gated" behind an ICE right now anyways.

To be clear, this code [is in a published crate](https://docs.rs/yoke/0.2.2/yoke/), I've preemptively disabled the test because we run coverage tests and they fail under `-Clink-dead-code`

Also, your PR causes another regression in the same crate:

<details>
```
[10:00:02] मanishearth@manishearth-glaptop ~/sand O_o 
$ cargo clone yoke
    Updating crates.io index
cd y       Fetch [                                                       ]   0.00%                                                       Downloaded yoke v0.2.2
  Downloaded 1 crate (19.2 KB) in 0.86s
[10:00:08] मanishearth@manishearth-glaptop ~/sand ^_^ 
$ cd yoke
[10:00:09] मanishearth@manishearth-glaptop ~/sand/yoke ^_^ 
$ cargo +icefix test
    Updating crates.io index
   Compiling serde v1.0.126
   Compiling stable_deref_trait v1.2.0
   Compiling bincode v1.3.3
   Compiling yoke v0.2.2 (/home/manishearth/sand/yoke)
    Finished test [unoptimized + debuginfo] target(s) in 4.30s
     Running unittests (target/debug/deps/yoke-04df88eb61fc288e)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests yoke

running 25 tests
test src/trait_hack.rs - trait_hack (line 78) ... ok
test src/trait_hack.rs - trait_hack (line 31) - compile fail ... FAILED
test src/yoke.rs - yoke::Yoke<Y, C>::project (line 502) ... ignored
test src/yoke.rs - yoke::Yoke<Y, C>::project (line 515) ... ignored
test src/trait_hack.rs - trait_hack (line 141) ... ok
test src/yoke.rs - yoke::Yoke<Y, ()>::new_always_owned (line 372) ... ok
test src/yoke.rs - yoke::Yoke<Y, C>::into_backing_cart (line 225) ... ok
test src/yoke.rs - yoke::Yoke (line 34) ... ok
test src/yoke.rs - yoke::Yoke<Y, C>::get (line 183) ... ok
test src/yoke.rs - yoke::Yoke<Y, C>::attach_to_cart_badly (line 108) ... ok
test src/yoke.rs - yoke::_ (line 668) - compile fail ... ok
test src/yoke.rs - yoke::_ (line 681) - compile fail ... ok
test src/yoke.rs - yoke::_ (line 694) - compile fail ... ok
test src/yokeable.rs - yokeable::Yokeable::transform_mut (line 140) - compile fail ... ok
test src/yokeable.rs - yokeable::Yokeable::transform_mut (line 163) - compile fail ... ok
test src/yoke.rs - yoke::Yoke<Y, C>::into_backing_cart (line 242) ... ok
test src/yoke.rs - yoke::Yoke<Y, C>::try_attach_to_cart_badly (line 148) ... FAILED
test src/yokeable.rs - yokeable::Yokeable::transform_mut (line 213) ... ok
test src/yokeable.rs - yokeable::Yokeable (line 46) ... ok
test src/yoke.rs - yoke::Yoke<Y, Option<C>>::new_owned (line 402) ... ok
test src/zero_copy_from.rs - zero_copy_from::Yoke<Y, &'b C>::attach_to_borrowed_cart (line 98) ... ok
test src/yoke.rs - yoke::Yoke<Y, C>::with_mut (line 278) ... ok
test src/zero_copy_from.rs - zero_copy_from::Yoke<Y, Box<C>>::attach_to_box_cart (line 126) ... ok
test src/zero_copy_from.rs - zero_copy_from::ZeroCopyFrom (line 31) ... ok
test src/zero_copy_from.rs - zero_copy_from::Yoke<Y, Rc<C>>::attach_to_rc_cart (line 156) ... ok

failures:

---- src/trait_hack.rs - trait_hack (line 31) stdout ----
Test compiled successfully, but it's marked `compile_fail`.
---- src/yoke.rs - yoke::Yoke<Y, C>::try_attach_to_cart_badly (line 148) stdout ----
error: internal compiler error: broken MIR in DefId(0:19 ~ rust_out[6150]::main::_doctest_main_src_yoke_rs_148_0::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&[closure@src/yoke.rs:10:40: 12:6]==&[closure@src/yoke.rs:10:40: 12:6]` failed with `NoSolution`
  --> src/yoke.rs:155:40
   |
10 |       Yoke::try_attach_to_cart_badly(rc, |data: &[u8]| {
   |  ________________________________________^
11 | |         bincode::deserialize(data)
12 | |     });
   | |_____^
   |
   = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (a264c0e92 2021-07-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C embed-bitcode=no --crate-type bin

query stack during panic:
end of query stack
Couldn't compile the test.

failures:
    src/trait_hack.rs - trait_hack (line 31)
    src/yoke.rs - yoke::Yoke<Y, C>::try_attach_to_cart_badly (line 148)

test result: FAILED. 21 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 1.45s

error: test failed, to rerun pass '--doc'
```
</details>

**Comment by jackh726** [comment]
Okay, I'll look into it.

<details>
<summary>no_core version of the repro</summary>

```rust
// build-pass
// compile-flags: -Z verbose

#![feature(no_core)]
#[no_core]

pub trait Borrow<Borrowed: ?Sized> {
    fn borrow(&self) -> &Borrowed;
}

pub trait ToOwned {
    type Owned: Borrow<Self>;
    fn to_owned(&self) -> Self::Owned;
}

pub enum Cow<'a, B: ?Sized + 'a>
where
    B: ToOwned,
{
    Borrowed(&'a B),
    Owned(<B as ToOwned>::Owned),
}

pub struct Rc<T: ?Sized> {
    _t: Box<T>,
}

pub unsafe trait Yokeable<'a>: 'static {
    type Output: 'a;
}

pub struct Yoke<Y: for<'a> Yokeable<'a>, C> {
    // must be the first field for drop order
    // this will have a 'static lifetime parameter, that parameter is a lie
    yokeable: Y,
    cart: C,
}


impl<Y: for<'a> Yokeable<'a>> Yoke<Y, Rc<[u8]>> {
    pub fn project<'this, P>(
        &'this self,
        f: for<'a> fn(&'this <Y as Yokeable<'a>>::Output, &'a ()) -> <P as Yokeable<'a>>::Output,
    ) -> Yoke<P, Rc<[u8]>>
    where
        P: for<'a> Yokeable<'a>,
    {
        unimplemented!()
    }
}

pub fn slice(y: Yoke<&'static str, Rc<[u8]>>) -> Yoke<&'static [u8], Rc<[u8]>> {
    y.project(move |yk, _| yk.as_bytes())
}


unsafe impl<'a, T: 'static + ToOwned + ?Sized> Yokeable<'a> for Cow<'static, T>
where
    <T as ToOwned>::Owned: Sized,
{
    type Output = Cow<'a, T>;

}

unsafe impl<'a, T: 'static + ?Sized> Yokeable<'a> for &'static T {
    type Output = &'a T;
}

fn main() {}
```
</details>

**Comment by Manishearth** [comment]
(@jackh726 Out of curiosity, is there a reason you like `no_core` for the repros? Easier to debug?)

**Comment by jackh726** [comment]
For me, yes, easier to debug. Making a test `no_core` means I can conceivably just `RUSTC_LOG=debug`, or at least be much more liberal with logging.

**Comment by lqd** [comment]
minimized a bit more the one in the OP (not the `no_core` repro)

```rust
pub unsafe trait Yokeable<'a> {
    type Output: 'a;
}
pub struct Yoke<Y: for<'a> Yokeable<'a>> {
    _marker: std::marker::PhantomData<Y>,
}
impl<Y: for<'a> Yokeable<'a>> Yoke<Y> {
    pub fn project<P>(
        &self,
        _f: for<'a> fn(&<Y as Yokeable<'a>>::Output, &'a ()) -> <P as Yokeable<'a>>::Output,
    ) -> Yoke<P>
    where
        P: for<'a> Yokeable<'a>,
    {
        unimplemented!()
    }
}
pub fn slice(y: Yoke<&'static str>) -> Yoke<&'static [u8]> {
    y.project(move |yk, _| yk.as_bytes())
}
unsafe impl<'a, T: 'static + ?Sized> Yokeable<'a> for &'static T {
    type Output = &'a T;
}
fn main() {
}
```

**Comment by jackh726** [comment]
@Manishearth just pushed a fix. Can you confirm?

**Comment by Manishearth** [comment]
@jackh726 will take me a while since that commit hasn't been trybuilt. But it looks like you checked in the reduced testcase, so that's good!

**Comment by Manishearth** [comment]
It works, thanks!
