### ISSUE TITLE
fail to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#86708]
```
<bpang@boyuan-Precision-3640-Tower:~/rust$ python3.8 x.py build                                                                                                                    
Updating only changed submodules                                                                                                                                                       
Submodules updated in 0.01 seconds                                                                                                                                                     
downloading https://static.rust-lang.org/dist/2021-05-23/rust-std-beta-x86_64-unknown-linux-gnu.tar.xz                                                                                 
############################################################################################################################################################################### 100.0% 
Traceback (most recent call last):                                                                                                                                                     
  File "x.py", line 27, in <module>                                                                                                                                                    
    bootstrap.main()                                                                                                                                                                   
  File "/home/bpang/rust/src/bootstrap/bootstrap.py", line 1187, in main                                                                                                               
    bootstrap(help_triggered)                                                                                                                                                          
  File "/home/bpang/rust/src/bootstrap/bootstrap.py", line 1153, in bootstrap                                                                                                          
    build.download_toolchain()                                                                                                                                                         
  File "/home/bpang/rust/src/bootstrap/bootstrap.py", line 413, in download_toolchain                                                                                                  
    self._download_component_helper(filename, pattern, tarball_suffix, stage0)                                                                                                         
  File "/home/bpang/rust/src/bootstrap/bootstrap.py", line 526, in _download_component_helper                                                                                          
    get("{}/{}".format(url, filename), tarball, verbose=self.verbose, do_verify=stage0)                                                                                                
  File "/home/bpang/rust/src/bootstrap/bootstrap.py", line 49, in get                                                                                                                  
    if do_verify and not verify(temp_path, sha_path, verbose):                                                                                                                         
  File "/home/bpang/rust/src/bootstrap/bootstrap.py", line 108, in verify                                                                                                              
    expected = sha256sum.readline().split()[0]                                                                                                                                         
IndexError: list index out of range
```

**Comment by JohnTitor** [comment]
It'd be great if you could provide more information e.g. your env, your config.toml, and if it happens after `./x.py clean` (or cleaning up manually).

**Comment by BaoshanPang** [comment]
It turns out I have installed a defect 'curl' from snap on my ubuntu 18.04, removed it and installed the one from "apt-get" makes the issue disappear.
