### ISSUE TITLE
encountered incremental compilation error with evaluate_obligation

### ISSUE THREAD

**Issue by stanly-johnson** [rust-lang/rust#86771]
### Code

https://github.com/valibre-org/vln-node/blob/master/runtime/src/lib.rs

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (a1411de9d 2021-06-26) running on aarch64-apple-darwin
```

### Error output

```
thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(6b4effcf9b9444-a474a1dbc8e8cc6): Ok(EvaluatedToOk)', /rustc/a1411de9de38e0fed728874580218338160eb185/compiler/rustc_query_system/src/query/plumbing.rs:624:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(6b4effcf9b9444-a474a1dbc8e8cc6)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p vln_parachain` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(6b4effcf9b9444-a474a1dbc8e8cc6): Ok(EvaluatedToOk)', /rustc/a1411de9de38e0fed728874580218338160eb185/compiler/rustc_query_system/src/query/plumbing.rs:624:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (a1411de9d 2021-06-26) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `futures_channel::mpsc::UnboundedSender<sc_transaction_pool::revalidation::WorkerPayload<sc_transaction_pool::FullChainApi<sc_service::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::ParachainRuntimeExecutor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, vln_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>>>: std::marker::Sync`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [sc_rpc::author::Author<sc_transaction_pool::BasicPool<sc_transaction_pool::FullChainApi<sc_service::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::ParachainRuntimeExecutor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, vln_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::ParachainRuntimeExecutor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u32, polkadot_service::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, vln_runtime::RuntimeApi>>, sp_core::H256, sp_core::H256], item_def_id: DefId(514:599 ~ sc_rpc_api[645d]::author::rpc_impl_AuthorApi::gen_server::AuthorApi::Metadata) } } }`
end of query stack
error: aborting due to previous error
```

</p>
</details>

**Comment by hellow554** [comment]
Hey @stanly-johnson 

please take a look at the pinned issue #84970

This is (sadly) known. To circumvent this you can run `cargo clean` and then the ICE should vanish.
