### ISSUE TITLE
rustc panics cross-compiling riscv64gc-unknown-uefi target

### ISSUE THREAD

**Issue by orvij** [rust-lang/rust#86829]
### Code

```diff
diff --git a/compiler/rustc_target/src/spec/mod.rs b/compiler/rustc_target/src/spec/mod.rs
index 0736ffb52f7..3d336243b85 100644
--- a/compiler/rustc_target/src/spec/mod.rs
+++ b/compiler/rustc_target/src/spec/mod.rs
@@ -875,6 +875,7 @@ fn $module() {
     ("riscv64gc-unknown-none-elf", riscv64gc_unknown_none_elf),
     ("riscv64gc-unknown-linux-gnu", riscv64gc_unknown_linux_gnu),
     ("riscv64gc-unknown-linux-musl", riscv64gc_unknown_linux_musl),
+    ("riscv64gc-unknown-uefi", riscv64gc_unknown_uefi),
 
     ("aarch64-unknown-none", aarch64_unknown_none),
     ("aarch64-unknown-none-softfloat", aarch64_unknown_none_softfloat),
diff --git a/compiler/rustc_target/src/spec/riscv64gc_unknown_uefi.rs b/compiler/rustc_target/src/spec/riscv64gc_unknown_uefi.rs
new file mode 100644
index 00000000000..3ffd1ab1f19
--- /dev/null
+++ b/compiler/rustc_target/src/spec/riscv64gc_unknown_uefi.rs
@@ -0,0 +1,24 @@
+use crate::spec::{CodeModel, Endian};
+use crate::spec::Target;
+
+pub fn target() -> Target {
+    let mut base = super::uefi_msvc_base::opts();
+    base.exe_suffix = ".efi".to_string();
+    base.features = "+m,+a,+f,+d,+c".to_string();
+    base.is_like_windows = true;
+    base.llvm_abiname = "c".to_string();
+    base.cpu = "generic-rv64".to_string();
+    base.os = "uefi".to_string();
+    base.max_atomic_width = Some(64);
+    base.endian = Endian::Little;
+    base.unsupported_abis = super::riscv_base::unsupported_abis();
+    base.code_model = Some(CodeModel::Medium);
+
+    Target {
+        llvm_target: "riscv64-unknown-windows".to_string(),
+        pointer_width: 64,
+        data_layout: "e-m:e-p:64:64-i64:64-i128:128-n64-S128".to_string(),
+        arch: "riscv64".to_string(),
+        options: base,
+    }
+}
```
`riscv-unknown-uefi.json`:

```json
{
  "abi-return-struct-as-int": true,
  "allows-weak-linkage": false,
  "arch": "riscv64",
  "cpu": "generic-rv64",
  "data-layout": "e-m:e-p:64:64-i64:64-i128:128-n64-S128",
  "default-hidden-visibility": true,
  "disable-redzone": true,
  "emit-debug-gdb-scripts": false,
  "exe-suffix": ".efi",
  "executables": true,
  "is-builtin": true,
  "is-like-msvc": true,
  "is-like-windows": true,
  "linker": "rust-lld",
  "linker-flavor": "lld-link",
  "linker-is-gnu": false,
  "lld-flavor": "link",
  "llvm-target": "riscv64-unknown-windows",
  "max-atomic-width": 64,
  "os": "uefi",
  "panic-strategy": "abort",
  "pre-link-args": {
    "lld-link": [
      "/NOLOGO",
      "/entry:efi_main",
      "/machine:riscv64",
      "/subsystem:efi_application"
    ]
  },
  "singlethread": true,
  "split-debuginfo": "packed",
  "stack-probes": {
    "kind": "call"
  },
  "target-c-int-width": "32",
  "target-endian": "little",
  "target-pointer-width": "64"
}
```

### Build command

```
RUST_BACKTRACE=full DESTDIR=toolchains/nightly-2021-07-02-riscv64gc-unknown-uefi/ ./x.py install -i --stage 1 --host riscv64-unknown-uefi.json --target riscv64gc-unknown-uefi library/std
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-beta.3 (82b862164 2021-05-22) running on x86_64-unknown-linux-gnu
```

### Error output

```
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc_attr v0.0.0 (rust/compiler/rustc_attr)
   Compiling rustc_query_system v0.0.0 (rust/compiler/rustc_query_system)
   Compiling rustc_parse v0.0.0 (rust/compiler/rustc_parse)
warning: could not load dep-graph from `rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/incremental/rustc_query_system-28kjeyetxu5s/s-g03u8nxzhy-1k0aj3o-working/dep-graph.bin`: failed to fill whole buffer

thread 'rustc' panicked at 'attempted to read from stolen value', /rustc/82b86216422e1ee696e20511180fada7a7a87949/compiler/rustc_data_structures/src/steal.rs:37:21
```

### Compiler flags

```
note: compiler flags: -Z macro-backtrace -Z tls-model=initial-exec -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib
```
<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'attempted to read from stolen value', /rustc/82b86216422e1ee696e20511180fada7a7a87949/compiler/rustc_data_structures/src/steal.rs:37:21
stack backtrace:
   0:     0x7f95c0704f10 - std::backtrace_rs::backtrace::libunwind::trace::h880e86c16131e543
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f95c0704f10 - std::backtrace_rs::backtrace::trace_unsynchronized::h58807f2da56c47b3
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f95c0704f10 - std::sys_common::backtrace::_print_fmt::h79d67bbf23537ee0
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f95c0704f10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6afd7ad593709198
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f95c077629f - core::fmt::write::hdc1e76b5176fd653
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/core/src/fmt/mod.rs:1094:17
   5:     0x7f95c06f9985 - std::io::Write::write_fmt::ha5c5c0efd1d08ddc
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/io/mod.rs:1584:15
   6:     0x7f95c0708c3b - std::sys_common::backtrace::_print::h16e0d1a95f75f210
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f95c0708c3b - std::sys_common::backtrace::print::hf8154bbac43d8779
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f95c0708c3b - std::panicking::default_hook::{{closure}}::hb22fb2f362e83354
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/panicking.rs:208:50
   9:     0x7f95c070871d - std::panicking::default_hook::hfe65f3219b44e611
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/panicking.rs:225:9
  10:     0x7f95c0ece8fd - rustc_driver::report_ice::hc5ffb3f418fe2cc5
  11:     0x7f95b39caa59 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9d27f7bc08eb917a
  12:     0x7f95b399a2d8 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hcc8be0bb29bad3ef
  13:     0x7f95c0709350 - std::panicking::rust_panic_with_hook::h1a85262a870dd5b0
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/panicking.rs:595:17
  14:     0x7f95c17baef5 - std::panicking::begin_panic::{{closure}}::hb81540db3fd23ae7
  15:     0x7f95c17bac4d - std::sys_common::backtrace::__rust_end_short_backtrace::h6828ad8316f4fa3c
  16:     0x7f95c17bae09 - std::panicking::begin_panic::ha1b7e453f2eb9e00
  17:     0x7f95c2592d4d - rustc_mir::transform::check_unsafety::unsafety_check_result::he0e8a1e513847bb0
  18:     0x7f95c2587b22 - core::ops::function::FnOnce::call_once::h13e204a905aaebc6
  19:     0x7f95c150ca76 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hd67ded2aa1a26972
  20:     0x7f95c2d90c28 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::hbb74f15b9b7951e3
  21:     0x7f95c2235c40 - rustc_query_system::query::plumbing::get_query_impl::h7f49812bc9784aaa
  22:     0x7f95c22a304d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result::h72c54143d3300db9
  23:     0x7f95c25933f5 - rustc_mir::transform::check_unsafety::check_unsafety::h1afd48b0f326e695
  24:     0x7f95c1f799df - rustc_session::utils::<impl rustc_session::session::Session>::time::h762448e2e8f4764f
  25:     0x7f95c29a61e7 - rustc_interface::passes::analysis::h1b06feeca7b4fa77
  26:     0x7f95c150f8ca - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hf23c535fad4ff1a2
  27:     0x7f95c2e17f98 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hdc2a84318571a1c4
  28:     0x7f95c2e51da7 - rustc_data_structures::stack::ensure_sufficient_stack::h52fa211240686db6
  29:     0x7f95c2d626e1 - rustc_query_system::query::plumbing::force_query_with_job::hbe7ca87583a9420e
  30:     0x7f95c2cfe263 - rustc_query_system::query::plumbing::get_query_impl::h08fe50dd3615e4fa
  31:     0x7f95c2de46cf - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h69b8848818ce6cb9
  32:     0x7f95c29854da - rustc_interface::passes::QueryContext::enter::hda3371188fab5819
  33:     0x7f95c296a252 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h8629d08bff5663db
  34:     0x7f95c2969244 - rustc_span::with_source_map::h312f1b4dbf506618
  35:     0x7f95c296b211 - rustc_interface::interface::create_compiler_and_run::hbc51e5d4dbff47cf
  36:     0x7f95c29848f8 - scoped_tls::ScopedKey<T>::set::h86373af0a1fe4beb
  37:     0x7f95c2984e7b - std::sys_common::backtrace::__rust_begin_short_backtrace::haf39e46e4706340b
  38:     0x7f95c2987cf5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1ea4e52130df0d2b
  39:     0x7f95c0717ee7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2fe906f7ca2c80c4
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/alloc/src/boxed.rs:1546:9
  40:     0x7f95c0717ee7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf577546e105ebded
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/alloc/src/boxed.rs:1546:9
  41:     0x7f95c0717ee7 - std::sys::unix::thread::Thread::new::thread_start::hedae860fc8535ac7
                               at /rustc/82b86216422e1ee696e20511180fada7a7a87949/library/std/src/sys/unix/thread.rs:71:17
  42:     0x7f95c064b259 - start_thread
  43:     0x7f95c05625e3 - __GI___clone
  44:                0x0 - <unknown>
```

</p>
</details>

**Comment by orvij** [comment]
Fixed on latest master [c7d6bcc](https://github.com/rust-lang/rust/commit/c7d6bcc788ef6b2293d2d5166a9b0339d5d03b0a)
