### ISSUE TITLE
ubuntu  libc malloc and free  will core dump

### ISSUE THREAD

**Issue by luyikk** [rust-lang/rust#86931]
All kinds of crashes come from libc malloc and free. This is one of them. When I don't use default global_allocator, it's OK to use mimalloc,the error will come from String, Vec<T>, Box<T>..... random core dump.
that makes me wonder about default global_ Allocator robustness.

I expected to see this happen: *explanation*
Instead, this happened: *explanation*

This is just a piece of normal code but my ubuntu could crash

I tried this code:
```rust
    fn get_result_buff(serial: i64, result: RetResult) -> Data {
        let mut data = Data::with_capacity(1024);

        data.write_fixed(0u32);
        data.write_fixed(2500u32);
        data.write_fixed(serial);

        if result.is_error {
            data.write_fixed(true);
            data.write_fixed(result.error_id);
            data.write_fixed(result.msg);
        } else {
            data.write_fixed(false);
            data.write_fixed(result.arguments.len() as u32);
            for argument in result.arguments {
                data.write_fixed(argument.into_inner());
            }
        }

        let len = data.len();
        (&mut data[0..4]).put_u32_le(len as u32);
        data
    }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (6a758ea7e 2021-06-22)
Ubuntu 18.04.4 LTS
```

<details><summary>Backtrace</summary>
<p>

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f3310703801 in __GI_abort () at abort.c:79
#2  0x00007f331074c897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f3310879b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f331075390a in malloc_printerr (str=str@entry=0x7f331087b7a8 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007f331075aecc in munmap_chunk (p=0x7f330c005c10) at malloc.c:2846
#5  __GI___libc_free (mem=0x7f330c005c20) at malloc.c:3117
#6  0x000055c6ab5b12cb in alloc::alloc::dealloc (
    ptr=0x7f330c005c20 "code\":6},{\"gamename\":\"slots280\",\"buildcode\":6},{\"gamename\":\"slots282\",\"buildcode\":6},{\"gamename\":\"slots283\",\"buildcode\":6},{\"gamename\":\"slots287\",\"buildcode\":6},{\"gamename\":\"slots288\",\"buildcode\":6},{"..., layout=...) at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/alloc/src/alloc.rs:104
#7  0x000055c6ab5b139b in <alloc::alloc::Global as core::alloc::Allocator>::deallocate (self=0x7f33106bfd90, ptr=..., layout=...) at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/alloc/src/alloc.rs:239
#8  0x000055c6ab5adfeb in <alloc::raw_vec::RawVec<T,A> as core::ops::drop::Drop>::drop (self=0x7f33106bfd90) at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/alloc/src/raw_vec.rs:521
#9  0x000055c6ab5b35eb in core::ptr::drop_in_place<alloc::raw_vec::RawVec<u8>> () at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/core/src/ptr/mod.rs:192
#10 0x000055c6ab5b3594 in core::ptr::drop_in_place<alloc::vec::Vec<u8>> () at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/core/src/ptr/mod.rs:192
#11 0x000055c6ab5b356b in core::ptr::drop_in_place<alloc::string::String> () at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/core/src/ptr/mod.rs:192
#12 0x000055c6ab13cddf in netxserver::server::impl_server::NetXServer<T>::get_result_buff (serial=4424961637612796050, result=...)
    at /home/luyi/.cargo/registry/src/github.com-1ecc6299db9ec823/netxserver-1.5.2/src/server/impl_server.rs:265

```
```
0x00007fded2b22801 in __GI_abort () at abort.c:79
#2  0x00007fded2b6b897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fded2c98b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fded2b7290a in malloc_printerr (str=str@entry=0x7fded2c9a7a8 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007fded2b79ecc in munmap_chunk (p=0x7fdecc002460) at malloc.c:2846
#5  __GI___libc_free (mem=0x7fdecc002470) at malloc.c:3117
#6  0x0000558740a140fb in alloc::alloc::dealloc (ptr=0x7fdecc002470 "", layout=...) at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/alloc/src/alloc.rs:104
#7  0x0000558740a1479b in <alloc::alloc::Global as core::alloc::Allocator>::deallocate (self=0x7fded2add8f0, ptr=..., layout=...) at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/alloc/src/alloc.rs:239
#8  0x0000558740a145cb in alloc::alloc::box_free (ptr=..., alloc=...) at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/alloc/src/alloc.rs:334
#9  0x0000558740a12af1 in core::ptr::drop_in_place<alloc::boxed::Box<dyn aqueue::queue::QueueItem+core::marker::Sync+core::marker::Send>> () at 
```
</p>
</details>

**Comment by jonas-schievink** [comment]
Please provide a way to reproduce this issue

**Comment by luyikk** [comment]
My own MEM is out of bounds. This issue is closed
