### ISSUE TITLE
rustdoc: cache.access_levels is wrong

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#87048]
I tried this code:

```diff
diff --git a/src/librustdoc/html/format.rs b/src/librustdoc/html/format.rs
index c08fe47696b..9238ed5477e 100644
--- a/src/librustdoc/html/format.rs
+++ b/src/librustdoc/html/format.rs
@@ -479,7 +479,12 @@ fn to_module_fqp(shortty: ItemType, fqp: &[String]) -> &[String] {
         if shortty == ItemType::Module { &fqp[..] } else { &fqp[..fqp.len() - 1] }
     }
 
-    if !did.is_local() && !cache.access_levels.is_public(did) && !cache.document_private {
+    if !cache.access_levels.is_public(did) && !cache.document_private {
+        // Private local items used to not be checked. Make sure that the behavior is the same as before.
+        if did.is_local() {
+            // NOTE: we don't need to check `external_paths.get(did).is_none()` because the crate will always be unknown.
+            assert!(cache.paths.get(&did).is_none(), "{:?}", did);
+        }
         return None;
     }
 
```

I expected to see this happen: All the rustdoc tests pass; this should be the same behavior as before.

Instead, this happened:
```

---- [rustdoc] rustdoc/blanket-reexport-item.rs stdout ----
------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'DefId(0:5 ~ foo[cf51]::m::S)', src/librustdoc/html/format.rs:486:13
```

The code for this test is https://github.com/rust-lang/rust/blob/dfd7b8d03fb93d0e03147d28b3be6d93260fa94d/src/test/rustdoc/blanket-reexport-item.rs#L1-L8. `m::S` should be marked as public (since it's accessible through the glob re-export), but is not.

### Meta

HEAD is 432e145bd5a974c5b6f4dd9b352891bd7502b69d.

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at 'DefId(0:5 ~ foo[cf51]::m::S)', src/librustdoc/html/format.rs:486:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/std/src/panicking.rs:457:5
   2: rustdoc::html::format::href
             at ./src/librustdoc/html/format.rs:486:13
   3: rustdoc::html::format::anchor
             at ./src/librustdoc/html/format.rs:681:17
   4: rustdoc::html::format::resolved_path
             at ./src/librustdoc/html/format.rs:585:13
   5: rustdoc::html::format::fmt_type
             at ./src/librustdoc/html/format.rs:711:13
   6: rustdoc::html::format::<impl rustdoc::clean::types::Impl>::print::{{closure}}
   7: <rustdoc::html::format::display_fn::WithFormatter<F> as core::fmt::Display>::fmt
             at ./src/librustdoc/html/format.rs:1429:13
   8: <T as alloc::string::ToString>::to_string
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/alloc/src/string.rs:2379:9
   9: rustdoc::html::render::write_shared::write_shared::{{closure}}
             at ./src/librustdoc/html/render/write_shared.rs:520:31
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/core/src/ops/function.rs:269:13
  11: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/core/src/slice/iter/macros.rs:268:38
  12: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/core/src/iter/adapters/filter_map.rs:61:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/alloc/src/vec/mod.rs:2453:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/library/core/src/iter/traits/iterator.rs:1748:9
  17: rustdoc::html::render::write_shared::write_shared
             at ./src/librustdoc/html/render/write_shared.rs:506:28
  18: <rustdoc::html::render::context::Context as rustdoc::formats::renderer::FormatRenderer>::init
             at ./src/librustdoc/html/render/context.rs:504:9
  19: rustdoc::formats::renderer::run_format::{{closure}}
             at ./src/librustdoc/formats/renderer.rs:62:17
  20: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_data_structures/src/profiling.rs:573:9
  21: rustdoc::formats::renderer::run_format
             at ./src/librustdoc/formats/renderer.rs:60:40
  22: rustdoc::run_renderer
             at ./src/librustdoc/lib.rs:668:11
  23: rustdoc::main_options::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/librustdoc/lib.rs:769:25
  24: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_data_structures/src/profiling.rs:573:9
  25: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_session/src/utils.rs:16:9
  26: rustdoc::main_options::{{closure}}::{{closure}}::{{closure}}
             at ./src/librustdoc/lib.rs:768:51
  27: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/passes.rs:780:42
  28: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_middle/src/ty/context.rs:1765:50
  29: rustc_middle::ty::context::tls::set_tlv
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_middle/src/ty/context.rs:1749:9
  30: rustc_middle::ty::context::tls::enter_context
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_middle/src/ty/context.rs:1765:9
  31: rustc_interface::passes::QueryContext::enter
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/passes.rs:780:9
  32: rustdoc::main_options::{{closure}}::{{closure}}
             at ./src/librustdoc/lib.rs:742:13
  33: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/queries.rs:390:19
  34: rustdoc::main_options::{{closure}}
             at ./src/librustdoc/lib.rs:722:9
  35: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/interface.rs:208:13
  36: rustc_span::with_source_map
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_span/src/lib.rs:917:5
  37: rustc_interface::interface::create_compiler_and_run
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/interface.rs:202:5
  38: rustdoc::main_options
             at ./src/librustdoc/lib.rs:721:5
  39: rustdoc::main_args::{{closure}}
             at ./src/librustdoc/lib.rs:648:17
  40: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/util.rs:155:13
  41: scoped_tls::ScopedKey<T>::set
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  42: rustc_span::create_session_globals_then
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_span/src/lib.rs:108:5
  43: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/util.rs:153:9
  44: rustc_interface::util::scoped_thread::{{closure}}
             at /rustc/432e145bd5a974c5b6f4dd9b352891bd7502b69d/compiler/rustc_interface/src/util.rs:128:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by jyn514** [comment]
Probably https://github.com/rust-lang/rust/blob/dfd7b8d03fb93d0e03147d28b3be6d93260fa94d/src/librustdoc/visit_ast.rs#L275 needs to mark items as public if they're used through a glob.

**Comment by inquisitivecrystal** [comment]
I'm currently taking a look to see if I'll be able to do this, though I think I probably will.

**Comment by inquisitivecrystal** [comment]
Alright, so...

It looks to me like I need to figure out how to get the DefId of the items behind the glob use, so I can add them to `self.cx.cache.access_levels.map`. Is that correct, and if so, how would I go about it?

**Comment by jyn514** [comment]
Yes, that sounds right. You can get the DefId by calling `path.res.def._id().`

**Comment by inquisitivecrystal** [comment]
Okay,  I've done some work. That test case now passes even with your changes. Unfortunately, a lot of the other tests are still failing. Should I be working on those too?

@rustbot claim

**Comment by jyn514** [comment]
@inquisitivecrystal I'm not sure - what are the other failures?

**Comment by inquisitivecrystal** [comment]
Here you go! I should mention that there's a bit of information from a `dbg!` statement in the full text version.
```
failures:
    [rustdoc] rustdoc/all.rs
    [rustdoc] rustdoc/inline_cross/renamed-via-module.rs
    [rustdoc] rustdoc/inline_local/glob-private-no-defaults.rs
    [rustdoc] rustdoc/inline_local/glob-private.rs
    [rustdoc] rustdoc/inline_local/issue-28537.rs
    [rustdoc] rustdoc/inline_local/issue-32343.rs
    [rustdoc] rustdoc/inline_local/trait-vis.rs
    [rustdoc] rustdoc/intra-doc/cross-crate/hidden.rs
    [rustdoc] rustdoc/issue-34473.rs
    [rustdoc] rustdoc/namespaces.rs
    [rustdoc] rustdoc/redirect-map.rs
    [rustdoc] rustdoc/redirect-rename.rs
    [rustdoc] rustdoc/redirect.rs
    [rustdoc] rustdoc/search-index.rs
    [rustdoc] rustdoc/synthetic_auto/complex.rs
```

<details>

```
---- [rustdoc] rustdoc/all.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:16 ~ foo[cf51]::private_module::ReexportedStruct)
thread 'rustc' panicked at 'DefId(0:16 ~ foo[cf51]::private_module::ReexportedStruct)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/inline_cross/renamed-via-module.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:5 ~ foo[cf51]::iter::range::StepBy)
thread 'rustc' panicked at 'DefId(0:5 ~ foo[cf51]::iter::range::StepBy)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/inline_local/glob-private-no-defaults.rs stdout ----

error: htmldocck failed!
status: exit status: 1
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
21: @!has check failed
	`PATTERN` did not match
	// @!has - "mod2"
22: @has check failed
	`PATTERN` did not match
	// @has - "Mod2Public"
26: @has check failed
	File does not exist 'foo/struct.Mod2Public.html'
	// @has foo/struct.Mod2Public.html

Encountered 3 errors

------------------------------------------

info: generating a diff against nightly rustdoc
thread '[rustdoc] rustdoc/inline_local/glob-private-no-defaults.rs' panicked at 'assertion failed: status.success() || status.code() == Some(1)', src/tools/compiletest/src/runtest.rs:2484:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- [rustdoc] rustdoc/inline_local/issue-28537.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:11 ~ issue_28537[2196]::bar::bar::Bar)
thread 'rustc' panicked at 'DefId(0:11 ~ issue_28537[2196]::bar::bar::Bar)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/inline_local/issue-32343.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:12 ~ issue_32343[11e0]::foo::Bar)
thread 'rustc' panicked at 'DefId(0:12 ~ issue_32343[11e0]::foo::Bar)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/inline_local/glob-private.rs stdout ----

error: htmldocck failed!
status: exit status: 1
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
19: @!has check failed
	`PATTERN` did not match
	// @!has - "mod2"
20: @has check failed
	`PATTERN` did not match
	// @has - "Mod2Public"
24: @has check failed
	File does not exist 'foo/struct.Mod2Public.html'
	// @has foo/struct.Mod2Public.html
34: @has-dir check failed
	Directory does not exist 'foo/mod1/mod2'
	// @has-dir foo/mod1/mod2
36: @has check failed
	File does not exist 'foo/mod1/mod2/struct.Mod2Public.html'
	// @has foo/mod1/mod2/struct.Mod2Public.html

Encountered 5 errors

------------------------------------------

info: generating a diff against nightly rustdoc
thread '[rustdoc] rustdoc/inline_local/glob-private.rs' panicked at 'assertion failed: status.success() || status.code() == Some(1)', src/tools/compiletest/src/runtest.rs:2484:21

---- [rustdoc] rustdoc/inline_local/trait-vis.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:8 ~ trait_vis[70a0]::asdf::SomeStruct)
thread 'rustc' panicked at 'DefId(0:8 ~ trait_vis[70a0]::asdf::SomeStruct)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/intra-doc/cross-crate/hidden.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
warning: lint `broken_intra_doc_links` has been renamed to `rustdoc::broken_intra_doc_links`
 --> [FULL PATH REDACTED]
  |
2 | #![deny(broken_intra_doc_links)]
  |         ^^^^^^^^^^^^^^^^^^^^^^ help: use the new name: `rustdoc::broken_intra_doc_links`
  |
  = note: `#[warn(renamed_and_removed_lints)]` on by default

[src/librustdoc/html/format.rs:490] did = DefId(0:7 ~ hidden_dep[505c]::future::ready::Ready)
thread 'rustc' panicked at 'DefId(0:7 ~ hidden_dep[505c]::future::ready::Ready)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack
warning: 1 warning emitted


------------------------------------------


---- [rustdoc] rustdoc/issue-34473.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:4 ~ foo[cf51]::second::SomeTypeWithLongName)
thread 'rustc' panicked at 'DefId(0:4 ~ foo[cf51]::second::SomeTypeWithLongName)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/namespaces.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:5 ~ namespaces[e9ef]::inner::sync::SomeStruct)
thread 'rustc' panicked at 'DefId(0:5 ~ namespaces[e9ef]::inner::sync::SomeStruct)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/redirect-map.rs stdout ----

error: rustdoc failed!
status: exit status: 1
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:10 ~ foo[cf51]::private::Quz)
thread 'rustc' panicked at 'DefId(0:10 ~ foo[cf51]::private::Quz)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'generate-redirect-map'


------------------------------------------


---- [rustdoc] rustdoc/redirect-rename.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:11 ~ foo[cf51]::hidden::bar::Thing)
thread 'rustc' panicked at 'DefId(0:11 ~ foo[cf51]::hidden::bar::Thing)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/redirect.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:10 ~ reexp_stripped[c7ca]::private::Quz)
thread 'rustc' panicked at 'DefId(0:10 ~ reexp_stripped[c7ca]::private::Quz)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/search-index.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:10 ~ rustdoc_test[88de]::private::Foo)
thread 'rustc' panicked at 'DefId(0:10 ~ rustdoc_test[88de]::private::Foo)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------


---- [rustdoc] rustdoc/synthetic_auto/complex.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: [REDACTED]
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
[src/librustdoc/html/format.rs:490] did = DefId(0:7 ~ complex[87cf]::foo::Inner)
thread 'rustc' panicked at 'DefId(0:7 ~ complex[87cf]::foo::Inner)', src/librustdoc/html/format.rs:491:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-dev running on x86_64-apple-darwin

query stack during panic:
end of query stack

------------------------------------------
```
</details>
