### ISSUE TITLE
Compiler error after unexpected powerdown

### ISSUE THREAD

**Issue by farbodpm** [rust-lang/rust#87448]
### Code

```Rust
#![no_std]
#![crate_name = "Operation"]
#![crate_type = "rlib"]


```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
farbod@farbod:~/avl/Operation$ cargo test
warning: constant is never used: `ConvertingGain`
  --> collector/src/lib.rs:11:1
   |
11 | const ConvertingGain : u32 = 1000000;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `metrics_ids`
  --> collector/src/lib.rs:16:5
   |
16 |     metrics_ids: Vec<u8>,//there are some reserved id's : 1. Time
   |     ^^^^^^^^^^^^^^^^^^^^

warning: constant `ConvertingGain` should have an upper case name
  --> collector/src/lib.rs:11:7
   |
11 | const ConvertingGain : u32 = 1000000;
   |       ^^^^^^^^^^^^^^ help: convert the identifier to upper case: `CONVERTING_GAIN`
   |
   = note: `#[warn(non_upper_case_globals)]` on by default

warning: 3 warnings emitted

   Compiling Operation v0.1.0 (/home/farbod/avl/Operation)
warning: unused import: `alloc::vec`
 --> Operation/src/lib.rs:6:5
  |
6 | use alloc::vec;
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unreachable pattern
   --> Operation/src/lib.rs:100:21
    |
100 |                     (_, true, _) => {
    |                     ^^^^^^^^^^^^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

warning: unused variable: `prv_point`
  --> Operation/src/lib.rs:26:50
   |
26 |     fn on_aquire(&self, points: &mut Vec<Point>, prv_point: &mut Point) {
   |                                                  ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_prv_point`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: field is never read: `id`
  --> Operation/src/lib.rs:20:5
   |
20 |     id: u8,
   |     ^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `incremented`
  --> Operation/src/lib.rs:21:5
   |
21 |     incremented: bool,
   |     ^^^^^^^^^^^^^^^^^

warning: field is never read: `logic_type`
  --> Operation/src/lib.rs:22:5
   |
22 |     logic_type: LogicType,
   |     ^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `metric_id`
  --> Operation/src/lib.rs:23:5
   |
23 |     metric_id: u8,
   |     ^^^^^^^^^^^^^

warning: associated function is never used: `on_aquire`
  --> Operation/src/lib.rs:26:8
   |
26 |     fn on_aquire(&self, points: &mut Vec<Point>, prv_point: &mut Point) {
   |        ^^^^^^^^^

warning: crate `Operation` should have a snake case name
  |
  = note: `#[warn(non_snake_case)]` on by default
  = help: convert the identifier to snake case: `operation`

warning: unreachable pattern
   --> Operation/src/lib.rs:100:21
    |
100 |                     (_, true, _) => {
    |                     ^^^^^^^^^^^^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

warning: unused variable: `prv_point`
  --> Operation/src/lib.rs:26:50
   |
26 |     fn on_aquire(&self, points: &mut Vec<Point>, prv_point: &mut Point) {
   |                                                  ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_prv_point`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: 9 warnings emitted

warning: crate `Operation` should have a snake case name
  |
  = note: `#[warn(non_snake_case)]` on by default
  = help: convert the identifier to snake case: `operation`

warning: function `on_aquire_check_MAX` should have a snake case name
   --> Operation/src/lib.rs:177:4
    |
177 | fn on_aquire_check_MAX() {
    |    ^^^^^^^^^^^^^^^^^^^ help: convert the identifier to snake case: `on_aquire_check_max`

thread 'rustc' panicked at 'Failed to recover key for crate_hash(734c19577ca205ef-2127172149ca103c) with hash 734c19577ca205ef-2127172149ca103c', compiler/rustc_query_impl/src/lib.rs:50:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (c7331d65b 2021-07-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: 4 warnings emitted

error: could not compile `Operation`; 5 warnings emitted

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Failed to recover key for crate_hash(734c19577ca205ef-2127172149ca103c) with hash 734c19577ca205ef-2127172149ca103c', compiler/rustc_query_impl/src/lib.rs:50:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (c7331d65b 2021-07-17) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: 4 warnings emitted

error: could not compile `Operation`; 5 warnings emitted

```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Perhaps a file is corrupted on your disk, does the problem persist if you `cargo clean` and rebuild?

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Without a way for others to reproduce the ICE, not much can be done at this point though. Closing.
