### ISSUE TITLE
Phantom ICE: thread 'rustc' panicked at 'index out of bounds: the len is 190 but the index is 40260'

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#87452]
As the title suggests, the ICE was "phantom" i.e. after I ran `cargo r` for a second-time compilation succeeded without problems. As such, I can't provide MRE.

The ICE happened while I was compiling edited `11-usart` example from the [Discovery Book][book]. The exact version of the code can be found in [my fork].

[book]: https://docs.rust-embedded.org/discovery/11-usart/index.html
[my fork]: https://github.com/WaffleLapkin/discovery/tree/34b4df1e1e9291a909594380bf122518b6ca884b/src/11-usart

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (240ff4c4a 2021-07-09)
binary: rustc
commit-hash: 240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4
commit-date: 2021-07-09
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

### Error output

<details><summary><strong>Error/Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 190 but the index is 40260', /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/compiler/rustc_middle/src/hir/map/mod.rs:192:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (240ff4c4a 2021-07-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'index out of bounds: the len is 190 but the index is 40260', /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/compiler/rustc_hir/src/definitions.rs:77:9
stack backtrace:
   0:     0x7f8ccf157f10 - std::backtrace_rs::backtrace::libunwind::trace::h706b838f5bbd876b
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f8ccf157f10 - std::backtrace_rs::backtrace::trace_unsynchronized::hc15f29ae7822b7b8
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8ccf157f10 - std::sys_common::backtrace::_print_fmt::h7c580c971f91926c
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8ccf157f10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2a772198c4032452
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f8ccf1c5cfc - core::fmt::write::h9a6d9c74526a6c1b
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/core/src/fmt/mod.rs:1115:17
   5:     0x7f8ccf149655 - std::io::Write::write_fmt::h00f38d9eb2c32e02
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/io/mod.rs:1663:15
   6:     0x7f8ccf15bc2b - std::sys_common::backtrace::_print::h5b3c171e6f864ae4
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f8ccf15bc2b - std::sys_common::backtrace::print::h93b9e9ed2a98e611
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f8ccf15bc2b - std::panicking::default_hook::{{closure}}::hd8da92bb68d520c5
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:208:50
   9:     0x7f8ccf15b701 - std::panicking::default_hook::hdbc8b2951c5afbab
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:225:9
  10:     0x7f8ccf92ef91 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::hb401cc3a4395a91f
  11:     0x7f8ccf15c459 - std::panicking::rust_panic_with_hook::h8a4c841655926f4e
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:626:17
  12:     0x7f8ccf15bf17 - std::panicking::begin_panic_handler::{{closure}}::h471b6bc74904b7b0
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:519:13
  13:     0x7f8ccf15840c - std::sys_common::backtrace::__rust_end_short_backtrace::h309f5c707f29932f
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f8ccf15be79 - rust_begin_unwind
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:515:5
  15:     0x7f8ccf126e91 - core::panicking::panic_fmt::hcf5f6d96e1dd7099
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/core/src/panicking.rs:92:14
  16:     0x7f8ccf126e52 - core::panicking::panic_bounds_check::hc3a71010bf41c72d
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/core/src/panicking.rs:69:5
  17:     0x7f8cd1c82913 - rustc_middle::ty::print::pretty::<impl rustc_middle::ty::context::TyCtxt>::def_path_str_with_substs::h08d438782369e849
  18:     0x7f8cd1c82724 - rustc_middle::ty::print::pretty::<impl rustc_middle::ty::context::TyCtxt>::def_path_str::hf76a9f58ece276a5
  19:     0x7f8ccfeb0261 - std::thread::local::LocalKey<T>::with::h172f963601e7c119
  20:     0x7f8ccfed39f8 - rustc_query_impl::plumbing::<impl rustc_query_system::query::config::QueryDescription<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::adt_def>::describe::h0f6233f3767f27df
  21:     0x7f8ccfeb8f17 - std::thread::local::LocalKey<T>::with::h70f9d18d71a71d67
  22:     0x7f8ccfeffa73 - rustc_query_impl::make_query::adt_def::h4595d6384c225c14
  23:     0x7f8ccfe50550 - rustc_query_system::query::plumbing::QueryState<D,K>::try_collect_active_jobs::h851d25e67c6666a1
  24:     0x7f8ccfef897e - rustc_query_impl::Queries::try_collect_active_jobs::h6c9631e703601d52
  25:     0x7f8ccfec8977 - rustc_query_system::query::job::print_query_stack::h5730919cbd425e7c
  26:     0x7f8ccfa3cbb7 - rustc_interface::interface::try_print_query_stack::h1bc8747c0ff2dca7
  27:     0x7f8ccf92f37f - rustc_driver::report_ice::h2f815295b2262d45
  28:     0x7f8ccf15c459 - std::panicking::rust_panic_with_hook::h8a4c841655926f4e
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:626:17
  29:     0x7f8ccf15bf17 - std::panicking::begin_panic_handler::{{closure}}::h471b6bc74904b7b0
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:519:13
  30:     0x7f8ccf15840c - std::sys_common::backtrace::__rust_end_short_backtrace::h309f5c707f29932f
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys_common/backtrace.rs:141:18
  31:     0x7f8ccf15be79 - rust_begin_unwind
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/panicking.rs:515:5
  32:     0x7f8ccf126e91 - core::panicking::panic_fmt::hcf5f6d96e1dd7099
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/core/src/panicking.rs:92:14
  33:     0x7f8ccf126e52 - core::panicking::panic_bounds_check::hc3a71010bf41c72d
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/core/src/panicking.rs:69:5
  34:     0x7f8cd16c223b - rustc_typeck::collect::adt_def::h76d798dde0e7b85c
  35:     0x7f8cd0ceb02f - rustc_query_system::query::plumbing::get_query_impl::h4cf7be0f86f1c9dc
  36:     0x7f8cd0d4bbdb - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::adt_def::h76bcf68b501ee568
  37:     0x7f8cd10783a8 - <rustc_middle::ty::adt::AdtDef as rustc_middle::ty::codec::RefDecodable<D>>::decode::h496e01c9c3b0d078
  38:     0x7f8cd1072e70 - rustc_middle::ty::sty::_DERIVE_rustc_serialize_Decodable_D_FOR_TyKind::<impl rustc_serialize::serialize::Decodable<__D> for rustc_middle::ty::sty::TyKind>::decode::h0947122d78a6889b
  39:     0x7f8cd108212c - rustc_middle::ty::codec::<impl rustc_serialize::serialize::Decodable<D> for &rustc_middle::ty::TyS>::decode::h51eeeb5979d62a12
  40:     0x7f8cd1080133 - <core::result::Result<T,E> as rustc_middle::ty::context::InternIteratorElement<T,R>>::intern_with::hb57e7b3f9b353d45
  41:     0x7f8cd107569b - rustc_middle::ty::codec::<impl rustc_serialize::serialize::Decodable<D> for rustc_middle::ty::sty::Binder<rustc_middle::ty::sty::FnSig>>::decode::h2e73789c0818418b
  42:     0x7f8cd10cb0d9 - rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::fn_sig::hca6833cea2913b07
  43:     0x7f8cd10b39f2 - rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::fn_sig::h7fc6a39851ff10df
  44:     0x7f8cd0cfee8a - rustc_query_system::query::plumbing::get_query_impl::h9aae2e3a178789f8
  45:     0x7f8cd0d4c596 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::fn_sig::hc22fcdfcb23f0955
  46:     0x7f8cd13802f9 - rustc_middle::ty::sty::<impl rustc_middle::ty::TyS>::fn_sig::hb9d61df52fa4a7df
  47:     0x7f8cd1047313 - rustc_middle::util::common::record_time::hbf5394ba433ea647
  48:     0x7f8cd103f5f6 - rustc_symbol_mangling::legacy::mangle::h7a3f09de647195b4
  49:     0x7f8cd1042add - rustc_symbol_mangling::symbol_name_provider::h6ae8c81b72d3bed9
  50:     0x7f8cd0cf70e3 - rustc_query_system::query::plumbing::get_query_impl::h726c34d46f814142
  51:     0x7f8cd0d4cd93 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::symbol_name::h8a48f9f148753992
  52:     0x7f8cd132c997 - rustc_middle::mir::mono::MonoItem::symbol_name::hdaa4820e154b94c0
  53:     0x7f8cd0f3d1a7 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h48719b4796652d23
  54:     0x7f8cd0ef52c2 - rustc_mir::monomorphize::partitioning::assert_symbols_are_distinct::h201e38e50d210784
  55:     0x7f8cd19a2e4d - rustc_data_structures::sync::join::hb7eb04d0fe3ccd41
  56:     0x7f8cd0ef56fd - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::hdfbab7419bb0126d
  57:     0x7f8cd17641e7 - rustc_query_system::query::plumbing::get_query_impl::h29d14c4a322a81ec
  58:     0x7f8cd1829b86 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items::h96b0607f2bd2b5da
  59:     0x7f8cd1a1e1ff - rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local::h66006d0fd50e43e7
  60:     0x7f8cd175c21f - rustc_query_system::query::plumbing::get_query_impl::h15f8d2c545a1f7cc
  61:     0x7f8cd1829ac8 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::exported_symbols::ha31325d6fb6e2c20
  62:     0x7f8cd1054842 - rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root::h1a12d3118a3756b7
  63:     0x7f8cd1a6b599 - rustc_metadata::rmeta::encoder::encode_metadata_impl::h55b9485f156012fa
  64:     0x7f8cd1a811f1 - rustc_data_structures::sync::join::hd8fff542e933abd6
  65:     0x7f8cd1acbcce - rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc_middle::middle::cstore::CrateStore for rustc_metadata::creader::CStore>::encode_metadata::hbc8a8a17a96c2e73
  66:     0x7f8cd1c895c9 - rustc_middle::ty::context::TyCtxt::encode_metadata::hed3372aa6c380b18
  67:     0x7f8cd141fe48 - rustc_interface::passes::QueryContext::enter::h285a8b6410891da8
  68:     0x7f8cd1418146 - rustc_interface::queries::Queries::ongoing_codegen::h14066dfb04bad0e6
  69:     0x7f8cd13f7085 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hb44adf2f7e4d9008
  70:     0x7f8cd13e5f8c - rustc_span::with_source_map::ha503ff1545426b21
  71:     0x7f8cd13f824a - rustc_interface::interface::create_compiler_and_run::h6e85467d9706bedf
  72:     0x7f8cd13eb299 - scoped_tls::ScopedKey<T>::set::h0e2c1597a1f6a576
  73:     0x7f8cd13e809a - std::sys_common::backtrace::__rust_begin_short_backtrace::h5c2fa93a4999a1ec
  74:     0x7f8cd13e6925 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8b6bc5ffa8abb153
  75:     0x7f8ccf168a07 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha8b1d5a0092467fc
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/alloc/src/boxed.rs:1572:9
  76:     0x7f8ccf168a07 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4b9f24ec4e8a879e
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/alloc/src/boxed.rs:1572:9
  77:     0x7f8ccf168a07 - std::sys::unix::thread::Thread::new::thread_start::h2a0e98fbc4ab4c32
                               at /rustc/240ff4c4a0d0936c9eeb783fa9ff5c0507a6ffb4/library/std/src/sys/unix/thread.rs:72:17
  78:     0x7f8ccf073259 - start_thread
  79:     0x7f8ccef885e3 - __GI___clone
  80:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (240ff4c4a 2021-07-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
   Compiling generic-array v0.11.2
error: could not compile `rustc_version`

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_version --edition=2018 /home/waffle/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc_version-0.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=67503ce5ddab7337 -C extra-filename=-67503ce5ddab7337 --out-dir /home/waffle/projects/repos/discovery/target/debug/deps -L dependency=/home/waffle/projects/repos/discovery/target/debug/deps --extern semver=/home/waffle/projects/repos/discovery/target/debug/deps/libsemver-3a20ab31769ba3a3.rmeta --cap-lints allow` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

</p>
</details>

**Comment by hellow554** [comment]
Sounds like a incremental compilation error. Do you know what you have changed between the two runs or before you did that? Can you maybe provide a `git diff` that shows the changes? A `cargo clean` should most likely resolve the issue nevertheless.

**Comment by WaffleLapkin** [comment]
@hellow554 I did literally nothing. No code changes, no `cargo clean`, etc.

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Without a way for others to reproduce the ICE, not much can be done at this point though. Closing.
