### ISSUE TITLE
[ICE] on minimal program on Nightly with edition 2021 and LTO

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#87626]
With the last Nightly I have problems even with a minimal program:

```
fn main() {}
```

Compiling it with:

```
rustc --edition 2021 -Z unstable-options -C lto temp.rs
```

Gives:

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 42, error_len: Some(1) }', /rustc/492723897e9b4db6701b3a75b72618d08a7d5319\compiler\rustc_serialize\src\opaque.rs:659:85
stack backtrace:
   0: rust_begin_unwind
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319\/library\std\src/panicking.rs:516:5
   1: core::panicking::panic_fmt
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319\/library\core\src/panicking.rs:93:14
   2: core::result::unwrap_failed
             at /rustc/492723897e9b4db6701b3a75b72618d08a7d5319\/library\core\src/result.rs:1599:5
   3: rustc_metadata::rmeta::decoder::__ty_decoder_impl::<impl rustc_serialize::serialize::Decoder for rustc_metadata::rmeta::decoder::DecodeContext>::read_str
   4: rustc_ast::ast::_DERIVE_rustc_serialize_Decodable_D_FOR_Attribute::<impl rustc_serialize::serialize::Decodable<__D> for rustc_ast::ast::Attribute>::decode
   5: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   6: rustc_middle::arena::Arena::alloc_from_iter
   7: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::item_attrs
   8: rustc_query_system::query::plumbing::get_query_impl
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::item_attrs
  10: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::get_attrs
  11: rustc_middle::ty::adt::AdtDef::new
  12: rustc_middle::ty::context::TyCtxt::alloc_adt_def
  13: rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_adt_def
  14: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::adt_def
  15: rustc_query_system::query::plumbing::get_query_impl
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::adt_def
  17: <rustc_middle::ty::adt::AdtDef as rustc_middle::ty::codec::RefDecodable<D>>::decode
  18: rustc_middle::ty::codec::<impl rustc_serialize::serialize::Decodable<D> for &rustc_middle::ty::TyS>::decode
  19: <rustc_metadata::rmeta::decoder::DecodeContext as rustc_middle::ty::codec::TyDecoder>::cached_ty_for_shorthand
  20: rustc_middle::ty::codec::<impl rustc_serialize::serialize::Decodable<D> for &rustc_middle::ty::TyS>::decode
  21: rustc_middle::ty::codec::<impl rustc_serialize::serialize::Decodable<D> for &rustc_middle::ty::TyS>::decode
  22: <rustc_metadata::rmeta::decoder::DecodeContext as rustc_middle::ty::codec::TyDecoder>::cached_ty_for_shorthand
  23: rustc_middle::ty::codec::<impl rustc_serialize::serialize::Decodable<D> for &rustc_middle::ty::TyS>::decode
  24: rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::get_type
  25: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::type_of
  26: rustc_query_system::query::plumbing::get_query_impl
  27: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
  28: rustc_symbol_mangling::legacy::mangle
  29: rustc_symbol_mangling::symbol_name_for_instance_in_crate
  30: rustc_codegen_ssa::back::symbol_export::symbol_name_for_instance_in_crate
  31: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  32: rustc_codegen_ssa::back::write::start_executing_work::{{closure}}
  33: rustc_codegen_ssa::back::write::start_executing_work
  34: rustc_codegen_ssa::back::write::start_async_codegen
  35: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  36: rustc_interface::passes::QueryContext::enter
  37: rustc_interface::queries::Queries::ongoing_codegen
  38: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  39: rustc_span::with_source_map
  40: rustc_interface::interface::create_compiler_and_run
  41: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (492723897 2021-07-29) running on x86_64-pc-windows-gnu

note: compiler flags: -Z unstable-options -C lto

query stack during panic:
#0 [item_attrs] collecting attributes of `std::detect::cache::Cache`
#1 [adt_def] computing ADT definition for `std::detect::cache::Cache`
#2 [type_of] computing type of `std::detect::cache::CACHE`
end of query stack
```

**Comment by hkratz** [comment]
Can't repro on Linux, maybe Windows-specific?

**Comment by ChrisDenton** [comment]
I can't seem to reproduce with either gnu or msvc toolchains on Windows, unless I'm missing something.

```plain
Z:\test> rustc +nightly-gnu --version
rustc 1.56.0-nightly (492723897 2021-07-29)
Z:\test> rustc +nightly-msvc --version
rustc 1.56.0-nightly (492723897 2021-07-29)
Z:\test> 'fn main() {}' > temp.rs
Z:\test> rustc +nightly-gnu --edition 2021 -Z unstable-options -C lto temp.rs
Z:\test> rustc +nightly-msvc --edition 2021 -Z unstable-options -C lto temp.rs
Z:\test>
```

Maybe there's something else in your environment affecting things?

**Comment by Aaron1011** [comment]
The ICE you're getting is very strange - I suspect that your libstd install might be corrupted. Can you try reinstalling the version of Rust that you're using?

**Comment by leonardo-m** [comment]
Thank you for your answers, I will try to clear the situation (I remove "-C lto" from the compiler arguments, it compiles).
