### ISSUE TITLE
no errors encountered even though `delay_span_bug` issued

### ISSUE THREAD

**Issue by tritone11** [rust-lang/rust#87757]
### Cargo.toml

```
redis = {verison = "0.21", features = ["async-std-comp", "cluster"] }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (0e63af5da 2021-01-31)
binary: rustc
commit-hash: 0e63af5da3400ace48a0345117980473fd21ad73
commit-date: 2021-01-31
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
error: internal compiler error: failed to process buffered lint here
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.21.0/src/macros.rs:5:54
    |
5   |           return Err(::std::convert::From::from($expr));
    |                                                        ^
    | 
   ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.21.0/src/aio.rs:444:18
    |
444 |               _ => fail!((
    |  __________________-
445 | |                 ErrorKind::ResponseError,
446 | |                 "Redis server refused to switch database"
447 | |             )),
    | |______________- in this macro invocation
    |
    = note: delayed at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (0e63af5da 2021-01-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `redis`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
```

</p>
</details>

**Comment by Aaron1011** [comment]
This should be fixed in the latest nightly.

**Comment by Mark-Simulacrum** [comment]
@Aaron1011 I'm seeing this in the 1.56 crater run -- did it perhaps slip into 1.56 and we need a backport?

```
[INFO] [stdout] error: internal compiler error: failed to process buffered lint here (dummy = false)
[INFO] [stdout]    --> atl-checker/src/emit_count.rs:5:49
[INFO] [stdout]     |
[INFO] [stdout] 5   |         eprintln!(concat!("[stats] ", $($msg)*));
[INFO] [stdout]     |                                                 ^
[INFO] [stdout]     |
[INFO] [stdout]    ::: atl-checker/src/algorithms/certain_zero/mod.rs:344:21
[INFO] [stdout]     |
[INFO] [stdout] 344 |                     emit_count!("worker received_dirty_token")
[INFO] [stdout]     |                     ------------------------------------------ in this macro invocation
[INFO] [stdout]     |
[INFO] [stdout]     = note: delayed at /rustc/f9a839ea0c4c4885a5366d877a75ad3525bbab5e/compiler/rustc_lint/src/early.rs:402:18
[INFO] [stdout]     = note: this error: internal compiler error originates in the macro `emit_count` (in Nightly builds, run with -Z macro-backtrace for more info)
```

* https://crater-reports.s3.amazonaws.com/beta-1.56-2/beta-2021-09-12/gh/d702e20.OnTheFlyATL/log.txt

**Comment by Aaron1011** [comment]
@Mark-Simulacrum That error is actually a previously-unreported bug that's present on the latest nightly. I'm working on a fix.

**Comment by Aaron1011** [comment]
@Mark-Simulacrum The new instance will be fixed by https://github.com/rust-lang/rust/pull/88996

**Comment by Mark-Simulacrum** [comment]
Thanks for the quick work! I'll beta-nominate the PR.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387757.20no.20errors.20encountered.20even.20though.20.60delay_span_bug.60.20i.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by pnkfelix** [comment]
fixed by #89527
