### ISSUE TITLE
Broken MIR in DefId(...): equate_normalized_input_or_output: `...` failed with `NoSolution`

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#87762]
### Code

```Rust
#![feature(generic_associated_types)]

pub trait BorrowedHandle {
    type Handle<'s, T>
    where
        T: 'static;
}

pub struct Owned<O, T, H>
where
    O: 'static,
    T: 'static,
    H: BorrowedHandle,
{
    _owner: &'static O,
    _borrow: H::Handle<'static, T>,
}

impl<O, T, H> Owned<O, T, H>
where
    H: BorrowedHandle,
{
    pub fn new(_: O, _: fn(&O) -> H::Handle<'_, T>) -> Self {
        todo!()
    }
}

struct PrimRef;

impl BorrowedHandle for PrimRef {
    type Handle<'s, T>
    where
        T: 'static,
    = &'s T;
}

type OwnedRef<T> = Owned<(T,), T, PrimRef>;

pub fn test() {
    let _: OwnedRef<u8> = Owned::new((42,), |v| &v.0); // < ERROR
}
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9a86a921f8e11054e77f0ca8ffe0f05b)

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (e3b1c12be 2021-08-02)
binary: rustc
commit-hash: e3b1c12becebd21d88ca9f4364d7db8d1d380c18
commit-date: 2021-08-02
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Error output

```
> cargo build

warning: Error finalizing incremental compilation session directory `/home/kimundi/projects/owning-ref-v2/target/debug/incremental/owning_ref_v2-234z64y4zgjj7/s-g13xkykhvy-vzm7mr-working`: No such file or directory (os error 2)

error: internal compiler error: broken MIR in DefId(0:27 ~ owning_ref_v2[893f]::test::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&[closure@src/lib.rs:40:45: 40:53]==&[closure@src/lib.rs:40:45: 40:53]` failed with `NoSolution`
  --> src/lib.rs:40:53
   |
40 |     let _: OwnedRef<u8> = Owned::new((42,), |v| &v.0);
   |                                                     ^
   |
   = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:299:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (e3b1c12be 2021-08-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `owning-ref-v2` (lib) generated 1 warning
error: could not compile `owning-ref-v2`; 1 warning emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/std/src/panicking.rs:516:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/std/src/panicking.rs:458:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
   9: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by ollpu** [comment]
Run into what seems like the same issue. Here's a simplified example:

```rust
#![feature(generic_associated_types)]

trait Trait {
    type Assoc<'a>;
}

fn f<T: Trait>(_: T, _: fn(T::Assoc<'_>)) {}

struct Type;

impl Trait for Type {
    type Assoc<'a> = &'a ();
}

fn main() {
    f(Type, |_| ());
}
```

![playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e5eeaf5e9267eb9a220367427dfb1be3)

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: broken MIR in DefId(0:14 ~ playground[4e8d]::main::{closure#0}) (bb0[0]): equate_normalized_input_or_output: `&[closure@src/main.rs:17:13: 17:19]==&[closure@src/main.rs:17:13: 17:19]` failed with `NoSolution`
  --> src/main.rs:17:19
   |
17 |     f(Type, |_| ());
   |                   ^
   |
   = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:299:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1065:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (574d37568 2021-08-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`
```

**Comment by jackh726** [comment]
This should be fixed by #85499
