### ISSUE TITLE
ICE on `rustc -C help | echo` on Windows

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/rust#87873]
I tried this code:

```bash
rustc -C help | echo
```

I expected to see this happen: `echo` should pipe the help output to stdout.

Instead, this happened (on stable and nightly): 

```
thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', lib
rary\std\src\io\stdio.rs:1193:9
<snip>

error: internal compiler error: unexpected panic

thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', lib
rary\std\src\io\stdio.rs:1193:9
<snip>

error: internal compiler error: unexpected panic

thread panicked while processing panic. aborting.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (ad981d58e 2021-08-08)
binary: rustc
commit-hash: ad981d58e1ca16bcf4072577934630deb11c5e14
commit-date: 2021-08-08
host: x86_64-pc-windows-msvc
release: 1.56.0-nightly
LLVM version: 12.0.1
```
and
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-pc-windows-msvc
release: 1.54.0
LLVM version: 12.0.1
```

<details><summary>BACKTRACE</summary><p>

```
thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', lib
rary\std\src\io\stdio.rs:935:9
stack backtrace:
   0:     0x7fffb421647f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Displ
ay>::fmt::hf141745c2b8f0ef6
   1:     0x7fffb423f68a - core::fmt::write::h056df61b7bc8b831
   2:     0x7fffb42099f8 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h528b029ec48da0bd
   3:     0x7fffb421a646 - std::panicking::take_hook::hb978b114d2382491
   4:     0x7fffb421a129 - std::panicking::take_hook::hb978b114d2382491
   5:     0x7fff7b4f99e7 - rustc_driver::report_ice::ha158ba3684d6a28e
   6:     0x7fffb421af40 - std::panicking::rust_panic_with_hook::h93d5982885e605de
   7:     0x7fffb421aa01 - rust_begin_unwind
   8:     0x7fffb4216dcf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Displ
ay>::fmt::hf141745c2b8f0ef6
   9:     0x7fffb421a959 - rust_begin_unwind
  10:     0x7fffb42723ec - std::panicking::begin_panic_fmt::h7c307d066c3b9e56
  11:     0x7fffb4208291 - std::io::stdio::_print::h7ac888e2b0b9fc90
  12:     0x7fff7b4f893b - rustc_driver::handle_options::ha327e2535327a5ef
  13:     0x7fff7b4ef9c7 - rustc_driver::RunCompiler::run::h41f0251ecadc65ad
  14:     0x7fff7b4ebf3e - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h46216c0117803f26
  15:     0x7fff7b4fb6fa - rustc_driver::main::he55654e9a1f96def
  16:     0x7ff6dbe5104e - <unknown>
  17:     0x7ff6dbe51006 - <unknown>
  18:     0x7ff6dbe5101c - <unknown>
  19:     0x7fffb421b35a - std::rt::lang_start_internal::h076b7fab8d534464
  20:     0x7ff6dbe51077 - <unknown>
  21:     0x7ff6dbe51284 - <unknown>
  22:     0x7fffe7cf7034 - BaseThreadInitThunk
  23:     0x7fffe97e2651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

thread 'main' panicked at 'failed printing to stdout: The pipe is being closed. (os error 232)', lib
rary\std\src\io\stdio.rs:935:9
stack backtrace:
   0:     0x7fffb421647f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Displ
ay>::fmt::hf141745c2b8f0ef6
   1:     0x7fffb423f68a - core::fmt::write::h056df61b7bc8b831
   2:     0x7fffb42099f8 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h528b029ec48da0bd
   3:     0x7fffb421a646 - std::panicking::take_hook::hb978b114d2382491
   4:     0x7fffb421a129 - std::panicking::take_hook::hb978b114d2382491
   5:     0x7fff7b4f99e7 - rustc_driver::report_ice::ha158ba3684d6a28e
   6:     0x7fffb421af40 - std::panicking::rust_panic_with_hook::h93d5982885e605de
   7:     0x7fffb421aa01 - rust_begin_unwind
   8:     0x7fffb4216dcf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Displ
ay>::fmt::hf141745c2b8f0ef6
   9:     0x7fffb421a959 - rust_begin_unwind
  10:     0x7fffb42723ec - std::panicking::begin_panic_fmt::h7c307d066c3b9e56
  11:     0x7fffb4208291 - std::io::stdio::_print::h7ac888e2b0b9fc90
  12:     0x7fff7b4f893b - rustc_driver::handle_options::ha327e2535327a5ef
  13:     0x7fff7b4f9d55 - rustc_driver::report_ice::ha158ba3684d6a28e
  14:     0x7fffb421af40 - std::panicking::rust_panic_with_hook::h93d5982885e605de
  15:     0x7fffb421aa01 - rust_begin_unwind
  16:     0x7fffb4216dcf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Displ
ay>::fmt::hf141745c2b8f0ef6
  17:     0x7fffb421a959 - rust_begin_unwind
  18:     0x7fffb42723ec - std::panicking::begin_panic_fmt::h7c307d066c3b9e56
  19:     0x7fffb4208291 - std::io::stdio::_print::h7ac888e2b0b9fc90
  20:     0x7fff7b4f893b - rustc_driver::handle_options::ha327e2535327a5ef
  21:     0x7fff7b4ef9c7 - rustc_driver::RunCompiler::run::h41f0251ecadc65ad
  22:     0x7fff7b4ebf3e - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h46216c0117803f26
  23:     0x7fff7b4fb6fa - rustc_driver::main::he55654e9a1f96def
  24:     0x7ff6dbe5104e - <unknown>
  25:     0x7ff6dbe51006 - <unknown>
  26:     0x7ff6dbe5101c - <unknown>
  27:     0x7fffb421b35a - std::rt::lang_start_internal::h076b7fab8d534464
  28:     0x7ff6dbe51077 - <unknown>
  29:     0x7ff6dbe51284 - <unknown>
  30:     0x7fffe7cf7034 - BaseThreadInitThunk
  31:     0x7fffe97e2651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

thread panicked while processing panic. aborting.

```

</p>
</details>

**Comment by ChrisDenton** [comment]
I can confirm for `cmd.exe`. Works in powershell though. It dates back to at least Rust 1.0:

```command
> rustc +1.0.0-gnu -C help | echo
ECHO is on.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread '<main>' panicked at 'failed printing to stdout: The pipe is being closed.
 (os error 232)', C:/bot/slave/stable-dist-rustc-win-64/build/src/libstd\io\stdio.rs:416
```

**Comment by ChrisDenton** [comment]
Minimal reproduction:

```rust
// main.rs
use std::io::{self, Write};
use std::{thread, time};

fn main() -> io::Result<()> {
    thread::sleep(time::Duration::from_millis(10));
    io::stdout().write(b"success?\n")?;
    Ok(())
}
```

```rust
// empty.rs
fn main() {}
```

```console
> rem run this in cmd.exe
> rustc main.rs
> rustc empty.rs
> .\main | .\empty
Error: Os { code: 232, kind: BrokenPipe, message: "The pipe is being closed." }
```

So the pipe gets broken which causes rustc to panic.

**Comment by dtolnay** [comment]
Repro for linux:

```console
$ rustc --print=cfg > /dev/full
thread 'rustc' panicked at 'failed printing to stdout: No space left on device (os error 28)', library/std/src/io/stdio.rs:1019:9
stack backtrace:
   0:     0x7f12ddd68f33 - std::backtrace_rs::backtrace::libunwind::trace::h527d8d64d53ade2d
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f12ddd68f33 - std::backtrace_rs::backtrace::trace_unsynchronized::hfb55b01517dd6379
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f12ddd68f33 - std::sys_common::backtrace::_print_fmt::hd134e914eea0bd97
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f12ddd68f33 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1480db11ec399d77
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f12dddc9d4f - core::fmt::write::h67ec4c4171c92b26
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/core/src/fmt/mod.rs:1247:17
   5:     0x7f12ddd5bed1 - std::io::Write::write_fmt::h3b12aef0fff2463b
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/io/mod.rs:1712:15
   6:     0x7f12ddd68d45 - std::sys_common::backtrace::_print::h584400135abdbd51
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f12ddd68d45 - std::sys_common::backtrace::print::hce41d3c8bd91096b
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f12ddd6b84f - std::panicking::default_hook::{{closure}}::h2043b657a3791225
   9:     0x7f12ddd6b507 - std::panicking::default_hook::h99252b8d3dd5719c
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/panicking.rs:293:9
  10:     0x7f12e0fdf915 - <rustc_driver_impl[d30cd2737d9d343a]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[cc19a662f3570270]::ops::function::FnOnce<(&core[cc19a662f3570270]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f12ddd6c005 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h222a2b674b9f4762
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/alloc/src/boxed.rs:1976:9
  12:     0x7f12ddd6c005 - std::panicking::rust_panic_with_hook::h7f49b36bf7f8ff77
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/panicking.rs:704:13
  13:     0x7f12ddd6bd73 - std::panicking::begin_panic_handler::{{closure}}::haa23a7352589e31e
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/panicking.rs:595:13
  14:     0x7f12ddd69376 - std::sys_common::backtrace::__rust_end_short_backtrace::h3d0cf6e3c96e3fe9
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f12ddd6ba72 - rust_begin_unwind
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/panicking.rs:584:5
  16:     0x7f12dddc5fe3 - core::panicking::panic_fmt::hf4b4ea11e3fdb110
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/core/src/panicking.rs:67:14
  17:     0x7f12ddd5aa07 - std::io::stdio::print_to::h55760b9ede306280
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/io/stdio.rs:1019:9
  18:     0x7f12ddd5aa07 - std::io::stdio::_print::h93deb6099db33eab
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/io/stdio.rs:1095:5
  19:     0x7f12e01e163b - rustc_driver_impl[d30cd2737d9d343a]::print_crate_info
  20:     0x7f12e0fb8e01 - rustc_span[9551eaa044f53f4f]::set_source_map::<(), rustc_interface[c2b70c9b1dae0906]::interface::run_compiler<(), rustc_driver_impl[d30cd2737d9d343a]::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
  21:     0x7f12e0fb6d59 - std[71a32ca0600a6a04]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c2b70c9b1dae0906]::util::run_in_thread_pool_with_globals<rustc_interface[c2b70c9b1dae0906]::interface::run_compiler<(), rustc_driver_impl[d30cd2737d9d343a]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  22:     0x7f12e0fe25b4 - std[71a32ca0600a6a04]::panicking::try::<(), core[cc19a662f3570270]::panic::unwind_safe::AssertUnwindSafe<<std[71a32ca0600a6a04]::thread::Builder>::spawn_unchecked_<rustc_interface[c2b70c9b1dae0906]::util::run_in_thread_pool_with_globals<rustc_interface[c2b70c9b1dae0906]::interface::run_compiler<(), rustc_driver_impl[d30cd2737d9d343a]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1}::{closure#0}>>
  23:     0x7f12e0fb0cf1 - <<std[71a32ca0600a6a04]::thread::Builder>::spawn_unchecked_<rustc_interface[c2b70c9b1dae0906]::util::run_in_thread_pool_with_globals<rustc_interface[c2b70c9b1dae0906]::interface::run_compiler<(), rustc_driver_impl[d30cd2737d9d343a]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[cc19a662f3570270]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f12ddd763e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf15d802f31f86225
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/alloc/src/boxed.rs:1962:9
  25:     0x7f12ddd763e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hac564355b46c52d6
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/alloc/src/boxed.rs:1962:9
  26:     0x7f12ddd763e5 - std::sys::unix::thread::Thread::new::thread_start::h86fb3aedb7811f07
                               at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f12dda94b43 - start_thread
                               at ./nptl/pthread_create.c:442:8
  28:     0x7f12ddb26a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  29:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (7f94b314c 2023-04-23) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

**Comment by Enselic** [comment]
Triage: The Linux repro looks like a different issue than originally reported ("No space left on device" rather than "The pipe is being closed").

**Comment by ChrisDenton** [comment]
This is no longer an ICE and fails more gracefully. In cmd prompt:

```
>rustc -C help | echo
ECHO is on.
```
