### ISSUE TITLE
ICE when trying to call closure in const fn w feature const_trait_impl

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#88037]
### Code

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=93d552fbeb987980256c88986d12fa29)

```rust
#![feature(const_trait_impl)]

const fn foo() -> u32 {
    let f = || 42;
    f()
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (2827db2b1 2021-08-01)
binary: rustc
commit-hash: 2827db2b137e899242e81f1beea39ae26e245153
commit-date: 2021-08-01
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```
### Error output
```
   Compiling ice v0.1.0 (/home/albin/rust/ice)
error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1885:13: to get the signature of a closure, use `substs.as_closure().sig()` not `fn_sig()`

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1034:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (2827db2b1 2021-08-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [fn_sig] computing function signature of `foo::{closure#0}`
#1 [mir_const_qualif] const checking `foo`
end of query stack
error: could not compile `ice`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1034:9                                                                                                                        
stack backtrace:                                                                                                                                                                                          
   0: std::panicking::begin_panic                                                                                                                                                                         
   1: std::panic::panic_any                                                                                                                                                                               
   2: rustc_errors::HandlerInner::bug                                                                                                                                                                     
   3: rustc_errors::Handler::bug                                                                                                                                                                          
   4: rustc_middle::ty::context::tls::with_opt                                                                                                                                                            
   5: rustc_middle::util::bug::opt_span_bug_fmt                                                                                                                                                           
   6: rustc_middle::util::bug::bug_fmt                                                                                                                                                                    
   7: rustc_typeck::collect::fn_sig                                                                                                                                                                       
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl                                                                                                                                   
   9: rustc_data_structures::stack::ensure_sufficient_stack                                                                                                                                               
  10: rustc_query_system::query::plumbing::force_query_with_job                                                                                                                                           
  11: rustc_query_system::query::plumbing::get_query_impl                                                                                                                                                 
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::fn_sig                                                                                                                         
  13: <rustc_mir::transform::check_consts::check::Checker as rustc_middle::mir::visit::Visitor>::visit_terminator                                                                                         
  14: rustc_mir::transform::check_consts::check::Checker::check_body                                                                                                                                      
  15: rustc_mir::transform::mir_const_qualif                                                                                                                                                              
  16: core::ops::function::FnOnce::call_once                                                                                                                                                              
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl                                                                                                                                   
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::force_query_with_job
  20: rustc_query_system::query::plumbing::get_query_impl
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_const_qualif
  22: rustc_middle::mir::query::<impl rustc_middle::ty::context::TyCtxt>::mir_const_qualif_opt_const_arg
  23: rustc_mir::transform::mir_promoted
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_promoted
  28: rustc_mir::borrow_check::mir_borrowck
  29: core::ops::function::FnOnce::call_once
  30: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  31: rustc_data_structures::stack::ensure_sufficient_stack
  32: rustc_query_system::query::plumbing::force_query_with_job
  33: rustc_query_system::query::plumbing::get_query_impl
  34: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  35: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  36: rustc_interface::passes::analysis
  37: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  40: rustc_data_structures::stack::ensure_sufficient_stack
  41: rustc_query_system::query::plumbing::force_query_with_job
  42: rustc_query_system::query::plumbing::get_query_impl
  43: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  44: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  45: rustc_span::with_source_map
  46: rustc_interface::interface::create_compiler_and_run
  47: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by usbalbin** [comment]
Replacing the call to `f` with just the literal `42` avoids the ICE, instead showing the expected error: [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c21876be0612e59a186fb1e5fd76ad86)

```rust
#![feature(const_trait_impl)]

const fn foo() -> u32 {
    let f = || 42;
    42 //f()
}

fn main() {}
```

**Comment by theo-lw** [comment]
I checked the playground link, and this seems to have been fixed in the latest nightly build (2021-08-29 2f662b14033c4369b0a7).

**Comment by usbalbin** [comment]
Great! Thanks :)
