### ISSUE TITLE
'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(9931bc8d27ddda19-903113a1b80b9ecd): Ok(EvaluatedToOk)'

### ISSUE THREAD

**Issue by sea212** [rust-lang/rust#88158]
### Code

I am not able to provide a minimal example, sorry! It occurred after the following changes: https://github.com/zeitgeistpm/zeitgeist/commit/43a84b66b3a2e67525be8e16e4d228e045dd8854

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (ad981d58e 2021-08-08)
binary: rustc
commit-hash: ad981d58e1ca16bcf4072577934630deb11c5e14
commit-date: 2021-08-08
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Error output

```
thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(9931bc8d27ddda19-903113a1b80b9ecd): Ok(EvaluatedToOk)', /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/compiler/rustc_query_system/src/query/plumbing.rs:626:9

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `std::option::Option<sp_utils::mpsc::inner::TracingUnboundedSender<sc_transaction_pool::revalidation::WorkerPayload<sc_transaction_pool::FullChainApi<sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>>>>: std::marker::Sync`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [jsonrpc_core::IoDelegate<substrate_frame_rpc_system::FullSystem<sc_transaction_pool::BasicPool<sc_transaction_pool::FullChainApi<sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::RpcMetadata>], item_def_id: DefId(2:7270 ~ core[734c]::iter::traits::collect::IntoIterator::IntoIter) } } }`
#2 [normalize_generic_arg_after_erasing_regions] normalizing `for<'r> fn(&'r <jsonrpc_core::IoDelegate<substrate_frame_rpc_system::FullSystem<sc_transaction_pool::BasicPool<sc_transaction_pool::FullChainApi<sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::RpcMetadata> as std::iter::IntoIterator>::IntoIter) -> (usize, std::option::Option<usize>) {<<jsonrpc_core::IoDelegate<substrate_frame_rpc_system::FullSystem<sc_transaction_pool::BasicPool<sc_transaction_pool::FullChainApi<sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::client::client::Client<sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::LocalCallExecutor<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, sc_client_db::Backend<sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_executor::NativeExecutor<service::Executor>>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>, zeitgeist_runtime::RuntimeApi>, sp_runtime::generic::Block<sp_runtime::generic::Header<u64, sp_runtime::traits::BlakeTwo256>, sp_runtime::OpaqueExtrinsic>>, sc_service::RpcMetadata> as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>::size_hint}`
#3 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: rust_begin_unwind
             at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:460:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_data_structures::stack::ensure_sufficient_stack
   5: rustc_query_system::query::plumbing::get_query_impl
   6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation
   7: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
   8: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
   9: rustc_trait_selection::traits::fulfill::FulfillProcessor::process_trait_obligation
  10: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  11: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  12: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  13: <rustc_infer::infer::InferCtxtBuilder as rustc_trait_selection::infer::InferCtxtBuilderExt>::enter_canonical_trait_query
  14: rustc_traits::normalize_projection_ty::normalize_projection_ty
  15: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  16: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::get_query_impl
  19: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_projection_ty
  20: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  21: rustc_middle::ty::fold::TypeFoldable::fold_with
  22: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with
  23: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  24: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize
  25: rustc_infer::infer::InferCtxtBuilder::enter
  26: core::ops::function::FnOnce::call_once
  27: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  28: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  29: rustc_data_structures::stack::ensure_sufficient_stack
  30: rustc_query_system::query::plumbing::get_query_impl
  31: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_generic_arg_after_erasing_regions
  32: rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder::normalize_generic_arg_after_erasing_regions
  33: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  34: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  35: rustc_mir::monomorphize::collector::collect_neighbours
  36: rustc_mir::monomorphize::collector::collect_items_rec
  37: rustc_mir::monomorphize::collector::collect_items_rec
  38: rustc_mir::monomorphize::collector::collect_items_rec
  39: rustc_mir::monomorphize::collector::collect_items_rec
  40: rustc_mir::monomorphize::collector::collect_items_rec
  41: rustc_mir::monomorphize::collector::collect_items_rec
  42: rustc_mir::monomorphize::collector::collect_items_rec
  43: rustc_mir::monomorphize::collector::collect_items_rec
  44: rustc_mir::monomorphize::collector::collect_items_rec
  45: rustc_mir::monomorphize::collector::collect_items_rec
  46: rustc_mir::monomorphize::collector::collect_items_rec
  47: rustc_mir::monomorphize::collector::collect_items_rec
  48: rustc_mir::monomorphize::collector::collect_items_rec
  49: rustc_mir::monomorphize::collector::collect_items_rec
  50: rustc_mir::monomorphize::collector::collect_items_rec
  51: rustc_mir::monomorphize::collector::collect_items_rec
  52: rustc_mir::monomorphize::collector::collect_items_rec
  53: rustc_mir::monomorphize::collector::collect_items_rec
  54: rustc_mir::monomorphize::collector::collect_items_rec
  55: rustc_mir::monomorphize::collector::collect_items_rec
  56: rustc_mir::monomorphize::collector::collect_items_rec
  57: rustc_mir::monomorphize::collector::collect_items_rec
  58: rustc_mir::monomorphize::collector::collect_items_rec
  59: rustc_mir::monomorphize::collector::collect_items_rec
  60: rustc_mir::monomorphize::collector::collect_items_rec
  61: rustc_mir::monomorphize::collector::collect_crate_mono_items
  62: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  63: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  64: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  65: rustc_data_structures::stack::ensure_sufficient_stack
  66: rustc_query_system::query::plumbing::force_query_with_job
  67: rustc_query_system::query::plumbing::get_query_impl
  68: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items
  69: rustc_codegen_ssa::base::codegen_crate
  70: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  71: rustc_interface::passes::QueryContext::enter
  72: rustc_interface::queries::Queries::ongoing_codegen
  73: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  74: rustc_span::with_source_map
  75: rustc_interface::interface::create_compiler_and_run
  76: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by asquared31415** [comment]
This is likely #84341
`cargo clean` and then building again should fix the issue
