### ISSUE TITLE
internal compiler error: encountered incremental compilation error with predicates_of(winit[a4e3]::dpi::Pixel)

### ISSUE THREAD

**Issue by coreh** [rust-lang/rust#88318]
Hey :wave:  Just hit an incremental compilation bug in 1.54.0.

As per #84970, I'm filing a bug.

Edit: Ouch, just realized I used the wrong template for this. I can't seem to tag it with *I-ICE* or *T-Compiler*. Sorry!

### Meta
`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
error: internal compiler error: encountered incremental compilation error with predicates_of(winit[a4e3]::dpi::Pixel)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p byo` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for predicates_of(winit[a4e3]::dpi::Pixel): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Copy>), []), /home/coreh/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/dpi.rs:104:18: 104:22 (#0)), (Binder(TraitPredicate(<Self as std::convert::Into<f64>>), []), /home/coreh/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/dpi.rs:104:25: 104:34 (#0)), (Binder(TraitPredicate(<Self as smithay::reexports::winit::dpi::Pixel>), []), /home/coreh/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/dpi.rs:104:1: 109:2 (#0))] }', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/compiler/rustc_query_system/src/query/plumbing.rs:620:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   6: rustc_middle::ty::generics::GenericPredicates::instantiate_identity_into
   7: rustc_middle::ty::generics::GenericPredicates::instantiate_identity
   8: rustc_ty_utils::ty::param_env
   9: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  10: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::get_query_impl
  13: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::param_env
  14: rustc_middle::ty::layout::<impl rustc_middle::ty::instance::Instance>::fn_sig_for_fn_abi
  15: <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_middle::ty::layout::FnAbiExt<C>>::of_instance
  16: rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn
  17: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  18: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  19: rustc_codegen_llvm::base::compile_codegen_unit
  20: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  21: rustc_interface::passes::QueryContext::enter
  22: rustc_interface::queries::Queries::ongoing_codegen
  23: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  24: rustc_span::with_source_map
  25: rustc_interface::interface::create_compiler_and_run
  26: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0 (a178d0322 2021-07-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `smithay::reexports::winit::dpi::Pixel`
#1 [param_env] computing normalized predicates of `smithay::reexports::winit::dpi::Pixel::cast`
end of query stack
error: aborting due to previous error

error: could not compile `byo`

Caused by:
  process didn't exit successfully: `rustc --crate-name byo --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=d5723ea90ce787d1 -C extra-filename=-d5723ea90ce787d1 --out-dir /home/coreh/Projects/byo/target/debug/deps -C incremental=/home/coreh/Projects/byo/target/debug/incremental -L dependency=/home/coreh/Projects/byo/target/debug/deps --extern byo=/home/coreh/Projects/byo/target/debug/deps/libbyo-a47d292da12527d5.rlib --extern femtovg=/home/coreh/Projects/byo/target/debug/deps/libfemtovg-8e2b43dbe34f4d7e.rlib --extern nalgebra=/home/coreh/Projects/byo/target/debug/deps/libnalgebra-b007309f762a1029.rlib --extern rpds=/home/coreh/Projects/byo/target/debug/deps/librpds-4ef582fe78ec83c9.rlib --extern slog=/home/coreh/Projects/byo/target/debug/deps/libslog-df1eb6c4a414ca1b.rlib --extern slog_async=/home/coreh/Projects/byo/target/debug/deps/libslog_async-83ae1585ccf03a44.rlib --extern slog_term=/home/coreh/Projects/byo/target/debug/deps/libslog_term-9c6528442997f443.rlib --extern smithay=/home/coreh/Projects/byo/target/debug/deps/libsmithay-f69dfb03a955de4c.rlib --extern thiserror=/home/coreh/Projects/byo/target/debug/deps/libthiserror-e8c8f299b78864ca.rlib --extern uuid=/home/coreh/Projects/byo/target/debug/deps/libuuid-c589a0b3228727a2.rlib -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu -L native=/usr/lib/x86_64-linux-gnu` (exit status: 101)
```

</p>
</details>

**Comment by jackh726** [comment]
cc @Aaron1011

**Comment by coreh** [comment]
> @coreh Could you share the repository where this happened?

This is code for a personal project that I'm not really ready to open source/make publicly available at this time.

I can share it with you in private if it helps, but I don't recall the exact changes that I made that triggered this. I was working on the code in one day, came back one the next day and when I tried to compile it it failed like this.

**Comment by carols10cents** [comment]
> @carols10cents Do you have a record of what kind of changes you were making? Is there a particular branch you were working on?

I don't have a record of exactly what I changed just before getting the ICE, sorry... I can try to change my workflow to commit before each time I run rustc to try and catch it happening again, if that would be helpful?

**Comment by Enselic** [comment]
Triage: Without a way to reproduce this, not much can be done at this point. Of course feel free to reopen if a way to reproduce is found.
