### ISSUE TITLE
Found unstable fingerprints for `item_children`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#88427]
I tried this code: https://github.com/rust-lang/rust/commit/5b9d468201e8825b0429ea7439e79cf3ff1bf3fd, and then renamed the top-level directory from `rust` to `rustc`.

I expected to see this happen: The compiler can bootstrap itself (possibly giving an error about the change in rustdoc, I forget if that code compiles).

Instead, this happened:

<details>

```
error: internal compiler error: encountered incremental compilation error with item_children(build_helper[daa7])
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p build_script_build` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for item_children(build_helper[daa7]): [Export { ident: tracked_env_var_os#0, res: Def(Fn, DefId(19:42 ~ build_helper[daa7]::tracked_env_var_os)), span: /home/joshua/rustc/src/build_helper/lib.rs:36:1: 36:81 (#0), vis: Public }, Export { ident: restore_library_path#0, res: Def(Fn, DefId(19:44 ~ build_helper[daa7]::restore_library_path)), span: /home/joshua/rustc/src/build_helper/lib.rs:49:1: 49:30 (#0), vis: Public }, Export { ident: run_verbose#0, res: Def(Fn, DefId(19:45 ~ build_helper[daa7]::run_verbose)), span: /home/joshua/rustc/src/build_helper/lib.rs:59:1: 59:38 (#0), vis: Public }, Export { ident: run#0, res: Def(Fn, DefId(19:46 ~ build_helper[daa7]::run)), span: /home/joshua/rustc/src/build_helper/lib.rs:64:1: 64:30 (#0), vis: Public }, Export { ident: try_run#0, res: Def(Fn, DefId(19:47 ~ build_helper[daa7]::try_run)), span: /home/joshua/rustc/src/build_helper/lib.rs:70:1: 70:42 (#0), vis: Public }, Export { ident: run_suppressed#0, res: Def(Fn, DefId(19:48 ~ build_helper[daa7]::run_suppressed)), span: /home/joshua/rustc/src/build_helper/lib.rs:85:1: 85:41 (#0), vis: Public }, Export { ident: try_run_suppressed#0, res: Def(Fn, DefId(19:49 ~ build_helper[daa7]::try_run_suppressed)), span: /home/joshua/rustc/src/build_helper/lib.rs:91:1: 91:53 (#0), vis: Public }, Export { ident: gnu_target#0, res: Def(Fn, DefId(19:50 ~ build_helper[daa7]::gnu_target)), span: /home/joshua/rustc/src/build_helper/lib.rs:111:1: 111:40 (#0), vis: Public }, Export { ident: make#0, res: Def(Fn, DefId(19:51 ~ build_helper[daa7]::make)), span: /home/joshua/rustc/src/build_helper/lib.rs:121:1: 121:35 (#0), vis: Public }, Export { ident: output#0, res: Def(Fn, DefId(19:52 ~ build_helper[daa7]::output)), span: /home/joshua/rustc/src/build_helper/lib.rs:134:1: 134:43 (#0), vis: Public }, Export { ident: rerun_if_changed_anything_in_dir#0, res: Def(Fn, DefId(19:53 ~ build_helper[daa7]::rerun_if_changed_anything_in_dir)), span: /home/joshua/rustc/src/build_helper/lib.rs:149:1: 149:52 (#0), vis: Public }, Export { ident: mtime#0, res: Def(Fn, DefId(19:57 ~ build_helper[daa7]::mtime)), span: /home/joshua/rustc/src/build_helper/lib.rs:167:1: 167:40 (#0), vis: Public }, Export { ident: up_to_date#0, res: Def(Fn, DefId(19:59 ~ build_helper[daa7]::up_to_date)), span: /home/joshua/rustc/src/build_helper/lib.rs:175:1: 175:50 (#0), vis: Public }, Export { ident: dir_up_to_date#0, res: Def(Fn, DefId(19:60 ~ build_helper[daa7]::dir_up_to_date)), span: /home/joshua/rustc/src/build_helper/lib.rs:191:1: 191:61 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: fail#0, res: Def(Fn, DefId(19:63 ~ build_helper[daa7]::fail)), span: /home/joshua/rustc/src/build_helper/lib.rs:202:1: 202:22 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: OsStr#0, res: Def(Struct, DefId(1:2763 ~ std[7817]::ffi::os_str::OsStr)), span: /home/joshua/rustc/src/build_helper/lib.rs:1:16: 1:21 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: OsString#0, res: Def(Struct, DefId(1:2760 ~ std[7817]::ffi::os_str::OsString)), span: /home/joshua/rustc/src/build_helper/lib.rs:1:23: 1:31 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: Display#0, res: Def(Trait, DefId(2:8969 ~ core[8a40]::fmt::Display)), span: /home/joshua/rustc/src/build_helper/lib.rs:2:5: 2:22 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: Path#0, res: Def(Struct, DefId(1:6928 ~ std[7817]::path::Path)), span: /home/joshua/rustc/src/build_helper/lib.rs:3:17: 3:21 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: PathBuf#0, res: Def(Struct, DefId(1:6821 ~ std[7817]::path::PathBuf)), span: /home/joshua/rustc/src/build_helper/lib.rs:3:23: 3:30 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: Command#0, res: Def(Struct, DefId(1:7161 ~ std[7817]::process::Command)), span: /home/joshua/rustc/src/build_helper/lib.rs:4:20: 4:27 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: Stdio#0, res: Def(Struct, DefId(1:7216 ~ std[7817]::process::Stdio)), span: /home/joshua/rustc/src/build_helper/lib.rs:4:29: 4:34 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: SystemTime#0, res: Def(Struct, DefId(1:11653 ~ std[7817]::time::SystemTime)), span: /home/joshua/rustc/src/build_helper/lib.rs:5:17: 5:27 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: UNIX_EPOCH#0, res: Def(Const, DefId(1:8618 ~ std[7817]::time::UNIX_EPOCH)), span: /home/joshua/rustc/src/build_helper/lib.rs:5:29: 5:39 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: env#0, res: Def(Mod, DefId(1:2123 ~ std[7817]::env)), span: /home/joshua/rustc/src/build_helper/lib.rs:6:11: 6:14 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: env#0, res: Def(Macro(Bang), DefId(2:23 ~ core[8a40]::macros::builtin::env)), span: /home/joshua/rustc/src/build_helper/lib.rs:6:11: 6:14 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: fs#0, res: Def(Mod, DefId(1:2951 ~ std[7817]::fs)), span: /home/joshua/rustc/src/build_helper/lib.rs:6:16: 6:18 (#0), vis: Restricted(DefId(19:0 ~ build_helper[daa7])) }, Export { ident: t#0, res: Def(Macro(Bang), DefId(19:41 ~ build_helper[daa7]::t)), span: /home/joshua/rustc/src/build_helper/lib.rs:17:1: 31:2 (#0), vis: Public }]', /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/compiler/rustc_query_system/src/query/plumbing.rs:624:9
stack backtrace:
   0:     0x7f623babab00 - std::backtrace_rs::backtrace::libunwind::trace::hff4d1766e93f64f1
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f623babab00 - std::backtrace_rs::backtrace::trace_unsynchronized::h56bbc8eb78770bcb
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f623babab00 - std::sys_common::backtrace::_print_fmt::h5c8e75464faca780
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f623babab00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48b88277def8b362
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f623bb2863c - core::fmt::write::h3381b3176fe2b3d3
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1115:17
   5:     0x7f623baac3e5 - std::io::Write::write_fmt::hd42607e5d8e44db0
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/io/mod.rs:1665:15
   6:     0x7f623babe81b - std::sys_common::backtrace::_print::ha537687d6c17dd0d
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f623babe81b - std::sys_common::backtrace::print::h61376ae57d131d72
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f623babe81b - std::panicking::default_hook::{{closure}}::h0f7208c0b9644a54
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:208:50
   9:     0x7f623babe2f1 - std::panicking::default_hook::hdac7fc06578c14ce
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:225:9
  10:     0x7f623c2d2511 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::he0fb23ee363efe57
  11:     0x7f623babf049 - std::panicking::rust_panic_with_hook::h72b21c283da3d1ef
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:626:17
  12:     0x7f623babeb07 - std::panicking::begin_panic_handler::{{closure}}::he5778f1729cff84a
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:519:13
  13:     0x7f623babafdc - std::sys_common::backtrace::__rust_end_short_backtrace::h2d11ca8b453b4b1d
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f623babea69 - rust_begin_unwind
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:515:5
  15:     0x7f623ba87a6b - std::panicking::begin_panic_fmt::h746518bde832d259
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:457:5
  16:     0x7f623cb1ca6c - rustc_query_system::query::plumbing::incremental_verify_ich::hd1e8c63d05db1cbd
  17:     0x7f623cb3c579 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::hafd5cfc2b75a38bb
  18:     0x7f623d95e81b - rustc_query_system::query::plumbing::get_query_impl::h38370b667150fb10
  19:     0x7f623d9d16de - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::item_children::h6a98773b83135e0c
  20:     0x7f623da90d20 - core::ops::function::FnOnce::call_once::hcc63c4515db47770
  21:     0x7f623cc805b4 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::he2c8ff830776acc7
  22:     0x7f623cb38c07 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h892c43358f7624b0
  23:     0x7f623cd2637f - rustc_data_structures::stack::ensure_sufficient_stack::he32d0c7c1b3b1290
  24:     0x7f623e2722e2 - rustc_query_system::query::plumbing::get_query_impl::h4b7ffb37b2bf1d9e
  25:     0x7f623e34c9b0 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::visible_parent_map::h484278cc4309205b
  26:     0x7f623dd21123 - rustc_middle::ty::print::pretty::PrettyPrinter::try_print_visible_def_path_recur::h0fa218b8b1e0876d
    Checking rustc_serialize v0.0.0 (/home/joshua/rustc/compiler/rustc_serialize)
    Checking petgraph v0.5.1
    Checking object v0.26.1
  27:     0x7f623dd2657c - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::h1999993a945ba7fc
  28:     0x7f623dd26a8c - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::h1999993a945ba7fc
  29:     0x7f623e6ac964 - <rustc_middle::ty::print::pretty::TraitRefPrintOnlyTraitPath as core::fmt::Display>::fmt::hd17b21c965fd08ee
  30:     0x7f623bb2863c - core::fmt::write::h3381b3176fe2b3d3
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1115:17
  31:     0x7f623d21787c - rustc_middle::ty::print::pretty::<impl rustc_middle::ty::print::Print<P> for rustc_middle::ty::sty::TraitRef>::print::h271f88060a6635a0
  32:     0x7f623d218478 - rustc_middle::ty::print::pretty::<impl core::fmt::Display for rustc_middle::ty::sty::TraitRef>::fmt::h4d06952020985627
  33:     0x7f623d14403d - std::thread::local::LocalKey<T>::with::h4db2ccc26f6ba94f
  34:     0x7f623d212bd3 - rustc_middle::ty::structural_impls::<impl core::fmt::Debug for rustc_middle::ty::sty::TraitRef>::fmt::hd6091a68c92a58b1
  35:     0x7f623bb2863c - core::fmt::write::h3381b3176fe2b3d3
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1115:17
  36:     0x7f623bb29804 - core::fmt::Formatter::write_fmt::hef36192260f6dab1
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1561:9
  37:     0x7f623d1ecabb - rustc_middle::ty::structural_impls::<impl core::fmt::Debug for rustc_middle::ty::PredicateKind>::fmt::h48d036d2aba217ad
  38:     0x7f623bb2574f - core::fmt::builders::DebugTuple::field::{{closure}}::hc7fd2be118f7d828
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:335:17
  39:     0x7f623bb2574f - core::result::Result<T,E>::and_then::ha1d3e75d8f6ab251
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/result.rs:948:22
  40:     0x7f623bb2574f - core::fmt::builders::DebugTuple::field::h12c72337ac093650
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:322:23
  41:     0x7f623d21930a - <rustc_middle::ty::sty::Binder<T> as core::fmt::Debug>::fmt::h2bacb59df45e9977
  42:     0x7f623bb2863c - core::fmt::write::h3381b3176fe2b3d3
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1115:17
  43:     0x7f623bb29804 - core::fmt::Formatter::write_fmt::hef36192260f6dab1
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1561:9
  44:     0x7f623d1de91a - <&T as core::fmt::Debug>::fmt::he942a9135a1cf751
  45:     0x7f623bb2574f - core::fmt::builders::DebugTuple::field::{{closure}}::hc7fd2be118f7d828
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:335:17
  46:     0x7f623bb2574f - core::result::Result<T,E>::and_then::ha1d3e75d8f6ab251
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/result.rs:948:22
  47:     0x7f623bb2574f - core::fmt::builders::DebugTuple::field::h12c72337ac093650
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:322:23
  48:     0x7f623d1ddeba - <&T as core::fmt::Debug>::fmt::h1d1630edb1902070
  49:     0x7f623bb258ec - core::fmt::builders::DebugInner::entry::{{closure}}::h250a6c8aab5520ff
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:407:17
  50:     0x7f623bb258ec - core::result::Result<T,E>::and_then::h5a357643fd70ba65
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/result.rs:948:22
  51:     0x7f623bb258ec - core::fmt::builders::DebugInner::entry::hb489f15b3901feb3
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:393:23
  52:     0x7f623bb259b9 - core::fmt::builders::DebugSet::entry::hfb9a35fd343788c1
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:482:9
  53:     0x7f623d21ef6d - core::fmt::builders::DebugList::entries::hccfda9b032f4d7b9
  54:     0x7f623d1de2b8 - <&T as core::fmt::Debug>::fmt::h69002c65a07c8e5e
  55:     0x7f623bb254bd - core::fmt::builders::DebugStruct::field::{{closure}}::h6486d994362fc82b
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:154:17
  56:     0x7f623bb254bd - core::result::Result<T,E>::and_then::h3504d96175cc5bae
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/result.rs:948:22
  57:     0x7f623bb254bd - core::fmt::builders::DebugStruct::field::h2d6292e15255a66d
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/builders.rs:137:23
  58:     0x7f623d15073e - <rustc_middle::ty::generics::GenericPredicates as core::fmt::Debug>::fmt::h72b77eb454512a02
  59:     0x7f623bb2863c - core::fmt::write::h3381b3176fe2b3d3
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:1115:17
  60:     0x7f623babec7f - core::fmt::Write::write_fmt::hd3f6e421de2c4340
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/fmt/mod.rs:187:9
  61:     0x7f623babec7f - std::panicking::begin_panic_handler::PanicPayload::fill::{{closure}}::h4954685877905da9
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:481:22
  62:     0x7f623babec7f - core::option::Option<T>::get_or_insert_with::h6916d48a346e0cc2
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/core/src/option.rs:1270:26
  63:     0x7f623babec7f - std::panicking::begin_panic_handler::PanicPayload::fill::had004f1089642f36
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:479:13
  64:     0x7f623babec7f - <std::panicking::begin_panic_handler::PanicPayload as core::panic::BoxMeUp>::get::hfc53357263322d10
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:497:13
  65:     0x7f623babf034 - std::panicking::rust_panic_with_hook::h72b21c283da3d1ef
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:625:34
  66:     0x7f623babeb07 - std::panicking::begin_panic_handler::{{closure}}::he5778f1729cff84a
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:519:13
  67:     0x7f623babafdc - std::sys_common::backtrace::__rust_end_short_backtrace::h2d11ca8b453b4b1d
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys_common/backtrace.rs:141:18
  68:     0x7f623babea69 - rust_begin_unwind
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:515:5
  69:     0x7f623ba87a6b - std::panicking::begin_panic_fmt::h746518bde832d259
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/panicking.rs:457:5
  70:     0x7f623e2e358c - rustc_query_system::query::plumbing::incremental_verify_ich::hbe1ace616008ab8e
  71:     0x7f623d9988e8 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h462d7d11364e5874
  72:     0x7f623d969e7c - rustc_query_system::query::plumbing::get_query_impl::h69045321bf6a58d1
  73:     0x7f623d9ceb74 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::explicit_predicates_of::h3547a6881748190b
  74:     0x7f623d5c06fb - rustc_typeck::collect::predicates_defined_on::hbdd16e4a17ba8af2
  75:     0x7f623e39ffdb - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h6724aa5c8ff6815b
  76:     0x7f623d9988be - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h462d7d11364e5874
  77:     0x7f623d969e7c - rustc_query_system::query::plumbing::get_query_impl::h69045321bf6a58d1
  78:     0x7f623d9cea74 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_defined_on::hce864edf04101e0d
  79:     0x7f623d5c0d82 - rustc_typeck::collect::predicates_of::hccffaf96e7796102
  80:     0x7f623e39ffdb - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h6724aa5c8ff6815b
  81:     0x7f623d9988be - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h462d7d11364e5874
  82:     0x7f623d969e7c - rustc_query_system::query::plumbing::get_query_impl::h69045321bf6a58d1
  83:     0x7f623d9cdf10 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of::h2c7b54bc732fa7c8
  84:     0x7f623d5d2f52 - rustc_ty_utils::ty::param_env::hd628288b8aeaefb6
    Checking crossbeam-queue v0.2.3
  85:     0x7f623e36f1a7 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h83799e2d6e223566
  86:     0x7f623e3e78aa - rustc_data_structures::stack::ensure_sufficient_stack::h0f3605d04d4f5b64
  87:     0x7f623e2c1bad - rustc_query_system::query::plumbing::force_query_with_job::hd4748b611474a44a
  88:     0x7f623cacd6a5 - rustc_query_system::query::plumbing::force_query_impl::hb1a4cca65f739067
  89:     0x7f623ca9baa3 - rustc_query_system::query::plumbing::force_query::h038802f7f590855b
  90:     0x7f623d9d437d - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h3ebc766d821de9a7
  91:     0x7f623d9d4355 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h3ebc766d821de9a7
  92:     0x7f623d9d4355 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h3ebc766d821de9a7
  93:     0x7f623d9d4174 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read::h79c247d3b75be821
  94:     0x7f623d98bde4 - rustc_query_system::query::plumbing::ensure_must_run::h1e4a8ccfe3e41c35
  95:     0x7f623d9cf90f - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck::h87d12e0b6c66eee0
  96:     0x7f623d3d913e - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners::hdb654225848648e9
  97:     0x7f623ddf7959 - rustc_interface::passes::analysis::h2288163d6ab7db94
  98:     0x7f623cc6a703 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h0053d9a08557dd9e
  99:     0x7f623cc4bbc7 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hb2aa29406a4a6b44
 100:     0x7f623cc55989 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task::hce17958cea334996
 101:     0x7f623cd181ce - rustc_data_structures::stack::ensure_sufficient_stack::h1a7cd8247c314c3a
 102:     0x7f623cae0add - rustc_query_system::query::plumbing::force_query_with_job::hc7565743559c0e94
 103:     0x7f623e2a0596 - rustc_query_system::query::plumbing::get_query_impl::he7aff690a0249722
 104:     0x7f623e3479cd - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h0cff0ba8b7dd6cb1
 105:     0x7f623ddcb9b8 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h10f951c96831b3bc
 106:     0x7f623ddba77c - rustc_span::with_source_map::h46995da78fbfb2ca
 107:     0x7f623ddccbda - rustc_interface::interface::create_compiler_and_run::hdd0d8e5ea2028f60
 108:     0x7f623ddbfc59 - scoped_tls::ScopedKey<T>::set::h4889fb0c1fafdd05
 109:     0x7f623ddbbcda - std::sys_common::backtrace::__rust_begin_short_backtrace::h78e9a1a2353d1913
 110:     0x7f623ddbb125 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb838edfbc6ca2ea1
 111:     0x7f623bacb5d7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h65c29e4642be2358
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/alloc/src/boxed.rs:1572:9
 112:     0x7f623bacb5d7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd0f8f7fbbd9fffbf
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/alloc/src/boxed.rs:1572:9
 113:     0x7f623bacb5d7 - std::sys::unix::thread::Thread::new::thread_start::h2fd22fee3ca77b65
                               at /rustc/739f8f0a8d728054a60a37fb29517e9e7cc2365a/library/std/src/sys/unix/thread.rs:74:17
 114:     0x7f623ba09edd - start_thread
 115:     0x7f623b929a4f - __GI___clone
 116:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-beta.1 (739f8f0a8 2021-07-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z binary-dep-depinfo -C embed-bitcode=no -C debuginfo=1 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
```
</details>

### Meta

`rustc --version`:
```
$ build/x86_64-unknown-linux-gnu/stage0/bin/rustc --version
rustc 1.55.0-beta.1 (739f8f0a8 2021-07-28)
```

cc @Aaron1011, https://github.com/rust-lang/rust/issues/84970

**Comment by Aaron1011** [comment]
This is fixed by https://github.com/rust-lang/rust/pull/87990
