### ISSUE TITLE
[ui] ui/asm/sym.rs test fails with 'assertion failed: `(left == right)

### ISSUE THREAD

**Issue by Apteryks** [rust-lang/rust#88569]
Hello,

I've stumbled upon this single test failure while packaging 1.54.0 for GNU Guix.

I tried this command:

```sh
"./x.py" "-j24" "test" "-vv"
```

I expected to see this happen: all test passes

Instead, this happened: one test failed (see below)

### Meta

version: 1.54.0 (release)

```
................................................................................
failures:

---- [ui] ui/asm/sym.rs stdout ----


executing "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/test/ui/asm/sym.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "-C" "prefer-dynamic" "-o" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/auxiliary"
------stdout------------------------------

------stderr------------------------------

------------------------------------------
executing "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a"
------stdout------------------------------

------stderr------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0x7ffff7c097c0`,
 right: `0x55555555710c`', /tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/test/ui/asm/sym.rs:75:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------------------------------------

error: test run failed!
status: exit status: 101
command: "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/test/ui/asm/sym/a"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0x7ffff7c097c0`,
 right: `0x55555555710c`', /tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/test/ui/asm/sym.rs:75:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------------------------------------



failures:
    [ui] ui/asm/sym.rs

test result: FAILED. 11883 passed; 1 failed; 96 ignored; 0 measured; 0 filtered out; finished in 99.38s

Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu


command did not execute successfully: "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/stage1/lib" "--run-lib-path" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--src-base" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/test/ui" "--build-base" "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage1-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/gnu/store/y13m9cii23kl8fmmdpi3vjsz3hbdhw6w-llvm-12.0.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/gnu/store/2r5lyg65qgx9xj24cq99zybv7ficl0py-python-wrapper-3.9.6/bin/python" "--lldb-python" "/gnu/store/2r5lyg65qgx9xj24cq99zybv7ficl0py-python-wrapper-3.9.6/bin/python" "--gdb" "/gnu/store/g7fhfdda5gal7x6sb7zkp9hg8gkvwn15-gdb-10.2/bin/gdb" "--verbose" "--quiet" "--llvm-version" "12.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzmutate globalisel hellonew hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit orcshared orctargetprocess passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "stable"
expected success, got: exit status: 1


Traceback (most recent call last):
  File "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/./x.py", line 27, in <module>
    bootstrap.main()
  File "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/bootstrap/bootstrap.py", line 1195, in main
    bootstrap(help_triggered)
  File "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/bootstrap/bootstrap.py", line 1181, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/guix-build-rust-1.54.0.drv-0/rustc-1.54.0-src/build/bootstrap/debug/bootstrap -j24 test -vv
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "./x.py" arguments: ("-j24" "test" "-vv") exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 119.4 seconds
command "./x.py" "-j24" "test" "-vv" failed with status 1
```

**Comment by the8472** [comment]
Is this with rust's llvm fork or some external llvm build?

**Comment by Apteryks** [comment]
This is with LLVM 12 as packaged in GNU Guix (external).

**Comment by Apteryks** [comment]
Ugh.  This seems non-determistic.  I haven't been able to reproduce in 2 new builds of 1.54, with the same LLVM 9.  Although the rustc used to bootstrap 1.54 is now 1.53 stage 1 instead of 1.53 stage 2 (I don't think this should make a difference).

**Comment by jyn514** [comment]
@Apteryks are you still running into this issue?

**Comment by Apteryks** [comment]
I think it's been resolved, somehow.  I'll reopen if it reappears.
