### ISSUE TITLE
[Known] ICE while executing cargo sqlx prepare

### ISSUE THREAD

**Issue by rakshith-ravi** [rust-lang/rust#88932]
### Code
I don't think this has to do with the code. I got this error while running `cargo sqlx prepare` (using `sqlx-cli`), which I think is calling `cargo build` internally. Cargo seems to be able to detect that this ICE is a known issue, but I just thought I'd open one to give more data points of ICEs. Hope this helps

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: x86_64-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```

### Error output
```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(c7c8447873c53f9b-222cfb5e8352f5ca)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p api` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(c7c8447873c53f9b-222cfb5e8352f5ca): Ok(EvaluatedToOkModuloRegions)', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/compiler/rustc_query_system/src/query/plumbing.rs:624:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `futures::future::IntoFuture<futures::future::MapErr<hyper::service::oneshot::Oneshot<hyper::client::connect::http::HttpConnector, shiplift::Uri>, fn(hyper::client::connect::http::ConnectError) -> hyper::error::Error {hyper::error::Error::new_connect::<hyper::client::connect::http::ConnectError>}>>: std::marker::Send`
#1 [codegen_fulfill_obligation] checking if `std::ops::CoerceUnsized` fulfills its obligations
end of query stack
error: could not compile `api` due to previous error
error: `cargo check` failed with status: exit code: 101
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(c7c8447873c53f9b-222cfb5e8352f5ca)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p api` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(c7c8447873c53f9b-222cfb5e8352f5ca): Ok(EvaluatedToOkModuloRegions)', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/compiler/rustc_query_system/src/query/plumbing.rs:624:9
stack backtrace:
   0:     0x7f26ace86b40 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f26ace86b40 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f26ace86b40 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f26ace86b40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f26acef46bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x7f26ace782d5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x7f26ace8a89b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f26ace8a89b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f26ace8a89b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x7f26ace8a371 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x7f26ad663251 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h6de3be617154114e
  11:     0x7f267efe4b83 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hdb1429dc7ed341cc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1586:9
  12:     0x7f267ef9ceea - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h58ac5cbc9cb03973
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7f26ace8b0c9 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
  14:     0x7f26ace8ab87 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  15:     0x7f26ace8703c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7f26ace8aae9 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  17:     0x7f26ace53aab - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  18:     0x7f26af66d49c - rustc_query_system::query::plumbing::incremental_verify_ich::h68784a796e4efb05
  19:     0x7f26af67f6f6 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::ha6ef4487bc8546db
  20:     0x7f26af779fd3 - rustc_data_structures::stack::ensure_sufficient_stack::h3f75b5a3804fd0df
  21:     0x7f26aecf5de6 - rustc_query_system::query::plumbing::get_query_impl::h49273a0276a4c18a
  22:     0x7f26aed658c3 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation::h4d7577941a183323
  23:     0x7f26aef8b44c - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation::h5c81ccbdb0fcc7f9
  24:     0x7f26aef8b760 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow::h7d5f61348012a371
  25:     0x7f26aefba87e - rustc_trait_selection::traits::fulfill::FulfillProcessor::process_trait_obligation::hcca34323d18d7f2e
  26:     0x7f26aefb94c8 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::h900518c8d79c7b31
  27:     0x7f26aefaf7f4 - rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations::h626eb0f98d463b58
  28:     0x7f26aefb9043 - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible::h7e94837b987fec5b
  29:     0x7f26aefb8e40 - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_all_or_error::h45cb7ce64391be89
  30:     0x7f26aefd7370 - rustc_trait_selection::traits::codegen::drain_fulfillment_cx_or_panic::h2f3fc7120e4aa875
  31:     0x7f26aef8072c - rustc_infer::infer::InferCtxtBuilder::enter::h8a84d22f6f791850
  32:     0x7f26aefd72e7 - rustc_trait_selection::traits::codegen::codegen_fulfill_obligation::h1fc49b8c436ad07a
  33:     0x7f26af70dfc0 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::hdeb250bfab156620
  34:     0x7f26af782e65 - rustc_data_structures::stack::ensure_sufficient_stack::hdabdf87093ecb88c
  35:     0x7f26aed1ee08 - rustc_query_system::query::plumbing::get_query_impl::hfd58d02768e5eb0d
  36:     0x7f26aed64422 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::codegen_fulfill_obligation::h2bb376452cb7d682
  37:     0x7f26adcaf2d0 - rustc_mir::monomorphize::custom_coerce_unsize_info::h33da7617c0824e17
  38:     0x7f26af5dff4f - rustc_mir::monomorphize::collector::find_vtable_types_for_unsizing::h46eb65355bf64c46
  39:     0x7f26aecd099e - <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_rvalue::h7ffa3730bd60a5cb
  40:     0x7f26aecd5788 - rustc_mir::monomorphize::collector::collect_neighbours::h8f36e75b605a1a85
  41:     0x7f26aeccf00b - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  42:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  43:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  44:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  45:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  46:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  47:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  48:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  49:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  50:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  51:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  52:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  53:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  54:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  55:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  56:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  57:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  58:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  59:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  60:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  61:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  62:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  63:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  64:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  65:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  66:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  67:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  68:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  69:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  70:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  71:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  72:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  73:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  74:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  75:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  76:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  77:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  78:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  79:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  80:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  81:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  82:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  83:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  84:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  85:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  86:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  87:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  88:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  89:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  90:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  91:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  92:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  93:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  94:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  95:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  96:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  97:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  98:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
  99:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 100:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 101:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 102:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 103:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 104:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 105:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 106:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 107:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 108:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 109:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 110:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 111:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 112:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 113:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 114:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 115:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 116:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 117:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 118:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 119:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 120:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 121:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 122:     0x7f26aeccf158 - rustc_mir::monomorphize::collector::collect_items_rec::h7dc24fbffc4c6b65
 123:     0x7f26af5df10b - rustc_mir::monomorphize::collector::collect_crate_mono_items::h49c06ab7185f331a
 124:     0x7f26aebb0f37 - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h35ecb7c05f4b8d36
 125:     0x7f26ae01769a - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hfd7188bb8caffed3
 126:     0x7f26adfdb7bd - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h77c03e99cc77bde2
 127:     0x7f26ae0b9b74 - rustc_data_structures::stack::ensure_sufficient_stack::hdb3c4a7f5ef3b706
 128:     0x7f26ade70269 - rustc_query_system::query::plumbing::force_query_with_job::h6c4138f9a2ab7dbd
 129:     0x7f26af5f1e92 - rustc_query_system::query::plumbing::get_query_impl::h0c45064c565f0a53
 130:     0x7f26af6dbf66 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items::hd409ae67463e5d42
 131:     0x7f26af20582c - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h4b4f25cfc1c72e9f
 132:     0x7f26af188b55 - rustc_interface::passes::QueryContext::enter::h99f80bbcae7b7b3d
 133:     0x7f26af180b86 - rustc_interface::queries::Queries::ongoing_codegen::h47529ac988919a0f
 134:     0x7f26af15ead5 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h2007d30ef68567cb
 135:     0x7f26af14e44c - rustc_span::with_source_map::hc5adfd8eb2dd5236
 136:     0x7f26af15fc8a - rustc_interface::interface::create_compiler_and_run::h976ed8e22b4f89b8
 137:     0x7f26af152e89 - scoped_tls::ScopedKey<T>::set::h4a2887b4d5b96c48
 138:     0x7f26af14f9aa - std::sys_common::backtrace::__rust_begin_short_backtrace::h220030c0c75c9d89
 139:     0x7f26af14edf5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd62830e2741d6b63
 140:     0x7f26ace97657 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
 141:     0x7f26ace97657 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
 142:     0x7f26ace97657 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
 143:     0x7f26acdb5450 - start_thread
 144:     0x7f26accc3d53 - clone
 145:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `futures::future::IntoFuture<futures::future::MapErr<hyper::service::oneshot::Oneshot<hyper::client::connect::http::HttpConnector, shiplift::Uri>, fn(hyper::client::connect::http::ConnectError) -> hyper::error::Error {hyper::error::Error::new_connect::<hyper::client::connect::http::ConnectError>}>>: std::marker::Send`
#1 [codegen_fulfill_obligation] checking if `std::ops::CoerceUnsized` fulfills its obligations
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `api` due to previous error
error: `cargo check` failed with status: exit code: 101
```

</p>
</details>

**Comment by reddevilmidzy** [comment]
Hello. @rakshith-ravi 
Could you please check if ICE is still occurring?

**Comment by rakshith-ravi** [comment]
@reddevilmidzy I can't recollect the last time I faced this ICE again. Given it's been 5 years since, should we presume the issue is fixed and close it?
