### ISSUE TITLE
Rustup install failure w/ i686 & 1.55.0

### ISSUE THREAD

**Issue by satmandu** [rust-lang/rust#88935]
### Code

I tried this code:

```RUSTFLAGS='-Clto=thin' bash ./rustup.sh -y --no-modify-path --default-host i686-unknown-linux-gnu --default-toolchain stable --profile minimal```

I expected to see this happen: Install succeeds

Instead, this happened: install failed.

### Version it worked on
1.54.0

It most recently worked on: 

### Version with regression
1.55.0

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
info: downloading installer
info: profile set to 'minimal'
info: setting default host triple to i686-unknown-linux-gnu
info: syncing channel updates for 'stable-i686-unknown-linux-gnu'
thread 'main' panicked at 'range start index 355 out of range for slice of length 32', /cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/util_libc.rs:65:24
stack backtrace:
   0: 0x77365023 - std::backtrace_rs::backtrace::libunwind::trace::h7fd0e141e2d906ca
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1: 0x77365023 - std::backtrace_rs::backtrace::trace_unsynchronized::h1eca8ded787c5b24
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0x77365023 - std::sys_common::backtrace::_print_fmt::h4cb0f8f7cda4d345
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3: 0x77365023 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2579a3d2b4303078
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4: 0x76f78164 - core::fmt::write::h02e8615e652766ba
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5: 0x773648de - std::io::Write::write_fmt::h92c644d2cf74e57f
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6: 0x77364300 - std::sys_common::backtrace::_print::h9b13230a85311925
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7: 0x77364300 - std::sys_common::backtrace::print::h5482833abe329a2b
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8: 0x77364300 - std::panicking::default_hook::{{closure}}::h68d5f6db0f5d7902
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9: 0x773638c6 - std::panicking::default_hook::h82ae8b9a767d7b31
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10: 0x76f15f08 - rustup::currentprocess::with::{{closure}}::{{closure}}::h30fa267c30e0f5f6
  11: 0x773634ca - std::panicking::rust_panic_with_hook::hc3227ec8c33f6507
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
  12: 0x77382bb2 - std::panicking::begin_panic_handler::{{closure}}::h0408582b591d5da8
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  13: 0x77382b1a - std::sys_common::backtrace::__rust_end_short_backtrace::h8bfb2d3fce40ba2b
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  14: 0x77382aa1 - rust_begin_unwind
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  15: 0x76effcf5 - core::panicking::panic_fmt::h50032c7c716249f8
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  16: 0x76f0016f - core::slice::index::slice_start_index_len_fail::hf81767729ae36c6a
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/index.rs:34:5
  17: 0x7707c7b8 - <rand_core::os::OsRng as rand_core::RngCore>::try_fill_bytes::hbe5b92d8708ff51f
  18: 0x7707c2b0 - std::thread::local::fast::Key<T>::try_initialize::h3f6f74dea40548cb
  19: 0x77290a67 - rustup::utils::raw::random_string::h201d9ea95dbc64f4
  20: 0x772902df - rustup::dist::temp::Cfg::new_file_with_ext::hc273008c953d79ae
  21: 0x7727f8c2 - rustup::dist::download::DownloadCfg::download_and_check::h9bc00d4eee4a5de3
  22: 0x7726c7e5 - rustup::dist::dist::dl_v2_manifest::h5b99ca00c2bca783
  23: 0x772649c4 - rustup::dist::dist::try_update_from_dist_::hf3ecf4073184eaa0
  24: 0x77262587 - rustup::install::InstallMethod::install::hc1e63ca148769e65
  25: 0x77260a7f - rustup::toolchain::DistributableToolchain::install_from_dist::ha25600041b01b912
  26: 0x7734f556 - rustup::cli::self_update::install::h47194fb43e6c8495
  27: 0x76f1bf9e - rustup_init::main::h2d77027039d73808
  28: 0x76f15102 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7b25bcc8e42ab05d
  29: 0x76f1d073 - main
  30: 0x76c70699 - __libc_start_main
```

</p>
</details>

Reported at https://github.com/skycocker/chromebrew/issues/6190

**Comment by apiraino** [comment]
@satmandu is this issue reproducible on a clean installation? Does it also reproduce outside a ChromeOS environment?

I'm trying to understand the conditions to make this reproducible.

**Comment by apiraino** [comment]
Pending any new comment, I'm inclined to close this: not sure about the current status.

**Comment by satmandu** [comment]
This is resolved on newer versions of rust, at least with 1.59. Sorry for not getting back to you on this.
