### ISSUE TITLE
could not compile storing_lists_vectors

### ISSUE THREAD

**Issue by sapoykov** [rust-lang/rust#89018]
Hello everyone. I practice using vectors. I wanted to iterate over mutable references to each element of the mutable vector in order to make changes to all elements. But somehow I got an error. I'm a beginner and would appreciate everyone's help!
My code:
```
fn main() {
    let mut s = vec![10, 20, 30];
    for i in &mut s {
        *i += 10;
        println!("{}", i);
    }
}
```

Error: could not compile storing_lists_vectors

Additional info:
```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

**Comment by Aaron1011** [comment]
@sapoykov Could you post the full error message that you're getting?

**Comment by sapoykov** [comment]
@Aaron1011 Thanks a lot! I didn't quite understand how I should use `RUST_BACKTRACE=1` and I run: `cargo run RUST_BACKTRACE=1` after that i got the following error:
```
thread 'rustc' panicked at 'Failed to recover key for crate_hash(7b325c0bcf1c8f7e-78e92a3d885642c8) with hash 7b325c0bcf1c8f7e-78e92a3d885642c8', compiler/rustc_query_impl/src/lib.rs:54:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `storing_lists_vectors`
```
This error only happens when using vectors. Arrays, loops, tuples, strings, etc. This all works fine. I just don't understand what to do...

**Comment by Aaron1011** [comment]
@sapoykov: Try running `RUST_BACKTRACE=1 cargo run`. Could you also zip and upload your `target` directory?

**Comment by sapoykov** [comment]
@Aaron1011 Result:
```
thread 'rustc' panicked at 'Failed to recover key for crate_hash(7b325c0bcf1c8f7e-78e92a3d885642c8) with hash 7b325c0bcf1c8f7e-78e92a3d885642c8', compiler/rustc_query_impl/src/lib.rs:54:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
   2: rustc_query_impl::query_callbacks::is_no_builtins::try_load_from_on_disk_cache
   3: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   4: rustc_middle::ty::context::tls::with_context::{{closure}}
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::serialize
   7: rustc_middle::ty::context::TyCtxt::serialize_query_result_cache
   8: rustc_session::utils::<impl rustc_session::session::Session>::time
   9: rustc_incremental::persist::save::save_in
  10: rustc_session::utils::<impl rustc_session::session::Session>::time
  11: rustc_data_structures::sync::join
  12: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  13: rustc_incremental::persist::save::save_dep_graph
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: rustc_interface::interface::create_compiler_and_run
  17: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `storing_lists_vectors`
```
[archive.zip](https://github.com/rust-lang/rust/files/7180042/archive.zip)

**Comment by Aaron1011** [comment]
@sapoykov That zip file you uploaded has an empty `target` directory. Are you sure it's the `target` directory in the directory where you're running `cargo run`?

**Comment by sapoykov** [comment]
@Aaron1011 Sure. I run ```cargo run``` and and made an archive. Here's one more ti
[new_archive.zip](https://github.com/rust-lang/rust/files/7180145/new_archive.zip)
me

**Comment by Aaron1011** [comment]
@sapoykov: That zip file has the same issue :)

I'm pretty sure that this issue is due to local corruption of your incremental data. I would run `cargo clean`, which should fix your issue. If it occurs again, please leave a new comment on this issue.

**Comment by sapoykov** [comment]
@Aaron1011 You mentioned data corruption. I'm using a laptop and didn’t keep track of the battery charge and it shut down during compilation. Now I remembered that everything worked up to this point. And after I connected the charger, this problem appeared.

**Comment by sapoykov** [comment]
@Aaron1011 OMG THANK YOU!!! I run ```cargo clean```. Everything works now. Thank you very much and I wish you all the best!
