### ISSUE TITLE
'rustc' panicked at 'attempted to read from stolen value

### ISSUE THREAD

**Issue by leoniloris** [rust-lang/rust#89178]
Hello, I'm facing the following bug, and the compiler recommended me to submit a bug report.

I'm sorry but I can't post the full code. I'm trying to come up with a minimal example, but well, it works fine with windows toolchains 

### Meta
`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: aarch64-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```

### Error output

```
➜  rtsp-feed git:(main) RUST_BACKTRACE=1 cargo test
   Compiling rtsp-feed v0.2.4-dev (/root/rtsp-feed)
thread 'rustc' panicked at 'attempted to read from stolen value', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/compiler/rustc_data_structures/src/steal.rs:37:21
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_mir::transform::check_unsafety::unsafety_check_result
   2: core::ops::function::FnOnce::call_once
   3: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   4: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::get_query_impl
   7: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result
   8: rustc_mir::transform::check_unsafety::check_unsafety
   9: rustc_session::utils::<impl rustc_session::session::Session>::time
  10: rustc_interface::passes::analysis
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::force_query_with_job
  14: rustc_query_system::query::plumbing::get_query_impl
  15: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  16: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  17: rustc_span::with_source_map
  18: rustc_interface::interface::create_compiler_and_run
  19: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on aarch64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `media::wrappers::pipeline::<impl at src/media/wrappers/pipeline.rs:16:1: 91:2>::new`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `rtsp-feed````

**Comment by istankovic** [comment]
@leoniloris is this issue still relevant? Could you please test with a recent rustc version?

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by Noratrieb** [comment]
An old issue without a reproduction, closing.
