### ISSUE TITLE
Rust internal Compiler Error when building SMT2 crate using nightly

### ISSUE THREAD

**Issue by Lukas-Dresel** [rust-lang/rust#89448]
### Code
Simply `cargo build` using the SMT2 crate as a dependency using rust nightly (1.57.0)

### Meta

```
note: rustc 1.57.0-nightly (aa7aca3b9 2021-09-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

### Error output
```
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1191:22: Unexpected type for `Single` constructor: <client::Client<L, C, S, F> as Environment>::Constant

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
<SNIP: backtrace see below>
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (aa7aca3b9 2021-09-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `client::interface::<impl at /home/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/smt2-0.2.0/src/client/interface.rs:19:1: 362:2>::downgrade_term`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `smt2`
```

Backtrace (RUST_BACKTRACE=full)
```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
stack backtrace:
   0:     0x7f21ce5a5b6c - std::backtrace_rs::backtrace::libunwind::trace::h2ab374bc2a3b7023
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f21ce5a5b6c - std::backtrace_rs::backtrace::trace_unsynchronized::h128cb5178b04dc46
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f21ce5a5b6c - std::sys_common::backtrace::_print_fmt::h5344f9eefca2041f
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f21ce5a5b6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h213003bc5c7acf04
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f21ce60345c - core::fmt::write::h78bf85fc3e93663f
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/core/src/fmt/mod.rs:1161:17
   5:     0x7f21ce596795 - std::io::Write::write_fmt::he619515c888f21a5
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/io/mod.rs:1668:15
   6:     0x7f21ce5a8de0 - std::sys_common::backtrace::_print::hf706674f77848203
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f21ce5a8de0 - std::sys_common::backtrace::print::hf0b6c7a88804ec56
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f21ce5a8de0 - std::panicking::default_hook::{{closure}}::h2dde766cd83a333a
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/panicking.rs:210:50
   9:     0x7f21ce5a898b - std::panicking::default_hook::h501e3b2e134eb149
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/panicking.rs:227:9
  10:     0x7f21ced83981 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h8ff5de92123cb8fd
  11:     0x7f21ce5a95f9 - std::panicking::rust_panic_with_hook::hc09e869c4cf00885
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/panicking.rs:628:17
  12:     0x7f21cfe73b3b - std::panicking::begin_panic::{{closure}}::h5c7a29a9f3c50d8d
  13:     0x7f21cfe73a76 - std::sys_common::backtrace::__rust_end_short_backtrace::h11b7892876009c1e
  14:     0x7f21cfe73b0f - std::panicking::begin_panic::hd63e7fe0ba9182da
  15:     0x7f21cfe8440d - std::panic::panic_any::h3c06e175d31a9167
  16:     0x7f21cfe864aa - rustc_errors::HandlerInner::bug::he6d06053695a98ed
  17:     0x7f21cfe85f50 - rustc_errors::Handler::bug::h61abf9991ffffcbc
  18:     0x7f21cfcffd56 - rustc_middle::ty::context::tls::with_opt::hd0b25ef1fa372784
  19:     0x7f21cfd00170 - rustc_middle::util::bug::opt_span_bug_fmt::he982db01d383152c
  20:     0x7f21cfd000e6 - rustc_middle::util::bug::bug_fmt::h3252ae0338f3fde6
  21:     0x7f21d03ccd27 - rustc_mir_build::thir::pattern::deconstruct_pat::DeconstructedPat::specialize::h6b19f78526d653cb
  22:     0x7f21d03e08eb - rustc_mir_build::thir::pattern::usefulness::is_useful::h23761feb3eda9ab6
  23:     0x7f21d03e09fa - rustc_mir_build::thir::pattern::usefulness::is_useful::h23761feb3eda9ab6
  24:     0x7f21d03e09fa - rustc_mir_build::thir::pattern::usefulness::is_useful::h23761feb3eda9ab6
  25:     0x7f21d03df626 - rustc_mir_build::thir::pattern::usefulness::compute_match_usefulness::h3fb34636c567887e
  26:     0x7f21d03b14ad - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h62aa40d9efd99101
  27:     0x7f21d03b1106 - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h62aa40d9efd99101
  28:     0x7f21d03b0c13 - rustc_mir_build::thir::pattern::check_match::check_match::hb6b0f9acf13dc3d3
  29:     0x7f21d06342bc - rustc_query_system::query::plumbing::try_execute_query::h7d4ffa313f78919b
  30:     0x7f21d06d4d63 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_match::h3b059d52e1073a1a
  31:     0x7f21cff9aa19 - rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners::hc72903ced0a349da
  32:     0x7f21d0c73348 - rustc_session::utils::<impl rustc_session::session::Session>::time::hb5e71f8a5f1eca54
  33:     0x7f21d0c71054 - rustc_session::utils::<impl rustc_session::session::Session>::time::h36f90b92842394ee
  34:     0x7f21d0c4990e - rustc_interface::passes::analysis::hb918b02982537851
  35:     0x7f21d10c83a1 - rustc_query_system::query::plumbing::try_execute_query::h784269645558384c
  36:     0x7f21d11bfd62 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::ha8ab0b7748e9a5d1
  37:     0x7f21d0c2f50b - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h97e60bfafbd48b55
  38:     0x7f21d0c1f722 - rustc_span::with_source_map::hce3a664e96079636
  39:     0x7f21d0c2ed50 - scoped_tls::ScopedKey<T>::set::h033dd5b45ac9d9cd
  40:     0x7f21d0c20515 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4110caeb43804b52
  41:     0x7f21d0c424f2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h18816eff1497881c
  42:     0x7f21ce5b4733 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59eef3b9c8a82350
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/alloc/src/boxed.rs:1638:9
  43:     0x7f21ce5b4733 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb5bbe017c347469c
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/alloc/src/boxed.rs:1638:9
  44:     0x7f21ce5b4733 - std::sys::unix::thread::Thread::new::thread_start::h62931528f61e35f5
                               at /rustc/aa7aca3b954131720df725e70d12e902eb3be1de/library/std/src/sys/unix/thread.rs:106:17
  45:     0x7f21ce4cb609 - start_thread
                               at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  46:     0x7f21ce3df293 - clone
  47:                0x0 - <unknown>
```

**Comment by Lukas-Dresel** [comment]
This looks similar to #89393, I can close this if this is a confirmed duplicate.

**Comment by Nadrieril** [comment]
Yep, definitely a duplicate
