### ISSUE TITLE
internal compiler error: encountered incremental compilation error with predicates_of(alloc[df14]::string::ToString)

### ISSUE THREAD

**Issue by cswinter** [rust-lang/rust#89496]
I possibly ran into an instance of https://github.com/rust-lang/rust/issues/84970. Not sure if this is a duplicate or not but figured I'd share in case it's useful. I think this may have been caused by me accidentally editing a file from a github dependency in `.cargo/registry/src`. After upgrading to latest Rust, I got a compile error instead and compilation succeeded after `rm -r`ing the cargo cache directory for the mangled dependency.

### Code

I don't have any minimal reproduction, unfortunately.

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1
```

### Error output

```
error: internal compiler error: encountered incremental compilation error with predicates_of(alloc[df14]::string::ToString)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p xprun` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for predicates_of(alloc[df14]::string::ToString): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::string::ToString>), []), /home/clemens/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2346:1: 2362:2 (#0))] }', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/compiler/rustc_query_system/src/query/plumbing.rs:620:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0 (a178d0322 2021-07-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type cdylib --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::string::ToString`
#1 [typeck] type-checking `client::build::build_image`
end of query stack
error: aborting due to previous error

error: could not compile `xprun`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: encountered incremental compilation error with predicates_of(alloc[df14]::string::ToString)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p xprun` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for predicates_of(alloc[df14]::string::ToString): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::string::ToString>), []), /home/clemens/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2346:1: 2362:2 (#0))] }', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/compiler/rustc_query_system/src/query/plumbing.rs:620:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   6: rustc_middle::ty::generics::GenericPredicates::instantiate_into
   7: rustc_middle::ty::generics::GenericPredicates::instantiate
   8: rustc_typeck::check::method::confirm::ConfirmContext::confirm
   9: rustc_typeck::check::method::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::lookup_method
  10: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  11: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  12: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  13: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  14: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  15: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  16: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  17: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  18: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  19: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  20: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  21: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  22: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  23: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  24: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  25: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  26: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  27: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  29: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  30: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  31: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  32: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  33: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  34: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  35: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  36: rustc_typeck::check::check::check_fn
  37: rustc_typeck::check::closure::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_closure
  38: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  39: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  40: rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
  41: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  42: rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  43: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  44: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  45: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  46: rustc_typeck::check::check::check_fn
  47: rustc_typeck::check::inherited::InheritedBuilder::enter
  48: rustc_typeck::check::typeck
  49: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  50: rustc_data_structures::stack::ensure_sufficient_stack
  51: rustc_query_system::query::plumbing::force_query_with_job
  52: rustc_query_system::query::plumbing::get_query_impl
  53: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  54: rustc_middle::ty::context::TyCtxt::typeck_opt_const_arg
  55: rustc_mir_build::build::mir_built
  56: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  57: rustc_data_structures::stack::ensure_sufficient_stack
  58: rustc_query_system::query::plumbing::get_query_impl
  59: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
  60: rustc_mir::transform::check_unsafety::unsafety_check_result
  61: core::ops::function::FnOnce::call_once
  62: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  63: rustc_data_structures::stack::ensure_sufficient_stack
  64: rustc_query_system::query::plumbing::force_query_with_job
  65: rustc_query_system::query::plumbing::force_query_impl
  66: rustc_query_system::query::plumbing::force_query
  67: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  68: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  69: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  70: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  71: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read
  72: rustc_query_system::query::plumbing::get_query_impl
  73: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
  74: rustc_trait_selection::traits::select::confirmation::<impl rustc_trait_selection::traits::select::SelectionContext>::confirm_candidate
  75: rustc_infer::infer::InferCtxt::probe
  76: rustc_trait_selection::traits::select::SelectionContext::evaluate_candidate
  77: rustc_trait_selection::traits::select::SelectionContext::evaluate_stack
  78: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  79: rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task
  80: rustc_trait_selection::traits::select::SelectionContext::evaluate_trait_predicate_recursively
  81: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively::{{closure}}
  82: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicate_recursively
  83: rustc_trait_selection::traits::select::SelectionContext::evaluate_predicates_recursively
  84: rustc_infer::infer::InferCtxt::probe
  85: rustc_trait_selection::traits::select::SelectionContext::evaluate_candidate
  86: rustc_trait_selection::traits::select::SelectionContext::evaluate_stack
  87: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  88: rustc_query_system::dep_graph::graph::DepGraph<K>::with_anon_task
  89: rustc_trait_selection::traits::select::SelectionContext::evaluate_trait_predicate_recursively
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0 (a178d0322 2021-07-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type cdylib --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::string::ToString`
#1 [typeck] type-checking `client::build::build_image`
#2 [mir_built] building MIR for `client::build::build_image`
#3 [unsafety_check_result] unsafety-checking `client::build::build_image`
#4 [type_of] computing type of `client::build::build_image::{opaque#0}`
#5 [evaluate_obligation] evaluating trait selection obligation `impl futures::Future: std::marker::Send`
#6 [typeck] type-checking `client::build::build`
#7 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `xprun`

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by Aaron1011** [comment]
This is fixed in the latest nightly (and possibly the latest stable as well).
