### ISSUE TITLE
crash when proc_macro produces invalid byte string literal

### ISSUE THREAD

**Issue by cmyr** [rust-lang/rust#89565]
I was messing around and hit this:

### Code

```Rust
// lib.rs
#[proc_macro]
pub fn oopsy(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    "b\"😊\"".parse().unwrap()
}

// tests/test.rs
#[test]
fn crash() {
    crate::oopsy!("anything");
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: aarch64-apple-darwin
release: 1.55.0
LLVM version: 12.0.1
```

also checked:
```
rustc 1.57.0-nightly (003d8d3f5 2021-10-04)
rustc 1.56.0-beta.3 (deef86610 2021-09-17)
```
### Error output

```
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1611:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', compiler/rustc_span/src/lib.rs:1611:17
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rustc_span::SourceFile::lookup_file_pos
   4: rustc_span::SourceFile::lookup_file_pos_with_col_display
   5: rustc_span::source_map::SourceMap::lookup_char_pos
   6: rustc_errors::emitter::FileWithAnnotatedLines::collect_annotations
   7: rustc_errors::emitter::EmitterWriter::emit_message_default
   8: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   9: rustc_errors::json::Diagnostic::from_errors_diagnostic
  10: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
  11: rustc_errors::HandlerInner::emit_diagnostic
  12: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  13: rustc_parse::lexer::unescape_error_reporting::emit_unescape_error
  14: rustc_lexer::unescape::unescape_literal
  15: rustc_parse::lexer::StringReader::next_token
  16: rustc_parse::lexer::tokentrees::TokenTreesReader::parse_all_token_trees
  17: rustc_parse::lexer::parse_token_trees
  18: rustc_parse::maybe_file_to_stream
  19: rustc_parse::source_file_to_stream
  20: rustc_parse::parse_stream_from_source_str
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  22: <proc_macro::bridge::server::Dispatcher<proc_macro::bridge::server::MarkedTypes<S>> as proc_macro::bridge::server::DispatcherTrait>::dispatch
  23: <proc_macro::bridge::closure::Closure<A,R> as core::convert::From<&mut F>>::from::call
  24: proc_macro::bridge::closure::Closure<A,R>::call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/closure.rs:27:18
  25: proc_macro::bridge::client::TokenStream::from_str::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:244:25
  26: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:336:47
  27: proc_macro::bridge::client::BridgeState::with::{{closure}}::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:293:17
  28: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  29: proc_macro::bridge::client::BridgeState::with::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:291:13
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
  31: std::thread::local::LocalKey<T>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
  32: proc_macro::bridge::client::BridgeState::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:290:9
  33: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:329:9
  34: proc_macro::bridge::client::TokenStream::from_str
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:237:17
  35: <proc_macro::TokenStream as core::str::traits::FromStr>::from_str
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/lib.rs:138:24
  36: core::str::<impl str>::parse
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/str/mod.rs:2221:9
  37: rustc_ice_1::oopsy
             at ./src/lib.rs:13:5
  38: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  39: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:410:40
  40: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:377:26
  41: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/scoped_cell.rs:80:33
  42: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/scoped_cell.rs:75:9
  43: proc_macro::bridge::scoped_cell::ScopedCell<T>::set
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/scoped_cell.rs:80:9
  44: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:325:35
  45: std::thread::local::LocalKey<T>::try_with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
  46: std::thread::local::LocalKey<T>::with
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
  47: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:325:9
  48: proc_macro::bridge::client::run_client::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:370:9
  49: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:347:9
  50: std::panicking::try::do_call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  51: ___rust_try
  52: std::panicking::try
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  53: std::panic::catch_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  54: proc_macro::bridge::client::run_client
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:369:5
  55: proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/proc_macro/src/bridge/client.rs:410:13
  56: proc_macro::bridge::server::run_server
  57: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::ProcMacro>::expand
  58: rustc_expand::expand::MacroExpander::fully_expand_fragment
  59: rustc_expand::expand::MacroExpander::expand_crate
  60: rustc_session::utils::<impl rustc_session::session::Session>::time
  61: rustc_interface::passes::configure_and_expand
  62: rustc_interface::queries::Queries::expansion
  63: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  64: rustc_span::with_source_map
  65: rustc_interface::interface::create_compiler_and_run
  66: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden
```

</p>
</details>

**Comment by Ezrashaw** [comment]
This has been fixed in the meantime on both nightly and stable. This issue can now be closed.
