### ISSUE TITLE
thread 'rustc' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError'

### ISSUE THREAD

**Issue by iucoen** [rust-lang/rust#89728]
### Code

While bootstraping rustc, stage1 compiler encounters internal error.

### Meta

`rustc --version --verbose`:
```
stage1/bin/rustc --version --verbose
rustc 1.55.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: i686-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```

### Error output

```
thread 'rustc' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /root/rustc-1.55.0-src/library/std/src/thread/local.rs:375:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 running on i686-unknown-linux-gnu

note: compiler flags: -Z macro-backtrace -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/1.55.0/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C linker=gcc -C link-args=-Wl,-rpath,$ORIGIN/../lib -C target-feature=-crt-static -C prefer-dynamic -C embed-bitcode=yes --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [symbol_name] computing the symbol for `core_arch::simd::<impl at library/core/src/../../stdarch/crates/core_arch/src/simd.rs:8:31: 8:36>::fmt`
#1 [exported_symbols] exported_symbols
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: 0xf3a2042a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8e652133cf421f2a
   1: 0xf3ad78e0 - core::fmt::write::hb09c7582f7f09c64
   2: 0xf3a065bc - std::io::Write::write_fmt::hee96fda83617bba6
   3: 0xf3a0735e - std::panicking::default_hook::{{closure}}::hc1cc4d1200864235
   4: 0xf3a06ea5 - std::panicking::default_hook::h26cf68d21a009eb3
   5: 0xf406a0c2 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::hece7cbcefc30ef5a
   6: 0xf3a07c5d - std::panicking::rust_panic_with_hook::hba3093af22d85989
   7: 0xf3a21286 - std::panicking::begin_panic_handler::{{closure}}::hd9dde358b654dd18
   8: 0xf3a2057e - std::sys_common::backtrace::__rust_end_short_backtrace::h12e05715bc42cc6d
   9: 0xf3a0764e - rust_begin_unwind
  10: 0xf39f2250 - core::panicking::panic_fmt::h42f20454d58ca339
  11: 0xf39f29b2 - core::result::unwrap_failed::h8348c2f043f3247f
  12: 0xf64a11bd - <rustc_middle::ty::adt::AdtDef as rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext>>::hash_stable::h73e98249a3f2a653
  13: 0xf66335d2 - <rustc_middle::ty::TyS as rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext>>::hash_stable::h729aa2a1bff9eef9
  14: 0xf66336f2 - <rustc_middle::ty::TyS as rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext>>::hash_stable::h729aa2a1bff9eef9
  15: 0xf5ad1233 - std::thread::local::LocalKey<T>::with::h69cd106db050de59
  16: 0xf5aef808 - rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::Binder<T>>::hash_stable::h1c24ad1182aa471d
  17: 0xf5ae7712 - rustc_middle::util::common::record_time::h3f0767c63ddfc562
  18: 0xf5ac0075 - rustc_symbol_mangling::legacy::mangle::he20172169da2a801
  19: 0xf5acb3f4 - rustc_symbol_mangling::symbol_name_provider::h355f3455b6e34a33
  20: 0xf5480b42 - rustc_query_system::query::plumbing::get_query_impl::h08f2bcb835992a1f
  21: 0xf5743388 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::symbol_name::h4d23c82c2cb05491
  22: 0xf65efe74 - rustc_middle::middle::exported_symbols::ExportedSymbol::symbol_name_for_local_instance::hf896eb07002b1044
  23: 0xf5a42a7c - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h5a7f0567375b0b0f
  24: 0xf5a55794 - rustc_codegen_ssa::back::symbol_export::exported_symbols_provider_local::hbfaad9757434ca01
  25: 0xf58add24 - stacker::grow::{{closure}}::hc72eecfa0a6d0ed1
  26: 0xf698367e - psm::on_stack::with_on_stack::he0b00868c1be3a09
  27: 0xf6983869 - rust_psm_on_stack
  28: 0xf6983278 - stacker::_grow::h984343a67870518c
  29: 0xf5499541 - rustc_query_system::query::plumbing::get_query_impl::h25e0e4444bf0e922
  30: 0xf57489fb - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::exported_symbols::h0e919c58a1e202bc
  31: 0xf5be7614 - rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root::h0b9a9fc8788ec348
  32: 0xf5c00999 - rustc_metadata::rmeta::encoder::encode_metadata_impl::hda2b0dc22cf0d73f
  33: 0xf5c8c5f0 - rustc_data_structures::sync::join::h024fe81282e204a4
  34: 0xf5c2344c - rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc_middle::middle::cstore::CrateStore for rustc_metadata::creader::CStore>::encode_metadata::h82cbd5f82935954a
  35: 0xf64f5bed - rustc_middle::ty::context::TyCtxt::encode_metadata::h1ef55eb39b4b2dea
  36: 0xf41b9907 - rustc_interface::passes::QueryContext::enter::h89634eb13fec4256
  37: 0xf41a95b1 - rustc_interface::queries::Queries::ongoing_codegen::h5b34ff2ec3222f9b
  38: 0xf40b8c32 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hafca90a38ced1061
  39: 0xf406c12c - rustc_span::with_source_map::he92d128fd96438a7
  40: 0xf40b9f95 - rustc_interface::interface::create_compiler_and_run::hd508cd880ce424c7
  41: 0xf408622c - scoped_tls::ScopedKey<T>::set::hf1517d63dc18c9f4
  42: 0xf4074721 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb07d13a2dd6495e0
  43: 0xf406ef32 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9d149e6d9b9eab7d
  44: 0xf3a10cbb - std::sys::unix::thread::Thread::new::thread_start::h04b1255fca1d36e2
  45: 0xeff022ea - start_thread
  46: 0xf38ed7b6 - __clone
  47:        0x0 - <unknown>
```

</p>
</details>

**Comment by bsodmike** [comment]
I had no issues with:

```
rustc 1.57.0-nightly (54bb4fec6 2021-10-08)
binary: rustc
commit-hash: 54bb4fec68cb592e23077896baea072919721573
commit-date: 2021-10-08
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

**Comment by iucoen** [comment]
> I had no issues with:
> 
> ```
> rustc 1.57.0-nightly (54bb4fec6 2021-10-08)
> binary: rustc
> commit-hash: 54bb4fec68cb592e23077896baea072919721573
> commit-date: 2021-10-08
> host: x86_64-unknown-linux-gnu
> release: 1.57.0-nightly
> LLVM version: 13.0.0
> ```

It's possible that there is something wrong with my toolchain environment. I'm running this inside a gentoo/i686 container. I get the same error when trying to emerge the rust-1.53.0 from official Gentoo repo. I then downloaded the vanilla 1.55.0 source tarball and tried to build it myself to make sure it's not a bug introduced by gentoo patches.

**Comment by iucoen** [comment]
This issue seem to happen if I bootstrap with the gold linker. With ld.bfd it's fine. Closing as not a bug.
