### ISSUE TITLE
UWP library/std tests fail

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#89746]
When running library/std tests with the host `x86_64-pc-windows-msvc` and the target `x86_64-uwp-windows-msvc` I get the following errors:

```
---- fs::tests::copy_file_returns_metadata_len stdout ----
thread 'fs::tests::copy_file_returns_metadata_len' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `7`', library\std\src\fs\tests.rs:774:5

---- fs::tests::links_work stdout ----
thread '<unnamed>' panicked at 'fs::hard_link(&input, &out) failed with: hard link are not supported on UWP', library\std\src\fs\tests.rs:876:5

---- fs::tests::symlink_hard_link stdout ----
thread '<unnamed>' panicked at 'fs::hard_link(tmpdir.join("symlink"), tmpdir.join("hard_link")) failed with: hard link are not supported on UWP', library\std\src\fs\tests.rs:1376:5

---- fs::tests::truncate_works stdout ----
thread 'fs::tests::truncate_works' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `3`', library\std\src\fs\tests.rs:959:5

---- fs::tests::open_flavors stdout ----
thread 'fs::tests::open_flavors' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `3`', library\std\src\fs\tests.rs:1089:5


failures:
    fs::tests::copy_file_returns_metadata_len
    fs::tests::links_work
    fs::tests::open_flavors
    fs::tests::symlink_hard_link
    fs::tests::truncate_works
```

Note: UWP is a tier 3 target so this isn't unexpected. Tests aren't (as far as I'm aware) even run in a UWP environment. However, they can still be useful for ensuring library/std is itself behaving as expected.

**Comment by ChrisDenton** [comment]
Given that [UWP is in now maintenance mode](https://www.techradar.com/news/microsoft-is-finally-dropping-uwp-app-support-windows-app-sdk-heres-why) and there's (so far) been little interest in improving Rust's tier 3 support for it, I'll close this as not planned. I'm happy to reopen if someone does want to work more on UWP and would find this issue useful.
