### ISSUE TITLE
regression: inherent impls overlap check

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#89820]
perf.rust-lang.org's stm32f4 is failing:

```
Checking stm32f4 v0.12.1 (/tmp/.tmprwkENR)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_typeck/src/coherence/inherent_impls_overlap.rs:242:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (02f2b31e6 2021-10-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z self-profile=/tmp/.tmprwkENR/self-profile-output -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [crate_inherent_impls_overlap_check] check for overlap between inherent impls defined in this crate
#1 [analysis] running analysis passes on this crate
end of query stack
thread 'main' panicked at 'assertion failed: status.success()', collector/src/rustc-fake.rs:77:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `stm32f4`
```

**Comment by Mark-Simulacrum** [comment]
I suspect this is caused by a3f98a7501384d4cd11ba94a46bdf88b7e2bc816, merged in https://github.com/rust-lang/rust/pull/89791 (rollup) and root PR https://github.com/rust-lang/rust/pull/89643

@cjgillot @rust-lang/wg-traits -- is this expected breakage (i.e., code in stm32f4 is unsound/should never have been accepted)?
