### ISSUE TITLE
ICE: `Free regions in MIR for CTFE` with `feature(adt_const_params)`

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#89851]
### Code

```Rust
#![feature(adt_const_params)]
#![allow(unused_must_use, incomplete_features)]

pub const BAR: () = ice::<"">();
pub const fn ice<const N: &'static str>() {
    &10;
}

fn main() {}

```

### Meta
ICE only occurs with debug assertions so the version is just "latest commit on master"

### Error output

```
thread 'rustc' panicked at 'Free regions in MIR for CTFE', compiler/rustc_mir_transform/src/lib.rs:406:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_for_ctfe] caching mir of `ice` for CTFE
#1 [eval_to_allocation_raw] const-evaluating + checking `BAR`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Free regions in MIR for CTFE', compiler/rustc_mir_transform/src/lib.rs:406:5
stack backtrace:
   0: std::panicking::begin_panic
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panicking.rs:543:12
   1: rustc_mir_transform::inner_mir_for_ctfe
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_mir_transform/src/lib.rs:406:5
   2: rustc_mir_transform::mir_for_ctfe
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_mir_transform/src/lib.rs:339:25
   3: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:136:17
   4: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:50
   5: rustc_middle::ty::context::tls::set_tlv
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1749:9
   6: rustc_middle::ty::context::tls::enter_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:9
   7: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:135:13
   8: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1809:13
   9: rustc_middle::ty::context::tls::with_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:40
  10: rustc_middle::ty::context::tls::with_context_opt
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1782:22
  11: rustc_middle::ty::context::tls::with_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:9
  12: rustc_middle::ty::context::tls::with_related_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1806:9
  13: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:124:9
  14: rustc_query_system::query::plumbing::execute_job
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:22
  15: rustc_query_system::query::plumbing::try_execute_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:401:44
  16: rustc_query_system::query::plumbing::get_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
  17: rustc_middle::ty::query::TyCtxtAt::mir_for_ctfe
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:204:17
  18: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::mir_for_ctfe
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:185:17
  19: rustc_middle::mir::query::<impl rustc_middle::ty::context::TyCtxt>::mir_for_ctfe_opt_const_arg
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/mir/query.rs:437:13
  20: <rustc_const_eval::const_eval::machine::CompileTimeInterpreter as rustc_const_eval::interpret::machine::Machine>::load_mir
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/machine.rs:235:24
  21: rustc_const_eval::interpret::eval_context::InterpCx<M>::load_mir
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/interpret/eval_context.rs:503:9
  22: <rustc_const_eval::const_eval::machine::CompileTimeInterpreter as rustc_const_eval::interpret::machine::Machine>::find_mir_or_eval_fn
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/machine.rs:285:17
  23: rustc_const_eval::interpret::terminator::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::eval_fn_call
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/interpret/terminator.rs:295:27
  24: rustc_const_eval::interpret::terminator::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::eval_terminator
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/interpret/terminator.rs:103:17
  25: rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::terminator
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/interpret/step.rs:320:9
  26: rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::step
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/interpret/step.rs:73:9
  27: rustc_const_eval::interpret::step::<impl rustc_const_eval::interpret::eval_context::InterpCx<M>>::run
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/interpret/step.rs:34:15
  28: rustc_const_eval::const_eval::eval_queries::eval_body_using_ecx
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/eval_queries.rs:68:5
  29: rustc_const_eval::const_eval::eval_queries::eval_to_allocation_raw_provider::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/eval_queries.rs:313:31
  30: core::result::Result<T,E>::and_then
             at /media/ellen-nyan/Nyoomies/rust/library/core/src/result.rs:965:22
  31: rustc_const_eval::const_eval::eval_queries::eval_to_allocation_raw_provider
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/eval_queries.rs:313:11
  32: rustc_query_system::query::plumbing::execute_job::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:55
  33: stacker::maybe_grow
             at /home/ellen-nyan/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  34: rustc_data_structures::stack::ensure_sufficient_stack
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  35: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:136:17
  36: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:50
  37: rustc_middle::ty::context::tls::set_tlv
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1749:9
  38: rustc_middle::ty::context::tls::enter_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:9
  39: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:135:13
  40: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1809:13
  41: rustc_middle::ty::context::tls::with_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:40
  42: rustc_middle::ty::context::tls::with_context_opt
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1782:22
  43: rustc_middle::ty::context::tls::with_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:9
  44: rustc_middle::ty::context::tls::with_related_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1806:9
  45: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:124:9
  46: rustc_query_system::query::plumbing::execute_job
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:22
  47: rustc_query_system::query::plumbing::try_execute_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:401:44
  48: rustc_query_system::query::plumbing::get_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
  49: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_allocation_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:573:17
  50: rustc_middle::ty::query::TyCtxtAt::eval_to_allocation_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:204:17
  51: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::eval_to_allocation_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:185:17
  52: rustc_const_eval::const_eval::eval_queries::eval_to_const_value_raw_provider
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/eval_queries.rs:244:5
  53: rustc_query_system::query::plumbing::execute_job::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:55
  54: stacker::maybe_grow
             at /home/ellen-nyan/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  55: rustc_data_structures::stack::ensure_sufficient_stack
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  56: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:136:17
  57: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:50
  58: rustc_middle::ty::context::tls::set_tlv
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1749:9
  59: rustc_middle::ty::context::tls::enter_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:9
  60: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:135:13
  61: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1809:13
  62: rustc_middle::ty::context::tls::with_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:40
  63: rustc_middle::ty::context::tls::with_context_opt
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1782:22
  64: rustc_middle::ty::context::tls::with_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:9
  65: rustc_middle::ty::context::tls::with_related_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1806:9
  66: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:124:9
  67: rustc_query_system::query::plumbing::execute_job
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:22
  68: rustc_query_system::query::plumbing::try_execute_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:401:44
  69: rustc_query_system::query::plumbing::get_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
  70: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:573:17
  71: rustc_middle::ty::query::TyCtxtAt::eval_to_const_value_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:204:17
  72: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::eval_to_const_value_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:185:17
  73: rustc_const_eval::const_eval::eval_queries::eval_to_const_value_raw_provider
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_const_eval/src/const_eval/eval_queries.rs:221:15
  74: rustc_query_system::query::plumbing::execute_job::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:55
  75: stacker::maybe_grow
             at /home/ellen-nyan/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.14/src/lib.rs:55:9
  76: rustc_data_structures::stack::ensure_sufficient_stack
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/stack.rs:17:5
  77: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:136:17
  78: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:50
  79: rustc_middle::ty::context::tls::set_tlv
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1749:9
  80: rustc_middle::ty::context::tls::enter_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:9
  81: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:135:13
  82: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1809:13
  83: rustc_middle::ty::context::tls::with_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:40
  84: rustc_middle::ty::context::tls::with_context_opt
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1782:22
  85: rustc_middle::ty::context::tls::with_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:9
  86: rustc_middle::ty::context::tls::with_related_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1806:9
  87: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:124:9
  88: rustc_query_system::query::plumbing::execute_job
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:22
  89: rustc_query_system::query::plumbing::try_execute_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:401:44
  90: rustc_query_system::query::plumbing::get_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
  91: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:573:17
  92: rustc_middle::ty::query::TyCtxtAt::eval_to_const_value_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:204:17
  93: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::eval_to_const_value_raw
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:185:17
  94: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/mir/interpret/queries.rs:73:13
  95: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/mir/interpret/queries.rs:22:9
  96: <rustc_lint::builtin::UnusedBrokenConst as rustc_lint::passes::LateLintPass>::check_item
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/builtin.rs:1570:25
  97: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_item
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/passes.rs:116:13
  98: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_item::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:147:17
  99: rustc_lint::late::LateContextAndPass<T>::with_param_env
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:75:9
 100: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_item::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:146:13
 101: rustc_lint::late::LateContextAndPass<T>::with_lint_attrs
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:63:9
 102: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_item
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:145:9
 103: rustc_hir::intravisit::Visitor::visit_nested_item
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_hir/src/intravisit.rs:264:9
 104: rustc_hir::intravisit::walk_mod
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_hir/src/intravisit.rs:482:9
 105: rustc_lint::late::LateContextAndPass<T>::process_mod
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:81:9
 106: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_mod
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:258:13
 107: rustc_middle::hir::map::Map::walk_toplevel_module
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/hir/map/mod.rs:548:9
 108: rustc_lint::late::late_lint_pass_crate::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:452:9
 109: rustc_lint::late::LateContextAndPass<T>::with_lint_attrs
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:63:9
 110: rustc_lint::late::late_lint_pass_crate
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:448:5
 111: rustc_lint::late::late_lint_crate
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:466:9
 112: rustc_lint::late::check_crate::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:496:17
 113: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/profiling.rs:611:9
 114: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_session/src/utils.rs:16:9
 115: rustc_lint::late::check_crate::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:494:13
 116: rustc_data_structures::sync::join
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/sync.rs:119:14
 117: rustc_lint::late::check_crate
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_lint/src/late.rs:492:5
 118: rustc_interface::passes::analysis::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:961:29
 119: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/profiling.rs:611:9
 120: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_session/src/utils.rs:16:9
 121: rustc_interface::passes::analysis::{{closure}}::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:960:25
 122: core::ops::function::FnOnce::call_once
             at /media/ellen-nyan/Nyoomies/rust/library/core/src/ops/function.rs:227:5
 123: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /media/ellen-nyan/Nyoomies/rust/library/core/src/panic/unwind_safe.rs:271:9
 124: std::panicking::try::do_call
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panicking.rs:403:40
 125: std::panicking::try
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panicking.rs:367:19
 126: std::panic::catch_unwind
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panic.rs:133:14
 127: rustc_interface::passes::analysis::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:947:17
 128: core::ops::function::FnOnce::call_once
             at /media/ellen-nyan/Nyoomies/rust/library/core/src/ops/function.rs:227:5
 129: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /media/ellen-nyan/Nyoomies/rust/library/core/src/panic/unwind_safe.rs:271:9
 130: std::panicking::try::do_call
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panicking.rs:403:40
 131: std::panicking::try
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panicking.rs:367:19
 132: std::panic::catch_unwind
             at /media/ellen-nyan/Nyoomies/rust/library/std/src/panic.rs:133:14
 133: rustc_interface::passes::analysis::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:943:9
 134: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_data_structures/src/profiling.rs:611:9
 135: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_session/src/utils.rs:16:9
 136: rustc_interface::passes::analysis
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:942:5
 137: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:136:17
 138: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:50
 139: rustc_middle::ty::context::tls::set_tlv
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1749:9
 140: rustc_middle::ty::context::tls::enter_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:9
 141: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:135:13
 142: rustc_middle::ty::context::tls::with_related_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1809:13
 143: rustc_middle::ty::context::tls::with_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:40
 144: rustc_middle::ty::context::tls::with_context_opt
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1782:22
 145: rustc_middle::ty::context::tls::with_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1793:9
 146: rustc_middle::ty::context::tls::with_related_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1806:9
 147: <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::start_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_impl/src/plumbing.rs:124:9
 148: rustc_query_system::query::plumbing::execute_job
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:444:22
 149: rustc_query_system::query::plumbing::try_execute_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:401:44
 150: rustc_query_system::query::plumbing::get_query
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_query_system/src/query/plumbing.rs:733:36
 151: rustc_middle::ty::query::TyCtxtAt::analysis
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:204:17
 152: rustc_middle::ty::query::<impl rustc_middle::ty::context::TyCtxt>::analysis
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/query.rs:185:17
 153: rustc_driver::run_compiler::{{closure}}::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_driver/src/lib.rs:384:30
 154: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:784:42
 155: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:50
 156: rustc_middle::ty::context::tls::set_tlv
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1749:9
 157: rustc_middle::ty::context::tls::enter_context
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_middle/src/ty/context.rs:1765:9
 158: rustc_interface::passes::QueryContext::enter
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/passes.rs:784:9
 159: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_driver/src/lib.rs:383:13
 160: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/queries.rs:390:19
 161: rustc_driver::run_compiler::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_driver/src/lib.rs:312:22
 162: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/interface.rs:203:13
 163: rustc_span::with_source_map
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_span/src/lib.rs:976:5
 164: rustc_interface::interface::create_compiler_and_run
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/interface.rs:197:5
 165: rustc_interface::interface::run_compiler::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/interface.rs:219:12
 166: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/util.rs:145:13
 167: scoped_tls::ScopedKey<T>::set
             at /home/ellen-nyan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
 168: rustc_span::create_session_globals_then
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_span/src/lib.rs:109:5
 169: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /media/ellen-nyan/Nyoomies/rust/compiler/rustc_interface/src/util.rs:143:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_for_ctfe] caching mir of `ice` for CTFE
#1 [eval_to_allocation_raw] const-evaluating + checking `BAR`
#2 [eval_to_const_value_raw] simplifying constant for the type system `BAR`
#3 [eval_to_const_value_raw] simplifying constant for the type system `BAR`
#4 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by JohnTitor** [comment]
Triage: This doesn't trigger ICE with the latest nightly, marking as `E-needs-test`.

**Comment by matthiaskrgr** [comment]
Still crashing with `rustc 1.60.0-nightly (a00e130da 2022-01-29)` and debug assertions
