### ISSUE TITLE
Internal Compiler Error running in docker container

### ISSUE THREAD

**Issue by rster2002** [rust-lang/rust#90543]
### Code

```Rust
struct Greeting {
    name: String,
}

fn main() {
    let greeting = Greeting {
        name: "Bjørn".to_string()
    };

    println!("Hello, {}!", greeting.name);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: aarch64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

### Error output

```
   Compiling rust v0.1.0 (/var/rust)
thread 'rustc' panicked at 'Failed to recover key for crate_hash(c30dce060fa55696-4106f204c387a065) with hash c30dce060fa55696-4106f204c387a065', compiler/rustc_query_impl/src/lib.rs:56:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on aarch64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rust`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling rust v0.1.0 (/var/rust)
thread 'rustc' panicked at 'Failed to recover key for crate_hash(c30dce060fa55696-4106f204c387a065) with hash c30dce060fa55696-4106f204c387a065', compiler/rustc_query_impl/src/lib.rs:56:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   2: rustc_query_impl::query_callbacks::all_traits::try_load_from_on_disk_cache::{{closure}}
   3: rustc_query_impl::query_callbacks::reachable_non_generics::try_load_from_on_disk_cache
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::serialize
   7: rustc_middle::ty::context::TyCtxt::serialize_query_result_cache
   8: rustc_incremental::persist::save::save_in
   9: rustc_data_structures::sync::join
  10: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  11: rustc_incremental::persist::save::save_dep_graph
  12: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  13: rustc_span::with_source_map
  14: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on aarch64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rust`
```

</p>
</details>

**Comment by hkratz** [comment]
What docker image did you use? Can you post your Dockerfile?

**Comment by rster2002** [comment]
I used the `ubuntu` image itself and then followed the installation guide on the website.

**Comment by hkratz** [comment]
Can't reproduce it like that:
```
$ uname -p
aarch64
$ docker run -it --rm ubuntu
root@9779d2dedc08:/# apt-get update -qq && apt-get install -y curl build-essential > /dev/null 2> /dev/null
root@9779d2dedc08:/# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q > /dev/null 2>/dev/null
root@9779d2dedc08:/# source $HOME/.cargo/env
root@9779d2dedc08:/# cargo init helloworld
     Created binary (application) package
root@9779d2dedc08:/# cd helloworld/
root@9779d2dedc08:/helloworld# cargo run
   Compiling helloworld v0.1.0 (/helloworld)
    Finished dev [unoptimized + debuginfo] target(s) in 1.31s
     Running `target/debug/helloworld`
Hello, world!
root@9779d2dedc08:/helloworld# cat > src/main.rs
struct Greeting {
    name: String,
}

fn main() {
    let greeting = Greeting {
        name: "Bjørn".to_string()
    };

    println!("Hello, {}!", greeting.name);
}
root@9779d2dedc08:/helloworld# cargo run
   Compiling helloworld v0.1.0 (/helloworld)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target/debug/helloworld`
Hello, Bjørn!
```

`rustc --version --verbose`:
```
root@9779d2dedc08:/helloworld# rustc --version --verbose
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: aarch64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

**Comment by rster2002** [comment]
Trying the above it also seems to work for me. I will try to create a new container the same way I did yesterday to see if it was just a hick-up.

**Comment by rster2002** [comment]
Just tried the same container I used yesterday and seems the issue has fixed itself, so probably one time hick-up. Thanks for your time.
