### ISSUE TITLE
`vptx64-nvidia-cuda` target triplet panics during compilation

### ISSUE THREAD

**Issue by Takashiidobe** [rust-lang/rust#90548]
### Context

A `#![no_std]` hello world binary panics when compiling for `vptx64-nvidia-cuda` target triplet. Rustc says it is due to this target not supporting dylibs. 

### Code

The code to compile is a `no_std` hello world cross compiled using `cross build`.

This code compiles just fine in most targets (Tier 1 + 2, I've tested 40+ other targets so far in github actions).

src/main.rs

```Rust
#![no_std]
#![no_main]

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[link(name = "c")]
extern "C" {
    fn write(fd: i32, buf: *const i8, count: usize) -> isize;
}

#[no_mangle]
pub extern "C" fn main() -> isize {
    unsafe { write(1, b"Hello, World!\n" as *const u8 as *const i8, 14) };
    0
}
```

Cargo.toml

```rs
[package]
name = "rust-build-binary-github-actions"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
```

#### Stable:

```
$ rustc --version --verbose
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

#### Nightly:

```
$ rustc --version --verbose
rustc 1.58.0-nightly (18bc4bee9 2021-11-02)
binary: rustc
commit-hash: 18bc4bee9710b181b440a472635150f0d6257713
commit-date: 2021-11-02
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

#### Beta:

```
$ rustc --version --verbose
rustc 1.57.0-beta.3 (708d57e28 2021-11-01)
binary: rustc
commit-hash: 708d57e288d051a6238ed56039ffeac158e10e84
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.57.0-beta.3
LLVM version: 13.0.0
```

### Error output

Note: Error output is the same for stable, nightly and beta.

```
$ cross build --locked --release --target=nvptx64-nvidia-cuda
Compiling rust-build-binary-github-actions v0.1.0 (/home/runner/work/rust-build-binary-github-actions/rust-build-binary-github-actions)
thread 'rustc' panicked at 'external dylibs not supported', compiler/rustc_codegen_ssa/src/back/linker.rs:1436:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C panic=abort -C embed-bitcode=no --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rust-build-binary-github-actions`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ cross build --locked --release --target=nvptx64-nvidia-cuda
Compiling rust-build-binary-github-actions v0.1.0 (/home/runner/work/rust-build-binary-github-actions/rust-build-binary-github-actions)
thread 'rustc' panicked at 'external dylibs not supported', compiler/rustc_codegen_ssa/src/back/linker.rs:1436:9
stack backtrace:
   0: std::panicking::begin_panic
   1: <rustc_codegen_ssa::back::linker::PtxLinker as rustc_codegen_ssa::back::linker::Linker>::link_dylib
   2: rustc_codegen_ssa::back::link::add_local_native_libraries
   3: rustc_codegen_ssa::back::link::link_natively
   4: rustc_codegen_ssa::back::link::link_binary
   5: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::link
   6: rustc_interface::queries::Linker::link
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C panic=abort -C embed-bitcode=no --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rust-build-binary-github-actions`
```

</p>
</details>

**Comment by Takashiidobe** [comment]
Reading through `https://github.com/japaric-archived/nvptx#targets` It says this target is for emitting asm.

Closing.
