### ISSUE TITLE
ICE 

### ISSUE THREAD

**Issue by spcan** [rust-lang/rust#90968]
### Code

Code is quite big to be able to display inside the issue. I can upload to a repository if needed.

Overview of what is happening in the code:
    - Create a zero size struct with a generic constant associated to compute at compile time a pointer to an embedded peripheral.
    - Create a wrapper around it to communicate with a device. This wrapper has some methods that return Result<[f32; 3], I::Error> where Error is the error type of the peripheral.
    - Inside this function an inner function is called with the signature: `fn write_to_address<const A: AddressType>(6mut self, bytes: &[u8]) -> Result<(), I::Error>`, this is where the ICE is happening.

```Rust


```

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (891ca5f63 2021-11-15)
binary: rustc
commit-hash: 891ca5f63c3b3cfe3939710a728671243e881ed6
commit-date: 2021-11-15
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### Error output

```
error: internal compiler error: compiler/rustc_traits/src/normalize_erasing_regions.rs:54:32: could not fully normalize `core::result::Result<(), <micro_rp2040::peripherals::comm::i2c::blocking::I2CMasterInterface<N> as embedded_hal::i2c::blocking::Write>::Error>`

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (891ca5f63 2021-11-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z trap-unreachable=no -C opt-level=3 -C panic=abort -C lto -C debuginfo=2 -C link-arg=--nmagic -C link-arg=-Tlink.x -C link-arg=-Tdefmt.x -C inline-threshold=5 -C no-vectorize-loops --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `core::result::Result<(), <micro_rp2040::peripherals::comm::i2c::blocking::master::interface::I2CMasterInterface<N> as embedded_hal::i2c::blocking::Write>::Error>`
#1 [fn_abi_of_instance] computing call ABI of `micro_rp2040::peripherals::comm::i2c::blocking::master::eh::<impl embedded_hal::i2c::blocking::Write for micro_rp2040::peripherals::comm::i2c::blocking::master::interface::I2CMasterInterface<1_usize>>::write`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f584619729c - std::backtrace_rs::backtrace::libunwind::trace::h793e05efd273d0f4
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f584619729c - std::backtrace_rs::backtrace::trace_unsynchronized::h640b7b86ff610c77
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f584619729c - std::sys_common::backtrace::_print_fmt::h362fa2a4f354f877
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f584619729c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf439e5ed84c74abd
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f58461f453c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/fmt/mod.rs:1149:17
   5:     0x7f5846187a35 - std::io::Write::write_fmt::h5562a8b6da0f0339
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/io/mod.rs:1697:15
   6:     0x7f584619a4f0 - std::sys_common::backtrace::_print::hb29ddd998d02631c
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f584619a4f0 - std::sys_common::backtrace::print::h81965e3d7c90fbb6
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f584619a4f0 - std::panicking::default_hook::{{closure}}::h84db205ab6674b38
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panicking.rs:211:50
   9:     0x7f584619a09b - std::panicking::default_hook::h1bf8bb4159936bca
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panicking.rs:228:9
  10:     0x7f5846930e91 - rustc_driver[e620c7401644acc4]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f583c224ae3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb3b781002ad9f488
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/alloc/src/boxed.rs:1708:9
  12:     0x7f583c236b1d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h648f1f87f5ea2953
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7f584619ad09 - std::panicking::rust_panic_with_hook::hf8e86850fbbd03b1
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panicking.rs:610:17
  14:     0x7f5847a256eb - std[a5529df289459975]::panicking::begin_panic::<rustc_errors[c8a333c965fedc03]::ExplicitBug>::{closure#0}
  15:     0x7f5847a25606 - std[a5529df289459975]::sys_common::backtrace::__rust_end_short_backtrace::<std[a5529df289459975]::panicking::begin_panic<rustc_errors[c8a333c965fedc03]::ExplicitBug>::{closure#0}, !>
  16:     0x7f5847a254ef - std[a5529df289459975]::panicking::begin_panic::<rustc_errors[c8a333c965fedc03]::ExplicitBug>
  17:     0x7f5847a35a1d - std[a5529df289459975]::panic::panic_any::<rustc_errors[c8a333c965fedc03]::ExplicitBug>
  18:     0x7f5847a3793d - <rustc_errors[c8a333c965fedc03]::HandlerInner>::bug
  19:     0x7f5847a373e0 - <rustc_errors[c8a333c965fedc03]::Handler>::bug
  20:     0x7f5847893bf6 - rustc_middle[93690e4789d7fe1d]::ty::context::tls::with_opt::<rustc_middle[93690e4789d7fe1d]::util::bug::opt_span_bug_fmt<rustc_span[2d5555579096f1fe]::span_encoding::Span>::{closure#0}, ()>
  21:     0x7f5847896490 - rustc_middle[93690e4789d7fe1d]::util::bug::opt_span_bug_fmt::<rustc_span[2d5555579096f1fe]::span_encoding::Span>
  22:     0x7f5847896406 - rustc_middle[93690e4789d7fe1d]::util::bug::bug_fmt
  23:     0x7f58481ad0ca - <rustc_infer[7163d95876195c41]::infer::InferCtxtBuilder>::enter::<rustc_middle[93690e4789d7fe1d]::ty::subst::GenericArg, rustc_traits[ffd713ba2c8d3aad]::normalize_erasing_regions::normalize_after_erasing_regions<rustc_middle[93690e4789d7fe1d]::ty::subst::GenericArg>::{closure#0}>
  24:     0x7f58481ba97a - <rustc_traits[ffd713ba2c8d3aad]::normalize_erasing_regions::provide::{closure#0} as core[cc79c391059f8e46]::ops::function::FnOnce<(rustc_middle[93690e4789d7fe1d]::ty::context::TyCtxt, rustc_middle[93690e4789d7fe1d]::ty::ParamEnvAnd<rustc_middle[93690e4789d7fe1d]::ty::subst::GenericArg>)>>::call_once
  25:     0x7f58481d3709 - rustc_query_system[efb192c4209e4e11]::query::plumbing::try_execute_query::<rustc_query_impl[e405c240d479aca8]::plumbing::QueryCtxt, rustc_query_system[efb192c4209e4e11]::query::caches::DefaultCache<rustc_middle[93690e4789d7fe1d]::ty::ParamEnvAnd<rustc_middle[93690e4789d7fe1d]::ty::subst::GenericArg>, rustc_middle[93690e4789d7fe1d]::ty::subst::GenericArg>>
  26:     0x7f5848288bf4 - <rustc_query_impl[e405c240d479aca8]::Queries as rustc_middle[93690e4789d7fe1d]::ty::query::QueryEngine>::normalize_generic_arg_after_erasing_regions
  27:     0x7f58486c323d - rustc_middle[93690e4789d7fe1d]::ty::util::fold_list::<rustc_middle[93690e4789d7fe1d]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder, &rustc_middle[93690e4789d7fe1d]::ty::TyS, <&rustc_middle[93690e4789d7fe1d]::ty::list::List<&rustc_middle[93690e4789d7fe1d]::ty::TyS> as rustc_middle[93690e4789d7fe1d]::ty::fold::TypeFoldable>::super_fold_with<rustc_middle[93690e4789d7fe1d]::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>::{closure#0}>
  28:     0x7f58486d4752 - rustc_middle[93690e4789d7fe1d]::ty::layout::fn_abi_of_instance
  29:     0x7f58481d7f8a - rustc_query_system[efb192c4209e4e11]::query::plumbing::try_execute_query::<rustc_query_impl[e405c240d479aca8]::plumbing::QueryCtxt, rustc_query_system[efb192c4209e4e11]::query::caches::DefaultCache<rustc_middle[93690e4789d7fe1d]::ty::ParamEnvAnd<(rustc_middle[93690e4789d7fe1d]::ty::instance::Instance, &rustc_middle[93690e4789d7fe1d]::ty::list::List<&rustc_middle[93690e4789d7fe1d]::ty::TyS>)>, core[cc79c391059f8e46]::result::Result<&rustc_target[819931b88a693851]::abi::call::FnAbi<&rustc_middle[93690e4789d7fe1d]::ty::TyS>, rustc_middle[93690e4789d7fe1d]::ty::layout::FnAbiError>>>
  30:     0x7f58482876ec - <rustc_query_impl[e405c240d479aca8]::Queries as rustc_middle[93690e4789d7fe1d]::ty::query::QueryEngine>::fn_abi_of_instance
  31:     0x7f5847bb5f1b - rustc_codegen_ssa[f6374deef2cbb8fd]::mir::codegen_mir::<rustc_codegen_llvm[3ea7e54ed77cfea0]::builder::Builder>
  32:     0x7f5847ba2c91 - rustc_codegen_llvm[3ea7e54ed77cfea0]::base::compile_codegen_unit::module_codegen
  33:     0x7f58488300b6 - <rustc_query_system[efb192c4209e4e11]::dep_graph::graph::DepGraph<rustc_middle[93690e4789d7fe1d]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[93690e4789d7fe1d]::ty::context::TyCtxt, rustc_span[2d5555579096f1fe]::symbol::Symbol, rustc_codegen_ssa[f6374deef2cbb8fd]::ModuleCodegen<rustc_codegen_llvm[3ea7e54ed77cfea0]::ModuleLlvm>>
  34:     0x7f5848866b46 - rustc_codegen_llvm[3ea7e54ed77cfea0]::base::compile_codegen_unit
  35:     0x7f5848846b18 - <rustc_codegen_llvm[3ea7e54ed77cfea0]::LlvmCodegenBackend as rustc_codegen_ssa[f6374deef2cbb8fd]::traits::backend::CodegenBackend>::codegen_crate
  36:     0x7f5848800517 - <rustc_session[cec017cef00f19c9]::session::Session>::time::<alloc[9a4bc13598ff604f]::boxed::Box<dyn core[cc79c391059f8e46]::any::Any>, rustc_interface[f89f8228a4e35bc7]::passes::start_codegen::{closure#0}>
  37:     0x7f58487e2198 - <rustc_interface[f89f8228a4e35bc7]::passes::QueryContext>::enter::<<rustc_interface[f89f8228a4e35bc7]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[cc79c391059f8e46]::result::Result<alloc[9a4bc13598ff604f]::boxed::Box<dyn core[cc79c391059f8e46]::any::Any>, rustc_errors[c8a333c965fedc03]::ErrorReported>>
  38:     0x7f58487dcc0f - <rustc_interface[f89f8228a4e35bc7]::queries::Queries>::ongoing_codegen
  39:     0x7f58487c17c7 - <rustc_interface[f89f8228a4e35bc7]::interface::Compiler>::enter::<rustc_driver[e620c7401644acc4]::run_compiler::{closure#1}::{closure#2}, core[cc79c391059f8e46]::result::Result<core[cc79c391059f8e46]::option::Option<rustc_interface[f89f8228a4e35bc7]::queries::Linker>, rustc_errors[c8a333c965fedc03]::ErrorReported>>
  40:     0x7f58487b241d - rustc_span[2d5555579096f1fe]::with_source_map::<core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>, rustc_interface[f89f8228a4e35bc7]::interface::create_compiler_and_run<core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>, rustc_driver[e620c7401644acc4]::run_compiler::{closure#1}>::{closure#1}>
  41:     0x7f58487c2718 - <scoped_tls[3fea4c3dcac147b1]::ScopedKey<rustc_span[2d5555579096f1fe]::SessionGlobals>>::set::<rustc_interface[f89f8228a4e35bc7]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[f89f8228a4e35bc7]::interface::run_compiler<core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>, rustc_driver[e620c7401644acc4]::run_compiler::{closure#1}>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>>::{closure#0}::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>>
  42:     0x7f58487b4ed5 - std[a5529df289459975]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f89f8228a4e35bc7]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[f89f8228a4e35bc7]::interface::run_compiler<core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>, rustc_driver[e620c7401644acc4]::run_compiler::{closure#1}>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>>
  43:     0x7f58487b0fb2 - <<std[a5529df289459975]::thread::Builder>::spawn_unchecked<rustc_interface[f89f8228a4e35bc7]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[f89f8228a4e35bc7]::interface::run_compiler<core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>, rustc_driver[e620c7401644acc4]::run_compiler::{closure#1}>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[c8a333c965fedc03]::ErrorReported>>::{closure#1} as core[cc79c391059f8e46]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f58461a5ff3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h771719d52c343434
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/alloc/src/boxed.rs:1694:9
  45:     0x7f58461a5ff3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf441746dfa4b0f57
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/alloc/src/boxed.rs:1694:9
  46:     0x7f58461a5ff3 - std::sys::unix::thread::Thread::new::thread_start::hfd168f9d312b29ca
                               at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/sys/unix/thread.rs:106:17
  47:     0x7f58460ca609 - start_thread
                               at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  48:     0x7f5845fde293 - clone
  49:                0x0 - <unknown>

```

</p>
</details>

**Comment by spcan** [comment]
Changing the signature of the `write_to_address` function to `fn write_to_address(&mut self, a: AddressType, bytes: &[u8]) -> Result<(),I::Error>` does ICE as well.

**Comment by spcan** [comment]
Switching from implementing the `embedded_hal::i2c::blocking::WriteRead` trait for a generic const to a manual implementation for all peripherals fixes the ICE.

**Comment by Enselic** [comment]
Triage: Without a way for others to reproduce this ICE, not much more can be done at the moment, so let's close this issue. Feel free to reopen after adding a way for others to reproduce the ICE.
