### ISSUE TITLE
ICE: ProjectionKinds Deref and Field were mismatched: (Deref, Field(5, 0))

### ISSUE THREAD

**Issue by mendess** [rust-lang/rust#91293]
### Code

I'm going to try to make a minimal rust example, in the mean time, this commit has my code in the state that causes the ICE: https://github.com/mendess/wtime/tree/246e60ceb9b65f4e389eaf6c4b76a05995894a92

The error message points to [`main.rs`](https://github.com/mendess/wtime/blob/246e60ceb9b65f4e389eaf6c4b76a05995894a92/src/main.rs#L134)

#### Stable

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

#### Nightly
The ICE does not happen in any of these nightly versions:
```
rustc 1.58.0-nightly (46b8e7488 2021-11-07)
binary: rustc
commit-hash: 46b8e7488eae116722196e8390c1bd2ea2e396cf
commit-date: 2021-11-07
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```
```
rustc 1.58.0-nightly (6d246f0c8 2021-11-26)
binary: rustc
commit-hash: 6d246f0c8d3063fea86abbb65a824362709541ba
commit-date: 2021-11-26
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

#### Beta
This seems to also not be present in beta
```
rustc 1.57.0-beta.7 (ef1a3b934 2021-11-19)
binary: rustc
commit-hash: ef1a3b93491be53289ab6b8af235a9e100d771f2
commit-date: 2021-11-19
host: x86_64-unknown-linux-gnu
release: 1.57.0-beta.7
LLVM version: 13.0.0
```

### Error output

```rust
error[E0616]: field `selected` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:254:41
    |
254 |                 .style(if action == new.selected {
    |                                         ^^^^^^^^ private field

error[E0616]: field `action` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:267:48
    |
267 |         let action = mkparagraph("action", new.action.as_str(), Selected::Action);
    |                                                ^^^^^^ private field

error[E0616]: field `start_time` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:268:57
    |
268 |         let start_time = mkparagraph("start time", &new.start_time, Selected::StartTime);
    |                                                         ^^^^^^^^^^ private field

error[E0616]: field `end_time` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:269:53
    |
269 |         let end_time = mkparagraph("end time", &new.end_time, Selected::EndTime);
    |                                                     ^^^^^^^^ private field

error[E0616]: field `day` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:270:43
    |
270 |         let day = mkparagraph("day", &new.day, Selected::Day);
    |                                           ^^^ private field

error: internal compiler error: compiler/rustc_typeck/src/check/upvar.rs:641:30: ProjectionKinds Deref and Field were mismatched: (Deref, Field(5, 0))

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1147:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `ui`
#1 [typeck] type-checking `ui::{closure#0}::{closure#0}`
end of query stack
For more information about this error, try `rustc --explain E0616`.
error: could not compile `wtime` due to 5 previous errors
```

#### The above mentioned nightly error output
```rust
error[E0616]: field `selected` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:254:41
    |
254 |                 .style(if action == new.selected {
    |                                         ^^^^^^^^ private field

error[E0616]: field `action` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:267:48
    |
267 |         let action = mkparagraph("action", new.action.as_str(), Selected::Action);
    |                                                ^^^^^^ private field

error[E0616]: field `start_time` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:268:57
    |
268 |         let start_time = mkparagraph("start time", &new.start_time, Selected::StartTime);
    |                                                         ^^^^^^^^^^ private field

error[E0616]: field `end_time` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:269:53
    |
269 |         let end_time = mkparagraph("end time", &new.end_time, Selected::EndTime);
    |                                                     ^^^^^^^^ private field

error[E0616]: field `day` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:270:43
    |
270 |         let day = mkparagraph("day", &new.day, Selected::Day);
    |                                           ^^^ private field

error[E0283]: type annotations needed for `{integer}`
   --> src/main.rs:291:72
    |
159 |     let mut total_days = 0;
    |         -------------- consider giving `total_days` a type
...
291 |         let avg_per_day = Paragraph::new(fmt_duration(total_month_time / total_days)).block(
    |                                                                        ^ cannot infer type for type `{integer}`
    |
    = note: multiple `impl`s satisfying `time::Duration: Div<{integer}>` found in the `time` crate:
            - impl Div<i16> for time::Duration;
            - impl Div<i32> for time::Duration;
            - impl Div<i8> for time::Duration;
            - impl Div<u16> for time::Duration;
            and 2 more

Some errors have detailed explanations: E0283, E0616.
For more information about an error, try `rustc --explain E0283`.
error: could not compile `wtime` due to 6 previous errors
```

#### The above mentioned beta output

```rust
error[E0616]: field `selected` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:254:41
    |
254 |                 .style(if action == new.selected {
    |                                         ^^^^^^^^ private field

error[E0616]: field `action` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:267:48
    |
267 |         let action = mkparagraph("action", new.action.as_str(), Selected::Action);
    |                                                ^^^^^^ private field

error[E0616]: field `start_time` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:268:57
    |
268 |         let start_time = mkparagraph("start time", &new.start_time, Selected::StartTime);
    |                                                         ^^^^^^^^^^ private field

error[E0616]: field `end_time` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:269:53
    |
269 |         let end_time = mkparagraph("end time", &new.end_time, Selected::EndTime);
    |                                                     ^^^^^^^^ private field

error[E0616]: field `day` of struct `ActivityBeingBuilt` is private
   --> src/main.rs:270:43
    |
270 |         let day = mkparagraph("day", &new.day, Selected::Day);
    |                                           ^^^ private field

For more information about this error, try `rustc --explain E0616`.
error: could not compile `wtime` due to 5 previous errors
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1147:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: alloc::slice::<impl [T]>::sort_by::{{closure}}
   8: alloc::slice::merge_sort
   9: rustc_typeck::check::upvar::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::compute_min_captures
  10: rustc_typeck::check::upvar::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::analyze_closure
  11: <rustc_typeck::check::upvar::InferBorrowKindVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  12: rustc_hir::intravisit::walk_stmt
  13: rustc_hir::intravisit::walk_expr
  14: rustc_hir::intravisit::walk_expr
  15: <rustc_typeck::check::upvar::InferBorrowKindVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  16: <rustc_typeck::check::upvar::InferBorrowKindVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  17: rustc_typeck::check::upvar::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::closure_analyze
  18: rustc_infer::infer::InferCtxtBuilder::enter
  19: rustc_typeck::check::typeck
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::force_query_with_job
  23: rustc_query_system::query::plumbing::get_query_impl
  24: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  25: rustc_typeck::check::typeck
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::force_query_with_job
  29: rustc_query_system::query::plumbing::get_query_impl
  30: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  31: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  32: rustc_typeck::check::typeck_item_bodies
  33: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  34: rustc_query_system::query::plumbing::force_query_with_job
  35: rustc_query_system::query::plumbing::get_query_impl
  36: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck_item_bodies
  37: rustc_session::utils::<impl rustc_session::session::Session>::time
  38: rustc_typeck::check_crate
  39: rustc_interface::passes::analysis
  40: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  41: rustc_data_structures::stack::ensure_sufficient_stack
  42: rustc_query_system::query::plumbing::force_query_with_job
  43: rustc_query_system::query::plumbing::get_query_impl
  44: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  45: rustc_interface::passes::QueryContext::enter
  46: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  47: rustc_span::with_source_map
  48: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `ui`
#1 [typeck] type-checking `ui::{closure#0}::{closure#0}`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by compiler-errors** [comment]
Since this is fixed on recent versions and 1.56.1 is quite old, closing this.
