### ISSUE TITLE
Internal Compiler Error after moving a module

### ISSUE THREAD

**Issue by og-dev** [rust-lang/rust#91558]
### Code

```Rust
<code>
There is no indication of where the failure occurs in the code.

It just stopped compiling and throws that error.

I moved a module from one folder to another,
I fixed the import paths. Then, when I try to compile it comes up with that error.
```

### Meta

`rustc --version --verbose`:
```
<version>
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
<output>
error: could not compile `dev_soft_account`; 7 warnings emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
stack backtrace:
   0:     0x7f8ae6735a9c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f8ae6735a9c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8ae6735a9c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8ae6735a9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f8ae6792fdc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x7f8ae6725c05 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x7f8ae6738f60 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f8ae6738f60 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f8ae6738f60 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x7f8ae6738b15 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x7f8ae6f252b1 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h932547f60770f26a
  11:     0x7f8ad14ebd83 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5929a71578584714
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1705:9
  12:     0x7f8ad14ecaed - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h458be0da3125e66c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7f8ae6739779 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
  14:     0x7f8ae6739202 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
  15:     0x7f8ae6735f44 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  16:     0x7f8ae6739199 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  17:     0x7f8ae66fd441 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  18:     0x7f8ae66fd38d - core::panicking::panic::h0ba7146865b2f9d6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
  19:     0x7f8ae8728b47 - <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id::hb925ab58899dddff
  20:     0x7f8ae8a94b21 - rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover::h2e76aa40aab4da19
  21:     0x7f8ae911f52c - rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node::hc7fd02f51ac51090
  22:     0x7f8ae8713d6a - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  23:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  24:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  25:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  26:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  27:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  28:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  29:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  30:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  31:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  32:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  33:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  34:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  35:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  36:     0x7f8ae86a0ecc - rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::h0eb1b79b9e091780
  37:     0x7f8ae86bd66d - rustc_query_system::query::plumbing::get_query::he848c9a74d759f95
  38:     0x7f8ae870fd24 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation::h2b78688237f47182
  39:     0x7f8ae89289d9 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation::h8dd6b3a9b1045c30
  40:     0x7f8ae8928e00 - <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow::h9254e4a68f95d40c
  41:     0x7f8ae894b61d - rustc_trait_selection::traits::fulfill::FulfillProcessor::process_trait_obligation::hd2a96a9f24be244a
  42:     0x7f8ae8944c03 - rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations::hfe1bcc41b6d0982a
  43:     0x7f8ae897799d - rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations::h44a6a3ba4a0d74cb
  44:     0x7f8ae8944059 - rustc_trait_selection::traits::fulfill::FulfillmentContext::select::hbd72a111ba645b38
  45:     0x7f8ae89449d2 - <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_with_constness_where_possible::hf54390769d3623c5
  46:     0x7f8ae82841f6 - rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_generator_interiors::h82e2c2b68dbab7e2
  47:     0x7f8ae82f3dfe - rustc_infer::infer::InferCtxtBuilder::enter::hfd0c29f454bb3dd3
  48:     0x7f8ae82e9b13 - rustc_typeck::check::typeck::hd2945a0033787c16
  49:     0x7f8ae91486e1 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h2483c0c71c4f2b2a
  50:     0x7f8ae90f2b33 - rustc_data_structures::stack::ensure_sufficient_stack::h505c3226f8bf8a56
  51:     0x7f8ae8688895 - rustc_query_system::query::plumbing::try_execute_query::h7c58dd7d89c4c4cf
  52:     0x7f8ae900cc23 - rustc_query_system::query::plumbing::force_query_impl::hb27911982f28ae98
  53:     0x7f8ae9121346 - rustc_query_impl::query_callbacks::typeck::force_from_dep_node::hd32e9d234745bec5
  54:     0x7f8ae8713d6a - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  55:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  56:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  57:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  58:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  59:     0x7f8ae8713d41 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::h14b50df9818693f3
  60:     0x7f8ae86a12aa - rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::h10cfccd9dcdc48f2
  61:     0x7f8ae8681672 - rustc_query_system::query::plumbing::try_execute_query::h5e8ca9cdff1d8669
  62:     0x7f8ae870b176 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of::h91474f612f5fd18f
  63:     0x7f8ae835692d - rustc_typeck::check::check::check_item_type::h83aecb3db5647369
  64:     0x7f8ae832a137 - rustc_middle::hir::map::Map::visit_item_likes_in_module::hb332e99923689268
  65:     0x7f8ae8e453ac - rustc_typeck::check::check::check_mod_item_types::h5a35f43b9b9d9dea
  66:     0x7f8ae9151731 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h429476b70c6d8b4c
  67:     0x7f8ae90fd6b3 - rustc_data_structures::stack::ensure_sufficient_stack::he8ab55a8c5d4796d
  68:     0x7f8ae867afa9 - rustc_query_system::query::plumbing::try_execute_query::h3f25d612f789df1c
  69:     0x7f8ae912cb65 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types::h1109e01393bf5f0a
  70:     0x7f8ae8e216e1 - rustc_middle::hir::map::Map::for_each_module::hf1d120cb6d680f52
  71:     0x7f8ae8dd04d0 - rustc_typeck::check_crate::h6215961d94aab927
  72:     0x7f8ae8b2f0a0 - rustc_interface::passes::analysis::h9fda1a8ae44d53e7
  73:     0x7f8ae91493cf - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h26e86d963a73dec8
  74:     0x7f8ae90ee609 - rustc_data_structures::stack::ensure_sufficient_stack::h135baf7277c4d193
  75:     0x7f8ae9012a7b - rustc_query_system::query::plumbing::try_execute_query::h0bf7639d3f58bfbd
  76:     0x7f8ae912b232 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::ha2144cf05b40d10d
  77:     0x7f8ae8b23ca9 - rustc_interface::passes::QueryContext::enter::h0523b23606206a0b
  78:     0x7f8ae8b0a977 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hf84cd18c24bd5171
  79:     0x7f8ae8af80ee - rustc_span::with_source_map::h6ab8a240e103b5b9
  80:     0x7f8ae8b0a2ac - scoped_tls::ScopedKey<T>::set::hd1fbd64c6f645895
  81:     0x7f8ae8af8ef5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a1328c9fa7f7448
  82:     0x7f8ae8b24962 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4ea1ced06d6b3e97
  83:     0x7f8ae6744933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7bd677a5dc988be6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  84:     0x7f8ae6744933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7b1c1ba11c4db785
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  85:     0x7f8ae6744933 - std::sys::unix::thread::Thread::new::thread_start::h9c58c0d12d84e854
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  86:     0x7f8ae6676609 - start_thread
                               at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  87:     0x7f8ae658a293 - clone
  88:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `for<'r, 's> {core::future::ResumeTy, infonicsa::Update<infonicsa_core::transform::auto_exec::AutoExec<infoncicsa::core::Message>, types::callback_query::CallbackQuery>, impl core::future::future::Future, (), core::result::Result<(), alloc::boxed::Box<(dyn std::error::Error + core::marker::Send + core::marker::Sync + 'r)>>, core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output = ()> + core::marker::Send + 's)>>}: core::marker::Send`
#1 [typeck] type-checking `run`
#2 [type_of] computing type of `run::{opaque#0}`
#3 [check_mod_item_types] checking item types in top-level module
#4 [analysis] running analysis passes on this crate
```

</p>
</details>

**Comment by asquared31415** [comment]
This might be an incremental compilation issue, does `cargo clean` resolve the issue?

**Comment by og-dev** [comment]
> This might be an incremental compilation issue, does `cargo clean` resolve the issue?

Yes

**Comment by og-dev** [comment]
`cargo clean` fixed
