### ISSUE TITLE
internal compiler error: encountered incremental compilation error with evaluate_obligation(1cec0724321627f4-89c75a6914c2ffb3)

### ISSUE THREAD

**Issue by martinrlilja** [rust-lang/rust#91572]
### Code

Not sure it matters but I encountered this when I reordered the arguments of a `tracing::info!` call.

```Rust
tracing::info!(
    remote_addr = %remote_addr,
    method = %req.method(),
    path = %req.uri(),
    version = ?req.version(),
);
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

### Error output

```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(1cec0724321627f4-89c75a6914c2ffb3)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p prj` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(1cec0724321627f4-89c75a6914c2ffb3): Ok(EvaluatedToOk)', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/compiler/rustc_query_system/src/query/plumbing.rs:644:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `hyper::proto::h2::PipeToSendStream<server::EitherBody<http_body::combinators::UnsyncBoxBody<hyper::body::Bytes, tonic::Status>, hyper::Body>>: std::marker::Send`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [hyper::server::conn::spawn_all::NoopWatcher, hyper::server::conn::AddrStream, tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, hyper::common::exec::Exec], item_def_id: DefId(155:5740 ~ hyper[2c4b]::server::conn::spawn_all::Watcher::Future) } } }`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(1cec0724321627f4-89c75a6914c2ffb3)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p prj` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for evaluate_obligation(1cec0724321627f4-89c75a6914c2ffb3): Ok(EvaluatedToOk)', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/compiler/rustc_query_system/src/query/plumbing.rs:644:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_data_structures::stack::ensure_sufficient_stack
   5: rustc_query_system::query::plumbing::get_query_impl
   6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation
   7: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
   8: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
   9: rustc_trait_selection::traits::fulfill::FulfillProcessor::process_trait_obligation
  10: rustc_trait_selection::traits::fulfill::FulfillProcessor::progress_changed_obligations
  11: rustc_data_structures::obligation_forest::ObligationForest<O>::process_obligations
  12: rustc_trait_selection::traits::fulfill::FulfillmentContext::select
  13: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
  14: <rustc_infer::infer::InferCtxtBuilder as rustc_trait_selection::infer::InferCtxtBuilderExt>::enter_canonical_trait_query
  15: rustc_traits::normalize_projection_ty::normalize_projection_ty
  16: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  17: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::get_query_impl
  20: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_projection_ty
  21: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  22: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize
  23: rustc_infer::infer::InferCtxtBuilder::enter
  24: core::ops::function::FnOnce::call_once
  25: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  26: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::get_query_impl
  29: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_generic_arg_after_erasing_regions
  30: rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder::normalize_generic_arg_after_erasing_regions
  31: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  32: rustc_ty_utils::needs_drop::needs_drop_raw
  33: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  34: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  35: rustc_data_structures::stack::ensure_sufficient_stack
  36: rustc_query_system::query::plumbing::get_query_impl
  37: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::needs_drop_raw
  38: rustc_ty_utils::instance::inner_resolve_instance
  39: rustc_ty_utils::instance::resolve_instance
  40: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  41: rustc_data_structures::stack::ensure_sufficient_stack
  42: rustc_query_system::query::plumbing::get_query_impl
  43: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  44: rustc_middle::ty::instance::Instance::resolve_opt_const_arg
  45: rustc_middle::ty::instance::Instance::resolve_drop_in_place
  46: <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_terminator
  47: rustc_mir::monomorphize::collector::collect_neighbours
  48: rustc_mir::monomorphize::collector::collect_items_rec
  49: rustc_mir::monomorphize::collector::collect_items_rec
  50: rustc_mir::monomorphize::collector::collect_items_rec
  51: rustc_mir::monomorphize::collector::collect_items_rec
  52: rustc_mir::monomorphize::collector::collect_items_rec
  53: rustc_mir::monomorphize::collector::collect_items_rec
  54: rustc_mir::monomorphize::collector::collect_items_rec
  55: rustc_mir::monomorphize::collector::collect_items_rec
  56: rustc_mir::monomorphize::collector::collect_items_rec
  57: rustc_mir::monomorphize::collector::collect_items_rec
  58: rustc_mir::monomorphize::collector::collect_items_rec
  59: rustc_mir::monomorphize::collector::collect_items_rec
  60: rustc_mir::monomorphize::collector::collect_items_rec
  61: rustc_mir::monomorphize::collector::collect_items_rec
  62: rustc_mir::monomorphize::collector::collect_items_rec
  63: rustc_mir::monomorphize::collector::collect_items_rec
  64: rustc_mir::monomorphize::collector::collect_items_rec
  65: rustc_session::utils::<impl rustc_session::session::Session>::time
  66: rustc_mir::monomorphize::collector::collect_crate_mono_items
  67: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  68: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  69: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  70: rustc_data_structures::stack::ensure_sufficient_stack
  71: rustc_query_system::query::plumbing::force_query_with_job
  72: rustc_query_system::query::plumbing::get_query_impl
  73: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items
  74: rustc_codegen_ssa::base::codegen_crate
  75: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  76: rustc_interface::queries::Queries::ongoing_codegen
  77: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  78: rustc_span::with_source_map
  79: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.1 (59eed8a2a 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `hyper::proto::h2::PipeToSendStream<server::EitherBody<http_body::combinators::UnsyncBoxBody<hyper::body::Bytes, tonic::Status>, hyper::Body>>: std::marker::Send`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [hyper::server::conn::spawn_all::NoopWatcher, hyper::server::conn::AddrStream, tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, hyper::common::exec::Exec], item_def_id: DefId(155:5740 ~ hyper[2c4b]::server::conn::spawn_all::Watcher::Future) } } }`
#2 [normalize_generic_arg_after_erasing_regions] normalizing `<hyper::server::conn::spawn_all::NoopWatcher as hyper::server::conn::spawn_all::Watcher<hyper::server::conn::AddrStream, tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, hyper::common::exec::Exec>>::Future`
#3 [needs_drop_raw] computing whether `hyper::server::conn::spawn_all::NewSvcTask<hyper::server::conn::AddrStream, tonic::codegen::Ready<std::result::Result<tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, std::convert::Infallible>>, tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, hyper::common::exec::Exec, hyper::server::conn::spawn_all::NoopWatcher>` needs drop
#4 [resolve_instance] resolving instance `std::ptr::drop_in_place::<hyper::server::conn::spawn_all::NewSvcTask<hyper::server::conn::AddrStream, tonic::codegen::Ready<std::result::Result<tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, std::convert::Infallible>>, tower::util::ServiceFn<[closure@prj/src/server/mod.rs:64:17: 88:18]>, hyper::common::exec::Exec, hyper::server::conn::spawn_all::NoopWatcher>>`
#5 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

</p>
</details>

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Can you still reproduce this on latest nightly? If yes, can you please provide detailed step by step instructions on how to reproduce please?

**Comment by reddevilmidzy** [comment]
Triage: no reproduce, If ICE occurs even in the latest nightly, please create a new issue. thank you.
