### ISSUE TITLE
ICE: panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_hir/src/definitions.rs:452:14

### ISSUE THREAD

**Issue by Alumin112** [rust-lang/rust#91585]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

```
alumin112@pop-os:~/Desktop/Rust/othello$ cargo run
   Compiling othello v0.1.0 (/home/alumin112/Desktop/Rust/othello)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `othello`
```

**Comment by fee1-dead** [comment]
Hello @Alumin112, could you please edit the issue description to include the source code that caused this error? Thanks.

**Comment by hellow554** [comment]
Looks like a dup of #90715

**Comment by cjgillot** [comment]
Closing as duplicate.
