### ISSUE TITLE
ICE: assertion failed: sentinel == STR_SENTINEL

### ISSUE THREAD

**Issue by wcampbell0x2a** [rust-lang/rust#91734]
This is while compiling my project: https://github.com/rsadsb/adsb_deku, on the lastest nightly. This looks to be an issue with `proc-macro-crate`, which is from the `deku` proc-macro crate.

### Meta

`rustc --version --verbose`:
```
✦2 ❯ rustc --version --verbose
rustc 1.59.0-nightly (0b42deacc 2021-12-09)
binary: rustc
commit-hash: 0b42deaccc2cbe17a68067aa5fdb76104369e1fd
commit-date: 2021-12-09
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

### Error output

```
✦2 ❯ cargo build
   Compiling syn v1.0.81
   Compiling tap v1.0.1
   Compiling funty v1.2.0
   Compiling radium v0.6.2
   Compiling wyz v0.4.0
   Compiling bitvec v0.22.3
   Compiling darling_core v0.13.0
   Compiling thiserror-impl v1.0.30
   Compiling darling_macro v0.13.0
   Compiling darling v0.13.0
   Compiling thiserror v1.0.30
   Compiling proc-macro-crate v1.1.0
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `proc-macro-crate`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
wcampbell@[] ../adsb_deku on  master [$?] is 📦 v0.4.0 via 🦀 v1.59.0-nightly
✦2 ❯ RUST_BACKTRACE=full cargo build
   Compiling proc-macro-crate v1.1.0
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0:     0x7f8d71cca35c - std::backtrace_rs::backtrace::libunwind::trace::hf7449935ead7573e
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f8d71cca35c - std::backtrace_rs::backtrace::trace_unsynchronized::h221aa2d88d72372a
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8d71cca35c - std::sys_common::backtrace::_print_fmt::h1c77e8983e1df895
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8d71cca35c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4ec41a9a6b0d22c
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f8d71d2737c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/core/src/fmt/mod.rs:1149:17
   5:     0x7f8d71cbaa65 - std::io::Write::write_fmt::haf74340a8cbeaa88
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/io/mod.rs:1660:15
   6:     0x7f8d71ccd520 - std::sys_common::backtrace::_print::h2d15cd157796a64a
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f8d71ccd520 - std::sys_common::backtrace::print::h52d286d22e2398eb
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f8d71ccd520 - std::panicking::default_hook::{{closure}}::h6da08fba6306daf2
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:211:50
   9:     0x7f8d71ccd0cb - std::panicking::default_hook::h266f67a22e76b11a
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:228:9
  10:     0x7f8d727f1291 - rustc_driver[feb513e6adc957d8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f8d71ccdd39 - std::panicking::rust_panic_with_hook::he55698a957f4fb6d
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:610:17
  12:     0x7f8d71ccd7c2 - std::panicking::begin_panic_handler::{{closure}}::h01f453c3ac181895
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:500:13
  13:     0x7f8d71cca804 - std::sys_common::backtrace::__rust_end_short_backtrace::h675d77c6e5a3926d
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x7f8d71ccd759 - rust_begin_unwind
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:498:5
  15:     0x7f8d71c91c21 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/core/src/panicking.rs:107:14
  16:     0x7f8d71c91b6d - core::panicking::panic::h50b51d19800453c0
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/core/src/panicking.rs:48:5
  17:     0x7f8d74259116 - <alloc[1954047e53701c4d]::string::String as rustc_serialize[b3e713358750c20b]::serialize::Decodable<rustc_metadata[b7dbc791ee3c9388]::rmeta::decoder::DecodeContext>>::decode
  18:     0x7f8d74d67a90 - <rustc_metadata[b7dbc791ee3c9388]::locator::CrateLocator>::extract_one
  19:     0x7f8d74d6727e - <rustc_metadata[b7dbc791ee3c9388]::locator::CrateLocator>::extract_lib
  20:     0x7f8d74d6689c - <rustc_metadata[b7dbc791ee3c9388]::locator::CrateLocator>::find_library_crate
  21:     0x7f8d74d65d37 - <rustc_metadata[b7dbc791ee3c9388]::locator::CrateLocator>::maybe_load_library_crate
  22:     0x7f8d7420c98d - <rustc_metadata[b7dbc791ee3c9388]::creader::CrateLoader>::load
  23:     0x7f8d74209ae5 - <rustc_metadata[b7dbc791ee3c9388]::creader::CrateLoader>::maybe_resolve_crate
  24:     0x7f8d74209f10 - <rustc_metadata[b7dbc791ee3c9388]::creader::CrateLoader>::maybe_resolve_crate
  25:     0x7f8d7344d0e3 - <rustc_metadata[b7dbc791ee3c9388]::creader::CrateLoader>::maybe_process_path_extern
  26:     0x7f8d73d6b5d8 - <rustc_resolve[ccbaf0437fbeefec]::Resolver>::extern_prelude_get
  27:     0x7f8d73d57268 - <rustc_resolve[ccbaf0437fbeefec]::Resolver>::early_resolve_ident_in_lexical_scope
  28:     0x7f8d73d67589 - <rustc_resolve[ccbaf0437fbeefec]::Resolver>::resolve_path_with_ribs
  29:     0x7f8d73d54896 - <rustc_resolve[ccbaf0437fbeefec]::Resolver>::resolve_macro_path
  30:     0x7f8d749be988 - <rustc_resolve[ccbaf0437fbeefec]::Resolver as rustc_expand[2c7572397f580867]::base::ResolverExpand>::resolve_derives
  31:     0x7f8d748c712d - <rustc_builtin_macros[3a3c657e84a01367]::derive::Expander as rustc_expand[2c7572397f580867]::base::MultiItemModifier>::expand
  32:     0x7f8d74283d04 - <rustc_expand[2c7572397f580867]::expand::MacroExpander>::fully_expand_fragment
  33:     0x7f8d74d9325a - <rustc_expand[2c7572397f580867]::expand::MacroExpander>::expand_crate
  34:     0x7f8d746c9787 - <rustc_session[2680299e10ec9d86]::session::Session>::time::<core[cc79c391059f8e46]::result::Result<rustc_ast[f63e3a251842e941]::ast::Crate, rustc_errors[248f3f311c690252]::ErrorReported>, rustc_interface[4c4b5644b43577f1]::passes::configure_and_expand::{closure#1}>
  35:     0x7f8d746add90 - rustc_interface[4c4b5644b43577f1]::passes::configure_and_expand
  36:     0x7f8d746b1f6f - <rustc_interface[4c4b5644b43577f1]::queries::Queries>::expansion
  37:     0x7f8d746856ec - <rustc_interface[4c4b5644b43577f1]::interface::Compiler>::enter::<rustc_driver[feb513e6adc957d8]::run_compiler::{closure#1}::{closure#2}, core[cc79c391059f8e46]::result::Result<core[cc79c391059f8e46]::option::Option<rustc_interface[4c4b5644b43577f1]::queries::Linker>, rustc_errors[248f3f311c690252]::ErrorReported>>  38:     0x7f8d7468214d - rustc_span[dda57b1885b40b9a]::with_source_map::<core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>, rustc_interface[4c4b5644b43577f1]::interface::create_compiler_and_run<core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>, rustc_driver[feb513e6adc957d8]::run_compiler::{closure#1}>::{closure#1}>
  39:     0x7f8d746867ef - <scoped_tls[3fea4c3dcac147b1]::ScopedKey<rustc_span[dda57b1885b40b9a]::SessionGlobals>>::set::<rustc_interface[4c4b5644b43577f1]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[4c4b5644b43577f1]::interface::run_compiler<core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>,
rustc_driver[feb513e6adc957d8]::run_compiler::{closure#1}>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>>::{closure#0}::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>>
  40:     0x7f8d74684995 - std[f24903a91e569aa2]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[4c4b5644b43577f1]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[4c4b5644b43577f1]::interface::run_compiler<core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>, rustc_driver[feb513e6adc957d8]::run_compiler::{closure#1}>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>>
  41:     0x7f8d746a4ffa - <<std[f24903a91e569aa2]::thread::Builder>::spawn_unchecked<rustc_interface[4c4b5644b43577f1]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[4c4b5644b43577f1]::interface::run_compiler<core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>, rustc_driver[feb513e6adc957d8]::run_compiler::{closure#1}>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>>::{closure#0}, core[cc79c391059f8e46]::result::Result<(), rustc_errors[248f3f311c690252]::ErrorReported>>::{closure#1} as core[cc79c391059f8e46]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7f8d71cd8e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4beb69a85f7fb16c
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/alloc/src/boxed.rs:1811:9
  43:     0x7f8d71cd8e23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hef865a799f44aaf2
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/alloc/src/boxed.rs:1811:9
  44:     0x7f8d71cd8e23 - std::sys::unix::thread::Thread::new::thread_start::hee0b2d4e2414fa96
                               at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/sys/unix/thread.rs:108:17
  45:     0x7f8d71be6259 - start_thread
  46:     0x7f8d71afb5e3 - __GI___clone
  47:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `proc-macro-crate`
```

</p>
</details>

**Comment by wcampbell0x2a** [comment]
Duplicate of: https://github.com/rust-lang/rust/issues/91689 and https://github.com/rust-lang/rust/issues/91663

This recommends `cargo clean` which fixed this issue.
