### ISSUE TITLE
ICE with doctests

### ISSUE THREAD

**Issue by abrassel** [rust-lang/rust#91773]
### Code

```Rust
    /// let mat: Matrix<usize> = Matrix::new(3, 6, 0..);
    ///
    /// let neighbors = mat.neighbors(0, 0);
    /// assert_eq!(neighbors.next().unwrap(), Neighbor {loc: (1,0), val: &6});
```

### Meta
`rustc --version --verbose`:
```
rustc 1.59.0-nightly (0b42deacc 2021-12-09)
binary: rustc
commit-hash: 0b42deaccc2cbe17a68067aa5fdb76104369e1fd
commit-date: 2021-12-09
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

### Error output

```
running 1 test
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/library/core/src/panicking.rs:48:5
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  12: <rustc_resolve::Resolver>::lookup_import_candidates::<&<rustc_resolve::late::LateResolutionVisitor>::smart_resolve_report_errors::{closure#1}>
  13: <rustc_resolve::late::LateResolutionVisitor>::smart_resolve_report_errors
  14: <rustc_resolve::late::LateResolutionVisitor>::smart_resolve_path_fragment::{closure#0}
  15: <rustc_resolve::late::LateResolutionVisitor>::smart_resolve_path_fragment
  16: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_ty
  17: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_local
  18: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_block
  19: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn
  20: rustc_ast::visit::walk_item::<rustc_resolve::late::LateResolutionVisitor>
  21: <rustc_resolve::late::LateResolutionVisitor>::resolve_item
  22: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_block
  23: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn
  24: rustc_ast::visit::walk_item::<rustc_resolve::late::LateResolutionVisitor>
  25: <rustc_resolve::late::LateResolutionVisitor>::resolve_item
  26: <rustc_resolve::Resolver>::late_resolve_crate
  27: <rustc_session::session::Session>::time::<(), <rustc_resolve::Resolver>::resolve_crate::{closure#0}>
  28: rustc_interface::passes::configure_and_expand
  29: <rustc_interface::queries::Queries>::expansion
  30: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  31: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  32: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-unkno```
<backtrace>
```wn-linux-gnu
```
<backtrace>
```
note: compiler flags: -C codegen-units=1 -C embed-bitcode=no --crate-type bin

query stack during panic:
end of query stack
Couldn't compile the test.test src/matrix.rs - matrix::Matrix<T>::neighbors (line 286) ... FAILED
```

Basically, doc tests seem unhappy

</p>
</details>

**Comment by matthiaskrgr** [comment]
dupicate of https://github.com/rust-lang/rust/issues/91663
