### ISSUE TITLE
runtime panic: 'entered unreachable code' with iter::Zip + iter::Rev over a custom DoubleEndedIterator

### ISSUE THREAD

**Issue by abreis** [rust-lang/rust#91944]
I have a custom `DoubleEndedIterator` that, when zipped to a plain slice iterator and reversed, triggers an `unreachable!()` in `iter::Zip::next_back()`.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=948145410c89b55f6a271b95e76155a2)

On its own, the custom iterator reports the right `len` (and the default `size_hint` of `(0, None)`), and seems to work correctly. When zipped to a slice iterator _but not reversed_ it also works well.

### Code

```Rust
fn main() {
    let data = [1.0, 2.0];
    let slice = &data[0..2];

    let slice_iter = slice.iter();
    let custom_iter = CustomSliceIterator::new(slice);

    for (_, _) in slice_iter.zip(custom_iter).rev() {} // panics
}

struct CustomSliceIterator<'s> {
    slice: &'s [f64],

    // The next row to access when walking forward.
    next_row: usize,
    // The next row to access when walking in reverse.
    next_back_row: isize,
}

impl<'s> CustomSliceIterator<'s> {
    pub fn new(slice: &'s [f64]) -> Self {
        Self {
            slice,
            next_row: 0,
            next_back_row: (slice.len() as isize - 1),
        }
    }
}

impl<'s> Iterator for CustomSliceIterator<'s> {
    type Item = f64;
    fn next(&mut self) -> Option<Self::Item> {
        // Can't go over the slice's end, or a possible reverse iteration.
        if (self.next_row < self.slice.len()) && (self.next_row as isize <= self.next_back_row) {
            let value = self.slice[self.next_row];
            self.next_row += 1;
            Some(value)
        } else {
            None
        }
    }
}

impl<'s> DoubleEndedIterator for CustomSliceIterator<'s> {
    fn next_back(&mut self) -> Option<Self::Item> {
        // Can't go over the slice's start, or a possible forward iteration.
        if (self.next_back_row >= 0) && (self.next_back_row >= self.next_row as isize) {
            let value = self.slice[self.next_back_row as usize];
            self.next_back_row -= 1;
            Some(value)
        } else {
            None
        }
    }
}

impl<'s> ExactSizeIterator for CustomSliceIterator<'s> {
    fn len(&self) -> usize {
        self.slice.len()
    }
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0
```
(also occurs in 2021-12-13 nightly)

### Error output

```
thread 'main' panicked at 'internal error: entered unreachable code', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/zip.rs:200:5
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'main' panicked at 'internal error: entered unreachable code', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/zip.rs:200:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: <core::iter::adapters::zip::Zip<A,B> as core::iter::adapters::zip::ZipImpl<A,B>>::next_back
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/zip.rs:185:22
   4: <core::iter::adapters::zip::Zip<A,B> as core::iter::traits::double_ended::DoubleEndedIterator>::next_back
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/zip.rs:110:9
   5: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/rev.rs:33:9
   6: playground::main
             at ./src/main.rs:29:19
   7: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
```

</p>
</details>

**Comment by scottmcm** [comment]
(Removed `ICE` as the compiler isn't panicking here; it's just a panic from the standard library at runtime.)

This looks to me like it's allowed behaviour, as the iterator is not upholding the `ExactSizeIterator` contract.  Specifically, it's not reporting a shorter `.len()` as it advances: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=fb171207dae6e3c36505ed1ed48e03ec>

```plain
[src/main.rs:8] custom_iter.len() = 2
[src/main.rs:9] custom_iter.next() = Some(
    1.0,
)
[src/main.rs:10] custom_iter.len() = 2
[src/main.rs:11] custom_iter.next() = Some(
    2.0,
)
[src/main.rs:12] custom_iter.len() = 2
[src/main.rs:13] custom_iter.next() = None
[src/main.rs:14] custom_iter.len() = 2
```

The library is not allowed to be *unsound* just because an iterator is misbehaving, but it doesn't have to do anything *useful* in that situation -- and thus panicking is completely allowed.

**Comment by abreis** [comment]
Thank you! I suspected something was wrong with my implementation, but I couldn't point to what exactly since the  iterator seemed to work correctly on its own.
