### ISSUE TITLE
broken MIR in DefId(0:15 ~ nocore[d905]::{impl#0}::add)

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#92157]
### Code

```Rust
#![feature(no_core)]
#![feature(lang_items)]

#![no_core]
#[cfg(target_os = "linux")]
#[link(name = "c")]
extern {}

#[lang = "start"]
fn start<T>(_main: fn() -> T, _argc: isize, _argv: *const *const u8) -> isize {
    40+2
}
pub fn main() { }

#[lang = "sized"]
pub trait Sized {}
#[lang = "copy"]
pub trait Copy {}

#[lang = "drop_in_place"]
#[allow(unconditional_recursion)]
pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
    drop_in_place(to_drop)
}

#[lang = "add"]
trait Add<RHS> {
    type Output;
    fn add(self, other: RHS) -> Self::Output;
}

impl Add<isize> for isize {
    type Output = isize;
    fn add(self, other: isize) -> isize {
        self + other
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (91a0600a5 2021-12-18) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: internal compiler error: broken MIR in DefId(0:15 ~ nocore[d905]::{impl#0}::add) (NoSolution): could not prove Binder(TraitPredicate(<isize as Copy>, polarity:Positive), [])
  |
  = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:319:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1188:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug

note: rustc 1.59.0-nightly (91a0600a5 2021-12-18) running on x86_64-unknown-linux-gnu
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_display::<&str>
   3: <rustc_errors::HandlerInner>::flush_delayed
   4: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   6: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   7: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   8: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
   9: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by kpp** [comment]
A "fix" for that code is to add `impl Copy for isize {}` however I don't want to get an ICE but a nice error.

**Comment by bjorn3** [comment]
The error comes from https://github.com/rust-lang/rust/blob/8ad3c1dd1d47f9ce7dfdf4a14c70c67e1790b0f5/compiler/rustc_borrowck/src/type_check/mod.rs#L575-L590 I think. If you weren't using `#![no_core]` hitting this case would be a genuine bug in rustc. Turning it from an ICE into a nice error would require special casing integer types to not ICE here. In general you should expect to see internal compiler errors when you mess up with `#![no_core]`. In some cases it is feasable to give nice errors but I think this is not such a case.

**Comment by kpp** [comment]
Thanks! You may close if you think there is nothing you can do.

**Comment by inquisitivecrystal** [comment]
> The error comes from
> 
> https://github.com/rust-lang/rust/blob/8ad3c1dd1d47f9ce7dfdf4a14c70c67e1790b0f5/compiler/rustc_borrowck/src/type_check/mod.rs#L575-L590
> 
> I think. If you weren't using `#![no_core]` hitting this case would be a genuine bug in rustc. Turning it from an ICE into a nice error would require special casing integer types to not ICE here. In general you should expect to see internal compiler errors when you mess up with `#![no_core]`. In some cases it is feasible to give nice errors but I think this is not such a case.

I am by no means familiar with the relevant code, but this would seem more like a basis for making this a `P-low` than closing it entirely. As in, it would be nice if there was a way to fix this, but we don't know what it is and it's not really a priority.

**Comment by JohnTitor** [comment]
Triage: Fixed since nightly-2023-01-04, marking as `E-needs-test`.

**Comment by clubby789** [comment]
Closing per https://github.com/rust-lang/rust/pull/150821#issuecomment-3725925251
