### ISSUE TITLE
incremental compilation error with explicit_predicates_of, item_children

### ISSUE THREAD

**Issue by noahols** [rust-lang/rust#92236]
This error is related to #84970.
This error is caused by running cargo check or cargo doc with an incremental cache.
I believe the cache is from a previous rust version. (Currently using 1.55.0)
Cargo build works fine. 

### Code
I don't believe I can create a minimal verifiable example because this bug relies on the incremental cache. Changing anything causes recompilation and avoids the error. I can provide all code and target directory if necessary.

### Meta
Switching to nightly causes recompilation and avoids the error.

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: x86_64-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```

### Error output
This is one instance of the error. The same error happens on multiple crates in the project.
```
error: internal compiler error: encountered incremental compilation error with explicit_predicates_of(nox_util[8b2e]::serde::DeserializeFallible)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p nox_pak` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

error: internal compiler error: encountered incremental compilation error with item_children(nox_util[8b2e])
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p nox_pak` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for item_children(nox_util[8b2e]): [Export { ident: third_party#0, res: Def(Mod, DefId(19:3 ~ nox_util[8b2e]::third_party)), span: /home/user/mount/LARGE/0_repos/nox/nox_util/src/lib.rs:1:1: 8:2 (#0), vis: Public }, Export { ident: cli#0, res: Def(Mod, DefId(19:22 ~ nox_util[8b2e]::cli)), span: /home/user/mount/LARGE/0_repos/nox/nox_util/src/lib.rs:10:1: 10:13 (#0), vis: Public }, Export { ident: error#0, res: Def(Mod, DefId(19:41 ~ nox_util[8b2e]::error)), span: /home/user/mount/LARGE/0_repos/nox/nox_util/src/lib.rs:11:1: 11:15 (#0), vis: Public }, Export { ident: path#0, res: Def(Mod, DefId(19:83 ~ nox_util[8b2e]::path)), span: /home/user/mount/LARGE/0_repos/nox/nox_util/src/lib.rs:12:1: 12:14 (#0), vis: Public }, Export { ident: serde#0, res: Def(Mod, DefId(19:90 ~ nox_util[8b2e]::serde)), span: /home/user/mount/LARGE/0_repos/nox/nox_util/src/lib.rs:13:1: 13:15 (#0), vis: Public }, Export { ident: read#0, res: Def(Mod, DefId(19:229 ~ nox_util[8b2e]::read)), span: /home/user/mount/LARGE/0_repos/nox/nox_util/src/lib.rs:15:1: 29:2 (#0), vis: Public }]', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/compiler/rustc_query_system/src/query/plumbing.rs:624:9
```
Backtrace removed
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
error: could not compile `nox_pak` due to 2 previous errors

Caused by:
  process didn't exit successfully: `rustc --crate-name nox_pak --edition=2018 nox_pak/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=313425dafc1f9547 -C extra-filename=-313425dafc1f9547 --out-dir /temp/nox/target/debug/deps -C incremental=/temp/nox/target/debug/incremental -L dependency=/temp/nox/target/debug/deps --extern nox_util=/temp/nox/target/debug/deps/libnox_util-f7d7935915fb9cac.rmeta --extern rand=/temp/nox/target/debug/deps/librand-b403519d74669dcc.rmeta` (signal: 4, SIGILL: illegal instruction)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7fb331887b40 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fb331887b40 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb331887b40 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fb331887b40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fb3318f56bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x7fb3318792d5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x7fb33188b89b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fb33188b89b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fb33188b89b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x7fb33188b371 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x7fb332064251 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h6de3be617154114e
  11:     0x7fb33188c0c9 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
  12:     0x7fb33188bb87 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  13:     0x7fb33188803c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fb33188bae9 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  15:     0x7fb331854aab - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  16:     0x7fb33289edac - rustc_query_system::query::plumbing::incremental_verify_ich::h89c7bc97eed12275
  17:     0x7fb3328c5e19 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h17ce6c2f5a3ebe5a
  18:     0x7fb33370b9eb - rustc_query_system::query::plumbing::get_query_impl::h9f22804c295d100b
  19:     0x7fb3337662be - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::item_children::h22923e62dabe3f64
  20:     0x7fb333825c70 - core::ops::function::FnOnce::call_once::hda03ecaa240882bc
  21:     0x7fb332a143d4 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hc735697a98b0a0ad
  22:     0x7fb3328c80f7 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h34ac0b040596c94d
  23:     0x7fb332aaf56f - rustc_data_structures::stack::ensure_sufficient_stack::h2da0a3900db5d3c1
  24:     0x7fb334020712 - rustc_query_system::query::plumbing::get_query_impl::h905320e734bbede9
  25:     0x7fb3340dc7d0 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::visible_parent_map::h1be3ca3e7f97e91c
  26:     0x7fb333ab778d - rustc_middle::ty::print::pretty::PrettyPrinter::try_print_visible_def_path_recur::h9346a891f65d4664
  27:     0x7fb333abe68c - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::he58512f847dc6f43
  28:     0x7fb333abeb9c - <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path::he58512f847dc6f43
  29:     0x7fb33443a1c4 - <rustc_middle::ty::print::pretty::TraitRefPrintOnlyTraitPath as core::fmt::Display>::fmt::h3f10f9d01902189c
  30:     0x7fb3318f56bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
  31:     0x7fb332fad2ac - rustc_middle::ty::print::pretty::<impl rustc_middle::ty::print::Print<P> for rustc_middle::ty::sty::TraitRef>::print::hf240106915203d80
  32:     0x7fb332fadea8 - rustc_middle::ty::print::pretty::<impl core::fmt::Display for rustc_middle::ty::sty::TraitRef>::fmt::h16f30f877128c224
  33:     0x7fb332eda64d - std::thread::local::LocalKey<T>::with::h808dba66914be2d7
  34:     0x7fb332fa8613 - rustc_middle::ty::structural_impls::<impl core::fmt::Debug for rustc_middle::ty::sty::TraitRef>::fmt::hf4d43679b7175e19
  35:     0x7fb3318f56bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
  36:     0x7fb3318f6884 - core::fmt::Formatter::write_fmt::hb9a2da07a5224baf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1561:9
  37:     0x7fb332f8250b - rustc_middle::ty::structural_impls::<impl core::fmt::Debug for rustc_middle::ty::PredicateKind>::fmt::h660c1b65ec6fbe35
  38:     0x7fb3318f27cf - core::fmt::builders::DebugTuple::field::{{closure}}::h01735522e2823ac2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:335:17
  39:     0x7fb3318f27cf - core::result::Result<T,E>::and_then::hb3018aa2c0e9faf9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:948:22
  40:     0x7fb3318f27cf - core::fmt::builders::DebugTuple::field::h9f4e7e2b00332384
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:322:23
  41:     0x7fb332faedba - <rustc_middle::ty::sty::Binder<T> as core::fmt::Debug>::fmt::he6c301c487ee298a
  42:     0x7fb3318f56bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
  43:     0x7fb3318f6884 - core::fmt::Formatter::write_fmt::hb9a2da07a5224baf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1561:9
  44:     0x7fb332f73c3a - <&T as core::fmt::Debug>::fmt::h52cda2292e0b69f0
  45:     0x7fb3318f27cf - core::fmt::builders::DebugTuple::field::{{closure}}::h01735522e2823ac2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:335:17
  46:     0x7fb3318f27cf - core::result::Result<T,E>::and_then::hb3018aa2c0e9faf9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:948:22
  47:     0x7fb3318f27cf - core::fmt::builders::DebugTuple::field::h9f4e7e2b00332384
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:322:23
  48:     0x7fb332f737ea - <&T as core::fmt::Debug>::fmt::h0a337e6d2bed45a2
  49:     0x7fb3318f296c - core::fmt::builders::DebugInner::entry::{{closure}}::h9a3dc54fa8fd789f
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:407:17
  50:     0x7fb3318f296c - core::result::Result<T,E>::and_then::h5c9edf223c3390fb
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:948:22
  51:     0x7fb3318f296c - core::fmt::builders::DebugInner::entry::h073d76f8b53cb02b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:393:23
  52:     0x7fb3318f2a39 - core::fmt::builders::DebugSet::entry::hd94672b699f4779c
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:482:9
  53:     0x7fb332fb47bd - core::fmt::builders::DebugList::entries::hb9b29df623465c18
  54:     0x7fb332f74188 - <&T as core::fmt::Debug>::fmt::hb7bafdc08eed8ae7
  55:     0x7fb3318f253d - core::fmt::builders::DebugStruct::field::{{closure}}::h4f234df4a18180a6
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:154:17
  56:     0x7fb3318f253d - core::result::Result<T,E>::and_then::h33aafdeaaa2cc4ed
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:948:22
  57:     0x7fb3318f253d - core::fmt::builders::DebugStruct::field::h22bd52f7aaecfb29
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/builders.rs:137:23
  58:     0x7fb332ee64fe - <rustc_middle::ty::generics::GenericPredicates as core::fmt::Debug>::fmt::h2fc788629191fdca
  59:     0x7fb3318f56bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
  60:     0x7fb33188bcff - core::fmt::Write::write_fmt::he5e35fc5fb035c2e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:187:9
  61:     0x7fb33188bcff - std::panicking::begin_panic_handler::PanicPayload::fill::{{closure}}::h69a0ee9c71c73967
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:481:22
  62:     0x7fb33188bcff - core::option::Option<T>::get_or_insert_with::h760ac51afc58f6f1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:1270:26
  63:     0x7fb33188bcff - std::panicking::begin_panic_handler::PanicPayload::fill::h233eb7bbd452e035
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:479:13
  64:     0x7fb33188bcff - <std::panicking::begin_panic_handler::PanicPayload as core::panic::BoxMeUp>::get::h59f507d2b3ace374
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:497:13
  65:     0x7fb33188c0b4 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:625:34
  66:     0x7fb33188bb87 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  67:     0x7fb33188803c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  68:     0x7fb33188bae9 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  69:     0x7fb331854aab - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  70:     0x7fb33407055c - rustc_query_system::query::plumbing::incremental_verify_ich::h8114dcdd0d1eecfc
  71:     0x7fb33372d548 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h99e292ca56b95e3b
  72:     0x7fb3336f7e4c - rustc_query_system::query::plumbing::get_query_impl::h507d30bd78a00584
  73:     0x7fb333763754 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::explicit_predicates_of::hca81bd229d82f95c
  74:     0x7fb33335562b - rustc_typeck::collect::predicates_defined_on::h7b664dd703058063
  75:     0x7fb33412d66b - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h04af2f1a52c0788c
  76:     0x7fb33372d51e - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h99e292ca56b95e3b
  77:     0x7fb3336f7e4c - rustc_query_system::query::plumbing::get_query_impl::h507d30bd78a00584
  78:     0x7fb333763654 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_defined_on::h362f778dca9038ac
  79:     0x7fb333355cb2 - rustc_typeck::collect::predicates_of::h57989296d047a466
  80:     0x7fb333768323 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h926d8e504ea18458
  81:     0x7fb333720c19 - rustc_query_system::query::plumbing::force_query_with_job::h624f643cf77a59db
  82:     0x7fb334041fc0 - rustc_query_system::query::plumbing::force_query_impl::hc61ee25ec9b91263
  83:     0x7fb332830cd5 - rustc_query_system::query::plumbing::force_query::h0ba5252d683b7344
  84:     0x7fb333768f5d - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::hebe559aa58bf1816
  85:     0x7fb333768d54 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read::h75827515110c1695
  86:     0x7fb333720a48 - rustc_query_system::query::plumbing::ensure_must_run::h8ed4c3a347dd4e11
  87:     0x7fb333765a7f - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_impl_item_well_formed::h83679a55c86065e8
  88:     0x7fb3332974cc - <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor as rustc_hir::intravisit::Visitor>::visit_impl_item::hf7eeb034f928b485
  89:     0x7fb3333381e4 - rustc_data_structures::sync::par_for_each_in::he35215503a9ebb41
  90:     0x7fb333db8ac8 - rustc_hir::hir::Crate::par_visit_all_item_likes::h684c805878a71907
  91:     0x7fb333daec40 - rustc_session::session::Session::track_errors::h3b9f33c289d4766f
  92:     0x7fb333da33d3 - rustc_typeck::check_crate::h4575c24b66669750
  93:     0x7fb333b8b3ef - rustc_interface::passes::analysis::hf91740f5893e2dd6
  94:     0x7fb332a16363 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::he5722ca07eceeed2
  95:     0x7fb3329dfa47 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h96f2846afe4c135b
  96:     0x7fb3329e9a19 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task::h61fc0f5b6132f6c1
  97:     0x7fb332aad0ce - rustc_data_structures::stack::ensure_sufficient_stack::h112bd9a1e5f14b8b
  98:     0x7fb33287382d - rustc_query_system::query::plumbing::force_query_with_job::hbbccc62bba484e69
  99:     0x7fb33402e786 - rustc_query_system::query::plumbing::get_query_impl::hc496b7da6ca5195d
 100:     0x7fb3340d77ed - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h8d17f3fde386d772
 101:     0x7fb333b5fa68 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h2007d30ef68567cb
 102:     0x7fb333b4f44c - rustc_span::with_source_map::hc5adfd8eb2dd5236
 103:     0x7fb333b60c8a - rustc_interface::interface::create_compiler_and_run::h976ed8e22b4f89b8
 104:     0x7fb333b53e89 - scoped_tls::ScopedKey<T>::set::h4a2887b4d5b96c48
 105:     0x7fb333b509aa - std::sys_common::backtrace::__rust_begin_short_backtrace::h220030c0c75c9d89
 106:     0x7fb333b4fdf5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd62830e2741d6b63
 107:     0x7fb331898657 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
 108:     0x7fb331898657 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
 109:     0x7fb331898657 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
 110:     0x7fb3317bc450 - start_thread
 111:     0x7fb3316cad53 - clone
 112:                0x0 - <unknown>
```

</p>
</details>

**Comment by Aaron1011** [comment]
I believe that this should be fixed in the latest versions of the compiler.

**Comment by noahols** [comment]
You're right. Thanks and sorry for the mis-report.

**Comment by Aaron1011** [comment]
@noahols Don't worry - it's always fine to open an issue for incremental compilation bugs, since it can be very difficult to tell if a new version fixes it or not.
