### ISSUE TITLE
Higher-Rank Trait Bounds: incorrect (or misleading) diagnostic

### ISSUE THREAD

**Issue by BraulioVM** [rust-lang/rust#92281]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f04b02c95cd4647878759f1a4f0abf30

```rust
pub struct Value {
    a: String,
}

pub struct Borrowed<'a> {
    b: &'a str,
}

pub fn parse(a: &Value) -> Borrowed<'_> {
    Borrowed { b: &a.a }
}

pub fn not<T>(predicate: impl for<'a> Fn(&'a T) -> bool) -> impl for<'a> Fn(&'a T) -> bool {
    move |t: &T| !predicate(t)
}

/// Transform a predicate on `Borrowed`s into a predicate for `Value`s
pub fn borrowed(predicate: impl for<'a> Fn(&Borrowed<'_>) -> bool) -> impl Fn(&Value) -> bool {
    move |t: &Value| {
        let parsed = parse(t);
        predicate(&parsed)
    }
}

pub fn is_borrowed_cool() -> impl for<'a> Fn(&Borrowed<'a>) -> bool {
    |b| true
}

pub fn compose_predicates() {
    let a = not(is_borrowed_cool());
    let b = borrowed(is_borrowed_cool());
    let c = borrowed(not(is_borrowed_cool()));
}
```

The current output is:

```
error[E0308]: mismatched types
  --> src/lib.rs:34:13
   |
13 | pub fn not<T>(predicate: impl for<'a> Fn(&'a T) -> bool) -> impl for<'a> Fn(&'a T) -> bool {
   |                                                             ------------------------------
   |                                                             |
   |                                                             one of the expected opaque types
   |                                                             one of the found opaque types
...
25 | pub fn is_borrowed_cool() -> impl for<'a> Fn(&Borrowed<'a>) -> bool {
   |                              --------------------------------------
   |                              |
   |                              one of the expected opaque types
   |                              one of the found opaque types
...
34 |     let c = borrowed(not(is_borrowed_cool()));
   |             ^^^^^^^^ lifetime mismatch
   |
   = note: expected associated type `<impl for<'a> Fn<(&'a Borrowed<'_>,)> as FnOnce<(&Borrowed<'_>,)>>::Output`
              found associated type `<impl for<'a> Fn<(&'a Borrowed<'_>,)> as FnOnce<(&Borrowed<'_>,)>>::Output`
note: the lifetime requirement is introduced here
  --> src/lib.rs:18:62
   |
18 | pub fn borrowed(predicate: impl for<'a> Fn(&Borrowed<'_>) -> bool) -> impl Fn(&Value) -> bool {
   |                                                              ^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

Note the following lines specially:

```
   = note: expected associated type `<impl for<'a> Fn<(&'a Borrowed<'_>,)> as FnOnce<(&Borrowed<'_>,)>>::Output`
              found associated type `<impl for<'a> Fn<(&'a Borrowed<'_>,)> as FnOnce<(&Borrowed<'_>,)>>::Output`
```

where the expected and the found types are the same. I'm not sure if this is a compiler bug because I'm not very familiar
with HRTBs, but the diagnostic could be better. I can't really propose the better diagnostic because I don't know what's wrong
with my code.

The error is the same on nightly and beta.

**Comment by smmalis37** [comment]
This looks like the kind of thing https://github.com/rust-lang/rust/pull/85499 was addressing?

**Comment by BraulioVM** [comment]
For what is worth, this very same code causes an internal compiler error when using -Zchalk.

https://godbolt.org/z/vsaTs4Kcb

```
thread 'rustc' panicked at 'index out of bounds: the len is 2 but the index is 2', /cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.75.0/src/lib.rs:2748:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (475b00aa4 2021-12-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z chalk -C debuginfo=1 -C linker=/opt/compiler-explorer/gcc-11.1.0/bin/gcc --crate-type bin

query stack during panic:
#0 [evaluate_goal] evaluating trait selection obligation `environment: [Binder(TypeWellFormedFromEnv(impl for<'a> Fn(&Borrowed<'_>) -> bool), []), Binder(ProjectionPredicate(ProjectionTy { substs: [impl for<'a> Fn(&Borrowed<'_>) -> bool, (&Borrowed<'_>,)], item_def_id: DefId(2:3268 ~ core[5910]::ops::function::FnOnce::Output) }, bool), [Region(BrNamed(DefId(0:16 ~ example[a33f]::borrowed::{opaque#0}::'a), 'a)), Region(BrAnon(0)), Region(BrAnon(1))]), Binder(TraitPredicate(<impl for<'a> Fn(&Borrowed<'_>) -> bool as core::ops::function::Fn<(&Borrowed<'_>,)>>, polarity:Positive), [Region(BrNamed(DefId(0:16 ~ example[a33f]::borrowed::{opaque#0}::'a), 'a)), Region(BrAnon(0)), Region(BrAnon(1))]), Binder(TraitPredicate(<impl for<'a> Fn(&Borrowed<'_>) -> bool as core::ops::function::FnMut<(&Borrowed<'_>,)>>, polarity:Positive), [Region(BrNamed(DefId(0:16 ~ example[a33f]::borrowed::{opaque#0}::'a), 'a)), Region(BrAnon(0)), Region(BrAnon(1))]), Binder(TraitPredicate(<impl for<'a> Fn(&Borrowed<'_>) -> bool as core::ops::function::FnOnce<(&Borrowed<'_>,)>>, polarity:Positive), [Region(BrNamed(DefId(0:16 ~ example[a33f]::borrowed::{opaque#0}::'a), 'a)), Region(BrAnon(0)), Region(BrAnon(1))]), Binder(TraitPredicate(<impl for<'a> Fn(&Borrowed<'_>) -> bool as core::marker::Sized>, polarity:Positive), [])], goal: impl for<'a> Fn(&Borrowed<'_>) -> bool: core::marker::Sized`
#1 [check_item_well_formed] checking that `borrowed` is well-formed
end of query stack
thread 'rustc' panicked at 'explicit panic', compiler/rustc_traits/src/chalk/lowering.rs:906:30

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (475b00aa4 2021-12-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z chalk -C debuginfo=1 -C linker=/opt/compiler-explorer/gcc-11.1.0/bin/gcc --crate-type bin

query stack during panic:
#0 [evaluate_goal] evaluating trait selection obligation `environment: [], goal: impl Fn(&Borrowed<'a>)-> bool well-formed`
#1 [check_item_well_formed] checking that `is_borrowed_cool` is well-formed
end of query stack
Compiler returned: 101
```

**Comment by RodBurman** [comment]
This problem, at least:
```
   = note: expected associated type `<impl for<'a> Fn(&'a Borrowed<'_>) -> bool as FnOnce<(&Borrowed<'_>,)>>::Output`
              found associated type `<impl for<'a> Fn(&'a Borrowed<'_>) -> bool as FnOnce<(&Borrowed<'_>,)>>::Output`
```

Where the compiler seems to be looking and finding the same item yet that item does not satisfy its requirements persists.
Since the -Zchalk switch is no longer accepted the internal compiler error is no longer applicable.

<details><summary>The compiler version:</summary>

```
% rustc -vV             
rustc 1.97.1 (8bab26f4f 2026-07-14)
binary: rustc
commit-hash: 8bab26f4f68e0e26f0bb7960be334d5b520ea452
commit-date: 2026-07-14
host: aarch64-apple-darwin
release: 1.97.1
LLVM version: 22.1.6
```
</details>
<details><summary>Now produces:</summary>

```
% rustc --crate-type=lib --allow unused-variables src/lib.rs 
error: implementation of `Fn` is not general enough
  --> src/lib.rs:34:13
   |
34 |     let c = borrowed(not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Fn` is not general enough
   |
   = note: `impl for<'a> Fn(&'a Borrowed<'2>) -> bool` must implement `Fn<(&Borrowed<'1>,)>`, for any lifetime `'1`...
   = note: ...but it actually implements `Fn<(&Borrowed<'2>,)>`, for some specific lifetime `'2`

error[E0308]: mismatched types
  --> src/lib.rs:34:13
   |
34 |     let c = borrowed(not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected associated type `<impl for<'a> Fn(&'a Borrowed<'_>) -> bool as FnOnce<(&Borrowed<'_>,)>>::Output`
              found associated type `<impl for<'a> Fn(&'a Borrowed<'_>) -> bool as FnOnce<(&Borrowed<'_>,)>>::Output`
note: the lifetime requirement is introduced here
  --> src/lib.rs:18:62
   |
18 | pub fn borrowed(predicate: impl for<'a> Fn(&Borrowed<'_>) -> bool) -> impl Fn(&Value) -> bool {
   |                                                              ^^^^

error: implementation of `Fn` is not general enough
  --> src/lib.rs:34:13
   |
18 | pub fn borrowed(predicate: impl for<'a> Fn(&Borrowed<'_>) -> bool) -> impl Fn(&Value) -> bool {
   | ---------------------------------------------------------------------------------------------
   | |                               |
   | |                               doesn't satisfy where-clause
   | due to a where-clause on `borrowed`...
...
34 |     let c = borrowed(not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: ...`impl for<'a> Fn(&'a Borrowed<'2>) -> bool` must implement `Fn<(&Borrowed<'1>,)>`, for any lifetime `'1`...
   = note: ...but it actually implements `Fn<(&Borrowed<'2>,)>`, for some specific lifetime `'2`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
```

</details>
From the example code.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=931d6dc8d14a714c2e5d1f8ae4fc0d76):

```
error[E0277]: expected an `Fn(&Borrowed<'_>)` closure, found `impl for<'a> Fn(&'a Borrowed<'_>) -> bool`
  --> src/lib.rs:34:22
   |
34 |     let c = borrowed(not(is_borrowed_cool()));
   |             -------- ^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'a, 'b> Fn(&'a Borrowed<'b>)` is not implemented for `impl for<'a> Fn(&'a Borrowed<'_>) -> bool`
   |             |
   |             required by a bound introduced by this call
   |
   = note: the trait bound `for<'a, 'b> impl for<'a> Fn(&'a Borrowed<'_>) -> bool: Fn(&'a Borrowed<'b>)` is not satisfied
note: required by a bound in `borrowed`
  --> src/lib.rs:18:33
   |
18 | pub fn borrowed(predicate: impl for<'a> Fn(&Borrowed<'_>) -> bool) -> impl Fn(&Value) -> bool {
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `borrowed`
help: consider borrowing here
   |
34 |     let c = borrowed(&not(is_borrowed_cool()));
   |                      +

error[E0277]: expected an `Fn(&Borrowed<'_>)` closure, found `impl for<'a> Fn(&'a Borrowed<'_>) -> bool`
  --> src/lib.rs:34:13
   |
34 |     let c = borrowed(not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an `Fn(&Borrowed<'_>)` closure, found `impl for<'a> Fn(&'a Borrowed<'_>) -> bool`
   |
   = help: the trait `for<'a, 'b> Fn(&'a Borrowed<'b>)` is not implemented for `impl for<'a> Fn(&'a Borrowed<'_>) -> bool`
   = note: expected a closure with signature `for<'a, 'b> fn(&'a Borrowed<'b>)`
              found a closure with signature `fn(&Borrowed<'_>)`
note: required by a bound in `borrowed`
  --> src/lib.rs:18:33
   |
18 | pub fn borrowed(predicate: impl for<'a> Fn(&Borrowed<'_>) -> bool) -> impl Fn(&Value) -> bool {
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `borrowed`
```

[If we follow the borrowing suggestion](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=c2544cf65836c91456fe8fc04ed5191d):

```
error: higher-ranked lifetime error
  --> src/lib.rs:34:13
   |
34 |     let c = borrowed(&not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: could not prove `for<'a, 'b> &impl for<'a> Fn(&'a Borrowed<'_>) -> bool: Fn(&'a Borrowed<'b>)`

error: higher-ranked lifetime error
  --> src/lib.rs:34:13
   |
34 |     let c = borrowed(&not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: could not prove `for<'a, 'b> <&impl for<'a> Fn(&'a Borrowed<'_>) -> bool as FnOnce<(&'a Borrowed<'b>,)>>::Output == bool`

error: higher-ranked lifetime error
  --> src/lib.rs:34:13
   |
34 |     let c = borrowed(&not(is_borrowed_cool()));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: could not prove `impl for<'a> Fn(&'a Value) -> bool well-formed`

error[E0716]: temporary value dropped while borrowed
  --> src/lib.rs:34:23
   |
34 |     let c = borrowed(&not(is_borrowed_cool()));
   |                       ^^^^^^^^^^^^^^^^^^^^^^^ - temporary value is freed at the end of this statement
   |                       |
   |                       creates a temporary value which is freed while still in use
35 | }
   | - borrow might be used here, when `c` is dropped and runs the destructor for type `impl for<'a> Fn(&'a Value) -> bool`
   |
help: consider using a `let` binding to create a longer lived value
   |
34 ~     let binding = not(is_borrowed_cool());
35 ~     let c = borrowed(&binding);
   |
```
