### ISSUE TITLE
Const Generic Exprressions

### ISSUE THREAD

**Issue by geoeo** [rust-lang/rust#92302]
### Code

I dont have a minimal example sorry. The example I was trying to run was https://github.com/geoeo/Vision/blob/inverse_depth/examples/image_processing/ba_3dv.rs
The files I made using nightly are here: https://github.com/geoeo/Vision/tree/inverse_depth/src/sfm

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (efec54529 2021-12-04)
binary: rustc
commit-hash: efec545293b9263be9edfb283a7aa66350b3acbf
commit-date: 2021-12-04
host: x86_64-pc-windows-msvc
release: 1.59.0-nightly
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'Unknown variable: 0', compiler\rustc_ty_utils\src\instance.rs:46:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (efec54529 2021-12-04) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'substs of instance DefId(47:3448 ~ vision[dd25]::sfm::landmark::Landmark::LANDMARK_PARAM_SIZE) not normalized for codegen: [^1]', compiler\rustc_middle\src\ty\instance.rs:303:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ff8681c9c5f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc2aeea11bb07072e
   1:     0x7ff8681f44fa - core::fmt::write::h8a2c40ddb66ccc71
   2:     0x7ff8681bb9e8 - <std::io::IoSlice as core::fmt::Debug>::fmt::hb0f7b7ec1545d2d8
   3:     0x7ff8681cd1a6 - std::panicking::take_hook::hb82d3fa273181deb
   4:     0x7ff8681ccc8c - std::panicking::take_hook::hb82d3fa273181deb
   5:     0x7ff856eca7f5 - <rustc_lint[d5b77cca1c855499]::BuiltinCombinedLateLintPass as rustc_lint[d5b77cca1c855499]::passes::LateLintPass>::check_crate_post
   6:     0x7ff8681cdab9 - std::panicking::rust_panic_with_hook::h8846bbc0e1c27093
   7:     0x7ff8681cd55b - rust_begin_unwind
   8:     0x7ff8681ca587 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc2aeea11bb07072e
   9:     0x7ff8681cd4b9 - rust_begin_unwind
  10:     0x7ff868228310 - core::panicking::panic_fmt::hc1b1ca620e7a2c9f
  11:     0x7ff85b47258b - <rustc_middle[63aa33dd3295c16a]::ty::instance::Instance>::new
  12:     0x7ff85a5b5468 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  13:     0x7ff85a81b000 - <alloc[bce774710940cf57]::vec::Vec<u8> as rustc_serialize[a7a60dfef5d3d355]::serialize::Decodable<rustc_query_impl[66d4c656b011426]::on_disk_cache::CacheDecoder>>::decode
  14:     0x7ff85a3d1dd1 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  15:     0x7ff85a62eaf4 - <rustc_query_impl[66d4c656b011426]::Queries>::new
  16:     0x7ff85a7ac51e - <&rustc_index[2bfb8672995629f8]::vec::IndexVec<rustc_middle[63aa33dd3295c16a]::mir::Promoted, rustc_middle[63aa33dd3295c16a]::mir::Body> as rustc_serialize[a7a60dfef5d3d355]::serialize::Decodable<rustc_query_impl[66d4c656b011426]::on_disk_cache::CacheDecoder>>::decode
  17:     0x7ff8570f92d7 - rustc_interface[1c6a2488f78f6a24]::interface::try_print_query_stack
  18:     0x7ff856ed6775 - rustc_driver[dea966e5e189d317]::report_ice
  19:     0x7ff8681cdab9 - std::panicking::rust_panic_with_hook::h8846bbc0e1c27093
  20:     0x7ff8681cd55b - rust_begin_unwind
  21:     0x7ff8681ca587 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc2aeea11bb07072e
  22:     0x7ff8681cd4b9 - rust_begin_unwind
  23:     0x7ff868228310 - core::panicking::panic_fmt::hc1b1ca620e7a2c9f
  24:     0x7ff859a9d52a - rustc_ty_utils[443b7b4dcd005d03]::instance::provide
  25:     0x7ff859a9a9e8 - rustc_ty_utils[443b7b4dcd005d03]::instance::provide
  26:     0x7ff85a6561ec - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  27:     0x7ff85a700605 - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  28:     0x7ff85a5efd15 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  29:     0x7ff85a555da7 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  30:     0x7ff85a630de6 - <rustc_query_impl[66d4c656b011426]::Queries as rustc_middle[63aa33dd3295c16a]::ty::query::QueryEngine>::try_mark_green
  31:     0x7ff85b477d4a - <rustc_middle[63aa33dd3295c16a]::ty::instance::Instance>::resolve_opt_const_arg
  32:     0x7ff85b3ea33b - <rustc_middle[63aa33dd3295c16a]::ty::context::TyCtxt>::const_eval_resolve
  33:     0x7ff85b1a0250 - <rustc_trait_selection[1c7115e003ec50b7]::traits::VtblSegment as core[3b5640218fb446b]::fmt::Debug>::fmt
  34:     0x7ff85b1ad4b8 - <rustc_trait_selection[1c7115e003ec50b7]::traits::query::normalize::QueryNormalizer as rustc_middle[63aa33dd3295c16a]::ty::fold::FallibleTypeFolder>::try_fold_const
  35:     0x7ff85b1ad58a - <rustc_trait_selection[1c7115e003ec50b7]::traits::query::normalize::QueryNormalizer as rustc_middle[63aa33dd3295c16a]::ty::fold::FallibleTypeFolder>::try_fold_mir_const
  36:     0x7ff85a1cbbda - <&chalk_ir[63366a7a24aa785e]::GenericArg<rustc_middle[63aa33dd3295c16a]::traits::chalk::RustInterner> as rustc_traits[dffea30f4dbc27f6]::chalk::lowering::LowerInto<rustc_middle[63aa33dd3295c16a]::ty::subst::GenericArg>>::lower_into
  37:     0x7ff85a1d9542 - <&chalk_ir[63366a7a24aa785e]::GenericArg<rustc_middle[63aa33dd3295c16a]::traits::chalk::RustInterner> as rustc_traits[dffea30f4dbc27f6]::chalk::lowering::LowerInto<rustc_middle[63aa33dd3295c16a]::ty::subst::GenericArg>>::lower_into
  38:     0x7ff85a1d4e93 - <&chalk_ir[63366a7a24aa785e]::GenericArg<rustc_middle[63aa33dd3295c16a]::traits::chalk::RustInterner> as rustc_traits[dffea30f4dbc27f6]::chalk::lowering::LowerInto<rustc_middle[63aa33dd3295c16a]::ty::subst::GenericArg>>::lower_into
  39:     0x7ff85a655e7c - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  40:     0x7ff85a6fa4fa - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  41:     0x7ff85a5f5970 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  42:     0x7ff85a585406 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  43:     0x7ff85a6307eb - <rustc_query_impl[66d4c656b011426]::Queries as rustc_middle[63aa33dd3295c16a]::ty::query::QueryEngine>::try_mark_green
  44:     0x7ff85a154d2e - <rustc_const_eval[2e3f6ed138b1d2c2]::interpret::machine::StackPopJump as core[3b5640218fb446b]::fmt::Debug>::fmt
  45:     0x7ff85a15ebaa - <rustc_const_eval[2e3f6ed138b1d2c2]::interpret::memory::AllocCheck as core[3b5640218fb446b]::fmt::Debug>::fmt
  46:     0x7ff85a05362f - rustc_const_eval[2e3f6ed138b1d2c2]::interpret::eval_context::mir_assign_valid_types
  47:     0x7ff85a09a5d8 - rustc_const_eval[2e3f6ed138b1d2c2]::const_eval::eval_queries::eval_to_allocation_raw_provider
  48:     0x7ff85a656034 - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  49:     0x7ff85a6fb351 - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  50:     0x7ff85a5f1178 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  51:     0x7ff85a56b4ef - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  52:     0x7ff85a62f89d - <rustc_query_impl[66d4c656b011426]::Queries as rustc_middle[63aa33dd3295c16a]::ty::query::QueryEngine>::try_mark_green
  53:     0x7ff85a0989cb - rustc_const_eval[2e3f6ed138b1d2c2]::const_eval::eval_queries::eval_to_const_value_raw_provider
  54:     0x7ff85a656034 - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  55:     0x7ff85a6fbb2b - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  56:     0x7ff85a5f1414 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  57:     0x7ff85a571530 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  58:     0x7ff85a62f90d - <rustc_query_impl[66d4c656b011426]::Queries as rustc_middle[63aa33dd3295c16a]::ty::query::QueryEngine>::try_mark_green
  59:     0x7ff85b3b9b8a - <rustc_middle[63aa33dd3295c16a]::ty::context::TyCtxt>::const_eval_global_id
  60:     0x7ff85b3ea39c - <rustc_middle[63aa33dd3295c16a]::ty::context::TyCtxt>::const_eval_resolve
  61:     0x7ff85b25284a - <rustc_infer[bf6a5cf34576fc96]::infer::InferCtxt>::const_eval_resolve
  62:     0x7ff85b1a487d - rustc_trait_selection[1c7115e003ec50b7]::traits::const_evaluatable::is_const_evaluatable
  63:     0x7ff85b156f1d - <rustc_trait_selection[1c7115e003ec50b7]::traits::fulfill::FulfillProcessor>::progress_changed_obligations
  64:     0x7ff85b17bd84 - <rustc_trait_selection[1c7115e003ec50b7]::traits::select::ProvisionalEvaluation as core[3b5640218fb446b]::fmt::Debug>::fmt
  65:     0x7ff85b15626d - <rustc_trait_selection[1c7115e003ec50b7]::traits::fulfill::FulfillmentContext>::new_ignoring_regions
  66:     0x7ff85b156930 - <rustc_trait_selection[1c7115e003ec50b7]::traits::fulfill::FulfillmentContext as rustc_infer[bf6a5cf34576fc96]::traits::engine::TraitEngine>::select_with_constness_where_possible
  67:     0x7ff8597fd81b - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
  68:     0x7ff859802199 - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::structurally_resolved_type
  69:     0x7ff8597d6d3e - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_call
  70:     0x7ff85983f221 - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  71:     0x7ff8597f09b9 - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_for_cast
  72:     0x7ff859807224 - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_stmt
  73:     0x7ff859807abd - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_block_no_value
  74:     0x7ff8597f09b9 - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_for_cast
  75:     0x7ff8597f1918 - <rustc_typeck[ce8e60202e7a8568]::check::fn_ctxt::FnCtxt>::check_for_cast
  76:     0x7ff859a13240 - <rustc_typeck[ce8e60202e7a8568]::variance::terms::TermsContext as rustc_hir[695f4c026424ffe0]::itemlikevisit::ItemLikeVisitor>::visit_foreign_item
  77:     0x7ff85995b265 - <rustc_typeck[ce8e60202e7a8568]::check::op::Op as core[3b5640218fb446b]::fmt::Debug>::fmt
  78:     0x7ff8598e763c - rustc_typeck[ce8e60202e7a8568]::check::provide
  79:     0x7ff85a658616 - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  80:     0x7ff85a70e551 - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  81:     0x7ff85a5fd450 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  82:     0x7ff85a4686d1 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  83:     0x7ff85a58c055 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  84:     0x7ff8599c718b - <rustc_typeck[ce8e60202e7a8568]::constrained_generic_params::Parameter as core[3b5640218fb446b]::fmt::Debug>::fmt
  85:     0x7ff8598ecac3 - <rustc_typeck[ce8e60202e7a8568]::check::CheckItemTypesVisitor as rustc_hir[695f4c026424ffe0]::itemlikevisit::ItemLikeVisitor>::visit_item
  86:     0x7ff85a65afcb - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  87:     0x7ff85a735e4e - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  88:     0x7ff85a60277a - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  89:     0x7ff85a5037bd - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  90:     0x7ff85a55d575 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  91:     0x7ff85990f70a - <rustc_typeck[ce8e60202e7a8568]::check::PlaceOp as core[3b5640218fb446b]::fmt::Debug>::fmt
  92:     0x7ff8598a5175 - rustc_typeck[ce8e60202e7a8568]::check_crate
  93:     0x7ff85702f9af - rustc_interface[1c6a2488f78f6a24]::passes::analysis
  94:     0x7ff85a65ab7b - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  95:     0x7ff85a72e52e - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  96:     0x7ff85a5f3901 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  97:     0x7ff85a4f0f69 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  98:     0x7ff85a58c4a2 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  99:     0x7ff856f4b960 - <rustc_driver[dea966e5e189d317]::args::Error as core[3b5640218fb446b]::fmt::Debug>::fmt
 100:     0x7ff856ef03d5 - <rustc_span[c5d9e30fa007120c]::symbol::SymbolStr as core[3b5640218fb446b]::fmt::Display>::fmt
 101:     0x7ff856ee1b25 - <chalk_engine[5e046f5921b469d8]::TimeStamp>::increment
 102:     0x7ff856ef1781 - <rustc_span[c5d9e30fa007120c]::symbol::SymbolStr as core[3b5640218fb446b]::fmt::Display>::fmt
 103:     0x7ff856eed773 - rustc_driver[dea966e5e189d317]::pretty::print_after_hir_lowering
 104:     0x7ff856f685f8 - <rustc_driver[dea966e5e189d317]::args::Error as core[3b5640218fb446b]::fmt::Debug>::fmt
 105:     0x7ff8681db18c - std::sys::windows::thread::Thread::new::h578a3ae84cde46a8
 106:     0x7ff8cf9e7034 - BaseThreadInitThunk
 107:     0x7ff8d1282651 - RtlUserThreadStart
```

</p>
</details>

**Comment by lcnr** [comment]
probably fixed by stalling for inference variables which causes us to stop having weird bound vars during ctfe.

as it seems hard to get a nice mcve for this, closing
