### ISSUE TITLE
ICE: `Option::unwrap()` on a `None` value, def_path_hash_map.rs:18:85

### ISSUE THREAD

**Issue by ibookstein** [rust-lang/rust#92325]
### Code
This issue seems to be related to incremental compilation, because yanking the code to a separate binary compiled successfully. I zipped the entire directory but it's a bit too large to upload...

### Meta

`rustc --version --verbose`:
```
PS Z:\Projects\aoc> rustc --version --verbose
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
PS Z:\Projects\aoc> rustc --crate-name 2021_day19 --edition=2021 src\bin\2021_day19.rs --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=8ba15e5d71c83007 --out-dir Z:\Projects\aoc\target\debug\deps -C incremental=Z:\Projects\aoc\target\debug\incremental -L dependency=Z:\Projects\aoc\target\debug\deps --extern aoc=Z:\Projects\aoc\target\debug\deps\libaoc-60be7e5b301e2efa.rlib --extern bimap=Z:\Projects\aoc\target\debug\deps\libbimap-b8f2e746078294fb.rlib --extern bitreader=Z:\Projects\aoc\target\debug\deps\libbitreader-0f4a5ed040161c70.rlib --extern bitvec=Z:\Projects\aoc\target\debug\deps\libbitvec-fdf10dc6deec369b.rlib --extern hex=Z:\Projects\aoc\target\debug\deps\libhex-22e62d81b05fbfdc.rlib --extern itermore=Z:\Projects\aoc\target\debug\deps\libitermore-047510360149a9d2.rlib --extern itertools=Z:\Projects\aoc\target\debug\deps\libitertools-339658f918e82723.rlib --extern lazy_static=Z:\Projects\aoc\target\debug\deps\liblazy_static-cf0478a2c0b8c8f8.rlib --extern num_bigint=Z:\Projects\aoc\target\debug\deps\libnum_bigint-cad4e3a79f25179a.rlib --extern num_derive=Z:\Projects\aoc\target\debug\deps\num_derive-b361c6081125db78.dll --extern num_integer=Z:\Projects\aoc\target\debug\deps\libnum_integer-b0007edce17c2bd5.rlib --extern num_rational=Z:\Projects\aoc\target\debug\deps\libnum_rational-9e09c7b2261b0eab.rlib --extern num_traits=Z:\Projects\aoc\target\debug\deps\libnum_traits-58d825b565ece2c7.rlib --extern num_enum=Z:\Projects\aoc\target\debug\deps\libnum_enum-cbdaf821c3290463.rlib --extern petgraph=Z:\Projects\aoc\target\debug\deps\libpetgraph-f47e6945fd32c42f.rlib --extern regex=Z:\Projects\aoc\target\debug\deps\libregex-67526a4c430cdc40.rlib --extern reqwest=Z:\Projects\aoc\target\debug\deps\libreqwest-bbf34aeaa2e8b87d.rlib --extern strum=Z:\Projects\aoc\target\debug\deps\libstrum-8926d1bc85f86faa.rlib --extern strum_macros=Z:\Projects\aoc\target\debug\deps\strum_macros-53c1894205bb4449.dll
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_metadata\src\rmeta\def_path_hash_map.rs:18:85
stack backtrace:
   0:     0x7ffa664092cf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h53606b08c01ef688
   1:     0x7ffa6643306a - core::fmt::write::he97f21b785b90134
   2:     0x7ffa663fb448 - <std::io::IoSlice as core::fmt::Debug>::fmt::h967100caef347f28
   3:     0x7ffa6640cd96 - std::panicking::take_hook::hb46205f0055becfd
   4:     0x7ffa6640c797 - std::panicking::take_hook::hb46205f0055becfd
   5:     0x7ffa5a53a295 - <tracing_subscriber::fmt::writer::TestWriter as std::io::Write>::flush::hff7a705da113f4ca
   6:     0x7ffa6640d6a9 - std::panicking::rust_panic_with_hook::hce0846b912adb5c5
   7:     0x7ffa6640d11f - rust_begin_unwind
   8:     0x7ffa66409bf7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h53606b08c01ef688
   9:     0x7ffa6640d0a9 - rust_begin_unwind
  10:     0x7ffa66469510 - core::panicking::panic_fmt::h58715deff5969a45
  11:     0x7ffa6646945c - core::panicking::panic::hc36befec1b90302c
  12:     0x7ffa5e12fc4f - rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc_session::cstore::CrateStore for rustc_metadata::creader::CStore>::def_path_hash_to_def_id::ha326ea748584dae2
  13:     0x7ffa5ddbb95a - <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id::h9f7b03ae96e81f81
  14:     0x7ffa5eacedc4 - rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::DefId>::recover::h5e74fdbc885e3958
  15:     0x7ffa5dce586d - rustc_query_impl::query_callbacks::adt_def::force_from_dep_node::he666492f1954504a
  16:     0x7ffa5dd3cb34 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  17:     0x7ffa5dd3cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  18:     0x7ffa5dd3cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  19:     0x7ffa5dd3cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  20:     0x7ffa5dd3cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  21:     0x7ffa5dd3cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  22:     0x7ffa5dd1497d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  23:     0x7ffa5dbd59b9 - <rustc_mir_dataflow::framework::cursor::CursorPosition as core::fmt::Debug>::fmt::hdad43e681eb5eae7
  24:     0x7ffa5dc8e1f3 - <rustc_span::def_id::LocalDefId as rustc_query_impl::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string::h641e5a6d4a18de66
  25:     0x7ffa5daa17c9 - <rustc_mir_dataflow::framework::cursor::CursorPosition as core::fmt::Debug>::fmt::hdad43e681eb5eae7
  26:     0x7ffa5dcfdf5e - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  27:     0x7ffa5d03ea1c - rustc_typeck::check::check::check_item_type::hfe6269e24b095dbe
  28:     0x7ffa5cfd93b7 - <<dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path::SubstsForAstPathCtxt as rustc_typeck::astconv::CreateSubstsForGenericArgsCtxt>::inferred_kind::h3effd8703dda5339
  29:     0x7ffa5d04ab1d - rustc_typeck::check::check::check_item_type::hfe6269e24b095dbe
  30:     0x7ffa5dcc0476 - ZN16rustc_query_impl13on_disk_cache260_$LT$impl$u20$rustc_serialize..serialize..Decodable$LT$rustc_query_impl..on_disk_cache..CacheDecoder$GT$$u20$for$u20$$RF$std..collections..hash..set..HashSet$LT$rustc_span..def_id..LocalDefId$C$core..hash..BuildHasher
  31:     0x7ffa5dd5a0bb - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  32:     0x7ffa5dc939db - <rustc_span::def_id::LocalDefId as rustc_query_impl::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string::h641e5a6d4a18de66
  33:     0x7ffa5da3915b - <rustc_mir_dataflow::framework::cursor::CursorPosition as core::fmt::Debug>::fmt::hdad43e681eb5eae7
  34:     0x7ffa5dd023aa - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  35:     0x7ffa5cfd7f3f - <<dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path::SubstsForAstPathCtxt as rustc_typeck::astconv::CreateSubstsForGenericArgsCtxt>::inferred_kind::h3effd8703dda5339
  36:     0x7ffa5ceedc0b - rustc_typeck::check_crate::h07f2a7631cf584be
  37:     0x7ffa5a6a3e8d - rustc_interface::passes::analysis::hc0b219c9fceabc88
  38:     0x7ffa5dcbb8eb - ZN16rustc_query_impl13on_disk_cache260_$LT$impl$u20$rustc_serialize..serialize..Decodable$LT$rustc_query_impl..on_disk_cache..CacheDecoder$GT$$u20$for$u20$$RF$std..collections..hash..set..HashSet$LT$rustc_span..def_id..LocalDefId$C$core..hash..BuildHasher
  39:     0x7ffa5dd4c61d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  40:     0x7ffa5dc92972 - <rustc_span::def_id::LocalDefId as rustc_query_impl::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string::h641e5a6d4a18de66
  41:     0x7ffa5da34849 - <rustc_mir_dataflow::framework::cursor::CursorPosition as core::fmt::Debug>::fmt::hdad43e681eb5eae7
  42:     0x7ffa5dcfe095 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  43:     0x7ffa5a58e59a - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::h8e44660347c50da5
  44:     0x7ffa5a558944 - rustc_driver::pretty::print_after_hir_lowering::h16ae7f3f7d316762
  45:     0x7ffa5a5907e6 - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::h8e44660347c50da5
  46:     0x7ffa5a55ed63 - rustc_driver::pretty::print_after_hir_lowering::h16ae7f3f7d316762
  47:     0x7ffa5a5b9a58 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h11014d06e9af86ea
  48:     0x7ffa66419d8c - std::sys::windows::thread::Thread::new::h4046847bccf80b57
  49:     0x7ffad7747034 - BaseThreadInitThunk
  50:     0x7ffad8162651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_of] computing type of `<impl at src\bin\2021_day19.rs:12:1: 60:2>::all::{opaque#0}`
#1 [check_mod_item_types] checking item types in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by Aaron1011** [comment]
This should be fixed on the latest nightly.

**Comment by ibookstein** [comment]
Alright, thank you!
