### ISSUE TITLE
ICE with chumsky crate

### ISSUE THREAD

**Issue by devonhollowood** [rust-lang/rust#92398]
#### Cargo.toml
```
[package]
name = "ice-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.7"
```

#### src/lib.rs
```Rust
use chumsky::prelude::*;
use chumsky::text::*;

pub fn parser() -> impl Parser<char, i64, Error = Simple<char>> {
    just("foo ")
        .to((|n: i64| n) as fn(i64) -> i64)
        .then(int(10))
        .map(|(f, n): (fn(i64) -> i64, i64)| f(n))
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

**This bug does not appear to occur in beta or nightly** (`cargo 1.58.0-beta (7f08ace4f 2021-11-24)` and `cargo 1.59.0-nightly (fcef61230 2021-12-17)`). I'm not sure whether it's still useful to report here.

### Error output

```
WARN rustc_metadata::locator no metadata found: incompatible metadata version found: '/home/devon/Documents/programming/ice-repro/target/debug/deps/libproc_macro_hack-bd66513869653eb4.so'
WARN rustc_metadata::locator no metadata found: incompatible metadata version found: '/home/devon/Documents/programming/ice-repro/target/debug/deps/libconst_random_macro-4dca77b4f7663b1c.so'
thread 'rustc' panicked at 'DefId::expect_local: `DefId(20:1328 ~ chumsky[a70a]::text::int::{opaque#0})` isn't local', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_span/src/def_id.rs:234:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `parser`
#1 [mir_built] building MIR for `parser`
end of query stack
error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: rustc_errors::Handler::delay_good_path_bug
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
             3: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
             4: rustc_data_structures::stack::ensure_sufficient_stack
             5: rustc_query_system::query::plumbing::try_execute_query
             6: rustc_query_system::query::plumbing::get_query
             7: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
             8: rustc_middle::ty::print::Printer::default_print_def_path
             9: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
            10: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::pretty::PrettyPrinter>::in_binder
            11: std::thread::local::LocalKey<T>::with
            12: rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_type
            13: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::pretty::PrettyPrinter>::generic_delimiters
            14: rustc_middle::ty::print::Printer::default_print_def_path
            15: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
            16: rustc_middle::ty::print::pretty::<impl rustc_middle::ty::print::Print<P> for rustc_middle::ty::ProjectionPredicate>::print
            17: rustc_middle::ty::print::pretty::<impl rustc_middle::ty::print::Print<P> for rustc_middle::ty::PredicateKind>::print
            18: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::pretty::PrettyPrinter>::in_binder
            19: rustc_middle::ty::print::pretty::<impl core::fmt::Display for rustc_middle::ty::Predicate>::fmt
            20: core::fmt::write
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
            21: core::fmt::Write::write_fmt
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:186:9
            22: alloc::fmt::format
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/fmt.rs:579:5
            23: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::report_projection_error
            24: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
            25: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
            26: rustc_typeck::check::coercion::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::try_coerce
            27: rustc_typeck::check::coercion::CoerceMany<E>::coerce_inner
            28: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
            29: rustc_typeck::check::check::check_fn
            30: rustc_infer::infer::InferCtxtBuilder::enter
            31: rustc_typeck::check::typeck
            32: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            33: rustc_data_structures::stack::ensure_sufficient_stack
            34: rustc_query_system::query::plumbing::try_execute_query
            35: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
            36: rustc_middle::ty::context::TyCtxt::typeck_opt_const_arg
            37: rustc_mir_build::build::mir_built
            38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            39: rustc_data_structures::stack::ensure_sufficient_stack
            40: rustc_query_system::query::plumbing::try_execute_query
            41: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
            42: rustc_mir_transform::check_unsafety::unsafety_check_result
            43: core::ops::function::FnOnce::call_once
            44: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            45: rustc_data_structures::stack::ensure_sufficient_stack
            46: rustc_query_system::query::plumbing::try_execute_query
            47: rustc_query_system::query::plumbing::force_query_impl
            48: rustc_query_impl::query_callbacks::unsafety_check_result::force_from_dep_node
            49: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
            50: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
            51: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
            52: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory
            53: rustc_query_system::query::plumbing::try_execute_query
            54: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
            55: rustc_typeck::collect::type_of::type_of
            56: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            57: rustc_data_structures::stack::ensure_sufficient_stack
            58: rustc_query_system::query::plumbing::try_execute_query
            59: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
            60: rustc_typeck::check::check::check_item_type
            61: rustc_middle::hir::map::Map::visit_item_likes_in_module
            62: rustc_typeck::check::check::check_mod_item_types
            63: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            64: rustc_data_structures::stack::ensure_sufficient_stack
            65: rustc_query_system::query::plumbing::try_execute_query
            66: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
            67: rustc_middle::hir::map::Map::for_each_module
            68: rustc_typeck::check_crate
            69: rustc_interface::passes::analysis
            70: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
            71: rustc_data_structures::stack::ensure_sufficient_stack
            72: rustc_query_system::query::plumbing::try_execute_query
            73: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
            74: rustc_interface::passes::QueryContext::enter
            75: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
            76: rustc_span::with_source_map
            77: scoped_tls::ScopedKey<T>::set
            78: std::sys_common::backtrace::__rust_begin_short_backtrace
            79: core::ops::function::FnOnce::call_once{{vtable.shim}}
            80: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
            81: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
            82: std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
            83: start_thread
            84: __GI___clone
          

thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:1165:13
stack backtrace:
   0:     0x7f3d00935a9c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f3d00935a9c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3d00935a9c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f3d00935a9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f3d00992fdc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x7f3d00925c05 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x7f3d00938f60 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f3d00938f60 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f3d00938f60 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x7f3d00938b15 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x7f3d011252b1 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h932547f60770f26a
  11:     0x7f3d00939779 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
  12:     0x7f3d00939230 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  13:     0x7f3d00935f44 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x7f3d00939199 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  15:     0x7f3d008fd441 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  16:     0x7f3d02209c3c - core::panicking::panic_display::h0c6ac292783ee908
  17:     0x7f3d03734866 - rustc_errors::HandlerInner::flush_delayed::hc35129b420cfd4e2
  18:     0x7f3d03733121 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h3c24eb5201838cbf
  19:     0x7f3d02d252a8 - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::hd814f279f0e36752
  20:     0x7f3d02d276ca - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hf486b211acc1f0aa
  21:     0x7f3d02cf87ad - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::hefd4f3f97698e310
  22:     0x7f3d02cf858c - rustc_span::with_source_map::h6ab8a240e103b5b9
  23:     0x7f3d02d0a2ac - scoped_tls::ScopedKey<T>::set::hd1fbd64c6f645895
  24:     0x7f3d02cf8ef5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a1328c9fa7f7448
  25:     0x7f3d02d24962 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4ea1ced06d6b3e97
  26:     0x7f3d00944933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7bd677a5dc988be6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  27:     0x7f3d00944933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7b1c1ba11c4db785
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  28:     0x7f3d00944933 - std::sys::unix::thread::Thread::new::thread_start::h9c58c0d12d84e854
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  29:     0x7f3d00854259 - start_thread
  30:     0x7f3d007695e3 - __GI___clone
  31:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `ice-repro`

Caused by:
  process didn't exit successfully: `rustc --crate-name ice_repro --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ecaa746029b2d5f1 -C extra-filename=-ecaa746029b2d5f1 --out-dir /home/devon/Documents/programming/ice-repro/target/debug/deps -C incremental=/home/devon/Documents/programming/ice-repro/target/debug/incremental -L dependency=/home/devon/Documents/programming/ice-repro/target/debug/deps --extern chumsky=/home/devon/Documents/programming/ice-repro/target/debug/deps/libchumsky-453f428639b3e404.rmeta` (signal: 4, SIGILL: illegal instruction)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'DefId::expect_local: `DefId(20:1328 ~ chumsky[a70a]::text::int::{opaque#0})` isn't local', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_span/src/def_id.rs:234:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: rustc_middle::ty::error::<impl rustc_middle::ty::context::TyCtxt>::suggest_constraining_opaque_associated_type
   3: rustc_middle::ty::error::<impl rustc_middle::ty::context::TyCtxt>::note_and_explain_type_err
   4: rustc_infer::infer::error_reporting::<impl rustc_infer::infer::InferCtxt>::note_type_err
   5: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::report_projection_error
   6: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
   7: rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::resolve_vars_with_obligations
   8: rustc_typeck::check::coercion::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::try_coerce
   9: rustc_typeck::check::coercion::CoerceMany<E>::coerce_inner
  10: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  11: rustc_typeck::check::check::check_fn
  12: rustc_infer::infer::InferCtxtBuilder::enter
  13: rustc_typeck::check::typeck
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::try_execute_query
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  18: rustc_middle::ty::context::TyCtxt::typeck_opt_const_arg
  19: rustc_mir_build::build::mir_built
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  21: rustc_data_structures::stack::ensure_sufficient_stack
  22: rustc_query_system::query::plumbing::try_execute_query
  23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
  24: rustc_mir_transform::check_unsafety::unsafety_check_result
  25: core::ops::function::FnOnce::call_once
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::try_execute_query
  29: rustc_query_system::query::plumbing::force_query_impl
  30: rustc_query_impl::query_callbacks::unsafety_check_result::force_from_dep_node
  31: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  32: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  33: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  34: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory
  35: rustc_query_system::query::plumbing::try_execute_query
  36: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  37: rustc_typeck::collect::type_of::type_of
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  39: rustc_data_structures::stack::ensure_sufficient_stack
  40: rustc_query_system::query::plumbing::try_execute_query
  41: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
  42: rustc_typeck::check::check::check_item_type
  43: rustc_middle::hir::map::Map::visit_item_likes_in_module
  44: rustc_typeck::check::check::check_mod_item_types
  45: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  46: rustc_data_structures::stack::ensure_sufficient_stack
  47: rustc_query_system::query::plumbing::try_execute_query
  48: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
  49: rustc_middle::hir::map::Map::for_each_module
  50: rustc_typeck::check_crate
  51: rustc_interface::passes::analysis
  52: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  53: rustc_data_structures::stack::ensure_sufficient_stack
  54: rustc_query_system::query::plumbing::try_execute_query
  55: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  56: rustc_interface::passes::QueryContext::enter
  57: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  58: rustc_span::with_source_map
  59: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by compiler-errors** [comment]
> This bug does not appear to occur in beta or nightly

I'll close this then.
