### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds: the len is 375 but the index is 375'

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [rust-lang/rust#92429]
### Code

The project repo [rust-code](https://github.com/JonathanWoollett-Light/rust-ad)

(minimal example currently WIP)

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (e99963c55 2021-10-29)
binary: rustc
commit-hash: e99963c554e4d12010c2dea9f46d7bbd41dc1271
commit-date: 2021-10-29
host: x86_64-pc-windows-msvc
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### Error output

```
C:\Users\User\Projects\rust-ad>cargo build
warning: the feature `adt_const_params` is incomplete and may not be safe to use and/or cause compiler crashes
 --> core\src\lib.rs:2:12
  |
2 | #![feature(adt_const_params)]
  |            ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: `rust-ad-core` (lib) generated 1 warning
warning: `rust-ad-core` (lib) generated 1 warning (1 duplicate)
   Compiling rust-ad-macros v0.4.1 (C:\Users\User\Projects\rust-ad\macros)
thread 'rustc' panicked at 'index out of bounds: the len is 375 but the index is 375', /rustc/e99963c554e4d12010c2dea9f46d7bbd41dc1271\compiler\rustc_middle\src\mir\interpret\mod.rs:282:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (e99963c55 2021-10-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [exported_symbols] exported_symbols
#1 [upstream_monomorphizations_for] collecting available upstream monomorphizations for `proc_macro::bridge::client::Client::<fn(proc_macro::TokenStream) -> proc_macro::TokenStream>::expand1::run`
end of query stack
error: could not compile `rust-ad-macros`

C:\Users\User\Projects\rust-ad>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
C:\Users\User\Projects\rust-ad>set RUST_BACKTRACE=full

C:\Users\User\Projects\rust-ad>cargo build
warning: the feature `adt_const_params` is incomplete and may not be safe to use and/or cause compiler crashes
 --> core\src\lib.rs:2:12
  |
2 | #![feature(adt_const_params)]
  |            ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: `rust-ad-core` (lib) generated 1 warning
warning: `rust-ad-core` (lib) generated 1 warning (1 duplicate)
   Compiling rust-ad-macros v0.4.1 (C:\Users\User\Projects\rust-ad\macros)
thread 'rustc' panicked at 'index out of bounds: the len is 375 but the index is 375', /rustc/e99963c554e4d12010c2dea9f46d7bbd41dc1271\compiler\rustc_middle\src\mir\interpret\mod.rs:282:35
stack backtrace:
   0:     0x7fff8d7d8b4f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4287336b592e4e30
   1:     0x7fff8d8027ca - core::fmt::write::h8a2c40ddb66ccc71
   2:     0x7fff8d7cb4f8 - <std::io::IoSlice as core::fmt::Debug>::fmt::h37489b9473b33977
   3:     0x7fff8d7dc2a6 - std::panicking::take_hook::hf14c76592f73c762
   4:     0x7fff8d7dbd8c - std::panicking::take_hook::hf14c76592f73c762
   5:     0x7fff4e23aa9e - <tracing_subscriber[281ba6a53a80a207]::fmt::writer::TestWriter>::new
   6:     0x7fff8d7dcbb9 - std::panicking::rust_panic_with_hook::hbc0e9c80ca88eac0
   7:     0x7fff8d7dc65b - rust_begin_unwind
   8:     0x7fff8d7d9487 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4287336b592e4e30
   9:     0x7fff8d7dc5b9 - rust_begin_unwind
  10:     0x7fff8d836cd0 - core::panicking::panic_fmt::hc1b1ca620e7a2c9f
  11:     0x7fff8d836c97 - core::panicking::panic_bounds_check::h1ef082ed7c01d5b9
  12:     0x7fff51f57d80 - rustc_metadata[dfdfc7113336e1f8]::dynamic_lib::dl::symbol
  13:     0x7fff51ee77ab - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  14:     0x7fff51e8b347 - <u32 as rustc_metadata[dfdfc7113336e1f8]::rmeta::table::FixedSizeEncoding>::write_to_bytes_at
  15:     0x7fff51f643e3 - rustc_metadata[dfdfc7113336e1f8]::dynamic_lib::dl::symbol
  16:     0x7fff51f6291f - rustc_metadata[dfdfc7113336e1f8]::dynamic_lib::dl::symbol
  17:     0x7fff51e65f10 - <rustc_metadata[dfdfc7113336e1f8]::creader::global_allocator_spans::Finder as rustc_ast[3ebc127026e5cc83]::visit::Visitor>::visit_item
  18:     0x7fff51eea22c - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  19:     0x7fff51f0ee06 - <rustc_span[abfcba77a0dab5e7]::span_encoding::Span as rustc_serialize[e9f3e8e17ec8afb5]::serialize::Encodable<rustc_metadata[dfdfc7113336e1f8]::rmeta::encoder::EncodeContext>>::encode
  20:     0x7fff51e93698 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  21:     0x7fff51e9a758 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  22:     0x7fff51e634d3 - <rustc_metadata[dfdfc7113336e1f8]::creader::global_allocator_spans::Finder as rustc_ast[3ebc127026e5cc83]::visit::Visitor>::visit_item
  23:     0x7fff51f63a72 - rustc_metadata[dfdfc7113336e1f8]::dynamic_lib::dl::symbol
  24:     0x7fff51eea1a8 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  25:     0x7fff51e9370e - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  26:     0x7fff51e9a758 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  27:     0x7fff51e632db - <rustc_metadata[dfdfc7113336e1f8]::creader::global_allocator_spans::Finder as rustc_ast[3ebc127026e5cc83]::visit::Visitor>::visit_item
  28:     0x7fff51f63a72 - rustc_metadata[dfdfc7113336e1f8]::dynamic_lib::dl::symbol
  29:     0x7fff51eea1a8 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  30:     0x7fff51f0ee06 - <rustc_span[abfcba77a0dab5e7]::span_encoding::Span as rustc_serialize[e9f3e8e17ec8afb5]::serialize::Encodable<rustc_metadata[dfdfc7113336e1f8]::rmeta::encoder::EncodeContext>>::encode
  31:     0x7fff51e93698 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  32:     0x7fff51e9a758 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  33:     0x7fff51f095ac - <rustc_metadata[dfdfc7113336e1f8]::dynamic_lib::DynamicLibrary>::open
  34:     0x7fff51e910a4 - <rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::DecodeContext as rustc_middle[68438b5bfe988d4e]::ty::codec::TyDecoder>::decode_alloc_id
  35:     0x7fff51f3c6b8 - rustc_metadata[dfdfc7113336e1f8]::rmeta::decoder::cstore_impl::provide_extern
  36:     0x7fff51acc8e6 - <rustc_query_impl[2492acdb0e5eb4f6]::on_disk_cache::CacheDecoder as rustc_serialize[e9f3e8e17ec8afb5]::serialize::Decoder>::error
  37:     0x7fff51a5d29a - <rustc_query_impl[2492acdb0e5eb4f6]::Queries as rustc_middle[68438b5bfe988d4e]::ty::query::QueryEngine>::try_mark_green
  38:     0x7fff519abb78 - rustc_query_impl[2492acdb0e5eb4f6]::profiling_support::alloc_self_profile_query_strings
  39:     0x7fff5180a0f0 - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  40:     0x7fff51724266 - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  41:     0x7fff519ef733 - rustc_query_impl[2492acdb0e5eb4f6]::query_callbacks::exported_symbols
  42:     0x7fff526dc0b3 - <rustc_middle[68438b5bfe988d4e]::ty::context::TyCtxt as rustc_query_system[993d4a9a8633e257]::dep_graph::DepContext>::try_force_from_dep_node
  43:     0x7fff51a347cb - <rustc_query_impl[2492acdb0e5eb4f6]::Queries as rustc_middle[68438b5bfe988d4e]::ty::query::QueryEngine>::try_mark_green
  44:     0x7fff51a347a7 - <rustc_query_impl[2492acdb0e5eb4f6]::Queries as rustc_middle[68438b5bfe988d4e]::ty::query::QueryEngine>::try_mark_green
  45:     0x7fff51a0caea - <rustc_query_impl[2492acdb0e5eb4f6]::Queries as rustc_middle[68438b5bfe988d4e]::ty::query::QueryEngine>::try_mark_green
  46:     0x7fff51894a19 - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  47:     0x7fff51988fb2 - rustc_query_impl[2492acdb0e5eb4f6]::profiling_support::alloc_self_profile_query_strings
  48:     0x7fff517b95c7 - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  49:     0x7fff518e8b27 - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  50:     0x7fff52777d66 - <rustc_middle[68438b5bfe988d4e]::ty::instance::Instance>::upstream_monomorphization
  51:     0x7fff5083baf6 - <rustc_monomorphize[b3b7798a5c6a84be]::collector::MirNeighborCollector as rustc_middle[68438b5bfe988d4e]::mir::visit::Visitor>::visit_operand
  52:     0x7fff5083d8e3 - <rustc_monomorphize[b3b7798a5c6a84be]::collector::RootCollector as rustc_hir[c1b1b26d2913040d]::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  53:     0x7fff5083daf7 - <rustc_monomorphize[b3b7798a5c6a84be]::collector::RootCollector as rustc_hir[c1b1b26d2913040d]::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  54:     0x7fff5083660a - <rustc_monomorphize[b3b7798a5c6a84be]::partitioning::MonoItemPlacement as core[3b5640218fb446b]::fmt::Debug>::fmt
  55:     0x7fff5081df9f - <core[3b5640218fb446b]::option::Option<rustc_middle[68438b5bfe988d4e]::middle::privacy::AccessLevel> as rustc_privacy[879947c57bdcd0fc]::VisibilityLike>::new_min
  56:     0x7fff50835522 - <rustc_monomorphize[b3b7798a5c6a84be]::partitioning::MonoItemPlacement as core[3b5640218fb446b]::fmt::Debug>::fmt
  57:     0x7fff50832f2d - <rustc_monomorphize[b3b7798a5c6a84be]::partitioning::default::DefaultPartitioning as rustc_monomorphize[b3b7798a5c6a84be]::partitioning::Partitioner>::internalize_symbols
  58:     0x7fff51acefb3 - <rustc_query_impl[2492acdb0e5eb4f6]::on_disk_cache::CacheDecoder as rustc_serialize[e9f3e8e17ec8afb5]::serialize::Decoder>::error
  59:     0x7fff51a70193 - <rustc_query_impl[2492acdb0e5eb4f6]::Queries as rustc_middle[68438b5bfe988d4e]::ty::query::QueryEngine>::try_mark_green
  60:     0x7fff519ac13c - rustc_query_impl[2492acdb0e5eb4f6]::profiling_support::alloc_self_profile_query_strings
  61:     0x7fff5183bcdc - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  62:     0x7fff518e8f5a - <rustc_mir_dataflow[b218101e43c2c97d]::framework::cursor::CursorPosition as core[3b5640218fb446b]::fmt::Debug>::fmt
  63:     0x7fff51a0c19e - <rustc_query_impl[2492acdb0e5eb4f6]::Queries as rustc_middle[68438b5bfe988d4e]::ty::query::QueryEngine>::try_mark_green
  64:     0x7fff4e5067f4 - <rustc_codegen_llvm[584d2ba760d45538]::back::lto::ThinLTOKeysMap as core[3b5640218fb446b]::fmt::Debug>::fmt
  65:     0x7fff4e54988b - <rustc_codegen_llvm[584d2ba760d45538]::LlvmCodegenBackend as rustc_codegen_ssa[ac267e58a1423317]::traits::backend::CodegenBackend>::codegen_crate
  66:     0x7fff4e458a82 - <rustc_interface[ff1d7c07a753e82f]::passes::boxed_resolver::BoxedResolver>::to_resolver_outputs
  67:     0x7fff4e3a270b - <rustc_interface[ff1d7c07a753e82f]::queries::Linker>::link
  68:     0x7fff4e38a41f - <rustc_interface[ff1d7c07a753e82f]::queries::Queries>::ongoing_codegen
  69:     0x7fff4e29a916 - <rustc_span[abfcba77a0dab5e7]::symbol::SymbolStr as core[3b5640218fb446b]::fmt::Display>::fmt
  70:     0x7fff4e254816 - rustc_driver[af3c8dcfa508860b]::pretty::print_after_hir_lowering
  71:     0x7fff4e2b6bd6 - <rustc_span[abfcba77a0dab5e7]::symbol::SymbolStr as core[3b5640218fb446b]::fmt::Display>::fmt
  72:     0x7fff4e25dd13 - rustc_driver[af3c8dcfa508860b]::pretty::print_after_hir_lowering
  73:     0x7fff4e2d5788 - <rustc_driver[af3c8dcfa508860b]::args::Error as core[3b5640218fb446b]::fmt::Debug>::fmt
  74:     0x7fff8d7e927c - std::sys::windows::thread::Thread::new::he49a5cdb1d3d1cfc
  75:     0x7fffe0107034 - BaseThreadInitThunk
  76:     0x7fffe1e62651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (e99963c55 2021-10-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [exported_symbols] exported_symbols
#1 [upstream_monomorphizations_for] collecting available upstream monomorphizations for `proc_macro::bridge::client::Client::<fn(proc_macro::TokenStream) -> proc_macro::TokenStream>::expand1::run`
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `rust-ad-macros`

C:\Users\User\Projects\rust-ad>
```

</p>
</details>

**Comment by JonathanWoollett-Light** [comment]
It is worth mentioning I am aware this is improper usage of my own macros. This shouldn't however trigger a rustc error.

**Comment by JonathanWoollett-Light** [comment]
The error in the full context of the repo being:
```RUST
C:\Users\User\Projects\rust-ad>cargo build
warning: the feature `adt_const_params` is incomplete and may not be safe to use and/or cause compiler crashes
 --> core\src\lib.rs:2:12
  |
2 | #![feature(adt_const_params)]
  |            ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

warning: `rust-ad-core` (lib) generated 1 warning
warning: `rust-ad-core` (lib) generated 1 warning (1 duplicate)
   Compiling rust-ad-macros v0.4.1 (C:\Users\User\Projects\rust-ad\macros)
thread 'rustc' panicked at 'index out of bounds: the len is 375 but the index is 375', /rustc/e99963c554e4d12010c2dea9f46d7bbd41dc1271\compiler\rustc_middle\src\mir\interpret\mod.rs:282:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (e99963c55 2021-10-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [exported_symbols] exported_symbols
#1 [upstream_monomorphizations_for] collecting available upstream monomorphizations for `proc_macro::bridge::client::Client::<fn(proc_macro::TokenStream) -> proc_macro::TokenStream>::expand1::run`
end of query stack
error: could not compile `rust-ad-macros`

C:\Users\User\Projects\rust-ad>
```

**Comment by JonathanWoollett-Light** [comment]
Need refining error

**Comment by JonathanWoollett-Light** [comment]
Doing `cargo clean` fixes it.
