### ISSUE TITLE
rustc-1.57.0: hang while building gkrust for firefox 91.0.1

### ISSUE THREAD

**Issue by OSS542** [rust-lang/rust#92489]
```
LLVM        : 12.0.1
kernel      : Linux DellXPS 5.7.0 #4 SMP Mon Nov 2 16:45:10 JST 2020 x86_64 GNU/Linux
Xorg server : 1.20.9
g++ / gcc   : 10.2.0
misc        : custom system built entirely from source code
rustc       : 1.57.0

cpu      : Core 2 Quad Q9550 2.83GHz
flags    : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
           pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall
           nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid
           aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3
           cx16 xtpr pdcm sse4_1 lahf_lmpti tpr_shadow vnmi flexpriority
           vpid dtherm

graphics : AMDGPU(0): Chipset: "Radeon RX 580 Series" (ChipID = 0x67df)

```

The following command hangs causing the entire build to hang :
```
CARGO=/usr/bin/cargo CARGO_CRATE_NAME=gkrust_shared CARGO_MANIFEST_DIR=/home/jhart/temp/firefox-91.0.1/toolkit/library/rust/shared CARGO_PKG_AUTHORS='nobody@mozilla.org' CARGO_PKG_DESCRIPTION='Shared Rust code for libxul' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MPL-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=gkrust-shared CARGO_PKG_REPOSITORY='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/jhart/temp/firefox-91.0.1/firefox-build-dir/release/deps:/usr/lib' OUT_DIR=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/build/gkrust-shared-1c4aded3e26582f6/out /usr/bin/rustc --crate-name gkrust_shared toolkit/library/rust/shared/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C panic=abort -C embed-bitcode=no --cfg 'feature="audioipc-client"' --cfg 'feature="audioipc-server"' --cfg 'feature="bookmark_sync"' --cfg 'feature="cubeb-pulse"' --cfg 'feature="cubeb-remoting"' --cfg 'feature="cubeb-sys"' --cfg 'feature="cubeb_pulse_rust"' --cfg 'feature="default"' --cfg 'feature="gecko_profiler"' --cfg 'feature="gecko_profiler_parse_elf"' --cfg 'feature="glean_disable_upload"' --cfg 'feature="glean_with_gecko"' --cfg 'feature="mdns_service"' --cfg 'feature="moz_memory"' --cfg 'feature="moz_places"' --cfg 'feature="profiler_helper"' --cfg 'feature="quantum_render"' --cfg 'feature="remote"' --cfg 'feature="webgpu"' --cfg 'feature="webrender_bindings"' --cfg 'feature="webrtc"' --cfg 'feature="wgpu_bindings"' --cfg 'feature="with_dbus"' -C metadata=5b78e5caf7503537 -C extra-filename=-5b78e5caf7503537 --out-dir /home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=/home/jhart/temp/firefox-91.0.1/build/cargo-linker -C incremental=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/incremental -L dependency=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/release/deps --extern app_services_logger=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libapp_services_logger-4961b708f8bcef49.rmeta --extern audio_thread_priority=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libaudio_thread_priority-0ee62fb318c31f1d.rlib --extern audioipc_client=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libaudioipc_client-c294cc789758c28d.rmeta --extern audioipc_server=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libaudioipc_server-4774a7ac0647dbe8.rmeta --extern authenticator=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libauthenticator-48b1ca9ee411b107.rmeta --extern bookmark_sync=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libbookmark_sync-06c3f63e464d634c.rmeta --extern cascade_bloom_filter=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libcascade_bloom_filter-a96b61d48ba81a72.rmeta --extern cert_storage=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libcert_storage-c1f2a61aabc04c00.rmeta --extern chardetng_c=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libchardetng_c-dcebd2737e7ff450.rmeta --extern cosec=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libcosec-b06e73ac3c360db9.rmeta --extern cubeb_pulse=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libcubeb_pulse-e9192f1f89012160.rlib --extern cubeb_sys=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libcubeb_sys-7267f326af92198a.rmeta --extern encoding_glue=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libencoding_glue-88a102b9147ca30d.rmeta --extern fluent=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libfluent-89b7df1df93bc268.rmeta --extern fluent_ffi=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libfluent_ffi-ed7bd8f5f551400b.rmeta --extern fluent_langneg=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libfluent_langneg-252399a0091c3efd.rmeta --extern fluent_langneg_ffi=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libfluent_langneg_ffi-16c543255c9f0541.rmeta --extern fog_control=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libfog_control-1ff0518a2a27a65e.rmeta --extern gecko_profiler=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libgecko_profiler-0ca2c92097b1a711.rmeta --extern gecko_logger=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libgecko_logger-a0ad41923d638f1a.rmeta --extern geckoservo=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libgeckoservo-8d613c0e0823e8c0.rmeta --extern gkrust_utils=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libgkrust_utils-6862c76e1b92e537.rmeta --extern http_sfv=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libhttp_sfv-8c411f0a033efe52.rmeta --extern jsrust_shared=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libjsrust_shared-ec279de0c1681aa7.rmeta --extern kvstore=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libkvstore-3b38a8a013a0d24e.rmeta --extern l10nregistry_ffi=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libl10nregistry_ffi-aa5c59d52b3805bc.rmeta --extern lmdb_sys=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/liblmdb_sys-a7d6fefc0fab7a14.rmeta --extern log=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/liblog-37f4e91b7abd5153.rmeta --extern mapped_hyph=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libmapped_hyph-c7ce45eb6da82552.rmeta --extern mdns_service=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libmdns_service-57ae6e8cf78e0c19.rmeta --extern mozurl=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libmozurl-30fc256d5a281163.rmeta --extern mp4parse_capi=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libmp4parse_capi-729cc0d927b9d992.rmeta --extern neqo_glue=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libneqo_glue-b3028a22ee1b0347.rmeta --extern netwerk_helper=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libnetwerk_helper-d9b601fd0ae861b5.rmeta --extern nserror=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libnserror-d30c5d572e234249.rmeta --extern nsstring=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libnsstring-a7c5428d03a52ea3.rmeta --extern prefs_parser=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libprefs_parser-70bfd289bce4bb4a.rmeta --extern processtools=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libprocesstools-6f585909d43bba0f.rmeta --extern profiler_helper=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libprofiler_helper-a6381f6cb76826d0.rmeta --extern qcms=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libqcms-359baef40ef18b7a.rmeta --extern remote=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libremote-0b4a1bd12d3f87ce.rmeta --extern rsdparsa_capi=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/librsdparsa_capi-aa3c659b46f7a245.rmeta --extern rusqlite=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/librusqlite-098100655a089605.rmeta --extern static_prefs=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libstatic_prefs-fdedb0b0bdb3c726.rmeta --extern storage=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libstorage-4ba64b4ee43048ed.rmeta --extern unic_langid=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libunic_langid-1a9b788525052411.rmeta --extern unic_langid_ffi=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libunic_langid_ffi-9a3a3db97e901e65.rmeta --extern viaduct=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libviaduct-d40558a6947388e0.rmeta --extern webext_storage_bridge=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libwebext_storage_bridge-61a69f11081aac43.rmeta --extern webrender_bindings=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libwebrender_bindings-402fbfd340dc87a0.rmeta --extern wgpu_bindings=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libwgpu_bindings-031c7889890c39e8.rmeta --extern xpcom=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/deps/libxpcom-0ce225d853e1dbd5.rmeta --cap-lints warn -Cembed-bitcode=yes -C codegen-units=1 -L native=/usr/lib -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/build/audioipc-d5947dee49e56ce3/out -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/build/lmdb-rkv-sys-90ff5c9b6096e709/out -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/build/mozglue-static-7a76d9917998cd67/out -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/dist/bin -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/security/nss/lib/nss/nss_nss3 -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/security/nss/lib/ssl/ssl_ssl3 -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/config/external/nspr/pr -L native=/home/jhart/temp/firefox-91.0.1/firefox-build-dir/x86_64-unknown-linux-gnu/release/build/swgl-e2952f23b1546e66/out
```
output: gdb attach to  manual run, from "thread apply all bt" :

```
    Attaching to process 15122
    [New LWP 15123]
    [New LWP 15125]
    [New LWP 15126]
    [New LWP 15127]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/libthread_db.so.1".
    0x00007f8adccbf6bf in pthread_join (threadid=140234370545408, thread_return=0x0) at pthread_join.c:92
    92      pthread_join.c: No such file or directory.
    warning: File "/usr/lib64/libstdc++.so.6.0.28-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
    To enable execution of this file add
            add-auto-load-safe-path /usr/lib64/libstdc++.so.6.0.28-gdb.py
    line to your configuration file "/home/jhart/.gdbinit".
    To completely disable this security protection add
            set auto-load safe-path /
    line to your configuration file "/home/jhart/.gdbinit".
    For more information about this security protection see the
    "Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
            info "(gdb)Auto-loading safe path"
    (gdb) thread apply all bt

    Thread 5 (Thread 0x7f8aae4b6700 (LWP 15127)):
    #0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
    #1  0x00007f8ae1971119 in _L_lock_3329 () from /lib/libc.so.6
    #2  0x00007f8ae196c3db in _int_free (av=0x7f8ad4000020, p=0x7f8ad6584370, have_lock=0) at malloc.c:3940
    #3  0x00007f8addefd172 in llvm::DenseMapBase<llvm::DenseMap<llvm::Value const*, llvm::MDAttachments, llvm::DenseMapInfo<llvm::Value const*>, llvm::detail::Den
    seMapPair<llvm::Value const*, llvm::MDAttachments> >, llvm::Value const*, llvm::MDAttachments, llvm::DenseMapInfo<llvm::Value const*>, llvm::detail::DenseMapP
    air<llvm::Value const*, llvm::MDAttachments> >::FindAndConstruct(llvm::Value const*&&) () from /usr/lib/libLLVM-12.so
    #4  0x00007f8addefe4fe in llvm::Value::setMetadata(unsigned int, llvm::MDNode*) () from /usr/lib/libLLVM-12.so
    #5  0x00007f8ade9b3f9f in AddAliasScopeMetadata(llvm::CallBase&, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value con
    st*, llvm::sys::SmartMutex<false> > >&, llvm::DataLayout const&, llvm::AAResults*) [clone .constprop.0] () from /usr/lib/libLLVM-12.so
    #6  0x00007f8ade9b5ede in llvm::InlineFunction(llvm::CallBase&, llvm::InlineFunctionInfo&, llvm::AAResults*, bool, llvm::Function*) ()
       from /usr/lib/libLLVM-12.so
    #7  0x00007f8adf05cdb6 in llvm::LegacyInlinerBase::inlineCalls(llvm::CallGraphSCC&) () from /usr/lib/libLLVM-12.so
    #8  0x00007f8adf2c15b8 in (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) () from /usr/lib/libLLVM-12.so
    #9  0x00007f8addeeeca8 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/libLLVM-12.so
    #10 0x00007f8adde37af9 in LLVMRunPassManager () from /usr/lib/libLLVM-12.so
    #11 0x00007f8ae2a088d1 in rustc_codegen_llvm::back::write::optimize () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #12 0x00007f8ae28ae491 in rustc_codegen_ssa::back::write::execute_work_item () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #13 0x00007f8ae2937f30 in std::sys_common::backtrace::__rust_begin_short_backtrace () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #14 0x00007f8ae299f257 in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #15 0x00007f8ae1cf28c3 in std::sys::unix::thread::Thread::new::thread_start () from /usr/lib/libstd-13e65b318180c5e7.so
    #16 0x00007f8adccbe1c7 in start_thread (arg=0x7f8aae4b6700) at pthread_create.c:309
    #17 0x00007f8ae19d0b6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 4 (Thread 0x7f8aae6b7700 (LWP 15126)):
    #0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
    #1  0x00007f8ae1d008ca in std::sync::mpsc::blocking::WaitToken::wait () from /usr/lib/libstd-13e65b318180c5e7.so
    #2  0x00007f8ae299bda9 in std::sync::mpsc::shared::Packet<T>::recv () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #3  0x00007f8ae292ee2c in rustc_codegen_ssa::back::write::start_executing_work::{{closure}} () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #4  0x00007f8ae293820b in std::sys_common::backtrace::__rust_begin_short_backtrace () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #5  0x00007f8ae299eec2 in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #6  0x00007f8ae1cf28c3 in std::sys::unix::thread::Thread::new::thread_start () from /usr/lib/libstd-13e65b318180c5e7.so
    #7  0x00007f8adccbe1c7 in start_thread (arg=0x7f8aae6b7700) at pthread_create.c:309
    #8  0x00007f8ae19d0b6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 3 (Thread 0x7f8adb576700 (LWP 15125)):
    #0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    #1  0x00007f8ae50b9eb0 in jobserver::HelperState::for_each_request () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #2  0x00007f8ae50ba32c in std::sys_common::backtrace::__rust_begin_short_backtrace () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #3  0x00007f8ae50bb74a in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #4  0x00007f8ae1cf28c3 in std::sys::unix::thread::Thread::new::thread_start () from /usr/lib/libstd-13e65b318180c5e7.so
    #5  0x00007f8adccbe1c7 in start_thread (arg=0x7f8adb576700) at pthread_create.c:309
    #6  0x00007f8ae19d0b6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 2 (Thread 0x7f8adbd77700 (LWP 15123)):
    #0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
    #1  0x00007f8ae197141f in _L_lock_9249 () at malloc.c:5175
    #2  0x00007f8ae196eea2 in __GI___libc_malloc (bytes=140234238984224) at malloc.c:2884
    #3  0x00007f8ae60f5339 in _dl_map_object_deps (map=0x7f8ae62e74d0, preloads=<optimized out>, npreloads=<optimized out>, trace_mode=0, open_mode=-2147483648)
        at dl-deps.c:511
    #4  0x00007f8ae60fb4b1 in dl_open_worker (a=0x7f8ae6302950) at dl-open.c:261
    #5  0x00007f8ae60f7362 in _dl_catch_error (objname=0x7f8ae6302998, errstring=0x7f8ae63029a0, mallocedp=0x7f8ae63029af, 
        operate=0x7f8ae60fb3a0 <dl_open_worker>, args=0x7f8ae6302950) at dl-error.c:187
    #6  0x00007f8ae60fae6a in _dl_open (file=0x7f8ae1a1ee22 "libgcc_s.so.1", mode=-2147483647, caller_dlopen=0x7f8ae19ddb75 <init+21>, nsid=-2, argc=204, 
        argv=<optimized out>, env=0x7fff7d12a550) at dl-open.c:650
    #7  0x00007f8ae1a06fb2 in do_dlopen (ptr=0x7f8ae6302b90) at dl-libc.c:87
    #8  0x00007f8ae60f7362 in _dl_catch_error (objname=0x7f8ae6302b68, errstring=0x7f8ae6302b70, mallocedp=0x7f8ae6302b7f, operate=0x7f8ae1a06f70 <do_dlopen>, 
        args=0x7f8ae6302b90) at dl-error.c:187
    #9  0x00007f8ae1a0704f in dlerror_run (operate=<optimized out>, args=<optimized out>) at dl-libc.c:46
    #10 0x00007f8ae1a070c1 in __GI___libc_dlopen_mode (name=<optimized out>, mode=<optimized out>) at dl-libc.c:163
    #11 0x00007f8ae19ddb75 in init () at ../sysdeps/x86_64/backtrace.c:52
    #12 0x00007f8adccc3be3 in pthread_once () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_once.S:103
    #13 0x00007f8ae19ddc94 in __GI___backtrace (array=<optimized out>, size=256) at ../sysdeps/x86_64/backtrace.c:103
    #14 0x00007f8ae2684273 in rustc_driver::signal_handler::print_stack_trace () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #15 <signal handler called>
    #16 0x00007f8ae196babd in malloc_consolidate (av=0x7f8ad4000020) at malloc.c:4162
    #17 malloc_consolidate (av=0x7f8ad4000020) at malloc.c:4100
    #18 0x00007f8ae196c538 in _int_free (av=0x7f8ad4000020, p=0x7f8ad4aa9e40, have_lock=0) at malloc.c:4054
    #19 0x00007f8ae26eb08f in core::ptr::drop_in_place<rustc_data_structures::sync::WorkerLocal<rustc_middle::arena::Arena>> ()
       from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #20 0x00007f8ae26de3ad in core::ptr::drop_in_place<rustc_interface::queries::Queries> () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #21 0x00007f8ae26cab2e in rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #22 0x00007f8ae268dafa in rustc_span::with_source_map () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #23 0x00007f8ae26c8e4c in scoped_tls::ScopedKey<T>::set () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #24 0x00007f8ae2693c49 in std::sys_common::backtrace::__rust_begin_short_backtrace () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #25 0x00007f8ae26fe9d0 in core::ops::function::FnOnce::call_once{{vtable-shim}} () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #26 0x00007f8ae1cf28c3 in std::sys::unix::thread::Thread::new::thread_start () from /usr/lib/libstd-13e65b318180c5e7.so
    #27 0x00007f8adccbe1c7 in start_thread (arg=0x7f8adbd77700) at pthread_create.c:309
    #28 0x00007f8ae19d0b6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

    Thread 1 (Thread 0x7f8ae6181c40 (LWP 15122)):
    #0  0x00007f8adccbf6bf in pthread_join (threadid=140234370545408, thread_return=0x0) at pthread_join.c:92
    #1  0x00007f8ae1cf2a7d in std::sys::unix::thread::Thread::join () from /usr/lib/libstd-13e65b318180c5e7.so
    #2  0x00007f8ae26fdd5a in std::thread::JoinHandle<T>::join () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #3  0x00007f8ae2684701 in rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #4  0x00007f8ae2674177 in rustc_driver::RunCompiler::run () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #5  0x00007f8ae26926b7 in <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once ()
       from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #6  0x00007f8ae267d045 in rustc_driver::main () from /usr/lib/librustc_driver-07f7f8139fa79bdb.so
    #7  0x000055b5f0a3e8dd in rustc_main::main ()
    #8  0x000055b5f0a3e8c3 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
    #9  0x000055b5f0a3e919 in std::rt::lang_start::{{closure}} ()
    #10 0x00007f8ae1cd1bb1 in std::rt::lang_start_internal () from /usr/lib/libstd-13e65b318180c5e7.so
    #11 0x000055b5f0a3e902 in main ()
    (gdb) 

```

**Comment by OSS542** [comment]
issue does not occur with rustc-1.59.0
