### ISSUE TITLE
ICE: index out of bound in dep_graph

### ISSUE THREAD

**Issue by hube12** [rust-lang/rust#92749]
I can not provide the code as this is a private project, this came after a single line change, I have yet to pin it down, seems my project might be too large (about 1000 crates dependencies)

### Error output & Backtrace

```Rust
thread 'rustc' panicked at 'index out of bounds: the len is 499 but the index is 520', compiler\rustc_query_impl\src\on_disk_cache.rs:726:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.60.0-nightly (092e1c9d2 2022-01-09) running on x86_64-pc-windows-msvc
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type rlib --crate-type cdylib --crate-type staticlib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 189226', /rustc/092e1c9d23158d81be27bb6f71bdd0c6282478fb\compiler\rustc_query_system\src\dep_graph\graph.rs:430:25
stack backtrace:
   0:     0x7ffd2b42609f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8a5458b86b45e723
   1:     0x7ffd2b45510a - core::fmt::write::h4cc163364c7ea692
   2:     0x7ffd2b417308 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::hced679b6e028b653
   3:     0x7ffd2b429acb - std::panicking::take_hook::h6d890d8a6a8e4d12
   4:     0x7ffd2b4295c4 - std::panicking::take_hook::h6d890d8a6a8e4d12
   5:     0x7ffd04e53b96 - <rustc_middle[2f71778518b1fb16]::ty::SymbolName as core[26170da0a386b13]::fmt::Display>::fmt
   6:     0x7ffd2b42a1f6 - std::panicking::rust_panic_with_hook::h24316f542539d322
   7:     0x7ffd2b429ffb - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h1e9188dfc7d90677
   8:     0x7ffd2b4269e7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8a5458b86b45e723
   9:     0x7ffd2b429cf9 - rust_begin_unwind
  10:     0x7ffd2b487a20 - core::panicking::panic_fmt::he148b69876cdaf6a
  11:     0x7ffd09312b13 - <rustc_middle[2f71778518b1fb16]::dep_graph::dep_node::DepKind as rustc_query_system[d4010243dc2f5113]::dep_graph::DepKind>::debug_node
  12:     0x7ffd0926242c - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::RegionHighlightMode>::highlighting_bound_region
  13:     0x7ffd0927bead - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::TraitRefPrintOnlyTraitName as core[26170da0a386b13]::fmt::Display>::fmt
  14:     0x7ffd0925693d - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::RegionHighlightMode>::highlighting_bound_region
  15:     0x7ffd0927d217 - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::TraitRefPrintOnlyTraitName as core[26170da0a386b13]::fmt::Display>::fmt
  16:     0x7ffd0925693d - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::RegionHighlightMode>::highlighting_bound_region
  17:     0x7ffd0927d217 - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::TraitRefPrintOnlyTraitName as core[26170da0a386b13]::fmt::Display>::fmt
  18:     0x7ffd0925693d - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::RegionHighlightMode>::highlighting_bound_region
  19:     0x7ffd0927d217 - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::TraitRefPrintOnlyTraitName as core[26170da0a386b13]::fmt::Display>::fmt
  20:     0x7ffd0925693d - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::RegionHighlightMode>::highlighting_bound_region
  21:     0x7ffd0927d217 - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::TraitRefPrintOnlyTraitName as core[26170da0a386b13]::fmt::Display>::fmt
  22:     0x7ffd0925693d - <rustc_middle[2f71778518b1fb16]::ty::print::pretty::RegionHighlightMode>::highlighting_bound_region
  23:     0x7ffd092c6087 - <rustc_middle[2f71778518b1fb16]::ty::context::TyCtxt>::def_path_str_with_substs
  24:     0x7ffd092c5f22 - <rustc_middle[2f71778518b1fb16]::ty::context::TyCtxt>::def_path_str
  25:     0x7ffd0867d8ac - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  26:     0x7ffd0868c73c - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  27:     0x7ffd086c5672 - <alloc[3974398b5b04c87a]::vec::Vec<u8> as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  28:     0x7ffd082b2415 - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  29:     0x7ffd084d19b4 - <rustc_query_impl[6c4574912974e63d]::Queries>::new
  30:     0x7ffd0864620e - <rustc_query_impl[6c4574912974e63d]::plumbing::QueryCtxt>::try_print_query_stack
  31:     0x7ffd050041f7 - rustc_interface[7f5a88b12e67523c]::interface::try_print_query_stack
  32:     0x7ffd04e607c7 - rustc_driver[f07e21a839bde537]::report_ice
  33:     0x7ffd2b42a1f6 - std::panicking::rust_panic_with_hook::h24316f542539d322
  34:     0x7ffd2b429ffb - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h1e9188dfc7d90677
  35:     0x7ffd2b4269e7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8a5458b86b45e723
  36:     0x7ffd2b429cf9 - rust_begin_unwind
  37:     0x7ffd2b487a20 - core::panicking::panic_fmt::he148b69876cdaf6a
  38:     0x7ffd2b4879e7 - core::panicking::panic_bounds_check::h82785cb20c0714b8
  39:     0x7ffd086e8b5b - <rustc_span[3ba4d84bf078f5fd]::span_encoding::Span as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  40:     0x7ffd086707dc - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  41:     0x7ffd0854bc5a - rustc_query_impl[6c4574912974e63d]::query_callbacks::diagnostic_hir_wf_check
  42:     0x7ffd084ed843 - <rustc_middle[2f71778518b1fb16]::ty::adt::AdtSizedConstraint as rustc_query_impl[6c4574912974e63d]::values::Value>::from_cycle_error
  43:     0x7ffd084d9b84 - <rustc_query_impl[6c4574912974e63d]::Queries as rustc_middle[2f71778518b1fb16]::ty::query::QueryEngine>::try_mark_green
  44:     0x7ffd08660809 - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7ffd08562a2c - <rustc_query_impl[6c4574912974e63d]::on_disk_cache::OnDiskCache>::load_side_effects
  46:     0x7ffd086608f8 - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  47:     0x7ffd085116ba - RNvXsd_NtCs9ikbLDu0Buz_16rustc_query_impl13on_disk_cacheRINtNtNtNtCsf0Q2M0kRAe5_3std11collections4hash3set7HashSetNtNtCs57tXtMsbfLR_10rustc_span6def_id10LocalDefIdINtNtCscFFh8D4BCV_4core4hash18BuildHasherDefaultNtCscD6UhMY0VlW_10rustc_hash8FxHasherEEINtNt
  48:     0x7ffd084f98d6 - <rustc_middle[2f71778518b1fb16]::mir::interpret::GlobalId as rustc_query_impl[6c4574912974e63d]::keys::Key>::default_span
  49:     0x7ffd084c1670 - <rustc_query_impl[6c4574912974e63d]::Queries>::as_dyn
  50:     0x7ffd08512ee3 - RNvXsd_NtCs9ikbLDu0Buz_16rustc_query_impl13on_disk_cacheRINtNtNtNtCsf0Q2M0kRAe5_3std11collections4hash3set7HashSetNtNtCs57tXtMsbfLR_10rustc_span6def_id10LocalDefIdINtNtCscFFh8D4BCV_4core4hash18BuildHasherDefaultNtCscD6UhMY0VlW_10rustc_hash8FxHasherEEINtNt
  51:     0x7ffd08660a03 - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  52:     0x7ffd084da276 - <rustc_query_impl[6c4574912974e63d]::Queries as rustc_middle[2f71778518b1fb16]::ty::query::QueryEngine>::try_mark_green
  53:     0x7ffd08660809 - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  54:     0x7ffd085116ba - RNvXsd_NtCs9ikbLDu0Buz_16rustc_query_impl13on_disk_cacheRINtNtNtNtCsf0Q2M0kRAe5_3std11collections4hash3set7HashSetNtNtCs57tXtMsbfLR_10rustc_span6def_id10LocalDefIdINtNtCscFFh8D4BCV_4core4hash18BuildHasherDefaultNtCscD6UhMY0VlW_10rustc_hash8FxHasherEEINtNt
  55:     0x7ffd08512e2c - RNvXsd_NtCs9ikbLDu0Buz_16rustc_query_impl13on_disk_cacheRINtNtNtNtCsf0Q2M0kRAe5_3std11collections4hash3set7HashSetNtNtCs57tXtMsbfLR_10rustc_span6def_id10LocalDefIdINtNtCscFFh8D4BCV_4core4hash18BuildHasherDefaultNtCscD6UhMY0VlW_10rustc_hash8FxHasherEEINtNt
  56:     0x7ffd0866d035 - <&[(rustc_middle[2f71778518b1fb16]::ty::Predicate, rustc_span[3ba4d84bf078f5fd]::span_encoding::Span)] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  57:     0x7ffd084fdc9d - <rustc_middle[2f71778518b1fb16]::mir::interpret::GlobalId as rustc_query_impl[6c4574912974e63d]::keys::Key>::default_span
  58:     0x7ffd0855bbfb - <rustc_query_impl[6c4574912974e63d]::on_disk_cache::OnDiskCache>::load_side_effects
  59:     0x7ffd082a98a4 - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  60:     0x7ffd086dd531 - <alloc[3974398b5b04c87a]::vec::Vec<u8> as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  61:     0x7ffd085d098f - <&[rustc_ast[a9885e384f78a034]::ast::InlineAsmTemplatePiece] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  62:     0x7ffd083d78bb - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  63:     0x7ffd0849bc03 - <rustc_query_impl[6c4574912974e63d]::Queries>::as_dyn
  64:     0x7ffd0843acfa - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  65:     0x7ffd084d4384 - <rustc_query_impl[6c4574912974e63d]::Queries as rustc_middle[2f71778518b1fb16]::ty::query::QueryEngine>::try_mark_green
  66:     0x7ffd0799b73c - rustc_ty_utils[701a07e3860b97ae]::instance::provide
  67:     0x7ffd0799a276 - rustc_ty_utils[701a07e3860b97ae]::instance::provide
  68:     0x7ffd086de643 - <alloc[3974398b5b04c87a]::vec::Vec<u8> as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  69:     0x7ffd083b559d - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  70:     0x7ffd0849b8f2 - <rustc_query_impl[6c4574912974e63d]::Queries>::as_dyn
  71:     0x7ffd08417afd - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  72:     0x7ffd084d55d1 - <rustc_query_impl[6c4574912974e63d]::Queries as rustc_middle[2f71778518b1fb16]::ty::query::QueryEngine>::try_mark_green
  73:     0x7ffd093767a9 - <rustc_middle[2f71778518b1fb16]::ty::instance::Instance>::resolve_opt_const_arg
  74:     0x7ffd09367b42 - <rustc_middle[2f71778518b1fb16]::ty::instance::Instance>::resolve
  75:     0x7ffd073e1ed8 - <rustc_monomorphize[2029d4b3572cf9a4]::collector::MirNeighborCollector as rustc_middle[2f71778518b1fb16]::mir::visit::Visitor>::visit_terminator
  76:     0x7ffd073e4b27 - <rustc_monomorphize[2029d4b3572cf9a4]::collector::RootCollector as rustc_hir[b1a7af8ade03b81]::itemlikevisit::ItemLikeVisitor>::visit_impl_item
  77:     0x7ffd073ddf9e - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  78:     0x7ffd073de275 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  79:     0x7ffd073de275 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  80:     0x7ffd073de275 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  81:     0x7ffd073de275 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  82:     0x7ffd073de275 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  83:     0x7ffd073de275 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  84:     0x7ffd073c6eee - <core[26170da0a386b13]::option::Option<rustc_middle[2f71778518b1fb16]::middle::privacy::AccessLevel> as rustc_privacy[455f77350644bcc9]::VisibilityLike>::new_min
  85:     0x7ffd073dc4f3 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::MonoItemPlacement as core[26170da0a386b13]::fmt::Debug>::fmt
  86:     0x7ffd073d7193 - <rustc_monomorphize[2029d4b3572cf9a4]::partitioning::default::DefaultPartitioning as rustc_monomorphize[2029d4b3572cf9a4]::partitioning::Partitioner>::internalize_symbols
  87:     0x7ffd086dcec3 - <alloc[3974398b5b04c87a]::vec::Vec<u8> as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  88:     0x7ffd0861190a - <&[rustc_ast[a9885e384f78a034]::ast::InlineAsmTemplatePiece] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  89:     0x7ffd084bef1c - <rustc_query_impl[6c4574912974e63d]::Queries>::as_dyn
  90:     0x7ffd083af57f - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  91:     0x7ffd0844508a - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  92:     0x7ffd084d4cde - <rustc_query_impl[6c4574912974e63d]::Queries as rustc_middle[2f71778518b1fb16]::ty::query::QueryEngine>::try_mark_green
  93:     0x7ffd087add91 - rustc_codegen_ssa[f9514a1d3bdc705a]::back::symbol_export::crates_export_threshold
  94:     0x7ffd086da746 - <alloc[3974398b5b04c87a]::vec::Vec<u8> as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  95:     0x7ffd085fd1f1 - <&[rustc_ast[a9885e384f78a034]::ast::InlineAsmTemplatePiece] as rustc_serialize[49e3c0a9d6544bb9]::serialize::Decodable<rustc_query_impl[6c4574912974e63d]::on_disk_cache::CacheDecoder>>::decode
  96:     0x7ffd084be9e7 - <rustc_query_impl[6c4574912974e63d]::Queries>::as_dyn
  97:     0x7ffd0837d064 - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  98:     0x7ffd084145e3 - <rustc_mir_dataflow[f2de7501e98a9638]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[f2de7501e98a9638]::framework::AnalysisDomain>::initialize_start_block
  99:     0x7ffd089df805 - <rustc_metadata[3eb0ec198fe1229e]::rmeta::encoder::EncodeContext as rustc_middle[2f71778518b1fb16]::ty::codec::TyEncoder>::encode_alloc_id
 100:     0x7ffd089f62c0 - rustc_metadata[3eb0ec198fe1229e]::rmeta::encoder::encode_metadata
 101:     0x7ffd08a43705 - <u32 as rustc_metadata[3eb0ec198fe1229e]::rmeta::table::FixedSizeEncoding>::write_to_bytes_at
 102:     0x7ffd089f5973 - rustc_metadata[3eb0ec198fe1229e]::rmeta::encoder::encode_metadata
 103:     0x7ffd04f58a7c - <rustc_interface[7f5a88b12e67523c]::queries::Queries>::ongoing_codegen
 104:     0x7ffd04e056ef - <rustc_driver[f07e21a839bde537]::args::Error as core[26170da0a386b13]::fmt::Debug>::fmt
 105:     0x7ffd04de2445 - <sha2[849c876cda4afd35]::sha512::Sha512Trunc224 as std[aedf39e63ec59993]::io::Write>::flush
 106:     0x7ffd04e03041 - <sha2[849c876cda4afd35]::sha512::Sha512Trunc224 as std[aedf39e63ec59993]::io::Write>::flush
 107:     0x7ffd04de5a17 - <sha2[849c876cda4afd35]::sha512::Sha512Trunc224 as std[aedf39e63ec59993]::io::Write>::flush
 108:     0x7ffd04de465c - <sha2[849c876cda4afd35]::sha512::Sha512Trunc224 as std[aedf39e63ec59993]::io::Write>::flush
 109:     0x7ffd04e08fb8 - <rustc_middle[2f71778518b1fb16]::ty::SymbolName as core[26170da0a386b13]::fmt::Display>::fmt
 110:     0x7ffd2b439bac - std::sys::windows::thread::Thread::new::h9448705b64f509fb
 111:     0x7ffd64667034 - BaseThreadInitThunk
 112:     0x7ffd65f42651 - RtlUserThreadStart
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.60.0-nightly (092e1c9d2 2022-01-09) running on x86_64-pc-windows-msvc
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type rlib --crate-type cdylib --crate-type staticlib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
thread panicked while panicking. aborting.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (092e1c9d2 2022-01-09)
binary: rustc
commit-hash: 092e1c9d23158d81be27bb6f71bdd0c6282478fb
commit-date: 2022-01-09
host: x86_64-pc-windows-msvc
release: 1.60.0-nightly
LLVM version: 13.0.0

```

**Comment by hube12** [comment]
This compiles fine on 1.57.0 stable

**Comment by Aaron1011** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/92533

**Comment by Enselic** [comment]
Closing since claimed fixed in https://github.com/rust-lang/rust/issues/92749#issuecomment-1009459723 more than a year ago
