### ISSUE TITLE
Internal Compiler Error

### ISSUE THREAD

**Issue by deceneu3** [rust-lang/rust#92815]
First complication try is fine, but second one get into error
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (1409c015b 2022-01-11)
binary: rustc
commit-hash: 1409c015b44a4d4d38bef2250b2a37c17b8b7463
commit-date: 2022-01-11
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0
```

### Error output

```
 erdpy  --verbose contract build
INFO:projects.core:build_project.directory: /cry/elrond/local-esdt-and-nft-25
INFO:projects.core:build_project.debug: False
INFO:myprocess:run_process: ['rustc', '--version'], in folder: None
INFO:myprocess:Successful run. Output:
rustc 1.60.0-nightly (1409c015b 2022-01-11)

warning: Hard linking files in the incremental compilation cache failed. Copying files instead. Consider moving the cache directory to a file system which supports hard linking
 in session dir `/cry/elrond/local-esdt-and-nft-25/meta/target/debug/incremental/local_esdt_and_nft-34v12lehhodgn/s-g61hya920h-gk865z-working`

warning: Error deleting lock file for incremental compilation session directory `/cry/elrond/local-esdt-and-nft-25/meta/target/debug/incremental/local_esdt_and_nft-34v12lehhodg
n/s-g61e85brkz-eldyrr.lock`: Text file busy (os error 26)

warning: `local-esdt-and-nft` (lib) generated 2 warnings
Compiling local-esdt-and-nft-meta v0.0.0 (/cry/elrond/local-esdt-and-nft-25/meta)
warning: Hard linking files in the incremental compilation cache failed. Copying files instead. Consider moving the cache directory to a file system which supports hard linking
 in session dir `/cry/elrond/local-esdt-and-nft-25/meta/target/debug/incremental/local_esdt_and_nft_meta-1wbaacaadaaoz/s-g61i0ga6xt-1s9pmy4-working`

warning: Error deleting lock file for incremental compilation session directory `/cry/elrond/local-esdt-and-nft-25/meta/target/debug/incremental/local_esdt_and_nft_meta-1wbaaca
adaaoz/s-g61hyeotc1-457gf6.lock`: Text file busy (os error 26)

thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder.rs:1640:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (1409c015b 2022-01-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 228', /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/compiler/rustc_query_system/src/dep_graph/graph.rs:430:25
stack backtrace:
0:     0x7fe3576e1e1c - std::backtrace_rs::backtrace::libunwind::trace::hb1b285558cdf1acb
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
1:     0x7fe3576e1e1c - std::backtrace_rs::backtrace::trace_unsynchronized::h2be3a053383c6ddb
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:     0x7fe3576e1e1c - std::sys_common::backtrace::_print_fmt::h4666212504fe1948
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys_common/backtrace.rs:67:5
3:     0x7fe3576e1e1c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf87e400b323a5828
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys_common/backtrace.rs:46:22
4:     0x7fe357742b0c - core::fmt::write::hddbdc65bfe2ed19b
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/core/src/fmt/mod.rs:1168:17
5:     0x7fe3576d1163 - std::io::Write::write_fmt::h24b6448ccd9288f5
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/io/mod.rs:1653:15
6:     0x7fe3576e62e2 - std::sys_common::backtrace::_print::h8639259e319221e9
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys_common/backtrace.rs:49:5
7:     0x7fe3576e62e2 - std::sys_common::backtrace::print::h8045791d03f3fd70
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys_common/backtrace.rs:36:9
8:     0x7fe3576e62e2 - std::panicking::default_hook::{{closure}}::h95eed860122e08c9
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:211:50
9:     0x7fe3576e5ec5 - std::panicking::default_hook::h90724d856dfe810a
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:228:9
10:     0x7fe357ed63d1 - rustc_driver[8714e23c1e821b1]::DEFAULT_HOOK::{closure#0}::{closure#0}
11:     0x7fe3576e6a95 - std::panicking::rust_panic_with_hook::hd2825d994660b622
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:610:17
12:     0x7fe3576e6790 - std::panicking::begin_panic_handler::{{closure}}::h3fa9e0f37671e2c6
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:502:13
13:     0x7fe3576e22c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hbfbfb744d8822e62
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys_common/backtrace.rs:139:18
14:     0x7fe3576e64c9 - rust_begin_unwind
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:498:5
15:     0x7fe3576ae0d1 - core::panicking::panic_fmt::hf0b0769354118e47
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/core/src/panicking.rs:110:14
16:     0x7fe3598ad7cc - <rustc_middle[b64a3ba39b863cb5]::dep_graph::dep_node::DepKind as rustc_query_system[931da4c172eb8020]::dep_graph::DepKind>::read_deps::<<rustc_query_sy
stem[931da4c172eb8020]::dep_graph::graph::DepGraph<rustc_middle[b64a3ba39b863cb5]::dep_graph::dep_node::DepKind>>::read_index::{closure#0}>
17:     0x7fe358978d17 - <rustc_span[8f278cc4e436f278]::def_id::DefId as rustc_query_impl[87cafe84cde3826e]::keys::Key>::default_span
18:     0x7fe358978c65 - <rustc_span[8f278cc4e436f278]::def_id::LocalDefId as rustc_query_impl[87cafe84cde3826e]::keys::Key>::default_span
19:     0x7fe35893fdd8 - rustc_query_impl[87cafe84cde3826e]::make_query::typeck
20:     0x7fe358721fa7 - <rustc_query_system[931da4c172eb8020]::query::plumbing::QueryState<rustc_middle[b64a3ba39b863cb5]::dep_graph::dep_node::DepKind, rustc_span[8f278cc4e43
6f278]::def_id::LocalDefId>>::try_collect_active_jobs::<rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt>
21:     0x7fe3587d46e9 - <rustc_query_impl[87cafe84cde3826e]::Queries>::try_collect_active_jobs
22:     0x7fe3588de4f4 - <rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt>::try_print_query_stack
23:     0x7fe357fc9492 - rustc_interface[3672e0c3fff8aeee]::interface::try_print_query_stack
24:     0x7fe357ed67c7 - rustc_driver[8714e23c1e821b1]::report_ice
25:     0x7fe3576e6a95 - std::panicking::rust_panic_with_hook::hd2825d994660b622
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:610:17
26:     0x7fe3576e6790 - std::panicking::begin_panic_handler::{{closure}}::h3fa9e0f37671e2c6
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:502:13
27:     0x7fe3576e22c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hbfbfb744d8822e62
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys_common/backtrace.rs:139:18
28:     0x7fe3576e64c9 - rust_begin_unwind
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/panicking.rs:498:5
29:     0x7fe3576ae0d1 - core::panicking::panic_fmt::hf0b0769354118e47
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/core/src/panicking.rs:110:14
30:     0x7fe35773f901 - core::panicking::panic_display::h175ab086714dcf84
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/core/src/panicking.rs:65:5
31:     0x7fe35773f8ab - core::panicking::panic_str::ha876d77f7a624bbb
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/core/src/panicking.rs:56:5
32:     0x7fe3576adfc6 - core::option::expect_failed::hc754100a40941261
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/core/src/option.rs:1817:5
33:     0x7fe358b52d18 - <rustc_metadata[617b01dbfa2c5230]::creader::CStore as rustc_session[ff261f91cefa7bd8]::cstore::CrateStore>::expn_hash_to_expn_id
34:     0x7fe35a322568 - <rustc_span[8f278cc4e436f278]::hygiene::ExpnId as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk_c
ache::CacheDecoder>>::decode
35:     0x7fe35a3264d5 - <rustc_span[8f278cc4e436f278]::hygiene::SyntaxContextData as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]
::on_disk_cache::CacheDecoder>>::decode
36:     0x7fe359872fb1 - <rustc_query_impl[87cafe84cde3826e]::on_disk_cache::CacheDecoder as rustc_middle[b64a3ba39b863cb5]::ty::codec::TyDecoder>::with_position::<<rustc_span[
8f278cc4e436f278]::hygiene::SyntaxContext as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk_cache::CacheDecoder>>::decode::
{closure#0}::{closure#0}, core[cd12ad7e3bc8284]::result::Result<rustc_span[8f278cc4e436f278]::hygiene::SyntaxContextData, alloc[da4e7b9aec230577]::string::String>>
37:     0x7fe3598ae4f1 - <rustc_span[8f278cc4e436f278]::span_encoding::Span as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_di
sk_cache::CacheDecoder>>::decode
38:     0x7fe3598a960b - <rustc_middle[b64a3ba39b863cb5]::ty::VariantDef as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk_
cache::CacheDecoder>>::decode
39:     0x7fe35986c907 - <rustc_query_impl[87cafe84cde3826e]::on_disk_cache::CacheDecoder as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decoder>::read_seq::<alloc[da4e7b9aec
230577]::vec::Vec<rustc_middle[b64a3ba39b863cb5]::ty::VariantDef>, <alloc[da4e7b9aec230577]::vec::Vec<rustc_middle[b64a3ba39b863cb5]::ty::VariantDef> as rustc_serialize[41a327d
4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk_cache::CacheDecoder>>::decode::{closure#0}>
40:     0x7fe35a2fb907 - <rustc_middle[b64a3ba39b863cb5]::ty::adt::AdtDef as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk
_cache::CacheDecoder>>::decode
41:     0x7fe35985481b - <rustc_middle[b64a3ba39b863cb5]::ty::sty::TyKind as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk
_cache::CacheDecoder>>::decode
42:     0x7fe3598a15f1 - <&rustc_middle[b64a3ba39b863cb5]::ty::TyS as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk_cache:
:CacheDecoder>>::decode
43:     0x7fe3598a14bb - <&rustc_middle[b64a3ba39b863cb5]::ty::TyS as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826e]::on_disk_cache:
:CacheDecoder>>::decode
44:     0x7fe359871316 - <rustc_query_impl[87cafe84cde3826e]::on_disk_cache::CacheDecoder as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decoder>::read_map::<std[4f17e28e306b
5344]::collections::hash::map::HashMap<rustc_hir[ef4a836978a76beb]::hir_id::ItemLocalId, &rustc_middle[b64a3ba39b863cb5]::ty::TyS, core[cd12ad7e3bc8284]::hash::BuildHasherDefau
lt<rustc_hash[18a65e35c2c7c4f3]::FxHasher>>, <std[4f17e28e306b5344]::collections::hash::map::HashMap<rustc_hir[ef4a836978a76beb]::hir_id::ItemLocalId, &rustc_middle[b64a3ba39b8
63cb5]::ty::TyS, core[cd12ad7e3bc8284]::hash::BuildHasherDefault<rustc_hash[18a65e35c2c7c4f3]::FxHasher>> as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query
_impl[87cafe84cde3826e]::on_disk_cache::CacheDecoder>>::decode::{closure#0}>
45:     0x7fe35a2fbba1 - <rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde3826
e]::on_disk_cache::CacheDecoder>>::decode::{closure#0}
46:     0x7fe35a2fabe6 - <&rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults as rustc_serialize[41a327d4cb5bf9c7]::serialize::Decodable<rustc_query_impl[87cafe84cde382
6e]::on_disk_cache::CacheDecoder>>::decode
47:     0x7fe35a3196f9 - <rustc_query_impl[87cafe84cde3826e]::on_disk_cache::OnDiskCache>::try_load_query_result::<&rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults>
48:     0x7fe35a392c3b - <rustc_middle[b64a3ba39b863cb5]::dep_graph::dep_node::DepKind as rustc_query_system[931da4c172eb8020]::dep_graph::DepKind>::with_deps::<rustc_query_sys
tem[931da4c172eb8020]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt, rustc_span[8f278cc4e436f278]::def_id::Lo
calDefId, &rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults>::{closure#0}, core[cd12ad7e3bc8284]::option::Option<&rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckR
esults>>
49:     0x7fe35a335fa6 - <rustc_query_system[931da4c172eb8020]::dep_graph::graph::DepGraph<rustc_middle[b64a3ba39b863cb5]::dep_graph::dep_node::DepKind>>::with_query_deserializ
ation::<rustc_query_system[931da4c172eb8020]::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt, rustc_span[8f278c
c4e436f278]::def_id::LocalDefId, &rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults>::{closure#0}, core[cd12ad7e3bc8284]::option::Option<&rustc_middle[b64a3ba39b863cb5
]::ty::context::TypeckResults>>
50:     0x7fe35a25d3e8 - rustc_query_system[931da4c172eb8020]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt
, rustc_span[8f278cc4e436f278]::def_id::LocalDefId, &rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults>
51:     0x7fe3597d7738 - rustc_query_system[931da4c172eb8020]::query::plumbing::try_execute_query::<rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt, rustc_query_system[
931da4c172eb8020]::query::caches::DefaultCache<rustc_span[8f278cc4e436f278]::def_id::LocalDefId, &rustc_middle[b64a3ba39b863cb5]::ty::context::TypeckResults>>
52:     0x7fe35984a2ac - <rustc_query_impl[87cafe84cde3826e]::Queries as rustc_middle[b64a3ba39b863cb5]::ty::query::QueryEngine>::typeck
53:     0x7fe359c53e09 - <rustc_middle[b64a3ba39b863cb5]::ty::context::TyCtxt>::typeck_body
54:     0x7fe3594cd18a - rustc_hir[ef4a836978a76beb]::intravisit::walk_item::<rustc_passes[73f857bfa8e55a12]::dead::MarkSymbolVisitor>
55:     0x7fe3594fb463 - rustc_passes[73f857bfa8e55a12]::dead::check_crate
56:     0x7fe359dc696c - <core[cd12ad7e3bc8284]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3672e0c3fff8aeee]::passes::analysis::{closure#5}::{closure#0}::{closure#1}
> as core[cd12ad7e3bc8284]::ops::function::FnOnce<()>>::call_once
57:     0x7fe359dc82be - <core[cd12ad7e3bc8284]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[3672e0c3fff8aeee]::passes::analysis::{closure#5}::{closure#0}> as core[cd1
2ad7e3bc8284]::ops::function::FnOnce<()>>::call_once
58:     0x7fe359dc46b8 - <rustc_session[ff261f91cefa7bd8]::session::Session>::time::<(), rustc_interface[3672e0c3fff8aeee]::passes::analysis::{closure#5}>
59:     0x7fe359d9ee7c - rustc_interface[3672e0c3fff8aeee]::passes::analysis
60:     0x7fe35a363726 - <rustc_query_system[931da4c172eb8020]::dep_graph::graph::DepGraph<rustc_middle[b64a3ba39b863cb5]::dep_graph::dep_node::DepKind>>::with_task::<rustc_mid
dle[b64a3ba39b863cb5]::ty::context::TyCtxt, (), core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>
61:     0x7fe35a2c81f3 - rustc_data_structures[9b4a9334ecec954f]::stack::ensure_sufficient_stack::<(core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::Er
rorReported>, rustc_query_system[931da4c172eb8020]::dep_graph::graph::DepNodeIndex), rustc_query_system[931da4c172eb8020]::query::plumbing::execute_job<rustc_query_impl[87cafe8
4cde3826e]::plumbing::QueryCtxt, (), core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>::{closure#3}>
62:     0x7fe35a2488f6 - rustc_query_system[931da4c172eb8020]::query::plumbing::try_execute_query::<rustc_query_impl[87cafe84cde3826e]::plumbing::QueryCtxt, rustc_query_system[
931da4c172eb8020]::query::caches::DefaultCache<(), core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>>
63:     0x7fe35a2a2ca5 - rustc_query_system[931da4c172eb8020]::query::plumbing::get_query::<rustc_query_impl[87cafe84cde3826e]::queries::analysis, rustc_query_impl[87cafe84cde3
826e]::plumbing::QueryCtxt>
64:     0x7fe359d7ff42 - <rustc_interface[3672e0c3fff8aeee]::interface::Compiler>::enter::<rustc_driver[8714e23c1e821b1]::run_compiler::{closure#1}::{closure#2}, core[cd12ad7e3
bc8284]::result::Result<core[cd12ad7e3bc8284]::option::Option<rustc_interface[3672e0c3fff8aeee]::queries::Linker>, rustc_errors[f0173504293ba049]::ErrorReported>>
65:     0x7fe359d61b6c - rustc_span[8f278cc4e436f278]::with_source_map::<core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>, rustc_interfa
ce[3672e0c3fff8aeee]::interface::create_compiler_and_run<core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>, rustc_driver[8714e23c1e821b1]
::run_compiler::{closure#1}>::{closure#1}>
66:     0x7fe359d7f32e - rustc_interface[3672e0c3fff8aeee]::interface::create_compiler_and_run::<core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::Error
Reported>, rustc_driver[8714e23c1e821b1]::run_compiler::{closure#1}>
67:     0x7fe359d630cb - <scoped_tls[73290609747467e0]::ScopedKey<rustc_span[8f278cc4e436f278]::SessionGlobals>>::set::<rustc_interface[3672e0c3fff8aeee]::util::setup_callbacks
_and_run_in_thread_pool_with_globals<rustc_interface[3672e0c3fff8aeee]::interface::run_compiler<core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorR
eported>, rustc_driver[8714e23c1e821b1]::run_compiler::{closure#1}>::{closure#0}, core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>::{cl
osure#0}::{closure#0}, core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>
68:     0x7fe359d62ec5 - std[4f17e28e306b5344]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3672e0c3fff8aeee]::util::setup_callbacks_and_run_in_thread
_pool_with_globals<rustc_interface[3672e0c3fff8aeee]::interface::run_compiler<core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>, rustc_dr
iver[8714e23c1e821b1]::run_compiler::{closure#1}>::{closure#0}, core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>::{closure#0}, core[cd1
2ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>
69:     0x7fe359d8f8e9 - <<std[4f17e28e306b5344]::thread::Builder>::spawn_unchecked<rustc_interface[3672e0c3fff8aeee]::util::setup_callbacks_and_run_in_thread_pool_with_globals
<rustc_interface[3672e0c3fff8aeee]::interface::run_compiler<core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>, rustc_driver[8714e23c1e821
b1]::run_compiler::{closure#1}>::{closure#0}, core[cd12ad7e3bc8284]::result::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>::{closure#0}, core[cd12ad7e3bc8284]::res
ult::Result<(), rustc_errors[f0173504293ba049]::ErrorReported>>::{closure#1} as core[cd12ad7e3bc8284]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
70:     0x7fe3576f1fe3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbe6f092d86b36955
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/alloc/src/boxed.rs:1854:9
71:     0x7fe3576f1fe3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h50c5cd71b690e216
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/alloc/src/boxed.rs:1854:9
72:     0x7fe3576f1fe3 - std::sys::unix::thread::Thread::new::thread_start::h17fc02621e7a1aef
at /rustc/1409c015b44a4d4d38bef2250b2a37c17b8b7463/library/std/src/sys/unix/thread.rs:108:17
73:     0x7fe35722f6db - start_thread
74:     0x7fe356d5071f - __clone
75:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (1409c015b 2022-01-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
warning: `local-esdt-and-nft-meta` (bin "local-esdt-and-nft-meta") generated 2 warnings
error: could not compile `local-esdt-and-nft-meta`; 2 warnings emitted

Caused by:
process didn't exit successfully: `rustc --crate-name local_esdt_and_nft_meta --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,future-incompat --c
rate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=4a73f7dbc54fdab7 -C extra-filename=-4a73f7dbc54fdab7 --out-dir /cry/elrond/local-esdt-and-nft-
25/meta/target/debug/deps -C incremental=/cry/elrond/local-esdt-and-nft-25/meta/target/debug/incremental -L dependency=/cry/elrond/local-esdt-and-nft-25/meta/target/debug/deps
--extern elrond_wasm=/cry/elrond/local-esdt-and-nft-25/meta/target/debug/deps/libelrond_wasm-6afc0d0267c19f9e.rlib --extern elrond_wasm_debug=/cry/elrond/local-esdt-and-nft-25/
meta/target/debug/deps/libelrond_wasm_debug-9fdf18b0103c7f4b.rlib --extern local_esdt_and_nft=/cry/elrond/local-esdt-and-nft-25/meta/target/debug/deps/liblocal_esdt_and_nft-d5d
c185a0a22c483.rlib` (signal: 4, SIGILL: illegal instruction)
CRITICAL:cli:Build error: error code = 101, see output.

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by kirawi** [comment]
The incremental compiler woes never cease.

**Comment by workingjubilee** [comment]
I was going through all the incremental compilation errors from about this period and closing most of them as probably a duplicate of other issues, but this one reads very differently so I am assuming nothing about it.

**Comment by workingjubilee** [comment]
...still clicked the "close" button on pure reflex, apparently.
