### ISSUE TITLE
ICE compiler\rustc_typeck\src\collect.rs:1089:14: impossible case reached

### ISSUE THREAD

**Issue by DzenanJupic** [rust-lang/rust#92848]
### Code

It's a big company project, and I'm not quite sure where it's coming form.

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (efec54529 2021-12-04)
binary: rustc
commit-hash: efec545293b9263be9edfb283a7aa66350b3acbf
commit-date: 2021-12-04
host: x86_64-pc-windows-msvc
release: 1.59.0-nightly
LLVM version: 13.0.0
```

works fine with stable
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler\rustc_errors\src\lib.rs:1170:9
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.59.0-nightly (efec54529 2021-12-04) running on x86_64-pc-windows-msvc
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [adt_def] computing ADT definition for `workflow_iterator::WorkflowIterError`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 1 warning emitted
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0:     0x7ff949a19c5f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc2aeea11bb07072e
   1:     0x7ff949a444fa - core::fmt::write::h8a2c40ddb66ccc71
   2:     0x7ff949a0b9e8 - <std::io::IoSlice as core::fmt::Debug>::fmt::hb0f7b7ec1545d2d8
   3:     0x7ff949a1d1a6 - std::panicking::take_hook::hb82d3fa273181deb
   4:     0x7ff949a1cc8c - std::panicking::take_hook::hb82d3fa273181deb
   5:     0x7ff8d45ea7f5 - <rustc_lint[d5b77cca1c855499]::BuiltinCombinedLateLintPass as rustc_lint[d5b77cca1c855499]::passes::LateLintPass>::check_crate_post
   6:     0x7ff949a1dab9 - std::panicking::rust_panic_with_hook::h8846bbc0e1c27093
   7:     0x7ff8d8dbf0c0 - <rustc_errors[d1edc47bc43c28ca]::diagnostic_builder::DiagnosticBuilder>::code
   8:     0x7ff8d8dbef89 - <rustc_errors[d1edc47bc43c28ca]::diagnostic_builder::DiagnosticBuilder>::code
   9:     0x7ff8d90a8761 - rustc_query_system[d5dc892f1d05674d]::query::job::report_cycle
  10:     0x7ff8d8deb8f0 - <rustc_errors[d1edc47bc43c28ca]::emitter::FileWithAnnotatedLines as core[3b5640218fb446b]::fmt::Debug>::fmt
  11:     0x7ff8d8df36f7 - <rustc_errors[d1edc47bc43c28ca]::HandlerInner>::emit_diagnostic
  12:     0x7ff8d8df11a2 - <rustc_errors[d1edc47bc43c28ca]::Handler>::bug
  13:     0x7ff8d8aa2421 - <rustc_middle[63aa33dd3295c16a]::ty::consts::valtree::ValTree>::zst
  14:     0x7ff8d8aa40e9 - <rustc_middle[63aa33dd3295c16a]::ty::generics::GenericPredicates>::instantiate_identity
  15:     0x7ff8d90a1340 - rustc_middle[63aa33dd3295c16a]::util::bug::bug_fmt
  16:     0x7ff8d701d03f - <rustc_typeck[ce8e60202e7a8568]::collect::ItemCtxt as rustc_typeck[ce8e60202e7a8568]::astconv::AstConv>::projected_ty_from_poly_trait_ref
  17:     0x7ff8d7d7958f - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  18:     0x7ff8d7e362c6 - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  19:     0x7ff8d7d1cf1b - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  20:     0x7ff8d7bc63df - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  21:     0x7ff8d7b20bb7 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  22:     0x7ff8d7de608f - rustc_query_impl[66d4c656b011426]::query_callbacks::adt_def
  23:     0x7ff8d8ad6c13 - <rustc_middle[63aa33dd3295c16a]::ty::context::TyCtxt as rustc_query_system[d5dc892f1d05674d]::dep_graph::DepContext>::try_force_from_dep_node
  24:     0x7ff8d7e19d7b - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  25:     0x7ff8d7df19ba - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  26:     0x7ff8d7b2682c - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  27:     0x7ff8d7c824d0 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  28:     0x7ff8d70e66bd - <rustc_typeck[ce8e60202e7a8568]::constrained_generic_params::Parameter as core[3b5640218fb446b]::fmt::Debug>::fmt
  29:     0x7ff8d702f26b - <rustc_typeck[ce8e60202e7a8568]::check::PlaceOp as core[3b5640218fb446b]::fmt::Debug>::fmt
  30:     0x7ff8d6fc5154 - rustc_typeck[ce8e60202e7a8568]::check_crate
  31:     0x7ff8d474f9af - rustc_interface[1c6a2488f78f6a24]::passes::analysis
  32:     0x7ff8d7d7ab7b - <rustc_span[c5d9e30fa007120c]::def_id::DefIndex as rustc_query_impl[66d4c656b011426]::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string
  33:     0x7ff8d7e4e52e - rustc_query_impl[66d4c656b011426]::query_callbacks::diagnostic_hir_wf_check
  34:     0x7ff8d7d13901 - <rustc_query_impl[66d4c656b011426]::queries::diagnostic_hir_wf_check as rustc_query_system[d5dc892f1d05674d]::query::config::QueryDescription<rustc_query_impl[66d4c656b011426]::plumbing::QueryCtxt>>::describe
  35:     0x7ff8d7c10f69 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  36:     0x7ff8d7cac4a2 - <rustc_mir_dataflow[60503fc7d90bc0c2]::impls::storage_liveness::MaybeRequiresStorage as rustc_mir_dataflow[60503fc7d90bc0c2]::framework::AnalysisDomain>::initialize_start_block
  37:     0x7ff8d466b960 - <rustc_driver[dea966e5e189d317]::args::Error as core[3b5640218fb446b]::fmt::Debug>::fmt
  38:     0x7ff8d46103d5 - <rustc_span[c5d9e30fa007120c]::symbol::SymbolStr as core[3b5640218fb446b]::fmt::Display>::fmt
  39:     0x7ff8d4601b25 - <chalk_engine[5e046f5921b469d8]::TimeStamp>::increment
  40:     0x7ff8d4611781 - <rustc_span[c5d9e30fa007120c]::symbol::SymbolStr as core[3b5640218fb446b]::fmt::Display>::fmt
  41:     0x7ff8d460d773 - rustc_driver[dea966e5e189d317]::pretty::print_after_hir_lowering
  42:     0x7ff8d46885f8 - <rustc_driver[dea966e5e189d317]::args::Error as core[3b5640218fb446b]::fmt::Debug>::fmt
  43:     0x7ff949a2b18c - std::sys::windows::thread::Thread::new::h578a3ae84cde46a8
  44:     0x7ff974547034 - BaseThreadInitThunk
  45:     0x7ff974b22651 - RtlUserThreadStart
```

</p>
</details>

**Comment by toshokan** [comment]
I am also experiencing this issue on 1.58.1, see a reproducible (but not minimally reproducible) example at https://github.com/toshokan/tomiko/commit/0bd72f35bf2813595ee03c02a9cec3dbe2707fec

In my case it seems to be triggered by a type alias. 

# rustc info

```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-unknown-linux-gnu
release: 1.58.1
LLVM version: 13.0.0
```

# Output
```
error: internal compiler error: compiler/rustc_typeck/src/collect.rs:1089:14: impossible case reached

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.1 (db9d1b20b 2022-01-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [adt_def] computing ADT definition for `auth::AuthorizationError`
#1 [unsafety_check_result] unsafety-checking `http::encoding::error::handle_reject::{closure#0}`
end of query stack
error: could not compile `tomiko`
```

**Comment by toshokan** [comment]
Looks like this is caused by not handling the `ItemKind::TyAlias` case at https://github.com/rust-lang/rust/blob/1.58.1/compiler/rustc_typeck/src/collect.rs#L1020

Is it supposed to be handled there, or should it have been handled earlier?

**Comment by compiler-errors** [comment]
Since another person said their similar ICE was fixed on nightly, please re-open this as a fresh issue if you encounter it on an up-to-date stable Rust.
