### ISSUE TITLE
Trait selection provisional cache incorrectly handles DepNodes, leading to ICE

### ISSUE THREAD

**Issue by znx3p0** [rust-lang/rust#92987]
### Code

Please clone [this repo](https://github.com/znx3p0/canary/tree/1920c7ed65b8181276f06030230dc3c9f8067a22) and build it.

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (5531927e8 2021-12-16)
binary: rustc
commit-hash: 5531927e8af9b99ad923af4c827c91038bca51ee
commit-date: 2021-12-16
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5531927e8af9b99ad923af4c827c91038bca51ee/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (5531927e8 2021-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `routes::Storable: core::marker::Send`
#1 [check_item_well_formed] checking that `routes::GLOBAL_ROUTE` is well-formed
end of query stack
error: could not compile `canary`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5531927e8af9b99ad923af4c827c91038bca51ee/compiler/rustc_hir/src/definitions.rs:452:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5531927e8af9b99ad923af4c827c91038bca51ee/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/5531927e8af9b99ad923af4c827c91038bca51ee/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/5531927e8af9b99ad923af4c827c91038bca51ee/library/core/src/panicking.rs:48:5
   3: <rustc_query_system::dep_graph::dep_node::DepNode<rustc_middle::dep_graph::dep_node::DepKind> as rustc_middle::dep_graph::dep_node::DepNodeExt>::extract_def_id
   4: rustc_query_impl::query_callbacks::type_of::force_from_dep_node
   5: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
   6: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   7: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
   8: rustc_data_structures::stack::ensure_sufficient_stack::<core::option::Option<(core::result::Result<rustc_middle::traits::select::EvaluationResult, rustc_middle::traits::select::OverflowError>, rustc_query_system::dep_graph::graph::DepNodeIndex)>, rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::infer::canonical::Canonical<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::Predicate>>, core::result::Result<rustc_middle::traits::select::EvaluationResult, rustc_middle::traits::select::OverflowError>>::{closure#2}>
   9: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::evaluate_obligation, rustc_query_impl::plumbing::QueryCtxt>
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::evaluate_obligation
  11: <rustc_trait_selection::traits::fulfill::FulfillProcessor>::progress_changed_obligations
  12: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor, rustc_data_structures::obligation_forest::Outcome<rustc_trait_selection::traits::fulfill::PendingPredicateObligation, rustc_infer::traits::FulfillmentErrorCode>>
  13: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_all_or_error
  14: <rustc_typeck::check::fn_ctxt::FnCtxt>::select_all_obligations_or_error
  15: <rustc_infer::infer::InferCtxtBuilder>::enter::<(), <rustc_typeck::check::inherited::InheritedBuilder>::enter<<rustc_typeck::check::wfcheck::CheckWfFcxBuilder>::with_fcx<rustc_typeck::check::wfcheck::check_item_type::{closure#0}>::{closure#0}, ()>::{closure#0}>
  16: rustc_typeck::check::wfcheck::check_item_type
  17: rustc_typeck::check::wfcheck::check_item_well_formed
  18: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, ()>
  19: rustc_data_structures::stack::ensure_sufficient_stack::<((), rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, ()>::{closure#3}>
  20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_item_well_formed
  22: <rustc_middle::hir::map::Map>::par_visit_all_item_likes::<rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor>
  23: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#5}, ()>
  24: rustc_typeck::check_crate
  25: rustc_interface::passes::analysis
  26: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorReported>>
  27: rustc_data_structures::stack::ensure_sufficient_stack::<(core::result::Result<(), rustc_errors::ErrorReported>, rustc_query_system::dep_graph::graph::DepNodeIndex), rustc_query_system::query::plumbing::execute_job<rustc_query_impl::plumbing::QueryCtxt, (), core::result::Result<(), rustc_errors::ErrorReported>>::{closure#3}>
  28: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorReported>>>
  29: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  30: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorReported>>
  31: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  32: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  33: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (5531927e8 2021-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `routes::Storable: core::marker::Send`
#1 [check_item_well_formed] checking that `routes::GLOBAL_ROUTE` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `canary`
```

</p>
</details>

**Comment by Aaron1011** [comment]
This is a new incremental compilation issue, distinct from the previous 'called Option::unwrap' issues. cc @cjgillot

**Comment by Aaron1011** [comment]
Thanks for the great reproducer - I was able to reproduce this by first building commit [`27f1892baf487c61390b61d14f96b7828bd5e660`](https://github.com/znx3p0/canary/commit/27f1892baf487c61390b61d14f96b7828bd5e660), then building commit https://github.com/znx3p0/canary/commit/1920c7ed65b8181276f06030230dc3c9f8067a22

**Comment by Aaron1011** [comment]
This is caused by the way that we handle `DepKind::TraitSelect` (which is an anon dep-node).

The current query system is set up so that we will never try to force a query with a stale `DefPathHash`. Normally, the only way of invoking a query with a `DefId` is to obtain that `DefId` from another query result, or to receive that `DefId` as part of the query argument.

If a query 'A' obtains a `DefId` by invoking another query 'B', then removing the corresponding definition from the crate will change the result of query 'B', causing it to be marked red. When we try to mark query 'A' as green, we will see the red dependency 'B' and bail out, before we ever attempt to force another query with the stale `DefPathHash` that we saved from the previous compilation session.

When we actually invoke a query during the execution of some query's body, we will try to find a matching `DepNode` from the previous compilation session. If the input to the invoked query contains a `DefId` (e.g. as part of the `AdtDef` inside of a `Ty`), then a change to the `DefPathHash` will cause us to compute a different hash for the query input. As a result, we will never try to load the depnode from a previous session, since we will not find a node with a matching hash.

However, anon dep nodes break this assumption. Specifically, when we create a `DepKind::TraitSelect`, we invoke queries like `type_of` using `DefId`s taken from the surrounding `SelectionContext`. From the perspective of the query system, these `DefId`s are essentially pulled out of thin air - the query system sees `DepKind::TraitSelect` as having no input. Specifically, we call:

https://github.com/rust-lang/rust/blob/fd20513f52b1e6a7799fd291c1a5979dd65678ac/compiler/rustc_trait_selection/src/traits/select/mod.rs#L756

Inside a (recursive) call to `evaluate_stack`, we may call queries with `DefId`s obtained from the predicate - for example, to look up constituent types for auto trait impls. 

As a result, trying to mark a `TraitSelect` node green can cause us to try to force a query with a stale `DefPathHash`, since our edges vec will not contain a dependency on a query used to produce the `DefPathHash` to begin with. With normal non-anon nodes, the dependency on a particular `DefId` will always be explicitly carried through the graph of query invocations - either being forwarded through a query argument (thus affecting the `DepNode` hash), or by using the result of another query.

The fact that we will never legitimately try to force a stale `DefPathHash` has helped us find bugs (e.g. https://github.com/rust-lang/rust/issues/91696#issuecomment-993043710), so I think it would be unfortunate if we had to start silently ignoring the forcing of a stale `DefPathHash`.

I'll need to think about how we can adjust anon dep nodes to fix this issue. Ideally, we would just remove the concept of anon dep nodes entirely - however, I'm pretty sure that it's the only way to make the global evaluation cache work with incremental compilation.

**Comment by Aaron1011** [comment]
On further investigation, it appears that this may be related to overwriting an existing `DepNode` in the evaluation or candidate cache, potentially causing us to fail to track needed dependencies.

**Comment by Aaron1011** [comment]
Minimal reproduction script:

`repro.rs`:

```rust
#[cfg(first)]
struct First(Box<Second>);

#[cfg(second)]
enum First {
    Variant(Box<Second>)
}

struct Second(First);

fn assert_send<T: Send>() {}

fn bar() {
    assert_send::<First>();
    assert_send::<Second>();
}
```

`repro.sh`:

```bash
set -euxo pipefail

rm -r foo
rustc repro.rs --crate-type lib -C incremental=foo --cfg first
rustc repro.rs --crate-type lib -C incremental=foo --cfg second
```
