### ISSUE TITLE
src/stage0.json doesn't contain a checksum for dist/2021-11-30/rustc-beta-armv7-linux-androideabi.tar.xz

### ISSUE THREAD

**Issue by rcreecy** [rust-lang/rust#93040]
I am attempting to compile Rust in a Raspberry Pi 3b+ running Emteria.os Android (Armv7 Android / Linux 4.9.196-v7+) and receiving checksum validation errors against the target. 

I have cloned the primary repository branch and am proceeding with the documented build instructions. Upon calling x.py for build, I receive a failure.

RuntimeError: src/stage0.json doesn't contain a checksum for dist/2021-11-30/rustc-beta-armv7-linux-androideabi.tar.xz

The rest of the stack trace seems to just indicate the path for src/bootstrap/bootstrap.py for the try/catch there. Reviewing stage0.json, the issue seems to be with the target file being pulled being **rustc**-beta-armv7-linux-androideabi.tar.xz, where stage0.json contains a checksum for **rust**-beta-armv7-linux-androideabi.tar.xz. Not sure how to proceed here.

<details><summary>Backtrace</summary>
<p>

```
Updating only changed submodules
  Submodules updated in 0.06 seconds
extracting /data/data/com.termux/files/home/rust/build/cache/2021-11-30/rust-std-beta-armv7-linux-androideabi.tar.xz
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/rust/./x.py", line 27, in <module>
    bootstrap.main()
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 1313, in main
    bootstrap(help_triggered)
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 1279, in bootstrap
    build.download_toolchain()
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 453, in download_toolchain
    self._download_component_helper(filename, "rustc", tarball_suffix, stage0)
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 591, in _download_component_helper
    get(
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 73, in get
    raise RuntimeError("src/stage0.json doesn't contain a checksum for {}".format(url))
RuntimeError: src/stage0.json doesn't contain a checksum for dist/2021-11-30/rustc-beta-armv7-linux-androideabi.tar.xz
```

</p>
</details>

**Comment by Mark-Simulacrum** [comment]
Can you paste your config.toml? I suspect you are enabling download-ci-llvm and/or download-rustc in config.toml, which force a dependency on the rustc tarball, but that's not available for armv7-linux-androideabi as it's a tier-2 without host tools target.

**Comment by rcreecy** [comment]
I am using the config sample out of the box, however, I did just adjust both download-ci-llvm and download-rustc to be set to false (I tried them both together and individually), and I continue to receive the same failure

```
~/rust $ ./x.py build && ./x.py install
Updating only changed submodules
  Submodules updated in 0.32 seconds
extracting /data/data/com.termux/files/home/rust/build/cache/2021-11-30/rust-std-beta-armv7-linux-androideabi.tar.xz
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/rust/./x.py", line 27, in <module>
    bootstrap.main()
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 1313, in main
    bootstrap(help_triggered)
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 1279, in bootstrap
    build.download_toolchain()
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 453, in download_toolchain
    self._download_component_helper(filename, "rustc", tarball_suffix, stage0)
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 591, in _download_component_helper
    get(
  File "/data/data/com.termux/files/home/rust/src/bootstrap/bootstrap.py", line 73, in get
    raise RuntimeError("src/stage0.json doesn't contain a checksum for {}".format(url))
RuntimeError: src/stage0.json doesn't contain a checksum for dist/2021-11-30/rustc-beta-armv7-linux-androideabi.tar.xz
```

**Comment by Mark-Simulacrum** [comment]
Oh, wait, rustc-beta -- sorry, confused it with a different component. Yes, this is just a poor error message, but the cause of this is as I indicated -- we don't currently have pre-built rustc binaries for this target, so x.py won't be able to bootstrap on this target without you providing the bootstrap binaries (rustc and cargo) to facilitate that, which may be obtainable by cross-compiling from a different machine.

**Comment by rcreecy** [comment]
Okay, thanks for the quick followup. I'll follow the rustc book for custom targets and try to compile for myself, and hopefully have some luck.
