### ISSUE TITLE
Compiler error reported

### ISSUE THREAD

**Issue by barscm** [rust-lang/rust#93701]
Running `cargo build` or `cargo check` on a workspace crate I got a compiler error.
(probably unrelated, I recently ran `cargo fix`)

If I go one level up to the workspace root I don't get a compiler error, but there is an error:

```
Caused by:
  process didn't exit successfully: `rustc --crate-name serde /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-0.8.23/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=c99fe8226859f2e4 -C extra-filename=-c99fe8226859f2e4 --out-dir /home/chris/code/rust/cargo/chrisb/target/debug/deps -L dependency=/home/chris/code/rust/cargo/chrisb/target/debug/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
fatal runtime error: Rust cannot catch foreign exceptions
error: build failed
```

However, the following are the bits from the workspace crate as it's reporting as a bug:

### Meta
`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0

```

### Error output
```
the compiler unexpectedly panicked. this is a bug.
```

### Backtrace
```
    Checking chba v0.1.0 (/home/chris/code/rust/cargo/chrisb/chba)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1, error_len: Some(1) }', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_serialize/src/opaque.rs:659:85
stack backtrace:
   0:     0x7f61fee48a9c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f61fee48a9c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f61fee48a9c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f61fee48a9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f61feea5fdc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x7f61fee38c05 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x7f61fee4bf60 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f61fee4bf60 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f61fee4bf60 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x7f61fee4bb15 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x7f61ff6382b1 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h932547f60770f26a
  11:     0x7f61fee4c779 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
  12:     0x7f61fee4c230 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  13:     0x7f61fee48f44 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x7f61fee4c199 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  15:     0x7f61fee10441 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  16:     0x7f61fee10533 - core::result::unwrap_failed::h32ef6b3156e8fc57
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  17:     0x7f620197a507 - rustc_serialize::serialize::Decoder::read_struct_field::h019b03bb7fadea77
  18:     0x7f6200ea6517 - rustc_metadata::rmeta::_DERIVE_rustc_serialize_Decodable_DecodeContext_a_tcx_FOR_CrateRoot::<impl rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext> for rustc_metadata::rmeta::CrateRoot>::decode::hea4ad47fcc4f1232
  19:     0x7f6201993148 - rustc_metadata::rmeta::decoder::MetadataBlob::get_root::he7cdfec36531697b
  20:     0x7f62019d36dd - rustc_metadata::locator::CrateLocator::extract_one::h13e10dbb6b88b7c4
  21:     0x7f62019d2dbb - rustc_metadata::locator::CrateLocator::extract_lib::h4f79a2ed0777d19b
  22:     0x7f62019d210b - rustc_metadata::locator::CrateLocator::find_library_crate::h8792751871cca143
  23:     0x7f62019d0e22 - rustc_metadata::locator::CrateLocator::maybe_load_library_crate::h134d81d03b219ab5
  24:     0x7f6200eb702d - rustc_metadata::creader::CrateLoader::load::hbd6535c69db3eebc
  25:     0x7f6200eb3cd3 - rustc_metadata::creader::CrateLoader::maybe_resolve_crate::h6aad008052115e7f
  26:     0x7f6200eb4109 - rustc_metadata::creader::CrateLoader::maybe_resolve_crate::h6aad008052115e7f
  27:     0x7f62002583b1 - rustc_metadata::creader::CrateLoader::maybe_process_path_extern::h2a4fa39ec70109f4
  28:     0x7f6200b0306d - rustc_resolve::Resolver::extern_prelude_get::h10f3a7f365038170
  29:     0x7f6200af651c - rustc_resolve::macros::<impl rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope::h444e0c6879539ff2
  30:     0x7f6200af0136 - rustc_resolve::imports::<impl rustc_resolve::Resolver>::resolve_ident_in_module_unadjusted_ext::hf5d8b4d577aa1fc8
  31:     0x7f6200affb36 - rustc_resolve::Resolver::resolve_ident_in_module_ext::h191b8d69197bed38
  32:     0x7f6200af1998 - rustc_resolve::imports::ImportResolver::resolve_import::{{closure}}::hea8751f8c90f6372
  33:     0x7f6200ad4c45 - rustc_resolve::imports::ImportResolver::resolve_imports::h98a865a81d2b173b
  34:     0x7f62015bd3c0 - rustc_resolve::macros::<impl rustc_expand::base::ResolverExpand for rustc_resolve::Resolver>::resolve_imports::h59512362acd06bf1
  35:     0x7f6200f163b4 - rustc_expand::expand::MacroExpander::fully_expand_fragment::h5e600dbaf1596531
  36:     0x7f62019ed9ff - rustc_expand::expand::MacroExpander::expand_crate::h8513f82e2067d8c9
  37:     0x7f62012703cf - rustc_session::utils::<impl rustc_session::session::Session>::time::ha9acf8231fd57720
  38:     0x7f620124140c - rustc_interface::passes::configure_and_expand::h0989102b965bac52
  39:     0x7f6201244c13 - rustc_interface::queries::Queries::expansion::hb40d9eb6ce7184e5
  40:     0x7f620121d876 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hf84cd18c24bd5171
  41:     0x7f620120b0ee - rustc_span::with_source_map::h6ab8a240e103b5b9
  42:     0x7f620121d2ac - scoped_tls::ScopedKey<T>::set::hd1fbd64c6f645895
  43:     0x7f620120bef5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0a1328c9fa7f7448
  44:     0x7f6201237962 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4ea1ced06d6b3e97
  45:     0x7f61fee57933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7bd677a5dc988be6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  46:     0x7f61fee57933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7b1c1ba11c4db785
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  47:     0x7f61fee57933 - std::sys::unix::thread::Thread::new::thread_start::h9c58c0d12d84e854
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  48:     0x7f61feb956db - start_thread
                               at /build/glibc-S9d2JN/glibc-2.27/nptl/pthread_create.c:463
  49:     0x7f61fe4b271f - __GI___clone
                               at /build/glibc-S9d2JN/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  50:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `chba`

```

**Comment by Yush08** [comment]
Please send a minimal example that can reproduce this ICE -- also remember to check that if this ICE exists on nightly, this might've already been fixed.

**Comment by Noratrieb** [comment]
This issue does not have a reproduction and is therefore not really actionable, closing. If you find the problem again, please open a new issue, ideally with a reproduction.
