### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14

### ISSUE THREAD

**Issue by John-Nagle** [rust-lang/rust#94163]
### Code

```Rust

No minimized error yet. This error occurred when making a small change to a large program. Here are the diffs from a working version:

diff --git a/slcommon/src/common/commontypes.rs b/slcommon/src/common/commontypes.rs
index d19daa8..3f38137 100644
--- a/slcommon/src/common/commontypes.rs
+++ b/slcommon/src/common/commontypes.rs
@@ -1223,8 +1223,12 @@ fn basictypetests() {
 //
 //  Miscellaneous types
 //
+/// Object ID from server.
 pub type LocalID = u32; // region-local ID
 
+/// Volume LOD. Value 0..3, with 3 the most detailed.
+pub type VolumeLod = u8;
+
 #[test]
 //  Tests for basic arithmetic.
 fn arithmetictests() {
diff --git a/slcommon/src/volume/decodemeshasset.rs b/slcommon/src/volume/decodemeshasset.rs
index 2269e56..6a0d0e7 100644
--- a/slcommon/src/volume/decodemeshasset.rs
+++ b/slcommon/src/volume/decodemeshasset.rs
@@ -39,7 +39,7 @@ impl MeshDecoded {
     }
     
     /// Return requested LOD. Includes all meshes.
-    pub fn get_lod(&self, detail: u32) -> Result<MeshLOD, Error> {
+    pub fn get_lod(&self, detail: VolumeLod) -> Result<MeshLOD, Error> {
         //  Names of levels of detail in the mesh LLSD.
         const LODNAMES: [&str; 4] = ["lowest_lod", "low_lod", "medium_lod", "high_lod"];
         assert!((detail as usize) < LODNAMES.len());            // bad LOD parameter
@@ -106,7 +106,7 @@ pub struct MeshLOD {
 impl MeshLOD {
     /// Get requested level of detail from asset.
     //  Old interface; decodes the entire asset each time.
-    pub fn get_lod(b: &[u8], detail: u32) -> Result<MeshLOD, Error> {
+    pub fn get_lod(b: &[u8], detail: VolumeLod) -> Result<MeshLOD, Error> {
         let mesh_decoded = MeshDecoded::new(b)?;
         mesh_decoded.get_lod(detail)
     }
@@ -543,7 +543,8 @@ fn decodemeshcube1() {
     }
     
     //  Now exercise the real code.
-    let lod3 = MeshLOD::get_lod(&meshbytes, 3).unwrap(); // get an LOD from it
+    let volume_lod: VolumeLod = 3;
+    let lod3 = MeshLOD::get_lod(&meshbytes, volume_lod).unwrap(); // get an LOD from it
     println!("LOD 3: {:?}", lod3); //
 }
 
diff --git a/slcommon/src/volume/mod.rs b/slcommon/src/volume/mod.rs
index 850eefe..58878a1 100644
--- a/slcommon/src/volume/mod.rs
+++ b/slcommon/src/volume/mod.rs
@@ -1,7 +1,7 @@
 //
 //  SL test viewer
 //
-//  viewer/mod.rs
+//  common/volume/mod.rs
 //
 //  Animats
 //  January, 2021
(END)




<code>


```

### Meta

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0

```

### Error output
```


cargo build
   Compiling slcommon v0.1.0 (/home/john/projects/sl/SL-test-viewer/slcommon)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id
   4: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover
   5: rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  10: rustc_query_system::query::plumbing::ensure_must_run
  11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::coherent_trait
  12: rustc_session::session::Session::track_errors
  13: rustc_typeck::check_crate
  14: rustc_interface::passes::analysis
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_query_system::query::plumbing::try_execute_query
  18: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `slcommon`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id
   4: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover
   5: rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  10: rustc_query_system::query::plumbing::ensure_must_run
  11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::coherent_trait
  12: rustc_session::session::Session::track_errors
  13: rustc_typeck::check_crate
  14: rustc_interface::passes::analysis
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_query_system::query::plumbing::try_execute_query
  18: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by John-Nagle** [comment]
Did "cargo clean" and rebuilt OK.

**Comment by Aaron1011** [comment]
This is a known issue with incremental compilation - it should be fixed in the latest Nightly.

**Comment by John-Nagle** [comment]
OK, thanks. I will look forward to seeing it fixed in Stable.
