### ISSUE TITLE
error: internal compiler error: compiler/rustc_traits/src/normalize_erasing_regions.rs:54:32: could not fully normalize

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [rust-lang/rust#94204]
### Code

The code cannot easily be entirely summarised in a small segment. It involves a [criterion benchmark](https://github.com/bheisler/criterion.rs) on a library.

Specifically running `cargo bench` in on this branch (https://github.com/JonathanWoollett-Light/static-la/tree/bench-error) triggers the error.

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (82af160c2 2021-11-10)
binary: rustc
commit-hash: 82af160c2cb9c349a0373cba98d8ad7f911f0d34
commit-date: 2021-11-10
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### Error output

```
error: internal compiler error: compiler/rustc_traits/src/normalize_erasing_regions.rs:54:32: could not fully normalize `<static_la::MatrixSxS<T, L, M> as static_la::Matmul<static_la::MatrixSxS<T, M, N>>>::Output`

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (82af160c2 2021-11-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `<static_la::MatrixSxS<T, L, M> as static_la::matmul::Matmul<static_la::MatrixSxS<T, M, N>>>::Output`
#1 [fn_abi_of_instance] computing call ABI of `<static_la::MatrixSxS<i32, 2_usize, 3_usize> as static_la::matmul::Matmul<static_la::MatrixSxS<i32, 3_usize, 2_usize>>>::matmul`
end of query stack
warning: `static-la` (bench "benchmarks") generated 12 warnings
error: could not compile `static-la`; 12 warnings emitted
warning: build failed, waiting for other jobs to finish...
error: build failed
jonathan@jonathan-MS-7B22:~/Projects/static-la$ 
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: compiler/rustc_traits/src/normalize_erasing_regions.rs:54:32: could not fully normalize `<static_la::MatrixSxS<T, L, M> as static_la::Matmul<static_la::MatrixSxS<T, M, N>>>::Output`

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug
   3: <rustc_errors::Handler>::bug
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_infer::infer::InferCtxtBuilder>::enter::<rustc_middle::ty::subst::GenericArg, rustc_traits::normalize_erasing_regions::normalize_after_erasing_regions<rustc_middle::ty::subst::GenericArg>::{closure#0}>
   8: <rustc_traits::normalize_erasing_regions::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::subst::GenericArg>)>>::call_once
   9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<rustc_middle::ty::subst::GenericArg>, rustc_middle::ty::subst::GenericArg>>
  10: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::normalize_generic_arg_after_erasing_regions
  11: rustc_middle::ty::util::fold_list::<rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder, &rustc_middle::ty::TyS, <&rustc_middle::ty::list::List<&rustc_middle::ty::TyS> as rustc_middle::ty::fold::TypeFoldable>::super_fold_with<rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder>::{closure#0}>
  12: rustc_middle::ty::layout::fn_abi_of_instance
  13: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::ParamEnvAnd<(rustc_middle::ty::instance::Instance, &rustc_middle::ty::list::List<&rustc_middle::ty::TyS>)>, core::result::Result<&rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS>, rustc_middle::ty::layout::FnAbiError>>>
  14: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::fn_abi_of_instance
  15: rustc_codegen_ssa::mir::codegen_mir::<rustc_codegen_llvm::builder::Builder>
  16: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  17: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::symbol::Symbol, rustc_codegen_ssa::ModuleCodegen<rustc_codegen_llvm::ModuleLlvm>>
  18: rustc_codegen_llvm::base::compile_codegen_unit
  19: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  20: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  21: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
  22: <rustc_interface::queries::Queries>::ongoing_codegen
  23: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  24: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}>
  25: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (82af160c2 2021-11-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `<static_la::MatrixSxS<T, L, M> as static_la::matmul::Matmul<static_la::MatrixSxS<T, M, N>>>::Output`
#1 [fn_abi_of_instance] computing call ABI of `<static_la::MatrixSxS<i32, 2_usize, 3_usize> as static_la::matmul::Matmul<static_la::MatrixSxS<i32, 3_usize, 2_usize>>>::matmul`
end of query stack
warning: `static-la` (bench "benchmarks") generated 12 warnings
error: could not compile `static-la`; 12 warnings emitted
jonathan@jonathan-MS-7B22:~/Projects/static-la$ 
```

</p>
</details>

**Comment by JonathanWoollett-Light** [comment]
To add a simpler example of what I beleive to be the same error.

`Cargo.toml`:
```
```
`src/main.rs`:
```rust
use static_la::Matmul;
fn main() {
    let l = static_la::MatrixSxS::<f32,2,2>::from([[0.,1.],[2.,3.]]);
    let lt = l.transpose();
    // The errors arises from `l.matmul(&lt);`
    let _ = l.matmul(&lt);
}
```

**Comment by JonathanWoollett-Light** [comment]
Adding `#![feature(generic_const_exprs)]` fixes the error. Although I'm not sure this prevents this being a bug still.

**Comment by moxian** [comment]
Still repros as of `rustc 1.85.0 (4d91de4e4 2025-02-17)`

Minimized :

```rs
// lib.rs
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

pub struct Empty;

pub struct MatrixSxS<const ROWS: usize> {
    data: [Empty; ROWS],
}
impl<const ROWS: usize> MatrixSxS<ROWS>
where
    [(); ROWS * ROWS]:,
{
    pub fn new() -> Self { todo!() }
}

pub trait Matmul {
    // commenting this out still repros ICE, but I fear it might be a bit too brittle
    // fn matmul(&self);
}

impl<const K: usize> Matmul for MatrixSxS<K> {
    // fn matmul(&self) {
    //     todo!()
    // }
}
```

```rs
// main.rs
use static_la::Matmul;
fn main() {
    let l = static_la::MatrixSxS::<0>::new();
    // let _ = l.matmul();
}
```

@rustbot label: -E-needs-mcve +S-has-mcve +F-generic_const_exprs +requires-nightly

**Comment by moxian** [comment]
Actually, I'm sorry, that's a *different* ICE on 1.85 - `Encountered anon const with inference variable args but no error reported`:

```
note: no errors encountered even though delayed bugs were created

note: those delayed bugs will now be shown as internal compiler errors

error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler\rustc_trait_selection\src\traits\mod.rs:605:27 - disabled backtrace

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `H:\work\my\trash\rust-mini\static-la\rustc-ice-2025-03-28T01_04_59-12792.txt` to your bug report

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `static-la` (bin "static-la")
```

<details>
<summary>Backtrace </summary>

```
error: internal compiler error: Encountered anon const with inference variable args but no error reported
  |
  = note: delayed at compiler\rustc_trait_selection\src\traits\mod.rs:605:27
             0: std::backtrace_rs::backtrace::dbghelp64::trace
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
             1: std::backtrace_rs::backtrace::trace_unsynchronized
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
             2: std::backtrace::Backtrace::create
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\backtrace.rs:331
             3: std::backtrace::Backtrace::capture
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\backtrace.rs:296
             4: <rustc_errors::DiagCtxtHandle>::flush_delayed
             5: <rustc_errors::DiagCtxtHandle>::emit_diagnostic
             6: <rustc_span::ErrorGuaranteed as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
             7: RINvMs6_NtCs9VVGc76UbHk_9hashbrown3rawINtB6_8RawTableTjINtNtNtCs1vmCzCB8wM7_13rustc_type_ir12search_graph12global_cache12WithOverflowNtNtNtCsacCxZy8tNDM_12rustc_middle2ty7context6TyCtxtEEE14reserve_rehashNCINvNtB8_3map11make_hasherjBR_INtNtCs1HK5c7eE0eW_4c
             8: rustc_trait_selection::traits::try_evaluate_const
             9: <rustc_trait_selection::traits::normalize::AssocTypeNormalizer as rustc_type_ir::fold::TypeFolder<rustc_middle::ty::context::TyCtxt>>::fold_const
            10: <thin_vec::IntoIter<_> as core::ops::drop::Drop>::drop::drop_non_singleton::<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>
            11: <thin_vec::IntoIter<_> as core::ops::drop::Drop>::drop::drop_non_singleton::<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>
            12: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
            13: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
            14: <rustc_trait_selection::traits::select::SelectionContext>::select
            15: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
            16: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_type_ir::fold::FallibleTypeFolder<rustc_middle::ty::context::TyCtxt>>::try_fold_ty
            17: <rustc_trait_selection::traits::select::SelectionContext>::evaluate_root_obligation
            18: rustc_traits::evaluate_obligation::evaluate_obligation
            19: rustc_query_impl::plumbing::query_key_hash_verify_all
            20: RINvNtNtCs8Ehw5TsioVt_18rustc_query_system5query8plumbing17try_execute_queryINtCshEjB07rFK3d_16rustc_query_impl13DynamicConfigINtNtB4_6caches12DefaultCacheINtNtCs1vmCzCB8wM7_13rustc_type_ir9canonical19CanonicalQueryInputNtNtNtCsacCxZy8tNDM_12rustc_middle2t
            21: rustc_query_impl::plumbing::query_key_hash_verify_all
            22: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
            23: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::query::evaluate_obligation::InferCtxtExt>::predicate_may_hold
            24: <alloc::raw_vec::RawVec<rustc_hir_typeck::method::probe::Candidate>>::grow_one
            25: rustc_hir_typeck::method::probe::method_autoderef_steps
            26: rustc_hir_typeck::method::probe::method_autoderef_steps
            27: rustc_hir_typeck::typeck
            28: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir::visit::TypeVisitor<rustc_middle::ty::context::TyCtxt>>::visit_ty
            29: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir::visit::TypeVisitor<rustc_middle::ty::context::TyCtxt>>::visit_ty
            30: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir::visit::TypeVisitor<rustc_middle::ty::context::TyCtxt>>::visit_ty
            31: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir::visit::TypeVisitor<rustc_middle::ty::context::TyCtxt>>::visit_ty
            32: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir::visit::TypeVisitor<rustc_middle::ty::context::TyCtxt>>::visit_ty
            33: <<rustc_hir_typeck::fn_ctxt::FnCtxt>::deduce_closure_signature_from_predicates::MentionsTy as rustc_type_ir::visit::TypeVisitor<rustc_middle::ty::context::TyCtxt>>::visit_ty
            34: rustc_hir_typeck::typeck
            35: rustc_hir_typeck::typeck
            36: rustc_query_impl::plumbing::query_key_hash_verify_all
            37: RINvNtNtCs8Ehw5TsioVt_18rustc_query_system5query8plumbing17try_execute_queryINtCshEjB07rFK3d_16rustc_query_impl13DynamicConfigINtNtCsfk1N0zTQ1Ep_21rustc_data_structures9vec_cache8VecCacheNtNtCs8yPNJtyUAIM_10rustc_span6def_id10LocalDefIdINtNtNtCsacCxZy8tNDM
            38: rustc_query_impl::plumbing::query_key_hash_verify_all
            39: <hashbrown::raw::RawTable<(&usize, ())>>::reserve_rehash::<hashbrown::map::make_hasher<&usize, (), rustc_hash::FxBuildHasher>::{closure#0}>
            40: rustc_hir_analysis::check_crate
            41: rustc_interface::passes::resolver_for_lowering_raw
            42: rustc_interface::passes::analysis
            43: <alloc::sync::Arc<rustc_session::cstore::CrateSource>>::drop_slow
            44: RINvNtNtCs8Ehw5TsioVt_18rustc_query_system5query8plumbing17try_execute_queryINtCshEjB07rFK3d_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCsacCxZy8tNDM_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
            45: rustc_query_impl::query_system
            46: RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCskXJAKvAmGc7_5alloc5boxed3BoxDINtNtNtCs1HK5c7eE0eW_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECs13K
            47: RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCskXJAKvAmGc7_5alloc5boxed3BoxDINtNtNtCs1HK5c7eE0eW_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECs13K
            48: RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCsbLMVCc8CHyP_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCs13KITJ2Zc2G_17rustc_driver_i
            49: RINvNtNtCsaor5jccb5ur_3std3sys9backtrace28___rust_begin_short_backtraceNCNCNCINvMNtB6_6threadNtB1h_7Builder16spawn_unchecked_INtNtCskXJAKvAmGc7_5alloc5boxed3BoxDINtNtNtCs1HK5c7eE0eW_4core3ops8function6FnOnceuEp6OutputuNtNtB2G_6marker4SendEL_EuEs_000uECs13K
            50: alloc::boxed::impl$28::call_once
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\alloc\src\boxed.rs:1993
            51: alloc::boxed::impl$28::call_once
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\alloc\src\boxed.rs:1993
            52: std::sys::pal::windows::thread::impl$0::new::thread_start
                       at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library\std\src\sys\pal\windows\thread.rs:56
            53: BaseThreadInitThunk
            54: RtlUserThreadStart

```

**Comment by moxian** [comment]
Minimization for the original issue on 1.58.0:

```rs
// lib.rs
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

pub trait Matmul {
    type Output;

    fn matmul(&self) -> Self::Output;
}

impl<const M: usize> Matmul for MatrixSxS<M>
where
    [(); M * M]:,
{
    type Output = ();

    fn matmul(&self) -> Self::Output {
        todo!()
    }
}

pub struct MatrixSxS<const ROWS: usize> {
    data: [(); ROWS],
}
impl<const ROWS: usize> MatrixSxS<ROWS> {
    pub fn new() -> Self {
        todo!()
    }
}
```

```rs
// main.rs
use static_la::Matmul;

fn main() {
    let l = static_la::MatrixSxS::<0>::new();
    let _ = l.matmul();
}
```

This has been fixed in `nightly-2022-03-11`
*  #94440
<details>
<summary>cargo output</summary>

```
   Compiling static-la v0.2.4 (...)
   Compiling mycrate v0.1.0 (H:\work\my\trash\rust-mini\thing)
error: failed to evaluate generic const expression
  --> H:\work\my\trash\rust-mini\static-la\src\lib.rs:13:10
   |
13 |     [(); M * M]:,
   |          ^^^^^
   |
   = note: the crate this constant originates from uses `#![feature(generic_const_exprs)]`
help: consider enabling this feature
   |
1  | #![feature(generic_const_exprs)]
   |

error: could not compile `mycrate` due to previous error
```

</details>

I believe the test in #94440 covers this case well, enough. The issue can probably be closed.

@rustbot label: -E-needs-mcve +S-has-mcve
