### ISSUE TITLE
RuntimeError: src/stage0.json doesn't contain a checksum for dist/2022-01-28/rustc-beta-sparcv9-sun-solaris.tar.xz

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#94217]
Trying to build latest sources on SPARC Solaris and `./x.py` fails with:

```
downloading https://static.rust-lang.org/dist/2022-01-28/rust-std-beta-sparcv9-sun-solaris.tar.xz
###################################################################################################################################################################### 100.0%extracting /builds/psumbera/rustc-test/build/cache/2022-01-28/rust-std-beta-sparcv9-sun-solaris.tar.xz
Traceback (most recent call last):
  File "./x.py", line 27, in <module>
    bootstrap.main()
  File "/builds/psumbera/rustc-test/src/bootstrap/bootstrap.py", line 1325, in main
    bootstrap(help_triggered)
  File "/builds/psumbera/rustc-test/src/bootstrap/bootstrap.py", line 1291, in bootstrap
    build.download_toolchain()
  File "/builds/psumbera/rustc-test/src/bootstrap/bootstrap.py", line 456, in download_toolchain
    self._download_component_helper(filename, "rustc", tarball_suffix, stage0)
  File "/builds/psumbera/rustc-test/src/bootstrap/bootstrap.py", line 600, in _download_component_helper
    do_verify=stage0,
  File "/builds/psumbera/rustc-test/src/bootstrap/bootstrap.py", line 73, in get
    raise RuntimeError("src/stage0.json doesn't contain a checksum for {}".format(url))
RuntimeError: src/stage0.json doesn't contain a checksum for dist/2022-01-28/rustc-beta-sparcv9-sun-solaris.tar.xz
```

**Comment by Mark-Simulacrum** [comment]
sparcv9-sun-solaris is not a [tier 2 with host tools platform](https://doc.rust-lang.org/nightly/rustc/platform-support.html), so rustc is not available in precompiled form for that target. You'll have to cross-compile from a different machine, most likely.

**Comment by psumbera** [comment]
I build every released veresion using previous one. Is there way to build latest github version using latest released version 1.58.1? Is cross-compiling explained somewhere?

**Comment by Mark-Simulacrum** [comment]
To be clear, I don't believe sparv9-sun-solaris has *ever* been a tier 2 with host tools target. Did x.py work for you before? It might be that we're detecting a different build triple for some reason. The problem you're running into is precisely that no 'previous' version exists for this target triple.

I'm not sure there's a very detailed explanation, but https://rustc-dev-guide.rust-lang.org/building/new-target.html#cross-compiling has some very basic docs.

**Comment by psumbera** [comment]
> To be clear, I don't believe sparv9-sun-solaris has _ever_ been a tier 2 with host tools target. Did x.py work for you before? It might be that we're detecting a different build triple for some reason. The problem you're running into is precisely that no 'previous' version exists for this target triple.

It probably newer worked for me. I was mainly confused that it did download some existing archive and it failed later with python stack trace. I would hope at least for some error message (not supported platform?!).

**Comment by Mark-Simulacrum** [comment]
Yeah, we can probably improve the checksum error message to something like "pre-built artifacts not available for this target at this time, see [platform support] page" -- happy to take a PR doing so.

**Comment by jyn514** [comment]
Mentoring instructions: change https://github.com/rust-lang/rust/blob/05d22212e89588e7c443cc6b9bc0e4e02fdfbc8d/src/bootstrap/bootstrap.py#L73 to include "pre-built artifacts not available for this target at this time, see https://doc.rust-lang.org/nightly/rustc/platform-support.html"

@rustbot label: +A-docs +E-easy

**Comment by gimbles** [comment]
(Will send a PR after #95671 is merged)
