### ISSUE TITLE
ICE: collect_error_for_expanding_node() could not find error for var  '_#0r in universe

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#94378]
### Code

```Rust
fn f<'a, 'b, 'd, 'e> (
    x: for<'c> fn(
        fn(&'c fn(&'c ())),
        fn(&'c fn(&'c ())),
        fn(&'c fn(&'c ())),
        fn(&'c fn(&'c ())),
    )
) -> fn(
        fn(&'a fn(&'d ())),
        fn(&'b fn(&'d ())),
        fn(&'a fn(&'e ())),
        fn(&'b fn(&'e ())),
) {
    x
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (4b043faba 2022-02-24)
binary: rustc
commit-hash: 4b043faba34ccc053a4d0110634c323f6c03765e
commit-date: 2022-02-24
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### Error output

```
warning: function is never used: `f`
 --> ./11637.rs:1:4
  |
1 | fn f<'a, 'b, 'd, 'e> (
  |    ^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

error: internal compiler error: collect_error_for_expanding_node() could not find error for var '_#0r in universe U0, lower_bounds=[
                                    RegionAndOrigin(ReEarlyBound(1, 'b),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(0, 'a),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(1, 'b),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(0, 'a),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                ], upper_bounds=[
                                    RegionAndOrigin(ReEarlyBound(3, 'e),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(2, 'd),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(3, 'e),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(2, 'd),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                ]
  --> ./11637.rs:14:5
   |
14 |     x
   |     ^
   |
   = note: delayed at compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs:748:25
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
fn f<'a, 'b, 'd, 'e> (
    x: for<'c> fn(
        fn(&'c fn(&'c ())),
        fn(&'c fn(&'c ())),
        fn(&'c fn(&'c ())),
        fn(&'c fn(&'c ())),
    )
) -> fn(
        fn(&'a fn(&'d ())),
        fn(&'b fn(&'d ())),
        fn(&'a fn(&'e ())),
        fn(&'b fn(&'e ())),
) {
    x
}

fn main() {}
~/vcs/github/fuzzgen on  master [?] is 📦 v0.1.0 via 🦀 v1.61.0-nightly
✦ at 23:29:32 ❯ rustc ./11637.rs
warning: function is never used: `f`
 --> ./11637.rs:1:4
  |
1 | fn f<'a, 'b, 'd, 'e> (
  |    ^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted

error: internal compiler error: collect_error_for_expanding_node() could not find error for var '_#0r in universe U0, lower_bounds=[
                                    RegionAndOrigin(ReEarlyBound(1, 'b),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(0, 'a),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(1, 'b),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(0, 'a),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                ], upper_bounds=[
                                    RegionAndOrigin(ReEarlyBound(3, 'e),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(2, 'd),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(3, 'e),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                    RegionAndOrigin(ReEarlyBound(2, 'd),Subtype(TypeTrace { cause: ObligationCause { span: ./11637.rs:14:5: 14:6 (#0), body_id: HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 6 }, code: Some(BlockTailExpression(HirId { owner: DefId(0:3 ~ 11637[4988]::f), local_id: 5 })) }, values: Terms(ExpectedFound { expected: Ty(fn(fn(&'a fn(&'d ())), fn(&'b fn(&'d ())), fn(&'a fn(&'e ())), fn(&'b fn(&'e ())))), found: Ty(for<'c> fn(for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())), for<'c> fn(&'c for<'c> fn(&'c ())))) }) })),
                                ]
  --> ./11637.rs:14:5
   |
14 |     x
   |     ^
   |
   = note: delayed at compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs:748:25

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1176:13
stack backtrace:
   0:     0x7fa59dab7d4c - std::backtrace_rs::backtrace::libunwind::trace::h853a1389f6e5e745
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fa59dab7d4c - std::backtrace_rs::backtrace::trace_unsynchronized::h141fba7f3343285a
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa59dab7d4c - std::sys_common::backtrace::_print_fmt::h3413d0b0d4b31c4c
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fa59dab7d4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc867a15ccd0341f
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fa59db179fc - core::fmt::write::h35157148513e92bc
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fa59daa7e78 - std::io::Write::write_fmt::hc5517132c5cecddc
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/io/mod.rs:1657:15
   6:     0x7fa59dabbd27 - std::sys_common::backtrace::_print::hc5f683d445b22529
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fa59dabbd27 - std::sys_common::backtrace::print::hd841ed3190824cc9
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fa59dabbd27 - std::panicking::default_hook::{{closure}}::h9a0c56b9dbc35012
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:295:22
   9:     0x7fa59dabb9df - std::panicking::default_hook::hc46807a97c7de333
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:314:9
  10:     0x7fa59e24d0d1 - rustc_driver[442ed871d20551d1]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fa59dabc5f6 - std::panicking::rust_panic_with_hook::h1ad2fcf54bcf9bb5
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:702:17
  12:     0x7fa59dabc2a7 - std::panicking::begin_panic_handler::{{closure}}::hf8003c262b110425
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:588:13
  13:     0x7fa59dab8214 - std::sys_common::backtrace::__rust_end_short_backtrace::hba6e0d383beff798
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fa59dabbfb9 - rust_begin_unwind
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:584:5
  15:     0x7fa59da84943 - core::panicking::panic_fmt::h949e0ccd2ca80abd
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/core/src/panicking.rs:142:14
  16:     0x7fa59f2ca4fc - core[a2af605994515733]::panicking::panic_display::<&str>
  17:     0x7fa5a09372ff - <rustc_errors[1b480dc045645b1a]::HandlerInner>::flush_delayed
  18:     0x7fa5a09358da - <rustc_errors[1b480dc045645b1a]::HandlerInner as core[a2af605994515733]::ops::drop::Drop>::drop
  19:     0x7fa5a005b488 - core[a2af605994515733]::ptr::drop_in_place::<rustc_session[94f6c5c92635dd6]::parse::ParseSess>
  20:     0x7fa5a005d69a - <alloc[712883fc59a62f7]::rc::Rc<rustc_session[94f6c5c92635dd6]::session::Session> as core[a2af605994515733]::ops::drop::Drop>::drop
  21:     0x7fa5a004579c - core[a2af605994515733]::ptr::drop_in_place::<rustc_interface[65caae14b4217ef3]::interface::Compiler>
  22:     0x7fa5a004637c - rustc_span[cac29f2f15677c0e]::with_source_map::<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_interface[65caae14b4217ef3]::interface::create_compiler_and_run<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#1}>
  23:     0x7fa5a00439b1 - rustc_interface[65caae14b4217ef3]::interface::create_compiler_and_run::<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>
  24:     0x7fa5a002f372 - <scoped_tls[876471c7b20f8e0c]::ScopedKey<rustc_span[cac29f2f15677c0e]::SessionGlobals>>::set::<rustc_interface[65caae14b4217ef3]::interface::run_compiler<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>
  25:     0x7fa5a002ec2d - std[2a6da251afaa3124]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[65caae14b4217ef3]::util::run_in_thread_pool_with_globals<rustc_interface[65caae14b4217ef3]::interface::run_compiler<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>
  26:     0x7fa5a002d419 - <<std[2a6da251afaa3124]::thread::Builder>::spawn_unchecked_<rustc_interface[65caae14b4217ef3]::util::run_in_thread_pool_with_globals<rustc_interface[65caae14b4217ef3]::interface::run_compiler<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>::{closure#1} as core[a2af605994515733]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:     0x7fa59dac8183 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbda7b2dd6cb05b7b
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/alloc/src/boxed.rs:1854:9
  28:     0x7fa59dac8183 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e7c4e55f1ee6074
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/alloc/src/boxed.rs:1854:9
  29:     0x7fa59dac8183 - std::sys::unix::thread::Thread::new::thread_start::h272cda2d6cad9954
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys/unix/thread.rs:108:17
  30:     0x7fa59d9cd259 - start_thread
  31:     0x7fa59d8e95e3 - __GI___clone
  32:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (4b043faba 2022-02-24) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by JohnTitor** [comment]
Duplicate of #67498
