### ISSUE TITLE
encountered ambiguity selecting `T` during codegen, presuming due to overflow or prior type error

### ISSUE THREAD

**Issue by 0rphon** [rust-lang/rust#94720]
### Code

```Rust
#[macro_use]
extern crate rocket;

use rocket::response::stream::TextStream;
use rocket::tokio::time::{self, Duration};

/// Produce an infinite series of `"hello"`s, one per second.
#[get("/infinite-hellos")]
fn hello() -> TextStream![&'static str] {
    TextStream! {
        let mut interval = time::interval(Duration::from_secs(1));
        loop {
            yield "hello";
            interval.tick().await;
        }
    }
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![hello])
}
```

### Meta

encountered this while trying to run an example int he Rocket documentation. bug only exists on nightly. im using `rocket = "0.5.0-rc.1"`

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (e7aca8959 2022-02-09) running on x86_64-pc-windows-msvc
```

### Error output

```
D:\coding\Rust\playground>cargo run
   Compiling rocket v0.5.0-rc.1
error: internal compiler error: encountered ambiguity selecting `Binder(<response::stream::reader::ReaderStream<impl futures::Stream<Item = response::stream::raw_sse::RawLinedEvent>> as std::convert::From<impl futures::Stream<Item = response::stream::raw_sse::RawLinedEvent>>>, [])` during codegen, presuming due to overflow or prior type error
  |
  = note: delayed at compiler\rustc_trait_selection\src\traits\codegen.rs:54:32

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:1176:13
stack backtrace:
   0:     0x7ffdead57d30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a1cc8c1ba9a6ad
   1:     0x7ffdead8779a - core::fmt::write::h346f1639821b09ca
   2:     0x7ffdead49119 - <std::io::IoSlice as core::fmt::Debug>::fmt::h6ed49041e1bde020
   3:     0x7ffdead5b4a2 - std::panicking::default_hook::hb86a255b5ae1a1b5
   4:     0x7ffdead5b063 - std::panicking::default_hook::hb86a255b5ae1a1b5
   5:     0x7ffd9cc8ca76 - <rustc_driver[62efd2c0abe8586f]::args::Error as core[22e88df2c075810]::fmt::Debug>::fmt
   6:     0x7ffdead5bdd2 - std::panicking::rust_panic_with_hook::h0b2277542f9fb56f
   7:     0x7ffdead5bb1d - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h26c29f56be126ea1
   8:     0x7ffdead58687 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a1cc8c1ba9a6ad
   9:     0x7ffdead5b799 - rust_begin_unwind
  10:     0x7ffdeadba985 - core::panicking::panic_fmt::ha2acae3cf1e02ef3
  11:     0x7ffda13f6167 - <rustc_errors[c908d4787ee654d4]::ErrorReported as core[22e88df2c075810]::fmt::Debug>::fmt
  12:     0x7ffda13f2e38 - <rustc_errors[c908d4787ee654d4]::HandlerInner>::delay_as_bug
  13:     0x7ffda13ee342 - <rustc_errors[c908d4787ee654d4]::HandlerInner as core[22e88df2c075810]::ops::drop::Drop>::drop
  14:     0x7ffd9cc2fde4 - <rustc_driver[62efd2c0abe8586f]::args::Error as core[22e88df2c075810]::fmt::Debug>::fmt
  15:     0x7ffd9cc4bec7 - <rustc_driver[62efd2c0abe8586f]::args::Error as core[22e88df2c075810]::fmt::Debug>::fmt
  16:     0x7ffd9cc2586d - <rustc_middle[69d22b9b016ab07c]::ty::SymbolName as core[22e88df2c075810]::fmt::Debug>::fmt
  17:     0x7ffd9cc29b20 - <rustc_driver[62efd2c0abe8586f]::args::Error as core[22e88df2c075810]::fmt::Debug>::fmt
  18:     0x7ffd9cc1ef0a - <tracing_log[8e7bf0df484a8cae]::InfoCallsite as tracing_core[e4007ebade0f9e88]::callsite::Callsite>::set_interest
  19:     0x7ffd9cbff7c3 - <tracing_log[8e7bf0df484a8cae]::InfoCallsite as tracing_core[e4007ebade0f9e88]::callsite::Callsite>::set_interest
  20:     0x7ffd9cca2fa8 - rustc_driver[62efd2c0abe8586f]::pretty::print_after_hir_lowering
  21:     0x7ffdead6c73c - std::sys::windows::thread::Thread::new::h1745d7e554009389
  22:     0x7ffe55e37034 - BaseThreadInitThunk
  23:     0x7ffe56582651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (e7aca8959 2022-02-09) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rocket`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
included in error output section
```

</p>
</details>

**Comment by 0rphon** [comment]
fixed on latest nightly. my bad
