### ISSUE TITLE
Rustc panics with unwrap on Result on Err value: PlaceBuilder {...}

### ISSUE THREAD

**Issue by Lol3rrr** [rust-lang/rust#94882]
### Code

```Rust
<code>
```
The Code currently only exists on my custom OS Project, which is rather large and I will try to produce a smaller example in the coming Days, but in the mean time the full code can be found in [this repo](https://github.com/Lol3rrr/rucoonos/tree/7c17a99e6cbba08420db2ea9414cd9a965d4d76c).

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (335ffbfa5 2022-03-11)
binary: rustc
commit-hash: 335ffbfa547df94ac236f5c56130cecf99c8d82b
commit-date: 2022-03-11
host: aarch64-apple-darwin
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### Error output

```
<output>
```
Im not exactly sure what the difference between the Error and the Backtrace is in this Case, because it just panics on a Thread, can update if more information is needed

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: PlaceBuilder { base: Upvar { var_hir_id: HirId { owner: DefId(0:192 ~ rucoonos[e72e]::kernel::{impl#0}::get_rsdt_entries), local_id: 27 }, closure_def_id: DefId(0:194 ~ rucoonos[e72e]::kernel::{impl#0}::get_rsdt_entries::{closure#0}), closure_kind: FnMut }, projection: [Deref] }', compiler/rustc_mir_build/src/build/expr/as_place.rs:303:69
stack backtrace:
   0:        0x102ac66c8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0e3b7b62ff438a87
   1:        0x102b15cc4 - core::fmt::write::h861c00eee0917184
   2:        0x102ab9950 - std::io::Write::write_fmt::hac803542aea73937
   3:        0x102ac9488 - std::panicking::default_hook::{{closure}}::had1c822168f7b455
   4:        0x102ac9164 - ___umodti3
   5:        0x109c27b3c - rustc_driver[cec1b2f1f471d767]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x102ac9b64 - std::panicking::rust_panic_with_hook::h51234b973c0ae8b6
   7:        0x102ac99bc - std::panicking::begin_panic_handler::{{closure}}::hcbae14a9f156eca5
   8:        0x102ac6ba4 - std::sys_common::backtrace::__rust_end_short_backtrace::h8459f32d2895cbb8
   9:        0x102ac9714 - _rust_begin_unwind
  10:        0x102b44078 - core::panicking::panic_fmt::h78e9e8c98c0a1a5b
  11:        0x102b4411c - core::result::unwrap_failed::he742f0b52386971c
  12:        0x10c496b80 - <rustc_mir_build[b37d5e05ae945448]::build::expr::as_place::PlaceBuilder>::into_place
  13:        0x10c470118 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::as_read_only_place
  14:        0x10c4752cc - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest
  15:        0x10c474430 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::as_temp_inner
  16:        0x10c46f80c - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::as_operand
  17:        0x10c46febc - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::as_call_operand
  18:        0x10c49b2bc - <core[f207860729abbb87]::iter::adapters::copied::Copied<core[f207860729abbb87]::slice::iter::Iter<rustc_middle[d0a35b59270e849e]::thir::ExprId>> as core[f207860729abbb87]::iter::traits::iterator::Iterator>::fold::<(), core[f207860729abbb87]::iter::adapters::map::map_fold<rustc_middle[d0a35b59270e849e]::thir::ExprId, rustc_middle[d0a35b59270e849e]::mir::Operand, (), <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest::{closure#3}, core[f207860729abbb87]::iter::traits::iterator::Iterator::for_each::call<rustc_middle[d0a35b59270e849e]::mir::Operand, <alloc[5ac291e32a014fd7]::vec::Vec<rustc_middle[d0a35b59270e849e]::mir::Operand> as alloc[5ac291e32a014fd7]::vec::spec_extend::SpecExtend<rustc_middle[d0a35b59270e849e]::mir::Operand, core[f207860729abbb87]::iter::adapters::map::Map<core[f207860729abbb87]::iter::adapters::copied::Copied<core[f207860729abbb87]::slice::iter::Iter<rustc_middle[d0a35b59270e849e]::thir::ExprId>>, <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest::{closure#3}>>>::spec_extend::{closure#0}>::{closure#0}>::{closure#0}>
  19:        0x10c4b5ff8 - <alloc[5ac291e32a014fd7]::vec::Vec<rustc_middle[d0a35b59270e849e]::mir::Operand> as alloc[5ac291e32a014fd7]::vec::spec_from_iter::SpecFromIter<rustc_middle[d0a35b59270e849e]::mir::Operand, core[f207860729abbb87]::iter::adapters::map::Map<core[f207860729abbb87]::iter::adapters::copied::Copied<core[f207860729abbb87]::slice::iter::Iter<rustc_middle[d0a35b59270e849e]::thir::ExprId>>, <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest::{closure#3}>>>::from_iter
  20:        0x10c474e24 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest
  21:        0x10c483ec4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::in_scope::<<rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  22:        0x10c4751d4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest
  23:        0x10c46eaf4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::ast_block_stmts
  24:        0x10c4836a4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::in_scope::<<rustc_mir_build[b37d5e05ae945448]::build::Builder>::ast_block::{closure#2}::{closure#0}, ()>
  25:        0x10c475f64 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest
  26:        0x10c483ec4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::in_scope::<<rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  27:        0x10c4751d4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest
  28:        0x10c483ec4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::in_scope::<<rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  29:        0x10c4751d4 - <rustc_mir_build[b37d5e05ae945448]::build::Builder>::expr_into_dest
  30:        0x10c46bed4 - rustc_mir_build[b37d5e05ae945448]::build::construct_fn::<core[f207860729abbb87]::iter::adapters::chain::Chain<alloc[5ac291e32a014fd7]::vec::into_iter::IntoIter<rustc_mir_build[b37d5e05ae945448]::build::ArgInfo>, core[f207860729abbb87]::iter::adapters::map::Map<core[f207860729abbb87]::iter::adapters::enumerate::Enumerate<core[f207860729abbb87]::slice::iter::Iter<rustc_hir[3c3be1e1f126bca9]::hir::Param>>, rustc_mir_build[b37d5e05ae945448]::build::mir_build::{closure#1}::{closure#0}>>>
  31:        0x10c4cd2f0 - <rustc_infer[378f2b88dbffb5d6]::infer::InferCtxtBuilder>::enter::<rustc_middle[d0a35b59270e849e]::mir::Body, rustc_mir_build[b37d5e05ae945448]::build::mir_build::{closure#1}>
  32:        0x10c46a8fc - rustc_mir_build[b37d5e05ae945448]::build::mir_built
  33:        0x10caefe4c - <rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind as rustc_query_system[7c0f1b07d3feb58e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>::{closure#0}, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>
  34:        0x10cb5073c - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>
  35:        0x10c94be84 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>>
  36:        0x10ca296bc - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::mir_built, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  37:        0x10cc2929c - <rustc_query_impl[89e41333fdae4439]::Queries as rustc_middle[d0a35b59270e849e]::ty::query::QueryEngine>::mir_built
  38:        0x10be97aa0 - rustc_mir_transform[371423e12b40b9df]::check_unsafety::unsafety_check_result
  39:        0x10be945ec - <rustc_mir_transform[371423e12b40b9df]::check_unsafety::provide::{closure#0} as core[f207860729abbb87]::ops::function::FnOnce<(rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId)>>::call_once
  40:        0x10cb5d658 - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId, &rustc_middle[d0a35b59270e849e]::mir::query::UnsafetyCheckResult>
  41:        0x10c95bfd4 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_span[b0496855f7b53c19]::def_id::LocalDefId, &rustc_middle[d0a35b59270e849e]::mir::query::UnsafetyCheckResult>>
  42:        0x10ca03d88 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::unsafety_check_result, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  43:        0x10be962ac - <rustc_mir_transform[371423e12b40b9df]::check_unsafety::UnsafetyChecker as rustc_middle[d0a35b59270e849e]::mir::visit::Visitor>::visit_rvalue
  44:        0x10be97ba4 - rustc_mir_transform[371423e12b40b9df]::check_unsafety::unsafety_check_result
  45:        0x10be945ec - <rustc_mir_transform[371423e12b40b9df]::check_unsafety::provide::{closure#0} as core[f207860729abbb87]::ops::function::FnOnce<(rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId)>>::call_once
  46:        0x10cb5d658 - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId, &rustc_middle[d0a35b59270e849e]::mir::query::UnsafetyCheckResult>
  47:        0x10c95bfd4 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_span[b0496855f7b53c19]::def_id::LocalDefId, &rustc_middle[d0a35b59270e849e]::mir::query::UnsafetyCheckResult>>
  48:        0x10ca03d88 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::unsafety_check_result, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  49:        0x10be9e824 - rustc_mir_transform[371423e12b40b9df]::mir_const
  50:        0x10caefe4c - <rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind as rustc_query_system[7c0f1b07d3feb58e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>::{closure#0}, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>
  51:        0x10cb5073c - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>
  52:        0x10c94be84 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>>>
  53:        0x10ca29828 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::mir_const, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  54:        0x10cc292d8 - <rustc_query_impl[89e41333fdae4439]::Queries as rustc_middle[d0a35b59270e849e]::ty::query::QueryEngine>::mir_const
  55:        0x10be9f0b4 - rustc_mir_transform[371423e12b40b9df]::mir_promoted
  56:        0x10caeff20 - <rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind as rustc_query_system[7c0f1b07d3feb58e]::dep_graph::DepKind>::with_deps::<<rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, (&rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_index[a6e710b87827e4cd]::vec::IndexVec<rustc_middle[d0a35b59270e849e]::mir::Promoted, rustc_middle[d0a35b59270e849e]::mir::Body>>)>::{closure#0}, (&rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_index[a6e710b87827e4cd]::vec::IndexVec<rustc_middle[d0a35b59270e849e]::mir::Promoted, rustc_middle[d0a35b59270e849e]::mir::Body>>)>
  57:        0x10cb50b3c - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_middle[d0a35b59270e849e]::ty::WithOptConstParam<rustc_span[b0496855f7b53c19]::def_id::LocalDefId>, (&rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_middle[d0a35b59270e849e]::mir::Body>, &rustc_data_structures[c8bf790fc1a513cb]::steal::Steal<rustc_index[a6e710b87827e4cd]::vec::IndexVec<rustc_middle[d0a35b59270e849e]::mir::Promoted, rustc_middle[d0a35b59270e849e]::mir::Body>>)>
  58:        0x10c9e9e14 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::mir_promoted, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  59:        0x10cc29428 - <rustc_query_impl[89e41333fdae4439]::Queries as rustc_middle[d0a35b59270e849e]::ty::query::QueryEngine>::mir_promoted
  60:        0x10c5fa7f0 - rustc_borrowck[d1378c39f644c876]::mir_borrowck
  61:        0x10c5de3b0 - <rustc_borrowck[d1378c39f644c876]::provide::{closure#0} as core[f207860729abbb87]::ops::function::FnOnce<(rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId)>>::call_once
  62:        0x10cb5d208 - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId, &rustc_middle[d0a35b59270e849e]::mir::query::BorrowCheckResult>
  63:        0x10c95b31c - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_span[b0496855f7b53c19]::def_id::LocalDefId, &rustc_middle[d0a35b59270e849e]::mir::query::BorrowCheckResult>>
  64:        0x10c9e949c - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::mir_borrowck, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  65:        0x10c18b958 - rustc_typeck[af8f2b698ab9d9c3]::collect::type_of::type_of
  66:        0x10cb649d8 - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::DefId, rustc_middle[d0a35b59270e849e]::ty::Ty>
  67:        0x10c973078 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_span[b0496855f7b53c19]::def_id::DefId, rustc_middle[d0a35b59270e849e]::ty::Ty>>
  68:        0x10ca27730 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::type_of, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  69:        0x10c1dc6c4 - rustc_typeck[af8f2b698ab9d9c3]::check::check::check_item_type
  70:        0x10c155160 - <rustc_middle[d0a35b59270e849e]::hir::map::Map>::visit_item_likes_in_module::<rustc_typeck[af8f2b698ab9d9c3]::check::CheckItemTypesVisitor>
  71:        0x10c1e07fc - rustc_typeck[af8f2b698ab9d9c3]::check::check::check_mod_item_types
  72:        0x10cb5df00 - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, rustc_span[b0496855f7b53c19]::def_id::LocalDefId, ()>
  73:        0x10c95d91c - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<rustc_span[b0496855f7b53c19]::def_id::LocalDefId, ()>>
  74:        0x10c9fe294 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::check_mod_item_types, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  75:        0x10c153b48 - <rustc_middle[d0a35b59270e849e]::hir::map::Map>::for_each_module::<rustc_typeck[af8f2b698ab9d9c3]::check_crate::{closure#6}::{closure#0}>
  76:        0x10c0d5490 - <rustc_session[dd162c890e5a100c]::session::Session>::time::<(), rustc_typeck[af8f2b698ab9d9c3]::check_crate::{closure#6}>
  77:        0x10c0d4ff8 - rustc_typeck[af8f2b698ab9d9c3]::check_crate
  78:        0x109d10998 - rustc_interface[9ef54a0254148c6e]::passes::analysis
  79:        0x10cb7ca18 - <rustc_query_system[7c0f1b07d3feb58e]::dep_graph::graph::DepGraph<rustc_middle[d0a35b59270e849e]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0a35b59270e849e]::ty::context::TyCtxt, (), core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>
  80:        0x10c99181c - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::try_execute_query::<rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt, rustc_query_system[7c0f1b07d3feb58e]::query::caches::DefaultCache<(), core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>>
  81:        0x10ca27878 - rustc_query_system[7c0f1b07d3feb58e]::query::plumbing::get_query::<rustc_query_impl[89e41333fdae4439]::queries::analysis, rustc_query_impl[89e41333fdae4439]::plumbing::QueryCtxt>
  82:        0x109c14188 - <rustc_interface[9ef54a0254148c6e]::passes::QueryContext>::enter::<rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>
  83:        0x109bc5fc0 - <rustc_interface[9ef54a0254148c6e]::interface::Compiler>::enter::<rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}::{closure#2}, core[f207860729abbb87]::result::Result<core[f207860729abbb87]::option::Option<rustc_interface[9ef54a0254148c6e]::queries::Linker>, rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>
  84:        0x109be3c80 - rustc_span[b0496855f7b53c19]::with_source_map::<core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>, rustc_interface[9ef54a0254148c6e]::interface::create_compiler_and_run<core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>, rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}>::{closure#1}>
  85:        0x109bc7944 - rustc_interface[9ef54a0254148c6e]::interface::create_compiler_and_run::<core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>, rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}>
  86:        0x109bbf914 - <scoped_tls[6dad880d7cbb7886]::ScopedKey<rustc_span[b0496855f7b53c19]::SessionGlobals>>::set::<rustc_interface[9ef54a0254148c6e]::interface::run_compiler<core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>, rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}>::{closure#0}, core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>
  87:        0x109bbc58c - std[2e288d1f06d78e3c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9ef54a0254148c6e]::util::run_in_thread_pool_with_globals<rustc_interface[9ef54a0254148c6e]::interface::run_compiler<core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>, rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}>::{closure#0}, core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>::{closure#0}, core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>
  88:        0x109bea14c - <<std[2e288d1f06d78e3c]::thread::Builder>::spawn_unchecked_<rustc_interface[9ef54a0254148c6e]::util::run_in_thread_pool_with_globals<rustc_interface[9ef54a0254148c6e]::interface::run_compiler<core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>, rustc_driver[cec1b2f1f471d767]::run_compiler::{closure#1}>::{closure#0}, core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>::{closure#0}, core[f207860729abbb87]::result::Result<(), rustc_errors[50a1034c68026d26]::ErrorGuaranteed>>::{closure#1} as core[f207860729abbb87]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  89:        0x102ad27c8 - std::sys::unix::thread::Thread::new::thread_start::h31aa346fa54e82a3
  90:        0x1b8d25240 - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (335ffbfa5 2022-03-11) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries::{closure#0}`
#2 [unsafety_check_result] unsafety-checking `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries`
#3 [mir_const] processing MIR for `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries`
#4 [mir_promoted] processing `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries`
#5 [mir_borrowck] borrow-checking `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries`
#6 [type_of] computing type of `kernel::<impl at src/kernel.rs:23:1: 156:2>::get_rsdt_entries::{opaque#0}`
#7 [check_mod_item_types] checking item types in module `kernel`
#8 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by Enselic** [comment]
Triage: A minimal reproducer is needed to make progress here. Feel free to re-open after providing one. Closing for now.
