### ISSUE TITLE
compiling rust on OpenBSD

### ISSUE THREAD

**Issue by sandeep-gh** [rust-lang/rust#94888]
Rust is available in OpenBSD as part of standard package, however the version is bit old and is giving problems. I am trying  to compile latest rust on openBSD but runs into this error:
```
Traceback (most recent call last):
  File "/home/shared/downloads/rust/./x.py", line 27, in <module>
    bootstrap.main()
  File "/home/shared/downloads/rust/src/bootstrap/bootstrap.py", line 1324, in main
    bootstrap(help_triggered)
  File "/home/shared/downloads/rust/src/bootstrap/bootstrap.py", line 1293, in bootstrap
    build.download_toolchain()
  File "/home/shared/downloads/rust/src/bootstrap/bootstrap.py", line 453, in download_toolchain
    self._download_component_helper(filename, pattern, tarball_suffix, stage0)
  File "/home/shared/downloads/rust/src/bootstrap/bootstrap.py", line 594, in _download_component_helper
    get(
  File "/home/shared/downloads/rust/src/bootstrap/bootstrap.py", line 73, in get
    raise RuntimeError("src/stage0.json doesn't contain a checksum for {}".format(url))
RuntimeError: src/stage0.json doesn't contain a checksum for dist/2022-02-22/rust-std-beta-aarch64-unknown-openbsd.tar.xz
```

Is there a workaround?  Why there is no checksum for this file in src/stage0.json. Can I compute the checksum and manually add it to src/stage0.json?

**Comment by Hukadan** [comment]
The OpenBSD Rust maintainer wrote a script to compile more recent versions of Rust (https://github.com/semarie/build-rust). May be you can have a look at how the script does.

**Comment by Dylan-DPC** [comment]
Closing this issue to clean up the issue tracker.
