### ISSUE TITLE
ICE: rustc' panicked at 'called `Option::unwrap()` on a `None` value', .../definitions.rs:452:14

### ISSUE THREAD

**Issue by ArthurKValladares** [rust-lang/rust#95248]
Sorry for not providing a lot of details, I currently can't dedicate the time to find a minimal repro. I'll try to at least update the post with a backtrace in the near future.

### Meta

`rustc --version --verbose`:
```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-apple-darwin
release: 1.58.1
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.1 (db9d1b20b 2022-01-20) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C codegen-units=16 -C debuginfo=2 -C incremental -C target-cpu=native -C link-arg=-undefined -C link-arg=dynamic_lookup --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `texture::Texture: core::marker::Send`
#1 [check_item_well_formed] checking that `shader_technique::default::<impl at brainstorm/src/gal/src/shader_technique/default.rs:39:1: 60:2>` is well-formed
end of query stack
```

**Comment by compiler-errors** [comment]
@ArthurKValladares, do you have a repo that reproduces this?

**Comment by ArthurKValladares** [comment]
Sadly not quite yet, this is in code I can't share, and there is no clear path to an easy minimal repro. I'll try to dedicate some time to finding a repro in the next few weeks.

**Comment by compiler-errors** [comment]
No worries and no rush. Thanks for the update, was just curious..

**Comment by workingjubilee** [comment]
As this is from version 1.58.1, I am closing as a likely functional duplicate of this issue. Several fixes were put in to place to resolve this, see the PRs.
- https://github.com/rust-lang/rust/issues/92987
- https://github.com/rust-lang/rust/pull/91919
- https://github.com/rust-lang/rust/pull/93064
