### ISSUE TITLE
Two ICE with `.into()` conversion into TAIT

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#95628]
### Code

```Rust
#![feature(type_alias_impl_trait)]

type T = impl Sized;

struct Foo;

impl Into<T> for Foo {
    fn into(self) -> T {}
}

fn main(){
    let _: T = Foo.into();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (76d770ac2 2022-04-02)
binary: rustc
commit-hash: 76d770ac21d9521db6a92a48c7b3d5b2cc535941
commit-date: 2022-04-02
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0

```

### Error output

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorGuaranteed(())', compiler/rustc_monomorphize/src/collector.rs:899:84
stack backtrace:
   <<<first backtrace>>>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (76d770ac2 2022-04-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(~const TraitPredicate(<() as std::convert::From<Foo>>, polarity:Positive), []), depth=1),Unimplemented)]` resolving bounds outside of type inference
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:125:24

error: internal compiler error: Encountered error `Unimplemented` selecting `Binder(<() as std::convert::From<Foo>>, [])` during codegen
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:65:43

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1309:13
stack backtrace:
   <<<second backtrace>>>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (76d770ac2 2022-04-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `foo`

```

<details><summary><strong>First backtrace</strong></summary>
<p>

```
0:     0x7f1f119294fd - std::backtrace_rs::backtrace::libunwind::trace::h701a19af54e96518
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1f119294fd - std::backtrace_rs::backtrace::trace_unsynchronized::h72ee8a54c0971fed
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1f119294fd - std::sys_common::backtrace::_print_fmt::h107ba6740bde4568
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f1f119294fd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ef53fbc8fdae4ac
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f1f1198335c - core::fmt::write::h65db65649c4a3094
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f1f1191aa51 - std::io::Write::write_fmt::h2a783718d67af8f3
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/io/mod.rs:1655:15
   6:     0x7f1f1192c5e5 - std::sys_common::backtrace::_print::he0510d2c6a87b26b
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f1f1192c5e5 - std::sys_common::backtrace::print::hd2a99ac691f33dce
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f1f1192c5e5 - std::panicking::default_hook::{{closure}}::hf449f9dd4998781a
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:295:22
   9:     0x7f1f1192c299 - std::panicking::default_hook::he8f54f41bcecb62f
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:314:9
  10:     0x7f1f120ae5a1 - rustc_driver[567d1d5f3a7c5811]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f1f1192cd30 - std::panicking::rust_panic_with_hook::h3c6fb7c0bbe9c7a1
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:702:17
  12:     0x7f1f1192cb67 - std::panicking::begin_panic_handler::{{closure}}::h1fbef4cbf40a70cf
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:588:13
  13:     0x7f1f119299b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h8fee2597b379cc21
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f1f1192c899 - rust_begin_unwind
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:584:5
  15:     0x7f1f118f09e3 - core::panicking::panic_fmt::h4c16adcdb276f16f
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/panicking.rs:143:14
  16:     0x7f1f118f0ad3 - core::result::unwrap_failed::h4642b44f48942d78
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/result.rs:1785:5
  17:     0x7f1f13384811 - rustc_monomorphize[416ef71b399942e6]::collector::collect_neighbours
  18:     0x7f1f1337c7b4 - rustc_monomorphize[416ef71b399942e6]::collector::collect_items_rec
  19:     0x7f1f1337c918 - rustc_monomorphize[416ef71b399942e6]::collector::collect_items_rec
  20:     0x7f1f1410006b - <rustc_session[1bd44c9aeaf68c2e]::session::Session>::time::<(), rustc_monomorphize[416ef71b399942e6]::collector::collect_crate_mono_items::{closure#1}>
  21:     0x7f1f140f187b - rustc_monomorphize[416ef71b399942e6]::collector::collect_crate_mono_items
  22:     0x7f1f140f83b6 - rustc_monomorphize[416ef71b399942e6]::partitioning::collect_and_partition_mono_items
  23:     0x7f1f12a1b6a8 - <rustc_middle[80ce3c200b65c1bf]::dep_graph::dep_node::DepKind as rustc_query_system[a211d6db6b7bb5c6]::dep_graph::DepKind>::with_deps::<<rustc_query_system[a211d6db6b7bb5c6]::dep_graph::graph::DepGraph<rustc_middle[80ce3c200b65c1bf]::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle[80ce3c200b65c1bf]::ty::context::TyCtxt, (), (&std[f62804d94bf33ed9]::collections::hash::set::HashSet<rustc_span[590a2279fe342e71]::def_id::DefId, core[48d2d63575a1b4fb]::hash::BuildHasherDefault<rustc_hash[7354581e907369c7]::FxHasher>>, &[rustc_middle[80ce3c200b65c1bf]::mir::mono::CodegenUnit])>::{closure#0}, (&std[f62804d94bf33ed9]::collections::hash::set::HashSet<rustc_span[590a2279fe342e71]::def_id::DefId, core[48d2d63575a1b4fb]::hash::BuildHasherDefault<rustc_hash[7354581e907369c7]::FxHasher>>, &[rustc_middle[80ce3c200b65c1bf]::mir::mono::CodegenUnit])>
  24:     0x7f1f12a96061 - <rustc_query_system[a211d6db6b7bb5c6]::dep_graph::graph::DepGraph<rustc_middle[80ce3c200b65c1bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[80ce3c200b65c1bf]::ty::context::TyCtxt, (), (&std[f62804d94bf33ed9]::collections::hash::set::HashSet<rustc_span[590a2279fe342e71]::def_id::DefId, core[48d2d63575a1b4fb]::hash::BuildHasherDefault<rustc_hash[7354581e907369c7]::FxHasher>>, &[rustc_middle[80ce3c200b65c1bf]::mir::mono::CodegenUnit])>
  25:     0x7f1f14440eeb - rustc_query_system[a211d6db6b7bb5c6]::query::plumbing::try_execute_query::<rustc_query_impl[41c9f61e780c6183]::plumbing::QueryCtxt, rustc_query_system[a211d6db6b7bb5c6]::query::caches::DefaultCache<(), (&std[f62804d94bf33ed9]::collections::hash::set::HashSet<rustc_span[590a2279fe342e71]::def_id::DefId, core[48d2d63575a1b4fb]::hash::BuildHasherDefault<rustc_hash[7354581e907369c7]::FxHasher>>, &[rustc_middle[80ce3c200b65c1bf]::mir::mono::CodegenUnit])>>
  26:     0x7f1f14477cc0 - rustc_query_system[a211d6db6b7bb5c6]::query::plumbing::get_query::<rustc_query_impl[41c9f61e780c6183]::queries::collect_and_partition_mono_items, rustc_query_impl[41c9f61e780c6183]::plumbing::QueryCtxt>
  27:     0x7f1f145393b2 - <rustc_query_impl[41c9f61e780c6183]::Queries as rustc_middle[80ce3c200b65c1bf]::ty::query::QueryEngine>::collect_and_partition_mono_items
  28:     0x7f1f13f9fc10 - <rustc_codegen_llvm[f548226652d86d9e]::LlvmCodegenBackend as rustc_codegen_ssa[3efb108933ead5fe]::traits::backend::CodegenBackend>::codegen_crate
  29:     0x7f1f13f6cda7 - <rustc_session[1bd44c9aeaf68c2e]::session::Session>::time::<alloc[43519ed41124516]::boxed::Box<dyn core[48d2d63575a1b4fb]::any::Any>, rustc_interface[f5b05d2a4419ce67]::passes::start_codegen::{closure#0}>
  30:     0x7f1f13f63c6b - <rustc_interface[f5b05d2a4419ce67]::passes::QueryContext>::enter::<<rustc_interface[f5b05d2a4419ce67]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[48d2d63575a1b4fb]::result::Result<alloc[43519ed41124516]::boxed::Box<dyn core[48d2d63575a1b4fb]::any::Any>, rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  31:     0x7f1f13f911df - <rustc_interface[f5b05d2a4419ce67]::queries::Queries>::ongoing_codegen
  32:     0x7f1f13f29dbb - <rustc_interface[f5b05d2a4419ce67]::interface::Compiler>::enter::<rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}::{closure#2}, core[48d2d63575a1b4fb]::result::Result<core[48d2d63575a1b4fb]::option::Option<rustc_interface[f5b05d2a4419ce67]::queries::Linker>, rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  33:     0x7f1f13f3d89f - rustc_span[590a2279fe342e71]::with_source_map::<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_interface[f5b05d2a4419ce67]::interface::create_compiler_and_run<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#1}>
  34:     0x7f1f13f2a9b7 - <scoped_tls[6c583823b66fe937]::ScopedKey<rustc_span[590a2279fe342e71]::SessionGlobals>>::set::<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  35:     0x7f1f13f51e3f - std[f62804d94bf33ed9]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f5b05d2a4419ce67]::util::run_in_thread_pool_with_globals<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  36:     0x7f1f13f3d359 - <<std[f62804d94bf33ed9]::thread::Builder>::spawn_unchecked_<rustc_interface[f5b05d2a4419ce67]::util::run_in_thread_pool_with_globals<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#1} as core[48d2d63575a1b4fb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7f1f11936f23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5f2cc5c325bd6f26
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
  38:     0x7f1f11936f23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1873871631f0e48e
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
  39:     0x7f1f11936f23 - std::sys::unix::thread::Thread::new::thread_start::he96d38568e3469f7
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7f1f1183c609 - start_thread
  41:     0x7f1f11755163 - clone
  42:                0x0 - <unknown>
```

</p>
</details>

<details><summary><strong>Second backtrace</strong></summary>
<p>

```
0:     0x7f1f119294fd - std::backtrace_rs::backtrace::libunwind::trace::h701a19af54e96518
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f1f119294fd - std::backtrace_rs::backtrace::trace_unsynchronized::h72ee8a54c0971fed
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1f119294fd - std::sys_common::backtrace::_print_fmt::h107ba6740bde4568
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f1f119294fd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ef53fbc8fdae4ac
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f1f1198335c - core::fmt::write::h65db65649c4a3094
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f1f1191aa51 - std::io::Write::write_fmt::h2a783718d67af8f3
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/io/mod.rs:1655:15
   6:     0x7f1f1192c5e5 - std::sys_common::backtrace::_print::he0510d2c6a87b26b
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f1f1192c5e5 - std::sys_common::backtrace::print::hd2a99ac691f33dce
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f1f1192c5e5 - std::panicking::default_hook::{{closure}}::hf449f9dd4998781a
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:295:22
   9:     0x7f1f1192c299 - std::panicking::default_hook::he8f54f41bcecb62f
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:314:9
  10:     0x7f1f120ae5a1 - rustc_driver[567d1d5f3a7c5811]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f1f1192cd30 - std::panicking::rust_panic_with_hook::h3c6fb7c0bbe9c7a1
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:702:17
  12:     0x7f1f13162321 - std[f62804d94bf33ed9]::panicking::begin_panic::<rustc_errors[8f15b138673742da]::ExplicitBug>::{closure#0}
  13:     0x7f1f13161ff6 - std[f62804d94bf33ed9]::sys_common::backtrace::__rust_end_short_backtrace::<std[f62804d94bf33ed9]::panicking::begin_panic<rustc_errors[8f15b138673742da]::ExplicitBug>::{closure#0}, !>
  14:     0x7f1f1316947f - std[f62804d94bf33ed9]::panicking::begin_panic::<rustc_errors[8f15b138673742da]::ExplicitBug>
  15:     0x7f1f13175cf6 - std[f62804d94bf33ed9]::panic::panic_any::<rustc_errors[8f15b138673742da]::ExplicitBug>
  16:     0x7f1f148323aa - <rustc_errors[8f15b138673742da]::HandlerInner as core[48d2d63575a1b4fb]::ops::drop::Drop>::drop
  17:     0x7f1f13f54838 - core[48d2d63575a1b4fb]::ptr::drop_in_place::<rustc_session[1bd44c9aeaf68c2e]::parse::ParseSess>
  18:     0x7f1f13f57cfa - <alloc[43519ed41124516]::rc::Rc<rustc_session[1bd44c9aeaf68c2e]::session::Session> as core[48d2d63575a1b4fb]::ops::drop::Drop>::drop
  19:     0x7f1f13f3e39d - core[48d2d63575a1b4fb]::ptr::drop_in_place::<rustc_interface[f5b05d2a4419ce67]::interface::Compiler>
  20:     0x7f1f13f3df25 - rustc_span[590a2279fe342e71]::with_source_map::<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_interface[f5b05d2a4419ce67]::interface::create_compiler_and_run<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7f1f13f2a9b7 - <scoped_tls[6c583823b66fe937]::ScopedKey<rustc_span[590a2279fe342e71]::SessionGlobals>>::set::<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  22:     0x7f1f13f51e3f - std[f62804d94bf33ed9]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f5b05d2a4419ce67]::util::run_in_thread_pool_with_globals<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>
  23:     0x7f1f13f3d359 - <<std[f62804d94bf33ed9]::thread::Builder>::spawn_unchecked_<rustc_interface[f5b05d2a4419ce67]::util::run_in_thread_pool_with_globals<rustc_interface[f5b05d2a4419ce67]::interface::run_compiler<core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>, rustc_driver[567d1d5f3a7c5811]::run_compiler::{closure#1}>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#0}, core[48d2d63575a1b4fb]::result::Result<(), rustc_errors[8f15b138673742da]::ErrorGuaranteed>>::{closure#1} as core[48d2d63575a1b4fb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f1f11936f23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5f2cc5c325bd6f26
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
  25:     0x7f1f11936f23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1873871631f0e48e
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
  26:     0x7f1f11936f23 - std::sys::unix::thread::Thread::new::thread_start::he96d38568e3469f7
                               at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f1f1183c609 - start_thread
  28:     0x7f1f11755163 - clone
  29:                0x0 - <unknown>
```

</p>
</details>

**Comment by oli-obk** [comment]
Essentially a duplicate of https://github.com/rust-lang/rust/issues/84660

Opaque types in trait impl signatures should be illegal and we're just missing some checks for that

**Comment by JohnTitor** [comment]
Triage: Should've been fixed by #95973, seems a regression test included in that PR is sufficient. @oli-obk could we just close this issue?

**Comment by oli-obk** [comment]
Oh yea 😆 thanks!
