### ISSUE TITLE
`cargo doc` ICE for crate `crossbeam`

### ISSUE THREAD

**Issue by usamoi** [rust-lang/rust#95768]
It looks related to https://github.com/rust-lang/rust/issues/93476.

### Code

`Cargo.toml`:

```toml
[dependencies]
crossbeam = "0.8.1"
```

### Meta

`rustdoc --version --verbose`:
```
rustdoc 1.62.0-nightly (306ba8357 2022-04-05)
binary: rustdoc
commit-hash: 306ba8357fb36212b7d30efb9eb9e41659ac1445
commit-date: 2022-04-05
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.0
```

### Error output

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (306ba8357 2022-04-05) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `crossbeam`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name crossbeam /home/usamoi/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.8.1/src/lib.rs --cap-lints allow -o /home/usamoi/USAMOI/Repos/PlayRust/target/doc --cfg 'feature="alloc"' --cfg 'feature="crossbeam-channel"' --cfg 'feature="crossbeam-deque"' --cfg 'feature="crossbeam-epoch"' --cfg 'feature="crossbeam-queue"' --cfg 'feature="default"' --cfg 'feature="std"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=6876eeb4d8d71469 -L dependency=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps --extern cfg_if=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps/libcfg_if-88879d2dc0fa106c.rmeta --extern crossbeam_channel=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps/libcrossbeam_channel-ef379b2d252a7012.rmeta --extern crossbeam_deque=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps/libcrossbeam_deque-7d979b10f86f70f3.rmeta --extern crossbeam_epoch=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps/libcrossbeam_epoch-3fbf110ece6a5f8c.rmeta --extern crossbeam_queue=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps/libcrossbeam_queue-3cce81e21c4b5545.rmeta --extern crossbeam_utils=/home/usamoi/USAMOI/Repos/PlayRust/target/debug/deps/libcrossbeam_utils-29020a11a4342d35.rmeta --crate-version 0.8.1` (exit status: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 Documenting crossbeam v0.8.1
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:977:16
stack backtrace:
   0:     0x7f93e8a9ddbd - std::backtrace_rs::backtrace::libunwind::trace::hed55b2655d2d24d4
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f93e8a9ddbd - std::backtrace_rs::backtrace::trace_unsynchronized::hdb09b6d01f28fc36
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f93e8a9ddbd - std::sys_common::backtrace::_print_fmt::h85d73dd15e59a966
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f93e8a9ddbd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h467642c35f832dfc
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f93e8af7bfc - core::fmt::write::h80ceeb54ece7aa73
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f93e8a8f671 - std::io::Write::write_fmt::hdad4cd8743ef8ba3
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/io/mod.rs:1655:15
   6:     0x7f93e8aa0ce5 - std::sys_common::backtrace::_print::h7e8d4c312968a3a4
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f93e8aa0ce5 - std::sys_common::backtrace::print::he2f3552019b2ee9b
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f93e8aa0ce5 - std::panicking::default_hook::{{closure}}::hf0781cd99cbd97bb
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/panicking.rs:295:22
   9:     0x7f93e8aa0959 - std::panicking::default_hook::h3afb6754f35bb197
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/panicking.rs:314:9
  10:     0x7f93e92d02b1 - rustc_driver[7757471c23bcdd79]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f93e8aa1480 - std::panicking::rust_panic_with_hook::he026b558348e638c
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/panicking.rs:702:17
  12:     0x7f93e8aa12b7 - std::panicking::begin_panic_handler::{{closure}}::h7d8266517b3a97b3
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/panicking.rs:588:13
  13:     0x7f93e8a9e274 - std::sys_common::backtrace::__rust_end_short_backtrace::hd820e490164f416e
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f93e8aa0fe9 - rust_begin_unwind
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/panicking.rs:584:5
  15:     0x7f93e8a65603 - core::panicking::panic_fmt::h8045f7299830fe26
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/core/src/panicking.rs:143:14
  16:     0x7f93e8af4a11 - core::panicking::panic_display::ha27eeb85d241feec
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/core/src/panicking.rs:72:5
  17:     0x7f93e8af49bb - core::panicking::panic_str::hd3774d6781b8e176
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/core/src/panicking.rs:56:5
  18:     0x7f93e8a65476 - core::option::expect_failed::ha693a582e4ea86cf
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/core/src/option.rs:1874:5
  19:     0x561beaebdb29 - rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::resolve_associated_trait_item
  20:     0x561beaebc33e - <rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  21:     0x561beaeb9765 - <rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::LinkCollector>::resolve
  22:     0x561beaebf623 - <rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4dafd65c5212ebd7]::visit::DocVisitor>::visit_item
  23:     0x561beaecc88a - <rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4dafd65c5212ebd7]::visit::DocVisitor>::visit_inner_recur
  24:     0x561beaec2cf4 - <rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::LinkCollector as rustdoc[4dafd65c5212ebd7]::visit::DocVisitor>::visit_item
  25:     0x561beaeb7f5c - rustdoc[4dafd65c5212ebd7]::passes::collect_intra_doc_links::collect_intra_doc_links
  26:     0x561beaed2602 - <rustc_session[93cf466beccfe173]::session::Session>::time::<(rustdoc[4dafd65c5212ebd7]::clean::types::Crate, rustdoc[4dafd65c5212ebd7]::config::RenderOptions, rustdoc[4dafd65c5212ebd7]::formats::cache::Cache), rustdoc[4dafd65c5212ebd7]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#0}>
  27:     0x561beaf61496 - <rustc_interface[3aa5dcd3b29cadd6]::passes::QueryContext>::enter::<rustdoc[4dafd65c5212ebd7]::main_options::{closure#0}::{closure#0}::{closure#1}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>
  28:     0x561beae5c229 - <rustc_interface[3aa5dcd3b29cadd6]::interface::Compiler>::enter::<rustdoc[4dafd65c5212ebd7]::main_options::{closure#0}::{closure#0}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>
  29:     0x561beaccb936 - rustc_span[783d01233175f916]::with_source_map::<core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>, rustc_interface[3aa5dcd3b29cadd6]::interface::create_compiler_and_run<core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>, rustdoc[4dafd65c5212ebd7]::main_options::{closure#0}>::{closure#1}>
  30:     0x561beae5e9d4 - rustc_interface[3aa5dcd3b29cadd6]::interface::create_compiler_and_run::<core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>, rustdoc[4dafd65c5212ebd7]::main_options::{closure#0}>
  31:     0x561beace6e9b - rustdoc[4dafd65c5212ebd7]::main_options
  32:     0x561bead0eadb - <scoped_tls[be19827943045dee]::ScopedKey<rustc_span[783d01233175f916]::SessionGlobals>>::set::<rustdoc[4dafd65c5212ebd7]::main_args::{closure#0}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>
  33:     0x561beae842af - std[be2b2098f2565a09]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3aa5dcd3b29cadd6]::util::run_in_thread_pool_with_globals<rustdoc[4dafd65c5212ebd7]::main_args::{closure#0}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>::{closure#0}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>
  34:     0x561beaf1ee69 - <<std[be2b2098f2565a09]::thread::Builder>::spawn_unchecked_<rustc_interface[3aa5dcd3b29cadd6]::util::run_in_thread_pool_with_globals<rustdoc[4dafd65c5212ebd7]::main_args::{closure#0}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>::{closure#0}, core[93896c7deb4583e1]::result::Result<(), rustc_errors[46e0f1031c6d896b]::ErrorGuaranteed>>::{closure#1} as core[93896c7deb4583e1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7f93e8aab553 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5e2ec464c6633a37
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/alloc/src/boxed.rs:1861:9
  36:     0x7f93e8aab553 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0630748fae134b06
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/alloc/src/boxed.rs:1861:9
  37:     0x7f93e8aab553 - std::sys::unix::thread::Thread::new::thread_start::h9400fecba0bc7090
                               at /rustc/306ba8357fb36212b7d30efb9eb9e41659ac1445/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7f93e88835c2 - start_thread
  39:     0x7f93e8908584 - __clone
  40:                0x0 - <unknown>
```

</p>
</details>

**Comment by petrochenkov** [comment]
If this is not already fixed on nightly, then it should be fixed by https://github.com/rust-lang/rust/pull/95706 soon.

**Comment by usamoi** [comment]
It was fixed by https://github.com/rust-lang/rust/pull/95706.
