### ISSUE TITLE
ICE when running `rustdoc` in crossbeam's CI

### ISSUE THREAD

**Issue by sb64** [rust-lang/rust#95774]
I hit this error in a CI run for a pull request I submitted, crossbeam-rs/crossbeam#811. The command being run was:
```
rustdoc --edition=2018 --crate-type lib --crate-name crossbeam src/lib.rs -o /home/runner/work/crossbeam/crossbeam/target/doc --cfg 'feature="alloc"' --cfg 'feature="crossbeam-channel"' --cfg 'feature="crossbeam-deque"' --cfg 'feature="crossbeam-epoch"' --cfg 'feature="crossbeam-queue"' --cfg 'feature="default"' --cfg 'feature="nightly"' --cfg 'feature="std"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=362f5a2b1a095e8c -L dependency=/home/runner/work/crossbeam/crossbeam/target/debug/deps --extern cfg_if=/home/runner/work/crossbeam/crossbeam/target/debug/deps/libcfg_if-88879d2dc0fa106c.rmeta --extern crossbeam_channel=/home/runner/work/crossbeam/crossbeam/target/debug/deps/libcrossbeam_channel-6fd5ca6a19ad7131.rmeta --extern crossbeam_deque=/home/runner/work/crossbeam/crossbeam/target/debug/deps/libcrossbeam_deque-3affaf6fdb3fcdab.rmeta --extern crossbeam_epoch=/home/runner/work/crossbeam/crossbeam/target/debug/deps/libcrossbeam_epoch-66e2db4f4762ec58.rmeta --extern crossbeam_queue=/home/runner/work/crossbeam/crossbeam/target/debug/deps/libcrossbeam_queue-726adb03bed4b2ad.rmeta --extern crossbeam_utils=/home/runner/work/crossbeam/crossbeam/target/debug/deps/libcrossbeam_utils-09043cc9cc5c3cdd.rmeta -D warnings --crate-version 0.8.1
```
[Here is a link to the CI run](https://github.com/crossbeam-rs/crossbeam/runs/5863056022)

### Meta
I can't run `rustc --version --verbose` on the CI runner, but the error message did offer this for the Rust version:
```
rustc 1.62.0-nightly (8f36334ca 2022-04-06) running on x86_64-unknown-linux-gnu
```

### Error output

```
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:977:16
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33/library/core/src/option.rs:1[87](https://github.com/crossbeam-rs/crossbeam/runs/5863056022?check_suite_focus=true#step:4:87)4:5
   5: rustdoc::passes::collect_intra_doc_links::resolve_associated_trait_item
   6: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
   7: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
   8: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
   9: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
  10: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_item
  11: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  12: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#0}>
  13: <rustc_interface::passes::QueryContext>::enter::<rustdoc::main_options::{closure#0}::{closure#0}::{closure#1}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  14: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_options::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  15: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustdoc::main_options::{closure#0}>::{closure#1}>
  16: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustdoc::main_options::{closure#0}>
  17: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustdoc::main_args::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by sb64** [comment]
I saw #95768, which addresses the same issue, so I don't know that this issue is necessary. I'll leave it open for now, but it can probably just be closed.

**Comment by usamoi** [comment]
It was fixed in today's nightly.
