### ISSUE TITLE
ICE: rustc -Ztranslate-lang=de

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#95934]
`rustc -Ztranslate-lang=de`

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'failed to load fluent bundle: LocaleIsNotDir', compiler/rustc_session/src/session.rs:1223:6
stack backtrace:
   0:     0x7fe97849e00d - std::backtrace_rs::backtrace::libunwind::trace::h3c2df544ab40aecb
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe97849e00d - std::backtrace_rs::backtrace::trace_unsynchronized::h81641a922b348d2e
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe97849e00d - std::sys_common::backtrace::_print_fmt::h6e79c701b9625c79
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fe97849e00d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb239ffa0f3fe9bfb
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fe9784f7d2c - core::fmt::write::h120f031e21e527b2
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/fmt/mod.rs:1194:17
   5:     0x7fe97848f8d1 - std::io::Write::write_fmt::hcadaf7a47c778d95
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/io/mod.rs:1655:15
   6:     0x7fe9784a0f25 - std::sys_common::backtrace::_print::h602596cd4438c0b8
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fe9784a0f25 - std::sys_common::backtrace::print::hced3c2bbbca51ba0
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fe9784a0f25 - std::panicking::default_hook::{{closure}}::ha0a37e1dfc5c5508
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/panicking.rs:295:22
   9:     0x7fe9784a0b99 - std::panicking::default_hook::h946f0e7b1a23823c
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/panicking.rs:314:9
  10:     0x7fe978ccf581 - rustc_driver[b0521e0029519726]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fe9784a16c0 - std::panicking::rust_panic_with_hook::h8c806c2553f250af
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/panicking.rs:702:17
  12:     0x7fe9784a14f7 - std::panicking::begin_panic_handler::{{closure}}::h32797e073841ac81
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/panicking.rs:588:13
  13:     0x7fe97849e4c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h08bcf94bf02e8894
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fe9784a1229 - rust_begin_unwind
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/panicking.rs:584:5
  15:     0x7fe978465773 - core::panicking::panic_fmt::h1e0f3eb75d9d073b
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/panicking.rs:142:14
  16:     0x7fe978465863 - core::result::unwrap_failed::h7e5a97bdf5ec6267
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/result.rs:1785:5
  17:     0x7fe97b58b134 - rustc_session[2dc4a7be5d9ff3ca]::session::build_session
  18:     0x7fe97ad4df46 - rustc_interface[94022c71fe7b49c0]::util::create_session
  19:     0x7fe978caab3c - <scoped_tls[af63e75d94209d10]::ScopedKey<rustc_span[969e4db7dd7c3d16]::SessionGlobals>>::set::<rustc_interface[94022c71fe7b49c0]::interface::run_compiler<(), rustc_driver[b0521e0029519726]::run_compiler::{closure#0}>::{closure#0}, ()>
  20:     0x7fe978cb80a6 - std[2766153f4a5dd1e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[94022c71fe7b49c0]::util::run_in_thread_pool_with_globals<rustc_interface[94022c71fe7b49c0]::interface::run_compiler<(), rustc_driver[b0521e0029519726]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#0}, ()>
  21:     0x7fe978cb316a - std[2766153f4a5dd1e]::panicking::try::<(), core[2aea4973b4bcdb83]::panic::unwind_safe::AssertUnwindSafe<<std[2766153f4a5dd1e]::thread::Builder>::spawn_unchecked_<rustc_interface[94022c71fe7b49c0]::util::run_in_thread_pool_with_globals<rustc_interface[94022c71fe7b49c0]::interface::run_compiler<(), rustc_driver[b0521e0029519726]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}::{closure#0}>>
  22:     0x7fe978cb8dbf - <<std[2766153f4a5dd1e]::thread::Builder>::spawn_unchecked_<rustc_interface[94022c71fe7b49c0]::util::run_in_thread_pool_with_globals<rustc_interface[94022c71fe7b49c0]::interface::run_compiler<(), rustc_driver[b0521e0029519726]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#0}, ()>::{closure#1} as core[2aea4973b4bcdb83]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  23:     0x7fe9784ab823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf447f1fcf8575211
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/alloc/src/boxed.rs:1858:9
  24:     0x7fe9784ab823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3aaba544bef0d46e
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/alloc/src/boxed.rs:1858:9
  25:     0x7fe9784ab823 - std::sys::unix::thread::Thread::new::thread_start::hae099952fe770af0
                               at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/sys/unix/thread.rs:108:17
  26:     0x7fe9782835c2 - start_thread
  27:     0x7fe978308584 - __clone
  28:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (1f7fb6413 2022-04-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z translate-lang=de

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by davidtwco** [comment]
Closing, fixed by #95716.

```shell-session
$ rustc +stage1 -Ztranslate-lang=de
error: failed to load fluent bundle: missing locale directory
```
