### ISSUE TITLE
ICE: "not implemented: implement when/if needed" compiler/rustc_mir_dataflow/src/framework/fmt.rs:141:

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#96172]
### Code

```Rust
#![feature(rustc_attrs)]
#[rustc_mir(borrowck_graphviz_postflow="hello.dot")]
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (ec77f2524 2022-04-17)
binary: rustc
commit-hash: ec77f252434a532fdb5699ae4f21a3072d211edd
commit-date: 2022-04-17
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.0
```

### Error output

```

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'not implemented: implement when/if needed', /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/compiler/rustc_mir_dataflow/src/framework/fmt.rs:141:9
stack backtrace:
   0:     0x7f2716c9d83d - std::backtrace_rs::backtrace::libunwind::trace::hdc1f21fb71c845ee
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f2716c9d83d - std::backtrace_rs::backtrace::trace_unsynchronized::h825695a1eac7e4dc
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2716c9d83d - std::sys_common::backtrace::_print_fmt::h201cc1fed0ce4598
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f2716c9d83d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4c86a2fdb08a33f9
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f2716cf8f1c - core::fmt::write::hee99b3f0c63f5ca9
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/core/src/fmt/mod.rs:1194:17
   5:     0x7f2716c8f031 - std::io::Write::write_fmt::hfa56cdeea03f4b89
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/io/mod.rs:1655:15
   6:     0x7f2716ca0555 - std::sys_common::backtrace::_print::hbd75018aef718598
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f2716ca0555 - std::sys_common::backtrace::print::hc594da4af1e8ead7
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f2716ca0555 - std::panicking::default_hook::{{closure}}::h0602100d469ef01e
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/panicking.rs:295:22
   9:     0x7f2716ca01c9 - std::panicking::default_hook::hc7ef6a8909090411
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/panicking.rs:314:9
  10:     0x7f27174d0521 - rustc_driver[8e3c698622bece67]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f2716ca0d26 - std::panicking::rust_panic_with_hook::hb9245fe7222caa6e
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/panicking.rs:702:17
  12:     0x7f2716ca0b27 - std::panicking::begin_panic_handler::{{closure}}::he83bcf9a0c850a85
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/panicking.rs:588:13
  13:     0x7f2716c9dcf4 - std::sys_common::backtrace::__rust_end_short_backtrace::h465a02e71d825eac
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f2716ca0859 - rust_begin_unwind
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/panicking.rs:584:5
  15:     0x7f2716c65c33 - core::panicking::panic_fmt::h23e69d1ae62ab6cd
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/core/src/panicking.rs:142:14
  16:     0x7f2717a31b80 - <&rustc_index[4a82e4fc80d3ad82]::bit_set::ChunkedBitSet<rustc_mir_dataflow[e64b17d8f1c2c6ae]::move_paths::InitIndex> as rustc_mir_dataflow[e64b17d8f1c2c6ae]::framework::fmt::DebugWithContext<rustc_mir_dataflow[e64b17d8f1c2c6ae]::impls::EverInitializedPlaces>>::fmt_with
  17:     0x7f2716cf8f1c - core::fmt::write::hee99b3f0c63f5ca9
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/core/src/fmt/mod.rs:1194:17
  18:     0x7f2716cec159 - core::fmt::Write::write_fmt::hd39326de7a6c3a74
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/core/src/fmt/mod.rs:186:9
  19:     0x7f2716cec159 - alloc::fmt::format::h465fae35ca392ce3
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/alloc/src/fmt.rs:597:5
  20:     0x7f2717b04616 - <rustc_mir_dataflow[e64b17d8f1c2c6ae]::framework::graphviz::BlockFormatter<rustc_mir_dataflow[e64b17d8f1c2c6ae]::impls::MaybeInitializedPlaces>>::write_row_with_full_state::<alloc[8d468ea801fd4f9]::vec::Vec<u8>>
  21:     0x7f2717b159ac - <rustc_mir_dataflow[e64b17d8f1c2c6ae]::framework::graphviz::Formatter<rustc_mir_dataflow[e64b17d8f1c2c6ae]::impls::MaybeInitializedPlaces> as rustc_graphviz[178dad2cc5300050]::Labeller>::node_label
  22:     0x7f2717ab9a6d - rustc_graphviz[178dad2cc5300050]::render_opts::<rustc_middle[c02e249562e6ab88]::mir::BasicBlock, rustc_mir_dataflow[e64b17d8f1c2c6ae]::framework::graphviz::CfgEdge, rustc_mir_dataflow[e64b17d8f1c2c6ae]::framework::graphviz::Formatter<rustc_mir_dataflow[e64b17d8f1c2c6ae]::impls::MaybeInitializedPlaces>, alloc[8d468ea801fd4f9]::vec::Vec<u8>>
  23:     0x7f2718d9447e - <rustc_mir_dataflow[e64b17d8f1c2c6ae]::framework::engine::Engine<rustc_mir_dataflow[e64b17d8f1c2c6ae]::impls::MaybeInitializedPlaces>>::iterate_to_fixpoint
  24:     0x7f2718d494c2 - rustc_borrowck[99159bdf76fa6f8e]::do_mir_borrowck
  25:     0x7f2718d42199 - rustc_borrowck[99159bdf76fa6f8e]::mir_borrowck
  26:     0x7f2718d3eea0 - <rustc_borrowck[99159bdf76fa6f8e]::provide::{closure#0} as core[f08f6a517a2b1407]::ops::function::FnOnce<(rustc_middle[c02e249562e6ab88]::ty::context::TyCtxt, rustc_span[e15e523c5f5ffbde]::def_id::LocalDefId)>>::call_once
  27:     0x7f2718ef7f10 - rustc_query_system[b98794630d07627]::query::plumbing::try_execute_query::<rustc_query_impl[9f8ea830b7665e9c]::plumbing::QueryCtxt, rustc_query_system[b98794630d07627]::query::caches::DefaultCache<rustc_span[e15e523c5f5ffbde]::def_id::LocalDefId, &rustc_middle[c02e249562e6ab88]::mir::query::BorrowCheckResult>>
  28:     0x7f2718ffba0a - <rustc_query_impl[9f8ea830b7665e9c]::Queries as rustc_middle[c02e249562e6ab88]::ty::query::QueryEngine>::mir_borrowck
  29:     0x7f271879eb7f - <rustc_middle[c02e249562e6ab88]::hir::map::Map>::par_body_owners::<rustc_interface[b4fe925d1e8786a0]::passes::analysis::{closure#2}::{closure#0}>
  30:     0x7f27195440e8 - <rustc_session[8619e56cac793b58]::session::Session>::time::<(), rustc_interface[b4fe925d1e8786a0]::passes::analysis::{closure#2}>
  31:     0x7f271953d565 - rustc_interface[b4fe925d1e8786a0]::passes::analysis
  32:     0x7f27199fabe4 - rustc_query_system[b98794630d07627]::query::plumbing::try_execute_query::<rustc_query_impl[9f8ea830b7665e9c]::plumbing::QueryCtxt, rustc_query_system[b98794630d07627]::query::caches::DefaultCache<(), core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>>
  33:     0x7f2719a3c07e - rustc_query_system[b98794630d07627]::query::plumbing::get_query::<rustc_query_impl[9f8ea830b7665e9c]::queries::analysis, rustc_query_impl[9f8ea830b7665e9c]::plumbing::QueryCtxt>
  34:     0x7f271951a807 - <rustc_interface[b4fe925d1e8786a0]::passes::QueryContext>::enter::<rustc_driver[8e3c698622bece67]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>
  35:     0x7f2719505d98 - <rustc_interface[b4fe925d1e8786a0]::interface::Compiler>::enter::<rustc_driver[8e3c698622bece67]::run_compiler::{closure#1}::{closure#2}, core[f08f6a517a2b1407]::result::Result<core[f08f6a517a2b1407]::option::Option<rustc_interface[b4fe925d1e8786a0]::queries::Linker>, rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>
  36:     0x7f271952eeef - rustc_span[e15e523c5f5ffbde]::with_source_map::<core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>, rustc_interface[b4fe925d1e8786a0]::interface::create_compiler_and_run<core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>, rustc_driver[8e3c698622bece67]::run_compiler::{closure#1}>::{closure#1}>
  37:     0x7f27195069b7 - <scoped_tls[ed206aee8c9203a6]::ScopedKey<rustc_span[e15e523c5f5ffbde]::SessionGlobals>>::set::<rustc_interface[b4fe925d1e8786a0]::interface::run_compiler<core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>, rustc_driver[8e3c698622bece67]::run_compiler::{closure#1}>::{closure#0}, core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>
  38:     0x7f271951bf0f - std[7eb92d5d5059ff02]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b4fe925d1e8786a0]::util::run_in_thread_pool_with_globals<rustc_interface[b4fe925d1e8786a0]::interface::run_compiler<core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>, rustc_driver[8e3c698622bece67]::run_compiler::{closure#1}>::{closure#0}, core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>::{closure#0}, core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>
  39:     0x7f271951c049 - <<std[7eb92d5d5059ff02]::thread::Builder>::spawn_unchecked_<rustc_interface[b4fe925d1e8786a0]::util::run_in_thread_pool_with_globals<rustc_interface[b4fe925d1e8786a0]::interface::run_compiler<core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>, rustc_driver[8e3c698622bece67]::run_compiler::{closure#1}>::{closure#0}, core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>::{closure#0}, core[f08f6a517a2b1407]::result::Result<(), rustc_errors[dbef8fecc23abfce]::ErrorGuaranteed>>::{closure#1} as core[f08f6a517a2b1407]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7f2716caabd3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd2056160a42acd52
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/alloc/src/boxed.rs:1866:9
  41:     0x7f2716caabd3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h99c5b980edefbf69
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/alloc/src/boxed.rs:1866:9
  42:     0x7f2716caabd3 - std::sys::unix::thread::Thread::new::thread_start::h42961cfa146716e3
                               at /rustc/ec77f252434a532fdb5699ae4f21a3072d211edd/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7f2716a835c2 - start_thread
  44:     0x7f2716b08584 - __clone
  45:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (ec77f2524 2022-04-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_borrowck] borrow-checking `main`
#1 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by Alexendoo** [comment]
No longer ICEs since #96578

**Comment by JohnTitor** [comment]
Looking at the ICE message, it doesn't make much sense to add a regression test as it's just an unimplemented panic. Going to close without a test.
