### ISSUE TITLE
Un-emitted error (in very proc-macro-heavy situation)

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#96364]
### Code

I'm afraid I don't have time now to minimise this.  Steps to reproduce:

 1. `git clone https://salsa.debian.org/iwj/otter`
 2. `cd otter`
 3. `git checkout origin/wip.ice.unemitted-syntax-error` # b87daaac3f524bccb338d7da1491f439a983c3c0
 4. `cargo build -p otter-api-tests`

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (1bfe40d11 2022-03-18)
binary: rustc
commit-hash: 1bfe40d11c3630254504fb73eeccfca28d50df52
commit-date: 2022-03-18
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### Error output

```
   Compiling otter-api-tests v1.0.0 (/volatile/rustcargo/Otter/Compile-test/otter/apitest)
error: internal compiler error: the following error was constructed but not emitted

error: expected one of `>` or `as`, found `>>`
   --> apitest/atmain.rs:386:67
    |
386 |                        -> impl Iterator<Item=<(PT, PieceInfo<JsV>)>> {
    |                                                                   ^^ expected one of `>` or `as`

thread 'rustc' panicked at 'explicit panic', compiler/rustc_errors/src/diagnostic_builder.rs:508:21
stack backtrace:
[elided -iwj]
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (1bfe40d11 2022-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `otter-api-tests` due to previous error
```

<details>

<summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling otter-api-tests v1.0.0 (/volatile/rustcargo/Otter/Compile-test/otter/apitest)
error: internal compiler error: the following error was constructed but not emitted

error: expected one of `>` or `as`, found `>>`
   --> apitest/atmain.rs:386:67
    |
386 |                        -> impl Iterator<Item=<(PT, PieceInfo<JsV>)>> {
    |                                                                   ^^ expected one of `>` or `as`

thread 'rustc' panicked at 'explicit panic', compiler/rustc_errors/src/diagnostic_builder.rs:508:21
stack backtrace:
   0:     0x7fc5c5b7d9dd - std::backtrace_rs::backtrace::libunwind::trace::ha0dcc0dbac37b490
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fc5c5b7d9dd - std::backtrace_rs::backtrace::trace_unsynchronized::hde1ae3efbda56431
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc5c5b7d9dd - std::sys_common::backtrace::_print_fmt::h33a851e03bd0b6e4
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fc5c5b7d9dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff9ff85f8279581f
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fc5c5bd752c - core::fmt::write::h2e0e90f8a2493173
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fc5c5b6ef61 - std::io::Write::write_fmt::h034fa14aa669df7f
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/io/mod.rs:1655:15
   6:     0x7fc5c5b80ac5 - std::sys_common::backtrace::_print::h84318396c29faefb
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fc5c5b80ac5 - std::sys_common::backtrace::print::h9768394db98e45ff
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fc5c5b80ac5 - std::panicking::default_hook::{{closure}}::hce98dd26e8c80f17
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/panicking.rs:295:22
   9:     0x7fc5c5b80779 - std::panicking::default_hook::hf647f5f3bad56e08
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/panicking.rs:314:9
  10:     0x7fc5c631c271 - rustc_driver[2d9984ec3b69f6c8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fc5c5b81210 - std::panicking::rust_panic_with_hook::he4d6049ea2de960b
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/panicking.rs:702:17
  12:     0x7fc5c5b81009 - std::panicking::begin_panic_handler::{{closure}}::hefe48cd5b70c6c39
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/panicking.rs:586:13
  13:     0x7fc5c5b7de94 - std::sys_common::backtrace::__rust_end_short_backtrace::h925c3fef9b95b3ea
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fc5c5b80d79 - rust_begin_unwind
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/panicking.rs:584:5
  15:     0x7fc5c5b44c93 - core::panicking::panic_fmt::h4129b45703e57723
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/core/src/panicking.rs:143:14
  16:     0x7fc5c5b44b5d - core::panicking::panic::h6d419beb146ec935
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/core/src/panicking.rs:48:5
  17:     0x7fc5c812d3ed - <rustc_errors[9a0bab4d6ac1940a]::diagnostic_builder::DiagnosticBuilderInner as core[e36ddb4c72619525]::ops::drop::Drop>::drop
  18:     0x7fc5c702bbed - core[e36ddb4c72619525]::ptr::drop_in_place::<rustc_errors[9a0bab4d6ac1940a]::diagnostic_builder::DiagnosticBuilderInner>
  19:     0x7fc5c7e51e63 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_generic_arg
  20:     0x7fc5c7e50db7 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_angle_args
  21:     0x7fc5c7e49559 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_path_inner
  22:     0x7fc5c88b35b6 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_generic_bounds_common
  23:     0x7fc5c7e5e1d9 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_ty_common
  24:     0x7fc5c7e3324d - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_fn_decl
  25:     0x7fc5c7e2e597 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_fn
  26:     0x7fc5c7e21ac3 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_item_common
  27:     0x7fc5c7e2a63a - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_item_impl
  28:     0x7fc5c7e22e9d - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_item_common
  29:     0x7fc5c7e209b4 - <rustc_parse[4f10fec2c3c42d5e]::parser::Parser>::parse_mod
  30:     0x7fc5c88b8468 - rustc_parse[4f10fec2c3c42d5e]::parse_crate_from_file
  31:     0x7fc5c81c8719 - <rustc_session[44a8dacdbda4c85a]::session::Session>::time::<core[e36ddb4c72619525]::result::Result<rustc_ast[f6a24c142fcd2ec9]::ast::Crate, rustc_errors[9a0bab4d6ac1940a]::diagnostic_builder::DiagnosticBuilder<rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>, rustc_interface[261c0c4ee18c4905]::passes::parse::{closure#0}>
  32:     0x7fc5c81acf2a - rustc_interface[261c0c4ee18c4905]::passes::parse
  33:     0x7fc5c81a4996 - <rustc_interface[261c0c4ee18c4905]::queries::Queries>::parse
  34:     0x7fc5c816a6b8 - <rustc_interface[261c0c4ee18c4905]::interface::Compiler>::enter::<rustc_driver[2d9984ec3b69f6c8]::run_compiler::{closure#1}::{closure#2}, core[e36ddb4c72619525]::result::Result<core[e36ddb4c72619525]::option::Option<rustc_interface[261c0c4ee18c4905]::queries::Linker>, rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>
  35:     0x7fc5c817d91f - rustc_span[187db9b1cfcb079d]::with_source_map::<core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>, rustc_interface[261c0c4ee18c4905]::interface::create_compiler_and_run<core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>, rustc_driver[2d9984ec3b69f6c8]::run_compiler::{closure#1}>::{closure#1}>
  36:     0x7fc5c816bec4 - rustc_interface[261c0c4ee18c4905]::interface::create_compiler_and_run::<core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>, rustc_driver[2d9984ec3b69f6c8]::run_compiler::{closure#1}>
  37:     0x7fc5c8168262 - <scoped_tls[8a9a8d9ce9b03694]::ScopedKey<rustc_span[187db9b1cfcb079d]::SessionGlobals>>::set::<rustc_interface[261c0c4ee18c4905]::interface::run_compiler<core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>, rustc_driver[2d9984ec3b69f6c8]::run_compiler::{closure#1}>::{closure#0}, core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>
  38:     0x7fc5c81666ff - std[1999d1a60a4290e6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[261c0c4ee18c4905]::util::run_in_thread_pool_with_globals<rustc_interface[261c0c4ee18c4905]::interface::run_compiler<core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>, rustc_driver[2d9984ec3b69f6c8]::run_compiler::{closure#1}>::{closure#0}, core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>::{closure#0}, core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>
  39:     0x7fc5c817e8a2 - <<std[1999d1a60a4290e6]::thread::Builder>::spawn_unchecked_<rustc_interface[261c0c4ee18c4905]::util::run_in_thread_pool_with_globals<rustc_interface[261c0c4ee18c4905]::interface::run_compiler<core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>, rustc_driver[2d9984ec3b69f6c8]::run_compiler::{closure#1}>::{closure#0}, core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>::{closure#0}, core[e36ddb4c72619525]::result::Result<(), rustc_errors[9a0bab4d6ac1940a]::ErrorGuaranteed>>::{closure#1} as core[e36ddb4c72619525]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7fc5c5b8b3a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcb71f654c0b0fdfd
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/alloc/src/boxed.rs:1853:9
  41:     0x7fc5c5b8b3a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h064662d2acfead96
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/alloc/src/boxed.rs:1853:9
  42:     0x7fc5c5b8b3a3 - std::sys::unix::thread::Thread::new::thread_start::hebe5500058936555
                               at /rustc/1bfe40d11c3630254504fb73eeccfca28d50df52/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7fc5c5a77fa3 - start_thread
                               at /build/glibc-fWwxX8/glibc-2.28/nptl/pthread_create.c:486:8
  44:     0x7fc5c599ceff - clone
                               at /build/glibc-fWwxX8/glibc-2.28/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  45:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (1bfe40d11 2022-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `otter-api-tests` due to previous error
```

</p>

Stable (1.60.0) does not panic and produces a correct-looking error message:
```
   Compiling otter-api-tests v1.0.0 (/volatile/rustcargo/Otter/Compile-test/otter/apitest)
error: expected one of `>` or `as`, found `>>`
   --> apitest/atmain.rs:386:67
    |
384 | impl<PI> IndexVec<PI, PieceInfo<JsV>> {
    |                                       - while parsing this item list starting here
385 |   fn filter_by_desc_glob(&self, desc_glob: &str)
386 |                        -> impl Iterator<Item=<(PT, PieceInfo<JsV>)>> {
    |                                                                   ^^ expected one of `>` or `as`
...
399 | }
    | - the item list ends here

error: expected `::`
   --> apitest/atmain.rs:386:67
    |
386 |                        -> impl Iterator<Item=<(PT, PieceInfo<JsV>)>> {
    |                                                                   ^^

error[E0599]: no method named `filter_by_desc_glob` found for struct `otter_api_tests::IndexVec<pi::PIA, PieceInfo<otter_api_tests::tera::Value>>` in the current scope
   --> apitest/atmain.rs:543:10
    |
543 |         .filter_by_desc_glob("a library load area marker")
    |          ^^^^^^^^^^^^^^^^^^^ method not found in `otter_api_tests::IndexVec<pi::PIA, PieceInfo<otter_api_tests::tera::Value>>`

error[E0609]: no field `id` on type `&_`
   --> apitest/atmain.rs:550:42
    |
550 |         session.api_piece(GH::With, &llm.id, pos)?;
    |                                          ^^

error[E0599]: no method named `find_piece_by_desc_glob` found for struct `otter_api_tests::IndexVec<pi::PIA, PieceInfo<otter_api_tests::tera::Value>>` in the current scope
  --> apitest/at-bundles.rs:29:29
   |
29 |         let _: PIA = pieces.find_piece_by_desc_glob(expect);
   |                             ^^^^^^^^^^^^^^^^^^^^^^^ method not found in `otter_api_tests::IndexVec<pi::PIA, PieceInfo<otter_api_tests::tera::Value>>`

error[E0599]: no method named `find_by_desc_glob` found for struct `otter_api_tests::IndexVec<pi::PIA, PieceInfo<otter_api_tests::tera::Value>>` in the current scope
  --> apitest/at-otter.rs:40:25
   |
40 |     let hand = a_pieces.find_by_desc_glob(otter::hand::UNCLAIMED_HAND_DESC);
   |                         ^^^^^^^^^^^^^^^^^ method not found in `otter_api_tests::IndexVec<pi::PIA, PieceInfo<otter_api_tests::tera::Value>>`

error[E0599]: no method named `filter_by_desc_glob` found for reference `&otter_api_tests::IndexSlice<PI, [PieceInfo<otter_api_tests::tera::Value>]>` in the current scope
  --> apitest/at-otter.rs:51:10
   |
51 |         .filter_by_desc_glob("* pawn")
   |          ^^^^^^^^^^^^^^^^^^^ method not found in `&otter_api_tests::IndexSlice<PI, [PieceInfo<otter_api_tests::tera::Value>]>`

Some errors have detailed explanations: E0599, E0609.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `otter-api-tests` due to 7 previous errors
```

</details>

**Comment by apiraino** [comment]
API documentation [at this link](https://github.com/abilita-org/apprendo-webapp/wiki/API_collection#post-collectionsshare)

**Comment by mcvicuna** [comment]
using:
```rustc 1.61.0-nightly (1bfe40d11 2022-03-18)
binary: rustc
commit-hash: 1bfe40d11c3630254504fb73eeccfca28d50df52
commit-date: 2022-03-18
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```
Here are 3 different single lines that cause the ICE:
```
static n: T<X=<(u8)>>;
```
```
fn test<T>() -> T<X=<(u8)>> {}
```
```
fn test(n: T<X=<(u8)>> ) {}
```
```

**Comment by oli-obk** [comment]
Thanks! Those minimized versions are great. I guess someone already fixed this ICE, and I'm assuming there are now tests for it, but I don't know. I guess we could search in the test suite for anything reporting the emitted error that looks like a repro of this issue and then close this issue
