### ISSUE TITLE
Incremental ICE in `exported_symbols` query

### ISSUE THREAD

**Issue by DropDemBits** [rust-lang/rust#96449]
### Reproduction steps

On repo <https://github.com/DropDemBits/turse-rs>:

```
git checkout 8f364cf
cargo t -p toc_analysis --no-run
git checkout 23b7440
cargo t -p toc_analysis -j1 --no-run
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (055bf4ccd 2022-04-25)
binary: rustc
commit-hash: 055bf4ccd521c2c2185166c86951be7be145727c
commit-date: 2022-04-25
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

Also hit on `rustc 1.61.0-beta.4 (69a6d12e9 2022-04-25)` and `rustc 1.60.0 (7737e0b5c 2022-04-04)`

### Error output

```
thread 'rustc' panicked at 'Found unstable fingerprints for mir_built(e82671bce93de738-864ce90ea73b0785): Steal { value: RwLock(RefCell { value: Some(<truncated>) }) }', compiler/rustc_query_system/src/query/plumbing.rs:626:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

Truncated to fit under character limit, see [rustc_backtrace.txt](https://github.com/rust-lang/rust/files/8566213/rustc_backtrace.txt) for full output.

```
   Compiling toc_analysis v0.1.0 (/home/usar/Projects/turse-rs/compiler/toc_analysis)
error: internal compiler error: encountered incremental compilation error with mir_built(e82670bce93de738-864ce90ea73b0785)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p toc_analysis` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for mir_built(e82671bce93de738-864ce90ea73b0785): Steal { value: RwLock(RefCell { value: Some(<truncated>) }) }', compiler/rustc_query_system/src/query/plumbing.rs:626:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/055bf4ccd521c2c2185166c86951be7be145727c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/055bf4ccd521c2c2185166c86951be7be145727c/library/core/src/panicking.rs:142:14
   2: rustc_query_system::query::plumbing::incremental_verify_ich_cold
   3: rustc_query_system::query::plumbing::incremental_verify_ich::<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
   4: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
   5: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>>
   6: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
   7: rustc_mir_transform::mir_const
   8: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>::{closure#1}, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
   9: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>>
  11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_const
  12: rustc_mir_transform::mir_promoted
  13: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, (&rustc_data_structures::steal::Steal<rustc_middle::mir::Body>, &rustc_data_structures::steal::Steal<rustc_index::vec::IndexVec<rustc_middle::mir::Promoted, rustc_middle::mir::Body>>)>::{closure#1}, (&rustc_data_structures::steal::Steal<rustc_middle::mir::Body>, &rustc_data_structures::steal::Steal<rustc_index::vec::IndexVec<rustc_middle::mir::Promoted, rustc_middle::mir::Body>>)>
  14: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, (&rustc_data_structures::steal::Steal<rustc_middle::mir::Body>, &rustc_data_structures::steal::Steal<rustc_index::vec::IndexVec<rustc_middle::mir::Promoted, rustc_middle::mir::Body>>)>
  15: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, (&rustc_data_structures::steal::Steal<rustc_middle::mir::Body>, &rustc_data_structures::steal::Steal<rustc_index::vec::IndexVec<rustc_middle::mir::Promoted, rustc_middle::mir::Body>>)>>
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_promoted
  17: rustc_borrowck::mir_borrowck
  18: <rustc_borrowck::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
  19: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>::{closure#1}, &rustc_middle::mir::query::BorrowCheckResult>
  20: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>
  21: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::mir::query::BorrowCheckResult>>
  22: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  23: <rustc_middle::ty::context::TyCtxt>::mir_borrowck_opt_const_arg
  24: rustc_mir_transform::mir_drops_elaborated_and_const_checked
  25: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>::{closure#1}, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  26: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>
  27: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_middle::ty::WithOptConstParam<rustc_span::def_id::LocalDefId>, &rustc_data_structures::steal::Steal<rustc_middle::mir::Body>>>
  28: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_drops_elaborated_and_const_checked
  29: rustc_mir_transform::optimized_mir
  30: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, &rustc_middle::mir::Body>
  31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, &rustc_middle::mir::Body>>
  32: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::optimized_mir
  33: <rustc_middle::ty::context::TyCtxt>::instance_mir
  34: rustc_monomorphize::collector::collect_neighbours
  35: rustc_monomorphize::collector::collect_items_rec
  36: rustc_monomorphize::collector::collect_items_rec
  37: rustc_monomorphize::collector::collect_items_rec
  38: rustc_monomorphize::collector::collect_items_rec
  39: rustc_monomorphize::collector::collect_items_rec
  40: rustc_monomorphize::collector::collect_items_rec
  41: rustc_monomorphize::collector::collect_items_rec
  42: rustc_monomorphize::collector::collect_items_rec
  43: rustc_monomorphize::collector::collect_items_rec
  44: rustc_monomorphize::collector::collect_items_rec
  45: rustc_monomorphize::collector::collect_items_rec
  46: rustc_monomorphize::collector::collect_items_rec
  47: rustc_monomorphize::collector::collect_items_rec
  48: <rustc_session::session::Session>::time::<(), rustc_monomorphize::collector::collect_crate_mono_items::{closure#1}>
  49: rustc_monomorphize::collector::collect_crate_mono_items
  50: rustc_monomorphize::partitioning::collect_and_partition_mono_items
  51: <rustc_middle::dep_graph::dep_node::DepKind as rustc_query_system::dep_graph::DepKind>::with_deps::<<rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task_impl<rustc_middle::ty::context::TyCtxt, (), (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>::{closure#0}, (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>
  52: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>
  53: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), (&std::collections::hash::set::HashSet<rustc_span::def_id::DefId, core::hash::BuildHasherDefault<rustc_hash::FxHasher>>, &[rustc_middle::mir::mono::CodegenUnit])>>
  54: rustc_query_system::query::plumbing::force_query::<rustc_query_impl::queries::collect_and_partition_mono_items, rustc_query_impl::plumbing::QueryCtxt>
  55: rustc_query_impl::query_callbacks::collect_and_partition_mono_items::force_from_dep_node
  56: <rustc_middle::ty::context::TyCtxt as rustc_query_system::dep_graph::DepContext>::try_force_from_dep_node
  57: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl::plumbing::QueryCtxt>
  58: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl::plumbing::QueryCtxt>
  59: rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl::plumbing::QueryCtxt, rustc_span::def_id::CrateNum, &[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>
  60: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::CrateNum, &[(rustc_middle::middle::exported_symbols::ExportedSymbol, rustc_middle::middle::exported_symbols::SymbolExportInfo)]>>
  61: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::exported_symbols, rustc_query_impl::plumbing::QueryCtxt>
  62: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
  63: rustc_metadata::rmeta::encoder::encode_metadata_impl
  64: rustc_data_structures::sync::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, rustc_metadata::rmeta::encoder::EncodedMetadata, ()>
  65: rustc_metadata::rmeta::encoder::encode_metadata
  66: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  67: <rustc_interface::queries::Queries>::ongoing_codegen
  68: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  69: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  70: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  71: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (055bf4ccd 2022-04-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `ty::lower::type_def_ty`
#1 [mir_const] processing MIR for `ty::lower::type_def_ty`
#2 [mir_promoted] processing `ty::lower::type_def_ty`
#3 [mir_borrowck] borrow-checking `ty::lower::type_def_ty`
#4 [mir_drops_elaborated_and_const_checked] elaborating drops for `ty::lower::type_def_ty`
#5 [optimized_mir] optimizing MIR for `ty::lower::type_def_ty`
#6 [collect_and_partition_mono_items] collect_and_partition_mono_items
#7 [exported_symbols] exported_symbols
end of query stack
error: could not compile `toc_analysis` due to previous error
```

</p>
</details>

**Comment by DropDemBits** [comment]
Smaller diff:

```diff
diff --git a/compiler/toc_analysis/src/const_eval/errors.rs b/compiler/toc_analysis/src/const_eval/errors.rs
index f0fa6196..5915c56d 100644
--- a/compiler/toc_analysis/src/const_eval/errors.rs
+++ b/compiler/toc_analysis/src/const_eval/errors.rs
@@ -146,6 +146,8 @@ pub(super) enum ErrorKind {
     /// Produced a char(n) that is too big
     #[error("produced a character sequence that is too large")]
     CharNTooBig,
+    #[error("")]
+    NoFields(toc_hir::symbol::Symbol),
 
     // Unsupported messages
     /// Currently unsupported const eval value
diff --git a/compiler/toc_analysis/src/const_eval/value.rs b/compiler/toc_analysis/src/const_eval/value.rs
index 60443b09..17b2b4f6 100644
--- a/compiler/toc_analysis/src/const_eval/value.rs
+++ b/compiler/toc_analysis/src/const_eval/value.rs
@@ -49,6 +49,8 @@ impl PartialEq for ConstValue {
 
 impl Eq for ConstValue {}
 
+fn use_me() { if let crate::ty::TypeKind::Enum(..) = loop {} {} }
+
 impl ConstValue {
     /// Formats the constant value for display.
     pub fn display<DB: crate::ty::db::TypeDatabase + ?Sized>(&self, _db: &DB) -> String {                                                                                      
```

**Comment by DropDemBits** [comment]
Smaller reproduction
Compile as-is, then compile with lines 3 and 8 uncommented.
```rs
#[allow(dead_code)]
enum InnerB {
    // V0(u32), // < uncomment this on 2nd compile
}

#[allow(unused)]
fn use_me() {
    // if let Outer::B(..) = loop {} {} // < uncomment this on 2nd compile
}

pub fn execute() -> u32 {
    fn any_outer<'a>() -> &'a Outer {
        loop {}
    }

    match any_outer() {
        // replacing v0 with v1 gets the same result
        Outer::A(InnerA::V0(_)) => loop {},
        Outer::B(InnerA::V0(_)) => loop {},
        _ if false => loop {},
        _ => loop {},
    };
}

#[allow(dead_code)]
enum Outer {
    A(InnerA),
    B(InnerA),
    C(InnerB),
}

#[allow(dead_code)]
enum InnerA {
    V0(u32),
    V1(u32),
}
```
