### ISSUE TITLE
Random internal compiler error appeared

### ISSUE THREAD

**Issue by Slixe** [rust-lang/rust#96526]
I tried to compile after a big change (~300 lines in my project), and I had an internal compiler panic, I had it several times in a row.
I'm using tokio by the way.

### Version
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

### Error output

```
thread 'rustc' panicked at 'Failed to extract DefId: local_def_id_to_hir_id 7ffa00d53fa72e15-d51a329f06fc65fb', compiler/rustc_middle/src/dep_graph/dep_node.rs:270:17
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
    Building [=========================> ] 97/98: daemon(bin)                                                       
thread 'rustc' panicked at 'Failed to extract DefId: local_def_id_to_hir_id 7ffa00d53fa72e15-d51a329f06fc65fb', compiler/rustc_middle/src/dep_graph/dep_node.rs:270:17
stack backtrace:
   0:     0x7fafc8dcf86d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fafc8dcf86d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fafc8dcf86d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fafc8dcf86d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fafc8e2f4ec - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fafc8dbfa98 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7fafc8dd3847 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fafc8dd3847 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fafc8dd3847 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7fafc8dd3510 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7fafc955f2c1 - rustc_driver[6eeb127b85fe99ac]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fafb5159b33 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd412fb4afdf2f390
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1867:9
  12:     0x7fafb515592c - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hcbf162f2851eb084
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/proc_macro/src/bridge/client.rs:319:21
  13:     0x7fafb5171d40 - std::panicking::update_hook::{{closure}}::hcb104a5add820ebd
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:258:41
  14:     0x7fafc8dd4124 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  15:     0x7fafc8dd3dd7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  16:     0x7fafc8dcfd34 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  17:     0x7fafc8dd3ae9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  18:     0x7fafc8d9c863 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  19:     0x7fafca53bb01 - <rustc_query_system[cf3d2502706fe991]::dep_graph::dep_node::DepNode<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind> as rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepNodeExt>::extract_def_id::{closure#0}
  20:     0x7fafcb2bb669 - <rustc_query_system[cf3d2502706fe991]::dep_graph::dep_node::DepNode<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind> as rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  21:     0x7fafcb8e1e1c - rustc_query_impl[8218de0923c6cd45]::query_callbacks::local_def_id_to_hir_id::force_from_dep_node
  22:     0x7fafcbbf1841 - <rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt as rustc_query_system[cf3d2502706fe991]::dep_graph::DepContext>::try_force_from_dep_node
  23:     0x7fafcaeb9263 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  24:     0x7fafcaeb8a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  25:     0x7fafcaeb8a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  26:     0x7fafcaeb8a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  27:     0x7fafcaeb8a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  28:     0x7fafcaf031f5 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<core[2734bb1f7d9ec6a5]::option::Option<(core[2734bb1f7d9ec6a5]::result::Result<rustc_middle[c145adf1c4567bf]::traits::select::EvaluationResult, rustc_middle[c145adf1c4567bf]::traits::select::OverflowError>, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex)>, rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_middle[c145adf1c4567bf]::infer::canonical::Canonical<rustc_middle[c145adf1c4567bf]::ty::ParamEnvAnd<rustc_middle[c145adf1c4567bf]::ty::Predicate>>, core[2734bb1f7d9ec6a5]::result::Result<rustc_middle[c145adf1c4567bf]::traits::select::EvaluationResult, rustc_middle[c145adf1c4567bf]::traits::select::OverflowError>>::{closure#2}>
  29:     0x7fafcae4ae95 - rustc_query_system[cf3d2502706fe991]::query::plumbing::get_query::<rustc_query_impl[8218de0923c6cd45]::queries::evaluate_obligation, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  30:     0x7fafcae7ec94 - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::evaluate_obligation
  31:     0x7fafcb1636cd - <rustc_trait_selection[1d7483382b445f9]::traits::fulfill::FulfillProcessor>::progress_changed_obligations
  32:     0x7fafcb17fd86 - <rustc_data_structures[762b64c8eff0c924]::obligation_forest::ObligationForest<rustc_trait_selection[1d7483382b445f9]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[1d7483382b445f9]::traits::fulfill::FulfillProcessor, rustc_data_structures[762b64c8eff0c924]::obligation_forest::Outcome<rustc_trait_selection[1d7483382b445f9]::traits::fulfill::PendingPredicateObligation, rustc_infer[844122ed1ec4b57a]::traits::FulfillmentErrorCode>>
  33:     0x7fafcb16219b - <rustc_trait_selection[1d7483382b445f9]::traits::fulfill::FulfillmentContext as rustc_infer[844122ed1ec4b57a]::traits::engine::TraitEngine>::select_where_possible
  34:     0x7fafca9a0452 - <rustc_infer[844122ed1ec4b57a]::infer::InferCtxtBuilder>::enter::<&rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults, <rustc_typeck[1c3c3b5b5d734e80]::check::inherited::InheritedBuilder>::enter<rustc_typeck[1c3c3b5b5d734e80]::check::typeck_with_fallback<rustc_typeck[1c3c3b5b5d734e80]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>::{closure#0}>
  35:     0x7fafca97a5c3 - rustc_typeck[1c3c3b5b5d734e80]::check::typeck
  36:     0x7fafcb91eaed - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>
  37:     0x7fafcb990bae - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(&rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>::{closure#3}>
  38:     0x7fafcae17cc2 - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>>
  39:     0x7fafcae765fc - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::typeck
  40:     0x7fafcb2881c6 - <rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt>::typeck_opt_const_arg
  41:     0x7fafcab76870 - rustc_mir_build[be2c27fa83ba0a6f]::build::mir_built
  42:     0x7fafcb91389b - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_middle[c145adf1c4567bf]::ty::WithOptConstParam<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId>, &rustc_data_structures[762b64c8eff0c924]::steal::Steal<rustc_middle[c145adf1c4567bf]::mir::Body>>
  43:     0x7fafcb98fdf5 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(&rustc_data_structures[762b64c8eff0c924]::steal::Steal<rustc_middle[c145adf1c4567bf]::mir::Body>, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_middle[c145adf1c4567bf]::ty::WithOptConstParam<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId>, &rustc_data_structures[762b64c8eff0c924]::steal::Steal<rustc_middle[c145adf1c4567bf]::mir::Body>>::{closure#3}>
  44:     0x7fafcae096eb - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<rustc_middle[c145adf1c4567bf]::ty::WithOptConstParam<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId>, &rustc_data_structures[762b64c8eff0c924]::steal::Steal<rustc_middle[c145adf1c4567bf]::mir::Body>>>
  45:     0x7fafcae704a4 - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::mir_built
  46:     0x7fafca8ad4be - rustc_mir_transform[9e737481de61c19e]::check_unsafety::unsafety_check_result
  47:     0x7fafca8aa8b7 - <rustc_mir_transform[9e737481de61c19e]::check_unsafety::provide::{closure#0} as core[2734bb1f7d9ec6a5]::ops::function::FnOnce<(rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId)>>::call_once
  48:     0x7fafcb91fa7d - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::mir::query::UnsafetyCheckResult>
  49:     0x7fafcb990f6e - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(&rustc_middle[c145adf1c4567bf]::mir::query::UnsafetyCheckResult, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::mir::query::UnsafetyCheckResult>::{closure#3}>
  50:     0x7fafcae19b52 - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::mir::query::UnsafetyCheckResult>>
  51:     0x7fafcb8c13c9 - rustc_query_system[cf3d2502706fe991]::query::plumbing::force_query::<rustc_query_impl[8218de0923c6cd45]::queries::unsafety_check_result, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  52:     0x7fafcb8e3e2e - rustc_query_impl[8218de0923c6cd45]::query_callbacks::unsafety_check_result::force_from_dep_node
  53:     0x7fafcbbf1841 - <rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt as rustc_query_system[cf3d2502706fe991]::dep_graph::DepContext>::try_force_from_dep_node
  54:     0x7fafcaeb9263 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  55:     0x7fafcaeb8a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  56:     0x7fafcaeb8a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  57:     0x7fafcaeb8837 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  58:     0x7fafcb88d4ef - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::mir::query::BorrowCheckResult>
  59:     0x7fafcae18af3 - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::mir::query::BorrowCheckResult>>
  60:     0x7fafcae7688e - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::mir_borrowck
  61:     0x7fafcaa09df0 - rustc_typeck[1c3c3b5b5d734e80]::collect::type_of::type_of
  62:     0x7fafcb927594 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_span[4b4bb4534443c42f]::def_id::DefId, rustc_middle[c145adf1c4567bf]::ty::Ty>
  63:     0x7fafcb98d327 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(rustc_middle[c145adf1c4567bf]::ty::Ty, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::DefId, rustc_middle[c145adf1c4567bf]::ty::Ty>::{closure#3}>
  64:     0x7fafcae6bcf4 - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::type_of
  65:     0x7fafcaa19141 - rustc_typeck[1c3c3b5b5d734e80]::check::check::check_item_type
  66:     0x7fafca9dda0d - <rustc_middle[c145adf1c4567bf]::hir::map::Map>::visit_item_likes_in_module::<rustc_typeck[1c3c3b5b5d734e80]::check::CheckItemTypesVisitor>
  67:     0x7fafcb6b514c - rustc_typeck[1c3c3b5b5d734e80]::check::check::check_mod_item_types
  68:     0x7fafcb9204de - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, ()>
  69:     0x7fafcb992f8e - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<((), rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, ()>::{closure#3}>
  70:     0x7fafcae1aa66 - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, ()>>
  71:     0x7fafcb8ad963 - rustc_query_system[cf3d2502706fe991]::query::plumbing::get_query::<rustc_query_impl[8218de0923c6cd45]::queries::check_mod_item_types, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  72:     0x7fafcb68f086 - <rustc_middle[c145adf1c4567bf]::hir::map::Map>::for_each_module::<rustc_typeck[1c3c3b5b5d734e80]::check_crate::{closure#6}::{closure#0}>
  73:     0x7fafcb654118 - <rustc_session[95a8f1c94d15e5dc]::session::Session>::time::<(), rustc_typeck[1c3c3b5b5d734e80]::check_crate::{closure#6}>
  74:     0x7fafcb6485c3 - rustc_typeck[1c3c3b5b5d734e80]::check_crate
  75:     0x7fafcb3e1ed7 - rustc_interface[afc566840a941718]::passes::analysis
  76:     0x7fafcb939b62 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, (), core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  77:     0x7fafcb98c303 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, (), core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#3}>
  78:     0x7fafcb87bbae - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<(), core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>>
  79:     0x7fafcb8bac05 - rustc_query_system[cf3d2502706fe991]::query::plumbing::get_query::<rustc_query_impl[8218de0923c6cd45]::queries::analysis, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  80:     0x7fafcb3c0608 - <rustc_interface[afc566840a941718]::passes::QueryContext>::enter::<rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  81:     0x7fafcb3aeac5 - rustc_interface[afc566840a941718]::interface::create_compiler_and_run::<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}>
  82:     0x7fafcb394134 - std[cd3cf6af28dff6de]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  83:     0x7fafcb3c73e9 - <<std[cd3cf6af28dff6de]::thread::Builder>::spawn_unchecked_<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#1} as core[2734bb1f7d9ec6a5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  84:     0x7fafc8ddfd03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  85:     0x7fafc8ddfd03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  86:     0x7fafc8ddfd03 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  87:     0x7fafc8d02ea7 - start_thread
  88:     0x7fafc8c25def - clone
  89:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0 (7737e0b5c 2022-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `alloc::sync::Arc<core::blockchain::Blockchain>: core::marker::Send`
#1 [typeck] type-checking `core::blockchain::<impl at src/core/blockchain.rs:57:1: 593:2>::mine_block`
#2 [mir_built] building MIR for `core::blockchain::<impl at src/core/blockchain.rs:57:1: 593:2>::mine_block`
#3 [unsafety_check_result] unsafety-checking `core::blockchain::<impl at src/core/blockchain.rs:57:1: 593:2>::mine_block`
#4 [mir_borrowck] borrow-checking `core::blockchain::<impl at src/core/blockchain.rs:57:1: 593:2>::mine_block`
#5 [type_of] computing type of `core::blockchain::<impl at src/core/blockchain.rs:57:1: 593:2>::mine_block::{opaque#0}`
#6 [check_mod_item_types] checking item types in module `core::blockchain`
#7 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by lqd** [comment]
Could be the same as #96319

**Comment by steffahn** [comment]
Presumably @rustbot label A-incr-comp

**Comment by Noratrieb** [comment]
This issue does not have a reproduction and is therefore not really actionable, closing. If you find the problem again, please open a new issue, ideally with a reproduction.
