### ISSUE TITLE
rustdoc fails at resolving intra doc links

### ISSUE THREAD

**Issue by drahnr** [rust-lang/rust#96937]
### Code

```Rust
<code>
```

```bash
git clone --branch overseer-janitor https://github.com/paritytech/polkadot
git checkout 228286b7fc30bfc8e5531bf2da8a91ce4dadc209
# I could not find a way to minimize this yet beyond this crate
cargo doc -p polkadot-node-subsystem
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
****
```

### Error output

```
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:916:16
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 Documenting polkadot-overseer v0.9.19 (/media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/node/overseer)
Wrote dot graph to /media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/debug/build/polkadot-overseer-gen-proc-macro-59aceb927e03c652/out/overseer-subsystem-messaging.dot
expander: writing /media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/debug/build/expander-892520bfcbca1cc2/out/overlord-expansion-9e3f81136d16.rs
 Documenting polkadot-node-subsystem v0.9.19 (/media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/node/subsystem)
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:916:16
stack backtrace:
   0:     0x7f6e4fdc086d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f6e4fdc086d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f6e4fdc086d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f6e4fdc086d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f6e4fe204ec - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f6e4fdb0a98 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f6e4fdc4847 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f6e4fdc4847 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f6e4fdc4847 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f6e4fdc4510 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f6e505502c1 - rustc_driver[6eeb127b85fe99ac]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f6e4fdc5124 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  12:     0x7f6e4fdc4dd7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  13:     0x7f6e4fdc0d34 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f6e4fdc4ae9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  15:     0x7f6e4fd8d863 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  16:     0x7f6e4fe1d2f1 - core::panicking::panic_display::hb184394d54dc8360
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
  17:     0x7f6e4fe1d29b - core::panicking::panic_str::ha42887cd972750c9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
  18:     0x7f6e4fd8d6d6 - core::option::expect_failed::h9159c9d16ed9fb7c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
  19:     0x558f2488b119 - rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::resolve_associated_trait_item
  20:     0x558f248892e8 - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  21:     0x558f24887107 - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector>::resolve
  22:     0x558f24890eed - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector>::resolve_link
  23:     0x558f2488c5e9 - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_item
  24:     0x558f24898f7a - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_inner_recur
  25:     0x558f2488c9e4 - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_item
  26:     0x558f24898f7a - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_inner_recur
  27:     0x558f2488c9e4 - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_item
  28:     0x558f24898f7a - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_inner_recur
  29:     0x558f2488c9e4 - <rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::LinkCollector as rustdoc[a32c9c6374e2ed81]::visit::DocVisitor>::visit_item
  30:     0x558f24885a9c - rustdoc[a32c9c6374e2ed81]::passes::collect_intra_doc_links::collect_intra_doc_links
  31:     0x558f2474e964 - <rustc_session[95a8f1c94d15e5dc]::session::Session>::time::<rustdoc[a32c9c6374e2ed81]::clean::types::Crate, rustdoc[a32c9c6374e2ed81]::core::run_global_ctxt::{closure#8}>
  32:     0x558f249387df - rustdoc[a32c9c6374e2ed81]::core::run_global_ctxt
  33:     0x558f2474ede2 - <rustc_session[95a8f1c94d15e5dc]::session::Session>::time::<(rustdoc[a32c9c6374e2ed81]::clean::types::Crate, rustdoc[a32c9c6374e2ed81]::config::RenderOptions, rustdoc[a32c9c6374e2ed81]::formats::cache::Cache), rustdoc[a32c9c6374e2ed81]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#0}>
  34:     0x558f2495f0c5 - <rustc_interface[afc566840a941718]::passes::QueryContext>::enter::<rustdoc[a32c9c6374e2ed81]::main_options::{closure#0}::{closure#0}::{closure#1}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  35:     0x558f248ce090 - <rustc_interface[afc566840a941718]::interface::Compiler>::enter::<rustdoc[a32c9c6374e2ed81]::main_options::{closure#0}::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  36:     0x558f2492bf6c - rustc_span[4b4bb4534443c42f]::with_source_map::<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_interface[afc566840a941718]::interface::create_compiler_and_run<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::main_options::{closure#0}>::{closure#1}>
  37:     0x558f248bcd79 - rustc_interface[afc566840a941718]::interface::create_compiler_and_run::<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::main_options::{closure#0}>
  38:     0x558f246f8666 - rustdoc[a32c9c6374e2ed81]::main_options
  39:     0x558f24899f5c - std[cd3cf6af28dff6de]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustdoc[a32c9c6374e2ed81]::main_args::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  40:     0x558f2474c2c9 - <<std[cd3cf6af28dff6de]::thread::Builder>::spawn_unchecked_<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustdoc[a32c9c6374e2ed81]::main_args::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#1} as core[2734bb1f7d9ec6a5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f6e4fdd0d03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  42:     0x7f6e4fdd0d03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  43:     0x7f6e4fdd0d03 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7f6e4fa9785a - start_thread
  45:     0x7f6e4fa374c0 - __clone3
  46:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0 (7737e0b5c 2022-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `polkadot-node-subsystem`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name polkadot_node_subsystem node/subsystem/src/lib.rs -o /media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=8976c55348ac1f3a -L dependency=/media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/debug/deps --extern polkadot_node_jaeger=/media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/debug/deps/libpolkadot_node_jaeger-939246d47d9cd8b2.rmeta --extern polkadot_node_subsystem_types=/media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/debug/deps/libpolkadot_node_subsystem_types-d6f0b850554f1cb5.rmeta --extern polkadot_overseer=/media/supersonic1t/projects/parity/polkadot-bernhard-clunky-janitor/target/debug/deps/libpolkadot_overseer-7f19394f08ebd7c6.rmeta --crate-version 0.9.19` (exit status: 101)

```

</p>
</details>

**Comment by drahnr** [comment]
Note that it does work with

```
cargo +nightly --version --verbose
cargo 1.62.0-nightly (e2e2ddd 2022-04-05)
release: 1.62.0-nightly
commit-hash: e2e2dddebe66dfc1403a312653557e332445308b
commit-date: 2022-04-05
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: OracleLinux 35.0.0 [64-bit]
```

**Comment by petrochenkov** [comment]
Closing as fixed on nightly.
