### ISSUE TITLE
failed to extract DefId: local_def_id_to_hir_id

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#97143]
I was warking with my code, `cargo b`, `cargo c`, but suddenly it broke on `cargo check`.

### Code

Sorry, no code.

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

### Error output

```
thread 'rustc' panicked at 'Failed to extract DefId: local_def_id_to_hir_id 7fbc51800a870e1-79e136f4f6dfb58c', compiler/rustc_middle/src/dep_graph/dep_node.rs:270:17
stack backtrace:
   0:     0x7f092119d86d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f092119d86d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f092119d86d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f092119d86d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f09211fd4ec - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f092118da98 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f09211a1847 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f09211a1847 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f09211a1847 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f09211a1510 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f092192d2c1 - rustc_driver[6eeb127b85fe99ac]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f090ef5bb23 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha4858ee0256e158c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1867:9
  12:     0x7f090ef578fc - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hb60507113b9e6730
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/proc_macro/src/bridge/client.rs:319:21
  13:     0x7f090ef74970 - std::panicking::update_hook::{{closure}}::hcacd55567ca7c210
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:258:41
  14:     0x7f09211a2124 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  15:     0x7f09211a1dd7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  16:     0x7f092119dd34 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  17:     0x7f09211a1ae9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  18:     0x7f092116a863 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  19:     0x7f0922909b01 - <rustc_query_system[cf3d2502706fe991]::dep_graph::dep_node::DepNode<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind> as rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepNodeExt>::extract_def_id::{closure#0}
  20:     0x7f0923689669 - <rustc_query_system[cf3d2502706fe991]::dep_graph::dep_node::DepNode<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind> as rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  21:     0x7f0923cafe1c - rustc_query_impl[8218de0923c6cd45]::query_callbacks::local_def_id_to_hir_id::force_from_dep_node
  22:     0x7f0923fbf841 - <rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt as rustc_query_system[cf3d2502706fe991]::dep_graph::DepContext>::try_force_from_dep_node
  23:     0x7f0923287263 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  24:     0x7f0923286a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  25:     0x7f0923286a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  26:     0x7f0923286a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  27:     0x7f0923286a09 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  28:     0x7f09232d11f5 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<core[2734bb1f7d9ec6a5]::option::Option<(core[2734bb1f7d9ec6a5]::result::Result<rustc_middle[c145adf1c4567bf]::traits::select::EvaluationResult, rustc_middle[c145adf1c4567bf]::traits::select::OverflowError>, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex)>, rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_middle[c145adf1c4567bf]::infer::canonical::Canonical<rustc_middle[c145adf1c4567bf]::ty::ParamEnvAnd<rustc_middle[c145adf1c4567bf]::ty::Predicate>>, core[2734bb1f7d9ec6a5]::result::Result<rustc_middle[c145adf1c4567bf]::traits::select::EvaluationResult, rustc_middle[c145adf1c4567bf]::traits::select::OverflowError>>::{closure#2}>
  29:     0x7f0923218e95 - rustc_query_system[cf3d2502706fe991]::query::plumbing::get_query::<rustc_query_impl[8218de0923c6cd45]::queries::evaluate_obligation, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  30:     0x7f092324cc94 - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::evaluate_obligation
  31:     0x7f09235316cd - <rustc_trait_selection[1d7483382b445f9]::traits::fulfill::FulfillProcessor>::progress_changed_obligations
  32:     0x7f092354dd86 - <rustc_data_structures[762b64c8eff0c924]::obligation_forest::ObligationForest<rustc_trait_selection[1d7483382b445f9]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[1d7483382b445f9]::traits::fulfill::FulfillProcessor, rustc_data_structures[762b64c8eff0c924]::obligation_forest::Outcome<rustc_trait_selection[1d7483382b445f9]::traits::fulfill::PendingPredicateObligation, rustc_infer[844122ed1ec4b57a]::traits::FulfillmentErrorCode>>
  33:     0x7f092353019b - <rustc_trait_selection[1d7483382b445f9]::traits::fulfill::FulfillmentContext as rustc_infer[844122ed1ec4b57a]::traits::engine::TraitEngine>::select_where_possible
  34:     0x7f0922d6e452 - <rustc_infer[844122ed1ec4b57a]::infer::InferCtxtBuilder>::enter::<&rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults, <rustc_typeck[1c3c3b5b5d734e80]::check::inherited::InheritedBuilder>::enter<rustc_typeck[1c3c3b5b5d734e80]::check::typeck_with_fallback<rustc_typeck[1c3c3b5b5d734e80]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>::{closure#0}>
  35:     0x7f0922d485c3 - rustc_typeck[1c3c3b5b5d734e80]::check::typeck
  36:     0x7f0923cecaed - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>
  37:     0x7f0923d5ebae - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(&rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>::{closure#3}>
  38:     0x7f09231e5cc2 - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::ty::context::TypeckResults>>
  39:     0x7f0923c900b6 - rustc_query_system[cf3d2502706fe991]::query::plumbing::force_query::<rustc_query_impl[8218de0923c6cd45]::queries::typeck, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  40:     0x7f0923cb2bde - rustc_query_impl[8218de0923c6cd45]::query_callbacks::typeck::force_from_dep_node
  41:     0x7f0923fbf841 - <rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt as rustc_query_system[cf3d2502706fe991]::dep_graph::DepContext>::try_force_from_dep_node
  42:     0x7f0923287263 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  43:     0x7f0923203a49 - rustc_query_system[cf3d2502706fe991]::query::plumbing::ensure_must_run::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_span[4b4bb4534443c42f]::def_id::LocalDefId, &rustc_middle[c145adf1c4567bf]::mir::query::BorrowCheckResult>
  44:     0x7f092324459c - <rustc_query_impl[8218de0923c6cd45]::Queries as rustc_middle[c145adf1c4567bf]::ty::query::QueryEngine>::typeck
  45:     0x7f0922da9a7a - <rustc_middle[c145adf1c4567bf]::hir::map::Map>::par_body_owners::<rustc_typeck[1c3c3b5b5d734e80]::check::typeck_item_bodies::{closure#0}>
  46:     0x7f0923a1de1c - rustc_typeck[1c3c3b5b5d734e80]::check::typeck_item_bodies
  47:     0x7f0923d0b8d3 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, (), ()>
  48:     0x7f0923d611c3 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<((), rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, (), ()>::{closure#3}>
  49:     0x7f0923c53230 - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<(), ()>>
  50:     0x7f0923c7abc8 - rustc_query_system[cf3d2502706fe991]::query::plumbing::get_query::<rustc_query_impl[8218de0923c6cd45]::queries::typeck_item_bodies, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  51:     0x7f0923a22309 - <rustc_session[95a8f1c94d15e5dc]::session::Session>::time::<(), rustc_typeck[1c3c3b5b5d734e80]::check_crate::{closure#7}>
  52:     0x7f0923a165e3 - rustc_typeck[1c3c3b5b5d734e80]::check_crate
  53:     0x7f09237afed7 - rustc_interface[afc566840a941718]::passes::analysis
  54:     0x7f0923d07b62 - <rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepGraph<rustc_middle[c145adf1c4567bf]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c145adf1c4567bf]::ty::context::TyCtxt, (), core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  55:     0x7f0923d5a303 - rustc_data_structures[762b64c8eff0c924]::stack::ensure_sufficient_stack::<(core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_query_system[cf3d2502706fe991]::dep_graph::graph::DepNodeIndex), rustc_query_system[cf3d2502706fe991]::query::plumbing::execute_job<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, (), core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#3}>
  56:     0x7f0923c49bae - rustc_query_system[cf3d2502706fe991]::query::plumbing::try_execute_query::<rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt, rustc_query_system[cf3d2502706fe991]::query::caches::DefaultCache<(), core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>>
  57:     0x7f0923c88c05 - rustc_query_system[cf3d2502706fe991]::query::plumbing::get_query::<rustc_query_impl[8218de0923c6cd45]::queries::analysis, rustc_query_impl[8218de0923c6cd45]::plumbing::QueryCtxt>
  58:     0x7f092378e608 - <rustc_interface[afc566840a941718]::passes::QueryContext>::enter::<rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  59:     0x7f092377cac5 - rustc_interface[afc566840a941718]::interface::create_compiler_and_run::<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}>
  60:     0x7f0923762134 - std[cd3cf6af28dff6de]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  61:     0x7f09237953e9 - <<std[cd3cf6af28dff6de]::thread::Builder>::spawn_unchecked_<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_driver[6eeb127b85fe99ac]::run_compiler::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#1} as core[2734bb1f7d9ec6a5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  62:     0x7f09211add03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  63:     0x7f09211add03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  64:     0x7f09211add03 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  65:     0x7f09210cf609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  66:     0x7f0920fe8133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  67:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0 (7737e0b5c 2022-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `futures_util::lock::mutex::Mutex<futures_channel::mpsc::Sender<endpoint::ToEndpoint>>: core::marker::Send`
#1 [typeck] type-checking `connection::<impl at transports/quic/src/connection.rs:87:1: 420:2>::poll_event`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by kpp** [comment]
Well I may try to give you the code, but it's a huge amount of code. I can't/don't want to reduce it to MRE.

**Comment by cjgillot** [comment]
This looks like a bug with incremental compilation.  We will need both the code and the last version that passed `cargo check`.  `cargo clean` should allow you to continue working.
