### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by vbmade2000** [rust-lang/rust#97344]
### Code

```Rust
Not sure what caused it.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (4c60a0ea5 2022-05-04)
binary: rustc
commit-hash: 4c60a0ea5b2385d7400df9db1ad04e96f2a4c154
commit-date: 2022-05-04
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85 
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
stack backtrace:
   0:     0x7fcb215dbf7d - std::backtrace_rs::backtrace::libunwind::trace::h60df59602e900a84
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fcb215dbf7d - std::backtrace_rs::backtrace::trace_unsynchronized::h4de728a76dc3c11c
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fcb215dbf7d - std::sys_common::backtrace::_print_fmt::h3ea622c4324f07d6
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fcb215dbf7d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he809f9fc56245962
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fcb21637cbc - core::fmt::write::hd10d9412db84b2f0
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/core/src/fmt/mod.rs:1194:17
   5:     0x7fcb215cd671 - std::io::Write::write_fmt::h6d2b0777a373199e
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/io/mod.rs:1655:15
   6:     0x7fcb215dec95 - std::sys_common::backtrace::_print::hf9320b3c85b5c9c3
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fcb215dec95 - std::sys_common::backtrace::print::hd5e6a4965c8f48d7
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fcb215dec95 - std::panicking::default_hook::{{closure}}::h9bcde255b6f94a95
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/panicking.rs:295:22
   9:     0x7fcb215de909 - std::panicking::default_hook::h1184cc1001dcee07
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/panicking.rs:314:9
  10:     0x7fcb21d87931 - rustc_driver[eac439b5877b29b]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fcafe3335f3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8646f420564d969a
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/alloc/src/boxed.rs:1880:9
  12:     0x7fcafe3612ad - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::ha403e6b9117d0dd1
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/proc_macro/src/bridge/client.rs:335:21
  13:     0x7fcb215df466 - std::panicking::rust_panic_with_hook::hd0b795e06b63fc0c
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/panicking.rs:702:17
  14:     0x7fcb215df229 - std::panicking::begin_panic_handler::{{closure}}::h458061200738767c
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/panicking.rs:586:13
  15:     0x7fcb215dc434 - std::sys_common::backtrace::__rust_end_short_backtrace::hd840801340c49037
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7fcb215def99 - rust_begin_unwind
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/panicking.rs:584:5
  17:     0x7fcb215a4263 - core::panicking::panic_fmt::h07e87b1463fff16d
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/core/src/panicking.rs:142:14
  18:     0x7fcb215a412d - core::panicking::panic::hc430d81e7cddf5d9
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/core/src/panicking.rs:48:5
  19:     0x7fcb2393c797 - <rustc_metadata[e51e08f076adebde]::creader::CStore as rustc_session[b90a80a9d1890455]::cstore::CrateStore>::def_path_hash_to_def_id
  20:     0x7fcb23cf3697 - <rustc_query_system[4645395faa47b867]::dep_graph::dep_node::DepNode<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind> as rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  21:     0x7fcb2283285c - rustc_query_impl[5025da45d65f0927]::query_callbacks::adt_def::force_from_dep_node
  22:     0x7fcb23caf3e1 - <rustc_middle[ea2e9add8620f8ff]::ty::context::TyCtxt as rustc_query_system[4645395faa47b867]::dep_graph::DepContext>::try_force_from_dep_node
  23:     0x7fcb237f0b0e - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  24:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  25:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  26:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  27:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  28:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  29:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  30:     0x7fcb2389f4fc - rustc_query_system[4645395faa47b867]::query::plumbing::get_query::<rustc_query_impl[5025da45d65f0927]::queries::evaluate_obligation, rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  31:     0x7fcb238469c5 - <rustc_query_impl[5025da45d65f0927]::Queries as rustc_middle[ea2e9add8620f8ff]::ty::query::QueryEngine>::evaluate_obligation
  32:     0x7fcb23b724b1 - <rustc_trait_selection[67983b8d34da70b4]::traits::fulfill::FulfillProcessor>::process_changed_obligations
  33:     0x7fcb23b95ad8 - <rustc_data_structures[28e88579a02b9b91]::obligation_forest::ObligationForest<rustc_trait_selection[67983b8d34da70b4]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[67983b8d34da70b4]::traits::fulfill::FulfillProcessor, rustc_data_structures[28e88579a02b9b91]::obligation_forest::Outcome<rustc_trait_selection[67983b8d34da70b4]::traits::fulfill::PendingPredicateObligation, rustc_infer[c3028463dd6f8763]::traits::FulfillmentErrorCode>>
  34:     0x7fcb23b70d51 - <rustc_trait_selection[67983b8d34da70b4]::traits::fulfill::FulfillmentContext as rustc_infer[c3028463dd6f8763]::traits::engine::TraitEngine>::select_where_possible
  35:     0x7fcb23229d30 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_argument_types
  36:     0x7fcb232652f0 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  37:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  38:     0x7fcb23253210 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  39:     0x7fcb23264d43 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  40:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  41:     0x7fcb23387f84 - rustc_typeck[291a5f620b60d0ab]::check::check::check_fn
  42:     0x7fcb232625da - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_closure
  43:     0x7fcb23266abc - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  44:     0x7fcb2322919f - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_argument_types
  45:     0x7fcb23212b7e - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  46:     0x7fcb2320f038 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_call
  47:     0x7fcb23264c1d - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  48:     0x7fcb2322919f - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_argument_types
  49:     0x7fcb23212b7e - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  50:     0x7fcb2320f038 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_call
  51:     0x7fcb23264c1d - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  52:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  53:     0x7fcb2403ed03 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::demand_scrutinee_type
  54:     0x7fcb2325ff05 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_match
  55:     0x7fcb2326548c - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  56:     0x7fcb2322919f - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_argument_types
  57:     0x7fcb23212b7e - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  58:     0x7fcb2320f038 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_call
  59:     0x7fcb23264c1d - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  60:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  61:     0x7fcb2403ed03 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::demand_scrutinee_type
  62:     0x7fcb2325ff05 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_match
  63:     0x7fcb2326548c - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  64:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  65:     0x7fcb23252089 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_stmt
  66:     0x7fcb232538c2 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  67:     0x7fcb23264d43 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  68:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  69:     0x7fcb2326624b - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  70:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  71:     0x7fcb23253210 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  72:     0x7fcb23264d43 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  73:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  74:     0x7fcb23387f84 - rustc_typeck[291a5f620b60d0ab]::check::check::check_fn
  75:     0x7fcb232625da - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_closure
  76:     0x7fcb23266abc - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  77:     0x7fcb2322919f - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_argument_types
  78:     0x7fcb23212b7e - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  79:     0x7fcb2320f038 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_call
  80:     0x7fcb23264c1d - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_kind
  81:     0x7fcb23263a50 - <rustc_typeck[291a5f620b60d0ab]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  82:     0x7fcb23387f84 - rustc_typeck[291a5f620b60d0ab]::check::check::check_fn
  83:     0x7fcb232e60ac - <rustc_infer[c3028463dd6f8763]::infer::InferCtxtBuilder>::enter::<&rustc_middle[ea2e9add8620f8ff]::ty::context::TypeckResults, <rustc_typeck[291a5f620b60d0ab]::check::inherited::InheritedBuilder>::enter<rustc_typeck[291a5f620b60d0ab]::check::typeck_with_fallback<rustc_typeck[291a5f620b60d0ab]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[ea2e9add8620f8ff]::ty::context::TypeckResults>::{closure#0}>
  84:     0x7fcb2329c9f0 - rustc_typeck[291a5f620b60d0ab]::check::typeck
  85:     0x7fcb242c2f80 - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[ea2e9add8620f8ff]::ty::context::TyCtxt, rustc_span[46e75677c1ee720]::def_id::LocalDefId, &rustc_middle[ea2e9add8620f8ff]::ty::context::TypeckResults>
  86:     0x7fcb23866d66 - rustc_query_system[4645395faa47b867]::query::plumbing::try_execute_query::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt, rustc_query_system[4645395faa47b867]::query::caches::DefaultCache<rustc_span[46e75677c1ee720]::def_id::LocalDefId, &rustc_middle[ea2e9add8620f8ff]::ty::context::TypeckResults>>
  87:     0x7fcb24319411 - rustc_query_system[4645395faa47b867]::query::plumbing::force_query::<rustc_query_impl[5025da45d65f0927]::queries::typeck, rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  88:     0x7fcb243c11de - rustc_query_impl[5025da45d65f0927]::query_callbacks::typeck::force_from_dep_node
  89:     0x7fcb23caf3e1 - <rustc_middle[ea2e9add8620f8ff]::ty::context::TyCtxt as rustc_query_system[4645395faa47b867]::dep_graph::DepContext>::try_force_from_dep_node
  90:     0x7fcb237f0b0e - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  91:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  92:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  93:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  94:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  95:     0x7fcb237f0adc - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  96:     0x7fcb238afd7b - rustc_query_system[4645395faa47b867]::query::plumbing::get_query::<rustc_query_impl[5025da45d65f0927]::queries::type_of, rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
  97:     0x7fcb23375c15 - rustc_typeck[291a5f620b60d0ab]::check::check::check_item_type
  98:     0x7fcb2337b8c9 - rustc_typeck[291a5f620b60d0ab]::check::check::check_mod_item_types
  99:     0x7fcb242c486f - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[ea2e9add8620f8ff]::ty::context::TyCtxt, rustc_span[46e75677c1ee720]::def_id::LocalDefId, ()>
 100:     0x7fcb23869d6e - rustc_query_system[4645395faa47b867]::query::plumbing::try_execute_query::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt, rustc_query_system[4645395faa47b867]::query::caches::DefaultCache<rustc_span[46e75677c1ee720]::def_id::LocalDefId, ()>>
 101:     0x7fcb2439f823 - rustc_query_system[4645395faa47b867]::query::plumbing::get_query::<rustc_query_impl[5025da45d65f0927]::queries::check_mod_item_types, rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
 102:     0x7fcb240d7e5d - <rustc_middle[ea2e9add8620f8ff]::hir::map::Map>::for_each_module::<rustc_typeck[291a5f620b60d0ab]::check_crate::{closure#6}::{closure#0}>
 103:     0x7fcb240a0838 - <rustc_session[b90a80a9d1890455]::session::Session>::time::<(), rustc_typeck[291a5f620b60d0ab]::check_crate::{closure#6}>
 104:     0x7fcb24075913 - rustc_typeck[291a5f620b60d0ab]::check_crate
 105:     0x7fcb23e24eb7 - rustc_interface[d19b96c655da2cbf]::passes::analysis
 106:     0x7fcb242dbfc5 - <rustc_query_system[4645395faa47b867]::dep_graph::graph::DepGraph<rustc_middle[ea2e9add8620f8ff]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[ea2e9add8620f8ff]::ty::context::TyCtxt, (), core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>
 107:     0x7fcb2436dc81 - rustc_query_system[4645395faa47b867]::query::plumbing::try_execute_query::<rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt, rustc_query_system[4645395faa47b867]::query::caches::DefaultCache<(), core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>>
 108:     0x7fcb243ae88e - rustc_query_system[4645395faa47b867]::query::plumbing::get_query::<rustc_query_impl[5025da45d65f0927]::queries::analysis, rustc_query_impl[5025da45d65f0927]::plumbing::QueryCtxt>
 109:     0x7fcb23e060a7 - <rustc_interface[d19b96c655da2cbf]::passes::QueryContext>::enter::<rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>
 110:     0x7fcb23defd28 - <rustc_interface[d19b96c655da2cbf]::interface::Compiler>::enter::<rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}::{closure#2}, core[d929402d3f6fe1ad]::result::Result<core[d929402d3f6fe1ad]::option::Option<rustc_interface[d19b96c655da2cbf]::queries::Linker>, rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>
 111:     0x7fcb23e1916f - rustc_span[46e75677c1ee720]::with_source_map::<core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>, rustc_interface[d19b96c655da2cbf]::interface::create_compiler_and_run<core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>, rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}>::{closure#1}>
 112:     0x7fcb23df0994 - rustc_interface[d19b96c655da2cbf]::interface::create_compiler_and_run::<core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>, rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}>
 113:     0x7fcb23dee632 - <scoped_tls[e18f92e1d327fbf1]::ScopedKey<rustc_span[46e75677c1ee720]::SessionGlobals>>::set::<rustc_interface[d19b96c655da2cbf]::interface::run_compiler<core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>, rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}>::{closure#0}, core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>
 114:     0x7fcb23e0672f - std[fa812e4e74340a6e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d19b96c655da2cbf]::util::run_in_thread_pool_with_globals<rustc_interface[d19b96c655da2cbf]::interface::run_compiler<core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>, rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}>::{closure#0}, core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>::{closure#0}, core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>
 115:     0x7fcb23e06869 - <<std[fa812e4e74340a6e]::thread::Builder>::spawn_unchecked_<rustc_interface[d19b96c655da2cbf]::util::run_in_thread_pool_with_globals<rustc_interface[d19b96c655da2cbf]::interface::run_compiler<core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>, rustc_driver[eac439b5877b29b]::run_compiler::{closure#1}>::{closure#0}, core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>::{closure#0}, core[d929402d3f6fe1ad]::result::Result<(), rustc_errors[a7c2dcfd55d4989c]::ErrorGuaranteed>>::{closure#1} as core[d929402d3f6fe1ad]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 116:     0x7fcb215e93b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb67e12bf0289e79c
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/alloc/src/boxed.rs:1866:9
 117:     0x7fcb215e93b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h579da739f09a917c
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/alloc/src/boxed.rs:1866:9
 118:     0x7fcb215e93b3 - std::sys::unix::thread::Thread::new::thread_start::h7b7b375f63dbd91d
                               at /rustc/4c60a0ea5b2385d7400df9db1ad04e96f2a4c154/library/std/src/sys/unix/thread.rs:108:17
 119:     0x7fcb21502609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
 120:     0x7fcb2141b133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 121:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (4c60a0ea5 2022-05-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `diesel::query_source::joins::Join<minos::db::schema::hci::plate::table, minos::db::schema::hci::measurement::table, diesel::query_source::joins::Inner>: diesel::query_source::QuerySource`
#1 [typeck] type-checking `endpoints::experiments::get_experiment_data`
#2 [type_of] computing type of `endpoints::experiments::get_experiment_data::{opaque#0}`
#3 [check_mod_item_types] checking item types in module `endpoints::experiments`
#4 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

**Comment by vbmade2000** [comment]
Rebuilt after `cargo clean` and error is gone.

**Comment by Nilstrieb** [comment]
If you're not sure what exactly caused it, could you send the entire reproducible code? Or did the problem go away after a `cargo clean`?

**Comment by vbmade2000** [comment]
It was gone after `cargo clean`.

**Comment by istankovic** [comment]
This doesn't look like an actionable issue.

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by Noratrieb** [comment]
This issue does not have a reproduction and is therefore not really actionable, closing. If you find the problem again, please open a new issue, ideally with a reproduction.
