### ISSUE TITLE
The behavior of method ·`unwarp_or` and method `unwarp_or_else` of `Result` is inconsistent

### ISSUE THREAD

**Issue by franklucky001** [rust-lang/rust#97509]
I tried this code:
[dataset](https://github.com/franklucky001/nl-readers/blob/master/src/dataset.rs) line 155

```rust
fn samples_to_records<const N: usize>(
        samples: Vec<ClassifierSample>,
        vocab: &BTreeMap<String, usize>,
        class2id: & HashMap<String, usize>) -> Vec<ClassifierRecord<N>>{
        samples
            .into_iter()
            .map(|s|(
                s.text.chars()
                    .into_iter()
                    .map(|c|*vocab.get(&c.to_string()).unwrap_or(&0))
                    .collect(),
                s.label
                    .parse::<usize>()
                    .map_err(|e|{
                        eprintln!("num {:?} parse error {}", s.label, e);
                        e
                    })
                    // .unwrap_or(
                    //     *class2id.get(&s.label)
                    //         .expect(&format!("invalid label {}", &s.label))
                    // )
                    .unwrap_or_else(|e|{
                        *class2id.get(&s.label)
                            .expect(&format!("invalid label {}, error {}", &s.label, e))
                    }
                    )
            )
            )
            .map(|(word_ids, label_id)|ClassifierRecord::new(word_ids, label_id))
            .collect()
    }
}
```

I expected to see this happen: both `unwrap_or` and `unwrap_or_else`can consistently capture errors or work ok

Instead, this happened: when parse `str` value "3" to `usize`
- panic, use method `unwarp_or`, and `map_err` seem not work either
- all it's ok, use method `unwrap_or_else`

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc                                        
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18                              
host: x86_64-pc-windows-msvc                         
release: 1.61.0                                      
LLVM version: 14.0.0               
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'invalid label 3', src\dataset.rs:157:30
stack backtrace:
   0:     0x7ff76dccbddf - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff76dccbddf - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff76dccbddf - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff76dccbddf - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff76dcdb80a - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff76dcc91a9 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff76dccdf3b - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff76dccdf3b - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff76dccdf3b - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff76dccdb2e - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff76dcce531 - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:698
  11:     0x7ff76dcce3ed - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  12:     0x7ff76dccc6e7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff76dcce0c9 - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  14:     0x7ff76dce17c5 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  15:     0x7ff76dcdaa00 - core::panicking::panic_display<str>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:72
  16:     0x7ff76dcda9ab - core::panicking::panic_str
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:56
  17:     0x7ff76dce1619 - core::option::expect_failed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\option.rs:1874
  18:     0x7ff76dcaae4c - enum$<core::option::Option<ref$<usize> >, 1, 18446744073709551615, Some>::expect<ref$<usize> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\option.rs:718
  19:     0x7ff76dc98c5f - nl_readers::dataset::impl$2::samples_to_records::closure$0<32>
                               at E:\workspace\rust\nl-readers\src\dataset.rs:156
  20:     0x7ff76dcc270d - core::iter::adapters::map::map_fold::closure$0<nl_readers::dataset::ClassifierSample,tuple$<alloc::vec::Vec<usize,alloc::alloc::Global>,usize>,tuple$<>,nl_readers::dataset::impl$2::samples_to_records::closure_env$0<32>,core::iter::adapters::map::map_fold:
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\iter\adapters\map.rs:84
  21:     0x7ff76dcb72f6 - core::iter::traits::iterator::Iterator::fold<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,tuple$<>,core::iter::adapters::map::map_fold::closure_env$0<nl_readers::dataset::ClassifierSample,tuple$<alloc::vec::V
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\iter\traits\iterator.rs:2362
  22:     0x7ff76dcc17d5 - core::iter::adapters::map::impl$2::fold<tuple$<alloc::vec::Vec<usize,alloc::alloc::Global>,usize>,alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers::dataset::impl$2::samples_to_records::closure_env$0<32
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\iter\adapters\map.rs:124
  23:     0x7ff76dcc1702 - core::iter::adapters::map::impl$2::fold<nl_readers::dataset::ClassifierRecord<32>,core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers::dataset::impl$2::samples_to_records::c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\iter\adapters\map.rs:124
  24:     0x7ff76dcc1e86 - core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers::dataset::impl$2::samples_to_records::clo
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\iter\traits\iterator.rs:779
  25:     0x7ff76dca4e71 - alloc::vec::spec_extend::impl$1::spec_extend<nl_readers::dataset::ClassifierRecord<32>,core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers::da
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\alloc\src\vec\spec_extend.rs:40
  26:     0x7ff76dca0e4b - alloc::vec::spec_from_iter_nested::impl$1::from_iter<nl_readers::dataset::ClassifierRecord<32>,core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_rea
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\alloc\src\vec\spec_from_iter_nested.rs:62
  27:     0x7ff76dca38af - alloc::vec::in_place_collect::impl$1::from_iter<nl_readers::dataset::ClassifierRecord<32>,core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers:
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\alloc\src\vec\in_place_collect.rs:164
  28:     0x7ff76dca4a8f - alloc::vec::impl$17::from_iter<nl_readers::dataset::ClassifierRecord<32>,core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers::dataset::impl$2:
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\alloc\src\vec\mod.rs:2554
  29:     0x7ff76dcc1cdd - core::iter::traits::iterator::Iterator::collect<core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<nl_readers::dataset::ClassifierSample,alloc::alloc::Global>,nl_readers::dataset::impl$2::samples_to_records::clos
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\iter\traits\iterator.rs:1784
  30:     0x7ff76dc98a3d - nl_readers::dataset::ClassifierDataset::samples_to_records<32>
                               at E:\workspace\rust\nl-readers\src\dataset.rs:142
  31:     0x7ff76dc9840d - nl_readers::dataset::ClassifierDataset::build_dataset<32>
                               at E:\workspace\rust\nl-readers\src\dataset.rs:131
  32:     0x7ff76dc9f569 - nl_readers::build_classifier
                               at E:\workspace\rust\nl-readers\src\main.rs:8
  33:     0x7ff76dc9f939 - nl_readers::main
                               at E:\workspace\rust\nl-readers\src\main.rs:16
  34:     0x7ff76dcb3a8b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:227
  35:     0x7ff76dcc052b - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\sys_common\backtrace.rs:122
  36:     0x7ff76dcb63e1 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\rt.rs:145
  37:     0x7ff76dcc56be - core::ops::function::impls::impl$2::call_once
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:259
  38:     0x7ff76dcc56be - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  39:     0x7ff76dcc56be - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  40:     0x7ff76dcc56be - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  41:     0x7ff76dcc56be - std::rt::lang_start_internal::closure$2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  42:     0x7ff76dcc56be - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  43:     0x7ff76dcc56be - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  44:     0x7ff76dcc56be - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  45:     0x7ff76dcc56be - std::rt::lang_start_internal
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  46:     0x7ff76dcb63af - std::rt::lang_start<tuple$<> >
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\rt.rs:144
  47:     0x7ff76dc9f996 - main
  48:     0x7ff76dcdfefc - invoke_main
                               at d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  49:     0x7ff76dcdfefc - __scrt_common_main_seh
                               at d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  50:     0x7ff81b167034 - BaseThreadInitThunk
  51:     0x7ff81c2e2651 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\nl-readers.exe` (exit code: 101)
```

</p>
</details>
[THUCNews.tar.gz](https://github.com/rust-lang/rust/files/8792723/THUCNews.tar.gz)

**Comment by SkiFire13** [comment]
`unwrap_or` takes a value, and that needs to be evaluated before calling the function, meanwhile `unwrap_or_else` executes the closure only when there's an error. This is the difference between them and the reason to have two methods.

What I suspect is happening in your code is that `*class2id.get(&s.label).expect(&format!("invalid label {}", &s.label))` might not be valid if `s.label.parse::<usize>()` succeeds, but you're alwaysing evaluating it in the `unwrap_or` version.

**Comment by franklucky001** [comment]
@SkiFire13 You are right to say that closures cover up operations. I made this mistake. Thank you for reminding me.
