### ISSUE TITLE
rustdoc json ice: assertion failure: different Item.inner.id  with `--document-private-items --document-hidden-items`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#98007]
### Code

```Rust
#![crate_name = "foo"]

// This test ensures that there is no "infinite redirection" file generated (a
// file which redirects to itself).

// We check it's not a redirection file.
// @has 'foo/builders/struct.ActionRowBuilder.html'
// @has - '//*[@id="synthetic-implementations"]' 'Auto Trait Implementations'

// And that the link in the module is targetting it.
// @has 'foo/builders/index.html'
// @has - '//a[@href="struct.ActionRowBuilder.html"]' 'ActionRowBuilder'

mod auto {
    mod action_row {
        pub struct ActionRowBuilder;
    }

    #[doc(hidden)]
    pub mod builders {
        pub use super::action_row::ActionRowBuilder;
    }
}

pub use auto::*;

pub mod builders {
    pub use crate::auto::builders::*;
}
```

### Meta

`rustc --version --verbose`:
```
rustdoc 1.63.0-nightly (c08b235a5 2022-06-11)
binary: rustdoc
commit-hash: c08b235a5ce10167632bb0fddcd0c5d67f2d42e3
commit-date: 2022-06-11
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

### Error output
`rustdoc -Zunstable-options  --output-format json --cap-lints warn --document-private-items --document-hidden-items ./src/test/rustdoc/infinite-redirection.rs`
```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("0:7:1518"), crate_id: 0, name: Some("builders"), span: Some(Span { filename: "./src/test/rustdoc/infinite-redirection.rs", begin: (20, 4), end: (22, 5) }), visibility: Public, docs: None, links: {}, attrs: ["#[doc(hidden)]"], deprecation: None, inner: Module(Module { is_crate: false, items: [Id("0:8")] }) }`,
 right: `Item { id: Id("0:7:1518"), crate_id: 0, name: Some("builders"), span: Some(Span { filename: "./src/test/rustdoc/infinite-redirection.rs", begin: (20, 4), end: (22, 5) }), visibility: Public, docs: None, links: {}, attrs: ["#[doc(hidden)]"], deprecation: None, inner: Module(Module { is_crate: false, items: [Id("0:5:1517")] }) }`', src/librustdoc/json/mod.rs:202:17
stack backtrace:
   0:     0x7fbb7ee9e24d - std::backtrace_rs::backtrace::libunwind::trace::hbda756d3a5f7793b
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fbb7ee9e24d - std::backtrace_rs::backtrace::trace_unsynchronized::he406e69cad63dc23
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbb7ee9e24d - std::sys_common::backtrace::_print_fmt::haf02d0db8ce964ea
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fbb7ee9e24d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h593e23fa276ab7eb
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fbb7eefa03c - core::fmt::write::h15ae908cdc2b7057
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fbb7ee8f9e1 - std::io::Write::write_fmt::hd05fda0f86262a57
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/io/mod.rs:1654:15
   6:     0x7fbb7eea0f25 - std::sys_common::backtrace::_print::h56e00569a093de7b
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fbb7eea0f25 - std::sys_common::backtrace::print::h154890ec5be15427
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fbb7eea0f25 - std::panicking::default_hook::{{closure}}::h956bfa0e86fe51f6
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/panicking.rs:295:22
   9:     0x7fbb7eea0c46 - std::panicking::default_hook::h6043872de872daf7
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/panicking.rs:314:9
  10:     0x7fbb7f6fac61 - rustc_driver[887956d0deaa6d7a]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fbb7eea15fa - std::panicking::rust_panic_with_hook::h06a4e01a02150fc1
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/panicking.rs:702:17
  12:     0x7fbb7eea1437 - std::panicking::begin_panic_handler::{{closure}}::h376c0b0d176b15fb
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/panicking.rs:588:13
  13:     0x7fbb7ee9e704 - std::sys_common::backtrace::__rust_end_short_backtrace::hb6064a5b72d04bd2
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fbb7eea1169 - rust_begin_unwind
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/panicking.rs:584:5
  15:     0x7fbb7ee66373 - core::panicking::panic_fmt::h18f352cc18da6352
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/core/src/panicking.rs:142:14
  16:     0x7fbb7eef6de8 - core::panicking::assert_failed_inner::hc3f9e178e607f850
  17:     0x55f8334c6174 - core[47d7e3b58a64b363]::panicking::assert_failed::<rustdoc_json_types[8c03fa6f039a8cd6]::Item, rustdoc_json_types[8c03fa6f039a8cd6]::Item>
  18:     0x55f8337c2780 - <rustdoc[325768d69b163fb7]::json::JsonRenderer as rustdoc[325768d69b163fb7]::formats::renderer::FormatRenderer>::item
  19:     0x55f8337bc4a9 - <rustdoc[325768d69b163fb7]::json::JsonRenderer as rustdoc[325768d69b163fb7]::formats::renderer::FormatRenderer>::item
  20:     0x55f833737cca - rustdoc[325768d69b163fb7]::formats::renderer::run_format::<rustdoc[325768d69b163fb7]::json::JsonRenderer>
  21:     0x55f833511e32 - rustdoc[325768d69b163fb7]::run_renderer::<rustdoc[325768d69b163fb7]::json::JsonRenderer>
  22:     0x55f8337644bb - <rustc_session[350565c454728d1f]::session::Session>::time::<core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>, rustdoc[325768d69b163fb7]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#2}>
  23:     0x55f8336fdcc7 - <rustc_interface[823eb738556b78ea]::passes::QueryContext>::enter::<rustdoc[325768d69b163fb7]::main_options::{closure#0}::{closure#0}::{closure#1}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>
  24:     0x55f83360083a - <rustc_interface[823eb738556b78ea]::interface::Compiler>::enter::<rustdoc[325768d69b163fb7]::main_options::{closure#0}::{closure#0}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>
  25:     0x55f8337faaf6 - rustc_span[b519e1d6b7be61e8]::with_source_map::<core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>, rustc_interface[823eb738556b78ea]::interface::create_compiler_and_run<core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>, rustdoc[325768d69b163fb7]::main_options::{closure#0}>::{closure#1}>
  26:     0x55f833629bc1 - rustc_interface[823eb738556b78ea]::interface::create_compiler_and_run::<core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>, rustdoc[325768d69b163fb7]::main_options::{closure#0}>
  27:     0x55f8334dfb07 - <scoped_tls[dfe53452cd62d879]::ScopedKey<rustc_span[b519e1d6b7be61e8]::SessionGlobals>>::set::<rustdoc[325768d69b163fb7]::main_args::{closure#0}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>
  28:     0x55f83362ae7f - std[8de092468d8aceba]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[823eb738556b78ea]::util::run_in_thread_pool_with_globals<rustdoc[325768d69b163fb7]::main_args::{closure#0}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>::{closure#0}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>
  29:     0x55f833719699 - <<std[8de092468d8aceba]::thread::Builder>::spawn_unchecked_<rustc_interface[823eb738556b78ea]::util::run_in_thread_pool_with_globals<rustdoc[325768d69b163fb7]::main_args::{closure#0}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>::{closure#0}, core[47d7e3b58a64b363]::result::Result<(), rustc_errors[61501852ee8eeabe]::ErrorGuaranteed>>::{closure#1} as core[47d7e3b58a64b363]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7fbb7eeab523 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h68a1c90dcd11ebd9
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/alloc/src/boxed.rs:1951:9
  31:     0x7fbb7eeab523 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he92bdcacbb726b3b
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/alloc/src/boxed.rs:1951:9
  32:     0x7fbb7eeab523 - std::sys::unix::thread::Thread::new::thread_start::hb6f32585ac3785d3
                               at /rustc/c08b235a5ce10167632bb0fddcd0c5d67f2d42e3/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7fbb7ec7f54d - <unknown>
  34:     0x7fbb7ed04b14 - clone
  35:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (c08b235a5 2022-06-11) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
You mean https://github.com/rust-lang/rust/pull/98053 , right? ^^

Looks like I can still reproduce this:
$`~/.rustup/toolchains/master/bin/rustdoc --version`
`rustdoc 1.63.0-nightly (d40f24e95 2022-06-16)`

`~/.rustup/toolchains/master/bin/rustdoc -Zunstable-options --output-format json --cap-lints warn --document-private-items --document-hidden-items ./src/test/rustdoc/infinite-redirection.rs`

````
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("0:7:1529"), crate_id: 0, name: Some("builders"), span: Some(Span { filename: "./src/test/rustdoc/infinite-redirection.rs", begin: (20, 4), end: (22, 5) }), visibility: Public, docs: None, links: {}, attrs: ["#[doc(hidden)]"], deprecation: None, inner: Module(Module { is_crate: false, items: [Id("0:8")] }) }`,
 right: `Item { id: Id("0:7:1529"), crate_id: 0, name: Some("builders"), span: Some(Span { filename: "./src/test/rustdoc/infinite-redirection.rs", begin: (20, 4), end: (22, 5) }), visibility: Public, docs: None, links: {}, attrs: ["#[doc(hidden)]"], deprecation: None, inner: Module(Module { is_crate: false, items: [Id("0:5:1528")] }) }`', src/librustdoc/json/mod.rs:234:21
stack backtrace:
   0:     0x7f56f129e49d - std::backtrace_rs::backtrace::libunwind::trace::h6aafea5516e4bfb3
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f56f129e49d - std::backtrace_rs::backtrace::trace_unsynchronized::hbcdb3988957bd716
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f56f129e49d - std::sys_common::backtrace::_print_fmt::h5dee031312c45400
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f56f129e49d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd5d2448ca2750cd8
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f56f12fa2dc - core::fmt::write::he31ff040039f6999
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f56f128fb01 - std::io::Write::write_fmt::h75230ad9ee2f58d4
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/io/mod.rs:1654:15
   6:     0x7f56f12a1175 - std::sys_common::backtrace::_print::h6d256b189395961d
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f56f12a1175 - std::sys_common::backtrace::print::hf7a5cdb24da5efce
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f56f12a1175 - std::panicking::default_hook::{{closure}}::hefcd5ae4bc8144ef
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/panicking.rs:295:22
   9:     0x7f56f12a0e96 - std::panicking::default_hook::h31fefa94cf26c116
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/panicking.rs:314:9
  10:     0x7f56f1afbd21 - rustc_driver[474c9c938fff0173]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f56f12a184a - std::panicking::rust_panic_with_hook::hec596526dd12471b
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/panicking.rs:702:17
  12:     0x7f56f12a1687 - std::panicking::begin_panic_handler::{{closure}}::h13655ebbacf6e61b
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/panicking.rs:588:13
  13:     0x7f56f129e954 - std::sys_common::backtrace::__rust_end_short_backtrace::h3d5cf270ce171725
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f56f12a13b9 - rust_begin_unwind
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/panicking.rs:584:5
  15:     0x7f56f12662c3 - core::panicking::panic_fmt::hc96e8f9879b3be4d
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/core/src/panicking.rs:142:14
  16:     0x7f56f12f7088 - core::panicking::assert_failed_inner::hbb30d39562d7707e
  17:     0x55599bec9274 - core[3e71735526d4dd4b]::panicking::assert_failed::<rustdoc_json_types[71cfd09cfc6c9797]::Item, rustdoc_json_types[71cfd09cfc6c9797]::Item>
  18:     0x55599c1eb39b - <rustdoc[24247a081d39efee]::json::JsonRenderer as rustdoc[24247a081d39efee]::formats::renderer::FormatRenderer>::item
  19:     0x55599c1e50c9 - <rustdoc[24247a081d39efee]::json::JsonRenderer as rustdoc[24247a081d39efee]::formats::renderer::FormatRenderer>::item
  20:     0x55599c1671da - rustdoc[24247a081d39efee]::formats::renderer::run_format::<rustdoc[24247a081d39efee]::json::JsonRenderer>
  21:     0x55599bf244ae - rustdoc[24247a081d39efee]::run_renderer::<rustdoc[24247a081d39efee]::json::JsonRenderer>
  22:     0x55599c1f473b - <rustc_session[4c6539f8b6b5b057]::session::Session>::time::<core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>, rustdoc[24247a081d39efee]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#2}>
  23:     0x55599c12ab57 - <rustc_interface[ee056990e706b6be]::passes::QueryContext>::enter::<rustdoc[24247a081d39efee]::main_options::{closure#0}::{closure#0}::{closure#1}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>
  24:     0x55599c02c16a - <rustc_interface[ee056990e706b6be]::interface::Compiler>::enter::<rustdoc[24247a081d39efee]::main_options::{closure#0}::{closure#0}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>
  25:     0x55599bedd62a - rustc_span[f5616531ecb15b4d]::with_source_map::<core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>, rustc_interface[ee056990e706b6be]::interface::create_compiler_and_run<core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>, rustdoc[24247a081d39efee]::main_options::{closure#0}>::{closure#1}>
  26:     0x55599c056001 - rustc_interface[ee056990e706b6be]::interface::create_compiler_and_run::<core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>, rustdoc[24247a081d39efee]::main_options::{closure#0}>
  27:     0x55599bee1b0f - <scoped_tls[d09f79adf346c7b8]::ScopedKey<rustc_span[f5616531ecb15b4d]::SessionGlobals>>::set::<rustdoc[24247a081d39efee]::main_args::{closure#0}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>
  28:     0x55599c05651f - std[a1a042396ca320bb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ee056990e706b6be]::util::run_in_thread_pool_with_globals<rustdoc[24247a081d39efee]::main_args::{closure#0}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>::{closure#0}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>
  29:     0x55599c147589 - <<std[a1a042396ca320bb]::thread::Builder>::spawn_unchecked_<rustc_interface[ee056990e706b6be]::util::run_in_thread_pool_with_globals<rustdoc[24247a081d39efee]::main_args::{closure#0}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>::{closure#0}, core[3e71735526d4dd4b]::result::Result<(), rustc_errors[792e4eb1ba22caeb]::ErrorGuaranteed>>::{closure#1} as core[3e71735526d4dd4b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f56f12ab783 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb5e79c50ed46987d
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/alloc/src/boxed.rs:1951:9
  31:     0x7f56f12ab783 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6e5b090d5a8c80f9
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/alloc/src/boxed.rs:1951:9
  32:     0x7f56f12ab783 - std::sys::unix::thread::Thread::new::thread_start::h2a064b2098f494b9
                               at /rustc/d40f24e956a698e47a209541031c4045acc5a684/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7f56f107f54d - <unknown>
  34:     0x7f56f1104b14 - clone
  35:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (d40f24e95 2022-06-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z unstable-options

query stack during panic:
end of query stack
````

**Comment by GuillaumeGomez** [comment]
No no, I meant https://github.com/rust-lang/rust/pull/93518 as "it will be fixed by this one" (hence why I didn't close it :wink: ).

**Comment by matthiaskrgr** [comment]
ooh I didn't see it was a pr, not an issue 😂🙈
my bad!
