### ISSUE TITLE
ICE during type checking

### ISSUE THREAD

**Issue by aaronjanse** [rust-lang/rust#98035]
### Code

Using the following dependency:
```toml
wyrm = { version = "0.9.1", features = ["fast-math"] }
```

```Rust
use wyrm::{Arr, IndexInputNode};

fn main() {
    let x = IndexInputNode::new(&[0; 1]);
    let input: Vec<_> = (0..1).map(|_| x).collect();
    input[0].set_value(Arr::zeros(2));
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (ec55c6130 2022-06-10)
binary: rustc
commit-hash: ec55c61305eaf385fc1b93ac9a78284b4d887fe5
commit-date: 2022-06-10
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

### Error output

```
   Compiling rust v0.1.0 (/home/research/dev/hutter/rust)
error[E0599]: no method named `set_value` found for struct `Variable` in the current scope
   --> src/main.rs:7:14
    |
7   |     input[0].set_value(Arr::zeros(2));
    |              ^^^^^^^^^
    |
   ::: /home/research/.cargo/registry/src/github.com-1ecc6299db9ec823/wyrm-0.9.1/src/lib.rs:192:8
    |
192 |     fn set_value(&self, T);
    |        --------- the method is available for `Variable<IndexInputNode>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
2   | use wyrm::DataInput;
    |
help: there is an associated function with a similar name
    |
7   |     input[0].value(Arr::zeros(2));
    |              ~~~~~

error[E0271]: type mismatch resolving `<usize as ndarray::shape_builder::ShapeBuilder>::Dim == ndarray::dimension::dim::Dim<[usize; 2]>`
   --> src/main.rs:7:24
    |
7   |     input[0].set_value(Arr::zeros(2));
    |                        ^^^^^^^^^^ expected an array with a fixed size of 2 elements, found one with 1 element
    |
    = note: expected struct `ndarray::dimension::dim::Dim<[usize; 2]>`
               found struct `ndarray::dimension::dim::Dim<[usize; 1]>`
note: required by a bound in `ndarray::impl_constructors::<impl ndarray::ArrayBase<S, D>>::zeros`
   --> /home/research/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.11.2/src/impl_constructors.rs:188:32
    |
188 |               Sh: ShapeBuilder<Dim=D>,
    |                                ^^^^^ required by this bound in `ndarray::impl_constructors::<impl ndarray::ArrayBase<S, D>>::zeros`

error: internal compiler error: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:856:33: unexpected path: def=ndarray::ArrayBase substs=[_, _] path=Path { span: src/main.rs:7:24: 7:27 (#0), res: Def(TyAlias, DefId(20:11 ~ wyrm[2d3a]::Arr)), segments: [PathSegment { ident: Arr#0, hir_id: Some(HirId { owner: DefId(0:10 ~ rust[461b]::main), local_id: 40 }), res: Some(Err), args: None, infer_args: true }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/compiler/rustc_errors/src/lib.rs:1339:9
stack backtrace:
   0:     0x7f5ff945f21d - std::backtrace_rs::backtrace::libunwind::trace::ha7efd7311c1d75b8
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5ff945f21d - std::backtrace_rs::backtrace::trace_unsynchronized::h106a9c84f83bc267
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5ff945f21d - std::sys_common::backtrace::_print_fmt::h6170062356b82c62
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f5ff945f21d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd5e8e52fbb0efcd6
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f5ff94bb00c - core::fmt::write::h7d8886379d097fb9
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f5ff94509b1 - std::io::Write::write_fmt::haa354a529fa52a88
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/io/mod.rs:1654:15
   6:     0x7f5ff9461ef5 - std::sys_common::backtrace::_print::h277482dab988217c
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f5ff9461ef5 - std::sys_common::backtrace::print::h3ce74106fbe92258
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f5ff9461ef5 - std::panicking::default_hook::{{closure}}::hf6f2d76bfd2cacfa
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/panicking.rs:295:22
   9:     0x7f5ff9461c16 - std::panicking::default_hook::hfc9374d90ba9f405
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/panicking.rs:314:9
  10:     0x7f5ff9c77411 - rustc_driver[6ead317479d5ea3c]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f5ff94625ca - std::panicking::rust_panic_with_hook::h7a5a27174917a2d9
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/panicking.rs:702:17
  12:     0x7f5ffad2eff1 - std[f90a0bdbe6da2f7e]::panicking::begin_panic::<rustc_errors[aaf794d4ed0fbe82]::ExplicitBug>::{closure#0}
  13:     0x7f5ffad2ea86 - std[f90a0bdbe6da2f7e]::sys_common::backtrace::__rust_end_short_backtrace::<std[f90a0bdbe6da2f7e]::panicking::begin_panic<rustc_errors[aaf794d4ed0fbe82]::ExplicitBug>::{closure#0}, !>
  14:     0x7f5ffaca96f6 - std[f90a0bdbe6da2f7e]::panicking::begin_panic::<rustc_errors[aaf794d4ed0fbe82]::ExplicitBug>
  15:     0x7f5ffac59c76 - std[f90a0bdbe6da2f7e]::panic::panic_any::<rustc_errors[aaf794d4ed0fbe82]::ExplicitBug>
  16:     0x7f5ffac58915 - <rustc_errors[aaf794d4ed0fbe82]::HandlerInner>::bug::<&alloc[618e14b65b6f03eb]::string::String>
  17:     0x7f5ffac583f0 - <rustc_errors[aaf794d4ed0fbe82]::Handler>::bug::<&alloc[618e14b65b6f03eb]::string::String>
  18:     0x7f5ffad2771d - rustc_middle[407d32d8c5b3a63]::ty::context::tls::with_opt::<rustc_middle[407d32d8c5b3a63]::util::bug::opt_span_bug_fmt<rustc_span[a55587c41aa9df06]::span_encoding::Span>::{closure#0}, ()>
  19:     0x7f5ffad28566 - rustc_middle[407d32d8c5b3a63]::util::bug::opt_span_bug_fmt::<rustc_span[a55587c41aa9df06]::span_encoding::Span>
  20:     0x7f5ffad284e3 - rustc_middle[407d32d8c5b3a63]::util::bug::bug_fmt
  21:     0x7f5ffabfec5f - <rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor>::path_inferred_subst_iter
  22:     0x7f5ffabff1ea - <rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[6b1b8f28f8e46ea9]::intravisit::Visitor>::visit_expr
  23:     0x7f5ffabff07f - <rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[6b1b8f28f8e46ea9]::intravisit::Visitor>::visit_expr
  24:     0x7f5ffac25e92 - rustc_hir[6b1b8f28f8e46ea9]::intravisit::walk_expr::<rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  25:     0x7f5ffabff094 - <rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[6b1b8f28f8e46ea9]::intravisit::Visitor>::visit_expr
  26:     0x7f5ffac22957 - rustc_hir[6b1b8f28f8e46ea9]::intravisit::walk_block::<rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  27:     0x7f5ffabff094 - <rustc_infer[ab50ab6dd1ee79c9]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[6b1b8f28f8e46ea9]::intravisit::Visitor>::visit_expr
  28:     0x7f5ffabc84e4 - <rustc_infer[ab50ab6dd1ee79c9]::infer::InferCtxt>::emit_inference_failure_err
  29:     0x7f5ffab14162 - <rustc_infer[ab50ab6dd1ee79c9]::infer::InferCtxt as rustc_trait_selection[1a741c00b3a5de9e]::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  30:     0x7f5ffab07d07 - <rustc_infer[ab50ab6dd1ee79c9]::infer::InferCtxt as rustc_trait_selection[1a741c00b3a5de9e]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  31:     0x7f5ffb27326b - <rustc_infer[ab50ab6dd1ee79c9]::infer::InferCtxtBuilder>::enter::<&rustc_middle[407d32d8c5b3a63]::ty::context::TypeckResults, <rustc_typeck[44099968ee4a7d3e]::check::inherited::InheritedBuilder>::enter<rustc_typeck[44099968ee4a7d3e]::check::typeck_with_fallback<rustc_typeck[44099968ee4a7d3e]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[407d32d8c5b3a63]::ty::context::TypeckResults>::{closure#0}>
  32:     0x7f5ffb2097fa - rustc_typeck[44099968ee4a7d3e]::check::typeck
  33:     0x7f5ffb7fdbb4 - rustc_query_system[b7cd757c7107c129]::query::plumbing::try_execute_query::<rustc_query_impl[e64f1927253e429e]::plumbing::QueryCtxt, rustc_query_system[b7cd757c7107c129]::query::caches::DefaultCache<rustc_span[a55587c41aa9df06]::def_id::LocalDefId, &rustc_middle[407d32d8c5b3a63]::ty::context::TypeckResults>>
  34:     0x7f5ffb7d459e - <rustc_query_impl[e64f1927253e429e]::Queries as rustc_middle[407d32d8c5b3a63]::ty::query::QueryEngine>::typeck
  35:     0x7f5ffb20998f - rustc_typeck[44099968ee4a7d3e]::check::typeck
  36:     0x7f5ffb7fdbb4 - rustc_query_system[b7cd757c7107c129]::query::plumbing::try_execute_query::<rustc_query_impl[e64f1927253e429e]::plumbing::QueryCtxt, rustc_query_system[b7cd757c7107c129]::query::caches::DefaultCache<rustc_span[a55587c41aa9df06]::def_id::LocalDefId, &rustc_middle[407d32d8c5b3a63]::ty::context::TypeckResults>>
  37:     0x7f5ffb7d459e - <rustc_query_impl[e64f1927253e429e]::Queries as rustc_middle[407d32d8c5b3a63]::ty::query::QueryEngine>::typeck
  38:     0x7f5ffb2cb368 - <rustc_middle[407d32d8c5b3a63]::hir::map::Map>::par_body_owners::<rustc_typeck[44099968ee4a7d3e]::check::typeck_item_bodies::{closure#0}>
  39:     0x7f5ffc09cabc - rustc_typeck[44099968ee4a7d3e]::check::typeck_item_bodies
  40:     0x7f5ffc3ae16c - rustc_query_system[b7cd757c7107c129]::query::plumbing::try_execute_query::<rustc_query_impl[e64f1927253e429e]::plumbing::QueryCtxt, rustc_query_system[b7cd757c7107c129]::query::caches::DefaultCache<(), ()>>
  41:     0x7f5ffc3d8751 - rustc_query_system[b7cd757c7107c129]::query::plumbing::get_query::<rustc_query_impl[e64f1927253e429e]::queries::typeck_item_bodies, rustc_query_impl[e64f1927253e429e]::plumbing::QueryCtxt>
  42:     0x7f5ffc0d18b3 - <rustc_session[e344760ec700607d]::session::Session>::time::<(), rustc_typeck[44099968ee4a7d3e]::check_crate::{closure#7}>
  43:     0x7f5ffc0b9bbb - rustc_typeck[44099968ee4a7d3e]::check_crate
  44:     0x7f5ffbe797c7 - rustc_interface[18c13601d1c1b041]::passes::analysis
  45:     0x7f5ffc3a369f - rustc_query_system[b7cd757c7107c129]::query::plumbing::try_execute_query::<rustc_query_impl[e64f1927253e429e]::plumbing::QueryCtxt, rustc_query_system[b7cd757c7107c129]::query::caches::DefaultCache<(), core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>>
  46:     0x7f5ffc3ead0e - rustc_query_system[b7cd757c7107c129]::query::plumbing::get_query::<rustc_query_impl[e64f1927253e429e]::queries::analysis, rustc_query_impl[e64f1927253e429e]::plumbing::QueryCtxt>
  47:     0x7f5ffbe37697 - <rustc_interface[18c13601d1c1b041]::passes::QueryContext>::enter::<rustc_driver[6ead317479d5ea3c]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>
  48:     0x7f5ffbe2185f - <rustc_interface[18c13601d1c1b041]::interface::Compiler>::enter::<rustc_driver[6ead317479d5ea3c]::run_compiler::{closure#1}::{closure#2}, core[fb8004f40595a7a]::result::Result<core[fb8004f40595a7a]::option::Option<rustc_interface[18c13601d1c1b041]::queries::Linker>, rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>
  49:     0x7f5ffbe1af3f - rustc_span[a55587c41aa9df06]::with_source_map::<core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>, rustc_interface[18c13601d1c1b041]::interface::create_compiler_and_run<core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>, rustc_driver[6ead317479d5ea3c]::run_compiler::{closure#1}>::{closure#1}>
  50:     0x7f5ffbe226f2 - <scoped_tls[7a85c70f5bf24ae6]::ScopedKey<rustc_span[a55587c41aa9df06]::SessionGlobals>>::set::<rustc_interface[18c13601d1c1b041]::interface::run_compiler<core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>, rustc_driver[6ead317479d5ea3c]::run_compiler::{closure#1}>::{closure#0}, core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>
  51:     0x7f5ffbe37d2f - std[f90a0bdbe6da2f7e]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[18c13601d1c1b041]::util::run_in_thread_pool_with_globals<rustc_interface[18c13601d1c1b041]::interface::run_compiler<core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>, rustc_driver[6ead317479d5ea3c]::run_compiler::{closure#1}>::{closure#0}, core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>::{closure#0}, core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>
  52:     0x7f5ffbe37e89 - <<std[f90a0bdbe6da2f7e]::thread::Builder>::spawn_unchecked_<rustc_interface[18c13601d1c1b041]::util::run_in_thread_pool_with_globals<rustc_interface[18c13601d1c1b041]::interface::run_compiler<core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>, rustc_driver[6ead317479d5ea3c]::run_compiler::{closure#1}>::{closure#0}, core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>::{closure#0}, core[fb8004f40595a7a]::result::Result<(), rustc_errors[aaf794d4ed0fbe82]::ErrorGuaranteed>>::{closure#1} as core[fb8004f40595a7a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7f5ff946c4f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc5278f6b2fa0011f
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/alloc/src/boxed.rs:1951:9
  54:     0x7f5ff946c4f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha197d457f97d013a
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/alloc/src/boxed.rs:1951:9
  55:     0x7f5ff946c4f3 - std::sys::unix::thread::Thread::new::thread_start::h7a371de16594a307
                               at /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7f5ff9237ff2 - start_thread
  57:     0x7f5ff92babfc - clone3
  58:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (ec55c6130 2022-06-10) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck] type-checking `main::{closure#0}`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
Some errors have detailed explanations: E0271, E0599.
For more information about an error, try `rustc --explain E0271`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling ndarray v0.11.2
   Compiling wyrm v0.9.1
   Compiling rust v0.1.0 (/home/research/dev/hutter/rust)
error[E0599]: no method named `set_value` found for struct `Variable` in the current scope
   --> src/main.rs:7:14
    |
7   |     input[0].set_value(Arr::zeros(2));
    |              ^^^^^^^^^
    |
   ::: /home/research/.cargo/registry/src/github.com-1ecc6299db9ec823/wyrm-0.9.1/src/lib.rs:192:8
    |
192 |     fn set_value(&self, T);
    |        --------- the method is available for `Variable<IndexInputNode>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
2   | use wyrm::DataInput;
    |
help: there is an associated function with a similar name
    |
7   |     input[0].value(Arr::zeros(2));
    |              ~~~~~

error[E0271]: type mismatch resolving `<usize as ndarray::shape_builder::ShapeBuilder>::Dim == ndarray::dimension::dim::Dim<[usize; 2]>`
   --> src/main.rs:7:24
    |
7   |     input[0].set_value(Arr::zeros(2));
    |                        ^^^^^^^^^^ expected an array with a fixed size of 2 elements, found one with 1 element
    |
    = note: expected struct `ndarray::dimension::dim::Dim<[usize; 2]>`
               found struct `ndarray::dimension::dim::Dim<[usize; 1]>`
note: required by a bound in `ndarray::impl_constructors::<impl ndarray::ArrayBase<S, D>>::zeros`
   --> /home/research/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.11.2/src/impl_constructors.rs:188:32
    |
188 |               Sh: ShapeBuilder<Dim=D>,
    |                                ^^^^^ required by this bound in `ndarray::impl_constructors::<impl ndarray::ArrayBase<S, D>>::zeros`

error: internal compiler error: compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs:856:33: unexpected path: def=ndarray::ArrayBase substs=[_, _] path=Path { span: src/main.rs:7:24: 7:27 (#0), res: Def(TyAlias, DefId(20:11 ~ wyrm[46b1]::Arr)), segments: [PathSegment { ident: Arr#0, hir_id: Some(HirId { owner: DefId(0:10 ~ rust[1b5d]::main), local_id: 40 }), res: Some(Err), args: None, infer_args: true }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ec55c61305eaf385fc1b93ac9a78284b4d887fe5/compiler/rustc_errors/src/lib.rs:1339:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor>::path_inferred_subst_iter
   8: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
   9: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  10: rustc_hir::intravisit::walk_expr::<rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  11: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  12: rustc_hir::intravisit::walk_block::<rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor>
  13: <rustc_infer::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  14: <rustc_infer::infer::InferCtxt>::emit_inference_failure_err
  15: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  16: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  17: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
  18: rustc_typeck::check::typeck
  19: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  20: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  22: rustc_typeck::check::typeck
  23: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  24: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  25: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  26: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_typeck::check::typeck_item_bodies::{closure#0}>
  27: rustc_typeck::check::typeck_item_bodies
  28: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  29: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  30: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
  31: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
  32: rustc_typeck::check_crate
  33: rustc_interface::passes::analysis
  34: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  35: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  36: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  37: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  38: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  39: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  40: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (ec55c6130 2022-06-10) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck] type-checking `main::{closure#0}`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
Some errors have detailed explanations: E0271, E0599.
For more information about an error, try `rustc --explain E0271`.
error: could not compile `rust` due to 2 previous errors
```

</p>
</details>

**Comment by compiler-errors** [comment]
This is fixed by the latest nightly.
