### ISSUE TITLE
ICE during custom bootstapping with latest beta rustc `thread 'rustc' panicked at 'invalid enum variant tag while decoding `MacroKind`, expected 0..3',`

### ISSUE THREAD

**Issue by krasimirgg** [rust-lang/rust#98056]
### Code
We're hitting an ICE with latest beta in our custom rustc bootstapping process when we try it with latest rustc 1.62.0-beta.4 (but also with all previous candidates 1.62.0-beta.*) at roughly stage0 rustc. I tried as much as possible to minimize the reproducer but it's still a bit involved:
we first build the rust standard libs with beta, then we use the newly built standard libs and try to build a chain of a rust library ("gsgdt") that depends on a rust library ("serde") that depends on a proc macro crate ("serde_derive"). In real world, we see the ICE while building these crates. In the Docker reproducer repo below, these contain just a few lines each to trigger the ICE: serde_derive implements 2 proc_macro functions, serde just re-exports them and gsgdt just use-s them. We believe that there may be something wrong in the way we build the standard libraries, the reproducer includes full commands for building those in hopes that this may be helpful to debug.

This error doesn't reproduce if using a 1.61.* beta, or if using the non-bootstapping stdlibs shipped with beta.

You can find a Docker reproducer here: https://github.com/krasimirgg/rust-beta-ice, running it with https://github.com/krasimirgg/rust-beta-ice/blob/main/run-in-docker.sh.

### Meta
```
note: rustc 1.62.0-beta.4 (8fd9e5fe1 2022-06-08) running on x86_64-unknown-linux-gnu
```

### Error output

You can find an example output of running the script here: https://gist.github.com/krasimirgg/69af6c35ebbe90d0d1d080831e97ee4c
```
thread 'rustc' panicked at 'invalid enum variant tag while decoding `MacroKind`, expected 0..3', /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/compiler/rustc_span/src/hygiene.rs:1074:49
stack backtrace:
   0:     0x7fbde9d89f9d - std::backtrace_rs::backtrace::libunwind::trace::ha8c8441a09b8a5bc
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fbde9d89f9d - std::backtrace_rs::backtrace::trace_unsynchronized::h4b7870aa29a1d4c5
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbde9d89f9d - std::sys_common::backtrace::_print_fmt::h3813ee8655d510d5
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fbde9d89f9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5c2417fecf04c429
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fbde9de5c2c - core::fmt::write::hc93f7920cebf06e1
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fbde9d7b671 - std::io::Write::write_fmt::h19519306be6e3671
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/io/mod.rs:1654:15
   6:     0x7fbde9d8ccb5 - std::sys_common::backtrace::_print::h97846cc0e21fd9de
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fbde9d8ccb5 - std::sys_common::backtrace::print::h63d2c018d0bf2f6c
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fbde9d8ccb5 - std::panicking::default_hook::{{closure}}::h057304560eb89725
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/panicking.rs:295:22
   9:     0x7fbde9d8c929 - std::panicking::default_hook::h56aba7101aa524eb
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/panicking.rs:314:9
  10:     0x7fbdea550821 - rustc_driver[5f65306c54a6ecaf]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fbde9d8d486 - std::panicking::rust_panic_with_hook::hb3a06577f993bbf8
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/panicking.rs:702:17
  12:     0x7fbde9d8d249 - std::panicking::begin_panic_handler::{{closure}}::h7dc1a5be3ba8e30e
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/panicking.rs:586:13
  13:     0x7fbde9d8a454 - std::sys_common::backtrace::__rust_end_short_backtrace::h84df54e144d24792
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fbde9d8cfb9 - rust_begin_unwind
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/panicking.rs:584:5
  15:     0x7fbde9d52233 - core::panicking::panic_fmt::h5cbc1de5926677b5
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/core/src/panicking.rs:142:14
  16:     0x7fbdec0ef101 - <rustc_metadata[d0c7e7e2ff6d80a2]::creader::CStore>::module_children_untracked
  17:     0x7fbdebbb8821 - <rustc_resolve[8f0fa6daad6d188e]::Resolver>::resolve_ident_in_module_unadjusted_ext
  18:     0x7fbdebba329a - <rustc_resolve[8f0fa6daad6d188e]::imports::ImportResolver>::resolve_import::{closure#0}
  19:     0x7fbdebb83540 - <rustc_resolve[8f0fa6daad6d188e]::imports::ImportResolver>::resolve_imports
  20:     0x7fbdec8e22df - <rustc_resolve[8f0fa6daad6d188e]::Resolver as rustc_expand[43ed22878aebb5b9]::base::ResolverExpand>::resolve_imports
  21:     0x7fbdec18b3a8 - <rustc_expand[43ed22878aebb5b9]::expand::MacroExpander>::fully_expand_fragment
  22:     0x7fbdecc887ee - <rustc_expand[43ed22878aebb5b9]::expand::MacroExpander>::expand_crate
  23:     0x7fbdec5f2364 - <rustc_session[10c476fea796aaab]::session::Session>::time::<core[95e30efa3d82213]::result::Result<rustc_ast[1722aabf387c4ffc]::ast::Crate, rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_interface[36aec6e00c7579eb]::passes::configure_and_expand::{closure#1}>
  24:     0x7fbdec5eb573 - rustc_interface[36aec6e00c7579eb]::passes::configure_and_expand
  25:     0x7fbdec6126b7 - <rustc_interface[36aec6e00c7579eb]::queries::Queries>::expansion
  26:     0x7fbdec5bb639 - <rustc_interface[36aec6e00c7579eb]::interface::Compiler>::enter::<rustc_driver[5f65306c54a6ecaf]::run_compiler::{closure#1}::{closure#2}, core[95e30efa3d82213]::result::Result<core[95e30efa3d82213]::option::Option<rustc_interface[36aec6e00c7579eb]::queries::Linker>, rustc_errors[94b87227e55ce631]::ErrorGuaranteed>>
  27:     0x7fbdec5e3e1f - rustc_span[1763f0391cd17db9]::with_source_map::<core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_interface[36aec6e00c7579eb]::interface::create_compiler_and_run<core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_driver[5f65306c54a6ecaf]::run_compiler::{closure#1}>::{closure#1}>
  28:     0x7fbdec5bc484 - rustc_interface[36aec6e00c7579eb]::interface::create_compiler_and_run::<core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_driver[5f65306c54a6ecaf]::run_compiler::{closure#1}>
  29:     0x7fbdec5b9c22 - <scoped_tls[3e6335cf174636ea]::ScopedKey<rustc_span[1763f0391cd17db9]::SessionGlobals>>::set::<rustc_interface[36aec6e00c7579eb]::interface::run_compiler<core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_driver[5f65306c54a6ecaf]::run_compiler::{closure#1}>::{closure#0}, core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>>
  30:     0x7fbdec5d0d4f - std[3b849506ec31f0bb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[36aec6e00c7579eb]::util::run_in_thread_pool_with_globals<rustc_interface[36aec6e00c7579eb]::interface::run_compiler<core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_driver[5f65306c54a6ecaf]::run_compiler::{closure#1}>::{closure#0}, core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>>::{closure#0}, core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>>
  31:     0x7fbdec5d0e89 - <<std[3b849506ec31f0bb]::thread::Builder>::spawn_unchecked_<rustc_interface[36aec6e00c7579eb]::util::run_in_thread_pool_with_globals<rustc_interface[36aec6e00c7579eb]::interface::run_compiler<core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>, rustc_driver[5f65306c54a6ecaf]::run_compiler::{closure#1}>::{closure#0}, core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>>::{closure#0}, core[95e30efa3d82213]::result::Result<(), rustc_errors[94b87227e55ce631]::ErrorGuaranteed>>::{closure#1} as core[95e30efa3d82213]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7fbde9d973a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc3c8c22a0e4ed4c2
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/alloc/src/boxed.rs:1872:9
  33:     0x7fbde9d973a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0d2b611978f8ae59
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/alloc/src/boxed.rs:1872:9
  34:     0x7fbde9d973a3 - std::sys::unix::thread::Thread::new::thread_start::h672ea1f303194440
                               at /rustc/8fd9e5fe1ed168622450f8e79864901e64fc7fc1/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7fbde9cc7609 - start_thread
  36:     0x7fbde9be2133 - clone
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic
```

**Comment by krasimirgg** [comment]
This same error appears if using the bootstap beta version and the freshly-built "standard" stage0-stdlib sysroot via x.py. Added a reproducer doing that in:
https://github.com/krasimirgg/rust-beta-ice-2.

**Comment by jyn514** [comment]
This is not a bug in libproc_macro, you can't use proc_macro from beta with the in-tree compiler. See https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/ICE.2Fboot.20invalid.20enum.20variant.20tag.20while.20decoding.20.60MacroKind.60
