### ISSUE TITLE
Error when I tried to compile my code???

### ISSUE THREAD

**Issue by Sagawarrier** [rust-lang/rust#98196]
### Code

```Rust
use image::{ImageBuffer, RgbaImage};
use std::time::Instant;

const ITERATIONS: i32 = 100;

//A function that takes 4 coordinates and a color as input and draws a line
fn drawline(coordinates0: (i32, i32), coordinates1: (i32, i32), x0: i32, y0: i32, x1: i32, y1: i32, canvas: &mut RgbaImage, color: &[u8; 4]) {
    let steep: bool = false;
    //If the change across the y axis is greater than that of the x axis, then swap their roles
    if (coordinates0.0-coordinates1.0).abs()<(coordinates0.1-coordinates1.1).abs() {
        coordinates0 = (coordinates0.1, coordinates0.0);
        coordinates1 = (coordinates1.1, coordinates1.0);
        steep = true;
    }
    if coordinates0.0 > coordinates1.0 {
        (x0, y0) = coordinates0;
        (x1, y1) = coordinates1;
        coordinates0 = (x1, y0);
        coordinates1 = (x0, y1);
    }
    for x in coordinates0.0..coordinates1.0 {
        let t: f32 = (x-coordinates0.0) as f32/(coordinates1.0-coordinates0.0) as f32;
        let y: u32 = (coordinates0.1 as f32*(1.-t) + coordinates1.1 as f32*t).round() as u32;
        if steep {
            *canvas.get_pixel_mut(y, x as u32) = image::Rgba(*color);
        } else {
            *canvas.get_pixel_mut(x as u32, y) = image::Rgba(*color);
        }
    }
}

//A function that takes 4 coordinates and a color as input and draws a line
fn line(arr: (i32, i32, i32, i32, bool), canvas: &mut RgbaImage, color: [u8; 4]) {
    for x in arr.0..arr.2 {
        let t: f32 = (x-arr.0) as f32/(arr.2-arr.0) as f32;
        let y: u32 = (arr.1 as f32*(1.-t) + arr.3 as f32*t).round() as u32;
        if arr.4 {
            *canvas.get_pixel_mut(y, x as u32) = image::Rgba(color);
        } else {
            *canvas.get_pixel_mut(x as u32, y) = image::Rgba(color);
        }
    }
}

//A function that reverses the coordinates as seen fit in order to execute the function correctly
fn lineref(x0: i32, y0: i32, x1: i32, y1: i32) -> (i32, i32, i32, i32, bool) {
    let mut steep = false;
    if (x0-x1).abs()<(y0-y1).abs() {
        steep = true;
        if y0>y1 {
            (y1, x1, y0, x0, steep)
        } else {
            (y0, x0, y1, x1, steep)
        }
    } else {
        if x0>x1 {
            (x1, y1, x0, y0, steep)
        } else {
            (x0, y0, x1, y1, steep)
        }
    }
}



fn main() {
    let white: [u8; 4] = [255,255,255,255];
    let red: [u8; 4] = [255,0,0,255];
    
    let mut canvas: RgbaImage = ImageBuffer::new(100, 100);

    let time = Instant::now();

    for _i in 0..ITERATIONS {
        drawline((13, 20), (80, 40), &mut canvas, &white);
        drawline((20, 13), (40, 80), &mut canvas, &red);
        drawline((80, 40), (13, 20), &mut canvas, &red);
    }

    println!("Time elapsed lines: {:?}", time.elapsed());
    canvas.save("output.png").unwrap()
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (c52b9c10b 2022-05-16) running on x86_64-unknown-linux-gnu
```

### Error output

```
maximus@pop-os:~/Documents/Rust/open_gl_simple$ cargo run
    Updating crates.io index
  Downloaded once_cell v1.12.0
  Downloaded rayon-core v1.9.3
  Downloaded unicode-ident v1.0.1
  Downloaded proc-macro2 v1.0.39
  Downloaded miniz_oxide v0.5.3
  Downloaded rayon v1.5.3
  Downloaded num-traits v0.2.15
  Downloaded flume v0.10.13
  Downloaded num-integer v0.1.45
  Downloaded flate2 v1.0.24
  Downloaded crossbeam-epoch v0.9.9
  Downloaded crossbeam-channel v0.5.5
  Downloaded getrandom v0.2.7
  Downloaded crossbeam-utils v0.8.9
  Downloaded jpeg-decoder v0.2.6
  Downloaded syn v1.0.96
  Downloaded 16 crates (1.8 MB) in 0.40s
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.126
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.9
   Compiling proc-macro2 v1.0.39
   Compiling once_cell v1.12.0
   Compiling unicode-ident v1.0.1
   Compiling rayon-core v1.9.3
   Compiling syn v1.0.96
   Compiling crc32fast v1.3.2
   Compiling futures-core v0.3.21
   Compiling adler32 v1.2.0
   Compiling adler v1.0.2
   Compiling either v1.6.1
   Compiling futures-sink v0.3.21
   Compiling weezl v0.1.6
   Compiling bit_field v0.10.1
   Compiling half v1.8.2
   Compiling lebe v0.5.1
   Compiling bitflags v1.3.2
   Compiling smallvec v1.8.0
   Compiling color_quant v1.1.0
   Compiling bytemuck v1.9.1
   Compiling scoped_threadpool v0.1.9
   Compiling byteorder v1.4.3
   Compiling miniz_oxide v0.5.3
   Compiling deflate v1.0.0
   Compiling inflate v0.4.5
   Compiling gif v0.11.3
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.9
   Compiling lock_api v0.4.7
   Compiling num-traits v0.2.15
   Compiling rayon v1.5.3
   Compiling num-integer v0.1.45
   Compiling num-rational v0.4.0
   Compiling num-iter v0.1.43
   Compiling crossbeam-channel v0.5.5
   Compiling flate2 v1.0.24
   Compiling png v0.17.5
   Compiling quote v1.0.18
   Compiling spin v0.9.3
   Compiling num_cpus v1.13.1
   Compiling getrandom v0.2.7
   Compiling crossbeam-deque v0.8.1
   Compiling threadpool v1.8.1
   Compiling nanorand v0.7.0
   Compiling jpeg-decoder v0.2.6
   Compiling tiff v0.7.2
   Compiling pin-project-internal v1.0.10
   Compiling pin-project v1.0.10
   Compiling flume v0.10.13
   Compiling exr v1.4.2
   Compiling image v0.24.2
   Compiling open_gl_simple v0.1.0 (/home/maximus/Documents/Rust/open_gl_simple)
thread 'rustc' panicked at 'index out of bounds: the len is 4 but the index is 5', compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:819:59
stack backtrace:
   0:     0x7f12fbe9df9d - std::backtrace_rs::backtrace::libunwind::trace::h8186514013210084
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f12fbe9df9d - std::backtrace_rs::backtrace::trace_unsynchronized::h6b4775fb370663f3
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f12fbe9df9d - std::sys_common::backtrace::_print_fmt::h9a7223dc2b92e9c9
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f12fbe9df9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h87633ce4c5fbefb8
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f12fbef9c2c - core::fmt::write::h04bff3779da7dc66
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/core/src/fmt/mod.rs:1196:17
   5:     0x7f12fbe8f711 - std::io::Write::write_fmt::h5913e30e5965001c
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/io/mod.rs:1654:15
   6:     0x7f12fbea0cb5 - std::sys_common::backtrace::_print::h5de6f21b2e3c85bb
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f12fbea0cb5 - std::sys_common::backtrace::print::h98bf7475a6d68cb4
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f12fbea0cb5 - std::panicking::default_hook::{{closure}}::h50a7614704635be5
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/panicking.rs:295:22
   9:     0x7f12fbea0929 - std::panicking::default_hook::h630f1d438198ac08
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/panicking.rs:314:9
  10:     0x7f12fc6eae11 - rustc_driver[f4e8bd0914616802]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f12fbea1486 - std::panicking::rust_panic_with_hook::h6e073d85d8ad1485
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/panicking.rs:702:17
  12:     0x7f12fbea1287 - std::panicking::begin_panic_handler::{{closure}}::h83d1c2e91d5c752f
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/panicking.rs:588:13
  13:     0x7f12fbe9e454 - std::sys_common::backtrace::__rust_end_short_backtrace::h151abaf5b95641ec
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f12fbea0fb9 - rust_begin_unwind
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/panicking.rs:584:5
  15:     0x7f12fbe66233 - core::panicking::panic_fmt::h91e78448ef48848d
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/core/src/panicking.rs:142:14
  16:     0x7f12fbe66172 - core::panicking::panic_bounds_check::hee5909a6d34e9f3b
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/core/src/panicking.rs:84:5
  17:     0x7f12fdbc76c1 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_argument_types
  18:     0x7f12fdb8f6ba - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_call
  19:     0x7f12fdbdda58 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  20:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  21:     0x7f12fdbcba39 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_stmt
  22:     0x7f12fdbcd0c0 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  23:     0x7f12fdbddb7e - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  24:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  25:     0x7f12fdbd9469 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_match
  26:     0x7f12fdbde2c7 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  27:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  28:     0x7f12fdbcc79d - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_stmt
  29:     0x7f12fdbcd0c0 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  30:     0x7f12fdbe02f0 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  31:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  32:     0x7f12fdbd9469 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_match
  33:     0x7f12fdbde2c7 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  34:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  35:     0x7f12fdbdf086 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  36:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  37:     0x7f12fdbcc79d - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_stmt
  38:     0x7f12fdbcd7b2 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  39:     0x7f12fdbddb7e - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_kind
  40:     0x7f12fdbdc890 - <rustc_typeck[9826d543c376686c]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  41:     0x7f12fdcf3942 - rustc_typeck[9826d543c376686c]::check::check::check_fn
  42:     0x7f12fdc5e29c - <rustc_infer[bea3751217f904eb]::infer::InferCtxtBuilder>::enter::<&rustc_middle[9da56bdffed011e6]::ty::context::TypeckResults, <rustc_typeck[9826d543c376686c]::check::inherited::InheritedBuilder>::enter<rustc_typeck[9826d543c376686c]::check::typeck_with_fallback<rustc_typeck[9826d543c376686c]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[9da56bdffed011e6]::ty::context::TypeckResults>::{closure#0}>
  43:     0x7f12fdc1d220 - rustc_typeck[9826d543c376686c]::check::typeck
  44:     0x7f12fec2d9f0 - <rustc_query_system[e95eab9e86022889]::dep_graph::graph::DepGraph<rustc_middle[9da56bdffed011e6]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9da56bdffed011e6]::ty::context::TyCtxt, rustc_span[51e5e155fa309565]::def_id::LocalDefId, &rustc_middle[9da56bdffed011e6]::ty::context::TypeckResults>
  45:     0x7f12fe1c86f6 - rustc_query_system[e95eab9e86022889]::query::plumbing::try_execute_query::<rustc_query_impl[84e0d871b49b4d57]::plumbing::QueryCtxt, rustc_query_system[e95eab9e86022889]::query::caches::DefaultCache<rustc_span[51e5e155fa309565]::def_id::LocalDefId, &rustc_middle[9da56bdffed011e6]::ty::context::TypeckResults>>
  46:     0x7f12fe1940f8 - <rustc_query_impl[84e0d871b49b4d57]::Queries as rustc_middle[9da56bdffed011e6]::ty::query::QueryEngine>::typeck
  47:     0x7f12fdcb52c8 - <rustc_middle[9da56bdffed011e6]::hir::map::Map>::par_body_owners::<rustc_typeck[9826d543c376686c]::check::typeck_item_bodies::{closure#0}>
  48:     0x7f12fe9e071c - rustc_typeck[9826d543c376686c]::check::typeck_item_bodies
  49:     0x7f12fec4ad48 - <rustc_query_system[e95eab9e86022889]::dep_graph::graph::DepGraph<rustc_middle[9da56bdffed011e6]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9da56bdffed011e6]::ty::context::TyCtxt, (), ()>
  50:     0x7f12fecf7452 - rustc_query_system[e95eab9e86022889]::query::plumbing::try_execute_query::<rustc_query_impl[84e0d871b49b4d57]::plumbing::QueryCtxt, rustc_query_system[e95eab9e86022889]::query::caches::DefaultCache<(), ()>>
  51:     0x7f12fed1e9a1 - rustc_query_system[e95eab9e86022889]::query::plumbing::get_query::<rustc_query_impl[84e0d871b49b4d57]::queries::typeck_item_bodies, rustc_query_impl[84e0d871b49b4d57]::plumbing::QueryCtxt>
  52:     0x7f12fea19933 - <rustc_session[e0c1d2b850b9f2b6]::session::Session>::time::<(), rustc_typeck[9826d543c376686c]::check_crate::{closure#7}>
  53:     0x7f12fea01f4b - rustc_typeck[9826d543c376686c]::check_crate
  54:     0x7f12fe79bda7 - rustc_interface[713d0d9db8a1df40]::passes::analysis
  55:     0x7f12fec46aa5 - <rustc_query_system[e95eab9e86022889]::dep_graph::graph::DepGraph<rustc_middle[9da56bdffed011e6]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9da56bdffed011e6]::ty::context::TyCtxt, (), core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>
  56:     0x7f12feced4d1 - rustc_query_system[e95eab9e86022889]::query::plumbing::try_execute_query::<rustc_query_impl[84e0d871b49b4d57]::plumbing::QueryCtxt, rustc_query_system[e95eab9e86022889]::query::caches::DefaultCache<(), core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>>
  57:     0x7f12fed2e94e - rustc_query_system[e95eab9e86022889]::query::plumbing::get_query::<rustc_query_impl[84e0d871b49b4d57]::queries::analysis, rustc_query_impl[84e0d871b49b4d57]::plumbing::QueryCtxt>
  58:     0x7f12fe77c887 - <rustc_interface[713d0d9db8a1df40]::passes::QueryContext>::enter::<rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>
  59:     0x7f12fe7678d8 - <rustc_interface[713d0d9db8a1df40]::interface::Compiler>::enter::<rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}::{closure#2}, core[63bf9982e82485d3]::result::Result<core[63bf9982e82485d3]::option::Option<rustc_interface[713d0d9db8a1df40]::queries::Linker>, rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>
  60:     0x7f12fe78ff4f - rustc_span[51e5e155fa309565]::with_source_map::<core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>, rustc_interface[713d0d9db8a1df40]::interface::create_compiler_and_run<core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>, rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}>::{closure#1}>
  61:     0x7f12fe77b754 - rustc_interface[713d0d9db8a1df40]::interface::create_compiler_and_run::<core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>, rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}>
  62:     0x7f12fe765de2 - <scoped_tls[2d300ce9482df573]::ScopedKey<rustc_span[51e5e155fa309565]::SessionGlobals>>::set::<rustc_interface[713d0d9db8a1df40]::interface::run_compiler<core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>, rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}>::{closure#0}, core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>
  63:     0x7f12fe77cf0f - std[ae5e8d7d94b027e8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[713d0d9db8a1df40]::util::run_in_thread_pool_with_globals<rustc_interface[713d0d9db8a1df40]::interface::run_compiler<core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>, rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}>::{closure#0}, core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>::{closure#0}, core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>
  64:     0x7f12fe77d049 - <<std[ae5e8d7d94b027e8]::thread::Builder>::spawn_unchecked_<rustc_interface[713d0d9db8a1df40]::util::run_in_thread_pool_with_globals<rustc_interface[713d0d9db8a1df40]::interface::run_compiler<core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>, rustc_driver[f4e8bd0914616802]::run_compiler::{closure#1}>::{closure#0}, core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>::{closure#0}, core[63bf9982e82485d3]::result::Result<(), rustc_errors[2517e9836de18d26]::ErrorGuaranteed>>::{closure#1} as core[63bf9982e82485d3]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  65:     0x7f12fbeab3a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1e87d47f9c3a818b
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/alloc/src/boxed.rs:1872:9
  66:     0x7f12fbeab3a3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc3d24a117925be14
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/alloc/src/boxed.rs:1872:9
  67:     0x7f12fbeab3a3 - std::sys::unix::thread::Thread::new::thread_start::h39eed1633cf142ff
                               at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/sys/unix/thread.rs:108:17
  68:     0x7f12fbc6cb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  69:     0x7f12fbcfea00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  70:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (c52b9c10b 2022-05-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `open_gl_simple`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
maximus@pop-os:~/Documents/Rust/open_gl_simple$ RUST_BACKTRACE=1 cargo build
   Compiling open_gl_simple v0.1.0 (/home/maximus/Documents/Rust/open_gl_simple)
thread 'rustc' panicked at 'index out of bounds: the len is 4 but the index is 5', compiler/rustc_typeck/src/check/fn_ctxt/checks.rs:819:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/c52b9c10bfb5164015eb977ff498e0597ae63eb1/library/core/src/panicking.rs:84:5
   3: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
   4: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
   5: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
   6: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
   7: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
   8: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
   9: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  10: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  11: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  12: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  13: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  14: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  15: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  16: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  17: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  18: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
  19: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  20: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  21: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  22: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  23: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  24: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  25: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  26: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
  27: rustc_typeck::check::check::check_fn
  28: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
  29: rustc_typeck::check::typeck
  30: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  32: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::typeck
  33: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_typeck::check::typeck_item_bodies::{closure#0}>
  34: rustc_typeck::check::typeck_item_bodies
  35: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  36: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  37: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
  38: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
  39: rustc_typeck::check_crate
  40: rustc_interface::passes::analysis
  41: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  42: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  43: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  44: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  45: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  46: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  47: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  48: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (c52b9c10b 2022-05-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `open_gl_simple`
```

</p>
</details>

**Comment by eggyal** [comment]
You're using an nightly from over a month ago; could you please `rustup update` and let us know if the issue is still present in the latest nightly? Thanks!

**Comment by compiler-errors** [comment]
This is indeed fixed on nightly. Closing.
