### ISSUE TITLE
thread 'rustc' panicked at 'Illegal read of: 77944', in dep_graph

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#98339]
not sure what caused this, I thought it was my changes but it was unrelated so stashed them and pulled latest master, but it still ICEs

### Meta
branch was set to: abace0a1f17

`rustc --version --verbose`:
```
<version>
```

### Error output

<details><summary><strong>Backtrace</strong></summary>
<p>

```
    Checking rustc_codegen_cranelift v0.1.0 (.../rust/compiler/rustc_codegen_cranelift)
thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:564:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/option.rs:1854:5
   5: <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::stable_crate_id_to_crate_num
   6: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   7: <[(rustc_middle::ty::Predicate, rustc_span::span_encoding::Span)] as rustc_middle::ty::codec::RefDecodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   8: <rustc_query_impl::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle::ty::generics::GenericPredicates>
   9: <<rustc_query_impl::queries::predicates_of as rustc_query_system::query::config::QueryDescription<rustc_query_impl::plumbing::QueryCtxt>>::TRY_LOAD_FROM_DISK::{closure#0} as core::ops::function::FnOnce<(rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::dep_graph::serialized::SerializedDepNodeIndex)>>::call_once
  10: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::predicates_of, rustc_query_impl::plumbing::QueryCtxt>
  11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
  12: <rustc_trait_selection::traits::wf::WfPredicates>::nominal_obligations
  13: <rustc_trait_selection::traits::wf::WfPredicates>::compute
  14: <rustc_trait_selection::traits::fulfill::FulfillProcessor>::process_changed_obligations
  15: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor, rustc_data_structures::obligation_forest::Outcome<rustc_trait_selection::traits::fulfill::PendingPredicateObligation, rustc_infer::traits::FulfillmentErrorCode>>
  16: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_all_or_error
  17: <rustc_typeck::check::fn_ctxt::FnCtxt>::select_all_obligations_or_error
  18: <rustc_infer::infer::InferCtxtBuilder>::enter::<(), <rustc_typeck::check::inherited::InheritedBuilder>::enter<<rustc_typeck::check::wfcheck::CheckWfFcxBuilder>::with_fcx<rustc_typeck::check::wfcheck::check_item_fn::{closure#0}>::{closure#0}, ()>::{closure#0}>
  19: rustc_typeck::check::wfcheck::check_item_fn
  20: rustc_typeck::check::wfcheck::check_item_well_formed
  21: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, ()>
  22: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_item_well_formed
  24: rustc_data_structures::sync::par_for_each_in::<&alloc::vec::Vec<rustc_hir::hir::MaybeOwner<&rustc_hir::hir::OwnerInfo>>, <rustc_middle::hir::map::Map>::par_visit_all_item_likes<rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor>::{closure#0}>
  25: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#5}, ()>
  26: rustc_typeck::check_crate
  27: rustc_interface::passes::analysis
  28: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  29: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  30: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  31: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  32: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  33: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  34: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  35: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-beta.2 (daf68b1f7 2022-05-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type dylib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C symbol-mangling-version=v0 -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -Z unstable-options -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z binary-dep-depinfo -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 77944', /rustc/daf68b1f766e67ffe040260b15c218301853386a/compiler/rustc_query_system/src/dep_graph/graph.rs:436:25
stack backtrace:
   0:     0x7fe8c083dfed - std::backtrace_rs::backtrace::libunwind::trace::ha8406fd4a233ad1f
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe8c083dfed - std::backtrace_rs::backtrace::trace_unsynchronized::h95f26ca4bd23bd0f
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe8c083dfed - std::sys_common::backtrace::_print_fmt::h9955f0b025c061cd
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fe8c083dfed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1025ecd2bac85833
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fe8c0899c7c - core::fmt::write::hd5fa34bae8a7f0ea
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fe8c082f6c1 - std::io::Write::write_fmt::h203cec764662c27d
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/io/mod.rs:1654:15
   6:     0x7fe8c0840d05 - std::sys_common::backtrace::_print::h330c8fadbab13d8b
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fe8c0840d05 - std::sys_common::backtrace::print::h38d4cf1c3e16e656
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fe8c0840d05 - std::panicking::default_hook::{{closure}}::h56cdf194ec124abb
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:295:22
   9:     0x7fe8c0840979 - std::panicking::default_hook::h9929fdc60733f795
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:314:9
  10:     0x7fe8c10067e1 - rustc_driver[25b442836e214e3a]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fe8c08414d6 - std::panicking::rust_panic_with_hook::h490228be5a55104d
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:702:17
  12:     0x7fe8c08412d7 - std::panicking::begin_panic_handler::{{closure}}::hfd963b6683c36656
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:588:13
  13:     0x7fe8c083e4a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h2912e3decfe2cba4
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fe8c0841009 - rust_begin_unwind
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:584:5
  15:     0x7fe8c0806283 - core::panicking::panic_fmt::hf4ba906a2c8693a2
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:142:14
  16:     0x7fe8c2a6194d - <rustc_middle[b283510e1dd05d73]::dep_graph::dep_node::DepKind as rustc_query_system[d6f3c753593960fb]::dep_graph::DepKind>::read_deps::<<rustc_query_system[d6f3c753593960fb]::dep_graph::graph::DepGraph<rustc_middle[b283510e1dd05d73]::dep_graph::dep_node::DepKind>>::read_index::{closure#0}>
  17:     0x7fe8c2b2c80a - rustc_query_system[d6f3c753593960fb]::query::plumbing::get_query::<rustc_query_impl[d28b29c5c0f26ce3]::queries::def_span, rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt>
  18:     0x7fe8c2aaf36e - <rustc_query_impl[d28b29c5c0f26ce3]::Queries as rustc_middle[b283510e1dd05d73]::ty::query::QueryEngine>::def_span
  19:     0x7fe8c18bd4a6 - <rustc_span[9389a2ea4399dbf9]::def_id::DefId as rustc_query_impl[d28b29c5c0f26ce3]::keys::Key>::default_span
  20:     0x7fe8c1aa3389 - rustc_query_impl[d28b29c5c0f26ce3]::make_query::predicates_of
  21:     0x7fe8c19a9829 - <rustc_query_system[d6f3c753593960fb]::query::plumbing::QueryState<rustc_span[9389a2ea4399dbf9]::def_id::DefId>>::try_collect_active_jobs::<rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt>
  22:     0x7fe8c198b61c - <rustc_query_impl[d28b29c5c0f26ce3]::Queries>::try_collect_active_jobs
  23:     0x7fe8c1922fae - <rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt>::try_print_query_stack
  24:     0x7fe8c10a6202 - rustc_interface[1214bec19156c976]::interface::try_print_query_stack
  25:     0x7fe8c10074b5 - rustc_driver[25b442836e214e3a]::report_ice
  26:     0x7fe8c08414d6 - std::panicking::rust_panic_with_hook::h490228be5a55104d
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:702:17
  27:     0x7fe8c08412d7 - std::panicking::begin_panic_handler::{{closure}}::hfd963b6683c36656
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:588:13
  28:     0x7fe8c083e4a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h2912e3decfe2cba4
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys_common/backtrace.rs:138:18
  29:     0x7fe8c0841009 - rust_begin_unwind
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:584:5
  30:     0x7fe8c0806283 - core::panicking::panic_fmt::hf4ba906a2c8693a2
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:142:14
  31:     0x7fe8c08968e1 - core::panicking::panic_display::h85c49ea53beff92d
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:72:5
  32:     0x7fe8c089688b - core::panicking::panic_str::h54aad4367eb7a446
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:56:5
  33:     0x7fe8c08060f6 - core::option::expect_failed::h1c20531357267673
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/option.rs:1854:5
  34:     0x7fe8c2bb82ea - <rustc_metadata[861e9325ed4d7b3f]::creader::CStore as rustc_session[42681064e675acd6]::cstore::CrateStore>::stable_crate_id_to_crate_num
  35:     0x7fe8c2ac12e1 - <rustc_span[9389a2ea4399dbf9]::span_encoding::Span as rustc_serialize[d140f8edb489d2a6]::serialize::Decodable<rustc_query_impl[d28b29c5c0f26ce3]::on_disk_cache::CacheDecoder>>::decode
  36:     0x7fe8c2a53ef1 - <[(rustc_middle[b283510e1dd05d73]::ty::Predicate, rustc_span[9389a2ea4399dbf9]::span_encoding::Span)] as rustc_middle[b283510e1dd05d73]::ty::codec::RefDecodable<rustc_query_impl[d28b29c5c0f26ce3]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7fe8c2a5dbc5 - <rustc_query_impl[d28b29c5c0f26ce3]::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle[b283510e1dd05d73]::ty::generics::GenericPredicates>
  38:     0x7fe8c2b32da0 - <<rustc_query_impl[d28b29c5c0f26ce3]::queries::predicates_of as rustc_query_system[d6f3c753593960fb]::query::config::QueryDescription<rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt>>::TRY_LOAD_FROM_DISK::{closure#0} as core[4a8947a89ffd1b77]::ops::function::FnOnce<(rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt, rustc_query_system[d6f3c753593960fb]::dep_graph::serialized::SerializedDepNodeIndex)>>::call_once
  39:     0x7fe8c2b0c00e - rustc_query_system[d6f3c753593960fb]::query::plumbing::get_query::<rustc_query_impl[d28b29c5c0f26ce3]::queries::predicates_of, rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt>
  40:     0x7fe8c2aacf2e - <rustc_query_impl[d28b29c5c0f26ce3]::Queries as rustc_middle[b283510e1dd05d73]::ty::query::QueryEngine>::predicates_of
  41:     0x7fe8c2e5458e - <rustc_trait_selection[ca1439896d44cba3]::traits::wf::WfPredicates>::nominal_obligations
  42:     0x7fe8c2e51fbc - <rustc_trait_selection[ca1439896d44cba3]::traits::wf::WfPredicates>::compute
  43:     0x7fe8c2df41aa - <rustc_trait_selection[ca1439896d44cba3]::traits::fulfill::FulfillProcessor>::process_changed_obligations
  44:     0x7fe8c2e1bfb3 - <rustc_data_structures[bd64897f28733a43]::obligation_forest::ObligationForest<rustc_trait_selection[ca1439896d44cba3]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[ca1439896d44cba3]::traits::fulfill::FulfillProcessor, rustc_data_structures[bd64897f28733a43]::obligation_forest::Outcome<rustc_trait_selection[ca1439896d44cba3]::traits::fulfill::PendingPredicateObligation, rustc_infer[651265fedc88e434]::traits::FulfillmentErrorCode>>
  45:     0x7fe8c2df2a9a - <rustc_trait_selection[ca1439896d44cba3]::traits::fulfill::FulfillmentContext as rustc_infer[651265fedc88e434]::traits::engine::TraitEngine>::select_all_or_error
  46:     0x7fe8c24feb0c - <rustc_typeck[3745d619f139cfc0]::check::fn_ctxt::FnCtxt>::select_all_obligations_or_error
  47:     0x7fe8c3326b9f - <rustc_infer[651265fedc88e434]::infer::InferCtxtBuilder>::enter::<(), <rustc_typeck[3745d619f139cfc0]::check::inherited::InheritedBuilder>::enter<<rustc_typeck[3745d619f139cfc0]::check::wfcheck::CheckWfFcxBuilder>::with_fcx<rustc_typeck[3745d619f139cfc0]::check::wfcheck::check_item_fn::{closure#0}>::{closure#0}, ()>::{closure#0}>
  48:     0x7fe8c334e1c3 - rustc_typeck[3745d619f139cfc0]::check::wfcheck::check_item_fn
  49:     0x7fe8c25c96ae - rustc_typeck[3745d619f139cfc0]::check::wfcheck::check_item_well_formed
  50:     0x7fe8c354b2af - <rustc_query_system[d6f3c753593960fb]::dep_graph::graph::DepGraph<rustc_middle[b283510e1dd05d73]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b283510e1dd05d73]::ty::context::TyCtxt, rustc_span[9389a2ea4399dbf9]::def_id::LocalDefId, ()>
  51:     0x7fe8c2ae5ffe - rustc_query_system[d6f3c753593960fb]::query::plumbing::try_execute_query::<rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt, rustc_query_system[d6f3c753593960fb]::query::caches::DefaultCache<rustc_span[9389a2ea4399dbf9]::def_id::LocalDefId, ()>>
  52:     0x7fe8c2ab02e1 - <rustc_query_impl[d28b29c5c0f26ce3]::Queries as rustc_middle[b283510e1dd05d73]::ty::query::QueryEngine>::check_item_well_formed
  53:     0x7fe8c25be3ae - rustc_data_structures[bd64897f28733a43]::sync::par_for_each_in::<&alloc[c5b2ee6b894df563]::vec::Vec<rustc_hir[374f189791373ac]::hir::MaybeOwner<&rustc_hir[374f189791373ac]::hir::OwnerInfo>>, <rustc_middle[b283510e1dd05d73]::hir::map::Map>::par_visit_all_item_likes<rustc_typeck[3745d619f139cfc0]::check::wfcheck::CheckTypeWellFormedVisitor>::{closure#0}>
  54:     0x7fe8c3336062 - <rustc_session[42681064e675acd6]::session::Session>::track_errors::<rustc_typeck[3745d619f139cfc0]::check_crate::{closure#5}, ()>
  55:     0x7fe8c331d6ed - rustc_typeck[3745d619f139cfc0]::check_crate
  56:     0x7fe8c30b7aa7 - rustc_interface[1214bec19156c976]::passes::analysis
  57:     0x7fe8c3562a75 - <rustc_query_system[d6f3c753593960fb]::dep_graph::graph::DepGraph<rustc_middle[b283510e1dd05d73]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[b283510e1dd05d73]::ty::context::TyCtxt, (), core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>
  58:     0x7fe8c3608181 - rustc_query_system[d6f3c753593960fb]::query::plumbing::try_execute_query::<rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt, rustc_query_system[d6f3c753593960fb]::query::caches::DefaultCache<(), core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>>
  59:     0x7fe8c364949e - rustc_query_system[d6f3c753593960fb]::query::plumbing::get_query::<rustc_query_impl[d28b29c5c0f26ce3]::queries::analysis, rustc_query_impl[d28b29c5c0f26ce3]::plumbing::QueryCtxt>
  60:     0x7fe8c3098527 - <rustc_interface[1214bec19156c976]::passes::QueryContext>::enter::<rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>
  61:     0x7fe8c3083588 - <rustc_interface[1214bec19156c976]::interface::Compiler>::enter::<rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}::{closure#2}, core[4a8947a89ffd1b77]::result::Result<core[4a8947a89ffd1b77]::option::Option<rustc_interface[1214bec19156c976]::queries::Linker>, rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>
  62:     0x7fe8c30abc7f - rustc_span[9389a2ea4399dbf9]::with_source_map::<core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>, rustc_interface[1214bec19156c976]::interface::create_compiler_and_run<core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>, rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}>::{closure#1}>
  63:     0x7fe8c30842f4 - rustc_interface[1214bec19156c976]::interface::create_compiler_and_run::<core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>, rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}>
  64:     0x7fe8c3081a92 - <scoped_tls[fdc467f1f45e3091]::ScopedKey<rustc_span[9389a2ea4399dbf9]::SessionGlobals>>::set::<rustc_interface[1214bec19156c976]::interface::run_compiler<core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>, rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}>::{closure#0}, core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>
  65:     0x7fe8c3098baf - std[49987cacb63ffdeb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1214bec19156c976]::util::run_in_thread_pool_with_globals<rustc_interface[1214bec19156c976]::interface::run_compiler<core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>, rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}>::{closure#0}, core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>::{closure#0}, core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>
  66:     0x7fe8c3098ce9 - <<std[49987cacb63ffdeb]::thread::Builder>::spawn_unchecked_<rustc_interface[1214bec19156c976]::util::run_in_thread_pool_with_globals<rustc_interface[1214bec19156c976]::interface::run_compiler<core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>, rustc_driver[25b442836e214e3a]::run_compiler::{closure#1}>::{closure#0}, core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>::{closure#0}, core[4a8947a89ffd1b77]::result::Result<(), rustc_errors[afa4f82815d8f672]::ErrorGuaranteed>>::{closure#1} as core[4a8947a89ffd1b77]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  67:     0x7fe8c084b3f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h997dc5bc9efdb91e
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/alloc/src/boxed.rs:1872:9
  68:     0x7fe8c084b3f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h482cb6422469721b
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/alloc/src/boxed.rs:1872:9
  69:     0x7fe8c084b3f3 - std::sys::unix::thread::Thread::new::thread_start::hcd1011649240eef0
                               at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/sys/unix/thread.rs:108:17
  70:     0x7fe8c0761609 - start_thread
                               at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  71:     0x7fe8c067a163 - clone
                               at /build/glibc-sMfBJT/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  72:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-beta.2 (daf68b1f7 2022-05-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type dylib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C symbol-mangling-version=v0 -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -Z unstable-options -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z binary-dep-depinfo -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
rustc exited with signal: 6 (core dumped)
error: could not compile `rustc_codegen_cranelift`

Caused by:
  process didn't exit successfully: `/home/dpc/code/rust/build/bootstrap/debug/rustc --crate-name rustc_codegen_cranelift --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type dylib --emit=dep-info,metadata -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=394dda7bc36fb6f5 -C extra-filename=-394dda7bc36fb6f5 --out-dir /home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C incremental=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/incremental -L dependency=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/release/deps --extern ar=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libar-4ae07157b9a86496.rmeta --extern cranelift_codegen=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libcranelift_codegen-90ae69cd31483998.rmeta --extern cranelift_frontend=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libcranelift_frontend-09ab713b3f9413d6.rmeta --extern cranelift_module=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libcranelift_module-dc93d434b86b1ad4.rmeta --extern cranelift_native=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libcranelift_native-6a3b92e9c0d30318.rmeta --extern cranelift_object=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libcranelift_object-9412ac51eb1563c6.rmeta --extern gimli=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libgimli-bd2c1294f6036aea.rmeta --extern indexmap=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libindexmap-c4230988bf97f3ef.rmeta --extern object=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libobject-0cfb8dc596880160.rmeta --extern once_cell=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libonce_cell-448595e8ae1aef3e.rmeta --extern smallvec=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libsmallvec-4a90802da05c84cf.rmeta --extern target_lexicon=/home/dpc/code/rust/build/x86_64-unknown-linux-gnu/stage0-codegen/x86_64-unknown-linux-gnu/release/deps/libtarget_lexicon-9c88e6cad212d6c4.rmeta --cfg=bootstrap -Csymbol-mangling-version=v0 -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Zunstable-options -Csplit-debuginfo=off -Cllvm-args=-import-instr-limit=10 -Z binary-dep-depinfo` (exit status: 254)
Build completed unsuccessfully in 0:00:14
```

</p>
</details>

**Comment by cbeuw** [comment]
This looks like the same as #97017

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by cyrgani** [comment]
Closing this issue as no longer reproducible per https://forge.rust-lang.org/release/issue-triaging.html#further-triaging.
