### ISSUE TITLE
Error when running rustdoc ... `--output-format json`

### ISSUE THREAD

**Issue by makspll** [rust-lang/rust#98465]
### Code
N/A

Error when running `rustup run nightly cargo rustdoc -p bevy:0.8.0-dev -- --output-format json -Zunstable-options` in crate with 
`bevy = { git = "https://github.com/bevyengine/bevy" }` as dependency

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (4cbaac699 2022-05-25)
binary: rustc
commit-hash: 4cbaac699c14b7ac7cc80e54823b2ef6afeb64af
commit-date: 2022-05-25
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.4
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("26:3173"), crate_id: 26, name: Some("TypeRegistry"), span: Some(Span { filename: "/home/makspll/.cargo/git/checkouts/bevy-f66245b8e5deb629/3d68094/crates/bevy_reflect/src/type_registry.rs", begin: (21, 0), end: (23, 1) }), visibility: Public, docs: Some("A synchronized wrapper around a [`TypeRegistry`]."), links: {"`TypeRegistry`": Id("26:1145")}, attrs: [], deprecation: None, inner: Struct(Struct { struct_type: Plain, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [Id("26:3174")], impls: [] }) }`,
 right: `Item { id: Id("26:3173"), crate_id: 26, name: Some("TypeRegistryArc"), span: Some(Span { filename: "/home/makspll/.cargo/git/checkouts/bevy-f66245b8e5deb629/3d68094/crates/bevy_reflect/src/type_registry.rs", begin: (21, 0), end: (23, 1) }), visibility: Public, docs: Some("A synchronized wrapper around a [`TypeRegistry`]."), links: {"`TypeRegistry`": Id("26:1145")}, attrs: [], deprecation: None, inner: Struct(Struct { struct_type: Plain, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [Id("26:3174")], impls: [] }) }`', src/librustdoc/json/mod.rs:196:17

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
makspll@maks-ubuntu:~/Git/bevy_scripting$ rustup run nightly cargo rustdoc -p bevy:0.8.0-dev -- --output-format json -Zunstable-options
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /home/makspll/Git/bevy_scripting/bevy_mod_scripting/Cargo.toml
workspace: /home/makspll/Git/bevy_scripting/Cargo.toml
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /home/makspll/Git/bevy_scripting/bevy_mod_scripting_derive/Cargo.toml
workspace: /home/makspll/Git/bevy_scripting/Cargo.toml
    Updating git repository `https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d`
   Compiling proc-macro2 v1.0.40
   Compiling unicode-ident v1.0.1
   Compiling quote v1.0.20
   Compiling syn v1.0.98
   Compiling autocfg v1.1.0
   Compiling libc v0.2.126
    Checking cfg-if v1.0.0
   Compiling serde_derive v1.0.137
   Compiling serde v1.0.137
    Checking once_cell v1.12.0
   Compiling version_check v0.9.4
    Checking bitflags v1.3.2
    Checking byteorder v1.4.3
   Compiling parking_lot_core v0.8.5
    Checking scopeguard v1.1.0
   Compiling memchr v2.5.0
    Checking pin-project-lite v0.2.9
   Compiling log v0.4.17
   Compiling futures-core v0.3.21
    Checking fixedbitset v0.4.1
    Checking cache-padded v1.2.0
   Compiling erased-serde v0.3.21
    Checking waker-fn v1.1.0
    Checking futures-io v0.3.21
    Checking fastrand v1.7.0
    Checking parking v2.0.0
    Checking event-listener v2.5.2
    Checking slab v0.4.6
    Checking async-task v4.2.0
    Checking downcast-rs v1.2.0
    Checking bevy_ptr v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking lazy_static v1.4.0
   Compiling pkg-config v0.3.25
    Checking regex-syntax v0.6.26
   Compiling crossbeam-utils v0.8.9
    Checking ansi_term v0.12.1
    Checking cty v0.2.2
    Checking ppv-lite86 v0.2.16
    Checking same-file v1.0.6
   Compiling anyhow v1.0.58
    Checking unicode-width v0.1.9
    Checking unicode-xid v0.2.3
    Checking termcolor v1.1.3
   Compiling khronos-egl v4.1.0
    Checking bit-vec v0.6.3
   Compiling ash v0.34.0+1.2.203
    Checking arrayvec v0.7.2
   Compiling cfg_aliases v0.1.1
    Checking rustc-hash v1.1.0
   Compiling crc32fast v1.3.2
    Checking hexf-parse v0.2.1
    Checking glow v0.11.2
    Checking renderdoc-sys v0.7.1
    Checking adler v1.0.2
    Checking profiling v1.0.6
    Checking inplace_it v0.3.3
    Checking adler32 v1.2.0
    Checking copyless v0.1.5
    Checking const_panic v0.2.3
    Checking scoped_threadpool v0.1.9
    Checking color_quant v1.1.0
    Checking hex v0.4.3
    Checking radsort v0.1.0
    Checking ttf-parser v0.15.2
   Compiling serde_json v1.0.81
    Checking svg_fmt v0.4.1
   Compiling inflections v1.1.1
    Checking ab_glyph_rasterizer v0.1.5
   Compiling typenum v1.15.0
   Compiling cpal v0.13.5
    Checking tinyvec_macros v0.1.0
    Checking itoa v1.0.2
    Checking ryu v1.0.10
    Checking xi-unicode v0.3.0
    Checking vec_map v0.8.2
    Checking percent-encoding v2.1.0
   Compiling winit v0.26.1
    Checking base64 v0.13.0
    Checking rectangle-pack v0.4.2
    Checking fnv v1.0.7
    Checking instant v0.1.12
    Checking libloading v0.7.3
    Checking gpu-alloc-types v0.2.0
    Checking gpu-descriptor-types v0.1.1
    Checking wgpu-types v0.12.0
    Checking tracing-core v0.1.27
    Checking thread_local v1.1.4
    Checking fxhash v0.2.1
    Checking ogg v0.8.0
    Checking hash32 v0.2.1
   Compiling ahash v0.7.6
   Compiling num-traits v0.2.15
   Compiling lock_api v0.4.7
   Compiling indexmap v1.9.1
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.3
   Compiling num-rational v0.4.0
   Compiling num-iter v0.1.43
   Compiling memoffset v0.6.5
    Checking concurrent-queue v1.2.2
    Checking sharded-slab v0.1.4
    Checking raw-window-handle v0.4.3
    Checking walkdir v2.3.2
    Checking pp-rs v0.2.1
   Compiling wgpu-core v0.12.2
    Checking codespan-reporting v0.11.1
    Checking bit-set v0.5.2
    Checking miniz_oxide v0.5.3
    Checking deflate v1.0.0
   Compiling alsa-sys v0.3.1
   Compiling libudev-sys v0.1.4
   Compiling x11-dl v2.19.1
    Checking tinyvec v1.6.0
    Checking gpu-alloc v0.5.3
    Checking tracing v0.1.35
    Checking regex-automata v0.1.10
    Checking owned_ttf_parser v0.15.0
    Checking tracing-log v0.1.3
    Checking async-channel v1.6.1
    Checking futures-lite v1.12.0
    Checking aho-corasick v0.7.18
    Checking lewton v0.10.2
    Checking ab_glyph v0.2.15
    Checking matchers v0.1.0
    Checking crossbeam-channel v0.5.5
    Checking png v0.17.5
    Checking regex v1.5.6
    Checking async-executor v1.4.1
    Checking getrandom v0.2.7
    Checking num_cpus v1.13.1
    Checking inotify-sys v0.1.5
    Checking filetime v0.2.16
    Checking mio v0.7.14
    Checking nix v0.23.1
    Checking nix v0.24.1
    Checking mio v0.8.4
    Checking inotify v0.9.6
    Checking bevy_tasks v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking rand_core v0.6.3
    Checking spirv v0.2.0+1.5.4
    Checking approx v0.5.1
    Checking euclid v0.22.7
    Checking notify v5.0.0-pre.11
    Checking rand_chacha v0.3.1
    Checking glyph_brush_layout v0.2.3
    Checking hashbrown v0.11.2
    Checking rand v0.8.5
    Checking guillotiere v0.6.2
    Checking gpu-descriptor v0.2.2
    Checking alsa v0.6.0
   Compiling encase_derive_impl v0.2.1
   Compiling thiserror-impl v1.0.31
   Compiling bytemuck_derive v1.1.0
   Compiling encase_derive v0.2.1
   Compiling gltf-derive v1.0.0
   Compiling hash32-derive v0.1.1
    Checking taffy v0.1.0
    Checking bytemuck v1.9.1
    Checking image v0.24.2
    Checking thiserror v1.0.31
    Checking smallvec v1.8.0
    Checking hashbrown v0.12.1
    Checking glam v0.20.5
    Checking uuid v1.1.2
    Checking ron v0.7.1
    Checking tracing-subscriber v0.3.11
    Checking gilrs-core v0.4.1
   Compiling toml v0.5.9
    Checking parking_lot v0.11.2
    Checking bevy_utils v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking gilrs v0.9.0
    Checking gltf-json v1.0.0
    Checking petgraph v0.6.2
    Checking rodio v0.15.0
   Compiling bevy_macro_utils v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
   Compiling bevy_reflect_derive v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
   Compiling bevy_ecs_macros v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
   Compiling bevy_derive v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
   Compiling bevy_render_macros v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
   Compiling bevy_encase_derive v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_math v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking hexasphere v7.1.0
    Checking encase v0.2.1
    Checking bevy_mikktspace v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking naga v0.8.5
    Checking gltf v1.0.0
    Checking bevy_reflect v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_ecs v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking wgpu-hal v0.12.5
    Checking bevy_app v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_log v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_time v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_hierarchy v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_input v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_core v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_diagnostic v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_transform v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_window v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_gilrs v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_asset v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_winit v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_scene v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_animation v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_audio v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking wgpu v0.12.0
    Checking bevy_render v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_core_pipeline v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_sprite v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_pbr v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_gltf v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_text v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_ui v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
    Checking bevy_internal v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
 Documenting bevy v0.8.0-dev (https://github.com/bevyengine/bevy?rev=fed93a0edce9d66586dc70c1207a2092694b9a7d#3d68094f)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Item { id: Id("26:3173"), crate_id: 26, name: Some("TypeRegistry"), span: Some(Span { filename: "/home/makspll/.cargo/git/checkouts/bevy-f66245b8e5deb629/3d68094/crates/bevy_reflect/src/type_registry.rs", begin: (21, 0), end: (23, 1) }), visibility: Public, docs: Some("A synchronized wrapper around a [`TypeRegistry`]."), links: {"`TypeRegistry`": Id("26:1145")}, attrs: [], deprecation: None, inner: Struct(Struct { struct_type: Plain, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [Id("26:3174")], impls: [] }) }`,
 right: `Item { id: Id("26:3173"), crate_id: 26, name: Some("TypeRegistryArc"), span: Some(Span { filename: "/home/makspll/.cargo/git/checkouts/bevy-f66245b8e5deb629/3d68094/crates/bevy_reflect/src/type_registry.rs", begin: (21, 0), end: (23, 1) }), visibility: Public, docs: Some("A synchronized wrapper around a [`TypeRegistry`]."), links: {"`TypeRegistry`": Id("26:1145")}, attrs: [], deprecation: None, inner: Struct(Struct { struct_type: Plain, generics: Generics { params: [], where_predicates: [] }, fields_stripped: false, fields: [Id("26:3174")], impls: [] }) }`', src/librustdoc/json/mod.rs:196:17
stack backtrace:
   0:     0x7fdfb706df4d - std::backtrace_rs::backtrace::libunwind::trace::h2a0687f70fa2932f
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fdfb706df4d - std::backtrace_rs::backtrace::trace_unsynchronized::hd9fe6fafb6949f1d
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdfb706df4d - std::sys_common::backtrace::_print_fmt::h1cb3661b4f93f527
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fdfb706df4d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h15d5b6f252669e68
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fdfb70c9aac - core::fmt::write::hfcda85493823842c
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fdfb705f6e1 - std::io::Write::write_fmt::h818d19a3163a9cb4
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/io/mod.rs:1654:15
   6:     0x7fdfb7070c35 - std::sys_common::backtrace::_print::h5d648ffba569db29
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fdfb7070c35 - std::sys_common::backtrace::print::h074e8185938ef288
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fdfb7070c35 - std::panicking::default_hook::{{closure}}::hc6c114b96e5a6a24
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/panicking.rs:295:22
   9:     0x7fdfb7070956 - std::panicking::default_hook::h8e3922ce7d759043
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/panicking.rs:314:9
  10:     0x7fdfb78395e1 - rustc_driver[27b059e750e1235c]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fdfb707130a - std::panicking::rust_panic_with_hook::h049e875c51e8c8d6
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/panicking.rs:702:17
  12:     0x7fdfb7071147 - std::panicking::begin_panic_handler::{{closure}}::h41581800f94edb3f
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/panicking.rs:588:13
  13:     0x7fdfb706e404 - std::sys_common::backtrace::__rust_end_short_backtrace::h3a787e02af7cad6d
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fdfb7070e79 - rust_begin_unwind
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/panicking.rs:584:5
  15:     0x7fdfb7036143 - core::panicking::panic_fmt::h17cbed6fcc59adb0
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/core/src/panicking.rs:142:14
  16:     0x7fdfb70c6858 - core::panicking::assert_failed_inner::h03945a00c982e362
  17:     0x56185fac66e4 - core[853f2de9cc51ff86]::panicking::assert_failed::<rustdoc_json_types[982ba5aa26e8deeb]::Item, rustdoc_json_types[982ba5aa26e8deeb]::Item>
  18:     0x56185fdd7487 - <rustdoc[d0704cae0f0349fe]::json::JsonRenderer as rustdoc[d0704cae0f0349fe]::formats::renderer::FormatRenderer>::item
  19:     0x56185fdd3039 - <rustdoc[d0704cae0f0349fe]::json::JsonRenderer as rustdoc[d0704cae0f0349fe]::formats::renderer::FormatRenderer>::item
  20:     0x56185fdd3039 - <rustdoc[d0704cae0f0349fe]::json::JsonRenderer as rustdoc[d0704cae0f0349fe]::formats::renderer::FormatRenderer>::item
  21:     0x56185fd0ed30 - rustdoc[d0704cae0f0349fe]::formats::renderer::run_format::<rustdoc[d0704cae0f0349fe]::json::JsonRenderer>
  22:     0x56185fb0ff62 - rustdoc[d0704cae0f0349fe]::run_renderer::<rustdoc[d0704cae0f0349fe]::json::JsonRenderer>
  23:     0x56185fd86fab - <rustc_session[7e53a420bcc2a0c1]::session::Session>::time::<core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>, rustdoc[d0704cae0f0349fe]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#2}>
  24:     0x56185fd197ef - <rustc_interface[5a86673b74eda5f7]::passes::QueryContext>::enter::<rustdoc[d0704cae0f0349fe]::main_options::{closure#0}::{closure#0}::{closure#1}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>
  25:     0x56185fc5df2f - <rustc_interface[5a86673b74eda5f7]::interface::Compiler>::enter::<rustdoc[d0704cae0f0349fe]::main_options::{closure#0}::{closure#0}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>
  26:     0x56185facd81a - rustc_span[656058cb53b69289]::with_source_map::<core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>, rustc_interface[5a86673b74eda5f7]::interface::create_compiler_and_run<core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>, rustdoc[d0704cae0f0349fe]::main_options::{closure#0}>::{closure#1}>
  27:     0x56185fc605b4 - rustc_interface[5a86673b74eda5f7]::interface::create_compiler_and_run::<core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>, rustdoc[d0704cae0f0349fe]::main_options::{closure#0}>
  28:     0x56185facfc15 - <scoped_tls[da5cf5393aafad40]::ScopedKey<rustc_span[656058cb53b69289]::SessionGlobals>>::set::<rustdoc[d0704cae0f0349fe]::main_args::{closure#0}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>
  29:     0x56185fc872cf - std[4a1d38e153457124]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[5a86673b74eda5f7]::util::run_in_thread_pool_with_globals<rustdoc[d0704cae0f0349fe]::main_args::{closure#0}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>::{closure#0}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>
  30:     0x56185fd344c9 - <<std[4a1d38e153457124]::thread::Builder>::spawn_unchecked_<rustc_interface[5a86673b74eda5f7]::util::run_in_thread_pool_with_globals<rustdoc[d0704cae0f0349fe]::main_args::{closure#0}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>::{closure#0}, core[853f2de9cc51ff86]::result::Result<(), rustc_errors[55fd38744d4a6b4a]::ErrorGuaranteed>>::{closure#1} as core[853f2de9cc51ff86]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x7fdfb707b223 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h437cc910991f4ea1
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/alloc/src/boxed.rs:1872:9
  32:     0x7fdfb707b223 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd6903e0b6d3402ac
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/alloc/src/boxed.rs:1872:9
  33:     0x7fdfb707b223 - std::sys::unix::thread::Thread::new::thread_start::h828b0c885880b055
                               at /rustc/4cbaac699c14b7ac7cc80e54823b2ef6afeb64af/library/std/src/sys/unix/thread.rs:108:17
  34:     0x7fdfb6f88609 - start_thread
                               at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  35:     0x7fdfb6d31163 - clone
  36:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (4cbaac699 2022-05-25) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `bevy`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name bevy /home/makspll/.cargo/git/checkouts/bevy-f66245b8e5deb629/3d68094/src/lib.rs --cap-lints allow -o /home/makspll/Git/bevy_scripting/target/doc --cfg 'feature="animation"' --cfg 'feature="bevy_audio"' --cfg 'feature="bevy_gilrs"' --cfg 'feature="bevy_winit"' --cfg 'feature="default"' --cfg 'feature="filesystem_watcher"' --cfg 'feature="hdr"' --cfg 'feature="png"' --cfg 'feature="render"' --cfg 'feature="vorbis"' --cfg 'feature="x11"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --output-format json -Zunstable-options -C metadata=e99b56ec49be3759 -L dependency=/home/makspll/Git/bevy_scripting/target/debug/deps --extern bevy_internal=/home/makspll/Git/bevy_scripting/target/debug/deps/libbevy_internal-c68f69146dff856f.rmeta --crate-version 0.8.0-dev` (exit status: 101)```

</p>
</details>

**Comment by matthiaskrgr** [comment]
Might be already fixed, your nightly is already a month old, could you try with a recent one?

**Comment by makspll** [comment]
Ah... didn't realise cargo doesn't update nightly by itself, yes the issue is fixed by running `rustup update` following a `rustup default nightly`,

which results in `rustc --version --verbose` output of :
```
rustc 1.63.0-nightly (dc80ca78b 2022-06-21)
binary: rustc
commit-hash: dc80ca78b6ec2b6bba02560470347433bcd0bb3c
commit-date: 2022-06-21
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```
