### ISSUE TITLE
Cross running tests fails due to missing C compiler

### ISSUE THREAD

**Issue by JakobDegen** [rust-lang/rust#98837]
Beginning with #97513 (cc @jyn514 ) , `RUST_BACKTRACE=1 x test src/test/mir-opt/ --target i686-unknown-linux-gnu` fails on my system, printing:

```
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.03s
thread 'main' panicked at '

couldn't find required command: "i686-linux-gnu-gcc"

', sanity.rs:59:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:142:14
   2: bootstrap::sanity::Finder::must_have::{{closure}}
             at ./src/bootstrap/sanity.rs:59:13
   3: core::option::Option<T>::unwrap_or_else
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/option.rs:805:21
   4: bootstrap::sanity::Finder::must_have
             at ./src/bootstrap/sanity.rs:58:9
   5: bootstrap::sanity::check
             at ./src/bootstrap/sanity.rs:159:13
   6: bootstrap::Build::new
             at ./src/bootstrap/lib.rs:522:13
   7: bootstrap::main
             at ./src/bootstrap/bin/main.rs:34:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:00
```

I'm not sure if this is intentional - the PR mentions that there is a vendoring change, so that might be related. It would be nice if this worked though.

**Comment by JakobDegen** [comment]
Wait, hold on, I just started reading this right. Why does it think that `i686-linux-gnu-gcc` is the name of a C compiler? That's not typical, is it?

**Comment by JakobDegen** [comment]
Investigated a little bit more. The cause of this issue is the version bump of `cc`. Setting `CC=clang` fixes the issue. I think this might be a bug on their end, but at least going to close this for now.
