### ISSUE TITLE
coverage: internal compiler error: regression on 20220702

### ISSUE THREAD

**Issue by catenacyber** [rust-lang/rust#98928]
### Code

This comes from Suricata coverage build on oss-fuzz :
https://oss-fuzz-build-logs.storage.googleapis.com/log-adfe2312-62e1-4c25-a25b-221bfb9ed3e0.txt

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (f2d93935f 2022-07-02) running on x86_64-unknown-linux-gnu
```

Was working with `rustc 1.64.0-nightly (46b8c23f3 2022-07-01)`
cf https://oss-fuzz-build-logs.storage.googleapis.com/index.html#suricata

### Error output

```
thread 'rustc' panicked at 'No counters provided the source_hash for used function: Instance { def: Item(WithOptConstParam { did: DefId(0:372 ~ minimal_lexical[4920]::stackvec::{impl#0}::capacity), const_param_did: None }), substs: [] }', compiler/rustc_codegen_ssa/src/coverageinfo/map.rs:156:9
stack backtrace:
   0:     0x7f48892feb40 - std::backtrace_rs::backtrace::libunwind::trace::h09823a8a3f4381ba
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f48892feb40 - std::backtrace_rs::backtrace::trace_unsynchronized::hbad91abf8c22d3bf
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f48892feb40 - std::sys_common::backtrace::_print_fmt::hc0fd0228c4b1ead3
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f48892feb40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h95a8ecc9fef0948b
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f48893577fc - core::fmt::write::heec2f4913ef79a6e
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f48892f01e5 - std::io::Write::write_fmt::h45314f98171aa8e3
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/io/mod.rs:1672:15
   6:     0x7f4889301731 - std::sys_common::backtrace::_print::h80a5d90ac837feab
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f4889301731 - std::sys_common::backtrace::print::h21c1c45c2d623e82
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f4889301731 - std::panicking::default_hook::{{closure}}::hdfeb0bb137e505c2
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:295:22
   9:     0x7f4889301403 - std::panicking::default_hook::h13ef6a9733a856f1
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:314:9
warning: `lazy_static` (lib) generated 1 warning (1 duplicate)
warning: `ryu` (lib) generated 1 warning (1 duplicate)
  10:     0x7f4889b21a84 - rustc_driver[354a5cb6145401a7]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f4889301f06 - std::panicking::rust_panic_with_hook::h30e3daa47b045e2d
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:702:17
  12:     0x7f4889301d57 - std::panicking::begin_panic_handler::{{closure}}::hca7da56c186e518b
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:588:13
  13:     0x7f48892ff014 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc31e8adf432d85e
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f4889301a82 - rust_begin_unwind
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:584:5
  15:     0x7f48892c6903 - core::panicking::panic_fmt::h9ab995c8ad914497
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/core/src/panicking.rs:142:14
  16:     0x7f488a6260cd - <rustc_codegen_ssa[acdb6cbff146a10]::coverageinfo::map::FunctionCoverage>::get_expressions_and_counter_regions
  17:     0x7f4889c4575e - rustc_codegen_llvm[db3973524393ca27]::coverageinfo::mapgen::finalize
  18:     0x7f488aead065 - rustc_codegen_llvm[db3973524393ca27]::base::compile_codegen_unit::module_codegen
  19:     0x7f488bcdcf86 - <rustc_query_system[5d37622d8cc274f7]::dep_graph::graph::DepGraph<rustc_middle[49138853b326ad21]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[49138853b326ad21]::ty::context::TyCtxt, rustc_span[b3572a7c9e19711]::symbol::Symbol, rustc_codegen_ssa[acdb6cbff146a10]::ModuleCodegen<rustc_codegen_llvm[db3973524393ca27]::ModuleLlvm>>
  20:     0x7f488bd0e1f9 - rustc_codegen_llvm[db3973524393ca27]::base::compile_codegen_unit
  21:     0x7f488bce3364 - rustc_codegen_ssa[acdb6cbff146a10]::base::codegen_crate::<rustc_codegen_llvm[db3973524393ca27]::LlvmCodegenBackend>
  22:     0x7f488bd3a84a - <rustc_codegen_llvm[db3973524393ca27]::LlvmCodegenBackend as rustc_codegen_ssa[acdb6cbff146a10]::traits::backend::CodegenBackend>::codegen_crate
  23:     0x7f488bca2837 - <rustc_session[89d4e73bb7d7e5d1]::session::Session>::time::<alloc[356c70a69fe8693f]::boxed::Box<dyn core[4ed53b4c6b14b6f1]::any::Any>, rustc_interface[94544147d39f291c]::passes::start_codegen::{closure#0}>
  24:     0x7f488bc96090 - <rustc_interface[94544147d39f291c]::passes::QueryContext>::enter::<<rustc_interface[94544147d39f291c]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<alloc[356c70a69fe8693f]::boxed::Box<dyn core[4ed53b4c6b14b6f1]::any::Any>, rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  25:     0x7f488bc9fcd3 - <rustc_interface[94544147d39f291c]::queries::Queries>::ongoing_codegen
  26:     0x7f488bc618b3 - <rustc_interface[94544147d39f291c]::interface::Compiler>::enter::<rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}::{closure#2}, core[4ed53b4c6b14b6f1]::result::Result<core[4ed53b4c6b14b6f1]::option::Option<rustc_interface[94544147d39f291c]::queries::Linker>, rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  27:     0x7f488bc5dd7f - rustc_span[b3572a7c9e19711]::with_source_map::<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_interface[94544147d39f291c]::interface::create_compiler_and_run<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#1}>
  28:     0x7f488bc78492 - rustc_interface[94544147d39f291c]::interface::create_compiler_and_run::<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>
  29:     0x7f488bc8a602 - <scoped_tls[e525fc613ec4a334]::ScopedKey<rustc_span[b3572a7c9e19711]::SessionGlobals>>::set::<rustc_interface[94544147d39f291c]::interface::run_compiler<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  30:     0x7f488bc602bf - std[9db71c232178d7a3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[94544147d39f291c]::util::run_in_thread_pool_with_globals<rustc_interface[94544147d39f291c]::interface::run_compiler<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  31:     0x7f488bc7bec9 - <<std[9db71c232178d7a3]::thread::Builder>::spawn_unchecked_<rustc_interface[94544147d39f291c]::util::run_in_thread_pool_with_globals<rustc_interface[94544147d39f291c]::interface::run_compiler<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>::{closure#1} as core[4ed53b4c6b14b6f1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7f488930b863 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h683028ced5e23810
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/alloc/src/boxed.rs:1934:9
  33:     0x7f488930b863 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h783a8fbbc6c47414
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/alloc/src/boxed.rs:1934:9
  34:     0x7f488930b863 - std::sys::unix::thread::Thread::new::thread_start::he5f5391e77e5e84e
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7f488922b609 - start_thread
  36:     0x7f488914e133 - clone
  37:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (27eb6d701 2022-07-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C debuginfo=1 -C force-frame-pointers -Z instrument-coverage -C link-arg=-lc++

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7f48892feb40 - std::backtrace_rs::backtrace::libunwind::trace::h09823a8a3f4381ba
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f48892feb40 - std::backtrace_rs::backtrace::trace_unsynchronized::hbad91abf8c22d3bf
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f48892feb40 - std::sys_common::backtrace::_print_fmt::hc0fd0228c4b1ead3
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f48892feb40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h95a8ecc9fef0948b
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f48893577fc - core::fmt::write::heec2f4913ef79a6e
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f48892f01e5 - std::io::Write::write_fmt::h45314f98171aa8e3
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/io/mod.rs:1672:15
   6:     0x7f4889301731 - std::sys_common::backtrace::_print::h80a5d90ac837feab
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f4889301731 - std::sys_common::backtrace::print::h21c1c45c2d623e82
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f4889301731 - std::panicking::default_hook::{{closure}}::hdfeb0bb137e505c2
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:295:22
   9:     0x7f4889301403 - std::panicking::default_hook::h13ef6a9733a856f1
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:314:9
  10:     0x7f4889b21a84 - rustc_driver[354a5cb6145401a7]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f4889301f06 - std::panicking::rust_panic_with_hook::h30e3daa47b045e2d
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:702:17
  12:     0x7f4889301d57 - std::panicking::begin_panic_handler::{{closure}}::hca7da56c186e518b
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:588:13
  13:     0x7f48892ff014 - std::sys_common::backtrace::__rust_end_short_backtrace::hfc31e8adf432d85e
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f4889301a82 - rust_begin_unwind
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/panicking.rs:584:5
  15:     0x7f48892c6903 - core::panicking::panic_fmt::h9ab995c8ad914497
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/core/src/panicking.rs:142:14
  16:     0x7f488a6260cd - <rustc_codegen_ssa[acdb6cbff146a10]::coverageinfo::map::FunctionCoverage>::get_expressions_and_counter_regions
  17:     0x7f4889c4575e - rustc_codegen_llvm[db3973524393ca27]::coverageinfo::mapgen::finalize
  18:     0x7f488aead065 - rustc_codegen_llvm[db3973524393ca27]::base::compile_codegen_unit::module_codegen
  19:     0x7f488bcdcf86 - <rustc_query_system[5d37622d8cc274f7]::dep_graph::graph::DepGraph<rustc_middle[49138853b326ad21]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[49138853b326ad21]::ty::context::TyCtxt, rustc_span[b3572a7c9e19711]::symbol::Symbol, rustc_codegen_ssa[acdb6cbff146a10]::ModuleCodegen<rustc_codegen_llvm[db3973524393ca27]::ModuleLlvm>>
  20:     0x7f488bd0e1f9 - rustc_codegen_llvm[db3973524393ca27]::base::compile_codegen_unit
  21:     0x7f488bce3364 - rustc_codegen_ssa[acdb6cbff146a10]::base::codegen_crate::<rustc_codegen_llvm[db3973524393ca27]::LlvmCodegenBackend>
  22:     0x7f488bd3a84a - <rustc_codegen_llvm[db3973524393ca27]::LlvmCodegenBackend as rustc_codegen_ssa[acdb6cbff146a10]::traits::backend::CodegenBackend>::codegen_crate
  23:     0x7f488bca2837 - <rustc_session[89d4e73bb7d7e5d1]::session::Session>::time::<alloc[356c70a69fe8693f]::boxed::Box<dyn core[4ed53b4c6b14b6f1]::any::Any>, rustc_interface[94544147d39f291c]::passes::start_codegen::{closure#0}>
  24:     0x7f488bc96090 - <rustc_interface[94544147d39f291c]::passes::QueryContext>::enter::<<rustc_interface[94544147d39f291c]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<alloc[356c70a69fe8693f]::boxed::Box<dyn core[4ed53b4c6b14b6f1]::any::Any>, rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  25:     0x7f488bc9fcd3 - <rustc_interface[94544147d39f291c]::queries::Queries>::ongoing_codegen
  26:     0x7f488bc618b3 - <rustc_interface[94544147d39f291c]::interface::Compiler>::enter::<rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}::{closure#2}, core[4ed53b4c6b14b6f1]::result::Result<core[4ed53b4c6b14b6f1]::option::Option<rustc_interface[94544147d39f291c]::queries::Linker>, rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  27:     0x7f488bc5dd7f - rustc_span[b3572a7c9e19711]::with_source_map::<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_interface[94544147d39f291c]::interface::create_compiler_and_run<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#1}>
  28:     0x7f488bc78492 - rustc_interface[94544147d39f291c]::interface::create_compiler_and_run::<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>
  29:     0x7f488bc8a602 - <scoped_tls[e525fc613ec4a334]::ScopedKey<rustc_span[b3572a7c9e19711]::SessionGlobals>>::set::<rustc_interface[94544147d39f291c]::interface::run_compiler<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  30:     0x7f488bc602bf - std[9db71c232178d7a3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[94544147d39f291c]::util::run_in_thread_pool_with_globals<rustc_interface[94544147d39f291c]::interface::run_compiler<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>
  31:     0x7f488bc7bec9 - <<std[9db71c232178d7a3]::thread::Builder>::spawn_unchecked_<rustc_interface[94544147d39f291c]::util::run_in_thread_pool_with_globals<rustc_interface[94544147d39f291c]::interface::run_compiler<core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>, rustc_driver[354a5cb6145401a7]::run_compiler::{closure#1}>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>::{closure#0}, core[4ed53b4c6b14b6f1]::result::Result<(), rustc_errors[a4fdbb72a3ceead6]::ErrorGuaranteed>>::{closure#1} as core[4ed53b4c6b14b6f1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7f488930b863 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h683028ced5e23810
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/alloc/src/boxed.rs:1934:9
  33:     0x7f488930b863 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h783a8fbbc6c47414
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/alloc/src/boxed.rs:1934:9
  34:     0x7f488930b863 - std::sys::unix::thread::Thread::new::thread_start::he5f5391e77e5e84e
                               at /rustc/27eb6d7018e397cf98d51c205e3576951d766323/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7f488922b609 - start_thread
  36:     0x7f488914e133 - clone
  37:                0x0 - <unknown>
```

</p>
</details>

Can this be solved by fixing the warning: `-Z instrument-coverage` is deprecated; use `-C instrument-coverage` ?

**Comment by wesleywiser** [comment]
This looks like a duplicate of #98833
