### ISSUE TITLE
GAT + Generic Const Exprs causes "unexpected bound ty in binder: BoundTy"

### ISSUE THREAD

**Issue by dziggas** [rust-lang/rust#99029]
Hello!
I realize this is the bleeding edge, but I ran into the following compiler bug. If this has already been reported, please link and close - I couldn't quite figure out how to classify this one, so my searching could have been ineffective.

Minimal verifiable example can be found here:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f3b20235fecb30defc4ae3b99b5abbdb

### Code

```Rust
#![feature(generic_const_exprs)]
#![feature(generic_associated_types)]
use std::marker::PhantomData;

trait Foo {
    const N: usize;
    type Bar;

    fn foo() -> [usize; Self::N];
}

trait Owner {
    type LendingFooIter<'a, F: Foo>: Iterator<Item = F::Bar>
    where
        [(); F::N]:;
}

struct OwnerImpl {}

impl Owner for OwnerImpl {
    type LendingFooIter<'a, F: Foo> = LendingFooIterImpl<'a, F>
    where
        [(); F::N]:;
}

struct LendingFooIterImpl<'a, F: Foo> {
    _owner: &'a OwnerImpl,
    _phantom: PhantomData<F>,
}

impl<'a, F: Foo> Iterator for LendingFooIterImpl<'a, F>
where
    [(); F::N]:,
{
    type Item = F::Bar;

    fn next(&mut self) -> Option<Self::Item> {
        // * This line requires the `[(); F::N]:` bounds added throughout the above.
        // * Adding those bounds causes the compiler crash.
        // * Removing this line and the requisite, above bounds, results in successful compile
        let _x = F::foo();
        None
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (7b46aa594 2022-07-05)
binary: rustc
commit-hash: 7b46aa594c4bdc507fbd904b6777ca30c37a9209
commit-date: 2022-07-05
host: x86_64-apple-darwin
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
error: internal compiler error: /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/compiler/rustc_middle/src/ty/fold.rs:492:29: unexpected bound ty in binder: BoundTy { var: 1, kind: Param("F") }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/compiler/rustc_errors/src/lib.rs:1391:9
stack backtrace:
   0:     0x7fe295ab9b70 - std::backtrace_rs::backtrace::libunwind::trace::h2668e53b48b23687
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fe295ab9b70 - std::backtrace_rs::backtrace::trace_unsynchronized::hf670805fe228611e
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe295ab9b70 - std::sys_common::backtrace::_print_fmt::h66785df836c49518
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fe295ab9b70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hac1392d77898738d
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fe295b1282c - core::fmt::write::h542b7cbb8e73ee9d
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/core/src/fmt/mod.rs:1198:17
   5:     0x7fe295aab415 - std::io::Write::write_fmt::hedb01b7d82e32f23
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/io/mod.rs:1672:15
   6:     0x7fe295abc761 - std::sys_common::backtrace::_print::h033f0673557525a6
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fe295abc761 - std::sys_common::backtrace::print::h59adf1b87415f3be
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fe295abc761 - std::panicking::default_hook::{{closure}}::h44cc4c9880a82dfc
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/panicking.rs:295:22
   9:     0x7fe295abc433 - std::panicking::default_hook::h5dc9e2102ddb921a
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/panicking.rs:314:9
  10:     0x7fe2962dd6f4 - rustc_driver[760efd21cbfea392]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fe295abcf36 - std::panicking::rust_panic_with_hook::hb02fdbd0b01bca74
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/panicking.rs:702:17
  12:     0x7fe2972b9f61 - std[bfd166edaabeec28]::panicking::begin_panic::<rustc_errors[d94b559c0fe93e17]::ExplicitBug>::{closure#0}
  13:     0x7fe2972b7b46 - std[bfd166edaabeec28]::sys_common::backtrace::__rust_end_short_backtrace::<std[bfd166edaabeec28]::panicking::begin_panic<rustc_errors[d94b559c0fe93e17]::ExplicitBug>::{closure#0}, !>
  14:     0x7fe2972e1996 - std[bfd166edaabeec28]::panicking::begin_panic::<rustc_errors[d94b559c0fe93e17]::ExplicitBug>
  15:     0x7fe2972b5e36 - std[bfd166edaabeec28]::panic::panic_any::<rustc_errors[d94b559c0fe93e17]::ExplicitBug>
  16:     0x7fe2972b3815 - <rustc_errors[d94b559c0fe93e17]::HandlerInner>::bug::<&alloc[604edc06ad172c03]::string::String>
  17:     0x7fe2972b3570 - <rustc_errors[d94b559c0fe93e17]::Handler>::bug::<&alloc[604edc06ad172c03]::string::String>
  18:     0x7fe29735b34d - rustc_middle[594c06b5ca181298]::ty::context::tls::with_context_opt::<rustc_middle[594c06b5ca181298]::ty::context::tls::with_opt<rustc_middle[594c06b5ca181298]::util::bug::opt_span_bug_fmt<rustc_span[c79d0fd7fd8da3f7]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7fe297361376 - rustc_middle[594c06b5ca181298]::util::bug::opt_span_bug_fmt::<rustc_span[c79d0fd7fd8da3f7]::span_encoding::Span>
  20:     0x7fe2973612f3 - rustc_middle[594c06b5ca181298]::util::bug::bug_fmt
  21:     0x7fe2971f9ad4 - <rustc_middle[594c06b5ca181298]::ty::context::TyCtxt>::replace_late_bound_regions_uncached::<rustc_middle[594c06b5ca181298]::ty::PredicateKind, <rustc_middle[594c06b5ca181298]::ty::context::TyCtxt>::replace_late_bound_regions<rustc_middle[594c06b5ca181298]::ty::PredicateKind, <rustc_middle[594c06b5ca181298]::ty::context::TyCtxt>::anonymize_late_bound_regions<rustc_middle[594c06b5ca181298]::ty::PredicateKind>::{closure#0}>::{closure#0}>::{closure#0}
  22:     0x7fe2982d9a0e - <rustc_middle[594c06b5ca181298]::ty::fold::BoundVarReplacer as rustc_middle[594c06b5ca181298]::ty::fold::TypeFolder>::fold_ty
  23:     0x7fe298bb87d5 - rustc_middle[594c06b5ca181298]::ty::util::fold_list::<rustc_middle[594c06b5ca181298]::ty::fold::BoundVarReplacer, rustc_middle[594c06b5ca181298]::ty::subst::GenericArg, <&rustc_middle[594c06b5ca181298]::ty::list::List<rustc_middle[594c06b5ca181298]::ty::subst::GenericArg> as rustc_middle[594c06b5ca181298]::ty::fold::TypeFoldable>::try_fold_with<rustc_middle[594c06b5ca181298]::ty::fold::BoundVarReplacer>::{closure#0}>
  24:     0x7fe297189e7e - <rustc_middle[594c06b5ca181298]::ty::ProjectionPredicate as rustc_middle[594c06b5ca181298]::ty::fold::TypeFoldable>::try_fold_with::<rustc_middle[594c06b5ca181298]::ty::fold::BoundVarReplacer>
  25:     0x7fe29718ca40 - <rustc_middle[594c06b5ca181298]::ty::PredicateKind as rustc_middle[594c06b5ca181298]::ty::fold::TypeFoldable>::fold_with::<rustc_middle[594c06b5ca181298]::ty::fold::BoundVarReplacer>
  26:     0x7fe298be90ce - <rustc_middle[594c06b5ca181298]::ty::context::TyCtxt>::anonymize_late_bound_regions::<rustc_middle[594c06b5ca181298]::ty::PredicateKind>
  27:     0x7fe29717b742 - <rustc_middle[594c06b5ca181298]::ty::erase_regions::RegionEraserVisitor as rustc_middle[594c06b5ca181298]::ty::fold::FallibleTypeFolder>::try_fold_binder::<rustc_middle[594c06b5ca181298]::ty::PredicateKind>
  28:     0x7fe298bb7e16 - rustc_middle[594c06b5ca181298]::ty::util::fold_list::<rustc_middle[594c06b5ca181298]::ty::erase_regions::RegionEraserVisitor, rustc_middle[594c06b5ca181298]::ty::Predicate, <&rustc_middle[594c06b5ca181298]::ty::list::List<rustc_middle[594c06b5ca181298]::ty::Predicate> as rustc_middle[594c06b5ca181298]::ty::fold::TypeFoldable>::try_fold_with<rustc_middle[594c06b5ca181298]::ty::erase_regions::RegionEraserVisitor>::{closure#0}>
  29:     0x7fe29718dbc1 - <rustc_middle[594c06b5ca181298]::ty::ParamEnv as rustc_middle[594c06b5ca181298]::ty::fold::TypeFoldable>::fold_with::<rustc_middle[594c06b5ca181298]::ty::erase_regions::RegionEraserVisitor>
  30:     0x7fe2981acec8 - <rustc_middle[594c06b5ca181298]::ty::context::TyCtxt>::erase_regions::<rustc_middle[594c06b5ca181298]::ty::ParamEnv>
  31:     0x7fe298bdc9f2 - <rustc_middle[594c06b5ca181298]::ty::consts::kind::ConstKind>::try_eval_for_typeck
  32:     0x7fe2971e3593 - <rustc_trait_selection[88bb4467b1e8d321]::traits::const_evaluatable::ConstUnifyCtxt>::try_unify
  33:     0x7fe2971e2b5a - rustc_trait_selection[88bb4467b1e8d321]::traits::const_evaluatable::satisfied_from_param_env::{closure#0}
  34:     0x7fe2971e2e73 - rustc_trait_selection[88bb4467b1e8d321]::traits::const_evaluatable::walk_abstract_const::recurse::<()>
  35:     0x7fe2971e2ae5 - rustc_trait_selection[88bb4467b1e8d321]::traits::const_evaluatable::satisfied_from_param_env
  36:     0x7fe298be048a - rustc_trait_selection[88bb4467b1e8d321]::traits::const_evaluatable::is_const_evaluatable
  37:     0x7fe298137c58 - <rustc_trait_selection[88bb4467b1e8d321]::traits::fulfill::FulfillProcessor as rustc_data_structures[cb0269f91e154762]::obligation_forest::ObligationProcessor>::process_obligation
  38:     0x7fe29819546e - <rustc_data_structures[cb0269f91e154762]::obligation_forest::ObligationForest<rustc_trait_selection[88bb4467b1e8d321]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[88bb4467b1e8d321]::traits::fulfill::FulfillProcessor, rustc_data_structures[cb0269f91e154762]::obligation_forest::Outcome<rustc_trait_selection[88bb4467b1e8d321]::traits::fulfill::PendingPredicateObligation, rustc_infer[22ea00aaff92c450]::traits::FulfillmentErrorCode>>
  39:     0x7fe2981307e4 - <rustc_trait_selection[88bb4467b1e8d321]::traits::fulfill::FulfillmentContext as rustc_infer[22ea00aaff92c450]::traits::engine::TraitEngine>::select_all_or_error
  40:     0x7fe297905c53 - <rustc_infer[22ea00aaff92c450]::infer::InferCtxtBuilder>::enter::<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_typeck[bf35706cb4e53049]::check::compare_method::check_type_bounds::{closure#2}>
  41:     0x7fe2986f3cd7 - rustc_typeck[bf35706cb4e53049]::check::compare_method::check_type_bounds
  42:     0x7fe2986f12f5 - rustc_typeck[bf35706cb4e53049]::check::compare_method::compare_ty_impl
  43:     0x7fe2978750b7 - rustc_typeck[bf35706cb4e53049]::check::check::check_item_type
  44:     0x7fe29787deee - rustc_typeck[bf35706cb4e53049]::check::check::check_mod_item_types
  45:     0x7fe297e4233b - rustc_query_system[bc203251ff6cebb1]::query::plumbing::try_execute_query::<rustc_query_impl[56f929962bf75e95]::plumbing::QueryCtxt, rustc_query_system[bc203251ff6cebb1]::query::caches::DefaultCache<rustc_span[c79d0fd7fd8da3f7]::def_id::LocalDefId, ()>>
  46:     0x7fe2989cd933 - rustc_query_system[bc203251ff6cebb1]::query::plumbing::get_query::<rustc_query_impl[56f929962bf75e95]::queries::check_mod_item_types, rustc_query_impl[56f929962bf75e95]::plumbing::QueryCtxt>
  47:     0x7fe29870f71f - <rustc_middle[594c06b5ca181298]::hir::map::Map>::for_each_module::<rustc_typeck[bf35706cb4e53049]::check_crate::{closure#6}::{closure#0}>
  48:     0x7fe29871a03d - rustc_typeck[bf35706cb4e53049]::check_crate
  49:     0x7fe2984572a7 - rustc_interface[958846f4fbf1d977]::passes::analysis
  50:     0x7fe29898f109 - rustc_query_system[bc203251ff6cebb1]::query::plumbing::try_execute_query::<rustc_query_impl[56f929962bf75e95]::plumbing::QueryCtxt, rustc_query_system[bc203251ff6cebb1]::query::caches::DefaultCache<(), core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>>
  51:     0x7fe2989ed21e - rustc_query_system[bc203251ff6cebb1]::query::plumbing::get_query::<rustc_query_impl[56f929962bf75e95]::queries::analysis, rustc_query_impl[56f929962bf75e95]::plumbing::QueryCtxt>
  52:     0x7fe298420f8a - <rustc_interface[958846f4fbf1d977]::interface::Compiler>::enter::<rustc_driver[760efd21cbfea392]::run_compiler::{closure#1}::{closure#2}, core[e88a173f09d36e2e]::result::Result<core[e88a173f09d36e2e]::option::Option<rustc_interface[958846f4fbf1d977]::queries::Linker>, rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>
  53:     0x7fe29841d4af - rustc_span[c79d0fd7fd8da3f7]::with_source_map::<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_interface[958846f4fbf1d977]::interface::create_compiler_and_run<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_driver[760efd21cbfea392]::run_compiler::{closure#1}>::{closure#1}>
  54:     0x7fe298422142 - rustc_interface[958846f4fbf1d977]::interface::create_compiler_and_run::<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_driver[760efd21cbfea392]::run_compiler::{closure#1}>
  55:     0x7fe29844aba2 - <scoped_tls[a58e32c3198b00c7]::ScopedKey<rustc_span[c79d0fd7fd8da3f7]::SessionGlobals>>::set::<rustc_interface[958846f4fbf1d977]::interface::run_compiler<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_driver[760efd21cbfea392]::run_compiler::{closure#1}>::{closure#0}, core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>
  56:     0x7fe29841f9df - std[bfd166edaabeec28]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[958846f4fbf1d977]::util::run_in_thread_pool_with_globals<rustc_interface[958846f4fbf1d977]::interface::run_compiler<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_driver[760efd21cbfea392]::run_compiler::{closure#1}>::{closure#0}, core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>::{closure#0}, core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>
  57:     0x7fe29843bd59 - <<std[bfd166edaabeec28]::thread::Builder>::spawn_unchecked_<rustc_interface[958846f4fbf1d977]::util::run_in_thread_pool_with_globals<rustc_interface[958846f4fbf1d977]::interface::run_compiler<core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>, rustc_driver[760efd21cbfea392]::run_compiler::{closure#1}>::{closure#0}, core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>::{closure#0}, core[e88a173f09d36e2e]::result::Result<(), rustc_errors[d94b559c0fe93e17]::ErrorGuaranteed>>::{closure#1} as core[e88a173f09d36e2e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  58:     0x7fe295ac6893 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c94be927a3df772
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/alloc/src/boxed.rs:1934:9
  59:     0x7fe295ac6893 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h012bf0167f12016b
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/alloc/src/boxed.rs:1934:9
  60:     0x7fe295ac6893 - std::sys::unix::thread::Thread::new::thread_start::h77ee7cb81da21d02
                               at /rustc/7665c3543079ebc3710b676d0fd6951bedfd4b29/library/std/src/sys/unix/thread.rs:108:17
  61:     0x7fe2959e9609 - start_thread
  62:     0x7fe29590c133 - clone
  63:                0x0 - <unknown>
```

</p>
</details>

**Comment by jackh726** [comment]
This is #98702
