### ISSUE TITLE
Internal compiler error `error: could not compile rustdoc`

### ISSUE THREAD

**Issue by obeis** [rust-lang/rust#99120]
After pulling master branch to this commit
```
268be96d6db196d79a1b2b8299a0485496e5a7ab
```
I am not able to build the compiler

### Error
```
thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:632:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/option.rs:1874:5
   5: <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::stable_crate_id_to_crate_num
   6: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
   7: <rustc_query_impl::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle::ty::generics::GenericPredicates>
   8: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::predicates_of, rustc_query_impl::plumbing::QueryCtxt>
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
  10: rustc_ty_utils::ty::param_env
  11: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::DefId, rustc_middle::ty::ParamEnv>
  12: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::param_env, rustc_query_impl::plumbing::QueryCtxt>
  13: rustc_typeck::check::wfcheck::for_id
  14: rustc_typeck::check::wfcheck::check_item_well_formed
  15: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, ()>
  16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, ()>>
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_item_well_formed
  18: <rustc_middle::hir::map::Map>::par_visit_all_item_likes::<rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor>
  19: <rustc_session::session::Session>::track_errors::<rustc_typeck::check_crate::{closure#5}, ()>
  20: rustc_typeck::check_crate
  21: rustc_interface::passes::analysis
  22: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  23: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  24: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  25: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  26: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  27: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  28: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-beta.2 (6c1f14289 2022-06-28) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C symbol-mangling-version=v0 -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -Z unstable-options -C split-debuginfo=off -Z tls-model=initial-exec -C llvm-args=-import-instr-limit=10 -Z binary-dep-depinfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'Illegal read of: 191814', /rustc/6c1f1428998a08864495bb599840a5997ec175f4/compiler/rustc_query_system/src/dep_graph/graph.rs:436:25
stack backtrace:
   0:     0x7f7ab80f81ad - std::backtrace_rs::backtrace::libunwind::trace::hd39436cf2637fe8e
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f7ab80f81ad - std::backtrace_rs::backtrace::trace_unsynchronized::h335fdfe2725ee7a4
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7ab80f81ad - std::sys_common::backtrace::_print_fmt::h5c9fc027b63f8c04
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f7ab80f81ad - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7872720990c73bfd
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f7ab8153f9c - core::fmt::write::h81ffafe73d2c897d
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/fmt/mod.rs:1197:17
   5:     0x7f7ab80e98c1 - std::io::Write::write_fmt::h620cba01b90c63e4
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/io/mod.rs:1672:15
   6:     0x7f7ab80fae75 - std::sys_common::backtrace::_print::h38cfabcde28269ad
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f7ab80fae75 - std::sys_common::backtrace::print::hdc3357495d7f03de
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f7ab80fae75 - std::panicking::default_hook::{{closure}}::hbcbed9087405d990
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:295:22
   9:     0x7f7ab80fab96 - std::panicking::default_hook::hac5a91355be6dfeb
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:314:9
  10:     0x7f7ab88e65d4 - rustc_driver[408cfae4cc3c6df2]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f7a6bdb7339 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha906293347996099
  12:     0x7f7a6bde340b - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::ha3d37b955ee157cf
  13:     0x7f7ab80fb54a - std::panicking::rust_panic_with_hook::hbd93644d507813e8
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:702:17
  14:     0x7f7ab80fb387 - std::panicking::begin_panic_handler::{{closure}}::hdb2a726c9c7bdbb5
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:588:13
  15:     0x7f7ab80f8664 - std::sys_common::backtrace::__rust_end_short_backtrace::h89864bbb035f1e5f
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7f7ab80fb0b9 - rust_begin_unwind
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:584:5
  17:     0x7f7ab80c0283 - core::panicking::panic_fmt::h418f829e9a4aee22
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:142:14
  18:     0x7f7aba53c3e4 - rustc_query_system[911edcd6a8f7477d]::query::plumbing::get_query::<rustc_query_impl[37e52937f351d760]::queries::def_span, rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt>
  19:     0x7f7aba4baf4e - <rustc_query_impl[37e52937f351d760]::Queries as rustc_middle[6f344fff696dbda8]::ty::query::QueryEngine>::def_span
  20:     0x7f7ab91ee806 - <rustc_span[6f70bc57662b2091]::def_id::DefId as rustc_query_impl[37e52937f351d760]::keys::Key>::default_span
  21:     0x7f7ab9394e59 - rustc_query_impl[37e52937f351d760]::make_query::predicates_of
  22:     0x7f7ab929ab99 - <rustc_query_system[911edcd6a8f7477d]::query::plumbing::QueryState<rustc_span[6f70bc57662b2091]::def_id::DefId>>::try_collect_active_jobs::<rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt>
  23:     0x7f7ab928be4c - <rustc_query_impl[37e52937f351d760]::Queries>::try_collect_active_jobs
  24:     0x7f7ab928a91c - <rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt>::try_print_query_stack
  25:     0x7f7ab89647cf - rustc_interface[f15557808a92caff]::interface::try_print_query_stack
  26:     0x7f7ab88e71e0 - rustc_driver[408cfae4cc3c6df2]::report_ice
  27:     0x7f7a6bdb7339 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha906293347996099
  28:     0x7f7a6bde340b - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::ha3d37b955ee157cf
  29:     0x7f7ab80fb54a - std::panicking::rust_panic_with_hook::hbd93644d507813e8
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:702:17
  30:     0x7f7ab80fb387 - std::panicking::begin_panic_handler::{{closure}}::hdb2a726c9c7bdbb5
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:588:13
  31:     0x7f7ab80f8664 - std::sys_common::backtrace::__rust_end_short_backtrace::h89864bbb035f1e5f
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys_common/backtrace.rs:138:18
  32:     0x7f7ab80fb0b9 - rust_begin_unwind
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/panicking.rs:584:5
  33:     0x7f7ab80c0283 - core::panicking::panic_fmt::h418f829e9a4aee22
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:142:14
  34:     0x7f7ab8150c01 - core::panicking::panic_display::h44eb5e78b4a565c3
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:72:5
  35:     0x7f7ab8150bab - core::panicking::panic_str::h38b9596b7b2b24cd
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/panicking.rs:56:5
  36:     0x7f7ab80c00f6 - core::option::expect_failed::h1d83381522dbb338
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/core/src/option.rs:1874:5
  37:     0x7f7aba5cea7a - <rustc_metadata[189bb5dd0a155bb6]::creader::CStore as rustc_session[2b91fda18a608cf5]::cstore::CrateStore>::stable_crate_id_to_crate_num
  38:     0x7f7aba425290 - <rustc_span[6f70bc57662b2091]::span_encoding::Span as rustc_serialize[6da498e8cb2a97f5]::serialize::Decodable<rustc_query_impl[37e52937f351d760]::on_disk_cache::CacheDecoder>>::decode
  39:     0x7f7aba42e921 - <rustc_query_impl[37e52937f351d760]::on_disk_cache::OnDiskCache>::try_load_query_result::<rustc_middle[6f344fff696dbda8]::ty::generics::GenericPredicates>
  40:     0x7f7aba51296d - rustc_query_system[911edcd6a8f7477d]::query::plumbing::get_query::<rustc_query_impl[37e52937f351d760]::queries::predicates_of, rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt>
  41:     0x7f7aba4b886e - <rustc_query_impl[37e52937f351d760]::Queries as rustc_middle[6f344fff696dbda8]::ty::query::QueryEngine>::predicates_of
  42:     0x7f7aba0235af - rustc_ty_utils[230085c7d7cea5fb]::ty::param_env
  43:     0x7f7aba456ecc - <rustc_query_system[911edcd6a8f7477d]::dep_graph::graph::DepGraph<rustc_middle[6f344fff696dbda8]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6f344fff696dbda8]::ty::context::TyCtxt, rustc_span[6f70bc57662b2091]::def_id::DefId, rustc_middle[6f344fff696dbda8]::ty::ParamEnv>
  44:     0x7f7aba541d1c - rustc_query_system[911edcd6a8f7477d]::query::plumbing::get_query::<rustc_query_impl[37e52937f351d760]::queries::param_env, rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt>
  45:     0x7f7ab9fdd64b - rustc_typeck[fa1fad5f624ccc5b]::check::wfcheck::for_id
  46:     0x7f7ab9fe1ecc - rustc_typeck[fa1fad5f624ccc5b]::check::wfcheck::check_item_well_formed
  47:     0x7f7abafa84df - <rustc_query_system[911edcd6a8f7477d]::dep_graph::graph::DepGraph<rustc_middle[6f344fff696dbda8]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6f344fff696dbda8]::ty::context::TyCtxt, rustc_span[6f70bc57662b2091]::def_id::LocalDefId, ()>
  48:     0x7f7aba4e77d3 - rustc_query_system[911edcd6a8f7477d]::query::plumbing::try_execute_query::<rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt, rustc_query_system[911edcd6a8f7477d]::query::caches::DefaultCache<rustc_span[6f70bc57662b2091]::def_id::LocalDefId, ()>>
  49:     0x7f7aba4bbec1 - <rustc_query_impl[37e52937f351d760]::Queries as rustc_middle[6f344fff696dbda8]::ty::query::QueryEngine>::check_item_well_formed
  50:     0x7f7ab9fca217 - <rustc_middle[6f344fff696dbda8]::hir::map::Map>::par_visit_all_item_likes::<rustc_typeck[fa1fad5f624ccc5b]::check::wfcheck::CheckTypeWellFormedVisitor>
  51:     0x7f7abadb0617 - <rustc_session[2b91fda18a608cf5]::session::Session>::track_errors::<rustc_typeck[fa1fad5f624ccc5b]::check_crate::{closure#5}, ()>
  52:     0x7f7abad99e0b - rustc_typeck[fa1fad5f624ccc5b]::check_crate
  53:     0x7f7abab0e567 - rustc_interface[f15557808a92caff]::passes::analysis
  54:     0x7f7abafc1975 - <rustc_query_system[911edcd6a8f7477d]::dep_graph::graph::DepGraph<rustc_middle[6f344fff696dbda8]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6f344fff696dbda8]::ty::context::TyCtxt, (), core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>
  55:     0x7f7abb06aa7d - rustc_query_system[911edcd6a8f7477d]::query::plumbing::try_execute_query::<rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt, rustc_query_system[911edcd6a8f7477d]::query::caches::DefaultCache<(), core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>>
  56:     0x7f7abb0b46ae - rustc_query_system[911edcd6a8f7477d]::query::plumbing::get_query::<rustc_query_impl[37e52937f351d760]::queries::analysis, rustc_query_impl[37e52937f351d760]::plumbing::QueryCtxt>
  57:     0x7f7abaaf2337 - <rustc_interface[f15557808a92caff]::passes::QueryContext>::enter::<rustc_driver[408cfae4cc3c6df2]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>
  58:     0x7f7abaadc61f - <rustc_interface[f15557808a92caff]::interface::Compiler>::enter::<rustc_driver[408cfae4cc3c6df2]::run_compiler::{closure#1}::{closure#2}, core[5a36d070a32d33ff]::result::Result<core[5a36d070a32d33ff]::option::Option<rustc_interface[f15557808a92caff]::queries::Linker>, rustc_errors[10645af10a1be704]::ErrorGuaranteed>>
  59:     0x7f7abaad5b5f - rustc_span[6f70bc57662b2091]::with_source_map::<core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>, rustc_interface[f15557808a92caff]::interface::create_compiler_and_run<core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>, rustc_driver[408cfae4cc3c6df2]::run_compiler::{closure#1}>::{closure#1}>
  60:     0x7f7abaadd4b2 - <scoped_tls[93fdc487700f9e56]::ScopedKey<rustc_span[6f70bc57662b2091]::SessionGlobals>>::set::<rustc_interface[f15557808a92caff]::interface::run_compiler<core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>, rustc_driver[408cfae4cc3c6df2]::run_compiler::{closure#1}>::{closure#0}, core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>
  61:     0x7f7abaaf2a6f - std[bb5070e20908af4f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f15557808a92caff]::util::run_in_thread_pool_with_globals<rustc_interface[f15557808a92caff]::interface::run_compiler<core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>, rustc_driver[408cfae4cc3c6df2]::run_compiler::{closure#1}>::{closure#0}, core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>::{closure#0}, core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>
  62:     0x7f7abaaf2ba9 - <<std[bb5070e20908af4f]::thread::Builder>::spawn_unchecked_<rustc_interface[f15557808a92caff]::util::run_in_thread_pool_with_globals<rustc_interface[f15557808a92caff]::interface::run_compiler<core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>, rustc_driver[408cfae4cc3c6df2]::run_compiler::{closure#1}>::{closure#0}, core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>::{closure#0}, core[5a36d070a32d33ff]::result::Result<(), rustc_errors[10645af10a1be704]::ErrorGuaranteed>>::{closure#1} as core[5a36d070a32d33ff]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  63:     0x7f7ab8105483 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4135e69d869d02da
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/alloc/src/boxed.rs:1951:9
  64:     0x7f7ab8105483 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f19aa106d42e724
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/alloc/src/boxed.rs:1951:9
  65:     0x7f7ab8105483 - std::sys::unix::thread::Thread::new::thread_start::h7e78afdac6a15870
                               at /rustc/6c1f1428998a08864495bb599840a5997ec175f4/library/std/src/sys/unix/thread.rs:108:17
  66:     0x7f7ab801cea7 - start_thread
  67:     0x7f7ab7f4adef - clone
  68:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-beta.2 (6c1f14289 2022-06-28) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C symbol-mangling-version=v0 -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -Z unstable-options -C split-debuginfo=off -Z tls-model=initial-exec -C llvm-args=-import-instr-limit=10 -Z binary-dep-depinfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
rustc exited with signal: 6 (SIGABRT)
error: could not compile `rustdoc`

Caused by:
  process didn't exit successfully: `/home/obei/rust/rust/build/bootstrap/debug/rustc --crate-name rustdoc --edition=2021 src/librustdoc/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=5f3db5373f5015b2 -C extra-filename=-5f3db5373f5015b2 --out-dir /home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C incremental=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/incremental -L dependency=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/release/deps --extern arrayvec=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libarrayvec-5e9627a3109f0d7e.rmeta --extern askama=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libaskama-b6ab6d4a165ed0d5.rmeta --extern atty=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libatty-e260ed71f1109515.rmeta --extern itertools=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-9ed04f91e5952933.rmeta --extern minifier=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libminifier-b8ada31161a3ba4d.rmeta --extern once_cell=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libonce_cell-57bf33c3a4d06911.rmeta --extern pulldown_cmark=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libpulldown_cmark-1b5bd6a8d964ad50.rmeta --extern regex=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libregex-f3adb9eb559e0d31.rmeta --extern rustdoc_json_types=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/librustdoc_json_types-7f53b9f34cdfd0ee.rmeta --extern serde=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libserde-46dc4be6e372ab2f.rmeta --extern serde_json=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libserde_json-fb9e6447e7bded78.rmeta --extern smallvec=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libsmallvec-6897fd200ae33804.rmeta --extern tempfile=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtempfile-b8424989c5739b71.rmeta --extern tracing=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtracing-98f64247bf9d9035.rmeta --extern tracing_subscriber=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtracing_subscriber-27c0244f54ed30ab.rmeta --extern tracing_tree=/home/obei/rust/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libtracing_tree-a821057c22419f8b.rmeta --cfg=bootstrap -Csymbol-mangling-version=v0 -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Zunstable-options -Csplit-debuginfo=off -Ztls-model=initial-exec -Cllvm-args=-import-instr-limit=10 -Z binary-dep-depinfo` (exit status: 254)
Build completed unsuccessfully in 0:00:02
```

**Comment by obeis** [comment]
Fixed by running `./x.py clean`
