### ISSUE TITLE
Panics when I import a submodule

### ISSUE THREAD

**Issue by brpandey** [rust-lang/rust#99167]
### Code

I am writing a radix_trie --> https://github.com/brpandey/radix_trie

After placing a thread on the rust forum -> https://users.rust-lang.org/t/handling-multiple-mutable-borrows-but-to-different-struct-fields/78135

I added some functionality to incorporate view structs. I checked in these changes yesterday.

Today, I am just trying to simply move any functionality that touches NodeView in node.rs into its own separate module view.rs so that Node is not as bloated. 

Here is what I checked in yesterday.
 https://github.com/brpandey/radix_trie/blob/3f375dad2db43ea00f30a26728f35ea2bdef1e09/src/node.rs 

I've moved one struct over to the view.rs file namely NodeView as seen here:

```Rust
<code>


use crate::node::Node;
use std::collections::hash_map::{Keys, Values/*, ValuesMut, IntoValues*/};

/*-----------------------------------------------------------------------------*/
// Auxiliary data structures that provide views into Node mainly used by Iter,
// generated when necessary

pub struct NodeView<'a, K, V> {
    pub(crate) label: Option<&'a [u8]>,
    pub(crate) value: Option<&'a V>,
    pub(crate) edges: Values<'a, u8, Box<Node<K, V>>>,
    pub(crate) keys: Keys<'a, u8, Box<Node<K, V>>>,
}


/*-----------------------------------------------------------------------------*/

impl<'a, K, V> NodeView<'a, K, V> {
    pub(super) fn new(label: Option<&'a [u8]>, value: Option<&'a V>,
               edges: Values<'a, u8, Box<Node<K, V>>>, keys: Keys<'a, u8, Box<Node<K, V>>>) -> Self {
        NodeView {
            label,
            value,
            edges,
            keys,
        }
    }
}


```
The only additional change I make is to add two lines to node.rs to incorprate my changes as well as commenting out the NodeView struct definition in node.rs and node_view() function in node.rs.
When I simply add these two lines -- the compiler bug happens when running cargo build
If I comment on the use crate::node::view::NodeView lines, it doesn't generate the bug

I can also check-in these breaking changes so its easy for you to run cargo build

```Rust
pub mod view;
use crate::node::view::NodeView;  <----offending use declaration...
```

### Meta

`rustc --version --verbose`:
```
<version>
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0

```

### Error output

```
<output>
brpandey@butterfly:~/Workspace/github/radix_trie$ RUST_BACKTRACE=1 cargo build
   Compiling radix_trie v0.1.0 (/home/brpandey/Workspace/github/radix_trie)
warning: unused imports: `Keys`, `Values`
  --> src/node.rs:10:44
   |
10 | use std::collections::{HashMap, hash_map::{Keys, Values, ValuesMut, IntoValues}};
   |                                            ^^^^  ^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
brpandey@butterfly:~/Workspace/github/radix_trie$ RUST_BACKTRACE=1 cargo build
   Compiling radix_trie v0.1.0 (/home/brpandey/Workspace/github/radix_trie)
warning: unused imports: `Keys`, `Values`
 --> src/node.rs:8:44
  |
8 | use std::collections::{HashMap, hash_map::{Keys, Values, ValuesMut, IntoValues}};
  |                                            ^^^^  ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id
   4: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover
   5: rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   8: rustc_query_system::query::plumbing::ensure_must_run
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_match
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  11: rustc_data_structures::sync::par_for_each_in
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_interface::passes::analysis
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::try_execute_query
  17: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  18: rustc_interface::passes::QueryContext::enter
  19: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  20: rustc_span::with_source_map
  21: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
warning: `radix_trie` (lib) generated 1 warning
error: could not compile `radix_trie`; 1 warning emitted
```

</p>
</details>

**Comment by brpandey** [comment]
Just upgraded to 1.62.0

rustc --version --verbose
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.62.0
LLVM version: 14.0.5

and not getting this error.

Will check again before I close this issue

**Comment by brpandey** [comment]
No longer running into compiler bug after upgrade Rust from 1.57 to 1.62.  Closing
