### ISSUE TITLE
Unexpected compiler panic after restart

### ISSUE THREAD

**Issue by mara-schulke** [rust-lang/rust#99238]
While compiling my system was shutdown due to mussing power, after rebooting the compiler kept crashing

I tried this code: confidential, sadly

I expected to see this happen: the compiler shouldnt panic

Instead, this happened: .. the compiler paniced :D

### Meta
`rustc --version --verbose`:

rust:1.62-alpine docker container with volumes to the working dir (inkl. target)

```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-unknown-linux-musl
release: 1.62.0
LLVM version: 14.0.5
```

```
thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/check_unsafety.rs:517:36
stack backtrace:
   0:     0x7fdc2f14cadd - std::backtrace_rs::backtrace::libunwind::trace::h91d5e08ec83aa53b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fdc2f14cadd - std::backtrace_rs::backtrace::trace_unsynchronized::hc1e2a5f8ec1acff3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdc2f14cadd - std::sys_common::backtrace::_print_fmt::h399ef521e9cfa38c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fdc2f14cadd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc9d0bc2361a81055
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fdc2f1a7c2c - core::fmt::write::hd290451e0cade67a
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fdc2f13e1a1 - std::io::Write::write_fmt::h9efe861491665d4b
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x7fdc2f14f7f5 - std::sys_common::backtrace::_print::h88be5589fe3d1a62
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fdc2f14f7f5 - std::sys_common::backtrace::print::hf2e0958149d5f57a
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fdc2f14f7f5 - std::panicking::default_hook::{{closure}}::h30de4c851c56c694
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x7fdc2f14f469 - std::panicking::default_hook::h9732410f9bf1dde1
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x7fdc2ffbf899 - rustc_driver[ac5896a06a60d4cd]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fdc25075ec3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h633ea08d9a6a41fb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1886:9
  12:     0x7fdc25067ead - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h6952368e5b528868
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/proc_macro/src/bridge/client.rs:335:21
  13:     0x7fdc2f14ffc6 - std::panicking::rust_panic_with_hook::h05457703f08d1cb5
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:702:17
  14:     0x7fdc2f14fdc7 - std::panicking::begin_panic_handler::{{closure}}::h63db6fbc665e433e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  15:     0x7fdc2f14cf94 - std::sys_common::backtrace::__rust_end_short_backtrace::h7b5645a9de09611c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  16:     0x7fdc2f14faf9 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  17:     0x7fdc2f114f43 - core::panicking::panic_fmt::h57aeae238836f7da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  18:     0x7fdc332c5a89 - <rustc_data_structures[77a0a44237720466]::steal::Steal<rustc_middle[2be53d6958540b72]::mir::Body>>::borrow
  19:     0x7fdc333d1b16 - rustc_mir_transform[1872f3cbb535a906]::check_unsafety::unsafety_check_result
  20:     0x7fdc333ccdf0 - <rustc_mir_transform[1872f3cbb535a906]::check_unsafety::provide::{closure#0} as core[a2a8060b23357c1d]::ops::function::FnOnce<(rustc_middle[2be53d6958540b72]::ty::context::TyCtxt, rustc_span[a943c0f06769dacb]::def_id::LocalDefId)>>::call_once
  21:     0x7fdc3457d017 - rustc_query_system[e7677a8cd54979bc]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[ae0ac63d7509f95f]::plumbing::QueryCtxt, rustc_span[a943c0f06769dacb]::def_id::LocalDefId, &rustc_middle[2be53d6958540b72]::mir::query::UnsafetyCheckResult>
  22:     0x7fdc344f336e - rustc_query_system[e7677a8cd54979bc]::query::plumbing::try_execute_query::<rustc_query_impl[ae0ac63d7509f95f]::plumbing::QueryCtxt, rustc_query_system[e7677a8cd54979bc]::query::caches::DefaultCache<rustc_span[a943c0f06769dacb]::def_id::LocalDefId, &rustc_middle[2be53d6958540b72]::mir::query::UnsafetyCheckResult>>
  23:     0x7fdc345c4328 - rustc_query_system[e7677a8cd54979bc]::query::plumbing::get_query::<rustc_query_impl[ae0ac63d7509f95f]::queries::unsafety_check_result, rustc_query_impl[ae0ac63d7509f95f]::plumbing::QueryCtxt>
  24:     0x7fdc333d2474 - rustc_mir_transform[1872f3cbb535a906]::check_unsafety::check_unsafety
  25:     0x7fdc300b4b9b - <rustc_session[12daf1dfc20f140b]::session::Session>::time::<(), rustc_interface[f2e422ee24f6f41]::passes::analysis::{closure#3}>
  26:     0x7fdc30094762 - rustc_interface[f2e422ee24f6f41]::passes::analysis
  27:     0x7fdc34389987 - <rustc_query_system[e7677a8cd54979bc]::dep_graph::graph::DepGraph<rustc_middle[2be53d6958540b72]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[2be53d6958540b72]::ty::context::TyCtxt, (), core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>
  28:     0x7fdc34545d84 - rustc_query_system[e7677a8cd54979bc]::query::plumbing::try_execute_query::<rustc_query_impl[ae0ac63d7509f95f]::plumbing::QueryCtxt, rustc_query_system[e7677a8cd54979bc]::query::caches::DefaultCache<(), core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>>
  29:     0x7fdc345dcd97 - rustc_query_system[e7677a8cd54979bc]::query::plumbing::get_query::<rustc_query_impl[ae0ac63d7509f95f]::queries::analysis, rustc_query_impl[ae0ac63d7509f95f]::plumbing::QueryCtxt>
  30:     0x7fdc2ff79c2b - <rustc_interface[f2e422ee24f6f41]::passes::QueryContext>::enter::<rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>
  31:     0x7fdc2ff53d46 - <rustc_interface[f2e422ee24f6f41]::interface::Compiler>::enter::<rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}::{closure#2}, core[a2a8060b23357c1d]::result::Result<core[a2a8060b23357c1d]::option::Option<rustc_interface[f2e422ee24f6f41]::queries::Linker>, rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>
  32:     0x7fdc2ffc9ba3 - rustc_span[a943c0f06769dacb]::with_source_map::<core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>, rustc_interface[f2e422ee24f6f41]::interface::create_compiler_and_run<core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>, rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}>::{closure#1}>
  33:     0x7fdc2ff549e1 - rustc_interface[f2e422ee24f6f41]::interface::create_compiler_and_run::<core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>, rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}>
  34:     0x7fdc2ff722c2 - <scoped_tls[2fc1fc5914a119fe]::ScopedKey<rustc_span[a943c0f06769dacb]::SessionGlobals>>::set::<rustc_interface[f2e422ee24f6f41]::interface::run_compiler<core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>, rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}>::{closure#0}, core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>
  35:     0x7fdc2ffc3aaf - std[1dace96f20543e2f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f2e422ee24f6f41]::util::run_in_thread_pool_with_globals<rustc_interface[f2e422ee24f6f41]::interface::run_compiler<core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>, rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}>::{closure#0}, core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>::{closure#0}, core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>
  36:     0x7fdc2ff7da29 - <<std[1dace96f20543e2f]::thread::Builder>::spawn_unchecked_<rustc_interface[f2e422ee24f6f41]::util::run_in_thread_pool_with_globals<rustc_interface[f2e422ee24f6f41]::interface::run_compiler<core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>, rustc_driver[ac5896a06a60d4cd]::run_compiler::{closure#1}>::{closure#0}, core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>::{closure#0}, core[a2a8060b23357c1d]::result::Result<(), rustc_errors[d01c6adafaed5e66]::ErrorGuaranteed>>::{closure#1} as core[a2a8060b23357c1d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7fdc2f159993 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h988d32f9fb503789
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  38:     0x7fdc2f159993 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6fa779ace735778d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  39:     0x7fdc2f159993 - std::sys::unix::thread::Thread::new::thread_start::h84b5f4d3c9057080
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys/unix/thread.rs:108:17
  40:     0x7fdc385941f5 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0 (a8314ef7d 2022-06-27) running on x86_64-unknown-linux-musl

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-feature=-crt-static

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `http::handler::health::healthcheck`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `<project>`
```

</p>
</details>

**Comment by jieyouxu** [comment]
Triage: hi @mara-schulke sorry for the very late ping, does this still repro on latest stable? I suspect at the time the reboot maybe corrupted incremental cache. Given how long it has been, I'm going to close this as I don't think we can do much without a repro, but please open a new issue if this still happens for you. Thanks for the report!

**Comment by mara-schulke** [comment]
> Triage: hi @mara-schulke sorry for the very late ping, does this still repro on latest stable? I suspect at the time the reboot maybe corrupted incremental cache. Given how long it has been, I'm going to close this as I don't think we can do much without a repro, but please open a new issue if this still happens for you. Thanks for the report!

Hi thank you for getting back, I haven't encountered this error ever since so I assume it was a one off corruption as you said. Thank you!
