### ISSUE TITLE
broken MIR in DefId

### ISSUE THREAD

**Issue by PerfumedLeftist** [rust-lang/rust#99254]
Only other code I can think of is the part that invokes the function "generate_function()" but i dont thin that matters. I'm trying to have async functions in a struct, and trying to use a Pin<> in this way made it break

The purpose of this program is a Discord bot, which I'm trying to associate each Command (struct) with a function (async)
My deps are
```
tokio = { version = "1.19.2", features = ["full"]}
dotenv = "0.15.0"
enumn = "0.1.4"
tokio-tungstenite = {version = "0.17.1", features = ["native-tls"]}
url = "2.1.0"
reqwest = { version = "0.11", features = ["json"] }
futures-util = "0.3.21"
tinyjson = "2"
```

### Code

```Rust
use std::future::Future;
use std::pin::Pin;

type PinDynFut<Out> = Pin<Box<dyn Future<Output = Out> + Send + 'static>>;

struct Guild {
    name: String,
    id: String
}

struct Invoker {
    username: String,
    discriminator: u16,
}

struct Command {
    name: String,
    kind: u8,
    description: String,
    associated_function: Box<dyn Fn(Guild, Invoker, Option<Vec<HashMap<String, String>>>) -> PinDynFut<Vec<String>>>
}

pub struct CommandsBuilder {
    commands: Vec<Command>
}

impl CommandsBuilder {
    fn new() -> CommandsBuilder {
        CommandsBuilder {
            commands: vec![]
        }
    }

    fn add(mut self: Self, name: String, kind: u8, description: String, associated_function: Box<dyn Fn(Guild, Invoker, Option<Vec<HashMap<String, String>>>) -> PinDynFut<Vec<String>>>) -> Self {
        let command = Command {
            name: name,
            kind: kind,
            description: description,
            associated_function: associated_function
        };

        self.commands.push(command);
        self
    }
}

async fn send_dog(guild: Guild, invoker: Invoker, args: Option<Vec<HashMap<String, String>>>) -> Vec<String> {
    vec!["Hello World!".to_string()]
}

pub async fn generate_commands() -> CommandsBuilder {
    // Code
    let commands: CommandsBuilder = CommandsBuilder::new()
                        .add("dog".to_string(), 1, "Sends a picture of a cute dog".to_string(), Box::new(send_dog));
    commands
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.62.0
LLVM version: 14.0.5
```

### Error output

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:98 ~ ferrisbot[ea30]::actions::commands::generate_commands::{closure#0}) (NoSolution): could not prove Binder(TraitPredicate(<std::boxed::Box<fn(actions::commands::Guild, actions::commands::Invoker, std::option::Option<std::vec::Vec<std::collections::HashMap<std::string::String, std::string::String>>>) -> impl futures_util::Future<Output = std::vec::Vec<std::string::String>> {actions::commands::send_dog}> as std::ops::CoerceUnsized<std::boxed::Box<dyn std::ops::Fn(actions::commands::Guild, actions::commands::Invoker, std::option::Option<std::vec::Vec<std::collections::HashMap<std::string::String, std::string::String>>>) -> std::pin::Pin<std::boxed::Box<dyn futures_util::Future<Output = std::vec::Vec<std::string::String>> + std::marker::Send>>>>>, polarity:Positive), [])
  --> src/actions/commands.rs:60:97
   |
60 |                         .add("dog".to_string(), 1, "Sends a picture of a cute dog".to_string(), Box::new(send_dog));
   |                                                                                                 ^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/canonical.rs:149:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:98 ~ ferrisbot[ea30]::actions::commands::generate_commands::{closure#0}) (NoSolution): could not prove Binder(TraitPredicate(<std::boxed::Box<fn(actions::commands::Guild, actions::commands::Invoker, std::option::Option<std::vec::Vec<std::collections::HashMap<std::string::String, std::string::String>>>) -> impl futures_util::Future<Output = std::vec::Vec<std::string::String>> {actions::commands::send_dog}> as std::ops::CoerceUnsized<std::boxed::Box<dyn std::ops::Fn(actions::commands::Guild, actions::commands::Invoker, std::option::Option<std::vec::Vec<std::collections::HashMap<std::string::String, std::string::String>>>) -> std::pin::Pin<std::boxed::Box<dyn futures_util::Future<Output = std::vec::Vec<std::string::String>> + std::marker::Send>>>>>, polarity:Positive), [])
  --> src/actions/commands.rs:60:97
   |
60 |                         .add("dog".to_string(), 1, "Sends a picture of a cute dog".to_string(), Box::new(send_dog));
   |                                                                                                 ^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at compiler/rustc_borrowck/src/type_check/canonical.rs:149:13

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1369:13
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   3: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   4: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   6: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
   7: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
   8: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0 (a8314ef7d 2022-06-27) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic
```

</p>
</details>

**Comment by PerfumedLeftist** [comment]
Tested on nightly, the compiler does not do an ICE, here is the output:
```
error[E0271]: type mismatch resolving `<fn(Guild, Invoker, Option<Vec<HashMap<std::string::String, std::string::String>>>) -> impl futures_util::Future<Output = Vec<std::string::String>> {send_dog} as FnOnce<(Guild, Invoker, Option<Vec<HashMap<std::string::String, std::string::String>>>)>>::Output == Pin<Box<(dyn futures_util::Future<Output = Vec<std::string::String>> + std::marker::Send + 'static)>>`
  --> src/actions/commands.rs:60:97
   |
60 |                         .add("dog".to_string(), 1, "Sends a picture of a cute dog".to_string(), Box::new(send_dog));
   |                                                                                                 ^^^^^^^^^^^^^^^^^^ expected struct `Pin`, found opaque type
   |
note: while checking the return type of the `async fn`
  --> src/actions/commands.rs:51:98
   |
51 | async fn send_dog(guild: Guild, invoker: Invoker, args: Option<Vec<HashMap<String, String>>>) -> Vec<String> {
   |                                                                                                  ^^^^^^^^^^^ checked the `Output` of this `async fn`, found opaque type
   = note:   expected struct `Pin<Box<(dyn futures_util::Future<Output = Vec<std::string::String>> + std::marker::Send + 'static)>>`
           found opaque type `impl futures_util::Future<Output = Vec<std::string::String>>`
   = note: required for the cast from `fn(Guild, Invoker, Option<Vec<HashMap<std::string::String, std::string::String>>>) -> impl futures_util::Future<Output = Vec<std::string::String>> {send_dog}` to the object type `dyn Fn(Guild, Invoker, Option<Vec<HashMap<std::string::String, std::string::String>>>) -> Pin<Box<(dyn futures_util::Future<Output = Vec<std::string::String>> + std::marker::Send + 'static)>>
```

**Comment by compiler-errors** [comment]
Since you said this now errors on nightly (instead of ICEs), I think this can be closed. I believe this error message is correct.
