### ISSUE TITLE
Main thread panicking at assertion after latest nightly update (d68e7ebc3 2022-07-20)

### ISSUE THREAD

**Issue by abhishekdhamale** [rust-lang/rust#99561]
We are checking file timestamps in our project but main thread is panicking at the assertion after latest nightly update. Earlier it was working fine.

Here is full `backtrace` 

```
thread 'main' panicked at 'assertion failed: mtime < atime', rbsigner\src\mcusigner.rs:162:5
stack backtrace:
   0:     0x7ff7ecd25faf - std::sys_common::backtrace::_print_fmt
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\sys_common\backtrace.rs:66
   1:     0x7ff7ecd25faf - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\sys_common\backtrace.rs:45
   2:     0x7ff7ecd373ea - core::fmt::write
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\core\src\fmt\mod.rs:1198
   3:     0x7ff7ecd2426a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\io\mod.rs:1672
   4:     0x7ff7ecd2857b - std::sys_common::backtrace::_print
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\sys_common\backtrace.rs:48
   5:     0x7ff7ecd2857b - std::sys_common::backtrace::print
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\sys_common\backtrace.rs:35
   6:     0x7ff7ecd2857b - std::panicking::default_hook::closure$1
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:295
   7:     0x7ff7ecd281a7 - std::panicking::default_hook
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:314
   8:     0x7ff7ecd28d49 - std::panicking::rust_panic_with_hook
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:698
   9:     0x7ff7ecd28c12 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:586
  10:     0x7ff7ecd269b7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\sys_common\backtrace.rs:138
  11:     0x7ff7ecd28920 - std::panicking::begin_panic_handler
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:584
  12:     0x7ff7ecd3da35 - core::panicking::panic_fmt
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\core\src\panicking.rs:142
  13:     0x7ff7ecd3d8dc - core::panicking::panic
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\core\src\panicking.rs:48
  14:     0x7ff7ecce0209 - rbsigner::mcusigner::construct_img_header<sha2::sha256::Sha256,32>
                               at C:\Users\ELCOME\Desktop\mcusigner-test\rustBoot\rbsigner\src\mcusigner.rs:162
  15:     0x7ff7eccd1455 - rbsigner::mcusigner::sign_mcu_image
                               at C:\Users\ELCOME\Desktop\mcusigner-test\rustBoot\rbsigner\src\mcusigner.rs:71
  16:     0x7ff7eccc5b6a - rbsigner::main
                               at C:\Users\ELCOME\Desktop\mcusigner-test\rustBoot\rbsigner\src\main.rs:99
  17:     0x7ff7eccd8c3b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503\library\core\src\ops\function.rs:248
  18:     0x7ff7eccc444e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503\library\std\src\sys_common\backtrace.rs:122
  19:     0x7ff7eccc3511 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503\library\std\src\rt.rs:145
  20:     0x7ff7ecd1fbc4 - core::ops::function::impls::impl$2::call_once
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\core\src\ops\function.rs:280
  21:     0x7ff7ecd1fbc4 - std::panicking::try::do_call
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:492
  22:     0x7ff7ecd1fbc4 - std::panicking::try
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:456
  23:     0x7ff7ecd1fbc4 - std::panic::catch_unwind
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panic.rs:137
  24:     0x7ff7ecd1fbc4 - std::rt::lang_start_internal::closure$2
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\rt.rs:128
  25:     0x7ff7ecd1fbc4 - std::panicking::try::do_call
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:492
  26:     0x7ff7ecd1fbc4 - std::panicking::try
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panicking.rs:456
  27:     0x7ff7ecd1fbc4 - std::panic::catch_unwind
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\panic.rs:137
  28:     0x7ff7ecd1fbc4 - std::rt::lang_start_internal
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503/library\std\src\rt.rs:128
  29:     0x7ff7eccc34df - std::rt::lang_start<tuple$<> >
                               at /rustc/d68e7ebc38cb42b8b237392b28045edeec761503\library\std\src\rt.rs:144
  30:     0x7ff7eccc64f6 - main
  31:     0x7ff7ecd3c320 - invoke_main
                               at d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  32:     0x7ff7ecd3c320 - __scrt_common_main_seh
                               at d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  33:     0x7ff9ca5d7034 - BaseThreadInitThunk
  34:     0x7ff9cc522651 - RtlUserThreadStart
error: process didn't exit successfully: `C:\Users\ELCOME\Desktop\mcusigner-test\rustBoot\target\debug\rbsigner.exe mcu-image ../boards/sign_images/signed_images/rp2040_bootfw.bin nistp256 ../boards/sign_images/keygen/ecc256.der 1234` (exit code: 101)
Error: command `cargo run mcu-image ../boards/sign_images/signed_images/rp2040_bootfw.bin nistp256 ../boards/sign_images/keygen/ecc256.der 1234` failed, exit code: 101 
error: process didn't exit successfully: `target\debug\xtask.exe rp2040 build-sign-flash rustBoot 1234 1235` (exit code: 1)
```

Version after latest update.
```
nightly-x86_64-pc-windows-msvc (default)
rustc 1.64.0-nightly (d68e7ebc3 2022-07-20)
```

**Comment by ChrisDenton** [comment]
Can you confirm that it still works on old nightly or stable?

**Comment by abhishekdhamale** [comment]
@ChrisDenton thanks for your reply. We found that it was due to wrong configuration in the `config.toml` file not because of `rustup update`. Because of wrong configuration it was generating empty bin file therefore while comparing file timestamp assertion was failing causing main thread to panic. closing this issue now.
