### ISSUE TITLE
Compiler panic with "features": "16bit-mode" on JSON target file

### ISSUE THREAD

**Issue by thomasarmel** [rust-lang/rust#99823]
The issue comes from **"features": "16bit-mode"**

### Code

**.cargo/config.toml**
```
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "i586-rust_dos.json"
rustflags = ["-C", "link-arg=-Tlink.x"]
```

**i586-rust_dos.json**
```
{
    "arch": "x86",
    "cpu": "pentium",
    "data-layout": "e-m:e-p:32:32-f64:32:64-f80:32-n8:16:32-S128",
    "dynamic-linking": false,
    "executables": true,
    "has-rpath": true,
    "is-builtin": false,
    "linker-flavor": "ld.lld",
    "linker": "rust-lld",
    "llvm-target": "i586-unknown-none-code16",
    "max-atomic-width": 64,
    "os": "none",
    "relocation-model": "static",
    "position-independent-executables": false,
    "relro-level": "off",
    "target-c-int-width": "32",
    "target-endian": "little",
    "target-pointer-width": "32",
    "vendor": "unknown",
    "panic-strategy": "abort",
    "disable-redzone": true,
    "features": "16bit-mode"
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (306ba8357 2022-04-05)
binary: rustc
commit-hash: 306ba8357fb36212b7d30efb9eb9e41659ac1445
commit-date: 2022-04-05
host: x86_64-pc-windows-msvc
release: 1.62.0-nightly
LLVM version: 14.0.0
```

### Error output

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C link-arg=-Tlink.x --target \\?\C:\Users\Thomas\Documents\programmation\rust\rust_dos\i586-rust_dos.json --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 101)
  --- stderr
  thread 'rustc' panicked at 'compiler\rustc_codegen_llvm\src\llvm_util.rs:526:9: target feature `16bit-mode` must begin with a `+` or `-`', compiler\rustc_middle\src\util\bug.rs:36:26
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

  note: rustc 1.62.0-nightly (306ba8357 2022-04-05) running on x86_64-pc-windows-msvc

  note: compiler flags: -C link-arg=-Tlink.x --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro

  query stack during panic:
  end of query stack
error: `cargo metadata` exited with an error: error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C link-arg=-Tlink.x --target \\?\C:\Users\Thomas\Documents\programmation\rust\rust_dos\i586-rust_dos.json --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 101)
  --- stderr
  thread 'rustc' panicked at 'compiler\rustc_codegen_llvm\src\llvm_util.rs:526:9: target feature `16bit-mode` must begin with a `+` or `-`', compiler\rustc_middle\src\util\bug.rs:36:26
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

  note: rustc 1.62.0-nightly (306ba8357 2022-04-05) running on x86_64-pc-windows-msvc

  note: compiler flags: -C link-arg=-Tlink.x --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro

  query stack during panic:
  end of query stack

Process finished with exit code 101

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by bjorn3** [comment]
Does it work with `"features": "+16bit-mode"`?

**Comment by thomasarmel** [comment]
Hi,
Yes it works with `"features": "+16bit-mode"`

**Comment by bjorn3** [comment]
In that case changing https://github.com/rust-lang/rust/blob/17659c71ba54471fce65111ff9166d5a00be8107/compiler/rustc_codegen_llvm/src/llvm_util.rs#L603 from a `bug!()` to a fatal error should fix this. Or alternatively it could be validated in `Target::from_json`. There are a whole bunch of other ways you can write an incorrect target spec that may crash the compiler though.
