### ISSUE TITLE
unstable fingerprints for def_ident_span

### ISSUE THREAD

**Issue by edef1c** [rust-lang/rust#99926]
### Meta

Instance of #84970.
I can't reproduce it anymore, so this is all I have.
The codebase I was compiling is available at https://src.unfathomable.blue/tree/ripple/minitrace?h=db58b80ac7d1cc4f16ef1bc21146de9ab6e90302.

`rustc --version --verbose`:
```
rustc 1.60.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.1
```

### Error output

```
error: internal compiler error: encountered incremental compilation error with def_ident_span(minitrace[a978]::{impl#69}::fmt::__BitFlags::NONBLOCK)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p minitrace` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for def_ident_span(minitrace[a978]::{impl#69}::fmt::__BitFlags::NONBLOCK): Some(minitrace/src/main.rs:574:9: 574:17 (#0))', compiler/rustc_query_system/src/query/plumbing.rs:657:9
stack backtrace:
   0:     0x7fa6cd9f382c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9a1e5015c7372de
   1:     0x7fa6cda8d73e - core::fmt::write::h9fe85dc123605e26
   2:     0x7fa6cda156c8 - std::io::Write::write_fmt::hb015af194a783782
   3:     0x7fa6cda279f6 - std::panicking::default_hook::{{closure}}::h5be0c3f8bc5f82d3
   4:     0x7fa6cda2768c - std::panicking::default_hook::h26c625e8da3d12e5
   5:     0x7fa6ce0df326 - rustc_driver[3332337927dbdeef]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7fa6cda28070 - std::panicking::rust_panic_with_hook::h9e5373efea59497b
   7:     0x7fa6cd9f5097 - std::panicking::begin_panic_handler::{{closure}}::h6675d1d897d2268b
   8:     0x7fa6cd9f3954 - std::sys_common::backtrace::__rust_end_short_backtrace::h2eebb466dcccf8e7
   9:     0x7fa6cda27b32 - rust_begin_unwind
  10:     0x7fa6cd9d6463 - core::panicking::panic_fmt::h388cf0442c96c658
  11:     0x7fa6ce09bfc1 - rustc_query_system[e867e22a11718a14]::query::plumbing::incremental_verify_ich_cold
  12:     0x7fa6cf5180f2 - rustc_query_system[e867e22a11718a14]::query::plumbing::incremental_verify_ich::<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, rustc_span[47a2a6ac91c9de99]::def_id::DefId, core[3544d9bd65975cf]::option::Option<rustc_span[47a2a6ac91c9de99]::span_encoding::Span>>
  13:     0x7fa6cf4e83ff - rustc_query_system[e867e22a11718a14]::query::plumbing::try_load_from_disk_and_cache_in_memory::<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, rustc_span[47a2a6ac91c9de99]::def_id::DefId, core[3544d9bd65975cf]::option::Option<rustc_span[47a2a6ac91c9de99]::span_encoding::Span>>
  14:     0x7fa6cf486cfc - rustc_query_system[e867e22a11718a14]::query::plumbing::try_execute_query::<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, rustc_query_system[e867e22a11718a14]::query::caches::DefaultCache<rustc_span[47a2a6ac91c9de99]::def_id::DefId, core[3544d9bd65975cf]::option::Option<rustc_span[47a2a6ac91c9de99]::span_encoding::Span>>>
  15:     0x7fa6cf53a7bf - rustc_query_system[e867e22a11718a14]::query::plumbing::get_query::<rustc_query_impl[10ca4ca612f63241]::queries::def_ident_span, rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt>
  16:     0x7fa6d05dd45d - <rustc_middle[c2021421e45840c5]::ty::assoc::AssocItem>::ident
  17:     0x7fa6cea10cd7 - <rustc_infer[f26e8b4270f267c1]::infer::InferCtxtBuilder>::enter::<(), <rustc_typeck[b093afebe23d5942]::check::inherited::InheritedBuilder>::enter<<rustc_typeck[b093afebe23d5942]::check::wfcheck::CheckWfFcxBuilder>::with_fcx<rustc_typeck[b093afebe23d5942]::check::wfcheck::check_associated_item::{closure#0}>::{closure#0}, ()>::{closure#0}>
  18:     0x7fa6cea8577b - rustc_typeck[b093afebe23d5942]::check::wfcheck::check_associated_item
  19:     0x7fa6cea4652a - rustc_typeck[b093afebe23d5942]::check::wfcheck::check_trait_item
  20:     0x7fa6cf5c33e4 - <rustc_query_system[e867e22a11718a14]::dep_graph::graph::DepGraph<rustc_middle[c2021421e45840c5]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c2021421e45840c5]::ty::context::TyCtxt, rustc_span[47a2a6ac91c9de99]::def_id::LocalDefId, ()>
  21:     0x7fa6cf796bbe - rustc_data_structures[b0cb2db09ec3dd9]::stack::ensure_sufficient_stack::<((), rustc_query_system[e867e22a11718a14]::dep_graph::graph::DepNodeIndex), rustc_query_system[e867e22a11718a14]::query::plumbing::execute_job<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, rustc_span[47a2a6ac91c9de99]::def_id::LocalDefId, ()>::{closure#3}>
  22:     0x7fa6cf484fd7 - rustc_query_system[e867e22a11718a14]::query::plumbing::try_execute_query::<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, rustc_query_system[e867e22a11718a14]::query::caches::DefaultCache<rustc_span[47a2a6ac91c9de99]::def_id::LocalDefId, ()>>
  23:     0x7fa6cf55a397 - rustc_query_system[e867e22a11718a14]::query::plumbing::get_query::<rustc_query_impl[10ca4ca612f63241]::queries::check_trait_item_well_formed, rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt>
  24:     0x7fa6ce892ff3 - <core[3544d9bd65975cf]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[b0cb2db09ec3dd9]::sync::par_for_each_in<&alloc[db4ee42289b85b97]::vec::Vec<rustc_hir[c137df6dafea0ff]::hir::MaybeOwner<&rustc_hir[c137df6dafea0ff]::hir::OwnerInfo>>, <rustc_middle[c2021421e45840c5]::hir::map::Map>::par_visit_all_item_likes<rustc_typeck[b093afebe23d5942]::check::wfcheck::CheckTypeWellFormedVisitor>::{closure#0}>::{closure#0}::{closure#0}> as core[3544d9bd65975cf]::ops::function::FnOnce<()>>::call_once
  25:     0x7fa6cea35fab - <rustc_middle[c2021421e45840c5]::hir::map::Map>::par_visit_all_item_likes::<rustc_typeck[b093afebe23d5942]::check::wfcheck::CheckTypeWellFormedVisitor>
  26:     0x7fa6ce9d5c1a - <rustc_session[f1e368d1df1a28f3]::session::Session>::track_errors::<rustc_typeck[b093afebe23d5942]::check_crate::{closure#5}, ()>
  27:     0x7fa6ce9b9e23 - rustc_typeck[b093afebe23d5942]::check_crate
  28:     0x7fa6ce244f61 - rustc_interface[f501ea23c001522a]::passes::analysis
  29:     0x7fa6cf5f780e - <rustc_query_system[e867e22a11718a14]::dep_graph::graph::DepGraph<rustc_middle[c2021421e45840c5]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[c2021421e45840c5]::ty::context::TyCtxt, (), core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>
  30:     0x7fa6cf7880f9 - rustc_data_structures[b0cb2db09ec3dd9]::stack::ensure_sufficient_stack::<(core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>, rustc_query_system[e867e22a11718a14]::dep_graph::graph::DepNodeIndex), rustc_query_system[e867e22a11718a14]::query::plumbing::execute_job<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, (), core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>::{closure#3}>
  31:     0x7fa6cf4ccb77 - rustc_query_system[e867e22a11718a14]::query::plumbing::try_execute_query::<rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt, rustc_query_system[e867e22a11718a14]::query::caches::DefaultCache<(), core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>>
  32:     0x7fa6cf564060 - rustc_query_system[e867e22a11718a14]::query::plumbing::get_query::<rustc_query_impl[10ca4ca612f63241]::queries::analysis, rustc_query_impl[10ca4ca612f63241]::plumbing::QueryCtxt>
  33:     0x7fa6ce0e0eca - <rustc_interface[f501ea23c001522a]::passes::QueryContext>::enter::<rustc_driver[3332337927dbdeef]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>
  34:     0x7fa6ce135eb1 - rustc_interface[f501ea23c001522a]::interface::create_compiler_and_run::<core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>, rustc_driver[3332337927dbdeef]::run_compiler::{closure#1}>
  35:     0x7fa6ce11a306 - std[a02bfb958047fa04]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f501ea23c001522a]::util::run_in_thread_pool_with_globals<rustc_interface[f501ea23c001522a]::interface::run_compiler<core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>, rustc_driver[3332337927dbdeef]::run_compiler::{closure#1}>::{closure#0}, core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>::{closure#0}, core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>
  36:     0x7fa6ce100b09 - <<std[a02bfb958047fa04]::thread::Builder>::spawn_unchecked_<rustc_interface[f501ea23c001522a]::util::run_in_thread_pool_with_globals<rustc_interface[f501ea23c001522a]::interface::run_compiler<core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>, rustc_driver[3332337927dbdeef]::run_compiler::{closure#1}>::{closure#0}, core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>::{closure#0}, core[3544d9bd65975cf]::result::Result<(), rustc_errors[449b844d74e393a8]::ErrorReported>>::{closure#1} as core[3544d9bd65975cf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:     0x7fa6cda20133 - std::sys::unix::thread::Thread::new::thread_start::h17b4aae352c54ef4
  38:     0x7fa6cd7f9eb2 - start_thread
  39:     0x7fa6cd87c31c - clone3
  40:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0 running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [def_ident_span] looking up span for `<impl at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.3.2/src/lib.rs:433:9: 495:10>::fmt::__BitFlags::NONBLOCK`'s identifier
#1 [check_trait_item_well_formed] checking that `<impl at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.3.2/src/lib.rs:433:9: 495:10>::fmt::__BitFlags::NONBLOCK` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: re-entrant incremental verify failure, suppressing message
```

**Comment by edef1c** [comment]
This __seems__ like a dupe of #95945 to my untrained eye.

**Comment by Enselic** [comment]
Triage: Without a way to reproduce, there is not much that can be done. Not sure if a duplicate. Closing as not reproducible.
